### ISSUE TITLE
[Android] [RN 0.66] TextInput AutoFocus issue when navigating to new screen

### ISSUE THREAD

**Issue by emin93** [react-navigation/react-navigation#10014]
### Current behavior

When navigating using the `Stack.Navigator` to a screen that has a `TextInput` with `autoFocus={true}`, the keyboard shows up quickly and disappears right away.

This only started happening since upgrading to React Native 0.66. It also doesn't happen when it's the initial screen that has that `TextInput`.

![](https://github.com/emin93/react-navigation-autofocus-issue/raw/main/Screen-Recording-2021-10-08-at-08.32.41.gif)

### Expected behavior

After navigating to the new screen the TextInput stays focused.

### Reproduction

https://github.com/emin93/react-navigation-autofocus-issue

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.0.4
| @react-navigation/stack                | 6.0.9
| react-native-safe-area-context         | 3.3.2
| react-native-screens                   | 3.8.0
| react-native-gesture-handler           | 1.10.3
| react-native                           | 0.66.0
| node                                   | v14.17.6
| npm or yarn                            | yarn 1.22.15

**Comment by gabrielbezerra81** [comment]
I'm having this issue without autoFocus. I'm using material top tabs and the first time I focus the input it closes the keyboard and you need to tap again. I tested on both RN 0.65.1 and 0.66. Also its weird that only happens if I have more than 2 top tabs.

**Comment by emin93** [comment]
This is a good thought, but I first updated React Native where the issue started occurring right away, then I also updated React Navigation (`@react-navigation/native` from `6.0.2` to `6.0.4` and `@react-navigation/stack` from `6.0.7` to `6.0.9`) in the hope that this resolves it, but it didn't.

**Comment by Hless** [comment]
Same issue. I have a similar solution to @Einere.:

```
useFocusEffect(() => inputRef.current?.focus());
```

Seems to do the trick, and doesn't rely on requestAnimationFrame or timeouts.

I use these versions:
```
"@react-navigation/native": "^6.0.6"
"@react-navigation/stack": "^6.0.11"
"react-native": "^0.66.3"
  ```

**Comment by WtfLaika** [comment]
I have also same issue, this happens only one time after navigating to screen.

**Comment by sumi-svmx** [comment]
This seems to be issue with `react-native-screens`. Upgrade to `3.10.0` which contains the fix 
PR: https://github.com/software-mansion/react-native-screens/pull/1214
