### ISSUE TITLE
[React Navigation 5] Issue with Color module in Card.tsx

### ISSUE THREAD

**Issue by aditya-keri-betterhalf** [react-navigation/react-navigation#10028]
### Current behavior

In my current Project, I installed react-navigation v5 and ran the app.
The only code I've added in my `App.js` is this starter code :

```
// In App.js in a new project

import * as React from 'react';
import { View, Text } from 'react-native';
import { NavigationContainer } from '@react-navigation/native';
import { createStackNavigator } from '@react-navigation/stack';

function HomeScreen() {
  return (
    <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
      <Text>Home Screen</Text>
    </View>
  );
}

const Stack = createStackNavigator();

function App() {
  return (
    <NavigationContainer>
      <Stack.Navigator>
        <Stack.Screen name="Home" component={HomeScreen} />
      </Stack.Navigator>
    </NavigationContainer>
  );
}

export default App;
```
On both iOS and Android it throws the following error :

![image](https://user-images.githubusercontent.com/90186621/136750236-8ab14e18-a04e-40eb-b62b-482c83d7dfc3.png)

```TypeError: (0, _colors.default) is not a function. (In '(0, _colors.default)(backgroundColor)', '(0, _colors.default)' is undefined)

This error is located at:
    in Card (at CardContainer.tsx:206)
    in CardContainer (at CardStack.tsx:623)
    in RCTView (at View.js:34)
    in View (at Screens.tsx:84)
    in MaybeScreen (at CardStack.tsx:616)
    in RCTView (at View.js:34)
    in View (at Screens.tsx:54)
    in MaybeScreenContainer (at CardStack.tsx:498)
    in CardStack (at StackView.tsx:462)
    in KeyboardManager (at StackView.tsx:458)
    in RNCSafeAreaProvider (at SafeAreaContext.tsx:74)
    in SafeAreaProvider (at SafeAreaProviderCompat.tsx:42)
    in SafeAreaProviderCompat (at StackView.tsx:455)
    in RCTView (at View.js:34)
    in View (at StackView.tsx:454)
    in StackView (at createStackNavigator.tsx:87)
    in StackNavigator (at app/index.js:19)
    in EnsureSingleNavigator (at BaseNavigationContainer.tsx:411)
    in ForwardRef(BaseNavigationContainer) (at NavigationContainer.tsx:91)
    in ThemeProvider (at NavigationContainer.tsx:90)
    in ForwardRef(NavigationContainer) (at app/index.js:18)
    in App (at renderApplication.js:45)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:106)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:132)
    in AppContainer (at renderApplication.js:39)
```

**What I noticed is this:**

When I go inside the Card.tsx file and comment out the following line:
`Color(backgroundColor).alpha() === 0` which is on line 522, it runs correctly. So there's some issue with the `color` library/module that's part of this package.

### Expected behavior

It should build the app correctly.

### Reproduction

https://gist.github.com/aditya-keri-betterhalf/2408a2d730b2dc74a5dd9a2f839ee005

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | ^5.x
| @react-navigation/stack                | ^5.x
| react-native-safe-area-context         | ^3.1.9
| react-native-screens                   | latest
| react-native-gesture-handler           | 1.6.0
| react-native-reanimated                | 1.13.0
| react-native                           | 0.63.3
| node                                   | 14.17.5
| npm or yarn                            | yarn 1.22.11
| @react-navigation/native | NA
| @react-navigation/bottom-tabs | NA
| @react-navigation/drawer | NA
| @react-navigation/material-bottom-tabs | NA
| @react-navigation/material-top-tabs | NA
@react-navigation/stack | ^5.x

**Comment by NgocLe1001** [comment]
same issue. sad
