### ISSUE TITLE
[TS] createNavigationContainerRef create an incompatible ref type

### ISSUE THREAD

**Issue by retyui** [react-navigation/react-navigation#10049]
### Current behavior

```tsx
export const navigationRef = createNavigationContainerRef()

<NavigationContainer
      ref={navigationRef}
      ^^^
      TS2322: Type 'NavigationContainerRefWithCurrent<RootParamList>' is not assignable to type 'Ref<NavigationContainerRef<{}>>'. 

      Type 'NavigationContainerRefWithCurrent<RootParamList>' is not assignable to type 'RefObject<NavigationContainerRef<{}>>'. 
        Types of property 'current' are incompatible. 
          Type 'NavigationContainerRef<RootParamList>' is not assignable to type 'NavigationContainerRef<{}>'. 
            Type 'NavigationContainerRef<RootParamList>' is not assignable to type 'PrivateValueStore<{}, never, {}>'. 
              The types of '''.b' are incompatible between these types. 
              Type 'string' is not assignable to type 'never'. 

>
```

To fix it need to pass an empty ParamList 

```diff
-createNavigationContainerRef()
+createNavigationContainerRef<{}>()
```

### Expected behavior

No TS errors

### Reproduction

...

### Platform

- [ ] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | ~6.0.1
| @react-navigation/bottom-tabs          |^6.0.5
| @react-navigation/drawer               |
| @react-navigation/material-bottom-tabs |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                |~6.0.1
| @react-navigation/native-stack         |^6.0.2
| react-native-safe-area-context         |
| react-native-screens                   |
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           |
| expo                                   |
| node                                   |
| npm or yarn                            |

**Comment by traviswimer** [comment]
I'm running into this same problem after upgrading to v7.

Considering how old this issue is, I assume I probably just happened to make the same mistake.

@retyui is there any chance you happen to remember how you fixed this?

**Comment by traviswimer** [comment]
In case anyone runs into this in the future, here is how I solved my problem.

A simplified version of my code was something like this:

```typescript
const navigationRef = createNavigationContainerRef<MyStackParamList>();

interface NavigationProps extends Partial<React.ComponentProps<typeof NavigationContainer>> {}

export const AppNavigator = function AppNavigator(props: NavigationProps) {
	return (
		<NavigationContainer
			ref={navigationRef}
			{...props}
		>
			<MyStackNav />
		</NavigationContainer>
	);
};
```

I'm not really sure why this became a problem after upgrading, but I was able to fix the error by updating `NavigationProps` to include passing a generic to `NavigationContainer` like this:

```typescript
export interface NavigationProps extends Partial<React.ComponentProps<typeof NavigationContainer<MyStackParamList>>> {}
```
