### ISSUE TITLE
Setting param doesn't update corresponding URL search param when loading a deep link 

### ISSUE THREAD

**Issue by emac3** [react-navigation/react-navigation#10046]
### Current behavior

When setting params for the current screen (`navigation.setParams`) the corresponding URL search params are not updated in the browser address bar.
This happens only when loading the screen directly (as a deep-link).

Caused by [associate path with the route it opens when deep linking](https://github.com/react-navigation/react-navigation/commit/86e64fdcd81a57cf3f3bdab4c9035b52984e7009) since [6.0.0-next.0 (2021-03-09)](https://github.com/react-navigation/react-navigation/blob/main/packages/core/CHANGELOG.md#600-next0-2021-03-09.).

### Expected behavior

Setting param should update corresponding URL search param also when loading a deep link.

### Reproduction

https://github.com/emac3/react-navigation-web-path-issue

### Platform

- [ ] Android
- [ ] iOS
- [X] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/native
- [ ] @react-navigation/stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.0.6
| @react-navigation/stack                | 6.0.11
| react-native-safe-area-context         | 3.2.0
| react-native-screens                   | 3.4.0
| react-native                           | 0.63.2
| expo                                   | 42.0.4
| node                                   | 14.17.6
| npm or yarn                            | yarn

**Comment by hohoaisan** [comment]
I have the same Issue with 
```
"@react-navigation/native": "^6.0.6",
"@react-navigation/native-stack": "^6.2.5",
```

**Comment by awinograd** [comment]
This is the patch I'm using to workaround the bug. No claims/guarantees it doesn't have any adverse / unforseen side effects but it's working for me so far.

[@react-navigation+routers+6.1.0.patch](https://github.com/react-navigation/react-navigation/files/7935539/%40react-navigation%2Brouters%2B6.1.0.txt)

**Comment by NilsBaumgartner1994** [comment]
The problem still occurs
