### ISSUE TITLE
Drawer screens lacking onpress handler

### ISSUE THREAD

**Issue by qualitymanifest** [react-navigation/react-navigation#10059]
### Current behavior

Currently there is no way to pass an `onPress` handler to `Drawer.Screen`. There are many reasons why someone would want to do this, and I've found several people looking for this functionality on stackoverflow. For me personally, some of my `Drawer.Screen` components are `Stack.Navigator`s, and I want to be able to reset the stack when the drawer item is pressed.

I am aware of the ability to pass your drawer navigator a custom `drawerContent` where you can then pass it `DrawerItem`s with `onPress` handlers, and I am already doing that for some things like my logout button. Trying to use that for screens seems pretty cumbersome though, since it seems like then you have to implement all of the navigation and focused logic as well as drawer open/close state. Additionally, you can only place them before or after all of your regular `Drawer.Screen`s that are rendered via `DrawerItemList`

I solved this by adding an optional `onPress` that gets passed the normal `onPress` handler. That way the user can do what they want, and call the default `onPress` before or after (or not at all?)

My best guess as for why this functionality does not currently exist is that it can allow the user to do things that conflict with what react-navigation is doing internally when you tap on a drawer item, which could lead to bugs. If this is the case, maybe it could be called `dangerousOnPress`?

I suppose this is more of a feature request than a bug, but I have a PR incoming for this so it seemed to make more sense to post it here.

### Expected behavior

Drawer.Screens should have an `onPress` handler

### Reproduction

https://example.com

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |^6.0.4|
| @react-navigation/bottom-tabs          |
| @react-navigation/drawer               |^6.1.6|
| @react-navigation/material-bottom-tabs |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                |^6.0.9|
| @react-navigation/native-stack         |
| react-native-safe-area-context         |
| react-native-screens                   |
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           |0.66|
| expo                                   |
| node                                   |16|
| npm or yarn                            |yarn 1.22.5|

**Comment by qualitymanifest** [comment]
Still present in the latest version

**Comment by qualitymanifest** [comment]
Still an issue

**Comment by izone-airstream** [comment]
It's a nice PR indeed.

**Comment by coayscue** [comment]
This is implemented here: https://reactnavigation.org/docs/drawer-navigator/#events

**Comment by AlexRayo** [comment]
I needed to implement a Logout to my Drawer menu as well, so this is what i did: 🚀 

✅ Create a **CustomDrawerContent** where you gonna enclosure your menu items (Avatar, elements, etc...)

```
<DrawerContentScrollView {...props} contentContainerStyle={stylesLocal.drawerContent}>

  <View >
    <Avatar.Image/>

    <DrawerItemList {...props} />
     {/* this DrawerItemList is for each Drawer.Screen menu element*/}

      <DrawerItem
        label="Logout"
        onPress={deleteSession}
        icon={() => <Icon name="logout" color={primary} size={24} />}
      />
  </View>

</DrawerContentScrollView>
```

✅ Now your **Drawer.Navigator**:
 
```
<Drawer.Navigator drawerContent={(props) => <CustomDrawerContent {...props} />}>
  <Drawer.Screen
    name="Home"
    component={BottomNav}
    options={{
    drawerIcon: ({ color }) => (
      <Icon name="home" color={primary} size={24} />
    )
   }}
  />
<Drawer.Navigator/>
```
