### ISSUE TITLE
Error: Requiring unknown module "undefined". If you are sure the module exists, try restarting Metro. You may also want to run `yarn` or `npm install`.

### ISSUE THREAD

**Issue by zhangKunUserGit** [react-navigation/react-navigation#10065]
### Current behavior

(1)Create app and run : 
   1. `npx react-native init MyApp --template react-native-template-typescript`
   2. `yarn add @react-navigation/native @react-navigation/stack @react-navigation/bottom-tabs`

(2)Edit `App.js` 
```
import * as React from 'react';
import {Text, View} from 'react-native';
import {NavigationContainer} from '@react-navigation/native';
import {createBottomTabNavigator} from '@react-navigation/bottom-tabs';

function HomeScreen() {
  return (
    <View style={{flex: 1, justifyContent: 'center', alignItems: 'center'}}>
      <Text>Home!</Text>
    </View>
  );
}

function SettingsScreen() {
  return (
    <View style={{flex: 1, justifyContent: 'center', alignItems: 'center'}}>
      <Text>Settings!</Text>
    </View>
  );
}

const Tab = createBottomTabNavigator();

function MyTabs() {
  return (
    <Tab.Navigator>
      <Tab.Screen name="Home" component={HomeScreen} />
      <Tab.Screen name="Settings" component={SettingsScreen} />
    </Tab.Navigator>
  );
}

export default function App() {
  return (
    <NavigationContainer>
      <MyTabs />
    </NavigationContainer>
  );
}

```

(3) `yarn start and yarn android`

get error:

error stackoverflow link: https://stackoverflow.com/questions/69341877/error-error-requiring-unknown-module-undefined 

![image](https://user-images.githubusercontent.com/13297317/138067976-f8bbaf64-714d-4643-8c9a-f57bb9453064.png)
![image](https://user-images.githubusercontent.com/13297317/138068099-56f17ecc-6bee-4e1a-9025-1b3882c26644.png)

```
 ERROR  Error: Requiring unknown module "undefined". If you are sure the module exists, try restarting Metro. You may also want to run `yarn` or `npm install`.
MaybeScreen@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.myapp&modulesOnly=false&runModule=true:112814:24
RCTView
View
MaybeScreenContainer@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.myapp&modulesOnly=false&runModule=true:112783:23
RNCSafeAreaProvider
SafeAreaProvider@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.myapp&modulesOnly=false&runModule=true:119505:24
SafeAreaProviderCompat@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.myapp&modulesOnly=false&runModule=true:119400:24
BottomTabView@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.myapp&modulesOnly=false&runModule=true:110385:30
BottomTabNavigator@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.myapp&modulesOnly=false&runModule=true:109884:32
MyTabs
EnsureSingleNavigator@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.myapp&modulesOnly=false&runModule=true:116220:24
BaseNavigationContainer@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.myapp&modulesOnly=false&runModule=true:113823:28
ThemeProvider@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.myapp&modulesOnly=false&runModule=true:111043:21
NavigationContainerInner@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.myapp&modulesOnly=false&runModule=true:110823:26
App
RCTView
View
RCTView
View

```

### Expected behavior

success

### Reproduction

https://stackoverflow.com/questions/69341877/error-error-requiring-unknown-module-undefined

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [X] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |
| @react-navigation/bottom-tabs          |
| @react-navigation/drawer               |
| @react-navigation/material-bottom-tabs |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                |
| @react-navigation/native-stack         |
| react-native-safe-area-context         |
| react-native-screens                   |
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           |
| expo                                   |
| node                                   |
| npm or yarn                            |

**Comment by natioskar** [comment]
Hey @zhangKunUserGit did you manage to solve the issue? I'm having the same problem when trying to upgrade react-navigation from 5.x to 6.x, the problem originating in the `@react-navigation/elements` package

I've tried clearing every possible cache of yarn\npm\rn and nothing helped

**Comment by kylefoo** [comment]
@natioskar have you resolved this?

**Comment by natioskar** [comment]
@kylefoo no :( 
still blocked from upgrading to 6.x

**Comment by aklevko** [comment]
I have the same problem. It doesn't allow upgrading to to 6.x

**Comment by aklevko** [comment]
@natioskar is right. This problem in the @react-navigation/elements

**Comment by bhavansh-arora** [comment]
The problem was resolved by installing react-native-screens and restarting the app along with the Metro.

**Comment by natioskar** [comment]
Unfortunately I already have  `react-native-screens` installed in my setup, here is my setup today - 

```js
"@react-navigation/bottom-tabs": "^5.11.11",
"@react-navigation/material-top-tabs": "^5.3.15",
"@react-navigation/native": "^5.9.4",
"@react-navigation/stack": "^5.14.5",
"react-native-screens": "3.10.1",
"react-native-tab-view": "2.16.0"
```

after upgrading all `react-navigation` to 6.x.x, also `react-native-tab-view` to 3.x and following this [migration guide](https://reactnavigation.org/docs/upgrading-from-5.x)

the issue mentioned above still persist, for some reason all the components exported from the `@react-navigation/elements` library is not being loaded

**Comment by waakemeup** [comment]
just ```yarn add react-native-screens``` and it works for me

**Comment by natioskar** [comment]
I've solved the issue on my project eventually, in my `metro.config.js` file I had inlineRequires: **true**, changing it to false solved the issue, I'm not really sure why.

inlineRequires: false uncovered some other issueד in the js tree that I had in the project so I needed to fix them also, cyclic dependencies etc.

**Comment by VeronicaRG** [comment]
same problem here :/

**Comment by lrxiang222** [comment]
same problem here :/

**Comment by lrxiang222** [comment]
I found that this problem is caused by the dependent library of @react-navigation/material-bottom-tabs, please refer to https://reactnavigation.org/docs/material-bottom-tab-navigator/. If you use @react-navigation/material-bottom-tabs must be added, react-native-paper and react-native-vector-icons dependency library. I have the above exception error because the react-native-vector-icons library is not installed; it is used normally after installation.

**Comment by sakura-sakai** [comment]
I solved this problem as follows:

`yarn add react-native-screens`

For IOS:
```
cd ios

rm -rf Pods

pod install
```

**Comment by kamalkrs** [comment]
Just install

yarn add react-native-screens

This works for me.

**Comment by arnnis** [comment]
I had `react-native-screen` already installed. 
It was caused by a circular import for me.

**Comment by Zemuel** [comment]
I had a similar problem with another npm package, then I went to the npm package node module js file. There you will see that the npm package you are using might have other npm packages that make it work so you just have to npm install those packages as well.

**Comment by shaponpal6** [comment]
Run this 
`rm -rf ./node_modules`
then
`yarn` or `npm i`

**Comment by zoomtronic** [comment]
None of the solutions above are working for me..

**Comment by MdImranNazeer1011** [comment]
> 
yeah it's working

**Comment by Muhiddin2007** [comment]
just `npm i` and project work again

**Comment by kyoung-jnn** [comment]
```
rm -rf ./node_modules
yarn
```
or
```
cd ios
rm -rf Pods
pod install 
```
Finally rebuild your app

**Comment by naveen707** [comment]
Just Install the **react-native-screens** 
this is work on me

**Comment by VishalKishwer5** [comment]
`import React, { useRef, useState, useEffect } from 'react';
import { View, Text } from 'react-native';
//import { jsxs as _jsxs } from 'react/jsx-runtime';
import ChatBox from '../../Component/ChatBox/ChatBox';
import Conversation from '../../Component/Coversation/Conversation';
import LogoSearch from '../../Component/LogoSearch/LogoSearch';
import NavIcons from '../../Component/NavIcons/NavIcons';
import { userChats } from '../../api/ChatRequests';
import { io } from 'socket.io-client';
import ChatScreenStyle from './ChatScreenStyle';
const env = require('./env');


const ChatScreen = () => {
  const socket = useRef();

  const [chats, setChats] = useState([]);
  const [onlineUsers, setOnlineUsers] = useState([]);
  const [currentChat, setCurrentChat] = useState(null);
  const [sendMessage, setSendMessage] = useState(null);
  const [receivedMessage, setReceivedMessage] = useState(null);

  // Get the chat in the chat section
  useEffect(() => {
    const user = { _id: 'userId' }; // Replace 'userId' with the actual user ID
    const getChats = async () => {
      try {
        const { data } = await userChats(user._id);
        setChats(data);
      } catch (error) {
        console.log(error);
      }
    };
    getChats();
  }, []);

  // Connect to Socket.io
  useEffect(() => {
    socket.current = io('http://192.168.43.182:8800');
    socket.current.emit('new-user-add', 'userId'); // Replace 'userId' with the actual user ID
    socket.current.on('get-users', (users) => {
      setOnlineUsers(users);
    });
  }, []);

  // Send Message to socket server
  useEffect(() => {
    if (sendMessage !== null) {
      socket.current.emit('send-message', sendMessage);
    }
  }, [sendMessage]);

  // Get the message from socket server
  useEffect(() => {
    socket.current.on('recieve-message', (data) => {
      console.log(data);
      setReceivedMessage(data);
    });
  }, []);

  const checkOnlineStatus = (chat) => {
    const chatMember = chat.members.find((member) => member !== 'userId'); // Replace 'userId' with the actual user ID
    const online = onlineUsers.find((user) => user.userId === chatMember);
    return online ? true : false;
  };

  return (
    <View style={ChatScreenStyle.container}>
      {/* Left Side */}
      <View style={ChatScreenStyle.leftSideChat}>
        <LogoSearch />
        <View style={ChatScreenStyle.chatContainer}>
          <Text style={ChatScreenStyle.heading}>Chats</Text>
          <View style={ChatScreenStyle.chatList}>
            {chats.map((chat) => (
              <View
                key={chat.id}
                onPress={() => {
                  // when click on conversation
                  setCurrentChat(chat);
                }}
              >
                <Conversation
                  data={chat}
                  currentUser="userId" // Replace 'userId' with the actual user ID
                  online={checkOnlineStatus(chat)}
                />
              </View>
            ))}
          </View>
        </View>
      </View>

      {/* Right Side */}
      <View style={ChatScreenStyle.rightSideChat}>
        <View style={styles.rightSideChatInner}>
          <NavIcons />
        </View>
        <ChatBox
          chat={currentChat}
          currentUser="userId" // Replace 'userId' with the actual user ID
          setSendMessage={setSendMessage}
          receivedMessage={receivedMessage}
        />
      </View>
    </View>
  );
};

export default ChatScreen;`
**i still got this error**

**Comment by LekeneCedric** [comment]
I encountered this problem after making major modifications to my imports, to resolve it, I just had to run the **clean task** command to clean the builds artifacts , temp files and other generated files from mobile project and next time rebuild app

In root project directory , run this commands in terminal :

`cd android`

**./gradlew clean** command is used to execute clean task , which remove the build artifacts , temporary files and other generated files from the projects

`./gradlew clean`

After rebuild your project with Metro: `npm start`

**Comment by Leersmaekers** [comment]
I'm also getting a series of many errors, using `react-navigation/drawer`

`
Error: Requiring unknown module "undefined". If you are sure the module exists, try restarting Metro. You may also want to run `yarn` or `npm install`.
`

`
Error: Requiring unknown module "undefined". If you are sure the module exists, try restarting Metro. You may also want to run `yarn` or `npm install`.
`

`
TypeError: Cannot read properties of undefined (reading 'PropsAllowlists')
`

`
Error: Requiring unknown module "undefined". If you are sure the module exists, try restarting Metro. You may also want to run `yarn` or `npm install`.
`


The error is only visible when using the React Native Debugger. If the debugger is not attached, it works as if no errors were present.

**Comment by niyodusengaclement** [comment]
This happened to me also when I upgraded all my dependencies and React Native. So I went through the documentation again, they suggest to install `react-native-screens` and `react-native-safe-area-context`

```
yarn add react-native-screens react-native-safe-area-context
```

Link to the documentation

https://reactnavigation.org/docs/getting-started/

**Comment by go-cristian** [comment]
I tried many things from here, but what it worked for me was to run `npm i --force`

**Comment by go-cristian** [comment]
I tried many things from here, but what it worked for me was to run `npm i --force`
