### ISSUE TITLE
Generated typings for `@react-navigation/drawer` are not compiling

### ISSUE THREAD

**Issue by desfero** [react-navigation/react-navigation#10066]
### Current behavior

There was some change recently to how typescript typings are generated and from `6.1.7` generated types for `drawer` package are not compiling.

```
node_modules/@react-navigation/drawer/lib/typescript/src/utils/useDrawerStatus.d.ts:5:51 - error TS2307: Cannot find module 'packages/routers/lib/typescript/src' or its corresponding type declarations.

5 export default function useDrawerStatus(): import("packages/routers/lib/typescript/src").DrawerStatus;
```

### Expected behavior

No `tsc` error when typescript is checking libs (`--skipLibCheck` is false)

### Reproduction

https://github.com/desfero/react-navigation-drawer-tsc-error-showcase

### Platform

- [ ] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/drawer               | 6.1.8

**Comment by elrony** [comment]
Hi,

Experiencing the same issue, for the time being I resolve it with this patch

```
diff --git a/node_modules/@react-navigation/drawer/lib/typescript/src/utils/useDrawerStatus.d.ts b/node_modules/@react-navigation/drawer/lib/typescript/src/utils/useDrawerStatus.d.ts
index 2477c31..a82d1da 100644
--- a/node_modules/@react-navigation/drawer/lib/typescript/src/utils/useDrawerStatus.d.ts
+++ b/node_modules/@react-navigation/drawer/lib/typescript/src/utils/useDrawerStatus.d.ts
@@ -1,5 +1,6 @@
+import type { DrawerStatus } from '@react-navigation/native';
 /**
  * Hook to detect if the drawer's status in a parent navigator.
  * Returns 'open' if the drawer is open, 'closed' if the drawer is closed.
  */
-export default function useDrawerStatus(): import("packages/routers/lib/typescript/src").DrawerStatus;
+export default function useDrawerStatus(): DrawerStatus;
```

**Comment by yiheinchai** [comment]
Hi I am facing this issue to, anyone knows what is the real underlying cause of this?
