### ISSUE TITLE
 double press bottomTabBar in nested stack. if tab is already focus useScrollToTop and if they are already at the top popToTop

### ISSUE THREAD

**Issue by libi1998** [react-navigation/react-navigation#10071]
### Current behavior

For now it only works if I am in index 0

### Expected behavior

I would like if I press the tab and I am at the bottom of the scrollview it would go up while if I am already at the top it would use the poptotop. this is when I am on another page in the stack.

### Reproduction

https://snack.expo.dev/@libi1998/myvolunteer

### Platform

- [X] Android
- [X] iOS
- [X] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack

### Environment

"dependencies": {
    "@eva-design/eva": "^2.1.1",
    "@react-navigation/bottom-tabs": "^6.0.7",
    "@react-navigation/native": "^6.0.4",
    "@react-navigation/native-stack": "^6.2.2",
    "@ui-kitten/components": "^5.1.1",
    "@ui-kitten/eva-icons": "^5.1.1",
    "axios": "^0.22.0",
    "expo": "~42.0.1",
    "expo-status-bar": "~1.0.4",
    "firebase": "8.2.3",
    "moment": "^2.29.1",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-hook-form": "^7.17.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz",
    "react-native-flash-message": "^0.2.0",
    "react-native-keyboard-aware-scroll-view": "^0.9.4",
    "react-native-safe-area-context": "3.2.0",
    "react-native-screens": "~3.4.0",
    "react-native-svg": "^12.1.1",
    "react-native-web": "~0.13.12"
  },

**Comment by suneeltechnew** [comment]
Hi...

I am also facing same issue. is there any solution for this?
