### ISSUE TITLE
while switching between top bar fastly app crashed in iOS 

### ISSUE THREAD

**Issue by Shahulul** [react-navigation/react-navigation#10083]
### Current behavior

Using @react-navigation/material-top-tabs app getting crashed in iOS. while switching fast between tabs.

### Expected behavior

The app must work without crashing.

### Reproduction

https://github.com/react-navigation/react-navigation.git

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [X] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | ^6.0.2
| @react-navigation/bottom-tabs          | ^6.0.5
| @react-navigation/material-bottom-tabs | ^6.0.5
| @react-navigation/material-top-tabs    |  ^6.0.4
| @react-navigation/stack                | ^6.0.7
| react-native-safe-area-context         | ^3.3.2
| react-native-screens                   | ^3.2.0
| react-native-gesture-handler           | ^1.10.3
| react-native-reanimated                | ^2.3.0-alpha.2
| react-native-pager-view                | ^5.4.6
| react-native                           | ^0.65.1
| node                                   | v14.17.5
| npm or yarn                            | 6.14.14

**Comment by nix23** [comment]
Most probably it happens because this package depends on react-native-tab-view. In our project after react-native-tab-view package upgrade from 0.0.69 to 3.1.1 we had same crash and downgraded back to 0.0.69 which works ok for us.
Most probably it happens because react-native-tab-view >= 3 depends on react-native-pager-view which have this bug with crash: https://github.com/callstack/react-native-pager-view/issues/458.

**Comment by olexh** [comment]
Downgrading `react-native-tab-view` from `3.1.1` to `2.16.0` solve this issue

**Comment by Metroidaron** [comment]
Just Sharing that this is still an ongoing issue, Downgrading did work for me though.

**Comment by Dilip-lohar** [comment]
> Downgrading `react-native-tab-view` from `3.1.1` to `2.16.0` solve this issue

working fine on 2.16.0

**Comment by marsalan72** [comment]
I am also getting the same issue in android fast speed mobile. Press bottom tab in continuously  press then app crash. Any one solution cane handle  this problem

**Comment by emonakov** [comment]
Still an issue. Confirmed on iPad OS 15.3

**Comment by elmcapp** [comment]
I am still having this issue. Maybe its worth opening up a new issues and post example
