### ISSUE TITLE
Android Gesture Enabled crashes when unmounting from SafeAreaView

### ISSUE THREAD

**Issue by florian-milky** [react-navigation/react-navigation#10080]
### Current behavior

On Android when unmounting a focused input from a SafeAreaView (`react-native-safe-area-context`) in a Stack with `gestureEnabled: true` sometimes causes a weird crash:

```
com.facebook.react.uimanager.IllegalViewOperationException: Unable to execute operation dispatchViewManagerCommand: focus on view with tag: 4077, since the view does not exists
```

To get the crash it's necessary to focus the input, unmount it. Sometimes it is needed to do several times in a row in order to get the crash.

### Expected behavior

No crash

### Reproduction

https://snack.expo.dev/@florian-milky/756387
However it does not crash with the online android emulator provided.
Unable to download on my own device.
Same code on my emulator crashes (without expo)

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [x] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [x] @react-navigation/material-top-tabs
- [x] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

    "@react-navigation/bottom-tabs": "^6.0.5",
    "@react-navigation/compat": "^5.3.20",
    "@react-navigation/material-top-tabs": "^6.0.4",
    "@react-navigation/native": "^6.0.2",
    "@react-navigation/stack": "^6.0.7",
"react-native": "0.65.1",
"react-native-gesture-handler": "^1.10.3",
"react-native-safe-area-context": "^3.2.0",
    "react-native-screens": "^3.0.0",
    "react-native-tab-view": "^3.1.1",

**Comment by drash-course** [comment]
We have the same issue

**Comment by theasc** [comment]
I also have this issue on my android devices

**Comment by drash-course** [comment]
Here is some more info about our crash.

```
Fatal Exception: com.facebook.react.uimanager.IllegalViewOperationException: Unable to execute operation dispatchViewManagerCommand: focus on view with tag: 30839, since the view does not exists
       at com.facebook.react.uimanager.UIImplementation.assertViewExists(UIImplementation.java:872)
       at com.facebook.react.uimanager.UIImplementation.dispatchViewManagerCommand(UIImplementation.java:751)
       at com.facebook.react.uimanager.UIManagerModule.dispatchCommand(UIManagerModule.java:727)
       at com.facebook.react.uimanager.UIManagerModule.dispatchViewManagerCommand(UIManagerModule.java:714)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:888)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
       at android.os.Looper.loop(Looper.java:213)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
       at java.lang.Thread.run(Thread.java:929)
```

The error happens when a `<TextInput>` is focused (keyboard open) and you select a different tab, causing the component with the input to unmount. Here is our code for reference, if it helps the react-navigation team.

```
/* DirectSendScreen.js */
class DirectSendScreen extends Component {
    /* ... */
    renderTabBar = () => (
        <View style={s.row}>
            <TouchableOpacity onPress={this.showClientTab}>
                <ClientInfoIcon height="25" width="25" />
            </TouchableOpacity>
            <TouchableOpacity onPress={this.showMessageTab}>
                <MessageIcon height="25" width="25" />
            </TouchableOpacity>
            <TouchableOpacity onPress={this.showVehicleTab}>
                <VehicleInfoIcon height="25" width="25" />
            </TouchableOpacity>
        </View>
    );

    renderActiveTab = () => {
        if (this.activeTab === contactTab) return <DirectSendClientTab />;
        if (this.activeTab === messageTab) return <DirectSendMessageTab />;
        if (this.activeTab === vehicleTab) return <DirectSendVehicleTab />;
        return null;
    };

    render() {
        return (
            <View style={s.screenContainer}>
                {this.renderTabBar()}
                {this.renderActiveTab()}
            </View>
        );
    }
```

The navigation is set like this:

```
/* DirectSendNavigator.js */
const DirectSendStack = createStackNavigator<DirectSendStackParamList>();

export function DirectSendNavigator() {
    return (
        <DirectSendStack.Navigator>
            <DirectSendStack.Screen
                name={DirectSend}
                component={DirectSendScreen}
                options={{
                    title: $t('screen.directSend.headerTitle'),
                    gestureEnabled: false,
                    headerBackTitle: null,
                    headerBackTitleVisible: false,
                    headerTintColor: Colors.text.title,
                    headerStyle: {
                        backgroundColor: Colors.header.background,
                        borderBottomWidth: 0,
                        shadowColor: Colors.separator.default,
                    },
                    headerTitleAlign: 'center',
                }}
            />
        </DirectSendStack.Navigator>
    );
}
```

```
/* RootNavigator.js */
const MainStack = createStackNavigator<MainStackParamList>();

function MainNavigator() {
    return (
        <MainStack.Navigator screenOptions={{ gestureEnabled: false, headerShown: false }}>
            <MainStack.Screen name={Home} component={InterventionNavigator} />
            {/* other screens... */}
            <MainStack.Screen
                name={DirectSendNav}
                component={DirectSendNavigator}
                options={{ presentation: 'modal', gestureEnabled: true }}
            />
        </MainStack.Navigator>
    );
}

function RootNavigator() {
    const routeNameRef = React.useRef();
    return (
        <SafeAreaProvider>
            <NavigationContainer>
                <RootStack.Navigator screenOptions={{ gestureEnabled: false, headerShown: false }}>
                    {/* other screens... */}
                    <RootStack.Screen name={Paired} component={MainNavigator} />
                </RootStack.Navigator>
            </NavigationContainer>
        </SafeAreaProvider>
    );
}

function App() {
    return (
        <View style={Styles.flex1}>
            <RootNavigator />
        </View>
    );
}
```

Please note the `gestureEnabled: true` in RootNavigator. Settting it to `false` makes the error go away. I'm not sure the `<SafeAreaView>` is related to the problem though.

**Comment by harshlakhanpal** [comment]
hey, and solution apart from turning gestureEnabled to false ?

**Comment by oidoug** [comment]
I'm having this issue and cannot go without `gestureEnabled`. Any known workaround?

**Comment by oidoug** [comment]
For us, we got rid of the crash by disabling `keyboardHandlingEnabled={false}` on `Stack.Navigator` props (using r-nav v5 yet).

And for closing keyboards in android, we add a listener to each `Stack.Screen` that have inputs to close the keyboard on leaving:

```
<Stack.Screen
        listeners={{
          transitionStart: ({ data: { closing } }) => {
            closing && Platform.OS === 'android' && Keyboard.dismiss();
          },
        }}
        ...
 />
```

**Comment by danibonilha** [comment]
> For us, we got rid of the crash by disabling `keyboardHandlingEnabled={false}` on `Stack.Navigator` props (using r-nav v5 yet).
> 
> And for closing keyboards in android, we add a listener to each `Stack.Screen` that have inputs to close the keyboard on leaving:
> 
> ```
> <Stack.Screen
>     listeners={{
>         transitionStart: ({ data: { closing } }) => {
>             closing && Platform.OS === 'android' && Keyboard.dismiss();
>         },
>     }}
>     ...
>  />
> ```


Just to give some more context on why this was happening. React navigation has this flag [keyboardHandlingEnabled](https://reactnavigation.org/docs/5.x/stack-navigator/#keyboardhandlingenabled)  which defaults to true and it's [used](https://github.com/react-navigation/react-navigation/blob/2f8cbfcc593d92080b73f9cd5d31f4d1ab22b768/packages/stack/src/views/Stack/CardContainer.tsx#L100) to let the [useKeyboardManager](https://github.com/react-navigation/react-navigation/blob/2f8cbfcc593d92080b73f9cd5d31f4d1ab22b768/packages/stack/src/utils/useKeyboardManager.tsx#L6) know if it should automatically refocus the input in case the screen was not dismissed by gesture for example.

On our project given some user interaction we change what is rendered on the screen, so we navigate to a route that contains an input, then the user taps on something, we render a new component within the `same route`,  the route was not dismissed but the input is not there anymore but React Navigation doesn't know that we don't have an input, so it tries to refocus on a input that doesn't exist. 

```
