### ISSUE TITLE
Back button is hidden after page reload in web

### ISSUE THREAD

**Issue by krivochenko** [react-navigation/react-navigation#10089]
### Current behavior

The app has StackNavigator with two screens HomeScreen and TestScreen. On first screen there is a link for navigate to second one. When I navigate by this link, I can see back button in the header, but if I refresh page by pressing F5 but is hidden.

### Expected behavior

Back button has to be showed every time there is previous URL in browser history.

### Reproduction

https://github.com/krivochenko/navigation

### Platform

- [ ] Android
- [ ] iOS
- [X] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.0.6
| @react-navigation/native-stack         | 6.2.5
| react-native-safe-area-context         | 3.3.2
| react-native                           | 0.64.2
| expo                                   | 43.0.0
| node                                   | 16.8.0
| npm or yarn                            | 7.21.0

**Comment by satya164** [comment]
> Back button has to be showed every time there is previous URL in browser history.

It's impossible to read browser history since there's no API for that. This is not technically feasible.

**Comment by krivochenko** [comment]
But we can subscribe on updates of navigation state, persist it in local storage and restore it when page reload. I already have tried it, but it didn't solve my problem.

If there is no way to solve it, it makes using built-in header useless. We can't allow, that user have possibility to go back only until refresh page. 

Just imagine case then we have online shop with structure: Catalogue->Category->Product. When I navigate to product, I can go back to category by clicking on back button. But if I share link on some product with someone, for come back to category he has click on Catalogue in main menu and from here go to category.

**Comment by krivochenko** [comment]
> > Back button has to be showed every time there is previous URL in browser history.
> 
> It's impossible to read browser history since there's no API for that. This is not technically feasible.

But we can subscribe on updates of navigation state, persist it in local storage and restore it when page reload. I already have tried it, but it didn't solve my problem.

If there is no way to solve it, it makes using built-in header useless. We can't allow, that user have possibility to go back only until refresh page.

Just imagine case then we have online shop with structure: Catalogue->Category->Product. When I navigate to product, I can go back to category by clicking on back button. But if I share link on some product with someone, for come back to category he has click on Catalogue in main menu and from here go to category.

**Comment by satya164** [comment]
> But we can subscribe on updates of navigation state, persist it in local storage and restore it when page reload

That's extremely hacky and also isn't going to work.

> We can't allow, that user have possibility to go back only until refresh page.

User can already go back using the browser's back button.

> Just imagine case

Imagining isn't going to change this since there's no browser API for such behavior. You'll need to work with what's there.

**Comment by lap888** [comment]
the same q

**Comment by Estevete** [comment]
If both screens are under the same stack, you can set an initialRouteName, but in case the navigation is between 3 screens:

A -> B -> C, and you set initialRouteName: A and you make refresh on C, the goBack will bring you to A instead of B, but the goBack button is shown.

**Comment by doertli** [comment]
Is it possible to persist state on each nav change and rehydrate/replay the pushed screens using something like https://reactnavigation.org//docs/state-persistence/ ?

**Comment by joeytwiddle** [comment]
Similarly, we would like to offer the user a back button if they have followed a deep link into the app.

In this case, there is no history to restore. We would like to specify a default route for the back button, if no history exists.

It might be fiddly to specify a default route for every screen. So we'd actually be happy to set a global default route, that would simply take the user to the home screen.

Although I suppose in most apps, taking the user up to the parent route in the tree, might be the most desirable way to go.

**Comment by satya164** [comment]
@joeytwiddle https://reactnavigation.org/docs/configuring-links/#rendering-an-initial-route
