### ISSUE TITLE
[Expo 43] Blank screen when native stack is nested inside material bottom tabs

### ISSUE THREAD

**Issue by Gruak** [react-navigation/react-navigation#10081]
### Current behavior

Using recently released expo 43, when native stacks are nested inside material bottom tabs, navigating between tabs back and forth causes a blank screen to appear.
The identical navigation setup used to work in expo 42.

https://user-images.githubusercontent.com/43846312/138920434-c608da41-218f-48db-bdb9-dd98a2b7821d.mp4

### Expected behavior

I expect the screen content to be properly displayed when navigating, as it is in case of using bottom tabs (not material) and/or stack (not native) or how it used to be in expo 42.

### Reproduction

https://github.com/Gruak/react-navigation-material-bottom-tabs-bug-repro

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [X] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/native-stack
- [ ] @react-navigation/stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.0.6
| @react-navigation/bottom-tabs          | 6.0.9
| @react-navigation/material-bottom-tabs | 6.0.9
| @react-navigation/native-stack         | 6.2.5
| react-native-safe-area-context         | 3.3.2
| react-native-screens                   | 3.8.0
| react-native                           | 0.64.2
| expo                                   | 43.0.1
| node                                   | 14.18.1
| yarn                            | 1.22.15

**Comment by feschm** [comment]
I am experiencing the same bug. 
Thanks for the hint to downgrade to Expo 42 as a quick fix @Gruak

**Comment by AronBe** [comment]
This issue is not exclusive to native stack btw, I face the same with imports from `'@react-navigation/stack'`
```
import { createStackNavigator } from '@react-navigation/stack';
```

**Comment by jjorian** [comment]
I have a same problem when upgrade expo from 42 to 43
After applying the following changes
`import { createMaterialBottomTabNavigator } from '@react-navigation/material-bottom-tabs';`
to
`import { createBottomTabNavigator } from '@react-navigation/bottom-tabs';`
the problem is solved, but the material is definitely more efficient

**Comment by jordann93** [comment]
Same here..
I began with Expo 43 and didn't understand my problem.
Thanks for the "quick fix".

**Comment by mmattax** [comment]
> This issue is not exclusive to native stack btw, I face the same with imports from `'@react-navigation/stack'`

I'm also experiencing this with a regular stack navigator, swapping to SDK42 or switching to the regular bottom tabs makes everything work again.

**Comment by mmattax** [comment]
My packages where I'm seeing this issue. I'm also not seeing this on my iPhone (could this be just Android?)

    "@react-navigation/bottom-tabs": "^5.11.11",
    "@react-navigation/drawer": "^5.12.5",
    "@react-navigation/material-bottom-tabs": "^6.0.9",
    "@react-navigation/material-top-tabs": "^5.3.15",
    "@react-navigation/native": "^5.9.4",
    "@react-navigation/stack": "^5.14.5",

**Comment by mmattax** [comment]
Ok, so I just updated all my react-navigation packages with:

```
yarn upgrade --latest --pattern "@react-navigation"
```

and it seems to be fixed (and I'm still on expo 43)

**Comment by santicna** [comment]
Same problem here, using react native with expo putting a stack screen inside a material bottom tab navigator with the same result.

**Comment by Gruak** [comment]
> Ok, so I just updated all my react-navigation packages with:
> 
> ```
> yarn upgrade --latest --pattern "@react-navigation"
> ```
> 
> and it seems to be fixed (and I'm still on expo 43)

Unfortunately after doing what you said, the issue still occurs. If it is indeed fixed on your end, could you please provide a repo/snack?

**Comment by SistaBossen11** [comment]
Exact same issue for me.  Intially all tabs are rendered, but as soon as i go back to a tab the associated screen will be blank.

Expo version 43 created this issue.

**Comment by SistaBossen11** [comment]
> I have a same problem when upgrade expo from 42 to 43 After applying the following changes `import { createMaterialBottomTabNavigator } from '@react-navigation/material-bottom-tabs';` to `import { createBottomTabNavigator } from '@react-navigation/bottom-tabs';` the problem is solved, but the material is definitely more efficient I spent a lot of time trying different ways like changing the version material-bottom-tabs but nothing changed and the problem still exists.

This worked for me to using Expo 43

**Comment by kendallroth** [comment]
Switching from `@react-navigation/material-bottom-tabs` to `@react-navigation/bottom-tabs` is not an acceptable answer in most cases, as it introduces differences in functionality and design. I would recommend one of the work arounds posted in https://github.com/software-mansion/react-native-screens/issues/1197#issuecomment-993682256, although they are still definitely workarounds!

**Comment by Gruak** [comment]
An acceptable solution was proposed https://github.com/software-mansion/react-native-screens/issues/1197#issuecomment-993682256 so I'm closing the issue. Thanks to everyone who took the time to investigate this.

**Comment by AbeethaHeshan** [comment]
I also face the same issue . I used  Bottom Tabs Navigator  in  react-navigations  .

**Comment by juanjosemayorga** [comment]
what worked for me was passing the property `sceneAnimationEnabled={false}` to the navigator, it looks like it could be a problem with the animation

`<BottomTabAndroid.Navigator sceneAnimationEnabled={false}>`

or also upgrading the react-native-paper version to the last
