### ISSUE TITLE
[Web] Navigation Drawer not closing When pressed outside

### ISSUE THREAD

**Issue by w8ze-devel** [react-navigation/react-navigation#10092]
### Current behavior

Please find below the sample code :   

```
<NavigationContainer>
	<Drawer.Navigator>
	  {isSignedIn ? (
		<Drawer.Screen name="Home" component={Home} options={{ headerShown: false }} />
	  ) : (
		<>
		  <Drawer.Screen name="Administration" component={Administration} />
		  <Drawer.Screen name="Profile" component={Profile} />
		</>
	  )
	  }
	</Drawer.Navigator>
</NavigationContainer>
```

### Expected behavior

Depending on the version of react-native-reanimated, i have different behaviors.

When using version 1.13.3. The project compile fine but i have the issue:  
* I can open the drawer with a DrawerAction
* When clicking outside the drawer (anywhere else in the page), the drawer remains open

When using version 2.2.0 of the react-native-reanimated, the project doesn't even compile. I'll open an issue on the reanimated project for this.

Expected behaviour :  
When clicking outside the drawer space, it is closed.

There was another anomaly in the same subject but the proposed fix didn't help. Here is the related issue https://github.com/react-navigation/react-navigation/issues/7530 

### Reproduction

Here are steps to reproduce : initialize a project with nx and add a web application with the below dependencies. Add the necessary code to create a drawer.

A sample repos with reanimated version 2 where it didn't compile. Please note the project is build with NX.
https://github.com/w8ze-devel/nx-react-native-reanimated-sample

### Platform

- [ ] Android
- [ ] iOS
- [X] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
|  core-js  |  3.6.5  |  
|  install  |  0.13.0  |  
|  npm  |  8.1.1  |  
|  react  | 17.0.2  |  
|  react-dom  | 17.0.2  |  
|  react-native  | 0.66.1  |  
|  react-native-elements  |  3.4.2  |  
|  react-native-gesture-handler  |  1.10.3  |  
|  react-native-ratings  |  8.1.0  |  
|  react-native-reanimated  |  1.13.0  |  
|  react-native-safe-area-context  |  3.2.0  |  
|  react-native-screens  |  3.3.0  |  
|  react-native-svg  | 12.1.1  |  
|  react-native-svg-transformer  | 0.14.3  |  
|  react-native-style-tachyons  |  4.2.0  |  
|  react-native-vector-icons  |  8.1.0  |  
|  @react-navigation/drawer  |  6.1.8  |  
|  @react-navigation/native  |  6.0.6  |  
|  @react-navigation/native-stack  |  6.2.5  |  
|  react-native-web  |  0.17.5  |  
|  regenerator-runtime  | 0.13.7  |  
|  tslib  |  2.0.0

**Comment by w8ze-devel** [comment]
> Hey! Thanks for opening the issue. The issue doesn't seem to contain a link to a repro (a [snack.expo.dev](https://snack.expo.dev) link or link to a GitHub repo under your username).
> 
> Can you provide a [minimal repro](https://stackoverflow.com/help/minimal-reproducible-example) which demonstrates the issue? A repro will help us debug the issue faster. Please try to keep the repro as small as possible and make sure that we can run it without additional setup.

A detailled instructions on how to reproduce is given.


> Couldn't find version numbers for the following packages in the issue:
> 
> * `@react-navigation/bottom-tabs`
> * `@react-navigation/material-bottom-tabs`
> * `@react-navigation/material-top-tabs`
> * `@react-navigation/stack`
> 
> Can you update the issue to include version numbers for those packages? The version numbers must match the format 1.2.3.

I didn't use theses libraries.

**Comment by kg-currenxie** [comment]
Same here :/

**Comment by furkan-harding-scott** [comment]
any solution?

**Comment by noamtamir** [comment]
same here. is downgrading the only solution?

**Comment by liquidvisual** [comment]
I believe this only occurs when devtools are enabled. I think the issue arose from upgrading Reanimated 2 and (possibly) `react-native-devtools-core`. Since it only affects dev, I just created a button in the top right of the drawer that shows only if `__dev__` so I have a way to toggle the menu when devtools are open.

**Comment by noamtamir** [comment]
FYI - For me this occurs in production as well...

**Comment by satya164** [comment]
Can you check if it works for you with `@react-navigation/drawer@6.5.5`?

**Comment by VivekNeel** [comment]
Thanks @satya164 , I can confirm this works on web!

**Comment by liquidvisual** [comment]
I upgraded "@react-navigation/drawer" to 6.6.0 this morning. Unfortunately it's still an issue for me with iOS. 

My react native is `0.67.5`, and not running hermes (on iOS).
