### ISSUE TITLE
Going back (`navigation.goBack()` or hardware button) completely freezing app

### ISSUE THREAD

**Issue by mrousavy** [react-navigation/react-navigation#10096]
### Current behavior

On Android, going back either via pressing the hardware-back button (Navigation Bar) or by using `navigation.goBack()` (or `navigation.pop()`), the screen jumps back and forth and the app goes into an unusable state.

Here's how this looks in my app:

https://user-images.githubusercontent.com/15199031/140042328-22864df7-0590-45ee-b4c3-994fe2a91d0e.mov

The button I'm pressing in the header is simply calling `navigation.goBack()`. The same thing also occurs when I use the default native header, or when I press the back button in the bottom Android Navigation Bar.

I have the following Navigation structure:

```tsx
const Stack = createNativeStackNavigator<MainStack>()

// …

return (
  <NavigationContainer>
    <Stack.Navigator
      screenOptions={{
        headerShown: false,
        contentStyle: styles.background,
      }}>
      <Stack.Screen name="MainTabs" component={MainTabsNavigator} />
      <Stack.Screen name="TokenDetails" getComponent={TokenDetails} />
      <Stack.Screen name="AllTokens" getComponent={AllTokens} />
      <Stack.Screen name="Settings" getComponent={Settings} />
    </Stack.Navigator>
  </NavigationContainer>
)
```

1. I do not use react-freeze
2. I use the native stack from react-native-screens
3. While I use a `Tab` Navigator in the code above, I also tried to not use the Tab Navigator at all (just a single screen) but the problem still occurs.
4. The problem does **not** occur when using the JS stack instead of the native stack.

### Expected behavior

I expect going back to work normally.

### Reproduction

working on it!

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.0.6
| @react-navigation/bottom-tabs          | 6.0.9
| @react-navigation/drawer               |
| @react-navigation/material-bottom-tabs |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                | 6.0.11
| @react-navigation/native-stack         | 6.2.5
| react-native-safe-area-context         | 3.3.2
| react-native-screens                   | 3.9.0
| react-native-gesture-handler           | 1.10.3 
| react-native-reanimated                | 2.3.0-beta.3
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           | 0.66.1
| expo                                   |
| node                                   | v14.18.1
| npm or yarn                            | 1.22.17

**Comment by WoLewicki** [comment]
I believe it is the same issue as this: https://github.com/software-mansion/react-native-reanimated/issues/2460. Unfortunately `Layout Animations` do not yet work correctly with `native-stack` on Android.

**Comment by RayVR** [comment]
@WoLewicki 
I am experiencing very similar issues so I want to add some data points:
1. Not using native-stack
2. Not using Layout Animations in some screens that freeze
3. This issue is observed in some iOS screens as well on goBack or swipe to go back.

**Comment by WoLewicki** [comment]
@RayVR 
1. `react-native-screens` are used in other navigators too, you can disable them per navigator by changing [`detachInactiveScreens`](https://reactnavigation.org/docs/bottom-tab-navigator#detachinactivescreens) to `false`.
2.  Some of the logic of `Layout Animations` is used in all components, regardless of whether you use it explicitly in them or not.
3. On iOS, the fix has already been merged, you can check if it resolves your issue (https://github.com/software-mansion/react-native-reanimated/commit/dd16e580e7a61145369177b9e7e2bc698a1b2068).

**Comment by RayVR** [comment]
@WoLewicki Thank you. That's useful to know.

**Comment by tsvetann** [comment]
@mrousavy I am also experiencing somewhat similar behavior. In my case only the hardware button isn't working anymore. Can this be related to [react-native-screens issue](https://github.com/software-mansion/react-native-screens/pull/1148)

**Comment by WoLewicki** [comment]
@tsvetann what version of `react-native-screens` are you using?

**Comment by tsvetann** [comment]
@WoLewicki `"react-native-screens": "^3.7.2"`

**Comment by WoLewicki** [comment]
FYI, there is a PR linked to the issue in `reanimated` repo that hopefully resolves the issue. It would be great if you could test it and check if it fixes the problem and does not introduce new ones.

**Comment by MarufSharifi** [comment]
The same issue with me

**Comment by aprilmintacpineda** [comment]
I'm experiencing the same issue. This is my first time using native-stack, I previously just use the stack package.

**Comment by Engazan** [comment]
Same here for me only solution is avoiding "presentation" setting => "containedTransparentModal" cuz this is root of problems for me when i have stacked 2+ "containedTransparentModal" screens its randomly freeze only on iOS

looks like only working "presentation" mode for this is "card"

Tested Expo 43, expo 44, but when i "Eject app" somehow it fix this even when using "containedTransparentModal"
