### ISSUE TITLE
When we switching to one screen from top tab (other than first tab) in a same stack, it will automatically redirect to first tab in Android only issue

### ISSUE THREAD

**Issue by Shahulul** [react-navigation/react-navigation#10101]
### Current behavior

 I am using the @react-navigation/material-top-tabs navigator inside a stack navigator. When I navigate to one screen from the tab to another screen in a stack. it will return back to the same screen(Working only when navigating from the first tab). Getting issue only in android. Did anyone face this issue?

### Expected behavior

It must stay in the currently navigated screen

### Reproduction

github.com/react-navigation/react-navigation

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [X] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |^6.0.2
| @react-navigation/bottom-tabs          |^6.0.5
| @react-navigation/material-bottom-tabs |^6.0.5
| @react-navigation/material-top-tabs    |^6.0.4
| @react-navigation/stack                |^6.0.7
| @react-navigation/native-stack         |
| react-native-safe-area-context         | ^3.3.2

| react-native-screens                   | ^3.2.0
| react-native-gesture-handler           |^1.10.3
| react-native-reanimated                |^2.3.0-alpha.2
| react-native-tab-view                  |
| react-native-pager-view                | 5.4.7
| react-native                           |^0.65.1
| node                                   |v14.17.5
| npm or yarn                            |6.14.14

**Comment by Shahulul** [comment]
Version updated but issue still there

**Comment by AGerphiS** [comment]
Currently having the same issue, haven't found a fix yet

**Comment by acenturion** [comment]
I have the same problem, it's happens in Android 8, on android 10 works fine

**Comment by MauroTaliente** [comment]
Son de terror viejo todo roto pa,
como puede ser... tenemos la app en producción, pun te suena el celular a la madrugada que no anda y son ustedes,
pasame el celu pa asi se lo paso a la gente de la empresa y te llaman a vos mr react-navigation.

Att: RompeNuca

**Comment by mehthabux** [comment]
any solution for this ?

**Comment by vanchung1234** [comment]
@mehthabux hi sir, do you have solution for this ?

**Comment by mehthabux** [comment]
no I have remove the @react-navigation/material-top-tabs and make it custom

**Comment by hiendc170196** [comment]
Has anyone fix this issue?

**Comment by hiendc170196** [comment]
I fixed this issue by set these props to options for specific screen that navigate from top tab navigator on stack navigation 
const navigationOptions: StackNavigationOptions = {
  headerShown: false,
  animationEnabled: false,
  detachPreviousScreen: false,
  gestureEnabled: Platform.OS === 'ios',
};

      <MainStack.Screen
        name={SCREEN_THAT_NAVIGATE_FROM_TOP_TAB_NAVIGATOR}
        component={ScreenA}
        options={navigationOptions}
      />

**Comment by Nikualla1** [comment]
@vanchung1234 Adding `detachPreviousScreen: false` to Stack screens I navigated from the Top Tab appeared to resolve the problem for me.

**Comment by anasvemmully** [comment]
Adding `detachPreviousScreen: false` did solved the issue but on navigating to some screen it shows glitch effect (showing random elements from the previous screen on to the current screen in stack navigator) only after `detachPreviousScreen: false` setting it happened!

Is there any options i miss to tackle this problem ?

Iam using Realme 3i Android 11
