### ISSUE TITLE
React navigation v6 not working on Android

### ISSUE THREAD

**Issue by phuocantd** [react-navigation/react-navigation#10102]
### Current behavior

I have a Stack contain 2 Screen (Home and ScreenA)
I navigate from Home screen to ScreenA, then I go back from screen A and the app doesn't work anymore

https://user-images.githubusercontent.com/31690470/140287567-56571c5c-23e7-42f4-afd3-fd55120584b8.mp4

### Expected behavior

I want to it working same on iOS

### Reproduction

https://github.com/phuocantd/NavigationV6

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |  ^6.0.6
| @react-navigation/native-stack         | ^6.2.5
| react-native-safe-area-context         | ^3.3.2
| react-native-screens                   |^3.9.0
| react-native-gesture-handler           |^1.10.3
| react-native-reanimated                |^2.3.0-beta.2
| react-native                           |"0.66.1
| node                                   |v14.18.1
| yarn                            |1.22.10

**Comment by kudiluv** [comment]
I have the same problem. In a clean project everything works correctly, but when I add [reanimated 2](https://docs.swmansion.com/react-native-reanimated/docs/2.2.0/installation) it stops working

**Comment by ticovix** [comment]
I have just same problem when I am using Reanimate 2

**Comment by kelvinpompey** [comment]
@kudiluv Which version of Reanimated 2 are you using? I have experienced this issue with the beta 2.3 but it worked with 2.2.

**Comment by ddikodroid** [comment]
> @kudiluv Which version of Reanimated 2 are you using? I have experienced this issue with the beta 2.3 but it worked with 2.2.

i have the same issue with reanimated 2.3.0-beta3

**Comment by ticovix** [comment]
> @kudiluv Which version of Reanimated 2 are you using? I have experienced this issue with the beta 2.3 but it worked with 2.2.

Hey @kelvinpompey, thanks for the tip, I made downgrade for reanimated 2.2 and it works on android.

![image](https://user-images.githubusercontent.com/12449764/140660231-92d95125-eff6-4081-b834-50ac83251156.png)

I have tried the newest react-navigations versions and oldest, but this downgrade for 2.2 works for me right now.

**Comment by kelvinpompey** [comment]
@vivevio I think 2.2.3 is supposed to support v0.66. 2.2.4 was just released to support v0.67.

**Comment by arasrezaei** [comment]
same here

**Comment by ken-nah** [comment]
Facing the same issue with reanimated 2.3.0-beta3. When I downgraded to **2.2.4** everything worked fine

**Comment by phuocantd** [comment]
> Facing the same issue with reanimated 2.3.0-beta3. When I downgraded to **2.2.4** everything worked fine

It work for me. Thanks
