### ISSUE TITLE
when variable changes, several addListener will be created

### ISSUE THREAD

**Issue by 1061750360** [react-navigation/react-navigation#10119]
### Current behavior

  useEffect(() => {
    navigation.addListener('beforeRemove', (e) => {
      **console.log(hasUnsavedChanges,'dhsajhsk')   // here will be executed many times**
      if (hasUnsavedChanges) {
        return;
      }
      setEventTmp(e)
      e.preventDefault();

      if (isSubmitFlag) {
        navigation.dispatch(e.data.action)
      } else {
        setDialogVisible(true)
      }
    })
  },[navigation, hasUnsavedChanges])   **// I guess when "hasUnsavedChanges" changes, several addListener will be created,**
  **// so console.log(hasUnsavedChanges,'dhsajhsk') will be executed many times**

### Expected behavior

      **console.log(hasUnsavedChanges,'dhsajhsk')   // here will be executed many times**

here should be executed once.

### Reproduction

oh my god

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.0.2
| @react-navigation/stack                | 6.0.7

**Comment by satya164** [comment]
You're not returning the unsubscribe function from the effect and hence not unsubscribing from the listener on cleanup. There's no bug.

**Comment by 1061750360** [comment]
> You're not returning the unsubscribe function from the effect and hence not unsubscribing from the listener on cleanup. There's no bug.

thank you, you said is true.I had resolved it.
