### ISSUE TITLE
Unable to close transparentModal on cardOverlay press

### ISSUE THREAD

**Issue by alex-solovev-spaceiq** [react-navigation/react-navigation#10114]
### Current behavior

Hello there, huge thanks for this library.

I've encountered an odd behaviour while using `transparentModal` and `cardOverlay`. What I'm trying to achieve is pretty simple – close modal by tapping on custom overlay, here is the code from repo that I've created to demonstrate the issue:

```js
import * as React from 'react';
import {View, Text, Button, StyleSheet, Pressable} from 'react-native';
import {NavigationContainer} from '@react-navigation/native';
import {createStackNavigator} from '@react-navigation/stack';

function HomeScreen({navigation: {navigate}}) {
  return (
    <View style={{flex: 1, alignItems: 'center', justifyContent: 'center'}}>
      <Text>Home Screen</Text>
      <Button title="Open Modal" onPress={() => navigate('Modal')} />
    </View>
  );
}

function ModalScreen() {
  return (
    <View
      style={{
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'white',
      }}>
      <Text>Modal Screen</Text>
    </View>
  );
}

function ModalOverlay({navigation: {goBack}}) {
  return (
    <Pressable
      // onPress will never be called 😢 
      onPress={goBack}
      style={[
        StyleSheet.absoluteFillObject,
        {backgroundColor: 'rgba(0,0,0,0.7)'},
      ]}
    />
  );
}

const Stack = createStackNavigator();

function App() {
  return (
    <NavigationContainer>
      <Stack.Navigator>
        <Stack.Screen name="Home" component={HomeScreen} />
        <Stack.Group
          screenOptions={{
            presentation: 'transparentModal',
            cardOverlay: () => <ModalOverlay />,
            cardOverlayEnabled: true,
            cardStyle: {
              width: 500,
              position: 'absolute',
              top: 40,
              right: 40,
              bottom: 40,
              borderRadius: 6,
            },
          }}>
          <Stack.Screen name="Modal" component={ModalScreen} />
        </Stack.Group>
      </Stack.Navigator>
    </NavigationContainer>
  );
}

export default App;

```

Here is the screen recording:

https://user-images.githubusercontent.com/85477836/141097460-6bcdd1da-dab6-41ad-ae90-c85ab103d858.mov

### Expected behavior

I would expect the `onPress` handler to be working, so that if I tap it – the modal would close. 
I know that there is `gestureEnabled` and `gestureDirection` that allows to swipe-close the modal, but I'm looking for the press/tap functionality. Thanks in advance!

### Reproduction

https://github.com/alex-solovev-spaceiq/react-navigation-card-overlay-issue

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | ^6.0.6
| @react-navigation/stack                | ^6.0.11
| react-native-safe-area-context         | ^3.3.2
| react-native-screens                   | ^3.9.0
| react-native-gesture-handler           | ^1.10.3"
| react-native                           | 0.66.2
| node                                   | 16.5.0
| yarn                            | 1.22.15

**Comment by 1280103995** [comment]
If you want to implement a modal, you can refer to: https://reactnavigation.org/docs/stack-navigator/#transparent-modals

**Comment by alex-solovev-spaceiq** [comment]
> If you want to implement a modal, you can refer to: https://reactnavigation.org/docs/stack-navigator/#transparent-modals

Thank you for the suggestion, however it is not an option, because in the project that I'm working on it's a little bit more complicated than the repro I've provided.
Instead of a single modal screen in the `Stack.Group`, we have `Stack.Screen` that contains a `ModalNavigator` – another stack, where one modal can be pushed on top of another. So, because you suggest to put overlay into a screen component – the overlay will be getting more and more darker resulting in a horrible looking UI (it's semi-transparent).

Here is what the structure looks like:
```
Main Navigator
|_ Screen 1
|_ Screen 2
|_ Modal Navigator
   |_ Modal Screen 1
   |_ Modal Screen 2
```

I just had a thought – would combining `detachPreviousScreen` and your approach work? I mean I wonder if it will only detach the previous screen... 🤔 

Let's say I have this stack:
- `Screen 1`
- `Modal Screen 1`
- `Modal Screen 2`

Both modal screens have overlay and if `detachPreviousScreen` is set on `Modal Screen 2` will I still have `Screen 1` there? I need to check this.

**Comment by alex-solovev-spaceiq** [comment]
@1280103995 Any suggestions on how to deal with this limitation?

**Comment by 1280103995** [comment]
> @1280103995关于如何处理此限制的任何建议？

You can take a look at this: https://github.com/colorfy-software/react-native-modalfy

**Comment by alex-solovev** [comment]
> https://github.com/colorfy-software/react-native-modalfy

@1280103995 Unfortunately using another modal library is not an option for me. Because the app supports both mobile and tablet and just some screens need to be presented as a modal on a tablet. That's why the desired result should be achieved using `react-navigation` library.
Currently it's working as expected for me, except for this issue with user not being able to dismiss the screen by tapping on the overlay (for tablet), for the phone standard navigation is used.

**Comment by alex-solovev** [comment]
@1280103995 Simply saying – somehow I need to be able to close the `transparentModal` with custom overlay by tapping the overlay.

**Comment by 1280103995** [comment]
I don’t have any better suggestions, and I don’t know very much about ```transparentModal```. Maybe you can consult the author.

**Comment by rlueder** [comment]
For those looking for a working solution, I was able to get it to work with the following setup:

```
<RootStack.Screen
    component={MyModal}
    name="MyModal"
    options={{
        gestureEnabled: false,
        headerShown: false,
        presentation: 'transparentModal',
    }}
/>
```

And the modal itself (in this example `MyModal` component) you can make it look whatever way you want it but make sure to add a `Pressable` just above all other elements in the modal that will take care of dismissing the modal, the Pressable needs a background fill color (in my case I made it transparent) for the `onPress` to work.

```
<View>
    <Pressable style={[StyleSheet.absoluteFill, {backgroundColor: 'transparent'}]} onPress={navigation.goBack} />
   <View>
        [... any other elements in your modal]
   </View>
</View>
```

**Comment by gaultierq** [comment]
After upgrading to react-navigation 6, I also had to add a Pressable. It was working well on previous version (4 and 5)

**Comment by satya164** [comment]
Closing this since this is already documented https://reactnavigation.org/docs/stack-navigator/#transparent-modals
