### ISSUE TITLE
@react-navigation/elements breaks monorepo setup

### ISSUE THREAD

**Issue by ecklf** [react-navigation/react-navigation#10120]
### Current behavior

This happens when upgrading `bottom-tabs` or `native-stack` to v6, but I assume this would happen to all packages utilizing the new `elements` package. It seems the issue is related to importing `safe-area-context`.

```
 ERROR  TypeError: undefined is not an object (near '.../commonjs/index.js").SafeAreaProviderCom...')

This error is located at:
    in BottomTabView (created by BottomTabNavigator)
    in Unknown (created by BottomTabNavigator)
    in BottomTabNavigator (at App.tsx:27)
    in EnsureSingleNavigator
    in BaseNavigationContainer
    in ThemeProvider
    in NavigationContainerInner (at App.tsx:26)
    in App (at renderApplication.js:50)
    in RCTView (at View.js:32)
    in View (at AppContainer.js:92)
    in RCTView (at View.js:32)
    in View (at AppContainer.js:119)
    in AppContainer (at renderApplication.js:43)
    in app(RootComponent) (at renderApplication.js:60)
```

<img width="548" alt="Screen Shot 2021-11-14 at 11 56 50" src="https://user-images.githubusercontent.com/8146736/141678509-e1f35a7d-b820-45b9-a068-7182076f90ef.png">

### Expected behavior

The example from the documentation to work without errors when upgrading to v6.

https://reactnavigation.org/docs/tab-based-navigation

### Reproduction

https://github.com/ecklf/react-navigation-v6-monorepo-issue

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |6.0.6
| @react-navigation/bottom-tabs          |6.0.9
| @react-navigation/native-stack         |6.2.5
| react-native-safe-area-context         |3.3.2
| react-native-screens                   |3.9.0
| react-native-gesture-handler           |1.10.3
| react-native-reanimated                |2.3.0-beta.3
| react-native                           |0.66.2
| node                                   |16.11.1
| npm or yarn                            |1.22.15

**Comment by satya164** [comment]
There's nothing React Navigation can do here. You need to investigate how to fix your monorepo setup.

**Comment by ecklf** [comment]
> There's nothing React Navigation can do here. You need to investigate how to fix your monorepo setup.

I am not really sure what I can try beside using module resolver for all `react-navigation` packages like here:
https://github.com/react-navigation/react-navigation/issues/10120#issuecomment-968347160

Do you have suggestions on what else I can try?
