### ISSUE TITLE
goBack to previous screen with parameters

### ISSUE THREAD

**Issue by mydesweb** [react-navigation/react-navigation#10125]
### Current behavior

The user can goBack from screen B to screen A using the swipe back gesture or pressing the back button. When this happen I just want to pass from screen B to screen A some parameters like user selected option.

 I use 
`e.preventDefault();` 
and then dispatch an action like 
`        navigation.dispatch(
          CommonActions.navigate({
            name: 'ReturningScreens',
            params: {
              option: 'A',
            },
          }),
        );`
but simply doesn't work this way, I receive an Error
![Simulator Screen Shot - iPhone 12 mini - 2021-11-15 at 12 57 04](https://user-images.githubusercontent.com/5901386/141770121-914cc124-0a68-4b97-b861-17c48c1b3121.png)

### Expected behavior

I would like to have a simple solution like either using navigation.goBack() with parameters or dispatching a POP action with parameters to automatically update the screen A params when coming from screen B

### Reproduction

https://snack.expo.dev/

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [X] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/stack                | 6.0.11
| @react-navigation/native-stack         | 6.2.5

**Comment by satya164** [comment]
You're preventing the action to go back, the dispatching an action to go back, then preventing it, then dispatching it again, and so on...

You need to check which action you want to prevent and which you don't by checking `e.data.action.`
