### ISSUE TITLE
Unexpected character ''

### ISSUE THREAD

**Issue by parice02** [react-navigation/react-navigation#10126]
### Current behavior

When I add: `drawerActiveTintColor`, `drawerInactiveTintColor`, `drawerActiveBackgroundColor`, or `drawerInactiveBackgroundColor` in the `screenOptions` props I get an error saying : `SyntaxError: ... : Unexpected character ''.`

### Expected behavior

Work well

### Reproduction

https://snack.expo.dev/@parice02/getting-started-|-react-navigation

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.0.6
| @react-navigation/drawer               |6.1.8
| @react-navigation/stack                |6.0.11
| react-native-safe-area-context         |3.3.2
| react-native-screens                   |3.8.0
| react-native-gesture-handler           |1.10.2
| react-native-reanimated                |2.2.0
| react-native                           |0.64.2
| expo                                   |43.0.0
| node                                   | 14.18.1
| npm                            | 8.1.1

**Comment by vonovak** [comment]
hi!

what you really have in the snack is this:


<img width="510" alt="Screen Shot 2022-01-08 at 22 44 24" src="https://user-images.githubusercontent.com/1566403/148660987-86ee6591-0d9b-452b-a42f-42c14720cb48.png">


remove those invisible spaces before `:` and you're good to go ;)
