### ISSUE TITLE
Back button is missing on the Web when directly navigating to a URL

### ISSUE THREAD

**Issue by ngokevin** [react-navigation/react-navigation#10134]
### Current behavior

Root
- HomeStack
- - Dashboard
- - Deck

There's a link from Dashboard to Deck.

1. When clicking the link, the Back button is there.
2. Reload
3. The back button is missing and user is stuck on that page.

```jsx
const linking: LinkingOptions<RootStackParamList> = {
  prefixes: [Linking.makeUrl('/')],
  config: {
    screens: {
      Root: {
        screens: {
          home: {
            screens: {
              dashboard: 'dashboard',
              deck: 'deck' 
            },
          },
          settings: 'settings',
        },
      },
      Modal: 'modal'
    }
  }
};

function HomeStackScreen () {
  return (
    <HomeStack.Navigator initialRouteName='dashboard'>
      <HomeStack.Screen name='dashboard' component={HomeScreen} options={{headerShown: false, title: 'Dashboard'}}/>
      <HomeStack.Screen name='deck' component={DeckScreen} options={{title: 'Deck'}} presentation='modal'/>
    </HomeStack.Navigator>
  );
}

// https://reactnavigation.org/docs/bottom-tab-navigator
export default function BottomTabNavigator ({navigation}) {
  return (
    <BottomTab.Navigator
      initialRouteName='home'
      screenOptions={{
        headerShown: false,
     }}>
      <BottomTab.Screen
        name='home'
        component={HomeStackScreen}
        options={({navigation}: RootTabScreenProps<'home'>) => ({
          title: 'Home'
       })}
     />
     />
    </BottomTab.Navigator>
  );
}
```

### Expected behavior

The back button should be there 

- If I am running a webapp that has a link to a profile page for example, I expect a link to go home.
- If it was running Yelp for example, and link to a restaurant, I'd expect a link to go back home from there.

With configuration on the Stacks and the Linking, react-navigation should be able to figure out what's nested screen. Unless my stack configuration is wrong, but I spent all day scouring and this is what is recommended in the documentation. Thanks!

### Reproduction

https://snack.expo.dev/-YzcNrqvf (except Snack doesn't support deep linking)

### Platform

- [ ] Android
- [ ] iOS
- [X] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack

### Environment

Expo CLI 4.13.0 environment info:
    System:
      OS: macOS 11.0.1
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 14.17.6 - ~/.nvm/versions/node/v14.17.6/bin/node
      Yarn: 1.22.17 - ~/.nvm/versions/node/v14.17.6/bin/yarn
      npm: 6.14.15 - ~/.nvm/versions/node/v14.17.6/bin/npm
    IDEs:
      Android Studio: 2020.3 AI-203.7717.56.2031.7784292
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.16.7 => 0.16.7
      expo: ~43.0.2 => 43.0.3
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    "@react-navigation/bottom-tabs": "^6.0.5",
    "@react-navigation/native": "^6.0.2",
    "@react-navigation/native-stack": "^6.1.0",
    npmGlobalPackages:
      expo-cli: 4.13.0
    Expo Workflow: managed

**Comment by ngokevin** [comment]
Workaround: manually specify Header and add a back button for route you want to default to, else pop

**Comment by lap888** [comment]
the same

**Comment by lap888** [comment]
> Workaround: manually specify Header and add a back button for route you want to default to, else pop

details
