### ISSUE TITLE
Android - Full Screen modal does not cover bottom tab bar

### ISSUE THREAD

**Issue by therunbuddy** [react-navigation/react-navigation#10137]
### Current behavior

When opening a modal screen in NativeStackNavigator the screen does not cover the bottom tab bar on Andoird. On iOS is covers the tab bar. 

### Screenshots
Android
![image](https://user-images.githubusercontent.com/77796515/142738789-e7256162-b375-4f23-aae5-fac92a65875f.png)

iOS
![image](https://user-images.githubusercontent.com/77796515/142738798-9e228e2f-5ce8-44d3-b85a-8b8d6e29b8e4.png)

### Expected behavior

The modal screen should cover the bottom tab bar

### Reproduction

https://github.com/software-mansion/react-native-screens/issues/1219

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| react-native                           |  0.66.3        |
| @react-navigation/native               |    6.0.4     |
| @react-navigation/native-stack         |    6.2.5     |
| react-native-screens                   |     3.9.0    |
| react-native-safe-area-context         |     3.3.2    |
| react-native-gesture-handler           |    1.10.3     |
| react-native-reanimated                |    2.2.4     |

**Comment by satya164** [comment]
We recommend rendering modals in the stack navigator at the root and not nested inside other navigators.

https://reactnavigation.org/docs/modal/

**Comment by rumax** [comment]
> We recommend rendering modals in the stack navigator at the root and not nested inside other navigators.
> 
> https://reactnavigation.org/docs/modal/

@satya164 the link you send refers to normal stacks. But how to handle it properly with tabs? I mean https://reactnavigation.org/docs/tab-based-navigation/. Because in case of tabs, "presentation: 'modal'" does not work. And the solution might be to wrap tabs into another stack navigator, but it create more complexity for navigation definition and some screens can be tabs specific.

**Comment by Gregoirevda** [comment]
@satya164 rendering modal at the root fixes the Android issue, but breaks Android native back behaviour

**Comment by desmond132518** [comment]
@rumax I understand ur concern, I also faced the same issue with nested navigator.

**Comment by Pnlvfx** [comment]
same here

**Comment by moulie415** [comment]
The solution for my problem was to use "containedTransparentModal" but the "containedModal" may work for others
