### ISSUE TITLE
Linking config doesn't respect `initialRouteName` after first render

### ISSUE THREAD

**Issue by nandorojo** [react-navigation/react-navigation#10152]
### Current behavior

If you set the `initialRouteName` for a stack inside of linking config, it isn't respected after the first render. Instead, it uses the `initialRouteName` prop from the `Navigator` component (or the 0th-index `Screen` if there isn't an `initialRouteName` defined on the navigator).

### Expected behavior

If I set `initialRouteName` inside of `linking` config, I shouldn't need to also set it on the `Navigator` component.

Consider this linking config. We have a tab navigator with `artistsTab`. It has 2 nested screens.

```tsx
const linking = {
  config: {
    screens: {
      homeTab: '',
      artistsTab: {
        path: 'artists',
        initialRouteName: 'artists'
        screens: {
          artists: '',
          artistDetail: ':slug'
        }
      }
    }
  }
}
```

This is what the stack inside of `artistsTab` looks like:

```tsx
const ArtistsStack = () => (
  <Navigator>
    <Screen name="artist" component={Artist} />
    <Screen name="artists" component={Artists} />
  </Navigator>
)

const TabNavigator = () => (
  <Tabs.Navigator>
    <Tabs.Screen name="homeTab" component={Home} />
    <Tabs.Screen name="artistsTab" component={ArtistsStack} />
  </Tabs.Navigator>
)
```

> Notice that the `artists` screen is _not_ the first artist in `Stack`.

Since I'm defining `initialRouteName` in `linking.config.artistsTab`, I wouldn't expect that it would be necessary to use as a `Navigator` prop. However, if I don't add `initialRouteName` to `Navigator`, then navigating to `/artists` makes the `artists` screen the second screen in the stack, not the initial one.

Given that `initialRouteName` from the linking config is `artists`, I would expect `linkTo('/artists')` to _always_ put the `artists` screen as the first one in the stack.

However, this is not the case.

On the _initial_ render, if I go to `/artists`, then the `artists` screen is correctly the first one on the stack.

However, on subsequent visits to `/artists`, it does not. 

If I do this:

- Open `/artists/1` as the first screen
- Open `/`
- Open `/artists`

Then, it puts `artists` as the second screen. That is, the `artists` screen has a back button, which goes back to the singluar `artist` screen.

### Reproduction

https://snack.expo.dev/@nandorojo/configuring-links-%7C-react-navigation

### Platform

- [ ] Android
- [ ] iOS
- [X] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [x] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

```json
{
  "@react-navigation/bottom-tabs": "^6.0.9",
  "@react-navigation/drawer": "^6.1.8",
  "@react-navigation/native": "^6.0.6",
  "@react-navigation/native-stack": "^6.2.2",
  "@react-navigation/stack": "^6.0.11",
  "expo": "^43.0.0",

  "react-native": "0.64.3",

  "react-native-web": "0.15.6"
}
```
### Workaround

If you set `initialRouteName` on `<Navigator />`, this gets solved. However, given that it is set in `linking`, I think this shouldn't be necessary.

```diff
<Navigator
+ initialRouteName="artists"
>
```

**Comment by nandorojo** [comment]
done @github-actions

**Comment by nandorojo** [comment]
I'm not using those ^

**Comment by satya164** [comment]
I don't think I understand the issue. Can you mention the exact repro steps? The steps in your snack don't seem right, the first step says "Open Post" but there's no such button.

**Comment by nandorojo** [comment]
Sorry, it looks like I changed the screen order in the example from when I wrote the repro steps in the snack comment. The Open Post button doesn't exist until you click around a bit. This was from a while ago and I've since gotten around the issue with a new approach, so I can just close it. Thanks for looking into it @satya164! Appreciate your time.
