### ISSUE TITLE
Hey every one I have got some crash in my app, I actually don't know how to fix it  

### ISSUE THREAD

**Issue by UnySonic** [react-navigation/react-navigation#10158]
### Current behavior

I have got this crash in firebase and actually I don't how to fix it , if someone know something about this crash I will be very grateful

Fatal Exception: com.facebook.react.common.JavascriptException: Error: Looks like you have configured linking in multiple places. This is likely an error since deep links should only be handled in one place to avoid conflicts. Make sure that:
- You are not using both 'linking' prop and 'useLinking'
- You don't have 'useLinking' in multiple components
- You have set 'android:launchMode=singleTask' in the '<activity />' section of the 'AndroidManifest.xml' file to avoid launching multiple instances

This error is located at:
    in NavigationContainer
    in RCTView
    in Unknown
    in SafeAreaView
    in Unknown
    in Connect(Component)
    in PersistGate
    in Provider
    in Unknown
    in RootApp
    in CodePushComponent
    in RCTView
    in Unknown
    in RCTView
    in Unknown
    in AppContainer, js engine: hermes, stack:
anonymous@1:1161969
flushPassiveEffectsImpl@1:178330
anonymous@1:296362
runWithPriority@1:141995
flushPassiveEffects@1:177886
anonymous@1:177830
V@1:295254
w@1:295578
anonymous@1:210195
_callTimer@1:209434
callTimers@1:211271
__callFunction@1:118825
anonymous@1:117312
__guard@1:118270
callFunctionReturnFlushedQueue@1:117270

       at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:83)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
       at android.os.Looper.loop(Looper.java:164)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
       at java.lang.Thread.run(Thread.java:764)

### Expected behavior

App should not crash

### Reproduction

I don't know how to reproduce it, it is error from firebase. Most likely this  happening on Android when someone do it quickly: Android back button -> open app

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |5.9.8
| @react-navigation/bottom-tabs          |5.11.15
| @react-navigation/stack                |5.14.9
| react-native-safe-area-context         |3.3.2
| react-native-reanimated                |2.2.3
| react-native-tab-view                  |3.1.1
| react-native-pager-view                |5.4.7
| react-native                           |0.65.1

**Comment by cjhines** [comment]
Potentially related: https://github.com/react-navigation/react-navigation/issues/10146

**Comment by cjhines** [comment]
> Hey! Thanks for opening the issue. The issue doesn't seem to contain a link to a repro (a [snack.expo.dev](https://snack.expo.dev) link or link to a GitHub repo under your username).
> 
> Can you provide a [minimal repro](https://stackoverflow.com/help/minimal-reproducible-example) which demonstrates the issue? A repro will help us debug the issue faster. Please try to keep the repro as small as possible and make sure that we can run it without additional setup.

If it is related to the issue I linked then a snack isn't going to do anything. You need a real device to memory kill the app.
