### ISSUE TITLE
useNavigation -> navigate causes typeScript error

### ISSUE THREAD

**Issue by mwegener-com** [react-navigation/react-navigation#10166]
### Current behavior

If you use navigation.navigate("screenName") with useNavigation, you get the following typeScript error.
Everything is working fine.

<img width="997" alt="Bildschirmfoto 2021-11-29 um 22 20 44" src="https://user-images.githubusercontent.com/64470126/143952905-fe2fb30b-7623-45fa-89d5-6f620a2671de.png">

### Expected behavior

No Error

### Reproduction

See Code in Screenshot

### Platform

- [ ] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack

### Environment
  "@react-navigation/bottom-tabs": "^6.0.9",
    "@react-navigation/native": "^6.0.6",
    "@react-navigation/native-stack": "^6.1.0",

**Comment by mwegener-com** [comment]
no repo needed

**Comment by mwegener-com** [comment]
> Hey! Thanks for opening the issue. The issue doesn't seem to contain a link to a repro (a [snack.expo.dev](https://snack.expo.dev) link or link to a GitHub repo under your username).
> 
> Can you provide a [minimal repro](https://stackoverflow.com/help/minimal-reproducible-example) which demonstrates the issue? A repro will help us debug the issue faster. Please try to keep the repro as small as possible and make sure that we can run it without additional setup.

no repo needed

**Comment by satya164** [comment]
Closing since this is covered in docs and there are several issues you could find if you searched before opening an issue.
