### ISSUE TITLE
Tab.screen has always re-render when switch tabs

### ISSUE THREAD

**Issue by bumjin1013** [react-navigation/react-navigation#10174]
### Current behavior

I'm using TopTabNavigator from '@react-navigation/material-top-tabs.
When i switch tab screen, the components are re-rendered at once again.

<Tab.screen 
  component={console.log('first component')}
/>
<Tab.screen 
  component={console.log('second component')}
/>
<Tab.screen 
  component={console.log('third component')}
/>

Every time swich tabs, all console logs are executed at once

### Expected behavior

I want prevent re-rerendering,  just render only once

### Reproduction

https://github.com/bumjin1013/node-react-food-delivery.git

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [X] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |
| @react-navigation/bottom-tabs          |
| @react-navigation/drawer               |
| @react-navigation/material-bottom-tabs |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                |
| @react-navigation/native-stack         |
| react-native-safe-area-context         |
| react-native-screens                   |
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           |
| expo                                   |
| node                                   |
| npm or yarn                            |

**Comment by sergeymorkovkin** [comment]
@bumjin1013 We are facing same issue on iOS. Were you able to work around this?

**Comment by Jamal-ReachFirst** [comment]
Facing same issue

**Comment by Jamal-ReachFirst** [comment]
All the screens get rendered while switching b/w tabs.

**Comment by sanduluca** [comment]
Same here. All of the tabs are re-redering when I switch between them

**Comment by williamliangwl** [comment]
same here, facing same issue in both Android + iOS, using the bottom tab https://reactnavigation.org/docs/5.x/bottom-tab-navigator

**Comment by Jamal-ReachFirst** [comment]
Did anyone figure out why this happening???

**Comment by raajnadar** [comment]
Please read this doc -> https://reactnavigation.org/docs/troubleshooting#screens-are-unmountingremounting-during-navigation

If you still have an issue, please give a snack repro that renders a component, not a console.log, in your case console.log is seen as a new change on each render & it is fired every time you switch tab

**Comment by Jamal-ReachFirst** [comment]
Why is this closed?

**Comment by sanduluca** [comment]
Why did you closed it ? @raajnadar 
Too much people report the problem and you still think no one of them didn't read the docs ?

**Comment by raajnadar** [comment]
This issue is open for a long time without a minimal reproducer, you cannot expect maintainers to dig into your codebase to find the bug nor the version are added correctly to see if the issue is solved in the latest versions

@sanduluca why don't you provide a minimal reproducer? I am happy to reopen the issue

**Comment by constantinescu-vlad** [comment]
Here I have a simple tab navigator inside a stack navigator. Whenever I switch tabs I get this re-render:

> StaticContainer
whyDidYouRender.js:690 
{StaticContainer: ƒ}
 'Re-rendered because of props changes:'
whyDidYouRender.js:704 props.route
whyDidYouRender.js:705 different objects that are equal by value. (more info at http://bit.ly/wdyr02)
whyDidYouRender.js:706 
{prev route: {…}}
prev route
: 
{key: 'tabs-1WgYOk1PVEjotvjQYTwqC', name: 'tabs', params: undefined}
[[Prototype]]
: 
Object
 '!==' 
{next route: {…}}
next route
: 
{key: 'tabs-1WgYOk1PVEjotvjQYTwqC', name: 'tabs', params: undefined}
[[Prototype]]
: 
Object

 
```jsx 
const TabNav = createBottomTabNavigator();

const renderTabBarButton = props => {
    return (
        <TouchableOpacity {...props}>
            <Text style={{color: 'red'}}>{props.to}</Text>
        </TouchableOpacity>
    )
}

const TAB_OPTIONS = () => ({
    tabBarButton: renderTabBarButton
})

const TestNavigator = () => {
    return (
        <TabNav.Navigator>
            <TabNav.Screen options={TAB_OPTIONS()} name={'tab1'} component={TestScreen}/>
            <TabNav.Screen options={TAB_OPTIONS()} name={'tab2'} component={TestScreen}/>
        </TabNav.Navigator>
    )
}

const StackNav = createNativeStackNavigator();
const Main = () => {
    return (
        <StackNav.Navigator>
            <StackNav.Screen name={'tabs'} component={TestNavigator}/>
            <StackNav.Screen name={'asd'} component={TestScreen}/>
        </StackNav.Navigator>
    )
}

class App {
  render() {
          return (
              <NavigationContainer>
                  <Main/>
              </NavigationContainer>
          );
  }
}
```

**Comment by okwasniewski** [comment]
> Here I have a simple tab navigator inside a stack navigator. Whenever I switch tabs I get this re-render:

Hey @constantinescu-vlad, 

Why are you passing options as a function? This way every time you are creating a new reference to the returned object. Please replace this:

```js
const TAB_OPTIONS = () => ({
    tabBarButton: renderTabBarButton
})

const TestNavigator = () => {
    return (
        <TabNav.Navigator>
            <TabNav.Screen options={TAB_OPTIONS()} name={'tab1'} component={TestScreen}/>
            <TabNav.Screen options={TAB_OPTIONS()} name={'tab2'} component={TestScreen}/>
        </TabNav.Navigator>
    )
}
```

with: 

```js
const TAB_OPTIONS = {
    tabBarButton: renderTabBarButton
}

const TestNavigator = () => {
    return (
        <TabNav.Navigator>
            <TabNav.Screen options={TAB_OPTIONS} name={'tab1'} component={TestScreen}/>
            <TabNav.Screen options={TAB_OPTIONS} name={'tab2'} component={TestScreen}/>
        </TabNav.Navigator>
    )
}
```

**Comment by constantinescu-vlad** [comment]
> > Here I have a simple tab navigator inside a stack navigator. Whenever I switch tabs I get this re-render:
> 
> Hey @constantinescu-vlad,
> 
> Why are you passing options as a function? This way every time you are creating a new reference to the returned object. Please replace this:
> 
> ```js
> const TAB_OPTIONS = () => ({
>     tabBarButton: renderTabBarButton
> })
> 
> const TestNavigator = () => {
>     return (
>         <TabNav.Navigator>
>             <TabNav.Screen options={TAB_OPTIONS()} name={'tab1'} component={TestScreen}/>
>             <TabNav.Screen options={TAB_OPTIONS()} name={'tab2'} component={TestScreen}/>
>         </TabNav.Navigator>
>     )
> }
> ```
> 
> with:
> 
> ```js
> const TAB_OPTIONS = {
>     tabBarButton: renderTabBarButton
> }
> 
> const TestNavigator = () => {
>     return (
>         <TabNav.Navigator>
>             <TabNav.Screen options={TAB_OPTIONS} name={'tab1'} component={TestScreen}/>
>             <TabNav.Screen options={TAB_OPTIONS} name={'tab2'} component={TestScreen}/>
>         </TabNav.Navigator>
>     )
> }
> ```

[okwasniewski](https://github.com/okwasniewski) hey thanks for the reply. It doesnt matter how I write the tab navigator options. the StaticContainer still re-renders unnecessarily

**Comment by okwasniewski** [comment]
@constantinescu-vlad Can you provide a expo snack with this issue?

**Comment by constantinescu-vlad** [comment]
@okwasniewski ok got it, thank you for your information

**Comment by wilmxre** [comment]
@constantinescu-vlad hey man, did you manage to solve this issue?

**Comment by constantinescu-vlad** [comment]
@wilmxre no, I still get the re-render

**Comment by Jamal-ReachFirst** [comment]
Yes, re-render all tab screens when tab is changed

**Comment by mahbubshaun** [comment]
I'm also facing same issue!

**Comment by Cheizr** [comment]
I had a similar issue, when i switch between two tabs for example, every component was re-rendered.

The problem was that I was passing a Contextprovider as a child of NavigationContainer, i level up my ContextProvider and the re-renders stopped

**Comment by wilmxre** [comment]
yeah, a context provider caused the re-rendering for me too

**Comment by Cheizr** [comment]
> yeah, a context provider caused the re-rendering for me too

Try what i said in my previous comment, that fixed it

**Comment by manhhoang02** [comment]
[screencast-Genymotion-2024-03-29_22.20.49.772.webm](https://github.com/react-navigation/react-navigation/assets/91677571/725ab9c1-0400-4104-97a2-14553229649b)

I don't know if I am facing the same issue as everyone else. I guess yes :)). Please help 🙏

**Comment by FadyBoj** [comment]
> I had a similar issue, when i switch between two tabs for example, every component was re-rendered.
> 
> The problem was that I was passing a Contextprovider as a child of NavigationContainer, i level up my ContextProvider and the re-renders stopped

Yes this solution worked for me too , thanks
