### ISSUE TITLE
Native and function GoBack not working in Android and IOS

### ISSUE THREAD

**Issue by matheusmirandaferreira** [react-navigation/react-navigation#10182]
### Current behavior

> "dependencies": {
    "@expo-google-fonts/open-sans": "^0.2.0",
    "@expo/vector-icons": "^12.0.0",
    "@motify/interactions": "^0.16.1",
    "@react-native-async-storage/async-storage": "~1.15.0",
    "@react-navigation/bottom-tabs": "^6.0.9",
    "@react-navigation/drawer": "^6.1.8",
    "@react-navigation/native": "^6.0.6",
    "@react-navigation/stack": "^6.0.11",
    "axios": "^0.24.0",
    "date-fns": "^2.27.0",
    "expo": "~43.0.2",
    "expo-app-loading": "~1.2.1",
    "expo-font": "~10.0.3",
    "expo-linear-gradient": "~10.0.3",
    "expo-linking": "~2.4.2",
    "expo-location": "~13.0.4",
    "expo-status-bar": "~1.1.0",
    "moti": "^0.16.1",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-hook-form": "^7.20.1",
    "react-is": "^17.0.2",
    "react-native": "0.64.3",
    "react-native-dotenv": "^3.2.0",
    "react-native-gesture-handler": "~1.10.2",
    "react-native-modal": "^13.0.0",
    "react-native-reanimated": "~2.2.0",
    "react-native-render-html": "^6.3.1",
    "react-native-safe-area-context": "3.3.2",
    "react-native-screens": "~3.8.0",
    "react-native-svg": "12.1.1",
    "react-native-toast-message": "^2.0.2",
    "react-native-web": "0.17.1",
    "styled-components": "^5.3.3"
  },

### Expected behavior

When I try use `navigation.goBack()` from `@react-navigation/core` or `@react-navigation/native`, I'm redirect to Home page, the routes is make with `@react-navigation/bottom-tabs` and a custom Header.

### Expected
when backHendler action is active or `navigation.goBack()` is used, back one page in stack

### Reproduction

https://snack.expo.dev/@matheusferreira/calm-edamame

### Platform

- [X] Android
- [x] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [x] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | ^6.0.6
| @react-navigation/bottom-tabs          |^6.0.9
| @react-navigation/stack                |^6.0.11
| @react-navigation/material-bottom-tabs |^6.0.9
|@react-navigation/material-top-tabs |^6.0.6
| react-native                           |0.64.3
| expo                                   |~43.0.2

**Comment by matheusmirandaferreira** [comment]
> Couldn't find version numbers for the following packages in the issue:
> 
> * `@react-navigation/material-bottom-tabs`
> * `@react-navigation/material-top-tabs`
> 
> Can you update the issue to include version numbers for those packages? The version numbers must match the format 1.2.3.

I update issue, can reverify pleace

**Comment by shelzTimesignature** [comment]
i had the same issue and was caused by reanimated@next

**Comment by matheusmirandaferreira** [comment]
Thanks @shelzTimesignature, I didn't realize

**Comment by matheusmirandaferreira** [comment]
I soved with `backBehavior="history"`

`  <Tab.Navigator
      backBehavior="history"`

**Comment by react-one** [comment]
```ts
export default function TabRouter({
  initialRouteName,
  backBehavior = 'firstRoute',
}: TabRouterOptions) {
```

the backBehavior is set by default to `firstRoute`.

This issue should be closed.
