### ISSUE TITLE
react-navigation integration in a react-native sdk or react-native library

### ISSUE THREAD

**Issue by sharifme04** [react-navigation/react-navigation#10187]
### Current behavior

Hi Currently I am working on a react-native SDK for my work. But I am failed to integrate react-navigation (version 6 , also tried version 5) as it has some configuration setup for native. But in the library, I do not have those files. I have used this to create my library `https://reactnative.dev/docs/native-modules-setup`. 

Does anyone have any idea how to integrate react-navigation in a react-native SDK  or react-native library ?

<img width="372" alt="Screenshot 2021-12-08 at 10 02 35 AM" src="https://user-images.githubusercontent.com/24765222/145179652-c4fa0767-93d3-4355-8555-64a831ce4dfd.png">

<img width="418" alt="Screenshot 2021-12-08 at 10 04 37 AM" src="https://user-images.githubusercontent.com/24765222/145179954-ff341e2d-05c3-447f-968d-50bb2e4d06dc.png">
 

### Expected behavior

 react-navigation should work in sdk or library also. 

### Reproduction

https://reactnative.dev/docs/native-modules-setup

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [X] @react-navigation/material-bottom-tabs
- [X] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [X] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |
| @react-navigation/bottom-tabs          |
| @react-navigation/drawer               |
| @react-navigation/material-bottom-tabs |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                |
| @react-navigation/native-stack         |
| react-native-safe-area-context         |
| react-native-screens                   |
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           |
| expo                                   |
| node                                   |
| npm or yarn                            |

**Comment by sharifme04** [comment]
Hi it is not about repository issue. it is general issue. react-navigation is not working when  we tried to use it in a library or SDK instead of app

**Comment by vonovak** [comment]
hello, react navigation depends on some other libraries, as seen in https://reactnavigation.org/docs/getting-started#installing-dependencies-into-a-bare-react-native-project

transitively, if any other package uses react-navigation, it needs to have those dependencies too.

you need to install those deps alongside your sdk or library.

hope this helps :)
