### ISSUE TITLE
Strange history behavior on tab navigator

### ISSUE THREAD

**Issue by fatoldsun00** [react-navigation/react-navigation#10195]
### Current behavior

Hi,

i make  a little snak for explain my purpose

In this (dirty) example i have 4 screen : feed, profile, settings and toto. When i navigate there are only 2 routes that are remain in history : the first (feed) and the last (currently route). The last route overwrite the n-1 route.

An example : try to navigate from feed > profile > settings and go back : we go to feed, but i want return on profile screen.

In my app i had a more complex architecture : stack > tab > stack / tab.screen > screen and i had the same issue.

### Expected behavior

I suppose that history of tab navigator works not as expected, we always have max 2 objects, so the go back button navigate to the initialscreen, always.

I expected that back button go to the last load route.

### Reproduction

https://snack.expo.dev/@bug00/getting-started-|-react-navigation

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |6.0.6
| @react-navigation/bottom-tabs          |6.0.9
| @react-navigation/stack                |6.0.11
| react-native-safe-area-context         |3.3.2
| react-native-screens                   |3.5.0
| react-native-gesture-handler           |1.10.3
| react-native-reanimated                |2.2.0
| react-native                           |0.66.1

**Comment by nschild** [comment]
I'm not sure when this was added, but there is a prop called backBehavior that lets you choose how the back button operates across the history
https://reactnavigation.org/docs/material-top-tab-navigator/#backbehavior

**Comment by fatoldsun00** [comment]
Hi,

backBehavior='order' seems to work.It push all routes visited to history and back button work correctly. Thanks a lot, but the default behavior it s not intuitive, even with backBehavior doc.

By the way : thanks a lot !!!

**Comment by fatoldsun00** [comment]
When a look a littlemore, i can see "firstRoute - return to the first tab (default)". So the doc it s alright, RTFM !! Sorry
