### ISSUE TITLE
Bottom Tabs tabBarLabel focused prop is always true when using a custom text

### ISSUE THREAD

**Issue by silencer07** [react-navigation/react-navigation#10199]
### Current behavior

![Screenshot_20211216-114013_fl360xp](https://user-images.githubusercontent.com/19424606/146304272-068e9e46-1e2c-4e5b-ae87-b32ba38cf503.jpg)

Current behaviour: focused seems to be always true, hence the "home" text is always blue

### Expected behavior

it should be gray

### Reproduction

      const {colors} = useTheme()  

      // rest of code omitted

      <Tab.Screen
        name="HomeNavigator"
        component={HomeNavigator}
        options={{
          // eslint-disable-next-line react/display-name
          tabBarLabel: (focused) => <Text style={{ fontSize: 10, color: focused ? colors.primary : "gray" }}> Home </Text> ,
        }}
      />  

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | "6.0.6" |
| @react-navigation/bottom-tabs          | "6.0.9" |
| @react-navigation/native-stack         | "6.2.5" |

**Comment by vonovak** [comment]
hello, change `tabBarLabel: (focused) =>` to `tabBarLabel: ({focused}) =>`

that should make it work, thanks

**Comment by pavel-genuine** [comment]
@silencer07 
focused should be inside {} curly bracket:
tabBarLabel: ({focused}) => <Text style={{ fontSize: 10, color: focused ? colors.primary : "gray" }}> Home </Text> ,

**Comment by yasodha-r** [comment]
@pavel-genuine
this is not rendered,
  tabBarLabel: ({focused}) => (
      <Text style={{fontSize: 10, color: focused ? 'red' : 'gray'}}>
        Home
      </Text>
    ), 
but this is rendered
  tabBarLabel: ({focused}) => {
      <Text style={[styles.tabBarLabel]}>
        Home
      </Text>;

it accepts only plain string or a plain text component. Not sure why it is not working
