### ISSUE TITLE
useFocusEffect cleanup not immediately fired when navigate to next screen

### ISSUE THREAD

**Issue by akhmadfauzi** [react-navigation/react-navigation#10190]
### Current behavior

For instance I have 2 pages, A and B. These pages implement `useFocusEffect` to load initial data and cleanup, in my case these pages has a task cancellation in the cleanup effect with this issue, the result was not as I expected but somehow it only happens when using the `navigation.navigate`, with the `navigation.goBack` it work as expected. 
From my understanding the cleanup function should immediately fired once the user navigate from page A and B. In the real case, the result quite different. For simple example, I put below:
```
...
// page A
useFocusEffect(
    React.useCallback(() => {
      console.log('Initial load A');
      return () => {
        console.log('Cleanup A');
      };
    }, [])
  );
...

...
//page B
useFocusEffect(
    React.useCallback(() => {
      console.log('Initial load B');
      return () => {
        console.log('Cleanup B');
      };
    }, [])
  );
...
```

The result when user navigate using `navigation.navigate` from A to B:
```
// not as expected
-> Initial load B
-> Cleanup A
```

The result when user navigate using `navigation.goBack` from B to A:
```
// as expected
-> Cleanup B
-> Initial load A
```

In my project, I am using version `5.x` but I also tried using the last version `6.x` the issue still there. The expo sample using version `6.x`

### Expected behavior

When navigate with `navigate.navigation` the cleanup should be fired immediately when 'unmount' in the page A
```
// expected result
-> Cleanup A
-> Initial load B
```

### Reproduction

https://snack.expo.dev/@cucumber/react-navigation-v5

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [X] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [X] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.0.6
| @react-navigation/bottom-tabs          | 6.0.9
| @react-navigation/stack                | 6.0.11
| react-native                           | 0.66.3

**Comment by vonovak** [comment]
hello and thanks for asking. The behavior you're describing is the expected behavior, not a bug

the useFocusEffect is built on top the navigation events https://reactnavigation.org/docs/navigation-events/

if you check out the docs there, they day

> focus - This event is emitted when the screen comes into focus
> blur - This event is emitted when the screen goes out of focus

So what happens when you go from A to B, you see

-> Initial load B - because B has come into focus (this is fired at the beginning of the screen transition animation so only a part of screen B might be visible at this point) and A is still visible at this point!
-> Cleanup A - this happens when the A is fully "hidden", has come out of focus completely

Hope this makes sense, thanks!

**Comment by ericlifs** [comment]
Is there a way of reversing those events? (without adding a setTimeout to the "Initial Load B" event)

Thank you!
