### ISSUE TITLE
Different header height based on device

### ISSUE THREAD

**Issue by poPaTheGuru** [react-navigation/react-navigation#10208]
### Current behavior

Hello!

I am using `react navigation v4` and my `Stack Navigator` have the next `options`:

```
{
    initialRouteName: 'profileScreen',
    defaultNavigationOptions: {
      headerBackImage: () => {
        return (
          <Image
            style={styles.backImage}
            source={backIcon}
          />
        )
      },
      headerBackTitle: null,
      headerBackTitleVisible: true,
      headerStyle: {
        backgroundColor: 'red',
        elevation: 0,
        shadowOpacity: 0,
        borderBottomWidth: 0,
      },
      headerTitleStyle: {
        fontSize: Fonts.large,
        color: Colors.grey_900
      }
    },
    headerMode: 'screen',
    headerLayoutPreset: 'center'
  }
```

My problem is that the `header height` is different from`iPhone 11 OS 15` to `iPhone 13 OS 15`. 

![Simulator Screen Shot - iPhone 11 - 2021-12-21 at 13 00 51](https://user-images.githubusercontent.com/80824203/146919719-6ef2d78d-efb1-40dc-8074-003b1563b2ac.png)
![Simulator Screen Shot - iPhone 13 - 2021-12-21 at 13 00 52](https://user-images.githubusercontent.com/80824203/146919730-76416945-c603-4163-b00c-12b9bb54fdae.png)

The first photo is on `iPhone 11` and the second is on `iPhone13`. As can be seen, on the second the header smaller and on device, the `title` is `right next to the notch`, there is no space between them.

I don't know how this can be a problem, because on `Android` is working as expected too, and my `iOS devices` have the same `OS version`. It doesn't matter if the simulator is opened from `VSC` or `Xcode`.

**The `Stack Navigator` is inside a `Tab Bar Navigator`.**

The project is older and I don't want to change all the navigation version to the newest ones.

### Expected behavior

That the height of header is equal on devices with notch.

### Reproduction

-

### Platform

- [ ] Android
- [X] iOS
- [ ] Web

### Packages

- [ ] react-navigation-drawer
- [X] react-navigation-stack
- [ ] react-navigation-tabs

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| react-navigation                       | ^4.0.10
| react-navigation-stack                 | ^1.10.3
| react-native-screens                   | ^2.0.0-alpha.8
| react-native-gesture-handler           | ^1.5.2
| react-native-reanimated                | ^1.4.0
| react-native-tab-view                  | ^2.10.2
| react-native                           | 0.61.4
| node                                   | 14.18.1
| npm or yarn                            | 6.14.15
|react-navigation-material-bottom-tabs                            | ^2.3.4
|react-navigation-drawer                            | not used
react-navigation-tabs                            | not used

**Comment by yeonwooz** [comment]
I have same problem. 
Is there any update ? 🤔

**Comment by mikkan-39** [comment]
Following, same problem

**Comment by Murphyst** [comment]
Any update on this? We have the same problem.

**Comment by JoeGonzalez0886** [comment]
any update to this issue yet?

**Comment by johelder** [comment]
any update?

**Comment by marcoaras** [comment]
any updates?
