### ISSUE TITLE
undefined is not an object(evaluating '_$$_REQUIRE(_dependencyMap[0], "@react-navigation/core").NavigationActions.init')

### ISSUE THREAD

**Issue by qgao233** [react-navigation/react-navigation#10203]
### Current behavior

I want to mix up redux and react-navigation, but a bug presents after I followed the steps in the internet.

Anyway, I find that maybe the problem is in "getStateForAction" of "@react-navigation/core" by steps debug.

the details can be found in my repository "bugDemo" [readme.md]

the redux config is at "/src/store/index.js"

### Expected behavior

it should be normal, or return null even if "getStateforAction()" can't handle as official docs said.

"https://reactnavigation.org/docs/2.x/custom-routers/#getstateforactionaction-state"

### Reproduction

https://github.com/qgao233/bugDemo/tree/master

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |  "^6.0.6"
| @react-navigation/bottom-tabs          |
| @react-navigation/drawer               |
| @react-navigation/material-bottom-tabs |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                |
| @react-navigation/native-stack         | "^6.2.5"
| react-native-safe-area-context         | "^3.3.2"
| react-native-screens                   | "^3.10.1"
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           | "0.64.0"
| expo                                   |
| node                                   | "12.22.5"
| npm or yarn                            |
| "react-navigation-redux-helpers"|  "^4.0.1",
 |    "react-redux"|  "^7.2.6",
|     "redux"|  "^4.1.2"

**Comment by satya164** [comment]
react-navigation-redux-helpers is deprecated and only works with very old versions as indicated in the README https://github.com/react-navigation/redux-helpers

**Comment by christianwondeson** [comment]
Hey guy , I was using "const playBackSate = useplaybackstate()" for my music player and  it raised the same issue . help me?
