### ISSUE TITLE
Cannot share socket between <Stack.navigator> items

### ISSUE THREAD

**Issue by artstylee** [react-navigation/react-navigation#10205]
### Current behavior

```
const socket = io("http://192.168.0.86:5000/")
const AppFunctions = {socket}

            <TestContext.Provider value={AppFunctions}>
                <NavigationContainer>
                    <Stack.Navigator initialRouteName="pageone">
                        <Stack.Screen name="pageone" component={pageone}/> <--------------------problem here
                        <Stack.Screen name="pagetwo" component={pagetwo}/> <--------------------problem here
                    </Stack.Navigator> 
                </NavigationContainer>
            </TestContext.Provider>
```
i cannot use socket.io instance inside both of these two problem components
im sharing socket instance with context. it can be only usable in one of two components (the second component wont work), disabling socket in one component makes it work in another and vise versa

### Expected behavior

websocket must work?

### Reproduction

[link to files](https://snack.expo.dev/@aptypkaa/funny-cheese)
test version contains of  3 files
app
pageone
pagetwo
it seems impossible to run this on snack

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [X] @react-navigation/native-stack

### Environment

    "@react-native-async-storage/async-storage": "^1.15.14",
    "@react-native-cookies/cookies": "^6.0.11",
    "@react-navigation/bottom-tabs": "^6.0.9",
    "@react-navigation/drawer": "^6.1.8",
    "@react-navigation/native": "^6.0.6",
    "@react-navigation/native-stack": "^6.2.5",
    "react": "17.0.2",
    "react-native": "0.66.4",
    "react-native-flipper": "^0.125.0",
    "react-native-gesture-handler": "^2.1.0",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-reanimated": "^2.3.1",
    "react-native-safe-area-context": "^3.3.2",
    "react-native-screens": "^3.10.1",
    "rn-flipper-async-storage-advanced": "^1.0.4",
    "socket.io-client": "^4.4.0"

**Comment by raajnadar** [comment]
Did you try passing the ref through params??

**Comment by artstylee** [comment]
looks like i solved the issue removing the usefocuseffect and rebuilduing the logic

**Comment by MohamedLamineAllal** [comment]
Should be closed no ??
