### ISSUE TITLE
Syntax Error in types.tsx: Unexpected token ','

### ISSUE THREAD

**Issue by Will-Mann-16** [react-navigation/react-navigation#10209]
### Current behavior

```
SyntaxError: /Users/willmann/Documents/Programming/mannclan-boxing-day-2021-v2/node_modules/@react-navigation/core/src/types.tsx: Unexpected token, expected "," (192:15)

  190 |   navigate<RouteName extends keyof ParamList>(
  191 |     ...args: undefined extends ParamList[RouteName]
> 192 |       ? [screen: RouteName] | [screen: RouteName, params: ParamList[RouteName]]
      |                ^
  193 |       : [screen: RouteName, params: ParamList[RouteName]]
  194 |   ): void;
  195 | 
```

### Expected behavior

To not have a syntax error

### Reproduction

https://github.com/Will-Mann-16/Mannclan-Boxing-Day-2021

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.0.6
| @react-navigation/native-stack         | 6.2.5
| react-native-safe-area-context         | 3.3.2
| react-native-screens                   |3.8.0
| react-native                           | 0.64.3
| expo                                   |43.0.0

**Comment by abosaiftaha** [comment]
Same Problem here

**Comment by stingerdallas** [comment]
Same problem for me as well
![image](https://user-images.githubusercontent.com/84995945/147589545-e9e0d5fb-e693-45bf-bdb3-cf67541d96a4.png)

**Comment by skinnynpale** [comment]
same

**Comment by skinnynpale** [comment]
https://reactnavigation.org/docs/troubleshooting#im-getting-syntaxerror-in-react-navigationxxxxxxtsx-or-syntaxerror-xxxreact-navigationxxxxxxtsx-unexpected-token

**Comment by mojvan** [comment]
You can add @babel/runtime to your devDependencies and re-install your node_modules. It works for me

**Comment by mojvan** [comment]
Update the @babel/core .I hope it help you

**Comment by pslyman** [comment]
> Update the @babel/core .I hope it help you

That fixed things for me. Thank you!

**Comment by Miadatsiory** [comment]
> Upgrade the @babel/core .I hope it help you

this solve for me to

**Comment by Leena-Sharma-rsys** [comment]
hi, 
I am facing similar problem 

export type PathConfigMap<ParamList extends {}> = {
  [RouteName in keyof ParamList]?: NonNullable<
    ParamList[RouteName]
  > extends NavigatorScreenParams<infer T extends {}>
    ? string | PathConfig<T>
    : string | Omit<PathConfig<{}>, 'screens' | 'initialRouteName'>;
};


error: /node_modules/@react-navigation/core/src/types.tsx: Unexpected token, expected "?" (705:52)

React navigation version : 
"@react-navigation/native": "^6.0.8",
    "@react-navigation/native-stack": "^6.9.13",
    "@react-navigation/stack": "^6.1.1",

Babel version before updation: 
 "@babel/core": "^7.18.6",
    "@babel/runtime": "^7.22.6",

Babel version after updation: 
"@babel/core": "^7.23.6",
    "@babel/runtime": "^7.22.6",


I am still facing this issue , please help

**Comment by abramval** [comment]
Hi. I'm getting the same error. Were you able to solve it?

node_modules/@react-navigation/core/lib/typescript/src/types.d.ts:510:120 - error TS1005: '?' expected.

"@react-navigation/native": "^6.1.9",
"@react-navigation/native-stack": "^6.9.17",
"react-native-safe-area-context": "^4.8.2",

"@babel/core": "^7.16.12",
"@babel/runtime": "^7.16.7",
"typescript": "^4.5.5"

**Comment by NightCoderPal** [comment]
> https://reactnavigation.org/docs/troubleshooting#im-getting-syntaxerror-in-react-navigationxxxxxxtsx-or-syntaxerror-xxxreact-navigationxxxxxxtsx-unexpected-token

npm install --save-dev @babel/core 
helped ..
