### ISSUE TITLE
support "maxFontSizeMultiplier" prop 

### ISSUE THREAD

**Issue by malacca** [react-navigation/react-navigation#10219]
### Current behavior

<img width="380" alt="header" src="https://user-images.githubusercontent.com/15194457/147416819-b7514ac9-2460-4ed3-ab35-061a474932eb.png">
<img width="365" alt="tabbar" src="https://user-images.githubusercontent.com/15194457/147416823-b4a383e4-5905-4069-8c98-d8e38b06c8f4.png">

If config `headerBackAllowFontScaling, headerTitleAllowFontScaling, tabBarAllowFontScaling` is `true` and user modifies the system font size, the situation shown above will appear

For `headerTitle` and `tabBarLabel`, I can also solve the problem by customizing components, but `headerBackTitle` and `tabBarBadge` not support customize components, even `tabBarBadge` does not `AllowFontScaling`

So it is particularly necessary to support `maxFontSizeMultiplier` in components that support `AllowFontScaling`

### Expected behavior

support "maxFontSizeMultiplier" prop 

### Reproduction

none

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |
| @react-navigation/bottom-tabs          |
| @react-navigation/drawer               |
| @react-navigation/material-bottom-tabs |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                |
| @react-navigation/native-stack         |
| react-native-safe-area-context         |
| react-native-screens                   |
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           |
| expo                                   |
| node                                   |
| npm or yarn                            |

**Comment by malacca** [comment]
hope `tabBarBadge` support ReactNode, and components support `maxFontSizeMultiplier`  that support `AllowFontScaling` 🙏

**Comment by jpaas** [comment]
It's too bad this was closed after being marked stale 1 month later. You can't create a repro for it because this depends on the OS settings for text size. As soon as it starts to go up from the default, the layout of the badge starts to change. It doesn't really need more style support, it just needs to make sure the badge text prevents scaling.
