### ISSUE TITLE
All TabBarButton (from Tab.Navigator) disappear after keyboard was opened

### ISSUE THREAD

**Issue by smatoox** [react-navigation/react-navigation#10214]
### Current behavior

```const Tab = createBottomTabNavigator();

export const TabNavigation = () => {
  const theme = useContext<ITheme>(ThemeContext);
  return (
    <Tab.Navigator
      screenOptions={() => ({
        unmountOnBlur: true,
        headerShown: false,
        tabBarStyle: {
          backgroundColor: theme.colors.grey1000,
          minHeight: 60,
        },
        tabBarHideOnKeyboard: true,
        tabBarActiveTintColor: theme.colors.grey0,
        tabBarInactiveTintColor: theme.colors.grey0,
        tabBarButton: props => <TabButton {...props} />,
      })}>
      <Tab.Screen name="home" component={HomeScreen} />
      <Tab.Screen name="top-actu-foot" component={TopScreen} />
      <Tab.Screen name="video-foot" component={VideosScreen} />
      <Tab.Screen name="favoris" component={FavoritesScreen} />
      <Tab.Screen name="match-foot" component={MatchesScreen} />
    </Tab.Navigator>
  );
};
```

Initial state (home)
![s1](https://user-images.githubusercontent.com/26866646/147246379-228bd7c3-0708-4002-92df-0e861dc08af0.jpg)

Open menu top right with searchInput
![s2](https://user-images.githubusercontent.com/26866646/147246378-9daaf010-743b-44c6-9357-3d920868b5e8.jpg)

Back to home
![s3](https://user-images.githubusercontent.com/26866646/147246374-df06dc49-7236-4e8e-a006-6f725326dd73.jpg)

When keyboard was opened and I get back to home page, items of `Tab.Navigator` disappeared.
`Tab.Navigator` is empty.

This behavior happens every where after opened keyboard.

### Expected behavior

How to keep Item displayed in Tab.Navigator after keyboard was opened ?

### Reproduction

https://

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native              |  6.0.6
| @react-navigation/bottom-tabs          | 6.0.9
| @react-navigation/material-top-tabs    | 6.0.6
| @react-navigation/stack                | 6.0.11
| @react-navigation/native-stack         | 6.2.5
| @react-navigation/drawer                 | 6.1.8
| @react-navigation/material-bottom-tabs  | 6.0.9
| react-native-safe-area-context         |  3.3.2
| react-native-screens                   | 3.9.0
| react-native-gesture-handler           | 1.10.3
| react-native-tab-view                  | 3.1.1
| react-native-pager-view                |  5.4.8
| react-native                           | 0.66.3
| node                                   | 14.17.0
| yarn                            | 1.21.1

**Comment by smatoox** [comment]
This 2 packages are not used, and without suspense, it did not change anything after adding them.

**Comment by JerakRus** [comment]
@smatoox Hey! We ran into the same problem and couldn't get around it. Did you happen to find a way out?

**Comment by AronBe** [comment]
I have this issue as well. This is some weird interaction between `tabBarHideOnKeyboard` and keyboard opening too quickly after mounting the screen. I tried to reproduce it in a new project but can't. So there must something else playing a role as well. Not sure what though. Have you @smatoox found any solution?

**Comment by choudlet** [comment]
I am seeing this issue as well! Does anyone have a current or working solution?

**Comment by DaryaBog** [comment]
> I am seeing this issue as well! Does anyone have a current or working solution?

Hi, @choudlet! I solved this problem in the following way:
- added state isUseKeyboard 
- for Input, I added the onFocus and onBlur functions (in the onFocus function, I change isUseKeyboard to true; in onBlur, I change it to false)
- in screenOptions I use tabBarHideOnKeyboard: isUseKeyboard

I hope this solution will help you!
