### ISSUE TITLE
drawerIcon on screen options is not working

### ISSUE THREAD

**Issue by thekingrenz23** [react-navigation/react-navigation#10221]
### Current behavior

Setting the ```drawerIcon``` on screen options does not work and it does not even executed at all. By adding a console.log inside the function I confirmed in.

```
import React from 'react';
import {Text, VStack, StatusBar} from 'native-base';
import {HomeScreenProp} from '../bootfile/BootDrawer';
import Ionicons from 'react-native-vector-icons/Ionicons';

const Home = (prop: HomeScreenProp) => {
  React.useLayoutEffect(() => {
    prop.navigation.setOptions({
      drawerIcon: ({focused, size}) => {
        console.log('executed');
        return (
          <Ionicons
            name="ios-home-outline"
            size={size}
            color={focused ? '#7cc' : '#ccc'}
          />
        );
      },
      headerTitle: 'Renz',
    });
  }, [prop.navigation]);

  return (
    <>
      <StatusBar backgroundColor="#3700B3" barStyle="light-content" />
      <VStack>
        <Text>Hello</Text>
      </VStack>
    </>
  );
};

export default Home;
```

![current_behavior](https://user-images.githubusercontent.com/24559541/147520644-9e6176c4-195a-42e3-83ec-f64e13f02ae6.jpg)

### Expected behavior

The drawer icon should be updated to whatever icon passed to the drawerIcon on the screen option

### Reproduction

https://github.com/thekingrenz23/para_mobile/tree/6f6d84d5292c34f38634e205f60fc2fb8d4457f1

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/drawer              | 6.1.8    |
| react-native                                     | 0.66.4   |
| node                                                | 16.13.0 |
| npm                                                 | 8.1.0 |

**Comment by ev3nst** [comment]
I have the same issue.

@react-navigation/drawer: 6.6.0
@react-navigation/native: 6.0.11
@react-navigation/stack: 6.2.2

**Comment by Hosar** [comment]
Same issue here, please provide some guidance

**Comment by leoperez-dev** [comment]
@Hosar  I was also looking into this, to change the default icon for the drawer I believe the only option is to implement it with the headerLeft prop, since in the source for DrawerToggleButton, the image url for the icon is not configurable via props, hope it helps.
