### ISSUE TITLE
Typescript useNavigation hook issue

### ISSUE THREAD

**Issue by chemiadel** [react-navigation/react-navigation#10228]
### Current behavior

I keep getting TypeScript parameter error on navigate function from the useNavigation
and can't find more details of how to use hook to navigate here [ref](https://reactnavigation.org/docs/use-navigation)

![image](https://user-images.githubusercontent.com/26901572/147731981-c8811978-2d15-437d-9fcb-37198127822a.png)

> Argument of type 'string' is not assignable to parameter of type '{ key: string; params?: undefined; merge?: boolean | undefined; } | { name: never; key?: string | undefined; params: never; merge?: boolean | undefined; }'.ts(2345)

### Expected behavior

```
import { useNavigation } from '@react-navigation/native';
...
const navigation = useNavigation()

  React.useEffect(()=>{
      if(!user && !initializing){
        navigation.navigate('Signin') // keeps showing error while I can't find any other alternative
        //  navigation.navigate({key: 'Signin'}) Tried this but it doesn't seems working
      }
  },[user])
```

### Reproduction

https://github.com/react-navigation/react-navigation

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |
| @react-navigation/bottom-tabs          |
| @react-navigation/drawer               |
| @react-navigation/material-bottom-tabs |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                |
| @react-navigation/native-stack         |
| react-native-safe-area-context         |
| react-native-screens                   |
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           |
| expo                                   |
| node                                   |
| npm or yarn                            |

**Comment by raajnadar** [comment]
Read the docs https://reactnavigation.org/docs/typescript/#annotating-usenavigation

**Comment by yujin-noh** [comment]
I solved type Error v6

1. I used global Type RootParamList
```
namespace ReactNavigation {
    interface RootParamList extends RootStackParamList {}
  }
```
 - if you don't want use global type you should useNavigation generic type RootStackParamList
  ex) 
```
...
type NavigationProps = StackNavigationProp<RootStackParamList>

 const navigation = useNavigation<Navigation>

...

```

2. RootStackParamList type
```
export type HomeStackType = {
  Foo: undefined;
  Bar: {userId: number};
};

export type RootStackParamList = {
  InitialScreen: undefined;
  HomeStack: {
    screen?: keyof HomeStackType;
    params?: ValueOf<HomeStackType>;
  };
};
``` 
3. I used 
``` 
const navigation = useNavigation();

const onPress = useCallback(() => {
    navigation.navigate('HomeStack', {screen: Foo})
}, [])

const onNavigate = useCallback(() => {
    navigation.navigate('HomeStack', {screen: Bar, {params: {userId: 1}}})
}, [])

``` 

I'm migration v5 to v6 therefore I need many opinion thanks

**Comment by raajnadar** [comment]
Reference for people who will see this thread in future, react navigation is a navigation library you as a developer need to annotate the methods exported by it, we cannot predict what name you will be used for the navigation & params, whether the params is optional or required.

https://reactnavigation.org/docs/typescript/#annotating-usenavigation

React navigation V6 enables strict type checking, if those red lines bother you disable TS for the project or annotate the methods. The document attached above explains how to annotate the methods and enable all the features offered by typescript.

Related https://github.com/react-navigation/react-navigation/issues/9820#issuecomment-1001437100

**Comment by Canoral** [comment]
Hi there 👋  this is the solution : 

In my App.tsx file, I declare all my routes, screens, and also define the types for the routes. I'm using the React Navigation library.

```
import { NavigationContainer, NavigationProp } from "@react-navigation/native";
import { createNativeStackNavigator } from "@react-navigation/native-stack";
import Home from "./screens/Home";
import { Provider } from "react-redux";
import store from "./redux/store";
import Détails from "./screens/Détails";

export type RootStackParamList = {
  Home: undefined;
  Détails: { pokemonId: string };
};

const Stack = createNativeStackNavigator<RootStackParamList>();

function App() {
  return (
    <Provider store={store}>
      <NavigationContainer>
        <Stack.Navigator initialRouteName="Home">
          <Stack.Screen name="Home" component={Home} />
          <Stack.Screen name="Détails" component={Détails} />
        </Stack.Navigator>
      </NavigationContainer>
    </Provider>
  );
}
export default App;
```

Then, in my Home screen, I use the useNavigate() method from React Navigation and type it like this:

```
function Home() {
  const dispatch = useAppDispatch();
  const navigation = useNavigation<NavigationProp<RootStackParamList>>();
  const pokemons = useAppSelector((state) => state.interaction.pokemons);

  useEffect(() => {
    dispatch(fetchAllPokemons());
  }, [dispatch]);

  return (
    <ScrollView contentInsetAdjustmentBehavior="automatic">
      <View style={styles.viewContainer}>
        {pokemons &&
          pokemons.map((pokemon, index) => (
            <TouchableOpacity
              key={index}
              onPress={() => {
                navigation.navigate("Détails", {
                  pokemonId: pokemon.id.toString(),
                });
              }}
            >

```
I hope this helps! If you have any more questions or need further clarification, feel free to ask.

**Comment by deepbag** [comment]
if you want you can add your routes in RootStackParamList

export type RootStackParamList = {
  [key: string]: undefined;
};
const Stack = createNativeStackNavigator<RootStackParamList>();
const { navigate } = useNavigation<NavigationProp<RootStackParamList>>();
