### ISSUE TITLE
Navigating from a nested material-top-tabs to a material-bottom-tabs doesn't work

### ISSUE THREAD

**Issue by andrei-datcu** [react-navigation/react-navigation#10234]
### Current behavior

Material bottom tabs with two routes:
TopTabs: Material Top tabs with two routes Screen 1 & Screen 2
Screen3 (default)

App starts with Screen2. Navigate to TopTabs. Navigate to Screen 2. Navigate to Screen 3: You'll get a flicker and a navigation back to TopTabs(Screen1)

https://user-images.githubusercontent.com/7924441/147889822-b9ae60e3-bb54-42c4-8388-b380ccc630aa.mp4

### Expected behavior

The navigation should work and you should not get navigated back.

### Other important notes

- Does not repro in expo
- Has surfaced as a regression from https://github.com/callstack/react-native-paper/pull/2985 (In other words: You need `react-native-paper >= 4.11.0` in order to repro
- Even though it is triggered by `react-native-paper` regression I still believe it's an issue with  `react-navigation` or maybe `react-native-tab-view`

I've debugged this a bit and the following occurs:

1. You are in `Screen2`
2. You navigate to `Screen3` in the outer bottom tabs navigator
3. The top tabs `PagerView` gets a layout with `width=height=0` and the native `ViewPager2` will raise an event of page changed with `page index = 0`. That event is the one causing the final and unwanted navigation back to the top tabs screen.

### Reproduction

https://github.com/andrei-datcu/ReactNavigationBug

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [X] @react-navigation/material-bottom-tabs
- [X] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |6.0.6|
| @react-navigation/material-bottom-tabs |6.0.9|
| @react-navigation/material-top-tabs    |6.0.6|
| react-native-safe-area-context         |3.3.2|
| react-native-tab-view                  |3.1.1|
| react-native-pager-view                |5.4.9|
| react-native                           |0.66.4|
| node                                   |16.13.1|
| npm or yarn                            |8.1.2|

**Comment by andrei-datcu** [comment]
Possibly related issue:
https://github.com/callstack/react-native-pager-view/issues/488

**Comment by lwts** [comment]
+1 one, seeing this issue only on Android devices with a Material Top Tabs nested within a Bottom Tab navigator.  Whenever a user is active on a Top Tab index >= 1 (ie not the first one) and then tries to navigate to another Bottom Tab screen, it momentarily opens and then reverts back to the previous Bottom Tab and resets the render.

**Comment by lwts** [comment]
As a temporary fix, within the Bottom Tab navigator setting `detachInactiveScreens` to true on Android devices resolves the issue.

**Comment by descyther** [comment]
Same issue with Material Bottom and Material Top Tabs too. Unable to fix with **detachInactiveScreens** 

Mat Top Tabs 6.1.0
Mat Bottom Tabs 6.0.9

**Comment by descyther** [comment]
[https://media.makeameme.org/created/waiting-for-react.jpg](url)

**Comment by yinshurman** [comment]
+1🙄
exactly same issues

**Comment by vyrotek** [comment]
+1 We're experiencing the same thing with the same top & bottom nested configuration.

The suggested detachPreviousScreen does not appear to work for us.

**Comment by descyther** [comment]
![raw.png](https://user-images.githubusercontent.com/27274367/161863463-cd6381ea-7418-4fd3-9e1c-54b096f4554d.png)

**Comment by JerakRus** [comment]
We are also facing this problem, has anyone found a workaround?

**Comment by mathiasandresen** [comment]
We are stuck with this problem as well, any progress?

**Comment by yinshurman** [comment]
anybody?😅

**Comment by DmytroKlimchuk** [comment]
I has found a workaround: use @react-navigation/bottom-tabs instead @react-navigation/material-bottom-tabs

**Comment by Chandra-Panta-Chhetri** [comment]
Same issue, commenting so I'll be updated on this issue! I have seen this issue being mentioned on StackOverflow & Reddit, no one has the solution :((

**Comment by GaylordP** [comment]
Same :/

**Comment by raajnadar** [comment]
Material bottom tabs issues should be reported on react native paper repository https://github.com/callstack/react-native-paper/labels/BottomNavigation

**Comment by Fcasasherrera** [comment]
Anyone resolve this problem...?
i try all possible solutions but nothing working :C

**Comment by GaylordP** [comment]
Hello @Fcasasherrera ,

This problem is related to react-native-paper, I have investigated a lot but it is beyond my competence : https://github.com/callstack/react-native-paper/issues/3292

Maybe if you support me on this issue we will get an answer ^^

**Comment by Maclay74** [comment]
Good news! I tested it with upcoming v5 on paper and it works perfectly (and animated :3)
The only problem is that I had to patch it a little, because now it exposes theme differently.

So, in package.json set 
`    "react-native-paper": "^5.0.0-rc.4",`

Change 13 line to 
in `node_modules/@react-navigation/material-bottom-tabs/src/views/MaterialBottomTabView.tsx`
to `import { BottomNavigation, MD2DarkTheme as DarkTheme, DefaultTheme } from 'react-native-paper';`

Hope it won't break something else, but for me it's fine so far.

**Comment by GaylordP** [comment]
@Eduanath 

`true` is the default value, so I don't think it solves the problem :/ 

https://reactnavigation.org/docs/stack-navigator/#animationenabled

**Comment by Eduanath** [comment]
> https://reactnavigation.org/docs/stack-navigator/#animationenabled

yeah, exactly.
Just in case you've changed it to `false` for any particular platform, it would cause the issue.

In my case, the problem was this:
`animationEnabled: Platform.OS == "android" && false`

**Comment by janoist1** [comment]
+1

**Comment by okwasniewski** [comment]
Hey, 

I've fixed this issue in paper here: https://github.com/callstack/react-native-paper/issues/3292 

This has been released in the last RC: `react-native-paper@5.0.0-rc.5`

**Comment by satya164** [comment]
Closing since this has been fixed in Paper.

**Comment by topdevwyq** [comment]
Setting animationEnabled={true} inside screenOptions of Stack.Navigator solved the issue for me.
