### ISSUE TITLE
Can't hide tabbar spesific screens on v6

### ISSUE THREAD

**Issue by efec89** [react-navigation/react-navigation#10231]
### Current behavior

I can't hide tabbar on spesific screens.
tabbarStyle: {display:'none'} not working.

### Expected behavior

I want to hide tabbar on spesific screens.

### Reproduction

no

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.0.6
| @react-navigation/bottom-tabs          |  6.0.9
| @react-navigation/native-stack         | 6.2.5
| react-native                           | 0.66.3

**Comment by llaver** [comment]
Try this
```
<Stack.Screen
  name="Home"
  component={HomeContainer}
  options={{
    header: () => {},
    headerShown: false,
  }}
/>
```

**Comment by raajnadar** [comment]
This can be moved to a discussion https://github.com/react-navigation/react-navigation/discussions/10236
