### ISSUE TITLE
redux-integration docs is not accessible

### ISSUE THREAD

**Issue by sasindroid** [react-navigation/react-navigation#10244]
### Current behavior

Accessing the docs in the below link shows a blank page
https://reactnavigation.org/docs/redux-integration

### Expected behavior

Page accessible @
https://reactnavigation.org/docs/redux-integration

### Reproduction

https://reactnavigation.org/docs/redux-integration

### Platform

- [ ] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [X] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |

**Comment by ademarsj** [comment]
Same here, on console its able to see the error.
Browser: Brave Browser (Version 1.33.106 Chromium: 96.0.4664.110 )
OS: Ubuntu 20.04
```
DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node
```

**Comment by vikasacharya16** [comment]
Hi I found in FireFox the page displays for less than a second and vanish. It gives below error

```
DOMException: Node.insertBefore: Child to insert before is not a child of this node main.5ee27e34.js:2:394017
DOMException: Node.insertBefore: Child to insert before is not a child of this node main.5ee27e34.js:2:394017
Uncaught DOMException: Node.insertBefore: Child to insert before is not a child of this node
```
This Github-Actions don't have brain!

**Comment by sasindroid** [comment]
Noticed this is fixed now.
