### ISSUE TITLE
willFocus event not fired when called in useEffect hook

### ISSUE THREAD

**Issue by yeonwooz** [react-navigation/react-navigation#10240]
### Current behavior

willFocus event is not fired when called in `useEffect` hook. 
Here is my code.

```
 useEffect(() => {
    const willFocusSubscription = navigation.addListener('willFocus', () => {
      console.log(1, 'function should be executed')     // not executed
    })

    console.log(2, 'function should be executed')     // executed
    return () => willFocusSubscription.remove()
  }, [])

```

When I tried to fire willFocus event in `componentDidMount` at a class component, it worked fine. 
Is it a bug? 
Or, what should I do to fix it? 

### Expected behavior

I think willFocus event should be fired so that the callback function should be executed.

### Reproduction

none

### Platform

- [X] Android
- [X] iOS
- [ ] Web

### Packages

- [ ] react-navigation-drawer
- [X] react-navigation-stack
- [ ] react-navigation-tabs

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| react-navigation                       | 4.4.4
| react-navigation-tabs                  | 2.11.1
| react-navigation-drawer                | 1.4.0
| react-navigation-stack                 | 1.7.3
| react-native-safe-area-context         | 
| react-native-screens                   | 2.7.0
| react-native-gesture-handler           | 1.6.1
| react-native-reanimated                | 1.8.0
| react-native-tab-view                  |
| react-native                           | 0.63.4
| expo                                   |
| node                                   |
| npm or yarn                            | yarn

**Comment by yeonwooz** [comment]
I just replaced `useEffect` hook with [`useLayoutEffect` Hook. ](https://reactjs.org/docs/hooks-reference.html#uselayouteffect)
And it the willFocus event is fired. 

I still don't understand the reason but maybe it is related to the timing of Dom Mutation... 🤔

**Comment by vonovak** [comment]
hello, seems like you figured out the issue yourself. When you use `useEffect` the `willFocus` event already happened. So because you subscribed for the event after it already happened, you do not receive the callback. 

It seems that using useLayoutEffect is the appropriate solution. 

Thanks! :)

**Comment by yeonwooz** [comment]
> hello, seems like you figured out the issue yourself. When you use `useEffect` the `willFocus` event already happened. So because you subscribed for the event after it already happened, you do not receive the callback.
> 
> It seems that using useLayoutEffect is the appropriate solution.
> 
> Thanks! :)

I will study more on react hook lifecycle.
Thank you!

**Comment by yeonwooz** [comment]
so, 

useEffect hook happens asynchronously and there is a separate useLayoutEffect Hook which happens synchronously (Both happens and done before rendering).
 
Some of DOM events ( such as 'willFocus' ) happens before useEffect but they are guaranteed to happens synchronously with useLayoutEffect. 

By the way, there is ['focus' event ](https://reactnavigation.org/docs/navigation-events/#navigationaddlistener)in React Navigation 6.x.x. This event happens after useEffect hook. 
'focus' event is not written in React Navigation 4.x.x docs but It seems that I can use it in 4.x.x version. 


---
https://github.com/facebook/react/issues/22506
https://reactjs.org/docs/hooks-effect.html
