### ISSUE TITLE
Changes to incorrect tab when navigation to shared screen

### ISSUE THREAD

**Issue by Livijn** [react-navigation/react-navigation#10257]
### Current behavior

I am currently experiencing an issue when navigating to a shared screen. The strange thing is that this **only happens** in the header. ~~I am also experiencing a weird glitch in the header. It seems like the safe area is delayed. Not sure if these are related, and if they aren't, this issue should focus on the tab navigation.~~

Here is a mapping over the navigation:
- RootStack
  - LoginScreen
  - TabNavigator
    - HomeStackNavigator
      - Feed
      - Profile
    - SearchStackNavigator
      - Browse
      - Profile

In the header I have a couple of buttons that are the same, so I have a component that uses `useNavigation`. I've also tried passing down the `navigation` from the respective Stacks.
```js

export default function UserButtons() {
  const navigation = useNavigation();

  return (
    <View style={tw('flex-row items-center')}>
      <TouchableOpacity
        onPress={() => {
            navigation.navigate('UserProfile', {
              username: userState.user!.username,
            });
        }}
      >
        <FaIcon icon="user" />
      </TouchableOpacity>
      // ... etc
    </View>
  );
}
```

Videos:
- ~~[Glitch in the header](https://imgur.com/a/uF2wiEI) (look at the top icons)~~
- [Incorrect tab navigation](https://imgur.com/a/4b7HkbR) (only in the header)

### Expected behavior

~~The header shouldn't glitch~~ and the navigation should choose the correct tab.

### Reproduction

https://github.com/Livijn/navigation-reproduction

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [X] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.0.6
| @react-navigation/bottom-tabs          | 6.0.9
| @react-navigation/native-stack         | 6.1.0
| react-native-safe-area-context         | 3.3.2
| react-native-screens                   | 3.10.1
| react-native                           | 0.64.3
| expo                                   | 5.0.3
| node                                   | 17.3
| npm or yarn                            | yarn

**Comment by Livijn** [comment]
I've updated with a reproduction repo :)

**Comment by Livijn** [comment]
Can someone take a look at this? I've tried digging in your code but the repo isn't very welcoming to get started with. @satya164 @brentvatne @osdnk @WoLewicki

**Comment by WoLewicki** [comment]
It looks like the same issue as the ones solved by https://github.com/react-navigation/react-navigation/pull/9772. Can you apply it and see if it fixes your problem?

**Comment by Livijn** [comment]
Yes, the flickering was solved by that! However, there is still the main issue with incorrect tab switch.

**Comment by Livijn** [comment]
As I stated earlier, this only happens in the header. When using `navigation.getState()` I get different results, depending on if I click on the item in the header or in the actual stack screen.

From the Header:
```json
{
  "stale": false,
  "type": "tab",
  "key": "tab-64JOYdSGsiTFlYsSDjUnq",
  "index": 0,
  "routeNames": [
    "HomeStack",
    "SearchStack"
  ],
  "history": [
    {
      "type": "route",
      "key": "HomeStack-zDhfTDlh9DL2EG7ox9HEY"
    }
  ],
  "routes": [
    {
      "name": "HomeStack",
      "key": "HomeStack-zDhfTDlh9DL2EG7ox9HEY"
    },
    {
      "name": "SearchStack",
      "key": "SearchStack-NUjvsF3UFBSFz3hyBtNgs"
    }
  ]
}
```

From the "HomeFeed" route:
```json
{
  "stale": false,
  "type": "stack",
  "key": "stack-Hh-786gZ8bT-kjtyQQ54e",
  "index": 0,
  "routeNames": [
    "HomeFeed",
    "UserProfile"
  ],
  "routes": [
    {
      "key": "HomeFeed-pHtQU3-hOQVdDTwEdFCBD",
      "name": "HomeFeed"
    }
  ]
}
```

**Comment by eyale** [comment]
> As I stated earlier, this only happens in the header. When using `navigation.getState()` I get different results, depending on if I click on the item in the header or in the actual stack screen.
> 
> From the Header:
> 
> ```json
> {
>   "stale": false,
>   "type": "tab",
>   "key": "tab-64JOYdSGsiTFlYsSDjUnq",
>   "index": 0,
>   "routeNames": [
>     "HomeStack",
>     "SearchStack"
>   ],
>   "history": [
>     {
>       "type": "route",
>       "key": "HomeStack-zDhfTDlh9DL2EG7ox9HEY"
>     }
>   ],
>   "routes": [
>     {
>       "name": "HomeStack",
>       "key": "HomeStack-zDhfTDlh9DL2EG7ox9HEY"
>     },
>     {
>       "name": "SearchStack",
>       "key": "SearchStack-NUjvsF3UFBSFz3hyBtNgs"
>     }
>   ]
> }
> ```
> 
> From the "HomeFeed" route:
> 
> ```json
> {
>   "stale": false,
>   "type": "stack",
>   "key": "stack-Hh-786gZ8bT-kjtyQQ54e",
>   "index": 0,
>   "routeNames": [
>     "HomeFeed",
>     "UserProfile"
>   ],
>   "routes": [
>     {
>       "key": "HomeFeed-pHtQU3-hOQVdDTwEdFCBD",
>       "name": "HomeFeed"
>     }
>   ]
> }
> ```
> 
> So, I tried passing down the `navigation` object from the options prop on `<Stack.Screen>` and it worked!
> 
> ```js
>     <HomeStack.Screen
>         name="HomeFeed"
>         component={HomeFeedScreen}
>         options={({ navigation }) => ({
>           headerTransparent: true,
>           headerRight: () => (
>             <UserButtons isHome={true} navigation={navigation} />
>           ),
>           headerLeft: () => <HomeFeedSelect />,
>           headerTitle: '',
>         })}
>       />
> ```

Man, your solution is so unexpected and so well works. But I have little improvement

`    headerTransparent: !IS_IOS,`

This solution in my case needs only for Android platform.
