### ISSUE TITLE
Debug with chrome not working with latest drawer showing blank screen.

### ISSUE THREAD

**Issue by Biplovkumar** [react-navigation/react-navigation#10264]
### Current behavior

Step 1: created a new project 
step 2: Installed **react-navigation/drawer** 
step 3: debug with chrome
step 4: showing Blank screen.

### Expected behavior

Working fine if code has been taken from [react navigation](https://reactnavigation.org/docs/drawer-based-navigation/)

### Reproduction

https://snack.expo.io/?platform=android&name=&dependencies=%40expo%2Fvector-icons%40*%2C%40react-native-community%2Fmasked-view%40*%2Creact-native-gesture-handler%40*%2Creact-native-pager-view%40*%2Creact-native-paper%40%5E4.7.2%2Creact-native-reanimated%40*%2Creact-native-safe-area-context%40*%2Creact-native-screens%40*%2Creact-native-tab-view%40%5E3.0.0%2C%40react-navigation%2Fbottom-tabs%406.0.4%2C%40react-navigation%2Fdrawer%406.1.3%2C%40react-navigation%2Felements%401.0.4%2C%40react-navigation%2Fmaterial-bottom-tabs%406.0.4%2C%40react-navigation%2Fmaterial-top-tabs%406.0.2%2C%40react-navigation%2Fnative-stack%406.0.5%2C%40react-navigation%2Fnative%406.0.2%2C%40react-navigation%2Fstack%406.0.6&hideQueryParams=true&sourceUrl=https%3A%2F%2Freactnavigation.org%2Fexamples%2F6.x%2Fdrawer-based-navigation.js

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [X] @react-navigation/native-stack

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | "^6.0.6"
| @react-navigation/bottom-tabs          | Not used
| @react-navigation/drawer               | "^6.1.8"
| @react-navigation/material-bottom-tabs | Not used
| @react-navigation/material-top-tabs    | Not used
| @react-navigation/stack                | Not used
| @react-navigation/native-stack         | Not used
| react-native-safe-area-context         |  "^3.3.2"
| react-native-screens                   | "^3.10.1"
| react-native-gesture-handler           | "^2.1.1"
| react-native-reanimated                | "^2.3.1"
| react-native-tab-view                  | Not used
| react-native-pager-view                | Not used
| react-native                           | "0.66.4"
| expo                                   | Not used
| node                                   | v14.17.5
| npm or yarn                            | yarn: 1.22.11, npm: 6.14.14

`    "@react-navigation/drawer": "^6.1.8",
    "@react-navigation/native": "^6.0.6",
    "react": "17.0.2",
    "react-native": "0.66.4",
    "react-native-gesture-handler": "^2.1.1",
    "react-native-reanimated": "^2.3.1",
    "react-native-safe-area-context": "^3.3.2",
    "react-native-screens": "^3.10.1"`

Isssue Image:  (Blank page showing)
![Simulator Screen Shot - iPhone 11 - 2022-01-14 at 13 36 46](https://user-images.githubusercontent.com/30401136/149472993-40f835b9-86bd-41ca-95d8-caeef54a93a2.png)

**Comment by Biplovkumar** [comment]
> * `act-navigation/bottom-tabs`
> * `@react-navigation/material-bottom-tabs`
> * `@react-navigation/material-top-tabs`
> * `@react-navigation/stack`

not used yet in this project. it is a fresh project.

**Comment by Biplovkumar** [comment]
any update?

**Comment by mezalejandro** [comment]
Hello,
I have the same problem, I also tried with previous versions of RN such as 0.64.2 and the same thing happens when I open the debugger the screen is blank.

**Comment by raarts** [comment]
Same problem here. Also happens on Android.

**Comment by wangoghstudio** [comment]
Same problem here. On Android simulator.

**Comment by thebergz** [comment]
Same problem here. Reproduced on RN with iOS and Android _as well as_ Expo.
```
    "@react-navigation/drawer": "^6.1.8", (also occurs with "^6.3.0")
    "@react-navigation/native": "^6.0.8",
    "@react-navigation/native-stack": "^6.5.0",
    "@react-navigation/stack": "^6.0.11",
    "react-native-gesture-handler": "~2.1.0",
    "expo": "~44.0.0",
    "react-native": "0.64.3",
```

**Comment by Biplovkumar** [comment]
Any update?

**Comment by thebergz** [comment]
Same problem here. Reproduced on RN with iOS and Android _as well as_ Expo.
```
    "@react-navigation/drawer": "^6.1.8", (also occurs with "^6.3.0")
    "@react-navigation/native": "^6.0.8",
    "@react-navigation/native-stack": "^6.5.0",
    "@react-navigation/stack": "^6.0.11",
    "react-native-gesture-handler": "~2.1.0",
    "expo": "~44.0.0",
    "react-native": "0.64.3",
```

**Comment by adilkhan2163** [comment]
still facing the same issue

**Comment by adilkhan2163** [comment]
{
  "name": "babacommerce",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint . --ext .js,.jsx,.ts,.tsx"
  },
  "dependencies": {
    "@react-native-async-storage/async-storage": "^1.15.14",
    "@react-native-community/slider": "^4.1.12",
    "@react-navigation/bottom-tabs": "^6.2.0",
    "@react-navigation/drawer": "^6.3.1",
    "@react-navigation/native": "^6.0.8",
    "@react-navigation/native-stack": "^6.2.5",
    "@react-navigation/stack": "^6.0.11",
    "@reduxjs/toolkit": "^1.7.1",
    "react": "^17.0.2",
    "react-native": "0.66.4",
    "react-native-app-intro-slider": "^4.0.4",
    "react-native-gesture-handler": "^2.1.1",
    "react-native-image-zoom-viewer": "^3.0.1",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-reanimated": "^2.4.1",
    "react-native-restart": "^0.0.23",
    "react-native-safe-area-context": "^3.3.2",
    "react-native-screens": "^3.11.0",
    "react-native-splash-screen": "^3.3.0",
    "react-native-vector-icons": "^9.0.0",
    "react-native-woocommerce-api": "^1.8.8",
    "react-redux": "^7.2.6",
    "redux": "^4.1.2",
    "redux-persist": "^6.0.0",
    "redux-thunk": "^2.4.1"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "@types/jest": "^26.0.23",
    "@types/react-native": "^0.66.4",
    "@types/react-native-vector-icons": "^6.4.10",
    "@types/react-test-renderer": "^17.0.1",
    "@typescript-eslint/eslint-plugin": "^5.7.0",
    "@typescript-eslint/parser": "^5.7.0",
    "babel-jest": "^26.6.3",
    "eslint": "^7.14.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.66.2",
    "react-test-renderer": "17.0.2",
    "typescript": "^4.4.4"
  },
  "resolutions": {
    "@types/react": "^17"
  },
  "jest": {
    "preset": "react-native",
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "jsx",
      "json",
      "node"
    ]
  }
}



still facing issue with drawer when debuging

**Comment by biplovappservinc** [comment]
@all PLease suggest, How debugging will be possible ?

**Comment by biplovappservinc** [comment]
same issue with react native 67.2 version

**Comment by ccyfly** [comment]
Same problem here.

```
"@react-navigation/bottom-tabs": "^6.2.0",
"@react-navigation/drawer": "^6.3.1",
"@react-navigation/material-bottom-tabs": "^6.1.1",
"@react-navigation/material-top-tabs": "^6.1.1",
"@react-navigation/native": "^6.0.8",
"@react-navigation/native-stack": "^6.5.0",
"@react-navigation/stack": "^6.1.1",
"react-native-gesture-handler": "2.1.1",
"react-native-reanimated": "^2.4.1",
"react-native-screens": "^3.10.1",
```

**Comment by amenacse** [comment]
Using _useLegacyImplementation={false}_ on my Drawer navigator fix this issue. [https://github.com/software-mansion/react-native-reanimated/issues/2820](url)

**Comment by amenacse** [comment]
Set useLegacyImplementation={false} on my Drawer navigator have fixed the issue. [https://github.com/software-mansion/react-native-reanimated/issues/2820](url)

**Comment by raarts** [comment]
For me it partly works. The app now draws, but now `navigation.dispatch(DrawerActions.toggleDrawer())` doesn't do anything anymore.

**Comment by thebergz** [comment]
@amenacse that worked for me too thanks! :)

**Comment by khoabuidev** [comment]
> Set useLegacyImplementation={false} on my Drawer navigator have fixed the issue. [https://github.com/software-mansion/react-native-reanimated/issues/2820](url)

Perfect. It's working for me. Many thanks.

**Comment by MyPricelow** [comment]
> useLegacyImplementation

Where do we need to set this configuration? Would you please share the file path?

**Comment by gaurav-webbytroops** [comment]
> > Set useLegacyImplementation={false} on my Drawer navigator have fixed the issue. [https://github.com/software-mansion/react-native-reanimated/issues/2820](url)
> 
> Perfect. It's working for me. Many thanks.

Would you please suggest the file path where we need to make this change?

**Comment by kurtisdevv** [comment]
I'm having the same trouble, i'm on reanimated 2.4.1 and have tried the legacy fix but it doesn't seem to work still.

@gaurav-webbytroops I believe it needs to go on the below:

<Drawer.Navigator useLegacyImplementation={false}>


</Drawer.Navigator>

**Comment by hoIIer** [comment]
I'm getting this same issue but when nesting a tab navigator in a stack navigator in fresh react-native/react-navigation project.

It only happens when I nest the <TabNavigator> into a <StackNavigator.Screen>
```
const Stack = createNativeStackNavigator();
const Tab = createBottomTabNavigator();

function Home() {
  return (
    <Tab.Navigator
    >
      <Tab.Screen name="foo" component={Foo}/>
    </Tab.Navigator>
  );
}

export default function AppNav() {
  // const isSignedIn = false;
  const isSignedIn = true;

  return (
    <NavigationContainer>
      {isSignedIn ? (
        <>
          <Stack.Screen name="home" component={Home}/>
        </>
      ) : (
        <>
          <Stack.Screen name="signin" component={SignIn}/>
          <Stack.Screen name="signup" component={SignUp}/>
        </>
      )}
    </NavigationContainer>
  );
}
```
Same blank white screen

    "@react-navigation/bottom-tabs": "^6.3.1",
    "@react-navigation/native": "^6.0.10",
    "@react-navigation/native-stack": "^6.6.1",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-native": "0.64.3",
    "react-native-safe-area-context": "3.3.2",
    "react-native-screens": "~3.10.1",
    "react-native-svg": "^12.3.0",
    "react-native-web": "0.17.1"

**Comment by testing7838** [comment]
Hey it's not working I have faced same error for this 
<Drawer.Navigator useLegacyImplementation={false}>

</Drawer.Navigator>

Dependencies:

"@babel/preset-typescript": "^7.16.7",
"@react-native-async-storage/async-storage": "^1.16.1",
"@react-navigation/drawer": "^6.3.1",
"@react-navigation/native": "^6.0.8",
"react": "17.0.2",
"react-native": "0.67.3",
"react-native-azure-auth": "^1.8.2",
"react-native-gesture-handler": "^2.3.1",
"react-native-reanimated": "^2.4.1",
"react-native-safe-area-context": "^4.1.2",
"react-native-screens": "^3.13.1"

**Comment by adilkhan2163** [comment]
after using useLegacyImplementation={false}
still facing the same issue

**Comment by kurtisdevv** [comment]
> Hey it's not working I have faced same error for this <Drawer.Navigator useLegacyImplementation={false}>
> 
> </Drawer.Navigator>
> 
> Dependencies:
> 
> "@babel/preset-typescript": "^7.16.7", "@react-native-async-storage/async-storage": "^1.16.1", "@react-navigation/drawer": "^6.3.1", "@react-navigation/native": "^6.0.8", "react": "17.0.2", "react-native": "0.67.3", "react-native-azure-auth": "^1.8.2", "react-native-gesture-handler": "^2.3.1", "react-native-reanimated": "^2.4.1", "react-native-safe-area-context": "^4.1.2", "react-native-screens": "^3.13.1"

I'm on a slightly later version of the below if you want to try updating them?

"react-native-gesture-handler": "^2.3.2",

"react-native-safe-area-context": "^4.1.4",

**Comment by ofgowtham** [comment]
useLegacyImplementation={false} not working.
 
   "react-native-reanimated": "2.4.1",
    "@react-navigation/drawer": "6.1.4",
    "@react-navigation/stack": "6.0.7",
    "react-native": "0.65.0",

**Comment by rickyviz** [comment]
same here with this version


    "react-native-reanimated": "^2.4.3",
    "react-native-gesture-handler": "~2.2.1",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-native": "0.68.2",
    "@react-navigation/drawer": "^5.12.5",
    "@react-navigation/native": "^5.9.4",
    "@react-navigation/stack": "^5.14.5",

**Comment by d4rky-pl** [comment]
Still broken
