### ISSUE TITLE
Navigates to screen on the wrong stack

### ISSUE THREAD

**Issue by yusufyildirim** [react-navigation/react-navigation#10287]
### Current behavior

NativeStack has an issue that makes navigation get confused and navigate to the right screen but on the wrong stack.

You can check the reproduction URL to understand the case well but the important thing here is, we use NativeStacks inside TabNavigator and we have the *same screen* defined by the *same name* in the both `HomeStack` and `BrowseStack`.

As you can see on the recording, when we're on the HomePage if we click on the `Go To Collection Page` button, it navigates to the page without issue. Things get interesting when we switch to the `Browse` tab, go back to the `HomeTab` again, and click on the `Go To Collection Page` button once again. It doesn't navigate to the screen within the `HomeStack`, it does navigate within the `BrowseStack` instead.

https://user-images.githubusercontent.com/22980987/150687044-8fefb369-372c-4dcc-9e0b-3bb3275e3a5b.mov

#### Steps to Reproduce

- Open the app
- Navigate to `Browse` tab
- Navigate back to `Home` tab
- Click on `Go To Collection Page` button
- You won't see the `Collection Page`
- Navigate to `Browse` tab
- See `Collection Page` is opened there

### Expected behavior

Should navigate to the `CollectionPage` *within the stack* the navigation action happens.

### Reproduction

https://snack.expo.dev/@yusufyildirimmm/react-navigation-issue

### Platform

- [X] Android
- [X] iOS
- [X] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.0.0
| @react-navigation/bottom-tabs          | 6.0.0
| @react-navigation/native-stack         | 6.2.3
| @react-navigation/native-stack         | 3.3.2
| react-native-screens                   | 3.10.1
| react-native                           | 0.66.4
| expo                                   | 44

**Comment by yusufyildirim** [comment]
I also found and solved the issue. Will open a PR

**Comment by yusufyildirim** [comment]
Fix is ready https://github.com/react-navigation/react-navigation/pull/10288

**Comment by liuyankit** [comment]
still having the same issue on 6.8.0
