### ISSUE TITLE
Cannot use state inside of header

### ISSUE THREAD

**Issue by tamis-laan** [react-navigation/react-navigation#10286]
### Current behavior

I'm adding a search bar into the components header. The search bar uses the search state and changes the search term onChangeText:
``` javascript 
const [search, setSearch] = useState('')
useEffect(()=>{
          navigation?.setOptions({
	          header:() => (
			          <SearchBar 
				          placeholder='search'
				          value={search}
				          onChangeText={text => {
					          setSearch(text)
				          }}
			          />
                                )
          })
},[])
```

### Expected behavior

I would expect `setSearch` to work and change the value of `search` when `onChangeText` is triggered. 

However this is not the case the search text stays the same.

### Reproduction

https://snack.expo.dev/hfFh3wP-J

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |
| @react-navigation/bottom-tabs          |
| @react-navigation/drawer               |
| @react-navigation/material-bottom-tabs |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                |
| @react-navigation/native-stack         |
| react-native-safe-area-context         |
| react-native-screens                   |
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           |
| expo                                   |
| node                                   |
| npm or yarn                            |

**Comment by raajnadar** [comment]
You forgot to add `search` as dependency of use effect to cause re render it.

**Comment by tamis-laan** [comment]
> You forgot to add `search` as dependency of use effect to cause re render it.

This doesn't work properly as old text duplicates tend to pop up when typing in the search bar. 

Also I would not see this as a clean solution, given that useEffect sets the header function once. The component should update based on state changes.

**Comment by raajnadar** [comment]
You should read the docs first,

https://reactnative.dev/docs/textinput#onchange

https://reactnative.dev/docs/textinput#onchangetext

This is the only way to update a screen with state change or ref. Dependencies are use to re invoke the useEffect, that is how react hooks work. This is not the place to ask question this section is to track bugs in react navigation library.
