### ISSUE TITLE
lag/delay when navigate to new screen

### ISSUE THREAD

**Issue by Pietro-Putelli** [react-navigation/react-navigation#10283]
### Current behavior

Here's my pushed screen:

  const venue_id = route.params.venue_id;
  const dispatch = useDispatch();

  const venue = useSelector((state) => get_venue_by_id_state(state, venue_id));

As you can see I get the venue_id from the previous screen and then, use this to get venue from redux-state.
I've also tried to pass venue as route params instead of venue_id and the getting it, but nothing the same lag.

### Expected behavior

The expected behaviour is that when tap on the list element it immediatly navigate to desired screen instead of lagging for half second and then navigate. This lag also allow user to tap the cell twice and so perform twice also the navigation.

### Reproduction

https://github.com/react-navigation/react-navigation/issues/new/choose

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [X] @react-navigation/native-stack

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |
| @react-navigation/bottom-tabs          |
| @react-navigation/drawer               |
| @react-navigation/material-bottom-tabs |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                |
| @react-navigation/native-stack         |
| react-native-safe-area-context         |
| react-native-screens                   |
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           |
| expo                                   |
| node                                   |
| npm or yarn                            |

**Comment by bl1lnk** [comment]
any  update ?

**Comment by jedashford** [comment]
We're also seeing this. RN 4 on another app we manage is much faster. Sluggish movement from one screen to another.
