### ISSUE TITLE
App crashes while navigating (Android Only)

### ISSUE THREAD

**Issue by Bayramito** [react-navigation/react-navigation#10290]
### Current behavior

After upgrading navigation v6 from v5, sometimes app crashing while animating. I investigated this a lot, and i think its bexcouse of default navigation animations.  And this happens on Android only.

This is what i get from logcat,

```
    --------- beginning of crash
2022-01-24 14:12:35.680 11277-11389/com.omuz A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x1c in tid 11389 (RenderThread), pid 11277 (com.omuz)
```

but instead of this if i  set `animationEnabled:false` from `screenOptions` in my very first stack navigator, then its being fixed but this time without any animation.

### Expected behavior

When i hit to the button it should navigates to the second screen  with default navigation animation

### Reproduction

----

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
    "@react-navigation/bottom-tabs": "^6.0.9",
    "@react-navigation/compat": "^5.1.9",
    "@react-navigation/core": "^6.1.0",
    "@react-navigation/drawer": "^6.1.6",
    "@react-navigation/elements": "^1.2.1",
    "@react-navigation/material-bottom-tabs": "^6.0.9",
    "@react-navigation/material-top-tabs": "^6.0.6",
    "@react-navigation/native": "^6.0.6",
    "@react-navigation/native-stack": "^6.2.5",
    "@react-navigation/stack": "^6.0.11",
    "react-native-safe-area-context": "^3.3.2",
    "react-native-screens": "^3.8.0",
    "react-native-gesture-handler": "^1.8.0",
    "react-native-reanimated": "^2.3.1",
    "react-native-tab-view": "^3.1.1",
    "react-native-pager-view": "^5.4.4",
    "react-native": "0.64.2",
| expo                                   |
| node                                   | v12.22.5
| npm or yarn                            | 8.1.4

**Comment by raajnadar** [comment]
Make sure you followed this guide https://reactnavigation.org/docs/upgrading-from-5.x

And RNGH & reanimated are configured correctly check their docs as per your dependency version.

**Comment by Bayramito** [comment]
i mean

> Make sure you followed this guide https://reactnavigation.org/docs/upgrading-from-5.x
> 
> And RNGH & reanimated are configured correctly check their docs as per your dependency version.

im using RNGH 1.8.0 since last year, and im sure i very carefully installed the newest version of reanimated 2.

i have lots of reanimated based animations and gestures on my project if there was something wrong i would know that till know. 

this issue started since i upgraded from v5... idk why, i tell you when i disable animations by animationEnabled prop, its getting fixed

**Comment by Bayramito** [comment]
> Make sure you followed this guide https://reactnavigation.org/docs/upgrading-from-5.x
> 
> And RNGH & reanimated are configured correctly check their docs as per your dependency version.

tried everything step by step one more time from scratch but didnt work

**Comment by raajnadar** [comment]
Try clearing the cache and test again with `expo start -c` or `react-native start --reset-cache`

Please add a repro so that we can check what is going wrong.

**Comment by Bayramito** [comment]
i just wonder can it be becouse of deep navigating ? 

for example here, i navigate into Online navigator's OnlineListDetail... this scenario crashes my app. 
BUT, if i alredy in Online navigator, and try to open same url, its working...

`    DeepLinking.addRoute("/online/list/:id", args => {
      navigate("Online", {
        screen: "OnlineListDetail",
        params: {
          id: args.id,
          uri: "",
        },
      });
    });
`

**Comment by Bayramito** [comment]
I cant realize whats wroing with my project :(

https://user-images.githubusercontent.com/44513402/151156891-d548a29a-b07a-4e41-9d9b-57cfd70125ca.mov


i just noticed that its crashing randomly,  

![code](https://user-images.githubusercontent.com/44513402/151157132-9f612b44-5ddc-4137-8b3a-91e44cf746b1.png)

I have that simple code to navigate between the apps.

BTW, let me show you my main stack maybe there something that i miss

![code](https://user-images.githubusercontent.com/44513402/151157299-009cc401-8915-44a4-bff5-f20afa7a819b.png)

What im doing here is, 
saving the current state of navigation to the storage, to be able to recover it when user re-opens the app.

and finally my navigation tree,

--> ModalStack.Navigator (with children screens, some modals and ManStack navigator)
------> MainStack.Navigator (with couple of children stack navigators Profile, Events, Actions etc...)
------------> EventStack.Navigator (with Events specific screens EventDetail, EventAgenda, EventFavorites etc...)
------------> Profile.Navigator (with Profile specific screens...)

lets say im in EventFavorites screen and want to go  Actions stack navigator's specific screen, 

i just  
```
 const navigation = useNavigation();
    navigate("Actions", {
        screen: "ActionDetail",
        params: {
          id:id,
        },
      });
```
Thats all, i think its becouse of Android's default pop up animation ... idk ... :(

**Comment by Bayramito** [comment]
Fixed it, the problem was on react-native-youtube-iframe library

**Comment by ofreyssinet-ledger** [comment]
Hello @Bayramito, I'm having a very similar crash, is there any chance that you know which fix on that other library fixed that?

**Comment by Bayramito** [comment]
My issue was that i was using react-navigation-shared-element on my project for creating navigators. createSharedElementStackNavigator  i removed it and everything is find

**Comment by ksielyov** [comment]
Same in just clean project. It`s crash sometimes

**Comment by Dilnawazkhan4Saufik** [comment]
all you need to do is, 
 <Stack.Navigator
      initialRouteName={componentName}
      screenOptions={{
        animationTypeForReplace: 'pop',
        headerShown: false,
        animationEnabled:
          Platform.OS == 'android' &&
          parseInt(deviceInfoModule.getSystemVersion()) > 9
            ? false
            : true,
      }}
    >
...
</Stach.Navigator>
that's how I resolved this issue

**Comment by lucasGabrielDeAA** [comment]
> all you need to do is, <Stack.Navigator initialRouteName={componentName} screenOptions={{ animationTypeForReplace: 'pop', headerShown: false, animationEnabled: Platform.OS == 'android' && parseInt(deviceInfoModule.getSystemVersion()) > 9 ? false : true, }} > ... </Stach.Navigator> that's how I resolved this issue

I was facing the same problem, and I also have the same library `react-native-iframe-youtube` on my project. And this "trick" solved my problem.

**Comment by Bayramito** [comment]
My issue was on react-native-youtube-iftame library. So if thr destinatiom route includes this lib, you have to set its opacity to 0.99

**Comment by Naandalist** [comment]
This solve my problem. Thank you.

`<YoutubePlayer 
...
    webViewStyle={ {opacity:0.99} }
/>`

> Fixed it, the problem was on react-native-youtube-iframe library

**Comment by Dilnawazkhan4Saufik** [comment]
> > all you need to do is, <Stack.Navigator initialRouteName={componentName} screenOptions={{ animationTypeForReplace: 'pop', headerShown: false, animationEnabled: Platform.OS == 'android' && parseInt(deviceInfoModule.getSystemVersion()) > 9 ? false : true, }} > ... </Stach.Navigator> that's how I resolved this issue
> 
> I was facing the same problem, and I also have the same library `react-native-iframe-youtube` on my project. And this "trick" solved my problem.

Pleased that it helped you

**Comment by alfredosdpiii** [comment]
> This solve my problem. Thank you.
> 
> `<YoutubePlayer ... webViewStyle={ {opacity:0.99} } />`
> 
> > Fixed it, the problem was on react-native-youtube-iframe library

Solved mine too

**Comment by LukasBombach** [comment]
It happens when you navigate to a webview with animations on. it works either without a webview or without animations

**Comment by LukasBombach** [comment]
This is the problem here:

https://github.com/react-navigation/react-navigation/issues/9061

**Comment by patlux** [comment]
We used a hidden webview on our settings page to communicate with a web-only sdk. All navigations from there to another page crashed on android. The fix was to set `androidLayer="software"` to the hidden webview instance.

**Comment by fabriziocucci** [comment]
The only reasonable workarounds I've found acceptable (without disabling the animations on the stack screen) are:
* setting `androidLayerType="software"` on the `WebView` component (as mentioned [here](https://github.com/react-navigation/react-navigation/issues/10290#issuecomment-1639862911)):
```
<WebView androidLayerType="software" ... />
```
* using  the `useIsFocused` hook to conditionally render the `WebView` (as mentioned [here](https://github.com/react-navigation/react-navigation/issues/9061#issuecomment-1511053069)):
```
const isFocused = useIsFocused();
// ...
return (isFocused && (<WebView ... />)
```
