### ISSUE TITLE
Deeplinks are not working in background after update to v6

### ISSUE THREAD

**Issue by quattrorx7** [react-navigation/react-navigation#10292]
### Current behavior

Deeplink is not working if we try to open it when app was not fully closed. However if we fully close application, then everything is fine. Also here is the warning I get.
P.S. - I don't have conditional rendering

Warning message:
The navigation state parsed from the URL contains routes not present in the root navigator. This usually means that the linking configuration doesn't match the navigation structure. See https://reactnavigation.org/docs/configuring-links for more details on how to specify a linking configuration.

### Expected behavior

Deeplink opens screen when app was not fully closed

### Reproduction

I can't provide example, because project is under NDA. linking code is the same with code in documentation

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [x] @react-navigation/bottom-tabs
- [x] @react-navigation/stack
- [x] @react-navigation/native

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               6.0.6
| @react-navigation/bottom-tabs          6.0.9
| @react-navigation/stack                6.0.11
| react-native                           0.64.2

**Comment by quattrorx7** [comment]
> Hey! Thanks for opening the issue. The issue doesn't seem to contain a link to a repro (a [snack.expo.dev](https://snack.expo.dev) link or link to a GitHub repo under your username).
> 
> Can you provide a [minimal repro](https://stackoverflow.com/help/minimal-reproducible-example) which demonstrates the issue? A repro will help us debug the issue faster. Please try to keep the repro as small as possible and make sure that we can run it without additional setup.

Unfortunately I can't share code because of NDA, I just took code from documentation(https://reactnavigation.org/docs/deep-linking/)

**Comment by quattrorx7** [comment]
> Couldn't find version numbers for the following packages in the issue:
> 
> * `@react-navigation/drawer`
> * `@react-navigation/material-bottom-tabs`
> * `@react-navigation/material-top-tabs`
> 
> Can you update the issue to include version numbers for those packages? The version numbers must match the format 1.2.3.

Updated

**Comment by giacomoalonzi** [comment]
> ### Current behavior
> Deeplink is not working if we try to open it when app was not fully closed. However if we fully close application, then everything is fine. Also here is the warning I get. P.S. - I don't have conditional rendering
> 
> Warning message: The navigation state parsed from the URL contains routes not present in the root navigator. This usually means that the linking configuration doesn't match the navigation structure. See https://reactnavigation.org/docs/configuring-links for more details on how to specify a linking configuration.
> 
> ### Expected behavior
> Deeplink opens screen when app was not fully closed
> 
> ### Reproduction
> I can't provide example, because project is under NDA. linking code is the same with code in documentation
> 
> ### Platform
> * [x]  Android
> * [x]  iOS
> * [ ]  Web
> * [ ]  Windows
> * [ ]  MacOS
> 
> ### Packages
> * [x]  @react-navigation/bottom-tabs
> * [x]  @react-navigation/stack
> * [x]  @react-navigation/native
> 
> package	version
> @react-navigation/native 6.0.6	
> @react-navigation/bottom-tabs 6.0.9	
> @react-navigation/stack 6.0.11	
> react-native 0.64.2

I have the same issue here, but If you tap a second time on the link the deep link works?

**Comment by bumjin1013** [comment]
same!!!!!!!

**Comment by internetammo** [comment]
still an issue please open

**Comment by internetammo** [comment]
Hey I had this issue but ended up fixing it by stripping out all the other items mostly suggested and just going with the linking config and that reference in the NavigationContainer

so just linking={linking}
and 
	const linking = {
		prefixes: [Linking.createURL('/'), 'https://colabs.world', 'colabs://'],
		conifg: {
			screens: {
			Screen1: 'screen1',
			Screen2: 'screen2',
			SignIn: '*',
			}
		}
	}

**Comment by Estevete** [comment]
I'm facing the same issue.

**Comment by TobiDevloft** [comment]
I had the same issue and solved it by adding the following in the AppDelegate.mm. This is not in the docs, but apparently needed for linking subscriptions to work when the app is in foreground or background.

```
- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url
  sourceApplication:(NSString *)sourceApplication annotation:(id)annotation
{
  return [RCTLinkingManager application:application openURL:url
                      sourceApplication:sourceApplication annotation:annotation];
}
```

**Comment by ajaybushel** [comment]
@TobiDevloft solution works! However, here's the code with the required import:

```objectivec

// Add just below #import <React/RCTAppSetupUtils.h>
#import <React/RCTLinkingManager.h>

// Add after "didFinishLaunchingWithOptions" function
- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url
  sourceApplication:(NSString *)sourceApplication annotation:(id)annotation
{
  return [RCTLinkingManager application:application openURL:url
                      sourceApplication:sourceApplication annotation:annotation];
}
```
