### ISSUE TITLE
Installing React Navigation 6 Insta-Nukes My App

### ISSUE THREAD

**Issue by bcorrel2** [react-navigation/react-navigation#10291]
### Current behavior

I have a pretty simple React Native, I'm actually starting over after unrelated issues. Essentially, 2 Screens connected by a Drawer, though right now I'm testing with the Default React Native Screen. 

I Install the Dependency as Specified:

`yarn add @react-navigation/native`

Instantly destroys my ability to build in iOS. 

---------------------------------------------------------------------------------------------------------------------------

`Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -workspace ProjectApp.xcworkspace -configuration Debug -scheme ProjectApp -destination id=A3F687EE-98BF-4A47-B71B-3FC7864AEFB2

User defaults from command line:
    IDEPackageSupportUseBuiltinSCM = YES

note: Using new build system
note: Planning
Analyze workspace

Create build description
Build description signature: df58154c2ccaf0f8b800d1593267a935
Build description path: /Users/Me/Library/Developer/Xcode/DerivedData/ProjectApp-epfnoloauyinvagczacvciywwios/Build/Intermediates.noindex/XCBuildData/df58154c2ccaf0f8b800d1593267a935-desc.xcbuild

note: Build preparation complete
note: Building targets in dependency order
CompileC /Users/Me/Library/Developer/Xcode/DerivedData/ProjectApp-epfnoloauyinvagczacvciywwios/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-CoreModules.build/Objects-normal/arm64/RCTAlertManager.o /Users/Me/Development/ProjectApp/node_modules/react-native/React/CoreModules/RCTAlertManager.mm normal arm64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'React-CoreModules' from project 'Pods')
    cd /Users/Me/Development/ProjectApp/ios/Pods
    export LANG\=en_US.US-ASCII
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c++ -target arm64-apple-ios11.0-simulator -fmessage-length\=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit\=0 -std\=c++14 -stdlib\=libc++ -fobjc-arc -fmodules -fmodules-cache-path\=/Users/Me/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -fmodules-prune-interval\=86400 -fmodules-prune-after\=345600 -fbuild-session-file\=/Users/Me/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror\=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -O0 -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror\=return-type -Wdocumentation -Wunreachable-code -Wno-implicit-atomic-properties -Werror\=deprecated-objc-isa-usage -Wno-objc-interface-ivars -Werror\=objc-root-class -Wno-arc-repeated-use-of-weak -Wimplicit-retain-self -Wno-non-virtual-dtor -Wno-overloaded-virtual -Wno-exit-time-destructors -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wdeprecated-implementations -Wno-c++11-extensions -DPOD_CONFIGURATION_DEBUG\=1 -DDEBUG\=1 -DCOCOAPODS\=1 -DOBJC_OLD_DISPATCH_PROTOTYPES\=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator15.2.sdk -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -Winvalid-offsetof -g -Wno-sign-conversion -Winfinite-recursion -Wmove -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wrange-loop-analysis -Wno-semicolon-before-method-body -Wunguarded-availability -fobjc-abi-version\=2 -fobjc-legacy-dispatch -index-store-path /Users/Me/Library/Developer/Xcode/DerivedData/ProjectApp-epfnoloauyinvagczacvciywwios/Index/DataStore -iquote /Users/Me/Library/Developer/Xcode/DerivedData/ProjectApp-epfnoloauyinvagczacvciywwios/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-CoreModules.build/React-CoreModules-generated-files.hmap -I/Users/Me/Library/Developer/Xcode/DerivedData/ProjectApp-epfnoloauyinvagczacvciywwios/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-CoreModules.build/React-CoreModules-own-target-headers.hmap -I/Users/Me/Library/Developer/Xcode/DerivedData/ProjectApp-epfnoloauyinvagczacvciywwios/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-CoreModules.build/React-CoreModules-all-non-framework-target-headers.hmap -ivfsoverlay /Users/Me/Library/Developer/Xcode/DerivedData/ProjectApp-epfnoloauyinvagczacvciywwios/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-CoreModules.build/all-product-headers.yaml -iquote /Users/Mel/Library/Developer/Xcode/DerivedData/ProjectApp-epfnoloauyinvagczacvciywwios/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-CoreModules.build/React-CoreModules-project-headers.hmap -I/Users/Me/Library/Developer/Xcode/DerivedData/ProjectApp-epfnoloauyinvagczacvciywwios/Build/Products/Debug-iphonesimulator/React-CoreModules/include -I/Users/Me/Development/ProjectApp/ios/Pods/Headers/Public -I/Users/Me/Development/ProjectApp/ios/Pods/Headers/Public/DoubleConversion -I/Users/Me/Development/ProjectApp/ios/Pods/Headers/Public/FBLazyVector -I/Users/Me/Development/ProjectApp/ios/Pods/Headers/Public/FBReactNativeSpec -I/Users/Me/Development/ProjectApp/ios/Pods/Headers/Public/RCT-Folly -I/Users/Me/Development/ProjectApp/ios/Pods/Headers/Public/RCTRequired -I/Users/Me/Development/ProjectApp/ios/Pods/Headers/Public/RCTTypeSafety -I/Users/Me/Development/ProjectApp/ios/Pods/Headers/Public/React-Core -I/Users/Me/Development/ProjectApp/ios/Pods/Headers/Public/React-callinvoker -I/Users/Mel/Development/ProjectApp/ios/Pods/Headers/Public/React-cxxreact -I/Users/Me/Development/ProjectApp/ios/Pods/Headers/Public/React-jsi -I/Users/Me/Development/ProjectApp/ios/Pods/Headers/Public/React-jsiexecutor -I/Users/Me/Development/ProjectApp/ios/Pods/Headers/Public/React-jsinspector -I/Users/Me/Development/ProjectApp/ios/Pods/Headers/Public/React-logger -I/Users/Me/Development/ProjectApp/ios/Pods/Headers/Public/React-perflogger -I/Users/Me/Development/ProjectApp/ios/Pods/Headers/Public/React-runtimeexecutor -I/Users/Me/Development/ProjectApp/ios/Pods/Headers/Public/ReactCommon -I/Users/Me/Development/ProjectApp/ios/Pods/Headers/Public/Yoga -I/Users/Me/Development/ProjectApp/ios/Pods/Headers/Public/fmt -I/Users/Me/Development/ProjectApp/ios/Pods/Headers/Public/glog -I/Users/Me/Development/ProjectApp/node_modules/react-native/React/CoreModules/React/CoreModules -I/Users/Me/Development/ProjectApp/ios/Pods/RCT-Folly -I/Users/Me/Library/Developer/Xcode/DerivedData/ProjectApp-epfnoloauyinvagczacvciywwios/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-CoreModules.build/DerivedSources-normal/arm64 -I/Users/Me/Library/Developer/Xcode/DerivedData/ProjectApp-epfnoloauyinvagczacvciywwios/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-CoreModules.build/DerivedSources/arm64 -I/Users/Me/Library/Developer/Xcode/DerivedData/ProjectApp-epfnoloauyinvagczacvciywwios/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-CoreModules.build/DerivedSources -F/Users/Me/Library/Developer/Xcode/DerivedData/ProjectApp-epfnoloauyinvagczacvciywwios/Build/Products/Debug-iphonesimulator/React-CoreModules -fmodule-map-file\=/Users/Me/Development/ProjectApp/ios/Pods/Headers/Public/React/React-Core.modulemap -fmodule-map-file\=/Users/Me/Development/ProjectApp/ios/Pods/Headers/Public/yoga/Yoga.modulemap -DFOLLY_NO_CONFIG -DFOLLY_MOBILE\=1 -DFOLLY_USE_LIBCPP\=1 -Wno-comma -Wno-shorten-64-to-32 -Wno-nullability-completeness -include /Users/Me/Development/ProjectApp/ios/Pods/Target\ Support\ Files/React-CoreModules/React-CoreModules-prefix.pch -MMD -MT dependencies -MF /Users/Me/Library/Developer/Xcode/DerivedData/ProjectApp-epfnoloauyinvagczacvciywwios/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-CoreModules.build/Objects-normal/arm64/RCTAlertManager.d --serialize-diagnostics /Users/Me/Library/Developer/Xcode/DerivedData/ProjectApp-epfnoloauyinvagczacvciywwios/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-CoreModules.build/Objects-normal/arm64/RCTAlertManager.dia -c /Users/Me/Development/ProjectApp/node_modules/react-native/React/CoreModules/RCTAlertManager.mm -o /Users/Me/Library/Developer/Xcode/DerivedData/ProjectApp-epfnoloauyinvagczacvciywwios/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-CoreModules.build/Objects-normal/arm64/RCTAlertManager.o

CompileC /Users/Me/Library/Developer/Xcode/DerivedData/ProjectApp-epfnoloauyinvagczacvciywwios/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-CoreModules.build/Objects-normal/arm64/RCTActionSheetManager.o /Users/Me/Development/ProjectApp/node_modules/react-native/React/CoreModules/RCTActionSheetManager.mm normal arm64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'React-CoreModules' from project 'Pods')
    cd /Users/Me/Development/ProjectApp/ios/Pods
    export LANG\=en_US.US-ASCII
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c++ -target arm64-apple-ios11.0-simulator -fmessage-length\=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit\=0 -std\=c++14 -stdlib\=libc++ -fobjc-arc -fmodules -fmodules-cache-path\=/Users/Me/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -fmodules-prune-interval\=86400 -fmodules-prune-after\=345600 -fbuild-session-file\=/Users/Me/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror\=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -O0 -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror\=return-type -Wdocumentation -Wunreachable-code -Wno-implicit-atomic-properties -Werror\=deprecated-objc-isa-usage -Wno-objc-interface-ivars -Werror\=objc-root-class -Wno-arc-repeated-use-of-weak -Wimplicit-retain-self -Wno-non-virtual-dtor -Wno-overloaded-virtual -Wno-exit-time-destructors -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wdeprecated-implementations -Wno-c++11-extensions -DPOD_CONFIGURATION_DEBUG\=1 -DDEBUG\=1 -DCOCOAPODS\=1 -DOBJC_OLD_DISPATCH_PROTOTYPES\=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator15.2.sdk -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -Winvalid-offsetof -g -Wno-sign-conversion -Winfinite-recursion -Wmove -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wrange-loop-analysis -Wno-semicolon-before-method-body -Wunguarded-availability -fobjc-abi-version\=2 -fobjc-legacy-dispatch -index-store-path /Users/Me/Library/Developer/Xcode/DerivedData/ProjectApp-epfnoloauyinvagczacvciywwios/Index/DataStore -iquote /Users/Me/Library/Developer/Xcode/DerivedData/ProjectApp-epfnoloauyinvagczacvciywwios/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-CoreModules.build/React-CoreModules-generated-files.hmap -I/Users/Me/Library/Developer/Xcode/DerivedData/ProjectApp-epfnoloauyinvagczacvciywwios/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-CoreModules.build/React-CoreModules-own-target-headers.hmap -I/Users/Me/Library/Developer/Xcode/DerivedData/ProjectApp-epfnoloauyinvagczacvciywwios/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-CoreModules.build/React-CoreModules-all-non-framework-target-headers.hmap -ivfsoverlay /Users/Me/Library/Developer/Xcode/DerivedData/ProjectApp-epfnoloauyinvagczacvciywwios/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-CoreModules.build/all-product-headers.yaml -iquote /Users/Me/Library/Developer/Xcode/DerivedData/ProjectApp-epfnoloauyinvagczacvciywwios/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-CoreModules.build/React-CoreModules-project-headers.hmap -I/Users/Me/Library/Developer/Xcode/DerivedData/ProjectApp-epfnoloauyinvagczacvciywwios/Build/Products/Debug-iphonesimulator/React-CoreModules/include -I/Users/Me/Development/ProjectApp/ios/Pods/Headers/Public -I/Users/Me/Development/ProjectApp/ios/Pods/Headers/Public/DoubleConversion -I/Users/Me/Development/ProjectApp/ios/Pods/Headers/Public/FBLazyVector -I/Users/Me/Development/ProjectApp/ios/Pods/Headers/Public/FBReactNativeSpec -I/Users/Me/Development/ProjectApp/ios/Pods/Headers/Public/RCT-Folly -I/Users/Me/Development/ProjectApp/ios/Pods/Headers/Public/RCTRequired -I/Users/Me/Development/ProjectApp/ios/Pods/Headers/Public/RCTTypeSafety -I/Users/Me/Development/ProjectApp/ios/Pods/Headers/Public/React-Core -I/Users/Me/Development/ProjectApp/ios/Pods/Headers/Public/React-callinvoker -I/Users/Me/Development/ProjectApp/ios/Pods/Headers/Public/React-cxxreact -I/Users/Me/Development/ProjectApp/ios/Pods/Headers/Public/React-jsi -I/Users/Me/Development/ProjectApp/ios/Pods/Headers/Public/React-jsiexecutor -I/Users/Me/Development/ProjectApp/ios/Pods/Headers/Public/React-jsinspector -I/Users/Me/Development/ProjectApp/ios/Pods/Headers/Public/React-logger -I/Users/Me/Development/ProjectApp/ios/Pods/Headers/Public/React-perflogger -I/Users/Me/Development/ProjectApp/ios/Pods/Headers/Public/React-runtimeexecutor -I/Users/Me/Development/ProjectApp/ios/Pods/Headers/Public/ReactCommon -I/Users/Me/Development/ProjectApp/ios/Pods/Headers/Public/Yoga -I/Users/Me/Development/ProjectApp/ios/Pods/Headers/Public/fmt -I/Users/Me/Development/ProjectApp/ios/Pods/Headers/Public/glog -I/Users/Me/Development/ProjectApp/node_modules/react-native/React/CoreModules/React/CoreModules -I/Users/Me/Development/ProjectApp/ios/Pods/RCT-Folly -I/Users/Me/Library/Developer/Xcode/DerivedData/ProjectApp-epfnoloauyinvagczacvciywwios/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-CoreModules.build/DerivedSources-normal/arm64 -I/Users/Me/Library/Developer/Xcode/DerivedData/ProjectApp-epfnoloauyinvagczacvciywwios/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-CoreModules.build/DerivedSources/arm64 -I/Users/Me/Library/Developer/Xcode/DerivedData/ProjectApp-epfnoloauyinvagczacvciywwios/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-CoreModules.build/DerivedSources -F/Users/Me/Library/Developer/Xcode/DerivedData/ProjectApp-epfnoloauyinvagczacvciywwios/Build/Products/Debug-iphonesimulator/React-CoreModules -fmodule-map-file\=/Users/Me/Development/ProjectApp/ios/Pods/Headers/Public/React/React-Core.modulemap -fmodule-map-file\=/Users/Me/Development/ProjectApp/ios/Pods/Headers/Public/yoga/Yoga.modulemap -DFOLLY_NO_CONFIG -DFOLLY_MOBILE\=1 -DFOLLY_USE_LIBCPP\=1 -Wno-comma -Wno-shorten-64-to-32 -Wno-nullability-completeness -include /Users/Me/Development/ProjectApp/ios/Pods/Target\ Support\ Files/React-CoreModules/React-CoreModules-prefix.pch -MMD -MT dependencies -MF /Users/Me/Library/Developer/Xcode/DerivedData/ProjectApp-epfnoloauyinvagczacvciywwios/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-CoreModules.build/Objects-normal/arm64/RCTActionSheetManager.d --serialize-diagnostics /Users/Me/Library/Developer/Xcode/DerivedData/ProjectApp-epfnoloauyinvagczacvciywwios/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-CoreModules.build/Objects-normal/arm64/RCTActionSheetManager.dia -c /Users/Me/Development/ProjectApp/node_modules/react-native/React/CoreModules/RCTActionSheetManager.mm -o /Users/Me/Library/Developer/Xcode/DerivedData/ProjectApp-epfnoloauyinvagczacvciywwios/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-CoreModules.build/Objects-normal/arm64/RCTActionSheetManager.o
/Users/Me/Development/ProjectApp/node_modules/react-native/React/CoreModules/RCTActionSheetManager.mm:98:35: error: no member named 'cancelButtonTintColor' in 'JS::NativeActionSheetManager::SpecShowActionSheetWithOptionsOptions'
      [RCTConvert UIColor:options.cancelButtonTintColor() ? @(*options.cancelButtonTintColor()) : nil];
                          ~~~~~~~ ^
/Users/Me/Development/ProjectApp/node_modules/react-native/React/CoreModules/RCTActionSheetManager.mm:98:72: error: no member named 'cancelButtonTintColor' in 'JS::NativeActionSheetManager::SpecShowActionSheetWithOptionsOptions'
      [RCTConvert UIColor:options.cancelButtonTintColor() ? @(*options.cancelButtonTintColor()) : nil];
                                                               ~~~~~~~ ^
2 errors generated.

CompileC /Users/Me/Library/Developer/Xcode/DerivedData/ProjectApp-epfnoloauyinvagczacvciywwios/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-CoreModules.build/Objects-normal/arm64/RCTAccessibilityManager.o /Users/Me/Development/ProjectApp/node_modules/react-native/React/CoreModules/RCTAccessibilityManager.mm normal arm64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'React-CoreModules' from project 'Pods')
    cd /Users/Me/Development/ProjectApp/ios/Pods
    export LANG\=en_US.US-ASCII
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c++ -target arm64-apple-ios11.0-simulator -fmessage-length\=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit\=0 -std\=c++14 -stdlib\=libc++ -fobjc-arc -fmodules -fmodules-cache-path\=/Users/Me/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -fmodules-prune-interval\=86400 -fmodules-prune-after\=345600 -fbuild-session-file\=/Users/Me/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror\=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -O0 -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror\=return-type -Wdocumentation -Wunreachable-code -Wno-implicit-atomic-properties -Werror\=deprecated-objc-isa-usage -Wno-objc-interface-ivars -Werror\=objc-root-class -Wno-arc-repeated-use-of-weak -Wimplicit-retain-self -Wno-non-virtual-dtor -Wno-overloaded-virtual -Wno-exit-time-destructors -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wdeprecated-implementations -Wno-c++11-extensions -DPOD_CONFIGURATION_DEBUG\=1 -DDEBUG\=1 -DCOCOAPODS\=1 -DOBJC_OLD_DISPATCH_PROTOTYPES\=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator15.2.sdk -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -Winvalid-offsetof -g -Wno-sign-conversion -Winfinite-recursion -Wmove -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wrange-loop-analysis -Wno-semicolon-before-method-body -Wunguarded-availability -fobjc-abi-version\=2 -fobjc-legacy-dispatch -index-store-path /Users/Me/Library/Developer/Xcode/DerivedData/ProjectApp-epfnoloauyinvagczacvciywwios/Index/DataStore -iquote /Users/Me/Library/Developer/Xcode/DerivedData/ProjectApp-epfnoloauyinvagczacvciywwios/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-CoreModules.build/React-CoreModules-generated-files.hmap -I/Users/Me/Library/Developer/Xcode/DerivedData/ProjectApp-epfnoloauyinvagczacvciywwios/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-CoreModules.build/React-CoreModules-own-target-headers.hmap -I/Users/Me/Library/Developer/Xcode/DerivedData/ProjectApp-epfnoloauyinvagczacvciywwios/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-CoreModules.build/React-CoreModules-all-non-framework-target-headers.hmap -ivfsoverlay /Users/Me/Library/Developer/Xcode/DerivedData/ProjectApp-epfnoloauyinvagczacvciywwios/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-CoreModules.build/all-product-headers.yaml -iquote /Users/Me/Library/Developer/Xcode/DerivedData/ProjectApp-epfnoloauyinvagczacvciywwios/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-CoreModules.build/React-CoreModules-project-headers.hmap -I/Users/Me/Library/Developer/Xcode/DerivedData/ProjectApp-epfnoloauyinvagczacvciywwios/Build/Products/Debug-iphonesimulator/React-CoreModules/include -I/Users/Me/Development/ProjectApp/ios/Pods/Headers/Public -I/Users/Me/Development/ProjectApp/ios/Pods/Headers/Public/DoubleConversion -I/Users/Me/Development/ProjectApp/ios/Pods/Headers/Public/FBLazyVector -I/Users/Me/Development/ProjectApp/ios/Pods/Headers/Public/FBReactNativeSpec -I/Users/Me/Development/ProjectApp/ios/Pods/Headers/Public/RCT-Folly -I/Users/Me/Development/ProjectApp/ios/Pods/Headers/Public/RCTRequired -I/Users/Me/Development/ProjectApp/ios/Pods/Headers/Public/RCTTypeSafety -I/Users/Me/Development/ProjectApp/ios/Pods/Headers/Public/React-Core -I/Users/Me/Development/ProjectApp/ios/Pods/Headers/Public/React-callinvoker -I/Users/Me/Development/ProjectApp/ios/Pods/Headers/Public/React-cxxreact -I/Users/Me/Development/ProjectApp/ios/Pods/Headers/Public/React-jsi -I/Users/Me/Development/ProjectApp/ios/Pods/Headers/Public/React-jsiexecutor -I/Users/Me/Development/ProjectApp/ios/Pods/Headers/Public/React-jsinspector -I/Users/Me/Development/ProjectApp/ios/Pods/Headers/Public/React-logger -I/Users/Me/Development/ProjectApp/ios/Pods/Headers/Public/React-perflogger -I/Users/Me/Development/ProjectApp/ios/Pods/Headers/Public/React-runtimeexecutor -I/Users/Me/Development/ProjectApp/ios/Pods/Headers/Public/ReactCommon -I/Users/Me/Development/ProjectApp/ios/Pods/Headers/Public/Yoga -I/Users/Me/Development/ProjectApp/ios/Pods/Headers/Public/fmt -I/Users/Me/Development/ProjectApp/ios/Pods/Headers/Public/glog -I/Users/Me/Development/ProjectApp/node_modules/react-native/React/CoreModules/React/CoreModules -I/Users/Me/Development/ProjectApp/ios/Pods/RCT-Folly -I/Users/Me/Library/Developer/Xcode/DerivedData/ProjectApp-epfnoloauyinvagczacvciywwios/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-CoreModules.build/DerivedSources-normal/arm64 -I/Users/Me/Library/Developer/Xcode/DerivedData/ProjectApp-epfnoloauyinvagczacvciywwios/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-CoreModules.build/DerivedSources/arm64 -I/Users/Me/Library/Developer/Xcode/DerivedData/ProjectApp-epfnoloauyinvagczacvciywwios/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-CoreModules.build/DerivedSources -F/Users/Me/Library/Developer/Xcode/DerivedData/ProjectApp-epfnoloauyinvagczacvciywwios/Build/Products/Debug-iphonesimulator/React-CoreModules -fmodule-map-file\=/Users/Me/Development/ProjectApp/ios/Pods/Headers/Public/React/React-Core.modulemap -fmodule-map-file\=/Users/Me/Development/ProjectApp/ios/Pods/Headers/Public/yoga/Yoga.modulemap -DFOLLY_NO_CONFIG -DFOLLY_MOBILE\=1 -DFOLLY_USE_LIBCPP\=1 -Wno-comma -Wno-shorten-64-to-32 -Wno-nullability-completeness -include /Users/Me/Development/ProjectApp/ios/Pods/Target\ Support\ Files/React-CoreModules/React-CoreModules-prefix.pch -MMD -MT dependencies -MF /Users/Me/Library/Developer/Xcode/DerivedData/ProjectApp-epfnoloauyinvagczacvciywwios/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-CoreModules.build/Objects-normal/arm64/RCTAccessibilityManager.d --serialize-diagnostics /Users/Me/Library/Developer/Xcode/DerivedData/ProjectApp-epfnoloauyinvagczacvciywwios/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-CoreModules.build/Objects-normal/arm64/RCTAccessibilityManager.dia -c /Users/Me/Development/ProjectApp/node_modules/react-native/React/CoreModules/RCTAccessibilityManager.mm -o /Users/Me/Library/Developer/Xcode/DerivedData/ProjectApp-epfnoloauyinvagczacvciywwios/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-CoreModules.build/Objects-normal/arm64/RCTAccessibilityManager.o

warning: Capabilities for Signing & Capabilities may not function correctly because its entitlements use a placeholder team ID. To resolve this, select a development team in the ProjectApp editor. (in target 'ProjectApp' from project 'ProjectApp')

objc[66006]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libamsupport.dylib (0x1e0113130) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1043902c8). One of the two will be used. Which one is undefined.
objc[66006]: Class AMSupportURLSession is implemented in both /usr/lib/libamsupport.dylib (0x1e0113180) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x104390318). One of the two will be used. Which one is undefined.
** BUILD FAILED **


The following build commands failed:
	CompileC /Users/Me/Library/Developer/Xcode/DerivedData/ProjectApp-epfnoloauyinvagczacvciywwios/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/React-CoreModules.build/Objects-normal/arm64/RCTActionSheetManager.o /Users/Me/Development/ProjectApp/node_modules/react-native/React/CoreModules/RCTActionSheetManager.mm normal arm64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'React-CoreModules' from project 'Pods')
(1 failure)

info Run CLI with --verbose flag for more details.
error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening ProjectApp.xcworkspace.`

---------------------------------------------------------------------------------------------------------------------------

Of course, I tested thoroughly to ensure that it was the addition of this library that caused the issue. Also, removing the library does not seem to fix my ability to build.

### Expected behavior

I expect the project to build like normal. It's a barebones project atm and it shouldn't be failing like this.

### Reproduction

none

### Platform

- [ ] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [X] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |
| @react-navigation/bottom-tabs          |
| @react-navigation/drawer               |
| @react-navigation/material-bottom-tabs |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                |
| @react-navigation/native-stack         |
| react-native-safe-area-context         |
| react-native-screens                   |
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           |
| expo                                   |
| node                                   |
| npm or yarn                            |

**Comment by bcorrel2** [comment]
Installing a bunch of dependencies and making progress?

**Comment by iamhaaamed** [comment]
same issue:
    "@react-navigation/native": "^6.0.8"
    "@react-navigation/native-stack": "^6.4.1"
    "react": "17.0.2"
    "react-native": "0.67.2"

**Comment by kurisubrooks** [comment]
Also having this issue. The package worked on first build for me, but on second build (after adding @react-nativation/bottom-tabs) it fails with the following issue;

```
path/to/project/node_modules/react-native/React/CoreModules/RCTActionSheetManager.mm:98:35:
  No member named 'cancelButtonTintColor' in 'JS::NativeActionSheetManager::SpecShowActionSheetWithOptionsOptions'
```

I've tried removing the added package and even downgrading various react-navigation packages & versions, but the app continues to refuse to start with this error. Same/similar package versions as above.

**Comment by punjasin** [comment]
remove pods folder and
reinstall pod 
solved this issue but it occur everytime we add new lib
