### ISSUE TITLE
[nativeStack] headerBackImageSource prop, image appears after a delay

### ISSUE THREAD

**Issue by TfADrama** [react-navigation/react-navigation#10300]
### Current behavior

When navigation to a screen on a native stack with the prop headerBackImageSource set to a local image source, the screen appears first with the native headerBackImage and then, after a delay, with my local image.

https://user-images.githubusercontent.com/1742789/151544525-3ce6ac83-79fe-4450-8e3e-37a8899da839.mp4

### Expected behavior

I expected the screen to appear with the local image.

### Reproduction

https://gist.github.com/TfADrama/1c4bcd64a115b10c7c50293f556a6e48

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.0.6|
| @react-navigation/native-stack         | 6.2.5|
| react-native-safe-area-context         |3.3.0|
| react-native-screens                   |3.10.2|
| react-native-gesture-handler           |1.10.3|
| react-native-reanimated                |1.13.3|
| react-native                           |0.65.1|

**Comment by michbil** [comment]
@TfADrama Does problem persist in production mode?
react-native-screens's code has such comment
```// IMPORTANT!!!
      // image can be nil in DEV MODE ONLY
      //
      // It is so, because in dev mode images are loaded over HTTP from the packager. In that case
      // we first check if image is already loaded in cache and if it is, we take it from cache and
      // display immediately. Otherwise we wait for the transition to finish and retry updating
      // header config.
      // Unfortunately due to some problems in UIKit we cannot update the image while the screen
      // transition is ongoing. This results in the settings being reset after the transition is done
      // to the state from before the transition.
```

Had similar issue, built production version, seems to be gone.(or switching very fast and not noticeable).

**Comment by michbil** [comment]
Found workaround for development version of the app(it's pretty annoying to develop with switching icons). The solution will be to place icon in the Images.xcassets in the iOS, to avoid downloading of the image over network.

```
const DefaultHeader: NativeStackNavigationOptions = {
  headerBackImageSource:
        Platform.OS === 'android'
            ? require('../../Resources/Images/Icons/back.png')
            : { uri: 'back', width: 24, height: 24 }, // pull from assets, to avoid icon changing from default to custom
}
```

**Comment by anhtuank7c** [comment]
@michbil Thank you so much.
