### ISSUE TITLE
safeAreaInsets in screenOptions not available after migrating from 5.x to 6.x

### ISSUE THREAD

**Issue by andordavoti** [react-navigation/react-navigation#10301]
### Current behavior

I cannot set a custom safeAreaInsets for a stack navigator.

### Expected behavior

I want to be able to customize the safe area inset for my stack navigator like I could in v5

### Reproduction

https://snack.expo.dev/@andordavoti/no-safeareainsets-screenoptions

### Platform

- [X] Android
- [X] iOS
- [X] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native                     |   6.0.6 |
| @react-navigation/stack                      |   6.0.11|
| react-native-safe-area-context          |   3.3.2|
| react-native-screens                           |   3.10.2|
| react-native-gesture-handler             |   1.10.2|
| react-native-reanimated                    |    2.2.0|
| react-native                                         |    0.64.2|
| node                                  | 14.17.0|
| npm or yarn                     |  1.22.10|

**Comment by satya164** [comment]
> I want to be able to customize the safe area inset for my stack navigator like I could in v5

What exactly do you need to customize?

**Comment by andordavoti** [comment]
When nested inside of a material top tab navigator, the inset size is wrong. In v5 I could fix this by setting the top inset to 10, in screenOptions. However with v6, this is not possible. Please refer to my screenshots. The first one is v5 and the second one is v6, where you can see a huge black space, which is the inset being the wrong size.

![v5-customized-inset](https://user-images.githubusercontent.com/24613178/151584934-012132db-8b42-4dae-99dd-4b31e8d3ada3.jpeg)
![v6](https://user-images.githubusercontent.com/24613178/151584943-5d0715cc-e086-4357-9c3e-82f079664207.png)

**Comment by satya164** [comment]
You can customize statusbar inset with https://reactnavigation.org/docs/elements/#headerstatusbarheight

**Comment by andordavoti** [comment]
> You can customize statusbar inset with https://reactnavigation.org/docs/elements/#headerstatusbarheight

I have tried this, but this does not work in a material tab bar nested stack navigator.

**Comment by satya164** [comment]
> I have tried this, but this does not work in a material tab bar nested stack navigator.

Options don't have anything to do with where it's nested. If there's a bug, please provide an repro. The snack you provided doesn't have a material tab bar.
