### ISSUE TITLE
Deep-link based on hostname

### ISSUE THREAD

**Issue by awkpagong** [react-navigation/react-navigation#10307]
### Current behavior

My app needs to support deep-links from different top-level domains. Here is how I attempted to configure the linking in my app.

```
linking={{
    prefixes: [
        'example://',
        'https://example.com',
        'https://*.example.com',
        'https://example.co.uk',
        'https://*.example.co.uk',
    ]
    // ...
}}
```

However, when I specify the prefixes like this, the prefixes get stripped from the deep-link urls before they are passed to `getStateFromPath`. As a result, I have no way to determine if the path I'm handling corresponds to a `.com` or a `.co.uk` url, which in my company's case needs to be used to determine the country in the app. Furthermore, my company uses the first part of the path to determine the language that the user speaks. For example, the url might be `https://example.com/en/product` for an `en-US` customer, whereas the url might be `https://example.co.uk/fr/product` for a `fr-GB` user. Is there a recommended way to handle these sorts of deep-links where a combination of the hostname and the path is needed to determine the user's country and language?

### Expected behavior

I expected there to be a way to handle deep-links when the hostname and path vary based on country and language.

### Reproduction

https://reactnavigation.org/docs/navigation-container/#linkingprefixes

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | latest
| @react-navigation/bottom-tabs          | latest
| @react-navigation/stack                | latest
| @react-navigation/native-stack         | latest
| react-native-safe-area-context         | latest
| react-native-screens                   | latest
| react-native-gesture-handler           | latest
| react-native                           | latest

**Comment by satya164** [comment]
You should use the `Linking` API directly to get the language from the domain and expose it to your app via context. It doesn't seem like something that needs to be in deep link handling since you're still rendering the same screens, just with a different language - which should ideally be in the context/global store.

**Comment by awkpagong** [comment]
@satya164 thanks, that makes sense in the case of native screens!

I have 1 more question for you - I'm building a hybrid app so I'm confused how I can get the full url to pass onto the webview screens as params. Ideally I'd like the screen to receive params like 

`{ url: 'https://example.com/en/us-specific-product-123' }`,
or
`{ url: 'https://example.co.uk/fr/gb-specific-product-456' }`,
etc

Do you have a recommendation for how I can implement such a thing given React Navigation's api? I'm struggling how to accomplish this using React Navigation's `linking` prop.
