### ISSUE TITLE
useFlipper(): TypeError: undefined is not a function (near '...addPlugin...')

### ISSUE THREAD

**Issue by therealkh** [react-navigation/react-navigation#10302]
### Current behavior

throwing error on start: 
```
TypeError: undefined is not a function (near '...addPlugin...')


This error is located at:
    in RootNavigator (created by RootApp)
    in Provider (at App.tsx:38)
    in RootApp (at CodePush.js:585)
    in CodePushComponent (at renderApplication.js:50)
    in RCTView (at View.js:32)
    in View (at AppContainer.js:92)
    in RCTView (at View.js:32)
    in View (at AppContainer.js:119)
    in AppContainer (at renderApplication.js:43)
    in <projectName>(RootComponent) (at renderApplication.js:60)
```

`
  const navigationContainerRef = useNavigationContainerRef();
  useFlipper(navigationContainerRef);
`

### Expected behavior

Run react navigation debug via Flipper.

### Reproduction

call useFlipper()

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [x] @react-navigation/stack
- [x] @react-navigation/native-stack

### Environment

[!!] I am on Apple Silicon M1 chip.
Flipper version is:  0.127.0

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/devtools                | ^6.0.4
| @react-navigation/native               | ^6.0.2
| @react-navigation/bottom-tabs          |  ^6.0.9
| @react-navigation/stack                | ^6.0.11
| @react-navigation/native-stack         | ^6.1.0
| react-native-safe-area-context         |  ^3.3.0
| react-native-screens                   |  ^3.6.0
| react-native-gesture-handler           | ^1.10.3
| react-native-tab-view                  |  ^3.1.1
| react-native-pager-view                | ^5.4.9
| react-native                           | 0.66
| node                                   | v17.4.0
| npm or yarn                            | 8.4.0

**Comment by cedricfressin** [comment]
According to the docs you should install the `react-native-flipper` package in your app
