### ISSUE TITLE
Params will not merge when navigate to nested navigator

### ISSUE THREAD

**Issue by nekosgr93** [react-navigation/react-navigation#10310]
### Current behavior

I create a simple project to show the problem(Sorry for the ugly style).

Home page and page1 are in their own stack, and page2 is in its own stack too.
When I navigate from home to page1, I pass title and content to page1.
Then, from page1 navigate to page2 and pass only title back.

If I use this pattern, the content disappeared(you can see that in the log).
![image](https://user-images.githubusercontent.com/33030570/151691745-b4b806fe-a3c5-4a77-96db-489fa8b87e01.png)

However, when I set the target name to page1, not the nested stack, it will merge the params as expected.
But typescript will complain on it.
![image](https://user-images.githubusercontent.com/33030570/151691875-4c0e15b5-055d-4567-8bc0-b5a8062aaf65.png)

### Expected behavior

Params will be merged when navigating back to a nested navigator.

### Reproduction

https://codesandbox.io/s/navigation-test-gltgl

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.0.6
| @react-navigation/bottom-tabs          |
| @react-navigation/drawer               |
| @react-navigation/material-bottom-tabs |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                | 6.0.11
| @react-navigation/native-stack         |
| react-native-safe-area-context         |
| react-native-screens                   |
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           |
| expo                                   |
| node                                   |
| npm or yarn                            |

**Comment by satya164** [comment]
`merge: true` needs to be at the correct level for it to merge the params. If you want to `merge` the nested params, then it should be specified in the nested object, not in the root.

**Comment by gorandalum** [comment]
> `merge: true` needs to be at the correct level for it to merge the params. If you want to `merge` the nested params, then it should be specified in the nested object, not in the root.

@satya164 How can you actually specify `merge` on the nested object? There is only possible to specify `merge` on the root level?

Added `merge` param and comment to OPs example:
```tsx
props.navigation.navigate({
  name: "stack1",
  params: {
    screen: "page1",
    params: {
      title: "I am from page2"
    }
    merge: true // This gives typescript error, and doesn't seem to have effect
  }
})
```

I have updated the sandbox with the `merge` param when navigating from page2 to page1, but not having an effect.
https://codesandbox.io/s/navigation-test-forked-xe01q9?file=/src/stack2/page2.tsx
