### ISSUE TITLE
[iOS]: presentation: 'modal' in native-stack locks navigation after navigating to another modal screen too fast

### ISSUE THREAD

**Issue by vzhovnitsky** [react-navigation/react-navigation#10324]
### Current behavior

After we close modal screen with gesture and try to open another modal fast enough navigation within the stack locks and does not seem to work.

```js
import * as React from 'react';
import { Text, View, StyleSheet, Button } from 'react-native';
import { createNativeStackNavigator } from '@react-navigation/native-stack';
import { NavigationContainer } from '@react-navigation/native';
import { useNavigation } from '@react-navigation/native';

export const Modal1 = React.memo(() => {
  return <View style={{ flexGrow: 1, backgroundColor: 'red', opacity: 0.7 }} />;
});

export const Modal2 = React.memo(() => {
  return (
    <View style={{ flexGrow: 1, backgroundColor: 'blue', opacity: 0.7 }} />
  );
});
export const MainScreen = React.memo(() => {
  const navigation = useNavigation();
  return (
    <View
      style={{ flexGrow: 1, justifyContent: 'center', alignItems: 'center' }}>
      <Button title={'Open modal 1'} onPress={() => {
        navigation.navigate('modalScreen-1')
      }}/>
      <Button title={'Open modal 2'} onPress={() => {
        navigation.navigate('modalScreen-2')
      }}/>
    </View>
  );
});

const Stack = createNativeStackNavigator();

export default function App() {
  return (
    <View style={styles.container}>
      <NavigationContainer>
        <Stack.Navigator
          initialRouteName={'main'}
          screenOptions={{
            headerBackTitle: 'Back',
            title: '',
            headerShadowVisible: false,
            headerTransparent: false,
            headerStyle: { backgroundColor: 'white' },
          }}>
          <Stack.Screen key={'main'} name={'main'} component={MainScreen} />
          <Stack.Screen
            key={'modalScreen-1'}
            name={'modalScreen-1'}
            component={Modal1}
            options={{ presentation: 'modal', headerShown: false }}
          />
          <Stack.Screen
            key={'modalScreen-2'}
            name={'modalScreen-2'}
            component={Modal2}
            options={{ presentation: 'modal', headerShown: false }}
          />
        </Stack.Navigator>
      </NavigationContainer>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    backgroundColor: '#ecf0f1',
  },
});

```

https://user-images.githubusercontent.com/32094306/152160248-44ca65b8-3860-43d2-8447-9bc5c4d63ce1.mp4

### Expected behavior

Can not use this in production.

### Reproduction

https://snack.expo.dev/@vzhovnitsky/cranky-apples

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.0.8 |
| @react-navigation/native-stack         | 6.4.0 |
| react-native                           | 0.66.4 |
| expo                                   | 44.0.0 |

**Comment by joshbuckley182** [comment]
I'm also seeing this - it seems that the original view is still not focused from the point-of-view of `react-navigation`, even when it's interactive, immediately after dismissing the overlay. 

I'm tracking updates on this ticket and https://github.com/software-mansion/react-native-screens/issues/1299, but in the meantime if anyone needs a solution, here's a workaround. If the screen is not focused, it waits 300ms before attempting to perform the navigation. 

```ts
setTimeout(
  () => {
    navigation.navigate("DetailView", {
      param: 'whatever',
    });
  },
  navigation.isFocused() ? 0 : 300
);
```

**Comment by ex3ndr** [comment]
I nailed down the issue on iOS side: https://github.com/software-mansion/react-native-screens/blob/ed6a31cca0afc5220e4c12220349ebd30dde7d97/ios/RNSScreenStack.m#L338

This line checks only one controller and the dismissing controller is not the one. Also for some reason controller still detected as "attached" while it is logically not true.

I am not aware how to fix it though.

**Comment by NathanBeesley** [comment]
Hmm. I'm thinking you remove useMemo from the main component and make it a regular component. What happens?
