### ISSUE TITLE
Preventing going back doesn't work with the native stack navigator

### ISSUE THREAD

**Issue by sdandois** [react-navigation/react-navigation#10328]
### Current behavior

I've followed the [preventing going back guide](https://reactnavigation.org/docs/preventing-going-back/) and it was working great. However, after that I've changed the stack navigator with the native stack navigator and the example no longer works. 

The behavior is that the event is still being thrown, but the `e.preventDefault()` action is not working.

### Expected behavior

I would expect the `e.preventDefault()` to prevent going back in the native stack navigator also.

### Reproduction

https://snack.expo.dev/Sj3BtIgCP

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.0.8
| @react-navigation/native-stack         | 6.0.5
| react-native-safe-area-context         | 3.3.2
| react-native-screens                   | ~3.8.0
| react-native-gesture-handler           | ~1.10.2
| react-native-reanimated                | ~2.2.0
| react-native-tab-view                  | ^3.0.0
| react-native-pager-view                | 5.4.6
| expo                                   | 43.0.0

**Comment by sdandois** [comment]
Related https://github.com/software-mansion/react-native-screens/pull/801

**Comment by WoLewicki** [comment]
Yeah, seems like the props from this PR are not added to v6 `native-stack`. cc @kacperkapusciak could you add it there too? Or maybe there is something that prevents us from doing so?
