### ISSUE TITLE
Route params are cached

### ISSUE THREAD

**Issue by Engazan** [react-navigation/react-navigation#10322]
### Current behavior

when navigating with TAB BAR **route** params are cached

### Expected behavior

when navigating with TAB BAR **route** params should be cleared

### Reproduction

https://github.com/react-navigation/react-navigation/discussions/10271

### Platform

- [X] Android
- [X] iOS
- [X] Web
- [X] Windows
- [X] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |^6.0.6
| @react-navigation/bottom-tabs          |^6.0.9
| @react-navigation/native-stack     |^6.2.5
| react-native-screens                   |~3.10.1
| react-native-gesture-handler           |^2.2.0
| react-native-reanimated                |~2.3.1
| react-native                           |0.64.3
| expo                                   | ^44.0.0
| npm or yarn                            | yarn

**Comment by raajnadar** [comment]
Answered in the discussion
