### ISSUE TITLE
containedModal presentation with transparent header has useHeaderHeight value of 0 on iOS

### ISSUE THREAD

**Issue by jstheoriginal** [react-navigation/react-navigation#10333]
### Current behavior

Recent changes to `native-stack` and how the transparent headers work has caused one scenario to have issues still (the other scenarios were recently fixed):

On iOS, a modal screen presented as a `'containedModal'` presentation type that has a transparent header has a header height of 0 returned from `useHeaderHeight`. On Android, it's returning the correct height.

The correct height height was being returned in native-stack version 6.2.5. Then in 6.3.0 it became 0.
The issue was corrected for all but this one scenario in 6.4.1. The issue still happens in 6.4.1/6.5.0 (latest) for this specific presentation mode.

6.2.5 iOS ✅:

<img width="331" alt="Screen Shot 2022-02-08 at 11 07 21 AM" src="https://user-images.githubusercontent.com/5117473/153038687-a558657a-0ea7-4745-876d-b3537ad58913.png">

6.5.0 iOS ❌:

<img width="316" alt="Screen Shot 2022-02-08 at 10 57 06 AM" src="https://user-images.githubusercontent.com/5117473/153039080-1824202f-6031-4ff0-8d11-905a5d26786e.png">

6.5.0 Android ✅:

<img width="321" alt="Screen Shot 2022-02-08 at 11 00 13 AM" src="https://user-images.githubusercontent.com/5117473/153039113-6969ec75-eb74-4c2d-a29f-10adb05cd73b.png">

Snack provided shows the issue.

### Expected behavior

A non-zero header height should be returned for iOS when a transparent header is presented as `containedModal`.

### Reproduction

https://snack.expo.dev/@jstheoriginal/containedmodal-transparent-header-height-0

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| react-native-screens | ~3.8.0
| @react-navigation/native | 6.0.8
| @react-navigation/elements | 1.3.1
| @react-navigation/native-stack | 6.5.0
| react-native-safe-area-context |3.3.2
| expo | 43.0.0

**Comment by jstheoriginal** [comment]
> Couldn't find version numbers for the following packages in the issue:
> 
> * `@react-navigation/bottom-tabs`
> * `@react-navigation/drawer`
> * `@react-navigation/material-bottom-tabs`
> * `@react-navigation/material-top-tabs`
> * `@react-navigation/stack`
> 
> Can you update the issue to include version numbers for those packages? The version numbers must match the format 1.2.3.

All good. not used.

**Comment by klandell** [comment]
I'm having this issue too, though I am seeing the problem for presentation `modal`, `fullScreenModal`, and `containedModal `. I use the `useHeaderHook` in a pretty low level component of my app, so this bug is affecting any screens that uses one of these presentation modes. It might affect the transparent modals too, but I don't use them in my app, so I'm not sure.  They all work in 6.2.5.

**Comment by henrik-d** [comment]
I'm having a similar issue.
```
"@react-navigation/elements": "^1.3.3",
"@react-navigation/native": "^6.0.10",
"@react-navigation/native-stack": "^6.6.1"
```

When showing a Screen inside a native StackNavigator using `presentation: 'modal'`, `useHeaderHeight()` returns `0`: 
```
<Stack.Screen
    name={'Address'}
    options={{
      presentation: 'modal',
    }}
    component={AddressScreen} // useHeaderHeight returns 0 in AddressScreen
  />
```

Whats interesting, when calling `useHeaderHeight()`from a nested StackNavigator that is presented as a modal, it returns the correct value:

```
<Stack.Screen
    options={{ presentation: 'modal', headerShown: false }}
    name={'Auth'}
    component={AuthNavigator} // useHeaderHeight in screens of AuthNavigator return correct value
  />
```

**Comment by gomo** [comment]
This issue is still there in 6.6.2.

As @klandell said, when I downgrade my `@react-navigation/native-stack` to 6.2.5, I get a non-zero value. I get 0 in 6.3.0 and later versions.

**Comment by saikojosh** [comment]
Is there any workaround for this? I've resorted to hardcoding a value if the `useHeaderHeight()` hook returns `0`.
