### ISSUE TITLE
linking not accepting initialRouteName

### ISSUE THREAD

**Issue by icecapp** [react-navigation/react-navigation#10331]
### Current behavior

Adding `initialRouteName` to the linking config under a screen navigator:

1- yields a TS error [as shown in this TS playground](https://www.typescriptlang.org/play?target=7&jsx=5&isolatedModules=false#code/JYWwDg9gTgLgBAbzgOQIYDdgHNU2BAOwGFCZVgCBTKOAXzgDMoIQ4AiAASktQGMYAtAQzZc+AgHphedJTYBuAFCLehAM7wANhQDWFLHAC8iRXDhhuDYAA9KagFxwA2gF0ANKbiqCVrI4SeZmq83JQEDiZmUXAAEiyUACqoAEYRAdHRFMB4qJoAShAArjCUaCCUjmxEABa4amweGXSNUbQtbYq0SooAPGiYOHiEJARkFNRw2gR6BFiGCFMzWPQSAHzyQA)
2- does not render the value as first route when linking to `testlinks://other` from background

However, the following config 

```js
const Home = () => {
  return (
    <Tab.Navigator>
      <Tab.Screen name="TabA" component={ScreenA} />
      <Tab.Screen name="TabB" component={ScreenB} />
      <Tab.Screen name="TabC" component={ScreenC} />
    </Tab.Navigator>
  );
};

const App = () => {
  return (
    <NavigationContainer linking={linking}>
      <Stack.Navigator>
        <Stack.Screen name="HomeTabs" component={Home} />
        <Stack.Screen name="Other" component={OtherScreen} />
      </Stack.Navigator>
    </NavigationContainer>
  );
};
```

```js
const linking: LinkingOptions<RootStackParamList> = {
  prefixes: ['testlinks://'],
  config: {
    screens: {
      HomeTabs: {
        initialRouteName: 'TabA',
        screens: {
          TabA: 'a',
          TabB: 'b',
          TabC: 'c',
          Other: 'other',
        },
      },
      // This works but renders as first route
      // Other: 'other',
    },
  },
  }
  ```
  
  when called with `getStateFromPath('/other', linking.config)` yields the expected output:
  
  ```js
  {
  "routes": [
    {
      "name": "HomeTabs",
      "state": {
        "index": 1,
        "routes": [
          {
            "name": "TabA"
          },
          {
            "name": "Other",
            "path": "/other"
}]}}]}
```

Did the API for `initialRouteName` change without the docs? 
Why don't the typings accept `initialRouteName`? 
What is the correct setup to deep link to a Stack.Screen with the first route in `state.routes` being a nested Screen of a sibling Navigator (i.e. deep linked screen would have a back button to `initialRouteName`) ?

### Expected behavior

Expect the `linking` prop type to match description and work as described in [Rendering an Initial Route](https://reactnavigation.org/docs/configuring-links#rendering-an-initial-route)

### Reproduction

https://www.typescriptlang.org/play?target=7&jsx=5&isolatedModules=false#code/JYWwDg9gTgLgBAbzgOQIYDdgHNU2BAOwGFCZVgCBTKOAXzgDMoIQ4AiAASktQGMYAtAQzZc+AgHphedJTYBuAFCLehAM7wANhQDWFLHAC8iRXDhhuDYAA9KagFxwA2gF0ANKbiqCVrI4SeZmq83JQEDiZmUXAAEiyUACqoAEYRAdHRFMB4qJoAShAArjCUaCCUjmxEABa4amweGXSNUbQtbYq0SooAPGiYOHiEJARkFNRw2gR6BFiGCFMzWPQSAHzyQA

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | ^6.0.8
| @react-navigation/bottom-tabs          | ^6.2.0
| @react-navigation/drawer               |
| @react-navigation/material-bottom-tabs |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                | "^6.1.1"
| @react-navigation/native-stack         | 
| react-native-safe-area-context         | "^3.3.2"
| react-native-screens                   | "^3.9.0"
| react-native-gesture-handler           | "^1.10.3"
| react-native-reanimated                |
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           | "0.67.1"
| expo                                   |
| node                                   | v16.2.0
| npm or yarn                            | 8.3.1  \ 1.22.10

**Comment by satya164** [comment]
https://reactnavigation.org/docs/typescript/#specifying-default-types-for-usenavigation-link-ref-etc

**Comment by FadiAboMsalam** [comment]
@icecapp  how did you solve the issue ?
