### ISSUE TITLE
headerBlurEffect with headerLargeTitle

### ISSUE THREAD

**Issue by Gregoirevda** [react-navigation/react-navigation#10339]
### Current behavior

When headerBlurEffect is used with headerLargeTitle, both the large title area and the header are blurred

### Expected behavior

Only the header bar should be blurred

### Reproduction

https://snack.expo.dev/

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.0.6
| react-native-screens                   | 3.10.1
| react-native                           | 0.66.4

**Comment by Gregoirevda** [comment]
Works with those options

```javascript
options={{
            headerTransparent: true,
            headerTitle: 'Title',
            headerLargeTitle: true,
            headerBlurEffect: 'regular',
            headerLargeStyle: {
              backgroundColor: PlatformColor('systemGroupedBackgroundColor'), // Color of your background
            },
          }}
```

**Comment by hems** [comment]
> headerTransparent: true,
>             headerTitle: 'Title',
>             headerLargeTitle: true,
>             headerBlurEffect: 'regular',
>             headerLargeStyle: {
>               backgroundColor: PlatformColor('systemGroupedBackgroundColor'), // Color of your background
>             },

for some reason this only works for me on iOS Simulator, not on real device even tough iOS version is the same on both.

any ideas?

thanks a lot!

**Comment by mihalikv** [comment]
Same issue here, I am able to make `headerLargeStyle` to work on simulator but not on real device. Did you found some solution  @hems ?
