### ISSUE TITLE
go back and go forward button wrong

### ISSUE THREAD

**Issue by gyl89** [react-navigation/react-navigation#10355]
### Current behavior

Let's say I have two links A and B of my react native web app.
I start the navigation from a third-party page. I then enter the link to A. I go to page B using the hook useLinkTo(); I then go to page A using the same hook. At this point, my browser's "go forward" button can be pressed and sent me to page B. The browser's "go backward" button can also be pressed and sent me to the original third-party page.

### Expected behavior

I would expect the "go forward" button not being active. I would expect the back button to sent me to page B.

### Reproduction

not_today

### Platform

- [ ] Android
- [ ] iOS
- [X] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [X] @react-navigation/native-stack

### Environment

    "@react-navigation/native": "6.0.8",
    "@react-navigation/native-stack": "6.5.0",
    "@react-navigation/stack": "6.1.1",

**Comment by CarlosHdez** [comment]
Probably similar to #10263? In case the workaround there works for you
