### ISSUE TITLE
React Navigation Drawer opens a little when screen rotate

### ISSUE THREAD

**Issue by elmcapp** [react-navigation/react-navigation#10368]
### Current behavior

On iOS 15 device the drawer opens a little when screen rotate.

https://user-images.githubusercontent.com/64275658/154790762-579f2f54-32f5-4b58-a778-a05840251091.mp4

 

### Expected behavior

drawer should stay closed when screen rotate

### Reproduction

I have video

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |
| @react-navigation/bottom-tabs          |
| @react-navigation/drawer               |
| @react-navigation/material-bottom-tabs |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                |
| @react-navigation/native-stack         |
| react-native-safe-area-context         |
| react-native-screens                   |
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           |
| expo                                   |
| node                                   |
| npm or yarn                            |

**Comment by elmcapp** [comment]
"@react-navigation/bottom-tabs": "^6.2.0",
    "@react-navigation/drawer": "^6.3.1",
    "@react-navigation/material-bottom-tabs": "^6.1.1",
    "@react-navigation/material-top-tabs": "^6.1.1",
    "@react-navigation/native": "^6.0.8",
    "@react-navigation/stack": "^6.1.1",
     "react": "17.0.2",
    "react-native": "0.67.2",

**Comment by elmcapp** [comment]
still have this problem

**Comment by elmcapp** [comment]
still have this problem

**Comment by elmcapp** [comment]
Still having this issue

**Comment by vcellu** [comment]
We are also experiencing the same issue.

**Comment by alexstanbury** [comment]
Same issue here...

**Comment by ankuragrawal29** [comment]
We are also experiencing the same issue.

**Comment by Dzban-Diego** [comment]
I also get the same issue. After few hours i manage to find solution. 
The bug was present only when i add `width: '100%` to `drawerStyle`. I need the drawer to be full screen. 
I simple change it to `width: dimentions.width` to set width as the screen, and this is working as expected.

**Comment by JairajJangleSLIOT** [comment]
Facing the same issue, why is this issue closed in spite of so many user actively reporting this issue?

**Comment by Dhananjay-JSR** [comment]
Can you please provide a https://snack.expo.dev/ links for reproducing this issue with minimal setup

**Comment by nimabk82** [comment]
any solution for this issue ?

**Comment by ninamargretdadadottir** [comment]
This worked for me:

<Drawer.Navigator
      defaultStatus={'closed'}
      drawerStyle: {
          width: Dimensions.get('window').width
        }>

**Comment by SagarAhir** [comment]
I am also facing this issue, Dimensions.get('window').width didn't work for me. also I have notice this issue while i am using drawerPosition: "right"

**Comment by klendi** [comment]
I tried @ninamargretdadadottir solution and it worked. It seems like to act weird when applied custom width.

This worked for me:

```js         
const width = Dimensions.get("window").width;

....

drawerStyle: {
          width: width * 0.8,
        },
```

**Comment by ankuragrawal29** [comment]
any luck with this issue?

**Comment by JJSLIoT** [comment]
Can we please reopen this issue, this is still affecting many users!

**Comment by rozekfr** [comment]
Same here, please solve it or reopen the issue.

**Comment by nijatkazimliPG** [comment]
I face this issue as well.

**Comment by anandsharmaautovyn** [comment]
+1 please open the issue again
