### ISSUE TITLE
Argument of type '{ headerSearchBarOptions

### ISSUE THREAD

**Issue by Kottidev** [react-navigation/react-navigation#10366]
### Current behavior

An error headerSearchBarOptions does not exist in type 'Partial<StackNavigationOptions>'.ts

<img width="684" alt="image" src="https://user-images.githubusercontent.com/12915009/154703057-79e8b8fb-a306-4c81-83ea-bb5843526a8c.png">

Argument of type '{ headerSearchBarOptions: { onChangeText: (event: any) => void; }; autoFocus: boolean; }' is not assignable to parameter of type 'Partial<StackNavigationOptions>'.
  Object literal may only specify known properties, and 'headerSearchBarOptions' does not exist in type 'Partial<StackNavigationOptions>'.ts(2345)

### Expected behavior

headerSearchBarOptions should be added to  type 'Partial<StackNavigationOptions>'.ts

### Reproduction

typescript

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [X] @react-navigation/native-stack

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.0.8
| @react-navigation/bottom-tabs          | 6.2.0
| @react-navigation/drawer               |
| @react-navigation/material-bottom-tabs |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                | 6.1.1
| @react-navigation/native-stack         | 6.4.1
| react-native-safe-area-context         |
| react-native-screens                   |
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           |
| expo                                   |
| node                                   |
| npm or yarn                            |

**Comment by m-sayari** [comment]
@Kottidev  You are probably mixing **Stack navigator** and **Native stack navigator** options.

`headerSearchBarOptions` is a property of `NativeStackNavigationOptions` type but not a property of `StackNavigationOptions`

Your screen props should be of type `NativeStackScreenProps` instead of `StackScreenProps`
