### ISSUE TITLE
"Go Back" swipe gesture now working with Drawer Navigator on iOS

### ISSUE THREAD

**Issue by thevinter** [react-navigation/react-navigation#10371]
### Current behavior

The Navigator is not responding to Swipe Back gestures using a Drawer Navigator on my iOS device while it works perfectly fine on an Android one.

### Expected behavior

I expect the navigator to go back once the swipe gesture is detected.

### Reproduction

https://gist.github.com/thevinter/aa03582484f7f1aa83f7db850009b268

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.0.8
| @react-navigation/drawer               |  6.3.1
| react-native-safe-area-context         | 3.3.2
| react-native-screens                   | 3.10.1
| react-native-gesture-handler           | 2.2.0
| react-native-reanimated                | 2.4.1
| react-native                           | 0.64.3
| expo                                   | 44.0.0

**Comment by thevinter** [comment]
I discovered that the Drawer Navigator doesn't natively support gestures (Which is a pity). I'll figure something out.

**Comment by hraschan** [comment]
@thevinter Did you find a solution to support ios back guesture with Drawer Navigation?

**Comment by thevinter** [comment]
I haven't been working on the application for a while now but if I remember correctly the solution was to implement the swipe manually

**Comment by hraschan** [comment]
@thevinter Could you maybe provide some basic implementation code?
