### ISSUE TITLE
@react-navigation/native-stack and headerTitleAlign left on ios doesn't work

### ISSUE THREAD

**Issue by marcoturi** [react-navigation/react-navigation#10378]
### Current behavior

headerTitleAlign: left property doesn't work on Ios using @react-navigation/native-stack (6.5.0). Property is ignored.

### Expected behavior

The Header title should be aligned on left.

Note: on @react-navigation/native title alignment looks fine.

### Reproduction

https://snack.expo.dev/lqMePNrQs

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack

### Environment

    "@react-navigation/bottom-tabs": "6.2.0",
    "@react-navigation/native": "6.0.8",
    "@react-navigation/native-stack": "6.5.0",
    "react-native": "0.66.0",
    "react-native-screens": "3.12.0",
Node 16
yarn 1.22.17

Not used:
@react-navigation/drawer
@react-navigation/material-bottom-tabs
@react-navigation/material-top-tabs
@react-navigation/stack

**Comment by satya164** [comment]
This is already documented, not a bug
https://reactnavigation.org/docs/native-stack-navigator/#headertitlealign

**Comment by marcoturi** [comment]
@satya164 you are right!
However is theoretically possibile to achieve it:

https://github.com/react-navigation/react-navigation/blob/94ab791cae5061455f036cd3f6bc7fa63167e7c7/packages/native-stack/src/views/HeaderConfig.tsx#L190 
-> Temporary comment title property

https://github.com/react-navigation/react-navigation/blob/94ab791cae5061455f036cd3f6bc7fa63167e7c7/packages/native-stack/src/views/HeaderConfig.tsx#L209
-> replace ScreenStackHeaderCenterView with ScreenStackHeaderLeftView

use a component for the property of headerTitle.

Please consider implement this feature.

**Comment by satya164** [comment]
> replace ScreenStackHeaderCenterView with ScreenStackHeaderLeftView

That's going to replace the back button on the screen which isn't what `headerTitleAlign` does. If you want to replace back button, you can already do that by specifying a custom `headerLeft`.
