### ISSUE TITLE
Cannot get back button when navigating from one navigator to another

### ISSUE THREAD

**Issue by abhishek-pokhriyal** [react-navigation/react-navigation#10372]
### Current behavior

My app structure is like this

```
Root - bottom tab naivgator
   A - stack navigator
      1. Home screen
      2. Cart screen

   B - stack navigator
      1. Checkout screen
      2. Payment screen
```

Now when I navigate to Cart screen from checkout screen, there is no back button on the checkout screen. How can I achieve this functionality.

### Expected behavior

Need a back button when navigating from one stack to another to go back to the end of the previous stack.

### Reproduction

https://snack.expo.dev/

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |
| @react-navigation/bottom-tabs          |
| @react-navigation/drawer               |
| @react-navigation/material-bottom-tabs |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                |
| @react-navigation/native-stack         |
| react-native-safe-area-context         |
| react-native-screens                   |
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           |
| expo                                   |
| node                                   |
| npm or yarn                            |

**Comment by nobady90** [comment]
I have the same problem, after logging in and then changing Drawer.Navigator the android back button does not work, while the one managed manually in the header works correctly. If I close and reopen the app, I am still logged in and this time the android back button will start working again. So it is as if this functionality is lost when changing the Drawer.Navigator after login.

these are my versions:

```
"@react-navigation/core": "^6.1.1",
"@react-navigation/drawer": "^6.3.1",
"@react-navigation/native": "^6.0.8",
"@react-navigation/native-stack": "^6.2.5",
"@react-navigation/routers": "^6.1.0",
"@react-navigation/stack": "^6.1.1",
```
    
if you need anything else let me know, thanks.
