### ISSUE TITLE
Bad tabbar display during app startup

### ISSUE THREAD

**Issue by maximewim** [react-navigation/react-navigation#10382]
### Current behavior

I use the bottom bar in the application. When I open the application, for half a second, the tab bar is not displayed correctly, at the bottom of the screen. See the vide

https://user-images.githubusercontent.com/89021780/155561613-d8e07763-2995-4c3f-acf5-277bfe10ff7f.mp4

o

### Expected behavior

Tab bar should be rendering at the bottom of the screen. 

### Reproduction

/

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.0.6
| @react-navigation/bottom-tabs          | 6.0.9
| @react-navigation/native-stack         | 6.2.5
| react-native-safe-area-context         |3.3.2
| react-native-screens                   | 3.10.1
| react-native                           | 0.66.2
| node                                   | v14.18.0
| yarn                            | 1.22.15

**Comment by maximewim** [comment]
> Couldn't find version numbers for the following packages in the issue:
> 
>     * `@react-navigation/drawer`
> 
>     * `@react-navigation/material-bottom-tabs`
> 
>     * `@react-navigation/material-top-tabs`
> 
>     * `@react-navigation/stack`
> 
> 
> Can you update the issue to include version numbers for those packages? The version numbers must match the format 1.2.3.
> 
> The versions mentioned in the issue for the following packages differ from the latest versions on npm:
> 
>     * `@react-navigation/native` (found: `6.0.6`, latest: `6.0.8`)
> 
>     * `@react-navigation/bottom-tabs` (found: `6.0.9`, latest: `6.2.0`)
> 
> 
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?

These packages are not used and the error is still there after upgrading to le latest version.

**Comment by MasterRedStorm** [comment]
the same issue Exists with @react-navigation/material-bottom-tabs
`
used versions:
"@react-navigation/material-bottom-tabs": "6.1.1",
"@react-navigation/native": "6.0.8",
`

issue persists when using stack, native-stack or simple FunctionlComponent as Screen in material-bottom-tabs.
it also persists whether the bottom-tab is nested inside a safeAreaView or not
All Packages use the latest version.

usage of StatusBar->translucent dosnt solve the problem ( seen here: https://github.com/react-navigation/react-navigation/issues/7665 )
similar issue as https://github.com/react-navigation/react-navigation/issues/7665
