### ISSUE TITLE
TabBarStyle is overwriting instead of merging

### ISSUE THREAD

**Issue by Navipro70** [react-navigation/react-navigation#10383]
### Current behavior

In specific cases I wanna hide tab bar, but when I show it again, my tabBarStyle specified at `<Stack.Navigator screensOptions={{tabBarStyle: {...}}} /> ` fully overwrites with new tabBarStyle:
```
navigation.setOptions({
  tabBarStyle: {
    display: isTabVisible ? 'flex' : 'none',
  },
});
```

### Expected behavior

New tabBarStyle object will merge with previous tabBarStyle, instead of overwriting it.

### Reproduction

No

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

```
"@react-navigation/bottom-tabs": "^6.2.0"
"@react-navigation/elements": "^1.3.1"
"@react-navigation/native": "^6.0.8"
"@react-navigation/stack": "^6.1.1"
```

**Comment by longtqdayma** [comment]
Use custom Tabbar MyTabBar
https://reactnavigation.org/docs/bottom-tab-navigator/
