### ISSUE TITLE
cancelButtonTintColor

### ISSUE THREAD

**Issue by miguel-rios-r** [react-navigation/react-navigation#10385]
### Current behavior

bottom-tabs are failed on iOS because it is looking for an option called "cancelButtonTintColor" and it is responses it is not created.

I fixed it Into my project reusing `UIColor:options.tintColor()` instead `UIColor:options. cancelButtonTintColor()`

I did it in the line 98 of RCTActionSheetManager.h

my line looks like: `UIColor *cancelButtonTintColor =
    [RCTConvert UIColor:options.tintColor() ? @(*options.tintColor()) : nil];`

### Expected behavior

It just should be created and allow builds normally

### Reproduction

no-public-repo

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |
| @react-navigation/bottom-tabs          |
| @react-navigation/drawer               |
| @react-navigation/material-bottom-tabs |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                |
| @react-navigation/native-stack         |
| react-native-safe-area-context         |
| react-native-screens                   |
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           |
| expo                                   |
| node                                   |
| npm or yarn                            |

**Comment by longtqdayma** [comment]
use
import { HeaderBackButton } from '@react-navigation/stack';
