### ISSUE TITLE
React Native Navigation Parameters don't update

### ISSUE THREAD

**Issue by hardikcc** [react-navigation/react-navigation#10399]
### Current behavior

I have a drawer navigation with react navigation 6.0. On screen 1, I have created a buttons inside FlatList which navigates to Screen 2.

`navigation.navigate("VideoCall", { token: Token, roomname: roomname });`

Now after task from Screen 2 is over, user is sent back to screen 1 and he has to start another task. So he will click another button, that should send different room name and token.

Issue is that I am receiving the token and room name sent on first attempt every time.

### Expected behavior

It should send updated parameter to the second screen.

### Reproduction

<div data-snack-id="@hardikcc/passing-parameters-to-routes-|-react-navigation" data-snack-platform="web" data-snack-preview="true" data-snack-theme="light" style="overflow:hidden;background:#F9F9F9;border:1px solid var(--color-border);border-radius:4px;height:505px;width:100%"></div> <script async src="https://snack.expo.dev/embed.js"></script>

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |^6.0.8
| @react-navigation/bottom-tabs          |
| @react-navigation/drawer               |^6.3.1
| @react-navigation/material-bottom-tabs |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                |
| @react-navigation/native-stack         |
| react-native-safe-area-context         |"^4.0.1"
| react-native-screens                   |"^3.12.0"
| react-native-gesture-handler           |"^2.2.0"
| react-native-reanimated                |"^2.4.1"
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           |"0.67.3"
| expo                                   |
| node                                   |
| npm or yarn                            |

**Comment by hardikcc** [comment]
https://snack.expo.dev/@hardikcc/passing-parameters-to-routes-|-react-navigation

**Comment by hardikcc** [comment]
> Couldn't find version numbers for the following packages in the issue:
> 
> * `@react-navigation/bottom-tabs`
> * `@react-navigation/material-bottom-tabs`
> * `@react-navigation/material-top-tabs`
> * `@react-navigation/stack`
> 
> Can you update the issue to include version numbers for those packages? The version numbers must match the format 1.2.3.

I am not using those packages.

**Comment by satya164** [comment]
You're not using correct dependency array, your params need to be in the dependency array if you're using it in the function

**Comment by hardikcc** [comment]
Thanks Satya, got that working as per your input.
