### ISSUE TITLE
Android: additional back button when providing a [headerTitle] in native-stack

### ISSUE THREAD

**Issue by adsellor** [react-navigation/react-navigation#10391]
### Current behavior

There is an additional native back button present in the andorid, when `headerTitle` is provided in the `Stack.Screen`, nested within `Stack.Group` with a custom `headerLeft`.
I believe the issue comes from [this line](https://github.com/react-navigation/react-navigation/blob/main/packages/native-stack/src/views/HeaderConfig.tsx#L136) , where `backButtonCustomView` is set to true, whenever custom React Element is provided to the `headerTitle`, and this [this line](https://github.com/react-navigation/react-navigation/blob/main/packages/native-stack/src/views/HeaderConfig.tsx#L219) renders custom `headerLeftElement` as expected. 

### Expected behavior

There should be no native back button present, whenever custom `headerLeft` is provided to the `Stack.Group`. 

### Reproduction

https://snack.expo.dev/re5qShMZr

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.0.8
| @react-navigation/bottom-tabs          | 6.2.0
| @react-navigation/drawer               | 6.3.0
| @react-navigation/stack                | 6.1.1
| @react-navigation/native-stack         | 6.4.1
| react-native-safe-area-context         | 3.2.0
| react-native-screens                   | 3.4.0
| react-native-gesture-handler           | 1.10.3
| react-native-reanimated                | 2.2.4
| react-native-pager-view                | 4.1.6
| react-native                           | 0.66.1
| node                                   | 16.13.0
| yarn                            | 1.22.17

**Comment by longtqdayma** [comment]
I use
import { HeaderBackButton } from '@react-navigation/stack';

**Comment by adsellor** [comment]
> I use import { HeaderBackButton } from '@react-navigation/stack';

It will still duplicate the back button in the provided scenario.

**Comment by tstampfel** [comment]
Same issue. Back button pops up when using headerTitle even if it was removed in headerLeft.

**Comment by bradjones1** [comment]
Can confirm as well... I ended up hiding the `headerLeft` element and including the back button in my custom header as a work-around.

**Comment by pekkahaka** [comment]
I can confirm this as well. 
The "extra" back button appears even though custom headerLeft is defined in Android.
This happens when headerTitle is defined as React.Element.
The extra back button does not appear if headerTitle is defined as string

**Comment by klandell** [comment]
Has anyone here found a workaround to this issue while still using a React.Element headerTitle?

**Comment by bang9** [comment]
+1

**Comment by klandell** [comment]
I actually found the solution to this.  Simply set `headerBackVisible: false` in your screenOptions for the native stack navigator.

**Comment by bradjones1** [comment]
https://github.com/react-navigation/react-navigation/issues/10391#issuecomment-1184769524 isn't actually a solution. This issue is about the fact that there is an _extra_ back button when you specify the header contents, but do not intend to override the back button.

What this comment is basically describing is part of the _work-around_ to this bug.

**Comment by JuanRdBO** [comment]
Is this being worked on? This issue still persists
