### ISSUE TITLE
Drawer unstable behavior with nested navigators with deferent types (drawer+tabs+stacks) in real andriod phone

### ISSUE THREAD

**Issue by KimzCodes** [react-navigation/react-navigation#10408]
### Current behavior

The drawer is doing weird behaviour when having nested navigators (please have look to schema section or repo):

1) Click in drawer screen: new screen open and drawer not closed
2) Click in drawer screen: new screen open and the drawer closed and open again
3) Click in button with navigation.toggleDrawer() twice:  no response and drawer not open OR open and cant close
 

**Schema:**
  Drawer.Navigator
     Drawer.Screen => Home [Tab Navigator ]
     Drawer.Screen => Profile [Natcive Stack Navigator]

**Versions:**
 "@react-navigation/bottom-tabs": "^6.2.0",
    "@react-navigation/drawer": "^6.3.1",
    "@react-navigation/native": "^6.0.8",
    "@react-navigation/native-stack": "^6.5.0",
   "react-native-gesture-handler": "~2.1.0",
    "react-native-paper": "^4.11.2",
    "react-native-reanimated": "~2.3.1",
    "react-native-safe-area-context": "3.3.2",
    "react-native-screens": "~3.10.1",

### Expected behavior

animation should be smooth more than current

### Reproduction

https://github.com/KimzCodes/drawer-issue

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [X] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [X] @react-navigation/native-stack

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |
| @react-navigation/bottom-tabs          |
| @react-navigation/drawer               |
| @react-navigation/material-bottom-tabs |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                |
| @react-navigation/native-stack         |
| react-native-safe-area-context         |
| react-native-screens                   |
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           |
| expo                                   |
| node                                   |
| npm or yarn                            |

**Comment by KimzCodes** [comment]
"@react-navigation/bottom-tabs": "^6.2.0",
    "@react-navigation/drawer": "^6.3.1",
    "@react-navigation/native": "^6.0.8",
    "@react-navigation/native-stack": "^6.5.0",
    "expo": "~44.0.0",
    "expo-status-bar": "~1.2.0",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-native": "0.64.3",
    "react-native-gesture-handler": "~2.1.0",
    "react-native-paper": "^4.11.2",
    "react-native-reanimated": "~2.3.1",
    "react-native-safe-area-context": "3.3.2",
    "react-native-screens": "~3.10.1",
    "react-native-web": "0.17.1"

**Comment by zoobibackups** [comment]
> ### Current behavior
> The drawer is doing weird behaviour when having nested navigators (please have look to schema section or repo):
> 
> 1. Click in drawer screen: new screen open and drawer not closed
> 2. Click in drawer screen: new screen open and the drawer closed and open again
> 3. Click in button with navigation.toggleDrawer() twice:  no response and drawer not open OR open and cant close
> 
> **Schema:** Drawer.Navigator Drawer.Screen => Home [Tab Navigator ] Drawer.Screen => Profile [Natcive Stack Navigator]
> 
> **Versions:** "@react-navigation/bottom-tabs": "^6.2.0", "@react-navigation/drawer": "^6.3.1", "@react-navigation/native": "^6.0.8", "@react-navigation/native-stack": "^6.5.0", "react-native-gesture-handler": "~2.1.0", "react-native-paper": "^4.11.2", "react-native-reanimated": "~2.3.1", "react-native-safe-area-context": "3.3.2", "react-native-screens": "~3.10.1",
> 
> ### Expected behavior
> animation should be smooth more than current
> 
> ### Reproduction
> https://github.com/KimzCodes/drawer-issue
> 
> ### Platform
> * [x]  Android
> * [ ]  iOS
> * [ ]  Web
> * [ ]  Windows
> * [x]  MacOS
> 
> ### Packages
> * [x]  @react-navigation/bottom-tabs
> * [x]  @react-navigation/drawer
> * [ ]  @react-navigation/material-bottom-tabs
> * [ ]  @react-navigation/material-top-tabs
> * [x]  @react-navigation/stack
> * [x]  @react-navigation/native-stack
> 
> ### Environment
> * [] I've removed the packages that I don't use
> 
> package	version
> @react-navigation/native	
> @react-navigation/bottom-tabs	
> @react-navigation/drawer	
> @react-navigation/material-bottom-tabs	
> @react-navigation/material-top-tabs	
> @react-navigation/stack	
> @react-navigation/native-stack	
> react-native-safe-area-context	
> react-native-screens	
> react-native-gesture-handler	
> react-native-reanimated	
> react-native-tab-view	
> react-native-pager-view	
> react-native	
> expo	
> node	
> npm or yarn

I am facing the same issue, when i close drawer it reopened again sometimes. 
Really weird behaviour.

**Comment by raajnadar** [comment]
Try this props https://reactnavigation.org/docs/drawer-navigator/#uselegacyimplementation

And let me know if this works as a workaround. And @KimzCodes you need to fill the versions in the original post.

**Comment by zoobibackups** [comment]
> Try this props https://reactnavigation.org/docs/drawer-navigator/#uselegacyimplementation
> 
> And let me know if this works as a workaround. And @KimzCodes you need to fill the versions in the original post.

i downgrade to v5, its 10times faster than v6 with no issues

**Comment by KimzCodes** [comment]
> Try this props https://reactnavigation.org/docs/drawer-navigator/#uselegacyimplementation
> 
> And let me know if this works as a workaround. And @KimzCodes you need to fill the versions in the original post.

**Comment by KimzCodes** [comment]
> https://reactnavigation.org/docs/drawer-navigator/#uselegacyimplementation

i will do same thing v5 has no issue

**Comment by KimzCodes** [comment]
> > Try this props https://reactnavigation.org/docs/drawer-navigator/#uselegacyimplementation
> > And let me know if this works as a workaround. And @KimzCodes you need to fill the versions in the original post.
> 
> i downgrade to v5, its 10times faster than v6 with no issues



> Try this props https://reactnavigation.org/docs/drawer-navigator/#uselegacyimplementation
> 
> And let me know if this works as a workaround. And @KimzCodes you need to fill the versions in the original post.

**Comment by raajnadar** [comment]
What did you do downgrade or used the legacy implementation??

**Comment by Julio-de-Leon** [comment]
is it better to downgrade or use useLegacyImplementation?

**Comment by raajnadar** [comment]
Use legacy so that once this is fixed you only need to toggle the props.
