### ISSUE TITLE
[TypeScript] onStateChange should be typed to allow async functions

### ISSUE THREAD

**Issue by eliw00d** [react-navigation/react-navigation#10404]
### Current behavior

An example [here](https://reactnavigation.org/docs/5.x/screen-tracking/) shows an async function being passed to onStateChange.

However, when using TypeScript in a component that wraps NavigationContainer and doing the same thing, I get the following lint error:
```
95:21  error  Promise-returning function provided to attribute where a void return was expected  @typescript-eslint/no-misused-promises
```

### Expected behavior

When using TypeScript in a component that wraps NavigationContainer and giving onStateChange an async function, [the type for onStateChange](https://github.com/react-navigation/react-navigation/blob/%40react-navigation/native%406.0.8/packages/core/src/types.tsx#L274) allows for a Promise being returned.

### Reproduction

https://github.com/eliw00d/react-navigation-issues-repro

### Platform

- [ ] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.0.8
| node                                   | 16.13.0
| yarn                            | 3.0.2

**Comment by eliw00d** [comment]
The type in question is here: https://github.com/react-navigation/react-navigation/blob/2f8cbfcc593d92080b73f9cd5d31f4d1ab22b768/packages/core/src/types.tsx#L274

**Comment by eliw00d** [comment]
Added a repro that uses the latest versions.

**Comment by satya164** [comment]
That's a lint rule from typescript-eslint that you have configured in your project, not TypeScript. The return type is correctly annotated as `void` which means you can return whatever you want including a promise since react-navigation doesn't care about the value.

**Comment by eliw00d** [comment]
> That's a lint rule from typescript-eslint that you have configured in your project, not TypeScript. The return type is correctly annotated as `void` which means you can return whatever you want including a promise since react-navigation doesn't care about the value.

Thank you for the quick response @satya164.

Although it is a lint rule from typescript-eslint, that does not make it an invalid request. A return type of `void` is not the same as `Promise<void>`. You could change the return type to `void | Promise<void>` and that would fix the issue. If I patch types.tsx in that way, I no longer get the error.

**Comment by satya164** [comment]
Making changes to make third-party lint rules happy adds additional overhead. You mentioned `onStateChange`, but there are a lot of APIs in React Navigation that accept a callback, all of those places need to be changed as well. I have limited time and I don't want to add additional overhead for behaviour that's not in TypeScript by default.

The return type `void` means you can return anything, and a majority of TypeScript code is written that way. The lint rule assumes return type `void` means you shouldn't be able to return a `Promise` which changes the actual intention of the code, it also feels pretty weird and probably will cause this issue with a lot of libraries. You can also disable this specific option (`checksVoidReturn`).

**Comment by eliw00d** [comment]
@satya164 That is fair. I actually did come across [this](https://github.com/typescript-eslint/typescript-eslint/issues/4619) which seems to have boiled down to either adding more granular options for checksVoidReturn or a custom wrapper. I will go in one of those directions, then.

**Comment by eliw00d** [comment]
Also, as an aside, this _only_ started to happen with the latest version of @typescript-eslint, due to [this](https://github.com/typescript-eslint/typescript-eslint/pull/4541).
