### ISSUE TITLE
Nested drawers not working with @react-navigation/drawer 6.3.1

### ISSUE THREAD

**Issue by stef1103** [react-navigation/react-navigation#10418]
### Current behavior

After updating @react-navigation/drawer to 6.3.1 nested drawers are not working correctly.
I have a left drawer nested inside a right one, the right one is not displaying correctly with wrong animation and starting position.

With @react-navigation/drawer 6.3.0 everything is working fine

I'm using hermes in both android and iOS with react-native-reanimated 2 enabled

### Expected behavior

Nested drawers to work correctly as with @react-navigation/drawer 6.3.0

### Reproduction

https://github.com/stef1103/drawerissue

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |6.0.8
| @react-navigation/drawer               |6.3.1
| @react-navigation/stack                |6.1.1
| react-native-safe-area-context         |4.1.2
| react-native-screens                   |3.13.1
| react-native-gesture-handler           |2.3.1
| react-native-reanimated                |2.4.1
| react-native                           |0.67.3
| node                                   |16.14.0
| npm                           |8.3.1

**Comment by mmmoussa** [comment]
Can confirm this is a bug with `@react-navigation/drawer` v6.3.1. I am experiencing the same issue in my app and downgrading to v6.3.0 fixed it.

**Comment by govind1530** [comment]
yes, this issue occur in v6.3.1 . i have to downgrade to v6.3.0 and its working fine.

**Comment by JoeyFenny** [comment]
Can confirm the same here.

I have nested drawers. One on the left. One on the right. When I use 6.3.1 the one on the right has the wrong starting position.

When I downgrade to 6.3.0 it works as expected.

**Comment by Srh07** [comment]
Downgrading to 6.3.0 fixes it.
I did a lot of testing for iPadOS. This issue is not the same for all devices or iPadOS. Depending on which solution you try (right: 0 depening on OS or screen width) there's always at least one device where this issue occurs. 
After downgrading it works on all devices, thanks for the fix!

**Comment by ryansyrl** [comment]
Hello, i have the similar issue, nested drawer with tab and stack. tried to downgrade the drawer version to 6.3.0 & now using 6.1.4 seems not working.. the app stuck on the splash screen. i tried the stack navigation as the entry route, and the drawer i wrapped inside stack navigation the result still the same. what is wrong with my code?
![code](https://user-images.githubusercontent.com/67872022/159205877-a4d26598-f90c-4e13-b916-97197edbf762.png)

**Comment by stef1103** [comment]
Fixed by a3fad5b37b4fbb194071b25286767a81d52f8096

**Comment by outaTiME** [comment]
Something related here?

https://github.com/react-navigation/react-navigation/issues/10434#issuecomment-1092321728

**Comment by mm-webx** [comment]
```
"@react-navigation/drawer": "^6.4.1",
"@react-navigation/native": "^6.0.10",
```
status is "open", but Drawer is missing
![CleanShot 2022-05-02 at 10 52 04](https://user-images.githubusercontent.com/34196239/166209209-ab99241c-77f3-45b9-a725-3481805538a1.png)

gestures and hamburger icon work correctly - changing status of drawer open/close

![CleanShot 2022-05-02 at 10 53 20](https://user-images.githubusercontent.com/34196239/166209284-5f2bad20-acf6-46da-92e7-fe9359b45177.png)

**Comment by PraveenPali** [comment]
When I downgrade to 6.3.0 it not working.

 "@react-navigation/drawer": "^6.3.0",
    "@react-navigation/native": "^6.1.6",
    "@react-navigation/stack": "^6.3.16",

**Comment by klendi** [comment]
For me it happened only when drawer had custom width by percentage
to fix it I removed the percentage and added this line instead and this fixed it.

```js         
const width = Dimensions.get("window").width;

....

drawerStyle: {
          width: width * 0.8,
        },
```
