### ISSUE TITLE
useDrawerStatus updated with more than 2sec delay on drawer overlay click??

### ISSUE THREAD

**Issue by zoobibackups** [react-navigation/react-navigation#10410]
### Current behavior

useDrawerStatus updated with a delay of 2sec when drawer is closed due to overlay tapped. 

**I am doing animation based on useDrawerState() which is delayed also.**

### Expected behavior

When i call `navigation.toggleDrawer() or openDrawer() or closeDrawer()` the state immediately updated but when i tap drawer overly the state updated with the delay(more than 2sec).

### Reproduction

https://snack.expo.dev/@jamalmrd/drawerstatedelay

### Platform

- [X] Android
- [X] iOS

### Packages

- [X] @react-navigation/drawer

### Environment

  "@react-navigation/drawer": "^6.3.1",
  "@react-navigation/native": "^6.0.8",
  "@react-navigation/native-stack": "^6.5.0",
  "react": "17.0.2",
  "react-native": "0.67.2",
  "react-native-gesture-handler": "^2.1.1",
  "react-native-pager-view": "^5.4.11",
  "react-native-reanimated": "^2.4.1",
  "react-native-safe-area-context": "^3.4.1",
  "react-native-screens": "^3.12.0",
  "react-native-tab-view": "^3.1.1"

**Comment by zoobibackups** [comment]
> Couldn't find version numbers for the following packages in the issue:
> 
> * `@react-navigation/bottom-tabs`
> * `@react-navigation/material-bottom-tabs`
> * `@react-navigation/stack`
> 
> Can you update the issue to include version numbers for those packages? The version numbers must match the format 1.2.3.

Updated!

**Comment by saaiful** [comment]
Same issue, it works if I press button with 1-2 second delay. Btw, if I use swipe it works without delay.

**Comment by alphonse92** [comment]
still happening

**Comment by anhquan291** [comment]
Facing the same issue. Any updates? thanks

**Comment by Revolt9k** [comment]
Same problem here. Any updates?

**Comment by Melzmr** [comment]
It can be related to https://github.com/react-navigation/react-navigation/issues/10504.

Try downgrading to `@react-navigation/drawer@6.3.0` or use `useLegacyImplementation`

**Comment by sunnylqm** [comment]
it should be a spring animation parameters issue 
https://github.com/facebook/react-native/issues/20783#issuecomment-449826734

increase these 2 parameters by 100x~500x you'll see a difference
https://github.com/react-navigation/react-navigation/blob/main/packages/drawer/src/views/modern/Drawer.tsx#L166-L167
