### ISSUE TITLE
Modal not covering entire screen on Android

### ISSUE THREAD

**Issue by fjckls** [react-navigation/react-navigation#10417]
### Current behavior

The modal `Stack.Screen` is behaving differently on **iOS** and **Android**. On **iOS** modal is covering the full screen, but on **Android** not. I would like to have a static header with some UI (burger etc.), that is present in all screens and I don't want to animate the same UI as `Stack.Screen` header every time I change the screen. To achieve this I have added a static header outside **Stack.Navigator**. Everything works as expected apart from modal screen. When I initialise modal screen I expect it to cover the whole screen - also the static header. That is true for **iOS**. However on **Android** the static header component is not covered. I guess it is due to the fact that my static header "lives" outside `Stack.Navigator`.
I have created snack, so check it out https://snack.expo.dev/@fjckls/fullscreen-modal-android-issue
How to implement the desired behaviour with static header? Thanks!

```
const Contacts = ({ navigation }) => {
  return (
    <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
      <Text>Contacts</Text>
      <Button title="Show Modal" onPress={() => navigation.navigate('Modal')} />
    </View>
  );
};
const About = () => {
  return (
    <View style={{ flex: 1 }}>
      <Text>About</Text>
    </View>
  );
};
const Modal = () => {
  return (
    <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
      <Text>This is fullscreen modal!!!</Text>
    </View>
  );
};
const MyStaticHeader = () => {
  return (
    <View style={{ height: 60, justifyContent: 'center', alignItems: 'center', backgroundColor:'orange' }}>
      <Text>MY STATIC HEADER!!</Text>
    </View>
  );
};

const TopTab = createMaterialTopTabNavigator();
const HomeTabs = () => {
  return (
    <TopTab.Navigator>
      <TopTab.Screen name="Contacts" component={Contacts} />
      <TopTab.Screen name="About" component={About} />
    </TopTab.Navigator>
  );
};

const Stack = createNativeStackNavigator();
const App = () => {
  return (
    <SafeAreaView style={{ flex: 1, justifyContent: 'center' }}>
      <StatusBar animated={true} backgroundColor="#61dafb" />
      <MyStaticHeader />
      <NavigationContainer>
        <Stack.Navigator screenOptions={{ headerShown: false }}>
          <Stack.Screen name="Home" component={HomeTabs} />
          <Stack.Screen
            name="Modal"
            component={Modal}
            options={{ presentation: 'modal',animation: 'slide_from_bottom' }}
          />
        </Stack.Navigator>
      </NavigationContainer>
    </SafeAreaView>
  );
};
```

![Simulator Screen Shot - iPhone 11 - 2022-03-09 at 09 51 51](https://user-images.githubusercontent.com/2750675/157402937-09f52116-0ee4-4cb1-b694-2dd53812437d.png)
![Simulator Screen Shot - iPhone 11 - 2022-03-09 at 09 52 31](https://user-images.githubusercontent.com/2750675/157402976-e9b5e987-94e1-4bbc-807e-1b1aa7fbef85.png)
![Screenshot_20220309_095844](https://user-images.githubusercontent.com/2750675/157403234-85709b54-2aef-4bf0-82f1-00a4e4a15134.png)
![Screenshot_20220309_095900](https://user-images.githubusercontent.com/2750675/157403293-7bbe89ca-691f-4867-8605-9d80d11da9b1.png)

### Expected behavior

Modal screen to cover the whole screen on Android just like on iOS.

### Reproduction

https://snack.expo.dev/@fjckls/fullscreen-modal-android-issue

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [X] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |6.0.8
| @react-navigation/material-top-tabs    |6.1.1
| @react-navigation/native-stack         |6.5.0
| react-native-safe-area-context         |3.3.2
| react-native-screens                   |3.10.2
| react-native-gesture-handler           |2.1.3
| react-native-reanimated                |2.3.3
| react-native-tab-view                  |3.1.1
| react-native-pager-view                |5.4.9
| react-native                           |0.67.2
| expo                                   |5.2.0
| node                                   |16.14.0
| yarn                            |1.22..11

**Comment by idrive-pankaj** [comment]
Facing the same issue, did you found any solution?

**Comment by laurenceunmind** [comment]
A workaround is to place all your full screen modal screens at the top layer of navigation. This isn't ideal though from a structural point of view!

**Comment by Travinator98** [comment]
I'm having the same problem. I'd really prefer to not have to move all modals to the top level. Is a solution to this in the works?

**Comment by ApWin** [comment]
Facing the same issue, Is there any on else who find solution?

**Comment by nomoreerrors** [comment]
https://reactnative.dev/docs/modal just use native modal

**Comment by dustinvforsyth** [comment]
I am having this same issue. I think the worst part about this is that it works as I would expect on iOS but on android modals are nested inside of the navigation headers or tab bars if they are nested in that navigator. I think one of the issues with putting these modals at the root is deep linking or routing into the app via web link or push notification. It works perfectly to send a user to their gallery tab and then open a modal there and have them in the area they should be in when they close the modal. With rooted modals it seems weird to just pop a modal at the root. You would almost need to route twice the way that I am thinking about it if you wanted the gallery to be underneath the modal.

**Comment by ShadReyes** [comment]
This a little bit of a hacky solution. You can add this hook below to the component you are displaying as the modal to hide the header and and tabs of a TabNavigator. This can also work on a normal navigator as long as you use the screen options to apply the header.

```
export const useFocusModalHandler = () => {
  const navigation = useNavigation();

  useEffect(() => {
    //Don't want to do anything on iOS
    if (Platform.OS !== 'android') {
      return;
    }

    const tabNavigator = getTabNavigatorProp(navigation.getParent());

    if (! tabNavigator) {
      return;
    }

    tabNavigator.setOptions({ headerShown: false });
    tabNavigator.setOptions({ tabBarStyle: { display: 'none' } });

    return () => {
      //Unmounted callback
      tabNavigator.setOptions({ headerShown: true });

      tabNavigator.setOptions({
        tabBarStyle: { display: 'flex'  },
      });
    };
  }, []);
};

const getTabNavigatorProp = (route: any): any => {
  if (!route) {
    return null;
  }
  if (route.getId() == 'IdOfTabNavigator') {
    return route;
  }
  return getTabNavigatorProp(route.getParent());
};
```

**Comment by ShadReyes** [comment]
> const StackOptions = {
>     headerShown: false,
>     gestureEnabled: true,
>     ...(Platform.OS === 'android' && TransitionPresets.ModalPresentationIOS),
> }
> 
> this solution is worked for me.

I am sure that works, but those options are only available in `@react-navigation/stack`. This is a `@react-navigation/native-stack` issue.

**Comment by cembicakci** [comment]
Yes i solved the problem

**Comment by ShadReyes** [comment]
> > > 
> > 
> > 
> > I am sure that works, but those options are only available in `@react-navigation/stack`. This is a `@react-navigation/native-stack` issue.
> 
> could you share the way that how you solved this?

I have a hacker solution I use throughout my clients app. See [above](https://github.com/react-navigation/react-navigation/issues/10417#issuecomment-1470736310)

**Comment by satya164** [comment]
Modals are intended to be at the root. On iOS it works without having it at the root for native stack because of underlying platform differences.

https://reactnavigation.org/docs/modal#best-practices

Also to emphasize:

> Think of nesting navigators as a way to achieve the UI you want rather than a way to organize your code.

https://reactnavigation.org/docs/nesting-navigators/#best-practices-when-nesting

**Comment by levantanphat9c** [comment]
`screenOptions={{
            presentation: IS_ANDROID ? 'transparentModal' : 'modal',
            headerShown: false,
            ...(IS_ANDROID && {
              contentStyle: { backgroundColor: dynamicColor.Opacity.blueGray50Percent },
              animation: 'slide_from_bottom',
            }),
          }}`
          
I used this and worked for me. In container style of Modal screen, use marginTop.
