### ISSUE TITLE
React navigation ref only refer one drawer if there are two drawers

### ISSUE THREAD

**Issue by cmark1302** [react-navigation/react-navigation#10424]
### Current behavior

Right drawer toggle doesn't work with navigationRef

navigationRef.getParent() or navigationRef.current.getParent() returns undefined

https://snack.expo.dev/@cmark1902/two-navigation-drawer

### Expected behavior

Need a method/function to remove any drawer if it has multiple drawer on one screen

### Reproduction

https://snack.expo.dev/@cmark1902/two-navigation-drawer

### Platform

- [X] Android
- [ ] iOS
- [X] Web
- [ ] Windows
- [X] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

package | version
-- | --
@react-navigation/native | ^6.0.8
@react-navigation/material-top-tabs | ^6.1.1
react-native-safe-area-context | ^4.1.2
react-native-screens | ^3.13.1
react-native-tab-view | ^3.1.1
react-native-pager-view | ^5.4.11
react-native | 0.67.3
node | 16.13.0
yarn | 1.22.11

**Comment by cmark1302** [comment]
Updated the versions

**Comment by satya164** [comment]
We recommend using this approach for multiple drawers: https://reactnavigation.org/docs/multiple-drawers/#nesting-2-drawer-navigators
