### ISSUE TITLE
v6 hiding tabbar with {display:none} does not work on iOS

### ISSUE THREAD

**Issue by tarikpnr** [react-navigation/react-navigation#10432]
### Current behavior

I am trying to achieve dynamically hiding tab bar behavior. I already know [what documentation suggest][1] for this purpose.

However, I am not a big fan of restructuring whole navigators and routes for only hiding tab bar. Thus, I did prefer a more dynamic way. But, I am facing a problem with IOS simulator/real device. It works fine on android devices.

What I do is basically, (just a summary of the logic I do app

```  
  <BottomTabBar
    style={{ display: shouldRenderTabBar ? "flex" : "none" }}
    {...props}
  />;

```

https://user-images.githubusercontent.com/61876765/158449077-0ebc3efc-e87a-4356-918a-418944621712.mov

And this is what happens on ios simulator/real-device. [Video link][2]

Seems like `display:none` doesn't affect anyway to height of bottom tab bar. I am wondering while it works on android emulator/real-device what's wrong with IOS? 
  

  [1]: https://reactnavigation.org/docs/hiding-tabbar-in-screens/
  [2]: https://streamable.com/n5xqej

### Expected behavior

Hide bottom tab bar with the applied styling

### Reproduction

https://snack.expo.dev/@tarikfp/hide-bottom-bar-fails-on-ios

https://streamable.com/n5xqej

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |6.0.6
| @react-navigation/bottom-tabs          |6.1.0
| @react-navigation/native-stack         |6.2.5
| react-native-safe-area-context         |3.3.2
| react-native-screens                   |3.9.0
| react-native-gesture-handler           |1.10.3
| react-native                           |0.66.3

**Comment by raajnadar** [comment]
Please add a repro, it should work properly when you pass the style to tabBarStyle props.

https://reactnavigation.org/docs/bottom-tab-navigator/#tabbarstyle

**Comment by tarikpnr** [comment]
> Please add a repro, it should work properly when you pass the style to tabBarStyle props.
> 
> https://reactnavigation.org/docs/bottom-tab-navigator/#tabbarstyle

I did update the description, here is the link. https://snack.expo.dev/@tarikfp/hide-bottom-bar-fails-on-ios

But notice that there will be no problem on snack's ios simulator, please try to run on xcode

**Comment by Freddy03h** [comment]
I also found this bug since I upgraded to react-native 0.67.3 (maybe that's why it's not reproductible on snack/expo)

**Comment by raajnadar** [comment]
Yes, the expo SDK 44 still uses the 0.64 version. We need to investigate the issue.

**Comment by consuelo-sanna** [comment]
Hi,
I spent some time researching and I hope this summary might help someone else.

I know my findings are not a final solutions but I think it might be helpful for others to at least create a workaround in the meantime

1) on IOS inside the Tab.Navigator -> screenOptions -> tabBarStyle use position:'absolute'
   downside: you'll have to fix the bottom padding to avoid that the menu goes upon your components
   source: https://github.com/react-navigation/react-navigation/issues/6779#issuecomment-583272325
   
2) set EnableScreens(false)
https://github.com/software-mansion/react-native-screens/issues/111#issuecomment-852997138

3) detach screen during the navigation
https://github.com/software-mansion/react-native-screens/issues/111#issuecomment-757518915

4) fix the epsilon value inside of the react-native-screens
https://github.com/software-mansion/react-native-screens/issues/1285

I think the fourth might solve this issue entirely or be a good starting point for investigate this one too

**Comment by tarikpnr** [comment]
> Hi, I spent some time researching and I hope this summary might help someone else.
> 
> I know my findings are not a final solutions but I think it might be helpful for others to at least create a workaround in the meantime. So far I have found this solutions:
> 
> 1. on IOS inside the Tab.Navigator -> screenOptions -> tabBarStyle use position:'absolute'
>    downside: you'll have to fix the bottom padding to avoid that the menu goes upon your components
>    source: [[ANDROID] Tab Bar - tabBarVisible = false displays grey bar #6779 (comment)](https://github.com/react-navigation/react-navigation/issues/6779#issuecomment-583272325)
> 2. set EnableScreens(false)
>    [flickering and blinking view on navigation.goBack() software-mansion/react-native-screens#111 (comment)](https://github.com/software-mansion/react-native-screens/issues/111#issuecomment-852997138)
> 3. detach screen during the navigation
>    [flickering and blinking view on navigation.goBack() software-mansion/react-native-screens#111 (comment)](https://github.com/software-mansion/react-native-screens/issues/111#issuecomment-757518915)
> 4. fix the epsilon value inside of the react-native-screens
>    [White line in the top of the screen after navigate between screens software-mansion/react-native-screens#1285](https://github.com/software-mansion/react-native-screens/issues/1285)
> 
> I think the fourth might solve this issue entirely or be a good starting point for investigate this one too

I can confirm that it is resolved by applying the second solution. Thx! @consuelo-sanna 

```
 // In app.tsx
  React.useEffect(() => {
    if (Platform.OS === "ios") {
      enableScreens(false);
    }
  }, []);

```

**Comment by JacobJaffe** [comment]
Is this a safe solution for this issue? 
It looks like this will have a meaningful performance impact:
https://github.com/software-mansion/react-native-screens/issues/111#issuecomment-855767735

> > Hi, I spent some time researching and I hope this summary might help someone else.
> > I know my findings are not a final solutions but I think it might be helpful for others to at least create a workaround in the meantime. So far I have found this solutions:
> > 
> > 1. on IOS inside the Tab.Navigator -> screenOptions -> tabBarStyle use position:'absolute'
> >    downside: you'll have to fix the bottom padding to avoid that the menu goes upon your components
> >    source: [[ANDROID] Tab Bar - tabBarVisible = false displays grey bar #6779 (comment)](https://github.com/react-navigation/react-navigation/issues/6779#issuecomment-583272325)
> > 2. set EnableScreens(false)
> >    [flickering and blinking view on navigation.goBack() software-mansion/react-native-screens#111 (comment)](https://github.com/software-mansion/react-native-screens/issues/111#issuecomment-852997138)
> > 3. detach screen during the navigation
> >    [flickering and blinking view on navigation.goBack() software-mansion/react-native-screens#111 (comment)](https://github.com/software-mansion/react-native-screens/issues/111#issuecomment-757518915)
> > 4. fix the epsilon value inside of the react-native-screens
> >    [White line in the top of the screen after navigate between screens software-mansion/react-native-screens#1285](https://github.com/software-mansion/react-native-screens/issues/1285)
> > 
> > I think the fourth might solve this issue entirely or be a good starting point for investigate this one too
> 
> I can confirm that it is resolved by applying the second solution.(Only if you are not using `Animated.View` as wrapper of custom tab bar component) Thx! @consuelo-sanna
> 
> ```
>  // In app.tsx
>   React.useEffect(() => {
>     if (Platform.OS === "ios") {
>       enableScreens(false);
>     }
>   }, []);
> ```

**Comment by guilhermefari** [comment]
I am facing the exact same problem. There is an empty space where the bottom tab is placed (should it be entirely hidden).  Using enableScreens(false) did not solve my problem. Any other tip about what to do?

**Comment by eagleeyejack** [comment]
> Hi, I spent some time researching and I hope this summary might help someone else.
> 
> I know my findings are not a final solutions but I think it might be helpful for others to at least create a workaround in the meantime. So far I have found this solutions:
> 
> 1. on IOS inside the Tab.Navigator -> screenOptions -> tabBarStyle use position:'absolute'
>    downside: you'll have to fix the bottom padding to avoid that the menu goes upon your components
>    source: [[ANDROID] Tab Bar - tabBarVisible = false displays grey bar #6779 (comment)](https://github.com/react-navigation/react-navigation/issues/6779#issuecomment-583272325)
> 2. set EnableScreens(false)
>    [flickering and blinking view on navigation.goBack() software-mansion/react-native-screens#111 (comment)](https://github.com/software-mansion/react-native-screens/issues/111#issuecomment-852997138)
> 3. detach screen during the navigation
>    [flickering and blinking view on navigation.goBack() software-mansion/react-native-screens#111 (comment)](https://github.com/software-mansion/react-native-screens/issues/111#issuecomment-757518915)
> 4. fix the epsilon value inside of the react-native-screens
>    [White line in the top of the screen after navigate between screens software-mansion/react-native-screens#1285](https://github.com/software-mansion/react-native-screens/issues/1285)
> 
> I think the fourth might solve this issue entirely or be a good starting point for investigate this one too

Option 1 worked for me on iOS, thank you for your help!! 🔥

**Comment by rdgomt** [comment]
i am facing the same issue...
option 2 worked for me

**Comment by akinlekan28** [comment]
Option two worked for me too

**Comment by chukiatt** [comment]
i have also the problem. can't hide bottom tabbar

**Comment by chukiatt** [comment]
I can solved this problem. after try a week

**Comment by bryce0516** [comment]
it's working react native 0.70.6

**Comment by rrsalian16** [comment]
I'm also having the same issue, Any fix?

**Comment by luudz** [comment]
Option 2 worked 🚀 🙌🏻

**Comment by wangqt1110** [comment]
This works for me
```
import { BottomTabBar } from "@react-navigation/bottom-tabs";

<Tab.Navigator
  tabBar={props => {
    if (condition) {
      return <BottomTabBar {...props} />;
    }
    return null;
  }}
>
  ...
</Tab.Navigator>
```

**Comment by tanzeel-abdulWahid** [comment]
option 2 Worked for me ✌🏻

**Comment by irekrog** [comment]
```ts
sceneContainerStyle={{
  backgroundColor: 'transparent',
}}
```

worked for me

**Comment by ameersami** [comment]
Option 2 did not work for me but option 1 worked for me.

```
"react-native": "0.73.1",
"@react-navigation/bottom-tabs": "6.5.11",
"@react-navigation/native": "6.1.9",
"@react-navigation/native-stack": "6.9.17"
```

**Comment by longnguyen2508** [comment]
Option 2 worked. But, still want to use Native Screen :(

**Comment by sirusbaladi** [comment]
why is this closed? still an issue

**Comment by dogankablan** [comment]
Option 2 not working on new react native versions(0.73.6).

Can anyone suggest a different solution?

**Comment by iamjavkhaa** [comment]
thaaaaaank youuuuu

**Comment by ebykdrms** [comment]
I was having the same problem. It seems I have solved it for now...
Giving `animation: 'none'` as screenOptions solved this problem for me.
I think there is an animation problem. Removing the animation solves the problem.
I gave it for Navigator but `animation: 'none'` can also be given to certain Stacks via the option prop.

```js
<Stack.Navigator screenOptions={{animation: 'none'}}>
      <Stack.Screen name={'CartScreen'} component={CartScreen} />
      <Stack.Screen name={'ProductDetailScreen'} component={ProductDetailScreen}/>
      ...
</Stack.Navigator>
```

**Comment by ATisma** [comment]
I also confirm that option 2 doesn't work on react-native@0.73.6. 

What fixed it was this: 

> I was having the same problem. It seems I have solved it for now... Giving `animation: 'none'` as screenOptions solved this problem for me. I think there is an animation problem. Removing the animation solves the problem. I gave it for `Stack.Navigator` but `animation: 'none'` can also be given to certain `Stack.Screen`s via the option prop.
> 
> <Stack.Navigator screenOptions={{animation: 'none'}}>
>       <Stack.Screen name={'CartScreen'} component={CartScreen} />
>       <Stack.Screen name={'ProductDetailScreen'} component={ProductDetailScreen}/>
>       ...
> </Stack.Navigator>

But this is not acceptable since our application relys on screen animations transitioning from one to the other side
