### ISSUE TITLE
Right drawer always half open

### ISSUE THREAD

**Issue by francesco-clementi-92** [react-navigation/react-navigation#10434]
### Current behavior

![photo5877719971176494821](https://user-images.githubusercontent.com/30288622/158654739-2b422085-63c4-461d-8d43-598fd2aeaf27.jpg)

I'm using react native without expo and I'm trying to move the drawer on the right.

I can't reproduce the bug on snack, but I reduced all my code at this easy point:
```
function Feed() {
  return (
    <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
      <Text>Feed Screen</Text>
    </View>
  );
}

<NavigationContainer>         
              <Drawer.Navigator
                screenOptions={{
                  drawerPosition: 'right',
                }}
                >
                            <Drawer.Screen name="Feed" component={Feed} />
              </Drawer.Navigator>
</NavigationContainer>
```

This code won't let the drawer to fully close.

Even if I start a fresh new project with react-native init myapp I get the same result.

### Expected behavior

I expect the right drawer to be fully close

### Reproduction

Code available on top

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [X] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

   "@react-native-async-storage/async-storage": "^1.16.1",
    "@react-native-community/push-notification-ios": "^1.10.1",
    "@react-native-firebase/app": "^11.5.0",
    "@react-native-firebase/auth": "^11.5.0",
    "@react-native-firebase/crashlytics": "^11.5.0",
    "@react-native-firebase/firestore": "^11.5.0",
    "@react-native-firebase/functions": "^11.5.0",
    "@react-native-firebase/messaging": "^11.5.0",
    "@react-native-firebase/ml": "^11.5.0",
    "@react-native-firebase/storage": "^11.5.0",
    "@react-native-masked-view/masked-view": "^0.2.6",
    "@react-navigation/bottom-tabs": "^6.2.0",
    "@react-navigation/drawer": "^6.3.1",
    "@react-navigation/material-top-tabs": "^6.1.1",
    "@react-navigation/native": "^6.0.8",
    "@react-navigation/stack": "^6.1.1",
    "deepmerge": "^4.2.2",
    "lodash": "^4.17.21",
    "moment": "^2.29.1",
    "qs": "^6.10.1",
    "react": "17.0.2",
    "react-native": "0.67.3",
    "react-native-actions-sheet": "^0.6.0",
    "react-native-app-intro-slider": "^4.0.4",
    "react-native-bootsplash": "^4.1.3",
    "react-native-calendars": "^1.1278.0",
    "react-native-date-picker": "^4.2.0",
    "react-native-fast-image": "^8.5.11",
    "react-native-gesture-handler": "^2.3.1",
    "react-native-google-places-autocomplete": "^2.4.1",
    "react-native-google-signin": "^2.1.1",
    "react-native-image-picker": "^4.7.3",
    "react-native-indicators": "^0.17.0",
    "react-native-keyboard-aware-scroll-view": "^0.9.5",
    "react-native-modal": "^13.0.0",
    "react-native-pager-view": "^5.4.11",
    "react-native-paper": "^4.11.2",
    "react-native-push-notification": "^8.1.1",
    "react-native-reanimated": "^2.4.1",
    "react-native-safe-area-context": "^3.4.1",
    "react-native-screens": "^3.12.0",
    "react-native-tab-view": "^3.1.1",
    "react-native-vector-icons": "^9.1.0"

**Comment by stef1103** [comment]
I have the same problem, downgrading to @react-navigation/drawer 6.3.0 fix the issue

#10418 #10335

**Comment by outaTiME** [comment]
It keeps failing for me with the latest version "@react-navigation/drawer" 6.4.1, for some reason when I try to access a screen by tapping on the drawer, it stays open, the only workaround at the moment is to go back to version 6.3.0 or using `useLegacyImplementation`, here are my dependencies:

```
"@react-navigation/drawer": "6.4.1",
"@react-navigation/elements": "^1.3.3",
"@react-navigation/native": "^6.0.10",
"@react-navigation/stack": "^6.2.1",
"react-native-reanimated": "~2.3.3",
"expo": "^44.0.6",
```

https://user-images.githubusercontent.com/140472/162339542-e1e03770-37df-4646-b6ec-8754e00bf8df.MP4

**Comment by raajnadar** [comment]
@outaTiME your issue is not related to the main thread.

**Comment by jonklein** [comment]
Seeing something similar, though happening a bit sporadically.  If it helps narrow it down, not seeing the issue in 6.3.1, but am seeing it in 6.3.2 or later

**Comment by satya164** [comment]
these comments are unrelated to the original issue. please open a separate issue if you have a different problem.

closing this issue since this problem is likely fixed in the latest version and OP hasn't provided a repro to test.

**Comment by henryteng07** [comment]
@francesco-clementi-92  I'm facing the same issue! How did you fix it?

**Comment by aymericdelaforcade** [comment]
I had this problem when building the application as an apk but not on Expo Go. I solved the problem by downgrading the version of `react-native-reanimated` under version 3 (2.14.4) and also the version of `expo sdk` to version 48 because from 49, versions of `react-native-reanimated `lower than 3 are no longer supported. 
I hope this helps someone.

**Comment by JairajJangleSLIOT** [comment]
Can we re-open this issue, I am also facing the same issue.
