### ISSUE TITLE
"RNSScreenNavigationContainer" was not found in the UIManager.

### ISSUE THREAD

**Issue by vmarcel** [react-navigation/react-navigation#10433]
### Current behavior

When navigating between an unauthorized to authorized stack screen I get this error

<img width="420" alt="Screen Shot 2022-03-15 at 11 25 15 PM" src="https://user-images.githubusercontent.com/20823925/158510845-9fe7942c-5842-4e48-9556-30e0b187c107.png">

### Expected behavior

I would navigate the to main screen

### Reproduction

https://github.com/veyl-zero/veyl-app

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [x] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

- [X] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
"@react-native-async-storage/async-storage"| "^1.15.7"
"@react-native-community/masked-view":|"^0.1.11"
"@react-navigation/bottom-tabs"| "^6.0.2"
"@react-navigation/native"| "^6.0.8"
"@react-navigation/stack"| "^6.0.2"
"react"| "17.0.2"
"react-native"| "0.65.2"
"react-native-gesture-handler"| "^1.10.3"
"react-native-reanimated"|"^2.4.1"
"react-native-safe-area-context"| "^3.4.1"
"react-native-screens"|"^3.13.1"

**Comment by raajnadar** [comment]
Did you run `npx pod-install`?

**Comment by vmarcel** [comment]
@raajnadar yes, I also reinstalled all the packages related to react-navigation to have them at the latest versions.

**Comment by vmarcel** [comment]
I did a full clean of my project following these steps

```
watchman watch-del-all
rm -rf yarn.lock package-lock.json node_modules
rm -rf android/app/build
rm -rf ios/Pods ios/Podfile.lock 
rm -rf ~/Library/Developer/Xcode/DerivedData
npm install && cd ios && pod update && cd ..
npm start -- --reset-cache
```

credit to [Florian Marcu](https://instamobile.io/react-native-tutorials/full-clean-react-native-project/)

**Comment by thinkmobilede** [comment]
For others facing this issue: The solution of @vmarcel  can lead to the same result, but I could not update all my dependencies. What solved the issue for me was to update all react-navigation versions to the latest. react-navigation/drawer I had to reduce to 6.5.0 because of an issue with pointer-events in a StyleSheet.
