### ISSUE TITLE
Expo Web refresh page 404 - 2

### ISSUE THREAD

**Issue by astriskit** [react-navigation/react-navigation#10447]
### Current behavior

expo-web + react-navigation-4.x + `expo build:web` => page-not-found/404 on a page that is working fine in development-time.

### Expected behavior

Should work as in development; When a route is redirected to then, the page should open up.

### Reproduction

none shareable atm 

### Platform

- [ ] Android
- [ ] iOS
- [X] Web

### Packages

- [ ] react-navigation-drawer
- [X] react-navigation-stack
- [ ] react-navigation-tabs

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| react-navigation                       | ^4.4
| react-navigation-stack                 | ^2.10
| react-native-safe-area-context         | 3.3.2
| react-native-screens                   | ~3.10
| react-native-gesture-handler           | ~2.1
| react-native-reanimated                | ~2.3
| react-native                           | 0.64.3
| expo                                   | ^44
| node                                   | 14.x
| npm or yarn                            | 6.x

**Comment by astriskit** [comment]
seems dupe of #9519, btw that's closed without resolution

**Comment by astriskit** [comment]
This seem to be out of scope of the react-navigation; In general was able to get through this using the deployment settings for SPA; 

Use-case was to run the built site using `serve` and while requesting for a file using a route from the build directory, a 404 response was being given. As it turns out, the request sort of never reached the react-navigation (hint: 404 page was a response page from the `serve`). That makes this a deployment issue rather than a library scoped.

Was able to sort out using the SPA configurations as this [comment](https://github.com/expo/expo-cli/issues/2983#issuecomment-1074277754) hinted.

**Comment by kirtikapadiya** [comment]
Need to add web.config file with URL rewrite rule on root folder.

**Comment by satya164** [comment]
https://reactnavigation.org/docs/7.x/web-support#configuring-hosting-providers
