### ISSUE TITLE
Warning: [react-native-gesture-handler] Seems like you're using an old API with gesture components, check out new Gestures system!

### ISSUE THREAD

**Issue by xstable** [react-navigation/react-navigation#10444]
### Current behavior

Got the following error with "react-native-gesture-handler": "^2.3.2". 

```bsah
LOG  Running "youSurvive" with {"rootTag":1}
WARN  [react-native-gesture-handler] Seems like you're using an old API with gesture components, check out new Gestures system! 
at PanGestureHandler (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.myProject&modulesOnly=false&runModule=true:190397:38)
at Drawer (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.myProject&modulesOnly=false&runModule=true:197431:26)
at DrawerViewBase (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.myProject&modulesOnly=false&runModule=true:168460:22)
at RNGestureHandlerRootView
at GestureHandlerRootView
at RNCSafeAreaProvider
at SafeAreaProvider (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.myProject&modulesOnly=false&runModule=true:146883:24)
at SafeAreaProviderCompat (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.myProject&modulesOnly=false&runModule=true:168024:24)
at DrawerView (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.myProject&modulesOnly=false&runModule=true:168732:27)
at DrawerNavigator (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.myProject&modulesOnly=false&runModule=true:168325:32)
at EnsureSingleNavigator (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.myProject&modulesOnly=false&runModule=true:159620:24)
at BaseNavigationContainer (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.myProject&modulesOnly=false&runModule=true:159129:28)
at ThemeProvider (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.myProject&modulesOnly=false&runModule=true:164916:21)
at NavigationContainerInner (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.myProject&modulesOnly=false&runModule=true:164776:26)
at ThemeProvider (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.myProject&modulesOnly=false&runModule=true:116190:36)
at App (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.myProject&modulesOnly=false&runModule=true:109991:40)
at RCTView
at View
at RCTView
at View
at AppContainer (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.myProject&modulesOnly=false&runModule=true:76839:36)
at youSurvive(RootComponent) (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.myProject&modulesOnly=false&runModule=true:83218:28)
BUNDLE  ./index.js 
```
Here is the info, what need's to be changed in v2 of gesture-handler: 
https://docs.swmansion.com/react-native-gesture-handler/docs/2.1.1/whats-new/#interoperability-with-gesture-handlers

### Expected behavior

No warning

### Reproduction

no

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

- [] I've removed the packages that I don't use

"dependencies": {
    "@babel/plugin-proposal-decorators": "^7.17.8",
    "@babel/preset-react": "^7.16.7",
    "@react-native-community/masked-view": "^0.1.11",
    "@react-navigation/devtools": "^6.0.5",
    "@react-navigation/drawer": "^6.3.1",
    "@react-navigation/native": "^6.0.8",
    "@react-navigation/native-stack": "^6.5.0",
    "dayjs": "^1.11.0",
    "i18next": "^21.6.14",
    "i18next-react-native-language-detector": "^1.0.2",
    "prop-types": "^15.8.1",
    "react": "17.0.2",
    "react-i18next": "^11.16.1",
    "react-native": "0.67.4",
    "react-native-elements": "^3.4.2",
    "react-native-gesture-handler": "^2.3.2",
    "react-native-localize": "^2.2.0",
    "react-native-reanimated": "^2.4.1",
    "react-native-safe-area-context": "^4.2.1",
    "react-native-screens": "^3.13.1",
    "react-native-svg": "^12.3.0",
    "react-native-vector-icons": "^9.1.0"
  },
  "devDependencies": {
    "@babel/core": "^7.17.8",
    "@babel/eslint-parser": "^7.17.0",
    "@babel/runtime": "^7.17.8",
    "@react-native-community/eslint-config": "^3.0.1",
    "babel-jest": "^27.5.1",
    "eslint": "^8.11.0",
    "eslint-config-airbnb-base": "^15.0.0",
    "eslint-plugin-flowtype": "^8.0.3",
    "eslint-plugin-import": "^2.25.4",
    "eslint-plugin-react": "^7.29.4",
    "eslint-plugin-react-native": "^4.0.0",
    "jest": "^27.5.1",
    "metro-react-native-babel-preset": "^0.69.1",
    "prettier-eslint": "^13.0.0",
    "react-native-flipper": "^0.138.0",
    "react-test-renderer": "17.0.2"
  },

**Comment by ravirajn22** [comment]
I think the issue is due to old installation instruction provided in v6 of react-navigation. 

Newer versions of react-native-gesture-handler does not require the step (v2 and above I think)
`import 'react-native-gesture-handler';` 
in https://reactnavigation.org/docs/stack-navigator#installation

Removing this line stops this warning.

Because this library should have already done that for us as said in react-native-gesture-handler,
`If you're using gesture handler in your component library, you may want to wrap your library's code in the GestureHandlerRootView component. This will avoid extra configuration for the user.`

@satya164 or someone please confirm this.

**Comment by raajnadar** [comment]
@ravirajn22 that is required step check the docs,

The library does the configuration to add the HOC wrapper so that we don't need to do any native changes.

https://docs.swmansion.com/react-native-gesture-handler/docs/installation#js

**Comment by satya164** [comment]
The warning comes from gesture handler. There's nothing React Navigation can do about it for now.

https://github.com/software-mansion/react-native-gesture-handler/issues/1831

**Comment by xstable** [comment]
@satya164 can you explain the reason? 
In my opinion it looks like it comes from the Drawer, as you see above in my trace... and in the thread you've linked, it's also mentioned, that its because of the use of the PanGestureHandler! (BTW: Even like described in the thread you've linked.) 

So please describe more in detail, why you think it's not an react-navigation (drawer-component) issue?!

**Comment by satya164** [comment]
> @xstable So please describe more in detail, why you think it's not an react-navigation (drawer-component) issue?!

React Navigation is using non-deprecated public APIs from gesture handler. There's no issue to be fixed.

**Comment by myrs** [comment]
Seems to be fixed now in `react-native-gesture-handler`, not released yet, though: https://github.com/software-mansion/react-native-gesture-handler/pull/1960

Meanwhile, for a quick fix (suppressing the warning) the following could be done (as suggested in https://github.com/software-mansion/react-native-gesture-handler/issues/1831#issuecomment-1014768871):
```
import { LogBox } from 'react-native';

LogBox.ignoreLogs([
  "[react-native-gesture-handler] Seems like you\'re using an old API with gesture components, check out new Gestures system!",
]);
```

**Comment by umardev500** [comment]
> ### Current behavior
> Got the following error with "react-native-gesture-handler": "^2.3.2".
> 
> ```
> LOG  Running "youSurvive" with {"rootTag":1}
> WARN  [react-native-gesture-handler] Seems like you're using an old API with gesture components, check out new Gestures system! 
> at PanGestureHandler (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.myProject&modulesOnly=false&runModule=true:190397:38)
> at Drawer (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.myProject&modulesOnly=false&runModule=true:197431:26)
> at DrawerViewBase (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.myProject&modulesOnly=false&runModule=true:168460:22)
> at RNGestureHandlerRootView
> at GestureHandlerRootView
> at RNCSafeAreaProvider
> at SafeAreaProvider (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.myProject&modulesOnly=false&runModule=true:146883:24)
> at SafeAreaProviderCompat (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.myProject&modulesOnly=false&runModule=true:168024:24)
> at DrawerView (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.myProject&modulesOnly=false&runModule=true:168732:27)
> at DrawerNavigator (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.myProject&modulesOnly=false&runModule=true:168325:32)
> at EnsureSingleNavigator (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.myProject&modulesOnly=false&runModule=true:159620:24)
> at BaseNavigationContainer (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.myProject&modulesOnly=false&runModule=true:159129:28)
> at ThemeProvider (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.myProject&modulesOnly=false&runModule=true:164916:21)
> at NavigationContainerInner (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.myProject&modulesOnly=false&runModule=true:164776:26)
> at ThemeProvider (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.myProject&modulesOnly=false&runModule=true:116190:36)
> at App (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.myProject&modulesOnly=false&runModule=true:109991:40)
> at RCTView
> at View
> at RCTView
> at View
> at AppContainer (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.myProject&modulesOnly=false&runModule=true:76839:36)
> at youSurvive(RootComponent) (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.myProject&modulesOnly=false&runModule=true:83218:28)
> BUNDLE  ./index.js 
> ```
> 
> Here is the info, what need's to be changed in v2 of gesture-handler: https://docs.swmansion.com/react-native-gesture-handler/docs/2.1.1/whats-new/#interoperability-with-gesture-handlers
> 
> ### Expected behavior
> No warning
> 
> ### Reproduction
> no
> 
> ### Platform
> * [x]  Android
> * [ ]  iOS
> * [ ]  Web
> * [ ]  Windows
> * [ ]  MacOS
> 
> ### Packages
> * [ ]  @react-navigation/bottom-tabs
> * [x]  @react-navigation/drawer
> * [ ]  @react-navigation/material-bottom-tabs
> * [ ]  @react-navigation/material-top-tabs
> * [ ]  @react-navigation/stack
> * [ ]  @react-navigation/native-stack
> 
> ### Environment
> * [] I've removed the packages that I don't use
> 
> "dependencies": { "@babel/plugin-proposal-decorators": "^7.17.8", "@babel/preset-react": "^7.16.7", "@react-native-community/masked-view": "^0.1.11", "@react-navigation/devtools": "^6.0.5", "@react-navigation/drawer": "^6.3.1", "@react-navigation/native": "^6.0.8", "@react-navigation/native-stack": "^6.5.0", "dayjs": "^1.11.0", "i18next": "^21.6.14", "i18next-react-native-language-detector": "^1.0.2", "prop-types": "^15.8.1", "react": "17.0.2", "react-i18next": "^11.16.1", "react-native": "0.67.4", "react-native-elements": "^3.4.2", "react-native-gesture-handler": "^2.3.2", "react-native-localize": "^2.2.0", "react-native-reanimated": "^2.4.1", "react-native-safe-area-context": "^4.2.1", "react-native-screens": "^3.13.1", "react-native-svg": "^12.3.0", "react-native-vector-icons": "^9.1.0" }, "devDependencies": { "@babel/core": "^7.17.8", "@babel/eslint-parser": "^7.17.0", "@babel/runtime": "^7.17.8", "@react-native-community/eslint-config": "^3.0.1", "babel-jest": "^27.5.1", "eslint": "^8.11.0", "eslint-config-airbnb-base": "^15.0.0", "eslint-plugin-flowtype": "^8.0.3", "eslint-plugin-import": "^2.25.4", "eslint-plugin-react": "^7.29.4", "eslint-plugin-react-native": "^4.0.0", "jest": "^27.5.1", "metro-react-native-babel-preset": "^0.69.1", "prettier-eslint": "^13.0.0", "react-native-flipper": "^0.138.0", "react-test-renderer": "17.0.2" },

same

**Comment by umardev500** [comment]
> The warning comes from gesture handler. There's nothing React Navigation can do about it for now.
> 
> [software-mansion/react-native-gesture-handler#1831](https://github.com/software-mansion/react-native-gesture-handler/issues/1831)

why react native gesture handler say the react navigaition use old api?
I think this warning shown because react navigation uing old api

**Comment by umardev500** [comment]
> @satya164 can you explain the reason? In my opinion it looks like it comes from the Drawer, as you see above in my trace... and in the thread you've linked, it's also mentioned, that its because of the use of the PanGestureHandler! (BTW: Even like described in the thread you've linked.)
> 
> So please describe more in detail, why you think it's not an react-navigation (drawer-component) issue?!

ini Stack too

**Comment by Codelica** [comment]
As mention previously, react-native-gesture-handler removed this warning [here](https://github.com/software-mansion/react-native-gesture-handler/pull/1960), which is in current releases now.  React-navigation just need to update whatever uses the older version (drawer, stack, ?) to a current version.

**Comment by raajnadar** [comment]
the version depends on your project, the version in this repo is for the development only. You need to use v2.4.0.

https://github.com/software-mansion/react-native-gesture-handler/commit/363bf6f4768cf0f11904c21b011843123566c8fe

**Comment by Codelica** [comment]
Thanks! Sorry about that, didn't see it was in the dev section. 👍
