### ISSUE TITLE
Error from basic navigation example

### ISSUE THREAD

**Issue by applesama** [react-navigation/react-navigation#10450]
### Current behavior

I tried to run a basic example for basic navigation, but error happened, I tried re-install both react-navigation and react-native, but they all does not work, I guess this is caused by packages' version is incompatible, but I am not sure. Here is the error report:

 ```ERROR  TypeError: (0, _$$_REQUIRE(_dependencyMap[0], "react-navigation").StackNavigator) is not a function. (In '(0, _$$_REQUIRE(_dependencyMap[0], "react-navigation").StackNavigator)({})', '(0, _$$_REQUIRE(_dependencyMap[0], "react-navigation").StackNavigator)' is undefined)
```
 ```
ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
```
 ```
ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
```

### Expected behavior

It is just a very simple code:
```import { StackNavigator } from 'react-navigation';

const RootNavigator = StackNavigator({

});

export default RootNavigator;```

### Reproduction

just run the code above

### Platform

- [X] Android
- [ ] iOS
- [ ] Web

### Packages

- [ ] react-navigation-drawer
- [ ] react-navigation-stack
- [ ] react-navigation-tabs

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| react-navigation                       |"^4.4.4"
| react-native-screens                   |"^3.13.1"
| react-native-gesture-handler           |"^2.3.2"
| react-native-reanimated                |"^2.5.0"
| react-native                           |"0.67.4"
| node                                   |16.14.0
|  yarn                            |yarn 1.22.17 
| npm                             |npm 8.3.1

**Comment by raajnadar** [comment]
I am sure this is not due to react navigation, Try adding a simple JSX in the root without the navigator.

**Comment by applesama** [comment]
> Hey! Thanks for opening the issue. The issue doesn't seem to contain a link to a repro (a [snack.expo.dev](https://snack.expo.dev) link or link to a GitHub repo under your username).
> 
> Can you provide a [minimal repro](https://stackoverflow.com/help/minimal-reproducible-example) which demonstrates the issue? A repro will help us debug the issue faster. Please try to keep the repro as small as possible and make sure that we can run it without additional setup.

https://snack.expo.dev/kkWqQ97RO
（should I just reply to this robot?)

**Comment by applesama** [comment]
> I am sure this is not due to react navigation, Try adding a simple JSX in the root without the navigator.

That's right I think, I used the default code that project created, it's all work, so I think that's the navigation's version is incompatible with my current react-native version

**Comment by satya164** [comment]
Please read the docs: https://reactnavigation.org/hello-react-navigation (v6), https://reactnavigation.org/docs/4.x/hello-react-navigation (v4)
That's not how you write a navigator.
