### ISSUE TITLE
Screen headerTitle is reset to default on Android when using headerLeft option

### ISSUE THREAD

**Issue by vytautasvargonas** [react-navigation/react-navigation#10452]
### Current behavior

Using custom `headerTitle` option together with a `headerLeft` component in native stack navigator does not work on Android and defaults to rendering the screen name.

```
<Stack.Screen
        name={"SomeScreenName"}
        component={SomeScreen}
        options={{ headerTitle: "Some title", headerLeft: () => <View></View> }}
    />
```

The above snippet shows "SomeScreenName" as a title on Android, and "Some title" on iOS

![screenshot_20220323-104202_expo_go](https://user-images.githubusercontent.com/10097195/159660744-441c6ace-309c-45cc-9256-869b5e574e8b.jpg)
![IMG_9E7B12B34393-1](https://user-images.githubusercontent.com/10097195/159660418-a5d1b8ba-f3ed-47d4-932b-a868d08ff56c.jpeg)

### Expected behavior

Expected to display "Some title" as headerTitle on Android

### Reproduction

https://snack.expo.dev/GPB2h8--J

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.0.8
| @react-navigation/bottom-tabs          | 6.2.0
| @react-navigation/drawer               |
| @react-navigation/material-bottom-tabs |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                | 6.1.1
| @react-navigation/native-stack         | 6.5.0
| react-native-safe-area-context         | 3.3.2
| react-native-screens                   | 3.13.1
| react-native-gesture-handler           | 2.3.2
| react-native-reanimated                | 2.4.1
| react-native-tab-view                  |
| react-native-pager-view                | 5.4.11
| react-native                           | 0.66.4
| expo                                   | 44.0.6
| node                                   | 16.5.0
| yarn                            | 1.22.15

**Comment by damonbauer** [comment]
Seeing the same issue. A workaround is to set the `title` prop as well: https://snack.expo.dev/6oYraycY5
