### ISSUE TITLE
Native stack landscape orientation weird rotate effect after close

### ISSUE THREAD

**Issue by vargajacint** [react-navigation/react-navigation#10459]
### Current behavior

https://user-images.githubusercontent.com/42407460/160243830-6a34a2c9-769f-4f48-8f3e-e9f3fe6ba608.mp4

### Expected behavior

As you can see after the landscape screen close the previous screen rotates back to portrait.
I would like to achive the previous screen should be portrait but, DO NOT ROTATE. Just simply stay portrait.

Maybe, after navigating to landscape screen the previous screen get detached or something simiular?

### Reproduction

https://github.com/vargajacint/nativestack-problem/blob/main/index.tsx

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [X] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | ^6.0.2
| @react-navigation/bottom-tabs          | ^6.0.5
| @react-navigation/material-top-tabs    | ^6.0.2
| @react-navigation/stack                | ^6.0.7
| @react-navigation/native-stack         | ^6.5.2
| react-native-safe-area-context         | ^3.2.0
| react-native-screens                   | ^3.3.0
| react-native-gesture-handler           | 2.3.0
| react-native-reanimated                | 2.4.1
| react-native-tab-view                  | 3.1.1
| react-native-pager-view                | 5.4.11
| react-native                           | ^0.67.2
| node                                   | 16.0.0
| npm or yarn                            | yarn

**Comment by vargajacint** [comment]
Yes it still exist! I'm using the newest packages!

**Comment by vargajacint** [comment]
Still issue, I provided reproduction repo

**Comment by vargajacint** [comment]
still issue

**Comment by jafar-jabr** [comment]
any update ?

**Comment by tslater** [comment]
Looks like the core issue is in react-native-screens:
https://github.com/software-mansion/react-native-screens/issues/1341

Hasn't been any sort of movement on that in a while.
