### ISSUE TITLE
MaterialTopTab focus/blur event order

### ISSUE THREAD

**Issue by tomasmozeris** [react-navigation/react-navigation#10460]
### Current behavior

Using MaterialTopTabs and navigating from one Tab1 to Tab2 with event listeners focus/blur most of the time order is:
- Tab2 focus
- Tab1 blur

### Expected behavior

Using MaterialTopTabs and navigating from one Tab1 to Tab2 with event listeners focus/blur order:
- Tab1 blur
- Tab2 focus

### Reproduction

https://snack.expo.dev/9Yff3GI1R

### Platform

- [X] Android
- [X] iOS
- [X] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [X] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |6.0.8        |
| @react-navigation/material-top-tabs    |6.1.1
| react-native-safe-area-context         |3.3.2
| expo                                   |43.0.0

**Comment by satya164** [comment]
That's a weird way to check the order of events - it's logging when the effect gets executed, not when the event fires. Simply logging inside the event shows it has correct order: https://snack.expo.dev/@satya164/material-top-tabs-navigator-%7C-react-navigation
