### ISSUE TITLE
Wrong CompositeNavigationProp resulting TS type

### ISSUE THREAD

**Issue by Gustash** [react-navigation/react-navigation#10471]
### Current behavior

I currently have the following declarations for some of my Screens:

```ts
export type UnlockedRoutes = {
  ChatList: undefined;
  ChatDialog: {
    dialog: Dialog;
  };
  CreateDialog: undefined;
  Directory: undefined;
  Profile: undefined;
};

export type RootRoutes = {
  Privacy: undefined;
  UnlockedNavigation: NavigatorScreenParams<UnlockedRoutes>;
};

export type UnlockedNavigationProp<
  RouteName extends keyof UnlockedRoutes = keyof UnlockedRoutes
> = CompositeScreenProps<
  NativeStackScreenProps<UnlockedRoutes, RouteName>,
  StackScreenProps<RootRoutes, 'UnlockedNavigation'>
>;
export type CreateDialogScreenNavigationProp = UnlockedNavigationProp<'CreateDialog'>;
export type DirectoryScreenNavigationProp = UnlockedNavigationProp<'Directory'>;
export type ProfileScreenNavigationProp = UnlockedNavigationProp<'Profile'>;
export type ChatDialogScreenNavigationProp = UnlockedNavigationProp<'ChatDialog'>;
export type ChatListScreenNavigationProp = UnlockedNavigationProp<'ChatList'>;
```

If you try to use `navigation.setOptions({fullScreenGestureEnabled: true})` (as an example) on `ChatDialogScreenNavigationProp`, this works fine and TS doesn't complain.

But if you attempt the same thing with `ChatListScreenNavigationProp`, TS will complain that `fullScreenGestureEnabled` is not a key in options.

I have done some research and for some reason if the params type for a route is `undefined`, `A extends NavigationProp<any, infer U> ? U : never` always returns `never`.

A fix I was able to find is if you change the above definition to `A extends NavigationProp<infer _T, infer U> ? U : never`, the type will be `U` as expected.

This can be fixed by changing the `CompositeNavigationProp` definition to:

```ts
export declare type CompositeNavigationProp<A extends NavigationProp<ParamListBase, string, any, any>, B extends NavigationHelpersCommon<ParamListBase, any>> = Omit<A & B, keyof NavigationProp<any>> & NavigationProp<
/**
 * Param list from both navigation objects needs to be combined
 * For example, we should be able to navigate to screens in both A and B
 */
(A extends NavigationHelpersCommon<infer T> ? T : never) & (B extends NavigationHelpersCommon<infer U> ? U : never), 
/**
 * The route name should refer to the route name specified in the first type
 * Ideally it should work for any of them, but it's not possible to infer that way
 */
A extends NavigationProp<infer _T, infer R> ? R : string, 
/**
 * The type of state should refer to the state specified in the first type
 */
A extends NavigationProp<infer _T, infer _R, infer S> ? S : NavigationState, 
/**
 * Screen options from both navigation objects needs to be combined
 * This allows typechecking `setOptions`
 */
(A extends NavigationProp<infer _T, infer _R, infer _S, infer O> ? O : {}) & (B extends NavigationProp<infer _T, infer _R, infer _S, infer P> ? P : {}), 
/**
 * Event consumer config should refer to the config specified in the first type
 * This allows typechecking `addListener`/`removeListener`
 */
A extends NavigationProp<infer _T, infer _R, infer _S, infer _O, infer E> ? E : {}>;
```

In the attached TS Playground, you can see that `NonWorkingInferWillBeNever` will not be properly typed, whereas `WorkingInferHasProperType` will.

### Expected behavior

I expect`setParams`, `setOptions`, etc. get properly typed (e.g. `setOptions` lets me pass both `native-stack` and `stack` screen options)

### Reproduction

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgZRgQwMYGtkagU3wDsAFKCMAZzgF84AzckOAcgAEDMYBaItAN2ABzNDGAQiAekrpsLANwAoUJFiI4AYQjgIlYDHy4CxMhUoAaOADkBw0eNLkwlm4JExoRwqTRQ0IajpGbVYOfC5eW3cHST4xfnwFZR01JBt4w1kcPG9TKloGJlDODB4+N3sJWPsE7hlMLEkAG2AAI0kYAE8wfEo8YDAYaSgMDu7epMV8AA9VeC6euAAlCAgYFYBXA2oAXkRFOEO4MmB+TE6ALjgNogATfHpgInxbpSO4AFUiJohsF9c7GIJFcAe5PDkTL5-JQADxfH5-W6bbYAPiUNCUU1m0Hm40+31+WBeyN6cD2CAORw0AAtRAAZYAyK43e6PZ6vSmHGmiAAiwDQPyEVwp73et35guFcGAtyuMigTyEtDeRwxnM0nAMfIFECF1zuDyeLxVhz5BFK0Eu+tZRo571Mjya+GZBrZxsUapmczgC3w+IRRNuoMqjgoMPVJJsID9MwMd2oRM6EHo-sJxIgW1Je0TydTiJJlHVKLJmm0kD0Bi8JicsPV73Sp0yDSroaocIJ+Yz20skf8+BR5jrR1QzYhrdhKzWBcsLHhaaDURDLBRRaUXpxPrxGk1+G1gpbwaBrZLc8Rh4ceRhLG34S1Et1y7X2LUvrgZvwFqgnQPi6PeRPHaBueEiXiw76fp0j5Yt6r4OsATo-hUf5OABAb-L+F5OFecFOlB64vlutIwHuuqIYCmEUKh87Aa2V7csR95CHhz64os9EMjIZHRCBKF7KeQEYTxYbXkRHEwFBiivlYEgAOrQFgioAJJEPQ+BQDJ8FNAAQvgVj4AkUAlg2CQjtgLZ5LC-HppmFisOxjLiSiADaLDlOREgsAAunAsbELc1A0ZeaBEJ0ljBaFcDhWFIWWE8qmGQAKsWAD8cAJXAVzPAZSivnJUAKUQQjKfFAASaCUHkakJXiezGU2ZljhZ7ZoUiXa9DO9kyMuLludxRBeT50xxv51iCbRcVqXAAD6CWxSpk1TR8c3xdNADSy0LcgG2GUsKXLBlcBZWpmIYBIMhwAA7uQhXFWpIKyfJSnzepmk6XpBkliKRz0BsTRNC2ADivQwBsBAAKJ8K0Tqyj6UAbPgg5qqdRDnadUDmjAt1QFceUFUVz1lRVThVTV+zvD9f2A8DoP4BDaBQy8VwwHDCMevIQA

### Platform

- [X] Android
- [X] iOS
- [X] Web
- [X] Windows
- [X] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [x] @react-navigation/drawer
- [x] @react-navigation/material-bottom-tabs
- [X] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [X] @react-navigation/native-stack

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.0.10
| @react-navigation/bottom-tabs          | 6.3.1
| @react-navigation/stack                | 6.2.1
| @react-navigation/native-stack         | 6.5.2
| react-native-safe-area-context         | 3.3.2
| react-native-screens                   | 3.13.1
| react-native-gesture-handler           | 1.10.3
| react-native-reanimated                | 2.4.1
| react-native                           | 0.67.2
| expo                                   | 44.0.6
| node                                   | 16.13.2
| npm                            | 8.1.2
| typescript					 | 4.2.4

**Comment by satya164** [comment]
Thanks for the issue, can you send a PR with a fix and a test [here](https://github.com/react-navigation/react-navigation/blob/main/example/types.check.tsx) to make sure it doesn't break in future?

**Comment by cjhines** [comment]
I'm also experiencing these issues.
