### ISSUE TITLE
Web: Selecting first tab unexpectedly navigates back when both linking and initialRouteName are used

### ISSUE THREAD

**Issue by jrc** [react-navigation/react-navigation#10481]
### Current behavior

1. Create a new app and paste the code from https://reactnavigation.org/docs/tab-based-navigation/#a-native-stack-navigator-for-each-tab
2. Add a `linking` config to the navigation container:
    ```
    const linking = {
        prefixes: [
            /* your linking prefixes */
        ],
        config: {
            screens: {
                HomeStack: {
                    screens: {
                        Home: 'home',
                        Details: 'home/details',
                    },
                },
                SettingsStack: {
                    screens: {
                        Settings: 'settings',
                        Details: 'settings/details',
                    },
                },
            },
        },
    };
    ```
    
4.  Set `initialRouteName` on the tab navigator to be the second tab:
    ```
    <NavigationContainer linking={linking}>
    <Tab.Navigator initialRouteName="SettingsStack">
        <Tab.Screen name="HomeStack" component={HomeStackScreen} />
        <Tab.Screen name="SettingsStack" component={SettingsStackScreen} />
    </Tab.Navigator>
    </NavigationContainer>
    ```
    (optional) Also fix up the tab screen names to not be ambiguous (buggy sample code).
5. Run the app. The app defaults to the second tab (SettingsStack) as expected.
6. Click on the first tab (HomeStack). Instead of switching to the first tab, the browser navigates back instead, possibly even going outside the app.

Attaching screen recording demonstrating the behavior.

Notes:
The problem only seems to occur if the `initialRouteName` is used, causing the window location to change.
* Does not reproduce if `linking` is not set.
* Does not reproduce if `initialRouteName` is not set or is set to the first tab.
* Can't reproduce in Snack as you can't explicitly reload the app in the browser (as far as I can tell).

https://user-images.githubusercontent.com/334386/161596478-dd03ed4b-0466-4470-bca1-52f3bb33787d.mov

Possible related to
* https://github.com/react-navigation/react-navigation/issues/10398 (but here the back button is never used)
* https://github.com/react-navigation/react-navigation/issues/10152

### Expected behavior

The app should switch to each tab normally.

### Reproduction

https://snack.expo.dev/@john_gronska/setting-initialroutename-on-navigation-incorrectly-navigates-back-when-selecting-first-tab

### Platform

- [ ] Android
- [ ] iOS
- [X] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack

### Environment

- [X] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |
| @react-navigation/bottom-tabs          | 6.3.1 |
| @react-navigation/drawer               |
| @react-navigation/material-bottom-tabs |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                |
| @react-navigation/native-stack         | 6.6.1 |
| react-native-safe-area-context         | 3.3.2 |
| react-native-screens                   | 3.8.0 |
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           | 0.64.3 |
| expo                                   | 44.0.6 |
| node                                   | 16.13.2 |
| npm or yarn                            | 8.4.0 |

**Comment by jrc** [comment]
> Couldn't find version numbers for the following packages in the issue:
> 
> * `@react-navigation/native`
> * `@react-navigation/drawer`
> * `@react-navigation/material-bottom-tabs`
> * `@react-navigation/material-top-tabs`
> * `@react-navigation/stack`
> 
> Can you update the issue to include version numbers for those packages? The version numbers must match the format 1.2.3.

Not needed

**Comment by mtourj** [comment]
We are also seeing this problem. In our setup, starting on a route within a stack that defines an `initialRouteName` causes calling `goBack()` to take you outside the page instead of to the initial route. I even found that it navigates outside of the page when using the tab bar to navigate to a route with the path "" (configured with `linking` prop). This is a breaking issue for web

**Comment by ruida-shen** [comment]
In my case, this happens with/without initialRouteName defined.

**Comment by ruida-shen** [comment]
> Also experiencing this without an initialRouteName defined. This makes tab navigation unusable for me on web with linking.

My temporary workaround is that in App.tsx I called window.history.pushState twice, that solves my problem
