### ISSUE TITLE
navigate() does not add the current screen to history

### ISSUE THREAD

**Issue by Rc85** [react-navigation/react-navigation#10486]
### Current behavior

If I call navigate from a drawer screen to another screen, it doesn't add the current screen to history. So when calling goBack() on the new screen, it goes back to wrong screen. For example

Initial render renders Home screen.
Open drawer to go to Profile screen.
In Profile screen, click on button to go Help screen.
In Help screen, click back button.
You're back at Home screen.

### Expected behavior

It should go back to the screen navigate() was called from.

Initial render renders Home screen.
Open drawer to go to Profile screen.
In Profile screen, click on button to go Help screen.
In Help screen, click back button.
You should be in Profile screen.

### Reproduction

https://snack.expo.dev/fut0Aj7RsC

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.0.10
| @react-navigation/bottom-tabs          |
| @react-navigation/drawer               | 6.4.1
| @react-navigation/material-bottom-tabs |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                |
| @react-navigation/native-stack         |
| react-native-safe-area-context         | 3.1.4
| react-native-screens                   | 3.13.1
| react-native-gesture-handler           | 2.3.2
| react-native-reanimated                | 2.5.0
| react-native-tab-view                  | 
| react-native-pager-view                |
| react-native                           | 0.68.0
| expo                                   | 
| node                                   | 14.16.0
| npm or yarn                            | 6.14.11

**Comment by Rc85** [comment]
Totally missed the `backBehavior` prop.

**Comment by arthwood** [comment]
> Totally missed the `backBehavior` prop.

@Rc85 Thanks for pointing the issue! `firstRoute` being a default feels counter intuitive - a `history` would be better 🤔

**Comment by Shameel123** [comment]
`backBehavior="history"` solved the issue for me too.
Thank you for pointing this out!

I believe this wasn't the case with v5.
