### ISSUE TITLE
Feature Request: Consistent availability of `navigation.state.params`

### ISSUE THREAD

**Issue by atshakil** [react-navigation/react-navigation#1048]
Currently, when there is no param available for a screen, `navigation` prop doesn't include a `params` property.

For an example, when some param is passed, `navigationOptions` of a screen gets,
```
"props": {
  "navigation": {
    "state": {
      "routeName": "S1",
      "key": "Init",
      "params": {
        "headless": true,
        "title": "Screen 1"
      }
    }
  },
  "screenProps": {},
  "navigationOptions": {}
}
```
but, when no param is passed, the screen gets
```
"props": {
  "navigation": {
    "state": {
      "routeName": "S6",
      "key": "Init"
    }
  },
  "screenProps": {},
  "navigationOptions": {}
}
```

This leads to difficulties in checking screen `params`. Consider the following scenario. In order to set a property value based on the availability of a specific param, we'll have to write,
```
navigationOptions({navigation}) {
  return {
    headerVisible: !(navigation.state.params && navigation.state.params.headless)
  };
}
```

But, if `params` had a consistent availability (e.g. `params: {}`) like `screenProps` or `navigationOptions`, then we could just write,
```
navigationOptions({navigation}) {
  return {
    headerVisible: !navigation.state.params.headless
  };
}
```

**Comment by jamesisaac** [comment]
Agree it would be nice, but in the mean time you can write your example as

```javascript
navigationOptions({ navigation }) {
  const { params = {} } = navigation.state
  return {
    headerVisible: !params.headless,
  };
}
```

or

```javascript
navigationOptions = ({ navigation: { state: { params = {} } } }) => ({
  headerVisible: !params.headless,
})
```

**Comment by Jacse** [comment]
I think this would be a very meaningful change, just like React Components without props have a default empty object. While the workaround posted by @jamesisaac will work, it is not exactly a clean or intuitive solution.

**Comment by kelset** [comment]
Pinging OP @atshakil since this issue is quite old and related to an old version of the lib. If no answer I'll close in 7 days.

**Comment by dantman** [comment]
@kelset There haven't been ant changes to react-navigation that fix this issue.

**Comment by kelset** [comment]
@dantman understood. I'll keep this open then. I actually think there are some other issues (and maybe even a PR that tackle this issue) but anyway I'll keep this open for the time being.

**Comment by brentvatne** [comment]
we should make a getter for this: `this.props.navigation.getParam(key, defaultValue)`

moved this to https://react-navigation.canny.io/feature-requests/p/easier-to-use-params-via-helper-or-default-object
