### ISSUE TITLE
initalRouteParams does not exist anymore in Stack Navigator

### ISSUE THREAD

**Issue by atomfried** [react-navigation/react-navigation#10483]
### Current behavior

You can pass an initialRouteName to Stack Navigator but there is no apparent way to pass route parameters with it. initialRouteParams stopped existing...???

### Expected behavior

There should be initialRouteParams like there used to be.

### Reproduction

There's nothing to reproduce, the option is just gone.

### Platform

- [X] Android
- [X] iOS
- [X] Web
- [X] Windows
- [X] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

I use stack navigator 6.

**Comment by atomfried** [comment]
I found this workaround: https://stackoverflow.com/questions/60115818/initial-route-params-in-react-navigation-v5

**Comment by satya164** [comment]
https://reactnavigation.org/docs/screen/#initialparams
