### ISSUE TITLE
Drawer not closing automatically on navigate v6?

### ISSUE THREAD

**Issue by premdasvm** [react-navigation/react-navigation#10495]
### Current behavior

I have an application with stack navigator nested in a drawer navigator, so I use `screen parameter` to navigate through my nested views.
Using this way when on IOS/Android, when when you click on a drawer item to navigate to a new view, the view is changed but it doesn't close the drawer automatically (happens sometimes only). I have to click twice on the item to get the correct behaviour here, I didn't see any API props to change that behaviour, I guess this is a bug.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/14838550/162585077-74873034-06cb-4d28-87ee-46f023e97760.gif)

### Expected behavior

When clicking on a drawer item, it navigates to the matching view and closes the drawer automatically.

### Reproduction

https://github.com/premdasvm/react_navigation_drawer_issue_reproduce

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/drawer
- [X] @react-navigation/native-stack

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.0.10
| @react-navigation/drawer               | 6.4.1
| @react-navigation/native-stack         | 6.6.1
| react-native-safe-area-context         | 4.2.4
| react-native-screens                   | 3.13.1
| react-native-gesture-handler           | 2.1.1
| react-native-reanimated                | 2.6.0
| react-native                           | 0.68.0
| node                                   | 16.13.0
| npm or yarn                            | 8.1.0

**Comment by samvangucht** [comment]
I recently had the same problem. It's because your DrawerNavigator doesn't recognize the components from the MainStackNavigator. You are navigating 'brute force' to the screens from the Stack in your DrawerContent. Can you try to remove all those stack screens and add them to your DrawerNavigator as drawer screens?

Keep me posted.

**Comment by premdasvm** [comment]
@samvangucht 

I Tried that, It does seem be working (the issue hasn't popped up yet), But doing it like this kinda gives me another issue, I've a nested view, to to I navigate from one of these pages for example, `Orders -> OrderDetails` when I put all my screens under the `DrawerNavigator` when I'm on `OrderDetails` screen and press the back button it takes me back to the `DrawerNavigator`'s initialRoute instead of `Orders` page. Any workaround to avoid this behaviour?

**Comment by premdasvm** [comment]
Update :

Moving all screens under to `DrawerNavigator` didn't fix the issue, it's still showing sometimes.

**Comment by KestasVenslauskas** [comment]
You can call `navigation.closeDrawer()` manually before navigating.
I usually use custom views for drawerContent and calling it manually doesn't seem to have this issue.

**Comment by premdasvm** [comment]
setting the `useLegacyImplementation` to `true `in my drawer navigator seem to fix my issue (I guess, issue hasn't popped up yet).

**Comment by Ben-WD** [comment]
Same problem, workaround from @premdasvm works fine though 👍🏻

**Comment by juspeeh** [comment]
Setting `useLegacyImplementation` true and the whole app freezes without errors.

**Comment by Edulynch** [comment]
Setting `useLegacyImplementation` to `true` in `Drawer.Navigator` <= `const Drawer = createDrawerNavigator();` 
this solved the problem.

**Comment by JazaelRivas** [comment]
@premdasvm you just saved my proyect. 
placing useLegacyImplementation like this:  <Drawer.Navigator useLegacyImplementation > </Drawer.Navigator>,
worked for me.

**Comment by PakDragoon** [comment]
Setting useLegacyImplementation to true makes the drawer closes as soon you open it, can't select any option(drawer screens) as the drawer closes quickly xD

**Comment by tipleavalentin** [comment]
Hi! It seems the issue persists in @react-navigation/drawer 6.6.4. Mostly on Xiaomi or Redmi phones, on Samsung works flawless.
The animations is lagging a lot and most of the times it's not closing at all. I tried multiple animations and "slide" seems to work a little better but it's a big issue.

**Comment by mprync** [comment]
I had the same issue, with stacks inside drawer navigation and navigation wouldn't close so I had to use DrawerActions and dispatch closeDrawer manually.

https://reactnavigation.org/docs/drawer-actions/

**Comment by ewein** [comment]
It seems to be an issue with Android 14 as well. Once the Drawer is opened it can't be closed by pressing out side or navigating to a new screen.

**Comment by GuoXiaoyang** [comment]
> I'm also still seeing this issue on Android only. Once the Drawer is opened it can't be closed by pressing out side or navigating to a new screen. Seems to only be when using Hermes, JSC works fine.我仍然仅在 Android 上看到此问题。一旦抽屉打开，就无法通过按外侧或导航到新屏幕来关闭它。似乎只有在使用 Hermes 时，JSC 才能正常工作。

Same issue here. Some of our users with Android 14 reported this issue. But I cannot reproduce now.

**Comment by VimukthiShohan** [comment]
+1
