### ISSUE TITLE
Getting navigation.dangerouslyGetState is not a function on tab navigation

### ISSUE THREAD

**Issue by akshaykatale99** [react-navigation/react-navigation#10493]
### Current behavior

Getting the following error when using bottom-tabs navigation.

`TypeError: navigation.dangerouslyGetState is not a function. (In 'navigation.dangerouslyGetState()', 'navigation.dangerouslyGetState' is undefined)`

![Screenshot 2022-04-09 at 1 06 35 PM](https://user-images.githubusercontent.com/12472207/162561951-9a980e9b-bafa-4750-8995-27d70798f52f.png)

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

"@expo-google-fonts/poppins": "^0.2.2",
    "@react-navigation/bottom-tabs": "^6.3.1",
    "@react-navigation/drawer": "^6.4.1",
    "@react-navigation/native": "^6.0.10",
    "@react-navigation/stack": "^6.2.1",
    "axios": "^0.26.1",
    "expo": "~44.0.2",
    "expo-font": "~10.0.4",
    "expo-linear-gradient": "~11.0.3",
    "expo-splash-screen": "~0.14.1",
    "expo-status-bar": "~1.2.0",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-native": "0.64.3",
    "react-native-config": "^1.4.5",
    "react-native-gesture-handler": "~2.1.0",
    "react-native-reanimated": "~2.3.1",
    "react-native-safe-area-context": "3.3.2",
    "react-native-screens": "~3.10.1",
    "react-native-web": "0.17.1"

**Comment by satya164** [comment]
https://reactnavigation.org/docs/upgrading-from-5.x/
