### ISSUE TITLE
Drawer reopen when navigating screen

### ISSUE THREAD

**Issue by zeeshan-shabbir** [react-navigation/react-navigation#10503]
### Current behavior

I am using react navigation drawer v6 with custom header when click on hamburger menu it show drawer its work fine but when I navigate from drawer it change screen and reopen drawer sometime . I don't known its a bug Or something else .I am attaching gif of behavior. 
![ezgif com-gif-maker](https://user-images.githubusercontent.com/80969033/162903402-49630dfb-f361-4ba0-a625-d54af8b59763.gif)

### Expected behavior

Drawer should not reopen .

### Reproduction

https://github.com/zeeshan-shabbir/Native

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [X] @react-navigation/material-bottom-tabs
- [X] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [X] @react-navigation/native-stack

### Environment

 "@react-navigation/drawer": "^6.4.1",
    "@react-navigation/material-top-tabs": "^6.1.1",
    "@react-navigation/native": "^6.0.8",
    "@react-navigation/stack": "^6.1.1",
    "react": "17.0.2",
    "react-native": "0.67.3",
   
    "react-native-gesture-handler": "^2.3.0",
    "react-native-pager-view": "^5.4.15",
  
    "react-native-reanimated": "^2.4.1",
    "react-native-safe-area-context": "^4.0.1",
    "react-native-screens": "^3.12.0",

**Comment by amandeepmittal** [comment]
seems like a duplicate for #10495

**Comment by zeeshan-shabbir** [comment]
It doesn't seem like duplicate, my drawer sometimes reopen not every time and all my screens are defined under drawer navagation.

**Comment by premdasvm** [comment]
try adding `useLegacyImplementation` to `true` inside your drawer navigator, that seemed to fix my issue.   #10495

**Comment by zeeshan-shabbir** [comment]
useLegacyImplementation  to true worked for me. thanks

**Comment by juspeeh** [comment]
useLegacyImplementation did not work for me. Whole app freezes when set as true

**Comment by DmitriyNikolenko** [comment]
> <img alt="@DmitriyNikolenko" width="40" height="40" src="https://avatars.githubusercontent.com/u/25880968?s=80&amp;v=4">

App freezes may happen due to using React Native Debugger (see https://github.com/software-mansion/react-native-reanimated/issues/1223)

You can try `useLegacyImplementation={process.env.NODE_ENV !== 'development'}`

**Comment by aminedammak** [comment]
Setting useLegacyImplementation to true worked for me. thank you!

**Comment by LandoSot** [comment]
Set uselegayImplementation to true works... thanks!

**Comment by izzis92** [comment]
I faced the issue when setting the drawer style.width to '100%'. changing to Dimensions.get('screen').width fixed the issue
