### ISSUE TITLE
Drawer open status delays

### ISSUE THREAD

**Issue by Melzmr** [react-navigation/react-navigation#10504]
### Current behavior

On latest version `6.4.1` it becomes impossible to immediately close the drawer by calling `closeDrawer()`.
Here is the snack [Drawer lag 6.4.1](https://snack.expo.dev/@melz_mr/drawer-lag-6_4_1) taken and edited from the official [docs](https://reactnavigation.org/docs/drawer-based-navigation/#opening-and-closing-drawer).
I simply deleted `useLegacyImplementation` and that's all.
Steps:
1) Open drawer.
2) Try to click the button `Close drawer` right after drawer opens.
3) It won't close unless a couple of secs later

Interesting that if you use version `6.3.0` everything works smoothly. Try this snack [Drawer NO lag 6.3.0](https://snack.expo.dev/@melz_mr/drawer-no-lag-6_3_0).

### Expected behavior

1) Open drawer.
2) Clicking on button with callback `closeDrawer()` should close the drawer even if user clicks it immediately after the drawer opened.

### Reproduction

https://snack.expo.dev/@melz_mr/drawer-lag-6_4_1

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | ^6.0.10
| @react-navigation/drawer               |^6.4.1
| @react-navigation/stack                |^6.2.1
| react-native-safe-area-context         |3.3.2
| react-native-gesture-handler           |~2.1.0
| react-native-reanimated                |~2.3.1
| react-native                           |0.64.3
| expo                                   |^44.0.4
| node                                   |v16.14.0
| npm                            |8.3.1

**Comment by Melzmr** [comment]
> Couldn't find version numbers for the following packages in the issue:
> 
> * `@react-navigation/bottom-tabs`
> * `@react-navigation/material-bottom-tabs`
> * `@react-navigation/material-top-tabs`
> 
> Can you update the issue to include version numbers for those packages? The version numbers must match the format 1.2.3.

I don't use them

**Comment by Melzmr** [comment]
Still not working when swiping from aside :(

**Comment by manelio** [comment]
Exactly the same three problems I'm facing:

- Drawer open status delay
- Drawer reopen when navigating screen #10503
- Drawer not closing automatically on navigate v6? #10495

That's driving the UX feeling unreliable and quite uncomfortable.

I'm trying downgrading to @react-navigation/drawer@6.3.0

**Comment by juspeeh** [comment]
Same issues for me
