### ISSUE TITLE
Tab Navigator created using example loads all the tabs ==

### ISSUE THREAD

**Issue by Vinay-Revankar** [react-navigation/react-navigation#10511]
### Current behavior

Custom Tab Navigator created using example loads all the tab screen at once. Setting option lazy true does not work
https://reactnavigation.org/docs/custom-navigators#usenavigationbuilder

### Expected behavior

Custom Tab Navigator created using example needs to lazy load on mount

### Reproduction

da

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

[BottomTabNavigation.txt](https://github.com/react-navigation/react-navigation/files/8482544/BottomTabNavigation.txt)
[CustomBottomTabNavigator.txt](https://github.com/react-navigation/react-navigation/files/8482545/CustomBottomTabNavigator.txt)

**Comment by satya164** [comment]
It's an example to build custom navigator, it doesn't try to replicate or implement features of  full navigators. You can implement any functionality you want including lazy rendering.

**Comment by hammadwahab12** [comment]
any update on this please, facing this same issue
