### ISSUE TITLE
Throw warning or error when navigate to an invalid route

### ISSUE THREAD

**Issue by sibelius** [react-navigation/react-navigation#1053]
I made a typo on one of my `this.props.navigation.navigate('routeName`)` and it was hard to figure it out 

can we throw a warning or an error when this happens?

**Comment by azisuazusa** [comment]
@grabbou @sibelius can you check my PR for this Issue? I've tried to create warning if routeName is not found

**Comment by brentvatne** [comment]
https://react-navigation.canny.io/feature-requests/p/throw-warning-or-error-when-navigate-to-an-invalid-route
