### ISSUE TITLE
forModalPresentationIOS interpolate crashes because there is no layout.screens yet

### ISSUE THREAD

**Issue by sjors98** [react-navigation/react-navigation#10533]
### Current behavior

We've recently updated to React Navigation 6 in our react-native application and stumbled upon this issue.
For one screen in a Stack Navigator we are using the `forModalPresentationIOS` cardStyleInterpolator. For the rest in this stack we are using the `forVerticalIOS` cardStyleInterpolator.
Since the update the app isn't able to boot because a nan value is given in the `forModalPresentationIOS` cardStyleInterpolator.
I've did some debugging and it turnes out the aspectRatio is NaN because the values that are given through the layouts.screen are 0 for a while. This line needs some nan/0 checking I guess: https://github.com/react-navigation/react-navigation/blob/main/packages/stack/src/TransitionConfigs/CardStyleInterpolators.tsx#L109

I've fixed it for now in our own repo by doing this: 
```
cardStyleInterpolator: (cardStyleInterpolatorCallback) => {
    const height = cardStyleInterpolatorCallback.layouts.screen.height || 100; // Replace 100 with the screen height ofcourse
    const width = cardStyleInterpolatorCallback.layouts.screen.width || 100; // Replace 100 with the screen width ofcourse
    console.log('height', height, 'width', width);

    return CardStyleInterpolators.forModalPresentationIOS({
        ...cardStyleInterpolatorCallback,
        layouts: {
            screen: {
                height,
                width,
            },
        },
    });
},
```
But my colleagues and myself are getting nauseas when we see this. 

The height and width are given somewhere because after a few rerenders these values are present (100 will be replaced in the log with the actual values). But without this the app already has crashed before it reaches that point.

### Expected behavior

I expect the aspectRatio to be checked for NaN or the layout.screen values to be given before this function is called.

I've pasted a snack below, but the behaviour I am seeing only occurs after a fresh install of the app. So I'm not entirely sure if this will work in Snack

### Reproduction

https://snack.expo.dev/RLvGRznfW

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |6.0.6
| @react-navigation/material-top-tabs    | 6.2.1
| @react-navigation/stack                |6.2.1
| react-native-safe-area-context         | 3.3.2
| react-native-screens                   |3.10.1
| react-native-gesture-handler           |1.10.0
| react-native-reanimated                |2.4.1
| react-native-tab-view                  |3.1.1
| react-native-pager-view                |5.4.15
| react-native                           |0.66.4
| node                                   |14.19.1
npm or yarn                            |1.22.18

**Comment by satya164** [comment]
> I've pasted a snack below, but the behaviour I am seeing only occurs after a fresh install of the app. So I'm not entirely sure if this will work in Snack

If you can't reproduce on Snack then that's not a repro. Providing a non-reproducible demo doesn't help with debugging.
