### ISSUE TITLE
Align `tabBarLabel` option signature between Material Bottom Tabs and Material Top Tabs

### ISSUE THREAD

**Issue by fabriziocucci** [react-navigation/react-navigation#10544]
### Current behavior

It seems that the definition of the `tabBarLabel` option is not consistent between Material bottom and top tabs.

Specifically:
```
// packages/material-bottom-tabs/src/types.tsx
  tabBarLabel?: string;

// packages/material-top-tabs/src/types.tsx
  tabBarLabel?:
    | string
    | ((props: { focused: boolean; color: string }) => React.ReactNode);
```

Is there a specific reason for this inconsistency or would you accept a PR to give the Bottom Tabs option the same level of flexibility as the Top Tabs one? i.e. support passing a function that given `{ focused: boolean, color: string }` returns a `React.Node`.

### Expected behavior

Ideally, the `tabBarLabel` option of the two packages should be aligned:

```
// packages/material-bottom-tabs/src/types.tsx
  tabBarLabel?:
    | string
    | ((props: { focused: boolean; color: string }) => React.ReactNode);

// packages/material-top-tabs/src/types.tsx
  tabBarLabel?:
    | string
    | ((props: { focused: boolean; color: string }) => React.ReactNode);
```

### Reproduction

[TS Playground](https://www.typescriptlang.org/play?#code/PTAEBUAsFMCdtASwM6gHYHsAulFoOahYajwAOsGANKMtAjguAMpECeZ0qAJtAGZ5EWRBjSgMfIjCIB3EmQCGAYwDWC-FwBcAKBCgAVKACyCrHEQKANqABC2YgFsICgEbJNoSFixl3IfEKQAK4uAHRKGA7A8MpYALRoCgBuiPimImjR0LEJyanposAulhguwA4KeMCKqupc5abmVnEu9pFxWK7IwMiwSsBYHFyhWMgAHgDEADIAbDO6YIYmZrAW1uAYZM5uHl4+fsABOCHhkVk5iSlpwoUxSvGX+TeZxaUNVTVqGt0VK2sdmw6XR6fQGQ2QI3G0wA7ABObSgUBAA)

### Platform

- [ ] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [X] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |
| @react-navigation/bottom-tabs          |
| @react-navigation/drawer               |
| @react-navigation/material-bottom-tabs |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                |
| @react-navigation/native-stack         |
| react-native-safe-area-context         |
| react-native-screens                   |
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           |
| expo                                   |
| node                                   |
| npm or yarn                            |

**Comment by satya164** [comment]
Material Bottom Tabs is a wrapper around React Native Paper and supports what the library supports. If you want more customization, please open an issue there with your use case.

**Comment by fabriziocucci** [comment]
@satya164 not really! :)

React Native Paper already exposes the functionality I'm talking about, it's just not being used by React Navigation at the moment. To put is simply, it should be just a matter of creating the `BottomNavigation` component passing [renderLabel](https://callstack.github.io/react-native-paper/bottom-navigation.html#renderLabel) rather than [getLabelText](https://github.com/react-navigation/react-navigation/blob/main/packages/material-bottom-tabs/src/views/MaterialBottomTabView.tsx#L180).

Does that sound more reasonable?

**Comment by satya164** [comment]
Feel free to send a PR which uses either `renderLabel` or `getLabelText` based on the type of `tabBarLabel`
