### ISSUE TITLE
native-stack: Back button wrong language

### ISSUE THREAD

**Issue by drthoben** [react-navigation/react-navigation#10545]
### Current behavior

My iPhone language is set to German. The back button title says "Back".

### Expected behavior

The back button should say "Zurück".

### Reproduction

https://github.com/drthoben/react-navigation-repro

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native | 6.0.10
| @react-navigation/native-stack | 6.6.2
| expo | 44.0.6
| expo-status-bar | 1.2.0
| react | 17.0.1
| react-dom | 17.0.1
| react-native | 0.64.3
| react-native-safe-area-context | 3.3.2
| react-native-screens | 3.13.1
| react-native-web | 0.17.1
| react-native                           | 0.64.3
| expo                                   | 5.0.3
| node                                   | v16.13.1
| yarn                            | v1.22.17

**Comment by drthoben** [comment]
> Couldn't find version numbers for the following packages in the issue:
> 
> * `@react-navigation/bottom-tabs`
> * `@react-navigation/drawer`
> * `@react-navigation/material-bottom-tabs`
> * `@react-navigation/material-top-tabs`
> * `@react-navigation/stack`
> 
> Can you update the issue to include version numbers for those packages? The version numbers must match the format 1.2.3.

I'm actually not using one of those packages. I'm using native-stack.

**Comment by kacperkapusciak** [comment]
Hi @drthoben :wave:

Apple documentation [How iOS Determines the Language For Your App](https://developer.apple.com/library/archive/qa/qa1828/_index.html#//apple_ref/doc/uid/DTS40014938) states that iOS apps have to be told which languages they support. 

You supply this info in Info.plist file with the `CFBundleDevelopmentRegion` field.

```xml
    <key>CFBundleDevelopmentRegion</key>
    <string>de</string>
```

In Expo-based development you can do this by editing `app.json` file:

```json
{
  "expo": {
    "ios": {
      "infoPlist": {
        "CFBundleDevelopmentRegion": "de"
      }
    }
  }
}

```
and this information will be used when the application is run standalone (e.g. producion build for your users) or when you eject (prebuild) your app.

This **won't work** in the Expo Go app. Expo Go is a compiled application and you can't customize the native parts of this app.

When you do this and run the app standalone the button will say "Zurück" despite the language set in the iPhone.
![image](https://user-images.githubusercontent.com/39658211/191520825-631ab4d2-4408-4b55-ad14-5faab6f33cd2.png)

Cheers
