### ISSUE TITLE
StackNavigator unmountOnBlur?

### ISSUE THREAD

**Issue by tamis-laan** [react-navigation/react-navigation#10542]
### Current behavior

``` javascript
// Screen options
const ScreenOptions = {
  unmountOnBlur: true,
}
```

``` javascript
<Stack.Navigator screenOptions={ScreenOptions} initialRouteName={props.initialRouteName || "Tabs"} >
	<Stack.Screen name="Todo" component={Todo} unmountOnBlur={true}/>
```

Does not umount on blur

### Expected behavior

Would expect component to unmount on blur...

### Reproduction

github.com/bla/null

### Platform

- [ ] Android
- [ ] iOS
- [X] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/stack                |

**Comment by satya164** [comment]
> Would expect component to unmount on blur...

There's no such option in the documentation, so there's no reason to expect that

**Comment by w4t3r-45** [comment]
this option exists in the React Navigation and it is really important but we can't find it in this package so please add it if possible , this is really important

**Comment by yahacom** [comment]
would be great to have it for stack navigator too.

**Comment by pdesign** [comment]
Stack.Navigator does not have unmountOnBlur because, navigation in Stack.Navigator have navigation.replace which replaces (unmounts) the screen if you use navigation.replace... if you use navigation.navigate it will not unmount it and will go back to the previously mounted screen when you navigate to it...
