### ISSUE TITLE
The version of rect-native-gesture-handler this library uses crashes the app in some devices

### ISSUE THREAD

**Issue by fermmm** [react-navigation/react-navigation#10540]
### Current behavior

See this issue in the react-native-gesture-handler github page:

https://github.com/software-mansion/react-native-gesture-handler/issues/1971#issuecomment-1105353865

### Expected behavior

I expect my devices to not crash

### Reproduction

https://github.com/software-mansion/react-native-gesture-handler/issues/1971#issuecomment-1105353865

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |
| @react-navigation/bottom-tabs          |
| @react-navigation/drawer               |
| @react-navigation/material-bottom-tabs |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                |
| @react-navigation/native-stack         |
| react-native-safe-area-context         |
| react-native-screens                   |
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           |
| expo                                   |
| node                                   |
| npm or yarn                            |

**Comment by fermmm** [comment]
> Hey! Thanks for opening the issue. Seems that this issue is related to `react-native-gesture-handler` library which is a dependency of React Navigation. Can you also post your issue in [this repo](https://github.com/software-mansion/react-native-gesture-handler) so that it's notified to the maintainers of that library? This will help us fix the issue faster since it's upto the maintainers of that library to investigate it.

If I understand correctly they already fixed it, you just need to upgrade the library

**Comment by satya164** [comment]
> If I understand correctly they already fixed it, you just need to upgrade the library

The library is installed by you in your project, there's nothing to upgrade on React Navigation's side
