### ISSUE TITLE
Navigation Container 'linking' props not working properly on device Samsung Galaxy S20 Fe

### ISSUE THREAD

**Issue by BrenoLuna0** [react-navigation/react-navigation#10551]
### Current behavior

We have a react-native app using the deeplink funcionality of the react-navigation/native lib to redirect our users to an especific screen of the app based on the url they clicked. We're using the 'linking' property of the NavigationContainer as in the piece of code below. We have already done the native configurations on Android and IOS, and it is working fine on others devices, not on Samsung Galaxy S20 Fe though. I'll show some more codes that may help you:

App.tsx
<img width="540" alt="Captura de Tela 2022-04-27 às 09 43 01" src="https://user-images.githubusercontent.com/29586153/165520496-f1f54c17-f4c3-4267-af0b-34d8c10ed77a.png">

Android Manifest
<img width="602" alt="image" src="https://user-images.githubusercontent.com/29586153/165522739-d307bcc7-cea8-453f-aa24-26f1a4a2fa16.png">

Routes passed to linking props
<img width="385" alt="image" src="https://user-images.githubusercontent.com/29586153/165523255-a9725bff-0183-4333-bd32-a967e710d4c3.png">

When a S20 Fe user clicks on any deeplink that has an especifi handler to a page, the app opens at the Home Page.

### Expected behavior

We expect it to work also on the especific device Samsung Galaxy S20 Fe

### Reproduction

no link

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native              | 5.3.0
| @react-navigation/bottom-tabs          | 5.11.11
| @react-navigation/stack                | 5.3.2
| react-native                           | 0.61.5
| node                                   | 16.8.0
| yarn                            | 1.22.11

**Comment by phuongit0301** [comment]
Im facing same issues with:

"@react-navigation/native": "^6.0.10",
"@react-navigation/native-stack": "^6.6.1",
