### ISSUE TITLE
The 'navigation' object hasn't been initialized yet

### ISSUE THREAD

**Issue by azizmobarak** [react-navigation/react-navigation#10566]
I have this issue in React Native 67 and @react-navigation/native@6.x

I see that mentioned method on documentation is not working for me and also a lot of developers if 'it's not for all, not sure but I suggest to update the documentaion based on that solution I did to fix it :

fixed by using `const navigationRef = useNavigationContainerRef();` I pass the `navigationRef` to the ref in `NavigationContainer` and then I added the functionality when I want to use the `navigationRef` inside `onReady`
you can also use `onStateChange` if you want to listen on state changes , but first initialise the a reference inside `onReady` so you can use it in onStateChange later, I mean create a new ref with `const myRef = useRef()` and inside on Ready you can do `myRef.current = navigationRef.getCurrentRoute() (just an example, depends on your need)`.

_Originally posted by @azizmobarak in https://github.com/react-navigation/react-navigation/issues/6879#issuecomment-1110865599_

**Comment by chetstone** [comment]
I was tearing out what little hair I have left trying to solve this warning which came up after I refactored to reduce the number of navigators. My Navigation Container looked much like what @azizmobarak describes above, and I wasn't using the navigation ref anywhere outside the container-- I only used it for onReady and onStateChange. Most of the docs around this issue focus on finding the use of the ref but a simple use of the navigation prop will also trigger it. 

Finally I found a reference to `this.props.navigate.setParams()` in the 'componentDidMount' method of a sneaky little component that I didn't think would be mounted at startup but was. 

I replaced it with `this.props.navigation.isReady() &&
      this.props.navigation.setParams` and all is good.
