### ISSUE TITLE
drawer navigation app crash regression

### ISSUE THREAD

**Issue by jahglow** [react-navigation/react-navigation#10560]
### Current behavior

App crashes with [this change](https://github.com/react-navigation/react-navigation/commit/ba868fcc87035958dd3250e81691f1f3098be033?diff=split#diff-e53e4593bbd84031aa52494ad48e5b1d9f95f0c4ba669c41f92c1885e4875ba2R88) introduced in v6.3.1, [multiple people facing the same issue](https://github.com/software-mansion/react-native-reanimated/issues/3049#issue-1159595875), the workaround is to be fixed at 6.3.0 atm
Honestly I see no point doing a wildcard import of Reanimated, rather than importing `isConfigured` via destructuring. I don't know if that could bring about some side effect. Snack doesn't reproduce. Reproduced when using the same boilerplate as below in a [monorepo by nx](https://nx.dev/guides/react-native)  and generating a react-native app from it

### Expected behavior

App should not crash

### Platform

- [X] Android **HERMES:ON**
- [ ] iOS
- [ ] Web
- [ ] Windows
- [x] MacOS

### Packages

- [ ] @react-navigation/​bottom-tabs
- [X] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [ ] @react-navigation/​stack
- [ ] @react-navigation/​native-stack

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |  6.0.10
| @react-navigation/drawer               | 6.3.1
| @react-navigation/native-stack         | 6.6.1
| react-native-safe-area-context         | 4.2.4
| react-native-screens                   | 3.13.1
| react-native-gesture-handler           | 2.4.1
| react-native-reanimated                | 2.8.0
| react-native                           | 0.68.0
| node                                   | 16.9.1
| yarn                            | 1.22.7

**Comment by jahglow** [comment]
Issue persists with the latest version as well starting from 6.3.1.
Trace:
```
14:33:45.179
28741
DEBUG
    x8  0000000000000083  x9  8a98b250be06e854  x10 fffffff87ffffbdf  x11 8a98b250be06e854
14:33:45.179
28741
DEBUG
    x12 8a98b250be06e854  x13 fffffff87ffffbdf  x14 00000000000000d0  x15 000000783892e8c8
14:33:45.179
28741
DEBUG
    x16 00000078389222b0  x17 0000007838834088  x18 00000077b6200080  x19 0000000000006f9f
14:33:45.179
28741
DEBUG
    x20 0000000000006f9f  x21 0000000000000083  x22 00000077b6014c00  x23 00000077876f7c00
14:33:45.179
28741
DEBUG
    x24 0000000000000002  x25 00000000ffffffff  x26 0000000000000012  x27 0000000000000005
14:33:45.179
28741
DEBUG
    x28 00000077b5961107  x29 0000007ff9f73040
14:33:45.179
28741
DEBUG
    sp  0000007ff9f73000  lr  00000078388254d0  pc  00000078388254f0
14:33:45.183
28741
DEBUG

backtrace:
14:33:45.183
28741
DEBUG
    #00 pc 00000000000224f0  /system/lib64/libc.so (abort+112)
14:33:45.183
28741
DEBUG
    #01 pc 000000000046e080  /system/lib64/libart.so (art::Runtime::Abort(char const*)+1208)
14:33:45.183
28741
DEBUG
    #02 pc 00000000000095a8  /system/lib64/libbase.so (android::base::LogMessage::~LogMessage()+720)
14:33:45.183
28741
DEBUG
    #03 pc 00000000002e9e6c  /system/lib64/libart.so (art::JavaVMExt::JniAbort(char const*, char const*)+1660)
14:33:45.183
28741
DEBUG
    #04 pc 00000000002e9fe8  /system/lib64/libart.so (art::JavaVMExt::JniAbortV(char const*, char const*, std::__va_list)+116)
14:33:45.183
28741
DEBUG
    #05 pc 00000000000fd884  /system/lib64/libart.so (art::(anonymous namespace)::ScopedCheck::AbortF(char const*, ...)+160)
14:33:45.183
28741
DEBUG
    #06 pc 00000000000fc240  /system/lib64/libart.so (art::(anonymous namespace)::ScopedCheck::CheckPossibleHeapValue(art::ScopedObjectAccess&, char, art::(anonymous namespace)::JniValueType)+1152)
14:33:45.183
28741
DEBUG
    #07 pc 00000000000fb5a8  /system/lib64/libart.so (art::(anonymous namespace)::ScopedCheck::Check(art::ScopedObjectAccess&, bool, char const*, art::(anonymous namespace)::JniValueType*)+628)
14:33:45.183
28741
DEBUG
    #08 pc 00000000000fac38  /system/lib64/libart.so (art::(anonymous namespace)::CheckJNI::GetObjectRefType(_JNIEnv*, _jobject*)+688)
14:33:45.183
28741
DEBUG
    #09 pc 0000000000019098  /data/app/cloud.mpi.mobile.dev-jM_auWHg10r3qT8m2RhiPQ==/lib/arm64/libfbjni.so (facebook::jni::isObjectRefType(_jobject*, jobjectRefType)+76)
14:33:45.183
28741
DEBUG
    #10 pc 0000000000133b00  /data/app/cloud.mpi.mobile.dev-jM_auWHg10r3qT8m2RhiPQ==/lib/arm64/libreanimated.so (facebook::jni::LocalReferenceAllocator::verifyReference(_jobject*) const+32)
14:33:45.183
28741
DEBUG
    #11 pc 0000000000133b78  /data/app/cloud.mpi.mobile.dev-jM_auWHg10r3qT8m2RhiPQ==/lib/arm64/libreanimated.so (facebook::jni::LocalReferenceAllocator::deleteReference(_jobject*) const+80)
14:33:45.183
28741
DEBUG
    #12 pc 0000000000133ac0  /data/app/cloud.mpi.mobile.dev-jM_auWHg10r3qT8m2RhiPQ==/lib/arm64/libreanimated.so (facebook::jni::base_owned_ref<facebook::jni::JString, facebook::jni::LocalReferenceAllocator>::reset(_jstring*)+144)
14:33:45.183
28741
DEBUG
    #13 pc 0000000000133a08  /data/app/cloud.mpi.mobile.dev-jM_auWHg10r3qT8m2RhiPQ==/lib/arm64/libreanimated.so (facebook::jni::base_owned_ref<facebook::jni::JString, facebook::jni::LocalReferenceAllocator>::reset()+28)
```

**Comment by ldcastell** [comment]
I'm facing this same error with the latest version

**Comment by uttu-316** [comment]
Still facing issue

**Comment by armandopadilla** [comment]
Have the same issue. 

    "react-native": "0.69.3",
    "react-native-gesture-handler": "^2.5.0",
    "react-native-reanimated": "^2.9.1",
   "@react-navigation/drawer": "^6.4.3",
    "@react-navigation/native": "^6.0.11",

**Comment by Emyboy** [comment]
I just created a new project and mine started crashing as soon as I added drawer navigation.
Has anyone tried downgrading the packages? 

`   "@react-navigation/drawer": "^6.4.4",
    "@react-navigation/native": "^6.0.12",

     "react-native": "0.69.5",
    "react-native-gesture-handler": "~2.5.0",
    "react-native-reanimated": "~2.9.1",
    "react-native-safe-area-context": "4.3.1",
    "react-native-screens": "~3.15.0"
`
