### ISSUE TITLE
navigation.goBack() inside custom header goes back within wrong navigation stack 

### ISSUE THREAD

**Issue by easymonee** [react-navigation/react-navigation#10561]
### Current behavior

I have multiple StackNavigators inside a TabNavigator.  The architecture looks something like this:

- TabNavigator
    - StackNavigator1 
         - Screen1.1
         - Screen1.2
         - Screen1.3
     - StackNavigator2
         -  Screen2.1
         - Screen2.2
         - Screen2.3
-  TabNavigator

For all my Screens(1.1-2.3) inside those StackNavigators, i build custom headers that look something like this:

```
<Stack.Screen
...
options={{
        header: () => {
          return (
             <View>
                    ...
                    <TouchableOpacity onPress={() => navigation.goBack()}>
                        ...
                    </TouchableOpacity>
                    ...
            </View>
...
/>
```

As you can see there is a TouchableOpacity that triggers navigation.goBack() onPress.

The issue:
If I navigate into StackNavigator1 (navigate a few screens into it -> Screen1.3), switch to StackNavigator2 and also navigate a few screens into that (->Screen2.3), now go BACK to StackNavigator1 (which still shows Screen1.3) click on the Component inside the Header (which should navigate back to Screen1.2), nothing happens. However the navigation.back() triggered the desired behaviour on the WRONG stack. If i go back to StackNavigator2 i can see that it went back there to Screen2.2

So navigation.goBack() goes back on the wrong StackNavigator first until there is nothing to go back and then continues to go back on the StackNavigator i am actually looking at. 

NOTE: All this does not happen if no custom header is used. With Native Header it works as expected. navigation.goBack() would also work correctly as long as its not called from the header. 

### Expected behavior

navigation.goBack() should go back within the StackNavigator it was called, when called from inside a custom header. 

You can reproduce it inside Snack repo:

1. Go to Stack1
2. Click on "Go to Profile"
3. Go to Stack2
4. Click on "Go to Profile"
5. Go back to Stack1
6. Click on red "Back" inside the header
7. First time "nothing" happens
8. click again - now it works

9. go to Stack2
10. it is now also navigated back, as the first time we hit "Back" it took affect on this StackNavigator

### Reproduction

https://snack.expo.dev/orGGT4q5r

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/​bottom-tabs
- [ ] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [ ] @react-navigation/​stack
- [X] @react-navigation/​native-stack

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.0.10
| @react-navigation/bottom-tabs          | 6.3.1
| @react-navigation/material-bottom-tabs | 6.2.1
| @react-navigation/stack                | 6.2.1
| @react-navigation/native-stack         | 6.5.0
| react-native-safe-area-context         | 4.1.2
| react-native-screens                   | 3.13.1
| react-native                           | 0.67.3
| node                                   | 16.14.0
| npm or yarn                            | 8.3.1

**Comment by easymonee** [comment]
issue still there with newest packages.

**Comment by raajnadar** [comment]
Try useing the navigation object from the header

`header: ({ navigation }) =>`

**Comment by easymonee** [comment]
thank you @raajnadar! that solved it!

**Comment by tunm1228** [comment]
I will close this issue because it works fine in release.
