### ISSUE TITLE
headerSearchBarOptions is not working with bottom tab navigation

### ISSUE THREAD

**Issue by nucleartux** [react-navigation/react-navigation#10567]
### Current behavior

I configured search bar using such code:
```
 useLayoutEffect(() => {
    if (Platform.OS === "ios") {
      navigation.setOptions({
        headerSearchBarOptions: {
          onChangeText: (event: { nativeEvent: { text: string } }) =>
            options.onChange(event.nativeEvent.text),
          placeholder: "Поиск",
          hintTextColor: "#7B7B7B",
          headerIconColor: "#7B7B7B",
          textColor: "#000000",
          ...options,
        },
      });
    }
  }, [navigation]);
```
Everything was fine.
Now I'm trying to setup TabBar but after that search bar is not displaying anymore.
Simplifed code:
```
const Stack = createNativeStackNavigator<RootStackParamList>();
const Tab = createBottomTabNavigator();

const ChatListScreen = () => {
// useLayoutEffect above
}

const TabsComponent = () => {
  return  <Tab.Navigator>
<Tab.Screen
        name="ChatList"
        component={ChatListScreen}
      />
 </Tab.Navigator>
}

const App = () => {
return (
      <Stack.Navigator
        initialRouteName="Home"
      >
        <Stack.Screen
          name="Home"
          component={TabsComponent}
        />
</Stack.Navigator>
}
```

### Expected behavior

Search should be displaying with or without tab stack.

### Reproduction

https://snack.expo.dev/@nucleartux/frowning-scone

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/​bottom-tabs
- [ ] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [ ] @react-navigation/​stack
- [X] @react-navigation/​native-stack

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.0.10
| @react-navigation/bottom-tabs          | 6.3.1
| @react-navigation/native-stack         | 6.6.1
| react-native-safe-area-context         | 4.2.4
| react-native-screens                   | 3.13.1
| react-native-gesture-handler           | 2.2.0
| react-native-reanimated                | 2.6.0
| react-native                           | 0.68.1
| expo                                   | 45.0.0-beta.9
| node                                   | 16.0
| npm or yarn                            | yarn 3.2.0

**Comment by satya164** [comment]
You need to use `getParent` to set the options on the correct navigator https://reactnavigation.org/docs/navigation-prop/#getparent

**Comment by nucleartux** [comment]
Yes, I know what I can set options for parent navigator but I need search bar inside my screen (inner stack).
As workaround for sure I can use `getParent` but in this case I can't remove search bar on screens where I don't need it.
For some reason when I do `setOptions` with `headerSearchBarOptions: null` nothing happens.

**Comment by arxlan99** [comment]
You can add  these option to any tab pages. I used useFocusEffect hook to update each different page. Otherwise, Navigation header was not updating

`import {
  useNavigation,
  useRoute,
  useFocusEffect,
} from '@react-navigation/native';
import { useCallback, useEffect } from 'react';
import { StyleSheet } from 'react-native';

import EditScreenInfo from '../components/EditScreenInfo';
import { Text, View } from '../components/Themed';

export default function TabOneScreen() {
  const navigation = useNavigation();
  const route = useRoute();

  useFocusEffect(
    useCallback(() => {
      navigation.getParent()?.setOptions({
        headerShown: true,
        headerTitle: 'Tab One',
        headerSearchBarOptions: { placeholder: 'Search Message' },
      });
    }, [])
  );

  return (
    <View style={styles.container}>
      <Text style={styles.title}>Tab One</Text>
      <View
        style={styles.separator}
        lightColor="#eee"
        darkColor="rgba(255,255,255,0.1)"
      />
      <EditScreenInfo path="/screens/TabOneScreen.tsx" />
    </View>
  );
}`

**Comment by jcaviedesc** [comment]
@nucleartux  My solution was nested screen into other stack navigator

```
import { createBottomTabNavigator } from '@react-navigation/bottom-tabs';
import { createNativeStackNavigator } from '@react-navigation/native-stack';

const Tab = createBottomTabNavigator();
const NestedStack = createNativeStackNavigator();

function SearchScreen() {
  return (
    <Stack.Navigator>
      <Stack.Screen
        name="Search"
        component={TabOneScreen}
      />
    </Stack.Navigator>
  );
}

function MyTabs() {
  return (
    <Tab.Navigator>
      <Tab.Screen name="Home" component={HomeScreen} />
      <Tab.Screen name="Search" component={SearchScreen} />
    </Tab.Navigator>
  );
}
```

**Comment by fredrikburmester** [comment]
Hey I still can't get this to work. Is there anyone that solved this?
