### ISSUE TITLE
Drawer throwing exception when chrome debugger is attached

### ISSUE THREAD

**Issue by AmyrAhmady** [react-navigation/react-navigation#10573]
### Current behavior

Right now I'm getting this error below on Android only when chrome debugger is enabled
```
Error: Requiring module "node_modules\@react-navigation\drawer\src\index.tsx", which threw an exception: Invariant Violation: Calling synchronous methods on native modules is not supported in Chrome.

 Consider providing alternative methods to expose this method in debug mode, e.g. by exposing constants ahead-of-time. 
```

### Expected behavior

Expected behavior for it is to simply work, like how it does when chrome debugger is not enabled

### Reproduction
You only need to install react navigation drawe and create a stack of it (obviously requires installing reanimated as well) and enable Chrome Debugger on Android

This repository is made by someone else but has the same effects as well

https://github.com/mjmasn/ReanimatedWithNav6

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/​bottom-tabs
- [X] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [ ] @react-navigation/​stack
- [ ] @react-navigation/​native-stack

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.0.10
| @react-navigation/drawer               | 6.4.1
| @react-navigation/stack                | 6.2.1
| react-native-safe-area-context         | 4.2.5
| react-native-screens                   | 3.13.1
| react-native-gesture-handler           | 2.4.1
| react-native-reanimated                | 2.8.0
| react-native                           | 0.67.4
| node                                   | v14.18.0
| npm or yarn                            | 6.14.15

**Comment by AmyrAhmady** [comment]
There's already an issue for it on reanimated repository
https://github.com/software-mansion/react-native-reanimated/issues/3174
And people there have mentioned incompatibility with react navigation as well
The only reason I opened an issue here too is because there isn't any open issue (or even a closed one) for it here yet 

Also a repro on Expo Snack playground wouldn't work because you need to enable Chrome Debugger in order to reproduce it

All that has to be done is using a Drawer stack and reanimated installed of course, and enable chrome debugger

**Comment by idsingh** [comment]
Here is the fix for it - https://github.com/software-mansion/react-native-reanimated/pull/3227/files

We can apply it using patch-package

**Comment by AmyrAhmady** [comment]
I can confirm this works

**Comment by rickyanwar** [comment]
same here does't work 
 "@babel/preset-typescript": "^7.17.12",
    "@ptomasroos/react-native-multi-slider": "^2.2.2",
    "@react-native-community/clipboard": "^1.5.1",
    "@react-native-community/geolocation": "^2.1.0",
    "@react-navigation/drawer": "^5.12.5",
    "@react-navigation/native": "^5.9.4",
    "@react-navigation/stack": "^5.14.5",
    "@twotalltotems/react-native-otp-input": "^1.3.5",
    "expo": "~45.0.0",
    "expo-app-loading": "~2.0.0",
    "expo-community-flipper": "^45.1.0",
    "expo-linear-gradient": "~11.3.0",
    "expo-location": "~14.2.2",
    "expo-splash-screen": "~0.15.1",
    "expo-status-bar": "~1.3.0",
    "geolib": "^3.3.3",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-native": "0.68.2",
    "react-native-gesture-handler": "~2.2.1",
    "react-native-keyboard-aware-scroll-view": "^0.9.5",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-maps": "0.30.2",
    "react-native-maps-directions": "^1.8.0",
    "react-native-reanimated": "^2.4.1",
    "react-native-swipe-list-view": "^3.2.9",
    "react-redux": "^8.0.2",
    "redux": "^4.2.0",
    "redux-thunk": "^2.4.1"

**Comment by Robiullah2244** [comment]
> Here is the fix for it - https://github.com/software-mansion/react-native-reanimated/pull/3227/files
> 
> We can apply it using patch-package

I just not seeing the error message now. But the app is stuck as before. Is there any solution, please?

**Comment by rickyanwar** [comment]
I was try like this, but same not fix issue,
