### ISSUE TITLE
Scrollview is not working with Stack Navigator in Android

### ISSUE THREAD

**Issue by komelabbbas** [react-navigation/react-navigation#10577]
### Current behavior

`gestureResponseDistance: SCREEN_WIDTH * 0.95`

gesture working fine but the scroll view not scrolling.

### Expected behavior

```
animationEnabled: true,
gestureEnabled: true,
gestureResponseDistance: SCREEN_WIDTH * 0.95,
cardOverlayEnabled: false,
...TransitionPresets.SlideFromRightIOS
```

Scrollview not scroll

### Reproduction

Not available

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/​bottom-tabs
- [ ] @react-navigation/​drawer
- [X] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [X] @react-navigation/​stack
- [X] @react-navigation/​native-stack

### Environment

```
"@react-navigation/bottom-tabs": "^6.0.9",
"@react-navigation/drawer": "^6.1.8",
"@react-navigation/material-top-tabs": "^6.0.6",
"@react-navigation/native": "^6.0.6",
"@react-navigation/native-stack": "^6.2.5",
"@react-navigation/stack": "^6.0.11",
```

**Comment by jeremyfrancis** [comment]
Simple fix. Import ScrollView or FlatList from "react-native-gesture-handler" and works instantly on Android!

**Comment by kaffonso** [comment]
> Simple fix. Import ScrollView or FlatList from "react-native-gesture-handler" and works instantly on Android!

Thank you, worked for me!

**Comment by J-Noel1523** [comment]
Strange but worked if imported from react-native-gesture-handler like how @jeremyfrancis said. Strange because other times (for other sections of the project), it requires me to import from react native.

Anyways this worked for me.

**Comment by Serpentarius13** [comment]
> Simple fix. Import ScrollView or FlatList from "react-native-gesture-handler" and works instantly on Android!

Thanks, saved me :)

**Comment by shubhamprkash** [comment]
> Simple fix. Import ScrollView or FlatList from "react-native-gesture-handler" and works instantly on Android!

Its giving error "nativeviewgesturehandler must be used as a descendant of gesturehandlerrootview" on importing from "react-native-gesture-handler" and no error from "react-native" but importing from "react-native" functionality is not coming

**Comment by denysoleksiienko** [comment]
> Simple fix. Import ScrollView or FlatList from "react-native-gesture-handler" and works instantly on Android!
But it doesn't work if I use refreshControl
