### ISSUE TITLE
Drawer: how to prevent tap to close?(gestureEnabled: false is not working)

### ISSUE THREAD

**Issue by Seb-AS** [react-navigation/react-navigation#10595]
### Current behavior

tapping on the right side of the screen always close the drawer.
swipeEnabled: false it works.

### Expected behavior

if gestureEnabled: false it should not allowed the user to close the drawer

### Reproduction

https://google.com

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/​bottom-tabs
- [X] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [X] @react-navigation/​material-top-tabs
- [X] @react-navigation/​stack
- [X] @react-navigation/​native-stack

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
|   "@react-navigation/native": "^6.0.10",        |
| "@react-navigation/bottom-tabs": "^6.3.1"         |
|  "@react-navigation/drawer": "^6.4.1"             |
| "@react-navigation/material-top-tabs": "^6.2.1"   |
|  "@react-navigation/stack": "^6.2.1"               |
|   "@react-navigation/native-stack": "^6.6.2"        |
|  "react-native-safe-area-context": "^4.2.5"       |
|  "react-native-screens": "^3.13.1"                  |
|    "react-native-gesture-handler": "^2.4.0"          |
|  "react-native-reanimated": "^2.4.1"               |
|  "react-native-tab-view": "^3.1.1"               |
| "react-native": "0.67.2"                          |
| node                                   |
|  yarn                            |

**Comment by Seb-AS** [comment]
Any news?

**Comment by bfricka** [comment]
`gestureEnabled: false` does absolutely nothing, and it's not even in the TypeScript types.

**Comment by Dev-Tester-Test** [comment]
gestureEnabled: false in <Stack.Navigator> screenOptions does not work for me either, neither does swipeEnabled: false

this is using @react-navigation/native and @react-navigation/stack on latest versions (6.0.11, 6.2.2)
I also tried adding it to options under Stack.Screen but this doesn't stop the user from swiping back/forward

**Comment by taylorkline** [comment]
`gestureEnabled: false` also not working for me.
