### ISSUE TITLE
If you do {display:’none’} on Tab.Screen, there is an invisible back button at the top left of the screen. (only android)

### ISSUE THREAD

**Issue by jwoo9928** [react-navigation/react-navigation#10598]
### Current behavior

In react native,
If you do {display:’none’} on Tab.Screen, 
there is an invisible back button at the top left of the screen.

This symptom only appears on Android.

` <Tab.Screen
          name="test"
          component={()=>{return<></>}}
          options={{
            tabBarStyle: { display: "none" },
            headerShown: false,
            tabBarShowLabel: false,
            // tabBarIcon: ({ focused }: any): ReactElement => TabBarIcon(focused, "브라우저"),
          }}
        />`
<img width="406" alt="스크린샷 2022-05-18 오후 3 40 52" src="https://user-images.githubusercontent.com/51700184/168974196-76ea8fe7-84cb-4bb6-90b3-29659b6ba06c.png">

### Expected behavior

I want to remove the button in the picture

### Reproduction

I have attached the code

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/​bottom-tabs
- [ ] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [ ] @react-navigation/​stack
- [ ] @react-navigation/​native-stack

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |6
| @react-navigation/bottom-tabs          |6
| react-native-screens                   |6
| react-native                           | 0.66.2

**Comment by soltia48** [comment]
I set zIndex:-1 to tabBarStyle as a temporary fix.

**Comment by siddharth-kt** [comment]
I also faced it, setting {overflow: "hidden"} to your icon(back button at the top left) should work.

**Comment by nikmercury** [comment]
Still reproducible.
