### ISSUE TITLE
@react-navigation/drawer@6.3.1 and newer!! having StackNavigators as screen components is causing Drawer to stay open when switching tabs!!

### ISSUE THREAD

**Issue by DarioQuintanilla2109** [react-navigation/react-navigation#10608]
### Current behavior

@react-navigation/drawer@6.3.1 and newer!! having StackNavigators as screen components is causing Drawer to stay open when switching tabs. In @react-navigation/drawer@6.3.0  and lower the drawer works as expected.  

https://user-images.githubusercontent.com/50418335/171285459-ac80bce8-e283-4521-aeea-0ba78cb13a7e.MP4

When switching(using gestures) to a drawerItem the default behavior isnt happening. The content of the screen changes but the drawer stays open causing really bad UI.

### Expected behavior

The expected behavior is when you press on a drawerItem it navigates to that screen and closes the drawer.

### Reproduction

https://github.com/DarioQuintanilla2109/drawerTest

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/​bottom-tabs
- [X] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [ ] @react-navigation/​stack
- [ ] @react-navigation/​native-stack

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.2.1
| @react-navigation/bottom-tabs          | 6.3.1
| @react-navigation/drawer               | 6.3.1
| @react-navigation/material-bottom-tabs |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                | 6.2.1
| @react-navigation/native-stack         |
| react-native-safe-area-context         |
| react-native-screens                   |
| react-native-gesture-handler           | 2.2.1
| react-native-reanimated                | 2.8.0
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           |
| expo                                   |
| node                                   |
| npm or yarn                            |

**Comment by SergioAN007** [comment]
Similar problem
When using drawer  prop useLegacyImplementation={false} work normal.
If upgrade RN0.68+ and enable Fabric architecture need use with reanimated v3+. Reanimated 3.0.0-rc.0 does not support useLegacyImplementation={false}

**Comment by bnussman** [comment]
Same thing happens to me. Started when I ran `expo upgrade` to upgrade from Expo SDK `44` ➡️ `45`

**Comment by bnussman** [comment]
Setting `useLegacyImplementation={true}` is working well for me in the mean time

**Comment by SergioAN007** [comment]
> Setting `useLegacyImplementation={true}` is working well for me in the mean time

Yes, it is. But you cannot use this with Fabric

**Comment by doughsay** [comment]
This is happening to me too, and it's inconsistent, I think the video here shows that.  Sometimes it works, sometimes it doesn't, and it feels like the tap handlers are really sensitive; any small amount of movement causes the pan handler to trigger and then ignores the tap.

**Comment by kacperkapusciak** [comment]
Good news! It looks like https://github.com/react-navigation/react-navigation/pull/10647 fixed this issue as well:

## @react-navigation/drawer v6.4.1

https://user-images.githubusercontent.com/39658211/175237513-50efdd85-2973-4791-9204-d7fa50e9a6c7.mov

## The newest main branch

https://user-images.githubusercontent.com/39658211/175237544-fb9379ac-affd-4579-b76d-97dec040e0a1.mov

**Comment by kacperkapusciak** [comment]
Hi @doughsay, @SergioAN007, @bnussman,
Could you upgrade the drawer to the newest version (v6.4.2) and confirm if that resolves the issue?

Cheers

**Comment by SergioAN007** [comment]
> Hi @doughsay, @SergioAN007, @bnussman, Could you upgrade the drawer to the newest version (v6.4.2) and confirm if that resolves the issue?
> 
> Cheers

I confirm. Now it works good. Thank you very much!

**Comment by doughsay** [comment]
> Hi @doughsay, @SergioAN007, @bnussman, Could you upgrade the drawer to the newest version (v6.4.2) and confirm if that resolves the issue?
> 
> Cheers

Yep, it's fixed! Thanks!
