### ISSUE TITLE
Changing background using tabBarStyle is not working on all tabs on 2 out of my 4 tabs change

### ISSUE THREAD

**Issue by karimdakroury** [react-navigation/react-navigation#10623]
### Current behavior

const screenOptions={
     indicatorStyle: {
      width: 0, height: 0, elevation: 0,      
  },
  tabBarActiveTintColor:colorScheme==='dark'?colors.white:colors.dark,
  tabBarLabelStyle:{
    fontWeight:'700'
  },
  tabBarStyle: {
    backgroundColor: colorScheme==='dark'?colors.black:colors.light,
    borderTopColor: colorScheme==='dark'?colors.dark:colors.light,
    elevation: 0,   // for Android
    shadowOffset: {
        width: 0, height: 0 // for iOS
  },
    height:Platform.OS==='ios'&& dimen.width>400?80:Platform.OS==='ios'&& dimen.width<400?60:50,
}  , 
};

  return (
    <Tab.Navigator
      initialRouteName={"Home"}
      {...{screenOptions}}
    >

What is currently happening is that i have 4 tabs and only screenOptions is only applied to 2 of them

### Expected behavior

screenOptions to get applied on all my tabs

### Reproduction

no link

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/​bottom-tabs
- [ ] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [ ] @react-navigation/​stack
- [ ] @react-navigation/​native-stack

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | ^6.0.10
| @react-navigation/bottom-tabs          |^6.3.1
| @react-navigation/drawer               |0
| @react-navigation/material-bottom-tabs |0
| @react-navigation/material-top-tabs    |0
| @react-navigation/stack                |^6.2.1
| @react-navigation/native-stack         |
| react-native-safe-area-context         |3.3.2
| react-native-screens                   |
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           |
| expo                                   |44.0.0
| node                                   |
| npm                             |^8.11.0

**Comment by Coby232** [comment]
Instead of applying the tabBarStyle in the screenOptions prop in the <Tab.Navigator>, apply it to each in <Tab.Screen> element through the options prop. This is because the tabBarStyle in the <Tab.Navigator> is automatically overwritten by the tabBarStyle in <Tab.Screen>: 

For Example;
import { NavigationContainer } from "@react-navigation/native";
import { createBottomTabNavigator } from "@react-navigation/bottom-tabs";

const Tab = createBottomTabNavigator();
const Stack = createStackNavigator();

export default function MainPage() {
  return (
    <NavigationContainer independent={true}>
      <Tab.Navigator
        sceneContainerStyle={{
          backgroundColor: "#F8F8F8",  // It will be overriden
        }}
        screenOptions={{
          tabBarLabelStyle: { color: "black", height: 25 },
          tabBarStyle: {
            height: ScreenHeight * 0.085,
          },
          headerTransparent: true,
          headerTitle: "",
          tabBarHideOnKeyboard: true,
          tabBarShowLabel: false,
        }}>
        <Tab.Screen
          name='Home'
          component={HomeScreen}
          options={({ route }) => ({
            tabBarIcon: ({ focused, color, size }) => {
              if (route?.name === "Home") {
                return focused ? (
                  <View className='flex flex-row items-center bg-slate-200 rounded-full w-20 ml-6'>
                    <Text className='font-semibold px-1'>
                      {route.name}
                    </Text>
                  </View>
                ) : (
                  <HomeTabIcon />
                );
              }
            },
            headerTransparent: true,
            headerTitle: "",
            headerShown: false,
            tabBarStyle: {  //This will override the tabBarStyle above regardless of the amount of styles it contains
              backgroundColor:"#000000",  //This will over
              height: 71,
            },
          })}
          initialParams={handleOpenedDrawer}
        />
        <Tab.Screen
          name='Checkout'
          component={Checkout}
          options={{
            tabBarStyle: {
              display: "none",
            },
            headerTransparent: true,
            headerTitle: "",
            headerShown: false,
          }}
        />
