### ISSUE TITLE
Navigation type in screen options marked as any.

### ISSUE THREAD

**Issue by Speckope** [react-navigation/react-navigation#10634]
### Current behavior

Hello,
when using "navigation" argument in "options" props of "Stack.Screen", navigation type is marked as any. On the other hand, "route" argument is marked correctly.

I recreated the issue in TypeScript playground, along with a workaround.

```ts
import React from 'react'
import { createNativeStackNavigator, NativeStackScreenProps } from '@react-navigation/native-stack';
import {Pressable, View, Text} from 'react-native'

type RootStackParamList = {
  AllPlaces: undefined;
  AddPlace: undefined;
  Map: undefined;
  PlaceDetails: undefined;
};

const RootStack = createNativeStackNavigator<RootStackParamList>();
type AllPlacesProps = NativeStackScreenProps<RootStackParamList, 'AllPlaces'>;


const RootStackNavigator = () => {
  return (
    <RootStack.Navigator initialRouteName='AllPlaces'>
      <RootStack.Screen
        name='AllPlaces'
        component={AllPlacesScreen}
        // navigation is marked as "any" type, while "route" is propertly typed as "RouteProp<RootStackParamList, "AllPlaces">"
        options={({ navigation, route }) => ({
          headerRight: () => (
            <Pressable
              onPress={() => {
                navigation.navigate('AddPlace');
              }}
            >
            <Text> Navigate to AllPlacesScreen</Text>
            </Pressable>
          ),
        })}
      />
    </RootStack.Navigator>
  );
};

export default RootStackNavigator;

const AllPlacesScreen: React.FC = ({}) => {
  return (<View>
    <Text>AllPlaces Screen</Text>
  </View>)
};

// Workaround
const RootStackNavigatorAround = () => {
  return (
    <RootStack.Navigator initialRouteName='AllPlaces'>
      <RootStack.Screen
        name='AllPlaces'
        component={AllPlacesScreen}
        // I think this should be expected type of "navigation" argument, but without the need to type it here.
        options={({ navigation }: {navigation: AllPlacesProps['navigation'] }) => ({
          headerRight: () => (
            <Pressable
              onPress={() => {
                navigation.navigate('AllPlaces');
              }}
            />
          ),
        })}
      />
    </RootStack.Navigator>
  );
};
```

<details><summary><b>Output</b></summary>

```ts
import React from 'react';
import { createNativeStackNavigator } from '@react-navigation/native-stack';
import { Pressable, View, Text } from 'react-native';
const RootStack = createNativeStackNavigator();
const RootStackNavigator = () => {
    return (React.createElement(RootStack.Navigator, { initialRouteName: 'AllPlaces' },
        React.createElement(RootStack.Screen, { name: 'AllPlaces', component: AllPlacesScreen, 
            // navigation is marked as "any" type, while "route" is propertly typed as "RouteProp<RootStackParamList, "AllPlaces">"
            options: ({ navigation, route }) => ({
                headerRight: () => (React.createElement(Pressable, { onPress: () => {
                        navigation.navigate('AddPlace');
                    } },
                    React.createElement(Text, null, " Navigate to AllPlacesScreen"))),
            }) })));
};
export default RootStackNavigator;
const AllPlacesScreen = ({}) => {
    return (React.createElement(View, null,
        React.createElement(Text, null, "AllPlaces Screen")));
};
// Workaround
const RootStackNavigatorAround = () => {
    return (React.createElement(RootStack.Navigator, { initialRouteName: 'AllPlaces' },
        React.createElement(RootStack.Screen, { name: 'AllPlaces', component: AllPlacesScreen, 
            // I think this should be expected type of "navigation" argument, but without the need to type it here.
            options: ({ navigation }) => ({
                headerRight: () => (React.createElement(Pressable, { onPress: () => {
                        navigation.navigate('AllPlaces');
                    } })),
            }) })));
};

```

</details>

<details><summary><b>Compiler Options</b></summary>

```json
{
  "compilerOptions": {
    "strict": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "target": "ES2017",
    "jsx": "react",
    "module": "ESNext",
    "moduleResolution": "node"
  }
}
```

</details>

**Playground Link:** [Provided](https://www.typescriptlang.org/play?ts=4.3.5#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wChRJY4BvONIlGJAOUeADckBlGdAa1btgAc0bQANHFYwO3Xmj5d6SJADsACjjABnOAF842XAQACDDAFpVKIaJkRVAemszOF7fL74A3OXDR4ak0kbW0UACMAGyRJADVgJAB3SQAVJAAPGAMjPEJiGCs2TjJSGABPMCRECAgYHn51FCgUEAAZYA84AF4aUjg4AEFIyPVI9BCALjgAV1UAEyRMYFUkOd9+gbm50fGp2YWllbW+uABZFDA9+cXl1fW4HbQkABEkXmBI7SuD2+O9X1IaAcnQQNTqnm6dAYTGksnqCkEIjEUAAPKDavC+I1mm0OjAAHwACgAlL5ypVBsNHiFNBAdJDYZxMUoiGpaTo0WDMdiWu0PJJ8EMRmMntp8PiAYDgfB0eD+Ii7NBISTuvjev0iDBplBVHBCSd+pyMZ4AHQK5FwZbAGQoSKg6YwlpILqCqkikLig39OBGuUKE0slSqL3euDWEDO13C8ZikPeoH+FaqGBdahC6naQNqPRx-qORxhmxI+y6jpwEBNPirOAoXQAIhQqjKdbg5JicESAAsPlU6zgHUgW2WwFokLBImVWxVq7W4HX7Ux2b7uU1eXjJHX0+7tHX8XXc3A6SXtKnCbRrLY2A5JP2mPpiaq9dQD-1O6gFlAECJOzApiqumq+qhsB3oosEoQRNEL7AQ44EntQ-5qs+IEod6F7FsADgmuhdhIISgpbNS+CktBoZ6DmqGhvipE+mkmRquad4wBAlLRqKWaqCijh0QSNFcXBkFINRlFwMS4gHnoxIUcBjjCaBjiypiZpFoqUBySR-ykKQGSUPABwoNMkQylyniMdAAJAqonRbjGHFTMg6AwCaABiADCyrUJJj7IXAmrarqhIovESRyYaPH4jZopwBxXHhScXHBYk+LEqQmmkPmcAAOrQHwTQQPsUpWcZxryipyIDP28zKg+AHqr5bz+XqXrLqaZlQJaqjWsAtoLiwToupFHqhaBimmhxB7hpGg2xqhCaQEmKZpm6tnKNmB4ZQAkq23aqHw21ltonb5ZEcxwOEVQ6UgGDVm2h6YHOOFXqoLZNMI0wRsmkjhA6HbWkdP0wG+YYqKdzFThS1pwG+RAmgeR6YVZp7nmVJb6FM1CPSWUzTey2gANr4JjCP4AAuvej5ntBb4oB+X7CD+f41YBfECVESA0f0sFEKEp5M3VImhkTWGY3hUYZsR9wC-o0kibJ0FiRJUlxnLoZcaN-DKZezFqScGneEAA)
      

### Expected behavior

I think navigation argument should be annotated properly as, in this example: 
```ts 
navigation: AllPlacesProps['navigation']
```
It may be a desired annotation due to something I don't understand. 

If it's a bug, I would love to contribute.

Thank You for Your time.

### Reproduction

https://www.typescriptlang.org/play?ts=4.3.5#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wChRJY4BvONIlGJAOUeADckBlGdAa1btgAc0bQANHFYwO3Xmj5d6SJADsACjjABnOAF842XAQACDDAFpVKIaJkRVAemszOF7fL74A3OXDR4ak0kbW0UACMAGyRJADVgJAB3SQAVJAAPGAMjPEJiGCs2TjJSGABPMCRECAgYHn51FCgUEAAZYA84AF4aUjg4AEFIyPVI9BCALjgAV1UAEyRMYFUkOd9+gbm50fGp2YWllbW+uABZFDA9+cXl1fW4HbQkABEkXmBI7SuD2+O9X1IaAcnQQNTqnm6dAYTGksnqCkEIjEUAAPKDavC+I1mm0OjAAHwACgAlL5ypVBsNHiFNBAdJDYZxMUoiGpaTo0WDMdiWu0PJJ8EMRmMntp8PiAYDgfB0eD+Ii7NBISTuvjev0iDBplBVHBCSd+pyMZ4AHQK5FwZbAGQoSKg6YwlpILqCqkikLig39OBGuUKE0slSqL3euDWEDO13C8ZikPeoH+FaqGBdahC6naQNqPRx-qORxhmxI+y6jpwEBNPirOAoXQAIhQqjKdbg5JicESAAsPlU6zgHUgW2WwFokLBImVWxVq7W4HX7Ux2b7uU1eXjJHX0+7tHX8XXc3A6SXtKnCbRrLY2A5JP2mPpiaq9dQD-1O6gFlAECJOzApiqumq+qhsB3oosEoQRNEL7AQ44EntQ-5qs+IEod6F7FsADgmuhdhIISgpbNS+CktBoZ6DmqGhvipE+mkmRquad4wBAlLRqKWaqCijh0QSNFcXBkFINRlFwMS4gHnoxIUcBjjCaBjiypiZpFoqUBySR-ykKQGSUPABwoNMkQylyniMdAAJAqonRbjGHFTMg6AwCaABiADCyrUJJj7IXAmrarqhIovESRyYaPH4jZopwBxXHhScXHBYk+LEqQmmkPmcAAOrQHwTQQPsUpWcZxryipyIDP28zKg+AHqr5bz+XqXrLqaZlQJaqjWsAtoLiwToupFHqhaBimmhxB7hpGg2xqhCaQEmKZpm6tnKNmB4ZQAkq23aqHw21ltonb5ZEcxwOEVQ6UgGDVm2h6YHOOFXqoLZNMI0wRsmkjhA6HbWkdP0wG+YYqKdzFThS1pwG+RAmgeR6YVZp7nmVJb6FM1CPSWUzTey2gANr4JjCP4AAuvej5ntBb4oB+X7CD+f41YBfECVESA0f0sFEKEp5M3VImhkTWGY3hUYZsR9wC-o0kibJ0FiRJUlxnLoZcaN-DKZezFqScGneEAA

### Platform

- [ ] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/​bottom-tabs
- [ ] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [ ] @react-navigation/​stack
- [X] @react-navigation/​native-stack

### Environment

- [X] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |6.0.10
| @react-navigation/native-stack         |6.6.2
| react-native-safe-area-context         |4.2.4
| react-native-screens                   |3.11.1
| react-native-gesture-handler           |2.2.1
| react-native-reanimated                |2.8.0
| react-native                           |0.68.2
| expo                                   |45.0.0
| node                                   |16.14.2
| npm or yarn                            |yarn

**Comment by Speckope** [comment]
> Hey! Thanks for opening the issue. The issue doesn't seem to contain a link to a repro (a [snack.expo.dev](https://snack.expo.dev) link, a [www.typescriptlang.org/play](https://www.typescriptlang.org/play) link or link to a GitHub repo under your username).
> 
> Can you provide a [minimal repro](https://stackoverflow.com/help/minimal-reproducible-example) which demonstrates the issue? Please try to keep the repro as small as possible and make sure that we can run it without additional setup.
> 
> A repro will help us debug the issue. The issue will be closed automatically after a while if you don't provide a repro.

Hello github-actions bot. It does, in fact, contain a minimal reproduction.
Reproduction:
https://www.typescriptlang.org/play?ts=4.3.5#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wChRJY4BvONIlGJAOUeADckBlGdAa1btgAc0bQANHFYwO3Xmj5d6SJADsACjjABnOAF842XAQACDDAFpVKIaJkRVAemszOF7fL74A3OXDR4ak0kbW0UACMAGyRJADVgJAB3SQAVJAAPGAMjPEJiGCs2TjJSGABPMCRECAgYHn51FCgUEAAZYA84AF4aUjg4AEFIyPVI9BCALjgAV1UAEyRMYFUkOd9+gbm50fGp2YWllbW+uABZFDA9+cXl1fW4HbQkABEkXmBI7SuD2+O9X1IaAcnQQNTqnm6dAYTGksnqCkEIjEUAAPKDavC+I1mm0OjAAHwACgAlL5ypVBsNHiFNBAdJDYZxMUoiGpaTo0WDMdiWu0PJJ8EMRmMntp8PiAYDgfB0eD+Ii7NBISTuvjev0iDBplBVHBCSd+pyMZ4AHQK5FwZbAGQoSKg6YwlpILqCqkikLig39OBGuUKE0slSqL3euDWEDO13C8ZikPeoH+FaqGBdahC6naQNqPRx-qORxhmxI+y6jpwEBNPirOAoXQAIhQqjKdbg5JicESAAsPlU6zgHUgW2WwFokLBImVWxVq7W4HX7Ux2b7uU1eXjJHX0+7tHX8XXc3A6SXtKnCbRrLY2A5JP2mPpiaq9dQD-1O6gFlAECJOzApiqumq+qhsB3oosEoQRNEL7AQ44EntQ-5qs+IEod6F7FsADgmuhdhIISgpbNS+CktBoZ6DmqGhvipE+mkmRquad4wBAlLRqKWaqCijh0QSNFcXBkFINRlFwMS4gHnoxIUcBjjCaBjiypiZpFoqUBySR-ykKQGSUPABwoNMkQylyniMdAAJAqonRbjGHFTMg6AwCaABiADCyrUJJj7IXAmrarqhIovESRyYaPH4jZopwBxXHhScXHBYk+LEqQmmkPmcAAOrQHwTQQPsUpWcZxryipyIDP28zKg+AHqr5bz+XqXrLqaZlQJaqjWsAtoLiwToupFHqhaBimmhxB7hpGg2xqhCaQEmKZpm6tnKNmB4ZQAkq23aqHw21ltonb5ZEcxwOEVQ6UgGDVm2h6YHOOFXqoLZNMI0wRsmkjhA6HbWkdP0wG+YYqKdzFThS1pwG+RAmgeR6YVZp7nmVJb6FM1CPSWUzTey2gANr4JjCP4AAuvej5ntBb4oB+X7CD+f41YBfECVESA0f0sFEKEp5M3VImhkTWGY3hUYZsR9wC-o0kibJ0FiRJUlxnLoZcaN-DKZezFqScGneEAA

**Comment by cgorski28** [comment]
@Speckope any update on this? I have been facing the same issue. Type-safe navigation not possible because navigator type is not suggesting routes since navigator type is 'any'. Would love to find a fix
