### ISSUE TITLE
Can't listen to tabPress event in custom navigation header

### ISSUE THREAD

**Issue by cjhines** [react-navigation/react-navigation#10637]
### Current behavior

The tabPress event is emitted but the listener does not catch the event.

### Expected behavior

Listener should be trigger on tabPress emit.

### Reproduction

https://snack.expo.dev/@cjhines/custom-header-event-listener

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/​bottom-tabs
- [ ] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [X] @react-navigation/​stack
- [ ] @react-navigation/​native-stack

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.0.10
| @react-navigation/bottom-tabs          | 6.3.1
| @react-navigation/stack                | 6.3.1
| react-native-safe-area-context         | 4.2.5
| react-native-screens                   | 3.13.1
| react-native-gesture-handler           | 2.4.2
| react-native                           | 0.68.2
| node                                   | 18.2.0
| npm or yarn                            | 8.9.0

**Comment by tylercote** [comment]
I am seeing the same issue.

**Comment by arindoneATK** [comment]
same issue here

**Comment by ian** [comment]
I can't get any version of `tabPress` to fire, was this discontinued?

**Comment by satya164** [comment]
Your code emitting the event is incorrect. The event requires the route key of the route in the navigator for the target option but you're passing the name of the route from a different navigator as the key.

See here for example implementation https://reactnavigation.org/docs/bottom-tab-navigator/#tabbar

**Comment by cjhines** [comment]
> Your code emitting the event is incorrect. The event requires the route key of the route in the navigator for the target option but you're passing the name of the route from a different navigator as the target.
> 
> See here for example implementation https://reactnavigation.org/docs/bottom-tab-navigator/#tabbar

This didn't fix it, by the way.

**Comment by satya164** [comment]
> This didn't fix it, by the way. I've never seen this work.

Then, provide a repro that uses the API correctly passing a route key from the tab navigator — but doesn't work.
