### ISSUE TITLE
When I customize tabBar with @react-navigation/material-top-tabs[^6.2.1]   the tabBar cannot scroll

### ISSUE THREAD

**Issue by sxyshirly** [react-navigation/react-navigation#10641]
### Current behavior

<NavigationContainer>
      <Tab.Navigator
        initialRouteName='ImportantNews'
        style={{
          height: 500
        }}
        tabBar={props => <HomepageTarBar {...props} />}
        screenOptions={{
          tabBarScrollEnabled: true,
          tabBarBounces: true,
          tabBarStyle: {
            borderTopColor: '#eee',
          },
        }}
      >
        {
          tabList.map(item => {
            return (
              <Tab.Screen
                key={item.name}
                name={item.name}
                options={{title: xxx, tabBarLabel: xxx}}
                component={item.component}
              />
            )
          })
        }
      </Tab.Navigator>
    </NavigationContainer>

and i customize tabBar follow react-navigation doc like this

const TabNav = () => {
  const HomepageTarBar = ({ state, descriptors, navigation, position }) => {
    return (
      <View style={{ flexDirection: 'row' }}>
        {
          state.routes.map((route, index) => {
            const { options } = descriptors[route.key];
            const isFocused = state.index === index;

            const onPress = () => {
              const event = navigation.emit({
                type: 'tabPress',
                target: route.key,
                canPreventDefault: true,
              });
    
              if (!isFocused && !event.defaultPrevented) {
                // The `merge: true` option makes sure that the params inside the tab screen are preserved
                navigation.navigate({ name: route.name, merge: true });
              }
            }
            return (
              <TouchableWithoutFeedback
                onPress={onPress}
                style={{ flex: 1 }}
              >
                <View style={styles.tabWrap}>
                  <View  style={styles.tabLabelWrap}>
                    <Text>{options.title}</Text>
                    <Text >{options.tabBarLabel}</Text>
                  </View>
                </View>
              </TouchableWithoutFeedback>
            )
          })
        }
      </View>
    )
  }

then i can swipper the screen, but <Tab.Navigator> cannot scroll as well

  

### Expected behavior

Tab.Navigator can scroll

### Reproduction

use the tabBar props in Tab.Navigator

### Platform

- [ ] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/​bottom-tabs
- [ ] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [ ] @react-navigation/​stack
- [ ] @react-navigation/​native-stack

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |
| @react-navigation/bottom-tabs          |
| @react-navigation/drawer               |
| @react-navigation/material-bottom-tabs |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                |
| @react-navigation/native-stack         |
| react-native-safe-area-context         |
| react-native-screens                   |
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           |
| expo                                   |
| node                                   |
| npm or yarn                            |

**Comment by Maddumage** [comment]
I am facing the same issue.
