### ISSUE TITLE
Drawer not working when debugger is on android

### ISSUE THREAD

**Issue by khanh21011999** [react-navigation/react-navigation#10658]
### Current behavior

I'm facing issue about drawer, don't know why but when i enable debug mode,  drawer not working any more:

My navigation structure as below:

- Login
- Drawer
   - Home
   - Setting 
  
My main navigation:

  ```javascript 
<NavigationContainer>
            <Stack.Navigator initialRouteName={RouteName.LOGIN}>
                {token!.length > 0 ? (
                    <>
                        <Stack.Screen
                            options={{ headerShown: false }}
                            name={RouteName.HOME}
                            component={DrawerRoute}
                        />
                        <Stack.Screen
                            options={{ headerShown: false }}
                            name={RouteName.ADD_NOTE}
                            component={AddNote}
                        />
                        <Stack.Screen
                            options={{ headerShown: false }}
                            name={RouteName.EDIT_NOTE}
                            component={EditNote}
                        />
                    </>
                ) : (
                    <Stack.Screen
                        options={{ headerShown: false }}
                        name={RouteName.LOGIN}
                        component={Login}
                    />
                )}
            </Stack.Navigator>
   </NavigationContainer>
```

My drawer route:
```javascript
  <Drawer.Navigator>
            <Drawer.Screen name='HomeDrawer' component={NoteListScreen}/>
   </Drawer.Navigator>
```

My package : 
```
	"@react-navigation/

https://user-images.githubusercontent.com/37074707/175807960-b4c5729b-3618-4b2b-8520-ae933a9a252b.mov

bottom-tabs": "^6.0.9",
	"@react-navigation/drawer": "^6.4.2",
	"@react-navigation/native": "^6.0.6",
	"@react-navigation/native-stack": "^6.2.5",
	"react-native-reanimated": "^2.4.0",
```

Here is video if issue:

Uploading Screen Recording 2022-06-26 at 16.16.09.mov…

### Expected behavior

The drawer show smoothly 

### Reproduction

abc

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/​bottom-tabs
- [X] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [ ] @react-navigation/​stack
- [ ] @react-navigation/​native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |  6.0.6
| @react-navigation/bottom-tabs          |
| @react-navigation/drawer               | 6.4.2
| @react-navigation/material-bottom-tabs |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                | 6.2.5
| @react-navigation/native-stack         |
| react-native-safe-area-context         |
| react-native-screens                   |
| react-native-gesture-handler           |
| react-native-reanimated                | 2.4.0
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           |
| expo                                   |
| node                                   |
| npm or yarn                            |

**Comment by jees47** [comment]
> ### Current behavior
> I'm facing issue about drawer, don't know why but when i enable debug mode, drawer not working any more:
> 
> My navigation structure as below:
> 
> * Login
> * Drawer
>   
>   * Home
>   * Setting
> 
> My main navigation:
> 
> ```js
> <NavigationContainer>
>           <Stack.Navigator initialRouteName={RouteName.LOGIN}>
>               {token!.length > 0 ? (
>                   <>
>                       <Stack.Screen
>                           options={{ headerShown: false }}
>                           name={RouteName.HOME}
>                           component={DrawerRoute}
>                       />
>                       <Stack.Screen
>                           options={{ headerShown: false }}
>                           name={RouteName.ADD_NOTE}
>                           component={AddNote}
>                       />
>                       <Stack.Screen
>                           options={{ headerShown: false }}
>                           name={RouteName.EDIT_NOTE}
>                           component={EditNote}
>                       />
>                   </>
>               ) : (
>                   <Stack.Screen
>                       options={{ headerShown: false }}
>                       name={RouteName.LOGIN}
>                       component={Login}
>                   />
>               )}
>           </Stack.Navigator>
>  </NavigationContainer>
> ```
> 
> My drawer route:
> 
> ```js
>   <Drawer.Navigator>
>             <Drawer.Screen name='HomeDrawer' component={NoteListScreen}/>
>    </Drawer.Navigator>
> ```
> 
> My package :
> 
> ```
> 	"@react-navigation/
> 
> https://user-images.githubusercontent.com/37074707/175807960-b4c5729b-3618-4b2b-8520-ae933a9a252b.mov
> 
> bottom-tabs": "^6.0.9",
> 	"@react-navigation/drawer": "^6.4.2",
> 	"@react-navigation/native": "^6.0.6",
> 	"@react-navigation/native-stack": "^6.2.5",
> 	"react-native-reanimated": "^2.4.0",
> ```
> 
> Here is video if issue:
> 
> Uploading Screen Recording 2022-06-26 at 16.16.09.mov…
> 
> ### Expected behavior
> The drawer show smoothly
> 
> ### Reproduction
> abc
> 
> ### Platform
> * [x]  Android
> * [ ]  iOS
> * [ ]  Web
> * [ ]  Windows
> * [ ]  MacOS
> 
> ### Packages
> * [ ]  @react-navigation/​bottom-tabs
> * [x]  @react-navigation/​drawer
> * [ ]  @react-navigation/​material-bottom-tabs
> * [ ]  @react-navigation/​material-top-tabs
> * [ ]  @react-navigation/​stack
> * [ ]  @react-navigation/​native-stack
> 
> ### Environment
> package	version
> @react-navigation/native	6.0.6
> @react-navigation/bottom-tabs	
> @react-navigation/drawer	6.4.2
> @react-navigation/material-bottom-tabs	
> @react-navigation/material-top-tabs	
> @react-navigation/stack	6.2.5
> @react-navigation/native-stack	
> react-native-safe-area-context	
> react-native-screens	
> react-native-gesture-handler	
> react-native-reanimated	2.4.0
> react-native-tab-view	
> react-native-pager-view	
> react-native	
> expo	
> node	
> npm or yarn

same issue

**Comment by martinezguillaume** [comment]
Same issue here after I updated to react-native 0.69

```
		"react": "18.0.0",
		"react-native": "0.69.0",
		"@react-navigation/bottom-tabs": "^6.0.9",
		"@react-navigation/compat": "^5.3.20",
		"@react-navigation/drawer": "^6.1.8",
		"@react-navigation/elements": "^1.2.1",
		"@react-navigation/native": "^6.0.6",
		"@react-navigation/native-stack": "^6.2.5",
		"@react-navigation/stack": "^6.0.11",
```
