### ISSUE TITLE
[iOS] Support prefersHomeIndicatorAutoHidden

### ISSUE THREAD

**Issue by NikitaGura** [react-navigation/react-navigation#10651]
### Current behavior

How could we change behaviour of home indicator for iOS ?

### Expected behavior

https://www.npmjs.com/package/react-native-home-indicator - does not help. 

### Reproduction

https://www.npmjs.com/package/react-native-home-indicator

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/​bottom-tabs
- [X] @react-navigation/​drawer
- [X] @react-navigation/​material-bottom-tabs
- [X] @react-navigation/​material-top-tabs
- [X] @react-navigation/​stack
- [X] @react-navigation/​native-stack

### Environment

| @react-navigation/native               |
| @react-navigation/bottom-tabs          |
| @react-navigation/drawer               |
| @react-navigation/material-bottom-tabs |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                |
| @react-navigation/native-stack         |
| react-native-safe-area-context         |
| react-native-screens                   |
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           |
| expo                                   |
| node                                   |
| npm or yarn                            |

**Comment by hirbod** [comment]
Was merged yesterday.

**Comment by kacperkapusciak** [comment]
Hi @NikitaGura :wave:

In the newest version of @react-navigation/native-stack there's a new prop that does exactly this:

https://reactnavigation.org/docs/native-stack-navigator#autohidehomeindicator

Cheers
