### ISSUE TITLE
I can't install the react native screens and gesturehandler dependencies, it's returning a TASK error - "React-native-screens:compileDebugJavaC

### ISSUE THREAD

**Issue by pedrinho132** [react-navigation/react-navigation#10660]
### Current behavior

I can't install the react native screens and gesturehandler dependencies, it's returning a TASK error - "react-native-screens:compileDebugJavaC, 

I believe it has something to do with the 0.69 update, I downgraded it but still no success

### Expected behavior

MY >>>>>>>>>>>>>>> android/build.gradlew <<<<<<<<<<<<<<<<<<<<<<<<<, 

import org.apache.tools.ant.taskdefs.condition.Os

// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "33.0.0"
        minSdkVersion = 21
        compileSdkVersion = 32
        targetSdkVersion = 32
        kotlinVersion =  " 1.6.21 "

        if (System.properties['os.arch'] == "aarch64") {
            // For M1 Users we need to use the NDK 24 which added support for aarch64
            ndkVersion = "24.0.8215888"
        } else {
            // Otherwise we default to the side-by-side NDK version from AGP.
            ndkVersion = "21.4.7075529"
        }
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:7.0.4")
        classpath("com.facebook.react:react-native-gradle-plugin")
        classpath("de.undercouch:gradle-download-task:5.0.1")
        classpath 'com.google.gms:google-services:4.3.12'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

**Comment by nibblesnbits** [comment]
There's an open issue for this I've commented on today: https://github.com/software-mansion/react-native-screens/issues/1449#issuecomment-1169550524
Hopefully it will get more attention soon.

**Comment by kacperkapusciak** [comment]
Looks like it was fixed in https://github.com/software-mansion/react-native-screens/issues/1449
