### ISSUE TITLE
Web adding a lot of non-sense div elements

### ISSUE THREAD

**Issue by ninacoder-info** [react-navigation/react-navigation#10675]
### Current behavior

<img width="1239" alt="Screenshot 2022-07-02 at 13 45 08" src="https://user-images.githubusercontent.com/63708869/176990015-e5e87c48-ba93-47cc-8c56-48b3a3389410.png">

### Expected behavior

<img width="418" alt="Screenshot 2022-07-02 at 13 48 53" src="https://user-images.githubusercontent.com/63708869/176990027-370ecfbf-d32d-442a-aac7-161c10ba76b0.png">

### Reproduction

https://snack.expo.dev/

### Platform

- [ ] Android
- [ ] iOS
- [X] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/​bottom-tabs
- [ ] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [X] @react-navigation/​stack
- [ ] @react-navigation/​native-stack

### Environment

Hi, I'm using navigation for web, all good, but one issue is when creating navigator it's added many div elements which will break my design on some browser such as Firefox... Please take a look at the attachment you can see a lot of elements with className "css-view-1dbjc4n" was created by nagivation. Is there any way to prevent that?

<img width="1239" alt="Screenshot 2022-07-02 at 13 45 08" src="https://user-images.githubusercontent.com/63708869/176989983-6bdcc6db-252d-472b-ae5f-c4559479695f.png">

**Comment by hirbod** [comment]
That's called "div soup" and it's most likely not the fault by react navigation, but react native web. When you have nested navigators, drawers etc, it will end up like this, because RNW needs to create a div basically for every wrapping element and even absolute positioned views etc.
