### ISSUE TITLE
so what should we do to have headerBackTitle? on Android

### ISSUE THREAD

**Issue by sureface** [react-navigation/react-navigation#10697]
so what should we do to have headerBackTitle? on Android

_Originally posted by @golestanirad in https://github.com/react-navigation/react-navigation/issues/1871#issuecomment-365411918_

**Comment by kacperkapusciak** [comment]
Hi @sureface,

There's just no such thing on Android as a title on the back button. It's an iOS feature that just doesn't exist on Android. 

On the other hand, if you need something custom you could use `headerLeft` prop in `native-stack` to set any component you want as a back button.

Cheers
