### ISSUE TITLE
resetting the screen  is showing the previous stack for a second 

### ISSUE THREAD

**Issue by vkmulloly** [react-navigation/react-navigation#10699]
### Current behavior

  **Issue** 
i am developing an application . in that  from login screen I am navigating to ActivationStack screen (stack with bottom navigation)
    NavigationService.reset("ActivationStack")

 now I can see 2 tabs at bottom home and account 
   from home screen i am navigating to profile screen
   NavigationService.navigate("Profile")
from profile screen when I click on logout 

 it is navigating to login screen 
 NavigationService.reset("LoginStack")

 **But in between of navigation from profile screen to log in screen for a fraction of a second i can see 
 ActivationStack  ie bottom tab screen even though i am doing resetting** 

 This ie happening after the upgrade of react navigation from 4 to 6

 Kindly help me to resolve the issue 

Note : using react native .68 
    "@react-navigation/bottom-tabs": "6.3.2",
    "@react-navigation/native": "^6.0.10",
    "@react-navigation/native-stack": "^6.6.2",

Below is my code and attaching the video of current and expected 

import Splash from "../Splash"
import Profile from "../Profile"

<NavigationContainer >
  <Stack.Navigator initialRouteName="Splash" screenOptions={{ presentation: "containedTransparentModal", headerShown: false }}>
    <Stack.Screen name="Splash" component={Splash} />
    <Stack.Screen name="LoginStack" component={LoginStack} />
    <Stack.Screen name="ActivationStack" component={ActivationBottomTab} />
    <Stack.Screen name="Profile" component={Profile} />
  </Stack.Navigator>
</NavigationContainer>

const LoginStack = () => {
  return (
    <Stack.Navigator
      screenOptions={{
        ...navigationOptions,
        headerShown: false,
        headerBackTitleVisible: false,
        presentation: "transparentModal"
      }}
      initialRouteName="Login">
      <Stack.Screen name="Login" component={Login} />
   </Stack.Navigator>
)}

const ActivationBottomTab = () => {
    return (
      <Tabs.Navigator screenOptions={({ route }) => tabBarDefaultNavOptions(route)}>
        <Tabs.Screen name="Home" component={Home} options={{ headerShown: false }} />
        <Tabs.Screen name="Account" component={Account} options={tabHeaderOptions(true, "Account")} />
      </Tabs.Navigator>
    );
  };

 **NavigationService.js**
  export function reset(routeName: string, params?: any) {
    navigationRef.dispatch(
    CommonActions.reset({
      index: 0,
      routes: [
        {
          name: routeName,
          params
        },
      ],
    })
  );
  }

  export function navigate(name: never, params: never) {
      navigationRef.navigate(name, params);
}

 i am attaching the video of issue 
 and expected behavior
Kindly help me on this

https://user-images.githubusercontent.com/30654527/179498849-fd979756-4a1b-455d-9e4c-a1de6a298e7d.mp4

### Expected behavior

https://user-images.githubusercontent.com/30654527/179498874-151dd821-8fa0-49e8-878c-55c7f10f470d.mp4

### Reproduction

https://user-images.githubusercontent.com/30654527/179498849-fd979756-4a1b-455d-9e4c-a1de6a298e7d.mp4

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/​bottom-tabs
- [ ] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [X] @react-navigation/​stack
- [X] @react-navigation/​native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |
| @react-navigation/bottom-tabs          |
| @react-navigation/drawer               |
| @react-navigation/stack                |
| @react-navigation/native-stack         |
| react-native-safe-area-context         |
| react-native-screens                   |
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           |
| node                                   |
| npm or yarn                            |

**Comment by DimitrisKokkonas** [comment]
@vkmulloly I am facing something  similar. Have you found out any solution on this
