### ISSUE TITLE
Customise border bottom

### ISSUE THREAD

**Issue by teckbeng-payboy** [react-navigation/react-navigation#10709]
### Current behavior

BorderColor does not work on the header of native stack. How can I change the color of the bottom border
<img width="372" alt="Screenshot 2022-07-20 at 10 27 18 PM" src="https://user-images.githubusercontent.com/85466071/180042134-c045fb31-0ac9-4a21-823f-4d5d9c707858.png">
k

### Expected behavior

Able to set the color

### Reproduction

-

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/​bottom-tabs
- [ ] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [ ] @react-navigation/​stack
- [X] @react-navigation/​native-stack

### Environment

"@react-navigation/bottom-tabs": "^6.3.2",
    "@react-navigation/native": "^6.0.11",
    "@react-navigation/native-stack": "^6.7.0",
"react": "18.0.0",
    "react-native": "0.69.1",

**Comment by alamothe** [comment]
Looks like it's not possible with native stack.

**Comment by MiryangJung** [comment]
Maybe this will help.

https://github.com/react-navigation/react-navigation/blob/main/example/src/Screens/StackHeaderCustomization.tsx#L164
