### ISSUE TITLE
NavigationContainer onStateChange not called

### ISSUE THREAD

**Issue by Willham12** [react-navigation/react-navigation#10711]
### Current behavior

```js
<NavigationContainer					
linking={linking}					
onStateChange={async () => {
/// not called with deeplink
}}>
...
</NavigationContainer>
```

### Expected behavior

onStateChange called if deep link provided

### Reproduction

https://snack.expo.dev/BKpQjP9u8

### Platform

- [x] Android
- [x] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/​bottom-tabs
- [ ] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [ ] @react-navigation/​stack
- [ ] @react-navigation/​native-stack

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |6.0.11
| @react-navigation/native-stack         |6.7.0
| react-native-safe-area-context         |4.3.1
| react-native-reanimated               |2.9.1 
| react-native                           |0.67.3
| node                                  | 16
| npm or yarn                       | yarn

**Comment by uztbt** [comment]
NavigationContainer's `onStateChange()` is never called for web, also.

**Comment by satya164** [comment]
There's no state change when app opens with a deep link. The state is used as initial state. If you need to get the state on initial launch then call `navigation.getRootState()` in `onReady`
