### ISSUE TITLE
Windows APP: folly::toJson: JSON object value was a NaN when serializing value at "arguments"->2->2->"layout"->"height"

### ISSUE THREAD

**Issue by taduyde** [react-navigation/react-navigation#10719]
### Current behavior

Windows APP: folly::toJson: JSON object value was a NaN when serializing value at "arguments"->2->2->"layout"->"height"
![image](https://user-images.githubusercontent.com/8236997/181426936-cb01e3db-ecc3-4064-b1a1-2c1f3b58eaae.png)

### Expected behavior

not appear that error 

### Reproduction

https://github.com/react-navigation/react-navigation

### Platform

- [ ] Android
- [ ] iOS
- [ ] Web
- [X] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/​bottom-tabs
- [ ] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [X] @react-navigation/​stack
- [X] @react-navigation/​native-stack

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |
| @react-navigation/bottom-tabs          |
| @react-navigation/drawer               |
| @react-navigation/material-bottom-tabs |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                |
| @react-navigation/native-stack         |
| react-native-safe-area-context         |
| react-native-screens                   |
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           |
| expo                                   |
| node                                   |
| npm or yarn                            |

**Comment by MaxPMagee** [comment]
We have seen this too, but we think it may be an issue with react-native-reanimated and debugging.
https://github.com/software-mansion/react-native-reanimated/issues/2914

**Comment by cjhines** [comment]
I'm also experiencing this also

```
    "@react-native-async-storage/async-storage": "^1.17.5",
    "@react-navigation/bottom-tabs": "^6.3.2",
    "@react-navigation/native": "^6.0.10",
    "@react-navigation/stack": "^6.2.1",
    "@reduxjs/toolkit": "^1.8.2",
    "react": "17.0.2",
    "react-intl": "^6.0.5",
    "react-native": "0.68.2",
    "react-native-gesture-handler": "^2.4.2",
    "react-native-safe-area-context": "^4.2.5",
    "react-native-screens": "^3.13.1",
    "react-native-windows": "0.68.9",
    "react-redux": "^8.0.2",
```

**Comment by tomekzaw** [comment]
@cjhines Which version of `react-native-reanimated` are you using? You can check this with `npm ls react-native-reanimated`.

**Comment by cjhines** [comment]
@tomekzaw `react-native-reanimated@2.9.1`

**Comment by tomekzaw** [comment]
@cjhines Hmm... We fixed this issue in 2.5.0 so it should work fine on 2.9.1.

Could you please submit an issue in Reanimated repo and prepare a minimal repro?

**Comment by cjhines** [comment]
@tomekzaw This is on Windows, so perhaps I'm missing something obvious that's platform-compatibility specific.

If not, I'll make an issue on the Reanimated repo.

**Comment by tomekzaw** [comment]
@cjhines The thing is that Reanimated does not support Windows (natively). So the `folly::toJSON` call that causes problems here certainly does not originate from Reanimated.

**Comment by cjhines** [comment]
@tomekzaw Thanks for taking the time to help me rule that out. I noticed that Reanimated issue was Android-only so didn't want to pollute the discussion there with Windows stuff.

I guess this is indeed a `react-navigation` issue, but this issue seems like a dead end.

**Comment by tomekzaw** [comment]
@cjhines If you are able to successfully recreate the error, do you have some kind of stack trace so we can narrow the issue to a specific library? I'm happy to help with fixing this in some other library as well.

**Comment by cjhines** [comment]
@tomekzaw That's very generous of you, thank you!

When the error occurs there is no output in the React Native debugger console, sadly.

When running the app through Visual Studio, I get the following in the debug output (I removed hundreds of `UnimplementedProperty` duplicate lines):

```
[UnimplementedProperty] ViewManager = RCTScrollView elementClass = Windows.UI.Xaml.Controls.ScrollViewer propertyName = horizontal value = false
[UnimplementedProperty] ViewManager = RCTScrollView elementClass = Windows.UI.Xaml.Controls.ScrollViewer propertyName = showsVerticalScrollIndicator value = false
[UnimplementedProperty] ViewManager = RCTScrollView elementClass = Windows.UI.Xaml.Controls.ScrollViewer propertyName = snapToEnd value = true
[UnimplementedProperty] ViewManager = RCTScrollView elementClass = Windows.UI.Xaml.Controls.ScrollViewer propertyName = snapToStart value = true
[UnimplementedProperty] ViewManager = RCTVirtualText elementClass = Windows.UI.Xaml.Documents.Span propertyName = lineHeight value = 20
[UnimplementedProperty] ViewManager = RCTText elementClass = Windows.UI.Xaml.Controls.TextBlock propertyName = isHighlighted value = false
Exception thrown at 0x00007FF90662474C in myapp.exe: Microsoft C++ exception: folly::json::print_error at memory location 0x000000DEE0BFC8C8.
```

**Comment by tomekzaw** [comment]
@cjhines Is there a possibility to build the app in debug mode and attach the debugger so we can see the full stack trace instead of only `C++ exception: folly::json::print_error at memory location 0x000000DEE0BFC8C8`?

**Comment by cjhines** [comment]
@tomekzaw I have the debugger attached, but frustrating still getting no such error.

<img width="500" alt="1" src="https://user-images.githubusercontent.com/16542421/185140860-3807f91f-d10c-4486-8d4f-c68c602c5bea.png">

Only the red box error shown.
<img width="607" alt="2" src="https://user-images.githubusercontent.com/16542421/185140911-39a12185-4584-4a62-84fb-0b7b3847f28f.png">

I even tried [running the script](https://microsoft.github.io/react-native-windows/docs/native-code#debugging-crashes-and-reporting-issues) to access the crash log, but it's not finding finding the dump file (I guess because it's not hard crashing).

```
Please reproduce your crash scenario. Press Enter when done:
Analyzing crash dump
Failed to analyze the crash dump. Exiting

Microsoft (R) Windows Debugger Version 10.0.22000.832 AMD64
Copyright (c) Microsoft Corporation. All rights reserved.

Loading Dump File [C:\temp\-c]
Could not open dump file [-c], Win32 error 0n2
    "The system cannot find the file specified."
Debuggee initialization failed, Win32 error 0n2
The system cannot find the file specified.
```

**Comment by tomekzaw** [comment]
Hey, React Native Debugger is for debugging JS code. You should use a native code debugger from Visual Studio: https://docs.microsoft.com/en-us/visualstudio/debugger/what-is-debugging?view=vs-2022

**Comment by cjhines** [comment]
@tomekzaw Unfortunately this is the extent of the Visual Studio debugger output. No stack trace.

```
[UnimplementedProperty] ViewManager = RCTText elementClass = Windows.UI.Xaml.Controls.TextBlock propertyName = isHighlighted value = false
Exception thrown at 0x00007FF90662474C in myapp.exe: Microsoft C++ exception: folly::json::print_error at memory location 0x000000DEE0BFC8C8.
```

**Comment by tomekzaw** [comment]
@cjhines Can you find file `folly/json.cpp` and add a breakpoint [in this line](https://github.com/facebook/folly/blob/main/folly/json.cpp#L1066)?

**Comment by cjhines** [comment]
@tomekzaw Here's the last six values of the breakpoint's serialized value before the crash:

```shell
"{\"id\":17465,\"method\":\"callFunctionReturnFlushedQueue\",\"arguments\":[\"RCTEventEmitter\",\"receiveEvent\",[9625,\"topLoadStart\",{\"target\":9625,\"source\":{\"uri\":\"http://localhost:8081/assets/src/atoms/AppIconSmall/...
"{\"id\":17466,\"method\":\"callFunctionReturnFlushedQueue\",\"arguments\":[\"RCTEventEmitter\",\"receiveEvent\",[9629,\"topLoadStart\",{\"target\":9629,\"source\":{\"uri\":\"http://localhost:8081/assets/src/atoms/AppIcon/...
"{\"id\":17473,\"method\":\"callFunctionReturnFlushedQueue\",\"arguments\":[\"RCTEventEmitter\",\"receiveEvent\",[8669,\"topLayout\",{\"layout\":{\"height\":0,\"width\":0,\"x\":0,\"y\":0},\"target\":8669}]]}"
"{\"id\":17474,\"method\":\"callFunctionReturnFlushedQueue\",\"arguments\":[\"RCTEventEmitter\",\"receiveEvent\",[8775,\"topLayout\",{\"layout\":{\"height\":0,\"width\":0,\"x\":0,\"y\":0},\"target\":8775}]]}"
"{\"id\":17475,\"method\":\"callFunctionReturnFlushedQueue\",\"arguments\":[\"RCTEventEmitter\",\"receiveEvent\",[8819,\"topLayout\",{\"layout\":{\"height\":0,\"width\":0,\"x\":0,\"y\":0},\"target\":8819}]]}"
"{\"id\":17476,\"method\":\"callFunctionReturnFlushedQueue\",\"arguments\":[\"RCTEventEmitter\",\"receiveEvent\",[8889,\"topLayout\",{\"layout\":{\"height\":44,\"width\":1000,\"x\":0,\"y\":0},\"target\":8889}]]}"
```

**Comment by tero-paananen** [comment]
How about if `RNScreensModule : Windows.UI.Xaml.Controls.TextBox` has height as auto? That cannot be converted into double. How about testing for example ` Windows.UI.Xaml.Controls.UserControl`

**Comment by KshamaShrey** [comment]
@taduyde I am also seeing this error. How did you resolve it?

**Comment by Manjunatha123** [comment]
We are also facing the same issue in windows platform. Any help or suggestion would be appreciated. Thanks

**Comment by cjhines** [comment]
Interestingly this doesn't happen to me on RNW 0.68.9.

Unfortunately I have to upgrade to 0.68.11 for another [navigation related bug](https://github.com/microsoft/react-native-windows/issues/9977).

**Comment by Manjunatha123** [comment]
Hi,
Is it possible to let us know the react-navigation version and peerDependencies versions you have for RNW 0.68.9?

**Comment by Manjunatha123** [comment]
I checked with RNW 0.68.9 and I still see the same error.
Error in app - folly::toJson: JSON object value was a NaN when serializing value at "arguments"->2->2->"layout"->"height"
Error in Debugger UI console - Invariant Violation: requireNativeComponent: "RNSScreenStackHeaderSubview" was not found in the UIManager.

Please find the details of the dependencies.
```
    "@react-navigation/native": "^6.0.12",
    "@react-navigation/native-stack": "^6.8.0",
    "react-native-safe-area-context": "^4.3.3",
    "react-native-screens": "^3.16.0",
    "react-native-windows": "0.68.9",
    "react-navigation": "^4.4.4",
    "react-native": "0.68.3",
```

Please find the output of the command `npx react-native info`
```

npx react-native info
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz
    Memory: 5.85 GB / 16.00 GB
  Binaries:
    Node: 16.14.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.16.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.14393.0, 10.0.16299.0, 10.0.17763.0, 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.11.32802.440 (Visual Studio Enterprise 2019), 15.9.28307.2019 (Visual Studio Enterprise 2017)
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.68.3 => 0.68.3
    react-native-windows: 0.68.9 => 0.68.9
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by cjhines** [comment]
@Manjunatha123 

With the following setup we do not get the crash, but we do get [this bug](https://github.com/microsoft/react-native-windows/issues/9977).

I'm aware we're missing gesture handler and should not have reanimated on Windows, but neither case is ideal in this situation.

```

    "@react-native-async-storage/async-storage": "^1.17.5",
    "@react-navigation/bottom-tabs": "^6.3.2",
    "@react-navigation/native": "^6.0.10",
    "@react-navigation/stack": "^6.2.1",
    "@reduxjs/toolkit": "^1.8.2",
    "react": "17.0.2",
    "react-native": "0.68.2",
    "react-native-reanimated": "^2.9.1",
    "react-native-safe-area-context": "^4.2.5",
    "react-native-screens": "^3.13.1",
    "react-native-windows": "0.68.9",
    "react-redux": "^8.0.2",
    "redux-persist": "^6.0.0"
````

**Comment by Manjunatha123** [comment]
@cjhines Same is the case with me! :(
After updating `package.json` and replacing `@react-navigation/native-stack` with `@react-navigation/stack` I am not seeing the crash (folly issue). But as you have already mentioned I am seeing the header issue.

Did you happen to  get any resolution to the issue with the header?
Thanks

**Comment by cjhines** [comment]
@Manjunatha123 After updating our RNW version to 0.69.6 we're no longer either of the two problems. Does this work for you?

```
    "@react-native-async-storage/async-storage": "1.17.10",
    "@react-navigation/bottom-tabs": "6.3.3",
    "@react-navigation/native": "6.0.12",
    "@react-navigation/stack": "6.2.3",
    "react": "18.0.0",
    "react-native": "0.69.5",
    "react-native-config": "^1.4.6",
    "react-native-gesture-handler": "^2.4.2",
    "react-native-safe-area-context": "4.2.5",
    "react-native-screens": "3.17.0",
    "react-native-windows": "0.69.6",
```

**Comment by Manjunatha123** [comment]
@cjhines 
Will try with both RNW 0.69.6 as well as 0.68.15 and will update here.
Thanks.

**Comment by Manjunatha123** [comment]
With RNW 0.69.6 Unable to build the solution in VS 2019 with the following error
```
Could not write lines to file "build\x64\Debug\Microsoft.ReactNative.Managed.CodeGen\netcoreapp3.1\win-x64\Microsoft.ReactNative.Managed.CodeGen.GeneratedMSBuildEditorConfig.editorconfig". Could not find a part of the path 'C:\Users\user\AppName\WinRebuild\AppName\node_modules\react-native-windows\Microsoft.ReactNative.Managed.CodeGen\build\x64\Debug\Microsoft.ReactNative.Managed.CodeGen\netcoreapp3.1\win-x64\Microsoft.ReactNative.Managed.CodeGen.GeneratedMSBuildEditorConfig.editorconfig'.				
```
Also metro bundler fails with the error 
```
None of these files exist:
  * debugger-ui\debuggerWorker.aca173c4(.native|.native.js|.js|.native.json|.json|.native.ts|.ts|.native.tsx|.tsx)
  * debugger-ui\debuggerWorker.aca173c4\index(.native|.native.js|.js|.native.json|.json|.native.ts|.ts|.native.tsx|.tsx)
    at ModuleResolver.resolveDependency (C:\Users\user\Appname\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:136:15)
    at DependencyGraph.resolveDependency (C:\Users\user\Appname\node_modules\metro\src\node-haste\DependencyGraph.js:231:43)
    at C:\Users\user\Appname\node_modules\metro\src\lib\transformHelpers.js:129:24
    at Server._resolveRelativePath (C:\Users\user\Appname\node_modules\metro\src\Server.js:1137:12)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Server._explodedSourceMapForURL (C:\Users\user\Appname\node_modules\metro\src\Server.js:1088:35)
    at async Promise.all (index 1)
    at async Server._symbolicate (C:\Users\user\Appname\node_modules\metro\src\Server.js:1039:26)
    at async Server._processRequest (C:\Users\user\Appname\node_modules\metro\src\Server.js:443:7)
```

With RNW 0.68.15 Even while navigating in App we get
```
folly::toJson: JSON object value was a NaN when serializing value at "arguments"->2->2->"layout"->"height"
```

In Debugger- UI Console we get error 
```
VirtualizedLists should never be nested inside plain ScrollViews with the same orientation because it can break windowing and other functionality - use another VirtualizedList-backed container instead. 
    at VirtualizedList (http://localhost:8081/index.bundle?platform=windows&dev=true&hot=false&inlineSourceMap=true:67972:36)
    at FlatList (http://localhost:8081/index.bundle?platform=windows&dev=true&hot=false&inlineSourceMap=true:67409:36)
    at SwipeListView (http://localhost:8081/index.bundle?platform=windows&dev=true&hot=false&inlineSourceMap=true:209220:36)
    at RCTView
    at View
    at RCTView
    at View
    at RCTView
    at View
    at RCTScrollContentView
    at RCTScrollView
    at ScrollView (http://localhost:8081/index.bundle?platform=windows&dev=true&hot=false&inlineSourceMap=true:69735:36)
    at ScrollView
    at RCTView
    at View
    at Component (http://localhost:8081/index.bundle?platform=windows&dev=true&hot=false&inlineSourceMap=true:197612:36)
    at StaticContainer (http://localhost:8081/index.bundle?platform=windows&dev=true&hot=false&inlineSourceMap=true:287724:18)
    at EnsureSingleNavigator (http://localhost:8081/index.bundle?platform=windows&dev=true&hot=false&inlineSourceMap=true:283084:25)
    at SceneView (http://localhost:8081/index.bundle?platform=windows&dev=true&hot=false&inlineSourceMap=true:287608:23)
    at RCTView
    at View
    at RCTView
    at View
    at RCTView
    at View
    at CardSheet (http://localhost:8081/index.bundle?platform=windows&dev=true&hot=false&inlineSourceMap=true:295106:24)
    at RCTView
    at View
    at AnimatedComponent (http://localhost:8081/index.bundle?platform=windows&dev=true&hot=false&inlineSourceMap=true:74345:38)
    at AnimatedComponentWrapper
    at Dummy (http://localhost:8081/index.bundle?platform=windows&dev=true&hot=false&inlineSourceMap=true:295164:25)
    at RCTView
    at View
    at AnimatedComponent (http://localhost:8081/index.bundle?platform=windows&dev=true&hot=false&inlineSourceMap=true:74345:38)
    at AnimatedComponentWrapper
    at RCTView
    at View
    at Card (http://localhost:8081/index.bundle?platform=windows&dev=true&hot=false&inlineSourceMap=true:294467:36)
    at CardContainer (http://localhost:8081/index.bundle?platform=windows&dev=true&hot=false&inlineSourceMap=true:294024:35)
    at RCTView
    at View
    at AnimatedComponent (http://localhost:8081/index.bundle?platform=windows&dev=true&hot=false&inlineSourceMap=true:74345:38)
    at AnimatedComponentWrapper
    at InnerScreen (http://localhost:8081/index.bundle?platform=windows&dev=true&hot=false&inlineSourceMap=true:295463:36)
    at Screen (http://localhost:8081/index.bundle?platform=windows&dev=true&hot=false&inlineSourceMap=true:295737:36)
    at MaybeScreen (http://localhost:8081/index.bundle?platform=windows&dev=true&hot=false&inlineSourceMap=true:295242:25)
    at RCTView
    at View
    at ScreenContainer (http://localhost:8081/index.bundle?platform=windows&dev=true&hot=false&inlineSourceMap=true:295606:32)
    at MaybeScreenContainer (http://localhost:8081/index.bundle?platform=windows&dev=true&hot=false&inlineSourceMap=true:295213:24)
    at RCTView
    at View
    at Background (http://localhost:8081/index.bundle?platform=windows&dev=true&hot=false&inlineSourceMap=true:281893:22)
    at CardStack (http://localhost:8081/index.bundle?platform=windows&dev=true&hot=false&inlineSourceMap=true:291515:36)
    at RCTView
    at View
    at SafeAreaProviderCompat (http://localhost:8081/index.bundle?platform=windows&dev=true&hot=false&inlineSourceMap=true:291207:25)
    at RCTView
    at View
    at StackView (http://localhost:8081/index.bundle?platform=windows&dev=true&hot=false&inlineSourceMap=true:280795:36)
    at PreventRemoveProvider (http://localhost:8081/index.bundle?platform=windows&dev=true&hot=false&inlineSourceMap=true:286493:26)
    at NavigationContent (http://localhost:8081/index.bundle?platform=windows&dev=true&hot=false&inlineSourceMap=true:287359:23)
    at http://localhost:8081/index.bundle?platform=windows&dev=true&hot=false&inlineSourceMap=true:287373:28
    at StackNavigator (http://localhost:8081/index.bundle?platform=windows&dev=true&hot=false&inlineSourceMap=true:280639:19)
    at EnsureSingleNavigator (http://localhost:8081/index.bundle?platform=windows&dev=true&hot=false&inlineSourceMap=true:283084:25)
    at BaseNavigationContainer (http://localhost:8081/index.bundle?platform=windows&dev=true&hot=false&inlineSourceMap=true:282593:29)
    at ThemeProvider (http://localhost:8081/index.bundle?platform=windows&dev=true&hot=false&inlineSourceMap=true:289097:22)
    at NavigationContainerInner (http://localhost:8081/index.bundle?platform=windows&dev=true&hot=false&inlineSourceMap=true:288957:27)
    at RCTView
    at View
    at CompatNativeSafeAreaProvider (http://localhost:8081/index.bundle?platform=windows&dev=true&hot=false&inlineSourceMap=true:290518:25)
    at SafeAreaProvider (http://localhost:8081/index.bundle?platform=windows&dev=true&hot=false&inlineSourceMap=true:290350:25)
    at Navigation (http://localhost:8081/index.bundle?platform=windows&dev=true&hot=false&inlineSourceMap=true:197086:36)
    at LoginPage (http://localhost:8081/index.bundle?platform=windows&dev=true&hot=false&inlineSourceMap=true:114422:36)
    at RCTView
    at View
    at KeyboardAvoidingView (http://localhost:8081/index.bundle?platform=windows&dev=true&hot=false&inlineSourceMap=true:77534:36)
    at Provider (http://localhost:8081/index.bundle?platform=windows&dev=true&hot=false&inlineSourceMap=true:301016:22)
    at App (http://localhost:8081/index.bundle?platform=windows&dev=true&hot=false&inlineSourceMap=true:113163:36)
    at RCTView
    at View
    at RCTView
    at View
    at MenuProvider (http://localhost:8081/index.bundle?platform=windows&dev=true&hot=false&inlineSourceMap=true:298893:9)
    at AppWindows (http://localhost:8081/index.bundle?platform=windows&dev=true&hot=false&inlineSourceMap=true:113066:36)
    at RCTView
    at View
    at RCTView
    at View
    at AppContainer (http://localhost:8081/index.bundle?platform=windows&dev=true&hot=false&inlineSourceMap=true:78019:36)
    at ComponentWithDisplayName (http://localhost:8081/index.bundle?platform=windows&dev=true&hot=false&inlineSourceMap=true:86112:29)
```
@cjhines  Any suggestions here would be appreciated.
Thanks

**Comment by cjhines** [comment]
@Manjunatha123 Did you clear the solution after installing 0.69.6?

<img width="415" alt="Screenshot 2022-09-12 at 17 53 12" src="https://user-images.githubusercontent.com/16542421/189699968-a9a05d4d-9542-49ed-8623-ec3b11c28fd4.png">

**Comment by 17Amir17** [comment]
Having the same issue but in react-native-webview on windows

**Comment by abbasvlb** [comment]
@taduyde @Manjunatha123 Im getting this error, below is my packages. Any advice?

`"dependencies": {
    "@babel/plugin-proposal-decorators": "^7.18.10",
    "@babel/preset-flow": "^7.18.6",
    "@react-native-async-storage/async-storage": "^1.17.10",
    "@react-native-community/datetimepicker": "^6.3.2",
    "@react-native-community/masked-view": "^0.1.11",
    "@react-native-community/netinfo": "^9.3.0",
    "@react-native-picker/picker": "^2.4.4",
    "@react-navigation/elements": "^1.3.6",
    "@react-navigation/native": "^6.0.12",
    "@react-navigation/stack": "^6.2.3",
    "deprecated-react-native-prop-types": "^2.3.0",
    "inversify": "4.13.0",
    "moment": "^2.29.4",
    "react": "18.0.0",
    "react-native": "0.69.5",
    "react-native-bcrypt": "^2.4.0",
    "react-native-calendars": "^1.1288.2",
    "react-native-device-info": "^10.0.2",
    "react-native-elements": "^3.4.2",
    "react-native-file-viewer": "^2.1.5",
    "react-native-fs": "^2.20.0",
    "react-native-gesture-handler": "^2.4.2",
    "react-native-linear-gradient": "^2.6.2",
    "react-native-maps": "^1.3.1",
    "react-native-modal-datetime-picker": "^13.1.2",
    "react-native-modal-selector": "^2.1.1",
    "react-native-popup-menu": "^0.16.0",
   
    "react-native-safe-area-context": "^4.3.3",
    "react-native-reanimated": "^2.10.0",
    "react-native-screens": "^3.17.0",
    "react-native-simple-dialogs": "^1.5.0",
    "react-native-simple-toast": "^1.1.4",
    "react-native-sqlite-storage": "^6.0.1",
    "react-native-vector-icons": "^9.2.0",
    "react-native-webview": "^11.23.1",
    "react-native-windows": "0.69.9",
    "react-redux": "^8.0.2",
    "react-router-redux": "^4.0.8",
    "recyclerlistview": "^4.1.3",
    "redux": "^4.2.0",
    "redux-devtools-extension": "^2.13.9",
    "redux-logger": "^3.0.6",
    "reflect-metadata": "^0.1.13",
    "rnpm-plugin-windows": "^0.6.1",
    "superagent": "^8.0.0",
    "superagent-promise": "^1.1.0",
    "windows": "^0.1.2"
  },`

**Comment by Boiko33** [comment]
Faced same issue with:
"react-native": "0.70.3",
"react-native-windows": "0.70.3",
"react-native-screens": "^3.18.2",
"@react-navigation/drawer": "6.4.1",
"@react-navigation/native": "6.0.10",
"@react-navigation/stack": "6.2.1",

The app crushing with this error:
`folly::toJson: JSON object value was a NaN when serializing value at "arguments"->2->2->"layout"->"height"`
It happened to me while navigate between Drawer.Screen

**Comment by Boiko33** [comment]
@tomekzaw Do you have the vision about which functionality and file probably needs to be changed (in react-navigation packages), and where issue is placed?

**Comment by tomekzaw** [comment]
@Boiko33 I solved a similar issue in react-native-reanimated but there's no occurrences of `toJSON` in this repo so I'm still not sure where the error originates from.

**Comment by Boiko33** [comment]
@tomekzaw So, did it fix Windows issue? if yes, would you tell what did you do?

**Comment by tomekzaw** [comment]
Nope, the fix was for Android but it was C++ code, just like here.

**Comment by Boiko33** [comment]
@tomekzaw As I see right now there are no files inside library with C++ code. I am using v2.2.4, and it worked with react-native v0.66.1, but not with the latest one. Do you have any ideas how to fix that issue?

**Comment by Neeraj2001** [comment]
I am also facing the same issue 
![image](https://user-images.githubusercontent.com/42690154/210046026-5d7ba5c1-86a4-4d89-bc76-81b5dc1fdb27.png)

These are the packages i am using

![image](https://user-images.githubusercontent.com/42690154/210046072-f6fafd03-c7e0-4b9c-a772-02aa046ddb31.png)

**Comment by cjhines** [comment]
Still occurs in debug mode for me regularly

**Comment by MacKenzieHnC** [comment]
To anyone still having this issue, is your App wrapped in a `<SafeAreaView>`? Try removing that.

**Comment by ttruongatl** [comment]
@MacKenzieHnC  could you link the issue in RNW?

**Comment by MacKenzieHnC** [comment]
@ttruongatl Oh yeah, my bad. Fixed

**Comment by ransfordnyarko** [comment]
Even without useState I still face this issue

**Comment by MacKenzieHnC** [comment]
> Even without useState I still face this issue

Is the content of your screens static? If not, are you getting the data from a store or something?

**Comment by ohzak** [comment]
don't know if anybody solved the issue but im still having the problem even with the destination screen completely static

here's my package.json

    "@ant-design/icons": "^4.8.0",
    "@react-navigation/drawer": "^6.5.6",
    "@react-navigation/native": "^6.1.1",
    "axios": "^1.2.2",
    "cjs-module": "^1.5.0",
    "native-base": "^3.4.25",
    "open": "^8.4.0",
    "react": "18.1.0",
    "react-hook-form": "^7.41.5",
    "react-native": "0.70.6",
    "react-native-axios": "^0.17.1",
    "react-native-easy-grid": "^0.2.2",
    "react-native-gesture-handler": "^2.9.0",
    "react-native-reanimated": "^2.13.0",
    "react-native-safe-area-context": "^4.5.0",
    "react-native-screens": "^3.19.0",
    "react-native-svg": "^13.6.0",
    "react-native-svg-transformer": "^1.0.0",
    "react-native-vector-icons": "^9.2.0",
    "react-native-windows": "0.70.10"

**Comment by ransfordnyarko** [comment]
> > Even without useState I still face this issue
> 
> Is the content of your screens static? If not, are you getting the data from a store or something?

Yes the content of my screen is static

**Comment by MacKenzieHnC** [comment]
@ransfordnyarko Okay, yeah, I see what you mean. I still think it's related to the same core problem though. For some reason, RNW causes both screens to re-render every time, and that leads to a lot of problems. Does this show up for you every time in your repro?

**Comment by hefberk** [comment]
Hi guys, I'm also facing this problem, and this bug seems to be related to a navigation header title which is null at screen initialisation. try to set a header title in react navigation

**Comment by IsuruLakshan97** [comment]
I am having the same issue in my RNW app.
I am trying to create RNW app from an existing React Native app.
with,
"react": "^18.2.0"
"react-native": "^0.71.7"
"react-native-windows": "0.71.10"

when I navigate to a new screen the screen loads and after couple of seconds it gives this error
 "  
 Windows APP: folly::toJson: JSON object value was a NaN when serializing value at "arguments"->2->2->"layout"->"height"
 "
 
 The navigation through the screen is done as follows.
 
 
<img width="538" alt="Screenshot 2023-05-12 153013" src="https://github.com/react-navigation/react-navigation/assets/62101948/a489fbe4-f755-4c7d-9432-75a22737484a">

the RootNavigation.js file is imported

<img width="455" alt="Screenshot 2023-05-12 153111" src="https://github.com/react-navigation/react-navigation/assets/62101948/05e4565d-0f8f-46a6-83be-6c7c39638d94">

Then the Rootnavigation.js file is as follows,

<img width="431" alt="Screenshot 2023-05-12 152753" src="https://github.com/react-navigation/react-navigation/assets/62101948/db8a340c-e76d-4894-a048-0e95ce80d598">

I get the error as follows when I try to go the Menu screen,
<img width="443" alt="Screenshot 2023-05-10 102106" src="https://github.com/react-navigation/react-navigation/assets/62101948/5063392d-d4e3-46e3-9407-6d93027fa608">

I tried to use,

`import { StackActions } from '@react-navigation/native';`
 
 But still get the same error! Any possible help or clarification is highly appreciated

**Comment by exotexot** [comment]
This also happens on the latest react-native / react-native windows / react-navigation versions as of today.

I find it also difficult to debug.  Any ideas guys???


```
  "dependencies": {
    "@dr.pogodin/react-native-fs": "^2.21.0-alpha.3",
    "@dr.pogodin/react-native-static-server": "^0.8.3",
    "@react-native-async-storage/async-storage": "^1.19.2",
    "@react-native-community/blur": "^4.3.2",
    "@react-native-community/checkbox": "^0.5.16",
    "@react-native-community/masked-view": "^0.1.11",
    "@react-native-community/netinfo": "^9.4.1",
    "@react-native-community/toolbar-android": "^0.2.1",
    "@react-native-segmented-control/segmented-control": "github:exotexot/segmented-control",
    "@react-navigation/drawer": "^6.6.3",
    "@react-navigation/native": "^6.1.7",
    "@react-navigation/stack": "^6.3.17",
    "@welldone-software/why-did-you-render": "^7.0.1",
    "blueimp-md5": "^2.19.0",
    "highlight-words-core": "^1.2.2",
    "lodash": "^4.17.21",
    "react": "^18.2.0",
    "react-native": "^0.72.4",
    "react-native-device-info": "^10.8.0",
    "react-native-dialog": "^9.3.0",
    "react-native-fast-image": "^8.6.3",
    "react-native-fs": "github:exotexot/react-native-fs#vinz_multi_merge",
    "react-native-gesture-handler": "^2.12.1",
    "react-native-modal": "^13.0.1",
    "react-native-navigation-bar-color": "^2.0.2",
    "react-native-pdftron": "github:exotexot/pdftron-react-native",
    "react-native-radio-buttons-group": "^3.0.3",
    "react-native-reanimated": "^1.13.4",
    "react-native-safe-area-context": "^4.7.1",
    "react-native-screens": "^3.24.0",
    "react-native-sensitive-info": "^6.0.0-alpha.9",
    "react-native-svg": "^13.13.0",
    "react-native-use-persist-storage": "^1.0.2",
    "react-native-vector-icons": "^10.0.0",
    "react-native-webview": "^13.3.1",
    "react-native-windows": "^0.72.8",
    "use-async-effect": "^2.2.7"
  },
```

**Comment by sivakusayan** [comment]
For anyone who finds this, this [person was kind enough to investigate and propose a bandaid fix ](https://github.com/microsoft/react-native-windows/issues/11182)that we can possibly implement locally in the C++ code. Just make sure that the fix actually works for your app.

**Comment by bwjohns4** [comment]
Is there any update on this? I am also getting this error on React Native Windows.
