### ISSUE TITLE
TS error on useScrollToTop if useRef type is SectionList

### ISSUE THREAD

**Issue by TomCorvus** [react-navigation/react-navigation#10722]
### Current behavior

Hi 👋

I update @types/react to `^18.0.15` version and I have a TS error if I use useScrollToTop method with SectionList.

```
const sectionList = useRef<SectionList>(null);
useScrollToTop(sectionList);
```

### Expected behavior

No error or warning

### Reproduction

https://codesandbox.io/s/typescript-playground-export-forked-6tylip?from-embed=&file=/index.tsx

### Platform

- [ ] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/​bottom-tabs
- [ ] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [X] @react-navigation/​material-top-tabs
- [X] @react-navigation/​stack
- [ ] @react-navigation/​native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | ^6.0.11
| @react-navigation/material-top-tabs    | ^6.2.2
| @react-navigation/stack                | ^6.2.2
| react-native-safe-area-context         | ^4.3.1
| react-native-screens                   | ^3.15.0
| react-native-gesture-handler           | ^1.10.3
| react-native-reanimated                | 2.9.1
| react-native-tab-view                  | ^3.1.1
| react-native-pager-view                | 5.4.25
| react-native                           | ~0.69.3
| expo                                   | ~46.0.1
| node                                   | v16.16.0
| yarn                            | 3.2.2

**Comment by TomCorvus** [comment]
https://codesandbox.io/s/typescript-playground-export-forked-6tylip?from-embed=&file=/index.tsx

**Comment by TomCorvus** [comment]
Repro:
https://codesandbox.io/s/typescript-playground-export-forked-6tylip?from-embed=&file=/index.tsx

**Comment by ken0nek** [comment]
+1

Getting the same error.

**Comment by ken0nek** [comment]
@TomCorvus I could resolve this error. I will create a pull request for the time being, please use this patch.

```diff
diff --git a/node_modules/@react-navigation/native/lib/typescript/src/useScrollToTop.d.ts b/node_modules/@react-navigation/native/lib/typescript/src/useScrollToTop.d.ts
index fefce01..c07a9c7 100644
--- a/node_modules/@react-navigation/native/lib/typescript/src/useScrollToTop.d.ts
+++ b/node_modules/@react-navigation/native/lib/typescript/src/useScrollToTop.d.ts
@@ -1,4 +1,6 @@
 import * as React from 'react';
+import {ScrollView} from 'react-native'
+
 declare type ScrollOptions = {
     x?: number;
     y?: number;
@@ -16,8 +18,8 @@ declare type ScrollableView = {
 } | {
     scrollResponderScrollTo(options: ScrollOptions): void;
 };
declare type ScrollableWrapper = {
-    getScrollResponder(): React.ReactNode;
+    getScrollResponder(): React.ReactNode | ScrollView;
 } | {
     getNode(): ScrollableView;
 } | ScrollableView;

```

**Comment by TomCorvus** [comment]
@ken0nek I patch the file but I still have the warning.
Did you try your fix with section list reference?
`const sectionList = useRef<SectionList>(null);`

**Comment by ken0nek** [comment]
> Did you try your fix with section list reference?

@TomCorvus Yes, I checked with section list reference and got no errors.

<img width="575" alt="Screen Shot 2022-09-22 at 3 16 08 PM" src="https://user-images.githubusercontent.com/5785300/191860971-9ca3f54b-afe6-48f6-90aa-d1e4b9294348.png">

**Comment by TomCorvus** [comment]
Sorry @ken0nek for this very late reply but your patch fix the problem. Thank you!
