### ISSUE TITLE
Error: setNativeProps is not currently supported in Fabric RN-0.69.3 - Card.tsx (Line 245)

### ISSUE THREAD

**Issue by Sumit2202** [react-navigation/react-navigation#10720]
### Current behavior

With RN 0.69.3 setNativeProps is not supported with Fabric Enabled, my app keeps on crashing!

 ERROR  Warning: Warning: setNativeProps is not currently supported in Fabric
    in Card (at CardContainer.tsx:219)
    in CardContainer (at CardStack.tsx:661)
    in RNSScreen (at createAnimatedComponent.js:211)
    in AnimatedComponent (at createAnimatedComponent.js:264)
    in AnimatedComponentWrapper (at src/index.native.tsx:257)
    in MaybeFreeze (at src/index.native.tsx:256)
    in Screen (at Screens.tsx:37)
    in MaybeScreen (at CardStack.tsx:654)
    in RNSScreenContainer (at src/index.native.tsx:332)

### Expected behavior

setNativeProps should be replaced. [Migrating off setNativeProps](https://reactnative.dev/docs/next/new-architecture-library-intro#migrating-off-setnativeprops)

### Reproduction

https://github.com/Sumit2202/MyApp

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/​bottom-tabs
- [ ] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [X] @react-navigation/​stack
- [ ] @react-navigation/​native-stack

### Environment

- [s] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/stack         |^6.2.2       
| react-native-safe-area-context   | ^4.3.1     
| react-native-screens            |^3.15.0       
| react-native-gesture-handler   |     ^2.5.0   
| react-native-reanimated      |^3.0.0-rc.0     
| react-native                 |0.69.3

**Comment by ginnymin** [comment]
I'm seeing this issue and my `@react-navigation/native` is `6.0.11`

**Comment by umardev500** [comment]
same

**Comment by anton-patrushev** [comment]
I'm on `0.69.5` RN, and just migrated from `"@react-navigation/native-stack": "6.8.0"` to `"@react-navigation/stack": "6.2.3"` packages since the first one doesn't work for me with New RCT Architecture enabled **at all** (Fabric + TurboModules) — I'm on iOS only.

And now I'm getting **the same** error/warning in a console :(
