### ISSUE TITLE
android app is crash when importing drawer in stack navigator 

### ISSUE THREAD

**Issue by Kadir-prog** [react-navigation/react-navigation#10733]
### Current behavior

this is my drawer

import 'react-native-gesture-handler';
import React from "react";
import { createDrawerNavigator } from "@react-navigation/drawer";
import GuestHome from '../pages/LoginAsGuest/HomeScreens/GuestHome'
import CustomDrawer from './Custom_Drawer'
import Guest_BottomTabNavigator from "./Guest_BottomNavigation";

const Drawer = createDrawerNavigator();

const DrawerNavigator = () => {
  return (
    <Drawer.Navigator
      drawerContent={(props) => <CustomDrawer {...props} />}
    >
      <Drawer.Screen name="screen1" component={Guest_BottomTabNavigator} options={{headerShown:false}} />
    </Drawer.Navigator>
  );
}

export default DrawerNavigator;

custom component :-

import React,{useState} from 'react';
import {
    View,
    Text,
    StyleSheet,
    StatusBar,
    useWindowDimensions,
    Button,
} from 'react-native';
import { NavigationContainer } from '@react-navigation/native';
import { createStackNavigator } from '@react-navigation/stack';
import {
    createDrawerNavigator,
    DrawerContentScrollView,
    DrawerItemList,
    DrawerItem,
} from '@react-navigation/drawer';

export default function CustomDrawer(props) {

    return (
        <DrawerContentScrollView {...props}>
            <StatusBar backgroundColor="transparent" barStyle='dark-content' translucent={true} />
            <View style={{ flex: 1, marginTop: -5 }}>
                <View style={{ flex: 1, backgroundColor: '#132239', height: 150, justifyContent: 'center' }}>
                    <View style={{ paddingLeft: 20 }}>
                        <Text >Welcome,</Text>
                        <Text >Jonathan Doe</Text>
                    </View>
                </View>
                <DrawerItem
                    label="Home"
                    onPress={() => {
                        props.navigation.navigate('Home');
                        props.navigation.closeDrawer();
                    }}
                />
                <DrawerItem
                    label="Ride histroy"
                    onPress={() => {
                        props.navigation.navigate('Ride_history');
                        props.navigation.closeDrawer();
                    }}
                />
                <DrawerItem
                    label="My account"
                    onPress={() => {
                        props.navigation.navigate('Profile');
                        props.navigation.closeDrawer();
                    }}
                />
                <DrawerItem
                    label="My wallet"
                    onPress={() => {
                        props.navigation.navigate('Screen1');
                    }}
                />
                <DrawerItem
                    label="Help & Support"
                    onPress={() => {
                        props.navigation.navigate('Help_and_support');
                        props.navigation.closeDrawer();
                    }}
                />
                
            </View>
        </DrawerContentScrollView>
    )
}

Stack

<Stack.Screen
          name="Guest_HomeScreen"
          component={DrawerNavigator }
          options={{
            title: '',
            headerShown: false,
            headerTitleAlign: 'center',
            headerTitleStyle: {color: '#fff', fontFamily: 'poppins'},
            headerStyle: {
              backgroundColor: '#132239',
            },
          }}
        />

any thing is wrong here please help

### Expected behavior

want to open drawer on home screen

### Reproduction

nope

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/​bottom-tabs
- [X] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [X] @react-navigation/​stack
- [X] @react-navigation/​native-stack

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |
| @react-navigation/bottom-tabs          |
| @react-navigation/drawer               |
| @react-navigation/material-bottom-tabs |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                |
| @react-navigation/native-stack         |
| react-native-safe-area-context         |
| react-native-screens                   |
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           |
| expo                                   |
| node                                   |
| npm or yarn                            |

**Comment by raajnadar** [comment]
Edit the issue ticket with versions and a runnable example or else I will close the issue

**Comment by krisidmisso** [comment]
@raajnadar use the latest stable version for every lib. This issue is for android in debug mode. In release seems to be working ok. ios debug mode doesnt have any issue

**Comment by raajnadar** [comment]
You might be using latest version of dependant modules, not the react navigation package, you need to provide a runnable repro so it is easier to find the issue and pass the issue to respected package repository

**Comment by Kadir-prog** [comment]
> You might be using latest version of dependant modules, not the react navigation package, you need to provide a runnable repro so it is easier to find the issue and pass the issue to respected package repository

thanks @raajnadar my issue was solved when i upgraded my navigation package with latest one thanks for reply

**Comment by Kadir-prog** [comment]
> @raajnadar use the latest stable version for every lib. This issue is for android in debug mode. In release seems to be working ok. ios debug mode doesnt have any issue

thanks for reply the issue was in my package navigation version was older

**Comment by ggchicote** [comment]
could you please share your final package.json set up? i'm struggling with the same issue. This is mine:

`{
  "dependencies": {
    "@apollo/client": "^3.6.9",
    "@react-navigation/drawer": "^6.4.1",
    "@react-navigation/material-top-tabs": "^6.2.3",
    "@react-navigation/native": "^6.0.10",
    "axios": "^0.27.2",
    "dotenv": "^16.0.1",
    "expo": "~46.0.8",
    "expo-status-bar": "^1.4.0",
    "expo-updates": "^0.14.5",
    "react": "18.0.0",
    "react-native": "0.69.5",
    "react-native-gesture-handler": "~2.5.0",
    "react-native-reanimated": "~2.9.1",
    "react-native-safe-area-context": "4.3.1",
    "react-native-screens": "~3.15.0"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/eslint-parser": "^7.18.9",
    "@colors/colors": "^1.5.0",
    "eslint": "^8.23.0",
    "eslint-plugin-react": "^7.31.1",
    "select-prompt": "^0.3.2"
  },
  "private": true
}`

**Comment by Kadir-prog** [comment]
> could you please share your final package.json set up? i'm struggling with the same issue. This is mine:
> 
> > {
> > "dependencies": {
> > "@apollo/client": "^3.6.9",
> > "@react-navigation/drawer": "^6.4.1",
> > "@react-navigation/material-top-tabs": "^6.2.3",
> > "@react-navigation/native": "^6.0.10",
> > "axios": "^0.27.2",
> > "dotenv": "^16.0.1",
> > "expo": "~46.0.8",
> > "expo-status-bar": "^1.4.0",
> > "expo-updates": "^0.14.5",
> > "react": "18.0.0",
> > "react-native": "0.69.5",
> > "react-native-gesture-handler": "~2.5.0",
> > "react-native-reanimated": "~2.9.1",
> > "react-native-safe-area-context": "4.3.1",
> > "react-native-screens": "~3.15.0"
> > },
> > "devDependencies": {
> > "@babel/core": "^7.12.9",
> > "@babel/eslint-parser": "^7.18.9",
> > "@colors/colors": "^1.5.0",
> > "eslint": "^8.23.0",
> > "eslint-plugin-react": "^7.31.1",
> > "select-prompt": "^0.3.2"
> > },
> > "private": true
> > }

here we go
"dependencies": {
    "@react-native-community/cameraroll": "^4.1.2",
    "@react-native-community/clipboard": "^1.5.1",
    "@react-native-community/masked-view": "^0.1.11",
    "@react-navigation/bottom-tabs": "^6.3.1",
    "@react-navigation/drawer": "^6.4.3",
    "@react-navigation/material-bottom-tabs": "^6.2.1",
    "@react-navigation/native": "^6.0.10",
    "@react-navigation/native-stack": "^6.6.2",
    "@react-navigation/stack": "^6.2.1",
    "@rneui/base": "^4.0.0-rc.5",
    "@rneui/themed": "^4.0.0-rc.5",
    "@twotalltotems/react-native-otp-input": "^1.3.11",
    "moment": "^2.29.4",
    "native-base": "^2.15.2",
    "react": "17.0.2",
    "react-native": "0.68.2",
    "react-native-calendars": "^1.1284.0",
    "react-native-datepicker": "^1.7.2",
    "react-native-elements": "^3.4.2",
    "react-native-gesture-handler": "^2.5.0",
    "react-native-linear-gradient": "^2.6.2",
    "react-native-paper": "^4.12.1",
    "react-native-phone-number-input": "^2.1.0",
    "react-native-progress": "^5.0.0",
    "react-native-raw-bottom-sheet": "^2.2.0",
    "react-native-reanimated": "^2.8.0",
    "react-native-safe-area-context": "^4.3.1",
    "react-native-screens": "^3.13.1",
    "react-native-snap-carousel": "^3.9.1",
    "react-native-splash-screen": "^3.3.0",
    "react-native-svg": "^12.4.3",
    "react-native-swipe-gestures": "^1.0.5",
    "react-native-vector-icons": "^9.2.0",
    "react-redux": "^8.0.2",
    "redux": "^4.2.0"
  },

**Comment by Kadir-prog** [comment]
here we go @ggchicote 

"dependencies": {
    "@react-native-community/cameraroll": "^4.1.2",
    "@react-native-community/clipboard": "^1.5.1",
    "@react-native-community/masked-view": "^0.1.11",
    "@react-navigation/bottom-tabs": "^6.3.1",
    "@react-navigation/drawer": "^6.4.3",
    "@react-navigation/material-bottom-tabs": "^6.2.1",
    "@react-navigation/native": "^6.0.10",
    "@react-navigation/native-stack": "^6.6.2",
    "@react-navigation/stack": "^6.2.1",
    "@rneui/base": "^4.0.0-rc.5",
    "@rneui/themed": "^4.0.0-rc.5",
    "@twotalltotems/react-native-otp-input": "^1.3.11",
    "moment": "^2.29.4",
    "native-base": "^2.15.2",
    "react": "17.0.2",
    "react-native": "0.68.2",
    "react-native-calendars": "^1.1284.0",
    "react-native-datepicker": "^1.7.2",
    "react-native-elements": "^3.4.2",
    "react-native-gesture-handler": "^2.5.0",
    "react-native-linear-gradient": "^2.6.2",
    "react-native-paper": "^4.12.1",
    "react-native-phone-number-input": "^2.1.0",
    "react-native-progress": "^5.0.0",
    "react-native-raw-bottom-sheet": "^2.2.0",
    "react-native-reanimated": "^2.8.0",
    "react-native-safe-area-context": "^4.3.1",
    "react-native-screens": "^3.13.1",
    "react-native-snap-carousel": "^3.9.1",
    "react-native-splash-screen": "^3.3.0",
    "react-native-svg": "^12.4.3",
    "react-native-swipe-gestures": "^1.0.5",
    "react-native-vector-icons": "^9.2.0",
    "react-redux": "^8.0.2",
    "redux": "^4.2.0"
  },
