### ISSUE TITLE
Web URLS are not respected when conditionally rendering navigators

### ISSUE THREAD

**Issue by trattles** [react-navigation/react-navigation#10747]
### Current behavior

Currently several of the docs even suggest conditionally rendering Navigators or Screens within Navigators. However, if you do this, Web URLS will be lost, and not resolve correctly.

I first noticed this issue when using a suspense boundary around a navigator.

If you conditionally render a navigator - it's URL configuration is not respected, and you'll end up at the initial route set for that navigator, rather than where you should actually end up.

Example LInking Config
```
const linking = {
  prefixes: [],
  config: {
    screens: {
      TestHome: "",
      TestHomeParams: {
        initialRouteName: "Deep",
        path: "deep/under",
        screens: {
          Deep: "",
          DeepPartTwo: "partTwo/:params",
        },
      },
    },
  },
};
```

With the above config, if I navigate to `deep/under/partTwo/someparam` if, that DeepPartTwo route OR it's navigator is conditionally rendered, I'll end up on the "Deep" screen rather than the "DeepPartTwo" screen.

Example of the nested navigator from above

```
const Stack2 = createStackNavigator();
const NestedNavigator = () => {
  const [state, setState] = useState(false);
  useEffect(() => {
    if (!state) {
      setState(state);
    }
  }, [state, setState]);
  return (
    <Stack2.Navigator initialRouteName="Deep">
      <Stack2.Screen
        name={"Deep"}
        component={FakeScreenComponent}
        options={{ headerShown: false, title: "Whoosh" }}
      />
      {state && (
        <Stack2.Screen
          name={"DeepPartTwo"}
          component={FakeScreenComponent}
          options={{ headerShown: false, title: "Whoosh" }}
        />
      )}
    </Stack2.Navigator>
  );
};
```

I included a GH repository that if you run Yarn Start - and then run the web build, you can try to navigate as my example above and you'll run into the issue.

### Expected behavior

I expect to end up on the screen indicated by the route config.

For example, the default example for "best practices when nesting" in this doc page `https://reactnavigation.org/docs/nesting-navigators` is a bit confusing as I'm not sure how I'd resolve "isLoggedIn" early enough that the URL would still be respected.

How am I to combine conditionally rendered navigators / screens with URL resolution for web?

### Reproduction

https://github.com/trattles/example-react-navigation-url-broken

### Platform

- [ ] Android
- [ ] iOS
- [X] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/​bottom-tabs
- [ ] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [X] @react-navigation/​stack
- [X] @react-navigation/​native-stack

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
    "@react-navigation/native": "^6.0.11",
    "@react-navigation/stack": "^6.2.2",
    "expo": "~45.0.0",
    "expo-status-bar": "~1.3.0",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-native": "0.68.2",
    "react-native-safe-area-context": "4.2.4",
    "react-native-screens": "~3.11.1",
    "react-native-web": "0.17.7"

**Comment by bfischer1121** [comment]
Also ran into this issue. Would be nice if `getStateFromPath` was optionally asynchronous, like `getInitialURL`. Would let us delay react-navigation's route resolution until data is loaded and the conditional tree is built.

**Comment by trattles** [comment]
I agree - if there was some way to hook into route resolution - or even save the initial route - but it seems like react navigation must require the navigator tree to actually figure out the route.

I solved this for myself by just doing any and all logic that would have caused things to be conditional before even rendering navigators. This is a bit awkward, but it works.

I think the docs should at least call this out - as they kind of tell you to conditionally render navigators without warning you of this issue.

**Comment by bfischer1121** [comment]
Seems like a good approach. We just decided to stop doing conditional renders to where it would change the routes in any way (swapping out components for the same route seems fine). Also, with code splitting, pulled all of our dynamically loaded navigators into a package available at boot time (cold start of app would result in resolution failing since react-navigation didn't know what package to load). All of this seems a bit hacky but whatever's needed to get it to work.

**Comment by leannieloop** [comment]
We also ran into this with a `Navigator` that is conditionally rendering one `Group` or another, depending on whether or not a user is authenticated (similar to what is shown in the ['Authentication flows' page in the docs](https://reactnavigation.org/docs/auth-flow/).

**Comment by satya164** [comment]
The stack renders based on what screens are available at the time of first render. Adding a new screen to the stack later never switches to it unless you navigate/update the state. The URL matches the screen that's rendered. If you want the stack to preserve the URL, then it needs to render the correct screen on the first render where the screen matches the URL.

As shown in the auth flow docs, the navigation container is not rendered until you have resolved the authentication state - a splash screen component is rendered instead.

Once the auth state is resolved and can be accessed synchronously, the navigation container is rendered and will also render the appropriate screen matching the URL.
