### ISSUE TITLE
Navigation header getting shift when go back and forth to same screen for multiple times.

### ISSUE THREAD

**Issue by hareshmabbly** [react-navigation/react-navigation#10746]
### Current behavior

Currently we have two screen A and B and in Screen B we are using navigation.setOptions() to set header title and right image now if we move from screen A to screen B like 5 or 6 times continuously then header title getting shifted and some time goes out of header.

### Expected behavior

Header title should not get shifted

### Reproduction

https://snack.expo.dev/

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/​bottom-tabs
- [X] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [X] @react-navigation/​stack
- [ ] @react-navigation/​native-stack

### Environment

![image (5)](https://user-images.githubusercontent.com/102948668/183654962-c1923d83-7207-4514-986f-5909920da3d7.png)

"@react-navigation/bottom-tabs": "^6.2.0",
"@react-navigation/devtools": "^6.0.5",
"@react-navigation/drawer": "^6.3.1",
"@react-navigation/elements": "^1.3.3",
"@react-navigation/material-top-tabs": "^6.2.1",
"@react-navigation/native": "^6.0.8",
"@react-navigation/native-stack": "^6.5.0",
 react-native   0.64.3
|expo   ~44.0.2

**Comment by Mihai-github** [comment]
Hi, I'm also having an issue with **react-navigation v6**  when adding as a header title image after moving to a different screen the picture is getting cut off.

![image](https://user-images.githubusercontent.com/56633911/195844749-595f2650-d6f2-4757-8ebe-e5f9744cc495.png)
After navigating to the settings screen and coming back
![image](https://user-images.githubusercontent.com/56633911/195844865-270df2c9-25d8-4cb2-b3c2-6d38edb72244.png)

**Comment by majirosstefan** [comment]
so this should not be closed, no ?

**Comment by CagriUysal** [comment]
I was having the same issue. Seems like the problem is gone when I've added a default headerTitle as recommended in the [docs](https://reactnavigation.org/docs/navigation-prop/#setoptions). That being said, I have no idea why the problem occurred in the first place.

```javascript

// In the navigator screen
      <UserStack.Screen
        name={SCREEN_NAMES.Chat}
        component={ChatScreen}
        options={{
          headerTitle: () => (  /* set this as default header title, seems like it solved my issue */
            <Text>Chat</Text>
          ),
        }}
      />

// In the ChatScreen.tsx
  useEffect(
    function initializeHeader() {
   
      navigation.setOptions({
        headerTitle: () => (
         /* Do something using props here */
        ),
      });
    },
    [navigation],
  );
```
