### ISSUE TITLE
Wrong redirect from notification when app is closed

### ISSUE THREAD

**Issue by cedricls1** [react-navigation/react-navigation#10752]
### Current behavior

Hello,

I did a serie of tests with the same link. I sent a notification on my phone and 7 times out of 20, the app opened on the home page and not the link of my notification with this warning :

> The navigation state parsed from the URL contains routes not present in the root navigator. This usually means that the linking configuration doesn't match the navigation structure.

The navigation seems not ready.
When the app is open, I don't have the problem.

We use this code :
`export async function getInitialURL(): Promise<string> {
  const dynamicLinkUrl = await dynamicLinks().getInitialLink()
  if (dynamicLinkUrl) {
    return dynamicLinkUrl.url
  }
  // Little break to avoid to have null link
  //await new Promise((r) => setTimeout(r, 500))
  const url = await BatchPush.getInitialURL()
  if (url) {
    return url
  }
  return WEBAPP_V2_URL
}`

When I used the setTimeout I don't have problem but it's not optimal

Thanks by advance for your help

### Expected behavior

Be redirected on my notification link everytime

### Reproduction

https://github.com/pass-culture/pass-culture-app-native

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/​bottom-tabs
- [ ] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [ ] @react-navigation/​stack
- [ ] @react-navigation/​native-stack

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | ^6.0.6
| @react-navigation/bottom-tabs          | ^6.0.9
| @react-navigation/stack                | ^6.0.11

**Comment by satya164** [comment]
As the warning says, your linking config doesn't match the navigation structure. You should review your linking config and make sure that the structure matches how you're nesting your screens. https://reactnavigation.org/docs/configuring-links/

If you still have issues, please open an issue with a minimal repro.
