### ISSUE TITLE
Version requirements make life difficult in TypeScript + React Native + Expo

### ISSUE THREAD

**Issue by ipmcc** [react-navigation/react-navigation#10751]
### Current behavior

[React Navigation 6 lists the following version requirements:](https://reactnavigation.org/docs/getting-started)

- react-native >= 0.63.0
- expo >= 41 (if you use [Expo](https://expo.io/))
- **typescript >= 4.1.0** (if you use [TypeScript](https://www.typescriptlang.org/))

[Expo/EAS lists these versions in their build infrastructure](https://docs.expo.dev/build-reference/infrastructure/) for the latest MacOS build nodes:

- macOS Monterey 12.4
- Xcode 13.4 (13F17a)
- Node.js 16.13.2
...

And even if you don't use EAS, Expo still says: "Only Node.js LTS releases (even-numbered) are recommended." and the latest current LTS versions are still 16.x.x, and will be until the end of October 2022. Even once Node blesses 18.x.x as the new active LTS at that time, Expo will have to rev their SDK to work with the new LTS Version, and redo their build infrastructure to use it as well. 

The problem with this is that TS 4.1.0 is _too new_ for even the newest LTS version of Node.js. You can determine the correct version of TS for a given version of Node by running `npm dist-tag ls @types/node`, which will give you this:

```
latest: 18.6.5
...
ts3.5: 15.6.1
ts3.6: 16.6.2
ts3.7: 16.11.7
ts3.8: 17.0.21
ts3.9: 17.0.41
ts4.0: 18.6.5
ts4.1: 18.6.5
ts4.2: 18.6.5
ts4.3: 18.6.5
ts4.4: 18.6.5
ts4.5: 18.6.5
ts4.6: 18.6.5
ts4.7: 18.6.5
ts4.8: 18.6.5
```

What this means, in practice, is that if I use TS == 3.7 as implied by this compatibility, I get many **dozens** of type-checking errors in react-navigation, but if I use TS >= 4.1, I get **hundreds** of errors for all the types for Node's built-ins (i.e. `@types/node`). 

For our part, we are using Expo SDK v45, Node.js 16.15.0 (which was the newest LTS when we last dug into this sort of thing), and TS v3.7 (because that's what's compatible with the Node.js we're using). 

### Expected behavior

I would expect react-navigation to use the appropriate version of TypeScript that lines up with recommended (i.e. LTS) versions of Node.js. I know that there's an amazing willingness in the TS/Node.js community to just shout, "YOLO! Ship it!" when faced with thousands of type errors (but where transpilation works), but it really diminishes the usefulness of TS type checking.

### Reproduction

https://www.typescriptlang.org/play?ts=3.7.5#code/MYewdgzgLgBAhmAogDzgWwA4BsCmA1OAJwEs4AjXGAXhgCIAJHLLEGAdREKwBNaAoUJFgIQUABY5CKdNhzUYABgDcfGDD5QAnhjkAxEKxpadIAGbwkqTLgIlyuFcbkAhIvKdmLoiVKuyVfDjIGJywTjAA3vogADQwroQAvkowAPSpMAAqYsQQMEEhhLAQmmBQcMgwuTBgOADu8HmemQDKMAAscWQArrDVCPmEhJxVYFltAMwAdADsUwCsfHypAFR8LbEwdRJjAJIwAOasUKzdEHIImjCe4nIACsMYME4QcfsHOLCSw4R5WMQAazkt3OWxylDOxDAB3G0xmAC4loghpx4QAKdoANjiAEYFABKcYAJgmCnm8JgAFkQNxupQAOS0KZTVLM1kstmclkAVXOv1SxAwaFSoG4OFSOAAjt04KkwDScAB9NA0uk4CCpAAChBwcGAUAAtGA4AA3YgHOBQYjgVLQPUA1L-MipF7AEgYKC2wjAWj0mBiOB5eX5YKhHDcGBoHBoMiSGD0lrlYAAgBypvNlutYAeIAw9KmSxWqT4QA

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/​bottom-tabs
- [ ] @react-navigation/​drawer
- [X] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [X] @react-navigation/​stack
- [ ] @react-navigation/​native-stack

### Environment

- [X] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |^6.0.10
| @react-navigation/bottom-tabs          |^6.3.1
| @react-navigation/material-top-tabs    |^6.1.1
| @react-navigation/stack                |^6.2.1
| react-native-safe-area-context         |4.2.4
| react-native-screens                   |~3.11.1
| react-native-gesture-handler           |~2.1.1
| react-native-reanimated                |~2.8.0
| react-native-tab-view                  |3.1.1
| react-native-pager-view                |5.4.15
| react-native                           |0.68.2
| expo                                   |^45.0.6
| node                                   |16.15.0
| npm or yarn                            |npm@8.5.5

**Comment by ipmcc** [comment]
It would; This is a fundamental, infrastructural version mismatch problem
with the use of TypeScript

**Comment by ipmcc** [comment]
> Hey! Thanks for opening the issue. The issue doesn't seem to contain a link to a repro (a [snack.expo.dev](https://snack.expo.dev) link, a [www.typescriptlang.org/play](https://www.typescriptlang.org/play) link or link to a GitHub repo under your username).
> 
> Can you provide a [minimal repro](https://stackoverflow.com/help/minimal-reproducible-example) which demonstrates the issue? Please try to keep the repro as small as possible and make sure that we can run it without additional setup.
> 
> A repro will help us debug the issue. The issue will be closed automatically after a while if you don't provide a repro.

There sure is a https://www.typescriptlang.org/play link here. Just in case, here it is again:

[https://www.typescriptlang.org/play?ts=3.7.5#code/MYewdgzgLgBAhmAogDzgWwA4BsCmA1OAJwEs4AjXGAXhgCIAJHLLEGAdREKwBNaAoUJFgIQUABY5CKdNhzUYABgDcfGDD5QAnhjkAxEKxpadIAGbwkqTLgIlyuFcbkAhIvKdmLoiVKuyVfDjIGJywTjAA3vogADQwroQAvkowAPSpMAAqYsQQMEEhhLAQmmBQcMgwuTBgOADu8HmemQDKMAAscWQArrDVCPmEhJxVYFltAMwAdADsUwCsfHypAFR8LbEwdRJjAJIwAOasUKzdEHIImjCe4nIACsMYME4QcfsHOLCSw4R5WMQAazkt3OWxylDOxDAB3G0xmAC4loghpx4QAKdoANjiAEYFABKcYAJgmCnm8JgAFkQNxupQAOS0KZTVLM1kstmclkAVXOv1SxAwaFSoG4OFSOAAjt04KkwDScAB9NA0uk4CCpAAChBwcGAUAAtGA4AA3YgHOBQYjgVLQPUA1L-MipF7AEgYKC2wjAWj0mBiOB5eX5YKhHDcGBoHBoMiSGD0lrlYAAgBypvNlutYAeIAw9KmSxWqT4QA](https://www.typescriptlang.org/play?ts=3.7.5#code/MYewdgzgLgBAhmAogDzgWwA4BsCmA1OAJwEs4AjXGAXhgCIAJHLLEGAdREKwBNaAoUJFgIQUABY5CKdNhzUYABgDcfGDD5QAnhjkAxEKxpadIAGbwkqTLgIlyuFcbkAhIvKdmLoiVKuyVfDjIGJywTjAA3vogADQwroQAvkowAPSpMAAqYsQQMEEhhLAQmmBQcMgwuTBgOADu8HmemQDKMAAscWQArrDVCPmEhJxVYFltAMwAdADsUwCsfHypAFR8LbEwdRJjAJIwAOasUKzdEHIImjCe4nIACsMYME4QcfsHOLCSw4R5WMQAazkt3OWxylDOxDAB3G0xmAC4loghpx4QAKdoANjiAEYFABKcYAJgmCnm8JgAFkQNxupQAOS0KZTVLM1kstmclkAVXOv1SxAwaFSoG4OFSOAAjt04KkwDScAB9NA0uk4CCpAAChBwcGAUAAtGA4AA3YgHOBQYjgVLQPUA1L-MipF7AEgYKC2wjAWj0mBiOB5eX5YKhHDcGBoHBoMiSGD0lrlYAAgBypvNlutYAeIAw9KmSxWqT4QA)

**Comment by satya164** [comment]
The supported version of TypeScript for `@types/node` is `3.7+`, not `3.7` https://github.com/DefinitelyTyped/DefinitelyTyped/blob/ca4b9d5fe1c8636e565afe5a130883919db9ef60/types/node/v16/index.d.ts#L70. Node 16 types are actively maintained in `DefinitelyTyped` repo which doesn't even support TypeScript versions older than 4.0.

If you get hundreds of type errors in `@types/node` when it's actively maintained and tested against the latest TypeScript versions on DefinitelyTyped, then it sounds like there's a configuration issue on your end.

Besides, Expo itself requires a newer version of TypeScript. And a lot of projects, including this repo, have no errors from `@types/node`. TypeScript 4.1 is almost 2 years old at this point. If you really want to use older versions of tools, you're welcome to keep using React Navigation 5 until you're ready to upgrade.

**Comment by ipmcc** [comment]
It seems that you and the Expo team disagree on this one, since the information I shared about version-locking typescript with the Node version came directly from an extended discord thread with them. Also, just think about it: a newer version of @types/node running against an older version of Node than it was tagged to may reflect additional and changed types that would make it wrong. 

I also see no evidence on [their TypeScript page](https://docs.expo.dev/guides/typescript/) that they require TS 4+.

I guess we'll just keep slogging along until November when we can upgrade all this stuff to the new Node 18 LTS train.

**Comment by satya164** [comment]
> just think about it: a newer version of @types/node running against an older version of Node than it was tagged to may reflect additional and changed types that would make it wrong.

Sure, but DefiniteyTyped tests their types against TS 4+ and types for Node 16 are actively maintained. I'm not sure this tagging process applies equally to LTS releases of Node given that they still exist in the repo and are updated, unlike non-LTS versions.

> I also see no evidence on [their TypeScript page](https://docs.expo.dev/guides/typescript/) that they require TS 4+.

The project generated by Expo uses a newer TS version, running `expo upgrade` changes the TS version in `package.json`, and their monorepo also uses a recent version of TS.
