### ISSUE TITLE
Linking does not navigate

### ISSUE THREAD

**Issue by marlonschlosshauer** [react-navigation/react-navigation#10783]
### Current behavior

I'm trying to implement some basic linking for my App. Open screen X if URL Y etc. I can get the app to open, but no navigation takes place. 
Doesn't make a difference if the app is in the background or foreground. Happens on both iOS (15.0, 13.7) and Android (13).

Here is what I did:
- Create a React Native app with `npx react-native init`
- Follow the [Getting Started](https://reactnavigation.org/docs/getting-started#installation) React Navigation Docs  
- Follow [Enabling Deep Links](https://reactnative.dev/docs/linking#enabling-deep-links) from React Native
- Follow [Set up with bare React Native projects​](https://reactnavigation.org/docs/deep-linking/#set-up-with-bare-react-native-projects) React Navigation docs
- Setup the links with [Configuring links](https://reactnavigation.org/docs/configuring-links)

Here is an excerpt from my [App.js](https://github.com/marlonschlosshauer/react-native-deep-linking-test/blob/main/App.js):

```jsx
const linking = {
  prefix: ['mychat://'],
  config: {
    screens: {
      Profile: 'profile',
      Home: 'home',
      NotFound: '*',
    }
  }
}

const App = () => {
  const Stack = createNativeStackNavigator();
  return (
    <SafeAreaView style={{ flex: 1 }}>
      <NavigationContainer linking={linking}>
        <Stack.Navigator>
          <Stack.Screen name='Home' component={Home} />
          <Stack.Screen name='Profile' component={Profile} />
          <Stack.Screen name='NotFound' component={NotFound} />
        </Stack.Navigator>
      </NavigationContainer>
    </SafeAreaView>
  );
};
```

Each screen just shows its name (e.g `Home` just says `Home`).

I'd now expect ``mychat://profile`` to link to my `Profile` screen.

https://user-images.githubusercontent.com/24259317/185375088-57ccd7f1-ea2a-42b7-a216-d03d40304952.mov

(Here I am navigating to `mychat://profile` with `uri-scheme` and would expect it to say `Profile` instead of `Home`)

I'm using `uri-scheme` for linking:
```shell
npx uri-scheme open "mychat://profile" --ios
```

```shell
npx uri-scheme open "mychat://profile" --android
```

Additional information:
- Turning off the debugger didn't fix it
- `Linking.addEventListener('url', ...)` spits out the `URL`
- Tried some solutions from facebook/react-native#32350 but couldn't find a fix

Is there something I am missing? Having it not work on two projects (with different versions!) makes me think it's an issue beyond React Navigation or React Native, but I'm unsure what could be the cause. Could be related to #10201.

### Expected behavior

I'd expect my app to navigate to the points specified in the `linking` prop. 
So:
- `mychat://profile` should navigate to `Profile`
- `mychat://home` should navigate to `Home`
- etc. 

### Reproduction

https://github.com/marlonschlosshauer/react-native-deep-linking-test

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/​bottom-tabs
- [ ] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [ ] @react-navigation/​stack
- [X] @react-navigation/​native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |^6.0.12
| @react-navigation/native-stack         |^6.7.0
| react-native-safe-area-context         |^4.3.1
| react-native-screens                   |^3.15.0
| react-native                           |0.69.4
| node                                   |v17.8.0
| npm or yarn                            |8.5.5

**Comment by marlonschlosshauer** [comment]
> The versions mentioned in the issue for the following packages differ from the latest versions on npm:
> 
>     * `@react-navigation/native` (found: `6.0.11`, latest: `6.0.12`)
> 
> 
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?

Just updated to `6.0.12` and the problem persists 👍

**Comment by frzkn** [comment]
Hey, @marlonschlosshauer did you find a solution for this yet?

**Comment by marlonschlosshauer** [comment]
> Hey, @marlonschlosshauer did you find a solution for this yet?

No, I haven't found one yet.

**Comment by LucasClaude** [comment]
@frzkn @marlonschlosshauer Any updates here? Thanks!

**Comment by marlonschlosshauer** [comment]
> @frzkn @marlonschlosshauer Any updates here? Thanks!

Nope. I have decided to implement the linking myself, as React Native correctly receives the URL on startup etc.

**Comment by kacperkapusciak** [comment]
Hi @marlonschlosshauer :wave:
I've managed to make your repo work and actually, it was a tiny misconfiguration rather than a bug in react-navigation.

**1.** First, there's a typo in the `linking` configuration. The correct field's name is `prefixes` not `prefix` so it would look like this:

```js
const linking = {
  prefixes: ['mychat://'], // <- typo `prefix` -> `prefixes`
  config: {
    // ...
  },
};
```

TypeScript would catch that 😅 

**2.** Second, a few config lines that need to be added to the `AppDelegate.m` were added in the incorrect place. Rather than putting them in `@interface AppDelegate` they should be in the`@implementation AppDelegate`.

So correct AppDelegate.m in the provided repro would look like:

<details>
<summary>AppDelegate.m</summary>
<br>



```obj-c
// Add deep linking support
#import <React/RCTLinkingManager.h>
#import "AppDelegate.h"

#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>

#import <React/RCTAppSetupUtils.h>

#if RCT_NEW_ARCH_ENABLED
#import <React/CoreModulesPlugins.h>
#import <React/RCTCxxBridgeDelegate.h>
#import <React/RCTFabricSurfaceHostingProxyRootView.h>
#import <React/RCTSurfacePresenter.h>
#import <React/RCTSurfacePresenterBridgeAdapter.h>
#import <ReactCommon/RCTTurboModuleManager.h>

#import <react/config/ReactNativeConfig.h>

static NSString *const kRNConcurrentRoot = @"concurrentRoot";

@interface AppDelegate () <RCTCxxBridgeDelegate, RCTTurboModuleManagerDelegate> {
  RCTTurboModuleManager *_turboModuleManager;
  RCTSurfacePresenterBridgeAdapter *_bridgeAdapter;
  std::shared_ptr<const facebook::react::ReactNativeConfig> _reactNativeConfig;
  facebook::react::ContextContainer::Shared _contextContainer;
}

@end
#endif

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application
   openURL:(NSURL *)url
   options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options
{
  return [RCTLinkingManager application:application openURL:url options:options];
}

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  RCTAppSetupPrepareApp(application);

  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];

#if RCT_NEW_ARCH_ENABLED
  _contextContainer = std::make_shared<facebook::react::ContextContainer const>();
  _reactNativeConfig = std::make_shared<facebook::react::EmptyReactNativeConfig const>();
  _contextContainer->insert("ReactNativeConfig", _reactNativeConfig);
  _bridgeAdapter = [[RCTSurfacePresenterBridgeAdapter alloc] initWithBridge:bridge contextContainer:_contextContainer];
  bridge.surfacePresenter = _bridgeAdapter.surfacePresenter;
#endif

  NSDictionary *initProps = [self prepareInitialProps];
  UIView *rootView = RCTAppSetupDefaultRootView(bridge, @"deeplink", initProps);

  if (@available(iOS 13.0, *)) {
    rootView.backgroundColor = [UIColor systemBackgroundColor];
  } else {
    rootView.backgroundColor = [UIColor whiteColor];
  }

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  return YES;
}

/// This method controls whether the `concurrentRoot`feature of React18 is turned on or off.
///
/// @see: https://reactjs.org/blog/2022/03/29/react-v18.html
/// @note: This requires to be rendering on Fabric (i.e. on the New Architecture).
/// @return: `true` if the `concurrentRoot` feture is enabled. Otherwise, it returns `false`.
- (BOOL)concurrentRootEnabled
{
  // Switch this bool to turn on and off the concurrent root
  return true;
}

- (NSDictionary *)prepareInitialProps
{
  NSMutableDictionary *initProps = [NSMutableDictionary new];

#ifdef RCT_NEW_ARCH_ENABLED
  initProps[kRNConcurrentRoot] = @([self concurrentRootEnabled]);
#endif

  return initProps;
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index"];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

#if RCT_NEW_ARCH_ENABLED

#pragma mark - RCTCxxBridgeDelegate

- (std::unique_ptr<facebook::react::JSExecutorFactory>)jsExecutorFactoryForBridge:(RCTBridge *)bridge
{
  _turboModuleManager = [[RCTTurboModuleManager alloc] initWithBridge:bridge
                                                             delegate:self
                                                            jsInvoker:bridge.jsCallInvoker];
  return RCTAppSetupDefaultJsExecutorFactory(bridge, _turboModuleManager);
}

#pragma mark RCTTurboModuleManagerDelegate

- (Class)getModuleClassFromName:(const char *)name
{
  return RCTCoreModulesClassProvider(name);
}

- (std::shared_ptr<facebook::react::TurboModule>)getTurboModule:(const std::string &)name
                                                      jsInvoker:(std::shared_ptr<facebook::react::CallInvoker>)jsInvoker
{
  return nullptr;
}

- (std::shared_ptr<facebook::react::TurboModule>)getTurboModule:(const std::string &)name
                                                     initParams:
                                                         (const facebook::react::ObjCTurboModule::InitParams &)params
{
  return nullptr;
}

- (id<RCTTurboModule>)getModuleInstanceFromClass:(Class)moduleClass
{
  return RCTAppSetupDefaultModuleFromClass(moduleClass);
}

#endif

@end


```

</details>

See that these RCTLinking configuration lines

```obj-c
- (BOOL)application:(UIApplication *)application
   openURL:(NSURL *)url
   options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options
{
  return [RCTLinkingManager application:application openURL:url options:options];
}
```

are inside of the `@implementation AppDelegate`. In the past versions of `react-native` the `AppDelegate` was way simpler (didn't have the `@interface AppDelegate` at all) and we do have to adjust the documentation to make it clearer where to put these lines.

**3.** After these changes the deep-linking is working again 😊 

https://user-images.githubusercontent.com/39658211/190372302-6b5af920-9735-4ec5-81af-bb3521d1ebc7.mov

(yes, it also works on Android)

**Comment by marlonschlosshauer** [comment]
> I've managed to make your repo work and actually, it was a tiny misconfiguration rather than a bug in react-navigation.

You're a godsend! Thank you so much! (Obviously) works with these "fixes" on my end, too! 🎉

**Comment by thongle12** [comment]
Hi @kacperkapusciak @marlonschlosshauer , 
If I use Linking.openURL('mychat://Home'); on the onPress of the RN button
Can I navigate to the Home screen?

**Comment by youngjuning** [comment]
How to set in 0.77 for ios
