### ISSUE TITLE
Custom Native Stack Navigator broken in v6.8.0

### ISSUE THREAD

**Issue by shobhitsinghal624** [react-navigation/react-navigation#10791]
### Current behavior

The custom native stack navigator gives this error after upgrading `@react-navigation/​native-stack` to `v6.8.0`.
```
ERROR  Error: Couldn't find the prevent remove context. Is your component inside NavigationContent?
```
I have reproduced it in this minimal snack:
https://snack.expo.dev/@shobhitsinghal624/custom-react-navigation-navigator?platform=android

Most likely it is related to this PR: https://github.com/react-navigation/react-navigation/pull/10682

Screenshot:
<img width="314" alt="Screenshot 2022-08-27 at 12 59 39 PM" src="https://user-images.githubusercontent.com/4579093/187020139-496e030b-c9b7-430c-8c32-3f5bfa539f0f.png">

### Expected behavior

There should be no error. Downgrading `@react-navigation/​native-stack` to `v6.7.0` fixes the issue.

### Reproduction

https://snack.expo.dev/@shobhitsinghal624/custom-react-navigation-navigator?platform=android

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/​bottom-tabs
- [ ] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [ ] @react-navigation/​stack
- [X] @react-navigation/​native-stack

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.0.12 |
| @react-navigation/native-stack         |  6.8.0 |
| react-native-safe-area-context         | 4.3.3 |
| react-native-screens                   | 3.17.0 |
| react-native                           | 6.8.3

**Comment by satya164** [comment]
Custom navigators need to wrap their content in `NavigationContent`: https://reactnavigation.org/docs/custom-navigators/#api-for-building-custom-navigators

Looks like it's missing from the "Extending Navigators" section. Can you send a PR to the documentation to add it?
