### ISSUE TITLE
Header bar is overlapping any view 

### ISSUE THREAD

**Issue by SectionTN** [react-navigation/react-navigation#10796]
### Current behavior

![Screenshot_20220827-122826_Moon Meet](https://user-images.githubusercontent.com/73752904/187028613-79f06b14-8b05-44dd-be9e-97c9d93a443e.png)
![Screenshot_20220827-124029_Moon Meet](https://user-images.githubusercontent.com/73752904/187028628-f39a9a9a-d4e5-4a44-b9d9-34afbd304f0d.png)

### Expected behavior

![Screenshot_20220827-122928_Moon Meet](https://user-images.githubusercontent.com/73752904/187028295-f285bcdb-c98a-4203-9a85-ae51d3515cf8.png)

It should look something like that

### Reproduction

https://github.com/MoonMeet/MoonMeet-CrossPlatform/blob/ce84dd143d21d5bf67f0de6de0ea01d150784cd6/src/config/Stack.js#L165

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/​bottom-tabs
- [ ] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [X] @react-navigation/​stack
- [X] @react-navigation/​native-stack

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | -------
| @react-navigation/material-bottom-tabs | 6.2.3
| @react-navigation/stack                | 6.2.3
| @react-navigation/native-stack         | 6.8.0
| @react-navigation/native                   | 6.0.12
| react-native-safe-area-context         | 4.3.3
| react-native-screens                   | 3.17.0
| react-native-gesture-handler           | 2.6.0
| react-native-                                    | 0.69.5
| react-native-pager-view                | 5.4.25
| react                                             | 18.0.0
| node                                   | 18 LTS
| npm or yarn                            | yarn latest

**Comment by SectionTN** [comment]
i have provided a link of repo not under my username, it's under my GitHub organization name

**Comment by SectionTN** [comment]
any news?

**Comment by raajnadar** [comment]
You need to provide a minimal runnable code reproducing the issue, so that we can confirm the bug is in the library and not due to your code

**Comment by SectionTN** [comment]
See here, i have already provided.
https://github.com/MoonMeet/MoonMeet-CrossPlatform/blob/ce84dd143d21d5bf67f0de6de0ea01d150784cd6/src/config/Stack.js#L165

**Comment by raajnadar** [comment]
This is not minimal, you cannot expect others to scan your repository and find the bug

https://stackoverflow.com/help/minimal-reproducible-example

**Comment by BerkeAras** [comment]
Same issue. @SectionTN Did you find any solution?

**Comment by SectionTN** [comment]
disable layoutAnimation in index.js
