### ISSUE TITLE
Typescript issues in latest releases.

### ISSUE THREAD

**Issue by Saikedo** [react-navigation/react-navigation#10802]
### Current behavior

I started experiencing some typescript issues with the library. Take a look at the following scenario.

So let`s say I have a stack navigator that looks something like this (
```
type RootStackParamList = {
    Home: undefined
    Login: undefined
    MemberDashboard: NavigatorScreenParams<MemberDashboarDrawerParamList>
    ...
};

const Stack = createNativeStackNavigator<RootStackParamList>();
```

And MemberDashboard here is another navigator where `MemberDashboarDrawerParamList` looks something like this.

```
type MemberDashboarDrawerParamList = {
  MemberDashboardHome: undefined;
  ...
};
```

So I started getting few types of errors and here are some.

First, when I do `navigation.navigate` somewhere with a screen name that is determined at runtime, I used to be able to do something like this.

// Ofcorse here I have some guarantees that someScreenName will actually always be a key of RootStackParamList.
`navigation.navigate(someScreenName as keyof RootStackParamList);`

This used to work just fine but lately, it started throwing TS error saying 

`Argument of type '[string | number | symbol]' is not assignable to parameter of type '[screen: "Home"] |...`

Another issue is this.

I have router related props declaration for all screens that do not have any extra params that looks like this

```
type UniversalScreenRouteProp = RouteProp<RootStackParamList>;
export type UniversalScreenNavigationProp = NativeStackNavigationProp<RootStackParamList>;

export type UniversalProps = {
  route: UniversalScreenRouteProp;
  navigation: UniversalScreenNavigationProp;
};
```

and is used like this for example.

```
const MemberDashboardHome = ({ navigation }: UniversalProps) => {
   ...
```

But when I try to use this screen in my nested MemberDashboard navigator like this

`<Drawer.Screen name="MemberDashboardHome" component={MemberDashboardHome} />`

It used to work but now it is throwing an error saying 

```
Type '({ navigation }: UniversalProps) => JSX.Element' is not assignable to type 'ScreenComponentType<MemberDashboarDrawerParamList, "MemberDashboardHome"> | undefined'.
  Type '({ navigation }: UniversalProps) => JSX.Element' is not assignable to type 'FunctionComponent<{}>'.
    Types of parameters '__0' and 'props' are incompatible.
      Type '{ children?: ReactNode; }' is missing the following properties from type 'UniversalProps': route, navigationts(2322)
```

Did something major change in react-navigation types? Am I handling these wrong?

NOTE: I provided a sample repo mimicking some of the code that we have in our project but I was unable to make TS work properly in expo snack so please keep that in mind.

### Expected behavior

Expected types to work as they used to.

### Reproduction

https://snack.expo.dev/@saikedo/carefree-pretzels

### Platform

- [X] Android
- [X] iOS
- [X] Web
- [X] Windows
- [X] MacOS

### Packages

- [ ] @react-navigation/​bottom-tabs
- [X] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [ ] @react-navigation/​stack
- [X] @react-navigation/​native-stack

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.0.12
| @react-navigation/drawer               | 6.4.4
| @react-navigation/native-stack         | 6.8.0
| react-native-safe-area-context         | 4.3.3
| react-native-screens                   | 3.17.0
| react-native-gesture-handler           | 2.6.0
| react-native-reanimated                | 2.10.0
| react-native                           | 0.68.2
| node                                   | 18.6.0
| npm or yarn                            | 8.13.2

**Comment by har0ld-scl** [comment]
Hi! I've been running the same problems with my app. 

I've found that the typing definitions introduced in `@react-navigation/core: 6.3.0` are causing the conflicts. My temporal fix was keep using the previous version (`@react-navigation/core: 6.2.2`) of that dependency manually specifying it in all my project's package.json files.

Additionally i'm using the following react navigation packages:
```json
"@react-navigation/bottom-tabs": "6.2.0",
"@react-navigation/native": "6.0.8",
"@react-navigation/stack": "6.2.1",
```

**Comment by gewfy** [comment]
Not a great at TypeScript to be honest. But we have the same issue, where we basically define route name constants based on screen prop defintions...

https://github.com/29ki/29k/blob/4854d0b7a370ce5fa63b66496a8c61e36ccd028b/client/src/common/constants/routes.ts#L1-L24

... and where it now struggles with type checking navigations
```
  Argument of type '[keyof ScreenProps]' is not assignable to parameter of type '[screen: "Home"] | [screen: "Home", params: undefined] | [screen: "Profile"] | [screen: "Profile", params: undefined] | [screen: "KillSwitch"] | [screen: "KillSwitch", params: undefined] | [screen: "Tabs"] | [screen: "Tabs", params: undefined] | [screen: "Breathing"] | [screen: "Breathing", params: undefined] | [scr...'.
    Type '[keyof ScreenProps]' is not assignable to type '[screen: "Temples", params: undefined]'.
      Source has 1 element(s) but target requires 2.
  Overload 2 of 2, '(options: { key: string; params?: undefined; merge?: boolean | undefined; } | { name: "Home"; key?: string | undefined; params: undefined; merge?: boolean | undefined; } | { key: string; params?: undefined; merge?: boolean | undefined; } | ... 10 more ... | { ...; }): void', gave the following error.
    Argument of type 'string' is not assignable to parameter of type '{ key: string; params?: undefined; merge?: boolean | undefined; } | { name: "Home"; key?: string | undefined; params: undefined; merge?: boolean | undefined; } | { key: string; params?: undefined; merge?: boolean | undefined; } | ... 10 more ... | { ...; }'.
      Type 'string' is not assignable to type '{ key: string; params?: undefined; merge?: boolean | undefined; } | { name: "Home"; key?: string | undefined; params: undefined; merge?: boolean | undefined; } | { key: string; params?: undefined; merge?: boolean | undefined; } | ... 10 more ... | { ...; }'.

85         <Button onPress={() => navigate(ROUTES.BREATHING)} primary>
                                           ~~~~~~~~~~~~~~~~
```

Caused by #10519 ?

As mentioned ⬆️ downgrading to `@react-navigation/core@6.2.2` solves it.

**Comment by shawnp84** [comment]
@gewfy I believe you're right that the issue stems from that commit, but it seems like that commit is actually catching something that could have been incorrect. I'm guessing for you the `ScreenProps` has some routes with different parameter definitions? That's what it was for me. `navigate` now verifies the param list against the type and since the only thing it knows is that its a type of `keyof ScreenProps` then it can't verify that the parameter list is correct. For me I changed my return type on my method from `keyof ParamList` to `'validRouteName1' | 'validRouteName2'` and it resolved the issue by filtering out the route options with a different parameter list. It's pretty kludgy and awkward to work with so hopefully someone has a better solution.

**Comment by gkpo** [comment]
Same issue here :/

**Comment by danweav1** [comment]
Also seeing issue. It is thinking my redux props need to be a part of the screen params.

**Comment by rarenatoe** [comment]
shameless bump of the month. Experimenting this too

**Comment by rarenatoe** [comment]
I was experimenting this too.

My issue was that it wasn't using the same type for the Stack, rather an alternate subset type. Even though technically that's fine. I'm glad it's stricter.

**Comment by FrancescoBonizzi** [comment]
> I was experimenting this too.
> 
> 
> 
> My issue was that it wasn't using the same type for the Stack, rather an alternate subset type. Even though technically that's fine. I'm glad it's stricter.

Same problem here, can you please explain in detail how did you fix? Thanks a lot.

**Comment by rarenatoe** [comment]
@FrancescoBonizzi

## The problem
Say I have the following **PSEUDOCODE**:
```ts
// types.ts
export type MyStackParamList = { HomeScreen: undefined, ContactsScreen: { name: string; phone: number } }
```
```ts
// MyStack.ts
import { createStackNavigator } from '@react-navigation/stack' 
import ContactsScreen from './ContactsScreen'
import { MyStackParamList } from './types'

const Stack = createStackNavigator<MyStackParamList>()
const MyStack = () => {
  return (
    <Stack.Navigator initialRouteName="HomeScreen">
      <Stack.Screen
        component={HomeScreen}
        name="HomeScreen"
      />
      <Stack.Screen
        component={ContactsScreen} // <---- error here
        name="ContactsScreen"
      />
    </Stack.Navigator>
)
```
```tsx
// ContactsScreen.tsx
import React from 'react'
import { StackScreenProps } from '@react-navigation/stack'

// This incomplete alternate type, causes the error in MyStack.ts
type MeeStackParamList = {
  ContactsScreen: { name: string, phone: number }
}

const ContactsScreen = (props: StackScreenProps<MeeStackParamList, 'ContactsScreen'>) => {
  return (
    ... 
  )
}

export default ContactsScreen
```

## The solution

```tsx
// ContactsScreen.tsx
import React from 'react'
import { StackScreenProps } from '@react-navigation/stack'
import { MyStackParamList } from './types'

const ContactsScreen = (props: StackScreenProps<MyStackParamList, 'ContactsScreen'>) => {
  return (
    ...
  )
}

export default ContactsScreen
```

**Comment by kylebake** [comment]
The above example is a bit over simplified for the issue called out in the OP, as well as the issue our team is running into. It seems that generic/dynamic navigation keys are where things start to break down. It's hard to tell if it's a misunderstanding of configuration or if its a bug somewhere in the library. 

Previously all of our generic types were working just fine in our project, but upgrading `@react-navigation/core` to anything above `6.2.2` starts throwing errors where we dynamically type our navigation keys. I reproduced this in a very [small react-native project here](https://github.com/kylebake/ReactNavigationTypeTest). Again, this is an oversimplified setup of our project, but we do something similar: setup some components + hooks to call navigate with dynamic generic keys + props. 

In my repo, the type errors will occur in the `NavButton` component, see screenshot:

<img width="1246" alt="Screen Shot 2022-10-20 at 2 37 36 PM" src="https://user-images.githubusercontent.com/13351403/197031350-7c74b1ff-df04-452d-a93f-98320b252238.png">

From what I can tell, everything is annotated as according to the documentation so I'm unsure as to why we seemingly can't use generics with the `navigate` call anymore. Happy to break this out into a separate issue if it's off-topic here.

**Comment by sterlingwes** [comment]
No downgrade needed, [patch-package](https://www.npmjs.com/package/patch-package) to the rescue:

```diff
diff --git a/node_modules/@react-navigation/core/lib/typescript/src/types.d.ts b/node_modules/@react-navigation/core/lib/typescript/src/types.d.ts
index a116b25..621590c 100644
--- a/node_modules/@react-navigation/core/lib/typescript/src/types.d.ts
+++ b/node_modules/@react-navigation/core/lib/typescript/src/types.d.ts
@@ -142,22 +142,22 @@ declare type NavigationHelpersCommon<ParamList extends ParamListBase, State exte
      * @param name Name of the route to navigate to.
      * @param [params] Params object for the route.
      */
-    navigate<RouteName extends keyof ParamList>(...args: RouteName extends unknown ? undefined extends ParamList[RouteName] ? [screen: RouteName] | [screen: RouteName, params: ParamList[RouteName]] : [screen: RouteName, params: ParamList[RouteName]] : never): void;
+    navigate<RouteName extends keyof ParamList>(...args: undefined extends ParamList[RouteName]
+        ? [screen: RouteName] | [screen: RouteName, params: ParamList[RouteName]]
+        : [screen: RouteName, params: ParamList[RouteName]]): void;
     /**
      * Navigate to a route in current navigation tree.
      *
      * @param route Object with `key` or `name` for the route to navigate to, and a `params` object.
      */
-    navigate<RouteName extends keyof ParamList>(options: RouteName extends unknown ? {
-        key: string;
-        params?: ParamList[RouteName];
-        merge?: boolean;
-    } | {
-        name: RouteName;
-        key?: string;
-        params: ParamList[RouteName];
-        merge?: boolean;
-    } : never): void;
+    navigate<RouteName extends keyof ParamList>(options:
+        | { key: string; params?: ParamList[RouteName]; merge?: boolean }
+        | {
+            name: RouteName;
+            key?: string;
+            params: ParamList[RouteName];
+            merge?: boolean;
+          }): void;
     /**
      * Reset the navigation state to the provided state.
      *
@@ -324,14 +324,14 @@ export declare type RouteConfigComponent<ParamList extends ParamListBase, RouteN
     /**
      * React component to render for this screen.
      */
-    component: ScreenComponentType<ParamList, RouteName>;
+    component: React.ComponentType<any>;
     getComponent?: never;
     children?: never;
 } | {
     /**
      * Lazily get a React component to render for this screen.
      */
-    getComponent: () => ScreenComponentType<ParamList, RouteName>;
+    getComponent: () => React.ComponentType<any>;
     component?: never;
     children?: never;
 } | {

```

(the strict types seem nice, just very hairy for us to fix at the moment so it's in the backlog...)

**Comment by AlkanV** [comment]
for complete implementation for a screen with react-navigation 6.0 please take a look at the below code example: 

TYPE DEFINITIONS: 

```
import {NativeStackScreenProps} from '@react-navigation/native-stack';

export type RootStackParamList = {
  Home: undefined;
  Splash: undefined;
};
export type DefaultNavigationProps<T extends keyof RootStackParamList> =
  NativeStackScreenProps<RootStackParamList, T>;

```

SCREEN IMPLEMENTATION: 
```
const Home: React.FC<
  NativeStackScreenProps<DefaultNavigationProps<'Home'>>
> = ({navigation}) => {
  return (
    <>
      <StatusBar barStyle="dark-content" backgroundColor="transparent" />
      <View style={styles.container}>
        <Text> HOME SCREEN</Text>
      </View>
    </>
  );
};
```

NAVIGATOR CREATION: 

```
    <Stack.Navigator
      screenOptions={() => ({
        headerRight: undefined,
        headerTitle: () => 'Title',
        headerTitleAlign: 'center',
        presentation: 'card',
      })}>
      <Stack.Screen name="Home" component={Home} />
    </Stack.Navigator>
```

**Comment by SmartArray** [comment]
Everything works fine for me, except when I try to call .reset() on an navigation instance.

Example: 
```
// Reset back to root
navigation.reset({
  index: 0,
  routes: [{ name: 'RootScreen', params: {...; }}],
});
```

yields the following typescript errros:

```
Argument of type '{ index: number; routes: { name: string; params: { ...; }; }[]; }' is not assignable to parameter of type 'NativeStackNavigationOptions | PartialState<NativeStackNavigationOptions>'.
  Object literal may only specify known properties, and 'index' does not exist in type 'NativeStackNavigationOptions | PartialState<NativeStackNavigationOptions>'.
```

However, the code works fine and doesn't cause any crashes.

By the way, for us, the `declare global` namespace definition worked flawlessly. Every call to `.navigate()` gets validated properly. We had convert the type for over 50 screens, but I am glad things worked out

**Comment by darkadept** [comment]
I'm seeing a strange issue with these types. I'm trying @AlkanV's v6.0 example.

You define `DefaultNavigationProps` like this (in TYPE DEFINITIONS):

`export type DefaultNavigationProps<T extends keyof RootStackParamList> = NativeStackScreenProps<RootStackParamList, T>;`

In your SCREEN IMPLEMENTATION section the props to the function component are this:

`NativeStackScreenProps<DefaultNavigationProps<'Home'>`

which is essentially this:

`NativeStackScreenProps<NativeStackScreenProps<RootStackParamList, 'Home'>>`

First of all, that seems odd and second of all I'm getting issues with using `navigation.navigate()` in my screen components.

I like to define my screen components like this, which should be the same as using React.FC:

```
export function Home({navigation}: NativeStackScreenProps<DefaultNavigationProps<'Home'>>) {
  return (
    <>
      <StatusBar barStyle="dark-content" backgroundColor="transparent" />
      <View style={styles.container}>
        <Text> HOME SCREEN</Text>
        <Button onPress={() => {
          navigation.navigate('Splash');  // This causes a typescript error.
        }>Go to Splash</Button
      </View>
    </>
  );
}
```

I get a TS2769 error "No overload matches this call" in the `navigation.navigate()` call.

---

So then I tried changing the props type to my `Home` component to this:

```
export function Home({navigation}: DefaultNavigationProps<'Home'>) {
```

This fixes my `navigation.navigate()` call and the typescript works!

Except now there is a typescript error in my NAVIGATOR CREATION file. It doesn't like the `component` prop. (TS2322 error)

```
  <Stack.Screen name="Home" component={Home} />
```

Then I checked how I was creating my `Stack` constant: `const Stack = createNativeStackNavigator();`. I changed it to this:

```
const Stack = createNativeStackNavigator<RootStackParamList>();
```

And now typescript seems to be satisfied.

One thing though... I don't like that I can't dynamically create navigation routes (code works, typescript doesn't)... but I guess that's just life with Typescript.

**Comment by Kaijonsson** [comment]
> I'm seeing a strange issue with these types. I'm trying @AlkanV's v6.0 example.
> 
> You define `DefaultNavigationProps` like this (in TYPE DEFINITIONS):
> 
> `export type DefaultNavigationProps<T extends keyof RootStackParamList> = NativeStackScreenProps<RootStackParamList, T>;`
> 
> In your SCREEN IMPLEMENTATION section the props to the function component are this:
> 
> `NativeStackScreenProps<DefaultNavigationProps<'Home'>`
> 
> which is essentially this:
> 
> `NativeStackScreenProps<NativeStackScreenProps<RootStackParamList, 'Home'>>`
> 
> First of all, that seems odd and second of all I'm getting issues with using `navigation.navigate()` in my screen components.
> 
> I like to define my screen components like this, which should be the same as using React.FC:
> 
> ```
> export function Home({navigation}: NativeStackScreenProps<DefaultNavigationProps<'Home'>>) {
>   return (
>     <>
>       <StatusBar barStyle="dark-content" backgroundColor="transparent" />
>       <View style={styles.container}>
>         <Text> HOME SCREEN</Text>
>         <Button onPress={() => {
>           navigation.navigate('Splash');  // This causes a typescript error.
>         }>Go to Splash</Button
>       </View>
>     </>
>   );
> }
> ```
> 
> I get a TS2769 error "No overload matches this call" in the `navigation.navigate()` call.
> 
> So then I tried changing the props type to my `Home` component to this:
> 
> ```
> export function Home({navigation}: DefaultNavigationProps<'Home'>) {
> ```
> 
> This fixes my `navigation.navigate()` call and the typescript works!
> 
> Except now there is a typescript error in my NAVIGATOR CREATION file. It doesn't like the `component` prop. (TS2322 error)
> 
> ```
>   <Stack.Screen name="Home" component={Home} />
> ```
> 
> Then I checked how I was creating my `Stack` constant: `const Stack = createNativeStackNavigator();`. I changed it to this:
> 
> ```
> const Stack = createNativeStackNavigator<RootStackParamList>();
> ```
> 
> And now typescript seems to be satisfied.
> 
> One thing though... I don't like that I can't dynamically create navigation routes (code works, typescript doesn't)... but I guess that's just life with Typescript.

I Agree 100% to this post. Typeing the stack creation fixed the same issue for me and i also read the documentation from react navigation the same way. In other words my implementation is the same. 

Perhaps typeing the stack creation is missing from the documentation on implementing a TS-based react navigation?

Thanks for the answer! This has been a source of 100 git-ignores and TODO:s on my end :)

**Comment by erquhart** [comment]
Thanks @darkadept I had a `createNativeStackNavigator()` call that I had forgotten to pass the param list to 👍 

Note this seems to work fine in Typescript using the latest versions of react navigation.

**Comment by shrekuu** [comment]
## Here is my solution:

This is my screen file:
```ts
import { NativeStackScreenProps } from '@react-navigation/native-stack';
import { RootStackParamList } from '@/types';

export default function ItemDetailScreen({

 //  I do this:
  route,

  //  Or I do this:
  //   route: {params: { id, name }}

}: NativeStackScreenProps<RootStackParamList, 'ItemDetailScreen'>) {

const {id, name} = route.params

// ...
```

In my type.ts file, I have:
```ts
export type RootStackParamList = {
ItemDetailScreen: { id: number; name: string };
// ...
```

**Comment by byronthe123** [comment]
@Kaijonsson thanks for this solution - solved my errors as well.

**Comment by Th0mYT** [comment]
This fix for me the problem.

Before:

`const Stack = createNativeStackNavigator();
`

After

`const Stack = createNativeStackNavigator<RootNativeStackParamList>();`

Ty @Kaijonsson

**Comment by victorcrbt** [comment]
> Hi! I've been running the same problems with my app.
> 
> I've found that the typing definitions introduced in `@react-navigation/core: 6.3.0` are causing the conflicts. My temporal fix was keep using the previous version (`@react-navigation/core: 6.2.2`) of that dependency manually specifying it in all my project's package.json files.
> 
> Additionally i'm using the following react navigation packages:
> 
> ```json
> "@react-navigation/bottom-tabs": "6.2.0",
> "@react-navigation/native": "6.0.8",
> "@react-navigation/stack": "6.2.1",
> ```

More than six months later and this was the only solution that worked for me. It was already driving me insane thinking that I was doing something wrong or it wasn't possible to achieve what I was trying to do.

Thanks for sharing this!

**Comment by airowe** [comment]
I'm still seeing this. Anyone else?

**Comment by Th0mYT** [comment]
> I'm still seeing this. Anyone else?

Have you tried specifying the type?

**Comment by angelica-snowit** [comment]
> I'm still seeing this. Anyone else?

Not with these versions:
```
"@react-navigation/bottom-tabs": "^6.5.7",
"@react-navigation/native": "^6.1.6",
"@react-navigation/native-stack": "^6.9.12",
"react": "18.2.0",
"react-native": "0.71.6",
```

**Comment by airowe** [comment]
> > I'm still seeing this. Anyone else?
> 
> Have you tried specifying the type?

Yes, I have specified a type but it conflicts with my deep linking config unfortunately. I only have one RootStackParamList type though. I'll attempt to create a type for each stack that is nested in a tab in my app.

**Comment by smalomo** [comment]
>>I'm still seeing this. Anyone else?

>Not with these versions:
>
```
"@react-navigation/bottom-tabs": "^6.5.7",
"@react-navigation/native": "^6.1.6",
"@react-navigation/native-stack": "^6.9.12",
"react": "18.2.0",
"react-native": "0.71.6",
```

I just upgraded to these versions and I'm still seeing the TS error when using `useNavigation()`

**Comment by kenobi91** [comment]
Can this be reopened, I still have this issue and nothing that i try is fixing it.

**Comment by Th0mYT** [comment]
https://github.com/react-navigation/react-navigation/issues/10802#issuecomment-1505230482

**Comment by kenobi91** [comment]
If I completely remove the navigation code from the app, it still fails because the error is inside the node_modules.

**Comment by Th0mYT** [comment]
> > [#10802 (comment)](https://github.com/react-navigation/react-navigation/issues/10802#issuecomment-1505230482)
> 
> > 
> 
> > Try this [#10802 (comment)](https://github.com/react-navigation/react-navigation/issues/10802#issuecomment-1378770685)
> 
> 
> 
> I've tried and don't work.

Which version of the library you are using? I'm not now on the project where I encountered the issue. I think that something is changed right now and for this reason you are not able to fix it.

**Comment by MiroslavPetrik** [comment]
I'm getting the same error as originally mentioned:

```
Type '... my type ...=> Element' is not assignable to type '(props any, deprecatedLegacyContext? any) => ReactNode'.
      Types of parameters '__0' and 'props' are incompatible.
        Type 'any' is not assignable to type 'never'.
```
which is accompanied by
```
 Its type '....type... => Element' is not a valid JSX element type.
 ``` 
Here its [in full](https://github.com/form-atoms/field/actions/runs/7069627434/job/19245496095?pr=54#step:7:53).

Strange thing is that there is no code nor dependency change. The code works, when installed with `yarn` package manager, which I have in the `main` branch. The error is from PR where I'm rolling to `npm`. Guess I will stay on yarn a bit.

Just my 2 cents, that maybe types are all right, only resolving process maybe fails?

**Comment by crossjs** [comment]
I'm getting the same error:
```
Type '({ children, rows, columns, ...props }: GridRendererProps) => Element' is not assignable to type 'DecoRenderer'.
  Types of parameters '__0' and 'props' are incompatible.
    Type '{ children?: ReactNode; }' is missing the following properties from type 'GridRendererProps': rows, columnsts(2322)
```

Here is the DecoRenderer definition:
```ts
export interface DecoRendererProps extends PropsWithChildren<any> {}

export type DecoRenderer = (props: DecoRendererProps) => JSX.Element;
```

Changing `PropsWithChildren` to `PropsWithChildren<any>` solves the issue.

**Comment by camboYY** [comment]
Type 'string' is not assignable to type 'never'.

**Comment by boutamente-abdessamad** [comment]
You need to do this and don't forget to make params optional 

//ViewReceipt screen 

```
import { View, Text } from 'react-native'
import React from 'react'
import { NavigationProp, RouteProp } from '@react-navigation/native';

type RootStackParamList = {
  ViewReceipt: { receiptId: string };
};

type Props = {
  navigation?: NavigationProp<RootStackParamList, 'ViewReceipt'>;
  route?: RouteProp<RootStackParamList, 'ViewReceipt'>;
};


const ViewReceipt = ({ navigation, route }: Props) => {

  return (
    <View>
      <Text>ViewReceipt</Text>
    </View>
  )
}

export default ViewReceipt
```

```
 <Tabs.Screen 
          name="ViewReceipt" 
          component={ViewReceipt}
        />
```
