### ISSUE TITLE
I got slow performance when i press tabbar to switch the content with large list. it's very lags

### ISSUE THREAD

**Issue by Mr-Rith** [react-navigation/react-navigation#10800]
### Current behavior

  <Tab.Navigator tabBar={props => <MyTabBar {...props} />}>
        <Tab.Screen
          name={all}
          children={() => <ChildTransaction press={onOpen} />}
        />
        <Tab.Screen
          name={incoming}
          children={() => <ChildTransaction press={onOpen} />}
        />
        <Tab.Screen
          name={outgoing}
          children={() => <ChildTransaction press={onOpen} />}
        />
      </Tab.Navigator>

### Expected behavior

i want to make it faster when i switch between tab 

### Reproduction

no repo

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/​bottom-tabs
- [ ] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [X] @react-navigation/​material-top-tabs
- [ ] @react-navigation/​stack
- [ ] @react-navigation/​native-stack

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |
| @react-navigation/bottom-tabs          |
| @react-navigation/drawer               |
| @react-navigation/material-bottom-tabs |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                |
| @react-navigation/native-stack         |
| react-native-safe-area-context         |
| react-native-screens                   |
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           |
| expo                                   |
| node                                   |
| npm or yarn                            |

**Comment by Jamal-ReachFirst** [comment]
This issue must be reopened

**Comment by Jamal-ReachFirst** [comment]
#10858 

Need your attention

**Comment by Jamal-ReachFirst** [comment]
#11047
