### ISSUE TITLE
Order of hooks violation

### ISSUE THREAD

**Issue by jahglow** [react-navigation/react-navigation#10812]
### Current behavior

```
ERROR  Warning: React has detected a change in the order of Hooks called by HeaderConfig. This will lead to bugs and errors if not fixed. For more information, read the Rules of Hooks: https://reactjs.org/link/rules-of-hooks

   Previous render            Next render
   ------------------------------------------------------
1. useContext                 useContext
2. useContext                 useContext
3. useContext                 useContext
4. useReducer                 useReducer
5. useEffect                  useEffect
6. useEffect                  useEffect
7. useDebugValue              useDebugValue
8. useContext                 useContext
9. useReducer                 useReducer
10. useEffect                 useEffect
11. useEffect                 useEffect
12. useDebugValue             useDebugValue
13. useContext                useContext
14. useReducer                useReducer
15. useEffect                 useEffect
16. useEffect                 useEffect
17. useDebugValue             useDebugValue
18. useContext                useContext
19. useCallback               useCallback
20. useCallback               useCallback
21. useContext                useContext
22. useCallback               useContext
   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    in HeaderConfig (created by SceneView)
    in RNSScreen (at createAnimatedComponent.js:211)
    in AnimatedComponent (at createAnimatedComponent.js:264)
    in AnimatedComponentWrapper (created by Screen)
    in MaybeFreeze (created by Screen)
    in Screen (created by SceneView)
    in SceneView (created by NativeStackViewInner)
    in RNSScreenStack (created by ScreenStack)
    in ScreenStack (created by NativeStackViewInner)
    in NativeStackViewInner (created by NativeStackView)
    in RCTView (at View.js:32)
    in View (created by SafeAreaInsetsContext)
    in SafeAreaProviderCompat (created by NativeStackView)
    in NativeStackView (created by NativeStackNavigator)
```
I render a native-stack screen with a custom headerRight in options as so:
```jsx
export const screenOptions = (): ScreenOptionsReturn => ({
  headerRight: AddButton,
  animation: 'slide_from_right',
  presentation: 'fullScreenModal',
});

// ...
<SettingsStack.Screen name="envs" component={Envs} options={envsScreenOptions} />
``` 
When my condition changes in an effect I setOptions like so:
```ts
  useEffect(() => {
    // remove `headerRight` when 
    if (shouldRemoveButton) {
      setOptions({
        headerRight: undefined,
      });
    } else {
      setOptions(screenOptions());
    }
  }, [shouldRemoveButton, setOptions]);
```

### Expected behavior

the button should disappear

### Reproduction

none

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/​bottom-tabs
- [ ] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [ ] @react-navigation/​stack
- [X] @react-navigation/​native-stack

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |"6.0.11"
| @react-navigation/drawer               |"6.4.3"
| @react-navigation/material-top-tabs    |"6.2.2"
| @react-navigation/native-stack         |"^6.7.0"
| react-native-safe-area-context         |"^4.3.1"
| react-native-screens                   |"3.15.0"
| react-native-gesture-handler           |"2.5.0"
| react-native-reanimated                |"2.9.1"
| react-native-tab-view                  |"3.1.1"
| react-native-pager-view                |5.4.25"
| react-native                           |"0.69.3"
| node                                   |v16.13.2
| npm or yarn                            |v1.22.17

**Comment by jahglow** [comment]
Yes, the issue still exists on latest versions

**Comment by raajnadar** [comment]
This doesn’t seem to be an issue with the library

https://reactjs.org/docs/hooks-rules.html#explanation

Closing as you did provide any repro as well

**Comment by hbriese** [comment]
@jahglow see #8463
