### ISSUE TITLE
Ios Drawer Navigation is not working properly when drawerPosition: 'right'

### ISSUE THREAD

**Issue by dhruvpvx** [react-navigation/react-navigation#10829]
### Current behavior

When drawer is positioned right side and if I open camera then if the camera is closed without capturing photo some part of the drawer remains unclosed and it can only be fixed after killing the app

uploaded image is from simulator but this isssue is causing mostly in real device when opening or closing the camera

https://user-images.githubusercontent.com/59329978/189084519-21565a5c-64df-47bd-a42c-9e589454a03a.mp4

![Simulator Screen Shot - iPhone 13 - 2022-09-08 at 14 44 36](https://user-images.githubusercontent.com/59329978/189084557-cceaf977-b651-4946-a595-716149cec59a.png)

### Expected behavior

the drawer should close completely even if opening any type of feature

### Reproduction

nolink

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/​bottom-tabs
- [X] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [ ] @react-navigation/​stack
- [ ] @react-navigation/​native-stack

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |
| @react-navigation/drawer               |
| @react-navigation/stack                |
| @react-navigation/native-stack         |
| react-native-safe-area-context         |
| react-native-screens                   |
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native                           |
| node                                   |
| npm or yarn                            |

**Comment by joshbuchea** [comment]
We ran into this issue at my job recently. I'm not sure if this is the best solution, but we were ultimately only able to resolve by adding a `marginLeft` and adjusting the `width` in our drawer styles:

from `{ width: '80%' }` to `{ marginLeft: '20%', width: '100%' }`

```jsx
<Drawer.Navigator
  screenOptions={{
    // ...
    drawerStyle: {
      // ...
      marginLeft: '20%',
      width: '100%',
    }
  }}>
  ...
</Drawer.Navigator>
```

Hopefully this info is helpful for your situation, good luck!

**Comment by RenanDore** [comment]
this solution resolved to me:

Inside the navigator:
```
screenOptions={() => ({
        drawerStyle: {
          backgroundColor: 'white',
          width: '60%',
          color: '#f1f1f1',
          marginLeft: Platform.OS === 'ios' ? '10%' : '0%',
        },
```
Inside the drawerComponent at VStack:
`w={Platform.OS === 'ios' ? '90%' : '100%'}`

**Comment by usichenko-nikita** [comment]
As was mentioned here https://github.com/react-navigation/react-navigation/issues/10335#issuecomment-1038327527 just add useLegacyImplementation prop to Drawer.Navigator

**Comment by MrSquaare** [comment]
`useLegacyImplementation` can't be used with Reanimated 3+ since legacy support has been removed

**Comment by minwoo129** [comment]
I had the same problem, but I think I found the way to solve it temporarily. (thanks to my colleague)

I think there is a problem in react-native-safe-area-context that drawer navigation library call.

`typescript
<Drawer.Navigator
      initialRouteName="MainTabNavigator"
      screenOptions={{
        drawerType: 'front',
        drawerPosition: 'right',
        swipeEnabled: false,
        headerShown: false,
        drawerStyle: {
          backgroundColor: 'white',
          width: Dimensions.get('window').width * 0.95,
          marginLeft: Dimensions.get('window').width - dimensions.width,
        },
      }}
`
