### ISSUE TITLE
Can't create a header bottom border and change the borders color

### ISSUE THREAD

**Issue by adherb** [react-navigation/react-navigation#10830]
### Current behavior

I am trying to change the border header width and color.

Here is the code I'm using:

```
options={{
          headerShadowVisible: true,
          shadowOffset: { height: 4, width: 4 },
          shadowColor: 'red',
          borderBottomColor: 'red',
          borderBottomWidth: 4,   
        }}
```

None of the above is working.

### Expected behavior

The border width should increase and the border color should change.

### Reproduction

none

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/​bottom-tabs
- [ ] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [X] @react-navigation/​stack
- [X] @react-navigation/​native-stack

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |
| @react-navigation/bottom-tabs          |
| @react-navigation/drawer               |
| @react-navigation/material-bottom-tabs |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                |
| @react-navigation/native-stack         |
| react-native-safe-area-context         |
| react-native-screens                   |
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           |
| expo                                   |
| node                                   |
| npm or yarn                            |

**Comment by raajnadar** [comment]
**For React Navigation v6**

Use this prop https://reactnavigation.org/docs/material-top-tab-navigator/#tabbarindicatorstyle

**For React Navigation v5** 

Use `indicatorStyle` prop inside https://reactnavigation.org/docs/5.x/material-top-tab-navigator#tabbaroptions

**Comment by MiryangJung** [comment]
> **For React Navigation v6**
> 
> Use this prop https://reactnavigation.org/docs/material-top-tab-navigator/#tabbarindicatorstyle
> 
> **For React Navigation v5**
> 
> Use `indicatorStyle` prop inside https://reactnavigation.org/docs/5.x/material-top-tab-navigator#tabbaroptions

This solution is for `material-top-tabs` .  needed when using `native-stack`

**Comment by adorum** [comment]
@MiryangJung have you found a solution to change the bottom border of native stack header?
