### ISSUE TITLE
Problems when using Drawer in Mobile app

### ISSUE THREAD

**Issue by JuanjoOrt** [react-navigation/react-navigation#10836]
### Current behavior

Hello,

I installed the @react-navigation/drawer library as the documents says, in web it works correctly, but when I use a mobile device or tablet, have this error: `Unable to resolve "./EnableExperimentalWebImplementation" from "node_modules/react-native-gesture-handler/src/index.ts"` I tried to search docs in internet  but didn't found nothing,

Thanks a lot.

### Expected behavior

use the drawer into ipads or android tablets

### Reproduction

https://snack.expo.dev/@juanjoort/786c5b

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/​bottom-tabs
- [X] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [ ] @react-navigation/​stack
- [ ] @react-navigation/​native-stack

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/bottom-tabs          | 6.3.3
| @react-navigation/drawer               | 6.4.4
| @react-navigation/native-stack         | 6.8.0
| @react-navigation/native | 6.0.12
| react-native-safe-area-context         | 4,3,1
| react-native-screens                   | 3.15.0
| react-native-gesture-handler           | 2.5.0
| react-native-reanimated                | 2.9.1
| react-native                           | 0.69.5
| expo                                   | 46.0.0
| node                                   | 14.18.0
| npm or yarn                            | 6.14.15

**Comment by JuanjoOrt** [comment]
Hello, 

Today I opened my project and its works correctly, I didnt touch anything, what could it be?

Thanks a lot

**Comment by raajnadar** [comment]
Cache issue, I always clean the cache of both Gradle and JavaScript when changing the version of dependencies

Gradle cache -

`./gradlew clean` or `gradlew clean`

JavsScript cache - 

Vanilla react-native `npx react-native start --reset-cache`
Expo - `yarn expo start -c`
