### ISSUE TITLE
Navigating from a page to another both pages always rerender

### ISSUE THREAD

**Issue by Ange1J** [react-navigation/react-navigation#10835]
### Current behavior

https://user-images.githubusercontent.com/92681843/189757099-b22b8ca0-12d8-4ade-8e00-775662c69219.mp4

Each time you navigate from one page to another, the starting and the arrival pages are re-render. I entered a console.log in both pages. In windows both console.logs are called up every time i navigate to a page. I tested react-navigation/drawer and react-navigation/bottom.tabs

### Expected behavior

https://user-images.githubusercontent.com/92681843/189757132-5b20b93d-7822-4e81-9b8f-ddf42cc4f613.mp4

Running on Android, console.log start only the first time since there is no variation of the state.

### Reproduction

https://github.com/Ange1J/AwesomeProject

### Platform

- [ ] Android
- [ ] iOS
- [ ] Web
- [X] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/​bottom-tabs
- [X] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [ ] @react-navigation/​stack
- [ ] @react-navigation/​native-stack

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |6.0.12
| @react-navigation/bottom-tabs          |6.3.3
| @react-navigation/drawer               |6.4.4
| react-native-safe-area-context         |3.4.1
| react-native-screens                   |3.17.0
| react-native-gesture-handler           |2.6.0
| react-native-reanimated                |2.9.1
| react-native                           |0.69.5
| node                                   |16.17.0
| npm or yarn                            |8.15.0

**Comment by chGalbadrakh** [comment]
@Ange1J  did any solutions work for you ?

**Comment by MacKenzieHnC** [comment]
Running into [a probably-related issue](https://github.com/react-navigation/react-navigation/issues/11146). Anyone want to collaborate on this? I have a hunch where to start.

**Comment by acaininet** [comment]
I am having this issue as well. With Stack in RN Windows (I'm on .71 at the moment). Was there a resolution or workaround?

**Comment by satya164** [comment]
From the comments I have seen, this is a bug in `react-native-windows` where it unmounts screens if they have accessibility options set to make them inaccessible. It needs to be done natively without unmounting the component on JS side. Please open an issue in `react-native-windows` repo.

**Comment by acaininet** [comment]
Is there a wy to disable the accessibility options?

**Comment by tritter** [comment]
Any updates on this? Seems like both react-navigation and react-native-windows are fingerpointing...

**Comment by satya164** [comment]
This same code works as intended on all platforms except Windows which makes it clear that it's a bug in React Native windows.
