### ISSUE TITLE
Search bar not rendering on iOS or Android on initial render

### ISSUE THREAD

**Issue by servonlewis** [react-navigation/react-navigation#10848]
### Current behavior

Using the example shown on the website, the native-stack search bar does not show on iOS until you pull down on the Scrollview, and on android, I have to switch the bottom tab back and forth to get it to show. 

I am using the exact example listed on the site. 
I’ve also tried changing the useEffect to useLayoutEffect. 

React.useEffect(() => {
  navigation.setOptions({
    headerSearchBarOptions: {
      // search bar options
    }
  });
}, [navigation]);

### Expected behavior

The search bar (iOS) and search header (android) renders without any user interaction.  

### Reproduction

https://github.com/wizebaseLLC/TopTrainerReactNative/blob/main/views/features/discover/discover.tsx

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/​bottom-tabs
- [ ] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [ ] @react-navigation/​stack
- [X] @react-navigation/​native-stack

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |
| @react-navigation/bottom-tabs          |
| @react-navigation/stack                |
| @react-navigation/native-stack         |
| react-native-screens                   |
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           |
| expo                                   |
| node                                   |
| npm or yarn                            |

**Comment by servonlewis** [comment]
Sorry about not listing versions, as I am on mobile on my way to work. This is a brand new app that was created this week, therefore, you can expect the latest version of each.

**Comment by raajnadar** [comment]
> Can you provide a [minimal repro](https://stackoverflow.com/help/minimal-reproducible-example) which demonstrates the issue? Please try to keep the repro as small as possible and make sure that we can run it without additional setup.
> 
> A repro will help us debug the issue. The issue will be closed automatically after a while if you don't provide a repro.

Please read this message

**Comment by servonlewis** [comment]
> > Can you provide a [minimal repro](https://stackoverflow.com/help/minimal-reproducible-example) which demonstrates the issue? Please try to keep the repro as small as possible and make sure that we can run it without additional setup.
> 
> > 
> 
> > A repro will help us debug the issue. The issue will be closed automatically after a while if you don't provide a repro.
> 
> 
> 
> Please read this message

How much time do I have to do it?  At work now but can make a quick reproduction tonight.

**Comment by servonlewis** [comment]
I will close this for now and then open again after a few more test.

**Comment by peterferguson** [comment]
Was a solution found for this?

**Comment by nandorojo** [comment]
If anyone finds a fix to this, please post it here.

**Comment by nandorojo** [comment]
I think I fixed this. I posted a comment here: https://github.com/react-navigation/react-navigation/issues/11627#issuecomment-1815491330

Please let me know if that works for you.
