### ISSUE TITLE
React navigation Modal with ScrollView inside

### ISSUE THREAD

**Issue by ShchipskiiYura** [react-navigation/react-navigation#10842]
### Current behavior

const ModalStack = createStackNavigator()

const Router = (props) => {
    ...
    return (
        <ModalStack.Root
            options={{
                presentation: 'modal',
                gestureEnabled: true,
                gestureDirection: 'vertical',
                gestureResponseDistance: height,
                fullScreenGestureEnabled: true,
                ...TransitionPresets.ModalPresentationIOS
            }}>
            <ModalStack.Screen name='Assets' component={AssetScreen} />
        </ModalStack.Root>
    )
}

const AssetsScreen = (props) => {

    return (
        <FlatList
            keyboardShouldPersistTaps='handled'
            data={userCurrency}
            keyExtractor={(item) => item.currencyCode}
            showsVerticalScrollIndicator={false}
            renderItem={renderFlatListItem}
            bounces={false}
        />
    )
}

### Expected behavior

https://user-images.githubusercontent.com/34343582/176510808-768f6227-7390-4444-a617-c3d0670117ee.gif

### Reproduction

nolink

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/​bottom-tabs
- [X] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [X] @react-navigation/​stack
- [X] @react-navigation/​native-stack

### Environment

- [ ] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | ^6.0.8
| @react-navigation/stack                | ^6.1.1
| @react-navigation/native-stack         | ^6.5.0
| react-native-safe-area-context         | ^3.3.2
| react-native-screens                   | ^3.10.2
| react-native-gesture-handler           | ^1.10.3
| react-native-reanimated                | 2.4.1
| react-native                           | 0.67.2
| node                                   | 14.18.2
| yarn                            | 1.22.10

**Comment by eeshankeni** [comment]
Same problem here.

**Comment by ser-emejia** [comment]
Any solution?
