### ISSUE TITLE
I cant find tab press in screenlistners and not even in listeners too

### ISSUE THREAD

**Issue by ckswopnera** [react-navigation/react-navigation#10854]
I cant find tab press in screenlistners and not even in listeners too 
![image](https://user-images.githubusercontent.com/73164259/190670153-2e7c375a-62ad-4ef1-96db-bab5ce6d3260.png)
and,
![image](https://user-images.githubusercontent.com/73164259/190670881-fc2c3a27-1297-408a-be53-97150aaf470e.png)

Please help in this

_Originally posted by @ckswopnera in https://github.com/react-navigation/react-navigation/issues/7252#issuecomment-1249478124_

**Comment by raajnadar** [comment]
You should not expect tab press in stack navigator as the listener is for the tab navigator
