### ISSUE TITLE
headerLargeTitle does not work with bottom-tabs

### ISSUE THREAD

**Issue by onursagir** [react-navigation/react-navigation#10862]
### Current behavior

Im expecting the bottom tabs to pick up the `headerLargeTitle` option and that the application would work similarly to the Apple Music app

### Expected behavior

The bottom tabs don't pick up the `headerLargeTitle` option at all

### Reproduction

https://snack.expo.dev/7jIIbRA_H

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/​bottom-tabs
- [ ] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [ ] @react-navigation/​stack
- [ ] @react-navigation/​native-stack

### Environment

- [X] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | ^6.0.13
| @react-navigation/bottom-tabs          | ^6.4.0
| @react-navigation/native-stack         |^6.9.0
| react-native-safe-area-context         |4.3.1
| react-native-screens                   |~3.15.0
| react-native                           | 0.70.1
| expo                                   |46.0.0
| node                                   |v16.17.0
| npm or yarn                            |^1.22.19

**Comment by onursagir** [comment]
I don't know what the implication are but there does seem to be a work around by using the nativeStack inside the bottomTab

```JavaScript
const Tab = createBottomTabNavigator();
const Stack = createNativeStackNavigator();

const Wrapped = () => {
  return (
    <Stack.Navigator>
      <Stack.Screen
        name="Homescreen"
        component={Home}
        options={{ headerLargeTitle: true }}
      />
    </Stack.Navigator>
  );
};

export default function App() {
  return (
    <SafeAreaProvider>
      <NavigationContainer>
        <Tab.Navigator>
          <Tab.Screen
            name="HomeTab"
            component={Wrapped}
            options={{ headerShown: false }}
          />
        </Tab.Navigator>
      </NavigationContainer>
    </SafeAreaProvider>
  );
}
```

**Comment by mabdurrafey-afl** [comment]
just encountered this again, is there any update on this issue yet. 👎 (

**Comment by satya164** [comment]
`headerLargeTitle` is an option in native stack navigator https://reactnavigation.org/docs/native-stack-navigator/#headerlargetitle

It's not an option in bottom-tabs.
