### ISSUE TITLE
No identifiers allowed directly after numeric literal

### ISSUE THREAD

**Issue by AndonMitev** [react-navigation/react-navigation#10869]
### Current behavior

App is not compiling when running on Android

### Expected behavior

App to compile when running on Android

### Reproduction

dsadsa

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/​bottom-tabs
- [ ] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [X] @react-navigation/​stack
- [X] @react-navigation/​native-stack

### Environment

```
  "@react-navigation/native": "6.0.12",
    "@react-navigation/native-stack": "6.8.0",
    "@react-navigation/stack": "6.2.3",
```

I'm hitting error: `No identifiers allowed directly after numeric literal` after a little bit of research is more likely coming from the `Color` package, what are you suggestions to resolve it

**Comment by ajayhcode** [comment]
getting same isseu
