### ISSUE TITLE
App Crash without informations when drawer is imported

### ISSUE THREAD

**Issue by antoine-carruana** [react-navigation/react-navigation#10866]
### Current behavior

I am currently working on a project where I wanted to implement the drawer navigation.

I am working on Windows 11 and I use expo to test the application on my Android phone. 
 
I followed the [documentation](https://reactnavigation.org/docs/drawer-navigator#installation) for the installation but as soon as I tried to launch the application the expo app keeps crashing and I can't get any information in the console. 

I wanted to make sure that the drawer navigation was the problem so I created a simple application and installed the drawer navigation and I have the same problem (which corresponds to the snack link but there's seems to be a problem with reanimated in the snack)

### Expected behavior

Opening drawer in the application

### Reproduction

https://snack.expo.dev/@carruanito/react-navigation-drawer-issue

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [X] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/​bottom-tabs
- [X] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [ ] @react-navigation/​stack
- [ ] @react-navigation/​native-stack

### Environment

- I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | ^6.0.13
| @react-navigation/drawer               | ^6.5.0
| react-native-safe-area-context         | 4.3.1
| react-native-screens                   | ~3.15.0
| react-native-gesture-handler           | ~2.5.0
| react-native-reanimated                | ~2.9.1
| react-native                           | 0.69.5
| react                                | 18.0.0
| expo                                   | ~46.0.9
| node                                   |
| npm                           |

**Comment by kacperkapusciak** [comment]
Hi @antoine-carruana :wave:

Here I've set up the drawer navigator in a separate repository so you can compare your setup: https://github.com/kacperkapusciak/expo-drawer-repro

<details>
<summary>Recording</summary>
<br>

https://user-images.githubusercontent.com/39658211/191205454-ebe5733d-8183-4c9c-915f-aacef081ac03.mov

</details>


Make sure to add a `'react-native-reanimated/plugin'` babel plugin to your `babel.config.js` and clean cache afterwards. The Reanimated installation steps: https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/installation/



Secondly, there seems to be a bug with the Expo snack. The function which is shown within the error `__reanimatedWorkletInit is not a function` doesn't exist anymore in the `react-native-reanimated` library.  I'm taking an educated guess that Expo has many versions of `react-native-reanimated`  in the monorepo setup and sadly there's nothing react-navigation can do about this.

**Comment by raajnadar** [comment]
@chGalbadrakh can't you see the solution provided by @kacperkapusciak?

**Comment by antoine-carruana** [comment]
> @antoine-carruana did any solutions work for you ?

Hey, I checked the config as suggested by @kacperkapusciak which was already ok on my end.
What helped for me was to delete the node_modules folder and reinstall everything then everything was ok
