### ISSUE TITLE
@react-navigation/material-bottom-tabs cannot be installed in these settings

### ISSUE THREAD

**Issue by R4Y-repo** [react-navigation/react-navigation#10877]
### Current behavior

when you do `npm install @react-navigation/material-bottom-tabs` it gives out this error:
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: ************@1.0.0
npm ERR! Found: react-native-paper@5.0.0-rc.6
npm ERR! node_modules/react-native-paper
npm ERR!   react-native-paper@"^5.0.0-rc.5" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react-native-paper@">= 3.0.0" from @react-navigation/material-bottom-tabs@6.2.4
npm ERR! node_modules/@react-navigation/material-bottom-tabs
npm ERR!   @react-navigation/material-bottom-tabs@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\user\AppData\Local\npm-cache\eresolve-report.txt for a full report.
```

### Expected behavior

`@react-navigation/material-bottom-tabs` should be installed fine

### Reproduction

****

### Platform

- [ ] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/​bottom-tabs
- [ ] @react-navigation/​drawer
- [X] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [ ] @react-navigation/​stack
- [ ] @react-navigation/​native-stack

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |6.0.13
| @react-navigation/bottom-tabs          |6.4.0
| @react-navigation/drawer               |6.5.0
| @react-navigation/material-bottom-tabs |6.2.4
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                |6.9.0
| @react-navigation/native-stack         |6.9.0
| react-native-safe-area-context         |4.3.1
| react-native-screens                   |3.15.0
| react-native-gesture-handler           |2.5.0
| react-native-reanimated                |2.9.1
| react-native-paper                |5.0.0-rc.6
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           |0.69.5
| expo                                   |46.0.10
| node                                   |16.17.0
| npm or yarn                            |8.19.1

**Comment by MarcLopezAvila** [comment]
Same problem here, please fix this.

**Comment by jardvanroest** [comment]
Same problem here

**Comment by okwasniewski** [comment]
Hey, I've posted a workaround with an explanation here: https://github.com/callstack/react-native-paper/issues/3451#issuecomment-1302617283

Let me know if this fixes the issue.

**Comment by Bi0max** [comment]
Same problem
