### ISSUE TITLE
All objects on the page I came back to disappear [Android]

### ISSUE THREAD

**Issue by ugurdalkiran** [react-navigation/react-navigation#10875]
### Current behavior

```
"react": "18.1.0",
"react-native": "0.70.1",
---
"@react-navigation/native": "6.0.13",
"@react-navigation/native-stack": "6.9.0",
"react-native-gesture-handler": "2.6.1",
"react-native-safe-area-context": "4.3.4",
"react-native-splash-screen": "3.0.6",

<GestureHandlerRootView style={{ flex: 1 }}>
	<NavigationContainer>
		<Stack.Navigator
		screenOptions={{
			headerMode: "screen"
		}}
		initialRouteName="Home">
		<Stack.Screen name="Home" component={Home} />
		<Stack.Screen
			name="Page"
			component={Page}
			options={{ animation: "slide_from_right" }}
		/>
		</Stack.Navigator>
	</NavigationContainer>
</GestureHandlerRootView>

props.navigation.navigate("Page");
props.navigation.goBack();
```

I'm opening a new page on Android and everything is fine. When I want to come back from that opened page, all Views and Texts disappear from the screen. A white screen appears. Then my back page opens.

At this stage, I want the objects on my screen not to disappear.

Here is the video.

https://user-images.githubusercontent.com/27302986/191944841-4caf6c35-7395-4329-8203-6ef68ff352a6.mp4

### Expected behavior

At this stage, I want the objects on my screen not to disappear.

### Reproduction

https://github.com/react-navigation/react-navigation

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/​bottom-tabs
- [ ] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [ ] @react-navigation/​stack
- [X] @react-navigation/​native-stack

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |
| @react-navigation/bottom-tabs          |
| @react-navigation/drawer               |
| @react-navigation/material-bottom-tabs |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                |
| @react-navigation/native-stack         |
| react-native-safe-area-context         |
| react-native-screens                   |
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           |
| expo                                   |
| node                                   |
| npm or yarn                            |

**Comment by ugurdalkiran** [comment]
I'm waiting for help.

**Comment by dppo** [comment]
Same question with use fabric
