### ISSUE TITLE
iOS only -- Push notifications params are not accessible in route.params when clicking notification and app is closed

### ISSUE THREAD

**Issue by jde8aa** [react-navigation/react-navigation#10873]
### Current behavior

When the app is closed and the user clicks on the push notification, the app opens up but no route.params are provided even though they are included in the deep link's "launchURL" field.

This behavior only occurs on real devices and not the simulator.  Running the simulator and using "npx uri-scheme open" to trigger deep links works perfectly.

When the app is active or in the background, things function as expected on the iOS simulator as well as real devices.

CODE:

App.js
```javascript
const App = () => {
	return (
		<ErrorBoundary FallbackComponent={ErrorBoundaryScreen}>
			<AuthProvider>
				<RootNavigator />
			</AuthProvider>
		</ErrorBoundary>
	);
};
```

RootNavigator.js
```javascript
const linking = {
	prefixes: ['myapp://'],
	config: {
		screens: {
			Drawer: {
				screens: {
					HomeScreen: {
						path: ':clientID/home/:customerID',
					},
				},
			},
		},
	},
};

HomeScreen.js
const RootNavigator = () => {
	const {authState} = useContext(AuthContext);

	return (
		<SafeAreaProvider style={styles.safeAreaView}>
			<HeapNavigationContainer onReady={onNavigationReady} linking={linking} ref={navigationRef}>
				<OnboardingProvider>
					{authState.token ? <AppNavigator /> : <LoginNavigator />}
				</OnboardingProvider>
			</HeapNavigationContainer>
		</SafeAreaProvider>
	);
};
```

```javascript 
const HomeScreen = props => {
        //this is not populated with clientID and customerID if the app was closed when the notif was clicked
	console.log(props.route.params);
};
```

### Expected behavior

When the app is closed and the user clicks the push notification, the expected behavior is that the app will open and navigate to the correct screen, providing the "launchURL" params as part of route.params.  

### Reproduction

n/a

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/​bottom-tabs
- [ ] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [X] @react-navigation/​stack
- [ ] @react-navigation/​native-stack

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.0.12 |
| @react-navigation/drawer               | 6.44 |
| @react-navigation/stack                | 6.2.3 |
| react-native                           | 0.68.3 |
| expo                                   | 45.0.0 |
| node                                   | 18.2.0 |
| npm or yarn                            | 8.1.0 |

**Comment by jde8aa** [comment]
After some further testing, it appears to be working on a test build about 30% of the time, so it seems to be some kind of race condition.  

I also tried alternative ways (Linking.getInitialURL) when testing locally and that function always returned null, so that was interesting.  I read other places that said that is natural on iOS if remote JS debugging is enabled.

**Comment by satya164** [comment]
React Navigation doesn't integrate with your push notifications. If you want to integrate `linking` with push notifications, then you need to configure React Navigation to do so

https://reactnavigation.org/docs/deep-linking#third-party-integrations

**Comment by jde8aa** [comment]
> 

Something is integrating with my push notifications, as it works fine when the app is active or in the background.  How is React Navigation able to grab the deep link from the notification automatically when that happens but unable to do it when the app is opening from clicking the notification then?  

It seems to be that React Navigation is getting the deep link from the notification just fine (I'm using OneSignal), but that is is attempting to navigate before the navigation stack is ready to go.
