### ISSUE TITLE
react-navigation@4.4.5 not released on npm

### ISSUE THREAD

**Issue by Aure77** [react-navigation/react-navigation#10880]
### Current behavior

Related to this commit:
https://github.com/react-navigation/react-navigation/commit/46ecfc529023201f71b26eecea375ec4148be95b
a job as failed.

### Expected behavior

4.4.5 should be released on npm registry.

### Reproduction

https://github.com/react-navigation/react-navigation/actions/runs/1783579862/jobs/2473039073

### Platform

- [X] Android
- [X] iOS
- [ ] Web

### Packages

- [X] react-navigation-​drawer
- [X] react-navigation-​stack
- [X] react-navigation-​tabs

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| react-navigation                       |
| react-navigation-tabs                  |
| react-navigation-drawer                |
| react-navigation-stack                 |
| react-native-safe-area-context         |
| react-native-screens                   |
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native-tab-view                  |
| react-native                           |
| expo                                   |
| node                                   |
| npm or yarn                            |

**Comment by amatyaichhya** [comment]
still facing this issue
