### ISSUE TITLE
Stack navigator nested inside drawer navigator. Unable to override headerShown property for inner stack navigator header.

### ISSUE THREAD

**Issue by atharva-jadhav-04** [react-navigation/react-navigation#10882]
### Current behavior

- I want only one header to be shown which is the parent header (because, I have already created many screens I cant change this very easily)
- The parent drawer navigator has drawer menu button, title shown in some screens, and icons/components added to header right.
- When I have change name, headerRight, or navigate to another screen in drawer I use the navigation object of drawer navigator passed down as a prop. It works as intended as well.
- However, when the orientation of screen is changed or keyboard inside scroll view is opened, stack navigator header is shown. (Only the white space, not the title or even the background color) even when It is explicitly set as false.
- When I close & reopen the screen it goes away, but comes back after reproduction mentioned above.
- This does not happen in IOS and the app is working perfectly fine there.
- Before changing orientation
![Screenshot_1664273169](https://user-images.githubusercontent.com/95622313/192498019-c0d07bc9-d222-4533-8b66-dc2a74cd0fb8.png)

- After changing orientation
![Screenshot_1664273179](https://user-images.githubusercontent.com/95622313/192498099-208255e9-6ee8-49aa-b3b2-78221b7b8431.png)

- How do I know this is the inner stack navigator and not just a UI bug from my application?
- I can set header title and background color to red and you can see it is actually the inner header belonging to stack navigator.
![Screenshot_1664274009](https://user-images.githubusercontent.com/95622313/192501066-3335390d-9f0b-46b1-a8ed-6981521e51e3.png)

- Now If I try to reproduce the same problem there is not white space added to the UI.
- Once again, this does not happen in IOS, there it is working perfectly fine. 

### Expected behavior

- The header of stack navigator (inner header) should not be displayed when Its property headerShown is set to false.

### Reproduction

https://github.com/Crimsonbeans-Techlabs/IguanaPro-V2

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/​bottom-tabs
- [X] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [X] @react-navigation/​stack
- [X] @react-navigation/​native-stack

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.0.10
| @react-navigation/bottom-tabs          | 
| @react-navigation/drawer               | 6.4.2
| @react-navigation/material-bottom-tabs |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                | 
| @react-navigation/native-stack         | 6.6.2
| react-native-safe-area-context         | 4.3.1
| react-native-screens                   | 3.13.1
| react-native-gesture-handler           | 2.5.0
| react-native-reanimated                | 2.9.1
| react-native-tab-view                  | 3.1.1
| react-native-pager-view                | 5.4.24
| react-native                           | 0.69.1
| expo                                   | NA
| node                                   | 16.16.0
| npm or yarn                            |  npm 8.11.0

**Comment by AndriyZahura** [comment]
This is an active issue, reproducible in 

"@react-navigation/drawer": "^6.5.7",
"@react-navigation/native": "^6.0.8",
"@react-navigation/native-stack": "^6.9.9",

I haven't found a workaround yet. Dynamic height is not an option. I have around ~20 createNativeStackNavigators inside one createDrawerNavigator. When changing to another orientation on Android, the height of drawer is doubled but there is no content, like on the author's screen. On screenshot: orange - my header; Red - SafeAreaView (or a simple View) of content.

![image](https://github.com/react-navigation/react-navigation/assets/55994435/317214f9-555a-4e5f-92b9-9b507f50a7ce)
