### ISSUE TITLE
getConstants is not a function  in react native navigation backbutton in header

### ISSUE THREAD

**Issue by bipin-goodworklabs** [react-navigation/react-navigation#10881]
### Current behavior

This is the error i am getting

`HeaderBackButton.tsx:207 Uncaught TypeError: react_native_web_dist_exports_I18nManager__WEBPACK_IMPORTED_MODULE_5__.default.getConstants is not a function
    at ./node_modules/@react-navigation/elements/lib/module/Header/HeaderBackButton.js (HeaderBackButton.tsx:207:1)
    at __webpack_require__ (bootstrap:789:1)
    at fn (bootstrap:100:1)
    at ./node_modules/@react-navigation/elements/lib/module/index.js (index.tsx:1:1)
    at __webpack_require__ (bootstrap:789:1)
    at fn (bootstrap:100:1)
    at ./node_modules/@react-navigation/drawer/lib/module/views/DrawerView.js (DrawerToggleButton.tsx:44:1)
    at __webpack_require__ (bootstrap:789:1)
    at fn (bootstrap:100:1)
    at ./node_modules/@react-navigation/drawer/lib/module/navigators/createDrawerNavigator.js (index.tsx:22:1)
    at __webpack_require__ (bootstrap:789:1)
    at fn (bootstrap:100:1)
    at ./node_modules/@react-navigation/drawer/lib/module/index.js (index.tsx:4:1)
    at __webpack_require__ (bootstrap:789:1)
    at fn (bootstrap:100:1)
    at ./App.jsx (bootstrap:856:1)
    at __webpack_require__ (bootstrap:789:1)
    at fn (bootstrap:100:1)
    at ./node_modules/expo/AppEntry.js (AppEntry.js:1:1)
    at __webpack_require__ (bootstrap:789:1)
    at fn (bootstrap:100:1)
    at 1 (index.js:18:1)
    at __webpack_require__ (bootstrap:789:1)
    at bootstrap:856:1
    at bootstrap:856:1`
    

### Expected behavior

i m not able to run the prooject. It is always giving this error. please Help!!!

### Reproduction

fd

### Platform

- [ ] Android
- [ ] iOS
- [X] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/​bottom-tabs
- [X] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [ ] @react-navigation/​stack
- [ ] @react-navigation/​native-stack

### Environment

{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject",
    "web:build": "expo build:web"
  },
  "dependencies": {
    "@expo-google-fonts/nunito-sans": "^0.2.2",
    "@react-native-async-storage/async-storage": "^1.17.10",
    "@react-native-google-signin/google-signin": "^7.2.2",
    "@react-navigation/drawer": "^6.1.1",
    "@react-navigation/native": "^6.0.13",
    "@reduxjs/toolkit": "^1.8.5",
    "accordion-collapse-react-native": "^1.1.0",
    "axios": "^0.26.1",
    "countries-and-timezones": "^3.3.0",
    "crypto-js": "^4.1.1",
    "expo": "~42.0.1",
    "expo-auth-session": "~3.3.1",
    "expo-document-picker": "~9.2.4",
    "expo-linear-gradient": "^11.4.0",
    "expo-random": "~11.2.0",
    "expo-status-bar": "~1.0.4",
    "expo-web-browser": "~9.2.0",
    "lodash.get": "^4.4.2",
    "lodash.isempty": "^4.4.0",
    "lodash.set": "^4.3.2",
    "native-base": "3.2.1",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-google-login": "^5.2.2",
    "react-native": "^0.68.2",
    "react-native-circular-progress": "^1.3.7",
    "react-native-country-flag": "^1.1.6",
    "react-native-gesture-handler": "^2.6.2",
    "react-native-keyboard-aware-scroll-view": "^0.9.4",
    "react-native-markdown-display": "^7.0.0-alpha.2",
    "react-native-paper": "^4.12.1",
    "react-native-phone-input": "^1.3.3",
    "react-native-reanimated": "~2.2.0",
    "react-native-safe-area-context": "3.2.0",
    "react-native-screens": "~3.4.0",
    "react-native-svg": "12.1.1",
    "react-native-web": "~0.13.12",
    "react-otp-input": "^2.4.0",
    "react-player": "^2.10.1",
    "react-rating-stars-component": "^2.2.0",
    "react-redux": "^8.0.2",
    "secure-web-storage": "^1.0.2",
    "styled-components": "^5.3.0",
    "styled-system": "^5.1.5",
    "typescript": "^4.8.3"
  },
  "devDependencies": {
    "@babel/core": "^7.9.0",
    "@types/react": "~16.9.35",
    "@types/react-native": "~0.63.2",
    "dom-helpers": "3.4.0"
  },
  "private": true
}

**Comment by bipin-goodworklabs** [comment]
I18nManager.getConstants().isRTL ? -1 : 1

this looks like here getConstants is not working. please help to resolve this

**Comment by bipin-goodworklabs** [comment]
I have updated @react-navigation/drawer version  to latest but still not working 

    "@react-navigation/drawer": "^6.5.0",

**Comment by PerryRylance** [comment]
Seeing this with an Expo build after forcing dom-helpers@3.4.0

**Comment by PerryRylance** [comment]
Also tried updating the following from older versions, issue still persists

```
    "@react-navigation/drawer": "^6.5.0",
    "@react-navigation/native": "^6.0.13",
    "@react-navigation/native-stack": "^6.9.1",
    "@react-navigation/stack": "^6.3.2",
```

**Comment by nsit-admin** [comment]
react-navigation/elements@1.3.7 is the problem.  I have downgraded all the react-navigation packages (elements, native, native-stack) and it started working

**Comment by juanchaur** [comment]
@nsit-admin which version did you downgraded to?
