### ISSUE TITLE
[IOS] Screen content can be pressed through the overlay when Drawer is open

### ISSUE THREAD

**Issue by khoale-groove** [react-navigation/react-navigation#10893]
### Current behavior

https://user-images.githubusercontent.com/97075023/192981374-8600f3f0-f92b-46f9-a0ee-f72a907c929e.MP4

### Expected behavior

preventing user press in that view.

### Reproduction

the bug is appeared in latest version

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/​bottom-tabs
- [X] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [ ] @react-navigation/​stack
- [ ] @react-navigation/​native-stack

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | "6.0.13"
| @react-navigation/bottom-tabs          |  "6.4.0"
| @react-navigation/drawer               |  "6.5.0"
| @react-navigation/stack                |  "6.3.1"
| @react-navigation/native-stack         | "6.9.0"
| react-native-safe-area-context         |  "4.3.3"
| react-native-screens                   |  "3.17.0"
| react-native-gesture-handler           |  "2.6.0"
| react-native-reanimated                |  "2.9.1"
| react-native                           | "0.68.3"

**Comment by khoale-groove** [comment]
I saw the bug in `@react-navigation/drawer/src/views/modern/Overlay.tsx` line 32.
We should keep `pointerEvents` is `auto` to prevent user press through the overlay.
Just remove this line.

**Comment by ravindraguptacapgemini** [comment]
I am also experiencing the same issue in the version 6.6.2, @khoale-groove any luck fixing the issue?
