### ISSUE TITLE
ApiV2Error: Entity Not Authorized.

### ISSUE THREAD

**Issue by bit-void** [react-navigation/react-navigation#10898]
### Current behavior

Unable to run example app without removing `owner` in the example's `app.json`. See this comment https://github.com/expo/expo-cli/issues/2436#issuecomment-735867585

### Expected behavior

Run example app

### Reproduction

https://github.com/expo/expo-cli/issues/2436#issuecomment-735867585

### Platform

- [ ] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [X] MacOS

### Packages

- [ ] @react-navigation/​bottom-tabs
- [ ] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [ ] @react-navigation/​stack
- [ ] @react-navigation/​native-stack

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |
| @react-navigation/bottom-tabs          |
| @react-navigation/drawer               |
| @react-navigation/material-bottom-tabs |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                |
| @react-navigation/native-stack         |
| react-native-safe-area-context         |
| react-native-screens                   |
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           |
| expo                                   |
| node                                   |
| npm or yarn                            |

**Comment by ismael-saavedra** [comment]
Hi!

I'm having the same issue and removing **owner** from app.json helps, been logged in in expo cli & Expo Go doesn't make a difference.

I'm ussing the following packages:

 "dependencies": {
    "@expo/vector-icons": "^13.0.0",
    "@native-html/table-plugin": "^5.3.1",
    "@react-native-community/netinfo": "9.3.0",
    "@react-native-picker/picker": "2.4.2",
    "@react-navigation/bottom-tabs": "^6.4.0",
    "@react-navigation/elements": "^1.3.6",
    "@react-navigation/native": "^6.0.13",
    "@react-navigation/native-stack": "^6.9.0",
    "@sanar/react-native-highlight-text": "^1.0.2",
    "@sentry/react-native": "4.2.2",
    "@types/highlight-words-core": "^1.2.1",
    "axios": "^0.27.2",
    "expo": "^46.0.0",
    "expo-application": "~4.2.2",
    "expo-blur": "~11.2.0",
    "expo-constants": "~13.2.4",
    "expo-device": "~4.3.0",
    "expo-linear-gradient": "~11.4.0",
    "expo-linking": "~3.2.2",
    "expo-notifications": "~0.16.1",
    "expo-print": "~11.3.0",
    "expo-secure-store": "~11.3.0",
    "expo-sharing": "~10.3.0",
    "expo-splash-screen": "~0.16.2",
    "expo-status-bar": "~1.4.0",
    "expo-task-manager": "~10.3.0",
    "expo-updates": "~0.14.5",
    "expo-web-browser": "~11.0.0",
    "jest": "^26.6.3",
    "lodash": "^4.17.21",
    "moment": "^2.29.3",
    "react": "18.0.0",
    "react-dom": "18.0.0",
    "react-error-boundary": "^3.1.4",
    "react-native": "0.69.6",
    "react-native-maps": "0.31.1",
    "react-native-render-html": "^6.3.4",
    "react-native-root-toast": "^3.4.0",
    "react-native-safe-area-context": "4.3.1",
    "react-native-screens": "~3.15.0",
    "react-native-svg": "12.3.0",
    "react-native-web": "~0.18.7",
    "react-native-webview": "11.23.0",
    "react-query": "^3.34.16",
    "sentry-expo": "~5.0.0",
    "styled-components": "^5.3.5",
    "uuid": "^8.3.2"
  },
  "devDependencies": {
    "@babel/core": "^7.18.6",
    "@testing-library/jest-native": "^4.0.4",
    "@testing-library/react-native": "^9.0.0",
    "@types/jest": "^27.4.1",
    "@types/lodash": "^4.14.180",
    "@types/react": "~18.0.0",
    "@types/react-native": "~0.69.1",
    "@types/styled-components": "^5.1.25",
    "@types/styled-components-react-native": "^5.1.3",
    "@types/uuid": "^8.3.4",
    "@typescript-eslint/eslint-plugin": "^5.21.0",
    "@typescript-eslint/parser": "^5.15.0",
    "eslint": "^8.11.0",
    "eslint-plugin-import": "^2.25.4",
    "eslint-plugin-react": "^7.29.4",
    "eslint-plugin-react-hooks": "^4.5.0",
    "eslint-plugin-testing-library": "^5.1.0",
    "jest-expo": "^46.0.0",
    "react-native-svg-transformer": "^1.0.0",
    "react-test-renderer": "^17.0.2",
    "typescript": "^4.6.3"
  },

**Comment by roni-castro** [comment]
It just worked for me if I [remove the `eas` from `app.json`](https://github.com/expo/expo-cli/issues/2436#issuecomment-1308534521):


<img width="961" alt="Screen Shot 2023-02-10 at 21 17 34" src="https://user-images.githubusercontent.com/24610813/218225421-7ce2e760-ab30-4f59-8c23-ff728594e072.png">


https://user-images.githubusercontent.com/24610813/218225872-e1182843-4e33-4809-a285-97cc58c67142.mov
