### ISSUE TITLE
[Android] glitchy `slide_from_bottom` animation

### ISSUE THREAD

**Issue by lkalashov** [react-navigation/react-navigation#10908]
### Current behavior

Navigation to screen is followed by glitchy animation. Screen is moved up a bit, then disappears and gets rendered fullscreen instantly.

https://user-images.githubusercontent.com/102518316/193790629-a96546f3-0d99-4395-a92c-9753dda0d5d7.mov

### Expected behavior

Navigation to screen is followed by smooth animation from bottom to top.

https://user-images.githubusercontent.com/102518316/193790444-809df6c2-4443-45fd-b511-e33905259d24.mov

### Reproduction

https://github.com/lkalashov/sample-navigation

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/​bottom-tabs
- [ ] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [ ] @react-navigation/​stack
- [X] @react-navigation/​native-stack

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |    =6.0.10
| @react-navigation/bottom-tabs          |    =6.3.1
| @react-navigation/drawer               |    =6.4.1
| @react-navigation/native-stack         |    =6.6.1
| react-native-safe-area-context         |    =3.3.2
| react-native-screens                   |    =3.10.2
| react-native-gesture-handler           |    =2.1.3
| react-native-reanimated                |    =2.3.3
| react-native                           |    =0.64.3
| expo                                   |    =44.0.6
| node                                   |    v14.19.2
| npm or yarn                            |    yarn 1.22.18

**Comment by lkalashov** [comment]
For those experiencing same issue, temporary workaround I found is to use 
`presentation: "transparentModal"` or `presentation: "containedTransparentModal"` option alongside `animation: "slide_from_bottom"` option.

**Comment by NeonKamuy** [comment]
Another issue with modal animations on Android.
If modal contains ScrollView which utilises RefreshControl, closing modal causes RefreshControl indicator to become visible.

![image](https://user-images.githubusercontent.com/56562519/194031778-b1eeb586-6ab4-4a99-b62e-415f8223dbd7.png)

https://user-images.githubusercontent.com/56562519/194032530-924b4246-77d7-4fc5-9792-cc873a927272.mp4

**Comment by ansh** [comment]
I am facing this issue as well. How did you solve it? @lkalashov

**Comment by lkalashov** [comment]
Hi @ansh!
I wasn't able to find proper solution for RefreshControl spinner showing up during the animation.
As a workaround I manually disable RefreshControl for FlatList before screen is going to be removed.

I use something like this:
```
  const [isRefreshControlEnabled, setIsRefreshControlEnabled] = useState(false);
 
  useEffect(() => {
    const eventCallback = (event: BeforeRemoveEvent) => {
      // Prevent default behavior of leaving the screen
      event.preventDefault();
      setIsRefreshControlEnabled(false);
      setTimeout(() => navigation.dispatch(event.data.action), 1);
    };

    navigation.addListener('beforeRemove', eventCallback);
    return () => navigation.removeListener('beforeRemove', eventCallback);
  }, [navigation, dispatch]);
  
  useFocusEffect(useCallback(() => { 
      setIsRefreshControlEnabled(true); 
  }, []));
  ```
