### ISSUE TITLE
Conflicting peer dependency react-native-reanimated@"3.0.0-rc.3"

### ISSUE THREAD

**Issue by hannojg** [react-navigation/react-navigation#10909]
### Current behavior

We have a client using `@react-navigation/drawer@6.5.0` and wants to use the latest react-native-reanimated version 3.

In `@react-navigation/drawer@6.5.0` `package.json` it says:

```json
"peerDependencies": {
    "react-native-reanimated": ">= 1.0.0",
```

However, a semver check with `react-native-reanimated@3.0.0-rc.3` fails against `>= 1.0.0"`.

The full npm install error:

```text
➜ npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @react-navigation/drawer@6.5.0
npm ERR! Found: react-native-reanimated@3.0.0-rc.3
npm ERR! node_modules/react-native-reanimated
npm ERR!   react-native-reanimated@"3.0.0-rc.3" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react-native-reanimated@">= 1.0.0" from @react-navigation/drawer@6.5.0
npm ERR! node_modules/@react-navigation/drawer
npm ERR!   @react-navigation/drawer@"6.5.0" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: react-native-reanimated@2.10.0
npm ERR! node_modules/react-native-reanimated
npm ERR!   peer react-native-reanimated@">= 1.0.0" from @react-navigation/drawer@6.5.0
npm ERR!   node_modules/@react-navigation/drawer
npm ERR!     @react-navigation/drawer@"6.5.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

Not an issue with using yarn though.

### Expected behavior

Versions are compatible. One fix would be to add in the meantime this fix:

```json
"peerDependencies": {
    "react-native-reanimated": ">= 1.0.0 || >= 3.0.0-rc",
```

### Reproduction

https://github.com/hannojg/react-navigation-rea-v3-rc-install-repro

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/​bottom-tabs
- [X] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [ ] @react-navigation/​stack
- [ ] @react-navigation/​native-stack

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.0.13
| @react-navigation/drawer               | 6.5.0
| @react-navigation/stack                | 6.3.1
| react-native-safe-area-context         | 4.4.1
| react-native-screens                   | 3.17.0
| react-native-gesture-handler           | 2.6.0
| react-native-reanimated                | 3.0.0-rc.3
| react-native                           | 0.70.1
| node                                   | 16.15.1
| npm or yarn                            | 8.11.0

**Comment by kacperkapusciak** [comment]
Hi @hannojg 👋 
Sorry but the `semver` check here is very much correct in this situation and we can't add your proposed solution.

Reanimated v3 drops support for Reanimated 1 API so the check would contradict itself. To officially support Reanimated 3 in Drawer we would have to drop support for legacy implementation ([useLegacyImplementation](https://reactnavigation.org/docs/drawer-navigator/#uselegacyimplementation) prop) for which we aren't ready as it still has its use cases. 

When you force install `react-native-reanimated` v3 and won't use `useLegacyImplementation` prop the drawer should work just fine but we can't accept this as an official solution today.

Cheers

**Comment by hannojg** [comment]
Ah yeah of course that makes sense I see. Thx for getting back to me with this!
