### ISSUE TITLE
Getting warning and auth flow doesn't work 

### ISSUE THREAD

**Issue by scshiv29-dev** [react-navigation/react-navigation#10901]
### Current behavior

Navigation doesn't render login screen even though the condition is true and there is no user logged in.

### Expected behavior

User should be redirected to Login if not or to home screen if logged in .

### Reproduction

https://github.com/scshiv29-dev/kirana-

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/​bottom-tabs
- [ ] @react-navigation/​drawer
- [X] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [ ] @react-navigation/​stack
- [ ] @react-navigation/​native-stack

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |6.0.13
| @react-navigation/material-bottom-tabs |6.2.4

| @react-navigation/native-stack         |6.9.0
| react-native-safe-area-context         |4.3.4
| react-native-screens                   |3.17.0
| react-native-gesture-handler           |2.6.2
| react-native-reanimated                |2.10.0
| react-native                           |0.70.1

| node                                   |
|  yarn                            |

**Comment by raajnadar** [comment]
Try adding the logic like this

```
<NavigationContainer
  screenOptions={{
     headerShown: false,
  }}>
    <Tab.Navigator>
      {state.user == null ? (
        <Tab.Screen name="Login" component={Login} />
      ) : (
        <>
          <Tab.Screen name="Home" component={Home} />
          <Tab.Screen name="Settings" component={Settings} />
        </>
    )}
  </Tab.Navigator>
</NavigationContainer>
```

**Comment by scshiv29-dev** [comment]
@raajnadar  yes i did this and its not working still tried using stack navigator instead doesn't work either. The user is null that i've logged and tested.  can you please tell me what i'm doing wrong here thanks

**Comment by raajnadar** [comment]
Closing the issue as this is not related to the library, it is some logical error on your codebase not in the library
