### ISSUE TITLE
@react-navigation/native-stack is being installed from another repository

### ISSUE THREAD

**Issue by b1ek** [react-navigation/react-navigation#10917]
### Current behavior

While installing `@react-navigation/native-stack`, following error occurs:
```
$ npx expo install @react-navigation/native-stack
› Installing 1 other package using npm
> npm install --save @react-navigation/native-stack
npm ERR! code 128
npm ERR! An unknown git error occurred
npm ERR! command git --no-replace-objects ls-remote ssh://git@github.com/react-native/native-stack.git
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
```
npm tries to install the library from https://github.com/react-native/native-stack . This repository does not even exists, and the `react-native` account is empty and last activity on it was years ago.

### Expected behavior

For it to get installed

### Reproduction

npx expo install @react-navigation/native-stack OR npm install --save @react-navigation/native-stack

### Platform

- [ ] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/​bottom-tabs
- [ ] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [ ] @react-navigation/​stack
- [X] @react-navigation/​native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.0.13 |
| react-native-screens                   | 3.15.0 |
| react-native                           | 0.69.6 |
| expo                                   | 46.0.13 |
| node                                   | 16.17.1 |
| npm                            | 8.15.0 |

**Comment by kacperkapusciak** [comment]
Hey @b1ek :wave:

I [(and 200k weekly downloads on npm)](https://www.npmjs.com/package/@react-navigation/native-stack) assure you that `@react-navigation/native-stack` is located in the correct repository on npm. The problem has to be located on your machine. Have you tinkered with your npm registry config?

I'm closing this issue as it is not actionable on our side.

Cheers

**Comment by b1ek** [comment]
@kacperkapusciak Yes, the problem was with the registry. I didn't touch it, but reseting the registry helped with the problem.
```
npm config delete registry
npm config set registry https://registry.npmjs.org/
npm update
```
