### ISSUE TITLE
useFocusEffect and useCallback do not detect dependency changes properly

### ISSUE THREAD

**Issue by t-a-y-l-o-r** [react-navigation/react-navigation#10911]
### Current behavior

When using `useFocusEffect` and `useCallback` in conjunction, changes in the dependency array for `useCallback` do not seem to update the function defined within `useCallback` as expected.

This seems related to other [issues opened](https://github.com/react-navigation/react-navigation/issues/8961) but turning off debugger does not help as indicated as I am able to reproduce this issue on my iphone.

Code that doesn't work:

When `user.permissions.faceID` is changed from `false` to `true` or vice versa this change does NOT reflect in the function as expected. In this specific case a user may update their permission settings and then re-authentication (such as when the app returns to foreground next)

It is important to note that we are using 2 callback functions here. One which relies on the user state, and another which will update it based on external factors (such as button presses etc)

```jsx
useFocusEffect(useCallback(() => {
    (async () => {
        if (user.permissions.faceID) {
            await checkFaceID();
        }
        await checkPinCode();
    })()
    
    return () => {
        // cleanup
    }
}, [user, refetchUser]));

const refetchUser = useCallback(() => {
    setUser(makeANetworkCall());
});
```

### Expected behavior

Dependencies would update the function definition as per normal.

### Reproduction

https://snack.expo.dev/f08LDEhbRq

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [X] MacOS

### Packages

- [ ] @react-navigation/​bottom-tabs
- [ ] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [ ] @react-navigation/​stack
- [ ] @react-navigation/​native-stack

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |  5.9.8
| @react-navigation/bottom-tabs          | 5.11.8
| @react-navigation/stack                | 5.14.9
| react-native                           | 0.65.1
| yarn                            | 1.22.19

**Comment by satya164** [comment]
please provide a "runnable" repro

**Comment by t-a-y-l-o-r** [comment]
Thank you for getting back so quickly! I've updated the link with a better (working) example of our exact use case as well as updated the code snippet and notes.

It seems that useCallback & useForcusEffect get weird when you have an update from another useCallback that isn't directly called by the "primary" useCallback

**Comment by t-a-y-l-o-r** [comment]
oh a third look I'm not able to properly reproduce this issue outside of our environment so it's probably not a problem with the library itself but something weird in our setup

I won't waste any more of you time, thank you
