### ISSUE TITLE
[Windows c#] TypeError: Cannot read properties of undefined (reading 'handleSetJSResponder')

### ISSUE THREAD

**Issue by chGalbadrakh** [react-navigation/react-navigation#10926]
### Current behavior

The following error occurs in the react-native-gesture-handler library used on drawer and stack.
"Windows application, Visual Studio 2019, Developed by c#"

![](https://user-images.githubusercontent.com/17295812/195008515-3459bf6b-22ce-4d62-a93a-1afbd640aef9.png)
9.5, react-native-windows version to 0.69.9, @react-navigation/native5.x->6.x
how solve this bug.

![](https://user-images.githubusercontent.com/17295812/195008519-01560371-340a-4a83-b82a-be9314b1ce06.png)

### Expected behavior

 I updgraded my React Native version to 0.69.5 and accordingly i upgraded the packages i use on React Navigation.
Upgraded libraries :
react-native: 0.64.2 -> 0.69.5
react-native-windows: 0.64.2 -> 0.69.9

Libraries used on React Navigation :
@react-navigation/drawer: 5.12.3 -> 6.5.0
@react-navigation/native: 5.9.2 -> 6.0.13
@react-navigation/stack: 5.14.2 -> 6.3.1
react-native-gesture-handler: 1.10.1 -> 2.7.0
react-native-reanimated: 1.113.2 -> 2.10.0
react-native-safe-area-context: 3.1.9 -> 4.4.1
react-native-screens: 2.17.1 -> 3.18.0

When i run debugging the above error is occurring on react-native-gesture-handler. If you have any method to fix this or any advice please share with me.
On IOS, debugging and release build are working fine.
The problem is RN Windows UWP c#.

### Reproduction

https://github.com/software-mansion/react-native-gesture-handler/issues/2266

### Platform

- [ ] Android
- [ ] iOS
- [ ] Web
- [X] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/​bottom-tabs
- [X] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [X] @react-navigation/​stack
- [ ] @react-navigation/​native-stack

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.0.13
| @react-navigation/drawer               |6.5.0
| @react-navigation/stack                |6.3.1
| react-native-safe-area-context         |4.4.1
| react-native-screens                   |3.18.0
| react-native-gesture-handler           |2.7.0
| react-native-reanimated                |2.10.0
| react-native                           |0.69.5
| node                                   |14.17.1
| yarn                            |1.22.18

**Comment by chGalbadrakh** [comment]
> The versions mentioned in the issue for the following packages differ from the latest versions on npm:
> 
> * `@react-navigation/stack` (found: `6.3.1`, latest: `6.3.2`)
> 
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?

Yes. It is not working properly on 6.3.2 either.

**Comment by Niranjans01** [comment]
@chGalbadrakh did any solutions work for you ?
