### ISSUE TITLE
App crashing when try to switch tabs with fabric and new architecture enabled in iOS

### ISSUE THREAD

**Issue by kartikmittal1996** [react-navigation/react-navigation#10925]
### Current behavior
![Simulator Screen Shot - iPhone 13 - 2022-10-13 at 23 21 01](https://user-images.githubusercontent.com/113685476/195679054-d3c3cd4a-aa9e-406e-ba38-e890765e7d18.png)
![Simulator Screen Shot - iPhone 13 - 2022-10-13 at 23 20 58](https://user-images.githubusercontent.com/113685476/195679057-b8a9bc1a-e829-47ca-aac1-310c55cfa6de.png)
![Simulator Screen Shot - iPhone 13 - 2022-10-13 at 23 20 54](https://user-images.githubusercontent.com/113685476/195679074-f1134a9a-a402-4c95-b66e-dd9829e4ee3b.png)

Hey, I am not able to implement tob tabs using react navigation with new architecture and fabric enabled in iOS. The errors are mentioned in the screenshots attached. Please check the errors and help to resolve as soon as possible. I have tried in the template project to make sure that no unnecessary code or other libraries creating this issue.

### Expected behavior

Tabs should work with fabric and new architecture enabled. 
Try to run app using yarn ios **RCT_NEW_ARCH_ENABLED** = 1 FABRIC_ENABLED=1

### Reproduction

https://github.com/kartikmittal1996/FabricTabNavigation

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/​bottom-tabs
- [ ] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [X] @react-navigation/​material-top-tabs
- [ ] @react-navigation/​stack
- [X] @react-navigation/​native-stack

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |6.0.13
| @react-navigation/material-top-tabs    |6.3.0
| @react-navigation/native-stack         |6.9.0
| react-native-safe-area-context         |4.4.1
| react-native-screens                   |3.18.1
| react-native-tab-view                  |3.3.0
| react-native-pager-view                |6.0.1
| react-native                           |0.70.1
| node                                   |16
| yarn                            |1.22.19

**Comment by kacperkapusciak** [comment]
Hi @kartikmittal1996 👋 

It seems like Fabric architecture in `react-native-pager-view` is extracted to a separate package. Please consult the documentation of this package https://github.com/callstack/react-native-pager-view#new-architecture-support-fabric

Cheers

**Comment by kartikmittal1996** [comment]
> Hi @kartikmittal1996 👋
> 
> It seems like Fabric architecture in `react-native-pager-view` is extracted to a separate package. Please consult the documentation of this package https://github.com/callstack/react-native-pager-view#new-architecture-support-fabric
> 
> Cheers

Thanks a lot @kkafar. I have been trying to find the issue from many days and you have resolved in few minutes. Thanks so much man.
