### ISSUE TITLE
`extractPathFromURL` broke query params when try to parse linking url

### ISSUE THREAD

**Issue by retyui** [react-navigation/react-navigation#10924]
### Current behavior

We use Firebase Dynamic Links to create links and configate linking to handle them

- Link that we used: `https://mysite.com/readPolicy?url=https%3A%2F%2Ftest.com`
- Then use Firebase API to get that ^^^ url:
  ```tsx
  await dynamicLinks().resolveLink("short url").url 
  ```
  Result: `https://mysite.com/readPolicy?url=https://test.com` (**as you see slashes non encoded now**)

- And then `react-navigation` try to parse this URL via `extractPathFromURL`
  ```tsx
  import extractPathFromURL from '@react-navigation/native/src/extractPathFromURL';

  test('extractPathFromURL', () => {
    expect(extractPathFromURL(['https://mysite.com'], 'https://mysite.com/readPolicy?url=https://test.com')).toBe(
      '/readPolicy?url=https://test.com',
    );
  });
  // test fail ^^^ because `extractPathFromURL` removed all double slashes
  // Expected: "/readPolicy?url=https://test.com"
  // Received: "/readPolicy?url=https:/test.com"
  ```

### Expected behavior

`extractPathFromURL` should not remove double slashes in query param of URL

### Reproduction

https://snack.expo.dev/see-unit-test-above^^^^

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/​bottom-tabs
- [ ] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [ ] @react-navigation/​stack
- [ ] @react-navigation/​native-stack

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.0.6
| @react-navigation/bottom-tabs          | 6.0.9
| @react-navigation/stack                | 6.0.11
| react-native-safe-area-context         | 3.2.2
| react-native-screens                   | 2.18.1
| react-native-gesture-handler           | 1.10.3
| react-native-reanimated                | 2.2.4
| react-native                           | 0.66.4
| node                                   | 14
| yarn                            | 1.x.x

**Comment by retyui** [comment]
any progress?

**Comment by etaiklein** [comment]
I'm also running into this for my use case.
After some digging, I discovered the root cause in [extractPathFromURL](https://github.com/react-navigation/react-navigation/blob/54739828598d7072c1bf7b369659e3682db3edc5/packages/native/src/extractPathFromURL.tsx#L8 
):
```
      .replace(/\/+/g, '/') // Replace multiple slash (//) with single ones
```

This seems intentional, but it's not documented why. Other routers seem to do this to support file browsing use cases (is that relevant for react navigation?)

For now, something like this is enough for my use case:
```
    if (param.includes('https:/') && !param.includes('https://')) {
      param.replace('https:/', 'https://');
    }
```

**Comment by retyui** [comment]
fixed in: https://github.com/react-navigation/react-navigation/pull/11528
