### ISSUE TITLE
Expo Firebase analytics causes stack to freeze the whole application

### ISSUE THREAD

**Issue by RGDEV2022** [react-navigation/react-navigation#10931]
### Current behavior

Adding `Expo firebase analytics` to an expo project with `stack` causes the routing to freeze completely after opening the first route. 

`native-stack` works fine,  but using stack freezes the whole application. 

Removing firebase analytics from the project lets stack work normal. 

[https://docs.expo.dev/versions/latest/sdk/firebase-analytics/](https://docs.expo.dev/versions/latest/sdk/firebase-analytics/)

### Expected behavior

Not freeze, behave like `native-stack`

### Reproduction

https://snack.expo.dev/

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/​bottom-tabs
- [ ] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [X] @react-navigation/​stack
- [ ] @react-navigation/​native-stack

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.0.2
| @react-navigation/stack                | 6.3.2
| @react-navigation/native-stack         | 6.1.0
| react-native                           | 0.68.2
| expo                                   |  45.0.0

**Comment by RGDEV2022** [comment]
> 

Verified. Not working.

**Comment by alterx** [comment]
@RGDEV2022 how did you fix this? I'm facing the same issue. Bottom Tab Navigator works, but the `stack` navigator freezes

**Comment by Hirurgo** [comment]
use_frameworks! cause of this issue

**Comment by AbdullahAnsarii** [comment]
The issue is still present in 

`@react-native-firebase/analytics": "^17.5.0,
  @react-native-firebase/app": "^17.5.0`

**Comment by guytepper** [comment]
@Hirurgo @AbdullahAnsarii did you find a solution for this issue?

**Comment by AbdullahAnsarii** [comment]
@guytepper Yes, it still exists

**Comment by jdponomarev** [comment]
same issue here

**Comment by AbdullahAnsarii** [comment]
Hi I have found the solution, please add `detachInactiveScreen={false}` in the Stack Navigator and it will work

**Example:**
`<Stack.Navigator detachInactiveScreens={Platform.OS === "ios" ? false : true}}>`
	
**Explanation:**
_Boolean used to indicate whether inactive screens should be detached from the view hierarchy to save memory. This enables integration with [react-native-screens](https://github.com/software-mansion/react-native-screens). Defaults to true._
