### ISSUE TITLE
Bottom Tabs Buggy with 120hz

### ISSUE THREAD

**Issue by sluhn-hershmangm** [react-navigation/react-navigation#10942]
### Current behavior

When testing bottom tabs on my iPhone 14 Pro, I notice a weird bug. When cycling between different tags, it seems that for a split second just after switching to a new tab, some of the information from the previous tab is frozen and appears on the new tab. 

In the Snack link below, you can see this bug. Open the link and change "<Tab.Screen name="Home" component={HomeScreen} />" to "<Tab.Screen name="Helloooooooo" component={HomeScreen} />" (it's just to make the text longer to see the problem better). Also, change the text of the Home title to something with more characters. Run the code on a device with a 120Hz refresh rate screen. Switch between the two tabs on a display with 120Hz and you can see this issue. 

Is there a way to get around this?

### Expected behavior

When switching between tabs on 120Hz refresh rate phones using Bottom Tabs, there should not be any freezing.

### Reproduction

https://snack.expo.io/?platform=android&name=Bottom%20Tabs%20Navigator%20%7C%20React%20Navigation&dependencies=%40expo%2Fvector-icons%40*%2C%40react-native-community%2Fmasked-view%40*%2Creact-native-gesture-handler%40*%2Creact-native-pager-view%40*%2Creact-native-paper%40%5E4.7.2%2Creact-native-reanimated%40*%2Creact-native-safe-area-context%40*%2Creact-native-screens%40*%2Creact-native-tab-view%40%5E3.0.0%2C%40react-navigation%2Fbottom-tabs%406.3.1%2C%40react-navigation%2Fdrawer%406.4.1%2C%40react-navigation%2Felements%401.3.3%2C%40react-navigation%2Fmaterial-bottom-tabs%406.2.1%2C%40react-navigation%2Fmaterial-top-tabs%406.2.1%2C%40react-navigation%2Fnative-stack%406.6.1%2C%40react-navigation%2Fnative%406.0.10%2C%40react-navigation%2Fstack%406.2.1&hideQueryParams=true&sourceUrl=https%3A%2F%2Freactnavigation.org%2Fexamples%2F6.x%2Ftab-based-navigation-minimal.js

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/​bottom-tabs
- [ ] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [ ] @react-navigation/​stack
- [ ] @react-navigation/​native-stack

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |^6.0.13|
| @react-navigation/bottom-tabs          |^6.4.0|
| @react-navigation/drawer               |
| @react-navigation/material-bottom-tabs |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                |
| @react-navigation/native-stack         |
| react-native-safe-area-context         |
| react-native-screens                   |
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           |
| expo                                   |
| node                                   |
| npm or yarn                            |

**Comment by joshnissenbaum** [comment]
This is still an issue

**Comment by radko93** [comment]
There is a repro for this issue.

**Comment by Fortidude** [comment]
Im still able to reproduce it. I guess it's due to JS based animations.
