### ISSUE TITLE
Could not load an app when i use React Navigator

### ISSUE THREAD

**Issue by radevinicius** [react-navigation/react-navigation#10949]
### Current behavior

When i use the drawer navigation, the app stop to compile in the emulator

On App.js:

import { StyleSheet, Text, View, Dimensions} from 'react-native'
import React from 'react'
import RootNavigator from './src/navigations/RootNavigator'

const App = () => {
  return (
          <RootNavigator/>  
  )
}
export default App;
  const styles = StyleSheet.create({
container:{
  flex:1
}
});

On RootNavigator:

import * as React from 'react';
import DrawerNavigator from '../navigations/DrawerNavigator'
import { NavigationContainer } from '@react-navigation/native';

export default function RootNavigator(){
    return(        
        <NavigationContainer>
             <DrawerNavigator/>       
        </NavigationContainer>
        )
}

On DrawerNavigator:

import * as React from 'react';
import { createDrawerNavigator } from '@react-navigation/drawer';
import { HomeStack } from './StackNavigators';
import { colors } from 'react-native-elements';
import {Icon} from 'react-native-elements';

const Drawer = createDrawerNavigator();

export default function DrawerNavigator(){
    return(     
        <Drawer.Navigator>
            <Drawer.Screen 
                name = "HomeStack"
                component = {HomeStack}
                options = {{
                    title:"Home",
                    drawerIcon: ({focussed,size})=><Icon type = "material-community" 
                                                         name = "home"
                                                         color = {focussed? '#7cc':colors.gray2}
                                                         size = {size}
                                                         />,
               headerShown : false                                  
                }}
            />
        </Drawer.Navigator>  
    )
}

When i doesn't use DrawerNavigator on RootNavigator like this:

import * as React from 'react';
import DrawerNavigator from '../navigations/DrawerNavigator'
import { NavigationContainer } from '@react-navigation/native';

export default function RootNavigator(){
    return(        
        <HomeScrenn/>
        )
}

The App loads normaly

### Expected behavior

I expect the app works fine

### Reproduction

https://github.com/radevinicius?tab=repositories

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/​bottom-tabs
- [X] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [X] @react-navigation/​stack
- [X] @react-navigation/​native-stack

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |
| @react-navigation/drawer               |
| @react-navigation/stack                |
| @react-navigation/native-stack         |
| react-native-safe-area-context         |
| react-native-screens                   |
| react-native-reanimated                |
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           |
| expo                                   |
| node                                   |
| npm or yarn                            |

**Comment by raajnadar** [comment]
Fill in the version of the libraries you use or else I will close the issue ticket
