### ISSUE TITLE
When i use DrawerNavigator the app stop to compile

### ISSUE THREAD

**Issue by radevinicius** [react-navigation/react-navigation#10950]
### Current behavior

``### Current behavior

When i use the drawer navigation, the app stop to compile in the emulator

On App.js:

```
import { StyleSheet, Text, View, Dimensions} from 'react-native'
import React from 'react'
import RootNavigator from './src/navigations/RootNavigator'

const App = () => {
  return (
          <RootNavigator/>  
  )
}
export default App;
  const styles = StyleSheet.create({
container:{
  flex:1
}
});
```

On RootNavigator:

```
import * as React from 'react';
import DrawerNavigator from '../navigations/DrawerNavigator'
import { NavigationContainer } from '@react-navigation/native';

export default function RootNavigator(){
    return(        
        <NavigationContainer>
             <DrawerNavigator/>       
        </NavigationContainer>
        )
}
```

On DrawerNavigator:

```
import * as React from 'react';
import { createDrawerNavigator } from '@react-navigation/drawer';
import { HomeStack } from './StackNavigators';
import { colors } from 'react-native-elements';
import {Icon} from 'react-native-elements';

const Drawer = createDrawerNavigator();

export default function DrawerNavigator(){
    return(     
        <Drawer.Navigator>
            <Drawer.Screen 
                name = "HomeStack"
                component = {HomeStack}
                options = {{
                    title:"Home",
                    drawerIcon: ({focussed,size})=><Icon type = "material-community" 
                                                         name = "home"
                                                         color = {focussed? '#7cc':colors.gray2}
                                                         size = {size}
                                                         />,
               headerShown : false                                  
                }}
            />
        </Drawer.Navigator>  
    )
}

```

When i doesn't use DrawerNavigator on RootNavigator like this:
```

import * as React from 'react';
import DrawerNavigator from '../navigations/DrawerNavigator'
import { NavigationContainer } from '@react-navigation/native';

export default function RootNavigator(){
    return(        
        <HomeScrenn/>
        )
}
```

The App loads normaly

### Expected behavior

I expect when i use drawerNavigator the apps loads normaly

### Reproduction

https://snack.expo.dev/@radevinicius/97b9a1

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/​bottom-tabs
- [X] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [X] @react-navigation/​stack
- [X] @react-navigation/​native-stack

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |
| @react-navigation/bottom-tabs          |
| @react-navigation/drawer               |
| @react-navigation/material-bottom-tabs |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                |
| @react-navigation/native-stack         |
| react-native-safe-area-context         |
| react-native-screens                   |
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           |
| expo                                   |
| node                                   |
| npm or yarn                            |

**Comment by itachi1101** [comment]
same issue still. So I made a new project and just install react navigation and drawer navigation and followed all the steps still the app crashes as soon as I use this.

**Comment by ArturoTorresMartinez** [comment]
Same issue
