### ISSUE TITLE
tabBarIcon are called many times with parameters of all screens

### ISSUE THREAD

**Issue by exzos28** [react-navigation/react-navigation#10952]
### Current behavior

```
...
      <Screen
        name="Dashboard"
        options={{
          title: 'Dashboard',
          tabBarIcon: props => {
            console.log('props', props);
            return null;
          },
        }}
        component={DashboardScreen}
      />
...
```
i just change screen focus and get multiple call to tabBarIcon

 LOG  props {"color": "#F7931A", "focused": true, "size": 25}
 LOG  props {"color": "#808080", "focused": false, "size": 25}
 LOG  props {"color": "#F7931A", "focused": true, "size": 25}
 LOG  props {"color": "#808080", "focused": false, "size": 25}
 LOG  props {"color": "#F7931A", "focused": true, "size": 25}
 LOG  props {"color": "#808080", "focused": false, "size": 25}
 LOG  props {"color": "#F7931A", "focused": true, "size": 25}
 LOG  props {"color": "#808080", "focused": false, "size": 25}

### Expected behavior

One call

### Reproduction

https://snack.expo.dev/X16hJ-44s

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/​bottom-tabs
- [ ] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [ ] @react-navigation/​stack
- [ ] @react-navigation/​native-stack

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.0.13
| @react-navigation/bottom-tabs          | 6.4.0
| @react-navigation/stack                | 6.3.2
| react-native-safe-area-context         |
| react-native-screens                   |
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native                           |
| expo                                   |
| node                                   |
| yarn                            |

**Comment by exzos28** [comment]
anyone?

**Comment by satya164** [comment]
This is not a bug, it's working as intended https://github.com/react-navigation/react-navigation/blob/a2e5f45c0ec603bb276c2e27595b4137fa3a85eb/packages/bottom-tabs/src/views/TabBarIcon.tsx#L44

**Comment by exzos28** [comment]
> This is not a bug, it's working as intended
> 
> https://github.com/react-navigation/react-navigation/blob/a2e5f45c0ec603bb276c2e27595b4137fa3a85eb/packages/bottom-tabs/src/views/TabBarIcon.tsx#L44

sounds bad, how do I know if the icon is actually in focus via tabBarIcon?

**Comment by satya164** [comment]
> sounds bad, how do I know if the icon is actually in focus via tabBarIcon

`tabBarIcon` function isn't intended for doing side-effects. you need to rethink your strategy if you are doing something on focus inside the icon's getter

**Comment by exzos28** [comment]
> `tabBarIcon` function isn't intended for doing side-effects. you need to rethink your strategy if you are doing something on focus inside the icon's getter

I just wanted to animate the icon change

**Comment by satya164** [comment]
You can use the `tabBarButton` prop to provide your own buttons where you can do animations
