### ISSUE TITLE
Swipe back gesture bug

### ISSUE THREAD

**Issue by jb-5murf** [react-navigation/react-navigation#10961]
### Current behavior

e.preventDefault() in 'beforeRemove' listener doesnt work when going back by swipe gesture. Instead of staying on the screen it goes back.

### Expected behavior

Should cancel going back like in v5.

### Reproduction

https://snack.expo.dev/@jb5/react-navigation-swipe-back-bug

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/​bottom-tabs
- [ ] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [X] @react-navigation/​stack
- [ ] @react-navigation/​native-stack

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.0.13
| @react-navigation/bottom-tabs          |
| @react-navigation/drawer               |
| @react-navigation/material-bottom-tabs |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                | 6.3.2
| @react-navigation/native-stack         |
| react-native-safe-area-context         | 4.3.1
| react-native-screens                   | 3.15.0
| react-native-gesture-handler           | 2.5.0
| react-native-reanimated                |
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           |
| expo                                   | 46.0.0
| node                                   |
| npm or yarn                            |

**Comment by kacperkapusciak** [comment]
Hi @jb-5murf 👋 
Thanks for letting us know! I've reverted the change that was causing the bug. It should be all good in @react-navigation/stack `6.3.3`.

Cheers

**Comment by jb-5murf** [comment]
Perfect &#128077; Thank you!
