### ISSUE TITLE
Object create getter, setter after passed navigation router params

### ISSUE THREAD

**Issue by Eumhongin** [react-navigation/react-navigation#10960]
### Current behavior

get my data from server like this

![스크린샷 2022-10-25 오후 12 23 01](https://user-images.githubusercontent.com/23710025/197674931-47233518-24d6-4ec8-a8ad-c6b59ef14a14.png)

but after passed

![스크린샷 2022-10-25 오후 12 24 52](https://user-images.githubusercontent.com/23710025/197675167-dacc661e-9e6d-4910-b2b5-d3ba3651523e.png)
![스크린샷 2022-10-25 오후 12 25 02](https://user-images.githubusercontent.com/23710025/197675201-49e90053-77e8-4443-af4c-2e31cc6c3585.png)

why getter and setter created?
is navigation problem? or my personal setting is problem?

This is my dependency
"react": "17.0.2",
"react-native": "0.66.3",
"@react-navigation/bottom-tabs": "^6.0.9",
"@react-navigation/native": "^6.0.12",
"@react-navigation/native-stack": "^6.8.0",

### Expected behavior

not showed getter and setter

### Reproduction

.

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/​bottom-tabs
- [ ] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [X] @react-navigation/​stack
- [X] @react-navigation/​native-stack

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | ^6.0.12
| @react-navigation/bottom-tabs          | ^6.0.9
| @react-navigation/drawer               |
| @react-navigation/material-bottom-tabs |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                | 
| @react-navigation/native-stack         | ^6.8.0
| react-native-safe-area-context         | ^4.3.3
| react-native-screens                   | ^3.17.0
| react-native-gesture-handler           |
| react-native-reanimated                | ^2.8.0
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           | 0.66.3
| expo                                   |
| node                                   | v16.15.0
| yarn                            |  1.22.19

**Comment by ddikodroid** [comment]
> ### Current behavior
> get my data from server like this
> 
> ![스크린샷 2022-10-25 오후 12 23 01](https://user-images.githubusercontent.com/23710025/197674931-47233518-24d6-4ec8-a8ad-c6b59ef14a14.png)
> 
> but after passed
> 
> ![스크린샷 2022-10-25 오후 12 24 52](https://user-images.githubusercontent.com/23710025/197675167-dacc661e-9e6d-4910-b2b5-d3ba3651523e.png) ![스크린샷 2022-10-25 오후 12 25 02](https://user-images.githubusercontent.com/23710025/197675201-49e90053-77e8-4443-af4c-2e31cc6c3585.png)
> 
> why getter and setter created? is navigation problem? or my personal setting is problem?
> 
> This is my dependency "react": "17.0.2", "react-native": "0.66.3", "@react-navigation/bottom-tabs": "^6.0.9", "@react-navigation/native": "^6.0.12", "@react-navigation/native-stack": "^6.8.0",
> 
> ### Expected behavior
> not showed getter and setter
> 
> ### Reproduction
> .
> 
> ### Platform
> * [x]  Android
> * [x]  iOS
> * [ ]  Web
> * [ ]  Windows
> * [ ]  MacOS
> 
> ### Packages
> * [x]  @react-navigation/​bottom-tabs
> * [ ]  @react-navigation/​drawer
> * [ ]  @react-navigation/​material-bottom-tabs
> * [ ]  @react-navigation/​material-top-tabs
> * [x]  @react-navigation/​stack
> * [x]  @react-navigation/​native-stack
> 
> ### Environment
> * [] I've removed the packages that I don't use
> 
> package	version
> @react-navigation/native	^6.0.12
> @react-navigation/bottom-tabs	^6.0.9
> @react-navigation/drawer	
> @react-navigation/material-bottom-tabs	
> @react-navigation/material-top-tabs	
> @react-navigation/stack	
> @react-navigation/native-stack	^6.8.0
> react-native-safe-area-context	^4.3.3
> react-native-screens	^3.17.0
> react-native-gesture-handler	
> react-native-reanimated	^2.8.0
> react-native-tab-view	
> react-native-pager-view	
> react-native	0.66.3
> expo	
> node	v16.15.0
> yarn	1.22.19

did solve this issue?
