### ISSUE TITLE
Navigating between screen siblings won't emit blur event on second screen

### ISSUE THREAD

**Issue by NordlingDev** [react-navigation/react-navigation#10980]
### Current behavior

When having multiple screens inside a StackNavigator, `useIsFocused()` doesn't change to `false` on screen B when going from A > B > A. Only A gets an ever changing value from `useIsFocused()`.

Even `navigation.addListener('blur', ...)` doesn't fire on screen B, while it does on screen A.

See Snack repro link for details. See the console log for details where each change in `useIsFocused()` will log its new state for each screen.

### Expected behavior

All screens in such scenario should emit blur events.

### Reproduction

https://snack.expo.dev/@nordlingdev/screen-navigation-focus-and-blur-events

### Platform

- [ ] Android
- [X] iOS
- [X] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/​bottom-tabs
- [ ] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [ ] @react-navigation/​stack
- [X] @react-navigation/​native-stack

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | ^6.0.13
| @react-navigation/native-stack         | ^6.9.1
| react-native-safe-area-context         | 4.3.1
| react-native-screens                   | ~3.15.0
| react-native                           | 0.69.6
| expo                                   | 46.0.0

**Comment by satya164** [comment]
The screen is immediately unmounted when going back in a native stack. It can't receive blur events since it's not mounted anymore.

If you need to do some cleanup, you can use `useFocusEffect`/`useEffect`'s cleanup function to do the cleanup according to what you need.
