### ISSUE TITLE
Force close when navigate (Android)

### ISSUE THREAD

**Issue by sandirr** [react-navigation/react-navigation#10994]
### Current behavior

<Pressable
          style={styles.ml1}
          onPress={() => navigation.navigate('referral')}>
          <Image source={Images.Earn} style={styles.action} />
        </Pressable>
        
  If I click it, it will navigate well but only in iOS. In android it will force close without error message

### Expected behavior

Can navigate well in Android

### Reproduction

-

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/​bottom-tabs
- [ ] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [ ] @react-navigation/​stack
- [X] @react-navigation/​native-stack

### Environment

    "@react-navigation/bottom-tabs": "^6.4.0",
    "@react-navigation/native": "^6.0.13",
    "@react-navigation/native-stack": "^6.9.1",

**Comment by hodacthanhminh** [comment]
I have a same problems. When i navigate to which screen using `KeyboardAvoidingView` (react-native components) my screen is zoom out then force close? https://github.com/facebook/react-native/issues/35278 here the same issue of my team when develop company applications! Please help
