### ISSUE TITLE
Can't merge params when navigating to nested screen

### ISSUE THREAD

**Issue by gorandalum** [react-navigation/react-navigation#10995]
### Current behavior

In React Navigation 6 the `merge` param is required when navigating if the params should be merged with the already existing params in the screen.

This is working as intended as the existing fields in the `HomeScreen` is still preserved:
```tsx
props.navigation.navigate({
  name: "HomeScreen",
  params: {
    field1: "Field value 1"
  },
  merge: true
}
```

However when we navigate to a nested screen, then this is not working:
```tsx
props.navigation.navigate({
  name: "HomeStack",
  params: {
    screen: "HomeSubScreen",
    params: {
      field1: "Field value 1",
    }
  },
  merge: true // Not working
}
```

In [this issue](https://github.com/react-navigation/react-navigation/issues/10310) it was mentioned that:
> merge: true needs to be at the correct level for it to merge the params. If you want to merge the nested params, then it should be specified in the nested object, not in the root.

However I can't see how this is possible. This isn't working, and also gives typescript-error:
```tsx
props.navigation.navigate({
  name: "HomeStack",
  params: {
    screen: "HomeSubScreen",
    params: {
      field1: "Field value 1",
    },
    merge: true // Not working, and not in the typing
  }
}
```

To reproduce on sandbox:
- Navigate to the ProfileScreen
- Navigate to the HomeScreen with link 1. to fill both title and content
- Navigate back go ProfileScreen
- Try another link than 1. to see that only title is filled
- Reiterate by going through link 1, then using another link.

The situation here is link 4. and 5. which doesn't update the field `content` even though `merge` is `true`.

### Expected behavior

It should be possible to navigate to a nested screen while also merging params.

### Reproduction

https://codesandbox.io/s/navigation-test-forked-xe01q9

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/​bottom-tabs
- [ ] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [X] @react-navigation/​stack
- [ ] @react-navigation/​native-stack

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |6.0.13
| @react-navigation/bottom-tabs          |6.4.0
| @react-navigation/stack                |6.3.4
| react-native-safe-area-context         |3.3.2
| react-native-screens                   |3.18.2
| react-native                           |0.66.5

**Comment by baesumin** [comment]
me too

**Comment by minemos** [comment]
same here

**Comment by minemos** [comment]
Not perfect solution, but using state can solve this problem


```jsx
const [a, setA] = useState(route.params.a);
const [b, setB] = useState(route.params.b);
useEffect(() => {
    if(a !== route.params.a) setA(route.params.a)
    if(b !== route.params.b) setB(route.params.b)
}, [route.params]);
```
