### ISSUE TITLE
Deeplinks are not working in background

### ISSUE THREAD

**Issue by Estevete** [react-navigation/react-navigation#10990]
### Current behavior

Deeplink is not working if we try to open it when the app is in background

**Warning message:**
`The navigation state parsed from the URL contains routes not present in the root navigator. This usually means that the linking configuration doesn't match the navigation structure. See https://reactnavigation.org/docs/configuring-links for more details on how to specify a linking configuration.d using the Authentication Flow.`

### Expected behavior

Deeplink should open the related screen.

### Reproduction

https://github.com/MADSENSE/Madsense.ReactNative.Sample

### Platform

- [X] Android
- [X] iOS
- [ ] Web

### Packages

- [X] @react-navigation/​bottom-tabs
- [X] @react-navigation/​drawer
- [x] @react-navigation/​material-bottom-tabs
- [x] @react-navigation/​material-top-tabs
- [X] @react-navigation/​stack
- [x] @react-navigation/​native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.0.13
| @react-navigation/bottom-tabs          | 6.4.0
| @react-navigation/drawer               | 6.5.0
| @react-navigation/material-bottom-tabs | 6.2.4
| @react-navigation/material-top-tabs    | 6.3.0
| @react-navigation/stack                | 6.3.4
| @react-navigation/native-stack         | 6.6.1
| react-native                           | 0.69.5, 0.70.5
| expo                                   | 46.0.9, 47.0.3

**Comment by sahil-republic** [comment]
I have updated this to the latest versions and it still does not work for me.

**Comment by satya164** [comment]
Your navigation container shouldn't be rendered until you have resolved the login info. The splash screen should be rendered separately and not be a screen, like shown here: https://reactnavigation.org/docs/auth-flow/#define-our-screens

**Comment by Estevete** [comment]
> Your navigation container shouldn't be rendered until you have resolved the login info.

To be honest, I don't understand this point, since in the docs the NavigationContainer is always rendered and we "switch" stacks whether user is logged in or not.

[Example from the docs](https://snack.expo.io/?platform=android&name=Authentication%20flows%20%7C%20React%20Navigation&dependencies=%40expo%2Fvector-icons%40*%2C%40react-native-community%2Fmasked-view%40*%2Creact-native-gesture-handler%40*%2Creact-native-pager-view%40*%2Creact-native-paper%40%5E4.7.2%2Creact-native-reanimated%40*%2Creact-native-safe-area-context%40*%2Creact-native-screens%40*%2Creact-native-tab-view%40%5E3.0.0%2C%40react-navigation%2Fbottom-tabs%406.3.1%2C%40react-navigation%2Fdrawer%406.4.1%2C%40react-navigation%2Felements%401.3.3%2C%40react-navigation%2Fmaterial-bottom-tabs%406.2.1%2C%40react-navigation%2Fmaterial-top-tabs%406.2.1%2C%40react-navigation%2Fnative-stack%406.6.1%2C%40react-navigation%2Fnative%406.0.10%2C%40react-navigation%2Fstack%406.2.1&hideQueryParams=true&sourceUrl=https%3A%2F%2Freactnavigation.org%2Fexamples%2F6.x%2Fauth-flow.js)

**Comment by Estevete** [comment]
@satya164 So I have pushed some links into it. You can check that, if we leave the app in background in the SignIn screen and you try to deep link to `exp://{your-ip:port}/--/profile` it will display the error.

If you sign in, leave the app in background and try to open the same deep link, we navigate to the `ProfileScreen`.

**Comment by Estevete** [comment]
> > You can check that, if we leave the app in background in the SigninScreen and you try to deep link to exp://{your-ip:port}/--/profile it will display the error.
> 
> If the user is not logged in, how can it open the profile screen? Given that the profile screen is only accessible after logging in.

Yeah, I'm not trying to navigate but to save the url so the user gets redirected once he logs in, in the end, it's a screen that really exists in the app but it's not accessible until user is logged in. 

For example, a user receives an email with a link. He taps on it and he has to login, once he logs in, he's redirected to the given link.
With this behavior this cannot be achieved.
