### ISSUE TITLE
animationEnabled: false is being ignored for material-top-tabs

### ISSUE THREAD

**Issue by Dakuan** [react-navigation/react-navigation#10997]
### Current behavior

set animation: false, but animations still occur

```
      <Tab.Navigator
        tabBar={(props) => <TabBar {...props} />}
        screenOptions={{
          tabBarPressColor: "white",
          swipeEnabled: false,
          tabBarScrollEnabled: true,
          animationEnabled: false
        }}
      >
```

### Expected behavior

animations should be disable

### Reproduction

..

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/​bottom-tabs
- [ ] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [X] @react-navigation/​material-top-tabs
- [ ] @react-navigation/​stack
- [ ] @react-navigation/​native-stack

### Environment

- [X] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/material-top-tabs    | ^6.3.0 |

**Comment by Dakuan** [comment]
peer dep https://github.com/satya164/react-native-tab-view/releases needs bumping to > 3.2.1

**Comment by okwasniewski** [comment]
Hey, this should be resolved by upgrading `react-native-tab-view` to latest version. Closing this
