### ISSUE TITLE
Cannot swipe back to last screen only works when my finger start swiping on the left first position

### ISSUE THREAD

**Issue by shop-fluencer** [react-navigation/react-navigation#11013]
### Current behavior

why I can not swipe back on iOS where my finger is in any position ? I can only swipe back while my finger is on the left position look at the video

I have linked an expo but this expo is only an example , its not work in any other projects

https://user-images.githubusercontent.com/101994056/202579150-e54704e5-bf5a-4418-a8da-2d4ad707c9c2.mp4

### Expected behavior

I want to swipe back while my finger is in any position

### Reproduction

https://snack.expo.dev/@adhithi/react-navigation---stack-navigator-example

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/​bottom-tabs
- [ ] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [X] @react-navigation/​stack
- [X] @react-navigation/​native-stack

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               6.0.13
| @react-navigation/native-stack         6.9.1
| react-native-safe-area-context         4.4.1
| react-native-screens                   3.15
| react-native-gesture-handler           2.5.0
| react-native-reanimated                2.9.1
| react-native-tab-view                  3.1.1
| react-native-pager-view                5.4.24
| expo                          46.0.0
| expo                                   |
| node                                   |
| npm or yarn                            |

**Comment by shop-fluencer** [comment]
> The versions mentioned in the issue for the following packages differ from the latest versions on npm:
> 
> * `@react-navigation/native` (found: `6.0.12`, latest: `6.0.13`)
> 
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?

Still happens

**Comment by Gregoirevda** [comment]
@shop-fluencer You can only modify this in `@react-navigation/​stack` with `gestureResponseDistance` 
for full screen swipe back use
`const screenWidth = useWindowDimensions();`

https://reactnavigation.org/docs/stack-navigator#gestureresponsedistance

**Comment by amanptl** [comment]
Try adding `fullScreenGestureEnabled: true` to `screenOptions` of your `Stack.Navigator`. Also it is only supported by Native Stack Navigator which is created using `createNativeStackNavigator();`

**Comment by shop-fluencer** [comment]
> Try adding `fullScreenGestureEnabled: true` to `screenOptions` of your `Stack.Navigator`. Also it is only supported by Native Stack Navigator which is created using `createNativeStackNavigator();`

Thank you very much!!
