### ISSUE TITLE
Drawer Toggle-Icon not visible in React-Native app inside NX-Monorepo

### ISSUE THREAD

**Issue by therawk** [react-navigation/react-navigation#11016]
### Current behavior

The default drawer toggle icon isn't visible. The margins, width and height settings are applied and also opening the drawer works.
Tint colour also doesn't make a difference.

**Information to running the project:**
Since the metro packager sometimes crashes I recommend running it in a seperate terminal window.
Start it with `npx nx start` optionally `npx nx start --reset-cache`
So when it crashes during compilation you can just restart it again.

In another terminal run `npx nx run-android --active-arch-only`

![Screenshot_20221119-130750](https://user-images.githubusercontent.com/24702753/202850101-69e22b8f-b157-4d9c-8f53-fe6de5ba24da.png)
![Screenshot_20221119-130746](https://user-images.githubusercontent.com/24702753/202850102-e8d4af96-3da6-4653-90fc-65eb3479249f.png)

### Expected behavior

Drawer toggle icon is visible

### Reproduction

https://github.com/therawk/react-navigation-issue

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/​bottom-tabs
- [X] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [ ] @react-navigation/​stack
- [ ] @react-navigation/​native-stack

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.0.13
| @react-navigation/drawer               | 6.5.0
| react-native-safe-area-context         | 4.4.1
| react-native-screens                   | 3.18.2
| react-native-gesture-handler           | 2.8.0
| react-native-reanimated                | 2.13.0
| react-native                           | 0.70.1
| node                                   | 16.17.0
| npm                                    | 8.15.0

**Comment by satya164** [comment]
It's a metro bug, unrelated to React Navigation. You can workaround it similar to this: https://github.com/react-navigation/react-navigation/blob/9041069ec495e7a58aead43dc11ad8b97b3b34dd/example/metro.config.js#L80
