### ISSUE TITLE
material-top-tabs typescript required attribute warnings

### ISSUE THREAD

**Issue by vlkpa** [react-navigation/react-navigation#11014]
### Current behavior

![image](https://user-images.githubusercontent.com/78504015/202659507-06cf2978-a02a-4950-a9aa-448f3d7b4d5c.png)
tsconfig.json
![image](https://user-images.githubusercontent.com/78504015/202660807-b339652f-ab62-4b76-966e-b656810230cc.png)

### Expected behavior

Is it really required ?

### Reproduction

https://github.com/react-navigation/react-navigation/tree/main/example

### Platform

- [ ] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/​bottom-tabs
- [ ] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [X] @react-navigation/​material-top-tabs
- [ ] @react-navigation/​stack
- [ ] @react-navigation/​native-stack

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.0.13
| @react-navigation/bottom-tabs          | 6.2.4
| @react-navigation/material-bottom-tabs | 6.2.4
| @react-navigation/material-top-tabs    | 6.3.0
| @react-navigation/stack                | 6.3.4
| react-native-gesture-handler           | 2.5.0
| react-native-reanimated                | 2.5.0
| react-native-tab-view                  | 2.16.0
| react-native-pager-view                | 6.1.0
| react-native                           | 0.66.5
| yarn                            | 3.1.1

**Comment by huanguolin** [comment]
same issue here:
```ts
Type '{ children: Element[]; screenOptions: MaterialTopTabNavigationOptions; initialRouteName: string; }' is missing the following properties from type 'Omit<DefaultRouterOptions<string> & { id?: string | undefined; children: ReactNode; screenListeners?: Partial<{ tabPress: EventListenerCallback<MaterialTopTabNavigationEventMap, "tabPress">; ... 6 more ...; beforeRemove: EventListenerCallback<...>; }> | ((props: { ...; }) => Partial<...>) | undefined; screenOptions?...': keyboardDismissMode, springConfig, timingConfig, tabBarPosition, and 2 more.ts(2740)
No quick fixes available

```

**Comment by okwasniewski** [comment]
Hey, updating to `react-native-tab-view@3.3.0` should solve the issue. Closing this as resolved.
