### ISSUE TITLE
Reuse screens inside different navigators with Typescript

### ISSUE THREAD

**Issue by pasquale95** [react-navigation/react-navigation#11028]
### Current behavior

I reopen an issue which has not been closed without being solved (https://github.com/react-navigation/react-navigation/issues/8139).
I want to use the same screen in two different navigators, something like the following:

```jsx
import React from 'react';
import {
  createStackNavigator,
  StackScreenProps,
} from '@react-navigation/stack';
import { Text } from 'react-native';
import { NavigationContainer } from '@react-navigation/native';

export type Navigator1ParamsList = {
  screen1: ReusableScreenParamsList;
};

const Stack1 = createStackNavigator<Navigator1ParamsList>();

function Navigator1() {
  return (
    <Stack1.Navigator>
      <Stack1.Screen
        name="screen1"
        component={ReusableScreen}
        initialParams={{
          text: 'hello from Stack1',
        }}
      />
    </Stack1.Navigator>
  );
}

export type Navigator2ParamsList = {
  screen2: ReusableScreenParamsList;
};

const Stack2 = createStackNavigator<Navigator2ParamsList>();

function Navigator2() {
  return (
    <Stack2.Navigator>
      <Stack2.Screen
        name="screen2"
        component={ReusableScreen} // with tsx error highlights here
        initialParams={{
          text: 'hello from Stack2',
        }}
      />
    </Stack2.Navigator>
  );
}

type Props = StackScreenProps<Navigator1ParamsList, 'screen1'>;

type ReusableScreenParamsList = {
  text: string;
};

const ReusableScreen = ({ route }: Props) => {
  const { text } = route.params;
  return <Text>{text}</Text>;
};

export type RootStackParamsList = {
  stack1: undefined;
  stack2: undefined;
};

const RootStack = createStackNavigator<RootStackParamsList>();

const App = () => {
  return (
    <NavigationContainer>
      <RootStack.Navigator initialRouteName='stack1'>
        <RootStack.Screen name="stack1" component={Navigator1} />
        <RootStack.Screen name="stack2" component={Navigator2} />
      </RootStack.Navigator>
    </NavigationContainer>
  );
};

export default App;
```

However, by using TypeScript an error prompts when I use the component `ReusableScreen` inside `Stack2.Navigator`. How to solve this problem?

### Expected behavior

The expectation would be to have a possibility to use the component in different navigators without problems.

### Reproduction

https://snack.expo.dev/@pasquale95/trembling-popcorn

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/​bottom-tabs
- [X] @react-navigation/​drawer
- [X] @react-navigation/​material-bottom-tabs
- [X] @react-navigation/​material-top-tabs
- [X] @react-navigation/​stack
- [X] @react-navigation/​native-stack

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.0.14 |
| @react-navigation/bottom-tabs          | 6.4.1 |
| @react-navigation/drawer               | 6.5.1 |
| @react-navigation/material-bottom-tabs | 6.2.5 |
| @react-navigation/material-top-tabs    | 6.3.1 |
| @react-navigation/stack                | 6.3.5 |

**Comment by semreg** [comment]
@pasquale95 actually there is another approach.
You may define screen params directly in your component and then use `useRoute()` hook from `@react-navigation/native`. The same thing with navigation actually.
It may look something like this:

```typescript
import { RouteProp, useNavigation, useRoute } from '@react-navigation/native'

type Params = {
  text: string
}

const ReusableScreen: FC = () => {
  const { params } = useRoute<RouteProp<{ params: Params }, 'params'>>()
  const navigation = useNavigation()
  
  ...
  
  return <Text>{params.text}</Text>
}
```

But I am not sure of cons if there are any

**Comment by satya164** [comment]
I recommend using `useNavigation` instead of the `navigation` prop, for reusable screens (or in general) since it's more typesafe.

For the `route` prop, instead of using `StackScreenProps` that defines the type for both `navigation` and `route` props, I'd annotate only the `route` prop to avoid the errors.

**Comment by semreg** [comment]
@satya164 so using `useRoute` is a good practice in general or just for reusable screens?

**Comment by satya164** [comment]
@semreg for `route`, I prefer the `route` prop since the navigator will error if you don't pass the correct type. but instead of `type Props = StackScreenProps<Navigator1ParamsList, 'screen1'>`, I'd do `type Props = { route: RouteProp<Navigator1ParamsList, 'screen1'> }`

if you're looking for type safety, then the prop for `route` and the hook for `navigation` are the best way.

**Comment by semreg** [comment]
@satya164 got it, thanks. But if we need to reuse that component in both `Navigator1` and `Navigator2`?

**Comment by satya164** [comment]
@semreg I assume the type of `route` would be same in both cases, if not, you can just use a union type for your params/route. this doesn't work for complex type like `navigation`, but for simple object like `route` it should be fine.

**Comment by semreg** [comment]
@satya164 sorry, I didn't really catch that. Do you mean something like this?

```typescript
type Props = {
  route: RouteProp<Nav1ParamsList | Nav2ParamsList, 'Screen1' | 'Screen2'>
}

```

**Comment by satya164** [comment]
@semreg `type Props = { route: RouteProp<...> | RouteProp<...> }` or define a union type for the params in the `ParamList`

**Comment by satya164** [comment]
Don't use `React.FC`. Annotate the props argument directly. `React.FC` doesn't really have any advantages.

**Comment by semreg** [comment]
@satya164 got it. Now I don't get error messages but I still can only access properties that are common to `Nav1ParamsList` and `Nav2ParamsList`. Or that should actually be this way?

**Comment by satya164** [comment]
@semreg i mean the `route` prop. with the hook it has no way of knowing if the type is correct or not.

**Comment by pasquale95** [comment]
Alright, so for the moment the only possible solution is to use union types.
Therefore, taking my example as guideline, the solution to the *lint* error would be declaring `Props` as:

```jsx
// use union types
type Props = StackScreenProps<Navigator1ParamsList, 'screen1'> | StackScreenProps<Navigator2ParamsList, 'screen2'>;
```

**Comment by markoj3s** [comment]
@satya164 

Sorry for "re-opening" that issue. I am facing the same issue and I have went through the conversation and seems like there was a conclusion for the `route` type which was **to use union type** but what would be the conclusion for the `navigation` type?

> this doesn't work for complex type like navigation, but for simple object like route it should be fine.

Based on this, shall I conclude that it is just impossible to handle common screens re-used by multiple different navigators, and if so, it means we should just give up on common screens?

**Comment by rrsalian16** [comment]
I'm also facing same issue, any solution?

**Comment by Alex1899** [comment]
anyone found a working solution for this? Having the same issue

**Comment by tfreitas90** [comment]
@Alex1899 
I still don't know if it works in all cases, even for me, and if this is correct to use, but right now i'm trying something like this. Tell me if you find this incorrect. 

```
export type ReusableScreen1Props = StackScreenProps<FirstStackParamsList, 'reusableScreen1'> &
  StackScreenProps<SecondStackParamsList, 'reusableScreen1'>&
  StackScreenProps<ThirdStackParamsList, 'reusableScreen1'>;

export type ReusableScreenNavigationProp = ReusableScreen1Props['navigation'];

// When in reusable screen 1 context i call:
const {navigate} = useNavigation<ReusableScreenNavigationProp>();
```

**Comment by satya164** [comment]
The `useNavigation` hook with default types works perfectly with components that are in multiple screens. There's no need to manually specify some complex types.

https://reactnavigation.org/docs/typescript#specifying-default-types-for-usenavigation-link-ref-etc

Closing since I already shared my recommendation here: https://github.com/react-navigation/react-navigation/issues/11028#issuecomment-1339909859
