### ISSUE TITLE
Hash/Fragment is stripped away on Web

### ISSUE THREAD

**Issue by nikgraf** [react-navigation/react-navigation#11026]
### Current behavior

When opening the example with the URL `https://react-navigation-example.netlify.app/native-stack/article/gandalf#key=something` the `#key=something` is stripped away.

### Expected behavior

When opening the example with the URL https://react-navigation-example.netlify.app/native-stack/article/gandalf#key=something the URL stays the same.

### Reproduction

https://github.com/react-navigation/react-navigation/tree/main/example

### Platform

- [ ] Android
- [ ] iOS
- [X] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/​bottom-tabs
- [ ] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [ ] @react-navigation/​stack
- [X] @react-navigation/​native-stack

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |   6.0.14

**Comment by Gregoirevda** [comment]
@nikgraf You're reading the url from `getStateFromPath` ?

**Comment by nikgraf** [comment]
Nope, should I used it in this case? Would this prevent the replace and stripping off the hash/fragment part?

**Comment by nikgraf** [comment]
great, will try that today

@satya164 do you have a hint where I would need to look to preserve the hash? I would try to create a PR

**Comment by satya164** [comment]
@nikgraf I think `useLinking.tsx` would be the best place to do it

**Comment by nikgraf** [comment]
was solved with the PR
