### ISSUE TITLE
Software rendering doesn't support drawRenderNode issue

### ISSUE THREAD

**Issue by Bayramito** [react-navigation/react-navigation#11027]
### Current behavior

Seems like React Navigation conflicting with `react-native-blur` library. 

There is a open thread on lib's GitHub 
https://github.com/Kureev/react-native-blur/issues/489#issuecomment-1315631695

But I think the issue is related on react navigation also. As like I mentioned on my comment. 

Because as like I  wrote on my comment there, it is happening when navigation from screen A to B. 

IF A and B are children of different navigators and you want to navigate from A to B like 

`navigation.navigate("SettingsNavigator",{screen:"EditProfile"})` then app throws this error.

But if your current active navigator contains the actual `EditProfile` and you want to navigate in the same navigator, then no problems.

I don't know what causes this issue but seems like it's a nested navigator related thing.

And this is completely a Android issue. Happening only on Android. on IOS everything is fine

### Expected behavior

should navigate as usual from A to B  without requiring A navigator to contain B's specific screen

### Reproduction

none

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/​bottom-tabs
- [ ] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [X] @react-navigation/​stack
- [ ] @react-navigation/​native-stack

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
    "@react-navigation/bottom-tabs": "^6.3.3",
    "@react-navigation/compat": "^5.3.20",
    "@react-navigation/core": "^6.3.0",
    "@react-navigation/drawer": "^6.4.4",
    "@react-navigation/material-bottom-tabs": "^6.2.3",
    "@react-navigation/material-top-tabs": "^6.2.3",
    "@react-navigation/native": "^6.0.12",
    "@react-navigation/native-stack": "^6.8.0",
    "@react-navigation/stack": "^6.2.3",
    "react-native-safe-area-context": "^3.4.1",
    "react-native-screens": "^3.17.0",
    "react-native-gesture-handler": "^2.8.0",
    "react-native-reanimated": "^2.11.0",
    "react-native-tab-view": "^3.1.1",
    "react-native-pager-view": "^5.4.4",
    "react-native": "0.70.5",
| expo                                   | - 
| node                                   | 14.20.0
| npm or yarn                            | 6.14.17

**Comment by Bayramito** [comment]
> The versions mentioned in the issue for the following packages differ from the latest versions on npm:
> 
> * `@react-navigation/bottom-tabs` (found: `6.3.3`, latest: `6.4.1`)
> * `@react-navigation/core` (found: `6.3.0`, latest: `6.4.1`)
> * `@react-navigation/drawer` (found: `6.4.4`, latest: `6.5.1`)
> * `@react-navigation/material-bottom-tabs` (found: `6.2.3`, latest: `6.2.5`)
> * `@react-navigation/material-top-tabs` (found: `6.2.3`, latest: `6.3.1`)
> * `@react-navigation/native` (found: `6.0.12`, latest: `6.0.14`)
> * `@react-navigation/stack` (found: `6.2.3`, latest: `6.3.5`)
> 
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?

yes still existing 

here is how my package looking like for now:

```
 "@react-navigation/bottom-tabs": "^6.4.1",
    "@react-navigation/compat": "^5.3.20",
    "@react-navigation/core": "^6.4.1",
    "@react-navigation/drawer": "^6.5.1",
    "@react-navigation/material-bottom-tabs": "^6.2.5",
    "@react-navigation/material-top-tabs": "^6.3.1",
    "@react-navigation/native": "^6.0.14",
    "@react-navigation/native-stack": "^6.9.2",
    "@react-navigation/stack": "^6.3.5",
    "react-native-safe-area-context": "^4.4.1",
    "react-native-screens": "^3.18.2",
    "react-native-pager-view": "^6.1.1",

```

**Comment by Gregoirevda** [comment]
@Bayramito Can be closed as the issue comes from blurview
