### ISSUE TITLE
Expose header height for default header (please reopen #10097)

### ISSUE THREAD

**Issue by olarcher** [react-navigation/react-navigation#11023]
### Current behavior

It is currently impossible to set header height for the default header, without implementing a custom header component.
This issue was already reported in #10097 but was closed due to missing repro. Please reopen, since [#10113](https://github.com/react-navigation/react-navigation/pull/10113) did not fix the issue and no repro is required (see comments).

### Expected behavior

It should be possible to set header height in screen options.

### Reproduction

No repro required.

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/​bottom-tabs
- [ ] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [ ] @react-navigation/​stack
- [X] @react-navigation/​native-stack

### Environment

    "@react-navigation/bottom-tabs": "^6.4.0",
    "@react-navigation/native": "^6.0.13",
    "@react-navigation/native-stack": "^6.9.1",

**Comment by Gregoirevda** [comment]
What's not working for you [here](https://github.com/react-navigation/react-navigation/pull/10113/files) ?

**Comment by olarcher** [comment]
@Gregoirevda as far as I can tell the fix only addresses the case when a [custom header is supplied](https://github.com/react-navigation/react-navigation/pull/10113/files#diff-430ad7ad5c4108117dc2b61f532413f1f1a8d9766b1f9554d64879a9a3f2610fR178). I would like to avoid re-implementing the entire header logic (back navigation etc.) only to adjust the header height. 
But maybe I'm missing something?

**Comment by satya164** [comment]
As documented in https://reactnavigation.org/docs/native-stack-navigator/, Native Stack exposes the native APIs which have limited customization. The native header only supports background color customization.

**Comment by Gregoirevda** [comment]
@olarcher I misread your issue, I thought you wanted to get and not set the height.

Not sure, but if react-navigation uses UINavigationBar, it seems reasonable not to be able to change height:

https://developer.apple.com/documentation/uikit/uinavigationcontroller/customizing_your_app_s_navigation_bar

> It is permissible to customize the appearance of the navigation bar using the methods and properties of the UINavigationBar class but you must never change its frame, bounds, or alpha values or modify its view hierarchy directly
