### ISSUE TITLE
Typescript: Required to specify initial route when navigating with `strict: "true"`

### ISSUE THREAD

**Issue by jackall3n** [react-navigation/react-navigation#11050]
### Current behavior

`tsconfig.json`

```json
{
  "compilerOptions": {
    "strict": true
  },
  "extends": "expo/tsconfig.base"
}

```

Implementing the example from the docs: https://reactnavigation.org/docs/typescript#organizing-types

```typescript
import type {
  CompositeScreenProps,
  NavigatorScreenParams,
} from "@react-navigation/native";
import type { StackScreenProps } from "@react-navigation/stack";
import type { BottomTabScreenProps } from "@react-navigation/bottom-tabs";

export type RootStackParamList = {
  Home: NavigatorScreenParams<HomeTabParamList>;
  PostDetails: { id: string };
  NotFound: undefined;
};

export type RootStackScreenProps<T extends keyof RootStackParamList> =
  StackScreenProps<RootStackParamList, T>;

export type HomeTabParamList = {
  Popular: undefined;
  Latest: undefined;
};

export type HomeTabScreenProps<T extends keyof HomeTabParamList> =
  CompositeScreenProps<
    BottomTabScreenProps<HomeTabParamList, T>,
    RootStackScreenProps<keyof RootStackParamList>
  >;

declare global {
  namespace ReactNavigation {
    interface RootParamList extends RootStackParamList {}
  }
}


```
Navigating as per the documentation for nested navigators: https://reactnavigation.org/docs/nesting-navigators/#navigating-to-a-screen-in-a-nested-navigator

```typescript
function PopularScreen({ navigation }: HomeTabScreenProps<'Popular'>) {
  navigation.navigate('Home');
  navigation.navigate('Home', { screen: "Popular" });
  navigation.navigate('Home', { screen: "Latest" });
  navigation.navigate('PostDetails', { id: '1234' });
  navigation.navigate('NotFound');
}
```
 
![Screenshot 2022-11-29 at 13 11 49](https://user-images.githubusercontent.com/38332643/204537920-53529fc6-8fa6-4621-b44f-3816a9c8335a.png)

#### Errors: 
`navigation.navigate('Home');`
> TS2345: Argument of type 'string' is not assignable to parameter of type '{ key: string; params?: undefined; merge?: boolean | undefined; } | { name: "Popular"; key?: string | undefined; params: undefined; merge?: boolean | undefined; } | { key: string; params?: undefined; merge?: boolean | undefined; } | ... 6 more ... | { ...; }'.

### Expected behavior

When navigating to a root level page containing a navigator `navigation.navigate('Home')`, no initial screen should be required to be provided.

### Reproduction

https://github.com/jackall3n/react-navigation-v6-navigate-typing

### Platform

- [ ] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/​bottom-tabs
- [ ] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [X] @react-navigation/​stack
- [ ] @react-navigation/​native-stack
- [ ] react-native-tab-view
- [ ] flipper-plugin-react-navigation

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |  ^6.0.16
| @react-navigation/bottom-tabs          | ^6.4.3
| @react-navigation/stack                | ^6.3.7
| node                                   | v16.17.1
|  yarn                            |  1.22.19

**Comment by satya164** [comment]
You have defined the params for `Home` as required, so it requires the param. If it should be optional then define it like `Home: NavigatorScreenParams<HomeTabParamList> | undefined;`

**Comment by satya164** [comment]
It's already documented

> Specifying `undefined` means that the route doesn't have params. A union type with undefined (e.g. `SomeType | undefined`) means that params are optional.

https://reactnavigation.org/docs/typescript/#type-checking-screens
