### ISSUE TITLE
[iOS] NavigationContainer onReady is called on unmount and never called after foregrounding

### ISSUE THREAD

**Issue by AlixH** [react-navigation/react-navigation#11068]
### Current behavior

I have a NavigationContainer wrapping other nested containers.
I am trying to dispatch navigation actions when opening a notification. To be sure that the navigation container is ready, I am dispatching the navigation actions inside the onReady prop callback.
When I put the app to backround, the onReady prop callback is called
Then, I tap a notification, the app is foregrounded, the navigation container is not ready, and the onReady callback never get fired until I put the app to background again

### Expected behavior

I expect the onReady prop callback to be called when the app is in the foreground/being foregrounded.
And even if it is called when backgrounding the app, I expect at least the navigation to be ready when foregrouding the app again

### Reproduction

https://github.com/sap-labs-france/ev-mobile/tree/upgrade_react_native

Root component code:
```tsx
export default class App extends React.Component<Props, State> {
  public state: State;
  public props: Props;
  public centralServerProvider: CentralServerProvider;
  public notificationManager: NotificationManager;
  public deepLinkingManager: DeepLinkingManager;
  private appVersion: CheckVersionResponse;
  private location: LocationManager;
  private themeSubscription: NativeEventSubscription;
  private navigationRef: React.RefObject<NavigationContainerRef<ReactNavigation.RootParamList>>;


  public constructor(props: Props) {
    super(props);
    this.navigationRef = React.createRef();
    this.state = {
      switchTheme: false,
      navigationState: null,
      showAppUpdateDialog: false
    };
  }

  public async componentDidMount() {
    console.log('mount App');
    // Get the central server
    this.centralServerProvider = await ProviderFactory.getProvider();

    // Set up deep linking
    this.deepLinkingManager = DeepLinkingManager.getInstance();
    this.deepLinkingManager?.initialize(this.navigationRef?.current, this.centralServerProvider);
    // Activate Deep links
    this.deepLinkingManager.startListening();

    // Set up notifications
    this.notificationManager = NotificationManager.getInstance();
    this.notificationManager.setCentralServerProvider(this.centralServerProvider);
    this.centralServerProvider.setNotificationManager(this.notificationManager);
    await this.notificationManager?.initialize(this.navigationRef?.current);
    await this.notificationManager.start();
  }

  public componentWillUnmount() {
      console.log('UNMOUNTING ROOT');
    this.deepLinkingManager?.stopListening();
    this.notificationManager?.stop();
  }

  public render() {
    const { switchTheme, showAppUpdateDialog } = this.state;
   <SafeAreaProvider>
        <NavigationContainer
          onReady={() => this.onReady()} // <-- This is called when putting the app to background, and never after foregrouding
          ref={this.navigationRef}
          onStateChange={(newState) => this.setState({navigationState: newState})}
          initialState={this.state.navigationState}
             >
          <rootStack.Navigator initialRouteName="AuthNavigator" screenOptions={{ headerShown: false }}>
            <rootStack.Screen name="AuthNavigator" children={createAuthNavigator} />
            <rootStack.Screen name="AppDrawerNavigator" children={createAppDrawerNavigator} />
          </rootStack.Navigator>
        </NavigationContainer>
      </SafeAreaProvider>
  }

  private onReady(): void {
    void hide({ fade: true });
    this.notificationManager?.performPendingNavigationActions(); // <-- Dispatch pending navigation actions
  }
}
```

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/​bottom-tabs
- [ ] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [ ] @react-navigation/​stack
- [ ] @react-navigation/​native-stack
- [ ] react-native-tab-view
- [ ] flipper-plugin-react-navigation

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |   6.0.14
| @react-navigation/drawer               |  6.5.1
| @react-navigation/material-bottom-tabs | 6.2.5
| @react-navigation/stack                | 6.3.5
| react-native-safe-area-context         | 4.4.1
| react-native-screens                   | 3.18.2
| react-native-gesture-handler           | 2.8.0
| react-native-reanimated                | 2.13.0
| react-native                           | 0.70.6
| node                                   | 16.13.0
| npm or yarn                            | 9.1.2

**Comment by AlixH** [comment]
My issue disappeared when I removed conditional rendering of my root component's content

**Comment by Dimon70007** [comment]
> My issue disappeared when I removed conditional rendering of my root component's content

Thank you. It helps me a lot. I moved SafeAreaProvider inside of NavigationContainer because of SafeAreaProvider has conditional rendering its children depends on insets state
