### ISSUE TITLE
Out of Memory Error in Release scheme when returning from background and swiping

### ISSUE THREAD

**Issue by yawnr** [react-navigation/react-navigation#11079]
### Current behavior

Extremely odd and reproducible bug when attempting to swipe back on a `Stack.Screen` after bringing the app to the foreground. **This only happens in Release mode.**

Steps to reproduce (iOS):
- Navigate to a screen in a Stack navigator
- Put the app into the background and switch to a different app
- Bring the app back into the foreground
- Attempt to swipe back
- App freeze's and eventually must be closed manually

Unclear if this is an issue with `react-native-gesture-handler` itself or the stack navigator's use of it, but it happens every time regardless of `gestureResponseDistance`

FWIW: Switching to `@react-navigation/native-stack` solves the issue, but that isn't an option for us currently

### Expected behavior

Swiping back does not freeze the app, as it correctly does in Debug mode

### Reproduction

cannot-repro-a-release-build.com

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/​bottom-tabs
- [ ] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [X] @react-navigation/​stack
- [ ] @react-navigation/​native-stack
- [ ] react-native-tab-view
- [ ] flipper-plugin-react-navigation

### Environment

- [X] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native                  |     6.0.16
| @react-navigation/stack                   |     6.3.7
| react-native-gesture-handler           |     2.8.0
| react-native-safe-area-context        |     4.4.1

**Comment by KingDoxik** [comment]
Hi, we are facing similar issue. Our app works fine in Expo Go, but when using dev-client build, on some screens when navigating to other screen and going back, the screen becomes frozen. Can't swipe back, even buttons does not work. When inspecting elements, content of the page is not inspectable, only header an be selected. I am not able to reproduce. It happens on some routes, but not others. I wasn't able to find any patter that could be causing it. I just know, that it happens with rect-navigation/stack

**Comment by yawnr** [comment]
@KingDoxik  I *think* I was able to solve this in our case but the cause is completely nebulous and weird.

Anyway, we had a custom `Image` component that had some logic around resolving the source depending on the URI passed because `react-native-web` wouldn't render images from a local source (this appears to no longer be an issue), and it would also fade the image in on load from opacity 0 to 1. 

Eventually I stripped the app down until I was able to have a reproducible instance of this freezing error on swipe when doing Release builds directly from xcode to my iPhone. The feedback loop was super slow since it required native builds to reproduce, but the trigger for this error, which resulted in an OOM error and a completely frozen app as you said, was this custom `<Animated.Image />`. Removing this, or passing in a remote URI instead of a local import or require appears to have fixed whatever is going on under the hood that's causing the error.

I don't really have the time or energy to dig into _why_ this fixed it -- it really was not a special or complicated component, and had actually been working completely fine as is in previous `react-navigation/stack` versions, but there it is. Hope you can find a minimal repro.

**Comment by Lunziyuan** [comment]
I encountered the same issue, and I also used react-native-web. Unfortunately, removing <Animated.Image /> did not solve my problem.
