### ISSUE TITLE
Keyboard is closing in Android 11 and 12 when keyboard comes over tab.

### ISSUE THREAD

**Issue by rifad4u** [react-navigation/react-navigation#11082]
### Current behavior

Keyboard closing automatically when keyboard comes over the tab. this one is working fine in android 10 , but facing this issue android 11 and 12.
please find the below video and u can check the same with the snack code mentioned below.

https://user-images.githubusercontent.com/37132763/206204166-d4007974-af81-4c8a-8f9b-811e92156f6d.mp4

### Expected behavior

Keboard should not close.

### Reproduction

https://snack.expo.dev/eS2H2RJbD

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/​bottom-tabs
- [ ] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [X] @react-navigation/​material-top-tabs
- [ ] @react-navigation/​stack
- [ ] @react-navigation/​native-stack
- [X] react-native-tab-view
- [ ] flipper-plugin-react-navigation

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
|"@react-navigation/native" |"^6.0.14"|
|"@react-navigation/material-top-tabs" | "^6.3.0"|
|"react-native-screens" |"^3.18.2" |
|"react-native-gesture-handler" | "^2.8.0" |
|"react-native-reanimated" | "^2.13.0"|
|"react-native-tab-view" | "^3.3.0"|
|"react-native-pager-view" | "^6.1.0" |
|"react-native" | "0.70.6" |
|node      | v14.21.1 |
|npm  | 6.14.17|

**Comment by okwasniewski** [comment]
Hey, 

Your example looks broken, the one simple thing is to change the top container style to flex instead of explicit height. 

Also **this doesn't work** even with a simple view (because keyboard can't expand over TextInput), you can check it [here](https://snack.expo.dev/@okwasniewski/keyboard-close-issue). TextInput works in tab-view when used properly, therefore Im closing this issue.
