### ISSUE TITLE
Disable pre-rendering the screens

### ISSUE THREAD

**Issue by nightspite** [react-navigation/react-navigation#11084]
### Current behavior

When navigating to a "heavy" screen (that uses a few `useEffects`) it kinda waits for them to be completed and then switch the screen. It happens on a development build done with expo.

### Expected behavior

I handle animations & loading by myself, so I don't need to preload anything there. I believe it was the default behavior based on that issue https://github.com/react-navigation/rfcs/issues/51, so I don't see why would it be removed, but I cannot find how to use it that way.

### Reproduction

-

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/​bottom-tabs
- [ ] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [X] @react-navigation/​stack
- [X] @react-navigation/​native-stack
- [ ] react-native-tab-view
- [ ] flipper-plugin-react-navigation

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | ^6.0.13|
| @react-navigation/native-stack         | ^6.9.0 |
| react-native                           | 0.69.6 |
| expo                                   | ~46.0.17 |
| node                                   | 16.18.1 |
| yarn                            | 3.2.4 |

**Comment by gmerino92** [comment]
Having the same issue here on both dev client and standalone build. When using react-navigation on SDK 45, navigation switches and then code is run. On SDK 47, navigation waits for code on next screen to run before switching to it.

By the way, nothing in our codebase changed and the react navigation package versions being used stayed the same.

**Comment by abumalick** [comment]
I used this dirty fix to launch navigation before rendering:
```
const isFirstRender = React.useRef(true);
  useFocusEffect(
    useCallback(() => {
      isFirstRender.current = false;
      return () => (isFirstRender.current = true);
    }, []),
  );
  if (isFirstRender.current) {
    return <Loading />;
  }
  ```

**Comment by Shariq512000** [comment]
<Tab.Navigator
  screenOptions={{
    lazy: true,  // This will lazy load screens, preventing them from rendering until the user navigates to them
   detachInactiveScreens: true,  // This will unmount inactive screens
  }}
>
  <Tab.Screen name="Home" component={HomeScreen} />
  <Tab.Screen name="Settings" component={SettingsScreen} />
  <Tab.Screen name="Profile" component={ProfileScreen} />
</Tab.Navigator>
