### ISSUE TITLE
Drawer Navigation not compatible with Fabric and Reanimated 3.0

### ISSUE THREAD

**Issue by RyanCommits** [react-navigation/react-navigation#11095]
### Current behavior

<img width="312" alt="Screen Shot 2022-12-12 at 5 07 08 PM" src="https://user-images.githubusercontent.com/30220112/207165488-5e62fb14-3bd9-493e-82b7-b0ab7f77fe9a.png">

Getting ENOENT error:  `node_modules/@react-navigation/drawer/lib/commonjs/views/modern/Drawer.js: /Users/ryanwang/src/testing/RN-new-arch/node_modules/@react-navigation/drawer/lib/commonjs/views/modern/Drawer.js: ENOENT: no such file or directory, open '/drawer/lib/commonjs/views/modern/Drawer.js'` 

when using `const Drawer = createDrawerNavigator()`

### Expected behavior

The JavaScript error shouldn't happen and crash the app.

### Reproduction

https://github.com/RyanCommits/RN-new-arch

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/​bottom-tabs
- [X] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [ ] @react-navigation/​stack
- [ ] @react-navigation/​native-stack
- [ ] react-native-tab-view
- [ ] flipper-plugin-react-navigation

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |6.0.16
| @react-navigation/bottom-tabs          |
| @react-navigation/drawer               |6.5.5
| @react-navigation/material-bottom-tabs |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                |
| @react-navigation/native-stack         |6.9.4
| react-native-safe-area-context         |4.4.1
| react-native-screens                   |3.18.2
| react-native-gesture-handler           |2.8.0
| react-native-reanimated                |3.0.0-rc.4
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           |0.70.6
| expo                                   |
| node                                   |16.17.0
| npm or yarn                            |3.3.0

**Comment by satya164** [comment]
That error message says the folder doesn't exist and comes from metro. You either don't have the folder due to corrupt installation or metro cache is bugged that you need to clear. It's unrelated to Fabric or Reanimated 3.0.
