### ISSUE TITLE
Typescript error when accessing toggleDrawer in the navigation prop 

### ISSUE THREAD

**Issue by wael-fadlallah** [react-navigation/react-navigation#11091]
### Current behavior

I have the Main Screen on which I have created a drawer as the following: 

```javascript
const DrawerComponent = () => {
  const Drawer = createDrawerNavigator();
  return (
    <NavigationContainer independent={true}>
      <Drawer.Navigator screenOptions={{headerShown: false}}>
        <Drawer.Screen name="Home" component={HomeScreen} />
      </Drawer.Navigator>
    </NavigationContainer>
  );
};
```
I have added `headerShown` to false because I want to create a button in each child screen to toggle the drawer, for example, this is my home screen:

```javascript
export default (props: HomeScreenProps) => {
  const {navigation} = props;
  const styles = getStyles(useTheme());
  return (
    <View style={styles.container}>
      <Text>Home</Text>
      <Button mode="contained" onPress={() => navigation.toggleDrawer()}>
        Click
      </Button>
    </View>
  );
};

```

`toggleDrawer` is giving me the following typescript error:
```
Property 'toggleDrawer' does not exist on type 'NativeStackNavigationProp<RootStackParamList, "Home", undefined>'.
```

### Expected behavior

The `toggleDrawer` type (and other drawer functions) should be available in the `navigation` prop 

### Reproduction

https://github.com/wael-fadlallah/Raha

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [X] MacOS

### Packages

- [ ] @react-navigation/​bottom-tabs
- [X] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [ ] @react-navigation/​stack
- [X] @react-navigation/​native-stack
- [ ] react-native-tab-view
- [ ] flipper-plugin-react-navigation

### Environment

- [Y] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native                | 6.0.14
| @react-navigation/drawer               | 6.5.1
| @react-navigation/native-stack      | 6.9.5
| react-native-safe-area-context      | 4.4.1
| react-native-screens                       | 3.18.2
| react-native-gesture-handler           | 2.8.0
| react-native-reanimated                | 2.13.0
| react-native                                    | 0.70.6
| node                                   | 18.3.0
| npm or yarn                            | yarn - 1.22.15

**Comment by satya164** [comment]
You are using native stack's `NativeStackNavigationProp` for a screen from drawer navigator.
