### ISSUE TITLE
Drawer overlay covers all the Screen in React native new Arch (Fabric)

### ISSUE THREAD

**Issue by MikePendo** [react-navigation/react-navigation#11107]
### Current behavior

Drawer overlay covers all the screen with overleay without option for touches to propagate further (When using new arch Fabric). i.e 

### Expected behavior

Drawer overlay is hidden or transparent BUT obviously should not block touches (drwerType permanent works as expected)

### Reproduction

https://github.com/MikePendo/PropertyFinderRN/tree/TurboModules

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/​bottom-tabs
- [X] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [ ] @react-navigation/​stack
- [ ] @react-navigation/​native-stack
- [ ] react-native-tab-view
- [ ] flipper-plugin-react-navigation

### Environment

- [X] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |6.0.6
| @react-navigation/bottom-tabs          |6.0.9
| @react-navigation/drawer               |6.1.8
| @react-navigation/material-bottom-tabs |6.0.0
| @react-navigation/material-top-tabs    |6.0.0
| @react-navigation/stack                |6.0.11
| react-native-safe-area-context         |4.1.2
| react-native-screens                   |2.17.1
| react-native-gesture-handler           |2.0.0
| react-native-reanimated                |1.7.0
| react-native-tab-view                  |3.1.1
| react-native                           |0.70.6
| node                                   |18.10.0
| npm or yarn                            |yarn

**Comment by MikePendo** [comment]
I Have disabled flipper
and have provided reports to reproduce, I can also provide code snippets if need but simply creating a drawer should reproduce the issue

**Comment by MikePendo** [comment]
yes the issue still present can somebody look at it

**Comment by raajnadar** [comment]
@MikePendo please add a working snack repro

**Comment by MikePendo** [comment]
if I use the last version I will see the following issue:
`[Invariant Violation: new NativeEventEmitter() requires a non-null argument]`
Just create a new project and call createDrawerNavigator

**Comment by MikePendo** [comment]
Sorry please wait I need to add dependent libs to the sample  project (maybe that will help)

**Comment by MikePendo** [comment]
My apologises, I cant reproduce the issue any more for the latest RN on my sample project with new arch
