### ISSUE TITLE
Material Top Tabs: Re-Render on every Tab Change

### ISSUE THREAD

**Issue by nikolail45** [react-navigation/react-navigation#11103]
### Current behavior

Everytime I change the Tab by Swiping or Clicking on another one, the whole component inside the tab re-renders (sometimes leading to a short flicker and reloading of images and text, also the position of my scrollview is getting reset). 

### Expected behavior

I want to change between Tabs, without the components constantly re-rendering.

### Reproduction

https://snack.expo.dev/tJHF0isoY

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/​bottom-tabs
- [ ] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [X] @react-navigation/​material-top-tabs
- [ ] @react-navigation/​stack
- [X] @react-navigation/​native-stack
- [X] react-native-tab-view
- [ ] flipper-plugin-react-navigation

### Environment

- [X] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native  | 6.0.14
| @react-navigation/material-top-tabs    | 6.5.1
| @react-navigation/native-stack         | ^6.9.2
| react-native-safe-area-context         | ^3.4.1
| react-native-screens                   | ~3.15.0
| react-native-tab-view                  | ^3.3.4
| react-native-pager-view                | ^5.4.25
| react-native                           | 0.69.4

**Comment by okwasniewski** [comment]
Hello @nikolail45,

I wasn't able to reproduce this issue on the snack you provided. All issues with re-rendering were fixed in recent versions of tab-view. So can you show me your actual code usage / provide valid repro?

**Comment by nikolail45** [comment]
Hello @okwasniewski,

thank you very much for your help! You're right, in the snack I provided the bug did not appear, I'm sorry. I made a new one which replicates my application structure, in the new one you can see the component reloading and flickering 
(I tried it for web and android, both reload, on the snack only the web-version flickers. But on my real devices, the bug appears on android as well as iOS).  

https://snack.expo.dev/1BQvwYlRM

Everytime you switch the tab the useEffect function triggers, leading to a reloading of data, which rerenders the whole component. 

<img width="268" alt="Bildschirm­foto 2022-12-16 um 10 22 19" src="https://user-images.githubusercontent.com/61502597/208066475-f6886c26-82d5-4f42-8b7d-9e86098b0c35.png">

**Comment by nikolail45** [comment]
Sorry, I accidentally closed it. 😆

**Comment by raajnadar** [comment]
If you use Eslint with a newer version it will give you a warning about what is causing the re-renders, check the below example for the fix

You are defining the component inside the body of another function with sees => as a new declaration and causing the render

https://snack.expo.dev/@raajnadar/solve-the-re-render-problem-in-tabs

**Comment by okwasniewski** [comment]
@nikolail45 Fixed your snack, you shouldn't declare components inside another component. Check this out: https://snack.expo.dev/@okwasniewski/material-top-tabs-test

**Comment by nikolail45** [comment]
That was it, thank you guys so much!! @okwasniewski @raajnadar
