### ISSUE TITLE
TypeError: Cannot read property 'props' of undefined

### ISSUE THREAD

**Issue by beqramo** [react-navigation/react-navigation#11113]
### Current behavior

In production from Sentry, I'm receiving error reporting from react-navigation.
According to report, it looks like it is only happening on IOS devices.

here is the most recent stack trace:
```
TypeError: Cannot read property 'props' of undefined
  at <global>(node_modules/@react-navigation/core/src/useDescriptors.tsx:160:26)
  at reduce(native)
  at <global>(node_modules/@react-navigation/core/src/useDescriptors.tsx:141:23)
  at <global>(node_modules/@react-navigation/core/src/useNavigationBuilder.tsx:667:37)
  at <global>(node_modules/@react-navigation/stack/src/navigators/createStackNavigator.tsx:78:25)
  at <global>(node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:3360:22)
  at <global>(node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:7227:34)
  at <global>(node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:6771:25)
  at <global>(node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:6764:54)
  at <global>(node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:6746:19)
  at <global>(node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:6454:34)
  at <global>(node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:2058:31)
  at <global>(node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:7948:58)
  at <global>(node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:1010:30)
```

### Expected behavior

props shouldn't be undefined in react-navigation

### Reproduction

I'm not able to share repo publicly here, sorry

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/​bottom-tabs
- [ ] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [X] @react-navigation/​stack
- [ ] @react-navigation/​native-stack
- [ ] react-native-tab-view
- [ ] flipper-plugin-react-navigation

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |  ~6.0.11
| @react-navigation/bottom-tabs          | ^6.3.2
| @react-navigation/stack                | ~6.2.2
| @react-navigation/native-stack         | ^6.7.0
| react-native-safe-area-context         | 4.3.1
| react-native-screens                   |  3.15.0
| react-native-gesture-handler           | 2.5.0
| react-native-reanimated                | 2.9.1
| react-native                           |  0.68.2
| npm or yarn                            | yarn

**Comment by beqramo** [comment]
I don't think it should be closed:
still receiving events on sentry.
I can event say the line where it is happening. 
<img width="1455" alt="image" src="https://user-images.githubusercontent.com/40486471/229913272-8356cdb6-5ac5-46f4-b699-921e13f211c3.png">

**Comment by rishabhmhjn** [comment]
I am facing a similar issue where we use initialState and then change the available routes underneath due to auth updates.

The routes defined in the initialState didn't exist in the next updated structure and so it throws the error.

**Comment by focux** [comment]
@rishabhmhjn Ya, I think that's what causing the error, did you find any workaround?

**Comment by AlkanV** [comment]
i have the same issue. any solution for it?

**Comment by rishabhmhjn** [comment]
> @rishabhmhjn Ya, I think that's what causing the error, did you find any workaround?

Apologies, I believe we did manage a workaround and released our app, but I cannot recall what we did on top of my mind now. I will update you as soon as I remember something related to it.

**Comment by betocolon23** [comment]
![bug](https://github.com/react-navigation/react-navigation/assets/22110224/ba4cfc0a-f53f-43f9-9ced-f68e41f0df20)


Hi everyone, im having this issue only on ios (expo). If I run the simulator on ios it works but when I read the QR code in expo to test it in my phone it throws the error. Any thoughts? 

My expo SDK version is 49.0.0

**Comment by beqramo** [comment]
Hi, in my case problem was initial navigation state that I was passing during the navigationContainer initialisation.
Have in mind that navigation needs to be ready before do any navigation too. 

Thanks

**Comment by Iuriy-Budnikov** [comment]
I'm getting this error when I open a deep link and app is off
<img width="435" alt="image" src="https://github.com/react-navigation/react-navigation/assets/3968373/cb7b979b-b00a-425c-a65e-17a6fb56c90b">

**Comment by anujkumar09062001** [comment]
Say we've two routes named Login and Welcome make sure the `initialRouteName` prop given to the root navigator  matches names of the screens i.e Login and Welcome

type RouteNames = "Login"|"Welcome"

✅
```
 <Stack.Navigator
        // this should either be Login or Welcome in our case
        initialRouteName={"Login"}
      >
        <Stack.Screen name="Login" component={LoginScreen} />
        <Stack.Screen name="Welcome" component={WelcomeScreen} />
 </Stack.Navigator>
```

Wrong route name was leading to  ❌ the aforementioned errors as there's no screen corresponding to SignUp name
```
<Stack.Navigator
        // SignUp
        initialRouteName={"SignUp"}
      >
        <Stack.Screen name="Login" component={LoginScreen} />
        <Stack.Screen name="Welcome" component={WelcomeScreen} />
 </Stack.Navigator>
```

**Comment by focux** [comment]
Yep, that's was my problem as well, having a wrong route name on initial route name.

**Comment by wiseqingyang** [comment]
In my case, I open my app by deep link like `myappschema://someroute`; 
My routes looks like this 
```JSX
<Stack.Navigator initialRouteName="Home">
    {isLogin ? (
      <>
        <Stack.Screen name="Home" component={Home} />
        {/* some other routes */}
      </>
    ) : (
      <>
        <Stack.Screen name="Login" component={Login} />
        {/* some other routes */}
      </>
    )}
  </Stack.Navigator>
  ```
 Yes, there is something wrong, when the user has login, the initialRouteName `Home` exists, but when the user hasn't login, the initialRouteName `Home` does not  esxits.
 So in my case, user who hasn't login will crash. while other users will not. This happens both on Android and iOS.
 
🚀 **change my code ` initialRouteName={isLogin ? "Home" : "Login"}` fixes my problem.**

If someone wants to reproduce the problem, do the following:
1. set  initailRouteName to some route that not exists.
2. kill the app process.
3. boot the app route by deep link with a route

hope this save someone's time!!
