### ISSUE TITLE
PathConfig TS2344: Type 'T' does not satisfy the constraint '{}'

### ISSUE THREAD

**Issue by anthlasserre** [react-navigation/react-navigation#11125]
### Current behavior

When running TSLint an error occured `yarn tsc`.

```
node_modules/@react-navigation/core/src/types.tsx:717:27 - error TS2344: Type 'T' does not satisfy the constraint '{}'.

717     ? string | PathConfig<T>
                              ~

  node_modules/@react-navigation/core/src/types.tsx:716:41
    716   > extends NavigatorScreenParams<infer T, any>
                                                ~
    This type parameter might need an `extends {}` constraint.


Found 1 error in node_modules/@react-navigation/core/src/types.tsx:717

error Command failed with exit code 2.
```

### Expected behavior

TSLint should succeed.

### Reproduction

Needs to run TSLint to reproduce it

### Platform

- [X] Android
- [X] iOS
- [X] Web
- [X] Windows
- [X] MacOS

### Packages

- [ ] @react-navigation/​bottom-tabs
- [ ] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [ ] @react-navigation/​stack
- [ ] @react-navigation/​native-stack
- [ ] react-native-tab-view
- [ ] flipper-plugin-react-navigation

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/bottom-tabs         | 6.4.0 |
| @react-navigation/drawer         | 6.5.0 |
| @react-navigation/material-top-tabs         | 6.3.0 |
| @react-navigation/native         | 6.0.13 |
| @react-navigation/native-stack         | 6.9.1 |
| react-native-reanimated                | 2.12.0 |
| react-native-tab-view                  | 3.3.0 |
| react-native-pager-view                | 6.0.2 |
| react-native                           | 0.70.5 |
| node                                   | 16.17.1 |
| yarn                            | 1.22.19 |

**Comment by exzos28** [comment]
same

**Comment by anthlasserre** [comment]
Waiting a fix here is a patch-package I made to handle that error.

**patches/@react-navigation+core+6.4.0.patch**

```
diff --git a/node_modules/@react-navigation/core/src/types.tsx b/node_modules/@react-navigation/core/src/types.tsx
index a6b0e61..64dfb79 100644
--- a/node_modules/@react-navigation/core/src/types.tsx
+++ b/node_modules/@react-navigation/core/src/types.tsx
@@ -713,7 +713,7 @@ export type PathConfig<ParamList extends {}> = {
 export type PathConfigMap<ParamList extends {}> = {
   [RouteName in keyof ParamList]?: NonNullable<
     ParamList[RouteName]
-  > extends NavigatorScreenParams<infer T, any>
+  > extends NavigatorScreenParams<infer T extends {}, any>
     ? string | PathConfig<T>
     : string | Omit<PathConfig<{}>, 'screens' | 'initialRouteName'>;
 };
```

**Comment by adamaveray** [comment]
I am still experiencing this error in @react-navigation/core 6.4.8. The patch by @anthlasserre works to get around the issue for now 👍 If PR #11238 can be merged that would resolve the issue without needing to patch the package.

**Comment by Jackman3005** [comment]
It looks like the PR you linked to in your [comment](https://github.com/react-navigation/react-navigation/issues/11125#issuecomment-1465868399) has been open since February and has not yet been merged. Are there any plans to include this any time soon?

Thanks in advance!
