### ISSUE TITLE
DrawerNavigator crashes unless useLegacyImplementation is set to true, with Reanimated 2

### ISSUE THREAD

**Issue by Slapbox** [react-navigation/react-navigation#11120]
### Current behavior

Excluding `useLegacyImplementation` crashes the app instantly for us on Android API level 31, but our `react-native-reanimated` is at `2.12.0`

### Expected behavior

`useLegacyImplementation` can safely be removed because we use Reanimated 2

**NOTE:** I don't think the repro is any good because I can't configure the necessary Babel plugins. I tried [this polyfill workaround](https://forums.expo.dev/t/r-g-reanimatedworkletinit-is-not-a-function-in-expo-snack/65873/6) but no luck.  We do have the Babel plugin configured in our actual project and it crashes just the same.

### Reproduction

https://snack.expo.dev/L6I99Ub49

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/​bottom-tabs
- [X] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [ ] @react-navigation/​stack
- [ ] @react-navigation/​native-stack
- [ ] react-native-tab-view
- [ ] flipper-plugin-react-navigation

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |  6.1.1
| @react-navigation/drawer               |  6.5.6
| @react-navigation/material-top-tabs    |  6.5.1
| @react-navigation/stack                |  6.3.10
| @react-navigation/native-stack         |  6.9.7
| react-native-safe-area-context         |  4.4.1
| react-native-screens                   |  3.18.0
| react-native-gesture-handler           |  2.8.0
| react-native-reanimated                |  2.12.0
| react-native-tab-view                  |  3.1.0
| react-native-pager-view                |  6.0.1
| react-native                           |  0.70.5
| expo                                   |  47.0.9
| node                                   |  16.18.0
| npm or yarn                            |  1.22.19

**Comment by Slapbox** [comment]
`flipper-plugin-react-navigation` is not installed. `react-native-tab-view` is not actually referenced in our project, but upgrading it to `3.3.4` does indeed fix the issue.

**Comment by Slapbox** [comment]
Actually no it didn't fix the issue. I don't know why the app didn't crash when I tested 2 days ago, but indeed it continues to crash without `useLegacyImplementation`.

**Comment by MacKenzieHnC** [comment]
Does [this hsck](https://github.com/MacKenzieHnC/ReactNavigationWindows/commit/46f5811fc965151a8b706dcc2d2f60dd8dbc01f3) solve your issue?

**Comment by Slapbox** [comment]
Still relevant.

**Comment by Slapbox** [comment]
Not stale. There's no easy way to create a repro for this though.

**Comment by pierroo** [comment]
Hi @Slapbox ; I've had to upgrade to reanimated v3 as well, but I was as well using useLegacyImplementation  just like you for drawer navigation.
I'm afraid to push to production without it now; did you happen to find a fix in the past 3 weeks?

**Comment by Slapbox** [comment]
Unfortunately I never found a fix. I hope this doesn't mean we can't upgrade to Reanimated v3, or else what are we supposed to do since no maintainer has taken note of this issue?

**Comment by Slapbox** [comment]
Not stale last I checked.
