### ISSUE TITLE
Custom getPathFromState doesn't run when using useLinkTo

### ISSUE THREAD

**Issue by jparkrr** [react-navigation/react-navigation#11126]
### Current behavior

We have some custom functionality implemented in `NavigationContainer` `linking.getPathFromState` (as [documented](https://reactnavigation.org/docs/navigation-container/#linkinggetpathfromstate)).

Most of the time, this works correctly. However, sometimes when we create a link with `Link` or `useLinkTo()`, this custom function doesn't run.

The issue seems to be in these lines of code in react-navigation, which bypass our custom getPathFromState:

https://github.com/react-navigation/react-navigation/blob/8f8bf02bb77c85cd7a6451533642451954301a94/packages/native/src/useLinking.tsx#L287-L306

An earlier version of it was introduced in this PR: https://github.com/react-navigation/react-navigation/pull/9384

And it was changed more in this commit to fix something with params on web: https://github.com/react-navigation/react-navigation/commit/4468b96db5065be8342483392d939742d21b20bc

It's a bit confusing because the PR claims that it's only associated with deep linking, but route.path seems to be present in more scenarios.

### Expected behavior

I expect a custom `linking.getPathFromState` to run on every navigation.

### Reproduction

https://github.com/jparkrr/react-navigation-bug/tree/main/example#readme
https://github.com/jparkrr/react-navigation-bug

### Platform

- [ ] Android
- [ ] iOS
- [X] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/​bottom-tabs
- [ ] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [ ] @react-navigation/​stack
- [ ] @react-navigation/​native-stack
- [ ] react-native-tab-view
- [ ] flipper-plugin-react-navigation

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.1.1
| @react-navigation/stack                | 6.3.10
| react-native                           | 0.69.5
| react-native-tab-view | 3.3.4
| flipper-plugin-react-navigation | 1.3.20

**Comment by satya164** [comment]
This is expected behavior. When using `useLinkTo`, you specify a path - which we parse to state, not the other way around. Since we're not converting a state to path, there's no reason to call `getPathFromState`. It should only call `getStateFromPath` as we're getting state from provided path.
