### ISSUE TITLE
Presentation: 'transparentModal' breaks SafeAreaView

### ISSUE THREAD

**Issue by MaximZybo** [react-navigation/react-navigation#11132]
### Current behavior

After navigating to modal screen with presentation: 'transparentModal', SafeAreaView does not correctly calculate paddings after screen rotation

### Expected behavior

After navigating to modal screen with presentation: 'transparentModal', SafeAreaView should calculate padding after screen rotation as before navigating to modal, or like navigating to modal with presentation: 'containedTransparentModal'

### Reproduction

https://github.com/MaximZybo/NavigationBug

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/​bottom-tabs
- [ ] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [X] @react-navigation/​stack
- [X] @react-navigation/​native-stack
- [ ] react-native-tab-view
- [ ] flipper-plugin-react-navigation

### Environment

"@react-navigation/native": "^6.1.1",
"@react-navigation/native-stack": "^6.9.7",
"react": "18.1.0",
"react-native": "0.70.6",
"react-native-safe-area-context": "^4.4.1",
"react-native-screens": "^3.18.2"

**Comment by satya164** [comment]
We don't recommend using the `SafeAreaView` component: https://reactnavigation.org/docs/handling-safe-area/

Bugs regarding `SafeAreaView` component should be reported in the `react-native` repo.
