### ISSUE TITLE
react-native-tab-view: undefined is not a function on tab remove

### ISSUE THREAD

**Issue by andrewcharnley** [react-navigation/react-navigation#11135]
### Current behavior

Come back after 6 months and found an error now occurs when TabView is removed from the render. Unfortunately error is a bit cryptic.

Everything renders ok (though it is slow to render the tab bars but that's another issue). It's when the tabview is removed from the render, i.e statusCode becomes !== 200.

{ stateBle.statusCode === 200 && <TabView 
  103         swipeEnabled={false}
+ 104         animationEnabled={false}
  105         navigationState={{ index, routes }}
  106         renderScene={({ route }) => views[route.key] }
  107         onIndexChange={setTabIndexWrapper}
  108         renderTabBar={ (props) => (<TabBar {...props} {...app.theme.data.tab } />) }
~ 109         initialLayout={{ width: layout.width }}
  110       />
  111       }

Error message:

TypeError: undefined is not a function
    in Unknown
    in RCTView (created by View)
    in View (created by SceneView)
    in SceneView (at TabView.tsx:113)
    in RCTView (created by View)
    in View (created by PagerView)
    in RNCViewPager (created by PagerView)
    in PagerView (created by AnimatedComponent)
    in AnimatedComponent
    in AnimatedComponentWrapper (created by PagerViewAdapter)
    in PagerViewAdapter (created by TabView)
    in RCTView (created by View)
    in View (created by TabView)
    in TabView
    in Unknown
    in Unknown
    in RCTView (created by View)
    in View (created by SceneView)
    in SceneView (at TabView.tsx:113)
    in RCTView (created by View)
    in View (created by PagerView)
    in RNCViewPager (created by PagerView)
    in PagerView (created by AnimatedComponent)
    in AnimatedComponent
    in AnimatedComponentWrapper (created by PagerViewAdapter)
    in PagerViewAdapter (created by TabView)
    in RCTView (created by View)
    in View (created by TabView)
    in TabView

### Expected behavior

No error

### Reproduction

yadayada

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/​bottom-tabs
- [ ] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [ ] @react-navigation/​stack
- [ ] @react-navigation/​native-stack
- [X] react-native-tab-view
- [ ] flipper-plugin-react-navigation

### Environment

  "dependencies": {
    "@react-native-picker/picker": "^2.4.8",
    "react": "18.1.0",
    "react-native": "0.70.6",
    "@react-native-async-storage/async-storage": "^1.17.11",
    "react-native-ble-plx": "^2.0.3",
    "react-native-exit-app": "^1.1.0",
    "react-native-fs": "^2.20.0",
    "react-native-gesture-handler": "^2.8.0",
    "react-native-nordic-dfu": "^3.2.1",
    "react-native-pager-view": "^6.1.2",
    "react-native-reanimated": "^2.13.0",
    "react-native-tab-view": "^3.3.4"
  },

**Comment by andrewcharnley** [comment]
Just digging a bit, I reverted to 3.0.1 and the issue continues.

**Comment by okwasniewski** [comment]
Hey @andrewcharnley, please provide an minimal reproduction using https://snack.expo.dev/

Thanks!
