### ISSUE TITLE
navigationBarColor props breaking safeArea / textinput & more

### ISSUE THREAD

**Issue by pierroo** [react-navigation/react-navigation#11139]
### Current behavior

On android, adding navigationBarColor in the screenOptions of a @react-navigation/native-stack will completely mess up the display of the app.
TextInput will no longer be pulled up above the keyboard and the view doesn't adjust naturally
SafeAreaView turns out messed up and needs to be manually added on some screens, while removed on others and it seems random.

### Expected behavior

navigationBarColor should simply allow us to change the navigation bar color without messing everything else.
Or does it add some kind of safeArea and extra changes under the hood?

### Reproduction

basic code is enough

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view
- [ ] flipper-plugin-react-navigation

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | ^6.0.16
| @react-navigation/drawer               | ^6.5.3
| @react-navigation/stack                | ^6.3.7
| @react-navigation/native-stack         | ^6.9.4
| react-native-safe-area-context         | ^3.3.2
| react-native-screens                   | ^3.18.2
| react-native-gesture-handler           | 2.8.0
| react-native-reanimated                | ^2.13.0
| react-native-tab-view                  | ^3.3.2
| react-native-pager-view                | ^5.4.25
| react-native                           | 0.69.7
| node                                   |
| npm or yarn                            |

**Comment by BeeMargarida** [comment]
Hey, I tested this and can't seem to replicate your problem. Can you share code that reproduces the problem?
For example, I used native stack and set the `navigationBarColor` to `#ff0000`. Inside one of the screens I added the code below, it all seems to be working fine when the keyboard opens up.

```
<SafeAreaView style={{ flex: 1 }}>
  <KeyboardAvoidingView style={{ flex: 1 }} behavior={Platform.OS === 'ios' ? 'padding' : 'height'}>
    <TouchableWithoutFeedback onPress={Keyboard.dismiss}>
      <View style={{
        padding: 24,
        flex: 1,
        justifyContent: 'space-around'
      }}>
        <Text style={{
          fontSize: 36,
          marginBottom: 48,
        }}>Header</Text>
        <TextInput placeholder="Username" style={{
          height: 40,
          borderColor: '#000000',
          borderBottomWidth: 1,
          marginBottom: 36,
        }} />
        <View style={{
          backgroundColor: 'white',
          marginTop: 12,
        }}>
          <Button title="Submit" onPress={() => null} />
        </View>
      </View>
    </TouchableWithoutFeedback>
  </KeyboardAvoidingView>
</SafeAreaView>
```

**Comment by crashWunderdog** [comment]
Im facing the same issue with android. Everything works as expected without defining `navigationBarColor`, but as soon as I add it safeArea / textinput avoiding stops working. The project uses RN 0.68.1 and latest versions of react-navigation.

**Comment by pierroo** [comment]
this still is a (big) issue.
Not stale

**Comment by arthur5005** [comment]
Wondering if anyone has a work around or know if this broke in a specific version I can roll back to.

Experiencing exactly this. It's not the end of the world if the app doesn't bleed to the edges with the color I want, but trying to work around this with manual adjustments has a very obvious pitfalls. 

Thanks again for all the hardwork everyone, I get what it takes to maintain a package like this.

**Comment by fabio-alvarenga** [comment]
Can't provide a repro at the moment, but I wanted to chime in and say I'm also experiencing exactly the same issue.

To work around it, I'm using [`expo-navigation-bar`](https://docs.expo.dev/versions/latest/sdk/navigation-bar/) to tweak styles separately from `react-navigation`.

**Comment by salesp07** [comment]
Experiencing the same issue here.... Any fixes yet?

**Comment by High5Apps** [comment]
I was able to find a workaround for this issue by switching from the `SafeAreaView` component to `useSafeAreaInsets` hook as suggested by the React Navigation docs on [Supporting safe areas](https://reactnavigation.org/docs/handling-safe-area). The relevant section is copied below:

> While React Native exports a `SafeAreaView` component, this component only supports iOS 10+ with no support for older iOS versions or Android. In addition, it also has some issues, i.e. if a screen containing safe area is animating, it causes jumpy behavior. So we recommend to use the `useSafeAreaInsets` hook from the [react-native-safe-area-context](https://github.com/th3rdwave/react-native-safe-area-context) library to handle safe areas in a more reliable way.

My change involved going from something like this:
```javascript
export default function ScreenBackground({ children }: PropsWithChildren<{}>) {
  return <SafeAreaView>{children}</SafeAreaView>;
}
```

to something like this:
```javascript
export default function ScreenBackground({ children }: PropsWithChildren<{}>) {
  const insets = useSafeAreaInsets();
  return (
    <View
      style={{
        // Paddings to handle safe area
        paddingTop: insets.top,
        paddingBottom: insets.bottom,
        paddingLeft: insets.left,
        paddingRight: insets.right,
      }}
    >
      {children}
    </View>
  );
}
```

**Comment by wbobeirne** [comment]
Also just wanted to add that I got bit by this from adding `navigationBarColor` to my `Stack.Navigator`. While the safe area fix above seems to work, this is very problematic for screens that aren't safe area-aware at all, as their content appears behind the Android nav bar. This seems to include LogBox.

![CleanShot 2023-11-21 at 18 20 48@2x](https://github.com/react-navigation/react-navigation/assets/649992/3eddb363-ed82-43d5-b737-902f0417719b)

**Comment by wbobeirne** [comment]
Looks like this might be downstream in `react-native-screens`: https://github.com/software-mansion/react-native-screens/issues/1530

**Comment by humaidk2** [comment]
Can confirm this mr fixes this issue,

https://github.com/software-mansion/react-native-screens/pull/1988/files

so should be fixed when it's released to rn screens

**Comment by gokul1630** [comment]
> Can confirm this mr fixes this issue,
> 
> https://github.com/software-mansion/react-native-screens/pull/1988/files
> 
> so should be fixed when it's released to rn screens

this works fine, Thanks!.

**Comment by sarthak-cars24** [comment]
I am facing a similar issue on react-native-screen 4.4.0, and RN 76. Content is going behind navbar intermittently and shifting the screen behind the statusbar. Was their any intermittent fix that I can try?
