### ISSUE TITLE
Ios: navigation.navigate not working 

### ISSUE THREAD

**Issue by naveenprakash74** [react-navigation/react-navigation#11148]
### Check the blow code 
I configure 3 screen in Stack Navigator HomeScreen, SettingScreen, ProfileScreen. I pass  this property (  presentation: 'containedModal', ) in ProfileScreen Options.

I am successfully able to navigate on ProfileScreen from HomeScreen. But not able to navigate on SettingScreen from ProfileScreen on Ios Devices 

it works fine in android device

 

```import * as React from 'react';
import { Text, View, StyleSheet, TouchableOpacity ,SafeAreaView} from 'react-native';
import { createNativeStackNavigator } from '@react-navigation/native-stack';
import { useNavigation,NavigationContainer } from '@react-navigation/native';


const Stack = createNativeStackNavigator();

const HomeScreen = () => {
  const navigation = useNavigation();
  return (
    <View style={{marginTop:50}}>
      <TouchableOpacity
        onPress={() => {
          navigation.navigate('ProfileScreen');
        }}>
        <Text>Navigate to Profile</Text>
      </TouchableOpacity>
    </View>
  );
};

const ProfileScreen = () => {
  const navigation = useNavigation();
  return (
    <View style={{marginTop:50}}>
      <TouchableOpacity
        onPress={() => {
          navigation.navigate('SettingScreen');
        }}>
        <Text>Navigate to ProfileScreen</Text>
      </TouchableOpacity>
    </View>
  );
};

const SettingScreen = () => {
  return (
    <View style={{marginTop:50}}>
      <Text>welcome to the SettingScreen</Text>
    </View>
  );
};

export default function App() {
  return (
    <SafeAreaView style={{flex:1}}>
    <NavigationContainer>
    <Stack.Navigator>
      <Stack.Screen
        name="Home "
        component={HomeScreen}
        options={{
          headerShown: false,
        }}
      />
      <Stack.Screen
        name="SettingScreen"
        component={SettingScreen}
        options={{
          headerShown: false,
        }}
      />
      <Stack.Screen
        name="ProfileScreen"
        component={ProfileScreen}
        options={{
          presentation: 'containedModal',
          headerShown: false,
        }}
      />
    </Stack.Navigator>
    </NavigationContainer></SafeAreaView>
  );
}
```

### Expected behavior

If I want to Navigate to new screen from a Modal Screen I should easily  navigate there

### Reproduction

https://snack.expo.dev/YHezl8VD8

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view
- [ ] flipper-plugin-react-navigation

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |"^6.0.10",
| @react-navigation/native-stack         |"^6.6.2",

**Comment by MacKenzieHnC** [comment]
Instead of using `useNavigation()` in the child screens, add `{navigation}` as a prop to the child screens (e.g. `ProfileScreen = ({navigation}) => ...`

Does this correct the issue? To the best of my knowledge, you don't have to call `useNavigation()` explicitly. It is automatically passed to all child screens.

**Comment by satya164** [comment]
Modal screens are intended to be always on top of other screens so navigating to a regular screen from a modal screen won't work. Alternatively you can close the modal before navigating, or use `navigation.replace` that'll replace the modal with the new screen.
