### ISSUE TITLE
Typescript report 'No overload matches this call.' error when navigating with object (for merge: true)

### ISSUE THREAD

**Issue by soemarko** [react-navigation/react-navigation#11140]
### Current behavior

Red lines underneath the navigation.navigate({});

<img width="802" alt="Screenshot 2023-01-08 at 6 55 49 pm" src="https://user-images.githubusercontent.com/381585/211192325-dbb9a2dd-0c19-4a5a-b62e-2be8aaa6ec11.png">

### Expected behavior

No red lines, like if I added @ts-ignore

<img width="381" alt="Screenshot 2023-01-08 at 6 57 16 pm" src="https://user-images.githubusercontent.com/381585/211192372-14035e85-4d0c-4a7a-b2be-a65d1b1212fd.png">

### Reproduction

can't get basic RN app running on the playground.

### Platform

- [ ] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [X] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view
- [ ] flipper-plugin-react-navigation

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | ^6.0.16
| @react-navigation/bottom-tabs          | ^6.5.2
| @react-navigation/native-stack         | ^6.9.7
| react-native-safe-area-context         | ^4.4.1
| react-native-screens                   | ^3.18.2
| react-native-gesture-handler           | ^2.8.0
| react-native                           | 0.70.6
| node                                   | 16.16.0
| yarn                            | 1.22.19

**Comment by soemarko** [comment]
> The versions mentioned in the issue for the following packages differ from the latest versions on npm:
> 
>     * `@react-navigation/native` (found: `6.0.16`, latest: `6.1.1`)
> 
> 
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?

still happens on 6.1.1

**Comment by soemarko** [comment]
Doesn't need repro, just typescript definition issue. I'll no longer comment to this, it seems like it's going to be abandoned anyway...

**Comment by ikapo** [comment]
This is happening to me as well

**Comment by soemarko** [comment]
Turns out it's my issue, I have another non-optional parameter to the previous screen.

`Checkout: {item: StartCheckoutResult, selectedAdress?: CustomerAddressResult};`

In my case on top, the params I've set just selectedAddress. Set `item: StartCheckoutResult` to `item?: StartCheckoutResult` fixes this.
