### ISSUE TITLE
Flickering when navigating from one screen to another

### ISSUE THREAD

**Issue by amalmohann-dgnl** [react-navigation/react-navigation#11154]
### Current behavior

**When navigating in IOS**
smooth animation of navigation and moves to the new screen.

**When navigating in ANDROID**
stutter is there before navigating to the new screen.

### Expected behavior

**When navigating in IOS**
smooth animation of navigation and moves to the new screen.

**When navigating in ANDROID**
smooth animation of navigation and moves to the new screen.

### Reproduction

no link

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view
- [ ] flipper-plugin-react-navigation

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
|@react-navigation/bottom-tabs | ^6.4.1
| @react-navigation/devtools | ^6.0.11
|@react-navigation/native | ^6.0.14
|@react-navigation/native-stack | ^6.9.2
| react-native-safe-area-context         |  ^4.4.1
| react-native-screens                   | ^3.18.2
| react-native-gesture-handler           | ^2.8.0
| react-native-reanimated                | ^2.12.0
| react-native                           | 0.70.5
| node                                   | v16.16.0
| npm | 8.11.0
|yarn                            | 1.22.19

smiliar open ticket : https://github.com/react-navigation/react-navigation/issues/10951

**Comment by amalmohann-dgnl** [comment]
Issue is reproducable

**Comment by raajnadar** [comment]
You need to send a runnable example on snack so that we can check what is going wrong, also try with the latest version

**Comment by jordiepasman** [comment]
If you search for a runnable example it is in this issue also: https://github.com/react-navigation/react-navigation/issues/10951

**Comment by cbjs** [comment]
still there
