### ISSUE TITLE
Using navigationRef.navigate messes up nested Stack Navigator

### ISSUE THREAD

**Issue by Rc85** [react-navigation/react-navigation#11151]
### Current behavior

I created a ref for my `NavigationContainer` using `createNavigationContainerRef`. When I navigate to a nested Stack Navigator (not the initialRouteName), go back to root, and then going to the screen with the Stack Navigator, it doesn't render the initialRouteName component. It renders the one that was navigated to using the ref.

In the reproduction snack, to reproduce the issue, follow these steps
1. Press `MENU` and press `MESSAGES`
2. You will see a button with `CHAT 1`
3. Press on `CHAT 1` and you will be on a screen with the `chat-1` displayed
4. Now go back to `MAIN` and press the `GO TO CHAT` button at the top
5. You will be on the screen with `chat-2` displayed
6. Press `GO BACK` and open `MENU` and go to `MESSAGES` and you will be on the screen with `chat-2` displayed

`MESSAGES` is suppose to take you to the `Chat rooms` screen, but after using `navigationRef.navigate` to a nested navigator's screen, you can no longer go to that screen anymore.

### Expected behavior

When navigating to a drawer's screen after using `navigationRef.navigate`, the navigator nested in that screen should render the component specified in the `initialRouteName`.

### Reproduction

https://snack.expo.dev/G-5c0GW3E

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view
- [ ] flipper-plugin-react-navigation

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |  ^6.1.0
| @react-navigation/drawer               | ^6.5.4
| @react-navigation/stack                | ^6.3.8
| react-native-safe-area-context         | ^4.4.1
| react-native-screens                   | ^3.18.2
| react-native-gesture-handler           | ^2.8.0
| react-native-reanimated                | ^2.13.0
| react-native                           | 0.70.6
| node                                   | 16.15.0
| npm                            | 8.5.5

**Comment by satya164** [comment]
https://reactnavigation.org/docs/nesting-navigators/#rendering-initial-route-defined-in-the-navigator

**Comment by Rc85** [comment]
> https://reactnavigation.org/docs/nesting-navigators/#rendering-initial-route-defined-in-the-navigator

Doesn't work. Try it.

1. Press `GO TO CHAT`
2. Pressing back goes to `Chat rooms` screen
3. Pressing back again goes to `MAIN`
4. Now open `MENU` and go to `MESSAGES` and you're at the screen with `chat-2`, not `Chat rooms`

**Comment by satya164** [comment]
If you want the screen to be reset then you can reset the params on blur: https://github.com/react-navigation/react-navigation/issues/6915

**Comment by Rc85** [comment]
> If you want the screen to be reset then you can reset the params on blur: [#6915 (comment)](https://github.com/react-navigation/react-navigation/issues/6915#issuecomment-591533068)

This definitely needs to be documented. New users aren't gonna expect params to be kept on blur, it just doesn't make sense.

**Comment by satya164** [comment]
> New users aren't gonna expect params to be kept on blur

That's why there's an open issue
