### ISSUE TITLE
react navigation very slow for react-native 0.71.0

### ISSUE THREAD

**Issue by ko-devHong** [react-navigation/react-navigation#11167]
### Current behavior

If you proceed with login and press the button, it is too slow than the previous version of RN 0.71.0.

### Expected behavior

proceed very fast 

### Reproduction

not repo

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [X] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view
- [ ] flipper-plugin-react-navigation

### Environment

{
    "name": "app",
    "version": "0.0.1",
    "private": true,
    "scripts": {
        "android:dev": "yarn set-env:dev &&  react-native run-android --variant=developmentDebug",
        "ios:dev": "yarn set-env:dev && ENVFILE=.env.development react-native run-ios --scheme \"app-dev\" -
        "start": "react-native start",
    },
    "dependencies": {
        "@amplitude/react-native": "^2.11.0",
        "@native-html/iframe-plugin": "^2.6.1",
        "@notifee/react-native": "^5.5.0",
        "@ptomasroos/react-native-multi-slider": "^2.2.2",
        "@react-native-async-storage/async-storage": "^1.17.3",
        "@react-native-clipboard/clipboard": "^1.10.0",
        "@react-native-community/netinfo": "^9.3.0",
        "@react-native-community/push-notification-ios": "^1.10.1",
        "@react-native-firebase/analytics": "^16.5.0",
        "@react-native-firebase/app": "^16.5.0",
        "@react-native-firebase/messaging": "^16.5.0",
        "@react-native-firebase/remote-config": "^16.5.0",
        "@react-navigation/bottom-tabs": "^6.3.1",
        "@react-navigation/elements": "^1.3.3",
        "@react-navigation/material-top-tabs": "^6.2.2",
        "@react-navigation/native": "^6.0.10",
        "@react-navigation/native-stack": "^6.6.2",
        "@sentry/react-native": "^4.1.0",
        "@types/react-native-version-check": "^3.4.4",
        "appcenter": "4.4.5",
        "appcenter-analytics": "4.4.5",
        "appcenter-crashes": "4.4.5",
        "axios": "^0.27.2",
        "dayjs": "^1.11.2",
        "deprecated-react-native-prop-types": "^2.3.0",
        "graphql": "^16.5.0",
        "hangul-js": "^0.2.6",
        "immer": "^9.0.15",
        "jotai": "^1.7.6",
        "lodash": "^4.17.21",
        "patch-package": "^6.4.7",
        "postinstall-postinstall": "^2.1.0",
        "react": "18.2.0",
        "react-native": "0.71.0",
        "react-native-appboy-sdk": "^1.41.0",
        "react-native-appsflyer": "^6.5.21",
        "react-native-bootsplash": "^4.4.1",
        "react-native-channel-plugin": "^0.7.4",
        "react-native-code-push": "^7.0.5",
        "react-native-config": "^1.4.12",
        "react-native-date-picker": "^4.2.1",
        "react-native-device-info": "^9.0.2",
        "react-native-exit-app": "^1.1.0",
        "react-native-fast-image": "^8.5.11",
        "react-native-haptic-feedback": "^1.14.0",
        "react-native-heic-converter": "^1.3.0",
        "react-native-image-pan-zoom": "^2.1.12",
        "react-native-keyboard-aware-scroll-view": "^0.9.5",
        "react-native-linear-gradient": "^2.6.2",
        "react-native-masked-text": "^1.13.0",
        "react-native-orientation-locker": "^1.5.0",
        "react-native-pager-view": "^5.4.25",
        "react-native-parsed-text": "^0.0.22",
        "react-native-permissions": "^3.6.1",
        "react-native-render-html": "^6.3.4",
        "react-native-safe-area-context": "^4.5.0",
        "react-native-screens": "^3.19.0",
        "react-native-snap-carousel": "^3.9.1",
        "react-native-tab-view": "^3.1.1",
        "react-native-version-check": "^3.4.3",
        "react-native-webview": "^11.26.0",
        "react-native-wrapped-text": "^1.2.2",
        "react-query": "^3.39.1",
        "sendbird": "^3.1.14"
    },
    "devDependencies": {
        "@babel/core": "^7.12.9",
        "@babel/preset-env": "^7.14.0",
        "@babel/runtime": "^7.12.5",
        "@react-native-community/eslint-config": "^3.0.0",
        "@trivago/prettier-plugin-sort-imports": "^3.2.0",
        "@tsconfig/react-native": "^2.0.2",
        "@types/jest": "^29.2.1",
        "@types/lodash": "^4.14.182",
        "@types/react": "^18.0.24",
        "@types/react-native": "^0.71.0",
        "@types/react-native-snap-carousel": "^3.8.5",
        "@types/react-test-renderer": "^18.0.0",
        "@typescript-eslint/eslint-plugin": "^5.17.0",
        "@typescript-eslint/parser": "^5.17.0",
        "appcenter-cli": "^2.10.10",
        "babel-jest": "^29.2.1",
        "babel-plugin-module-resolver": "^4.1.0",
        "eslint": "^8.19.0",
        "eslint-config-prettier": "^8.5.0",
        "eslint-config-standard-with-typescript": "^21.0.1",
        "eslint-plugin-import": "^2.26.0",
        "eslint-plugin-jest": "^27.2.1",
        "eslint-plugin-node": "^11.1.0",
        "eslint-plugin-prettier": "^4.2.1",
        "eslint-plugin-promise": "^6.0.0",
        "eslint-plugin-react": "^7.29.4",
        "eslint-plugin-react-hooks": "^4.5.0",
        "eslint-plugin-react-native": "^4.0.0",
        "husky": "^8.0.0",
        "jest": "^26.6.3",
        "lint-staged": "^12.4.1",
        "metro-react-native-babel-preset": "^0.73.5",
        "prettier": "^2.8.2",
        "react-native-flipper": "^0.144.0",
        "react-query-native-devtools": "^4.0.0",
        "react-test-renderer": "18.2.0",
        "rn-flipper-async-storage-advanced": "^1.0.4",
        "typescript": "^4.8.4"
    },
    "resolutions": {
        "@types/react": "^17"
    },
    "jest": {
        "preset": "react-native",
        "moduleFileExtensions": [
            "ts",
            "tsx",
            "js",
            "jsx",
            "json",
            "node"
        ]
    }
}

**Comment by devoren** [comment]
I had the same problem and it got much faster after v0.71.1. Please upgrade RN to 0.71.1 [(#35828)](https://github.com/facebook/react-native/issues/35828)

**Comment by ralppppy** [comment]
It's still slow when using nested navigation, I'm using stack together with  tab navigation.

**Comment by devoren** [comment]
@ralppppy Can you share the code how you use stack with tab navigation? In DEV mode on Android, when switching tabs, fps drops to about 50-55 fps in my project

**Comment by ralppppy** [comment]
@devoren  I've tried the example code in the documentation

`import AccountScreen from './AccountScreen';
import FeedScreen from './FeedScreen';
import ProfileScreen from './ProfileScreen';
import SettingsScreen from './SettingsScreen';
import {NavigationContainer} from '@react-navigation/native';

import {createBottomTabNavigator} from '@react-navigation/bottom-tabs';
import {createNativeStackNavigator} from '@react-navigation/native-stack';

const Tab = createBottomTabNavigator();

function HomeTabs() {
  return (
    <Tab.Navigator>
      <Tab.Screen name="Feed" component={FeedScreen} />
      <Tab.Screen name="Profile" component={ProfileScreen} />
      <Tab.Screen name="Account" component={AccountScreen} />
    </Tab.Navigator>
  );
}

const Stack = createNativeStackNavigator();

export default function App() {
  return (
    <NavigationContainer>
      <Stack.Navigator>
        <Stack.Screen name="Settings" component={SettingsScreen} />

        <Stack.Screen name="Home" component={HomeTabs} />
      </Stack.Navigator>
    </NavigationContainer>
  );
}
`

The SettingsScreen has a Button that navigates to "Home". The transition itself is not slow, it's just you need to press the button at least twice to navigate.

**Comment by devoren** [comment]
@ralppppy With newArch enabled I also have issues, maybe we need to wait for updates from react navigation.

**Comment by shemseddine** [comment]
> I had the same problem and it got much faster after v0.71.1. Please upgrade RN to 0.71.1 [(#35828)](https://github.com/facebook/react-native/issues/35828)

I can confirm that upgrading from 0.71.0 to 0.71.1 has solved the issue.

**Comment by Yassine-Chraa** [comment]
> I had the same problem and it got much faster after v0.71.1. Please upgrade RN to 0.71.1 [(#35828)](https://github.com/facebook/react-native/issues/35828)

upgrading to version 0.71.1 solve the issue

**Comment by jqn** [comment]
Upgrading to RN version 0.71.1 didn't work for me, but I figured out two solutions that did:

You can disable hermes in your gradle.properties file

```
# Use this property to enable or disable the Hermes JS engine.
# If set to false, you will be using JSC instead.
hermesEnabled=false
```

or you can use the following prop if you are using @react-navigation/drawer

```
useLegacyImplementation={true}
```

**Comment by conoremclaughlin** [comment]
Noting that rendering performance seems to have dropped for all react native versions above ^0.7 - with hermes having the worst performance. See the following issues:

https://github.com/facebook/react-native/issues/36123 
https://github.com/facebook/react-native/issues/35778
https://github.com/wix/react-native-calendars/issues/2138

In our case, whether due to the combination of synchronous effect flushing, or slower rendering performance on both jsc and hermes, we need to move away from useFocusEffect for any data fetching due to its halting of the UI on transition. This was not an issue in RN ^0.68.

**Comment by hasanaktas** [comment]
is there any progress on this? I am currently waiting for 1 or 2 seconds on page transitions in android.

**Comment by rodrigolourenco** [comment]
> is there any progress on this? I am currently waiting for 1 or 2 seconds on page transitions in android.

Same here, is there any workaround?

**Comment by ThePlatinum** [comment]
The issues still persist, even v0.71.0.

**Comment by DavideSegullo** [comment]
I also experience the same problem, I have tried debugging but to no avail, has anyone been able to solve it?

**Comment by jotilohana** [comment]
facing same issue? any solution?

**Comment by arasrezaei** [comment]
there is a noticable lag/delay while navigating ...

**Comment by DavideSegullo** [comment]
Does anyone have a mre repo? So we can start working on that?

**Comment by hasanaktas** [comment]
Why is there no improvement when there is such an obvious performance problem in the current React version?

Especially on Android, page transitions are so slow. If the page is already full (for example if I have 2 horizontal flatlists with 20 products).

If the page data is blank, the page loads a bit faster. But if I'm fetching from cache like react query or redux, I wait for at least 2 3 seconds for the page to be drawn.

There is no solution I haven't tried. Converting the flatlist to flashlist didn't help. I'm sure there are places in the React navigation library that need to be resolved.

**Comment by danbim** [comment]
@hasanaktas / @arasrezaei / @DavideSegullo and anyone facing the same issue here: have you tried profiling your application as e.g. described in https://www.youtube.com/watch?v=5Q3VCgKV0GE ?

We faced the same issues and had the hypothesis that this was caused by react-navigation. After profiling however, we learned that on every route change (aka navigation state change), a context changed, which triggered a re-rendering all of our screens that were previously visited *before* screen transition. On a 5 year old Android phone this resulted in 2-3 seconds delay.

The root cause in our case, was a custom hook introducing the context that changed on every route change. The context contained the current route which obviously always changes. Every screen used that hook so it was re-rendered on route change. The fix was to make the hook more granular so that only components actually reacting to route changes would re-render.

**Comment by wolfcarves** [comment]
isn't due to flatlist/virtualist?

**Comment by dbankier** [comment]
I am also trying to debug the hit on performance since moving to anything after 0.71. 
I am finding that running setOptions (in useLayoutEffect/useEffect) is one significant performance hit.
Not sure if that helps narrow down the issue.

**Comment by pandora-bdo** [comment]
I'm facing the same issue!
I've just upgraded to RN 0.71.3 / SDK 48, and now navigation seems pretty slow, especially when navigating from nested navigators(2 seconds delay after closing the drawer menu on Android).

After reading the replies, it looks like the topic is abandoned... so.... is there a temporary solution? 
For now I'll keep my current project on SDK 45 & RN 0.68.

**Comment by CaarLo1337** [comment]
@pandora-bdo,

@danbim already gave the perfect answer for this issue.. i had the same 2 days ago with 3sec delay when navigating in a custom navigation. i used flipper to see wich components take to much time to render and i fixed them. now i navigate with 300ms to a huge contentpage.
try using more useCallbacks and memo on the right components.

my issue was that i used 5 horizontal scrollview to list components. i replaced all with a flatlist and used initialNumToRender and  maxToRenderPerBatch

**Comment by yunushuyut** [comment]
> @pandora-bdo,
> 
> @danbim already gave the perfect answer for this issue.. i had the same 2 days ago with 3sec delay when navigating in a custom navigation. i used flipper to see wich components take to much time to render and i fixed them. now i navigate with 300ms to a huge contentpage. try using more useCallbacks and memo on the right components.
> 
> my issue was that i used 5 horizontal scrollview to list components. i replaced all with a flatlist and used initialNumToRender and maxToRenderPerBatch

Did you do that by using Profiling?

**Comment by CaarLo1337** [comment]
Yes with Profiling. And you should check out the Video that was posted in this Issue. 
https://www.youtube.com/watch?v=5Q3VCgKV0GE

Or read this https://reactnative.dev/docs/performance
And try disabling DevMode in the app.

> JavaScript thread performance suffers greatly when running in dev mode. This is unavoidable: a lot more work needs to be done at runtime to provide you with good warnings and error messages, such as validating propTypes and various other assertions. Always make sure to test performance in [release builds](https://reactnative.dev/docs/running-on-device#building-your-app-for-production).

**Comment by yunushuyut** [comment]
> Yes with Profiling. And you should check out the Video that was posted in this Issue. https://www.youtube.com/watch?v=5Q3VCgKV0GE

Thank you for your response. I checked the video too and profiled my app, but I couldn't solve my problem. I m using nested navigation with empty screens, for testing. Unfortunately, render threads are being completed step by step without a problem or looping through the misroutes, then it takes 3 seconds almost. I attached the Profiling record. If you have time and decide to allocate for me, I'll be appreciated for this. 

[ezyzip.zip](https://github.com/react-navigation/react-navigation/files/11986736/ezyzip.zip)

**Comment by CaarLo1337** [comment]
wow how deep is this nested?

> > Yes with Profiling. And you should check out the Video that was posted in this Issue. https://www.youtube.com/watch?v=5Q3VCgKV0GE
> 
> Thank you for your response. I checked the video too and profiled my app, but I couldn't solve my problem. I m using nested navigation with empty screens, for testing. Unfortunately, render threads are being completed step by step without a problem or looping through the misroutes, then it takes 3 seconds almost. I attached the Profiling record. If you have time and decide to allocate for me, I'll be appreciated for this.
> 
> [ezyzip.zip](https://github.com/react-navigation/react-navigation/files/11986736/ezyzip.zip)

wow how deep is this nested? Profiling looks fine for me.

**Comment by eikhunter** [comment]
Also experienced a huge drop in performance across all navigating screens, not just android, but iOS too

```
"@react-navigation/bottom-tabs": "^6.5.8",
"@react-navigation/devtools": "^6.0.19",
"@react-navigation/drawer": "^6.5.4",
"@react-navigation/native": "^6.1.7",
"@react-navigation/native-stack": "^6.9.13",
```
`react-native: 0.71.10`

**Comment by quyentho** [comment]
I experienced this issue. I have 1 Stack navigation at the root -> bottom tab -> another bottom tab nested. Navigating from the deepest bottom tab screens to the parent Stack screens is very slow (about 10s). The `navigation.goBack()` is slow too even when navigating in the same level (about 10s).  Use `native-stack` improved a lot for the `goBack` but still slow when navigating from nested screen.
```
    "@react-navigation/bottom-tabs": "^6.5.7",
    "@react-navigation/material-bottom-tabs": "^6.2.16",
    "@react-navigation/native": "^6.0.8",
    "@react-navigation/native-stack": "^6.9.13",
    "@react-navigation/stack": "^6.2.0",
    "react-native": "0.71.8",
    "react-navigation": "^4.4.4",
    "expo": "^48.0.0",
```

**Comment by devoren** [comment]
@quyentho i have the same problem using expo router with native stack

**Comment by AdarshJais** [comment]
Can we reopen this issue, of Is there any other thread open for this?

**Comment by dbankier** [comment]
Follow this issue: https://github.com/facebook/react-native/issues/36296
It seems like it is a broader RN issue.

**Comment by devoren** [comment]
@dbankier you are right, hope this gets resolved soon 🥺

**Comment by devoren** [comment]
@quyentho same issue when i use expo-router and expo 49 goback REALLY SLOW 😢

**Comment by quyentho** [comment]
Ok, guys, I have to apologize. The `goBack` is the real issue, but for nested navigation, it seems like my app's performance problem since when running in `no-dev` mode, the navigation is still fast (about 1-2sec)

**Comment by imransilvake** [comment]
looks like on 0.73.0, navigation.setOptions loads pretty late. It was working fine on 0.70.0.

```
	useEffect(() => {
	       navigation.setOptions({ header: () => <ContentHeader /> });
	}, [])
```

**Comment by CloudGTMain** [comment]
Does someone have a solution for this?  tried all without success

**Comment by devoren** [comment]
@CloudGTMain https://github.com/facebook/react-native/issues/36296

**Comment by emzet93** [comment]
I also feel that screen transitions are more laggy/expensive after upgrading to 72 from 67. It might be due to the issues with [react native itself](https://github.com/facebook/react-native/issues/36296), but maybe there were some changes included in react-navigation or react-native-screens which are causing issues too?

As the example, I have a screen placed in native stack navigator and presented modally. I see a delay between pressing button opening it and transition start and js FPS drops to ~45 sometimes. But on the other hand, if I open exactly the same screen inside react native Modal component, it reacts much faster and FPS is dropping to ~56/58.

**Comment by devoren** [comment]
@emzet93 yeah you are right very slow. in my case around 10fps

**Comment by chyde** [comment]
> Upgrading to RN version 0.71.1 didn't work for me, but I figured out two solutions that did:
> 
> You can disable hermes in your gradle.properties file
> 
> ```
> # Use this property to enable or disable the Hermes JS engine.
> # If set to false, you will be using JSC instead.
> hermesEnabled=false
> ```
> 
> or you can use the following prop if you are using @react-navigation/drawer
> 
> ```
> useLegacyImplementation={true}
> ```

This seemed to fix my issue.

for reference, I have StackNavigator with nested BottomTab's.  Previously the bottom-tab transitions were slowwww

**Comment by thang997** [comment]
any solution for navigation when newArchEnabled=true guys

**Comment by jordann93** [comment]
Hello,
Do we have news about this problem ? Same problem as everyone....

**Comment by Georg7** [comment]
Same issue here. On Android transitions take 2-4 seconds! On iOS it works at an acceptable speed (~500ms). 

I've noticed that if I don't include a component in the ```headerTitle``` the performance increases slightly but is still unacceptable from a UX perspective. 

```
<Stack
					screenOptions={(route) => ({
						headerShown: true,
						animationEnabled: true,
						animation: Platform?.OS === "ios" ? "simple_push" : "slide_from_right",


						headerStyle: {
							backgroundColor: "transparent",
						},

						headerShadowVisible: false,
						headerTitle: () => <CommonHeader showHeader={showHeader} numSteps={numSteps} stepNum={stepNum} />,
						headerLeft: () => <HeaderBackButton />,
						headerBackVisible: false,
					})}
				/>
```

Has anyone been able to find a workaround or a root-cause of this and how to fix it?

**Comment by HieronymusLex** [comment]
@Georg7  FWIW I experienced this issue and it was particularly noticeable on an old Android device when I was rendering complex components (SVGs), storing state in screen components/context and doing data fetching in screen component useEffects. Per [this comment](https://github.com/react-navigation/react-navigation/issues/11167#issuecomment-1625737911) I optimised my components by breaking the screen up into smaller components, used useCallback, useMemo, and memoised my components which improved things. Probably the biggest improvement came from introducing zustand and connecting the child components to the relevant part of store, rather than storing my state using useState on the screens which was a causing rerenders of the entire screen

**Comment by ewein** [comment]
I'm also having this issue on Android only with Expo SDK 49. I'm using a Drawer Navigator and once the Drawer opens which is very laggy it cannot be closed again.

**Comment by asgarovf** [comment]
Having the same issue both on Android and IOS on native stack navigation at `"@react-navigation/native-stack": "6.9.17"`, and `"react-native": "0.71.8"`. The animation is a bit slow but affects end users.

**Comment by ko-devHong** [comment]
@satya164  This is not solved issue, Please reopen

**Comment by mmahdibyt** [comment]
dont worry in production there is not speed problem all be fast :)

**Comment by daywong1119** [comment]
Expo 49 and RN 0.72, I have slow issue on production build, no issue on dev mode, after the drawer is opened, it cant be close. 

```
    "@react-navigation/drawer": "6.6.6",
    "react-native": "0.72.6",
```

**Comment by mollyOver** [comment]
Just upgraded RN to 0.73.3. Tab-Navigator is noticeably lagging in release build. There is no log when I am debugging on the same android phone. All the react-navigation packages are up-to date.
The older RN 0.64.4 release build is working well.

**Comment by ipoogleduck** [comment]
I am experiencing lots of issues with slow navigation on React Native v0.72.5 for Android devices. The navigation is slow in release mode for some devices and very slow in debug mode for all devices. Mainly just hangs up for up to a minute when trying to tap the back button or tap on a tab.

**Comment by rogerkerse** [comment]
For us with Fabric turned on, navigation is slow, without it everything is fine. We have nested tab and stack navigators. Would like to get solution for fabric variant 😕

**Comment by vijaychouhan-rails** [comment]
I found that this is happening because of mounting the component on the page so I added a hack to solve the issue

Step 1) Create a customer hook

// It will run when component is mounted, return status of mounting
```
export function useOnMounted() {
  const onMounted = useRef(false);
  const [isLoading, setLoading] = useState(true);

  useEffect(() => {
    onMounted.current = true;
    setTimeout(() => {
      setLoading(false);
    });

    return () => {
      onMounted.current = false;
    };
  }, []);

  return {onMounted: useCallback(() => onMounted.current, []), isLoading};
}

In component users.js

const Users = ({navigation}) => {
  const {onMounted} = useOnMounted();
  
  if (!onMounted()) {
    return null //OR <LoaderComponent />;
  }
  
  // Else return original component
  
  return (
    <Text>This is the main component</Text>
  )
  
}

```

**Comment by forever-sumit** [comment]
Its working with RN 0.73.4. Thanks @vijaychouhan-rails 

I know its hack but make my navigation page transition from 3 second to milisecond, navigation working like native navigation.

I am really happy with that solution. Thanks again

**Comment by anhnguyen123** [comment]
still error 0.71.3

**Comment by ko-devHong** [comment]
> still error 0.71.3

you can update 0.73.x

**Comment by anhnguyen123** [comment]
Is it really effective? My project is really running.

Vào Th 3, 26 thg 3, 2024 vào lúc 09:33 TAE HONG LEE <
***@***.***> đã viết:

**Comment by priedejm** [comment]
Same exact issue^. react-native 0.74.1 SDK 51 and bottom tabs are especially slow. Often delayed.

**Comment by raajnadar** [comment]
Reproduce the issue on [snack](https://snack.expo.dev/) also add the device details that you are using to test

**Comment by doublelam** [comment]
Hi anything new here, My app becomes slow everywhere after upgrading react-native to 0.74.2 and enabling new arc

**Comment by anhnguyen123** [comment]
My project has been uploaded to the store but it's still slow on Android. iOS is very fast.

**Comment by Mikail-snipez13** [comment]
Same issue in my project. Slow on Android but fast on iOS.

**Comment by GeekJC** [comment]
+1 on react-native 0.74.3 and expo SDK 51

**Comment by ArvinRhen** [comment]
this issue should be reopened, i am also having issues in terms of performance in multiple nested stacks with material top tabs.

**Comment by vorn-dev-ni** [comment]
any solution?

**Comment by jahirfiquitiva** [comment]
It feels like React Navigation is slow mounting some screens.

@vijaychouhan-rails solution helped us show at least some loading screen while the screen is mounted, but I wonder if there's anything to make it faster 😕

**Comment by WKampel** [comment]
0.75 same issue with drawer

**Comment by Sheiicker** [comment]
Hello there,
I have been through a really slow display while using material-top-tabs.
**Here is my conclusion:**
The issue is due to a delay using `onLayout` in the `bottom-tabs/src/views/BottomTabBar.tsx`.

The `onLayout` attribute that carries `handleLayout` leaves a useState `setLayout` to 0 for too long.
Layout useState is used in `defaultTabWidth` which returns the TabBar with a `width=0`.

**The solution before a quick fix is using a custom TabBar:**
`<ProfilTab.Navigator tabBar={CustomTabBar}>`

If you want to keep the same style as the usual TabBar don't hesitate to rewrite the lib files in your project as a new component.

**Comment by camboYY** [comment]
"@react-navigation/bottom-tabs": "^7.2.0",
    "@react-navigation/devtools": "^7.0.15",
    "@react-navigation/native": "^7.0.14",
    "@react-navigation/stack": "^7.1.1",
    "react": "18.2.0",
    "react-native": "0.74.2",
i have the same issue.

**Comment by alexstock1** [comment]
still issue on 76.6, any updates?
