### ISSUE TITLE
Wired strip on the bottom of tab if set tab background color to transparent

### ISSUE THREAD

**Issue by themez** [react-navigation/react-navigation#11166]
### Current behavior

![image](https://user-images.githubusercontent.com/1323793/213468942-ce53f3e4-71e1-4afd-84a0-e547da97b46a.png)

### Expected behavior

the white strip should not show

### Reproduction

https://snack.expo.dev/@themez/getting-started-%7C-react-navigation

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view
- [ ] flipper-plugin-react-navigation

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.1.2
| @react-navigation/bottom-tabs          | 6.5.3
| @react-navigation/elements | 1.3.12
| @react-navigation/native-stack         | 6.9.7
| react-native-safe-area-context         | 4.4.1
| react-native-screens                   | 3.18.0
| react-native-reanimated                | 2.14.2
| react-native                           | 0.70.5
| expo                                   | 47.0.12
| node                                   | 16.15.1
| npm or yarn                            | 8.11.0

**Comment by themez** [comment]
Yes, this issue still exists

**Comment by lucyanddarlin** [comment]
Hi, this can be fixed if you pass elevation: 0 in the tabBarStyle. Elevation > 0 (default style of the bottom tab) and transparent background color has some quirks in android

**Comment by ceebows** [comment]
Can confirm this resolves issue.

**Comment by vagnerlandio** [comment]
> Hi, this can be fixed if you pass elevation: 0 in the tabBarStyle. Elevation > 0 (default style of the bottom tab) and transparent background color has some quirks in android

Thanks, I spent a lot of time trying to solve it and I tried your solution and it worked
