### ISSUE TITLE
I cant find any Animation speed or config props for React Native Tabs  

### ISSUE THREAD

**Issue by talha-ash** [react-navigation/react-navigation#11173]
### Current behavior

i see timing config in React Navigation V5 but not in 6 in tabs

### Expected behavior

I cant find any Animation speed or config props for React Native Tabs  

### Reproduction

I cant find any Animation speed or config props for React Native Tabs  

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages
- [X] @react-navigation/material-top-tabs 6.3.1
- [X] react-native-tab-view 3.3.0

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/bottom-tabs          |
| @react-navigation/material-top-tabs    |
]
| react-native-tab-view                  |

**Comment by okwasniewski** [comment]
Hey @talha-ash,

That's because material-top-tabs v5 supported react-native-tab-view till version 2.0.0 (back when it was using reanimated). 

Right now from version 3.0.0 tab-view doesn't support passing this config option (because of react-native-pager-view).

**Comment by talha-ash** [comment]
> Hey @talha-ash,
> 
> That's because material-top-tabs v5 supported react-native-tab-view till version 2.0.0 (back when it was using reanimated).
> 
> Right now from version 3.0.0 tab-view doesn't support passing this config option (because of react-native-pager-view).

thx
