### ISSUE TITLE
componentWIllUnmount gets called before navigation onBlur callback

### ISSUE THREAD

**Issue by Meninblack007** [react-navigation/react-navigation#11179]
### Description

With `react-native-screens` disabled, we used to get `blur` event on componentWillUnmount. Attaching screenshot for lifecycle.
 
<img width="284" alt="old" src="https://user-images.githubusercontent.com/6505547/215486364-dcd46770-3d1b-4640-a665-7d4729d6003b.png">

With `react-native-screens` enabled, we don't get `blur` event on componentWillUnmount as we tend to remove listener on unmount and unmount happens before blur callback is received by the container. Attaching screenshot for lifecycle.

<img width="277" alt="new" src="https://user-images.githubusercontent.com/6505547/215486383-305e28e8-d8b3-480f-9725-3e982110258e.png">

### Steps to reproduce

Sharing snack links with repro (these snack links uses latest version of screens and react native but this issue exists on older versions as well)
JS navigator: https://snack.expo.dev/@sanyam.jain/js-navigator
Native navigator: https://snack.expo.dev/@sanyam.jain/native-navigator

### Snack or a link to a repository

https://snack.expo.dev/@sanyam.jain/native-navigator

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view
- [ ] flipper-plugin-react-navigation

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | ^6.1.2
| @react-navigation/stack                | ^6.3.11
| @react-navigation/native-stack         | ^6.1.2
| react-native-safe-area-context         | 4.4.1
| react-native-screens                   | ~3.18.0
| react-native-gesture-handler           | ~2.8.0
| react-native-reanimated                | ~2.12.0
| react-native                           |  0.70.5

**Comment by Meninblack007** [comment]
Checkout this thread for more information: https://github.com/software-mansion/react-native-screens/issues/1695

**Comment by satya164** [comment]
This is expected. The `blur` event notifies the screen that it has been unfocused after navigation happens, but it happens asynchronously after the state update since effects are async, so the screen is removed before that happens.

If your use case is to remove listeners, you should be removing them in `componentWillUnmount` as well as `blur`. The component can get removed due to a variety of reasons, not only blur.

If you use function components using `useFocusEffect` will normalize these multiple cases in a single hook.
