### ISSUE TITLE
RootStack Navigator card styles classes flcikering on the WEB

### ISSUE THREAD

**Issue by oliviercperrier** [react-navigation/react-navigation#11186]
### Current behavior

https://user-images.githubusercontent.com/28421005/216150509-590848a7-1bae-4dbd-bcfb-90b819b0dce0.mov

As you can see on the video, when resizing the screen, the `RootStack.Navigator` -> `Card` classes are changing..

By default, the style contains:
- min-height: 100%

But when resizing, sometimes the following styles get applied: 
- overflow: hidden
- flex: 1 1 0%
- min-height: unset

This is causing the view to flicker.

In one of my app (i cant share it unfortunatly), sometimes this bug makes the entire screen flicker indefinitely... 
When opening the console, i can see the classes of the `RootStack.Navigator` changing by their own.

### Expected behavior

When resizing the screen, the style classes of the `RootStack.Navigator` -> `Card` should not flicker/change on their own.

### Reproduction

https://react-navigation-example.netlify.app/

### Platform

- [ ] Android
- [ ] iOS
- [X] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view
- [ ] flipper-plugin-react-navigation

### Environment

- [X] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
    "@react-native-async-storage/async-storage": "^1.17.11",
    "@react-navigation/native": "^6.1.2",
    "@react-navigation/native-stack": "^6.9.8",
    "@react-navigation/stack": "^6.3.11",
    "axios": "^0.21.4",
    "expo": "^47.0.13",
    "expo-constants": "~14.0.2",
    "expo-linking": "~3.3.0",
    "expo-secure-store": "~12.0.0",
    "expo-status-bar": "~1.4.2",
    "expo-updates": "^0.15.6",
    "react": "^18.1.0",
    "react-native": "^0.70.6",
    "react-native-email-link": "^1.14.3",
    "react-native-gesture-handler": "~2.8.0",
    "react-native-modalize": "^2.1.1",
    "react-native-reanimated": "^2.13.0",
    "react-native-safe-area-context": "4.4.1",
    "react-native-url-polyfill": "^1.3.0",
    "react-native-webview": "^11.26.0",
    "react-plaid-link": "^3.3.2",
    "redux": "^4.2.0",
    "redux-persist": "^6.0.0",
    "whatwg-url": "^12.0.0"

npm `8.11.0` with node `v16.16.0`

**Comment by oli-xentraffic** [comment]
I provided the react navigation netlify demo as a repro link because the bug can be observed on this app. See my video.

**Comment by oliviercperrier** [comment]
I provided the react navigation netlify demo as a repro link because the bug can be observed on this app. See my video.

**Comment by oliviercperrier** [comment]
So by adding the flashing style attribute to my RootStack.Navigator:
`    
flex: 1,
overflow: "hidden"
`

i don't get the shaking/flashing bug anymore.

Will close this issue as there is a fix for it.
