### ISSUE TITLE
No option to disable the navigation animation (navigate, goBack etc) so as to keep the swipe to go back animation on ios.

### ISSUE THREAD

**Issue by RomaKurilovich-Appmint** [react-navigation/react-navigation#11185]
### Current behavior

I want to disable the navigation animation when calling navigation api methods (go back or navigate), but still want to leave the swipe to back animation on ios.

Below I will describe 3 ways that did not work for me. 

First way.
CardStyleInterpolator which only works when swiping. [snack](https://snack.expo.dev/@moralek/navigation1).
This way doesn't work because after the gesture a new screen appears instantly without transition. If cardStyleInterpolator had transiting params it would be a great solution.

Second way.
Looks wrong and there is no way to configure transition [snack](https://snack.expo.dev/@moralek/navigation2).

Third way.
Like in the first case, the animation after the swipe does not work. [snack](https://snack.expo.dev/@moralek/navigation3)

### Expected behavior

Disable the navigation animation, keep the swipe (to go back) animation on ios.

### Reproduction

Links to examples in the section "Current behavior".

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view
- [ ] flipper-plugin-react-navigation

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |6.0.13|
| @react-navigation/stack                |6.3.12|
| react-native-screens                   |3.18.0|
| react-native-gesture-handler           |2.8.0|

**Comment by satya164** [comment]
This is not a bug. You're requesting a new feature so please open a feature request in canny and include the use case.
