### ISSUE TITLE
[react-native-tab-view] Setting TabBar background color to transparent causes interaction animation to overflow

### ISSUE THREAD

**Issue by acb** [react-navigation/react-navigation#11198]
### Current behavior

When you set `style={{backgroundColor: "transparent"}}` (or `style={{backgroundColor: undefined}}`) on the TabBar component on Android the interaction animation overflows the tab bar and looks quite jarring.

How it looks with a background color -- the interaction animation is confined to the tab bar element:
![Screenshot_1675574016](https://user-images.githubusercontent.com/4690898/216803396-0444b56c-7a79-4aff-b601-8ff9c8237040.png)

How it looks without a background color -- the interaction animation overflows both the tab bar and the content below:
![Screenshot_1675574030](https://user-images.githubusercontent.com/4690898/216803421-530a6e1a-7ad4-4e02-bef3-253212b69c0f.png)

### Expected behavior

With a transparent tab bar background the interaction animation should still be limited to the physical bounds of the TabBar component.

### Reproduction

https://snack.expo.dev/@taboobat/react-native-tab-view-bug

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [X] react-native-tab-view
- [ ] flipper-plugin-react-navigation

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native | 6.1.3
| react-native-tab-view                  | 3.3.4

**Comment by acb** [comment]
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?

Indeed it does my bot friend.

**Comment by okwasniewski** [comment]
Hey @acb, 

We've released tab-view `3.4.0` it now allows you to pass `android_ripple={{borderless: false}}`. Let me know if this fixes your bug, so I can close this issue.

**Comment by acb** [comment]
@okwasniewski sorry I missed your ping -- I just updated to 3.4.0 and confirm that the ripple is working as expected now!  Thank you for the quick turnaround!
