### ISSUE TITLE
Missing-asset-registry-path for @react-navigation/elements/lib/commonjs/assets/back-icon-mask.png on RN 70.6

### ISSUE THREAD

**Issue by boostvolt** [react-navigation/react-navigation#11192]
### Current behavior

When building my app I get the following error message since I switched to React Native 70.6 (Android and iOS), without `@react-navigation` everything works. On React Native 69.7, the app runs without problems with the identical `@react-navigation` versions.

```
Error: Unable to resolve module missing-asset-registry-path from /node_modules/@react-navigation/elements/lib/commonjs/assets/back-icon-mask.png: missing-asset-registry-path could not be found within the project or in these directories:
  node_modules
> 1 | �PNG
  2 | 
  3 | 
  4 | IHDR2���gAMA��
                    �a cHRMz&�����u0�`:�p��Q<bKGD���̿tIME�
    at ModuleResolver.resolveDependency (/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:178:15)
    at DependencyGraph.resolveDependency (/node_modules/metro/src/node-haste/DependencyGraph.js:264:43)
    at Object.resolve (/node_modules/metro/src/lib/transformHelpers.js:170:21)
    at resolveDependencies (/node_modules/metro/src/DeltaBundler/graphOperations.js:466:33)
    at processModule (/node_modules/metro/src/DeltaBundler/graphOperations.js:232:31)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async addDependency (/node_modules/metro/src/DeltaBundler/graphOperations.js:361:18)
    at async Promise.all (index 18)
    at async processModule (/node_modules/metro/src/DeltaBundler/graphOperations.js:279:3)
    at async addDependency (/node_modules/metro/src/DeltaBundler/graphOperations.js:361:18)
```

### Expected behavior

The build should pass successfully.

### Reproduction

bare react-native project

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view
- [ ] flipper-plugin-react-navigation

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.1.3
| @react-navigation/stack                | 6.3.12
| react-native-safe-area-context         | 4.5.0
| react-native-screens                   | 3.19.0
| react-native-gesture-handler           | 2.9.0
| react-native-reanimated                | 2.14.4
| react-native                           | 70.6
| expo                                   | 47.0.13
| node                                   | 18.12.1
| npm or yarn                            | 8.19.2

**Comment by bananer** [comment]
@boostvolt could you fix the problem? It occurs for me with a different package (react-native-calendars), and this is the only good result when googling for the error message.

**Comment by naeliofreires** [comment]
@bananer @boostvolt 

Could you fix the problem guys? I am this right now


`Unable to resolve module missing-asset-registry-path from ProjectName/src/assets/images/waysaverTRPLogo.png: missing-asset-registry-path could not be found within the project or in these directories:
  node_modules`

**Comment by EmanoelLoreto** [comment]
I'ma with the same error: 

``..\..\modules\linxpay\dependencies\react-native-linxtef-module\src\assets\remove-card.gif: native\apps\assistenteVendas\node_modules\react-native\Libraries\Image\AssetRegistry could not be found within the project. `

Did someone already fix that?

**Comment by nth-zik** [comment]
The same on me on react-native 0.71.10 and 0.72.0

**Comment by saurabhbakolia** [comment]
The same error I am getting. I don't know, but when I installed the `react-native-svg-transfer`. This error started.

**Comment by tohshine** [comment]
This is a bug from the latest version of React Native and the issue is caused by the react-native-svg library installed, what works for me so I installed the previous version of react-native.

**Comment by VijayMFinGlide** [comment]
> This is a bug from the latest version of React Native and the issue is caused by the react-native-svg library installed, what works for me so I installed the previous version of react-native.

"react-native": "^0.70.0" is working for me ...  Thanks [tohshine](https://github.com/tohshine)

**Comment by aikhan** [comment]
> This is a bug from the latest version of React Native and the issue is caused by the react-native-svg library installed, what works for me so I installed the previous version of react-native.

Were you able to fix it other than by downgrading. I need to be on 0.73 and this problem persists.

**Comment by VijayMFinGlide** [comment]
> > This is a bug from the latest version of React Native and the issue is caused by the react-native-svg library installed, what works for me so I installed the previous version of react-native.
> 
> Were you able to fix it other than by downgrading. I need to be on 0.73 and this problem persists.

Unfortunately, no  I am still running with "react-native": "^0.70.0"

**Comment by gorgon** [comment]
+1

**Comment by 0xlethe** [comment]
+1 for 0.73

**Comment by iSaBo96** [comment]
+1 for 0.73

**Comment by dancosta-fed** [comment]
+1 for 0.73

**Comment by Alexandra-Rdrgs** [comment]
+1 for 0.73.

**Comment by FakeCoder01** [comment]
@dancosta-fed Thank you so much. it has saved my a$$.

**Comment by rpatidar** [comment]
I was facing the similar issues for the expo, in my case I didn't needed the metro config so i deleted and it worked.

**Comment by Upsite-cor** [comment]
> > This is a bug from the latest version of React Native and the issue is caused by the react-native-svg library installed, what works for me so I installed the previous version of react-native.
> 
> Were you able to fix it other than by downgrading. I need to be on 0.73 and this problem persists.

I do too. Downgrading should not be the only option.

**Comment by Jithinkrishnapu** [comment]
Don't be panic just do `npx react-native start --reset-cache` that's it . It will work fine.

**Comment by CarlosAlbertoTI** [comment]
> Just do `npx react-native start --reset-cache` that's it . It will work fine.

This didn't work for me

**Comment by tb-dhk** [comment]
this is still happening for me and i have no idea what to do about it

**Comment by Sergio1C** [comment]
So, it seems not fixed yet :-(
