### ISSUE TITLE
Screen options for transition animation are not working for Android.

### ISSUE THREAD

**Issue by osvald0** [react-navigation/react-navigation#11211]
### Current behavior

Always the default animation transition is displayed for Android for any specified `TransitionPresets`.

### Expected behavior

The specified animation transition in `screenOptions` should be displayed.

### Reproduction

https://github.com/osvald0/rn-navigation-issue

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [x] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view
- [ ] flipper-plugin-react-navigation

### Environment

Node: 16.13.2
Yarn: 1.22.17
"@react-navigation/native": "^6.1.3",
"@react-navigation/native-stack": "^6.9.9",
"@react-navigation/stack": "^6.3.12",
"react": "18.2.0",
"react-native": "0.71.2",
"react-native-gesture-handler": "^2.9.0",
"react-native-safe-area-context": "^4.5.0",
"react-native-screens": "^3.19.0",
"react-native-webview": "^11.26.1"

**Comment by BeeMargarida** [comment]
I think this is due to the fact that you are using the `@react-navigation/native-stack`. If you change to `createStackNavigator` from `@react-navigation/stack` it works. The docs say:

>One thing to keep in mind is that while @react-navigation/native-stack offers native performance and exposes native features such as large title on iOS etc., it may not be as customizable as [@react-navigation/stack](https://reactnavigation.org/docs/stack-navigator) depending on your needs. So if you need more customization than what's possible in this navigator, consider using @react-navigation/stack instead - which is a more customizable JavaScript based implementation.
