### ISSUE TITLE
App crashes on android while using stack navigation

### ISSUE THREAD

**Issue by jabedzaman** [react-navigation/react-navigation#11216]
### Current behavior

I been trying to use stack navigation. As soon as I try to open the app it crashes unexpectedly...

Heres the code:
```bash
import { NavigationContainer } from "@react-navigation/native";
import { createStackNavigator } from "@react-navigation/stack";
import Home from "./screens/Home";
import Settings from "./screens/Settings";

const Stack = createStackNavigator();

export default function App() {
  return (
    <NavigationContainer>
      <Stack.Navigator>
        <Stack.Screen
          options={{
            headerShown: false,
          }}
          name="Home"
          component={Home}
        />
        <Stack.Screen
          options={{
            headerShown: false,
          }}
          name="Settings"
          component={Settings}
        />
      </Stack.Navigator>
    </NavigationContainer>
  );
}

```

### Expected behavior

The app should open and I should be able to move between screens

### Reproduction

https://github.com/jabedzaman/spotiloader

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view
- [ ] flipper-plugin-react-navigation

### Environment

- [ ] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | ^6.1.2
| @react-navigation/bottom-tabs          |
| @react-navigation/drawer               |
| @react-navigation/material-bottom-tabs |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                |^6.3.12
| @react-navigation/native-stack         | ^6.9.8
| react-native-safe-area-context         | 4.4.1
| react-native-screens                   |
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           | 0.70.5
| expo                                   | ~47.0.12
| node                                   | v19.4.0.
| npm or yarn                            | 8.19.2

**Comment by jabedzaman** [comment]
I tried doing on a bare local expo project but still its not working out. The app is running on emulator but on a physical device its crashing...

Here is the `package.json` :

```bash
{
  "name": "spotiloader",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "@react-navigation/native": "^6.1.3",
    "@react-navigation/stack": "^6.3.12",
    "expo": "~47.0.12",
    "expo-status-bar": "~1.4.2",
    "react": "18.1.0",
    "react-native": "0.70.5"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9"
  },
  "private": true
}
```

Here is my `app.js`

```bash
import { NavigationContainer } from "@react-navigation/native";
import { createStackNavigator } from "@react-navigation/stack";
import Home from "./screens/Home";
import Settings from "./screens/Settings";

const Stack = createStackNavigator();

export default function App() {
  return (
    <NavigationContainer>
      <Stack.Navigator>
        <Stack.Screen
          options={{
            headerShown: false,
          }}
          name="Home"
          component={Home}
        />
        <Stack.Screen
          options={{
            headerShown: false,
          }}
          name="Settings"
          component={Settings}
        />
      </Stack.Navigator>
    </NavigationContainer>
  );
}
```

**Comment by kacperkapusciak** [comment]
Hello @jabedzaman 👋 
Sorry, but I won't consider a fully fledged application as a minimal reproduction example.

In the second comment of "local expo project" I can tell from `package.json` that you're missing some installation steps i.e. installation of `react-native-screens` and `react-native-safe-area-context`.

Here's the link for with installation steps you: https://reactnavigation.org/docs/getting-started/#installing-dependencies-into-an-expo-managed-project 

Cheers

**Comment by vijay38** [comment]
I am also facing the same issue, what is the solution for this?

**Comment by recepaltas** [comment]
same ??
