### ISSUE TITLE
react-native-tab-view does not render for nested scrollable tab view

### ISSUE THREAD

**Issue by paulsjohnson91** [react-navigation/react-navigation#11218]
### Current behavior

On ios and android (not web) the tabs in a nested scrollable tab view do not render

<img width="290" alt="Screenshot 2023-02-11 at 17 48 54" src="https://user-images.githubusercontent.com/28013436/218273205-dc575d14-2d14-4ae4-be96-2f39fab92415.png">

### Expected behavior

tabs should be visible and scrollable as they are in the web view

<img width="338" alt="Screenshot 2023-02-11 at 17 49 08" src="https://user-images.githubusercontent.com/28013436/218273215-fb85412f-d8a0-4ff5-b98e-e5bd240b4c21.png">

### Reproduction

https://snack.expo.dev/@pxj101/react-native-tab-view-quick-start

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [X] react-native-tab-view
- [ ] flipper-plugin-react-navigation

### Environment

"react-native-tab-view": "3.1.1",
"react-native-pager-view": "5.4.9"

expo version 46

**Comment by paulsjohnson91** [comment]
version 3.3.4 has the same behaviour, and although this issue doesn't include react-navigation/native in my app I have installed the latest version navigation 7.32

**Comment by okwasniewski** [comment]
Hey @paulsjohnson91, 

This behaviour is not going to be supported in upcoming versions of tab-view, I'm linking answer to a similar issue: https://github.com/satya164/react-native-tab-view/issues/1349#issuecomment-1320052854

**Comment by Moistbobo** [comment]
It would be great if the documentation [here](https://reactnavigation.org/docs/tab-view/#avoid-rendering-tabview-inside-scrollview) was updated to explicitly state that TabView content nested in a `Scrollview` **will not be rendered**

**Comment by ahmetkuslular** [comment]
@okwasniewski  hi.  This is still a great need. Unfortunately, the current problem occurs when I migrate an old project(v2.14) to the current version. The problem here is not an edge case and it is a situation we need in applications. For example, if we were to create Instagram's profile page, how can we create it without any problems with this package? There are other header-related problems in the proposed collapsible-tab-view library. :/
