### ISSUE TITLE
Can't extract screen to different files

### ISSUE THREAD

**Issue by bryantobing12** [react-navigation/react-navigation#11217]
### Current behavior

![image](https://user-images.githubusercontent.com/46083126/218253953-e05ad03e-9e10-4a81-a33d-f332a9c73529.png)

i got this error when extracting my screen out from a single file.

I used to define it like this only in a single file

```tsx
// navigation.ts
export const RootStack = createStackNavigator<RootStackParamList>()

export const Navigation = () => {
  return (
    <NavigationContainer>
       <RootStack.Navigator>
        // All my screen defined here
        <RootStack.Screen name="FinanceScreen" component={FinanceScreen} />
        
        // This later will be moved to its own file
        <RooStack.Screen name="PostScreen" component={PostScreen}/>
        <RooStack.Screen name="PostDetailsScreen" component={PostDetailsScreen}/>
        
       </RootStackNavigator>
    </NavigationContainer>
 )
}
```

now I have more than 100 screens. so it is hard to main it in only a single file. and i want to extract some screens to its own file based on their context.

I created a new file called `PostRelatedScreens.tsx`, this will contain all screens related to post

```tsx
import { RootStack } from "./navigation"

export const PostRelatedScreens = () => {
  return (
    <>
      <RooStack.Screen name="PostScreen" component={PostScreen}/>
      <RooStack.Screen name="PostDetailsScreen" component={PostDetailsScreen}/>
    </>
  )
}
```

after that i imported `PostRelatedScreens` component and render it in navigation.ts

```tsx
import { PostRelatedScreens } from "./PostRelatedScreens"

// navigation.ts
export const RootStack = createStackNavigator<RootStackParamList>()

export const Navigation = () => {
  return (
    <NavigationContainer>
       <RootStack.Navigator>
        // All my screen defined here
        <RootStack.Screen name="FinanceScreen" component={FinanceScreen} />

        // i'm planning to move all my screen to this structure to make it tidier        
        <PostRelatedScreens/>       
        
       </RootStackNavigator>
    </NavigationContainer>
 )
}
```

But i got this error instead like i put in a screenshot above

```
A navigator can only contain 'Screen', 'Group' or 'React.Fragment' as its direct children. To render this component in the navigator, pass it in the component prop to Screen
```

### Expected behavior

the expected behavior is that it should work as I put all my screens in a single file. because what I did is only extract it to different files/components. so that I have a cleaner structure of my file and I can maintain it better. Because having more than 100 screens in a single file is really hard to maintain. not to mention the import line for the screen file

### Reproduction

https://snack.expo.dev/@bryanltobing/react-navigation

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view
- [ ] flipper-plugin-react-navigation

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |6.1.3
| @react-navigation/bottom-tabs          |
| @react-navigation/drawer               |
| @react-navigation/material-bottom-tabs |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                |6.3.12
| @react-navigation/native-stack         |
| react-native-safe-area-context         |
| react-native-screens                   |
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           |
| expo                                   |
| node                                   |
| npm or yarn                            |

**Comment by FN-FAL113** [comment]
experienced this yesterday, would appreciate if there is way for this , I already tried using fragment, Group but to no avail

**Comment by bryantobing12** [comment]
unfortunately, I'm still experiencing this

**Comment by satya164** [comment]
It's not possible due to limitations in React. You can make regular functions that return an array of screens instead of components if you want to keep them in separate functions.

**Comment by bryantobing12** [comment]
> It's not possible due to limitations in React. You can make regular functions that return an array of screens instead of components if you want to keep them in separate functions.

could you mention what kind of limitation that is?

also i tried to put it in a regular function but i couldn't get the typescript types work properly.
would u mind sharing an example?

**Comment by FN-FAL113** [comment]
> > It's not possible due to limitations in React. You can make regular functions that return an array of screens instead of components if you want to keep them in separate functions.
> 
> could you mention what kind of limitation that is?
> 
> also i tried to put it in a regular function but i couldn't get the typescript types work properly. would u mind sharing an example?
> 
> i'm also not sure i get what you mean by array of screens

should be an array of screen components, it could be a normal arrow or named function that returns these instead of having them as a react component, haven't tried it but surely it will work

**Comment by bryantobing12** [comment]
> should be an array of screen components, it could be a normal arrow or named function that returns these instead of having them as a react component, haven't tried it but surely it will work

do you mean something like this???


```tsx
export const PostRelatedScreens = () => {
  return [
      <RooStack.Screen name="PostScreen" component={PostScreen}/>,
      <RooStack.Screen name="PostDetailsScreen" component={PostDetailsScreen}/>,
  ]
}

```

and call it like this?

```tsx
import { PostRelatedScreens } from "./PostRelatedScreens"

// navigation.ts
export const RootStack = createStackNavigator<RootStackParamList>()

export const Navigation = () => {
  return (
    <NavigationContainer>
       <RootStack.Navigator>
        // All my screen defined here
        <RootStack.Screen name="FinanceScreen" component={FinanceScreen} />

        {PostRelatedScreens()}
        
       </RootStackNavigator>
    </NavigationContainer>
 )
}

```

**Comment by FN-FAL113** [comment]
> > should be an array of screen components, it could be a normal arrow or named function that returns these instead of having them as a react component, haven't tried it but surely it will work
> 
> do you mean something like this???
> 
> ```tsx
> export const PostRelatedScreens = () => {
>   return [
>       <RooStack.Screen name="PostScreen" component={PostScreen}/>,
>       <RooStack.Screen name="PostDetailsScreen" component={PostDetailsScreen}/>,
>   ]
> }
> ```
> 
> and call it like this?
> 
> ```tsx
> import { PostRelatedScreens } from "./PostRelatedScreens"
> 
> // navigation.ts
> export const RootStack = createStackNavigator<RootStackParamList>()
> 
> export const Navigation = () => {
>   return (
>     <NavigationContainer>
>        <RootStack.Navigator>
>         // All my screen defined here
>         <RootStack.Screen name="FinanceScreen" component={FinanceScreen} />
> 
>         {PostRelatedScreens()}
>         
>        </RootStackNavigator>
>     </NavigationContainer>
>  )
> }
> ```

yeah, tried similar thing for react web, tbh its ugly looking but does its job, have you tested it

**Comment by brleinad** [comment]
I tested and this approach worked for me thanks!


> > > should be an array of screen components, it could be a normal arrow or named function that returns these instead of having them as a react component, haven't tried it but surely it will work
> > 
> > 
> > do you mean something like this???
> > ```tsx
> > export const PostRelatedScreens = () => {
> >   return [
> >       <RooStack.Screen name="PostScreen" component={PostScreen}/>,
> >       <RooStack.Screen name="PostDetailsScreen" component={PostDetailsScreen}/>,
> >   ]
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and call it like this?
> > ```tsx
> > import { PostRelatedScreens } from "./PostRelatedScreens"
> > 
> > // navigation.ts
> > export const RootStack = createStackNavigator<RootStackParamList>()
> > 
> > export const Navigation = () => {
> >   return (
> >     <NavigationContainer>
> >        <RootStack.Navigator>
> >         // All my screen defined here
> >         <RootStack.Screen name="FinanceScreen" component={FinanceScreen} />
> > 
> >         {PostRelatedScreens()}
> >         
> >        </RootStackNavigator>
> >     </NavigationContainer>
> >  )
> > }
> > ```
> 
> yeah, tried similar thing for react web, tbh its ugly looking but does its job, have you tested it

**Comment by omarbenzi** [comment]
how this solution can be typed ?

**Comment by suark** [comment]
> how this solution can be typed ?

Do you mean the example of returning an array of screens? I think it would automatically be typed by typescript

**Comment by omarbenzi** [comment]
@suark thank you for your reply 

I import the trypes from the other stacks and I do this:  

`export type Stack1ParamList = {
    Screen1: undefined;
    Screen2: undefined;
    Screen3: undefined;
} & Stack2ParamList &
    Stack3ParamList;`
