### ISSUE TITLE
[Reanimated] Issue with @react-navigation/drawer in react-native-macos

### ISSUE THREAD

**Issue by edcylau** [react-navigation/react-navigation#11229]
### Current behavior

I am trying to build a drawer with react-native-macos, yet got into the problem below, is it a known issue? or is there a drawer solution for react native macos?? Thanks

```
 ERROR  [Reanimated] Couldn't determine the version of the native part of Reanimated. Did you forget to re-build the app after upgrading react-native-reanimated? If you use Expo Go, you must use the exact version which is bundled into Expo SDK.
  ERROR  TypeError: undefined is not an object (evaluating 'this.InnerNativeModule.installCoreFunctions')
App@http://192.168.1.200:8081/index.bundle?
platform=macos&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.

 ERROR  Error: Requiring module "node_modules/@react-navigation/drawer/src/index.tsx", which threw an exception: TypeError: undefined is not an object (evaluating 'this.InnerNativeModule.installCoreFunctions')
  ERROR  TypeError: undefined is not an object (evaluating '_$$_REQUIRE(_dependencyMap[3], "@react-navigation/drawer").createDrawerNavigator')

This error is located at:
    in App (at renderApplication.js:50
  ERROR  TypeError: undefined is not an object (evaluating '_$$_REQUIRE(_dependencyMap[3], "@react-navigation/drawer").createDrawerNavigator')

This error is located at:
    in App (at renderApplication.js:50)
```

### Expected behavior

The build should have completed successfully.

### Reproduction

https://snack.expo.io/?platform=android&name=Getting%20started%20%7C%20React%20Navigation&dependencies=%40expo%2Fvector-icons%40*%2C%40react-native-community%2Fmasked-view%40*%2C%40react-navigation%2Fbottom-tabs%40%5E5.11.15%2C%40react-navigation%2Fdrawer%40%5E5.12.9%2C%40react-navigation%2Fmaterial-bottom-tabs%40%5E5.3.19%2C%40react-navigation%2Fmaterial-top-tabs%40%5E5.3.19%2C%40react-navigation%2Fnative%40%5E5.9.8%2C%40react-navigation%2Fstack%40%5E5.14.9%2Creact-native-paper%40%5E4.0.1%2Creact-native-reanimated%40*%2Creact-native-safe-area-context%40*%2Creact-native-gesture-handler%40*%2Creact-native-screens%40*%2Creact-native-tab-view%40%5E2.15.1&hideQueryParams=true&sourceUrl=https%3A%2F%2Freactnavigation.org%2Fexamples%2F5.x%2Fdrawer-open-close-toggle.js

### Platform

- [ ] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [X] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view
- [ ] flipper-plugin-react-navigation

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
   "@react-native-async-storage/async-storage": "^1.17.11",
    "@react-navigation/drawer": "^6.6.0",
    "@react-navigation/native": "^6.1.4",
    "@react-navigation/stack": "^6.3.13",
    "react": "17.0.2",
    "react-native": "0.66.3",
    "react-native-config": "^1.5.0",
    "react-native-gesture-handler": "^2.9.0",
    "react-native-macos": "^0.66.0-0",
    "react-native-reanimated": "^2.14.4",
    "react-native-safe-area-context": "^4.5.0",
    "react-native-screens": "^3.20.0",
    "react-native-windows": "0.66.25"

**Comment by edcylau** [comment]
Yes it's the same, when I have upgraded to @react-navigation/stack  6.3.14

**Comment by FrenchMajesty** [comment]
Faced the same issue. Decided to not use the react-navigation drawer and hack together a drawer functionality within my app elsewhere.

The library that this depends on (`react-native-reanimated`) is riddled with issues that developers have to get it working either in development or in production. Just spend 10min on Google and you will see. Furthermore, their docs talk about running installs on CocoaPods which you cannot do if you're within Expo. 

Overall, this is not worth the hassle to get it working IMO. I recommend others who land here from future Googling to take another approach

**Comment by omatsola619** [comment]
yeah i can't use it either, react-native-reanimated has a lot of issues

**Comment by AnhKhoaVo26** [comment]
.[Reanimated] Couldn't determine the version of the native part of Reanimated. Did you forget to re-build the app after upgrading react-native-reanimated? If you use Expo Go, you must use the exact version which is bundled into Expo SDK.
 ERROR  TypeError: this.InnerNativeModule.makeShareableClone is not a function. (In 'this.InnerNativeModule.makeShareableClone(value, shouldPersistRemote)', 'this.InnerNativeModule.makeShareableClone' is undefined)
. ERROR  Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 11): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient, RCTEventEmitter.
   .     A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
 ERROR  Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 11): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient, RCTEventEmitter.
     .   A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native
     -->Help me

**Comment by Wolf-111** [comment]
Same issue here. I've tried 
- expo doctor --fix-dependencies
- Deleting podfile.lock, DerivedData folder, build folder, Pods folder, project_name.xcworkspace folder, node_modules, yarn.lock and reinstalling packages using yarn install
- npx expo install react-native-reanimated

Nothing has helped unfortunately. Just for some context, here is my expo and my react-native-reanimated versions - 
"expo": "~48.0.9"
"react-native-reanimated": "~2.14.4"
