### ISSUE TITLE
The type annotation for headerBackVisible in stack options, say its for platform IOS only.

### ISSUE THREAD

**Issue by Vin-Xi** [react-navigation/react-navigation#11221]
### Current behavior

The type definition for headerBackVisible, says its for platform IOS only. However in the documentation, there is no such mention. I have also checked for both android and IOS devices, it works fine. 

<img width="682" alt="Screen Shot 2023-02-13 at 11 15 17 AM" src="https://user-images.githubusercontent.com/45799230/218394182-757f5a92-42b9-48cf-ae04-c9c6b17ba983.png">

### Expected behavior

The definition should be corrected, corresponding with the documentation.

I have raised a PR, to correct this, if this indeed, is a mistake in type definitions. https://github.com/react-navigation/react-navigation/pull/11220

### Reproduction

https://github.com/react-navigation/react-navigation/blob/main/packages/native-stack/src/types.tsx

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view
- [ ] flipper-plugin-react-navigation

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native-stack         | 6.9.9

**Comment by PtjeEquinor** [comment]
@Vin-Xi Does headerBackVisible work on web for you? I suspect the type definition was correct here.
