### ISSUE TITLE
[Android][Android 13] Hardware back button don't work at all on physical device 

### ISSUE THREAD

**Issue by Roamer77** [react-navigation/react-navigation#11227]
### Current behavior

I have nativeStackNavigator with inner tabNavigator. Each screen of tabNavigator is nativeStackNavigator.   The issue is hardware backButton don't work at all on Android physical  device with Android 13.  I have tried  use simple useBackHandler  hook in my app but it haven't solved problem. Every thing works nice on every device with Android OS lower than 13.  I have tasted on Pixel 7, Samsung s22

### Expected behavior

On physical device with OS Android 13  hardware backButton should work as expected (back to previous screen)

### Reproduction

https://github.com/Roamer77/Android13backButtonBug

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view
- [ ] flipper-plugin-react-navigation

### Environment

"react-native": "0.70.3", 
   "@react-navigation/bottom-tabs": "^6.3.2",
    "@react-navigation/native": "^6.0.11",
    "@react-navigation/native-stack": "^6.7.0",

**Comment by Navipro70** [comment]
@satya164 
We have the same issue, can you please response, what may cause the problem?

**Comment by ronjunevaldoz** [comment]
any solution?

**Comment by fukemy** [comment]
I have tested on Android 13, backbutton make app exist, not called as `navigation.pop()`

**Comment by GaudetteM** [comment]
I'm still experiencing this issue with the latest version for Android 13+.

**Comment by antoxa2584x** [comment]
Same here

**Comment by usmanabid94** [comment]
any solution or update on this i am facing the same issue on v6 react navigation bottom tabs

**Comment by satya164** [comment]
React Navigation uses [BackHandler](https://reactnative.dev/docs/backhandler) to listen to hardware back button press. If `BackHandler` isn't working as you expect, please open an issue in React Native repo.

**Comment by ronal2s** [comment]
> It was fixed when i switched by device somehow it was not working on google pixel device but works fine on rest of the devices.

I mean yes but that's not a solution, or you will ask to your users change the device to use your app?

**Comment by usmanabid94** [comment]
> > It was fixed when i switched by device somehow it was not working on google pixel device but works fine on rest of the devices.
> 
> I mean yes but that's not a solution, or you will ask to your users change the device to use your app?

Yes you are right it should work on all devices but i mentioned the scenario here in which i was facing the issue.Hoping for the solution on it soon from the community.

**Comment by nived-cv** [comment]
I still have the issue

**Comment by usmanabid94** [comment]
is there any update on this @satya164 @antoxa2584x @ronal2s @Roamer77

**Comment by enchorb** [comment]
Getting the same issue on Google Pixel devices, opened https://github.com/facebook/react-native/issues/44670 in the React Native repo

**Comment by Wellapos** [comment]
I have this same error on Android 13 and 14.

**Comment by baronha** [comment]
> Tôi cũng gặp lỗi này trên Android 13 và 14.

Same me on Android 13, 14

**Comment by baronha** [comment]
> I have this same error on Android 13 and 14.

same me on Android 13, 14

**Comment by usmanabid94** [comment]
no fix for this till now strange

**Comment by Wellapos** [comment]
@baronha @usmanabid94 

I fix this issue with [this](https://stackoverflow.com/questions/78463555/react-native-app-closes-on-android-back-button-or-swipe-left-android-13-devices)

-  Add implementation `"androidx.activity:activity:1.6.0-alpha05"` to project build.gradle
-  Add `android:enableOnBackInvokedCallback="false"` to either the application or specific activity in AndroidManifest.xml

**Comment by baronha** [comment]
> @baronha @usmanabid94
> 
> I fix this issue with [this](https://stackoverflow.com/questions/78463555/react-native-app-closes-on-android-back-button-or-swipe-left-android-13-devices)
> 
> * Add implementation `"androidx.activity:activity:1.6.0-alpha05"` to project build.gradle
> * Add `android:enableOnBackInvokedCallback="false"` to either the application or specific activity in AndroidManifest.xml

Yup. Yesterday I added `android:enableOnBackInvokedCallback="false”` and it worked fine.
