### ISSUE TITLE
Drawer for ONLY one screen

### ISSUE THREAD

**Issue by nica0012** [react-navigation/react-navigation#11230]
### Current behavior

Drawer opens on all screens when nested in a drawer navigator

### Expected behavior

I only want the drawer to be accessible from the first, "Home" tab.

### Reproduction

-

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view
- [ ] flipper-plugin-react-navigation

### Environment

Is this possible?

It seems I am unable to wrap a drawer on only one screen. I am converting from react native router flux where this was possible. I am just confused because that library was built off of React Navigation.

Cheers.

**Comment by danish-dct** [comment]
You can pass Drawer Navigator component inside main Stack navigation screen.

```
<Stack.Navigator
			screenOptions={{
				headerShown: false,
			}}
		>
<Stack.Screen
				name="Login"
				component={Login}
				options={{ headerShown: false }}
			/>
            <Stack.Screen
                name="DrawerNavigator"
                component={DrawerNavigator}
            />
		</Stack.Navigator>
```

Then, inside the Drawer, you can add your home screen:

```
<Drawer.Navigator
				backBehavior="none"
				drawerType="slide"
				overlayColor="transparent"
				drawerContentOptions={{
					activeBackgroundColor: 'transparent',
					activeTintColor: 'white',
					inactiveTintColor: 'white',
				}}
				sceneContainerStyle={styles.scene}
				drawerContent={(props) => {
					return <DrawerNavigatorTemplate {...props} />;
				}}
			>
				<Drawer.Screen 
					name="Home" 
					component={Home}
					options={{
						headerShown: false,
					}}
				/>
			</Drawer.Navigator>
```
