### ISSUE TITLE
How to keep screen state after navigating ?

### ISSUE THREAD

**Issue by cashbackdev** [react-navigation/react-navigation#11258]
### Current behavior

I have a navigator looking like this :

    <NavigationContainer>
            <Stack.Navigator>
                <Stack.Screen name="Home" component={HomeScreen} />
                <Stack.Screen name="Support" component={SupportScreen} />
            </Stack.Navigator>
     </NavigationContainer>

HomeScreen and SupportScreen both only have a <TextInput> component rendered in their function.
I want every screen to persist the content but it is not working for me
here are the steps :
1. the navigator loads on the Home screen
2. I type 'abc' in Home's TextInput
3. navigate to SupportScreen
4. Type 'xyz' in Support's TextInput
5. goBack/navigate to Home 
6. I can see 'abc' in the input
7. navigate to Support
8. the input is empty

### Expected behavior

I would expect Support's TextInput to keep the text in the input

### Reproduction

https://snack.expo.dev/@devcashback/how-to-keep-screen-state-after-navigating

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
"@react-navigation/bottom-tabs": "^6.5.7",
"@react-navigation/native": "^6.1.6",
"@react-navigation/native-stack": "^6.9.8",
"@react-navigation/stack": "^6.3.16",
"react-native": "0.71.1",
| node -> v18.12.1                |
| npm -> 8.19.2                            |

**Comment by satya164** [comment]
That's how a stack navigator works. You add screens to the stack and you remove screens from the stack. If you don't want to remove the screens then you need to use a different navigator or build your own navigator. If it's only some state that you want to keep then store them in a global store.

**Comment by cashbackdev** [comment]
This worked for me (the update part):
https://stackoverflow.com/a/75608398/17208512

**Comment by amfredfred** [comment]
i don't know if this is the best way to do this but, 
i had this same challenge, 
i solve by doing blow:

```
<BottomTab.Screen 
    name='...' 
    component={Component} 
    options={{ freezeOnBlur: false, unmountOnBlur: false }} 
/>
```

then inside the Component useMemo(() => tsx || jsx, [dependencies])
