### ISSUE TITLE
Drawer undefined property 'prototype' value with Reanimated v3.0.0

### ISSUE THREAD

**Issue by FN-FAL113** [react-navigation/react-navigation#11252]
### Current behavior

currently reanimated v2 is only supported on various navigators that relies on reanimated as its dependency, reanimated v3 fixes a lot of bugs associated with layout animations, etc. 

### Expected behavior

Drawers must work properly on the latest reanimated which is currently unsupported

### Reproduction

1. Upgrade existing reanimated 2 package to v3.0.0
2. Throws an exception on start up specifically inside drawer.tsx

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [x] @react-navigation/bottom-tabs
- [x] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [x] @react-navigation/stack
- [x] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | latest
| @react-navigation/bottom-tabs          | latest
| @react-navigation/drawer               | latest
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                | latest
| @react-navigation/native-stack         | latest
| react-native-safe-area-context         | latest
| react-native-screens                   | latest
| react-native-gesture-handler           | latest
| react-native-reanimated                | 3.0.0
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           | 0.71.3
| expo                                   |
| node                                   | 16
| npm or yarn                            |

**Comment by SuperBigBang** [comment]
+1

**Comment by satya164** [comment]
what do you mean by reanimated 3 support? please open specific issues if anything is not working with reanimated 3.

**Comment by FN-FAL113** [comment]
> what do you mean by reanimated 3 support? please open specific issues if anything is not working with reanimated 3.

specifically drawers, it needs updating to the newer reanimated which is 3.0.0. It sends out an undefined prototype value inside drawer.tsx
I could have made a separate issue but that's what im experiencing, unsure about other possible scenarios

**Comment by SuperBigBang** [comment]
> what do you mean by reanimated 3 support? please open specific issues if anything is not working with reanimated 3.

+React Navigation 6 works correctly only with react-native-reanimated v1.13.4;
At now, React Navigation 6 with react-native-reanimated v3 very slow and bogged down;
react-native-reanimated v2.xx.x - not work with latest RN 0.70+, build crashes and other problems.

**Comment by satya164** [comment]
> specifically drawers, it needs updating to the newer reanimated which is 3.0.0. It sends out an undefined prototype value inside drawer.tsx

please open a new issue or update this issue with full detail and repro

**Comment by FN-FAL113** [comment]
> > specifically drawers, it needs updating to the newer reanimated which is 3.0.0. It sends out an undefined prototype value inside drawer.tsx
> 
> please open a new issue or update this issue with full detail and repro

I have updated this current issue

**Comment by FN-FAL113** [comment]
Snack does not support the new reanimated version, reproducing it is as simple as updating the reanimated package to 3.0.0 while having versions of drawer and other navigators.

**Comment by migueldaipre** [comment]
Same issue here, just using Reanimated 3 and React Navigation Drawer.
Warns are thrown in terminal.

**Comment by kacperkapusciak** [comment]
Hi @FN-FAL113 👋 
It seems like Reanimated [3.0.1](https://github.com/software-mansion/react-native-reanimated/releases/tag/3.0.1) fixes the problems you've encountered. Please update `react-native-reanimated` to the newest version.

There's nothing that we particularly had to do on the `@react-navigation/drawer` side to support Reanimated 3 as it uses the same API as Reanimated 2 without any breaking changes between versions.

Cheers

**Comment by FN-FAL113** [comment]
> Hi @FN-FAL113 👋 It seems like Reanimated [3.0.1](https://github.com/software-mansion/react-native-reanimated/releases/tag/3.0.1) fixes the problems you've encountered. Please update `react-native-reanimated` to the newest version.
> 
> There's nothing that we particularly had to do on the `@react-navigation/drawer` side to support Reanimated 3 as it uses the same API as Reanimated 2 without any breaking changes between versions.
> 
> Cheers

Cheers! Thank you for the follow up :D
