### ISSUE TITLE
navigation.reset makes iOS app crash without error

### ISSUE THREAD

**Issue by MSetnik** [react-navigation/react-navigation#11259]
### Current behavior

when using navigation.reset, iOS app crash without error on react native v0.71.3.
Android app works fine.

on RN v0.70.6, app on both platforms works fine

### Expected behavior

navigation.reset should not crash the app

### Reproduction

cannot provide repo

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |^6.1.6
| @react-navigation/bottom-tabs               |^6.5.7
| @react-navigation/native-stack         |^6.9.12
| react-native-safe-area-context         |^4.5.0
| react-native-screens                   |^3.20.0
| react-native                           |0.71.3
| expo                                   |^48.0.4

**Comment by curthipster** [comment]
I wonder if this is related to #11201

**Comment by MSetnik** [comment]
> I wonder if this is related to #11201

Yes it is! 
Unfortunatly, didnt find the fix for it yet :(

**Comment by fr0staman** [comment]
I confirm that too, only on iOS.

**Comment by curthipster** [comment]
@MSetnik or @fr0staman do either of you have a simple repro? I just started to create a snack, but they don't support Expo 48 yet, which is required for RN 0.71.x.

If not, I'll see if I can whip together a quick repo. This is blocking my RN upgrade.

**Comment by kartikbhalla12** [comment]
calling the event with setTimeout 0 seems to solve the issue for now

**Comment by MSetnik** [comment]
> calling the reset function with setTimeout 0 seems to solve the issue for now

Can confirm, this is current workaround

**Comment by curthipster** [comment]
> calling the reset function with setTimeout 0 seems to solve the issue for now

Unfortunately, that doesn't work for me. My issue is a little different, which is that the app crashes when calling `navigation.replace` while a modal is showing.

I can also work around by changing to

```
navigation.pop();
setTimeout(() => navigation.push(), EMPIRICALLY_OBSERVED_VALUE);
```

and `EMPIRICALLY_OBSERVED_VALUE` varies from 500 to 1000ms in my tests, which is clearly non confidence-inspiring or ideal.

**Comment by curthipster** [comment]
I have discovered that my issue is only happening with New Arch enabled. I logged #11270, as it's unclear if it's related to this issue at all.

**Comment by alexanderblackh** [comment]
This isn't happening on iOS for my project, however, it is happening on Samsung Galaxy devices only, and only when using Navigation.reset. I don't believe this is fixed and it should be reopened. The timeout workaround isn't working for us sadly.

**Comment by Manikanta-GEP** [comment]
Even timeout solution not working for me

**Comment by Leslie-Wong-H** [comment]
I use this workaround. 
```
navigation.popToTop();
setTimeout(() => {
   navigation.replace('Home');
}, 0);
```

**Comment by eidan66** [comment]
Hey!
It's still happened with the `setTimeout` solution.

Any other fix maybe?

**Comment by LucSilveira** [comment]
Hey, in my case, i soluted this using two steps

First, define de timging in animation close using the property `animationOutTiming={0}` in modal
ex : `<Modal {...rest} visible={visible} transparent={true} animationType='fade' animationOutTiming={0}>`

Second, i seted on button to close modal, applying this function
`async function handleClose(){
    await setShowModalAppointment(false)

    navigation.replace("Medico Prontuario")
  }`

That way, i can close modal and replace the stack to other screen (that's was my problem). obviously has a little problem about the visual animation, but was enough to resolve the problem

**Comment by sciranka** [comment]
The iOS app (simulator, iOS 17.4) crashed after I updated react-native from 0.73.7 to 0.74.0.
`setTimeout` didn't work for me, the app still crashed.
For now I reverted to RN update.

**Comment by rahuls225632** [comment]
Change "react-native-reanimated": "^3.8.1" to "react-native-reanimated": "^3.11.0"
it worked for me

**Comment by Srh07** [comment]
Also happening here when going back with navigation.goBack() or navigation.popToTop()

"@react-navigation/native": "^6.1.17",
"@react-navigation/native-stack": "^6.9.26",
"react-native-screens": "3.31.1",
"react-native-safe-area-context": "4.10.1"

**Comment by GabrielDokov** [comment]
@Srh07 try installing  **npm i react-native-reanimated** and **expo install react-native-reanimated"**, reload the app and it needs to be fixed, this worked for me

**Comment by Srh07** [comment]
@GabrielDokov thanks for the tip, however reanimated was already installed. I also tried reinstalling all of my node_modules and pods but unfortunately it's still not working.

**Comment by syedumerali101** [comment]
Import Modal from react native instead of importing it from react-native-modal.

**Comment by Srh07** [comment]
I got it working again with the following versions: 
"react-native": "0.72.13",
"react-native-reanimated": "3.8.1",
"@react-navigation/native": "^6.1.17",
"@react-navigation/native-stack": "^6.9.26",
"react-native-screens": "3.31.1",
"react-native-safe-area-context": "4.10.1"

The major thing I did was downgrading "react-native-reanimated" from 3.9.0 tot 3.8.1 and doing a "Clean build" within XCode. Only resetting cache when starting metro didn't seem enough.

note: I always use Modal from react-native, so this was not an issue.

**Comment by Libinvincent** [comment]
Use InteractionManager.runAfterInteractions before calling navigation.reset to prevent crashes.

Example: InteractionManager.runAfterInteractions(() => {
  navigation.reset({ index: 0, routes: [{ name: 'screenName' }] });
});

**Comment by dlu2002** [comment]
> Use InteractionManager.runAfterInteractions before calling navigation.reset to prevent crashes.
> 
> Example: InteractionManager.runAfterInteractions(() => { navigation.reset({ index: 0, routes: [{ name: 'screenName' }] }); });

i tried almost exactly that:

```javascript
InteractionManager.runAfterInteractions(() => {
    navigation.dispatch(
        CommonActions.reset({
            index: 0,
            routes: [{ name: 'MainTabs' }],
        })
    );
});
```

but this still crashes my app. any ideas?
