### ISSUE TITLE
Error: Text strings must be rendered within a <Text> component.

### ISSUE THREAD

**Issue by AliYar-Khan** [react-navigation/react-navigation#11267]
### Current behavior

I have an app where i am creating a bottom tab navigator.

`import {createBottomTabNavigator} from '@react-navigation/bottom-tabs';

const Tab = createBottomTabNavigator();

<Tab.Navigator
      initialRouteName="Stories"
      screenOptions={({route}) => ({
        headerShown: false,
        tabBarHideOnKeyboard: true,
        tabBarStyle: {
          backgroundColor: Colors.bottomMenu,
          height: Platform.OS === 'ios' ? 116 : 90,
          position: 'absolute',
          elevation: 0,
          shadowOffset: {
            width: 0,
            height: 0, // for iOS
          },
          borderTopWidth: 0,
        },
        tabBarLabel: ({focused}) => {
          let name = '';
          if (route.name === 'Statistics') {
            name = 'الملخّص';
          } else if (route.name === 'Favorites') {
            name = 'المفضّلة';
          } else if (route.name === 'Stories') {
            name = 'القصص';
          }
          return (
            <Text
              GulfSemiBold
              color={Colors.white}
              size={15}
              style={{
                fontWeight: focused ? 'bold' : 'normal',
                marginBottom: 20,
              }}>
                {name}
              </Text>
          );
        },
        >
    ....
    </Tab.Navigator>
`
it gives this error and gets crashed

` ERROR  Error: Text strings must be rendered within a <Text> component.

This error is located at:
    in RCTView (created by View)
    in View (created by TabBarIcon)
    in RCTView (created by View)
    in View (created by TabBarIcon)
    in TabBarIcon (created by BottomTabBarItem)
    in RCTView (created by View)
    in View (created by Pressable)
    in Pressable (created by Pressable)
    in BottomTabBarItem (created by BottomTabBar)
    in RCTView (created by View)
    in View (created by BottomTabBar)
    in RCTView (created by View)
    in View (created by AnimatedComponent)
    in AnimatedComponent
    in AnimatedComponentWrapper (created by BottomTabBar)
    in BottomTabBar (created by SafeAreaInsetsContext)
    in RCTView (created by View)
    in View (created by SafeAreaInsetsContext)
    in SafeAreaProviderCompat (created by BottomTabView)
    in BottomTabView (created by BottomTabNavigator)
    in PreventRemoveProvider (created by NavigationContent)
    in NavigationContent
    in Unknown (created by BottomTabNavigator)
    in BottomTabNavigator (created by App)
    in App (created by SceneView)
    in StaticContainer
    in EnsureSingleNavigator (created by SceneView)
    in SceneView (created by SceneView)
    in RCTView (created by View)
    in View (created by DebugContainer)
    in DebugContainer (created by MaybeNestedStack)
    in MaybeNestedStack (created by SceneView)
    in RCTView (created by View)
    in View (created by SceneView)
    in RNSScreen (created by AnimatedComponent)
    in AnimatedComponent
    in AnimatedComponentWrapper (created by InnerScreen)
    in Suspender (created by Freeze)
    in Suspense (created by Freeze)
    in Freeze (created by DelayedFreeze)
    in DelayedFreeze (created by InnerScreen)
    in InnerScreen (created by Screen)
    in Screen (created by SceneView)
    in SceneView (created by NativeStackViewInner)
    in Suspender (created by Freeze)
    in Suspense (created by Freeze)
    in Freeze (created by DelayedFreeze)
    in DelayedFreeze (created by ScreenStack)
    in RNSScreenStack (created by ScreenStack)
    in ScreenStack (created by NativeStackViewInner)
    in NativeStackViewInner (created by NativeStackView)
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by SafeAreaInsetsContext)
    in SafeAreaProviderCompat (created by NativeStackView)
    in NativeStackView (created by NativeStackNavigator)
    in PreventRemoveProvider (created by NavigationContent)
    in NavigationContent
    in Unknown (created by NativeStackNavigator)
    in NativeStackNavigator (created by MainNavigator)
    in MainNavigator (created by App)
    in EnsureSingleNavigator
    in BaseNavigationContainer
    in ThemeProvider
    in NavigationContainerInner (created by App)
    in App (created by App)
    in Provider (created by App)
    in RCTView (created by View)
    in View (created by App)
    in App
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in KidsFairyTales(RootComponent), js engine: hermes`

### Expected behavior

Should work without getting crashed.

### Reproduction

https://github.com/AliYar-Khan/kids-rn

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | ^6.1.6
| @react-navigation/bottom-tabs          | ^6.5.7
| @react-navigation/native-stack         | ^6.9.12
| react-native-safe-area-context         | ^4.5.0
| react-native-screens                   | ^3.20.0
| react-native-gesture-handler           | ^2.9.0
| react-native-reanimated                |  ^3.0.0
| react-native                           | 0.71.3
| expo                                   | >=48.0.0-0 <49.0.0
| node                                   | 18.12.1
| npm or yarn                            | npm

**Comment by faraz-ahmad-uft** [comment]
@AliYar-Khan - Your **Text**  is not closed correctly. That's why It is throwing error. It's not a navigation issue.

**Comment by AliYar-Khan** [comment]
@faraz-ahmad-uft While formatting I may have missed removed the closing tag. Its there
![Screenshot (56)](https://user-images.githubusercontent.com/37889962/223519450-82c9909e-be7e-4d18-af8c-38be33ced18a.png)

**Comment by BeeMargarida** [comment]
It's related to the `tabBarIcon`, it should return a react node and not directly the svg files. You should use something like [`react-native-svg`](https://github.com/software-mansion/react-native-svg/blob/main/USAGE.md#use-with-svg-files) for what you are trying to do there

**Comment by AliYar-Khan** [comment]
@BeeMargarida Can you please share an example what you are trying to say! Thanks for poiniting it out though

**Comment by BeeMargarida** [comment]
@AliYar-Khan You need to make the setup mentioned in the link - https://github.com/software-mansion/react-native-svg/blob/main/USAGE.md#use-with-svg-files - and then do something like
```
import StoriesOn from '../assets/images/iconSvg/StoriesOn.svg';
import StoriesOff from '../assets/images/iconSvg/StoriesOff.svg';

....

tarBarIcon: {
  ...
  let Icon: React.Node;
  if (route.name === 'Stories') {
    Icon = focused
      ? StoriesOn
      : StoriesOff
  ...
  return Icon;
}
```

Possibly there's some mistake here since I didn't test it, but it would be something like this
