### ISSUE TITLE
Tabs reset to first tab after launching native activity (Android)

### ISSUE THREAD

**Issue by RobinFarmer** [react-navigation/react-navigation#11268]
### Current behavior

Hi,

Currently I'm running into the following problem on Android with some specific devices, I'm using this package with `Tab.Navigator` with 2 tabs.
When I select the second tab I have a button which will launch an Activity. In the Activity I can select some photos and once I am done I close the activity with another button, once the activity is closed the tabs are reset and I end up on the first tab again. 

The strange thing is that this only happens on a few select devices, for example it does not work on a `Samsung A52S` or a `OnePlus 9`. I did not have any issues my `OnePlus Nord CE 2` or my `PocoPhone F1`.

Currently I'm thinking it could be related to Android 13 maybe, is this something someone else has run into?

In the repro I was not able to add the actual activity launching code because it's a private repo.

### Expected behavior

I would expect the behavior to be consistent on all devices, so if I open an activity from the second tab and close the activity that we are returned back to the second tab and not reset back to the original tab.

### Reproduction

https://snack.expo.dev/plQH8C9ge

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.1.6
| @react-navigation/bottom-tabs          | 6.5.7
| react-native-safe-area-context         | 4.2.4
| react-native-screens                   | 3.13.1
| react-native                           | 0.71.1
| expo                                   | 5.0.3
| node                                   | v19.6.0
| yarn                            | 1.22.10

**Comment by geeker-cmc** [comment]
I have the same problem. How did you resolve it

**Comment by RobinFarmer** [comment]
@geeker-cmc 
> I have the same problem. How did you resolve it

Sorry, I played around with it for like a week and gave up.
