### ISSUE TITLE
Tab.Navigator  Background color set transparent

### ISSUE THREAD

**Issue by windsleaver** [react-navigation/react-navigation#11260]
### Current behavior

Background color set transparent

Transparency is set, and the effect is available, but there is still a white background

      <Tab.Navigator
        initialRouteName="Home_router"
        screenOptions={{
          tabBarStyle: {
            position: 'absolute',
            borderTopLeftRadius: 12,
            borderTopRightRadius: 12,
            backgroundColor: 'transparent',
          },
        }}>

<img width="415" alt="image" src="https://user-images.githubusercontent.com/54970708/222684770-ecdb25d7-cab6-4577-aaee-037a99c53b29.png">

### Expected behavior

Background color set transparent

### Reproduction

[[provide repo](https://snack.expo.dev/@winds_leaver/f75860)](https://snack.expo.dev/@winds_leaver/f75860)

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

    "@react-navigation/bottom-tabs": "^6.3.1",
    "@react-navigation/drawer": "^6.4.1",
    "@react-navigation/material-top-tabs": "^6.2.1",
    "@react-navigation/native": "^6.0.10",
    "@react-navigation/native-stack": "^6.6.1",
    "@react-navigation/stack": "^6.2.1",

**Comment by windsleaver** [comment]
> 嘿@windsleaver！感谢您打开问题。该问题似乎不包含指向重现的链接。
> 
> **引起对问题的关注的最佳方式是为开发人员提供一种简单的方法来重现问题。**
> 
> 您可以使用以下任一方式提供重现：
> 
> * [世博小吃](https://snack.expo.io)
> * [打字游乐场](https://www.typescriptlang.org/play)
> * GitHub repo 在你的用户名下
> 
> 小吃链接是首选，因为它是创建和共享复制品的最简单方法。如果无法使用 snack 创建 repro，则使用您的用户名链接到 GitHub 存储库是一个不错的选择。**不要链接到分支或特定文件等，**因为它不会被检测到。
> 
> 通过缩小重现问题所需的最少代码量，尽量保持重现尽可能小。**不要链接到您的整个项目或包含与问题无关的代码的项目。**有关详细信息，请参阅[“如何创建最小的、可重现的示例”](https://stackoverflow.com/help/minimal-reproducible-example)。
> 
> 您可以编辑原始问题以包含指向重现的链接，或将其保留为评论。如果您不提供重现，**该问题将在一段时间后自动关闭。**

https://snack.expo.dev/@winds_leaver/f75860

**Comment by windsleaver** [comment]
> Hey @windsleaver! Thanks for opening the issue. It seems that the issue doesn't contain a link to a repro.
> 
> **The best way to get attention to your issue is to provide an easy way for a developer to reproduce the issue.**
> 
> You can provide a repro using any of the following:
> 
> * [Expo Snack](https://snack.expo.io)
> * [TypeScript Playground](https://www.typescriptlang.org/play)
> * GitHub repo under your username
> 
> A snack link is preferred since it's the easiest way to both create and share a repro. If it's not possible to create a repro using a snack, link to a GitHub repo under your username is a good alternative. **Don't link to a branch or specific file etc.** as it won't be detected.
> 
> Try to keep the repro as small as possible by narrowing down the minimal amount of code needed to reproduce the issue. **Don't link to your entire project or a project containing code unrelated to the issue.** See ["How to create a Minimal, Reproducible Example"](https://stackoverflow.com/help/minimal-reproducible-example) for more information.
> 
> You can edit your original issue to include a link to the repro, or leave it as a comment. **The issue will be closed automatically after a while** if you don't provide a repro.

https://snack.expo.dev/@winds_leaver/f75860

**Comment by BeeMargarida** [comment]
Hi, this can be fixed if you pass `elevation: 0` in the `tabBarStyle`. Elevation > 0 (default style of the bottom tab) and transparent background color has some quirks in android

**Comment by windsleaver** [comment]
> Hi, this can be fixed if you pass `elevation: 0` in the `tabBarStyle`. Elevation > 0 (default style of the bottom tab) and transparent background color has some quirks in android

It worked, thank you very much
