### ISSUE TITLE
initialRouteName being ignored

### ISSUE THREAD

**Issue by maxmilianf** [react-navigation/react-navigation#11262]
### Current behavior

initialRouteName is being ignored and react drawer instead displays the first child in order as they are placed inside it. 
I expect the drawer to render the HOME component. Instead, it takes an OVERVIEW because it is first placed inside the Drawer.
Code: 
` function DrawerNavigator() {
  const { authenticated } = useAuth();
  const { t } = useTranslation();

  if (!authenticated) {
    return (
      <Drawer.Navigator
        screenOptions={{
          headerShown: false,
        }}
      >
        <Drawer.Screen name={Routes.LOGIN} component={LoginScreen} />
      </Drawer.Navigator>
    );
  }

  return (
    <Drawer.Navigator
      initialRouteName={Routes.HOME}
      screenOptions={{
        headerShown: false,
      }}
      drawerContent={(props) => <CustomDrawerContent {...props} />}
    >
      <Drawer.Screen
        name={Routes.OVERVIEW}
        component={OverviewNavigator}
        options={{ drawerLabel: t("overview") }}
      />
      <Drawer.Screen
        name={Routes.HOME}
        component={HomeNavigator}
        options={{ drawerLabel: t("home") }}
      />
      <Drawer.Screen
        name={Routes.PROFILE}
        component={UserProfileNavigator}
        options={{ drawerLabel: t("settings") }}
      />
    </Drawer.Navigator>
  );
} `

### Expected behavior

The component that initialRouteName belongs to is displayed not the first one in the drawer. 

### Reproduction

Cant reproduce this on Snack. 

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 4.2.2
| @react-navigation/bottom-tabs          | 6.0.9
| @react-navigation/drawer               | 6.6.2
| @react-navigation/material-top-tabs    | 
| @react-navigation/stack                | 6.0.11
| @react-navigation/native-stack         |
| react-native-safe-area-context         | 4.3.1
| react-native-screens                   | 3.15.0
| react-native-gesture-handler           | 2.5.0
| react-native-reanimated                | 2.9.1
| react-native-tab-view                  | 3.0.1
| react-native-pager-view                | 5.4.24
| react-native                           | 0.69.6
| expo                                   | 46.0.0
| node                                   | >=14  <15
| npm or yarn                            | 6.x

**Comment by Roman-ZN** [comment]
This bug is still actual
