### ISSUE TITLE
a screen made with createStackNavigator is not responding to touching when goBack() to it.

### ISSUE THREAD

**Issue by kamalmalaklife** [react-navigation/react-navigation#11277]
### Current behavior

Created a stackNavigator using
`import { createStackNavigator } from "@react-navigation/stack";

  const FoodStack = createStackNavigator();
`

I success  navigate to the screen
`<FoodStack.Screen
        name="RecipeDetails"
        component={RecipeDetailsScreen}
      />
`
with both `navigation.push` and `navigation.navigate'

but when I navigation.goBack() from it, it views the previous screen, but is not responding to any touches

when I create the navigator using createNativeStackNavigator from /native-stack, it works fine.

I imported `import "react-native-gesture-handler"` at the head of App.js

 

### Expected behavior

Scrolling and touching buttons on screen I go back to, to work normally.

### Reproduction

cant

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |  6.0.12
| @react-navigation/bottom-tabs          | 6.3.3
| @react-navigation/drawer               | 6.4.4
| @react-navigation/stack                |  6.2.3
| @react-navigation/native-stack         | 6.9.10
| react-native-safe-area-context         |  4.4.1
| react-native-screens                   | 3.8.12
| react-native-gesture-handler           | 2.9.0
| react-native                           | 0.70.5
| expo                                   | 47.0.12
| node                                   | 16.14.0
| npm or yarn                            | yarn

**Comment by kamalmalaklife** [comment]
Yes, I upgraded to the latest, the problem still exists.

**Comment by fr0staman** [comment]
I can confirm this problem.
I just replace stack with native-stack and it works on iOS.

**Comment by kamalmalaklife** [comment]
> I can confirm this problem. I just replace stack with native-stack and it works on iOS.

Are you using Expo aswell ?

**Comment by emzet93** [comment]
I can also confirm that issue - in my case it happens after dropping screen from `createStackNavigator` stack. Doesn't matter if it's dropped after `goBack` call or after navigating to other screen. Also it doesn't happen always, seems pretty random.

The weird thing is that I was using all this the same for months and it was working ok. Here are my versions from `package.json`:
```
"@react-navigation/drawer": "^6.4.3",
"@react-navigation/material-top-tabs": "^6.6.1",
"@react-navigation/native": "^6.0.11",
"@react-navigation/native-stack": "^6.5.0",
"@react-navigation/stack": "^6.2.1",
```
I tried to remove `^` to bring back older versions but the issue still exists, which makes me think that the source of the problem is not in `@react-navigation` itself, but maybe in one of its dependencies?

**Comment by Arhaler** [comment]
Some problem with any versions

**Comment by kamalmalaklife** [comment]
I found a work around
add detachInactiveScreens={false} to Stack 

`    <Stack.Navigator
      screenOptions={{
        headerShown: false,
      }}
      detachInactiveScreens={false}
    >
`
