### ISSUE TITLE
Failed to print error: Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by valery-lavrik** [react-navigation/react-navigation#11284]
### Current behavior

```
import { createDrawerNavigator } from '@react-navigation/drawer';

const Drawer = createDrawerNavigator();
```

I am getting an error after updating react-native from version 0.70.5 to 0.71.4. Previously (before the update) this error was not.

And this happens when debug mode is enabled

Any ideas how to solve this?

### Expected behavior

The app must not crash.

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

    "@react-navigation/drawer": "^6.6.2",
    "@react-navigation/native": "^6.1.6",
    "@react-navigation/native-stack": "^6.9.12",
    "react": "18.2.0",
    "react-native": "0.71.4",

**Comment by valery-lavrik** [comment]
This issue is discussed at
https://stackoverflow.com/questions/74859163/typeerror-cannot-read-property-createdrawernavigator-of-undefined/75753538#75753538
but no solution yet

**Comment by valery-lavrik** [comment]
Screenshot of the error

![image](https://user-images.githubusercontent.com/8047999/225558444-331ab763-37b6-40b9-90f7-e23d5597bee0.png)

**Comment by parimal20** [comment]
When I added @react-navigation/drawer - 6.6.2 version it showed the same error when I debug the app and when I removed @react-navigation/drawer error was not showing when I debug the app, So does the downgrade of drawer work without an error in debug?

**Comment by valery-lavrik** [comment]
I think the react-navigation team is currently working on version 7 and will no longer fix bugs in 6

**Comment by parimal20** [comment]
Till then have you found any alternative of debugging?

**Comment by valery-lavrik** [comment]
@parimal20   No, I couldn't find anything.  
Therefore, I decided to stay on version 0.70.5 RN for now

**Comment by parimal20** [comment]
@valery-lavrik I tried debugging on the Flipper debugging tool and it works fine without any error because Flipper is using "Direct debugging" not "Remote Debugging"(like Chrome, etc. browsers).

**Comment by valery-lavrik** [comment]
@parimal20   I didn't like Flipper, it's kind of strange, a million buttons, windows, everything jumps, duplicates each other, crashes, restarts....
