### ISSUE TITLE
TypeError: property is not configurable

### ISSUE THREAD

**Issue by minemos** [react-navigation/react-navigation#11289]
### Current behavior

<img width="708" alt="스크린샷 2023-03-18 오전 7 00 49" src="https://user-images.githubusercontent.com/24834933/226060701-49e1f388-5197-48b8-9872-ae556b5511ac.png">

TypeError: property is not configurable

Only render with no errors after hot-reload

### Expected behavior

Render with no errors

### Reproduction

https://github.com/differz-korea/welinkor-rn

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.1.6
| @react-navigation/bottom-tabs          | 6.5.7
| @react-navigation/native-stack         | 6.9.12
| react-native-safe-area-context         | 4.5.0
| react-native-gesture-handler           | 2.9.0
| react-native-reanimated                | 3.0.2
| react-native                           | 0.71.4
| node                                   | 16
| npm or yarn                            | yarn

**Comment by satya164** [comment]
All of the comments I have seen with this error mention reanimated. If this only happens when you have reanimated installed, then please open an issue in reanimated repo instead.

**Comment by miguelangarano** [comment]
In my case, this was caused because of an error in the component sent in the `tabBarIcon` property.

**Comment by zamih23** [comment]
Try to downgrade `react-native-reanimated` to 2.14.4, then run `npm start -- --reset-cache`.  It helped me.

**Comment by NedStar72** [comment]
Check https://github.com/software-mansion/react-native-reanimated/pull/4252

**Comment by anuragipankaj** [comment]
facing same issue

**Comment by minemos** [comment]
Go to this file

`node_modules/react-native-reanimated/src/reanimated2/initializers.ts`

And modify 

```tsx
const capturableConsole = console;
```

to

```tsx
const capturableConsole = { ...console };
```

will fix this issue

**Comment by ChrisNg02655332** [comment]
> 

it worked. Thanks

**Comment by ChrisNg02655332** [comment]
> Go to this file
> 
> `node_modules/react-native-reanimated/src/reanimated2/initializers.ts`
> 
> And modify
> 
> ```tsx
> const capturableConsole = console;
> ```
> 
> to
> 
> ```tsx
> const capturableConsole = { ...console };
> ```
> 
> will fix this issue

it worked. Thanks

**Comment by Dhananjay-JSR** [comment]
Closing this as it seems to resolved

**Comment by muzhaqi16** [comment]
I just started having the same issue out of nowhere. Nothing works so far?!

**Comment by Dhananjay-JSR** [comment]
https://github.com/software-mansion/react-native-reanimated/pull/4252, as mentioned by Core Members This, seems to be an issue from the RN-reanimated package, there is nothing react-navigation can do to fix the problem, Either Update your reanimated-version or patch your existing version

**Comment by azadsarxanli** [comment]
in my case, this is because of the custom Tab bar, after commenting that, everything worked normally.

**Comment by abhishek-appsdeployer** [comment]
> ```tsx
> const capturableConsole = { ...console };
> ```

Also work for me ,Very very thank you

**Comment by ragOP** [comment]
> ```tsx
> const capturableConsole = { ...console };
> ```

wroked for me as well ty

**Comment by muaaz9329** [comment]
> Go to this file
> 
> `node_modules/react-native-reanimated/src/reanimated2/initializers.ts`
> 
> And modify
> 
> ```tsx
> const capturableConsole = console;
> ```
> 
> to
> 
> ```tsx
> const capturableConsole = { ...console };
> ```
> 
> will fix this issue

it worked bro , Thanks alot

**Comment by muaaz9329** [comment]
> Go to this file
> 
> `node_modules/react-native-reanimated/src/reanimated2/initializers.ts`
> 
> And modify
> 
> ```tsx
> const capturableConsole = console;
> ```
> 
> to
> 
> ```tsx
> const capturableConsole = { ...console };
> ```
> 
> will fix this issue

Thank brother

**Comment by philodi-dev** [comment]
> Go to this file
> 
> `node_modules/react-native-reanimated/src/reanimated2/initializers.ts`
> 
> And modify
> 
> ```tsx
> const capturableConsole = console;
> ```
> 
> to
> 
> ```tsx
> const capturableConsole = { ...console };
> ```
> 
> will fix this issue

It worked for me as well but this is not the best way it should be.
Anyway, thank you.

**Comment by AstrOOnauta** [comment]
> Go to this file
> 
> `node_modules/react-native-reanimated/src/reanimated2/initializers.ts`
> 
> And modify
> 
> ```tsx
> const capturableConsole = console;
> ```
> 
> to
> 
> ```tsx
> const capturableConsole = { ...console };
> ```
> 
> will fix this issue

Thanks! This worked like a charm!!

**Comment by izuutech** [comment]
For me, I was returning an array and I forgot to add the **key** attribute to each element in the map function. I fixed my issue by adding the key attribute. The above option also worked but using the key solved it without having to touch my node modules

**Comment by joaolvcas** [comment]
> Go to this file
> 
> `node_modules/react-native-reanimated/src/reanimated2/initializers.ts`
> 
> And modify
> 
> ```tsx
> const capturableConsole = console;
> ```
> 
> to
> 
> ```tsx
> const capturableConsole = { ...console };
> ```
> 
> will fix this issue

this does not seem to be a good way to solve this issue.

**Comment by ZECTBynmo** [comment]
I had this issue, and the change to react-native-reanimated did resolve the issue. However I was unhappy with that fix, so I kept looking and eventually found that I was also missing a key on elements within an array, like @izuutech. Adding a key fixed the issue even after removing the change to reanimated.

I don't understand why the two changes are related, but the missing key is a better fix, because it's not deep in node_modules, etc.

**Comment by mMarcos208** [comment]
Upgrade of "react-native-reanimated": "^3.0.0" to "react-native-reanimated": "^3.3.0".

**Comment by mateusdegobi** [comment]
> Atualização de `"react-native-reanimated": "^3.0.0"`para`"react-native-reanimated": "^3.3.0".`

it worked for me

**Comment by Arsl4** [comment]
> Go to this file
> 
> `node_modules/react-native-reanimated/src/reanimated2/initializers.ts`
> 
> And modify
> 
> ```tsx
> const capturableConsole = console;
> ```
> 
> to
> 
> ```tsx
> const capturableConsole = { ...console };
> ```
> 
> will fix this issue

it worked for me.

**Comment by kundanthe** [comment]
> Try to downgrade `react-native-reanimated` to `2.14.4`, then run `npm start -- --reset-cache`. It helped me.

Its working for me.

**Comment by Abdullah-Sajjad026** [comment]
In my case, I was accepting a prop named **style** and was adding it to the array of styles of component without giving it initial value of **{}**. So, I updated the prop's initial value and it got fixed.

In destructuring of props: 
`{
        style = {},
        data
}
`

Then, while passing prop:
`
<View
            style={[
              {
                // Going to put some default styles here
              },
              **style**,
            ]}
          ></View>
`

Another method can be like this:
`
 <View
            style={[
              {
                // Going to put some default styles here
              },
              style || {} //This method does not require changing anything in props destructuring.
            ]}
          ></View>
`


_**Hope it helps someone. Thanks**_
