### ISSUE TITLE
Cannot disable animation when tabBarHideOnKeyboard is true

### ISSUE THREAD

**Issue by nithronium** [react-navigation/react-navigation#11286]
### Current behavior

I have a bottom tab navigator initiated like this;

```
   <Tabs.Navigator
      screenOptions={{
        tabBarStyle: {
          height: 70,
          justifyContent: 'center',
          alignItems: 'center',
          paddingBottom: 12,
        },
        tabBarHideOnKeyboard: true,
      }}>
```
When keyboard is activated the bottom bar disappears by sliding down and when keyboard is sent down - it re-appears by sliding up. I want to disable the sliding animation but currently there is no way to do it.

I'm using the latest version.

### Expected behavior

I wish to have a parameter like `slidingAnimationDisabled` so once it's set to true, appearing keyboard just gets rendered without sliding up.

### Reproduction

https://snack.expo.dev/7LrRN3X67

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [X] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |  ^6.1.4
| @react-navigation/bottom-tabs          |  ^6.5.5
| @react-navigation/drawer               |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                |
| @react-navigation/native-stack         |  ^6.9.10
| react-native-safe-area-context         |
| react-native-screens                   |
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           |
| expo                                   |
| node                                   |
| npm or yarn                            |

**Comment by nithronium** [comment]
The issue exists on the recent versions too.

**Comment by Rhym** [comment]
If anyone is trying to do this in 2025 you can use the following:

```ts
screenOptions={{
  tabBarHideOnKeyboard: true,
  tabBarVisibilityAnimationConfig: {
    show: {
      animation: 'timing',
      config: {
        duration: 0,
      },
    },
    hide: {
      animation: 'timing',
      config: {
        duration: 0,
      },
    },
  },
}}
```

**Comment by roman01la** [comment]
Can confirm the issue is still present. The fix above only removes the animation, but the bar tab is still visible on Android for a brief moment.
