### ISSUE TITLE
Previous stack screens are persisting when switching to a different stack

### ISSUE THREAD

**Issue by varunsaini2112** [react-navigation/react-navigation#11283]
### Current behavior

I'm using a boolean state to switch between two stacks. Stack A and Stack B

when switching from Stack A to Stack B, all the screens currently mounted on Stack A and also present in Stack B with the same name are persisting.

### Expected behavior

Previous stack screens should all be removed and only the default screen of the Stack B should be mounted.

Is this the required behaviour or it should be changed?

if this behaviour is as expected, is there a way to overcome this problem?

### Reproduction

https://snack.expo.dev/1BQ0EnZBw

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |6.1.4
| @react-navigation/stack                |6.3.14
| react-native-safe-area-context         |4.5.0
| react-native-screens                   |3.20.0
| react-native-gesture-handler           |2.9.0
| react-native                           |0.71.3
| node                                   |14.19.3
| npm or yarn                            |6.14.17

**Comment by varunsaini2112** [comment]
Yes, still getting the same issue

**Comment by satya164** [comment]
You are misunderstanding how React works. It won't make them different stack navigators if you put them in different render functions. They both are still the same stack navigator and so will preserve state. You can do this with any React component.

e.g. `someCondition ? <MyComp value={10} /> : <MyComp value={2} />` means the same as `<MyComp value={someCondition ? 10 : 2} />`

They'll only be different navigators if you:

- Have them inside 2 different components (not render functions)
- Have different `key` props
- Have a different parent component
