### ISSUE TITLE
Overflow of TabBar

### ISSUE THREAD

**Issue by sumsalabim** [react-navigation/react-navigation#11296]
### Current behavior

Currently my Tab bar looks like this:
<img width="418" alt="image" src="https://user-images.githubusercontent.com/37812273/226610028-1ed0b3c2-9f0f-4690-b82f-e811a9c483cd.png">
As you can see, I've added Avatar to the first tab, but It's hidden under overflow style
Is there any chance I can get rid of it?
I've tried various different methods of inline styling the TabBar but nothing seems to be working

### Expected behavior

I would like to get rid of overflow X and be able to display the avatar between tabbar and section above

### Reproduction

https://snack.expo.dev/khosM5lxb

### Platform

- [X] Android
- [X] iOS

### Packages

- [X] react-native-tab-view

**Comment by okwasniewski** [comment]
Hello @sumsalabim,

Can you provide a valid expo snack? This one doesn't have tab-view in package.json and doesn't work.
