### ISSUE TITLE
React navigation v6 - Navigation is not working after app have been killed and re-opened via deep link

### ISSUE THREAD

**Issue by AndonMitev** [react-navigation/react-navigation#11292]
### Current behavior

When i open a deep link, app launch successfully to the screen that is supposed to handle deeplink, however in this screen i have a navigation to other screen and this navigation is not triggered. If app is just minimized everything is working as expected

### Expected behavior

To be able to navigate to another screen when app is opened via deeplink

### Reproduction

-

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

    "@react-navigation/bottom-tabs": "6.4.0",
    "@react-navigation/devtools": "6.0.18",
    "@react-navigation/native": "6.0.13",
    "@react-navigation/native-stack": "6.9.0",
    "@react-navigation/stack": "6.2.3",

**Comment by plgrazon** [comment]
@AndonMitev Hi Andon, sorry for reopening this. Have you found a solution for this?
