### ISSUE TITLE
Missing core listeners types in react native stack navigator

### ISSUE THREAD

**Issue by sacha-c** [react-navigation/react-navigation#11293]
### Current behavior

When implementing listeners in a screen in a NativeStackNavigator, typescript complains if I use `e.preventDefault()` on the `beforeRemove` listener. However functionally speaking, it works.

For example, this code:
```ts
const Stack = createNativeStackNavigator<RootStackParamsList>()

const RootStack = () => {
  return (
    <Stack.Navigator>
      <Stack.Screen
        name="HomeScreen"
        component={HomeScreen}
        listeners={{ beforeRemove: e => e.preventDefault() }}
      />
    </Stack.Navigator>
  )
}
```

Gives this typescript error:
```
error TS2339: Property 'preventDefault' does not exist on type 'EventArg<"beforeRemove", unknown, unknown>'.

16         listeners={{ beforeRemove: e => e.preventDefault() }}
```

The main issue I see is that _beforeRemove_ is defined as `EventArg<"beforeRemove", unknown, unknown>`, although it should be defined as `EventArg<"beforeRemove", true, something else?>`

Looking into [how the types are defined](https://github.com/react-navigation/react-navigation/blob/main/packages/core/src/types.tsx#L561-L566), I see that _ScreenListeners_ takes an _EventMap_ that is supposed to extend the keys of possible events _EventMapCore_ (which beforeRemove is from). So in my case, it's passing _NativeStackNavigationEventMap_

But then, if we look at the [definition of EventListenerCallback](https://github.com/react-navigation/react-navigation/blob/main/packages/core/src/types.tsx#L95), it only looks at the _passed_ _EventMap_ to get the right values for _canPreventDefault_ and _data_. So it only looks at the _EventMap_ that is passed, and is missing the _EventMapCore_ values which have the right definition for _beforeRemove_

I _think_ (but really am not sure, I've only looked so far into this), that the `EventMapCore` values should also be included in the `EventListenerCallback` type, would that make sense?

### Expected behavior

When defining core listeners in the Screen props of a NativeStackNavigator, typescript is happy

### Reproduction

https://snack.expo.dev/@frenchie/look-at-the-codesandbox-repro-below-for-typescript-example

https://codesandbox.io/s/dazzling-chatterjee-0pef14?file=/src/App.tsx

snapshot from the codesandbox repro above ^
<img width="941" alt="image" src="https://user-images.githubusercontent.com/3247529/226398154-193d0afc-ca0f-451c-8544-56457944b377.png">

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [x] I've removed the packages that I don't use (or are irrelevant)

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.0.10
| @react-navigation/native-stack         | 6.5.0
| @types/react | 17.0.43
| @types/react-native | 0.67.3
| react-native                           | 0.67.5
| node                                   | v14.18.3
| yarn                            | 1.22.18

**Comment by JshGrn** [comment]
Did you find a resolution?

**Comment by JosefBud** [comment]
My team is running into a similar issue with these types, and wondering if there has been any resolution?

**Comment by krmao** [comment]
for now I set the ***e*** type to any

```
this.beforeRemoveListener = (e: any) => {  
};
```
