### ISSUE TITLE
Modal opening as screen in createNativeStackNavigation, but works in createStackNavigation

### ISSUE THREAD

**Issue by ajanjairam** [react-navigation/react-navigation#11294]
### Current behavior

https://snack.expo.dev/@ajanjairam/screen-options-with-nested-navigators-|-react-navigation

### Expected behavior

https://snack.expo.io/?platform=android&name=Screen%20options%20with%20nested%20navigators%20%7C%20React%20Navigation&dependencies=%40expo%2Fvector-icons%40*%2C%40react-native-community%2Fmasked-view%40*%2Creact-native-gesture-handler%40*%2Creact-native-pager-view%40*%2Creact-native-paper%40%5E4.7.2%2Creact-native-reanimated%40*%2Creact-native-safe-area-context%40*%2Creact-native-screens%40*%2Creact-native-tab-view%40%5E3.0.0%2C%40react-navigation%2Fbottom-tabs%406.3.1%2C%40react-navigation%2Fdrawer%406.4.1%2C%40react-navigation%2Felements%401.3.3%2C%40react-navigation%2Fmaterial-bottom-tabs%406.2.1%2C%40react-navigation%2Fmaterial-top-tabs%406.2.1%2C%40react-navigation%2Fnative-stack%406.6.1%2C%40react-navigation%2Fnative%406.0.10%2C%40react-navigation%2Fstack%406.2.1&hideQueryParams=true&sourceUrl=https%3A%2F%2Freactnavigation.org%2Fexamples%2F6.x%2Fmodal.js

### Reproduction

https://snack.expo.dev/@ajanjairam/screen-options-with-nested-navigators-|-react-navigation

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [X] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.1.6 |
| @react-navigation/native-stack         | 6.9.12 |
| react-native-safe-area-context         | 4.5.0 |
| react-native-screens                   | 3.20.0 |
| react-native                           | 0.71.3 |
| expo                                   | 48.0.6 |
| node                                   |
| yarn                            |

**Comment by Dhananjay-JSR** [comment]
https://reactnavigation.org/docs/stack-navigator/#presentation This is a feature not a bug as Native Stack leverages native APIs without any Animation Built whereas the stack is more customizable
