### ISSUE TITLE
Cannot call hooks in subscribe method to deep link

### ISSUE THREAD

**Issue by SupriyaPKalghatgi** [react-navigation/react-navigation#11300]
### Current behavior

Cannot autoSignIn user with incoming deep link (no push notification)
Currently the incoming deep link url will have a token, fetch it and call hook into `subscribe` fails

```
const linking: LinkingOptions<RootRoutes> = {
  prefixes: [Linking.createURL('/'), 'myapp://'],
  config: {
    initialRouteName: 'Root',
    screens: {
      Root: 'Root',
      NotFound: '*',
    },
  },

  getInitialURL: async () => {
    return await Linking.getInitialURL()
  },

  subscribe: (listener) => {
    const onReceiveURL = async ({ url }: any) => {
      // 1. Fetch token from incoming URL and storing to Async storage
      // 2. Call `useContext` hook which makes an API call
      return listener(url)
    }
    const subscription = Linking.addEventListener('url', onReceiveURL)
    return () => subscription.remove()
  },
}

export default linking
```

### Expected behavior

Before the incoming deep link navigates to desired screen, successfully call hook

### Reproduction

https://snack.expo.dev/

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | ^6.0.14
| @react-navigation/bottom-tabs          | ^6.0.9
| @react-navigation/drawer               | ^6.1.8
| @react-navigation/stack                | ^6.0.11
| @react-navigation/native-stack         | ^6.2.5
| react-native-safe-area-context         | 4.4.1
| react-native-screens                   | ~3.18.2
| react-native-gesture-handler           | ~2.8.0
| react-native-reanimated                | ~2.12.0
| react-native-tab-view                  | ^2.16.0
| react-native-pager-view                | 6.0.1
| react-native                           | 0.70.5
| expo                                   | ~47.0.3
| node                                   | 16.14.0
| npm or yarn                            | npm 8.3.1 / yarn 1.22.19

**Comment by SupriyaPKalghatgi** [comment]
Yes the issue exists with latest versions

**Comment by SupriyaPKalghatgi** [comment]
@satya164 Any help on this?

**Comment by satya164** [comment]
Hooks can only be called at top level of components and can't be called inside such functions. Please use the proper channels for asking questions.

**Comment by SupriyaPKalghatgi** [comment]
@satya164 Is there any way to access incoming deep link URL before 
```
    <NavigationContainer
      linking={LinkingConfiguration}
    >
    ```
