### ISSUE TITLE
`type does not satisfy the constraint 'never'` when typing `useNavigation`

### ISSUE THREAD

**Issue by jrafaaael** [react-navigation/react-navigation#11302]
### Current behavior

I'm trying to type `useNavigation` hook but I'm getting the error `Type 'NativeStackNavigationProp<RootStackParamList, "PurchaseOrder", undefined>' does not satisfy the constraint 'never'.` (`PurchaseOrder` is the screen that contains `OrderDetails` component):
```tsx
type Props = NativeStackScreenProps<RootStackParamList, "PurchaseOrder">;
type ProfileScreenNavigationProp = Props["navigation"];

export function OrderDetails() {
  const onSubmit = () => navigation.navigate<ProfileScreenNavigationProp>("");
  return (...)
}
```

### Expected behavior

correct type checking (? I think I'm doing as expected (see https://reactnavigation.org/docs/typescript/#annotating-usenavigation)

### Reproduction

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgVwM4FMByBDAbsAc2xmAgDs4BfOAMyghDgCIABKdbAYxgFoy9CxUmQD0-ErnRMA3AChQkWIjg4J6AMowuAa3Wd26MgAV6YVFVr1Grdl1798REuTFDJPVFs7aZs2egAPRXgYAE8wdDgAJQgIGE0dI2wobBAAGWBPOABeRFk4OCNkKE4AC2wMAHkoABN0KAAuFDI6mmAydBq5AqTQkEMYJuQW9DaOrtlKOVkwiMLTc1zVYEkE7z0DYwWAHhi4te0klPTMmAAaZiKS8qra+qYAPjlZyJMINoAbDX10QxxHITkN5gHLzCBmADaTAcgmcZCYAF1poFgrRhtxhHBqnUoAARdBaYAfVAACgAlHkCgVOOQsjCnJjcmgsAIGeRyd0qTSyFlyOpkAAjEDAeC5ck5B5wemAsgAOmlMHQ2zen2+m3+sOEwIeJKYTDJnIK7BgxQoJPyVMt2wAasB0AB3B7bES2h0PC0FMmTIA

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native       | 6.1.6 |
| @react-navigation/native-stack |6.9.12|
| react-native-safe-area-context   |4.5.0|
| react-native-screens                   |3.20.0|
| react-native-gesture-handler           |2.9.0|
| react-native-reanimated                |2.14.4|
| react-native                           |0.71.3|
| expo                                   |48.0.5|
| node                                   |18.14.2|
| npm or yarn                            |1.22.19|

**Comment by jrafaaael** [comment]
Updated. I'm not usign `@react-navigation/stack`. Sorry :smile:

**Comment by satya164** [comment]
`navigation.navigate` doesn't take a generic. You need to specify the generic in `useNavigation`. However it's recommended to specify the type once in global types without annotating every time.
