### ISSUE TITLE
There is a significant delay in events when switching tab screens

### ISSUE THREAD

**Issue by sgshy1995** [react-navigation/react-navigation#11307]
### Current behavior

When using events in tab screen, such as `setTimeout` and `setInterval` and `addListener` and so on. When I switch to another tab screen and switch back, repeat this many times, I find that the event cannot be executed immediately, it looks like there's some kind of blockage. 

Even if I use `useFocusEffect` to clean it up, it still doesn't seem to work right.

Such as using `useFocusEffect`:

```ts
const [scrollTop, setScrollTop] = useState(0);
let interval:ReturnType<typeof setInterval> | undefined;

useFocusEffect(
    useCallback(() => {
      interval && clearInterval(interval)
      interval = setInterval(() => {
        console.log("check interval")
      }, 5)
      console.log('show');

      return () => {
        interval && clearInterval(interval)
        console.log('hide');
      };
    }, []),
);
```

Such as not using `useFocusEffect`:
```ts
const [scrollTop, setScrollTop] = useState(0);

const onScroll = (event: NativeSyntheticEvent<NativeScrollEvent>) => {
    console.log("onScroll start")
    setScrollTop(event.nativeEvent.contentOffset.y)
}

return (
    <Animated.ScrollView showsVerticalScrollIndicator={false} scrollEventThrottle={16}
                  onScroll={Animated.event(
                    [{ nativeEvent: { contentOffset: { y: scrollOffsetY}}}],
                    {
                      useNativeDriver: false,
                      listener: onScroll
                    }
    )}>
        ...
    </Animated.ScrollView>
)
```

When I use the two cases above, after many times swtich tabs, here are no console log at the terminal until a few seconds later.

How can I resolve it?

### Expected behavior

When swtich tabs, the events can take effect immediately.

Using `useFocusEffect` can achieve the desired effect.

### Reproduction

cant

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [X] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.1.6
| @react-navigation/bottom-tabs          | 6.3.1
| @react-navigation/drawer               |  6.6.2
| @react-navigation/material-top-tabs    | -
| @react-navigation/stack                | 6.3.16
| @react-navigation/native-stack         | 6.9.12
| react-native-safe-area-context         | 4.5.0
| react-native-screens                   | 3.20.0
| react-native-gesture-handler           | 2.9.0
| react-native-reanimated                | 3.0.2
| react-native-tab-view                  | 3.3.4
| react-native-pager-view                | 6.1.2
| react-native                           | 0.68.2
| expo                                   | -
| node                                   | 16.18.1
| npm or yarn                            | 1.22.17

**Comment by aik117** [comment]
Facing same issue as well

**Comment by js2585** [comment]
Facing this issue as well. How are you supposed to implement polling with this bug?

**Comment by js2585** [comment]
I noticed that if a screen A calls useEffect, then going from [screen A -> any other screen -> screen A] will clear all intervals running on the app. Is this a known issue with expo go? Does it go away in production?
