### ISSUE TITLE
Don't use BackHandler in web code paths

### ISSUE THREAD

**Issue by necolas** [react-navigation/react-navigation#11316]
### Current behavior

BackHandler is imported in web code but is not part of the react-native-web API (0.19) anymore.

### Expected behavior

BackHandler should not be used in web code paths. BackHandler can only be imported from `react-native` for native platforms, and file extension forks should be used to prevent `import { BackHandler } from 'react-native'` from being present in web code.

### Reproduction

n/a. No repro because snack doesn't use the latest versions of the react libraries.

### Platform

- [ ] Android
- [ ] iOS
- [X] Web
- [ ] Windows
- [ ] MacOS

**Comment by agusvazquez** [comment]
BackHandler got removed on react-native-web here by @necolas 
https://github.com/necolas/react-native-web/pull/2377/files#diff-7b7290df21d2dbbc4a5f367f43fb9d8beacd84c6b4ea693ccec2265d2e212404

He broke the main purpose of the library that is to provide compatibility with react native platforms, and now he expects everyone coding for react native (not web) to fix that on external libs. 

BackHandler is not deprecated on RN https://reactnative.dev/docs/backhandler.

More info here.
https://github.com/necolas/react-native-web/pull/2377
https://github.com/necolas/react-native-web/issues/2504

**Comment by Acetyld** [comment]
Any update on this?

**Comment by mlennie** [comment]
@EvanBacon any update on this? I just tried deploying to firebase and I'm getting the same issue
<img width="920" alt="Screenshot 2023-07-18 at 7 52 02 PM" src="https://github.com/react-navigation/react-navigation/assets/2946543/5840919e-556c-4a4f-9c62-4c8d211f6462">

**Comment by Gregoor** [comment]
Is there a 6.x release for this fix planned or only 7.x? I'm wondering because this seems to be blocking my expo-router adoption (in conjunction with react-native-web)
