### ISSUE TITLE
Prevent swiping and clicking at the same time in Tabs

### ISSUE THREAD

**Issue by Eloy8** [react-navigation/react-navigation#11313]
### Current behavior

Currently it's not possible to distinguish between a click event and swipe event in a Tab screen.

As seen in the recording bellow, when one swipes to a different tab from a clickable component, it also triggers a click event besides the swipe:
![Recording_2023-03-30-12-49-49(1)](https://user-images.githubusercontent.com/32520608/228836635-1d9ecd6e-5bfa-4684-883e-1357a8320b95.gif)

This combination of events will trigger both the click event (aka a navigation from the FlatList to a child component) as a swipe to a different Tab. It also seems to glitch a bit, so immediately after opening the child component it will go back to the parent component.

At this moment I haven't found a way to disable the click action when swiping, a solution would be a great improvement.
Since the code stack is private, no code is supplied. When necessary, a code snippet can be produced.

### Expected behavior

When an user swipes on a Tab screen, it won't be accompanied by click events.

### Reproduction

-

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [X] @react-navigation/material-top-tabs
- [x] @react-navigation/stack
- [x] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.0.13
| @react-navigation/bottom-tabs          | 6.4.0
| @react-navigation/drawer               | -
| @react-navigation/material-top-tabs    | 6.3.0
| @react-navigation/stack                | 6.3.2
| @react-navigation/native-stack         | 6.9.1
| react-native-safe-area-context         | 4.5.0
| react-native-screens                   | 3.20.0
| react-native-gesture-handler           | 2.9.0
| react-native-reanimated                | -
| react-native-tab-view                  | 3.3.0
| react-native-pager-view                | -
| react-native                           | 0.71.4
| expo                                   | 48.0.0
| node                                   | 16.19.0
| yarn                                    | 1.22.19

**Comment by Eloy8** [comment]
Upgrading to the specific package number doesn't solve the issue, there is no change in the previously described behavior.

**Comment by intergalacticspacehighway** [comment]
@Eloy8 are you using Pressable from React Native for clickable items? Did you try using [RectButton](https://docs.swmansion.com/react-native-gesture-handler/docs/api/components/buttons/#rectbutton) for example? 
Also, sharing a minimal repro (an expo snack or a GitHub repo with an example) would be really helpful. It really saves a ton of time 😄

**Comment by Eloy8** [comment]
@intergalacticspacehighway Thanks for your reply! Indeed we use the RN Pressable, I haven't tried RectButton.

I will provide an minimal repo later today!

**Comment by Eloy8** [comment]
Thanks for your patience, I just finished creating a minimal repo to demonstrate the problem.

All relevant code is put in the App.js file. It exists out of an overview and a detail Stack Screen.
The Overview has a swipeable Tab Navigator with three screens. When one swipes quite often and quick, the detail page will be opened. For this issue I seek a solution.

https://github.com/Eloy8/react-navigation-swipe-click-issue/blob/main/App.js

Feel free to ask if there're any further questions! :)

**Comment by Eloy8** [comment]
@intergalacticspacehighway Thanks for your patience, I just finished creating a minimal repo to demonstrate the problem.

All relevant code is put in the App.js file. It exists out of an overview and a detail Stack Screen.
The Overview has a swipeable Tab Navigator with three screens. When one swipes quite often and quick, the detail page will be opened. For this issue I seek a solution.

https://github.com/Eloy8/react-navigation-swipe-click-issue/blob/main/App.js

Feel free to ask if there're any further questions! :)

**Comment by Eloy8** [comment]
@Dhananjay-JSR Is the "needs response" label still relevant?

**Comment by DominicWiedman** [comment]
I had the same problem, but this solution helped

https://github.com/satya164/react-native-tab-view/issues/1241#issuecomment-1022400366

**Comment by DominicWiedman** [comment]
I had the same problem, but this solution helped

https://github.com/satya164/react-native-tab-view/issues/1241#issuecomment-1022400366

**Comment by Eloy8** [comment]
@DominicWiedman Thanks for your reply and suggestion!

 I've implemented it with the Pressable component and changed the position treshhold to 5 instead of 2.
 Although it is a work-around, it works incredibelly well. Thanks again!

**Comment by mharrison-nzme** [comment]
Late to the party, just wanted to reply with my solution.
Using the Touchable components from react-native-gesture-handler, rather than react-native, solved the issue for me
