### ISSUE TITLE
gestureEnabled: false doesnt work on a Stack.Screen?

### ISSUE THREAD

**Issue by LozziStyle** [react-navigation/react-navigation#11310]
### Current behavior

```
<Stack.Screen
 name="MyCases"
component={MyCasesScreen}
options={{
headerShown: false,
gestureEnabled: false,
}}
 />
```

Doesnt work. Gestures still working on MyCasesScreen.
All the issues were closed by the team without even answering the question.

### Expected behavior

Go Back Gesture not working on the MyCasesScreen.

### Reproduction

I think Im not allowed to do that (private repo)

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |6.0.13
| @react-navigation/native-stack         |6.9.0
| react-native-safe-area-context         |3.4.1
| react-native-screens                  |3.17.0 
| react-native                           |0.70.3

**Comment by satya164** [comment]
https://reactnavigation.org/docs/native-stack-navigator#gestureenabled

> **Only supported on iOS.**

**Comment by LozziStyle** [comment]
> https://reactnavigation.org/docs/native-stack-navigator#gestureenabled
> 
> > **Only supported on iOS.**

Is there any way to do the same thing on android? Or not implemented yet?

**Comment by satya164** [comment]
https://reactnavigation.org/docs/custom-android-back-button-handling

https://reactnavigation.org/docs/preventing-going-back/

**Comment by baixjian** [comment]
<img width="1226" alt="cf20a62a-1b21-48f4-aeba-f4260c6c9879" src="https://github.com/react-navigation/react-navigation/assets/109275788/bdb58c15-1f48-4544-8c2f-ffcdb5031f89">
<img width="1289" alt="1556a3af-93b5-4038-b703-5246343e168a" src="https://github.com/react-navigation/react-navigation/assets/109275788/051b7556-5076-473d-8b3d-e65302b126fc">

so  in react-navigation@v5 
Whether Android can disable the left swipe gesture when { gestureEnabled = false } is set

**Comment by reinismu** [comment]
> <img alt="cf20a62a-1b21-48f4-aeba-f4260c6c9879" width="1226" src="https://private-user-images.githubusercontent.com/109275788/264217230-bdb58c15-1f48-4544-8c2f-ffcdb5031f89.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwMTU2NzYsIm5iZiI6MTcyNTAxNTM3NiwicGF0aCI6Ii8xMDkyNzU3ODgvMjY0MjE3MjMwLWJkYjU4YzE1LTFmNDgtNDU0NC04YzJmLWZmY2RiNTAzMWY4OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgzMFQxMDU2MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mM2IzMWEzNWE5YzEzM2Q5ZTU1Yzk2MzlkOTJjYzAwZjRiYTE0OGRjN2Y3YzYwNmI3N2NlZWNhNWQwYmE4YWQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6_WESGvXG5W1t4RrQaeY-s9Wj2CGUUIn6_1Q4_fdhS4"> <img alt="1556a3af-93b5-4038-b703-5246343e168a" width="1289" src="https://private-user-images.githubusercontent.com/109275788/264217254-051b7556-5076-473d-8b3d-e65302b126fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwMTU2NzYsIm5iZiI6MTcyNTAxNTM3NiwicGF0aCI6Ii8xMDkyNzU3ODgvMjY0MjE3MjU0LTA1MWI3NTU2LTUwNzYtNDczZC04YjNkLWU2NTMwMmIxMjZmYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgzMFQxMDU2MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZTc1YTgyNWUwODdiYmJlNzZhNzQ4YjE3ZDA3YjU3ZDZlZWZkYzA3MGNlY2I0YWQ3ODg4MjZjNjg3ZGRiYzNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8EaKNW81fTRx9EGHoYOuWlao6u-f23lGighbCXYc3KA">
> 
> so in react-navigation@v5 Whether Android can disable the left swipe gesture when { gestureEnabled = false } is set

Did you ever find out what happened here? I enjoyed having back gesture on android as well
