### ISSUE TITLE
Default Stack navigator inside Tab navigator

### ISSUE THREAD

**Issue by zdnk** [react-navigation/react-navigation#11317]
### Current behavior

There seems to be a separate stack navigator in every screen of the tab navigator.
I have a tab navigator inside stack navigator to hide tab bar when navigating on iOS. However on the screens inside the tab navigator, the navigation bar is doubled and also causing different other issues like back button always says. `Back` instead the name of the previous screen or the navigation title having weird height.

### Expected behavior

The screen inside the tab navigator are plain and dont have their own stack by default.

### Reproduction

Here it is when the root stack navigators header is hidden for the tab navigator. Theres always 'Back', no previous screen name.
https://snack.expo.dev/@zdnk/petrified-watermelon

The second example shows correctly the back button, BUT on the tab screen you always have the title of the tab navigator in stack navigator.
https://snack.expo.dev/@zdnk/shallow-apple

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.1.6
| @react-navigation/bottom-tabs          | 6.5.7
| @react-navigation/native-stack         | 6.9.12
| react-native-safe-area-context         | 4.5.0
| react-native-screens                   | 3.20.0
| react-native-gesture-handler           | 2.9.0
| react-native-reanimated                | 2.14.4
| react-native                           | 0.71.4
| expo                                   | 48.0.9
| node                                   | 18.15.0
| npm                            | 9.6.1

**Comment by zdnk** [comment]
What? I believe this is a bug. I am unable to reproduce the native behavior. How is this a question since the back buttons dont work as expected?

**Comment by satya164** [comment]
Please make yourself more familiar with nesting navigators before opening an issue. In the first example you're removing the first screen's header so there's no previous title. The linked channels are a good place to discuss with others first before opening an issue.
