### ISSUE TITLE
navigation.replace creating blank white screen

### ISSUE THREAD

**Issue by sgarchavada** [react-navigation/react-navigation#11311]
### Current behavior

when I try to navigate to new screen using `navigation.replace`, I got blank white screen, if I navigate using navigation.push, then its works like charm. something is wrong with `navigation.replace`

Its say route does not exist when we use replace and same route will work with push.

### Expected behavior

navigation.replace should remove current page and redirect to new page.

### Reproduction

No repo

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

Note: I have write the package version which I am using in my project. rest I am not using it

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | ^6.1.6
| @react-navigation/bottom-tabs          | ^6.5.7
| @react-navigation/drawer               |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                |
| @react-navigation/native-stack         | ^6.9.12
| react-native-safe-area-context         | ^4.5.0
| react-native-screens                   | ^3.20.0
| react-native-gesture-handler           | 
| react-native-reanimated                |
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           | 0.71.4
| expo                                   |
| node                                   | 18.12.0
| npm or yarn                            | 1.22.19

**Comment by sgarchavada** [comment]
> Couldn't find version numbers for the following packages in the issue:
> 
> * `@react-navigation/drawer`
> * `@react-navigation/material-top-tabs`
> * `@react-navigation/stack`
> * `react-native-tab-view`
> 
> Can you update the issue to include version numbers for those packages? The version numbers must match the format 1.2.3.

As I mention, I only write version name, which I am using in my project, I am not using this packages.

**Comment by sgarchavada** [comment]
UPDATE: 
I tried this too, but still same issue

```
navigation.dispatch(   
                        StackActions.replace('login')
                    );
```

**Comment by sgarchavada** [comment]
UPDATE:  ISSUE RESOLVED
I found the culprit. In my case this library was causing the issue with navigation replace, so I removed and problem solved
`react-native-document-picker`
I dont know how its connected, but its working now, I think it somehow messing with pod of react-navigation

**Comment by sgarchavada** [comment]
I am having this issue again, turns out it's not working in IOS because of new architecture.
RCT_NEW_ARCH_ENABLED=1 pod install.

If I simply use old architecture, its working fine. if I enable again it will not work.

**Comment by em1pro** [comment]
> I am having this issue again, turns out it's not working in IOS because of new architecture. RCT_NEW_ARCH_ENABLED=1 pod install.
> 
> If I simply use old architecture, its working fine. if I enable again it will not work.

The same issue occurred here and using `@react-navigation/stack` did not result in this problem

**Comment by shreyas1328** [comment]
A work around is made from this thread: https://github.com/software-mansion/react-native-screens/issues/1628#issuecomment-1526364617

**Comment by karimb11** [comment]
This issue is still occurring as of the latest versions of both react-native and react-navigation.

**Comment by zvici** [comment]
> I am having this issue again, turns out it's not working in IOS because of new architecture. RCT_NEW_ARCH_ENABLED=1 pod install.
> 
> If I simply use old architecture, its working fine. if I enable again it will not work.

Do you have any solution yet?

**Comment by xiaofeiyun** [comment]
I also encountered the same problem with the latest versions react-navigation.

**Comment by MaharMudasar532** [comment]
in my case i  uninstall @react-native-community/blur and problem gone

**Comment by lvlupharshit** [comment]
This error also occurs randomly in my project, it's even hard to determine as it sometimes don't appear and sometimes appear randomly,  

Generally occurs when navigation screen changes
