### ISSUE TITLE
Performance mistake in Tab-View

### ISSUE THREAD

**Issue by hosseinmd** [react-navigation/react-navigation#11321]
### Current behavior

https://github.com/react-navigation/react-navigation/blob/9fe34b445fcb86e5666f61e144007d7540f014fa/packages/react-native-tab-view/src/SceneView.tsx#L40
this line of code has performance issue

### Expected behavior

SetState should be moved in useLayoutEffect

### Reproduction

https://github.com/react-navigation/react-navigation/blob/9fe34b445fcb86e5666f61e144007d7540f014fa/packages/react-native-tab-view/src/SceneView.tsx#L40

### Platform

- [X] Android
- [X] iOS
- [X] Web
- [X] Windows
- [X] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [X] react-native-tab-view

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| react-native-tab-view                  |3.5.1

**Comment by satya164** [comment]
It doesn't. Moving it to an effect will cause 2 re-renders and 2 commits. The current code does 2 re-renders but one commit which is objectively more performant.

**Comment by hosseinmd** [comment]
No, that is not right, useLayoutEffect blocks the browser from repainting. You could set state in it without repainting.
Maybe there is no different between useLayoutEffect and set state during rendering, but which one is good pattern? And which one is safe?

**Comment by satya164** [comment]
> No, that is not right, useLayoutEffect blocks the browser from repainting

I didn't say it doesn't. 1 commit and one repaint is still better than 2 commits and repaint.
