### ISSUE TITLE
Reopen: Cannot read property 'props' of undefined

### ISSUE THREAD

**Issue by beqramo** [react-navigation/react-navigation#11320]
### Current behavior

Hi,
It is ligit error,
I can't create any repo as I can't follow any pattern when and how it is happening:

Here is a link to old issue: https://github.com/react-navigation/react-navigation/issues/11113
can't

### Expected behavior

it should not crash the app

### Reproduction

I can't give you.

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view

**Comment by Dhananjay-JSR** [comment]
Can you please share a minimal repo which would show the problem happening, This way it would be easier to pin point problem as without Reproduction it's nearly impossible to find exact cause

**Comment by beqramo** [comment]
Hi, thank for your answer.
I would love to, but I don't understand where and when an error is happening so the only logical way is to put the entire app codebase on GitHub. 
I don't have a clue why or where it is coming from. 
As a blindfolded fix: to failsafe mechanism at least for now so that it will not crash the app.

So from the codes: before reaching to props object, check if config exists.
Thank you

**Comment by migueldaipre** [comment]
Could you share a simple starter project with the same routes file and parameters/names?

**Comment by beqramo** [comment]
Hi again,
I think I found something. the problem is that I'm calling navigation using ref. 
but still, this error should not happen in any case.
example:

helper for checking if Navigation is ready(on app open I'm doing things on parallel so not to miss Navigation readiness, I'm using small helper)
```tsx
export const navigationReadiness = async () => {
  if (!navigationRef.isReady()) {
    await HELPERS.delay(50)
    return await navigationReadiness()
  } else return true
}
```

Mobx Model:
```jsx


  yield navigationReadiness();
  navigationRef.reset({
      index: 1,
      routes: [
        { name: ROUTES.introduction },
        { name: ROUTES.KYC, params: { userId } },
      ],
    });
```
In the 
And also this comment can be a help too:
https://github.com/react-navigation/react-navigation/issues/11113#issuecomment-1500195364

**Comment by beqramo** [comment]
Above solutions didn't work. I have no idea when it is happening
