### ISSUE TITLE
NativeStack navigate: Always push new screens

### ISSUE THREAD

**Issue by Badestrand** [react-navigation/react-navigation#11327]
### Current behavior

`navigation.navigate` will go back to the route if it is already present in the history:

A -> B -> C -> D

navigation.navigate('A') // Now the history will be A

### Expected behavior

I think there should be a way to specify that the new screen should always be added to the stack. I mean, maybe there is a way but I couldn't find it in the [documentation](https://reactnavigation.org/docs/navigation-prop#navigate) and I found it hard the understand the source code for `Stack.Navigator`. At the very least it should be clearly added to the docs IMO.

I also don't understand why this current behaviour would be the default behaviour? I just tested some major apps (YouTube, Spotify & Instagram) and I couldn't find that behaviour in any of those. When going back a user surely wants to go back to their last screen and not a screen from 20 screens ago?

### Reproduction

-

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [X] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native | 6.1.6
| @react-navigation/native-stack         | 6.9.12

**Comment by prabakarviji** [comment]
You can add new screen using customised way of `getID` prop

From the [documentation](https://reactnavigation.org/docs/navigation-prop/#navigate) 

> By default, the screen is identified by its name. But you can also customize it to take the params into account by using the [getId](https://reactnavigation.org/docs/screen#getid) prop.
> 
> For example, say you have specified a getId prop for Profile screen:
> 
> <Tab.Screen name={Profile} component={ProfileScreen} getId={({ params }) => params.userId} />
> 
> 
> Now, if you have a stack with the history Home > Profile (userId: bob) > Settings and you call navigate(Profile, { userId: 'alice' }), the resulting screens will be Home > Profile (userId: bob) > Settings > Profile (userId: alice) since it'll add a new Profile screen as no matching screen was found.

**Comment by Badestrand** [comment]
I am aware of this parameter but how does it solve the problem?

Imagine the app opens up with the home screen, then the user navigates around a bit, then navigates to the "home" screen. This erases all their history so now when they go back again it will exit the app instead of going to their last visited screen.

Or would it be viable to use `<Tab.Screen ... getId={Math.random} />` ?

**Comment by prabakarviji** [comment]
Yes. The second option is viable for your expectation.

**Comment by satya164** [comment]
You can call `navigation.push('ScreenName')` if you always want to push a screen in a stack https://reactnavigation.org/docs/stack-actions/#push

The go back behaviour of `navigate` is being removed in React Navigation 7.

**Comment by Badestrand** [comment]
> You can call `navigation.push('ScreenName')` if you always want to push a screen in a stack https://reactnavigation.org/docs/stack-actions/#push

Perfect, thank you! Would be great if the docs [here](https://reactnavigation.org/docs/navigation-prop#navigate) could be updated about the former thing.

**Comment by satya164** [comment]
It's mentioned under https://reactnavigation.org/docs/navigation-prop/#navigator-dependent-functions

**Comment by DPirate** [comment]
> The go back behaviour of `navigate` is being removed in React Navigation 7.

Hello, does that mean in React Navigation 7 `navigate` would be equivalent to or an extension of `push`?

**Comment by moinmk** [comment]
> Hello, does that mean in React Navigation 7 `navigate` will be equivalent to or an extension of `push`?

with version 7 navigate does not go back, instead it adds new screen every time. to achieve the older behaviour now we can use navigation.navigate(SCREENNAME, PARAMS, {pop:true}) instead.
[reference](https://reactnavigation.org/docs/upgrading-from-6.x/#the-navigate-method-no-longer-goes-back-use-popto-instead)
