### ISSUE TITLE
nested Stack navigation docs are unclear:  how to access params from nested navigator

### ISSUE THREAD

**Issue by lucksp** [react-navigation/react-navigation#11324]
### Current behavior

As described in https://github.com/react-navigation/react-navigation/discussions/11254 before posting this issue.  We are navigating with a nested Stacks, however, accessing the params is appearing as `params.params` for some reason:

We follow the [instructions from your docs](https://reactnavigation.org/docs/nesting-navigators/#passing-params-to-a-screen-in-a-nested-navigator)

```
navigation.navigate('InspectionSubStack', { // Top level Stack which has a InspectionSubStack "screen".  This is really just another StackNavigator which contains `VehicleInspectionSection` screen
    screen: 'VehicleInspectionSection',  // nested screen
    params: {
        vehicleId,
        name,
        section: 'Overview',
    },
})
```

Then we update our typings [to match the docs](https://reactnavigation.org/docs/typescript/#type-checking-screens-and-params-in-nested-navigator):

```
export type RootStackParamList = HomeStackParams & InspectionStackParams;

export type HomeStackParams = {
  Account: undefined;
  CreateAccountScreen: { uuid: string };
  InspectionOverviewScreen: { inspectionId: string | number };
  Inspections: undefined;
  VehicleDetail: { vehicleId: string | number };
  InspectionSubStack: NavigatorScreenParams<InspectionStackParams>; // <-- this is our nested navigator
};

export type HomeStackScreenProps<T extends keyof HomeStackParams> = NativeStackScreenProps<
  HomeStackParams,
  T
>;
```

I am filing this issue because it's unclear how to access the params.  Should it be:

```
  const { params } = useRoute<InspectionRouteProps<'VehicleInspectionStep'>>();

```
or 
```
  const { params : { params } } = useRoute<InspectionRouteProps<'VehicleInspectionStep'>>();
```
If I read the injected `props` of the nested navigator, it looks like:
<img width="526" alt="image" src="https://user-images.githubusercontent.com/15162169/230424737-154a1e9c-3a04-41b3-b93b-c75b58d4038d.png">

Is my setup incorrect?  I attached repo.

### Expected behavior

The docs should make it clear how to access this data when inside multiple Stacks.  It's missing, or the examples tend to be a Tab or Drawer nesting

I think it always should be `const { params } = useRoute<InspectionRouteProps<'VehicleInspectionStep'>>();`?

### Reproduction

https://github.com/lucksp/expo-rne-jest-test

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | ^6.0.11
| @react-navigation/stack                | ^5.14.4
| @react-navigation/native-stack         | ^6.9.12
| react-native-safe-area-context         | 4.3.1
| react-native-screens                   | ~3.15.0
| react-native-reanimated                | ~2.9.1
| react-native                           | 0.69.6
| expo                                   | ~46.0.19
| node                                   | 16
| yarn                            | 1.22.5

https://github.com/react-navigation/react-navigation/issues/9006 was closed due to not enough info, hoping this repo & issue can help clarify

**Comment by lucksp** [comment]
> The versions mentioned in the issue for the following packages differ from the latest versions on npm:
> 
> * `@react-navigation/native` (found: `6.0.11`, latest: `6.1.6`)
> * `@react-navigation/stack` (found: `5.14.4`, latest: `6.3.16`)
> 
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?

I did successfully update, but no difference in outcome.  

The route outputs:

```
{
  key: 'InspectionSubStack-wBJy3BzPzmZQdUUgC-qEc',
  name: 'InspectionSubStack',
  params: {
    params: {
      aggId: 'be2c16cd-ccc9-4641-bfea-1d18b22d0c20',
      name: 'Default Monthly Inspection',
      section: 'Overview',
      vehicleId: 25323,
    },
    screen: 'VehicleInspectionSection',
  },
  path: undefined,
};

```

**Comment by arnavyagnik** [comment]
Hey did you manage to solve this, i am getting the same.

**Comment by lucksp** [comment]
Nope. Not sure.

**Comment by oiver555** [comment]
Still no answer to this?
