### ISSUE TITLE
typescript navigate with params

### ISSUE THREAD

**Issue by chj-damon** [react-navigation/react-navigation#11325]
### Current behavior

I'm currently using the **static configuration** introduced in **react-navigation@7**. Everything works fine until I met a typescript problem when I try to navigate from one screen to another with parameters.

```ts
navigation.navigate('Detail', {id: 2});
```

it will keep complaining: 
```ts
Type '["Detail", { id: number; }]' is not assignable to type '[screen: "Detail", params: undefined]'.
```

here's my configuration:
```ts
const RootStack = createNativeStackNavigator({
  screens: {
    Gallery: {
      screen: Gallery,
    },
    Detail: {
      screen: Detail,
    },
  },
});

const Navigation = createStaticNavigation(RootStack);

type RootStackParamList = StaticParamList<typeof RootStack>;

declare global {
  namespace ReactNavigation {
    interface RootParamList extends RootStackParamList {}
  }
}
```
I didn't find any documentation talking about this, are we missing something here?
what should I do to solve this problem?

### Expected behavior

it should support passing parameters

### Reproduction

https://github.com/thundersdata-frontend/rn-template

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |^7.0.0-alpha.1|
| @react-navigation/bottom-tabs          |^7.0.0-alpha.1|
| @react-navigation/native-stack         | ^7.0.0-alpha.1|
| react-native                           | 0.66.5|

**Comment by satya164** [comment]
Can you provide a minimal repro that demonstrates this issue?

Params should work as long as the screen specifies the params it accepts (e.g. using `StaticScreenProps`)

https://reactnavigation.org/docs/7.x/static-typescript

**Comment by chj-damon** [comment]
https://github.com/thundersdata-frontend/rn-template/tree/navigation7+reanimated3

here's the repo. I fixed it in this way:
```ts
declare global {
  namespace ReactNavigation {
    interface RootParamList extends RootStackParamList {
      SharedElementDetail: { tag: string };
    }
  }
}
```

if I remove `SharedElementDetail: { tag: string };`, typescript will complain

**Comment by chj-damon** [comment]
<img width="1102" alt="image" src="https://user-images.githubusercontent.com/4902684/230617514-2ba24ca1-df80-46fc-be39-2b82646c3276.png">

**Comment by chj-damon** [comment]
let me make it clear, the functionality works fine. it's just the typescript error.

**Comment by satya164** [comment]
Looks like there's a bug with inferring correct types when the screens are in a group. I'll take a look.

**Comment by chj-damon** [comment]
thanks for your help.

**Comment by chj-damon** [comment]
<img width="463" alt="image" src="https://user-images.githubusercontent.com/4902684/230621784-78b3e175-0fe5-46c8-b7eb-7d5a67ed1746.png">
by the way, can you take a look at this? If I delete `screens`, there's gonna be an error

**Comment by satya164** [comment]
sure. that's an easy change

**Comment by CutieCat6778** [comment]
Is the issue fixed? I'm currently updated to the latest version and it's still not working.

```js
navigation.push("EmailScreen", {
   username: "String",
});
```

```
o overload matches this call.
  Argument of type '["EmailScreen", { username: string; }]' is not assignable to parameter of type '[screen: "EmailScreen"] | [screen: "EmailScreen", params: undefined]'.
    Type '["EmailScreen", { username: string; }]' is not assignable to type '[screen: "EmailScreen", params: undefined]'.
      Type at position 1 in source is not compatible with type at position 1 in target.
        Type '{ username: string; }' is not assignable to type 'undefined'.
  Argument of type '["EmailScreen", { username: string; }]' is not assignable to parameter of type '[screen: keyof RootStackParamList] | [screen: keyof RootStackParamList, params: { screen?: undefined; params?: undefined; initial?: undefined; path?: string | undefined; state: Readonly<...> | ... 1 more ... | undefined; } | ... 8 more ... | undefined]'.
    Type '["EmailScreen", { username: string; }]' is not assignable to type '[screen: keyof RootStackParamList, params: { screen?: undefined; params?: undefined; initial?: undefined; path?: string | undefined; state: Readonly<{ key: string; index: number; routeNames: string[]; history?: unknown[] | undefined; routes: NavigationRoute<...>[]; type: string; stale: false; }> | PartialState<...> ...'.
      Type at position 0 in source is not compatible with type at position 0 in target.
        Type '"EmailScreen"' is not assignable to type 'keyof RootStackParamList'.
```

**Comment by satya164** [comment]
@CutieCat6778 please post your code

**Comment by nasunnguyenhuynh** [comment]
Something bug is really silly and unexpected.
My MainNavigator.tsx
![Screenshot 2024-09-10 211615](https://github.com/user-attachments/assets/b4174cbf-7054-4ec0-88e9-379a961b75c7)
and its type
![Screenshot 2024-09-10 211826](https://github.com/user-attachments/assets/98f25025-4b01-4879-b9c8-fcd42ab1ff44)

other types
![Screenshot 2024-09-10 212004](https://github.com/user-attachments/assets/cab47e32-37db-4e2d-a24e-2e9ba3d6ae74)
![Screenshot 2024-09-10 212031](https://github.com/user-attachments/assets/358b6dc6-a072-4cc4-aaf4-e7cab462703d)
![Screenshot 2024-09-10 212058](https://github.com/user-attachments/assets/b59e84e5-5c17-4855-b5e3-1518266f1c8e)

I want to navigate from OrderConfirmingScreen of OrderScreenStackParamList to PaymentResultScreen of PaymentStackParamList and this error happened
![Screenshot 2024-09-10 212313](https://github.com/user-attachments/assets/5588172b-9a65-4ab0-bb4c-9489137095ca)

but if I change RootStackParamList into 
![image](https://github.com/user-attachments/assets/1795b894-d159-469a-8e7d-22f0f571dce6)
It works fine 
![Screenshot 2024-09-10 212613](https://github.com/user-attachments/assets/3742d1ea-a2ac-45c9-a755-8743a1a21fcf)

The difference is "," and ";" in my declaration params.
