### ISSUE TITLE
Inconsistent TypeScript behavior with optional arguments in useNavigation

### ISSUE THREAD

**Issue by ThePlatinum** [react-navigation/react-navigation#11334]
### Current behavior

When using the `useNavigation` hook from `@react-navigation/native` in TypeScript, optional arguments are not being correctly inferred and produce a type error.

## Actual Behavior:
Optional arguments produce a type error, requiring the use of the `// @ts-ignore` comment to suppress the error.

### Expected behavior

Optional arguments should be correctly inferred and not produce a type error.

## Steps to Reproduce:
- Use the useNavigation hook with an optional argument.
- Attempt to pass a string value as the optional argument.
- Observe the type error.

### Reproduction

https://www.typescriptlang.org/play?#code/PTAEHUFMBsGMHsC2lQBd5oBYoCoE8AHSAZVgCcBLA1UABWgEM8BzM+AVwDsATAGiwoBnUENANQAd0gAjQRVSQAUCEmYKsTKGYUAbpGF4OY0BoadYKdJMoL+gzAzIoz3UNEiPOofEVKVqAHSKihSIBPBkNADeoOyCkAByDDoUzAyoFPBeAL6gAGZsiKAA5AACTgywqAC0nMmp6ZmcwHUZesUA3MEInII0dSlpGVmgALyx8UmDjVkAFACUXYo9faADDQpjoLOC5JCQnEnIAPwAXKB9lJzM82MAfKBRiqCgKgCCZMzsyJw08HloQgoYqXCjXYoiYSceA0BiCOTMOrSdxoDAERwMZAKMigf6AoglTiQPRkYrPNb1IZNALrIaQHZ7A5HSDzckqcARADWjg4PEk8k0KlKqEE1VS0KcbLAwtF4oiShetJmnBplPS9N2TiZmJZimy3SyqzMAFEAB6YgjuABqjgoDGRKHGACIABIwaAYDlkaDcJ3LQ3wdwBD3MWYm81ha22+3uVnKMA4DDuTygRDysTSDg0VDYNxmL4MZiQfiwaDqTkZ+B6EReJ1mi3uQRO3E4p3gByoEGgBKQCROoIqADyOcgZAkQmLWkgND6jgUrmkeFATjTKWuWH0KAQiB+IrEfJHkgiPshoEM7BxlqYrF53CCLyAA

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.1.6
| @react-navigation/bottom-tabs          | 6.5.7
| @react-navigation/stack                | 6.3.16
| @react-navigation/native-stack         | 6.9.12
| react-native                           | 0.71.6
| npm or yarn                            |  1.22.19

**Comment by satya164** [comment]
It has nothing to do with optional argument. There are no types defined for your screens. `string` isn't a valid type for `navigate`, it needs to be a screen name.

https://reactnavigation.org/docs/typescript/
