### ISSUE TITLE
TabView very sensitive

### ISSUE THREAD

**Issue by 7maucdn** [react-navigation/react-navigation#11333]
### Current behavior

I have an ViewPapger vertical swipe inside an TabView horizontal swipe.

Some time I swipe verticaly on ViewPager, the TabView trigger horizontal tab transition. 

### Expected behavior

Need a option for ViewPager to control swipe threshold.

### Reproduction

https://github.com/react-navigation/react-navigation

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [X] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | lasted
| @react-navigation/bottom-tabs          |lasted
| @react-navigation/drawer               |lasted
| @react-navigation/material-top-tabs    |lasted
| @react-navigation/stack                |lasted
| @react-navigation/native-stack         |lasted
| react-native-safe-area-context         |lasted
| react-native-screens                   |lasted
| react-native-gesture-handler           |lasted
| react-native-reanimated                |lasted
| react-native-tab-view                  |lasted
| react-native-pager-view                |lasted
| react-native                           |lasted
| expo                                   |lasted
| node                                   |lasted
| npm or yarn                            |lasted

**Comment by okwasniewski** [comment]
Hey, 

Please open an issue here: https://github.com/callstack/react-native-pager-view. Im closing this one since it's more of a feature request for pager-view.

**Comment by Hamidrezana** [comment]
@7maucdn  I have same problem, did you solve it?
