### ISSUE TITLE
Type of initialRouteName breaks in nested linking options

### ISSUE THREAD

**Issue by ol-web** [react-navigation/react-navigation#11332]
### Current behavior

```typescript
type RootStackParamList = {
  Main:
    | NavigatorScreenParams<{
        Library: NavigatorScreenParams<{
          LibraryMain: undefined
          Book: { id: string }
        }>
      }>
    | undefined
}

const linking: LinkingOptions<RootStackParamList> = {
  config: {
    screens: {
      Main: {
        initialRouteName: 'Library',
        screens: {
          Library: {
            initialRouteName: 'LibraryMain',
            screens: {
              Book: '/book/:id'
            }
          }
        }
      }
    }
  }
}
```

Typescript resolves both initialRouteName to the following:

```typescript
initialRouteName?: "Library" | undefined
initialRouteName?: undefined
```

### Expected behavior

Without errors, the proper types would look something like this:

```typescript
initialRouteName?: "Library" | undefined
initialRouteName?: "LibraryMain" | undefined
```

### Reproduction

https://codesandbox.io/s/linking-ts-error-hm1vhe

### Platform

- [ ] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.1.6
| node                                   | 16.15.1

**Comment by francesco-clementi-92** [comment]
I have the same problem

**Comment by Vi-dot** [comment]
Same problem, dirty fix :
```
const linking: LinkingOptions<RootStackParamList> = {
  config: {
    screens: {
      Main: {
        initialRouteName: 'Library',
        screens: {
          ...
        }
      } **as any**
    }
  }
}
```

**Comment by ol-web** [comment]
> Hello 👋, this issue has been open for more than a month without a repro or any activity. If the issue is still present in the latest version, please provide a repro or leave a comment within 7 days to keep it open, otherwise it will be closed automatically. If you found a solution or workaround for the issue, please comment here for others to find. If this issue is critical for you, please consider sending a pull request to fix it.

it's right there mr bot... 🙄
