### ISSUE TITLE
Support for react native web 0.19, transforms foreach

### ISSUE THREAD

**Issue by humaidk2** [react-navigation/react-navigation#11356]
### Current behavior

On react native web 0.19, they stopped supporting transforms as an array so Header.js and headerbackbutton.web.js
are giving off errors from react navigation elements

This is with the latest react, react native, react navigation, and react native web

### Expected behavior

Modify headerbackbutton.web.js to use strings instead of arrays for animation transforms.

For header.js, I'm not sure but it seems passing transform with undefined also causes issues. I guess that should be fixed on rnw side

### Reproduction

will add when i get time

### Platform

- [ ] Android
- [ ] iOS
- [X] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [X] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |  6.1.6 |
| @react-navigation/bottom-tabs          | 6.5.7 |
| @react-navigation/drawer               | 6.6.2 |
| @react-navigation/native-stack         | 6.9.12 |
| react-native-safe-area-context         | 4.5.2 |
| react-native-screens                   | 3.20.0 |
| react-native-gesture-handler           | 2.9.0 |
| react-native-reanimated                | 3.1.0 |
| react-native-tab-view                  | 3.5.1
| react-native                           | 0.71.7 |
| node                                   | 18.13.0 |
| yarn                            | 3.5.1 |

**Comment by chrisedington** [comment]
https://github.com/software-mansion/react-native-reanimated/pull/4352#discussion_r1194890091

**Comment by iujisato** [comment]
right now its easier to downgrade to react-native-web 0.18.10 until the fix is applied

**Comment by humaidk2** [comment]
I did a quick check so for the first issue
seems someone who knows this project has to go modify

packages/elements/src/Header/HeaderBackButton.tsx

and change those transforms to only use strings web

aka the compiled HeaderBackButton.web.js

Technically new react native has support for string transforms too so they could maybe change it completely

Also regarding the second issue,
it's not relevant to this library, seems rnw doesnt allow undefined to be passed to transform

someone already created a pr.

https://github.com/necolas/react-native-web/pull/2530

**Comment by humaidk2** [comment]
Just a small fyi,

We did test everything with all the latest libraries and this ossue is definitely resolved.
