### ISSUE TITLE
getConstants is not a function in react native navigation backbutton in header

### ISSUE THREAD

**Issue by Satyendra4** [react-navigation/react-navigation#11350]
### Current behavior

I have cloned repo fron git, and started working ,
Once I deployed to  dev environment it is showing error 
getContant is not define
in my local it working fine.

I have tried update verison react 

"dependencies": {
    "@expo-google-fonts/nunito-sans": "^0.2.2",
    "@react-native-async-storage/async-storage": "^1.17.0",
    "@react-native-picker/picker": "^2.4.1",
    "@react-navigation/drawer": "^6.5.0",
    "@react-navigation/native": "^6.0.13",
     "@react-navigation/native-stack": "^6.9.6",
    "antd": "^4.21.3",
    "axios": "^0.26.1",
    "expo": "~42.0.1",
    "expo-app-loading": "1.1.2",
    "expo-document-picker": "~9.2.4",
    "expo-font": "~9.2.1",
    "expo-status-bar": "~1.0.4",
    "lodash.get": "^4.4.2",
    "lodash.isempty": "^4.4.0",
    "lodash.set": "^4.3.2",
    "native-base": "3.2.1",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-helmet": "^6.1.0",
    "react-native": "^0.68.2",
    "react-native-circular-progress": "^1.3.7",
    "react-native-gesture-handler": "~1.10.2",
    "react-native-keyboard-aware-scroll-view": "^0.9.4",
    "react-native-markdown-display": "^7.0.0-alpha.2",
    "react-native-paper": "^4.12.1",
    "react-native-progress": "^5.0.0",
    "react-native-reanimated": "~2.2.0",
    "react-native-safe-area-context": "3.2.0",
    "react-native-screens": "~3.4.0",
    "react-native-svg": "12.1.1",
    "react-native-table-component": "^1.2.2",
    "react-native-web": "~0.13.12",
    "styled-components": "^5.3.0",
    "styled-system": "^5.1.5"
  },

After updating this issue is reproduced to me in local as well
Please suggest right way to resolve this

HeaderBackButton.tsx:207 Uncaught TypeError: react_native_web_dist_exports_I18nManager__WEBPACK_IMPORTED_MODULE_5__.default.getConstants is not a function at ./node_modules/@react-navigation/elements/lib/module/Header/HeaderBackButton.js (HeaderBackButton.tsx:207:1) at __webpack_require__ (bootstrap:789:1) at fn (bootstrap:100:1) at ./node_modules/@react-navigation/elements/lib/module/index.js (index.tsx:1:1) at __webpack_require__ (bootstrap:789:1) at fn (bootstrap:100:1) at ./node_modules/@react-navigation/drawer/lib/module/views/DrawerView.js (DrawerToggleButton.tsx:44:1) at __webpack_require__ (bootstrap:789:1) at fn (bootstrap:100:1) at ./node_modules/@react-navigation/drawer/lib/module/navigators/createDrawerNavigator.js (index.tsx:22:1) at __webpack_require__ (bootstrap:789:1) at fn (bootstrap:100:1) at ./node_modules/@react-navigation/drawer/lib/module/index.js (index.tsx:4:1) at __webpack_require__ (bootstrap:789:1) at fn (bootstrap:100:1) at ./App.jsx (bootstrap:856:1) at __webpack_require__ (bootstrap:789:1) at fn (bootstrap:100:1) at ./node_modules/expo/AppEntry.js (AppEntry.js:1:1) at __webpack_require__ (bootstrap:789:1) at fn (bootstrap:100:1) at 1 (index.js:18:1) at __webpack_require__ (bootstrap:789:1) at bootstrap:856:1 at bootstrap:856:1

### Expected behavior

It should work in local and after deployment also.
I have tried to clone many time from dev branch and there navigation code was commented to no issue 
once i use app.js file navigationcontaioner for all screen and push my code it showing error on dev env url

### Reproduction

dS

### Platform

- [ ] Android
- [ ] iOS
- [X] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject",
    "web:build": "expo build:web"
  },
  "dependencies": {
    "@expo-google-fonts/nunito-sans": "^0.2.2",
    "@react-native-async-storage/async-storage": "^1.17.0",
    "@react-native-picker/picker": "^2.4.1",
    "@react-navigation/drawer": "^6.5.0",
    "@react-navigation/native": "^6.0.13",
     "@react-navigation/native-stack": "^6.9.6",
    "antd": "^4.21.3",
    "axios": "^0.26.1",
    "expo": "~42.0.1",
    "expo-app-loading": "1.1.2",
    "expo-document-picker": "~9.2.4",
    "expo-font": "~9.2.1",
    "expo-status-bar": "~1.0.4",
    "lodash.get": "^4.4.2",
    "lodash.isempty": "^4.4.0",
    "lodash.set": "^4.3.2",
    "native-base": "3.2.1",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-helmet": "^6.1.0",
    "react-native": "^0.68.2",
    "react-native-circular-progress": "^1.3.7",
    "react-native-gesture-handler": "~1.10.2",
    "react-native-keyboard-aware-scroll-view": "^0.9.4",
    "react-native-markdown-display": "^7.0.0-alpha.2",
    "react-native-paper": "^4.12.1",
    "react-native-progress": "^5.0.0",
    "react-native-reanimated": "~2.2.0",
    "react-native-safe-area-context": "3.2.0",
    "react-native-screens": "~3.4.0",
    "react-native-svg": "12.1.1",
    "react-native-table-component": "^1.2.2",
    "react-native-web": "~0.13.12",
    "styled-components": "^5.3.0",
    "styled-system": "^5.1.5"
  },
  "devDependencies": {
    "@babel/core": "^7.9.0",
    "@types/react": "~16.9.35",
    "@types/react-native": "~0.63.2",
    "dom-helpers": "3.4.0",
    "typescript": "~4.0.0"
  },
  "private": true
}

**Comment by Satyendra4** [comment]
I have updated both drawer and eact native version still issue persist

**Comment by juanchaur** [comment]
This is happening to me as well with:
```json
    "@react-navigation/drawer": "^6.6.3",
    "@react-navigation/native": "^6.1.7",

```
