### ISSUE TITLE
tabPress no longer a part of the listeners Prop. Cannot override bottom-tabs button press behavior anymore

### ISSUE THREAD

**Issue by 1mike12** [react-navigation/react-navigation#11363]
### Current behavior

https://stackoverflow.com/a/62056423/2532762

There is supposed to be a way to override the buttons on the bottom navigator. For instance, to have one of the buttons skip the bottom tap navigation altogether and instead navigate to a new page. This was working around a year ago when I was working with this funcitonality but no longer works. 

```ts
 <Tab.Screen
            name="log"
            component={() => null}
            options={{
              tabBarIcon: LogButton as any
            }}
            listeners={{
              tabPress: (e) => {
                // Prevent default action
                e.preventDefault()
                this.props.navigation.navigate("foo")
              }
            }}
          />
```

### Expected behavior

should intercept button press and prevent default behavior

### Reproduction

none

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [X] I've removed the packages that I don't use
    "@react-navigation/bottom-tabs": "^6.5.7",
    "@react-navigation/native": "^6.1.6",
    "@react-navigation/native-stack": "^6.9.12",
    "@tsconfig/react-native": "^3.0.0",
    "react": "18.2.0",
    "react-native": "0.71.7",
    "react-native-date-picker": "^4.2.13",
    "react-native-device-info": "^10.6.0",
    "react-native-elements": "^3.4.3",
    "react-native-fast-image": "^8.6.3",
    "react-native-image-picker": "^5.3.1",
    "react-native-linear-gradient": "^2.6.2",
    "react-native-localize": "^3.0.0",
    "react-native-pager-view": "^6.2.0",
    "react-native-safe-area-context": "^4.5.2",
    "react-native-screens": "^3.20.0",
    "react-native-svg": "^13.9.0",
    "react-native-tab-view": "^3.5.1",

**Comment by 1mike12** [comment]
couldnt repro in the virtual sandbox, will create a project and update link

**Comment by ian** [comment]
Related #10637

**Comment by murilogok** [comment]
According to official docs the event "tabPress" should exists but we can't find it in any 6x version.
