### ISSUE TITLE
react-native-tab-view when use scrollEnabled, the active tab can't scroll to the right place

### ISSUE THREAD

**Issue by LastStranger** [react-navigation/react-navigation#11365]
### Current behavior

the active tab can't scroll to the right place, and after the last tab, there are a lot of empty space 

### Expected behavior

work normal, or there shouldn't have so many empty space

### Reproduction

I can't give a demo at this moment

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [X] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 
| @react-navigation/bottom-tabs          |
| @react-navigation/drawer               |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                |
| @react-navigation/native-stack         |
| react-native-safe-area-context         |
| react-native-screens                   |
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native-tab-view                  | ^3.5.1
| react-native-pager-view                |^6.2.0
| react-native                           |0.71.4
| expo                                   |
| node                                   | v16.19.1
| npm or yarn                            | yarn 1.22.19

**Comment by okwasniewski** [comment]
Hello, can you provide the reproduction? 

I will have some time to work on tab-view this Friday and wanted to check in on this. If not, I will close this issue.
