### ISSUE TITLE
@react-navigation/drawer goBack goes to the first screen

### ISSUE THREAD

**Issue by SunnyAureliusRichard** [react-navigation/react-navigation#11373]
### Current behavior

![navigationDrawerGoBackGoesHome](https://github.com/react-navigation/react-navigation/assets/100728856/5256a12c-9613-490f-be27-0712775761c3)

I've come across an issue where "go back" doesn't actually "go back". Instead, it goes to the first screen.

To test out I've made a simple app that has three screens. Navigating `Screen 1` -> `Screen 2` -> `Screen 3` and pressing `goBack` lands on `Screen 1`

### Expected behavior

It should land on `Screen 2`

### Reproduction

https://github.com/SunnyAureliusRichard/navigationDrawerGoBackGoesHome

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [X] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.1.6
| @react-navigation/drawer               | 6.6.2
| react-native-safe-area-context         | 4.5.0
| react-native-screens                   | 3.20.0
| react-native-gesture-handler           | 2.9.0
| react-native-reanimated                | 2.14.4
| react-native                           | 0.71.7
| expo                                   | 48.0.15
| node                                   | 18.12.1
| npm or yarn                            | 9.6.6

**Comment by Luca4444** [comment]
Add `backBehavior="history"` to your XXXXX.navigator component. This worked for me.

**Comment by Samamoah** [comment]
@Luca4444 It didn't work for windows it always goes to the first screen

**Comment by UIT19521334** [comment]
same with me, anything to fix ?

**Comment by UIT19521334** [comment]
@Samamoah Have you fix this issue ?

**Comment by sanikantv** [comment]
backBehavior="history"

this worked for me also
