### ISSUE TITLE
Nothing is visible on the screen, React Native 71.8 & navigation 6x

### ISSUE THREAD

**Issue by kaiyes** [react-navigation/react-navigation#11370]
### Current behavior

the stack navigator with 2 simple page renders only the header & nothing else. When I try to render a basic page, it shows white screen.  Same thing happened to our production app with 150+ screens (react-navigatioon 5x). For simplicity's sake, we uploaded a bare react native init project with basic screens with 6x react-navigation packages that are available from yarn as of today ( 12th may, 2023 ).

### Expected behavior

- At least a page should render 
- Or a stack of pages should render

### Reproduction

https://github.com/kaiyes/stackNavigatorFail71

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [X] @react-navigation/stack

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |6.1.6
| @react-navigation/bottom-tabs          |6.5.7
| @react-navigation/drawer               |6.6.2
| @react-navigation/stack                |6.3.16
| react-native-safe-area-context         |4.5.2
| react-native-screens                   |3.20.0
| react-native-gesture-handler           |2.10.0
| react-native                           |0.71.8
| expo                                   | nope
| node                                   | 20.0.0
| npm or yarn                            |1.22.18

**Comment by kaiyes** [comment]
These are the packages I'm using. Basic react-native-init with  
    
    "@react-native-community/masked-view": "^0.1.11",
    "@react-navigation/bottom-tabs": "^6.5.7",
    "@react-navigation/drawer": "^6.6.2",
    "@react-navigation/native": "^6.1.6",
    "@react-navigation/stack": "^6.3.16",
    "react": "18.2.0",
    "react-native": "0.71.8",
    "react-native-gesture-handler": "^2.10.0",
    "react-native-safe-area-context": "^4.5.2",
    "react-native-screens": "^3.20.0"

**Comment by kaiyes** [comment]
You can also take a look at screenshots of 4 files that are in the repo.
https://user-images.githubusercontent.com/5293742/237977053-0eb7adde-cca3-47f8-8b2f-c4a0b87434db.png
https://user-images.githubusercontent.com/5293742/237982499-7b12339e-44b1-421d-b9a6-bc39bf2fa62d.png
https://user-images.githubusercontent.com/5293742/2379
![simulator_screenshot_6CF0810B-1A6D-4F5B-A719-2A3C89A24217](https://github.com/react-navigation/react-navigation/assets/5293742/21a46646-a37b-46e5-8cc0-b8466466e5f0)
83062-dbfac895-38fc-43b9-9593-13ef743f1a6a.png

**Comment by satya164** [comment]
Remove `GestureHandlerRootView` wrapper from your `App` component.

**Comment by kaiyes** [comment]
Thanks @satya164 . Seems to work now. 

https://github.com/react-navigation/react-navigation/assets/5293742/a9ce1a64-b536-49fc-a416-650fd285b382
