### ISSUE TITLE
drawerIcon triggers eslint react/no-unstable-nested-components

### ISSUE THREAD

**Issue by LorenDorez** [react-navigation/react-navigation#11371]
### Current behavior

I am following example for adding icons to the drawer items. However i get an eslint error because of having components in the render.

Example of some of my drawer options
```
<Drawer.Screen
        name="About"
        component={HomeView}
        options={{
          drawerIcon: ({focused, size}) => (
            <Icon name="info" size={size} color={focused ? '#7cc' : '#ccc'} />
          ),
        }}
      />
      <Drawer.Screen
        name="Settings"
        component={HomeView}
        options={{
          drawerIcon: ({focused, size}) => (
            <Icon
              name="settings"
              size={size}
              color={focused ? '#7cc' : '#ccc'}
            />
          ),
        }}
      />
```

Maybe if we could have the dawerIcon function pass in the name prop then we cam move the drawerIcon rendering outside the parent.

### Expected behavior

Ability to dynamically render drawerIcons

### Reproduction

N/A

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [X] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.1.6
| @react-navigation/drawer               |6.6.2
| react-native-safe-area-context         |4.5.2
| react-native-screens                   |3.20.0
| react-native-gesture-handler           |2.10.0
| react-native-reanimated                |3.1.0
| react-native                           |0.71.8
| node                                   |18.16.0
| npm                            |9.5.1

**Comment by satya164** [comment]
There's no bug. The ESLint rule is wrong since those aren't components.
