### ISSUE TITLE
Light theme while in dark mode (or vice versa) does not style headers correctly

### ISSUE THREAD

**Issue by mozzius** [react-navigation/react-navigation#11397]
### Current behavior

I would like to let the user to choose between light theme, dark theme, or system theme. As such, sometimes the theme I use is at odds with the system colour scheme. However, some elements (most notably the header search) are using the system theme at all times and are not affected by the selected colour theme.

Light scheme / Light theme: ✅
<img width="334" alt="Screenshot 2023-06-01 at 08 22 18" src="https://github.com/react-navigation/react-navigation/assets/10959775/c5a76742-1159-4ed1-b0df-c271cb544433">
Dark scheme / Light scheme: ❌ - search bar is wrong and missing border beneath header
<img width="334" alt="Screenshot 2023-06-01 at 08 22 28" src="https://github.com/react-navigation/react-navigation/assets/10959775/f0659d22-18f7-40f8-b51a-e923973aaf4d">
Dark scheme / Dark theme: ✅
<img width="333" alt="Screenshot 2023-06-01 at 08 22 45" src="https://github.com/react-navigation/react-navigation/assets/10959775/d640dbf8-fba7-48a2-b0fa-46219cb92d89">
Light scheme / Dark theme: ❌ - search bar is wrong
<img width="333" alt="Screenshot 2023-06-01 at 08 22 56" src="https://github.com/react-navigation/react-navigation/assets/10959775/5b1fcc46-5ad3-4521-aa00-5eeb8a340844">

### Expected behavior

The themes should not be affected by the system dark mode - it should look like images 1 and 3 at all times (see above)

### Reproduction

https://github.com/mozzius/theme-repro

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |^6.1.6
| react-native-safe-area-context         |4.5.0
| react-native-screens                   |~3.20.0
| react-native-gesture-handler           |~2.9.0
| react-native-reanimated                |~2.14.4
| react-native-tab-view                  |^3.5.1
| react-native-pager-view                |6.1.2
| react-native                           |0.71.8
| expo                                   |^48.0.17
| node                                   |16
| npm or yarn                            |pnpm
|expo-router|^1.7.2

**Comment by WhidRubeld** [comment]
https://github.com/software-mansion/react-native-screens/issues/1683

**Comment by joaqo** [comment]
Turns out I needed to set my device to light/dark mode in the expo settings file. So you can close this issue I think.

**Comment by iliapnmrv** [comment]
Hey! Simply use [Appearance API](https://reactnative.dev/docs/appearance)
```ts
Appearance.setColorScheme
```

It fixes the issue for me. So if you store theme is context/asyncStorage, just add `setColorScheme` method or move to native RN solution

**Comment by astrahov** [comment]
With this configuration, the problem still persists. (No Expo)

<!DOCTYPE html>
package | version
-- | --
@react-navigation/bottom-tabs | 6.6.1
@react-navigation/elements | 1.3.31
@react-navigation/native | 6.1.18
@react-navigation/native-stack | 6.10.1
react | 18.2.0
react-native | 0.74.2
react-native-gesture-handler | 2.16.2
react-native-safe-area-context | 4.10.8
react-native-screens | 3.32.0
react-native-svg | 15.4.0
node | 21.7.2
npm or yarn | npm

**Comment by satya164** [comment]
https://reactnavigation.org/docs/themes#keeping-the-native-theme-in-sync
