### ISSUE TITLE
Other screen appears briefly when navigation

### ISSUE THREAD

**Issue by gosongying** [react-navigation/react-navigation#11399]
### Current behavior

when i move from my login screen to signup screen, the home screen appears briefly there even though there is no code for navigating to home screen in my login code

### Expected behavior

home screen wont appear

### Reproduction

Snack

### Platform

- [ ] Android
- [ ] iOS
- [X] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |
| @react-navigation/bottom-tabs          |
| @react-navigation/drawer               |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                |
| @react-navigation/native-stack         |
| react-native-safe-area-context         |
| react-native-screens                   |
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           |
| expo                                   |
| node                                   |
| npm or yarn                            |

**Comment by alexdobson** [comment]
We're also getting this on the latest versions. Navigating back to a previous screen in the stack shows the correct animation, but then a split second later displays the original screen you're navigating from over the top.
