### ISSUE TITLE
React-Navigation/Drawer. When Clicking Hamburger Menu, Nothing happens

### ISSUE THREAD

**Issue by kdmmanapul** [react-navigation/react-navigation#11409]
### Current behavior

React-Navigation/Drawer. When Clicking Hamburger Menu, Nothing happens. 

But, something is  blocking a portion of the screen when the  hamburger menu is pressed. then when pressed again, the blocking is gone. So I thought maybe the Drawer Screen is  there and just  can't be seen, but i'm not sure. 

If anyone got any idea that would be great.

### Expected behavior

Clicking Hamburger Menu should  toggle/open the Drawer Screen. 

### Reproduction

https://snack.expo.dev/WOLBowow4I

### Platform

- [X] Android
- [ ] iOS
- [X] Web
- [X] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

"@react-native-community/masked-view": "^0.1.11",
    "@react-navigation/drawer": "^6.6.2",
    "@react-navigation/native": "^6.1.6",
    "@react-navigation/stack": "^6.3.16",
    "axios": "^1.4.0",
    "lottie-react-native": "^5.1.6",
    "react": "18.2.0",
    "react-native": "0.71.10",
    "react-native-gesture-handler": "^2.11.0",
    "react-native-reanimated": "^3.2.0",
    "react-native-safe-area-context": "^4.5.3",
    "react-native-screens": "^3.20.0",
    "react-navigation": "^4.4.4",
    "styled-components": "^5.3.11"

**Comment by baesumin** [comment]
+1

**Comment by baesumin** [comment]
How did you get it?

**Comment by llz383455526** [comment]
when i upgrade react-native-reanimate to 3.2.0, i faced the same problem

**Comment by thitoo** [comment]
same problem with react-native-reanimated 3.2.0

**Comment by kacperkapusciak** [comment]
Upgrade to `react-native-reanimated` v3.3.0 fixes the `@react-navigation/drawer

https://github.com/react-navigation/react-navigation/assets/39658211/e0bb88f4-1e31-4a8c-9cbf-1e5b071b393e

**Comment by radelcom** [comment]
can anyone verify if this works on web too? it is not working for me at the moment. just wondering if this only resolves the native one and not in web 😢
