### ISSUE TITLE
App Crashing When "reseting previous stack with navigating" from drawer screens to Normal stack screens

### ISSUE THREAD

**Issue by Adnan46** [react-navigation/react-navigation#11407]
### Current behavior

if (navigationRef.isReady()) {
     navigationRef?.current?.dispatch(
      CommonActions.reset({
        index: 0,
        routes: [{ name: SignIn }],
      })
    );
  }

### Expected behavior

if (navigationRef.isReady()) {
     navigationRef?.current?.dispatch(
      CommonActions.reset({
        index: 0,
        routes: [{ name: name }],
      })
    );
  }

### Reproduction

no

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [x] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
"@react-native-community/checkbox": "^0.5.15",
    "@react-navigation/drawer": "^6.6.2",
    "@react-navigation/material-top-tabs": "^6.6.2",
    "@react-navigation/native": "^6.1.6",
    "@react-navigation/native-stack": "^6.9.12",
    "@rneui/base": "^4.0.0-rc.7",
    "@rneui/themed": "^4.0.0-rc.7",
    "react": "18.2.0",
    "react-native": "0.71.7",

**Comment by andrefangeloni** [comment]
Same here, is there any workaround or downgrade version?
