### ISSUE TITLE
Drawer Navigator disappears when navigator icon clicked 

### ISSUE THREAD

**Issue by shane2004ukpickerill** [react-navigation/react-navigation#11400]
### Current behavior

When I click the drawer icon, the navigator disappears as though there is navigator component

If I open the drawer navigator by swiping from left to right, the drawer opens where I see the drawer items which belong  to the navigator, however when I click the drawer item, the relevant screen is not loaded and the navigator disappears

https://github.com/react-navigation/react-navigation/assets/61972137/15cda6c9-760e-412c-a0fe-63510b40f0bc

https://github.com/react-navigation/react-navigation/assets/61972137/cf6e57ff-ad82-4f37-a2a6-51d3f39dbdad

### Expected behavior

when I click the drawer/navigation icon I expect drawer to be visible.
when I click the drawer item, I expect the navigator to still be displayed and the content of the associated screen to be displayed

### Reproduction

https://github.com/shane2004ukpickerill/test2

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use
| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |6.1.6
| @react-navigation/drawer               |6.6.2
| @react-navigation/native-stack         |6.9.12
| react-native-safe-area-context         |4.5.3
| react-native-gesture-handler           |2.10.2
| react-native-reanimated                |3.2.0
| react-native                           |0.71.8
| node                                   |19.6.0
| yarn                            |1.22.19

**Comment by ryanalencar** [comment]
I'm getting a similar error. 
My drawer is working with swipe gestures (left to right), but when I click outside the drawer component dissappears as it never existed. And then when I click on a button that I have on my custom header that has the function **navigation.openDrawer()**, it changes the drawer status to open, but the drawer doesn't appear.

Environment
| @react-navigation/native |6.1.6
| @react-navigation/drawer |6.6.2
| @react-navigation/native-stack |6.9.12
| react-native-safe-area-context |4.5.3
| react-native-gesture-handler |2.10.2
| react-native-reanimated |3.2.0
| react-native |0.71.8
| node |18.16.0
| yarn |1.22.19

**Comment by Clemweb** [comment]
Same problem here : I have a custom header with an icon calling navigation.toggleDrawer();
=  Nothing appear;

Environnement 
"@react-navigation/drawer": "^6.6.2",
  "@react-navigation/native": "^6.1.6",
  "react": "18.2.0",
  "react-native": "0.71.8",
  "react-native-gesture-handler": "^2.10.2",
  "react-native-reanimated": "^3.2.0",
  "react-native-safe-area-context": "^4.5.3",
  "react-native-screens": "^3.20.0"
"@babel/core": "^7.20.0",
    "@babel/preset-env": "^7.20.0",
    "@babel/runtime": "^7.20.0",
    "@react-native-community/eslint-config": "^3.2.0",
    "@tsconfig/react-native": "^2.0.2",
    "@types/jest": "^29.2.1",
    "@types/react": "^18.0.24",
    "@types/react-test-renderer": "^18.0.0",
    "babel-jest": "^29.2.1",
    "eslint": "^8.19.0",
    "jest": "^29.2.1",
    "metro-react-native-babel-preset": "0.73.9",
    "prettier": "^2.4.1",
    "react-test-renderer": "18.2.0",
    "typescript": "4.8.4"
"react-native": "0.71.8"

**Comment by Portkey-David** [comment]
i got the same issue     :(

**Comment by pmtu95** [comment]
I got the same issue

**Comment by pmtu95** [comment]
> I got the same issue

I tried to downgrade react-native-reanimated to version "^2.14.4", it's worked now

**Comment by khan1672** [comment]
10 days before using same code the drawer were opening by onpress and swiping both but now it is only opening by swiping but not by onpress additionally after onpress it stops swiping drawer

"dependencies": {
    "@react-navigation/bottom-tabs": "^6.5.7",
    "@react-navigation/drawer": "^6.6.2",
    "@react-navigation/native": "^6.1.6",
    "@react-navigation/native-stack": "^6.9.12",
    "react": "18.2.0",
    "react-native": "0.71.8",
    "react-native-gesture-handler": "^2.10.1",
    "react-native-reanimated": "^3.1.0",
    "react-native-safe-area-context": "^4.5.3",
    "react-native-screens": "^3.20.0",
  },


https://github.com/react-navigation/react-navigation/assets/111041491/9155c6c4-d0da-4684-a692-9224cb870e33

**Comment by kacperkapusciak** [comment]
The issue got fixed in `react-native-reanimated` v3.3.0. Please upgrade this dependency in your project to the newest version.

https://github.com/react-navigation/react-navigation/assets/39658211/3e2db3c0-25d4-4d30-88ae-91b345dad3b1

I'm closing the issue as there's no change on `react-navigation` side required.

Cheers ✌️
