### ISSUE TITLE
React Native `useColorScheme()` hook stops working when using presentation: 'fullScreenModal'

### ISSUE THREAD

**Issue by tw0po1nt** [react-navigation/react-navigation#11404]
### Current behavior

I am trying to present a `Stack.Navigator` as a `fullScreenModal` of a different stack, like so:
```
<Stack.Navigator
  initialRouteName="Splash"
  screenOptions={{
    ...GlobalStackOptions,
    headerTintColor: design.primaryText as string,
  }}>
  {/* Modal flows */}
  <Stack.Group
    screenOptions={{presentation: 'fullScreenModal', headerShown: false}}>
    <Stack.Screen name="MyScreen" component={ScreenComponent} />
  </Stack.Group>
</Stack.Navigator>
```

My app needs to support light and dark mode, which I am doing by utilizing React Native's `useColorScheme()` hook.
The rest of my app responds instantly to changes in the user's color scheme preference, but when a screen is in a fullScreenModal context, useColorScheme stops returning a correct value when the device color scheme changes.

Using `formSheet` works properly.

fullScreenModal:
https://github.com/react-navigation/react-navigation/assets/66689851/8931a780-3ae2-42ca-8ced-d968ae25cd23

formSheet:
https://github.com/react-navigation/react-navigation/assets/66689851/1d3740da-70a1-4b4b-9931-a01aa159beba

### Expected behavior

I expect the UI to respond properly to the system color scheme when a screen is presented via a fullScreenModal.

### Reproduction

todo

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.1.4
| @react-navigation/bottom-tabs          | 6.5.7
| @react-navigation/material-top-tabs    | 6.6.2
| @react-navigation/native-stack         | 6.9.10
| react-native-safe-area-context         | 4.5.0
| react-native-screens                   | 3.20.0
| react-native-gesture-handler           |  2.10.1
| react-native-tab-view                  | 3.5.1
| react-native-pager-view                | 6.2.0
| react-native                           | 0.71.4
| node                                   | 18.14.1
| npm                            | 9.3.1

**Comment by davidlintin** [comment]
Having the same issue on "@react-navigation/native": "^6.1.8"

**Comment by The0racle** [comment]
Did anyone find a solution to this?

**Comment by jforaker** [comment]
Confirming this absolutely happens. Nice find @tw0po1nt 

We have a screen with options `{ presentation: pushIfIpad() }`

```
pushIfIpad() {
    return 'isPad' in Platform && Platform.isPad ? 'push' : 'fullScreenModal';
  }
```

Toggling the colorscheme on Iphone has no effect, yet works perfectly on iPads. I've verified this by changing my Iphone config to a "push" and various other configs like "formSheet" -- all of them work except for "fullScreenModal"

**Comment by jforaker** [comment]
@tw0po1nt actually this issue is probably more related to [`react-native-screens`](https://github.com/software-mansion/react-native-screens)

Searching their code base for "fullScreenModal": 
https://github.com/search?q=repo%3Asoftware-mansion%2Freact-native-screens%20fullScreenModal&type=code

**Comment by chrysb** [comment]
This is still happening. Anyone find a solution for this?

**Comment by jforaker** [comment]
Closed via https://github.com/software-mansion/react-native-screens/issues/2002
