### ISSUE TITLE
React Native Drawer not opening on toggle press

### ISSUE THREAD

**Issue by asfaqehussain** [react-navigation/react-navigation#11414]
[###](url) Current behavior

I have created the simple example demo with the given example on the https://reactnavigation.org/docs/drawer-based-navigation/ for drawer.
Also installed the dependencies too but the drawer is not opening where as the status of the drawer is showing correctly, I have tried different versions of the package but no luck.

### Expected behavior

Drawer should open on toggle press

### Reproduction

https://github.com/asfaqehussain/rn_drawer.git/

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.1.6
| @react-navigation/drawer               | 6.6.2
| react-native-safe-area-context         | 4.5.0
| react-native-screens                   | 3.20.0
| react-native-gesture-handler           | 2.9.0
| react-native-reanimated                | 3.2.0
| react-native                           | 0.71.10
| node                                   | 18.2.0
| npm or yarn                            |

https://github.com/react-navigation/react-navigation/assets/51645676/de09c56d-abc7-45ba-8fe3-8778973d4431

**Comment by asfaqehussain** [comment]
By mistake added the wrong version I am using the latest version 6.6.2 for drawer
@react-navigation/drawer : 6.6.2

**Comment by GaelCO** [comment]
Hi, 
I think it's the same problem as this :  https://github.com/react-navigation/react-navigation/issues/11405
To workaround this issue, you can downgrade "react-native-reanimated" to  "3.1.0"

**Comment by amit13091992** [comment]
any updates on the issue fix?? getting in the iOS as well

**Comment by asfaqehussain** [comment]
> any updates on the issue fix?? getting in the iOS as well

Not yet resolved. 
Tried reanimated 3.1.0 version also

**Comment by AdamSheaHewett** [comment]
Just adding that I'm also getting this problem. The drawer does not open if I set `drawerType: 'front',` to the `screenOptions` and if I don't set anything in screenOptions I just get a blank screen.

**Comment by AdamSheaHewett** [comment]
> Just adding that I'm also getting this problem. The drawer does not open if I set `drawerType: 'front',` to the `screenOptions` and if I don't set anything in screenOptions I just get a blank screen.

I've also tried reanimated `3.1.0` although I have to patch its podfile with an additional dependency to get it to work.

**Comment by Munemh** [comment]
Any Solutions For this ticket?

**Comment by Munemh** [comment]
While it is working on swiping but after closing or clicking outside the Drawer issue occurs

**Comment by fellenabmb** [comment]
> Actually, `react-native-reanimated` just updated to `3.3.0` and now it seems to be working as expected! Fix!

Good to know, I'm running into this issue currently and tried downgrading reanimated versions with no luck so far. I'll try this and also update, thanks mate!.

**Comment by asfaqehussain** [comment]
I have tested with the latest version of Reanimated 3.2.0 and It is Working in android but not working in iOS.
There is an error while installing pods.

Below is the version with all the dependencies
    "@react-navigation/drawer": "^6.6.2",
    "@react-navigation/native": "^6.1.6",
    "react": "18.2.0",
    "react-native": "0.71.10",
    "react-native-gesture-handler": "^2.11.0",
    "react-native-reanimated": "^3.3.0",
    "react-native-safe-area-context": "^4.5.3",
    "react-native-screens": "^3.20.0"





![MicrosoftTeams-image](https://github.com/react-navigation/react-navigation/assets/51645676/2292fb6b-c4eb-4b61-92bb-6fb77638d110)

**Comment by ecosse3** [comment]
Works as expected with Reanimated `3.3.0`!

I had to remove `Pods`, `Podfile.lock` and `build` inside `ios` as well as did a `gradle clean` for Android.

```
    "@react-navigation/drawer": "6.6.2",
    "@react-navigation/native": "6.1.6",
    "@react-navigation/native-stack": "6.9.12",
    "react": "18.2.0",
    "react-native": "0.71.10",
    "react-native-gesture-handler": "2.11.0",
    "react-native-reanimated": "3.3.0",
    "react-native-safe-area-context": "4.5.3",
    "react-native-screens": "3.20.0",
```

**Comment by asfaqehussain** [comment]
**Issue resolved** with reanimated version 3.3.0 
Also, do the pod clean, and remove the podfile.lock

**Comment by kacperkapusciak** [comment]
I confirm `@react-navigation/drawer` working with `react-native-reanimated` v3.3.0

https://github.com/react-navigation/react-navigation/assets/39658211/a81f499d-f48b-4ef5-9e49-d4696d9ba27b




I'm closing the issue as there is and was nothing on the `react-navigation` side to fix.

Cheers

**Comment by zeeshanansari-danbertech** [comment]
I am facing the same issue with

    "@react-navigation/drawer": "^6.7.2",
     "react-native-reanimated": "^3.3.0",
     
 is there any solution?

**Comment by XeeshanAnsari** [comment]
I am facing the same issue with

"@react-navigation/drawer": "^6.7.2",
"react-native-reanimated": "^3.3.0",
 
is there any solution?

**Comment by XeeshanAnsari** [comment]
Any updates please?

**Comment by SreerajIS5** [comment]
if there is an issue of drawer not opening please check your react-native-reanimated version and try to update the version to 3.3.o

**Comment by asfaqehussain** [comment]
> Any updates please?

Please try to match the version of react native and reanimated. ![Image](https://github.com/user-attachments/assets/016b8776-7a62-474b-bc0f-388b5c9fd3d7)
