### ISSUE TITLE
Inconsistent behaviour in header across IOS & Android

### ISSUE THREAD

**Issue by saif-o99** [react-navigation/react-navigation#11413]
### Current behavior

I'm trying to add a small banner above the header. 
i placed it on the same level as the stack, same code on IOS and Android but different behaviour.
![Screenshot 2023-06-11 152526](https://github.com/react-navigation/react-navigation/assets/52207667/8c4128f0-e479-436e-a7de-b38217d7837b)

notice how on android its working fine but on IOS its at the top and not clickable. also notice how the header height on the IOS increased.
i tried SafeAreaView and it worked but it will cause the header height to be larger so the solution is not working fine.

### Expected behavior

Same UI should be on both platforms as the code is the same

### Reproduction

https://snack.expo.dev/

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.0.12
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                | 6.0.11
| @react-navigation/native-stack         | 6.8.0
| react-native-safe-area-context         | 3.1.8
| react-native-screens                   | 3.8.0
| react-native-gesture-handler           | 2.8.0
| react-native-reanimated                | 2.13.0
| react-native-tab-view                  | 3.1.1
| react-native-pager-view                | 5.0.12
| react-native                           | 0.70.6
| expo                                   | 47.0.8

**Comment by disrae** [comment]
I can confirm, on iPhone 14 Pro and Pro Max the issue still persists with the latest packages: 
```
@react-navigation/native (found: 6.0.12, latest: 6.1.6)
@react-navigation/stack (found: 6.0.11, latest: 6.3.16)
react-native-tab-view (found: 3.1.1, latest: 3.5.1)
```
The safe areas seem to be missing the padding? It happens on the bottom drag tab as well.

**Comment by saif-o99** [comment]
Anyone looking into this?

**Comment by saif-o99** [comment]
Not stale
