### ISSUE TITLE
I am trying to use custom header which has rounded corner bit when I apply it,its showing wierd background white color Not able to figure and fix it with code

### ISSUE THREAD

**Issue by AamenaSaiyed** [react-navigation/react-navigation#11422]
### Current behavior

![Simulator Screenshot - 12 iphone - 2023-06-15 at 15 22 56](https://github.com/react-navigation/react-navigation/assets/90598756/68550274-fbc4-43ca-8ac3-ca28edeab0c9)

### Expected behavior

![Simulator Screenshot - 12 iphone - 2023-06-15 at 15 17 51](https://github.com/react-navigation/react-navigation/assets/90598756/9aa9661c-153f-4244-ac8a-ecb29813c337)

### Reproduction

Make custom header from stack navigation options or using props.navigation.setOptions({})
```
<Stack.Screen
          {...props}
          name="EmptyScreen"
          
          options={{
            headerStyle: {

              backgroundColor: "blue",
              // height: 105,
              borderRadius: 24,
            },
            headerBackground:()=>(
              <View style={{height:105,backgroundColor:'red',width:'100%',borderBottomEndRadius:24,borderBottomStartRadius:24}}>

              </View>
            ),
            headerTitleStyle: {
              fontFamily: FONT_FAMILY.Mazzard_SemiBold,
              fontSize: FONT_SIZE.fontSize_22,
              lineHeight: 26,
              fontWeight: "600",
            },
// headerTransparent:true,
            header:()=>(
              <View style={{height:105,backgroundColor:'cyan',width:'100%',borderBottomEndRadius:24,borderBottomStartRadius:24}}>

              </View>
            ), 
            
          }}
          component={EmptyScreen}
        />
```
OR
`  useLayoutEffect(() => {
    props.navigation.setOptions(
      {
        headerBackTitle: "",
            headerBackVisible:false,
            
            headerStyle: {

              backgroundColor: Colors.DARK_PURPLE,
              // height: 105,
              borderRadius: 24,
            },
            // headerTintColor: "#fff",
            // headerTitleStyle: {
            //   fontFamily: FONT_FAMILY.Mazzard_SemiBold,
            //   fontSize: FONT_SIZE.fontSize_22,
            //   lineHeight: 26,
            //   fontWeight: "600",
            // },

      },
      []
    );
  });`

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

System:
    OS: macOS 13.0
    CPU: (12) x64 Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz
    Memory: 58.36 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 20.2.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.6.6 - ~/node_modules/.bin/npm
    Watchman: 2023.05.22.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.12.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK:
      API Levels: 26, 27, 28, 29, 30, 31, 32, 33
      Build Tools: 29.0.2, 30.0.2, 30.0.3, 31.0.0, 33.0.0, 33.0.1
      System Images: android-26 | Intel x86 Atom, android-26 | Intel x86 Atom_64, android-27 | Intel x86 Atom, android-27 | Intel x86 Atom_64, android-33 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
  Languages:
    Java: 17.0.6 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.4 => 0.66.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

Dependencies

"dependencies": {
    "@freakycoder/react-native-bounceable": ">= 0.1.1",
    "@react-native-async-storage/async-storage": "^1.17.10",
    "@react-native-community/blur": "^4.3.0",
    "@react-navigation/bottom-tabs": "^6.3.2",
    "@react-navigation/native": "^6.0.10",
    "@react-navigation/native-stack": "^6.6.2",
    "@reduxjs/toolkit": "^1.9.1",
    "@wowmaking/react-native-iron-source": "^7.0.4",
    "ironsource-mediation": "^1.0.0",
    "lodash": "^4.17.21",
    "moment": "^2.29.4",
    "native-base": "^3.4.19",
    "patch-package": "^7.0.0",
    "postinstall-postinstall": "^2.1.0",
    "react": "17.0.2",
    "react-native": "0.66.4",
    "react-native-animatable": "^1.3.3",
    "react-native-animated-pagination-dots": "^0.1.73",
    "react-native-app-intro-slider": "^4.0.4",
    "react-native-blink-view": "^0.0.6",
    "react-native-bottomsheet-reanimated": "^0.2.0",
    "react-native-countdown-component": "^2.7.1",
    "react-native-drax": "^0.10.3",
    "react-native-eject": "^0.1.2",
    "react-native-eventemitter": "^0.0.1",
    "react-native-gesture-handler": "^2.10.1",
    "react-native-interactable-reanimated": "^0.0.15",
    "react-native-linear-gradient": "^2.6.2",
    "react-native-pager-view": "^6.0.0-rc.2",
    "react-native-paper": "^4.12.2",
    "react-native-paper-dropdown": "^1.0.7",
    "react-native-popable": "^0.4.3",
    "react-native-popup-menu": "^0.16.1",
    "react-native-raw-bottom-sheet": "^2.2.0",
    "react-native-reanimated": "^2.9.1",
    "react-native-rounded-checkbox": "^0.3.3",
    "react-native-safe-area-context": "^3.3.2",
    "react-native-screens": "^3.14.1",
    "react-native-slider": "^0.11.0",
    "react-native-snap-carousel": "^3.9.1",
    "react-native-svg": "^12.1.1",
    "react-native-vector-icons": "^9.2.0",
    "react-native-viewpager": "^0.2.13",
    "react-native-walkthrough-tooltip": "^1.5.0",
    "react-redux": "^8.0.5",
    "reanimated-bottom-sheet": "^1.0.0-alpha.22",
    "redux-persist": "^6.0.0",
    "redux-thunk": "^2.4.2",
    "round-robin-tournament": "^1.2.3",
    "toggle-switch-react-native": "^3.3.0"
  },

**Comment by AamenaSaiyed** [comment]
> The versions mentioned in the issue for the following packages differ from the latest versions on npm:
> 
> * `@react-navigation/bottom-tabs` (found: `6.3.2`, latest: `6.5.7`)
> * `@react-navigation/native` (found: `6.0.10`, latest: `6.1.6`)
> 
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?

"dependencies": {
    "@freakycoder/react-native-bounceable": ">= 0.1.1",
    "@react-native-async-storage/async-storage": "^1.17.10",
    "@react-native-community/blur": "^4.3.0",
    "@react-navigation/bottom-tabs": "^6.5.7",
    "@react-navigation/native": "^6.1.6",
    "@react-navigation/native-stack": "^6.6.2",
    "@react-navigation/stack": "^6.3.16",
    "@reduxjs/toolkit": "^1.9.1",
    "@wowmaking/react-native-iron-source": "^7.0.4",
    "ironsource-mediation": "^1.0.0",
    "lodash": "^4.17.21",
    "moment": "^2.29.4",
    "native-base": "^3.4.19",
    "patch-package": "^7.0.0",
    "postinstall-postinstall": "^2.1.0",
    "react": "17.0.2",
    "react-native": "0.66.4",
    "react-native-animatable": "^1.3.3",
    "react-native-animated-pagination-dots": "^0.1.73",
    "react-native-app-intro-slider": "^4.0.4",
    "react-native-blink-view": "^0.0.6",
    "react-native-bottomsheet-reanimated": "^0.2.0",
    "react-native-countdown-component": "^2.7.1",
    "react-native-drax": "^0.10.3",
    "react-native-eject": "^0.1.2",
    "react-native-eventemitter": "^0.0.1",
    "react-native-gesture-handler": "^2.10.1",
    "react-native-interactable-reanimated": "^0.0.15",
    "react-native-linear-gradient": "^2.6.2",
    "react-native-pager-view": "^6.0.0-rc.2",
    "react-native-paper": "^4.12.2",
    "react-native-paper-dropdown": "^1.0.7",
    "react-native-popable": "^0.4.3",
    "react-native-popup-menu": "^0.16.1",
    "react-native-raw-bottom-sheet": "^2.2.0",
    "react-native-reanimated": "^2.9.1",
    "react-native-rounded-checkbox": "^0.3.3",
    "react-native-safe-area-context": "^3.3.2",
    "react-native-screens": "^3.14.1",
    "react-native-slider": "^0.11.0",
    "react-native-snap-carousel": "^3.9.1",
    "react-native-svg": "^12.1.1",
    "react-native-vector-icons": "^9.2.0",
    "react-native-viewpager": "^0.2.13",
    "react-native-walkthrough-tooltip": "^1.5.0",
    "react-redux": "^8.0.5",
    "reanimated-bottom-sheet": "^1.0.0-alpha.22",
    "redux-persist": "^6.0.0",
    "redux-thunk": "^2.4.2",
    "round-robin-tournament": "^1.2.3",
    "toggle-switch-react-native": "^3.3.0"
  },
  
  Output:-
  still same

**Comment by idrakimuhamad** [comment]
You need to set the `headerTransparent` to true so the header will be absolutely positioned, and then set the header height as the padding-top for the `contentStyle`

**Comment by haabnaseem** [comment]
Hi all, 

I want to apply top rounded corners for the content area as the image below. any got ideas ?. 

![Simulator Screenshot - iPhone 15 Pro - 2024-06-04 at 15 15 49](https://github.com/react-navigation/react-navigation/assets/7299846/00ae479f-83c4-4efb-be47-ed8c2fd876ed)

**Comment by montanhes** [comment]
> Hi all,
> 
> I want to apply top rounded corners for the content area as the image below. any got ideas ?.
> 
> ![Simulator Screenshot - iPhone 15 Pro - 2024-06-04 at 15 15 49](https://github.com/react-navigation/react-navigation/assets/7299846/00ae479f-83c4-4efb-be47-ed8c2fd876ed)

I have achived this by creating a custom bottom header:

```typescript
import React from 'react';
import { View, StyleSheet } from 'react-native';
import { useNavigation } from '@react-navigation/native';

export const CustomHeader = () => {
  const navigation = useNavigation();

  return (
    <View style={styles.top}>
      <View style={styles.topInside}></View>
    </View>
  );
};

const styles = StyleSheet.create({
  top:{
    height: 30,
    width: '100%',
    backgroundColor: '#40744D',
  },
  topInside: {
    backgroundColor: '#f2f2f2',
    height: 30,
    width: '100%',
    position: 'absolute',
    bottom: 0,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20
  },
});
```

And I call this component on every screen that need to render it, something like this:

```typescript
  return (
    <View>
      <CustomHeader />
      <Card style={styles.view}>
        <FlatList
          data={items}
          renderItem={renderItem}
          keyExtractor={(item, index) => index.toString()}
          onEndReached={handleLoadMore}
          onEndReachedThreshold={0.5}
          ListFooterComponent={renderFooter}
          ItemSeparatorComponent={({ highlighted, leadingItem }) => (
            <ItemSeparator isLast={leadingItem.index === items.length - 1} />
          )}
        />
      </Card>
    </View>
  );
```

**Comment by NarasimhaVaddala** [comment]
> You need to set the `headerTransparent` to true so the header will be absolutely positioned, and then set the header height as the padding-top for the `contentStyle`

Worked , Thankyou
