### ISSUE TITLE
Navigation is not working after app have been killed and re-opened via deep link

### ISSUE THREAD

**Issue by ValyaBabenkov** [react-navigation/react-navigation#11426]
### Current behavior

**Current behavior.**
When I open the link in minimized mode - everything works correctly, but as soon as I hide the application the screen opens but not in Modal mode but in Stack mode and the button navigation.goBack() - it fails

### Expected behavior

**Expected behavior.**
Opening a modal window and being able to close the window (navigation.goBack)

### Reproduction

https://snack.expo.dev/FC9iyta_2

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | ^6.1.6
| @react-navigation/bottom-tabs          | ^6.5.7
| @react-navigation/drawer               | ^6.5.1
| @react-navigation/stack                | ^6.3.16
| @react-navigation/native-stack         | ^6.9.1
| react-native-safe-area-context         | ^4.4.1
| react-native-screens                   | 3.18.2
| react-native-gesture-handler           | 2.8.0
| react-native-reanimated                | 2.13.0
| react-native                           | 0.70.5
| yarn                            | 1.22.19

**Code**
```
 <NavigationContainer fallback={<ActivityIndicator />} ref={navigationRef} theme={ThemeNavigation} linking={linking}>
    {profile ? <Main /> : <Auth />}
</NavigationContainer>

```

**MainNavigation**
```
<RootStack.Navigator initialRouteName={'Drawer'}>
      <RootStack.Screen
                    name="Drawer"
                    component={DrawerNavigation}
                    options={{ headerShown: false }}
        />
       <RootStack.Group
                    screenOptions={{
                        presentation: 'modal', headerShown: false,
                    }}
                >
    <RootStack.Screen
            name="DetailsShortStatusLast"
            component={DetailsShortStatusLastScene}
        />
    </RootStack.Group>
</RootStack.Navigator>
```

**Comment by ValyaBabenkov** [comment]
Updating the version did not help

> The versions mentioned in the issue for the following packages differ from the latest versions on npm:
> 
> * `@react-navigation/drawer` (found: `6.5.1`, latest: `6.6.2`)
> 
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?

**Comment by kyawthura-gg** [comment]
Can you please provide a valid repo? It will save alot of time for us. Thanks!
