### ISSUE TITLE
Getting blank screen on navigation.goBack()

### ISSUE THREAD

**Issue by Invictus-Munish** [react-navigation/react-navigation#11441]
### Current behavior

I am going forward from one page to another and while returning back using back button it shows previous page for a fraction of seconds and vanishes and blank screen appears. No error is shown.

`  const onBack = () => {
    setbackModal(false);
    props.navigation.goBack()
  }
`

https://github.com/react-navigation/react-navigation/assets/86218548/9b3a9771-a21e-4dbc-b208-c2ee46d6f660

### Expected behavior

To show the screen

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | ^6.1.7
| @react-navigation/stack                | ^6.3.17
| @react-navigation/native-stack         | ^6.9.13
| react-native-safe-area-context         | ^3.3.2
| react-native-screens                   | ^3.8.0
| react-native-gesture-handler           | ^1.10.3
| react-native                           | ^0.70.10
| expo                                   | ^48.0.0
| node                                   | 16.17.0
| npm or yarn                            | ^8.19.3

**Comment by radko93** [comment]
Hi, without any example I'm not sure if we can help here.

**Comment by Invictus-Munish** [comment]
I will share the code of the file being vanished

**Comment by Invictus-Munish** [comment]
`import React,{useEffect,useState} from 'react'
import { View, Text, StyleSheet, TouchableOpacity, FlatList, Modal, Image } from 'react-native'
import { Icon } from 'react-native-elements'
// import { Pothole, City, Hospital, School, Mechanic, Diversion, Fuel } from '../svg/pointTypes'
import api from '../apis/index'
import Others from '../components/modals/othersModal'
import store from 'react-native-simple-store';
import Header from '../components/header'
import { changeWarning } from '../redux/actions/rsa';
import { bindActionCreators } from 'redux';
import { connect } from 'react-redux';
import { ScrollView } from 'react-native'

const obj = {"id": 8, "name": "others", "type": "others"}

const RiskType = (props) => {

  const [points, setpoints] = useState([])
  const [otherModel, setotherModel] = useState(false)
  const [profile, setprofile] = React.useState(false);

  useEffect( () => {
    const willFocusSubscription = props.navigation.addListener('focus', () => {
      getPoints()
    });
    return willFocusSubscription;
  },[])

  const getPoints = async() => {
    api.getJraTripPointDefination().then(async res => {
      if(res.data.status === 'success'){
        let data = []
        data = res.data.data.filter(res => res.isApproved === "1")
        store.save('riskType',data)
        data.push(obj)
        setpoints(data)
      }else{
        var result = await store.get('riskType')
        if(result){
          result.push(obj)
          setpoints(result) 
        }
      }
    }).catch(async err => {
      console.log(err)
      var result = await store.get('riskType')
      if(result){
        result.push(obj)
        setpoints(result) 
      }
    })
  }

  const setRisk = (item) => {
    props.actions.changeWarning([item.name])
    props.navigation.navigate('Add',{item:item,...props.route.params})
  }

  return (
    <>
      <View style={props.potrait ? styles.container:styles.landscape}>
        <Header back={true} navigation={props.navigation}/>
        <Text style={styles.text}>Select the applicable risk from the list below</Text>
        {/* <ScrollView> */}
          {points && points.length > 0 && <FlatList 
            showsVerticalScrollIndicator={false}
            data={points}
            keyExtractor={(item,i) => i}
            style={{marginTop:20}}
            columnWrapperStyle={{justifyContent:'space-between'}}
            numColumns={2}
            renderItem={({item}) =>{
            if(item?.type === 'others'){
              return (
                <TouchableOpacity activeOpacity={1} style={styles.riskBox} onPress={() => setotherModel(true)}>
                  <Icon name='plus' size={20} type='font-awesome-5' color='black' onPress={() => props.navigation.goBack()} />
                  <Text style={styles.boxText}>Others</Text>
                </TouchableOpacity>
              )
            }
            return(
              <TouchableOpacity activeOpacity={1} style={styles.riskBox} onPress={() => setRisk(item)}>
                {/* {!item?.icon && item?.type === 'Risk' && <Diversion />}
                {!item?.icon && item?.type === 'City' && <City />}
                {!item?.icon && item?.type === 'Resource' && <School />} */}
                {!item?.icon && item?.type === 'Risk' && <Icon name={'exclamation-triangle'} size={20} type='font-awesome-5' color='black' />}
                {!item?.icon && item?.type === 'City' && <Icon name={'city'} size={20} type='font-awesome-5' color='black' />}
                {!item?.icon && item?.type === 'Resource' && <Icon name={'book'} size={20} type='font-awesome-5' color='black' />}
                {item?.icon && <Icon name={item?.icon} size={20} type='font-awesome-5' color='black' /> }
                <Text style={styles.boxText}>{item?.name}</Text>
              </TouchableOpacity>
            )
            }}
          />}
          <Modal 
            style={{flex:1}}
            animationType='fade'
            visible={otherModel}
            transparent
            onRequestClose={() => {
              setotherModel(false);
            }}
          >
            <Others close={() => setotherModel(false)} points={points} params={props.route.params} navigation={props.navigation} user_type='JRA' />
          </Modal>
        {/* </ScrollView> */}
      </View>
    </>
  )
}
const mapDispatchToProps = dispatch => ({
  actions: bindActionCreators(
    {
      changeWarning:changeWarning,
    },
    dispatch
  ),
});

const mapStateToProps = state => {
  return {
    potrait:state.rsa.potrait
  };
};

export default connect(mapStateToProps,mapDispatchToProps)(RiskType);

const styles = StyleSheet.create({
  container:{
    flex:1,
    backgroundColor:'#FFFFFF',
    padding:20,
    paddingBottom:60
  },
  landscape:{
    flex:1,
    backgroundColor:'#FFFFFF',
    paddingHorizontal:20,
    paddingBottom:60
  },
  avatar:{
    height:40,
    width:40,
    borderRadius:20,
    borderWidth:1,
    borderColor:'#000'
  },
  head:{
    fontFamily:'Montserrat-Medium',
    color:'#2E2E2E',
    fontSize:16,
  },
  backButton:{
    alignItems:'flex-start',
    paddingBottom:16
  },
  jraText:{
    fontFamily:'Montserrat-Medium',
    fontSize:16,
    lineHeight:19.5,
    color:'#2E2E2E'
  },
  riskBox:{
    minHeight:40,
    borderWidth:1,
    width:'48%',
    marginVertical:8,
    borderRadius:5,
    borderColor:'#e7e6e6',
    backgroundColor:'#e7e6e6',
    flexDirection:'row',
    justifyContent:'flex-start',
    paddingStart:8,
    alignItems:'center'
  },
  box:{
    height:40,
    borderWidth:1,
    width:'48%',
    marginVertical:8,
    borderRadius:5,
    borderColor:'#F7FDF7',
    backgroundColor:'#F7FDF7',
    flexDirection:'row',
    justifyContent:'flex-start',
    paddingStart:18,
    alignItems:'center'
  },
  boxText:{
    fontFamily:'Montserrat-Medium',
    fontSize:15,
    color:'#2E2E2E',
    marginLeft:8,
    width:'80%',
  },
  text:{
    fontFamily:'Montserrat-Medium',
    fontSize:12,
    color:'#2E2E2E',
    textAlign:'center',
    marginTop:16
  }
})

`

**Comment by Invictus-Munish** [comment]
Issue is solved , it was caused by [react-native-simple-radio-button](https://github.com/moschan/react-native-simple-radio-button)

**Comment by Invictus-Munish** [comment]
Issue is solved , it was caused by [react-native-simple-radio-button](https://github.com/moschan/react-native-simple-radio-button)

**Comment by shivamlooper** [comment]
facing same issue

**Comment by mohamedmagdy7** [comment]
facing same issue

**Comment by erie-e9** [comment]
Facing same, I didn't install react-native-simple-radio-button and only happens to me on only one screen (Settings to Home), I'm using a reusable back button component so it isn't clear why on this screen is happening. Any idea?
