### ISSUE TITLE
How can i put the Searchbar component before headerRight elements ?

### ISSUE THREAD

**Issue by arnelcariaga** [react-navigation/react-navigation#11442]
### Current behavior

When i set this option to display the Searchbar it's show at the end of the header but i want to show the Searchbar before the headerRight elements and not after.

```
headerSearchBarOptions: {
                disableBackButtonOverride: true,
                obscureBackground: false,
                hideNavigationBar: true
}
```

Current screen 
![Screenshot 2023-06-28 104318](https://github.com/react-navigation/react-navigation/assets/42476817/1da076b1-929f-411a-a944-85b253ec897d)

### Expected behavior

Expected screen
![Screenshot 2023-06-28 104440](https://github.com/react-navigation/react-navigation/assets/42476817/f568b9c3-68d0-419a-b719-60eeb3400162)

### Reproduction

null

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |
| @react-navigation/bottom-tabs          |
| @react-navigation/drawer               |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                |
| @react-navigation/native-stack         |
| react-native-safe-area-context         |
| react-native-screens                   |
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           |
| expo                                   |
| node                                   |
| npm or yarn                            |

**Comment by sthales** [comment]
+1

**Comment by Ainias** [comment]
@sthales @arnelcariaga We've got the same problem. Did you find a solution for the placement of the search-icon?
