### ISSUE TITLE
Invariant Violation: requireNativeComponent: "RNCViewPager" was not found in the UIManager.

### ISSUE THREAD

**Issue by gwonsuji** [react-navigation/react-navigation#11459]
### Current behavior

I am trying to upgrade from react-native 0.64.3 to react-native 0.68.6 using react native cli.

So we are migrating the React Navigation version from 5 to 6.

An error occurs when trying to create a 'Tab.Navigator' tag using the 'material-top-tabs' library.

Is there a library that doesn't fit the 0.68.6 version?

I created a project with react native cli and am using the tools of expo using install-expo-modules. In this case, can I share the source using snack? If it is impossible, I will upload an example using git.

### Expected behavior

I hope it will be executed without any problems.

### Reproduction

I will make an example and add it within a day.

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [x] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [X] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [X] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |  6.0.13
| @react-navigation/bottom-tabs          | 6.3.3
| @react-navigation/drawer               | 6.3.1
| @react-navigation/material-top-tabs    | 6.1.1
| @react-navigation/stack                | 6.3.1
| react-native-safe-area-context         | 3.3.2
| react-native-screens                   | 3.8.0
| react-native-gesture-handler           | 2.2.1
| react-native-reanimated                | 2.8.0
| react-native-tab-view                  | 3.0.1
| react-native-pager-view                | 5.4.6
| react-native                           | 0.68.6
| expo                                   | 45.0.0
| node                                   | v16.14.1
| npm or yarn                            | npm

**Comment by Felix-Asante** [comment]
I also got the same issue after installing react-native-tab-view and react-native-pager-view. can someone help me out

**Comment by Felix-Asante** [comment]
I was able to resolve this by deleting node_modules and reinstalling again. I also rebuilt the app for andriod

**Comment by gwonsuji** [comment]
hi, i was trying to make an example and finally fixed the problem. I modified the existing code to upgrade the version. In the process, we annotated the value of classpath ("com.facebook.react:react-native-gradle-plugin") in build.gradle because other modules require kotlin versioning. As a result, if you clear the comment, it ran properly. I'm glad your problem has been solved, too.
