### ISSUE TITLE
Deeplink not working with app in background

### ISSUE THREAD

**Issue by VaiteaBimOne** [react-navigation/react-navigation#11455]
### Current behavior

I have an app with a nested navigation. Deeplink is working well when the app is closed, but I have it in the background I have the error "Cannot read property 'some' of undefined" from useLinking.native.tsx where my state is empty.

Here is an example of my navigation:
```
const linking: any = {
  config: {
    screens: {
      AppStackNavigator: {
        screens: {
          TestScreen: {
            path: 'Projects/test'
          },
        }
      }
    }
  },
  getStateFromPath: async (path: any, options: any) => {
    // ...url parsing logic

    const newState = {
      ...state,
      routes: state?.routes.map((route: any) => {
        const routeName = route.state.routes[0].name;

      if(otherScreen) {
        // ...
      } else if (routeName === 'TestScreen') {
        return route;
      } else if( someOtherScreens){
        // ...
      }
    }

    return newState;
  }
}

<SafeAreaProvider initialMetrics={initialWindowMetrics}>
  ...
    <NavigationContainer onReady={() => RNBootSplash.hide({ fade: true })} ref={navigationRef} linking={linking}>
      <MainStackNavigator />
    </NavigationContainer>
  ...
</SafeAreaProvider>
```

I checked the useLinking.ative.tsx file and the state form this line `const state = navigation ? getStateFromURL(url) : undefined;` looks always something like this `{"_40": 0, "_55": null, "_65": 0, "_72": null}`

Then I have the error when `state.routes.some` is called since `.route` is undefined
```
if (state.routes.some((r) => !rootState?.routeNames.includes(r.name))) {
          console.warn(
            "The navigation state parsed from the URL contains routes not present in the root navigator. This usually means that the linking configuration doesn't match the navigation structure. See https://reactnavigation.org/docs/configuring-links for more details on how to specify a linking configuration."
          );
          return;
        }
```

When I have the error, this alert appear too
![image](https://github.com/react-navigation/react-navigation/assets/128174796/00a5bd5c-ad4d-4ea2-8c9f-5e27c70c3c80)

Is this a known bug or I am missing something since it's only happening when the app is in background? 

### Expected behavior

Open the app at the right screen when the app is opened in the background.

### Reproduction

https://snack.expo.dev/1m9gCWxDz

### Platform

- [x] Android
- [x] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |"6.0.11"
| @react-navigation/bottom-tabs          |"6.3.2"
| @react-navigation/material-top-tabs    |"6.2.2"
| @react-navigation/stack                |"6.2.2"
| @react-navigation/native-stack         |"6.7.0"
| react-native-reanimated                |"^2.14.1"
| react-native-pager-view                |"5.4.25"
| react-native                           |"0.66.5"
| yarn                            |1.22.19

**Comment by kyawthura-gg** [comment]
Can you please provide a valid repo? It will save alot of time for us. Thanks!

**Comment by VaiteaBimOne** [comment]
Here is a repo with a minimal exemple that have the error: https://github.com/VaiteaBimOne/DeepLinkError. A valid url to test the deeplink would be 'https://testvaitea.bimtrackqa.co/Projects'. 

The first time that we click on the link the app will open and redirect to the right screen. If the app is open in the background, the error will appear

**Comment by pheN1x** [comment]
I have the same problem any solution/workaround please?

**Comment by equan4647** [comment]
It works when commenting out getStateFromPath in the linking object, if you want to use you logic in this , in the end of your function call make sure it return getStateFromPath(path,obj) .

`import { getStateFromPath } from '@react-navigation/native';`


```
const linking = {
    prefixes: ['test://'],
    config: config,
    getStateFromPath: (path: string,opt :any) => {
     // logic
      return getStateFromPath(path, opt);
    },
  };
```

**Comment by satya164** [comment]
`getStateFromPath` can't be async. Closing since this is an error in your code.

**Comment by VaiteaBimOne** [comment]
Thanks @satya164!

**Comment by EavOutDom** [comment]
> Thanks @satya164!

how did you fix that?
