### ISSUE TITLE
Material Bottom Tabs doesn't have lazy prop

### ISSUE THREAD

**Issue by haiderali3071** [react-navigation/react-navigation#11456]
### Current behavior

Material Bottom Tabs doesn't have lazy prop

### Expected behavior

I want to use lazy=false prop in material bottom tabs

### Reproduction

n/a

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |
| @react-navigation/bottom-tabs          |
| @react-navigation/drawer               |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                |
| @react-navigation/native-stack         |
| react-native-safe-area-context         |
| react-native-screens                   |
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           |
| expo                                   |
| node                                   |
| npm or yarn                            |

**Comment by TomCorvus** [comment]
Do you really have to use Material Bottoms Tabs?
If not, you can use Material Top Tabs with tabBarPosition="bottom".
lazy option exists for it.

**Comment by RiedelNicolas** [comment]
Hello I'm with the same issue. Have you come with a work around @haiderali3071 ?
