### ISSUE TITLE
Can we reopen https://github.com/react-navigation/react-navigation/issues/7839 ?

### ISSUE THREAD

**Issue by billnbell** [react-navigation/react-navigation#11461]
### Current behavior

Reopen https://github.com/react-navigation/react-navigation/issues/7839 with PR

### Expected behavior

This fixes the issue.

### Reproduction

https://github.com/react-navigation/react-navigation/issues/7839

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [X] react-native-tab-view

### Environment

- [X] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |
| @react-navigation/bottom-tabs          |
| @react-navigation/drawer               |
| @react-navigation/stack                |
| @react-navigation/native-stack         |
| react-native-safe-area-context         |
| react-native-screens                   |
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native-tab-view                  |
| react-native                           | 0.72.1
| node                                   | 18
| yarn                            |

**Comment by MariuzM** [comment]
Any one know how to get first and last index of those screens? Idea I'm thinking is once reached those index disable swipe gesture, at least on my testing I'm noticing this error `Sending `onAnimatedValueUpdate` with no listeners registered.` when lets say I'm on 1st screen and trying to swipe again to left.

**Comment by ilies-space** [comment]
in my case i had this line causing the issue:

    navigation.navigate('Home', { scannedBarcode: scanResult.data }); 

Instead i tried this :


    navigation.removeListener
    navigation.navigate('Home', { scannedBarcode: scanResult.data }); 

Calling **navigation.removeListener** before navigating solved the issue for me.
