### ISSUE TITLE
Typescript issue with bottom-tabs / BottomTabScreenProps

### ISSUE THREAD

**Issue by c-goettert** [react-navigation/react-navigation#11462]
### Current behavior

Thanks for this excellent library! I am currently trying to implement a bottom-tab navigation with @react-navigation/bottom-tabs and typescript. 

Following the typescript documentation, I started using  a very simple example:

```
export type TabNavParamList = {
  Home: undefined;
};

export type HomeScreenProps = BottomTabScreenProps<TabNavParamList, 'Home'>;

const Tab = createBottomTabNavigator();

function Home({ navigation, route }: HomeScreenProps): JSX.Element {
  return (
    <View>
      <Text>HOME</Text>
    </View>
  );
}

export default function () {
  return (
    <Tab.Navigator>
      <Tab.Screen name="Home" component={Home} />
    </Tab.Navigator>
  );
}
```

However, typescript is giving me the following error (in the line where 'Home' component for Tab.Screen is defined):

> Type '({ navigation, route }: HomeScreenProps) => Element' is not assignable to type 'ScreenComponentType<ParamListBase, "Home"> | undefined'.
  Type '({ navigation, route }: HomeScreenProps) => Element' is not assignable to type 'FunctionComponent<{}>'.
    Types of parameters '__0' and 'props' are incompatible.
      Type '{}' is missing the following properties from type 'HomeScreenProps': navigation, route

You can also see the error in the ts-playground demo link. Am I missing something here or might this be a bug in the type definitions?

### Expected behavior

Typescript should not return errors.

### Reproduction

https://www.typescriptlang.org/play?ts=5.1.6&ssl=31&ssc=2&pln=9&pc=1#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wChRJY4BvOANWCQHcAaOAFSQA94BfObLgJF0MALQA7FDGAA3JGQrR41UnDhoRMJACEIMGLnYoARgDkUs4AHNp0Fmrh6DR0wGVNSJBIAKOMADODvyCePgAAiIYkpY20sAQEgD0JvqGIGIwpgH4ANykBdyU8DAAnmBIHKYWsj4oUCggADLAAfAAvDSOABK4SABccACuEgAmSJjAEkij+bz5pEXKcGUVcL0gSB5E3n4QgXCdzunGJttevv4BADynNXUNza0wbPgbCgB8C2iJbVUmhw0Wl0aVc5litkMUAAFABKBaYEYYBISdZ9aG0KRWSEotg4IbaOC8Qbvc67K6wwYAKTcAA0AHQAUQANkhNhIVI4iDAhlBUdDHOprgxmB9Beo4LduDAPt0APIAWUZ1ySnB4YolkqSIqYGrg8NIvEKXGKcHGmBQQ2ZWCRMkScDhXXU3N5-PFt1M9JqcShes1HpM9LJqKkm3aACJ3uGNLhINMOe1qO9+Ek-VrTl6IXYoHqDbwgA

### Platform

- [ ] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [X] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | ^6.1.6
| @react-navigation/bottom-tabs          |^6.5.7
| @react-navigation/native-stack         |^6.9.12
| react-native                           |0.71.7
| node                                   |14.20.0
| npm or yarn                            |yarn

**Comment by c-goettert** [comment]
Yes, the issue still persists in the latest version.

**Comment by git-user-1337** [comment]
Does anyone know how to fix this?

**Comment by saif-o99** [comment]
All of react navigation types are missed for me not only this one
