### ISSUE TITLE
react-native-tab-view rerender more than once even though I've followed the way to optimize it

### ISSUE THREAD

**Issue by chj-damon** [react-navigation/react-navigation#11468]
### Current behavior

```tsx
const FirstRoute = () => <LongList />;
const SecondRoute = () => <LongList />;

// const renderScene = SceneMap({
//   first: FirstRoute,
//   second: SecondRoute,
// });

const renderScene = ({ route }) => {
  switch (route.key) {
    case 'first':
      return <FirstRoute />;
    
    case 'second':
      return <SecondRoute />;
    
    default:
      return null;
  }
};

const routes = [
  { key: 'first', title: 'First' },
  { key: 'second', title: 'Second' },
];

const [index, setIndex] = useState(0);

return (
  <TabView lazy navigationState={{ index, routes }} renderScene={renderScene} onIndexChange={setIndex} />
);
```

```tsx
function LongList() {
  useEffect(() => {
    console.log(123);
  }, []);

  return <Text>123</Text>;
}

export default memo(LongList);
```

as you can see, I've already wrap `LongList` component with `memo` method. 

now, for the first time I enter this page, the `useEffect` in `FirstRoute` invokes once, which is perfect. but then I navigate to `SecondRoute`, the `useEffect` method invokes twice. and also if I navigate back to `FirstRoute`, the `useEffect` invokes twice too.

so there are two problems:
1. `useEffect` invokes twice.
2. `FirstRoute` should not rerender if I navigate back to it from `SecondRoute`

### Expected behavior

1. useEffect in `FirstRoute` and `SecondRoute` should both invokes only once.
2. `FirstRoute` should not rerender if I navigate back from `SecondRoute` and vice versa.

### Reproduction

https://snack.expo.dev/@chenjie/react-native-tab-view-rerender

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/native
- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [X] react-native-tab-view

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
|@react-navigation/native|6.1.7|
| react-native-tab-view                  |3.5.2|
| react-native-pager-view                |6.2.0|
| react-native                           |0.72.0
| node                                   |v16.19.1

**Comment by chj-damon** [comment]
I tried different ways to render, all behaves the same: 
```tsx
// 1
const renderScene = SceneMap({
  first: () => <LongList />,
  second: () => <LongList />,
});

// 2
const FirstRoute = () => <LongList />;
const SecondRoute = () => <LongList />;

const renderScene = SceneMap({
  first: FirstRoute,
  second: SecondRoute,
});

//3
const renderScene = ({ route }) => {
  switch (route.key) {
    case 'first':
      return <FirstRoute />;
    
    case 'second':
      return <SecondRoute />;
    
    default:
      return null;
  }
};
```

`useEffect` in `LongList` component will invoke twice.

**Comment by okwasniewski** [comment]
Hello @chj-damon,

You need to define routes outside of component. In the snack, there are routes defined inside of `TabListDemo` component. Move those outside like so: 

```ts
const FirstRoute = () => <LongList />;
const SecondRoute = () => <LongList />;

const renderScene = ({ route }) => {
  switch (route.key) {
    case 'first':
      return <FirstRoute />;

    case 'second':
      return <SecondRoute />;

    default:
      return null;
  }
};

const renderScene2 = SceneMap({
  first: () => <LongList />,
  second: () => <LongList />,
});

export const TabListDemo = () => {
  const routes = [
    { key: 'first', title: 'First' },
    { key: 'second', title: 'Second' },
  ];

  const [index, setIndex] = React.useState(0);

  return (
    <TabView
      lazy
      navigationState={{ index, routes }}
      renderScene={renderScene}
      onIndexChange={setIndex}
    />
  );
};
```

I've checked and useEffect invokes once for each route.

**Comment by chj-damon** [comment]
what if I need to pass some props to `<LongList />` component?

**Comment by okwasniewski** [comment]
You can use custom renderScene to pass props.

```tsx
export const AutoWidthTabBar = () => {
  const routes = [
    { key: 'first', title: 'First' },
    { key: 'second', title: 'Second' },
  ];

  const [index, setIndex] = React.useState(0);
  const [count, setCount] = React.useState(0);

  const renderScene = React.useCallback(
    ({ route }) => {
      switch (route.key) {
        case 'first':
          return <FirstRoute setCount={setCount} />;

        case 'second':
          return <SecondRoute count={count} />;

        default:
          return null;
      }
    },
    [count]
  );

  return (
    <TabView
      lazy
      navigationState={{ index, routes }}
      renderScene={renderScene}
      onIndexChange={setIndex}
    />
  );
};
```

**Comment by chj-damon** [comment]
yes I know that, and also I tried this code. I confirmed that it won't work. the first tab renders only once at the first time, if you switch to the second one, you'll see it renders twice, when you navigate back to the first tab, it renders twice too.

**Comment by okwasniewski** [comment]
Hey @chj-damon, 

I've prepared a snack showing that it works properly: https://snack.expo.dev/@okwasniewski/react-native-tab-view-rerender

Im getting just two `console.logs` - please confirm that it's also working for you.
<img width="303" alt="CleanShot 2023-07-18 at 14 46 54@2x" src="https://github.com/react-navigation/react-navigation/assets/52801365/88c70803-f77b-418e-a977-e508484256be">

**Comment by joemitz** [comment]
@chj-damon I'm having this problem too. Did you ever solve it?

**Comment by badereddinesassi** [comment]
any updates on this ?

**Comment by chj-damon** [comment]
I made a tabview component myself in the end.
