### ISSUE TITLE
Keyboard pushing Header when scrolling screen to avoid hiding an input (Android only)

### ISSUE THREAD

**Issue by mkalaizich** [react-navigation/react-navigation#11479]
### Current behavior

When keyboard appears and scrolls the screen so it doesn't hide the input, it pushes too the screen header. Here's a video of that behaviour: 

https://github.com/react-navigation/react-navigation/assets/22138653/c594c493-1d7b-4a95-85d4-b8f141ac5590

in my app.config.ts file softwareKeyboardLayoutMode is already set to 'pan' for android

this are some snippets of my code
Index file with the rootstack
`<RootStack.Group key="auth">
   <RootStack.Screen name="Register" options={{ title: 'Register' }} component={RegisterForm} />
</RootStack.Group>
`

RegisterForm Component Excerpt (Box component is from restyle and Input component is custom)

`
<KeyboardAvoidingView
      keyboardVerticalOffset={Platform.OS === 'ios' ? headerHeight + Number(StatusBar.currentHeight) : 0}
      behavior={'padding'}
      enabled={Platform.OS === 'ios'}
      style={{ flex: 1 }}
>
  <ScrollView
        contentInsetAdjustmentBehavior="automatic"
        keyboardShouldPersistTaps="handled"
        keyboardDismissMode="on-drag"
        scrollEnabled={scrollEnabled}
        contentContainerStyle={[
          {
            flexGrow: 1,
          },
          contentContainerStyle,
        ]}
        refreshControl={refreshControl}
      >
        <Box flex={1} backgroundColor="backgroundPrimary" {...rest}>
           <Box pt="xl" paddingHorizontal="l">
               <Input
                  autoComplete="name"
                 label="Full name"
                placeholder="Enter your name"
              />
              <Input
                autoCapitalize="none"
                autoComplete="email"
                label="email"
                placeholder="Email"
             />
          <Input
               autoComplete="password"
               icon="lock"
               password
               label="Password"
               placeholder="Password"
          />
         <Input
               autoComplete="password"
               label="confirm password"
             placeholder="Repeat password"
         />
      </Box>
      <Box width="100%" alignItems="center" paddingHorizontal="l">
          <Button
            width="100%"
            text="create account"
          />
      </Box>
  </ScrollView>

</KeyboardAvoidingView>
`

The example from KeyboardAvoidingView has a similar behaviour

### Expected behavior

Keyboard should scroll the screen container but not the header.

### Reproduction

https://reactnative.dev/docs/keyboardavoidingview

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/bottom-tabs          | ^6.0.5
| @react-navigation/material-top-tabs    | ^6.2.1
| @react-navigation/stack                |^6.2.1
| @react-navigation/native-stack         |^6.1.0
| react-native-safe-area-context         |4.4.1
| react-native-screens                   |~3.18.0
| react-native-gesture-handler           |~2.8.0
| react-native-reanimated                |~2.12.0
| react-native-pager-view                |6.0.1
| react-native                           |0.70.10
| expo                                   |^47.0.12
| node                                   |16.13.2
| npm or yarn                            |8.1.2

**Comment by little-buddy** [comment]
Same issue. 
IOS is ok.
Help~

**Comment by mkalaizich** [comment]
> Hey, man @mkalaizich I find a solution Do any nothing Only set `AndroidManifest.xml` -> android:windowSoftInputMode="adjustResize" then is ok 😁

I already tried that and didn't worked

**Comment by little-buddy** [comment]
@mkalaizich set behavior = `undefined` in Android, It will work!

```JS
<KeyboardAvoidingView
      behavior={Platform.OS === 'ios' ? 'padding' : undefined}
      keyboardVerticalOffset={
        Platform.OS === 'ios' ? keyboardVerticalOffset : 0
      }
    >
    {children}
</KeyboardAvoidingView>
```

**Comment by mkalaizich** [comment]
> @mkalaizich set behavior = `undefined` in Android, It will work!
> 
> ```js
> <KeyboardAvoidingView
>       behavior={Platform.OS === 'ios' ? 'padding' : undefined}
>       keyboardVerticalOffset={
>         Platform.OS === 'ios' ? keyboardVerticalOffset : 0
>       }
>     >
>     {children}
> </KeyboardAvoidingView>
> ```

Also already done but didnt worked

**Comment by datngotan-aavn** [comment]
Has anyone resolved this issue yet?

**Comment by abhaykumar181** [comment]
> Hey, man @mkalaizich I find a solution Do any nothing Only set `AndroidManifest.xml` -> android:windowSoftInputMode="adjustResize" then is ok 😁

Thanks @mkalaizich

**Comment by Alwaz** [comment]
2026, same issue, already have adjustResize set, but nothing works. Please help
