### ISSUE TITLE
Button presses do not fire when navigator does not cover whole screen on Fabric with New Architecture

### ISSUE THREAD

**Issue by erksch** [react-navigation/react-navigation#11471]
### Current behavior

Hey there,

I was trying to get the new architecture and fabric running in our Android only app on RN 0.71.12, when I noticed that some (not all) button presses in my app would not fire. 

I investigated the problem and found that if you have a view above the native stack navigator it results in buttons inside of screens in the navigator not to fire.

Here is a basic  reproducer:

```typescript
const HomeScreen = () => {
  const [counter, setCounter] = useState(0);

  return (
    <View>
      <TouchableOpacity
        onPress={() => {
          setCounter(counter + 1);
        }}
        style={{
          padding: 10,
          backgroundColor: 'lightblue',
          margin: 20,
          borderRadius: 5,
        }}>
        <Text>Counter {counter}</Text>
      </TouchableOpacity>
    </View>
  );
};

const Stack = createNativeStackNavigator();

const App = () => {
  return (
    <SafeAreaView style={{flex: 1}}>
      <NavigationContainer>

         {/* THIS VIEW RESULTS IN BUTTON PRESSES NOT FIRING */}
        <View style={{ height: 120,  backgroundColor: 'lightblue' }} />

        <Stack.Navigator
          initialRouteName="home"
          screenOptions={{ headerShown: false }}
       >
          <Stack.Screen name="home" component={HomeScreen} />
        </Stack.Navigator>
      </NavigationContainer>
    </SafeAreaView>
  );
};
```

https://github.com/react-navigation/react-navigation/assets/19290349/2198033c-f3b4-4fbc-ae9a-3fb959821909

The current behaviour is that the counter does add count up (`onPress` is never called), when I re move the view above the navigator or set its `height` to 0, `onPress` is called correctly and the counter goes up.

### Expected behavior

`onPress` should fire regardless of the `View` above the navigator.

### Reproduction

https://github.com/erksch/react-navigation-fabric-issue-reproducer

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | v6.1.7
| @react-navigation/native-stack         | v6.9.13
| react-native-safe-area-context         | 4.7.1
| react-native-screens                   | v3.19.0
| react-native                           | v0.71.12
| node                                   | v16.16.0
| npm or yarn                            | yarn 1.22.19

**Comment by kyawthura-gg** [comment]
I don't see any issue.

<img width="501" alt="Screen Shot 2023-08-17 at 7 00 31 PM" src="https://github.com/react-navigation/react-navigation/assets/44088165/3b401244-b853-4d68-97f4-5fbd61b52dfb">

**Comment by bnchdrff** [comment]
I just reproduced this issue with the above-linked repo, on a pixel 7.

**Comment by christocracy** [comment]
I'm seeing this too now with react-native `0.76.3` with new arch.

`onPress` on a `<Button />` does **not** fire.

```javascript
React.useLayoutEffect(() => {    
    navigation.setOptions({
      headerRight: () => (
        <Button onPress={() => alert('Simple Button pressed')} title="Register" />
      ),
    });
  }, [navigation, org, username]);
```

But replacing with a `<Switch />`, the `onValueChange` **DOES** fire.

```javascript
React.useLayoutEffect(() => {    
    navigation.setOptions({
      headerRight: () => (
        <Switch onValueChange={() => alert('Switch toggled')} value={true} />
      ),
    });
  }, [navigation, org, username]);
```
