### ISSUE TITLE
Build failed with RN 0.72.0 + react-native-reanimated 3.3.0 Android

### ISSUE THREAD

**Issue by vincemavill** [react-navigation/react-navigation#11470]
### Current behavior

Build failed on Android,

I am using windows with Android studio simulator
NDK version: 23.1.7779620
React Native version: 0.72.0
    "@react-navigation/drawer": "^6.6.3",
    "@react-navigation/native": "^6.1.7",
    "@react-navigation/native-stack": "^6.9.13",
    "@react-navigation/stack": "^6.3.17",
    "react-native-reanimated": "^3.3.0",
    "react-native-safe-area-context": "^4.7.1",
    "react-native-screens": "^3.22.1",

Error message below

node_modules/react-native-reanimated/Common/cpp/Fabric/ReanimatedUIManagerBinding.cpp.o cannot be safely placed under this directory. The build may not work correctly. ninja: error: manifest 'build.ninja' still dirty after 100 tries

### Expected behavior

Build success

### Reproduction

none

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [X] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |
| @react-navigation/drawer               |
| @react-navigation/stack                |
| @react-navigation/native-stack         |
| react-native-safe-area-context         |
| react-native-screens                   |
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native                           |
| node                                   |
| npm or yarn                            |

**Comment by radko93** [comment]
Hi, this issues does seem related to React Navigation. Please open an issue with Reanimated.
