### ISSUE TITLE
New Architecture: Drawer overlay not clickable in iOS

### ISSUE THREAD

**Issue by ravindraguptacapgemini** [react-navigation/react-navigation#11474]
### Current behavior

We are facing issues with click on the blur background, the clicks are going down to screen beneath the opened drawer and not dismissing the drawer at all, it specifically happens on the New Architecture of React Native.

### Expected behavior

We should be able to click the blur background to dismiss the drawer, click should not go beyond the opened drawer.

### Reproduction

https://snack.expo.dev/?platform=ios

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |6.1.7
| @react-navigation/drawer               |6.6.3
| @react-navigation/stack                |6.3.17
| react-native-safe-area-context         |4.7.1
| react-native-screens                   |3.22.1
| react-native-gesture-handler           |2.12.0
| react-native-reanimated                |3.3.0
| react-native                           |0.72.1
| node                                   |16.20.0
| npm or yarn                            |8.19.4

**Comment by ravindraguptacapgemini** [comment]
Checked again going to the node_modules directly, I am using the latest version of these libraries only. Update the issue as well.

**Comment by NonSerializedClass** [comment]
I am facing something similar with RN 0.72,3 and New Arch enabled on iOS

**Comment by ravindraguptacapgemini** [comment]
@NonSerializedClass found any fix for this issue?

**Comment by ravindraguptacapgemini** [comment]
Why no one replies here, expected a response at least from the library maintainers. I have provided the repro as well.

**Comment by ravindraguptacapgemini** [comment]
@satya164 seems this issue has started after you changes for overlay as in commit: https://github.com/react-navigation/react-navigation/commit/5f94c1d6c421a7d6f8781c5188b4f2a654c338d2.
Also due to this commit the background element on the screen are not accessible anymore when the drawer is open. please check the issue once.

**Comment by ravindraguptacapgemini** [comment]
[ericvicenti](https://github.com/ericvicenti)

**Comment by ravindraguptacapgemini** [comment]
@ericvicenti can you please check this one

**Comment by ravindraguptacapgemini** [comment]
Similar issue: https://github.com/react-navigation/react-navigation/issues/10893, no solution provided yet

**Comment by ravindraguptacapgemini** [comment]
Issue seems to be fixed with latest version of dependencies as below. I did not check which of these has the fixed the issue, just updated all to latest version and it's working fine now.

    "@react-navigation/drawer": "^6.6.3",
    "@react-navigation/native": "^6.1.7",
    "@react-navigation/stack": "^6.3.17",
    "react-native-gesture-handler": "^2.12.1",
    "react-native-reanimated": "^3.5.1",
    "react-native-safe-area-context": "^4.7.2",
    "react-native-screens": "^3.25.0",

Closing the now.
