### ISSUE TITLE
TypeScript Error: Property 'navigate' does not exist on type 'Props'.ts(2339) -- but it's there and I can navigate just fine.

### ISSUE THREAD

**Issue by soemarko** [react-navigation/react-navigation#11476]
### Current behavior

To simplify, I have this as navigation props: `type NavProps = NativeStackScreenProps<StackParamList>;`

And I want to use `useNavigation()` like so: `const navigation = useNavigation<NavProps>();`

<img width="485" alt="Screenshot 2023-07-17 at 5 26 05 pm" src="https://github.com/react-navigation/react-navigation/assets/381585/6ad29c12-a40c-4795-931e-35bb10fab2b8">

However VSCode spits out error like titled when I use it like `navigation.navigate('Screen', { label: 'Activity' });` even though I can navigate just fine.

VSCode seems to think that the navigation property is one level below, following the autocomplete it spits it out like: `navigation.navigation.navigate()`, but this will crash the app since `navigation.navigation` is _undefined_.

<img width="442" alt="Screenshot 2023-07-17 at 5 40 55 pm" src="https://github.com/react-navigation/react-navigation/assets/381585/134a6002-076a-43bb-a6c8-fb29e48fa488">

### Expected behavior

VSCode should work as expected. As in no error complains because the app is running as expected.

### Reproduction

https://snack.expo.dev/c1h-n6hoJ

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | ^6.1.4
| @react-navigation/drawer               |^6.6.3
| @react-navigation/native-stack         |^6.9.10
| react-native-safe-area-context         |^4.4.1
| react-native-screens                   |^3.20.0
| react-native-gesture-handler           |^2.9.0
| react-native-reanimated                |^3.0.2
| react-native                           |0.72.3
| node                                   |v18.15.0
|  yarn                            |1.22.19

**Comment by soemarko** [comment]
Figured it out. Should have used `NativeStackNavigationProp` instead of `NativeStackScreenProps`

**Comment by sohaibzahid197** [comment]
It Works For as , 

App.tsx

// App.tsx

import React from 'react';
import SplashScreen from './src/screens/SplashScreen';
import SplashScreen2 from './src/screens/SplashScreen2';
import SplashScreen3 from './src/screens/SplashScreen3';
import NumberVerfication from './src/screens/NumberVerification';
import OTP
 from './src/screens/OTP';
 import SelectCountry from './src/screens/SelectCountry';
 import SelectArea from './src/screens/SelectArea';
 import Numbers from './src/screens/SelectNumber';
 import ChoosePlan from './src/screens/ChoosePlan';
import Home from './src/screens/Home';
 import {NavigationContainer} from '@react-navigation/native';

import { createNativeStackNavigator } from '@react-navigation/native-stack';
import { RootStackParamList } from './src/types';


const Stack = createNativeStackNavigator<RootStackParamList>();

const App: React.FC = () => {
  

  return (<NavigationContainer>
    <Stack.Navigator>
      <Stack.Screen name = 'splash' component = {SplashScreen}></Stack.Screen>
      <Stack.Screen name = 'splash2' component = {SplashScreen2}></Stack.Screen>

    </Stack.Navigator>
  </NavigationContainer> );
};

export default App;

========================
//SplashScreen
import React from 'react';
import { View, Text, StyleSheet, Image, Dimensions, TouchableWithoutFeedback } from 'react-native';
import { NativeStackScreenProps } from '@react-navigation/native-stack';
import { RootStackParamList } from '../types';  // Assuming types.ts is at the same level as SplashScreen

type SplashScreenProps = NativeStackScreenProps<RootStackParamList, 'splash'>;

const { width } = Dimensions.get('window');

const SplashScreen: React.FC<SplashScreenProps> = ({ navigation }) => {
  return (
    <TouchableWithoutFeedback onPress={() => navigation.navigate("splash2")}>
      <View style={styles.container}>
        {/* Icon */}
        <Image
          source={require('../assets/logo1.png')}
          style={styles.icon}
        />

        <View style={styles.textContainer}>
          <Text style={styles.title}>2nd Virtual</Text>
          <Text style={styles.subtitle}>E-sim</Text>
        </View>
      </View>
    </TouchableWithoutFeedback>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    backgroundColor: '#FFFFFF',
  },
  icon: {
    width: width * 0.15,
    height: width * 0.15,
    marginRight: '5%',
  },
  textContainer: {
    justifyContent: 'center',
  },
  title: {
    fontSize: width * 0.05,
    fontWeight: 'bold',
    color: '#000000',
  },
  subtitle: {
    fontSize: width * 0.04,
    color: '#000000',
  },
});

export default SplashScreen;
==========
// types.ts

export type RootStackParamList = {
    splash: undefined;
    splash2: undefined;
  };
