### ISSUE TITLE
Bottom inset on a BottomTabNavigator is 4 pixels off on iOS 

### ISSUE THREAD

**Issue by SSead** [react-navigation/react-navigation#11480]
### Current behavior

While tinkering around insets in my app, trying to match everything on iOS and Android, I noticed that the navigation bars didn't look the same on both platforms. I inspected what was happening and found that the `paddingBottom`  property on the navigation bar didn't match the value I was getting with `useSafeAreaInsets()`. On an iPhone 14 Pro the bottom inset returned by `useSafeAreaInsets()` is `34` but the `paddingBottom` property on the bottom navigation is `30` (see screenshot bellow).

Naturally, I tried to find a solution and I stumbled upon the `safeAreaInsets` property on the `Navigator` component, but it did not fix the issue. If I pass in a value like `{bottom: 10}` the padding on the `Navigator` will be `6`. That means that the padding always gets lowered by 4.

![IMG_0574](https://github.com/react-navigation/react-navigation/assets/34585838/5c48b9b9-9a2b-413e-8b33-e3d3185a40db)

### Expected behavior

The padding on the navigator should match the value supplied by the `SafeAreaProvider` or the value passed to the `safeAreaInsets` property.

### Reproduction

https://github.com/SSead/DummyNavigation

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [X] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.1.7
| @react-navigation/bottom-tabs          | 6.5.8
| react-native-safe-area-context         | 4.7.1
| react-native-screens                   | 3.22.1
| react-native                           | 0.72.3
| node                                   | 16.14.0
| yarn                            | 1.22.19

**Comment by satya164** [comment]
The tab bar tries to match the platform behaviour, e.g. how the safe area in native tab bar on iOS. If you want to match everything exactly the same on Android and iOS then you should use your own components for header, tab bar etc. as that's not a goal of React Navigation.
