### ISSUE TITLE
drawer && useLegacyImplementation 

### ISSUE THREAD

**Issue by TomWq** [react-navigation/react-navigation#11498]
### Current behavior

Error: The `useLegacyImplementation` prop is not available with Reanimated 3 as it no longer includes support for Reanimated 1 legacy API. Remove the `useLegacyImplementation` prop from `Drawer.Navigator` to be able to use it.

 "@react-navigation/drawer": "^6.6.3",
 "react-native": "0.72.3",
  "react-native-reanimated": "^3.4.0",

### Expected behavior

Normal operation

### Reproduction

none

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

 "@react-navigation/drawer": "^6.6.3",
 "react-native": "0.72.3",
  "react-native-reanimated": "^3.4.0",

**Comment by LukasMod** [comment]
Had same error today with similar dependencies (only diff is react-native: "0.71.10")
Rebuilding and cache clear helped me:
`rm -rf $TMPDIR/metro-* && watchman watch-del-all && cd android && ./gradlew clean && cd .. && rm -rf android/app/build && rm -rf node_modules && yarn`

**Comment by ivosabev** [comment]
"@react-navigation/native": "6.1.7"

**Comment by alimek** [comment]
yeah, just upgraded all deps to latest version and I am getting the same error only with something like that: 

```js
<Drawer.Navigator
  drawerContent={props => <DrawerContent {...props} />}
>
  <Drawer.Screen name="BottomTabs" component={BottomTabNavigation} />
</Drawer.Navigator>
```

I am pretty sure in my code `useLegacyImplementation` is never used 🤔

**Comment by ivosabev** [comment]
The cause is react-native-reanimated 3.4.0 deleting isConfigured()

https://github.com/software-mansion/react-native-reanimated/pull/4727

Which breaks this logic here

https://github.com/react-navigation/react-navigation/blob/24c03924397a6e59aba9f6b74a9c5cb4b939d9e1/packages/react-native-drawer-layout/src/views/Drawer.tsx#L56

**Comment by jasminder** [comment]
I have also started getting this issue today. What is happening? What is the solution?

**Comment by ivosabev** [comment]
Downgrade to reanimated 3.3.0 until react-navigation fixes their use of `isConfigured`

**Comment by jraleman** [comment]
I am also running into the same issue after updating my `react-native` version: `0.71.8` → `0.72.3`. 
My `react-native-reanimated` version is 3.3.0... what version should I downgrade it to? I am afraid this may break things in my project.

**Comment by myatphyokyaw2** [comment]
This is ok=>https://github.com/react-navigation/react-navigation/issues/10253

**Comment by kacperkapusciak** [comment]
React Native Reanimated 3.4.1 was released with a fix for this issue. It should be good now.

https://github.com/software-mansion/react-native-reanimated/releases/tag/3.4.1

Cheers

**Comment by jraleman** [comment]
I have updated `react-native-reanimated` to `3.4.1` and it has solved this issue. 

This is the list of my related dependencies:

```json
{
    "@react-navigation/drawer": "^6.6.2",
    "@react-navigation/native": "^6.1.6",
    "@react-navigation/stack": "^6.3.17",
    "react": "18.2.0",
    "react-native": "0.72.3",
    "react-native-gesture-handler": "^2.12.0",
    "react-native-reanimated": "^3.4.1",
    "react-native-safe-area-context": "^4.5.3",
}
```

@luvnishCapgemini I see you have packages with newer subversions compared to mine... maybe you can try downgrading some of them? In case that fixes the issue for you.

**Comment by Dakuan** [comment]
this is still an issue for us with the exact same deps as @jraleman

**Comment by NoodleOfDeath** [comment]
> this is still an issue for us with the exact same deps as @jraleman

same issue for me. im not even sure what changed because i literally just did `rm -rf node_modules` then `yarn && npx pod-install` and suddenly this started happening. no packages got upgraded or anything

**Comment by huzaifa3115** [comment]
Adding `useLegacyImplementation={false}` work for me

here is an example
   ```
 <Drawer.Navigator 
      initialRouteName="Todo"
      drawerContent={}
      useLegacyImplementation={false}
    >
      <Drawer.Screen name="navigation-tabs" component={tabs} {...props}/>
    </Drawer.Navigator>
```

**Comment by bdtren** [comment]
I replicated this issue with react-native-reanimated `3.6.1`. It working fine after I rolled back to `3.5.4`

**Comment by SujayST** [comment]
Just use useLegacyImplementation={false}

**Comment by oshilaRightS** [comment]
I cant add "useLegacyImplementation" as I am getting this error, 
`Type '{ children: Element[]; useLegacyImplementation: boolean; }' is not assignable to type 'IntrinsicAttributes & Omit<Props, "initialRouteName" | "children" | "layout" | "screenListeners" | "screenOptions" | "screenLayout" | "UNSTABLE_getStateForRouteNamesChange" | "id"> & DefaultRouterOptions<...> & { ...; } & { ...; }'.
  Property 'useLegacyImplementation' does not exist on type 'IntrinsicAttributes & Omit<Props, "initialRouteName" | "children" | "layout" | "screenListeners" | "screenOptions" | "screenLayout" | "UNSTABLE_getStateForRouteNamesChange" | "id"> & DefaultRouterOptions<...> & { ...; } & { ...; }'.ts(2322)
(property) useLegacyImplementation: boolean`

these are the versions I am using,

`    "react": "18.3.1",
    "react-dom": "18.3.1",
    "react-native": "0.76.2",
    "react-native-gesture-handler": "~2.20.2",
    "react-native-reanimated": "~3.16.1",
    "react-native-safe-area-context": "4.12.0",
    "react-native-screens": "~4.1.0",
    "react-native-svg": "15.8.0",
    "react-native-web": "~0.19.13",
    "react-native-webview": "13.12.4"
    "@react-native/metro-config": "^0.76.3",
    "@react-navigation/bottom-tabs": "^7.0.0",
    "@react-navigation/devtools": "^7.0.14",
    "@react-navigation/drawer": "^7.0.18",
    "@react-navigation/native": "^7.0.13",
    "@react-navigation/stack": "^7.0.18",`

**Comment by summerkiflain** [comment]
This is still a problem even with reanimated v4, when using drawer v6 in an expo sdk 54 app.
