### ISSUE TITLE
material-top-tabs slow render

### ISSUE THREAD

**Issue by TomCorvus** [react-navigation/react-navigation#11490]
### Current behavior

on mount, there are some milliseconds during which the material-top-tabs doesn't display.
On a fresh install, you can see it rapidly, but when on your screen, you have multiple API calls for example, this problem occurs for many seconds.

https://github.com/react-navigation/react-navigation/assets/3451011/b7324584-6ada-43c9-b962-a068689019d2

https://github.com/react-navigation/react-navigation/assets/3451011/59a799db-ca02-4905-a0ec-816b05bce8a5

### Expected behavior

Make it more efficient and maybe get a hook to know when tabs are fully mounted and displayed to know when to do greedy actions.

### Reproduction

https://github.com/TomCorvus/RNNavigationSlowRender

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [X] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.1.7
| @react-navigation/bottom-tabs          |
| @react-navigation/drawer               |
| @react-navigation/material-top-tabs    | 6.6.3
| @react-navigation/stack                |
| @react-navigation/native-stack         |
| react-native-safe-area-context         |
| react-native-screens                   |
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native-tab-view                  | 3.5.2
| react-native-pager-view                | 6.2.0
| react-native                           | 0.72.3
| expo                                   |
| node                                   | 18.12.0
| npm or yarn                            | 1.22.10

**Comment by okwasniewski** [comment]
Hey, this is related to the ongoing refactor of tab-view to address issues with poor performance when used together with material-top-tabs. If you want, a quick solution you can use `react-native-tab-view` without material-top-tabs for now.  

I've created an RFC that describes the new approach [here](https://github.com/react-navigation/rfcs/pull/88). The new API still needs some work, so I will keep this issue open until the release of a new version with the refactored API.

**Comment by TomCorvus** [comment]
Hi @okwasniewski,
thanks for your help.

For now, I can wait improvements on material-top-tabs and react-native-tab-view relationships.
Do you have an idea about when these improvements will be released? Or the priority against the others issues?

Thanks

**Comment by TomCorvus** [comment]
I try react-native-tab-view without material-top-tabs but the problem is the same.
When API calls are over, the TabView appears or the TabView content appears to be exact.

https://github.com/react-navigation/react-navigation/assets/3451011/9262cfba-2384-41fb-93c4-4338a332953f

I tried to encapsulate tabview navigator with a View to get onLayout prop and get a state to know when TabView is fully mounted before calling API.

It's better than before but not fully clean. There are some milliseconds before the content of the TabView appears.

is there no way to get onLayout prop on navigator?
Do you think it is a good solution?

Thanks

**Comment by krunalinfynno** [comment]
Getting Same issue after updating react native and react navigation

**Comment by lvlrSajjad** [comment]
![image](https://github.com/react-navigation/react-navigation/assets/42815758/9131895f-0afe-4e57-82f7-342630eb35c8)
Same issue it takes a few seconds for top tabs to get rendered for the first time.
Till then we can only see the underline

**Comment by mthomas100** [comment]
Has anyone made progress on this? Getting the same issue on react native 0.73. Happens with v5 and v6.

**Comment by josegiufrida** [comment]
Same issue after upgrading from react-native 0.71.7 to 0.73.8

```
"@react-navigation/material-top-tabs": "6.6.13",
"@react-navigation/native": "6.1.17",
"@react-navigation/native-stack": "6.9.26",
```

**Comment by rizikolik** [comment]
> ![image](https://private-user-images.githubusercontent.com/42815758/305185130-9131895f-0afe-4e57-82f7-342630eb35c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxNTU1MTEsIm5iZiI6MTcyNjE1NTIxMSwicGF0aCI6Ii80MjgxNTc1OC8zMDUxODUxMzAtOTEzMTg5NWYtMGFmZS00ZTU3LTgyZjctMzQyNjMwZWIzNWM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDE1MzMzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzNzczY2Q2YmRkYzAxY2VmYjViMGI1Zjg3OTFlMGViODJhYzI3MDdhZWE1NjFhOTJkYzI2Njc4ODAwYjg2MzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JK69XjEM7GceVKkuUULEKBK-mPa19Scn8MQWxiR4q8k) Same issue it takes a few seconds for top tabs to get rendered for the first time. Till then we can only see the underline

Is there any solution for this ?
I am getting the exact same error.

**Comment by rizikolik** [comment]
@okwasniewski ,is there any plan to fix this issue ?
