### ISSUE TITLE
[iOS][react-native-tab-view] The initial tab index does not work in react-native-modal on iOS

### ISSUE THREAD

**Issue by lchenfox** [react-navigation/react-navigation#11492]
### Current behavior

The intial tab index setting does not work in `react-native-modal` on iOS.

Code snippets

```
import React, { useState } from 'react';
import { View, TouchableOpacity, Text } from 'react-native';
import Modal from 'react-native-modal';
import { TabBar, TabView } from "react-native-tab-view";

const FirstRoute = props => (
	<View style={{ flex: 1, backgroundColor: '#ff4081' }}>
		<TouchableOpacity onPress={props.hide}>
			<Text style={{ color: 'white', fontSize: 30, marginTop: 50 }}>Hide modal</Text>
		</TouchableOpacity>
	</View>
);

const SecondRoute = props => (
	<View style={{ flex: 1, backgroundColor: '#673ab7' }}>
		<TouchableOpacity onPress={props.hide}>
			<Text style={{ color: 'white', fontSize: 30, marginTop: 50 }}>Hide modal</Text>
		</TouchableOpacity>
	</View>
);

const TabViewExample = () => {
	const [visible, setVisible] = useState(false);
	const renderScene = ({ route }) => {
		switch (route.key) {
			case 'first':
				return <FirstRoute hide={() => setVisible(false)} />;
			case 'second':
				return <SecondRoute hide={() => setVisible(false)} />;
			default:
				return null;
		}
	};
	return (
		<View style={{ flex: 1, backgroundColor: 'white' }}>
			<TouchableOpacity onPress={() => setVisible(true)}>
				<Text style={{ marginTop: 100 }}>Show date</Text>
			</TouchableOpacity>
			<Modal isVisible={visible}>
				<TabView
					style={{ flex: 1, backgroundColor: 'white' }}
					navigationState={{
						index: 1,
						routes: [
							{ key: "first", title: "Year" },
							{ key: "second", title: "Month" },
						],
					}}
					renderScene={renderScene}
					swipeEnabled={false}
					renderTabBar={props => <TabBar{...props} pressColor={'#E2E6EA'} />}
					initialLayout={{ width: 350 }}
				/>
			</Modal>
		</View>
	);
};

export default TabViewExample;
```

```
"react-native-modal": "^13.0.1"
```

Screenshot
![IMG_B7C2846C23EE-1](https://github.com/react-navigation/react-navigation/assets/22851821/747a389b-6c11-4542-8752-b764091c2013)

The initial tab index is `1`(i.e. the second tab is selected by default).

### Expected behavior

The intial tab index setting work as expected in `react-native-modal` on iOS.

### Reproduction

https://github.com/lchenfox/react-native-tab-view-issue

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [X] react-native-tab-view

### Environment

- [yes] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.1.2
| @react-navigation/bottom-tabs          |
| @react-navigation/drawer               |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                |
| @react-navigation/native-stack         | 6.9.8
| react-native-safe-area-context         | 4.4.1
| react-native-screens                   | 3.18.2
| react-native-gesture-handler           | 2.9.0
| react-native-reanimated                | 3.3.0
| react-native-tab-view                  | 3.5.2
| react-native-pager-view                | 6.1.2
| react-native                           | 0.72.0
| expo                                   |
| node                                   | 20.4.0
| npm or yarn                            | npm

**Comment by lchenfox** [comment]
> Couldn't find version numbers for the following packages in the issue:
> 
> * `@react-navigation/bottom-tabs`
> * `@react-navigation/drawer`
> * `@react-navigation/material-top-tabs`
> * `@react-navigation/stack`
> 
> Can you update the issue to include version numbers for those packages? The version numbers must match the format 1.2.3.
> 
> The versions mentioned in the issue for the following packages differ from the latest versions on npm:
> 
> * `@react-navigation/native` (found: `6.1.2`, latest: `6.1.7`)
> 
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?

I just use the following dependencies:

```
  "dependencies": {
    "react": "18.2.0",
    "react-native": "0.72.0",
    "react-native-modal": "^13.0.1",
    "react-native-pager-view": "^6.2.0",
    "react-native-tab-view": "^3.5.2"
  },
```
So it's not related to the `react-navigation` dependencies metioned above.

**Comment by okwasniewski** [comment]
Hey, 

I've been debugging this issue for quite a while today. I have a workaround that you can use in your code I know it's not great but unfortunately I don't think that it's solvable on tab-view side. Firstly, rendering tab-view itself (without `react-native-modal` or when using built-in RN Modal) always results in selecting correct index, so the issue is clearly happening only when used in conjunction.

I saw that `react-native-modal` has a lot of animations happening at the same time, therefore it has impact on the RN bridge  - which may cause why TabView's animations are not set correctly but Im not sure if that's actually the case because I didnt dig into react-native-modal code that much. 

What I've observed is when we delay TabView rendering for 0ms (so it's called after the next iteration of JS event loop) it's rendered correctly. Here is a component you can use: 


```tsx
const Delayed = ({ children, waitBeforeShow = 0 }: Props) => {
  const [isShown, setIsShown] = useState(false);

  useEffect(() => {
    const timer = setTimeout(() => {
      setIsShown(true);
    }, waitBeforeShow);
    return () => clearTimeout(timer);
  }, [waitBeforeShow]);

  return isShown ? children : null;
};
```
And then you can just wrap TabView with it: 
```tsx
//...
<Delayed>
          <TabView
            navigationState={{
              index: 1,
              routes: [
                { key: "first", title: "Year" },
                { key: "second", title: "Month" },
              ],
            }}
          />
        </Delayed>
``` 
        
Hope that helps with solving your issue! :)

**Comment by lchenfox** [comment]
@okwasniewski Thank U so much. It does work well now. 

However, maybe it's not related to `react-native-modal`, it also happens when using built-in RN Modal. After many attempts, I changed the `react-native-modal` source code(`node_modules/react-native-modal/dist/modal.js`) as follows:

```
import * as React from 'react';
import {Modal, View} from 'react-native';
import * as PropTypes from 'prop-types';
import styles from './modal.style';

export class ReactNativeModal extends React.Component {

    constructor(props) {
        super(props);
        this.state = {
            isVisible: false,
        };
    }

    shouldComponentUpdate(nextProps, nextState, nextContext) {
        if (nextProps.isVisible !== this.props.isVisible) {
            this.setState({isVisible: nextProps.isVisible}); 
        }
        return true;
    }

    render() {
        const {
            children,
            style,
            isVisible,
        } = this.props;
        const computedStyle = [
            {margin: 20,},
            styles.content,
            style,
        ];
        const containerView = React.createElement(View, Object.assign({}, {style: [computedStyle]}, {}), children);
        return (React.createElement(Modal, {visible: isVisible}, containerView));
    }
}

export default ReactNativeModal;
```

Still, this issue also exists. So, it may not be related to `animation` used in `react-native-modal`. But I still cannot figure out what  happend. Now I will add the `delay` operation as described by you, it can solve my problem temperarily. Thank u again.
