### ISSUE TITLE
Unable to resolve "@react-navigation/native" from "App.tsx"

### ISSUE THREAD

**Issue by MatthewOng3** [react-navigation/react-navigation#11507]
### Current behavior

Hi ! I am creating a react native project on expo, when I run npx expo to start the project, bundling fails because it says @react-navigation/native can't be resolved, but I clearly installed it and it was working couple hours ago but I closed the program and rebooted it and suddenly there are issues so not sure what is going on.
Thanks!
Error Image:
![photo_6203904784344397527_y](https://github.com/react-navigation/react-navigation/assets/89276786/7f02be38-6026-4c51-ba15-203ae9068904)

Package.json
`
{
  "name": "food_folio",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "@react-navigation/bottom-tabs": "^6.5.8",
    "@react-navigation/native": "^6.1.7",
    "@react-navigation/native-stack": "^6.9.13",
    "expo": "~49.0.5",
    "expo-status-bar": "~1.6.0",
    "firebase": "^10.1.0",
    "native-base": "^3.4.28",
    "react": "^18.2.0",
    "react-native": "0.72.3",
    "react-native-ionicons": "^4.6.5",
    "react-native-safe-area-context": "4.6.3",
    "react-native-screens": "~3.22.0",
    "react-native-svg": "13.9.0"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@types/react": "~18.2.14",
    "typescript": "^5.1.3"
  },
  "private": true
}

`

### Expected behavior

It should bundle correctly and the screens should be displayed

### Reproduction

https://github.com/MatthewOng3/Food_Folio

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [x] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [x] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |  6.1.7
| @react-navigation/bottom-tabs          | 6.5.8
| @react-navigation/native-stack         | 6.9.13
| react-native-safe-area-context         | 4.6.3
| react-native-screens                   |  ~3.22.9
| react-native                           | 0.72.3
| expo                                   | ~49.0.5
| node                                   |  18.14.1
| npm or yarn                            | npm

**Comment by MatthewOng3** [comment]
Whoops made a mistake but fixed it, I indicated the wrong packages used

**Comment by MatthewOng3** [comment]
hi sorry for the late response! Yeap it works thank you so much!

**Comment by Adill00** [comment]
> hi sorry for the late response! Yeap it works thank you so much!

I am having the same issue over here, would you give detailed explanation on how you solved it?
