### ISSUE TITLE
Android: screen overflow when headerShown: true 

### ISSUE THREAD

**Issue by prince-sugarfit** [react-navigation/react-navigation#11504]
### Current behavior

On Android, Bottom component is overflowing and hidden behind navigation bar

iOS it is working as expected

![Screenshot_1690444694](https://github.com/react-navigation/react-navigation/assets/96161907/2c772484-fd07-4b9f-9a03-c16fd1a069c4)

### Expected behavior

Something like this, where full component (at bottom) should be visible

![simulator_screenshot_D70181FD-144E-49CA-8243-59C6CAC9C475](https://github.com/react-navigation/react-navigation/assets/96161907/01e8e4cf-1d12-42f9-b6fb-114939526c1d)

### Reproduction

https://github.com/prince-sugarfit/RN72

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- ['react-native-tab-view'] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | "^6.1.7" |
| @react-navigation/bottom-tabs          | "^6.5.8" |
| @react-navigation/stack                | ""6.3.17" |
| @react-navigation/native-stack         | "6.9.13" |
| react-native-safe-area-context         | "^4.7.1" |
| react-native-screens                   | "^3.22.1" |
| react-native-gesture-handler           | "^2.12.0" |
| react-native-reanimated                | "^1.13.1" |
| react-native-pager-view                | "^6.2.0" |
| react-native                           | "0.72.3" |
| node                                   | "16.14.0" |
| yarn                            | "1.22.17" |

**Comment by prince-sugarfit** [comment]
Not using `react-native-tab-view`, updated an issue

**Comment by prince-sugarfit** [comment]
Can't understand why it was closed. It is a bug, not a question

**Comment by Aure77** [comment]
Not a react-navigaiton bug. 
Your screen has `position: absolute` + `height: 100` + `bottom: 0` = your view is bounded at what you configured...
https://github.com/prince-sugarfit/RN72/blob/master/App.tsx#L30

replace with:
`flex: 1`
to let your screen use all available space....

**Comment by prince-sugarfit** [comment]
@Aure77 Screen already has `flex: 1`, child text inside the screen has absolute position which is correct I think

**Comment by Aure77** [comment]
OK. You need to read doc about safe area:
https://reactnavigation.org/docs/handling-safe-area/
