### ISSUE TITLE
headerTitleStyle is not applied when using a custom headerTitle on iOS

### ISSUE THREAD

**Issue by febis001** [react-navigation/react-navigation#11500]
### Current behavior

When using a custom `headerTitle` in React Navigation on iOS, the `headerTitleStyle` property appears to be ignored. This results in the custom `headerTitle` not receiving any styles that are set through `headerTitleStyle`. The callback for `headerTitle` only contains `children` and `tintColor` properties, but does not include the style property which should be set by `headerTitleStyle`. This behavior leads to a situation where it's not possible to control the styling of the custom `headerTitle` through the `headerTitleStyle` property, which is not the expected or desired behavior.

Note: The reproduction example is just a modified snack linked in the documentation. In my project im using an expo development build with the most recent versions. The problem occurs on both.

### Expected behavior

When using a customized `headerTitle` the `headerTitleStyle` property should still apply because it appears that the intended behavior is that the style is passed to the callback (https://github.com/react-navigation/react-navigation/blob/%40react-navigation/elements%401.3.18/packages/elements/src/Header/Header.tsx#L274).

### Reproduction

https://snack.expo.dev/@febis001/header-title

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.1.7
| @react-navigation/bottom-tabs          | 6.5.8
| @react-navigation/drawer               | 6.6.3
| @react-navigation/stack                | 6.3.17
| @react-navigation/native-stack         | 6.9.13
| react-native-safe-area-context         | 4.7.1
| react-native-screens                   | 3.23.0
| react-native-gesture-handler           | 2.12.0
| react-native-reanimated                | 3.3.0
| react-native                           | 0.72.3
| expo                                   | 49.0.5
| node                                   | 18.16.1
| npm or yarn                            | 9.5.1

**Comment by febis001** [comment]
I think I have just identified my thinking mistake. There is a difference between the `headerTitle` from _elements_ and the `headerTitle` from _native-stack_. And I am in the context of native-stack (https://github.com/react-navigation/react-navigation/blob/main/packages/native-stack/src/types.tsx#L275)

**Comment by kyawthura-gg** [comment]
You're using both `title` and `headerTitle`. Closing since error is in your code.

**Comment by febis001** [comment]
That‘s wrong. There is no error in using both. Just have a look at the code. The title is used as the children of the headerTitle. The titleText ist build by the getHeaderTitle method which checks if headerText is a string and if not then uses title. And that isn‘t even related to the point of the options of headerTitle
