### ISSUE TITLE
Issue in reanimated 3.4.1 with drawer

### ISSUE THREAD

**Issue by luvnishCapgemini** [react-navigation/react-navigation#11505]
### Current behavior

TypeError: 0, _$$_REQUIRE(_dependencyMap[5], "react/jsx-runtime").jsx is not a function (it is undefined)

This error is located at:
    in MaybeScreenContainer (created by Drawer)
    in RCTView (created by View)
    in View (created by Drawer)
    in RCTView (created by View)
    in View (created by AnimatedComponent(View))
    in AnimatedComponent(View)
    in Unknown (created by Drawer)
    in RCTView (created by View)
    in View (created by AnimatedComponent(View))
    in AnimatedComponent(View)
    in Unknown (created by PanGestureHandler)
    in PanGestureHandler (created by Drawer)
    in Drawer (created by DrawerViewBase)
    in DrawerViewBase (created by DrawerView)
    in RNGestureHandlerRootView (created by GestureHandlerRootView)
    in GestureHandlerRootView (created by DrawerView)
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by SafeAreaInsetsContext)
    in SafeAreaProviderCompat (created by DrawerView)
    in DrawerView (created by DrawerNavigator)
    in PreventRemoveProvider (created by NavigationContent)
    in NavigationContent
    in Unknown (created by DrawerNavigator)
    in DrawerNavigator (created by MyDrawer)
    in MyDrawer (created by App)
    in EnsureSingleNavigator
    in BaseNavigationContainer
    in ThemeProvider
    in NavigationContainerInner (created by App)
    in App
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in Drawer(RootComponent), js engine: hermes
    
   After this fix: https://github.com/react-navigation/react-navigation/issues/11498, above issue rises for both Android & iOS.
   
   Using:
   NewArchitecture with
   "@react-navigation/drawer": "6.6.3",
    "@react-navigation/native": "^6.1.7",
    "react": "18.2.0",
    "react-native": "0.72.3",
    "react-native-gesture-handler": "^2.12.0",
    "react-native-reanimated": "3.4.1",
    "react-native-safe-area-context": "^4.7.1"

### Expected behavior

Normal operation

### Reproduction

none

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

NewArchitecture enabled with 

"@react-navigation/drawer": "6.6.3",
"@react-navigation/native": "^6.1.7",
"react": "18.2.0",
"react-native": "0.72.3",
"react-native-gesture-handler": "^2.12.0",
"react-native-reanimated": "3.4.1",
"react-native-safe-area-context": "^4.7.1"

**Comment by luvnishCapgemini** [comment]
Hi @kacperkapusciak 

Please provide a solution. Thanks.

**Comment by migueldaipre** [comment]
Add a minimal reproducible example.

**Comment by luvnishCapgemini** [comment]
Hi @migueldaipre 
I created an example and pushed it on GitHub. Please check with https://github.com/luvnishCapgemini/FabricDrawer

**Comment by NoodleOfDeath** [comment]
> Hi @migueldaipre I created an example and pushed it on GitHub. Please check with https://github.com/luvnishCapgemini/FabricDrawer

Having this issue too... omg keeps saying "_IS_FABRIC doesn't exist" and "cannot read property abs of undefined". How even does `require('...').abs === undefined`, at least use an optional? `require(...)?.abs === undefined`

**Comment by NoodleOfDeath** [comment]
@luvnishCapgemini I managed to solve this problem by downgrading back to `^3.3.0`

**Comment by luvnishCapgemini** [comment]
Hi @NoodleOfDeath 
as per your suggestionI tried to downgraded 3.3.0 but I am still facing the same issue which I reported in question section.
Did you enable Fabric?

**Comment by luvnishCapgemini** [comment]
Hi @migueldaipre 
Did you get chance to look into reproducible example?

https://github.com/luvnishCapgemini/FabricDrawer

**Comment by NoodleOfDeath** [comment]
@luvnishCapgemini have you also tried reverting your yarn.lock and all other packages to the last successful build? Frustrated the hell out of me, but that's what it took for me

**Comment by luvnishCapgemini** [comment]
@NoodleOfDeath 
It wasn't working for me anyhow. I created an example and that's not working for me. I tried couple of modifications but nothing has worked. 
@migueldaipre  @kacperkapusciak

**Comment by migueldaipre** [comment]
You haven't followed the drawer/native stack setup steps. [Link](https://reactnavigation.org/docs/getting-started#installing-dependencies-into-a-bare-react-native-project)

react-native-screens is required. Closing.

**Comment by NoodleOfDeath** [comment]
@luvnishCapgemini you need to make each of your tab components inside of `Screen` components rather than `View` components.

**Comment by skizzo** [comment]
> @luvnishCapgemini you need to make each of your screen render components inside of `Screen` components rather than `View` components: lines 8, 16, 24 of your [`App.js`](https://github.com/luvnishCapgemini/FabricDrawer/blob/4254deb7900a21518c6454c5c477cb96ebdca2ab/App.js#L8)
> 
> ```js
> import { Screen, Text, View } from 'react-native';
> 
> function FeedScreen() {
>   return (
>     <Screen>
>       <View style={{ flexGrow: 1 }}>
>         <Text>Feed</Text>
>       </View>
>     </Screen>
>   );
> }
> ```

No idea what you are talking about..

<img width="435" alt="Screenshot 2023-09-15 at 13 44 41" src="https://github.com/react-navigation/react-navigation/assets/2892572/3b59edbe-5c86-4b56-8dca-da3e2de6d89b">

**Comment by LucaB01** [comment]
After installing
`npm install react-native-reanimated react-native-gesture-handler react-native-screens react-native-safe-area-context @react-native-community/masked-view`
It worked for me
