### ISSUE TITLE
Screens loaded with React.lazy within nested navigator refreshes when setting params

### ISSUE THREAD

**Issue by mtourj** [react-navigation/react-navigation#11512]
### Current behavior

When you have a screen within a nested navigator, and that screen is dynamically loaded using import(), React.lazy and Suspense, calling `navigation.setParams()` causes that screen to re-mount entirely, losing its state.

To clarify the use case, this is a search screen with filters, and when filters change, I want to set them in params so user can refresh the screen and retain state.

If the screen is imported statically, it works fine. If the screen is not within a nested navigator, it works fine. However, a combination of these conditions seems to cause a problem within react-navigation. Please refer to the attached snack for a repro.

### Expected behavior

I expect setParams not to unmount my screen and cause it to lose its state when it is 1) dynamically imported and 2) rendered within a nested navigator.

Note: I have only tested this in the browser, so I'm not sure if this carries over to the native side.

### Reproduction

https://snack.expo.dev/@mohammadtourj/react-navigation-weirdness

### Platform

- [ ] Android
- [ ] iOS
- [X] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [x] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [X] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.1.6
| @react-navigation/bottom-tabs          | 6.5.7
| @react-navigation/stack                | 6.3.16
| react-native-safe-area-context         | 4.5.0
| react-native-screens                   | 3.20.0
| react-native-gesture-handler           | 2.9.0
| react-native-pager-view                | 6.1.2
| react-native                           | 0.71.8
| expo                                   | 48.0.0
| node                                   | 18.12.1
| npm or yarn                            | 8.19.2

**Comment by mtourj** [comment]
Yes, the issue does persist. The snack uses the latest versions of these packages.

**Comment by kyawthura-gg** [comment]
Hey, thanks for reporting issue. I just checked the snack and your `useEffect` is running infinite. It's the reason why it causes re-render too.

**Comment by mtourj** [comment]
Oops, I made a mistake in the snack. And the strange behavior was because I was passing createScreen(ExampleScreen) into the `component`, not something wrong with the package. Sorry about that!
