### ISSUE TITLE
Native Stack doesn't update status bar when opening a modal

### ISSUE THREAD

**Issue by CircuitSacul** [react-navigation/react-navigation#11513]
### Current behavior

In the following conditions:
 - on iOS
 - in light mode
 - with a modal screen open

The status bar becomes invisible, because the text is the same color is the background (black). There was [a similar issue](https://github.com/react-navigation/react-navigation/issues/7916) opened for `stack`, and it was fixed, but it seems it was never fixed for `native-stack`.

https://github.com/react-navigation/react-navigation/assets/55721663/2de4cb0c-f7b6-431f-b8c0-e9a27cf59832

### Expected behavior

The status bar should invert itself based on the background color.

### Reproduction

https://snack.expo.dev/@circuitsacul/stack-navigator-%7C-react-navigation?platform=ios

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.0.10
| @react-navigation/native-stack         | 6.6.1
| react-native-screens                   | 3.20.0
| react-native-safe-area-context         | 4.5.0

**Comment by CircuitSacul** [comment]
It does. Version 6.1.7 fails to install on snack, but that is the version I am using locally.

**Comment by michaelkremenetsky** [comment]
I was able to fix this by setting `UIViewControllerBasedStatusBarAppearance: true` and removing all the StatusBar components around that app.

**Comment by CircuitSacul** [comment]
> I was able to fix this by setting `UIViewControllerBasedStatusBarAppearance: true` in `infoPlist` and removing all the StatusBar components around that app.

This works for me also. I'm using a managed workflow, so I guess the question is, how do I get prebuild to set this value to true? Currently it's adding it with a value of `false`.

**Comment by michaelkremenetsky** [comment]
You can set 
```typescript
  ios: {
    infoPlist: {
      UIViewControllerBasedStatusBarAppearance: true,
    },
  },
```
in the expo config

**Comment by c-info** [comment]
> I was able to fix this by setting `UIViewControllerBasedStatusBarAppearance: true` in `infoPlist` and removing all the StatusBar components around that app.

We need to remove the StatusBar component and use the StatusBar configuration from the navigator to resolve the issue.

**Comment by donni106** [comment]
> > I was able to fix this by setting `UIViewControllerBasedStatusBarAppearance: true` in `infoPlist` and removing all the StatusBar components around that app.
> 
> We need to remove the StatusBar component and use the StatusBar configuration from the navigator to resolve the issue.

Works for me just with removing `StatusBar`, without adjusting `infoPlist`.

**Comment by donni106** [comment]
The additional adjustment in `infoPlist` seems to be needed for older iOS.
