### ISSUE TITLE
react native hardwareBackbutton cause minimize app from Android >= 10

### ISSUE THREAD

**Issue by fukemy** [react-navigation/react-navigation#11524]
### Current behavior

I dont know how to describe the problem by codes, but my hardwareBackbutton work normally for android devices with OS < 10. Another cause minimize app.

With pop() function from navigation, it's work. Only problem with hardwareBackbutton.

I am using native stack:

```
 "@react-navigation/bottom-tabs": "^6.3.1",
    "@react-navigation/material-bottom-tabs": "^6.2.1",
    "@react-navigation/native": "^6.1.6",
    "@react-navigation/native-stack": "^6.9.12",
    "@react-navigation/stack": "^6.3.7",
    "react": "^18.2.0",
    "react-native": "^0.71.8",


...


export const Stack = createNativeStackNavigator()
```

here is the video i captured: [Video here](https://vimeo.com/851681998)

### Expected behavior

back button work as navigation.pop()

### Reproduction

no repo

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |
| @react-navigation/bottom-tabs          |
| @react-navigation/drawer               |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                |
| @react-navigation/native-stack         |
| react-native-safe-area-context         |
| react-native-screens                   |
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           |
| expo                                   |
| node                                   |
| npm or yarn                            |

**Comment by Dhiraj-j** [comment]
I have facing same issue when I got update android version 13

**Comment by alexejh** [comment]
For me removing `android:enableOnBackInvokedCallback="true"` from the Manifest has fixed the issue.


https://developer.android.com/guide/navigation/custom-back/predictive-back-gesture#opt-predictive

**Comment by baddda** [comment]
For me removing android:enableOnBackInvokedCallback="true" from the Manifest has fixed the issue.

https://developer.android.com/guide/navigation/custom-back/predictive-back-gesture#opt-predictive

**Comment by SaulSilver** [comment]
Per documentation: https://reactnavigation.org/docs/getting-started/#opting-out-of-predictive-back-on-android

> React Navigation doesn't yet support Android's predictive back gesture. Disabling it is necessary for the system back gesture to work properly with React Navigation.
> 
> To opt out, in AndroidManifest.xml, in the <application> tag (or <activity> tag to opt-out at activity level), set the android:enableOnBackInvokedCallback flag to false:
> 
> ```
> <application
>   android:enableOnBackInvokedCallback="false"
>   >
>   
> </application>
> ```
