### ISSUE TITLE
ScrollView randomly scrolls after refresh in iOS when headerLargeTitle:true

### ISSUE THREAD

**Issue by federunco** [react-navigation/react-navigation#11527]
### Current behavior

In iOS, when a ScrollView content is updated after a pull to refresh, the content view is randomly scrolled down. This happens when a Redux state is used as the refreshing param for the RefreshControl and the Screen headerLargeTitle option is set to true. 
If a RN state is used as the refreshing variable instead, the ScrollView gets bugged only when the refresh is invoked by a navigator listener (e.g. refresh on focus)   

![RPReplay_Final1691274049_MP4_AdobeExpress](https://github.com/react-navigation/react-navigation/assets/37912651/fef55d8a-598b-4389-b40b-01d3dee1984d)

### Expected behavior

No ScrollView jump after refresh:

![image](https://iosexample.com/content/images/2019/11/ios.gif)
[image source](https://iosexample.com/refreshui-provide-native-refresh-control-to-swiftui/)

### Reproduction

https://snack.expo.dev/@federunco/rn-scrollviewbug

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native              | 6.1.7
| @react-navigation/native-stack               | 6.9.13
| react-native-safe-area-context         | 4.7.1
| react-native-screens                   | 3.23.0
| react-native                           | 0.72.3
| node                                   | v16.17.0
| npm                            | 8.15.0

**Comment by kyawthura-gg** [comment]
Hey, thanks for reporting issue. You have added `redux` and it makes us hard to debug. Can you please remove that library and update the repo? This code doesn't show issue as you mentioned above: 
<img width="513" alt="Screen Shot 2023-08-15 at 6 14 56 PM" src="https://github.com/react-navigation/react-navigation/assets/44088165/3524adae-f142-455a-bbba-a2852978478f">

**Comment by kyawthura-gg** [comment]
Hey, thanks again for providing repo. Closing since this is not related to React Navigation.
