### ISSUE TITLE
NavigationContainer problem

### ISSUE THREAD

**Issue by cembicakci** [react-navigation/react-navigation#11529]
### Current behavior

i am getting 'couldn't find a navigation object. is your component inside navigationcontainer?' error even though i have in my AppNavigation page.

### Expected behavior

Due to my components inseide navigation container, i should not get this error or i should get more specific error.

### Reproduction

Not able to reproduce the issue in snack

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |
| @react-navigation/bottom-tabs          |
| @react-navigation/drawer               |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                |
| @react-navigation/native-stack         |
| react-native-safe-area-context         |
| react-native-screens                   |
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           |
| expo                                   |
| node                                   |
| npm or yarn                            |

**Comment by cembicakci** [comment]
i solved this issue by not using useNavigation on the same page i use NavigationContainer. It does not allow to use navigation because of the app is not loaded yet. You can navigate by giving ref to navigationContainer and ref.navigate() property.

**Comment by lhguerra** [comment]
@cembicakci did you get it to work?

**Comment by taiwonaf** [comment]
Just encountered this same issue, after upgrading to the latest sdk

**Comment by zulqarnain004** [comment]
I encountered this same issue, after installing the npm install expo-router
