### ISSUE TITLE
Custom Header doesn't update props

### ISSUE THREAD

**Issue by alexghi** [react-navigation/react-navigation#11538]
### Current behavior

I have a custom header component that I want to update with a new name, buttons, icons. The update should take place whenever I'm switching between the screens using the bottom tabs. The screens themselves update. also the custom tabbar navigation updates with the new route, but somehow the header doesn't gets updated and I wonder if it's the way I'm doing things, or is it something else (a bug / misunderstanding)

### Expected behavior

I would expect the custom header component should update when changing routes.

I'm attaching a reproduction code where it's all plain and simple

### Reproduction

https://snack.expo.dev/HvDIzXY3O

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.1.7
| @react-navigation/bottom-tabs          | 6.5.8
| @react-navigation/material-top-tabs    | 6.6.3
| @react-navigation/stack                | 6.3.17
| @react-navigation/native-stack         | 6.9.13
| react-native-safe-area-context         | 4.7.1
| react-native-screens                   | 3.24.0
| react-native-gesture-handler           | 2.12.1
| react-native-reanimated                | 3.4.2
| react-native-tab-view                  | 3.5.2
| react-native-pager-view                | 5.4.25
| react-native                           | 0.72.4

**Comment by alexghi** [comment]
I'm attaching a video.
I would expect that when navigating from first screen to second the props change so that the current screen header title would also change to that of the screen (first / second), but it doesn't

https://github.com/react-navigation/react-navigation/assets/11394898/9b669833-fd25-4ff7-b61a-a5f1f74ed5d6

**Comment by kyawthura-gg** [comment]
You can use [useRoute](https://reactnavigation.org/docs/use-route/) to get current screen name or other param.

**Comment by satya164** [comment]
if you want to show tab name then you need to use the tab navigator header, not header of parent stack.

https://reactnavigation.org/docs/nesting-navigators/#each-navigator-has-its-own-options

**Comment by alexghi** [comment]
I want to use more than just the tabname. My whole header is custom, with different buttons and icons. Is this achievable with suggested navigator?

**Comment by alexghi** [comment]
I was able to achieve the expected functionality in the previous version (5.x) with the code above. After I updated to 6.x I'm having troubles achieving this. I'm already using tab navigator for tabs and the whole screen. I **don't** want to render a new header on bottom tab change

**Comment by alexghi** [comment]
> You can use [useRoute](https://reactnavigation.org/docs/use-route/) to get current screen name or other param.

When using this, or navigationState for the matter, I still get the `Initial` Route, just like nothing changed. I presume this is because the parent never changes, only the children?
