### ISSUE TITLE
inactiveColor issue with 4 bottom Tabs #8323

### ISSUE THREAD

**Issue by dheeraj539** [react-navigation/react-navigation#11540]
### Current behavior

I currently want to implement a material bottom tab navigator with 4 tabs.
When only three tabs were present the inactiveColor would work perfectly for all the tabs. When i added the 4th new tab, the inactiveColor prop is suddenly failing to give the color to the inactive tabs. the active tab's label and icon would get correctly colored. And the label isnt showing up as well.

![image](https://github.com/react-navigation/react-navigation/assets/25552328/d8846420-c137-4335-b6b2-64eedac7bbef)

### Expected behavior

Expected Behaviour would be that all the 3 inactive tabs and the 4th active tabs would properly get their respective colors for the icons and labels both.

![image](https://github.com/react-navigation/react-navigation/assets/25552328/5e89bb64-ba52-4f3a-88a1-8d4f337f0abb)

Should be the same for 4 tabs. The above image is when I used only 3 tabs.

### Reproduction

https://snack.expo.dev/@dheeraj539/react-navigation

### Platform

- [ ] Android
- [ ] iOS
- [X] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
    "@expo/vector-icons"  |  "^13.0.0",
    "react-native-paper"  |  "^4.7.2",
    "react-native-screens"  |  "~3.20.0",
    "@react-navigation/stack"  |   "6.2.1",
    "react-native-reanimated"  |   "~2.14.4",
    "@react-navigation/drawer"  |   "6.4.1",
    "@react-navigation/native"  |   "6.0.10",
    "@react-navigation/elements"  |   "1.3.3",
    "react-native-gesture-handler"  |   "~2.9.0",
    "@react-navigation/bottom-tabs"  |   "6.3.1",
    "@react-navigation/native-stack"  |   "6.6.1",
    "react-native-safe-area-context"  |   "4.5.0",
    "@react-native-community/masked-view"  |   "*",
    "@react-navigation/material-bottom-tabs"  |   "6.2.1"

**Comment by dheeraj539** [comment]
Issue still exists in the latest versions

**Comment by satya164** [comment]
There's no `tabBarInactiveTintColor` option for material bottom tabs https://reactnavigation.org/docs/material-bottom-tab-navigator#options

**Comment by dheeraj539** [comment]
> https://snack.expo.dev/@dheeraj539/react-navigation



> There's no `tabBarInactiveTintColor` option for material bottom tabs https://reactnavigation.org/docs/material-bottom-tab-navigator#options

The issue exists even without the option tabBarInactiveTintColor.  
I have also updated the snack to replicate the same.

**Comment by satya164** [comment]
Please read the documentation thoroughly.
