### ISSUE TITLE
Failed to create a worklet. Did you forget to add Reanimated Babel plugin in babel.config.js? 

### ISSUE THREAD

**Issue by alejandro-geeksquare** [react-navigation/react-navigation#11545]
### Current behavior

I have deleted node_modules, ios and android folder. Cleared cache, restarted my computer but still getting the same error. Any ideas? Thank you so much. this problem appears when i try to start const Drawer = createDrawerNavigator() from "@react-navigation/drawer"

<img width="855" alt="Captura de pantalla 2023-08-18 a las 17 51 47" src="https://github.com/software-mansion/react-native-reanimated/assets/128458985/c0de80df-fd99-4346-80d2-aa883e495300">
<img width="855" alt="Captura de pantalla 2023-08-18 a las 17 51 37" src="https://github.com/software-mansion/react-native-reanimated/assets/128458985/ba249b35-d452-405f-8be7-855c4830f8b8">
<img width="855" alt="Captura de pantalla 2023-08-18 a las 17 50 38" src="https://github.com/software-mansion/react-native-reanimated/assets/128458985/27d7d720-dca9-4828-be3c-8174fa93e9b4">
<img width="421" alt="Captura de pantalla 2023-08-18 a las 17 52 23" src="https://github.com/software-mansion/react-native-reanimated/assets/128458985/c10f7a6f-7923-4028-9640-2edff1694fb7">
<img width="1251" alt="Captura de pantalla 2023-08-18 a las 17 52 38" src="https://github.com/software-mansion/react-native-reanimated/assets/128458985/6e091209-a303-45a5-90a9-3f2be837c196">

### Expected behavior

Use Drawer Navigation

### Reproduction

const Drawer = createDrawerNavigator()

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |
| @react-navigation/bottom-tabs          |
| @react-navigation/drawer               |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                |
| @react-navigation/native-stack         |
| react-native-safe-area-context         |
| react-native-screens                   |
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           |
| expo                                   |
| node                                   |
| npm or yarn                            |

**Comment by HamoBoker** [comment]
Hi, i think you should set **useLegacyImplementation** prop to false

Check Docs

[Drawer navigator doc](https://reactnavigation.org/docs/drawer-navigator#uselegacyimplementation)

**Comment by alejandro-geeksquare** [comment]
@HamoBoker From what I read in the documentation the useLegacyImplementation property is added to the tag, but the error starts before adding the Drawer.Navigation or Drawer.Screen component simply at the time of executing the createDrawerNavigator function. I've tried adding the component and setting the createDrawerNavigator property to false, but it's still the same. :(

**Comment by alejandro-geeksquare** [comment]
<img width="647" alt="Captura de pantalla 2023-08-19 a las 19 14 33" src="https://github.com/react-navigation/react-navigation/assets/128458985/8a7c0405-4199-499b-997e-68c34f667df7">

**Comment by chuysb** [comment]
I'm having the same problem and the only way I could fix it is by adding this line to the babel.config.js file:

```
module.exports = function (api) {
  api.cache(true);
  return {
    presets: ["babel-preset-expo"],
    plugins: ["react-native-reanimated/plugin"], // added this line
  };
};

```

[Source](https://stackoverflow.com/a/69925121/173299)

**Comment by valn1** [comment]
why did you close the issue @alejandro-geeksquare ?
i am running into this issue purely because i tried adding drawer navigation to my app and it requires reanimated to work.
my babel file is correct but still the app fails to open and says `Failed to create a worklet.`
i tried everything but didnt manage to make it work

**Comment by alejandro-geeksquare** [comment]
> why did you close the issue @alejandro-geeksquare ? i am running into this issue purely because i tried adding drawer navigation to my app and it requires reanimated to work. my babel file is correct but still the app fails to open and says `Failed to create a worklet.` i tried everything but didnt manage to make it work

In my case the failure was due to the Babel file, which is why I closed it and had not added it correctly. Try deleting the Android Ios and node_modules folders and recreating them

**Comment by valn1** [comment]
sorry.
you're right, in my ccase tho, i had everything correct, but was running `npm start --reset-cache` instead of `npm start -- --reset-cache`
