### ISSUE TITLE
createNativeStackNavigator does not work

### ISSUE THREAD

**Issue by simoneeek** [react-navigation/react-navigation#11552]
### Current behavior

I'm using React Native Navigation without Expo. When I use createNativeStackNavigator and try to step back from some screen, the app crashes. The only way I can fix this is to use createStackNavigator...
[https://imgur.com/a/k8nYJED](url)

### Expected behavior

i expecting same functionality with createNativeStackNavigator like with createStackNavigator.

### Reproduction

x

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |6.1.7
| @react-navigation/stack                |6.3.17
| @react-navigation/native-stack         |6.9.13
| react-native-screens                   |3.24.0
| react-native-gesture-handler           |2.12.1
| react-native-reanimated                |3.4.2
| react-native                           |0.72.4
| node                                   |20.5.1
| npm or yarn                            |9.8.0

**Comment by t1gu1** [comment]
We use `createNativeStackNavigator` in our app and it works fine.

You should really provide a Expo Snack playground to reproduce the bug.
You can even use that example to add few screen inside a Stack for your example.
[https://snack.expo.dev/@t1gu1/react-navigation-bottomtab-test](https://snack.expo.dev/@t1gu1/react-navigation-bottomtab-test)
