### ISSUE TITLE
calling navigation from header freezes app when used with freezeOnBlur

### ISSUE THREAD

**Issue by aclelland-netfore** [react-navigation/react-navigation#11555]
### Current behavior

I have a Stack Navigator set up like the following

```
<Stack.Navigator screenOptions={{ freezeOnBlur: true }}>
    <Stack.Group
        screenOptions={{
            header: (props) => <AppHeader {...props} />,
        }}
    >
        <Stack.Screen name="root" component={RootScreen} />
        <Stack.Screen name="example" component={ExampleScreen} />
    </Stack.Group>
</Stack.Navigator>
```

I navigate to the screen by using `navigation.navigate("example")` which works fine when called from the root screen using the screen props. However, when called from the `AppHeader` using the passed navigation props or the navigation from `useNavigation()` the resulting screen is completely unresponsive and frozen. if freezeOnBlur is set to false the navigation will work correctly.

### Expected behavior

focused screen shouldn't be frozen

### Reproduction

snack doesn't resolve: "@react-navigation/native": "^6.1.7",

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |6.1.7
| @react-navigation/native-stack         |6.9.13
| react-native-safe-area-context         |4.5.0
| react-native-screens                   |~3.20.0
| react-native-gesture-handler           |~2.9.0
| react-native-reanimated                |~2.14.4
| react-native                           |0.71.8
| expo                                   |48.0.11
| node                                   |18.13.0

**Comment by cbjs** [comment]
same problem.
any solution?

**Comment by Daniel3711997** [comment]
any news here ?

**Comment by AZ604** [comment]
same problem
