### ISSUE TITLE
`headerLargeTitle` does not work with Safe Areas and cuts off text/content underneath

### ISSUE THREAD

**Issue by ansh** [react-navigation/react-navigation#11550]
### Current behavior

As shown in the image below, there is some text in my code that should be displayed. However, currently it is hidden.

I have added a reproduction below.

```tsx
export default function App() {
  return (
    <SafeAreaProvider>
      <NavigationContainer>
        <Stack.Navigator>
          <Stack.Screen name="Hello" component={Hello} options={{ headerLargeTitle: true }} />
          {/* <Stack.Screen name="Hello" component={HelloWithSafeAreaContextView} options={{ headerLargeTitle: true }} /> */}
          {/* <Stack.Screen name="Hello" component={HelloWithDefaultSafeAreaView} options={{ headerLargeTitle: true }} /> */}
          {/* <Stack.Screen name="Hello" component={HelloWithInsets} options={{ headerLargeTitle: true }} /> */}
        </Stack.Navigator>
      </NavigationContainer>
    </SafeAreaProvider>
  );
}

const Hello = () => {
  return (
      <View>
        <Text>Hello, this text is invisible!</Text>
      </View>
  );
};
```

<img height="600" src="https://github.com/react-navigation/react-navigation/assets/8207733/58bb80b2-83f2-4ab9-92f3-aef63a388743" />

### Expected behavior

The text is shown as follows without any tricks or manually adding padding.

<img width="300" alt="CleanShot 2023-08-20 at 17 36 17@2x" src="https://github.com/react-navigation/react-navigation/assets/8207733/f23c4a1f-a7ae-4198-8430-981a9f3885e8">

I tried all the following methods and the only thing that works is using the default `SafeAreaView` from `react-native`. But, [according to the documentation, that is not recommended at all](https://reactnavigation.org/docs/handling-safe-area/)
- Tried using a `View` and nothing else
- Tried using a `SafeAreaView` from `react-native-safe-area-context`
- Tried using `useSafeAreaInsets` as recommended by docs
None of the above worked. 

```tsx
export default function App() {
  return (
    <SafeAreaProvider>
      <NavigationContainer>
        <Stack.Navigator>
          {/* <Stack.Screen name="Hello" component={Hello} options={{ headerLargeTitle: true }} /> */}
          {/* <Stack.Screen name="Hello" component={HelloWithSafeAreaContextView} options={{ headerLargeTitle: true }} /> */}
          <Stack.Screen name="Hello" component={HelloWithDefaultSafeAreaView} options={{ headerLargeTitle: true }} />
          {/* <Stack.Screen name="Hello" component={HelloWithInsets} options={{ headerLargeTitle: true }} /> */}
        </Stack.Navigator>
      </NavigationContainer>
    </SafeAreaProvider>
  );
}

const Hello = () => {
  return (
      <View>
        <Text>Hello, this text is invisible!</Text>
      </View>
  );
};

const HelloWithSafeAreaContextView = () => {
  return (
    <SafeAreaView>
      <View>
        <Text>Hello, this text is invisible!</Text>
      </View>
    </SafeAreaView>
  );
} 

const HelloWithDefaultSafeAreaView = () => {
  return (
    <View>
      <DefaultSafeAreaView>
        <Text>Hello, this text is actually not invisible, suprisingly!</Text>
      </DefaultSafeAreaView>
    </View>
  );
}

const HelloWithInsets = () => {
  const insets = useSafeAreaInsets();
  return (
    <View style={{ 
      paddingTop: insets.top,
      paddingBottom: insets.bottom,
      paddingLeft: insets.left,
      paddingRight: insets.right,
     }}>
      <Text>Hello, this text is invisible!</Text>
    </View>
  );
}
```

### Reproduction

https://github.com/ansh/headerLargeTitle-bug

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | "^6.1.7",
| @react-navigation/native-stack         | "^6.9.13",
| react-native-safe-area-context         | "4.6.3",
| react-native-screens                   | "~3.22.0"
| react-native                           | "0.72.3",
| expo                                   | "~49.0.7",
| node                                   | 18

**Comment by ansh** [comment]
There is a repro linked above!

**Comment by kyawthura-gg** [comment]
As documentation stated [here](https://reactnavigation.org/docs/native-stack-navigator/#headerlargetitle), you need to wrap in a scrollable view such as `ScrollView` or `FlatList` with `contentInsetAdjustmentBehavior="automatic"`.

**Comment by ansh** [comment]
Can `headerLargeTitle` not be used without using a `ScrollView` or `FlatList` as the direct child? @kyawthura-gg

**Comment by kyawthura-gg** [comment]
I guess no, and it's only supported on `ios`.

**Comment by ansh** [comment]
That's fair. This issue can be closed now.
