### ISSUE TITLE
Error after upgrading to expo 49

### ISSUE THREAD

**Issue by Dakuan** [react-navigation/react-navigation#11561]
### Current behavior

```
 ERROR  Error: The `useLegacyImplementation` prop is not available with Reanimated 3 as it no longer includes support for Reanimated 1 legacy API. Remove the `useLegacyImplementation` prop from `Drawer.Navigator` to be able to use it.

This error is located at:
   in DrawerViewBase (created by DrawerView)
    in RCTView (created by View)
```

### Expected behavior

run without errors

### Reproduction

...

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

```
{
    "@react-navigation/drawer": "^6.6.2",
    "@react-navigation/native": "^6.1.6",
    "@react-navigation/stack": "^6.3.17",
    "react": "18.2.0",
    "react-native": "0.72.3",
    "react-native-gesture-handler": "^2.12.0",
    "react-native-reanimated": "^3.4.1",
    "react-native-safe-area-context": "^4.5.3",
}
```

**Comment by migueldaipre** [comment]
Looks like you are use `useLegacyImplementation` prop with reanimated V3.

Remove this prop and try again. Add a minimal reproduce example.
