### ISSUE TITLE
Drawer crashes after certain gestures

### ISSUE THREAD

**Issue by netsnatch** [react-navigation/react-navigation#11575]
### Current behavior

I use react-native-drawer-layout. 
The application crashes when the onCancel event is fired. I was able to reproduce one case. 

This requires a real device. You need to partially open the Drawer with a swipe and lock the device without releasing your finger. After these actions, the application crashes.

Another way is the Windows Android Subsystem. You need to switch windows when you swipe the drawer.

```
Attempting to call runOnJS with an object that is not a host function. Using runOnJS is only possible with methods that are defined on the main React-Native Javascript thread and that aren't marked as worklets

Error: Attempting to call runOnJS with an object that is not a host function. Using runOnJS is only possible with methods that are defined on the main React-Native Javascript thread and that aren't marked as worklets
    at runOnJS (/home/expo/workingdir/build/node_modules/react-native-reanimated/src/reanimated2/core.ts (302:7):1:86)
    at runOnJS (native)
    at _f (/home/expo/workingdir/build/node_modules/react-native-drawer-layout/src/views/modern/Drawer.tsx (233:14):1:71)
    at _f (native)
    at _f (/home/expo/workingdir/build/node_modules/react-native-reanimated/src/reanimated2/hook/useAnimatedGestureHandler.ts (54:18):1:624)
    at _f (native)
```

https://github.com/react-navigation/react-navigation/assets/11537020/114221cd-4755-47ca-a406-a4ff26142284

### Expected behavior

The application should not crash.

### Reproduction

https://github.com/netsnatch/react-native-drawer-issue

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

Check out the [repo](https://github.com/netsnatch/react-native-drawer-issue)

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
|**react-native-drawer-layout**             |3.2.1
| @react-navigation/native               |6.1.7
| @react-navigation/bottom-tabs          |6.5.8
| @react-navigation/native-stack         |6.9.13
| react-native-safe-area-context         |4.5.0
| react-native-screens                   |3.20.0
| react-native-gesture-handler           |2.9.0
| react-native-reanimated                |2.14.4
| react-native                           |0.71.8
| expo                                   |48.0.20
| node                                   |16.20.2
| npm or yarn                            |yarn 1.22.19

**Comment by jacobmolby** [comment]
You can fix it with this patch:

`react-native-drawer-layout+3.2.0.patch`

```
diff --git a/node_modules/react-native-drawer-layout/src/views/modern/Drawer.tsx b/node_modules/react-native-drawer-layout/src/views/modern/Drawer.tsx
index 2705f4b..37c38b6 100644
--- a/node_modules/react-native-drawer-layout/src/views/modern/Drawer.tsx
+++ b/node_modules/react-native-drawer-layout/src/views/modern/Drawer.tsx
@@ -219,7 +219,9 @@ export function Drawer({
   );
 
   React.useEffect(() => toggleDrawer(open), [open, toggleDrawer]);
-
+  const maybeCancel = ()=>{
+    if(onGestureCancel) onGestureCancel()
+  }
   const onGestureEvent = useAnimatedGestureHandler<
     PanGestureHandlerGestureEvent,
     { startX: number; hasCalledOnStart: boolean }
@@ -231,7 +233,8 @@ export function Drawer({
       touchStartX.value = event.x;
     },
     onCancel: () => {
-      runOnJS(() => onGestureCancel?.())();
+      
+      runOnJS(maybeCancel)();
     },
     onActive: (event, ctx) => {
       touchX.value = event.x;
```

**Comment by satya164** [comment]
fixed in onGestureCancel

**Comment by ismaelsousa** [comment]
Now, It's also available for the [v3](https://github.com/react-navigation/react-navigation/releases/tag/react-native-drawer-layout%403.3.0)
