### ISSUE TITLE
Drawer navigation gestures don't work on Android devices

### ISSUE THREAD

**Issue by superyarik** [react-navigation/react-navigation#11583]
### Current behavior

using sample from [docs](https://reactnavigation.org/docs/drawer-navigator/#api-definition)(with minimal addons)

drawer open only by pressing hamburger, not swipe on android

### Expected behavior

drawer open by swipe

### Reproduction

https://snack.expo.dev/@hubex_developers/drawer-navigator-%7C-react-navigation

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

"@expo/vector-icons": "^13.0.0",
    "@react-native-community/masked-view": "*",
    "react-native-gesture-handler": "~2.9.0",
    "react-native-paper": "^4.7.2",
    "react-native-reanimated": "~2.14.4",
    "react-native-safe-area-context": "4.5.0",
    "react-native-screens": "~3.20.0",
    "@react-navigation/bottom-tabs": "6.3.1",
    "@react-navigation/drawer": "6.4.1",
    "@react-navigation/elements": "1.3.3",
    "@react-navigation/material-bottom-tabs": "6.2.1",
    "@react-navigation/native-stack": "6.6.1",
    "@react-navigation/native": "6.0.10",
    "@react-navigation/stack": "6.2.1"

**Comment by superyarik** [comment]
Update deps except "@react-navigation/native" - it "6.1.6", "6.1.7" not available on Snack. Result the same

**Comment by kacperkapusciak** [comment]
Closing as it's not reproductible with the newest version of react-native-reanimated & react-native-gesture-handler

**Comment by superyarik** [comment]
@kacperkapusciak i've update [snack](https://snack.expo.dev/@hubex_developers/drawer-navigator-%7C-react-navigation) to 
 "react-native-reanimated": "2.17.0",
 "react-native-gesture-handler": "2.12.1",

still not working
