### ISSUE TITLE
I'm Getting Failed to create a worklet, When i try to include/use createDrawerNavigator() 

### ISSUE THREAD

**Issue by shankarThiyagaraajan** [react-navigation/react-navigation#11582]
### Current behavior

**Before:**
![image](https://github.com/react-navigation/react-navigation/assets/10199091/9397330d-7638-4203-9e74-ff965e430f08)

**After:**
![image](https://github.com/react-navigation/react-navigation/assets/10199091/d9cd8488-5377-4c57-bf87-58e656ba9489)

### Expected behavior

I wanted to use createDrawerNavigator() for drawer menu in my app, But due to this issue
its not happening. 

Don't know why its crashing by just adding this line [not even started using in component].

### Reproduction

https://github.com/shankarThiyagaraajan/react-native-boilerplate

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [X] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.1.7
| @react-navigation/bottom-tabs          | 6.5.8
| @react-navigation/drawer               | 6.6.3
| @react-navigation/native-stack         | 6.9.13
| react-native-screens                   | 3.22.0
| react-native-gesture-handler           | 2.12.0
| react-native                           | 0.72.4
| expo                                   | 49.0.8
| node                                   | v18.12.0
| npm or yarn                            | npm

**Comment by iamalexcrow** [comment]
I am experiencing the same issue

**Comment by shankarThiyagaraajan** [comment]
Any updates?

**Comment by viniciuscmatos** [comment]
I came across this issue on my project. I solved it by installing react-native-reanimated, adding its plugin on babel.configs.js and starting the project removing the cache (yarn start --reset-cache).

**Comment by JackHull** [comment]
Same problem here.

**Comment by kacperkapusciak** [comment]
# <div style="color: red;">Add `"react-native-reanimated/plugin"` to the `plugins` array in your `babel.config.js`

How to fix the issue is literally said in the provided screenshot 🥲 

![image](https://github.com/react-navigation/react-navigation/assets/39658211/11d7923c-3165-4e43-ada3-027ff8a40730)

Here's more visual guide:

https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/getting-started/#step-2-add-reanimateds-babel-plugin

Cheers
