### ISSUE TITLE
Tab bar from material-top-tabs doesn't automatically scroll all the way when container has padding

### ISSUE THREAD

**Issue by LukyLurks** [react-navigation/react-navigation#11580]
### Current behavior

Context: the tab bar container has horizontal padding, scroll is enabled, and there's enough items to scroll.

If I repeatedly swipe until reaching the last tab, or directly touch it when it's partially visible, then the tab bar doesn't automatically scroll all the way. The last tab item will appear to lack padding or to be cut off. Please see the attached video for a demonstration (it uses the code provided in the reproduction).

https://github.com/react-navigation/react-navigation/assets/20930768/df0f6306-b8ab-466e-8dd8-4686ceaefa66

### Expected behavior

I expect the bar to automatically scroll all the way. Please see the attached video for an example. I was able to achieve this by modifying [`getMaxScrollDistance` in `react-native-tab-view/src/TabBar.tsx`](https://github.com/react-navigation/react-navigation/blob/ba53154b51edcdcfcac4cb249c5d93b8e4dc3564/packages/react-native-tab-view/src/TabBar.tsx#L159C14-L159C14) to only return `tabBarWidth` instead of `tabBarWidth - layoutWidth`.

https://github.com/react-navigation/react-navigation/assets/20930768/05f8542a-f4d3-4def-929b-85e1bd863b0e

### Reproduction

https://github.com/LukyLurks/material-top-tabs-scroll-issue

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [X] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [X] react-native-tab-view

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native | ^6.1.7 |
| @react-navigation/material-top-tabs    | ^6.6.3 |
| react-native-tab-view                  | ^3.5.2 |
| react-native-pager-view                | 6.2.0 |
| react-native                           | 0.72.4 |
| expo                                   | ~49.0.8 |
| node                                   | v16.20.0 |
| npm                           | 9.8.1 |

**Comment by LukyLurks** [comment]
I have seen [another issue](https://github.com/react-navigation/react-navigation/issues/8667) that should've been fixed by the [associated PR](https://github.com/react-navigation/react-navigation/pull/11408), but I couldn't figure out why I am having this behavior. Hoping the videos will help clarify things.

**Comment by sagarjeu** [comment]
After update to 72.2 new architecture true if I give  tabbaritemstyle width auto then tabbarindicater not display

**Comment by Freddy03h** [comment]
@LukyLurks What is the point of using `width: "auto"` on `tabBarContentContainerStyle` ?

**Comment by LukyLurks** [comment]
> @LukyLurks What is the point of using `width: "auto"` on `tabBarContentContainerStyle` ?

@Freddy03h If I remove this line, I get the same visual result as on the first video where the last tab is cut off, except I can't scroll to the end at all, even by scrolling the tab bar manually. You can see my finger trying to scroll on the bar in this video:
https://github.com/react-navigation/react-navigation/assets/20930768/156fc3e2-4ab5-4765-b42b-00a059cc72df

(Sorry for the late reply, I thought I'd receive email notifications for new comments. I'll make sure to set that up properly.)

**Comment by sagarjeu** [comment]
> > @LukyLurks What is the point of using `width: "auto"` on `tabBarContentContainerStyle` ?
> 
> @Freddy03h If I remove this line, I get the same visual result as on the first video where the last tab is cut off, except I can't scroll to the end at all, even by scrolling the tab bar manually. You can see my finger trying to scroll on the bar in this video:
> 
>  top-tabs-issue-3.mp4 
> (Sorry for the late reply, I thought I'd receive email notifications for new comments. I'll make sure to set that up properly.)

If we try to change tab bar multiple time app get crash

**Comment by LukyLurks** [comment]
@sagarjeu Your 2 comments on this issue seem to address 2 different problems, which are both unrelated to mine. Please search for existing issues related to your problem, and if you can't find any, open a new issue.

**Comment by Freddy03h** [comment]
@LukyLurks It's seems my PR only land in 4.0.0-alpha.0 https://github.com/react-navigation/react-navigation/releases/tag/react-native-tab-view%404.0.0-alpha.0

Try this version please, but I'm suggesting to remove `width: auto` on `tabBarContentContainerStyle` otherwise it will override the calculated width based on all sizes and parameters.

**Comment by LukyLurks** [comment]
@Freddy03h Thank you. I updated my package.json with `"react-native-tab-view": "4.0.0-alpha.0"`, removed `width: "auto"`, and now I can remove `tabBarIndicatorContainerStyle: { marginHorizontal: 20 }` too, and it works perfectly without my dirty hack. I just didn't know your PR was still in alpha, so I thought I already had your changes but I didn't... 🤦 Thanks for your work on this. Closing as solved.

**Comment by giginkrishnan** [comment]
Working material top bar using react-navigation and scroll automatically on content swipe

https://github.com/react-navigation/react-navigation/assets/18523239/b9e2e818-1ff4-42b5-be10-65b20b8c3b34

**Comment by VictorioMolina** [comment]
any solutions?

**Comment by giginkrishnan** [comment]
> any solutions?

CustomTabBar

import {
  Animated,
  View,
  TouchableOpacity,
  ScrollView,
  Dimensions,
} from "react-native";
import { theme } from "../../assets/styles/theme";
import moment from "moment";
import colors from "../../assets/styles/colors";
import { useEffect, useRef } from "react";

const screenWidth = Dimensions.get("window").width;

export default function MyTabBar({ state, descriptors, navigation, position }) {
  const scrollRef = useRef(null);

  useEffect(() => {
    const index = state.index;
    const xOffset = (index - 1) * (screenWidth / 5);
    scrollRef.current.scrollTo({ x: xOffset, animated: true });
  }, [state.index]);

  return (
    <View>
      <ScrollView
        horizontal
        ref={scrollRef}
        showsHorizontalScrollIndicator={false}
        style={{ backgroundColor: "white" }}
      >
        {state.routes.map((route, index) => {
          const { options } = descriptors[route.key];
          const label =
            options.tabBarLabel !== undefined
              ? options.tabBarLabel
              : options.title !== undefined
                ? options.title
                : route.name;

          const isFocused = state.index === index;

          const onPress = () => {
            const event = navigation.emit({
              type: "tabPress",
              target: route.key,
              canPreventDefault: true,
            });

            if (!isFocused && !event.defaultPrevented) {
              navigation.navigate(route.name, route.params);
            }
          };

          const onLongPress = () => {
            navigation.emit({
              type: "tabLongPress",
              target: route.key,
            });
          };

          const inputRange = state.routes.map((_, i) => i);
          const opacity = position.interpolate({
            inputRange,
            outputRange: inputRange.map((i) => (i === index ? 1 : 0.6)),
          });

          const date = moment(label);
          return (
            <TouchableOpacity
              key={`tab-header-${index}`}
              accessibilityRole="button"
              accessibilityState={isFocused ? { selected: true } : {}}
              accessibilityLabel={options.tabBarAccessibilityLabel}
              testID={options.tabBarTestID}
              onPress={onPress}
              onLongPress={onLongPress}
              style={{
                alignItems: "center",
                width: screenWidth / 5,
              }}
            >
              <Animated.View
                style={{
                  backgroundColor: isFocused ? "#0BB6EC" : "transparent",
                  paddingVertical: 5,

                  paddingHorizontal: 10,
                  marginHorizontal: 5,
                  borderRadius: 4,
                  flexDirection: "row",
                }}
              >
                <View style={{}}>
                  <Animated.Text
                    style={{
                      opacity,
                      color: isFocused ? colors.white : "#121212",
                      fontFamily: theme.fontFamily.poppinsSemiBold,
                      fontSize: 20,
                      marginRight: 5,
                    }}
                  >
                    {moment(label).format("DD")}
                    {/* {label} */}
                  </Animated.Text>
                </View>
                <View
                  style={{
                    flexDirection: "column",
                    marginBottom: 0,
                    alignItems: "center",
                  }}
                >
                  <Animated.Text
                    style={{
                      opacity,
                      color: isFocused ? colors.white : "#121212",
                      fontFamily: theme.fontFamily.poppinsMedium,
                      fontSize: 12,
                    }}
                  >
                    {moment(label).format("dd")}
                    {/* {label} */}
                  </Animated.Text>
                  <Animated.Text
                    style={{
                      opacity,
                      color: isFocused ? colors.white : "#121212",
                      fontFamily: theme.fontFamily.poppinsMedium,
                      fontSize: 8,
                      marginTop: -4,
                    }}
                  >
                    {moment(label).format("MMM")}
                    {/* {label} */}
                  </Animated.Text>
                </View>
              </Animated.View>
            </TouchableOpacity>
          );
        })}
      </ScrollView>
    </View>
  );
}
