### ISSUE TITLE
When try use Drawer show error in ios : [Reanimated] `valueUnpacker` is not a worklet

### ISSUE THREAD

**Issue by moGeekHex** [react-navigation/react-navigation#11595]
### Current behavior

 "react-native": "0.71.7",
"react-native-reanimated": "^3.5.1",
"@react-native-masked-view/masked-view": "^0.2.9",
"@react-navigation/bottom-tabs": "^6.5.8",
"@react-navigation/drawer": "^6.6.3",
"@react-navigation/native": "^6.1.7",
"@react-navigation/native-stack": "^6.9.13",
"@react-navigation/stack": "^6.3.17",

### Expected behavior

.

### Reproduction

..

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |
| @react-navigation/bottom-tabs          |
| @react-navigation/drawer               |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                |
| @react-navigation/native-stack         |
| react-native-safe-area-context         |
| react-native-screens                   |
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           |
| expo                                   |
| node                                   |
| npm or yarn                            |

**Comment by JackHull** [comment]
Same problem here.

`@react-navigation/compat@5.3.20`
`@react-navigation/native@6.1.7`
`@react-navigation/native-stack@6.9.13`
`react-native-reanimated@3.5.1`
`react-native-worklets-core@0.2.0`
`react-native@0.72.4`
`react-native-tab-view@3.5.2`

**Comment by kacperkapusciak** [comment]
Should be fixed by https://github.com/software-mansion/react-native-reanimated/pull/5087

**Comment by thehelium** [comment]
Have you tried add Reanimated's babel plugin?

### Add react-native-reanimated/plugin plugin to your babel.config.js
```javascript
  module.exports = {
    presets: [
      ... // don't add it here :)
    ],
    plugins: [
      ...
      'react-native-reanimated/plugin',
    ],
  };
```

### Clear cache
```sh
yarn start --reset-cache
```

> https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/getting-started/#step-2-add-reanimateds-babel-plugin

**Comment by jmejiamu** [comment]
Hello every 
Package: 
```shell
"@gorhom/bottom-sheet": "^4.5.1",
"react-native-gesture-handler": "^2.13.1",
"react-native-reanimated": "^3.5.4",
```
I am getting this error in React native cli. I am following this [Bottom Sheet Modal](https://gorhom.github.io/react-native-bottom-sheet/modal/usage/)

```shell
ERROR  TypeError: Cannot read property 'BottomSheetModalProvider' of undefined

This error is located at:
    in BottomSheet (created by unboundStoryFn)
    in RCTView (created by View)
    in View (created by GestureHandlerRootView)
    in GestureHandlerRootView (created by unboundStoryFn)
    in unboundStoryFn (created by StoryView)
    in RCTView (created by View)
    in View (created by StoryView)
    in StoryView (created by OnDeviceUI)
    in RCTView (created by View)
    in View (created by Preview)
    in RCTView (created by View)
    in View
    in Unknown (created by Preview)
    in Preview (created by OnDeviceUI)
    in RCTView (created by View)
    in View
    in Unknown (created by OnDeviceUI)
    in RCTView (created by View)
    in View (created by AbsolutePositionedKeyboardAwareView)
    in RCTView (created by View)
    in View (created by AbsolutePositionedKeyboardAwareView)
    in AbsolutePositionedKeyboardAwareView (created by OnDeviceUI)
    in RCTView (created by View)
    in View (created by KeyboardAvoidingView)
    in KeyboardAvoidingView (created by OnDeviceUI)
    in RCTView (created by View)
    in View (created by emotion(View))
    in emotion(View) (created by OnDeviceUI)
    in OnDeviceUI
    in ThemeProvider2
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider
    in Unknown
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in WalkSmart(RootComponent), js engine: hermes
 LOG  [TypeError: Cannot read property 'BottomSheetModalProvider' of undefined]
 ERROR  Error rendering story 'buttonsheet--basic':
 ERROR  [TypeError: Cannot read property 'BottomSheetModalProvider' of undefined]
```
 
 IMPLEMENTATION:
 ```typescript
//BottomSheet.tsx
import React, {useRef} from 'react';
import {View, Text, StyleSheet, Button} from 'react-native';

import {BottomSheetModal, BottomSheetModalProvider} from '@gorhom/bottom-sheet';

const BottomSheet = () => {
  const bottomSheetRef = useRef<BottomSheetModal>(null);

  const snapPoints = ['25%'];

  const handlePressModal = () => {
    bottomSheetRef.current?.present();
  };

  return (
    <BottomSheetModalProvider>
      <View style={styles.container}>
        <Button title="Show Modal" onPress={handlePressModal} />
        <BottomSheetModal
          ref={bottomSheetRef}
          index={0}
          snapPoints={snapPoints}>
          <View>
            <Text>Awesome 🎉</Text>
          </View>
        </BottomSheetModal>
      </View>
    </BottomSheetModalProvider>
  );
};

export default BottomSheet;

const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 24,
    justifyContent: 'center',
    backgroundColor: 'grey',
  },
});
```
STORYBOOK:
```typescript

import React from 'react';
import {View, Text} from 'react-native';
import BottomSheet from './BottomSheet';
import {GestureHandlerRootView} from 'react-native-gesture-handler';

const BottomSheetMeta = {
  title: 'ButtonSheet',
  component: BottomSheet,
  decorators: [
    Story => (
      <GestureHandlerRootView style={{flex: 1}}>
        <BottomSheet />
      </GestureHandlerRootView>
    ),
  ],
};

export default BottomSheetMeta;
export const Basic = {};
```
<img width="339" alt="Screenshot 2023-10-07 at 3 07 35 PM" src="https://github.com/gorhom/react-native-bottom-sheet/assets/27458911/8c3b2859-35e5-4cbb-8760-bd51447cb9f0">


I just wonder if I am missing something here? or I am implementing this incorrectly? or maybe packages compatible issues?

**Comment by joumanam** [comment]
@jmejiamu same here! Were you able to fix it?

**Comment by jmejiamu** [comment]
Hey @joumanam , I was not able to fix, but I found this alternative option that seems to be working just fine for both Android and iOS. https://www.npmjs.com/package/@devvie/bottom-sheet
