### ISSUE TITLE
Custom Tab Bar Component: react/no-unstable-nesting-components

### ISSUE THREAD

**Issue by skizzo** [react-navigation/react-navigation#11590]
### Current behavior

Hi,
when following the docs on [creating a custom tab bar component](https://reactnavigation.org/docs/bottom-tab-navigator#tabbar) 1:1, I receive the eslint error 

<img width="495" alt="Screenshot 2023-09-11 at 10 59 24" src="https://github.com/react-navigation/react-navigation/assets/2892572/4ab8720a-daa8-4f99-ac91-c2e26ff38c4d">

`react/no-unstable-nested-components` – *Do not define components during render. React will see a new component type on every render and destroy the entire subree's DOM nodes and state. (...) Instead, move this component definition out of the parent component "TabNavigator" and pass data as props. If you want to allow component creation in props, set allowAsProps option to true.*

I wonder if there's a better way of doing this which is not mentioned in the docs, and would be grateful for any help. Thanks!

### Expected behavior

No eslint errors when exactly following docs.

### Reproduction

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAJQKYEMDGMA0cDeBhCcCAOyWJgF84AzKQuAIilQwYChRJZcA1YJAO7YAKkgAeWOMIgBXNAAsUAIwA2SAPJh0wGAE8qtekxYwAtMRQxgANyTtO0eDjTNLSAEIQYMQsOUA5FGtgAHNLaGxPb19ldxQoAAU6MABnAzoQRgABVwxzINDLYBIAeiUvHxBTGGUU9jY0EhT4PyU4AF44F1QYDwqYpUDgsJ8oAAoASjYGppaAgpHoDrhJjoA+FbY4OBKAKl3tw6Pjk9yYEuIIUxliZuU1cyRmpAATU0aiUnIUuF2SrbgAB5WgA6IaFUZwGpKOJQdo4MDJH7tDaAgCyulasNwINxiIgqSoJTWFDWAO2wOUIIAyt0yHALCAkO0GAARJ5WCxWJoMLqESBfGDw1kyEAgXS05hkIlko6UpQ0unEBkoJksgBSsigpF0dT5nzIQpwIrFEqVMvJQNBkqQ9MZzIYSQg1GAal5HwFhuFovFNulO1lQJKoPBiygZKmM1u8BNvqVy1WKKBfEEa2B4hga1EzTgfuIgODGbTJRTAjJbGoNwwxWVGKx8TG+NSAC44FFKvXEkiJrgAY1o7gLMMiiQqJ0mykAcwYDJtZs5dI5IpVBotGgdLo4CQkk8UvDExshxCayCjyMkGMAOROl1qS8TUmWimiCRrUNuAsvzOWz+yBT3VdtD0QMJgAbjYChpiAA

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.1.7
| @react-navigation/bottom-tabs          | 6.5.8
| @react-navigation/stack                | 6.3.17
| @react-navigation/native-stack         | 6.9.13
| react-native-safe-area-context         | 4.7.1
| react-native-screens                   | 3.25.0
| react-native-gesture-handler           | 2.12.1
| react-native                           | 0.71.7
| node                                   | 18.16.0
| npm or yarn                            | 9.5.1

**Comment by satya164** [comment]
That's a regular function that returns a react element, not a component. It's a false positive from the ESLint plugin.

**Comment by skizzo** [comment]
Okay cool, thanks for the super-quick reply. For anybody else running into this eslint error: It can simply be ignored by adding 

```
"react/no-unstable-nested-components": 0
```

to `.eslintrc.js`.
