### ISSUE TITLE
accessibility not working for elements which are under opened Drawer for appium [iOS]

### ISSUE THREAD

**Issue by ravindraguptacapgemini** [react-navigation/react-navigation#11593]
### Current behavior

Unable to find the elements under the overlay. 

### Expected behavior

Should be able to find the elements under the overlay. 

### Reproduction

https://github.com/ravindraguptacapgemini/AwesomeProject_Latest/tree/react-navigation-drawer-crash

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |6.1.7|
| @react-navigation/drawer               |6.6.3|
| @react-navigation/stack                |6.3.17|
| react-native-safe-area-context         |4.7.2|
| react-native-screens                   |3.25.0|
| react-native-gesture-handler           |2.12.1|
| react-native-reanimated                |3.5.1|
| react-native                           |0.72.4|
| node                                   |16.20.0|
| npm                            |9.6.7|

**Comment by ravindraguptacapgemini** [comment]
Added Reproducer app now.

**Comment by felipebaisi** [comment]
Indeed. I have the same issue.

**Comment by ajmferrier** [comment]
Could this issue be re-opened? This thread was closed due to no repro, but a repro was attached and I am currently facing the same issue.
