### ISSUE TITLE
Tab Screen Switching Animation

### ISSUE THREAD

**Issue by TranLeHaiDuong** [react-navigation/react-navigation#11609]
### Current behavior

Normally, when switching between tab screens, it will provide animation sliding from current tab screen to target tab screen and also sliding through the tab screen between them.

### Expected behavior

Here, I still need the sliding animation but I want the animation to slide from the current to the target tab screen without through the tab screen between them.

import {
  createMaterialTopTabNavigator,
  MaterialTopTabBarProps,
} from '@react-navigation/material-top-tabs';
const Tab = createMaterialTopTabNavigator<BottomTabParamList>();

export function HomeTab() {
  return (
    <Tab.Navigator
      tabBarPosition="bottom"
      screenOptions={{
        swipeEnabled: false,
      }}
      tabBar={(props: MaterialTopTabBarProps) => (
        <NavigationBar {...props} data={bottomTabItems} />
      )}>
      {bottomTabItems
        .filter(dt => dt.component)
        .map((dt, index) => (
          <Tab.Screen key={index} name={dt.name} component={dt.component} />
        ))}
    </Tab.Navigator>
  );
}

The bottomTabItems like this: [{
    name: bottomNavigation.HomeScreen,
    icon: 'icon_home',
    label: I18n.t('bottomBar.Home'),
    component: HomeScreen,
  },
  {
    name: bottomNavigation.TransactionScreen,
    icon: 'document',
    label: I18n.t('bottomBar.Transactions'),
    component: TransactionScreen,
  }]

### Reproduction

https://github.com/react-navigation/react-navigation

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [X] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [X] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.6.2
| @react-navigation/bottom-tabs          | 6.5.8
| @react-navigation/material-top-tabs    | 6.6.2
| @react-navigation/stack                | 5.14.5
| react-native-safe-area-context         | 4.5.0
| react-native-screens                   | 3.19.0
| react-native-reanimated                | 2.14.4
| react-native-tab-view                  | 3.4.1
| react-native-pager-view                | 6.1.4
| react-native                           | 0.69.8
| node                                   | 18.12.1
| yarn                            | 1.22.19

**Comment by Elvin2019** [comment]
Hello, were you able to resolve that issue? I also need to have sliding between tabs but am facing the same issue as you. If you managed to fix it or found an alternative solution, I’d be glad to see it.

**Comment by kamalmplus** [comment]
You can use <Animated.View entering={SlideInLeft} exiting={SlideOutRight}> wrapping your screen component

**Comment by Ungkarl** [comment]
Any solution to this? - i am having this issue, on iOS its working perfectly, showing only the current screen and the target screen.
On android, it shows all the screens in between the current and target

**Comment by pierroo** [comment]
I'm a bit late, but did any of you guys find a reliable / smooth solution? :)
