### ISSUE TITLE
Crash occurs on iOS when moving device stack with navigation.replace()

### ISSUE THREAD

**Issue by heeeete** [react-navigation/react-navigation#11604]
### Current behavior

It works fine on Android, but the app only turns off on iOS.
There is a stack appropriate for each environment, and the code moves to that stack.

https://github.com/react-navigation/react-navigation/assets/101648575/8e8ceae6-2547-4ac4-91d8-05cbbcb6c3b2

App.js
```

function MainDrawer() {
    return (
      <Drawer.Navigator
        initialRouteName="Main"
        screenOptions={screenOptions}
        drawerContent={props => CustomDrawerContent(props)}>
        <Drawer.Screen name="Main" component={Main} />
        <Drawer.Screen name="ViewDiary" component={ViewDiary} />
        <Drawer.Screen name="Todo" component={Todo} />
        <Drawer.Screen name="RememberBook" component={RememberBook} />
        <Drawer.Screen name="MyPage" component={MyPage} />
      </Drawer.Navigator>
  );


  }
  function MainTab() {
    return (
      <Tab.Navigator initialRouteName="Main" screenOptions={tabScreenOptions}>
        <Tab.Screen name="Main" component={Main} />
        <Tab.Screen name="ViewDiary" component={ViewDiary} />
        <Tab.Screen name="Todo" component={Todo} />
        <Tab.Screen name="RememberBook" component={RememberBook} />
        <Tab.Screen name="MyPage" component={MyPage} />
      </Tab.Navigator>
  );

function App() {
return (
    <GestureHandlerRootView style={{flex: 1}}>
      <ThemeProvider>
        <NavigationContainer>
          <Stack.Navigator screenOptions={{headerShown: false}}>
            {value => console.log(value.name)}
            <Stack.Screen name="Addinfo" component={Addinfo} />                              //       HERE
            <Stack.Screen name="IosMainPage" component={MainDrawer} />             //       HERE
            <Stack.Screen name="AndroidMainPage" component={MainTab} />
            <Stack.Screen name="AddDiary" component={AddDiary} />
            <Stack.Screen name="ModifyDiary" component={ModifyDiary} />
            <Stack.Screen name="Viewall" component={Viewall} />
            <Stack.Screen name="ShowMore" component={ShowMore} />
          </Stack.Navigator>
        </NavigationContainer>
      </ThemeProvider>
    </GestureHandlerRootView>
  );
}

```

Addinfo.js
Addinfo Stack
```
  const join_success = () => {
    if (Platform.OS !== 'ios') navigation.replace('AndroidMainPage');
    else {
      navigation.replace('IosMainPage');
    }
  };
```

The behavior I want is to prevent the user from going back to the login page after successful login.

### Expected behavior

The behavior I want is to prevent the user from going back to the login page after successful login.

### Reproduction

no

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native             |  6.1.6|
| @react-navigation/bottom-tabs     |     6.5.8|
| @react-navigation/drawer           |    6.6.3|
| @react-navigation/material-top-tabs |   6.6.3|
| @react-navigation/native-stack      |   6.9.12|
| react-native-safe-area-context      |   4.7.1|
| react-native-screens              |     3.20.0|
| react-native                        |   0.72.1|

**Comment by ashadnasim52** [comment]
it is still happening in the version 6.1.7
   "@react-navigation/bottom-tabs": "^6.5.7",
    "@react-navigation/native": "^6.1.7",
    "@react-navigation/native-stack": "^6.9.12",
