### ISSUE TITLE
Crash occurs on iOS when moving device stack with navigation.replace()

### ISSUE THREAD

**Issue by heeeete** [react-navigation/react-navigation#11603]
### Current behavior

It works fine on Android, but the app only turns off on iOS.
There is a stack appropriate for each environment, and the code moves to that stack.

https://github.com/react-navigation/react-navigation/assets/101648575/03bfbcab-4771-44d2-be30-18425b109ce6
App.js
```

function MainDrawer() {
  return (
    <Drawer.Navigator
      initialRouteName="Main"
      screenOptions={screenOptions}
      drawerContent={props => CustomDrawerContent(props)}>
      <Drawer.Screen name="Main" component={Main} />
      <Drawer.Screen name="ViewDiary" component={ViewDiary} />
      <Drawer.Screen name="Todo" component={Todo} />
      <Drawer.Screen name="RememberBook" component={RememberBook} />
      <Drawer.Screen name="MyPage" component={MyPage} />
    </Drawer.Navigator>
  );
}

function MainTab() {
  return (
    <Tab.Navigator initialRouteName="Main" screenOptions={tabScreenOptions}>
      <Tab.Screen name="Main" component={Main} />
      <Tab.Screen name="ViewDiary" component={ViewDiary} />
      <Tab.Screen name="Todo" component={Todo} />
      <Tab.Screen name="RememberBook" component={RememberBook} />
      <Tab.Screen name="MyPage" component={MyPage} />
    </Tab.Navigator>
  );
}

return (
    <Tab.Navigator initialRouteName="Main" screenOptions={tabScreenOptions}>
      <Tab.Screen name="Main" component={Main} />
      <Tab.Screen name="ViewDiary" component={ViewDiary} />
      <Tab.Screen name="Todo" component={Todo} />
      <Tab.Screen name="RememberBook" component={RememberBook} />
      <Tab.Screen name="MyPage" component={MyPage} />
    </Tab.Navigator>
  );
```

Login.js
```
  const join_success = () => {
    if (Platform.OS !== 'ios') navigation.replace('AndroidMainPage');
    else {
      navigation.replace('IosMainPage');
    }
  };
```

### Expected behavior

The behavior I want is to prevent the user from going back to the login page after successful login.

### Reproduction

no

### Platform

- [ ] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native             |  6.1.6|
| @react-navigation/bottom-tabs     |     6.5.8|
| @react-navigation/drawer           |    6.6.3|
| @react-navigation/material-top-tabs |   6.6.3|
| @react-navigation/native-stack      |   6.9.12|
| react-native-safe-area-context      |   4.7.1|
| react-native-screens              |     3.20.0|
| react-native                        |   0.72.1|

**Comment by satya164** [comment]
`replace` is only available in stack navigator. i don't see any stack navigator in the code.

**Comment by ashadnasim52** [comment]
I am also facing this issue. I had imported 
import {useNavigation, useRoute} from '@react-navigation/native';
then I had used this   const navigation = useNavigation();
                navigation.replace(ONBOARDING_SCREEN);

**Comment by infiniteline** [comment]
I have also had this issue going from a nested stack navigator to another nested stack navigator. `navigate` works fine but `replace` results in a complete crash of the app. This only happens on iOS.

Here's an example of my navigators. In this instance, using replace to move from `AccountSurveys` to `MainTabStackNav` will cause the crash.

```
<Stack.Navigator>
   <Stack.Screen name='AuthStackNav' component={AuthStackNav} options={{ headerShown: false, orientation: 'portrait', gestureEnabled: false }} />
   <Stack.Screen name='MainTabStackNav' component={MainTabStackNav} options={{ headerShown: false, orientation: 'portrait' }} />
   <Stack.Screen name='AccountSurveys' component={AccountSurveys} options={{ headerShown: false, orientation: 'portrait', gestureEnabled: false }} />
</Stack.Navigator>
```
<br>
Even using `replace` to navigate to another screen in the same stack (e.g., within `AccountSurveys`) will result in a crash BUT ONLY WHEN USING OPTIONAL PARAMS:

```
this.props.navigation.replace('AccountSurveys', { screen: 'SomeSortOfAccountScreen' });
```

The following won't cause a crash:

```
this.props.navigation.replace('SomeSortOfAccountScreen');
```

(That seems to be a workaround if you're navigating within the same stack but not if you need to go to another one.)


**Environment**
        "@react-navigation/bottom-tabs": "^6.6.1",
        "@react-navigation/native": "^6.1.18",
        "@react-navigation/native-stack": "^6.10.1",
        "react": "^18.3.1",
        "react-native": "^0.74.3"
