### ISSUE TITLE
navigation.setOptions Error: SceneView: Rendered fewer hooks than expected. This may be caused by an accidental early return statement.

### ISSUE THREAD

**Issue by SMJ93** [react-navigation/react-navigation#11600]
### Current behavior

We currently update our header in a useEffect hook with the following:

```
const navigation = useNavigation();

useEffect(() => {
      navigation.setOptions({
        header: () => (
          <View>
            <Text>Test</Text>
          </View>
        )
      });
  }, [navigation]);
```

Everything was working as expected when we used these versions of react navigation:

```
    "@react-navigation/bottom-tabs": "^6.4.0",
    "@react-navigation/drawer": "^6.4.3",
    "@react-navigation/native": "^6.0.13",
    "@react-navigation/native-stack": "6.2.2",
    "@react-navigation/stack": "^6.2.2",
```

But since updating to the following versions:
```
    "@react-navigation/bottom-tabs": "^6.5.8",
    "@react-navigation/drawer": "^6.6.3",
    "@react-navigation/native": "^6.1.7",
    "@react-navigation/native-stack": "6.9.13",
```

_Note: we removed "@react-navigation/stack" as it was only used for types._

`navigation.setOptions` returns the following error:

```
Error: Rendered fewer hooks than expected. This may be caused by an accidental early return statement.

This error is located at:
    in SceneView (created by NativeStackViewInner)
    in Suspender (created by Freeze)
    in Suspense (created by Freeze)
    ...
```

We've checked the `SceneView` inside `node_modules/@react-navigation/native-stack/src/views/NativeStackView.native.tsx` and can't see any hooks that are conditionally called.

Thanks!

### Expected behavior

It should update the navigation header component like on the older versions.

### Reproduction

Use the snippet above to reproduce

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.1.7
| @react-navigation/bottom-tabs          | 6.5.8
| @react-navigation/drawer               | 6.6.3
| @react-navigation/native-stack         | 6.9.13
| react-native-safe-area-context         | 4.7.2
| react-native-screens                   | 3.25.0
| react-native-gesture-handler           | 2.5.0
| react-native-reanimated                | 2.17.0
| react-native                           | 0.71.12
| node                                   | v16.16.0
| npm or yarn                            | 1.22.19

**Comment by SMJ93** [comment]
Tried updating all packages to the latest versions and still getting the issue. Also appears when running tests with react testing library 🤔

**Comment by SMJ93** [comment]
It looks like one of the header changes in `6.3.0` caused this issue:

https://github.com/react-navigation/react-navigation/compare/%40react-navigation/native-stack%406.2.5...%40react-navigation/native-stack%406.3.0

`6.2.5` works as expected so we will use this version for now.

**Comment by TPXP** [comment]
Hi, I had a similar issue when I was trying to mix headerLeft components that are functions with other that aren't:
```jsx
        <Stack.Navigator
          initialRouteName={'Home'}
          screenOptions={{
            headerLeft: EnhancedBackButton,
          }}>
```

```jsx
    this.props.navigation.setOptions({
      headerLeft: ({onPress, ...props}) => (
        <EnhancedBackButton {...props} onPress={this.exit} />
      ),
    });
```

Wrapping the initial call to have the same level of functions before the actual component fixed it
```jsx
        <Stack.Navigator
          initialRouteName={'Home'}
          screenOptions={{
            headerLeft: (props) => <EnhancedBackButton {...props} />,
          }}>
```
Hopefully that helps :)
