### ISSUE TITLE
Drawer gets stuck while open and close

### ISSUE THREAD

**Issue by SanketDorle** [react-navigation/react-navigation#11616]
### Current behavior

When the drawer is opening it gets stuck, after touching the screen 2-3 times the drawer opens but not smoothly and after clicking on any item in the drawer the drawer does not close.

https://github.com/react-navigation/react-navigation/assets/29650271/84923e49-c80b-4f32-b585-032329ce019f

this happed only on production build.

### Expected behavior

Drawer should open & close smoothly.

### Reproduction

https://github.com/SanketDorle/EVCFinder/tree/Energize

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [X] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | ^6.1.7
| @react-navigation/drawer               | ^6.6.3
| @react-navigation/stack                | ^6.3.17
| react-native-gesture-handler           | ~2.12.0
| react-native-reanimated                | ~3.3.0
| react-native-pager-view                | 6.2.0
| react-native                           | 0.72.4
| expo                                   | ^49.0.9
| node                                   | 16.18.1
| npm                            |  8.19.2

**Comment by SanketDorle** [comment]
> * @react-navigation/native
Same issue after upgrading above packages.

**Comment by Eonfuzz** [comment]
Running into a similar issue, I believe it has something to do with gestures

**Comment by thats-sarthak** [comment]
Can you please assign me this issue

**Comment by Eonfuzz** [comment]
I was able to get this fixed by updating to these versions:
```typescript

    "@react-navigation/drawer": "^6.6.4",
    "@react-navigation/native": "^6.1.8",
    "react-native-reanimated": "^3.5.4",
    "react-native-gesture-handler": "^2.13.1",
```

I believe it has something to do with older versions of reanimated or gesture handler.

**Comment by guruprasath1327** [comment]
i am aslo face this issue how to fix it

**Comment by HodgertA** [comment]
https://github.com/react-navigation/react-navigation/issues/11826 Facing the same issue

**Comment by guruprasath1327** [comment]
"@react-navigation/drawer": "^6.6.3",
"@react-navigation/native": "^6.1.7",
"@react-navigation/native-stack": "^6.9.13",
"react-native-reanimated": "~3.3.0",

**Comment by HodgertA** [comment]
> "@react-navigation/drawer": "^6.6.3", "@react-navigation/native": "^6.1.7", "@react-navigation/native-stack": "^6.9.13", "react-native-reanimated": "~3.3.0",

@guruprasath1327 Thanks! I upgraded to expo 50 and the packages seemed to have resolved themselves and it works now. I am using 

"@react-navigation/drawer": "^6.6.7",
"@react-navigation/native": "^6.1.10",
"@react-navigation/stack": "6.3.21",
"react-native-reanimated": "~3.6.2"

**Comment by ArthurDias01** [comment]
I have the same issue but with these versions:

```json

"@react-navigation/drawer": "6.6.7",
"@react-navigation/native": "6.1.10",
"@react-navigation/stack": "^6.3.21",
"react-native-reanimated": "~3.3.0",

```

**Comment by guruprasath1327** [comment]
> I have the same issue but with these versions:
> 
> ```json
> "@react-navigation/drawer": "6.6.7",
> "@react-navigation/native": "6.1.10",
> "@react-navigation/stack": "^6.3.21",
> "react-native-reanimated": "~3.3.0",
> ```

Use  "react-native-reanimated": "^3.6.2"

**Comment by estiventhneira** [comment]
any update at this?

**Comment by JenilynnB** [comment]
Ran into this issue today and determined that it's likely related to having "Reduce motion" turned on on a physical device.  

Here's a [minimal reproducible example](https://snack.expo.dev/@jbrandes/authentic-yellow-apple). Ran with device running iOS 17.4.1 with "Reduce motion" and "Prefer Cross Fade transitions" turned on in Accessibility Settings and it looks like the video in the original post.

**Comment by Mahmoudkhoder01** [comment]
> ```json
> ^
> ```

how can I download this specific version of reanimated without facing errors? I'm facing ana issue when I change the version

**Comment by guruprasath1327** [comment]
> any update at this?

"@react-navigation/drawer": "6.6.7",
"@react-navigation/native": "6.1.10",
"@react-navigation/stack": "^6.3.21",
"react-native-reanimated": "~3.3.0",

update the latest version of these lib

**Comment by guruprasath1327** [comment]
> any update at this?

"@react-navigation/drawer": "6.6.7",
"@react-navigation/native": "6.1.10",
"@react-navigation/stack": "^6.3.21",
"react-native-reanimated": "~3.3.0",

update tje latest version of these lib

**Comment by Eonfuzz** [comment]
> > any update at this?
> 
> "@react-navigation/drawer": "6.6.7", "@react-navigation/native": "6.1.10", "@react-navigation/stack": "^6.3.21", "react-native-reanimated": "~3.3.0",
> 
> update the latest version of these lib

Unable to test iOS, but I am on and this issue also occurs on Android when animations have been turned off in device settings:

    "@react-navigation/drawer": "^6.6.15",
    "@react-navigation/native": "6.1.17",
    "@react-navigation/stack": "6.3.29",
    "react-native-reanimated": "^3.11.0",

**Comment by gmartpad** [comment]
Any update?

**Comment by cyrilchapon** [comment]
I'm facing the same issue without any "Reduced Motion" setting (fresh ios simulator), with the followings :
```
"react-native-drawer-layout": "^3.3.2",
"react-native-gesture-handler": "~2.16.1",
"react-native-reanimated": "~3.10.1",
```

**Comment by frankie-text** [comment]
I found out the solution https://stackdev.space/questions/exploring-challenges-with-navigation-drawer-in-android-using-kotlin
