### ISSUE TITLE
I18nManager.getConstants is not a function

### ISSUE THREAD

**Issue by juanchaur** [react-navigation/react-navigation#11612]
### Current behavior

I've updated my dependencies to the last version and I don't see any compilation error.
But during run time I see the following error

```
HeaderBackButton.tsx:207 Uncaught TypeError: _I18nManager.default.getConstants is not a function
    at ./node_modules/@react-navigation/elements/lib/module/Header/HeaderBackButton.js (HeaderBackButton.tsx:207:41)
    at __webpack_require__ (bootstrap:79:1)
    at ./node_modules/@react-navigation/elements/lib/module/index.js (index.tsx:5:1)
    at __webpack_require__ (bootstrap:79:1)
    at ./node_modules/@react-navigation/drawer/lib/module/views/DrawerView.js (DrawerView.tsx:1:1)
    at __webpack_require__ (bootstrap:79:1)
    at ./node_modules/@react-navigation/drawer/lib/module/navigators/createDrawerNavigator.js (createDrawerNavigator.tsx:20:1)
    at __webpack_require__ (bootstrap:79:1)
    at ./node_modules/@react-navigation/drawer/lib/module/index.js (index.tsx:4:1)
    at __webpack_require__ (bootstrap:79:1)
    
```

![Screenshot 2023-09-20 at 13 18 29](https://github.com/react-navigation/react-navigation/assets/1659402/8bf34e50-83bf-4951-bfdf-af0469821504)

### Expected behavior

Proper execution during runtime

### Reproduction

https://codesandbox.io/s/react-native-web-playground-getconstants-error-rmkjdn?file=/src/App.js

### Platform

- [ ] Android
- [ ] iOS
- [X] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [x] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [x] @react-navigation/material-top-tabs
- [x] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.1.7
| @react-navigation/bottom-tabs          | 6.5.8
| @react-navigation/drawer               | 6.6.3
| @react-navigation/material-top-tabs    | 6.6.3
| @react-navigation/stack                | 6.3.17
| @react-navigation/native-stack         |
| react-native-safe-area-context         |
| react-native-screens                   |
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native-tab-view                  | 3
| react-native-pager-view                |
| react-native                           |
| expo                                   |
| node                                   |
| npm or yarn                            |

```json
"@react-navigation/bottom-tabs": "6.5.8",
"@react-navigation/drawer": "6.6.3",
"@react-navigation/material-top-tabs": "6.6.3",
"@react-navigation/native": "6.1.7",
"@react-navigation/stack": "6.3.17",
```

**Comment by juanchaur** [comment]
Here's a codesandbox to reproduce the issue:
 
https://codesandbox.io/s/react-native-web-playground-getconstants-error-rmkjdn?file=/src/App.js

![Screenshot 2023-09-20 at 17 46 03](https://github.com/react-navigation/react-navigation/assets/1659402/c89fc64b-30a5-4cc4-9041-b31203993ba7)

**Comment by satya164** [comment]
You're using a very old version of `react-native-web` and need to upgrade.
