### ISSUE TITLE
Unexpected go back on react-navigation inside nested navigations

### ISSUE THREAD

**Issue by satyabrata-dash5** [react-navigation/react-navigation#11611]
### Current behavior

mainstack.js called on App.js
then inside MainStack.js there 3 stack navigator 

- MainSatack
                -IntroVideo
                -AuthStack
                -AppStack

Inside AuthStack the login, signup, forgot password was handled 
and inside AppStack the initial screen was the bottom tab and then all tabs were there 

- AppStack
          -BottomTab
          -ProfileScreen
          -EditProfile

inside the Bottom tab, the HomeScreen was there on the tab screen

- BottomTab
        - Home
        - Vide0
        - Feed

So the issue was when I navigated from Home (BottomaTab) to AppStack Profile, Navigation successfully navigated and suddenly back to the previous one. I have added initial:false on every navigation but it did not work.

### Expected behaviour

It was not happening and it was not going back suddenly at all

### Reproduction

no

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

     @react-native-masked-view/masked-view": "^0.2.9",
    "@react-navigation/bottom-tabs": "^6.5.8",
    "@react-navigation/material-top-tabs": "^6.6.3",
    "@react-navigation/native": "^6.1.7",
    "@react-navigation/native-stack": "^6.9.13",
    "@react-navigation/stack": "^6.3.17",
     "react": "18.2.0",
     "react-native": "^0.72.4",
     "react-native-screens": "^3.25.0",

**Comment by osdnk** [comment]
Hey,
Thanks for the issue. However, without a proper minimal example (one file or expo snack), we cannot really understand all details of the issues. Although, the problems you described seems to be a pretty regular react-navigation usage, I cannot see sufficient level of details. 

Unfortunately, for the time being, I decide to close the issue, while waiting for further details.
