### ISSUE TITLE
Native Stack Navigator combining headerTransparent headerBlurEffect and headerShadowVisible does not work correctly on iOS 

### ISSUE THREAD

**Issue by jobpaardekooper** [react-navigation/react-navigation#11618]
### Current behavior

Using screenOptions for the stack navigator on iOS as follows:
```jsx
{
    headerTransparent: true,
    headerBlurEffect: 'systemMaterial',
    headerShadowVisible: true,
}
```

Does not display the line on the bottom of the header on iOS.

### Expected behavior

There should be a way to achieve the same header behavior as the iOS settings app where there is a blured background and gray line at the bottom. Here is a screenshot of the iOS settings header:

![IMG_C7818C1133C4-1](https://github.com/react-navigation/react-navigation/assets/34612663/3798e3d7-b57a-4be5-aa8c-918e7969089e)

### Reproduction

-

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |6.1.8
| @react-navigation/native-stack         |6.9.14
| react-native-screens                   |3.25.0
| react-native                           | 0.72.5
| node                                   | v16.13.0
| npm or yarn                            | 8.1.4

**Comment by jobpaardekooper** [comment]
The issue still exists.

**Comment by ljukas** [comment]
Can confirm

**Comment by jobpaardekooper** [comment]
Having a bot like this is not very productive...

I know it takes a bunch of time to go trough issues and I should really add a reproduction repo but, like the reviewers of these issues, I am also busy. This is not a super big critical issue so it is not such a big deal that it is not fixed but it is nice to have an issue that at least documents the problem is there.

**Comment by smontlouis** [comment]
@jobpaardekooper having the same issue. 
Did you manage to fix it ?

**Comment by jobpaardekooper** [comment]
No I did not fix it.

**Comment by smontlouis** [comment]
Found a workaround:

```
headerStyle: {
            backgroundColor:
                colorScheme === 'dark'
                  ? 'rgba(0,0,0,0.05)'
                  : 'rgba(255,255,255,0.05)'
          },
          ```

Instead of headerTransparent
