### ISSUE TITLE
bottom-tabs issue navigation touch icon

### ISSUE THREAD

**Issue by tupywebteam** [react-navigation/react-navigation#11633]
### Current behavior

On physical android device, does not respond to bottom-tabs navigation when click on icon

https://github.com/react-navigation/react-navigation/assets/50232450/3e90a8c7-4cb8-46ed-acb5-1baa0eb9031f

### Expected behavior

Match navigation when icon click

### Reproduction

https://github.com/tupywebteam/react-nativation-bottom-tab-issue

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |6.1.8
| @react-navigation/bottom-tabs          |6.5.9
| @react-navigation/stack                |6.3.18
| @react-navigation/native-stack         |6.9.14
| react-native-safe-area-context         |4.7.2
| react-native-screens                   |3.25.0
| react-native-gesture-handler           |2.13.1
| react-native-reanimated                |3.5.4
| react-native                           |0.72.5
| node                                   |18.18.0
| npm or yarn                            |9.8.1

**Comment by tupywebteam** [comment]
Done

> Couldn't find version numbers for the following packages in the issue:
> 
> * `@react-navigation/drawer`
> * `@react-navigation/material-top-tabs`
> * `react-native-tab-view`
> 
> Can you update the issue to include version numbers for those packages? The version numbers must match the format 1.2.3.

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |6.1.8
| @react-navigation/bottom-tabs          |6.5.9
| @react-navigation/stack                |6.3.18
| @react-navigation/native-stack         |6.9.14
| react-native-safe-area-context         |4.7.2
| react-native-screens                   |3.25.0
| react-native-gesture-handler           |2.13.1
| react-native-reanimated                |3.5.4
| react-native                           |0.72.5
| node                                   |18.18.0
| npm or yarn                            |9.8.1

**Comment by tupywebteam** [comment]
After reading this issue (https://github.com/react-navigation/react-navigation/issues/11634)
I solved it by disabling the new architecture

**Comment by caspg** [comment]
@damasofc Did you solve it by any chance? I have similar issue but with new arch disabled. Sometimes clicking on icon stops working.
