### ISSUE TITLE
App crash for Android 

### ISSUE THREAD

**Issue by sagarj-iprogrammer** [react-navigation/react-navigation#11636]
### Current behavior

App Crash when switch between tab

### Expected behavior

App shouild not crash 

### Reproduction

-

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [X] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [X] react-native-tab-view

### Environment

  "react": "18.2.0",
    "react-native": "0.72.2",
    "@react-navigation/native": "^6.0.13",
    "@react-navigation/native-stack": "^6.9.1",
    "@react-navigation/stack": "^6.3.2",
    "react-native-gesture-handler": "2.12.0",
    "react-native-reanimated": "3.4.0",
    "react-native-safe-area-context": "^4.4.1",
    "react-native-screens": "3.21.0",
    "react-native-tab-view": "^3.3.0",
    "@react-navigation/material-top-tabs": "6.2.1",
    "react-native-pager-view": "6.1.2"
    
    
    ------------------
import * as React from 'react';
import { Text, View } from 'react-native';
import { NavigationContainer } from '@react-navigation/native';
import { createMaterialTopTabNavigator } from '@react-navigation/material-top-tabs';

function HomeScreen() {
  return (
    <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
      <Text>Home!</Text>
    </View>
  );
}

function SettingsScreen() {
  return (
    <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
      <Text>Settings!</Text>
    </View>
  );
}

const Tab = createMaterialTopTabNavigator();

export default function App() {
  return (
    <NavigationContainer>
      <Tab.Navigator>
        <Tab.Screen name="Home" component={HomeScreen} />
        <Tab.Screen name="Settings" component={SettingsScreen} />
      </Tab.Navigator>
    </NavigationContainer>
  );
}
 for new Arch false did not  crash  when enable new Arch true app get crash when fast switching with @react-navigation/material-top-tabs @satya164

**Comment by sagarj-iprogrammer** [comment]
Tried with latest veriosn 
   "react": "18.2.0",
    "react-native": "0.72.2",
    "@react-navigation/native": "^6.1.8",
    "@react-navigation/native-stack": "^6.3.18",
    "@react-navigation/stack": "^6.3.2",
    "react-native-gesture-handler": "2.12.0",
    "react-native-reanimated": "3.4.0",
    "react-native-safe-area-context": "^4.4.1",
    "react-native-screens": "3.21.0",
    "react-native-tab-view": "^3.5.2",
    "@react-navigation/material-top-tabs": "^6.6.4",
    "react-native-pager-view": "^6.1.2"
    
    
Still crashing on switch

**Comment by sagarjeu** [comment]
@okwasniewski  you can create simple init app and added the required dependency  with above versions

**Comment by sagarj-iprogrammer** [comment]
@okwasniewski  you can create simple init app and added the required dependency with above versions

**Comment by sagarj-iprogrammer** [comment]
any update ?

**Comment by pc9** [comment]
@sagarj-iprogrammer Try setting `detachInactiveScreens={false}` [https://reactnavigation.org/docs/bottom-tab-navigator/#detachinactivescreens](https://reactnavigation.org/docs/bottom-tab-navigator/#detachinactivescreens) Worked for me.
