### ISSUE TITLE
useHeaderHeight() returns incorrect height for ios

### ISSUE THREAD

**Issue by itsramiel** [react-navigation/react-navigation#11655]
### Current behavior

I am trying to create a full screen vertical scroll window so I need to get the height of the window, using useWindowDimensions, minus the header height, using useHeaderHeight. Here is a simple reproducable:
```
// In App.js in a new project
import * as React from "react";
import { View, useWindowDimensions } from "react-native";
import { useHeaderHeight } from "@react-navigation/elements";
import { NavigationContainer, DefaultTheme } from "@react-navigation/native";
import { createNativeStackNavigator } from "@react-navigation/native-stack";

function HomeScreen() {
  const { height: windowHeight } = useWindowDimensions();
  const headerHeight = useHeaderHeight();
  return (
    <View
      style={{
        height: windowHeight - headerHeight,
        backgroundColor: "black",
      }}
    />
  );
}

const Stack = createNativeStackNavigator();

function App() {
  return (
    <NavigationContainer
      theme={{
        ...DefaultTheme,
        colors: { ...DefaultTheme.colors, background: "white" },
      }}
    >
      <Stack.Navigator>
        <Stack.Screen name="Home" component={HomeScreen} />
      </Stack.Navigator>
    </NavigationContainer>
  );
}

export default App;
```

But this will leave a very small ~1px at the bottom:
<img width="1376" alt="Screenshot 2023-10-24 at 8 56 40 AM" src="https://github.com/react-navigation/react-navigation/assets/80689446/3595ace4-19dd-4efd-b99f-e35780d86aa9">

The issue is here is that when making a vertically scrolling list that takes the whole screen then each slide will be 1 pixel short and eventually the gap will increase with every slide. Also UI look not good when you have contrasting colors as you see the white line at the bottom

### Expected behavior

I expect `useHeaderHeight` to return the correct value

### Reproduction

https://github.com/itsramiel/HeaderHeightIos

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |  6.1.9
| @react-navigation/native-stack         | 6.9.16
| react-native-safe-area-context         | 4.6.3
| react-native-screens                   | 3.26.0
| react-native                           | 0.72.6
| expo                                   | 49.0.16
| node                                   | 18.17.1
| yarn                            | 1.22.19

**Comment by itsramiel** [comment]
> The versions mentioned in the issue for the following packages differ from the latest versions on npm:
> 
>     * `@react-navigation/native` (found: `6.9.16`, latest: `6.1.9`)
> 
> 
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?

Fixed it

**Comment by itsramiel** [comment]
Using onLayout returns ``754.333312988281` while `useWindowDimensions().height - useHeaderHeight()` return `754`. The pixel density is 3 pixels per point so it is exactly missing 1 pixel. I am not sure if this is a rounding error somewhere?

**Comment by tboba** [comment]
Hi @itsramiel, I think I have spotted the same problem, where `useHeaderHeight` may be invalid indeed - when I'm checking the header height with use of `useAnimatedHeaderHeight` For the small header I'm getting `97.66666666666666` value and for the large header - `149.66666666666666`.
Can you check whether adding `0.66666666666666` value to to header height fixes your problem? Also, have you checked if on iOS 16 this value is still correct (`98`/`150`)?

**Comment by itsramiel** [comment]
Hi @tboba 

`useHeaderHeight` retursn 98, which is 0.3333333 more than the real value. The value you mentioned `97.66666666666666` is correct.

When using `useHeaderHeight` as it is. There is a small space at the bottom and it gets clearer the more you scroll since it compounds as every View is 0.333333 shorter than it should. Check the video here at the very bottom:

https://github.com/react-navigation/react-navigation/assets/80689446/11b42377-e798-4da2-8415-b50d20aadfc7

> Can you check whether adding 0.66666666666666 value to to header height fixes your problem?

I think what I need to do is to subtract 0.333333333 since useHeaderHeight returns 98 but you mentioned useAnimatedHeaderHeight return 97.6666666666. If I do that then the View takes the entire available space as is expected 👍:

https://github.com/react-navigation/react-navigation/assets/80689446/b444260f-abff-4dc0-b75e-6291d62ce1e6

> Also, have you checked if on iOS 16 this value is still correct (98/150)?
Unfortunately I do not have access to Ios 16 simulator since I am on macos 14. I have a physical device on ios 16 but it is a notchles iphone 8, so I dont think it applies there.

I hope you are able to narrow down the source of the issue.

**Comment by gianlucalippolis** [comment]
Hy @itsramiel, i fixed the bug in this PR https://github.com/react-navigation/react-navigation/pull/11786
