### ISSUE TITLE
Don't work DeepLink 

### ISSUE THREAD

**Issue by ValyaBabenkov** [react-navigation/react-navigation#11650]
### Current behavior

Good afternoon.

Can you tell me how to implement DeepLink in navigation.
The navigation itself is multi-nested and consists of various Stack/Tab/Drawer navigation buttons

On demand via safari appS://test
The app opens but the navigation does not go to the "NotificationsScene" screen

My code:

```
const linking = {
    prefixes: ['appS://'],
    config: {
        screens: {
            DrawerScene: {
                screens: {
                    Tab : {
                        screens :{
                            NotificationsScene: {
                                path: 'test'
                            }
                        }
                    }
                }
            }
        },
    },
}
<NavigationContainer ref={navigationRef}
                onStateChange={(state) => console.log('New state is', state)}
                linking={linking}>
                {isLoading ? <View className={'flex-1 bg-wc-bg items-center justify-center'}><ActivityIndicator/></View> :
                    profile?.id ?  <MainStack/> : <AuthStackNavigation/>}
</NavigationContainer>
```
<img width="618" alt="Снимок экрана 2023-10-20 в 01 43 53" src="https://github.com/react-navigation/react-navigation/assets/53038415/14c4b0f8-f670-4789-adae-e88b4afbabeb">

### Expected behavior

Result, go to the NotificationsScene screen

### Reproduction

-

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

"react": "18.1.0",
"react-native": "0.70.10",
"@react-navigation/bottom-tabs": "^6.5.8",
"@react-navigation/drawer": "^6.6.3",
"@react-navigation/native": "^6.1.7",
"@react-navigation/native-stack": "^6.9.13",          
"react-native-safe-area-context": "^4.7.1",
"react-native-screens": "^3.24.0",

**Comment by ValyaBabenkov** [comment]
Updated the dependencies, the problem with the transition remains

**Comment by radko93** [comment]
Check exact paths https://reactnavigation.org/docs/configuring-links/#matching-exact-paths
This is unfortunately not a bug report so I will have to close it.
