### ISSUE TITLE
Bottom Tab Navigator show Rectangle icons in React Navigation 6.1.8 (Desktop app)

### ISSUE THREAD

**Issue by OoChaPtpn** [react-navigation/react-navigation#11658]
### Current behavior

**Problem:**
I'm trying to use icons in my project ( **React Native for Windows app** ) from React Native Vector Icons and it work very well in android but in Desktop app is show Rectangle.

![image](https://github.com/react-navigation/react-navigation/assets/138839110/19959aca-b0b5-4130-a2d7-f81a0546a583)

### Expected behavior

Icons show on bottom tab navigator

### Reproduction

-

### Platform

- [ ] Android
- [ ] iOS
- [ ] Web
- [X] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

Environment:

| package                                | version |
| -------------------------------------- | ------- |
| react-native-windows  |  0.72.14  |
| Target Platform Version  |  10.0.19041.0  |
| react-native-vector-icons  |  ^10.0.0  |
| react-native  |  0.72.6 |
| react-native-gesture-handler  |  ^2.13.3  |
| react-native-screens  |  ^3.26.0  |  
| @react-navigation/native  |  6.1.9  |

**Comment by OoChaPtpn** [comment]
@react-navigation/native  6.1.9

**Comment by satya164** [comment]
Icon components are provided by you, so it'll render whatever you provide. You can render those icons outside the tab bar and verify.

**Comment by OoChaPtpn** [comment]
> Icon components are provided by you, so it'll render whatever you provide. You can render those icons outside the tab bar and verify.

I try to set icon outside the tab bar but it not show too

![image](https://github.com/react-navigation/react-navigation/assets/138839110/71660ee9-8385-4ff8-b189-f6c29a5ea729)
