### ISSUE TITLE
After Closing Presented Modal Stack Screen breaks SafeAreaView

### ISSUE THREAD

**Issue by oguzydz** [react-navigation/react-navigation#11664]
### Current behavior

Actually, you see the bug in the video on the attachment. Let me explain the flow. I added a stack screen as a presented modal style. I navigate from BottomBar Navigator to Stack Navigator. It breaks SafeAreaView insets (react-native-safearea-context).

Note: When I use useSafeAreaInsets() instead of SafeAreaView component it could not breaks insets of safe areas. However, it does not being useful because of the SafeAreaView features such as nearest providers insets.

In the snack, the SafeAreaView is not being breaked :)

https://github.com/react-navigation/react-navigation/assets/36233491/c9297352-7a93-451e-bf1d-f6fff30ff04f

### Expected behavior

I expect it should not breaks SafeAreaView when I close to presented modal stack screen to bottom bar screen.

### Reproduction

https://snack.expo.dev/@oguzydz/simple-case

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | ^6.1.7
| @react-navigation/bottom-tabs          |  ^6.5.8
| @react-navigation/drawer               | not use
| @react-navigation/material-top-tabs    | not use
| @react-navigation/stack                | ^6.3.17
| @react-navigation/native-stack         | not use
| react-native-safe-area-context         |  ^4.7.2
| react-native-screens                   | ^3.25.0
| react-native-gesture-handler           | ^2.12.1
| react-native-reanimated                | ^3.4.2
| react-native-tab-view                  | ^3.5.2
| react-native-pager-view                | 6.2.1
| react-native                           | ^0.72.4
| expo                                   | (not use)
| node                                   | v18.16.0
| npm or yarn                            | 9.6.7 (npm)

**Comment by oguzydz** [comment]
any update on this?

**Comment by andrewzey** [comment]
I too am having this exact issue. 

My version numbers are:
`@react-navigation/native` on `6.1.9`
`@react-navigation/bottom-tabs` on `6.5.11`
`@react-navigation/stack` on `6.3.20`

I am not using `@react-navigation/drawer` or `@react-navigation/material-top-tabs`

**Comment by ink404** [comment]
Another fix might be changing the presentation style to `containedModal` or `containedTransparentModal`.

**Comment by muhammadarsal** [comment]
+1

**Comment by YousefMohsen** [comment]
Any new on this ? I have the same issue

**Comment by satya164** [comment]
React Navigation doesn't control the insets of the safe area context library. If it's breaking in specific scenario, please open the issue in the library's repo.
