### ISSUE TITLE
useLinkBuilder() undefined is not a function

### ISSUE THREAD

**Issue by hongyingyang78** [react-navigation/react-navigation#11689]
### Current behavior

Create a new project, add @react-navigation/bottom-tabs 

<img width="583" alt="截屏2023-11-08 10 33 37" src="https://github.com/react-navigation/react-navigation/assets/143774358/e53b0106-2829-4da6-a1a7-38cd7b5a114f">

version：
  "dependencies": {
    "@react-native-masked-view/masked-view": "^0.3.0",
    "@react-navigation/bottom-tabs": "^6.5.11",
    "@react-navigation/native": "^7.0.0-alpha.4",
    "@react-navigation/stack": "^6.3.20",
    "react": "18.2.0",
    "react-native": "0.71.6",
    "react-native-gesture-handler": "^2.13.4",
    "react-native-safe-area-context": "^4.7.4",
    "react-native-screens": "^3.27.0"
  },

code:

<img width="760" alt="截屏2023-11-08 11 23 23" src="https://github.com/react-navigation/react-navigation/assets/143774358/ffb3126c-8ced-448d-a360-6e17add8e174">

### Expected behavior

The bottom tab is displayed normally

### Reproduction

    <NavigationContainer>       <Tab.Navigator screenOptions={{headerShown: false}}>         <Tab.Screen name="Home" component={HomePage} />         <Tab.Screen name="Settings" component={SettingPage} />       </Tab.Navigator>     </NavigationContainer>

### Platform

- [ ] Android
- [x] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [x] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [x] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |  7.0.0-alpha.4
| @react-navigation/bottom-tabs          |   6.5.11
| @react-navigation/stack                | 6.3.20
| react-native-safe-area-context         | 4.7.4
| react-native-screens                   |.  3.27.0
| react-native-gesture-handler           |. 2.13.4
| react-native-reanimated                |   3.5.4
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           |    0.71.6
| node                                   |   v16.14.2
| npm or yarn                            | npm 8.5.0     yarn1.6.0

**Comment by satya164** [comment]
You cannot mix 7.x and 6.x versions of navigation packages.
