### ISSUE TITLE
Adding custom button inside stack navigation lead no pop animation on navigation.goBack();

### ISSUE THREAD

**Issue by mobileexpert1** [react-navigation/react-navigation#11683]
### Current behavior

Currently when i am adding custom button inside stack navigation there is no animation on goBack();

Here is code snippet and Video attached below :

`const Stack = createNativeStackNavigator();
	const NavStack =()=>{

		return <Stack.Navigator  screenOptions={{
			
			headerTitle: mapRouteName, 
			headerBackTitle:'Go Back',
			header:({navigation})=>{
				return <HeaderWithButton
					currentScreenName={mapRouteName}
					onBackButtonPress={() => {
						navigation.goBack();
					}}
					onProfilePress={() => {
						handleOpenModal();
					}}

https://github.com/react-navigation/react-navigation/assets/9291694/585f7ebd-42b6-43a9-af2e-588284358755

				/>;
			}
		
		}}
		>`

### Expected behavior

The custom header should work like default header in header.

`const Stack = createNativeStackNavigator();
	const NavStack =()=>{

		return <Stack.Navigator  screenOptions={{
			
			headerTitle: mapRouteName, 

https://github.com/react-navigation/react-navigation/assets/9291694/a50ebe27-4b79-40ec-bb60-af08ca1d6d27

			headerBackTitle:'Go Back',
		
		}}
		>`

### Reproduction

none

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |  ^6.1.7
| @react-navigation/drawer               | ^6.6.3
| @react-navigation/stack                | ^6.3.17
| @react-navigation/native-stack         | ^6.9.13
| react-native-safe-area-context         | ^4.7.1
| react-native-screens                   | ^3.24.0
| react-native-gesture-handler           | ^2.12.1
| react-native-reanimated                | ^3.4.2
| react-native                           | 0.71.6
| node                                   | v18.12.1
| npm or yarn                            | yarn

**Comment by mobileexpert1** [comment]
Tried with the latest versions as well .

**Comment by Nehal-Zeller** [comment]
hey @mobileexpert1  

were you able to find any solution? I've a similar scenario and animation on dismissing modal is not working
