### ISSUE TITLE
[React Native 0.73.0] Drawer is crashing on latest RC 0.73.0-rc.4

### ISSUE THREAD

**Issue by ravindraguptacapgemini** [react-navigation/react-navigation#11693]
### Current behavior

App is crashing on navigating to drawer.

 ERROR  TypeError: undefined is not an object (evaluating '_$$_REQUIRE(_dependencyMap[1], "../core").makeMutable')

This error is located at:
    in Drawer (created by DrawerViewBase)
    in DrawerViewBase (created by DrawerView)
    in RNGestureHandlerRootView (created by GestureHandlerRootView)
    in GestureHandlerRootView (created by DrawerView)
    in RCTView (created by View)
    in View (created by SafeAreaInsetsContext)
    in SafeAreaProviderCompat (created by DrawerView)
    in DrawerView (created by DrawerNavigator)
    in PreventRemoveProvider (created by NavigationContent)
    in NavigationContent
    in Unknown (created by DrawerNavigator)
    in DrawerNavigator (created by AuthenticatedArea)
    in AuthenticatedArea (created by SceneView)
    in StaticContainer
    in EnsureSingleNavigator (created by SceneView)
    in SceneView (created by CardContainer)
    in RCTView (created by View)
    in View (created by CardContainer)
    in RCTView (created by View)
    in View (created by CardContainer)
    in RCTView (created by View)
    in View
    in CardSheet (created by Card)
    in RCTView (created by View)
    in View
    in Unknown (created by PanGestureHandler)
    in PanGestureHandler (created by PanGestureHandler)
    in PanGestureHandler (created by Card)
    in RCTView (created by View)
    in View
    in Unknown (created by Card)
    in RCTView (created by View)
    in View (created by Card)
    in Card (created by CardContainer)
    in CardContainer (created by CardStack)
    in RNSScreen
    in Unknown (created by InnerScreen)
    in Suspender (created by Freeze)
    in Suspense (created by Freeze)
    in Freeze (created by DelayedFreeze)
    in DelayedFreeze (created by InnerScreen)
    in InnerScreen (created by Screen)
    in Screen (created by MaybeScreen)
    in MaybeScreen (created by CardStack)
    in RNSScreenContainer (created by ScreenContainer)
    in ScreenContainer (created by MaybeScreenContainer)
    in MaybeScreenContainer (created by CardStack)
    in RCTView (created by View)
    in View (created by Background)
    in Background (created by CardStack)
    in CardStack (created by HeaderShownContext)
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by SafeAreaInsetsContext)
    in SafeAreaProviderCompat (created by StackView)
    in RNGestureHandlerRootView (created by GestureHandlerRootView)
    in GestureHandlerRootView (created by StackView)
    in StackView (created by StackNavigator)
    in PreventRemoveProvider (created by NavigationContent)
    in NavigationContent
    in Unknown (created by StackNavigator)
    in StackNavigator (created by AppNavigator)
    in AppNavigator (created by App)
    in RCTView (created by View)
    in View (created by App)
    in EnsureSingleNavigator
    in BaseNavigationContainer
    in ThemeProvider
    in NavigationContainerInner (created by App)
    in App (created by Connect(App))
    in Connect(App) (created by intelexMobile)
    in Provider (created by intelexMobile)
    in intelexMobile
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in intelexMobile(RootComponent)
 ERROR  Error: Exception in HostFunction: java.lang.NoSuchFieldError: no "Lcom/facebook/react/fabric/BindingImpl;" field "mBinding" in class "Lcom/facebook/react/fabric/FabricUIManager;" or its superclasses
 ERROR  Error: Exception in HostFunction: java.lang.NoSuchFieldError: no "Lcom/facebook/react/fabric/BindingImpl;" field "mBinding" in class "Lcom/facebook/react/fabric/FabricUIManager;" or its superclasses
 ERROR  Error: Exception in HostFunction: java.lang.NoSuchFieldError: no "Lcom/facebook/react/fabric/BindingImpl;" field "mBinding" in class "Lcom/facebook/react/fabric/FabricUIManager;" or its superclasses
 ERROR  Error: Exception in HostFunction: java.lang.NoSuchFieldError: no "Lcom/facebook/react/fabric/BindingImpl;" field "mBinding" in class "Lcom/facebook/react/fabric/FabricUIManager;" or its superclasses
 ERROR  TypeError: undefined is not an object (evaluating '_$$_REQUIRE(_dependencyMap[1], "../core").makeMutable')

This error is located at:
    in Drawer (created by DrawerViewBase)
    in DrawerViewBase (created by DrawerView)
    in RNGestureHandlerRootView (created by GestureHandlerRootView)
    in GestureHandlerRootView (created by DrawerView)
    in RCTView (created by View)
    in View (created by SafeAreaInsetsContext)
    in SafeAreaProviderCompat (created by DrawerView)
    in DrawerView (created by DrawerNavigator)
    in PreventRemoveProvider (created by NavigationContent)
    in NavigationContent
    in Unknown (created by DrawerNavigator)
    in DrawerNavigator (created by AuthenticatedArea)
    in AuthenticatedArea (created by SceneView)
    in StaticContainer
    in EnsureSingleNavigator (created by SceneView)
    in SceneView (created by CardContainer)
    in RCTView (created by View)
    in View (created by CardContainer)
    in RCTView (created by View)
    in View (created by CardContainer)
    in RCTView (created by View)
    in View
    in CardSheet (created by Card)
    in RCTView (created by View)
    in View
    in Unknown (created by PanGestureHandler)
    in PanGestureHandler (created by PanGestureHandler)
    in PanGestureHandler (created by Card)
    in RCTView (created by View)
    in View
    in Unknown (created by Card)
    in RCTView (created by View)
    in View (created by Card)
    in Card (created by CardContainer)
    in CardContainer (created by CardStack)
    in RNSScreen
    in Unknown (created by InnerScreen)
    in Suspender (created by Freeze)
    in Suspense (created by Freeze)
    in Freeze (created by DelayedFreeze)
    in DelayedFreeze (created by InnerScreen)
    in InnerScreen (created by Screen)
    in Screen (created by MaybeScreen)
    in MaybeScreen (created by CardStack)
    in RNSScreenContainer (created by ScreenContainer)
    in ScreenContainer (created by MaybeScreenContainer)
    in MaybeScreenContainer (created by CardStack)
    in RCTView (created by View)
    in View (created by Background)
    in Background (created by CardStack)
    in CardStack (created by HeaderShownContext)
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by SafeAreaInsetsContext)
    in SafeAreaProviderCompat (created by StackView)
    in RNGestureHandlerRootView (created by GestureHandlerRootView)
    in GestureHandlerRootView (created by StackView)
    in StackView (created by StackNavigator)
    in PreventRemoveProvider (created by NavigationContent)
    in NavigationContent
    in Unknown (created by StackNavigator)
    in StackNavigator (created by AppNavigator)
    in AppNavigator (created by App)
    in RCTView (created by View)
    in View (created by App)
    in EnsureSingleNavigator
    in BaseNavigationContainer
    in ThemeProvider
    in NavigationContainerInner (created by App)
    in App (created by Connect(App))
    in Connect(App) (created by intelexMobile)
    in Provider (created by intelexMobile)
    in intelexMobile
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in intelexMobile(RootComponent)

### Expected behavior

It should not crash on navigating to drawer.

### Reproduction

https://snack.expo.dev/

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/drawer               |6.6.6|
| @react-navigation/stack                |6.3.20|
| react-native-safe-area-context         |4.7.4|
|@react-navigation/native         |6.1.9|
| react-native-screens                   |@kkafar/rn-73|
| react-native-gesture-handler           |@jpiasecki/support-rn-73|
| react-native-reanimated                |master|
| react-native                           |0.73.0-rc.4|
| node                                   |v18.17.1|
| npm or yarn                            |10.2.1|

**Comment by migueldaipre** [comment]
Please add a minimal repro code

**Comment by hsjoberg** [comment]
I think that this error is related to a bug in react-native 0.73.0, causing react-native-reanimated to flip out.
You can read more here: https://github.com/software-mansion/react-native-reanimated/issues/5472

Sadly a fix wasn't picked for https://github.com/reactwg/react-native-releases/discussions/64#discussioncomment-7693949, so we need to wait for 0.73.1.

**Comment by migueldaipre** [comment]
Probably will be fixed with this https://github.com/software-mansion/react-native-reanimated/pull/5550 and upgrading React Native to 0.73.1.

Add this in your **`proguard-rules.pro`** until a new patch release with the fix.

`-keep class com.facebook.react.fabric.** { *; }`

**Comment by Mwajahath** [comment]
I'm getting same issue is RN 0.73.2

**Comment by waqid** [comment]
same issue too in RN 0.73.2 it said
`MainApplication.kt:25:9 A 'return' expression required in a function with a block body ('{...}')`

**Comment by PolaroidZone** [comment]
Hello, I'm getting this issue on version 0.73.4. Has anyone found a fix for it yet?

**Comment by anatooly** [comment]
I have some issue only on release Android build, on debug all fine.

Logcat:
`Error: Exception in HostFunction: expected 1 arguments, got 0, js engine: hermes
E  TypeError: Cannot read property 'isConfigured' of undefined
                                                                                                    
This error is located at:
    in DrawerViewBase
    in RNGestureHandlerRootView
    in GestureHandlerRootView
    ...`

**Comment by anatooly** [comment]
> same issue too in RN 0.73.2 it said `MainApplication.kt:25:9 A 'return' expression required in a function with a block body ('{...}')`

This problem you code migrate from java to kotlin, when upgrade RN 0.72->0.73 or some manual code on this file. It's not issues react-navigation.
