### ISSUE TITLE
`headerBackImageSource` tintColor not applied (Android only)

### ISSUE THREAD

**Issue by eightyfive** [react-navigation/react-navigation#11697]
### Current behavior

If I use a custom `headerBackImageSource` asset for my back button:
```ts
const options: NativeStackNavigationOptions = {
  headerBackImageSource: require("./assets/back-icon.png"),
}
```

The tint color (`NavigationTheme.colors.primary`) is not applied on Android devices. It is applied normally on iOS devices.

### Expected behavior

Tint/primary color applied on Android devices.

### Reproduction

https://github.com/eightyfive/react-navigation-repro-back-source

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.1.9
| @react-navigation/native-stack         | 6.9.17
| react-native-safe-area-context         | 4.6.3
| react-native-screens                   | 3.22.1
| react-native                           | 0.72.6
| expo                                   | 49.0.18
| node                                   | 21.1.0
| npm                            | 10.2.0

**Comment by eightyfive** [comment]
It seems like the tint color is never applied on Android devices, even if not using `headerBackImageSource`.

For the time being I found a hacky workaround:

```ts
<Stack.Navigator screenOptions={{
        // headerBackImageSource: require("./assets/back-icon.png"),
        headerTintColor: 'red',
        headerTitleStyle: {
          color: 'black'
        }
}}>
```

**Comment by satya164** [comment]
The header implements the native UI and conventions of the platform. If you want a different behavior that doesn't match native then you can use a custom header or a custom back button.

**Comment by eightyfive** [comment]
Fair enough. But this should be documented? (That Android will display the image as-is).

For example when supporting light & dark themes, the back icon color won't change (this is how I noticed in my app).
