### ISSUE TITLE
While trying to resolve module use-latest-callback from file ... the package ...  was successfully found. However, this package itself specifies a main module field that could not be resolved

### ISSUE THREAD

**Issue by 6vz** [react-navigation/react-navigation#11690]
### Current behavior

There is a issue with some @react-navigation module that seems related to it. Every time I try to run it with Expo or even build using EAS it shows this error. 
```
Metro has encountered an error: While trying to resolve module `use-latest-callback` from file `/Users/matt/Documents/GitHub/app-candidate.nosync/node_modules/@react-navigation/core/src/PreventRemoveProvider.tsx`, the package `/Users/matt/Documents/GitHub/app-candidate.nosync/node_modules/use-latest-callback/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/matt/Documents/GitHub/app-candidate.nosync/node_modules/use-latest-callback/lib/index.js`. Indeed, none of these files exist:

  * /Users/matt/Documents/GitHub/app-candidate.nosync/node_modules/use-latest-callback/lib/index.js(.native|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json)
  * /Users/matt/Documents/GitHub/app-candidate.nosync/node_modules/use-latest-callback/lib/index.js/index(.native|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json): /Users/matt/Documents/GitHub/app-candidate.nosync/node_modules/metro/src/node-haste/DependencyGraph.js (277:17)

  275 |         }
  276 |         if (error instanceof InvalidPackageError) {
> 277 |           throw new PackageResolutionError({
      |                 ^
  278 |             packageError: error,
  279 |             originModulePath: from,
  280 |             targetModuleName: to,

ABI47_0_0RCTFatal
__37-[ABI47_0_0RCTCxxBridge handleError:]_block_invoke
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_drain
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
-[UIApplication _run]
UIApplicationMain
main
start_sim
0x0
```

Really don't know what's the issue - I tried everything, if anyone knows the suggestion, please let me know.

### Expected behavior

App would normally run & build.

### Reproduction

(upon request - very specific issue)

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [X] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |^6.0.10
| @react-navigation/native-stack         |^6.6.2
| react-native-safe-area-context         |4.4.1
| react-native-screens                   |~3.18.0
| react-native-gesture-handler           |~2.8.0
| react-native-reanimated                |~2.12.0
| react-native                           |0.70.8
| expo                                   |~47.0.14
| node                                   |v20.0.0
| npm                             |9.6.4

**Comment by alex-mironov** [comment]
I'm getting the same issue on 
```
    "@react-navigation/native": "^6.1.9",
```

**Comment by 6vz** [comment]
@alex-mironov we don't have repro. Maybe can you provide one? If yes, please send it here, i will put and include your credits.

**Comment by 6vz** [comment]
Would be really appreciated, hit me up when you reproduce this

**Comment by bytemtek** [comment]
My environment is ok.

   "@react-navigation/native": "^6.1.9",
    "@react-navigation/native-stack": "^6.9.17",
    "react": "18.2.0",
    "react-native": "0.72.6",
    "react-native-safe-area-context": "^4.7.4",
    "react-native-screens": "^3.27.0"

**Comment by alex-mironov** [comment]
Ok so it says
```
error: Error: While trying to resolve module `use-latest-callback` from file `/Users/.../node_modules/@react-navigation/core/src/PreventRemoveProvider.tsx`, the package `/Users/.../node_modules/@react-navigation/core/node_modules/use-latest-callback/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/.../node_modules/@react-navigation/core/node_modules/use-latest-callback/lib/index.js`. Indeed, none of these files exist:
```
meaning it's trying to find `core/node_modules/use-latest-callback/lib/index.js`
but indeed right now `index.js` is inside of `src` folder
<img width="304" alt="image" src="https://github.com/react-navigation/react-navigation/assets/2544767/d5c01b4f-798e-4c4a-bbb4-ab4e3b2ed9a5">

**Comment by alex-mironov** [comment]
There is a fix already https://github.com/satya164/use-latest-callback/releases/tag/v0.1.9

**Comment by alex-mironov** [comment]
To me updating the version in `yarn.lock` helped
```
rm yarn.lock
yarn install
```

**Comment by sem4phor** [comment]
workaround: 

```json
// package..json
...
"overrides": {
  "use-latest-callback": "0.1.9"
}
...
```
then `npm i`

**Comment by jkaveri** [comment]
I have this pr to fix the issue: https://github.com/react-navigation/react-navigation/pull/11696

**Comment by osdnk** [comment]
Hey, apparently it got resolved and should be in with the new version
