### ISSUE TITLE
Navigation.push and .navigation function doesn't allow to push params

### ISSUE THREAD

**Issue by CutieCat6778** [react-navigation/react-navigation#11705]
### Current behavior

From issue #11325

Is the issue fixed? I'm currently updated to the latest version and it's still not working.

```json
    "@react-navigation/bottom-tabs": "^6.5.11",
    "@react-navigation/native": "^6.1.9",
    "@react-navigation/native-stack": "^6.9.17",
```

```js
navigation.push("EmailScreen", {
   username: "String",
});
```

```
o overload matches this call.
  Argument of type '["EmailScreen", { username: string; }]' is not assignable to parameter of type '[screen: "EmailScreen"] | [screen: "EmailScreen", params: undefined]'.
    Type '["EmailScreen", { username: string; }]' is not assignable to type '[screen: "EmailScreen", params: undefined]'.
      Type at position 1 in source is not compatible with type at position 1 in target.
        Type '{ username: string; }' is not assignable to type 'undefined'.
  Argument of type '["EmailScreen", { username: string; }]' is not assignable to parameter of type '[screen: keyof RootStackParamList] | [screen: keyof RootStackParamList, params: { screen?: undefined; params?: undefined; initial?: undefined; path?: string | undefined; state: Readonly<...> | ... 1 more ... | undefined; } | ... 8 more ... | undefined]'.
    Type '["EmailScreen", { username: string; }]' is not assignable to type '[screen: keyof RootStackParamList, params: { screen?: undefined; params?: undefined; initial?: undefined; path?: string | undefined; state: Readonly<{ key: string; index: number; routeNames: string[]; history?: unknown[] | undefined; routes: NavigationRoute<...>[]; type: string; stale: false; }> | PartialState<...> ...'.
      Type at position 0 in source is not compatible with type at position 0 in target.
        Type '"EmailScreen"' is not assignable to type 'keyof RootStackParamList'.
```

### Expected behavior

The function will allow to pass params and redirect to the next screen without a problem.

### Reproduction

https://github.com/parties-app/frontend-react/blob/main/screens/authenticationTab/EmailScreen.tsx#L88C22-L88C22

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | ^6.1.9
| @react-navigation/bottom-tabs          | ^6.5.11
| @react-navigation/native-stack         | ^6.9.17
| react-native-safe-area-context         | 4.6.3
| react-native-screens                   | ~3.22.0
| react-native                           | 0.72.6
| expo                                   | ~49.0.15
| node                                   | v18.14.0
| npm                           | 9.3.1

**Comment by satya164** [comment]
You haven't specified any params in your types for `EmailScreen` https://github.com/parties-app/frontend-react/blob/7e11119e0147a045c606c66b15f7db3c39763621/types/screens.ts#L83
