### ISSUE TITLE
@react-navigation/native 6.x typescript type issue

### ISSUE THREAD

**Issue by kenobi91** [react-navigation/react-navigation#11706]
### Current behavior

I upgraded @react-navigation/native from version 5.x to 6.x since version 5.x was failing on react native 0.70.1 due to removeEventListener error. After upgrade build went fine but my precommit hook and ts build are failing with error:

node_modules/@react-navigation/core/lib/typescript/src/types.d.ts:510:120 - error TS1005: '?' expected.

[RouteName in keyof ParamList]?: NonNullable<ParamList[RouteName]> extends NavigatorScreenParams<infer T extends {}> ? string | PathConfig<T> : string | Omit<PathConfig<{}>, 'screens' | 'initialRouteName'>;

I tried solutions like adding @react-navigation/core 6.2.2 but that is making same error. Tried all version from 6.0.0 to 6.1.9. and it is the same.
Any solution for this ? 

### Expected behavior

To pass ts build: tsc -p tsconfig.json --skipLibCheck --resolveJsonModule --noEmit --isolatedModules false

### Reproduction

Dont have it

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native              |  6.1.9
| @react-navigation/bottom-tabs          | ^5.11.7
| @react-navigation/stack                | ^5.13.0
| react-native-safe-area-context         | ^4.7.4
| react-native-screens                   | ^3.27.0
| react-native-reanimated                | 1.13.4
| react-native                           | 0.70.1

**Comment by kenobi91** [comment]
> The versions mentioned in the issue for the following packages differ from the latest versions on npm:
> 
>     * `@react-navigation/core` (found: `6.2.2`, latest: `6.4.10`)
> 
>     * `@react-navigation/bottom-tabs` (found: `5.11.7`, latest: `6.5.11`)
> 
>     * `@react-navigation/stack` (found: `5.13.0`, latest: `6.3.20`)
> 
> 
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?

Yes

**Comment by opatricpires** [comment]
Same issue here.

**Comment by antilakash** [comment]
+1

**Comment by antilakash** [comment]
![Uploading Screenshot 2023-12-19 at 10.36.09 AM.png…]()

**Comment by bytehala** [comment]
+1 The type that doesn't have an error is:

`[RouteName in keyof ParamList]?: NonNullable<ParamList[RouteName]> extends NavigatorScreenParams<infer T> ? string | PathConfig<T> : string | Omit<PathConfig<{}>, 'screens' | 'initialRouteName'>;`

(Removed `extends {}`)

If you have any luck doing `patch-package`, that might work -- however, it's not an ideal solution as it's better to be fixed at the root.

**Comment by bytehala** [comment]
Update, this is "solved" by using the same Typescript version that the project was on when the change happened:

At said commit, it's `"typescript": "^4.9.4"`:

The change was done to fix this issue:
https://github.com/react-navigation/react-navigation/issues/11125

**Comment by fullstackninja864** [comment]
@bytehala How did you solved this issue except downgrading ts?
