### ISSUE TITLE
Types for `getState` are incorrect

### ISSUE THREAD

**Issue by josh-** [react-navigation/react-navigation#11701]
### Current behavior

Calling `getState` on the navigation object from `useNavigation` can return `undefined`, despite the types indicating that this is not possible.

For example, the following code:

```ts
const isStateUndefined = navigation.getState() === undefined;
```

returns the following ESLint error:

```
  29:28  error  Unnecessary conditional, the types have no overlap  @typescript-eslint/no-unnecessary-condition
```

since the return type of `getState` is defined as:

```ts
Readonly<{
    key: string;
    index: number;
    routeNames: never[];
    history?: unknown[] | undefined;
    routes: NavigationRoute<ReactNavigation.RootParamList, never>[];
    type: string;
    stale: false;
}>
```

however in my reproduction it's evident that `getState` can return `undefined`.

### Expected behavior

The types for `getState` indicate that the return type is `State | undefined`.

### Reproduction

https://github.com/josh-/react-navigation-type-repro

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |6.1.9
| @react-navigation/native-stack         |6.9.17
| react-native-safe-area-context         |4.6.3
| react-native-screens                   |3.22.1
| react-native                           |0.72.6
| expo                                   |49.0.18
| node                                   |18.18.2

**Comment by goelbenj** [comment]
I am looking into this too, I will make a PR with what I consider a reasonable solution.

**Comment by roryabraham** [comment]
We've encountered this [here](https://github.com/Expensify/App/issues/32515) and a similar issue [here](https://github.com/Expensify/App/issues/34383) where `navigation.getState().routes` is undefined.

**Comment by MrRefactor** [comment]
Hey! It's Kuba from Callstack - expert contributor group - I'd like to take this issue.

**Comment by roryabraham** [comment]
Haha hi @MrRefactor – this looks like the kind of comment we see a lot on issues in https://github.com/Expensify/App, and while I'd love to assign it to you you might have to talk to @satya164 about that 🙂

**Comment by Yupeng-li** [comment]
Hi @MrRefactor ,

Do you know when the `getState` could return `undefined`?  

We noticed sometimes `getState` returns `undefined` but `getCurrentRoute` returns the route properly. Is this normal? 

I checked https://reactnavigation.org/docs/navigation-state/ and https://reactnavigation.org/docs/use-navigation-state/, but they didn't mention that `getState` could be undefined. 

Many thanks

**Comment by bhandanyan-nomad** [comment]
Does this type need to get updated too? @osdnk @MrRefactor 

https://github.com/react-navigation/react-navigation/blob/main/packages/core/src/types.tsx#L364
