### ISSUE TITLE
cardOverlay children do not receive pointer events

### ISSUE THREAD

**Issue by jonathanj** [react-navigation/react-navigation#11710]
### Current behavior

The default card overlay cannot be dismissed by pressing it, trying to implement a custom overlay that is a `Pressable` does not work because that pressable does not receive pointer events.

There were previous issues about this:
- https://github.com/react-navigation/react-navigation/issues/9524
- https://github.com/react-navigation/react-navigation/issues/10114

But they have been closed pointing at [the documentation](https://reactnavigation.org/docs/stack-navigator/#transparent-modals), which suggests a workaround. The workaround is unsatisfactory (at least from my point of view) because it requires reimplementing a fair amount of machinery that I consider to be the navigation library's job.

I poked around the source code and what seemed to work (without breaking anything else that I could find) was adding `pointerEvents="box-none"` to [this View in Card](https://github.com/react-navigation/react-navigation/blob/d718b717320d41c90051c2a5f849b8d74f518a18/packages/stack/src/views/Stack/Card.tsx#L548-L550).

```tsx
              <Animated.View
                pointerEvents="box-none"
                needsOffscreenAlphaCompositing={hasOpacityStyle(cardStyle)}
                style={[styles.container, cardStyle]}
              >
```

This view occupies the entirety of the screen, but only for layout purposes. Because it is not discarding pointer events and has a more important placement in the hierarchy than the overlay, it receives pointer events instead of the overlay.

### Expected behavior

Implementing a custom `cardOverlay` with `Pressable` should receive pointer events.

### Reproduction

https://snack.expo.dev/@jonathanj/hazardous-yellow-pretzels

### Platform

- [ ] Android
- [ ] iOS
- [X] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.1.9
| @react-navigation/stack                | 6.3.20
| react-native                           | 0.72
| expo                                   |
| node                                   | 18
| npm or yarn                            | yarn

**Comment by jonathanj** [comment]
> The versions mentioned in the issue for the following packages differ from the latest versions on npm:
> 
> * `@react-navigation/native` (found: `6.1.7`, latest: `6.1.9`)
> * `@react-navigation/stack` (found: `6.3.17`, latest: `6.3.20`)
> 
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?

Yes, the issue still exists.

**Comment by satya164** [comment]
Please don't open the same issue again after it has been closed multiple times with link to documentation.

If you want a new feature then use the proper channel to post your feature request and if enough people want it then we'll consider it.

**Comment by satya164** [comment]
https://react-navigation.canny.io/feature-requests

**Comment by jonathanj** [comment]
Thanks for replying, Satya. 

I opened the issue, and referred to the other issues (and documentation), hoping for a discussion, because the contribution guidelines suggest this prior to pull requests:

> For pull requests that change the API or implementation, discuss with maintainers first by opening an issue.

Can I submit a PR for this issue that has been reported multiple times?

**Comment by satya164** [comment]
Please use GitHub discussions for discussions. You can find a link to discussion forum when opening an issue and in the above reply from the bot. The issue tracker is for bug reports.
