### ISSUE TITLE
useFocusEffect and useEffect are triggered while previous screen is still open

### ISSUE THREAD

**Issue by lini-lini** [react-navigation/react-navigation#11724]
### Current behavior

For test I've set up Home screen with 2 buttons which are navigating to screen which includes useFocusEffect (FocusEffectScreen) and to screen which includes useEffect (UseEffectScreen). Both hooks trigger PermissionsAndroid modal.

<img src='https://github.com/react-navigation/react-navigation/assets/152303565/ab9fe10d-5394-4dff-a672-a982832c5d03' width='300'>
<img src='https://github.com/react-navigation/react-navigation/assets/152303565/f0f55a7f-b5bd-46a3-bba8-cfbea5e53c63' width='300'>

I've expected that at least useFocusEffect hook should be triggered **after** the FocusEffectScreen is opened, so the modal should be shown above the FocusEffectScreen.
But modal is shown above HomeScreen.

The same situation is with useEffect hook.

### Expected behavior

Expected to see that the useFocusEffect hook is triggered when the related screen is opened, so, the modal which is opened by such hook should be shown above the related screen.

### Reproduction

https://github.com/lini-lini/TestNavigation

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.1.7
| @react-navigation/bottom-tabs          | 6.5.8
| @react-navigation/drawer               | 6.6.3
| @react-navigation/material-top-tabs    | 6.6.3
| @react-navigation/stack                | 6.3.17
| react-native-safe-area-context         | 4.7.1
| react-native-screens                   | 3.25.0
| react-native-gesture-handler           | 2.13.4
| react-native-tab-view                  | 3.5.2
| react-native-pager-view                | 6.2.0
| react-native                           | 0.72.4
| node                                   | 16.14.0
| yarn                            | 1.5.1

**Comment by satya164** [comment]
https://reactnavigation.org/docs/use-focus-effect/#delaying-effect-until-transition-finishes
