### ISSUE TITLE
No view found for id ... for fragment ScreenStackFragment...

### ISSUE THREAD

**Issue by Medkhat** [react-navigation/react-navigation#11720]
### Example here

https://github.com/react-navigation/react-navigation/assets/42961493/ae5fa3dc-e141-4b56-9357-bd0ec95dc9fb

### Expected behavior

I want a help with this

### Reproduction

I attached video example. Code is common

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [✅] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |  6.1.9
| @react-navigation/bottom-tabs          | 6.5.11
| @react-navigation/native-stack         |6.9.17
| react-native-safe-area-context         | 4.7.4
| react-native-screens                   | 3.27.0
| react-native-gesture-handler           | 2.14.0
| react-native-reanimated                | 3.5.4
| react-native                           |0.72.7
| node                                   | 20.9.0
| npm or yarn                            | yarn@1.22.19

**Comment by yangm97** [comment]
I think I have this issue.

Are you using freezeOnBlur on your BottomTabs?

**Comment by Medkhat** [comment]
@yangm97 Hi! I'm using the standard features which in the docs

**Comment by steveacalabro-indevets** [comment]
+1

**Comment by pc9** [comment]
@Medkhat Try disabling [detachInactiveScreens](https://reactnavigation.org/docs/bottom-tab-navigator/#detachinactivescreens). Worked for me.

**Comment by danidaryaweesh** [comment]
I'm also experiencing this issue on RN 0.73.1 and latest React-navigation version. I tried the react-native paper integration solution and it works with no issues. Have anyone found any solution for this?

**Comment by danidaryaweesh** [comment]
Worked for me by disabling Fabric (new architecture) for now.

**Comment by gdaghero** [comment]
same

**Comment by vnijat** [comment]
> @Medkhat Try setting `detachInactiveScreens={false}` https://reactnavigation.org/docs/bottom-tab-navigator/#detachinactivescreens. Worked for me.

Thank you @Medkhat,  this worked for me too RN 0.73.5

**Comment by wallycarvalho** [comment]
> > @Medkhat Try setting `detachInactiveScreens={false}` https://reactnavigation.org/docs/bottom-tab-navigator/#detachinactivescreens. Worked for me.
> 
> Thank you @Medkhat, this worked for me too RN 0.73.5

It appears this solution worked for me as well. I have a similar scenario where I have a stack navigator running inside a drawer with Fabric enabled. Switching the flag in the stack navigator has prevented the error from surfacing.

**Comment by foyarash** [comment]
I am encountering the same issue but only on new architecture.

Expo 51
RN 0.74.1
RNS 3.31.1
react-navigation/native-stack 6.9.26
react-navigation/native 6.1.17
react-navigation/bottom-tabs 6.5.20

**Comment by tonypangs** [comment]
i am experiencing this too
    "react": "18.2.0",
    "react-native": "^0.72.7",
    "@react-navigation/bottom-tabs": "^6.5.11",
    "@react-navigation/native": "^6.1.9",
    "@react-navigation/native-stack": "^6.9.17",
    "@react-navigation/stack": "^6.3.20",

**Comment by foyarash** [comment]
This has been fixed in https://github.com/software-mansion/react-native-screens/pull/2351

**Comment by MussadiqAli** [comment]
only following solution works for me.
I'm unmounting the tab which is not active:
```
unmountOnBlur: true,
```
