### ISSUE TITLE
Badge does not display on a HarmonyOS

### ISSUE THREAD

**Issue by renyufei8023** [react-navigation/react-navigation#11735]
### Current behavior

If the Badge is set directly inside the useEffect method, it will be displayed normally. However, if the unread count is obtained from an API and then set, it will not be displayed.If the TabBarItem is tapped, it will be displayed correctly.

https://github.com/react-navigation/react-navigation/assets/8408209/3c522487-b9c2-49f5-a230-4bb53e1355a1

### Expected behavior

The expected behavior is that it should be displayed when the app is opened.

### Reproduction

not

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.1.9
| @react-navigation/bottom-tabs          | 6.5.11
| @react-navigation/drawer               | not installed
| @react-navigation/material-top-tabs    | not installed
| @react-navigation/stack                | 6.3.20
| @react-navigation/native-stack         | 6.9.16
| react-native-safe-area-context         | 4.7.4
| react-native-screens                   | 3.27.0
| react-native-gesture-handler           | 2.13.4
| react-native-reanimated                | 3.5.4
| react-native-tab-view                  | not installed
| react-native-pager-view                | not installed
| react-native                           | 0.71.10
| expo                                   | not installed
| node                                   | 18.2
| npm or yarn                            | yarn

**Comment by renyufei8023** [comment]
useEffect(() => {
        navigation.setOptions({
            tabBarBadge: 10 //this is work
        })
       getWaitNum() //not work
    }, []) 

function getWaitNum() {
        let params = {
            SteamGameId: currentGame && currentGame.SteamGameID || '730',
            PageIndex: 1,
            PageSize: 20,
        }
        let url = BASEURL + '/Api/Order/QuerySelfOrderGoods'
        FetchManager.postJson(url, params, res => {
            let num = res.TotalRecord
            waitNum.current = num
            if (num > 0) {
                tabColl && tabColl.current && tabColl.current.setTab(1)
            }
            if (num > 99) {
                num = 99
            }
            num = 10
            setBadgeNum(num)
            navigation.setOptions({
                tabBarBadge: num == 0 ? undefined : num
            })
        })
    }

**Comment by dodoto** [comment]
感觉是navigation不正确

**Comment by renyufei8023** [comment]
> 感觉是navigation不正确

跟navigation没太大关系，这个问题只出现在鸿蒙系统下面，debug看的时候是因为opacity等于0.001，导致显示不出来

**Comment by dodoto** [comment]
如果不是js代码层的问题的话，还是鸿蒙这种感觉修复的希望很渺茫。这种跨组件的数据最后都放在状态管理里的，你可以试一下状态管理变化引起的重新渲染能不能成功。

**Comment by renyufei8023** [comment]
> 如果不是js代码层的问题的话，还是鸿蒙这种感觉修复的希望很渺茫。这种跨组件的数据最后都放在状态管理里的，你可以试一下状态管理变化引起的重新渲染能不能成功。

就是Badge里面的js代码可能有点问题，如果把`position`改成`undefined`的话是可以显示出来，但是位置不太对。

**Comment by renyufei8023** [comment]
It still exists
