### ISSUE TITLE
Solution for Changing background using tabBarStyle is not working on all tabs on 2 out of my 4 tabs change #10623

### ISSUE THREAD

**Issue by Coby232** [react-navigation/react-navigation#11739]
Instead of applying the tabBarStyle in the screenOptions prop in the <Tab.Navigator>, apply it to each in <Tab.Screen> element through the options prop. This is because the tabBarStyle in the <Tab.Navigator> is automatically overwritten by the tabBarStyle in <Tab.Screen>: 

For Example;
import { NavigationContainer } from "@react-navigation/native";
import { createBottomTabNavigator } from "@react-navigation/bottom-tabs";

const Tab = createBottomTabNavigator();
const Stack = createStackNavigator();

export default function MainPage() {
  return (
    <NavigationContainer independent={true}>
      <Tab.Navigator
        sceneContainerStyle={{
          backgroundColor: "#F8F8F8",  // It will be overriden
        }}
        screenOptions={{
          tabBarLabelStyle: { color: "black", height: 25 },
          tabBarStyle: {
            height: ScreenHeight * 0.085,
          },
          headerTransparent: true,
          headerTitle: "",
          tabBarHideOnKeyboard: true,
          tabBarShowLabel: false,
        }}>
        <Tab.Screen
          name='Home'
          component={HomeScreen}
          options={({ route }) => ({
            tabBarIcon: ({ focused, color, size }) => {
              if (route?.name === "Home") {
                return focused ? (
                  <View className='flex flex-row items-center bg-slate-200 rounded-full w-20 ml-6'>
                    <Text className='font-semibold px-1'>
                      {route.name}
                    </Text>
                  </View>
                ) : (
                  <HomeTabIcon />
                );
              }
            },
            headerTransparent: true,
            headerTitle: "",
            headerShown: false,
            tabBarStyle: {  //This will override the tabBarStyle above regardless of the amount of styles it contains
              backgroundColor:"#000000", 
              height: 71,
            },
          })}
          initialParams={handleOpenedDrawer}
        />
             </Tab.Navigator>
    </NavigationContainer>

_Originally posted by @Coby232 in https://github.com/react-navigation/react-navigation/issues/10623#issuecomment-1848894120_

**Comment by Jashanpreet1998** [comment]
sceneContainerStyle={{
backgroundColor: "#F8F8F8", // It will be overriden
}}

to

screenOptions={{
sceneStyle: { backgroundColor:  "#F8F8F8",},
}}
