### ISSUE TITLE
Getting warning "shadow*" style props are deprecated. Use "boxShadow" for expo-web in nx-workspace without webpack.

### ISSUE THREAD

**Issue by pratish-respo** [react-navigation/react-navigation#11730]
### Current behavior

I am using react-navigation package in my nx-workspace. In my workspace, I have mobile(react-native) & web(expo-web). When i run my web project with react-native-web version 0.19.6, I am getting a warning "shadow*" style props are deprecated. Use "boxShadow".
![Screenshot from 2023-11-30 13-07-29](https://github.com/react-navigation/react-navigation/assets/120653213/31adf6e4-6add-4c7f-8aa8-8bbcf0280855)
![Screenshot from 2023-11-30 13-06-13](https://github.com/react-navigation/react-navigation/assets/120653213/a03483ca-f63a-46ab-b853-601387b205bc)

### Expected behavior

Instead of using shadow in styles as below

>   tabBar: {
>     shadowColor: 'black',
>     shadowOpacity: 0.1,
>     shadowRadius: StyleSheet.hairlineWidth,
>     shadowOffset: {
>       height: StyleSheet.hairlineWidth,
>       width: 0
>     },
>   }

we have to use boxShadow which uses a space separated string containing styles as below

> tabBar: {
>     boxShadow: '0px ${StyleSheet.hairlineWidth}px ${StyleSheet.hairlineWidth}px #0000001A',
>   }

This above change removes the warning in web.

### Reproduction

No need to reproduce, as it is a common styling issue, provided screenshot instead

### Platform

- [ ] Android
- [ ] iOS
- [X] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [X] react-native-tab-view

### Environment

- [X] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |6.1.9
| @react-navigation/bottom-tabs          |6.5.11
| @react-navigation/stack                |6.3.0
| react-native-safe-area-context         |4.7.4
| react-native-screens                   |3.27.0
| react-native-gesture-handler           |2.13.4
| react-native-reanimated                |3.5.4
| react-native-tab-view                  |3.5.2
| react-native                           |0.72.4
| expo                                   |49.0.20
| node                                   |16.20.0
| npm or yarn                            |9.6.7

**Comment by aaronkogan** [comment]
I use react-native-web  with vite. Easy to reproduce by adding shadows to styleSheet.

![Screenshot 2023-12-30 at 19 27 29](https://github.com/react-navigation/react-navigation/assets/59419760/47dc32af-0d84-4280-be0d-db2de002a405)

import { StyleSheet, } from 'react-native';

const styles = StyleSheet.create({
    modalContent: {
      minWidth: 320,
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      padding: 20,
      //@ts-ignore
      cursor: 'initial',
      backgroundColor: '#c4a631',
      borderRadius: 10,
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.25,
      shadowRadius: 4,
      elevation: 5,
    },
)}

**Comment by giladresisi** [comment]
> The versions mentioned in the issue for the following packages differ from the latest versions on npm:
> 
> * `@react-navigation/stack` (found: `6.3.0`, latest: `6.3.20`)
> 
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?

For me it does, versions:
```
"dependencies": {
    "@expo/webpack-config": "^19.0.0",
    "@react-navigation/bottom-tabs": "^6.5.11",
    "@react-navigation/native": "^6.1.9",
    "@react-navigation/native-stack": "^6.9.17",
    "@react-navigation/stack": "^6.3.20",
    "@reduxjs/toolkit": "^2.0.1",
    "expo": "~49.0.15",
    "expo-status-bar": "~1.6.0",
    "react": "18.2.0",
    "react-dom": "^18.2.0",
    "react-native": "0.72.6",
    "react-native-gesture-handler": "~2.12.0",
    "react-native-paper": "^5.12.1",
    "react-native-reanimated": "~3.3.0",
    "react-native-safe-area-context": "4.6.3",
    "react-native-screens": "~3.22.0",
    "react-native-vector-icons": "^10.0.3",
    "react-native-web": "^0.19.10",
    "react-redux": "^9.1.0",
    "redux": "^5.0.1"
  }
```

**Comment by aabmar** [comment]
This issue is still present and everyone using Expo default template will experience it.

To recreate:

    npx create-expo-app test

Then start the server:

cd test
npm start

Click w to open  the app in the browser. The error will appear on the browser console.

No special procedure is needed to recreate this bug, it is always present for everybody using Expo with react-navigation.

 "dependencies": {
    "@expo/vector-icons": "^14.0.2",
    "@react-navigation/native": "^6.0.2",
    "expo": "~51.0.28",
    "expo-constants": "~16.0.2",
    "expo-font": "~12.0.9",
    "expo-linking": "~6.3.1",
    "expo-router": "~3.5.23",
    "expo-splash-screen": "~0.27.5",
    "expo-status-bar": "~1.12.1",
    "expo-system-ui": "~3.0.7",
    "expo-web-browser": "~13.0.3",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.74.5",
    "react-native-gesture-handler": "~2.16.1",
    "react-native-reanimated": "~3.10.1",
    "react-native-safe-area-context": "4.10.5",
    "react-native-screens": "3.31.1",
    "react-native-web": "~0.19.10"
  },

**Comment by jtomaszewski** [comment]
I get this too, on a fresh and up-to-date expo app.

Temporary workaround to hide the warning:

```ts
const originalConsoleWarn = console.warn;

console.warn = (...args) => {
  // https://github.com/react-navigation/react-navigation/issues/11730
  if (
    args[0] === '"shadow*" style props are deprecated. Use "boxShadow".' &&
    new Error().stack?.includes("useNavigationBuilder")
  ) {
    return;
  }

  originalConsoleWarn(...args);
};

```

**Comment by totallytotallyamazing** [comment]
I've been getting this same error in my react native web app development:
```
"shadow*" style props are deprecated. Use "boxShadow". Error Component Stack
```
 ...for quite some time now even after changing all of my shadow* styles to boxShadow styles, etc. and nothing worked to stop this warning / error... Now in production I'm getting this Minified React error (bigger issue), which I believe is caused by the initial shadow* issue:

```
Uncaught Error: Minified React error #421; visit https://reactjs.org/docs/error-decoder.html?invariant=421 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at ei (entry-e61a37013c0229c273aa6005fa9e3443.js:330:81364)
    at Go (entry-e61a37013c0229c273aa6005fa9e3443.js:330:79310)
    at Ai (entry-e61a37013c0229c273aa6005fa9e3443.js:330:121780)
    at Is (entry-e61a37013c0229c273aa6005fa9e3443.js:330:111489)
    at Ds (entry-e61a37013c0229c273aa6005fa9e3443.js:330:111417)
    at Rs (entry-e61a37013c0229c273aa6005fa9e3443.js:330:111280)
    at zs (entry-e61a37013c0229c273aa6005fa9e3443.js:330:108421)
    at na (entry-e61a37013c0229c273aa6005fa9e3443.js:330:47338)
    at Bs (entry-e61a37013c0229c273aa6005fa9e3443.js:330:114326)
    at entry-e61a37013c0229c273aa6005fa9e3443.js:330:112453
```

Is anyone experiencing this issue or something similar?.. I've looked at the possibility of plugins I'm using causing this, like react-native-reanimated, etc. Also using Tailwindcss 3.3.2 with nativewind 2.0.11 but as far as I know, these version take shadow* into consideration... Please help!

FYI: this Minified React error 421 is not fatal to my production site in testing but I'm assuming it would be unwise to ignore it due to its throttling nature.?

Thanks for taking the time to read this!
