### ISSUE TITLE
Bug: invalid drawer position with 'right' and 

### ISSUE THREAD

**Issue by cyrilchapon** [react-navigation/react-navigation#11737]
### Current behavior

When using `<Drawer>` from `react-native-drawer-layout` with `drawerPosition="right"` (and any of `front` or `slide` type); the drawer is misplaced over the main content before swiping it.

After swiping it, it has an incorrect left-aligned position.

⚠️ the linked snack doesn't work because `react-native-drawer-layout` basically doesn't work there; but see screenshot here and code there.

Before swipe :
![Capture d’écran 2023-12-08 à 02 14 00](https://github.com/react-navigation/react-navigation/assets/10728426/cb5eb2f1-1c16-44ed-830e-2254e7c16c6e)

After swipe :
![Capture d’écran 2023-12-08 à 02 14 09](https://github.com/react-navigation/react-navigation/assets/10728426/8061531d-c3e7-4c02-90af-fa9978c32907)

### Expected behavior

I'd expect the same behavior than `left`, at the opposite

### Reproduction

https://snack.expo.dev/@chimanos/drawer-right-bug

### Platform

- [ ] Android
- [X] iOS
- [X] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| react-native-safe-area-context         |4.6.3
| react-native-screens                   |~3.22.0
| react-native-gesture-handler           |~2.12.0
| react-native-reanimated                |~3.3.0
| react-native-tab-view                  |3.5.2
| react-native-pager-view                |6.2.0
| react-native                           |0.72.6
| expo                                   |49.0.21
| node                                   |v18.18.0
| yarn                            |1.22.19

**Comment by cyrilchapon** [comment]
> Couldn't find version numbers for the following packages in the issue:
> 
> * `@react-navigation/native`
> 
> Can you update the issue to include version numbers for those packages? The version numbers must match the format 1.2.3.

I'm not using @react-navigation/native

**Comment by cyrilchapon** [comment]
https://snack.expo.dev/@chimanos/drawer-right-bug

**Comment by maloni991** [comment]
did you manage to fix it ?  I got same issue , Drawer position right is always half open

**Comment by satya164** [comment]
Please don't link to snack that doesn't run. The whole point of providing repro is that someone can quickly verify and debug the issue. From the bot reply:

> If it's not possible to create a repro using a snack, link to a GitHub repo under your username is a good alternative.

**Comment by dudgus5766** [comment]
I got same issue.

**Comment by cyrilchapon** [comment]
@satya164 did you actually read what I wrote ???

> ⚠️ the linked snack doesn't work because react-native-drawer-layout basically doesn't work there; but see screenshot here and code there.

Before making an annoying bot to enforce something, maybe ensure it's possible first ?

**Comment by satya164** [comment]
Again, the bot clearly asks you to provide a GitHub repo if Snack isn't possible. It's your responsibility to provide a repro.

If you find it annoying then you're free to use a different library.
