### ISSUE TITLE
MaterialBottomTabNavigator breaks header in nested screens occasionally (iOS)

### ISSUE THREAD

**Issue by tomwaitforitmy** [react-navigation/react-navigation#11773]
### Current behavior

When navigating to a nested screen, the header of the new screen breaks. See the attached video. As shown in the video, it does not happen all the time.

What I know so far:
* Navigating has to be from a different tab with e.g. `navigation.navigate("Tab 1", { screen: "Details"})`
* If I use `createBottomTabNavigator` instead of `createMaterialBottomTabNavigator` it works. I even added `screenOptions={{ headerShown: false }}` to make the headers exactly the same in my app.
* I did not check whether the stack navigators are needed to reproduce this
* If I navigate to the "parent" of "Details", in my case the name is "Mangi & Bevi", the issue does not occur
* If I navigate from within the same tab (in my case "Mangi & Bevi"), the issue does not occur

https://github.com/react-navigation/react-navigation/assets/25305424/bd868c11-588c-4cda-9433-26abf58ee0a9

Note: I would have provided an expo snack, but newer versions of @react-navigation/native are incompatible with snack and SDK 49.

### Expected behavior

Header should not break.

### Reproduction

https://github.com/tomwaitforitmy/mangi-bevi/tree/minimalReproHeaderBreaks

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [X] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.1.9
| @react-navigation/bottom-tabs          | 6.5.11 (not needed for repro, just for comparison)
| @react-navigation/material-bottom-tabs    | 6.2.19
| @react-navigation/native-stack         | 6.9.17
| react-native-safe-area-context         | 4.6.3
| react-native-screens                   | 3.22.0
| react-native                           | 0.72.6
| expo                                   | 49.0.21
| node                                   |v18.13.0
| npm                            |8.19.3

**Comment by tomwaitforitmy** [comment]
I am not using 
    @react-navigation/material-top-tabs
    @react-navigation/stack
The template mentioned that I should remove dependencies that I do not use.

**Comment by tomwaitforitmy** [comment]
Bump, I need help to narrow this down, because Snacks are impossible with `@react-navigation/native`

**Comment by naveenApplikation** [comment]
i am also facing this issue

**Comment by naveenApplikation** [comment]
any solution?

**Comment by tomwaitforitmy** [comment]
Nope, no solution yet. You´re the first person to react.

**Comment by naveenApplikation** [comment]
for me the issue occurred in materialtoptab

**Comment by satya164** [comment]
https://reactnavigation.org/docs/material-bottom-tab-navigator/

> The material-bottom-tabs navigator is moved to [react-native-paper](https://reactnativepaper.com/). Refer to [react-native-paper's documentation](https://callstack.github.io/react-native-paper/docs/guides/bottom-navigation) instead for installation instructions, usage guide and API reference. For any issues with the navigator, please open an issue in [react-native-paper's repository](https://github.com/callstack/react-native-paper/).
