### ISSUE TITLE
Tabs reset to first tab after launching native activity exiting app

### ISSUE THREAD

**Issue by geeker-cmc** [react-navigation/react-navigation#11789]
### Current behavior

We are a hybrid app, when the tab jumps to the native page and then returns to the tab page, the tab is reset to the first tab on android.

### Expected behavior

tab should not be reset

### Reproduction

https://snack.expo.dev/@geeker-cmc/979b2a

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.1.9|
| @react-navigation/bottom-tabs          |6.5.11|
| @react-navigation/native-stack         |6.9.17|
| react-native-safe-area-context         |4.7.4|
| react-native                           |0.72.7|
| node                                   |20.10.0|
|yarn                            |1.22.21|

**Comment by geeker-cmc** [comment]
@react-navigation/stack:

**Comment by geeker-cmc** [comment]
not use @react-navigation/stack

**Comment by satya164** [comment]
your snack doesn't reproduce the issue.

also react navigation has no control over your activities. if the state is being reset, maybe your previous activity unmounts the component. it's something you have to handle in your app.
