### ISSUE TITLE
tabBarBadgeStyle prop doesn't work

### ISSUE THREAD

**Issue by tannerschmutte** [react-navigation/react-navigation#11809]
### Current behavior

the tabBarBadge remains ugly red no matter what I do.

### Expected behavior

allow the tabBarBadge to be styled

### Reproduction

https://snack.expo.dev/@inpubliq/55a5c4?platform=ios

### Platform

- [x] Android
- [x] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [x] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

{
  "dependencies": {
    "@expo/vector-icons": "^13.0.0",
    "@react-navigation/material-bottom-tabs": "^6.2.12",
    "react-native-paper": "^5.1.4",
    "react-native-safe-area-context": "4.6.3",
    "@react-navigation/native": "^5"
  }
}

**Comment by zouhairgharsa** [comment]
try this options={({ }) => ({
           tabBarBadge: "Why I'm not green?",
              tabBarBadgeStyle: { backgroundColor: "green" },
        })}

**Comment by tannerschmutte** [comment]
hi zouhairgharsa, that has no effect either. did you even try to get it to work doing that?

**Comment by satya164** [comment]
https://reactnavigation.org/docs/material-bottom-tab-navigator/

> The material-bottom-tabs navigator is moved to [react-native-paper](https://reactnativepaper.com/). Refer to [react-native-paper's documentation](https://callstack.github.io/react-native-paper/docs/guides/bottom-navigation) instead for installation instructions, usage guide and API reference. For any issues with the navigator, please open an issue in [react-native-paper's repository](https://github.com/callstack/react-native-paper/).

**Comment by irazaa** [comment]
Sample Styling, do it like this in options
  tabBarBadge: notificationCount > 9 ? '+9' : notificationCount,
          tabBarBadgeStyle: {
            backgroundColor: '#FF1673',
            fontSize: getFontSize(12),
            justifyContent: 'center', // Centers text vertically
            alignItems: 'center', // Centers text horizontally
            textAlign: 'center',
            fontWeight: 'bold',
            marginTop: -7,
            borderRadius: notificationCount > 9 ? 10 : 9, // Conditional borderRadius
            paddingHorizontal: notificationCount > 9 ? 2 : 4,
          }
