### ISSUE TITLE
Back button won't go away on Android

### ISSUE THREAD

**Issue by catsclaw** [react-navigation/react-navigation#11817]
### Current behavior

This is my `App.js`:

```
import { NavigationContainer } from '@react-navigation/native';
import { createNativeStackNavigator } from '@react-navigation/native-stack';

import Main from './js/screens/main';
import Page from './js/screens/page';

const Stack = createNativeStackNavigator();

const headerOptions = {
  headerLeft: () => null,
};

export default () => {
  return (
    <NavigationContainer>
      <Stack.Navigator screenOptions={headerOptions}>
        <Stack.Screen
          name="Main"
          component={Main}
        />
        <Stack.Screen
          name="Page"
          component={Page}
        />
      </Stack.Navigator>
    </NavigationContainer>
  );
};
```

This disables the back button on both the `Main` and the `Page` screens if I run in the web. When I run on Android, however, the back button appears on the `Page` screen, although not the `Main` screen.

### Expected behavior

The back button should be hidden on all screens.

### Reproduction

https://snack.expo.dev/@catsclaw/greedy-indigo-pizza

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [X] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |
| @react-navigation/stack                |
| @react-navigation/native-stack         |
| react-native-safe-area-context         |
| react-native-screens                   |
| react-native-gesture-handler           |
| react-native                           |
| expo                                   |
| node                                   |
| npm                             |

**Comment by satya164** [comment]
https://reactnavigation.org/docs/native-stack-navigator/#headerbackvisible
