### ISSUE TITLE
Android Production Build - @react-navigation/drawer not working

### ISSUE THREAD

**Issue by HodgertA** [react-navigation/react-navigation#11826]
### Current behavior

I am using @react-navigation/drawer in my app. It works fine on both iOS and Android dev builds, but after I create and submit a production build to the Google PlayStore it stops working (I've tried 3 times now). When I open the drawer it only opens half way and I have to press multiple times to get it open and the closeDrawer() functionality doesn't work properly either.

### Expected behavior

I expect that the drawer would work properly the same it does on iOS and in dev builds.

I have included the :
import "react-native-gesture-handler"

and added it to the top of my index.js file but it still doesn't work.

### Reproduction

https://github.com/HodgertA/StickerSmash

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native         |  ^6.1.10
| @react-navigation/bottom-tabs          |  6.5.12
| @react-navigation/drawer               | ^6.6.7
| @react-navigation/stack                | 6.3.21
| react-native-safe-area-context         | 4.6.3
| react-native-screens                   | ~3.22
| react-native-gesture-handler           | ~2.12
| react-native-reanimated                | ~3.3.0
| react-native-tab-view                  |  ^3.5.2
| react-native-pager-view                | 6.2.0
| react-native                           | 0.72.10
| expo                                   | ^49.0.0
| node                                   | 18.12.0
| npm or yarn                            | 8.19.2

**Comment by HodgertA** [comment]
Issue still exists after upgrading packages.

**Comment by HodgertA** [comment]
> Couldn't find version numbers for the following packages in the issue:
> 
> * `@react-navigation/native`
> 
> Can you update the issue to include version numbers for those packages? The version numbers must match the format 1.2.3.
> 
> The versions mentioned in the issue for the following packages differ from the latest versions on npm:
> 
> * `@react-navigation/bottom-tabs` (found: `6.5.11`, latest: `6.5.12`)
> * `@react-navigation/stack` (found: `6.3.17`, latest: `6.3.21`)
> 
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?


Issue still exists after upgrading packages to latest versions.

**Comment by HodgertA** [comment]
I upgraded to expo 50 and the issue seems to have fixed itself. From looking at similar problems the the issue has to do with the not using the proper versions for the packages below:

"@react-navigation/drawer": "^6.6.7",
"@react-navigation/native": "^6.1.10",
"@react-navigation/stack": "6.3.21",
"react-native-reanimated": "~3.6.2"

**Comment by enikakisMellon** [comment]
is there any solution without upgrading to expo 50?
