### ISSUE TITLE
How to change the pressColor of a drawer menu item?

### ISSUE THREAD

**Issue by victorwpbastos** [react-navigation/react-navigation#11836]
### Current behavior

When I press a drawer menu item the background becomes dark gray. I want to change this color. I see in the docs that the `DrawerItem` component receives a prop called `pressColor`, but I didn't find a way to pass this prop. How can I change this `pressColor` prop to another color?

To test the behavior, just open the provided snack and do a long press on some drawer menu item. The background color is always dark gray.

### Expected behavior

I should be able to change the `pressColor` to another color of my choice.

### Reproduction

https://snack.expo.dev/@victorwpbastos/drawer-presscolor

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |6.1.7
| @react-navigation/drawer               |6.6.3
| @react-navigation/stack                |6.3.21
| react-native-safe-area-context         |4.6.3
| react-native-screens                   |3.22.0
| react-native-gesture-handler           |2.12.0
| react-native-reanimated                |3.3.0
| react-native                           |0.72.6
| expo                                   |49.0.7
| node                                   |20.9
| npm or yarn                            |yarn

**Comment by victorwpbastos** [comment]
Yes. The behavior persists on the latest version of @react-navigation/drawer.

**Comment by victorwpbastos** [comment]
For me it's a bug. If I can't change the pressColor, I believe it's a bug.

**Comment by FlorianGG** [comment]
Thes issue is always active. In the code, the component DrawerItem has well the prop `pressColor` but the DraweritemList component does not give him
