### ISSUE TITLE
Title overlaps when the title length increases

### ISSUE THREAD

**Issue by Linuhusainnk** [react-navigation/react-navigation#11838]
### Current behavior

![longer text](https://github.com/react-navigation/react-navigation/assets/80395697/64439ccf-3e00-41f0-87f3-dc3bff2a2cc7)

### Expected behavior

![normal](https://github.com/react-navigation/react-navigation/assets/80395697/5ac06f79-819d-4664-b1db-cfa079ac3108)

### Reproduction

most of the repo

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/bottom-tabs          | 6.5.11
| @react-navigation/stack                | 6.3.17
| @react-navigation/native  | 6.1.7
| react-native-safe-area-context         | 4.7.2
| react-native-screens                   | 3.25.0
| react-native-gesture-handler           | 2.12.1
| react-native-reanimated                | 3.0.2
| react-native                           | 0.72.4
| node                                   | 18
| yarn                            | 1.22.19

**Comment by Linuhusainnk** [comment]
Still same in latest versions

**Comment by khagesh** [comment]
I am not sure what is the correct solution here. But I use a custom header title components for screens where header title is dynamic. Here is my custom header.

headerTitle: ({
          children,
          tintColor,
        }: {
          children: string;
          tintColor?: string;
        }) => (
          <Text
            style={{
              color: tintColor
              flex: 1,
              flexWrap: "wrap",
              maxWidth: "75%",
            }}
            numberOfLines={2}
            ellipsizeMode="tail"
          >
            {children}
          </Text>
        ),


> Sorry about no code formatting. Sending from mobile github app.
