### ISSUE TITLE
中国人请看：作为一名资深5年的RN告诉你这个烂库别用，尤其是新手

### ISSUE THREAD

**Issue by StationChnqoo** [react-navigation/react-navigation#11843]
### Current behavior

1.安装麻烦，什么乱七八糟的一大堆，Stack、BottomTabs、Drawer都是分开的
2.Bug超级多，他引用的`react-native-screens`和`react-native-reanimated`Bug很多，你永远不知道什么时候他就又爆红了，你得自己去挨个试各个依赖的三方库的版本看哪个不报错
3.体验很差，尤其是Debug体验极其差，Android设备响应很慢，因为他的动画依赖的`react-native-reanimated`这个垃圾库，这个库2.x和3.x版本都用过，Debug直接爆红，不能调试，但是就一个简单的跳转，要个毛复杂的动画，还得依赖这垃圾玩意儿
4.内存溢出，生产环境大概率会崩
https://github.com/react-navigation/react-navigation/issues/7686

### Expected behavior

已经弃坑了，`react-native-navigation`推荐使用这个库，纯JS实现，没那些乱七八糟的依赖，一个包就搞定，劝各位如果项目现在不是很大，趁早别用这垃圾库，欢迎访问https://blog.cctv3.net ...

### Reproduction

......

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [X] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [X] @react-navigation/native-stack
- [X] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |
| @react-navigation/bottom-tabs          |
| @react-navigation/drawer               |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                |
| @react-navigation/native-stack         |
| react-native-safe-area-context         |
| react-native-screens                   |
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           |
| expo                                   |
| node                                   |
| npm or yarn                            |

**Comment by talpx0** [comment]
I have the same feeling , but most of problem I encounter is it work perfectly  on android  , but when I switch to ios , it suddenly have lots of UI problem

**Comment by likeSo** [comment]
你的这个问题，我只能同意一部分；这个导航框架确实有很多问题，但应该是下面这些：
- `material-top-tab` 可定制程度低，经常需要完全自己写tab bar；
- `material-top-tab`依赖的`react-native-pager-view`在快速切换的时候偶尔会闪退；
- `drawer`导航在快速切换子页面的时候，偶发抽屉内容消失；而且如果把抽屉内容放在右侧，必现UI错位问题；


至于你说的`react-native-screens`和`react-native-reanimated`，这俩是RN上的支柱框架了，我还是很喜欢这俩的，至少大部分人应该没有遇到你说的那些问题；

**Comment by huix9527** [comment]
Why so mad? Please be more specific, most problems can be fixed without much effort
