### ISSUE TITLE
react-native-drawer-layout: right drawer stuck in open position. Won't close.

### ISSUE THREAD

**Issue by jehillert** [react-navigation/react-navigation#11853]
### Current behavior

This issue seems nearly the same as [this one](https://github.com/expo/router/issues/837), except for react-native-drawer-layout version 3.2 and above. The app opens with the  right drawer fully extended, and changing the state directly doesn't do anything. It was weird though, because I didn't have issue for months and it just started happening.  And I could get it to go away and stay away, but if I cleaned the project it came back again and guaranteed it would show up on deployment.

I got it to go away by reverting to version 3.0.0.

### Expected behavior

Expected it not to block the app.  My repo is private so I cannot share code, but I think in this case you are aware of what needs to be done.  I am just pointing it out it's also present in the react-native-drawer-view package as well.  If not useful, feel free to close this right away. Also, npm doesn't link directly to the react-native-drawer-view repo, so I figured this was the place to post

### Reproduction

.

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use
    "@react-navigation/material-top-tabs": "^6.6.8",
    "@react-navigation/native": "^6.1.8",
    "@react-navigation/native-stack": "^6.9.20",
    "react-native-drawer-layout": "^3.2.1",

**Comment by jehillert** [comment]
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?

I also tried [4.0.0-alpha.5](https://www.npmjs.com/package/react-native-drawer-layout/v/4.0.0-alpha.5) and it was there too.  Sorry about the format of this Issue, but I just spent 24 hours trying to figure it out and I'm toast at the moment.

**Comment by likeSo** [comment]
Please check this: https://github.com/react-navigation/react-navigation/pull/11651
I am waiting for the resolution too

**Comment by yuvrajchaudhari03** [comment]
```
<Drawer
        open={false}
        onOpen={() => setRightDrawerOpen(true)}
        onClose={() => setRightDrawerOpen(false)}
        drawerPosition="right"
        drawerType="front"
        renderDrawerContent={() => (
          <>
            <Text>Right</Text>
          </>
        )}
      >
        <NavigationDrawer {...props} />
      </Drawer>
```

still, it shows/opens.
found any solution?

**Comment by jehillert** [comment]
I dropped the version down to 3.0.0.  I

**Comment by neomeisters** [comment]
Downgrading to version 3.0.0 works!, thanks

**Comment by sindarovcoder** [comment]
https://github.com/react-navigation/react-navigation/assets/97356814/9da7670c-6673-42e6-a504-af3c157a320d

that's how it works for me

**Comment by bserrano27** [comment]
> Downgrading to version 3.0.0 works!, thanks

How can I downgrade the version? I'm just using @react-navigation/drawer no react-native-drawer-layout

**Comment by jehillert** [comment]
> > Downgrading to version 3.0.0 works!, thanks
> 
> How can I downgrade the version? I'm just using @react-navigation/drawer no react-native-drawer-layout


I don't think you could without patch package and you really wouldn't want to.   If you are using @react-navigation/drawer then I think that uses drawer-layout as a dependency. Maybe try reverting back to the version of @react-navigation/drawer that was out when version 3.0.0 of react-native-drawer-layout came out.  If that doesn't work, go back earlier and see if - that does it.  

Btw, there is a similar issue (#8551) for @react-navigation-drawer where a solution was to [revert back to version 6.1.4.](https://github.com/react-navigation/react-navigation/issues/8551#issuecomment-1499965528
)

**Comment by bserrano27** [comment]
> > Downgrading to version 3.0.0 works!, thanks
> 
> How can I downgrade the version? I'm just using @react-navigation/drawer no react-native-drawer-layout

For those who would like to know how to solve this if you're using @react-navigation/drawer on Expo, please update Expo to SDK 50 or please refer to this closed issue https://github.com/react-navigation/react-navigation/issues/11616

**Comment by chanphiromsok** [comment]
I used 3.2.2 is not stuck but is open by default sometime when app start I set it isOpen to false but no luck

**Comment by milesingrams** [comment]
In general the drawerPosition: "right" needs a lot of work. For 3 years it hasn't worked in web due to the translateX not updating on window resize. Lots of issues related to this problem in the past have been closed without solutions other than to use useLegacyImplementation, however this stopped being possible since reanimated 3 disallows it.
