### ISSUE TITLE
Error using setParams and setOptions, rollback to version @react-navigation/core@6.4.10 is mandatory

### ISSUE THREAD

**Issue by alexandre1921** [react-navigation/react-navigation#11858]
### Current behavior

After the update of [@react-navigation/core@6.4.10](https://github.com/react-navigation/react-navigation/releases/tag/%40react-navigation%2Fcore%406.4.10) to [@react-navigation/core@6.4.11](https://github.com/react-navigation/react-navigation/releases/tag/%40react-navigation%2Fcore%406.4.11), setParams and setOptions methods stopped working and started showing this error in all platforms:

![image](https://github.com/react-navigation/react-navigation/assets/44145981/b79989b3-c652-4400-80b8-8f525eeddc0a)

This is caused by the [commit](https://github.com/react-navigation/react-navigation/commit/144040a1bed9eb1b610c9e5575d0495101323025), more precisely on these lines of code of [packages/core/src/BaseNavigationContainer.tsx](https://github.com/react-navigation/react-navigation/blob/144040a1bed9eb1b610c9e5575d0495101323025/packages/core/src/BaseNavigationContainer.tsx):
![image](https://github.com/react-navigation/react-navigation/assets/44145981/ff8bc3bf-bb0f-4917-a020-30193786bdca)

### Expected behavior

Set params should not throw an error.

# For now this release should be rolled back immediately.

### Reproduction

https://github.com/alexandre1921/SetParamsErrorShowcase

### Platform

- [X] Android
- [X] iOS
- [X] Web
- [X] Windows
- [X] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [X] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [X] @react-navigation/native-stack
- [X] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native                  ~6.1.6 |
| @react-navigation/bottom-tabs       ~6.5.7 |
| @react-navigation/native-stack      ~6.9.12 |
| react-native                                        0.73.4 |
| expo                                                 ~50.0.8 |
| node                                                 18.19.0 |
| yarn                                                  1.22.21 |

 expo-env-info 1.2.0 environment info:
    System:
      OS: Windows 11 10.0.22631
    Binaries:
      Node: 18.19.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.21 - C:\Program Files\nodejs\yarn.CMD
      npm: 10.2.3 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 33
        Build Tools: 30.0.3, 33.0.0
        System Images: android-30 | Google APIs Intel x86 Atom, android-31 | Google Play Intel x86 Atom_64, android-33 | Google Play Intel x86_64 Atom, android-34 | Google Play Intel x86_64 Atom
    IDEs:
      Android Studio: AI-212.5712.43.2112.8609683
    npmPackages:
      expo: ~50.0.8 => 50.0.8
      expo-router: ~3.4.7 => 3.4.7
      react: 18.2.0 => 18.2.0
      react-dom: 18.2.0 => 18.2.0
      react-native: 0.73.4 => 0.73.4
      react-native-web: ~0.19.6 => 0.19.10
    Expo Workflow: managed

**Comment by alexandre1921** [comment]
As this is bug caused by a minor version change, I suggest to look more carefully for code that can throw an error on these kind of updates by toughen the pull requests policy.

**Comment by alexandre1921** [comment]
I created this [PR](https://github.com/react-navigation/react-navigation/pull/11859) to resolve this issue without the rollback.

**Comment by satya164** [comment]
Please provide repro without expo router.

**Comment by patrickjvieira** [comment]
> Please provide repro without expo router.

For what? Is the commit unclear?
You don't add a throw to a minor that didn't exist before, no matter the reason. It broke my application too. Instead, they should have added a warning.

**Comment by satya164** [comment]
There was no such method before and trying to call it would have resulted in an error regardless. The point of error message is to make it more clear.

Why is your application is automatically calling a method that didn't exist before?

If you believe there is actually a bug in the intended usage then provide a repro.

**Comment by alexandre1921** [comment]
As the PR was ignored by a fix from the @satya164 I will be closing this issue. - https://github.com/react-navigation/react-navigation/pull/11859

**Comment by patrickjvieira** [comment]
> There was no such method before and trying to call it would have resulted in an error regardless. The point of error message is to make it more clear.
> 
> Why is your application is automatically calling a method that didn't exist before?
> 
> If you believe there is actually a bug in the intended usage then provide a repro.

It's not actually a bug; it's more of an oversight. The issue, in reality, stems from the Expo careless implementation.

React Navigation's flexibility makes it tricky to predict implementations. Therefore, we need to be rigorously with patches and decline PRs like that.

In any case, I've noticed that you've adjusted the approach.

Thank you for swiftly addressing this.
