### ISSUE TITLE
Stack header accessibility issue: tab order

### ISSUE THREAD

**Issue by gentlee** [react-navigation/react-navigation#11855]
### Current behavior

Header is after screen content in the DOM, so it is focused after the content. 

Implementation detail: `flex-direction: column-reverse` style is used in container.

![Screenshot 2024-02-27 at 20 47 25](https://github.com/react-navigation/react-navigation/assets/2361140/12f56733-88ab-48e8-bc9b-df9c69ef12be)

### Expected behavior

Header should be before the screen content in the DOM to focus first, without overriding tabindex.

### Reproduction

1. Open stack screen with header.
2. Press tab until header elements are focused.

### Platform

- [ ] Android
- [ ] iOS
- [X] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |"6.1.9"
| @react-navigation/bottom-tabs          |"6.5.11"
| @react-navigation/material-top-tabs    |"6.6.5"
| @react-navigation/stack                |"6.3.20"
| react-native-safe-area-context         |"4.8.2"
| react-native-screens                   |"3.29.0"
| react-native-gesture-handler           |"2.14.0"
| react-native-reanimated                |"3.6.1"
| react-native-tab-view                  |"3.5.2"
| react-native-pager-view                |"6.2.0"
| react-native                           |"0.73.2"
| node                                   |v20.9.0
| npm or yarn                            |1.22.19

**Comment by sgaddameedi-insight** [comment]
This is reproducible in the live example website here: 
https://react-navigation-example.netlify.app/native-stack-header-customization/article/gandalf

Tab order focuses on the screen and then focus back on header later.

https://github.com/user-attachments/assets/22009c54-1bb7-43ab-b484-95fa755e5ea5

If you still need a repro, please let me know.

**Comment by Francisco42** [comment]
Hi! @gentlee @sgaddameedi-insight did you manage to find a solution for this?

**Comment by SYoder1** [comment]
@gentlee have you thought about opening a PR to pull in the changes?
