### ISSUE TITLE
React native bottom tab bar pushing itself up when opening keyboard

### ISSUE THREAD

**Issue by sandeep-kumar-eptura** [react-navigation/react-navigation#11868]
### Current behavior

We are using `createBottomTabNavigator`. In one of the tab contains search bar at the top. While clicking on that search bar, we are opening the keyboard. But the keyboard pushing up the bottom tab bar also. We need the bottom tab bar remains at the bottom when opening keyboard
we are using `"@react-navigation/bottom-tabs": "6.5.3",`

Also I used` {tabbarhideonkeyboard =true }` inside tab.input . It's not working. 

I tried other option, like changing "adjustresize " to "adjustPan " in side androidMainfest.xml file, and set the Custom keyboard hook for hiding tabbar . But none of those are working.

### Expected behavior

We need the bottom tab bar remains at the bottom when opening keyboard

### Reproduction
<img width="461" alt="Screenshot 2024-03-05 at 5 32 09 PM" src="https://github.com/react-navigation/react-navigation/assets/141620173/22a2e1c8-3a41-444a-a6a0-a43fb7c9ee8a">

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [x] @react-navigation/stack
- [x] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |^6.0.8
| @react-navigation/bottom-tabs          |6.5.3
| @react-navigation/drawer               |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                |^6.2.0
| @react-navigation/native-stack         |6.9.7
| react-native-safe-area-context         |4.4.1
| react-native-screens                   |
| react-native-gesture-handler           |
| react-native-reanimated                |3.6.1
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           |
| expo                                   |
| node                                   |
| npm or yarn                            |yarn

**Comment by sandeep-kumar-eptura** [comment]
yes, issue is with latest version

**Comment by FaizyQadri** [comment]
in my setup i am facing this issue 
to reproduce use 
"@react-navigation/bottom-tabs": "^6.6.1",
 "@react-navigation/native": "^6.1.18",
    "@react-navigation/native-stack": "^6.11.0",
     "react": "18.3.1",
    "react-native": "0.75.2",
    "react-native-safe-area-context": "^4.10.9",
    "react-native-screens": "^3.34.0",
    
    AppEnter.tsx
    return (
    <SafeAreaView style={styles.root}>
      <KeyboardAvoidingView
        behavior={Platform.OS === 'ios' ? 'padding' : undefined}
        style={styles.root}>
        <StatusBar  barStyle={"dark-content"} backgroundColor={Colors.white}/>
        <RootStackNavigator />
      </KeyboardAvoidingView>
    </SafeAreaView>
  );
  
  RootStack
   return (
    <NavigationContainer>
      <Stack.Navigator
        screenOptions={{headerShown: false, animation: 'slide_from_right'}}>
        <Stack.Screen
          name="BottomTabNavigator"
          component={BottomTabNavigator}
        />
        <Stack.Screen name="Products" component={Products} />
        <Stack.Screen
          name="ProductDescription"
          component={ProductDescription}
        />
      </Stack.Navigator>
    </NavigationContainer>
  );
};

BtootmTabNaviagtor 
<Tab.Navigator
        screenOptions={{
          tabBarHideOnKeyboard: true,
          headerShown: false,
        }}
        backBehavior="initialRoute"
        tabBar={() => {
          return <TabBar  />;
        }}
        sceneContainerStyle={styles.sceneContainerStyle}>
        <Tab.Screen name="Home" component={Home} />

        <Tab.Screen name="Updates" component={Updates} />

        <Tab.Screen name="Inquiries" component={Inquiries} />

        <Tab.Screen name="ContactUs" component={ContactUs} />
      </Tab.Navigator>
@<Tab.Navigator
        screenOptions={{
          tabBarHideOnKeyboard: true,
          headerShown: false,
        }}
        backBehavior="initialRoute"
        tabBar={() => {
          return <TabBar  />;
        }}
        sceneContainerStyle={styles.sceneContainerStyle}>
        <Tab.Screen name="Home" component={Home} />

        <Tab.Screen name="Updates" component={Updates} />

        <Tab.Screen name="Inquiries" component={Inquiries} />

        <Tab.Screen name="ContactUs" component={ContactUs} />
      </Tab.Navigator>
