### ISSUE TITLE
React native tabview stuck on iOS while switching tabs

### ISSUE THREAD

**Issue by faheem-cmd** [react-navigation/react-navigation#11874]
### Current behavior

While switching tabs on iOS, the screen can become stuck if the keyboard is active.

https://github.com/react-navigation/react-navigation/assets/56709898/178f0827-f29f-4c98-92fa-6c771d54cae2

### Expected behavior

Screen not freezing while switching

### Reproduction

https://github.com/react-navigation/react-navigation

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [X] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |
| @react-navigation/bottom-tabs          |
| @react-navigation/drawer               |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                |
| @react-navigation/native-stack         |
| react-native-safe-area-context         |
| react-native-screens                   |
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           |
| expo                                   |
| node                                   |
| npm or yarn                            |

**Comment by faheem-cmd** [comment]
The issue is that when you switch tabs, the keyboard closes and the tab switch transition occurs simultaneously. So, I used Keyboard.dismiss()  and rest of the code wrapped  inside the  settimeout function in the TabBar.tsx file to solve this problem. 
Please suggest any better alternatives.

` onPress: () => {
          Keyboard.dismiss();
          setTimeout(function () {
            const event: Scene<T> & Event = {
              route,
              defaultPrevented: false,
              preventDefault: () => {
                event.defaultPrevented = true;
              },
            };
            onTabPress?.(event);
            if (event.defaultPrevented) {
              return;
            }
            jumpTo(route.key);
          }, 100);
        },`

**Comment by anavahonskaya** [comment]
Hey @faheem-cmd. I can't share the code but we experienced similar problem. In our case a temporary quick workaround could be to set `animationEnabled` as `false` in `TabView`.

**Comment by cetfu** [comment]
> Hey [@faheem-cmd](https://github.com/faheem-cmd), I can't share the code but we experienced similar issue. In our case, a temporary quick workaround could be to set `animationEnabled` as `false` in `TabView`.

Whats wrong with animations on iOS?

**Comment by Nader-CS** [comment]
setting animationEnabled to false and still happen

**Comment by bolumaks** [comment]
> setting animationEnabled to false and still happen

Did you find the solution? I'm having the same issue
