### ISSUE TITLE
Crash due to useNativeDriver true for tab animations with android 12 devices

### ISSUE THREAD

**Issue by vibhor-d11** [react-navigation/react-navigation#11890]
### Current behavior

Dear Maintainers,

I hope this message finds you well. I am writing on behalf of Dream11 to bring to your attention an issue we've encountered while using react-native-tab-view library.

Issue Overview:

Currently their is no provision to enable/disable useNativeDriver for react native tab view. For tab animations `useNativeDriver` is set to true i.e they run on UI thread by default. We encountered some crashes related to Animated node that occurred only on Android 12 devices and after digging into it we get to know it is related to useNativeDriver set to true for tab animations. Also their is an open issue in react-native related to this crash: [Link](https://github.com/facebook/react-native/issues/33375). So we added a patch in `react-native-tab-view` library for disabling useNativeDriver for devices having Android 12 and that reduces the crash rate for that crash with very few instances now. We have been using this for almost a year and haven't faced any issue with our app exposed to more than 20 million users. So we though of adding support for enable/disable useNativeDriver for react-native-tab-view as a prop exposed from `material-top-tabs` as it internally uses `react-native-tab-view`

### Expected behavior

Following [PR](https://github.com/react-navigation/react-navigation/pull/11866) addresses the fix to add optional prop `useNativeDriver` for `material-top-tabs` which internally passes it to `react-native-tab-view` to enable/disable useNativeDriver for tab animations.

### Reproduction

Their is not defined steps to reproduce it but we have many instances of this crash on our firebase portal. Many were related to react native tab view, after adding the patch for setting useNativeDriver to false, its instances reduced to none. This is the stacktrace for the crash.

<img width="1252" alt="Screenshot 2024-03-18 at 2 58 12 PM" src="https://github.com/react-navigation/react-navigation/assets/85783438/f3eb1057-ff29-4887-8f98-3c184a2a9939">

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [X] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [X] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.1.7 
| @react-navigation/bottom-tabs          | 6.5.1
| @react-navigation/material-top-tabs    | 6.2.1
| @react-navigation/stack                | 6.2.1
| @react-navigation/native-stack         | 6.9.13
| react-native-safe-area-context         | 3.3.2
| react-native-screens                   |  3.25.0
| react-native-gesture-handler           | 2.9.0
| react-native-reanimated                | 3.4.0
| react-native-tab-view                  | 3.1.1
| react-native-pager-view                | 5.4.25
| react-native                           | 0.72.5
| node                                   | 18
| npm or yarn                            | 1.22.19

**Comment by hurshore** [comment]
@vibhor-d11 how did you disable useNativeDriver for android 12 devices only? Users are experiencing this issue in random parts of my app. But I think it happens when navigating to a screen. There is an open issue for it [here](https://github.com/facebook/react-native/issues/37267). 

This is the crash I get:
```
Fatal Exception: com.facebook.react.bridge.JSApplicationIllegalArgumentException: connectAnimatedNodes: Animated node with tag (child) [3851] does not exist
       at com.facebook.react.animated.NativeAnimatedNodesManager.connectAnimatedNodes(NativeAnimatedNodesManager.java:371)
       at com.facebook.react.animated.NativeAnimatedModule$16.execute(NativeAnimatedModule.java:777)
       at com.facebook.react.animated.NativeAnimatedModule$ConcurrentOperationQueue.executeBatch(NativeAnimatedModule.java:171)
       at com.facebook.react.animated.NativeAnimatedModule$3.execute(NativeAnimatedModule.java:365)
       at com.facebook.react.uimanager.UIViewOperationQueue$UIBlockOperation.execute(UIViewOperationQueue.java:579)
       at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:926)
       at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1037)
       at com.facebook.react.uimanager.UIViewOperationQueue.-$$Nest$mflushPendingBatches()
       at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1097)
       at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
       at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
       at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1036)
       at android.view.Choreographer.doCallbacks(Choreographer.java:846)
       at android.view.Choreographer.doFrame(Choreographer.java:776)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1023)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7986)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:553)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

**Comment by vibhor-d11** [comment]
> @vibhor-d11 how did you disable useNativeDriver for android 12 devices only? Users are experiencing this issue in random parts of my app. But I think it happens when navigating to a screen. There is an open issue for it [here](https://github.com/facebook/react-native/issues/37267).
> 
> This is the crash I get:
> 
> ```
> Fatal Exception: com.facebook.react.bridge.JSApplicationIllegalArgumentException: connectAnimatedNodes: Animated node with tag (child) [3851] does not exist
>        at com.facebook.react.animated.NativeAnimatedNodesManager.connectAnimatedNodes(NativeAnimatedNodesManager.java:371)
>        at com.facebook.react.animated.NativeAnimatedModule$16.execute(NativeAnimatedModule.java:777)
>        at com.facebook.react.animated.NativeAnimatedModule$ConcurrentOperationQueue.executeBatch(NativeAnimatedModule.java:171)
>        at com.facebook.react.animated.NativeAnimatedModule$3.execute(NativeAnimatedModule.java:365)
>        at com.facebook.react.uimanager.UIViewOperationQueue$UIBlockOperation.execute(UIViewOperationQueue.java:579)
>        at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:926)
>        at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1037)
>        at com.facebook.react.uimanager.UIViewOperationQueue.-$$Nest$mflushPendingBatches()
>        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1097)
>        at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
>        at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
>        at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
>        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1036)
>        at android.view.Choreographer.doCallbacks(Choreographer.java:846)
>        at android.view.Choreographer.doFrame(Choreographer.java:776)
>        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1023)
>        at android.os.Handler.handleCallback(Handler.java:938)
>        at android.os.Handler.dispatchMessage(Handler.java:99)
>        at android.os.Looper.loopOnce(Looper.java:201)
>        at android.os.Looper.loop(Looper.java:288)
>        at android.app.ActivityThread.main(ActivityThread.java:7986)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:553)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
> ```

We disabled it using `Platform` api from react native to identify if the os is android and version is 12. Here is code snippet for same

**Comment by lucasoliveiraw00** [comment]
I am going through the same situation, with over 42 thousand errors in a short period.
![299676322-37c9957c-4a0a-48dd-9ac5-2b8c4e3089b9](https://github.com/react-navigation/react-navigation/assets/42048768/7cf7918d-6b01-4d7c-bfdc-824ffcb8acf9)

**Comment by lucasoliveiraMM** [comment]
The error is related to the Animated component of React Native. Wouldn't it be better to remove its usage and utilize the Animated from react-native-reanimated? After all, there's still no solution for the error in the Animated component of React Native.

[Link to the issue in react-native-reanimated](https://github.com/software-mansion/react-native-reanimated/issues/4242#issuecomment-1547816213)

**Comment by douglasjunior** [comment]
Still happening.

**Comment by ahsan-lebara** [comment]
Still happening.

**Comment by yasinsolak** [comment]
Still happening.

**Comment by lucasoliveiraw00** [comment]
Still happening.

**Comment by douglasjunior** [comment]
Please guys, leave a thumbs up on this issue, and also on this PR #11866 to help the maintainers to prioritize this case.

**Comment by deepanshushuklad11** [comment]
Can we get this PR merge.

**Comment by dprevost-LMI** [comment]
It is unfortunate to close this without assessing the number of impacted clients. We were waiting for his fix because all other avenues had a performance impact. Now I see that the only way to have a fix is to let Android 12 die with the years.

**Comment by DewantiV** [comment]
same issue
