### ISSUE TITLE
Dropdown and popover components opening at incorrect position in iOS when using default header in React Navigation 6 stack

### ISSUE THREAD

**Issue by ManiTWIndia** [react-navigation/react-navigation#11892]
### Current behavior

When opening the select component, the dropdown list appears shifted upwards. It positions itself above its expected location by the exact height of the header.

https://github.com/react-navigation/react-navigation/assets/104359410/cf30327a-852e-4d86-a1e0-ac7f4161ffcb

React Native version: 0.73.6
@react-navigation/stack version: 6.3.28
React Native new architecture: Fabric
Device/OS: iOS

The issue happens in React native new architecture and it is not happening only for the above mentioned Select component (react-native-modal-dropdown) but also happens in Popover component (react-native-popover-view)

### Expected behavior

The dropdown should open right below the select component as in below video. This works when we pass headerShown: false in options or custom header is passed. Issue happens when using default header from react-navigation-stack.

https://github.com/react-navigation/react-navigation/assets/104359410/c65acde1-1696-4717-b1e8-6c8a30d46665

### Reproduction

https://github.com/ManiTWIndia/stack-navigation-header-issue

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.1.16
| @react-navigation/stack                | 6.3.28
| react-native-safe-area-context         | 4.9.0
| react-native-screens                   | 3.29.0
| react-native-gesture-handler           | 2.15.0
| react-native-reanimated                | 3.8.0
| react-native                           | 6.1.16
| node                                   | v20.11.1
| npm or yarn                            | 10.2.4

**Comment by satya164** [comment]
Open an issue in the dropdown library.
