### ISSUE TITLE
Header height not getting calculated in pageY value for components in new architecture

### ISSUE THREAD

**Issue by ManiTWIndia** [react-navigation/react-navigation#11894]
### Current behavior

When using default header from the stack navigation, facing inconsistency in pageY value of component rendered in old and new architecture. In the example screenshots, I am passing screenOptions={{headerStyle: {height: 150}}} to Stack navigator in React native new architecture and the pageY is being returned without taking the header height into consideration. 
![iOS new architecture](https://github.com/react-navigation/react-navigation/assets/104359410/087a43b2-97af-41ce-9ef3-443bc986f40f)

### Expected behavior

But in old architecture in iOS, the header height is included in the pageY value. 
![iOS old architecture](https://github.com/react-navigation/react-navigation/assets/104359410/3503819b-ace5-4b9a-b097-e8272f8e72be)

The issue happens in iOS new architecture only. A lot of existing libraries we were using is getting affected when using the stack navigation in new architecture. In android, even with the new architecture the pageY value is the same including the header height in both old and new architecture.

### Reproduction

https://github.com/ManiTWIndia/stack-navigation-header-issue

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.1.16
| @react-navigation/stack                | 6.3.28
| react-native-safe-area-context         | 4.9.0
| react-native-screens                   | 3.29.0
| react-native-gesture-handler           | 2.15.0
| react-native-reanimated                | 3.8.0
| react-native                           | 6.1.16
| node                                   | v20.11.1
| npm or yarn                            | 10.2.4

**Comment by satya164** [comment]
Please open an issue in React Native repo. React Navigation isn't giving you `pageY` value.

**Comment by ManiTWIndia** [comment]
In old architecture and in new architecture android, the pageY value is returned as expected. Even in iOS, when i use headerShown: false or custom header in react-navigation stack, the pageY value is returned as expected.
I am seeing this issue only when using the default header of react-navigation stack in new architecture. So please do have a look
