### ISSUE TITLE
Pressable interaction issue with StackNavigator on iPhone Xs + new architecture

### ISSUE THREAD

**Issue by omniphx** [react-navigation/react-navigation#11900]
### Current behavior

On iPhone Xs/Xs Max + the new architecture enabled, Pressable does not correctly respond to `onPress` when wrapped inside a StackNavigator. Seems to be an issue related to the `Pressable` rectangle not accounting for the space that the header takes up. If the component is not inside a StackNavigator screen, it will behave correctly.

Observed that touching the "pressable" area emits a `LEAVE_RECT_AREA` signal, but when I move my press to the top of the screen it will emit a `ENTER_RECT_AREA` signal and fire the onPress. Seems to think the pressable area is at the top of the screen possibly caused by the stack header. 

https://github.com/react-navigation/react-navigation/assets/3722405/d91f53fe-c5b7-4ad6-af41-814a3fa18340

**To reproduce**
1. Clone this repo: https://github.com/omniphx/reproducer-navigation
2. `cd ReproducerApp`
3. `yarn`
4. `yarn install:pods`
5. `yarn ios`

```
System:
  OS: macOS 14.4
  CPU: (10) arm64 Apple M2 Pro
  Memory: 134.39 MB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.11.0
    path: ~/.nvm/versions/node/v20.11.0/bin/node
  Yarn:
    version: 1.22.21
    path: ~/.nvm/versions/node/v20.11.0/bin/yarn
  npm:
    version: 10.2.4
    path: ~/.nvm/versions/node/v20.11.0/bin/npm
  Watchman:
    version: 2023.12.04.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.14.3
    path: /Users/MITCHMX20/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.4
      - iOS 17.4
      - macOS 14.4
      - tvOS 17.4
      - visionOS 1.1
      - watchOS 10.4
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.10671973
  Xcode:
    version: 15.3/15E204a
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.10
    path: /usr/bin/javac
  Ruby:
    version: 2.7.6
    path: /Users/MITCHMX20/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.6
    wanted: 0.73.6
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: true
```

### Expected behavior

Pressable should fire `onPress` when inside StackNavigator screen

### Reproduction

https://github.com/omniphx/reproducer-navigation

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |  6.1.16 |
| @react-navigation/bottom-tabs          | n/a |
| @react-navigation/drawer               | n/a |
| @react-navigation/material-top-tabs    | n/a |
| @react-navigation/stack                | ^6.3.28 |
| @react-navigation/native-stack         | n/a |
| react-native-safe-area-context         | ^4.9.0 |
| react-native-screens                   | ^3.29.0 |
| react-native-gesture-handler           | ^2.15.0 |
| react-native-reanimated                | n/a |
| react-native-tab-view                  | n/a |
| react-native-pager-view                | n/a |
| react-native                           | 0.73.6 |
| expo                                   | n/a |
| node                                   | v20.11.0 |
| npm or yarn                            | npm@10.2.4 |

**Comment by satya164** [comment]
Please open an issue in React Native repo. Stack Navigator is made up of views from React Native and has no control over  any measurements components make.

**Comment by omniphx** [comment]
In case anyone else comes across this, opened a new issue in the React Native repo: https://github.com/react-navigation/react-navigation/issues/11900

**Comment by cortinico** [comment]
@satya164 are you folks using `react-native-screens` under the hood? If so, the problem is the same as this one:
- https://github.com/facebook/react-native/issues/36710

Which has already been resolved in 0.74

**Comment by satya164** [comment]
@cortinico Thanks, yes we use`react-native-screens` under the hood

To verify it's the same issue, can you try the following @omniphx 

1. Disable`react-native-screens` by using `detachInactiveScreens={false}` on the stack navigator and see if you can still repro this
2. Test with React Native 0.74 as @cortinico mentioned

**Comment by omniphx** [comment]
@satya164 yup, verified it works with `detachInactiveScreens={false}` as well as when upgrading to RN 0.74. Thanks for the help!

**Comment by cortinico** [comment]
Great stuff
