### ISSUE TITLE
7.0.0-alpha.15 @react-navigation/material-top-tabs - tabBarIcons are not showing.

### ISSUE THREAD

**Issue by schoy3** [react-navigation/react-navigation#11904]
### Current behavior

tabBarIcon are not showing in the tab bar. 

### Expected behavior

The tabBarIcon should display an icon in the top tab bar. 
Example code:

import { createMaterialTopTabNavigator } from '@react-navigation/material-top-tabs';
const Tab = createMaterialTopTabNavigator();

export default function Example({ navigation, route }) {
    return (
        <Tab.Navigator
            screenOptions={{  tabBarShowIcon: true }} >
            <Tab.Screen
                options={{ tabBarIcon: () => <Icon /> }}
                name="Screen1" component={Screen1} />
        </Tab.Navigator>
    );
}

### Reproduction

https://snack.expo.dev/@schoy2/top-navigation-icons

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [X] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 7.0.0-alpha.15
| @react-navigation/bottom-tabs          | 7.0.0-alpha.18
| @react-navigation/drawer               | 7.0.0-alpha.16
| @react-navigation/material-top-tabs    | 7.0.0-alpha.15
| @react-navigation/stack                | 7.0.0-alpha.16
| @react-navigation/native-stack         | 7.0.0-alpha.16
| react-native-safe-area-context         | 4.7.1
| react-native-screens                   | 3.29.0
| react-native-gesture-handler           | 2.15.0
| react-native-reanimated                | 3.8.1
| react-native-pager-view                | 6.2.2
| react-native                           | 0.73.6
| node                                   | 18
| npm or yarn                            | yarn

**Comment by migueldaipre** [comment]
Please add a minimal repro

**Comment by schoy3** [comment]
@migueldaipre Here is my expo snack: https://snack.expo.dev/@schoy2/top-navigation-icons
