### ISSUE TITLE
When using frosted glass stack to jump in Android mode, ReactNavigation will experience lag and frosted glass will reset

### ISSUE THREAD

**Issue by yuhao965472200** [react-navigation/react-navigation#11920]
### Current behavior

https://github.com/react-navigation/react-navigation/assets/86100818/79b0b295-9b7b-4896-842a-7580a4803513

### Expected behavior

\

### Reproduction

\

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

System:
  OS: macOS 13.5.1
  CPU: (8) arm64 Apple M1 Pro
  Memory: 57.97 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.19.1
    path: ~/.nvm/versions/node/v18.19.1/bin/node
  Yarn:
    version: 1.22.21
    path: ~/.nvm/versions/node/v18.19.1/bin/yarn
  npm:
    version: 10.2.4
    path: ~/.nvm/versions/node/v18.19.1/bin/npm
  Watchman:
    version: 2024.01.22.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - visionOS 1.0
      - watchOS 10.2
  Android SDK: Not Found
IDEs:
  Android Studio: 2023.2 AI-232.10227.8.2321.11479570
  Xcode:
    version: 15.2/15C500b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.10
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.6
    wanted: 0.73.6
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

**Comment by migueldaipre** [comment]
Please add a minimal reproducer

**Comment by yuhao965472200** [comment]
> Please add a minimal reproducer

How to add?

**Comment by migueldaipre** [comment]
> Hey @yuhao965472200! Thanks for opening the issue. It seems that the issue doesn't contain a link to a repro.
> 
> **The best way to get attention to your issue is to provide an easy way for a developer to reproduce the issue.**
> 
> You can provide a repro using any of the following:
> 
> * [Expo Snack](https://snack.expo.io)
> * [TypeScript Playground](https://www.typescriptlang.org/play)
> * GitHub repo under your username
> 
> A snack link is preferred since it's the easiest way to both create and share a repro. If it's not possible to create a repro using a snack, link to a GitHub repo under your username is a good alternative. **Don't link to a branch or specific file etc.** as it won't be detected.
> 
> Try to keep the repro as small as possible by narrowing down the minimal amount of code needed to reproduce the issue. **Don't link to your entire project or a project containing code unrelated to the issue.** See ["How to create a Minimal, Reproducible Example"](https://stackoverflow.com/help/minimal-reproducible-example) for more information.
> 
> You can edit your original issue to include a link to the repro, or leave it as a comment. **The issue will be closed automatically after a while** if you don't provide a repro.

@yuhao965472200
