### ISSUE TITLE
[Bridgeless] [RN 0.74] Event cannot be both direct and bubbling: topFocus

### ISSUE THREAD

**Issue by tjzel** [react-navigation/react-navigation#11928]
### Current behavior

Install brand new app with 
`npx react-native@next init NavigationApp --version 0.74.0-rc.6`

add all the necessary dependencies.

When running this bit of code:

```tsx
import {createNativeStackNavigator} from '@react-navigation/native-stack';
import {NavigationContainer} from '@react-navigation/native';

import React from 'react';

function HomeScreen({navigation}) {
  navigation.setOptions({
    headerSearchBarOptions: {},
    headerTransparent: false,
  });

  return null;
}

const Stack = createNativeStackNavigator();

export default function App() {
  return (
    <NavigationContainer>
      <Stack.Navigator>
        <Stack.Screen name="Home" component={HomeScreen} />
      </Stack.Navigator>
    </NavigationContainer>
  );
}

```

I am getting the error:

`Event cannot be both direct and bubbling: topFocus`

It's on:
```package.json
    "@react-navigation/native": "^7.0.0-alpha.18",
    "@react-navigation/native-stack": "^7.0.0-alpha.20",
    "react": "18.2.0",
    "react-native": "0.74.0-rc.6",
    "react-native-safe-area-context": "^4.10.0-rc.1",
    "react-native-screens": "^3.31.0-rc.1"
```

### Expected behavior

No crashes 🤡 

### Reproduction

no-repro.com

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 7.0.0-alpha.18 |
| @react-navigation/native-stack         | 7.0.0-alpha.20 |
| react-native-safe-area-context         | 4.10.0-rc.1 |
| react-native-screens                   | 3.31.0-rc.1 |
| react-native                           | 0.74.0-rc.6 |

**Comment by kuldipopenxcell** [comment]
I'm getting similar issue in android when i use Marker component of react-native-maps in MapView. 

 <MapView
        provider={PROVIDER_GOOGLE} // remove if not using Google Maps
        style={styles.map}
        region={{
          latitude: 37.78825,
          longitude: -122.4324,
          latitudeDelta: 0.015,
          longitudeDelta: 0.0121,
        }}>
        <Marker coordinate={{latitude: 37.78825, longitude: -122.4324}}>
          <Image source={images.marker} style={styles.marker} />
        </Marker>
</MapView>

Find the attached screenshot:
![Uploading Screenshot 2024-04-12 at 2.35.45 PM.png…]()

**Comment by tboba** [comment]
Hi @tjzel, thanks for submitting this issue 🙏 
I can confirm this issue happens on my side, this can be reproduced by switching our internal tests in test examples from non-searchbar test (e.g. Test761) to searchbar one (e.g. Test758). Thanks!

**Comment by tboba** [comment]
Hi! We've opened right now a PR that fixes this change. You can follow the progress [here](https://github.com/software-mansion/react-native-screens/pull/2154). For now, let me close this PR.

Cheers! 👋

**Comment by agestaun** [comment]
+1
