### ISSUE TITLE
Weird transition in navigation

### ISSUE THREAD

**Issue by JoseVov** [react-navigation/react-navigation#11925]
### Current behavior

The navigation is transitioning weirdly.

https://github.com/react-navigation/react-navigation/assets/96314055/ff07c2ff-0d84-4f2c-b52f-51b44be04d94

### Expected behavior

Navigation should work as it does in native apps or at least something similar.

### Reproduction

there is not.

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |
| @react-navigation/native-stack         |
| react-native-safe-area-context         |
| react-native-screens                   |
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native                           |

```
"@react-navigation/native": "6.1.17",
"@react-navigation/native-stack": "6.9.26",
"react": "18.2.0",
"react-native": "0.73.6",
"react-native-animated-pagination-dot": "0.4.0",
"react-native-gesture-handler": "2.15.0",
"react-native-reanimated": "3.8.1",
"react-native-screens": "3.30.1",
```

```
System:
  OS: macOS 14.1.1
  CPU: (8) arm64 Apple M1
  Memory: 111.77 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
```

**Comment by JoseVov** [comment]
The issue was caused because I did not define a background to the home view.

**Comment by JoseVov** [comment]
Hi @aknad,

My issue was that I defined a background image globally in my Main Container the one in which you mount the navigation. I moved the background to each component individually and that solved the issue

**Comment by aknad** [comment]
thanks @JoseVov,
unfortunately I haven't a background image so the issue is the same but the cause is different
