### ISSUE TITLE
Invariant Violation: requireNativeComponent: "RNSModalScreen" was not found in the UIManager.

### ISSUE THREAD

**Issue by ayushthumar** [react-navigation/react-navigation#11926]
### Current behavior

Below is my code and I am **not using expo**, I am using the react-native cli:

```
import * as React from 'react';
import { Text, View } from 'react-native';
import { NavigationContainer } from '@react-navigation/native';
import { createBottomTabNavigator } from '@react-navigation/bottom-tabs';

function HomeScreen() {
  return (
    <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
      <Text>Home!</Text>
    </View>
  );
}

function SettingsScreen() {
  return (
    <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
      <Text>Settings!</Text>
    </View>
  );
}

const Tab = createBottomTabNavigator();

export default function App() {
  return (
    <NavigationContainer>
      <Tab.Navigator>
        <Tab.Screen name="Home" component={HomeScreen} />
        <Tab.Screen name="Settings" component={SettingsScreen} />
      </Tab.Navigator>
    </NavigationContainer>
  );
}
```

**This is the error I am getting**

Invariant Violation: requireNativeComponent: "RNSModalScreen" was not found in the UIManager.

This error is located at:
    in RNSModalScreen
    in Unknown (created by InnerScreen)
    in Suspender (created by Freeze)
    in Suspense (created by Freeze)
    in Freeze (created by DelayedFreeze)
    in DelayedFreeze (created by InnerScreen)
    in InnerScreen (created by Screen)
    in Screen (created by MaybeScreen)
    in MaybeScreen (created by BottomTabView)
    in RNSScreenNavigationContainer (created by ScreenContainer)
    in ScreenContainer (created by MaybeScreenContainer)
    in MaybeScreenContainer (created by BottomTabView)
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by SafeAreaProviderCompat)
    in SafeAreaProviderCompat (created by BottomTabView)
    in BottomTabView (created by BottomTabNavigator)
    in PreventRemoveProvider (created by NavigationContent)
    in NavigationContent
    in Unknown (created by BottomTabNavigator)
    in BottomTabNavigator (created by App)
    in EnsureSingleNavigator
    in BaseNavigationContainer
    in ThemeProvider
    in NavigationContainerInner (created by App)
    in App
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in appUI(RootComponent), js engine: hermes
    
**Screenshot**

<img width="570" alt="Screenshot 2024-04-03 at 12 28 26 PM" src="https://github.com/react-navigation/react-navigation/assets/90693731/8a452d06-4458-4ad6-bffc-065dd4eb6a68">

### Expected behavior

What I want is

![image](https://github.com/react-navigation/react-navigation/assets/90693731/ff5b1fbc-3f95-481e-a3a1-0ac4b9db85b2)

### Reproduction

https://reactnavigation.org/docs/tab-based-navigation

### Platform

- [x] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [X] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.1.17
| @react-navigation/bottom-tabs          | 6.5.20
| react-native                           | 0.73.6
| node                                   | 18.0.0
| npm or yarn                            | 10.5.0

**Comment by Dhruv-88** [comment]
hello @ayushthumar  can you share how you resolve this issue please ?

**Comment by ayushthumar** [comment]
> hello @ayushthumar can you share how you resolve this issue please ?

Hello dhruv, I just deleted the build file in ios folder and then rebuild it, and also I stopped the server at port 8081 and restarted it !

**Comment by WyattBensman** [comment]
I am using Expo, and I am receiving the same error with the same code you provided. Any insight on how to correct this? I saw you mentioned deleting the build file in ios folder, where exactly is this? Any other tips?

**Comment by ayushthumar** [comment]
> I am using Expo, and I am receiving the same error with the same code you provided. Any insight on how to correct this? I saw you mentioned deleting the build file in the ios folder, where exactly is this? Any other tips?

<img width="1440" alt="Screenshot 2024-04-05 at 10 34 33 AM" src="https://github.com/react-navigation/react-navigation/assets/90693731/87a445ef-db5d-459d-a7d4-17267e1f4e39">

In your home directory there will be ios folder, go in that folder and run command `rm -r build` and then again run the app in simulator or your device that will automatically create new latest build file.

**Comment by netshade** [comment]
I think you may have accidentally tagged me on this issue, I'm not able to assist with this.

**Comment by WyattBensman** [comment]
> > I am using Expo, and I am receiving the same error with the same code you provided. Any insight on how to correct this? I saw you mentioned deleting the build file in the ios folder, where exactly is this? Any other tips?
> 
> <img alt="Screenshot 2024-04-05 at 10 34 33 AM" width="1440" src="https://private-user-images.githubusercontent.com/90693731/320057285-87a445ef-db5d-459d-a7d4-17267e1f4e39.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzMzE3ODEsIm5iZiI6MTcxMjMzMTQ4MSwicGF0aCI6Ii85MDY5MzczMS8zMjAwNTcyODUtODdhNDQ1ZWYtZGI1ZC00NTlkLWE3ZDQtMTcyNjdlMWY0ZTM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA1VDE1MzgwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkM2YxMzQ5OGMwZmU3NGJjYjEyNzMwNDMxYWUxODk5Mjk4MzQ3N2QxMTU3Y2MxMjU4ZTIyYzRiNGViOTIwMTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XsnuCfapXb1HhIoYIeB70s6kb-rKlJhTbt_j6UWc2g0">
> In your home directory there will be ios folder, go in that folder and run command `rm -r build` and then again run the app in simulator or your device that will automatically create new latest build file.

I sadly don't have the same file structure. I will continue to trouble shoot & hopefully find a solution.

**Comment by aminesebastian** [comment]
Just want to report I'm experiencing this too on Expo.

**Comment by jeremiasr** [comment]
Thanks! aminesebastian it's work!

**Comment by gulsher7** [comment]
same error facing . Tried all methods but now working

**Comment by alphayowakarindi** [comment]
I had the same issue and running `npx expo install react-native-screens react-native-safe-area-context` fixed the issue.
Source: https://reactnavigation.org/docs/getting-started#installing-dependencies-into-an-expo-managed-project

**Comment by Petercopter** [comment]
Same error as OP here. Another similarity is that it's the Tabs component
* Using Expo with file based routing
* Navigating from sign in (root) to `/(app)/(tabs)`
* Downgrading to 3.29.0 resolves the issue

**Comment by Generalchrist** [comment]
I'm encountering the same issue as described in this thread. However, I'm using `createStackNavigator` as outlined in the [documentation](https://reactnavigation.org/docs/typescript/#type-checking-the-navigator).

While the application runs smoothly on the Android emulator, it throws the following error and gets stuck at the splash screen when launched on my iPhone 7:

` ERROR  Invariant Violation: requireNativeComponent: "RNSModalScreen" was not found in the UIManager.`

- I'm not using `react-native-screens` 
- I'm using expo so I don't have the same folder structure

**Comment by abisalde** [comment]
> Just want to report I'm experiencing this too on Expo. I was able to resolve it by downgrading `react-native-screens` to `3.29.0`:
> 
> ```
> npm install react-native-screens@~3.29.0
> ```

This works

**Comment by protonforest** [comment]
yeah theres definetly something wrong with the last 3.30 version

**Comment by codegabk** [comment]
Is there a workaround without downgrading from 3.30 to 3.29 ?

**Comment by ayushthumar** [comment]
> Is there a workaround without downgrading from 3.30 to 3.29 ?

Till now I have not found any other way to get the work done with 3.30 !
