### ISSUE TITLE
RemoveEventListener error in react-native-navigation@4 

### ISSUE THREAD

**Issue by gkasireddy202** [react-navigation/react-navigation#11936]
### Current behavior

I have used react-navigation: 4.4.4 in my project for the last 5 years.
I upgraded the react-navigation to 0.73.2 and got this error.
_reactNative.Linking.removeEventListener is not a function (it is undefined)

### Expected behavior

I expect this error will be resolved.

### Reproduction

Private repo maintained by company

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

"react-navigation": "^4.4.4",
"react-navigation-drawer": "^2.7.2",
"react-navigation-stack": "^2.10.4",
"react-navigation-tabs": "^2.11.2",
![Simulator Screenshot - iPhone 15 Pro Max - 2024-04-13 at 15 00 37](https://github.com/react-navigation/react-navigation/assets/90603484/95c46c03-454e-44e5-9022-6a0bff333670)

**Comment by gkasireddy202** [comment]
"react-navigation": "^4.4.4",

**Comment by radko93** [comment]
This React Navigation version is not maintained anymore so it won't be updates. Only latest React Navigation is supported currently.

**Comment by gkasireddy202** [comment]
> Hey! This issue is closed and isn't watched by the core team. You are welcome to discuss the issue with others in this thread, but if you think this issue is still valid and needs to be tracked, please open a new issue with a repro.

How to add repro?It is my company repo.

**Comment by gkasireddy202** [comment]
> > Hey! This issue is closed and isn't watched by the core team. You are welcome to discuss the issue with others in this thread, but if you think this issue is still valid and needs to be tracked, please open a new issue with a repro.
> 
> How to add repro?It is my company repo.
We have maintained this navigation@4 for last 7 years.So please check the issue once.
