### ISSUE TITLE
To prevent the default behavior using e.preventDefault() on `tabPress` event is no longer working

### ISSUE THREAD

**Issue by vikassharma96** [react-navigation/react-navigation#11935]
### Current behavior

To prevent the default behavior by calling event.preventDefault() on `tabPress` event is no longer working for the first time even though it is mentioned in the official documentation [@react-navigation/bottom-tabs@^6.5.19](https://reactnavigation.org/docs/bottom-tab-navigator/#events)

### Expected behavior

It should prevent the default behavior for `tabPress` event after calling `event.preventDefault()` for the first and subsequent times

### Reproduction

https://snack.expo.dev/Hek2xjzn0zFcww-yg0C1L

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [x] @react-navigation/stack
- [x] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.1.10
| @react-navigation/bottom-tabs          | 6.5.19
| @react-navigation/native-stack         | 6.9.18
| react-native-safe-area-context         | 4.9.0
| react-native-screens                   | 3.29.0
| react-native-gesture-handler           | 2.16.0
| react-native-reanimated                | 3.8.1
| react-native                           | 0.73.4
| node                                   | 18.19.0
| npm or yarn                            | 10.2.3

**Comment by satya164** [comment]
Screens are only rendered after you navigate to it the first time. Your code for listener isn't called https://reactnavigation.org/docs/bottom-tab-navigator/#lazy
