### ISSUE TITLE
Ripple effect shown twice after clicking one time on material top tab after new architecture enabled.

### ISSUE THREAD

**Issue by hpurohit97** [react-navigation/react-navigation#11930]
### Current behavior

When the user click on the top tab, the screen is smoothly transitioned but the ripple effect is shown multiple times.

### Expected behavior

Ripple effect should only come once.

### Reproduction
Worked on a personal project, cannot share link here.

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [X] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [X] @react-navigation/native-stack
- [X] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.1.17
| @react-navigation/bottom-tabs          | 6.5.20
| @react-navigation/material-top-tabs    | 6.6.13
| @react-navigation/stack                | 6.3.29
| @react-navigation/native-stack         | 6.9.13
| react-native-safe-area-context         |  4.9.0
| react-native-screens                   | 3.30.1
| react-native-gesture-handler           | 2.15.0
| react-native-reanimated                |   3.8.0
| react-native-tab-view                  | 3.5.2
| react-native-pager-view                |  6.2.3
| react-native                           |  0.73.6

**Comment by KManiKumarReddy** [comment]
I'm on the latest versions and still experience this intermittently, I'll attach a expo snack soon. I'm attaching a video of what's happening
![Screen Recording 2024-04-19 at 7 37 04 PM1](https://github.com/react-navigation/react-navigation/assets/13102841/dcd6d11f-ee51-4cf0-b50f-2abd6f7f5eab)

**Comment by hpurohit97** [comment]
@KManiKumarReddy I didn't find the reason for this yet. But to disable it we can update material-top-tabs and use tabBarRippleConfig={radius: 0} in screen options

**Comment by shovel-kun** [comment]
Still happening on RN 0.75.3 with material top tabs `7.0.0-rc.23`

**Comment by MichalKrakow** [comment]
Does enyone even use expo? How is this not addressed in newest versions. Clean install of expo latest on 10.02.2025 single tap on any button fires ripple effect twice.

**Comment by kevingandrades** [comment]
Same here, any update about this?

**Comment by EchoEkhi** [comment]
Yeah I can confirm the bug disappears after upgrading to SDK 53
