### ISSUE TITLE
Bottom Tabs flash when opening keyboard 

### ISSUE THREAD

**Issue by PPHelios** [react-navigation/react-navigation#11940]
### Current behavior

When clicking inside an input field the bottom tabs move with the keyboard then disappears, is there a way to prevent this behavior using tabBarHideOnKeyboard: true

https://github.com/react-navigation/react-navigation/assets/103271591/64a22cc4-9c15-4390-ba92-e95cb61b8406

### Expected behavior

The keyboard opens without the bottom tabs showing or flashing, The only solution I found was to wrap the Tap.Navigator in a view with fixed width and height , but this is unreliable on older devices as Dimensions.get('screen').height and Dimensions.get('window').height gives same result on these devices , so I have to remove the height of statusbar and soft navigation bar manually, I could get the statusbar height but couldn't  find a way to get the navigation bar.

Is there an easy and reliable way to stop this effect or am I doing something wrong?

### Reproduction

https://github.com/PPHelios/Bottom-Tabs-Issue

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native             6.1.17  |
| @react-navigation/bottom-tabs         6.5.20 |
| react-native-safe-area-context        4.9.0 |
| react-native-screens                 3.30.1  |
| react-native                         0.73.6  |
| node                                   20|
| npm or yarn                            npm|

**Comment by dribble-njr** [comment]
This is especially obvious in dark mode. When the keyboard is awakened, the bottombar will be hidden and there will be a white flash.

**Comment by dribble-njr** [comment]
I find a [solution](https://github.com/react-navigation/react-navigation/issues/7447#issuecomment-541366297).
