### ISSUE TITLE
Task :react-native-safe-area-context:compileDebugKotlin FAILED

### ISSUE THREAD

**Issue by featlast** [react-navigation/react-navigation#11959]
### Current behavior

![image](https://github.com/react-navigation/react-navigation/assets/66761042/21f42482-6709-4e81-b230-cd2beac23fa2)

### Expected behavior

![image](https://github.com/react-navigation/react-navigation/assets/66761042/085fc124-c3ad-4e5f-aa64-a211336c77d0)

### Reproduction

https://github.com/featlast/RNanimate

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

    "@react-native-masked-view/masked-view": "^0.3.1",
    "@react-navigation/native": "^6.1.17",
    "@react-navigation/stack": "^6.3.29",
    "react": "18.2.0",
    "react-native": "0.74.0",
    "react-native-gesture-handler": "^2.16.0",
    "react-native-safe-area-context": "^4.9.0",
    "react-native-screens": "^3.31.1"

**Comment by jackiemacklein** [comment]
having the same problem here

**Comment by jackiemacklein** [comment]
@featlast update react-native-safe-area-context to 4.10.1.

it worked here

**Comment by featlast** [comment]
@jackiemacklein Thanks bro, I made the adjustment and it's working.

**Comment by sarowerj** [comment]
> @featlast update react-native-safe-area-context to 4.10.1.
> 
> it worked here

thinks. It's working fine

**Comment by ProgrammerNephi** [comment]
> @featlast update react-native-safe-area-context to 4.10.1.
> 
> it worked here

Thanks so much! Updating it to the latest version worked 👍

**Comment by Andreibv** [comment]
Im using     
"react-native-safe-area-context": "^4.10.9",
but not work :(

**Comment by Andreibv** [comment]
> [@Andreibv](https://github.com/Andreibv) have u find the solution my friend

You can try:

rm -rf ~/.gradle/caches
./gradlew --stop
./gradlew clean
./gradlew app:assembleDebug
