### ISSUE TITLE
App is freezing if you use drawer navigation on RN 73.7

### ISSUE THREAD

**Issue by BrianSoevii** [react-navigation/react-navigation#11956]
### Current behavior

Basically if you use drawer navigator app freezes, when i remove the drawer component the app works normally

```
import * as React from 'react';
import {
  createDrawerNavigator,
  DrawerContentComponentProps,
} from '@react-navigation/drawer';
import DrawerContent from './DrawerContent';
import AppStack from './AppStack';

const Drawer = createDrawerNavigator();

function DrawerStack() {
  return (
    <Drawer.Navigator
      drawerContent={(props: DrawerContentComponentProps) => (
        <DrawerContent {...props} />
      )}>
      <Drawer.Screen name="Main" component={AppStack} />
    </Drawer.Navigator>
  );
}

export default DrawerStack;
```

### Expected behavior

App not freezing :(

### Reproduction

it's not needed in this case

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.1.17
| @react-navigation/drawer             |6.6.15 
| @react-navigation/stack                |6.3.29
| @react-navigation/native-stack         |6.9.26
| react-native-safe-area-context         |4.9.0
| react-native-screens                   |3.30.1
| react-native-gesture-handler           |2.16.0
| react-native-reanimated                |3.8.1
| react-native                           |0.73.7

**Comment by tomDubrovsky** [comment]
any updates?
