### ISSUE TITLE
Cannot style shadow in react navigation header

### ISSUE THREAD

**Issue by demoox** [react-navigation/react-navigation#11970]
### Current behavior

**I tried this:**

```
screenOptions={{
  headerShown: true,
  headerStyle: {
    backgroundColor: '#4aceaf',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 5,
    elevation: 5
  },
  headerTitle: 'Home', 
  headerTintColor: '#000',
  headerTitleStyle: {
    fontSize: 15, 
  }, 
  headerShadowVisible: false
}}
```

**I also tried this:**

```
screenOptions={{
  headerShown: true,
  headerStyle: {
    backgroundColor: '#4aceaf
  },
contentStyle: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 5,
    elevation: 5
},
  headerTitle: 'Home', 
  headerTintColor: '#000',
  headerTitleStyle: {
    fontSize: 15, 
  }, 
  headerShadowVisible: false
}}
```
**no shadow appears:**
<img width="360" alt="obtained" src="https://github.com/react-navigation/react-navigation/assets/114532343/af16c6ad-2e64-46b0-a610-7b6cdce1f83c">

### Expected behavior

<img width="360" alt="expected" src="https://github.com/react-navigation/react-navigation/assets/114532343/7619e586-4bad-442b-ad25-0163cbc891c8">

### Reproduction

https://snack.expo.dev/@demoox/cannot-style-shadow-header

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | "^6.0.2"
| @react-navigation/native-stack | "^6.9.17"
| @react-navigation/stack                | "^6.3.29"
| react-native-gesture-handler | "~2.14.0"
| react-native-safe-area-context | "4.8.2"
| react-native-screens | "~3.29.0"
| react-native                           | "0.73.6"
| expo                                   | "~50.0.14"

**Comment by demoox** [comment]
> The versions mentioned in the issue for the following packages differ from the latest versions on npm:
> 
> * `@react-navigation/native` (found: `6.0.2`, latest: `6.1.17`)
> 
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?


**The problem persists**

**Comment by demoox** [comment]
**Anyone have a solution?**

**Comment by satya164** [comment]
As documented on this page, the only supported property is `backgroundColor`

https://reactnavigation.org/docs/native-stack-navigator/#headerstyle

**Comment by demoox** [comment]
ds

> Comme indiqué sur cette page, la seule propriété prise en charge est`backgroundColor`
> 
> https://reactnavigation.org/docs/native-stack-navigator/#headerstyle

Can you provide a clearer answer or solution instead of simply closing the topic?
Is it possible to add a personalized shadow? because many applications do it

**Comment by demoox** [comment]
@satya164 Thanks, I understood correctly that the only property supported by `headerStyle `is only `backgroundColor`.

Now what I'm asking: what solution to apply a shadow to the header?
What would be the way to proceed? Because I can't find any way to achieve this in the documentations.

Thank you for your help

**Comment by satya164** [comment]
@demoox native stack is less customizable as mentioned on top of the page and only supports what's supported by Android/iOS. If you want more customization you either need to use a custom header with the `header` option, or use JS stack (`@react-navigation/stack`).
