### ISSUE TITLE
Problem with "createDrawerNavigator"

### ISSUE THREAD

**Issue by stefunlive0** [react-navigation/react-navigation#11973]
### Current behavior

I would like to launch an app on Expo (Android Studio Giraffe) but I have this error

```
Android Bundling failed 20738ms (C:\Users\My-User\Desktop\Projet01\node_modules\expo\AppEntry.js)
Unable to resolve "@react-navigation/drawer" from "App.jsx"    
Android Bundling failed 31085ms (C:\Users\My-User\Desktop\Projet01\node_modules\expo\AppEntry.js)
Unable to resolve "@react-navigation/drawer" from "App.jsx"
```

Please can you solve the bug in my code ? :
```
import * as React from 'react';
import { Button, View, Text } from 'react-native';
import { NavigationContainer } from '@react-navigation/native';
import { createStackNavigator } from '@react-navigation/stack';
import { createBottomTabNavigator } from '@react-navigation/bottom-tabs';
import { createDrawerNavigator } from '@react-navigation/drawer';

function HomeScreen(props) {
  return (
    <View style={{flex: 1, alignItems: 'center', justifyContent: 'center'}}>
      <Text>Bonjour</Text>
      <Button title='Contact' onPress={() => {props.navigation.navigate('Contact')}}/>
    </View>
  )
};

function ContactScreen(props) {
  return (
    <View style={{flex: 1, alignItems: 'center', justifyContent: 'center'}}>
      <Text>Contact</Text>
      <Button title='Contact' onPress={() => {props.navigation.navigate('Home')}}/>
    </View>
  )
};

/*
const Stack = createStackNavigator();
const Tabs = createBottomTabNavigator();
*/
const Drawer = createDrawerNavigator();

export default function App() {
  return (
    <NavigationContainer>
      <Drawer.Navigator
        screenOptions={{
          headerStyle: {
            backgroundColor: 'green'
          },
          headerTitleStyle:{
            color: 'white',
            fontWeight: 'bold'
          }
        }}

      >
        <Drawer.Screen name='Home' component={HomeScreen}/>
        <Drawer.Screen name='Contact' component={ContactScreen}/>
      </Drawer.Navigator>
    </NavigationContainer>
  )
};

```
Thanks in advance

### Expected behavior

Normally it works every time when I test new React component.
I don't undestand where is the problem

### Reproduction

https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwBQokscA3nAEICuMMEAdgBo4ANWBYA7kIAqWAB7wAvnCIlylPDAC0fZDGAA3LLQbho8NgDlk+4AHNdwfgGF+MZMD5YocJStJkAAXV8bWs7B34Aeh09Q2NGM1Y4XHUYLABlN1wAaysbe15vX2J-IKotHXyIvkjULOz402Y2FJw09ggeEilkACM88MKfZRLyMo1Qqr0o3s7eEE03XtRGpnNk1KwAEShkcS8BguhhvzHgirCCxxqAE139qGM6Ak4+fGu4AAkSDNasPgAFGBiGBUABKVh0OBwSgwThQPhwAFQ6FwAA8ogkcDqAE8ADZYAC8LBYBAJsgAXHAAIxCZB4ux8ACSaRAqCpZFw-zSjyEACtOHVgAQcS4+GlxRyueKvGQFAoAHwo1HomTyBUdPh8iDwtGRNUwJUq6ForhdRF6GAEwlkMVZGBkOD8AAKlFQqGJAIhhIVrGBEFBADpKoNrsHLrosADba4NGQwfLIkbUXrMeJk2C6Ap6M9Xu9+HA7Rp0n9Af7QRCWCjYfDEciVRixOJsTB8USSWS5FTaSgGbZmaz2eRpTyyPzBXoRXbuVLubL5cmGwaFUX8Hrl8qU2beBbgFaiTHxXGnXxXVh3Z7vb6WOXUOGpmGQwUo2RviAjAmFEnN6mmxmszmkQIHQuD8HUcCZHg2RwISGxtBk9SHLo0BevQoF8OBPTLDBcGRh0XQgFhSGFKhdAIJEIFgfAOx7F4OGtJGNEPMRKFgjmchrHANxYAQyCcHihB5tMiIAIJgGAXqQtCNYIkiP7EdcRYeF4i4pkxXiBixUCbiqqClgA8mAwkeiSOnGgAFjg3FQJkbZUlWxqOXAvRQbYxCvDcLh4tAHJuVg-xkGZKoKAIQWopZyDWVIe4ErZBIUg5TkqqB3lQBy4jmXuRihUlKoEK4ADqWB2OZMAcrMeI3IFuU+GF8p0GZqkNupUCBiWlD-HAOjvjab5GMkJCQJ44rEn17X+XwX5NWp9waeNnXdQeq4OgNpjDTAxLLfNk3fo5eotZpEaFKpeoKc4sbKVA-7ZkAA

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.1.17
| @react-navigation/drawer               | 6.6.15
| @react-navigation/material-top-tabs    | 6.6.13
| @react-navigation/native-stack         |
| react-native-safe-area-context         |
| react-native-screens                   |
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native-tab-view                  | 3.5.2
| react-native-pager-view                |
| react-native                           |
| expo                                   |
| node                                   |
| npm or yarn                            |

**Comment by stefunlive0** [comment]
It's updated

**Comment by Vikas-singh-0** [comment]
@stefunlive0 I ran npm install instead of npx expo install and one extra step from documentation, 
`npx expo install react-native-gesture-handler react-native-reanimated`

Please try this if it helps.

`// import 'react-native-gesture-handler'
import { createDrawerNavigator } from "@react-navigation/drawer";
import { NavigationContainer } from "@react-navigation/native";
import { createNativeStackNavigator } from "@react-navigation/native-stack";
import { Button, StyleSheet, Text, View } from "react-native";

function HomeScreen() {
  return (
    <View style={{ flex: 1, alignItems: "center", justifyContent: "center" }}>
      <Text>Home Screen</Text>
    </View>
  );
}


function NotificationsScreen({ navigation }) {
  return (
    <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
      <Button onPress={() => navigation.goBack()} title="Go back home" />
    </View>
  );
}

const Drawer = createDrawerNavigator();

export default function App() {
  return (
    <NavigationContainer>
      <Drawer.Navigator initialRouteName="Home">
        <Drawer.Screen name="Home" component={HomeScreen} />
        <Drawer.Screen name="Notifications" component={NotificationsScreen} />
      </Drawer.Navigator>
    </NavigationContainer>
  );
}

const Stack = createNativeStackNavigator();

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
  text: {
    display: "flex",
    backgroundColor: "red",
    height: "1000px",
    color: "black",
  },
  btn: {
    width: "100px",
    height: "100px",
    backgroundColor: "red",
  },
});
`
I am using expo to run the app.

**Comment by stefunlive0** [comment]
> @stefunlive0 I ran npm install instead of npx expo install and one extra step from documentation, `npx expo install react-native-gesture-handler react-native-reanimated`
> 
> Please try this if it helps.
> 
> `// import 'react-native-gesture-handler' import { createDrawerNavigator } from "@react-navigation/drawer"; import { NavigationContainer } from "@react-navigation/native"; import { createNativeStackNavigator } from "@react-navigation/native-stack"; import { Button, StyleSheet, Text, View } from "react-native";
> 
> function HomeScreen() { return ( <View style={{ flex: 1, alignItems: "center", justifyContent: "center" }}> Home Screen ); }
> 
> function NotificationsScreen({ navigation }) { return ( <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}> <Button onPress={() => navigation.goBack()} title="Go back home" /> ); }
> 
> const Drawer = createDrawerNavigator();
> 
> export default function App() { return ( <Drawer.Navigator initialRouteName="Home"> <Drawer.Screen name="Home" component={HomeScreen} /> <Drawer.Screen name="Notifications" component={NotificationsScreen} /> </Drawer.Navigator> ); }
> 
> const Stack = createNativeStackNavigator();
> 
> const styles = StyleSheet.create({ container: { flex: 1, backgroundColor: "#fff", alignItems: "center", justifyContent: "center", }, text: { display: "flex", backgroundColor: "red", height: "1000px", color: "black", }, btn: { width: "100px", height: "100px", backgroundColor: "red", }, }); ` I am using expo to run the app.

Hello I have this error :
Android Bundling failed 29987ms (C:\Users\My-User\Desktop\Projet01\node_modules\expo\AppEntry.js)
Unable to resolve "@react-navigation/drawer" from "App.jsx"

I think that
```
import { createDrawerNavigator } from "@react-navigation/drawer";
```
creates the error.

I need to add this :
```
import 'react-native-gesture-handler'
```
?
