### ISSUE TITLE
Invariant Violation: requireNativeComponent: "LEGACY_RNCViewPager" was not found in the UIManager.

### ISSUE THREAD

**Issue by JmarshTri** [react-navigation/react-navigation#11999]
### Current behavior

I've tried anything from RN 73, Reanimated 2 and 3 

import * as React from 'react'
import { View, useWindowDimensions } from 'react-native'
import { TabView, SceneMap } from 'react-native-tab-view'

const FirstRoute = () => (
  <View style={{ flex: 1, backgroundColor: '#ff4081' }} />
)

const SecondRoute = () => (
  <View style={{ flex: 1, backgroundColor: '#673ab7' }} />
)

const renderScene = SceneMap({
  first: FirstRoute,
  second: SecondRoute,
})

export default function TabViewExample() {
  const layout = useWindowDimensions()

  const [index, setIndex] = React.useState(0)
  const [routes] = React.useState([
    { key: 'first', title: 'First' },
    { key: 'second', title: 'Second' },
  ])

  return (
    <TabView
      navigationState={{ index, routes }}
      renderScene={renderScene}
      onIndexChange={setIndex}
      initialLayout={{ width: layout.width }}
    />
  )
}

### Expected behavior

Render the tab view without crashing

### Reproduction

Can't produce 

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [X] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
"@react-navigation/bottom-tabs": "^6.5.20",
"@react-navigation/native": "^6.1.17",
"@react-navigation/stack": "^6.3.29",
"react-native-safe-area-context": "4.10.1",
"react-native-screens": "^3.31.1",
"react-native-gesture-handler": "^2.14.0",
"react-native-reanimated": "^3.11.0",
"react-native-tab-view": "3.5.2",
"react-native-pager-view": "^6.3.1",
"react-native": "0.74.1",
"yarn": "^1.22.4"

**Comment by arslan-Techno** [comment]
@JmarshTri  did you find any solution ??

**Comment by kaaaaaaaaaaai** [comment]
same problems

**Comment by arslan-Techno** [comment]
npm i  react-native-pager-view and `cd ios && pod install` worked for me

**Comment by rodrigoAbril** [comment]
installing it thru expo fixed it for me
`npx expo install react-native-pager-view`

**Comment by JmarshTri** [comment]
I added react-native-pager-view via yarn and that does not work. I've also ran "rm -rf node_modules; rm -rf ios/build; rm -rf ios/Pods; rm -rf ios/Podfile.lock; yarn; yarn pods" after installing pager-view still getting the error.

I also tried  npx expo install react-native-pager-view no success with that either

**Comment by kaaaaaaaaaaai** [comment]
i tried, me too

**Comment by SwanHub** [comment]
> installing it thru expo fixed it for me `npx expo install react-native-pager-view`

worked for me

**Comment by jilvanx** [comment]
If you are using expo run: `npx expo run:ios` or `npx expo run:android`
Worked for me

**Comment by JmarshTri** [comment]
I'm not using expo and have yet to find a solution that works

**Comment by dowatugkins** [comment]
@JmarshTri, did you ever get it figured out? I was having problems after installing it and running `pod install` so I ran all my blowout everything and rebuild commands and it did the trick for me. I ran my first aliased command `rm -rf node_modules/; rm package-lock.json; rm yarn.lock; cd ios; rm -rf Pods/; rm Podfile.lock; rm -rf build/; cd ..; yarn install; cd ios; bundle exec pod repo update; bundle exec pod install; cd ..` and then my second aliased command `bundle install; cd ios; bundle exec pod repo update; bundle exec pod install; cd ..` followed by my reset cache command `yarn start --reset-cache` followed by my simulator run command `yarn ios --simulator 'iPhone 15 Pro Max (iOS 17.4)'` and it finally worked. Hopefully you've gotten it figured out by now though.

**Comment by viquanghoa** [comment]
after installing `npx expo install react-native-pager-view` 
worked for me.
**Remember that stop simulator then restart, it will work.**

**Comment by franfernandez20** [comment]
> npx expo install react-native-pager-view

That fix the problem for me 👌

**Comment by pratiksham28** [comment]
Not working for React-native cli - 
  "react": "18.2.0",
    "react-native": "0.74.2",
    "react-native-pager-view": "^6.3.3",
    "react-native-tab-view": "^3.5.2",
  "@react-navigation/bottom-tabs": "^6.5.20",
    "@react-navigation/material-top-tabs": "^6.6.14",
    "@react-navigation/native": "^6.1.17",
    "@react-navigation/native-stack": "^6.9.26",
    "@react-navigation/stack": "^6.4.0",

**Comment by bachvinh** [comment]
> installing it thru expo fixed it for me `npx expo install react-native-pager-view`

Worked for me

**Comment by arielcorte** [comment]
> installing it thru expo fixed it for me `npx expo install react-native-pager-view`

Worked for me! Thanks!

**Comment by shuvajitmaitra** [comment]
> installing it thru expo fixed it for me `npx expo install react-native-pager-view`


At first, I installed the package and removed the node_modules and installed it again and it worked for me.

Thanks

**Comment by LorenzoCruccu** [comment]
I still have this issue and by running  `npx expo install react-native-pager-view` it doesn't fix it. I tried to remove node_modules and package-lock.json, and I also tried to restart my simulator and i also tried to install different versions of this dependency (6.3.0, 6.3.1 and latest 6.4.1)

**Comment by n3ps** [comment]
Also encountering this issue
