### ISSUE TITLE
Toast hidden behind presentation: 'modal' group

### ISSUE THREAD

**Issue by longb1997** [react-navigation/react-navigation#12011]
### Current behavior

When creating toasts within a screen with presentation modal from react-navigation in iOS, the toast appears behind the modal. 

### Expected behavior

I expect the toasts to be visible and not appear behind the modal.

### Reproduction

.

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
    "@react-navigation/bottom-tabs": "6.4.1",
    "@react-navigation/drawer": "^6.6.2",
    "@react-navigation/native": "6.0.14",
    "@react-navigation/native-stack": "6.9.2",
    "@react-navigation/stack": "6.3.16",
    "react-native-safe-area-context": "^4.4.1",
    "react-native-screens": "3.18.2",
    "react-native-gesture-handler": "2.9.0",
    "react-native-reanimated": "2.14.4",
    "react-native": "0.71.13",

**Comment by danieldunderfelt** [comment]
I am also seeing issues with presentation: 'modal' on native stack navigators. KeyboardAvoidingView doesn't work properly, and @gorhom bottom sheets aren't visible over modals now. Changing to "card" makes the screens work properly. There are probably many more problems yet to discover.

Versions:

```
"@react-navigation/bottom-tabs": "6.5.20",
"@react-navigation/elements": "1.3.30",
"@react-navigation/material-top-tabs": "6.6.13",
"@react-navigation/native": "6.1.17",
"@react-navigation/native-stack": "6.9.26",
"@react-navigation/stack": "6.3.29",
```

I'll try to downgrade versions and see where it starts happening.

**Comment by raajnadar** [comment]
You guys don't read the docs and then complain things are not working properly

https://github.com/software-mansion/react-native-screens?tab=readme-ov-file#fullwindowoverlay

**Comment by danieldunderfelt** [comment]
> You guys don't read the docs and then complain things are not working properly
> 
> https://github.com/software-mansion/react-native-screens?tab=readme-ov-file#fullwindowoverlay

presentation: 'modal' worked before. Now it does not. Your link doesn't explain anything related to this.

I can use "fullScreenModal" in react-navigation, but "full window overlay" is not a thing. "fullScreenModal" works, but does not show the layered modal effect in iOS like "modal" did.

So do I understand this correctly, that you just broke "modal" with no replacement?

**Comment by Josefnm** [comment]
I got this working by wrapping my toast in FullWindowOverlay.


````
const Toast = () => {
....
  <FullWindowOverlay>
   <Animated.View style={[s.background, { transform: [{ translateY: translateY.current }] }]}>
     ...
   </Animated.View>
  </FullWindowOverlay>
}
````
```
const RootStack = createNativeStackNavigator({
  layout: () => {
    return (
      <>
        <Toast />
        {children}
      </>
    )
  },
```

![Image](https://github.com/user-attachments/assets/97410e33-c718-4c3b-94c2-81d8fa06e56e)

![Image](https://github.com/user-attachments/assets/978cc6d7-f668-41e1-a310-46b7080d8416)

**Comment by ironweber** [comment]
@Josefnm This is the way. Works with the custom Dialog component I made.

Also if anyone is looking to prevent clicks underneath the FullWindowOverlay this worked for me https://github.com/software-mansion/react-native-screens/issues/1666#issuecomment-1873598993

**Comment by chiefchief** [comment]
> I got this working by wrapping my toast in FullWindowOverlay.
> 
> ```
> const Toast = () => {
> ....
>   <FullWindowOverlay>
>    <Animated.View style={[s.background, { transform: [{ translateY: translateY.current }] }]}>
>      ...
>    </Animated.View>
>   </FullWindowOverlay>
> }
> ```
> 
> ```
> const RootStack = createNativeStackNavigator({
>   layout: () => {
>     return (
>       <>
>         <Toast />
>         {children}
>       </>
>     )
>   },
> ```
> 
> ![Image](https://github.com/user-attachments/assets/97410e33-c718-4c3b-94c2-81d8fa06e56e)
> 
> ![Image](https://github.com/user-attachments/assets/978cc6d7-f668-41e1-a310-46b7080d8416)

works amazing, thank you
