### ISSUE TITLE
detachPreviousScreen is not set to false when using "presentation: 'modal'" option

### ISSUE THREAD

**Issue by IgorVanian** [react-navigation/react-navigation#12016]
### Current behavior

Hi!

The [docs](https://reactnavigation.org/docs/stack-navigator/#detachpreviousscreen) say that `detachPreviousScreen` is set to `false` if `presentation` is set to `transparentModal` or `modal`.

It seems that it is not the case:
https://github.com/react-navigation/react-navigation/blob/25e834b4f330fb05b4ecdbe81ef7f2f065fd26c8/packages/stack/src/views/Stack/CardStack.tsx#L615-L616

In my app, it's `true` by default on **iOS** and the previous screen is visible but on **Android** the previous screen is not visible.

Is it a mistake in the docs or in the code? Should I make a PR with `detachPreviousScreen = options.presentation === 'transparentModal' || options.presentation === 'modal'` ?

### Expected behavior

If the docs are correct, `detachPreviousScreen` should be set to `false` when using  `presentation: 'modal'`

### Reproduction

None.

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.1.6
| @react-navigation/bottom-tabs          | 6.3.1
| @react-navigation/stack                | 6.3.16
| react-native-screens                   | 3.29.0
| react-native-gesture-handler           | 2.15.0
| react-native-reanimated                | 3.7.1
| react-native-tab-view                  | 3.1.1
| react-native-pager-view                | 5.4.11
| react-native                           | 0.73.6
| node                                   | 18.16.1
| npm or yarn                            | 1.22.17

**Comment by satya164** [comment]
> The [docs](https://reactnavigation.org/docs/stack-navigator/#detachpreviousscreen) say that detachPreviousScreen is set to false

It doesn't say that it's set to `false`. It says that it's automatically adjusted (to the necessary value - which would be `false` on iOS).  Unless the current behaviour is causing a bug then this doesn't seem like an issue.

**Comment by satya164** [comment]
> to keep the *required* screens visible

It keeps the screen that's *required* to stay visible like it says.

> Why should it detach previous screens for a modal

Why exactly should the screen stay visible on Android for modals?

On iOS the previous screen is visible underneath when using modal presentation style, and same for transparent modals on both platforms. What's the point of keeping it on Android when it's not even visible underneath?
