### ISSUE TITLE
Flickers while changing orientation

### ISSUE THREAD

**Issue by ankuragrawal29** [react-navigation/react-navigation#12021]
### Current behavior

* Showing white screen while changing orientation.
* The Side drawer is getting flickers from left to right while switching orientaiton

### Expected behavior

not show any of the white space without flickering

### Reproduction

https://www.npmjs.com/package/@react-navigation/drawer

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | ^6.1.17
| @react-navigation/bottom-tabs          |
| @react-navigation/drawer               |^6.6.15
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                |
| @react-navigation/native-stack         |
| react-native-safe-area-context         | ^4.10.4
| react-native-screens                   | ^3.31.1
| react-native-gesture-handler           | ^2.16.2
| react-native-reanimated                | ^3.12.0
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           | ^0.73.6
| expo                                   |
| node                                   |
| npm or yarn                            |

**Comment by nijatkazimliPG** [comment]
It still happens.
