### ISSUE TITLE
there is an additional blank space at the bottom of the screen 

### ISSUE THREAD

**Issue by one-god** [react-navigation/react-navigation#12029]
### Current behavior

When I'm using the @react-navigation/native-stack navigation library in a mixed native and React Native (RN) development environment, if I navigate from a native (non-React Native) screen to a React Native screen, there is an additional blank space or padding at the bottom of the React Native screen. However, this blank space or padding disappears when I navigate to another React Native screen and then return to the previous React Native screen.

https://github.com/react-navigation/react-navigation/assets/25094341/21323911-971c-4214-b6b8-ba20514963c4

### Expected behavior

 Hope to help me with this, thanks

### Reproduction

I'm able to reproduce this issue only in the mixed native and RN environment, and not in a pure RN project.

### Platform

- [ ] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

"@react-navigation/native": "^6.1.17",
"@react-navigation/native-stack": "^6.9.26",
 "react-native-screens": "^3.31.1",
 "react-native-reanimated": "^3.8.1",
 "react-native-gesture-handler": "^2.16.0",
 "react-native-pager-view": "^6.2.3",

**Comment by JAYBORICHA07** [comment]
@one-god did you solved it? if yes can you please share the solution

**Comment by MorganTrudeau** [comment]
This is happening to me on react-native@0.78.0. Fresh project with a simple StackNavigator and one nested DrawerNavigator. 

```
// RootStack.tsx

import React, {useContext} from 'react';
import {
  createNativeStackNavigator,
  NativeStackNavigationOptions,
} from '@react-navigation/native-stack';
import LoginScreen from '../screens/Auth/LoginScreen';
import IntroScreen from '../screens/Auth/IntroScreen';
import SignUpScreen from '../screens/Auth/SignUpScreen';
import {StackParamList} from './StackParamList';
import {theme} from '../styles/theme';
import {AuthContext} from '../context/AuthProvider';
import {DrawerNavigator} from './DrawerNavigator';
import EditCostScreen from '../screens/Main/EditCostScreen';
import ProjectScreen from '../screens/Main/ProjectScreen';
import BuildEstimateScreen from '../screens/Main/BuildEstimateScreen';

const Stack = createNativeStackNavigator<StackParamList>();

const screenOptions: NativeStackNavigationOptions = {
  headerTintColor: theme.colors.onSurface,
  headerBackButtonDisplayMode: 'minimal',
  headerStyle: {backgroundColor: theme.colors.inversePrimary},
};

const AuthStack = () => {
  return (
    <Stack.Navigator screenOptions={screenOptions}>
      <Stack.Screen
        name="intro"
        component={IntroScreen}
        options={{headerShown: false}}
      />
      <Stack.Screen
        name="login"
        component={LoginScreen}
        options={{title: 'Log In'}}
      />
      <Stack.Screen
        name="signup"
        component={SignUpScreen}
        options={{title: 'Sign Up'}}
      />
    </Stack.Navigator>
  );
};

const MainStack = () => {
  return (
    <Stack.Navigator screenOptions={screenOptions}>
      <Stack.Screen
        name="main"
        component={DrawerNavigator}
        options={{title: '', headerShown: false}}
      />
      <Stack.Screen
        name={'edit-cost'}
        component={EditCostScreen}
        options={{
          title: 'Edit Cost',
          headerTransparent: true,
        }}
      />
      <Stack.Screen
        name={'project'}
        component={ProjectScreen}
        options={{
          title: '',
          headerTransparent: true,
          headerStyle: {backgroundColor: 'transparent'},
          headerBackButtonDisplayMode: 'generic',
        }}
      />
      <Stack.Screen
        name={'build-estimate'}
        component={BuildEstimateScreen}
        options={{title: 'Estimate'}}
      />
    </Stack.Navigator>
  );
};

export const RootStack = () => {
  const {uid} = useContext(AuthContext);
  return uid ? <MainStack /> : <AuthStack />;
};
```

```
// DrawerNavigator.tsx


import {createDrawerNavigator} from '@react-navigation/drawer';
import {DrawerContent} from './DrawerContent';
import {useTheme} from 'react-native-paper';
import LogoBlack from '../assets/logo-black.svg';
import {useCallback} from 'react';

import HomeScreen from '../screens/Main/HomeScreen';
import CostsScreen from '../screens/Main/CostsScreen';
import {DrawerParamList} from './DrawerParamList';
import ProjectsScreen from '../screens/Main/ProjectsScreen';

const Drawer = createDrawerNavigator<DrawerParamList>();

export const DrawerNavigator = () => {
  const theme = useTheme();
  const LogoHeaderTitle = useCallback(() => <LogoBlack width={120} />, []);
  return (
    <Drawer.Navigator
      drawerContent={DrawerContent}
      screenOptions={{
        headerStyle: {backgroundColor: theme.colors.inversePrimary},
        headerTintColor: theme.colors.onSurface,
        drawerActiveBackgroundColor: theme.colors.inversePrimary,
        drawerLabelStyle: {color: theme.colors.onSurface},
      }}>
      <Drawer.Screen
        name="home"
        component={HomeScreen}
        options={{
          title: '',
          drawerLabel: 'Home',
          headerTitle: LogoHeaderTitle,
        }}
      />
      <Drawer.Screen
        name="projects"
        component={ProjectsScreen}
        options={{
          title: 'Projects',
          drawerLabel: 'Projects',
        }}
      />
      <Drawer.Screen
        name="costs"
        component={CostsScreen}
        options={{
          title: 'Costs',
          drawerLabel: 'Costs',
        }}
      />
    </Drawer.Navigator>
  );
};
```

**Comment by NJneeraj** [comment]
> This is happening to me on react-native@0.78.0. Fresh project with a simple StackNavigator and one nested DrawerNavigator.
> 
> ```
> // RootStack.tsx
> 
> import React, {useContext} from 'react';
> import {
>   createNativeStackNavigator,
>   NativeStackNavigationOptions,
> } from '@react-navigation/native-stack';
> import LoginScreen from '../screens/Auth/LoginScreen';
> import IntroScreen from '../screens/Auth/IntroScreen';
> import SignUpScreen from '../screens/Auth/SignUpScreen';
> import {StackParamList} from './StackParamList';
> import {theme} from '../styles/theme';
> import {AuthContext} from '../context/AuthProvider';
> import {DrawerNavigator} from './DrawerNavigator';
> import EditCostScreen from '../screens/Main/EditCostScreen';
> import ProjectScreen from '../screens/Main/ProjectScreen';
> import BuildEstimateScreen from '../screens/Main/BuildEstimateScreen';
> 
> const Stack = createNativeStackNavigator<StackParamList>();
> 
> const screenOptions: NativeStackNavigationOptions = {
>   headerTintColor: theme.colors.onSurface,
>   headerBackButtonDisplayMode: 'minimal',
>   headerStyle: {backgroundColor: theme.colors.inversePrimary},
> };
> 
> const AuthStack = () => {
>   return (
>     <Stack.Navigator screenOptions={screenOptions}>
>       <Stack.Screen
>         name="intro"
>         component={IntroScreen}
>         options={{headerShown: false}}
>       />
>       <Stack.Screen
>         name="login"
>         component={LoginScreen}
>         options={{title: 'Log In'}}
>       />
>       <Stack.Screen
>         name="signup"
>         component={SignUpScreen}
>         options={{title: 'Sign Up'}}
>       />
>     </Stack.Navigator>
>   );
> };
> 
> const MainStack = () => {
>   return (
>     <Stack.Navigator screenOptions={screenOptions}>
>       <Stack.Screen
>         name="main"
>         component={DrawerNavigator}
>         options={{title: '', headerShown: false}}
>       />
>       <Stack.Screen
>         name={'edit-cost'}
>         component={EditCostScreen}
>         options={{
>           title: 'Edit Cost',
>           headerTransparent: true,
>         }}
>       />
>       <Stack.Screen
>         name={'project'}
>         component={ProjectScreen}
>         options={{
>           title: '',
>           headerTransparent: true,
>           headerStyle: {backgroundColor: 'transparent'},
>           headerBackButtonDisplayMode: 'generic',
>         }}
>       />
>       <Stack.Screen
>         name={'build-estimate'}
>         component={BuildEstimateScreen}
>         options={{title: 'Estimate'}}
>       />
>     </Stack.Navigator>
>   );
> };
> 
> export const RootStack = () => {
>   const {uid} = useContext(AuthContext);
>   return uid ? <MainStack /> : <AuthStack />;
> };
> ```
> 
> ```
> // DrawerNavigator.tsx
> 
> 
> import {createDrawerNavigator} from '@react-navigation/drawer';
> import {DrawerContent} from './DrawerContent';
> import {useTheme} from 'react-native-paper';
> import LogoBlack from '../assets/logo-black.svg';
> import {useCallback} from 'react';
> 
> import HomeScreen from '../screens/Main/HomeScreen';
> import CostsScreen from '../screens/Main/CostsScreen';
> import {DrawerParamList} from './DrawerParamList';
> import ProjectsScreen from '../screens/Main/ProjectsScreen';
> 
> const Drawer = createDrawerNavigator<DrawerParamList>();
> 
> export const DrawerNavigator = () => {
>   const theme = useTheme();
>   const LogoHeaderTitle = useCallback(() => <LogoBlack width={120} />, []);
>   return (
>     <Drawer.Navigator
>       drawerContent={DrawerContent}
>       screenOptions={{
>         headerStyle: {backgroundColor: theme.colors.inversePrimary},
>         headerTintColor: theme.colors.onSurface,
>         drawerActiveBackgroundColor: theme.colors.inversePrimary,
>         drawerLabelStyle: {color: theme.colors.onSurface},
>       }}>
>       <Drawer.Screen
>         name="home"
>         component={HomeScreen}
>         options={{
>           title: '',
>           drawerLabel: 'Home',
>           headerTitle: LogoHeaderTitle,
>         }}
>       />
>       <Drawer.Screen
>         name="projects"
>         component={ProjectsScreen}
>         options={{
>           title: 'Projects',
>           drawerLabel: 'Projects',
>         }}
>       />
>       <Drawer.Screen
>         name="costs"
>         component={CostsScreen}
>         options={{
>           title: 'Costs',
>           drawerLabel: 'Costs',
>         }}
>       />
>     </Drawer.Navigator>
>   );
> };
> ```

Did you resolve this ? I am having the same issue.
