### ISSUE TITLE
`createStaticNavigation` type errors when defining screen options in v7

### ISSUE THREAD

**Issue by edxds** [react-navigation/react-navigation#12041]
### Current behavior

When defining screen options in the `createNativeStackNavigator` function, TypeScript throws the following error when passing the created stack to `createStaticNavigation`:
```
error TS2345: Argument of type 'TypedNavigatorInternal<ParamListBase, undefined, StackNavigationState<ParamListBase>, NativeStackNavigationOptions, NativeStackNavigationEventMap, { ...; }, ({ id, initialRouteName, children, layout, screenListeners, screenOptions, screenLayout, UNSTABLE_getStateForRouteNamesChange, ...rest }: NativeStackNavigatorPr...' is not assignable to parameter of type 'StaticNavigation<any, any, any>'.
  Property 'config' is missing in type 'TypedNavigatorInternal<ParamListBase, undefined, StackNavigationState<ParamListBase>, NativeStackNavigationOptions, NativeStackNavigationEventMap, { ...; }, ({ id, initialRouteName, children, layout, screenListeners, screenOptions, screenLayout, UNSTABLE_getStateForRouteNamesChange, ...rest }: NativeStackNavigatorPr...' but required in type 'StaticNavigation<any, any, any>'.

27 const Navigation = createStaticNavigation(RootStack);
                                             ~~~~~~~~~

  node_modules/@react-navigation/core/lib/typescript/src/StaticNavigation.d.ts:144:5
    144     config: StaticConfig<NavigatorTypeBagBase>;
            ~~~~~~
    'config' is declared here.
```

`RootStack` is defined as
```
const RootStack = createNativeStackNavigator({
  screens: {
    Hello: {
      // config: {...} is expected here?
      screen: Screen,
      options: { presentation: "modal" },
    },
    Bye: Screen,
  },
})
```
### Expected behavior

Types are accepted and inferred correctly when declaring screens with options

### Reproduction

https://github.com/edxds/react-navigation-7-repro

### Platform

- [ ] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 7.0.0-rc.2
| @react-navigation/native-stack         |7.0.0-rc.3
| react-native-safe-area-context         |4.10.1
| react-native-screens                   |3.31.1
| react-native                           |0.74.2
| expo                                   |51.0.17
| node                                   |20.10.0
| yarn                            |1.22.22
| typescript | 5.5.2

**Comment by satya164** [comment]
Should be fixed by https://github.com/react-navigation/react-navigation/commit/85c4bbbf535cde2ba9cd537a2a5ce34f060d32b9

**Comment by edxds** [comment]
Works as expected now. Thank you, @satya164!
