### ISSUE TITLE
Error running due to TypeError: (0 , use_latest_callback__WEBPACK_IMPORTED_MODULE_4__.default) is not a function

### ISSUE THREAD

**Issue by djaffer** [react-navigation/react-navigation#12056]
### Current behavior

The app is not able to run and build due to likely the latest update to the package. This has broke our production code.

https://github.com/satya164/use-latest-callback

TypeError: (0 , use_latest_callback__WEBPACK_IMPORTED_MODULE_4__.default) is not a function
    at PreventRemoveProvider (PreventRemoveProvider.js:37:1)
    at renderWithHooks (react-dom.development.js:15486:1)
    at mountIndeterminateComponent (react-dom.development.js:20103:1)
    at beginWork (react-dom.development.js:21626:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at beginWork$1 (react-dom.development.js:27490:1)
    at performUnitOfWork (react-dom.development.js:26599:1)
    at workLoopSync (react-dom.development.js:26505:1)

### Expected behavior

app should run as normal

### Reproduction

https://snack.expo.dev/@geeek/react-navigation-debug?platform=web

### Platform

- [ ] Android
- [ ] iOS
- [X] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

 "@react-navigation/drawer": "^6.6.15",
    "@react-navigation/native": "^6.1.17",
    "@react-navigation/native-stack": "^6.9.26",
    "@react-navigation/stack": "^6.3.29",
    "react-native-safe-area-context": "4.6.3",
    "react-native-screens": "~3.22.0",
    "react-native-reanimated": "~3.3.0",
    "react-native-gesture-handler": "~2.12.0"

**Comment by djaffer** [comment]
yes does exit

**Comment by lluiscab** [comment]
Same issue here: `ERROR  TypeError: 0, _useLatestCallback.default is not a function (it is undefined)`

Adding
```json
    "resolutions": {
        "use-latest-callback": "0.1.9"
    }
``` 
to `package.json` fixes the issue, which seems to have been introduced in this release https://github.com/satya164/use-latest-callback/releases/tag/v0.1.10

**Comment by lluiscab** [comment]
`use-latest-callback` has just released version `0.2.1` that might solve this issue:

https://github.com/satya164/use-latest-callback/commit/80c3cb2e01b3d6d63bae052f2376493baae6656e
https://github.com/satya164/use-latest-callback/releases/tag/v0.2.0
https://github.com/satya164/use-latest-callback/blob/HEAD/CHANGELOG.md

**Comment by grumpyoldman-io** [comment]
The v7 lib has been [correctly updated to reflect this](https://github.com/react-navigation/react-navigation/blob/main/packages/native/CHANGELOG.md#700-rc10-2024-07-10), v6 unfortunately does not yet contain this fix yet.

**Comment by satya164** [comment]
It doesn't need to be updated as it uses a semver range. You can just delete it from your lockfile and run `yarn install`/`npm install` to update it.

Or run `yarn add use-latest-callback && yarn remove use-latest-callback` or `npm install use-latest-callback && npm uninstall use-latest-callback`

**Comment by jkhaui** [comment]
> The v7 lib has been [correctly updated to reflect this](https://github.com/react-navigation/react-navigation/blob/main/packages/native/CHANGELOG.md#700-rc10-2024-07-10), v6 unfortunately does not yet contain this fix yet.

I'm confused because I'm using the v7 lib, yet the only way I can get around this error (in a production build with rollup) is by adding the following to my package.json

```
  "pnpm": {
    "overrides": {
      "use-latest-callback": "0.1.9"
    }
  }
```

So at least in my case I don't think the issue is fixed?
