### ISSUE TITLE
React native version 0.73 is bundling on every screen navigation

### ISSUE THREAD

**Issue by alam65** [react-navigation/react-navigation#12051]
### Current behavior

Recently I upgraded my React native version so after version 0.73 my screen is getting bundled on every screen navigation. I don't know if this is the new way react native works or if it's an issue in Metro or react native. Even if I'm navigating my tabs it show downloading at the top of my device. This happens in debug mode only
![photo_6079962791369884099_y](https://github.com/react-navigation/react-navigation/assets/22978276/00845deb-3cdc-4dd3-a5f8-9ba38fdd2b6d)
![photo_6334558703101000155_y](https://github.com/react-navigation/react-navigation/assets/22978276/3afbb1bf-21af-4ec8-9be8-23f450d48c3b)

### Expected behavior

The pages should not load on every page navigation 

### Reproduction
package.json
{
    "name": "vmrnbpv4",
    "version": "5.0.1",
    "private": true,
    "scripts": {
        "init": "npm run clean && npm install && npm run patch && npm run init:ios && npm run build:tw && npm run init:styles && npm run init:fonts",
        "init:win": "npm run patch && npm run init:fonts && npm run clean:win",
        "init:styles": "cd ext && npm link && vmrn ../src/styles/config/StyleMap.js -o ../src/styles/config/StyleKeys.ts ",
        "init:fonts": "npx react-native-asset",
        "android": "react-native run-android",
        "ios": "react-native run-ios",
        "ipad": "react-native run-ios --simulator='iPad Air (4th generation)'",
        "start": "react-native start",
        "start:dev": "npm run build:tw && npm run init:styles && npm run start",
        "test": "jest",
        "lint": "eslint src//*.{js, ts, tsx}",
        "init:ios": "cd ios && pod install",
        "build:tw": "tailwindcss --input input.css --output tailwind.css --no-autoprefixer && tailwind-rn",
        "clean:win": "npm run build:tw && npm run init:styles && react-native start --reset-cache",
        "clean": "watchman watch-del-all ",
        "clean:start": "npm run clean && npm run build:tw && npm run init:styles && react-native start --reset-cache",
        "prepare": "husky install",
        "vmlint": "./node_modules/.bin/eslint --ignore-path .gitignore ./src//.{js,ts,tsx}",
        "patch": "rimraf node_modules/.cache && npx @vm-lib/patch-node-modules -s node_modules_patches -o node_modules"
    },
    "dependencies": {
        "@nozbe/watermelondb": "^0.27.1",
        "@nozbe/with-observables": "^1.6.0",
        "@react-native-async-storage/async-storage": "^1.23.1",
        "@react-native-community/blur": "^4.4.0",
        "@react-native-community/datetimepicker": "^8.1.0",
        "@react-native-community/netinfo": "^11.3.2",
        "@react-native-google-signin/google-signin": "^12.2.1",
        "@react-native-masked-view/masked-view": "^0.2.8",
        "@react-native-picker/picker": "^2.7.7",
        "@react-navigation/bottom-tabs": "^6.5.20",
        "@react-navigation/native": "^6.1.17",
        "@react-navigation/stack": "^6.3.29",
        "@reduxjs/toolkit": "^2.2.5",
        "@vm-lib/patch-node-modules": "^1.0.0",
        "appcenter": "^5.0.1",
        "appcenter-analytics": "^5.0.1",
        "appcenter-crashes": "^5.0.1",
        "axios": "^1.7.2",
        "deprecated-react-native-prop-types": "^2.3.0",
        "i18next": "^23.11.5",
        "lottie-ios": "^4.4.3",
        "lottie-react-native": "^6.7.2",
        "react": "18.2.0",
        "react-i18next": "^14.1.2",
        "react-native": "0.74.2",
        "react-native-app-intro-slider": "^4.0.4",
        "react-native-base64": "^0.2.1",
        "react-native-fbsdk-next": "^13.0.0",
        "react-native-gesture-handler": "^2.16.2",
        "react-native-image-crop-picker": "^0.41.1",
        "react-native-keychain": "^8.2.0",
        "react-native-linear-gradient": "^2.8.3",
        "react-native-notifications": "^5.1.0",
        "react-native-permissions": "^4.1.5",
        "react-native-popup-menu": "^0.16.1",
        "react-native-razorpay": "^2.3.0",
        "react-native-reanimated": "^3.10.1",
        "react-native-restart": "^0.0.27",
        "react-native-safe-area-context": "^4.10.4",
        "react-native-screens": "^3.31.1",
        "react-native-size-matters": "^0.4.2",
        "react-native-skeleton-placeholder": "^5.2.4",
        "react-native-splash-screen": "^3.3.0",
        "react-native-svg": "^15.3.0",
        "react-native-svg-transformer": "^1.4.0",
        "react-native-ui-lib": "^7.23.5",
        "react-redux": "^9.1.2",
        "redux": "^5.0.1",
        "redux-persist": "^6.0.0",
        "redux-thunk": "^3.1.0",
        "simple-react-validator": "^1.6.2",
        "tailwind-rn": "^4.2.0",
        "tailwind-safelist-generator": "^1.0.0"
    },
    "devDependencies": {
        "@babel/core": "^7.20.0",
        "@babel/plugin-proposal-decorators": "^7.14.5",
        "@babel/preset-env": "^7.20.0",
        "@babel/runtime": "^7.20.0",
        "@fullhuman/postcss-purgecss": "^4.0.3",
        "@react-native/babel-preset": "0.74.84",
        "@react-native/eslint-config": "0.74.84",
        "@react-native/metro-config": "^0.74.84",
        "@react-native/typescript-config": "0.74.84",
        "@types/react": "^18.2.6",
        "@types/react-dom": "^18.0.9",
        "@types/react-native": "^0.70.7",
        "@types/react-native-base64": "^0.2.0",
        "@types/react-test-renderer": "^18.0.0",
        "autoprefixer": "^10.2.6",
        "babel-jest": "^29.6.3",
        "babel-plugin-module-resolver": "^5.0.2",
        "eslint": "^8.19.0",
        "husky": "^7.0.0",
        "jest": "^29.6.3",
        "lint-staged": "^12.1.4",
        "ncp": "^2.0.0",
        "postcss": "^8.4.7",
        "postcss-cli": "^9.1.0",
        "postcss-import": "^14.0.2",
        "prettier": "2.8.8",
        "react-test-renderer": "18.2.0",
        "tailwindcss": "^3.4.3",
        "typescript": "^5.0.4"
    },
    "engines": {
        "node": ">=18"
    },
    "packageManager": "yarn@3.6.4",
    "lint-staged": {
        "src/**/.{js,ts,tsx}": [
            "./node_modules/.bin/eslint --ignore-path .gitignore",
            "prettier --write"
        ]
    }

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |
| @react-navigation/bottom-tabs          |
| @react-navigation/stack                |
| @react-navigation/native-stack         |
| react-native-safe-area-context         |
| react-native-screens                   |
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native                           |
| node                                   |
| npm or yarn                            |

**Comment by alam65** [comment]
> The versions mentioned in the issue for the following packages differ from the latest versions on npm:
> 
> * `@react-navigation/bottom-tabs` (found: `6.5.20`, latest: `6.6.0`)
> * `@react-navigation/stack` (found: `6.3.29`, latest: `6.4.0`)
> 
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?

Yes i have tried to upgarde and check but still the issue is same

**Comment by alam65** [comment]
@raajnadar can you reopen the issue i have still not got the solution

**Comment by raajnadar** [comment]
This does not look like a problem from react-navigation, if you think this is an issue you need to add a runnable reproducer instead of pasting a package.json.

Also, do your research before opening an issue ticket.

**Comment by shubhamguptadream11** [comment]
@alam65 Are you still facing this issue? If no, how did you fixed this?
