### ISSUE TITLE
React Navigation 7: Not resolving cjs files -> "error: Error: Unable to resolve module ./views/NativeStackView from */node_modules/@react-navigation/native-stack/lib/commonjs/index.cjs:"

### ISSUE THREAD

**Issue by JeffreyVanelderenACA** [react-navigation/react-navigation#12059]
### Current behavior

On a new empty, bare React Native 0.74.2 project: Doing the React Navigation setup as stated in the docs results in a run time error by the Resolver for CJS files.

```
> Task :app:installDebug
Installing APK 'app-debug.apk' on 'Pixel_6_Pro_API_32(AVD) - 12' for :app:debug
Installed on 1 device.

BUILD SUCCESSFUL in 5s
93 actionable tasks: 14 executed, 79 up-to-date
info Connecting to the development server...
info Starting the app on "emulator-5554"...
Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=***.MainActivity }
 BUNDLE  ./index.js 

error: Error: Unable to resolve module ./views/NativeStackView from /Users/jeffreyvanelderen/Documents/repos/***/node_modules/@react-navigation/native-stack/lib/commonjs/index.cjs: 

None of these files exist:
  * node_modules/@react-navigation/native-stack/lib/commonjs/views/NativeStackView(.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  * node_modules/@react-navigation/native-stack/lib/commonjs/views/NativeStackView/index(.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  23 | });
  24 | var _createNativeStackNavigator = require("./navigators/createNativeStackNavigator.cjs");
> 25 | var _NativeStackView = require("./views/NativeStackView");
     |                                 ^
  26 | var _useAnimatedHeaderHeight = require("./utils/useAnimatedHeaderHeight.cjs");
```

### Expected behavior

Add step in docs or fix resolving the cjs files in the module

### Reproduction

~

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

| Dependency                           | Version         |
|--------------------------------------|-----------------|
| **Dependencies**                     |                 |
| @react-navigation/bottom-tabs        | ^7.0.0-rc.18    |
| @react-navigation/native             | ^7.0.0-rc.11    |
| @react-navigation/native-stack       | ^7.0.0-rc.13    |
| babel-plugin-module-resolver         | ^5.0.2          |
| patch-package                        | ^8.0.0          |
| react                                | 18.2.0          |
| react-native                         | 0.74.2          |
| react-native-safe-area-context       | ^4.10.8         |
| react-native-screens                 | ^3.32.0         |
| **Dev Dependencies**                 |                 |
| @babel/core                          | ^7.20.0         |
| @babel/preset-env                    | ^7.20.0         |
| @babel/runtime                       | ^7.20.0         |
| @react-native/babel-preset           | 0.74.84         |
| @react-native/eslint-config          | 0.74.84         |
| @react-native/metro-config           | 0.74.84         |
| @react-native/typescript-config      | 0.74.84         |
| @types/react                         | ^18.2.6         |
| @types/react-test-renderer           | ^18.0.0         |
| babel-jest                           | ^29.6.3         |
| eslint                               | ^8.19.0         |
| jest                                 | ^29.6.3         |
| prettier                             | 2.8.8           |
| react-test-renderer                  | 18.2.0          |
| typescript                           | 5.0.4           |

## The fix I found

Update your `metro.config.js` to resolve the .cjs files:

```
const {getDefaultConfig, mergeConfig} = require('@react-native/metro-config');

/**
 * @type {import("metro-config").MetroConfig}
 */
const DEFAULT_CONFIG = getDefaultConfig(__dirname);

/**
 * Metro configuration
 * https://reactnative.dev/docs/metro
 *
 * @type {import("metro-config").MetroConfig}
 */
const config = {
  resolver: {
    sourceExts: [...DEFAULT_CONFIG.resolver.sourceExts, 'cjs'],
  },
};

module.exports = mergeConfig(DEFAULT_CONFIG, config);

```

**Comment by satya164** [comment]
The latest RC no longer uses `.cjs` extensions. So it should work without configuration now.
