### ISSUE TITLE
Unexpected behavior: headerShadow unexpectedly visible 

### ISSUE THREAD

**Issue by Softkeydel** [react-navigation/react-navigation#12063]
### Current behavior

Header shadow visible unexpectedly

https://github.com/user-attachments/assets/2edb6e0e-3520-4b80-b765-6db9b961456b

Already tried with most updated versions of the libraries mentioned 

### Expected behavior

Header shadow should not visible 

https://github.com/user-attachments/assets/bd561646-a000-498b-bc31-9c86a9ba257c

### Reproduction

https://github.com/Softkeydel/Reproduce

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.1.17
| @react-navigation/drawer               | 6.7.0
| @react-navigation/native-stack         | 6.10.0
| react-native-safe-area-context         | 4.10.8
| react-native-screens                   | 3.32.0
| react-native-gesture-handler           | 2.16.2
| react-native-reanimated                | 3.10.1
| react-native                           | 0.72.15
| react                                   | 18.2.0
| node                                   | 20.15.1
| npm                           | 10.7.0

**Comment by Softkeydel** [comment]
GitHub repo added pls check

**Comment by Nonag** [comment]
I have the same issue on a screen with a transparent header.

When first adding the screen to the stack, the header is presented as expected. But as soon as you add another screen on top and then navigate back to the screen with the transparent header, the shadow was added.

**Comment by Softkeydel** [comment]
@Nonag any solution??

**Comment by edritech93** [comment]
same issue for me, any solution ?

**Comment by ngondat97** [comment]
same issue

**Comment by santiagomariani-tiendanube** [comment]
same issue

**Comment by wangchongwei** [comment]
same issue

**Comment by sakarzac000** [comment]
Same as well. It's worth noting that I wasn't having this issue before using Fabric, but switching to the new arch made it show up.

**Comment by vantienvnn** [comment]
I had the same problem, but it went away after I updated React Native from 0.73 to 0.74.
![Photo](https://github.com/user-attachments/assets/8a4ff947-ef3b-4752-adb4-ed623b815706)

**Comment by spo-mmorales** [comment]
same issue

**Comment by MuckT** [comment]
Updating to [react-native-screens@3.33.0](https://github.com/software-mansion/react-native-screens/releases/tag/3.33.0) fixes the issue. Related PR: https://github.com/software-mansion/react-native-screens/pull/2216.

**Comment by balkrishna-1996** [comment]
same issue i am also facing once i am updating the react-native-screen it is effecting on others and not able to build the app.
