### ISSUE TITLE
headerBlurEffect does not work in nested navigators

### ISSUE THREAD

**Issue by kahx** [react-navigation/react-navigation#12066]
### Current behavior

I have nested navigators. When I apply headerBlurEffect and headerTransparent to the child navigator, it doesn't work. Works when I apply it to the parent navigator. The same result occurs when I apply it to the Stack.Navigator.

Child navigator

```
<Stack.Navigator
      screenOptions={{
        headerStyle: {
          backgroundColor: '#f2f2f2',
        },
        headerTintColor: 'black',
        headerTitleStyle: {
          fontFamily: 'Lato-Bold',
          fontSize: ms(18, 0.2),
        },
      }}
    >
      <Stack.Screen
        name="Drawer"
        component={Drawer}
        options={{ headerShown: false, animation: 'slide_from_right', orientation: 'portrait' }}
      />
      <Stack.Screen
        name="Screen1"
        component={Screen1}
        options={{
          title: Screen1',
          headerBlurEffect: 'regular',
          headerTransparent: true,
        }}
      />
...
```

### Expected behavior

The expected result is for the blur effect to be applied to the header of the child navigator.

### Reproduction

https://snack.expo.dev/nkbpufXRy9L7oImyqPIgK?platform=ios

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native              | 6.0.8
| @react-navigation/drawer               | 6.4.3
| @react-navigation/native-stack         | 6.7.0
| react-native-safe-area-context         | 4.5.1
| react-native-screens                   | 3.19.0
| react-native-gesture-handler           | 2.9.0
| react-native-reanimated                | 2.14.1
| react-native-pager-view                | 6.2.0
| react-native                           | 0.71.0
| expo                                   | 47.0.0
| node                                   | 18.18.2
| npm or yarn                            | 9.8.1

**Comment by satya164** [comment]
> The expected result is for the blur effect to be applied to the header of the child navigator.

That's not how options work. Each navigator has its own options and it doesn't affect child or parent navigators.

https://reactnavigation.org/docs/nesting-navigators/#each-navigator-has-its-own-options

The `headerBlurEffect` option is only supported in native stack, not in bottom tabs. However you can use a `BlurView` in `headerBackground` https://reactnavigation.org/docs/elements#headerbackground

**Comment by kahx** [comment]
> > The expected result is for the blur effect to be applied to the header of the child navigator.
> 
> That's not how options work. Each navigator has its own options and it doesn't affect child or parent navigators.
> 
> https://reactnavigation.org/docs/nesting-navigators/#each-navigator-has-its-own-options
> 
> The `headerBlurEffect` option is only supported in native stack, not in bottom tabs. However you can use a `BlurView` in `headerBackground` https://reactnavigation.org/docs/elements#headerbackground

I know how the options work. What I mean is that the blur effect doesn't work when applied to the child navigator. If I set the parent navigator's headerShown property to true and give the same properties to its options, I can see that the blur effect works. I am already using native-stack.

**Comment by satya164** [comment]
> the blur effect doesn't work when applied to the child navigator

As I mentioned 

> The headerBlurEffect option is only supported in native stack, not in bottom tabs
