### ISSUE TITLE
 Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by wjg55555** [react-navigation/react-navigation#12064]
### Current behavior

run programes

### Expected behavior

success

### Reproduction

/**  * Sample React Native App  * https://github.com/facebook/react-native  *  * @format  */ import React from "react"; import { Text, Button } from "react-native"; import { Drawer } from "react-native-drawer-layout";  export default function App() {   const [open, setOpen] = React.useState(false);   return (     <Drawer       open={open}       onOpen={() => setOpen(true)}       onClose={() => setOpen(false)}       renderDrawerContent={() => {         return <Text>Drawer content</Text>;       }}     >       <Button onPress={() => setOpen(prevOpen => !prevOpen)} title={`${open ? "Close" : "Open"} drawer`} />     </Drawer>   ); }

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |
| @react-navigation/bottom-tabs          |
| @react-navigation/drawer               |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                |
| @react-navigation/native-stack         |
| react-native-safe-area-context         |
| react-native-screens                   |
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           |
| expo                                   |
| node                                   |
| npm or yarn                            |
react-native-drawer-layout

**Comment by wjg55555** [comment]
{
  "name": "app_chinese_course",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "dev": "react-native run-android",
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "lint": "eslint .",
    "start": "react-native start",
    "test": "jest",
    "recache": "react-native start --reset-cache"
  },
  "dependencies": {
    "@jamsch/react-native-hanzi-writer": "^0.3.1",
    "@react-native-async-storage/async-storage": "^1.23.1",
    "@react-navigation/bottom-tabs": "^6.5.20",
    "@react-navigation/native": "^6.1.17",
    "@react-navigation/stack": "^6.3.29",
    "@reduxjs/toolkit": "^2.2.3",
    "@splicer97/react-native-switch": "^1.0.0",
    "axios": "^1.6.8",
    "i18next": "^23.11.2",
    "lottie-react-native": "^6.7.2",
    "moment": "^2.30.1",
    "qs": "^6.12.1",
    "react": "18.2.0",
    "react-i18next": "^14.1.1",
    "react-native": "0.73.7",
    "react-native-audio-recorder-player": "^3.6.7",
    "react-native-calendars": "^1.1304.1",
    "react-native-drawer-layout": "^3.3.1",
    "react-native-fs": "^2.20.0",
    "react-native-gesture-handler": "^2.17.1",
    "react-native-linear-gradient": "^2.8.3",
    "react-native-modal": "^13.0.1",
    "react-native-progress": "^5.0.1",
    "react-native-reanimated": "^3.14.0",
    "react-native-safe-area-context": "^4.10.1",
    "react-native-screens": "^3.31.1",
    "react-native-splash-screen": "^3.3.0",
    "react-native-storage": "^1.0.1",
    "react-native-svg": "^13.4.0",
    "react-native-video": "^5.2.1",
    "react-redux": "^9.1.1"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/preset-env": "^7.20.0",
    "@babel/runtime": "^7.20.0",
    "@react-native/babel-preset": "0.73.21",
    "@react-native/eslint-config": "0.73.2",
    "@react-native/metro-config": "0.73.5",
    "@react-native/typescript-config": "0.73.1",
    "babel-jest": "^29.6.3",
    "eslint": "^8.19.0",
    "eslint-plugin-react": "^7.34.1",
    "jest": "^29.6.3",
    "prettier": "2.8.8",
    "react-native-devsettings": "^1.0.5",
    "react-test-renderer": "18.2.0"
  },
  "engines": {
    "node": ">=18"
  }
}

**Comment by wjg55555** [comment]
The current error occurs only when the debugger is running

**Comment by wjg55555** [comment]
There's nothing wrong with not hitting the debugger

**Comment by wjg55555** [comment]
@netshade @natew @ddedic @renchap

**Comment by wjg55555** [comment]
![Uploading QQ截图20240705144536.jpg…]()

**Comment by wjg55555** [comment]
![QQ截图20240705144536](https://github.com/user-attachments/assets/a8bf5736-8508-4fad-a744-28315397a733)

**Comment by wjg55555** [comment]
![微信图片_20240715105035](https://github.com/user-attachments/assets/7cc836dd-32be-4669-847b-efaa6b99045a)

**Comment by satya164** [comment]
Use Chrome Devtools with Hermes instead https://reactnative.dev/docs/hermes#debugging-js-on-hermes-using-google-chromes-devtools

Chrome debugger doesn't work well with reanimated.

**Comment by TonyFTannous-Byd** [comment]
i need debug my network request, and Use Chrome Devtools with Hermes didn't provide network
what is the solution (i user react native 0.75.1)
