### ISSUE TITLE
Passing a React Component (without wrapping it in a function) to `header` and `headerLeft` makes any `useNavigation` call in the custom headerLeft component return the wrong navigator

### ISSUE THREAD

**Issue by tran-simon** [react-navigation/react-navigation#12076]
### Current behavior

Inside a custom `Header` component, if I try to render the `headerLeft` from `options` by calling it as a normal function, `useNavigation` inside the `headerLeft` returns the wrong navigator.

`navigation.goBack()` goes back in the navigator parent to `MyNavigator`.

```typescript
const Header = ({
  navigation,
  options: { headerLeft = HeaderLeft, headerTintColor, headerBackTitle },
}: NativeStackHeaderProps) => {
  return (
    <View>
      {headerLeft({
        canGoBack: navigation.canGoBack(),
        tintColor: headerTintColor,
        label: headerBackTitle,
      })}
    </View>
  );
};

const HeaderLeft = (props: HeaderBackButtonProps) => {
  const navigation = useNavigation();

  return <Button title={'back'} onPress={() => navigation.goBack()} />;
};

const MyNavigator = createNativeStackNavigator();

const App = () => {
  return (
    <MyNavigator.Navigator
      screenOptions={{
        header: Header,
      }}
    >
      <MyNavigator.Screen name={'Test'} component={() => null} />
    </MyNavigator.Navigator>
  );
};

```

---

I believe the issue is caused by calling the `headerLeft` as a function instead of rendering it as a React Component

https://kentcdodds.com/blog/dont-call-a-react-function-component

> But the hooks that are in Counter [HeaderLeft] will be associated with the App component instance, because there is no Counter component instance. 

What is the proper way of fixing this?

### Expected behavior

If I modify my `Header` component like so, pressing the button properly goes back in `MyNavigator`, but I get type errors:

```
return (
    <View>
      <HeaderLeft {...{
        canGoBack: navigation.canGoBack(),
        tintColor: headerTintColor,
        label: headerBackTitle,
      }} />
    </View>
  );
```

### Reproduction

https://snack.expo.dev/@simon.tran/react-navigation-bug

To reproduce:

1. Press "Go to screen2"
2. Press "Go to test2"

- Pressing "RootNavigator back" navigates back in RootNavigator (Back to "screen1")
- Pressing "MyNavigator back" navigates back in "MyNavigator" (Back to "screen1>test")

### Platform

- [X] Android
- [X] iOS
- [X] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.1.9
| @react-navigation/native-stack         | 6.1.9
| react-native-safe-area-context         | 4.4.1
| react-native-screens                   | 3.31.1
| react-native                           | 0.71.19
| node                                   | 20.12.2
| npm                          | 10.5.0

**Comment by satya164** [comment]
`header` or `headerLeft` don't accept components. They accept render functions.

This is not the correct syntax to pass them:

```js
header: Header,
headerLeft: HeaderLeft,
```

This is the correct syntax:

```js
header: props => <Header {...props} />,
headerLeft: props => <HeaderLeft {...props} />,
```

https://reactnavigation.org/docs/elements#header

**Comment by Jackman3005** [comment]
I also am running into this when upgrading to v7. I was passing components directly and even sometimes doing inline components which used hooks which are now failing everywhere throughout...

Not sure why it can't be a component in v7 as it was working fine in v6...
