### ISSUE TITLE
Navigation 7 - Static - ts type interference breaks if add `screenOptions.animationTypeForReplace`

### ISSUE THREAD

**Issue by sync** [react-navigation/react-navigation#12071]
### Current behavior

```
const RootStack = createNativeStackNavigator({
  screens: {
    Home: {
      screen: HomeScreen,
      options: {
        title: "Just wow",
      },
    },
    Details: {
      screen: DetailsScreen,
      options: {
        headerStyle: { backgroundColor: "purple" },
      },
    },
  },
  screenOptions: {
    animationTypeForReplace: "pop",
  },
});

const Navigation = createStaticNavigation(RootStack);

type RootStackParamList = StaticParamList<typeof RootStack>;

declare global {
  namespace ReactNavigation {
    interface RootParamList extends RootStackParamList {}
  }
}
```

<img width="644" alt="Screenshot 2024-07-24 at 6 04 55 PM" src="https://github.com/user-attachments/assets/540efd5f-e0ac-4b31-a9b6-26168e2895ed">

<img width="1457" alt="Screenshot 2024-07-24 at 6 13 20 PM" src="https://github.com/user-attachments/assets/891bc1a9-aece-4251-a759-43673738633d">

If i commented out: `animationTypeForReplace: "pop",` typescript is no longer unhappy.

### Expected behavior

<img width="680" alt="Screenshot 2024-07-24 at 6 05 09 PM" src="https://github.com/user-attachments/assets/b05e5563-b4c0-45f2-9604-1a9fc6eb7ce6">

### Reproduction

https://github.com/sync/navilost

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 7.0.0-rc.14
| @react-navigation/native-stack              | 7.0.0-rc.14
| react-native-safe-area-context         | 4.10.5
| react-native-screens                   | 3.31.1
| react-native                           | 0.74.3
| expo                                   | 51.0.22
| node                                   | 18.19.1
| yarn                            | 1.22.22

**Comment by sync** [comment]
I know using latest 7 rc

**Comment by migueldaipre** [comment]
Same issue here
