### ISSUE TITLE
Header height - Can't change the height of the header

### ISSUE THREAD

**Issue by mo92othman** [react-navigation/react-navigation#12087]
### Current behavior

I am working on a react native project, using Expo router, to work on the header/ or topNavBar.

in the `<Stack.Screen  name="usage"  options={usageHeader} `

there are different ways to set the header, either a custom component for the whole header, by using `header `, or using the navigation feature and then using of `headerTitle  `and `headerLeft  `and `headerRight`. I am using the second approch because I don't have to worry about safe areas an so on. However, the issue is that I couldn't find a way to increase the height of the header.

headerStyle only accepts backgroundColor.

Is there a solution for this, or am I missing something? I found an issue about this on gitHub, but i didn't see any solution apart from using a header and defining a whole custom component.

https://github.com/react-navigation/react-navigation/issues/10097

`headerStyle: { backgroundColor: '#E9FDFF', height: 100, // not doing anything marginTop: 100, // not doing anything paddingTop: 100, // not doing anything },`

### Expected behavior

`headerStyle: { height: 100 },  `

I expect this to change the header height

### Reproduction

p

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [1] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |^5.0.0
| react-native-safe-area-context        |^4.10.1 
| react-native-screens                   |^3.31.1
| react-native-gesture-handler           |~2.16.1
| react-native-reanimated                | ~3.10.1
| react-native                       |  0.74.2  
| expo                                  | ~51.0.14
| node                         |v20.15.1          
| npm or yarn                  | v1.22.22

**Comment by satya164** [comment]
Native Stack uses the native header provided by the system which has specific styling. If you want to change the height then you need to use a custom header.
