### ISSUE TITLE
Web: Cards are absoluteFilled which breaks the render for long content on web

### ISSUE THREAD

**Issue by mabounassif** [react-navigation/react-navigation#12084]
### Current behavior

Given a website that has a navigation stack with a header and footer.
When the screen's content exceeds display height
Then the header and footer are absolute and only the content scrolls.

[Code affecting behavior @ packages/stack/src/views/Stack/CardStack.tsx#L667](https://github.com/react-navigation/react-navigation/blob/%40react-navigation/stack%406.4.1/packages/stack/src/views/Stack/CardStack.tsx#L667)

**Current solution:** embed same Header & Footer in all of the Screens

### Expected behavior

Given a website that has a navigation stack with a header and footer.
When the screen's content exceeds display height
Then the header and footer are relative and the scrolling moves header, content and footer together.

### Reproduction

https://snack.expo.dev/@foodsmarts/shallow-indigo-ramen

### Platform

- [ ] Android
- [ ] iOS
- [X] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |  6.1.18
| @react-navigation/stack                | 6.4.1
| react-native-screens                   | 3.31.1

**Comment by satya164** [comment]
Stack can contain multiple screens, so it's quite tricky to have a single footer that scrolls with content of each screen.

Instead you can put the footer in each screen itself. React Navigation 7 exposes a `screenLayout` prop that makes it easy.

```js
<Stack.Navigator screenLayout={({ children }) => <>{children}<Footer /></> }>
  <Stack.Screen name="Dashboard" component={Component} />
</Stack.Navigator>
```

**Comment by mabounassif** [comment]
One last point. 

In the case of a nested navigator, the screen layout doesn't seem to be passed down. So the screen layout only applies to the shallow screens.

Is there a work around?
