### ISSUE TITLE
Swipe Back Gesture Not Dismissing Keyboard Properly on IOS

### ISSUE THREAD

**Issue by FilipiRafael** [react-navigation/react-navigation#12092]
### Current behavior

When performing a swipe-back gesture to navigate to a previous screen, the keyboard sometimes remains open even though the beforeRemove event is triggered.

### How it's working:

https://github.com/user-attachments/assets/73655d28-efdb-40c3-b4ef-cf2ebfdae2ac

### Steps to Reproduce:

1. Open a screen with an active text input field.
2. Initiate a swipe-back gesture to navigate to the previous screen.
3. Observe that the keyboard does not always dismiss immediately and remains open.

Despite trying various methods, including custom hooks and the latest Gesture API, the issue of consistently dismissing the keyboard during swipe-back gestures persists. Attempts to use the beforeRemove event with multiple setTimeout calls and the updated gesture handling methods have not resolved the issue. The keyboard sometimes remains open partially, making us suspect that the problem might be related to React Navigation or iOS gesture handling.

Also, this started happening after upgrading the react native to the latest version. 

### Expected behavior

The keyboard should be dismissed consistently when initiating a swipe back gesture or when navigating away from the screen.

### Reproduction

google.com

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

"@react-navigation/bottom-tabs": "^6.x",
"@react-navigation/native": "^6.x",
"@react-navigation/stack": "^6.x",

**Comment by trantuandatvietnam** [comment]
I have the same problem
