### ISSUE TITLE
[iOS] - Black Screen when navigation to fullScreenModal

### ISSUE THREAD

**Issue by ianvasco** [react-navigation/react-navigation#12091]
### Current behavior

Suddenly started to get issues with a random black screen, it appeared randomly when navigating to a "fullScreenModal", it was reproducible when navigating multiple times or repeatedly between modals, some times it was at the very first attempt.

This is only happening on iOS devices

https://github.com/user-attachments/assets/5644ac5f-0338-4a06-acb4-85250d22db02

With further investigation, I reached this Thread https://forums.developer.apple.com/forums/thread/28828 where is explaining the same issue with native iOS. Taking a look at the react-navigation docs I saw that "fullScreenModal" translates to UIModalPresentationFullScreen and decided to use "containedModal" option, and it's working fine now.

### Expected behavior

"fullScreenModal" presentation should be working without a black screen.

### Reproduction

https://nonreproducible

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

    "react-native": "0.73.1",
    "@react-navigation/elements": "^1.3.18",
    "@react-navigation/native": "^6.1.6",
    "@react-navigation/native-stack": "^6.9.13",
    "@react-navigation/stack": "^6.3.16",

Simulator: iPhone 15 Pro - iOS 17.0
XCode: 15.0.1

**Comment by teojiesern** [comment]
I have a similar issue but have found some pattern as to when will this happen, whenever I change any of the header options (for fullScreenModal screens), whether by declaring them directly in the options prop or by using setOptions, I get an error, and highly suspect that this error is causing the screen to turn black. If I don't modify the header options at all, the screen works perfectly fine.

```
// Using options prop
<Stack.Screen
  name="MyScreen"
  component={MyScreenComponent}
  options={{
        headerLeft: ({ canGoBack }) => <CustomCloseButton canGoBack={canGoBack} />,
        presentation: 'fullScreenModal',
    }}
/>

// Using setOptions
useLayoutEffect(() => {
  navigation.setOptions({ headerLeft: ({ canGoBack }) => <CustomCloseButton canGoBack={canGoBack} /> });
}, []);

```

| package             | version         |
| --------------- | --------------- |
| react-navigation/native   | 6.1.18 |
| react-navigation/native-stack | 6.11.0 |
| react-native | 0.74.5 |

![View recent photos](https://github.com/user-attachments/assets/02da924f-d294-48b2-b25d-132cd29cd575)

**Comment by jb-** [comment]
Same here
- react-native: 0.72.8
- @react-navigation/native: 6.0.11 (same on 6.1.18)
- @react-navigation/native-stack: 6.7.0 (same on 6.11.0)

**Comment by unamed000** [comment]
Having the same issue:
"@react-navigation/native": "6.1.18",
"@react-navigation/native-stack": "6.11.0",
"react-native-screens": "3.34.0",

**Comment by SRandazzo** [comment]
We were experiencing the same issue and we're able to resolve it with @ianvasco's suggestion of changing `fullScreenModal` ->  `containedModal` 

"react-native": "0.75.4"
"@react-navigation/native": "^6.1.18",
"@react-navigation/native-stack": "^6.11.0",

**Comment by johankasperi** [comment]
I am seeing this as well:
```
    "@react-navigation/core": "6.4.17",
    "@react-navigation/native": "6.1.18",
    "@react-navigation/native-stack": "6.11.0",
    "react-native": "0.75.2",
```

**Comment by chrisbianca** [comment]
I can confirm that updating `react-native-screens` to 3.35.0 has fixed the issue for me too

**Comment by OrkhanAlikhanov** [comment]
Thank you guys for suggesting to upgrade `react-native-screens` to version 3.35.0. I was not only experiencing random black screens but also UI was not rendering the state properly usually.
