### ISSUE TITLE
Drawer Peeks Out From Behind Modal When Right Positioned

### ISSUE THREAD

**Issue by salieflewis** [react-navigation/react-navigation#12109]
### Current behavior

Following the [how-to-router](https://github.com/kadikraman/how-to-router/tree/main/drawer-and-tabs) drawer structure. There is an issue where if a tab has a stack navigator that includes a modal that is presented as such, the drawer peeks out from beneath the stack when opening and closing that modal.

https://github.com/user-attachments/assets/29a85fec-6325-4a33-b1ae-bed27ab9ed93

### Expected behavior

The drawer should not be visible at all.

### Reproduction

https://github.com/salieflewis/how-to-router/tree/main/drawer-and-tabs

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

```
  "dependencies": {
    "@expo/vector-icons": "^14.0.0",
    "@react-navigation/drawer": "^6.6.15",
    "@react-navigation/native": "^6.0.2",
    "expo": "~50.0.14",
    "expo-font": "~11.10.3",
    "expo-linking": "~6.2.2",
    "expo-router": "~3.4.8",
    "expo-splash-screen": "~0.26.4",
    "expo-status-bar": "~1.11.1",
    "expo-system-ui": "~2.9.3",
    "expo-web-browser": "~12.8.2",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.73.6",
    "react-native-gesture-handler": "~2.14.0",
    "react-native-reanimated": "~3.6.2",
    "react-native-safe-area-context": "4.8.2",
    "react-native-screens": "~3.29.0",
    "react-native-web": "~0.19.6"
  },
  ```

**Comment by salieflewis** [comment]
> The versions mentioned in the issue for the following packages differ from the latest versions on npm:
> 
> * `@react-navigation/drawer` (found: `6.6.15`, latest: `6.7.2`)
> * `@react-navigation/native` (found: `6.0.2`, latest: `6.1.18`)
> 
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?

Yes, the issue persists

**Comment by erwannbst** [comment]
The issue is not resolved

**Comment by laurienicholas** [comment]
Commenting for visibility as this ticket is showing up on Google.

I had this issue, and to further compound it, certain navigation events would leave the drawer half peeked out even once the modal was closed.

In my case the issue was that I was setting the drawer width to 80% to allow for wider content

My solution was to set the width explicitly using the `Dimensions` constants instead:

```tsx
<Drawer
        screenOptions={{
          drawerStyle: {
//          width: "80%",
            width: Dimensions.get("window").width * 0.8,
          },
      >
```
