### ISSUE TITLE
react_native__WEBPACK_IMPORTED_MODULE_1__.default.getViewManagerConfig is not a function

### ISSUE THREAD

**Issue by yyuunn922** [react-navigation/react-navigation#12103]

**Comment by satya164** [comment]
Your webpack config is incorrect. It shouldn't be loading `.android.js` or `.ios.js` on web which is a completely different platform. This is unrelated to React Navigation.

**Comment by yyuunn922** [comment]
> Your webpack config is incorrect. It shouldn't be loading `.android.js` or `.ios.js` on web which is a completely different platform. This is unrelated to React Navigation.

sorry, i dont understand, can you explain little more? i think there is not .android or .ios in my webpack,

you mean is, must delete extension tap in webpack.config.js?

i love react-navigation lib, but can't use because this error.... can you help me little bit?

**Comment by satya164** [comment]
https://github.com/yyuunn922/react-native-web-webpack/blob/19adacaffb5e8a17bb08fa8324d8cf1b1728ca9a/web/webpack.config.js#L75-L82
