### ISSUE TITLE
React Native Tab View & Material Top Tabs are broken in RTL Language 

### ISSUE THREAD

**Issue by hasanal95** [react-navigation/react-navigation#12101]
### Current behavior

there are 2 issues when App is RTL direction in the latest version "3.5.2":

1. swipe direction is inverted on Android.
2. indicator wrong position and disappearing issues on both platforms, this behavior happens when direction is RTL and scroll enabled.

Please note that this behavior was not exist in version 2.16m every thing was well.

my sample code:
```
import { useState } from "react";
import { Button, I18nManager, View, useWindowDimensions } from "react-native";
import { TabView, SceneMap, TabBar } from "react-native-tab-view";
import RNRestart from "react-native-restart";

const Route1 = () => <View style={{ flex: 1, backgroundColor: "#ff4081" }} />;
const Route2 = () => <View style={{ flex: 1, backgroundColor: "#673ab7" }} />;
const Route3 = () => <View style={{ flex: 1, backgroundColor: "#173ab8" }} />;
const Route4 = () => <View style={{ flex: 1, backgroundColor: "#373ab8" }} />;
const Route5 = () => <View style={{ flex: 1, backgroundColor: "#773ab8" }} />;
const Route6 = () => <View style={{ flex: 1, backgroundColor: "#A73ab8" }} />;
const Route7 = () => <View style={{ flex: 1, backgroundColor: "#D73ab8" }} />;

const renderScene = SceneMap({
  route1: Route1,
  route2: Route2,
  route3: Route3,
  route4: Route4,
  route5: Route5,
  route6: Route6,
  route7: Route7,
});

const routes = [
  { key: "route1", title: "Route1" },
  { key: "route2", title: "Route2" },
  { key: "route3", title: "Route3" },
  { key: "route4", title: "Route4" },
  { key: "route5", title: "Route5" },
  { key: "route6", title: "Route6" },
  { key: "route7", title: "Route7" },
];

export default function TabViewExample() {
  const layout = useWindowDimensions();
  const [index, setIndex] = useState(0);

  return (
    <View style={{ flex: 1, paddingTop: 50, paddingBottom: 50 }}>
      <TabView
        renderTabBar={(props) => <TabBar scrollEnabled {...props} />}
        style={{ flex: 1 }}
        navigationState={{ index, routes }}
        renderScene={renderScene}
        onIndexChange={setIndex}
        initialLayout={{ width: layout.width }}
      />
      <Button
        onPress={() => {
          try {
            I18nManager.allowRTL(true);
            I18nManager.forceRTL(true);
            setTimeout(() => {
              console.log('AAA')
              RNRestart.restart();
            }, 500);
          } catch (error) {
            console.log("ERROR: ", error);
          }
        }}
        title="change language"
      />
    </View>
  );
}

```

my package.json:
```
{
  "name": "my-app",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "expo": "~50.0.17",
    "expo-status-bar": "~1.11.1",
    "react": "18.2.0",
    "react-native": "0.73.6",
    "react-native-pager-view": "6.2.3",
    "react-native-restart": "^0.0.27",
    "react-native-tab-view": "^3.5.2"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0"
  },
  "private": true
}
```

### Expected behavior

The expected behavior is working well with RTL just like 2.16 version.

### Reproduction

https://github.com/hasanal95/tabs-RTL-issue-demo/tree/main

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [X] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| react-native-tab-view                  |3.5.2
| react-native-pager-view                |6.2.3
| react-native                          | 0.73.6
| expo                                   |50.0.0
| node                                   |22.0.0
| yarn                            |1.22.22

**Comment by hasanal95** [comment]
> Couldn't find version numbers for the following packages in the issue:
> 
> * `@react-navigation/native`
> 
> Can you update the issue to include version numbers for those packages? The version numbers must match the format 1.2.3.

I have no this library in my example

**Comment by moedeveloper** [comment]
I have the same issue on IOS, i have being trying for 3 days now and created a new custom tab bars but still the same issue!! I cant figure it out actually :(

**Comment by hasanal95** [comment]
i resolved the issue, check this article: https://medium.com/@halawneh595/tackling-rtl-issues-in-react-native-73-0-0-30fa81ea49ce
