### ISSUE TITLE
[react-native-tab-view] wrong initial tab index

### ISSUE THREAD

**Issue by rawnney** [react-navigation/react-navigation#12111]
### Current behavior

I experience issues with wrong `tabBarItem` being focused when wrapping the `TabView` with margins or padding.

I'm trying to initially render scene B. So i set the `initialIndex` to 1. But even so the `tabBarItem` is still focusing the wrong item (index 0). This is randomly occurring (see video)

For some reason adding margins or padding to the TabView, or having it wrapped, seemingly causes this issue.

https://github.com/user-attachments/assets/4abb7b81-4972-4021-aafb-d64e39c21b47

### Expected behavior

I would expect having a styled wrapper for the TabView and to be able to have an initial index > 0 which correspond to the correct tabBarItem focus.

### Reproduction

[link](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwBQokscA3nAGrBYDuANHABUsADxj8ArqiwB1YADsAJhG4ARUFjmpgETXAC+cIiXKU8MALRzkMYADcstBuGjw2A5ACNOPfgGVcGlgAsshg+obEpBRUFlY29uYwnua2XNyOdLg6qPAAYsBQORgQ4jBYcAC8cAAUAJSVAHw1dHBwADze3HA5AJ4ANlgVLCwEA8IAXHAAjPweeADWAObE4ooAwhB90JNkAMQEBAAsAAwAHFNk-Mh9wItyAJJlIKg7AXJlUGR6eg0tre1CUTdGD9QbDLJbKA7bgAC2AZUuhh0MF8wAAXlhJgBmY78EDIKCLeSTABMx2+DXyhXgqFwlA0bQA9ICYL9WkzOr9avRMtl4L4sFlFMVSuUqnVGs12Z1gaChiMxpMZnA5rglit1pttuRdgA2ADsWM8+sR11uDyeL3Ibw+Xx+f3ZLNlA3lEO1ZFh8Ic-AIyNRGOxuLg+MJxLgZIpAqFCm6dKwDOZIlZfw5aS5PKFOTglEUWCg-kClTgBbkwVC1RYfwIBRykypRRKZV4fyk0cmUZ0ChFTboem5dDoIiY8Ez8AEUGQmjM2jk7i8aSLEoqTUrrVHcD6yB6jaLkhk8iUqnUmhnqDqPLXfLgAG0DyJ+FIYPdc8IALpF7BmAB0e98STK1RTP2l6aPA14rGUqDvlUn74D+Uh-tYWDVNeDqsHA8xYD0OzVtSiI2DAAw7PWMBkPozb-OhmHYeQradvh8JEeQHaKGRegUXAr79n8lAwOIUByFK-wdAuvQusMowiEqeIEkScikuS9qUY6nidGhlFWKkizWDOiFlPKcB3sI-AQVg6DfOp-w5goeYlmC1m2W8WB6JZrQ6M+NnCGsMKTosYKPh5Igucp-zyPCwDXAAMlujYGdwwAKDAMKTJu26lF+8WJTC+jBcpjJssJjKcn8-Z6EAA)

### Platform

- [ ] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [X] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [X] react-native-tab-view

### Environment

- [X] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |6.1.18
| @react-navigation/native-stack         |6.11.0
| react-native-safe-area-context         |4.10.9
| react-native-screens                   |3.34.0
| react-native-gesture-handler           |2.18.1
| react-native-reanimated                |3.15.0
| react-native-tab-view                  |3.5.2
| react-native-pager-view                |6.4.0
| react-native                           |0.75.2
| node                                   |20.8.0
| yarn                            |4.2.2

**Comment by SherlockLena** [comment]
Any updates?

**Comment by JustynaKK** [comment]
Any updates? still facing exactly the same issue
