### ISSUE TITLE
Navigation add focus listener does not get fired on first render with lazy loading

### ISSUE THREAD

**Issue by SYoder1** [react-navigation/react-navigation#12110]
### Current behavior

When using code splitting with React lazy, `navigation.addListener('focus', () => {})` will not be fired on the first render, on the first time navigating to the screen. If you navigate off the screen, and back to it, it will fire correctly.

I noticed that in v7 there is now screenLayout prop and a [docs section](https://reactnavigation.org/docs/7.x/web-support#lazy-loading-screens) talking about lazy loading. I tried out the v7 example and was also able to see the same issue.

Steps to reproduce in the example repo:
1. Navigate to the "Native stack" screen - observe that the comment  "** ArticleScreen focused" is **not** fired.
2. Navigate off the screen using pop or the back arrow
3. Navigate back to the screen  - observe that the comment  "** ArticleScreen focused" is **now** fired.

v6 reproducible example: https://github.com/SYoder1/react-navigation-lazy-example/tree/v6-lazy-load-screens
v7 reproducible example: https://github.com/SYoder1/react-navigation-lazy-example/tree/lazy-load-artical-screen

### Expected behavior

I would expect `navigation.addListener('focus', () => {})` to behave the same way as it does when screens are not lazy loaded, and fire on the first render of the first visit.

### Reproduction

https://snack.expo.dev/EU4_DO4JfP1RG-E1Di9DM

### Platform

- [X] Android
- [X] iOS
- [X] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

I am able to reproduce this on the example app on the latest v6 branch as well as main.
"@react-navigation/native": "6.1.18"

**Comment by satya164** [comment]
Lazy loaded screens get rendered after the screen has already been focused. It's normal that they won't get the event. It's not a bug - the thing with events is you'll miss them if you're not listening at the time they are fired.

If you need focus state, then there are other ways that don't have this limitation, such as `useFocusEffect` and `useIsFocused`.
