### ISSUE TITLE
key prop warning package Material Top Tabs Navigator

### ISSUE THREAD

**Issue by Anuj-Dhanuka** [react-navigation/react-navigation#12123]
### Current behavior

getting error while rendring but code is working good
 Warning: A props object containing a "key" prop is being spread into JSX:
  let props = {key: someKey, position: ..., route: ..., navigationState: ..., getAccessibilityLabel: ..., getAccessible: ..., getLabelText: ..., getTestID: ..., renderBadge: ..., renderIcon: ..., renderLabel: ..., activeColor: ..., inactiveColor: ..., pressColor: ..., pressOpacity: ..., onLayout: ..., onPress: ..., onLongPress: ..., labelStyle: ..., style: ..., defaultTabWidth: ..., android_ripple: ...};
  <TabBarItem {...props} />
React keys must be passed directly to JSX without using spread:
  let props = {position: ..., route: ..., navigationState: ..., getAccessibilityLabel: ..., getAccessible: ..., getLabelText: ..., getTestID: ..., renderBadge: ..., renderIcon: ..., renderLabel: ..., activeColor: ..., inactiveColor: ..., pressColor: ..., pressOpacity: ..., onLayout: ..., onPress: ..., onLongPress: ..., labelStyle: ..., style: ..., defaultTabWidth: ..., android_ripple: ...};
  <TabBarItem key={someKey} {...props} />
![IMG_20240828_224644_197](https://github.com/user-attachments/assets/2b54a73c-c405-449b-b61c-e0c6a94e7e87)

### Expected behavior

remove this unexpected behaviour

### Reproduction

https://github.com/Anuj-Dhanuka/social_media_app.git

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [X] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |
| @react-navigation/bottom-tabs          |
| @react-navigation/drawer               |
| @react-navigation/material-top-tabs    |  6.6.14
| @react-navigation/stack                |
| @react-navigation/native-stack         |
| react-native-safe-area-context         |
| react-native-screens                   |
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           |
| expo                                   |
| node                                   |
| npm or yarn                            |

**Comment by satya164** [comment]
Duplicate of #11989

**Comment by Zhashkha** [comment]
A few hours were spent on the investigation. In the end, I realized it had nothing to do with the code and updated all the navigation packages including @react-navigation/material-top-tabs 6.6.14 -> 7.0.3. The warning had gone

**Comment by eisodev-r** [comment]
For anyone wondering ,this is the cause:

<img width="616" height="467" alt="Image" src="https://github.com/user-attachments/assets/112c3b4d-d6df-4438-b0ef-eeafa0129243" />

Warning introduces from React 18.3

Patch package (make changes in the file and then run patch package) the key handling or update to latest versions. Im stuck on 6 for now because the upgrade to 7 is huge.
