### ISSUE TITLE
White flicker on drawer@7 when having nested navigators on new architecture

### ISSUE THREAD

**Issue by hsjoberg** [react-navigation/react-navigation#12137]
### Current behavior

Hi, when there are nested navigators \w @react-navigation/drawer@7, flickering occurs on Android when pulling the drawer.
This only happens on new architecture.

https://github.com/user-attachments/assets/5c56946a-2207-4187-8408-4af9d3c00243

There's also a warning from react-reanimated:
```
[react-native-gesture-handler] None of the callbacks in the gesture are worklets. If you wish to run them on the JS thread use '.runOnJS(true)' modifier on the gesture to make this explicit. Otherwise, mark the callbacks as 'worklet' to run them on the UI thread.
```

But I do not believe this is related.

It seems like the screens gets dismounted or something, because I have the core background color on my real other app as dark ( `<item name="android:windowBackground">@color/dark</item>`), and there the flickering is black instead.

The code is just this. Just nest navigators. I also uploaded a repro to github, link below.

```Typescript
import React from 'react';
import {createStackNavigator} from '@react-navigation/stack';
import {View} from 'react-native';
import {NavigationContainer} from '@react-navigation/native';
import {createDrawerNavigator} from '@react-navigation/drawer';

function Screen() {
  return (
    <View style={{ flex: 1, backgroundColor: '#000' }} />
  );
}

const Stack = createStackNavigator();
function MyStack() {
  return (
    <Stack.Navigator>
      <Stack.Screen name="Screen" component={Screen} />
    </Stack.Navigator>
  );
}

const Drawer = createDrawerNavigator();
function MyDrawer() {
  return (
    <Drawer.Navigator
      screenOptions={{
        swipeEdgeWidth: 400,
      }}>
      <Drawer.Screen name="Test" component={MyStack} />
    </Drawer.Navigator>
  );
}

export default function App() {
  return (
    <NavigationContainer>
      <MyDrawer />
    </NavigationContainer>
  );
}
```

### Expected behavior

There should be no flickering.

### Reproduction

https://github.com/hsjoberg/reactnavigationflashbug

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 7.0.0-rc.18
| @react-navigation/drawer               | 7.0.0-rc.28
| @react-navigation/stack                | 7.0.0-rc.24
| react-native                           | 0.75.2
| node                                   | v21.6.0
| npm or yarn                            | yarn@3

**Comment by Hasham24** [comment]
Any solution for this issue?

**Comment by hsjoberg** [comment]
> Any solution for this issue?

I'm not sure exactly where the issue is coming so I haven't looked at this yet.
What does your gut feeling say @satya164? Is it inside react-navigation or react-native-screens?

**Comment by Hasham24** [comment]
@hsjoberg I think react-native-screens is causing this issue.

**Comment by efstathiosntonas** [comment]
This warning `None of the callbacks in the gesture are worklets.` is fixed in this PR: https://github.com/react-navigation/react-navigation/pull/12240

**Comment by igoro00** [comment]
I had the same issue using expo 52 beta with new architecture enabled and using expo-router. It was flickering white during drawer animation but also when opening/closing a route with `animation: "slide_from_bottom"`. 

Just now expo 52 (non-beta) got released and the problem is gone.

I'm still getting consistent stutters on any drawer interaction but I think thats beyond the scope of this issue (and seems to be device dependent since there are no stutters on Waydroid on my PC)

**Comment by JustJoostNL** [comment]
@igoro00 did you manage to solve those consistent stutters? Since I upgraded to Expo SDK52 I have those too.

**Comment by mbilenko-florio** [comment]
There is one related bug with using useAnimatedStyle in react-native-reanimated. Can it be related? https://github.com/software-mansion/react-native-reanimated/issues/6659

**Comment by msaqlain** [comment]
Any Update on this issue?

**Comment by viet795** [comment]
react native screens flicker with new architecture.
Disabling it in Android and iOS works well

**Comment by arifrdon** [comment]
> react native screens flicker with new architecture. Disabling it in Android and iOS works well

this works for me on RN 0.77.3

**Comment by efstathiosntonas** [comment]
Hey folks, being struggling with this for like 3hrs, this patch finally fixed it for me: 

`react-native-drawer-layout+4.2.2.patch`

```patch
diff --git a/node_modules/react-native-drawer-layout/lib/module/views/Drawer.native.js b/node_modules/react-native-drawer-layout/lib/module/views/Drawer.native.js
index 40fdcdb..4a3c1e2 100644
--- a/node_modules/react-native-drawer-layout/lib/module/views/Drawer.native.js
+++ b/node_modules/react-native-drawer-layout/lib/module/views/Drawer.native.js
@@ -101,16 +101,16 @@
     onGestureCancel?.();
     endInteraction();
   });
-  const hitSlop = React.useMemo(() => isRight ?
-  // Extend hitSlop to the side of the screen when drawer is closed
-  // This lets the user drag the drawer from the side of the screen
-  {
+  // Patched: removed isOpen dependency to prevent gesture handler reconfiguration
+  // during animation, which causes a Fabric re-commit flash on Android.
+  // When open, the overlay handles close via onPress. Edge-only swipe is always active.
+  const hitSlop = React.useMemo(() => isRight ? {
     right: 0,
-    width: isOpen ? undefined : swipeEdgeWidth
+    width: swipeEdgeWidth
   } : {
     left: 0,
-    width: isOpen ? undefined : swipeEdgeWidth
-  }, [isRight, isOpen, swipeEdgeWidth]);
+    width: swipeEdgeWidth
+  }, [isRight, swipeEdgeWidth]);
   const touchStartX = useSharedValue(0);
   const touchX = useSharedValue(0);
   const translationX = useSharedValue(getDrawerTranslationX(open));
@@ -124,15 +124,21 @@
     }
     onTransitionEnd?.(!open);
   });
+  const animatingTo = useSharedValue(null)
   const toggleDrawer = React.useCallback((open, velocity) => {
     'worklet';

+    if (animatingTo.value === (open ? 'open' : 'close')) {
+      return;
+    }
+
     const translateX = getDrawerTranslationX(open);
     if (velocity === undefined) {
       runOnJS(onAnimationStart)(open);
     }
     touchStartX.value = 0;
     touchX.value = 0;
+    animatingTo.value = open ? 'open' : 'close';
     translationX.value = withSpring(translateX, {
       velocity,
       stiffness: 1000,
@@ -142,7 +148,12 @@
       restDisplacementThreshold: 0.01,
       restSpeedThreshold: 0.01,
       reduceMotion: ReduceMotion.Never
-    }, finished => runOnJS(onAnimationEnd)(open, finished));
+    }, finished => {
+      if (finished) {
+        animatingTo.value = null;
+      }
+      runOnJS(onAnimationEnd)(open, finished);
+    });
     if (open) {
       runOnJS(onOpen)();
     } else {
@@ -269,7 +280,7 @@
             children: [/*#__PURE__*/_jsxs(Animated.View, {
               style: [styles.content, contentAnimatedStyle],
               children: [/*#__PURE__*/_jsx(View, {
-                "aria-hidden": isOpen && drawerType !== 'permanent',
+                "aria-hidden": false,
                 style: styles.content,
                 children: children
               }), drawerType !== 'permanent' ? /*#__PURE__*/_jsx(Overlay, {

```

Claude code reasoned: 

> 1. The hitSlop → gesture handler cascade (THE main cause)
> 
>   Inside react-native-drawer-layout, hitSlop depends on isOpen:
>   width: isOpen ? undefined : swipeEdgeWidth
>   When onClose fires → open changes → isOpen changes → hitSlop recomputes → pan gesture recreates → GestureDetector reconfigures the native gesture handler. On Android
>   Fabric, this native reconfiguration mid-animation causes the entire child view tree to detach/reattach for one frame → flash.
> 
>   2. aria-hidden prop change
> 
>   The content View had aria-hidden={isOpen}. When open flipped during animation, this native prop change triggered another Fabric commit on the view wrapping all your
>   content.
> 
>  The fixes:
>   - Patched hitSlop to not depend on isOpen (edge-swipe always, overlay handles close-on-tap)
>   - Patched aria-hidden to constant false (overlay already handles accessibility)
>   - animatingTo guard with if (finished) (prevents spring double-fire and interrupted animation race)


@satya164 sorry for tagging you on this old issue but maybe you might want to look into it. It was a big PITA to hunt it down.
