### ISSUE TITLE
Bottom Tab Push itself up when keyboard is opening in both android and ios

### ISSUE THREAD

**Issue by FaizyQadri** [react-navigation/react-navigation#12147]
### Current behavior

whenver keyboard is opening the bottom tab push it self up in ios and android both
![keyboard](https://github.com/user-attachments/assets/8c06395f-4a5d-4ebb-bdac-a41249875f0b)

const AppEntry = () => {
  useEffect(() => {
    setTimeout(() => {
      SplashScreen.hide();
    }, 2000);
  }, []);

  return (
    <SafeAreaView style={styles.root}>
      <KeyboardAvoidingView
        behavior={Platform.OS === 'ios' ? 'padding' : undefined}
        style={styles.root}>
        <NavigationContainer>
          <StatusBar barStyle={'dark-content'} backgroundColor={Colors.white} />

          <RootStackNavigator />
        </NavigationContainer>
      </KeyboardAvoidingView>
    </SafeAreaView>
  );
};

export default AppEntry;

const styles = StyleSheet.create({
  root: {
    flex: 1,
  },
  text: {
    color: 'black',
    fontSize: 14,
  },
});
const Stack = createNativeStackNavigator<any>();
const RootStackNavigator = () => {
  return (
      <Stack.Navigator
        screenOptions={{headerShown: false, animation: 'slide_from_right'}}>
        <Stack.Screen
          name="BottomTabNavigator"
          component={BottomTabNavigator}
        />
        <Stack.Screen name="Products" component={Products} />
        <Stack.Screen
          name="ProductDescription"
          component={ProductDescription}
        />
      </Stack.Navigator>
  );
};

export default RootStackNavigator;

const Tab = createBottomTabNavigator();

const BottomTabNavigator = () => {
  return (
      <Tab.Navigator
        screenOptions={{
          tabBarHideOnKeyboard: true,
          headerShown: false,
        }}
        backBehavior="initialRoute"
        tabBar={() => {
          return <TabBar  />;
        }}
        sceneContainerStyle={styles.sceneContainerStyle}>
        <Tab.Screen name="Home" component={Home} />

        <Tab.Screen name="Updates" component={Updates} />

        <Tab.Screen name="Inquiries" component={Inquiries} />

        <Tab.Screen name="ContactUs" component={ContactUs} />
      </Tab.Navigator>
  );
};

### Expected behavior

i want bottom should not be seen when keyboard is opening it should be hidden
so what should i do to achieve this

### Reproduction

https://github.com/FaizyQadri/Nexus

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |6.1.18
| @react-navigation/bottom-tabs        |6.6.1  
| @react-navigation/drawer               |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                |
| @react-navigation/native-stack         |6.11.0
| react-native-safe-area-context         |^4.10.9
| react-native-screens                   |3.34.0
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           |0.75.2
| expo                                   |
| node                                   |>=18
| npm or yarn                            | yarn

**Comment by FaizyQadri** [comment]
"@react-navigation/native-stack": "^6.11.0",
@react-navigation/drawer : not using 
@react-navigation/material-top-tabs:"^6.6.14",
react-native-tab-view:""^3.5.2"

but i am not using tabview and material top tabs 
i have shared repo link as well of the project hope so this time u people will fix this issue

**Comment by FaizyQadri** [comment]
> Couldn't find version numbers for the following packages in the issue:
> 
> * `@react-navigation/stack`
> * `@react-navigation/drawer`
> * `@react-navigation/material-top-tabs`
> * `react-native-tab-view`
> 
> Can you update the issue to include version numbers for those packages? The version numbers must match the format 1.2.3.

have u done any changes ?

**Comment by FaizyQadri** [comment]
@satya164 any updates on this why custom tab bar is not hiding in latest version

**Comment by raajnadar** [comment]
You should spend time to figure out things, or at least send a runnable [snack](https://snack.expo.dev/) code to reproduce the bug.

Tagging maintainer is not correct way

**Comment by FaizyQadri** [comment]
> Hey! This issue is closed and isn't watched by the core team. You are welcome to discuss the issue with others in this thread, but if you think this issue is still valid and needs to be tracked, please open a new issue with a repro.

i have shared running repo u can run and check it 
i have used same library in several projects 
but currently this is not working when we create custom tab bar

**Comment by raajnadar** [comment]
The repo link is not working, you are missing some native configuration you need to figure out that yourself, this has nothing to do with react-navigation. Compare your code with the project where it works.

If you can reproduce it on snack expo send the link.

**Comment by FaizyQadri** [comment]
@raajnadar 
https://snack.expo.dev/@faizyqadri/bottomtabissue?platform=android
look i have created it in snack as well

**Comment by FaizyQadri** [comment]
> https://snack.expo.dev/@faizyqadri/bottomtabissue?platform=android
> look i have created it in snack as well

https://snack.expo.dev/@faizyqadri/bottomtabissue?platform=android
look i have created it in snack as well
@satya164
