### ISSUE TITLE
Align API with `native-navigation`

### ISSUE THREAD

**Issue by grabbou** [react-navigation/react-navigation#1215]
During discussion with @ericvicenti, there was that idea of aligning APIs betweeh those two libraries.

This issue is a placeholder for work that has to be done in that area.

- [ ] `headerLeft` and `headerRight` should accept a string

Open for discussion if there are (any) benefits of doing so

**Comment by ericvicenti** [comment]
We can also provide function handlers for left and right button, like how native-navigation does

**Comment by satya164** [comment]
We don't render any

What'd `headerLeft: 'Something'` or `headerRight: 'Something'` render?

Regarding the handler, isn't `headerLeft: <HeaderBackButton onPress={...} />` sufficient?

**Comment by ericvicenti** [comment]
It would render a button, like it does in Airbnb's library

**Comment by grabbou** [comment]
Hm, what would be the onPress behaviour of such?
