### ISSUE TITLE
Bottom Tab Get Pushed When Keyboard Is Opening In Both Android And Ios When We Use Custom Tab 

### ISSUE THREAD

**Issue by FaizyQadri** [react-navigation/react-navigation#12152]
### Current behavior

When i am using custom tab bar in BottomTab when keyboard is opening then bottom tab pushes its self up 

https://github.com/user-attachments/assets/ae0e3e38-d0fe-4def-bf34-b6b7f912846d

import {NavigationContainer} from '@react-navigation/native';
import {createNativeStackNavigator} from '@react-navigation/native-stack';
import React from 'react';
import BottomStack from './BottomStack';
const Stack = createNativeStackNavigator();

const RootStack = () => {
  return (
    <NavigationContainer>
      <Stack.Navigator screenOptions={{animation: 'fade', headerShown: false}}>
        <Stack.Screen name="BottomStack" component={BottomStack} />
      </Stack.Navigator>
    </NavigationContainer>
  );
> };`
**BottomStack**
`import {createBottomTabNavigator} from '@react-navigation/bottom-tabs';
import React from 'react';
import Home from '../screens/home/Home';
import Notifications from '../screens/notifications/Notifications';
import Profile from '../screens/profile/Profile';
import MyMenu from '../screens/myMenu/MyMenu';
import TabBar from '../tabBar/tabBar';

const Tab = createBottomTabNavigator();
const BottomStack = () => {
  return (
    <Tab.Navigator
      initialRouteName="Home"
      screenOptions={{
        tabBarHideOnKeyboard: true,
        headerShown: false,
      }}
      tabBar={props => <TabBar {...props} />}>
      <Tab.Screen name="Home" component={Home} />
      <Tab.Screen name="Notifications" component={Notifications} />
      <Tab.Screen name="Profile" component={Profile} />
      <Tab.Screen name="MyMenu" component={MyMenu} />
    </Tab.Navigator>
  );
};

export default BottomStack;`
[https://snack.expo.dev/@faizyqadri/bottomtabissue?platform=android](url)

### Expected behavior

@raajnadar 
@satya164 
i have shared expo snack link hope so this time u guys ware taking it seriously 
we want bottom tab to hide when keyboard open 

if we dont use CustomTab then its working great

https://github.com/user-attachments/assets/535b6912-5feb-4b1a-92fb-d26d5d7845d9

### Reproduction

https://snack.expo.dev/@faizyqadri/bottomtabissue

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use
@react-navigation/drawer 
@react-navigation/material-top-tabs
@react-navigation/stack
react-native-gesture-handler 
react-native-tab-view
react-native-pager-view 
expo

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |    6.1.18
| @react-navigation/bottom-tabs          |  6.6.1
| @react-navigation/drawer               |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                |
| @react-navigation/native-stack         | 6.11.0
| react-native-safe-area-context         |  4.11.0 
| react-native-screens                   |   3.34.0
| react-native-gesture-handler           |
| react-native-reanimated                |  3.15.2
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           |  0.75.3
| expo                                   |
| node                                   | v20.9.0
| npm or yarn                            | yarn - 3.6.4

**Comment by FaizyQadri** [comment]
> * @react-navigation/stack

@react-navigation/stack
@react-navigation/drawer
@react-navigation/material-top-tabs
react-native-tab-view
not using any of these libraryies

**Comment by FaizyQadri** [comment]
@raajnadar bro u can check here i have created that issue in within no times on slack as well if u want i can share u git repo as well

**Comment by raajnadar** [comment]
As you are using a custom tab it is you as a developer to figure out this, that is the reason the control was given to the devs to customise as per your requirements.

https://github.com/react-navigation/react-navigation/blob/main/packages/bottom-tabs/src/utils/useIsKeyboardShown.tsx

**Comment by FaizyQadri** [comment]
> As you are using a custom tab it is you as a developer to figure out this, that is the reason the control was given to the devs to customise as per your requirements.
> 
> https://github.com/react-navigation/react-navigation/blob/main/packages/bottom-tabs/src/utils/useIsKeyboardShown.tsx

so why the same code is working fine in previous all versions u as developer can explained

**Comment by FaizyQadri** [comment]
> As you are using a custom tab it is you as a developer to figure out this, that is the reason the control was given to the devs to customise as per your requirements.
> 
> https://github.com/react-navigation/react-navigation/blob/main/packages/bottom-tabs/src/utils/useIsKeyboardShown.tsx

@raajnadar i guess u people are not resolving this issue thats y u are just closing it without even having a look at the code 
great ...

**Comment by raajnadar** [comment]
What is to be fixed here? if you use the built-in tab bar you get the feature, if you opt to use your own implementation of the tab bar you need to handle that case.

If you have a solution around it send a PR, the code is open source for you to look into it and send a fix if you think you have a solution.

**Comment by FaizyQadri** [comment]
Can u just give an explanation then why same implementation was working fine with older versions
That would be very kind of you

**Comment by raajnadar** [comment]
You can see the comments, I gave you the snippet from the built-in bottom bar, but you overlooked the comments, you as a dev can figure out how to implement the same in your codebase.

**Comment by FaizyQadri** [comment]
Bro I have made the solution at my end as well but still wanna know the reason as u have developed so please explain why we have to now used some other thing to fixed it

**Comment by vladimirivanoviliev** [comment]
I'm experiencing the same issue on latest react navigation, and it happens only in production builds. This is the most annoying - different behavior between production and dev builds. I'm not sure how that should be expected.
