### ISSUE TITLE
Re-render all screens in tabs when pressing bottom tab, top tab, stack  on react native for windows c++

### ISSUE THREAD

**Issue by vuongdev68** [react-navigation/react-navigation#12172]
### Current behavior

I use bottom tab navgiation react native for windows, when clicking on a tab all screens in the tab are initialized again. I tried initializing a new project and got the same situation. I use the latest version of react native, react native windows navigation.

### Expected behavior

I don't want it to reload the screens, even empty dependency useEffect gets called again

### Reproduction

no

### Platform

- [ ] Android
- [ ] iOS
- [ ] Web
- [X] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [X] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |
| @react-navigation/bottom-tabs          |
| @react-navigation/drawer               |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                |
| @react-navigation/native-stack         |
| react-native-safe-area-context         |
| react-native-screens                   |
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           |
| expo                                   |
| node                                   |
| npm or yarn                            |

**Comment by satya164** [comment]
react native windows is unmounting unfocused screens (iirc when they are hidden from a11y). it's a bug in react native windows since the same code works correctly on all other platforms.
