### ISSUE TITLE
[7.x] crashes on ios with react-native 0.76.rc.6

### ISSUE THREAD

**Issue by jbrodriguez** [react-navigation/react-navigation#12198]
### Current behavior

it crashes on start

it worked on 0.76.rc.2, it's crashing with this upgrade to rc.6

![Simulator Screenshot - iPhone 15 Pro - 2024-10-19 at 08 39 53](https://github.com/user-attachments/assets/4f4eaecd-83d2-458b-bf5d-f86f16a4364d)
```
 (NOBRIDGE) ERROR  Warning: Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `DebugContainer`.

This error is located at:
    in DebugContainer (created by MaybeNestedStack)
    in MaybeNestedStack (created by SceneView)
    in RNSScreen (created by Animated(Anonymous))
    in Animated(Anonymous)
    in Suspender (created by Freeze)
    in Suspense (created by Freeze)
    in Freeze (created by DelayedFreeze)
    in DelayedFreeze
    in InnerScreen (created by Screen)
    in Screen (created by SceneView)
    in SceneView (created by NativeStackView)
    in Suspender (created by Freeze)
    in Suspense (created by Freeze)
    in Freeze (created by DelayedFreeze)
    in DelayedFreeze (created by ScreenStack)
    in RNSScreenStack (created by ScreenStack)
    in ScreenStack (created by NativeStackView)
    in RCTView (created by View)
    in View (created by SafeAreaProviderCompat)
    in SafeAreaProviderCompat (created by NativeStackView)
    in NativeStackView (created by NativeStackNavigator)
    in PreventRemoveProvider (created by NavigationContent)
    in NavigationContent
    in Unknown (created by NativeStackNavigator)
    in NativeStackNavigator (created by RootNavigator)
    in RootNavigator
    in ThemeProvider
    in EnsureSingleNavigator
    in BaseNavigationContainer
    in NavigationContainerInner
    in Navigation (created by Navigator)
    in Navigator (created by App)
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by App)
    in App
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in app(RootComponent)
```

### Expected behavior

shouldn't crash

### Reproduction

https://snack.expo.dev/2FA3O15GEfnvY4CxZ1773

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | next
| @react-navigation/stack                | next
| @react-navigation/native-stack         | next
| react-native-safe-area-context         | 4.11.0
| react-native-screens                   | 3.34.0
| react-native                           | 0.76.0-rc.6
| node                                   | 21.x
| npm or yarn                            | yarn 3.x

**Comment by jbrodriguez** [comment]
package version are next because of 7.x

**Comment by satya164** [comment]
https://github.com/react-navigation/react-navigation/releases/tag/%40react-navigation%2Fnative-stack%407.0.0-rc.28

> Native Stack now requires react-native-screens 4
