### ISSUE TITLE
Adding bottom tabs to the app creates a white space roughly equal to the height of status bar at the top of the screen

### ISSUE THREAD

**Issue by rranjan14** [react-navigation/react-navigation#12200]
### Current behavior

![Screenshot_20241021_125911](https://github.com/user-attachments/assets/8322b46f-e7c6-4df7-811d-495d258e5e5f)
I am facing some trouble with `@react-navigation/bottom-tabs` since I upgraded to `react-native-0.75` and `react-native-screens` to `3.34.0`. On iOS, everything seems to work fine, but on Android, I get this space which is roughly equal to the height of the status bar. I have a navigation structure which is something like:
```- Stack Navigator
  - Tab Navigator
      - Drawer Navigator
      - Tab 2
      - Tab 3
      - Tab 4
  - Stack Screen 2
  - Stack Screen 3```
Now, my app is wrapped in `SafeAreaProvider` and I use a translucent status bar.
I am not using any screen with `SafeAreaView`

If I remove the tab navigator, every thing works just fine.  The white space visible in the attached image is not a part of react tree as I am only able to change it's background color using `expo-system-ui`'s `setBackgroundColorAsync`.

Relevant dependencies:
```{
    "@react-navigation/bottom-tabs": "^6.6.1",
    "@react-navigation/drawer": "^6.7.2",
    "@react-navigation/native": "^6.1.18",
    "@react-navigation/native-stack": "^6.11.0",
    "expo-system-ui": "~3.0.7",
    "react-native": "~0.75.4",
    "react-native-gesture-handler": "~2.20.0",
    "react-native-keyboard-controller": "^1.14.1",
    "react-native-reanimated": "~3.15.5",
    "react-native-safe-area-context": "^4.11.1",
    "react-native-screens": "^3.34.0",
}```

Everything works fine on rn 0.74. I haven't checked on any other version other than 0.75(both new and old architecture) and 0.74. 
Structure:
```
- SafeAreaProvider
  - GestureHandlerRootView
    - KeyboardProvider (from react-native-keyboard-controller)
      - NavigationContainer
      
      
- `headerShown` screenOption is set to false at the navigator level and  added to the `Screen` component wherever relevant

### Expected behavior

There should not be any white space

### Reproduction

Unable to repro this in a new project

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | "^6.1.18"
| @react-navigation/bottom-tabs          | "^6.6.1"
| @react-navigation/drawer               | "^6.7.2"
| @react-navigation/material-top-tabs    | N/A
| @react-navigation/stack                | N/A
| @react-navigation/native-stack         | "^6.11.0"
| react-native-safe-area-context         | "^4.11.1"
| react-native-screens                   | "^3.34.0"
| react-native-gesture-handler           | "~2.20.0"
| react-native-reanimated                | "~3.15.5"
| react-native-tab-view                  | N/A
| react-native-pager-view                | "6.4.1"
| react-native                           | "~0.75.4"
| expo                                   | "~51.0.38"
| node                                   | "v20.13.1
| npm or yarn                            | `yarn-4.5.0`

**Comment by fracico-tech** [comment]
Hi @rranjan14 , did you remember how you fixed it?
