### ISSUE TITLE
[v7] Module "react-native-tab-view" has no exported member Scene

### ISSUE THREAD

**Issue by efstathiosntonas** [react-navigation/react-navigation#12239]
### Current behavior

Hi, after upgrading to v7 I got this type error:

![Image](https://github.com/user-attachments/assets/8b37c36d-51a3-4222-8922-66fc29118008)

TS2305: Module "react-native-tab-view" has no exported member Scene

```ts
  function renderScene({ route: tabRoute }: Scene<Route>) {
     ...
  }
```

on v6 I used to import it like this: `import { Scene } from 'react-native-tab-view/lib/typescript/src/types'` and it worked fine.

Weird thing is that `react-native-tab-view/src/types.tsx` contains:

```ts
export type Scene<T extends Route> = {
  route: T;
};
```

After adding it on `/lib/typescript/commonjs/src/index.d.ts` it stopped complaining: 

```ts
export type { NavigationState, Route, SceneRendererProps, TabDescriptor, Scene, } from './types';
```

### Expected behavior

Expect the `Scene` to be properly exported.

### Reproduction

no repro, it's typing issue

### Platform

- [x] Android
- [x] iOS
- [x] Web
- [x] Windows
- [x] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [x] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 7.0.0
| @react-navigation/bottom-tabs         | 7.0.0 
| @react-navigation/drawer              | 7.0.0 
| @react-navigation/stack               | 7.0.0
| @react-navigation/native-stack        | 7.0.0
| react-native-safe-area-context         | 4.14.0
| react-native-screens                  | 4.0.0 
| react-native-gesture-handler           | 2.0.22
| react-native-reanimated                | 3.16.1
| react-native-tab-view                 | 4.0.1
| react-native-pager-view               | 6.5.0
| react-native                          | 0.75.4 
| expo                                   | 51.0.38
| node                                   | 20
| npm or yarn                            | 4.5.1

**Comment by satya164** [comment]
It wasn't exported in v6 either, importing internal files like what you were doing was never supported. `Scene` type is supposed to be an internal type.

You can just write `{ route: Route }` which isn't that different from `Scene<Route>`. Does it really need to be exported?

But if you want to properly type `renderScene`, then `Scene` is not a correct type. You can annotate `renderScene` like this:

```js
const renderScene: React.ComponentProps<typeof TabView<Route>>['renderScene'] =
```

It maybe useful to export `TabViewProps` which would make it:

```js
const renderScene: TabViewProps<Route>['renderScene'] =
```

**Comment by efstathiosntonas** [comment]
@satya164 thanks for the inshight, closing this.
