### ISSUE TITLE
TypeError: 0, _native.useLocale is not a function (it is undefined)

### ISSUE THREAD

**Issue by IlirBajrami** [react-navigation/react-navigation#12237]
### Current behavior

![Image](https://github.com/user-attachments/assets/11ae2398-0907-494a-813a-201d48db4723)

### Expected behavior

Show the tabs at the top

### Reproduction

no repo

### Platform

- [ ] Android
- [x] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [x] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [x] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | "^6.0.2"
| @react-navigation/bottom-tabs          |
| @react-navigation/drawer               |
| @react-navigation/material-top-tabs    | "^7.0.1"
| @react-navigation/stack                |
| @react-navigation/native-stack         |
| react-native-safe-area-context         | "4.10.5"
| react-native-screens                   | "3.31.1"
| react-native-gesture-handler           | "~2.16.1"
| react-native-reanimated                | "~3.10.1"
| react-native-tab-view                  | "^4.0.1"
| react-native-pager-view                | "6.3.0"
| react-native                           | "0.74.5"
| expo                                   | "~51.0.38"
| node                                   | v20.9.0
| npm or yarn                            | npm 10.1.0

**Comment by pisacode** [comment]
try installing `pnpm add @react-navigation/drawer@6.7.2` that is the latest working version @IlirBajrami

**Comment by IlirBajrami** [comment]
@pisacode actually it worked after updating `"@react-navigation/native": "^7.0.0",` but i'm having another issue which i don't know how to explain it shortly. Its not navigating to my other links in a use case with nested layouts using expo router. It might be tricky to fix if its "fixable" at all.

**Comment by leandromatos** [comment]
I have the same issue here. When I downgrade from 7.0.0 to 6.7.2, everything works again.

**Comment by satya164** [comment]
You can't mix 7.x and 6.x packages. Either use 6.x versions of all packages, or use 7.x versions.

**Comment by leandromatos** [comment]
In my case, I was trying to use the expo-router/drawer.

**Comment by bimix** [comment]
@IlirBajrami  veq bonja update react navigation edhe rregullohet.

**Comment by vinibgoulart** [comment]
worked for me using this versions:

```json
"@react-navigation/bottom-tabs": "^6.6.1",
"@react-navigation/drawer": "6.7.2",
"@react-navigation/native": "^6.1.18",
```

**Comment by Asadaial** [comment]
gpt can never give response to errors like these...

**Comment by HezekiahsDev** [comment]
> gpt can never give response to errors like these...

Maybe it will grow overtime when users provide the solutions that worked...
then GPT will become better and guess what??
