### ISSUE TITLE
Material top Tabs Navigation label tab delay render for split seconds on first mount

### ISSUE THREAD

**Issue by vorn-dev-ni** [react-navigation/react-navigation#12231]
### Current behavior

The tab labels do not show up immediately when the component is first rendered.
There is a noticeable delay before the labels are displayed, which affects the initial user experience

### Expected behavior

The tab labels should be visible immediately upon the initial render without any delay.
The active tab's indicator should also be displayed correctly and instantly.

### Reproduction

https://snack.expo.dev/UNrDA-FD3T1eIMGZF91It

### Platform

- [x] Android
- [x] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [x] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |
| @react-navigation/bottom-tabs          |
| @react-navigation/drawer               |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                |
| @react-navigation/native-stack         |
| react-native-safe-area-context         |
| react-native-screens                   |
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           |
| expo                                   |
| node                                   |
| npm or yarn                            |

**Comment by GaelCO** [comment]
Hi, 
Same issue in our project. 
It is especially noticeable if a child screen takes a long time to load.
For example, in a child screen, a CalendarList is loaded (react-native-calendars) and the label is displayed only after the child screen was loaded.
From memory, this was not the case in older versions of react navigation (4 or 5).

react-navigation versions
"@react-navigation/bottom-tabs": "^6.6.1",
"@react-navigation/core": "^6.4.17",
"@react-navigation/material-top-tabs": "^6.6.14",
"@react-navigation/native": "^6.1.18",
"@react-navigation/stack": "^6.4.1",
"react-native-tab-view": "^3.5.2",

For information, I test with react-navigation 7.X and this behavior is still present
