### ISSUE TITLE
[v7][newarch] NavigationContainer onReady callback is never triggered

### ISSUE THREAD

**Issue by jafar-jabr** [react-navigation/react-navigation#12247]
### Current behavior

The onReady callback of NavigationContainer from 
@react-navigation/native
 is never triggered. No logs or errors are generated.

### Expected behavior

The onReady callback should be triggered after the navigation tree is fully mounted and ready.

### Reproduction

https://github.com/react-navigation/react-navigation/blob/main/example/src/index.tsx#L237

### Platform

- [x] Android
- [x] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [x] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 7.0.0
| @react-navigation/bottom-tabs          |  N/A
| @react-navigation/drawer               | N/A
| @react-navigation/material-top-tabs    | N/A
| @react-navigation/stack                | 7.0.0
| @react-navigation/native-stack         | 7.0.0
| react-native-safe-area-context         | 4.14.0
| react-native-screens                   | 4.0.0
| react-native-gesture-handler           | 2.20.2
| react-native-reanimated                | 3.16.1
| react-native-tab-view                  | N/A
| react-native-pager-view                |
| react-native                           | 0.76.1
| expo                                   | N/A
| node                                   | v20.1.0
| npm or yarn                            | yarn@3.6.4

**Comment by thianphat** [comment]
@jafar-jabr  Also running into this as well, what was your solution?

**Comment by zabojad** [comment]
@thianphat @jafar-jabr Have you found an explanation?
