### ISSUE TITLE
when i try to use react naviagation i can't build the project some errors from gradle is comming

### ISSUE THREAD

**Issue by GANGADHARAN-ls** [react-navigation/react-navigation#12245]
### Current behavior

info Installing the app...
Starting a Gradle Daemon, 1 stopped Daemon could not be reused, use --status for details

info 💡 Tip: Make sure that you have set up your development environment correctly, by running npx react-native doctor. To read more about doctor command visit: https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor 

FAILURE: Build failed with an exception.

* Where:
Settings file 'C:\Users\gangadharan\Desktop\React Native\LMS\android\settings.gradle' line: 2

* What went wrong:
Error resolving plugin [id: 'com.facebook.react.settings']
> A build operation failed.
      Could not read workspace metadata from C:\Users\gangadharan\.gradle\caches\8.10.2\transforms\1833916025afc9f563349d959213ee6c\metadata.bin
   > Could not read workspace metadata from C:\Users\gangadharan\.gradle\caches\8.10.2\transforms\1833916025afc9f563349d959213ee6c\metadata.bin

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 7s
error Failed to install the app. Command failed with exit code 1: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081 FAILURE: Build failed with an exception. * Where: Settings file 'C:\Users\gangadharan\Desktop\React Native\LMS\android\settings.gradle' line: 2 * What went wrong: Error resolving plugin [id: 'com.facebook.react.settings'] > A build operation failed. Could not read workspace metadata from C:\Users\gangadharan\.gradle\caches\8.10.2\transforms\1833916025afc9f563349d959213ee6c\metadata.bin > Could not read workspace metadata from C:\Users\gangadharan\.gradle\caches\8.10.2\transforms\1833916025afc9f563349d959213ee6c\metadata.bin * Try: > Run with --stacktrace option to get the stack trace. > Run with --info or --debug option to get more log output. > Run with --scan to get full insights. > Get more help at https://help.gradle.org. BUILD FAILED in 7s.
info Run CLI with --verbose flag for more details.

### Expected behavior

expected behavior to build the project without any error

### Reproduction

i can't share the github

### Platform

- [ ] Android
- [ ] iOS
- [ ] Web
- [x] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [x] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |
| @react-navigation/bottom-tabs          |
| @react-navigation/drawer               |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                |
| @react-navigation/native-stack         |
| react-native-safe-area-context         |
| react-native-screens                   |
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           |
| expo                                   |
| node                                   |
| npm or yarn                            |

**Comment by AbuthahirGitHub** [comment]
Simple change the gradle to local installation , if you're using android studio navigate to file->settings->build and execution tools-> build tools->gradle change wrapper to local installation
