### ISSUE TITLE
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined

### ISSUE THREAD

**Issue by burakgokcinarr** [react-navigation/react-navigation#12250]
### Current behavior

Hello everyone 

I recently created an empty project to try React Navigation v7 and tried to run the basic code in the documentation, but I got the error “Error: Item type invalid: expected a string (for built-in components) or a class/function (for composite components) but I got the following result: undefined. You probably forgot to export your component from the file where it is defined, or you may have mixed up default and named imports.” Yes, the documentation says Expo SKD 52 and above, but I'm using 51. I wanted to try it anyway. I'm not sure if the error is entirely due to this, but has anyone else encountered this? I don't think this error is due to the Expo version.

![Image](https://github.com/user-attachments/assets/b58ced1b-9def-4a14-bc27-75d974cc8855)

### Expected behavior

I actually expected it to work in Expo SDK 51 because I don't think this error is caused by expo sdk.

### Reproduction

https://snack.expo.dev/@burak717171/react-navigation-v7-test-app

### Platform

- [x] Android
- [x] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [x] @react-navigation/stack
- [x] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |^7.0.0
| @react-navigation/native-stack         |^7.0.0
| react-native-safe-area-context         |4.10.5
| react-native-screens                   |3.31.1
| react-native                           |0.74.5
| expo                                   |~51.0.28
| node                                   |v20.17.0
| npm or yarn                            |10.8.2

**Comment by alecdhansen** [comment]
Following. Same issue

**Comment by satya164** [comment]
React Navigation 7 requires Expo SDK 52. Snack doesn't have Expo SDK 52 yet.

**Comment by ryanwangtian** [comment]
fix the same issue by updating `react-native-screens` to 4.3.0
