### ISSUE TITLE
headerLargeStyle Doesn't work anymore in iOS

### ISSUE THREAD

**Issue by LegendProjects** [react-navigation/react-navigation#12268]
### Current behavior

headerLargeStyle is true but doesn't do the animation in iOS as it should..

Usng EXPO SDK 52 latest when I upgraded all to the latest version I have this issue..

### Expected behavior

To do the animation

### Reproduction

headerLargeStyle

### Platform

- [ ] Android
- [x] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [x] @react-navigation/stack
- [x] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |
| @react-navigation/bottom-tabs          |
| @react-navigation/drawer               |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                |
| @react-navigation/native-stack         |
| react-native-safe-area-context         |
| react-native-screens                   |
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           |
| expo                                   |
| node                                   |
| npm or yarn                            |

**Comment by LegendProjects** [comment]
edit

**Comment by mlabod** [comment]
you mean `headerLargeTitle`, right?
when i set it to true with the new react native version, it doesn't collapse anymore when scrolling..

**Comment by LegendProjects** [comment]
> you mean `headerLargeTitle`, right? when i set it to true with the new react native version, it doesn't collapse anymore when scrolling..

Yes exactly

**Comment by mlabod** [comment]
I think i found the problem in my case:

The ScrollView / FlatList inside the stack had a parent view with a backgroundColor. When i remove it it works. really strange


_layout

```tsx

import { ScrollView, View, Text } from "react-native";
import { Stack } from "expo-router";

export default function StackScreen () {
  return (
    <View style={{ backgroundColor: "red" }}> // <-- this seems to break it???
      <ScrollView
        contentInsetAdjustmentBehavior="automatic"
      >
        <Stack.Screen
          options={{
            title:"Large Header Test",
            headerLargeTitle:true,
            headerTransparent:true
          }}
        />
        <View>
          <Text>Test</Text>
        </View>
      </ScrollView>
    </View>
  )
}

```

**Comment by LegendProjects** [comment]
> I think i found the problem in my case:

Yes that's was the problem but i cannot understand why this happened.. before it worked fine but now with the update is breaking.. and yes i checked now and it was bg problem you was correct.

**Comment by hwhh** [comment]
I am also seeing this, previous behavior worked where the scrollView / flatList could be within a view but now its broken

**Comment by madsfranzen** [comment]
This is still a problem, I just opened a new issue [ISSUE12430](https://github.com/react-navigation/react-navigation/issues/12430)

**Comment by jerone** [comment]
Did anyone find a solution for this problem?

I cannot remove the extra wrapped `View`; it contains logic I need.
This used to work just fine.
