### ISSUE TITLE
Using React.ReactElement instead of React.ReactNode is causing new unnecessary typescript errors (`tabBarBadge` options for example)

### ISSUE THREAD

**Issue by bhandanyan-nomad** [react-navigation/react-navigation#12267]
### Current behavior

```javascript
tabBarBadge: () => !!shouldShowBadge && (
    <View style={{ paddingRight: 40 }}>
        <TopTabBadge />
    </View>
),
```

throws the following TS error:
```
Type '() => false | React.JSX.Element' is not assignable to type '() => ReactElement<any, string | JSXElementConstructor<any>>'.
  Type 'false | Element' is not assignable to type 'ReactElement<any, string | JSXElementConstructor<any>>'.
    Type 'boolean' is not assignable to type 'ReactElement<any, string | JSXElementConstructor<any>>'.ts(2322)
```

### Expected behavior

The badge function should be able to return any valid react node, including `null` when there should be no badge. The functionality works fine in both v6 and v7, it's just that there's a new type error.

### Reproduction

-

### Platform

- [x] Android
- [x] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [x] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |
| @react-navigation/bottom-tabs          |
| @react-navigation/drawer               |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                |
| @react-navigation/native-stack         |
| react-native-safe-area-context         |
| react-native-screens                   |
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           |
| expo                                   |
| node                                   |
| npm or yarn                            |

**Comment by satya164** [comment]
`React.ReactNode` isn't the correct type as it also allows to return `string`, `number` etc. which are not valid and will crash the app. Of course you can still do that with `ReactElement`, but there's nothing that can be done on type-level to prevent that.

I'd suggest something like this instead:

```js
tabBarBadge: shouldShowBadge ? () => (
    <View style={{ paddingRight: 40 }}>
        <TopTabBadge />
    </View>
) : undefined
```

Or if you want to have ternary like this you can always wrap it in a fragment:


```js
tabBarBadge: () => <>{!!shouldShowBadge && (
    <View style={{ paddingRight: 40 }}>
        <TopTabBadge />
    </View>
)}</>
```
