### ISSUE TITLE
Drawer/bottom-tabs screens not removed from DOM on web

### ISSUE THREAD

**Issue by fuelkoy** [react-navigation/react-navigation#12272]
### Current behavior

(The minimal repo is made purely with npx create-expo-app@latest without any changes)
The react-navigation [documentation](https://reactnavigation.org/docs/upgrading-from-6.x/#the-unmountonblur-option-is-removed-in-favor-of-poptotoponblur-in-bottom-tab-navigator-and-drawer-navigator) states:

The unmountOnBlur option is removed in favor of popToTopOnBlur in Bottom Tab Navigator and Drawer Navigator.
...
It's still possible to achieve the old behavior of unmountOnBlur by using the useIsFocused hook in the screen.

On web navigating with Drawer/bottom-tabs and using unmountOnBlur removed the previous screens from the DOM. Now every screen needs separately use useIsFocused hook to unmount them. This requires much more configuration than having single prop on the Drawer screenOptions

**Problems:**

1. Imagine having for example Drawer navigator with 20 screens and all being in the DOM at the same time just having style z-index: -1 on the inactive ones. Or having tabs that are hidden and the user has only couple of them. This makes web version with expo-router Drawer/bottom-tabs non-performant.
2. e2e testing (for example playwrifght) trusting on exact strings or labels will not work because they will notice x-number of same items from the other screens that are just hidden with style z-index: -1

We have actually such use case. At the moment we cannot upgrade to "expo": "~52.0.0".

**Example:**
First tab on the web page opening the first time
![Image](https://github.com/user-attachments/assets/e10c9c90-0126-4d48-802d-59826ca2eca4)

Opening the second tab
![Image](https://github.com/user-attachments/assets/587a14de-4dc7-4911-aca9-a36e29de0874)

Going back to the first tab
![Image](https://github.com/user-attachments/assets/d9187016-0b39-450a-85fb-a124b287bfdf)

Notice all the tab screens will remain in the DOM. Only the z-index value is changed.

(Thank you for the awesome library)

### Expected behavior

On web screens should not be left on DOM.

### Reproduction

https://github.com/fuelkoy/my-app

### Platform

- [ ] Android
- [ ] iOS
- [x] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [x] @react-navigation/bottom-tabs
- [x] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use
- Using **expo router**

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 7.0.0
| @react-navigation/bottom-tabs          | 7.0.0
| react-native-safe-area-context         | 4.12.0
| react-native-screens                   | 4.1.0
| react-native-gesture-handler           | 2.20.2
| react-native-reanimated                | 3.16.1
| react-native                           | 0.76.2
| expo                                   | 52.0.7
| npm or yarn                            | 10.2.3

**Comment by fuelkoy** [comment]
`@react-navigation/drawer` is not used in this repo.

Those versions are 7.0.0 because those come with `expo-router`.

**Comment by satya164** [comment]
There's `screenLayout` (https://reactnavigation.org/docs/navigator#screen-layout, https://reactnavigation.org/docs/group#screen-layout) to add a wrapper to multiple screens in one place like in options. It's unnecessary to add it to each screen separately. Just create a component like `<RenderIfFocused>` and use it as a wrapper in `screenLayout`.

**Comment by fuelkoy** [comment]
@satya164 Thank you very much for the clarification. The screen layout was a familiar concept to me but I did not connect to this for some reason.
Also thank you for explaining about the usage of .locator('visible=true'). I had not heard of it and will surely use it.

Thank you for the wonderful work you are making, (and for the kind and instructing responses)! ❤❤❤

**Comment by fuelkoy** [comment]
@satya164 On more question. When using expo-router should we then install react-navigation in addition? Also does using the functions from there (like for example useIsFocused hook in _layout.tsx to return null for all non focused screens) work 1-to-1 with expo-router?

**Comment by satya164** [comment]
@fuelkoy expo router declares a direct dependency instead of a peer dependency so no - though that means importing things from react navigation is not safe and won't work with all package managers.

`useIsFocused` should work fine.
