### ISSUE TITLE
React Navigation 7 Hides/Ignores Label for Material Top Tabs

### ISSUE THREAD

**Issue by nathanembaye** [react-navigation/react-navigation#12279]
### Current behavior

I have a problem with “@react-navigation/material-top-tabs” not showing labels. To begin with I have it nested within another material top tab. That previously worked fine so I know its not the issue. The problem is not apparent initially, but after doing some navigating, consistently on the 3rd or 4th navigation push the label gets hidden. In addition, when the label disappears the touch to switch tabs option is also broken, but I can still swipe to see the next tab.

https://github.com/user-attachments/assets/65657646-da6b-4212-82e2-494b1921f9f1

### Expected behavior

The expected behavior:

- Labels should always show
- Labels should be touchable to navigate to their respective tab

### Reproduction

https://github.com/nathanembaye/material_top_tab_bug

### Platform

- [ ] Android
- [x] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [x] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | ^7.0.0
| @react-navigation/bottom-tabs          | ^7.0.0
| @react-navigation/material-top-tabs    | ^7.0.6
| react-native-safe-area-context         | 4.12.0
| react-native-screens                   | ~4.1.0
| react-native-gesture-handler           | ~2.20.2
| react-native-reanimated                | ~3.16.1
| react-native                           | 0.76.2
| expo                                   | ^52.0.8
| node                                   | 23.2.0
| npm                            | 10.9.0

**Comment by nathanembaye** [comment]
> The versions mentioned in the issue for the following packages differ from the latest versions on npm:
> 
> * `@react-navigation/native` (found: `7.0.0`, latest: `7.0.3`)
> * `@react-navigation/bottom-tabs` (found: `7.0.0`, latest: `7.0.6`)
> 
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?

**The issues do still persist!**

**Comment by satya164** [comment]
Can you repro this after disabling new architecture?

**Comment by nathanembaye** [comment]
> Can you repro this after disabling new architecture?

This resolved it! Thanks @satya164!
