### ISSUE TITLE
Header jump when animation is set for bottom tab navigator

### ISSUE THREAD

**Issue by matinzd** [react-navigation/react-navigation#12273]
### Current behavior

The header will have an initial jump when animation is set for tab navigator. It doesn't matter if it's set to `fade` or `shift`.

https://github.com/user-attachments/assets/8435fe72-3fad-4e48-a27e-ce92c11d1ce9

### Expected behavior

The header should not flicker or have jumps.

https://github.com/user-attachments/assets/b13aeb15-2d52-4955-aeba-87ae63f6ac84

### Reproduction

https://github.com/matinzd/ReactNavigationHeaderFlicker

### Platform

- [x] Android
- [x] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [x] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 7.0.3
| @react-navigation/bottom-tabs          | 7.0.6
| @react-navigation/native-stack         | 7.0.3
| react-native-safe-area-context         | 4.14.0
| react-native-screens                   | 4.1.0
| react-native                           | 0.76.2
| node                                   | 20.10.0
| npm or yarn                            | 10.2.3

**Comment by matinzd** [comment]
Sorry for tagging. Any plans to take a look at this? @satya164

**Comment by satya164** [comment]
I can't repro this on JS stack, and the `headerTopInsetEnabled` prop for screens is always set to `true`. So it seems to be an issue with `react-native-screens`.

**Comment by matinzd** [comment]
Closing the issue as the problem is potentially in react native screens.

**Comment by satya164** [comment]
@matinzd right, so actually what `headerTopInsetEnabled` is set to isn't even relevant for iOS.
