### ISSUE TITLE
[v7] NativeStack setting contentStyle: { backgroundColor: 'transparent' } on all screens does not render the stack transparently

### ISSUE THREAD

**Issue by marklawlor** [react-navigation/react-navigation#12287]
### Current behavior

Reproduction with React Navigation 7: https://snack.expo.dev/@mwlawlor/blessed-indigo-apple

In React Navigation 7 setting

```
<Stack.Navigator
      initialRouteName="Home"
      screenOptions={{
        presentation: 'transparentModal',
        contentStyle: { backgroundColor: 'transparent' }
     }}
}>
```

Does not render the `<Stack />` transparently as it has a permanent background color
### Expected behavior

Reproduction with React Navigation 6: https://snack.expo.dev/@mwlawlor/native-stack-navigator

The behaviour in v7 is different than v6. In v7 it is no longer possible to create a fully transparent `<Stack />`

### Reproduction

https://snack.expo.dev/@mwlawlor/f33eef

### Platform

- [x] Android
- [x] iOS
- [x] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [x] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 7.0.3
| @react-navigation/native-stack         | 7.0.4

**Comment by NiuGuohui** [comment]
@satya164 Static configuration also has this problem.
