### ISSUE TITLE
[V7] useNavigation() hook returns wrong navigator

### ISSUE THREAD

**Issue by tux2nicolae** [react-navigation/react-navigation#12293]
### Current behavior

Based on this doc:

https://reactnavigation.org/docs/use-navigation?config=dynamic

If you have a screen like this one:

```
<RestaurantStack.Screen
  name="myName"
  component={MyScreen}
  options={{
    headerTitle: '',
    headerLeft: props => <MyBackButton {...props} />,
  }}
/>
```

and in MyBackButton component you are using

```
const navigation = useNavigation<NativeStackNavigationProp<any>>();

<SomeButton onPress={navigation.goBack} />
```

the navigation prop is not the right one for the current screen but instead for the parent navigator, not being able to call `goBack()`, as a workaround you need to do something similar to :

```
const MyScreen = ({navigation}: Props) => {
  useLayoutEffect(() => {
    navigation.setOptions({
      headerLeft: () => <MyBackButton onPress={navigation.goBack} />,
    });
  }, [navigation]);

  ...
}
```

In which case the navigator is the right one

### Expected behavior

You should be able to use `useNavigation()` hook from any component and the navigator returned by the hook should be for the current screen

### Reproduction

.

### Platform

- [x] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [x] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |7.0.4
| @react-navigation/bottom-tabs          |7.0.7
| @react-navigation/drawer               |7.0.7
| @react-navigation/material-top-tabs    |7.0.7
| @react-navigation/native-stack         |7.1.1
| react-native-safe-area-context         |4.14.0
| react-native-screens                   |4.3.0
| react-native-gesture-handler           |2.21.2
| react-native-reanimated                |3.16.2
| react-native-tab-view                  |4.0.3
| react-native                           |0.76.3

**Comment by robrechtme** [comment]
I have the same issue. See a minimal reproducible example [here](https://github.com/robrechtme/react-navigation-bug). The setup is a simple native stack inside of a tab navigator, with a custom back button:

```javascript
const CustomBackButton = () => {
  const navigation = useNavigation(); // <- This seems to resolve the bottom tab navigator, which is wrong
  return <Button title="Back" onPress={() => navigation.goBack()} />;
};

const RootStack = createBottomTabNavigator({
  screens: {
    Home: HomeScreen,
    More: {
      screen: createNativeStackNavigator({
        screenOptions: {
          headerLeft: () => <CustomBackButton />,
        },
        screens: {
          More: MoreScreen,
          MoreDetail: MoreDetailScreen,
        },
      }),
    },
  },
});

```



**Steps to reproduce**

1. Navigate to different tab
2. Navigate deeper into stack
3. Pressing back should pop from the stack, instead it goes to the previous tab

https://github.com/user-attachments/assets/fe7093b8-e792-4615-ad26-e878b940087a

**Comment by orel91** [comment]
I'm still facing the same issue with @react-navigation/native-stack 7.1.6
Also, label from props is undefined when setting a custom headerLeft component. Not sure why though

**Comment by satya164** [comment]
@orel91 I can't repro the issue after upgrading `@react-navigation/native-stack` to latest version in your repro.

**Comment by orel91** [comment]
@satya164 Ok, I compared my code with the code from the repo and by changing `headerLeft: HeaderLeft` to `headerLeft: (props) => <HeaderLeft {...props} />`, the navigation now works as expected.

Is it an issue or do we have to pass a function instead of a functional component?

Btw, thanks for the quick fix on the label!

**Comment by satya164** [comment]
@orel91 `headerLeft` accepts a function, not a component.

**Comment by iiagodias** [comment]
I updated my application and I stopped having this problem, we are losing all navigation.
