### ISSUE TITLE
[v7][Android][bottom-tabs] Disable ripple effect on tabBarItem press

### ISSUE THREAD

**Issue by ice-cap0** [react-navigation/react-navigation#12309]
### Current behavior

On Android, BottomTab TabBar Item press creates a material design ripple effect

### Expected behavior

i'd expect there to be an API to disable this

### Reproduction

N/A

### Platform

- [x] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [x] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-drawer-layout
- [ ] react-native-tab-view

### Environment

    "@react-navigation/bottom-tabs": "^7.1.1",
    "@react-navigation/material-top-tabs": "^7.0.16",
    "@react-navigation/native": "^7.0.11",
    "@react-navigation/native-stack": "^7.1.12",
    "@react-navigation/stack": "^7.0.16",

**Comment by ice-cap0** [comment]
yes the issue still exists

**Comment by Shivemmer** [comment]
is there any update on this ??

**Comment by satya164** [comment]
You can override the effect with your own/remove it by using `tabBarButton`:

```js
tabBarButton: ({ android_ripple, ...rest }) => <Pressable {...rest} />
```
