### ISSUE TITLE
Unimplemented components with RN New Architecture

### ISSUE THREAD

**Issue by dkhai19** [react-navigation/react-navigation#12318]
### Current behavior

![Image](https://github.com/user-attachments/assets/cae77943-c0df-48a8-bfcd-33c050234496)

### Expected behavior

Normal screen without display red area like that

### Platform

- [ ] Android
- [x] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [x] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-drawer-layout
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |
| @react-navigation/bottom-tabs          |
| @react-navigation/drawer               |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                |
| @react-navigation/native-stack         |
| react-native-drawer-layout             |
| react-native-tab-view                  |
| react-native-screens                   |
| react-native-safe-area-context         |
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native-pager-view                |
| react-native                           |
| expo                                   |
| node                                   |
| npm or yarn                            |

**Comment by dkhai19** [comment]
"@react-navigation/bottom-tabs": "^7.1.3",
    "@react-navigation/native": "^7.0.13",
    "@react-navigation/stack": "^7.0.18",
    "react": "18.3.1",
    "react-native": "0.76.3",
    "react-native-safe-area-context": "^4.14.0",
    "react-native-screens": "^4.3.0"

**Comment by dkhai19** [comment]
> Couldn't find version numbers for the following packages in the issue:
> 
> * `@react-navigation/native`
> * `@react-navigation/bottom-tabs`
> * `@react-navigation/drawer`
> * `@react-navigation/material-top-tabs`
> * `@react-navigation/stack`
> * `react-native-drawer-layout`
> * `react-native-tab-view`
> 
> Can you update the issue to include version numbers for those packages? The version numbers must match the format 1.2.3.

**Comment by dkhai19** [comment]
> Couldn't find version numbers for the following packages in the issue:
> 
> * `@react-navigation/native`
> * `@react-navigation/bottom-tabs`
> * `@react-navigation/drawer`
> * `@react-navigation/material-top-tabs`
> * `@react-navigation/stack`
> * `react-native-drawer-layout`
> * `react-native-tab-view`
> 
> Can you update the issue to include version numbers for those packages? The version numbers must match the format 1.2.3.

My dependencies:
"@react-navigation/bottom-tabs": "^7.1.3",
    "@react-navigation/native": "^7.0.13",
    "@react-navigation/stack": "^7.0.18",
    "react": "18.3.1",
    "react-native": "0.76.3",
    "react-native-gesture-handler": "^2.21.2",
    "react-native-reanimated": "^3.16.3",
    "react-native-safe-area-context": "^4.14.0",
    "react-native-screens": "^4.3.0"

**Comment by dkhai19** [comment]
Here is my link to repo: https://github.com/dkhai19/PetProject.git
I tried to downgrade react-native version to 0.75 but still didn't work. 

> Hey [@dkhai19](https://github.com/dkhai19)! Thanks for opening the issue. It seems that the issue doesn't contain a link to a repro, or the provided repro is not valid (e.g. broken link, private repo, code doesn't run etc.).
> 
> **The best way to get attention to your issue is to provide an easy way for a developer to reproduce the issue.**
> 
> You can provide a repro using any of the following:
> 
> * [Expo Snack](https://snack.expo.io)
> * [TypeScript Playground](https://www.typescriptlang.org/play)
> * GitHub repo under your username
> 
> A snack link is preferred since it's the easiest way to both create and share a repro. If it's not possible to create a repro using a snack, link to a GitHub repo under your username is a good alternative. **Don't link to a branch or specific file etc.** as it won't be detected.
> 
> Try to keep the repro as small as possible by narrowing down the minimal amount of code needed to reproduce the issue. **Don't link to your entire project or a project containing code unrelated to the issue.** See ["How to create a Minimal, Reproducible Example"](https://stackoverflow.com/help/minimal-reproducible-example) for more information.
> 
> You can edit your original issue to include a link to the repro, or leave it as a comment. **The issue will be closed automatically after a while** if you don't provide a valid repro.

**Comment by dkhai19** [comment]
I apologize for not clear it through, original version was 0.76 and I downgrade it to 0.75.x but I still got the same error.
I created new project, install react navigation, added some code and I got this issue.

**Comment by satya164** [comment]
so please share the repro with 0.76 instead of 0.75, though this is issue with your setup/environment rather than react navigation as we don't control the build configuration.

if you need a working starter project then use the template https://reactnavigation.org/docs/getting-started#starter-template

**Comment by dkhai19** [comment]
Thanks for your help Satya, I will try a new project
