### ISSUE TITLE
goBack is closing multiple fullScreenModal screens

### ISSUE THREAD

**Issue by santomegonzalo** [react-navigation/react-navigation#12317]
### Current behavior

On our app we have multiple screens with `presentation: 'fullScreenModal',` where Screen1 opens as a `fullScreenModal` and then it will open Screen2 on top of it... then to close Screen2 we just call `navigation.goBack()` and Screen2 will get closed but Screen1 will stay.

After updating to **react-navigation** v7 I started to noticed that doing exactly the same, `navigation.goBack()` will close all `fullScreenModal` screens. So based on my example. Screen1 and Screen2 will close when we decide to close Screen2 only using `navigation.goBack()`.

```
              <Stack.Group
                screenOptions={{
                  presentation: 'fullScreenModal',
                }}
              >
                <Stack.Screen
                  name="Screen1"
                  getComponent={() => Screen1}
                />
              </Stack.Group>
              <Stack.Group
                screenOptions={{
                  presentation: 'transparentModal',
                }}
              >
                <Stack.Screen
                  name="Screen2"
                  getComponent={() => Screen2}
                />
              <Stack.Group/>
```

### Expected behavior

The expected behaivor is to only close the latest `fullScreenModal` that the library has on their stack.

### Reproduction

https://norepo.com

### Platform

- [x] Android
- [x] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [x] @react-navigation/native-stack
- [ ] react-native-drawer-layout
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 7.0.9
| @react-navigation/bottom-tabs          | 7.0.14
| @react-navigation/stack                | 7.0.14
| @react-navigation/native-stack         | 7.1.10
| react-native-screens                   | 4.1.0
| react-native-safe-area-context         | 4.12.0
| react-native-gesture-handler           | 2.20.2
| react-native-reanimated                | 3.16.3
| react-native                           | 0.76.3
| expo                                   | 52.0.11

**Comment by KoenCa** [comment]
Also noticed this when upgrading from React navigation v6 to v7 when using `presentation: 'modal'` in a native stack navigator. Pressing back button on a second modal in the stack closes both modals.

**Comment by santomegonzalo** [comment]
Thank you @satya164 ... I will report this on `react-native-screen` and see whats going on... I found the logger really useful and I can see the following: 

![Image](https://github.com/user-attachments/assets/e3f824e2-92c8-4e58-8b40-4b106533baac)

And I'm not calling `pop` at all anywhere 🤔

**Comment by faljabi** [comment]
The same issue to popTo method.

**Comment by KoenCa** [comment]
After installing version 4.4.0 of react-native-screens I can confirm that it is fixed for me.

**Comment by MrXyfir** [comment]
@KoenCa Did you have to make any other changes to get it to work? Seems like I'm the only one who still has the issue on 4.4.0. I tried clearing out my cache, reinstalling, rebuilding, etc, but the issue persists.

**Comment by KoenCa** [comment]
> [@KoenCa](https://github.com/KoenCa) Did you have to make any other changes to get it to work? Seems like I'm the only one who still has the issue on 4.4.0. I tried clearing out my cache, reinstalling, rebuilding, etc, but the issue persists.

No, I only updated the `react-native-screens` library.

**Comment by celleb** [comment]
I am on `4.4.0` and updated to `4.5.0` and still the same problem

**Comment by MrXyfir** [comment]
Well at least I'm not the only one then. Welcome to the club @celleb 😢 I mainly just gave up and tried to rework my screens and how my app navigates so that it's less of an issue.

**Comment by KoenCa** [comment]
Which navigator stack are you using? I'm using the native stack and for me it works, so maybe its only fixed for the native stack and not for the other?

**Comment by MrXyfir** [comment]
I'm using `@react-navigation/stack`, so yeah maybe that could be it. I did try the `native-stack` version but I don't remember the outcome. Either it didn't work, or it required too many changes to use it so I gave up.

**Comment by celleb** [comment]
> Well at least I'm not the only one then. Welcome to the club @celleb 😢 I mainly just gave up and tried to rework my screens and how my app navigates so that it's less of an issue.

Actually, it was my mistake, I was using `popTo` to navigating to another screen from the modal. Which let to  back navigation from other screens closing the modal
