### ISSUE TITLE
[Static Navigation v7]Custom Header Back does not navigate to actual previous screen

### ISSUE THREAD

**Issue by MaganAnkur** [react-navigation/react-navigation#12313]
### Current behavior

I have a Parent Stack in which I have one **screen(Home)** and other **screen(SettingsStack**) is again a stack which has 2 screens `Setting` and `Profile`, when I navigate from `HomeScreen` to `SettingsStack` and then navigate further to `ProfileScreen` upon clicking back on `ProfileScreen`, it takes back to `HomeScreen` instead of `SettingScreen`.

```
import * as React from 'react';
import { Text, View, Pressable } from 'react-native';
import {
  createStaticNavigation,
  useNavigation,
} from '@react-navigation/native';
import { createNativeStackNavigator } from '@react-navigation/native-stack';
import { createBottomTabNavigator } from '@react-navigation/bottom-tabs';
import { Button } from '@react-navigation/elements';


const HeaderBack = ()=>{
  const navigation = useNavigation()
  return <Pressable onPress = {()=>{
    navigation.goBack()
  }}>
  <Text>Go Back</Text>
  </Pressable>
}

function SettingsScreen() {
  const navigation = useNavigation();

  React.useEffect(() => {
    console.log('SettingsScreen mounted');

    return () => console.log('SettingsScreen unmounted');
  }, []);

  return (
    <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
      <Text>Settings Screen</Text>
      <Button onPress={() => navigation.navigate('Profile')}>
        Go to Profile
      </Button>
    </View>
  );
}

function ProfileScreen() {
  const navigation = useNavigation();

  React.useEffect(() => {
    console.log('ProfileScreen mounted');

    return () => console.log('ProfileScreen unmounted');
  }, []);

  return (
    <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
      <Text>Profile Screen</Text>
    </View>
  );
}

function HomeScreen() {
  const navigation = useNavigation();

  React.useEffect(() => {
    console.log('HomeScreen mounted');

    return () => console.log('HomeScreen unmounted');
  }, []);

  return (
    <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
      <Text>Home Screen</Text>
      <Button onPress={() => navigation.push('Settings')}>
        Go to Settings
      </Button>
    </View>
  );
}


const SettingsStack = createNativeStackNavigator({
   screenOptions: {
    headerLeft: HeaderBack,
  },
  screens: {
    Settings: {
      screen: SettingsScreen,
      options : {
        headerShown : false,
      }
      },
    Profile: ProfileScreen,
  },
});

const HomeStack = createNativeStackNavigator({
  screenOptions : {
headerShown : false
  },
  screens: {
    Home: HomeScreen,
    Settings : SettingsStack
  },
});



const Navigation = createStaticNavigation(HomeStack);

export default function App() {
  return <Navigation />;
}

```

### Expected behavior

Back Button on `ProfileScreen` should take back to `SettingsScreen` instead of `HomeScreen`

### Reproduction

https://snack.expo.dev/@maganankur/navigation-lifecycle

### Platform

- [x] Android
- [x] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [x] @react-navigation/native-stack
- [ ] react-native-drawer-layout
- [ ] react-native-tab-view

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 7.0.13
| @react-navigation/bottom-tabs          | 7.1.3
| @react-navigation/native-stack         | 7.1.14
| react-native-screens                   | 4.1.0
| react-native-safe-area-context         | 0.3.2
| react-native-gesture-handler           | 2.21.2
| react-native-reanimated                | 3.16.2
| react-native                           | 0.76.1
| node                                   | 22.1.0
| npm or yarn                            | npm

**Comment by satya164** [comment]
`headerLeft` accepts a function returning a react element, not a component like you're passing https://reactnavigation.org/docs/native-stack-navigator#headerleft

**Comment by MaganAnkur** [comment]
Thanks @satya164 for your swift response, for other visibility even if I change `headerLeft` to a function this issue was still there on below version: 
`@react-navigation/native-stack: ^7.0.3`
`@react-navigation/native: ^7.0.3`

after upgrading it to 

`@react-navigation/native: ^7.0.13`
`@react-navigation/native-stack: ^7.1.14`

it resolves the issue.

**Note: `headerLeft` should be used as function**
