### ISSUE TITLE
Drawer issue - when opened using hamburger - links do not work

### ISSUE THREAD

**Issue by belspirit** [react-navigation/react-navigation#12329]
### Current behavior

On the real Android Device Samsung Galaxy S9:

When opening Drawer by swiping, the links work - they redirect to the specified screens. But if you open Drawer by clicking on hamburger - the links do not work. There is a visualization of the touch, but there is no redirection.

### Expected behavior

No matter how the Drawer is opened, swiping, or clicking on the hamburger, the links must lead to screens.

### Reproduction

https://snack.expo.dev/@belspirit/drawer-test

### Platform

- [x] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [x] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-drawer-layout
- [ ] react-native-tab-view

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
|expo | "~52.0.18"|
|react | "18.3.1"|
|react-native | "0.76.5"|
|expo-status-bar | "~2.0.0"|
|react-native-screens | "~4.1.0"|
|react-native-reanimated | "~3.16.1"|
|@react-navigation/drawer | "^7.0.19"|
|@react-navigation/native | "^7.0.13"|
|@react-navigation/elements | "^2.2.4"|
|react-native-gesture-handler | "~2.20.2"|
|react-native-safe-area-context | "4.12.0"|
|@react-native-masked-view/masked-view | "0.3.2"|
| npx expo -v                               |"0.22.5"|
| node -v                                   |"22.12.0"|
| npm -v                            |"10.9.0"|

**Comment by david-phx** [comment]
I can confirm that I am experiencing the same issue with Expo version 52.0.18 and React Native 0.76.5. Works fine on Expo 52.0.17 and React Native 0.76.3.

**Comment by crisemcon** [comment]
same for me

**Comment by Sharpen-Cjh** [comment]
me too

**Comment by dmohler20** [comment]
So I was able to get around it by instead of using the drawer item, i used a touchable opacity, and then instead of using onPress i used onPressIn.  While not ideal, it seems to be working as it should this way.
