### ISSUE TITLE
@react-navigation/core createNavigatorFactory any types

### ISSUE THREAD

**Issue by ChromeQ** [react-navigation/react-navigation#12320]
### Current behavior

In the latest version of @react-navigation/core (v7.3.0) the types of createNavigatorFactory are `any`
https://github.com/react-navigation/react-navigation/blob/%40react-navigation/core%407.3.0/packages/core/src/createNavigatorFactory.tsx

This was not the case in the latest v6 version (v6.4.17) so I believe this is a regression.
https://github.com/react-navigation/react-navigation/blob/%40react-navigation/core%406.4.17/packages/core/src/createNavigatorFactory.tsx

### Expected behavior

The types should be preserved and allows the types to be known when using navigators such as `createMaterialBottomTabNavigator` from `react-native-paper/react-navigation` as they did in v6

### Reproduction

https://github.com/react-navigation/react-navigation/blob/%40react-navigation/core%407.3.0/packages/core/src/createNavigatorFactory.tsx

### Platform

- [x] Android
- [x] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-drawer-layout
- [ ] react-native-tab-view

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/core               | 7.3.0
| @react-navigation/native               | 7.0.13
| @react-navigation/drawer               | 7.0.19
| @react-navigation/native-stack         | 7.1.14
| react-native-screens                   | 4.1.0
| react-native-safe-area-context         | 4.12.0
| react-native-gesture-handler           | 2.20.2
| react-native-reanimated                | 3.16.3
| react-native                           | 0.76.3
| expo                                   | 52.0.14
| node                                   | 20.13.1
| npm or yarn                            | yarn@1.22.22

**Comment by ChromeQ** [comment]
This issue was highlighted when raising this bug in `react-native-paper` - https://github.com/callstack/react-native-paper/issues/4572

**Comment by satya164** [comment]
This is a breaking change. The factory needs to be wrapped in a function annotated with appropriate types so automatic type inference can work: https://reactnavigation.org/docs/custom-navigators#type-checking-navigators (example https://github.com/react-navigation/react-navigation/blob/29813807ea6723e6bc4536fd0906fa637954eb35/packages/bottom-tabs/src/navigators/createBottomTabNavigator.tsx#L77-L98)

So the types on `createNavigatorFactory` aren't used anymore and are not important. `react-native-paper` needs to update the types.

**Comment by ChromeQ** [comment]
This is a bit disappointing for react-navigation to deprecate material bottom tabs and tell us it moved to react-native-paper when the latest version of react-native-paper has a dependency on v6 of react-navigation/native.
https://github.com/callstack/react-native-paper/blob/9162a1fdf4e97c0669de8a8fa2057d8cfbe2e728/package.json#L61C6-L61C30

So at this time there is no way to use material-bottom-tabs with react-navigation v7?

**Comment by satya164** [comment]
It was moved almost 2 years ago during v6 and the package was marked as deprecated. It's only mentioned in v7 upgrade guide as a reminder since the v7 version of the package doesn't exist, but it's not a part of v7 release.

The point of moving is that maintenance is offloaded, so in the end it's up to paper to keep their integration uptodate. I'd suggest sending pull request to paper and track updates there instead.

> So at this time there is no way to use material-bottom-tabs with react-navigation v7?

The alternative approach is using `@react-navigation/bottom-tabs` and using paper's `BottomNavigationBar` as the tab bar as custom tab bar which should have proper types. Here is an example https://callstack.github.io/react-native-paper/docs/components/BottomNavigation/BottomNavigationBar#usage
