### ISSUE TITLE
Params are erased from SubStack component after navigation

### ISSUE THREAD

**Issue by bradchristensen** [react-navigation/react-navigation#12330]
### Current behavior

The change made in PR https://github.com/react-navigation/react-navigation/pull/12264 has broken some of the navigation between nested screens in our app and I'm not sure if this is an intentional or unintentional breakage - but if it's intentional I'm not sure how I'm supposed to work around it!

I was able to confirm this by bisecting the versions and found it was working correctly in `@react-navigation/core` 7.0.2 and prior, and then broken in 7.0.3 onwards due to the change to the SceneView file in that PR.

The basic steps to reproduce are:

1. Navigate from a root substack to a screen within a child substack, passing through some params
1. Navigate to another screen within the child substack, passing through the same params (`route.params`)

Initially I thought this change caused the params passed into the screen within the child substack to be erased, but after I created a minimal repro I found that this was not the case - the params are passed to the second child substack screen correctly, but the issue is that the params passed into the _child SubStack_ are erased when navigating between screens within the SubStack.

The reason we require those params to be available in the SubStack is because in our app, we wrap the entire SubStack in a React Context, and the params are required for the behaviour of the context provider (for example: start and maintain a BLE connection while the context is in scope).

If this change was made intentionally, I'm curious to understand why, and what the best practices are for structuring our app to work around it. In our app, we could probably capture the initial params to make sure they don't get lost when the SubStack screen changes, but this seems counter-intuitive and unexpected from a DX perspective.

### Expected behavior

Ideally the previous behaviour should be restored: i.e. the params that were initially passed into the SubStack should not be erased, and should remain available when navigating between screens within the SubStack.

### Reproduction

https://snack.expo.dev/nd7Vv7SY4cTEPXjqZlYJu

### Platform

- [x] Android
- [x] iOS
- [x] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [x] @react-navigation/stack
- [x] @react-navigation/native-stack
- [ ] react-native-drawer-layout
- [ ] react-native-tab-view

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 7.0.13  |
| @react-navigation/native-stack         | 7.1.14  |
| react-native-screens                   | 4.3.0   |
| react-native-safe-area-context         | 5.0.0   |
| react-native-gesture-handler           | 2.21.2  |
| react-native-reanimated                | 3.16.4  |
| react-native                           | 0.76.5  |
| expo                                   | 52.0.17 |
| node                                   | 22.6.0  |
| yarn                                   | 4.5.3   |

**Comment by bradchristensen** [comment]
> Couldn't find version numbers for the following packages in the issue:
> 
> * `@react-navigation/stack`
> 
> Can you update the issue to include version numbers for those packages? The version numbers must match the format 1.2.3.

Not applicable

**Comment by satya164** [comment]
> The reason we require those params to be available in the SubStack is because in our app, we wrap the entire SubStack in a React Context, and the params are required for the behaviour of the context provider (for example: start and maintain a BLE connection while the context is in scope).

Can you explain more what exactly this is doing? Why does BLE connection rely on params passed to the navigator? What's the exact information that you're relying on?

> but if it's intentional I'm not sure how I'm supposed to work around it!

You haven't explained what's the information you need for your use case, so I can't suggest a solution.

**Comment by bradchristensen** [comment]
Sorry, I was just trying to boil it down to the minimum repro for clarity so I omitted the specifics around how our app is working 🙂 

The structure of our app looks more like:

```tsx
<Stack.Navigator>
  <Stack.Screen name="DeviceList" component={DeviceList} />
  <Stack.Screen name="DeviceContext" component={DeviceContextStack} />
</Stack.Navigator>
```

where DeviceContextStack is defined as:

```tsx
function DeviceContextStack({ route }) {
  // Accessing the params here is the part that's not working anymore
  const { peripheralId } = route.params;

  return (
    <BleConnectionProvider peripheralId={peripheralId}>
      <SubStack.Navigator>
        {
        // While any of the below screens are mounted, they rely on having a
        // persistent BLE connection to the device identified by
        // `peripheralId`. The context means we can establish and keep
        // the connection open without disconnects/reconnects when
        // navigating between screens.
        }
        <SubStack.Screen name="DeviceInfo" component=... />
        <SubStack.Screen name="DeviceNetworkStatus" component=... />
        <SubStack.Screen name="ReadWriteCharacteristics" component=... />
        <SubStack.Screen name="SetupDevice" component=... />
      </SubStack.Navigator>
    </BleConnectionProvider>
  );
}
```

and BleConnectionProvider is a React context provider, something like:

```tsx
function BleConnectionProvider({ peripheralId }) {
  useEffect(() => {
    // While this provider is mounted, we establish and maintain a
    // BLE connection to device `peripheralId`
    
    return () => {
      // And clean up the connection when the context provider is
      // unmounted
    };
  }, []);

  return (
    <BleConnectionContext.Provider value={provider}>
      {children}
    </BleConnectionContext.Provider>
  );
}
```

**Comment by bradchristensen** [comment]
> Also in your snack you're logging route.params.id in ChildStack, but that screen never received this param.

Maybe this is where my understanding is breaking down - is there another way I'm supposed to pass that param through?

**Comment by satya164** [comment]
I don't think I understand. If this is similar to what your snack shows, and in this case, you passed a param to a screen nested inside `DeviceContextStack` (e.g. `navigate('DeviceContext', { screen: 'DeviceInfo', params: { peripheralId }})`, that param was not available to the `DeviceContext` like in your example.

This code never worked:

> ```js
> // Accessing the params here is the part that's not working anymore
> const { peripheralId } = route.params;
> ```

This code would've received `undefined` earlier, if not throw an error like now - though neither result in anything usable.

And if you're explicitly passing a param to `DeviceContext` (e.g. `navigate('DeviceContext', { peripheralId })`, then you can still access those params.

**Comment by satya164** [comment]
> Maybe this is where my understanding is breaking down?

You're saying this change broke the code in your app, but this param was never available even before this change.

> is there another way I'm supposed to pass that param through

Sure, you can always pass that param explicitly to the screen containing the stack:

```js
navigate('DeviceContext', { peripheralId, /* anything else like screen: 'DeviceInfo' */ })
```

**Comment by bradchristensen** [comment]
> Sure, you can always pass that param explicitly to the screen containing the stack - same as any other screen:
> 
> navigate('DeviceContext', { peripheralId, /* anything else like screen: 'DeviceInfo' */ })

Ahh! This is what I was missing, thanks. I didn't realise this was possible because our TypeScript types didn't allow it 🤦 

> This code never worked:
> 
> > // Accessing the params here is the part that's not working anymore
> > const { peripheralId } = route.params;
> 
> This code would've received `undefined` earlier, if not throw an error like now - though neither result in anything usable.
> 
> And if you're explicitly passing a param to `DeviceContext` (e.g. `navigate('DeviceContext', { peripheralId })`, then you can still access those params.

Whoops - I copied over that part incorrectly, sorry - although as per that snack, it causes a crash either way since `route.params` is undefined now. It should have been written as `route.params.params.id`, which is accessing the child screen's params. On the subsequent navigation to the second child screen, `route.params` becomes undefined. FWIW here's a repro where I've rolled back the `@react-navigation/core` version to 7.0.0 and corrected the log line, and it doesn't throw an error: https://snack.expo.dev/JmL8Gn_l5YMsYLLwQLlNj - however, now I see what I was doing wrong, I can't think of any good use case for retaining the previous behaviour so please feel free to close this.

Thanks, I really appreciate your help investigating this 🙂
