### ISSUE TITLE
`useNavigation` results differ between v6 and v7 when used inside a nested navigator within a DrawerNavigator

### ISSUE THREAD

**Issue by 1natsu172** [react-navigation/react-navigation#12354]
### Current behavior

I'm encountering an issue while upgrading app from v6(Expo 51) to v7(Expo 52).

## Details

The app has a structure where a `NativeStackNavigator` is nested inside a `DrawerNavigator`. The `screenOptions` of the nested `NativeStackNavigator` includes a `headerLeft` option, where I use `useNavigation` within a custom component.  

The result of `useNavigation` inside `headerLeft` differs between v6 and v7. In v6, it returned the navigation object of the `NativeStackNavigator` itself, but in v7, it returns the navigation object of the parent `DrawerNavigator`.

#### react-navigation v6(with Expo51)

https://snack.expo.dev/@1natsu/reproduction-of-usenavigation-for-nested-drawer-navigator-v6

In v6, the navigation of the Stack itself was returned in all cases, including native platforms.

> ![Image](https://github.com/user-attachments/assets/d7497d39-8b4d-4f8c-b40b-ff944adad78d)
``` 
Web: "Stack"
Android: "Stack"
iOS: "Stack"
```

#### react-navigation v7(with Expo52)

https://snack.expo.dev/@1natsu/reproduction-of-usenavigation-for-nested-drawer-navigator

In v7, the Drawer navigation is returned on native platforms.

> ![Image](https://github.com/user-attachments/assets/36f62db3-9869-4140-beac-15b7892b4cc0) 
``` 
Web: "Stack"
Android: "Drawer"
iOS: "Drawer"
```

### Expected behavior

I expect the same behavior as in v6. The navigation object should be that of the NativeStackNavigator itself, not the parent DrawerNavigator.

### Reproduction

https://snack.expo.dev/@1natsu/reproduction-of-usenavigation-for-nested-drawer-navigator

### Platform

- [x] Android
- [x] iOS
- [x] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [x] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [x] @react-navigation/native-stack
- [ ] react-native-drawer-layout
- [ ] react-native-tab-view

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |^7.0.0
| @react-navigation/bottom-tabs          |^7.0.0
| @react-navigation/drawer               |^7.0.18
| @react-navigation/material-top-tabs    |7.0.18
| @react-navigation/stack                |^7.0.18
| @react-navigation/native-stack         |^7.1.14
| react-native-tab-view                  |^4.0.5
| react-native-screens                   |~4.1.0
| react-native-safe-area-context         |4.12.0
| react-native-gesture-handler           |~2.20.2
| react-native-reanimated                |~3.16.1
| react-native-pager-view                |6.5.1
| react-native                           | 0.76.5
| expo                                   | ~52.0.19
| node                                   | 20.11.0
| ~npm or yarn~ bun                            | 1.1.40

**Comment by satya164** [comment]
`headerLeft` accepts a function returning a react element, not a component:

```js
headerLeft: () => <MyGoBack />
```

https://reactnavigation.org/docs/native-stack-navigator/#headerleft

**Comment by 1natsu172** [comment]
Thank you. It is true that if I make it an element, the result will be the same as v6.

**Comment by iiagodias** [comment]
Same problem here, I don't use headerLeft @satya164

**Comment by 1natsu172** [comment]
@iiagodias  I think your problem is different from this Issue. In your repro you have different navigators assigned to different screens. And direct navigation to the child navigator is no longer possible with react-navigation v7. 

You need to use `navigationInChildEnabled` or `navigation.navigate(“ProfileStack”, { screen: 'Search' })` following the upgrade docs. (https://reactnavigation.org/docs/upgrading-from-6.x/#changes-to-the-navigate-action)


```ts
export default function App() {
  return (
    <NavigationContainer navigationInChildEnabled>
      <RootStack.Navigator initialRouteName='Tab'>
...
OR
...
<Button
      onPress={() => {
       navigation.navigate("ProfileStack", {screen:'Search'})
      }}>
      Go Search!
</Button>
```
