### ISSUE TITLE
Does the new navigation not support the animationEnabled attribute?

### ISSUE THREAD

**Issue by Qy742698** [react-navigation/react-navigation#12353]
### Current behavior

Does the new navigation not support the animationEnabled attribute?

### Expected behavior

import Example from './page'
import { createStackNavigator } from '@react-navigation/stack'

const TestStack = createStackNavigator()
// screenOptions={{
//     animationEnabled:false
//   }}
export const TestScreen = () => {
    return (
        <TestStack.Navigator
            screenOptions={{
                animationEnabled: true
            }}
        >
            <TestStack.Screen name="page1" component={Example} />
            <TestStack.Screen name="page2" component={Example} />
            <TestStack.Screen name="page3" component={Example} />
        </TestStack.Navigator>
    )
}

### Reproduction

import Example from './page' import { createStackNavigator } from '@react-navigation/stack'  const TestStack = createStackNavigator() // screenOptions={{ //     animationEnabled:false //   }} export const TestScreen = () => {     return (         <TestStack.Navigator             screenOptions={{                 animationEnabled: true             }}         >             <TestStack.Screen name="page1" component={Example} />             <TestStack.Screen name="page2" component={Example} />             <TestStack.Screen name="page3" component={Example} />         </TestStack.Navigator>     ) }

### Platform

- [ ] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [x] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-drawer-layout
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |
| @react-navigation/bottom-tabs          |
| @react-navigation/drawer               |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                |
| @react-navigation/native-stack         |
| react-native-drawer-layout             |
| react-native-tab-view                  |
| react-native-screens                   |
| react-native-safe-area-context         |
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native-pager-view                |
| react-native                           |
| expo                                   |
| node                                   |
| npm or yarn                            |

**Comment by Qy742698** [comment]
I use the navigation library. Currently, the disappear function is automatically triggered after the second jump. As a result, the previous page of the map component is destroyed. After the page is returned, the interface does not respond.

**Comment by satya164** [comment]
https://reactnavigation.org/docs/upgrading-from-6.x#animationenabled-option-is-removed-in-favor-of-animation-option-in-stack-navigator
