### ISSUE TITLE
[v7] navigation.navigate not typed

### ISSUE THREAD

**Issue by haivle** [react-navigation/react-navigation#12359]
### Current behavior

```tsx
// navigation/root.ts
const RootStack = createNativeStackNavigator({
  initialRouteName: 'Launch',
  screenOptions: {
    headerShown: false,
  },
  screens: {
    BottomTabs,
    Launch: LaunchScreen,
    Details: DetailsScreen,
    NotFound: NotFoundSceen,
  },
}

export const RootNavigation = createStaticNavigation(RootStack);

export type RootStackParamList = StaticParamList<typeof RootStack>;

// navigation/index.d.ts
import { RootStackParamList } from './root';

declare global {
  namespace ReactNavigation {
    type RootParamList = RootStackParamList;
  }
}

// LaunchScreen.tsx
type Props = StaticScreenProps<undefined>;

export const LaunchScreen = (props: Props) => {
  const navigation = useNavigation();
  useEffect(() => {
    navigation.navigate('BottomTabs');
  }, []);

  return (
      <Text>Loading</Text>
  );
};
```

navigation.navigate throw error
<img width="821" alt="Image" src="https://github.com/user-attachments/assets/2690f185-8d6d-41be-8060-dd0a640645b4" />

### Expected behavior

navigation.navigate('BottomTabs') should not throw any error

### Reproduction

private

### Platform

- [x] Android
- [x] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [x] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [x] @react-navigation/stack
- [x] @react-navigation/native-stack
- [ ] react-native-drawer-layout
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 7.0.14 |
| @react-navigation/bottom-tabs          | 7.2.0 |
| @react-navigation/stack                | 7.1.1 |
| @react-navigation/native-stack         | 7.2.0 |
| react-native                           | 0.76.5 |
| expo                                   | 52.0.19 |
| node                                   | 20.17.0
| yarn                            | 4.3.1 |

**Comment by satya164** [comment]
You need to use `interface RootParamList extends RootStackParamList {}` for declaration merging to work. `type RootParamList = RootStackParamList;` won't work.
