### ISSUE TITLE
Suspected bug in push behavior for dynamic routes

### ISSUE THREAD

**Issue by pebeasley** [react-navigation/react-navigation#12350]
### Current behavior

When using dynamic routes, if pushing a new route to the same location and changing the ID, the routing stack does not actually push a new route.  It instead seems to just replace the existing route on the stack.  This results in breaking the back behavior for a Stack navigator.

### Expected behavior

Pushing a new dynamic route, when already on the same dynamic route, should just add a new screen to the stack.

### Reproduction

https://github.com/pebeasley/dynamic-routing-issue

### Platform

- [x] Android
- [x] iOS
- [x] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [x] @react-navigation/stack
- [x] @react-navigation/native-stack
- [ ] react-native-drawer-layout
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native              7.0.0|
| @react-navigation/stack               
|
| @react-navigation/native-stack         |
| react-native-screens                   4.1.0|
| react-native-safe-area-context         |
| react-native                           |
| expo                                   |
| node                                   |
| npm or yarn                            |

 https://github.com/user-attachments/assets/4c8f9383-ae14-4618-9d53-692e5126d143

**Comment by satya164** [comment]
Please open Expo Router related issues in Expo's repo.
