### ISSUE TITLE
Back Button Closes the App Instead of Navigating to the Previous Screen on Android

### ISSUE THREAD

**Issue by raghav-phonebox** [react-navigation/react-navigation#12366]
### Current behavior

When pressing the back button on Android, the app closes unexpectedly instead of navigating to the previous screen.

I have tested the issue by creating two separate apps using the following commands:
 - `npx create-expo-app@latest`
 - `npx create-expo-app@latest --template react-navigation/template`

In both implementations, the back button works as expected and navigates to the previous screen.

I upgraded Expo to version 51 (from version 50) and updated the necessary packages, but the issue persists. I have attempted several solutions over the past few days, including upgrading React Navigation to version 7, but the problem remains unresolved.

At this point, I am unsure of what else to try.

Here is the code I have implemented inside App.tsx:

```ts
import { NavigationContainer } from '@react-navigation/native';
import { createNativeStackNavigator } from '@react-navigation/native-stack';
import React from 'react';
import { Button, Text, View } from 'react-native';

const Stack = createNativeStackNavigator();

const ScreenOne = (props) => {
  return (
    <View
      style={{ flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: 'white' }}
    >
      <Text>Screen One</Text>
      <Button
        onPress={() => {
          props.navigation.navigate('ScreenTwo');
        }}
        title="Go To Screen Two"
      />
    </View>
  );
};

const ScreenTwo = () => {
  return (
    <View
      style={{ flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: 'white' }}
    >
      <Text>Screen Two</Text>
    </View>
  );
};

export default function App() {
  return (
    <NavigationContainer>
      <Stack.Navigator>
        <Stack.Screen name="ScreenOne" component={ScreenOne} />
        <Stack.Screen name="ScreenTwo" component={ScreenTwo} />
      </Stack.Navigator>
    </NavigationContainer>
  );
}

```
I also tried adding `import 'react-native-gesture-handler';` (recommendation from one of the solutions)

Here are the packages I am using (Note: These versions are after updating to expo v51)

| Dependency                                         | Version   |
|----------------------------------------------------|-----------|
| `@dotlottie/react-player`                          | ^1.6.19   |
| `@expo/metro-runtime`                              | ~3.2.3    |
| `@expo/vector-icons`                               | ^14.0.3   |
| `@expo/webpack-config`                             | ^19.0.1   |
| `@lottiefiles/react-lottie-player`                 | ^3.5.4    |
| `@react-native-async-storage/async-storage`        | 1.23.1    |
| `@react-native-community/datetimepicker`          | 8.0.1     |
| `@react-native-picker/picker`                      | 2.7.5     |
| `@react-navigation/bottom-tabs`                    | ^6.5.20   |
| `@react-navigation/material-top-tabs`              | ^6.6.14   |
| `@react-navigation/native`                         | ^6.1.17   |
| `@react-navigation/native-stack`                   | ^6.9.26   |
| `@reduxjs/toolkit`                                 | ^2.2.2    |
| `@svgr/webpack`                                    | ^8.1.0    |
| `axios`                                            | ^1.6.8    |
| `babel-plugin-module-resolver`                     | ^5.0.2    |
| `crisp-sdk-web`                                    | ^1.0.25   |
| `expo`                                             | ^51.0.0   |
| `expo-apple-authentication`                        | ~6.4.2    |
| `expo-auth-session`                                | ~5.5.2    |
| `expo-build-properties`                            | ~0.12.5   |
| `expo-checkbox`                                    | ~3.0.0    |
| `expo-clipboard`                                   | ~6.0.3    |
| `expo-crypto`                                      | ~13.0.2   |
| `expo-dev-client`                                  | ~4.0.29   |
| `expo-file-system`                                 | ~17.0.1   |
| `expo-font`                                        | ~12.0.10  |
| `expo-image-picker`                                | ~15.0.7   |
| `expo-linear-gradient`                             | ~13.0.2   |
| `expo-linking`                                     | ~6.3.1    |
| `expo-print`                                       | ~13.0.1   |
| `expo-secure-store`                                | ~13.0.2   |
| `expo-sharing`                                     | ~12.0.1   |
| `expo-splash-screen`                               | ~0.27.7   |
| `expo-status-bar`                                  | ~1.12.1   |
| `expo-web-browser`                                 | ~13.0.3   |
| `lottie-react-native`                              | 6.7.0     |
| `moment`                                           | ^2.30.1   |
| `patch-package`                                    | ^8.0.0    |
| `react`                                            | 18.2     |
| `react-dom`                                        | 18.2.0   |
| `react-google-autocomplete`                        | ^2.7.3    |
| `react-helmet`                                     | ^6.1.0    |
| `react-native`                                     | 0.74.5    |
| `react-native-crisp-chat-sdk`                      | ^0.14.4   |
| `react-native-dotenv`                              | ^3.4.11   |
| `react-native-dropdown-picker`                     | ^5.4.6    |
| `react-native-gesture-handler`                     | ~2.16.1   |
| `react-native-google-places-autocomplete`          | ^2.5.6    |
| `react-native-linear-gradient`                     | ^2.8.3    |
| `react-native-pager-view`                          | 6.3.0     |
| `react-native-paper`                               | ^5.12.3   |
| `react-native-paper-dates`                         | ^0.22.5   |
| `react-native-picker-select`                       | ^9.3.1    |
| `react-native-progress`                            | ^5.0.1    |
| `react-native-reanimated`                          | ~3.10.1   |
| `react-native-safe-area-context`                   | 4.10.5    |
| `react-native-screens`                             | 3.31.1   |
| `react-native-svg`                                 | 15.2.0    |
| `react-native-tab-view`                            | ^3.5.2    |
| `react-native-uuid`                                | ^2.0.3    |
| `react-native-vector-icons`                        | ^10.0.3   |
| `react-native-web`                                 | ~0.19.6   |
| `react-native-webview`                             | 13.8.6   |
| `react-redux`                                      | ^9.1.0    |
| `uuid`                                             | ^11.0.3   |

I have included the current behaviour video.

Please let me know what else could I provide to help finding the cause.

## I am unable to reproduce this issue in new project.

https://github.com/user-attachments/assets/ee43b4a0-d25f-4917-b7b0-4d2c2bed358c

### Expected behavior

Pressing back button should take user to previous screen.

### Reproduction

https://github.com/raghav-phonebox/navigation-test

### Platform

- [x] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [x] @react-navigation/native-stack
- [ ] react-native-drawer-layout
- [ ] react-native-tab-view

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |  ^6.1.17
| @react-navigation/bottom-tabs          | ^6.5.20
| @react-navigation/material-top-tabs    | ^6.6.14
| @react-navigation/native-stack         | ^6.9.26
| react-native-tab-view                  | ^3.5.2
| react-native-screens                   | 4.10.5
| react-native-safe-area-context         | 4.10.5
| react-native-gesture-handler           | ~2.16.1
| react-native-reanimated                | ~3.10.1
| react-native-pager-view                | 6.3.0
| react-native                           | "0.74.5
| expo                                   | ^51.0.0
| node                                   | 20.15.1
| npm                           | 10.8.2

**Comment by raghav-phonebox** [comment]
Yes, issue still exists, even if I upgrade to the latest version. I believe it could be a React Native configuration issue, but can not figure out what.

**Comment by raghav-phonebox** [comment]
Finally I was able to reproduce this.

Not an issue with React navigation, it was due to `"react-native-crisp-chat-sdk"` package.

In case, you face this issue and can not figure out who is the culprit, you can follow what I did to find the culprit, (or suggest me a better way)

1. Duplicate the entire project.
2. REMOVE everything EXCEPT the bare minimum required to run the project. 
3. Remove all imports from other config files.
4. remove all but base minimum required packages from the list (package.json)
5. Run `npm install`
6. Run `npm run android`
7. If the app works as expected, add 2 or 3 npm packages from old package.json file and run `npm install` -> `npm run android` -> TEST
8. Keep repeating previous step until you find the culprit. 
9. If no culprit is found, start updating config files with import from original files, one by one and test after every change.
10. To keep testing simple, add the following code inside your App.tsx file or index.tsx file. (Entry file)
```js
import { NavigationContainer } from '@react-navigation/native';
import { createNativeStackNavigator } from '@react-navigation/native-stack';
import React from 'react';
import { Button, Text, View } from 'react-native';

const Stack = createNativeStackNavigator();

const ScreenOne = (props) => {
  return (
    <View
      style={{ flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: 'white' }}
    >
      <Text>Screen One</Text>
      <Button
        onPress={() => {
          props.navigation.navigate('ScreenTwo');
        }}
        title="Go To Screen Two"
      />
    </View>
  );
};

const ScreenTwo = () => {
  return (
    <View
      style={{ flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: 'white' }}
    >
      <Text>Screen Two</Text>
    </View>
  );
};

export default function App() {
  return (
    <NavigationContainer>
      <Stack.Navigator>
        <Stack.Screen name="ScreenOne" component={ScreenOne} />
        <Stack.Screen name="ScreenTwo" component={ScreenTwo} />
      </Stack.Navigator>
    </NavigationContainer>
  );
}
```

I am closing this, I hope this comment will help someone one day.

**Comment by Uuga-Chaka** [comment]
> Finally I was able to reproduce this.
> 
> Not an issue with React navigation, it was due to `"react-native-crisp-chat-sdk"` package.
> 
> In case, you face this issue and can not figure out who is the culprit, you can follow what I did to find the culprit, (or suggest me a better way)
> 
> 1. Duplicate the entire project.
> 2. REMOVE everything EXCEPT the bare minimum required to run the project.
> 3. Remove all imports from other config files.
> 4. remove all but base minimum required packages from the list (package.json)
> 5. Run `npm install`
> 6. Run `npm run android`
> 7. If the app works as expected, add 2 or 3 npm packages from old package.json file and run `npm install` -> `npm run android` -> TEST
> 8. Keep repeating previous step until you find the culprit.
> 9. If no culprit is found, start updating config files with import from original files, one by one and test after every change.
> 10. To keep testing simple, add the following code inside your App.tsx file or index.tsx file. (Entry file)
> 
> import { NavigationContainer } from '@react-navigation/native';
> import { createNativeStackNavigator } from '@react-navigation/native-stack';
> import React from 'react';
> import { Button, Text, View } from 'react-native';
> 
> const Stack = createNativeStackNavigator();
> 
> const ScreenOne = (props) => {
>   return (
>     <View
>       style={{ flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: 'white' }}
>     >
>       <Text>Screen One</Text>
>       <Button
>         onPress={() => {
>           props.navigation.navigate('ScreenTwo');
>         }}
>         title="Go To Screen Two"
>       />
>     </View>
>   );
> };
> 
> const ScreenTwo = () => {
>   return (
>     <View
>       style={{ flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: 'white' }}
>     >
>       <Text>Screen Two</Text>
>     </View>
>   );
> };
> 
> export default function App() {
>   return (
>     <NavigationContainer>
>       <Stack.Navigator>
>         <Stack.Screen name="ScreenOne" component={ScreenOne} />
>         <Stack.Screen name="ScreenTwo" component={ScreenTwo} />
>       </Stack.Navigator>
>     </NavigationContainer>
>   );
> }
> I am closing this, I hope this comment will help someone one day.

I encountered the same issue with a chat SDK and resolved it by modifying the AndroidManifest.xml

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
          xmlns:tools="http://schemas.android.com/tools"
          package="com.example">

    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.CAMERA"/>

    <application
            android:name=".MainApplication"
            android:label="@string/app_name"
            android:icon="@mipmap/ic_launcher"
            android:roundIcon="@mipmap/ic_launcher_round"
            android:allowBackup="false"
            tools:replace="android:enableOnBackInvokedCallback"
            android:enableOnBackInvokedCallback="false"
            android:theme="@style/AppTheme"
            android:supportsRtl="true">
      <!-- The rest of your config-->
    </application>
</manifest>
```

**Comment by FastheDeveloper** [comment]
Adding these two lines to the `<application>` tag in AndroidManifest.xml solved it:


tools:replace="android:enableOnBackInvokedCallback"
android:enableOnBackInvokedCallback="false"

**Comment by Siddhantshelake** [comment]
I’m aware that disabling **android:enableOnBackInvokedCallback="false"** temporarily restores the old back behavior on Android 16, but that’s not a long-term solution.

Specifically, on **Android 16 devices, pressing the physical back button should navigate to the previous screen in the navigation stack, rather than exiting the app or going to the device home screen.**
Right now, returning to the main screen from a directed screen does not behave as expected when predictive back gestures are enabled.

I’m looking for guidance on the best way to handle this:

Are there recommended approaches in React Navigation to fully support Android 16+ predictive back gestures?

Are there plans for built-in support for this behavior in upcoming releases?

**Comment by Siddhantshelake** [comment]
> I’m aware that disabling **android:enableOnBackInvokedCallback="false"** temporarily restores the old back behavior on Android 16, but that’s not a long-term solution.
> 
> Specifically, on **Android 16 devices, pressing the physical back button should navigate to the previous screen in the navigation stack, rather than exiting the app or going to the device home screen.** Right now, returning to the main screen from a directed screen does not behave as expected when predictive back gestures are enabled.
> 
> I’m looking for guidance on the best way to handle this:
> 
> Are there recommended approaches in React Navigation to fully support Android 16+ predictive back gestures?
> 
> Are there plans for built-in support for this behavior in upcoming releases?


Why This Happens

Android 16 no longer calls onBackPressed() or dispatches KEYCODE_BACK for apps targeting API level 36+.

React Native still depends on these legacy callbacks (onBackPressed() → ReactInstanceManager.onBackPressed() → JS BackHandler).

As a result, when predictive back is active, React Native never receives the back event, and Android assumes the activity should exit — causing the app to close.

Any sample code, patch, or guidance would be greatly appreciated 🙏

**Comment by Abdelaty-magdy** [comment]
https://github.com/react-native-community/discussions-and-proposals/discussions/921
