### ISSUE TITLE
Change route of the tab navigator while inside a stack navigator

### ISSUE THREAD

**Issue by matthamil** [react-navigation/react-navigation#1280]
### Current Behavior
Here's a condensed version of my navigation structure:

```
RootStack: {
  LogIn,
  Register,
  Home // HomeTabs
}

HomeTabs: {
  HomeStack,
  FeedStack,
  ProgressStack,
  FriendsStack,
  ChatStack
};

HomeStack: {
  screen: StackNavigator(Stack, { initialRouteName: 'Home' })
}

Stack: {
  // all other screens that I could navigate to from any of the tabs
}
```

When I go from the Home screen (with the home tab selected), and go to a screen in the Stack, I want to navigate to a separate tab screen. When I use `navigation.navigate('FeedStack')`, it will direct me to that tab, but when I click back on the Home tab, the stack does not reset to the original HomeStack screen.

### Expected Behavior
I navigate seamlessly from a stack within a tab to another tab screen.

When I am on the Home screen, and I navigate to one of the screens in Stack, I want to be able to navigate *back* to the Tab view *and* change the current tab to the FeedStack tab. 

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  pointing to Master branch
| react-native     |  0.43.1
| node             | 7.5.0
| yarn      | 0.22.0

I don't know if this is an example of needing multiple dispatches (as described in this feature request https://github.com/react-community/react-navigation/issues/1206).

**Comment by Zeeeeta** [comment]
I too have a structure similar to you and the Nesting Navigators example.

const HomeTabs = TabNavigator({
        Tab1: {},
        Tab2: {},
})
const App = StackNavigator({
        Home: {screen: HomeTabs},
        Stack1: {},
})

Tab1 could open up Stack1, and there is a button to go back AND jump to Tab2.

if I issue **navigation.navigate('Tab2')** form the Stack1 button, it seems to open up a new instance of HomeTabs, with some **setState(...): Can only update a mounted or mounting component...** warning.

**navigation.goBack(null)** and then **navigation.navigate('Tab2')** doesn't work either.
Only if the goBack transition animation is completely finished, it could properly navigate to Tab2.

Currently I have setup a conditional callback to navigate('Tab2') in the StackNavigator **onTransitionEnd** function, but I would also like to know a proper way to do that, thanks.

**Comment by matthamil** [comment]
Can you show what you mean by the *onTransitionEnd* function? I'd really like to get this type of navigation working without the hack that I have been doing:

```js
this.props.navigation.goBack();
setTimeout(this.props.navigation.navigate.bind(null, "Tab2"), 500);
```

I've been doing a `setTimeout` to wait for the `goBack()` transition to finish before dispatching another navigation action.

**Comment by Zeeeeta** [comment]
[https://reactnavigation.org/docs/navigators/stack](url)
StackNavigatorConfig:
onTransitionEnd - Function to be invoked once the card transition animation completes.

I added something like:
        onTransitionEnd: () => {
            if (GLOBAL.TransEndCallBack != null) {
                GLOBAL.TransEndCallBack();
                GLOBAL.TransEndCallBack = null;
            }
        },

So that I can place a callback function there and then call goBack().
I know this is bad but I do not know any other way to do it.

**Comment by maotora** [comment]
Is there any less "hacky" solution to this?

I too face the same challenge where the navigation opens a new instance of a certain screen when I use DrawerNavigator. 
I'm not sure how to solve this maybe will try one of your solutions but would be happier to know if there is a better / permanent solution to this.

Thank you.

**Comment by rad182** [comment]
Is there any other solution for this? I also need this functionality.

**Comment by maotora** [comment]
@rad182 I didn't solve the new instances thing, but what I noticed is my "bug" doesn't happen in production builds!
Maybe you should check that out yourself.

**Comment by wassgha** [comment]
This would have been really easy to do if `goBack` had an `actions` parameter. Any better solutions? @skevy @spencercarli ?

**Comment by tundak** [comment]
got any solution on this ?

**Comment by kranti-neteffect** [comment]
Is any one found proper solution for this pragmatically tab change scenario?

**Comment by brentvatne** [comment]
I was not able to repro this. It works as expected to navigate to a tab by its route name. See this Snack: https://snack.expo.io/H1Zosa3LM

If you are able to reproduce, please create a new issue with a Snack or a unit test that demonstrates it! Thanks!
