### ISSUE TITLE
Present new stack modally when not in a `mode: modal` stack

### ISSUE THREAD

**Issue by lprhodes** [react-navigation/react-navigation#1290]
At the moment you need to create two stacks; a parent for modal transitions and a child for everything else.

Ideally we'd be able to add an option when performing `navigate()`

I'd like to tackle this but it'd be great to get some thoughts on how best to implement it from core developers before I start.

**Comment by lprhodes** [comment]
> Ideally we'd be able to add an option when performing navigate()

In fact it may be better if we simply have a `modal: true` or `mode: 'modal'` in the navigation options of whichever screen or navigation stack we wish to present. The `navigate() ` method would check for this and perform the intended animation.

**Comment by koenpunt** [comment]
I think having 2 navigators _is_ the way to go. All applications I'm currently working on all start with a `StackNavigator` in modal mode. This makes it possible to always display a screen on top of everything else.

Also if it would be possible to present a modal screen in the middle of a stack, that would also mean that the modal becomes part of the stack, which I believe is not what a "Modal" defines.

Or it would be that a `StackNavigator` is automatically "wrapped" with a modal `StackNavigator`. But then again that's unnecessary for people who do not use modal screen.

Why do you think is the problem with having 2 navigators? You probably end up having more than 1 anyway.

**Comment by lprhodes** [comment]
> I think having 2 navigators is the way to go. All applications I'm currently working on all start with a StackNavigator in modal mode.

The reason to do something a particular way shouldn't be because you're already doing it that way. 

> This makes it possible to always display a screen on top of everything else.

As a modal we'd of course still need this to be the case

> Also if it would be possible to present a modal screen in the middle of a stack, that would also mean that the modal becomes part of the stack, which I believe is not what a "Modal" defines.

Being a part of the stack would be more natural. It would allow you to navigate through a stack like a timeline rather than ad hoc.

How you would develop it natively e.g. on iOS:

UINavigationControllerA -> Root UIViewController -> Push UIViewController -> Push UIViewController -> Present UINavigationControllerB Modally -> Root UIViewController  Push UIViewController -> Push UIViewController

UINavigationControlerB is dedicated to that stack, which you'd expect

As it stands we have to jump around navigation stacks which feels incredibly unnatural and also makes us have to think about hiding headers:

ModalStackNavigator -> Root CardStackNavigator  -> Root View -> Navigate to View -> Navigate To View -> Call back to Modal Stack Navigator -> Root View -> Navigate to View -> -> Navigate to View

**Comment by ms88privat** [comment]
Omg, I don't get it. React-Native got like 6 iterations of navigators and I have the feeling we start every time from the beginning how to do things and always have the same problems (modal, header, ...), over and over again.

I'm not complaining because I know I could also help making it better because it is open source and I really appreciate every person who is working on things like this! Just telling my thoughts here :)

**Comment by lprhodes** [comment]
@ms88privat there's many ways to do one thing and people have differing opinions on how to implement them.

On top of the 50 existing issues relating to problems with nesting (not all of them directly solvable by this change) I'll be specifying issues I come across to further push my case as I continue to try make react-navigation work for me in its current state

- Dismissing a modal that has a nested stack nav navigator (#686)
- Dismissing multiple modals

**Comment by kelset** [comment]
Pinging OP @dkpalmer since this issue is quite old and related to an old version of the lib. If no answer I'll close in 7 days.

Moreover, I think this PR #2308 will provide a feature related to this issue (but I may be wrong, in which case let me know)

**Comment by dkpalmer** [comment]
@kelset Wrong mention, or different GH issue?

**Comment by kelset** [comment]
Whoops! Sorry, wrong autocomplete X_X

**Comment by kelset** [comment]
(update: not going to close until the PR is merged)

**Comment by brentvatne** [comment]
please re-post to https://react-navigation.canny.io/feature-requests if this is important for you. re-organizing issues to focus on bug reports here and feature requests on canny. thanks!
