### ISSUE TITLE
Drawer pan mask 

### ISSUE THREAD

**Issue by jcsmesquita** [react-navigation/react-navigation#1301]
Is it currently possible to set some sort of pan mask for the Drawer to open when the swipe gesture is initiated anywhere but solely from the edge of the screen?

**Comment by boomfly** [comment]
+1

**Comment by aaronleo28** [comment]
Just had a look myself and I doubt this will be possible any time soon, they use the drawer component in react-native (https://facebook.github.io/react-native/docs/drawerlayoutandroid.html#content) which doesn't have any available props to change the gesture response distance.

**Comment by kelset** [comment]
I'm sorry to say that @aaronleo28 is right, for the drawer is a "long chain" of deps. I'll keep this issue open but I can't see it happening anytime soon.

**Comment by brentvatne** [comment]
please re-post to https://react-navigation.canny.io/feature-requests if this is important for you. re-organizing issues to focus on bug reports here and feature requests on canny. thanks!
