### ISSUE TITLE
Nested DrawerNavigator has top gap for header when open

### ISSUE THREAD

**Issue by svicalifornia** [react-navigation/react-navigation#1305]
If a DrawerNavigator is nested inside a StackNavigator (particularly a modal one), then opening the drawer shifts everything (the drawer and the active screen behind it) down by the standard height of a StackNavigator header:

<img width="320" alt="4650f97a-e8ba-11e6-95c4-3d0fe0bfc7ce" src="https://cloud.githubusercontent.com/assets/134837/25554880/dcbadc8e-2c8d-11e7-80fe-b884b5a83005.png">

DrawerNavigator is implemented as two nested TabRouters. The outer one should have `header: null` in its `navigationOptions` so that it doesn't add a gap for its nonexistent header when nested inside a StackNavigator.

Bugfix PR coming right up…

**Comment by SCasarotto** [comment]
I am not sure if this is your exact case but I came across the same things. Adding `navigationOptions: { header: null } ` after DrawerNavigator removed that space at the top when the Drawer is open.

```    
Main : {
	screen: DrawerNavigator({
		Main		: { screen: Main },
		Profile		: { screen: Profile },
		Vehicle		: { screen: Vehicle },
		Schedule	: { screen: Schedule },
	}), 
	navigationOptions: { header: null } 
}
```

Hope this helps some.

**Comment by svicalifornia** [comment]
@SCasarotto It's been some time since I worked on this in April, but we did try `header: null` back then, and it did not work properly with DrawerNavigator nested inside another navigator. Perhaps it has been been fixed, but I would ask maintainers to keep this issue open to confirm the nested use case (as described above, a DrawerNavigator nested inside a StackNavigator).

**Comment by hugows** [comment]
Did you ever fix that? Happening to me as well..

**Comment by kelset** [comment]
@hugows probably it will be fixed in `beta.16`, but until that lands I am not sure.

**Comment by Progoogler** [comment]
This is happening to me too. The only way I've found to work around it is to create a custom view above my `DrawerItems`with a height that approximately overlaps this blank space. 

The problem it caused me was that I couldn't press on my first DrawerItem label. The blank space, although not visible, was discretely covering the label, preventing me from navigating to that screen.

**Comment by ivosabev** [comment]
Any status on this, I am having the same issue with a DrawerNavigator nested inside StackNavigator.

```
const HomeNavigation = DrawerNavigator({
  Tasks: {
    path: 'tasks',
    screen: TasksScreen,
  },
});

const Navigation = StackNavigator({
    Login: {
      path: 'login',
      screen: LoginScreen,
    },
    Home: {
      path: 'home',
      screen: HomeNavigation,      
    },
  },
});
```

<img width="473" alt="screen shot 2018-01-05 at 1 11 17 pm" src="https://user-images.githubusercontent.com/103370/34606986-29ac38ba-f21a-11e7-92d5-a4b84f6e4e73.png">

**Comment by brentvatne** [comment]
you should put stacks inside of the drawer, or on your drawernavigator do:

```
const HomeNavigation = DrawerNavigator({
  Tasks: {
    path: 'tasks',
    screen: TasksScreen,
  },
});

HomeNavigation.navigationOptions = {
  header: null,
};
```

**Comment by svicalifornia** [comment]
@brentvatne There are legitimate use cases for putting a DrawerNavigator inside a StackNavigator. One very common example is to use a StackNavigator to transition from a login screen to a logged-in state, where the logged-in state includes a hamburger menu to open a drawer that is only available while logged-in.

If this was your sole argument for closing the issue, then please undo that decision and reopen.

**Comment by brentvatne** [comment]
ok, please reopen an issue and follow the issue template this time :)
