### ISSUE TITLE
Expect nav state to have routes and index, {"routeName":"Main","key":"Init"}

### ISSUE THREAD

**Issue by veedeo** [react-navigation/react-navigation#1359]
Im trying to implement react-navigation with Redux and nested TabBar

### Current Behavior
Im getting error:
Expect nav state to have routes and index, {"routeName":"Main","key":"Init"}

```
const Main = TabNavigator({
  MapViewWithActivityList: {
    screen: MapViewWithActivityList
  }, 
});
const AppNavigator = StackNavigator({
  LoginScreen: { screen: VerifyLoginScreen },
  Main: { screen: Main },
})

const initialState = AppNavigator.router.getStateForAction(NavigationActions.navigate({ routeName: 'Main' }));
  const navReducer = (state = initialState, action) => {
    console.tron.log({state,action,nextState})
    let nextState;
    // = AppNavigator.router.getStateForAction(action, state);


    // Simply return the original `state` if `nextState` is null or undefined.
    return nextState || state;
  };
```
And there is no nested Tabs in the state
```
{
  state:{
    index: 0,
    routes: [ { type: undefined, routeName: 'Main', key: 'Init' } ]
  },
  action: { type: '@@redux/INIT' },
  nextState: undefined
}
```

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.9
| react-native     |  0.43.4

**Comment by alonbardavid** [comment]
I'm also experiencing this problem.

The implementation of `getStateForAction` is inconsistent - when supplying the state, it creates a proper new state, however when not providing the state it creates a hybrid between a state and an action.

The culprit is this code in `stackRouter.getStateForAction`:

```js
if (!state) {
        let route = {};
        if (
          action.type === NavigationActions.NAVIGATE &&  childRouters[action.routeName] !== undefined
        ) {
          return {
            index: 0,
            routes: [
              {
                ...action,
                type: undefined,
                key: 'Init',
              },
            ],
          };
}
```
I'm guessing this is used internally somehow for nested routers - such that sometimes the action parameter in getStateForAction is an action and sometimes it's a nested state.

I would argue that the `getStateForAction` should have a single api which receives an action and the current functionality should be split to a new function to compose nested states. Or at the very least `getStateForAction` should require a previous state to be sent.

**Comment by Jekiwijaya** [comment]
+1
Helpp

**Comment by mzafer** [comment]
Is there a solution or work around for this ? Thanks.

**Comment by HanAsteroid** [comment]
+ 1

**Comment by eduzera** [comment]
same here

+1

**Comment by GarethOates** [comment]
I'm also interested in a work around as this has become a show stopper for me.

**Comment by mzafer** [comment]
The error was resolved for me after I renamed the navigation state object in my application to 'nav'. I had initially named as AppNav.

**Comment by mynamespace** [comment]
@mzafer same for me!

**Comment by GarethOates** [comment]
The name you choose is supposed to match the name of the 'sub-reducer' in your store right?  The name of the sub property in your state object that handles navigation?

**Comment by mzafer** [comment]
@GarethOates, yes that is correct.

**Comment by ds300** [comment]
renaming the navigation state object to 'nav' did nothing for me. Anyone got any tips for fixing this?

**Comment by lideen** [comment]
This works for me:

`const INITIAL_STATE = router.getStateForAction(NavigationActions.init())`

**Comment by dchersey** [comment]
This worked for me too but I have no idea why ... here's more fully elaborated code separated into 3 statements for easier debugging: 
```javascript
import { RootStackNavigator } from "../navigation/RootNavigation";
import { StackNavigator, NavigationActions } from "react-navigation";

const router = RootStackNavigator.router;
const action = NavigationActions.init();
const initialState = router.getStateForAction(action);
```

This is the only code that manages to include the index and child routes in the routes array
```javascript
{index: 0, routes: Array(1)}
   index: 0
   routes: Array(1)
   0 :
      index : 0
      key: "Init-id-1506541831169-0"
      routeName: "Main"
      routes : Array(3) 
          0 : {key: "Home", routeName: "Home"}
          1 : {key: "Links", routeName: "Links"}
          2 : {key: "Settings", routeName: "Settings"}
```

 that is missing when using the recommended code. 

```javascript
const initialState = RootStackNavigator.router.getStateForAction(
  RootStackNavigator.router.getActionForPathAndParams("Main")
);
```

which produces
```javascript
{index: 0, routes: Array(1)}
    index: 0 
    routes: Array(1)
      0 : {type: undefined, routeName: "Main", key: "Init-id-1506542362161-0"}
```

Would love to understand why ... it seems as though my navigator's actions are not initialized.  

How would I specify initial state to be "Links" or "Settings" in this case?

note: I also tried 
```javascript
const initialState = RootStackNavigator.router.getStateForAction(
 NavigationActions.navigate({ routeName: 'Main' })
);
```
following [this example](https://github.com/cribspot/react-navigation/commit/4c07d8b5fafd386004dd8197659fff8d9126467e) and received the same uninitialized output as above.

**Comment by haseebnaseem** [comment]
I have not been able to generate the state correctly using either from @dchersey's method or from the the one mentioned in the docs. 
This is how my navigators are defined:
```
const HomeNav = TabNavigator({
    feed:{screen:Feed},
    restaurantScreen:{screen:Restaurant},
},{
    tabBarComponent:NavigationComponent,
    tabBarPosition:'bottom',
    tabBarOptions:{
        bottomNavigationOptions:{
            labelColor:'white',
            rippleColor:'white',
            tabs:{
                feed:{
                    barBackgroundColor:'#37474F',
                },
                restaurantScreen:{
                    barBackgroundColor:'#00796B',
                }
            }
        }
    }
});
export const Navigator=StackNavigator(
    {
        HomeScreen:{screen:Home},
        VerifyScreen:{screen:Verify},
        newUserScreen1:{screen:newUser1},
        newUserScreen2:{screen:newUser2},
        loginScreen:{screen:login},
        feedScreen:{screen:HomeNav},
    },
    {
        headerMode:'none',
    },
);
```
and this is how I am trying to set the initial state and navigate:
```
const initialState=Navigator.router.getStateForAction(
    NavigationActions.init()
);

function navigate(screenName,state){
    return Navigator.router.getStateForAction(NavigationActions.navigate({routeName:screenName},state));
}
```
The following error comes up when navigating from Home screen to the feed Navigator:
```
Expect nav state to have routes and index, {"routeName":"feedScreen","key":"Init-id-1510393473667-1"}
```

**Comment by brentvatne** [comment]
hi! this is specific to redux integration, so the issue belongs on https://github.com/react-navigation/react-navigation-redux-helpers
