### ISSUE TITLE
iOS card animations for android

### ISSUE THREAD

**Issue by jeffreymendez1993** [react-navigation/react-navigation#1400]
It would be nice to have this working the same for android since mode={'modal'} and mode={'card'} are the same transitions on android.

**Comment by koenpunt** [comment]
Ran into this as well, and as a workaround I set the `transitionConfig` to the horizontal interpolator:

```js
import CardStackStyleInterpolator from 'react-navigation/src/views/CardStackStyleInterpolator';

export default StackNavigator({
  Home: {
    screen: HomeScreen,
  },
}, {
  transitionConfig: () => ({
    screenInterpolator: CardStackStyleInterpolator.forHorizontal,
  }),
  navigationOptions: ({ navigation }) => ({
    //...
  }),
})

**Comment by wokalski** [comment]
It would be great to export `CardStackStyleInterpolator` to the public API. It has been also mentioned in https://github.com/react-community/react-navigation/pull/1002 by @ericvicenti.

**Comment by aqnaruto** [comment]
and the same transaction-gesture is better @wokalski

**Comment by aqnaruto** [comment]
dear @koenpunt  ,do you know how to  make same goback-gesture on android just like ios's . thank you

**Comment by ryancoughlin** [comment]
Trying to track down a bit more information regarding custom transitions and `transitionConfig` within this lib. What exactly will:

```
  transitionConfig: () => ({
    screenInterpolator: CardStackStyleInterpolator.forHorizontal,
  }),
```

When executed?

**Comment by manuTro** [comment]
@wokalski Do you know if now `CardStackStyleInterpolator` is available into the API?  I got problem by requiring it from "react-navigation/src/views/CardStackStyleInterpolator.js"

**Comment by koenpunt** [comment]
@manuTro the following works fine for me:

```
import CardStackStyleInterpolator from 'react-navigation/src/views/CardStackStyleInterpolator';
```

**Comment by manuTro** [comment]
@koenpunt  The problem is that I'm using clojurescript so I need to require it directly from react-navigation.. OtherwiseI have this warnig:
![warning](https://user-images.githubusercontent.com/25326470/27690411-904f8050-5ce1-11e7-8a6e-76d81b7928da.png)

**Comment by manuTro** [comment]
@koenpunt  Or maybe is there another way to make stacknavigator swipe horizontally?

**Comment by koenpunt** [comment]
You can copy the file for the time being, until it's exposed as a default export.
