### ISSUE TITLE
proposal: `Navigation/BACK` action gets key for router ID, so disconnected Navigators respond individually

### ISSUE THREAD

**Issue by faceyspacey** [react-navigation/react-navigation#1421]
### Current Behavior
Currently, say, if you have 2 *visible but disconnected* Navigator "families" (e.g. a StackNavigator, and a Modal, which in it has another StackNavigator), both Navigators will respond to a `Navigation/BACK` action, when you really just want the modal navigator responding.

Another use case is, say, if you have a custom drawer that has a Navigator within it (using `contentComponent`), which appears simultaneously while you can see a sliver of your main app behind it. Again, you have 2 simultaneously visible routers both responding to `BACK` actions, when your intent is for only one of them to respond. Navigators are powerful and getting more animation capabilities--people are going to have more and more "disconnected router families," especially in medium to large-sized apps.

The current workaround is to identify some state in your reducer that determines what router the user is currently acting within, and then only update the state of the router you determine the action was for. Here's a quick example of how I do it within a DrawerNavigator:

```js
export default function DrawerStackFamily(state, action) => {
  if (action.type === 'Navigation/BACK' && state.index === 1) { // drawer is open, and other navigator should respond
    return state
  }
  return MyDrawer.router.getStateForAction(action, state) || state
}

// This router doesn't need to worry about avoiding other BACK actions
// as when it is visible, all actions will correspond just to this router.
export default function ModalStackFamily(state, action) => {
  return MyStack.router.getStateForAction(action, state) || state
}
```

To make it more concrete, here's what your navigator families might look like:

- DrawerRouter 
--> DrawerClosed -> StackRouter: { scene1: TabRouter -> ..., sceneEtc: PushedPage }
--> DrawerOpen.*contentComponent*: AnotherStackRouter

> note: arrows indicate proper router "connections," which form the lineage of a router family.

So, this is just an example. In my opinion, the solution doesn't include *not having multiple disconnected routers*. If so, please enlighten me. I already have many needs for multiple disconnected routers, and I know how to make use of what I'm calling "router families" very idiomatically (where you assign a Navigator to the `screen` prop within `routeConfig` entries), eg: `TabRouter -> StackRouter` or `DrawerRouter -> StackRouter: { scene1: TabRouter, sceneEtc: PushedPage }`. It still doesn't solve all my uses cases. Not at all.

### PROPOSAL: Expected Behavior (suggesting a change/improvement)
Dispense these actions instead:

```js
const action = {
   type: 'Navigation/BACK',
   routerId: 'DrawerRouter' | 'AnotherStackRouter'
   key: null
}
```

And then build into the router's `getStateForAction` method inference of whether to update its state, based on whether the ID corresponds to it. Straightforward.

***Potential problems?***

**Comment by alenia** [comment]
Similarly, the same behavior happens with 'Navigation/RESET' and it would be great to indicate which router it should reset.

**Comment by faceyspacey** [comment]
This is actually a core issue everywhere. Nested navigators (such as TabNavigator within StackNavigator as in the main example in the documentation) should dispatch actions that indicate which Parent navigator they are nested within. See this other issue of mine:

https://github.com/react-community/react-navigation/issues/1508

For example, in StackNavigator -> TabNavigator, the tabs dispatch a flat action instead of an action with a nested action. The latter is what you would get if you called `getActionForPathAndParams` on the corresponding path. However, `getStateForAction` doesn't handle it appropriately (https://github.com/react-community/react-navigation/issues/1508). 

Imho, this stuff (though very advanced usage) needs to be handled before 1.0 or a very bad precedents will be set where people will be dispatching flat actions all over the place, and writing all sorts of workarounds in their reducers to guess which reducer actions are meant for. 

As it stands, the entire deep-linking system cannot be used in professional apps. It's close, but for it to be complete links must generate the exact same state as the actions dispatched from the buttons built into the navigators. Buttons built into the navigators generate flat actions, where as actions generated from nested paths generated nested actions. It's not correct. 

And to be sure it's a challenging problem--probably because the expected result is dependent on which type of router is nested in which type of parent router. I'm working on changes to `StackRouter.getStateForAction` to see if I can at least solve this for the concrete relationship of StackRouter -> TabRouter (as in the primary example in the documentation).

**Comment by faceyspacey** [comment]
Here's a preliminary PR to address this:

https://github.com/react-community/react-navigation/issues/1508

Here's how it works:

```js
export const MyStack = StackNavigator(routeConfigs, { 
   navKey: 'myStack'
})
```

Sample action dispatched:
```js
const action = {
   type: 'Navigation/NAVIGATE',
   routeName: 'Foo',
   navKey: 'myStack'
}
```

*reducer*:
```js
import MyStack from '../components/MyStack'

const myStackReducer = (state, action) =>
 MyStack.router.getStateForAction(action, state) || state

combineReducers({ myStack: myStackReducer })
```


The primary mechanism to achieve this is in `addNavigationHelpers`:

```js
// ...
export default function<S: *>(navigation: NavigationProp<S, NavigationAction>) {
  const oldDispatch = navigation.dispatch

  navigation.dispatch = (action: NavigationAction): NavigationAction => {
    action.navKey = typeof action.navKey !== 'undefined'
      ? action.navKey
      : navigation.navKey

    return oldDispatch(action)
  }

  return {
    ...navigation,
    goBack: (key?: ?string): boolean =>
      //...
```

Then in `getStateForAction` for all routers you have (simplified):

```js
getStateForAction(action, state) {
      if (action.navKey && action.navKey !== navKey) {
        return state
      }
     // ...
```
> note: if you dispatch `action.navKey === null`, all reducers (and accordingly independent router families) will be able to respond to the action. This is obviously intentional. It allows code in any Navigator to dispatch automatically to itself, to everyone by specifying `null` or even directly to a different Navigator family by specifying its `navKey`. It's my belief that this is the state of the art and the future of *react-navigation* when it comes to redux-integration :).


The primary remaining consideration is directly targeting nested routers. Currently there are issues with deep-linking where if you take a path, convert it to an action via `router.getActionForPathAndParams` the resulting action (which can will nested actions) isn't handled the same way a flat action is handled, which attempts to let child routers handle it in `getStateForAction`. So perhaps simply fixing that bug (which I have a have another PR which attempts to at least solve part of it: https://github.com/react-community/react-navigation/pull/1515), will solve the problem of dispatching actions within one router family that targets another router family. But if not, this PR may want to be amended to allow for child routers (which don't have a corresponding reducer of their own), to still have their own `navKey`, which can be directly targeted, even though their state is calculated in a parent reducer.

**Comment by brentvatne** [comment]
and yet again, thanks @faceyspacey - https://github.com/react-navigation/rfcs is a good place for this going forward. apologies for the hassle
