### ISSUE TITLE
proposal: screen-level `modal` and `transitionConfig` options for StackNavigator

### ISSUE THREAD

**Issue by faceyspacey** [react-navigation/react-navigation#1423]
Currently, **every scene gets the same transition**. The `StackNavigatorConfig` takes a `mode` or `transitionConfig` option.  So the feature would be for screens' `navigatorOptions` to also take such options. 

To make this most useful, we need these 2 additional improvements as well:

-  make `modal` `mode` also work on Android. It seems it's just a question of removing this code: https://github.com/react-community/react-navigation/blob/6b8cb793b426be36c1366f3e4157a9f208815dcd/src/views/TransitionConfigs.js#L63 

- export various transition configs and interpolators so client code can make use of them to create custom transitions. Currently there is no way to get access to them from `react-navigation.js`. As it currently stands, how are you supposed to create the `transitionConfig` prop without these exports? The old `Navigator` included with React Native exported straightforward interpolation tools for custom transitions.

> NOTE: the idea for allowing `modal` on Android is: let the user decide if he wants to create the effect of a an iOS style modal on Android, rather than force the user to create dialogs. That way you can use the same code for both platforms. It seems unnecessarily strict to block the use of a feature that is already cross-platform (correct me if I'm wrong about it being cross-platform).

**Comment by Exilz** [comment]
This is a most needed change, and at first glance it looks like it shouldn't be too much work. I second this 👍

**Comment by aqnaruto** [comment]
no,this is not the most needed change,  the mode 'card' on android is still has not been implemented but written in document,and can't use transaction-gesture   is most needed @Exilz

**Comment by KylePalko** [comment]
This would have made our refactor from React Native's deprecated navigation to React Navigation much simpler.

**Comment by faceyspacey** [comment]
@KylePalko it's probably far simpler to add this feature to React Navigation and fork it until it's merged. I looked into it--passing along specific animation properties dynamically per scene isn't trivial though, since everything is setup statically when you first create your navigators. I don't imagine it being that time-consuming for someone who knows the codebase though. 

That said, there is 2 versions of "dynamically": per scene, and even in response to dispatches. Like, you may wanna transition the same scene differently in different scenarios. 

Before that, we really need to get control of the transition animations. There should be more options. Traditionally with the original Navigator you just specify an interpolation config and done. That should be low-hanging fruit. *Only once you have more than 1.5 options does it matter whether you can dynamically change which animation option is used.*

**Comment by kelset** [comment]
I think PR https://github.com/react-community/react-navigation/pull/2308 addresses this issue.

**Comment by brentvatne** [comment]
again thanks @faceyspacey - https://github.com/react-navigation/rfcs is a good place for this going forward. apologies for the hassle
