### ISSUE TITLE
proposal: idiomatic way to connect child navigators that are diconnected in the component tree

### ISSUE THREAD

**Issue by faceyspacey** [react-navigation/react-navigation#1425]
This is an answer to the following line from the documentation.:

https://reactnavigation.org/docs/guides/redux
>Keep in mind that when a navigator is given a navigation prop, it relinquishes control of its internal state. That means you are now responsible for persisting its state, handling any deep linking, integrating the back button, etc.

## Use Case
Say you're using the `contentComponent` option of DrawerNavigator. And you put a StackNavigator in it. It's now disconnected from the parent, but it doesn't need to be.

Currently, you can work around this by doing things like the following in its reducer:

```js
drawerReducer(state, action) => {
  const prevStackDrawerState = state && state.routes[1] && state.routes[1].routes && state.routes[1].routes[0]
  const stackDrawerState = StackDrawer.router.getStateForAction(action, prevStackDrawerState) || prevStackDrawerState

  const drawerState = action.type === 'Navigation/BACK' && state.index === 1
    ? {...state}
    : (Drawer.router.getStateForAction(action, state) || state)

  drawerState.routes[1].routes = [stackDrawerState]
  drawerState.routes[1].index = 0

  if (stackDrawerState !== prevStackDrawerState) {
    return { ...drawerState }
  }

  return drawerState
}
```

So here I'm nesting a Stack in the `DrawerOpen`'s state, similar to how the `DrawerClosed` closed state is represented. 

But ultimately that is garbage. 

## Proposal
The proposal is for a way to connect the Navigators beyond assigning to a `screen` in the routeConfigs. The API could look like this:

```js
const Stack = StackNavigator(routeConfigs)

DrawerNavigator({
    Scene: { screen: SomeScene }
}, {
   openScreenNavigator: Stack
})
```

*for StackNavigator:*
```js
const Stack1 = StackNavigator(routeConfigs)
const Stack2 = StackNavigator({
    Scene: { 
       screen: SomeScene,
       navigator: Stack1
    }
})
```

Something like that. Because of the nature of the different navigators, the way a child navigator is specified might need different naming and locations within options. And of course--as can bee seen with the `drawerReducer` above--how the corresponding router state connects will also differ depending on the parent navigator.

That all said, not all navigators have routers that make sense as direct descendants of another navigator, but that can be up to the user to decide.

**Comment by faceyspacey** [comment]
Also perhaps the API is more about connecting `routers`, i.e:

```js
const Stack1 = TabNavigator(routeConfigs)

const SomeScene = () => 
    <View style={fancyStyles}>
         <Stack1 /> // notice this is disconnected, and it allows for fancy wrapping styles
    </View>

const Stack2 = StackNavigator({
    Scene: { 
       getScreen: () => SomeScene,
       router: Stack1.router
    }
})
```

**Comment by brentvatne** [comment]
closing this because it's inactive, not because it's a bad idea. if anyone wants to carry the torch, please open a rfc
