### ISSUE TITLE
Caching between routes in DrawerNavigator

### ISSUE THREAD

**Issue by CandyOgre** [react-navigation/react-navigation#1486]
I have the following drawer in my app:
```
const MainDrawer = DrawerNavigator({
  Map: { screen: MapViewContainer },
  Organization: { screen: OrganizationView },
});
```
`MapViewContainer` - it\`s a View with Google Map.
`OrganizationView` - just some text.

The problem is, when I load my app, Google Map loads. BUT. If I go to `OrganizationView` and then again to `MapViewContainer` my Google Map start loading again from scratch. I have a lot (~3000) polygons to display on map, so it`s a bit heavy to load all of this on every route entry.

Is there any way to somehow cache MapPage or something like that?

**Comment by efkan** [comment]
I've create an entry on `v2` RoadMap. https://github.com/react-community/react-navigation/issues/1263#issuecomment-309692518 
Please increase its number of `+1` if you still interested on this feature.

**Comment by efkan** [comment]
Alternatively I've been trying to make Map Screen the main screen of the stack by playing route configurations like the following:


```
const mainStackNavigator = StackNavigator(
	home: { 
		screen: Screens.Home,
		navigationOptions: ({ navigation, screenProps }) => ({ ... })
	},
       /* and other screens like home */
)

const mainDrawerNavigator = DrawerNavigator(
	{
		mainStackNavigator: {
			screen: mainStackNavigator
		}
	},
	{
		screenMode: 'screen',
		contentComponent: Drawer, // custom Drawer navigator
		drawerWidth: Dimensions.get('window').width / divider,
	}
)


// ROOT NAVIGATOR WHICH IS USED IN FINALLY REACT COMPONENT (in appWithNavigationState)
const AppNavigator = StackNavigator(
	{
		mainStack: { screen: mainDrawerNavigator, },
		loginStack: { screen: loginStackNavigator, },
	},
	{
		navigationOptions: ({ screenProps }) => {
			return {
				header: null, // preventing from double header issue!
			}
		}
	}
)
```


But this setup has another issues on route index when handling `NavigationActions.back()` with `BackHandler`.

**Comment by kelset** [comment]
Pinging OP @CandyOgre since this issue is quite old and related to an old version of the lib. If no answer I'll close in 7 days.

**Comment by CandyOgre** [comment]
@kelset this issue does not resolved yet

**Comment by brentvatne** [comment]
https://github.com/react-navigation/react-navigation/issues/2277 is more popular, so closing it in favor of that. we'll give drawer a lot more attention while working on the next version of react-navigation so we expect to have this solved in the coming months. apologies for the delays
