### ISSUE TITLE
Unnecessary restriction: cannot create DrawerNavigator with `navigator` and `contentComponent` properties

### ISSUE THREAD

**Issue by frankiesardo** [react-navigation/react-navigation#1502]
### Current Behavior

I wish to create a DrawerNavigator that has its state managed externally (explicit `navigator` props passed) **and** I want to be able to style the content of the drawer (explicit `contentComponent` props passed). The app errors with:

```
This navigator has both navigation and container props, so it is unclear if it should own its own state. Remove props: "contentComponent" if the navigator should get its state from the navigation prop. If the navigator should maintain its own state, do not pass a navigation prop.
```

### Expected Behavior
I don't understand why this is a restriction at all: the component should not own its state because I'm passing explicit `navigation` props and should simply call the `contentComponent` with the parent properties so I can properly style the drawer. How can we achieve such thing with this restriction in place? Is this necessary at all?

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.9
| react-native     |  15

**Comment by kelset** [comment]
I think most of these requests will be handled by `beta.16`. By PRs like #2764 (you can test them via master in the meantime)

**Comment by brentvatne** [comment]
please re-post to https://react-navigation.canny.io/feature-requests if this is important for you. re-organizing issues to focus on bug reports here and feature requests on canny. thanks!
