### ISSUE TITLE
proposal: idiomatic way to nest a StackNavigator in DrawerOpen state/ui

### ISSUE THREAD

**Issue by faceyspacey** [react-navigation/react-navigation#1541]
### Current Way To Achieve Stack Navigator in DrawerOpen UI
Currently you specify a DrawerNavigator like this:

```js
export const StackDrawer = StackNavigator({
  Menu: { screen: Menu },
  Settings: { screen: Settings },
  Notifications: { screen: Notifications }
})

let AppStackDrawer = ({ state, dispatch, close }) =>
  <StackDrawer
    screenProps={{ close }}
    navigation={addNavigationHelpers({
      dispatch,
      state
    })}
  />

AppStackDrawer = connect(({ stackDrawer }) => ({ state: stackDrawer }))(AppStackDrawer)

export const Drawer = DrawerNavigator(closeStateRouteConfigs, {
  contentComponent: props => (
    <ScrollView>
      <View>
        <AppStackDrawer
            close={() => props.navigation.navigate('DrawerClose')}
        />
      </View>
    </ScrollView>
  )
})
```

### Desired Way to Specify this:
```js
const StackDrawer = StackNavigator({
  Menu: { screen: Menu },
  Settings: { screen: Settings },
  Notifications: { screen: Notifications }
})

export const Drawer = DrawerNavigator(closeStateRouteConfigs, {
  menuNavigator: StackDrawer
})
```

:)

## Notes

I've pulled off something similar with a `Drawer` reducer like this:

```js
export default (state, action) => {
  const prevStackDrawerState = state && state.routes && state.routes[1] && state.routes[1].routes && state.routes[1].routes[0]
  const stackDrawerState = StackDrawer.router.getStateForAction(action, prevStackDrawerState) || prevStackDrawerState

  const drawerState = action.type === 'Navigation/BACK' && state.index === 1
    ? {...state}
    : (Drawer.router.getStateForAction(action, state) || state)


  drawerState.routes[1].routes = [stackDrawerState]
  drawerState.routes[1].index = 0

  if (stackDrawerState !== prevStackDrawerState) {
    return { ...drawerState }
  }

  return drawerState
}
```

I didn't take it farther than that, but to make this work with deep-linking you then need to override `Drawer.router.getPathAndParamsForState` to get paths for your opened drawer state's router's child navigator. etc. 

To me personally, the idea of having your Drawer be a menu that just displays items which when clicked displays corresponding screens *in the close state UI placeholder* is incorrect. I mean I guess some apps are built that way. I always put a full on navigator in the menu itself so that the drawer feels like a separate area unrelated to your main app area (where you may have a TabNavigator, etc). Switching in-and-out the screen for the first spot in the TabNavigator isn't ideal. Are people really doing that?? Anyway, I think this is a must and allows for another common pattern nevertheless (if not the primary pattern here).

**Comment by faceyspacey** [comment]
In addition, the DrawerNavigator needs open and close path configuration options as per my PR:

https://github.com/react-community/react-navigation/pull/1516

```js
export const Drawer = DrawerNavigator(routesConfig, {
  closePath: 'app',
  openPath: 'drawer',
```

That kinda completes the optimum developer experience here.

**Comment by brentvatne** [comment]
@faceyspacey - again, thank you for this well thought out proposal. can i ask that you repost it a rfc for it on https://github.com/react-navigation/rfcs following the template provided? thanks!
