### ISSUE TITLE
Reset stacks for all tabs (TabNavigator)

### ISSUE THREAD

**Issue by RyanMitchellWilson** [react-navigation/react-navigation#1613]
Is there a way to reset all stacks under a TabNavigator? I've been looking for a while now without much luck finding an answer. I've seen that there is a `reset` navigation option that will reset a stack but it will only reset the current stack that you are on. I need to find a way to also reset the stacks of my other tabs. 

Use case: signing out of the app and resetting all Stacks on the TabNavigator so you have a clean state when the next person signs in.

Using:
Redux
React-Native: 0.41
React: 15.4.2
React-Navigation: 1.0.0-beta.7

**Comment by jordanmkoncz** [comment]
I have the same requirement. When a particular Redux action is dispatched, I need to completely reset the stacks for each tab in my `TabNavigator`. My navigation state is managed in Redux. Has anyone managed to implement functionality like this?

**Comment by diegorodriguesvieira** [comment]
+1

**Comment by bakarshams** [comment]
any update? Did you find the solution?
@jordanmkoncz 
@diegorodriguesvieira

**Comment by jordanmkoncz** [comment]
@bakarshams I kind of found a solution, but not one that is ideal or that would work for all use cases. I basically just dispatch a `NavigationActions.reset(...)` action which resets my entire navigation state to the point where each tab in my `TabNavigator` is in the state I want (reset to its initial state).

Here's the code from my app:

```
this.props.navigation.dispatch(NavigationActions.reset({
  index: 0,
  key: null,
  actions: [NavigationActions.navigate({ routeName: SCREEN.MAIN })],
}));
`

In my case, `SCREEN.MAIN` is my `TabNavigator`.

**Comment by ybentlili** [comment]
hello , 
I'm trying to logout from my application by rest my TabNavigator stack. I need to go to the Login Screen. 

`const actionToDispatch = NavigationActions.reset({
                 index: 0,
                 key: null,
                 actions: [NavigationActions.navigate({ routeName: Pages.LoginMail })]
               })
               this.props.navigation.dispatch(actionToDispatch)`

I switch to the Login screen but I have the tabs bottom are displayed ?? 

Any solution for the tabs bottom ?

thank you

**Comment by RyanMitchellWilson** [comment]
@ybentlili to hide the tab bar for a specific screen you can add this to your component:
```
static navigationOptions = {
  tabBarVisible: false
}
```
https://reactnavigation.org/docs/navigators/tab#tabBarVisible

**Comment by ybentlili** [comment]
@RyanMitchellWilson  thank you for you response.. 
But I don't need this params.. 
For more details, Login Screen and the TabNavigator has each stack. So when I switch from Login -> Home (with tabBar) then when I press a logout button from Home, I switch to Login Screen with the TabBar at the bottom..

**Comment by kelset** [comment]
I suggest y'all take a look at issue #1127 (in particular from [this comment](https://github.com/react-community/react-navigation/issues/1127#issuecomment-319727619) on) to better understand how reset works atm until the overall behaviour of it is tackled properly (see the roadmap).

**Comment by brentvatne** [comment]
https://reactnavigation.org/docs/en/auth-flow.html - you can use switchnavigator for this.

if someone can explain exactly what they need in a new issue that would be appreciated, the information here isn't sufficient for me to understand the use case
