### ISSUE TITLE
screen's component multiple mount

### ISSUE THREAD

**Issue by jemmyphan** [react-navigation/react-navigation#1724]
I've got some weird case which component got mount and unmount again after re-entering the same scene with different props key.
it occurred when i goBack an reenter to that screen immediately ( different props )
<img width="506" alt="screen shot 2017-05-30 at 1 08 55 pm" src="https://cloud.githubusercontent.com/assets/7644274/26571071/225cec6e-453e-11e7-895d-ce3b9ea1c8d2.png">
but if i re-enter it with some delay
it behaves normally, there is no extra mount and unmount there
<img width="496" alt="screen shot 2017-05-30 at 1 10 07 pm" src="https://cloud.githubusercontent.com/assets/7644274/26571078/3134a484-453e-11e7-9842-5a35ad45847d.png">

https://snack.expo.io/BJOB36c-b
<img width="1277" alt="screen shot 2017-05-30 at 5 40 37 pm" src="https://cloud.githubusercontent.com/assets/7644274/26579737/3f458f36-455f-11e7-82b1-1db79747de69.png">
how to reproduce: navigate to "Test" -> back -> navigate to "Test" immediately

**Comment by ucare-wuh** [comment]
Got the same issue here.

**Comment by kwnccc** [comment]
I can confirm too!

**Comment by kelset** [comment]
I think this may be related to the app being in debug mode.  Does this happen when in production release? On both platforms Android/iOS? With the latest version of this lib?

**Comment by ucare-wuh** [comment]
@kelset , it does happen in production release. I tested this with an iPhone 6, by alerting a message in `componentWillMount`. Two alerts were prompted when I goBack and enter again quickly.
```
componentWillMount () {
  alert('will mount')
}
```

**Comment by justinobney** [comment]
It appears this was introduced between `1.0.0-beta.11` & `1.0.0-beta.12`

**Comment by brentvatne** [comment]
thanks for the detailed report and the repro, moving it to an umbrella issue for this bug. we'll be tackling it in the near future as we rewrite the Transitioner component
