### ISSUE TITLE
Cannot Properly Center Title on Android

### ISSUE THREAD

**Issue by StevePotter** [react-navigation/react-navigation#1728]
The default for title alignment on Android is left but in our app we center it.   

To center the title, I specified a style in `headerTitleStyle` that has `alignSelf: 'center'`.  That moved the title to the middle, but it was offset by 40px, as shown here:
<img width="377" alt="screenshot 2017-05-29 16 27 41" src="https://cloud.githubusercontent.com/assets/271103/26582058/8d04106e-450d-11e7-8460-1450789bf38d.png">

I found the cause, which is in 
[this line from Header.js](https://github.com/react-community/react-navigation/blob/30ca3c1f80617abc28fdd71f0b37d4f62b3e388a/src/views/Header.js#L163).  On Android, this essentially cancels out the offset from `TITLE_OFFSET`.  Since there is not 'right' component but there is a 'left' back button, the style on the title's container is `{ left: 40, right: 0 }`, which causes the problem.  It would also be nice to have access to magic constants like `TITLE_OFFSET` as well.  Maybe there could be a config setting for those as well.

It took a lot of work to get the title to align to the center.  I suggest adding a property like `headerTitleAlign`.  That could allow someone like me to override the default behavior.  Would you be open to something like that?

By the way, I have fixed the problem in our app by subclassing Header.js and adding:
```
  _renderTitle(props: SceneProps, options: *): ?React.Element<*> {
    const view = super._renderTitle(props, options)
    // see https://github.com/react-community/react-navigation/blob/30ca3c1f80617abc28fdd71f0b37d4f62b3e388a/src/views/Header.js#L162
    // by setting the right to 0 and not the left, the title is off center
    // style is an array and we check for left/right being set and if so, match 
    let left, right
    for (const style of view.props.style) {
      if (style.left !== undefined) {
        left = style.left
      }
      if (style.right !== undefined) {
        right = style.right
      }
    }
    if (left !== undefined || right !== undefined) {
      if (left === undefined) {
        left = right
      } else if (right === undefined) {
        right = left
      } else {
        left = right = Math.max(left, right)
      }
      view.props.style.push({ right, left })
    }

    return view
  }
```
This logic works for centering only.

**Comment by hecvasro** [comment]
@StevePotter Adding an empty view as 'headerRight' works too.

**Comment by ShenghuGong** [comment]
@hecvasro   empty view means headerRight=null or headerRight=<View  /> ?

**Comment by hecvasro** [comment]
@ShenghuGong I meant `<View/>`.

**Comment by MoOx** [comment]
I added a border to the "headerTitle" component and we can see a diff on android and ios: on android it does not take 100% of the screen  when you add an element on the right. The center part is moved (which make sense in a way).
On iOS, the headerTitle always take 100%, even when you add a thing on the left or on the right.
Looks like a unification of the behavior is desired.

**Comment by kelset** [comment]
Pinging OP @StevePotter since this issue is quite old and related to an old version of the lib. If no answer I'll close in 7 days.

Moreover the comments provide ways to do this.

**Comment by MoOx** [comment]
The responsible code is still in master https://github.com/react-community/react-navigation/blob/d93acdd918a306fb911442eb0a9d40558869e339/src/views/Header/Header.js#L185
I don't really understand why there is such a different behaviour for those 2 platforms. It's really weird to (by default) does not center title in the header bar on android, especially when you use the same visual pattern for this 2 OS in your app. 

@Freddy03h I saw that you edited this recently to bring the iOS part below this code. Can you take a look to this issue and give us your thoughts? Thanks in advance!

**Comment by kelset** [comment]
> I don't really understand why there is such a different behaviour for those 2 platforms.

Because the two platforms ([android](https://developer.android.com/design/material/index.html), [ios](https://developer.apple.com/ios/human-interface-guidelines/bars/navigation-bars/)) have different guidelines?

**Comment by MoOx** [comment]
If you take the initial screenshot associated with this issue, I am really sure it's not the desired behavior on any platform.
I don't have to read android guidelines to see that the non centred text is not acceptable for the end user and won't be advised by any guidelines. Just look at the clock + title not aligned...

**Comment by kelset** [comment]
Well, then. Feel free to submit a PR to fix this issue, we'll review asap.

**Comment by Freddy03h** [comment]
It's different between Android and iOS because title isn't centered by default on Android.

Consequences of this behavior are :
- on iOS `left` and `right` must have the same values to keep the title centered (before my PR, `left` and `right` were always at `TITLE_OFFSET`, now `left` and `right` are set to `0` if there is no left **and** right component)
- on Android the title component take all the available space, `left` and `right` are independents and based of the associate left/right component.

For now, if you want a centered title component on Android and have a component on left or right, you must set an empty view on the opposite side.

If you want to unify this behavior between iOS and Android because you want to centered the title on both. You'll break the default Android behavior :
- for a left to right language with a title and a right component : the title will not be at the left of the header.
- for a right to left language with a title and a left component : the title will not be at the right of the header.

**Comment by kesha-antonov** [comment]
+1 Please fix guys 🥇

**Comment by abaumer** [comment]
+1 We're looking to do the exact opposite: left align titles on iOS to match Android. Seems it is not possible to override the styles on Animated.View in src/views/header/header.js line 222 which would otherwise provide the flexibility we're looking for. 

If there is a way to pass styles through to this component from NavigationOptions, we haven't found it yet. If you know of one let us know.

**Comment by verzil** [comment]
Latest 1.2.1 does not allow for flex styles in header, therefore it does not allow for center header for android. Is there going to be a fix for this, or any work arounds?

Thanks in advance!

**Comment by brentvatne** [comment]
hi, I've assigned myself to this and will look into it when I have some time. if anyone else wants to help it would be very welcome. we should probably use a completely different header implementation on android.

**Comment by Freddy03h** [comment]
I think it's can be cool to have an option on it instead of doing strict Platform difference in the component. `centeredTitle` and 'leftAlignTitle' for example, or `iosStyle` and `androidStyle`.

So if I want a left aligned title on iOS I can, and if I want a centered title on Android I can too.

**Comment by paramaggarwal** [comment]
To centre title text on Android, I was able to get away with this for now:
```
headerTitleStyle: {
  flex: 1,
  textAlign: "center"
}
```

**Comment by ikniaziuk** [comment]
Unfortunately,  `{ flex: 1, textAlign: 'center' }` doesn't work properly when you have either `headerRight` or `headerLeft`. Adding `headerRight` with empty `<View />` doesn't solve the problem when `index === 0` (root screen) and `headerLeft` not displayed.

**Comment by hlthi** [comment]
![585f81a6-0dd1-4d67-8257-8e0a0bd8c1ac](https://user-images.githubusercontent.com/16364199/40455185-84096048-5ef4-11e8-98d1-0eaf990028fa.jpg)
```javascript
static navigationOptions = {
title: 'Canlı Yardım',
    headerStyle: {
      backgroundColor: '#fff',
    },
    headerTintColor: '#000',
    headerTitleStyle: {
      fontWeight: '200',
      color: '#2c38ff',
      textAlign: 'center',
      flex: 1,
    },
}
```
![d49ac8be-c0e7-49e3-839e-f639b4a133d5](https://user-images.githubusercontent.com/16364199/40455187-8883f098-5ef4-11e8-9a57-8d819703f316.jpg)
```javascript
static navigationOptions = {
 title: 'Canlı Yardım',
    headerStyle: {
      backgroundColor: '#fff',
    },
    headerTintColor: '#000',
    headerTitleStyle: {
      fontWeight: '200',
      color: '#2c38ff',
      textAlign: 'center',
      flex: 1,
    },
    headerRight: <View />, // add headerRight for fix
}
```

**Comment by RnbWd** [comment]
I ran into the same issue on Android (not iOS) on the latest version. Adding marginLeft: 'auto' and marginRight: 'auto' worked for me.

```
navigationOptions: {
      title: 'BrightID',
      headerTintColor: '#fff',
      headerTitleStyle: {
        fontFamily: 'EurostileRegular',
        fontWeight: '200',
        fontSize: 24,
        marginLeft: 'auto',
        marginRight: 'auto',
      },
      headerBackground: (
        <LinearGradient
          colors={['#F52828', '#F76B1C']}
          style={{ flex: 1, width: '100%' }}
        />
      ),
    },
```

**Comment by avz** [comment]
Here is my ugly-ugly hack. Tested on `react-navigation` `v2.2.3`.

```js
import { createStackNavigator } from 'react-navigation';

import HeaderStyleInterpolator from 'react-navigation/src/views/Header/HeaderStyleInterpolator';
import Header from 'react-navigation/src/views/Header/Header';

/*
 * Copied from react-navigation/src/views/Header/Header.js
 */
const TITLE_OFFSET = Platform.OS === 'ios' ? 70 : 56;

createStackNavigator(
    {/* routes */},
    {
        navigationOptions: (...args) => ({
            header: props => {
                return <Header
                    {...props}
                    titleInterpolator={(props) => {
                        return {
                            ...HeaderStyleInterpolator.forCenter(props),
                            left: TITLE_OFFSET,
                            right: TITLE_OFFSET,
                        };
                    }}
                />
            },
            headerTitleStyle: {
                flex: 1,
                textAlign: 'center',
            },
        })
    }
)
```

**Comment by brentvatne** [comment]
working on https://github.com/react-navigation/react-navigation/pull/4588 which will make this easier

**Comment by PrinceSharzeel** [comment]
[](https://stackoverflow.com/questions/52866912/cannot-center-align-header-title-in-react-native-android)

Cant do this..please help with it

**Comment by PrinceSharzeel** [comment]
[https://stackoverflow.com/questions/52866912/cannot-center-align-header-title-in-react-native-android](url)

Please solve this issue

**Comment by brentvatne** [comment]
@PrinceSharzeel - please read the comment directly above yours :P 

`headerLayoutPreset: 'center'`

done
