### ISSUE TITLE
TabRouter has no initialRouteParams option.

### ISSUE THREAD

**Issue by simonemarinelli** [react-navigation/react-navigation#1790]
It would be nice to have the initialRouteParams like in StackRouter.

**Comment by kelset** [comment]
Closing since the `initialRouteName` param exists now.

**Comment by alexisbronchart** [comment]
@kelset `initialRouteName` exists but not `initialRouteParams`. Could you reopen?

**Comment by kelset** [comment]
Ah gotcha. Sure.

**Comment by MrHubble** [comment]
@kelset I believe this can be closed again please as it was added in [1.0.0-beta.28](https://github.com/react-navigation/react-navigation/releases/tag/v1.0.0-beta.28). Thanks.
