### ISSUE TITLE
screenProps not getting computed properly on nested routers

### ISSUE THREAD

**Issue by mikelambert** [react-navigation/react-navigation#1848]
I am defining a `TabNavigator` containing a wrapped `StackNavigator`. When I nest the Routers in each other, the initial computation of `navigationOptions` does not have access to all the screenProps I had expected it to. (Particularly, it only has access to the Tab `screenProps`, not the Stack's dynamic `screenProps`).

My `WrappedStackNavigator` is as follows, and pulls in react/intl props to pass in for use by the `navigationOptions` function of my Firstview.

```
class FirstView extends React.Component {
  static navigationOptions = ({ screenProps }) => ({
    title: screenProps.intl.formatMessage(Myi18nMessage),
    headerLeft: <Button onPress={screenProps.onAction}>{screenProps.stateData}</Button>,
  });
}
const MyStackNavigator = StackNavigator({
  FirstRoute: { screen: FirstView },
});

class _WrappedStackNavigator extends React.Component {
  render() {
    return <StackNavigator
      screenProps={
        intl: this.props.intl,
        stateData: this.props.stateData,
        onAction: this.props.someFunction,
      }
    />;
  }
}
const WrappedStackNavigator = connect({
  state => ({
    stateData = state.reduxState,
  }),
  dispatch => ({
    someFunction: dispatch(someFunction()),
  })
)(injectIntl(_WrappedStackNavigator));
WrappedStackNavigator.router = MyStackNavigator.router;
```

This all works fine, alone. Unfortunately, when I stick this in a `TabNavigator`, things go downhill. For example, when I try this, things break:
```
const TabNav = TabNavigator({
  FirstTab: WrappedStackNavigator,
});
...
class MyApp extends React.Component {
  render() {
    return <TabNav screenProps={{prop1: True}} />;
  }
}
```

In particular, it crashes on the following error:
```
TypeError: Cannot read property 'formatMessage' of undefined
    at _class2.navigationOptions (http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false&hot=true:104821:47)
    at applyConfig (http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false&hot=true:98645:44)
    at Object.getScreenOptions (http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false&hot=true:98696:20)
    at Object.getScreenOptions (http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false&hot=true:98679:39)
    at TabView.render (http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false&hot=true:99372:28)
```

From what I can tell, `TabView` is attempting to render the first component:
```
    const options = router.getScreenOptions(
      this.props.childNavigationProps[state.routes[state.index].key],
      screenProps || {}
    );
```
which in `getScreenOptions/createConfigGetter`, it detects the first component is a Navigator, and runs:
```
    outputConfig = Component.router.getScreenOptions(
      childNavigation,
      screenProps
    );
```
This in turn evaluates the Component's navigationOptions.

Unfortunately, it does this entirely on the Component class, and not the rendered instantiated Component that has the redux/intl/etc state available. So things break because the `static navigationOptions` function above cannot depend on any `screenProps` in the component....and can only defend on the `screenProps` passed into the top-level `<TabView />`. (And of course, I don't want to stick my entire app's state/dispatch/etc into the toplevel `<TabView>`, as that'd be a horrible abstraction.)

Am I missing something here? Or using it wrong? Or an actual bug/design limitation of `react-navigation`?

My workaround is to basically just `return null` from the `static navigationOptions` function if my desired `screenProps` are not available, which helps get it rendered on the frame, and then on subsequent renders it is passed all the necessary `screenProps` I expect.

FWIW, I'm running with:
react-navigation: 1.0.0-beta.11
react-native: 0.45.0

**Comment by mikelambert** [comment]
Upon more digging and understanding, I think I can sum up my problem as:

The `TabView` needs to ask each tab's Router for the value of `tabBarVisible` or `tabBarLabel`. But instead of stopping at the StackRouter's `navigationOptions`, the StackRouter is in turn computing the first Screen's `navigationOptions` to merge as well.

And I assume the Screen (or the Stack) hasn't actually been rendered yet, so there's no way to rely on the dynamic values I pass in my `render()`.

I personally don't think the `TabView` should be asking the individual Screen for the value of `tabVar*` properties. But maybe that's just a consequence of the `createConfigGetter` chained design, since the Stack itself *does* care about what the Screen thinks for various Stack properties.

Not sure what a fix to `react-navigation` would even be, here...

But if this is intentional, it's certainly confusing, but I can see the argument. And maybe my "early-return" from my `navigationOptions` is the best answer, since I will never be using them to compute `tabBar*` properties.

Curious if anyone more experienced can weigh in here on what the correct approach is here, though...since the docs/examples don't cover these situations at all.

**Comment by mikelambert** [comment]
Though this seems like a bug:

Given the merging behavior I noticed and described above, it causes the `title` field of a nested Stack screen's `navigationOptions` (for the Stack titlebar)....to get merged into the Tab's navigationOptions, and so it becomes the name of the tab itself, too. And navigating the Stack seems to change the name of the Tab on the bottom of the screen, because they both use and depend on the `title` property of `navigationOptions`.

:(

**Comment by kelset** [comment]
Pinging OP @mikelambert since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open, because if I get no answer in the next 7 days I will close it.

That said, from my understanding, the behaviour of the tab-bar comes from `react-native-tab-view`.

**Comment by mikelambert** [comment]
It's been months since I've touched react-navigation code (or worked on RN code), so a lot of this state has been paged out in my mind, which is why I did my best to document things in the above bug for those who have this state paged-in memory.

I understand it's an old version of the lib (namely, because this bug sat here until now). Do you believe the new lib fixes this version, or does it just shuffle things around enough that you are no longer sure if it applies?

And are you suggesting that the problem with `screenProps` is in tab-view, and I should be filing my complaint there instead? From what I remember, this bug relates to the way things are configured and set up (and state is passed around), which is at a higher-level than `react-native-tab-view`, which is just called-and-used from `react-navigation`.

**Comment by kelset** [comment]
Gotcha.
To be honest, I haven't had enough time to dig deep into the issue you presented, but since a lot happened since Jun (which is now ~5 months ago) I was hoping that maybe simply it was fixed and you forgot to update/close the issue.
But since it doesn't look like the case, I'll keep this open for further investigation.

Thanks for your reply.

**Comment by serhiipalash** [comment]
Hi @mikelambert !
Can you share your setup of StackNavigator wrapped with IntlProvider?
Is there any solution without `injectIntl`? Is it possible to use 'intl` as context not as prop?
I can't fix this bug https://github.com/react-navigation/react-navigation/issues/2770 that's why I am asking.

**Comment by brentvatne** [comment]
we're discussing getting rid of `screenProps`. @satya164 gave a good outline of what needs to be done in https://github.com/react-navigation/react-navigation/issues/2770#issuecomment-355812804 which I think @serhiipalash is referring to here. we should have docs on internationalization as well..

see: https://github.com/react-navigation/rfcs/pull/5
and i created this issue to add i18n docs to website: https://github.com/react-navigation/react-navigation.github.io/issues/45
