### ISSUE TITLE
Feature: export DrawerNavigatorItem

### ISSUE THREAD

**Issue by slorber** [react-navigation/react-navigation#1858]
Hi,

DrawerNavigatorItems iterate over the items and build for each item a TouchableItem. I think it would be nice to export this element as a new `DrawerNavigatorItem` component so that people could use it in addition to existing `DrawerNavigatorItems`.

For example, I want to do:

```
const CustomDrawerContent = (props) => (
  <View>
    <View
      display="flex"
      alignItems="center"
      justifyContent="center"
      width="100%"
      padding={20}
    >
      <Image
        height={60}
        width={60}
        resizeMode="contain"
        source={require("./../resources/icon.png")}
      />
    </View>
    <DrawerItems
      {...props}
    />
    <DrawerItem onPress={() = props.logout()}>Logout</DrawerItem>
  </View>
);
```

Basically I want to reuse the DrawerItem component already defined inside DrawerItems except it should not trigger any navigation in my app.

**Comment by brentvatne** [comment]
please re-post to https://react-navigation.canny.io/feature-requests if this is important for you. re-organizing issues to focus on bug reports here and feature requests on canny. thanks!
