### ISSUE TITLE
setParams callback function

### ISSUE THREAD

**Issue by joncursi** [react-navigation/react-navigation#1895]
I noticed that if you run `navigation.setParams` in succession, i.e.:

```js
    navigation.setParams({
      headerLeft: { ... }
    });

    navigation.setParams({
      headerRight: { ... }
    });
```

Sometimes only one `setParams` gets applied. I think there is a conflict in execution and the latter `setParams` is over-riding the first.

This is a contrived example, where you would obviously just move `headerLeft` and `headerRight` into a single `setParams`, however there are many use-cases where multiple `setParams` need to exist to keep your component DRY (i.e. abstracting various `setParams` methods into different component methods.

It would be great if `setParams` accepted a second argument, an optional callback. This way you could run:

```js
    navigation.setParams({
      headerLeft: { ... }
    }, () => this._someMethod());
```

Where `_someMethod` is:

```js
_someMethod() {
      navigation.setParams({
      headerRight: { ... }
    });
}
```

Allowing you to chain `setParams` calls in series, ensuring each one gets applied and not over-written by the next call. Basically identical to how react's built-in `setState` method accepts an optional callback argument.

**Comment by brentvatne** [comment]
please re-post to https://react-navigation.canny.io/feature-requests if this is important for you. re-organizing issues to focus on bug reports here and feature requests on canny. thanks!
