### ISSUE TITLE
headerStyle broken in TabNavigator

### ISSUE THREAD

**Issue by joncursi** [react-navigation/react-navigation#1899]
The `headerStyle` navigationOption has no effect for screens that are direct descendents of a `TabNavigator`, even though other header options such as `headerTitle`, `headerRight`, etc., still work.

**Comment by kyo504** [comment]
@joncursi I was also faced with a similar issue. In my case, `TabNavigator` was wrapped in `StackNavigator` and `headerStyle` was set in navigatorConfig like below.
```javascript
const routeConfigs = {
  Tabs: {
    screen: TabNavigator,
  },
  Post: {
    screen: PostScreen,
  },
  Settings: {
    screen: SettingsScreen,
  },
};

const navigatorConfig = {
  cardStyle: {
    shadowOpacity: 0,
  },
  headerMode: 'screen',
  mode: 'card',
  transitionConfig: () => ({ screenInterpolator: CardStackStyleInterpolator.forHorizontal }),
  navigationOptions: ({ header }) => ({
    ...header,
    headerTintColor: '#888888',
    headerStyle: {
      backgroundColor: '#ffffff',
      shadowColor: 'white',
      elevation: 0,
    },
  }),
};
```
In this case, the dynamic change request of `headerStyle` in TabView via setParams didn't work for me. So, I removed `headerStyle` in StackNavigator navigationOptions. Then it worked fine.

**Comment by joncursi** [comment]
@kyo504 Thanks, I'm able to reproduce the same result. The unfortunate part is that I want to use `headerStyle` in StackNavigator navigationOptions to set the defaults that 99% of screens will use, and then over-ride the default at the screen level for the small number of screens that need to do this.

But this does not work currently, since setting `headerStyle` on StackNavigator navigationOptions prevents you from being able to over-ride at the screen level, at least for screens wrapped by a TabNavigator.

**Comment by kelset** [comment]
Pinging OP @joncursi since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open, because if I get no answer in the next 7 days I will close it.

**Comment by joncursi** [comment]
Please keep it open, it’s still a bug

**Comment by llamaluvr** [comment]
Heads-up that this bug adds an extra layer of complication with Android and translucent status bars (see https://github.com/react-community/react-navigation/issues/12). The best way I've found to work around issue 12 is by adding a topPadding to the headerStyle (so the translucent status bar covers area that's the same color as the status bar). Now that I have a feature request in my app that requires to changing styles on individual children, I have to make sure that the headerStyle I was applying to work around the Android status bar bug is applied separately to every child in my stack.

**Comment by satya164** [comment]
This looks like the same thing as #2580. I'm closing this since the solution has been suggested there. If it's not the same, please comment here with a code sample and I'll re-open the issue.

**Comment by llamaluvr** [comment]
@satya164  These are the same issue, so do just keep one issue open, but I do not see a feasible solution posted there, and this is definitely still a problem. I explain further in I explain further in https://github.com/react-navigation/react-navigation/issues/2580. It's not consistent or intuitive for the child screen here to be able to override every other header property other than `headerStyle`, and the workarounds result in code that is very fragile when applied across a non-trivial application.
