### ISSUE TITLE
Request: Can you expose Header as a standalone component taking in Navigation Options

### ISSUE THREAD

**Issue by ramamurthynagaraj** [react-navigation/react-navigation#1933]
### Current Behavior
Hi, React Native provides Modal component, but the Navigator component has been deprecated. 
At present, react-navigation library doesn't provide screen level transistionConfig. 
We have a need where in all screens in the stack should slide in from left, but only certain screens(modals) to be animated from bottom. There are issues open regarding the same.

Currently we were able to use the undocumented Header Component along with React-Native's Modal, but I would like to know if its possible to document it and maybe clean up the required props for standalone consumption.
e.g 
```
import Header from 'react-navigation/src/views/Header'

           <Modal
                animationType="slide"
                visible={this.props.isModalVisible}
                onRequestClose={this.props.onCancel}>
                <View style={styles.newScene}>
                    <Header scene={{index: 0}}
                        navigation={{state: {index: 0}}}
                        getScreenDetails={() => ({options: {
                            headerLeft: this.renderLeftButton(),
                            headerStyle: styles.navigationBar,
                            headerTitleStyle: styles.navigationBarTitle,
                            title: this.props.title
                        }})}/>
                    <ModalContent />
                </View>
            </Modal>
```

### Expected Behavior
It would be great if we can expose the Header component and just make navigationOptions as the only prop instead of scene, navigation and getScreenDetails.
e.g
```
import {Header} from 'react-navigation'

<Header navigationOptions={{
    title: 'Standalone Header'
}} />
```

### Your Environment
| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.9
| react-native     |  0.42.3
| node             | v6.3.1
| npm     |3.10.3

**Comment by Barylskyigb** [comment]
@kelset in most cases you can customize the header in the way it’s described in the link you provided, but not always. For example, if one uses react-native-swiper (like myself) and you need a custom header on each slide, it’s impossible to implement this without using exposed Header component.

**Comment by kelset** [comment]
Gotcha. Then I'll keep this open. Thanks for the feedback

**Comment by alejomendoza** [comment]
@ramamurthynagaraj your solution breaks in `react-navigation: 1.0.0-beta.19`

**Comment by brentvatne** [comment]
this sounds reasonable, if someone can open a rfc with more info that would be appreciated: https://github.com/react-navigation/rfcs

otherwise, please repost the feature request to https://react-navigation.canny.io/
