### ISSUE TITLE
TabRouter and StackRouter have divergent API contracts

### ISSUE THREAD

**Issue by mikelambert** [react-navigation/react-navigation#1939]
I discussed/discovered this in context here: https://github.com/react-community/react-navigation/issues/271#issuecomment-309449578

Namely, a `StackRouter.getStateForAction` contract on `return null` behaves differently when embedded in a `TabRouter` vs `StackRouter`.

When the `StackRouter` returns `null` to the parent `TabRouter`, the `TabRouter` will treat it as a no-op, returning the existing state:
```
          const route = childRouter.getStateForAction(action, childRoute);
          if (route === null) {
            return state;
          }
```

Whereas when the `StackRouter` returns `null` to the parent `StackRouter`, it propagates up further, blowing away its own parent state (in which case, blowing away my parent redux state):
```
        const activeTabState = activeTabRouter.getStateForAction(
          action.action || action,
          activeTabLastState
        );
        if (!activeTabState && inputState) {
          return null;
        }
```

Might possibly be related to https://github.com/react-community/react-navigation/issues/1852, in terms of the contract for `return null` and what it means...

**Comment by vincent1988** [comment]
+1

**Comment by brentvatne** [comment]
cleaning up some old issues, it's unclear to me if this is still a problem. if so, a pr would be welcome, even in the form of a failing test! thanks!

**Comment by mikelambert** [comment]
I spent a day or two debugging this in my code to figure it out, and decided to be a good citizen and go all the way down into the code and give this project a root cause, and how this API contract was inconsistent and could be made clearer.

I'm sad to see it closed out of hand without investigating. I get that code has changed and it may no longer be relevant at all. But you have a lot more state than I do, on what's changed in the last year of development. And yes, I get that it's the nature of popular projects that you fall behind on issues And bug reports.

I'm not actively in my RN codebase, and am working on other things now and into the foreseeable future, so I do not expect to spend another day reloading state to figure out if this is still a problem. If this is a problem, I'm sure you'll notice from the stackoverflows as people get confused and get contradictory answers on why "nesting doesn't work". And then if necessary, someone can do the work to figure out root causes. Who knows, maybe they'll even stumble on this issue, too. :)

Good luck with the cleanup, hope you can stay on top of issues going forward!

**Comment by brentvatne** [comment]
cc @ericvicenti
