### ISSUE TITLE
Uncaught (in promise) Unsupported platform

### ISSUE THREAD

**Issue by zarcode** [react-navigation/react-navigation#1959]
Hi, thanks for the library. I am using it on Web, with this webpack configuration:

```
const webpack = require('webpack');

const path = require('path');

module.exports = {
  devServer: {
    contentBase: path.join(__dirname, 'build'),
    // enable HMR
    hot: true,
    // embed the webpack-dev-server runtime into the bundle
    inline: true,
    // serve index.html in place of 404 responses to allow HTML5 history
    historyApiFallback: true,
    port: 3000
  },
  devtool: 'source-map',
  entry: [
    'webpack-dev-server/client?http://localhost:3000',
    'webpack/hot/only-dev-server',
    'react-hot-loader/patch',
    path.join(__dirname, '../index.web.js')
  ],
  module: {
    rules: [
      {
        test: /\.js$/,
        include: [
          path.resolve(__dirname, '..', 'index.web.js'),
          path.resolve(__dirname, '..', 'src'),
          path.resolve(__dirname, '../node_modules/react-native-tab-view')
        ],
        loader: 'babel-loader?+cacheDirectory'
      },
      {
        test: /\.(gif|jpe?g|png|svg)$/,
        loader: 'url-loader',
        query: { name: '[name].[hash:16].[ext]' }
      },
    ]
  },
  output: {
    path: path.join(__dirname, 'build'),
    filename: 'bundle.js'
  },
  plugins: [
    new webpack.HotModuleReplacementPlugin(),
    new webpack.NamedModulesPlugin(),
    new webpack.DefinePlugin({
      'process.env': {
        NODE_ENV: JSON.stringify('development')
      },
    })
  ],
  resolve: {
    modules: [
      path.join(__dirname, '..', 'node_modules')
    ],
    alias: {
      'react-native': 'react-native-web',
      'react-navigation': 'react-navigation/lib/react-navigation.js',
    }
  }
};
```

### Current Behavior

I am getting this error in console: "Uncaught (in promise) Unsupported platform".

### Expected Behavior

Not showing console error.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  ^1.0.0-beta.11
| react-native     |  16.0.0-alpha.12
| node             | 6.9.1
| npm or yarn      | 5.0.3

**Comment by HudsonHughes** [comment]
I am also dealing with this problem. I thought react-navigation worked with react-native-web.

**Comment by damiaozi** [comment]
I am also dealing with this problem.How to resolve?
can react-navigation well done on web?

**Comment by xml** [comment]
related/same: https://github.com/react-community/react-navigation/issues/1660

**Comment by Connorelsea** [comment]
I am also dealing with this problem when attempting to use StackNavigator and react-everywhere/react-native-web

**Comment by wojdziw** [comment]
Same here, react-native-web and react-navigation not working together

**Comment by kelset** [comment]
Pinging OP @zarcode since this issue has not been active for a while, and it's related to an old version of the lib. Moreover, as mentioned in the README, we "froze" the web support.

Please let me know if you want this to remain open; if I get no answer in the next 7 days I will close it.

**Comment by zarcode** [comment]
Yes, it's ok to freeze web support and set focus on solving other more important issues.
