### ISSUE TITLE
Improvement: navigation.state.params should be empty object instead of undefined

### ISSUE THREAD

**Issue by tyleralves** [react-navigation/react-navigation#2046]
It is inconvenient that the `navigation.state.params` property is undefined when no route params are passed in. In components that rely on a property of params, one must add an additional check that params exists, before checking that the desired property exists:

`const photoType = (navigation.state.params && navigation.state.params.photoType) || 'self';`

If the `params` property was an empty object rather than undefined, it would be much nicer:

`const photoType = navigation.state.params.photoType || 'self';`

**Comment by jurajkrivda** [comment]
This is my approach to this problem


```
import { path } from 'ramda';
import { withProps } from 'recompose';

withProps(props => ({
  photoType: path([ 'navigation', 'state', 'params', 'photoType' ], props),
}))
```

**Comment by nonameolsson** [comment]
@jurajkrivda Nice solution! But as @tyleralves says, I also think that it should be an empty object. Then it isn't necessary with a third-party library to perform such check.

**Comment by brentvatne** [comment]
yeah this seems pretty reasonable

**Comment by peterpme** [comment]
@tyleralves , @nonameolsson, @jurajkrivda #3510 recently merged in offers:

```
this.props.navigation.getParam('name', 'default value')
```

https://reactnavigation.org/docs/navigation-prop.html#getparam-get-a-specific-param-value-with-a-fallback

Thanks!

**Comment by brentvatne** [comment]
i'd suggest using `getParam` - there's a lot of discussion in this rfc about it: https://github.com/react-navigation/rfcs/pull/21
