### ISSUE TITLE
[StackNav] static navigationOptions not working as described in the documentation

### ISSUE THREAD

**Issue by ixje** [react-navigation/react-navigation#2132]
The [documentation](https://reactnavigation.org/docs/navigators/navigation-options#Stack-Navigation-Options) says the following things:

> the options can be a function that takes the following arguments, and returns an object of navigation options that **will be override the route-defined and navigator-defined navigationOptions**

and

> Whenever both the navigator and screen define the same option (e.g. headerTintColor), the screen wins.
The short summary of these 2 quotes is that the static navigationOptions of the screen should _always_ win from options sets elsewhere.

Then from [StackNavigator Screen navigation options](https://reactnavigation.org/docs/navigators/stack#Screen-Navigation-Options) there is the following :

> [headerTitle](https://reactnavigation.org/docs/navigators/stack#headerTitle) String or React Element used by the header. **Defaults to scene `title`**

> [title](https://reactnavigation.org/docs/navigators/stack#title) String that can be used as a fallback for `headerTitle` and `tabBarLabel`

Which I interpret as follows:
if headerTitle is not present, it shall fallback to using `title`
if headerTitle and `title` are present, it shall use `title`

### Current Behavior
`static navigationOptions` on the screen do not have precedence over `navigationOptions` defined in the [RouteConfigs](https://reactnavigation.org/docs/navigators/stack#RouteConfigs) 

e.g.
in RouteConfigs of a StackNavigator
```
    MenuPlace: {
        screen: MenuScreen,
        navigationOptions: {
            ...defaultOptions,
            headerTitle: 'bla'
        }
    }
```
in a Screen component
```
    static navigationOptions = {
        headerTitle: 'bla2'
    }
```

I expect the header title to be 'bla2', instead it's 'bla1' as configured in the RouteConfigs.

### Expected Behavior
I ran a couple of tests and created the following table to show the actual vs expect results, and with which configuration
![table](http://i.imgur.com/fYEBlw6.png)

The way to read this is as follows. Taking test case 4 as example would be:
**RouteConfigs**
```
    MenuPlace: {
        screen: MenuScreen,
        navigationOptions: {
            ...defaultOptions,
            **headerTitle: null**
        }
    }
```
**Screen component**
```
    static navigationOptions = {
        headerTitle: 'test1',
        title: 'test2'
    } 
```
**Actual header title:** 'test2'
**Expected header title:** 'test1'

As you can see in the table test case 1 & 4 are mutually exclusive. One of the 2 cases is right, and equally so 1 of the 2 cases is wrong depending on how you interpret the documentation.

Suggestion/improvement: 

1. fix the RouteConfig navigationOptions vs static navigationOptions precedence issue in code, or correct the documentation. I'm indifferent how to solve it as long as it's consistent.
2. fix the `headerTitle` vs `title` precedence (see test case 1 & 4) in code, or correct the documentation.
 
### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  react-navigation@1.0.0-beta.11
| react-native     |  react-native@0.46.0
| node             | v7.10.0
| npm or yarn      | npm 4.2.0
Only tested on iOS simulator due to broken Android Dev env.

**Comment by lykfe** [comment]
this is very annoying :(

**Comment by alohawav** [comment]
@ixje are you using redux connect in this component? If so, try make a const and then add .navigationOptions:

```js 
const ConnectedElement = connect(...)(Element),
);

ConnectedElement.navigationOptions = () => {
  title: 'whatever',
}

export default ConnectedElement;
```

**Comment by kelset** [comment]
Pinging OP @ixje since this issue has not been active for a while, and it's related to an old version of the docs.

Please let me know if you want this to remain open; if I get no answer in the next 7 days I will close it.

**Comment by ixje** [comment]
It's still shows wrong behaviour on version `1.0.0-beta.21`. The documents have changed just slightly, but for completeness sake I'll quote them again.

> `headerTitle` - String, React Element or React Component used by the header. **Defaults to scene title**

> `title` - String that can be used as a **fallback for headerTitle**

I keep the same interpretation what the above means as before:

> Which I interpret as follows:
> if headerTitle is not present, it shall fallback to using title
> if headerTitle and title are present, it shall use title

I created a sample project showing all test cases. It's not the prettiest, but shows the issue. Find it here:  https://github.com/ixje/react-native-wrong-navigationoptions

What goes wrong:
- `headerTitle` takes precedence over `title` when routeconfig has no `headerTitle` key. Expected: `title` have precendence over `headerTitle`. (case 1)
- if routconfig `headerTitle` key is present and it's value is `null`, then it takes precedence over the `headerTitle` (in static navigationOptions) (case 6).  Expect: static navigation options `headerTitle` to take precedence over route config. Note: a `title` key in static navigation options, _does_ take precedence over routeconfig in the same setting (case 4 + 5).
- if routeconfig `headerTitle` key is present and has a value that is not `null`, then it takes precedence over static navigation options (both `title` and `headerTitle`) (case 6,7 & 7). Expected: static navigation options to have precedence over routeconfig.

**Comment by kelset** [comment]
Awesome, thanks :)

**Comment by brentvatne** [comment]
> if headerTitle and title are present, it shall use title

this is not the correct interpretation.

> title - String that can be used as a fallback for headerTitle

by "used as fallback" this means that if `headerTitle` is not provided.

I followed the table that you provided above and the results were not the same as what you recorded, which leads me to believe that you may have had some other things going on in your code that you didn't account for. see the barebones snack example where you can play with this: https://snack.expo.io/ByH3S1KIG

**Comment by sourabhv** [comment]
`navigationOptions` don't work if you are using `withTheme` from `styed-components/native`. But @alohawav's solution still works :+1:

**Comment by AliYar-Khan** [comment]
> 
> 
> @ixje are you using redux connect in this component? If so, try make a const and then add .navigationOptions:
> 
> ```js
> const ConnectedElement = connect(...)(Element),
> );
> 
> ConnectedElement.navigationOptions = () => {
>   title: 'whatever',
> }
> 
> export default ConnectedElement;
> ```

i tried you solution but it didn't work

**Comment by RenanZX** [comment]
For me the solution from @alohawav not works too

**Comment by anandh-pga** [comment]
my navigation option was not working inside the function based components why?
