### ISSUE TITLE
Disable Android/back button in StackNavigator

### ISSUE THREAD

**Issue by aaymont** [react-navigation/react-navigation#2138]
There is no ability to disable the Android/hardware back button when using the StackNavigator or assigning a function to it, such as closing the app when it's pressed.  It forces popping all the screens on the stack, which can lead to undesirable behavior.

**Comment by emsihyo** [comment]
me too.

**Comment by NamanArora** [comment]
Any news on this?

**Comment by nhuthan** [comment]
+1

**Comment by alzalabany** [comment]
is there even any hack we can apply to disable back button app wide ?

**Comment by peterlau** [comment]
@alzalabany Yes. Put this in your App.js
```
  componentDidMount() {
    BackAndroid.addEventListener('hardwareBackPress', this.handleBackPress);
  }
  componentWillUnmount() {
    BackAndroid.removeEventListener('hardwareBackPress', this.handleBackPress);
  }
  handleBackPress() {
    return true;
  }
```

**Comment by alzalabany** [comment]
@peterlau i did but callback never get called.
I have nested navigators can this affect listeners somehow? I applied this at root navigator but looks like event got intercepted by react navigation somewhere and prevent bubbling cause event never triggers

**Comment by VittoriDavide** [comment]
You could implement the onBackPressed in your MainActivity 

 ```
   @Override
    public void onBackPressed() {
    }
```

**Comment by brentvatne** [comment]
please re-post to https://react-navigation.canny.io/feature-requests if this is important for you. re-organizing issues to focus on bug reports here and feature requests on canny. thanks!
