### ISSUE TITLE
Make onDrawerSlide sliding position available at navigation and main screen props (for use in animations etc)

### ISSUE THREAD

**Issue by RobIsHere** [react-navigation/react-navigation#2157]
https://facebook.github.io/react-native/docs/drawerlayoutandroid.html#ondrawerslide
Provides the current status of drawer movement progress while opening and closing [0..1].

This is needed to build animations that depend on the current drawer sliding state.

My use case: a parallax drawer. Currently I have no way to find out the status of the drawer and have to implement my custom drawer.

**Comment by kelset** [comment]
Pinging OP @RobIsHere since this issue has not been active for a while, and it's related to an old version of the lib (and we improved a lot Drawer support).

Please let me know if you want this to remain open; if I get no answer in the next 7 days I will close it.

**Comment by RobIsHere** [comment]
As you see here https://github.com/react-community/react-navigation/blob/master/src/views/Drawer/DrawerView.js#L185 the onDrawerSlide callback is not attached.

So I think this should stay open.

**Comment by brentvatne** [comment]
please re-post to https://react-navigation.canny.io/feature-requests if this is important for you. re-organizing issues to focus on bug reports here and feature requests on canny. thanks!

**Comment by Jonovono** [comment]
@RobIsHere did you find a solution to this?

**Comment by RobIsHere** [comment]
No, I've given up with this lib because I've hit so many issues back then. I've had success without any navigation or routing abstraction lib. Better software architecture and way faster to implement.

**Comment by Jonovono** [comment]
@RobIsHere haha don't blame ya, thanks.

**Comment by RobIsHere** [comment]
@Jonovono Hehe :) That's not what I intended to say. I wish you good luck with rn ;)

**Comment by brentvatne** [comment]
this might be helpful: https://github.com/react-navigation/react-navigation-drawer/pull/40
