### ISSUE TITLE
Lightbox Modal Feature Request

### ISSUE THREAD

**Issue by quadsurf** [react-navigation/react-navigation#2253]
I see this feature common in other navigation libraries (like wix's react-native-navigation lib, or react-native-router-flux), so I was sad to not see it naturally supported in this react-navigation lib.

A few good examples of a lightbox modal:
1. https://github.com/react-native-community/react-native-modal
2. https://github.com/maxs15/react-native-modalbox

I can easily achieve this lightbox-style “modaling” with the 2 example libs just-mentioned, however, the big problem is that they are controlled by state rather than by navigation on stack (the better way).

A proper lightbox-style modal should behave more like a drawer or side-nav overlay that’s loaded onto stack, where it overlays on top of another screen but the screen underneath it is still visible (but darkened out a bit).

If I had the expertise to PR this, I gladly would, but I'm just not there yet. Please forgive.

**Comment by kelset** [comment]
Related https://github.com/react-community/react-navigation/pull/2308

**Comment by brentvatne** [comment]
please re-post to https://react-navigation.canny.io/feature-requests if this is important for you. re-organizing issues to focus on bug reports here and feature requests on canny. thanks!
