### ISSUE TITLE
Feature Request: Ability to refresh navigationOptions

### ISSUE THREAD

**Issue by dannycochran** [react-navigation/react-navigation#2330]
There are a number of issues related to the lifecycle around navigationOptions, which does not update after the initial render:

https://github.com/react-community/react-navigation/issues/2309
https://github.com/react-community/react-navigation/issues/2203
https://github.com/react-community/react-navigation/issues/940
https://github.com/react-community/react-navigation/issues/413

The common prescribed fix is to use "setParams" or put any state that controls the header configuration into the router parameters. This feels like a forced workaround when the header state is not necessarily part of a router parameter, but some other state.

Could navigationOptions take a property that controls whether it should re-render more aggressively? Or even a function like "shouldHeaderUpdate"?

**Comment by coderafei** [comment]
👍

**Comment by janreyho** [comment]
👍

**Comment by MarcelBlockchain** [comment]
@Antoine38660 
so is it fixed in this merge? Any example out there how to use it?
Thanks a lot

**Comment by Antoine38660** [comment]
@MarcelBlockchain we used the "`setParams` fix" but we are still looking for a better way to do! You can see how we did it in this commit : https://github.com/gitpoint/git-point/pull/193/commits/a10e9c9df8cffb6297b79ad8e1023e40b6c0a77c 😃 

Sorry for the late answer, I miss the notification...

**Comment by brentvatne** [comment]
please re-post to https://react-navigation.canny.io/feature-requests if this is important for you. re-organizing issues to focus on bug reports here and feature requests on canny. thanks!
