### ISSUE TITLE
Passing position through scene to be able to animate a custom TabBarLabel

### ISSUE THREAD

**Issue by tomasfrancisco** [react-navigation/react-navigation#2376]
I have a suggestion, let me know what do you think about it.

I would consider passing the position through scene props so we can be able to do animations based on the position of the scroll - just like it's already done with default label.

Here's the function I'm talking about: https://github.com/react-community/react-navigation/blob/ae9fb10e60d2735cd2debaae34483510aa9ab3e9/src/views/TabView/TabBarBottom.js#L60

Right now we only have access to `focused` and `tintColor`, but I guess would be nice to have the current position.

Let me know what you think and if it's worth to do a PR for it.

**Comment by kelset** [comment]
Hi @tomasfrancisco, thanks for the FR and sorry for the **really** late answer.

I think it would be great to expose something like that, and a PR would surely be appreciated.

**Comment by satya164** [comment]
You can do the following:

```js
tabBarComponent: props =>
  <TabBarBottom renderLabel={scene => <Label scene={scene} position={props.position} />} />
```

I'm against this change because
- The `renderLabel` method for `TabBarBottom` will differ from `TabBarTop` after this change, which is confusing
- `position` is not part of the current scene, so having it in `scene` is incorrect

**Comment by brentvatne** [comment]
please re-post to https://react-navigation.canny.io/feature-requests if this is important for you. re-organizing issues to focus on bug reports here and feature requests on canny. thanks!
