### ISSUE TITLE
Reset route stack to a new route with back animation

### ISSUE THREAD

**Issue by drpiou** [react-navigation/react-navigation#2390]
Is it possible to achieve a "resetTo" function to reset stack with back animation, like it was possible to do with Navigator component (http://facebook.github.io/react-native/releases/0.34/docs/navigator.html#resetto) ?

I search many places and didn't found anything that works fine. I found how to "replace" a scene (which is missing), but I miss the "resetTo" function also.

Beside I wonder why these "classical" functions are not implemented, I really need them.

Thanks in advance

**Comment by DanielRamosAcosta** [comment]
I miss this feature too :cry:

**Comment by luco** [comment]
That's a must.

**Comment by luco** [comment]
That's a must.

**Comment by brentvatne** [comment]
please re-post to https://react-navigation.canny.io/feature-requests if this is important for you. re-organizing issues to focus on bug reports here and feature requests on canny. thanks!
