### ISSUE TITLE
Simpler Left-to-right Stack Navigation transitions

### ISSUE THREAD

**Issue by aeirola** [react-navigation/react-navigation#2393]
Hi, an application I'm developing requires screen transitions in both normal right-to-left and inverse left-to-right transitions, depending on what screen one is navigating to.

It is rather simple to change the direction of the actual card transitions by implementing a custom `screenInterpolator` in the `transitionConfig` which checks the scene properties to see which transitions is wanted.

For the getting the header title to move in the correct direction, it becomes a bit nastier, since one needs to create a new class which extends `Header` and overrides the internal `_renderTitle` method to inject a custom `styleInterpolator`. Luckily, this is only a few lines of code.

The last thing, which is causing a lot of bad vibes for me, is changing the back swipe gesture direction. Currently, the only solution I've found is to create new functions and classes for `StackRouter`, `CardStackTransitioner` and `CardStack` in order to override the whole PanResponder in the `render` method of `CardStack`. All of this is a couple hundred lines of code, and has some serious risks of breaking on new versions of the library.

Would be nice to have some more configurability either in the configuration objects, or through easier extension of the classes.

I wonder if this is a common case in other applications as well? Would be nice to see if it would make sense to start planning a change in the codebase for support for this.

**Comment by nlwiskus** [comment]
+1 I'm also dealing with this issue. I took a look at what you're doing and got a bit frightened.. don't want to break anything. Would love it if in the future there was a navigation prop or something to deal with this.

`onPress={() => navigator.navigate({routeName: 'Settings', transitionStyle: 'inverted'}) }`

**Comment by kelset** [comment]
@aeirola @nlwiskus have a look at this [StackOverflow question](https://stackoverflow.com/questions/46624633/from-left-to-right-window-animation-with-react-navigation), it provides a solution on how to implement it.

That said I'll keep this one as Feature Request.

**Comment by aeirola** [comment]
@kelset Thanks for that, but unfortunately that doesn't provide the inverted swipe to go back.

Also noticed that starting from 1.0.0-beta.14, the `Header` component is wrapped, making it very tedious to override single methods of the components.

**Comment by kelset** [comment]
Ok, thanks for letting me know. Then this needs to surely remain open.

**Comment by kesha-antonov** [comment]
+1 Need it

**Comment by norbajunior** [comment]
+1 Need it

**Comment by aeirola** [comment]
Based on the +1 comments, there seems to be a desire for the feature elsewhere as well. I'll start working on a couple of PRs to enable this in the `StackNavigator` configuration without subclassing. I'll split the work into two separate PRs:

**Enable custom header transition interpolators**
I propose doing something similar to the existing `stackConfig.transitionConfig.screenInterpolator`, by exposing custom configs for the header transition styles. This would probably need separate interpolators for the left, center and right parts.

**Override back gesture direction**
Currently the `CardStack` back gesture swipe direction is determined by the `I18nManager.isRTL` value. I propose allowing overriding this from the `StackNavigator` configuration through something like a `stackConfig.navigationOptions.gestureDirection = sceneProps => 'left'` 


I'll try to provide some more detailed configuration API definitions and examples next week.

**Comment by aeirola** [comment]
@kelset Okay, so the idea for my configuration API changes is to try to mimic as much as possible from the existing conventions. I.e. not do anything too extraordinary and unfamiliar.

#### Header transitions
For the header transition configuration I'll propose adding three new configuration values:

- `headerLeftInterpolator?: (props: NavigationSceneRendererProps) => {},`
- `headerTitleInterpolator?: (props: NavigationSceneRendererProps) => {},`
- `headerRightInterpolator?: (props: NavigationSceneRendererProps) => {},`

placed alongside the already existing `screenInterpolator` under the `transitionConfig` return value. The function signature would be the same, and would apply to the three parts of the default `Header` component.

The left and right interpolators aren't really needed for nice left-to-right transitions, since the default fading transitions are direction independent. But probably good to add these for the sake of completeness.


#### Dismiss gesture direction

For the dismiss gesture I guess it's better to provide only configuration of the gesture direction, instead of complete control of the pan handlers. This would be in line with the convention of the `gestureResponseDistance` configuration option in `navigationOptions`. Since we need to support both vertical and horizontal transition directions, I propose adding a single common configuration option

 - `gestureDirection?: 'default' | 'inverted',`

to the `navigationOptions`. Here `default` would keep the current behaviour based on the value of `I18nManager.isRTL`, and `inverted` would just invert that default direction.


#### Example

All in all, an example of a `StackNavigator` with left-to-right navigation would look like this:

```javascript
const navigator = ReactNavigation.StackNavigator(routes, {
  mode: 'card',
  navigationOptions: params => ({
    gesturesEnabled: true,
    gesturesDirection: 'inverted',
  }),
  transitionConfig: () => ({
    screenInterpolator: sceneProps => {
      const { layout, position, scene } = sceneProps;
      const { index } = scene;
      const width = layout.initWidth;

      return {
        opacity: position.interpolate({
          inputRange: [index - 1, index, index + 1],
          outputRange: [ 0, 1, 0],
        }),
        transform: [{
          translateX: position.interpolate({
            inputRange: [index - 1, index, index + 1],
            outputRange: [-width, 0, width],
          }),
        }]
      };
    },
    headerTitleInterpolator: sceneProps => {
      const { layout, position, scene } = sceneProps;
      const { index } = scene;

      return {
        opacity: position.interpolate({
          inputRange: [index - 1, index, index + 1],
          outputRange: [ 0, 1, 0],
        }),
        transform: [{
          translateX: position.interpolate({
            inputRange: [index - 1, index, index + 1],
            outputRange: [-50, 0, 50],
          }),
        }]
      };
    },
  }),
});
```

Dynamic configuration per transition is left out of the example for the sake of clarity, but the user could easily configure the behaviour based on the navigation state from the function parameters.

#### Next steps

I'll start working on these changes in the code. Expect some PRs during this week.

**Comment by kelset** [comment]
Hey @aeirola thanks for document all the steps so well 👌
I'll ping some more ppl ( @vonovak @spencercarli @davepack  ) to take a look at this 'cause I am really not good at code reviewing ;)

**Comment by aeirola** [comment]
Thanks for pinging the appropriate people. The PRs can be found at #3075 and #3077

**Comment by vonovak** [comment]
@aeirola seems that both prs were merged, can this be closed?

**Comment by aeirola** [comment]
Sure, I'll go ahead and close the issue.

**Comment by marzieh-kazemi** [comment]
+ 1 Need it!

**Comment by jamessawyer** [comment]
Can it be top-to-bottom or bottom-to-top?

**Comment by brentvatne** [comment]
can someone post a feature request with more info to https://react-navigation.canny.io/ please? thanks! locking thread
