### ISSUE TITLE
createNavigator(...) and its parameters

### ISSUE THREAD

**Issue by alexkuc** [react-navigation/react-navigation#2405]
According to the official docs ([`createNavigator`](https://reactnavigation.org/docs/navigators/custom#createNavigator) and [`createNavigator`](https://github.com/react-community/react-navigation/blob/master/docs/guides/Custom-Navigators.md#createnavigator)), when creating custom navigator we need to supply only 2 parameters (i.e. `const MyApp = createNavigator(MyRouter)(MyView)`).

However, looking at the actual code, it appears that MyRouter can be supplied with 3 additional parameters.
https://github.com/react-community/react-navigation/blob/ae9fb10e60d2735cd2debaae34483510aa9ab3e9/src/navigators/createNavigator.js#L17-L22

The built-in navigators (i.e. `StackNavigator`, `TabNavigator` and `DrawerNavigator`) do use them.
https://github.com/react-community/react-navigation/blob/ae9fb10e60d2735cd2debaae34483510aa9ab3e9/src/navigators/DrawerNavigator.js#L72-L77
https://github.com/react-community/react-navigation/blob/ae9fb10e60d2735cd2debaae34483510aa9ab3e9/src/navigators/StackNavigator.js#L42-L47
https://github.com/react-community/react-navigation/blob/ae9fb10e60d2735cd2debaae34483510aa9ab3e9/src/navigators/TabNavigator.js#L45-L50

My question is the following - when creating custom navigator should we follow the docs or should we follow built-in navigators and supply 3 additional parameters?

**Comment by kelset** [comment]
Uhm actually yes, it looks like we should re-work a bit that section of the docs to explain also the other params that can be passed.

**Comment by brentvatne** [comment]
we're in the middle of refactoring this and the new api will be much more clean. we'll update the docs accordingly
