### ISSUE TITLE
Can we have the "back" action take a number of steps instead of a key?

### ISSUE THREAD

**Issue by pensierinmusica** [react-navigation/react-navigation#2478]
Hi,

I'm suggesting to change the API and have the [`Back`](https://reactnavigation.org/docs/navigators/navigation-actions#Back) action take a number of steps instead of a key as a parameter.

Imho is a more natural use case, and a friendlier interface, especially considering that in a Stack Navigator keys are hashes and don't correspond to the `routeName`.

So, let's say that I want to go back 2 steps, I'd just do something like this:

```js
const backAction = NavigationActions.back(2)
this.props.navigation.dispatch(backAction)
```

Let me now your thoughts, cheers!

**Comment by spencercarli** [comment]
Agreed. I think there is another issue similar to this but can't find it right now so will leave this open.

**Comment by levsero** [comment]
A possible alternative that I'd be happy with is if it would be possible to set a custom key on a route, I wouldn't mind using that to go back to the given screen. Totally agree as it currently is with hashed keys trying to use the key is not very practical.

**Comment by ratkus91** [comment]
Now it works like this
```
const backAction = NavigationActions.back();

this.props.navigation.dispatch(backAction); - 1
this.props.navigation.dispatch(backAction); - 2
...
this.props.navigation.dispatch(backAction); - n
```

**Comment by brentvatne** [comment]
please re-post to https://react-navigation.canny.io/feature-requests if this is important for you. re-organizing issues to focus on bug reports here and feature requests on canny. thanks!
