### ISSUE TITLE
Transitioning from Stack Navigator to Drawer Navigator, Drawer shows up while entering & leaving

### ISSUE THREAD

**Issue by deadcoder0904** [react-navigation/react-navigation#2539]
<img alt="stack-to-drawer-error" width="320" height="568" src="https://user-images.githubusercontent.com/16436270/30100514-c533122c-9306-11e7-95e6-90ec4e71ede1.gif" />

I think GIF speaks for itself 😝

**Comment by spencercarli** [comment]
Repro of this issue?

**Comment by deadcoder0904** [comment]
https://github.com/deadcoder0904/react-native-animations

**Comment by deadcoder0904** [comment]
@spencercarli Awesome Course btw 😂 Loved it !

**Comment by kelset** [comment]
Pinging OP @deadcoder0904 since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open (does it still happen in the latest version?); if I get no answer in the next 7 days I will close it.

**Comment by deadcoder0904** [comment]
Cool I'll check with the new version

**Comment by kelset** [comment]
Ping @deadcoder0904

**Comment by deadcoder0904** [comment]
Ohh wait I forgot checking now. I will reply in 15 minutes 😄

**Comment by deadcoder0904** [comment]
Yep it still exists -> https://github.com/deadcoder0904/react-native-animations

**Comment by nikoootine** [comment]
This issue also happens to me. Any updates on this?

**Comment by deadcoder0904** [comment]
Naah

**Comment by brentvatne** [comment]
I created a related issue on https://github.com/react-native-community/react-native-drawer-layout/issues/50

**Comment by brentvatne** [comment]
moving to umbrella issue
