### ISSUE TITLE
Expect nav state to have routes and index... error

### ISSUE THREAD

**Issue by nguyenhoanglam** [react-navigation/react-navigation#2551]
My app has a nest navigator (StackNavigator > DrawerNavigator) and implement replace mode like this:

```
const MainNavigator = DrawerNavigator({
  Home: {
    screen: StackNavigator({ Screen1: { screen: HomeScreen } })
  },
  About: {
    screen: StackNavigator({ Screen2: { screen: AboutScreen } })
  }
});

const AppNavigator = StackNavigator(
  {
    Splash: { screen: SplashScreen },
    Login: { screen: LoginScreen },
    Main: { screen: MainNavigator }
  },
  {
    headerMode: "none"
  }
);

const defaultGetStateForAction = AppNavigator.router.getStateForAction;

AppNavigator.router.getStateForAction = (action, state) => {
  if (state && action.type === "ReplaceCurrentScreen") {
    let routes = state.routes.slice(0, state.routes.length - 1);
    routes.push(action);
    return {
      ...state,
      routes,
      index: routes.length - 1
    };
  }
  return defaultGetStateForAction(action, state);
};

AppRegistry.registerComponent("Workforce", () => AppNavigator);
```
When I'm in Splash screen, if I navigate to Login screen, it works. But when I navigate to Main screen, it throws: 

`Expect nav state to have routes and index {"type":"ReplaceCurrentScreen","routeName":"Main","key":"Main"}`

```
  //   it works
  goToLogin() {
    this.props.navigation.dispatch({
      type: "ReplaceCurrentScreen",
      routeName: "Login",
      key: "Login"
    });
  }

  //   throws error
  goToMain() {
    this.props.navigation.dispatch({
      type: "ReplaceCurrentScreen",
      routeName: "Main",
      key: "Main",
    });
  }
```

Have solution for this?

**Comment by spencercarli** [comment]
Could you put together a demo app with this issue? I guess the issue here is that `Main` is a drawer rather than a screen and isn't getting the necessary props it needs

**Comment by nguyenhoanglam** [comment]
@spencercarli  yes, Main is a drawer navigator. So, how to pass props to it?

**Comment by wilomgfx** [comment]
Having the same problem here...

**Comment by rochapablo** [comment]
Same here, I'm following the example and these are navigators

``` javascript
const stack = StackNavigator(
  {
    Login: { screen: Login },
    Register: { screen: Register }
    ...
  },
  {
    ...settings,
    initialRouteName: 'Login'
  }
)

const drawer = DrawerNavigator(
  {
    Dashboard: { screen: Dashboard },
    ...
  },
  {
    ...settings,
    contentComponent: (props) => <Sidenav {...props} />
  }
)

export const AppNavigator = StackNavigator(
  {
    LoginNav: { screen: stack },
    DrawerNav: { screen: drawer }
  },
  {
    ...settings,
    initialRouteName: 'LoginNav'
  }
)
```

**Comment by spencercarli** [comment]
Interesting. What if you just tried to navigate directly to `Login` rather than to the root navigator and then the child?

**Comment by rochapablo** [comment]
Tried that too! Anyway it seems that my problem is to be using ```createFilter(```, for now I've commented the block and it's working.

**Comment by jonbronson** [comment]
Running into this same issue.

**Comment by gianpieroc** [comment]
I'm facing the same issue... do you have any solution for this?

**Comment by Alver23** [comment]
Running into this same issue. Do you have any solution for this?.

![image](https://user-images.githubusercontent.com/16018328/36038117-b8dc6e00-0d8c-11e8-8c53-41a741489934.png)

**Comment by brentvatne** [comment]
@Alver23 - please provide an example on https://snack.expo.io to reproduce this issue. not much we can do without being able to reproduce it. also be sure you're using the latest version (1.0.3 at the time of posting).

**Comment by Alver23** [comment]
I will update the library and follow the documentation, if I have a problem I will let you know, thank you
@brentvatne

**Comment by brentvatne** [comment]
closing for now! please create a new issue with our new issue template if you are still having the problem @Alver23

**Comment by karloluis** [comment]
Any links to the new issue or to a working solution for this issue?

**Comment by Alver23** [comment]
@karloluis you are working with redux in reacting native ?

**Comment by karloluis** [comment]
@Alver23 That's correct.

**Comment by Alver23** [comment]
Each time you add a route to the navigation, you must clean the redux status

This code is my reducer combined with immutable

`// Dependencies
import {fromJS} from 'immutable';
import {NavigationActions} from 'react-navigation';
import includes from 'lodash/includes';

// Components
import AppNavigation from '../../components/Navigation';

const initialState = fromJS(AppNavigation.router.getStateForAction(
  AppNavigation.router.getActionForPathAndParams('Eula'),
));

// Utils
import {getCurrentRouteName} from '../../utils/navigation';

export default function NavigatorReducer(state = initialState, action) {
  const nextState = AppNavigation.router.getStateForAction(action, state.toJS());

  // Is this a navigation action that we should act upon?
  if (includes(NavigationActions, action.type)) {
    // lets find currentScreen before this action based on state
    const currentScreen = getCurrentRouteName(state);
    // determine what the new screen will be after this action was performed
    const nextScreen = getCurrentRouteName(nextState);

    if (nextScreen !== currentScreen) {
      nextState.currentRoute = nextScreen;
      console.log(`screen changed, punk: ${currentScreen} -> ${nextScreen}`);
    }

    return fromJS(nextState);
  }

  return state;
}

`
