### ISSUE TITLE
Navigatiton to screen of navigator with empty history from another navigator also adds initialRoute

### ISSUE THREAD

**Issue by punksta** [react-navigation/react-navigation#2554]
### Current Behavior
Let's say we have routes of the following structure without redux and wrapper components:
```
root: StackNavigator {
     a: StackNavigator({
           a1: Screen
      }),
     b: StackNavigator({
           b1: Screen
           b2: Screen
     })
}
```
initially we are on `a` and we want to navigate to`b2`

```
this.props.navigation.dispatch(
            NavigationActions.navigate({
                            routeName: 'b2'
                        }),
        );
```
After this action both `b1` and `b2` will be in state. 
```
index: 1
routes: [
   a: {...}
   b: {
   index: 1
   routes: [
      b1: {...},
      b2: {...}
    }
}
``` 

### Expected Behavior
After navigation from `a1` to `b2` route `b1` is not being added to state

### Possible reason of problem
https://github.com/react-community/react-navigation/blob/5e075e1c31d5e6192f2532a815b1737fa27ed65b/src/routers/StackRouter.js#L190-L222

It gets state for `NavigationActions.init()` then gets state for required action with `initChildRoute` as current state. It should not include route from `init` action in result. We need only state for required action without initial route.

###
edit: improve English.

**Comment by punksta** [comment]
Possible very dirty solution. Override `getStateForAction` of `B` navigator router.

```
// @flow
import React from 'react';

import {
    CardStackTransitioner,  NavigationRouteConfigMap, StackNavigatorConfig
} from "react-navigation"
import type {NavigationStackAction, NavigationState} from "react-navigation/src/TypeDefinition";
import { NavigationActions } from "react-navigation";
import NavigatorTypes from "react-navigation/src/navigators/NavigatorTypes";


const NoInitialStackRouter = (original) => {

    const getStateForAction = (
        passedAction: NavigationStackAction,
        state: ?NavigationState
    ) => {
        const action = NavigationActions.mapDeprecatedActionAndWarn(passedAction);
        if (!state && action.type === NavigationActions.INIT) {
            return {
                routes: [],
                index: -1
            }
        } else {
            if (state && state.routes.length === 0 && state.index === -1) {
                return original.getStateForAction(passedAction, null);
            }
        }

        return original.getStateForAction(passedAction, state);
    };

    return {
        ...original,
        getStateForAction
    }
};


export const NoInitialStateStackNavigator = (
    routeConfigMap: NavigationRouteConfigMap,
    stackConfig: StackNavigatorConfig = {}
) => {
    const original = StackNavigator(routeConfigMap, stackConfig);

    original.router = NoInitialStackRouter(original.router);
    return original;
};

```

**Comment by zsaraf** [comment]
@punksta having the exact same issue!

**Comment by brentvatne** [comment]
please re-post to https://react-navigation.canny.io/feature-requests if this is important for you. re-organizing issues to focus on bug reports here and feature requests on canny. thanks!

**Comment by Elijen** [comment]
@brentvatne This seems like a bug not a feature request.

**Comment by brentvatne** [comment]
@Elijen - explain?

**Comment by Elijen** [comment]
@brentvatne It seems that the initial route of a navigator is always pushed into the navigation history even though a different route was requested by navigation.navigate. This for example breaks `goBack()`. In @punksta's example `b1` is not expected to be in the history.

Wouldn't the solution with `initialRouteKey` work only if you are navigating to the initial route?

**Comment by Elijen** [comment]
@brentvatne  Seems to be confusing a lot of people and if back button does go to a screen where the user never navigated it must be a bug. 

More issues:
- https://github.com/react-navigation/react-navigation/issues/2549
- https://github.com/react-navigation/react-navigation/issues/1695

BTW for me the `navigation.dispatch(NavigationActions.back())` works the same as `goBack(null)` or `goBack()`.

**Comment by adonandal** [comment]
Any fix for this?

**Comment by sgtpepper43** [comment]
Why is this closed? This bug is still an issue. Navigating to a screen that isn't the initialRoute of a stack shouldn't then add the initialRoute to the stack. It makes no sense.

**Comment by satya164** [comment]
@sgtpepper43 no need to be disrespectful

**Comment by punksta** [comment]
I am still using `NoInitialStateStackNavigator` in production as workaround

**Comment by punksta** [comment]
the problem was this:
when parent navigator `b` isn't in state, it's being added there with "INIT()" action followed by "NAVIGATE" action dispatching. The structure of react-navigation files has been changed so I am not sure where is current router is located.

**Comment by satya164** [comment]
Closing since this is no longer the behaviour in v5.

**Comment by MishaChernov** [comment]
> the problem was this:
> when parent navigator `b` isn't in state, it's being added there with "INIT()" action followed by "NAVIGATE" action dispatching. The structure of react-navigation files has been changed so I am not sure where is current router located.

Hello. I have the same issue in navigation 4, and I can't find how to fix it. Do you still remember this issue? Is your fix `NoInitialStateStackNavigator` still working? I can't find this method, could you tell more about it `NavigationActions.mapDeprecatedActionAndWar` please?
