### ISSUE TITLE
How to use a custom component to the tab bar navigator?

### ISSUE THREAD

**Issue by THPubs** [react-navigation/react-navigation#2601]
Hi, I need to use the Tab navigator but need to customize its tab bar. Here's what I'm trying to achieve:

![screen shot 2017-09-16 at 6 09 48 pm](https://user-images.githubusercontent.com/1212023/30512323-8b68168a-9b0a-11e7-8779-7f094b1a2150.png)

The middle button is not a screen in the tab bar. It's a custom button which opens a floating menu. Now I have already created this component but unable to attach it to my tab bar. All I want to do is to navigate to screens through this tab bar.

The app's code looks like this:

    <View style={{ flex: 1, backgroundColor: '#f3f3f3' }}>
      <MainTabNavigator /> // The tabbar created from react-navigation
      <TXTabBar navigation={tabNavigation} /> // My custom tabbar
    </View>

I tried to use the `NavigationActions` navigate function. It didn't work. I tried to pass the `navigation` props from a tab screen to my redux store, pass it back to my custom tab bar and used it's navigating function. The function gets passed but nothing happens. Yes, the last thing I did is a bit stupid. Can anyone please help me fix this?

**Comment by justinlok** [comment]
Use the tabBarComponent for tabnavigator.
https://reactnavigation.org/docs/navigators/tab

This should work
```
  tabBarComponent: ({navigation}) => <TXTabBar navigation={navigation} />,
```

**Comment by vanhoutk** [comment]
Assuming you create your navigator like this, you can specifiy the tabBarComponent when you're creating the TabNavigator:

```
export const MainTabNavigator = TabNavigator({
  Home: { screen: HomeScreen },
  Activity: { screen: ActivityScreen },
  Contacts: {screen: ContactsScreen },
  More: { screen: MoreScreen }
}, {
  tabBarComponent: TXTabBar,
  tabBarPosition: 'bottom',
});
```

**Comment by shukla12manish** [comment]
I also got stuck in same kind of problem. I have created different components for different screen of tab navigation but getting error while connecting the tab with component. I have same code as Vanhoutk and each screen is defined separately as component. error is 'undefined is not an object(evaluating 'this.props.navigation.navigate'). Kindly suggest what can be done.

**Comment by 424626154** [comment]
@THPubs 
Okay?Open a new page,What's the click event that the middle button starts up?
实现了么？打开一个新页面，中间按钮的点击事件是什么样的？

**Comment by kelset** [comment]
Pinging OP @THPubs since this issue has not been active for a while, and it's related to an old version of the lib.

Moreover the solutions by @jslok & @vanhoutk seems reasonable to me.

Please let me know if you want this to remain open (does it still happen in the latest version?); if I get no answer in the next 7 days I will close it.

**Comment by kelset** [comment]
Hi there @THPubs,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.

**Comment by reza7rm** [comment]
I still couldn't solve the issue my tab navigator in in a stack navigator, the router is as follows:
`

export const SignedInStack = StackNavigator({
  Test:{
    screen:SignUp,
    navigationOptions: {
      title: "Sign Up",
      headerStyle
    }
  }
})

export const SignedOut = StackNavigator({
  SignUp: {
    screen: SignUp,
    navigationOptions: {
      title: "Sign Up",
      headerStyle
    }
  },
   //SignInWebview
  SignIn: {
    screen: SignIn,
    navigationOptions: {
      title: "Sign In",
      headerStyle
    }
  }
},{initialRouteName:"SignIn"}
);

export const SignedIn = TabNavigator(
  {
    Home: {
      screen: Home,
      navigationOptions: {
        title:'Home',
        tabBarIcon: ({ focused }) => (
          focused ?
          <Icon name="home" type="simple-line-icon" size={24} iconStyle={{paddingBottom:0,paddingTop:0}} color="#007700" />:
          <Icon name="home" type="simple-line-icon" size={24} iconStyle={{paddingBottom:0,paddingTop:0}} color="#000" />
        ),

      }
    },
    Search: {
      screen: Search,
      navigationOptions: {
        title:'Search',
        tabBarIcon: ({ focused }) => (
          focused ?
          <Icon name="magnifier" type="simple-line-icon" size={24} iconStyle={{paddingBottom:0,paddingTop:0}} color="#007700" />:
          <Icon name="magnifier" type="simple-line-icon" size={24} iconStyle={{paddingBottom:0,paddingTop:0}} color="#000" />

        ),

      }
    },

    Notifications: {
      screen: Notifications,
      navigationOptions: {
        title:'Notifications',
        tabBarIcon: ({ focused }) => (
          focused ?
          <Icon name="bell" type="simple-line-icon" size={24} iconStyle={{paddingBottom:0,paddingTop:0}} color="#007700" />:
          <Icon name="bell" type="simple-line-icon" size={24} iconStyle={{paddingBottom:0,paddingTop:0}} color="#000" />

        ),

      }
    },
    Profile: {
      screen: Profile,
      navigationOptions: {
        title:'Profile',
        tabBarIcon: ({ focused }) => (
          focused ?
          <Icon name="user" type="simple-line-icon" size={24} iconStyle={{paddingBottom:0,paddingTop:0}} color="#007700" />:
          <Icon name="user" type="simple-line-icon" size={24} iconStyle={{paddingBottom:0,paddingTop:0}} color="#000" />

        ),

      }
    },

  },
  {
    initialRouteName:"Home",
    tabBarComponent: TabBarBottom,
    lazy:true,
    tabBarPosition:'bottom',
    tabBarOptions: {
      iconStyle: {
        paddingTop:0,
        paddingBottom:50,
      },
      showIcon:true,
      showLabel:false,
      activeTintColor:"#000000",
      inactiveTintColor:"#ffffff"
    }
  }
);

export const RootNavigator = (signedIn = true) => {
  return StackNavigator(
    {
      SignedIn: {
        screen: SignedIn,
        navigationOptions: {
          gesturesEnabled: false
        }
      },
      SignedOut: {
        screen: SignedOut,
        navigationOptions: {
          gesturesEnabled: false
        }
      },
      Comments:{
        screen: Comments,
        navigationOptions: {
          title:'Comments',
        }
      },
      ImageUpload:{
        screen: ImageUpload,
        navigationOptions: {
          title:'ImageUpload',
        }
      },
      SingleProfile:{
        screen: SingleProfile,
        navigationOptions: {
          title:'SingleProfile',
        }
      },
    },
    {
      headerMode: "none",
      mode: "modal",
      initialRouteName: (signedIn ? "SignedIn" : "SignedOut")
    },
  );
};
`

How can I add a button to this tabbar as the one asked in the first question by @THPubs

**Comment by fuyue111** [comment]
@reza7rm Have you got the solution?

**Comment by amirmatin** [comment]
@THPubs  Did you find a solution for this ?

**Comment by Im-Goutham** [comment]
@reza7rm have you got the solution ? If yes please share.

**Comment by vivek12345** [comment]
See if this helps you all in any way
https://snack.expo.io/HyVAreX1X

**Comment by pkhien95** [comment]
This is my solution: 
```
const CustomTabNavigator = createBottomTabNavigator({
	FirstTab: {
		screen: FirstScreen,
	},
	AddButton: {
		screen: () => null,
		navigationOptions: () => ({
			tabBarIcon: (<AddButton/>),
			tabBarOnPress: () => {}
		})
	},
	SecondTab: {
		screen: SecondScreen,
	}
}
```
Hope this helps you 😄

**Comment by reza7rm** [comment]
Hi This is my final solution which I am not sure it works with new version on react-navigation:
```
export const SignedIn = TabNavigator(
  {
    Home: {
      screen: Home,
      navigationOptions: {
        title:'Home',
        tabBarIcon: ({ focused }) => (
          focused ?
          <MyIcon name="home" size={30} iconStyle={{paddingBottom:0,paddingTop:0}} color="#000" />: //color="#007700"
          <MyIcon name="home-line"  size={30} iconStyle={{paddingBottom:0,paddingTop:0}} color="#000" />
        ),

      }
    },
    Search: {
      screen: Search,
      navigationOptions: {
        title:'Search',
        tabBarIcon: ({ focused }) => (
          focused ?
          <MyIcon name="search"  size={30} iconStyle={{paddingBottom:0,paddingTop:0}} color="#000" />:
          <MyIcon name="search-line"  size={30} iconStyle={{paddingBottom:0,paddingTop:0}} color="#000" />

        ),

      }
    },
    
    Photo: {
      screen: Photo,
      navigationOptions: {
        title:'Camera',
        tabBarIcon: ({ focused }) => (
          focused ?
          <Icon name="add-circle"  type="Ionicons"  size={30} iconStyle={{paddingBottom:0,paddingTop:0}} color="#000" />:
          <Icon name="add-circle-outline" type="Ionicons"  size={30} iconStyle={{paddingBottom:0,paddingTop:0}} color="#000" />

        ),

      }
    },

    Notifications: {
      screen: Notifications,
      navigationOptions: {
        title:'Notifications',
        tabBarIcon: ({ focused }) => (
          focused ?
          <MyIcon name="heart"  size={30} iconStyle={{paddingBottom:0,paddingTop:0}} color="#000" />:
          <MyIcon name="heart-line"  size={30} iconStyle={{paddingBottom:0,paddingTop:0}} color="#000" />

        ),

      }
    },
    Profile: {
      screen: Profile,
      navigationOptions: {
        title:'Profile',
        tabBarIcon: ({ focused }) => (
          focused ?
          <MyIcon name="user" size={30} iconStyle={{paddingBottom:0,paddingTop:0}} color="#000" />:
          <MyIcon name="user-line" size={30} iconStyle={{paddingBottom:0,paddingTop:0}} color="#000" />

        ),

      }
    },

  },
  {
    initialRouteName:"Home",
    tabBarComponent: TabBarBottom,
    lazyLoad:true,
    lazy:true,
    tabBarPosition:'bottom',
    swipeEnabled:false,
    animationEnabled:false,
    tabBarOptions: {
      iconStyle: {
        paddingTop:0,
        paddingBottom:50,
      },
      showIcon:true,
      showLabel:false,
      activeTintColor:"#000000",
      inactiveTintColor:"#ffffff",
    },
    navigationOptions: ({navigation})=>({
      tabBarOnPress:(tab,jumpToIndex) =>{
        const {
          dispatch,
          state,
      } = navigation;
      //alert(JSON.stringify(tab));
      if (tab.index == 2){
        dispatch(NavigationActions.reset({
          index: 0,
          key: state.key,
          actions: [NavigationActions.navigate({ routeName: "CameraPage" })],
      }))
      }else {
        jumpToIndex(tab.index)
    }
      }
    })
  }
);
```

**Comment by zjb19970804** [comment]
> 这是我的解决方案：
> 
> ```
> const CustomTabNavigator = createBottomTabNavigator({
> 	FirstTab: {
> 		screen: FirstScreen,
> 	},
> 	AddButton: {
> 		screen: () => null,
> 		navigationOptions: () => ({
> 			tabBarIcon: (<AddButton/>),
> 			tabBarOnPress: () => {}
> 		})
> 	},
> 	SecondTab: {
> 		screen: SecondScreen,
> 	}
> }
> ```
> 希望这对你有所帮助 😄
@pkhien95 
This is valid, but how to remove the text under this icon? The default text is the name of the icon component. Other normal label bars display text. Button icons are not needed. I don't know where to turn it off using showLabe.
![screenshot_2018-11-22-10-54-41-344_com zuiyou](https://user-images.githubusercontent.com/37135411/48879067-35595080-ee45-11e8-8989-7ac693872d74.png)

**Comment by aniruddhashevle** [comment]
@pkhien95 : This suggestion is good,

```
const CustomTabNavigator = createBottomTabNavigator({
	FirstTab: {
		screen: FirstScreen,
	},
	AddButton: {
		screen: () => null,
		navigationOptions: () => ({
			tabBarIcon: (<AddButton/>),
			tabBarOnPress: () => {}
		})
	},
	SecondTab: {
		screen: SecondScreen,
	}
}

```
However, the value of focused that I'm getting in the tabBarIcon is not proper, shown below.
```
AddButton: {
		screen: () => null,
		navigationOptions: () => ({
			tabBarIcon: ({ focused }) => (<AddButton focused={focused} />),
			tabBarOnPress: () => {}
		})
	},
```
If we **click on AddButton tab**, the **value of focused** mentioned above in tabBarIcon is **false**.

**Comment by hassamali898** [comment]
how can i navigate another screen when i am using tabBarIcon:()=><AddButton/> ??
how can i access navigation options in AddButton to navigate another screen

**Comment by hassamali898** [comment]
the navigation is not working in components when i this code
`AddDocbtn: {
		screen: () => null,
		navigationOptions: () => ({
			tabBarIcon: ({ focused }) => (<AddButton focused={focused} />),
			tabBarOnPress: () => {}
		})
	}`
`export default AddDocBtn =({navigation})=>{
    return <View style={{position:"absolute",alignItems:'center'}}>
        <View style={styles.btnstyle}>
        <TouchableOpacity onPress={()=>navigation.navigate("Docs")}>
            <AntDesign name ="plus" size={24} color = "#fff"/>
        </TouchableOpacity>
        </View>
        
    </View>
}`

**Comment by williamsiuhang** [comment]
Updated answer for react router v6:

Use `tabBarButton` in the options prop

`
import { NavigationContainer } from '@react-navigation/native';
import { createBottomTabNavigator } from '@react-navigation/bottom-tabs';

const Tab = createBottomTabNavigator();

    <NavigationContainer>
      <Tab.Navigator>
        // normal button
        <Tab.Screen name="home" component={Home} options={{ tabBarLabel: "Home" }} />
        // custom floating action button
        <Tab.Screen
          name="screennamehere"
          component={FABComponentScreen}
          options={{
            tabBarLabel: "Home",
            tabBarButton: () => <CustomButton />
          }}
        />
      </Tab.Navigator>
    </NavigationContainer>
`
