### ISSUE TITLE
setParams inside nested navigator, replace initialRouteName 

### ISSUE THREAD

**Issue by llaine** [react-navigation/react-navigation#2609]
### Current Behavior
Whenever I got multiple nested navigator, intialeRouteName starts to be overridden.

Let's imagine the following stack 

```typescript

class TabOne extends Component {
  render() {
    return <Text>TabOne</Text>
  }
}

class TabTwo extends Component {
  static navigationOptions = ({ navigation }) => ({
    headerTitle: (<Text>{navigation.state.params ? navigation.state.params.title : ''}</Text>)
  })
  
  componentDidMount() {
    this.props.navigation.setParams({
      title: 'passing params',
    });
  }
  
  render() {
    return <Text>TabTwo</Text>
  }
}

const HomeNavigator = StackNavigator({
  tabOne: {
    screen: TabTwo,
  }
}, { intialRouteName: 'tabOne' })

const MainTabNavigation = TabNavigator({
  tabOne: {
    screen: TabOne
  },
  tabTwo: {
    screen: HomeNavigator
  },
}, { intialRouteName: 'tabOne' });

export default StackNavigator({
  mainScreen: {
    screen: MainTabNavigation
  }
}, { intialRouteName: 'mainScreen' });
```

```

StackNavigator
 |
 +--> MainScreen : 
           |
           + ---> TavNavigator
                        |
                        + --> TabOne : Component // This is the initialRouteName
                        + --> TabTwo 
                                   |
                                   +---> StackNavigator
                                              | 
                                              +---> Component // This is the route rendered instead

```

TabTwo is render instead of TabOne.

### Expected Behavior

It should just render the correct initialRouteName

You can easily reproduce the issue using this snack : https://snack.expo.io/HJmosSpcW

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.12
| react-native     | 0.47.1
| node             | v8.2.1
| npm or yarn      | 5.3.0

**Comment by ahanriat** [comment]
👍 On this issue, may be related to #1711 #2583

**Comment by fstojanac** [comment]
I've been experiencing the same issue. Workarounds suggested in #1711 and #2583 are haven't fixed it for me.

**Comment by kelset** [comment]
Pinging OP @llaine since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open (does it still happen in the latest version?); if I get no answer in the next 7 days I will close it.

**Comment by kelset** [comment]
Hi there @llaine,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.
