### ISSUE TITLE
TabNavigator doesn't reload view change on tab.

### ISSUE THREAD

**Issue by kiritnim** [react-navigation/react-navigation#2618]
Hi,

I will use the tabNavigator for tabbar.I want to reload the selected tab when user select tab. In my code here when user change tab, but no one lifecycle of react native called. Please see my below code .

**Link :** https://snack.expo.io/H10d2YCc-

**Comment by jedrichards** [comment]
I used this solution to trigger some code when we navigate back to a tab:

https://github.com/react-community/react-navigation/issues/962#issuecomment-323873066

**Comment by sanjayholla94** [comment]
https://github.com/react-community/react-navigation/pull/1335. It lets you detect when a tabBar is pressed.

**Comment by sanjayholla94** [comment]
If you want to reload when the tab is in focus, you can look at https://github.com/react-community/react-navigation/issues/51#issuecomment-302366381

**Comment by pencilcheck** [comment]
The last comment is for StackNavigator, I wonder if that works for TabNavigator? Also, shouldn't this be part of react navigation? 

Currently I'm on 1.0.0-beta.9 but switching tab doesn't call reactJS lifecycle function such as componentWillReceiveProps.

**Comment by kelset** [comment]
Pinging OP @kiritnim since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open (does it still happen in the latest version?); if I get no answer in the next 7 days I will close it.

**Comment by ayyouboulidi** [comment]
+1
I am facing the same problem, I have my data loaded, once I switch the tab and I go back to my previous tab the data are not loaded and the component is not re-rendered :(

**Comment by kelset** [comment]
Hi there @kiritnim,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.

**Comment by dhani112** [comment]
Solution i found to trigger the on click 
const MyTabs = TabNavigator({
  ...
}, {
  tabBarComponent: TabBarBottom /* or TabBarTop */,
  tabBarPosition: 'bottom' /* or 'top' */,
  navigationOptions: ({ navigation }) => ({
    tabBarOnPress: (scene, jumpToIndex) => {
      console.log('onPress:', scene.route);
      jumpToIndex(scene.index);
    },
  }),
});

**Comment by paulopacitti** [comment]
@dhani112 this method is depecrated, does it have another solution?

**Comment by brentvatne** [comment]
use https://reactnavigation.org/docs/en/with-navigation-focus.html

**Comment by headwinds** [comment]
looks like that page got moved to https://reactnavigation.org/docs/function-after-focusing-screen/

**Comment by yadavanuj1996** [comment]
The link provided by @headwinds contains latest working solution.

**Comment by ubaidmoin** [comment]
You can reload screen by unmounting screens in bottom tab by adding option in navigation screenOptions:

`unmountOnBlur: true`

You can do it in Tab & Drawer Navigations but not in Stack Navigation.
And you can also add unmount to individual screen by adding same option (unmountOnBlur).

**Comment by AlaeddineMessadi** [comment]
addListener to 'didFocus' instead of 'focus'

Functional Component: 

```javascript
const StatsScreen = ({ navigation }) => {
  React.useEffect(() => {
    const unsubscribe = navigation.addListener('didFocus', () => {
      // The screen is focused
      console.log('focused')
    });
    });

    // Return the function to unsubscribe from the event so it gets removed on unmount
    return unsubscribe.remove();
  }, [navigation]);
...
```


Class Component: 

```javascript
import React, { Component } from 'react';
import { View } from 'react-native';
import { withNavigation } from 'react-navigation';

class TabScreen extends Component {
  componentDidMount() {
    const { navigation } = this.props;
    this.focusListener = navigation.addListener('didFocus', () => {
      // The screen is focused
      // Call any action
    });
  }

  componentWillUnmount() {
    // Remove the event listener
    this.focusListener.remove();
  }

  render() {
    return <View />;
  }
}

export default withNavigation(TabScreen);
```

**Comment by nedyalkov** [comment]
Hey, @AlaeddineMessadi there is a mistake in the code - the `useEffect` callback should return a cleanup function and not directly cleanup the handler when returning. Also, I believe the correct event name is `focus` and not `didFocus` (at least for the `TabNavigator`).

Here is how I modified your code and it works great:
```
  useEffect(() => {
    const unsubscribe = navigation.addListener('focus', () => {
      // The screen is focused
      console.log('focused');
    });

    // Return the function to unsubscribe from the event so it gets removed on unmount
    return () => unsubscribe.remove();
  }, [navigation]);
```
