### ISSUE TITLE
Tab Menu Item Changing instead of being Fixed.

### ISSUE THREAD

**Issue by rainbowhat** [react-navigation/react-navigation#2624]
Hi, when i navigate to another page, the tabs at the bottom changes which shouldn't happen. It should only change the screen not the tab, the tab menu below should remain the same regardless of which page i'm at, what settings did i do wrong?

const MainNavigator = TabNavigator({
      welcome: { screen: WelcomeScreen },
      auth: { screen: AuthScreen },
      login: { screen: LoginScreen },
      main: { 
        screen: TabNavigator({
          map: { screen: MapScreen },
          deck: {
            screen: StackNavigator({
              deck: {screen:DeckScreen},
              viewJobsScreen: {screen: viewJobsScreen} // This shouldnt replace the tab menu 
            })
          },
          review: {
            screen: StackNavigator({
              review: {screen:ReviewScreen},
              settings: {screen: SettingsScreen}
            })
          }
          
        },{
          tabBarPotion: 'bottom',
          // swipeEnabled: false,
          tabBarOptions: {
            labelStyle: { fontSize: 12 }
          }
        })
      }
    },{
      navigationOptions:{
        tabBarVisible: false
      },
      lazy : true
    });

**Comment by spencercarli** [comment]
What do you mean by "tabs at the bottom changes"?

**Comment by rainbowhat** [comment]
@spencercarli 
![screen shot 2017-09-21 at 7 53 15 am](https://user-images.githubusercontent.com/3077812/30672898-f5ae2198-9ea1-11e7-82f7-ce6cb2e97599.jpg)

**Comment by kelset** [comment]
Pinging OP @rainbowhat since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open (does it still happen in the latest version?); if I get no answer in the next 7 days I will close it.

**Comment by kelset** [comment]
Hi there @rainbowhat,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.
