### ISSUE TITLE
ReRender loop caused by using screenProps on a DrawerNavigator component

### ISSUE THREAD

**Issue by jayesbe** [react-navigation/react-navigation#2625]
### Current Behavior
Using a DrawerNavigator component and specifying a screenProps property on the component, results in the render method of the active scene being constantly called **AFTER** triggering a setParams on the navigation property.

### Expected Behavior
setParams on the navigation property should trigger a rerender only if the navigation props have changed and only once.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | master
| react-native     | 0.48.3
| node             | 6.9
| npm or yarn      | yarn

### Example

app.js
```

    render() {
      const MainDrawerNavigator = this.mainNavigator;
      return(<MainDrawerNavigator 
        ref="navigation"
        screenProps={{
          myFunc: () => null
        }}        
      />);
    }

```

scene.js

```
const NavigatorHeader = ({ navigation, screenProps }) => {
  if (!navigation.state.hasOwnProperty('params')) {
    navigation.state['params'] = {
        isOpen: false
    };
  }

  const right (
      <View style={{ flexDirection: 'row', flex: 1 }}>
        <Icon.Button
          style={{ flex: 1 }}
          name={'search'}
          size={22} 
          color={Theme.Colours.white} 
          backgroundColor={'transparent'} 
          iconStyle={{marginLeft: 10}}
          borderRadius={0}
          onPress={() => {
            navigation.setParams({isOpen: !navigation.state.params.isOpen});
          }}
        />  
      </View>
    );
  }
  
  return {
    ...DefaultNavigationOptions({ navigation }),
    headerRight: right,
  }
};
```

Pressing the button in the header negates the isOpen param in navigation state. 

The moment the button is pressed, render loops on the scene component.

If I remove screenProps on MainDrawerNavigator, there is no render loop. 

Note the myFunc in screenProps is not even being used.  In fact, it doesnt even need to be there. An empty screenProps (ie screenProps={{}} ) causes the same behaviour.

**Comment by dstollie** [comment]
We're dealing with the exact same issue

**Comment by HannanShaik** [comment]
Facing the same issue. Any update on this?

**Comment by brentvatne** [comment]
I recommend not using screenProps. We are discussing removing it. Instead you can use other mechanisms like Redux or react-broadcast to pass data through.

**Comment by izbari** [comment]
im facing the same issue
