### ISSUE TITLE
Update Docs

### ISSUE THREAD

**Issue by ShMcK** [react-navigation/react-navigation#2634]
Update docs referring to 'DrawerOpen', 'DrawerClose', 'DrawerToggle' to use `{ routeName: 'DrawerOpen' }`.

**Comment by matthamil** [comment]
Hi! We'll gladly accept any PR to correct the documentation.

**Comment by kelset** [comment]
@ShMcK you mean here? https://reactnavigation.org/docs/navigators/drawer#DrawerNavigator

**Comment by brentvatne** [comment]
👋
