### ISSUE TITLE
Cannot Deep Link using only a DrawerNavigator

### ISSUE THREAD

**Issue by joshbroton** [react-navigation/react-navigation#2647]
### Current Behavior
My app has a DrawerNavigator at the root of the app. I've successfully registered a URL Type in Xcode. When I ` xcrun simctl openurl booted "myapp://resetpassword/39392834`, it opens the app, but navigates to the `initialRouteName` rather than the screen with the correct path.

When I simply switch DrawerNavigator to StackNavigator it works without issues. 

I should add that the actual code is much more complicated than this example and doesn't lend itself to simply switching to a DrawerNavigator nested in a StackNavigator because there are many more routes that need to be deep linked.

### What I expected
I expect that DrawerNavigator would honor paths just like StackNavigator does, since path is included in the DrawerNavigator documentation.

### A simple version of my code
```
const prefix = Platform.OS == 'android' ? 'myapp://myapp/' : 'myapp://';

const AppDrawerNav = DrawerNavigator(
    {
        Auth: {
            screen: Auth
        },
        ResetPassword: {
            screen: ResetPassword,
            path: 'resetpassword/:token'
        }
    }, {
        initialRouteName: 'Auth'
    }
);

export default class App extends React.Component {
    render() {
        return <AppDrawerNav uriPrefix={prefix} />;
    }
}
```

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.11
| react-native     | 0.48.4

**Comment by PatNeedham** [comment]
@joshbroton what happens if you change
```
export default class App extends React.Component {
    render() {
        return <AppDrawerNav uriPrefix={prefix} />;
    }
}
```
to
```
const App = () => <AppDrawerNav uriPrefix={prefix} />;
export default App
```

I used that with `DrawerNavigator` and got it to work as expected for your example, but with react-navigation version 1.0.0-beta.13 and react-native 0.49.1.

**Comment by kelset** [comment]
Pinging OP @joshbroton since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open (does it still happen in the latest version?); if I get no answer in the next 7 days I will close it.

**Comment by kelset** [comment]
Hi there @joshbroton,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.
