### ISSUE TITLE
React navigation not working from within the  Actions . 

### ISSUE THREAD

**Issue by jpca999** [react-navigation/react-navigation#2650]
Heres the gist of the Actions code: It doesnt trigger the route.  allFruits

Do i somehow have to provide the list of screens in the Actions file ?

import { NavigationActions } from 'react-navigation'

export const Create = ({address, cell, phone, comments, shift, _id  }) => {

    return async ( dispatch, NavigationActions ) => {
      console.log(' 44-  NavigationActions = ', NavigationActions);
      console.log(' 45-  NavigationActions.getState = ', NavigationActions.getState);
        try {
            const token = await AsyncStorage.getItem('token');
            if (token !== null) {
                axios.defaults.headers.common['authorization'] = token;
                axios.post(ROOT_URL, {
                        address: address,
                        cell: cell,
                        phone: phone,
                        comments: comments,
                        // shift : shift
                    })
                    .then(response => {
                        console.log('43 -  response of FRUIT create   response.data = ', response.data);
                        dispatch({
                            type: FRUIT_CREATE,
                            payload: response.data
                        });

                })
                .then(response => {
                    dispatch(NavigationActions.navigate({ routeName: 'allFruits' }));                    
            });
            }
        } catch (error) {
            console.log(error);
        }
    }; // end return (dispatch)
};

![image](https://user-images.githubusercontent.com/1026325/30888621-7d4e6a3a-a2ef-11e7-8223-24eefdb92ecd.png)

**Comment by spencercarli** [comment]
Is `NavigationActions` being overridden? You're importing it but also using `NavigationActions` as an argument name.

**Comment by jpca999** [comment]
@spencercarli   Thank you spencer, Here is the updated code, Now it doesn't throw the error but it doesn't navigate either. 


[
import { NavigationActions } from 'react-navigation'

export const Create = ({address, cell, phone, comments, shift, _id }) => {

return async ( dispatch ) => {
  console.log(' 44-  NavigationActions = ', NavigationActions);
  console.log(' 45-  NavigationActions.getState = ', NavigationActions.getState);
    try {
        const token = await AsyncStorage.getItem('token');
        if (token !== null) {
            axios.defaults.headers.common['authorization'] = token;
            axios.post(ROOT_URL, {
                    address: address,
                    cell: cell,
                    phone: phone,
                    comments: comments,
                    // shift : shift
                })
            .then(response => {
                dispatch(NavigationActions.navigate({ routeName: 'allFruits' }));                    
        });
        }
    } catch (error) {
        console.log(error);
    }
}; // end return (dispatch)
};
](url)

**Comment by spencercarli** [comment]
Just to make sure, based on your code, I'm assuming that you're using redux to manage your navigation state?

**Comment by jpca999** [comment]
@spencercarli   Yes

**Comment by kelset** [comment]
Pinging OP @jpca999 since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open (does it still happen in the latest version?); if I get no answer in the next 7 days I will close it.

**Comment by kelset** [comment]
Hi there @jpca999,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.
