### ISSUE TITLE
Drawer Navigation not showing within a Stack Nav within a Tab Nav on Android

### ISSUE THREAD

**Issue by nextriot** [react-navigation/react-navigation#2652]
Hi,

My structure is as follows:

Tab Nav > Stack Nav > Drawer Nav. When I open the Drawer Nav, it renders as expected on iOS but I just get the dark back drop on Android, as the below:

(I couldn't upload the image directly for some reason, so depressingly - here's an imgur link):
https://i.imgur.com/oKSXJly.png

Is there some sort of styling I need to apply to get the menu to work on the android side?

I am using a `contentComponent`, however the issue is present when using the de-facto configuration also.

Any help is much appreciated. Thanks.

**UPDATE**
If I drag from the side of the screen on Android I can pull the drawer out, once I've initially pressed the menu button and have the backdrop present. It seems whatever function triggers the visibility of the menu itself isn't being called properly when embedded in a tab bar controller.

**Comment by spencercarli** [comment]
Can you put together a demo of this issue?

**Comment by nextriot** [comment]
@spencercarli thanks for checking this out. Here's the a demo of the app in question: https://expo.io/@nextriot/bai-app

**Comment by alanselo** [comment]
I have the exact same problem. Did you find any solution @nextriot ?

Thanks,

**Comment by mkayswork** [comment]
Also having the same problem here

**Comment by kelset** [comment]
Pinging OP @nextriot since this issue has not been active for a while, and it's related to an old version of the lib.

Please let me know if you want this to remain open (does it still happen in the latest version?); if I get no answer in the next 7 days I will close it.

**Comment by kelset** [comment]
Hi there @nextriot,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.
