### ISSUE TITLE
TabRouter remounts components on every screen change

### ISSUE THREAD

**Issue by IAmMarcellus** [react-navigation/react-navigation#2687]
**Summary:**
I have an app with two screens, a home screen (a map) and a list, that I navigate between using custom navigator built with TabRouter.  The code for the navigator is at the bottom.  My problem is with how the navigator mounts pages/saves state when the screen changes. Specifically:

**Expected behavior:**
When I switch from home screen to the list screen and then back to the home screen, the home screen will be just as it was before it was visited, i.e. the same state.  This means that the map will be in the same location as the user was when he/she left the screen.

**Actual behavior:**
Switching back to the home screen remounts the component and the state resets.  It has to find the user's location again instead of already having it in the state.  

**The Navigator:**

```
const CustomTabView = ({ router, navigation }) => {
const { routes, index } = navigation.state;
  const ActiveScreen = router.getComponentForState(navigation.state);
  return(
        <View style={styles.fullscreen}>
          <View style={styles.belowHeader}>
            <ActiveScreen
              navigation={addNavigationHelpers({
                ...navigation,
                state: routes[index],
              })}
            />
          </View>
          <Header navigation={navigation} style={styles.fullscreen} />
        </View>
  )
}

const CustomTabRouter = TabRouter(
  {
    Home:{
      screen: HomeView,
      path: '',
    },
    List:{
      screen: Settings,
      path: '/List'
    }
  },
  {
    initialRouteName: 'Home'
  }
);

const NavView = createNavigationContainer(
  createNavigator(CustomTabRouter)(CustomTabView)
);

export default NavView;
```

**Comment by 0kai** [comment]
is there any config to fix this

**Comment by brentvatne** [comment]
> that I navigate between using custom navigator built with TabRouter

this is totally up to you. you can look at the code for TabNavigator and react-native-tab-view to see how react-navigation deals with it. the router says nothing about what you do in the view component

**Comment by MichelDiz** [comment]
I have this issue too. I have copied part of a code from Spencer. About Auth Flow. All works nice before my custom SignedIn stack made with:

```Typescript
const CustomTabs = createNavigationContainer(
  createNavigator(CustomTabRouter)(CustomTabView as any),
);
```

```Typescript
export const createRootNavigator = (signedIn = false) => {
  console.log(signedIn, "signedIn ?");
  return SwitchNavigator(
	{
		SignedIn: {
		screen: CustomTabs, // ! This section re-render all screens between tabs and sub stacks(I did a test)
		},
		SignedOut: {
		screen: SignedOut, // ! This section works great, as expected.
		},
	},
	{
		initialRouteName: signedIn ? "SignedIn" : "SignedOut",
	},
  );
};

```

I just wanted to create a custom Tab. And it's very good, I was able to create as I wanted from design. I came across this problem only now using createNavigationContainer for CustomTabs.
