### ISSUE TITLE
why should i navigate with setTimeout?

### ISSUE THREAD

**Issue by derakhshanfar** [react-navigation/react-navigation#2688]
i have to check some condition in componentDidUpdate lifecycle and if my condition is true, i navigated my screen to _Home_ screen like this command:

```
componentDidUpdate() {
        if (this.props.accessToken && !this.state.appLoading) {          
            if (firstTime) {                
                firstTime = false;
                setTimeout(() => {
                    this
                    .props
                    .navigation
                    .navigate('Home');
                }, 500);
            }            
        }
    }
```
i have InputText in my Home Page and after navigate to Home page, if i don't use the setTimeout in above code , when i tap on my InputText for first time, the inputText lost its focus

| software         | version
| ---------------- | -------
| react-navigation | ^1.0.0-beta.11
| react-native     | 0.48.3
| node             | 6.11.1
| npm or yarn      | 3.10.10

**Comment by carsonwah** [comment]
Maybe the navigate method altered this.props.navigation so causing the current screen to re-render and get the focus.

If you don't have UI to be changed, you can try putting the logic in shouldComponentUpdate() and see if it works.

Better for this case though (I guess it's the login -> Home logic?), I think you should not use navigation.

Maybe something like this?

```
render() {
  if (this.state.appLoading) {
    return <AppLoading>;
  } else {
    if (this.props.accessToken) {
      return <Home>;
    } else {
      return <Login>;
    }
  }
}
```
