### ISSUE TITLE
DrawerToggle does not work as expected -It doesn't closes the DrawerNavigation

### ISSUE THREAD

**Issue by DFelten** [react-navigation/react-navigation#2689]
### Current Behavior
The behavior of `navigation.navigate('DrawerToggle')`  is not as expected. On this example the menu button should open and close the drawer navigation. But it's only possible to open it. When the drawer is visible, the button does nothing.

```javascript
const DrawerNavigation = StackNavigator({
  DrawerStack: {screen: DrawerStack},
}, {
  headerMode: 'float',
  navigationOptions: ({navigation}) => ({
    headerStyle: {backgroundColor: 'green'},
    title: 'Welcome!',
    headerTintColor: 'white',
    headerLeft: <Text onPress={() => {
      navigation.navigate('DrawerToggle')
    }}>Menu</Text>
  }),
});
```
With DrawerOpen and DrawerClose instead it's working

```
if (navigation.state.index === 0) {
  navigation.navigate('DrawerOpen')
} else {
  navigation.navigate('DrawerClose')
}
```

I thought DrawerToggle should be a replacement for this if block, so the drawer opens and closes through the button.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.13
| react-native     | 0.47.2
| node             | 8.6.0
| npm or yarn      | yarn

**Comment by vonovak** [comment]
can you post full code? ideally an expo snack?

**Comment by DFelten** [comment]
Sorry, it's not possible to post the full code, because it's a project for a customer. When creating the navigation, I followed [this tutorial](https://shift.infinite.red/react-navigation-drawer-tutorial-a802fc3ee6dc).  

[There](https://github.com/GantMan/drawer-example/blob/master/Navigation/AppNavigation.js) in line 35 you can see the corresponding part.

**Comment by vonovak** [comment]
@DFelten I meant a repository which reproduces the bug. Some thing that people can clone and run to see the error.

**Comment by DFelten** [comment]
I've created an [Expo Snack](https://snack.expo.io/rJicaEGTW) (my first one). 

There you can see that it's only possible to open the Drawer with _DrawerToggle_

**Comment by sunnixx** [comment]
Having the same problem, any luck ?

**Comment by DFelten** [comment]
@sunnixx 
I'm using the mentioned workaround 


```
if (navigation.state.index === 0) {
  navigation.navigate('DrawerOpen')
} else {
  navigation.navigate('DrawerClose')
}
```

**Comment by brentvatne** [comment]
I updated the Snack to the latest version and it works as expected: https://snack.expo.io/SJvS0p3Lz
