### ISSUE TITLE
Change navigationOptions header components switching tabs

### ISSUE THREAD

**Issue by JayricMok** [react-navigation/react-navigation#2699]
### Current Behavior
I have done some research on docs and stackoverflow, cannot find any related post/docs about this. 
I using TabNavigator and StackNavigator for my app navigation, I would like to change the navigationOption header components when switching tabs. I have 3 tabs, `Home` , `Live` and `Radio`

### Expected Behavior
Example -
When tab is Home header components is 
    `<View><ScrollView><GenerateList_1/></ScrollView></View>`
When tab is Live header components is 
    `<View><ScrollView><GenerateList_2/></ScrollView></View>`

### Code 
        const mainNav = TabNavigator({
          Home: { screen: HomeScreen},
          Live: { screen: LiveScreen },
          Radio: { screen: RadioScreen},
        } );

        export const mainStack = StackNavigator({
          Home: { 
            screen: mainNav,
            navigationOptions: {
              header: (
                      <View style={styles.topnavscrollview}>
                        <View style={{width:300}}>
                          <ScrollView horizontal={true} showsHorizontalScrollIndicator={false}>
                            <GenerateList_1/> <-- Change this when switch to Live tab or others
                          </ScrollView>
                        </View>
                      </View>
              ),
            },
          },
          Content: { screen: ContentScreen },
        });

**Current header is share on each tab**

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 5.3.0
| react-native     | 0.48.4

**Comment by JayricMok** [comment]
Anyone can help ? Thanks

**Comment by kelset** [comment]
Uhm ok I may have an idea on how to do something like that, but it's not pretty.

Basically, you should have something like this in the stack navigator component:

```js
  static navigationOptions = ({ navigation }) => {
    let header = null;

    return {
      header: navigation.state.params.customHeader,
    };
  };
```

and in its componentWillReceiveProps a switch case where you pass the dedicated header:

```js
  componentWillReceiveProps(nextProps) {
    const index = nextProps.navigationTab.index;

    switch (index) {
      case 1:
        this.props.navigation.setParams({
          customHeader: (
            <Header1/>
          ),
        });
        break;
      case 2:
        this.props.navigation.setParams({
          customHeader: (
            <Header2/>
          ),
        });
        break;
      default:
        this.props.navigation.setParams({
          customHeader: null,
        });
        break;
    }
  }
```

Note well: this is fake code just to explain what you should do.

**Comment by JayricMok** [comment]
@kelset where to put componentWillReceiveProps ? sorry, I very new in React Native

**Comment by JayricMok** [comment]
@kelset btw my navigationOptions must inside StactNavigator, cannot put outside as static

**Comment by kelset** [comment]
You need to have the navigator as a component:

```js
const MyStack = StackNavigator(routeConfiguration, stackNavigatorConfiguration);

class EventTabBarNavigation extends React.Component {
  render() {
    const { dispatch, navigationState } = this.props;

    // BOTH THINGS I'VE WRITTEN ABOVE GO HERE

    return (
      <View style={styles.container}>
        <MyStack
          navigation={addNavigationHelpers({
            dispatch,
            state: navigationState,
          })}
        />
      </View>
    );
  }
```

Again, this is "fake code" to explain what you should do to achieve that.

**Comment by JayricMok** [comment]
@kelset sorry I still very confused, actually in my new question i just want to know how to pass the param from tabnavigator to stacknavigator

**Comment by brentvatne** [comment]
```
    const mainNav = TabNavigator({
      Home: { screen: HomeScreen},
      Live: { screen: LiveScreen },
      Radio: { screen: RadioScreen},
    } );

   mainNav.navigiatonOptions = ({ navigation }) => {
      let { routeName } = navigation.state.routes[navigation.state.index];
      if (routeName === 'Home') {
      // etc...
   }
```

that said, this is a question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.
