### ISSUE TITLE
Accessing root stack from within child stack

### ISSUE THREAD

**Issue by rrajasek92** [react-navigation/react-navigation#2700]
Is there a way to access a root stack navigator from an inner stack navigator? For example:

```
const Root = StackNavigator(
{
  Login: {
      screen: Login,
    },
    TabNav: {
      screen: TabNav    
    }
}
);
```

```
const TabNav = TabNavigator(
  {
    Content: {
      screen: Content,
    },
    Settings: {
      screen: SettingsStack
    }
  }
);
```

Within that SettingsStack screen I have a logout button. How would I access the Root Stack to navigate back to Login? Rather than that inner stack in the Tab Navigation just pushing to the login page.

**Comment by ArvoGuo** [comment]
+1

**Comment by ArvoGuo** [comment]
`key` option helps me.
``` js
this.props.navigation.dispatch(NavigationActions.reset({
  index: 0,
  actions: [NavigationActions.navigate({ routeName: 'Login' })],
  key: null  
}));
```

`key`, string or null - optional - If set, the navigator with the given key will reset. If null, the root navigator will reset.
