### ISSUE TITLE
StackNavigator inside TabNavigator inside DrawerNavigator - How to display header?

### ISSUE THREAD

**Issue by Balasnest** [react-navigation/react-navigation#2701]
I have stackNavigator inside TabNavigator. 
I'm showing a Menu Button in the TabNavigator Header which open the Drawer. If I start moving from stackNavigator I would like to show stackNavigator header and hide the tabNavigator header.

**Expected behaviour result:**
I would like to show stackNavigator header and hide the tabNavigator header.

**Actual Behaviour result:**
Its showing tabNavigator header which open the Drawer everwhere. So it cannot go back from the current stack navigator.

code:
[Check the code here](https://stackoverflow.com/questions/46448679/stacknavigator-inside-tabnavigator-inside-drawernavigator-how-to-display-heade)

**Comment by AnthonyLamot** [comment]
I was looking for similar behavior actually.

What I found is to set the `headerMode: 'none'` for your parent navigator (the Drawer in your case). Instead,  define the headers themselves  in the StackNavigators:

```
    screen: SomeScreen,
    navigationOptions: {
      headerTitle: 'Journal',
   },
```

So there is no real "hiding", but this workaround should get the behavior I think you seek.

Hope that helps!
