### ISSUE TITLE
this.props.navigation.setParams resulting in infinite loop

### ISSUE THREAD

**Issue by tehwayne** [react-navigation/react-navigation#2702]
### Current Behavior
Running this.props.navigation.setParams in componentDidMount results in an infinite loop for 1.0.0-beta.13, currently using a Tabnavigator, when this tab is the 1st opened there is an infinite loop, if it's the second (hidden) tab then the background render completes with no issues.

### Expected Behavior
Running this.props.navigation.setParams should not result in an infinite loop.

**Comment by PatNeedham** [comment]
@tehwayne can you share the code sample to reproduce this?

**Comment by tehwayne** [comment]
Yep, hopefully this is clear enough and lmk if you need more info. New to all of this, so hopefully I'm doing it correctly! Thanks for taking a look! 

In my header:

```
const Header = {
  getHeader: (navigation) => {
    return {
      headerTitle: ('Groups'),
      headerRight: (
        <TouchableOpacity onPress={() => navigation.state.params.profileMenuClick()}>
          <View style={{ marginRight: 13 }}>
            <Icon
              name="person"
              type="material"
              color="black"
              style={{ padding: 2 }}
              size={26}
            />
          </View>
        </TouchableOpacity>
      ),
    };
  },
};
```

and then in the parent component: 

`static navigationOptions = ({ navigation }) => Header.getHeader(navigation);`

```
  componentDidMount() {
    this.props.navigation.setParams({
      profileMenuClick: this.profileMenuClick,
    });
  }
```

**Comment by tehwayne** [comment]
Oh also, sorry I didn't see/respond before, this is current occurring on iOS simulator (iOS 11), I can update when I get a chance to test on device if that would help

**Comment by coolguy001tv** [comment]
It happens on me in an android device. Hoping for the solution.

**Comment by kelset** [comment]
From a first look, I think this may be related to what `profileMenuClick` do.

Probably the easiest way to better understand would be to see the code in that method. I'm concerned that it changes some props that then triggers the re-render of the screen/header in which is contained.

The "rough way" to debug this issue would be to do a couple things.

1. write the Header this way:

```js
const Header = {
  getHeader: (navigation) => {
    console.log('getting called with this param',navigation.state.params.profileMenuClick );
    return {
      headerTitle: ('Groups'),
      headerRight: (
        <TouchableOpacity onPress={() => navigation.state.params.profileMenuClick()}>
          <View style={{ marginRight: 13 }}>
            <Icon
              name="person"
              type="material"
              color="black"
              style={{ padding: 2 }}
              size={26}
            />
          </View>
        </TouchableOpacity>
      ),
    };
  },
};

```

To understand if the param is defined every time the header is created.

2. add a console.log inside the TouchableOpacity to better understand when it gets called:

```js
        <TouchableOpacity onPress={() => {
            console.log('getting called by touch');
            navigation.state.params.profileMenuClick();
          }}>

``` 

3. trying to do the same thing inside `profileMenuClick`

**Comment by tehwayne** [comment]
Hi, sorry about the delayed response, I've since changed the code to just move the tabs around. 

Before I had this for `profileMenuClick` 

``` 
profileMenuClick = () => {
 console.log('click');
 this.showProfileModal();
 }
```

then

```
showProfileModal = () => {
 this.setState({ isProfileModalVisibile: true });
}
```

I believe that the code should work normally unless header code is re-rendering with each param change (my hypothesis) because I was using `showProfileModal` without any issues in other parts of the main view/non-header component.

**Comment by kelset** [comment]
@tehwayne have you tried to do what I suggested in my last comment?
I think too that something in your code is forcing the header to re-render constantly, but I don't believe it's caused by the library itself.

**Comment by raulclaudino** [comment]
It worked for me:
```

componentDidMount() {
        InteractionManager.runAfterInteractions(() => {
            this.props.navigation.setParams({ kindOfList: 'grid' });
        });
    }
```

**Comment by tehwayne** [comment]
Hey @kelset, thanks for taking a look again! I did what you suggested and when I run the code "getting called with this param" is the only log that appears. It looks like the header keeps getting re-rendered when I set a function into the params for a Tabnavigator, when the Tab with the params is in the front. 

The code in profileClick never gets called (log('click')) and even when I remove all code the infinite loop still occurs. 

Am I perhaps using params incorrectly which results in it being re-rendered? Is it not meant to be used with functions? I do have it working with other navigator situations, just not this one. 

@raulclaudino, was this with a Tabnavigator and a function? I don't encounter this issue without a Tabnavigator with params being set with the Tab as the 1st tab in the view and the params being a function.

**Comment by kelset** [comment]
Possibly related https://github.com/react-community/react-navigation/issues/2931

**Comment by nodece** [comment]
It is worked
```
componentDidMount() {
        InteractionManager.runAfterInteractions(() => {
            this.props.navigation.setParams({ kindOfList: 'grid' });
        });
 }
```

**Comment by brentvatne** [comment]
in tab navigator: https://snack.expo.io/ryKg7lKUz
in stack navigator: https://snack.expo.io/SklGQeYIM

cannot repro this. please create a new issue with an executable piece of code (preferably on snack, as I shared above) or in a github repository (minimal, without a bunch of other stuff in it) that I can clone and run

**Comment by gijoehosaphat** [comment]
Check that you have no duplicate route keys. This symptom can appear in those situations.

**Comment by nodece** [comment]
@youngjuning  React Native API, I think this issue should be closed.  Use react-native 2.x is working.

**Comment by yongching** [comment]
I still having this issue in `2.18.2` 🤨

**Comment by fkomaralp** [comment]
I still having this issue in `3.3.2`

**Comment by brentvatne** [comment]
this should be resolved. if it is not working as expected still on the latest version, please create a new issue with a runnable example on https://snack.expo.io -- thanks!
