### ISSUE TITLE
Drawer does not work with GoogleMap

### ISSUE THREAD

**Issue by emregurler** [react-navigation/react-navigation#2728]
### Current Behavior
I am using airbnb-maps module. I designed navigation like this:
 StackNav > DrawerNav > TabNav
In TabNav, I have 2 screens and one of them is Map. When I am on the Map tab, I cant call Drawer on Map, but I can pull it from header.
Here is my code:
```
const DrawerHomeScreen = DrawerNavigator(
	{
		HomeScreen: {
			screen: HomeScreen,
		},
	},
	{
		contentComponent: (props: any) => <DrawableContent {...props} />,
		drawerPosition: 'left',
		drawerWidth: 250,
	},
)
```

### Expected Behavior
- My drawer should come on the map when I pull screen from left. I am definetely sure that it does not work in the map. Map went left, but Drawer didn't come. I tried to pull it very slow, very fast from very very left of screen. Am I doing something wrong or is it an issue ?

### My Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.13
| react-native     | 0.48.4
| node             | v8.1.4
| npm or yarn      | yarn

**Comment by edisonywh** [comment]
What devices did you test it on?It doesn't work on my Android device (the map moves, like you said), whereas on my iOS device, the map moves BUT it also opens up the drawer.

**Comment by emregurler** [comment]
How can we solve this android issue? Working like ios is enough for me. Any help is appriciated

**Comment by alanselo** [comment]
Did you find anything on this issue? Tks

**Comment by markmssd** [comment]
I'm having the exact same problem. Did you guys find a solution?

**Comment by brentvatne** [comment]
the gesture conflicts with the map gesture. we'll switch to react-native-gesture-handler for the drawer soon which should hopefully let us handle this properly. cc @kmagiera

**Comment by baaart** [comment]
Any update on this? Is there any workaround or we have to use hamburger icon on maps?

**Comment by marcmo** [comment]
ran into the same thing. As a workaround I was thinking of overlaying my mapscreen with a transparent view that only covers a small part of the screen...but currently I have no idea how to do this.
any thoughts?

**Comment by brentvatne** [comment]
no update, use an icon if you must. we'll get to using react-native-gesture-handler soon

**Comment by marcmo** [comment]
[this](https://stackoverflow.com/questions/44602642/react-native-drawer-not-opening-on-swipe-over-map/49905612#49905612) technique worked for me...no need for an icon

**Comment by brentvatne** [comment]
we're switching over to using react-native-gesture-handler for drawer on this branch https://github.com/react-navigation/react-navigation-drawer/branches - that should resolve the issue in the future. for now, the workaround @marcmo linked to should be good

**Comment by emregurler** [comment]
Thanks for helping guys
