### ISSUE TITLE
TabNavigator: Ability to style a tab's content container with cardStyle

### ISSUE THREAD

**Issue by joncursi** [react-navigation/react-navigation#2730]
### Current Behavior

I have a TabNavigator that uses `lazy` loading. The issue I'm having is that when the user taps on a lazily loaded tab, they see an awkward empty state while the tab is rendering (in my case, a bright red color because red is my default screen background.

### Expected Behavior
What I would like to do is customize the background color of the tab content, i.e. a `cardStyle` prop so that I can make the split second the content is rendering look less hideous.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | latest
| react-native     | latest
| node             | latest
| npm or yarn      | latest

**Comment by kelset** [comment]
Hi @joncursi thanks for this feature request.

I wonder, wouldn't be enough to wrap the navigator into a `<View style={{flex:1, backgroundColor: 'less-hideous.color'}}> <TabNavigator> </ View>`?

**Comment by joncursi** [comment]
My tab navigator is nested in a root stack navigator. So if I were to follow your suggestion, wouldn’t I have to wrap the stack navigator instead? The problem with doing this is that now I’m applying styles to every screen instead of just the tabs where I need it. I’m looking for screen based option or a tabs based option, rather than an entire app option. I already wrap my entire app with a default background color, but I’m trying to customize this background color for when the tabs are loading.

With regard to package versions... I submitted this issue on beta 13, it was still present on beta 14, and it is also still present on beta 15.

**Comment by kelset** [comment]
> So if I were to follow your suggestion, wouldn’t I have to wrap the stack navigator instead?

First off I didn't know about it being nested in a StackNavigator.
Second, you can simply add that View with background to that screen of the stack; if you can put your code into a simple [Expo Snack](https://snack.expo.io/) it would be easier to help btw.

**Comment by brentvatne** [comment]
please re-post to https://react-navigation.canny.io/feature-requests if this is important for you. re-organizing issues to focus on bug reports here and feature requests on canny. thanks!

**Comment by jpamarohorta** [comment]
I know this issue is old and it's closed but did you @joncursi manage to find a solution for your problem? I'm having the same issue now with a TabNavigator inside a StackNavigator.
