### ISSUE TITLE
Transition from headerless screen to screen with header jerks content on first screen down

### ISSUE THREAD

**Issue by mschipperheyn** [react-navigation/react-navigation#2732]
### Current Behavior
I have two screens, one is without a header and one is with a header. The content on screen one is centered vertically. 

When I navigate from screen 1 to screen 2, during the transition, the content from screen 1 jumps down to the position it would have had if the screen did have a header.

### Expected Behavior
The content on screen 1 should stay in place.

### Your Environment
| react-navigation | 1.0.0-beta.13
| react-native     |  0.49.3
| node             | 8.5.0
| npm or yarn      | yarn

## code
```
const ScreenStack = StackNavigator(
    { ...routez.drawerRoutez, ...routez.loginRoutez },
    {
        initialRouteName: 'Loading',
        headerMode: 'float',
    },
);

const PrimaryNav = DrawerNavigator(
    {
        DrawerStack: {
            screen: ScreenStack,
        },
    },
    {
        headerMode: Platform.OS === 'ios' ? 'float' : 'screen',
        navigationOptions: ({ navigation }) => ({
            headerStyle: { backgroundColor: 'green' },
            gesturesEnabled: false,
            headerLeft: (
                <IconButton
                    icon="menu-1"
                    onPress={() => {
                        if (navigation.state.index === 0) {
                            navigation.navigate('DrawerOpen');
                        } else {
                            navigation.navigate('DrawerClose');
                        }
                    }}
                />
            ),
        }),
    },
);

export default PrimaryNav;
```

```
class LoginScreen extends React.Component {
}

LoginScreen.navigationOptions = {
    header: null,
    drawerLockMode: 'locked-closed',
};

class RegisterScreen extends React.Component {
}

const Title = () => <FormattedMessage id="ui.registration" />;

RegisterScreen.navigationOptions = ({ navigation: { state: { params = {} } } }) => ({
    drawerLockMode: 'locked-closed',
    title: <Title />,
    headerRight: (
        <HeaderSaveButton
            formName={FORM}
            dispatch={params.dispatch}
            submitting={params.submitting}
            title={params.title}
        />
    ),
});

```

**Comment by helios1138** [comment]
you can give header a height and set the same value as negative margin on root view

**Comment by mschipperheyn** [comment]
Yeah, that would be a workaround. But it does seem to me like a bug.

**Comment by kelset** [comment]
Thanks for reporting. Is it related in any way to https://github.com/react-community/react-navigation/pull/2520?

**Comment by heyjared** [comment]
Also facing this issue. While transitioning from ScreenWithoutHeader to ScreenWithHeader, it will push push content down on ScreenWithoutHeader to make space for the header, reducing the available height on the screen. If using flex, this will cause the content on the screen to suddenly compress and look weird.

**Comment by fengshanjian** [comment]
Is there any one to fix this bug? It's so irritable

**Comment by fengshanjian** [comment]
@kelset It does not  related to   [https://github.com/react-community/react-navigation/pull/2520](#2520)

**Comment by richeterre** [comment]
I also experience this bug and so far worked around it by setting the "headerless" screen's header color to `'transparent'` and giving its view a negative top margin of 64 points.

However, this doesn't really work with the iPhone X, which has its own status and navigation bar heights. @davepack & @kelset, is there a way to retrieve the appropriate margin from `react-navigation`, or some other workaround for this?

**Comment by lancelotlan** [comment]
Use the component "Modal" to cover the header of "headerless screen" with animationType={"none"}.It's not a good way but seems not bad for me.

**Comment by cbjs** [comment]
+1

**Comment by longdw** [comment]
@richeterre  when I set header color to 'transparent',  it turned to black.
```
navigationOptions: {
     headerStyle: { backgroundColor: 'transparent' }
}
```

**Comment by richeterre** [comment]
@longdw: It's not the header that turned black, but rather you're seeing through it onto whatever is behind (usually your root view). You missed the second part of my hack, which is to apply a negative top margin to the content of the page with the "hidden" header. For instance, if that page has a background image, give the image a `marginTop` of `-64` (or `-88` for iPhone X) and it will cover the area that is currently black for you. By the way, this whole issue seems to be iOS-only.

As you can see from the magical numbers, this isn't really a clean solution, but the best I could find. Let's hope this will be addressed in an upcoming release to match the native iOS behavior.

**Comment by longdw** [comment]
@richeterre nice, it seems that this method can only be used to solve, thank you very much, but also hope that the RN team to solve this problem as soon as possible.

**Comment by cihakcc** [comment]
Transparent header doesn't work for me, as I can't touch anything "under" the header...

**Comment by brentvatne** [comment]
cc @skevy did you have a good fix for this?

**Comment by brentvatne** [comment]
moved to feature request https://react-navigation.canny.io/feature-requests/p/smooth-transition-from-screen-without-header-to-screen-with-header

**Comment by cbjs** [comment]
@richeterre this solution seems not work for TabNavigator screens.

**Comment by richeterre** [comment]
Just noticed that [v1.2.0](https://github.com/react-navigation/react-navigation/releases/tag/v1.2.0) adds a `headerTransparent` config option to the screen navigation options, so instead of my [above hack](https://github.com/react-navigation/react-navigation/issues/2732#issuecomment-341717998) (making the header's background color transparent and setting a negative top margin on the content), you can now simply set that to `true`. The header transition still isn't animated, but at least the code is much cleaner!

**Comment by bighitbiker3** [comment]
@cihakcc My solution to this was to add `pointerEvents='none'` to my custom header. Not sure if you can pass that to the built in header, but worth a shot

**Comment by rickvdl** [comment]
Unfortunately still happening for, with a bottomTabNavigator containing two tabs, each having it's own stackNavigator. Using version `2.16.0`.

**Comment by brentvatne** [comment]
@rickvdl - please post new issue and fill out issue template
