### ISSUE TITLE
title only accepts text as value and headerTitle doesn't apply formatting

### ISSUE THREAD

**Issue by mschipperheyn** [react-navigation/react-navigation#2762]
### Current Behavior
Internationalized applications tend to use react-intl.
react-intl allows you to use `<FormattedMessage id="ui.wall"/>` to access translation texts irrespective of context or props, and is therefore the goto choice for applying translations, especially in static contexts.

while this
```
const drawerRoutez = {
    Wall: {
        path: 'account/wall',
        getScreen: () => require('screens/WallScreen').default,
        navigationOptions: {
            title: <FormattedMessage id="ui.wall" />,
        },
    },
```
seems to work with React-Navigation at first glance, when you navigate an error occurs:
<img width="334" alt="screen shot 2017-10-16 at 10 35 19" src="https://user-images.githubusercontent.com/384959/31612334-294e0eb2-b25e-11e7-8c39-ce9fe42bf827.png">

Alternatively, you can use headerTitle to be able to use React Elements. However, in this case, no formatting is applied, requiring you to replicate formatting styles which is part of the point we are using react-navigation. 

### Expected Behavior
`headerTitle` should apply the formatting that `title` applies. Users can always override this if they need to.
Ideally, `title` should not distinguish between element or text and simply act according to whatever is passed in.

### Your Environment
| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.13
| react-native     | 0.49.4
| node             |
| npm or yarn      |

**Comment by dantman** [comment]
The `HeaderTitle` component is exported by react-navigation. You should be able to use it directly to get the same formatting.
