### ISSUE TITLE
Drawer navigator disable overlap with main content

### ISSUE THREAD

**Issue by kazixma** [react-navigation/react-navigation#2784]
I want to open drawer and move main content to side.

example like this

![alt text](https://i.stack.imgur.com/r3MXn.jpg)

Thank

**Comment by kelset** [comment]
Hi @kazixma.
That approach to the drawer is not possible because it's on, as far as I know, in line with the Android guidelines, which are the foundation of the library [`react-native-drawer-layout`](https://github.com/react-native-community/react-native-drawer-layout) we rely on for the drawer.

**Comment by monotv** [comment]
It would be great if the drawer supported different sliding behaviours like react-native-drawer does for example. The one OP is talking bout would be the 'Slack' type. In my case this is a showstopper for the react-navigation DrawerNavigator and I have to patch some mix of different modules together to make it work. Would be great if this worked in react-navigation alone.

**Comment by brentvatne** [comment]
please re-post to https://react-navigation.canny.io/feature-requests if this is important for you. re-organizing issues to focus on bug reports here and feature requests on canny. thanks!

**Comment by DVLNarayana** [comment]
any progress on this feature?

**Comment by dev4xy** [comment]
+1

**Comment by cseelus** [comment]
Its implemented, use `drawerType: 'back'` or `drawerType: 'slide'` within the `DrawerNavigatorConfig`

https://reactnavigation.org/docs/en/drawer-navigator.html#docsNav
