### ISSUE TITLE
useHorizantalTabs broken on split-screen iPad layout

### ISSUE THREAD

**Issue by SteffeyDev** [react-navigation/react-navigation#2794]
### Current Behavior
- When the app is launched in split-view mode or as a popover on the latest iPads running iOS 11 (taking only 1/4 or 1/3 of the screen width), the labels still show next to the tabs instead of beneath them, and thus the labels end up overlapping onto the next tab bar icon.
- The labels that show next to the icon are a comically small font size, as if they had simply been moved from the bottom to the sides.
- An iPad that is in portrait mode shows the labels beneath the icons

### Expected Behavior
- When an iPad app has a [Size Class](https://developer.apple.com/library/content/featuredarticles/ViewControllerPGforiPhoneOS/TheAdaptiveModel.html) of Horizontal: Compact, the labels should move to beneath the icons, and when the iPad app is in Horizontal: Regular, the labels should be next to the icon.
- The font size for labels **next** to the icons should be several points larger
- On an iPad, the labels should show besides the icon whenever the app is in Horizontal: Regular size class, despite current orientation
- This is the behavior of other iOS native applications

The issue is in this file: https://github.com/react-community/react-navigation/blob/master/src/views/TabView/TabBarBottom.js
It looks like `isLandscape` is returning true when the physical device is in landscape mode, regardless of the size class or trait collection currently active for the device.  Obviously, this can have countless side effects when using different combinations of split-views.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.15
| react-native     | 0.48.4
| node             |  7.7.1
| yarn      | 1.1.0

**Comment by vonovak** [comment]
Seems like we will need some api for getting the size class and listening for its change. Alternatively, we can listen to onLayout and find out how much space we have available and act accordingly (easier). I'm not an experienced iOS dev, do you guys think that will be enough?

**Comment by SteffeyDev** [comment]
The issue with the second approach that I see is that the threshold between regular and compact size classes that Apple uses is not constant nor is it published that I know of.  You could have a giant switch for every available size and split screen configuration and look at the pixel ratio but then as soon as Apple releases a new iPad or changes iOS to allow new layouts things break.  

Querying size classes would be future-proof and reliable, but require at least one UIViewController to receive and broadcast the initial configuration the change event.  I know you guys are trying not to use native code though so....

**Comment by dantman** [comment]
We probably don't need to query iOS specific size classes. The React Native Dimensions has separate `window` and `screen` dims. Presumably this code is using the `window` dimensions to change layout. On Android these dims are different and you should get the right behaviour in multi-tasking modes. However in iOS which never had any variable layout stuff for a whole decade, Reaxct Native just exported the same dimensions as both `screen` and `window`.

The best fix would just be to get react native to output the correct window dimensions, then this functionality would immediately start working again.

**Comment by SteffeyDev** [comment]
I agree that RN should be exporting the correct window dimension, but even so, you still don’t know the threshold of size classes (at what dimension do you move from labels next to icons to labels beneath icon, and isLandscape will still return true if the iPad is in landscape mode, regardless of window dimensions. 

You can ballpark the correct pixel width at which you should move, and that would be close to correct, but that is only after RN is updated

**Comment by vonovak** [comment]
I guess some may disagree, but my personal opinion is that we don't need to
copy the ios behavior *exactly*. We can set our own boundaries at which the
way things are displayed would change. Of course, by default, it would be
something that is the same or close to native ios, but we may give library
users a way to customize this if they like.

Even if the RN dimensions api does not return correct window size, I
believe we may use `onLayout` and the dimensions it returns, to handle
this. isLandscape would be removed

On Oct 24, 2017 19:15, "SteffeyDev" <notifications@github.com> wrote:

I agree that RN should be exporting the correct window dimension, but even
so, you still don’t know the threshold of size classes (at what dimension
do you move from labels next to icons to labels beneath icon, and
isLandscape will still return true if the iPad is in landscape mode,
regardless of window dimensions.

You can ballpark the correct pixel width at which you should move, and that
would be close to correct, but that is only after RN is updated

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/react-community/react-navigation/issues/2794#issuecomment-339064744>,
or mute the thread

**Comment by SteffeyDev** [comment]
Actually I think this will work great, and if you wanted to one-piece iOS you could adjust the threshold depending on the number of tabs, so with two tabs the labels could stay next to the icons at a smaller width than with five tabs. Though that would be a feature, it certainly would be best to have this fixed first

**Comment by kelset** [comment]
Hey @SteffeyDev , we released beta.17; does your issue still happen in the latest version?

**Comment by SteffeyDev** [comment]
@kelset I will check, but because this issue was not mentioned in any PR’s I would be surprised if it was fixed yet.

**Comment by SteffeyDev** [comment]
Amazingly it is actually even more broken now, on iPad in landscape with split screen, not only are the words next to the icons (even when the area is iPhone-width) but now the tab bar is so short that the icons almost go out the top.

**Comment by kelset** [comment]
Ugh sorry about that, we'll look into it!

**Comment by SteffeyDev** [comment]
Any update on this or estimate on when it might be implemented? If it's not fixed in the next month I might have time for a PR over the break but I would love to see a fix before then

**Comment by kelset** [comment]
Hey @SteffeyDev sorry, as far as I know, we don't have this fix as in the roadmap. So yeah if you could submit a PR it's probably the fastest route anyway.
