### ISSUE TITLE
Question: Is there any suitable way to unsubscribe event on tab change

### ISSUE THREAD

**Issue by sadi304** [react-navigation/react-navigation#2803]
Hello, 
I am aware of the issue that component life cycle hooks don't get called if a tab is rendered already. I have an event in a tab (Shake Event), the problem is even when i switch the tab the event is already subscribed as componentwillunmount is never called from that screen (that leads to no remove listener of the event to be called). So in other screen the event is occuring also. I am asking for help if there's any suitable way to handle this scenario. I am not using redux.  TIA

**Comment by spencercarli** [comment]
Have you tried using the [tabBarOnPress](https://reactnavigation.org/docs/navigators/tab#tabBarOnPress) to take care of the issue?

**Comment by sadi304** [comment]
@spencercarli , there is a problem in that case. If backbutton is pressed or again home tab then the event is not instantiated again . No idea why this is happening .

**Comment by spencercarli** [comment]
Can you put together a demo of the behavior you're seeing? I'm not sure I'm following

**Comment by sadi304** [comment]
okay i will post the code . later .

**Comment by brentvatne** [comment]
you can use `this.props.navigation.addListener` for this! https://reactnavigation.org/docs/navigation-prop.html#addlistener-subscribe-to-updates-to-navigation-lifecycle

**Comment by sadi304** [comment]
moved to router flux at this moment. handling via onEnter and onExit props .
