### ISSUE TITLE
Call action when pressing tab in TabNavigator

### ISSUE THREAD

**Issue by mazing** [react-navigation/react-navigation#2804]
I have two tab navigators at different routes.

Is it possible to navigate to a route by pressing a tab?

I have tried

    const TabNavigator1 = TabNavigator({
      Home: {
        screen: HomeScreen,
      },
      Exit: {
        screen: ({ navigation }) => {
          navigation.navigate('TabNavigator2')
          return Something // because it has to return something
        },
    })

it actually does navigate as I wanted, but I receive a warning saying `Functions are not valid as React child`.

It also seems a bit hacky to do it like this. Could I replace `screen: ({ navigation }) => ...` with something like `onPress: ({ navigation }) => ...`

**Comment by carsonwah** [comment]
[According to the doc](https://reactnavigation.org/docs/navigators/tab), does customizing `tabBarOnPress` works for you? Though it only provides a `jumpToIndex()` exit method. I'm not sure.

**Comment by 2ducanhpham** [comment]
```
import { StackNavigator, TabNavigator, TabBarBottom } from 'react-navigation';

//config 
tabBarComponent: (props) => {
    return (
      <TabBarBottom
          {...props}
          jumpToIndex={(index) => {
            //code here
            //ex: props.screenProps.rootNavigation.dispatch(jumpToTabYourPost(index));
        }}
      />
    )
  },
  initialRouteName: 'DEMO',
```

**Comment by carsonwah** [comment]
@mazing You may also take a look on my implementation for scrollToTop function.

https://github.com/react-community/react-navigation/issues/2955

**Comment by satya164** [comment]
Closing since `tabBarOnPress` option already exists.
