### ISSUE TITLE
Error on shallow render during tests in jest

### ISSUE THREAD

**Issue by hrkeni** [react-navigation/react-navigation#2820]
I've been going through the issues and I believe #699 is pretty much the same but that does not have any resolution in it.

### Current Behavior
- I have hooked up react-navigation with redux and trying to test with jest and enzyme.
- When running in simulator or on a phone, the navigation works as expected
- When running with the test runner, I get the following errors:

``` 
FAIL  src/test/components/LoginScreen.spec.tsx
  ● Test suite failed to run

    Route 'Login' should declare a screen. For example:

    import MyScreen from './MyScreen';
    ...
    Login: {
      screen: MyScreen,
    }

      at node_modules/react-navigation/src/routers/validateRouteConfigMap.js:22:7
          at Array.forEach (<anonymous>)
      at validateRouteConfigMap (node_modules/react-navigation/src/routers/validateRouteConfigMap.js:18:12)
      at Object.<anonymous>.exports.default (node_modules/react-navigation/src/routers/StackRouter.js:37:37)
      at Object.<anonymous>.exports.default (node_modules/react-navigation/src/navigators/StackNavigator.js:39:37)
      at Object.<anonymous> (src/navigators/AppNavigator.tsx:7:103)
      at Object.<anonymous> (src/actions/LoginActions.ts:1:7545)
```
- I believe the cause of this is that an action creator dispatches an action to navigate using my AppNavigator

Here is the action creator:
```
const loginUser = (email: string, password: string) => {
    return (dispatch: Dispatch<any>): Promise<any> => {
        dispatch(loginUserWait(true));
        return UserDal.login(email, password)
        .then((user) => {
            dispatch(loginUserSuccess(user));
            dispatch(AppNavigator.router.getActionForPathAndParams('OtherScreen'));
        })
        .catch(() => dispatch(loginUserFail()));
    };
};
```

This is my AppNavigator:
```
import React from 'react';
import { connect } from 'react-redux';
import { addNavigationHelpers, StackNavigator } from 'react-navigation';
import LoginScreen from '../components/LoginScreen';
import OtherScreen from '../components/OtherScreen';

export const AppNavigator = StackNavigator({
    Login: { screen: LoginScreen },
    OtherScreen: { screen: OtherScreen }
}, {
    initialRouteName: 'Login'
});

class AppWithNavigationState extends React.Component<any, any> {
    render() {
        return (
            <AppNavigator navigation={addNavigationHelpers({
                dispatch: this.props.dispatch,
                state: this.props.nav
            })} />
        );
    }
}

const mapStateToProps = state => ({
    nav: state.nav
});

export default connect(mapStateToProps)(AppWithNavigationState);

```

This is what my test looks like:
```
import React from 'react';
import { shallow } from 'enzyme';
import configureStore from 'redux-mock-store';
import LoginScreen from '../../components/LoginScreen';
import thunk from 'redux-thunk';
import { GlobalState } from '../../reducers/index';

const mockStore = configureStore([ thunk ]);

const initialState: GlobalState = {
    auth: {
        error: '',
        loginLoading: false,
        user: {
            email: '',
            id: -1,
            password: '',
            name: ''
        }
    },
    nav: {}
};

describe('Testing the LoginScreen component', () => {
    it('renders the LoginScreen', () => {
        const wrapper = shallow( <LoginScreen />, { context: { store: mockStore(initialState) } });
        expect(wrapper.dive()).toMatchSnapshot();
    });
});

```

### Expected Behavior
- I expect since the test is a shallow render of a specific screen component, there should not even be any reason for navigation to affect this test

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |1.0.0-beta.15
| react-native     |0.49.3
| node             |8.4.0
| npm or yarn      |yarn@1.2.1

**Comment by kelset** [comment]
Hey sorry for not replying to you earlier, tests are a complex subject, but we are trying to improve - in fact,  I think @GantMan could know something more about this issue.

**Comment by hrkeni** [comment]
@kelset @GantMan Thanks for the reply. I managed to work around this issue, though I am still not sure what changed.

So in my action creator, changing the way I get my navigation action from:
`AppNavigator.router.getActionForPathAndParams('OtherScreen')`

to 
`NavigationActions.navigate({routeName: 'OtherScreen'})`

did the trick. This could just entail a documentation update to because I had initially just followed direction there. If it's just that, then I can update the documentation, or even write up some documentation or examples for writing tests.

**Comment by kelset** [comment]
Gotcha. Yeah surely feel free to submit PRs for docs, those are always welcome :)

**Comment by rochapablo** [comment]
+1

**Comment by rcosteira79** [comment]
Having the same problem. I'm already using NavigationActions to set the navigation action, so that's not a solution for me :/

**Comment by hrkeni** [comment]
@rcosteira79 try using jest.mock() to mock the specific navigator(s) you're using

**Comment by marcin-chudy** [comment]
For me something like this did the trick:
```
jest.mock('../../AppNavigator/AppNavigator', () => ({
    AppNavigator: {
        router: {
            getStateForAction: jest.fn(),
            getActionForPathAndParams: jest.fn()
        }
    }
}));
```

**Comment by kelset** [comment]
Thanks for your snippet @marcin-chudy - I personally don't use Jest so I have only one question about it. Is it like, a workaround or more of a "hacky" way to solve this? Could it be worth to add to the docs/FAQ/a section about testing with Jest?

**Comment by rcosteira79** [comment]
Had to go with @marcin-chudy's solution.

**Comment by brentvatne** [comment]
please re-create issue with a minimal example to reproduce the problem, thanks!
