### ISSUE TITLE
TouchableOpacity not working for android inside navigationOptions

### ISSUE THREAD

**Issue by chrisverra** [react-navigation/react-navigation#2866]
### Current Behavior
I want to add a button to the header (right side). I use a touchable opacity so it can trigger a download action onPress.

This works fine on iOS, on Android however, it does not.
- if i replace the conditional image with just an image, it works on iOS, but not on Android
- When I just return a Button or Image etc, It does show something on headerRight's position (this works on both platforms)
### Code:
```

const shareButton = (props) => (
    <TouchableOpacity
        onPress={() => {
            const url = `file://${strings.pdfPath}`;
            const {month, year} = props.navigation.state.params;
            const invoiceTitle = `Factuur_${moment(month, 'M').format('MMMM')}_${year}`;

            const shareOptions = {
                title: invoiceTitle,
                message: `${invoiceTitle} in bijlage`,
                url: url,
                type: 'application/pdf',
                subject: invoiceTitle, // email subject
                excludedActivityTypes: [
                    'com.apple.UIKit.activity.PostToFacebook'
                ]
            };
            if (Platform.OS !== 'ios') {
                RNFS.readFile(
                    url,
                    'base64'
                ).then(pdfData => {
                    Share.open({
                        ...shareOptions,
                        url: 'data:application/pdf;base64,' +
                        pdfData
                    }).catch(e => {
                        // eslint-disable-next-line
                        console.log('Share error: ', e);
                    });
                });
                return;
            }

            Share.open(shareOptions).catch(e => {
                // eslint-disable-next-line
                console.log('Share error: ', e);
            });
        }}
        style={styleGuide.navButtonRight}
    >
        <Image
            style={styleGuide.navButtonImage}
            source={
                Platform.OS === 'ios'
                    ? require('../images/share_ios.png')
                    : require('../images/share_android.png')
            }
        />
    </TouchableOpacity>
);

type InvoiceFileProps = {
    invoiceFile: IInvoiceFile,
    loginState: LoginState
}

const mapStateToProps = (state) => ({
    invoiceFile: state.invoiceFile.invoiceFile,
    loginState: state.login
});

class InvoiceFile extends Component {
    props: InvoiceFileProps;

    static navigationOptions = (props) => ({
        headerTitleStyle: {
            ...styleGuide.headerStyle
        },
        headerTintColor: styleGuide.primaryColor,
        headerRight: shareButton(props)
    });

    static PDF_PATH = strings.pdfPath;

    state = {
        isPdfDownload: false,
        isFailedDownload: false
    };

    errorMessage = '';

    componentWillMount () {
        if (this.props.invoiceFile.example) {
            this.seeInvoiceFile(this.props.invoiceFile.pdf);
        } else {
            this.seeInvoiceFile(this.props.invoiceFile.pdf);
        }
    }

    seeInvoiceFile (url: string) {
        RNFS.downloadFile({
            fromUrl: url,
            toFile: InvoiceFile.PDF_PATH,
            headers: {
                'Authorization': 'Bearer ' + this.props.loginState.token
            }
        }).promise.then((res) => {
            if (res.statusCode === 200) {
                this.setState({isPdfDownload: true});
            } else {
                this.onError();
            }
        }).catch(() => {
            this.onError();
        });
    }

    onError () {
        this.errorMessage = 'Er is iets mis gegaan met het ophalen van de factuur. Probeer het nog een keer';
        this.setState({isFailedDownload: true});
    }

    componentWillUnmount () {
        this.setState({isPdfDownload: false});
        RNFS.unlink(InvoiceFile.PDF_PATH);
    }

    render () {
        return (
            <View style={styleGuide.scene}>

                <ErrorMessage message={this.errorMessage}/>

                {this.state.isPdfDownload ? (
                    <View style={styles.pdf}>
                    { Platform.OS === 'ios' ? (
                        <WebView source={{uri: InvoiceFile.PDF_PATH}} style={styles.pdf} scalesPageToFit={true} />
                    ) : (

                        <PDFView
                             path={InvoiceFile.PDF_PATH}
                             style={styles.pdf}/>
                    )}
                    </View>
                ) : (
                    <LoadingView blocking={true} show={!this.errorMessage}/>
                )}
            </View>
        );
    }
}

const styles = StyleSheet.create({
    pdf: {
        flex: 1,
    }
});

export default connect(mapStateToProps)(InvoiceFile);

```

### Screenshot iOS
https://imgur.com/a/IMbFv
### Screenshot Android
https://imgur.com/a/BDTGK

### Expected Behavior
- touchable opacity with a share image in the top right corner

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |1.0.0-beta.13
| react-native     | 0.48.1
| node             |8.2.1
| npm       |5.4.2

**Comment by kelset** [comment]
1. Have you considered using an icon instead of an image? I think it's something related to its styling tbh.
1. have you tried updating to newer versions of the lib? Does it still happen? (but tbh atm you should try with `beta.15`, there are some issues with `beta.16`

**Comment by chrisverra** [comment]
Thank you for your reply.

beta.15 does not change anything. 

I am new to RN, what styling issues should I be looking for?

Also, When i inspect the header in React Native Debugger, 
I do see the touchable opacity and an image, within the Animated Component key='right_scene...

**Comment by kelset** [comment]
> I am new to RN, what styling issues should I be looking for?

Things like Image size (height & width) and like, resize mode. You'll probably need to mess around with [those settings](https://facebook.github.io/react-native/docs/image.html).
If you try with the iOS image does that still happen?

Anyway these are [the icons](https://github.com/oblador/react-native-vector-icons) I was referring to.

**Comment by jqn** [comment]
I'm experiencing a similar issue where I overlay a badge icon on top  a tab. I use the badge icon to add special handling of the notification when the badge icon is pressed. After upgrading to beta.16 the onPress stop working.

![screen shot 2017-11-16 at 2 51 22 pm](https://user-images.githubusercontent.com/9710893/32918077-63f4cea0-cade-11e7-9571-a5637c408e11.png)

**Comment by brentvatne** [comment]
please repost with an example that we can run on https://snack.expo.io or that we can clone from github. thanks for this report, look forward to investigating it when we have an example!

**Comment by pauldcollins** [comment]
Did anyone ever work this out? I'm also experiencing the same issue.

**Comment by jlewicki-nevo** [comment]
I'm running into this issue as well.  Maybe it should be reopened?

**Comment by maitrungduc1410** [comment]
For those who's having this issue. It seems like on Android the TouchableOpacity doesn't have a real `height` (I mean it actual height is 0) so when we click, nothing happens. So we need to make a `height` property. For example:
```
headerRight: (
        <TouchableOpacity onPress = {() => alert('This is a button!')}>
            <View style={{ alignItems: "center", justifyContent: "center", height: 40 }}>
              <Icon
                name="ios-search"
                color="white"
                size={28}
              />
            </View>
        </TouchableOpacity>
      )
```

It works like a charm for me.

**Comment by qasimmehdi** [comment]
I was having the same problem but I was using `navigation.setOptions` in a `useEffect` with `isFocused` condition to set headerRight and the code changes were not useable until I navigated to a different screen and came back.

### Code:
```js
useEffect(() => {
    if (isFocused) {
      props.navigation.setOptions({
        headerRight: () => (
          <TouchableOpacity
            onPress={() => {
              navigation.navigate('TradeBot');
              console.log('object');
            }}>
            <FontAwesome5
              name={'robot'}
              size={25}
              color={COLOR.WHITE}
              style={{
                paddingRight: 5,
                display: 'flex',
                justifyContent: 'center',
              }}
            />
          </TouchableOpacity>
        ),
      });
    }
```

### Library version:
"@react-navigation/bottom-tabs": "^5.10.2",
"@react-navigation/drawer": "^5.10.6",
"@react-navigation/material-top-tabs": "^5.3.10",
"@react-navigation/native": "^5.0.9",
"@react-navigation/stack": "^5.1.1",
