### ISSUE TITLE
Increase hitSlop and pressRetentionOffset for navbar buttons

### ISSUE THREAD

**Issue by ide** [react-navigation/react-navigation#287]
The nav bar buttons are more difficult to touch compared to iOS's, and the "press retention offset" is also less generous (while continuing to touch the screen, move your finger away and back). We should identify what these values roughly are on iOS and set them here too.

**Comment by grabbou** [comment]
Will include that in my header refactoring unless someone else picks this up today or tomorrow.

**Comment by ericvicenti** [comment]
Thanks for filing this @ide, this is definitely a recent regression that I've noticed as well. @grabbou, thanks for taking care of this in your header fixup!

**Comment by kelset** [comment]
Pinging OP @ide since this issue is quite old and related to an old version of the lib. If no answer I'll close in 7 days.

**Comment by ide** [comment]
Last time I used React Navigation a couple months ago this wasn't fixed and I made the changes to the header buttons myself. It's the kind of thing that isn't visual but improves the experience.

**Comment by kelset** [comment]
Got it.
Then we can keep this open, thanks for letting me know. :)

**Comment by sunkibaek** [comment]
Has this been resolved? 

![simulator screen shot - iphone x - 2018-03-05 at 12 13 05](https://user-images.githubusercontent.com/1668601/36955968-ee48832c-206e-11e8-96f6-2fbd09410641.png)

I can see the buttons in navbar areas are pretty well occupying the empty spaces.

**Comment by brentvatne** [comment]
I haven't had time to check on this yet, will soon

**Comment by grabbou** [comment]
Let's see :) Added on my list, might attempt today or tomorrow!

**Comment by summerkiflain** [comment]
1+ for a way to change hitslop for BottomTabNavigator navbar buttons.
