### ISSUE TITLE
Reset convenience functions

### ISSUE THREAD

**Issue by tmaly1980** [react-navigation/react-navigation#2897]
It would be great if there were a way to have convenience functions for reset() as part of this.props.navigation . It's cumbersome to always have to import NavigationActions as well as create the action (which could take multiple lines) for such a common/basic/simple task! I'd imagine people do it often. It would be great to have:
`
this.props.navigation.reset(routeName, params)`

rather than:

```
import { NavigationActions } from 'react-navigation'
const resetAction = NavigationActions.reset({ index: 0, actions: [ 
    NavigationActions.navigate({ routeName: routeName, params }) 
] })
this.props.navigation.dispatch(resetAction)
```

I do it often, especially when I have several top-level screens. I shouldn't have to mess around with data structures to do a simple and common navigation task.

This has been my number 1 biggest complaint with this navigation library.

It would be great if there were an easier way to define the new stack, as well, I shouldn't have to define indexes and what not - I should be able to just pass one or more routeName+params, ie:

this.props.navigation.reset([ { routeName: routeName1, params: params1 }, { routeName: routeName2, params: params2 } ])

Why make it any more complicated than that for something we do so often in an app? It doesn't require changing things under the hood, but for goodness sake, make it easier on the developer and convert these simpler data structures to something more usable behind the scenes.

This might help when working with tabbed apps where I need to switch to a subscreen on a different tab.

**Comment by kelset** [comment]
Well, reset is a part of this library which has many issues; thanks for your suggestion.
That said, feel free to provide a Pull Request with this implementation if you can, we'll review it asap.

**Comment by googya** [comment]
There is a solution for version 1.0.0-beta.12 

```javascript
  render() {
    return (
      <RootNavigator
        ref={(c) => this.appNavigatorInstance = c }
        navigation={addNavigationHelpers({
          dispatch: this.props.dispatch,
          state: this.props.nav,
          back: this.handleBack.bind(this),
          reset: this.handleReset.bind(this),
        })}
      />
    )
  }

  handleReset(routes) {
    let params = [routes];
    if (isArray(routes)) {
      params = [...routes];
    }
    this._handleResetTo(params);
  }

  _handleResetTo = (routes) => {
    const { navigation } = this.appNavigatorInstance.props;
    const resetAction = NavigationActions.reset({
      index: (routes.length - 1),
      actions: routes.map(routeName => NavigationActions.navigate({ routeName }))
    });
    navigation.dispatch(resetAction);
  };

```

but it does not work behind version version 1.0.0-beta.12

**Comment by janpo** [comment]
@googya Maybe like this -> https://reactnavigation.org/docs/navigators/stack#Navigator-Props

**Comment by googya** [comment]
@janpo yes, that is a workable way of passing props

**Comment by brentvatne** [comment]
please re-post to https://react-navigation.canny.io/feature-requests if this is important for you. re-organizing issues to focus on bug reports here and feature requests on canny. thanks!
