### ISSUE TITLE
NavigationActions for screens nested inside StackNavigator causing duplicate screen render

### ISSUE THREAD

**Issue by PatNeedham** [react-navigation/react-navigation#2904]
I am trying to implement some sort of deep linking functionality, but from a push notification, using React Navigation along with [react-native-fcm](https://github.com/evollu/react-native-fcm).

The navigation structure of app is set up like this:
top root level `StackNavigator` with:

 - Home screen
 - Login screen
 - Users screen

Users screen is a `DrawerNavigator` with two drawers

 - Drawer 1 (a StackNavigator with 3 nested screens)
 - Drawer 2 (regular screen)

Here is the code for all of those navigational screens and components:

```
    var style = {width, height, alignItems: 'center', justifyContent: 'center'}
    
    class HomeScreen extends Component {
      componentDidMount() {
        const { navigate, dispatch } = this.props.navigation;
        setTimeout(() => {
          var potentialAction = this.props.screenProps.getCorrectScreenTransition()
          if (potentialAction) {
            dispatch(potentialAction)
          }
        }, 100)
      }
      render() {
        var {navigate} = this.props.navigation
        return (
          <View style={style}>
            <Text>HomeScreen</Text>
            <TouchableHighlight onClick={() => {
                navigate('AppDrawer')
              }}>
              <Text>Go to DrawerNavigator</Text>
            </TouchableHighlight>
          </View>
        )
      }
    }
    
    class Drawer1Screen1Screen extends Component {
      render() {
        var {navigate} = this.props.navigation
        return (
          <View style={style}>
            <TouchableHighlight onClick={() => {
                navigate('Drawer1Screen2')
              }}>
              <Text>Go to Screen 2</Text>
            </TouchableHighlight>
          </View>
        )
      }
    }
    
    class Drawer1Screen2Screen extends Component {
      render() {
        var {navigate} = this.props.navigation
        return (
          <View style={style}>
            <TouchableHighlight onClick={() => {
                navigate('Drawer1Screen3')
              }}>
              <Text>Go to Screen 3</Text>
            </TouchableHighlight>
          </View>
        )
      }
    }
    
    class Drawer1Screen3Screen extends Component {
      render() {
        var {navigate} = this.props.navigation
        return (
          <View style={style}>
            <Text>on screen three</Text>
          </View>
        )
      }
    }
    
    const Drawer1Screen = StackNavigator({
      Drawer1Screen1: {screen: Drawer1Screen1Screen, path: 'screen-1'},
      Drawer1Screen2: {screen: Drawer1Screen2Screen, path: 'screen-2'},
      Drawer1Screen3: {screen: Drawer1Screen3Screen, path: 'screen-3'}
    })
    
    class Drawer2Screen extends Component {
      render() {
        return (
          <View style={style}>
            <Text>Only a screen, not a nested stack navigator</Text>
          </View>
        )
      }
    }
    
    const UserNavigator = DrawerNavigator({
      Drawer1: {screen: Drawer1Screen, path: 'drawer-1' },
      Drawer2: {screen: Drawer2Screen, path: 'drawer-2' }
    })
    
    class LoginScreen extends Component {
      render() {
        return (
          <View style={style}>
            <Text>LoginScreen</Text>
          </View>
        )
      }
    }
    
    const DeepLinkFromPushNotification = StackNavigator({
      Home: { screen: HomeScreen },
      Users: { screen: UserNavigator, path: 'users' },
      Login: { screen: LoginScreen, path: 'login' }
    }, {mode: "modal"});


The remainder of my `App.js` class looks like this:

    const initialState = DeepLinkFromPushNotification.router.getStateForAction(DeepLinkFromPushNotification.router.getActionForPathAndParams('Home'))
    const navReducer = (state = initialState, action) => {
      const nextState = DeepLinkFromPushNotification.router.getStateForAction(action, state)
    
      // Simply return the original `state` if `nextState` is null or undefined.
      return nextState || state
    }
    
    const appReducer = combineReducers({
      nav: navReducer
    })
    
    class App extends Component {
      constructor(props) {
        super(props)
        this.state = {
          deepLink: false
        }
      }
      componentDidMount() {
        setTimeout(() => {
          if (Platform.OS === 'ios') {
            FCM.requestPermissions().then(() => {
              // accepted
            }).catch(() => {
              // rejected push notification permission
            });
          }
        }, 250);
        FCM.getInitialNotification().then(notif => {
          if (notif && notif.payload && notif.payload.openURL) {
            this.setState({deepLink: notif.payload.openURL, deepLinkPayload: notif.payload})
          } else {
            var data = { foo: 'bar' }
            console.warn("scheduling it now!!")
            FCM.scheduleLocalNotification({
              fire_date: new Date().getTime() + 8000,
              id: "UNIQ_ID_STRING",
              body: "This is a local push notification!",
              payload: {
                openURL: "users/drawer-1/screen-1/screen-2/screen-3",
                data: data
              },
              show_in_foreground: true
            })
          }
        })
        FCM.on(FCMEvent.Notification, async (notif) => {
          if (Platform.OS ==='ios') {
            switch(notif._notificationType){
              case NotificationType.Remote:
                notif.finish(RemoteNotificationResult.NewData) //other types available: RemoteNotificationResult.NewData, RemoteNotificationResult.ResultFailed
                break;
              case NotificationType.NotificationResponse:
                notif.finish();
                break;
              case NotificationType.WillPresent:
                notif.finish(WillPresentNotificationResult.All) //other types available: WillPresentNotificationResult.None
                break;
            }
          }
        })
      }
      render() {
        var {deepLink} = this.state
        var sampleScreenProp1 = 'sampleScreenProp1'
        var sampleScreenProp2 = 'sampleScreenProp2'
        return (
          <DeepLinkFromPushNotification
            uriPrefix={prefix}
            screenProps={{
              sampleScreenProp1,
              sampleScreenProp2,
              getCorrectScreenTransition: () => {
                if (deepLink) {
                  return NavigationActions.navigate({
                    routeName: 'Users',
                    action: NavigationActions.navigate({
                      routeName: 'Drawer1',
                      action: NavigationActions.navigate({
                        routeName: 'Drawer1Screen2',
                      })
                    })
                  })
                } else {
                  // not from a deep link
                }
              }
            }} />
        )
      }
    }
    
    const mapStateToProps = (state) => ({
      nav: state.nav
    })
    
    const AppWithNavigationState = connect(mapStateToProps)(App)
    
    const store = createStore(appReducer);
    
    class Root extends React.Component {
      render() {
        return (
          <Provider store={store}>
            <AppWithNavigationState />
          </Provider>
        );
      }
    }
    
    export default Root
```

### Current Behavior

When the app first opens, a local push notification is scheduled to fire in 8 seconds. I put the app in the background, see the push, then swipe close the app, open the push and get redirected the expected screen. But swiping left to right once makes the same screen appear again, as if one was nested on top of the other, when that shouldn't be the case.

To further demonstrate this irregularity, replacing the return action within `getCorrectScreenTransition` with:

```
    return NavigationActions.navigate({
      routeName: 'Users',
      action: NavigationActions.navigate({
        routeName: 'Drawer1',
        action: NavigationActions.navigate({
          routeName: 'Drawer1Screen2',
          action: NavigationActions.navigate({
            routeName: 'Drawer1Screen3',
          })
        })
      })
    })
```

Makes three of the same screens (all Drawer1Screen3 instances) appear on top of each other, instead of Screen 1 -> Screen 2 -> Screen 3 inside the drawer.

### Expected Behavior

For the first case I mentioned (before _To further demonstrate this irregularity_), I expect the nested screens in the `StackNavigator` to be Screen 1 -> Screen 2, instead of Screen 2 -> Screen 2. I uploaded [a video here](https://vimeo.com/241305605) demonstrating what happens with 3 screens inside the `StackNavigator`.

I believe this is a problem with the [NavigationActions navigate](https://github.com/react-community/react-navigation/blob/master/src/NavigationActions.js#L40) implementation, but I haven't been able to pinpoint the cause yet.

### My Environment

| software         | version
| ---------------- | -------
| react-navigation | ^1.0.0-beta.19
| react-native     |  react-native-cli: 2.0.1 , react-native: 0.50.0
| node             | v8.6.0
| npm or yarn      | 5.5.1

### Steps to reproduce

```
$ react-native init DeepLinkFromPushNotification && cd DeepLinkFromPushNotification/
$ npm install react-native-fcm --save
$ npm install
$ react-native link react-native-fcm
[Only targeting on iOS for now]
$ cd ios && pod init
```

Added pod 'FirebaseMessaging' to ios/Podfile within “target 'DeepLinkParamsMissing' do” block right after existing “# Pods for DeepLinkParamsMissing” comment

```
$ pod install
```

[ got error message saying “[!] The target `DeepLinkParamsMissing-tvOSTests` is declared twice.” So I removed lines 23 to 35 end of file, starting with “target 'DeepLinkParamsMissing-tvOS' do” and ending with the “end” keyword ]

```
$ pod install
```

[ Followed the Shared steps instructions (https://github.com/evollu/react-native-fcm#shared-steps) making specified edits to AppDelegate.h and AppDelegate.m, and added “Push Notifications” and “Background Modes > Remote notifications” capabilities ]

```
$ npm install --save react-redux redux react-navigation
```
I also made a sample repo with that contains all the configurations mentioned [located here](https://github.com/PatNeedham/DeepLinkFromPushNotification). To get it running from that I you you'll just need to run `npm install` from the root directory and `pod install` from the `ios/` folder.

**Comment by kelset** [comment]
Thanks for reporting, we'll take a look at it asap.

**Comment by PatNeedham** [comment]
@kelset I don't exactly how related this is, but I looked into another issue (#1477) similar in the sense that for the deep link to a nested screen, pressing the back button showed that same nested screen duplicated.

**Comment by kelset** [comment]
hey @PatNeedham thanks for the hint, yeah they are probably somewhat related. It looks like something "overall" buggy with deep linking.

**Comment by davepack** [comment]
Hey @PatNeedham, for the second case, the action you want would be the result of this code:
```js
NavigationActions.navigate({
  routeName: 'Users',
  action: NavigationActions.reset({
    index: 2,
    actions: [
      NavigationActions.navigate({
        routeName: 'Drawer1Screen1',
      }),
      NavigationActions.navigate({
        routeName: 'Drawer1Screen2',
      }),
      NavigationActions.navigate({
        routeName: 'Drawer1Screen3',
      }),
    ],
  }),
});
```

For the first case, are you wanting the uri `users/drawer-1/screen-1/screen-2/screen-3` to accomplish the same thing?

**Comment by davepack** [comment]
Also, I didn't see your link to the other issue until just now. You were on the right track in your comment. The problem with `users/drawer-1/screen-1/screen-2/screen-3` is that any part of the path that is followed by a `/` has to match to a navigator component. So when it is matching the path and it hits `screen-1/...` it does not find a matching path because it can only match `screen-1`, with no following `/`. I can see why it was written this way if you think of how routing on the web works. But since this is mobile app navigation, I think it makes sense to allow deep linking to a screen that is more than one route deep on a stack.

Ideally, `getActionForPathAndParams` would return the action above for that uri. So the ideal behavior is to nest a `navigate` action for each match with a navigator, then nest a `reset` action with an array of `navigate` actions for each normal component. This will presumably fix the back button problem and the duplicate screens on the stack.

**Comment by PatNeedham** [comment]
@davepack that was perfect, thank you! Using `NavigationActions.reset` instead of another nested `NavigationActions.navigate` as the action did the trick.

**Comment by gabrielfrischer** [comment]
I like turtles
