### ISSUE TITLE
TypeError: [native code] in forEach

### ISSUE THREAD

**Issue by onrige** [react-navigation/react-navigation#2924]
First sorry if this issue will be not with your contribution guidelines but I can't reproduce my problem for now and write it here with `Actual` and `Expected` behaviors.

I am using RNRF for now what is based on your library, Expo and Sentry for catching exceptions on production, and sometimes I see exceptions with your stacktrace. 

```
TypeError: undefined is not an object (evaluating 't._component.setNativeProps')

This error is located at:
    in n
    in RCTView
    in t
    in r
    in withCachedChildNavigation(r)
    in Unknown
    in t
    in a
    in t
    in RCTView
    in RCTView
    in RCTView
    in n
    in t
    in n
    in RCTView
    in RCTView
    in t
    in RCTView
    in n
    in r
    in Unknown
    in t
    in a
    in t
    in RCTView
    in RCTView
    in RCTView
    in n
    in t
    in n
    in RCTView
    in RCTView
    in t
    in RCTView
    in n
    in r
    in Unknown
    in t
    in a
    in t
    in P
    in RCTView
    in m
    in r
    in r
    in t
    in n
    in RCTView
    in RCTView
    in t
```  
<img width="804" alt="screen shot 2017-11-07 at 15 43 34" src="https://user-images.githubusercontent.com/14055801/32494439-582e3680-c3ca-11e7-83b4-e8c46a945cc7.png">

Maybe you could help me to find the problem or catch this one on simulator?

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.19
| react-native     | 0.49 (Expo version https://github.com/expo/react-native/archive/sdk-22.0.1.tar.gz)
| node             | v8.7.0
| yarn      | 1.1.0

**Comment by kelset** [comment]
Hi @onrige.
I am a bit confused, why you think the issue is caused by this lib? In the stack trace you posted is the `Animated` sub-library of `react-native` that is responsible for the crash.
Moreover, you say you are using `RNRF` and `Expo`. What makes you think that it is caused by `react-navigation`?

**Comment by onrige** [comment]
Hey @kelset. Because only in your package I found this module `withCachedChildNavigation` that figure in stack trace. I guess Animated is the place where app is crashing when navigator is animating for example but I can be wrong.

**Comment by kelset** [comment]
Uhm really weird. Thanks for reporting anyway, we'll take a look at it.

Btw have you tried older versions of the lib? ex. `beta.15`?

**Comment by onrige** [comment]
Nope, unfortunately I didn't have such opportunity because of RNRF. The main problem for me with this bug because I can't reproduce it on simulator. Btw I see this error on Android.

**Comment by noskurt** [comment]
Hi @onrige, are your remember how can you fix this problem?

**Comment by onrige** [comment]
@noskurt Hi, unfortunately not, I still have this bug

**Comment by brentvatne** [comment]
if you can create a reproducible example of this on the latest version of react-navigation and create a new issue i'd be happy to investigate

**Comment by dimlksin2** [comment]
phone_model: Urban
android_version: 7.0

com.facebook.react.common.JavascriptException: TypeError: TypeError: TypeError: Invalid attempt to destructure non-iterable instance

This error is located at:
    in t
    in t
    in RCTView
    in RCTView
    in RCTView
    in n
    in t
    in n
    in RCTView
    in RCTView
    in t
    in i
    in RCTView
    in t
    in n
    in n
    in r
    in n
    in t
    in RCTView
    in RCTView
    in t
    in RCTView
    in RCTView
    in t
    in n
    in n
    in n
    in RCTView
    in RCTView
    in t
    in t
    in r
    in Connect(r)
    in RCTView
    in t
    in Connect(t)
    in t
    in Connect(t)
    in o
    in Connect(o)
    in n
    in t
    in t
    in o
    in RCTView
    in RCTView
    in t

This error is located at:
    in n
    in t
    in RCTView
    in RCTView
    in t
    in RCTView
    in RCTView
    in t
    in n
    in n
    in n
    in RCTView
    in RCTView
    in t
    in t
    in r
    in Connect(r)
    in RCTView
    in t
    in Connect(t)
    in t
    in Connect(t)
    in o
    in Connect(o)
    in n
    in t
    in t
    in o
    in RCTView
    in RCTView
    in t

This error is located at:
    in n
    in RCTView
    in RCTView
    in t
    in t
    in r
    in Connect(r)
    in RCTView
    in t
    in Connect(t)
    in t
    in Connect(t)
    in o
    in Connect(o)
    in n
    in t
    in t
    in o
    in RCTView
    in RCTView
    in t, stack:
<unknown>@11:5685
value@1490:4869
f@41:42083
beginWork@41:45676
o@41:64674
a@41:65053
T@41:68561
y@41:67997
v@41:67834
batchedUpdates@41:72172
Ie@41:14848
ze@41:15343
receiveTouches@41:16180
value@18:3582
<unknown>@18:1067
value@18:3009
value@18:1039

	at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:54)
	at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:38)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:836)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
	at android.os.Looper.loop(Looper.java:203)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
	at java.lang.Thread.run(Thread.java:761)
