### ISSUE TITLE
Retrieving route params on back navigation

### ISSUE THREAD

**Issue by lorenzsell** [react-navigation/react-navigation#2932]
I'm storing params in the route on each navigation action on a stack navigator using redux.  It looks like this:

```
case SELECT_USER:
      nextState = AppNavigator.router.getStateForAction(NavigationActions.navigate({ routeName: 'UserProfile', params: { username: action.payload } }), state);
      break;
```

The user is able to navigate many layers deep and thus browse through many user profiles.  As the user goes back through the stack, I need to retrieve the param for that particular route level using this.props.navigation.state.params.  I'm finding, though, that react navigation is just returning the same params to me at each level on the way back, and not the ones that we set at that level.

The navigation reducer state tree indicates that the right params are being saved with each route, but on retrieval, I just get the first ones over and over.  Is this a bug or am I missing something?  Is there a more elegant pattern for saving route data for back navigation?

I just update to react navigation v1.0.0-beta.19 and this is still an issue.

**Comment by lorenzsell** [comment]
@kelset - I see you tagged this question as needs more info.  Can you suggest what additional information I should provide?  Thank you.

**Comment by brentvatne** [comment]
this is reasonable. you can use `navigate` with a supplied `key` of the route you're going back to and pass params that way while going back at the same time. we need to document this and perhaps come up with a better solution. I made an issue on our docs repo to cover this
