### ISSUE TITLE
add ability to set drawerLockMode for each screen in a drawerNavigator

### ISSUE THREAD

**Issue by rborn** [react-navigation/react-navigation#2939]
### Current Behavior
- On iOS the `navigationOptions: { drawerLockMode: 'locked-closed' }` doesn't seem to really work.

The code is replicated form a real app, and the drawer is nested inside another StackNavigator because there is a login screen that shows on app start (removed for simplicity).

Please find attached a small video with the issue and the code (not pretty but it's a quick hack 😄 ).

https://www.dropbox.com/s/mevidd0gvp9dx1t/drawerIssue.mov?dl=0

### Expected Behavior
- Basically the correct behaviour with this setting on would be that only the first screen in the StackNavigator to show the drawer, the subsequent not to have it and the swipe back to return to the previous screen.

Thank you!

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.19
| react-native     | 0.50.3
| node             | 8.3.0
| npm or yarn      | yarn 1.3.2

~~~

import React, { Component } from 'react';
import { Platform, StyleSheet, Text, View, TouchableOpacity } from 'react-native';
import { DrawerNavigator, StackNavigator } from 'react-navigation';

const DrawerMenu = () => {
    return <View style={{ backgroundColor: 'red' }} />;
};

const One = props => {
    const { navigate } = props.navigation;
    return (
        <View style={styles.container}>
            <TouchableOpacity
                style={styles.button}
                onPress={() => {
                    navigate('Two');
                }}
            >
                <Text>One</Text>
            </TouchableOpacity>
        </View>
    );
};

const Two = props => {
    const { navigate } = props.navigation;
    return (
        <View style={styles.container}>
            <Text>Two</Text>
        </View>
    );
};

class Main extends Component {
    render() {
        const Navigator = createInnerStackNavigator();
        return <Navigator />;
    }
}

const createStackNavigator = () =>
    StackNavigator(
        {
            Drawer: {
                screen: Drawer,
                navigationOptions: {
                    gesturesEnabled: false
                }
            }
        },
        {
            headerMode: 'none',
            mode: 'modal',
            initialRouteName: 'Drawer'
        }
    );

const Drawer = DrawerNavigator(
    {
        Main: {
            screen: Main
        }
    },
    {
        drawerWidth: 300,
        initialRouteName: 'Main',
        contentComponent: DrawerMenu,
        headerMode: 'none',
        navigationOptions: {
            headerMode: 'float'
        },
        contentOptions: {
            itemsContainerForceInset: { horizontal: 'never', top: 'always' },
            activeTintColor: '#e91e63'
        }
    }
);

const createInnerStackNavigator = () =>
    StackNavigator(
        {
            One: {
                screen: One,

                navigationOptions: { drawerLockMode: 'unlocked', key: 'one' }
            },
            Two: {
                screen: Two,
                navigationOptions: { drawerLockMode: 'locked-closed' }
            }
        },
        {
            headerMode: 'float'
        }
    );
const InnerStackNavigator = createInnerStackNavigator();

const styles = StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#F5FCFF'
    },
    welcome: {
        fontSize: 20,
        textAlign: 'center',
        margin: 10
    },
    instructions: {
        textAlign: 'center',
        color: '#333333',
        marginBottom: 5
    }
});

export default class App extends Component {
    render() {
        const Navigator = createStackNavigator();
        return <Navigator />;
    }
}

~~~

**Comment by vonovak** [comment]
Quick answer - you're setting the drawerLockMode on the StackNavigator, but you should set it on the  DrawerNavigator.

**Comment by rborn** [comment]
@vonovak I think you're right. Any quick idea how to do this when navigating in the InnerStackNavigator from One to Two (and back of course) ? Thank you :)

**Comment by vonovak** [comment]
@rborn in your Drawer you have

```
const Drawer = DrawerNavigator(
    {
        Main: {
            screen: Main
        }
    },
    {
        drawerWidth: 300,
        initialRouteName: 'Main',
        contentComponent: DrawerMenu,
        headerMode: 'none',
        navigationOptions: {
            // put the settings here
        },
    }
);
```

So putting the settings where I indicated should work

**Comment by rborn** [comment]
@vonovak yes, that I managed to do. My problem is how I enable/disable it based on the InnerStackNavigator screens. The idea is that when I'm in the root of the InnerStackNavigator to have the drawer active, but when I'm in a deeper level than the root, the drawer to be disabled, so the user cannot open it by swiping back instead of going to a previous route.

Makes sense? Thanks!

**Comment by dharakhatri88** [comment]
I am running into same issue. Need drawer active in root only not in inner screens. Anyone has an idea?

**Comment by rborn** [comment]
I am testing with react-native-drawer-layout but this brings a new set of issues :(

**Comment by vonovak** [comment]
@rborn I don't think there is a good way to do this now, since the Drawer is reused across all screens in a drawer navigator. You'd have to find a way to re-render the drawer view with new props.

**Comment by nikolal** [comment]
Any news about this?

**Comment by brentvatne** [comment]
please re-post to https://react-navigation.canny.io/feature-requests if this is important for you. re-organizing issues to focus on bug reports here and feature requests on canny. thanks!

**Comment by jamonholmgren** [comment]
Just in case someone is looking to figure out why their `drawerLockMode` is being ignored and Google leads them here, this issue helped me fix the problem.

https://github.com/react-navigation/react-navigation/issues/1082#issuecomment-411080810

```js
const Drawer = createDrawerNavigator({
    Drawer: SomeScreen,
},
    {
        drawerLockMode: 'locked-closed'
    }
);
```
