### ISSUE TITLE
setParams blurs currently focused TextInput in screen

### ISSUE THREAD

**Issue by CptMaumau** [react-navigation/react-navigation#2940]
While I am typing in a TextInput which is part of my screen and not the header, I use setParams to update a button in the header.

### Current Behavior
- TextInput is blurred after typing one letter  

### Expected Behavior
- TextInput is not blurred

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | beta.19
| react-native     | 0.49.3

**Comment by kelset** [comment]
Thanks for reporting, this is quite weird.

Some followup questions:
1. does it happen only on Android/iOS?
1. does it happen on both Debug and Release modes?
1. does it happen with Debugger On or Off? Both?
1. Can you provide a repo or a snack to reproduce this issue?

**Comment by CptMaumau** [comment]
1. Both
2. Both
3. Both
4. I can't provide a repo but an extra info, the TextInput is a password input

**Comment by bunea** [comment]
are you using a Tab Navigator by any chance?

**Comment by vonovak** [comment]
1 . my guess is that the `setParams` causes your screen to re-render and the textInput somehow loses focus
2 . calling `setParams` in every `onChangeText` seems kind of weird to me

**Comment by carsonwah** [comment]
If @vonovak 's guess is right, maybe you can try using redux. Just use a component that subscribed to redux change, instead of changing it manually.

```
static navigationOptions = {
  headerRight: <SomeReduxComponent/>
}

onChangeText() {
  // Send change to redux
}
```

**Comment by CptMaumau** [comment]
Thank you I will look into this option

**Comment by baldurpan** [comment]
Similar thing happened to me but I was just using redux. Turned out that multiple components were updating at the same time which was interfering with my TextInput.

**Comment by richgilbank** [comment]
For anyone currently encountering this, upgrade to `2.0.1` or greater, which seems to resolve this. 
Snack: https://snack.expo.io/By4wG7zkm
(on `2.0.0-rc.7` the TextInput loses focus on change, but by switching to `2.0.1`, the focus is retained).
