### ISSUE TITLE
issue of  android hardware back button 

### ISSUE THREAD

**Issue by mc-tracker** [react-navigation/react-navigation#2952]
### Preparation
```
const B = tabNavigator ({
         E:{screen:E} ,
         F:{screen:F},
})
const A = stackNavigator({
         C:{screen:C},
         D:{screen:D},
         B::{screen:B}
},{
     initialRouteName:C
})
```
### Reproduce steps
1、open App,  C is rendered now
2、navigate to B and initial tab is E
3、navigate to F
4、navigate to D
5、click back button of android，noting happened
6、click back button of android
### Current Behavior
Go back works after clicked twice, and current screen is tab E of B
### Expected Behavior
Go back after clicked once and current screen should be tab F of B
### Your Environment
| software         | version
| ---------------- | -------
| react-navigation |1.0.0-beta.19
| react-native     |0.49.3
| node             |8.1.3
| npm |4.6.1

**Comment by kelset** [comment]
Thanks for reporting.

Is it somewhat related to https://github.com/react-community/react-navigation/issues/2549?

**Comment by mc-tracker** [comment]
@kelset  I don't think so. #2549 used goback of navigation for go back but mine is hardware back button of android device

**Comment by jinxac** [comment]
@mc-tracker are u adding `eventListeners` to some component in between? I was facing same issue while working with hardwarePress eventListeners.

**Comment by mc-tracker** [comment]
@jinxac FYI, I'm only binding listener in root component.

**Comment by brentvatne** [comment]
this should be resolved. if it is not working as expected still on the latest version, please create a new issue with a runnable example on https://snack.expo.io -- thanks!
