### ISSUE TITLE
TabNavigator lazy={true} not works as expected on Android

### ISSUE THREAD

**Issue by Ilario17** [react-navigation/react-navigation#2961]
### Current Behavior
I have a TabBar with three tabs, each tab has a right button in its navigation bar. When I open the app the Tab1 is rendered, then if I tap on Tab3 the `componentDidMount()` in Tab2 is called also. In `componentDidMount()` of each tab, I set `onPress()` of the right button. 
Rendering Tab2 and Tab3 in the same time creates a conflict in `onPress()` of the right buttons, practically if I tap on Tab3, then tap on Tab2, the `onPress()` of the right button in Tab2 call the function in Tab3.

### Expected Behavior
With lazy={true} the tab should be rendered when the tab become active for the first time.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0
| react-native     | 0.49.3
| node             | 8.6.0
| npm or yarn      | npm 5.3.0

**Comment by rambabusaravanan** [comment]
Yes, for me too ..

> **Environment:**
>   OS: Linux 4.4
>   Node: 8.1.2
>   Yarn: 1.3.2
>   npm: 4.6.1
>   Watchman: Not Found
>   Xcode: N/A
>   Android Studio: Not Found
> 
> **Packages: (wanted => installed)**
>   react: 16.0.0 => 16.0.0
>   react-native: ^0.50.3 => 0.50.3

**Comment by spencercarli** [comment]
I think the issue here is that, on Android, `animationEnabled ` is true therefore when you go from Tab 1 to Tab 3 you'll be going through Tab 2 while animating, thus mounting the component.

If you set `animationEnabled` to false does this alleviate the problem?

I'm not sure that there's any way around this when using that (seemingly common) pattern on Android. I think you'll just have to disable `animationEnabled`.

**Comment by rambabusaravanan** [comment]
Thanks for the information.
I'll try with `animationEnabled: false` ..

**Comment by Ilario17** [comment]
No, `animationEnabled={false}` not works, I already tried that.

**Comment by douglasjunior** [comment]
I think that bad decisions have been made https://github.com/react-community/react-navigation/pull/3064

**Comment by Donhv** [comment]
pls help me fix this issue

**Comment by satya164** [comment]
Closing since `lazy` option has been dropped.

**Comment by fumer79** [comment]
why remove lazy option.Any other replacement?

**Comment by Donhv** [comment]
@satya164  have any idea for replace lazy ?

**Comment by alainib** [comment]
same question, is this bad ? ( why to remove it so) 

i found another way, but much code with redux store. 
tell me if you want the code ( reducer / action + 10lines to put inside each "tab" of tabnavigator )

**Comment by gairon** [comment]
@alainib share code here, pls.
Could your solution be wrapped in HOC to make it reusable?

**Comment by alainib** [comment]
@gairon what is HOC please ?

@wwpeng520  this is how i make it , maybe not the best / good solution, tell me :) 
EDIT : sorry don't have time to make a clear exemple, the following code may contain some useless lines

----------

`yourprojectname/package.json `

	{  "name": "yourprojectname",
		"dependencies": {
			"react": "^16.2.0",
			"react-native": "^0.52.0",
			"react-navigation": "^1.0.0-beta.26",
			"react-redux": "^5.0.6",
			"redux": "^3.7.2",
			"redux-logger": "^3.0.6",
			"redux-persist": "^5.4.0",
			"seamless-immutable": "^7.1.2"
		},
	}

----------
`yourprojectname/src/redux/actions/index.js`
	
	/*
		//you can do multi export all the actions from her
		export * from "./language_actions";
	*/
	export * from "./tabname_actions";

----------
`yourprojectname/src/redux/actions/tabname.js`


	import { TAB_NAME } from "yourprojectname/src/redux/actions/types";
	// to use this action call this.props.action_changeTabName(newTabName); 
	export const action_changeTabName = tabname => {
	  return {
		payload: tabname,
		type: TAB_NAME
	  };
	};
	// if you need another action 
	/*
		export const action_doSomething = tabname => {
		  return {
			payload: tabname,
			type: "SOMETHING"
		  };
		};
	*/

----------
`yourprojectname/src/redux/actions/types.js`
 
	/*
		// in this file create constant to avoid typo when passing parameter
		export const CHANGE_LANGUAGE = "CHANGE_LANGUAGE";
	*/
	export const TAB_NAME = "TAB_NAME";
	
----------
`yourprojectname/src/redux/reducers/index.js`

	// import language from "./language_reducer";
	import tabname from "./tabname_reducer.js";

	export default {	 
	  // language,	  
	  tabname
	}; 

 
---------- 
`yourprojectname/src/redux/reducers/tabname_reducer.js`

	import { TAB_NAME } from "yourprojectname/src/redux/actions/types";
	export default function (state = null , action) {
	  switch (action.type) {
		case TAB_NAME:
		  return action.payload;
		default:
		  return state;
	  }
	}

	
	

----------
`yourprojectname/src/redux/store/index.js`

	import { createStore, compose, applyMiddleware } from 'redux';
	import { persistStore, persistCombineReducers } from 'redux-persist';
	import storage from 'redux-persist/lib/storage';
	import { createLogger } from 'redux-logger';
	import rootReducers from "yourprojectname/src/redux/reducers";

	const config = { key: 'root', storage };
	const middleware = [];

	const reducers = persistCombineReducers(config, rootReducers);
	const enhancers = [applyMiddleware(...middleware)];
	const initialState = {};
	const persistConfig = { enhancers };
	const store = createStore(reducers, undefined, compose(...enhancers));
	const persistor = persistStore(store, persistConfig, () => {
	  // console.log(store.getState());
	});
	const configureStore = () => {
	  return { persistor, store };
	}

	export default configureStore;

----------

In each tab i want to use this lazy loading : 

`yourprojectname/src/tab/tab1.js`

	import * as actions from "yourprojectname/src/redux/actions";
	import { connect } from "react-redux";
	 
	const tabname = "TAB1";
	var self; // cannot use this inside of static navigationOptions so need this "dirty hack"
	  

	class Tab1 extends React.PureComponent {

	  static navigationOptions = ({ navigation }) => {
		return {
		  tabBarIcon: ({ tintColor }) => <Icon name="pagelines" size={22} color={tintColor} />,
		  tabBarOnPress: (tab, jumpToIndex) => {
			navigation.navigate(tabname);
			self.props.action_changeTabName(tabname);
		  }
		};
	  };

	  constructor (props) {
		super(props);
		self = this;
		this.state = {
		  dataIsLoading: false,
		  data: [],      
		};
	  }	
	  
	  componentWillReceiveProps(nextProps) {
		if (tabname == nextProps.tabname) {
		  this.setState({dataIsLoading:true});
		  ... load your data her 	  
		}
	  }
	} 

	function mapToStateProps(data) {
	  // extract the tabname from data returned by redux 
	  return {   
		tabname: data.tabname
	  };
	}
	// inject action , will be available in component with this.props.actionname();
	export default connect(mapToStateProps, actions)(Tab1);
	  
	

`yourprojectname/src/tab/tab2.js`

	import * as actions from "yourprojectname/src/redux/actions";
	import { connect } from "react-redux";
	 
 
	const tabname = "TAB2";
	var self; // cannot use this inside of static navigationOptions so need this "dirty hack"
	  

	class Tab2 extends React.PureComponent {

	  static navigationOptions = ({ navigation }) => {
		return {
		  tabBarIcon: ({ tintColor }) => <Icon name="pagelines" size={22} color={tintColor} />,
		  tabBarOnPress: (tab, jumpToIndex) => {
			navigation.navigate(tabname);
			self.props.action_changeTabName(tabname);
		  }
		};
	  };

	  constructor (props) {
		super(props);
		self = this;
		this.state = {
		  dataIsLoading: false,
		  data: [],      
		};
	  }	
	  
	  componentWillReceiveProps(nextProps) {
		if (tabname == nextProps.tabname) {
		  this.setState({dataIsLoading:true});
		  ... load your data her 	  
		}
	  }
	} 

	function mapToStateProps(data) {
	  // extract the tabname from data returned by redux 
	  return {   
		tabname: data.tabname
	  };
	}
	// inject action , will be available in component with this.props.actionname();
	export default connect(mapToStateProps, actions)(Tab2);
	  
		


	
----------
This is my app.js, i'm not sure you need to edit your but in case of 

	`yourprojectname/src/App.js`

	import { Provider } from "react-redux";
	import { PersistGate } from 'redux-persist/es/integration/react';
	import Home from "yourprojectname/src/tab/Home";
	import Tab1 from "yourprojectname/src/tab/tab1";
	import Tab2 from "yourprojectname/src/tab/tab2";

	import configureStore from "yourprojectname/src/redux/store";
	const { persistor, store } = configureStore();

	const MyTabView = TabNavigator(
	  {
		Home: { screen: Home },
		Tab1: { screen: Tab1 },
		Tab2: { screen: Tab2 }     
	  },
	  {
		swipeEnabled: false,
		initialRouteName: "Home",
		tabBarPosition: "bottom",
		tabBarOptions: {
		  activeTintColor: "green",
		  pressColor: "green",
		  inactiveTintColor: "#373738",
		  showIcon: true,
		  showLabel: false,
		  style: { backgroundColor: "green" }
		}
	  }
	);


	import * as actions from "yourprojectname/src/redux/actions";
	export default class App extends React.PureComponent {
	  constructor (props) {
		super(props);
		this.state = { ...store.getState() };
		
		store.subscribe(() => {
		  const storestate = store.getState();
		  // force le changement de langue dans I18 en remettant la dernière valeur sauvegardée
		  if (storestate.language != null) {
			I18n.locale = storestate.language;
		  }
		});
	  }

	  render() {
		return (
		  <Provider store={store}>
			  <View style={{ flex: 1 }}>
				<MyTabView />
			  </View>         
		  </Provider>
		);
	  }
	}

**Comment by brentvatne** [comment]
`lazy` is enabled by default and released in react-navigation 1.1.2
