### ISSUE TITLE
Snapshot test for react navigator failing

### ISSUE THREAD

**Issue by jayeszee** [react-navigation/react-navigation#2994]
### Current Behavior
Hi guys, I recently upgraded react-navigation from beta 9 to beta 15 but it looks like the jest snapshot that my local environment generates is different from what circle ci generates. Mine seems add an extra undefined to the top level style prop.

![image](https://user-images.githubusercontent.com/10326244/32975513-c083304c-cbbc-11e7-9dc9-53ae0d23b12d.png)

On circle, it doesn't have the extra param.
![image](https://user-images.githubusercontent.com/10326244/32975552-4040b192-cbbd-11e7-85c3-f7947b9d6762.png)

### Expected Behavior
- expecting circle and my environment to generate the same snapshot.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | beta 15
| react-native        |    49.5
| node                    |        8.6
| npm or yarn        |        1.0.1

circle env:
node: 8.5
yarn: 1.0.2

**Comment by kelset** [comment]
Hi thanks for reporting.

1. Is it related to https://github.com/react-community/react-navigation/issues/2820 ?
1. can you try with newer versions of the lib? We have worked a lot on Jest & Flow implementation so it may be fixed. Moreover we are going to release a new version very soon, so maybe if `beta.19` still has this issue for you maybe try pointing at master.

**Comment by jayeszee** [comment]
@kelset I don't think so but I'll look into it more. It seems like its just a matter of the container adding an extra undefined in the styles array in the local environment compared to circle which doesn't.  I've rewritten the test a bit to bypass this issue (since it really is a mount test anyways)
