### ISSUE TITLE
unexpected getStateForAction value in nested navigators.

### ISSUE THREAD

**Issue by shubhnik** [react-navigation/react-navigation#3009]
### Current Behavior
I have this navigation structure:
```javascript
export const Tabs = TabNavigator({
  feed: {
    screen: Feed
  },
  logout: {
    screen: Logout
  }
});

const AppNavigator = StackNavigator({
  login: {
    screen: Login
  },
  screen1: {
    screen: Screen1
  },
  screen2: {
    screen: Tabs,
    navigationOptions: {
      gestureEnabled: false
    }
  }
});
```
* Now If I do this:
```javascript
AppNavigator.router.getStateForAction(AppNavigator.router.getActionForPathAndParams(
  "screen2"
))
```
I will get the output(state) as:
```js
{"index":0,"routes":[{"routeName":"screen2","key":"Init-id-1511202869081-1"}]}
```
* But If I do this:
```js
AppNavigator.router.getStateForAction(AppNavigator.router.getActionForPathAndParams(
  "screen2"
), 
  AppNavigator.router.getStateForAction(
    AppNavigator.router.getActionForPathAndParams('login')
  )
)
```
I will get the output state as:
```js
{
	"index": 1,
	"routes": [
		{
			"routeName": "login",
			"key": "Init-id-1511202855232-0"
		},
		{
			"routes": [
				{
					"key": "feed",
					"routeName": "feed"
				},
				{
					"key": "logout",
					"routeName": "logout"
				}
			],
			"index": 0,
			"key": "id-1511202855232-1",
			"routeName": "screen2"
		}
	]
}
```

### Expected Behavior
* I was expecting this behavior:
```javascript
AppNavigator.router.getStateForAction(AppNavigator.router.getActionForPathAndParams(
  "screen2"
))
```
should return this:
```js
{
	"index": 0,
	"routes": [
		{
			"routes": [
				{
					"key": "feed",
					"routeName": "feed"
				},
				{
					"key": "logout",
					"routeName": "logout"
				}
			],
			"index": 0,
			"key": "id-1511202855232-1",
			"routeName": "screen2"
		}
	]
}
```
Is the current behavior happening right or is it some bug?
### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^1.0.0-beta.15
| react-native     | 0.49.3
| node             | 7.1.0
| npm or yarn      | 4.2.0

**Comment by kelset** [comment]
Uhm does it happen with newer versions of the lib?

Moreover, is it related to https://github.com/react-community/react-navigation/issues/2622? If so, can you please close this in favor of that?

**Comment by shubhnik** [comment]
@kelset I think these two are different issues. I have doubts specifically regarding getStateForAction().

One doubt, what will `getStateForAction(action)` return if the action doesn't define any route? let's say if the action is `{"type":"persist/PERSIST"}`, should it return `null` or what?

**Comment by kelset** [comment]
Quick update: this getStateForAction may be solved via:
* https://github.com/react-community/react-navigation/pull/1515
or
* https://github.com/react-community/react-navigation/pull/1888

Can you please let me know if that's the case via a comment in the PR that fixes it?

**Comment by brentvatne** [comment]
hi there! if this is still a bug can you create a new issue that reproduces the bug on https://snack.expo.io? thanks!
