### ISSUE TITLE
Navigators are undefined when importing "react-navigation"

### ISSUE THREAD

**Issue by Connorelsea** [react-navigation/react-navigation#3014]
### Current Behavior

TabNavigator (and other navigators) are undefined when using `require("react-navigation").TabNavigator` and `import { TabNavigator } from "react-navigation`.

I am using react-everywhere which is based on a create-react-app setup.

![image](https://user-images.githubusercontent.com/1844458/33044981-c12b0dd4-ce10-11e7-95ab-8a494e1dc607.png)

![image](https://user-images.githubusercontent.com/1844458/33044987-c7425aba-ce10-11e7-9ad8-29ab5dac67f9.png)

### Expected Behavior

TabNavigator should be defined when using `require("react-navigation").TabNavigator` and `import { TabNavigator } from "react-navigation`

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^1.0.0-beta.19
| react-native     | 0.50.3
| node             | 8.0.0
| npm or yarn      | 0.24.6

Babel Plugin Versions: 

![image](https://user-images.githubusercontent.com/1844458/33044884-526e0112-ce10-11e7-996f-7cef74f44a34.png)

![image](https://user-images.githubusercontent.com/1844458/33044914-6fd68daa-ce10-11e7-9fbf-996d12fe1f98.png)

Error Display: 
![image](https://user-images.githubusercontent.com/1844458/33044965-ae93b1e4-ce10-11e7-8d60-0d898204d925.png)

**Comment by kelset** [comment]
Looks like you misconfigured Webpack.
This is 99% not caused by the library.

**Comment by Connorelsea** [comment]
I'm unsure why react-navigation would be undefined (as well as some of its children) but certain children would not be defined, because of a webpack configuration. I am just using a fairly standard CRA config
