### ISSUE TITLE
Header interaction with screen component maybe don't work.

### ISSUE THREAD

**Issue by lucasleelz** [react-navigation/react-navigation#3018]
### Current Behavior
I follow the document `Header interaction with the screen component ` to write a custom method. However, this method is undefined in `navigation.state.params` when using reset to return to the current screen.
```
let headerRight = (
  <Button
    title="Save"
    onPress={params.handleSave ? params.handleSave : () => null}
   />
);

componentDidMount() {
  this.props.navigation.setParams({ handleSave: this._handleSave });
}

use reset

export default function resetTo(navigation, routeName) {
  const action = NavigationActions.reset({
    index: 0,
    actions: [NavigationActions.navigate({ routeName })],
  });
  return navigation.dispatch(action);
}

at routeName , this `handleSave` does not exist.
```

### Expected Behavior
Hope that after the reset, `navigation.state.params` there is this method.

### Example
**I simply wrote an [example](https://github.com/lucasleelz/ReactNavigationExample).
Only when reset, save button does not work.**

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  1.0.0-beta.19
| react-native     | 0.50.3
| node             | v7.5.0
| npm     | 5.5.1

**Comment by kelset** [comment]
Ping @Jacse who wrote that part of the doc. It looks weird that it doesn't get re-defined.

But it may be a bug related to reset. Can you also try to use the latest version of the lib?

**Comment by Jacse** [comment]
Could you provide some more code? I’d like to see the whole component - A repo would be ideal.

**Comment by lucasleelz** [comment]
@kelset Update to the latest version(`1.0.0-beta.21`) of the problem still exists.
@Jacse I simply wrote an [example](https://github.com/lucasleelz/ReactNavigationExample)

**Comment by jaisongreen** [comment]
version(`1.0.0-beta.28`) and have the exact same issue. Custom navigation bar buttons wont fire if I reset the navigation stack.

**Comment by brentvatne** [comment]
I had to reorder this a bit to get the same behavior you wanted on react-navigation@2.0, but can't reproduce it in this case: https://snack.expo.io/r14LUwR6M

Also, not related to this issue but I would change the structure of your app so that you have:

```
StackNavigator (without header) -> Tabs -> Home -> Stack
                                                                       -> Profile -> Stack
```
