### ISSUE TITLE
Using a component as stack navigator title throws when navigating away

### ISSUE THREAD

**Issue by albertogasparin** [react-navigation/react-navigation#3043]
I've found out that when setting a component as `navigationOptions.title`, `react-navigation` tries to use it as a text for the back button of the next screen. Hoverer, if the component is not serializable, react will throw several errors like:

```sh
Malformed calls from JS: field sizes are different.
# and
TypeError: Converting circular structure to JSON
```

The code could be as dummy as:
```js
class Home extends Component {
  static navigationOptions = () => ({
    title: <Text>Title</Text>,
  });
}
```

The solution is setting `navigationOptions.headerBackTitle`, so explicitly providing a string to be used on the back button. However the error makes this simple fix hard to spot.

### Expected Behavior

I think `react-navigation` should check whenever `navigationOptions.title` is a `string`, and if not use the same `headerTruncatedBackTitle`default text. 

### Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.21
| react-native     | 0.50.3
| node             | 8.4.0

**Comment by kelset** [comment]
Does it happen also with [latest release](https://github.com/react-community/react-navigation/releases)?

**Comment by albertogasparin** [comment]
Yes it does, just updated now to `1.0.0-beta.21` (I've also updated the version on the issue)

**Comment by kelset** [comment]
Ok thanks for reporting, it looks like the proposed solution is a viable one.
We'll try to work on it asap.

**Comment by brentvatne** [comment]
this should be `headerTitle` and not `title`. but we need to warn better if people don't provide a string here.

**Comment by brentvatne** [comment]
see https://github.com/react-navigation/react-navigation/issues/4058
