### ISSUE TITLE
BackHandler not working TabNavigator to StackNavigator

### ISSUE THREAD

**Issue by MSSPL-PiyaleeMaiti** [react-navigation/react-navigation#3050]
BackHandler not working in StackNavigator nested with TabNavigator 
---

### Current Behavior
- In my app I use first StackNavigator then nested with TabNavigator. When I want to back from Tab to stack route page, with the help of hardware back in android, there BackHandler not working. Can't get any event of BackHandler. 
- Not use also  `backBehavior: 'none',`    option in tabNavigator configuration. 

### Expected Behavior
- I want to get any event or any solution so that I can back to previous page or any other action by backHandler.
- Suggest any solution.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^1.0.0-beta.15
| react-native     |  0.44
| node             |  v6.11.5
| npm or yarn      |  npm

**Comment by kelset** [comment]
1. you are using an old version of RN, of this lib, and node. Moreover, which version of npm are you using?
1. it's probably related to https://github.com/react-community/react-navigation/issues/2523
1. without the code of the two navigators it's really hard to understand how you set them up

**Comment by MSSPL-PiyaleeMaiti** [comment]
@kelset  Thanks for your response. 
1. my npm version is 3.10.10. Till now we can't upgrade RN version.
2. my route navigation structure is below:

```
AppNavigate = StackNavigator({
  Home: {
    screen: Home,
    navigationOptions: {
      header: null
    },
  },
  About: {
    screen: About,
    navigationOptions: {
      header: null,
    },
  },
  Chat: {
    screen: TabNavigator({
      Tab1: { screen: Tab1 },
      Tab2: { screen: Tab2 },
      Tab3: {
        screen: TabNavigator({
          TabInner1: { screen: TabInner1 },
          TabInner2: { screen: TabInner2 },
          TabInner3: { screen: TabInner3 },
        },{
          headerMode:'float',
          tabBarPosition: 'top',
          tabBarOptions:{
            showLabel: true,
            showIcon: false,
            style: {
              backgroundColor: '#ffffff',
            },
          }
        }),
      },
      Tab4: { screen: Tab4 },
      Tab5: { screen: Tab5 },
    },{
      tabBarPosition: 'bottom',
      tabBarOptions: {
        activeTintColor: 'red',
        showLabel: false,
        showIcon: true,
        iconStyle:{
          height:40,
          width:44
        },
        labelStyle: {
          fontSize: 12,
        },
        style: {
          backgroundColor: '#ffffff',
        },
      }
    }),
  },
});
  
```

And I setup BackHandler in Tab1 page like below:

```
componentDidMount() {
    BackHandler.addEventListener('hardwareBackPress', this._handleBackHandler);
  }

  componentWillUnmount() {
    BackHandler.removeEventListener('hardwareBackPress', this._handleBackHandler);
  }

 _handleBackHandler = () => {
   navigation.goBack(null);
    return true;
  }
```

Now tell me any suggestion to solve the problem.

**Comment by ibrahimcanbaz** [comment]
This worked for me you can try,
```
import { NavigationActions } from 'react-navigation'
...
...
this.props.navigation.dispatch(NavigationActions.back())
```

**Comment by MSSPL-PiyaleeMaiti** [comment]
@ibrahimcanbaz   Thanks for your suggestion.
In my project BackHandler event can't fire not a singlt time, if it fire then  
`navigation.goBack(null);`    this is working fine. I need solution how to    
`BackHandler.removeEventListener('hardwareBackPress', this._handleBackHandler);`    this code is working.

**Comment by MSSPL-PiyaleeMaiti** [comment]
Can anyone suggest any solution to the problem?? We are stuck still now with this issue.

**Comment by brentvatne** [comment]
this should be resolved in latest version. if not, please create a new issue with a runnable example on https://snack.expo.io -- thanks!

**Comment by theutkarshsoni** [comment]
@MSSPL-PiyaleeMaiti  Did you find any solution till now? If yes, please do share here.

**Comment by raajnadar** [comment]
@theutkarshsoni create a new issue with more info.
