### ISSUE TITLE
TabNavigator weird borders when backgroundColor is transparent (Android)

### ISSUE THREAD

**Issue by tbehunin** [react-navigation/react-navigation#3052]
### Current Behavior
- When setting `tabBarOptions.style.backgroundColor` to `rgba(0,0,0,0.3)`, the transparent look/feel works as expected, but there's this weird border that goes around it. The left/right sides looks like a very thin triangle (thinner at the top, wider at the bottom) and the top also has a border. Attempting to set the border in `style` doesn't seem to work.

### Expected Behavior
- There shouldn't be that weird triangular border on the left/right sides, or
- You should be able to override that border through configuration.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |1.0.0-beta.19
| react-native     |0.49.5
| node             | 8.1.3
| npm or yarn      | npm@5.4.2

![image](https://user-images.githubusercontent.com/796147/33289563-d7c31622-d374-11e7-8b7c-de6fd27ff021.png)

**Comment by kelset** [comment]
Hi @tbehunin, thanks for reporting.

It looks like you are not using the latest version of `react-navigation`, and I'm quite sure that with `beta.20` & `beta.21` we also updated the underlying library for tabs (`react-native-tab-view`). Can you please try upgrading and let me know if the issue persists?

**Comment by mohit-github** [comment]
Hi @kelset, I have updated to `react-navigation v1.0.0-beta.21` and `react-native-tab-view v0.0.70` but the issue still persists. I am using `react-native v0.48.0`.

**Comment by yooouuri** [comment]
I have the same issue, see #3141

**Comment by yooouuri** [comment]
@tbehunin see: https://github.com/react-community/react-navigation/blob/master/src/views/Header/Header.js#L359

When I add this to my `static navigationOptions`

```
headerStyle: {
      ...Platform.select({
        android: {
          shadowColor: 'transparent',
          shadowOpacity: 0,
          shadowRadius: 0,
          shadowOffset: {
            height: 0,
            width: 0,
          },
          elevation: 0,
        }
      }),
    },
```

My issue is now solved...

**Comment by tbehunin** [comment]
@yooouuri Excellent - I haven't tested your solution since I've since moved to using a custom component, but this may come in handy later down the road!

**Comment by satya164** [comment]
It's not a border, it's shadow. @yooouuri's fix should work for you.
