### ISSUE TITLE
Tabbar feature request

### ISSUE THREAD

**Issue by geroale** [react-navigation/react-navigation#3060]
Hi guys, I have developed my app in which I am controlling the different screens using the Stack navigator. In one of this, I have a Tab Navigator with my tabs and tabbar, but I want to show the tabbar also in other screens of the stack navigator, outside the Tab Navigator.

Those are the packages
https://reactnavigation.org/docs/navigators/stack
https://reactnavigation.org/docs/navigators/tab

This is the structure
Stack Navigator {
    Normal screen // show the tabbar
    Normal screen 2 // don't show the tabbar
    Tab Navigator { 
        Tab screen 1 // normal tabbar from tab navigator
         Tab screen 2 // normal tabbar from tab navigator
    }
}

The is a way to do it? Thanks for reading

**Comment by matthamil** [comment]
The `Normal screen` that shows the tab bar should be one of the available routes of either `Tab screen 1` or `Tab screen 2` to achieve this.

**Comment by geroale** [comment]
Hi @matthamil , thank you for the answer. Could you show an example on my code?

**Comment by matthamil** [comment]
@geroale Convert the `Normal screen` to a screen that the TabNavigator renders. The `Normal screen` should be a Stack Navigator.

Here's the idea with pseudocode:

```
MyStackNavigator {
  initialRoute: Component2,
  otherRoute: Component3
}

TabNavigator {
  Screen1: Component1,
  Screen2: MyStackNavigator
}
```

Hope this helps.

**Comment by geroale** [comment]
Yeah, @matthamil , this really helps! But how can I get the reference of the MyStackNavigator, which is inside the TabNavigator? Thank you again.

**Comment by matthamil** [comment]
What do you mean by "get the reference"? The StackNavigator will render like any other screen component, except now you have the added benefits of routing (pop/push) within that navigator as well.

**Comment by geroale** [comment]
@matthamil  The problem with this approach is that we need the reference to navigate between two tab navigator and stack navigator.
Something like that https://github.com/react-community/react-navigation/issues/1439

**Comment by brentvatne** [comment]
you can just use `navigate` for this, and make sure the route you're navigating to only exists on one of the routers and you're good
