### ISSUE TITLE
White line between tabs

### ISSUE THREAD

**Issue by goinnovative** [react-navigation/react-navigation#3061]
<img width="645" alt="bildschirmfoto 2017-12-01 um 01 38 14" src="https://user-images.githubusercontent.com/18541587/33462582-9bddc7c6-d638-11e7-899c-18ad21b5fcee.png">

### Code

```
const TabsNavigator = TabNavigator({
  Location:   { screen: Location },
  Coupon:     { screen: Coupon },
  Map:        { screen: Map },
  Hours:   { screen: Hours },
  Contact:    { screen: Contact },
}, {
  tabBarComponent: props => <TabBarBottom {...props} />,
  tabBarPosition: 'top',
  animationEnabled: false,
  swipeEnabled: false,
  tabBarOptions: {
    inactiveBackgroundColor: '#303033',
    activeBackgroundColor:  '#303033',
    showLabel: false,
    style: {
      height: 40,
      borderTopWidth: 0,
      backgroundColor:  '#303033',
    }
  },
});
```

### Current Behavior
On large screens (iPad Mini, iPhone 6 Plus) I get a thin white line between two tabs.

### Expected Behavior
No white line.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.13
| react-native     | 0.50.3

**Comment by kelset** [comment]
Thanks for reporting, but it looks like you are using a *really* old version of the library.
Can you please update to latest and let me know if it still happens?

**Comment by benoist** [comment]
I've got it with 1.0.0-beta.21 as well, it looks like it appears when the tabs are an uneven number. When I change my tabs to 4 it's gone

**Comment by satya164** [comment]
Probably a bug with React Native and subpixel positioning.

Can you change `inactiveBackgroundColor` and `activeBackgroundColor` to `transparent` and see if it still happens?

**Comment by brentvatne** [comment]
closing because inactive and better fit for https://github.com/react-native-community/react-native-tab-view

**Comment by ChelseaDan** [comment]
@satya164 I had the same issue, and your method worked. Thanks.
