### ISSUE TITLE
Flow-types of RouteConfig doesn't match its documentation.

### ISSUE THREAD

**Issue by blindbox** [react-navigation/react-navigation#3063]
### Current Behavior
- The problem lies in RouteConfig (StackNavigator's first param)
- RouteConfig properties doesn't explicitly accept `screen` as a property.
- I'm able to add additional properties to RouteConfig properties.

### Expected Behavior
- RouteConfig properties should accept `screen` as a property.
- RouteConfig properties should not accept additional properties.

### References
- `react-navigation 1.0.0-beta.21`, but the same bug is there on `master`
- https://github.com/react-community/react-navigation/blob/master/src/TypeDefinition.js line 269, specifically. `type NavigationRouteConfig`
- https://github.com/react-community/react-navigation/blob/master/src/navigators/StackNavigator.js line 28, specifically, the default export.
- https://reactnavigation.org/docs/navigators/stack#RouteConfigs

**Comment by kelset** [comment]
Thanks for reporting, our resident Flow expert is @Ashoat so he should know why it's set up that way (or @skevy).

**Comment by Ashoat** [comment]
@blindbox, you're totally right that this isn't typed correctly. Unfortunately, I don't have the time right now to look into fixing it. Would you be interested in making a PR?

**Comment by blindbox** [comment]
Sure, I'm a typescript user (never used Flow) but let's see if I could get a PR running today. Shouldn't be too hard.

**Comment by Ashoat** [comment]
Typescript and Flow are really similar, so hopefully there shouldn't be much of a learning curve.

> Shouldn't be too hard.
Famous last words... :)

Make sure the `examples/NavigationPlayground` directory (as well as the root directory) typecheck!

**Comment by blindbox** [comment]
Wow, this is difficult.

My current progress is that, I need to setup another system before I can tackle this. I'm getting Flow issues on Windows and I'm going to try this on a Mac/Linux + Nuclide and see if I could get rid of that. I know what to fix, but I can't really test it if Flow keeps giving me an unknown type even on a sanity test.

Even without the system issue, it is as you said, this is harder than it looks (a change of two lines in the TypeDefinition to fix this issue affects more than 10 files!).

**Comment by kelset** [comment]
Yeah it's really hard usually :(

Btw these steps @Ashoat wrote a while back may help you:

1. downgrade RN/React versions to match `react-navigation`'s versions
2. install `flow-bin` version corresponding to `react-navigation`'s
3. patch `.flowconfig` with https://github.com/facebook/react-native/pull/16816
4. `yarn add --dev jest`
5. `flow-typed install`
