### ISSUE TITLE
Export CardStackStyleInterpolator

### ISSUE THREAD

**Issue by satya164** [react-navigation/react-navigation#3086]
When customizing the transition animations with the `transitionConfig` option in `StackNavigator`, it's sometimes desirable to conditionally use a custom transition animation and use the default one when the conditions don't match.

Since `CardStackStyleInterpolator` has the default interpolations, exporting this will allow using the default interpolations when needed.

**Comment by superburrito** [comment]
@satya164 You mean as opposed to
```
import CardStackStyleInterpolator from 'react-navigation/src/views/CardStack/CardStackStyleInterpolator'
```
?

**Comment by brentvatne** [comment]
please re-post to https://react-navigation.canny.io/feature-requests if this is important for you. re-organizing issues to focus on bug reports here and feature requests on canny. thanks!

**Comment by ganmor** [comment]
import CardStackStyleInterpolator from "react-navigation/src/views/StackView/StackViewStyleInterpolator";

**Comment by huowenxuan** [comment]
For V2 
import StackViewStyleInterpolator from 'react-navigation/src/views/StackView/StackViewStyleInterpolator';

**Comment by gmaclennan** [comment]
From v2.12.0 this has been moved to `react-navigation-stack/dist/views/StackView/StackViewStyleInterpolator`

**Comment by pawansrijan** [comment]
For latest react-navigation 4.0.10 it is inside
import CardStackStyleInterpolator from 'react-navigation-stack/src/views/StackView/StackViewStyleInterpolator';

**Comment by quachsimon** [comment]
@pawansrijan where do you see that? I am in the [stack](https://github.com/react-navigation/stack) repo and can't find that file anymore.

**Comment by urolovshohruh** [comment]
Error: Unable to resolve module ./TransitionConfigs/CardStyleInterpolators from C:\Users\HP i5\Desktop\exmNative\newNative\node_modules\@react-navigation\stack\src\index.tsx:
