### ISSUE TITLE
Specifying regex in the path

### ISSUE THREAD

**Issue by jinxac** [react-navigation/react-navigation#3096]
### Current Behavior
In my application I have create a deep linking for activating users.

Here is how it works:-

1. User signs up
2. I take him to sign up successful screen showing please check your mail box.
3. He/She gets mail in his registered inbox with activation link
4. Once he/she clicks on activation link my backend either returns `https://mypage.com/auth/activation-error` or `https://mypage.com/auth/activation-success` which should open login screen in app.

Now in my config I need to check for both the links, so I was thinking if there is way to user regular expression for this. Here is my code:-
```
*/
  [ROUTE_CONSTANTS.LoginStart]: {
    screen: mapNavigationStateParamsToProps(Login),
    path : "https://mypage.com/auth/activation-error" ||  "https://mypage.com/auth/activation-success"
  },
*/
```

We have different environments and URL changes for each of the environment. On staging it is mypage.staging , on development it is mypage.dev.

So I think there should be way to specify regex in path somewhat like this:-

```
  [ROUTE_CONSTANTS.LoginStart]: {
    screen: mapNavigationStateParamsToProps(Login),
    path: /.*\/auth\/(activation-error|activation-success).*/
  },
```

### Expected Behavior
- Regular expressions should be allowed in path

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.21
| react-native     | 0.47.2
| node             | 8.1.2
| npm or yarn      | 5.1.3

**Comment by kelset** [comment]
Thanks for reporting, I think this subject was already side-talked here: https://github.com/react-community/react-navigation/issues/1455

Anyway, I'll tag this as a feature request.

**Comment by jinxac** [comment]
Thanks @kelset if its same issue we can close this and monitor that one.

**Comment by brentvatne** [comment]
please re-post to https://react-navigation.canny.io/feature-requests if this is important for you. re-organizing issues to focus on bug reports here and feature requests on canny. thanks!
