### ISSUE TITLE
SafeAreaView causes screen content jittering when first loading on devices other than iPhoneX

### ISSUE THREAD

**Issue by JaxGit** [react-navigation/react-navigation#3106]
### Current Behavior
- Try adding simple mock screens in TabNavigator
- When app first loaded (no matter debug/release scheme, simulator/real device) on iOS 6S, the mock screen content quickly jitters (from 88pt to 64pt)

### Expected Behavior
- No jitters on devices other than iPhoneX

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.21
| react-native     | 0.50.4
| node             | v6.9.1
| npm or yarn      | npm v4.0.3

**Comment by kelset** [comment]
Uhm that's weird; it doesn't happen to me.

A couple of issues that may have some extra information:
1. https://github.com/react-community/react-navigation/issues/3072
1. https://github.com/react-community/react-navigation/issues/3054
1. https://github.com/react-community/react-navigation/issues/3055

**Comment by brentvatne** [comment]
need video or some way to repro as I've never seen this

**Comment by Monte9** [comment]
I recently encountered this too.

@brentvatne let me know if this video helps: (.mp4 - link to GDrive)
https://drive.google.com/file/d/1umGLjZwOBgSZmS_WnZnemXNU0gwrQQzM/view?usp=sharing

**Comment by troublediehard** [comment]
@brentvatne can we reopen this? I have the same issue as @Monte9 video.

**Comment by satya164** [comment]
Please open a new issue with a repro

**Comment by Gra55h0pper** [comment]
I have the same issue also.

**Comment by lucidlive** [comment]
same here

**Comment by brentvatne** [comment]
please don't use safe area view from react-navigation. use react-native-safe-area-context instead
