### ISSUE TITLE
Tabnavigator tabs navigate function not working when I pass screenProps

### ISSUE THREAD

**Issue by chetankotkar** [react-navigation/react-navigation#3110]
### Current Behavior
```
const TabNav = TabNavigator({
  // config
});

<TabNav
  screenProps={/* this prop will get passed to the screen components as this.props.screenProps */}
/>
```

I have the above structure in one of the component. when I pass my data in screenprops it will get received by all tabs defined in TabNavigator along with navigation props. But when I try to navigate the navigation function is not working.
I logged this.props.navigation in onpress I got 

```
{ dispatch: [Function],
  state: { key: 'Today', routeName: 'Today' },
  goBack: [Function: goBack],
  navigate: [Function: navigate],
  setParams: [Function: setParams] }
```
But navigate function is not working 

### Expected Behavior
I want navigation to be working in this case.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.15 |
| react-native| 0.49.3    |

**Comment by kelset** [comment]
Thanks for reporting, I have a few questions:
1. have you tried updating to the latest release?
1. does it happen only on Android/iOS?
1. does it happen on both Debug and Release modes?
1. does it happen with Debugger On or Off? Both?
1. Can you provide a GIF or a repo or a snack to reproduce this issue?
1. What do you mean with
> But navigate function is not working

Which error does it throw?

   7. Can you share the code in which you are using the `navigate`?

**Comment by chetankotkar** [comment]
@kelset 
1. No, I ll update to letest release and check today
2. checked on Android , yet to check on ios
3. It happen in debug mode, yet to check in release mode.
4. Both
5. I have listview in each tab component, onclick of row navigate not working
6. I mean on press of row I have logged "`console.log(this.props.navigation);`"  I got the object 
   ```
 { dispatch: [Function],
  state: { key: 'Today', routeName: 'Today' },
  goBack: [Function: goBack],
  navigate: [Function: navigate],
  setParams: [Function: setParams] }
```
which we generally get in each route/component. But at this route (in tabnavigator component) `this.props.navigation.navigate("notification");`   not working. i.e. on pressing row it prints above navigation object but does not navigate to `notifications` screen.

**Comment by kelset** [comment]
5. if you don't share code it's really hard to help you because as you wrote in 6, you are not getting any error. So probably there is simply something misconfigured in your code.

Moreover, re-reading the first post, why do you think it is related to you passing `screenProps` to the navigator? If you don't pass that prop is it working fine?

**Comment by chetankotkar** [comment]
In Maincomponent.js

```
const Tabs = TabNavigator({
        Today: {
          screen:Today ,
          headerMode: 'none',
          navigationOptions: ({navigation}) => ({
            tabBarLabel: 'Today',
          })
        },
        Tomorrow: {
          screen: Tomorrow,
          headerMode:'none',
          navigationOptions: ({navigation}) => ({
            tabBarLabel: 'Tomorrow',
          })
        },

      },
      {
        tabBarOptions:{
          activeTintColor: '#ffffff',
          inactiveTintColor:'#ffffff',
          inactiveBackgroundColor: '#d3d3d3',
          activeBackgroundColor: '#d3d3d3',
          showLabel: true,
          showIcon: false,
          style: {
            backgroundColor: '#efefef',
            height:45,
            padding:0,
            margin:0,
            flexDirection:Platform.OS=="ios"?'row':'column',
          },
          labelStyle:{fontSize:10,padding:0,width:width/5,color:'#000000'},
          indicatorStyle:{
            backgroundColor:'transparent',
            height:0,
            borderBottomColor: '#294da1',
            borderBottomWidth: 2,
          }
        },
        swipeEnabled: true,
        animationEnabled: true,
        tabBarPosition: 'top',
        lazyLoad: true,
        headerMode: 'screen',
      });
```
  ```
return (
        <View style={styles.container} >
        {this.state.animating?(
          <Loader animating={this.state.animating}/>
        ):(
          <View style={{flex:1}}  >
            <View style={[styles.itemBlock, styles.itemDateBackground]}>
              <Text style={styles.itemDateHeadline}>
              Next To Jump
              </Text>
            </View>

            <ScrollView contentContainerStyle={styles.wrapper}
            horizontal={true}
            showsHorizontalScrollIndicator={false}
            automaticallyAdjustContentInsets={false}
            >
              {nexttojumpdata}
            </ScrollView>
            <View style={{width:width,height:height-280}}>
            <Tabs screenProps={this.state.meetings} />
          </View>
          </View>
        )}
        </View>
      )

```

Today.js and Tomorrow.js contain listview i.e. 

```
// render component
  render() {
          return (
          <ListView
              automaticallyAdjustContentInsets={false}
              removeClippedSubviews={false}
              dataSource={this.state.dataSource}
              renderRow={(rowData) => {return this.renderRow(rowData)}}
              enableEmptySections={true}
          />
        )
    }
```

renderRow function as below

renderRow(row) {
    //console.log("rwo :"+JSON.stringify(row));
    let aband = ''
    let country = null

    if(row.country) {
        country = row.country
    }

            if(row.raceList) {
           
                return (
                        <TouchableOpacity style={[styles.itemBlock, styles.blockBackground]} **onPress={() => this.props.navigation.navigate('MeetingScreen', {selectedTab: '', meetingid: row.MeetingId})}**>
                            <View>
                                <Text style={styles.itemHeadline}>
                                    <Image
                                        style={[styles.runner]}
                                    />
                                    <Text>
                                        {`${row.VenueName}`} {this.renderCountry(country)} {"\n"}
                                    </Text>
                                </Text>
                              </View>
                            <IconMat name="chevron-right" style={styles.chevi} />
                        </TouchableOpacity>
                )
            } else {
                return ( null )
            }
        
    // }
}

**Comment by kelset** [comment]
> If i dont pass the screenProps it ll throw exception navigate undefined.

Ok then this is a clue.
Maybe in the way you are setting up the datasource the reference gets "misconfigured"?

Can you try an using [NavigationAction](https://reactnavigation.org/docs/navigators/navigation-actions) instead?

**Comment by chetankotkar** [comment]
> Maybe in the way you are setting up the datasource the reference gets "misconfigured"? 

  I dont understand the relation between listview datasource and navigation props relation ?
  can you just brief ? how can the setting up datasource can misconfigure the reference ?

Any ways I ll try with [NavigationActions](https://reactnavigation.org/docs/navigators/navigation-actions) and check what happens ..

**Comment by carsonwah** [comment]
@chetankotkar Just a wild guess, have you done this.renderRow(rowData).bind(this) ?

**Comment by chetankotkar** [comment]
@carsonwah  yes .. I have tried all possible options. No navigation functions are working.

**Comment by nicholasess** [comment]
Hi everyone,
Is there someone solution for that?

**Comment by brentvatne** [comment]
can someone who would like to see this issue resolved please create a new issue with a reproducible example on https://snack.expo.io or in a github repository, with a minimal amount of superfluous code? (please don't post your entire app, just a small one to reproduce the problem). thanks!

**Comment by imjaad94** [comment]
### 

- [ ] 

- [ ]
