### ISSUE TITLE
Back gestures do not work when RTL is enabled

### ISSUE THREAD

**Issue by aeirola** [react-navigation/react-navigation#3127]
### Current Behavior
If react native is in RTL mode (`I18nManager.isRTL` is `true`), then react navigation back swipe gestures do not seem to work, from neither edge of the screen.

I've tested this by adding 

```
I18nManager.forceRTL(true);
```

at the top of [`App.js`](https://github.com/react-community/react-navigation/blob/master/examples/ReduxExample/App.js) in the ReduxExample of the repository.

Other navigation related components, such as transitions and header back button, seem to behave as expected.

### Expected Behavior
I expect the back gesture to work by swiping from the right side of the screen.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | `master`
| react-native     | 0.50.3
| node             | 8.9.1
| npm or yarn      | 0.27.5

**Comment by eriveltonelias** [comment]
Hi @aeirola! 
thanks for your PR, I'll close this.
