### ISSUE TITLE
Pass params from navigationOptions / Shared Screens

### ISSUE THREAD

**Issue by CptFabulouso** [react-navigation/react-navigation#3139]
### Current Behavior
The only way to pass custom params is passing them as _navigate_ option e.g. :
` this.props.navigation.navigate('screen', { someParam: 'someParam'}))`

### Expected Behavior
I would like to be able to pass them when I configure navigators, something like :
```
const navigator = StackNavigator({
	main: {
		screen: Main,
		params: { //pass some default params to the screen from here
			someParam: 'someParam'
		}
	},
})
```

The reason why is because I (commonly) have a shared screen between different routes and I show one thing differently based on the route, e.g. button "Create" or "Edit", so I would like to end up with this:

```
const navigator = StackNavigator({
	main: {
		screen: StackNavigator({
			someScreen: { screen: SomeScreen }
			sharedScreenMain: { 
				//same component as in "other" route, shows button "Create"
				screen: SharedScreen 
			} 

		})
	},
	other: {
		screen: StackNavigator({
			someOtherScreen: { screen: SomeOtherScreen }
			sharedScreenOther: { 
				//same component as in "main" route, shows button "Edit"
				screen: SharedScreen,
				params: { 
					// "Edit" button will be shown based on this param
					editing: true
				}
			 } 
		})
	},
})
```
Now I don't have to worry about passing the param in _navigation.navigate(..)_, the screen gets the prop (param) right from navigator no matter how I get to there (there will be much more screens in those stacks). 

This question also scratches a question about how to deal with shared screens which share 99% of content. I deal with it this way, because it has nicely defined navigation structure, I always know in which stack I am in and don't have to "leave" the stack to show the shared screen (drawback is code duplication). I am open for other suggestions (I didn't find any)

**Comment by kelset** [comment]
Uhm tbh the way I would approach would be to simply create some intermediate components.
Ex. 

```js
const navigator = StackNavigator({
	main: {
		screen: StackNavigator({
			someScreen: { screen: ScreenToShareCustom1 }
		})
	},
	other: {
		screen: StackNavigator({
			someScreen: { screen: ScreenToShareCustom2 }
		})
	},
})
```

where

```js

const ScreenToShare = ({options}) => {
	// does some stuff
}

const ScreenToShareCustom1 = () => {
	render () {
		< ScreenToShare options={ //custom stuff for 1} />
	}
}

const ScreenToShareCustom2 = () => {
	render () {
		< ScreenToShare options={ //custom stuff for 2} />
	}
}
```

or use Redux.

Anyway I'll keep this open as FR.

**Comment by CptFabulouso** [comment]
that's... a good approach, I like it. It also allows to extrapolate some functions (and logic) from ScreenToShare to ScreenToShareCustom1(2).
Thank you.

**Comment by lanten** [comment]
hi,
I got a similar question

```
Login: { screen: Login, navigationOptions: { title: '登录', test: 'ok' } },
```
I want to get `navigationOptions` (like `title` and `test`) in my screen

I can get this in custom navigation, but I can't get it in the screen

**Comment by brentvatne** [comment]
please re-post to https://react-navigation.canny.io/feature-requests if this is important for you. re-organizing issues to focus on bug reports here and feature requests on canny. thanks!
