### ISSUE TITLE
Add support for onLongPress events on tab bar tabs

### ISSUE THREAD

**Issue by jwrubel** [react-navigation/react-navigation#3147]
### Current Behavior
Hi! I wanted to be able to capture long press events on tabs, so I could take different actions when a tab was long-pressed. There is a `tabBarOnPress` handler but nothing specifically for long press.

### Expected Behavior
Similar to how the `tabBarOnPress` handler is supported in TabNavigator Screen Navigation Options, I'd like to see a `tabBarOnLongPress` handler, or possibly just detect the long press on the underlying component and bubble up `long` as a boolean property.

I implemented this functionality in a commit on my fork [here](https://github.com/kennenai/react-navigation/commit/a751d22dafbf0c77e96781e5054123032d2dc4db) - this just clones the existing `onPress` functions and handlers all the way up. I'm sure it could be more elegant, but it served my purpose. I'm happy to wrap this up as a PR to the main repo if you'd like.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.21
| react-native     | 0.50.4
| node             |  8.9.1
| npm or yarn      | yarn 1.3.2

**Comment by kelset** [comment]
> I'm happy to wrap this up as a PR to the main repo if you'd like.

Yeah sure that would be lovely.

**Comment by jwrubel** [comment]
Turns out that Android doesn't work without support for `onLongPress` in [`react-native-tab-view`](https://github.com/react-native-community/react-native-tab-view), since that library is used here. I'm going to try and get a PR in for that library, and submit a PR when that one's merged.

**Comment by brentvatne** [comment]
this is important, i agree 100%!

that said, if you'd like to keep this feature request tracked, please re-post to https://react-navigation.canny.io/feature-requests. re-organizing issues to focus on bug reports here and feature requests on canny. thanks!

**Comment by capella55** [comment]
Any updates here?

**Comment by brianw-tech** [comment]
Any updates on this?
