### ISSUE TITLE
Why tabBarIcon allows only square (x=y) icons? 

### ISSUE THREAD

**Issue by greenais** [react-navigation/react-navigation#3158]
According to docs tabBarIcon accepts: 
"React Element or a function that given { focused: boolean, tintColor: string } returns a React.Node, to display in tab bar"

I have component which provides rectangular (x>y) icon image, but in tabBar my icon is cutted horizontally like this:
[image](http://i68.tinypic.com/n5mp2v.jpg)

If this is hardcoded limitation - it probably should be documented?

**Comment by kelset** [comment]
TBH as far as I can tell, it's a good practice to have icons being squared / inside a squared image in order to prevent weird re-shaping with different screen resolutions/formats.

**Comment by greenais** [comment]
Yep, you are surely right, but in some (mine) cases there's need them rectangular, what then?
Again, if it is real limitation - that probably is better to document it, in order to avoid time wasting for people trying to "resolve" this.
If it's just opinated default - there should be a way to override it, IMHO.

**Comment by kelset** [comment]
> Yep, you are surely right, but in some (mine) cases there's need them rectangular, what then?

The only solution I can think is to modify the image to be a transparent square so that the icon will preserve the rectangular appearance.

> Again, if it is real limitation - that probably is better to document it, in order to avoid time wasting for people trying to "resolve" this.

PRs are always welcome.

> If it's just opinated default - there should be a way to override it, IMHO.

Again, open a PR that enables it and surely it can be discussed further.

**Comment by greenais** [comment]
> The only solution I can think is to modify the image to be a transparent square so that the icon will preserve the rectangular appearance.
It isn't solution at all as this way you will end up with unnecessary smaller icons of decreased height, wasting screen space in favor of still questionable square approach.
I'll look for solution and PR

**Comment by SoundBlaster** [comment]
@greenais try to add `iconStyle` to the `tabBarOptions` for your `TabNavigator`.

**Comment by SoundBlaster** [comment]
@greenais on Android used `TabBarTop` that contains a style:
```const styles = StyleSheet.create({
  icon: {
    height: 24,
    width: 24,
  },```
this style is used for render icon:
```<TabBarIcon
        position={position}
        navigation={navigation}
        activeTintColor={activeTintColor}
        inactiveTintColor={inactiveTintColor}
        renderIcon={renderIcon}
        scene={scene}
        style={[**styles.icon**, iconStyle]}
      />```
This is not a bug, but very bad feature.

**Comment by satya164** [comment]
Like @SoundBlaster said, you can use `iconStyle` to solve your use case.
