### ISSUE TITLE
Nesting StackNavigator inside TabRouter

### ISSUE THREAD

**Issue by prodigynelson** [react-navigation/react-navigation#3160]
Because I'm a masochist, the first time I'm using react native I am attempting to build a relatively complex social media app (note this is my first time so consequently I may be doing this completely wrong) that has the format as follows (pseudocode): 

    Stack Navigator: 
        Home: BottomTabNavigator
        CreatePostScreen: CreatePostScreen
        CreatePostScreen2: CreatePostScreen2, etc
(I have the "create post screens" at the highest level of the stack so that when you load that page, it doesn't show the tab bar for obvious reasons)

    BottomTabNavigator = TabNavigator:
        Homescreen: HomeTabRouter (TabRouter, see below)
        Explore: ExploreNavigator (stack navigator, works fine)
        Notifications: NotificationsNavigator (stack navigator, works fine)
        Profile: ProfileNavigator (stack navigator, works fine)

Here's where it starts to get complex (this is actual code, and I'll explain why I can't decide between tab navigator and tab router after)

    export const HomeTabNavigator = TabRouter({
        FriendsNavigator: {
            screen: FriendsNavigator,
            path: 'Friends',
            routeName: 'Friends',
        },
        LocalNavigator: {
            screen: LocalNavigator,       
            path: 'LocalScreen',
            routeName: 'LocalScreen'
        },

    }, 
    {
        headerMode: 'none',
    }
    )

    const CustomTabView = ({ router, navigation }) => {
        const { routes, index } = navigation.state;
        const ActiveScreen = router.getComponentForRouteName(routes[index].routeName);   
        return (
            <View style={{flex: 1}}>
            <ActiveScreen
                // navigation={navigation} (commented out because if it's not, 
                my app won't render anything and tell me there is no route defined
                for key "LocalNavigator" and this is because the ActiveScreen
                is a StackNavigator that isn't aware of the other StackNavigators
                even though I think it should be???)
            />
            </View>
        );
    };

    export default HomeTabRouter = createNavigationContainer(
        createNavigator(HomeTabNavigator)(CustomTabView)
    )

(this code comes before instantiation of HomeTabNavigator but for readability's sake I'm putting it after)

    export const FriendsNavigator = StackNavigator({
        FriendPostsScreen: {
            screen: FriendPostsScreen,
            path: 'Friends',
            routeName: 'Friends'
        },
        IndividualFriendPostPage: {
            screen: IndividualFriendPostPage,
            routeName: 'IndividualFriendPostPage'        
        }
    },    
    {
        headerMode: 'none',
    
    });
    (LocalNavigator is an exact copy of FriendsNavigator, just gives the option to 
    navigate between the screen of all posts and the screen of a specific post)

The issue I'm having with the tab router is that the code as it is either 

A. if navigation={navigation} for ActiveScreen is commented out, I can't navigate from the FriendPostsScreen to the LocalPostsScreen from a button declared on FriendPostsScreen even if I connect the class to the global navigation and navigate to the routename declared in that index (I'm aware I can construct the navigation buttons elsewhere, but until I changed HomeTabNavigator from being FriendsScreen to FriendsNavigator rendering the buttons in a SafeAreaView on the FriendsScreen worked fine) [screenshot when commented out][1]

B. if it's not commented out, it tells me "there is no key defined for route LocalNavigator" [screenshot][2]

I know that it's not an issue with the actual key/routename because I've tested it and passed every possible routename. 

I can't set the screen of "Homescreen" in the BottomTabNavigator to the non navigationContainer HomeTabNavigator because it tells me "I must declare a screen," and I don't know of any other way to use a tab router. 

Before I list my reasoning on using a tab navigator, I want to reiterate that the tab router setup with CustomTabView worked fine until I nested stacknavigators in it. 

BottomTabNavigator is obviously, already a Tab Navigator and I haven't figured out a way to only set navigationOptions: { tabBarVisible: false } for the nested tab navigator, not both, because I need to be able to customize the tab navigator bar of Friends/Local to include a button that links me to the CreatePostScreen a level above the original BottomTabNavigator. [screenshot][3]

I've done a decent amount of research and I'm pretty certain that the issue is one of two things: 
1. I don't fully understand how stack navigators work and I'm doing something wrong that makes it incompatible with TabRouter 
2. There is an inherent issue with nesting StackNavigators in a TabRouter.

Regardless of the issue, like I said in the beginning, I'm new to react native and react-navigation. Based on what I'm trying to accomplish with the nested navigators, am I going about it the right way? What do you recommend? 

I know it's long but I just didn't want to skip any details, so thanks for taking the time to read!

  [1]: https://prnt.sc/hpturk
  [2]: https://prnt.sc/hptuj2
  [3]: http://prntscr.com/hpty4w

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.19
| react-native     | 20.0.0

**Comment by kelset** [comment]
Hi @prodigynelson.

It's a bit weird the behaviour you are experiencing, but I feel it may be related in the way the tab navigator "loads" the screens.

1. can you try upgrading to latest version of the lib? (and, what do you mean with RN 20.0.0?)
1. can you try creating a snack that reproduces the issue you are explaining?
1. have you tried "removing" the custom tabnavigator and load directly the nested stacknav? I have a 50-50 feeling it may be simply something off with one of those Stack(s).
