### ISSUE TITLE
Ability to have side tab bar

### ISSUE THREAD

**Issue by chapeljuice** [react-navigation/react-navigation#3165]
The current tab bar has options to display it on the `top` or the `bottom` of the screen.

I'm requesting that the side of the screen also be an option so each tab is stacked vertically on top of one another and the group is stuck to the side of the screen (either `left` or `right`).

I also have a SO question out there in case this can already be done via custom code:
https://stackoverflow.com/questions/47874723/react-navigation-tab-bar-on-the-side

My current environment, just FYI:
```
    "react": "16.0.0-alpha.12",
    "react-native": "0.44.0",
    "react-navigation": "^1.0.0-beta.21",
```

**Comment by kodayashi** [comment]
Seen more common on iPad apps (e.g. Evernote)

**Comment by eduardojunio** [comment]
Since this library uses **react-native-tab-view** to show the tab bar, this feat should be implemented there first, so it can be implemented here. I'm developing a tablet app and I need this feature ASAP, so I'll be working on it in the next days.

**Comment by brentvatne** [comment]
please re-post to https://react-navigation.canny.io/feature-requests if this is important for you. re-organizing issues to focus on bug reports here and feature requests on canny. thanks!

**Comment by jpstrikesback** [comment]
hey @eduardojunio we'll be working on the same thing shortly (I think), specifically a side pane/tab that remains open to facilitate tablet nav and more, like placing a profile or detail view in a sidepane)

Did you manage to get something like that off of the ground in your fork?

Obrigado!
JP

**Comment by donni106** [comment]
Hi @jpstrikesback, how did it go with your navigation and remaining open side pane? I also want to do a "navigation left/details right" screen and wonder how to start.

**Comment by jpstrikesback** [comment]
Hey @donni106 here is what we are doing currently:

https://github.com/react-navigation/rfcs/issues/39#issuecomment-399583164
