### ISSUE TITLE
RN <SafeArea> and safe view

### ISSUE THREAD

**Issue by theohdv** [react-navigation/react-navigation#3173]
Same problem as #2991 so I created a new issue (was closed because he did not follow the issue template).

### Current Behavior
When using React Native 0.50 `<SafeArea>` component and React Navigation safe view. Those two components doesn't fit well together. Here a screenshot (additional 44 padding added):

![simulator screen shot - iPhone x - 2017-12-22 at 10 45 25](https://user-images.githubusercontent.com/26060802/34293510-48860b32-e705-11e7-9654-63a426c124ca.png)

### Expected Behavior
I don't really know which should be the expected behavior. As React native support this now is it the role of react navigation to do that?

And maybe an option could exist to activate or deactivate the `safeview`.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | beta 21
| react-native     | 0.50.4
| node             | 8.7
| npm or yarn      | 5.6

**Comment by kelset** [comment]
Probably related: https://github.com/react-community/react-navigation/issues/3072

**Comment by brentvatne** [comment]
you should use the SafeAreaView from react-navigation
