### ISSUE TITLE
Cannot override header title left style and header back button margin style

### ISSUE THREAD

**Issue by SimonVuong** [react-navigation/react-navigation#3177]
### Current Behavior

I set `left: 0` in headerTitleStyle and `margin: 0` in headerBackTitleStyle. However, their values do not change from the default 56 and 16 respectively.

```
const StackView = ({ dispatch, nav, reduxState, ...extraProps }) => (
  <CardStackTransitioner {...extraProps} navigation={addNavigationHelpers({dispatch, state: nav, reduxState})} />
)

const mapStateToProps = ({nav, ...remainingState}) => ({
  nav: find(nav.routes, {key: 'accountNavigator'}),
  reduxState: remainingState
});

const StackViewWithRedux = connect(mapStateToProps)(StackView);

const AccountNavigator = (props) => {
    
  const router = StackRouter({
    accountScreen: { screen: AccountScreen },
  }, {
    initialRouteName: 'accountScreen',
    navigationOptions: {
      headerStyle: styles.header,
      headerTitleStyle: styles.title,
      headerBackTitleStyle: styles.back,
      headerTintColor: commonColors.toolbarTextColor
    }
  });

  return createNavigator(router)(StackViewWithRedux);
}

const styles = StyleSheet.create({
  header: {
    backgroundColor: commonColors.brandBase,
    elevation: 1,
  },
  title: {
    marginHorizontal: 0,
    left: 0,     //title needs this
  },
  back: {
    margin: 0 //image needs this
  }
});

export default AccountNavigator();
```
### Expected Behavior

I expect my values to override the default values such that the padding between the edge + back arrow and the padding between arrow + header text are both reduced.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.22
| react-native     | https://github.com/expo/react-native/archive/sdk-21.0.2.tar.gz
| node             | v8.5.0
| npm or yarn      | 5.3.0

**Comment by Amerr** [comment]
This also applies to property backBehavior for the Drawer Navigation.

**Comment by brentvatne** [comment]
hi there! if you'd like to see this feature in react navigation, please [create a feature request](https://react-navigation.canny.io/feature-requests) for it. thanks!
