### ISSUE TITLE
goBack() and NavigationActions.back() behave differently

### ISSUE THREAD

**Issue by evrimfeyyaz** [react-navigation/react-navigation#3180]
I use the following navigation structure:

- Custom Navigator with Tab Router
    - First Screen
    - Stack Navigator
        - First In Stack
        - Second In Stack

### Current Behavior
When I try to go back from `Second In Stack` using the `goBack()` function, the navigation system takes me back to `First Screen`.

When I try the same using the `NavigationActions.back()` function, the navigation system works correctly, and takes me back to `First In Stack`.

### Expected Behavior
`goBack()` should pop the current screen off the stack, and go back to `First In Stack`.

### Sample App
You can find a sample app reproducing the issue here:

https://github.com/evrimfeyyaz/custom-navigation-test/tree/go-back-issue

### Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.22
| react-native     | 0.51.0
| node             | v8.9.1
| npm or yarn      | 1.3.2

**Comment by kelset** [comment]
Thanks for reporting, can I only ask you one thing? Out of curiosity, have you tried using `goBack(null)`?

**Comment by evrimfeyyaz** [comment]
@kelset I just gave it a try. `goBack(null)` works properly (the same as `NavigationActions.back()`.

**Comment by evrimfeyyaz** [comment]
I just checked the documentation again, it has this explanation:

> If the goal is to go back anywhere, without specifying what is getting closed, call .goBack(null);

I still have no idea what that means.

**Comment by kelset** [comment]
There was a PR around this behaviour, but it's kinda complex: https://github.com/react-community/react-navigation/pull/2759#issue-265600916

**Comment by evrimfeyyaz** [comment]
@kelset I am more confused now because the comment says:

> The problem is that it [`goBack()`] doesn't work if we want to go back from a nested navigator to a parent navigator, but `goBack(null)` works.

But in my experience, `goBack(null)` takes me to the previous screen in the nested stack navigator, and `goBack()` takes me back in the parent navigator.

**Comment by ericvicenti** [comment]
I think we're in a better state now with documenting this behavior. You can see the new docs here: https://reactnavigation.org/docs/navigation-prop.html#goback-close-the-active-screen-and-move-back

`props.navigation.goBack()` should always take you back *from the screen that you call it from*. If you want to go back from the *current* screen, you can call `props.navigation.goBack(null)`
