### ISSUE TITLE
StackNavigator Header adds SafeAreaView inset padding even when nested

### ISSUE THREAD

**Issue by davidgraves** [react-navigation/react-navigation#3184]
Expected behavior:
If StackNavigator is rendering a header at the top of the screen, it should add the appropriate inset for the status bar or iphone X safe area. If it is rendering a header in a view that is already inset from the top of the screen it should NOT add the inset padding.

Actual behavior:
Header.js hard-codes <SafeAreaView forceInset={{top:'always'}} />. This is appropriate only when the StackNavigator is at the top of the screen. In all other cases it is incorrectly adding 20 or 44 pixels (iphone or iphone X) of padding to the header.

Steps to Reproduce:
Embed a StackNavigator in a view that is already protected from the safe area. Try to prevent your navigation bar from being too large by 20 or 44 points of wasted padding.

SafeAreaView already knows if it is at the top of the screen. But Header.js specifies "forceInset: {top: 'always'}".  If SafeAreaView already handles this case, Header.js should not override its behavior. If SafeAreaView does not correctly handle this case, it should be fixed.

**Comment by kelset** [comment]
I think it's duplicate of one of these: https://github.com/react-navigation/react-navigation/issues/3173 or https://github.com/react-navigation/react-navigation/issues/3072

Please check them and if so, close this and comment on the other one.

**Comment by davidgraves** [comment]
This is a duplicate. closing.

**Comment by attitude** [comment]
@davidgraves, this is still valid. It's not a duplicate of any of the mentioned issues and should not be closed. `header.js` introduces top padding even when nested in other View that doesn't touch top screen edge.

**Comment by bramus** [comment]
What @attitude says: this is not a duplicate.

**Comment by bramus** [comment]
Until this gets reopened, because it really is no duplicate, you can bypass it by manually overriding the `containerStyle` in the `transitionConfig` of the **nested** navigator:

```
const routeConfigs = { … };
const NestedNavigator = StackNavigator(routeConfigs, {
	headerMode: 'screen',
	transitionConfig: () => ({
		containerStyle: {
			marginTop: -40,
		}
	}),
});
```

(Of course only set this conditionally: when it's an iPhoneX (see [`react-native-iphone-x-helper`](https://github.com/ptelad/react-native-iphone-x-helper) and when the device is in portrait mode)

**Comment by B3rry** [comment]
@davidgraves, I agree, with @attitude and @bramus, this is not a duplicate.

See this view with a marginTop of '35' for an example:
<img width="559" alt="screen shot 2018-03-01 at 1 38 36 pm" src="https://user-images.githubusercontent.com/5562161/36863554-01eaa5d2-1d58-11e8-9434-592ab39ef1f9.png">

**Comment by ericpoon** [comment]
Thanks @bramus, it works for me.
For iPhone X, the extra padding is 24px so `marginTop: -24` works well for my app.

**Comment by quadsurf** [comment]
@bramus  i've found the opposite to be true... if it's not an iPhoneX i have to conditionally set the marginTop to 0 in order to avoid that pesky padding, like so:
```
transitionConfig: () => {
    if (!isIPhoneX) {
       return {
          containerStyle: { marginTop: 0 }
       }
    }
 }
```

either way, your post led me to a solution, so thanks, much appreciated

**Comment by jpamarohorta** [comment]
You can set `headerForceInset: { top: 'never', bottom: 'never' }` in the `navigationOptions` and that will remove the paddingTop.

**Comment by kirkol** [comment]
`navigationOptions:{
header: null,
}
`
Works for me ;)

**Comment by Titozzz** [comment]
This issue should still be opened. I can make a quick snack if you need reproduction. If react-navigation was using SafeAreaView from react-native, this issue could be solved without hacking like @jpamarohorta or @bramus . I forked on my side to fix this, but I could submit a PR. What do you think @kelset @davidgraves ?

**Comment by kelset** [comment]
@Titozzz I think that it would be best to open a new issue with the repro so that @brentvatne can check it out more easily

**Comment by Titozzz** [comment]
Okay sure :)

**Comment by StefanBlamberg** [comment]
`headerForceInset` was replaced with `safeAreaInsets: { top: 0, bottom: 0 }`

**Comment by chialuka** [comment]
> You can also use `safeAreaInsets: { top: 0, bottom: 0 }` as a screen option

Thanks @StefanBlamberg. This worked for me

**Comment by xesf** [comment]
None of the above worked for me, but the reason my SafeAreaView was not getting the proper values was because I had enabled the headerTranslucent option.

**Comment by aswinter90** [comment]
> You can also use `safeAreaInsets: { top: 0, bottom: 0 }` as a screen option

Thanks a lot, @StefanBlamberg, this did the trick!

**Comment by scottwio** [comment]
For anyone looking for the same thing in v6 `safeAreaInset` seems to have been deprecated you can use  `headerStatusBarHeight` set to 0

**Comment by jwallet** [comment]
just realized if you are with expo and you use StatusBar from expo-status-bar, it will interfere with SafeAreaProvider/SafeAreaView from react-native-safe-area-context and the StackNavigator.

It was safe for me to remove expo-status-bar, and I did not need any params shown above.

**Comment by amjadmak** [comment]
I have just tried  headerStatusBarHeight:0  in "options" and it worked just fine

**Comment by antonsthb** [comment]
Has anyone come across a solution for the native stack navigator? None of these props exist there.
