### ISSUE TITLE
"Could not locate shadow view" warnings when resetting StackNavigator

### ISSUE THREAD

**Issue by jd20** [react-navigation/react-navigation#3185]
### Current Behavior
Recently, I added some logic to my app to reset a StackNavigator, but started seeing numerous "Could not locate shadow view with tag" warnings when the reset action was dispatched. I was able to reproduce these warnings by doing following:

1) Enable remote JS debugging (otherwise you won't see the warnings)
2) Create a StackNavigator with two routes (I name the initial one Main, and the one pushed on top Login)
3) Add at least one TextInput component to Login screen
4) Somewhere in Login screen (i.e. componentWillMount), call navigation.setParams(). What params you set are unimportant.
5) Use a reset action to dismiss Login, instead of navigation.goBack().

When the reset action is dispatched, I get a shadow view warning, for each TextInput. If there are 3 TextInput's, for example, I'll get three warnings. If remote JS debugging is not enabled, you will not see the warnings, but instead I tend to see the top screen (Login) flash briefly after it's transitioned out, probably the artifact that the warnings are trying to warn us about.

I created a simple gist which combines all these steps: https://gist.github.com/jd20/b05fd748528c35a592fdfa6daa24a6af

![simulator screen shot - iphone 6 - 2017-12-25 at 01 37 55](https://user-images.githubusercontent.com/17896438/34337782-3a261af0-e917-11e7-8aaa-e86e323edd5b.png)

### Expected Behavior
There should not be any warnings when dispatching the reset action.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.22
| react-native     | 0.51.0
| node             | 9.3.0
| npm or yarn      | yarn 1.3.2

**Comment by kelset** [comment]
Probably related:
* https://github.com/react-navigation/react-navigation/issues/2940
* https://github.com/react-navigation/react-navigation/issues/2609

**Comment by ahmad2smile** [comment]
Getting the same error after dispatching reset Navigation Action

**Comment by just4fun** [comment]
This warning has been resolved in `1.0.0-beta.28`. However, with the latest version, if I navigate from screen A to screen B, to use gesture to swipe back to screen A, both `headerLeft` and `headerRight` button will be un-clickable, not sure why.

**Comment by kelset** [comment]
Thanks for reporting @just4fun, please submit a new issue for the new bug

**Comment by devprakashbinary** [comment]
getting the same error after using the react-native-tab-view and then using the TextInput in a tabContainer and then try to setState for the username/ password.

**Comment by rawadrifai** [comment]
and 2 years later, I get this warning.
Was this ever resolved?

When I do a state update in a content component for a drawer navigator, the update is slow, for example if i hold down the backspace key to delete contents of a text input, it deletes and shows back some letters, then eventually deletes (I know that's confusing). So here's the code:

```
const [searchText, setSearchText] = useState('');
```

```
          <TextInput ref={searchBox} style={styles.searchBoxInput} value={searchText}
            onTouchEnd={() => onTouchEnd()}
            onChangeText={(text) => setSearchText(text)} />
```

**Comment by dmitryshelomanov** [comment]
+ 1

**Comment by dmitryshelomanov** [comment]
@jd20 can you reopen issue ?

**Comment by jd20** [comment]
@dmitryshelomanov I'm not sure if what you're reporting is the same issue (even if warning message is same), I'd suggest filing a new issue and filling out the template, with a simple repro case if possible. A lot's changed since I tested this originally, so not sure it's the same thing or not.
