### ISSUE TITLE
Cannot read property 'router' of undefined, AppNavigator returns undefined (redux)

### ISSUE THREAD

**Issue by LeonChabbey** [react-navigation/react-navigation#3186]
### Current Behavior
I'd like to import my redux store in a file by using
`import { store } from '../store'`

But whenever I try to do it, i get this error:
![simulator screen shot - iphone 8 plus - 2017-12-26 at 10 49 43](https://user-images.githubusercontent.com/12344434/34353936-3e571aba-ea2b-11e7-9c57-994df93c9085.png)

### Expected Behavior
- React navgation shouldn't be affected by that and the app should work

### Your Environment
Tested on iOS simulator.
I'm using redux with react-navigation, I've got nested navigators and it actually works when I do not import my store in other files.
I don't think that there is a problem with importing the store in other file but I might be wrong.

Here are the relevant files:
# store.js
```
import { applyMiddleware, createStore, compose, combineReducers } from 'redux';
import thunk from 'redux-thunk';
import { persistCombineReducers, persistStore } from 'redux-persist';
import rootReducer from './reducers';

const middlewares = [thunk];

const reducer = combineReducers(rootReducer);

const store = createStore(
  reducer,
  compose(applyMiddleware(...middlewares))
);
const persistor = persistStore(store);

export default { store, persistor };
```

# navigator.js
```
import { Platform } from 'react-native';
import { StackNavigator, TabNavigator } from 'react-navigation';

import TabBar from './containers/TabBar';

import LoginContainer from './containers/LoginContainer';
import RealtimeContainer from './containers/RealtimeContainer';

import EventsContainer from './containers/EventsContainer';

const RealTimeNavigator = StackNavigator({
  Events: { screen: EventsContainer },
  RealtimeEvent: { screen: RealtimeContainer }
}, {
  initialRouteName: 'Events',
  headerMode: "none"
});

const AppTabNavigator = TabNavigator({
  Realtime: { screen: RealTimeNavigator }
}, {
  tabBarComponent: TabBar,
  tabBarPosition: "bottom",
  animationEnabled: Platform.OS === "android",
  initialRouteName: "Realtime",
  tabBarOptions: {
    style: {
      backgroundColor: "green"
    }
  }
});

const AppNavigator = StackNavigator({
  Login: { screen: LoginContainer },
  App: { screen: AppTabNavigator }
}, {
  initialRouteName: 'Login',
  headerMode: "none"
});

export default AppNavigator;
```

# navReducer.js
```
// AppNavigator is undefined when importing store in other file
import AppNavigator from '../navigator';

// This line returns the error
const initialState = AppNavigator.router.getStateForAction(AppNavigator.router.getActionForPathAndParams("Login"));

export default nav = (state = initialState, action) => {
  const nextState = AppNavigator.router.getStateForAction(action, state);

  return nextState || state;
};
```

Everything works fine when I don't import my store in other file, if i do it breaks.
Thanks for your help.

**Comment by kelset** [comment]
I'm confused by some things; I don't think it's related to the lib itself:

1. > I'd like to import my redux store in a file by using
import { store } from '../store'

why would you import `store` in a file? Which file, aside from where you have the `Provider`?

2. Can you show the code in where you setup the provider / render the navigator? Or create a Snack to reproduce the issue?

3. I feel like there is something that "conflicts" with the standard way to [integrate redux with this lib](https://reactnavigation.org/docs/guides/redux).

**Comment by LeonChabbey** [comment]
1. I'd like to get the "dispatch" function from my store to dispatch actions from my custom functions that are not connected in any way to redux. I've read that you can do that, but as we can see react-navigation doesn't like it.

2. The file in which the store is provided:
### wrapper.js
```
import React, { Component } from 'react';
import { Provider } from 'react-redux';

import App from './App';
import store from './store';

const wrapper = () => {
  return (
    <Provider store={store.store}>
      <App />
    </Provider>
  );
};

export default wrapper;
```
### App.js (navigator rendered)
```
import React, { Component } from 'react';
import { StatusBar } from 'react-native';
import { connect } from 'react-redux';
import { addNavigationHelpers } from 'react-navigation';
import AppNavigator from './navigator';

class App extends Component {
  render() {
    return (
      <AppNavigator
        screenProps={{
          colors: this.props.colors
        }}
        navigation={addNavigationHelpers({
          dispatch: this.props.dispatch,
          state: this.props.nav
        })} />
    );
  }
}

const mapStateToProps = (state) => {
  return {
    nav: state.nav
  }
}

export default connect(mapStateToProps)(App);
```

3) Maybe, actually I'm not sure if I should keep track of the navigation in redux, I don't really use it that way at the moment.

**Comment by yurikilian** [comment]
Same here

**Comment by heltonvalentini** [comment]
Did anyone manage to understand why this happens ?

**Comment by yurikilian** [comment]
hi @heltonvalentini , I don't know why exactly but this occurs to me when I'm using Redux and need import the created store file because in some actions I need dispatch custom actions using store.dispatch. When I do this, the store is restarted, losing all the routes references.

I've made an workaround creating a service to hold the store. Like this:

```javascript
import StoreHolder from "./src/lib/StoreHolder";
import store from './store.js';

StoreHolder.initialize(store);
export default class App extends Component<{}> {
  render() {
    return (
      <Provider store={store}>
        <Application />
      </Provider>
    );
  }
}

```


Then in my custom actions  I can do this:


```javascript
StoreHolder.dispatch(myAction);
```

**Comment by MyGuySi** [comment]
Ran into this a few weeks ago and it went away for no apparent reason. Just had the same issue resurface today while I'm working on some unrelated code..

**Comment by TheDutchCoder** [comment]
Same issue here, even though I don't import my store but define it inline.
Redux and React Navigation don't work too well together it seems.

I run into this issue whenever I try to nest navigators as documented (here)[https://reactnavigation.org/docs/modal.html]

**Comment by brentvatne** [comment]
ymmv with redux integration, we don't explicitly provide support for this, sorry.

**Comment by TheDutchCoder** [comment]
Would it be a good idea to have a warning at the top of the guide that informs people that Redux is not officially supported? Because it looks like it for your average user probably.

I'm confused about this. The docs have a pretty elaborate guide on how to integrate `react-navigation` with `redux` and the react-navigation team has a `react-navigation-redux-helpers` repo explicitly for this as well.

**Comment by MyGuySi** [comment]
> ymmv with redux integration, we don't explicitly provide support for this, sorry.

As @TheDutchCoder said, that seems a bit strange when there's a section in the docs for redux integration

**Comment by brentvatne** [comment]
Your concerns makes sense! To clarify, the react-navigation repo itself is not concerned with redux integration. If you have redux integration issues, it's best to create an issue on the redux helpers repo (something missing from it? bug in some functionality?) or the website repo (problem with the guide? want to add more documentation to it?).

I hope you can appreciate that everyone who uses redux has their own special configuration that suits their taste, whether they use redux-thunk, saga, or their own homemade thing. perhaps they use a library that abstracts on top of those. perhaps they have other middleware that do many other strange things. It's for this reason that I do not want to support Redux integration in the issues for React Navigation. If an issue can be framed in a way where it can be reproduced without Redux and impacts users who don't use Redux then I'm happy to investigate though.

If someone would like to contribute a section to the documentation for how to use React Navigation with mobx or apollo-link-state or any other state management library I would be happy to integrate that, but we won't support it in the issues.

**Comment by JulianKingman** [comment]
After some experimentation, I can reproduce this issue by separating the navigator from the state initialization. For example, I put the following in one file:
```javascript
const AppNavigator = StackNavigator({
  Home: { screen: Home },
});

export default AppNavigator;
```
...and then this in another:
```javascript
import AppNavigator from '../views/AppNavigator'

const initialState = AppNavigator.router.getStateForAction(AppNavigator.router.getActionForPathAndParams('Home'),
);

export default (state = initialState, action) => {
  const nextState = AppNavigator.router.getStateForAction(action, state);
  return nextState || state;
};
```
Keeping both in one file === no problems, but as soon as I put them in separate files (even though I would expect the same order of operations), AppNavigator comes up as undefined and causes errors. I think this has something to do with the build/initialization process. 

I can get around this issue by doing this (hacky) thing:
```javascript
import AppNavigator from '../views/AppNavigator';

let Navigator = AppNavigator;

if (!AppNavigator) {
  Navigator = {
    router: {
      getStateForAction: () => null,
      getActionForPathAndParams: () => null,
    },
  };
}

const initialState = Navigator.router.getStateForAction(Navigator.router.getActionForPathAndParams('Home'),
);

export default (state = initialState, action) => {
  const nextState = Navigator.router.getStateForAction(action, state);
  return nextState || state;
};
```

**Comment by JulianKingman** [comment]
@brentvatne I can submit a PR to the docs with this tip, but I think this is technically a bug.

**Comment by alexaround25** [comment]
I have manage to resolve this by passing all the props from the Provider to the Root component.

```javascript
<Provider store={store}>
  <Root {...this.props}/>
</Provider>
```

**Comment by RamyarIran** [comment]
I solved it! small confusion while working on redux persist
You define a StackNavigator constant and use it in nav reducer like { AppNavigator }
but for using inside the PersistGate you need to use the default exported navigator which is a React Component which is connected to redux!

```
export const AppNavigator = StackNavigator({
  Splash: { screen: Splash }
}, {
  headerMode: 'none'
  // initialRouteName: 'Splash'
})

class Navigator extends Component {

  render() {
    const { dispatch, nav } = this.props

    return (
      <AppNavigator navigation={addNavigationHelpers({ 
        dispatch, 
        state: nav, 
        addListener: createReduxBoundAddListener('root')
      })} />
    )
  }
}

Navigator.propTypes = {
  dispatch: PropTypes.func.isRequired,
  nav: PropTypes.object.isRequired,
}

const mapStateToProps = state => ({
  nav: state.nav
})

export default connect(mapStateToProps)(Navigator)
```

navReducer :

```
import { AppNavigator } from '../../Navigator'
```

App :
```
import Navigator from './app/Navigator'
```

hope it helps :)
