### ISSUE TITLE
getComponentForState() bypasses nested navigators

### ISSUE THREAD

**Issue by evrimfeyyaz** [react-navigation/react-navigation#3188]
The documentation on creating custom navigators has the following recommendation:

```javascript
// Figure out what to render based on the navigation state and the router:
    const Component = MyRouter.getComponentForState(state);
```

This causes issues when there is a navigator nested inside this custom one.

Let's assume we have the following route structure:

- Navigator
    - Route 1: Screen 1
    - Route 2: Screen 2

- Custom Navigator
    - Route 1: Navigator

### Current Behavior
When `Custom Navigator` requests for the component to render using the `getComponentForState()` method, it bypasses the navigator, and directly fetches `Screen 1`.

`getComponentForRouteName()` works properly. I only found out I could use it after checking the source code of the built-in `TabView` component.

### Expected Behavior
It should fetch `Navigator`.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0 beta 22

**Comment by satya164** [comment]
The behaviour looks fine to me. `getComponentForState` is supposed to return the component for the screen for a given state, and that's what it does.

**Comment by evrimfeyyaz** [comment]
@satya164 I think that is the wrong behavior, and here is why. Take a look at the two states that I took from my current app:

This is the parent navigator (`Custom Navigator` in the example above):
![screenshot 2017-12-30 09 08 50](https://user-images.githubusercontent.com/11249734/34451746-5601efd2-ed41-11e7-8dbf-ccb253dd8377.png)

This is the child navigator (`Route 1: Navigator` in the example above):
![screenshot 2017-12-30 09 09 08](https://user-images.githubusercontent.com/11249734/34451759-79c05102-ed41-11e7-9420-f9308bfae98d.png)

You will see that the parent navigator's state includes the state of the child navigator. They are not the same state, but `getComponentForState()` returns the same component for both of them. The reason, I'm guessing, is that `getComponentForState()` traverses the state tree, and returns the bottom node.

Unless I'm missing something, this should not be the intended behavior, and `getComponentForState()` should return the component at the root node.

**Comment by satya164** [comment]
It returns the component that should be rendered with the given state. For example, if the state was represent as a URL string and not an object, `/settings/notifications` and `/settings/feed` would return different pages, not the same page for the parent route, `/settings`.

Why shouldn't it be the intended behaviour? What is the issue you are having?

**Comment by evrimfeyyaz** [comment]
@satya164 I understand your point, but your analogy isn't accurate in my opinion.

Yes, when you're visiting `/settings/notifications` it means "show notifications." But when you're dealing with navigators, the component you are trying to show is not the bottom node, it's the view for the navigator itself.

Think of it like this, you have a `TabNavigator`, and inside that you have two tabs. In the `TabNavigator`, even when the state is `Tab Navigator/Tab 2`, the component you want to render is not `Tab 2`, it is `TabView` with the child navigation element passed to it.

The current behavior is confusing to me, and even more so because the documentation recommends using `getComponentForState()` for custom navigators. At the very least, that should change.

The way it currently is implemented, I'm having a hard time imagining a use for `getComponentForState()`.

**Comment by satya164** [comment]
> the documentation recommends using getComponentForState() for custom navigators

That's an issue with the documentation. Please send a PR to change it to `getComponentForRouteName`. All the navigators in the library use `getComponentForRouteName` 

> I'm having a hard time imagining a use for getComponentForState()

That's used primarily on the web which you can see here https://github.com/react-navigation/react-navigation/search?utf8=✓&q=getComponentForState

**Comment by evrimfeyyaz** [comment]
@satya164 I've explained the issue with the documentation in the beginning, I wish we didn't have to run a full circle to get to this point.

**Comment by satya164** [comment]
@evrimfeyyaz you already pointed out that `getComponentForRouteName` works properly and the issue was already tagged as "good first issue" and " documentation", which means that the docs need to be updated.

I clarified the intent of `getComponentForState` and that the behaviour is not wrong. you were arguing that it's wrong behaviour. sorry that I spent my free time explaining.

**Comment by brentvatne** [comment]
docs are re-written and live at https://github.com/react-navigation/react-navigation.github.io -- pull requests are very welcome. to improve them
