### ISSUE TITLE
App crashes when overriding tabBarComponent

### ISSUE THREAD

**Issue by DiegoFranciscoHG** [react-navigation/react-navigation#3190]
### Current Behavior
The app crashes with the following error:

![26142530_1521800654535146_489331505_o](https://user-images.githubusercontent.com/34254918/34373214-79b30820-ea9f-11e7-9d1c-407577977b88.png)

### Expected Behavior
The app should not crash, show the custom tab navigator and be able to navigate.

#### Repository with code
https://github.com/DiegoFranciscoHG/react-native-with-react-navigation-custom-tabbarcomponent-bug

#### Steps to reproduce
- Set tabNavigator
- Make component using tabBarBottom
- Manage navigation state with redux
- Override tabBarComponent in the tabNavigator with the custom component

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |1.0.0-beta.22
| react-native     |0.50.3
| node             |9.3.0
| npm or yarn      |yarn 1.3.2

**Comment by Ajith-Pandian** [comment]
@DiegoFranciscoHG The problem is you are not passing the `tabBarComponent's props` to `CustomTabBar` Component.

In your app/router.js 
````
const Navigator = TabNavigator(
  // Screens
  {/* your screens */},
  // TabNavigator configuration
  {
    tabBarPosition: 'bottom',
    tabBarComponent: props => <CustomTabBar {...props} />  // Change this line
  }
);
````

**Comment by DiegoFranciscoHG** [comment]
Hello @Ajith-Pandian, thanks for you response, but it stills not working after making the changes you suggested, it gives me: `TypeError: undefined is not an object (evaluating 'navigation.state.routes')`

**Comment by satya164** [comment]
Can you post your code after the changes?

**Comment by DiegoFranciscoHG** [comment]
@satya164 Here is the diff with the changes: [react-native-with-react-navigation-custom-tabbarcomponent-bug](https://github.com/DiegoFranciscoHG/react-native-with-react-navigation-custom-tabbarcomponent-bug/commit/8cd025e3286ed131b4305f7ab58ae43a3b59bc79?diff=unified#diff-f4b86314561f090eceb05c67e7c5843b)

**Comment by satya164** [comment]
@giautm already pointed out the error, though I'm not sure why you need to override the navigation prop at all.

**Comment by DiegoFranciscoHG** [comment]
@satya164 When I don't override the navigation prop the tabs don't render at all, and changing navigation to navigation.state doesn't seems to work, same error.

**Comment by DiegoFranciscoHG** [comment]
Never mind, it finally worked when I removed the navigation prop. Closing
