### ISSUE TITLE
Cardstyle not working

### ISSUE THREAD

**Issue by jslok** [react-navigation/react-navigation#3193]
I am trying to change the default card background color from the light grey to white but cardStyle does not seem to be working. Using react-native 0.51.0 and react-navigation beta 22.

const Stack = StackNavigator(
{
  Screen1: { screen: Main },
  Screen2: { screen: Map }
},
{
  cardStyle: {
    backgroundColor: "transparent" //or "#FFFFFF"
  }
});

I was only able to change the default background color by editing node_modules\react-navigation\src\views\CardStack\Card.js directly. Any help would be much appreciated.

**Comment by Ajith-Pandian** [comment]
@jslok I've created  a project with 
```js
 "react-native": "0.51.0",
 "react-navigation": "^1.0.0-beta.22"
`````
and applied `cardStyle : { backgroundColor : "red" }` on _StackNavigator_

 It's working perfectly. I think no issues with `react-navigation`.
Please share your code. It will give more clarity to your problem.

**Comment by jslok** [comment]
I got it working. I had cardstyle in the wrong place in my actual code.
