### ISSUE TITLE
React Navigation API Refresh

### ISSUE THREAD

**Issue by satya164** [react-navigation/react-navigation#3195]
This proposal aims to refresh the API of React Navigation to allow advanced use cases and avoid confusion. The changes will likely require fundamental changes under the hood, but aims to minimize the changes to the external API surface.

### Rationale behind the current API

The current API has a single method for navigation, i.e. `navigate`, `goBack` to go back, and a `dispatch` method for more advanced tasks. This is supposed to make it simple to learn the API because it's just one method.

### Problem

Since it's just one method, it has to do a lot of different things depending on the current navigator. However, it gets pretty ugly quickly. Consider the drawer navigator:

```js
// Open drawer
navigate('DrawerOpen');

// Close drawer
navigate('DrawerClose');
```

This looks pretty weird. We create 2 new routes just to open and close the drawer. It also doesn't fit with the mental model, the user would think "I want to open the drawer", not "I want to navigate to the 'DrawerOpen' route".

Apart from the weirdness of the API, since there are no other methods, even simple tasks such as `replace` forces us to use Redux. We shouldn't have to use Redux to use a navigation library. It also ignores the familiarity people might have with web's history API and other navigation libraries.

### Proposal

All navigators are not created equal. It's better to have methods specific to navigators instead of one method for all. We probably want to have 2 kinds of methods:

#### Common methods

These methods will be present on all the navigators.

- `replace(name: string, params?: Object)`: replace the current route object with a new one
- `goBack`: go back to the previous screen

#### Navigator specific methods

- `StackNavigator`
  - `push(name: string, params?: Object)`: push a new route to the stack
  - `pop(count?: number)`: pop a number of routes from the stack
- `TabNavigator`
  - `jumpTo(name: string)`: jump to a specific route
- `DrawerNavigator`
  - `openDrawer()`: open the drawer
  - `closeDrawer()`: close the drawer

For backward compatibility, `navigate` can be an alias to `push` or `jumpTo`.

## Provide a way to subscribe to events such as focus and blur

This has been a hugely controversial API [#51](https://github.com/react-navigation/react-navigation/issues/51). Where lots of people preferred lifecycle-event esque hooks to get notified of events.

The rationale for hooks was:

- It is simple to learn since React already has lifecycle methods
- No need to worry about cleaning up the subscription
- Facebook already uses this approach in some apps

It baffles me how nobody understood all the points I put against it. I'll list them here again in hope that it'll be given some thought:

- A fundamental issue with this is that they look like lifecycle hooks, but aren't. With React, say you have `componentWillUpdate` hook, React will call it recursively from parent to children, with these navigation hooks, this is not the case
- To be able to call these hooks, we need to keep a ref to the original screen. When the screen is wrapped in an HOC, while many HOCs copy the static props, they don't copy the instance methods as it's not straightforward. A common approach is to expose the instance by exposing a method `getWrappedInstance`. We need to do this ceremony to actually expose this method: [react-native-paper/src/core/withTheme.js#L85](https://github.com/callstack/react-native-paper/blob/1ea7def251a80d8bed72ce242eb47c8120492d48/src/core/withTheme.js#L85). In addition, there's additional work required at the callsite to check if this method exists. This approach basically tries to keep simplicity for very simple use cases while requiring way more work for extremely common use cases such as using an HOC.
- If there's a need to hook into these hooks from a child component, it also requires additional ceremony to keep and synchronise the focus state in component state and pass it to child.
- This won't work with static type checkers as Flow

Now lets look at the advantage provides by the alternative approach I suggested, i.e. event listeners:

- It is simple to learn since event listeners are common in JavaScript, you already know how to use them
- No need to worry about cleaning up the subscription, we can clear the subscription automatically when the route unmounts
- Works with HOCs and any other pattern without extra work
- You can pass the navigation prop to a child and the child can subscribe to the events if it needs to
- Static type checkers like Flow will work with this

There are few cons:

- Little bit of extra typing
- In case you conditionally render a child and it subscribes to the events, you need to unsubscribe manually

### Proposal

We can add an additional method `addListener` on the `navigation` prop:

```js
this.props.navigation.addListener('focus', doStuff);
this.props.navigation.addListener('blur', doStuff);
```

## Configuring screen options based on props and state

Currently the screen options can be specified statically. If you need to configure any options based on props and state of the component, or want to update state and props based on some action such as tab press, you need to do it in a hacky way by changing params. it's way more complicated than it needs to be. It also breaks when used with HOCs which don't hoist static props, a common source of confusion. (#145, #2725, #2804)

### Proposal

We can add an additional method `setOptions` on the `navigation` prop:

```js
class Home extends Component {
  constructor(props) {
    super(props);

    this.props.navigation.setOptions({
      title: 'Home'
    });
  }

  render() {
    ...
  }
}
```

If you call `setOptions` again at some point, the object is shallow merged with previous configuration. It might seem a little ugly at first, but this imperative API allows us to build a declarative API on top of it:

```js
function Profile({ route }) {
  return (
    <React.Fragment>
      <NavigationOptions
        title={`${route.user}'s Profile`}
      />
      <ScreenContent />
    </React.Fragment>
  );
}
```

`NavigationOptions` is a React component that can be used to configure the current screen from the render method. It's very useful when your screen's configuration depends on the props, state or both. (#2546)

The static way of specifying the config can still be supported for simplicity and backward compatibility.

## Dynamically specifying navigator options and nesting navigators

Since the navigator options are specified statically, there is no way to specify options such as `initialRouteName` based on a prop or state. (#1586)

### Proposal

Allow passing options as props when rendering the navigator.

```js
<StackNavigator
  initialRouteName="Home"
/>
```

This requires fundamental changes to how the navigator is coded, but is extremely useful. The static way of specifying options still needs to be supported, and options are shallow merged.

Due to the way the parent navigators access the router (i.e. from a static `router` property), this pattern breaks nesting of navigators. So we would need to change it to access the router via the context API probably. It will also enable navigators to be wrapped in HOC. (#1425)

Please post your feedback on these proposals :)

Many of these APIs are implemented here if you wanna give them a try https://github.com/satya164/react-navigation-addons

**Comment by kelset** [comment]
Ok, there's a lot to unpack here - I'll write down a few things.

### 1. Deprecate the `navigate` method

#### A
I like the overall idea of having "better naming" for how to interact with each type of navigator.

#### B
I actually want to double down on the issue you talk about, which is mostly related to how the Drawer creates this "dissonance".
To be honest, I believe we should completely remove/separate the drawer component from the navigation library (which if I can recall correctly is something @brentvatne was also considering too) - and, moreover, to change the drawer we rely upon in order to not be restricted anymore to the Android-like drawer. 
My current proposal on that would be to "take over" (since they are looking for maintainers) [`React Native Drawer`](https://github.com/root-two/react-native-drawer), which would provide way more customization over that approach.

#### C
One more one question over this. In the new "naming" you have, for the Drawer, only an open/close action, which would "add up" to `replace`; meaning, from my understanding, that each screen in the Drawer is always the only one active (because you can only replace the current one with another). Am I right?
Mostly asking because there are a couple issues about having the different screens of a drawer being active all the time / not just one active / this weird scenario ( https://github.com/react-navigation/react-navigation/issues/2277 ) - I'm saying weird because to me it's "right" that in a drawer only one screen is active/mounted at the time, but it may be just me.

### 2. Provide a way to subscribe to events such as focus and blur

I like the listeners' approach, my current concern would be related to how they would be set up. Basically, I guess in your proposal they would be "configured once" at startup and navigator-wide; my concern is that ppl would start wanting to change that at runtime... which probably then would be possible by changing the callback and not the listener...? (does this question even makes sense?)

### 3. Configuring screen options based on props and state

#### A
I agree with adding the `NavigationOptions` as component.
Bit confused by `setOptions` - would it basically be a `setParams` + component level `navigationOptions` short-hand to make it simpler to config? (referring to [this approach](https://reactnavigation.org/docs/intro/headers#Header-interaction-with-screen-component))

#### B (OT)

In the snippet, you use `<React.Fragment>`, are those out already in RN (isn't it 16.2 only?)? 😋

### 4. Dynamically specifying navigator options and nesting navigators

A bit concerned by this, basically because of what you already said:

> This requires fundamental changes to how the navigator is coded, but is extremely useful.

> Due to the way the parent navigators access the router (i.e. from a static router property), this pattern breaks nesting of navigators.

But surely we should figure out a way to make them dynamically configurable.

How would this approach "behave" with, like, screen-level changes of animations and stuff (ex. https://github.com/react-navigation/react-navigation/issues/175 ) ?

**Comment by satya164** [comment]
> To be honest, I believe we should completely remove/separate the drawer component from the navigation library (which if I can recall correctly is something @brentvatne was also considering too) 

That's alright. It's about establishing the pattern we use so that the API stays coherent.

> from my understanding, that each screen in the Drawer is always the only one active (because you can only replace the current one with another)

Yes. If it's necessary, another method like `jumpTo` could probably added too.

> my current concern would be related to how they would be set up. Basically, I guess in your proposal they would be "configured once" at startup and navigator-wide; my concern is that ppl would start wanting to change that at runtime

`addListener` would be a property on the `navigation` prop, so the listeners would be setup inside components, for example in `componentDidMount`, not once navigator-wide.

> would it basically be a setParams + component level navigationOptions short-hand to make it simpler to config? (referring to this approach)

I'm not sure what you mean by `component level navigationOptions`? That approach in the docs is a big hack, even though it's the only option right now. Params are part of the navigation state. Methods, styles etc. and don't belong in the navigation state. For example, when you persist your redux state, what do you do with those things that aren't navigation state? `setOptions` is to make it straightforward to configure options without piggybacking on params, and keep params separate from options.

> A bit concerned by this, basically because of what you already said

Yes, but we need to change the internals because the fundamental design is flawed. But it shouldn't affect the external API, so it shouldn't matter much.

> How would this approach "behave" with, like, screen-level changes of animations and stuff

These are only navigator options. They will behave the same as previous, the only difference is now you can specify options per instance of the navigator instead of global options for all instances.

**Comment by kelset** [comment]
Thanks for the replies 👌

Couple more things:

> React Native Drawer is based on pan responder which means it'll not have good perf. The current implementation uses native drawer on Android which is a better approach.

Tbh I think, from what I can see in the issues / around me:
1. having more customization > better perfs
1. tbh drawer, as a pattern, is slowly dying

But I'd like to ask @GantMan what he thinks about this since he used drawers way more than me.

> That approach in the docs is a big hack

Oh wow, I thought it was a legit one - I've been using it a lot 😅

Anyway, I'd like to hear from couple more people and then we can maybe do a new release roadmap kinda thing 😇

**Comment by satya164** [comment]
> having more customization > better perfs

PanResponder can have very bad performance and depending on the app and requires lots of work to optimize. You probably use iOS/high end Android device, so don't see it. But I've used it on mid range Android devices and it's noticeable enough to distinguish itself from actual native apps. That's why there is work going on gesture handler.

**Comment by wvteijlingen** [comment]
I like your proposal. If possible I would like to add a couple of things:

1. Give each navigator the ability to `present` another screen or navigator modally. Right now you have to nest navigators if you want to display some things modally, which is not a clean solution.

2. Bring in the `parentNavigator` property that currently exists in [react-native-addons](https://github.com/satya164/react-navigation-addons). When nesting a lot of navigators, this is really helpful if you want to navigate back within a parent navigator.

3. I still think the way of passing props should be reviewed again. I know [the issue](https://github.com/react-navigation/react-navigation/issues/935) was closed, but there have been quite a few people questioning this.

**Comment by satya164** [comment]
Thanks for your comments @wvteijlingen

> Give each navigator the ability to present another screen or navigator modally. Right now you have to nest navigators if you want to display some things modally, which is not a clean solution.

I'm not sure what you mean. Can you give an example?

> Bring in the parentNavigator property that currently exists in react-native-addons

It's a method `getParent`. yeah, it will probably be useful

> I still think the way of passing props should be reviewed again

I think this is out of scope of this proposal. I don't think it makes a lot of sense to change it even if people are questioning this because
1. Whatever the new way is, it'll be a big breaking change and will affect a lot of people since params is such a basic feature
2. The current way is inconvenient, but changing it is purely for convenience and doesn't add any new features/significantly improve the workflow to justify the breaking change

**Comment by wvteijlingen** [comment]
> I'm not sure what you mean. Can you give an example?

Basically the option to indicate per navigation action if a screen should be presented modally. Right now you can't do this, so you have to work around it by wrapping your navigation hierarchy in a StackNavigator with a modal mode. So I think it would be nice to have a `present` method that opens the new screen modally. This can then be called on a StackNavigator, but also a TabNavigator (not sure about drawer). There has been a lot of requests for this in the past already. 

> It's a method getParent. Yeah, it will probably be useful

**Comment by philpl** [comment]
@wvteijlingen correct me if I'm wrong, but this would either radically change the idea of how to set up React Navigation navigators, or it would add on to the API, bloating it in the process possibly.

It'd be great though to improve the StackNavigator modal story, since it does indeed break the "top-down" approach of nested navigators, since suddenly a StackNavigator far above in the hierarchy needs to be controlled.

I'm pretty sure @satya164's navigator-specific methods would alleviate this problem though

**Comment by satya164** [comment]
> So I think it would be nice to have a present method that opens the new screen modally

I'm still not sure about what you are proposing, what do you mean by "modally"? Can you give some code example of how it'll be used and how it'll behave? From my guess, you mean this?

```js
class MyComponent extends React.Component {
  onPress() {
    this.props.present(<MyStacks />
  }

  render() {
    ...
  }
}
```

If you mean this, what's the use case? If you just want to render a navigator dynamically based on some condition, won't my last proposal work for this, where it allows to render a navigator as a component? I think that's a much better API because it's declarative vs the imperative `present` method.

Or are you talking about the transition animation?

**Comment by kelset** [comment]
He may be referring to something along these lines: https://github.com/react-navigation/react-navigation/pull/2308

**Comment by satya164** [comment]
@kelset So it's about customising the transition animation per screen basis? I actually have some ideas on making that easier since I had a similar use case recently. But let's talk about it later. Though @wvteijlingen mentioned it should work with `TabeNavigator` too, so I'm not entirely sure.

One idea is to have a `<Card />` component which controls the animations and gestures for individual screens based on a `visible` prop. In `StackNavigator`, every screen would be wrapped by `<Card />`. Now if you want same transition and gestures in another navigator, you just render that component with desired children.

**Comment by wvteijlingen** [comment]
Yeah, basically that is what it boils down to I think. Consider the following use cases:

A tab bar with a big 'action button' in the middle (quite a few apps have this). The normal tabs just show a different screen, but tapping the action button opens a new navigator as a modal. Would be great if that would be possible.

I  think for such a thing to work, you have to be able to specify `mode: modal` on the navigationOptions. Or even better imho, to be able to pass that as an option when navigating.

**Comment by ericvicenti** [comment]
These are some exciting proposals, @satya164! I think it would be easier if we broke out discussion into separate RFCs/issues. These are the independent proposals, as I understand it: (trying to discuss them all here would be madness!)

- Deprecate 'navigate'
- Event system
- navigator.setOptions and <NavigationOptions />
- initialRouteName prop for navigators

I think the event system is the most important thing to address, and I've come to agree with your event emitter approach. Lets discuss the details in https://github.com/react-navigation/rfcs/pull/1

As far as the other proposals go, I think setOptions and <NavigationOptions /> is pretty important and would be viable additions for v1. I don't really want to deprecate 'navigate', but I agree that action names have room for improvement in the use cases you mentioned.

**Comment by Donhv** [comment]
Now I use react-navigation-add-ons.
I have a question: What is best solution for refresh API when change TabNavigator.

**Comment by JulianKingman** [comment]
I think these proposals all make a lot of sense. One thing that was touched on that I would like to see is an easy way to override actions within Tab and Drawer navigators. Using @wvteijlingen's example above, a button in the middle of a tab bar that does something different (maybe it brings up a modal, or maybe it opens the camera, etc...). To my mind, if everything else remained the same, I would like it to look something like this:
```javascript
const Tabs = TabNavigator({
  Home: {screen: Home},
  TakePicture: { 
    // if onPress is present, screen is not necessary
    onPress (navigation) {
      const pic = Camera.takePictureAsync();
      //...etc
    },
    // configuration
    navigationOptions: {
      tabBarIcon: {...}
    },
  },
});
```

**Comment by satya164** [comment]
@JulianKingman you can achieve it with a custom Tab Bar.

**Comment by JulianKingman** [comment]
@satya164 that's what I've been doing so far, but it's a common enough use-case that I think it should be baked in. I've used some sort of custom function in roughly 50% of my projects, and that number might go up if it was easier to do. A few examples I turned up in a couple minutes: https://github.com/react-navigation/react-navigation/issues/314, https://github.com/react-navigation/react-navigation/pull/525, https://github.com/react-navigation/react-navigation/issues/1576, https://github.com/react-navigation/react-navigation/issues/1059, https://github.com/react-navigation/react-navigation/pull/1335, https://github.com/react-navigation/react-navigation/issues/1670, https://github.com/react-navigation/react-navigation/issues/2804
It feels like an anti-pattern to overwrite the whole tab bar just to change one of the tab's functions.

**Comment by JulianKingman** [comment]
@satya164 I missed tabBarOnBarPress which was merged here: https://github.com/react-navigation/react-navigation/pull/1335
So there should perhaps be a drawerItemOnPress, but otherwise we're looking good.

**Comment by brentvatne** [comment]
closed because this is better suited for rfcs and mostly has been split up accordingly in rfcs already
