### ISSUE TITLE
Hide navigation header when open drawer

### ISSUE THREAD

**Issue by hoangdv1995** [react-navigation/react-navigation#3197]
I want to hide header only when opening drawer.

`const TabBaseApp = TabNavigator({
  [screens.MY_HOME]: {
    screen: Home
  },
  [screens.TOOL]: {
    screen: Tool
  }
}, {
  tabBarComponent: CustomTabBar,
  tabBarOptions: {
    activeTintColor: theme.COLORS.primary,
    inactiveTintColor: theme.COLORS.inactive,
    upperCaseLabel: false,
    indicatorStyle: {
      backgroundColor: theme.COLORS.primary
    },
    style: {
      backgroundColor: theme.COLORS.white,
      borderTopColor: theme.COLORS.divider,
      borderTopWidth: 1,
      borderStyle: 'solid'
    },
    labelStyle: {
      fontSize: 12
    },
    showIcon: true,
    showLabel: false
  }
});

const DrawerNav = DrawerNavigator({
  [screens.HOME]: {
    screen: TabBaseApp
  }
}, {
  contentComponent: Drawer
});

const StackBaseApp = StackNavigator({
  [screens.LOGIN]: {
    screen: Login
  },
  [screens.DRAWER]: {
    screen: DrawerNav
  }
}, {
  // headerMode: 'none' //---- alway hide header
});`

Thanks in advance!

**Comment by kelset** [comment]
Closing because you haven't followed the template. Moreover it's already been discussed here: https://github.com/react-navigation/react-navigation/issues/843
