### ISSUE TITLE
Supported React-Native version's for a particular React-Navigation version? Docs.

### ISSUE THREAD

**Issue by ravirajn22** [react-navigation/react-navigation#3198]
## The issue tracker is reserved for bug reports only.
I have already searched many places but can't find information regarding supported React-Native versions for a particular React-Navigation version. If u have got any links it would be highly helpful.

### Current Behavior
Currently, I am upgrading react-native from 0.44.0 to 0.51.0. But I have no idea to which react-navigation version should I upgrade? Will it support any react-native versions?

### Expected Behavior
Docs for supported react-native versions for each react-navigation versions.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.11
| react-native     | 0.51.0
| node             | 6.11.0
| npm or yarn      | 1.3.2

**Comment by jslok** [comment]
I have not run into any compatibility issues with react-native starting 0.47 and the latest at the time react-navigation. You can check the react-navigation release notes for any breaking changes.

**Comment by ravirajn22** [comment]
But how to be 100% sure that a particular react-native version will work with this react-navigation version without breaking. Breaking changes of react-navigation probably only list changes on that library. BTW each react-native version brings its own set of breaking changes,  hence I can't be sure if we can blindly update versions. Also, React-navigation has a peer-dependency on ``"react-native": "*"`` in all versions. Is something I am missing?

**Comment by kelset** [comment]
>  Release notes of react-navigation probably only list changes on that library.

Nice to see that you haven't even checked the release notes before writing this issue.
We actually do write it when we upgrade to a particular version (ex. https://github.com/react-navigation/react-navigation/releases/tag/v1.0.0-beta.20 ).

> BTW each react-native version brings its own set of breaking changes, hence I can't be sure if we can blindly update versions.

Both libraries are still in beta, so it's up to you to keep up to speed with them.

**Comment by ravirajn22** [comment]
@kelset and @jslok sorry my mistake. I checked the release notes but just did not give proper attention.  Thanks for the quick reply. Request if we can add this to the documentation instead of checking release notes?
