### ISSUE TITLE
Add a new optional prop to enable/disable BackHandler.

### ISSUE THREAD

**Issue by jainkuniya** [react-navigation/react-navigation#3200]
We have combination of navigation in our app. `DrawerNavigator`, `StackNavigator` & `TabNavigator`.

Navigation tree is like 
```
StackNavigator
       ||
DrawerNavigator
       ||
TabNavigator
```

We have tabs in our first route of `StackNavigator` (basically inside `TabNavigator` which are in `Drawer`). 

### Current Behavior
Now when user is on another screen of `StackNavigator` (I mean first screen is at the bottom of stack) & presses hardware back button then that press is captured by `TabNavigator` (of the first screen)

### Expected Behavior
It should be captured by `StackNavigator`. 

We have `BackHandler` which is at the same level of `StackNavigator` in the tree. But it is only triggered when it is retured from Navigator `BackHandler`. https://github.com/react-navigation/react-navigation/blob/master/src/createNavigationContainer.js#L156

Also we want to handle `TabNavigator` back events manually.

So to handle such situations adding a new optional prop to enable/disable BackHandler will be very helpful. 

Thoughts of this?
I will be happy to send a PR for this.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | `1.0.0-beta.22`
| react-native     | `0.51.0`
| node             | `v8.6.0`
|  yarn      | `v1.2.0`

**Comment by satya164** [comment]
You can just add a listener with https://facebook.github.io/react-native/docs/backhandler.html manually and do what you want.

**Comment by jainkuniya** [comment]
Thanks 👍 
Changing the position of our old `BackHandler` in the tree, worked.
