### ISSUE TITLE
Custom navigation prop and redux integration

### ISSUE THREAD

**Issue by rodan-lewarx** [react-navigation/react-navigation#3206]
### Current Behavior
- When integrating react-navigation with redux (as described in documentation) I found out an issue. I tried to pass custom navigation prop = I didnt want to use addNavigationHelpers and I wanted to construct navigate, setParams and goBack actions on my own. I expected that such modified navigation prop object when passed to top level router would be available in all the screens. This didnt happen. I have found out that even custom props get overwritten in `react-navigation/src/views/CardStack/CardStack.js` 

on line 405 `const { navigation } = this._getScreenDetails(scene);` as `this._getScreenDetails` calls `addNavigationHelpers` when screendetails are not saved and this navigation gets passed into SceneView

### Expected Behavior
- I was expecting that this (line 405 of Cardstack.js) would behave like 

`const navigation = this.props.navigation || this._getScreenDetails(scene).navigation;`

 instead. So that if there is a custom prop passed it will always get distributed further down to SceneView and its context.
- Am I missing something. Or is it okay to make PR like this?

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation  | 1.0.0.-beta22
| react-native  |  0.50.4
| node         |  v8.9.1 
| yarn     | 1.3.2

**Comment by kelset** [comment]
👋 there.

Yeah sure open a PR, so it can be tested and further discussed :)

**Comment by rodan-lewarx** [comment]
@kelset I have created the PR for testing here #3208 

So you can check it out.

I dont think this is a feature request but a bug, because [Redux integration docs](https://reactnavigation.org/docs/guides/redux) say that:

> Once you pass your own navigation prop to the navigator, the default navigation prop gets destroyed. You will most probably pass the navigation prop's properties that you want to access. Normally state and dispatch properties are passed to the navigator. You will learn how to pass those properties further in this guide. Since you have destroyed the default props, if you try to invoke something you have not explicitly passed down, it won't work. So, if you didn't pass dispatch to the navigator and only passes state than you can't access dispatch further in your Components.

Which is not happening in this case and in the end the navigation prop gets always overwritten in the screen.

**Comment by kelset** [comment]
Awesome, thanks.

(and yeah I actually tagged it as a bug earlier, but then I was a bit concerned that would be a bit "too harsh", dunnow)

**Comment by brentvatne** [comment]
@Ashoat - not really sure what to think about this one

**Comment by Ashoat** [comment]
This is similar to [#12](https://github.com/react-navigation/react-navigation-redux-helpers/issues/12). Currently, we don't allow people to define custom action creators - we only pass down the core `react-navigation` ones, and custom implementations of the core action creators get overriden. I think @rodan-lewarx is right that the Redux integration docs mistakenly lead the user to believe that using custom action creators is supported. One of the items on my to-do list for this project is to revamp those docs, and when I do that I'll make sure that that changes.

The bigger question here might be: "do we want to support custom action creators"? On one hand, enabling the use of custom action creators could obviate the need for Redux integration in many use cases, which would be a good thing. Right now the only way to mutate the navigation state in a custom way is through Redux integration.

On the other hand, though, we probably don't want to support people mutating the navigation state in custom ways, and that's pretty much the only reason custom action creators would exist. I have some custom navigation state mutations in my application, but I've carefully made sure that the mutations don't result in unexpected state changes for the views.

**Comment by brentvatne** [comment]
of interest re: custom action creators: https://github.com/react-navigation/rfcs/pull/18

**Comment by kodayashi** [comment]
Hi @Ashoat - I think you're asking the right question. My ask came up after reading a few articles like this: http://blog.isquaredsoftware.com/2016/10/idiomatic-redux-why-use-action-creators/

I liked the idea of using pre-bound action creators to obviate the need for components to use dispatch and make them Redux agnostic. The flow has been nice in my app, and moving that practice into redux-powered navigation felt like a natural next step (so as not to have multiple patterns for dispatching actions).

**Comment by brentvatne** [comment]
I believe this is resolved now on 2.0, and you don't need to even use `addNavigationHelpers` anymore.
