### ISSUE TITLE
Swipe Feature to open Drawer doesn't work well on iOS

### ISSUE THREAD

**Issue by wookelvin** [react-navigation/react-navigation#3210]
I've noticed that swiping from left edge to open the drawer works well on android. However, on iOS, it stutters and freezes position if you swipe too fast. The only proper way to open the drawer is through an external onPress button from a given screen. 

---

### Current Behavior
To produce the bug, on iOS, swipe from left edge to open drawer. 
Drawer will show, but freeze about 1/4 of way in. 
Letting go of swipe will cause the drawer menu to freeze at location. 
To cancel the action, tap anywhere else in the screen. 

Issue does not exist on android. 

### Expected Behavior
I should be able to drag the drawer menu fully out and not have it lose focus nor freeze half way through. 

### Your Environment
Using iOS 11.2.1
react-navigation 1.0.0-beta.22
react-native 0.50.3
node 6.11.4
npm 5.6.0

**Comment by PatNeedham** [comment]
@wookelvin can you post a minimal code snippet demonstrating how you are creating the drawer? Is it only on one child screen that the drawer freezes, or on all of them?

**Comment by wookelvin** [comment]
Thanks for getting back. 
The code is as follows. It freezes on all child screens. 

`const CustomDrawerContentComponent = (props) => (
  <View style={{flex:1}}>
    {/*Logo*/}
    <Image
      style = {{width:240,resizeMode:'contain'}}
      source={require('./../assets/logo.jpg')}
    />

    {/*The rest of the menu items that show up underneath it*/}
    <DrawerItems {...props} />
  </View>
);

/*
 * Drawer Customization options
 */
const DrawerNavigatorConfig = {
  drawerWidth: 250,
  contentComponent:CustomDrawerContentComponent,
  drawerOpenRoute: 'DrawerOpen', 
  drawerCloseRoute: 'DrawerClose',
  drawerToggleRoute: 'DrawerToggle',
};
const DrawerApp = DrawerNavigator(DrawerRouteConfigs, DrawerNavigatorConfig);`

**Comment by brentvatne** [comment]
we'll switch drawer to use react-native-gesture-handler soon

**Comment by brentvatne** [comment]
https://github.com/react-navigation/react-navigation-drawer/tree/next

working on it here
