### ISSUE TITLE
Jest throws error mentioning CardStack in stack trace

### ISSUE THREAD

**Issue by ahmad2smile** [react-navigation/react-navigation#3211]
### Current Behavior
- Error on running snapshot test with `jest` using `react-test-renderer`. Still nothing breaks though. Test runs and passes. Stack trace presented by `jest` shows the error is related to `CardStackTransitioner` and `CardStack`.

I got Dashboard Screen as main route and Login Screen as secondary route. Could be related to the fact the I'm reseting the stack of Stack Navigator in my components.

[Code where I'm reseting the stack](https://github.com/ahmad2smile/react-native-starter/blob/27d294e68a25fcf6257be6ded1ca2ae52234bba8/screens/Dashboard/DashboardComponent.js#L42)

Screenshot:
<img width="1225" alt="react-native-starter_ _yarn_test_-u_ _node_ _node__usr_local_bin_yarn_test_-u_ _181x51" src="https://user-images.githubusercontent.com/6108922/34512108-f8210184-f081-11e7-9c0e-ec85126cf445.png">

Repo to Reproduce Error:

[react-native-starter](https://github.com/ahmad2smile/react-native-starter)

Instructions to run the repo:

- Install Packages
- `yarn ios`

### Expected Behavior
- `jest` not throw error cause of `react-navigation`

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.22
| react-native     | 0.51.0
| node             | 9.3.0
| npm or yarn      | 5.6.0 n 1.3.2

**Comment by kelset** [comment]
Thanks for reporting.
Jest sometimes act weirdly around navigation.
Some (prob) related issues:
* https://github.com/react-navigation/react-navigation/issues/3049
* https://github.com/react-navigation/react-navigation/issues/2820
* https://github.com/react-navigation/react-navigation/issues/2994

**Comment by ahmad2smile** [comment]
I check all of those issues I don't think this one is related to those. I actually did search ends of the internet before posting it here (I think :) )

**Comment by eriveltonelias** [comment]
Hi! Since this issue has been quiet for a while I'm going to go ahead and close it. If the issue persists in the latest version of React Navigation please re-open!
