### ISSUE TITLE
Jumpy navigation animation on click of tab

### ISSUE THREAD

**Issue by nicksarafa** [react-navigation/react-navigation#3212]
### Current Behavior
- on click of a tab, the screen occasionally jumps on iOS before navigating to the other tab screen. However, when I slide from one view to the other, the screen doesn't jump

### Expected Behavior
- When I click a tab, I'd like the transition between tabs to animate as smoothly as it does when i swipe between tabs

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation  ^1.0.0-beta.19 |
| react-native 50.3    |
| node 9.3.0          |
| yarn |

![janky-tab-nav](https://user-images.githubusercontent.com/7340254/34513486-75e7a250-f0a3-11e7-8e33-4d41a398babc.gif)

**Comment by kelset** [comment]
1. looks like it only happens to you on the third tab, have you tried "removing some code" to see if it's caused by something in particular from that tab?
1. without a repro it's gonna be hard to debug I fear

**Comment by nsarafa** [comment]
@kelset unfortunately its a private repo at the moment 😞 . Perhaps I'm seeing things, but i feel as though there is a correlation between the tab animation changes, and the screen transition jumps. Is there anyway I can override the tab color transition on tap when I initialize my `TabNavigator`?

**Comment by satya164** [comment]
You have a map which can be expensive to render and might be causing lags.

**Comment by MoOx** [comment]
I confirm that maps can very easily produce lags, especially in simulators
