### ISSUE TITLE
Feature:Enable Single Screen rotation support 

### ISSUE THREAD

**Issue by jinxac** [react-navigation/react-navigation#3216]
### Current Behavior

I have a react native application in which i use react navigation for handling navigation.

I have a portrait only screen orientation enabled for both iOS and android. Since landscape mode is locked rotation does not work for the screens. 

Now, I was wondering if there a way possible to enable rotation for a particular screen. This feature is useful for apps that has a video player screen, which only need the player screen can be rotated.
Please check [https://github.com/wix/react-native-navigation/issues/681](https://github.com/wix/react-native-navigation/issues/681) for further references.

### Expected Behavior
Screen wise rotation should be allowed in orientation locked devices.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | v1.0.0-beta.21
| react-native     | 0.47.2
| node             | 0.7.2
| npm or yarn      | 3.10.10

**Comment by satya164** [comment]
This is not the job of react-navigation. You need to use a native module to enable/disable orientation dynamically. You'll need to know when a screen is focused to be able to do that, but that's a separate feature (#3195)

**Comment by jinxac** [comment]
@satya164 i think you are right. Maybe [https://github.com/yamill/react-native-orientation](https://github.com/yamill/react-native-orientation) can help me out here. Let me give it a try.

**Comment by jinxac** [comment]
@satya164 @kelset i tried  [ https://github.com/yamill/react-native-orientation]( https://github.com/yamill/react-native-orientation) and it works fine with that.

Here is what i tried:-

```
import React from "react";
import PropTypes from "prop-types";
import Orientation from "react-native-orientation";
import VideoPlayer from "react-native-video-controls";
import {popRoute} from "../../navigation/helper";


const propTypes = {
  navigation: PropTypes.object.isRequired,
  pageUrl: PropTypes.string.isRequired
};


class VideoDetail extends React.Component {

  componentDidMount () {
    Orientation.unlockAllOrientations();
  }

  componentWillUnmount () {
    Orientation.lockToPortrait();
  }

  goBack = () => {
    popRoute(this.props.navigation);
  };

  render () {
    return (
      <VideoPlayer
        disableFullscreen
        disableVolume
        repeat
        goBack={this.goBack}
        source={{
          uri: this.props.pageUrl,
          type: "mp4"
        }}
      />
    );
  }
}

VideoDetail.propTypes = propTypes;

export default VideoDetail;
```

**Comment by brentvatne** [comment]
moved to feature request but comments above are all valid to solve the issue

https://react-navigation.canny.io/feature-requests/p/control-orientation-for-screens-in-navigationoptions

**Comment by ThisaraGitHub** [comment]
can we change this portrait view to landscape mode in the beginning? your help is highly appreciated 

![screen shot 2018-08-20 at 9 55 25 am](https://user-images.githubusercontent.com/30999158/44320398-7e24f600-a45f-11e8-84ba-c3add33758ce.png)

![screen shot 2018-08-20 at 9 55 40 am](https://user-images.githubusercontent.com/30999158/44320400-80875000-a45f-11e8-8770-e707fe5505a9.png)

**Comment by lustigdev** [comment]
@jinxac would you mind sharing your popRoute helper?

**Comment by jinxac** [comment]
@lustigdev I do a simple `navigation.goBack` to popRoute. May I know what are u looking for exactly?

**Comment by amwebexpert** [comment]
This one is also an alternative:
- https://www.npmjs.com/package/react-native-orientation-locker
