### ISSUE TITLE
TypeError: In this environment the sources for assign MUST be an object.This error is a performance optimization and not spec compliant

### ISSUE THREAD

**Issue by naveed89** [react-navigation/react-navigation#3231]
## The issue tracker is reserved for bug reports only.

If you have a question or feature request, please try one of the following resources:

- [Read the documentation](https://reactnavigation.org/)
- [Post a feature request to Canny](https://react-navigation.canny.io/feature-requests)
- [Get help on Discord chat (#react-navigation on Reactiflux)](https://discord.gg/4xEK3nD) or [on StackOverflow](https://stackoverflow.com/questions/tagged/react-navigation)
- Search for your issue - it may have already been answered or even fixed in the development branch. However, if you find that an old, closed issue still persists in the latest version, you should open a new issue.

---

### Current Behavior
- _If describing a bug, tell us what happens. Please provide a repository with code and steps to reproduce the bug. **Not providing code that other people can run makes is significantly harder to fix your bug.** Provide a screenshot when possible_
- _If suggesting a change/improvement, explain the difference from current behavior_

### Expected Behavior
- _If you're describing a bug, tell us what should happen_
- _If you're suggesting a change/improvement, tell us how it should work_

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |
| react-native     |
| node             |
| npm or yarn      |

Below is the code 

import React, { PureComponent } from 'react';
import {
  StyleSheet,
  View,
} from 'react-native';
import Date from './Date';
import type Moment from 'moment';

export default class Dates extends PureComponent {

  props: {
    // Currently active date index
    currentDateIndex: ?number,
    // Array of dates to render
    dates: Array<Moment>,
    // Callback to handle date select
    onSelectDay: (index: number) => void,
    // Callback to handle date render
    onRenderDay: (index: number, width: number) => void,
  };

  render() {
    const {
      currentDateIndex,
      dates,
      onSelectDay,
      onRenderDay,
    } = this.props;
    return (
      <View style={styles.container}>
        {dates.map((date, index) =>
          <View key={index}>
            <Date
              date={date}
              index={index}
              isActive={index === currentDateIndex}
              onPress={onSelectDay}
              onRender={onRenderDay}
              key={index}
            />
          </View>
        )}
      </View>
    );
  }

}

const styles = StyleSheet.create({
  container: {
    flexDirection: 'row',
  },
});

![screenshot_1515219602](https://user-images.githubusercontent.com/33197194/34637243-8bc39cb4-f2d3-11e7-9103-6f6099d70aac.png)

**Comment by satya164** [comment]
How is this related to React Navigation?

**Comment by naveed89** [comment]
Not related to navigation
