### ISSUE TITLE
Misleading error message when initialRouteName is incorrectly set for drawerNavigator instance.

### ISSUE THREAD

**Issue by antwan2093** [react-navigation/react-navigation#3233]
### Current Behavior
An error is raised when you declare an invalid initialRouteName in the configuration passed to a DrawerNavigator instance. The error contains a misleading message though, stating that the initialRouteName is invalid for the TabNavigator when, in my case I wasn't using/hadn't even imported TabNavigator. Fixing the initialRouteName got rid of this error, but was briefly quite confusing.

Suspect its only a copy paste error or something silly but would be useful if fixed! :) I will submit a pull request if i can figure out where the message is coming from!

### Expected Behavior
The error should specify the initialRouteName was invalid for the drawerNavigator not the tabNavigator.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.23
| react-native     | 0.51.0
| node             | 9.3.0
| npm or yarn      | 5.5.1

**Comment by Michael-Antczak** [comment]
Hey @antwan2093. Can you provide the screenshoot with the error message? I am trying to replicate this behavior.

**Comment by brentvatne** [comment]
ah yeah, drawer is using the same router as tabs currently. we'll change this soon and it should resolve the problem

**Comment by antwan2093** [comment]
That's great, thanks, just wanted to highlight it as it's currently a tad baffling :p

 

Cheers

**Comment by brentvatne** [comment]
this is resolved on master now :) but won't be released until 2.0

**Comment by antwan2093** [comment]
@brentvatne that's great! Thanks :)
