### ISSUE TITLE
Allow user defined styles for the Animated.View that wraps TabBarIcon

### ISSUE THREAD

**Issue by SeunLanLege** [react-navigation/react-navigation#3245]
https://github.com/react-navigation/react-navigation/blob/e2e540c32d9126cbcd03d14e60ff4b22c97699bb/src/views/TabView/TabBarIcon.js#L50-L64

User should be able to supply their own style for the animated views

**Comment by Druux** [comment]
@SeunLanLege did you manage to solve this?

**Comment by SeunLanLege** [comment]
Uhm no not really, it required more time than I had, so I used a custom tab bar
