### ISSUE TITLE
Beta 22 breaks param passing functionality in nested navigators

### ISSUE THREAD

**Issue by mishacajic** [react-navigation/react-navigation#3252]
I'm passing a user parameter from a login screen (which is a token I receive from an external API) to a tab navigator and all of its children. The structure of my navigator is like this:

Root navigator (Stack):
----Login screen (Screen):
----Main tab navigator (Tab navigator):
--------Tab 1 (Stack navigator):
------------Tab 1 screen 1 (Screen)
------------Tab 1 screen 2 (Screen)
--------Tab 2 (Stack navigator):
------------Tab 2 screen 1 (Screen)
------------Tab 2 screen 2 (Screen)

I'm passing the user object as a param from Login screen down to Tab 1 screen 1, with all initial screens of each tab getting the param through **this.props.navigation.state.params**. 

I have created an example app at this repo here to replicate the behaviour, and so you can see how my code is set up:
https://github.com/mishacajic/passing-params-demo

### Current Behavior
- Prior to react-navigation 1.0.0-beta.22, this behaved as expected, and the user object would be passed from the Login page to all the tabs and their initial screens.
- Since this version, I get a **this.props.navigation.state.params.user is undefined** error.
- The current system works only if the tab screens are just single screens, instead of nested stack navigators. But obviously, this shouldn't be an issue

### Expected Behaviour
- Since beta 23 includes some fixes relating to deep linking, that solved some problems with double mounting of a component, I would like to be up to date with this current version. However, I can't because of this issue that was introduced in beta 22. The behaviour should be as it was before, with params passed from the root navigator being passed down to the stacks nested within the tabs.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |1.0.0-beta.21
| react-native     |0.50.3
| node             |8.3.0
| npm or yarn      |5.6.0

**Comment by spencercarli** [comment]
Thanks for opening this issue @mishacajic! I think this bug was introduced in #3094, which lines up with which versions work and which ones don't.

I _think_ the issue is that the params are passed on the tab navigator's initial render but those params are never passed because only the init action would be called on the tab navigator, which doesn't handle params.

Would the solution be to pass params on init? Or to dispatch an action with the appropriate params?

cc @Ashoat

**Comment by Ashoat** [comment]
I do not think this is a bug.

The behavior that was removed in #3094 was that the params from the very first action would be pulled and placed in every single screen. I don't think this was ever intended behavior. Besides being undocumented, it only worked with the very first action, and it strikes me as a poor way to sharing global information throughout your application.

My interpretation is that the old behavior was unintentional and that we should not have params from the first action leak into route initialization.

I think a more idiomatic solution would be to use a Redux store to share your user object. Alternately, you could just set it as a global variable somewhere.

**Comment by Ashoat** [comment]
"Pass params on init" would certainly be a cleaner solution than "params on first action get passed to init on every descendant". That said, I don't see a strong reason why we need to solve the generic "global state" problem in this library.

**Comment by mishacajic** [comment]
Hi @Ashoat 
That makes sense to me. Sharing something as important as the user object throughout the app using the router is probably a bit messy, and it did strike me as such while I was developing. I'll take your suggestion and use a Redux store for it instead.

Cheers!

**Comment by spencercarli** [comment]
Speaking with @mishacajic off GH he fixed the issue - it was unrelated to React Navigation.
