### ISSUE TITLE
clear stack when navigating to nested stack navigator inside drawer navigator

### ISSUE THREAD

**Issue by connercms** [react-navigation/react-navigation#3254]
### Current Behavior
My react-native application consists of a DrawerNavigator that contains several StackNavigators. A simplified example of my structure looks like this

- Drawer
  - Stack 1
    - Screen 1
    - Screen 2
  - Stack 2
    - Screen 1
    - Screen 2

My problem is the following: I am on Screen 1 of Stack 1. I navigate to screen 1 of Stack 2 using the Drawer. From Screen 1 of Stack 2 I navigate to Screen 2 of Stack 2 on the press of a button. I then navigate back to Stack 1 using the Drawer. I again return to Stack 2 using the Drawer. I am now on Screen 1 of Stack 2, but there is a back button in the header, and it appears that my current screen has just been placed on top of the old stack. Pressing it navigates me to Screen 2 of Stack 2, and pressing it again navigates me to Screen 1 of Stack 2.

### Expected Behavior
When navigating back to a stack in the drawer I would expect it to return me to the first item in the stack with a fresh stack - that is, with no back button, or to let me resume the stack from the screen it was at instead of just adding a screen on top of it. Is this the correct expected behavior or have I done something wrong? 

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | beta.21
| react-native     | .51
| node             | 8.1.4
| npm or yarn      | 5.0.3

**Comment by kelset** [comment]
Can you create a small Snack that repro the issue? I think it's something in your code.

**Comment by Dror-Bar** [comment]
Not sure if this will fix your problem, but have you considered the following method:
```
_navigateToNewStack() {
        this.props.navigation.dispatch(NavigationActions.reset({
            index: 0, key: null, actions: [NavigationActions.navigate({ routeName: 'Stack1' })]
        }));
}
```
You can also navigate to Stack2 in this manner, and you are able to send params. key: null is important to have here - do note that this will reset the stack.

**Comment by connercms** [comment]
@kelset Here is the bare minimum code to recreate the issue. I created this in expo but not sure how to share the repo as I've never used expo before.

To recreate the issue:
1. Press 'Navigate To Drawer Item 1 Screen 2'
2. Open Drawer
3. Select Item2 from Drawer
4. Open Drawer
5. Select Item1 from Drawer

You should now be back to 'Drawer Item 1 Screen 1', but there is a back button and if you press it, you 'go back' to 'Drawer Item 1 Screen 2', and if you press it again you go back to 'Drawer Item 1 Screen 1' 

```
import React, { Component } from 'react';
import { Text, View, StyleSheet } from 'react-native';

// or any pure javascript modules available in npm
import { DrawerNavigator, StackNavigator } from 'react-navigation' // 1.0.0-beta.23

class Screen1 extends Component {
  render() { 
    return (
    <View style={{alignItems: 'center',flex: 1, justifyContent: 'space-around'}}>
      <Text>Drawer Item 1 Screen 1</Text>
      <Text style={{margin: 10}} 
      onPress={() => this.props.navigation.navigate('Screen2')}>
      Navigate To Drawer Item 1 Screen 2
      </Text>
    </View>
    ) 
  }
}

class Screen2 extends Component {
  render() { return <Text>Drawer Item 1 Screen2</Text> }
}

class Screen3 extends Component {
  render() { return <Text>Drawer Item 2 Screen 2</Text> }
}

class Screen4 extends Component {
  render() { return <Text>Drawer Item 2 Screen 2</Text> }
}

const MyDrawer = DrawerNavigator({
  Item1: {
    screen: StackNavigator({
      Screen1: { screen: Screen1 },
      Screen2: { screen: Screen2 }
    })
  },
  Item2: {
    screen: StackNavigator({
      Screen3: { screen: Screen3 },
      Screen4: { screen: Screen4 }
    })
  }
})

export default class App extends Component {
  render() {
    return (
      <MyDrawer/>
    );
  }
}
```

**Comment by Dror-Bar** [comment]
@connercms
Have you tried my suggestion?

**Comment by connercms** [comment]
@Dror-Bar I don't know how I would implement that. All they are doing is opening an item from the drawer so there is no way to know what stack they will select

**Comment by Dror-Bar** [comment]
Right, you would need to use a custom menu for that (using contentComponent).

In your example, it would look like this:
```
const MyDrawer = DrawerNavigator({
  Item1: {
    screen: StackNavigator({
      Screen1: { screen: Screen1 },
      Screen2: { screen: Screen2 }
    })
  },
  Item2: {
    screen: StackNavigator({
      Screen3: { screen: Screen3 },
      Screen4: { screen: Screen4 }
    })
  },
{ contentComponent: MyMenu } // MyMenu is your custom menu
})
```
In MyMenu just add some touchables and apply my method, depending on which screen the user presses on. I hope this makes sense?

**Comment by kelset** [comment]
> I created this in expo but not sure how to share the repo as I've never used expo before.

You can use [Snack](https://snack.expo.io/)

**Comment by connercms** [comment]
@kelset https://snack.expo.io/rk2HV-HNf

**Comment by connercms** [comment]
@Dror-Bar https://snack.expo.io/ByZgHrB4f I tried your suggestion but just get an error. Maybe look it over and see if that is what you meant or if ive done it wrong

**Comment by Dror-Bar** [comment]
Sorry for the delayed response.
Try the following:
1) Give DrawerComponent class a constructor:
```
constructor(props) {
        super(props);
}
```
Also, you might want to give a constructor to your other screens. I'm not sure if it's necessary though, it's just common to have that on the main classes since we often use props and state.

2) Try to bind the navigateToScreen method:
```
<TouchableOpacity onPress={() => this.navigateToScreen.bind(this, 'Item1')}>
      <Text>Item1</Text>
</TouchableOpacity>
```

**Comment by connercms** [comment]
@Dror-Bar I tried both those suggestions and I just get error 'There is no route defined for key (routeName that I pass). Must be one of (key of navigator that I am currently in).' So ex. I am in Stack1 and try to navigate to Stack2 using this code 
```
navigateToScreen = routeName => {
    const navigateAction = NavigationActions.reset({
      index: 0,
      actions: [NavigationActions.navigate({ routeName: 'Stack2' })]
    })
    this.props.navigation.dispatch(navigateAction)
  }
```
It will say 
> There is no route defined for 'Stack2'. Must be one of 'Stack1'.

**Comment by Dror-Bar** [comment]
You for forgot key: null, which I mentioned is important. Try again with this:

```
navigateToScreen = routeName => {
    const navigateAction = NavigationActions.reset({
      index: 0,
      key: null,
      actions: [NavigationActions.navigate({ routeName: 'Stack2' })]
    })
    this.props.navigation.dispatch(navigateAction)
  }
```

**Comment by connercms** [comment]
@Dror-Bar  Sorry, I tried that also. I also tried using key: routeName as suggested in another post somewhere in these threads but neither worked :/

**Comment by Dror-Bar** [comment]
Strange.

> There is no route defined for 'Stack2'. Must be one of 'Stack1'.

This means you don't have Stack2 defined as one of the routes for your DrawerNavigator. Are you sure your structure is like this?
```
const MyDrawer = DrawerNavigator({
  Stack1: {
    screen: StackNavigator({
      Screen1: { screen: Screen1 },
      Screen2: { screen: Screen2 }
    })
  },
  Stack2: {
    screen: StackNavigator({
      Screen3: { screen: Screen3 },
      Screen4: { screen: Screen4 }
    })
  }
},
```
Here both Stack1 and Stack2 should be viable routes.

**Comment by shubhamtaunk** [comment]
Stuck with this issue.
@connercms Any updates? Have you resolved this?

**Comment by Dror-Bar** [comment]
I'm sorry it didn't work out. I'm using the same react-navigation version as you, but my structure is different. Instead of this:
```
const MyDrawer = DrawerNavigator({
  Stack1: {
    screen: StackNavigator({
      Screen1: { screen: Screen1 },
      Screen2: { screen: Screen2 }
    })
  },
  Stack2: {
    screen: StackNavigator({
      Screen3: { screen: Screen3 },
      Screen4: { screen: Screen4 }
    })
  }
}
```
I have this:
```
const RootNavigator = StackNavigator({
  Login: {
      screen: Login 
    },
  Drawer: {
      screen: Drawer
      navigationOptions: { header: null } // prevent double header
    }
```
**Drawer** is a DrawerNavigator, it has only one screen which is another StackNavigator (this is why I need to prevent double header).

I can navigate from Login screen to Drawer and from any screen inside Drawer to Login with the method I suggested, and the stack is cleared. Perhaps you could test this and change your structure somehow. If not, I'm sorry I cannot afford any additional help.

**Comment by dccarmo** [comment]
Have the same problem with a similar implementation. I thought nesting Navigators would help "fix" this, but it's still happening.

The issue with @Dror-Bar solution is that `NavigationActions.reset` doesn't animate the transition.

@kelset is this expected or are we doing something wrong?

**Comment by connercms** [comment]
Still need to dive into it a little more, but I think 1.0.0 beta 28 seems to have fixed this.

**Comment by brentvatne** [comment]
i updated the version in the snack you linked to above @connercms and the issue appears to be resolved: https://snack.expo.io/rkyVjE0wG

thanks for following up here!

**Comment by p3ym4n** [comment]
I think the solution is to name the Stack name as the key prop & the inner screen as the routeName.
something like this : 
```javascript
const actionToDispatch = NavigationActions.reset({
	index: 0,
	key: "Stack2",
	actions: [
		NavigationActions.navigate({routeName: "screen3"}),
	],
});
this.props.dispatch(actionToDispatch);
```

**Comment by daybreaker** [comment]
@p3ym4n I'm doing this in mine, but it isn't resetting correctly.

I have a bottomTabNavigator with 3 screens. Each screen is a StackNavigator.

If I'm on Tab1, and go Tab1Screen1->Tab1Screen2->Tab2Screen1 by doing:

```
const actionToDispatch = NavigationActions.reset({
	index: 0,
	key: "Tab2",
	actions: [
		NavigationActions.navigate({routeName: "Tab2Screen1"}),
	],
});
this.props.dispatch(actionToDispatch);
```

If I use the bottom navigator to go back to Tab1, it's still on Tab1Screen2, but I need that to reset as well.

Any ideas?

**Comment by agrass** [comment]
Hi
I'm still having issue, already tried different solutions from this issues but nothing actually reset my drawerNavigator. 

I'm using this way:

```createDrawerNavigator({home: {screen: HomeScreen}, user: {screen: UserScreen}})```

and then 

```this.props.navigation.dispatch(StackActions.reset({index: 0, actions:[NavigationActions.navigate({routeName: 'user'})]});```

**Comment by elisegriset92** [comment]
Hello, stuck with the same problem in react navigation v5. Does anyone have a working solution ? Thanks

**Comment by Dror-Bar** [comment]
@elisegriset92 
This thread is 2 years old.
Have you read the official docs? in particular [Nesting navigators](https://reactnavigation.org/docs/nesting-navigators).

Perhaps you need something like this:

```
navigation.navigate('Root', {
  screen: 'Settings',
  params: {
    screen: 'Sound',
    params: {
      screen: 'Media',
    },
  },
});
```

Otherwise, there are more examples there.

**Comment by elisegriset92** [comment]
Thanks @Dror-Bar I've tried everything in the docs and unfortunately nothing works...  I don't know what's wrong with my stacks but indeed anytime I go from screen 3 of stack A  to another screen on stack B and try to go back to stack A from the drawer, it shows me the screen 3 instead of 1

**Comment by celciusjj** [comment]
Same issue here
