### ISSUE TITLE
Navigating with deep links causes issue with nested navigators

### ISSUE THREAD

**Issue by alexmngn** [react-navigation/react-navigation#3260]
### Current Behavior
I am attempting to set up deep links with react-navigation, but I found a bug when you have too many nested navigators.

I'm able to reproduce the issue with the following code at the root level of the app:

```
import { View, Text, Linking } from 'react-native';
export default StackNavigator(
  {
    A: {
      screen: StackNavigator(
        {
          B: {
            screen: StackNavigator(
              {
                C: {
                  screen: () => (
                    <View style={{ flex: 1, backgroundColor: 'red' }}>
                      <Text style={{ marginTop: 100 }} onPress={() => Linking.openURL('myapp://d')}>
                        Navigate to D
                      </Text>
                    </View>
                  ),
                  path: 'c',
                },
              },
              {
                initialRouteName: 'C',
                headerMode: 'none',
              },
            ),
            path: 'b',
          },
        },
        {
          initialRouteName: 'B',
          headerMode: 'none',
        },
      ),
      path: 'a',
    },
    D: {
      screen: StackNavigator(
        {
          E: {
            screen: () => (
              <View style={{ flex: 1, backgroundColor: 'blue' }}>
                <Text style={{ marginTop: 100 }} onPress={() => Linking.openURL('myapp://a')}>
                  Navigate to A
                </Text>
              </View>
            ),
            path: 'e',
          },
        },
        {
          initialRouteName: 'E',
          headerMode: 'none',
        },
      ),
      path: 'd',
    },
  },
  {
    initialRouteName: 'D',
    headerMode: 'none',
  },
);
```

The initial route is D, which displays E screen (blue).
When I try to navigate from E to A (then B, then C as initialRouteName) using a deep link with `Linking.openURL`, I get a red screen. Using the command lines `xcrun simctl openurl booted myapp://a` does the same.

![screen_shot_2018-01-11_at_18_08_42](https://user-images.githubusercontent.com/4203845/34840394-ce31475e-f6fc-11e7-947d-ab346564ad76.png)

However, if I replace the deep link with a regular navigation, everything works fine:

```
screen: () => (
   <View style={{ flex: 1, backgroundColor: 'blue' }}>
      <Text style={{ marginTop: 100 }} onPress={() => props.navigation.navigate('A')}>
         Navigate to A
      </Text>
   </View>
),
```

Another thing, if I decide to set the root initialRouteName to 'A' instead of 'D', it renders A properly. Clicking the link with the deep link to navigate to D works fine. Then clicking A to navigate to A throw the same error. 

### Expected Behavior
Navigating with deep linking should work with nested navigator.
It seems like when there are more than 2 levels of nested navigators, react-navigation can't handle deep links anymore.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.23
| react-native     | 0.51.0
| node             | 8.4.0
| npm or yarn      | yarn

**Comment by kelset** [comment]
Possibly duplicate of https://github.com/react-navigation/react-navigation/issues/1950, can you please check that one and close this if that's the case? I want to reduce the redundancy.

**Comment by alexmngn** [comment]
Seems to be the same issue you're right.
PR: https://github.com/react-navigation/react-navigation/pull/2982
