### ISSUE TITLE
Animate TabBar based on TabView swipe position

### ISSUE THREAD

**Issue by Druux** [react-navigation/react-navigation#3264]
### Current Behavior
My custom TabBar has to have different background colors, tint colors and font sizes for some tabs. Therefore I would really like to animate my TabBar icons / labels based on the current swipe position of `TabViewAnimated`. If I don't interpolate the style based on the swipe position, it will result in a delayed re-render of the TabBar content and styles.

What I basically want to is this:
![nav](https://user-images.githubusercontent.com/9655723/34864714-eff82082-f775-11e7-8b25-3df1a545ae0b.gif)
Credits and copyright goes to https://dribbble.com/shots/3799265-Swipe-navigation, Steffen Nørgaard Andersen.

### Expected Behavior
Currently there is no possibility for me to perform animations during the swipe.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^1.0.0-beta.13
| react-native     |  0.51.0
| node             | 9.3.0
| npm or yarn      | 5.6.0

**Comment by brentvatne** [comment]
please re-post to https://react-navigation.canny.io/feature-requests if this is important for you. re-organizing issues to focus on bug reports here and feature requests on canny. thanks!
