### ISSUE TITLE
StackNavigator navigate to screen like modal

### ISSUE THREAD

**Issue by flarocca** [react-navigation/react-navigation#3273]
[StackOverflow question](https://stackoverflow.com/questions/48253357/react-navigation-default-background-color)

# Short description: 

- I want to navigate to a screen (lets call it screen A) without lossing the previous screen (lets call it screen B) so the screen A plays as a modal form and keeps the screen B in the background.

# Full description: 

I'm using stack-navigator to manage my screens.

I have a screen, ***which acts as a modal form*** but it is really a full screen. Why is it important the part of ***"acts as a modal form"***? That's because it is kind of modal menu with some options and **WITH A TRANSPARENT BACKGROUND COLOR**. 

This is what I expect:
----------------------

[![Expectation][2]][2]

But what I'm getting is this:
-----------------------------

[![Reality][3]][3]

As you can see, in the second example the background color is completely replaced or the components previously loaded is unmounted so the effect I want to acchieve is lost.
***The idea is to be able to navigate to this screen like any other screen: *** `this.props.navigation.navigate('ScreenA', ...params);`

This component executes actions (redux) since is a cross app component and encapsulates lot of mechanisms and logic inside, that's why I can't use it as a `PureComponent` relaying on the component which makes use of this one. At least, making this Component as PureComponent would force me to replicate many mechanisms and logic in many other components.

For the sake of the question, and to avoid making the question enormous, both screens have exactly the same style, but the one pushed through `StackNavigation` seems to be unmounting the previous screen.

This is what I've have so far:

    //PlaylistSelector.js
    render() {
      //Just a full size empty screen is useful for replicating the behavior
      
      return (
        <View style={{ flex: 1, backgroundColor: 'transparent' }}/>
      );
    }

    //Navigator.js
    import { StackNavigator } from 'react-navigation';
    
    import Album from './Album'; //This is the screen I expect to keep at the background
    import PlaylistSelector from './PlaylistSelector'; //This is the screen I expect to render over Album screen to get the illusion of a modal menu.
    
    const AppNavigator = StackNavigator(
        {
            ...moreScreens,
            Album: { screen: Album },
            PlaylistSelector: {
                screen: PlaylistSelector,
                navigationOptions: {
                    //Does not work, red is just to ilustrate, should be transparent
                    style: { 
                        backgroundColor: 'red' 
                    },
                    //Does not work
                    cardStyle: {
                        backgroundColor: 'transparent'
                    },
                    //Does not work
                    bodyStyle: {
                        backgroundColor: 'transparent'
                    }
                }
            }
        },
        {
            initialRouteName: 'Splash',
            headerMode: 'none',
            //Does not work
            cardStyle: { 
                backgroundColor: 'transparent',
            },
            //Does not work
            transitionConfig: (): Object => ({ 
                containerStyle: {
                    backgroundColor: 'transparent',
                },
            }),
        }
    );
    
    export default AppNavigator;

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.11
| react-native     | 0.47.1
| node             | 5
| npm or yarn      |

  [2]: https://i.stack.imgur.com/WAz6q.png
  [3]: https://i.stack.imgur.com/YqW0Z.png

**Comment by kelset** [comment]
1. you are using a really old version of the lib, have you tried upgrading?
1. to get a modal you need to set the mode modal [in the config](https://reactnavigation.org/docs/navigators/stack#Modal-StackNavigator-with-Custom-Screen-Transitions)
1. there's a PR that would feature another way to get what you need https://github.com/react-navigation/react-navigation/pull/2308, feel free to provide your feedback on that approach there.

**Comment by shekharskamble** [comment]
@flarocca did the fix from @kelset worked for you? I am having the exact same issue.

**Comment by flarocca** [comment]
I havent had the chance yet.

**Comment by shekharskamble** [comment]
Still happening 

"react-native": "0.49.3"
"react-navigation": "1.0.0-beta.26"

**Comment by flarocca** [comment]
@kelset I've updated to the latest and I've also tested what you sugested. 
The problem is still there.

Any sugestion?

**Comment by quadsurf** [comment]
@flarocca  @kelset  I can confirm that the same issue exists for me too... the most common use of a modal is one where it partially overlays on top of the prior screen or background screen, so I'm not even sure why a less-common full-screen modal is the default... I understand that iOS does things that way, but no one else does... not modals on the web, not modals on Android, so I don't think iOS defaults should dictate React Navigation defaults

on a separate note @kelset ... the docs claim that the default animation for a modal is supposed to be 'bottomToTop' ... but whether I rely on the default, or declare the transition's direction explicitly, it still always flies the modal in from the right... can you please help? here is my setup:

```
const ModalNavigator = StackNavigator(
  {
    Root: { screen:Claims }
  },
  {
    initialRouteName: 'Root',
    headerMode: 'none',
    mode: 'modal',
    direction: 'bottomToTop',
    navigationOptions: {
      gesturesEnabled: true
    }
  }
)

const RootStack = StackNavigator(
  {
    Root: { screen: AuthState },
    LoggedOut: { screen: Login },
    LoggedIn: { screen: TabNav },
    Messages: { screen: Messages },
    Claims: { screen: ModalNavigator }
  },
  {
    initialRouteName: 'Root',
    headerMode: 'none'
  }
)
```

**Comment by TheDutchCoder** [comment]
As a workaround you could write your own component that is basically just an absolutely positioned `View` with a semi-transparent background and show it on a state change.

That's how I currently use it.

The downside is that it's not part of the navigation stack, so you can't easily navigate to it from other navigation points.

**Comment by brentvatne** [comment]
I have a stub for documentation around this if anyone would like to help! https://github.com/react-navigation/react-navigation.github.io/blob/source/docs/partial-overlay.md

@TheDutchCoder's solution is good right now. we may explore supporting other types of modals directly within StackNavigator at some point, but for now it only supports full screen modals. I tried to make this clear from the new docs section: https://reactnavigation.org/docs/modal.html

**Comment by rashmitaparia** [comment]
I am facing same issue.
![simulator screen shot - iphone 8 - 2018-02-08 at 15 03 48](https://user-images.githubusercontent.com/32276954/35969513-19fb7f64-0ced-11e8-96e5-1063351de16e.png)


when app launch first time view of previous screen is visible but when close this screen and open again a white blank screen shows.

any suggesstion ??
