### ISSUE TITLE
SafeAreaView doesn't work with modal StackNavigator

### ISSUE THREAD

**Issue by ethanyuwang** [react-navigation/react-navigation#3276]
## The issue tracker is reserved for bug reports only.

---

### Current Behavior

My app currently has this following StackNavifator structure:

```
const GleverScreens = StackNavigator({
  Welcome: { 
    screen: Welcome
  },
  Resumes: { 
    screen: Resumes,
  },
}
{
  headerMode: 'none',
});

const GleverTop = StackNavigator({
  GleverScreens: { 
    screen: GleverScreens
  },
  Autocomplete: {
    screen: Autocomplete
  },
},
{
  headerMode: 'none',
  mode: 'modal',
});
```
There's a custom header using absolute positioning within a SafeAreaView in Autocomplete screen. However, the header overlaps with the status bar:
![simulator screen shot - iphone 8 - 2018-01-15 at 14 38 28](https://user-images.githubusercontent.com/17556945/34964300-c3a60b0a-fa01-11e7-9b1a-1c966159d5cf.png)

if I move Autocomplete to the inside of GleverScreens (changing from "modal" to regular behavior) The overlapping disappears
<img width="462" alt="screen shot 2018-01-15 at 2 33 39 pm" src="https://user-images.githubusercontent.com/17556945/34964331-f3d00cd6-fa01-11e7-8c10-53ce7eb01f8f.png">
:

### Expected Behavior

the absolute positioned custom header should be right under the status bar.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  v1.0.0-beta.26
| react-native     | 0.51.0
| node             | v6.11.3
| npm or yarn      | 4.6.1

**Comment by kelset** [comment]
Have you checked the [release notes](https://github.com/react-navigation/react-navigation/tree/v1.0.0-beta.26) for `beta.26`?

Because the statusbar behaviour changed.

**Comment by just4fun** [comment]
@kelset - `beta.26` also doesn't work for me.

**Comment by ocarreterom** [comment]
Try to set `Autocomplete` screen in a new stack:
```js
const GleverTop = StackNavigator({
  GleverScreens: { 
    screen: GleverScreens
  },
  AutocompleteStack: {
    screen: StackNavigator({
      Autocomplete: {
        screen: Autocomplete
      },
    }),
  },
},
{
  headerMode: 'none',
  mode: 'modal',
});
```

**Comment by kelset** [comment]
We have a PR in the pipeline which may solve this https://github.com/react-navigation/react-navigation/pull/3452 check it out

**Comment by brentvatne** [comment]
hi there! if this is still a bug can you create a new issue that reproduces the bug on https://snack.expo.io? thanks!

(i expect to have to scan the example from snack.expo.io on my iphonex to test it, that's fine!)

**Comment by mtt87** [comment]
I'm still experiencing this issue, on `1.2.1` but it's been like this at least since `1.0`
It works when you immediately reset the app `CMD+R`
<img width="378" alt="screen shot 2018-03-02 at 15 08 07" src="https://user-images.githubusercontent.com/2150927/36902659-8d881e84-1e2b-11e8-90a8-f07552e46d23.png">
Then broken
<img width="376" alt="screen shot 2018-03-02 at 15 01 44" src="https://user-images.githubusercontent.com/2150927/36902640-7f89df7a-1e2b-11e8-8fa1-5b5b56536814.png">

In my app I can reproduce it 100% of the times if I do these steps:
- I'm on the 1st Tab screen
- I go on the 3rd Tab screen
- I open a root route (modal) and it works fine
- I go back to the 1st Tab screen
X In the 1st Tab screen (which is a StackNavigator itself) I navigate to a route, this seem to be the action that breaks everything, if I don't open this route I can always switch between the tabs and open the modal and it's fine, as soon as I open a route on any StackNavigator in my Tabs then it breaks.
- I go on the 3rd Tab screen
- I open a root route (modal) and now it's broken.

As soon as I have a moment I'll try to reproduce on Expo (I'm not really used to it tbh) in the meantime is there something that I can do to help debug?

My routes looks more or less like this:
```js
const Tab1 = StackNavigator({ ...});
const Tab2 = StackNavigator({ ... });
const Tab3 = StackNavigator({ ... });
const TabScreens = TabNavigator( 3 tabs );
const RootScreens = StackNavigator(
  {
    AppScreens: {
      screen: TabScreens,
      navigationOptions: defaultNavigationOptions,
    },
    ChangeLanguage,
    ChangeCity,
    ...other routes
  {
    mode: 'modal',
    header: null,
    headerMode: 'none',
    initialRouteName,
  },
);
return <RootScreens />;
```

**Comment by brentvatne** [comment]
thanks @mtt87! using https://snack.expo.io should be no different than locally, looking forward to seeing what is causing this

**Comment by Soweyln** [comment]
Same issue here. Any updates?

**Comment by mtt87** [comment]
@Soweyln they kindly asked to reproduce on snack.expo.io, which I didn't have time to do yet.
Do you wanna do it? 😄

**Comment by ethanyanjiali** [comment]
i run into same issue and made a expo reprop here:
https://snack.expo.io/rkGN36_Kf

Note the the top button after you open the modal, it overlapped with status bar even though I use SafeAreaView for modal screen

src code:
```javascript
import React, { Component } from 'react';
import { DrawerNavigator, StackNavigator, SafeAreaView } from 'react-navigation';
import { Text, StyleSheet, Button } from 'react-native';
import { Constants } from 'expo';

class Modal extends Component {
  _handleButtonPress = () => {
    const { navigation } = this.props;
    navigation.goBack();
  };

  render() {
    return (
      <SafeAreaView style={styles.modalContainer}>
        <Button
          title="Dangerous Button X"
          onPress={this._handleButtonPress}
        />
        <Text style={styles.paragraph}>
          Pull down to close Modal
        </Text>
      </SafeAreaView>
    );
  }
}

class Home extends Component {
  render() {
    const { navigation } = this.props;
    return (
      <SafeAreaView style={styles.container}>
        <Button title="Open Modal" onPress={ () => navigation.navigate('B') }>
        </Button>
      </SafeAreaView>
    );
  }
}

const AppNavigator = DrawerNavigator({
  C: { screen: Home },
});

const ModalNavigator = StackNavigator({
  A: { screen: AppNavigator },
  B: { screen: Modal },
}, {
  mode: 'modal',
  headerMode: 'none',
});

export default ModalNavigator;

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: Constants.statusBarHeight,
    backgroundColor: '#ecf0f1',
  },
  modalContainer: {
  },
});
```

**Comment by Soweyln** [comment]
@brentvatne could you take a look when you have some time? @ethanyanjiali has posted the snack

**Comment by Soweyln** [comment]
SafeAreaView works well on iphone x, but overlaps with status bar on previous models. @brentvatne

**Comment by brentvatne** [comment]
you have two ways to work around this:
- use `forceInset={{top: 'always'}}`
- only render the safeareaview when the transition has completed https://snack.expo.io/SJdNHhZ5M (the safeareaview doesn't know it will be at the top of the screen when it renders during the animation, so it doesn't apply the padding)

if you want to try to fix the issue upstream in react-navigation: https://github.com/react-community/react-native-safe-area-view
