### ISSUE TITLE
Tab bar doesn't hide if status bar is shown and translucent is true when keyboard appears

### ISSUE THREAD

**Issue by YusufHussien** [react-navigation/react-navigation#3283]
### Current Behavior
- _If I press on text input and the keyboard appears the tab bar on the bottom doesn't disappear if the status bar is shown and translucent is set to true_

- _If I press on text input and the keyboard appears the tab bar on the bottom disappears if the status bar is not shown and translucent is set to false_

### Expected Behavior
- _Tab bar should disappear in both cases_

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 0.0.26
| react-native     | 52.0.0

**Comment by brentvatne** [comment]
moved to https://github.com/react-navigation/react-navigation-tabs/issues/16
