### ISSUE TITLE
Position of labels is incorrect after upgrading to 1.0.0-beta.26

### ISSUE THREAD

**Issue by lewistaylor** [react-navigation/react-navigation#3286]
### Current Behavior
Upgrading from 1.0.0-beta.25 to 1.0.0-beta.26 causes odd styling issues in TabNavigation.

Code is as follows:

```
const MainNavigator = TabNavigator(
  {
    [routeNames.venueTabs.information]: { screen: VenueInformation },
    [routeNames.venueTabs.fixtures]: { screen: VenueFixtures },
    [routeNames.venueTabs.offers]: { screen: VenueOffers },
  },
  {
    tabBarComponent: TabBarTop,
    tabBarPosition: 'top',
    animationEnabled: true,
    swipeEnabled: true,
    tabBarOptions: {
      activeTintColor: '#000000',
      inactiveTintColor: '#333333',
      style: {
        backgroundColor: theme.colors.mpYellow,
      },
      indicatorStyle: {
        backgroundColor: 'black',
      },
      upperCaseLabel: false,
    },
  },
);
```
<img width="313" alt="screen shot 2018-01-16 at 18 38 24" src="https://user-images.githubusercontent.com/497206/35005765-77208936-faec-11e7-92fc-37bfc1eee414.png">

### Expected Behavior

The tabs should look as they do in beta-25.
<img width="317" alt="screen shot 2018-01-16 at 18 34 09" src="https://user-images.githubusercontent.com/497206/35005766-78f6bb36-faec-11e7-90b9-450020e5e40d.png">

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.26
| react-native     | 0.52.0
| node             | v9.2.0
| npm or yarn      | yarn 1.3.2

**Comment by satya164** [comment]
https://github.com/react-navigation/react-navigation/pull/3285

cc @brentvatne

**Comment by brentvatne** [comment]
ok looks like I need to rollback a change, will do this shortly

**Comment by brentvatne** [comment]
fixed in alpha.27, sorry for the hassle
