### ISSUE TITLE
Get screenProps of nested navigator

### ISSUE THREAD

**Issue by Druux** [react-navigation/react-navigation#3288]
### Current Behavior
My Navigator looks like this:
```
StackNavigator (main)
|---- StackNavigator (user)
|-------- TabNavigator (profile, friends)
```
What I am trying to do is to have access to the screenProps / navigationOptions of the `TabNavigator` screen profile screen in the friends screen. Or basically from anywhere else.

I tried a lot with e.g.
```
const screenNavigation = addNavigationHelpers({
            state: props.navigation.state.routes[0].routes[0],
            dispatch: props.navigation.dispatch,
        });
```
Which (obviously?) doesn't work.

### Expected Behavior
I am expecting to get access to the screenProps of any other screen at any point in the navigator.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^1.0.0-beta.26
| react-native     | 0.51.0
| node             | 9.3.0
| npm      | 5.6.0

**Comment by brentvatne** [comment]
please re-post to https://react-navigation.canny.io/feature-requests if this is important for you. re-organizing issues to focus on bug reports here and feature requests on canny. thanks!

**Comment by brentvatne** [comment]
changed my mind, this is a bug

**Comment by superburrito** [comment]
Ehh @Druux I'm not sure what you mean. Aren't `screenProps` only passable to the root navigator? The screens in your nested navigators (i.e. `profile`/`friends`) should receive those `screenProps`.
