### ISSUE TITLE
Dynamic animate the screen view content using the DrawerNavigator position

### ISSUE THREAD

**Issue by obetomuniz** [react-navigation/react-navigation#3290]
I want to control the scale of the the screen view when the Drawer View is open using react-navigation with DrawerNavigator. 

![You can see the expected behavior here](https://i.stack.imgur.com/sEKRp.gif)

![kapture 2018-01-17 at 15 27 05](https://user-images.githubusercontent.com/1680157/35057078-fd3fd78e-fb9a-11e7-8cf4-def79a8afc4a.gif)

I'm not sure if is it possible, so suggestions using react-navigation are welcome.

**Comment by kelset** [comment]
I don't think this will be possible since the drawer is based on the Android guidelines and that behaviour is not consistent with material design.

**Comment by obetomuniz** [comment]
:( I did the example above using `react-native-side-menu` + `react-native-router-flux`. I need to test it in the Android Env. I'll do it today and back here to report.

**Comment by obetomuniz** [comment]
@kelset I just updated the issue description with the Android demo.

**Comment by brentvatne** [comment]
please re-post to https://react-navigation.canny.io/feature-requests if this is important for you

**Comment by esxph** [comment]
> :( I did the example above using `react-native-side-menu` + `react-native-router-flux`. I need to test it in the Android Env. I'll do it today and back here to report.

Hey can you share the code using react-native-side-menu and - router flux? Or did you find a way to put animations with DrawerNavigator? I'm new using react and js...
