### ISSUE TITLE
Drawer Item Custom Style

### ISSUE THREAD

**Issue by JayricMok** [react-navigation/react-navigation#3296]
How can set different style for active and inactive ? I only saw `activeTintColor ` and `inactiveTintColor ` , if want to set active with `fontWeight` bold and inactive keep normal `fontWeight , any idea ? Thanks.

**Comment by satya164** [comment]
Use a custom component with the `drawerComponent` option.

**Comment by matheusbaumgart** [comment]
Did you mean `drawerContent` @satya164? 
I'm using that but now can't tell which drawer screen is active :( 
Any ideas?

**Comment by matheusbaumgart** [comment]
Thanks to @satya164 I got it working with: `props.state.routes[props.state.index].name`
