### ISSUE TITLE
Custom export leads to crash with exception (0, _.Navigator) is not a function

### ISSUE THREAD

**Issue by Druux** [react-navigation/react-navigation#3299]
### Current Behavior
If I am importing the `StackNavigator` not directly via `react-navigation` it leads to an app crash.
My import looks like: 
```
// Navigator.js
import { StackNavigator } from './';

export default StackNavigator({   // <-- exception occurs here
    ...some routes
})
```
```
// index.js
...other imports
import { StackNavigator } from 'react-navigation';
...other imports

export {
    ...other exports
    StackNavigator
    ...other exports
}
```
If I am running this, the app is going to crash with the exception 
`(0, _.StackNavigator) is not a function`

I have already tried to implement the same export schema as you guys did (via `module.exports` getter) but without any success.
Am I missing something or is this a known issue?

### Expected Behavior
I am expecting to import and export the Navigators at any point in my app.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^1.0.0-beta.26
| react-native     | 0.51.0
| node             | 9.3.0
| npm      | 5.6.0

**Comment by Ajith-Pandian** [comment]
@Druux You should use `export default`

In your index.js
```js
// index.js
...other imports
import { StackNavigator } from 'react-navigation';
...other imports

export default {
    ...other exports
    StackNavigator
    ...other exports
}

**Comment by Druux** [comment]
@Ajith-Pandian already tried that - still the same issue

**Comment by Druux** [comment]
solved it by doing the following:
`export { StackNavigator } from 'react-navigation';`

**Comment by kelset** [comment]
Quick question, in which scenario you may want to import the StackNavigator not directly via react-navigation? 🤔

**Comment by Druux** [comment]
@kelset  Actually I wanted to wrap the `StackNavigator` to add additional props I need. Worked absolutely fine until I have faced the export / import issue I described. First I thought it is related to the custom `StackNavigator` I have just created, but then the issue occurred with the original `StackNavigator` as well.

closing the issue.
