### ISSUE TITLE
iPhoneX vs iPhone 7 and lower status bar not truly hidding

### ISSUE THREAD

**Issue by julesmoretti** [react-navigation/react-navigation#3306]
### Current Behavior
Despite adding `navBarHidden` in the navigarStyle of the HomeScreen of the desired screen the status bar is still occupying space which is problematic when designing between iPhone X and previous versions. iPhoneX taking 44pixel in height and others 20 (green zone of the attached screenshot)

Please see attached repo and following code:

https://github.com/julesmoretti/hiddenstatus
```
import React from 'react';
import { StyleSheet, Text, View, Button } from 'react-native';

class HomeScreen extends React.Component {
  static navigatorStyle = {
    navBarHidden: true,
    statusBarHidden: true,
    statusBarHideWithNavBar: true,
  };

  static navigationOptions = {
    title: 'Welcome',
  };

  render() {
    const { navigate } = this.props.navigation;
    return (
      <View
        style={{
          backgroundColor: 'blue',
          flex: 1,
          justifyContent: 'center',
        }}
      >
        <Button
          title="Go to Jane's profile"
          onPress={() =>
            navigate('Profile', { name: 'Jane' })
          }
        />
      </View>
    );
  }
}

export default HomeScreen;
```

### Expected Behavior
I would expect for that entire top zone above the header to not be there at all.

How can this be achieved properly, either at the screen level or through the` <StatusBar />` component? (I tried the `<StatusBar hidden />` with no success either.

Thank you.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^1.0.0-beta.25
| react-native     | 0.50.3
| node             | 7.0.0
| npm or yarn      | 4.6.1

![screen shot 2018-01-18 at 10 09 33 am](https://user-images.githubusercontent.com/744300/35113838-bda24e5c-fc37-11e7-82ae-f416205b56a3.png)

![screen shot 2018-01-18 at 10 09 25 am](https://user-images.githubusercontent.com/744300/35113844-c122e12c-fc37-11e7-8659-3b8e5166ffa0.png)

**Comment by kelset** [comment]
(I'm adding `needs more info` simply because I am not sure that's removable)

@brentvatne any idea how to 'remove' completely the green-ish area? (If I understood correctly that's what you want to achieve, right?)

**Comment by satya164** [comment]
There is no `navigatorStyle` option in React Navigation. Please check the docs on how to customize the header https://reactnavigation.org/docs/navigators/stack
