### ISSUE TITLE
Update to react-native@0.52 and flow-bin@0.61

### ISSUE THREAD

**Issue by Ashoat** [react-navigation/react-navigation#3307]
Creating this issue to track the work to upgrade us to RN@0.52 and flow-bin@0.61. These versions introduce 17 new type errors on my personal project.

Effort is currently blocked on the release of Expo v25, since the examples have to have the same RN version as the main package, and the examples are based on Expo.

**Comment by Ashoat** [comment]
@kelset please assign to me at your earliest convenience :)

**Comment by kelset** [comment]
(you can't assign it to yourself? 🤔)

**Comment by kelset** [comment]
Closing since https://github.com/react-navigation/react-navigation/pull/3383 was merged & released
