### ISSUE TITLE
Navigation can add the attribute replace() or pop().

### ISSUE THREAD

**Issue by jeasonHu** [react-navigation/react-navigation#3309]
### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.27
| react-native     | 0.52.0
navigation.goBack('key') can back to target Scene. but it depend on another Scene/page to pop from the stack. So. I wanna know Navigation can add the attribute replace() or pop() like Navigator!

**Comment by kelset** [comment]
Hi @jeasonHu!

I'm sorry but this issue is invalid: it's really hard to understand what you wrote and what you want to obtain. Please open a new one that follows the template.
