### ISSUE TITLE
TabNavigator tabBarOnPress is not invoked when selecting tab via andorid back button.

### ISSUE THREAD

**Issue by harikrishnanp** [react-navigation/react-navigation#3311]
TabNavigator tabBarOnPress is not invoked when selecting tab via andorid back button.
### Current Behavior
1) Click on 2nd tab in tab bar.
2) Click back button of android.
3) The first tab is selected. But `tabBarOnPress` event is not fired.

### Expected Behavior
1) Click on 2nd tab in tab bar.
2) Click back button of android.
3) The first tab is selected. `tabBarOnPress` event should get fired.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.23
| react-native     | 0.52.0
| node             | 9.3.0
|  yarn      |  1.3.2

**Comment by kelset** [comment]
1. can you provide a [Snack](https://snack.expo.io/) that reproduces the issue?
1. have you tried upgrading to the latest version of the lib? Is the issue still present?

**Comment by harikrishnanp** [comment]
2. Upgrading to the latest version didn't fix the issue.

**Comment by satya164** [comment]
As the name `tabBarOnPress` says, it is called when you press a tab in the tab bar. It's not called when you switch to a tab, whether via a swipe gesture or via android back button.

This is expected behaviour.
