### ISSUE TITLE
Navigation back event

### ISSUE THREAD

**Issue by MSSPL-PiyaleeMaiti** [react-navigation/react-navigation#3313]
### Current Behavior
- _when I back to the previous page by using navigation then I can't get any event so that I can reload or refresh the previous page if any needed_

### Expected Behavior
- _I need an event at navigation.goBack() and the event will be needed on the previous page so that it is known to me that after back where I stay, this features is so important for me._

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  ^1.0.0-beta.15
| react-native     |  0.44
| node             |  v6.11.5
| npm or yarn      |  3.10.10

**Comment by ericvicenti** [comment]
Hi, this issue isn't very clear. Can you post a code example and explain what is going wrong with it?

**Comment by MSSPL-PiyaleeMaiti** [comment]
I open my app and show **screen-1**, after that route to another page **screen-2** and do some action on that page. Then go back to the previous page **screen-1** and need to refresh that page **screen-1** so that I can get the updated value on **screen-1**. So I need an event on **navigation.goBack()** so that I can refresh the **screen-1** page on that event.

**Comment by Msspl-PrashenjeetRoy** [comment]
@ericvicenti Its a not specific syntax issue. Is it possible to pass data on go back function?
https://reactnavigation.org/docs/navigators/navigation-prop#goBack-Close-the-active-screen-and-move-back

**Comment by MSSPL-PiyaleeMaiti** [comment]
I made an example file for you to understand the scenario.
https://repl.it/@PiyaleeMaiti12/WelltodoSentimentalAnnashummingbird

Simply I need an event on the Home page to do something after coming back from the second route page.
I think this makes sense and it's enough to clear to you.

I was using Navigator in our project, they provide an event on componentWillReceiveProps on the back but in new react-navigation, on goBack() there are not more options to do. Please need some help on this.

**Comment by MSSPL-PiyaleeMaiti** [comment]
Hi @ericvicenti  Is there any solution to this issue??

**Comment by satya164** [comment]
https://github.com/react-navigation/react-navigation/pull/3345

**Comment by XcqRomance** [comment]
@MSSPL-PiyaleeMaiti I think you can use callback in navigate. just like below in screen-1
```
this.props.navigation.navigate(' screen-2 routerName',{params1:xxx, params2: xxx, callBack: (data) => {
                  console.log(data)
                  // refresh screen-1 data in here
}})
```
and in screen-2 ,just below
```
const {state} = this.props.navigation
state.params.callBack(data) 
goBack(null)
```

**Comment by MSSPL-PiyaleeMaiti** [comment]
@XcqRomance Your solution is working. But this is a temporary solution. 
Thanks, @XcqRomance  for your solution.

**Comment by iosdev-republicofapps** [comment]
But what about a callback **after** `goBack(null)` has completed.  For example, the equivalent of `viewDidAppear` in UIKit?  This would tell us when the parent screen was once again visible to the user after the `goBack` was finished transitioning the nav ... That would be very useful.  Is that not possible?
