### ISSUE TITLE
[BUG] Gap on top of nested TabNavigator in StackNavigator

### ISSUE THREAD

**Issue by BowgartField** [react-navigation/react-navigation#3314]
### Current Behavior
It a bug that happend when you nested a TabNavigtor in a StackNavigator. On the TabNavigator header above the tabs's name there is a bleu (default color in android) gap with blank.

### Expected Behavior
This gap should not exist because it useless.
To repdroduce it you juste have to nested a TabNavigator in a Stack Navigator and see.

### Your Environment
It happend just on android.

![screenshot_20180119-221724](https://user-images.githubusercontent.com/13118844/35172212-f7e495cc-fd66-11e7-8cde-a82e7eab2f71.jpg)

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.26
| react-native     | 0.50.3
| node             | v9.4.0
| yarn      | 1.3.2

**Comment by brentvatne** [comment]
update top beta.27
