### ISSUE TITLE
React is not defined

### ISSUE THREAD

**Issue by itanhduy** [react-navigation/react-navigation#3317]
### Current Behavior
When I'm using the tabBarIcon for TabNavigator. I got error "React is not defined"

![image](https://user-images.githubusercontent.com/10527554/35185445-2bd6afde-fe37-11e7-94af-0e663172766c.png)

### Expected Behavior
It should work and show the icon as expected

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^1.0.0-beta.27
| react-native        | https://github.com/expo/react-native/archive/sdk-24.0.0.tar.gz
| node                    | v8.9.4
| npm or yarn        | yarn

**Comment by tamhv** [comment]
i guess you're missing

`import React from 'react'`

**Comment by kelset** [comment]
Can you please share your code? As @tamhv stated, it's probably because you are missing some imports.

But it's quite weird tbh, could you try maybe to create a repro with [Snack](https://snack.expo.io/)?

**Comment by dnlek** [comment]
👍 
I have similar issue. I can use icons in other places but when using in tabBarIcon it fails with error.

![image](https://user-images.githubusercontent.com/547490/35219258-2fb1f2da-ff72-11e7-9d0d-4a21aa5b9d46.png)

```
import Ionicons from 'react-native-vector-icons/Ionicons';

LaunchScreen.navigationOptions = {
  tabBarLabel: 'Map',
  tabBarIcon: ({ tintColor, focused }) => (
    <Ionicons name='ios-home' fontSize={26} style={{ color: tintColor }} />
  )
}

// Manifest of possible screens
const TabNav = TabNavigator({
    Main: {
      screen: LaunchScreen
    },
    Profile: { screen: ProfileScreen }
}, {
    headerMode: 'none',
    initialRouteName: 'Map',
    navigationOptions: {
        headerStyle: styles.header
    }
});
```

**Comment by tamhv** [comment]
@dnlek your code is missing `import React from 'react'`
```

import React from 'react
import Ionicons from 'react-native-vector-icons/Ionicons';

LaunchScreen.navigationOptions = {
  tabBarLabel: 'Map',
  tabBarIcon: ({ tintColor, focused }) => (
    <Ionicons name='ios-home' fontSize={26} style={{ color: tintColor }} />
  )
}

// Manifest of possible screens
const TabNav = TabNavigator({
    Main: {
      screen: LaunchScreen
    },
    Profile: { screen: ProfileScreen }
}, {
    headerMode: 'none',
    initialRouteName: 'Map',
    navigationOptions: {
        headerStyle: styles.header
    }
});
```

**Comment by dnlek** [comment]
@tamhv I am not using React in this file ... but ... I though I will give it a try and it actually helped :) 
Thanks!

**Comment by satya164** [comment]
@dnlek Any JSX code is transpiled to `React.createElement`, so you are using React here. e.g.-

`<Ionicons name='ios-home' />` -> `React.createElement(Ionicons, { name: 'ios-home' })`

Use https://github.com/yannickcr/eslint-plugin-react to catch these errors.

**Comment by dnlek** [comment]
Thanks @satya164 ! I don't know if it resolves @itanhduy issue but surely resolves mine :)

**Comment by itanhduy** [comment]
Thanks everyone. I will try the solution of @tamhv.

**Comment by ericgoe** [comment]
Isn't it possible to auto-import React ? Importing React in every file seems redundant to me
