### ISSUE TITLE
TabNavigator configureTransition() is an unused property?

### ISSUE THREAD

**Issue by Druux** [react-navigation/react-navigation#3319]
### Current behavior
`TabNavigator` `configureTransition()` prop doesn't affect the transition between the tabs. Even my IDE gives me a hint that the prop isn't used.

### Expected behavior
I expect to modify the behavior of the tab transitions as described in the docs.

### Code sample, screenshots
```
{
     ... other tab config
     configureTransition: (currentTransitionProps,nextTransitionProps) => ({
          timing: Animated.spring,
          tension: 1000,
          friction: 100,
     }),
     ... other tab config
}
```

### What have you tried
I have reviewed the implementation and figured out that it is going to be forwarded correctly to the `TabViewPagerPan` component. Since then there isn't any further usage of the function. The `transitionTo()` function, which is responsible for performing the transition (I suppose?) is based on the `DefaultTransitionSpec`.

`const { timing, ...transitionConfig } = DefaultTransitionSpec;`

Doesn't even work with the `react-navigation` sample: https://snack.expo.io/Sye_jJWSM

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^1.0.0-beta.26
| react-native     | 0.51.0
| node             | 9.3.0
| npm      | 5.6.0

**Comment by ericvicenti** [comment]
Correct, configureTransition is only a feature of StackNavigator. Its a bit confusing and I hope we can improve the API in the future. (I think @satya164 would be the best one to investigate this, as the owner of the tabs view and someone who has good ideas about improvements to transition config.)

@Druux, could you send in a PR to the new website/docs, to explain this current (not so ideal) situation?

https://github.com/react-navigation/website

**Comment by anton6** [comment]
So why does in documentation under TabNavigatorConfig "https://reactnavigation.org/docs/tab-navigator.html#tabnavigatorconfig" it says?:

configureTransition - a function that, given currentTransitionProps and nextTransitionProps, returns a configuration object that describes the animation between tabs.
