### ISSUE TITLE
Simple native functionality

### ISSUE THREAD

**Issue by samuelgjabel** [react-navigation/react-navigation#3322]
It would be nice if this library use some basic native options like push new screen and pop..Like deprecated navigatorIOS but for both platforms...... couse performance push / pop at stacknavigator isnt good enought... // usually on android

I mean if library use just native methods for pop/ push and other methods like tabs, swiping between tabs, etc  stay in JS based animations.

Anyway its possible? 

Just the idea what i welcome in next releases :p

**Comment by kelset** [comment]
This is a library that decided to go for a different approach to navigation, if you want to discuss how it evolves I suggest you do it [here](https://github.com/react-navigation/rfcs) or in the [roadmap issue](https://github.com/react-navigation/react-navigation/issues/2585).
