### ISSUE TITLE
[Android] TabNavigator RTL not working

### ISSUE THREAD

**Issue by cristijora** [react-navigation/react-navigation#3325]
### Current Behavior
- TabNavigator RTL behavior on Android is weird. The active tab is not displayed correctly.
- When navigating to the tabs on the left, the rightmost tab remains active and the text opacity changes.

![screen shot 2018-01-22 at 2 39 31 pm](https://user-images.githubusercontent.com/15955045/35221311-5745f020-ff82-11e7-9cdf-08dd04716dd1.png)
![screen shot 2018-01-22 at 2 39 22 pm](https://user-images.githubusercontent.com/15955045/35221485-f32901ee-ff82-11e7-9bbe-35e6365e324a.png)

### Steps to reproduce
```js
import {I18nManager, AppRegistry} from 'react-native';
import {StackNavigator, TabNavigator} from 'react-navigation';
I18nManager.forceRTL(true)
const HomeApp = TabNavigator({
  Main: {screen: Home},
  Shop: {screen: Shop},
  Cart: {screen: Cart},
  Account: {screen: Account},
});
AppRegistry.registerComponent('test', () => App);
```
Screens can be any component.

### Expected Behavior
- When tapping on tabs, the pressed tab should become active.

### Notes:
- Works properly on iOS
- Works properly on Android with react-navigation `<beta.19`

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.27 (seems to appear from >beta.20)
| react-native     | 0.52.0
| node             | 8.9.1
| npm or yarn      | yarn latest

**Comment by brentvatne** [comment]
@satya164 - any idea if this is a react-native-tab-view issue? beta.23 includes #3064

**Comment by satya164** [comment]
@brentvatne yes, RTL is not properly supported in react-native-tab-view. I'd accept PRs to fix it https://github.com/react-native-community/react-native-tab-view/issues/184

**Comment by brentvatne** [comment]
sounds good @satya164

**Comment by cristijora** [comment]
@brentvatne what about having react native tab vie as a peerDependency. It feels strange do downgrade react navigation because of react native tab view. If we have it as peerDependency, people can pick the version they want + react navigation will not depend on it so much

**Comment by brentvatne** [comment]
@cristijora - I think that won't work in practice because react-navigation depends an api contract with react-native-tab-view. It will be too fragile and we will have to provide a version compatibility table if not. You're welcome to fork TabNavigator to what you need though!

**Comment by ProMasoud** [comment]
this may help
this is not an answer to this problem but could help

```
import { TabNavigator, StackNavigator, NavigationActions, TabBarBottom } from 'react-navigation';
...

export const Tabs = TabNavigator(routeConfig,
{
  tabBarPosition: 'bottom',
  tabBarComponent: TabBarBottom, // add this line
});
```

**Comment by MehranAbghari** [comment]
+1

**Comment by hakemo26** [comment]
> just add flexDirection: 'row-reverse' as second parameter to TabNavigator or createBottomTabNavigator
> 
> like this:
> const TabNavigator = createBottomTabNavigator({
> ...
> }, {
> tabBarOptions: {
> activeTintColor: '#E61C4B',
> inactiveTintColor: 'gray',
> //showLabel: true,
> showLabel: (Platform.OS !== 'android'), //No label for Android
> labelStyle: {
> fontSize: 11,
> fontFamily: 'iransans',
> },
> style: {
> flexDirection: 'row-reverse', // here
> backgroundColor: '#fff',
> height: (Platform.OS === 'ios') ? 48 : 50
> },
> showIcon: true,
> }
> });

Like it works for me thank Mohandes ;)
