### ISSUE TITLE
Override Navigation padding added in beta-21

### ISSUE THREAD

**Issue by gregbenner** [react-navigation/react-navigation#3330]
## The issue tracker is reserved for bug reports only.

"react-navigation": "^1.0.0-beta.21" from "react-navigation": "^1.0.0-beta.20",

---

### Current Behavior
- ![screenshot from 2018-01-22 14-12-05](https://user-images.githubusercontent.com/1177690/35239445-7bcd1148-ff7e-11e7-8988-f110ecd887b5.png)

### Expected Behavior
 - same padding as previous minor version
- we can't override this without hacks it seems

### Your Environment
OSX High Sierra,
Ubuntu 17.10
Android V8
iOs multiple versions
EXPO SDK 24
^1.0.0-beta.21
RN 0.51
version 8 and 9
npm and yarn

**Comment by brentvatne** [comment]
do you mean beta 26? https://github.com/react-navigation/react-navigation/releases/tag/v1.0.0-beta.26

> If you would like to revert to the old behavior, you can use the following escape hatch:

```
import { Platform } from 'react-native';
import { SafeAreaView } from 'react-navigation';
if (Platform.OS === 'android') {
  SafeAreaView.setStatusBarHeight(0);
}
```

**Comment by fahadakhan96** [comment]
Hi! I'm new to React Native and cannot figure out where to put this code:
```javascript
import { Platform } from 'react-native';
import { SafeAreaView } from 'react-navigation';
if (Platform.OS === 'android') {
  SafeAreaView.setStatusBarHeight(0);
}
```
Should it be in the `componentWillMount` function of `App.js` or someplace else? I'd really appreciate it if someone could guide me.
