### ISSUE TITLE
performing navigation after app closes using backhandler fill the state.routes with extra routes

### ISSUE THREAD

**Issue by assafb81** [react-navigation/react-navigation#3334]
## The issue tracker is reserved for bug reports only.
I have a stack that looks like this:

**routes.js**
```
const mainStack = stackNavigator({
  SplashScreen: { screen: SplashScreenContainer },
  ScreenA: { screen: StackA }, // this one is stack navigator
  ScreenB: { screen: StackB }, // this one is stack navigator
  ScreenC: { screen: StackC }, // this one is tab navigator
})

export default mainStack;
```

**SplashScreenContainer.js**
```
...
componentDidMount() {
        this.props.initializeApp();
    }

    // navigating to the proper stack
    componentDidUpdate() {
        if (this.props.initialRouteName) {
            this.props.navigation.navigate(this.props.initialRouteName);
        }
        SplashScreen.hide();
    }
```
and my **navReducer.js** looks like:
```
import { NavigationActions } from 'react-navigation';
import MainStack from '../../routes/routes';

const initialState = MainStack.router.getStateForAction(NavigationActions.init());

export default (state = initialState, action) => {
  const nextState = MainStack.router.getStateForAction(action, state);
  return nextState || state;
}
```

and on handling android device back button in **AppWithNavigationState .js** is:
```
class AppWithNavigationState extends Component {
    static propTypes = {
        dispatch: PropTypes.func.isRequired,
        nav: PropTypes.object.isRequired,
    }

    componentWillMount() {
        BackHandler.addEventListener('hardwareBackPress', this.onBackPress);
    }

    componentWillUnmount() {
        BackHandler.removeEventListener('hardwareBackPress');
    }

    onBackPress = () => {
        const { dispatch, nav } = this.props;

        if (this.shouldCloseApp(dispatch, nav)) {
            return false;
        }

        dispatch({ type: 'Navigation/BACK' });
        return true;
    };

    shouldCloseApp = (dispatch, nav) => {
        if (nav.routes[1].routes.length === 1) {
             //for the splash screen did mount function
            dispatch({ type: UPDATE_INITIAL_ROUTE_SUCCESS, initialRouteName: '' }); 
            return true;
        }
        return false;
    }

    render() {
        const { dispatch, nav } = this.props;
        const navigation = addNavigationHelpers({
            dispatch,
            state: nav,
        });
        return <MainStack navigation={navigation} />;
    }
}
```

---

### Current Behavior
my nav object before closing (from **AppWithNavigationState.js**) looks like:
nav -> `{index: 1, routes: Array(2)}`
nav.routes[0] => `{routeName: "SplashScreen", key:"uniqeKey"}`
nav.routes[1] => `{params: undefined, index: 0, routeName: "StackA", key:"uniqeKey"}`

After re-launch the nav object looks like:
nav -> `{index: 1, routes: Array(2)}`
nav.routes[0] => `{routeName: "SplashScreen", key:"uniqeKey"}`
nav.routes[1] => `{params: undefined, index: 0, routeName: "StackA", key:"uniqeKey", routes:Array(1) - the first screen in the stack}`
nav.routes[2] => `{params: undefined, index: 1, routeName: "StackA", key:"uniqeKey", routes:Array(1) - the first screen in the stack}`

### Expected Behavior
-I expect that the nav object won't look different

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.27
| react-native     |0.52
| node             |8.9.3
| yarn      |1.3.2

**Comment by kelset** [comment]
Thanks for reporting, can you please create a [Snack](https://snack.expo.io/) that reproduces the issue?

**Comment by brentvatne** [comment]
closed because no repro
