### ISSUE TITLE
DrawerNavigator: Images flicking when navigation.goBack()

### ISSUE THREAD

**Issue by Syahrul** [react-navigation/react-navigation#3336]
### Current Behavior

![image_flicking](https://user-images.githubusercontent.com/2231998/35268941-909871a2-0065-11e8-952a-f6e0c6936b13.gif)

Even using local image (pre-cached), the result is the same as above.
No issue when navigating between tabs.

### Expected Behavior

- No flicking

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.21
| react-native     | 0.52.1
| node             | 8.5.0
| npm or yarn      | npm 5.6.0, yarn 1.3.2
| expo | 24.0

**Comment by kelset** [comment]
Have you tried updating to latest? Is that still present?

**Comment by Syahrul** [comment]
Upgraded to latest version and yes it is still present. What info do you need?

**Comment by kelset** [comment]
Aside from knowing if it happens with latest, a snippet of the code where the images are and the navigators would be good - best would be a [Snack repro](https://snack.expo.io/)

**Comment by satya164** [comment]
This is a React Native issue, not related to React Navigation. You can try caching the images to avoid flicker https://hackernoon.com/image-caching-in-react-native-96d8df33ca84
