### ISSUE TITLE
Modal's default behavior is not opening from the bottom (as specified in the docs)

### ISSUE THREAD

**Issue by quadsurf** [react-navigation/react-navigation#3344]
### Current Behavior
modal opens from the right

### Expected Behavior
modal should open from the bottom (your docs claim this is the default, but it's not behaving like the default, so when I attempt to declare the direction using the below key:value pair, it still does not work)
```
direction: 'bottomToTop'
```

### How to reproduce
https://snack.expo.io/@quadsurf/react-navigation-modal

### Your Environment
| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.27
| react-native | 0.52
| node | v7.10.0
| npm or yarn | yarn

**Comment by brentvatne** [comment]
the structure of the modal isn't right. read this doc for more info: https://reactnavigation.org/docs/modal.html and see this example: https://snack.expo.io/@react-navigation/full-screen-modal

**Comment by quadsurf** [comment]
@brentvatne the example you sent me, is a non-intuitive work-around, or at least it appears that way.

At  reactnavigation.org/docs/modal.html, declaring ```mode: 'modal'``` on the parent or RootStack is essentially saying that I want modal behavior on both of the children stacks, or in your example's case, it's declaring that I want modal behavior on both 'MyModal' and 'Main', when clearly modal behavior is not intended for the 'Main' stack. However, when running the code, the 'Main' stack is not inheriting the parent's modal declaration. I could understand if the 'Main' stack had some configuration options overwriting the parent's default, but it doesn't, hence the "work-around" feel.

I think the way I originally had it set up at https://snack.expo.io/@quadsurf/react-navigation-modal is the more intuitive way, the more declarative way, declaring it at the modal's stack level and not at the parent's global level... is there a reason why it was done this way? I'm guessing it had to do with normalizing modal differences between iOS and Android, but not sure.

Regardless, I have it working correctly in my app now, so I'm happy! And nice make-over on the React Navigation website by the way :-)
