### ISSUE TITLE
Unexpected token import on AppNavigator.js in redux integration example

### ISSUE THREAD

**Issue by francisrod01** [react-navigation/react-navigation#3348]
### Current Behavior

I trying to code for my own the redux integration and I running the test but it don't work.

![image](https://user-images.githubusercontent.com/4691768/35346036-46ad4910-0118-11e8-94e8-895e9afb0f0b.png)

References:

https://github.com/react-navigation/react-navigation/issues/1180
https://github.com/react-navigation/react-navigation/issues/569
[ReactJS with Redux-saga project studies](https://github.com/francisrod01/devReactJS/tree/master/projects/redux-saga/src)

### Redux Example

https://github.com/react-navigation/react-navigation/tree/master/examples/ReduxExample

```js
import React from 'react'
import PropTypes from 'prop-types'
import { connect } from 'react-redux'
import { addNavigationHelpers, StackNavigator } from 'react-navigation'

import LoginScreen from '../components/LoginScreen'
import MainScreen from '../components/MainScreen'
import ProfileScreen from '../components/ProfileScreen'


export const AppNavigator = StackNavigator({
    // Services: { screen: ServicesListScreen },
    Login: { screen: LoginScreen },
    Main: { screen: MainScreen },
    Profile: { screen: ProfileScreen },
})


const AppWithNavigationState = ({ dispatch, nav }) => (
    <AppNavigator navigation={ addNavigationHelpers({ dispatch, state: nav }) } />
)

AppWithNavigationState.propTypes = {
    dispatch: PropTypes.func.isRequired,
    nav: PropTypes.object.isRequired,
}


const mapStateToProps = (state) => ({
    nav: state.nav,
})


export default connect(mapStateToProps)(AppWithNavigationState)
```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | `1.0.0-beta.27`
| react-native     | `0.52.1`
| node             | `9.4.0`
| npm or yarn      | `1.3.2`

**Comment by keksipurkki** [comment]
I was bitten by this bug today, too. AFAIK, react-navigation does not currently play nicely with jest. Any jest test importing "react-navigation" is going to fail since the imported code is not transpiled down to NodeJS compatible JS. As a workaround, set the `transformIgnorePatterns` in your Jest config, see this [comment](https://github.com/react-navigation/react-navigation/issues/256#issuecomment-278626369).

**Comment by francisrod01** [comment]
@keksipurkki thank you for your answer!

I think it works but now...

![image](https://user-images.githubusercontent.com/4691768/35412784-74a0b1f8-0204-11e8-98a7-67896d634558.png)

**Comment by brentvatne** [comment]
> I was bitten by this bug today, too. AFAIK, react-navigation does not currently play nicely with jest. Any jest test importing "react-navigation" is going to fail since the imported code is not transpiled down to NodeJS compatible JS. As a workaround, set the transformIgnorePatterns in your Jest config...

this isn't really a bug, it's just the way the react-native ecosystem works at the moment -- people don't ship their transpiled source, instead they depend on metro transforming it for them in development. it's documented in jest docs themselves: https://facebook.github.io/jest/docs/en/tutorial-react-native.html#transformignorepatterns-customization

that said, we should probably ship a transpiled version so this isn't an issue, and all libraries in the ecosystem should probably start doing this at some point as well. created a feature request: https://react-navigation.canny.io/feature-requests/p/distribute-pre-compiled-version-of-react-navigation-to-npm -- feel free to vote up or implement and send pr

**Comment by NeliHarbuzava** [comment]
Answer: https://github.com/react-navigation/react-navigation/issues/256#issuecomment-278626369
