### ISSUE TITLE
Child event subscriptions should automatically subscribe/unsubscribe

### ISSUE THREAD

**Issue by ericvicenti** [react-navigation/react-navigation#3354]
As described in https://github.com/react-navigation/react-navigation/pull/3345, we do not properly subscribe and unsubscribe from upstream events at the right time.

To fix this, `getChildEventSubscriber` should only subscribe when the child `addListener` is called, and it should call 'cleanup' when the last child listener is `remove`d

**Comment by brentvatne** [comment]
@ericvicenti - is this a thing?
