### ISSUE TITLE
reset to the home page, the back button can not be monitored

### ISSUE THREAD

**Issue by 7449** [react-navigation/react-navigation#3361]
## explain

I searched a lot of issues under the project and found one that I had encountered the same problem, but was closed, and I did not find the answer I wanted, so I reopened one issues，

### Current Behavior

reset to the main page, Android's back button can not be monitored, I get the index has been zero, if not reset, it works

code:

this is based on the documentation

             componentDidMount() {
                BackHandler.addEventListener('hardwareBackPress', this.onBackPress);
            }
        
            componentWillUnmount() {
                BackHandler.removeEventListener('hardwareBackPress', this.onBackPress);
            }
        
            onBackPress = () => {
                console.log('=======================', store.getState().nav.index, '=======================')
                if (store.getState().nav.index === 0) {
                    return false;
                }
                store.dispatch(NavigationActions.back());
                return true;
            };

reset code:

            return Stack.router.getStateForAction(NavigationActions.reset({
                index: 0,
                key: null,
                actions: [{
                    type: 'Navigation/NAVIGATE',
                    routeName: DrawerName,
                    params: {},
                    state: state,
                }]
            }));

### How to reproduce

code is very simple, is to jump three pages, the third page is reset jump, and then jump to the fourth page, if this time by pressing the back key, the expected should be back to the third page , But app directly exit, log shows index has always been 0

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |   ^1.0.0-beta.26
| react-native     |  0.52.0
| node             |    9.4.0
| npm or yarn      |  1.3.2

**Comment by 7449** [comment]
drawer was imported directly before use，It is a DrawerNavigator
nested directly after the use of the back can not detect, I changed to the following code on it,

            class DrawerNavigationState extends Component {
                render() {
                    return <Drawer/>
                }
            }


                    const RouteConfigs = {
                        Drawer: {
                            screen: DrawerNavigationState,
                        },
                    };

can recognize, do not know why ... Hope to be explained

**Comment by FredZeng** [comment]
I think u should override the "onBackPress()" method to fit the case when the DrawerNavigator is on top of the stack.
## Example
Since lack of Nav state logs, i guess u r facing the problem like this:
```
const AppStackNavigator= StackNavigator({
    Login: {
        screen: LoginScreen,
    },
    Drawer: {
        screen: HomeDrawerNavigator,
    }
})

const HomeDrawerNavigator = DrawerNavigator({
    Home: {
        screen: HomeScreen,
    },
    ScreenA: {
        screen: ScreenA,
    },
    ScreenB: {
        screen: ScreenB,
    }
})
```
Here is a DrawerNavigator nested in a StackNavigator, and the DrawerNavigator contains three screens. 
## Before reset
Assume that we r in the ScreenA, thus the nav state currently should look like:
```
nav:
{
    index: 1,
    routes: [
        {
            key: "",
            routeName: "Login",
        },
        {
            key: "",
            index: 1,
            routeName: "Drawer",
            routes: [
                { key: "", routeName: "HomeScreen" },
                { key: "", routeName: "ScreenA" },
                { key: "", routeName: "ScreenB" },
            ]
        }
    ]
}
```
At this time, when u press the back key constantly, it should work in such case: 
1. from ScreenA back to HomeScreen.
In this step, u will receive `1` as the result of `store.getState().nav.index` in the `onBackPress ` method. Thus the nav goes back, and the nav state becomes:
```
nav:
{
    index: 1,
    routes: [
        {
            key: "",
            routeName: "Login",
        },
        {
            key: "",
            index: 0,
            routeName: "Drawer",
            routes: [
                { key: "", routeName: "HomeScreen" },
                { key: "", routeName: "ScreenA" },
                { key: "", routeName: "ScreenB" },
            ]
        }
    ]
}
```

2. from HomeScreen back to LoginScreen. 
Still receive `1` since `store.getState().nav.index` returns the first layer of nav's index.And the nav should become:
```
nav:
{
    index: 0,
    routes: [
        {
            key: "",
            routeName: "Login",
        }
    ]
}
```

3. App exit.
At this time, the `nav.index` is `0` and the app exit since `onBackPress ` return `false`.

## After reset
After reset the state to a point where `Drawer` was on the top of the stack and the active screen was `ScreenA`, the nav should become:
```
nav:
{
    index: 0,
    routes: [
        {
            key: "",
            index: 1,
            routeName: "Drawer",
            routes: [
                { key: "", routeName: "HomeScreen" },
                { key: "", routeName: "ScreenA" },
                { key: "", routeName: "ScreenB" },
            ]
        }
    ]
}
```
Because the `Drawer` on the top of the stack and the `store.getState().nav.index` returns `0`, pressing the back key only results in closing the app, which means that u shouldn't handle the back button press actions by only comparing the `nav.index` when the DrawerNavigator or TabNavigator is on the top of the stack.

## Solution for the example
Here is a trick by overriding the `onBackPress `  method.
```
onBackPress = () => {
    const nav = store.getState().nav;
    if ((nav.index === 0 && nav.routes[0].routeName !== "Drawer") || (nav.index === 0 && nav.routes[0].routeName === "Drawer" && nav.routes[0].index === 0)) {
        return false;
    }
    store.dispatch(NavigationActions.back());
    return true;
};
```
## Summary
u'd better log the nav state to see the differences between each `NavigationActions` for better understanding.
Hope someone can tell me a better solution.

**Comment by 7449** [comment]
explain my second question:

I put the DrawerNavigator returned in a new component, which is equivalent to taking the initiative to give up the back key monitoring, so it works


In fact, my nesting is more complicated


        const AppStackNavigator= StackNavigator({
            Login: {
                screen: LoginScreen,
            },
            Drawer: {
                screen: DrawerNavigator,
            }
        })
        
        const DrawerNavigator = DrawerNavigator({
            Tab: {
                screen: TabNavigator,
            }
        })
        
        
        const TabNavigator = TabwerNavigator({
            Home:{
                screen: HomeScreen,
            },
            Home:{
                screen: HomeScreen,
            },
            Home:{
                screen: HomeScreen,
            },
            Home:{
                screen: HomeScreen,
            },
            ...
        })


such judgment, `onBackPress` will have a lot of judgments, is not conducive to maintenance, so I chose to give up the` DrawerNavigator` return monitoring

just like the code I showed above, instead of specifying `DrawerNavigator` directly, a component that contains` DrawerNavigator` is returned

**Comment by 7449** [comment]
and I think the priority is highest if the DrawerNavigator pops up, but if I monitor the DrawerNavigator, then I'll have to deal with whether the drawer pops up

**Comment by 7449** [comment]
I finally modified the onBackPress method, as shown below, to meet my requirements


            onBackPress = () => {
                const nav = store.getState().stackNav;
                if (nav.index === 0 && nav.routes[0].routeName !== 'Drawer') {
                    BackHandler.exitApp();
                    return false;
                }
                let drawerRoutes = nav.routes[0].routes[0].routes;
                if (drawerRoutes[0].index === 0 && nav.routes[0].index === 0) {
                    BackHandler.exitApp();
                    return false;
                }
                let tabRoutes = drawerRoutes[0].routes;
                if (tabRoutes[0].index === 0 && drawerRoutes[0].index === 0 && nav.routes[0].index === 0) {
                    BackHandler.exitApp();
                    return false;
                }
                store.dispatch(NavigationActions.back());
                return true;
            };

but I think a return key to handle this judgment, logic too much, this is not the way I want to deal, but now in addition to giving up the monitoring of DrawerNavigator, I did not find other better ways

**Comment by brentvatne** [comment]
this should be resolved. if it is not working as expected still on the latest version, please create a new issue with a runnable example on https://snack.expo.io -- thanks!
