### ISSUE TITLE
TabNavigator this.props.navigation.state.params is undefined

### ISSUE THREAD

**Issue by yitzhakd** [react-navigation/react-navigation#3369]
I'm making an android app and trying to pass data between screens throught TabNavigator, but the this.props.navigation.state.params is undefined. Currently I am using

```
"react-native": "0.51.0",
"react-navigation": "^1.0.0-beta.22"
```

Example code (tried to keep the relevant only):

this is my index.js:

```
const RootNavigator = TabNavigator({
    Home: { screen: App },
    Design: { screen: ImageDesign }
}
```
this is the home screen:

```
export default class App extends React.Component {

  constructor(props) {
    super(props);

    this.state = { ... }
  }

  static navigationOptions = {
    tabBarVisible: false
  };

  render() {
    const { navigate } = this.props.navigation;

    return (
      <View style={styles.container}>
        <Button title="design image"
                onPress={ () => navigate('Design',{name: 'Jane'}) }/>
      </View>
    );
  }
}
```
this is the design screen:

```
export default class ImageDesign extends React.Component {

  constructor(props) {
    super(props);

    this.state = { ... }
  }

  static navigationOptions = {
    tabBarVisible: false
  };

  render() {
    const { params } = this.props.navigation.state;

    return (
      <View>
        <Text>{ params.name }</Text>
      </View>
    );
  }
}
```
but unfortunately params is undefined, so an 'undefined is not an object' error accured

I also tried:

```
<Button title="design image"
        onPress={ () => navigate('Design', {}, {type: "Navigate", routName:"ImageDesign", params: {name: 'Jane'}}) }/>
```
but I'm not sure that works that way

Thank you in advance!ImageDesign", params: {name: 'Jane'}}) }/>
but I'm not sure that works that way

Thank you in advance!

**Comment by Nqsty** [comment]
Hi, i'm having the same issue with StackNavigator.
```
react-native: 0.52.5
react-navigation: 1.0.29
```

**Comment by satya164** [comment]
Your `Design` screen receives params when you're navigating to it, but `TabNavigator` mounts all the screens on initial load. The `Designs` screen doesn't have any params on initial load, so you'll need to add a check for params inside your `render`

**Comment by Nqsty** [comment]
Is this the same for `StackNavigator`?
What do you mean by adding a check?

Regards

**Comment by satya164** [comment]
> Is this the same for StackNavigator?

No. `StackNavigator` renders a screen when you navigate to it.

> What do you mean by adding a check?

Something like:

```js
if (!this.props.navigation.state) {
  return null;
}
```
