### ISSUE TITLE
[BUG] Gap on top of nested StackNavigator in a TabNavigator

### ISSUE THREAD

**Issue by BowgartField** [react-navigation/react-navigation#3370]
### Current Behavior
It a bug that happend when you nested a StackNavigator in a TabNavigator. On the StackNavigator header above the tabs's name there is a bleu (default color in android) gap with blank.

### Expected Behavior
This gap should not exist because it useless.
To reproduce it you juste have to nested a StackNavigator in a TabNavigator and see.

### Your Environment
It happend just on android.

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.27
| react-native     | 0.50.3
| node             | v9.4.0
| yarn      | 1.3.2

**Comment by brentvatne** [comment]
please create a new issue with a link to a project on github where this happens, as requested by the issue template :)
