### ISSUE TITLE
Error - undefined is not an object using this.props.navigation.navigate

### ISSUE THREAD

**Issue by eahema** [react-navigation/react-navigation#3371]
### Current Behavior
I am using StackNavigator to navigate from 'Splashscreen-->'Registeration'--> 'homescreen'. i am able navigate from Splashscreen to Registration and not able to navigate to homescreen using this.props.navigation.navigate('Home'), it showing undefined is not an object. trying to find the solution via google.. but there is no correct solution.

- What code are you running and what is happening?
App.js
`
import SplashScreen from './component/SplashScreen'
import RegistrationScreen from './component/Regstration/index'
import HomeScreen from './component/HomeScreen/index'
const MainNavigator=StackNavigator(
    {
       Splash:{
        screen:SplashScreen,
        navigationOptions: {
            headerLeft :null,
            header: null,
        }
       },
       Registeration:{
        screen:RegistrationScreen,
        
       },
       Home: {
           screen:HomeScreen
          
       }
      
       
    } ,
    {
        initialRouteName: 'Splash',
      } 
    );
    export default MainNavigator`

Splashscreen.js
`import React, { Component } from 'react';

import {
  Alert,
  AppRegistry,
  StyleSheet,
  Dimensions,
  View,Text,StatusBar,
  NetInfo
} from 'react-native'

import { NavigationActions } from 'react-navigation';

var _this;

export default class SplashScreen extends Component {
  constructor(props) {
    super(props);
    NetInfo.isConnected.fetch().then(isConnected => {
      if(isConnected)
      {
          console.log('Internet is connected');
      }
})
  }
  componentDidMount() {
   
    setTimeout(() => {
      requestAnimationFrame(() => {
        this.props.navigation.navigate('Registeration');
      });
    }, 1000);
  }
  
    render() {
        const {height: screenHeight} = Dimensions.get('window');
      return (
        <View style={styles.container}>
        <StatusBar
            backgroundColor="#65499c"
            barStyle="light-content"
          />
              <Text style={styles.title}>Welcome to Smart device</Text>
        </View>
        
      );
    }
  }

//Connect everything
//export default connect(mapStateToProps, mapDispatchToProps)(SplashScreen);

var styles = StyleSheet.create({
  container: {
      flex:1,
      backgroundColor: '#9575cd',
    alignItems: 'center',
    justifyContent: 'center'
  },
  title: {
    fontSize: 19,
    color: 'gold',
    textAlign:'center'
    
  }
  
});`

Register.js
`import { View,
         TouchableOpacity, 
          Alert,
          StyleSheet ,
          ActivityIndicator,
          KeyboardAvoidingView,
          Keyboard ,
          BackHandler,Text,Input,Button,TextInput } from 'react-native';

import{Icon} from 'native-base'
import { NavigationActions } from 'react-navigation';
var _this;
export default class Register extends Component {
    

          constructor(props)
          {
              super(props);
              //const { navigate } = this.props.navigation;
             // console.log('Props value'+ navigate)
              this.state=
              {
                  name:"",
                  phonenumber:"",
                  error:"",
                  showProgress:false,
                  loginExist:false,
                  user:""
              }
            
          }

          componentDidMount()
          {
            this.props.navigation.navigate('Splash');
          }
          async onLoginPressed() {
            Keyboard.dismiss();
           // const {navi} = this.props.navigation;
            this.setState({showProgress: true});
           
            if(this.state.name=='' && this.state.phonenumber=='')
            {
                Alert.alert('Warning','Enter Name & Phonenumer');
            }
           else if(this.state.name=='')
            {
                Alert.alert('Warning','Enter name');
            }
            else if(this.state.phonenumber=='')
            {
                Alert.alert('Warning','Enter phonenumber');
            }
            else if(this.state.phonenumber!='')
            {
                var pattern=new RegExp(/^(\+[\d]{1,3}|0)?[7-9]\d{9}$/)
                var test=pattern.test(this.state.phonenumber);
                console.log('Patternresult:'+test)
                if(!test)
                {
                    Alert.alert('Warning','Enter valid phonenumber');
                }
            }

            
              this.setState({showProgress: false});
              
              //Alert.alert( this.props);
    
             
        }
         
          render() {
           
              return (
                  
                
                  <View style={styles.container}>
                        
                           <View style={styles.inputcontainer}>
                                <View style={styles.iconContainer}>
                                    <Icon style={{color:'#9e9e9e'}}  size={10} name='person' />
                                </View>
                                    <TextInput maxLength={20} onSubmitEditing={()=>this.phonenumber.focus()}
                                                onChangeText={ (text)=> this.setState({name: text}) } 
                                               style={styles.input} keyboardType='default' 
                                               multiline={false} underlineColorAndroid='rgba(0,0,0,0)'  placeholderTextColor='#9e9e9e' placeholder="Full Name"></TextInput>
                              </View>    
                              <View style={styles.inputcontainer}>
                                    <View  style={styles.iconContainer}>
                                        <Icon style={{color:'#9e9e9e'}} size={10} name='phone-portrait' />
                                    </View>
                                    <TextInput maxLength={13} ref={(input)=>this.phonenumber=input} 
                                    onChangeText={ (text)=> this.setState({phonenumber: text}) } 
                                     style={styles.input}  keyboardType='phone-pad' 
                                     multiline={false} underlineColorAndroid='rgba(0,0,0,0)' placeholderTextColor='#9e9e9e' placeholder="Mobilenumber"></TextInput>
                              </View>
                                    <TouchableOpacity  style={styles.button} onPress={this.onLoginPressed.bind(this)}>
                                    <Text
                                      style={styles.buttonText}>Sign In</Text>
                                  </TouchableOpacity>
                     </View>
              );
             
          
          }
      
         
      
      }

      // define your styles
      const styles = StyleSheet.create({
          container: {
           flexGrow:1,
           justifyContent: 'center',
           alignItems:'center'
          },
          inputcontainer: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
            paddingBottom:0
           },
          button:
          {
            justifyContent: 'center',
            width: '90%',
            borderRadius:25,
            marginVertical:10,
            paddingVertical:12,
            backgroundColor: '#00CA9D',
          },
          input: {
            width:'80%',            
            fontSize: 16,
            marginVertical:10,
            backgroundColor: '#bdbdbd',
            color: '#ffffff',
            fontWeight: '500',
            height:40,
            padding:10,
            justifyContent:'center'
        },
          buttonContainer:{
              backgroundColor: '#2980b6',
              paddingVertical: 15,
              borderRadius:25
          },
          buttonText:{
              color: '#fff',
              textAlign: 'center',
              fontWeight: '500',
              fontSize:16
          },
         iconContainer:{ 
            backgroundColor: '#bdbdbd',
            height:40,
            width:40,
            borderRightWidth:0.8,
            borderRightColor:'#ebebeb',
            justifyContent:'center',
            alignItems:'center'
        }
         
      });
`

home.js code
`'use strict';
import React, { Component } from 'react';
import { View,
         TouchableOpacity, 
          Alert,
          StyleSheet ,
          ActivityIndicator,
          KeyboardAvoidingView,
          Keyboard ,
          BackHandler,Text,Input,Button,TextInput } from 'react-native';

import{Icon} from 'native-base'
import { NavigationActions } from 'react-navigation';
var _this;
export default class HomeScreen extends Component {
    

          constructor(props)
          {
              super(props);
              //const { navigate } = this.props.navigation;
             // console.log('Props value'+ navigate)
            
            
          }

         
        
         
          render() {
           
              return (
                  
                
                  <View style={styles.container}>
                        
                           <Text>Wewewewe</Text>
                     </View>
              );
             
          
          }
      
         
      
      }

      // define your styles
      const styles = StyleSheet.create({
          container: {
           flexGrow:1,
           justifyContent: 'center',
           alignItems:'center'
          },
         
         
      });
`
- Include a screenshot if it makes sense.
![image](https://user-images.githubusercontent.com/4590907/35476908-0731b1f6-03b9-11e8-8b5d-1fb5382d71dc.png)

### Expected Behavior
it should navigate to Home screen. pls help me to resolve this issue asap
- What do you expect should be happening?
- Include a screenshot if it makes sense.

### How to reproduce

hope if use above code for reproduce error.

### Your Environment

"dependencies": {
    "@expo/vector-icons": "^6.2.2",
    "expo": "^25.0.0",
    "native-base": "^2.3.7",
    "react": "16.2.0",
    "react-native": "0.52.0",
    "react-navigation": "^1.0.0-beta.27",
    "react-redux": "^5.0.6",
    "redux": "^3.7.2",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.2.0"
  },

**Comment by brentvatne** [comment]
this isn't a bug. somewhere in your code you are referring to this.props.navigation where it is not available. find the line that the error msg points to and make sure that `this` is on the class and that navigation object is available on it. sorry this issue list is only for bugs.
