### ISSUE TITLE
unable to resolve module 'react-navigation'

### ISSUE THREAD

**Issue by BreakTruth** [react-navigation/react-navigation#3373]
### Current Behavior

- when I run the app I receive an error
- ![screen shot 2018-01-28 at 09 36 46](https://user-images.githubusercontent.com/13135287/35480477-145a4bda-040f-11e8-9c97-2bec62aa3c53.png)
 
### Expected Behavior

- it should have run normally

### How to reproduce

- I am running the default app.js from react-native, only added `import { TabNavigator } from 'react-navigation';`

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.27
| react-native     | 0.52.2
| node             | 8.6
| npm or yarn      | npm 4.6.1

**Comment by brentvatne** [comment]
hello! without a link to a project on github we cannot help here. this does not happen on a new project, so it is something about the configuration on your machine. one possible thing you could do is delete node_modules in the project directory and then run `npm install` again and restart the packager afterwards.

**Comment by BreakTruth** [comment]
it is a new project, literally created yesterday, and navigation was the first thing I installed

**Comment by satya164** [comment]
Please link to a project on GitHub. Otherwise it's not possible to know what the issue is.

**Comment by BreakTruth** [comment]
oddly enough, when I shut my mac and came back later to it, it suddenly worked…

**Comment by yllow** [comment]
use yarn to install

**Comment by Kitloo** [comment]
@yllow Can you give more detail?
(I mean show the example code~)

**Comment by VinayLucknow** [comment]
Hi,
I am also getting the same error when running app.  i am using sudo npm install --save react-navigation after deleting node_modules.
