### ISSUE TITLE
[Android] this.props.subscribe is not a function

### ISSUE THREAD

**Issue by RyanMitchellWilson** [react-navigation/react-navigation#3382]
I just updated from 1.0.0-beta.13 to 1.0.0-beta.27 and the ios side of it worked perfectly, no problems at all, but when I went to run it on Android I got this error:
<img width="381" alt="screen shot 2018-01-29 at 3 31 54 pm" src="https://user-images.githubusercontent.com/11371200/35538286-73176634-050a-11e8-8706-e55591274533.png">

I can get around this error by giving my TabNavigator the property `animationEnabled: true` but that itself causes a separate error where my nested TabNavigator doesn't work (Android only, still works on ios). Before the upgrade, having `animationEnabled` set to false allowed both the ios and android sides to work with no problem, but now I cannot have `animationEnabled` set to false because it causes a crashing bug on android, but I also cannot have `animationEnabled` set to true because that causes a problem where I cannot navigate between my nested tabs and nothing renders inside of them on android. Everything is working 100% on ios so this is an Android only issue. Would be great to either get the nesting tabNavigators fixed for android or allow me to set `animationEnabled` to false again so that my nested tab navigators work again the way they used to.

**Comment by satya164** [comment]
Your `node_modules` folder seems to be in a bad state. Try:

```sh
rm -rf node_modules
yarn
```

There's no usage of `.subscribe` in `react-navigation` or `react-native-tab-view` in beta 27. Also please use the issue template when opening an issue. It helps us understand the problem better.
