### ISSUE TITLE
NavigationDrawerItems text cutting off

### ISSUE THREAD

**Issue by zixk** [react-navigation/react-navigation#3389]
### Current Behavior

I was testing the app I am working on, on an actual phone and I have found an inconsistency between the emulated version of the app and the actual built one on the phone. The "tabs" or drawer items display properly on an emulated phone but don't on my actual phone.

![Image of app from an actual device](https://cdn.discordapp.com/attachments/360773211450900503/407884949283405824/Screenshot_20180130-130858.jpg)

### DrawerNavigation Code

```javascript
const DrawerContent = (props) => (
    <View>
        <View
            style={{
                backgroundColor: '#f50057',
                height: 140,
                alignItems: 'center',
                justifyContent: 'center',
            }}
        >
            <Text style={{ color: 'white', fontSize: 30 }}>
                Header
            </Text>
        </View>
        <DrawerItems {...props} />
    </View>
)
const Drawer = DrawerNavigator(
    {
        Campus: {
            path: '/',
            screen: Map,
            navigationOptions: {
                tabBarLabel: 'Map',
            },
        },
        Projects: {
            path: '/sent',
            screen: ProjectStack,
            navigationOptions: {
                tabBarLabel: 'Projects',
            },
        },
        News: {
            path: '/news',
            screen: NewsStack,
            navigationOptions: {
                tabBarLabel: 'News',
            },
        },
        Settings: {
            path: '/settings',
            screen: Settings,
            navigationOptions: {
                tabBarLabel: 'Settings',
            },
        },
        'Contact Us': {
            path: '/contact',
            screen: Contact,
            navigationOptions: {
                tabBarLabel: 'Contact Us',
            },
        },
        'Log In': {
            path: '/account',
            screen: Account,
            navigationOptions: {
                tabBarLabel: 'Log In',
            },
        },
    },
    {
        initialRouteName: 'Campus',
        drawerOpenRoute: 'DrawerOpen',
        drawerCloseRoute: 'DrawerClose',
        drawerToggleRoute: 'DrawerToggle',
        drawerPosition: 'left',
        contentComponent: DrawerContent,
        statusBarBackgroundColor:'white',
    }
);
export default Drawer;

const styles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#fff',
      alignItems: 'center',
      justifyContent: 'center',
    },
    footer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'flex-end',
    }
  });

```

### Expected Behavior

The excpected way this screen should display is shown below on a screenshot.

![Image of app from an emulated device](https://cdn.discordapp.com/attachments/360773211450900503/407887786998366212/Screenshot_1517318126.png)
### How to reproduce

- I am not really allowed to share more code but hopefully there is an easy fix for this.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.21
| react-native     | 0.50.3
| node             | 8.9.4
| npm or yarn      | 5.6.0

**Comment by kelset** [comment]
first off, have you tried updating to latest?

It looks like a styling issue tbh

**Comment by ericvicenti** [comment]
This seems like a react native issue because it works fine on emulator but has troubles on the phone.

@zixk, to get this fixed, please try to find the simplest example code that results in your phone truncating the text. Then create an issue in the react native repo with the following info:

- Exact version of Android on your simulator
- Exact model of your phone
- Exact version of Android on your phone
- Exact react native version

Can you try to run a simpler app

**Comment by peckpeck20** [comment]
I'm having the same issue on my app if there is any news please let us know :)

**Comment by alindj** [comment]
I am also facing the same issue.

**Comment by Kida007** [comment]
Had Same Issue in React Navigation (v1). Try Appending 1 space character in drawerLabel .  
`    drawerLabel: 'Credits ****',
`
Dont knoe how , but works like charm !

**Comment by n6g7** [comment]
@zixk did you ever submit that issue to the RN repo?
I'm still having this issue.

**Comment by amalamarypaul** [comment]
I am having the same issue. Any solution?

**Comment by jeremyhallden** [comment]
Same issue here on a OnePlus 6 running Android 9.
No issue on a Nexus 5X running Android 8, nor on iOS.

Expo SDK 32
react-navigation": "3.0.9"

**Comment by jeremyhallden** [comment]
The reason for this error and proposed solutions can be found here: https://github.com/facebook/react-native/issues/15114

**Comment by abrarrahman** [comment]
there seems to be an issue with the font on one plus phones https://stackoverflow.com/questions/53420564/react-navigation-header-title-cut-off
i'm experiencing a similar issue using a one plus 5
