### ISSUE TITLE
Stacknavigator: onEndReached call on all screens

### ISSUE THREAD

**Issue by vufrontend** [react-navigation/react-navigation#3394]
### Current Behavior

ArticleNav = StackNavigator({
  ArticleDetail: {
    screen: ArticleDetailPage,
    navigationOptions: () => ({
      title: `detail`
    }),
  },
  ArticlesList: {
    screen: ArticlesPage,
    navigationOptions: () => ({
      title: `list`
    })
  }
});

ArticlesPage is using Flatlist (https://facebook.github.io/react-native/docs/flatlist.html) and call onEndReached() to load more articles.

When User clicks on an article, Stacknavigator is called this.props.navigation.navigate('ArticleDetail',{id});

on ArticleDetailPage, when user scroll, onEndReached() are called.

### Expected Behavior

 onEndReached() are called only on ArticlesPage

| react-navigation@^1.0.0-beta.27 | 
| react-native  0.50.4  |
| node   v8.8.1         |
|  yarn  1.2.0    |

**Comment by kelset** [comment]
Hi @vufrontend.

This seems to me more of a react-native related issue (onEndReached behaviour is not free from bugs, ex: https://github.com/facebook/react-native/issues/12827) - you need to also remember that StackNavigator doesn't 'freeze' in any way the 'cards' that are below the current one, at the moment that's up to your code/implementation.

I'm going to close this, but if you can create a repro (better if using [Snack](snack.expo.io)) that proves that this is indeed a bug of the lib, I'll reopen it.

**Comment by buffaloDeveloper** [comment]
@vufrontend facing the same issue, did you find a solution?
