### ISSUE TITLE
how to avoid screens in the transition between tabs

### ISSUE THREAD

**Issue by rmn528** [react-navigation/react-navigation#3405]
I have a doubt, I'm ussing the tab navigation, I have 3 screens (A, B, C) and I start the tab navigation in the A screen, when I press the tab that carry me to the C screen from the A screen, I notive that the animation passes through B screen, is there a way to avoid the B screen when I go from A to C?

**Comment by brentvatne** [comment]
hello! please ask questions on stackoverflow or on discord (https://www.reactiflux.com/). this is only for bug reports, as the issue template explains
