### ISSUE TITLE
Is it possible to build Nested Navigators and change a title with Redux?

### ISSUE THREAD

**Issue by francisrod01** [react-navigation/react-navigation#3409]
### Current Behavior

I like to build a `StackNavigator` + `TabNavigator` with `Redux integration` and change the Stack title only I access a children from tab but the Doc DONT says if it's possible and how to do it.

* So.. I hide the title from TabNavigator for now but I have only one title (StackNavigator) parent at all.

I've been see  the doc below as reference:

- [Nesting a Navigator in a screen](https://reactnavigation.org/docs/intro/nesting#Nesting-a-Navigator-in-a-screen)
- [Details Regarding Redux Integration](https://reactnavigation.org/docs/guides/redux#Details-Regarding-Redux-Integration)

Redux integration: https://github.com/react-navigation/react-navigation/pull/2964

**Screenshots:**

![image](https://user-images.githubusercontent.com/4691768/35717434-60d9be90-07c6-11e8-892e-65ea748fd803.png)

![image](https://user-images.githubusercontent.com/4691768/35717460-7b065102-07c6-11e8-8c4f-e94af0001901.png)

### Expected Behavior

I tried to build a navigator as below:

```
- StackNavigator
   |--- MainScreen (title) <---- Main route
          |--TabNavigator
                |-- ListTabItem (StackNavigator)
                      |-- ListScreen (title) <----- Main tab item --> I don't need this title
                     |-- ItemDetails (title) <---- I need this title
                |-- ProfileTabItem (StackNavigator) (title) <-- I don't need this title
                     |-- UpdateScreen (title) <--- I need this title
                     |-- ViewAccount (title) <----- I need this title
   |--- SomethingElse
```

**Screenshot:**

![image](https://user-images.githubusercontent.com/4691768/35717620-a39c7370-07c7-11e8-87e5-12def5b57a8a.png)

I also implemented like this particular tutorial:
[hackernoon.com/...react-navigation-the-navigation-solution-for-react-native](https://hackernoon.com/getting-started-with-react-navigation-the-navigation-solution-for-react-native-ea3f4bd786a4)

and this is their project url:
https://github.com/spencercarli/getting-started-react-navigation

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.27
| react-native     | 0.52.2
| node             | 9.3.0
| yarn      | 1.3.2

**Comment by brentvatne** [comment]
hello! please ask questions on stackoverflow or on discord (https://www.reactiflux.com/). this is only for bug reports, as the issue template explains

**Comment by francisrod01** [comment]
Sure! Thank you for remember me about StackOverflow, but now I think that isn't possible because this is not in the doc.
