### ISSUE TITLE
Keyboard is not getting dismissed, StackNavigator swipe back

### ISSUE THREAD

**Issue by pyankoff** [react-navigation/react-navigation#3410]
Keyboard was getting dismissed when swiping back on StackNavigator in `1.0.0-beta.27`

Keyboard stays on screen when using current `master`

**Comment by brentvatne** [comment]
react-navigation never did anything to dismiss the keyboard automatically. please fill out the issue template fully when submitting an issue

**Comment by pyankoff** [comment]
Hm, here is a Snack using `1.0.0-beta.27` and dismissing keyboard https://snack.expo.io/@andrey/react-navigation-keyboard 
Keyboard was dismissing before and it seems like a desired behavior. 
Sorry for the lack of template info, thought it's an obvious one.

**Comment by brentvatne** [comment]
so the way to handle this, if you want to dismiss the keyboard during the swipe transition currently, is to use https://reactnavigation.org/docs/navigation-prop.html#addlistener-subscribe-to-updates-to-navigation-lifecycle and listen for `willBlur`. that said, we should build this into react-navigation at some point! it's on our radar
