### ISSUE TITLE
React navigation dynamic tabnavigator: cannot navigate to a specific tab

### ISSUE THREAD

**Issue by GloboM** [react-navigation/react-navigation#3412]
Hi there,
I have a nested tabnavigator which is  created dynamically(data are fetched and stored in redux store) . However from my homescreen, i have a horizontal flatlist which represents a shortcuts to the tabs. 
ex: a click on the second item should bring me to the second tab( I have 1 to 5 tabs, that depends on the fetched user data )
The problem is that im always redirected to the first tab.

Here is the structure of my app and what i've tried to do
 
my app main navigator  is a tabnavigator :( if a user has already logged in, he is directly redirected to the main screen). 

     welcome: {screen: WelcomeScreen},
     login: {screen: LoginScreen}
     main: { screen: AppDrawerNavigator}

my main screen(AppDrawerNavigator) is a DrawerNavigator with the following structure:

    const AppDrawerNavigator = DrawerNavigator({
       home: {
         screen: HomeNavigatorScreen, // HomeNavigatorScreen has the flatlist which  
                                      // links to the dynamictabs screen
       },
       dynamictabs: {
         screen: DynamictabsNavigator
       })

here is the code i'm using to navigate when a flat list item is clicked:

     this.props.navigation.dispatch(NavigationActions.navigate({
              routeName: 'dynamictabs',
              action: NavigationActions.navigate({ routeName:`Tab${this.props.index}`})
            }));

DynamicTabsNavigator.js 

    class TabNavigator extends React.Component {   
        
      render() {
        const  MarksTabs = StackNavigator({
          marksStack: {
            screen:  MarkTabs(this.props.marks), // MarkTabs is a function 
          }
        });
    
        return <MarksTabs />
      }
     }
    
     const mapStateToProps = state => ({
      marks: state.userInfo.marks,
    })
    export const  DynamicTabsNavigator =connect(mapStateToProps)(TabNavigator)

// markTabs function 

    const MarkTabs = (marks) => TabNavigator(generatetabs(marks),configurationObject)

// generateTabs Function loop through marks array and generate the tabs //dynamically

    generatetabs = (marks) => {
      lat tabs ={};
      marks[0].Cursuses.forEach((item, index, array) => {
        tabs[`Tab${index}`] = {
          screen:props => <NotesScreen {...props} data={item.Materials}/>,
          navigationOptions: ({navigation}) => ({
            title: item.Name,
          })
         }
      });
      return tabs
    }

 
 what i've tried to do is to assign a router in a  static way and is built dynamically at runtime. and add navigation props when returning <MarkTabs navigation={this.props.navigation} /> (i've linked react navigation to redux store as well.
In this case the navigation works correctly, if i click on the third item i'm redirected directly to the third stack. But this solution suppose that i will always have 5 tabs which is not always  the case)

here is the code for the modification i did:

    class TabNavigator extends React.Component {   
    
      static router = StackRouter({
        marksStack0: {
          screen: TabNavigator({
            'Tab0': {
              screen: () => <NotesScreen/>
            },
            'Tab1':{
              screen: () => <NotesScreen/>
            },
            'Tab2':{
              screen: () => <NotesScreen/>
            },
            'Tab3':{
              screen: () => <NotesScreen/>
            },
            'Tab4': {
              screen: () => <NotesScreen/>
            }
          })
        }
      })
    
      render() {
        const  MarksTabs = StackNavigator({
          marksStack: {
            screen:  MarkTabs(this.props.marks), // MarkTabs is a function 
          }
        });
    
        return <MarksTabs navigation= {this.props.navigation} />
      }
     }
    
     const mapStateToProps = state => ({
      marks: state.userInfo.marks,
    })
    export const  DynamicTabsNavigator =connect(mapStateToProps)(TabNavigator)

The problem is that inside a static declaration we cannot access any instance property or redux state in order to conditionally render tabs according to how many item i have.
I've tried to import redux store: store.getState(), but it's returning undefined. 

I hope that my description is clear.

Any help of how can i achieve that please? 

### Current Behavior
not able to navigate to a specific tab from my home screen

### Expected Behavior

a click on a horizontal flatlist item in the homescreen should bring me to a specific tab.
ex: a click on the third item of the flat list should bring me to the third tab. 

### How to reproduce

- You must provide a way to reproduce the problem. If you are having an issue with your machine or build tools, the issue belongs on another repoistory as that is outside of the scope of Rect Navigation.
- Either re-create the bug on [Snack](https://snack.expo.io) or link to a GitHub repository with code that reproduces the bug.
- Explain how to run the example app and any steps that we need to take to reproduce the issue from the example app.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^1.0.0-beta.26
| react-native     | https://github.com/expo/react-native/archive/sdk-24.0.0.tar.gz
| node             | 8.7.0
| npm or yarn      | 4.6.1

**Comment by ericvicenti** [comment]
Right now the TabRouter doesn't allow you to dynamically change tabs, but we could potentially add an action for it. 

For now, you can do this by overriding the router.getStateForAction function, and return a navigation state with a different set of routes.

**Comment by GloboM** [comment]
Thanks ericvicenti,
Could you please clarify more on where to place the overrided getStateForAction function.

**Comment by towfiqi** [comment]
Would like to know that as well.

**Comment by sinhpn92** [comment]
Did you solve this issue @GloboM ?
Could you please expand how to add new component or remove exists component from current router? @towfiqi
