### ISSUE TITLE
Stacknavigator header transition

### ISSUE THREAD

**Issue by EstebanBP** [react-navigation/react-navigation#3418]
### Current Behavior
Can not reproduce same behavior on iOS and Android. 
TabNavigator + StackNavigators related.
TabNavigator
- Tab1: StacknavigatorA
- Tab2: StacknavigatorB

When I switch between tabs, on iOS I've achieved to cancel stack navigator headers animations so it feels like it's the same header, but can't make it work on Android.
## Android
![android](https://user-images.githubusercontent.com/23704234/35769886-69c4474e-0912-11e8-802e-9c01315cf507.gif)
## iOS
![ios](https://user-images.githubusercontent.com/23704234/35769887-69dbb8e8-0912-11e8-8ed5-a93e39d5e144.gif)

### Expected Behavior

Get same behavior on Android 

### How to reproduce

I'm using this stackNav config:
```config: {
headerMode: 'float',
  transitionConfig: () => ({
    transitionSpec: {
      duration: 0,
      timing: Animated.timing,
      easing: Easing.step0,
    },
}
```

### Your Environment

| software         | version
| ---------------- | -------
"react-navigation" | ^1.0.0-beta.21
"react-native" | 0.51.0

**Comment by kelset** [comment]
Please update to latest release and let us know if still happens on beta.28

**Comment by EstebanBP** [comment]
@kelset Still happening on beta.28

**Comment by ericvicenti** [comment]
Perhaps this is due to the TabView behavior on Android, cc @satya164 

I don't think tab view was designed with this functionality in mind, so I'm not sure if it will be fixable

**Comment by EstebanBP** [comment]
but It's working on iOS @ericvicenti

**Comment by EstebanBP** [comment]
@ericvicenti Sure,  I'll try to post sample code in the next few hours.
Thanks for the help btw

**Comment by EstebanBP** [comment]
@ericvicenti Ok while doing the sample code I've realized what is happening.
TabNavigator has different default values for 'animationEnabled'. On iOS 'animationEnabled' is false, so it has no animation. Android 'animationEnabled' default's value is true.

There is no bug, but it would be nice to include it in doc.
Thanks for your help
