### ISSUE TITLE
getStateForAction returning null/undefined errors for initial state (redux integrated)

### ISSUE THREAD

**Issue by JulianKingman** [react-navigation/react-navigation#3421]
### Current Behavior
I set up a new project using redux (on expo 25, react navigation beta 27), and I'm running into problems with the code that sets up the initial state. Something's going wrong with getStateForAction. I set up a snack that demonstrates the behavior here: https://snack.expo.io/@buishi/react-navigation-redux-bug

I separated out my code like so:
(imports/exports skipped for brevity)

RootNavigator.js
```javascript
const RootNavigator = StackNavigator({
  LoggedInNavigator: {screen: LoggedInNavigator},
  LoggedOutNavigator: {screen: LoggedOutNavigator},
});
```
navState.js (nav reducer)
_This is what it tells me is null; 'Login' is a route of LoggedOutNavigator, but if I try 'LoggedInNavigator' as the path, I get a 'undefined is not an object (evaluating states.routes[childIndex])' error_

```javascript
// this is where error occures
const initialNavState = RootNavigator.router.getStateForAction(
  RootNavigator.router.getActionForPathAndParams('Login')
);
const navStateMiddleware = createReactNavigationReduxMiddleware(
  "root",
  state => state.navState,
);
const addListener = createReduxBoundAddListener("root");

const navState = (state = initialNavState, action) => {
  const nextState = RootNavigator.router.getStateForAction(action, state);
  return nextState || state;
};
```

Redux.js - where store is made
```javascript
const Store = createStore(
  combineReducers({
    appState, 
    userState, 
    navState,
  }), applyMiddleware(navStateMiddleware));
```

App.js - where the app is rendered
```javascript
const App = () => (
  <Provider store={Store}>
    {connect(({navState})=>navState)(<RootNavigator navigation={addNavigationHelpers({
      dispatch: props.dispatch,
      state: props.navState,
      addListener,
      })}/>)}
  </Provider>
);
```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |^1.0.0-beta.27
| react-native     | expo 25 (https://github.com/expo/react-native/archive/sdk-25.0.0.tar.gz)
| node             | ?
| npm or yarn      | npm 5.5.1

**Comment by JulianKingman** [comment]
(I read through various issues, and am aware of https://github.com/react-navigation/react-navigation/issues/3148, which seems to affect just drawers)

**Comment by brentvatne** [comment]
can you update to the latest version of react-navigation and follow the updated guide for redux at https://reactnavigation.org/docs/redux-integration.html?

let me know if this solves your problem

**Comment by robsongomes** [comment]
DrawerNavigator doesn't working anymore. Should I use StackNavigator as root and put Drawer inside it, or the contrary?
`
// 1
const Drawer = DrawerNavigator({
  Screen1: { screen: Screen1 },
  Stack1: { screen: Stack1 }
}

const Stack1 = StackNavigator({
  Screen2: { screen: Screen2 }
  ...
}
`
Scenario 1 doens't work.

`
// 2
const Drawer = DrawerNavigator({
  Screen1: { screen: Screen1 },
  Screen2: { screen: Screen2 },
  Screen3: { screen: Screen3 },
}
`

Scenario 2 works but I don't want Screen2, Screen3.... appearing on the Drawer Menu.

**Comment by brentvatne** [comment]
@robsongomes - not sure what you mean, this works fine: https://github.com/react-navigation/react-navigation/blob/master/examples/NavigationPlayground/js/Drawer.js

**Comment by JulianKingman** [comment]
@brentvatne @robsongomes's issue seems unrelated to this one. I tried setting up a snack exactly as it's suggested in the redux integration docs, but it's giving me an odd error about not being able to import `ren`, which is not even required...
https://snack.expo.io/@buishi/react-navigation-redux-bug
Your thoughts? I'll do my best to narrow the issue down once I can get anything working.

**Comment by brentvatne** [comment]
hey @JulianKingman can you re-create this issue on https://github.com/react-navigation/react-navigation-redux-helpers along with that repro?

**Comment by JulianKingman** [comment]
done

**Comment by jsina** [comment]
@brentvatne how could I addListener for ‘didFocus or didBlur’  with creatReduxBoundAddListener ?
