### ISSUE TITLE
headerLeft and headerRight will be un-clickable in 1.0.0-beta.28 if we use gesture to swipe back

### ISSUE THREAD

**Issue by just4fun** [react-navigation/react-navigation#3423]
### Current Behavior

- What code are you running and what is happening?

1. Say I have a `Home` page, it includes a `FlatList` component for topic list.
2. Click each topic item will navigate to `Topic Detail` page.
3. At this time, if we click back button to `Home` page, both `headerLeft` and `headerRight` works as usual.
4. However, if we use gesture to swipe back, both `headerLeft` and `headerRight` will be un-clickable.

#### More Information

1. I used both `DrawerNavigator` and `StackNavigator`, and also used a hacky way for modal card since `react-navigation` could not set `mode: 'modal'` for each card.

```javascript
const AppNavigator = DrawerNavigator({
  App: {
    screen: StackNavigator({
      Main: {
        screen: StackNavigator({
          Home: {
            screen: HomeScreen
          },
          Topic: {
            screen: TopicScreen
          }
        }, {
          initialRouteName: 'Home',
          navigationOptions: {
            headerTintColor: 'white',
            headerStyle: {
              backgroundColor: colors.blue
            },
            drawerLockMode: 'locked-closed'
          }
        })
      },
      LoginModal: {
        screen: LoginModalScreen
      }
    }, {
      // Without `headerMode: 'none'`, there will be two headers since there are two
      // StackNavigators which is workaround for using both `Card` and `Modal` mode.
      //
      // However, it will also hide header for Modal components, maybe you think why
      // we don't use original custom Header component written with RN Modal, the reason
      // is in that way we need to involve Modal component in every needed place.
      //
      // As workaround, I just used original custom Header component for Modal components.
      //
      // https://github.com/react-navigation/react-navigation/issues/1276
      headerMode: 'none',
      mode: 'modal',
      initialRouteName: 'Main',
      navigationOptions: {
        headerTintColor: 'white',
        headerStyle: {
          backgroundColor: colors.blue
        },
        drawerLockMode: 'locked-closed'
      }
    })
  },
}, {
  initialRouteName: 'App',
  contentComponent: Menu, // <-- This is custom menu.
  drawerOpenRoute: 'DrawerOpen',
  drawerCloseRoute: 'DrawerClose',
  drawerToggleRoute: 'DrawerToggle',
});
```

2. In `LoginModal` screen, I will reset to `Home` page if login successfully. Everything works well including `headerLeft` and `headerRight` in `Home` page.

```javascript
// In `LoginModal` screen
const resetAction = NavigationActions.reset({
  index: 0,
  actions: [
    NavigationActions.navigate({ routeName: 'Main' })
  ]
});
this.props.navigation.dispatch(resetAction);
```

But if I want to logout (in drawer, there is a logout button), I will also reset to `Home` page with code below.

```javascript
// In `Home` screen with open `Drawer`
const resetAction = NavigationActions.reset({
  index: 0,
  actions: [
    NavigationActions.navigate({ routeName: 'Home' })
  ]
});
this.props.navigation.dispatch(resetAction);
```
At this time, both `headerLeft` and `headerRight` button in Home page will be un-clickable. But they will back normal if I click topic item then click button back to Home page again.

- Include a screenshot if it makes sense.

https://youtu.be/pMSzsdwrJu0

### Expected Behavior

- What do you expect should be happening?

1. Whenever and wherever I navigate or swipe back to `Home` page, both `headerLeft` and `headerRight` will work as usual.

#### More information

1. If we used `1.0.0-beta.26`, there is no this issue, but we will face https://github.com/react-navigation/react-navigation/issues/3185. Hence the latest version (`1.0.0-beta.28`) I upgraded.

### How to reproduce

Please refer `Current Behavior` I described above.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.28
| react-native     | 0.51.0
| node             | 7.7.4
| npm or yarn      | npm - 4.1.2

**Comment by pcasa** [comment]
Believe same is happening to me when trying to add a Button on the headerRight.  Tried with https://github.com/react-navigation/react-navigation/blob/master/examples/NavigationPlayground/js/SimpleStack.js

Results are Buttons Show, but unable to click.

**Comment by binchik** [comment]
The same happens for me. If I swipe a screen, its header buttons are not clickable. If I swipe one screen MORE both header buttons and the screen contents are not clickable (only swiping works).

**Comment by macelii** [comment]
Experienced the same drawer issue when upgrading an existing project.
The problem exists in beta.28 and beta.29, beta.27 is fine.

**Comment by brentvatne** [comment]
hello! I believe that beta.30 will resolve this issue, can you try it out and let me know?

**Comment by pcasa** [comment]
@brentvatne beta.30 fixed my issue with buttons on header.  Thanks.  Hopefully it will work for others too.

**Comment by macelii** [comment]
beta.30 fixed the issue. Thanks!

**Comment by kelset** [comment]
Looks like the issue has been fixed (thanks @brentvatne!) - @just4fun can you please close the issue if it's fixed for you too?

**Comment by just4fun** [comment]
Thanks, it works.
