### ISSUE TITLE
Complete freezing of screen when swiping back from 2 screens deep StackNavigator on beta 28+

### ISSUE THREAD

**Issue by tankers746** [react-navigation/react-navigation#3424]
### Current Behavior

When navigating to a depth of two or lower screens and swiping to return to the parent screen, the parent screen is unresponsive to touch. This seems to occur on both iOS (tested on iPhone X and iPad Air 2) and Android (GS7) and does not occur when using the back button, only when swiping.

### How to reproduce

Simple App.js to demonstrate the problem:
```
import React from "react";
import { TouchableHighlight, Text } from "react-native";
import { StackNavigator } from "react-navigation";

const AppNavigator = StackNavigator({
  level1: {
    screen: ({ navigation }) => (
      <TouchableHighlight
        style={{ height: 100, width: 100, backgroundColor: "white" }}
        onPress={() => navigation.navigate("level2")}
      >
        <Text>Go level 2</Text>
      </TouchableHighlight>
    )
  },
  level2: {
    screen: ({ navigation }) => (
      <TouchableHighlight
        style={{ height: 100, width: 100, backgroundColor: "white" }}
        onPress={() => navigation.navigate("level3")}
      >
        <Text>Go level 3</Text>
      </TouchableHighlight>
    )
  },
  level3: { screen: () => null }
});

export default class App extends React.Component {
  render() {
    return <AppNavigator />;
  }
}

```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.29
| react-native     | 0.52.2
| node             | 9.2.0
| npm or yarn      | 4.6.1

**Comment by jamsch** [comment]
Confirmed here. In my case I used a regular reset action. Screen animates but it seems as though touch interaction is disabled.

```
 return AppNavigator.router.getStateForAction(NavigationActions.reset({
              index: 0,
              key: null, // 'Course',
              actions: [
                NavigationActions.navigate({
                  routeName: 'Course',
                }),
              ],
            }));
```

**Comment by rogchap** [comment]
I'm also having similar issues using a resetAction:
```
const resetAction = NavigationActions.reset({
      index: 0,
      actions: [
        NavigationActions.navigate({ routeName, params }),
      ],
    });
    this.props.navigation.dispatch(resetAction);
```
whole screen is unresponsive to touch including header.

**Comment by neel132** [comment]
I had a similar issue, haven't know the exact solution, but for workaround, I shifted back to 1.0.0.beta-27.

**Comment by zhouanbo** [comment]
Having the exact issue.

**Comment by brentvatne** [comment]
resolved in beta.30

**Comment by afshin-hoseini** [comment]
Check this : https://github.com/react-navigation/react-navigation/issues/2495#issuecomment-379545416

**Comment by ggdegreat** [comment]
Its happen in StackActions now. 

```
navigation.dispatch(
                      StackActions.reset({
                        index: 0,
                        actions: [
                          NavigationActions.navigate({ routeName: 'Home' }),
                          NavigationActions.navigate({ routeName: 'Sell' }),
                          NavigationActions.navigate({ routeName: 'SellDetails' })
                        ],
                      }),
                    )
```

it will successfully reset to Home, but the whole screen is unresponsive.

**Comment by danielkv** [comment]
same problem here

**Comment by shariq93** [comment]
I have used an alternative approach to solve this issue
https://medium.com/@shariq93/screen-getting-stuck-when-navigate-react-navigation-e6d2561a3381?sk=09f48fbd5175dce1886846e015d1da07

**Comment by denisk20** [comment]
For me the issue was happening only in prod mode (with chrome debugger it never froze). Resolved by removing the `addListener` focus effect:

```
  useEffect(() => {
    if (navigation && refetch) {
     // this caused the freezing
      navigation.addListener('focus', () => myFun())
    }
  }, [navigation, myFun])
```

**Comment by cloped** [comment]
@denisk20 Debug with Android Studio logcat. I found a bug on my dependencies, it was not the React Navigation
![image](https://user-images.githubusercontent.com/25209410/143956511-7999e48a-72f7-47f4-ad23-9a5e214b8179.png)

**Comment by Jvinicius06** [comment]
I'm getting the following error and right after the screen freezes, I've tried everything I can't solve it.
![image](https://user-images.githubusercontent.com/30390323/152653330-c6bb5b3b-427b-4c68-94f1-3ae9699e5d40.png)
