### ISSUE TITLE
black screen is cased by push and pop quickly

### ISSUE THREAD

**Issue by musicode** [react-navigation/react-navigation#3430]
## The issue tracker is reserved for bug reports only.

1. have you tried updating to the latest release?

   yes

2. does it happen only on Android/iOS?

  iOS, I dont know how about android

3. does it happen on both Debug and Release modes?

   both

4. does it happen with Debugger On or Off? Both?

   off

5. Can you provide a GIF or a repo or a snack to reproduce this issue?

I found that when i push and pop **quickly**, it will happen at the last pop action.

![image](https://user-images.githubusercontent.com/2732303/35776760-6adce642-09dd-11e8-8685-8f852f346483.png)

![image](https://user-images.githubusercontent.com/2732303/35776770-8dc71c72-09dd-11e8-836b-6f834c4db7e3.png)

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.29
| react-native     |  0.52.0
| node             |   v8.9.0
| npm or yarn      |  5.5.1

**Comment by kelset** [comment]
Without code it's hard to investigate.

**Comment by brentvatne** [comment]
indeed we need some way to reproduce this as I wasn't able to on my own, can you post some code and steps to follow please @musicode? thanks for the report!

**Comment by musicode** [comment]
[this](https://user-images.githubusercontent.com/2732303/35776770-8dc71c72-09dd-11e8-836b-6f834c4db7e3.png) is a screenshot gif, it's so frequently, i need help

**Comment by kelset** [comment]
Again, @musicode , it's **code** that is needed because it's really hard to investigate without.

You can use [Snack Expo](snack.expo.io) to provide us with a simple repro.

**Comment by brentvatne** [comment]
@musicode - as @kelset suggested, please create a snack where we can reproduce this. it's possible if you're using redux that something is wrong with the redux config. also be sure to update to the latest version. i can't reproduce this using the same steps you did in your gif on the playground app: https://expo.io/@react-navigation/NavigationPlayground

**Comment by musicode** [comment]
@brentvatne i don't use redux.

I set `transitionConfig` like below, it' ok. I think the default transitionConfig has some bugs.

```js
StackNavigator(
    routeConfig,
    {
      headerMode: 'screen',
      backTitle: null,
      transitionConfig: () => ({
        transitionSpec: {
          duration: 300,
          easing: Easing.out(Easing.poly(4)),
          timing: Animated.timing,
        },
        screenInterpolator: sceneProps => {
          const { layout, position, scene } = sceneProps;
          const { index } = scene;

          const width = layout.initWidth;
          const translateX = position.interpolate({
            inputRange: [index - 1, index, index + 1],
            outputRange: [width, 0, 0],
          });

          const opacity = position.interpolate({
            inputRange: [index - 1, index - 0.99, index],
            outputRange: [0, 1, 1],
          });

          return { opacity, transform: [{ translateX }] };
        },
      }),
    }
  )
```

**Comment by brentvatne** [comment]
the playground app (https://github.com/react-navigation/react-navigation/tree/master/examples/NavigationPlayground) uses the default transition configs in the simple stack example and I can't reproduce it there. I'd really like to reproduce this, let me know if you're able to somehow in the playground app, it would be much appreciated!

**Comment by kathychauhk01** [comment]
@musicode I tried to use the `transitionConfig` you posted, but it seems doesn't solve this issue. When I use the `default transitionConfig`, I can reproduce the black screen issue very quickly. But when I use your `transitionConfig`, the issue becomes harder to reproduce, but still, when I try to push and pop many times, the app would freeze at the last page I push. I think it is the same issue as the black screen, but the screen is just not in black color this time.

**Comment by brentvatne** [comment]
@kathychauhk01 @musicode - please explain how to reproduce on the NavigationPlayground app :) I really want to get to the bottom of this!

**Comment by musicode** [comment]
@kathychauhk01 I hope I can reproduce the issue with a little code, when I have time, I will try it

**Comment by musicode** [comment]
@brentvatne I hope I can reproduce the issue with a little code, when I have time, I will try it

**Comment by emj365** [comment]
I got the same problem, don't know the reason but it fixed by adding `duration: 300,` which https://github.com/react-navigation/react-navigation/issues/3430#issuecomment-363984644 told

**Comment by MrPluto** [comment]
same here when do some actions like:
```javascript
navigation.popToTop();
navigation.navigate(routeName);
```

**Comment by MikhailVolkov350504** [comment]
@musicode @kathychauhk01 @emj365 @MrPluto 
Does anybody setting navigation params on the screen he is navigating to?
I have `navigation.setParams` on one screen. And when I do some actions on another screen, it sets navigation params on the first screen and navigates back to the first screen. When I do it quick, I got the same issue with black screen. But when I remove `navigation.setParams` on the first screen, the issue disappears.
