### ISSUE TITLE
The previous screen is being rendered after reset, causing type errors like "this.props.user is not an object"

### ISSUE THREAD

**Issue by julianocomg** [react-navigation/react-navigation#3431]
### Current Behavior
(Redux integration)

I'm redirecting the user to the app's initial screen, and after that, removing the user from the store with a logout action. But, the previous screen (the logged area) is being rendered, causing type error, because the user data is no longer available on the store.

### Expected Behavior

The previous scene doesn't need to be rendered after a reset.

### How to reproduce

Connect some screen to any store data, reset the router to another screen, and clear that connected store data. The previous screen will be rendered, but now, without the data, causing a render error...

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.29
| react-native     | 0.52.2
| node             |
| npm or yarn      |

**Comment by kelset** [comment]
Can you please create a repro with [Expo](snack.expo.io)?

**Comment by ericvicenti** [comment]
It looks like you can fix this by making your screen handle the empty data provided by the store. If you have an issue with the navigation library, please provide an example with Expo Snack

**Comment by JoseIgnacio92** [comment]
#2421 Same issue
