### ISSUE TITLE
componentWillUnmount is not called by swipe 

### ISSUE THREAD

**Issue by musicode** [react-navigation/react-navigation#3432]
## The issue tracker is reserved for bug reports only.

1. have you tried updating to the latest release?

   yes

2. does it happen only on Android/iOS?

  iOS, I dont know how about android

3. does it happen on both Debug and Release modes?

   both

4. does it happen with Debugger On or Off? Both?

   off

5. Can you provide a GIF or a repo or a snack to reproduce this issue?

when i click back button, it's ok, but when i swipe,`componentWillUnmount` is not called

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.29
| react-native     |  0.52.0
| node             |   v8.9.0
| npm or yarn      |  5.5.1

**Comment by kelset** [comment]
Can you please create a repro with [Expo Snack](snack.expo.io)?

**Comment by brentvatne** [comment]
cannot repro it here: https://snack.expo.io/SkIbDtvUf
