### ISSUE TITLE
Documentation Website

### ISSUE THREAD

**Issue by LouisJS** [react-navigation/react-navigation#3433]
### Current Behavior

https://reactnavigation.org/docs/intro/nesting

Many pages of the doc disappeared.
I didn't find any explications in the READme or Twitter about this

**Comment by brentvatne** [comment]
there's no 1 to 1 mapping from old pages to new ones. we talk about nesting navigators in the context of a use case (full screen modal). additionally, old urls no longer work as you have noticed, there is no explanation beyond that we rewrote the docs and moved to a new docs tool to reduce maintenance burden and let us focus on improving the docs.
