### ISSUE TITLE
onNavigationStateChange not called in screen when screen is defined as function.

### ISSUE THREAD

**Issue by Billydubb** [react-navigation/react-navigation#3444]
## The issue tracker is reserved for bug reports only.

If you have a question, feature request, or an idea for improving the library or its related tools, please try one of the following resources:

```
const ChatList = () => (
	<View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
	  <Text>ChatList</Text>
	</View>
);

const ChatDetail = () => (
	<View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
	  <Text>ChatDetail</Text>
	</View>
);

//MAINDRAWER
const MainDrawerNavigator = DrawerNavigator({

	
	ChatList:{
		screen: ChatList
	},

	ChatDetail: {
		screen: ChatDetail
	}


});
  

//ROOT
const RootNavigator = StackNavigator({

	MainDrawerNavigator: {
		screen: MainDrawerNavigator
	}
},
{
	initialRouteName: 'MainDrawerNavigator',
	headerMode: 'none'
}
);


export default class ReactNavigationExample extends React.Component {	

	navigate = () => {
		const navAction = NavigationActions.navigate({
			routeName: 'MainDrawerNavigator'
		});
		this.nav.dispatch(navAction);
	}

	onStateChange = (prevState, currState) => {
		console.log('STATE CHANGED');
	}

	render() {
		return (
			<View style={{flex: 1}}>
				<RootNavigator
					onNavigationStateChange={this.onStateChange}/>
			</View>
		);
	}

}
```

---

### Current Behavior

When nesting navigators and defining the screen of the nested navigator as a function, the `onNavigationStateChange` callback of the nested navigator is not called.  In the example above, the screen field of MainDrawerNavigator is not defined as a function, so the onNavigationStateChange callback which is registered fires as expected when the drawer is opened or closed or when navigating between its child components.

However, when replacing the screen attribute with
```
screen: ({navigation}) => <MainDrawerNavigator/>
```

the callback is no longer called.

### Expected Behavior
The `onNavigationStateChange` callback should be triggered when the navigation state of a navigator changes.

### How to reproduce
Run the code above.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.30
| react-native     | 0.52.0
| node             | 6.9.0
| npm or yarn      | yarn

**Comment by ericvicenti** [comment]
This function component API is not supported for navigators:

```
screen: ({navigation}) => <MainDrawerNavigator/>
```

Instead, you could do this..

```
class MyNavigator extends React.Component {
  static router=MainDrawerNavigator;
  render() {
    return <MainDrawerNavigator {...this.props} />;
  }
}
...
screen: MyNavigator,
```
