### ISSUE TITLE
TypeError in latest build

### ISSUE THREAD

**Issue by elliotfleming** [react-navigation/react-navigation#3445]
Going from 1.0.0-beta.27 to 1.0.0-beta.28 or higher results in the error below. No other changes to the project have been made.

```
$ rm yarn.lock
$ rm -rf node_modules
// change version in package.json
$ yarn
// start app
// error (below)
```

<img width="300" alt="screen shot 2018-02-06 at 11 18 19 am" src="https://user-images.githubusercontent.com/1790645/35873629-e1e1abc6-0b2f-11e8-9881-c6df54b6fcf4.png">

**Comment by brentvatne** [comment]
https://github.com/react-navigation/react-navigation/issues/3437
https://github.com/react-navigation/react-navigation/issues/3421
https://github.com/react-navigation/react-navigation/issues/3416

please follow the new redux guide as per the release notes :) https://reactnavigation.org/docs/redux-integration.html

if you don't use redux, please re-open the issue and follow the issue template
