### ISSUE TITLE
nesting StackNavigation inside DrawerNavigation in order to use Modals doesn't show all screens in stacks

### ISSUE THREAD

**Issue by jeffsteinmetz** [react-navigation/react-navigation#3447]
### Current Behavior

While following the guide here, a modal example was created
https://reactnavigation.org/docs/modal.html

Screens open as expected using only the `StackNavigator`

Then creating a DrawerNavigator, a Drawer was created with a main stack (2 non modals) and 1 or more modal, with mode set to mode: 'modal'.

The MainStack only shows one of the 2 screens.

<img width="395" alt="iphone_7_plus_-_11_2" src="https://user-images.githubusercontent.com/5488059/35882035-a80ca10a-0b37-11e8-9d7e-ad554530c95c.png">

### Expected Behavior

Drawer should show 3 screen links
- Home
- Notifications
- MyModal

### How to reproduce

exact code here

```
import React from 'react'
import { Button, Image, Text, View } from 'react-native'
import { StackNavigator, DrawerNavigator } from 'react-navigation'

class MyHomeScreen extends React.Component {
  static navigationOptions = {
    drawerLabel: 'Home'
  }

  render() {
    return (
      <View>
        <Button
          onPress={() => this.props.navigation.navigate('Notifications')}
          title="Go to notifications"
        />
        <Button
          onPress={() => this.props.navigation.navigate('DrawerToggle')}
          title="Open Drawer"
        />
        <Button
          onPress={() => this.props.navigation.navigate('MyModal')}
          title="Open Modal"
        />
      </View>
    )
  }
}

class MyNotificationsScreen extends React.Component {
  static navigationOptions = {
    drawerLabel: 'Notifications'
  }

  render() {
    return (
      <View>
        <Button
          onPress={() => this.props.navigation.goBack()}
          title="Go back home"
        />
        <Button
        onPress={() => this.props.navigation.navigate('DrawerToggle')}
        title="Open Drawer"
        />
      </View>
    )
  }
}

class ModalScreen extends React.Component {
  render() {
    return (
      <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
        <Text style={{ fontSize: 30 }}>This is a modal!</Text>
        <Button
          onPress={() => this.props.navigation.goBack()}
          title="Dismiss"
        />
      </View>
    )
  }
}

const MainStack = StackNavigator(
  {
    Home: {
      screen: MyHomeScreen,
    },
    Notifications: {
      screen: MyNotificationsScreen,
    },
  },
  {
    initialRouteName: 'Home',
    mode: 'card'
  }
)

const RootDrawer = DrawerNavigator(
  {
    Main: {
      screen: MainStack
    },
      MyModal: {
        screen: ModalScreen,
      }
    }, {
      mode: 'modal',
      headerMode: 'none',
    } 
)

export default class App extends React.Component {
  render() {
    return <RootDrawer />;
  }
}

```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |    "version": "1.0.0-beta.29",
| react-native     |  "version": "0.52.0",

**Comment by brentvatne** [comment]
the screens that show up in the drawer are the ones that you put in the routeconfig for drawer. i think you want this:

```js
const MainDrawer = DrawerNavigator(
  {
    Home: {
      screen: MyHomeScreen, // you may want to use a stack here too
    },
    Notifications: {
      screen: MyNotificationsScreen, // and maybe also here
    },
  },
  {
    initialRouteName: 'Home',
    mode: 'card'
  }
)

const RootStack = StackNavigator(
  {
    Main: {
      screen: MainDrawer
    },
      MyModal: {
        screen: ModalScreen,
      }
    }, {
      mode: 'modal',
      headerMode: 'none',
    } 
)
```

**Comment by jeffsteinmetz** [comment]
That brings in the main nav items, but not the items in stack of modals.

I should have added the clarification that "MyModal" might be a "settings" screen or something that also has a desired result to show as an item in the Drawer.

The proposed suggestion doesn't include "My Modal" in the drawer.

The desired result is a mix of navigation items that open Standard Stacks as well as Modal style screens (that allow opening a settings or single screen), and closes back to the original Screen

<img width="397" alt="iphone_7_plus_-_11_2" src="https://user-images.githubusercontent.com/5488059/35889401-3fa44c76-0b50-11e8-8664-0a6d2600c245.png">

using your approach, and adding a stack of modals (i.e. Modal 1 and Modal 2, which might be something like Settings and Feedback) results in only Modal 1 showing up.

such as

```
import React from 'react'
import { Button, Image, Text, View } from 'react-native'
import { StackNavigator, DrawerNavigator } from 'react-navigation'

class MyHomeScreen extends React.Component {
  static navigationOptions = {
    drawerLabel: 'Home'
  }

  render() {
    return (
      <View>
        <Button
          onPress={() => this.props.navigation.navigate('Notifications')}
          title="Go to notifications"
        />
        <Button
          onPress={() => this.props.navigation.navigate('DrawerToggle')}
          title="Open Drawer"
        />
        <Button
          onPress={() => this.props.navigation.navigate('MyModal1')}
          title="Open Modal"
        />
      </View>
    )
  }
}

class MyNotificationsScreen extends React.Component {
  static navigationOptions = {
    drawerLabel: 'Notifications'
  }

  render() {
    return (
      <View>
        <Button
          onPress={() => this.props.navigation.goBack()}
          title="Go back home"
        />
        <Button
        onPress={() => this.props.navigation.navigate('DrawerToggle')}
        title="Open Drawer"
        />
      </View>
    )
  }
}

class ModalScreen1 extends React.Component {
  static navigationOptions = {
    drawerLabel: 'Settings Modal1'
  }

  render() {
    return (
      <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
        <Text style={{ fontSize: 30 }}>This is a modal!</Text>
        <Button
          onPress={() => this.props.navigation.goBack()}
          title="Dismiss Modal Screen 1"
        />
      </View>
    )
  }
}

class ModalScreen2 extends React.Component {
  static navigationOptions = {
    drawerLabel: 'Feedback Modal1'
  }

  render() {
    return (
      <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
        <Text style={{ fontSize: 30 }}>This is a modal!</Text>
        <Button
          onPress={() => this.props.navigation.goBack()}
          title="Dismiss Modal Screen 2"
        />
      </View>
    )
  }
}

const MainStack = StackNavigator(
  {
    Home: {
      screen: MyHomeScreen,
    },
    Notifications: {
      screen: MyNotificationsScreen,
    },
  }
)

const ModalStack = StackNavigator(
  {
      MyModal1: {
        screen: ModalScreen1,
      },
      MyModal2: {
        screen: ModalScreen2,
      }
    }, {
      mode: 'modal',
      headerMode: 'none',
    } 
)

const MainDrawer = DrawerNavigator(
  {
    Home: {
      screen: MyHomeScreen, // you may want to use a stack here too
    },
    Notifications: {
      screen: MyNotificationsScreen, // and maybe also here
    },
    Modals: {
      // this only shows 1 modal
      // and it can't be dismissed
      screen: ModalStack 
    }
  }
)

export default class App extends React.Component {
  render() {
    return <MainDrawer />;
  }
}

```

Also changing the DrawerNavigation to use a stack instead of listing each screen key, results in only showing the "Home" screen

```
const MainDrawer = DrawerNavigator(
  {
    Main: {
      screen: MainStack, // this only shows Home
    },
    Modals: {
      // this only shows 1 modal
      // and it can't be dismissed
      screen: ModalStack 
    }
  }
)
```

**Comment by jeffsteinmetz** [comment]
Here is the snack

https://snack.expo.io/@jeffsteinmetz/drawernavigation-with-modal-issue-demo

**Comment by jeffsteinmetz** [comment]
@brentvatne would you like me to open a new issue if this is still valid?

**Comment by brentvatne** [comment]
here's a fixed version of the snack you shared! https://snack.expo.io/BkCSSr9LM

hope that helps!

**Comment by jeffsteinmetz** [comment]
@brentvatne - Thanks for giving it a look.

I checked out your fixed version.
It doesn't have drawer labels for the modals (tested on both iOS and Android)
Would the expected behavior be that the drawer would show all 4 labels (2 cards and 2 modals)?  or was it working for you with all 4 labels in the drawer?

screen shot:

<img width="316" alt="iphone_7_plus_-_11_2" src="https://user-images.githubusercontent.com/5488059/36011594-3f5c1122-0d0d-11e8-962c-6bfd3b697905.png">

**Comment by jeffsteinmetz** [comment]
One other thing I noticed.  Let me know if this approach would have this expected result.

If in your snack,  `HomeStack` is changed to

```
const HomeStack = StackNavigator({
  Home: {
    screen: MyHomeScreen,
  },
  Foo: {
    screen: FooScreen
  }
});
```
(and of course create a FooScreen).

It still only shows the Home screen.  The Drawer only ever seems to pickup the first screen of the stack; in addition to not showing labels for the modals placed directly in the Drawer.

**Comment by brentvatne** [comment]
the drawernavigator only shows buttons for the routes that are registered immediately in the drawernavigator. sorry these issues are only for bugs, if you have more questions see https://reactnavigation.org/help.html

**Comment by jeffsteinmetz** [comment]
Thank you, I can open some discussions up on the other channels outlined on the help.

The reason I brought it up as an issue vs a question, is that it wasn't clear if the drawer navigation should, even as you suggest, support a mix of card types and modal types.

Is there no way to add links that open both modals and standard cards in the drawer without some work arounds then?

Thanks again.

Is there no way to add links that open both modals and standard cards in the drawer without some work arounds then?

Thanks again.

**Comment by brentvatne** [comment]
heya. it's not a 'workaround' to do what I described above with nesting stacks and drawernavigator, that's just how this library works.

**Comment by brentvatne** [comment]
that said, we should have more ergonomic support for modals, we're thinking about it

**Comment by jeffsteinmetz** [comment]
Right on.

In summary, is it correct to say the Drawer currently does not support rendering a mix of modals and non modals touchable **labels**.  I understand the modals in a stack (`<RootStack>` in your last example) make them available for navigation elsewhere in the app which is handy.

In other words, can it be said that the DrawerNavigator does not have a constructor that provides a way to include the touchable **labels** for the modals (since as you said they need to be `registered immediately in the drawernavigator`)?

Confirming this is helpful, as I can stop wrestling with this using the current approach.

Thank you again for summarizing this in
https://github.com/react-navigation/rfcs/issues/15

**Comment by brentvatne** [comment]
the labels are generated by default from the navigation options for the drawer. you can however override that with a contentComponent if you like: https://reactnavigation.org/docs/drawer-navigator.html#drawernavigatorconfig

**Comment by hugoh59** [comment]
Is this still accurate or are there updates on how to integrate modals inside a drawer?
