### ISSUE TITLE
PopToTop not working and undocumented

### ISSUE THREAD

**Issue by TheDutchCoder** [react-navigation/react-navigation#3449]
### Current Behavior

`NavigationActions.PopToTop()`
`NavigationActions.popToTop()`
`this.props.navigation.popToTop`
`this.props.navigation.PopToTop`

Neither of those work and since it's undocumented I'm unsure what to follow (I assumed it uses a similar syntax as `reset` since it's in the same [list](https://reactnavigation.org/docs/navigation-actions.html#PopToTop)

### Expected Behavior

The navigator to be able to use this method.

### How to reproduce

See top.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.27
| react-native     | 0.52.0
| node             | v4.8.2
| npm or yarn      | 4.6.1

**Comment by ericvicenti** [comment]
Please try the latest release, `1.0.0-rc.0`. Either of the following should work:

`this.props.navigation.dispatch(NavigationActions.PopToTop())`
`this.props.navigation.popToTop()`

I have noticed an issue with popToTop inside nested stack navigators, so I'll be fixing that shortly

**Comment by brentvatne** [comment]
it's documented in the API reference: https://reactnavigation.org/docs/navigation-prop.html

it'll make its way into the 'docs' section soon

**Comment by TheDutchCoder** [comment]
Please don't close this issue, it's not resolved yet...

In `1.0.0-rc.0` if you use `this.props.navigation.popToTop()` the following error is invoked:
![image](https://user-images.githubusercontent.com/1668207/35886242-6a6902b8-0b5e-11e8-8ac0-23ddb3de7765.png)

`this.props.navigation.pop(1)` works fine (didn't work in `beta.27`).

**Comment by elijahmurray** [comment]
@TheDutchCoder 's solution worked for me. Subbed `this.props.navigation.pop()` with `this.props.navigation.pop(1)`.

**Comment by ilibilibom** [comment]
> Please try the latest release, `1.0.0-rc.0`. Either of the following should work:
> 
> `this.props.navigation.dispatch(NavigationActions.PopToTop())`
> `this.props.navigation.popToTop()`
> 
> I have noticed an issue with popToTop inside nested stack navigators, so I'll be fixing that shortly

Hi Is this fixed for nested stack navigators?
