### ISSUE TITLE
headerStyle alignItems: 'flex-end' not working as expected

### ISSUE THREAD

**Issue by wuyunqiang** [react-navigation/react-navigation#3457]
### Current Behavior
if I set ``` alignItems: 'flex-end', ``` in  router headerStyle then head can't show.
I remove  ``` alignItems: 'flex-end', ``` will be ok.

### Expected Behavior

I can set ''' alignItems: 'flex-end', ''' in headerStyle and head can show.

### How to reproduce
the code:
```
//实现定义某个页面的动画效果
const TransitionConfiguration = () => {
    return {
        transitionSpec: {
            duration: 300,
            easing: Easing.linear(),
            timing: Animated.timing,
        },
        screenInterpolator:CardStackStyleInterpolator.forHorizontal,
        // screenInterpolator:freeStyle,
    };
};

const StackOptions = ({navigation}) => {
    const gesturesEnabled = true;
    const headerStyle= {
        flexDirection: 'row',
        justifyContent:'space-between',
        alignItems: 'flex-end',
        height:60,
        backgroundColor: Color.C5995f5,
        borderWidth: 0,
        borderBottomWidth: 0,
    };
    const headerTitleStyle = {
        backgroundColor:'transparent',
        fontSize: FONT(17),
        color: 'white',
    };
    const headerTintColor= 'white';
    const headerLeft = (
        <TouchableOpacity activeOpacity={1} onPress={()=>{
            console.log('配置里面的navigation goback');
            navigation.goBack(null)
        }}>
            <View style={{height: SCALE(100), paddingBottom:SCALE(20), justifyContent: 'flex-end',paddingLeft:SCALE(30),paddingRight:SCALE(40)}}>
                <Image
                    source={AppImages.Home.back}
                    style={{width:SCALE(20),height:SCALE(37)}}/>
            </View>
        </TouchableOpacity>
    );
    const headerRight=(<View style={{paddingRight:SCALE(30)}}>
    </View>);
    return {headerLeft,headerRight,headerStyle,gesturesEnabled,headerTitleStyle,headerTintColor,}
};

const AppNavigator = StackNavigator(
    {
        ...Routes,
        Index: {
            screen: Index,
        },
    },
    {
        initialRouteName: 'Index',
        headerMode: 'screen',
        mode: 'card',
        transitionConfig: TransitionConfiguration,
        navigationOptions: ({navigation}) => StackOptions({navigation}),
    }
);

export default AppNavigator;

```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^1.0.0-beta.27
| react-native     |0.52.0
| node             |v8.3.0
| yarn      |0.27.5

**Comment by kelset** [comment]
Have you tried updating to 1.0? Does it still happen?

**Comment by brentvatne** [comment]
please provide a runnable example on https://snack.expo.io or a repository that we can clone, thanks!

**Comment by wuyunqiang** [comment]
I update to 1.0 the bug still here.
code demo:https://github.com/wuyunqiang/RNDemo/tree/master/RNDemo

**Comment by wuyunqiang** [comment]
@brentvatne

**Comment by wuyunqiang** [comment]
if fixed please let me know.

**Comment by brentvatne** [comment]
@wuyunqiang - the example you provided is still pretty involved, can you create a *minimal* reproduction of this on https://snack.expo.io please? in other words, there are too many factors mixed in to the example currently, try to make an example that reproduces only exactly this problem with no extra code. thanks!

**Comment by wuyunqiang** [comment]
I have change code and remove extra code. please look that.
https://github.com/wuyunqiang/RNDemo/tree/master/RNDemo

**Comment by wuyunqiang** [comment]
android:
![navigation2](https://user-images.githubusercontent.com/13480948/36082552-9030c32e-0fe5-11e8-8052-f40bfa1e1713.png)
iOS:
![savereactnavigation](https://user-images.githubusercontent.com/13480948/36082603-03d3f67a-0fe6-11e8-89ec-4eff38b173ce.png)

**Comment by brentvatne** [comment]
I made flex styles no longer valid for `headerStyle`. Might block some more as well as they come up. To get the desired behavior you want here (using the master branch of this repo) you can set `titleStyle: {alignSelf: 'flex-end'}` and on your headerLeft, something like `headerLeft: <View style={{alignSelf: 'flex-end'}} />` -- hope that helps
