### ISSUE TITLE
popToTop not working

### ISSUE THREAD

**Issue by TheDutchCoder** [react-navigation/react-navigation#3458]
Opening a new issue because the previous one got closed prematurely.

### Current Behavior

`this.props.navigation.popToTop()` throws an error:
![image](https://user-images.githubusercontent.com/1668207/35886242-6a6902b8-0b5e-11e8-8ac0-23ddb3de7765.png)

### Expected Behavior

Expected it to work like documented.

### How to reproduce

Call `this.props.navigation.popToTop()`.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-rc.0
| react-native     | 0.52.0
| node             | v4.8.2
| npm or yarn      | 4.6.1

**Comment by kelset** [comment]
Please provide a repro using [Snack Expo](https://snack.expo.io/) and use 1.0 instead of rc.0

**Comment by TheDutchCoder** [comment]
As of 12 hours ago, in `1.0.0-rc.0` it was still broken: https://snack.expo.io/r1ONRtuLM

Okay, I can't keep up with this release tempo, but it's fixed in `1.0.0`.

I'll close this as it's currently fixed.

Just a side note: would it be worth considering using semver? I see breaking changes all over the beta releases which is usually not something that should be introduced in minor releases. (As you will run into problems like these, where suddenly functionality does/doesn't work on an `npm install` because it pulls down a non-major new version, but it has breaking changes).

**Comment by kelset** [comment]
> Just a side note: would it be worth considering using semver?

Yeah basically we moved to 1.0 for that reason. Here's the [blogpost of 1.0](https://reactnavigation.org/blog/2018/02/06/react-navigation-1.0.html)
