### ISSUE TITLE
goBack is not working

### ISSUE THREAD

**Issue by KurobaZhang** [react-navigation/react-navigation#3460]
## The issue tracker is reserved for bug reports only.

if I provide Header Component by navigationOptions props, I can use headerProps. 

when I use     

 
        this.props.navigation.goBack()

I found out that addNavigationHelpers.js goBack function , I will get key: 'StackRouterRoot',      
  
  ```
    goBack: key => {
      let actualizedKey = key;
      if (key === undefined && navigation.state.key) {
        invariant(
          typeof navigation.state.key === 'string',
          'key should be a string'
        );
        actualizedKey = navigation.state.key;
      }
      return navigation.dispatch(
        NavigationActions.back({ key: actualizedKey })
      );
    },
  ```

 so  when the program run to function getStateForAction in StackRouter.js, 
 
  ```
       if (
        action.type === NavigationActions.BACK ||
        action.type === NavigationActions.POP
      ) {
        const { key, n, immediate } = action;
        let backRouteIndex = state.index;
        if (action.type === NavigationActions.POP && n != null) {
          // determine the index to go back *from*. In this case, n=1 means to go
          // back from state.index, as if it were a normal "BACK" action
          backRouteIndex = Math.max(1, state.index - n + 1);
        } else if (key) {
          const backRoute = state.routes.find(route => route.key === key);
          backRouteIndex = state.routes.indexOf(backRoute);
        }

        if (backRouteIndex > 0) {
          return {
            ...state,
            routes: state.routes.slice(0, backRouteIndex),
            index: backRouteIndex - 1,
            isTransitioning: immediate !== true,
          };
        } else if (
          backRouteIndex === 0 &&
          action.type === NavigationActions.POP
        ) {
          return {
            ...state,
          };
        }
      }
  ```

 I will get backRouterIndex = -1,  so it will not goBack

---

### Current Behavior

goBack is not working

### Expected Behavior

goBack  work well

### How to reproduce

rewrite Header component and use HeaderProps to goBack

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0
| react-native     | 0.51.0
| node             |  7.9.0
| npm  | 5.6.0

**Comment by kelset** [comment]
Can you please provide a repro with [Snack Expo](https://snack.expo.io/)?

**Comment by brentvatne** [comment]
updated release notes accordingly https://github.com/react-navigation/react-navigation/releases/tag/1.0.0
