### ISSUE TITLE
Component withNavigation cannot be given refs

### ISSUE THREAD

**Issue by andrewcroce** [react-navigation/react-navigation#3461]
### Current Behavior

When using the HOC `withNavigation`, one is unable to set refs on this component. This is because it is a stateless functional component. 

### Expected Behavior

Refs should be possible on components using `withNavigation`.

### How to reproduce

Wrap a component using `withNavigation` and try to set a ref on it.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.11
| react-native     | 0.51.0
| node             | 8.9.3
| npm or yarn      | yarn 1.3.2

**Comment by kelset** [comment]
Please update to 1.0 and provide a repro via [Snack Expo](https://snack.expo.io/) know if it still happens.

**Comment by brentvatne** [comment]
we can either do nothing and user can provide their own callback prop, eg: on your wrapped component add getRef which supplies the ref to a callback, or:

- use something like https://github.com/elado/hoist-non-react-methods or proxy
- let the user pass in an array of methods to proxy

I don't have a strong preference. the redux approach afaict is to do nothing and let the user provide a callback prop. cc @ericvicenti

**Comment by brentvatne** [comment]
you can use `onRef={callback}` with a component wrapped with `withNavigation` now

**Comment by potasium** [comment]
It is not clear for me to implement onRef.  How can i get the child components states with onRef

**Comment by brentvatne** [comment]
it's the same as using ref. `onRef={ref => this._something = ref;}}` then do what you want with it. https://reactjs.org/docs/refs-and-the-dom.html
