### ISSUE TITLE
TypeError: addListener is not a function

### ISSUE THREAD

**Issue by laclance** [react-navigation/react-navigation#3465]
| react-navigation 1.0.0-beta.21 |
| react-native 0.50.4   |
| node 9.4.0             |
| npm 5.6.0     |
react-redux 5.0.6
redux 3.7.2
OSX and Android

Stack Trace:

```
This error is located at:
    in CardStack (at CardStackTransitioner.js:66)
    in RCTView (at View.js:113)
    in View (at Transitioner.js:142)
    in Transitioner (at CardStackTransitioner.js:19)
    in CardStackTransitioner (at StackNavigator.js:38)
    in Unknown (at createNavigator.js:13)
    in Navigator (at createNavigationContainer.js:214)
    in NavigationContainer (at AppWithNavigationState.js:24)
    in AppWithNavigationState (created by Connect(AppWithNavigationState))
    in Connect(AppWithNavigationState) (at App.js:15)
    in Provider (at App.js:14)
    in _class2 (at index.android.js:9)
    in awezaEduApp (at renderApplication.js:35)
    in RCTView (at View.js:113)
    in View (at AppContainer.js:102)
    in RCTView (at View.js:113)
    in View (at AppContainer.js:122)
    in AppContainer (at renderApplication.js:34)


```

**Comment by brentvatne** [comment]
please fillw out issue template and search for related issues first. https://github.com/react-navigation/react-navigation/issues?utf8=%E2%9C%93&q=+addListener+is+not+a+function

**Comment by laclance** [comment]
I dont know how because it doesnt really make sense because everything was working fine :( but i will try

**Comment by raulclaudino** [comment]
I have the same problem. Are you using redux?

**Comment by laclance** [comment]
yes

| react-navigation 1.0.0-beta.21 |
| react-native 0.50.4 |
| node 9.4.0 |
| npm 5.6.0 |
react-redux 5.0.6
redux 3.7.2
OSX High Sierra 10.13.3
Android emulator Nexus 5x API 25

**Comment by laclance** [comment]
#3468
