### ISSUE TITLE
IndicatorStyle not working for TabBarBottom

### ISSUE THREAD

**Issue by VanessaChu** [react-navigation/react-navigation#3466]
I've read other threads on this related issue but they didn't work for me

![screen shot 2018-02-07 at 12 12 42 pm](https://user-images.githubusercontent.com/11250498/35939182-37c88f48-0c00-11e8-82b0-ee6fc868ab1a.png)

I'm trying to get something like this, but the purple bottom border doesn't show up.

```
const Tabs = TabNavigator({
...
    // options
  lazy: true,
  tabBarComponent: TabBarBottom,
  tabBarPosition: 'bottom',
  swipeEnabled: false,
  headerMode: 'float',
  tabBarOptions: {
    indicatorStyle: {
      backgroundColor: 'transparent',
      borderBottomColor: 'rgba(119,75,151,1)',
      borderBottomWidth: 2
    },
    showIcon: true,
    showLabel: false,
    style: styles.tabBar,
  }
})
```

**Comment by brentvatne** [comment]
can you please follow the issue template (the text that is prefilled in the comment box) when creating issues? :) if you can reproduce this on https://snack.expo.io or provide a small project that reproduces it, we can help. thanks!

**Comment by brentvatne** [comment]
it would seem that this is only supported on TabBarTop -- https://github.com/react-navigation/react-navigation/issues/3117#issuecomment-353139002

notice: https://reactnavigation.org/docs/tab-navigator.html#tabbaroptions-for-tabbarbottom-default-tab-bar-on-ios and https://reactnavigation.org/docs/tab-navigator.html#tabbaroptions-for-tabbartop-default-tab-bar-on-android

**Comment by yakirbu** [comment]
How come a bottom tab navigator doesn't have an option for indicator line?

**Comment by heyman333** [comment]
I am also wondering about supporting about bottomtabbar indicator. it is really needed

**Comment by brentvatne** [comment]
you'll need to implement this on your own if you want it, or open a feature request on https://react-navigation.canny.io/feature-requests
