### ISSUE TITLE
TypeError: addListener is not a function

### ISSUE THREAD

**Issue by laclance** [react-navigation/react-navigation#3468]
### Current Behavior

red screen with the following:

> TypeError: addListener is not a function
> This error is located at:
>     in CardStack (at CardStackTransitioner.js:66)
>     in RCTView (at View.js:113)
>     in View (at Transitioner.js:142)
>     in Transitioner (at CardStackTransitioner.js:19)
>     in CardStackTransitioner (at StackNavigator.js:38)
>     in Unknown (at createNavigator.js:13)
>     in Navigator (at createNavigationContainer.js:214)
>     in NavigationContainer (at AppWithNavigationState.js:24)
>     in AppWithNavigationState (created by Connect(AppWithNavigationState))
>     in Connect(AppWithNavigationState) (at App.js:15)
>     in Provider (at App.js:14)
>     in _class2 (at index.android.js:9)
>     in awezaEduApp (at renderApplication.js:35)
>     in RCTView (at View.js:113)
>     in View (at AppContainer.js:102)
>     in RCTView (at View.js:113)
>     in View (at AppContainer.js:122)
>     in AppContainer (at renderApplication.js:34)

### Expected Behavior

Expect app to run

### How to reproduce

type 'npm install && react-native run-android' in command line

### Your Environment

| react-navigation 1.0.0-beta.21 |
| react-native 0.50.4 |
| node 9.4.0 |
| npm 5.6.0 |
react-redux 5.0.6
redux 3.7.2
OSX High Sierra 10.13.3
Android emulator Nexus 5x API 25

**Comment by brentvatne** [comment]
https://github.com/react-navigation/react-navigation/issues?utf8=%E2%9C%93&q=addListener+is+not+a+function

**Comment by brentvatne** [comment]
follow this guide: https://reactnavigation.org/docs/redux-integration.html

**Comment by laclance** [comment]
i did but couldn't get it working together with redux-persist. redux-logger and redux-thunk. Will try again, thank you.

**Comment by laclance** [comment]
My apologies Brent, I was trying to over complicate things but it was actually very easy. 
Here is my configureStore in case anybody else has a similar setup to mine.

```
import {AsyncStorage} from 'react-native';
import {
  applyMiddleware,
  compose,
  createStore
} from 'redux';
import thunk from 'redux-thunk';
import {createLogger} from 'redux-logger';
import reducers from './reducers/index';
import {
  autoRehydrate,
  persistStore
} from 'redux-persist';
import {
  createReduxBoundAddListener,
  createReactNavigationReduxMiddleware
} from 'react-navigation-redux-helpers';

const reduxMiddleware = createReactNavigationReduxMiddleware(
  'root',
  (state) => state.nav,
);

export const addListener = createReduxBoundAddListener('root');

export default (onStorePersisted) => {
  const reduxDevTools = __DEV__ && window.__REDUX_DEVTOOLS_EXTENSION__ ? window.__REDUX_DEVTOOLS_EXTENSION__() : {};
  
  const middleWare = __DEV__
    ? applyMiddleware(thunk, createLogger(), reduxMiddleware)
    : applyMiddleware(thunk, reduxMiddleware);

  const enhancer = compose(middleWare, autoRehydrate());

  const store = createStore(reducers, reduxDevTools, enhancer);

  const persistOptions = {
    storage: AsyncStorage,
    blacklist: ['home', 'learning', 'loading', 'nav', 'search', 'audio']
  };

  persistStore(store, persistOptions, onStorePersisted);

  return store;
};
```

**Comment by raulclaudino** [comment]
It worked for me. Thank you very much!

**Comment by jaschaio** [comment]
@laclance what did you change? Getting the same error

**Comment by forrestbwilson** [comment]
@laclance did you have too pass addListener to the React-Navigation element too?  The documentation alluded to this but I am wondering if it is necessary in this set

`<AppNavigator navigation={addNavigationHelpers({
        dispatch: this.props.dispatch,
        state: this.props.nav,
        addListener,
      })} />`

**Comment by concuacon** [comment]
@laclance you saved my day <3

**Comment by wzup** [comment]
@brentvatne 
Why do you give links for redux-integration? It doesn't solve the issue it when you do not use redux
