### ISSUE TITLE
TypeError: undefined is not a function (near '...addListener...')

### ISSUE THREAD

**Issue by happyeverydayzhh** [react-navigation/react-navigation#3470]
## The issue tracker is reserved for bug reports only.

![image](https://user-images.githubusercontent.com/5198326/35960074-3f267974-0ce3-11e8-85e6-7d95e48fb832.png)

| software         | version
| ---------------- | -------
| react-navigation |  v1.0.0
| react-native     | 0.51.0
| node             | v8.2.1
| npm or yarn      | v0.24.5

**Comment by happyeverydayzhh** [comment]
i solve it following bellow:
https://reactnavigation.org/docs/redux-integration.html

**Comment by dann1609** [comment]
Just run:
` yarn add react-navigation-redux-helpers`
or
`npm install --save react-navigation-redux-helpers`
