### ISSUE TITLE
addListener is not a function

### ISSUE THREAD

**Issue by ArtyEmsee** [react-navigation/react-navigation#3475]
### Current Behavior

When running `react-native run-ios`, I get this error.

![screen shot 2018-02-08 at 3 17 47 pm](https://user-images.githubusercontent.com/10135423/35996038-4d96c842-0ce3-11e8-8a88-ab6b25d2de24.png)
)

Which directs me to line 106 of CardStack.js. The error seems to be in this function: 

```javascript
_getScreenDetails = scene => {
    const { screenProps, navigation, router } = this.props;
    let screenDetails = this._screenDetails[scene.key];
    if (!screenDetails || screenDetails.state !== scene.route) {
      const screenNavigation = addNavigationHelpers({
        dispatch: navigation.dispatch,
        state: scene.route,
        addListener: getChildEventSubscriber(
          navigation.addListener,
          scene.route.key
        ),
      });
      screenDetails = {
        state: scene.route,
        navigation: screenNavigation,
        options: router.getScreenOptions(screenNavigation, screenProps),
      };
      this._screenDetails[scene.key] = screenDetails;
    }
    return screenDetails;
  };
```

The problem seems to be with the navigation.addListener function, as navigation does not seem to have an addListener method.

I can comment out
```javascript
addListener: getChildEventSubscriber(
          navigation.addListener,
          scene.route.key
        ),
```
to get past the error and open my application but it obviously breaks react-navigation functionality which I need.

I'm pretty confused by this; any help is welcome.

### Environment

| software         | version
| react-navigation | v1.0.0
| react-native     | v0.47.2
| node             | v6.3.1
| npm or yarn      | npm v3.10.3

**Comment by ericvicenti** [comment]
Hi there! The integration with redux has changed in recent versions. Please see the new documentation here: https://reactnavigation.org/docs/redux-integration.html

**Comment by ArtyEmsee** [comment]
That worked; thank you.

**Comment by tychota** [comment]
For record, here is the required changes.

**Comment by MarcoLLeite** [comment]
I am also having this issue. 
addListener works perfectly on Android, but on iOS I get the "is not a function" error.
Is there anything I can do? Other then adding redux to my project?

Thanks

**Comment by brentvatne** [comment]
hi there! if this is still a bug can you create a new issue that reproduces the bug on https://snack.expo.io? thanks!
