### ISSUE TITLE
TabBarBottom not hiding when Keyboard is activated

### ISSUE THREAD

**Issue by YogeshDevgun** [react-navigation/react-navigation#3481]
Hi 

when search bar is clicked and keyboard opens up, TabBarBottom moves up on the keyboard, instead, it should be hidden behind the keyboard.  How to achieve that? Please check screenshot for more.

![image](https://user-images.githubusercontent.com/23658483/36039577-e422eda8-0de8-11e8-98a5-c7acf01b4d6f.png)

**Comment by brentvatne** [comment]
hi, please search issues beforehand: https://github.com/react-navigation/react-navigation/issues/618

also, when you do create an issue please fill out the template :)
