### ISSUE TITLE
Issue with NavigationActions

### ISSUE THREAD

**Issue by Chooster** [react-navigation/react-navigation#3482]
Having issues with an animation after NavigationActions is called where the animation of the page is going from left-right instead of right-left.

`const resetAction = NavigationActions.reset({
          index: 0,
          actions: [ NavigationActions.navigate({
            routeName: screen,
            params: params,
          }) ]
        })`
 `this.navigator.dispatch(resetAction)`

Is there an option to change this or change the animation?

**Comment by brentvatne** [comment]
hello! please re-create the issue following the issue template if you think this is a bug, otherwise look at https://reactnavigation.org/help
