### ISSUE TITLE
Ability to keep tab menu title fixed

### ISSUE THREAD

**Issue by morfsys** [react-navigation/react-navigation#3485]
I am using a using a little nested navigation based on both StackNavigator and TabNavigator.

A snippet of my code looks like this:

` const TabOne = StackNavigator({
     ScreenOne: {screen: ScreenOne},
     ScreenTwo: {screen: ScreenTwo},
});

const TabTwo = StackNavigator({
     ScreenThree: {screen: ScreenThree},
});

const TabStack = TabNavigator({
    Home: {screen: TabOne},
    Others: {screen: TabTwo},
});

const RootStack = StackNavigator({
    TabStack: {screen: TabStack},
    ScreenFive: {screen: ScreenFive},
})
`
When I navigate from ScreenOne to ScreenTwo using this.props.navigation.navigate('ScreenTwo') from ScreenOne, I find that the menu title in tab bar changes from 'Screen One' to 'Screen Two'. I want to make sure that this doesn't happen in tab bar and the menu remains fixed to 'Screen One' irrespective of how the user navigates within the app.

What am I doing wrong here?

**Comment by brentvatne** [comment]
hi! please read and follow the issue template. issues here are only for bugs. if you have a question then please refer to http://reactnavigation.org/help
