### ISSUE TITLE
react-native-web: Warning: React does not recognize the `headerMode` prop on a DOM element.

### ISSUE THREAD

**Issue by raarts** [react-navigation/react-navigation#3488]
I know it's not officially supported, but it was one of the original design objectives, so I put it in anyways. I made it very easy to reproduce.

### Current Behavior

Running on react-native-web results in warnings:

    Warning: React does not recognize the `headerMode` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `headermode` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

And the same for `cardStyle`, `transitionConfig`, `getScreenDetails`, `leftInterpolator`, `titleInterpolator` and `rightInterpolator`.

### Expected Behavior

no warnings

### How to reproduce

Download[ this script](https://gist.github.com/raarts/8b8637a2a2a04a2ce54214554b1b3468), and make it executable:

    curl -s https://gist.githubusercontent.com/raarts/8b8637a2a2a04a2ce54214554b1b3468/raw/ab08443947daee4d5202460d8ebd966ab8d25db7/create-expo-web-app > create-expo-web-app
    chmod +x create-expo-web-app
    ./create-expo-web-app testapp
    cd ./testapp
    yarn start

(The script creates a combined minimum source tree for react-native, react-native-web and includes react navigation)

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.3
| react-native     | 0.52.0
| node             | v9.5.0
| yarn          | 1.3.2

**Comment by brentvatne** [comment]
hi @raarts, I appreciate you opening these but I'm afraid they create noise in the bug reports. are you interested in maintaining react-native-web support in react-navigation? we currently have nobody on the team that will own this and so it doesn't make sense for us to leave issues open for it. I'd really love for someone to help out on this but unless you or someone else steps up to take that role I'll have to close these issues

**Comment by raarts** [comment]
Oh dear. Yes I can work on it, but I don't have a lot of JavaScript experience. Is there somewhere where the crew hands out so I can ask questions?

**Comment by brentvatne** [comment]
yup! ping me on the discord channel. https://discordapp.com/invite/4xEK3nD

**Comment by rjp44** [comment]
I need some of this stuff to work for a project so would be happy to take a look and submit pull requests.

**Comment by raarts** [comment]
@rjp44 any specific areas? I have been putting in pull requests already, and am making progress.

**Comment by raarts** [comment]
@rjp44 Ping me on the [slack channel](expo-developers.slack.com) if you want to chat.

**Comment by rjp44** [comment]
Hmm, I'm not on that slack channel.

**Comment by raarts** [comment]
You should be able to create an account

**Comment by rjp44** [comment]
Not going to create an account and add yet another messaging channel to my life to [communicate with one person about a single issue ](https://xkcd.com/1810/). Happy to contribute fixes to these issues as they are affecting me, but if you have already done so then I'll leave it there.

**Comment by brentvatne** [comment]
@raarts - I believe this is fixed now with some cleanup I did for header, but I may be wrong

**Comment by raarts** [comment]
Yes, this does not happen for me any more.

**Comment by txs** [comment]
How do you fix the issue

**Comment by txs** [comment]
@brentvatne @raarts  How is this issue solved? May you please help out? Thanks!

**Comment by raarts** [comment]
@txs we might be able to help you out but we would need more information. Version numbers, code example, etc.

**Comment by txs** [comment]
I followed this tutorial and install react-native-web with their webpack setup. But I didn't patch the package since I don't have the issue that needs to patch

**Comment by raarts** [comment]
(Note: you can use triple backticks (\`\`\`) around your code to properly format it.)

> But I didn't patch the package since I don't have the issue that needs to patch

Which issue are you referring to?

And which version of React Navigation are you using?
