### ISSUE TITLE
react-native-web: Uncaught (in promise) Unsupported platform

### ISSUE THREAD

**Issue by raarts** [react-navigation/react-navigation#3489]
I know it's not officially supported, but it was one of the original design objectives, so I put it in anyways. I made it very easy to reproduce.

### Current Behavior

Running on react-native-web results this warning:

```
Uncaught (in promise) Unsupported platform
Promise.then (async) 
  | componentDidMount | @ | createNavigationContainer.js?cd8b:13
  | commitLifeCycles | @ | react-dom.development.js?cada:11505
  | commitAllLifeCycles | @ | react-dom.development.js?cada:12294
  | callCallback | @ | react-dom.development.js?cada:1299
  | invokeGuardedCallbackDev | @ | react-dom.development.js?cada:1338
  | invokeGuardedCallback | @ | react-dom.development.js?cada:1195
  | commitAllWork | @ | react-dom.development.js?cada:12415
  | workLoop | @ | react-dom.development.js?cada:12687
  | callCallback | @ | react-dom.development.js?cada:1299
  | invokeGuardedCallbackDev | @ | react-dom.development.js?cada:1338
  | invokeGuardedCallback | @ | react-dom.development.js?cada:1195
  | performWork | @ | react-dom.development.js?cada:12800
  | scheduleUpdateImpl | @ | react-dom.development.js?cada:13185
  | scheduleUpdate | @ | react-dom.development.js?cada:13124
  | scheduleTopLevelUpdate | @ | react-dom.development.js?cada:13395
  | updateContainer | @ | react-dom.development.js?cada:13425
  | (anonymous) | @ | react-dom.development.js?cada:17105
  | unbatchedUpdates | @ | react-dom.development.js?cada:13256
  | renderSubtreeIntoContainer | @ | react-dom.development.js?cada:17104
  | render | @ | react-dom.development.js?cada:17129
  | (anonymous) | @ | index.js?1fdf:1
  | (anonymous) | @ | bundle.js:3870
  | __webpack_require__ | @ | bundle.js:679
  | fn | @ | bundle.js:89
  | (anonymous) | @ | bundle.js:3605
  | __webpack_require__ | @ | bundle.js:679
  | (anonymous) | @ | bundle.js:725
  | (anonymous) | @ | bundle.js:728

```

### Expected Behavior

no warnings

### How to reproduce

Download[ this script](https://gist.github.com/raarts/8b8637a2a2a04a2ce54214554b1b3468), and make it executable:

    curl -s https://gist.githubusercontent.com/raarts/8b8637a2a2a04a2ce54214554b1b3468/raw/ab08443947daee4d5202460d8ebd966ab8d25db7/create-expo-web-app > create-expo-web-app
    chmod +x create-expo-web-app
    ./create-expo-web-app testapp
    cd ./testapp
    yarn start

(The script creates a combined minimum source tree for react-native, react-native-web and includes react navigation)

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.3
| react-native     | 0.52.0
| node             | v9.5.0
| yarn          | 1.3.2

**Comment by brentvatne** [comment]
let me know if you need anything from me for this @raarts

**Comment by raarts** [comment]
This was fixed but for the life of me I can't remember where and when exactly. In any case, it's fixed.

**Comment by miamoin** [comment]
what is command for windows
