### ISSUE TITLE
react-native-web: Error: Can't resolve 'react-native-web/dist/exports/DeviceInfo'

### ISSUE THREAD

**Issue by raarts** [react-navigation/react-navigation#3490]
I know it's not officially supported, but it was one of the original design objectives, so I put it in anyways. I made it very easy to reproduce.

### Current Behavior

Without proper measures, the following errors happens:

```
ERROR in ./node_modules/react-native-safe-area-view/index.js
Module not found: Error: Can't resolve 'react-native-web/dist/exports/DeviceInfo' in '/Users/raarts/work/apptest/node_modules/react-native-safe-area-view'
 @ ./node_modules/react-native-safe-area-view/index.js 1:1276-1327
 @ ./node_modules/react-navigation/src/react-navigation.js
 @ ./src/App.js
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/index.js

ERROR in ./node_modules/react-native-tab-view/src/TabViewPagerAndroid.js
Module not found: Error: Can't resolve '/Users/raarts/work/apptestsrc/compat/ViewPagerAndroid' in '/Users/raarts/work/apptest/node_modules/react-native-tab-view/src'
 @ ./node_modules/react-native-tab-view/src/TabViewPagerAndroid.js 1:1024-1088
 @ ./node_modules/react-native-tab-view/src/index.js
 @ ./node_modules/react-navigation/src/views/TabView/TabBarTop.js
 @ ./node_modules/react-navigation/src/react-navigation.js
 @ ./src/App.js
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/index.js
webpack: Failed to compile.
```

This is caused by react-native-web not exporting those modules. I created a few around it by adding that section in webpack, and creating two files in src/compat: 

src/compat/DeviceInfo.web.js:
```
const DeviceInfo = {
  type: 'screen',
}

export {
  DeviceInfo
}
```

src/compat/ViewPagerAndroid.web.js:
```
const ViewPagerAndroid = {
  type: 'screen',
}

export {
  ViewPagerAndroid
}
```

But that is of course not how it should be done.

Note that the maintainer of react-native-web sees reasons not to provide these exports: necolas/react-native-web#801

### Expected Behavior

That it works.

### How to reproduce

Download[ this script](https://gist.github.com/raarts/8b8637a2a2a04a2ce54214554b1b3468), and make it executable:

    curl -s https://gist.githubusercontent.com/raarts/8b8637a2a2a04a2ce54214554b1b3468/raw/ab08443947daee4d5202460d8ebd966ab8d25db7/create-expo-web-app > create-expo-web-app
    chmod +x create-expo-web-app
    ./create-expo-web-app testapp
    cd ./testapp
    yarn start

(The script creates a combined minimum source tree for react-native, react-native-web and includes react navigation)

Now: comment out the following section from webpack.config.js:

        // This is to make react-navigation work with react-native-web
        ['transform-imports', {
          'react-native': {
            'transform': function(importName) {
                           if (importName === 'DeviceInfo' || importName == 'ViewPagerAndroid') {
                             return appDirectory + '/src/compat/' + importName;
                           }
                           return 'react-native-web';
                         },
              skipDefaultConversion: true,
            }
          }
      ],

and try `yarn start`

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.3
| react-native     | 0.52.0
| node             | v9.5.0
| yarn          | 1.3.2

**Comment by brentvatne** [comment]
let me know if you need anything from me for this fix @raarts

**Comment by raarts** [comment]
The first warning is fixed by https://github.com/react-community/react-native-safe-area-view/pull/18. And released, so that one is done with.

The second warning is fixed in https://github.com/react-native-community/react-native-tab-view/pull/450, but not released yet. This is due to the fact that master contains a breaking API change. I promised to help with that repo, but I did not have the time for that yet. Maybe the breaking API change can be moved to a branch, and an intermediate release can be done, I don't know, I'll propose it to @satya164 .

**Comment by brentvatne** [comment]
@satya164 - maybe when working on tabview related things you can bump the version and use `jumpTo` in reactnav?

**Comment by booboothefool** [comment]
After doing:

    create-react-native-app myapp --with-web-support
    yarn add react-navigation

And using the starter code:

    import React from 'react';
    import { StyleSheet, Text, View } from 'react-native';
    import { createStackNavigator } from 'react-navigation';
    
    class HomeScreen extends React.Component {
      render() {
        return (
          <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
            <Text>Home Screen</Text>
          </View>
        );
      }
    }
    
    const RootStack = createStackNavigator({
      Home: {
        screen: HomeScreen
      },
    });
    
    export default class App extends React.Component {
      render() {
        return <RootStack />;
      }
    }
    
    const styles = StyleSheet.create({
      container: {
        flex: 1,
        backgroundColor: '#fff',
        alignItems: 'center',
        justifyContent: 'center',
      },
    });

I am getting the following error for `react-native-web`:

    ERROR in ./node_modules/react-navigation-deprecated-tab-navigator/node_modules/react-native-tab-view/src/TabViewPagerAndroid.js
    Module not found: Error: Can't resolve 'react-native-web/dist/exports/ViewPagerAndroid' in '/Users/a/projects/mission/client2/node_modules/react-navigation-deprecated-tab-navigator/node_modules/react-native-tab-view/src'
     @ ./node_modules/react-navigation-deprecated-tab-navigator/node_modules/react-native-tab-view/src/TabViewPagerAndroid.js 1:965-1022
     @ ./node_modules/react-navigation-deprecated-tab-navigator/node_modules/react-native-tab-view/src/index.js
     @ ./node_modules/react-navigation-deprecated-tab-navigator/src/views/TabView.js
     @ ./node_modules/react-navigation-deprecated-tab-navigator/src/index.js
     @ ./node_modules/react-navigation/src/react-navigation.js
     @ ./src/App.js
     @ ./src/index.js
     @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/index.js
    webpack: Failed to compile.

@raarts Can you clarify how I can get `react-navigation` working with `react-native-web`?

**Comment by raarts** [comment]
This is caused by react-navigation-deprecated-tab-navigator pulling in a version of react-native-tab-view that predates the web-support. Mentioning @brentvatne, he probably knows more about this. 
For the moment you can do the following:

Create `./node_modules/react-navigation-deprecated-tab-navigator/node_modules/react-native-tab-view/src/TabViewPagerAndroid.web.js` with the following contents:

```
import React from 'react';
import { Text } from 'react-native';

export default class TabViewPagerAndroid<T: *> extends React.Component<
  Props<T>
> {
  render() {
    return (
      <Text>The TabViewPagerAndroid is not supported on React Native Web</Text>
    );
  }
}``` 

That should fix your compile error.

**Comment by booboothefool** [comment]
@raarts Thank you for the help.

Here is what I did exactly:
```
create-react-native-app myapp --with-web-support
cd myapp
yarn add react-navigation
cd node_modules/react-navigation-deprecated-tab-navigator
yarn add react-native-tab-view
cd node_modules/react-native-tab-view/src
```
I then checked `TabViewPagerAndroid.web.js` and the contents are similar to the one you posted.

At this point, I am able to run `yarn run web` and it compiles successfully, but when I try the following code in App.js:
```
import React from 'react';
import { View, Text } from 'react-native';
import { createStackNavigator } from 'react-navigation';

class HomeScreen extends React.Component {
  render() {
    return (
      <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
        <Text>Home Screen</Text>
      </View>
    );
  }
}

export default createStackNavigator({
  Home: {
    screen: HomeScreen
  },
});
```

There are no errors, but it renders a blank screen. Any advice?

**Comment by raarts** [comment]
I did exactly the same, and I too got a blank screen, but I *did* get an error:

```
invariant.js?7313:42 Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

Check the render method of `StackViewLayout`.
    at invariant (invariant.js?7313:42)
    at createFiberFromElementType (react-dom.development.js?cada:8185)
    at createFiberFromElement (react-dom.development.js?cada:8130)
    at createChild (react-dom.development.js?cada:8832)
    at reconcileChildrenArray (react-dom.development.js?cada:9132)
    at reconcileChildFibers (react-dom.development.js?cada:9495)
    at reconcileChildrenAtPriority (react-dom.development.js?cada:10127)
    at reconcileChildren (react-dom.development.js?cada:10118)
    at updateHostComponent (react-dom.development.js?cada:10370)
    at beginWork (react-dom.development.js?cada:10609)
react-dom.development.js?cada:8305 The above error occurred in the <div> component:
    in div (created by View)
    in View (at StackViewLayout.js:384)
    in StackViewLayout (at withOrientation.js:30)
    in withOrientation (at StackView.js:58)
    in div (created by View)
    in View (at Transitioner.js:146)
    in Transitioner (at StackView.js:22)
    in StackView (at createNavigator.js:96)
    in Navigator (at createKeyboardAwareNavigator.js:11)
    in KeyboardAwareNavigator (at createNavigationContainer.js:387)
```

I also tried several other react navigation 2 examples, but they all have the same error.  Haven't been able to track the source yet

**Comment by raarts** [comment]
@booboothefool can you create a new issue for your remaining problem? And close this one if you agree?

**Comment by luandro** [comment]
I've been searching for a while for a way to build universal (web + mobile) apps and a router that could work on both. You guys think `react-navigation` is ready? Or should we use a routing solution for web and different one for mobile?

Thanks for the awesome tests you guys have been doing 👍

**Comment by raarts** [comment]
Yes, I think so, I already used v1 in an application like you describe. v2 is just released and needs to settle down a little though. Also, `react-navigation` _is_ the official router for react-native.

**Comment by carlbarrdahl** [comment]
`yarn upgrade --latest` worked for me

Here's the dependency diff:
```
  "dependencies": {
    "expo": "^27.0.1",
    "expo-web": "^0.0.12",
    "react": "16.3.1",
    "react-dom": "16.0.0",
    "react-native": "~0.55.2",
    "react-native-web": "^0.4.0",
    "react-navigation": "^2.5.3",
    "webpack": "^3.11.0",
    "webpack-dev-server": "2.9.4"
  }
```

```
  "dependencies": {
    "expo": "^28.0.0",
    "expo-web": "^0.0.14",
    "react": "16.4.1",
    "react-art": "^16.4.1",
    "react-dom": "16.4.1",
    "react-native": "~0.55.2",
    "react-native-web": "^0.8.5",
    "react-navigation": "^2.5.3",
    "webpack": "^4.12.2",
    "webpack-dev-server": "3.1.4"
  }
```
(also had to install `react-art`)

**Comment by curiousdustin** [comment]
@slampenny , I'm getting the same error.

After adding that alias to webpack.config.js, it DOES compile, but then I get a bunch of other errors. Is there anything else you had to do?

`Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
Check the render method of 'SceneView'.`

`The above error occurred in the <SceneView> component:
 in SceneView (at SwitchView.js:12)`

`Uncaught Error: A cross-origin error was thrown. React doesn't have access to the actual error object in development. See https://fb.me/react-crossorigin-error for more information.`

`The above error occurred in the <NavigationContainer> component:
    in NavigationContainer (at Root.js:14)`

**Comment by valstu** [comment]
@curiousdustin I had the same error. After switching to older version `2.13.0` of `react-navigation` i got it working

**Comment by proof666** [comment]
> 'react-native-web/dist/exports/MaskedViewIOS': 'react-native-web/dist/index.js',

Man, you make may day! Thank you!

**Comment by murad-faridi** [comment]
You have to run this command

npm i react-native-web

Error will be resolved

**Comment by artokun** [comment]
@slampenny that did the trick for me!

For those needing a complete solution here's the code

```js
const createExpoWebpackConfigAsync = require("@expo/webpack-config");

module.exports = async function(env, argv) {
  const config = await createExpoWebpackConfigAsync(env, argv);
  // Customize the config before returning it.

  config.resolve = {
    ...config.resolve,
    alias: {
      "react-native-web/dist/exports/MaskedViewIOS": "react-native-web/dist/index.js",
    },
  };

  return config;
};
```
