### ISSUE TITLE
Allow custom elements be placed after SafeAreaView

### ISSUE THREAD

**Issue by ArsenyYankovsky** [react-navigation/react-navigation#3493]
Hey,

So my use case is the following. I have this offline thing on top of my screens:

![rsz_screenshot_1518292144](https://user-images.githubusercontent.com/1508345/36066083-203aa298-0ea4-11e8-8570-c2eeeea92a68.png)

Which I achieve by doing following in my App.js:

```
    <SafeAreaView/>
    <NetworkStatus isOffline={this.state.isOffline}/>
    <RootNavigation />
```

This works fine on Android, but on iOS I get some additional padding on the header which looks like this:

![rsz_2s6a5205_k](https://user-images.githubusercontent.com/1508345/36066550-cdc95c0e-0eab-11e8-93f1-afee164f5e76.jpg)

I have a pull request from my fork which I use right now: https://github.com/react-navigation/react-navigation/pull/3492
It's probably not something that will get merged as it is not the best solution, but that fixes an issue for me. 
Should probably let users add SafeAreaView themselves instead of just adding it to all the headers.

**Comment by brentvatne** [comment]
i think we want to default to using safe area view and alternatively let people opt-out. you could also manually set the status bar height for safe area view to 0 so it doesn't have any insets: https://github.com/react-community/react-native-safe-area-view/blob/2c5f497188ff9c59c6bd9f9c9ce63ce28c609236/index.js#L98-L100

a better place to discuss changes like this is on https://github.com/react-navigation/rfcs
