### ISSUE TITLE
Hide React Navigation only for Android Platform

### ISSUE THREAD

**Issue by saman-ghm** [react-navigation/react-navigation#3497]
In order to hide React Navigation I'm using the code below:

```
static navigationOptions = {
    header: null
 };
```
Fortunately it's working fine, but the problem appears when I want to differentiate between android and iOS based on their different UX, I want to hide the Navigation bar only in android platform:

```
static navigationOptions = {
    header: Platform.OS === 'android' ? null: /* don't know what to write here :( */,
 };
```
The piece I've commented above is executed for iOS. Any idea?

**Comment by satya164** [comment]
```js
static navigationOptions = {
   ...Platform.select({
    android: { header: null }
   }),
 };
```
