### ISSUE TITLE
Hardware Back Button issue on a Hidden tabBar Screen 

### ISSUE THREAD

**Issue by Kida007** [react-navigation/react-navigation#3498]
I just have a Simple **TabNavigator**, In which one of the Tabs navigate to a screen with **Hidden TabBar** .  which i achieved using this :
`
Trip: {
       screen:Trip,
       navigationOptions:{
         tabBarLabel:'Start',
         tabBarVisible: false
       }
     }
`

Now When i press **hardware Back Button** it crashes with :
`TypeError: undefined is not an object (evaluating '_this3._component.setNativeProps')
`
and if it make it Visible, it works just fine i.e navigates to the first Tab Screen.

**Comment by iloo123** [comment]
Why do you have `tabBarLabel:'Start'` when you're hiding it ?

**Comment by iloo123** [comment]
Try this
`import { Platform, BackHandler } from 'react-native'`
`componentWillMount() {
        if (Platform.OS !== 'android') return
        BackHandler.addEventListener('hardwareBackPress', () => {
            const { dispatch } = this.props
            dispatch({ type: 'Navigation/BACK' })
            return true
        })
    }

    componentWillUnmount() {
        if (Platform.OS === 'android') BackHandler.removeEventListener('hardwareBackPress')
    }`

**Comment by Kida007** [comment]
Thanks @iloo123 for reply .
I tried BackHandler on that Specific Tab Screen.
Apparently BackHandler doesn't work inside TabNavigator (for me atleast). 

I want to achieve something like this :
https://user-images.githubusercontent.com/1212023/30512323-8b68168a-9b0a-11e7-8779-7f094b1a2150.png

Which I can think better be achieved by Custom TabBar .

But I still Think Back Button on Hidden TabBar Screen Working ideally .

**Comment by iloo123** [comment]
Try this. 
```
  static navigationOptions = ({navigation}) => ({
    tabBarVisible: false,
    headerLeft: (<View style={{paddingLeft: 25}}><TouchableOpacity onPress={() => navigation.goBack()}>
    <Image source={require('./icons/back.png')} style={{width: 20, height: 20, resizeMode: 'contain'}} />
    </TouchableOpacity></View>),
    headerTitle: <View>
                  <Text style={styles.titleStyle}>Account Settings</Text>
                </View>,
  })
```

**Comment by Kida007** [comment]
thanks for the reply! 
but does that solve the problem of 'hardwareBackButton' ?
