### ISSUE TITLE
TabNavigator does not work as expected when placed inside a DrawerNavigator

### ISSUE THREAD

**Issue by HardikDhanani** [react-navigation/react-navigation#3499]
### Current Behavior

I am having trouble with this setup:
```
- Root (StackNavigator)
 	|- Unauthorised (StackNavigator)
	|	|- Login
  	|	|- Reset Password
	|
 	|- Authorised (DrawerNavigator)
		|- Home (TabNavigator)
		|	|- TabContact (StackNavigator)
		|	|	|-  List View
   		|	|	|-  View Details
    		|	|	|-  Add New Item
		|       |
   		|	|- TabChat (StackNavigator)
		|	|	|-  List View
   		|	|	|-  Conversation List
    		|	|	|-  Chat Detail Page
		|       |
   		|	|- TabGroup (StackNavigator)
		|		|-  List View
    		|		|-  View Details
    		|		|-  Add New Item
		|
		|- Settings (StackNavigator)
			|- Setting Page
```

While I navigate on the drawer items, I am getting an error: 

![simulator screenshot - iPhone 6 - 2018-02-12 at 12 26 06](https://user-images.githubusercontent.com/19322214/36086266-440aef72-0ff1-11e8-944b-97a50fe47700.png)

### Expected Behavior
- It should navigate to the last active page on the tab stack.

### How to reproduce
- When the app loads, it takes me to the unauthorized page.
- I press on login button and it navigates to the `Authorized > Home > TabContact`
- I navigated to the tab index > 0 (any of the tab other than the first one)
- I opened the drawer and navigated to the other drawer item. `Settings` in this case
- I opened the drawer and again navigated to `Home`, and this error comes up.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.3
| react-native     |  0.53.0
| node             | 8.9.3
| npm or yarn      | 5.5.1

**Comment by brentvatne** [comment]
hello! as per the issue template, please provide an example that we can run. i can't tell if you intended to do that and forgot (as you refer to an app in the issue). please re-create this issue with a way to reproduce, thanks!

**Comment by janrop** [comment]
I was able to reproduce the error:

https://snack.expo.io/@janrop/drawernavigator-test

It occurs (at least for me) only if the Screen of the first Tab is itself a Stacknavigator.

Steps to reproduce: 
* Go to the second or third tab
* Open the Drawer
* Go To "InDrawer"
* Open the Drawer
* Try to return to "Tabs"
