### ISSUE TITLE
Unable to center the Navbar indicator after giving a custom size

### ISSUE THREAD

**Issue by iloo123** [react-navigation/react-navigation#3502]
### Current Behavior

![simulator screen shot - iphone 6 - 2018-02-12 at 16 37 19](https://user-images.githubusercontent.com/31450344/36095311-82ccc7b8-1013-11e8-8a36-ac23b9802144.png)
```
indicatorStyle: {
      backgroundColor: '#1ef7c1',
      top: 0,
      width: 40,
      marginLeft: 42
    },
```
### Expected Behavior

![simulator screen shot - iphone 6 - 2018-02-12 at 16 38 57](https://user-images.githubusercontent.com/31450344/36095369-c518e4f8-1013-11e8-8ad8-a5f6ce42d711.png)

### How to reproduce
I think it would be possible if following code works

```
    indicatorStyle: {
      backgroundColor: '#1ef7c1',
      top: 0,
      width: 40,
      alignContents: 'center'
    },
```

### My Environment

| software         | version
| ---------------- | -------
| react-navigation | ^1.0.0-beta.26
| react-native     | 0.51.0
| node             | 9.4.0
| npm or yarn      | 5.6.0

**Comment by brentvatne** [comment]
hi @iloo123! please re-create this issue with a runnable example that we can reproduce this with. the above code is a good start but without all of those screens we still have to do a bunch of work to reproduce the bug. we can't really do this for every issue, it's much easier for hundreds of people reporting bugs to provide a repro for their bug than it is for a few react navigation core team members to reproduce hundreds of bugs that people report. thanks!

**Comment by liwenDeng** [comment]
hi @brentvatne, I have also met this situation, and i created a [demo here](https://snack.expo.io/HywWFKoy7), could you help me?

**Comment by hirthbrian** [comment]
For my work workaround I use Dimensions.

```
indicatorStyle: {
        backgroundColor: '#1ef7c1',
        width: 40,
        left: Dimensions.get('window').width / 12,
        width: Dimensions.get('window').width / 6,
        // alignItems: 'center'
        // marginLeft: 37, 
     }
```

In TabBar the indicator is 'absolute' so you can't do much without changing the code directly in react-native-tab-view. If anyone have a better solution please correct me :)
