### ISSUE TITLE
Memory leak when switching between DrawerNavigator screens

### ISSUE THREAD

**Issue by Billydubb** [react-navigation/react-navigation#3503]
## The issue tracker is reserved for bug reports only.

If you have a question, feature request, or an idea for improving the library or its related tools, please try one of the following resources:

- [Read the documentation](https://reactnavigation.org/)
- [Post an issue to the website repository if you'd like to see a documentation change](http://github.com/react-navigation/website)
- [Post a feature request to Canny](https://react-navigation.canny.io/feature-requests)
- [Write a RFC if you have ideas for how to implement a feature request](https://github.com/react-navigation/rfcs)
- [Get help on Discord chat (#react-navigation on Reactiflux)](https://discord.gg/4xEK3nD) or [on StackOverflow](https://stackoverflow.com/questions/tagged/react-navigation)
- Search for your issue - it may have already been answered or even fixed in the development branch. However, if you find that an old, closed issue still persists in the latest version, you should open a new issue.

---

####  What code are you running and what is happening?
Here is a minimal working example of DrawerNavigator with two screens:

```
import React from 'react';
import {
	Text,
	View,
} from 'react-native';

import * as Keychain from 'react-native-keychain';
import {DrawerNavigator} from 'react-navigation';


class FirstScreen extends React.Component{

	render(){
		return(
			<View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
				<Text>FirstScreen</Text>
		  </View>
		)};
}


class SecondScreen extends React.Component{
	
	render(){
		return(
			<View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
				<Text>SecondScreen</Text>
		  </View>
		)};
}

const MainDrawerNavigator = DrawerNavigator({
	FirstScreen:{
		screen: FirstScreen
	},
	SecondScreen: {
		screen: SecondScreen
	}
});
  


export default class ReactNavigationExample extends React.Component {	

	render() {
		return (
			<View style={{flex: 1}}>
				<MainDrawerNavigator/>
			</View>
		);
	}

}
```

When I repeatedly switch between the two screens, the memory consumption of the app increases with every switch. The memory never decreases after that, even when keeping the app running for 10, 20 or 60 minutes. This points to a memory leak.

Once the app consumes too much memory, it crashes with an out of memory error.

I'm logging the memory consumption in the terminal with:
`adb shell dumpsys meminfo com.rnplayground` (com.rnplayground is the package name of my project)

#### Include a screenshot if it makes sense.

This is the output of the adb command to log memory usage of running processes. The amount next to TOTAL is the relevant number (90974 kb).  When the app was started, before switching back and forth between the two screens, the memory usage was at around 60000 kb

![screen shot 2018-02-12 at 1 44 54 pm](https://user-images.githubusercontent.com/1459741/36097378-087a2996-0ffb-11e8-889f-15db64e71804.png)

#### What do you expect should be happening? 
The memory consumption should not increase with every switch between screens.

### How to reproduce

Simply run the code example provided above and keep switching between the two screens.
To log the memory consumption run the following in the terminal:
`while sleep 1; do adb shell dumpsys meminfo com.rnplayground; done` (replace com.rnplayground with the package name of your app)

This will log the memory consumption every second.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.23
| react-native     | 0.52.0
| node             |  6.9.0
| npm or yarn      | yarn

**Comment by ericvicenti** [comment]
Hey, thanks for providing detailed info on how to reproduce this! I'll play with it soon and try to hunt down the problem. Hopefully its a simple bug in our Drawer navigator and not some insidious native issue.

**Comment by jr-k** [comment]
Even without the drawer, just setup 2 screens and switch between them with `this.props.navigation.navigate` and the memory rises up.

**Comment by satya164** [comment]
> just setup 2 screens and switch between them with this.props.navigation.navigate

That'll push new screens to the stack, not switch between them.

**Comment by Billydubb** [comment]
Does the drawer in react-navigation reuse old views or does it create new ones every time you switch between them?

**Comment by jr-k** [comment]
@satya164 good point, missed that point sorry

**Comment by jr-k** [comment]
I found some other issues, this time I don't think I'm doing anything wrong. I've setup a simple TabNavigator, when I'm switching between 2 tabs memory increases over and over. Plus if animationEnabled is true for the TabNavigator, memory increases faster.

**Comment by Billydubb** [comment]
I think DrawerNavigator uses TabNavigator in its implementation, so the problem seems to lie with the TabNavigator

**Comment by brentvatne** [comment]
I could not repro this on 1.4.0. It reuses the views.

I inspected memory usage on both iOS and Android after switching between two drawer routes thousands of times and once GC settled it was roughly the same.

**Comment by Billydubb** [comment]
@brentvatne Just checked. Leak seems to be fixed. Thanks

**Comment by solominh** [comment]
react-navigation version 1.5 latest
I have a simple case of memory leak

Drawer={
stack1 : screen1stack1, screen1stack2, screen3stack1
stack2: screen1stack2, screen2Stack2
}
- screen1stack1  => go to screen2stack1 is a WebView and play audio => goto screen3stack1, audio still playing
- then open drawer and go to stack2, audio still playing
- open drawer and go to stack1, audio still playing and no way to stop it

**Comment by ashutosh-akss** [comment]
@brentvatne & @ericvicenti  I am also getting huge memory leak while using StackNavigator

used chrome dev tools, every time i navigate to component and come back it creates a new object and keeps it 

can we check this for StackNavigator .

<img width="1147" alt="screen shot 2018-07-26 at 9 11 50 pm" src="https://user-images.githubusercontent.com/11007583/43272849-978bdf78-9118-11e8-8b1a-446d08ec6103.png">

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
