### ISSUE TITLE
How to change drawerPosition dynamically?

### ISSUE THREAD

**Issue by NaseebullahSafi** [react-navigation/react-navigation#3504]
The issue is, I want to dynamically change the drawer's position between left and right based on a click event.

However DrawerNavigator doesn't accept any params where I can pass the position. So the question really is, how can we change that dynamically?

AppNavigation.js
=
```js
export const SignedOut = StackNavigator({   
  SignIn: {    
    screen: Login,
        navigationOptions: {     
      header: null    
    }   
  }  
});

  
export const SignedIn = DrawerNavigator({   
  Home: {    
    screen: LaunchScreen   
  }  
}, {   
  contentComponent: CustomSideMenu, // this is the side menu that slides from left.
    
});


  
const PrimaryNav = StackNavigator({   
  SignedIn: {    
    screen: SignedIn,
        navigationOptions: {     
      gesturesEnabled: false    
    }   
  },
     SignedOut: {    
    screen: SignedOut,
        navigationOptions: {     
      gesturesEnabled: false    
    }   
  },
     Loading: {    
    screen: Loading   
  }  
}, {   
  headerMode: "none",
     mode: "modal",
     initialRouteName: "Loading"  
});

  
export default PrimaryNav;
```

LaunchScreen.js
=
```js
<TouchableHighlight 
    onPress={()=> { this.props.navigation.navigate('DrawerToggle') }}
  <Ionicons style={{padding: 8}} name="menu" size={22} color="#bccad0" />
</TouchableHighlight>
```

I've tried pushing this question towards SO.

**Comment by brentvatne** [comment]
you cannot do this. it is defined statically at the moment. you're welcome to submit a PR or open a feature request on http://react-navigation.canny.io/ if you'd like this!

**Comment by baselbj** [comment]
to do that I had to made 2 drawer component (right and left). and dynamically call the one I need.

**Comment by nikolal** [comment]
If anyone needs this, please vote at:

https://react-navigation.canny.io/feature-requests/p/dynamic-drawerposition

**Comment by mikeKane** [comment]
@baselbj Can you elaborate a bit more? I'm kind of new and would like to accomplish this, would I be able to set a new component with the 2nd nav component?

**Comment by Prince-Hamza** [comment]
> to do that I had to made 2 drawer component (right and left). and dynamically call the one I need.

how to call them dynamically ?
