### ISSUE TITLE
Navigation.navigate params can't be passed

### ISSUE THREAD

**Issue by wellyshen** [react-navigation/react-navigation#3505]
### Current Behavior

I wrap my three StackNavigator in a TabNavigator. Then I pass a param from one of the `Home` StackNavigator through `navigation.navigate('MyWorkouts', { test: 'HELLO!' })` to the `MyWorkouts` StackNavigator. I can't get the passed param from the `MyWorkouts` StackNavigator. Now I use redux for passing the param between two StackNavigator instead.

Here's my navigation structure:
```javascript
import { StackNavigator, TabNavigator } from 'react-navigation';

import {
  HomeScreen,
  MyWorkoutsScreen,
  SettingsScreen,
  PlayerScreen
} from '../screens';
import styles from './Navigator.styles';

const commonOptions = {
  headerStyle: styles.header,
  headerTitleStyle: styles.headerTitle
};

const Home = StackNavigator(
  { Home: { screen: HomeScreen } },
  { navigationOptions: commonOptions }
);

const MyWorkouts = StackNavigator(
  { MyWorkouts: { screen: MyWorkoutsScreen } },
  { navigationOptions: commonOptions }
);

const Settings = StackNavigator(
  { Settings: { screen: SettingsScreen } },
  { navigationOptions: commonOptions }
);

const MainScreenNavigator = TabNavigator(
  {
    Home: { screen: Home },
    MyWorkouts: { screen: MyWorkouts },
    Settings: { screen: Settings }
  },
  {
    tabBarOptions: { style: styles.tab, showLabel: false }
  }
);

export default StackNavigator(
  {
    Main: { screen: MainScreenNavigator },
    Player: { screen: PlayerScreen }
  },
  {
    navigationOptions: { header: null },
    mode: 'modal'
  }
);
```

react-navigation: v1.0.0
react-native: v0.53.0
node: v9.5.0
yarn: v1.3.2

**Comment by brentvatne** [comment]
hi @wellyshen! please re-create this issue with a runnable example that we can reproduce this with. the above code is a good start but without all of those screens we still have to do a bunch of work to reproduce the bug. we can't really do this for every issue, it's much easier for hundreds of people reporting bugs to provide a repro for their bug than it is for a few react navigation core team members to reproduce hundreds of bugs that people report. thanks!
