### ISSUE TITLE
Back button performance issues when using remote js debugging

### ISSUE THREAD

**Issue by maxlang** [react-navigation/react-navigation#3509]
### Current Behavior

I'm running a simple StackNavigator. These files are compiled with typescript, but the result is essentially the same, just a little harder to read.

`index.tsx:`
```
import { AppRegistry } from 'react-native'
import Root from './app'

AppRegistry.registerComponent('...', () => Root)
```

`app.tsx`
```
import React from 'react'
import { StackNavigator} from 'react-navigation'
import {View, Button, Text} from 'react-native'

class MapScreen extends React.Component {
  static navigationOptions = ({ navigation }) => ({
    title: 'Map',
    headerRight: (
      <Button
        onPress={() => navigation.navigate('Settings')}
        title='Info'
      />
    ),
  })

  render() {
    return (
      <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
        <Text>Map Screen</Text>
      </View>
    )
  }
}

class SettingsScreen extends React.Component {
  static navigationOptions = {
    title: 'Settings',
  }

  render() {
    return (
      <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
        <Text>Settings Screen</Text>
      </View>
    )
  }
}

const appRouteConfigs = {
  Map: {
    screen: MapScreen,
  },
  Settings: {
    screen: SettingsScreen,
  },
}

// tslint:disable-next-line:variable-name
const AppNavigator = StackNavigator(appRouteConfigs)

class Root extends React.Component {
  render() {
    return (
      <AppNavigator />
    )
  }
}

export default Root
```

### Expected Behavior

I expect to be able to click the "Info" button to go to the "Settings" screen, then click the back button in the header and get back to the the "Map" screen quickly.

### How to reproduce

With Remote JS Debugging enabled (and only then), when I go to the "Settings" screen then press the back button to go to the "Map" screen, the transition takes about 10 seconds. I've traced the delay to the `requestAnimationFrame` call added in #3305. When I remove the call to requestAnimationFrame, the transition is instant. It's also instant if I disable remote JS debugging.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.3
| react-native     | 0.52.0
| node             | 8.9.4
| yarn      | 1.3.2

**Comment by mandx** [comment]
I'm experiencing something similar to this, but in my case, the header's back button doesn't work at all with remote JS debugging enabled.

**Comment by orangecoloured** [comment]
I've just updated from `1.0.0-beta.15` to `1.0.3` and experiencing a similar issue on Android. While debugging pressing Back takes up to 1-2 seconds till transition happens.

**Comment by hyperh** [comment]
+1 same issue.

Oddly, just `navigation.navigate(...)` works fine on the simulator, very smooth. But pressing the back button in the nav bar takes 1-2 seconds to work in the simulator.

**Comment by natesymer** [comment]
+1

**Comment by SNY7** [comment]
2.0.1 still has this issue, works fine after stop remote JS debugging

**Comment by brentvatne** [comment]
can someone investigate this? surely of all the interested people someone can find out what the problem is :P

**Comment by brentvatne** [comment]
if this is happening to you, please try removing requestAnimationFrame here https://github.com/react-navigation/react-navigation/blob/9a82706fbafb5b4ddf312a256ff715cdc5280923/src/views/Header/Header.js#L203-L208 and let me know if it resolves your issue

**Comment by trevor-trou** [comment]
+1

**Comment by Faolain** [comment]
+1

**Comment by brentvatne** [comment]
<img width="802" alt="screen shot 2018-09-24 at 10 44 05 am" src="https://user-images.githubusercontent.com/90494/45968801-ca2b0380-bfe6-11e8-98bb-0a21500a5d7c.png">

**Comment by inorichi** [comment]
@brentvatne Yes, if `requestAnimationFrame` is removed it works instantly with the debugger enabled. Also, the ripple effect still works.

**Comment by inorichi** [comment]
@brentvatne Yes, if `requestAnimationFrame` is removed, it works instantly with the debugger enabled. Also, the ripple effect still works.

**Comment by brentvatne** [comment]
ok I will remove that then. tracking in https://github.com/react-navigation/react-navigation-stack/issues/41
