### ISSUE TITLE
willBlur/didBlur events fired when trying to navigate to the current tab

### ISSUE THREAD

**Issue by MichaelBorde** [react-navigation/react-navigation#3511]
### Current Behavior

I have a TabNavigator and i use navigation.addListener to catch events like willBlur or didBlur.

When i try to navigate to the same tab i am actually on willBlur and didBlur events are triggered.

I want to load data on focus event and clean data on blur event. Triggering a blur event when tab is not changed is difficult to handle.

### Expected Behavior

Blur events should be fired only when tab is changed or focus events should follow blur events in this specific case.

### How to reproduce

There is a snack : https://snack.expo.io/@michaelborde/react-navigation-willblur

### Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.3
| react-native     | 0.53.0

## Thoughts

I agree it is not common to navigate to the current screen but i discovered this behaviour with a specific use case. Feel free to close this issue if you think it's irrelevant. For the moment my workaround is to check wether i try to navigate to the current screen or not.

**Comment by satya164** [comment]
Hey, please provide a repro on snack.expo.io

**Comment by satya164** [comment]
So the issue you have is that you're already on "Settings" screen and try to navigate to the same screen again, then you get "willBlur", right? I can repro it on snack. It fires only the first time I try to navigate though.

cc @ericvicenti

**Comment by MichaelBorde** [comment]
That's right. The use case may seem odd but i discovered this behaviour trying to implement a custom tab bar. When i press a tab i navigate to it but i had no guard to prevent navigation to the current tab.

Anyway in that specific use case, the screen blurs but no other screen is focused though i am on a screen actually.

**Comment by brentvatne** [comment]
repros on 2.0 -- @ericvicenti https://snack.expo.io/Hy_mKLApG

**Comment by jozan** [comment]
We encountered this recently when using StackNavigator.

Repro using 2.0: https://snack.expo.io/BkSVTgJCf

**Comment by brentvatne** [comment]
2.0.1 should resolve these issues, with https://github.com/react-navigation/react-navigation/pull/4168
