### ISSUE TITLE
Access to parent's routes from nested navigation (rendered by component)

### ISSUE THREAD

**Issue by OskarKaminski** [react-navigation/react-navigation#3514]
Is it possible to access parent's routes form nested navigation rendered by a component?

Case 1 - Working good - Both `RootStack`'s routes and `RootTab`'s routes accessible from `RootTab`
```
const RootStack = StackNavigator({
  RootTab: { screen: RootTab },
  RootTwo: { screen: RootTwo },
});
const RootTab = TabNavigator({
  ChildStack: { screen: ChildStack }
});
const ChildStack = StackNavigator({
  UserScreen: { screen: UserScreen }
});
```

Case 2 - Working wrong - only `RootTab`'s routes accessible from `RootTab`. No access to `RootStack`'s routes
```
const RootStack = StackNavigator({
  RootTab: { screen: WrapperRootTab },
  RootTwo: { screen: RootTwo },
});
const RootTab = TabNavigator({
  ChildStack: { screen: ChildStack }
});
class WrapperRootTab extends React.Component{
  render(){return <RootTab/>}
}
const ChildStack = StackNavigator({
  UserScreen: { screen: UserScreen }
});
```

Is it possible to access `RootStack`'s routes from `RootTab`'s in the case 2?

**Comment by ericvicenti** [comment]
You're wrapping a navigator improperly. Can you try the following instead?

```
class WrapperRootTab extends React.Component{
  static router = RootTab.router;
  render(){return <RootTab navigation={this.props.navigation} />}
}
```

Feel free to re-open if that doesn't help your issue.

Next time when you file an issue, can you be more specific about *what* you are trying to accomplish, rather than what seems broken? That will help us give you better guidance for your app
