### ISSUE TITLE
Customising Drawer Navigation not working `undefined is not an object`

### ISSUE THREAD

**Issue by javahemans** [react-navigation/react-navigation#3515]
I am trying to customise my `drawerNavigation` and I followed the `official example` on the following page: `https://reactnavigation.org/docs/drawer-navigator.html`

Unfortunately, it is not working for me and I get the following error.
![image](https://user-images.githubusercontent.com/12991664/36171932-41b8bb4a-1169-11e8-9c41-247e36cd34f1.png)

### The problem is `NOT` the `StyleSheet` because I have removed it and then it says: 

![image](https://user-images.githubusercontent.com/12991664/36172153-da9ad3e8-1169-11e8-8fb4-82e59e228c14.png)

### Here is my component and how I made it:

![image](https://user-images.githubusercontent.com/12991664/36171963-5aca2d30-1169-11e8-9022-6336a2cd7a3c.png)

![image](https://user-images.githubusercontent.com/12991664/36171965-5e5243c0-1169-11e8-8327-aa2cc451d55d.png)

### My Environment

```json
{
  "name": "Empiric",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest",
    "devtools": "react-devtools"
  },
  "dependencies": {
    "eslint-config-rallycoding": "^3.2.0",
    "firebase": "^4.8.1",
    "react": "16.0.0-alpha.12",
    "react-native": "0.47.1",
    "react-native-check-box": "^2.0.2",
    "react-native-flexi-radio-button": "^0.2.2",
    "react-native-gridview": "^0.1.1",
    "react-native-modalbox": "^1.4.2",
    "react-native-svg": "^6.0.1-rc.3",
    "react-navigation": "^1.0.3"
  },
  "devDependencies": {
    "babel-jest": "20.0.3",
    "babel-preset-react-native": "2.1.0",
    "jest": "^20.0.4",
    "react-devtools": "^3.0.0",
    "react-test-renderer": "16.0.0-alpha.12"
  },
  "jest": {
    "preset": "react-native"
  }
}

```

| software         | version
| ---------------- | -------
| node             | v6.10.3
| npm or yarn      | 3.10.10

**Comment by brentvatne** [comment]
you imported StyleSheet from react and not react-native

**Comment by javahemans** [comment]
I mentioned above that the problem is not `StyleSheet` even when I am not having any style for my custom drawer navigator it is giving me the `_react.Reac.createElement` error. 

Take a look at this one:

![image](https://user-images.githubusercontent.com/12991664/36235677-f0ab4bac-1256-11e8-886a-1f242c0be84b.png)

Still gives me this error
![image](https://user-images.githubusercontent.com/12991664/36235693-03c145d4-1257-11e8-979c-d7ffc5391e24.png)



```js
import { React } from 'react';
import { ScrollView, StyleSheet } from 'react-native';
import { DrawerItems, SafeAreaView } from 'react-navigation';

const CustomDrawerContentComponent = (props) => (
  <ScrollView>
    <SafeAreaView style={styles.container} forceInset={{ top: 'always', horizontal: 'never' }}>
      <DrawerItems {...props} />
    </SafeAreaView>
  </ScrollView>
);

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
});

export default CustomDrawerContentComponent;
```

**Comment by brentvatne** [comment]
hi @javahemans - you can re-create this issue with an example that we can run on github or https://snack.expo.io as per the template and I will investigate. please leave out any superfluous code
