### ISSUE TITLE
Set `initialRouteName`  of Root Stack Navigator without creating a  root component / screen / splash

### ISSUE THREAD

**Issue by yashojha19** [react-navigation/react-navigation#3518]
Ok. So I was using a splash screen and renderd an image  till now to apply the logic of where to navigate next. But, I have found that you can actually show an image or drawable while android application starts (when cold start happens). So, I can replace that loading white screen to my desired splash image. So I want to remove splash screen now. It has a 2 sec timer which I don't like. I use AsyncStorage to check if user is logged in. Any help or suggestions is appreciated.

**Comment by brentvatne** [comment]
moved to https://github.com/react-navigation/rfcs/issues/23
