### ISSUE TITLE
https://reactnavigation.org footer links left column broken

### ISSUE THREAD

**Issue by morriswinkler** [react-navigation/react-navigation#3519]
This is related to the https://reactnavigation.org site [ thanks for that nice page, good docs, keep it going ]

There are a handful of links in the left column, something like:

```
https://reactnavigation.org/docs/en/api-reference.html
```

which resolves into an 404

```
https://reactnavigation.org/docs/api-reference.html
```
works, so either remove the 'en/' or add that section.

👍

**Comment by matthamil** [comment]
Hi @morriswinkler ! Thanks for the issue. Can you move this ticket to the website's repo at https://github.com/react-navigation/react-navigation.github.io/issues? Thanks!
