### ISSUE TITLE
Top tabbar is stuck when we set header: null in navigationOptions

### ISSUE THREAD

**Issue by harikrishnanp** [react-navigation/react-navigation#3520]
**My Code**
______________

```
export default class MyComponent extends Component {

 static navigationOptions = {
    title: '',
    header: null,
};
render() {
const MyTabNavigator = TabNavigator({
      Tab1: { screen: Screen1  },
      Tab2:{ screen: Screen2  },
    }, {
        tabBarPosition: 'top',
        animationEnabled: true,
        tabBarComponent: TabBarTop,
        swipeEnabled: false,
        tabBarOptions: {
          activeTintColor: '#1772cd',
          inactiveTintColor: '#595959',
          showIcon: false,
          showLabel: true,
          pressColor: 'transparent',
          labelStyle: myStyle.labelStyle,
          style: myStyle.tabBar,
          tabStyle: myStyle.underline,
          indicatorStyle: myStyle.tabBarIndicator
        },
      }
    );
    return (
      <MyTabNavigator />
    );
};
}
```
### Current Behavior

The tab bar is rendering. But it is stuck. Touch not working. Also the view inside the tabbar is not rendering.

### Expected Behavior

The tab bar should respond to touch. It should render the view correctly. 

### How to reproduce

Please run the given code.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.3
| react-native     | 0.52.0
| node             | 9.3.0
| npm or yarn      | 1.3.2

**Comment by brentvatne** [comment]
please follow the issue template and provide an example project that reproduces this
