### ISSUE TITLE
React Native TextInput inside TabNavigator cannot show "paste" options on long press

### ISSUE THREAD

**Issue by hallz11** [react-navigation/react-navigation#3521]
Hi all,

I have a problem with text input inside tabnavigator.
I cannot do the "long press" on the textinput for any options, cut, copy, paste, etc..
Anyone can help?

Thank you very much!

**Comment by satya164** [comment]
This is a bug with React Native and scrollview/viewpager. Please open an issue in the React native repo.

**Comment by moddi3** [comment]
I have the same issue. Text selection works with stackNavigator, but not with tabs.

**Comment by brentvatne** [comment]
> This is a bug with React Native and scrollview/viewpager. Please open an issue in the React native repo.
