### ISSUE TITLE
Navigation listeners firing multiple times per event

### ISSUE THREAD

**Issue by victorbadila** [react-navigation/react-navigation#3523]
### Current Behaviour

I have a tab navigator and inside one of the tabs I declare some listeners:
```
  static navigationOptions = ({ navigation }) => {
    navigation.addListener('didFocus', () => {
      console.log('tab did focus);
    });
  };
```
Whenever I focus on that tab the function triggers multiple times and I get 'tab did focus' logged 6, 10, etc. times in a row. This happens for all of the mentioned listeners: didFocus, willFocus, didBlur, willBlur.

### Expected Behaviour

I would expect the function to only trigger once per event.
In the expo I have a tab navigator with 2 tabs and I'm using alerts to notify when the tab1 "will focus" or "did focus". I seem to not get any alert when the component "did focus", yet I get "will focus" 2 times for each tab visit.

https://snack.expo.io/SyzWOkfDf

### How to reproduce

I guess reproducing the bug would mean creating a tab navigator with some child components and switching between them.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.3
| react-native     | 0.47.1
| node             | 8.9.1
| npm or yarn      | 5.6.0

**Comment by satya164** [comment]
Hey there, please provide a repro on https://snack.expo.io as per the issue template.

**Comment by wachunei** [comment]
My guess is that function is called multiple times, the listener should be added on the component you are rendering and not inside that static method.

**Comment by victorbadila** [comment]
@satya164 I updated my example with an expo

@wachunei yes, the function si called multiple times, that's for sure. how would you add the listener in the component and not in the static method? You mean something like taking the `navigation` from the `props` in `componentDidMount` or something similar?

**Comment by wachunei** [comment]
Yes
```jsx
class YourComponent extends Component {
  componentDidMount() {
    this.subs = [
      this.props.navigation.addListener('willFocus', () => console.log('will focus')),
      this.props.navigation.addListener('willBlur', () => console.log('will blur')),
      this.props.navigation.addListener('didFocus', () => console.log('did focus')),
      this.props.navigation.addListener('didBlur', () => console.log('did blur')),
    ];
  }

  componentWillUnmount() {
    this.subs.forEach((sub) => {
      sub.remove();
    });
  }

  render() {
    return ( /* your render */ );
  }
}
```

**Comment by brentvatne** [comment]
the example you linked to doesn't run.

as @wachunei it should not be added in the static method, that can be called any arbitrary number of times and has no way for you to handle cleanup

**Comment by victorbadila** [comment]
yes, well Expo is not the most stable app out there, turns out it didn't save my changes at all. I have updated the link to the expo snack just to have it there. @wachunei I will try your example, hopefully it works.

**Comment by victorbadila** [comment]
yeah, works perfectly now, thanks.

**Comment by brentvatne** [comment]
> yes, well Expo is not the most stable app out there, turns out it didn't save my changes at all. I have updated the link to the expo snack just to have it there. @wachunei I will try your example, hopefully it works.

you need to hit save for it to save your changes, nothing to do with expo, it's how most stuff works :P
