### ISSUE TITLE
Header buttons in root navigation stack don't receive navigation context

### ISSUE THREAD

**Issue by petrogad** [react-navigation/react-navigation#3524]
### Current Behavior
Currently if you are building a custom element to control navigation from a header button, IF you attempt to use the withNavigation HOC on that custom element, the navigation property is undefined.

Here is a brief example :

```
// navigation.js
StackNavigator({
	'Profile': {
		key: 'profile',
		navigationOptions: {
			headerRight: ( <CustomElement /> )
		}
});

// CustomElement.js
....
export default withNavigation(CustomElement);
```

### Expected Behavior

- Would expect the context in the withNavigation HOC pass in the navigator prop to my custom element.  

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.3
| react-native     | 0.53
| node             | 8.6.0
| npm or yarn      | 1.3.2

**Comment by petrogad** [comment]
An alternative solution is passing the navigator into navigateOptions via:

```
StackNavigator({
	'Profile': {
		key: 'profile',
		navigationOptions: ({navigation}) => ({
			headerRight: ( <CustomElement /> )
		})
});

```
then remove the withNavigation HOC from `CustomElement`.

This issue can likely be closed, however leaving it up to the maintainer to comment on wether or not the original question is a valid use case.

**Comment by brentvatne** [comment]
Thanks for reporting. In the future it's best if you provide a runnable example :) I went ahead and made one here: https://snack.expo.io/SkambWfvz

You'll notice that `withNavigation` appears to not work in the header component when the navigator is the root navigator. Otherwise, it will work. Still a bug but generally this won't impact most apps, and if it does then you can work around it for now by adding another stack at the root.

**Comment by petrogad** [comment]
Good to know, and thanks; going forward will make sure to create a runnable example; apologies!

Thanks for the quick feedback!

**Comment by gitwik** [comment]
any idea when this bug will be fixed ??

**Comment by bramski** [comment]
This needs to be documented in the docs for 1.0 please.

**Comment by brentvatne** [comment]
@bramski - you can open a PR here: https://github.com/react-navigation-v1/react-navigation-v1.github.io

I don't have time to maintain old docs
