### ISSUE TITLE
on Android my back button title is missing

### ISSUE THREAD

**Issue by golestanirad** [react-navigation/react-navigation#3525]
I am using _React Navigation_, but noticed that on Android my back button title is missing! it works fine on iOS.

```
const RootNavigator = StackNavigator(
    {
        Options: {
            screen: Options,
            navigationOptions: {
                headerTitle: 'Options',              
            },
        },
        Themes: {
            screen: Themes,
            navigationOptions:{
                headerTitle: 'Themes',
            },
        }
   }
);
```

https://stackoverflow.com/questions/48775960/on-android-my-back-button-title-is-missing

**Comment by matthamil** [comment]
This is a feature supported only on iOS: https://reactnavigation.org/docs/header-buttons.html#customizing-the-back-button. You can override the back button with your own component to achieve this affect.

**Comment by vonovak** [comment]
I believe the question was answered.

**Comment by hegelstad** [comment]
Vote for this feature:

https://react-navigation.canny.io/feature-requests/p/give-android-header-back-button-title-by-default

**Comment by JimVercoelen** [comment]
You can also use HeaderBackButton directly from react-navigation
