### ISSUE TITLE
Redux nested getActionForPathAndParams returns null

### ISSUE THREAD

**Issue by tomcrusader** [react-navigation/react-navigation#3527]
So I've looked at all documentation and examples I could find. Thought I had this pieced together, but still doesn't work.

### Current Behavior

- Nested Redux navigation returns null in `getActionForPathAndParams`

![react-navigation-nested-error](https://user-images.githubusercontent.com/396545/36256313-ad1484fc-1252-11e8-8050-cf0165c7878b.jpg)

### Expected Behavior

- Nested nav "LoggedInNavigator" loads as child of "LoginNavigator"
- LoginNavigator: StackNavigator
  - LoginScreen
  - MainScreen: LoggedinNavigator (nested)
- LoggedinNavigator: TabNavigator
  - Map
  - Profile

### How to reproduce

- Create an app with Redux and react-navigation
- Add a nested TabNavigator as a screen according to below
- Run the app

### Your Environment
OSX, VS Code

- react: 16.0.2
- react-navigation: ^1.0.3
- react-native: ^0.52.0
- expo: ^25.0.0
- react-navigation-redux-helpers: ^1.0.1
- node:8.9.4
- npm: 5.6.0

#### AppNavigator.js

```javascript
import React from 'react';
import PropTypes from 'prop-types';
import { View } from 'react-native';
import { StackNavigator, TabNavigator, addNavigationHelpers } from 'react-navigation';
import { FontAwesome } from '@expo/vector-icons';
import _ from 'lodash';
import { createReactNavigationReduxMiddleware, createReduxBoundAddListener } from 'react-navigation-redux-helpers';

import Styles, { Colors, TabIconSize } from '../styles';

// Component views used in navigation
import LoginContainer from '../containers/LoginContainer';
import MapContainer from '../containers/MapContainer';
import ProfileContainer from '../containers/ProfileContainer';

/**
 * Redux middleware for the navigator
 */
export const middleware = createReactNavigationReduxMiddleware(
  'root',
  state => state.nav,
);
export const addListener = createReduxBoundAddListener('root');

export const LoggedinNavigator = TabNavigator({
  MapScreen: {
    screen: MapContainer,
    navigationOptions: {
      tabBarLabel: 'Boka',
      title: 'Boka',
      tabBarIcon: (<FontAwesome name="map-o" size={TabIconSize} style={Styles.tabBarIcon} />),
    },
  },
  ProfileScreen: {
    screen: ProfileContainer,
    navigationOptions: {
      tabBarLabel: 'Jag',
      title: 'Jag',
      tabBarIcon: (<FontAwesome name="user-circle-o" size={TabIconSize} style={Styles.tabBarIcon} />),
    },
  },
}, {
  initialRouteName: 'MapScreen',
  tabBarPosition: 'bottom',
  animationEnabled: true,
  tabBarOptions: {
    allowFontScaling: true,
    activeTintColor: Colors.CrossLightBlue,
    labelStyle: {
      fontSize: 9,
    },
    showIcon: true,
  },
});

/**
 * Main navigation for the app (react-navigation)
 */
export const LoginNavigator = StackNavigator(
  {
    LoginScreen: {
      screen: LoginContainer,
      navigationOptions: { title: 'Logga in' },
    },
    MainScreen: {
      screen: LoggedinNavigator,
      navigationOptions: {
        gesturesEnabled: false,
        headerLeft: null,
      },
    },
  },
  {
    mode: 'modal',
    headerMode: 'none',
  },
);

/**
 * Navigation component with styles
 *
 * Remarks: this component also has named exports "LoginNavigator", "middleware" and "addListener"
 * @param {*} props - props containing dispatch and nav
 */
const AppNavigator = props =>
  (
    <View style={Styles.container}>
      {
        !_.isNil(props.nav) ?
          (
            <View style={Styles.container}>
              <LoginNavigator
                navigation={
                  addNavigationHelpers({
                    dispatch: props.dispatch,
                    state: props.nav,
                    addListener,
                  })}
              />
            </View>
          ) : null
      }
    </View>);

AppNavigator.propTypes = {
  dispatch: PropTypes.func.isRequired,
  nav: PropTypes.shape({
    index: PropTypes.number.isRequired,
    routes: PropTypes.array.isRequired,
  }).isRequired,
};

export default AppNavigator;
```

#### NavigationReducer.js
```javascript

import { NavigationActions } from 'react-navigation';
import _ from 'lodash';

import { NavigationConstants } from '../Constants';
import { LoginNavigator } from '../components/AppNavigator';

// Start with two routes: The main screen, with the login screen on top.
const actionForLoggedOut = LoginNavigator
  .router
  .getActionForPathAndParams(NavigationConstants.LOGIN);

const actionForLoggedIn = LoginNavigator
  .router
  .getActionForPathAndParams(NavigationConstants.MAIN);

const stateForLoggedOut = LoginNavigator.router.getStateForAction(actionForLoggedOut);

const stateForLoggedIn = LoginNavigator.router.getStateForAction(
  actionForLoggedIn,
  stateForLoggedOut,
);

const initialNavState = { stateForLoggedOut, stateForLoggedIn };

/**
 * Handles application navigation actions
 * @param {Object} state
 * @param {Object} action
 */
const NavReducer = (state = initialNavState, action) => {
  let nextState;
  if (!_.isNil(action)) {
    switch (action.type) {
      case NavigationConstants.LOGIN:
        nextState = LoginNavigator.router.getStateForAction(
          NavigationActions.back(),
          state,
        );
        break;
      case NavigationConstants.LOGOUT:
        nextState = LoginNavigator.router.getStateForAction(
          NavigationActions.navigate({ routeName: NavigationConstants.LOGIN }),
          state,
        );
        break;
      default:
        nextState = LoginNavigator.router.getStateForAction(action, state) || state;
    }
  }
  return nextState || state;
};

export default NavReducer;
```

#### Constants.js
```javascript
...
export const NavigationConstants = {
  LOGIN: 'LoginScreen',
  MAIN: 'MainScreen',
  LOGOUT: 'LogoutScreen',
  MAP: 'MapScreen',
  PROFILE: 'ProfileScreen',
};
```

**Comment by MariusMeiners** [comment]
Haha so i actually had this exact problem like 2 days ago...
If you try to pull the `getActionForPathAndParams` from a nested Navigator it will always return `null`.
I've worked around it for providing the start screen within that nested navigator...
Honestly we've ran into even more problem when we tried to integrate react-navigation into redux.
The performance is absolutely terrible as described in many issues... 
I'd really suggest if you dont absolutely need to go through redux, then dont.

**Comment by TomFanella4** [comment]
I also ran into this issue recently. I managed to find a workaround in #1357 by creating the action directly. Unfortunately it does seem like there is a bug in `getActionForPathAndParams`.

``` javascript
const actionForLoggedIn = NavigationActions.reset({
  index: 0,
  actions: [
    NavigationActions.navigate({
      routeName: 'Main',
    }),
  ],
});
```

**Comment by TomFanella4** [comment]
After running the code through the debugger I found that if you replace
```javascript
const actionForLoggedIn = LoginNavigator.router.getActionForPathAndParams('Main');
```
with
```javascript
const actionForLoggedIn = LoginNavigator.router.getActionForPathAndParams('Main/{DEFAULT_SCREEN}');
```
it will return the correct action. Hope this helps!

**Comment by MariusMeiners** [comment]
That is great to know. Honestly tho the performance if stacknavigator becomes so frustrating that I just don't feel like you could really use their redux implementation anyway...

**Comment by brentvatne** [comment]
@MariusMeiners - create an issue that reproduces this problem and I'd be happy to investigate

**Comment by brentvatne** [comment]
cc @ericvicenti -- was what @TomFanella4 suggested above intentional?

**Comment by superburrito** [comment]
Took some time to look into this, it seems like when we try to retrieve the nested action, we hit:
https://github.com/react-navigation/react-navigation/blob/276fb8f7b39214c3bd78bad485160f53810151a7/src/routers/StackRouter.js#L515-L517
because we're passing an empty `path` string to the nested TabRouter's `getActionForPathAndParams`. As expected, this empty`path` param fails all of the checks against `paths[tabId]` and so the final result defaults to null:
https://github.com/react-navigation/react-navigation/blob/276fb8f7b39214c3bd78bad485160f53810151a7/src/routers/TabRouter.js#L317-L318

Maybe it might be better if we switched this null fallback value for the TabRouter to something like
`NavigationActions.navigate({ routeName: initialRouteName })`? @brentvatne do you think that's a feasible change?

**Comment by superburrito** [comment]
Think this issue can be closed, I see that:

https://github.com/react-navigation/react-navigation/blob/d57d118fda8ad46942d964f45e9303580153a9ee/src/routers/SwitchRouter.js#L330-L336

has been added
