### ISSUE TITLE
Why go Back button don' work ?

### ISSUE THREAD

**Issue by Johnba1988** [react-navigation/react-navigation#3530]
My environnement : 
`Your Environment

 react-navigation :"^1.0.0-beta.26"
 react-native     :"0.52.0"
 node      :v8.4.0       
 npm   : 5.3.0  `

When I press back button on the header , the screen of the previous page is displayed but functions existed in the componentwillMount and compnentDidMount of the component of screen not executed .

For example I have an home screen (component Home) and details screen (component Details) , in the Home component I add `console.log('home)` in componentDidMount . Now when I navigate from home to details and I press back button , the home screen displayed but nothing logged .

**Comment by matthamil** [comment]
Can you provide a reproducible code sample as listed in the issue template?

**Comment by Johnba1988** [comment]
@matthamil I don't understand what my question expect .

**Comment by brentvatne** [comment]
please follow the issue template. these issues are for bugs and not questions. see https://reactnavigation.org/help for other resources
