### ISSUE TITLE
StackNavigator title does not update when changed via Mobx

### ISSUE THREAD

**Issue by YourGamesBeOver** [react-navigation/react-navigation#3531]
### Current Behavior

In my project, I have a simple StackNavigator with a list of data items pulled from an API, and a details view for each item.  I want the title of the details page to change when the data changes via Mobx.  
My code to do so is below: 

```javascript
@observer
export class SimpleDetailsPage extends React.Component<ISimpleDetailsPageProps, {}> {
    static navigationOptions = ({ navigation, screenProps }: {navigation: NavigationScreenProp<NavigationParams, {}>, screenProps: any}) => {
        var title = "Details";
        if(!navigation.state.params) {
            //nop
        } else if(navigation.state.params.title) {
            title = navigation.state.params.title
        } else if (navigation.state.params.titleProp) {
            let item = SimpleDetailsPage.getItem(screenProps, navigation.state);
            if(item) {
                title = unescapeString(String(item[navigation.state.params.titleProp]));
            }
        }
        console.log("setting title", title);
        return {title: title};
    };
    static getItem(screenProps: any, navState: any) {
        let store = screenProps.store[navState.params.store];
        return store.getItem(navState.params.item);
    }
...
```
The title will never change from "Details".  An example of the console output is below:
```
[exp] setting title Details
[exp] setting title Details
[exp] setting title Details
[exp] setting title Details
[exp] setting title Details
[exp] setting title Details
[exp] setting title Details
[exp] setting title Details
[exp] got data back from api
[exp] setting title 1437290
[exp] setting title 1437290
[exp] setting title 1437290
[exp] setting title 1437290
[exp] setting title 1437290
```
### Expected Behavior

When navigationOptions returns a different title than before, the title bar should update to display the new value.
This may be Android-specific.  I am unable to reproduce this on iOS, but that may be due to other factors (the console output never says 'setting title Details' in the first place)

### How to reproduce

Create a StackNavigator screen that updates its title via changes to a Mobx store

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.27
| react-native     | 0.25.0
| node             | 9.1.0
| yarn      | 1.3.2
|expo | 25.0.0
|mobx|3.5.1

**Comment by YourGamesBeOver** [comment]
I found a workaround.  instead of changing the title inside navigationOptions, I instead use mobx.autorun to call this.props.navigation.setParams to update the title later

**Comment by joshuapinter** [comment]
@YourGamesBeOver How did you get `navigation.setParams` to work with `mobx.autorun`? When I tried doing it I was stuck in what appeared to be an endless loop. 

I was setting up the store in `componentWillMount` and trying the following both `componentWillMount` and `constructor` with no success: 

```js
mobx.autorun( () => this.props.navigation.setParams( { title: store.title } ) )
```

**Comment by barrylachapelle** [comment]
SetParams always has a lag too. I would love to see how others are handling this.
