### ISSUE TITLE
Getting errors in bugs tracker in createNavigationContainer.js and CardStack.js

### ISSUE THREAD

**Issue by Elf2707** [react-navigation/react-navigation#3533]
Hello, thanks for your work.

Constantly (10 - 15 times per day) getting two strange error reports in bugs tracker. Seems to me it could be related with react-navigation, may be not. Strange thing is app doesn't crash at that moments, but errors do registered. May be you could give me a hint what can be the reason. Sorry can't add code. Here's stack traces:

First error:
node_modules/react-navigation/src/createNavigationContainer.js:7 t	
node_modules/react-navigation/src/createNavigationContainer.js:7 checkStatus	
node_modules/promise/setimmediate/core.js:39:17 tryCallOne	
node_modules/promise/setimmediate/core.js:125:22	
node_modules/react-native/Libraries/Core/Timers/JSTimers.js:296:6	
node_modules/react-native/Libraries/Core/Timers/JSTimers.js:149:24 _callTimer
 
Second error:
node_modules/react-navigation/src/views/CardStack/CardStack.js:261:57 t	
node_modules/react-navigation/src/views/CardStack/CardStack.js:273:10 checkStatus	
node_modules/promise/setimmediate/core.js:39:17 tryCallOne	
node_modules/promise/setimmediate/core.js:125:22	
node_modules/react-native/Libraries/Core/Timers/JSTimers.js:296:6	
node_modules/react-native/Libraries/Core/Timers/JSTimers.js:149:24 _callTimer	
node_modules/react-native/Libraries/Core/Timers/JSTimers.js:203:20 _callImmediatesPass
### Current Behavior
Errors registered in bugs tracker.

### Expected Behavior
Working without errors

### How to reproduce
-

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.2
| react-native     | 0.49.3
| node             | 6.9.2
| npm or yarn      | yarn

Thanks in advance.

**Comment by brentvatne** [comment]
`checkStatus` is not a function that exists in react-navigation. sorry the stack trace doesn't help much :( if you can provide an example project that reproduces this I'd be happy to investigate, please open a new issue if so.
