### ISSUE TITLE
TopTabBar with scrollEnabled causes indicator to render in wrong position on orientation

### ISSUE THREAD

**Issue by paulpopiel** [react-navigation/react-navigation#3534]
### Current Behavior

Issue occurs when using a `TabNavigator` with `TabBarTop` tab bar components, positioned at the top, and with `scrollEnabled` set to true.
Behaviour is that when the device is rotated (sometimes needs a few rotations/orientation changes) the indicator is drawn in the wrong position. 

See screenshots below (note the default yellow indicator not sitting directly under the tab):

<img width="1183" alt="screen shot 2018-02-16 at 11 25 25 am" src="https://user-images.githubusercontent.com/8855763/36292379-775b3f9e-130c-11e8-8774-e0e7c628fc46.png">

<img width="1150" alt="screen shot 2018-02-16 at 11 25 05 am" src="https://user-images.githubusercontent.com/8855763/36292378-77191c5e-130c-11e8-8d30-bdddf00e776c.png">

I managed to track down the release in which this started occurring. Basically it seems to have been introduced in v1.0.0-beta23 when react-native-tab-view was upgraded from 0.70 to 0.74.

### Expected Behavior

Indicator should always render in the correct position under the the tab bar component.

### How to reproduce

Create a `TabNavigator` as below. Run the App and rotate the device between portrait and landscape until you see the indicator display in the wrong position.

```
const tabNavigator = TabNavigator(anyTabConfig, {
            animationEnabled: false,
            swipeEnabled: true,
            tabBarComponent: TabBarTop,
            tabBarPosition: 'top',
            tabBarOptions: {
                scrollEnabled: true,
            },
        })
```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.3 
| react-native     | 0.53.0

**Comment by brentvatne** [comment]
this belongs in https://github.com/react-navigation/react-navigation-tabs now
