### ISSUE TITLE
GoBack from TabNavigator to stackNavigator

### ISSUE THREAD

**Issue by borjaruiz** [react-navigation/react-navigation#3535]
StackNavigatorMain
  - LoginScreen
  - TabNavigator
    - StackNavigator1
    - StackNavigator2
    - StackNavigator3
  - OtherScreen

When I move from Login to TabNavigator I do this way:
this.props.navigation.navigate('Tabs') (This shows TabNavigator and StackNavigator1)

Then, I have a button in StackNavigator1 to goBack to Login, but it's not working:
this.props.navigation.dispatch(NavigationActions.back('LoginScreen'))

I also tried different ways with no success.
(IE: this.props.navigation.dispatch(NavigationActions.back()))

Thanks in advance

**Comment by MariusMeiners** [comment]
I think NavigationActions.back() takes an object as an argument which has the Name of the key you want to go back to, not just a simple string... 
so you would have to rewrite it to: 
```
const backAction = NavigationActions.back({key: "LoginScreen"})
this.props.navigation.dispatch(backAction);
```
what confuses me is why .back() doesnt work... I think you'd have to share more of your code in order for me to help you.

**Comment by ericvicenti** [comment]
I agree with @MariusMeiners here. The back action with a key should work for this use case. 

There isn’t really a clear issue here so I’m gonna close it out. 

When you find some unexpected behavior like this, please post some code so that we can see the bug and fix it!

**Comment by borjaruiz** [comment]
Hi @MariusMeiners ,
Thanks for your help, your code doesn't work for me.

When I click the hardware button, it goes back properly.

`goLoginScreen(){`
   ` console.log("goback")`
  `  const backAction = NavigationActions.back({key: "LoginScreen"})`
  `  this.props.navigation.dispatch(backAction);`
`  }`
`render() {`
`...`
    `<Button `
              `  style={blueButton} `
          `      textStyle={blueButtonTextStyle}`
              `  onPress={() => this.goLoginScreen()}>`
                `Go login              </Button>`

The "goback" is being displayed in console, but no navigation is done

**Comment by MariusMeiners** [comment]
@borjaruiz i can't see any mistakes in the code you provided... you'd have to post your navigator src code + the src code of that component your try to navigate from and file structure and then maybe i can help you from there...
btw supplying a function that just calls your action handler is not necessary 
`onPress={() => this.goLoginScreen()}>`
can just be 
`onPress={this.goLoginScreen}>`

**Comment by borjaruiz** [comment]
@MariusMeiners I finally used .reset and it works. Thanks for your help
