### ISSUE TITLE
Lazy parameter is missing

### ISSUE THREAD

**Issue by sm2017** [react-navigation/react-navigation#3539]
### Current Behavior
I upgrade from 1.0.0-beta15 to 1.0.0 , and it seems in the newer version TabNavigator has not `lazy` prop , but in the https://reactnavigation.org/docs/tab-navigator.html it has

I search in source code and it seems you missing `lazy` props in newer version

### Expected Behavior
Lazy tab loading must works as in older version

### How to reproduce

```js
const TabNavigation= TabNavigator(
  {
    One: {
      screen: createTabScreen('One', 'numeric-1-box-outline', 'numeric-1-box'),
    },
    Two: {
      screen: createTabScreen('Two', 'numeric-2-box-outline', 'numeric-2-box'),
    },
    Three: {
      screen: createTabScreen(
        'Three',
        'numeric-3-box-outline',
        'numeric-3-box'
      ),
    },
  },
  {
    tabBarPosition: 'bottom',
    swipeEnabled: false,
    lazy: true,
  }
);
```
### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0
| react-native     | 0.53.0
| node             | v8.1.3
| npm or yarn      | v1.3.2

**Comment by nico1510** [comment]
It is coming back https://github.com/react-navigation/react-navigation/pull/3538. Please don't forget to close this issue if this answer solves your problem.

**Comment by brentvatne** [comment]
indeed, you can install 1.1.0-rc.2 to try it

**Comment by pilot4u** [comment]
@brentvatne thank you very much for this update.
but we are getting following error:
TypeError: addListener is not a function
ExceptionsManager.js:65
This error is located at:
    in withCachedChildNavigation(TabView) (at TabNavigator.js:34)
    in Unknown (at createNavigator.js:13)
    in Navigator (at createNavigationContainer.js:227)
    in NavigationContainer (at TabBarNavigation.js:66)
    in TabBarNavigation (created by Connect(TabBarNavigation))
    in Connect(TabBarNavigation) (at SceneView.js:17)
    in SceneView (at DrawerScreen.js:21)
    in DrawerScreen (at withCachedChildNavigation.js:44)
    in withCachedChildNavigation(DrawerScreen) (at DrawerNavigator.js:71)
    in Unknown (at createNavigator.js:13)
    in Navigator (at DrawerView.js:154)
    in RCTView (at View.js:112)
    in View (at DrawerLayoutAndroid.android.js:186)
    in AndroidDrawerLayout (at DrawerLayoutAndroid.android.js:200)
    in DrawerLayoutAndroid (at DrawerView.js:134)
    in DrawerView (at DrawerNavigator.js:88)
    in Unknown (at createNavigator.js:13)
    in Navigator (at createNavigationContainer.js:227)
    in NavigationContainer (at SceneView.js:17)
    in SceneView (at CardStack.js:401)
    in RCTView (at View.js:112)
    in View (at createAnimatedComponent.js:134)
    in AnimatedComponent (at Card.js:12)
    in Card (at PointerEventsContainer.js:39)
    in Container (at CardStack.js:430)
    in RCTView (at View.js:112)
    in View (at CardStack.js:349)
    in RCTView (at View.js:112)
    in View (at CardStack.js:348)
    in CardStack (at CardStackTransitioner.js:67)
    in RCTView (at View.js:112)
    in View (at Transitioner.js:142)
    in Transitioner (at CardStackTransitioner.js:19)
    in CardStackTransitioner (at StackNavigator.js:39)
    in Unknown (at createNavigator.js:13)
    in Navigator (at createNavigationContainer.js:227)
    in NavigationContainer (at Router.js:329)
    in ExitOnDoubleBack (at Router.js:324)
    in Router (created by Apollo(Router))
    in Apollo(Router) (created by Connect(Apollo(Router)))
    in Connect(Apollo(Router)) (created by Apollo(Connect(Apollo(Router))))
    in Apollo(Connect(Apollo(Router))) (created by Connect(Apollo(Connect(Apollo(Router)))))
    in Connect(Apollo(Connect(Apollo(Router)))) (created by Apollo(Connect(Apollo(Connect(Apollo(Router))))))
    in Apollo(Connect(Apollo(Connect(Apollo(Router))))) (created by Connect(Apollo(Connect(Apollo(Connect(Apollo(Router)))))))
    in Connect(Apollo(Connect(Apollo(Connect(Apollo(Router)))))) (at index.js:67)
    in QueryRecyclerProvider (created by ApolloProvider)
    in ApolloProvider (at index.js:66)
    in Provider (at index.js:65)
    in App (at renderApplication.js:35)
    in RCTView (at View.js:112)
    in View (at AppContainer.js:102)
    in RCTView (at View.js:112)
    in View (at AppContainer.js:122)
    in AppContainer (at renderApplication.js:34)
TypeError: addListener is not a function

We have navigators hierarchic as follows:
StackNavigator:
	Drawer:
		TabNavigator:
		  TabA:
			 StackNavigator
		  TabB:
			 StackNavigator

could you please advise how should we implement your vital fix?

**Comment by pilot4u** [comment]
@brentvatne thank you very much for this update.
but we are getting following error:
TypeError: addListener is not a function
ExceptionsManager.js:65
This error is located at:
    in withCachedChildNavigation(TabView) (at TabNavigator.js:34)
    in Unknown (at createNavigator.js:13)
    in Navigator (at createNavigationContainer.js:227)
    in NavigationContainer (at TabBarNavigation.js:66)
    in TabBarNavigation (created by Connect(TabBarNavigation))
    in Connect(TabBarNavigation) (at SceneView.js:17)
    in SceneView (at DrawerScreen.js:21)
    in DrawerScreen (at withCachedChildNavigation.js:44)
    in withCachedChildNavigation(DrawerScreen) (at DrawerNavigator.js:71)
    in Unknown (at createNavigator.js:13)
    in Navigator (at DrawerView.js:154)
    in RCTView (at View.js:112)
    in View (at DrawerLayoutAndroid.android.js:186)
    in AndroidDrawerLayout (at DrawerLayoutAndroid.android.js:200)
    in DrawerLayoutAndroid (at DrawerView.js:134)
    in DrawerView (at DrawerNavigator.js:88)
    in Unknown (at createNavigator.js:13)
    in Navigator (at createNavigationContainer.js:227)
    in NavigationContainer (at SceneView.js:17)
    in SceneView (at CardStack.js:401)
    in RCTView (at View.js:112)
    in View (at createAnimatedComponent.js:134)
    in AnimatedComponent (at Card.js:12)
    in Card (at PointerEventsContainer.js:39)
    in Container (at CardStack.js:430)
    in RCTView (at View.js:112)
    in View (at CardStack.js:349)
    in RCTView (at View.js:112)
    in View (at CardStack.js:348)
    in CardStack (at CardStackTransitioner.js:67)
    in RCTView (at View.js:112)
    in View (at Transitioner.js:142)
    in Transitioner (at CardStackTransitioner.js:19)
    in CardStackTransitioner (at StackNavigator.js:39)
    in Unknown (at createNavigator.js:13)
    in Navigator (at createNavigationContainer.js:227)
    in NavigationContainer (at Router.js:329)
    in ExitOnDoubleBack (at Router.js:324)
    in Router (created by Apollo(Router))
    in Apollo(Router) (created by Connect(Apollo(Router)))
    in Connect(Apollo(Router)) (created by Apollo(Connect(Apollo(Router))))
    in Apollo(Connect(Apollo(Router))) (created by Connect(Apollo(Connect(Apollo(Router)))))
    in Connect(Apollo(Connect(Apollo(Router)))) (created by Apollo(Connect(Apollo(Connect(Apollo(Router))))))
    in Apollo(Connect(Apollo(Connect(Apollo(Router))))) (created by Connect(Apollo(Connect(Apollo(Connect(Apollo(Router)))))))
    in Connect(Apollo(Connect(Apollo(Connect(Apollo(Router)))))) (at index.js:67)
    in QueryRecyclerProvider (created by ApolloProvider)
    in ApolloProvider (at index.js:66)
    in Provider (at index.js:65)
    in App (at renderApplication.js:35)
    in RCTView (at View.js:112)
    in View (at AppContainer.js:102)
    in RCTView (at View.js:112)
    in View (at AppContainer.js:122)
    in AppContainer (at renderApplication.js:34)
TypeError: addListener is not a function

We have navigators hierarchic as follows:
StackNavigator:
	Drawer:
		TabNavigator:
		  TabA:
			 StackNavigator
		  TabB:
			 StackNavigator

could you please advise how should we implement your vital fix?
