### ISSUE TITLE
Redesign Playground app

### ISSUE THREAD

**Issue by satya164** [react-navigation/react-navigation#3543]

**Comment by ericvicenti** [comment]
What are you looking for in a new design? Maybe we could take an iterative approach and start adding more realistic mini-apps/examples?

**Comment by satya164** [comment]
@ericvicenti I'm not exactly sure yet, I talked to @brentvatne on slack and he suggested it. I was thinking to take some ideas from the ex-navigation example.

**Comment by ericvicenti** [comment]
Ah it’s just a @brentvatne placeholder issue! 😆 

There is definitely room for improvement on the playground!

**Comment by brentvatne** [comment]
in particular we desperately need to improve it for android. I think it looks fine on ios (although certainly not anything fancy), but it's truly awful on android thanks to the built-in `Button` component being so offensive

**Comment by gazedash** [comment]
For me it was frustrating to see that default behavior of StackNavigator is to open a new screen on each click, or same button (it seems like it can be fixed using 'keys')
