### ISSUE TITLE
Double navigation is happening even on master branch

### ISSUE THREAD

**Issue by rogerkerse** [react-navigation/react-navigation#3544]
This issue got closed https://github.com/react-navigation/react-navigation/issues/271 but actually the issue is not fixed. I just tested it out in master branch and if pressing button fast, double navigation happens.

**Comment by brentvatne** [comment]
you did not follow the issue template or apparently read the last comment on that thread, which links to https://github.com/react-navigation/rfcs/issues/16 and explains how you can avoid this behavior right now and is a place for us to discuss how we can handle it automatically for users. that's a better place to comment if you have something constructive to share!
