### ISSUE TITLE
Change the drawerLabel attribute dynamically

### ISSUE THREAD

**Issue by Gshock1** [react-navigation/react-navigation#3545]
Hi there,
I'm using DrawerNavigator as my main Sidebar component, and I would like to change the look of the Sidebar Screen upon changes in the AsyncStorage.

Is there any way to do that?
I was searching all over the internet and couldn't find a fine solution.

Thanks.

**Comment by ericvicenti** [comment]
If you customize the drawer contentComponent, you can write a custom component for your sidebar that uses AsyncStorage and anything else RN supports
