### ISSUE TITLE
Cant access to screenProps on cardStyle property

### ISSUE THREAD

**Issue by vitorcamachoo** [react-navigation/react-navigation#3548]
### Current Behavior
At the moment cardStyle cannot be styled through screenProps

### Expected Behavior
The property cardStyle could receive a function the way that navigationOptions receive, to allow access screenProps in order to style cardStyle based on passing props.

```js
const navigatorConfig = {
  initialRouteName: 'UserSelection',
  mode: 'card',
  navigationOptions: props => ({
    headerStyle: {
      backgroundColor: props.screenProps.theme.color(),
    },
  }),
  cardStyle: props => ({
    backgroundColor: props.screenProps.theme.color(),
  }),
}
```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0
| react-native     | 0.53.0
| node             | 8.6.0
| npm or yarn      | 1.3.2

**Comment by brentvatne** [comment]
you should use context or something like redux instead. we plan to deprecate screenProps so I would avoid depending on it

**Comment by vitorcamachoo** [comment]
How can I access context inside `cardStyle`, or on `navigationOptions` property for example  when using `navigationOptions` as static ?

**Comment by brentvatne** [comment]
cc @satya164

**Comment by satya164** [comment]
@brentvatne yeah, I was also talking about it earlier. The way to solve it is to move the options to inside `render`.

**Comment by maxammann** [comment]
@satya164 can you maybe elaborate what you mean by moving it into the render? Is there a special prop which allows you to change the navigationOptions?

**Comment by maxammann** [comment]
I ended up using: 
```
    cardStyle: {
      backgroundColor: 'transparent'
    }
```

**Comment by sourabhv** [comment]
@satya164 Can you explain how to do this? I am trying to change `cardStyle` based on the theme user chooses.

**Comment by trickeyd** [comment]
I am facing the exact same problem. I really like @vitorcamachoo 's idea of using a function.

Did you manage to solve this in the end?

**Comment by vikrantnegi** [comment]
@satya164 How can move the Visual options inside render since `createSwitchNavigator` accepts object unlike navigationOptions which can be a function.
