### ISSUE TITLE
React-Navigation Reset while Passing Props to Children

### ISSUE THREAD

**Issue by wvicioso** [react-navigation/react-navigation#3550]
I'm using `React-Navigation` with `React-Native`. I get different results for identical code executed at different points of the stack. My Router uses a mix of `Stack Navigators` and `Tab Navigators.` Here's the structure:

- **StackNav:**
   - Login<br>
   
   - Register<br>
   
   - Home<br>
     - **TabsNav:**
         - Tab One
         - Tab Two

**Login** is the first screen the user sees. From here, They can log in and go to **Home => Tab One** OR they can **Register**. From **Register** They can then go to **Home => Tab One**

On both the **Login** and **Register** screens, I make an API call before navigating to **Home => Tab One**

When I navigate I want to reset the Stack and also pass the same `props` to **Tab One** and **Tab Two**

Here is my navigation code in **Login**:

        const actions = [
          NavigationActions.reset({
            index: 0,
            actions: [
              NavigationActions.navigate({
                routeName: "Home"
              })
            ]
          }),
          NavigationActions.setParams({
            key: 'Tab Two',
            params: {data: responseJson.data}
          }),
          NavigationActions.navigate({
            routeName: 'Tab One',
            params: {data: responseJson.data}
          })
        ];
        actions.forEach(this.props.navigation.dispatch);

In **Tab One**, the params don't get passed to `this.props.navigation.state`. After hunting a bit, I discovered that I can access the params by going to `this.props.navigation.dispatch.arguments`

In **Tab Two**, the params get passed to `this.props.navigation.state`

Here is my navigation code for **Register** (*it's identical to Login*):

        const actions = [
          NavigationActions.reset({
            index: 0,
            actions: [
              NavigationActions.navigate({
                routeName: "Home"
              })
            ]
          }),
          NavigationActions.setParams({
            key: 'Tab Two',
            params: {data: responseJson.data}
          }),
          NavigationActions.navigate({
            routeName: 'Tab One',
            params: {data: responseJson.data}
          })
        ];
        actions.forEach(this.props.navigation.dispatch);

Now, in **Tab One**, the params can be found in `this.props.navigation.state`. In **Tab Two** the params do not get passed at all. They do not appear neither in `this.props.navigation.state`(I only get the `routeName` and `key`) or `this.props.navigation.dispatch.arguments` (this appears as null)

I want to be able to access my data/props from this.props.navigation.state. My code is the the same in both places yet my results differ. Not sure what is going on. Am I missing something or is this a bug?

PS: I need to reset the stack. Everything works normally if I just navigate in a normal way.

**Comment by noxee** [comment]
Is there a reason that the `NavigationActions.setParams` and second `NavigationActions.navigate` actions aren't defined in the `actions` of `NavigationActions.reset`? 

You may be hitting a race condition where `NavigationActions.reset` is being executed after `NavigationActions.setParams` and `NavigationActions.navigate` and is wiping your state.

**Comment by wvicioso** [comment]
@noxee If I put the the `NavigationActions.setParams` and the second `NavigationActions.navigate` in the `NavigationActions.reset` actions I get an error saying the routes "Tab One" and "Tab Two" don't aren't defined.

**Comment by matthamil** [comment]
Can you create a reproducible example in a repo or with https://snack.expo.io/?

**Comment by noxee** [comment]
@wvicioso ah yeah sorry they're in different routers so the Root stack wouldn't know about the other two routes.

I've mocked up a snack similar to what you outlined and it appears to work correctly with version `1.1.1` so I'm not 100%  how you've got your code written so please correct me if I've missed something in the snack. You can see the snack here https://snack.expo.io/H1TFrQKwz.

I feel like there is a more idiomatic way of doing this so someone it would be good to hear from someone with experience with the library.

**Comment by wvicioso** [comment]
@noxee Thank you for your responses. Updating to `1.1.1` resolved all my issues.
