### ISSUE TITLE
TabBarTop doesn't respect background color properties

### ISSUE THREAD

**Issue by kylethebaker** [react-navigation/react-navigation#3551]
### Current Behavior

When using `tabComponent: TabBarTop` in a `TabNavigator`, the tabs do not respect the `inactiveBackgroundColor` or `activeBackgroundColor` properties and use a default.

#### With the following declaration:
```js
const screens = {
  S1: { screen: createDummyComponent('one'), path: 'one', },
  S2: { screen: createDummyComponent('two'), path: 'two', },
};

const tabProps = {
  tabBarPosition: 'top',
  tabBarComponent: TabBarTop,
  tabBarOptions: {
    activeBackgroundColor: '#ff0000',
  }
};

const Tabs = TabNavigator(screens, tabProps);
```

#### I get the following results:
![using-default-tab-colors](https://user-images.githubusercontent.com/4935420/36395740-a6465c0c-1588-11e8-87c8-477b2614a15d.png)

### Expected Behavior

I expect the active tab background color to be red, as is specified in the `tabBarOptions`.

### How to reproduce

You can reproduce this by creating a new `TabNavigator` using the example code I pasted above

### What I think is happening

Currently the default `TabBarComponent` that gets used is based on the Platform rather than the `tabBarPosition` property ([see here](https://github.com/react-navigation/react-navigation/blob/3600ecbd9bf62be4e1c0d4632bb0d8f5635c9454/src/navigators/TabNavigator.js#L51)). This means that if you specify `tabBarPosition: 'top'` on IOS and leave off the `tabBarComponent` you will end up with a `TabBarBottom` component that is positioned at the top. This will give you the proper styling as specified in the `activeBackgroundColor`, it's just weird that the component is named `TabBarBottom` when it's appearing at the top.

I think the underlying issue here is the `TabBarTop` component actually comes from an external module: `react-native-tab-view`. It looks the the `TabBar` that comes from this external module doesn't understand the `activeBackgroundColor` or `inactiveBackgroundColor` props and therefore always renders the TabBar using the default blue color.

So I think there is maybe two issues here:

Should `tabBarComponent` default to either `TabBarTop` and `TabBarBottom` based on `tabBarPosition` rather than the platform (in other words, ios still defaults to `{ tabBarPosition: 'bottom', tabBarComponent: TabBarBottom }` but if you specify `tabBarPosition: 'top'` as an option, it will also by default change use the component `tabBarComponent: TabBarTop` rather than keeping `TabBarBottom`)?

And how can we get the styling properties to be understood by this underlying `react-native-tab-view` component? It looks like some properties are being understood, like `activeTintColor`, but not the background colors.

### My workaround for now

To work around this issue I am just explicitly specifying `tabBarComponent: TabBarBottom` for my top positioned tabs, so that it uses the bottom tab bar but along the top. This will let me use the `activeBackgroundColor` and `inactiveBackgroundColor` props successfully.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.3
| react-native     | 0.53.2
| node             | 8.9.0
| npm or yarn      | 1.3.2

**Comment by kylethebaker** [comment]
There is a companion issue I have opened for React Native Router Flux that maybe provide additional context: https://github.com/aksonov/react-native-router-flux/issues/2888

**Comment by brentvatne** [comment]
@kylethebaker - can you post the example to https://snack.expo.io? it helps if it's easy to run, whereas I'd need to do some work to get what you shared above running before investigating

**Comment by kylethebaker** [comment]
@brentvatne Here is an expo link that demonstrates this: https://snack.expo.io/S1LK8rivG

I get the default background styling for the `TabBarTop` component (which is essentially an external dependency from `react-native-tab-view`) but the `activeTintColor` property sticks (my hunch is that this external dependency doesn't understand `activeBackgroundColor or inactiveBackgroundColor`.

If you un-comment the `tabBarComponent` property on line 25 and force the `TabNavigator` to the use `TabBarBottom` component for the top tabs then the styling will go through.

**Comment by Jakst** [comment]
Any updates on this issue? It really renders the component useless

**Comment by brentvatne** [comment]
example: https://snack.expo.io/BJ4oV_ZjG
see `style`, `indicatorStyle`, and `labelStyle` in docs: https://reactnavigation.org/docs/tab-navigator.html#tabbaroptions-for-tabbartop-default-tab-bar-on-android

apparently `activeTintColor` and `inactiveTintColor` only apply to the label here

**Comment by kylethebaker** [comment]
@Jakst Did you see my workaround above?

```js
import { TabBarBottom } from 'react-navigation';

const tabProps = {
  tabBarPosition: 'top',
  tabBarComponent: TabBarBottom,
  tabBarOptions: {
    activeBackgroundColor: '#ff0000',
  }

const Tabs = TabNavigator(screens, tabProps);
```

This is working fine for us on both platforms, thought there might be something specific from `TabBarTop` that you want.

**Comment by Jakst** [comment]
@kylethebaker Yes I saw it, but then I have to manually reimplement the whole behaviour and layout of TabBarTop.

@brentvatne You are correct. It seems when I last attempted this i used tabStyle instead of style, which led to differently colored tabs. A bit confusing with the different implementations for the top and bottom component. One could argue that the topbar should also support active/inactive backgroundcolor. But at least I found what I was looking for. Thanks!

**Comment by basiclaser** [comment]
I'm seeing this behaviour still now, is this a current issue for others?

**Comment by brentvatne** [comment]
@basiclaser - read the entire thread!
