### ISSUE TITLE
Android Header buttons show up as white boxes

### ISSUE THREAD

**Issue by DhruvTekchandani** [react-navigation/react-navigation#3552]
Hey guys!
So I was following the documentation and trying to create header buttons.
I noticed that the buttons would render perfectly on the iOS device but not on the android device.

I even ran the demo on the documetation site and the same problem occured there.

**This is the iOS Screen**
![screen shot 2018-02-20 at 10 24 05 am](https://user-images.githubusercontent.com/32982268/36401020-a7f61a6a-1628-11e8-9685-2239123b6557.png)

**This is the Android Screen**
![screen shot 2018-02-20 at 10 23 57 am](https://user-images.githubusercontent.com/32982268/36401029-b0675d6c-1628-11e8-834d-7108edcef4f1.png)

````
 static navigationOptions = {
        title: 'Log In',
        headerStyle:{
            backgroundColor:'#cb060d',
            paddingLeft:10
        },
        headerTintColor:'#fff',
        headerTitleStyle:{
            fontWeight:'bold',
            fontSize:20
        },
        headerRight:(
            <Button
                onPress={() => alert('This is a button!')}
                title="info"
                color="#fff"
            />),
        headerLeft: (
            <Button
                onPress={() => alert('This is a button!')}
                title="Maps"
                color="#fff"
            />
        ),

    };
````

Thank you in advance.

**Comment by brentvatne** [comment]
this is how the button component works in react-native, see: https://snack.expo.io/B15_QgYwG - if you set the color to `#fff` it changes the background color on android.

you can create your own button components or use this package: https://github.com/vonovak/react-navigation-header-buttons
