### ISSUE TITLE
Drawer item, style to item active

### ISSUE THREAD

**Issue by djuniorscjr** [react-navigation/react-navigation#3557]
With DrawerItem is possible, change style only of item active?

### Current Behavior
![current](https://user-images.githubusercontent.com/6300639/36424236-636a6a56-1621-11e8-98d5-385edde1287a.png)

### Expected Behavior
![expected](https://user-images.githubusercontent.com/6300639/36424219-594435fc-1621-11e8-8c02-a2b4fba088c4.png)

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^1.0.0-beta.27
| react-native     | 0.52.2

**Comment by brentvatne** [comment]
hi there! issues are only for bug reports. please ask questions on stackoverflow or discord. https://reactnavigation.org/help
