### ISSUE TITLE
Nested TabNavigators broken when child is on first tab of parent

### ISSUE THREAD

**Issue by nol13** [react-navigation/react-navigation#3561]
### Current Behavior

Update: snack example apparently showing separate issue, will try to update later

Running 1.1.1, same issue on beta-23
ios and android

The nested child TabNavigator goes to a blank white screen (iOS) when you try to switch and parent has lazy: true. 

If you switch tabs on the parent before switching on child it works, or if you add anther tab before the one with the child, or set intialRouteName to another route it works fine. Turning off swipe or animations didn't seem to help.

(also if you navigate from componentDidMount of a screen, componentDidMount will fire again when you later go back to that tab unless you give it ~100ms timeout the first time, which may be another issue)

### Expected Behavior

The nested child TabNavigator should be able to switch tabs immediately without issues.

### How to reproduce

[original snack redacted pending better example]

^snack shows the broken android behavior, but wasn't able to consistently reproduce the iOS behavior on there. works fine if you uncomment TabC.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation| 1.1.1 
| react-native |  0.51     |

**Comment by brentvatne** [comment]
cc @satya164

**Comment by nol13** [comment]
Lazy false on the parent seems to fix the issue in the 'real' app on iOS. On android though, at least in the snack example, setting lazy on the parent false breaks child nav even when it's not on the first tab. :/

**Comment by satya164** [comment]
Nesting sliding tabs is not supported as `ViewPagerAndroid` doesn't support it, also it's not possible to distinguish which tab you're trying to swipe when nesting. https://github.com/react-navigation/react-navigation/issues/662

Adding `swipeEnabled: false` and `animationEnabled: false` to any of the tab navigators fixes the issue for me.

**Comment by satya164** [comment]
Duplicate of #662

**Comment by nol13** [comment]
Hmm, I think I actually ran into a completely separate issue when trying to make the snack example, which is #662. In real app I get the white screen behavior on both iOS and android when the root doesn't have lazy set to false, irregardless of what swipeEnabled or animationEnabled are set to.

Will try to get a better example up later. The navigators in question are actually a few levels deep which may account for i\t.

**Comment by nol13** [comment]
Eh, I'll close until I can replicate I guess. Setting lazy: false seems to be working for now.
