### ISSUE TITLE
How to define StackNavigator when use custom tab?

### ISSUE THREAD

**Issue by Leadrive** [react-navigation/react-navigation#3564]
Hi, I use custom tab,  such as example.
https://github.com/react-navigation/react-navigation/blob/master/examples/NavigationPlayground/js/CustomTabs.js

My question is, how to define the StackNavigator screen?
I want to use as:
navigation.navigate('InfoScreen')

How to define the InfoScreen?
Thanks.

**Comment by brentvatne** [comment]
sorry this is only for bugs. if you have a question you can post it to stackoverflow or discourse. please see https://reactnavigation.org/help
