### ISSUE TITLE
Navigate to root tab screen inside a tabnavigator

### ISSUE THREAD

**Issue by morfsys** [react-navigation/react-navigation#3570]
I have been using react-navigation for a while now. When I tried referring to this [Snack](https://snack.expo.io/@react-navigation/stacks-in-tabs) on Expo, I realised that if I navigate inside a tab, then I could not navigate back to Home Tab screen by pressing the Home button on the tabbar. I have to click on Back button that is present on the screen in order to navigate back to home.

Here is a piece of code:

`const HomeStack = StackNavigator({
    Home: { screen: HomeScreen },
    Details: { screen: DetailsScreen },
});

const SettingsStack = StackNavigator({
    Settings: { screen: SettingsScreen },
    Details: { screen: DetailsScreen },
});

export default TabNavigator({
    Home: { screen: HomeStack },
    Settings: { screen: SettingsStack },
});
 `

Referring to above code, if I click on Settings from the tabbar and then navigate to Details present inside that stack then I cant navigate back to Settings when I click on Settings again. I have to click on Back button that is present in the top section of the screen.

What is wrong here?

**Comment by brentvatne** [comment]
this is a known missing feature. it does not happen by default right now.

**Comment by morfsys** [comment]
Is there any work around?

**Comment by matthamil** [comment]
To clarify _why_ this happens: When you press on the tab button, you are already at that tab's route (the stacknavigator that gets rendered, including any routes it can navigate to). What you are wanting is for the StackNavigator at that route to reset. Like Brent said, this feature doesn't exist yet (maybe a great time to write an [RFC](https://github.com/react-navigation/rfcs) 😄 )

**Comment by morfsys** [comment]
I will try achieving it by rendering a custom TabBar as a workaround. Hope for the best!

**Comment by valinaga** [comment]
you can add this to your TabNavigator:
```
    navigationOptions: ({ navigation }) => ({
      tabBarOnPress: ({ previousScene, scene, jumpToIndex }) => {
        const { route, focused, index } = scene;
        if (!focused) {
          if (route.index > 0) {
            const tabRoute = route.routeName;
            const { routeName, key } = route.routes[0];
            navigation.dispatch(
              NavigationActions.navigate({ routeName: tabRoute })
            );
            navigation.dispatch(
              NavigationActions.reset({
                index: 0,
                key,
                actions: [
                  NavigationActions.navigate({ routeName })
                ]
              })
            );
          } else {
            jumpToIndex(index);
          }
        }
      },
    })
```
It worked for me.

**Comment by morfsys** [comment]
Will try this.

**Comment by brentvatne** [comment]
moving this to https://github.com/react-navigation/react-navigation/issues/3588

**Comment by chawax** [comment]
Thanks @valinaga , it helped me a lot ! I just had to remove `key` argument  in `NavigationActions.reset` because I use React Navigation 1.x but it did the work 👍

**Comment by farhadeidi** [comment]
I’ve created a gist to solve this problem:

https://gist.github.com/farhadeidi/d9f3af865d4f58d9e5c0c9dc4cc4ee6d
