### ISSUE TITLE
Setting title & buttons on header when drawer opens

### ISSUE THREAD

**Issue by jadidian** [react-navigation/react-navigation#3571]
I'm not sure if this is a bug or its supposed to behave like this; I'm nesting a `DrawerNavigator` in a `StackNavigator` so the drawer opens behind the navigation bar; I would like to switch the "hamburger" button with a "close" button when the menu opens.

---

### Current Behavior

All the header contents (title & buttons) disappear when opening the drawer.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/650099/36536753-5298774a-17e3-11e8-9a2c-ff2e04a448cd.gif)

This is some parts of the code:
```js
const ApplicationNavigator = StackNavigator({ ... });

const MenuNavigator = DrawerNavigator({
  Application: {
    screen: ApplicationNavigator
  },
  LogIn: {
    path: '/log-in',
    screen: Authentication
  }
},
{
  initialRouteName: 'Application',
  drawerOpenRoute: 'DrawerOpen',
  drawerCloseRoute: 'DrawerClose',
  drawerToggleRoute: 'DrawerToggle',
  contentComponent: DrawerContent
});

const MainNavigator = StackNavigator({
  Menu: {
    screen: MenuNavigator
  }
});
```

I have custom content for the drawer and have tried setting `navigationOptions` on the drawer content component, but it didn't have any effects:

```js
class DrawerContent extends Component {

  static navigationOptions = ({ navigation }) => {
    const { state, setParams } = navigation;
    const { params } = state;
    return {
      headerTitle: 'Menu',
      headerLeft: (
        <HeaderButtons IconComponent={ Icon } iconSize={ 24 } color={ palette.lightGrey }>
          <HeaderButtons.Item iconName="close" onPress={ () => navigation.navigate('DrawerToggle') } />
        </HeaderButtons>
      )
    };
  }
}
```

### Expected Behavior

Being able to set title & buttons for opened drawer.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.3
| react-native     | 0.52.0
| node             | 8.4.0
| yarn      | 1.2.1

UPDATE: Also tried it with `react-navigation@1.1.2`, still the same...

**Comment by jadidian** [comment]
UPDATE: I was able to do this by changing my `MainNavigator` to:
```js
const MainNavigator = StackNavigator({
  Menu: {
    screen: MenuNavigator,
    navigationOptions: ({ navigation }) => {
      const { state } = navigation;
      if (state.routes[ state.index ].key !== 'DrawerClose') {
        return {
          headerTitle: <Image source={ require('...') } />,
          headerLeft: (
            <HeaderButtons IconComponent={ Icon } iconSize={ 24 } color={ palette.lightGrey }>
              <HeaderButtons.Item iconName="close" onPress={ () => navigation.navigate('DrawerToggle') } />
            </HeaderButtons>
          )
        };
      } else {
        return null
      }
    }
  }
});
```

But I was wondering if this the best way to achieve this...

**Comment by wzup** [comment]
Same https://github.com/react-navigation/react-navigation/issues/469#issuecomment-290640137

**Comment by wzup** [comment]
One more https://github.com/react-navigation/react-navigation/issues/374

**Comment by brentvatne** [comment]
update to react-navigation 2.x and this is resolved
