### ISSUE TITLE
Header Components Unable to Access Screen State

### ISSUE THREAD

**Issue by bsbechtel** [react-navigation/react-navigation#3572]
### Current Behavior

A common mobile design pattern is to provide action buttons inside the header bar based on content inside the current screen. Oftentimes, these actions depend on state or properties stored inside the current screen/component.

However, there doesn't seem to be a straightforward way to access screen component properties in the header. The `navigationOptions` is a static class property which passes `navigationOptions`, `screenProps`, and the `navigation` property to the header when used in its functional form, but `this` is inaccessible and instead refers to the global object.

A dependency on a third party global state management library shouldn't be a requirement, considering the stored state is local to the current screen. Also, lifting state up and passing it in as `screenProps` unnecessarily complicates your application component tree, as you would need a stateful component above your navigator specifically for managing state in one screen (consider if you needed to access state on many screens managed in the same navigation component!).

The solution found by myself and others in the community is to pass your state (or any other component class property) as a navigation `param`, however this seems like both an anti-pattern (and also a possible security issue if you are deep linking to your app?).

I saw there is a PR needing [review](https://github.com/react-navigation/react-navigation/pull/2990) that would bind the component class instance to the static `navigationOptions` method. However, the comments as to why the PR shouldn't be merged don't appear particularly persuasive as to why a user shouldn't be able to directly access a screen component's properties in that screen's header bar.

If binding this properly on the `navigationOptions` static method isn't an acceptable solution to this problem, I'd like to see if there are other acceptable solutions anyone might have so we can avoid passing class properties around in navigator `params`.

### Expected Behavior

Component class properties are accessible in the `navigationOptions` static method to allow header bar events and actions based on the current screen.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0
| react-native     | 0.53.2
| node             | 9.4.0
| npm or yarn      | 5.6.0

**Comment by satya164** [comment]
https://github.com/react-navigation/rfcs/issues/24
