### ISSUE TITLE
Additional Icon instead of Active tintColor

### ISSUE THREAD

**Issue by TamsynJennifer4** [react-navigation/react-navigation#3573]
Hello, 
Based on the custom Tab Bar (ios) is there a way to have an active icon (yellow triangles) instead of an active tint color?

![screen shot 2018-02-22 at 19 14 59](https://user-images.githubusercontent.com/32341857/36559176-1c7631f8-1805-11e8-9253-f09af648d6fc.png)

**Comment by matthamil** [comment]
Hi! The Issues are meant to be for bug reports. You can create your own custom tab bar component that accomplishes this: https://reactnavigation.org/docs/tab-navigator.html#tabnavigatorconfig

**Comment by TamsynJennifer4** [comment]
Sorry.
