### ISSUE TITLE
withNavigation() is incompatible with react-native-tab-view

### ISSUE THREAD

**Issue by arnoldbird** [react-navigation/react-navigation#3577]
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

Yes

### Environment

Environment:
  OS: macOS High Sierra 10.13.3
  Node: 9.5.0
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: https://github.com/expo/react-native/archive/sdk-25.0.0.tar.gz => 0.52.0

### Steps to Reproduce

1.  Create an app with create-react-native-app
2. Install react-native-tab-view and react-navigation
3. Copy the Example code from react-native-tab-view README into the new app's App.js
4. Implement withNavigation as directed at https://reactnavigation.org/docs/connecting-navigation-prop.html

### Expected Behavior

I expected that I would be able to access the navigation prop in my component.

### Actual Behavior

The navigation prop is not found in this.props, and I see this error...

Warning: Failed context type: The context `navigation` is marked as required in `withNavigation(TabViewExample)`, but its value is `undefined`.

### Reproducible Demo

To reproduce the bug, I recommend running the code with react-native run-ios.  I do not get the error if I scan the QR from the snack, but I get the error if I run the exact same code with react-native run-ios, both in the simulator and in my device.
https://snack.expo.io/BJQoAMaPz

Here are the modules installed:

{
  "name": "AwesomeProject",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "react-native-scripts": "1.11.1",
    "jest-expo": "25.0.0",
    "react-test-renderer": "16.2.0"
  },
  "main": "./node_modules/react-native-scripts/build/bin/crna-entry.js",
  "scripts": {
    "start": "react-native-scripts start",
    "eject": "react-native-scripts eject",
    "android": "react-native-scripts android",
    "ios": "react-native-scripts ios",
    "test": "node node_modules/jest/bin/jest.js"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "expo": "^25.0.0",
    "react": "16.2.0",
    "react-native": "0.52.0",
    "react-native-tab-view": "0.0.74",
    "react-navigation": "^1.1.2"
  }
}

**Comment by arnoldbird** [comment]
I should probably stop trying to integrate react-native-tab-view with React Navigation.  In my earlier attempts this week, I did declare a StackNavigator in the app root, but still was not able to access the navigation prop.  The reason I did not declare a StackNavigator in the above demo is that the documentation at reactnavigation.org does not give me the impression that should be necessary for use of withNavigation.  

I have generally not been trying to use withNavigation in my efforts.  My attempt to use withNavigation yesterday was a last ditch effort to determine if react-native-tab-view can jibe with React Navigation.  

I certainly trust you when you say that the two are compatible, but I have found it exhausting to try to make it work.  All other concepts in React Native have been fairly easy for me to figure out, despite not having any prior experience with React.

Because I'm new to React and to React Native, it might be best for me to confine myself to React Navigation and not attempt to use it alongside any other navigation library.

**Comment by satya164** [comment]
> I did declare a StackNavigator in the app root, but still was not able to access the navigation prop

Can you post a reproducible example? There is no reason it won't work. And as I replied, react-navigation already uses this library internally: https://github.com/react-navigation/react-navigation/blob/master/src/views/TabView/TabView.js#L3

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
