### ISSUE TITLE
Unexpected slide-up transition for TabNavigator with 1.1.x

### ISSUE THREAD

**Issue by MoOx** [react-navigation/react-navigation#3579]
### Current Behavior

- What code are you running and what is happening?

```js
const Navigator = TabNavigator(tabs, {
  // force to bottom, (for android)
  tabBarPosition: 'bottom',
  // NOTE: I tried without and with lazy and removeClippedSubviews (separately and together)
  lazy: false,
  removeClippedSubviews: false,
  animationEnabled: false,
  tabBarOptions: {
    inactiveTintColor: config.color.secondary,
    inactiveBackgroundColor: config.color.darkGray,
    activeTintColor: config.color.tertiary,
    activeBackgroundColor: config.color.darkGray,
    showIcon: true,
  },
  initialRouteName: initialTab,
  tabBarComponent: TabBar,
});
```
- Include a screenshot if it makes sense.

![rnav bug](https://user-images.githubusercontent.com/157534/36585922-0c1c04ec-1880-11e8-8ac3-93df7459fbd4.gif)

### Expected Behavior

- What do you expect should be happening?

I don't expect to have my child stack navigator coming from the bottom.
I didn't have this problem with 1.0.x(alphas) or 1.0.x (with no lazy)

1) why am I getting this transition? I would prefer to have no transition than this slide up
2) I think `ResourceSavingSceneView` is probably too agressive at trying to save us from something, especially with `lazy` and `removeClippedSubviews` set to `false`.
3) I tried to play with `animationEnabled` (to `false`) but no luck I randomly have screen from tabs that show up from the bottom.

I am really confused on the origin of this transitions.

(I also tried to force child navigators (stacknavigators) as mode: card, but this doesn't change the behavior)

### How to reproduce

I am not really able to quickly share my code.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.1.1
| react-native     | 0.52
| node             | 8.x
| npm or yarn      | yarn 1.3.2

**Comment by MoOx** [comment]
Ok very sorry for the noize, seems related to the fact that we pass some information to redux. The more I use redux, the more I hate it haha.

**Comment by jeffreymendez1993** [comment]
happens to me as well when making fetch request on navigation change.

**Comment by jeffreymendez1993** [comment]
CAn you re-open @MoOx

**Comment by MoOx** [comment]
No I don't, it's not a library bug, but more a bad usage of it. Maybe this lib can be improved to avoid the issue we faced, but without a stable reproduction I won't reopen. Feel free to create an example via expo or similar and create a new issue if you feel like there is a bug in the lib, cause I don't :/

**Comment by donovanCarreno** [comment]
@jeffreymendez1993 - were you able to solve this issue?  I'm having the same problem even without making a fetch request on navigation change.  The weird thing is that it only happens when navigating from Tab B to Tab C or Tab B to Tab A.  It works just fine when navigating between Tab A and Tab C directly.

Thanks!

**Comment by qalqi** [comment]
+1

**Comment by qalqi** [comment]
Please re-open the issue

**Comment by satya164** [comment]
@qalqi open a new issue and fill the issue template to demonstrate your problem

**Comment by qalqi** [comment]
@satya164  Its the same issue as illustrated. 
The bug is using FAR_FAR_AWAY

**Comment by satya164** [comment]
The bug was reported with react navigation 1.x, current version is 3.x.

**Comment by qalqi** [comment]
Will try to create new issue. 
Meanwhile, Jumpy loading of views happens in react navigation 3.x,  android only when  lazy: true,

```
import { useScreens } from 'react-native-screens'; 
false && useScreens() // Unexpected slide-up
true && useScreens() // No slide-up

```

**Comment by qalqi** [comment]
```javascript
import {
    NativeModules,
    LayoutAnimation,
    StyleSheet,
    View,
    Dimensions
} from 'react-native';
const width = Dimensions.get('window').width;
const { UIManager } = NativeModules;

UIManager.setLayoutAnimationEnabledExperimental &&
UIManager.setLayoutAnimationEnabledExperimental(true); 
```

` UIManager.setLayoutAnimationEnabledExperimental(true); ` in custom tab bar without `useScreens()` making the unexpected slide-up transition.

 ` UIManager.setLayoutAnimationEnabledExperimental(true); ` in custom tab bar with `useScreens()` making the unexpected slide-up transition.

**Comment by liogate** [comment]
Same issue here. But seems working using 
```{js}
UIManager.setLayoutAnimationEnabledExperimental && UIManager.setLayoutAnimationEnabledExperimental(true);
useScreens();
```
in my custom tab componnent.

**Comment by limiaspasdaniel** [comment]
Is this issue still happening for you all? It's happening to me when switching between bottom tab navigator tabs.
