### ISSUE TITLE
Blank screen with TabNavigator inside StackNavigator when using Redux for navigation state

### ISSUE THREAD

**Issue by alizahid** [react-navigation/react-navigation#3586]
Snack https://snack.expo.io/@alizahid/blank-screen

### Current Behavior

Starts with `login`, and then navigates to `app`.

But once there, other than the initial tab `one`, the rest are all blank if I navigate using `TabBar`. If I navigate with `navigate('two')`, it works fine.

At first, I thought maybe it was my views. So I replaced all three with the first one, which renders properly. But that didn't work.

This leads me to believe that `TabBar` isn't invoking the proper methods for navigation, or some such issue.

### Expected Behavior

`TabBar` should render the other screens. I've even tried setting `lazy` to `false`, but that didn't help.

### How to reproduce

Snack https://snack.expo.io/@alizahid/blank-screen

Video https://imgur.com/a/FVzZ6

### Your Environment

| software  | version
| ----- | -----
| react-navigation | 1.1.2
| react-native | 0.53.3
| node | 9.5.0
| yarn | 1.3.2

**Comment by peterpme** [comment]
I'm assuming this has something to do with:
https://github.com/react-navigation/react-navigation/commit/3600ecbd9bf62be4e1c0d4632bb0d8f5635c9454

I'm having the same issue. Will debug and see if I can help!

**Comment by peterpme** [comment]
Downgrading to 1.0.3 should temporarily fix this for you @alizahid

**Comment by alizahid** [comment]
Thank you. Will downgrade for now, but looking forward to a fix. Anything I can do to help?

**Comment by peterpme** [comment]
It's something inside `ResourceSavingSceneView.js`. If you'd like to place some console.log's in there and note your findings, that would be helpful 😄 Thanks!

**Comment by peterpme** [comment]
Tapping tab first time: `visible: false`
Tapping tab second time: `visible: true`

**Comment by alizahid** [comment]
What would you like me to log?

**Comment by alizahid** [comment]
All right, so I logged `state.visible`, and it does indeed set it to `true` once and then `false` immediately.

**Comment by brentvatne** [comment]
fwiw, I removed redux from the example and there is no problem: https://snack.expo.io/SkutLb0vM

**Comment by peterpme** [comment]
@brentvatne it works fine without using redux. Only happens with redux 

Side redux chat:

I would love to get rid of it, but I only use it because of `dispatch`. ```this.props.dispatch(NavigationActions.navigate())```

**Comment by brentvatne** [comment]
`this.props.navigation.dispatch` ?

**Comment by peterpme** [comment]
when top level and figuring out logged in / logged out:

```<AppNavigator ref={n => this.nav = n)```

```this.nav && this.nav.dispatch``` would poop out on me from time to time

Maybe I should handle logged in / logged out a level under `AppWithNavigationState`

**Comment by peterpme** [comment]
Anyway, this is a chat outside the scope of this issue! Thanks for the help! 😄 

I will try to remove Redux from my app and get this working!

**Comment by alizahid** [comment]
Removing the `navigation` prop from my `Navigator` component does indeed fix it.

And this won't have any effect on `navigation` being available inside connected components?

**Comment by brentvatne** [comment]
right. using redux with react-navigation is optional and something that i just would not recommend in general

**Comment by brentvatne** [comment]
cc @Ashoat re: redux integration issues and lazy tabs

**Comment by alizahid** [comment]
I'm a tad confused by that statement. Do you mean I should not use Redux in my React Native app if I'm using React Navigation? Or just not connect them to each other?

I've got `addListener` and `createReactNavigationReduxMiddleware` from `react-navigation-redux-helpers` and the `state` reducer.

**Comment by brentvatne** [comment]
you can use redux in your app just fine. I just suggest not using it to hold your react-navigation state

**Comment by peterpme** [comment]
I think the issue that a lot of folks have (myself included) is handling logged in / logged out state without redux.

I know this is an easy issue to fix, but I think it *clicks* for some people and doesn't *click* for others.

I'd be happy to write up the documentation because I've gone through several attempts and always fall back to redux due to time.

This is literally the only reason I use **redux /w react-navigation**:

```es6
componentDidMount() {
   const { dispatch, session} = this.props
    if (session.loggedIn) {
      dispatch(NavigationActions.navigate({ routeName: 'MainTab' })
    } else {
      dispatch(NavigationActions.navigate({ routeName: 'Splash' })
    }

    render() {
      return <AppNavigator navigation={addNavigationHelpers({ /* */ })} />
    }
}
```

When I try to do : 
```
componentDidMount() {
   const { session} = this.props
    if (session.loggedIn) {
      this.navigation && this.navigation.dispatch(NavigationActions.navigate({ routeName: 'MainTab' })
    } else {
      this.navigation && this.navigation.dispatch(NavigationActions.navigate({ routeName: 'Splash' })
    }

    render() {
      return <AppNavigator ref={n => this.navigation =n} />
    }
}
```

I get `dispatch` is undefined which is really frustrating. I know its a me thing and not a react-nav thing.

I've also considered a component that comes AFTER `<AppNavigator />` but BEFORE the `StackNavigator` that has `this.props.navigation` and lets me figure out the logged in / logged out state, but I'm at a loss as to where that would go:

1) do I use `withNavigation` outside of this tree // top level `AppWithNavigationState`
2) do I check logged in / logged out on the first loaded tab (or splash screen in my case)
3) Do I do something like:


```

const AppNavigator = StackNavigator({
Splash: { screen: SplashNavigator },
Onboarding: { screen: OnboardingStackNavigator },
Main: { screen: MainTabNavigator }
})

class Auth extends React.Component {
   // all that if logged in / logged out logic here
   render() {
       return <AppNavigator /> somehow
   }
}

const RootNavigator = StackNavigator(
{
  App: { screen: Auth }
}

```

**Comment by alizahid** [comment]
I removed Redux from React Navigation, and resorting to navigating on login and logout, and if that's what I need for a clean'ish approach, then I'm okay with it.

**Comment by brentvatne** [comment]
I renamed this issue to indicate that it's redux related

**Comment by peterpme** [comment]
@alizahid can you explain how you did that?

**Comment by alizahid** [comment]
### How to remove Redux from React Navigation

1. Remove the `state` reducer
2. Remove `navigation` and `addNavigationHelpers` props from app navigator
3. Remove all `react-navigation-redux-helpers` related code -- `addListener` from `addNavigationHelpers` and `createReactNavigationReduxMiddleware` from Redux store
4. Remove `dispatch` and `state` from app component -- I removed `mapStateToProps` entirely, because I was only using it for those two
5. Remove the `react-navigation-redux-helpers` package

This should clean up your code considerably. Good riddance, I say!

**Comment by peterpme** [comment]
but then how do you navigation logged in / logged out? this.navigation.dispatch?

**Comment by danjocha** [comment]
I'm having the same issue here. Removing Redux is not an option for me so any help would be really appreciated.

**Comment by alizahid** [comment]
@peterpme Yes, I navigate between screens on login and logout. I just `reset` like

```
import { NavigationActions } from 'react-navigation'

...

const { isLoggedIn, navigation } = this.props

const routeName = isLoggedIn ? 'main' : 'login'

const reset = NavigationActions.reset({
  index: 0,
  actions: [
    NavigationActions.navigate({
      routeName
    })
  ]
})

navigation.dispatch(reset)
```

**Comment by Ashoat** [comment]
I am not seeing this issue in my project. The Snack linked above (https://snack.expo.io/@alizahid/blank-screen) has a simple typo that is causing the blank screen. `state.nav` in store.js should be `state.state`; both the reducer and `App`'s `mapStateToProps` use the key named `state`.

Lots of people on this issue, so presumably not everybody made the same typo. Glad to debug this further if we can get a Snack that repros the issue!

**Comment by Ashoat** [comment]
By the way folks, note that the Redux integration docs have changed since we went to 1.0. Redux middleware and a separate npm package are required now. My theory is that many people missed it, or implemented it incorrectly (as in the Snack), but things didn't really start breaking until something in `react-navigation` actually started depending on the new `addListener` prop working in 1.1? Just a theory, again I'll take a look once I have a repro :)

**Comment by peterpme** [comment]
Hey @Ashoat,

FWIW - If I downgrade to 1.0.3 things work correctly w/ redux. I'd be happy to share repo access with you to show you.

**Comment by gianpaj** [comment]
I got into the same issue after upgrading from `1.0.3` to `1.1.1`.
`tabBarOnPress()` runs inside a Tab component.

e.g.
```jsx
export class AddProductScreen extends React.Component<Props, State> {
  static navigationOptions = (props: any) => {
    return {
      // navigate to the screen instead of showing as a normal tab screen
      tabBarOnPress: ({ scene }: any) => {
        if (!scene.focused) {
          props.navigation.navigate('addProduct', { focused: !scene.focused });
        }
      },
    };
  };
```

But `componentWillMount()` doesn't run 😞 

@peterpme can you share your code as a gist, for example, or somewhere where we can fork it? might help us all try to debug this quicker

**Comment by alizahid** [comment]
@peterpme @Ashoat Confirming, it was indeed the typo. After the amount of time I spent on it, I'm not even surprised that was the solution. Thanks!

**Comment by gianpaj** [comment]
That was the issue for me as well.

I had to change this:
```jsx
const middleware = createReactNavigationReduxMiddleware(
  'root',
  state => state.nav
);
```

to this:
```jsx
const reactNavigation = createReactNavigationReduxMiddleware('root', state => {
  return state.LoginReducer.isLoggedIn == true
    ? state.NavigationReducer.stateForLoggedIn
    : state.NavigationReducer.stateForLoggedOut;
});
```

because I have this inital _state_:
`navigationReducer.js`
```jsx
const stateForLoggedOut = NavigationStack.router.getStateForAction(
  ActionForLoggedOut
);
const stateForLoggedIn = NavigationStack.router.getStateForAction(
  ActionForLoggedIn
);

const initialState = { stateForLoggedOut, stateForLoggedIn };
```

but now the app doesn't restore the state correctly 🤦‍♂️ 
i'll open a StackOverflow question if I can't get this to work...
or just remove redux from react navigation

**Comment by peterpme** [comment]
@gianpaj removing redux is the best option 😄
