### ISSUE TITLE
TabNavigator default double press behaviors

### ISSUE THREAD

**Issue by brentvatne** [react-navigation/react-navigation#3588]
Collapsing the following issues into one:
- [x] scroll to top - https://github.com/react-navigation/react-navigation/issues/2955
- [x] pop to top - https://github.com/react-navigation/react-navigation/issues/3570

**Comment by brentvatne** [comment]
done: https://react-navigation.canny.io/feature-requests/p/scroll-to-top-of-current-tab-when-it-is-pressed-again-in-tabnavigator

**Comment by FrenchMajesty** [comment]
Following up, It would be nice to see something for "Pop to Top" as well.

**Comment by brentvatne** [comment]
@FrenchMajesty - that happens automatically if you have a stack within a tab

**Comment by octodhruv** [comment]
> @FrenchMajesty - that happens automatically if you have a stack within bottom tabs

@brentvatne could you please expand on this? Or perhaps show a working example? That would be super helpful :)

**Comment by farhadeidi** [comment]
I’ve created a gist to solve this problem:

https://gist.github.com/farhadeidi/d9f3af865d4f58d9e5c0c9dc4cc4ee6d
