### ISSUE TITLE
DrawerNavigator with dynamic routes should be possible

### ISSUE THREAD

**Issue by alex-gunning** [react-navigation/react-navigation#3591]
## The issue tracker is reserved for bug reports only.

If you have a question, feature request, or an idea for improving the library or its related tools, please try one of the following resources:

- [Read the documentation](https://reactnavigation.org/)
- [Post an issue to the website repository if you'd like to see a documentation change](http://github.com/react-navigation/website)
- [Post a feature request to Canny](https://react-navigation.canny.io/feature-requests)
- [Write a RFC if you have ideas for how to implement a feature request](https://github.com/react-navigation/rfcs)
- [Get help on Discord chat (#react-navigation on Reactiflux)](https://discord.gg/4xEK3nD) or [on StackOverflow](https://stackoverflow.com/questions/tagged/react-navigation)
- Search for your issue - it may have already been answered or even fixed in the development branch. However, if you find that an old, closed issue still persists in the latest version, you should open a new issue.

---

### Current Behavior

Please see this snack for what I wish to achieve (with code) : https://snack.expo.io/HJ7ggj0vz

Look specifically in **DrawerNavigation.js** 

I'm trying to implement a DrawerNavigator with a list of dynamic routes from Redux state. The DrawerNavigator is a child of a TabNavigator. The TabNavigator is setup so there is a menu button which toggles the drawer open and closed.

This is an example of a DrawerNavigator with pre-defined routes: https://snack.expo.io/B1VlMsADf
(I'm not sure why the menu button is now not opening the drawer in this snack but that's what I'm attempting to achieve). It's a copy of the same code above but with static routes initialized.

You'll see that, in the first one, I left a comment about the static router property.
_// FoodHOC.router = FoodDrawer.router;_

I'm fairly confident that the example would run if I could find a way to add that router property to my HOC.

I'd appreciate any assistance. I've been trying to get this to work for four days.

### Expected Behavior

I should be able to define dynamic routes from redux state.

### How to reproduce

Run this and examine the source specifically of **DrawerNavigator.js**: https://snack.expo.io/B1VlMsADf
Then look at this and see how I'm trying to set up dynamic routes in **DrawerNavigator.js** https://snack.expo.io/HJ7ggj0vz

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.1.1
| react-native     | 0.52
| node             | 9.4.0
| npm      | 4.6.1

**Comment by brentvatne** [comment]
please open a feature request for this. this is not a bug. we don't support dynamic routes. http://react-navigation.canny.io/
