### ISSUE TITLE
Current key

### ISSUE THREAD

**Issue by sm2017** [react-navigation/react-navigation#3596]
How can I get current screen's `key`?

**Comment by matthamil** [comment]
Hey @sm2017 ! The issue tracker is for bug reports. I recommend checking out some of the resources listed in the [issue template](https://github.com/react-navigation/react-navigation/blob/master/.github/ISSUE_TEMPLATE.md) or [README](https://github.com/react-navigation/react-navigation/blob/master/README.md).

**Comment by brentvatne** [comment]
`this.navigation.state.key`

**Comment by sm2017** [comment]
@brentvatne , Sorry for `issue template or README` 
But `this.props.navigation.state.key` is undefined

**Comment by sm2017** [comment]
@brentvatne help please

**Comment by matthamil** [comment]
@sm2017 Check out the resources listed in the [Issue Template](https://github.com/react-navigation/react-navigation/blob/master/.github/ISSUE_TEMPLATE.md). The Issues on the repo are meant exclusively for bug reports.
