### ISSUE TITLE
nested TabBarNavigator in StackNavigator cause blank screens

### ISSUE THREAD

**Issue by Under-Warz** [react-navigation/react-navigation#3607]
### Current Behavior

When I navigate between Tabbar screen, the initial screen is loaded properly, mais the other are blank (no render method call)

Here is a demo to reproduce the bug : https://snack.expo.io/@lmenu/sample-for-tabbar-bug

### How to reproduce

This bug seems to be present since the version 1.1.2 (I rollback to 1.0.3 temporarly and it's ok)

I red that adding param `swipeEnabled: false, animationEnabled: false, lazy: true` solve the problem. I did it but have no effect. But if I put `swipeEnabled: true` or `animationEnabled: true`, everything is OK.

Here is the structure of my navigation routes.

- Root StackNavigator (mode modal)
 -- Auth StackNavigator
 -- App TabBarNavigator
 ---- Home StackNavigator
 ---- Notif StackNavigator
 ---- ... Other navigators
 -- ... Other modals

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.2.0
| react-native     | 0.50.4
| node             | 9.4.0
| yarn      | 1.3.2

I'm using Redux with the new library package (react-navigation-redux-helpers)

Thank's in advance.

**Comment by brentvatne** [comment]
hi there! please post this to https://github.com/react-navigation/react-navigation-redux-helpers unless you can reproduce it without using redux.

thanks!

**Comment by hushicai** [comment]
+1

I meet the same issue.

**Comment by Under-Warz** [comment]
@brentvatne @hushicai here is a test without Redux and I did not get the bug, I'm gonna open a new issue on  https://github.com/react-navigation/react-navigation-redux-helpers 

https://snack.expo.io/@lmenu/sample-for-tabbar-bug-without-redux

**Comment by hushicai** [comment]
@Under-Warz yes, without redux, everything is ok.

**Comment by Under-Warz** [comment]
@hushicai here is the other ticket you can follow https://github.com/react-navigation/react-navigation-redux-helpers/issues/10
