### ISSUE TITLE
TabPage switch screen does not display

### ISSUE THREAD

**Issue by cx5168** [react-navigation/react-navigation#3610]
Use version：
react-navigation^1.2.1
react-navigation-redux-helpers^1.0.1

result：
The screen defined in TabNavigator does not display when tab switches.

![1](https://user-images.githubusercontent.com/29448456/36709740-d0db9894-1bbc-11e8-8886-239c85fc099d.png)
![2](https://user-images.githubusercontent.com/29448456/36709741-d11519e8-1bbc-11e8-9dc0-9e87cc6710a3.png)

routes.js：
import {
  StackNavigator,
  TabNavigator,
} from 'react-navigation';
import TabOne from '../components/TabOne';
import TabTwo from '../components/TabTwo';
import TabThree from '../components/TabThree';
import ScreenOne from '../components/ScreenOne';
import ScreenTwo from '../components/ScreenTwo';

const Routes = {
  ScreenOne:{screen:ScreenOne},
  ScreenTwo:{screen:ScreenTwo},
  TabOne:{screen:TabOne},
  TabTwo:{screen:TabTwo},
  TabThree:{screen:TabThree},
};

const TabScreen = TabNavigator(
  {
    TabOne:{screen:TabOne},
    TabTwo:{screen:TabTwo},
    TabThree:{screen:TabThree},
  },
  {
    swipeEnabled: true,
    tabBarPosition: 'bottom',
    animationEnabled: true,
  }
);

const AppNavigator = StackNavigator(
  {
    ...Routes,
    TabScreen:{screen:TabScreen}
  },
  {
    initialRouteName: 'TabScreen'
  }
);

export default AppNavigator;

Ask for help！

**Comment by brentvatne** [comment]
see https://github.com/react-navigation/react-navigation-redux-helpers/issues/7

feel free to investigate. i can have a look soon but redux support isn't a priority for me

**Comment by wuyunqiang** [comment]
maybe set ```lazy:false,```

**Comment by cx5168** [comment]
@wuyunqiang   Wow, that's the solution. Thank you very much.

**Comment by zhouyingkai1** [comment]
@wuyunqiang   set lazy:false can't fixed it, only display one page

**Comment by cx5168** [comment]
@zhouyingkai1   If you use Redux, you need to install react-navigation-redux-helpers

see react-navigation/react-navigation-redux-helpers#7

**Comment by zhouyingkai1** [comment]
I've done this already, but can't fiexed it
