### ISSUE TITLE
TabNavigator blank screen with redux

### ISSUE THREAD

**Issue by hushicai** [react-navigation/react-navigation#3611]
When using redux integration, TabNavigator just render the first screen, and when i switch to other tab. screen is empty!

Here is my code:

```javascript
const TabsNav = TabNavigator(
  {
    messages: {
      screen: Messages,
      path: '/tab/messages'
    },
    baike: {
      screen: Baike,
      path: '/tab/baike'
    },
    setting: {
      screen: Setting,
      path: '/tab/setting'
    }
  },
  {
    laze: true,
    tabBarPosition: 'bottom',
    animationEnabled: false,
    swipeEnabled: false
  }
);

export default {
  tabs: {
    screen: TabsNav
  }
};
```

TabNavigator render `messages` correctly, buy empty screen for other tabs...

When i remove redux integration code, everything become well.

but i really need redux to navigate.

**Comment by hushicai** [comment]
react-navigation/react-navigation-redux-helpers#7

**Comment by cx5168** [comment]
I have the same problem.
https://github.com/react-navigation/react-navigation/issues/3610

**Comment by brentvatne** [comment]
see https://github.com/react-navigation/react-navigation-redux-helpers/issues/7
