### ISSUE TITLE
lastState and state in event payload are always same

### ISSUE THREAD

**Issue by kyo504** [react-navigation/react-navigation#3612]
### Current Behavior

From the source code, I could see the content of payload for event callback.
```
      const childPayload = {
        context: `${key}:${action.type}_${payload.context || 'Root'}`,
        state: newRoute,
        lastState: lastRoute,
        action,
        type: eventName,
      };
```
I guess that `lastState` means the route where I come from but it is always same as `state`.

### Expected Behavior

`lastState` should be route where I come from, not the same as `state`.

### How to reproduce

Here is the reproducible code.
```
import React from 'react';
import { View, Text } from 'react-native';
import { StackNavigator, TabNavigator } from 'react-navigation';

class ScreenA extends React.Component {
  componentWillMount() {
    this.willFocusSubscription = this.props.navigation.addListener('willFocus', payload => {
      console.log(payload);
    });
    this.willBlurSubscription = this.props.navigation.addListener('willBlur', payload => {
      console.log(payload);
    });
  }

  componentWillUnount() {
    this.willFocusSubscription.remove();
    this.willBlurSubscription.remove();
  }

  render() {
    return (
      <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
        <Text>ScreenA</Text>
      </View>
    );
  }
}

class ScreenB extends React.Component {
  componentWillMount() {
    this.willFocusSubscription = this.props.navigation.addListener('willFocus', payload => {
      console.log(payload);
    });
    this.willBlurSubscription = this.props.navigation.addListener('willBlur', payload => {
      console.log(payload);
    });
  }

  componentWillUnount() {
    this.willFocusSubscription.remove();
    this.willBlurSubscription.remove();
  }

  render() {
    return (
      <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
        <Text>ScreenA</Text>
      </View>
    );
  }
}

const AppNavigator = TabNavigator({
  ScreenA: ScreenA,
  ScreenB: ScreenB
});

export default class App extends React.Component {
  render() {
    return <AppNavigator />;
  }
}
```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.2.1
| react-native     | 0.53.0
| node             | v9.3.0
| npm or yarn      | 5.6.0

**Comment by brentvatne** [comment]
`lastState` is the previous state that the current route was in. for a `TabNavigator`, for example, the state would change such that the `index` key would go from `index: 0` to `index: 1` when you change from the first to the second tab.

what is perhaps unintuitive here is that the specific route is provided, and not the state object for the navigator that contains it. @ericvicenti - curious what you think about this

**Comment by kyo504** [comment]
Thanks for clarifying the meaning of `lastState`. However, like you mentioned, it's a bit strange that actual value of `lastState` doesn't match one that what we expected.

**Comment by brentvatne** [comment]
closing because this isn't actionable. if you'd like to open a rfc to discuss changes it'd be welcome!

**Comment by st-sloth** [comment]
But is there a way to know, in these events, what route the current screen `willFocus` / `didFocus`  from or `willBlur` / `didBlur` to? What seems to have been expected in this issue originally.

**Comment by monaye** [comment]
@st-sloth only `willBlur` has the action with the `routname` of the screen that will display. I am also looking for a way to get the previous `routeName` on `willFocus` and `didFocus` but no luck so far.
