### ISSUE TITLE
Can´t find variable: navigate

### ISSUE THREAD

**Issue by Gonzalezmmiguel** [react-navigation/react-navigation#3616]
Hi everyone, i'm trying to navigate to my homeScreen but i'm getting this issue Can´t find variable: navigate.

I'm sorry i'm new in react.

#  ****MY APP.JS****

/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 * @flow
 */

import React, { Component } from 'react';
import { AppRegistry, TouchableOpacity, Platform, StyleSheet, Text, TextInput, View, Button } from 'react-native';
import { StackNavigator } from 'react-navigation';
import { HomeScreen }  from "./src/screens/homeScreen";

export default class App extends Component
{
  render() 
  {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>
          Welcome to React Native!
        </Text>
        <Text style={styles.instructions}>
          To get started, edit App.js
        </Text>
        <TextInput style={styles.username}
          placeholder="Username"
          //onChangeText={(text) => this.setState({text})}
        />
        <TextInput style={styles.password}
          placeholder="Password"
        />
        <TouchableOpacity style={styles.button} onPress={this.onPress}>
          <Text> Touch Here </Text>
        </TouchableOpacity>        
        <TouchableOpacity
          onPress = {() => { navigate("Home");}}>           
        <Text> Touch Heress </Text>     
        </TouchableOpacity>

      </View>
      
    );
  }
}

const RootStack = StackNavigator({
  Base: 
  {
    screen: App,
  },
  Home:
  {
    screen: HomeScreen,
    navigationOptions: {
      header: {
        visible: false
      }
    }
  }
},
{
  initialRouteName: "Base",
}
);

AppRegistry.registerComponent("Scheduled", () => RootStack);

/** -----------------------------------------------------------------------------  **/
const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
  button: {
    alignItems: 'center',
    backgroundColor: '#DDDDDD',
    padding: 15,
    width: 150,
  },
  username:{
    alignItems: 'center',
    width: 300,
  },
  password:{
    alignItems: 'center',
    width: 300,
  },
  buttonSignUpUser: {
    padding: 15,
    left: -50,  
  },
  countText: {
    color: '#FF00FF',
  },
});

# **MY homeScreen.js**

import React, { Component } from 'react';
import { AppRegistry, TouchableOpacity, Platform, StyleSheet, Text, TextInput, View, Button } from 'react-native';
import { StackNavigator } from 'react-navigation';

export class HomeScreen extends Component{
    render() {
      const { navigate } = this.props.navigation;
      return (
        <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
          <Text>Details Screen</Text>
        </View>
      );
    }
  }

**Comment by brentvatne** [comment]
you need to get navigate off props

```
<TouchableOpacity
onPress = {() => { this.props.navigation.navigate("Home");}}>
```

please post these kinds of question to stackoverflow in the future

**Comment by Gonzalezmmiguel** [comment]
i'm sorry brent, but when i use { this.props.navigation.navigate("Home");}} i get the next issue
undefined is not an object (evaluating '_this2.props.navigation.navigate')

**Comment by brentvatne** [comment]
sorry, we only provide support for bugs here. you should post this to stackoverflow for help :)
