### ISSUE TITLE
Hello from Callstack! 👋 

### ISSUE THREAD

**Issue by thymikee** [react-navigation/react-navigation#3622]
Hi React Navigation team!

At first, I'd like to say sorry for violating your carefully crafted issue template, but I'm not reporting a bug nor a feature request.

I ask you, however, to label as many issues as possible as "Good First Issue" or "Needs Triage" or similar, because for the upcoming week my small team at Callstack, as a part of our Open Source mission, is going to contribute to this repository. The labelling is very helpful to get productive inside your project faster, especially that we have limited time.

I can see the issue tracker is already in a pretty good shape (congrats! I've seen it couple of months ago 😄), but just wanted to let you know upfront. I hope we can ease the maintenance and close some bugs or even implement new features at least for upcoming few days.

I'll close this issue in a week, but feel free to close it earlier and leave it for discussion.

cc @brentvatne @ericvicenti @satya164 @skevy

**Comment by satya164** [comment]
This can be our first task: https://github.com/react-navigation/rfcs/pull/2
There is an open PR already, need to finish it and get it merged.

**Comment by satya164** [comment]
I have a bunch of issues [here](https://github.com/react-native-community/react-native-tab-view/labels/help%20wanted) I'd like to get some help with.

**Comment by brentvatne** [comment]
will go through more issues today and tag, thanks for the help :D

**Comment by satya164** [comment]
https://github.com/react-navigation/react-navigation/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22+
