### ISSUE TITLE
How to trigger the tabnavigator  hook function when I click the tabBarIcon and tabBarLabel 

### ISSUE THREAD

**Issue by heroofchina** [react-navigation/react-navigation#3624]
### I want to hide the header's  CommonTab whe I click the last tabbar's item

# This is my App.js
export default class App extends Component{
    constructor(props) {
      super(props);
    
      this.state = {
          #controll the header 's commontab show or hide
          showTabBar:true
      };
    }
    render(){
      return(
         <View style={styles.main}>
             
              <StatusBar
                 backgroundColor="#0b70ff"
                 barStyle="light-content"
               />
                 # this is the  CommonTab
               <CommonTab 
                showTabBar={this.state.showTabBar}
                />
               <Main/>
           
          </View> 
     );
    }
    componentDidMount(){
        RCTDeviceEventEmitter.addListener('SHOWBARS',(flag)=>{
           this.setState({
              showTabBar:flag
           });
        })
    }
    
}

# This is the screen config
const WorkBench=TabNavigator({
      Index:{
        screen:Index,
        navigationOptions:{
            tabBarLabel: '首页',
            tabBarIcon: ({tintColor}) =>(
                 <Text
                    style={[{color:tintColor},styles.tabFonts]}
                >&#xe61e;</Text>
            ),
        },
      },
      Course:{
        screen:Course,
        navigationOptions:{
            tabBarLabel: '课程',
            tabBarIcon: ({tintColor}) => (
                 <Text
                    style={[{color:tintColor},styles.tabFonts]}
                >&#xe60e;</Text>
            ),
        }
      },
      Player:{
          screen:Player,
          navigationOptions:{
            tabBarLabel: '直播',
            tabBarIcon: ({tintColor}) => (
                 <Text
                    style={[{color:tintColor},styles.tabFonts]}
                >&#xe60c;</Text>
            ),
        }
      },

      Stores:{
         screen:Stores,
         navigationOptions:{
            tabBarLabel: '题库',
            tabBarIcon: ({tintColor}) => {
                return ( <Text
                    style={[{color:tintColor},styles.tabFonts]}
                >&#xe60d;</Text>)
            }
               
            
        }
      },
      My:{
         screen:My,
         navigationOptions:{
            tabBarLabel: '我',
            tabBarIcon: ({tintColor}) => {
                return ( <Text
                    style={[{color:tintColor},styles.tabFonts]}
                >&#xe634;</Text>)
            },
        }

      }

},
{initialRouteName:'Index',
  lazy:true,
  animationEnabled:true,
  tabBarOptions:{
        activeBackgroundColor:'white',
        activeTintColor:'#2979FF',
        inactiveBackgroundColor:'white',
        inactiveTintColor:'#000',
        labelStyle:{
          fontSize: 12
        }
  }
 
});

# when I click the My Items I want to have a hock function let me to controll the commonbar,
but I using listener way now,this is code
export default class My extends Component{
      constructor(props) {
        super(props);
      
          this.state = {};
          console.log('SHOWBARS');
          RCTDeviceEventEmitter.emit('SHOWBARS',false);

          this.subs=this.props.navigation.addListener('willFocus', () => {
                        console.log('willFocus');
                        RCTDeviceEventEmitter.emit('SHOWBARS',false);
          });
          
      }
      render(){
             return (
                   <View>
                       <MyHeader/>
                       <MyMenu/>
                   </View>

            );
      }
      componentDidMount(){

          this.listen=this.props.navigation.addListener('didBlur', () => {
              console.log('didBlur');
              RCTDeviceEventEmitter.emit('SHOWBARS',true);
          });
      }
      
}

# and I found the way cause the the commonbar   instant disappearance,this is poor experience,
please whereone give me some comments,thanks !

**Comment by matthamil** [comment]
:wave: Hello! Thanks for the issue, and sorry you are experiencing issues. As the [issue template](https://github.com/react-navigation/react-navigation/blob/master/.github/ISSUE_TEMPLATE.md) explains, we require that you provide a runnable example that reproduces the bug on [Snack](https://snack.expo.io) or in a separate repository. Please try to minimize the extraneous code and focus on reproducing the bug.

We're closing any issues that do not have reproducible examples. Do not take this personally :). 

Please create a new issue with a reproducible example and one of the maintainers/collaborators would be glad to look at it!
