### ISSUE TITLE
Add listener for TabNavigator 's items but first click null and void,I think the is the component not listener this event

### ISSUE THREAD

**Issue by heroofchina** [react-navigation/react-navigation#3625]
## This is my code

export default class My extends Component{
      constructor(props) {
        super(props);
      
          this.state = {};
          console.log('SHOWBARS');
         // this is event is no effect when I first click the  tabbar items
          this.subs=this.props.navigation.addListener('willFocus', () => {
                        console.log('willFocus');
                        RCTDeviceEventEmitter.emit('SHOWBARS',false);
          });
          
      }
      render(){
             return (
                   <View>
                       <MyHeader/>
                       <MyMenu/>
                   </View>

            );
      }
      componentDidMount(){

          this.listen=this.props.navigation.addListener('didBlur', () => {
              console.log('didBlur');
              RCTDeviceEventEmitter.emit('SHOWBARS',true);
          });
      }
      
}

# but you can add this code to resolve it

RCTDeviceEventEmitter.emit('SHOWBARS',false); // Add the action that you hope,whether or not the event occurs or not
 
this.subs=this.props.navigation.addListener('willFocus', () => {
                        console.log('willFocus');
                        RCTDeviceEventEmitter.emit('SHOWBARS',false);
          });

**Comment by matthamil** [comment]
:wave: Hello! Thanks for the issue, and sorry you are experiencing issues. As the [issue template](https://github.com/react-navigation/react-navigation/blob/master/.github/ISSUE_TEMPLATE.md) explains, we require that you provide a runnable example that reproduces the bug on [Snack](https://snack.expo.io) or in a separate repository. Please try to minimize the extraneous code and focus on reproducing the bug.

We're closing any issues that do not have reproducible examples. Do not take this personally :). 

Please create a new issue with a reproducible example and one of the maintainers/collaborators would be glad to look at it!

**Comment by heroofchina** [comment]
ok
