### ISSUE TITLE
{ header: null } Not Working With Custom Header Component

### ISSUE THREAD

**Issue by wvicioso** [react-navigation/react-navigation#3626]
`"react-native": "0.52.0"`
    `"react-navigation": "^1.1.1"`

`header: null` is not working for a nested screen that I have when I use a custom header component. If I instead use `headerTitle` and `headerLeft` etc, Everything works as expected (Meaning I am able to hide the header using `header: null` within nested scenes)

```
const RootNavigator = StackNavigator(
   {
    Splash: {
      screen: Splash,
      navigationOptions: { header: null }
    },
    Register: {
      screen: Register,
      navigationOptions: { header: null }
    },
    Home: {
      screen: GlobalTabs,
      navigationOptions: {
        header: (<Header />), <----- CUSTOM HEADER
        gesturesEnabled: false,
      }
    },
  }
})


const GlobalTabs = TabNavigator(
   {
    Home: {
      screen: home,
   },
    Settings: {
      screen: settings,
   },
    Profile: {
      screen: LocalTabs,
      navigationOptions: {
        header: null <----NOT WORKING
     }
   },
})
```

**Comment by satya164** [comment]
It doesn't work because `header` is a valid option in `StackNavigator`'s screen's, but it doesn't apply to `TabNavigator`'s screens.

**Comment by wvicioso** [comment]
@satya164 do you know why it works fine when I don't use a custom header component? 

ie:
```
    Home: {
      screen: GlobalTabs,
      navigationOptions: {
        headerTitle: 'Text in the middle of header', <----- NOT CUSTOM HEADER
        headerRight: 'Text on the right of header'
        gesturesEnabled: false,
      }
    },
```

**Comment by satya164** [comment]
No idea. Seems strange to me. cc @ericvicenti

**Comment by brentvatne** [comment]
this is the same issue as https://github.com/react-navigation/react-navigation/issues/3628

same solution applies here -- you can use a stack for each tab screen, and set `header: null` on the parent.

alternatively, you can do something like this:



```
const GlobalTabs = TabNavigator(
   {
    Home: {
      screen: home,
   },
    Settings: {
      screen: settings,
   },
    Profile: {
      screen: LocalTabs,
   },
});

GlobalTabs.navigationOptions = ({ navigation } => {
  const { state } = navigation;
  const activeRoute = state.routes[state.index];
  if (activeRoute.routeName === 'Profile') {
    return { header: null };
  } else {
   return { };
  }
});
```

(I didn't actually run this code but something like it will work)

this would be made more clear by having the `navigationOptions` config for the `TabNavigator` refer to the navigation options that are used by the parent, and not reaching into nested routers and merging config. You can read this RFC for more info on this likely change: https://github.com/react-navigation/rfcs/pull/26

**Comment by Nazeerahmad1996** [comment]
onst AppNavigator = createStackNavigator({
  MainTabNavigator: {
    screen: MainTabNavigator,
    navigationOptions: { header: null }
  },
  Home: {
    screen: Home,
  },
  introSlider: {
    screen: introSlider
  },
  SignUp: {
    screen: SignUp
  },
  Login: {
    screen: Login,
  },
});


this worked for me.
