### ISSUE TITLE
Using react-native-scrollable-tab-view can not load the contents of a tabPage

### ISSUE THREAD

**Issue by cx5168** [react-navigation/react-navigation#3627]
react navigation-defined tabNavigator screen using react-native-scrollable-tab-view, can not load the contents of the tabPage when the application starts to display the page, the normal display if the page is refreshed.

Application start loading screen：
![111](https://user-images.githubusercontent.com/29448456/36824094-03b26562-1d44-11e8-9542-a2bc4772ce6a.png)

Update button to refresh：
![222](https://user-images.githubusercontent.com/29448456/36824132-2bfb3242-1d44-11e8-861a-4192f76dec98.png)

Ask for help！

**Comment by matthamil** [comment]
:wave: Hello! Thanks for the issue, and sorry you are experiencing issues. As the [issue template](https://github.com/react-navigation/react-navigation/blob/master/.github/ISSUE_TEMPLATE.md) explains, we require that you provide a runnable example that reproduces the bug on [Snack](https://snack.expo.io) or in a separate repository. Please try to minimize the extraneous code and focus on reproducing the bug.

We're closing any issues that do not have reproducible examples. Do not take this personally :). 

Please create a new issue with a reproducible example and one of the maintainers/collaborators would be glad to look at it!
