### ISSUE TITLE
TabNavigator screens don't override default header buttons

### ISSUE THREAD

**Issue by Lichwa** [react-navigation/react-navigation#3628]
### Current Behavior

`headerLeft` and `headerRight` defined in TabNavigator screen's navigationOptions don't override  default navigationOptions defined in TabNavigator navigationOptions.

### Expected Behavior

Every value defined in TabNavigator screen's navigationOptions should override default navigationOptions defined in TabNavigator navigationOptions.

### How to reproduce

https://snack.expo.io/@lichwa/react-navigation-navigation-options-override-bug

Tab screens display default buttons in its headers even though I override them in TabScreen component with static navigationOptions. For StackNavigator screens default buttons get overridden just fine.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.2.1
| react-native     | 0.53.0
| node             | 9.5.0
| npm or yarn      | yarn 1.3.2

**Comment by brentvatne** [comment]
it's not particularly intuitive but the config from nested routers is used as the 'base' configuration and then others are merged on top of it. you can see the code here https://github.com/react-navigation/react-navigation/blob/318788ca60fcf1b1118b8c7e634e4124f9d74988/src/routers/createConfigGetter.js#L43-L68

in this case you can just have a StackRouter for each tab and it will solve your problem.

I think deeply extracting navigationOptions from nested routers is very confusing and unnecessary, I wrote a RFC to propose removing this behavior entirely, so navigation options are only based on the navigator config and a direct child (
https://github.com/react-navigation/rfcs/pull/26).

hope that helps! i'll close this issue as any changes to navigationOptions resolution are best discussed in the RFC mentioned above
