### ISSUE TITLE
Navigation options, unable to provide styling for custom header back image

### ISSUE THREAD

**Issue by spaceye** [react-navigation/react-navigation#3629]
Hi!

There's no way to provide style for custom Header Back image, `navigationOptions.headerBackImage` — think of width, height, margins, etc. The whole idea of custom image is pretty much useless without it.
We could add `navigationOptions.headerBackImageStyle` prop and pass it down to corresponding Header back button components as, say `iconStyle` or `imageStyle`. Just like we do with `navigationOptions.headerBackTitle` and supporting `navigationOptions.headerBackTitleStyle`.

* I'm filing this issue rather than making a feature request since I believe it's a bug in this context.

Thanks!

**Comment by brentvatne** [comment]
`headerBackImageProps` is probably better in case you need to add other things.. but at this point, why even expose this when we you could just use `headerLeft` instead?

**Comment by shyaniv7** [comment]
I used this login and it works great for me

```
navigationOptions: ( { navigation } ) => ( {
    headerStyle: {
      backgroundColor: colors.white
    },
    headerLeft: <BackButton navigation={navigation} />,
  } )
```

BackButton.js wrapping our custom Icon component
```
const BackButton = ( { navigation } ) => {
  const onPress = () => navigation.goBack();

  return (
    <Icon
      color={colors.black}
      containerStyle={styles.backButton}
      name="chevron-left"
      onPress={onPress}
      size={20}
    />
  );
};
```

**Comment by spaceye** [comment]
@brentvatne, @shyaniv7 Thanks for your replies guys! However it would mean that I'll have to reimplement `HeaderBackButton` cause it's more than just an image there, correct? So in this case it's even more strange that we allow for custom image and at the same time force people to certain geometry in the icon's styling which beats the purpose, does it not? No offense just trying to better communicate my problem with it.

**Comment by brentvatne** [comment]
@SpaceK33z - yeah there's not too much to it though https://github.com/react-navigation/react-navigation/blob/master/src/views/Header/HeaderBackButton.js

**Comment by ikhilko** [comment]
@brentvatne - thank you for your response! But it really looks strange when you allow to pass custom icon/image for header back button, but it's has hardcoded style (geometry) - so `headerBackImage` prop becomes useless in this case. 
Maybe you can revisit the code of the `HeaderBackButton` component and allow for this new `imageStyle` property or custom Image component (with styles) as a property just like `headerLeft`.

**Comment by brentvatne** [comment]
that's fair. I think the change for `headerBackImage` was maybe premature and I'm not sure we want to continue down that path if it means adding yet more configuration for alternative styles. it seems preferably to have some `headerBack` property that is a react component that gets wrapped in touchable. if you want to open a PR or an RFC for this it would be welcome
