### ISSUE TITLE
Frequently call navigation.setParams, memory is getting higher and higher.

### ISSUE THREAD

**Issue by helele90** [react-navigation/react-navigation#3636]
```
import React, { Component } from 'react';
import { View, StyleSheet, AppRegistry, ScrollView } from 'react-native';
import { StackNavigator } from "react-navigation"; // 1.0.0

class Page extends Component {

  static navigationOptions = ({navigation}) => ({
    title: `Page1`
  });

  render() {
    return (
      <View style={styles.container}>
        <ScrollView style={{flex: 1}} scrollEventThrottle={16} onScroll={this.onScroll} >
          <View style={{backgroundColor: 'red', height: 2000}} />
        </ScrollView>
      </View>
    );
  }

  onScroll = () => {
    console.debug('onScroll');
    this.props.navigation.setParams({});
  }

}

const App = StackNavigator({
    Page: {
    screen: Page,
  },
});

const styles = StyleSheet.create({
  container: {
    flex: 1
  },
});

export default App;
AppRegistry.registerComponent("hello", () => App);
```

### Current Behavior

- What code are you running and what is happening?
Every time I call navigation.setParams, the memory gets higher.
Memory grows faster in my project.
- Include a screenshot if it makes sense.
Application Start
<img width="622" alt="2018-03-02 09 49 12" src="https://user-images.githubusercontent.com/4125469/36879733-28476e74-1e00-11e8-8d57-ff2d2bcb5783.png">
Call thousands navigation.setParams({})
<img width="488" alt="2018-03-02 09 54 02" src="https://user-images.githubusercontent.com/4125469/36879764-42c6e6bc-1e00-11e8-868c-c532fea04675.png">
A few minutes later, not call navigation.setParams({})
<img width="490" alt="2018-03-02 10 00 54" src="https://user-images.githubusercontent.com/4125469/36879846-a2819714-1e00-11e8-905e-c693efe58da1.png">
### Expected Behavior

- What do you expect should be happening?
- Include a screenshot if it makes sense.

### How to reproduce

use my example code

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.2.1
| react-native     | 50.1
| node             | 8
| npm or yarn      | 5.4

**Comment by JulianKingman** [comment]
I'm having a similar problem, maybe some sort of memory leak? My memory usage went as high as 15gb 😮

**Comment by brentvatne** [comment]
this was resolved in latest version. see referenced prs such as https://github.com/react-navigation/react-navigation/pull/3649

if memory usage got to 15gb from this even when the leak existed it would be very surprising. you might want to reconsider how you're using setParams, that probably would only happen if you ran setParams on every tick and left your app open for hours

**Comment by JulianKingman** [comment]
Hm, I only ran it a couple times... maybe it's not related to this issue.

**Comment by bilalyaqoob** [comment]
Any buddy knows that how to remove that err and make build successful
![event emitter](https://user-images.githubusercontent.com/31065558/64536861-43745100-d333-11e9-988a-3c26fbc4403d.PNG)
![build failed](https://user-images.githubusercontent.com/31065558/64536865-43745100-d333-11e9-89f3-02248cc9c9df.PNG)
