### ISSUE TITLE
"Cannot read property 'screen' of undefined" error when creating a SwitchNavigator

### ISSUE THREAD

**Issue by jstansbe** [react-navigation/react-navigation#3641]
I cannot create a SwitchNavigator without getting the following error, "Cannot read property screen of undefined".  This code will run without errors if I pass Navigators but I'm trying to use it as shown in the react-navigation example/docs and want a screen component to be used for AuthLoading (example here: https://snack.expo.io/@react-navigation/auth-flow). Also, wrapping with {screen: compNameHere} doesnt work either.

```

const AppNavigator = SwitchNavigator(
    {
      AuthLoading: AuthLoadingScreen,
      Home: HomeScreen,
    },
    {
      initialRouteName: 'AuthLoading',
    }
  );

  


class AuthLoadingScreen extends Component {
    render() {
        return (
            <View style={styles.container}>
                <ActivityIndicator/>
                <StatusBar barStyle="default"/>
                <Text>Auth Loading Screen</Text>
            </View>
        );
    }
}

class HomeScreen extends Component {
    render() {
        return (
            <View style={styles.container}>
                <Text>Home Screen</Text>
            </View>
        );
    }
}
```

### package.json

```
{
  "name": "nb-project",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "mobx": "^3.5.1",
    "mobx-react": "^4.4.2",
    "mobx-state-tree": "^1.3.1",
    "native-base": "^2.3.8",
    "react": "16.2.0",
    "react-native": "0.53.0",
    "react-navigation": "^1.3.0"
  },
  "devDependencies": {
    "babel-jest": "22.2.2",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-preset-react-native": "4.0.0",
    "jest": "22.3.0",
    "react-test-renderer": "16.2.0"
  },
  "jest": {
    "preset": "react-native"
  }
}

```

**Comment by brentvatne** [comment]
you need to define the `AppNavigator` after you have defined the screens. `AuthLoadingScreen` is undefined at the time that you are using it. see: https://snack.expo.io/S14Mt7D_G

we should perhaps have another error message in this case

**Comment by brentvatne** [comment]
fixed error message: https://github.com/react-navigation/react-navigation/commit/4569ad49f9224d7a980dafe3c3798fa2384aa788

did a patch release with this: https://github.com/react-navigation/react-navigation/releases/tag/v1.3.1

**Comment by jstansbe** [comment]
Appreciate the quick response and SwitchNavigator is working after moving the declaration/initialization below the comps. Thanks!

**Comment by hbmjobe** [comment]
I am having issues implementing the auth flow. Error message: undefined is not a function  (near '...(0, _reactNavigation.SwitchNavigator)..')

Below is my App.js class. Help would be appreciated

``import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import Register from './src/components/Register';
import Login from './src/components/Login';
import Dashboard from './src/components/Dashboard';
import AuthLoading from './src/components/AuthLoading';

import { StackNavigator, SwitchNavigator } from 'react-navigation';


const AppStack = StackNavigator({ Dashboard: Dashboard });
const AuthStack = StackNavigator({ Login: Login, Register: Register });

const MainNavigation = SwitchNavigator({
  AuthLoading: AuthLoading,
  Login: AppStack,
  Dashboard: AuthStack,
},
{
  initialRouteName: 'AuthLoading',
}
);

export default class App extends React.Component {
  render() {
    return (
      <View style={styles.container}>
        
        <MainNavigation />
        
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
});
``

**Comment by brentvatne** [comment]
update your version of react-navigation

**Comment by hbmjobe** [comment]
It working now, thanks!!
