### ISSUE TITLE
What is the correct Flow type for the `navigation` props of a screen?

### ISSUE THREAD

**Issue by EdwardDrapkin** [react-navigation/react-navigation#3643]
I'm trying to register a screen to a StackNavigator:

```
const SignUpRootNavigator = StackNavigator({
    Approval: { screen: Approval },
});
```

And I have my component here:

```
type Props = {
    navigation: ????
};

export class Approved extends React.Component<Props, *> {
 /* snip */
}
```

What should the flow type for Props.navigation be?  I've tried just about everything I can find in the flow-typed definition and I can't seem to figure out what it's supposed to be.

**Comment by EdwardDrapkin** [comment]
`NavigationScreenProp<any>` is the only way I've been able to make Flow pass.

Basically anything else I parameterize `NavigationScreenProp` with results in an error:

This error was caused by changing `any` to `*`:

```
Cannot call StackNavigator with object literal bound to routeConfigMap because property key is missing in
NavigationState [1] but exists in NavigationLeafRoute [2] in property navigation.state of type argument Props [3] of
property Approval.screen.```

This is starting to look like a libdef issue, no?

**Comment by EdwardDrapkin** [comment]
The libdef defines a private type:

```
declare type _NavigationInjectedProps = {
        navigation: NavigationScreenProp<NavigationState>,
    };
```

if I try to use the exact same type for my props:

```
type Props = {
    navigation: NavigationScreenProp<NavigationState>,
};
```

I get this error:

```
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ src/component/SignUp/index.js:16:25

Cannot call StackNavigator with object literal bound to routeConfigMap because property key is missing in
NavigationState [1] but exists in NavigationLeafRoute [2] in property navigation.state of type argument Props [3] of
property Approval.screen.

     src/component/SignUp/index.js
       8│ import React, { Component } from 'react';
       9│ import { StackNavigator } from 'react-navigation';
      10│
      11│ const SignUpRootNavigator = StackNavigator({
      16│     Approval: { screen: Approval },
      17│ });
      18│
      19│ export default class Apply extends Component<{}> {
      20│   static navigationOptions = {

     flow-typed/npm/react-navigation_v1.x.x.js
 [2] 243│     declare export type NavigationStateRoute = NavigationLeafRoute &

     /private/tmp/flow/flowlib_165ff2a0/react.js
 [3]  26│ declare class React$Component<Props, State = void> {

     src/component/Approval/Approved.js
 [1]  50│     navigation: NavigationScreenProp<NavigationState>,
```

**Comment by EdwardDrapkin** [comment]
I found the issue!

```
declare type _NavigationInjectedProps = {
  navigation: NavigationScreenProp<NavigationState>,
};
```

Should be:

```
declare type _NavigationInjectedProps = {
  navigation: NavigationScreenProp<NavigationStateRoute>,
};
```

Will PR flow-typed momentarily!

**Comment by brentvatne** [comment]
@EdwardDrapkin - the canonical flow definition is in this repo, which we sync to flow-typed when we have time (would be great to have some way to do this on CI or in a release script -- but we don't have bandwidth to investigate atm). so if you submit a pr to flow-typed, please submit a PR to this as well: https://github.com/react-navigation/react-navigation/blob/master/flow/react-navigation.js

**Comment by EdwardDrapkin** [comment]
@brentvatne Done here: https://github.com/react-navigation/react-navigation/pull/3645 as well as here: https://github.com/flowtype/flow-typed/pull/1909

Just a heads up though, I wasn't aware you guys maintained this Flow definition here and had already PR'd a small change over there... so I did a search and there are several PRs that have been merged there already that you may need to pull here: https://github.com/flowtype/flow-typed/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aclosed+react-navigation\

**Comment by Ashoat** [comment]
@EdwardDrapkin's PR makes sense. That said, it's unfortunate the people are submitting PRs on `flow-typed` before they get the libdef in this repo updated. I've created an [issue](https://github.com/flowtype/flow-typed/issues/1915) on `flow-typed` to see if there's a way to prevent this.

**Comment by Ashoat** [comment]
> I can make a PR that's just pulling that flow definition into this repository

@EdwardDrapkin that would be great. If it passes CI then it should be okay to merge after I review it. Otherwise, these changes will probably just be overriden next time we merge our local libdef into `flow-typed.

**Comment by tafelito** [comment]
Any plans to update the latest libdef in flow-typed? What's the current process for this, have you guys integrated it on CI? Should I create a new PR?

**Comment by brentvatne** [comment]
@tafelito - @Ashoat works on it in his spare time but I think he has been busy recently. If you'd like to help our with the flow integration of react-navigation perhaps he could help onboard you

**Comment by Ashoat** [comment]
@roballsopp submitted a `flow-typed` [PR](https://github.com/flowtype/flow-typed/pull/2140) to update the libdef, so it should be updated soon. Thanks Rob!

I think the original subject of this issue was addressed a while back, so I'm gonna go ahead and close it now.

**Comment by tafelito** [comment]
Great! Thanks @Ashoat, next time I can def help out with this if needed

**Comment by SergioGeeK7** [comment]
Awesome @semireg

**Comment by kodayashi** [comment]
@semireg - When I take that approach eslint thinks all of my other props that I've destructured are covered as a part of NavigationScreenProps. This makes me worried that we'll miss some prop validations. Are you hitting this?

```javascript
type Props = NavigationScreenProps & {
  // Some other props
}

export const myComponent = ({ navigation, // Some other props that eslint now misses }) => { ... }
```

**Comment by lgraubner** [comment]
This works for me:

```JavaScript
interface Props extends NavigationScreenProps {
  // Some other props
}
```

**Comment by mars-lan** [comment]
FWIW, one can also do it the following way to allow for exact object typing

```
type Props = {|
  ...NavigationScreenProps,
  // Some other props
|}
```

**Comment by haufsleo** [comment]
I use the following:
`export interface myProps extends NavigationStackScreenProps{}`
In my Component I use the myProps as the Props type.
