### ISSUE TITLE
`withNavigation` doesn't work with `SwitchNavigator`

### ISSUE THREAD

**Issue by migueloller** [react-navigation/react-navigation#3646]
### Current Behavior

I'm using `SwitchNavigator` but am unable to access the `navigation` prop when using `withNavigation`.

### Expected Behavior

I expected `withNavigation` to work with `SwitchNavigator`.

### How to reproduce

https://snack.expo.io/ByBA-VwOM

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |v1.3.0
| react-native     |https://github.com/expo/react-native/archive/sdk-25.0.0.tar.gz
| node             |v9.5.0
| npm or yarn      |v1.3.2

**Comment by brentvatne** [comment]
thanks! investigating

**Comment by brentvatne** [comment]
thanks @migueloller! this is fixed now, you can install v1.3.2. https://github.com/react-navigation/react-navigation/releases/tag/v1.3.2

**Comment by migueloller** [comment]
@brentvatne, thanks so much for the quick follow-up!
