### ISSUE TITLE
onTransitionEnd doesn't have access to props

### ISSUE THREAD

**Issue by TheDutchCoder** [react-navigation/react-navigation#3647]
### Current Behavior

Where `onTransitionStart` has access to props, `onTransitionEnd` does not, which prevents you from e.g. calling redux dispatches.

### Expected Behavior

`onTransitionEnd` to have access to props.

### How to reproduce

```js
  ..., {
    onTransitionStart: (props) => console.log(props), // object
    onTransitionEnd: (props) => console.log(props), // undefined
  }
```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.3.1
| react-native     | 0.53.0
| node             | 4.8.2
| npm or yarn      | 4.6.1

**Comment by brentvatne** [comment]
I'm not familiar with this part of the codebase, can you put up a more complete example that demonstrates what you're using this for? thanks

**Comment by TheDutchCoder** [comment]
It's used in e.g. the StackNavigator options:
```js
export const AppNavigator = StackNavigator({
  Main: { screen: MainScreen },
  Login: { screen: LoginScreen }
}, {
  onTransitionStart: (props) => console.log(props), // object
  onTransitionEnd: (props) => console.log(props),
})
```

**Comment by brentvatne** [comment]
which navigator should be available `onTransitionStart` and `onTransitionEnd`? the one for the screen you're transitioning to or from? or the parent stack navigator navigation object?

cc @eric

**Comment by TheDutchCoder** [comment]
I honestly don't know (or care in this case), I just need access to the dispatch function in my particular case.

I believe `onTransitionSTart` uses the parent stack?

**Comment by chochihim** [comment]
It used to have access to the transition props. But it has changed in recent commit [https://github.com/react-navigation/react-navigation/commit/0157a4c9e9d30ec60b788a5e1084785e39848393#diff-109c57d09b031f621d1c4cfcb0d28d9f](url)

I used to perform similar actions in `onTransitionEnd` as @TheDutchCoder does and encountered this issue after upgraded to latest release. I resolved by using the [subscription system](https://reactnavigation.org/docs/navigation-prop.html#addlistener-subscribe-to-updates-to-navigation-lifecycle). 

I think you can subscribe to the `didFocus` event on your screen to replace what you do in `onTransitionEnd`.

**Comment by TheDutchCoder** [comment]
Yes but that's mightily inefficient as you'd have to subscribe on each screen (and unsub on unmount as well). It's an anti-pattern where Redux is concerned as it should be handled in one place ideally.

**Comment by brentvatne** [comment]
cc @ericvicenti it looks like `onTransitionEnd` change for events broke this

**Comment by ericvicenti** [comment]
Yikes, sorry about breaking this! Looks like we already have it fixed on master, and I just pushed a fix for this on the v1 branch: https://github.com/react-navigation/react-navigation/commit/3bfb0b90d027e8ca0fd9005d5db8f63b5b9f8348

@brentvatne, can we ship the patch release when you get a chance?

**Comment by brentvatne** [comment]
shipped it @ericvicenti! @TheDutchCoder this should be live in 1.5.4
