### ISSUE TITLE
Navigation issue with nested stack drawer and tab navigator

### ISSUE THREAD

**Issue by fithaN** [react-navigation/react-navigation#3652]
Hi,
I have the navigation flow as below:
Stack Navigator->Login
                           ->Profile (Drawer Navigator)
                                           ->screen 1 (Tab Navigator)
                                                             ->Tab 1
                                                             ->Tab 2
                                           ->screen 2

I wanted to navigate from screen 2 to Tab 1. 
I tried using this.props.navigation.navigate("Tab 1") which doesn't work for me.
Is there any other easy way to navigate between the screens?

**Comment by matthamil** [comment]
:wave: Hello! As the [issue template](https://github.com/react-navigation/react-navigation/blob/master/.github/ISSUE_TEMPLATE.md) explains, issues are reserved for bug reports only.
We're closing any issues that are not bugs. Do not take this personally :). 

Please refer to the README, the documentation, or the resources listed in the [issue template](https://github.com/react-navigation/react-navigation/blob/master/.github/ISSUE_TEMPLATE.md) if you have a question about usage.
