### ISSUE TITLE
Correct way of navigation upon receiving push notification when app is in foreground or closed.

### ISSUE THREAD

**Issue by shekharskamble** [react-navigation/react-navigation#3654]
This is a general question to all who are using react navigation, following is my navigation structure

    export const createRootNavigator = (signedIn = false) => {
      return StackNavigator({
          Login: screen: Login,
          Welcome: screen: Welcome,
          Loading: screen: Loading,
          SignedIn: screen:  SignedIn,
        });
    };

    export const SignedIn = TabNavigator ({
        Home: screen: HomeNavigation, 
        FeedBack: screen: FeedBackNavigation, 
        Search: screen: SearchNavigation, 
        Me: screen: ProfileNavigation,  
    });

I am using 'react-native-fcm' to receive the notification when app is in foreground or closed. How should I structure the code to navigate to specific screens upon receiving notification? 
Shall I subscribe to onNotification in every screen and then navigate to specific screen or have it at a  centralised place? Has anyone tackled this before? sample code would be great   

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.26
| react-native     | 0.49.3
| node             |
| npm or yarn      |

**Comment by matthamil** [comment]
:wave: Hello! As the [issue template](https://github.com/react-navigation/react-navigation/blob/master/.github/ISSUE_TEMPLATE.md) explains, issues are reserved for bug reports only.

We're closing any issues that are not bugs. Do not take this personally :). 

Please refer to the README, the documentation, or the resources listed in the [issue template](https://github.com/react-navigation/react-navigation/blob/master/.github/ISSUE_TEMPLATE.md) if you have a question about usage.

**Comment by brentvatne** [comment]
there isn't really a correct way, although it would be nice for us to have some documentation around it! perhaps create an issue on the website repo? http://github.com/react-navigation/website

**Comment by shekharskamble** [comment]
@brentvatne created...
