### ISSUE TITLE
back button' onPress callback is configurable?

### ISSUE THREAD

**Issue by musicode** [react-navigation/react-navigation#3655]
I want to use the default back button image, but I hope to do something before `goBack`, so how to achieve it?

**Comment by matthamil** [comment]
:wave: Hello! As the [issue template](https://github.com/react-navigation/react-navigation/blob/master/.github/ISSUE_TEMPLATE.md) explains, issues are reserved for bug reports only.
We're closing any issues that are not bugs. Do not take this personally :). 

Please refer to the README, the documentation, or the resources listed in the [issue template](https://github.com/react-navigation/react-navigation/blob/master/.github/ISSUE_TEMPLATE.md) if you have a question about usage.

**Comment by brentvatne** [comment]
you can use addListener `this.props.navigation.addListener('willBlur', () => { /* */ });`
