### ISSUE TITLE
how to set style activetabstyle

### ISSUE THREAD

**Issue by isthaison** [react-navigation/react-navigation#3656]

**Comment by matthamil** [comment]
:wave: Hello! As the [issue template](https://github.com/react-navigation/react-navigation/blob/master/.github/ISSUE_TEMPLATE.md) explains, issues are reserved for bug reports only.
We're closing any issues that are not bugs. Do not take this personally :). 

Please refer to the README, the documentation, or the resources listed in the [issue template](https://github.com/react-navigation/react-navigation/blob/master/.github/ISSUE_TEMPLATE.md) if you have a question about usage.
