### ISSUE TITLE
Remove use of deprecated lifecycle hooks

### ISSUE THREAD

**Issue by rhysforyou** [react-navigation/react-navigation#3657]
### Current Behavior

When adding React Navigation to a new React Native project and setting up a basic StackNavigator, I see a lot of warnings from React that I'm using soon-to-be-deprecated component lifecycle hooks. Looking at these warnings more closely, I can see they call out components from React Navigation such as [Transitioner](https://github.com/react-navigation/react-navigation/blob/master/src/views/Transitioner.js#L47).

![img_0955](https://user-images.githubusercontent.com/320910/36955461-cd7ad09c-207c-11e8-8996-0664da34b87f.PNG)

### Expected Behavior

Adding React Navigation to a project should not cause any warnings to be generated.

### How to reproduce

This problem is present in any application which uses a StackNavigator.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.4.0
| react-native     | 0.54.0
| node             | 9.4.0
| npm or yarn      | yarn

**Comment by ericvicenti** [comment]
Looks like we should rename our usage to `UNSAFE_` in order to make the warnings go away. Although that may be breaking for older versions of RN..

**Comment by satya164** [comment]
I guess we can do something like:

```js
class SomeComponent extends React {
  ...
}

const componentWillReceiveProps = () => { ... };

if (React.version.startsWith('15.') {
  SomeComponent.prototype.componentWillReceiveProps = componentWillReceiveProps;
} else {
  SomeComponent.prototype.UNSAFE_componentWillReceiveProps = componentWillReceiveProps;
}
```

**Comment by Kisepro** [comment]
FYI : I get it using the StackNavigator option "path" and coming from an external link.

```
const AppNavigator = StackNavigator({
  Home: {
    screen: HomeScreen
  },
  Color: {
    screen: TestScreen,
    path: "test/:user"
  }
});
```

> adb shell am start -W -a android.intent.action.VIEW -d "mychat://mychat/test/xxx"

**Comment by sanjibnarzary** [comment]
above two methods did not work for me

**Comment by scriptum** [comment]
After upgrade of react-native to 0.55 I get same warning message (using tab navigation).

**Comment by mmerickel** [comment]
It looks like react-lifecycles-compat [1] is the recommended [2] path forward here.

[1] https://www.npmjs.com/package/react-lifecycles-compat
[2] https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html#open-source-project-maintainers

**Comment by iscriptology** [comment]
+1 react-lifecycles-compat ASAP

**Comment by sudotliu** [comment]
Hopefully the maintainers can implement the above suggested compatibility polyfill as a workaround soon.

In the meantime, here's an example workaround for others looking to suppress such warnings:
```js
console.ignoredYellowBox = [
    'Warning: componentWillMount is deprecated',
    'Warning: componentWillReceiveProps is deprecated',
    'Warning: isMounted(...) is deprecated',
];
```

Note that this is a naive string prefix match so it will suppress all such errors, so it's advisable to make sure your own project components are no longer using the deprecated lifecycle methods before applying this.

**Comment by rmkpatchaa** [comment]
@sudotliu 
Since version [52.0](https://github.com/facebook/react-native/releases/tag/v0.52.0), `console. ignoredYellowBox` is deprecated.
Use this instead : 
```
import { YellowBox } from 'react-native';
...
YellowBox.ignoreWarnings([
  'Warning: componentWillMount is deprecated',
  'Warning: componentWillReceiveProps is deprecated',
  'Warning: isMounted(...) is deprecated',
]);
```

**Comment by brentvatne** [comment]
we won't be backporting any changes to 1.x branch but on 2.x all of these lifecycle hooks are removed with the exception of in Transitioner, where we need to refactor it to be able to remove the lifecycle. however we will silence the warning on that one specifically

**Comment by vikrantnegi** [comment]
When we can have the 2.0 stable release?

**Comment by DoctaCloak** [comment]
Why don't we just create a separate branch or a new version of React Navigation that takes care of these errors and supports future updates, while making it publicly known that the current state of React Navigation will only support React Native pre-2.0?  🤔

**Comment by gpatarin** [comment]
Hello, still getting the warning for the Transitioner 😄

| software         | version
| ---------------- | -------
| react-navigation | 3.9.1
| react-native     | 0.59.5
| node             | 10.15.3
| npm or yarn      |  npm

**Comment by vkts** [comment]
I'm getting a "componentWillUpdate is deprecated" warning along with the suggestion to update DrawerLayout when using `createDrawerNavigator()`.

software | version
-- | --
react-navigation | 3.11.1
react-native | 0.60.4
node | 10.16.0
npm or yarn | npm

I tried to update the drawer component with `npm install react-navigation-drawer` which installed v2.0.0 however react-native-navigation@3.11.1 seems to supply its own dependency react-navigation-drawer@1.2.1

I'm not quite sure how to proceed.

**Comment by vkts** [comment]
I'm getting a "componentWillUpdate is deprecated" warning along with the suggestion to update DrawerLayout when using createDrawerNavigator().

software 	version
react-navigation 	3.11.1
react-native 	0.60.4
node 	10.16.0
npm or yarn 	npm

I tried to update the drawer component with `npm install react-navigation-drawer` which installed v2.0.0 however react-native-navigation@3.11.1 seems to supply its own dependency react-navigation-drawer@1.2.1

I'm not quite sure how to proceed.
