### ISSUE TITLE
Tab Is not being focused when navigating 

### ISSUE THREAD

**Issue by 0xori** [react-navigation/react-navigation#3662]
### Current Behavior
I'm trying to build a nested stack inside a tab navigator.
When you navigate to another tab the navigation works well but the indicator remains on the same tab.

![app](https://user-images.githubusercontent.com/2307798/36972947-c2d08dce-2079-11e8-97ee-aff1145fef55.gif)

I have followed the documentation [here](https://reactnavigation.org/docs/tab-based-navigation.html#a-stacknavigator-for-each-tab)
and I'm running this code 
```
import React from 'react';
import { StyleSheet, Text, View, Button } from 'react-native';

import { TabNavigator, StackNavigator } from 'react-navigation';

class DetailsScreen extends React.Component {
    render() {
        return (
            <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
                <Text>Details!</Text>
            </View>
        );
    }
}

class HomeScreen extends React.Component {
    render() {
        return (
            <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
                { /* other code from before here */ }
                <Button
                    title="Go to Details"
                    onPress={() => this.props.navigation.navigate('Details')}
                />
            </View>
        );
    }
}

class SettingsScreen extends React.Component {
    render() {
        return (
            <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
                { /* other code from before here */ }
                <Button
                    title="Go to Details"
                    onPress={() => this.props.navigation.navigate('Details')}
                />
            </View>
        );
    }
}

const HomeStack = StackNavigator({
    Home: { screen: HomeScreen },
    Details: { screen: DetailsScreen },
});

const SettingsStack = StackNavigator({
    Settings: { screen: SettingsScreen },
    Details: { screen: DetailsScreen },
});

const Navigator = TabNavigator(
    {
        Home: { screen: HomeStack },
        Settings: { screen: SettingsStack },
    },
    {
        /* Other configuration remains unchanged */
    }
);


export default class App extends React.Component {
  render() {
    return (
      <Navigator/>
    );
  }
}
```

### Expected Behavior

Tab active indicator should appear on the active tab.

### How to reproduce
just build an empty app with the code example from the [documentation ](https://reactnavigation.org/docs/tab-based-navigation.html#a-stacknavigator-for-each-tab)
or look [at this snack](https://snack.expo.io/rJgIroc_M)

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.4.0
| react-native     | 0.52.0
| node             | 9.5.0
| npm or yarn      | yarn 1.3.2

**Comment by kpsroka** [comment]
I couldn't reproduce this bug. What platform do you run this on? Are you certain that the code is exactly what you've described in the bug?

**Comment by 0xori** [comment]
I'm running on windows 10.
It happened to me with a larger codebase so in order to isolate it I created a fresh & clean react native app using `create-react-native-app` and installed only react navigation, wrote the code from my first comment on the main file (copy & pasted from my IDE to here) and it still happened.
BTW, if I add `animationEnabled: false`  and `swipeEnabled: false`, it's working as expected but then I don't see the screen content.

**Comment by brentvatne** [comment]
it appears that you have two routes with the same name, which can lead to results that you may not expect

<img width="402" alt="screen shot 2018-03-05 at 3 08 09 pm" src="https://user-images.githubusercontent.com/90494/37004961-141f0aea-2087-11e8-8b91-546c35018747.png">

cc @ericvicenti - perhaps we should warn for this

**Comment by brentvatne** [comment]
I also am unable to reproduce this. one thing that stands out to me here is that your home button is on the *right side*, whereas in the snack you shared it is on the left side. do you have RTL enabled?

I was, however, able to reproduce it if I changed the tabnavigator to this:

```
const Navigator = TabNavigator(
  {
    Settings: { screen: HomeStack },
    Home: { screen: SettingsStack },
  },
```

what happens then is that we try to navigate to the 'Settings' route because that's what the other tab is called, *but* there is a route named settings nested within the active route, so it switches to that instead and appears to jump back.

**Comment by 0xori** [comment]
@brentvatne it still happens even if I change the route name.

  ```
const Navigator = TabNavigator(
{
    Home: { screen: HomeStack },
    Whatever : { screen: SettingsStack },
  },
```

However, **I do have RTL enabled** (from device settings) and when I change it it's working fine.
**Can I make it work with RTL**?

**Comment by brentvatne** [comment]
RTL support is broken in react-native-tab-view: https://github.com/react-native-community/react-native-tab-view/issues/184

**Comment by 0xori** [comment]
I have downgraded react-navigation to 1.0.0-beta.15 and it's working fine.
The only thing is that I lost the [Navigation Event Subscriptions](https://github.com/react-navigation/react-navigation/pull/3345). So in using [this](https://github.com/react-navigation/react-navigation/issues/51#issuecomment-279885514) for now.

**Comment by brentvatne** [comment]
sounds good. the old version of react-native-tab-view supports RTL so that makes sense that it solves your problem. sorry there is no eta on RTL support in it, a PR would be welcome.
