### ISSUE TITLE
Navigating without navigation prop cannot give proper root state.

### ISSUE THREAD

**Issue by kopax** [react-navigation/react-navigation#367]
I am using this https://reactnavigation.org/docs/en/navigating-without-navigation-prop.html to access my navigation from any source, my file look as follow:

```jsx
import { createRef } from 'react';

export const navigationRef = createRef();

export function navigate(name, params) {
  return navigationRef.current?.navigate(name, params);
}

export function goBack() {
  return navigationRef.current?.goBack();
}

export function getRootState() {
  return navigationRef.current?.getRootState();
}
```

This is required because my `@navigation/drawer` is outside my stack navigation and can't use `useNavigation` hook.

Only one problem the last method is not synchronized and I want to have an active state on my item menu that is the current route.

How is that possible with react-navigation 5? Thanks!

**Comment by satya164** [comment]
Drawer content received `navigation` and `state` props. Use them instead of using a ref.

**Comment by kopax** [comment]
My drawer content does not receives `navigation` and `state` props. Is it because I am not in the tree of `<Stack.Navigator />` ?

Me: `<DrawerNavigator drawerContent={DrawerContent}><Stack.Navigator><Screens /></Stack.Navigator></DrawerNavigator>`

**Comment by satya164** [comment]
https://reactnavigation.org/docs/en/drawer-navigator.html#drawercontent

**Comment by kopax** [comment]
@satya164 thanks for linking the documentation which I read already. If I ask it's mainly because this answer is not in the documentation. Should navigator drawer wrap the stack or the stack wrap the drawer? May you please answer just this question?

If the drawer wrap the stack, then `useNavigation()` can't be called in the drawer. The navigation I am refering is the one from the stack.
