### ISSUE TITLE
Tab Navigation Laggy for Release Version with Redux Integration

### ISSUE THREAD

**Issue by michchan** [react-navigation/react-navigation#3672]
I have been using react-navigation@beta-27 (with redux integration) before updating to release version. It was stable. However, after updating to release version, the tab navigation of my app becomes a bit laggy.
An example of behavior indicating the degraded performance is as follows.

### Current Behavior

On real device, debug mode is off:
1. There is a bit delay for tab switching.
2. When I quickly tap different tabs (press different tab very quickly, like a crazy guy), and then stop tapping, screens are still changing. It looks like it cannot follow my quickly tapping, the action dispatching is slow. 
3. On Android the performance monitor shows a drops of JS fps to lower than ZERO when switching tab.

### Expected Behavior

1. At least on iOS the tab switching should be very seamless like what I experience from beta-27.
2. The screen changing should stop when I stop tapping. (working fine in beta-27)
3. The JS fps has never been lower than ZERO when switching tab.

### How to reproduce

- TabNavigator with StackNavigators as routes.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.4.0
| react-native     | 0.52
| node             | 6.9.0
| npm or yarn      | 1.3.2

**Comment by satya164** [comment]
This is a sign of unnecessary re-renders. Tab switching by tapping should be super fast unless too much is going on. By default, React Navigation should optimize this. But if this is happening in your app, that means there's something causing re-renders. A common source of this is `screenProps`. You should profile your app to see what's taking time.

**Comment by michchan** [comment]
@satya164 thanks for your suggestion.
Moreover, Any hint about the performance given the same app, between beta-27 and release version?
May I know any hint of methods to profile the app for this issue?

**Comment by brentvatne** [comment]
sorry the issues are only for bugs in react-navigation, it sounds like you need to look at re-renders in your app and that's not related to a react-navigation bug. perhaps we could improve documentation around it, if you think that's the case please open an issue on the website repo. thanks!

**Comment by michchan** [comment]
@brentvatne It doesn't matter but I just still doubt whether it is not react-navigation issue.
I just downgrade from 1.4.0 to 1.0.0-beta-27 version recently. It works fine!

**Comment by brentvatne** [comment]
if you can post a minimal example that reproduces this problem as requested by template i'm happy to take a look and help you figure out if it's react-navigation or your code

**Comment by michchan** [comment]
@brentvatne Sorry cannot quite extract an example due to the complexity of the app.
But I have profiled my app performance and optimized to limit the re-render count. It seems not my app problem but obviously the new event system of redux integration with react navigation. The tab navigation feels smooth when the app was just opened, but got to be laggy as the time using the app grows. Absolutely I won't see this on beta-27 or downward version.

I have never been frustrated about performance like this since I have used react-navigation from beta version (for several apps). This is absolutely the problem changing to the new event system or the release version. Btw, will it be related to Expo? I'm using SDK 25.

I have recorded a video comparing two versions.
- GOOD: beta-27 version, the screen stop changing just right at the time I stop tapping.
![ezgif-5-f3a098798b-good](https://user-images.githubusercontent.com/26570687/37283698-d38dbf78-2633-11e8-9172-da87c07b2827.gif)

- BAD: release version, the screen still changing (for 1-2 seconds) even I have been stop tapping.
![ezgif-5-65be0d1550-bad](https://user-images.githubusercontent.com/26570687/37283703-d78e551a-2633-11e8-938d-aec0725aa1a3.gif)

**Comment by brentvatne** [comment]
@michchan - if you give me access to the app I will look into it, otherwise not much I can do

**Comment by AdrianMrn** [comment]
@michchan Heya, did you end up fixing the issue? I get the same issue but for me it lags on beta27, and only when I debug on an iOS device (iOS emulator, Android device and emulator are fine).

**Comment by michchan** [comment]
@AdrianMrn I end up downgrading to beta27 and it works fine. I had looked into it and I guessed there are two many transition actions dispatched on release version but I have already limited the re-rendering.
