### ISSUE TITLE
Set headerMode:"screen", but behavior is "float".

### ISSUE THREAD

**Issue by watanabeyu** [react-navigation/react-navigation#3673]
### Current Behavior

I create Camera App, so I try to make tab button like instagram.
Camera App is need to fullscreen at take camera, and `headerMode:"float"` will cause layout jump.
So I set `headerMode:"screen"` at RootStack, but behavior is `headerMode:"float"`.

Please Check below snack.
https://snack.expo.io/rJd_4G2_M

[screenshot is here](https://im.ezgif.com/tmp/ezgif-1-adee895695.gif)

### Expected Behavior

I want to set `headerMode:"screen"` correctly.

### How to reproduce

Please Check below snack.
https://snack.expo.io/rJd_4G2_M

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |1.4.0
| react-native     |0.52
| node             |8.2.1
| npm      |npm

**Comment by brentvatne** [comment]
@watanabeyu - I don't understand what you expect to happen here, in the example you shared the behavior is what is expected from `headerMode: 'screen'`

**Comment by watanabeyu** [comment]
@brentvatne `headerMode:'screen'` behavior is not this?
https://snack.expo.io/BJoZRnnuG
![img_2514_1024](https://user-images.githubusercontent.com/6455904/37068892-5ccdbc1e-21f4-11e8-9927-68d1b2018144.png)
Each screen has a header attached.

In the snacks I shared [before](https://snack.expo.io/rJd_4G2_M), I set `headerMode:'screen'` at RootStack.
![img_2515_1024](https://user-images.githubusercontent.com/6455904/37068944-904b81fc-21f4-11e8-9a5f-d40ac64b42aa.png)
Render a single header that stays at the top and animates as screens are changed.

I expected a each screen has a header attached to it and the header fades in and out together with the screen transition within TakeModal.

**Comment by brentvatne** [comment]
oh I didn’t know you were referring to that transition, I didn’t see that one - I only looked at the transition when you open the camera from the tab bar

**Comment by watanabeyu** [comment]
@brentvatne Thanks!
Please let me know how to do set correctly `headerMode:'screen'` in this scene.

**Comment by brentvatne** [comment]
@watanabeyu - here you go: https://snack.expo.io/@react-navigation/instagram-tab-nav-with-react-navigation

this may be a bug, but i think it's not really a great way to structure stacknavigators so i don't think it's high priority. here's what you can do instead:

- each tab should have its own stack rather than have a header that is shared at the root stack.
- the modal stack has its own header

also i changed the + icon to navigate to the modalstack rather than to the first route in the stack

**Comment by brentvatne** [comment]
react-navigation@2.0.0 is better at handling `header: null` now, so you could also just set no header and then render a header manually as you see fit on the camera. going to close this
