### ISSUE TITLE
HeaderTitle image not centering

### ISSUE THREAD

**Issue by daddevs** [react-navigation/react-navigation#3677]
Before updating to 1.0+ of react-navigation, I was able to center the headerTitle image I use in my app using the previously proposed resolution of `alignSelf: 'center'`. However since updating, that no longer works. The image is now forced to the left on Android (can only confirm this issue on Android). Here is the total code for the header Title image and a snapshot of what it is doing (using the Pixel XL Android emulator):

`static navigationOptions = {
    headerTitle:(<Image style={{width:100, height: 100}} source={require('./link/to/image.png')}/>),
    headerTitleStyle:{textAlign: 'center',alignSelf:'center'},
 };`

![image](https://user-images.githubusercontent.com/36425381/37075499-b1497ccc-2197-11e8-8a64-5026fe14caab.png)

### Notes
I am running a StackNavigator nested inside of a TabNavigator.

### My Environment
| react-navigation | 1.4
| react-native     |  0.51
| node             | 8.9.1
| npm              | 5.6.0

**Comment by daddevs** [comment]
I found where the issue lies. The issue lies in the Header.js file under the Styles `const` in the module folder for react navigation. the specific style is `title`. For ios the default for `justifyContent` is "center" and for android it is "flex-start". Changing the android option to be "center" (or whatever the preference) in this spot fixes the issue, but it raises a bigger issue. I tried setting justifiedContent via the `headerStyle` and `headerTitleStyle` in `navigationOptions` for the StackNavigator and it did not change it. I had to manually edit in the Header.js file for it to work. Here is the code I was using to try and override the justifyContent via navigation options:

` navigationOptions: {
    headerStyle: {
      height: 60, justifyContent: 'center'
    },
    headerTitleStyle: {
      fontWeight: 'bold',
      alignSelf: 'center',
      textAlign: 'center',
      justifyContent: 'center'
    },
 }`

Am i doing something wrong or is the react-navigation module ignoring my overrides?

**Comment by yutingLei** [comment]
maybe you can try it: `headerTitle:(<Image style={{width:100, height: 100, flex: 1}} resizeMode="contain" source={require('./link/to/image.png')}/>)`

**Comment by newfylox** [comment]
I have the same issue.... I was overriding `headerTitle` with a centered view in it so that my image was centered but it's not working anymore... I'm using `react-navigation 1.5.0`

**Comment by newfylox** [comment]
Ok, I just did some tests and for my part, it's working with `v1.1.2` and breaks at `v1.2.0`

Don't know if it could help.

**Comment by dccarmo** [comment]
You're also gonna have to take `headerLeft` and `headerRight` into consideration to keep the title centered.

**Comment by shopshow** [comment]
same issue +1

**Comment by nottyjay** [comment]
Same with me

**Comment by nottyjay** [comment]
Ok. Maybe you can try this cssstyle:
`headerTitleStyle: {flex: 1, textAlign: 'center'}`

**Comment by EvanSays** [comment]
I ended up using this...
```
title:(<Image style={{height: 125, width: 200}} resizeMode="contain" source={require('../link/to/image.png')}/>),
headerTitleStyle: {flex: 1, textAlign: 'center'},
```

In the case of having a headerLeft and a centered logo, I created a false headerRight the same size as headerLeft.

```
headerRight: <View style={{height: 50, width: 50}}></View>
```

**Comment by Nitingadhiya** [comment]
**Header code :** 
  headerTitle: (
      <Image source={ImagePath.headerLogo} style={styles.logoIcon}/>
    ),
**You have to put below css :** 
  logoIcon: {
    flex:1,
    resizeMode,
  },

**Comment by miaraya** [comment]
static navigationOptions = {
    headerTitle: (
      <View style={{ flex: 1, alignItems: "center" }}>
        <Image source={logo} style={{ height: 35, width: 35 }} />
      </View>
    ),
    headerLeft: null,
    headerRight: null
  };

**Comment by anw063** [comment]
@daddevs I have the same issue that you are having, but I also have text with an image. The headerTitle only centers when I manually edit the Header.js file in node_modules for Android, and I do have a headerRight and headerLeft object. Did you end up just doing that as a fix or did you find another way?

**Comment by hasanshahoud** [comment]
@daddevs This is an optimal solution: https://stackoverflow.com/a/52343933/7439383

**Comment by omrigivoni** [comment]
Use [headerTitleContainerStyle][1]

    static navigationOptions = {
      headerTitleStyle: { justifyContent: 'center' },
    }


  [1]: https://reactnavigation.org/docs/en/stack-navigator.html#headertitlecontainerstyle

**Comment by alireza107** [comment]
try this refer to react navigation document: 
`const navigator = createStackNavigator({
  Login,
  SignUp,
  ForgotPass
}, {
  initialRouteName: "Login",
  headerLayoutPreset : 'center',
  defaultNavigationOptions: {
    headerTitle: <Image resizeMode="contain"  style={{ width: 140, height: 50 }} source={require("./assets/logo/logo1.png")} />,
    headerStyle: {
      elevation: 0
    }
  }
});`

**Comment by sauravsolanki** [comment]
This worked for me.
 {headerLayoutPreset: 'center'}
https://stackoverflow.com/questions/43326705/how-can-we-center-title-of-react-navigation-header

**Comment by vijaysinghrajput** [comment]
return {
     
        headerTitle: 'Settings',
        headerTitleStyle: {
          width: '75%',
          textAlign: 'center',
      },
       
        headerLeft: (
          <Icon style={{ paddingLeft: 10 }} onPress={() => navigation.openDrawer()} name="md-menu" size={30} />
        )


Done :

**Comment by vipinsharma22** [comment]
Try this one :
 headerTitle: <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
      <Image source={LOGO_IMAGE} />
    </View>

**Comment by samad324** [comment]
add `headerTitleAlign: 'center'` in `navigationOptions`

**Comment by adrienpoly** [comment]
For anyone searching for this @samad324 answer is correct with the new V5 API -> https://reactnavigation.org/docs/stack-navigator#headertitlealign

**Comment by nathanielongyiitak** [comment]
What worked for me:
```
headerTitle: () => (
  <Image source={logo} resizeMode="contain" style={{width: 135}} />
),
headerTitleAlign: 'center',
```

**Comment by franklincosta** [comment]
> add `headerTitleAlign: 'center'` in `navigationOptions`

This so usefull in 2021!

My code

`const configHeader = {
  headerTitle: props => <LogoTitle {...props} />,
  headerTitleAlign: 'center' ,
  headerStyle: {
    backgroundColor: '#16042A',
    flex: 1, 
    textAlign: 'center',
  },
  headerTintColor: '#fff',
  headerTitleStyle: {
    fontWeight: 'bold',
    
  },
}
export default function App() {
  return (
    <NavigationContainer>
        <Stack.Navigator screenOptions={configHeader}>
          <Stack.Screen name="Home" component={HomeScreen}></Stack.Screen>
          <Stack.Screen name="Ember" component={EmberScreen}></Stack.Screen>
        </Stack.Navigator>
    </NavigationContainer>
  );
}
`
