### ISSUE TITLE
Can we get a Project Dashboard to help you making contribution

### ISSUE THREAD

**Issue by ScreamZ** [react-navigation/react-navigation#3678]
Hey,

I just wanted to know if there is one place other than https://github.com/react-navigation/rfcs where we can see features that are waiting to be implemented. Maybe I can give you some help sometimes on some things ?

Consider making a project dashboard on github ?

Best regards

PS: Maybe I missed something else ?

**Comment by matthamil** [comment]
IIRC I believe @brentvatne is working on a rough draft for the v2.0 roadmap, which would shed some light on what features are coming down the pipeline.

**Comment by brentvatne** [comment]
here is a high level view of what we're working on for 2.0:

- [x] New createNavigator API (https://github.com/react-navigation/react-navigation/pull/3392)
- [x] Real DrawerRouter (https://github.com/react-navigation/react-navigation/pull/3618)
- [ ] 'dismiss' helper that calls goBack with the parent key (pr open) (https://github.com/react-navigation/react-navigation/pull/3669)
- [ ] `getParent` helper (not started) (https://github.com/react-navigation/rfcs/issues/27)
- [ ] Make stack actions bubble like navigate (pr open) (https://github.com/react-navigation/react-navigation/pull/3617)
- [ ] New Actions API (pr in progress) (https://github.com/react-navigation/react-navigation/pull/3619 and https://github.com/react-navigation/rfcs/pull/18)
- [ ] Less pushy Navigate behavior (rfc merged) (https://github.com/react-navigation/rfcs/pull/25)
- [ ] State persistence (not started)
- [ ] Shallow navigation options (rfc in comment period) (https://github.com/react-navigation/rfcs/pull/26)
- [ ] Minimize React 16.3 warnings by moving away from lifecycle methods where possible
- [ ] Extract tab navigator to separate library, default bottom tabs (more discussion needed around this)

Bonus

- [ ] Get react-native-web support working well again
- [ ] Make navigation playground look much nicer on android
- [ ] Docs for 'partial overlays' (eg: built-in react-native Modal component)
- [ ] Docs for navigator ref at top level

In the future I might start maintaining a public roadmap but I don't see a lot of benefit in it right now

**Comment by brentvatne** [comment]
https://github.com/react-navigation/react-navigation/issues/3685 it's here now :)
