### ISSUE TITLE
Show TabNavigator tabs underneath StackNavigator header

### ISSUE THREAD

**Issue by jskidd3** [react-navigation/react-navigation#3684]
### Current Behavior

Current code can be found in this [Expo Snack](https://snack.expo.io/HyJehn6dM).

![Actual tabs/header](https://i.imgur.com/TJqJ75u.png)

### Expected Behavior

On iPhone everything that happens is expected. On Android, I do not understand why the header is rendered below the tab bar. Material Design shows that tabs appear under the action bar/header. How can I change my code so that the tabs in my Snack render below the header as per the screenshot below.

![Expected tabs/header](https://i.stack.imgur.com/4HOqO.png)

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.4.0
| react-native     | 0.53.3
| node             | 8.9.4
| npm or yarn      | 5.6.0

**Comment by brentvatne** [comment]
hello! you just need to organize your navigators differently. the stack should be a parent of the tab, it logically makes sense given the visual hierarchy you've presented and as you can see it works as expected in code: https://snack.expo.io/@react-navigation/move-tabs-under-header

**Comment by jskidd3** [comment]
@brentvatne My hero! Thanks for this. Is it possible to keep the tab bar visible when navigating between Screen C and Schedule?

**Comment by jskidd3** [comment]
@brentvatne Should I post a separate issue for this question?

**Comment by jskidd3** [comment]
@brentvatne Facebook, Twitter, Airbnb and more. Maybe I didn't make it clear as to what I was saying. I mean if I press to go to a screen I don't want the tab bar to disappear from the view. It's very common to allow users to progress within a tab but be able to switch between other tabs and then return and continue etc.

**Comment by jskidd3** [comment]
@brentvatne D'oh! I was talking about iPhone but I can see what you mean now on Android. Is it Friday yet? 😆

**Comment by kristoff2016** [comment]
Hey @jskidd3  did you find the idea for both IOs and Andriod at the top the same ? thanks
