### ISSUE TITLE
different behavior of tabBarIcon in iOS and android 

### ISSUE THREAD

**Issue by invyctus92** [react-navigation/react-navigation#3691]
Using TabNavigation of the react navigation, in iOS the component in tabBarIcon comes out of the tab space, instead in android the component is truncated visually. Why do they have different behaviors with the same code and component <ComponentAnimated3 /> ? How can I have the same effect as ios on android?

navigationOptions: ({ navigation }) => ({
      tabBarIcon: ({ focused, tintColor }) => {
        const { routeName } = navigation.state;
        let iconName;
        if (routeName === "Mappa") {
          iconName = `ios-information-circle${focused ? "" : "-outline"}`;
        } else if (routeName === "Settings") {
          iconName = `ios-options${focused ? "" : "-outline"}`;
        } else if (routeName === "Pulsante") {
          iconName = `${CliccatoPulsante ? "iconatest" : "MUV_logo"}`;
          return <ComponentAnimated3 />;
        } else {
          iconName = `ios-options${focused ? "" : "-outline"}`;
        }
        return <Ionicons name={iconName} size={25} color={tintColor} />;
      }}

![simulator screen shot - iphone 6 - 2018-03-07 at 17 46 30](https://user-images.githubusercontent.com/13299821/37141596-cf38338a-22b5-11e8-8bc7-8fc318df120a.png)
![screenshot_1520441188](https://user-images.githubusercontent.com/13299821/37141601-db08b40a-22b5-11e8-8815-68c49352a4ca.png)

| software         | version
| ---------------- | -------
| react-navigation | 1.5.0
| react-native     | 0.53.0
| react             | 16.2.0
npm

**Comment by matthamil** [comment]
:wave: Hi! This is due to the differences between Android and iOS's rendering in React Native. Android doesn't easily overflow content into over components, while iOS handles them quite well. Closing this because this isn't an issue with React Navigation.
