### ISSUE TITLE
There is no route defined for key ... Issue with drawer?

### ISSUE THREAD

**Issue by naturom** [react-navigation/react-navigation#3696]
Hi, here's my navigators:

const StacksARoutes = {
    StackA: { screen: StackA },
    StackB: { screen: StackB },
};
const StacksA = StackNavigator(StacksARoutes);

const TabsARoutes = {
    TabA: { screen: TabA, icon: 'ios-options' },
    TabB: { screen: TabB, icon: 'ios-options' },
    TabC: { screen: StacksA, icon: 'ios-options' },
};
const TabsA = TabNavigator(TabsARoutes, {
    order: ['TabA', 'TabB', 'TabC'],
    //initialRouteName: 'TabC', // if set initial route to TabC, crash directly when switch to tab in drawer
});

const DrawerRoutes = {
    StacksA: { screen: StacksA },
    TabsA: { screen: TabsA },
    PlainA: { screen: PlainA },
};
const Drawer = DrawerNavigator(DrawerRoutes);

If I go to the TabsA in Drawer, then go to TabC (StacksA) in TabsA, then open drawer, and go to PlainA or StacksA, then go to TabsA via Drawer again, I'll get this crash:

12:55:37: Error: There is no route defined for key TabA.
Must be one of: 'StackA','StackB'

This error is located at:
    in DrawerView (at DrawerNavigator.js:88)
    in Unknown (at createNavigator.js:13)
    in Navigator (at createNavigationContainer.js:226)
    in NavigationContainer (at appNavigation.js:76)
    in AppNavigation (created by Connect(AppNavigation))
    in Connect(AppNavigation) (at app.js:11)
    in Provider (at app.js:10)
    in App (at registerRootComponent.js:35)
    in RootErrorBoundary (at registerRootComponent.js:34)
    in ExpoRootComponent (at renderApplication.js:35)
    in RCTView (at View.js:71)
    in View (at AppContainer.js:102)
    in RCTView (at View.js:71)
    in View (at AppContainer.js:122)
    in AppContainer (at renderApplication.js:34)

Did I do sth wrong? is this a bug or expected behavior? Thanks.

The same setup has no issue if I change the TabsA order to:
order: ['TabC', 'TabA', 'TabB'], // making TabC (StacksA) the first tab

### Current Behavior

It crashed with error above

### Expected Behavior

Should work fine.

### How to reproduce

- You must provide a way to reproduce the problem. If you are having an issue with your machine or build tools, the issue belongs on another repoistory as that is outside of the scope of Rect Navigation.
- Either re-create the bug on [Snack](https://snack.expo.io) or link to a GitHub repository with code that reproduces the bug.
- Explain how to run the example app and any steps that we need to take to reproduce the issue from the example app.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.4.0
| react-native     | 0.52.0
| node             | 8.9.3
| npm or yarn      | npm 4.6.1

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!

**Comment by stevemkroll** [comment]
https://snack.expo.io/BkMDbFZjG

steps to reproduce:

-slide open navigation
-select tabs in drawer menu
-select tab3 in the tab menu
-slide open navigation
-select home in drawer menu
-slide open navigation
-select tabs in drawer menu

*there is no route defined for key*

**Comment by naturom** [comment]
thanks @stevemkroll for creating this runnable example!

**Comment by stevemkroll** [comment]
just found a solution... nest the tabNavigator in a stackNavigator with the headerMode set to none.

drawerNavigator > stackNavigator > [App Section1]
drawerNavigator > stackNavigator > tabNavigator > stackNavigator > [App Section2 Tab1]
drawerNavigator > stackNavigator > tabNavigator > stackNavigator > [App Section2 Tab2]
drawerNavigator > stackNavigator > [App Section3]

I hope that makes sense.

**Comment by naturom** [comment]
Thanks @stevemkroll for the neat solution!

**Comment by Jnlbr** [comment]
Thaaaanks @stevemkroll for the solution!

**Comment by kylethielk** [comment]
Thanks as well @stevemkroll, saved me a ton of time!
