### ISSUE TITLE
Add a migration guide ex-navigation or NavigationExperimental -> React Navigation

### ISSUE THREAD

**Issue by knowbody** [react-navigation/react-navigation#37]
I think for now we could create a WIP PR and start documenting this one. There were a few request already (i.e. #31) and we want to have that once we're out of beta release anyway.

@satya164 had a chance to make a migration on one of his projects (NavigationExperimental -> React Navigation): https://github.com/satya164/PocketGear/pull/12/commits/8322cbc62a844f509ede97d821426abb762b5ebe

I think it would be great to have docs and maybe even codemods.

**Comment by grabbou** [comment]
I could demonstrate a migration steps from `Navigator` which is something really fun. I do not plan everyone to migrate, but maybe there are users that are in the process of writing their app that would benefit from such document.

**Comment by knowbody** [comment]
@grabbou that would be amazing! We should have the top level Migration header in the docs and then just add the docs for:

- ex-navigation
- NavigationExperimental
- Navigator

**Comment by grabbou** [comment]
Yes please! So who wants to take `NavigationExperimental`? I think what we can also do is just to show how to migrate from Demo to another Demo, so that people can grasp some concepts.

**Comment by JodiWarren** [comment]
@grabbou I'm migrating an in-progress app from NavigationExperimental, since it's being removed from React Native soon. I'm happy to document the process. Is there a structure of any prior guides that I can follow?

**Comment by keeleycarrigan** [comment]
@JodiWarren I would love a guide like that. I have so much custom navigation logic with NavigationExperimental in my app and am struggling to port it over now that NavigationExperimental has officially been removed in 0.44.

**Comment by spencerapplegate** [comment]
@JodiWarren have you made progress on this? If so, could you please share? I'm going through that migration now

**Comment by spencercarli** [comment]
I've got a guide on migrating from [ex-navigation to react navigation](https://hackernoon.com/migrate-from-exnavigation-to-react-navigation-1af661ec5082) and would be happy to repurpose it for the docs. Is this still something we want to pursue?

**Comment by kelset** [comment]
@spencercarli I think it would be helpful to have somewhere a guide to migrate from other navigators to this one.
Maybe we can start with a page with the link to different articles and then add them into our docs?

**Comment by spencercarli** [comment]
@kelset yeah I would like to add a migrations section with the various options to the docs

**Comment by vonovak** [comment]
I feel like react-navigation has been available (and other old navigators deprecated) for so long, that everybody has already migrated to either react-navigation or react-native-navigation. With this, I'll go ahead and close the issue because I think it simply is not relevant any more, but if somebody has a different view, we can reopen.

**Comment by sahil290791** [comment]
I am still waiting for official migration docs, I have tried out moving it to react-navigation but still get stuck at most of the places as I have used ex-navigation extensively and I am unable to find similar methods in react navigation.

> Before the 1.0 release of react-navigation, a migration path from ExNavigation will be provided, but feel free to migrate before then if you prefer.

So will the be migration be made available?

**Comment by brentvatne** [comment]
you can use this guide: https://hackernoon.com/migrate-from-exnavigation-to-react-navigation-1af661ec5082

**Comment by sahil290791** [comment]
I am writing this as I am experimenting with and migrating to **react-navigation**: [Migration guide](https://gist.github.com/sahil290791/25b0a0414d94d198fa8350f754aaafd0)
