### ISSUE TITLE
Creating a navigator don't make take an argument.May be you are trying to use React Navigation 4 Api with react navigation 5..

### ISSUE THREAD

**Issue by 2016CS112** [react-navigation/react-navigation#370]

**Comment by satya164** [comment]
What the error says

**Comment by 2016CS112** [comment]
Problem is how to upgrade react navigation 4 to 5v ..
I have tried to delete node-package & install the  "@react-navigation/drawer": "^5.0.0",
    "@react-navigation/native": "^5.0.0",
but still found this error...

**Comment by isaacmmarvin** [comment]
I'm also having a similar issue with creating bottom tabs
