### ISSUE TITLE
Adding a full-screen background image to a StackNavigator?

### ISSUE THREAD

**Issue by nextriot** [react-navigation/react-navigation#3705]
Hi.

I have an RN project using react navigation (with redux integration).
I've been trying to figure out how to wrap a stack navigator inside another view with an ImageBackground, or alternatively add one to the stack via a prop.

I found the `cardStyle` option but that doesn't allow for such customization it seems.

Logically, I can't fathom how to even wrap a navigator - given the redux structure -  with other sibling navigators, within a simple view that would allow me to add a bg image.

The issue is that 2 screens share a background image, adding them to each screen causes the image to transition along with the stack. So I want the stack to transition whilst keeping the background image static.

Hopefully that makes sense. Any help is much appreciated.

**Comment by matthamil** [comment]
:wave: The issue tracker is for bug reports. I recommend checking out some of the resources listed in the issue template or README.

**Comment by DimitrisTzimikas** [comment]
@nextriot 
````javascript
const StackTab = createStackNavigator (
    {
        Tabs: TabNavigation,
        Modal: Modal,
    },
    {
        navigationOptions:
            {
                headerTitle:(
                    <Image style={{flex: 1, height: 150, backgroundColor: '#fdc011'}}
                           resizeMode="contain"
                           source={require('./img/starter_actionbar_logo.png')}
                    />
                ),
                headerStyle: { height: 150, backgroundColor: 'transparent', opacity: 1},
            },
        cardStyle: {
            shadowColor: 'transparent',
            backgroundColor: 'transparent'
        }
    }
);

class App extends Component
{
    render()
    {
        return (
            <ImageBackground
                style={{width: '100%', height: '100%'}}
                source={require('./img/main_background.png')}
            >
                <StackTab style={{ backgroundColor: 'transparent' }} />


            </ImageBackground>
        );
    }
}

export default App;

**Comment by ultimateshoppingapp** [comment]
import * as React from 'react';
import { Button, View, Text, Image, StyleSheet, ImageBackground, TouchableOpacity, BackgroundColor } from 'react-native';
import Constants from 'expo-constants';
import { NavigationContainer } from '@react-navigation/native';
import { createStackNavigator } from '@react-navigation/stack';
import { Card } from 'react-native-paper';

const Stack = createStackNavigator();



 function MyCustomHeaderBackImage() {
  return (
    <Image 
      style={{ width: 30, height: 30,}}      
      source={require('./assets/backicon.png')}
     />
    ); }             
          


function HomeScreen({ navigation }) {
  return (
    <View style={{ flex: 1, 
                   alignItems: 'left', 
                   justifyContent: "flex-end",
                   flexDirection: "column",
                   padding: 1,
                   height: "10%",
                   width: "100%",
                   transparentCard: true,
                   backgroundColor: 'transparent',                        
                   }}>
                  
               <ImageBackground
                style={{width: '100%', height: '100%'}}
                source={require('./assets/backgroundimage.png')} >
               
               <Button title="Go to Details"
                onPress={() => navigation.navigate('Details')} />        
              
              </ImageBackground>
     </View>  );  }

function DetailsScreen({ navigation }) {
  return (
    <View style={{ flex: 1, 
                   alignItems: 'left', 
                   justifyContent: "flex-end",
                   flexDirection: "column",
                   padding: 1,
                   height: "10%",
                   width: "100%",
                   transparentCard: true,
                   backgroundColor: 'transparent',                        
                   }}>
                  
               <ImageBackground
                style={{width: '100%', height: '100%'}}
                source={require('./assets/backgroundimage.png')} >
               
      <Text>Details Screen</Text>
      <Button title="Go to Details... again"
        onPress={() => navigation.push('Details')} />
      <Button title="Go to Home" 
        onPress={() => navigation.navigate('Home')} />
      <Button title="Go back" 
        onPress={() => navigation.goBack()} />
      <Button
        title="Go back to first screen in stack"
        onPress={() => navigation.popToTop()}  />
               
               </ImageBackground>
    </View>  ); }

function LogoTitle() {
  return (
    <Image
     style={{ width: 245, height: 55 }}
      source={require('./assets/ultimateimage3new.png')}
     />
    ); }    


function App() {
  return (   
    <NavigationContainer>
      
      <Stack.Navigator initialRouteName="Home" 
      screenOptions={{headerStyle: { backgroundColor: '#000000', },
                      headerBackImage: MyCustomHeaderBackImage   ,                              
                      headerTintColor: '#ffffff', 
                      headerTitleStyle: { fontWeight: 'bold', },
                      headerTitleAlign: 'center',
                      headerTitle: props => <LogoTitle {...props} />
                      }}>
 
             
         <Stack.Screen name="Home" component={HomeScreen}
                       
                       options={{ title: 'Main Page', 
                       cardStyle: {backgroundColor: 'transparent',                                                                            shadowColor:'transparent'},
                       transparentCard: true,
                       transitionConfig: () => ({ containerStyle: {
                       backgroundColor: 'transparent', }, 
                       }),                       
                        }} 
                       />
                        
         <Stack.Screen name="Details" component={DetailsScreen}
                       options={{ title: '2nd Page', 
                       cardStyle: {backgroundColor: 'transparent',                                                                            shadowColor:'transparent'},
                       transparentCard: true,
                       transitionConfig: () => ({ containerStyle: {
                       backgroundColor: 'transparent', }, 
                       }),        
                        }} />
                       
      </Stack.Navigator>

   
   
    </NavigationContainer>  
  );
}



export default App;
