### ISSUE TITLE
Question: Multiple HOC exported screen component errors in Jest

### ISSUE THREAD

**Issue by jameskirkpatrick23** [react-navigation/react-navigation#3706]
Essentially I have a screen container that is using multiple HOC's. You can see the export here: 
```
const SplashPageContainer = compose(
  connect(mapStateToProps, null),
  withDrawer({label: 'Splash', title: 'Lynked App'}),
  withTabs()
)(SplashPage);
```
I then attempt to use the container as my splash screen here inside of a StackNavigator:
```
const sidebarRoutes = {
  Splash: {screen: SplashPageContainer},
};
export default StackNavigator(sidebarRoutes);
```
Then when i run my jest suite, I receive the following error: 
```
Test suite failed to run

    The component for route 'Splash' must be a React component. For example:

    import MyScreen from './MyScreen';
    ...
    Splash: MyScreen,
    }

    You can also use a navigator:

    import MyNavigator from './MyNavigator';
    ...
    Splash: MyNavigator,
    }
```

#### So here is the question: How do I get a composed higher order component to be recognized as a react component within my navigator. I am under the impression that this should be possible, and that Higher Order Components are supposed to be the way you create reusable code between your components.

**Comment by jameskirkpatrick23** [comment]
For additional information, when I console.log the SplashPageContainer, I get:
```
function Connect(props,context){
      _classCallCheck(this,Connect);

      var _this=_possibleConstructorReturn(this,_Component.call(this,props,context));

      _this.version=version;
      _this.state={};
      _this.renderCount=0;
      _this.store=props[storeKey]||context[storeKey];
      _this.propsMode=Boolean(props[storeKey]);
      _this.setWrappedInstance=_this.setWrappedInstance.bind(_this);

      (0,_invariant2.default)(_this.store,'Could not find "'+storeKey+'" in either the context or props of '+('"'+displayName+'". Either wrap the root component in a <Provider>, ')+('or explicitly pass "'+storeKey+'" as a prop to "'+displayName+'".'));

      _this.initSelector();
      _this.initSubscription();
      return _this;
      }
```

**Comment by matthamil** [comment]
:wave: The issue tracker is for bug reports only. I recommend checking out some of the resources listed in the issue template or README.

**Comment by jameskirkpatrick23** [comment]
Thanks for sending me to the README. There were a couple of links I looked at through there, however, none of them speak to the fact that this library does not allow you to pass a composed component with HOCs to a screen. Which feels like it should be a bug. Am I wrong in assuming that the library should support a composed component?

**Comment by brentvatne** [comment]
@jameskirkpatrick23 - can you please create a new issue with a reproducible example of this that we can run? will need a link to a github repo. sorry we don't have the time to re-create issues from small code examples but we are always happy to investigate issues that provide a full repro case

**Comment by MarcusHurney** [comment]
I am having the same issue.

**Comment by MarcusHurney** [comment]
@jameskirkpatrick23 Any luck on this yet?

**Comment by brentvatne** [comment]
@MarcusHurney - can you please create a new issue with a reproducible example of this that we can run? will need a link to a github repo. sorry we don't have the time to re-create issues from small code examples but we are always happy to investigate issues that provide a full repro case
