### ISSUE TITLE
isFocused from withNavigationFocus is a function on first render

### ISSUE THREAD

**Issue by dozoisch** [react-navigation/react-navigation#3709]
IsFocused from withNavigationFocus is a function on first render, before becoming a boolean.

Here is a log of the typeof the prop inside the render function of a component

```js
console.log('isFocused',
  typeof this.props.isFocused,
  typeof this.props.isFocused === 'function' ?
    this.props.isFocused() :
    this.props.isFocused,
);
```

![image](https://user-images.githubusercontent.com/4422516/37237356-03a7a5d0-23c7-11e8-91bd-0f6a3d51b449.png)

This seems to be the culprit:

![image](https://user-images.githubusercontent.com/4422516/37237275-3c5c6c36-23c6-11e8-8d2b-2ed50d89127a.png)

## How to reproduce
See the snack

https://snack.expo.io/SkKrJpltf

## Versions:

react-navigation 1.5.0

**Comment by brentvatne** [comment]
*facepalm*

thank you. will release a new version with this fix today

**Comment by potasium** [comment]
`console.log(this.props.navigation.isFocused());`
I tried on all of my screens but the same error. 
`ExceptionsManager.js:65 Cannot read property 'state' of undefined`

What is my mistake?

**Comment by brentvatne** [comment]
@potasium - please create a new issue with an example that reproduces this
