### ISSUE TITLE
TabBarBottom broken layout on iPad

### ISSUE THREAD

**Issue by artempyanykh** [react-navigation/react-navigation#3712]
### Current Behavior

On iPad the icons in the bottom navigation bar look broken (iPhone and Android phones look fine).

![screen shot 2018-03-10 at 16 49 00](https://user-images.githubusercontent.com/2338443/37243041-2209e5f2-2484-11e8-8d05-a70c99da2683.png)

### Expected Behavior

Icons render on iPad the way they do on phones.

### How to reproduce

Run `exp init` and choose `tabs` type of project. Then run the app in a simulator (or real iPad).

### Your Environment

| software         | version
| ---------------- | -------
| expo | 25 |
| react-navigation | 1.5.1
| react-native     | 0.52.0
| node             | 9.5.0
| npm or yarn      | yarn 1.5.1

**Comment by matthamil** [comment]
Related: https://github.com/react-navigation/react-navigation/issues/3704

**Comment by brentvatne** [comment]
thank you, will fix this today

**Comment by brentvatne** [comment]
fixed https://github.com/react-navigation/react-navigation/releases/tag/v1.5.2

**Comment by artempyanykh** [comment]
@brentvatne wow, that was fast! Thank you!

Confirm, works for me.
<img width="928" alt="screen shot 2018-03-13 at 15 33 57" src="https://user-images.githubusercontent.com/2338443/37341921-2a4ba578-26d4-11e8-9897-c57f170faa51.png">

**Comment by Dhruvpatel32** [comment]
can you eexplain process please
i'm having same isuue,please help

**Comment by brayanL** [comment]
Not working yet. Any solution? I tested on **Ipad**, **IOS version** = 14.4.2
![image](https://user-images.githubusercontent.com/8359783/116488533-308bf880-a858-11eb-8a4e-60e8e4c3b74e.png)
