### ISSUE TITLE
TabNavigation Ripple effect bug in RTL

### ISSUE THREAD

**Issue by AlirezaAkbarix** [react-navigation/react-navigation#3714]
I have 5 bottom navigation tabs and app supports both `rtl` and `ltr`. At `ltr` mode everything goes well, but not at `rtl`.

### Current Behavior
- Clicking on each tab, makes it's **mirror** tab ripple effect (if I select first **left** tab, the first **right** tab will play ripple effect)

### Expected Behavior

- It's clear.

### How to reproduce

- Simply by setting `I18nManager.forceRTL(true);`

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.5.1
| react-native     |0.50.4
| node             |8.9.4
| yarn      |1.3.2

**Comment by omidgharib** [comment]
I have the same issue

**Comment by brentvatne** [comment]
tabs don't support rtl currently, this is an upstream issue in react-native-tab-view: https://github.com/react-native-community/react-native-tab-view/issues/184

**Comment by AlirezaAkbarix** [comment]
@brentvatne Thanks for your response, so:
1- When do you predict this issue will be fixed?
2- How can I remove ripple effect (at least user can't feel it has issue until next release)

**Comment by brentvatne** [comment]
@AlirezaAkbarix - I am not working on this and I do not have an eta. You'll want to comment in the `react-native-tab-view` repo for support

**Comment by mohamadian** [comment]
please visit #3325
