### ISSUE TITLE
SwitchNavigator doesn't work with Redux integration outlined in guide

### ISSUE THREAD

**Issue by nextriot** [react-navigation/react-navigation#3717]
Hi.

I'm using the exact Redux Integration outlined in the guide found here: https://reactnavigation.org/docs/redux-integration.html

However, when I export a SwitchNavigator (with a StackNavigator as its initial route) as my default Navigator I'm met with the following error:

`undefined is not an object (evaluating 'prevState.index')`

Here is a Snack reproducing the bug: https://snack.expo.io/Hy643mQtz

![Image of stack trace](https://i.imgur.com/6FADkn8.png)

Any help is much appreciated.

**Comment by brentvatne** [comment]
please post to the redux repo as per the issue template: https://github.com/react-navigation/react-navigation-redux-helpers
