### ISSUE TITLE
Nested Navigation Issue After Redux Intergration

### ISSUE THREAD

**Issue by anilgurindapalli** [react-navigation/react-navigation#3723]
Whenever i'm using Nested Navigation i'm getting an Error as shown below..
![screenshot_2018-03-12-15-39-53](https://user-images.githubusercontent.com/30103626/37277988-54fc5c18-260c-11e8-8009-8a756d67f150.png)

How exactly we need to Implement Navigation using React Navigation with Redux. 
The Flow i need is 
**if not Logged In**
  1. Login
  2. Welcome
  3. BackUp
  4. Main Screen
        a. Two Tabs (Tab Navigator)
        b. Drawer
        c. Stack

**If Logged In** 

1. Main Screen
        a. Two Tabs (Tab Navigator)
        b. Drawer
        c. Stack

I have done it without using Redux it worked fine.. but when i'm trying to Integrate Redux it is showing the above issue..

Some time it is also showing "Cannot read property undefined of undefined"

**Routes.js**
`const LoginFlow = StackNavigator({
            Login: {
              screen: Login
            },
            Welcome: {
              screen: Welcome
            },
            Backup: {
              screen: Backup
            },
            // Main: {
            //   screen: AppDrawer
            // }
          }, {
            navigationOptions: {
              header: null
            }
    });
const AppNavigator = StackNavigator({
  BlankPage: {
    screen: BlankPage,
  },
  LoginFlow: {
    screen: LoginFlow}
}, {
    navigationOptions: {
      header: null
    }
  });
export default AppNavigator;`
-------------------------------------------------------------------------------------------------------------------

**AppNavigator.js**

`class AppWithNavigationState extends Component {
  componentDidMount() {
    BackHandler.addEventListener("hardwareBackPress", this.onBackPress);
  }

  componentWillUnmount() {
    BackHandler.removeEventListener("hardwareBackPress", this.onBackPress);
  }

  onBackPress = () => {
    const { dispatch, navigationState } = this.props;
    if (navigationState.stateForLoggedIn.index <= 1) {
      BackHandler.exitApp();
      return;
    }
    dispatch(NavigationActions.back());
    return true;
  };

  render() {
    const { navigationState, dispatch, isLoggedIn } = this.props;
    const state = isLoggedIn
      ? navigationState.stateForLoggedIn
      : navigationState.stateForLoggedOut;
    return (
      <AppNavigator navigation={addNavigationHelpers({ dispatch, state, addListener })} />
    );
  }
}

const mapStateToProps = state => {
  return {
    isLoggedIn: state.AuthReducer.isLoggedIn,
    navigationState: state.NavigationReducer
  };
};

export default connect(mapStateToProps)(AppWithNavigationState);`

-------------------------------------------------------------------------------------------------------------------
NavigationReducer.js

`const ActionForLoggedOut = AppNavigator.router.getActionForPathAndParams(
  "LoginFlow"
);

const ActionForLoggedIn = AppNavigator.router.getActionForPathAndParams(
  "BlankPage"
);

const stateForLoggedOut = AppNavigator.router.getStateForAction(
  ActionForLoggedOut
);
const stateForLoggedIn = AppNavigator.router.getStateForAction(
  ActionForLoggedIn
);

const initialState = { stateForLoggedOut, stateForLoggedIn };

const navigationReducer = (state = initialState, action) => {
  switch (action.type) {
    case "@@redux/INIT":
      return {
        ...state,
        stateForLoggedIn: AppNavigator.router.getStateForAction(
          ActionForLoggedIn,
          stateForLoggedOut
        )
      };

    case Login:
      return {
        ...state,
        stateForLoggedIn: AppNavigator.router.getStateForAction(
          ActionForLoggedIn,
          stateForLoggedOut
        )
      };

    case Logout:
      return {
        ...state,
        stateForLoggedOut: AppNavigator.router.getStateForAction(
          NavigationActions.reset({
            index: 0,
            actions: [NavigationActions.navigate({ routeName: "LoginFlow" })]
          })
        )
      };

    /* Other logic for logging out, more cleaner but unlike the above isn't telling the reader 
           that navigation is reset, that's why I chose the *reset* one for the article. I prefer
           this one, what about you?
        
        case 'LOGOUT':
            return { 
              ...state, 
              stateForLoggedIn, 
              stateForLoggedOut
            }
            break;

        */

    default:
      return {
        ...state,
        stateForLoggedIn: AppNavigator.router.getStateForAction(
          action,
          state.stateForLoggedIn
        )
      };
  }
};

export default navigationReducer;`

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |1.0.0-beta.23
| react-native     |sdk-23.0.0
| node             | v8.9.1
| npm or yarn      | npm

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
