### ISSUE TITLE
Black header when moving back from transparent header

### ISSUE THREAD

**Issue by Hellhiem** [react-navigation/react-navigation#3726]
### Current Behavior
When I'm moving back from screen that contain transparent header to the screen that has white background, header is black for a moment instead of white
Video: 
![blackheader](https://user-images.githubusercontent.com/17336747/37325143-1093a834-26a6-11e8-829a-5a4231a45d8c.gif)

My styles for transparent header: 
```
Details.navigationOptions = ( ) => {
  return {
    headerStyle: {
      justifyContent: 'center',
      backgroundColor: 'transparent',
      borderBottomWidth: 0,
      elevation: 0
    }
  }
}
```
Styles for white header: 
```
headerStyle: {
      backgroundColor: 'white,
      elevation: 0,
      borderBottomWidth: 0.5,
      borderBottomColor: 'grey,
      shadowOpacity: 0
    }
```

### Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.5.2
| react-native     | 0.54.0-rc.3

**Comment by marcinkornek** [comment]
It's unfortunately hardcoded [here](https://github.com/react-navigation/react-navigation/blob/master/src/views/StackView/StackViewTransitionConfigs.js#L28) - you can change it with [patch package](https://github.com/ds300/patch-package). You can find more info about it [here](https://blog.novanet.no/easier-react-native-upgrade-with-patch-package/)

**Comment by brentvatne** [comment]
another solution is to `headerMode: 'screen'` if you have a stack where you have a transparent header this will look better

@marcinkornek - it's not really hardcoded because you can override `transitionConfig`
