### ISSUE TITLE
didFocus doesn't get triggered at first load when using tab navigator

### ISSUE THREAD

**Issue by gameunite** [react-navigation/react-navigation#3727]
Is this the normal behavior? It works fine when I navigate to a stacknavigator.

```
  componentDidMount() {
    this.listener = this.props.navigation.addListener('didFocus', () => (
      this.refresh()
    ));
  }
```

**Comment by brentvatne** [comment]
you need to add it to constructor to get the focused event otherwise it has already mounted and focused

**Comment by gameunite** [comment]
@brentvatne I did that and it didn't work. It's working fine with StackNavigator even in componentDidMount.

**Comment by gameunite** [comment]
@brentvatne I made a repository based on the redux example here but not using create-react-native-app. It's not working as expected when I'm not using that. Did I miss anything?

https://github.com/gameunite/react-navigation-example

Just login then click the Profile screen. You'll see that the console log is not called at first run but works fine the second time.

**Comment by brentvatne** [comment]
i'd repost this to https://github.com/react-navigation/react-navigation-redux-helpers unless you can reproduce it without redux
