### ISSUE TITLE
Introducing a wrapper component for a navigator breaks integration with Redux

### ISSUE THREAD

**Issue by AnthonyLamot** [react-navigation/react-navigation#3728]
### Current Behavior

- `this.props.navigation` inside my screens is not functional

### Expected Behavior

- Things like `this.props.navigation.dispatch()` etc. should work

### How to reproduce

I have created an app structured as follows:
- App
-- Provider (for Redux store)
--- Navigator (integration with Redux, following instructions https://reactnavigation.org/docs/redux-integration.html)
---- Routes (a StackNavigator)
----- Closet (my funnily named "wrapper component" for the Drawer inside. It is connected to Redux because it uses data to dynamically generate routes for a DrawerNavigator using the technique found here: https://github.com/react-navigation/react-navigation/issues/1872)
----- ... other routes
------ OrgDrawer (the Drawer created in Closet)
------- Org 1 (x amount of screens using my Org component, depending on how much data was passed down at the Closet)
------- Org 2
------- Org ...

Now, when I take out `Closet` from this hierarchy, at the level of an `Org` I can use `this.props.navigation.dispatch()` just fine.
However, as soon as I introduce `Closet` into the hierarchy, it seems `this.props.navigation` gets messed up. It is still there, but apparently not functionally.

**So how do I make sure the `navigation` prop still gets passed down properly?**

One thing I tried was to replicate the Redux integration with React Navigation, not only at the top level of my app, but also at the level of this "wrapper" component, i.e. something like this:

```
// https://reactnavigation.org/docs/redux-integration.html
      <Closet navigation={addNavigationHelpers({
        dispatch: this.props.dispatch,
        state: this.props.nav,
        addListener,
      })} />
```

However that caused errors I simply couldn't interpret, so I doubt it is the right approach.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^1.0.3
| react-native     | https://github.com/expo/react-native/archive/sdk-24.0.0.tar.gz
| yarn      | 1.2.1

**Comment by angly-cat** [comment]
> `this.props.navigation` inside my screens is not functional

I assume that you mean that this prop is falsey (like `undefined`), and not truthy but not functional. Have you tried wrapping your child component with `withNavigation`? Here's [the link to the docs](https://reactnavigation.org/docs/with-navigation.html).

**Comment by brentvatne** [comment]
what @angly-cat said sounds right. if you still have this problem @AnthonyLamot please create a new issue along with a runnable minimal repro case on snack.expo.io or in a github repo, thanks!

**Comment by AnthonyLamot** [comment]
@angly-cat `navigation` was defined and looks alright, it just doesn't seem to be connected to Redux anymore.

Tried to wrap the `Closet` with `withNavigation` and although the code still ran, it made no difference.

I will open a new issue with a link to the repo.
