### ISSUE TITLE
Tab Navigator using redux - reactnavigation 1.5.2

### ISSUE THREAD

**Issue by charlielukman** [react-navigation/react-navigation#3731]
## The issue tracker is reserved for bug reports only.
Tab bar problem, using it with redux: Only showing page on first initial tab, navigating to another tab give blank page.

Example :
TabNavigator contain 2 tab Tab1 , Tab2
Initial page Tab1 is showing fine, navigating to Tab2 , only show blank page.

---

### Current Behavior

Tab bar problem: Only showing page on first initial tab, navigating to another tab give blank page.

### Expected Behavior

Page should be show, just like previous version

### How to reproduce

Run application from the repo https://github.com/charlielukman/TestNavigation , 
Try change tab

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.5.2 or after 1.2.1
| react-native     | 0.53.3
| redux             | 3.7.2
| react-redux     | 5.0.7

**Comment by letsgojuno** [comment]
@charlielukman It doesn't look like you are applying then middleware https://github.com/charlielukman/TestNavigation/blob/master/App.js#L12

It should be added to `applyMiddleware` in `configureStore`

**Comment by charlielukman** [comment]
Hey, thanks a lot @letsgojuno
Looks like it is working now
