### ISSUE TITLE
react native

### ISSUE THREAD

**Issue by bawhari** [react-navigation/react-navigation#3738]
Hello friends
How can I fix this?
I want to go to the new page by pressing the button
plz help me
                    <TouchableOpacity onPress={() =>
                        navigate('iot')}
                        <Image source={require('./assets/image/ic_menu.png')}
                               style={{width: 50, height: 50}}/>
                    </TouchableOpacity>

**Comment by nicholasess** [comment]
this.props.navigation.navigate("iot")

**Comment by bawhari** [comment]
@nicholasess tanks but I encountered this error
application nameApp has not been registered :(

**Comment by nicholasess** [comment]
@bawhari I need that you reproduce your in https://snack.expo.io
