### ISSUE TITLE
Redirect with navigate() not work when use TabNavigator as Component

### ISSUE THREAD

**Issue by nicholasess** [react-navigation/react-navigation#3739]
Hi everyone.
I have a problem when i use TabNavigator as Component. I`m trying redirect for route out TabNavigator, but not work. Is there solution for that?

---

### Current Behavior

Click in "Access Tab" and after, click in "Back to Index". Not redirect to Index.

### Expected Behavior

Click in "Access Tab" and after, click in "Back to Index". The Index render again.

### How to reproduce

https://snack.expo.io/HkiqutHFz

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.3.0
| react-native     | 0.45
| node             | 9.2.0
| npm or yarn      | 5.5.1

**Comment by nicholasess** [comment]
@ecoleman I use navigate, because i need to redirect for other route, index is just example

**Comment by ronal2do** [comment]
solution here, https://snack.expo.io/rJJXviHFG

**Comment by nicholasess** [comment]
@ecoleman Work with push("RouteName")

Solution: https://snack.expo.io/rkIZFiSYf

Thanks
