### ISSUE TITLE
Drawer causes header title to disappear, possibly has wrong font

### ISSUE THREAD

**Issue by mkonicek** [react-navigation/react-navigation#374]
Using the latest version (beta 5: https://www.npmjs.com/package/react-navigation)

- The header title disappears when the drawer is opened. It should stay visible and change only when the user selects a new screen.
- The font used for header items doesn't look like the standard iOS font? Not sure if it is but looked strange to me.

(This is a followup after https://github.com/react-community/react-navigation/issues/216 was fixed. It's now broken in a different way than before so creating a new issue.)

![ezgif-1-d1846ee2b0](https://cloud.githubusercontent.com/assets/346214/23092438/2524aba2-f5cb-11e6-806e-fd9a783dc737.gif)

**Comment by grabbou** [comment]
> The font used for header items doesn't look like the standard iOS font? Not sure if it is but looked strange to me.

Haven't looked at them too closely, but font used is `system`, so if anything is broken, it might be the letter spacing or font weight that's slightly different.

**Comment by grabbou** [comment]
I believe this is because DrawerNavigator uses TabNavigator behind the scenes, with two routes, DrawerOpen and DrawerClosed, the first one is null. That explains why title disappears. Not sure if that was intentional though.

**Comment by keshavkaul** [comment]
Hi, any updates on this issue? I would like to contribute to the issue fix. It would help if you could guide me a little on how to go about that. Thanks

**Comment by jfalk** [comment]
Doesn't it make more sense to have the drawer open up over the header? I know it's a slightly different issue and there are talks in other tickets for DrawerNavigator to have its own built in header. This just seems odd from a navigation standpoint though.

**Comment by sonaye** [comment]
I am not facing this issue, even though I am using both drawer and stack navigators together, drawer would be the parent navigator in my case.

**Comment by nonameolsson** [comment]
Is this still an issue? I have a Drawer navigator as my main navigator with Stack Navigators nested. I don't have this issue.

**Comment by cwagner22** [comment]
@nonameolsson I think it happens when DrawerNavigator is inside a StackNavigator

**Comment by nonameolsson** [comment]
@cwagner22 Oh. I have never tried that. Only nesting stack navigators inside a drawer.

**Comment by wmendes** [comment]
Any developments on this? Im searching a workaround but no luck yet.

**Comment by slhawkins** [comment]
I copied the drawer code in the example Expo app and made some changes to show this bug. The resulting code can be found here: https://github.com/slhawkins/drawer-in-stack-example.

I saw two possible workarounds for this. Both require the StackNavigator the Drawer is inside to have headerMode set to 'none'. From there, you can either nest each screen inside a StackNavigator with the headerMode set to something other than 'none', or you can use a custom header for everyone screen in the Drawer. In either case, I would probably create a simple component to wrap everything in, and then use a utility function that takes the DrawerNavigator route options and returns a new set of options with every screen wrapped appropriately. That would make it easy to remove the workaround once this is fixed.

**Comment by vonovak** [comment]
this happens if you nest a `DrawerNavigator` in a `StackNavigator` and actually I don't think this is a bug. You just need to hide the header for the drawerNavigator:


```js
const doNotShowHeaderOption = {
  navigationOptions: {
    header: null,
  },
};
const MyDrawer = DrawerNavigator(
  {
    // screens here
  }
);

const MainStack = initialRouteName =>
  StackNavigator(
    {
      Drawer: {
        screen: MyDrawer,
        ...doNotShowHeaderOption,
      },
```

**Comment by webdevsyd** [comment]
@nonameolsson can I see your code on how you implement the drawer navigator with nested stack navigator?

**Comment by rexlow** [comment]
+1

**Comment by kelset** [comment]
Guys I suggest you take a look at the [Intermediate Concepts](https://github.com/react-community/react-navigation#intermediate-concepts) linked in the README for some complex Drawer examples.

I'm not sure this issue should still be open :/

**Comment by hoscarcito** [comment]
Hi @kelset ! 
As you mentioned, this issue looks more like a misunderstanding of the documentation than a real issue. Also there is no code to check how it was implemented.
In the first comment @grabbou explained the reasons why the tittle is not shown and almost at the end @vonovak gave a correct example of the Drawer usage.
I believe this issue should be removed from the Roadmap too.
Thanks!

**Comment by alextorn** [comment]
@kelset i have checked examples provided by you, but still have no solution for the same issue. I have a clickable [example](https://snack.expo.io/HJC7YHDWf) with the code. Problem: when opening drawer, header disappears.

**Comment by ericvicenti** [comment]
Hey folks, sorry to hear about the troubles!

I was able to reproduce the issue from @slhawkins' repo here: https://github.com/slhawkins/drawer-in-stack-example The workaround is to add the following configuration:

```js
DrawerExample.navigationOptions = props => {
  const { index, routes } = props.navigation.state.routes[0];
  const title = routes[index].routeName;
  return { title };
};
```

Unfortunately we don't really support putting a Drawer inside a stack, so we won't be able to fix this for a while. I've created an issue here to explain this better in the docs: https://github.com/react-navigation/website/issues/10

**Comment by Vishal1419** [comment]
@ericvicenti I have tried your solution. That works. I mean it gives me the header title. But what about the background color and tintColor? I have supplied those properties to stackNavigator and I want them to remain the same in either cases. i.e. if drawer is opened or not, I want to see those properties as set by header.

**Comment by wzup** [comment]
Same error https://github.com/react-navigation/react-navigation/issues/3571

**Comment by brentvatne** [comment]
you won't have this issue on 2.0
