### ISSUE TITLE
Got an error when passing navigation to TabNavigator

### ISSUE THREAD

**Issue by adrianha** [react-navigation/react-navigation#3740]
### Current Behavior

- What code are you running and what is happening?
I'm trying to achieve navigation between nested stacks by passing rootNavigation to child using screenProps. so the children can access parent's navigation stack. But i found that when i passed screenProps to the child, navigation should be passed too in order to make the children be able to use `this.props.navigation`

### Expected Behavior

- What do you expect should be happening?
navigation should be passed to children and got no error.

### How to reproduce

Here's snack link: https://snack.expo.io/@adrianhartanto/nested-routes
You'll find the error when navigating to main ("Go to Main")

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0

**Comment by brentvatne** [comment]
https://snack.expo.io/Hywdw2SKM

pass a key to `reset` to do what you want here. also, the behavior you're trying to create here can be more easily solved with `SwitchNavigator`: https://snack.expo.io/HJRpD3SYM

also notice that i updated to react-navigation 1.5.2
