### ISSUE TITLE
Wrapping navigator in custom component breaks navigation prop

### ISSUE THREAD

**Issue by AnthonyLamot** [react-navigation/react-navigation#3744]
This is a follow up on https://github.com/react-navigation/react-navigation/issues/3728

I have now provided an example repo here: https://github.com/AnthonyLamot/navigator-wrapper-breaks-redux

### Current Behavior

- `this.props.navigation` inside my screens is not functional

### Expected Behavior

- Things like `this.props.navigation.dispatch()` etc. should work

### How to reproduce

1. Run repo https://github.com/AnthonyLamot/navigator-wrapper-breaks-redux
2. Note that buttons in the screen don't actually update Redux state
3. Note that using drawer doesn't update Redux state either
4. In `Routes.js`, pass `UserDrawer` as a screen instead of the `Closet`
5. When you run the code now, the buttons work and so do the drawer items (in `CustomDrawer` I have also tweaked `onPress` so that the Redux state is updated with the "currentOrg")

In other words - as mentioned before:
> Now, when I take out `Closet` from this hierarchy, at the level of an `Org` I can use `this.props.navigation.dispatch()` just fine.
> However, as soon as I introduce `Closet` into the hierarchy, it seems `this.props.navigation` gets messed up. It is still there, but apparently not functionally.

### Additional explanation

I have created an app structured as follows:
```
- App
-- Provider (for Redux store)
--- Navigator (integration with Redux, following instructions https://reactnavigation.org/docs/redux-integration.html)
---- Routes (a StackNavigator)
----- Closet (my funnily named "wrapper component" for the Drawer inside. It is connected to Redux because it uses data to dynamically generate routes for a DrawerNavigator using the technique found here: https://github.com/react-navigation/react-navigation/issues/1872)
----- ... other routes
------ OrgDrawer (the Drawer created in Closet)
------- Org 1 (x amount of screens using my Org component, depending on how much data was passed down at the Closet)
------- Org 2
------- Org ...
```

**So how do I make sure the `navigation` prop still gets passed down properly?**

Your help is really much appreciated - have been dealing with this problem for a while now and it is becoming a bottleneck for the project.

I will post below what I have tried so far, perhaps that saves some time.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^1.0.3
| react-native     | https://github.com/expo/react-native/archive/sdk-24.0.0.tar.gz
| yarn      | 1.2.1

**Comment by AnthonyLamot** [comment]
One thing I tried was to replicate the Redux integration with React Navigation, not only at the top level of my app, but also at the level of this "wrapper" component, i.e. something like this:

```
// https://reactnavigation.org/docs/redux-integration.html
      <Closet navigation={addNavigationHelpers({
        dispatch: this.props.dispatch,
        state: this.props.nav,
        addListener,
      })} />
```

However that caused errors I simply couldn't interpret, so I doubt it is the right approach because it is like integrating React-Navigation with Redux twice.

**Comment by AnthonyLamot** [comment]
What I also tried is to simply pass down `navigation` to the Drawer:
```
// In Closet.js
    return <Drawer navigation={this.props.navigation} />;
```

This (as I expected) produced errors:

```
ExceptionsManager.js:65 TypeError: Cannot read property 'find' of undefined

This error is located at:
    in DrawerView (at DrawerNavigator.js:88)
    in Unknown (at createNavigator.js:13)
    in Navigator (at createNavigationContainer.js:214)
    in NavigationContainer (at Closet.js:53)
    in Closet (created by Connect(Closet))
    in Connect(Closet) (at SceneView.js:17)
    in SceneView (at CardStack.js:385)
    in RCTView (at View.js:112)
    in View (at createAnimatedComponent.js:134)
    in AnimatedComponent (at Card.js:12)
    in Card (at PointerEventsContainer.js:39)
    in Container (at CardStack.js:414)
    in RCTView (at View.js:112)
    in View (at CardStack.js:348)
    in RCTView (at View.js:112)
    in View (at CardStack.js:347)
    in CardStack (at CardStackTransitioner.js:66)
    in RCTView (at View.js:112)
    in View (at Transitioner.js:142)
    in Transitioner (at CardStackTransitioner.js:19)
    in CardStackTransitioner (at StackNavigator.js:38)
    in Unknown (at createNavigator.js:13)
    in Navigator (at createNavigationContainer.js:214)
    in NavigationContainer (at Navigator.js:58)
    in Navigator (created by Connect(Navigator))
    in Connect(Navigator) (at App.js:17)
    in Provider (at App.js:16)
    in App (at registerRootComponent.js:35)
    in RootErrorBoundary (at registerRootComponent.js:34)
    in ExpoRootComponent (at renderApplication.js:35)
    in RCTView (at View.js:112)
    in View (at AppContainer.js:102)
    in RCTView (at View.js:112)
    in View (at AppContainer.js:122)
    in AppContainer (at renderApplication.js:34)
```

**Comment by AnthonyLamot** [comment]
Thirdly, I tried `withNavigation` as suggested here https://github.com/react-navigation/react-navigation/issues/3728#issuecomment-372696373:

```
// In Closet.js
export default connect(mapStateToProps)(withNavigation(Closet));
```

This did not break the code but did not make a change. 

I did not expect this to work either, because I am basically adding a function to `Closet.js`, not passing down `navigation` to the actual drawer / child screens. I don't see how I could do this without causing the error mentioned above?

**Comment by ericvicenti** [comment]
The biggest problem I see at the moment is the way that you use the drawer router. You don't wan't to re-create it on every render. 

https://github.com/AnthonyLamot/navigator-wrapper-breaks-redux/blob/master/src/screens/Closet.js#L39

Instead, you should declare it somewhere else. Also, if you render a navigator manually within any screen, you need to pass it your navigation prop, and make sure that you set:

`static router = MyDrawer.router;`

This will make sure that the drawer's navigation behavior will happen on this screen.

**Comment by angly-cat** [comment]
Do you use something beside `.dispatch()` from `navigation` here?

I have Redux integrated with `react-navigation` in my app. However, instead of dispatching actions (both regular Redux actions and NavigationActions) with `navigation.dispatch`, as said in [Overview p.3](https://reactnavigation.org/docs/redux-integration.html#overview), I actually use regular Redux's `dispatch` (from `connect`). So far, it works just fine.

**Comment by brentvatne** [comment]
the problem is basically what @ericvicenti describes, along with a couple of other things. we should add some documentation for dynamic tab/drawer routes but we don't actually explicit support this at the moment. routes should be defined statically.

**Comment by kevinsperrine** [comment]
@brentvatne I believe I'm running into a similar issue here. I'm trying to dynamically load my TabNavigator routeConfig from the redux store and it _almost_ works, but when trying to use navigationOptions on the screens the parent Stack header isn't updating. I've got an example repo ready, but then came across this issue while searching before opening a new one. Is this an example of what you mean by "explicit support"?

**Comment by AnthonyLamot** [comment]
@ericvicenti those seem very good suggestions, but I have trouble implementing / understanding them:

```
The biggest problem I see at the moment is the way that you use the drawer router. You don't want to re-create it on every render.
https://github.com/AnthonyLamot/navigator-wrapper-breaks-redux/blob/master/src/screens/Closet.js#L39
Instead, you should declare it somewhere else. 
```
I am struggling how to, because I need to pass props (in this case, `this.props.orgs.myOrgs`) into it. I have now tried several ways of first defining `const Drawer = new DrawerNavigator()` and trying to do stuff with that, but to no avail.

Would you mind giving an example?

> Also, if you render a navigator manually within any screen, you need to pass it your navigation prop, and make sure that you set:
> `static router = MyDrawer.router;`
> This will make sure that the drawer's navigation behavior will happen on this screen.
In this case, you are talking only about statically defined or also about dynamically defined routes?

Is this similar to what is described here https://reactnavigation.org/docs/routers.html?
(The example is slightly different: `static router = StackRouter(routes, config);`)

**Comment by AnthonyLamot** [comment]
@brentvatne is there a reason you are not (yet) supporting this? Seems like a feature that is relatively common. E.g. well-known apps like Gmail and Trello have dynamic routes in their navigation.

Just curious. :)

**Comment by AnthonyLamot** [comment]
@ericvicenti I went a bit further with your suggestion to use `static router = MyDrawer.router;`. However, reading https://reactnavigation.org/docs/routers.html I assumed you would mean I had to the router to the parent's router, which in this case is `Routes` (this is the parent that contains `Closet`, which should render a drawer dynamically).

So I tried:
```
...
import Routes from '../config/Routes';

...

class Closet extends Component {
   ...
  static router = Routes.router;
   ...
}
```

But then I get this error?:
```
Cannot read property 'router' of undefined
```

**Comment by ericvicenti** [comment]
In this most recent case, you're making a circular reference error, so the module is coming as undefined. You shouldn't require routes in your screen component, because the dependency goes in the opposite direction.

How about something like:
```
const Drawer = DrawerNavigator({...});

class Closet extends React.Component {
  static router = Drawer.router;
  static navigationOptions = Drawer.navigationOptions;
  render() {
    return <Drawer navigation={this.props.navigation} />;
  }
}
```

**Comment by AnthonyLamot** [comment]
@ericvicenti thanks for pointing out the circular dependency. I have taken it out.

Still, while applying the example that you provided I run into the following:
- the navigation prop is still not working (e.g. `navigation.dispatch()` doesn't work when called from within the `Org` screen through the buttons).
- in addition, inside my `Drawer` I can no longer declare `OrgStack` (a stack navigator) as a screen, but only screens directly
- it is still not clear to me how I can pass props from `Closet` to this `Drawer` that would allow me to generate screens dynamically (i.e. how do I make my `myOrgsToScreens()` function part of this again?

**Comment by brentvatne** [comment]
> is there a reason you are not (yet) supporting this? Seems like a feature that is relatively common. E.g. well-known apps like Gmail and Trello have dynamic routes in their navigation.

support for it doesn't exist yet in react-navigation core so people need to do strange things like what you're doing here to get it to work. it's not highly requested on https://react-navigation.canny.io/feature-requests so i haven't prioritized implementing it.
