### ISSUE TITLE
isFocused gives error

### ISSUE THREAD

**Issue by potasium** [react-navigation/react-navigation#3746]
- `<TouchableOpacity style={ styles.button } onPress={() => console.log(this.props.navigation.isFocused()) }>`
- `<TouchableOpacity style={ styles.button } onPress={() => console.log(this.props.navigation.isFocused) }>`

### Current Behavior
![ekran resmi 2018-03-14 11 56 47](https://user-images.githubusercontent.com/36793879/37392316-d5e93c42-277e-11e8-95eb-80d47292870f.png)

`ƒ (route) {
        var state = _this.props.navigation.state;
        var focusedRoute = state.routes[state.index];
        return route === focusedRoute;
      }`

### Expected Behavior

- true / false

| software         | version
| ---------------- | -------
| react-navigation | 1.5.2
| react-native        | 0.53.3
| node                    | 8.9.4
| npm                     | 4.6.1

**Comment by brentvatne** [comment]
v1.5.3

**Comment by EyMaddis** [comment]
@brentvatne this is not on the releases page https://github.com/react-navigation/react-navigation/releases

**Comment by RossKinsella** [comment]
@brentvatne Lets get 1.5.3 as the latest release on the releases page. Its currently set to 1.5.2, which has this issue in it. Thanks for you work on this great library
