### ISSUE TITLE
Code is executed in a closed component

### ISSUE THREAD

**Issue by animaonline** [react-navigation/react-navigation#3748]
I'm displaying a screen component by using StackNavigator, the screen queries a webservice, and it takes a couple of seconds for it to respond, if I close the screen by navigating back, the callback still executes.

I would expect it to not execute since the screen is gone.

I'm quite new to RN and I'm not sure how to handle that, maybe this is not the right place to ask?

**Comment by brentvatne** [comment]
you need to check if the component is mounted still in the callback. this isn't really related to navigation, the same thing applies to every component in react. usually in componentWillMount you would do some cleanup for event listeners, so you could do `this._isMounted = true` in constructor and `this._isMounted = false` in `componentWillMount` then check in the callback that the component is mounted

**Comment by animaonline** [comment]
Thanks!
