### ISSUE TITLE
[iOS] BottomTabBar icon visibility issue (showLabel:false) when rotate screen to landscape from v1.5.0 to v1.5.4

### ISSUE THREAD

**Issue by malonguwa** [react-navigation/react-navigation#3754]
@brentvatne This issue happens in v1.5.0 to v1.5.4, but v1.4.0 is working well.
So far Only see this issue in iOS, in my own project, i am using this structure,

main TabNavigator  
-> StackNavigator_1
-> StackNavigator_2
-> StackNavigator_3
-> StackNavigator_4

### Current Behavior
- What code are you running and what is happening?
 Using TabBar as the main navigation structure, and when rotate screen to Landscape mode. The bottom bar icon been cut off almost half the size. 

!! Please see my screenShot:

[LandScape mode - wrong tabBarIcon position]
![landscapelayoutissue](https://user-images.githubusercontent.com/2183780/37439808-d1876104-2834-11e8-9d93-2f4e2996541e.jpeg)

[Vertical mode - correct tabBarIcon position]
![vertical](https://user-images.githubusercontent.com/2183780/37440088-330dd092-2836-11e8-8332-a31399a9d052.jpeg)

### Expected Behavior
- What do you expect should be happening?
Should not have tabBar icon been cut off and it should position in the center.
!! Please refer to this screenShot which working well in v1.4.0.

[LandScape mode - correct tabBarIcon position in react-navigation **v1.4.0**]
![1 4 0](https://user-images.githubusercontent.com/2183780/37441400-2ecada2e-283c-11e8-8246-ecf69b10a674.jpeg)

### How to reproduce

Rotate screen to Landscape mode

[!!!] You may need to init a new project in your local, run in the simulator and rotate the screen to see the layout issue, cos I do not why I can not rotate the screen in Expo app after loading the code. I am very new to expo :P

Please refer my demo code [just a TabBarNvigator with two screens] for 
https://snack.expo.io/@lma/tabbarbottomlayoutissue

This is how I init my demo project.
`react-native init --version="0.50.3" TabBarBottomLayoutIssue`

FYI, I think `showLabel:false` cause the landscape layout issue, once I set `showLable: true`, after rotate the screen to landscape the layout issue is gone.

### Your Environment
My environment:
React-Native: 0.50.3
React-Navigation: 1.5.4 (lastest) also tried 1.5.0, 1.5.1,1.5.2,1.5.3, both got this layout issue.

Please let me know if you need any more info :)

**Comment by brentvatne** [comment]
thanks! published 1.5.5 with the fix :)

**Comment by brentvatne** [comment]
my bad, missed a small detail and republished 1.5.6 with a proper fix

**Comment by malonguwa** [comment]
@brentvatne thanks for the quick fix and reply..... BUT after install the 1.5.6..... there is new issue....
landscape mode is ok now.... the vertical mode has the same layout issue again...... 

please see my screenShot

![verticalissue](https://user-images.githubusercontent.com/2183780/37446990-ab53bbd8-285a-11e8-825b-7e49ee96c90c.jpeg)

**Comment by malonguwa** [comment]
@brentvatne FYI 1.5.5 works well...........
