### ISSUE TITLE
navigationOptions ignored by parent when dynamically generating TabNavigator routes from redux store

### ISSUE THREAD

**Issue by kevinsperrine** [react-navigation/react-navigation#3755]
### Current Behavior
The navigationOptions of the tab screens are ignore by the parents. Specifically in this example the headerRight icons aren't rendered by the parent StackNavigator.

### Expected Behavior
I would expect the icons to appear in the headerRight position of the parent stack navigator. This does work if the routes are passed statically without any redux connecting.

### How to reproduce
I've provided a [minimal reproduction repo](https://github.com/kevinsperrine/react-navigation-dynamic-redux-tab-test). You can simply run `yarn install` and see it working with dynamically passed routes, BUT the `navigationOptions` on the screens for those routes (`headerRight` in this case) are ignored by the parent. I also included an attempt two that passes the navigation prop, but I get a different error there. [Documented here](https://github.com/kevinsperrine/react-navigation-dynamic-redux-tab-test/blob/master/App.js#L158) I understand redux isn't supposed to be included here, but as I'm not managing the state of the navigators within redux (only attempting to pass additional properties to the navigators) that didn't seem to apply.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.5.4
| react-native     | 0.52.0
| node             | 9.5.0
| yarn      | 1.5.1

**Comment by kevinsperrine** [comment]
Not sure if there is any association to issue https://github.com/react-navigation/react-navigation/issues/3744

**Comment by rbadr** [comment]
The tabnavigator navigationOptions doesn't have a headerRight.
You can read the doc [here ](https://reactnavigation.org/docs/tab-navigator.html#navigationoptions-used-by-tabnavigator)

Also, you can not override the navigationOptions of a parent stackNavigator from a view that is inside a tabNavigator.

**Comment by kevinsperrine** [comment]
@rbadr, I'm sorry, but that's simply not true. I just updated the reproduction repo, and you can see this functionality demonstrated under the "StaticTabs" screen.

**Comment by brentvatne** [comment]
@kevinsperrine - this does not work properly in every situation and I would not depend on that behavior as it is going away very shortly: https://github.com/react-navigation/rfcs/pull/26/files. Recursively merging nested navigation options has proven to be very confusing in the past, feel free to read the RFC I linked to for more information.

**Comment by brentvatne** [comment]
I added a note to https://github.com/react-navigation/react-navigation/issues/3685 to add documentation on how to work around shallow navigation options in the rare cases where it is desirable to set navigation options on some ancestor navigator

**Comment by kevinsperrine** [comment]
@brentvatne Thanks for the note. Can you give me a tip on how to handle it now? I don't need full documentation, but I've been digging through for a couple of days and cannot figure it out.

**Comment by brentvatne** [comment]
you can have header state in somewhere like redux or react context and render a button conditionally on the settings there
