### ISSUE TITLE
StackNavigator will not render when re-entering RN app from native views in hybrid application.

### ISSUE THREAD

**Issue by jasoncleo** [react-navigation/react-navigation#3759]
We are encountering a very bizarre scenario with react-navigation in our React Native application that is only observed on Android (both in the emulator and on physical devices AND for debug builds as well as release builds), but it works fine on iOS.

### Context
We have an existing native application, and decided to implement some new screens in React Native as an experiment to see whether it would benefit our development lifecycle.

Our native app has a sidebar menu, and we added a new menu item, that when selected, takes the user into the React Native portion. They can of course navigate back out whenever they want, and later go back into that React Native portion.

### Observed problem (Only occurs in Android)
We have identified it relates to the react-navigation library, but we don't know what we're doing wrong.

When the app is first loaded, the user can select the new menu item and the React Native app loads fine, showing its initial route page and with the StackNavigator working fine.

If the user returns to the native portion (either via the back key, or by selecting a different option from the sidebarmenu) and then later opts to return to the React Native portion, then the StackNavigator component doesn't display. Other React components **outside** the StackNavigator get rendered. We know it mounts the contained components, as some of them are making API calls and we see those endpoints being queried. It just doesn't render.

Reloading within the emulator will render the app properly again until we navigate out of React Native and then return.

Oddly enough: If we turn on remote JS debugging, it suddenly all works fine.

### So our question:

Can anyone spot what we might be missing in how we are using the StackNavigator, that is keeping it from rendering properly? Again: it works fine when the JS debugger is on, making us think that it is not a logic item, but perhaps a timing condition, or some subtle config? Or should we just ditch react-navigation and go to a different navigation library?

### Versions

| software         | version
| ---------------- | -------
| react-navigation | 1.5.2
| react-native     | 0.50.4
| react             | 16.0.0

### Reproduction of the issue:

Single file app.js to be referenced by index.android.js

```
import * as React from 'react';
import { AppRegistry, Text, View } from 'react-native';
import { StackNavigator } from 'react-navigation';

AppRegistry.registerComponent('MyApp', () => MyApp);

class MyApp extends React.Component {
  render() {
    return (
      <View style={{flex:1}}\>
        <Text>'This text always shows up fine on Android, even on reentry to React application'</Text>
        <AccountNavigator />
      </View>
    );
  }
}

const AccountNavigator = StackNavigator(
  {
    FirstPage: {
      screen: TestPage,
      navigationOptions: ({ navigation }) => ({
        title: 'Test View'
      })
  },
  {
    initialRouteName: 'FirstPage'
  }
);

class TestPage extends React.Component {
  public render() {
    return (
      <View style={{flex:1, alignItems: 'center', justifyContent: 'center'}}\>
        <Text>'If you can read this, then the app is on first load. But return to the native portion and then try to come back to React Native and you will not see me.'</Text>
      </View>
    );
  }
}
```

**Comment by brentvatne** [comment]
hi there! we don't support react-navigation in a hybrid context right now. that said, it should be working fine so the problem is either in your native or js code.

the code you shared for example is not valid for several reasons which i think show that you're a bit confused about how to use react.

- `<View style={{flex:1}}\>` - the `\` here is invalid
- `public render() {` - `public` is not a thing in javascript

**Comment by jasoncleo** [comment]
Thank you for looking at it so quickly, but not sure how I feel about you closing the issue so quickly. I was manually typing the javascript in due to some weirdness about my working environment setup (we develop our mobile apps on Macs, but access to the broader internet, and hence GitHub, is via VMs so I can't copy paste).

So there is a couple of typos, and we were playing typescript for a bit, which is the reason why render()  had the public declarator. But I was using the sample in javascript, and I have ammended the JS in the original post.

I can understand that there might be concerns about our native code, but it works perfectly for basic React Native UI components and re-entry into the RN portion.

The JS side has been reduced to super simple as the sample code shows, and yet the issue still exists in Android. Loaded in iOS, the application runs as expected without this re-entry problem. And as mentioned before, attaching the JS debugger makes the issue disappear altogether in Android.

**Comment by jasoncleo** [comment]
Issue has been solved. I had the question on StackOverflow here [https://stackoverflow.com/questions/49273944/react-native-stacknavigator-disappearing-on-re-entry](https://stackoverflow.com/questions/49273944/react-native-stacknavigator-disappearing-on-re-entry) and basically it came down to the Android layout XML having a bad value for height, which was causing the StackNavigator to render with 0 pixel height.

So we could see the React code being run, we could see outlines of the controls via the Android Studio Layout Inspector, but it wasn't showing because of that layout item. I don't understand quite how it all works in Android, and I guess the JS debugger must override the container layout, which was why it worked when the remote debugger was on. 

Anyway, hope it is of use for anyone else encountering this issue.
