### ISSUE TITLE
DrawerStack to know previous route?

### ISSUE THREAD

**Issue by hkung77** [react-navigation/react-navigation#3760]
### Current Behavior

Using the goBack() function on the drawer navigation.
It is always going to the initial route of the drawer navigation even if the previous route was somewhere else.

### Expected Behavior

Can we make goBack smarter to know the previous screen it was on for DrawerStack / TabStack?

**Comment by brentvatne** [comment]
this is in progress in https://github.com/react-navigation/rfcs/pull/2
