### ISSUE TITLE
react-navigation v1.5.6, tabBarIcon position shifted down.

### ISSUE THREAD

**Issue by watanabeyu** [react-navigation/react-navigation#3762]
### Current Behavior

I upgrated `react-navigation` to v1.5.6, when tabBarIcon position shifted down.

please check below snack.
https://snack.expo.io/rJI1zldFz

![image_uploaded_from_ios_1024](https://user-images.githubusercontent.com/6455904/37465468-87e328f2-289e-11e8-9ac6-a89af32fcb58.png)

### Expected Behavior

I want to place tabBarIcon correctly.
`react-navigation:1.4.0` snack is below.
https://snack.expo.io/rJd_4G2_M

### How to reproduce

Please Check below snack.
https://snack.expo.io/rJI1zldFz

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |1.5.6
| react-native     |0.52
| node             |8.2.1
| npm      |npm

**Comment by brentvatne** [comment]
fixed in 1.5.7
