### ISSUE TITLE
react navigation back button not working with native base integration

### ISSUE THREAD

**Issue by Aashir1** [react-navigation/react-navigation#3765]
When pressing the back button of react navigation it navigates the screen around 5 to 6 seconds later this is a code of react navigation. Subsequently when I use simple react native component for login, signup from it works properly.
`import React from 'react';
import { View, Text } from 'react-native';
import { StackNavigator } from 'react-navigation';
import Signup from '../Component/signup';
import Login from '../Component/login';
import Home from '../Component/home';
const AuthStack = StackNavigator(
  {
    SignUp: {
      screen: Signup,
    },
    LogIn: {
      screen: Login,
    },
    Home:{
      screen: Home
    }
  },
  {
    initialRouteName: 'LogIn',
  }
);

export default class App extends React.Component {
  render() {
    return <AuthStack />;
  }
}`

**Comment by matthamil** [comment]
:wave: Hi! Can you reopen another issue following the issue template? We are closing any issues that don't have reproducible examples (cloneable Github repos or [Snack](http://snack.expo.io) links).
