### ISSUE TITLE
Title wrapped by a View doesn't detect params changes

### ISSUE THREAD

**Issue by ivanbtrujillo** [react-navigation/react-navigation#3768]
### Current Behavior

- What code are you running and what is happening?

I have a custom header in my component:
```javascript
static navigationOptions = ({ navigation }) => {
    const params = navigation.state.params || { title: 'Map', subtitle: '' }
    return {
      headerStyle: {
        backgroundColor: PRIMARY,
      },
      title: <CustomHeader title={params.title} subtitle={params.subtitle} />,
      headerTintColor: 'white',
      headerLeft: (
        <Icon
          name="md-menu"
          style={styles.menuIcon}
          size={30}
          onPress={() => navigation.navigate('DrawerOpen')}
        />
      ),
    }
  }
```

And also I have some functions to update the title and subtitle params:

```javascript
onSelectedItem = (item) => {
    const { setParams } = this.props.navigation
    setParams({ title: item.name, subtitle: item.address })
  }

onUnselectedItem = () => {
    const { setParams } = this.props.navigation
    setParams({ title: 'Map', subtitle: '' })
  }
```

The problem is with the component that is rendered for the title. It detect changes if I leave it like this:

```javascript
const CustomHeader = ({ title = 'Map', subtitle = 'A subtitle' }) => (
  <Text>
    {title} - {subtitle}
  </Text>
)
```

But if I wrap it into a <View></View> component, it doesn't detect any changes from params.

```javascript
const CustomHeader = ({ title = 'Map', subtitle = 'A subtitle' }) => (
  <View>
      <Text>
          {title} - {subtitle}
      </Text>
  <View>
)
```

### Expected Behavior

- What do you expect should be happening?

It should detect changes in params despite of is wrapped by a <View></View>. This allow to create a two line header with title a subtitle by adding a bit of style.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  1.1.2
| react-native     | 0.54.2
| node             | 9.8.0
| npm or yarn      | yarn (1.5.1)

**Comment by matthamil** [comment]
Can you create a reproducible example using [Snack](http://snack.expo.io)?

**Comment by ivanbtrujillo** [comment]
Yep. Today I''ll create it when I arrive at home.

**Comment by ivanbtrujillo** [comment]
@matthamil here is the link to the project. 
https://snack.expo.io/@ivanbtrujillo/rn-issue-3738

In expo it gives me an error in the logs that I didn't saw in local development:

<img width="324" alt="captura de pantalla 2018-03-18 a las 17 12 17" src="https://user-images.githubusercontent.com/6088653/37568617-8c69bdc2-2acf-11e8-8512-88987c046fb1.png">

If you change the CustomHeader component from this:
```
const CustomHeader = ({ title = 'Default title', subtitle = 'Default subtitle' }) => (
  <View style={{ display: 'flex', flexDirection:'column'}}>
    <Text style={{flex:1}}>
      {title}
    </Text>
    <Text style={{flex:1}}>
    {subtitle}
    </Text>
  </View>
)
```

To this:

 ```
const CustomHeader = ({ title = 'Default title', subtitle = 'Default subtitle' }) => (
    <Text>
      {title} - {subtitle}
    </Text>
)
```

It works as expected.

Seems that react-navigation doesn't support a View as a title component, just a text. My question is: If I can't add a View as a title, how can I add a title / subtitle header?

**Comment by ivanbtrujillo** [comment]
Any news?

**Comment by brentvatne** [comment]
use the `headerTitle` property https://reactnavigation.org/docs/stack-navigator.html#headertitle

**Comment by ivanbtrujillo** [comment]
Thx, didn't saw in the docs before.
