### ISSUE TITLE
When i use yarn add react-navigation, has a error

### ISSUE THREAD

**Issue by apkJava** [react-navigation/react-navigation#3774]
## The issue tracker is reserved for bug reports only.
c:\developer\github\cuju>yarn add react-navigation
yarn add v1.5.1
[1/4] Resolving packages...
error An unexpected error occurred: "Couldn't find the binary git".
info If you think this is a bug, please open a bug report with the information p
rovided in "c:\\developer\\github\\cuju\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this comm
and.
---

### My Environment

| software         | version
| ---------------- | -------
| react-navigation |
| react-native     |    "0.54.2"
| node             |   9.8.0
| npm or yarn      |  yarn

**Comment by apkJava** [comment]
I try to use
yarn add react-navigation@1.5.7
it's ok...
what happend?
c:\developer\github\cuju>yarn add react-navigation
yarn add v1.5.1
[1/4] Resolving packages...
error An unexpected error occurred: "Couldn't find the binary git".
info If you think this is a bug, please open a bug report with the information
rovided in "c:\\developer\\github\\cuju\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this com
and.

c:\developer\github\cuju>yarn add react-navigation@1.5.7
yarn add v1.5.1
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.1.3: The platform "win32" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check.
Excluding it from installation.
[3/4] Linking dependencies...
warning "react-native > metro > @babel/plugin-check-constants@7.0.0-beta.38" ha
 incorrect peer dependency "@babel/core@7.0.0-beta.38".
warning " > babel-jest@23.0.0-alpha.0" has unmet peer dependency "babel-core@^6
0.0 || ^7.0.0-0".
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 10 new dependencies.
info Direct dependencies
└─ react-navigation@1.5.7
info All dependencies
├─ clamp@1.0.1
├─ hoist-non-react-statics@2.5.0
├─ path-to-regexp@1.7.0
├─ react-lifecycles-compat@1.0.2
├─ react-native-dismiss-keyboard@1.0.0
├─ react-native-drawer-layout-polyfill@1.3.2
├─ react-native-drawer-layout@1.3.2
├─ react-native-safe-area-view@0.7.0
├─ react-native-tab-view@0.0.74
└─ react-navigation@1.5.7
Done in 5.42s.

**Comment by brentvatne** [comment]
`yarn add react-navigation@1.5.1` if you want to install that specific version
