### ISSUE TITLE
nested DrawerNavigator children, headers not showing / empty

### ISSUE THREAD

**Issue by JulianKingman** [react-navigation/react-navigation#3777]
### Current Behavior

I'm not sure if this is exactly what's happening, but it appears that children of DrawerNavigators that are nested in other navigators can't have their own headers. Here's an example: https://snack.expo.io/@buishi/nested-navigator-headers

The example is structured like so:
-- RootNavigator (stack)
--- AppNavigator (stack)
---- DrawerNavigator (drawer)
----- App (view)

Although headers are enabled for DrawerNavigator, the header doesn't display, nor does the title. Somehow I was able to solve this in a local project, but I can't explain why...

### Expected Behavior

I would expect the drawer and child headers to display, along with their titles.

### How to reproduce

https://snack.expo.io/@buishi/nested-navigator-headers

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.5.8
| react-native     | expo 25
| node             | 8.6.0
| npm or yarn      | 5.5.1

**Comment by vonovak** [comment]
Hi! Thanks for providing a repro. Does this work for you? (I just changed the structure a little).

**Comment by JulianKingman** [comment]
@vonovak it does, but does that imply that I need a `StackNavigator` for each individual screen? It's not an ideal workaround...

Also, related issues: 
https://github.com/react-navigation/react-navigation/issues/374
https://github.com/react-navigation/react-navigation.github.io/issues/10

**Comment by JulianKingman** [comment]
I made a "fixer function" for my views using your method, which appears to work pretty well:
```javascript
const compontStackFix = Component =>
  StackNavigator(
    { [Component.displayName]: Component },
    { navigationOptions: {...options}},
  );

const Drawer = DrawerNavigator({
  App: componentStackFixer(App),
  ...screens,
  {header: null},
);
```

Other related issues:
https://github.com/react-navigation/react-navigation/issues/131
https://github.com/react-navigation/react-navigation/issues/165

**Comment by vonovak** [comment]
@JulianKingman it's not a workaround actually; if you want screens in a drawer, and you want those screens to have a header, you need them to be in a stack. Many app likely end up having more than one screen in stack in the end, so the stack makes a little more sense, but here it still does, since it gives us the header.
