### ISSUE TITLE
Designing an all-in-one events management mobile app with react-navigation

### ISSUE THREAD

**Issue by chen4393** [react-navigation/react-navigation#3783]
I want to build an all-in-one events management app, just like [AttendeeHub](https://play.google.com/store/apps/details?id=com.crowdcompass.app4815162342) or [Whova](https://play.google.com/store/apps/details?id=com.whova.event). 
When the app launching for the first time, it will fetch data of multiple events from server. 
There will be at most 10 events in the server. So I want to dynamically create at most 10 new StackNavigators. There will be a RootDrawer that can let users select which event they want to look at. There will also be some inner Drawer for each event. For example, Drawer1 is for Event1, Drawer2 is for Event2. Each Drawer will be different from each other.

```
const Event1Navigator = StackNavigator(
  {
    Drawer1: { screen: Drawer1 },
    RootDrawer: { screen: RootDrawer }
  },
  {
    initialRouteName: 'Drawer1'
    headerMode: 'none'
  }
);

const Event2Navigator = StackNavigator(
  {
    Drawer2: { screen: Drawer2 },
    RootDrawer: { screen: RootDrawer }
  },
  {
    initialRouteName: 'Drawer2'
    headerMode: 'none'
  }
);

...

const Event10Navigator = StackNavigator(
  {
    Drawer10: { screen: Drawer10 },
    RootDrawer: { screen: RootDrawer }
  },
  {
    initialRouteName: 'Drawer10'
    headerMode: 'none'
  }
);
```

Does anyone know how to dynamically create a StackNavigator for each event? 

Could anyone give me some general ideas about how to design such an event app that can let user look up multiple events? Thanks

**Comment by ericvicenti** [comment]
Maybe you can try something like the following:

```
class AppWithDynamicTabs extends Component {

    state = { TabNavigator: null };

    async componentDidMount() { // I'm in such suspense
        const tabsConfig = await getTabsConfigWithNetwork();
        this.setState({
            TabNavigator: createTabNavigator(tabsConfig);
        });
    }

    render() {
        const {TabNavigator} = this.state;
        return TabNavigator && <TabNavigator />;
    }
}
```

We currently do not support dynamic re-configuration of navigators, but it is something that we are considering for the future. If you'd like us to prioritize this use case, can you post a feature request on canny, and see if the community upvotes it? https://react-navigation.canny.io/feature-requests

Also you can consider having a Stack with a single type of route, which uses route params to select the correct screen within one main screen component.
