### ISSUE TITLE
SwitchNavigator in Redux example throwing error cannot read property index of undefined

### ISSUE THREAD

**Issue by Shubham-Sinha** [react-navigation/react-navigation#3788]
I was trying to implement Redux example with ``SwitchNavigator`` . 
Routes are : 
```jsx
const AppNavigator = SwitchNavigator({
    AuthLoading,
    Auth: AuthRoutes,
    App: AppRoutes,
  },
  {
    initialRouteName: 'AuthLoading',
  });

const AuthRoutes = StackNavigator({
    Login,
  },
  {
    headerMode: 'none',
  });
```
I get error in the line 
```jsx
const initialState = AppNavigator.router.getStateForAction(AppNavigator.router.getActionForPathAndParams('Login'))
```
as ``cannot read property index of undefined``

I'm unable to even second guess what it's expecting and getting as undefined as `AppNavigator.router.getActionForPathAndParams('Login')` gives 
```js
{
  "type": "Navigation/NAVIGATE",
  "routeName": "Login"
}
```

**Comment by jeffreyffs** [comment]
Same issue here. Just trying to navigate to another top level StackNavigator within the SwitchNavigator is giving me the same error.

`nextState = router.getStateForAction(NavigationActions.navigate({ routeName: 'Login' }))` which I would expect to switch from wherever I am in the 'App' StackNavigator to the 'Login' Navigator.

**Comment by brentvatne** [comment]
https://github.com/react-navigation/react-navigation/pull/3856 landed so this is resolved now, thanks @seanmorton
