### ISSUE TITLE
While Navigating without the navigation prop replace does not work as i don't have the key

### ISSUE THREAD

**Issue by dhirendrarathod2000** [react-navigation/react-navigation#3789]
First of all Thanks for this library it is really good.
Also I tried to get answer for this on discord but seems like no one knows so putting it up here.

 Current Behaviour

-On Root of my application I have a SwitchNavigator that has all the login routes with a route that has DrawerNavigation that has stack navigator in it.

On root of my application I store reference to the root navigation (https://reactnavigation.org/docs/navigating-without-navigation-prop.html)
```
<SwitchNavigator ref={navigatorRef => {setTopLevelNavigator(navigatorRef);}} />
```

### Expected Behaviour

- When I use that reference on the routing logic navigate and back works fine, but according to code replace needs a key to work. (`StackRouter.js` Replace Logic)
- With This logic i don't get any key in the navigator reference. or I have no way to get the key for the screen.

### How to reproduce
https://snack.expo.io/r1Aypv6Ff

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.5.6
| react-native     | 0.53.0
| node             |  9.5.0
| yarn      |  1.3.2

**Comment by ericvicenti** [comment]
To use the StackNavigator replace behavior, you need to pass the key from your screen's `props.navigation.state.key` into `NavigationActions.replace({key})`.

If that seems inconvenient, the easiest way to do that is to call `this.props.navigation.replace("MyRoute")` from within the screen component

**Comment by dhirendrarathod2000** [comment]
@ericvicenti Thanks for the quick reply

Initially did the same
but due to our existing deep-linking stuff I was not able to get navigator access in the root of the application.

I have to look into that.

Thanks
D
