### ISSUE TITLE
Is that possible to share a common screen between two stackNavigators?

### ISSUE THREAD

**Issue by yanhao-li** [react-navigation/react-navigation#3790]
### Current Behavior

Currently say my navigator looks like below
- TabNavigator
   - StackNavigator 1
      - Screen 1     <==   initial route for this stack navigator
      - Screen 2 (UserProfileScreen) 
   - StackNavigator 2
      - Screen 3
      - Screen 4

In my use case, Screen 2 user profile page need to be an common share screen which should be accessible from every other screens, and it need to have the functionality of going back to previous screen.

Suppose I was at Screen 3, when I use this.props.navigation.navigate(UserProfileScreen), It works but it will load the initial route of stackNavigator 1 first, which is Screen 1, then go to the Screen2. This break the go back function of the stack header, which means when I navigated to Screen2, then I click go back button, it will go the screen 1.

### Expected Behavior

is that possible to navigate from Screen 1, 3 and 4 to Screen 2 and still could use the go back button on screen2 to go back to screen1, 3 and 4 without customizing the go back function?

Any helps or replies will be welcomed, Thank you!

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^1.5.8
| react-native     |  0.50.3
| node             | v8.9.1
| npm or yarn      |

**Comment by ericvicenti** [comment]
Yes this should work:

```
const App = TabNavigator({
  TabA: StackNavigator({
    Screen1,
    Screen2,
  }),
  TabB: StackNavigator({
    Screen3,
    Screen4,
    Screen2,
  }),
})
```

This way, you can navigate to screen 2 within either tab A or tab B

**Comment by geekwill** [comment]
I don't think the solution is very good. Is there any other way?

**Comment by carmelocatalfamo** [comment]
Hi, I have similar behavior.
I have an app that can be used by user without signup/login.

```javascript
import ScannerScreen from './screens/Scanner'
import PayScreen from './screens/Pay'

const UserNavigator = createStackNavigator({
  Summary: {...},
  Scanner: { screen: ScannerScreen }, // Shared
  Pay: { screen: PayScreen }, // Shared
  Stats: {...}
})

const MainNavigator = createStackNavigator({
  Home: {...} // Initial screen if user is not logged in
  User: { screen: UserNavigator } // Initial screen if user is logged in
  Scanner: { screen: ScannerScreen }, // Shared
  Pay: { screen: PayScreen }, // Shared
  Signup: {...},
  Login: {...}
})
```

How can i share screen between stack?
What if I use `...navigation.navigate('Scanner')` in the MainNavigator or in UserNavigator?

I think that this solution (@ericvicenti) is not the best solution.

**Comment by Slapbox** [comment]
If I do this, I get separate instances of the screen each time I use it. Is there some way I can navigate to the same instance of a screen across navigators, or twice within the same navigator (passed with params to change the screen's function.)

**Comment by tauanbinato** [comment]
Im having the exact same problem. 
I have a the same stack navigator for some tabs.. but they are not actually the same. i need a way to share the exact same screen between tabs.. otherwise will cause some re-render issues for me

**Comment by tauanbinato** [comment]
@Slapbox have you found a solution?

**Comment by raajnadar** [comment]
@tauanbinato use version 5 of react navigation it supports dynamic routing.

**Comment by tauanbinato** [comment]
@raajnadar Thanks for the reply, i have the following situation:

TabNavigator
     Tab 1 - Point to stacknavigator A
     Tab 2 - Point to stacknavigator A
 
But they are not the same, each one is causing a render when a change tabs on the app. I need the tabs pointing into the same screen, like a common shared screen. 
Im gonna search about dynamic routing to understand better what you are saying.

**Comment by nandantal** [comment]
> @raajnadar Thanks for the reply, i have the following situation:
> 
> TabNavigator
> Tab 1 - Point to stacknavigator A
> Tab 2 - Point to stacknavigator A
> 
> But they are not the same, each one is causing a render when a change tabs on the app. I need the tabs pointing into the same screen, like a common shared screen.
> Im gonna search about dynamic routing to understand better what you are saying.
> 
> Im using v5

did you find the solution on v5 ?

**Comment by matt-dalton** [comment]
Has anyone got any good solutions to this? I was hoping it might be something that was solved when we moved to v5.

**Comment by spyr0s** [comment]
I just started using navigation 5. 
I v4 I had a way to achieve this.
In v5 I am trying something like this. (Not sure if it will work 100%, I'm just trying this)

```
const getCommon = (Stack) => {
    return [
        <Stack.Screen key="screen1" name='Screen1' component={Screen1} />,
        <Stack.Screen key="screen2" name='Screen2' component={Screen2} />,
       ... other screens common in multiple tabs
    ];
};

const Tab1 = () => {
    const Stack = createStackNavigator();
     const common = getCommon(Stack);
 
       return (
            <Stack.Navigator>
                <Stack.Screen name='Tab1' component={Tab1} />
                {common}
            </Stack.Navigator>
        );
}

const Tab2 = () => {
    const Stack = createStackNavigator();
     const common = getCommon(Stack);
 
       return (
            <Stack.Navigator>
                <Stack.Screen name='Tab2' component={Tab2} />
                {common}
            </Stack.Navigator>
        );
}
`

**Comment by matt-dalton** [comment]
Thanks @spyr0s, nice solution. 
This works well from a functional perspective, but I'm struggling to make it work with Typescript. If I have two stacks `HomeStack` and `OtherStack`:

```
const getCommon = (Stack: typeof HomeStack | typeof OtherStack) => (
        <Stack.Screen key="screen1" name='Screen1' component={Screen1} />
)
```

throws a TS error `JSX element type 'Stack.Screen' does not have any construct or call signatures.`

Weirdly works fine if I type the argument as either `typeof HomeStack` or `typeof OtherStack`. Anyone got any experience of making this work?

**Comment by mar-bi** [comment]
@matt-dalton, i had the same issue with Typescript. 
I have 3 stacks where I need to share screens with.
Probably `any` type is not the best solution, but it works for me this way.

```
function createCommon(Stack: any) {
  return (
    <>
      <Stack.Screen name="Screen1" component={Screen1} />
      <Stack.Screen name="Screen2" component={Screen2} />
   </>
  )
}

**Comment by josmithua** [comment]
@mar-bi how do you type the shared screen's `navigation` and `route` props?

**Comment by swizes** [comment]
This solution looks solid. I will try tomorrow

It is really weird, if the docs do not cover this. If an app has a lot of common screens, it doesn't make sense to repeat those lines alll over the place and if you want to change some options etc.. you have to do it on every parent stack.

I don't think this is an uncommon requirement for most of the apps. 


> I just started using navigation 5.
> I v4 I had a way to achieve this.
> In v5 I am trying something like this. (Not sure if it will work 100%, I'm just trying this)
> 
> ```
> const getCommon = (Stack) => {
>     return [
>         <Stack.Screen key="screen1" name='Screen1' component={Screen1} />,
>         <Stack.Screen key="screen2" name='Screen2' component={Screen2} />,
>        ... other screens common in multiple tabs
>     ];
> };
> 
> const Tab1 = () => {
>     const Stack = createStackNavigator();
>      const common = getCommon(Stack);
>  
>        return (
>             <Stack.Navigator>
>                 <Stack.Screen name='Tab1' component={Tab1} />
>                 {common}
>             </Stack.Navigator>
>         );
> }
> 
> const Tab2 = () => {
>     const Stack = createStackNavigator();
>      const common = getCommon(Stack);
>  
>        return (
>             <Stack.Navigator>
>                 <Stack.Screen name='Tab2' component={Tab2} />
>                 {common}
>             </Stack.Navigator>
>         );
> }
> `
> ```

**Comment by swizes** [comment]
I finally found a decent solution.

We need to use NestedNavigators



```
<Stack.Navigator>
            <Stack.Screen name="Map"  component={MapScreen} />
            <Stack.Screen name={'Common'} options={{headerShown:true}}  component={CommonScreenWithHeader}/>
</Stack.Navigator>
```

The example above shows how to do it.

This stack navigator **"Map"** is one of the tab's stack. I have added anoter Stack called as **"Common"** which has lots of common screens like Profile, Chat, Notifications etc...

To navigate one of the nested stack screen.
```
navigation.navigate('Common', {
  screen: 'Profile',
  params: {
     id: 5,
  },
});
```

Basically we try to navigate to a Stack which is called **Common** and try to open the screen named as **Profile**

**Comment by matt-dalton** [comment]
Nice...looks cleaner. Although I understood there was a performance overhead associated with nesting stacks? Not sure whether this would be a drawback in practice.

**Comment by swizes** [comment]
Well if there is a  performance issue about that, then react-navigation v5 has a major problem (if there is no other decent solution). Because if I add the below line to all TabNavigator stacks. The screen **won't** be opened in the  **current** tab, if I have navigated between tabs.

Let's say i have 3 tabs called Home -Calendar - - Messages

Initial tab is Home

I open the app, navigate to Calendar tab, then go back to Home tab and try to navigate on Profile screen. The screen will be opened in Calendar tab, and it is opened in the background, the app does not navigate to Calendar tab (eventough that is not what we want to achieve). We basically want to be able to open "n" amount of different screens in all tabs, without navigating to different tab.

<Stack.Screen name={'Profile'} component{Profile}/>

**Comment by victorbruce** [comment]
The only way around this currently is to repeat the screens in each StackNavigator.

For example, let's say we have a user screen that we want to access from two stack navigators (HomeStackNavigator and SettingsStackNavigator). What you will need to do is to define the user profile screen both under the HomeStackNavigator and SettingsStackNavigator

`const HomeStackNavigator = () => {
  <Stack.Navigator>
  <Stack.Screen name="UserProfile" component={UserProfile}/>
</Stack.Navigator>
}`

`const SettingsStackNavigator = () => {
  <Stack.Navigator>
  <Stack.Screen name="UserProfile" component={UserProfile}/>
</Stack.Navigator>
}`

**Comment by joseygordev** [comment]
@spyr0s  thanks man, that really helped me... 

I am using the V5, and I was duplicating Stacks, but this approach was very helpful to avoid this.

I don't know if there is some problem with this approach, I believe not, but if anyone finds something, please let us know about it.

**Comment by cinemanja** [comment]
> The only way around this currently is to repeat the screens in each StackNavigator.
> 
> For example, let's say we have a user screen that we want to access from two stack navigators (HomeStackNavigator and SettingsStackNavigator). What you will need to do is to define the user profile screen both under the HomeStackNavigator and SettingsStackNavigator
> 
> ```
> const HomeStackNavigator = () => {
>   <Stack.Navigator>
>   <Stack.Screen name="UserProfile" component={UserProfile}/>
> </Stack.Navigator>
> }
> 
> const SettingsStackNavigator = () => {
>   <Stack.Navigator>
>   <Stack.Screen name="UserProfile" component={UserProfile}/>
> </Stack.Navigator>
> }
> ```

@victorbruce Did you use typescript in the UserProfile screen? How we could add Typescript types to the common screens now with two stack navigators?

**Comment by victorbruce** [comment]
> > The only way around this currently is to repeat the screens in each StackNavigator.
> > For example, let's say we have a user screen that we want to access from two stack navigators (HomeStackNavigator and SettingsStackNavigator). What you will need to do is to define the user profile screen both under the HomeStackNavigator and SettingsStackNavigator
> > ```
> > const HomeStackNavigator = () => {
> >   <Stack.Navigator>
> >   <Stack.Screen name="UserProfile" component={UserProfile}/>
> > </Stack.Navigator>
> > }
> > 
> > const SettingsStackNavigator = () => {
> >   <Stack.Navigator>
> >   <Stack.Screen name="UserProfile" component={UserProfile}/>
> > </Stack.Navigator>
> > }
> > ```
> 
> @victorbruce Did you use typescript in the UserProfile screen? How we could add Typescript types to the common screens now with two stack navigators?

@cinimanja I used plain javascript instead.

**Comment by okevino47** [comment]
Hi, i m re-opening that topic for one reason:
I am working on an application react native and i am facing the same problem actually.

I have a bottomTabBar navigator with 5 tabs, each contain a stack navigator. The problem is i have common screen between these stack (like payment screen, profile screen etc...)
I created a "commonStack" like you said before in the topic.
And i m facing the issue when i press back button and i go back in common screen that i opened far earlier in my navigation workflow where the expected behavior is to go back to the previous screen (which is part of an other stack sometime).

So, to avoid this my question is, is it still a good way to create a "commonScreen" stack and use reset or some tricks. like this or is it better to put common screen multiple time in the different tab stacks and even if it will create a new instance of the same screen, to retrieve correct information with redux/context or even hooks which now is a possibility ?

It looks like the previous answer were given without the mention of theses possibilities. That s why i m asking it.

Thanks for answers

**Comment by jstheoriginal** [comment]
> Thanks @spyr0s, nice solution.
> This works well from a functional perspective, but I'm struggling to make it work with Typescript. If I have two stacks `HomeStack` and `OtherStack`:
> 
> ```
> const getCommon = (Stack: typeof HomeStack | typeof OtherStack) => (
>         <Stack.Screen key="screen1" name='Screen1' component={Screen1} />
> )
> ```
> 
> throws a TS error `JSX element type 'Stack.Screen' does not have any construct or call signatures.`
> 
> Weirdly works fine if I type the argument as either `typeof HomeStack` or `typeof OtherStack`. Anyone got any experience of making this work?

The issue is probably because there's a cyclical reference. those two stacks use this function, so the definition of the function can't use those two stacks.

I just did this instead and it works in TypeScript. Note the use of `React.Fragment` (`<>` is an alias) rather than an array, which works fine as well.

```
export const sharedStackScreens = (Stack: ReturnType<typeof createStackNavigator>) => (
  <>
    <Stack.Screen name="Something" component={SomethingComponent} />
    // others
  </>
)
```

**Comment by andrewdang17** [comment]
I still can't figure this out. If I create `sharedStackScreens` and pass it to all my `Tab.Screen` components then  it results in ` WARN  Found screens with the same name nested inside one another`

**Comment by TowhidKashem** [comment]
> 

hey swizes, your solution is working for me but do you know if there's much performance overhead to instantiating a new stack navigator per tab?

**Comment by TowhidKashem** [comment]
> I will paste here final version of my solution
> 
> @andrewdang17 It may help your problem
> 
> Create a file called SharedScreens.js
> 
> Put all your shared screens in that array below
> 
> ```
> export const getSharedScreens = Stack => {
> return [
>     <Stack.Screen key="SharedScreen1" name={'SharedScreen1'} component={SharedScreen1} />,
>     <Stack.Screen key="SharedScreen2" name={'SharedScreen2'} component={SharedScreen2} />,
> }
> ```
> 
> Creating the second "Main Stack1" -> MainStack1.js
> 
> ```
> //Stack Object for our Stack1
> const Stack = createStackNavigator();
> 
> export const Stack1 = props => {
> 
>   //We pass the Stack Object to the function
>   const sharedScreens = getSharedScreens(Stack);
> 
>   return (
>     <Stack.Navigator>
>       <Stack.Screen key="Stack1Screen1" name={'Stack1Screen1'} component={Stack1Screen1} />,
>       <Stack.Screen key="Stack1Screen2" name={'Stack1Screen2'} component={Stack1Screen2} />,
>       {sharedScreens}
>     </Stack.Navigator>
>   );
> };
> ```
> 
> Creating the second "Main Stack2" -> MainStack2.js
> 
> ```
> //Stack Object for our Stack2
> const Stack = createStackNavigator();
> 
> export const Stack2 = props => {
> 
>   //We pass the Stack Object to the function
>   const sharedScreens = getSharedScreens(Stack);
> 
>   return (
>     <Stack.Navigator>
>       <Stack.Screen key="Stack2Screen1" name={'Stack2Screen1'} component={Stack2Screen1} />,
>       <Stack.Screen key="Stack2Screen2" name={'Stack2Screen2'} component={Stack2Screen2} />,
>       {sharedScreens}
>     </Stack.Navigator>
>   );
> };
> ```
> 
> Key point here is that the MainStack1 or MainStack2 should not have the same screens as in the SharedScreens array. If you need to have, have it with different name and stack otherwise react navigation will complain

hey swizes, your solution is working for me but do you know if there's much performance overhead to instantiating a new stack navigator per tab?

**Comment by swizes** [comment]
> > I will paste here final version of my solution
> > @andrewdang17 It may help your problem
> > Create a file called SharedScreens.js
> > Put all your shared screens in that array below
> > ```
> > export const getSharedScreens = Stack => {
> > return [
> >     <Stack.Screen key="SharedScreen1" name={'SharedScreen1'} component={SharedScreen1} />,
> >     <Stack.Screen key="SharedScreen2" name={'SharedScreen2'} component={SharedScreen2} />,
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Creating the second "Main Stack1" -> MainStack1.js
> > ```
> > //Stack Object for our Stack1
> > const Stack = createStackNavigator();
> > 
> > export const Stack1 = props => {
> > 
> >   //We pass the Stack Object to the function
> >   const sharedScreens = getSharedScreens(Stack);
> > 
> >   return (
> >     <Stack.Navigator>
> >       <Stack.Screen key="Stack1Screen1" name={'Stack1Screen1'} component={Stack1Screen1} />,
> >       <Stack.Screen key="Stack1Screen2" name={'Stack1Screen2'} component={Stack1Screen2} />,
> >       {sharedScreens}
> >     </Stack.Navigator>
> >   );
> > };
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Creating the second "Main Stack2" -> MainStack2.js
> > ```
> > //Stack Object for our Stack2
> > const Stack = createStackNavigator();
> > 
> > export const Stack2 = props => {
> > 
> >   //We pass the Stack Object to the function
> >   const sharedScreens = getSharedScreens(Stack);
> > 
> >   return (
> >     <Stack.Navigator>
> >       <Stack.Screen key="Stack2Screen1" name={'Stack2Screen1'} component={Stack2Screen1} />,
> >       <Stack.Screen key="Stack2Screen2" name={'Stack2Screen2'} component={Stack2Screen2} />,
> >       {sharedScreens}
> >     </Stack.Navigator>
> >   );
> > };
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Key point here is that the MainStack1 or MainStack2 should not have the same screens as in the SharedScreens array. If you need to have, have it with different name and stack otherwise react navigation will complain
> 
> hey swizes, your solution is working for me but do you know if there's much performance overhead to instantiating a new stack navigator per tab?

TBH I did not check, if this causes any performance issues but so far I have used this approach in production and didn't notice any performance overhead. But in my opinion adding manually or via a function should not make a difference.

**Comment by NhutMinhIT** [comment]
![image](https://user-images.githubusercontent.com/90835621/221353368-2ec8e8e2-7bc5-4ccb-b993-b2df2cf5ac3f.png)

**Comment by NhutMinhIT** [comment]
![image](https://user-images.githubusercontent.com/90835621/221353375-b90fe4ea-8f99-4150-a0e0-4ccbbda5a9c2.png)

**Comment by ser-emejia** [comment]
> > The only way around this currently is to repeat the screens in each StackNavigator.
> > For example, let's say we have a user screen that we want to access from two stack navigators (HomeStackNavigator and SettingsStackNavigator). What you will need to do is to define the user profile screen both under the HomeStackNavigator and SettingsStackNavigator
> > ```
> > const HomeStackNavigator = () => {
> >   <Stack.Navigator>
> >   <Stack.Screen name="UserProfile" component={UserProfile}/>
> > </Stack.Navigator>
> > }
> > 
> > const SettingsStackNavigator = () => {
> >   <Stack.Navigator>
> >   <Stack.Screen name="UserProfile" component={UserProfile}/>
> > </Stack.Navigator>
> > }
> > ```
> 
> @victorbruce Did you use typescript in the UserProfile screen? How we could add Typescript types to the common screens now with two stack navigators?

I'm facing the same, did you find a workaround?

**Comment by THE-BLUE-FRIEND** [comment]
We can either wrap a Stack Navigator outside the Tab Navigator and place the common screens in this global Stack Navigator or we can include those screens in the Tab Navigator and hide the Tab Bar Item by applying the right styles. An appropriate implementation for the latter would be:

```
return (
    <Tab.Navigator {...props} >
        <Tab.Screen {...screenOneProps} />
        <Tab.Screen {...screenTwoProps} />
        <Tab.Screen
            name='Common Screen One' // a Stack or even a Tab Navigator with its Tab Bar hidden
            component={CommonScreenOne}
            options=
            {{
                tabBarItemStyle: { display: 'none' }
            }}
            {...otherProps}
        />
        <Tab.Screen {...commonScreenTwoProps-in-the-same-way} />
    </Tab.Navigator>
);
```

The last thing would be to create a Dummy Screen in each of those common Stacks which would be inaccessible to the user in any way. This is to make sure that the Back Button is visible and on clicking it the user navigates back twice. Or if you want you can create a `headerLeft` component and generate a Back Button in it to account for the Dummy Screen.

**Cons:** Pressing the Back Button from each of those Common Screens would always take you back to the Initial Screen of the Tab Navigator. For this you can manually handle the conditions or use the first method which is also listed in the official React Navigation Docs.

**Custom Navigator (?):** If possible you can also build a Custom Navigator which would implement both a Stack and a Tab Navigator. An idea is to introduce a `type` attribute in the Screen element which can hold a value of `"stack" | "tab"`. A stack would keep its Tab Bar Item Hidden and generate a Back Button. The Back Button can also navigate you back up to the right Tab you were in before navigating into the Stack. This method needs proper knowledge of React Navigation Components used within the library which would be burdening as the Docs were kept as minimal as possible. I am yet to learn how this can be achieved.

**Comment by jackrdye** [comment]
> > > I will paste here final version of my solution
> > > @andrewdang17 It may help your problem
> > > Create a file called SharedScreens.js
> > > Put all your shared screens in that array below
> > > ```
> > > export const getSharedScreens = Stack => {
> > > return [
> > >     <Stack.Screen key="SharedScreen1" name={'SharedScreen1'} component={SharedScreen1} />,
> > >     <Stack.Screen key="SharedScreen2" name={'SharedScreen2'} component={SharedScreen2} />,
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Creating the second "Main Stack1" -> MainStack1.js
> > > ```
> > > //Stack Object for our Stack1
> > > const Stack = createStackNavigator();
> > > 
> > > export const Stack1 = props => {
> > > 
> > >   //We pass the Stack Object to the function
> > >   const sharedScreens = getSharedScreens(Stack);
> > > 
> > >   return (
> > >     <Stack.Navigator>
> > >       <Stack.Screen key="Stack1Screen1" name={'Stack1Screen1'} component={Stack1Screen1} />,
> > >       <Stack.Screen key="Stack1Screen2" name={'Stack1Screen2'} component={Stack1Screen2} />,
> > >       {sharedScreens}
> > >     </Stack.Navigator>
> > >   );
> > > };
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Creating the second "Main Stack2" -> MainStack2.js
> > > ```
> > > //Stack Object for our Stack2
> > > const Stack = createStackNavigator();
> > > 
> > > export const Stack2 = props => {
> > > 
> > >   //We pass the Stack Object to the function
> > >   const sharedScreens = getSharedScreens(Stack);
> > > 
> > >   return (
> > >     <Stack.Navigator>
> > >       <Stack.Screen key="Stack2Screen1" name={'Stack2Screen1'} component={Stack2Screen1} />,
> > >       <Stack.Screen key="Stack2Screen2" name={'Stack2Screen2'} component={Stack2Screen2} />,
> > >       {sharedScreens}
> > >     </Stack.Navigator>
> > >   );
> > > };
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Key point here is that the MainStack1 or MainStack2 should not have the same screens as in the SharedScreens array. If you need to have, have it with different name and stack otherwise react navigation will complain
> > 
> > 
> > hey swizes, your solution is working for me but do you know if there's much performance overhead to instantiating a new stack navigator per tab?
> 
> TBH I did not check, if this causes any performance issues but so far I have used this approach in production and didn't notice any performance overhead. But in my opinion adding manually or via a function should not make a difference.

This works :). Any ideas on how to structure it with typescript? I'm unable to get the {CommonScreens(Stack)} added as types to recognise params etc.
