### ISSUE TITLE
Requested keys of a value that is not an object

### ISSUE THREAD

**Issue by sebavp** [react-navigation/react-navigation#3791]
This is a weird error that I came across, I haven't found any reference to it so here it goes.
### Current Behavior

- What code are you running and what is happening?
  Getting 'TypeError: Requested keys of a value that is not an object.'
  Here is a snack: https://snack.expo.io/HkKxAHpKM
Running on an Android 7.1.1 device. 
Also, when I activate 'Debug JS Remotely' in Expo App the error stops

### Expected Behavior

- What do you expect should be happening?
 for the error not to happen.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.5.7
| react-native     | https://github.com/expo/react-native/archive/sdk-25.0.0.tar.gz
| node             | 8.2.1
| npm or yarn      | 5.3.0

**Comment by ericvicenti** [comment]
This looks like a JSC error inside of Expo on Android, unfortunately, because the issue cannot be reproduced on iOS or within the chrome debugger.

Sorry I don't have more time to help you debug this, but I am pretty sure the issue is not within react-navigation 😢

**Comment by sebavp** [comment]
Just in case someone comes across this, I worked around this by changing the 'headerForceInset' in navigationOption, I put a number which caused the problem then I changed to {top: 10} and it worked. I don't know whay it worked in Debugging mode though.

**Comment by brentvatne** [comment]
ah, yeah that is the issue. `headerForceInset` is an object. would be nice to provide an invariant around this so it gives a more useful error
