### ISSUE TITLE
Passing parameters into a StackNavigator

### ISSUE THREAD

**Issue by chen4393** [react-navigation/react-navigation#3794]
I want to pass an object to a StackNavigator. 
Here is my StackNavigator:
```
const RootNavigator = StackNavigator(
  {
    Home: {
      screen: HomeScreen
    },
    Details: {
      screen: DetailsScreen
    },
  }
);
```
And here is my data object:
```
const data = {
  time: '3:46PM',
  country: 'US'
}
```
My question is how to pass my data object to my RootNavigator so that both HomeScreen and DetailsScreen can access my data object? Thanks.

**Comment by EstebanBP** [comment]
`<RootNavigator screenProps={data} />`

**Comment by brentvatne** [comment]
hi there! this is a question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.

**Comment by chen4393** [comment]
Yes, I can use screenProps to pass parameters inside a navigator. Thanks.
