### ISSUE TITLE
Switch Navigator does not render correctly when placed inside Tab or Drawer Navigator

### ISSUE THREAD

**Issue by hjpsievert** [react-navigation/react-navigation#3796]
### Current Behavior

I was very excited to see the new switch navigator as my navigation is more point-to-point, rather than following a breadcrumb trail as better supported by stack navigator. However, when I converted my stacks into switches, I ran into issues. When the switch navigator is inside a stack navigator, it works just fine, even seems to take configuration from what initially was a stack navigator.

**When I converted existing stacks that were inside a tab or drawer navigator, no headers are rendering.**

### Expected Behavior

**Switch Navigator renders like Stack Navigator, but no back functionality and routes are reset.**

Even though the switch navigator has been introduced in connection with a login flow, I expected that it would mimic the behavior of a stack, but not provide the back function and reset routes to default. It was not clear from the current API documentation whether SwitchNavigatorConfig behaved similar to stack navigator.

The documentation only shows a few params that can be set, so I was pleasantly surprised when my existing stack navigator fully worked when converted to switch navigator, including using my custom header component correctly. 

### How to reproduce

Both snacks provided have the same file structure, screens are in _Containers_ folder, the Side Menu rendering and Header components are in _Components_, and the navigation is in **AppNavigation** under _Navigation_. I removed Redux and overall navigation may seem a bit convoluted because I removed quite a bit of my existing structure to make this more compact. All screens are minimally rendered and mostly show Header and Tabs and a link.

1. Here is a snack that shows that the initial conversion of the acRegisterStack from stack to switch works just fine. Just pull out the side menu and select Account Management, everything looks fine. When you go to the Plans tab from the home screen and clock on Plan Breakdown Screen it renders fine as stack navigator:

https://snack.expo.io/@hjpsievert/switch-navigator-issue-working

2. Here is the snack where I converted the fpPlanStack which is located inside a tab navigator from stack to switch and it looses its header. Similarly, I converted the acStack, the parent of the acRegisterStack, to a switch navigator, and now the account management page is not rendering correctly, also missing the header. Removing the original stack navigator navigationOptions in the screen containers and only leaving the title definition does not change anything.

https://snack.expo.io/@hjpsievert/switch-navigator-issue-not-working

### Workaround identified

When I inserted an additional stack navigator above either of the two problem navigators, that is below the Tab or Drawer navigators, and then ran the Stack Navigators that did not work correctly as Switch Navigators, the expected behavior is seen, but this seems to be a bit of a brute force approach.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.5.7
| react-native     | 0.52.0 
| node             | 6.10.2
| yarn      | 1.5.1

**Comment by brentvatne** [comment]
hi! sorry for the slow response. this is expected behavior, switchnavigator does not render any headers. it is very barebones and just switches between screens. there's a request for it here: https://react-navigation.canny.io/feature-requests/p/switchnavigator-header-bar.
