### ISSUE TITLE
Navigation between navigator without re-construct the screen

### ISSUE THREAD

**Issue by Kisepro** [react-navigation/react-navigation#3797]
I would like to navigate from a screenA ( include in a Stacknavigator ) to a screenB ( include in a TabNavigator ) without re-construct the screenB.

I created a snack in Expo https://snack.expo.io/rkFQ14LKz.

As you can see navigate between screens in TabNavigator does not call the constructor but coming from a Stack screen it will re-create the screen.

Is it possible ?

**Comment by brentvatne** [comment]
dupe of https://github.com/react-navigation/react-navigation/issues/3804
