### ISSUE TITLE
Dynamic drawer width

### ISSUE THREAD

**Issue by EstebanBP** [react-navigation/react-navigation#3802]
Hi, Im sorry, this might not be a bug but a question, but I got no success in SO or Discord.

Is it possible to change drawerWidth dynamically?
Let's say I have a drawer and I set up drawerWith to 500 in drawerConfig
```
new DrawerNavigator(
      {
        SomeStack: {
          screen: SomeStack,
        },
      },
      {
        drawerWidth: 500,
        drawerPosition: 'right',
        contentComponent: ({ navigation }) => <MyDrawerView />,
      },
    );
```
I'd like to have some buttons inside MyDrawerView and change drawerWidth when user press on them.
Is it possible?

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  0.54.2
| react-native     | 1.5.7

**Comment by brentvatne** [comment]
that's not possible currently. you can post a feature request on http://react-navigation.canny.io/ or fork the drawer to add whichever behavior you like!

**Comment by cmcodes1** [comment]
```jsx
<Drawer.Navigator
  drawerStyle={{
    backgroundColor: '#c6cbef',
    width: 240,
  }}
>
  {/* screens */}
</Drawer.Navigator>
```

**Comment by hamzaASK** [comment]
<Drawer.Navigator 
      screenOptions={ {
        drawerStyle: {
                              backgroundColor: '#c6cbef',
                              width: 240,
                              },
      } }>
 {/* screens */}
</Drawer.Navigator>
