### ISSUE TITLE
Not able to create fully transparent screens 

### ISSUE THREAD

**Issue by dahiri-farid** [react-navigation/react-navigation#3803]
### Current Behavior

I have a stack with 3 screens. With the following cardStyle configuration
` 
   cardStyle: {
      backgroundColor: 'transparent',
    }
`
I would like to have all my screens transparent with a blur effect. A dynamic background view (at the base level, below the screens) will be always visible. 
Actually, when I set the cardStyle background to transparent, it becomes black. I have attached a screenshot of XCODE visual debugger.
<img width="827" alt="screenshot 2018-03-20 11 51 55" src="https://user-images.githubusercontent.com/10142212/37649595-eeb5bdfc-2c3a-11e8-8a28-8da0b0cc8e34.png">

### Expected Behavior
When I set cardStyle background to transparent, the screen background should be transparent.

### How to reproduce

Create a stack of several screens (A, B, C). Set the cardStyle backgroundColor to transparent. Generate a push from A to B or C. 

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.5.6
| react-native     | 0.54.0
| node             | v8.9.4
| npm or yarn      | 5.6.0

**Comment by brentvatne** [comment]
can you explain what you're trying to accomplish by doing this?

**Comment by dahiri-farid** [comment]
Hello Brent. Yes basically this is what I want to achieve. I have spent some time on implementing a custom transition using a stack navigator and I have made a video of it.
So basically in my custom transition the only think that is missing is that when I push/pop child screen, the parent is not moving like in iOS. I can do that using this transition but in that case I will see half of the screen with black background. This happens because right now my dynamic content is in parent screen. The reason for that, is that if I move my dynamic content out of my stacknavigator (parent screen), it will not be visible. because of black background.

https://www.dropbox.com/s/ycfxl362bsast3s/custom-blur-transition.mov?dl=0

**Comment by brentvatne** [comment]
perhaps it's related to this? https://github.com/react-navigation/react-navigation/blob/e27ad22c57444fadb827bf3bd3a75e3b2ca38041/src/views/StackView/StackViewCard.js#L26-L27

**Comment by brentvatne** [comment]
see: https://github.com/react-navigation/react-navigation/issues/2713

**Comment by brentvatne** [comment]
moved to a feature request
