### ISSUE TITLE
Keyboard can't be dismissed after coming back in StackNavigator

### ISSUE THREAD

**Issue by cryser29** [react-navigation/react-navigation#3805]
### Current Behavior

`StackNavigator` contains two screens. Each of them has `TextInput`. Second one has `autoFocus` prop. User presses on `TextInput` on the first screen, keyboard opens, user navigates to the second screen, comes back. He isn't able to dismiss the Keyboard by pressing outside of `TextInput`. The only way to make it work is to press on the `TextInput` again.

### Expected Behavior

User always should be able to dismiss the Keyboard.

### How to reproduce

The issue can be reproduced using [following Snack](https://snack.expo.io/@cryser29/textinput-focus-issue).

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.5.8
| react-native     | 0.52
| Expo SDK | 25.0.0

**Comment by brentvatne** [comment]
Thanks for this report! It looks like `keyboardShouldPersistTaps="handled"` doesn't work well in this situation because of the way gestures are handled with PanResponder... there's not much that can be done in the short-term for this but we are going to be rewriting the gesture part of stack navigator to react-native-gesture-handler soon and we will be able to fix the problem at that point.

Until then, you may want to use `keyboardDismissMode="on-drag"` which gets you pretty similar behavior.

**Comment by cryser29** [comment]
@brentvatne Thank you for the quick answer!

For my regret `keyboardDismissMode="on-drag"` doesn't work in my case. I use `alwaysBounceVertical={false}` so user isn't able to drag, he can only tap. As a workaround I would prefer to save last focused `TextInput` and call `focus()` right after the screen appears again.

I think the important information is that this issue can be reproduced with another navigation library. We used `react-native-navigation` before. I've run the older project version and managed to reproduce the issue too.

It would be great to reproduce the issue without any navigation at all. I tried to just render additional `TextInput` with `autoFocus` by condition (condition is a flag that can be toggled by button for example). That `TextInput` becomes focused once condition is true. But once the condition is false and it isn't rendered no more first `TextInput` doesn't receive focus.

Do you know why first `TextInput` receives focus again after a reversed transition? If we manage to emulate a reversed transition without a navigation library the issue can be moved to `react-native`.

Thank you!

**Comment by cryser29** [comment]
I've found the workaround that works for me:

```
<TextInput
  ref={input => this.input = input}
  onFocus={() => setTimeout(this.input.focus, 0)}
/>
```

This solution works because `onFocus` also calls when user comes back to the first screen.

**Comment by eriveltonelias** [comment]
Hi @cryser29! 

I just tested your example using the last update of `react-navigation` and now it's working as expected. :)
