### ISSUE TITLE
Using TabBarBottom with tabBarPosition: 'top' doesn't work with iPhoneX

### ISSUE THREAD

**Issue by markphilpot** [react-navigation/react-navigation#3817]
When TabBarBottom uses the <SafeArea/> construct, it sets `forceInset={{ bottom: 'always', top: 'never' }}` which will applies bottom padding always.  When using the bar in the top position these `forceInset` parameters should be reversed.

---

### Current Behavior

Extra padding for safeArea included when using TabBarBottom with tabBarPosition: top on iPhoneX

![image](https://user-images.githubusercontent.com/46191/37802909-91310ec4-2de9-11e8-88fa-84696541d4cf.png)

### Expected Behavior

The SafeArea forceInset parameters should take it's cue from tabBarPosition.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.5.8
| react-native     | v0.25
| node             |
| npm or yarn      |

**Comment by brentvatne** [comment]
we don't support this style of navigator. in v2, which we will be releasing shortly, we made this very explicit and you can no longer tell a bottom tab bar to be rendered on the top. if you'd like to build this you can do so using the same mechanism with which we created the tab navigators, see https://github.com/react-navigation/react-navigation-tabs for the repo with the new navigators and https://v2.reactnavigation.org/docs/bottom-tab-navigator.html for doc with some more info. we're also working on updating docs for building custom navigators.

your best bet for now is to supply a custom tabbar
