### ISSUE TITLE
Component lifecycle methods are being called for screen's not currently shown on device

### ISSUE THREAD

**Issue by kodayashi** [react-navigation/react-navigation#3818]
### How to reproduce

Two screens (A and B). Implement componentDidUpdate() in A. Change your redux state (or do something) that triggers this lifecycle method. Navigate to B and do something that would've triggered the lifecycle method in A again (e.g. a redux store update). You'll notice that the lifecycle method in A fires again.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.5.8
| react-native     | 0.53.3
| node             | 9.5.0
| yarn      | 1.3.2

**Comment by vonovak** [comment]
@kodayashi this is actually expected. The A screen in your example is not unmounted, so it still receives new props from redux when its state updates. There is now a new `ResourceSavingSceneView.js` component, so the behavior may change slightly in v2, but I do not know the details.

**Comment by kodayashi** [comment]
@vonovak - Yep just tried doing a snack and realized that the component isn't unmounting, leaving lifecycle methods active. I could see how this may be preferred by default for performance reasons, but I'd also be very useful to ensure that components are unmounted upon navigation (perhaps a navigation option?)
