### ISSUE TITLE
navigation header transparent

### ISSUE THREAD

**Issue by Taffyw** [react-navigation/react-navigation#3822]
hello, i have a little problem!
Can i set the head navigation background transparent or the gradient effect, for example, the default is the transparent page that slides a segment of distance and becomes the default color.
Or is it to set the head null and then customize the header component implementation?
thank you!
| software         | version
| ---------------- | -------
| react-navigation | 1.5.8
| react-native     | 0.49.3
| node             | 6.11.3
| npm or yarn      | yarn

**Comment by brentvatne** [comment]
https://reactnavigation.org/docs/stack-navigator.html#headertransparent
https://reactnavigation.org/docs/stack-navigator.html#headerbackground
https://github.com/react-navigation/react-navigation/blob/9c3fffa47fba0ef64e580ce96ee3cb5cbc3f69f0/examples/NavigationPlayground/js/StackWithTranslucentHeader.js
