### ISSUE TITLE
StatusBar not showing on Android

### ISSUE THREAD

**Issue by huiming1313** [react-navigation/react-navigation#3826]
Anyone else experiencing this ? I can't see android StatusBar and if i set marginTop: Expo.Constants.statusBarHeight, i can see the header but the color is a bit weird.

This is the result
![screenshot_2018-03-23-01-35-31-108_host exp exponent](https://user-images.githubusercontent.com/15344977/37788816-66518298-2e3d-11e8-8019-e62741110d59.png)

This is the result with marginTop: Expo.Constants.statusBarHeight in navigationOptions
![screenshot_2018-03-23-01-38-01-245_host exp exponent](https://user-images.githubusercontent.com/15344977/37788833-6f27078a-2e3d-11e8-8087-d8e9147a1a8b.png)

This is the result in IOS
![img_7852](https://user-images.githubusercontent.com/15344977/37788838-72901b96-2e3d-11e8-8e8f-21365d8f724e.PNG)

The status bar should be like this
![screenshot_2018-03-23-01-38-24-129_com ddctimes](https://user-images.githubusercontent.com/15344977/37788843-750b06e2-2e3d-11e8-861a-3ccd23241e3b.png)

software | version
-- | --
react-navigation | ^1.5.1
react-native | 0 .52
expo | ^25.0.0

Attached my GitHub repo for your reference. https://github.com/huiming1313/laughing-robot
Any help would be greatly appreciated! :)

**Comment by brentvatne** [comment]
in the example you shared i see the status bar as expected

<img width="657" alt="screen shot 2018-03-23 at 10 25 27 am" src="https://user-images.githubusercontent.com/90494/37844275-863cce7c-2e84-11e8-818c-50ea23423cc0.png">

what device are you using? what do other apps look like on the device? what am i missing to be able to repro your screenshot?

**Comment by huiming1313** [comment]
working in android emulator though, but not when i scan from my device.

I'm using Redmi Note 5A android version 7.1.2.

Will it be affected by their own custom UI ? because this phone is using MIUI, but some of the apps i developed earlier doesn't have this problem (which i've downloaded from playstore).

**Comment by brentvatne** [comment]
it's something about your own OS config but yeah i have no idea what is going on here.

**Comment by remontees** [comment]
I'm experiencing exactly the same issue now with a Redmi Note 5A with Android 9.
