### ISSUE TITLE
How to Hide Single Tab from Tab Bar in Tab navigator ?

### ISSUE THREAD

**Issue by vnnovatedeveloper** [react-navigation/react-navigation#3830]
I have created one tab navigator in Which I have three tabs

----A-------B------C-----

I want that for certain condition my Tab B must Hide/not visible 
As 
------A---------C-------

Any one has any idea how this thing can be possible?

**Comment by PatNeedham** [comment]
@vnnovatedeveloper were you able to find out a way to do that?
