### ISSUE TITLE
How to hide particular tab in tab navigator on some flag from Redux ?

### ISSUE THREAD

**Issue by bhautik-bharadava** [react-navigation/react-navigation#3831]
I have created one tab navigator in Which I have three tabs

----A-------B------C-----

I want that for certain condition my Tab B must Hide/not visible
As
------A---------C-------

Moreover, I want this condition using redux.
Does anyone have any idea how this thing can be possible?

**Comment by brentvatne** [comment]
https://react-navigation.canny.io/feature-requests/p/hiding-tab-from-the-tabbar
