### ISSUE TITLE
iPhone X with Top TabBar isn't working

### ISSUE THREAD

**Issue by DLevai94** [react-navigation/react-navigation#3832]
In a TabNavigator if I set the TabBarPosition to top, it doesn't respect the iPhone X's notch. If I want to create a Tinder like top navbar, I can't because of the Navigators fixed 84 height and 34 paddingBottom.

This is a modified version of official docs: [https://snack.expo.io/@dlevai94/react-navigation-docs:-iphonex-demo](https://snack.expo.io/@dlevai94/react-navigation-docs:-iphonex-demo)
Changes:
* uncommented headerMode: 'none' on the StackNav,
* added tabBarPosition: 'top' to TabNav

For now, I fixed like this:
In the TabBarBottom.js line 236 change to this:
```
forceInset={ this.props.tabBarPosition === 'top' ? false : { bottom: 'never', top: 'always' }}
```

Maybe there should be an option to use the TabBarBottom in top with proper SafeAreaHandling? I can't use TabBarTop too because it isn't handle any SafeArea (yeah, I know. Android component)

**Comment by brentvatne** [comment]
this solution isn't quite right because you usually want a tab bar on the top underneath a header, and this would add extra padding. I'm not sure what the best solution here is but agree it's an issue that should be resolved

**Comment by Swolebrain** [comment]
So I think I'm running into this. This is a screenshot of my app and it has some extremely intrusive extra spacing below the tabbar only in iphone x:

![image](https://user-images.githubusercontent.com/10286294/38644460-8504bd56-3dae-11e8-85e3-8941a5ad7876.png)

What can I do about this?

**Comment by hans-1** [comment]
I solved this by wrapping the TabNavigator itself in a `SafeAreaView`:

```javascript
class MainScreen extends React.Component {
  render() {
    return (
      <SafeAreaView style={{flex: 1, backgroundColor: '#ffffff'}}>
        <MainScreenNavigation />
      </SafeAreaView>
    );
  }
}
```
and
```javascript
const MainScreenNavigation = TabNavigator({
  Tab1: Tab1,
  Tab2: Tab2,
  Tab3: Tab3,
}, 
{
  tabBarComponent: TabBarTop,
  tabBarPosition: 'top',
});
```

**Comment by brentvatne** [comment]
this issue lives on the new repo for tabs: https://github.com/react-navigation/react-navigation-tabs/issues/1
