### ISSUE TITLE
headerBackImage not work

### ISSUE THREAD

**Issue by lasthrun** [react-navigation/react-navigation#3836]
```
import backChevron from './assets/images/backChevron.png'

static navigationOptions = ({navigation}) => ({
  headerBackImage: {backChevron} //this will show nothing in the image position
  //have try 'headerBackImage: backChevron' too. not work too. this will show native image
})
```
It is worth noting that the document example seems to be wrong

### Current Behavior

have not replace headerBackImage

### Expected Behavior

it should replace headerBackImage

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |1.5.8
| react-native     |0.52.2
| node             |8.9.4
| npm or yarn      |5.6.0

**Comment by aknad** [comment]
you can try with:

static navigationOptions = ({navigation}) => ({
  headerBackImage: {require('./assets/images/backChevron.png')}
})

https://reactnavigation.org/docs/stack-navigator.html#headerbackimage

**Comment by kanion** [comment]
try:

```
static navigationOptions = {
        headerBackImage: require('../../assets/icon.png'),
};
```

it is working, but I see that sometimes icon loads slowly

**Comment by lasthrun** [comment]
still not work, is it relate CRNA? @brentvatne can you reopen this issue?

**Comment by austin-roberts** [comment]
I am getting the same results as @lasthrun 

Most attempts result in native image still being displayed. `static navigationOptions = {
        headerBackImage: require('../../assets/icon.png'),
};`

This shows native image. Cannot get my new set of icons to take no matter what I try. Can we re-open this?

**Comment by meetravi** [comment]
Same issue and Still not able to use this headerBackImage

**Comment by lasthrun** [comment]
> Same issue and Still not able to use this headerBackImage

Is you just trying to change the image colour? if yes, i found they use `headerTintColor` to cover the source image colour. so the truth is, the image had correctly change, but the colour has been replace to `headerTintColor`.

**Comment by guoxuzan** [comment]
try <Image.../>

**Comment by guoxuzan** [comment]
headerBackImage:<Image />

**Comment by guoxuzan** [comment]
headerBackImage:<Image source={require('./images/myBack.png')}></Image>
