### ISSUE TITLE
Deep Linking requires different paths when the app is already loaded

### ISSUE THREAD

**Issue by EyMaddis** [react-navigation/react-navigation#3840]
# Setup
Requires a setup of deep linking!

```js
const Navigator = TabNavigator({
  main: {
     screen: StackNavigator({
        home: { screen: MainComponent },
        nested: { screen: NestedComponent } 
     }}
  },
  other: {
     ....
  }
})
``` 

I ran the following situations on the iOS simulator.

## Situation 1: Cold Start
* do not start the app (or close via app switcher)
* open `myapp://main/nested` via `xcrun simctl openurl booted myapp://main/nested`

### Current Behavior
shows NestedComponent as expected

## Situation 2: MainComponent is already rendered
* open the app
* manually navigate to "Main"
* open `myapp://main/nested` via `xcrun simctl openurl booted myapp://main/nested`

### Current Behavior
Pushes and renders MainComponent a second time.

### Expected Behavior 
Should push NestedComponent to the stack and render it.

In order for it to render the screen now, one could call
`xcrun simctl openurl booted myapp://nested` (note the missing `main/`!)

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.1.2
| react-native     | 0.53.0
| node             |  v9.4.0
| npm or yarn      | yarn v1.5.1

**Comment by EyMaddis** [comment]
I think this relates to #2913 and #2904

**Comment by ericvicenti** [comment]
Would you possibly be able to try this on v2 of the library, which is currently in beta? You can also temporarily point to this git repo.

I think the issue will be addressed by @brentvatne's new "less pushy navigate" behavior, but I'd like to make sure this works and there isn't some edge case with nested navigation actions.

Can you help with some debugging steps? The easiest way is to set `process.env.REACT_NAV_LOGGING = true` and post the console output here.

You can see the logging to "createNavigationContainer.js", where the the actions and navigation state are logged?.You'll see the link handling code in "_handleOpenURL", and you can add more logging there to see the action that is generated for each path. Please post your results here!

**Comment by jeffreymendez1993** [comment]
@ericvicenti having the same issue ill try it out.

**Comment by ericvicenti** [comment]
Tabs have been moved to this repo, but will still work in v2: https://github.com/react-navigation/react-navigation-tabs/

For the deep linking bug, can anybody paste the log output that I asked for? Or it would be great if somebody could write a test for the router that causes the bug

**Comment by brentvatne** [comment]
closing because no response. please create a new issue with the information requested by @ericvicenti and following the issue template if this is still a problem
