### ISSUE TITLE
installation failed

### ISSUE THREAD

**Issue by zc-Mukden** [react-navigation/react-navigation#3846]
installation failed

F:\xxxx\TestCodePush>npm install --save react-navigation
npm ERR! code ENOGIT
npm ERR! Error while executing:
npm ERR! undefined ls-remote -h -t ssh://git@github.com/react-navigation/react-native-tab-view.git
npm ERR!
npm ERR! undefined
npm ERR! No git binary found in $PATH
npm ERR!
npm ERR! Failed using git.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Mukden\AppData\Roaming\npm-cache\_logs\2018-03-27T04_18_58_097Z-debug.log

**Comment by Taym95** [comment]
Try to search about this issue in [stackoverflow](https://stackoverflow.com/questions/26620312/installing-git-in-path-with-github-client-for-windows), this is not react-navigation issue.

**Comment by zc-Mukden** [comment]
Thank you, you have solved the problem


------------------ 原始邮件 ------------------
发件人: "Taym Haddadi"<notifications@github.com>;
发送时间: 2018年3月28日(星期三) 凌晨0:59
收件人: "react-navigation/react-navigation"<react-navigation@noreply.github.com>;
抄送: "天海·麒麟星"<1352497075@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [react-navigation/react-navigation] installation failed (#3846)




Try to search about this issue in stackoverflow, this is not react-navigation issue.
