### ISSUE TITLE
How to set the default params when configuring StackNavigator or TabNavigator

### ISSUE THREAD

**Issue by cindyya** [react-navigation/react-navigation#3850]
## How to set the default params when configuring StackNavigator or TabNavigator
const TabNav = TabNavigator(  
  {  
    Home:{  
      screen:Home,  
      initialRouteParams:{name:"12423"},
      navigationOptions:({navigation}) => ({  
        tabBarLabel:'首页',  
        tabBarIcon:({focused,tintColor}) => (  
          <Icon  color={focused?"#58a0ff":"#999"}  size={22} name={!focused?HOME_ICON:HOME_ICON_FOCUS}/>  
        )  
      }),  
    },  
    Mine:{  
          screen:Mine,  
          initialRouteParams:{name:"gggggg"},
          navigationOptions:({navigation}) => ({  
          tabBarLabel:'我',  
          tabBarIcon:({focused,tintColor}) => (  
            <Icon  color={focused?"#58a0ff":"#999"}  size={22} name={!focused?MY_ICON:MY_ICON_FOCUS}/>  
          )  
        }),  
      },  
    },  
    {  
        initialRouteParams:{name:"gggggg"},
      tabBarComponent:TabBarBottom,  
      tabBarPosition:'bottom',  
      swipeEnabled:false,  
      animationEnabled:false,  
      lazy:true,  
      tabBarOptions:{  
        activeTintColor:'#58a0ff',  
        inactiveTintColor:'#999',  
        style:{backgroundColor:'#ffffff',},  
        labelStyle: {  
              fontSize: 12, // 文字大小  
          },  
      }  
    }  
  ); 
I want to set a default params when loading both of page named Mine and page named Home

**Comment by brentvatne** [comment]
there are no 'default params' currently but this would be nice to have. discuss here https://github.com/react-navigation/rfcs/issues/36

**Comment by TranVanThaiSon** [comment]
you can using params: in stacknavigation or tabNavigation :
`Consume: { 
      screen: Consume ,
      navigationOptions: {
        tabBarLabel:i18n.t('news.all'),
      },
      params:{one:1}
    },`
and in screen you want get params only do:
`var x =  this.navigation.getParam('one',0);// default value  = 0
      console.log('my params:',x)`
