### ISSUE TITLE
StackNavigator within a custom Navigator does not render correctly

### ISSUE THREAD

**Issue by nilscox** [react-navigation/react-navigation#3852]
Hi,

I'm having trouble understanding how to create a custom Navigator using a SwitchRouter and having a StackNavigator as its child.
My main navigator displays its child components (a `Home` page and a `Stack` navigator) along with 2 buttons allowing to navigate in the app. The `Home` page is a simple React component, and the `Stack` navigator is a StackNavigator with only one page in it.

### Current Behavior

The `StackPage` page within the StackNavigator is displayed as if it was a regular page, exactly like the `Home` page is.

### Expected Behavior

The `StackPage` page should be displayed like a page in a StackNavigator with default configuration (i.e. a header on top, and the page grayed out).

### How to reproduce

[Here is the snack](https://snack.expo.io/@nilscox/custom-navigator-with-switchrouter-and-nested-stacknavigator) that reproduces the behavior I have.
And [here is the snack](https://snack.expo.io/@nilscox/custom-navigator-with-switchrouter-and-nested-stacknavigator-(expecetd)) that reproduce the behavior I expect.

The only diff is on `App.js:28`, where I define the screen property of the `Stack` route as a functional component instead of giving the StackNavigator directly. According to what I understand from the documentation, I should be able to display the `StackPage` page correctly without having to pass the navigator through a functional component.

> Note: Only tested on an Android device.

### My Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.5.8
| react-native     | 0.52.0
| node             | 8.9.4
| yarn      | 1.5.1

**Comment by brentvatne** [comment]
hi! we totally rewrote the api for creating navigators in 2.0. check out this example, which uses 2.0.0-beta.6: https://snack.expo.io/rkhQkPZoG -- it works as expected in your case. I'd suggest testdriving 2.0 in your project and let us know if you run into any issues. it's feature complete, we're just doing some more QA and polish before full release :)
