### ISSUE TITLE
Open Drawer on pressing a touchable opactity - image

### ISSUE THREAD

**Issue by MounikaK999** [react-navigation/react-navigation#3853]
Open Drawer on pressing a touchable opacity - image

### Current Behavior

- What code are you running and what is happening?
I'm trying to use Drawer navigation. I have header.js components which have a hamburger icon to open the navigation drawer. But, it is giving me the error this.props.navigation.navigate('DrawerToggle') is undefined.

I tried without adding "this" to props.navigation.navigate('DrawerToggle')
   
        //Header.js

         import React from 'react';
         import { Text, View, Image, TouchableHighlight} from 'react-native';
         import { DrawerNavigator  } from 'react-navigation';

         // Make a component
         const Header = (props, {navigate}) => {
         const { textStyle, viewStyle, imgstyle } = styles;

         return (
       <View style={viewStyle}>
    
      <TouchableHighlight onPress={()=> this.props.navigation.navigate('DrawerToggle')}> //here the error is coming
           <Image style={{width:40, height:40}} 
         source={require('./../media/hamburger.png')}
                  />
      </TouchableHighlight>
      
      <Text style={textStyle}>{props.headerText}</Text>
       </View>
         );
         };
         export default Header;

Here is App.js

        const MyApp = DrawerNavigator({
           Login: {
              screen: Login,
           },
           Signup: {
              screen: Signup,
           },
        });

        export default class App extends React.Component {
           render() {
              return <MyApp />;
           }
        }

Here is one of the component Login.js

    import React, { Component } from 'react';
    import {
      Text, View, StyleSheet
     } from 'react-native';
    import Header from './Header';

    export default class Login extends Component{
	static navigationOptions = {
        drawerLabel: 'Login',
     };
	render(){
		return(
			<View >
				<Header headerText={'Login'}/>
				<Text>Login Screen</Text>
			</View>
			 );
	       }
    }

### Expected Behavior

- What do you expect should be happening?
I'm expecting, on clicking the hamburger images navigation drawer should open. 

### How to reproduce

Couldn't find a much better way to share how to reproduce. Please clone this code, https://github.com/MounikaK999/loginregister.git to reproduce the error im facing

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  1.5.8
| react-native     |  0.54.2
| node             |  8.9.4
| npm or yarn      |  npm 5.8.0

**Comment by brentvatne** [comment]
see https://react-navigation.github.io/docs/connecting-navigation-prop.html
