### ISSUE TITLE
Is that an Anti-Pattern ?

### ISSUE THREAD

**Issue by ScreamZ** [react-navigation/react-navigation#3854]
Hello people!

I used to do the following pattern: 

When my `SwitchNavigator` -- which is managing authenticated / anonymous context --  is rendering the `AuthenticatedTabNavigator`, I want to trigger some actions using components lifecycles hooks like the following:

- A `ChatListener` component that is rendering `null` and only serve for the purpose of lifecycle hooks that open a websocket connection in order to listen for incoming messages and close it accordingly. That kind of side effects that I'm not managing using third party library like `redux-saga`.
- It could be anything else, I guess this pattern is very clear and modular.

I saw -- one time -- the following pattern that consist on instantiating a Navigator and use its `navigator.router` to feed my `static router` in my custom component and then I pass the navigation to my router component using props as shown below, if I don't, the component is detached and manage its own state of navigation as described in the documentation.

However, I can't get any reference about this pattern in the documentation anymore ?

Is this pattern considered as a bad practice now ? If it is we could also add a part on the documentation about one good pattern that solve that kind of issues.

```js
import React, { PureComponent } from 'react'
import { View } from 'react-native'
import { connect } from 'react-redux'
import { TabNavigator } from 'react-navigation'
import PropTypes from 'prop-types'

// Components
import ChatListener from '../Containers/Chat/ChatListener'

// Redux and services
import { userMetadata } from '../redux/selectors/user'
import { common as commonStyles } from '../themes'

const AuthNav = TabNavigator(
  {
    Home: {
      screen: require('../Containers/HomeScreen').default,
      path: 'home'
    },
    Explore: {
      screen: require('./Authenticated/ExploreNavigator').default,
      path: 'explore'
    },
    Profile: {
      screen: require('./Authenticated/ProfileNavigator').default,
      path: 'profile'
    }
  },
  {
    initialRouteName: 'Home'
  }
)

class AuthenticatedNavigator extends PureComponent {
  static router = AuthNav.router

  static propTypes = {
    navigation: PropTypes.object.isRequired,
    pushNotifsEnabled: PropTypes.bool.isRequired,
    userMeta: PropTypes.object.isRequired
  }
  componentWillMount() {}

  render() {
    const { userMeta } = this.props

    return (
      <View style={{ flex: 1 }}>
        <ChatListener userMeta={userMeta} />
        <AuthNav navigation={this.props.navigation} />
      </View>
    )
  }
}

const mapStateToProps = state => ({
  userMeta: userMetadata(state)
})

export default connect(mapStateToProps)(AuthenticatedNavigator)
```

It works well, doesn't break the navigation state.

But is it safe ? Is it cool ?

Best regards

**Comment by vonovak** [comment]
> I used to do something like this
> Is that considered as a bad practice

it is not clear what *this* and *that* is. Can you update the description?

**Comment by ScreamZ** [comment]
@vonovak Apologies, my bad,

I updated the description, I hope this is clearer than previously.

Regards

**Comment by brentvatne** [comment]
it's really up to you. I like the SwitchNavigator approach because it's easier to understand imo, but whichever you prefer -- both are totally valid!

**Comment by ScreamZ** [comment]
I'm combining both, it was about creating kind of `side effect` components that are displayed only in some context.

If it's still valid, then it's okay.

Thank you :-)
