### ISSUE TITLE
Typescript definition for tabBarVisible in StackNavigator options

### ISSUE THREAD

**Issue by stereodenis** [react-navigation/react-navigation#3855]
I have `StackNavigator` inside `TabNavigator` and to hide tabBar I use `tabBarVisible`
And this parameter is not in definition of `StackNavigatorConfig`

```Error:(30, 4) TS2345: Argument of type '{ navigationOptions: { headerStyle: { backgroundColor: any; }; headerBackTitle: null; headerTintC...' is not assignable to parameter of type 'StackNavigatorConfig | undefined'.
  Type '{ navigationOptions: { headerStyle: { backgroundColor: any; }; headerBackTitle: null; headerTintC...' is not assignable to type 'StackNavigatorConfig'.
    Types of property 'navigationOptions' are incompatible.
      Type '{ headerStyle: { backgroundColor: any; }; headerBackTitle: null; headerTintColor: string; headerT...' is not assignable to type 'NavigationStackScreenOptions | ((navigationOptionsContainer: NavigationScreenConfigProps & { navi...'.
        Object literal may only specify known properties, and 'tabBarVisible' does not exist in type 'NavigationStackScreenOptions | ((navigationOptionsContainer: NavigationScreenConfigProps & { navi...'.```

**Comment by vonovak** [comment]
we do not provide the typescript definition, you will have to find whoever maintains this and ask them to update it or submit an update yourself. sorry! see: react-navigation/rfcs#34 -- if you'd like to help with it, it'd be great!

**Comment by nhht77** [comment]
Hi, 

I also have a use case where the solution to this issue could help a lot.

I am using Typescript react-navigation in my project and I face the situation where I want to hide the bottom navigation bar in some nested screen of a stack in tab navigation.

If there is already a solution, that would be great!

**Comment by EugeniusGR** [comment]
@nhht77 did you find it?
