### ISSUE TITLE
can not show TabNavigator after I do like down said!

### ISSUE THREAD

**Issue by clycheng2015** [react-navigation/react-navigation#3857]
When passing navigation prop, you tell navigator that its navigation is coming from either Redux or parent navigator. That means it's not acting as a top-level navigator. uriPrefix is only respected if navigator is top-level.

In order to use Redux with deep linking, you should do something along these lines on your own: https://github.com/react-community/react-navigation/blob/master/src/createNavigationContainer.js#L159-L163

@grabbou Thank you so much for the solution. I followed your instruction and was able to integrate both Redux and deep linking successfully, except, the customized stack navigator and it's descendants in my implementation aren't receiving any header. (I understand, it has something to do with CardStack. But, couldn't get a clear idea from the doc. to resolve my issue)
 
I do not thnow why? do @grabbou thnow????
my code is down---->

const HomeNavigator = TabNavigator({....})
export const MainNavigator = StackNavigator({.....})

export default class AppNav extends Component {
    constructor(props, context) {
        super(props, context);
        this.handleUrl = this.handleUrl.bind(this);
    }

    static router = StackRouter(
        {
            MainNavigator: {screen: MainNavigator}
        }
    );

    handleUrl(url) {
        const { navigation } = this.props;
        const { dispatch } = navigation;
        const uriPrefix = 'buyer://hmc/';
        const params = {};
        let path = url.split(uriPrefix)[1];
        if (!path) {
            path = url;
        }
        const action = AppNav.router.getActionForPathAndParams(path, params);

        if (action) {
            dispatch(action);
        }
    }

    componentDidMount() {
        Linking.addEventListener('url', ({ url }: {url: string}) => {
            this.handleUrl(url);
        });

        Linking.getInitialURL().then(
            (url:string) => url && this.handleUrl(url)
        );
    }

    render() {
        const { navigation } = this.props;
        const { state, dispatch } = navigation;
        const { routes, index } = state;
        const Component = AppNav.router.getComponentForState(state);
        let childNavigation = {dispatch, state: routes[index]};
        childNavigation = addNavigationHelpers(childNavigation);
        return (
            <Component navigation={childNavigation}/>
        );
    }
}

**Comment by clycheng2015** [comment]
class Navigation extends Component {
    constructor(props) {
        super(props);
        this.state = {};
    }

    render() {
       
        const { dispatch, nav } = this.props;
       
        const navigation = addNavigationHelpers({
            dispatch,
            state: nav,
            addListener
        });
        return (<AppNav navigation={navigation} />);
    }
}

export default Navigation;

**Comment by brentvatne** [comment]
hi there! this is a question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.
