### ISSUE TITLE
TabNavigator with StackNavigator cant work

### ISSUE THREAD

**Issue by massoprod** [react-navigation/react-navigation#3858]
I have tried to import TabNavigator inside StackNavigator, but for longer time I have same Error screen in my App.

react-native: 0.52
react-navigation: 1.5.8
react: 16.3.0-alpha.1
node: 8.3.0
npm: 5.4.0
yarn: 1.3.2

## ERROR SCREEN: 
![29633991_10210974283860860_122306341_o](https://user-images.githubusercontent.com/8200096/38072210-a405788c-3325-11e8-9263-67a146a714c8.png)

## TAB NAVIGATOR:
```
import React, { Component } from 'react';
import { TabNavigator } from 'react-navigation';

// Components
import Home from '../components/Tabs/Home';
import Profile from '../components/Tabs/Profile';

export const Tabs = TabNavigator({
  Home: {
    screen: Home,
    navigationOptions: ({ navigation }) => ({
      title: 'Home'
    }),
  },
  Profile: {
    screen: Profile,
    navigationOptions: ({ navigation }) => ({
      title: 'Profile'
    }),
  },
}, {
  lazy: true,
  swipeEnabled: true,
  animationEnabled: true,
  tabBarPosition: 'bottom',
});
```

## STACK NAVIGATOR:
```
import React from 'react';
import { StackNavigator } from 'react-navigation';

// Components
import Home from '../components/Tabs/Home';
import Tabs from './Tabs';

export const SignedIn = StackNavigator({
   Tabs: {
     screen: Tabs, 
  },
  Home: {
    screen: Home,
    navigationOptions: ({ navigation }) => ({
      title: 'Home'
    }),
  },
});
```

**Comment by checkmatez** [comment]
You exporting Tabs as a named export, but importing as a default export. You might want to change this line:
`export const Tabs = TabNavigator({`
to
`export default TabNavigator({`

**Comment by massoprod** [comment]
@checkmatez it works. Thanks!
