### ISSUE TITLE
how can I pass more than one param when use uriPrefix

### ISSUE THREAD

**Issue by clycheng2015** [react-navigation/react-navigation#3861]
when I do like this {screen: CarInfoDetail, path: 'react/pages/cartype/carInfoDetail/:typeId'},just one param, it works,

but,can I do  {screen: CarInfoDetail, path: 'react/pages/cartype/carInfoDetail/:typeId/:other'},and what  should I do in Android the Activity which one to jump and send params to Rn Page that use uriPrefix?

**Comment by brentvatne** [comment]
cc @ericvicenti perhaps for docs?

**Comment by ericvicenti** [comment]
Yeah, hopefully this is just a docs improvement. We should fully support paths like the one you mentioned.
