### ISSUE TITLE
how to navigate when i use both StackNavigation and TabNavigation in project?

### ISSUE THREAD

**Issue by Wangzihao5325** [react-navigation/react-navigation#3865]
As i use both StackNavigation and TabNavigation in project like this:
```
const TabNavi = TabNavigator({
  HomePage: { screen: FirstRoute },
  Service: { screen: SecondRoute },
  Login: { screen: ThirdRoute },

}, {
    tabBarPosition: 'bottom',
    swipeEnabled: false,
  });

const RootStack = StackNavigator(
  {
    Home: {
      screen: TabNavi,
    },
    MapLoad: {
      screen: MapLoad,
    },
    Map: {
      screen: Map,
    },
  });
```  
but in homepage i can't navigate to mapload ,"undefined is not an obj(this.props.navigation.navigate)",i think that the navigation i get from "this.props.navigation" is the TabNavigation ,but how can i get the StackNavigation ? i am sorry for my poor english, and hope anyone could help me

**Comment by ztMalone** [comment]
You can try to replace "this.props.navigation.navigate" with "navigation.navigate". Hope it can help you
!

**Comment by Wangzihao5325** [comment]
i try that but it doesn't work.and i solve the problem by use **Navigating without the navigation prop** in the guide Docs
