### ISSUE TITLE
Component renders three times after reseting stack and calling setParams from componentWillMount

### ISSUE THREAD

**Issue by michalpetrov** [react-navigation/react-navigation#3867]
### Current Behavior
I'm having a simple stack containing just two components: Loading, Main. First Loading is rendered, after two second the stack is reseted with Main component. Everything works as expected. But if the Main component has button in the header that needs to interact with the Main component than the Main component is rendered three times.

The component renders only once If `componentWillMount` is empty.
The component renders three times if the function to be called is set like this:
```
componentWillMount() {
    this.props.navigation.setParams({doSomething: this.doSomething})
}
``` 

The problem occures only after resetting the stack.

### Expected Behavior
Component should render only once.

### How to reproduce
Snack example: https://snack.expo.io/HyzENh99z

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.5.8
| react-native     | 0.54.4
| node             | v9.9.0
| yarn      | 1.5.1

**Comment by lxcid** [comment]
I just found out about this issue it cause the unmounting and mounting my screen until it return this error

![screenshot 2018-03-30 12 18 27](https://user-images.githubusercontent.com/297156/38124488-80883fc6-3414-11e8-9b97-2e1446596cca.png)

**Comment by lxcid** [comment]
Sorry for reposting, I'm just trying to figure out which ticket does this really belong to, I decide it should be here…

I just found out about this issue it cause the unmounting and mounting my screen until it return this error out.

![screenshot 2018-03-30 12 18 27](https://user-images.githubusercontent.com/297156/38124488-80883fc6-3414-11e8-9b97-2e1446596cca.png)

Might be remotely related to #3730 as well.

**Comment by ericvicenti** [comment]
I've been looking into this. Reset is an "immediate transition", which is a somewhat new concept in the library. You've uncovered some real bugs here!

One thing I'll note is that you shouldn't be using `componentWillMount` here. No matter what you do, it will momentarily render in the initial state. Use component did mount instead.

Here's the test snippet I used to verify this bug against react navigation master: https://gist.github.com/ericvicenti/4acda38271fd4bef677f26dbc24428e2

Here are PRs that address the extra rendering I see in your example use-case:

https://github.com/react-navigation/react-navigation/pull/3899
https://github.com/react-navigation/react-navigation/pull/3901
https://github.com/react-navigation/react-navigation/pull/3902

Your problem should go away in the upcoming v2 release!

**Comment by brentvatne** [comment]
@cogell - can you clarify your question? I don't understand

**Comment by joshuapinter** [comment]
I'm still running into this issue where anytime `navigation.setParams()` is called, a complete re-render of the Component is issued. Whether that's in a `componentDidMount` or a Button's `onClick` long after the entire screen has been rendered.

This was the case on version 1 and then I tried updating to `2.0.1` and it still exhibits this behaviour. None of the other links referenced here seemed to address it.

Is this expected or is this an issue with the library or our app?

Thanks!

**Comment by ericvicenti** [comment]
If you call `setParams`, it is expected that your component will re-render. That way it can display the new params, which are coming in through `props.navigation.state.params`. There is a helper called `props.navigation.getParam` but it is just a helper to access `state.params`. So its definitely a good thing that the component re-renders when the params change!

To avoid a flashy behavior when the screen appears, avoid setting params in `componentDidMount` or `componentWillMount`

**Comment by joshuapinter** [comment]
Thanks for the response, @ericvicenti!

We need to set the `title`, `headerLeft` and `headerRight` dynamically so we cannot do it in the `static navigationOptions`. We are doing this by calling `setParams` in `componentDidMount`. If we're not supposed to do that, where else would be best? 

Here's a rough example of what we're doing now to give you an idea:

```js
static navigationOptions = ( { navigation } ) => {
  const params = navigation.state.params || {};

  return {
    title:       params.title,
    headerLeft:  params.headerLeft,
    headerRight: params.headerRight
  };
};

componentDidMount() {
  this.props.navigation.setParams( {
    headerRight: (
      <View style={ { flexDirection: "row" } }>
        <EditButton onPress={ this._edit } />
        <AddButton onPress={ this._add } />
      </View>
    ),
    title: this.props.name
  } );
}
```

**Comment by Bonobomagno** [comment]
I have the same use case, how to handle that?

**Comment by joshuapinter** [comment]
@Bonobomagno It works and we're using it as our standard but I'd like to replace it with something better eventually. It tends to mess up the initialization of the component and the mobx store. 

For example, we have to put a fake delay on rendering our screens if `setParams` is called, otherwise some list components don't render.

Use it but be cautious and post back here if you have a better solution.

**Comment by Bonobomagno** [comment]
I see it. I thinks that setParams is called async, so no way to control that...except timebased render delay ofc.
