### ISSUE TITLE
Props in a custom header component 

### ISSUE THREAD

**Issue by Naeoth** [react-navigation/react-navigation#3873]
### Current Behavior

```
const TreasureNav = StackNavigator(
  {
    Screen: { screen: Screen }
  },
  {
    initialRouteName: 'Screen'
  }
);
```

```
export default class Screen extends React.Component {
  static navigationOptions = {
    title: "Screen",
    headerTitle: <CustomHeader />
  }

  render() {
    return (
        .......
    );
}
```

```
export default class CustomHeader extends React.Component {
  render() {
    return (
        <Text>{this.props.children}</Text>
    );
}
```

### Expected Behavior

I read in the doc that the title properties is passed to the header title in the props children : 

> headerTitle
> 
> String, React Element or React Component used by the header. Defaults to scene title. When a component is used, it receives allowFontScaling, style and children props. The title string is passed in children.

I expect to have the title string in `this.props.children` and the other props in my custom header but my props are empty.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.5.8
| react-native     | 0.54.4
| node             | 8.11.1
| npm or yarn      | 5.6.0

**Comment by vonovak** [comment]
if you want to receive the props, you need to pass a React Component, now you're passing an Element. Change 

```js
  static navigationOptions = {
    title: "Screen",
    headerTitle: <CustomHeader />
  }
```


to 

```js
  static navigationOptions = {
    title: "Screen",
    headerTitle: CustomHeader
  }
```
