### ISSUE TITLE
An animation problem with the navigation head?

### ISSUE THREAD

**Issue by geekwill** [react-navigation/react-navigation#3875]
Project USES the react - navigation, there is now a navigation according to the screen and achieve a rolling head gradually into the effect of fading out, don't know how to achieve, and the train of thought is temporarily not ideal I know, how should I at the bottom of the high performance to achieve a similar effect? Thanks for your advice.

![g2qg1-i5dz7](https://user-images.githubusercontent.com/23651539/38169249-c3c07b94-3597-11e8-9dd7-a674f12b6bbb.gif)

**Comment by brentvatne** [comment]
you would want to implement a custom header here. search issues and you can find similar questions and some attempted solutions
