### ISSUE TITLE
How to use NavigationActions.replace?

### ISSUE THREAD

**Issue by pacozaa** [react-navigation/react-navigation#3877]
```javascript 
export const navigateToScreen = (routeName) => NavigationActions.reset({
  index: 0,
  actions: [
    NavigationActions.navigate({ routeName })
  ]
})
```
works fine for me but

```javascript 
export const navigateToScreen = (routeName) => NavigationActions.replace({
  index: 0,
  actions: [
    NavigationActions.navigate({ routeName })
  ]
})
```

I got error `NavigationActions.replace` is not a function.

How to use NavigationActions.replace?

**Comment by JoseIgnacio92** [comment]
check if you have imported

import { NavigationActions } from 'react-navigation';

**Comment by brentvatne** [comment]
also update to the latest version

**Comment by younny** [comment]
@pacozaa Replace action is included in StackActions

Try, import { StackActions } from 'react-navigation'

**Comment by ahmad923245** [comment]
navigation.replace is not function in react native
