### ISSUE TITLE
TabNavigator inside StackNavigator with redux has wrong state when going back to default tab

### ISSUE THREAD

**Issue by SEUH** [react-navigation/react-navigation#3878]
I have a TabNavigator inside a StackNavigator
```
const Nav = StackNavigator( {
    Tabs: {
      screen: TabNavigator({
          home: {
            screen: HomeScreen, ...
          },
          points: {
            screen: PointsScreen,  ...
          },
          account: {
            screen: AccountScreen,  ...
          }
```
Now i have a middleware for my redux store which basically logs me the navigation state

---

### Current Behavior

On my android phone i swipe left (to 'points'), then i swipe right (back to 'home' (default)) which is all displayed correctly but in the navigation state, it says that the tabnavigator is still on index 1.

![image](https://user-images.githubusercontent.com/21090493/38188538-ae4c8314-365c-11e8-818b-450ea4887ed2.png)

### Expected Behavior

Normally the navigation state should change correctly. It only doesn't change if i swipe to the "home" (default) tab.

### How to reproduce

I installed redux, did the [Redux Integration](https://reactnavigation.org/docs/redux-integration.html) 'tutorial' and logged me the navigation state. If there's a need for a replication app i can do one, but it will take some time.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.5.4
| react-navigation-redux-helpers | 1.0.3
| react-redux | 5.0.6

Am i missing something here?

**Comment by brentvatne** [comment]
hi!

i've added a warning to our new docs about redux integration: https://v2.reactnavigation.org/docs/en/redux-integration.html

please don't use it unless you absolutely need it. if you decide after reading the warning that you still would like to use it, please repost your issue to https://github.com/react-navigation/react-navigation-redux-helpers
