### ISSUE TITLE
componentWillReceiveProps does not get triggered upon calling pop/goBack

### ISSUE THREAD

**Issue by sahil290791** [react-navigation/react-navigation#3879]
When we come back to a previous screen, componentWillReceiveProps should be triggered, so that we can check if the screen is focussed or not, but that does not happen.

If this is the desired behaviour is there any other way of knowing if a screen has become active upon **pop/goBack**.

I use flux, so when I leave a screen, I need to remove the listeners from the previous screen so that it does not keep getting updated in background. 

I again need to activate the listeners based on the screen isFocused state. I was relying on `componentWillReceiveProps` in `expo/ex-navigation`, I am currently migrating to react-navigation. So far so good, except this issue.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.5.2
| react-native     | 0.45.1
| node             |  8.9.1
| npm or yarn      | yarn

**Comment by brentvatne** [comment]
this is not a bug, this is expected behavior. the state does not change when you go back. if you need to react to focus see https://reactnavigation.org/docs/with-navigation-focus.html https://reactnavigation.org/docs/navigation-prop.html#addlistener-subscribe-to-updates-to-navigation-lifecycle

**Comment by sahil290791** [comment]
thanks @brentvatne this is what I was looking for, its working now as expected.
