### ISSUE TITLE
missing `key` prop in `NavigationActions.navigate` for Typescript

### ISSUE THREAD

**Issue by jhalborg** [react-navigation/react-navigation#3880]
### Current Behavior
This is an improvement request for the TS typings. 

When navigating to a route using the screen prop `navigation`, the typings correctly propose that an `key` prop can be passed to avoid dublicate navigations to the same route, i.e.:

```
this.props.navigation.navigate({
      routeName: RouteNames.FeedComments,
      key: `${RouteNames.FeedComments}${mediaID}`,
      params: {
        tab: NavigationTabNames.FEED,
        id: mediaID,
      },
    });
```

However, when dispatching a similar action without using the screen prop `navigation` but instead, for example, dispatching the action in redux, `key` is not a recognized prop. I.e. 

```
NavigationActions.navigate({
      routeName: route,
      params,
      // @ts-ignore
      key: route,
    })
```

It does, however, still work. 

### Expected Behavior

`key` should be a recognized prop for Typescript

### How to reproduce
Use `react-navigation` v 1.5.2 and the typings for this version, try to dispatch `NavigationActions.navigate` with a `key` prop. 

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.5.2
| react-native     | 0.51.0
| node             | 8.9.4
| npm or yarn      | (yarn) 1.5.1

**Comment by brentvatne** [comment]
we don't support typescript type definitions. these are maintained by the community. https://github.com/react-navigation/rfcs/issues/34
