### ISSUE TITLE
pan responder collisions, react-native-gesture-handler integration?

### ISSUE THREAD

**Issue by elwhitman** [react-navigation/react-navigation#3881]
I'm having pan responder collisions where two downward drag listeners are being fired, where I need to put a `waitFor` on one of them for a specific state. how would I go about getting this done? can the react-native-gesture-handler API be exposed here for this purpose?

**Comment by brentvatne** [comment]
we will integrate rngh in the future. for now we don't support this, sorry

**Comment by erickreutz** [comment]
@brentvatne any timeline on integrating rngh?
