### ISSUE TITLE
tabBarOptions.style bug on iPhone X

### ISSUE THREAD

**Issue by TheDutchCoder** [react-navigation/react-navigation#3882]
### Current Behavior

The tabBarOptions work fine, but the styling is incorrect on the iPhone X, leaving a big gap at the bottom.

![image](https://user-images.githubusercontent.com/1668207/38200910-365b7b50-3664-11e8-9884-631889b3a43b.png)

![image](https://user-images.githubusercontent.com/1668207/38200927-4501772c-3664-11e8-9b48-485fed4ec997.png)

### Expected Behavior

Styling should be the same as on all other devices (it is the same on other tested devices (iPhone 5, 5s, 6, 6s)

### How to reproduce

Style a `TabNavigator` on different devices setting a specific height.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0
| react-native     | 0.53.0
| node             | 4.8.2
| npm or yarn      | 4.6.1

**Comment by TheDutchCoder** [comment]
Interestingly enough, this is the default styling on multiple devices, almost looks like the iPhone X is the *only one* to have proper default styles?

![image](https://user-images.githubusercontent.com/1668207/38201186-567ea582-3665-11e8-82fb-40aab04971f7.png)

**Comment by brentvatne** [comment]
this is intentional and the result of using a SafeAreaView, it exists because by default you want to render the tab content above the home indicator. https://github.com/react-navigation/react-navigation/blob/cbe46d7303199ee608764bb80ee294cd1c24b18e/src/views/TabView/TabBarBottom.js#L234-L237

see more info at https://developer.apple.com/ios/human-interface-guidelines/overview/iphone-x/

you might want to fork the TabBarBottom component and remove this if it isn't needed for your UI.

**Comment by TheDutchCoder** [comment]
Okay fair enough, so there's no way to override this behavior?

Our app doesn't have the tabBar as the "last" (bottom most) component and we use the `SafeAreaView` as a wrapper around the entire screen.

**Comment by TheDutchCoder** [comment]
I'm also of the opinion that wrapping a single component in a `SafeAreaView` is not correct. React Native recommends wrapping your top-level view in it (which makes sense, and takes care of everything already): https://facebook.github.io/react-native/docs/safeareaview.html

This is the way we use it.

I don't think individual components should be wrapper in it.

**Comment by brentvatne** [comment]
@TheDutchCoder - we don't use that component and also that is incorrect for various reasons :O

**Comment by TheDutchCoder** [comment]
@brentvatne Oh... I'm just trying to understand this: the React Native advice/guideline on `SafeAreaView`(which is a RN component) is actually incorrect?

I thought it was just a wrapper around top-level views that prevents inner components from flowing into things like the status bar and sensor areas.

I can see how the tabBar uses it as it assumes it's always at the bottom (as per Apple's guidelines), though a user should be free to use it as they see fit (our tabBar is actually part of a nested view, therefore not the bottom most part on the screen).

Maybe I'm better off not using the tab navigation then and just writing my own simple component for it, I really only need to show different content on each tab which I can probably do with a very minimal custom component.

**Comment by brentvatne** [comment]
>  Oh... I'm just trying to understand this: the React Native advice/guideline on SafeAreaView(which is a RN component) is actually incorrect?

it only describes the most basic case. it is incorrect insofar as it does not explain when you might not actually want to do that in most cases and it doesn't explain this.

**Comment by naiger** [comment]
By using forceInset={{ bottom: "never"}}, the big gap issue solved on my device.

<SafeAreaView style={styles.safeArea} forceInset={{ bottom: "never"}}>
  { youCode}
</SafeAreaView>

**Comment by vandrieu** [comment]
```
export default createBottomTabNavigator(
	{
		// your routes
	},
	{
		navigationOptions: ({ navigation }) => ({
			//your navigation options
		}),
		tabBarOptions: {
			activeTintColor: '#3498db',
			inactiveTintColor: 'black',
			activeBackgroundColor: 'white',
			inactiveBackgroundColor: 'white',
			**safeAreaInset: { bottom: 'never', top: 'never' }  // <-- this is the solution**
		},
	}
);

```

**Comment by canhtran10** [comment]
https://github.com/canhtran10/react-navigation-oslo/blob/master/README.md

**Comment by GuidoGagliardini** [comment]
> ```
> export default createBottomTabNavigator(
> 	{
> 		// your routes
> 	},
> 	{
> 		navigationOptions: ({ navigation }) => ({
> 			//your navigation options
> 		}),
> 		tabBarOptions: {
> 			activeTintColor: '#3498db',
> 			inactiveTintColor: 'black',
> 			activeBackgroundColor: 'white',
> 			inactiveBackgroundColor: 'white',
> 			safeAreaInset: { bottom: 'never', top: 'never' }  // <-- this is the solution
> 		},
> 	}
> );
> ```

i worked for me.
```
    "react": "18.1.0",
    "react-native": "0.70.6",
```
I just had to implement it like this

```
<Tab.Navigator
          initialRouteName="HomeTab"
          safeAreaInsets={{bottom:0,top:0}} //  **ADD THIS LINE** 
          screenOptions={{
            tabBarShowLabel: false,
            tabBarStyle: style.tabsBottomContainer,
            tabBarHideOnKeyboard: true,
            tabBarIconStyle: style.iconTabs,
            unmountOnBlur: true, 
            headerShown: false,
          }}
          screenListeners={{
            tabPress: e => {
              if (e.target?.includes('Asset')) {
                navigation.dispatch(
                  CommonActions.navigate({
                    name: 'Assets',
                    params: {},
                  }),
                );
              }
            },
          }}>
          <Tab.Screen
            name="Assets"
            component={AssetsStack}
            initialParams={{
              screen: 'ListAsset',
              params: {type},
            }}
            options={{
              tabBarIcon: ({focused, color}) => (
                <View>
                  <Image
                    source={iconAsset}
                    style={{
                      tintColor: focused ? '#00B2DF' : '',
                      marginTop: 8,
                    }}
                  />
                </View>
              ),
            }}
          />
          <Tab.Screen
            name="ConnectGateway"
            component={ConnectGatewayStack}
            options={{
              tabBarIcon: ({focused, color}) => (
                <View>
                  <Image
                    source={iconBluetooth}
                    style={{
                      tintColor: focused ? '#00B2DF' : '',
                    }}
                  />
                </View>
              ),
            }}
          />
        </Tab.Navigator>
```
