### ISSUE TITLE
Using new React Context API throws Warnings

### ISSUE THREAD

**Issue by smithaitufe** [react-navigation/react-navigation#3884]
### Current Behavior

- I am trying to use the new React Context API. After my ThemeProvider and ThemeContext, I added the ThemeProvider to my app as can been seen below
```js
<ApolloProvider client={client}>
        <ThemeProvider>          
          <View style={styles.statusBar}>
            <StatusBar backgroundColor={"transparent"} translucent />
          </View>
          <Screens />
        </ThemeProvider>
      </ApolloProvider>
```
And then in one of my component, I added the ThemeConsumer

```
<ThemeConsumer>
                {({ state, actions }) => (
                    <View style={{backgroundColor: state.theme.primaryBackground}}>
                        <TouchableHighlight>
                            <View><Text>Resellers</Text></View>
                        </TouchableHighlight>
                    </View>
                )}
            </ThemeConsumer>
```

### Expected Behavior

I expected the App to work smoothly. However that is not the case. I am seeing the following warnings

__Warning: componentWillMount is deprecated and will be removed in the next major version. Use componentDidMount instead. As a temporary workaround, you can rename to UNSAFE_componentWillMount. Please update the following components Container, Transitioner__

__Warning: componentWillRecieveProps is deprecated and will be removed in the next major version. Use static getDerivedStateFromProps instead. Please update the following components: CardStack, Container, NavigationContainer, QueryRecyclerProvider, SafeView, Transitioner___

__Warning: isMounted(...) is deprecated in plain Javascrpt; React classes instead make sure to clean up subscriptions and pending requests in componentWillMount to prevent memory leaks__

### Environment

| software         | version
| ---------------- | -------
|react-navigation | 1.1.1
|react-native| 0.55.0-rc.2
|react| 16.3.0
|node| 8.9.1

**Comment by tlvenn** [comment]
Hi @smithaitufe,

I don't think this is related specifically to the new context API, it just happens that the new React release (16.3.0) that the latest RN is pulling has deprecated a few lifecycle methods and the latest RN version as well as the eco system around it have yet to catch up with this.

As stated in the RN release note:
>Lifecycle methods were renamed to be consistent with React RFC6 – note that there are Yellowbox warnings right now because of this, it's work-in-progress.

**Comment by smithaitufe** [comment]
Hi @tlvenn

Thanks. So what do you recommend?

**Comment by smithaitufe** [comment]
As seen from the warning messages above, these are warnings aren't coming from my components but from react navigation. 

How do I fix them?

The fix should come from top to bottom, meaning the life cycle methods of react navigation components should be worked on.

Or do I not understand the warnings?

**Comment by timwangdev** [comment]
This are just deprecation warning. Those method will continue working before react 17.0. You can safely ignore them by using `YellowBox.ignoreWarnings(['Warning: componentWill'])` for now.

You can always submit PR if you want to help `react-navigation` to fix this problems.

**Comment by jsina** [comment]
I've get the same warning with below dependencies, 
```
 "dependencies": {
    "prop-types": "^15.6.1",
    "react": "16.3.1",
    "react-native": "0.55.2",
    "react-navigation": "^1.5.11"
  },
```
