### ISSUE TITLE
"lazy":"false" doesn't work for TabNavigator on iOS

### ISSUE THREAD

**Issue by ruslan-bikkinin** [react-navigation/react-navigation#3885]
### Current Behavior
Looks like `"lazy":"false"` doesn't work for TabNavigator anymore (it does on android though).
This simple example illustrates the issue:
```js
import React, { Component } from 'react';
import {
  Platform,
  StyleSheet,
  Text,
  View
} from 'react-native';
import { TabNavigator } from 'react-navigation';

class Page1 extends Component {
  render() {
    return (
      <View style={{flex: 1, backgroundColor: "green", justifyContent:"center"}}>
        <Text>page 1</Text>
      </View>
    );
  }
}

class Page2 extends Component {
  render() {
    return (
      <View style={{flex: 1, backgroundColor: "green", justifyContent:"center"}}>
        <Text>page 2</Text>
      </View>
    );
  }
}

const RootTabNavigator = TabNavigator(
  {
    page1: {
      screen: Page1,
    },
    page2: {
      screen: Page2,
    }
  },
  {
    initialRouteName: 'page1',
    navigationOptions: {
      swipeEnabled: true,
      animationEnabled: true
    },
    lazy: false,
  }
);

export default class App extends Component{
  render() {
    return (
      <RootTabNavigator />
    );
  }
}
```
 What I get when I am swiping from page1 to page2 in iOS..:

![image](https://user-images.githubusercontent.com/30265843/38206406-f9a318ea-36b2-11e8-90d7-2a1b5e239ced.png)

... and what I get on android:

![image](https://user-images.githubusercontent.com/30265843/38206435-1479e75c-36b3-11e8-8eea-2a7e85f81372.png)

### Expected Behavior

Swiping on iOS should behave the same as on android.

### How to reproduce

1. Clone my repo (it generated via `react-native init`): https://github.com/ruslan-bikkinin/react-nav-repro
2. Run `npm i` inside project directory and then run `react-native run-ios` or `react-native run-android`

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |1.5.9
| react-native     | 0.54.4
| node             | 8.9.4
| npm or yarn      | npm v5.6.0

**Comment by ruslan-bikkinin** [comment]
Changing tabBarOptions to 
```js
  {
    initialRouteName: 'page1',
    navigationOptions: {
      animationEnabled: true
    },
    lazy: false,
    swipeEnabled: true,
  }
```
fixed my issue.

**Comment by anastely** [comment]
@ruslan-bikkinin  it does not work for me!
