### ISSUE TITLE
Transition between screen with header and  headerless tab screen jerks

### ISSUE THREAD

**Issue by cbjs** [react-navigation/react-navigation#3889]
code
```js
const Home = TabNavigator({
  boards: { screen: ScrollTabBoards },
  explore: { screen: Explore },
  message: { screen: Message },
  profile: { screen: Profile }
}, {
  initialRouteName:'boards',
  tabBarPosition: 'bottom',
  animationEnabled: false,
  lazy: true
});

const RootNavigator = StackNavigator({
  home: {
    screen: Home, 
    path: '/', 
    navigationOptions: { 
        header: null,
        gesturesEnabled: false 
    } 
  },
  article: {screen: PostDetail, path: '/article/:board/:id' },
}, {
  initialRouteName: 'home'
})
```

this issue only exists on ios platform.
home boards screen has no header( set header = null), while article screen has a header.

screenshot

home boards screen to article screen
![home2article](https://user-images.githubusercontent.com/1215843/38262745-c579401e-37a0-11e8-91b1-71b3241893ed.gif)

go back from article screen to home boards screen
![article2home](https://user-images.githubusercontent.com/1215843/38262772-d5186d9c-37a0-11e8-88c9-149154d80850.gif)

**Comment by brentvatne** [comment]
resolved in 2.0 but thanks for the report! we're working on getting that ready for release within the next couple of weeks
