### ISSUE TITLE
docs: Clarify a common gotcha of StackNavigator inside DrawerNavigator. ex-navigation

### ISSUE THREAD

**Issue by skabbes** [react-navigation/react-navigation#3890]
This is a documentation bug.

_Using multiple Navigators inside a DrawerNavigator, where the subnavigators shared a route name, led to unexpected (undocumented) behavior_

| software | version
| -- | --
| react-navigation | 1.5.9
| react-native | expo@26

## Context
I was an early user of @expo/ex-navigation, and have recently been upgrading to react-navigation.  I came across some faults in either the DrawerNavigation documentation or in the general mental framework of react-navigation.

## Current Behavior
When nesting navigators inside a DrawerNavigator, duplicated route names behave unexpectedly (in my mental model).
[Expo Snack repro](https://snack.expo.io/ByWqlS-jG)

```javascript
const WidgetStack = StackNavigator({
  Widget: {
    screen: WidgetScreen,
  },
  // This is very easy to get wrong, it is not clear in the Drawer documentation
  // that this route name should be distinct.
  Settings: {
    screen: SettingsScreen,
  },
});

const SettingsStack = StackNavigator({
  Settings: {
    screen: SettingsScreen,
  },
});

const DrawerApp = DrawerNavigator({
  Widget: {
    screen: WidgetStack,
  },
  Settings: {
    screen: SettingsStack,
  },
}, {
  initialRouteName: 'Widget',
});
```

When tapping on the "Settings" drawer item, I expected the currently selected "tab" in the drawer to be "Settings", I expected no routes to be "pushed" onto my stack navigator.  Instead, the "widget" tab stays selected, and a settings route is pushed onto the WidgetStack.

There were no pieces of documentation to warn me of this behavior, and it was actually very difficult to even tell this is what was happening (it was much easier when I decided to build the minimal repro).

## My current mental model
My mental model for react-navigation was previously that each nested navigator was a "subtree".  With that model, I saw no issue with a duplicated route name.

```
               DrawerApp
	      /         \
	  WidgetStack    SettingsStack
          |     |	       |
	  /      \           Settings
	Widget   Settings
```

I'm not here to debate whether this is the correct model, but a simple piece of documentation would have saved me about an entire day :(

I would be happy to submit a PR to address this, but it appears with the [2.0 push](https://github.com/react-navigation/react-navigation/pull/3618), this might be out of date, and furthermore - I am not sure if my current model is correct enough to even write docs.

**Comment by brentvatne** [comment]
moved this to https://github.com/react-navigation/react-navigation.github.io/issues/117 -- let's discuss there
