### ISSUE TITLE
newKey param in StackNavigator replace

### ISSUE THREAD

**Issue by aknad** [react-navigation/react-navigation#3892]
StackNavigator [replace](https://reactnavigation.org/docs/navigation-prop.html#replace) should handle _newKey_ param as the NavigationActions [Replace](https://reactnavigation.org/docs/navigation-actions.html#replace) does
In the StackRouter source code the [newKey is used](https://github.com/react-navigation/react-navigation/blob/master/src/routers/StackRouter.js#L387)
`key: action.newKey || generateKey(),`

but the [action creator](https://github.com/react-navigation/react-navigation/blob/master/src/routers/StackRouter.js#L176) doesn't handle it
`replace: (routeName, params, action) => ({`

**Comment by ericvicenti** [comment]
Addressing as a part of https://github.com/react-navigation/react-navigation/pull/3906
