### ISSUE TITLE
focus / blur events not fired when using getStateForAction

### ISSUE THREAD

**Issue by pensierinmusica** [react-navigation/react-navigation#3893]
Hi,

I'm using React Navigation integrated with Redux. I've noticed that the focus / blur events are not fired when I change route using `getStateForAction`.

For example let's imagine a reducer that returns this:

```js
const newState = AppNavigator.router.getStateForAction(NavigationActions.back(args), state);
```

Is such usage expected to not fire a focus event for the route it lands in, or is it due to a bug?

Thanks!

**Comment by ericvicenti** [comment]
`getStateForAction` is a pure function, which means it cannot have side effects. This is used to help make things easier to understand and optimize inside the library.

The top level action event and `addListener` is something that redux users are responsible for, but there are a set of official middlewares to handle this for you. Please look into the redux guide here: https://reactnavigation.org/docs/redux-integration.html#docsNav

https://github.com/react-navigation/react-navigation-redux-helpers

**Comment by dnmsk** [comment]
@pensierinmusica You need to connect nav props to navigation component. Check the example https://reactnavigation.org/docs/redux-integration.html#docsNav in
on row `const AppWithNavigationState = connect(mapStateToProps)(App);`
This is works for me.

**Comment by pensierinmusica** [comment]
@dnmsk I've done that already. Have you tried [the code I posted above](https://github.com/react-navigation/react-navigation/issues/3893#issue-311041929) and it works for you with a `didFocus` listener?

**Comment by jsina** [comment]
@pensierinmusica I have the exact provle. Have you find any solution for it?

**Comment by pensierinmusica** [comment]
@jsina nope.

**Comment by Ashoat** [comment]
`react-navigation-redux-helpers@1.1.1` introduces a new export called `createDidUpdateCallback` that should fix this issue. Refer to the [docs](https://github.com/react-navigation/react-navigation-redux-helpers) for how it's used.
