### ISSUE TITLE
Double tapping doesn't make the active navigation stack pop to the top of the stack

### ISSUE THREAD

**Issue by feliperaul** [react-navigation/react-navigation#3896]
### Expected Behavior

Docs state that "Double tapping the tab bar should make the active navigation stack pop to the top of the stack, and doing it again should scroll the active scroll view in that stack scroll to the top". But double tapping is not triggering that behavior. (source: https://reactnavigation.org/docs/tab-based-navigation.html)

### How to reproduce

Just double tab any tab icon while the tab is active showing a screen that is not the main screen of that stack. Nothing happens, while it was expected to navigate back to the top of the stack. 

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.27
| react-native     | expo/react-native/archive/sdk-25.0.0.tar.gz

**Comment by wvteijlingen** [comment]
Not sure what is and what isn't implemented, but the docs also say:

> While not all of these behaviors are implemented out of the box yet with React Navigation, they will be and you will not get any of this if you use a standalone tab view component.

So possibly this is not implemented at the moment.

**Comment by brentvatne** [comment]
@ericvicenti - this is already implemented. @feliperaul - you're using a very old version of react-navigation. update to 1.5.9 and you will find that it works as expected

**Comment by AndroConsis** [comment]
@brentvatne I am using createBottomTabNavigator and this functionality is not working in 
`react-navigation: 3.11.0,
  react-native: 0.59.6`
