### ISSUE TITLE
componentWillMount is deprecated now

### ISSUE THREAD

**Issue by douglasjunior** [react-navigation/react-navigation#3897]
See https://reactjs.org/docs/react-component.html#unsafe_componentwillmount

**Comment by gertvdkolk** [comment]
As [this](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html) page states, developers not yet have to directly change all the lifecycle methods. This can be done over a period of time.

>Note that if you’re a React application developer, you don’t have to do anything about the legacy methods yet. The primary purpose of the upcoming version 16.3 release is to enable open source project maintainers to update their libraries in advance of any deprecation warnings. Those warnings will not be enabled until a future 16.x release.

**Comment by ericvicenti** [comment]
Thanks, this is super easy to fix in react-navigation. Will fix soon

**Comment by ericvicenti** [comment]
https://github.com/react-navigation/react-navigation/pull/3903

**Comment by douglasjunior** [comment]
Thanks for the library.

**Comment by douglasjunior** [comment]
Just to inform, all `componentWill*` events have been deprecated.

See the prefix `UNSAFE_` => https://reactjs.org/docs/react-component.html

**Comment by f3ist** [comment]
@ericvicenti The android back documents need to be updated too

https://reactnavigation.org/docs/custom-android-back-button-handling.html
