### ISSUE TITLE
TabBarBottom broken on iPad iOS 10

### ISSUE THREAD

**Issue by avertin** [react-navigation/react-navigation#3904]
### Current Behavior

On iPad iOS 10 the icons in the bottom navigation bar look broken. Does not affect iPhone, Android or devices running iOS 11. 

![screen shot 2018-04-04 at 3 29 50 pm](https://user-images.githubusercontent.com/11411307/38338135-10548db0-381d-11e8-8d2d-3b68654a6eef.png)

### Expected Behavior

iPad icon and iPhone icons should look the same for iOS 10. 

Related: (#3712) and (#3704) although both were fixed for iOS **11**

### How to reproduce

Run `exp init` and choose tabs type of project. Then run the app on an iOS 10 simulator (or real iPad).

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  1.5.8
| react-native     | 0.52.2
| node             | 9.6.0
| npm or yarn      | yarn 1.5.1

**Comment by brentvatne** [comment]
install react-navigation@1.5.9 and let me know if this resolves the issue for you

**Comment by avertin** [comment]
Installing react-navigation@1.5.9  did not resolve the issue.

**Comment by brentvatne** [comment]
thank you for catching this issue! apologies for all of the back and forth on here, I'll push a fix very shortly

**Comment by brentvatne** [comment]
react-navigation@1.5.10 should do the trick

**Comment by avertin** [comment]
That fixed it, thanks!
