### ISSUE TITLE
How to use Tabnavigator to change tab contnet

### ISSUE THREAD

**Issue by Periclessan** [react-navigation/react-navigation#3908]
My project mainly using tab for navigation and could like to modify the tab content. But I can't make change in tab navigation.
My Router is:
Stacknavigation:
Home screen -- StackNavigator
----One screen (Tab) --TabNavigator
----Two screen (Tab) --TabNavigator
Profile screen -- StackNavigator
----Three screen (Tab) --TabNavigator
----Home screen (Tab) --TabNavigator

When I click Home screen (Tab) at Profile screen, it go to Home screen, but the Tab content dose not change to 'One screen (Tab)' and Two screen (Tab).

I don't know how to write the code.

**Comment by brentvatne** [comment]
hi there! this is a question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.
