### ISSUE TITLE
Npm install issue 

### ISSUE THREAD

**Issue by mhaneef50673** [react-navigation/react-navigation#3910]
When I try to install react-navigation, it throws me the following error

npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:211:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:885:16)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
npm WARN addRemoteGit  react-navigation/react-native-tab-view resetting remote C:\Users\BATHUMO\AppData\Roaming\npm-cache\_git-remotes\git-github-com-react-navigation-react-native-tab-view-git-9747c439 because of error: { Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:211:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:885:16)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }

I have added the following lines in .gitconfig as well:

[core]
	longpaths = true
[url "https://"]   
    insteadOf = git://	

| software         | version
| ---------------- | -------
| react-navigation | 
| react-native     | 0.54.2
| node             | 7.2.1
| npm or yarn      |3.10.10

**Comment by brentvatne** [comment]
might want to google these errors related to git. this isn't related to react-navigation, we use a git repo url in package.json and we expect that this will just work on your machine (as it should) or that you can debug it if not
