### ISSUE TITLE
Can't use the new headerBackImage

### ISSUE THREAD

**Issue by luco** [react-navigation/react-navigation#3911]
I'm trying to use the new headerBackImage as proposed in this pull request, #3680. However, I can't make it work.

```
class MyCustomHeaderBackImage extends React.Component<any, any> {
  render() {
    const source = require('../images/back-icon.png');
    return (
       <Image source={source} style={{width: 50, height: 50}} />
    );
  }
}
```

```
export const NavConfig = {
 headerBackImage: MyCustomHeaderBackImage,
 ...
}
```

It returns me this warning and doesn't render the button. 

![image](https://user-images.githubusercontent.com/246373/38366065-009f83d2-38b5-11e8-86e0-e3d76cb20a8a.png)

Thoughts?
Thanks

**Comment by brentvatne** [comment]
`headerBackImage` as a component only exists on 2.0 branch, on 1.x you need to pass in a source. https://reactnavigation.org/docs/stack-navigator.html#headerbackimage

**Comment by luco** [comment]
@brentvatne Is there a 2.0 release date?

**Comment by brentvatne** [comment]
you can use the beta version now if you want! we'll release it when we feel it's stable enough and ready for production use
