### ISSUE TITLE
header onPress

### ISSUE THREAD

**Issue by cbjs** [react-navigation/react-navigation#3913]
scroll to top of list while header is pressed.

```
static navigationOptions = ({navigation}) {
   const { title, onPress } = navigation.state.params;
   return {
      title,
      header: <TouchableWithoutFeedback onPress={onPress}>
        <Header/>
      </TouchableWithoutFeedback>
   }
}
```

onPress is not invoked. 1.5.9
it works in 1.0.0-beta.12

**Comment by terrysahaidak** [comment]
@cbjs have you tried to wrap your header component into the function?

```
header: () => (
	<TouchableWithoutFeedback onPress={onPress}>
		<Header/>
	</TouchableWithoutFeedback>
)
```

This might help. Also, I had some issues with TouchableWithoutFeedback where onPress wasn't invoked for some reason. Replacing by TouchableOpacity might help you.

**Comment by cbjs** [comment]
@terrysahaidak thanks~, replacing with TouchableOpacity works.
It may be a bug of react-native.
