### ISSUE TITLE
Connect DrawerNavigator not to root component.

### ISSUE THREAD

**Issue by ybaidiuk** [react-navigation/react-navigation#3917]
Hello !
I wont initi DrawerNavigator in my already existing Component  (\<Main/>)?
I found how can i do it with the root component App, but:
 if i write "export default DrawerNav... etc..." in Main.js  
and init  it as \<Main/>  in previos componnet its not work ;

**Comment by brentvatne** [comment]
hi there! this is a question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.
