### ISSUE TITLE
effect of pressing?

### ISSUE THREAD

**Issue by eeeman1** [react-navigation/react-navigation#3921]
hello to all connoisseurs, how do I make a click effect for my own button like the tab menu items?

![new project](https://user-images.githubusercontent.com/26044998/38411935-dedb1d06-3990-11e8-97fb-0408539f4b11.jpg)

**Comment by brentvatne** [comment]
https://facebook.github.io/react-native/docs/touchablenativefeedback.html on android only or https://callstack.github.io/react-native-paper/touchable-ripple.html if you want on both platforms
