### ISSUE TITLE
Missing export of addNavigationHelpers in v2 rc1

### ISSUE THREAD

**Issue by MrLoh** [react-navigation/react-navigation#3930]
Reporting as asked in https://twitter.com/reactnavigation/status/982667759543664640?s=21

Somehow the release candidate of v2 doesn’t export the `addNavigationHelper` function anymore. It simply a missing line in `src/react-navigation.js` I couldn’t find any alternative for setup up a redux integration and it’s still mentioned in the v2 docs.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by derekbar90** [comment]
You can import via `import addNavigationHelpers from 'react-navigation/src/addNavigationHelpers';`

**Comment by brentvatne** [comment]
cc @ericvicenti

**Comment by MrLoh** [comment]
The redux integration works fine otherwise. There’s just no export of the helper as described in the docs anymore. Not sure what the reasoning for removing it was. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by derekbar90** [comment]
@brentvatne You do the same integration as before just add the import from where I referenced it.

**Comment by ericvicenti** [comment]
You shouldn’t need it anymore! If you pass in “dispatch”, you don’t need to add helpers at the top level

**Comment by mgscreativa** [comment]
As @patw0929 states,. what's the correct way to remove `addNavigationHelpers`?

**Comment by mgscreativa** [comment]
Cool! thank you!

**Comment by dhazlettjr** [comment]
Can someone give me an example of this solution??

**Comment by mohamadswaidan** [comment]
just do as @derekbar90 and should works fine

**Comment by derekbar90** [comment]
@mohamadswaidan actually I was wrong and found you can just put a bare object like this: 

`render () {
    const navigation = {
      dispatch: this.props.dispatch,
      state: this.props.nav,
      addListener: REACT_NAVIGATION_LISTENER
    };

    return <AppNavigation navigation={navigation}/>;
  }`

FYI: 

REACT_NAVIGATION_LISTENER = createReduxBoundAddListener('root');

**Comment by a-koka** [comment]
`createReduxBoundAddListener` is deprecated in `2.0.2`. What is the recommendation to get around this problem?

**Comment by derren7532123** [comment]
Hi Guys anyone can provide solution for this addreduxhelper:
import React from 'react'
import * as ReactNavigation from 'react-navigation'
import { connect } from 'react-redux'
import MixedNavigation from './MixedNavigation'

// here is our redux-aware our smart component
function ReduxNavigation (props) {
const { dispatch, nav } = props
const navigation =({
dispatch,
state: nav
})

return 
}

const mapStateToProps = state => ({ nav: state.nav })
export default connect(mapStateToProps)(ReduxNavigation)

**Comment by NoahSong** [comment]
@derren7532123 Have you solved this issue??
