### ISSUE TITLE
(0 , _reactNativeNavigation.StackNavigator) is not a function

### ISSUE THREAD

**Issue by StudioAleph** [react-navigation/react-navigation#3932]
Root.js Codes =>

import React, { Component } from 'react';
import { StackNavigator } from 'react-native-navigation';
import Login from './components/login';

const RootNavigator=StackNavigator({
  Login2:{
    screen:Login,
  }
});

export {RootNavigator};

App.js Codes

import React, { Component } from 'react';
import {
  Platform,
  StyleSheet,
  Text,
  View
} from 'react-native';
import { RootNavigator } from './src/Root';

export default class App extends Component<Props> {
  constructor(props)
	{
		super(props);
	}

  render() {

    return (
      <View style={{flex:1}}>
         <RootNavigator />
      </View>
    );
  }
}
![2018-04-08_16-29-19](https://user-images.githubusercontent.com/38176913/38467204-278e50b2-3b4a-11e8-961c-b6fd0643feb7.jpg)

how can I solve this issue ???

**Comment by brentvatne** [comment]
`react-native-navigation`

**Comment by anilkumar1505** [comment]
Same problem i am facing now. I added package name" like react-navigation"
still problem exist.
