### ISSUE TITLE
Just upgraded to react native 55 and the initial screen of tab navigator fails to load

### ISSUE THREAD

**Issue by THPubs** [react-navigation/react-navigation#3933]
I just upgraded to the latest react-native version and the tab navigator stopped working as intended. Usually when the app loads, it should look like this:

<img width="458" alt="screen shot 2018-04-09 at 9 45 27 am" src="https://user-images.githubusercontent.com/1212023/38479165-f43030d2-3bda-11e8-8ecc-bf3a89c1a5ef.png">

But now it looks like this:

<img width="450" alt="screen shot 2018-04-09 at 9 45 11 am" src="https://user-images.githubusercontent.com/1212023/38479174-fd00c974-3bda-11e8-852a-f6c8637a7a06.png">

The code looks like this:

    const AppNavigator = TabNavigator(
      {
        PatientNavigator: {
          screen: PatientNavigator
        },
        Scan: {
          screen: ScanNavigator
        },
        Settings: {
          screen: SettingsNavigator
        }
      },
      {
        animationEnabled: true,
        initialRouteName: 'Scan',
        headerMode: 'none',
        tabBarOptions: {
          inactiveTintColor: '#bbbbbb',
          activeTintColor: '#fff',
          labelStyle: {
            fontSize: 13,
            marginBottom: 5,
            marginTop: 0,
            fontFamily: 'Quicksand-Medium'
          },
          style: {
            backgroundColor: '#4d87ee',
            borderWidth: 0,
            borderTopColor: 'transparent',
            shadowOpacity: 0.6,
            shadowRadius: 4,
            shadowColor: '#212121',
            shadowOffset: {
              width: 0,
              height: 0
            }
          }
        }
      }
    );

If I switch to another screen and come back it loads correctly. Any idea what's happening?

**Comment by lwansbrough** [comment]
I had this issue in React Native 0.54 and upgrading to 0.55 fixed it. Are you on the latest version? I'm on 2.0.0-rc1 which seems to work nicely.

**Comment by THPubs** [comment]
Im in react native 55. But on react-navigation 1.5.11

**Comment by lwansbrough** [comment]
I wouldn't be too surprised seeing bugs in that case. The React API is changing in React 16.3 / React Native 55 and there may be unexpected problems there. Might be necessary to update react-navigation.

**Comment by brentvatne** [comment]
also are you using redux integration? I would imagine so, as this issue only seems to occur in that case

**Comment by THPubs** [comment]
Thanks @lwansbrough Just downgraded react native to `54` and now it's working! React navigation 1.5.11 seems to be working. But the version 2.0.0 does not!

@brentvatne No I'm not using redux integration 😀

**Comment by brentvatne** [comment]
interesting, thanks. I have no idea what could have changed in 55 to cause this behavior, if you have time to create a [mvce](https://stackoverflow.com/help/mcve) it would be appreciated!

**Comment by THPubs** [comment]
@brentvatne Sure I will do it as soon as I get some time 👍

**Comment by banaszeknorbert** [comment]
Do you have a working solution for apps with redux integration? I tried lot of different versions and still no effect :( I have SwitchNavigation with three Stack Navigations. First screen from each stack is normal, others are covered with black layer, all content is invisible but clickable.
