### ISSUE TITLE
why goBack is implemented as "goBackFrom" instead of "goBackTo"?

### ISSUE THREAD

**Issue by kdong007** [react-navigation/react-navigation#3937]
Personally I feel this is a bit anti-social...

I have screen pattern like 
A=>B=>Z
A=>C=>Z
A=>D=>Z
A=>whatever other screens =>Z

But I need transition from Z to A. basically I have to track all possible screens that is after screen A and retrieve "goBackFrom" key before jump.

Now things get even worse, we are adding a screen Z2, which have similar route transitions like Z. 
Does anyone have a forked repo or some sort of work-around to do "goBackTo" ?

**Comment by brentvatne** [comment]
you can use `navigate` to go back to a specific screen.

`navigate({routeName: 'SomeRoute', key: 'somekey'})` or on 2.x branch if you didn't explicitly provide a key `just `navigate('SomeRoute')` would work

**Comment by brentvatne** [comment]
I'll close this issue as I believe this answers the question, if you have more concerns about it please open a RFC issue or PR https://github.com/react-navigation/rfcs

**Comment by dblachut-adb** [comment]
> you can use navigate to go back to a specific screen.

@brentvatne the thing is that if you have some nested navigators using `navigate` always may create loops. The screens are pushed on the stack on and on, and they are never released/unmounted, you can use back button on android to get back to them. In that case after some time the device runs out of memory. Without `goBackTo` you must reset the navigation as a workaround.

@kdong007 I faced similar issue and I have written my own `goBackTo` with `scanNavigationHistory(navigationState, routeNameToFind)` utils function that is trying to find route given by an argument in navigation history (`navigationState`). Unfortunately I cannot share the code.

**Comment by brentvatne** [comment]
> the thing is that if you have some nested navigators using navigate always may create loops. The screens are pushed on the stack on and on, and they are never released/unmounted, you can use back button on android to get back to them. In that case after some time the device runs out of memory. Without goBackTo you must reset the navigation as a workaround.

I think you misread my comment, please read the RFC I linked to and re-read comment more carefully

**Comment by dblachut-adb** [comment]
I see thank you. I am not sure where should I find the `key` of the route and how it is assigned though.
