### ISSUE TITLE
How can use navigation on const

### ISSUE THREAD

**Issue by StudioAleph** [react-navigation/react-navigation#3953]
I import StudentDetails const to showstuden.js but my problem is when I want to use onPress={this.navigation.navigate('somewhere')} in StudentDetails the simulator says cannot read property 'navigation' of undefined

## showstudent .js
![2018-04-11_11-41-43](https://user-images.githubusercontent.com/38176913/38601594-672b8c3c-3d7d-11e8-851a-c30ff5c8a854.jpg)

`import React, { Component } from 'react';
import {
  Platform,
  StyleSheet,
  Text,
  View,
  ListView,
  ActivityIndicator,
  TouchableOpacity
} from 'react-native';
import {Header} from './index';
import axios from 'axios';
import StudentDetail from './StudentDetails';

class ShowStudent extends Component<Props> {
  constructor(props){
    super(props);
    this.state={
      Info:[],
      isLoading:true
    }
  }

  componentDidMount(){
    axios.get('http://192.168.1.102/react/showStudent.php')
       .then(response => this.setState({Info:response.data,isLoading:false}))
       .catch(function (error) {
          console.log(error);
       });
  }

  ListItemSeprator(){
    return(
      <View style={{width:'100%',height:1,backgroundColor:'#ccc'}}></View>
    );
  }

  resnderStudent(){
    return this.state.Info.map(student=>
      <StudentDetail key={student.Id} student={student} />
    );
  }

  userEditData(){
    alert('asdasd');
  }

  render(){
    if(this.state.isLoading==true){
      return(
        <View style={styles.main}>
           <ActivityIndicator />
        </View>
      )
    }
    else {
      return(
          <View style={styles.main}>
             <Header text="جدول دانش آموزان" />
             {this.resnderStudent()}
          </View>
      )
    }

  }
}

const styles = StyleSheet.create({
  main:{
    flex:1,
    backgroundColor:'#FFF'
  },
  TouchStyle:{
    width:'90%',
    marginRight:'5%',
    marginLeft:'5%',
    justifyContent:'center',
    alignItems:'center',
    backgroundColor:'#00BCD4',
    height:40,
    borderRadius:5,
    marginTop:10
  },
  TextTouchStyle:{
    color:'#FFF',
    fontSize:14,
    fontFamily:'IRANSansWeb-Light',
  }
})
export {ShowStudent};
`
## StudentDetails.js

`import React from 'react';
import { Text, ToastAndroid } from 'react-native';
import List from './List';
import ListSection from './ListSection';
import axios from 'axios';

const StudentDetail = (alow) => {

  return (
    <List style={styles.MyList}>
       <ListSection>
           <Text style={styles.ListText} onPress={()=>
             axios({
                 method:"POST",
                 url:'http://192.168.1.102/react/deleteStudent.php',
                 data:'StudentId='+alow.student.Id
             }).then(function (response){
                 ToastAndroid.show(response.data,ToastAndroid.SHORT);
             })
             .catch(function (error) {
                 console.log(error);
             })
           }>حذف</Text>
           <Text style={styles.ListText} onPress={() => this.props.navigation.navigate('Profiled')}>ورایش</Text>
           <Text style={styles.ListText}>{alow.student.Phone}</Text>
           <Text style={styles.ListText}>{alow.student.Class}</Text>
           <Text style={styles.ListText}>{alow.student.Name}</Text>
       </ListSection>
    </List>
  );
};

const styles = {
  MyList:{
    flex: 1,
    flexDirection: 'row'
  },
  ListText:
  {
    width:'20%',
    height:20,
    textAlign:'center'
  }
}

export default StudentDetail;
`

**Comment by nazrdogan** [comment]
```

const StudentDetail = (alow) => {

return (
<Text style={styles.ListText} onPress={()=>
axios({
method:"POST",
url:'http://192.168.1.102/react/deleteStudent.php',
data:'StudentId='+alow.student.Id
}).then(function (response){
ToastAndroid.show(response.data,ToastAndroid.SHORT);
})
.catch(function (error) {
console.log(error);
})
}>حذف
<Text style={styles.ListText} onPress={() => this.props.navigation.navigate('Profiled')}>ورایش
{alow.student.Phone}
{alow.student.Class}
{alow.student.Name}
);
};
 ```
This component dont have `this.props` Just  have `alow` You can't do that. Pass `navigation` object to this component and call like this "navigation.navigate('Profiled')"

and Please use  code block. When you posting issue

**Comment by vonovak** [comment]
@StudioAleph please use `this.props.navigation` instead of `this.navigation` and make sure the component is a screen component or use the `@withNavigation` HOC
