### ISSUE TITLE
DrawerNavigator does not work, if it contains a TabNavigator containing a Stacknavigator

### ISSUE THREAD

**Issue by janrop** [react-navigation/react-navigation#3954]
### Current Behavior

https://snack.expo.io/@janrop/drawernavigator-test

Navigating with the DrawerNavigator does not work if there is a TabNavigator which itself contains a StackNavigator

- Drawer Navigator
    - TabNavigator
        - Stacknavigator
            - Screen
        - Screen
        - Screen
    - Screen

### Expected Behavior

- Navigation should work as expected

### How to reproduce

https://snack.expo.io/@janrop/drawernavigator-test

* Go to the second or third tab
* Open the Drawer
* Go To "InDrawer"
* Open the Drawer
* Try to return to "Tabs"

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.5.11
| expo sdk     | 26.0.0

**Comment by kosmicbird** [comment]
+1 

I have a very similar navigation system and am experiencing the same issue

**Comment by ericvicenti** [comment]
Just fixed it here: https://github.com/react-navigation/react-navigation/pull/4237

In the mean time you can make this change yourself, or use a custom drawer contentComponent that just does a normal `props.navigation.navigate()` when a link is pressed.

**Comment by kosmicbird** [comment]
Oh cool! Great news to wake up to ^_^ I will implement this in my app. Thanks!

**Comment by brentvatne** [comment]
we still need to remove the `StackActions.reset()` thing from drawer, issue lives on at https://github.com/react-navigation/react-navigation-drawer/issues/2

**Comment by seanmorton** [comment]
https://github.com/react-navigation/react-navigation-drawer/pull/16
