### ISSUE TITLE
Ripple back button Android is too wide

### ISSUE THREAD

**Issue by JasperVercammen** [react-navigation/react-navigation#3955]
### Current Behavior

- The default back arrow on android has a ripple that goes too wide.
![ripple_too_large](https://user-images.githubusercontent.com/2750271/38606731-25ead0a8-3d77-11e8-9b9a-46dfb11bb6f5.gif)

If the header ends, the ripple is cut off. 
If not, the ripple will go on till it's under the statusbar. This is visible in the default example project: 
https://expo.io/@react-navigation/NavigationPlayground

### Expected Behavior

- The ripple should have boundaries. (48 x 48 dp) 
Example from the messeges app from google: 
![ripple_as_it_should_be](https://user-images.githubusercontent.com/2750271/38606729-25d05e08-3d77-11e8-98be-4384ad810147.gif)

Can also be checked in every other app from Google. 

### How to reproduce

- Open an android project with a stacknavigator and 2 screens. Navigate to the second screen. Press (and hold) the back arrow.  (https://expo.io/@react-navigation/NavigationPlayground)

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.5.3
| react-native     | 0.53

**Comment by kristfal** [comment]
Nitpick: Also the ripple should inherit the tint colour of the icon. See an example at:

https://material.io/guidelines/components/buttons.html#buttons-toggle-buttons

**Comment by kolyneh** [comment]
Maybe this issue is fixed then #4616 is fixed too.
The `headerLeft` component should have `marginLeft:16` to prevent from touching parent's left.

**Comment by brentvatne** [comment]
fix is merged on master, to be released soon
