### ISSUE TITLE
after using react-navigation-redux, get the warning

### ISSUE THREAD

**Issue by kk412027247** [react-navigation/react-navigation#3957]
version:
```
  "dependencies": {
    "prop-types": "^15.6.1",
    "react": "16.3.1",
    "react-native": "0.55.2",
    "react-native-elements": "^0.19.1",
    "react-navigation": "^1.5.11",
    "react-navigation-redux-helpers": "^1.0.5",
    "react-redux": "^5.0.7",
    "redux": "^3.7.2",
    "redux-thunk": "^2.2.0"
  },
```

After using the latest version of react-navigation with redux, i get the message:**'Warning: isMounted(...) is deprecated in plain JavaScript React classes. Instead, make sure to clean up subscriptions and pending requests in componentWillUnmount to prevent memory leaks.'**
I didn't use *isMounted* in my code. I don't know why this happen. 
I haven't get this message before.

By the way , when I run the demo with native code , also get this warning.
https://github.com/react-navigation/react-navigation/tree/master/examples/ReduxExample

Need some help, please.

```
import React from 'react';
import {connect} from 'react-redux';
import {bindActionCreators} from 'redux';
import PropTypes from 'prop-types';
import {View, Text, Button} from 'react-native';
import {handleNav} from '../../actions/navAction';
import styles from '../styles/styles';
const Login = ({handleNav}) => (
  <View style={styles.container}>
    <Text>Login Page</Text>
    <Text>Login Page</Text>
    <Text>Login Page</Text>
    <Text>Login Page</Text>
    <Text>Login Page</Text>
    <Text>Login Page</Text>
    <Button
      title = {'Login Button'}
      onPress = {handleNav.bind(null, 'MAIN')}
    />
    <Button
      title={'go to register page'}
      onPress={handleNav.bind(null, 'REGISTER')}
    />
  </View>
);
Login.propTypes = {
  handleNav:PropTypes.func,
};
const mapDispatchToProps = dispatch => bindActionCreators({handleNav}, dispatch);
export default connect(null, mapDispatchToProps)(Login);
```

**Comment by jonajgs** [comment]
@kk412027247 how did you solve it ?

**Comment by pabloIO** [comment]
@kk412027247  yes, how did you solve it? please share it, I'm in the same trouble

**Comment by pabloIO** [comment]
hahaha alright thanks @kk412027247 , actually its pretty strange

**Comment by kgrajan12** [comment]
Yes I have the same issue
and I know about remove yellow box
This just ignores the problem not resolve the problem
plz anyone give the good reason for this yellow box

**Comment by Subrata0biswas** [comment]
But In this way i am unable to create an apk

**Comment by ryekerjh** [comment]
same issue +1

**Comment by pabloIO** [comment]
I thing for the moment the solution is to downgrade react-navigation

**Comment by pabloIO** [comment]
Is this issue known by the react-navigation community? I think it is VERY important to solve

**Comment by ryekerjh** [comment]
@pabloIO Do you know the suggested best option for downgrade?

**Comment by pabloIO** [comment]
I was working on a project without that problem, the version was 1.5.8
