### ISSUE TITLE
Selectively enabling the header for some screens only does not work

### ISSUE THREAD

**Issue by marcmo** [react-navigation/react-navigation#3958]
### Current Behavior

removing the header for some screens works for me, adding it for some only not:

### How to reproduce

this does not seem to work (default is no header, but adding a header for `A`)
```
const MainModalNavigator = StackNavigator(
  {
    A: {
      screen: DevOpts,
      navigationOptions: {
        header: (props) => <Text>myhuder3</Text>,
        headerMode: 'screen',
      },
    },
    B: { screen: IdentityScreen },
  },
  {
    mode: 'modal',
    headerMode: 'none',
  },
);
```
this works: default is with header, here I just remove it on `A`
```
const MainModalNavigator = StackNavigator(
  {
    A: {
      screen: DevOpts,
      navigationOptions: {
        header: null,
      },
    },
    B: { screen: IdentityScreen },
  },
  {
    mode: 'modal',
  },
);
```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.5.9
| react-native     | 0.53.3

**Comment by brentvatne** [comment]
`headerMode` is not customizable on per screen basis. it's not part of `navigationOptions`. use `header: null` if you want to get rid of the header for a specific screen

**Comment by bosz** [comment]
Thanks @brentvatne . Saved me days of headache.

**Comment by gbmahili** [comment]
Very helpful. Thank you.

**Comment by dipakparmar** [comment]
I have two stack navigatior which has two screens and I want to set header: null for the second screen and for first screen tabBarvisible: false but it applying one stack, not for other one. 

```
export default (HomeStack = createStackNavigator({
  Home: {
    screen: HomeScreen,
    navigationOptions: {
      header: null,
      tabBarVisible: true ,
    }
  },
  Details: {
    screen: DetailsScreen,
    navigationOptions: {
      header:null,
      tabBarVisible: fasle,
    }
  }
}));


  HomeStack.navigationOptions = {
  tabBarLabel: '',
  header: null,
  tabBarIcon: ({ focused }) => (
    <TabBarIcon type='AntDesign' name='home' />
  )
};
```

```
export default CategoriesStack = createStackNavigator({
  Category: {
    screen: CategoryScreen,
    header:null,
    tabBarVisible: false,
  },

});


CategoriesStack.navigationOptions = {
  tabBarLabel: '',
  header: null,
  tabBarIcon: ({ focused }) => (
    <TabBarIcon type='Foundation' name='thumbnails' />
  )
};
```

If anyone knows please help out!

**Comment by abumalick** [comment]
Note for a future self:
Here is how to use it with <Stack.Screen /> component
```
<Stack.Screen
            name="Home"
            component={Home}
            options={{header: () => null}}
          />
```

**Comment by rosorio02** [comment]
You have to set `headerMode` to screen in order to display header on every screen and config screens individually to disable it on certain screens:
`<Stack.Screen
            name="Home"
            component={Home}
            options={{
                 headerShown:false
            }}/>`

**Comment by Nivethan-Ar** [comment]
react navigation 6 answer 

### To hide header by default and show it only one screen you can do like this:

`<Stack.Navigator
  screenOptions={{ headerShown: false }} // header hidden by default on all screens
>
  <Stack.Screen name="Home" component={HomeScreen}>
  <Stack.Screen name="About" component={AboutScreen} options={{ headerShown:true, title: About}}>  // header will be shown only on this screen
  `
