### ISSUE TITLE
Custom headerLeft shows blue back arrow after pressing it

### ISSUE THREAD

**Issue by greghuels** [react-navigation/react-navigation#3959]
### Current Behavior

I have a custom headerLeft arrow in a StackNavigator screen, and it shows up perfectly.  However, after I press it, the default blue back arrow appears on the screen being navigated to for a fraction of a second.  

### Expected Behavior

The default blue back arrow does not appear.

### How to reproduce

Add a custom back icon to a screen within a StackNavigator:

```
MyScreen.navigationOptions = () => ({
  headerLeft: <MyBackButton onPress={onBack} />,
});
```

### Your Environment

Tested on iPhone 8 simulator, with deployment target 9.0

| software         | version
| ---------------- | -------
| react-navigation | 2.0.0-rc.2
| react-native     | 0.53.0
| node             | 9.3.0
| yarn      | 1.3.2

**Comment by greghuels** [comment]
This was actually due to hiding my header bar on the previous page.  Will re-open if I cannot fix this myself.

**Comment by jpamarohorta** [comment]
@greghuels have you fixed this? I'm having the same issue when going back from a screen with a custom header to a screen without header.

**Comment by jrounsav** [comment]
Seeing this as well. Only on previous screen without any header
