### ISSUE TITLE
undefined is not a function (evaluating '(0, _reactNavigation.TabNavigator)')

### ISSUE THREAD

**Issue by hhw3KevinHou** [react-navigation/react-navigation#3962]
I tried 2.0.0-rc.2 and got error even in guide code.

"dependencies": {
    "react": "^16.3.1",
    "react-native": "^0.55.2",
    "react-native-vector-icons": "^4.6.0",
    "object-assign": "^4.1.1",
    "react-navigation": "^2.0.0-rc.2"
  },

class HomeScreen extends React.Component {
    render() {
        return (
            <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
                <Text>Home!</Text>
            </View>
        );
    }
}

class SettingsScreen extends React.Component {
    render() {
        return (
            <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
                <Text>Settings!</Text>
            </View>
        );
    }
}

export default TabNavigator({
    Home: { screen: HomeScreen },
    Settings: { screen: SettingsScreen },
});

**Comment by hhw3KevinHou** [comment]
so I downgrade to 
"dependencies": {
    "react": "^16.3.1",
    "react-native": "^0.55.2",
    "react-native-vector-icons": "^4.6.0",
    "object-assign": "^4.1.1",
    "react-navigation": "^1.5.11"
  },

now the code can run.
I can not run 2.0.0-rc.2 correctly.

**Comment by brentvatne** [comment]
it is there, so it is some bug in your code: https://github.com/react-navigation/react-navigation/blob/master/src/react-navigation.js#L50-L55

**Comment by serhiipalash** [comment]
@brentvatne I ran into the same problem an hour ago.

I guess the problem is that in v1.5.2 TabNavigator is a function
```
const TabNavigator = (routeConfigs, config = {}) => {
    ...
}
```

and `default` export from main file of `react-navigation-deprecated-tab-navigator` is not a function
https://github.com/react-navigation/react-navigation-deprecated-tab-navigator/blob/master/src/index.js#L6-L11

Maybe in `react-navigation` TabNavigator export should look like this?
```
  get TabNavigator() {
    console.warn(
      'TabNavigator is deprecated. Please use the createBottomTabNavigator or createMaterialTopNavigator instead.'
    );
    return require('react-navigation-deprecated-tab-navigator').createTabNavigator;
  },
```

**Comment by brentvatne** [comment]
good point! yeah it should look like that @serhiipalash! can you submit a PR?

**Comment by serhiipalash** [comment]
https://github.com/react-navigation/react-navigation/pull/3979

**Comment by lFaustus** [comment]
I looked at the library source code, it seems createTabNavigation is missing
react-navigation 3.0.5
![screenshot_5](https://user-images.githubusercontent.com/10105530/51147452-3d59cd80-1895-11e9-9e17-bae4ec398b08.png)
