### ISSUE TITLE
Status Bar changes occur instantly on pushing onto a StackNavigator, but are delayed on pressing the back button

### ISSUE THREAD

**Issue by Rob117** [react-navigation/react-navigation#3964]
### Current Behavior

The code is available in the [snack](https://snack.expo.io/rkLguunjz), but essentially we have a simple StackNavigator with two screens. Each screen has a StyleBar barStyle defined in its render method. Example:

```
class DetailsScreen extends React.Component {
  render() {
    return (
      <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: 'Gray'}}>
      <StatusBar barStyle="dark-content" />
        <Text>Details Screen</Text>
      </View>
    );
  }
}
```

When transitioning *down* the stack navigator, the status bar style works as expected and changes the status bar at the moment the screen transition begins. When transitioning *up* the stack navigator (using the goBack navigation option or pressing back in the default header), the status bar style does not work as expected and instead changes the color only at the end of the screen-transition animation. 

### Expected Behavior

I expect that if the colors of the status bar are signaled to change in a renderer, that they should always change at the beginning of a transition animation regardless of the version the navigator progresses in.

**Note** I did see somewhere that StatusBar options could be defined directly in the stack and not only on individual screen components. If that solves my issue and removes the animation delay, a quick  code snippet or a point in the right direction would be highly appreciated.

### How to reproduce

[Snack with bare-minimum code](https://snack.expo.io/rkLguunjz)

Notice that on either android or iOS, the original home screen status bar is light (on iOS, this should make it nearly invisible on the white background).

Click the button in the center of the screen "Go to details."

Notice that the status bar immediately changes color before the screen change animation is complete.

Click the back button on Android or the back button in the header on iOS.

Notice that the status bar does **not** change color until the transition animation is complete.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.5.11
| react-native     | 0.54.4
| node             |  9.5.0
| npm or yarn      |  Yarn 1.3.2, npm 5.6.0

**Comment by EyMaddis** [comment]
The StatusBar only updates when the screen is (re)rendered. 
When a new screen is shown, it needs to render everything first, updating the StatusBar.
When you go back there is no need to rerender as the view is already in cache.

You can unify the experience using the [`withNavigationFocus`](https://reactnavigation.org/docs/with-navigation-focus.html) this will add the `isFocused` property when the view is loaded.
This leads to only update the StatusBar whenever the screen is completely shown.

I updated your snack to show this: https://snack.expo.io/Hkr8Vn0sG

**Comment by Rob117** [comment]
Awesome! Thank you for the advice, that was very helpful. I'll close the issue. Should I make a PR for the docs to address this, or should I wait for 2.0 docs to be official?

**Comment by Rob117** [comment]
Actually, I made a bit of an error, and I need to re-open the issue. I need a way to update the status bar for a given screen **the moment that the back button is pressed**. Is there a way to do that? So, for example, when the back button is pressed, before the previous screen is re-rendered the status bar changes to some static option for that screen.

**Comment by EyMaddis** [comment]
I think you could implement this in `static navigationOptions = () { .... StatusBar.setBarStyle(...) }` in the target component.
However, you would have to manually reset the style when you leave the route, something that would be automatically handled by using `<StatusBar ... />`

**Comment by brentvatne** [comment]
https://github.com/react-navigation/rfcs/issues/19 - let's discuss on here

**Comment by simonsisay** [comment]
@Rob117 did you resolve your issue ??

**Comment by Rob117** [comment]
@simonsisay No.

So, you _could_ set the status bar when you change screens via navigation focus, but it's gonna be ugly it it works at all, and I certainly haven't done anything with it in RN 3

**Comment by valyakin** [comment]
If even `withNavigationFocus` didn't do a trick for you here is a workaround:
`{ this.props.isFocused && <StatusBar backgroundColor='#e5e5e5' barStyle="dark-content"/> }`

**Comment by taeingyu** [comment]
@Rob117 
Try useFocusEffect.

```javascript
  useFocusEffect(
    React.useCallback(() => {
      StatusBar.setBarStyle('light-content');
    }, [])
  );
```

before
![1](https://user-images.githubusercontent.com/24571455/75249746-30d6d100-581a-11ea-9cdb-06fcb8dde8f3.gif)

after
![2](https://user-images.githubusercontent.com/24571455/75249761-39c7a280-581a-11ea-95a0-3639907b50bc.gif)

**Comment by fabio-alvarenga** [comment]
@IngyuTae loved it. This performs so much better than what is advised in the current docs https://reactnavigation.org/docs/status-bar/#tabs-and-drawer

Thank you!
