### ISSUE TITLE
How to tell if a view is being focused like ios viewWillAppear.

### ISSUE THREAD

**Issue by jgfidelis** [react-navigation/react-navigation#3967]
I have a background on iOS so I am familiar with the `viewWillAppear:` method, that is called whenever a screen is appearing to the user. On our app, we need a similar behaviour. For detecting if a screen is coming back to focus after a back button (`navigation.goBack()`), I am using `componentWillReceiveProps` and see in the navigation state if the new prop route is my screen's route.

Does react-navigation have a built in method for this or what I am doing is the only way to detect this?

Maybe I could do `if (newProps.navigation.isFocused() && !props.navigation.isFocused())` on componentWillReceiveProps will work, I will test this.

I just want to know what is the most correct/elegant solution. I need this in a lot of screens and will try to make a HOC for this.

Our react-navigation version is 1.5.10.
React-native version 0.53.0

Edit: I don't know if the best place to open this was here or at react-native's repo...

**Comment by vonovak** [comment]
this is more of a usage question and would be better suited for stackoverflow.
consider also subscribing for the events: https://reactnavigation.org/docs/navigation-prop.html#addlistener-subscribe-to-updates-to-navigation-lifecycle

**Comment by jgfidelis** [comment]
@vonovak Hi, thanks, I created a HOC and managed to make it work.

I also tried to subscribe for the 'didFocus' and 'willFocus' event and it did not work.

Is this a known bug on 1.5.11?
