### ISSUE TITLE
ReduxExample Breaks on 1.5.2

### ISSUE THREAD

**Issue by mike3run** [react-navigation/react-navigation#3970]
### How to reproduce

- Start a new create-react-native-app
- Add redux, prop-types, react-navigation react-navigation-redux-helpers react-redux
- Copy src folder from the `ReduxExample`
- Copy App.js from the `ReduxExample`

Click on `< Home Page`

<img width="465" alt="screen shot 2018-04-12 at 10 49 33 am" src="https://user-images.githubusercontent.com/7088511/38688632-327430d0-3e3f-11e8-8d8e-0f91d8c299f8.png">

Red Screen of Death

### How to solve

`yarn add react-navigation@next`

😛

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.5.2
| react-native     | 16.3.0-alpha.1
| node             | 8.9.4
| npm or yarn      | yarn

**Comment by brentvatne** [comment]
use the redux example from the 1.x branch: https://github.com/react-navigation/react-navigation/tree/1.x
