### ISSUE TITLE
Keyboard issue when a screen has a header

### ISSUE THREAD

**Issue by tafelito** [react-navigation/react-navigation#3971]
### Current Behavior

KeyboardAvoidingView is not working when a screen has a header. If no header is shown, it works as expected.

Here are some screen shots describing the issue

Screen w/ header
![image 2](https://user-images.githubusercontent.com/5973652/38692805-f4dbdf2a-3e52-11e8-8ca5-07ab497efac6.png)

Screen wo/ header
![image 1](https://user-images.githubusercontent.com/5973652/38692784-eac17dce-3e52-11e8-80a2-e27e2c44b99c.png)

### Expected Behavior

It should work the same as it does when no header is shown without to manually having to adjust the offset

### How to reproduce

Snack to reproduce this issue
https://snack.expo.io/@tafelito/keyboard-issue-iphonex

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.5.11
| react-native     | 0.54.4

As a temporary solution, I'm doing this for iOS

```js
<KeyboardAvoidingView
        behavior="padding"
        keyboardVerticalOffset={isIphoneX() ? 88 : 64} 
        style={{flex:1}}
      >
     {children}
</KeyboardAvoidingView>
```

**Comment by brentvatne** [comment]
I'm curious -- what makes you think this is a react-navigation issue vs an issue with KeyboardAvoidingView?

**Comment by tafelito** [comment]
I'm not so sure but I guess it's the fact that if I don't use react-navigation or, as I pointed it out, I hide the header on the screen, it does work. Not much other than that. 
It looks like is not taking the height of the top navbar into consideration.

**Comment by brentvatne** [comment]
any suggestions on how to improve that? I don't see how react-navigation could help make KeyboardAvoidingView work better here

**Comment by tafelito** [comment]
I'll try to dig a little bit more and see if there is anything that can be done here

**Comment by brentvatne** [comment]
ok. i will close this issue because i don't think it's related to react navigation (it's an issue with KeyboardAvoidingView i believe) but feel free to create a rfc (https://github.com/react-navigation/rfcs) if you come up with some ideas for how to integrate it more nicely

**Comment by artdent** [comment]
https://github.com/facebook/react-native/issues/13393 is the corresponding react-native issue, FYI.

**Comment by yangyuan** [comment]
This is not an issue of KeyboardAvoidingView, neither an issue of react-navigation. It's problem of collaboration between both.

According to [The document](https://facebook.github.io/react-native/docs/keyboardavoidingview.html#keyboardverticaloffset), KeyboardAvoidingView.keyboardVerticalOffset is required if the view doesn't start from the top of the screen.

However it is very difficult to retrive this "offset" when playing with react-navigation headers. There are many cases need to be considered.
It's actually easier to solve from react-navigation side, because react-navigation controlls the headers. We just need to put the KeyboardAvoidingView outside the headers.

I tried some experiments with stack navigator:
in StackViewLayout.render():
```
      <View {...handlers} style={containerStyle}>
        <View style={styles.scenes}>
          {scenes.map(s => this._renderCard(s))}
        </View>
        {floatingHeader}
      </View>
```

```
    <KeyboardAvoidingView style={{flex:1}} behavior="padding">
      <View {...handlers} style={containerStyle}>
        <View style={styles.scenes}>
          {scenes.map(s => this._renderCard(s))}
        </View>
        {floatingHeader}
      </View>
    </KeyboardAvoidingView>
```

This works if you have nothing (expect status bar) above the stack navigation header, if you have a tab navigator with tabs on top, then you need to add the KeyboardAvoidingView for tab navigator. Bottom tab navigator, however, is usually okay to be covered by keyboard.

I believe, a decent design would be adding an option in navigationOptions, and let the user decide if the navigator should be "keyboard avoiding".

**Comment by yangyuan** [comment]
I modified the react-navigation so that you can wrap the (tab/stack/switch) navigators with KeyboardAvoidingView without extending the avigators.
#4290

**Comment by zcmgyu** [comment]
Same issue

**Comment by brentvatne** [comment]
@d3vhound - can you open a PR on the docs about this KeyboardAvoidingView limitation?

**Comment by shaoner** [comment]
Currently using this approach:

```js
import { Header } from 'react-navigation-stack';
import {
    KeyboardAvoidingView,
    StatusBar,
    View
 } from 'react-native';
const KEYBOARD_VERTICAL_OFFSET = Header.HEIGHT + StatusBar.currentHeight;

const MyScreen = (props) => (
    <KeyboardAvoidingView
         style={{ flex: 1 }}
         keyboardVerticalOffset={KEYBOARD_VERTICAL_OFFSET}
         behavior="padding">
         <View style={styles.contentContainer}>
              {props.children}
         </View>
         <View>
              {footer}
         </View>
    </KeyboardAvoidingView>
);
```

**Comment by chidimo** [comment]
Here's what I eventually did following suggestions here and on [SO](https://stackoverflow.com/questions/44990478/react-native-keyboardavoidingview-with-sticky-footer/55688676#55688676)

My app uses `react-navigation`. So Toh Ban Soon's answer I ended up doing

```javascript
import { KeyboardAvoidingView } from 'react-native';
import { Constants } from 'expo';
import { Header } from 'react-navigation';

<KeyboardAvoidingView behavior="padding" keyboardVerticalOffset = {Header.HEIGHT + Constants.statusBarHeight} style={[sharedStyles.container, {justifyContent: 'center'}]}>

... Input components...

</KeyboardAvoidingView>
```

**Comment by nandorojo** [comment]
This worked for me using react-native's `createStackNavigator`. It's slightly hacky but did the job. Basically you make the header absolute positioned and adjust your screen content accordingly.

When the header is absolute positioned, the KeyboardAvoidingView doesn't take it into account.

**1. In navigation options for your screen:**
First make the header absolute positioned by setting `headerTransparent: true`.
```javascript
const InboxStack = createStackNavigator(
    {
        Screen1: {
            screen: Screen1,
            navigationOptions: () => ({
                headerTransparent: true
                // other things you put here
            })
        },
);

```

**2. Adjust your screen style**

This part is up to you. Basically, just set your screen paddingTop equal to the height of the header. 

```javascript
import React, { Component } from 'react';
import { View, KeyboardAvoidingView, Platform } from 'react-native';
import { Header } from 'react-navigation';

const behavior = (Platform.OS === 'ios') ? 'padding' : null;

export default class YourComponent extends Component {
render() {
    const headerOffset = Header.HEIGHT;
    <KeyboardAvoidingView behavior={behavior} style={{ flex: 1 }}>
         <View style={{ paddingTop: headerOffset, flex: 1 }}>
            // your content here...
          </View>
   </KeyboardAvoidingView>
}
}

**Comment by Ashoat** [comment]
Try wrapping your `KeyboardAvoidingView` around any `StackNavigator` with a header:

```js
import * as React from 'react';
import { KeyboardAvoidingView, StyleSheet } from 'react-native';
import hoistNonReactStatics from 'hoist-non-react-statics';

import ChatNavigator from './chat-navigator.react';

class Chat extends React.PureComponent {

  render() {
    return (
      <KeyboardAvoidingView behavior="padding" style={styles.keyboardAvoidingView}>
        <ChatNavigator {...this.props} />
      </KeyboardAvoidingView>
    );
  }

}

const styles = StyleSheet.create({
  keyboardAvoidingView: {
    flex: 1,
  },
});

hoistNonReactStatics(Chat, ChatNavigator);

export default Chat;
```

If your `StackNavigator` is inside a `TabNavigator`, make sure to set `keyboardHidesTabBar` to `false` for this to work.

**Comment by GabrielCTroia** [comment]
@Ashoat's solution is the only thing that worked in my case!

**Comment by zmefz** [comment]
This solutions works pretty good:

```javascript
import React from 'react';
import { KeyboardAvoidingView, StatusBar } from 'react-native';
import { useHeaderHeight } from '@react-navigation/stack';

export default function CustomKeyboardAvoidingView({ children, style }) {
    const headerHeight = useHeaderHeight();

    return (
        <KeyboardAvoidingView
            style={style}
            behavior="padding"
            keyboardVerticalOffset={headerHeight + StatusBar.currentHeight}
        >
            {children}
        </KeyboardAvoidingView>
    );
}
```

Usage example:
```javascript
<CustomKeyboardAvoidingView style={{ flex: 1 }}>
  {/* ... */}
</CustomKeyboardAvoidingView>
```

P.S. Inline style is used only for demonstration; styles should live at `StyleSheet.create({ ... })`

**Comment by douglasrcjames** [comment]
Here is a full example that I built to break down what part of my UI was causing the issue (it truly was the stack navigation header). Used @zmefz component as well for hook implementation since context usage getting header height doesn't seem reliable. The important line of code is `keyboardVerticalOffset={headerHeight + StatusBar.currentHeight}`, take that away and it breaks.

```
import React, { Component } from 'react';
import { View, KeyboardAvoidingView, TextInput, Text, Platform, TouchableWithoutFeedback, Keyboard, ActivityIndicator, SafeAreaView, ScrollView, Button, StatusBar   } from 'react-native';
import { NavigationContainer } from '@react-navigation/native';
import { createBottomTabNavigator } from '@react-navigation/bottom-tabs';
import { createStackNavigator, useHeaderHeight } from '@react-navigation/stack';

const Stack = createStackNavigator();

function TicketStack() {
  return (
    <Stack.Navigator>
      <Stack.Screen name="Ticket" component={TicketScreen} />
      <Stack.Screen name="Chat" component={ChatScreen} />
    </Stack.Navigator>
  );
}

function HomeScreen() {
  return (
    <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
      <Text>Home screen!</Text>
    </View>
  );
}

function TicketScreen(props){
  return (
    <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
      <Text>Ticket screen!</Text>
      <Button title="Go to Chat" onPress={() => props.navigation.navigate('Chat')} />
    </View>
  );
}

function CustomKeyboardAvoidingView({ children, style }) {
    const headerHeight = useHeaderHeight();

    return (
        <KeyboardAvoidingView
            style={style}
            behavior={Platform.OS == "ios" ? "padding" : "height"}
            keyboardVerticalOffset={headerHeight + StatusBar.currentHeight}
        >
            {children}
        </KeyboardAvoidingView>
    );
}

function ChatScreen(){
  return(
    <SafeAreaView SafeAreaView style={{flex: 1, backgroundColor: "grey"}}>
      <TouchableWithoutFeedback onPress={Keyboard.dismiss}>
        <CustomKeyboardAvoidingView style={{backgroundColor: "#fff", flex: 1, flexDirection: "column", justifyContent: "space-between" }}>
          <View style={{backgroundColor: "dodgerblue", paddingVertical: 15}}>
              <View style={{ margin: 10, marginBottom: 15}}>
                  <ActivityIndicator size="large" style={{marginBottom: 10}}/>
                  <Text>Waiting for more info here....</Text>
              </View>
          </View>

          <ScrollView style={{backgroundColor: "tomato", paddingVertical: 15}}>
              <Text>Chat messages</Text>
              <Text>Chat messages</Text>
              <Text>Chat messages</Text>
              <Text>Chat messages</Text>
              <Text>Chat messages</Text>
              <Text>Chat messages</Text>
              <Text>Chat messages</Text>
              <Text>Chat messages</Text>
              <Text>Chat messages</Text>
              <Text>Chat messages</Text>
              <Text>Chat messages</Text>
              <Text>Chat messages</Text>
              <Text>Chat messages</Text>
              <Text>Chat messages</Text>
              <Text>Chat messages</Text>
              <Text>Chat messages</Text>
              <Text>Chat messages</Text>
              <Text>Chat messages</Text>
              <Text>Chat messages</Text>
              <Text>Chat messages</Text>
              <Text>Chat messages</Text>
              <Text>Chat messages</Text>
              <Text>Chat messages</Text>
          </ScrollView>
          
          <View style={{backgroundColor: "yellow", paddingVertical: 15}}>
              <TextInput placeholder="Type your message here" />
          </View>
        </CustomKeyboardAvoidingView>
      </TouchableWithoutFeedback>
    </SafeAreaView>
  )
}

const Tab = createBottomTabNavigator();

export default class App extends Component {
  render(){
    return (
      <NavigationContainer>
        <Tab.Navigator>
          <Tab.Screen name="Home" component={HomeScreen} />
          <Tab.Screen name="Ticket" component={TicketStack} />
        </Tab.Navigator>
      </NavigationContainer>
    );
  }
}

```

**Comment by tomwaitforitmy** [comment]
What is the current state of this? Years later I still have the issue and none of the proposed fixes works smoothly.

**Comment by bimix** [comment]
> This solution works pretty good:
> 
> ```js
> import React from 'react';
> import { KeyboardAvoidingView, StatusBar } from 'react-native';
> import { useHeaderHeight } from '@react-navigation/stack';
> 
> export default function CustomKeyboardAvoidingView({ children, style }) {
>     const headerHeight = useHeaderHeight();
> 
>     return (
>         <KeyboardAvoidingView
>             style={style}
>             behavior="padding"
>             keyboardVerticalOffset={headerHeight + StatusBar.currentHeight}
>         >
>             {children}
>         </KeyboardAvoidingView>
>     );
> }
> ```
> 
> Usage example:
> 
> ```js
> <CustomKeyboardAvoidingView style={{ flex: 1 }}>
>   {/* ... */}
> </CustomKeyboardAvoidingView>
> ```
> 
> P.S. Inline style is used only for demonstration; styles should live at `StyleSheet.create({ ... })`

Error: useHeaderHeight is not a function.

**Comment by raajnadar** [comment]
You need to read this https://reactnavigation.org/docs/elements/#useheaderheight, check your version

**Comment by bimix** [comment]
> You need to read this https://reactnavigation.org/docs/elements/#useheaderheight, check your version

Thats for whiever uses Hooks, I dont! I use class components.

**Comment by raajnadar** [comment]
Check the whole thread we also have solution for class component.

**Comment by bimix** [comment]
> ```js
> 64
> ```

Can you please point out which one? I went thruogh all of them, couldnt find it

**Comment by daviddunnington** [comment]
Not sure why but the seems to be poorly documented however there is a solution. When debugging the issue I discovered that setting the headerShown prop to false fixed the issue, obviously not great as we need a header in the stack navigator.

What you need to do is import the React Navigation Elements library as we need to figure out what the header height is to add an offset to the keyboard avoiding view.

Install the library with one of the following.`yarn add @react-navigation/elements` Or `npm install @react-navigation/elements`

Then I created a custom component to make life easier for when I need to use the keyboard avoiding view.

```
import React from 'react';
import { useHeaderHeight } from '@react-navigation/elements';
import { KeyboardAvoidingView, Platform, ScrollView } from 'react-native';

interface KeyboardAwareScrollViewProps {
  children: React.ReactNode;
}

function KeyboardAwareScrollView({ children }: KeyboardAwareScrollViewProps) {
  const headerHeight = useHeaderHeight();

  return (
    <KeyboardAvoidingView
      behavior={Platform.OS === 'ios' ? 'padding' : 'height'}
      style={{ flex: 1 }}
      keyboardVerticalOffset={Platform.OS === 'ios' ? headerHeight : 0}>
      <ScrollView keyboardShouldPersistTaps="handled">{children}</ScrollView>
    </KeyboardAvoidingView>
  );
}

export default KeyboardAwareScrollView;
```

You can then use this in any screen like so

```
import React from 'react';
import { KeyboardAvoidingView, Platform, ScrollView } from 'react-native';
import KeyboardAwareScrollView from './Components/Layout/KeyboardAwareScrollView'

function Home() {
  const [text, onChangeText] = React.useState('Useless Text');
  
  return (
      <KeyboardAwareScrollView>
          <TextInput
              style={styles.input}
              onChangeText={onChangeText}
              value={text}
            />
      <KeyboardAwareScrollView/>
  );
}

export default KeyboardAwareScrollView;

```
