### ISSUE TITLE
Yellow Box Warnings - Attention Please

### ISSUE THREAD

**Issue by mozaik1** [react-navigation/react-navigation#3973]
Hi, I'm using this right now and you need to make changes in the version. In later versions of "React Native", some usage patterns will be removed. 
These are: "**componentWillMound**", "**componentWillUpdate**", "**componentWillReceiveProps**".
You can also review usage patterns in this guide: [https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html](url)

![ekran resmi 2018-04-13 12 36 57](https://user-images.githubusercontent.com/16558196/38728624-0e4cdf42-3f19-11e8-9bb0-b85f446dac9c.png)

| software         | version
| ---------------- | -------
| react-navigation | ^1.5.11
| react-native     | 0.55.1
| node             | 8.10.0
| npm / yarn      |  5.6.0 / 1.3.2

**Comment by brentvatne** [comment]
please search existing issues before creating an issue: https://github.com/react-navigation/react-navigation/issues/3897

this is fixed already on master but will not be backported to the 1.x branch unless someone submits a PR to do it

**Comment by mozaik1** [comment]
@brentvatne 
Sorry, I did not see it #3897.
I thought the situation was important.
For this reason, I thought it was a issue.
Thank you for warning.
