### ISSUE TITLE
Flow error: Property `navigation` is missing in props [1] but exists in `Props` [2].

### ISSUE THREAD

**Issue by unclesaam** [react-navigation/react-navigation#3977]
Using the higher order component `withNavigation` passes the expected prop `navigation` to my component, but Flow 0.69.0 is complaining that the instantiation of the same component is missing the `navigation` props. Here's an example:

BackButton.js: (Simple component using `withNavigation`)
```
function BackButton({ navigation  }: { navigation: any }) {
  return (
    <TouchableOpacity onPress={() => navigation.goBack()}>
      <Icon name="chevron-thin-left"/>
    </TouchableOpacity>
  );
}

export default withNavigation(BackButton);
```
Component instantiation: `<BackButton />`

Now, I get the following Flow error:
```
Property `navigation` is missing in props [1] but exists in `Props` [2].

   src/job/containers/JobCategoryListing.js:67:11
   67|           <BackButton />
                 ^^^^^^^^^^^^^^ [1]

References:
   src/main/components/buttons/BackButton.js:17:72
   17| function BackButton({ navigation }: { navigation: any }) {
                                             ^^^^^^^^^^^^^^^ [2]
```

I've also tried declaring my props as follow:
`{ navigation: NavigationScreenProp<any> }` as well as 
`{ navigation: NavigationScreenProp<NavigationStateRoute> }`

But the same error persists.

How do I know this issue is related to react-navigation libdefs and not flow itself? Because In my project I also use many other props-injecting higher-order components, such as `redux` and `redux-thunk`. Also using the default flow-generated stub for `react-navigation` eliminates the issue. Unfortunately this will have to do for now, but it would be great to be able to use the actual react-navigation libdef.

### My Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.5.11
| react-native     | 0.53.0
| flow-bin | 0.69.0
| flow-typed      | 2.4.0

**Comment by unclesaam** [comment]
It might be useful to state that declaring the prop `navigation` as optional does fix the problem, but prevent any use of the methods contained inside, such a `goBack()`.

**Comment by Ashoat** [comment]
@unclesaam, could you try [this version](https://raw.githubusercontent.com/react-navigation/react-navigation/1.x/flow/react-navigation.js) of the libdef and let me know if it fixes the issue?

**Comment by unclesaam** [comment]
It seems to have solved the issue. Thank you!

**Comment by montogeek** [comment]
@Ashoat What is the fix exactly?
