### ISSUE TITLE
Hide Tabs in Nested StackNavigator Screens broken in v2

### ISSUE THREAD

**Issue by MrLoh** [react-navigation/react-navigation#3980]
It seems that #464 doesn't work anymore in v2-rc1. It used to be possible to hide the Tab Bar on a specific screen in a StackNavigator that was nested in a TabNavigator. This doesn't work anymore.

To reproduce simply run this code in the `App.js` of a CRNA, install once `react-natvigation` and once 
`react-navigation@^2.0.0-rc.1`. You will see that the TabBar isn't hidden anymore on the Nested Screen.

```js
import React from 'react';
import { View, Text, TouchableOpacity } from 'react-native';

import { TabNavigator, createBottomTabNavigator, StackNavigator } from 'react-navigation';
const _TabNavigator = createBottomTabNavigator || TabNavigator;

const HomeScreen = ({ navigation: { push } }) => (
  <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
    <TouchableOpacity onPress={() => push('Nested', { id: Math.round(Math.random() * 10) })}>
      <Text>Open Nested Screen</Text>
    </TouchableOpacity>
  </View>
);

const NestedScreen = ({ navigation: { push, state: { params: { id } } } }) => (
  <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
    <Text style={{ color: 'white', marginBottom: 20, fontWeight: 'bold' }}>Nested Screen</Text>
  </View>
);

const Navigator = _TabNavigator({
  Home: {
    screen: StackNavigator({
      Home: { screen: HomeScreen, navigationOptions: { title: 'Home' } },
      Nested: {
        screen: NestedScreen,
        navigationOptions: { title: 'Nested', tabBarVisible: false },
      },
    }),
  },
});

export default () => <Navigator />;

console.ignoredYellowBox = [
  'Warning: componentWillMount',
  'Warning: componentWillReceiveProps',
  'Warning: componentWillUpdate',
];
```

The cause is probably in the new descriptor API. The code for checking is now: 

https://github.com/react-navigation/react-navigation-tabs/blob/master/src/navigators/createBottomTabNavigator.js#L60-L68

It used to be: 

https://github.com/react-navigation/react-navigation/blob/1.x/src/views/TabView/TabView.js#L145-L151

The `childNavigationProps` Function isn't used anymore to get the right config, but the options just come from the parent tab screen.

**Comment by MrLoh** [comment]
It seems like this is a ‘feature’ of the new shallow navigation options that have been implemented in [RFC 5](https://github.com/react-navigation/rfcs/blob/master/text/0005-shallow-navigation-options.md). Seems like a step backwards to me, but I guess that's the price for making this library acessible to inexperienced developers. 

As a workaround, one can implement there own TabBar component and add a ton of extra logic to get the feature back.

**Comment by brentvatne** [comment]
> but I guess that's the price for making this library acessible to inexperienced developers.

the behavior should be easily predictable and not require you to reason about how navigation options propagate up through several layers. so while it certainly helps inexperienced developers, having a model with clear and simple rules benefits anybody using the library.

if you want to toggle some navigation option from somewhere deeper in the nav tree, you can make that option be calculated from a param and then modify the param through a custom action (https://github.com/react-navigation/rfcs/blob/master/text/0006-action-creators.md -- see "getCustomActionCreators"). this action will then be available on the navigation prop for any screens deeper than it.

**Comment by brentvatne** [comment]
what is the real use case? fairly curious

**Comment by MrLoh** [comment]
Our app is tab based and has stack navigators nested in each tap, some screens are for a single focused task and shouldn’t allow switching in between to another tab, until done, so tabs must be disabled for specific tasks. I solved the thing with a custom tab bar component now that pulls in the navigation options of the current screen basically enabling the previous behaviour.

**Comment by origamih** [comment]
@MrLoh I have the same use-case here. Still looking for an elegant solution without too much hacking

**Comment by MrLoh** [comment]
@origamih 

when you define your custom TabBar, you can do something likes this: 

```js
const tabs = navigation.state.routes;
const activeTab = tabs[navigation.state.index];
// don't show tab bar on android if in nested screen
if (Platform.OS === 'android' && activeTab.index > 0) return null;
// get routeName of active route 
const activeRouteName = activeTab.routes[activeTab.index].routeName;
if (routeNamesWithoutTabBar.includes(activeRouteName)) return null;
return ...
```

**Comment by jaschaio** [comment]
@MrLoh Can you post some more code? I have the exact same use case as you and this worked fine in before `2.0.0`.

This is the fairly simplified RouteConfig I am currently using:

```
import React from 'react';
import { createBottomTabNavigator, createStackNavigator, HeaderBackButton } from 'react-navigation';

// […] Importing screen components

/** 
 * Stack Navigator which should show the Tab Bar on the main Screen but hide it on the subscreens
 **/
const SettingsRouteConfig = {
    SettinsMain: {
        screen: Settings,
        navigationOptions: {
            tabBarLabel: 'Settings',
            title: 'Settings',
        }
    },
    SettingsSubpage: {
        screen: SettingsSubpage,
        navigationOptions: {
            title: 'FAQ',
            tabBarVisible: false, // <-- This used to work before but is no longer working
        }
    }
}

const SettingsNavigator = createStackNavigator( SettingsRouteConfig );

// […] Other StackNavigators that follow the same pattern as above

/**
 * Tab Navigator which should only be shown on the Main Screens
 **/
const TabRouteConfigs = {
    Main: {
        screen: MainNavigator
    },
    Messages: {
        screen: Messages
    },
    Settings: {
        screen: SettingsNavigator
    }
};

const BottomTabNavigatorConfig = {
    lazy: true,
    tabBarOptions: {
        // [...] Tab Bar Configuration
    }
}

const Tabs = createBottomTabNavigator( TabRouteConfigs, BottomTabNavigatorConfig );

export const RouteConfigs = {
    Home: {
        screen: Tabs,
        navigationOptions: {
            header: null,
            gesturesEnabled: false
        }
    },
    Login: {
        screen: Login
    }
}
```

**Comment by ZackTRobertson** [comment]
@jaschaio

You can try something like this, as I just had to deal with a similar issue. Got this from the snack expo brentvatne  had recommended for dealing with this problem so not my idea.

```
//create your stack navigator

const SomeStack = createStackNavigator({
    SomeIndex: SomeIndex,
    AnotherIndex: AnotherIndex,
})

//set tab bar options here use whatever logic you like to enable/disable tab bar
SomeStack.navigationOptions = ({ navigation }) => {
    if(navigation.state.index==1){
        return {
            tabBarVisible: false,
        };
    }
    return {
        tabBarVisible: true,
    };
};
```

Then add the stack in a tab navigator and you are done.

**Comment by lucky-xiaohu** [comment]
I have same issue, below is my way:

```
export default myTabNav = createBottomTabNavigator({
    home: {
        screen: HomeNavigator,
        navigationOptions: ({ navigation }) => ({
            tabBarVisible: homeTabbarVisible(navigation),
        }),
    },
});

const homeTabbarVisible = (navigation) => {
    const routes = navigation.state.routes;
    if (routes && routes,length > 0) {
        const route = routes[routes.length - 1];
        if (route.routeName == 'homeBarcode') {  // match by last routeName
            return false;
        }
    }
    return true;
}
```

**Comment by SKempin** [comment]
The documented option worked for me on V2:

https://reactnavigation.org/docs/en/navigation-options-resolution.html#a-tab-navigator-contains-a-stack-and-you-want-to-hide-the-tab-bar-on-specific-screens

**Comment by AWDGroup** [comment]
@SKempin Thanks for the answer. This method works when I use "createStackNavigator", but seems to be broken when I use "createMaterialBottomTabNavigator". Any thoughts? 
@brentvatne

**Comment by SKempin** [comment]
@AWDGroup I have only used this with `createStackNavigator` I'm afraid. Do you have a code snippet?

**Comment by AWDGroup** [comment]
@SKempin I'm sorry I meant "createBottomTabNavigator"
You can use the same documented example and replace the "createBottomTabNavigator" with createMaterialBottomTabNavigator

    import { createMaterialBottomTabNavigator } from 'react-navigation-material-bottom-tabs';

    const FeedStack = createStackNavigator({
      FeedHome: FeedScreen,
      Details: DetailsScreen,
    });

    const TabNavigator = createMaterialBottomTabNavigator({
      Feed: FeedStack,
      Profile: ProfileScreen,
    });

    const AppNavigator = createSwitchNavigator({
      Auth: AuthScreen,
      Home: TabNavigator,
    });

    const FeedStack = createStackNavigator({
      FeedHome: FeedScreen,
      Details: DetailsScreen,
    });

    FeedStack.navigationOptions = ({ navigation }) => {
      let tabBarVisible = true;
      if (navigation.state.index > 0) {
        tabBarVisible = false;
      }

      return {
        tabBarVisible,
      };
    };

**Comment by JelaniThompson** [comment]
Having the same issue as @AWDGroup currently.

**Comment by SKempin** [comment]
@AWDGroup I'm confused what you are trying to achieve? Can you upload a demo repo?

You cannot hide tabs on the TabNavigator as it's purpose is to display tabs, I think you are probably using the wrong nested structure. If you have tabs on your root screen but do not want them on your nested screens then you should use `createStackNavigator` for those nested screens. 

Also you have `FeedStack` defined twice in your code snippet.

**Comment by SKempin** [comment]
@AWDGroup @JelaniThompson Please see https://reactnavigation.org/docs/en/tab-based-navigation.html#a-stack-navigator-for-each-tab

Hopefully this solves your issue(s)?

**Comment by JelaniThompson** [comment]
@SKempin Thanks a ton, that helped me get it working. You rock!

**Comment by JoshWhite** [comment]
I wanted to reference the screen by name, rather than index (like above), as I think it's more readable. 
I used something like this:

```
const MyStack = createStackNavigator({
  'myScreen': {
      screen: MyScreenComponent
  },
  'myOtherScreen': {
      screen: MyOtherScreenComponent
  },
})

MyStack.navigationOptions = ({ navigation }) => {
  const currentScreenPath = navigation.router.getPathAndParamsForState(navigation.state).path
  const isMyScreen = currentScreenPath  === 'myScreen'
  return {
    tabBarVisible: isMyScreen === false
  }
}

const MyTabs = createBottomTabNavigator({
  MyStack,
  MyOtherStack
})
```

Hope this helps :)
