### ISSUE TITLE
Can not get navigation lifecycle event after Redux integration

### ISSUE THREAD

**Issue by firetheworld** [react-navigation/react-navigation#3987]
Hi, I have done Redux integration follow the guide (https://reactnavigation.org/docs/redux-integration.html).After that I can not got navigation lifecycle envent,Can you pls help me?

---

### Current Behavior

This is my code, and I got no logs
```
const addListener = createReduxBoundAddListener("root");

class NavigatorView extends Component {
  render() {
    return (
      <AppNavigator
        navigation={addNavigationHelpers({
          dispatch: this.props.dispatch,
          state: this.props.nav,
          addListener
        })}
      />
    );
  }
}
```

```
this._s0 = this.props.navigation.addListener("didFocus", this._onEvent);

_onEvent(event) {
    console.log("_onEvent", event);
}
```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 0.51.0
| react-native     | 1.2.0

**Comment by brentvatne** [comment]
hi there!

just wanted to point out this tidbit from the issue template:

> Bugs with react-navigation must be reproducible *without any external libraries that operate on it*. This means that if you are attempting to use Redux or MobX with it and you think you have found a bug, you must be able to reproduce it without Redux or MobX in this report. Redux related issues belong in [react-navigation-redux-helpers](https://github.com/react-navigation/react-navigation-redux-helpers), and we do not have any first-class integration with MobX at the moment.

could you repost this to the redux helpers issue as mentioned above?

**Comment by computerjazz** [comment]
Are you passing the react-navigation middleware into `createStore`?

```javascript
import {createStore, applyMiddleware} from 'redux';  
import reducer from './reducer';  

const middleware = createReactNavigationReduxMiddleware("root", state => state.nav);

const store = createStore(
    reducer,
    applyMiddleware(middleware)
  );

<Provider store={store}>
... etc
```

**Comment by jsina** [comment]
@firetheworld have you found any solution for your problem, because I have yours and I haven’t found anything yet.
