### ISSUE TITLE
custom contentComponent no status bar offset

### ISSUE THREAD

**Issue by James2516** [react-navigation/react-navigation#3989]
### How to reproduce

https://snack.expo.io/r1XJf3ynf

If I do not define the `contentComponent`, I'll get this:
![](https://i.imgur.com/EgQTf07.png)

If I define it to be the same as the [default one used in react-navigation](https://github.com/react-navigation/react-navigation/blob/master/src/navigators/createDrawerNavigator.js#L16), I get this instead
![](https://i.imgur.com/1QOJJKF.png)

What's causing the offset not to be present in the default version?

**Comment by Ashwin-Mothilal** [comment]
Immediate solution will be put DrawerContent inside SafeAreaView.

**Comment by James2516** [comment]
@Ashwin-Mothilal that's exactly what I did, pls see the snack (the component is copied from the default implementation in `react-navigation`, so I'm not sure why the behavior is different from it).

A workaround is to add statusBarHeight offset to the component.
