### ISSUE TITLE
Quickly press on a TabBar icon after calling `goBack` triggers another mount of the old screen

### ISSUE THREAD

**Issue by jamesbechet** [react-navigation/react-navigation#3990]
First of all, thank you for this library.

Regarding the issue that I'm encountering at first I thought it was pretty hard to reproduce, but now I can reproduce it every single time.

---

### Current Behavior
I currently have something like that:
```
RootNavigator (StackNavigator)
  MainNavigator (StackNavigator)
     ScreenA
     TabBar (TabBarNavigator)
        ScreenWithLinkToScreenA
        ScreenB
        ScreenC
```
- So I go to `ScreenWithLinkToScreenA`, I press on the link and navigate to `ScreenA`
- `ScreenA` doesn't have the TabBar
- `ScreenA` has the top left back button
   - If you press it does a `navigation.goBack(null)`
     - It navigates back to `ScreenWithLinkToScreenA` where the TabBar is
     - Everything is fine, here are the lifecycle hooks I get:
        ```
         constructor -> render  -> componentDidMount -> componentWillUnmount
        ```
   - However, when you press the back button and while it's navigating you try to fast press several times on `ScreenB` or `ScreenC` icons. Here are the lifecycle hooks I get:
      ```
       constructor -> render  -> componentDidMount -> componentWillUnmount
       constructor -> render  -> componentDidMount -> componentWillUnmount
      ```
    - It seems to quickly mount `ScreenA` after it has been unmounted.
    - And `ScreenB` or `ScreenC` have nothing to do with `ScreenA`

After trying it multiple times it actually happens toward the end of the animation. The last ~50 px or less. If you press any icon (other than the active one), it will try to re-render `ScreenA`.
At the beginning of the animation the TabBar icons, seems to be disabled. There must be some kind of overlay over the view. However, toward the end of it they become pressable.

I have tried using `tabBarOnPress` to see if they were any differences with `previousScene` and `scene`, with and without the issue but didn't find anything.

### Expected Behavior

- Don't re-mount a screen that has just been unmounted.
- Disable the actions while the screen is completely unmounted.

### How to reproduce
Use a real device to reproduce it: https://snack.expo.io/rJ9kmbl3G
I'm currently using an iPhone 8.
It's better to copy the code and try it locally so you can see the logs.
So I was able to reproduce it very easily with my example:
-  Press on `Navigate to Screen A` -- it navigates to screenA
- Press on top left back button -- it navigates back
- While it's navigating back spam the middle icon (which is screen B) 

Here are my logs:
```
18:38:49: ScreenA: constructor
18:38:49: ScreenA: render
18:38:49: ScreenA: componentDidMount
18:38:54: ScreenB: render
18:38:54: ScreenA: componentWillUnmount
18:38:54: ScreenB: render
18:38:54: ScreenA: constructor
18:38:54: ScreenA: render
18:38:54: ScreenA: componentDidMount
18:38:54: ScreenA: componentWillUnmount
````

Let me know if you have any questions or if you want more details.
I said "spam" but when you get used to it, just one press toward the end of the animation and it triggers this behaviour.
I know it's an issue the average user might not encounter often, but it won't make me sleep at night if I push my app in Production knowing this issue is happening to me.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.5.11
| react-native     | https://github.com/expo/react-native/archive/sdk-26.0.0.tar.gz
| node             | 9.11.1
| npm or yarn      | npm@5.8.0

**Comment by brentvatne** [comment]
thanks for the detailed report! moving it to an umbrella issue for this bug in transitioner: https://github.com/react-navigation/react-navigation/issues/4155
