### ISSUE TITLE
unable to reduce switch delay in tab navigator

### ISSUE THREAD

**Issue by ketankulkarni** [react-navigation/react-navigation#3993]
expected output -
tabs should  switch as soon as it is touched without delay 

actual output - 
tab gets switched when you touch and remove finger  

following properties has been set in tab navigator
animationEnabled: false,
swipeEnabled: false,
lazy: false,

**Comment by ericvicenti** [comment]
Maybe we could add an option for this, or change the default behavior.

Why is "tab-change-on-touch-down" the expected output, instead of touch up? Are there other apps that do this? What OS and tab style are you using?

**Comment by ketankulkarni** [comment]
well, its an application specific requirement

**Comment by brentvatne** [comment]
hi there! if you'd like to see this feature in react navigation, please [create a feature request](https://react-navigation.canny.io/feature-requests) for it. thanks!
