### ISSUE TITLE
Redirect doesn´t load asyncstorage until full refresh

### ISSUE THREAD

**Issue by hecmonn** [react-navigation/react-navigation#3998]
I am using react-navigation for a user-logged app.
If the user is logged redirects to the App stack, if it is not to the Login/Sing up stack. 
This functions without a problem using SwitchNavigator. However when I am in the Login Stack and successfully, the App stack gives me that the variables from the asyncstorage token are null. However if I reload the app, the problem is gone. 

`this.props.login({identifier:username,password})
            .then(
                async r=>{
                    if(r.data.isLogged){
                        const decodedToken=jwtDecode(r.data.token);
                        await AsyncStorage.setItem('auth',r.data.token)
                        .then(this.props.validateAuth(decodedToken))
                        .then(r=>{
                            this.props.navigation.navigate('App')
                        })
                        .done();
                    }
                    else{
                        this.setState({errors:r.data.errors.form});
                    }
                }`

This happens as well after submitting a content, I redirect to App stack and gives me the same error. 

Any ideas?

**Comment by ericvicenti** [comment]
I can't tell what the issue is, based on what you've posted here.

Please post a simplified example of the bug next time:

https://stackoverflow.com/help/mcve
