### ISSUE TITLE
React Navigation from StackNavigator to TabNavigator not working

### ISSUE THREAD

**Issue by olympikesoft** [react-navigation/react-navigation#4001]
This is my APP.JS defined:

```
const AppStackNavigator = StackNavigator({
  Authentication:{
    screen: Authentication
  },
  MainScreen:{
    screen:MainScreen
  },
  SingleConversation:{
    screen: SingleConversation
  }
});

```
I have defined on click inside MainScreen that have a `TabNavigators`.

Now i want redirect from **'Tab1'** to **SingleConversation**, HOW I CAN DO IT THAT?

```
 _onPressItem = (item) => { 

  console.log(JSON.stringify(this.props.navigation, null, 3))
 this.props.navigation.navigate('SingleConversation', {name: 'Diego', age: 24,})
};
```
I get this:

`{ "state": { "key": "MessagesTab", "routeName": "MessagesTab" } }`

**Comment by ericvicenti** [comment]
It should work to do `.navigate('SingleConversation', {..})` from inside a sub-screen MainScreen, as you've shown.

It looks like it should work, so I can't see the bug here. If its still misbehaving, please post a minimal example that demonstrates the issue, using expo snack or a little test repo.
