### ISSUE TITLE
No changelog in latest versions

### ISSUE THREAD

**Issue by nirpeled** [react-navigation/react-navigation#4002]
Hey everyone,
I noticed that the changelog stopped in version 1.5.2, any ideas why?
Thanks!

**Comment by ericvicenti** [comment]
Err, whoops! The new releases are minor bugfixes, and you can see the history of them here:

https://github.com/react-navigation/react-navigation/commits/1.x

We will try to update the changelog soon, but we'd greatly appreciate a pull request if you have a few minutes to help us out with it!
