### ISSUE TITLE
how to goBack to the parent screen and replace the parent screen?

### ISSUE THREAD

**Issue by taslimR** [react-navigation/react-navigation#4005]
i know how to go back to parent screen. but I need to know how can i go back to the parent screen and can replace it at the same time or can reload the parent screen... any suggestions??

**Comment by ericvicenti** [comment]
in the upcoming version of react nav (v2) you can call `props.navigate("ParentRouteName", {...params})`, which will now take you back to the screen in the stack.

In `v1.x`, you can try dispatching multiple actions at once, or customizing your router.
