### ISSUE TITLE
SafeAreaView incompatible with list items

### ISSUE THREAD

**Issue by TheAlmightyBob** [react-navigation/react-navigation#4008]
Native iOS UITableViews inset the individual cell contents (rather than the entire TableView or the ScrollView content) according to the safe area, via `insetsContentViewsToSafeArea`. For example, you can see that the cell background and separators extends outside the safe area, but the actual labels/controls are kept within the safe area:

![image](https://user-images.githubusercontent.com/7707864/38888357-39be6c9e-4230-11e8-85df-065847eb0378.png)

Although React Native's `FlatList` does not support `insetsContentViewsToSafeArea`, the behavior can be replicated by using its `SafeAreaView` in `renderItem` (the blue background is the cell "content," the red lines are the item separators):
![image](https://user-images.githubusercontent.com/7707864/38891683-e9f96646-4239-11e8-9ea0-4f5430aa2d9d.png)

However, React Native's `SafeAreaView` is incompatible with react-navigation's tabs (#3767) and this technique does not work with react-navigation's version of `SafeAreaView` (i.e. https://github.com/react-community/react-native-safe-area-view ), which winds up randomly adding extra vertical margins to items:
![image](https://user-images.githubusercontent.com/7707864/38888709-5b5f31ca-4231-11e8-8126-ea78bca97101.png)

---

### How to reproduce

- Use `exp init` to create a new (plain, non-tabs) project
- Add `react-navigation` to it
- Replace `App.js` with the following gist: https://gist.github.com/TheAlmightyBob/367ffd6337c04be3e5d5b963017fc2c1

@davepack

**Comment by davepack** [comment]
Just tested but don't have time to debug. There's several weird things going on when I use that code and some of it seems to be an issue with FlatList.

To prevent the random padding, add `forceInset={{ vertical: 'never' }}`.

Personally, I'd play around with different combos of `forceInset` and placements of SafeAreaView (e.g. nest the FlatList inside a SafeAreaView with `{left='always', right='never'}`) to see if you can figure out a workaround. Pretty sure FlatList is causing the main issues here, not sure why.

**Comment by brentvatne** [comment]
moving to umbrella issue

**Comment by ShepelievD** [comment]
U can use the following:
```
import { SafeAreaView } from 'react-navigation'

<FlatList ... ListFooterComponent={<SafeAreaView forceInset={{ bottom: 'always' }} />} />

```

just play with `forceInset`, I needed that from the bottom
