### ISSUE TITLE
Unable to make Drawer navigation doc example run as snack

### ISSUE THREAD

**Issue by realtebo** [react-navigation/react-navigation#4009]
Referrring to this page of the doc: https://reactnavigation.org/docs/drawer-based-navigation.html 

Can the staff, please, provide a full and working sneak? 

I'm not able to make a working one, and could be usefull to see a working example, like for other page of the docs.

**Comment by tkserver** [comment]
I was just about to post the same comment.

**Comment by ericvicenti** [comment]
Can you provide a link to the broken snack and re-open the issue?

**Comment by tkserver** [comment]
The link in the first post is the link.  It isn't that snack is broken. There is NO link to a snack. The other components have a link below them saying "run this code..."  This one doesn't.
