### ISSUE TITLE
navigate to another page after redux action

### ISSUE THREAD

**Issue by jsina** [react-navigation/react-navigation#4011]
How could I navigate for example from **registerPage** to **profilePage** after redux action's done. as react-navigation document we probably do not need to integrate react-navigation to redux, so I don't want to do that. as you see below there is a `userRegister` action. I actually want after everything's done navigate user to another page from **Register** page. I'm user **NavigationActions** but after the action the rout **does not change.**

```
import { AsyncStorage } from 'react-native';
import { NavigationActions } from 'react-navigation'

import { register } from '../services/user.services';
import { userConstants } from '../constants/user.constants';
import * as consts from '../constants/consts';


export default function userRegister(user) {
  const requestOptions = {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(user),
  };
  return (dispatch) => {
    dispatch({
      type: userConstants.REGISTER_REQUEST,
      payload: {},
    });

    fetch(consts.END_POINT_REGISTER, requestOptions).then(response => response.json())
      .then((responseJson) => {
        console.log(responseJson, ' responseJson')
        AsyncStorage.setItem('userToken', 'abc');

        // AsyncStorage.setItem('user', response.data);
        dispatch({
          type: userConstants.REGISTER_SUCCESS,
          payload: responseJson.data,
        });
        dispatch(NavigationActions.navigate({ routeName: 'Login' }));
      }).catch((err) => {
        dispatch({
          type: userConstants.REGISTER_FAILURE,
          payload: err,
        });
      });
  };
}


```

**Comment by ericvicenti** [comment]
`dispatch(NavigationActions.navigate({ routeName: 'Login' }));`

This is the important line and it looks fine to me. Maybe your router is not set up properly with redux? Make sure you have followed this guide:

https://reactnavigation.org/docs/redux-integration.html

Also, you don't need to have your navigation state in redux. It might be easier to call `this.props.navigate` when your registration form succeeds.

**Comment by tmaly1980** [comment]
@jsina, this.props.navigate is usually in your component, which gets called in componentWillRecieveProps . Usually redux/sagas will set a flag when an operation starts and clear it when it completes. You'd do:

```
componentWillReceiveProps(newProps) {
  if(!newProps.finished && this.props.finished) {
    this.props.navigate('SomewhereScreen');
  }
}
```

'finished' is set by redux and retrieved in mapStateToProps.

**Comment by codekiln** [comment]
@tmaly1980, [now that componentWillReceiveProps is deprecated](https://reactjs.org/docs/react-component.html#unsafe_componentwillreceiveprops), what is the correct lifecycle hook for this?

**Comment by sahilpatel16** [comment]
@tmaly1980 ,I have been using this form of navigation extensively in my apps but now I am facing a problem.  Props `finished` now can not be used anywhere else right? Because if I update it in any other screen and this previous screen is present in the back stack, then it is going to execute that code block. 

I use this same technique to show alert dialogs for error messages. Since many screens are listening to changes made to `error` state and they keep listening in back stack too, I end up getting multiple alert boxes when `error` state is updated.

Can't really find any fix for this problem.

**Comment by goranefbl** [comment]
This worked for me, you get access to navigator through refs and you can use it then anywhere in the app to dispatch https://reactnavigation.org/docs/en/navigating-without-navigation-prop.html

**Comment by forrest23** [comment]
> This worked for me, you get access to navigator through refs and you can use it then anywhere in the app to dispatch https://reactnavigation.org/docs/en/navigating-without-navigation-prop.html

thank you very much! This worked for me!

**Comment by reactdevrocks** [comment]
@goranefbl doesn't worked for me with redux.
```const store = createStore( reducer);

export default class App extends Component
{
  render() {
      return (
          <Provider store={store} >
            <AppNavigator
              // ref={navigatorRef => {
              //   NavigationService.setTopLevelNavigator(navigatorRef);
              // }}
            />
        </Provider>
      )
  }
}```
