### ISSUE TITLE
V2: create*TabNavigator cannot be standalone?

### ISSUE THREAD

**Issue by rborn** [react-navigation/react-navigation#4014]
It seems that you cannot use a TabNavigator as the root of the app.

### Current Behavior

- create any `TabNavigator` and try to use it as main root of the app
- try to change the tab by clicking on a tab
- kboom (see screenshot)
![simulator screen shot - iphone 7 - 2018-04-18 at 15 34 51](https://user-images.githubusercontent.com/406409/38935234-22c11322-431e-11e8-9152-543e00a30971.png)

### Expected Behavior

- Work like Stack or Switch navigator

### How to reproduce

```
// App.js

const TabNav = createBottomTabNavigator({
    One: { screen: OneScreen },
    Two: { screen: TwoScreen }
});

export default () => {
    return <TabNav />;
};

// export default createSwitchNavigator({
//     Tab: { screen: TabNav }
// });

```
If you wrap the Tab Navigator with a single route Switch navigator will work just fine (just switch the commented code in the above snippet)

Thank you 🤗

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |2.0.0-rc.2
| react-native     |0.54.4
| node             | 8.11.0
| npm or yarn      |1.5.1

**Comment by MichelDiz** [comment]
Did u tried your code with this https://reactnavigation.org/docs/connecting-navigation-prop.html ?

With "withNavigation" you can use the navigation prop from any component.

**Comment by rborn** [comment]
@MichelDiz I feel that the navigators should all behave the same, for consistency.
The Stack and Switch work just fine, the Tabs and Drawer don't. 

IMHO they all should be usable as root in the app so the users don't have to use tricks like this to make it work 🤗

**Comment by jozan** [comment]
`withNavigation` only works in the context of navigation meaning it can be only used inside of navigation component tree otherwise it doesn't work.

I ended up doing this:

```js
export default createSwitchNavigator({
  App: TabNavigation
})
```

**Comment by brentvatne** [comment]
@rborn - this isn't anything specific to 2.0 or any particular navigator, you just need to be inside of some navigation context in order to access the prop. if you prefer, you can do this: https://reactnavigation.org/docs/navigating-without-navigation-prop.html

**Comment by rborn** [comment]
@brentvatne sorry but I don't really understand 😔
If I start the app with a TabNavigator, why switching tabs **clicking on the provided tabs** leads to a `navigation` not found crash?

It's not something that ** I  ** do, but the tab itself. Makes more sense?

**Comment by ericvicenti** [comment]
Actually I do think this is a real bug within v2 of the library- specifically, the tabs component has not upgraded to the new action creators API. I have sent a PR to fix it here: https://github.com/react-navigation/react-navigation-tabs/pull/12

**Comment by brentvatne** [comment]
merged that pr and released in latest rc version
