### ISSUE TITLE
Use TabNavigator in render method

### ISSUE THREAD

**Issue by LouisJS** [react-navigation/react-navigation#4015]
### Current Behavior

I followed the Authentication Flow provided by react-navigation.
So i'm having a SwitchNavigator with

- SignStack (Simple StackNavigator)
- AppTab (a TabNavigator which contains my app)
  - ConversationStack
  - SettingsStack

```
const AppTabNavigator = TabNavigator(
  {
    Conversation: {
      screen: ConversationStack
    },
    Settings: {
      screen: SettingsStack // this is a stack navigator
    }
  }
);

export default AppTabNavigator;
```

It works fine. Then, i had to setup a `WebSocket` initialisation when i'm logging in the app.
So i did something like

```
class AppNavigator extends React.Component {
  static childContextTypes = {
    cable: PropTypes.object
  };

  state = { cable: null };

  getChildContext() {
    return { cable: this.state.cable };
  }

  async componentDidMount() {
    this.setState({cable: RNActionCable.createConsumer() }); // setting up my Context var
  }

  render() {
    return <AppTabNavigator />;
  }
}

export default AppNavigator;
```

### Expected Behavior

I was expecting to use `AppTabNavigator` the same way i would use it if i was exporting it directly.
My issue is, I can't go back to my `SignStack` (from the SwitchNavigator) when i do this

I don't have this issue when i export directly my `AppTabNavigator`, but i need some lifecycle method for my WebSocket initialisation.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | "^1.5.9"
| react-native     | 0.54
| node             |  v9.5.0
| npm or yarn      | 4.6.1

**Comment by ericvicenti** [comment]
> i need some lifecycle method for my WebSocket initialisation.

It sounds like you can just use the screen event listener to subscribe on `willFocus`.

https://reactnavigation.org/docs/navigation-prop.html#addlistener-subscribe-to-updates-to-navigation-lifecycle

Next time you open an issue, please post a full example of what is broken!
