### ISSUE TITLE
V2: DrawerOpen is not working

### ISSUE THREAD

**Issue by rborn** [react-navigation/react-navigation#4016]
Hi, it seems that none of the `DrawerOpen/Close/Toggle` works
---

### Current Behavior
None of the below works:
`this.props.navigation.navigate('DrawerOpen' );`
`this.props.navigation.navigate({ routeName: 'DrawerOpen' });`

However this works:
`this.props.navigation.openDrawer();`

### Expected Behavior

It should work or we should update the docs

### How to reproduce
Just execute the code above

Thanks 🤗
### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |2.0.0-rc.2
| react-native     |0.54.4
| node             |8.11.0
| yarn      |1.5.1

**Comment by ericvicenti** [comment]
Correct, the API for this has changed, and it will be part of the v2 release notes. I'll fix the docs here: 
https://v2.reactnavigation.org/docs/en/drawer-based-navigation.html

**Comment by choo737** [comment]
> Correct, the API for this has changed, and it will be part of the v2 release notes. I'll fix the docs here:
> https://v2.reactnavigation.org/docs/en/drawer-based-navigation.html

The links returns 404 error.

**Comment by shravanteegala** [comment]
this.props.navigation.openDrawer();
its working fine.

**Comment by MuhammadUmairghufran** [comment]
> this.props.navigation.openDrawer();
> its working fine.

navigation.openDrawer is not a function. (In 'navigation.openDrawer()', 'navigation.openDrawer' is undefined)

onPress
    index.bundle?platform=ios&dev=true&minify=false:151585:32
touchableHandlePress
    index.bundle?platform=ios&dev=true&minify=false:45040:33
_performSideEffectsForTransition
    index.bundle?platform=ios&dev=true&minify=false:45646:36
_receiveSignal
    index.bundle?platform=ios&dev=true&minify=false:45575:46
touchableHandleResponderRelease
    index.bundle?platform=ios&dev=true&minify=false:45454:26
onResponderRelease
    index.bundle?platform=ios&dev=true&minify=false:44979:63
invokeGuardedCallbackImpl
    index.bundle?platform=ios&dev=true&minify=false:8736:21
invokeGuardedCallback
    index.bundle?platform=ios&dev=true&minify=false:8827:42
invokeGuardedCallbackAndCatchFirstError
    index.bundle?platform=ios&dev=true&minify=false:8831:36
executeDispatch
    index.bundle?platform=ios&dev=true&minify=false:9025:48
executeDispatchesInOrder
    index.bundle?platform=ios&dev=true&minify=false:9045:26
executeDispatchesAndRelease
    index.bundle?platform=ios&dev=true&minify=false:9140:35
forEachAccumulated
    index.bundle?platform=ios&dev=true&minify=false:9130:22
runEventsInBatch
    index.bundle?platform=ios&dev=true&minify=false:9234:27
runExtractedEventsInBatch
    index.bundle?platform=ios&dev=true&minify=false:9241:25
<unknown>
    index.bundle?platform=ios&dev=true&minify=false:10207:36
batchedUpdates$1
    index.bundle?platform=ios&dev=true&minify=false:20474:20
batchedUpdates
    index.bundle?platform=ios&dev=true&minify=false:10149:37
_receiveRootNodeIDEvent
    index.bundle?platform=ios&dev=true&minify=false:10206:23
receiveTouches
    index.bundle?platform=ios&dev=true&minify=false:10236:34
__callFunction
    index.bundle?platform=ios&dev=true&minify=false:2470:49
<unknown>
    index.bundle?platform=ios&dev=true&minify=false:2243:31
__guard
    index.bundle?platform=ios&dev=true&minify=false:2424:15
callFunctionReturnFlushedQueue
    index.bundle?platform=ios&dev=true&minify=false:2242:21
