### ISSUE TITLE
stackNavigator inside TabNavigator resets 

### ISSUE THREAD

**Issue by starba3** [react-navigation/react-navigation#4018]
it seems that using stackNavigator inside TabNavigator resets AsyncStorage values,
i have three main navigators, 2 are tabs and 1 stack.
```
const ProfileStack = StackNavigator(
    {
      `Profile: Profile,
      UpdatePassword: UpdatePassword,
    },
  );



const AuthStack = StackNavigator({ Signin: LoginScreen });

const StudentNavigator = TabNavigator(
  { 
    Home: HomeStudent,
    Profile: ProfileStack,
    Settings: SettingsStudent
  },

  {
    tabBarPosition: 'bottom',
    tabBarVisible: true,
  }
);

const DriverNavigator = TabNavigator(
    { 
      Home: HomeDriver,
      Profile: ProfileStack,
      Settings: SettingsDriver,
    },
    {
      tabBarPosition: 'bottom',
      tabBarVisible: true,
    }
  );

const switcher = SwitchNavigator(
  {
    AuthLoading: AuthLoadingScreen,
    Student: StudentNavigator,
    Auth: AuthStack,
    Driver: DriverNavigator,
  },
  {
    initialRouteName: 'AuthLoading',
  }
);
```

after logging in an AsyncStorage item with key `student` is used to make the change the default navigator to `StudentNavigator `.

the issue is when i switch pages inside `ProfileStack `; which is placed inside a `StudentNavigator` and `DriverNavigator` , it resets AsyncStorage items and i have to login again.

"react": "16.3.1",
"react-native": "0.55.2",
"react-navigation": "^1.5.11"

what is the cause of this issue and how to solve it?

**Comment by ericvicenti** [comment]
Your code example is incomplete (I don't see AsyncStorage being used)

Please file a new issue that has enough code to let us reproduce the error, otherwise we can't see what is broken.

https://stackoverflow.com/help/mcve
