### ISSUE TITLE
missing addNavigationHelpers on example

### ISSUE THREAD

**Issue by jsina** [react-navigation/react-navigation#4019]
in [ReduxExample](https://github.com/react-navigation/react-navigation/blob/master/examples/ReduxExample/src/navigators/AppNavigator.js) on file AppNavigator there is no `addNavigationHelpers` for passing props to the navigator. I've copy the incorrect code from the example and paste in below.
```
<AppNavigator
        navigation={{
          dispatch,
          state: nav,
          addListener,
        }}
      />
```
in fact the correct one is:
```
<AppNavigator
        navigation={addNavigationHelpers({
          dispatch,
          state: nav,
          addListener,
        })}
     />
```

**Comment by ericvicenti** [comment]
You're looking at the master branch, and the API has changed here in version 2, where addNavigationHelpers are no longer needed. You can look at the 1.x branch instead

**Comment by jiwenjiang** [comment]
if there is no `addNavigationHelpers` in v2.x.
plz update the docs......thx
