### ISSUE TITLE
Incorrect documentation for onTransitionEnd

### ISSUE THREAD

**Issue by Slessi** [react-navigation/react-navigation#4021]
API reference for [onTransitionEnd](https://reactnavigation.org/docs/transitioner.html#ontransitionend-function) specifies that it receives no parameters, however in your [StackView](https://github.com/react-navigation/react-navigation/blob/bbacabeba3b0b21502e0880458dcab4c9a4e3031/src/views/StackView/StackView.js#L28) it does

In my own code when using `<Transitioner />` I also receive props.

Using react-navigation version 1.5.11

**Comment by ericvicenti** [comment]
Could you please file an issue or pull request to the documentation repo? 

https://github.com/react-navigation/react-navigation.github.io
