### ISSUE TITLE
componentWillMount is deprecated ? componentWillReceiveProps is deprecate ?

### ISSUE THREAD

**Issue by oneroundseven** [react-navigation/react-navigation#4022]
ReactNativeJS: Warning: componentWillMount is deprecated and will be removed in the next major version. Use componentDidMount instead. As a temporary workaround, you can rename to UNSAFE_componentWillMount.
                                                           
Please update the following components: Container, Transitioner

Learn more about this warning here:
https://fb.me/react-async-component-lifecycle-hooks

ReactNativeJS: Warning: componentWillReceiveProps is deprecated and will be removed in the next major version. Use static getDerivedStateFromProps instead.
                                                           
Please update the following components: CardStack, Container, NavigationContainer, SafeView, Transitioner
Learn more about this warning here:
https://fb.me/react-async-component-lifecycle-hooks

ReactNativeJS: Warning: isMounted(...) is deprecated in plain JavaScript React classes. Instead, make sure to clean up subscriptions and pending requests in componentWillUnmount to prevent memory leaks.

**Comment by ericvicenti** [comment]
Known issue. This will be fixed in v2.

**Comment by skptricks** [comment]
Check out solution for this issue : https://www.skptricks.com/2018/10/warning-componentwillmount-is-deprecated-in-react-native.html

**Comment by wilau2** [comment]
@ericvicenti 
Is this by any chances related: 
![image](https://user-images.githubusercontent.com/5473183/56626130-6a451b80-660e-11e9-8a53-fd0f6e56f2a0.png)

```
 "react": "16.8.6",
    "react-native": "0.59.6",
    "react-navigation": "^3.8.1",
```

**Comment by ithustle** [comment]
+1

**Comment by honter36** [comment]
+1

**Comment by NicholasDwyer** [comment]
+1
