### ISSUE TITLE
navigation.setParams doesn't work property when navigate.navigate('DrawOpen') at the same time

### ISSUE THREAD

**Issue by DrakeXiang** [react-navigation/react-navigation#4029]
### Current Behavior

The tabBar seems toggles every other time as I toggle the drawer

### Expected Behavior

The tab bar should toggles every time correctly as I toggle the drawer

### How to reproduce
Demo: https://snack.expo.io/Skpvj5P2z

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.5.11
| react-native     | 0.55.3
| node             | 8.10.0
| npm or yarn      | yarn 1.3.2

**Comment by brentvatne** [comment]
this is a bug that falls out of the fact that we use a separate navigator for drawer routes. that said, this isn't the right way to be structuring this based on what you're trying to accomplish. if you instead do this:

```
import { TabNavigator, DrawerNavigator, TabBarBottom } from 'react-navigation';

import HomeScreen from './HomeScreen';


const HomeTab = TabNavigator(
  {
    Home: HomeScreen,
  },
  {
    tabBarComponent: TabBarBottom,
    tabBarPosition: 'bottom',
  }
);


const Router = DrawerNavigator(
  {
    HomeTab,
  },
);

export default Router;
```

then your problem will be solved, the drawer will appear above the tab bar and there is no need to hide it at all.
