### ISSUE TITLE
Nested StackNavigator over Map View

### ISSUE THREAD

**Issue by KchTT** [react-navigation/react-navigation#4030]
Hi, im trying to add a stacknavigator into a component over a MapView. When a do that i cant drag the map....can anybody help me?

Here is the example
[https://snack.expo.io](https://snack.expo.io/ry9yC6v3G)

Thankss

**Comment by vonovak** [comment]
Its hard to tell what you're after so it is hard to help. Can you describe your goal better?

**Comment by KchTT** [comment]
I need to be able to drag the map when I'm over de second stacknavigator and i can't.

**Comment by Tennen** [comment]
maybe you shouldn't put a StackNavigator in a MapView..

**Comment by KchTT** [comment]
It isnt IN a MapView, its OVER

**Comment by brentvatne** [comment]
hi there! this is a question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.
