### ISSUE TITLE
Default HeaderTitle excessive marginHorizontal

### ISSUE THREAD

**Issue by James2516** [react-navigation/react-navigation#4034]
[HeaderTitle.js](https://github.com/react-navigation/react-navigation/blob/3c3668c95295eb34e52ccdc46824753924be1396/src/views/Header/HeaderTitle.js#L21)
```
const styles = StyleSheet.create({
  title: {
    fontSize: Platform.OS === 'ios' ? 17 : 20,
    fontWeight: Platform.OS === 'ios' ? '700' : '500',
    color: 'rgba(0, 0, 0, .9)',
    textAlign: Platform.OS === 'ios' ? 'center' : 'left',
    marginHorizontal: 16,
  },
});
```
Why does the default header title use a huge margin of 16? 
And why does it need an alpha of 0.9?

**Comment by James2516** [comment]
16 to left + right margin causes even relatively short title to be truncated on smaller iOS devices.
Most apps would prefer title being closer to left/right header than getting truncated.
I think something like 5 would be more appropriate. 

As for the 0.9 alpha, not much noticeable difference so just wondering why it's added in the first place.

**Comment by brentvatne** [comment]
please repost an issue and phrase how this behavior deviates from expected behavior, with a clear statement of what the bug is
