### ISSUE TITLE
Statusbar iOS changed when present and dismiss from native.  

### ISSUE THREAD

**Issue by FaiChou** [react-navigation/react-navigation#4035]
<img width="888" alt="situation" src="https://user-images.githubusercontent.com/18500846/39096083-938e22cc-467d-11e8-97d3-5083903a5f5b.png">

This is a react-native project with five tab (using `react-navigation`), and every tab home screen was Statusbar dark-content:

```
<StatusBar backgroundColor="white" barStyle="dark-content" />
```

In the second tab, click one cell present to native controller which Statusbar was light-content, and then dismiss the native controller, the react-native statusbar will have a bad performance, it won't change back to dark-content.

And also the other four tab home screen will have an abnormal light-content change.

<img width="624" alt="affect" src="https://user-images.githubusercontent.com/18500846/39096168-dd9e471a-467e-11e8-9490-e55eee8b6612.png">

XCode setting:

![image](https://user-images.githubusercontent.com/18500846/39096159-bbbf1606-467e-11e8-9267-35a505290849.png)

PS. How I present to native controller: (with self-designed transition)

```
RCT_EXPORT_METHOD(goStartSingleChat) {
  dispatch_async(dispatch_get_main_queue(), ^{
    UIViewController *groupVC = [[ABCBook sharedInstance]getChooseMembersVCWithExceptData:nil WithType:[NSNumber numberWithInteger:SelectObjectType_None]];
    UINavigationController *presentNav = [[UINavigationController alloc] initWithRootViewController:groupVC];
    presentNav.transitioningDelegate = self;
    [self addScreenLeftEdgePanGestureRecognizer:groupVC.view];
    UIViewController *rootVC = [UIApplication sharedApplication].keyWindow.rootViewController;
    [rootVC presentViewController:presentNav animated:YES completion:nil];
  });
}
```

The self-designed transition was made to change present/dismiss style looks like push/pop.

I don't know it's react-native's fault or react-navigation's or just my code's problem, so I also give the issue to[ react-native](https://github.com/facebook/react-native/issues/18976).

Environment:
  OS: macOS High Sierra 10.13.4
  Node: 9.5.0
  Yarn: 1.5.0
  npm: 5.7.1
  Watchman: 4.9.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 2.3 AI-162.4069837

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.50.1 => 0.50.1

**Comment by vonovak** [comment]
The <StatusBar /> component simply does an imperative call to set the status bar styling when it is mounted or updated (with new props). My guess it that after you dismiss your view controller, the StatusBar component is not updated, and hence the Statusbar keeps its old styling. You need to set the status bar style after dismissing the view controller. 

This does not seem to be an issue with react-navigation so I will go ahead and close it. Also, please note that we require issues to have a runnable reproduction.

**Comment by FaiChou** [comment]
@vonovak  thank you. react native should add a listener when native controller dismissed.

```
const notifiManagerEmitter = new NativeEventEmitter(ReactNotifiManager);

this.l1 = notifiManagerEmitter.addListener(
        'dismissController',
        () => StatusBar.setBarStyle('dark-content'));

```

**Comment by yexiaosong** [comment]
I solve this problem, you need to rewrite `tabBarOnPress` callback option. The doc address:`https://reactnavigation.org/docs/en/tab-navigator.html`.
code: 
```javascript
Tabs = {
  Home: { screen: Home, navigationOptions: ({ navigation }) => ({
    tabBarIcon: ({ focused, tintColor }) => (
      <TabBarItem
        selectedImage={ require('../../assets/img/tabbar/home_active.png') }
        normalImage={ require('../../assets/img/tabbar/home.png') }
        focused={ focused }
        tintColor={ tintColor }
      />
    )
  , tabBarOnPress: (e) => {
      StatusBar.setBarStyle('dark-content')
      e.jumpToIndex(0)
    }})
  }}
```
