### ISSUE TITLE
How to use Header Back Image

### ISSUE THREAD

**Issue by johadi10** [react-navigation/react-navigation#4037]
I have checked the whole doc, [link here](https://reactnavigation.org/docs/stack-navigator.html#headerbackimage), and couldn't understand how to use `headerBackImage` prop on the navigationOptions of StackNavigator. Please someone should put me through.

**Comment by brentvatne** [comment]
`headerBackImage: {uri: 'path/to/image.png'}`

**Comment by hsavit1** [comment]
you need to use a function that returns an `<Image />` component
