### ISSUE TITLE
Unable to open drawer if Nav declared with JSX

### ISSUE THREAD

**Issue by riwu** [react-navigation/react-navigation#4039]
### How to reproduce
```
import React from 'react';
import { Button, Text } from 'react-native';
import { StackNavigator, DrawerNavigator } from 'react-navigation';

const StackNav = StackNavigator({
  main: {
    screen: (props) => <Text>{(props.screenProps || {}).text || "StackNav"}</Text>,
    navigationOptions: ({ navigation }) => ({
      headerLeft: (
        <Button
          title="Open Drawer"
          onPress={() => navigation.navigate('DrawerOpen')}
        />
      ),
      headerRight: (
        <Button
          title="Nav to child"
          onPress={() => navigation.navigate('child')}
        />
      ),
    }),
  },
  child: {
    screen: () => <Text>child</Text>,
  },
});

const StackNavWithScreenProp = () => <StackNav screenProps={{ text: 'StackNavWithScreenProp' }} />; 

const App = DrawerNavigator({
  StackNav: {
    screen: StackNav,
  },
  StackNavWithScreenProp: {
    screen: StackNavWithScreenProp,
  },
});

export default App;
```
https://snack.expo.io/@riwu/react-navigation-drawer-jsx

![](https://i.imgur.com/Z13wsB4.gif)

As seen in the gif, `StackNav` works fine but the drawer cannot be opened in `StackNavWithScreenProp` via `navigation.navigate('DrawerOpen')`, though `navigation.navigate('child')` works.

It works if I integrate with Redux and call `dispatch({ type: 'Navigation/NAVIGATE', routeName: 'DrawerOpen' })`.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.5.11
| react-native     | 0.54
| node             |  9.10.1
| yarn      | 1.5.1

**Comment by brentvatne** [comment]
this is not the correct way to nest navigators. if you run this locally on react-navigation@2.0.0 you will get an error to indicate as much. see this doc for more info: https://reactnavigation.org/docs/en/common-mistakes.html#explicitly-rendering-more-than-one-navigator
