### ISSUE TITLE
Navigate to a screen inside another stacknavigator while skipping the initial screen when going back

### ISSUE THREAD

**Issue by koswarabilly** [react-navigation/react-navigation#4041]
So i am trying to navigate to the second index of a nested stacknavigation

The route:

stacknavigator(
viewA,
viewB
)

viewB = stacknavigator(
viewBB,
viewC
)

---

### Current Behavior

i want to navigate to viewC from viewA. Successfully navigate to viewC but viewB follow over

### Expected Behavior

viewB do not follow at all when i try to navigate from viewA

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.5.11
| react-native     | 0.55.2
| node             | 9.11.1
| npm or yarn      | 5.8.0

**Comment by brentvatne** [comment]
hi there! this is a question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.
