### ISSUE TITLE
redux-persist migration needed whenever routes are modified

### ISSUE THREAD

**Issue by James2516** [react-navigation/react-navigation#4044]
In most apps (correct me if I'm wrong), we want the last opened screen (in a DrawerNavigator/TabNavigator) to be shown when the app restarts.

Am I right to say that Redux integration + persisting redux state is necessary to achieve this?

However, whenever the routes are modified in any way (add/remove, modify name), a [migration](https://github.com/rt2zz/redux-persist/blob/master/docs/migrations.md) has to be created to purge the entire stored navigation state (or create a complex migration function) for the new version to work, otherwise an `There is no route defined for key <new route>` error is thrown.

Is there a better way to do this?

**Comment by brentvatne** [comment]
hi there! this is a question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.
