### ISSUE TITLE
RFC: Pass props to navigationOptions

### ISSUE THREAD

**Issue by James2516** [react-navigation/react-navigation#4045]
I google around and it seems like the current workaround is calling `this.navigation.setParams` in `componentDidMount` which is unacceptable imo since it causes an unnecessary re-render.

If `navigation` and `screenProps` can be passed to `navigationOptions`, is it possible to pass the component's props to it as well?

**Comment by brentvatne** [comment]
https://github.com/react-navigation/rfcs
