### ISSUE TITLE
[V2.0.0-rc.*] - tabBarIcon not working with createMaterialTopTabNavigator

### ISSUE THREAD

**Issue by vdlindenmark** [react-navigation/react-navigation#4047]
At Slack I asked Brent if it was right that the]`createMaterialTopTabNavigator` inside v2 is ignoring `tabBarIcon` settings. He said it's supported, but I don't get it working...
I don’t know why.. but with this one the hole tabbar is gone. https://snack.expo.io/SJPjD5Ghz if you change `createMaterialTopTabNavigator` to `createTabNavigator` everything works.

This is my own code for a transparent topbar WITHOUT icons. If you change `createMaterialTopTabNagivator` to `createTabNavigator` and removed the style element, then you see the tabbar on the bottom WITH icons.
```export default createMaterialTopTabNavigator(
  {
    Workshops: WorkshopsStack,
    Logboek: LogboekStack,
  },
  {
    tabBarOptions: {
      tintColor: colors.white,
      activeTintColor: colors.white,
      inactiveTintColor: '#8e8e93',
      showLabel: true,
      lazyLoad: true,
      upperCaseLabel: false,
      indicatorStyle: {
        backgroundColor: colors.white,
        height: 3
      },
      style: [ mainStyles.addHeaderSpace, {
        elevation: 0,
        backgroundColor: 'transparent',
        borderTopWidth: 0,
        position: 'absolute',
        left: 0,
        right: 0,
        top: 0,
      } ],
      labelStyle: {
        fontFamily: "MuseoSans-500",
        fontSize: 12,
        fontStyle: "normal",
        letterSpacing: 1.5,
        textAlign: "center",
        color: colors.white,
        marginBottom: 10
      }
    },
    navigationOptions: ( { navigation } ) => ({
      tabBarIcon: ( { focused } ) => {
        const { routeName } = navigation.state;
        if (routeName === 'WorkshopsOverview') {
          if (focused) {
            return <Image source={require('../assets/images/workshopIconActive.png')}/>
          } else {
            return <Image source={require('../assets/images/workshopIconNonActive.png')}/>
          }
        } else {
          if (focused) {
            return <Image source={require('../assets/images/journalIconActive.png')}/>
          } else {
            return <Image source={require('../assets/images/journalIconNonActive.png')}/>
          }
        }
      },
    }),
  }
);
```

**Comment by dulmandakh** [comment]
It works for me on 2.0.0-rc.3, but I'm using icon fonts and here is my snippet. I

``` javascript
Home: {
    screen: HomeScreen,
    navigationOptions: {
      title: 'Home',
      tabBarIcon: ({ tintColor }) => <Icon icon='home' style={{ color: tintColor }} />
    }
}
```

**Comment by vdlindenmark** [comment]
For me it look like you're using the icons inside the tab itself, am I correct?
Maybe thats the hole point, because this issue only exists when I'm using `createMaterialTopTabNagivator`.

**Comment by brentvatne** [comment]
looks like there is a bug with snack when importing these tab navigators from 2.0.0-rc. see: https://snack.expo.io/rkMnYw1aM where i import directly from react-navigation-tabs instead. also, notice that i added `showIcon: true` to show the icons

**Comment by vdlindenmark** [comment]
OMG, sorry @brentvatne ... Only the `showIcon: true` was enough... Just forget that one...
Just a little confusing that showIcon is specifically needed for this, and not for the bottom variant.

But thanks!! :-)

**Comment by sunaryohadi** [comment]
Same problem. My case, both not showing any icon.
tabBarIcon and tabBarLabel in navigationOptions seem not affecting the bottomTabNavigator.
