### ISSUE TITLE
 does react-navigation not support  web platform any more?

### ISSUE THREAD

**Issue by pallyoung** [react-navigation/react-navigation#4048]
## react-navigation not support web platform
i used the react-navigation at my web project with the version 1.0.0-beta.21,and it runs well,but when i try to upgrade it to the latest version,error happens.and i also find that the docs removed the info about react-navigation on web ,and in package.json removed the property of module, so i guess,has react-navigation removed the support to web platform? and can i going on to  use react-navigation on my web project.

**Comment by brentvatne** [comment]
it does but it requires some configuration to do so. we don't actually support it as such out of the box right now. you can do `create-react-native-app yourappname --with-web-support` to see some basic webpack config to get this working. we'll have some better support for it in coming months.
