### ISSUE TITLE
TabBarBottom with absolute position

### ISSUE THREAD

**Issue by AmirHosseinSalari** [react-navigation/react-navigation#4049]
Hi, I tried to make a TabBarBottom like this and I used style position = 'absolute' and zIndex to raise the red button but it didn't work... 

![photo_2018-04-24_15-48-21](https://user-images.githubusercontent.com/38690265/39185018-e5b89fce-47da-11e8-9be1-9a6e317da8a1.jpg)

I got customized the tabBarComponent like this.

`import React from 'react';
import { View, StyleSheet, TouchableWithoutFeedback } from 'react-native';

const styles = StyleSheet.create({
  tabbar: {
    height: 49,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    borderTopWidth: 1,
    borderTopColor: '#000',
    backgroundColor: '#fff',
  },
  tab: {
    alignSelf: 'stretch',
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center'
  }
});

class TabBar extends React.Component {
  render() {

    const {
      navigation,
      renderIcon,
      activeTintColor,
      inactiveTintColor,
      jumpToIndex
    } = this.props;

    const {
      routes
    } = navigation.state;

    return (
      <View style={styles.tabbar}>
        {routes && routes.map((route, index) => {
          const focused = index === navigation.state.index;
          const tintColor = focused ? activeTintColor : inactiveTintColor;
          return (
            <TouchableWithoutFeedback
              key={route.key}
              style={styles.tab}
              onPress={() => jumpToIndex(index)}
            >
              <View style={styles.tab}>
                {renderIcon({
                  route,
                  index,
                  focused,
                  tintColor
                })}
              </View>
            </TouchableWithoutFeedback>
          );
        })}
      </View>
    );
  }
}

export default TabBar;
`

**Comment by brentvatne** [comment]
hi there! this is a question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.

**Comment by McDreamy** [comment]
@AmirHosseinSalari, may I know how you render the icon??

**Comment by AmirHosseinSalari** [comment]
@McDreamy 
hi, i solved this. First you should got customized your tabBottomComponeny like this. Then make a View and put two chiled View in it. One of them is your tab and the other should have transparent color.Then you can put  the center circle button with the absolute position and zIndex in the middle.
Also your tabbar style should have absolute position with right=0,left=0,bottom=0

**Comment by wuyunqiang** [comment]
@AmirHosseinSalari  hello I wanna make like that,but no effect in android.how I can do? please help me.

**Comment by AmirHosseinSalari** [comment]
@wuyunqiang  Hi, you should make a customized tabBarComponent then make 3 views. One for parent.Tow for child. One of this child is your tabbar and the other is nothing whith transparent color.Style them with zIndex and absolute position and don't forget to make tabbar with right,left,bottom equal 0.

**Comment by wuyunqiang** [comment]
ok I got.
![react-navigation](https://user-images.githubusercontent.com/13480948/41089270-0c820d5a-6a74-11e8-87af-c5f1c75122a9.png)
https://github.com/wuyunqiang/RNApp

**Comment by pera14** [comment]
> @McDreamy hi, i solved this. First you should got customized your tabBottomComponent like this. Then make a View and put two chiled View in it. One of them is your tab and the other should have transparent color.Then you can put the center circle button with the absolute position and zIndex in the middle. Also your tabbar style should have absolute position with right=0,left=0,bottom=0

@AmirHosseinSalari Thanks man, I've been struggling for days 😮‍💨 You made my day!!
