### ISSUE TITLE
Transition between not loaded screens in TabNavigator displays white page during animation

### ISSUE THREAD

**Issue by dblachut-adb** [react-navigation/react-navigation#4050]
### Current Behavior
```
TabNavigator({
  A: { screen: A },
  B: { screen: B },
  C: { screen: C },
  D: { screen: D },
  E: { screen: E },
}, {
    initialRouteName: "B",
    animationEnabled: true,
    swipeEnabled: false,
    navigationOptions: {
      tabBarVisible: false,
    },
    lazy: true,
  },
);

```
When the app starts and the `B` screen is displayed after using `navigation.navigate(D)` during the screen transition animation the white `C` screen is displayed for a split of a second. This is due to `C` not being loaded yet as I am using `lazy: true` flag.

### Expected Behavior
It would be nice if the screen would transition from `B` to `D` directly without showing screens that are located between them. Please note that this still may be problematic if used with `lazy: false` - when e.g. screen `C` would differ much from `B` and `D` the user could still observe the transition and it may not be desired is case the app is using its own navigation bar.

### How to reproduce
https://snack.expo.io/HJzwyPg6f
The app starts on `B` screen, use the button to navigate to `D`. During transition the black `C` screen is displayed (not yet loaded due to `lazy` flag).
Once the `C` Screen is loaded, navigating from `B` to `D` shows `C` during transition which can be seen by the user as it has different background and it may not be desired. IMHO some config flag like `transitionDirectly` would be nice.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.5.11
| react-native     | 0.55.3
| node             | v9.2.0
| npm     | 5.5.1

**Comment by brentvatne** [comment]
hi there. the example you pasted is not runnable. please create a full example on https://snack.expo.io/ so we can run it and see what you mean.

**Comment by dblachut-adb** [comment]
Hello, thank for the reply. Are you sure that description in words is not enough in this case? I guess I will try to prepare it later on.

**Comment by dblachut-adb** [comment]
@brentvatne Okay :+1:, I have updated the issue, please take a look.

**Comment by dblachut-adb** [comment]
@brentvatne could you please take off the "needs repro" flag?

**Comment by brentvatne** [comment]
thanks for updating it. this issue isn't really valid anymore because in 2.0 we removed `animationEnabled` on tab navigator. this isn't a common use case and we aren't interested in supporting it, if you'd like to implement this behavior you can create your own custom navigator to do so. you can simply fork one of the existing tab navigators and make the appropriate changes to do so. I'm sorry I don't have a better answer for you :(

**Comment by dblachut-adb** [comment]
No problem, thanks for taking a look and a detailed explanation!
