### ISSUE TITLE
Navigation actions skipping execution when button tapped too quickly

### ISSUE THREAD

**Issue by zaguiini** [react-navigation/react-navigation#4052]
Hi! I have a simple `TabNavigator` and I want to `dispatch` navigation actions from the parent component. It is "kinda" working. But...

### Current Behavior

When I `dispatch` multiple actions in a short period of time, it doesn't work. I mean, if I `dispatch` one navigation action and, after, let's say, 300ms, I dispatch another one: it works.

But, if I try to dispatch them too fast, the navigation actions doesn't get executed at all...

### Expected Behavior

The navigation actions should happen even it fastly dispatched

### How to reproduce

```js
import React from 'react'

import {
  BackHandler,
  Button,
  Platform,
  View,
  Text,
} from 'react-native'

import { TabNavigator } from 'react-navigation'

const FormNavigator = TabNavigator({
  PersonalInfo: () => <Text>Personal information</Text>,
  BillingInformation: () => <Text>Billing information</Text>,
  HouseInformation: () => <Text>House information</Text>,
}, {
  tabBarComponent: () => null,
  swipeEnabled: false,
  initialRouteName: 'PersonalInfo',
  backBehavior: 'none',
})


const navigate = (routeName, params) => ({
  type: 'Navigation/NAVIGATE',
  routeName,
})

export class FormView extends React.PureComponent {
  constructor(props) {
    super(props)

    this.routes = [
      'PersonalInfo',
      'BillingInformation',
      'HouseInformation',
    ]

    this.state = {
      activeStep: 0,
    }

    this.goToPreviousPage = this.goToPreviousPage.bind(this)
    this.goToNextPage = this.goToNextPage.bind(this)

    if(Platform.OS === 'android') {
      this.handleBackPress = this.handleBackPress.bind(this)
    }
  }

  componentDidMount() {
    if(Platform.OS === 'android') {
      BackHandler.addEventListener('hardwareBackPress', this.handleBackPress)
    }
  }

  componentWillUnmount() {
    if(Platform.OS === 'android') {
      BackHandler.removeEventListener('hardwareBackPress', this.handleBackPress)
    }
  }

  handleBackPress() {
    if(!this.state.finished && this.state.activeStep > 0) {
      this.setState(({ activeStep }) => ({
        activeStep: activeStep - 1,
      }))

      return true
    }

    return false
  }

  dispatchRoute() {
    const route = this.routes[this.state.activeStep]
    this.navigator.dispatch(navigate(route))
  }

  goToPreviousPage() {
    this.setState(({ activeStep }) => ({
      activeStep: activeStep > 0 ? activeStep - 1 : activeStep,
    }), this.dispatchRoute)
  }

  goToNextPage() {
    this.setState(({ activeStep }) => ({
      activeStep: activeStep < this.routes.length - 1 ? activeStep + 1 : activeStep,
    }), this.dispatchRoute)
  }

  renderWizard() {
    return (
      <View>
        <Button
          title="Previous page"
          onPress={this.goToPreviousPage}
        />

        <Button
          title="Next page"
          onPress={this.goToNextPage}
        />
      </View>
    )
  }

  render() {
    return (
      <React.Fragment>
        {this.renderWizard()}
        <FormNavigator
          ref={(navigator) => {
            this.navigator = navigator
          }}
        />
      </React.Fragment>
    )
  }
}
```

Just mount this component. Now quickly tap on "Next page" button, twice. It should only have one action dispatched and you should be at "Billing information" tab instead of "House information" one.

Now it is important to note that if we `throttle` the dispatch function, like this:

```js
import _ from 'underscore'
...
  constructor(props) {
    super(props)
    ...
    this.dispatchRoute = _.throttle(
      this.dispatchRoute.bind(this),
      300,
    )
  }
```

Both actions are dispatched and it successfully work. Why? I'm not saying that's a solution, but well, it would be nice to getting it to work without throttling. Another question: is this amount of time enough? `300ms`? What if the user has a low end device? Will it work the same? Confusing.

Am I doing something wrong? No, I don't want to integrate that `TabNavigator` into my Redux store.

### Your Environment

```
Environment:
  OS: Linux 4.13
  Node: 9.11.1
  Yarn: 1.6.0
  npm: 5.6.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.3.2
  react-native: 0.55.3
  react-navigation: 1.4.0
```

**Comment by brentvatne** [comment]
hi, please post your full example to https://snack.expo.io/ so we can just run it right away. also, you're using an old version of react-navigation, please only report against the latest version.

**Comment by zaguini** [comment]
Is `1.5.11` the recommended version?

**Comment by brentvatne** [comment]
the second block of code is not executable. make an example that i can just run to see it in action :) 1.5.11 is recommended right now until maybe next week when we release 2.0 proper

**Comment by zaguini** [comment]
Tested in the last stable version, no results.

I've made the snack, tho. https://snack.expo.io/SJzwZrkTz

Quickly tap in the buttons to reproduce the issue. Then toggle the switch on, double tap again and it should work after a short amount of time.

**Comment by petetastic** [comment]
I think this post is a similar problem (although @zaguini for me too the snack that you posted works as it should).

https://stackoverflow.com/questions/50046136/react-navigation-blank-screen-with-nested-tabnavigator-on-device-only

**Comment by zaguini** [comment]
Ok, I'll make it clearer.

# Expected behavior

Navigates to the third screen ("HouseInformation" in this case) with a **QUICK DOUBLE TAP**

## CASE A

Toggle the switch off, and then QUICKLY **DOUBLE** tap the "next page" button.

### Actual behavior

Navigates to the second screen ("BillingInformation"), despite the double tap on the button

## CASE B

Toggle the switch on, then QUICKLY DOUBLE TAP the "next page button"

### Actual behavior

It works as expected, but after a certain amount of time

**Comment by brentvatne** [comment]
I can't repro this, when I double tap as quickly as I possibly can it brings me to the third screen ("HouseInformation")

**Comment by zaguini** [comment]
Have you tried to double tap with the switch off?

**Comment by brentvatne** [comment]
yes, i followed the instructions that you provided

**Comment by mlazari** [comment]
@brentvatne I can reproduce with @zaguini's snack, but only on Android.
[demo.mp4.zip](https://github.com/react-navigation/react-navigation/files/1977588/demo.mp4.zip)
I've added a Text component to show the activeStep from the state. Here is the modified snack: https://snack.expo.io/HkPgTwh6f
It doesn't reproduce by firing two navigate actions in a row.

**Comment by mlazari** [comment]
@brentvatne It's also reproducible by firing second navigate action after a short timeout like this:
```
  dispatchRoute() {
    const _this = this;
    console.log('Navigate to BillingInformation');
    _this.navigator.dispatch(navigate('BillingInformation'))
    setTimeout(() => {
      console.log('Navigate to HouseInformation');
      _this.navigator.dispatch(navigate('HouseInformation'))
    }, 100);
  }
```

It's not reproducing all the time. I think it happens when the second navigate action fires while TabViewPagerAndroid is changing the tab.

When it changes correctly I see these logs:
```
App.js:91 Navigate to BillingInformation
TabViewPagerAndroid.js:89 _handlePageScrollStateChanged settling
TabViewPagerAndroid.js:89 _handlePageScrollStateChanged idle
App.js:94 Navigate to HouseInformation
TabViewPagerAndroid.js:89 _handlePageScrollStateChanged settling
TabViewPagerAndroid.js:89 _handlePageScrollStateChanged idle
```

Or these:
```
App.js:91 Navigate to BillingInformation
App.js:94 Navigate to HouseInformation
TabViewPagerAndroid.js:89 _handlePageScrollStateChanged idle
TabViewPagerAndroid.js:89 _handlePageScrollStateChanged settling
TabViewPagerAndroid.js:89 _handlePageScrollStateChanged idle
```

When the issue occurs (BillingInformation is shown instead of HouseInformation) I see these logs:
```
App.js:91 Navigate to BillingInformation
TabViewPagerAndroid.js:89 _handlePageScrollStateChanged settling
App.js:94 Navigate to HouseInformation
TabViewPagerAndroid.js:89 _handlePageScrollStateChanged idle
```

Packages
```
    "react": "16.3.1",
    "react-native": "0.55.3",
    "react-navigation": "^1.5.11",
```

**Comment by brentvatne** [comment]
ok, please create a new issue with a runnable repro case and the description of exactly what steps we can take to repro it
