### ISSUE TITLE
Can't dynamically change individual card styles

### ISSUE THREAD

**Issue by superfunkminister** [react-navigation/react-navigation#4053]
Given that you can set the cardStyle globally, e.g.

``` 
export default StackNavigator(
  {
    Home: { screen: Home },
	Other: { screen: Other }
  },
  { cardStyle: { backgroundColor: 'white' } }
);
```

is there a way to set styles on a per card basis? I.e. can I have each card have a different backgroundColor?

**Comment by brentvatne** [comment]
hi there! this is a question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.
