### ISSUE TITLE
app crashing after installing react-navigation@2.0.0-rc.3

### ISSUE THREAD

**Issue by dulmandakh** [react-navigation/react-navigation#4055]
## The issue tracker is reserved for bug reports only.

Tried to migrate to react-navigation@2.0.0-rc.* but app fails with below error. Then created a new project to confirm the bug, and reproduced.

I can install react-native-vector-icons and it error goes away. Maybe need to add react-native-vector-icons as dependency.

![simulator screen shot - iphone 6 - 2018-04-25 at 09 20 53](https://user-images.githubusercontent.com/178494/39221551-47391636-486a-11e8-9ee0-814ffc4095b2.png)

### Current Behavior

- App is crashing and fails to run

### Expected Behavior

- App should just run and be usable

### How to reproduce
- Remove react-navigation and react-native-vector-icons packages
- Then install react-navigation@2.0.0-rc.*  as described in blog post
```
yarn add react-navigation@^2.0.0-rc.1
```
- Try to run the app using react-navigation@2.0.0-rc.*

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.0.0-rc.3
| react-native     | 0.55.3
| node             | 9.11.1
| npm or yarn      | yarn@1.6.0

**Comment by pallyoung** [comment]
it seems the crash is not caused by react-navigation

**Comment by dulmandakh** [comment]
I suspect that it's using react-native-vector-icons somewhere, and didn't specified as dependency, but as devDependency.

Installed react-native-vector-icons as workaround, but need to remove react-native-vector-icons use or add it as dependency

**Comment by brentvatne** [comment]
moved to other issue
