### ISSUE TITLE
cannot switch between tabs with 2.0.0-rc.3 (crashing)

### ISSUE THREAD

**Issue by dulmandakh** [react-navigation/react-navigation#4056]
I created an tab navigator using below code snippet, and cannot switch between tabs because app is crashing

``` javascript
const Navigator = createBottomTabNavigator({
  Info: { 
    screen: Info
  },
  Review: {
    screen: Review
  }
})
```

![simulator screen shot - iphone x - 2018-04-25 at 09 49 02](https://user-images.githubusercontent.com/178494/39222538-d6dd8bf0-486f-11e8-9809-b7b1264eb186.png)

### Current Behavior

- App is crashing when I press on a tab

### Expected Behavior
- App should switch to the tab

### How to reproduce

- create React components and create tab navigator, then press on a tab 

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.0.0-rc.3
| react-native     | 0.55.3
| node             | 9.11.1
| yarn      | 1.6.0

**Comment by dulmandakh** [comment]
Fix PR is still waiting to merge into react-navigation-tabs repo (https://github.com/react-navigation/react-navigation-tabs/pull/12)

Please merge

**Comment by brentvatne** [comment]
published rc.4 with fix
