### ISSUE TITLE
Warning： isMounted(...) is deprecated in plain JavaScript React classes. 

### ISSUE THREAD

**Issue by sunneytree** [react-navigation/react-navigation#4057]
### How to reproduce

-when I Start a new project and then  do the React-Navigation demo ,The warning will appear。The demo url is https://reactnavigation.org/docs//hello-react-navigation.html.

    Warning： isMounted(...) is deprecated in plain JavaScript React classes. 

![qq 20180425101844](https://user-images.githubusercontent.com/28665327/39222951-0eaedac8-4872-11e8-8d96-fef24074bbf9.png)

![qq 20180425094334](https://user-images.githubusercontent.com/28665327/39222914-ced3b18a-4871-11e8-9f1f-449272922fc8.png)

-What should I do to solve this problem?

### My Environment
| software         |  Webstorm
| ---------------- | -------
| react-navigation |  1.5.11
| react-native     |  0.55.3
| node             |  v8.11.1
| npm or yarn      | yarn

**Comment by hawkup** [comment]
#3956

**Comment by hawkup** [comment]
dup: #3956

**Comment by sunneytree** [comment]
Thanks so much!

发自我的 iPhone
