### ISSUE TITLE
It should warn against using <Text> as title

### ISSUE THREAD

**Issue by ScottDikowitz** [react-navigation/react-navigation#4058]
### Current Behavior

-adding a \<Text> to the title property in navigationOptions properly renders the text component in the header
```
MyComponent.navigationOptions = {
    title: <Text style={{color: colors.blue}}>Don't be like me and make this mistake!</Text>
}
```
-But when navigating somewhere, you'll see confusing errors with the underlying Native code (Invariant Violation, not usable as a native method, etc)

### Expected Behavior

There should be a clear warning, eg, only raw strings allowed to set the title property

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |1.5.8
| react-native     |https://github.com/expo/react-native/archive/sdk-26.0.0.tar.gz
| node             |
| npm or yarn      |

**Comment by brentvatne** [comment]
pr welcome for this!

**Comment by briank621** [comment]
I can't seem to reproduce these errors on my device. I created a [snack](https://snack.expo.io/ryUuAWraM) with a <Text> in the navigationOptions.

**Comment by ScottDikowitz** [comment]
hi @briank621, thanks for the snack. I suspect it's because you're navigating with a SwitchNavigator, which doesn't render transitions. I modified your [snack](https://snack.expo.io/SJ7bl7Spz), try pressing 'show me more of the app'.

**Comment by Eyesonly88** [comment]
Thanks for making this issue. It helped me figure out why I was getting the Invariant Violation errors!

**Comment by brentvatne** [comment]
https://github.com/react-navigation/react-navigation/commit/bc01a4cd5701fd6f73861c14a578131950061f28
