### ISSUE TITLE
Stack Navigator Push screen from bottom to top

### ISSUE THREAD

**Issue by CoericK** [react-navigation/react-navigation#4068]
I have a StackNavigator nested, what Im trying to accomplish is given a button on Screen X_a, that navigates to X_b, X_b appears from bottom pushing to X_a to top until X_a disappears, and also making it recognize the gesture of sliding from top to bottom so the X_a screen smoothly pushes to X_b until it disappears, so far What I accomplished is to make the view  appears from top to bottom but i can make the gesture to work properly.
Here's something I done:

```
            X: {

                screen: StackNavigator({
                    X_a: {
                        screen: require('./A').default,
                    },
                    X_b: require('./B').default,

                }, {
                    navigationOptions: {
                        header: null,
                    },
                    animationEnabled: true,
                    swipeEnabled: true,
                    gesturesEnabled: true,
                    transitionConfig: () => ({
                        screenInterpolator: sceneProps => {
                            const {layout, position, scene} = sceneProps;
                            const {index} = scene;
                            const width = layout.initWidth;
                            const height = layout.initHeight;

                            return {
                                opacity: position.interpolate({
                                    inputRange: [index - 1, index, index + 1],
                                    outputRange: [0, 1, 0],
                                }),
                                transform: [{
                                    translateY: position.interpolate({
                                        inputRange: [index - 1, index, index + 1],
                                        outputRange: [-height, 0, height],
                                    }),
                                }]
                            };
                        },
                    }),
                    initialRouteName: 'X_a',
                }),
            },
```

Is this posible? I also was thinking on use TabNavigator hide the tabbar and enable some how "vertical tabs" 
Another option could be unify the 2 screens into one screen and use a library like react-navigation-swiper (top half of the image) but I would lose the ability to navigate to that Screen.
![](http://i.imgur.com/hP3f3oO.gif=300x)

**Comment by CoericK** [comment]
Please keep in mind that out there is the option to handle the stack as a modal, but modal will cover the screen, no push it .

**Comment by brentvatne** [comment]
hi there! this is a question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.

**Comment by brentvatne** [comment]
also -- if the modal option doesn't work as you would like, you may want to consider implementing your own navigator for this or opening a feature request for more customizable options on modal in a way that would suit your needs https://react-navigation.canny.io/feature-requests
