### ISSUE TITLE
Hiding a specific Tab in TabNavigator

### ISSUE THREAD

**Issue by JeremyBradshaw7** [react-navigation/react-navigation#4069]
I cannot find an answer to this - how do I completely hide or disable a specific tab in a TabNavigator?

I found the TabBarVisible property in navigationOptions but that seems to be something else - hiding all the tabs when on that tab - I want to remove a single tab completely from the tab bar, depending upon some state of the containing component. 

Also I may want to disable a single tab - show it greyed out but not respond to taps.

**Comment by brentvatne** [comment]
https://github.com/react-navigation/react-navigation/issues?utf8=%E2%9C%93&q=hide+a+Tab

hi there! this is a question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.

**Comment by brentvatne** [comment]
also https://react-navigation.canny.io/feature-requests/p/hiding-tab-from-the-tabbar

**Comment by JeremyBradshaw7** [comment]
I've found a way to do this so will document it here in case it helps anyone else. It seems you can create tab components on the fly inside other components, rather than always at the global level:

```
class IncludeTabs extends React.Component<Props, State> {

  private MyTabs;

    const screens = {};
    // can now add screens, if required conditionally based on props:
    screens['Tab1'] = { screen: Tab1Container };
    if ( … ) {
      screens['Tab2'] = { screen: Tab2Container };
    }

    this.MyTabs = TabNavigator( /* I'm using v1 but I think this will work in v2 as well */
      screens,
      { /* options */ }
    );
  }
  :
  render() {
    return (
        <this.MyTabs
          screenProps={{ … }}
        />
    );
  }
```
I'm not sure about changing MyTabs in componentWillReceiveProps in case any of the props that the tab visibility depends upon changes in the containing component - in my case that doesn't happen.

**Comment by misterpoloy** [comment]
I have an implementation similar to @JeremyBradshaw7 

The problem with `tabBarOptions` is that only hide the current navigation (tabs) for the selected screen. But does not hide/show the tabs.
```
tabBarOptions: {
      visible: false
    }
```
# Custom solution
I made some special class to achieve this using `createMaterialTopTabNavigator`

```
export default class CustomTabsNavigator extends Component {
  // Final navigation setup with screens
  TabsNavigation;

  constructor(props) {
    super(props);
    // Only this is necessary if you just want to hide/show without change it.
    this._setScreens();
  }
  // This is necessary if you want to hide/show depending on some user behavior
  componentDidUpdate(prevProps) {
    // Add your condition to avoid infinite renders
    if (prevProps.foo === this.props.foo) return;
    this._setScreens();
  }
  // Actual code to show/hide based on props.
  _setScreens = () => {
    const { isAdmin } = this.props;
    const screens = {};
    const settings = {
      tabBarOptions: {
        style: {...}
      }
    };
    // Set tabs depending on user and state
    if (isAdmin) {
      screens.Dashboard = {
        screen: DashboardScreen,
        navigationOptions: { ... }
      };
    }
    screens.Home = { screen: HomeScreen };
    this.TabsNavigation = createMaterialTopTabNavigator(screens, settings);
    // Since we are not using setState
    this.forceUpdate();
  };

  render() {
    // AppContainer is required in react-native version 3.x
    const { props } = this;
    const NavigatorTabs = createAppContainer(this.TabsNavigation);
    return <NavigatorTabs screenProps={{ ...props }} />;
  }
}
```
#Implementation of tabs:
```
<CustomTabsNavigator isAdmin={true} />

```

**Comment by suarezluis** [comment]
I made an npm package for that, check :
https://www.npmjs.com/package/react-navigation-selective-tab-bar

**Comment by kayrules** [comment]
In my case, I have successfully disabled / hide the "Center" tabbar item by giving null value to `screen` and `navigationOptions:tabBarOnPress` properties accordingly.

```
const TabNavigator = createBottomTabNavigator(
  {
    Home: {
      screen: HomeScreen,
    },
    Profile: {
      screen: ProfileScreen,
    },
    Center: {
      screen: () => null,
      navigationOptions: ({navigation}) => ({
        tabBarOnPress: () => null
      }),
    },
    Explore: {
      screen: ExploreScreen,
    },
    Inbox: {
      screen: InboxScreen,
    }
  }
);
```

**Comment by iamhussy** [comment]
> 
> 
> In my case, I have successfully disabled / hide the "Center" tabbar item by giving null value to `screen` and `navigationOptions:tabBarOnPress` properties accordingly.
> 
> ```
> const TabNavigator = createBottomTabNavigator(
>   {
>     Home: {
>       screen: HomeScreen,
>     },
>     Profile: {
>       screen: ProfileScreen,
>     },
>     Center: {
>       screen: () => null,
>       navigationOptions: () => ({
>         tabBarOnPress: () => null
>       }),
>     },
>     Explore: {
>       screen: ExploreScreen,
>     },
>     Inbox: {
>       screen: InboxScreen,
>     }
>   }
> );
> ```

worked for me, thank you soo much found you after a long struggle

**Comment by florian-milky** [comment]
Here is a simple solution if you want to have a hidden tab:

```
<Tab.Navigator>
    <Tab.Screen
      name="Home"
      component={HomeStack}
    />
    <Tab.Screen
      name="HiddenTab"
      component={HiddenTab}
      options={{
        tabBarButton: () => null,
        tabBarVisible: false, // if you don't want to see the tab bar
      }}
    />
  </Tab.Navigator>
```

**Comment by JeremyBradshaw7** [comment]
Yes @florian-milky seems much easier with the new version 5 API.

**Comment by DadouBordeaux** [comment]
For example, a search component accessible from the header :
Version createBottomTabNavigator

```Search: {
  screen: SearchStack,
  navigationOptions: {
    tabBarButton: () => null,
    tabBarButtonComponent: () => null,
    tabBarLabel: () => null,
  },
},```

**Comment by Lcharvol** [comment]
> Here is a simple solution if you want to have a hidden tab:
> 
> ```
> <Tab.Navigator>
>     <Tab.Screen
>       name="Home"
>       component={HomeScreen}
>     />
>     <Tab.Screen
>       name="HiddenTab"
>       component={HiddenTab}
>       options={{
>         tabBarButton: () => null,
>         tabBarVisible: false, // if you don't want to see the tab bar
>       }}
>     />
>   </Tab.Navigator>
> ```

At least someone with a brain, thx

**Comment by HariChowdary** [comment]
> For example, a search component accessible from the header :
> Version createBottomTabNavigator
> 
> ```
> Search: {
>   screen: SearchStack,
>   navigationOptions: {
>     tabBarButton: () => null,
>     tabBarButtonComponent: () => null,
>     tabBarLabel: () => null,
>   },
> },
> ```

It's working for me.

**Comment by eyjolfur12** [comment]
Tanks @DadouBordeaux , @Lcharvol  and @HariChowdary.

This works nicely to "hide" the button from the tab. But the tab is still there on the the tab bar, i.e. is clickable and shifting the other tab icons if the tab icons are centered. Did you run into that and fund a solution?

**Comment by webuijorgeGL** [comment]
> Here is a simple solution if you want to have a hidden tab:
> 
> ```
> <Tab.Navigator>
>     <Tab.Screen
>       name="Home"
>       component={HomeScreen}
>     />
>     <Tab.Screen
>       name="HiddenTab"
>       component={HiddenTab}
>       options={{
>         tabBarButton: () => null,
>         tabBarVisible: false, // if you don't want to see the tab bar
>       }}
>     />
>   </Tab.Navigator>
> ```

This is what I needed. Thanks!

**Comment by paulonteri** [comment]
> Here is a simple solution if you want to have a hidden tab:
> 
> ```
> <Tab.Navigator>
>     <Tab.Screen
>       name="Home"
>       component={HomeScreen}
>     />
>     <Tab.Screen
>       name="HiddenTab"
>       component={HiddenTab}
>       options={{
>         tabBarButton: () => null,
>         tabBarVisible: false, // if you don't want to see the tab bar
>       }}
>     />
>   </Tab.Navigator>
> ```

Thanks!

**Comment by fjarrett** [comment]
In case anyone else comes across this, the above solution only works with `createBottomTabNavigator` it will not work with `createMaterialTopTabNavigator` or  `createMaterialBottomTabNavigator` 😢  Still trying to figure out how to accomplish it, will update any findings here.

**Comment by GeorgK1** [comment]
Old thread, but this is what i did to hide Info tab  in `createMaterialTopTabNavigator` navigator. I conditionally render it based on state. 
` 
 this.state = {
    
            tabVisible: false,
 };
//stuff
{this.state.tabVisible && <Tab.Screen name='Info' component={Info} />}
`

**Comment by trickeyd** [comment]
Yes - unfortunately the solution suggested by @GeorgK1 doesn't work.

I had implemented something this way and we have hit a bug whereby: when the tab is added, the tab button appears as expected. Then when clicking the tab button, rather than showing a new tab with the intended content, there is no transition and it attempts to render the current tab but with the new tab's props.

So basically navigating to the 'new tab' just shows a corrupted clone of the tab you were on.

I've tried updating to latest version but no joy (was 5.3.13, now on 6.5.3)

Has anyone found a way to do this yet?

**Comment by trickeyd** [comment]
As a work around i ended up added these patches which work in most of our situations - it still messes up when you are on the tab of index directly above one you are removing, but overall it is an improvement in our particular use case.

It must be said that this is a massive hack though. I don't have time right now to get into the inner workings of react-navigation so this will have to surface for the time being.

Use at your own risk!!! (Feel like im going to get some serious thumbs down for this 😆 )

@react-navigation+core+5.16.1.patch
```
diff --git a/node_modules/@react-navigation/core/src/useNavigationBuilder.tsx b/node_modules/@react-navigation/core/src/useNavigationBuilder.tsx
index 5baabd1..cfca2a6 100644
--- a/node_modules/@react-navigation/core/src/useNavigationBuilder.tsx
+++ b/node_modules/@react-navigation/core/src/useNavigationBuilder.tsx
@@ -194,7 +194,8 @@ export default function useNavigationBuilder<
   EventMap extends Record<string, any>
 >(
   createRouter: RouterFactory<State, any, RouterOptions>,
-  options: DefaultNavigatorOptions<ScreenOptions> & RouterOptions
+  options: DefaultNavigatorOptions<ScreenOptions> & RouterOptions,
+  reinitOnRouteChangeHack: boolean = false, 
 ) {
   const navigatorKey = useRegisterNavigator();
 
@@ -238,6 +239,7 @@ export default function useNavigationBuilder<
   }, {});
 
   const routeNames = routeConfigs.map((config) => config.name);
+  const numRouteNames = reinitOnRouteChangeHack ? routeNames.length : 0; 
   const routeParamList = routeNames.reduce<Record<string, object | undefined>>(
     (acc, curr) => {
       const { initialParams } = screens[curr];
@@ -333,7 +335,7 @@ export default function useNavigationBuilder<
     // that some changes to routeConfigs are explicitly ignored, such as changes
     // to initialParams
     // eslint-disable-next-line react-hooks/exhaustive-deps
-  }, [currentState, router, isStateValid]);
+  }, [currentState, router, isStateValid, numRouteNames]);
 
   let state =
     // If the state isn't initialized, or stale, use the state we initialized instead
@@ -437,7 +439,7 @@ export default function useNavigationBuilder<
       }, 0);
     };
     // eslint-disable-next-line react-hooks/exhaustive-deps
-  }, []);
+  }, [numRouteNames]);
 
   // We initialize this ref here to avoid a new getState getting initialized
   // whenever initializedState changes. We want getState to have access to the
```

```
diff --git a/node_modules/@react-navigation/material-top-tabs/src/navigators/createMaterialTopTabNavigator.tsx b/node_modules/@react-navigation/material-top-tabs/src/navigators/createMaterialTopTabNavigator.tsx
index 9fe927d..fb51cf2 100644
--- a/node_modules/@react-navigation/material-top-tabs/src/navigators/createMaterialTopTabNavigator.tsx
+++ b/node_modules/@react-navigation/material-top-tabs/src/navigators/createMaterialTopTabNavigator.tsx
@@ -38,7 +38,10 @@ function MaterialTopTabNavigator({
     backBehavior,
     children,
     screenOptions,
-  });
+  },
+  // @ts-ignore
+  true
+  );
 
   return (
     <MaterialTopTabView

```

**Comment by RaguRam1991** [comment]
it seems working, 

 <Tab.Screen
        name="supportTab"
        component={ContactUs}
        options={{      
          tabBarButton: () => null,
        }}
      />

**Comment by lingadurai98** [comment]
> tabBarButton: () => null,
>         tabBarVisible: false, // if you don't want to see the tab bar

Thank you so much >

**Comment by matheusbaumgart** [comment]
Still no solution for `createMaterialTopTabNavigator` :/

**Comment by masarbazi** [comment]
workaround using react navigation v.7
### Hide a list of tab bar buttons
```typescript
// suppose I have four screen and want to hide `index` and `dictionary` tab bar buttons
const hiddenTabButtons = ['index', 'dictionary'];
<Tabs
  screenOptions={({ route }) => {
    return {
      tabBarItemStyle: {
        display: hiddenTabButtons.includes(route.name) ? 'none' : 'flex',
      },
    };
  }}
>
  <Tabs.Screen name='index' />
  <Tabs.Screen name='settings' />
  <Tabs.Screen name='dictionary' />
  <Tabs.Screen name='overview' />
</Tabs>;
```
### Hide specific screen (cleaner if you just want to hide one or two screens)
```typescript
// suppose I have four screen and want to hide `index` screen
<Tabs>
  {/* hidden tab bar button */}
  <Tabs.Screen
    name='index'
    options={{
      tabBarItemStyle: { display: 'none' },
    }}
  />
  <Tabs.Screen name='settings' />
  <Tabs.Screen name='dictionary' />
  <Tabs.Screen name='overview' />
</Tabs>;
```

**Comment by arthur-menezes** [comment]
<img width="798" alt="Image" src="https://github.com/user-attachments/assets/f954292f-1143-4767-910c-510a5cf6085e" />
