### ISSUE TITLE
V2 DrawerSidebar.js this.props.navigation.navigate is not a function

### ISSUE THREAD

**Issue by josh0707** [react-navigation/react-navigation#4077]
### Current Behavior

- React Navigation master v2.0.0-rc.x integrated with Redux.
- Click on any drawer label triggers error '_this.props.navigation.navigate is not a function'

### Expected Behavior

- Click on any drawer label should trigger navigation to route.

### Proposed solution

**Problem: /src/views/Drawer/DrawerSidebar.js#_onItemPress still uses `this.props.navigation.navigate`.**

_onItemPress still expects a `navigate` method which in previous versions was passed by `addNavigationHelpers`.
However, in v2.0.0-rc.x `addNavigationHelpers` is not required anymore.

The problem is similar to the one described in pull request [#12](https://github.com/react-navigation/react-navigation-tabs/pull/12) addressing tab actions.

 **Fix**
replace in /src/views/Drawer/DrawerSidebar.js:
````
_onItemPress = ({ route, focused }) => {
    if (!focused) {
      let subAction;
      // if the child screen is a StackRouter then always navigate to its first screen (see #1914)
      if (route.index !== undefined && route.index !== 0) {
        subAction = NavigationActions.reset({
          index: 0,
          actions: [
            NavigationActions.navigate({
              routeName: route.routes[0].routeName,
            }),
          ],
        });
      }
      this.props.navigation.navigate(route.routeName, undefined, subAction);
    }
};
````

With:
````
_onItemPress = ({ route, focused }) => {
    if (!focused) {
      let subAction;
      this.props.navigation.dispatch(NavigationActions.navigate({
        routeName: route.routeName,
        params: undefined,
        action: subAction
      }));
    }
  };
````

Thank you for taking a look at this and create a pull request if appropriate.

### Environment

| software         | version
| ---------------- | -------
| react-navigation | v2.0.0-rc5
| react-native     | 16.3.1

**Comment by gogumai** [comment]
Also, in this #4121  PR's playground , in the `Drawer Example` the app is crashing (I think) because of this..

Steps to reproduce:

1. Go to `Drawer Example`
2. Tap one or more times on `Open other screen` button
3. Open the drawer and switch to `Inbox` screen
4. Open the drawer again and switch to `Drafts` screen

**Comment by brentvatne** [comment]
cc @ericvicenti ^

**Comment by ericvicenti** [comment]
Oh, this is because the reset action was moved from the NavigationActions to StackActions
