### ISSUE TITLE
Using a StackNavigator without a header inside a TabNavigation makes the app crash on Android

### ISSUE THREAD

**Issue by ngarnier** [react-navigation/react-navigation#4081]
### Current Behavior

The bug is triggered when using a StackNavigator inside a TabNavigator, and setting the `navigationOptions` of the initial route like so:

```
    navigationOptions: {
      header: 'none',
    }, 
```

In this case, the app crashes on Android, returning the following error:

```
Cannot add a child that doesn't have a YogaNode to a parent without a measure function! (Trying to add a 'ReactRawTextShadowNode' to a 'LayoutShadowNode')
```

### Expected Behavior

The expected behavior would be to navigate to the tab without crashing. This behavior can be observed by running the app on iOS.

### How to reproduce

You can reproduce this issue by using a StackNavigator inside a TabNavigator as described.

I created a boilerplace so you can just install it and run it to reproduce the issue. Here is the link: https://github.com/ngarnier/stacknavigator-inside-tabnavigator. Here are the important parts:
- Using an initial [TabNavigator with a StackNavigator as the initial Screen](https://github.com/ngarnier/stacknavigator-inside-tabnavigator/blob/master/App.js#L7-L10)
- [Hiding the header](https://github.com/ngarnier/stacknavigator-inside-tabnavigator/blob/master/src/components/World/index.js#L8-L12) in the initial route of the StackNavigator used in the initial TabNavigator

### Your Environment

```
Environment:
  OS: macOS High Sierra 10.13.3
  Node: 8.9.1
  Yarn: 1.3.2
  npm: 5.8.0
  Watchman: 4.9.1
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: 3.1 AI-173.4697961

Packages: (wanted => installed)
  react: 16.3.0 => 16.3.0
  react-native: ~0.54.1 => 0.54.4
```

**Comment by colinbarstow** [comment]
Experiencing this exact issue, reading around has only lead me to find that any text not wrapped in <Text></Text> is causing this issue. However the same as you, I am trying to declare the properties 

static navigationOptions = {
        header: 'none'
    }

And I get the YogaNode error, very very frustrating.

**Comment by brentvatne** [comment]
added a more helpful error message here: https://github.com/react-navigation/react-navigation/commit/bb5719f4388e3778ed2afcd3268cc2b35a828773
