### ISSUE TITLE
Focus events don't fire when opening / closing drawer

### ISSUE THREAD

**Issue by brentvatne** [react-navigation/react-navigation#4082]
As a result of this, it's not possible to determine whether the drawer is open or closed from a screen. You can repro this on https://snack.expo.io/ry170Jbaf

**Comment by slicejunk** [comment]
[2.0.0-rc.9]
focus/blur events are fired only once for stackNavigator as well.
withNavigationFocus is useless for now since isFocused does not change.

**Comment by brentvatne** [comment]
moving to https://github.com/react-navigation/react-navigation-drawer/issues/11
