### ISSUE TITLE
Zindex and absolute position not working

### ISSUE THREAD

**Issue by AmirHosseinSalari** [react-navigation/react-navigation#4083]
Hi, i'm trying to make a center circle button in my bottomTab but zIndex and absolute position not working.

![photo_2018-04-27_23-37-16](https://user-images.githubusercontent.com/38690265/39380485-fba15664-4a73-11e8-81e7-32b6906d5438.jpg)

My TabBarComponent is like this 

`import React from 'react';
import { View, StyleSheet, TouchableWithoutFeedback } from 'react-native';

const styles = StyleSheet.create({
  tabbar: {
    height: 49,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    borderTopWidth: 1,
    borderTopColor: colors.border,
    backgroundColor: colors.bgLightGrey
  },
  tab: {
    alignSelf: 'stretch',
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center'
  }
});

const TabBar = React.createClass({
  render() {

    const {
      navigation,
      renderIcon,
      activeTintColor,
      inactiveTintColor,
      jumpToIndex
    } = this.props;

    const {
      routes
    } = navigation.state;

    return (
      <View style={styles.tabbar}>

        {routes && routes.map((route, index) => {
          const focused = index === navigation.state.index;
          const tintColor = focused ? activeTintColor : inactiveTintColor;
          return (
            <TouchableWithoutFeedback
              key={route.key}
              style={styles.tab}
              onPress={() => jumpToIndex(index)}
            >
              <View style={styles.tab}>
                {renderIcon({
                  route,
                  index,
                  focused,
                  tintColor
                })}
              </View>
            </TouchableWithoutFeedback>
          );
        })}

      </View>
    );
  }
});

export default TabBar;`

@faceyspacey 
@satya164

**Comment by brentvatne** [comment]
this is the behavior of zIndex in react-native
