### ISSUE TITLE
didFocus event not fired on initial mount

### ISSUE THREAD

**Issue by MrLoh** [react-navigation/react-navigation#4087]
I'm testing `^2.0.0-rc.2` following the [StatusBar tutorial](https://reactnavigation.org/docs/status-bar.html) I noticed that the actions don't get fired consistently. My app is integrated with redux and uses StackNavigators inside a BottomTabNavigator. The `Navigation/COMPLETE_TRANSITION` actions don't fire consistently either, which is probably what is causing the problem.

**Comment by brentvatne** [comment]
try updating to rc.5 and let me know if the issue persists

**Comment by brentvatne** [comment]
@MrLoh - please provide reproducible examples in future reports, as per the issue template. Here's what that would look like for your most recent comment: https://snack.expo.io/S1_q2z86f

**Comment by MrLoh** [comment]
Yeah sorry the initial error was not trivial to reproduce in a simple project and since your working on the RC I thought first reporting is a better way than waiting until I find the 3 hours to build a reproducible example. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by brentvatne** [comment]
3 hours? that took me 2 mins :P

**Comment by brentvatne** [comment]
the latter issue is resolved in https://github.com/react-navigation/react-navigation/pull/4104

**Comment by MrLoh** [comment]
thisi is still not fixed in v2.0.1 the initial opening of tabs that contain stack's doesn't fire a `didFocus` event.

**Comment by MrLoh** [comment]
@brentvatne can this be reopened, or should I create a new issue?

**Comment by MrLoh** [comment]
This is very odd, I tried to reproduce this in a green field project, and I can't. Something strange in my app setup must be broken, but it doesn't seem to be an issue with react-navigation. Sorry for the confusion.

**Comment by MrLoh** [comment]
I have an example where everything works, here if someone run's into this problem in the future. 
https://snack.expo.io/@mrloh/nested-stacks-in-tabs-didfocus

**Comment by MrLoh** [comment]
Ok, turn's out that the redux integration was breaking it, I created a new issue with a reproducible example.

**Comment by psyanite** [comment]
@MrLoh, where did you create the new issue?
