### ISSUE TITLE
Deep linking: links opens app but navigates away from page

### ISSUE THREAD

**Issue by ellismarte** [react-navigation/react-navigation#4091]
react-navigation: ^1.0.0-beta.11
react-native: 0.48.3
node: v8.3.0
npm: 6.0.0

When I send my friend a link to a screen in my app he can open it and it goes to the screen, but then it navigates away from that screen back to the home screen. 

If he already has the app open and it's in the background this behavior doesn't happen, instead when he clicks the link the app stays on the right screen. 

It's like the router gets initialized and then goes through the usual startup process ... if this isn't a bug then how would I go about handling a user clicking a deep link while the app is closed so that they aren't navigated to the homescreen?

**Comment by brentvatne** [comment]
hi @ElliottJRo! please update to the latest version of react-navigation (1.5.11 at the time of writing, soon to be 2.0.0) and test your code against it. if this is still a bug, please create a new issue and provide an example repository that we can clone and run to reproduce the bug, as per the issue template. thanks!
