### ISSUE TITLE
Option to force the header view in iOS to be rendered like Android (left-aligned) and vice versa

### ISSUE THREAD

**Issue by afshin-hoseini** [react-navigation/react-navigation#4092]
Is it possible to force the stack navigator's header on iOS to be rendered as like as what it appears on Android?

I applied this headerTitleStyle:

```
{
    fontFamily : "fontName",
    textAlign : 'left',
    position : 'absolute',
    top : 0, left : 20 , right:20, bottom:0,
    backgroundColor : 'red'
}
```

And everything went well except the headerBack min width.

**The result without back button**
![withoutbackbtn](https://user-images.githubusercontent.com/15011928/39420379-91688f6c-4c79-11e8-839b-49f3498324ab.png)

**The result width back button**
![withoutbackbtn](https://user-images.githubusercontent.com/15011928/39420445-dcaf6dd8-4c79-11e8-970f-781198e04e83.png)

My problem is the min width of back button. Is there any solution to change this min width?

**Comment by pzatorski** [comment]
Hey @afshin-hoseini I am not sure but I think the only way that you can change the 'back button' it that you can create your own one. You can do it by adding component to `headerLeft` key in `navigationOptions`. If you set the `headerLeft: null` then it wouldn't return the 'back button' at all.

**Comment by brentvatne** [comment]
hi there! I think this is an important feature for us to add - it should be easy to set the header mode to use the android style of header on ios.

**Comment by brentvatne** [comment]
related: https://github.com/react-navigation/react-navigation/issues/3677

**Comment by brentvatne** [comment]
have a WIP PR open for this, will hopefully land it soon

**Comment by brentvatne** [comment]
done in #4588, check out react-navigation@2.9.1

**Comment by pzatorski** [comment]
Great work @brentvatne !
