### ISSUE TITLE
react-navigation 1.5.8 header interacting with component

### ISSUE THREAD

**Issue by jadelmir** [react-navigation/react-navigation#4093]
I did the same example provided in the docs https://snack.expo.io/@react-navigation/header-interacting-with-component-instance
I am using react-navigation 1.5.8 but in the example there are using 1.0.0beta

but it never worked for me 

class plan extends Component {
	static navigationOptions = ({ navigation }) => {
		const params = navigation.state.params || {};

		return {
			headerRight: (
				<Button onPress={params.increaseCount} title="+1" color="tomato" />
			)
		};
	};

	componentWillMount() {
		this.props.navigation.setParams({ increaseCount: this._increaseCount });
	}

	state = {
		count: 0
	};

	_increaseCount = () => {
		this.setState({ count: this.state.count + 1 });
	};
	render() {
		return (
			<View>
				<Text>{this.state.count}</Text>
			</View>
		);
	}
}
const mapStateToProps = ({}) => {
	return {};
};
export default connect(mapStateToProps, {})(plan);

if I console.log params it is always {} 
so I think that this.props.navigation.setParams({ increaseCount: this._increaseCount }); is not working 

### Your Environment

| software         | version
| ---------------- | -------

| react-navigation |"^1.5.8"
| react-native     |"0.54.2",
| node             |v8.9.3
| npm or yarn      |5.5.1

![simulator screen shot - iphone 6 - 2018-04-30 at 13 36 41](https://user-images.githubusercontent.com/31207632/39423642-96bcb702-4c7b-11e8-8ae5-7c12fe0bdcac.png)

**Comment by vonovak** [comment]
@jadelmir if I use the expo snack that you provide, and change the version in package.json, the example still works for me, so I'm afraid there's something more happening in your app which we cannot investigate without a runnable bug reproduction.
please create a new issue with a runnable repro and i'd be happy to review it!

**Comment by jadelmir** [comment]
@vonovak the problem is that everything is working fine expect this

**Comment by vonovak** [comment]
@jadelmir please refer to my original comment. We need a runnable repro to be able to help. Thank you.
