### ISSUE TITLE
tab navigator inside static layout

### ISSUE THREAD

**Issue by mojtaba-hajishah** [react-navigation/react-navigation#4094]
Can I achieve this layout?
![test](https://user-images.githubusercontent.com/30038691/39426897-e336d5b6-4c96-11e8-97c1-e481420bde62.png)

the header part is shared across all tabs. it's part of the layout in this screen.
and each tab contains a scrollView.

btw, I have tried defining the tab navigator as a component and using that inside the render method, along with the static header component.

`render() {
  return (
    <StaticHeaderComponent />
    <MyTabNavigator />
  )
}
`
that does not work. the tab navigator does not render at all.

**Comment by vonovak** [comment]
hi @mojtaba-hajishah I'm closing this, because our issue tracked is reserved for bugs only, while your post is a usage question which is suited more for stackoverflow.
