### ISSUE TITLE
[Question] Is it possible to create an Android-style tabbed UI with this library?

### ISSUE THREAD

**Issue by jamesqo** [react-navigation/react-navigation#4105]
[React-Native-ViewPager](https://github.com/zbtang/React-Native-ViewPager) supports creating a kind of carousel Android-style UI, with icon-less tabs on the top, like this:

![image](https://github.com/zbtang/React-Native-ViewPager/raw/master/imgs/titleIndicator.gif)

Is it easy to create an Android-style tab layout like the above with this library (including little details, like the rectangle that appears below the tab for the current page)? Thanks.

**Comment by xanderberkein** [comment]
Yes, this is pretty easy with a TabBarTop component.  
Wrap a TabNavigator inside a StackNavigator (for the HeaderBar), and disable some styles on the HeaderBar of the StackNavigator:
```
navigationOptions: {
  headerStyle: {
    elevation: 0,
    borderBottomWidth: 0,
  },
}
```

**Comment by brentvatne** [comment]
hi there! this is a question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.
