### ISSUE TITLE
HOC's don't play nice with explicitly rendering more than one navigator

### ISSUE THREAD

**Issue by xanderberkein** [react-navigation/react-navigation#4112]
### Current Behavior & How to reproduce

The docs of react-navigation v2 have a nice section about [Explicitly rendering more than one navigator](https://v2.reactnavigation.org/docs/en/common-mistakes.html). At the bottom of the page, there is an example showing how to expose the `router` static, which makes it possible to render a navigator inside a component inside another navigator. This example works perfectly.

However, when you wrap the `AuthenticationScreen` of the example inside a HOC, the navigation prop doesn't get passed correctly, and react-navigation throws following error `TypeError: undefined is not an object (evaluating 't.routes.forEach')` . This error is to be expected when  incorrectly exposing the `router` static or incorrectly passing the `navigation` prop, but even when doing that correctly, the app still crashes.

I prepared a simple snack with a demo of this problem: [snack](https://snack.expo.io/@x11n/react-navigation-hoc)

As you can see, if you uncomment line 48 and comment line 47, everything works fine. This is the default example of *rendering more than one navigator*. However, when you wrap the AuthenticationScreen inside a very simple HOC (uncomment line 47 and comment line 48), the error gets thrown.

You can clearly see that the HOC variant doesn't pass the correct navigation prop when inspecting the logs. The navigation prop of the HOC variant doesn't include the `isTransitioning`, `index` or `routes` params.

### Expected Behavior

I expect the navigation prop to be passed correctly. Now, to fix above error, all we have to do is uncomment line 34 and declare the exposed `router` there as well. However, for HOC's imported from external packages (like Redux or Mobx), this is not possible to do. Is there another way to easily point the `router` of the AuthenticationScreen to the correct class?

### Your Environment

Reproducible on the stable branch (like you can see in the snack) as well as on the v2 branch (I tested this locally).

**Comment by brentvatne** [comment]
your hoc should use this so static properties are hoisted: https://github.com/mridgway/hoist-non-react-statics

**Comment by xanderberkein** [comment]
That seems to do the trick! By letting the HOC return 
```
return hoistNonReactStatics(WithHOC, WrappedComponent);
```
the static properties are properly hoisted.

Thanks!
