### ISSUE TITLE
Swipe back gesture in RTL mode is broken

### ISSUE THREAD

**Issue by spaceye** [react-navigation/react-navigation#4118]
### Current Behavior

Swipe back doesn't work in RTL mode by default and even when you set `navigationOptions.gestureDirection` to 'inverted' value to facilitate it functionality remains broken: one is able to swipe back but stack card responds to user's gesture in a jerky near-edge movement.

### Expected Behavior

Swipe back works just fine in RTL mode by default. If one needs to override it they can do it even when the RTL mode is on.

### How to reproduce

- Add a StackNavigator with some routes to your setup;
- Force app into RTL mode with `I18nManager.forceRTL(true);` call;
- Navigate from one route to another;
- Try to swipe back.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.0.0-rc.1 (also on the latest release)
| react-native     | 0.54.4
| node             | 9.10.1
| npm or yarn      | 1.5.1

**Comment by spaceye** [comment]
Initial functionality was added in https://github.com/react-navigation/react-navigation/pull/3077 however there is a bug in there and I'd like it to use RTL by default as everywhere else in the code we do just that (RTL is supported in all the transitions) with an ability to override it if one chooses so.

**Comment by brentvatne** [comment]
thanks for the pr in #4119!

**Comment by spaceye** [comment]
You're welcome!

**Comment by mohamadian** [comment]
please visit #3325
