### ISSUE TITLE
navigationOptions from nested TabNavigator are not respected in react-navigation@2

### ISSUE THREAD

**Issue by angly-cat** [react-navigation/react-navigation#4120]
### Current Behavior

I have a tab navigator nested in a stack navigator. In `react-navigation@2` I can't get `navigationOptions` of tab screens working (tested with `2.0.0-rc.7`).

### Expected Behavior

`navigationOptions` from tab screens are to be respected. `Settings` screen is expected to have header with "Settings" title and `Home` screen is expected to not have a header. This works as expected in `react-navigation@1.5.12`. I don't know how to achieve desired functionality with v2.

### How to reproduce

Check [this snack](https://snack.expo.io/@angly/basic-tabs).
### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.0.0-rc.7

**Comment by Jeepeng** [comment]
Same here

**Comment by brentvatne** [comment]
intentional, see https://v2.reactnavigation.org/docs/en/navigation-options-resolution.html for more information.

we'll get back to you soon with how to handle this specific case with new resolution behavior

**Comment by fuxianwei** [comment]
Thank you. It works for me. I have this problem too.

**Comment by angly-cat** [comment]
> we'll get back to you soon with how to handle this specific case with new resolution behavior

Thanks, @brentvatne. I'm looking forward to it.

**Comment by Amurmurmur** [comment]
Same here.

**Comment by brentvatne** [comment]
here's one approach you could use: https://snack.expo.io/rkbt7ns6M

```
Tabs.navigationOptions = ({ navigation }) => {
  let title;
  let focusedRouteName =
    navigation.state.routes[navigation.state.index].routeName;
  if (focusedRouteName === 'Home') {
    title = 'Home'; // of course in this case it's the same, but do whatever you want here
  } else if (focusedRouteName === 'Settings') {
    title = 'Settings';
  }

  return {
    title,
  };
};
```

**Comment by brentvatne** [comment]
the above represents the state of the world with react-navigation@2.0.0, if you have some thoughts on how we should improve this then please comment on this rfc issue: https://github.com/react-navigation/rfcs/issues/44

**Comment by angly-cat** [comment]
I didn't want to move `navigationOptions` from components, so I've enhanced @brentvatne's solution and ended up with the following:

```
Tabs.navigationOptions = (configProps) => {
  const focusedRouteName = configProps.navigation.state.routes[configProps.navigation.state.index].routeName;
  const childNavigationOptions = TabScreens[focusedRouteName].navigationOptions;
  if (childNavigationOptions) {
    return childNavigationOptions(configProps);
  }
};
```
You can check it in action in [this snack](https://snack.expo.io/@angly/basic-tabs-enhanced).

I use shorthand syntax everywhere, so solution is specifically for that scenario. In case you use something like:
```
routeName: {
  screen: Component,
},
```
the code should be modified accordingly.

**Comment by angly-cat** [comment]
@leethree Thanks for sharing your workaround. Your `.router.getComponentForState` is sure more clean than my solution.

Your concern about `setParams` is valid. [Official docs](https://reactnavigation.org/docs/en/navigation-options-resolution.html) suggest creating separate stack navigators for each tab and using its' headers for that.

> if you have some thoughts on how we should improve this then please comment on this rfc issue: react-navigation/rfcs#44

If you have some thoughts, @leethree, I invite you to write there in that issue. I have some thoughts regarding this matter, but I need to think about it a bit more before I would be able to express them so they would make sense.

**Comment by ravirajn22** [comment]
@brentvatne I have a Stack configured like,

```
const RootNavigator = createStackNavigator (
  HomeTabs: HomeTabs,
  Screen1: normalScreen,
  Screen2: normalScreen,
  ....
)

const HomeTabs = createBottomTabNavigator (
  SubTab1: createMaterialTopTabNavigator,
  SubTab2: createMaterialTopTabNavigator
) 
```

i.e Tabs nested inside Tabs nested inside parent Stack.

Previously I used to control the navigation options of the Stack from any deeply nested child, it was smooth and easy to understand once you know how it works.

Now with the changes in v2.0.0, I can't find the solution to this problem.  Moreover, it's not a simple change like title, I also change the header, headerRight based on the nested screen.

For example, Say SubTab1 has two tabs, Profile and Rank. I need to change the header button, Title for Profile screen and Rank screen. How do I do it without performing heavy hacks?. Moreover, the screen level navigation Options was cleaner.

**Comment by ravirajn22** [comment]
@brentvatne If no easy solution, then as discussed in the RFC can you add the toggle for merging of navigationOptions from the nested child screens?

**Comment by SaeedZhiany** [comment]
Hi @lebedev, I need a real quick assistance please,

previously I have some routing like this:

```
const StackNav = createStackNavigator({
    'Screen1': {
        screen: Screen1Component
        navigationOption: Screen1Component.appBarNavigationOption
    },
    'Screen2': {
        screen: Screen2Component
        navigationOption: Screen2Component.appBarNavigationOption
    },
});
```

in the `appBarNavigationOption` I returned customize options like custom `headerTitle `component and so on, like below: (I simplified it)

```
{
    headerTitle: (
        <TouchableNativeFeedBack onPress={callSomeFunction}>
             <Text></Text>
             <Text></Text>
        </View>
    ),
    headerTitle: (
        <View>
             <Text></Text>
             <Text></Text>
        </View>
    ),
   ...
}
```

**Now** I have decided to add a Tab and move the `Screen 2` into the tab with another screen `Screen 3`

```
function getAppBarNavigationOptionsFromTab(props: NavigationScreenConfigProps): NavigationStackScreenOptions {
  const {navigation: {state: {routes, index}}} = props;
  const { routeName } = routes[index];
  switch(routeName) {
    case 'Screen 2':
      return Screen2Component.appBarNavigationOption;
    case 'Screen 3':
      return Screen3Component.appBarNavigationOption;
    default: 
      return {};
  }
}

const TabNav = createBottomTabNavigator({
    'Screen2': {
        screen: Screen2Component
    },
    'Screen3': {
        screen: Screen3Component
    },
}, {
 navigationOption: getAppBarNavigationOptionsFromTab
});
const StackNav = createStackNavigator({
    'Screen1': {
        screen: Screen1Component
        navigationOption: Screen1Component.appBarNavigationOption
    },
    'Screen2': {screen: TabNav},
});
```

result:

- Screen 1: works just like before
- Screen 2: `headerTitle` does not show up, I think it's not rendering at all, `headerRight` is the same
- Screen 3: `headerTitle` is the same above, `headerRight` shows up but onPress does not call


Am I passing navigatorOptions wrong? I want to customize the stack's AppBar in each tab separately

**Comment by SaeedZhiany** [comment]
Hi @lebedev and @brentvatne , I'm using react-navigation v3.11.0 and need a real quick assistance please,

previously I have some routing like this:

```
const StackNav = createStackNavigator({
    'Screen1': {
        screen: Screen1Component
        navigationOption: Screen1Component.appBarNavigationOption
    },
    'Screen2': {
        screen: Screen2Component
        navigationOption: Screen2Component.appBarNavigationOption
    },
});
```

in the `appBarNavigationOption` I returned customize options like custom `headerTitle `component and so on, like below: (I simplified it)

```
{
    headerTitle: (
        <TouchableNativeFeedBack onPress={callSomeFunction}>
             <Text></Text>
             <Text></Text>
        </View>
    ),
    headerTitle: (
        <View>
             <Text></Text>
             <Text></Text>
        </View>
    ),
   ...
}
```

**Now** I have decided to add a Tab and move the `Screen 2` into the tab with another screen `Screen 3`

```
function getAppBarNavigationOptionsFromTab(props: NavigationScreenConfigProps): NavigationStackScreenOptions {
  const {navigation: {state: {routes, index}}} = props;
  const { routeName } = routes[index];
  switch(routeName) {
    case 'Screen 2':
      return Screen2Component.appBarNavigationOption;
    case 'Screen 3':
      return Screen3Component.appBarNavigationOption;
    default: 
      return {};
  }
}

const TabNav = createBottomTabNavigator({
    'Screen2': {
        screen: Screen2Component
    },
    'Screen3': {
        screen: Screen3Component
    },
}, {
 navigationOption: getAppBarNavigationOptionsFromTab
});
const StackNav = createStackNavigator({
    'Screen1': {
        screen: Screen1Component
        navigationOption: Screen1Component.appBarNavigationOption
    },
    'Screen2': {screen: TabNav},
});
```

result:

- Screen 1: works just like before
- Screen 2: `headerRight` shows up but onPress does not call
- Screen 3: same as Screen 2

Am I passing navigatorOptions wrong? I want to customize the stack's AppBar with custom buttons in each tab separately

**Comment by SaeedZhiany** [comment]
Hi @lebedev and @brentvatne , I'm using react-navigation v3.11.0 and need a real quick assistance please,

previously I have some routing like this:

```
const StackNav = createStackNavigator({
    'Screen1': {
        screen: Screen1Component
        navigationOption: Screen1Component.appBarNavigationOption
    },
    'Screen2': {
        screen: Screen2Component
        navigationOption: Screen2Component.appBarNavigationOption
    },
});
```

**Now** I have decided to add a Tab and move the `Screen 2` into the tab with another screen `Screen 3`

```
function getAppBarNavigationOptionsFromTab(props: NavigationScreenConfigProps): NavigationStackScreenOptions {
  const {navigation: {state: {routes, index}}} = props;
  const { routeName } = routes[index];
  switch(routeName) {
    case 'Screen 2':
      return Screen2Component.appBarNavigationOption;
    case 'Screen 3':
      return Screen3Component.appBarNavigationOption;
    default: 
      return {};
  }
}

const TabNav = createBottomTabNavigator({
    'Screen2': {
        screen: Screen2Component
    },
    'Screen3': {
        screen: Screen3Component
    },
}, {
 navigationOption: getAppBarNavigationOptionsFromTab
});
const StackNav = createStackNavigator({
    'Screen1': {
        screen: Screen1Component
        navigationOption: Screen1Component.appBarNavigationOption
    },
    'Screen2': {screen: TabNav},
});
```

result:

- Screen 1: works just like before
- Screen 2: `headerRight` shows up but onPress does not call
- Screen 3: same as Screen 2

in `Screen 2` and `Screen 3` I was passing the onPress handler like this:

```
public componentDidMount(): void {
    this.props.navigation.setParams({onPressHandler: this.onPressHandler});
}
```

and in `appBarNavigationOption` I get it using code below:

```
const {navigation: {state: {params}}} = props;
...
headerTitle: (
  <TouchableNativeFeedBack onPress={params !== undefined ? params.onPressHandler: undefined}>
    <Text></Text>
    <Text></Text>
  </TouchableNativeFeedBack>
)
    
```

What I'm doing wrong? I want to customize the stack's AppBar with custom buttons in each tab separately
