### ISSUE TITLE
White Flash on First Tab Render

### ISSUE THREAD

**Issue by MrLoh** [react-navigation/react-navigation#4122]
### Current Behavior

I have a simple stack navigators nested in tab navigators app, with some screens that have some complex rendering. When the screen opens for the first time there is somehow a white flash, before the screen actually renders. This does not happen on subsequent renders. 

![ezgif-2-10900d9bbc](https://user-images.githubusercontent.com/1285032/39643090-d89b0448-4fd3-11e8-83cb-7645f2da7145.gif)

I though it has to do with some delay in rendering, so I tried to first render a simple green screen and then render the real screen after a timeout of 100ms, but the issue persisted. I just got first the simple green screen, then the white flash, and then the real screen. 

I was using `react-native-navigation` before and didn't have these issues, so I am pretty certain this has something to do with react navigation. 

### Expected Behavior

There shouldn't be a white flash or at least it should be possible to adjust the background color of the initial render. 

### How to reproduce

I have no idea how to reproduce this, as it seems to just happen, once screens get a bit more complex. I could share some of our app code with a dedicated person, but it is not public. 

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | `2.0.0-rc7`
| react-native     | `0.53.3`
| node             | `10.0.0`
| yarn      | `1.6.0`

**Comment by MrLoh** [comment]
I think the color must come from here: 

https://github.com/react-navigation/react-navigation/blob/e27ad22c57444fadb827bf3bd3a75e3b2ca38041/src/views/StackView/StackViewCard.js#L26

At least that is the only parent in the whole render tree that I can find that has such a background color.

**Comment by brentvatne** [comment]
@MrLoh - can you open a PR to make that background color customizable with a stack navigator config option?

**Comment by MrLoh** [comment]
I really did try to reproduce it but making it visible depends on having something complex to render. However the culprit is clearly the line above (I changed the color and the color of the flashing changes). So i guess all I have to do is change the `cardStyle` in the stack navigator options. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by kurushibu00** [comment]
@brentvatne , @MrLoh, Don't we have any other way to disable it ? 

I don't want this white screen. If I set false to animationEnabled in TabNavigatore, it will show this white background.
