### ISSUE TITLE
Tab navigator not working with redux integration in nested stack

### ISSUE THREAD

**Issue by tobby1177** [react-navigation/react-navigation#4123]
### Current Behavior

I'm trying to nest a tab navigator to my stack. I'm also using redux, but it keeps returning what's stated in the screenshot below.

![screenshot_2018-05-05-01-28-16](https://user-images.githubusercontent.com/34566758/39658128-be13ef3e-5007-11e8-8701-1c8e342be384.png)

### Expected Behavior

I expect the app run with the tab navigator displaying.

### How to reproduce
I have followed the exact same steps for integrating `redux` with your `react-navigation` from the official documentation and everything worked fine there, not until i started with this Navigation structure.

```
import React, { Component } from 'react';
import { BackHandler } from 'react-native';
import {
	StackNavigator,
	TabNavigator,
	addNavigationHelpers,
	NavigationActions,
} from 'react-navigation';
import {
	createReduxBoundAddListener,
	createReactNavigationReduxMiddleware,
} from 'react-navigation-redux-helpers';
import { connect } from 'react-redux';
import PropTypes from 'prop-types';

import * as Routes from './components/Routes';

export const Navigation = StackNavigator(
	{
		Home: {
			screen: TabNavigator(
				{
					HomeGallery: { screen: Routes.Gallery.Home },
					HomeTasks: { screen: Routes.Tasks.Home },
					HomeServices: { screen: Routes.Services.Home },
					HomeClients: { screen: Routes.Clients.Home },
					HomeInsights: { screen: Routes.Insights.Home },
				},
				{
					initialRouteName: 'HomeGallery',
				}
			),
		},
		SearchGallery: { screen: Routes.Gallery.Search },
		Settings: { screen: Routes.Gallery.Home },
	},
	{
		initialRouteName: 'Home',
		cardStyle: {
			backgroundColor: 'transparent',
		},
	}
);

export const middleware = createReactNavigationReduxMiddleware(
	'root',
	state => state.nav
);

const addListener = createReduxBoundAddListener('root');

class AppNavigator extends Component {
	componentDidMount() {
		BackHandler.addEventListener('hardwareBackPress', this.onBackPress);
	}

	componentWillUnmount() {
		BackHandler.removeEventListener('hardwareBackPress', this.onBackPress);
	}

	onBackPress = () => {
		const { dispatch, nav } = this.props;
		if (nav.index === 0) {
			return false;
		}
		dispatch(NavigationActions.back());
		return true;
	};

	render() {
		const { dispatch, nav } = this.props;
		const navigation = addNavigationHelpers({
			dispatch,
			state: nav,
			addListener,
		});
		return <Navigation navigation={navigation} />;
	}
}

const mapStateToProps = state => ({
	nav: state.nav,
});

AppNavigator.propTypes = {
	dispatch: PropTypes.func.isRequired,
	nav: PropTypes.object.isRequired,
};

export default connect(mapStateToProps)(AppNavigator);
```

And here is my reducer as well.
```
import { Navigation } from '../AppNavigator';

const { router } = Navigation;
const mainNavAction = router.getActionForPathAndParams('Home');
const initialNavState = router.getStateForAction(mainNavAction);

const NavigationReducer = (state = initialNavState, action) =>
	router.getStateForAction(action, state);

export default NavigationReducer;
```

I have also tried checking from my side, but it seems like the logger started returning null from `const mainNavAction` in my reducer:
```
import { Navigation } from '../AppNavigator';

const { router } = Navigation;
const mainNavAction = router.getActionForPathAndParams('Home');
```

**When i also changed my `TabNavigator()` to `StackNavigator()`, it was unbelievably working fine.**

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^1.5.11
| react-native     | 0.55.2
| node             | 9.9.0
| npm or yarn      | yarn 1.5.1

**Comment by angly-cat** [comment]
Your reducer differs from the example in the docs.

I can't say for sure what's wrong with it. However, in recent `react-navigation-redux-helpers` there was introduced new `createNavigationReducer` method, which is more convenient for using instead of writing your own reducer. Check [redux integration documentation of v2 docs](https://v2.reactnavigation.org/docs/en/redux-integration.html). Despite this doc being a part of v2 docs, it works just fine with `react-navigation@1`. Please try it.

**Comment by tobby1177** [comment]
Okay, so i tried using `createNavigationReducer`, but unfortunately it didn't seem to fit in. It gave me some `undefined` error. I then updated `react-navigation` to the latest version and followed the redux integration guide from the docs and everything started working again as expected. Thanks @angly-cat.
