### ISSUE TITLE
DrawerToggle in V2 with Redux not working.

### ISSUE THREAD

**Issue by opp100** [react-navigation/react-navigation#4125]
I tried create a project from the documentation and Redux example in this repo. And I think the `DrawerToggle` is not working for DrawerNavigation.

### Current Behavior
`this.props.navigation.navigate('DrawerToggle');` is not working. Neither `DrawerOpen` and `DrawerToggle` .

### Expected Behavior
It is working.

### How to reproduce
I have created a project in Snack to reproduce this bug. (Maybe it is because the documentation haven't up to date).
[Snack](https://snack.expo.io/@opp100/react-navigation-v2-test)

### Packages used
```javascript
  "dependencies": {
    "react": "16.3.1",
    "react-native": "0.55.3",
    "react-navigation": "^2.0.0-rc.9",
    "react-navigation-redux-helpers": "^1.0.5",
    "react-redux": "^5.0.7",
    "redux": "^4.0.0"
  },
```

**Comment by brentvatne** [comment]
seems like we need to update docs for this as it was a breaking change in 2.0. you can now just call `this.props.navigation.toggleDrawer()` / `openDrawer()` / `closeDrawer()`

**Comment by brentvatne** [comment]
actually no, this is already up to date in docs: https://v2.reactnavigation.org/docs/en/drawer-based-navigation.html

if you find a place where it isn't up to date (on the v2 website) please create an issue on https://github.com/react-navigation/react-navigation.github.io/issues

**Comment by opp100** [comment]
Thanks, @brentvatne, I have tried the `this.props.navigation.toggleDrawer()`, it is working perfectly in the view, but not in the `navigationOptions`. It will popup the error message `navigation.toggleDrawer` is not a function

```javascript
    navigationOptions: ({ navigation }) => ({
      headerLeft: (
        <TouchableOpacity onPress={()=>{navigation.toggleDrawer()}}> // toggleDrawer is not a function
          <Text
            style={{
              color: '#fff',
            }}>
            Menu
          </Text>
        </TouchableOpacity>
      ),
      headerStyle: { backgroundColor: '#f00' },
      title: '<--- Not Working Here',
      headerTintColor: '#fff',
    }),
```

Test Snack:
https://snack.expo.io/@opp100/react-navigation-v2-test

**Comment by opp100** [comment]
Sorry, that was my bad. In the `navigationOptions`, the onPress should be `navigation.dispatch(DrawerActions.toggleDrawer())`.
