### ISSUE TITLE
focus/blur events are not fired for StackNavigator

### ISSUE THREAD

**Issue by slicejunk** [react-navigation/react-navigation#4126]
### Current Behavior

focus/blur events are fired only once
withNavigationFocus gives a wrong ```isFocused``` prop

### Expected Behavior

```isFocused``` should be correct

### How to reproduce

https://snack.expo.io/BJmDhGi6G

click on [next] then [ back]

```isFocused```  is false but the view is focused

more investingation shows that focus and blur events are fired only once

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.0-rc-9
| react-native     | 0.55.3

**Comment by slicejunk** [comment]
may be related to https://github.com/react-navigation/react-navigation/issues/4082

**Comment by ericvicenti** [comment]
Thanks for the clear bug report. Will fix this ASAP!

**Comment by brentvatne** [comment]
2.0.0-rc.11
