### ISSUE TITLE
addNavigationHelpers is not a function

### ISSUE THREAD

**Issue by Amurmurmur** [react-navigation/react-navigation#4127]
## The issue tracker is reserved for bug reports only.

If you have a question, feature request, or an idea for improving the library or its related tools, please try one of the following resources:

- [Read the documentation](https://reactnavigation.org/)
- [Post an issue to the website repository if you'd like to see a documentation change](http://github.com/react-navigation/website)
- [Post a feature request to Canny](https://react-navigation.canny.io/feature-requests)
- [Write a RFC if you have ideas for how to implement a feature request](https://github.com/react-navigation/rfcs)
- [Get help on Discord chat (#react-navigation on Reactiflux)](https://discord.gg/4xEK3nD) or [on StackOverflow](https://stackoverflow.com/questions/tagged/react-navigation)
- Search for your issue - it may have already been answered or even fixed in the development branch. However, if you find that an old, closed issue still persists in the latest version, you should open a new issue.

Bugs with react-navigation must be reproducible *without any external libraries that operate on it*. This means that if you are attempting to use Redux or MobX with it and you think you have found a bug, you must be able to reproduce it without Redux or MobX in this report. Redux related issues belong in [react-navigation-redux-helpers](https://github.com/react-navigation/react-navigation-redux-helpers), and we do not have any first-class integration with MobX at the moment.

---

### Current Behavior
```
import React from 'react'
import * as ReactNavigation from 'react-navigation'
import { connect } from 'react-redux'
import AppNavigation from './AppNavigation'
import { createReduxBoundAddListener } from 'react-navigation-redux-helpers'

function ReduxNavigation (props) {
  const { dispatch, nav } = props
  const addListener = createReduxBoundAddListener('root');
  const navigation = ReactNavigation.addNavigationHelpers({
    dispatch,
    state: nav,
    addListener
  })

  return <AppNavigation navigation={navigation} />
}

const mapStateToProps = state => ({ nav: state.nav })
export default connect(mapStateToProps)(ReduxNavigation)

```
![image](https://user-images.githubusercontent.com/8608333/39664355-f40aa7be-5079-11e8-98ce-92d155bbc12a.png)

### Expected Behavior

When using react-navigation v1.5.12 works as expected
Going through the source code of react-navigation v2.0.0-rc.9 I've noticed addNavigationHelpers is not included at all.

### How to reproduce

- You must provide a way to reproduce the problem. If you are having an issue with your machine or build tools, the issue belongs on another repoistory as that is outside of the scope of Rect Navigation.
- Either re-create the bug on [Snack](https://snack.expo.io) or link to a GitHub repository with code that reproduces the bug.
- Explain how to run the example app and any steps that we need to take to reproduce the issue from the example app.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.0.0-rc.9
| react-native     | 0.55.3
| node             | 10.0.0
| npm or yarn      | 1.6.0

**Comment by guizmo** [comment]
Have you managed to fix this or did you go back to V1.5 ?

**Comment by guizmo** [comment]
ok i found that....
https://github.com/react-navigation/react-navigation/issues/4019

**Comment by dann1609** [comment]
why this was closed?
I can't see any solution.

**Comment by brentvatne** [comment]
addNavigationHelpers doesn’t exist anymore... read the redux docs if you use that

**Comment by km16** [comment]
```
bundling failed: Error: Unable to resolve module `./addNavigationHelpers` from  `.../node_modules/react-navigation/src/react-navigation.js`
```

I am receiving the same error. I am not making use of redux for react-navigation. I am on `react-navigation: 2.6.2`

**Comment by nicnocquee** [comment]
> ```
> bundling failed: Error: Unable to resolve module `./addNavigationHelpers` from  `.../node_modules/react-navigation/src/react-navigation.js`
> ```
> I am receiving the same error. I am not making use of redux for react-navigation. I am on `react-navigation: 2.6.2`

Just happened to me. Try resetting the cache when running the metro bundler: `npm start -- --reset-cache`

**Comment by nipasarker01** [comment]
not working on expo..

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
