### ISSUE TITLE
Passing parameters between Navigators

### ISSUE THREAD

**Issue by techyvish** [react-navigation/react-navigation#4130]
Hi Guys,

I am new to react-native and react-navigation. I have a question. How do I pass params between navigators? i.e. Passing some parameters from screen of NavigatorA to the another screen of NavigatorB. See below for my Navigator setup.

```
const MobileNumberEntryStack = StackNavigator({
    MobileNumberEntry: MobileNumberEntryScreen
});

const AuthStack = StackNavigator({
    SignIn: SignInScreen,
    SignUp: SignUpScreen
});

const AppNavigator = SwitchNavigator({
    Loading: LoadingScreen,
    App: TabNavigator,
    Auth: AuthStack,
    MobileNumberEntryStack: MobileNumberEntryStack,
});

export default AppNavigator;
```
In my `LoadingScreen` I am fetching some data and from there I am switching to `MobileNumberEntryStack` by calling  `this.props.navigation.navigate('MobileNumberEntryStack', { user` })
But I am not getting user in `MobileNumberEntryScreen`. Can someone help me with this?

**Comment by brentvatne** [comment]
use `this.props.navigation.navigate('MobileNumberEntry', { user })` instead

that said, this is a question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.
