### ISSUE TITLE
Deep linking: load only exact Screen

### ISSUE THREAD

**Issue by luongs3** [react-navigation/react-navigation#4133]
### Current Behavior
- What code are you running and what is happening?
I apply deep linking into my application but get 1 problem. After clicking to a link (to a post), I want my app opens only PostScreen to load that post, but instead, My app opens the HomeScreen first, then PostScreen later.
I handle deep link in a file called `BootstrapProvider.js`. This file was imported in App.js and is the first file running when app starts.
```
class BootstrapProvider extends React.Component {
  componentWillMount() {
    Linking.getInitialURL().then((url) => {
      if (url) {
        dispatchUrl(url) // this function process url, will navigate to PostScreen if it's a post
      }
    }).catch(err => console.error('An error occurred', err))
    console.log('BootstrapProvider - componentWillMount')
    Linking.addEventListener('url', this._handleOpenURL)
    ......
  }

  _handleOpenURL(event) {
    if (event.url) {
      dispatchUrl(event.url)
    }
  }

  componentWillUnmount() {
    Linking.removeEventListener('url', this._handleOpenURL)
  }
  .....
```

- Include a screenshot if it makes sense.
https://www.youtube.com/watch?v=IBC4o4z54X0
### Expected Behavior
Open only Post Screen (just one screen, not included my HomeScreen)

### How to reproduce
- Click a link in browser to visit a post in my website ( https://stg1.viblo.asia/p/test-video-3-oOVlYO9BK8W )
- My application (Viblo) open instead of browser to load that post
- My application load HomeScreen first, then load PostScreen to load post
### Your Environment
| software         | version
| ---------------- | -------
| react-navigation | 1.4.0
| react-native     | 0.52.1
| react              | 16.2.0
| node             | v9.11
| npm or yarn      | 5.6

I don't know exactly this's package's issue or issue in my code. But if you have any ideas or any solution, please let me know. Thanks.

**Comment by nicholasess** [comment]
You can include in componentwillmount of homescreen the validate, if has a deep linking, you will redirect to other screen

**Comment by luongs3** [comment]
@nicholasess tried this solution, but it always load Home Screen first.
Linking.getInitialURL() take too long (about 2-4 seconds to process external url and redirect to PostScreen)

**Comment by gwl002** [comment]
I have the same problem.This package has very little document about deeplink.

**Comment by jdnichollsc** [comment]
same issue using a `setTimeout` in my initial component... the app is redirecting the user to other page after open the screen with deep linking, any solution to detect if the current routeName is the screen of the deep link?

**Comment by v-singhal** [comment]
Any update on this issue?

**Comment by brentvatne** [comment]
there is no update. if you would like to work on this you may open a rfc, thanks!

**Comment by Minishlink** [comment]
This PR should fix this issue https://github.com/react-navigation/react-navigation-native/pull/12

**Comment by AmmarAshfaq** [comment]
issue is still there

**Comment by satya164** [comment]
Closing since this is no longer the behaviour in v5.
