### ISSUE TITLE
how to set initialRouteName based on props received in navigation in v2.0

### ISSUE THREAD

**Issue by netsmertia** [react-navigation/react-navigation#4136]
This is not a bug but need to know how to implement this after upgrading to React Navigation V2.0
Here is the long thread on same issue for React Navigation 1.0 #458

Requirements: 
How to set initialRouteName for  TabNavigator/ StackNavigator  based on the props. I need to set initial Tab based on some conditions. Previously I was able to handle the props inside a React Component and Compose the TabNavigator inside Component based on the props "defaultTab" from parent.

As in RN@2.0, only one navigator should be rendered inside component and if I use previous method I got this error. 

> console.error: "You should only render one navigator explicitly in your app, and other navigators should by rendered by including them in that navigator. Full details at: https://v2.reactnavigation.org/docs/common-mistakes.html#explicitly-rendering-more-than-one-navigator"

If I follow "Common-mistakes" and use the alternative method provided by exposing routes I am unable to use the props received to set the initialRouteName.

previously I used this approach   [458](https://github.com/react-navigation/react-navigation/issues/458#issuecomment-369129600)

I am at very beginner level and this project does not use Redux. Here is the exact code.
```
export default class CategoryChooser extends Component {

    componentWillMount () {

        const {defaultTab} = this.props.navigation.state.params;
        if (defaultTab == undefined) {
            defaultTab = 'ExpenseCategoryTab';
        }

        CategoryChooseStack =  TabNavigator({
        IncomeCategoryTab: {
            screen: IncomeCategoryTab,
            navigationOptions: {
            title: 'Income',
            }
        },
        ExpenseCategoryTab: {
            screen: ExpenseCategoryTab,
            navigationOptions: {
            title: 'Expense',
            }
        },
        TransferTab: {
            screen: WalletChooserTab,
            navigationOptions: {
            title: 'Transfer',
            }
        },
        }, {
            initialRouteName: defaultTab,
            backBehavior: 'none',
            navigationOptions: {
            //....
            },        
        });
    }

    render() {
        return <CategoryChooseStack screenProps={{...this.props.navigation.state.params, pn: this.props.navigation}}/>
    }
}
```

**Comment by brentvatne** [comment]
please include a full example that repros your issue :)

**Comment by netsmertia** [comment]
As you can see in above code snippet previously I used a property `defaultTab` to set the initialRouteName and composed Navigator. Here is an  [expo snack](https://snack.expo.io/@netsmertia/dynamicinitialroutename) but I am unable to do the same in 2.0.

How should I use the navigation param to set initialRouteName dynamically.

**Comment by mauritsd** [comment]
I'm having a similar issue, only I'm creating the routes themselves dynamically based on props, not only choosing the initial route. I realise this was a terrible hack to begin with, but it's unclear to me whether it's possible to do this properly with 2.0, either by using redux or by recreating the router (as suggested in #3827). If this is possible using an advanced technique, then maybe something for the docs?

**Comment by vikrantnegi** [comment]
Following the #4196, it seems that updating the react-navigation to 2.0.2 has fixed the error.
@brentvatne But now when I go to the app it always loads the initial screen instead of the last opened screen.
Can you confirm this there? I'm not able to comment on issue there as it is locked. 

Thanks.

**Comment by EduardoMondragon** [comment]
just run    npm install --save react-navigation

**Comment by brentvatne** [comment]
@netsmertia - in that example you provided you just need to navigate to "Tab2" rather than "Tabs" and that will get you to that tab

**Comment by sahil290791** [comment]
@brentvatne if I change routeName to `Tab2`, it does go to tab2 but it also pushes `tab1` which is the `initialRoute` as first route in the stack, so the expected behaviour was to go back to home screen when user presses back from `Tab2`, but instead it goes to `Tab1` and then `home`, here is the demo code: https://snack.expo.io/rJxe4T77Qm

**Comment by abdulbasit1248** [comment]
it is impossible to set initial route name based on props .because it takes a string .if you want to navigate between tabs dinamically .so Please use tab index to navigate between
