### ISSUE TITLE
I got " evaluation 'context.changedBits' "

### ISSUE THREAD

**Issue by Ghostrick** [react-navigation/react-navigation#4137]
Here is my code.
Why does this error occur?

### App.js
```javascript
import Expo from 'expo'
import React from 'react'
import { StyleSheet, Text, View } from 'react-native'
import AppNavigator from '../navigator/AppNavigator'

export default class App extends React.Component {
  render() {
    return <AppNavigator />
  }
}

Expo.registerRootComponent(App)

```

### SigninScreen.js

```javascript
import React from 'react'
import { Text, View } from 'react-native'

export default class SigninScreen extends React.Component  {
  render() {
    return (
      <View>
        <Text>signin</Text>
      </View>
    )
  }
}

```

### AppNavigator.js
```javascript

import { StackNavigator } from 'react-navigation'

import SigninScreen from '../components/SigninScreen'

const routes = {
  Signin: { screen: SigninScreen }
}

const stackConfig = {
  initialRouteName: 'Signin'
}

export default StackNavigator(routes, stackConfig)
```

### Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.0.0-rc.9
| react-native     |0.54.0
| node             | 9.2.0
| npm or yarn      |v0.24.5

**Comment by brentvatne** [comment]
I copied this code into a local project and ran it, it worked as expected.

it looks like your yarn version is very old... the latest version is 1.6.0. perhaps update that and reinstall the dependencies. if the issue persists then feel free to create a new issue but please upload the reproducible example to a github repository.

**Comment by Ghostrick** [comment]
@brentvatne Thank you!
