### ISSUE TITLE
How can I navigate to same screen, just render it with new screenprops?

### ISSUE THREAD

**Issue by Cronnay** [react-navigation/react-navigation#4138]
Hi there!

I'm currently creating an app where you can some sport games. One of my screens is a screen where you can see info about the game. In this screen, I want to show other games from the same league and I want to be able to navigate to it, even though it's the same screen.
Imagine you are on Spotify and going through an artist and you see similar artists. If you click on one of the artists, you navigate but still in the same screen.

How can I navigate to the same screen and provide other data in screenprops? I'm using Stacknavigator.

Thanks in advance!

**Comment by nicholasess** [comment]
You can use modal for that

**Comment by brentvatne** [comment]
hi there! this is a question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.
