### ISSUE TITLE
missing NavigationActions in master branch

### ISSUE THREAD

**Issue by sheenm** [react-navigation/react-navigation#4141]
Hello
I think I found strange bug which is not appeared in 1.x branch.
We can see that  [addNavigationHelpers.js](https://github.com/react-navigation/react-navigation/blob/master/src/addNavigationHelpers.js) imports everything from [NavigationActions.js](https://github.com/react-navigation/react-navigation/blob/master/src/NavigationActions.js) as NavigationActions and uses  ```NavigationActions.replace```, ```NavigationActions.openDrawer``` and other
things which does not exist in NavigationActions but existed in 1.x branch.

We can see these changes in [3619](https://github.com/react-navigation/react-navigation/pull/3619) pull request. 
Also it seems like addNavigationHelpers is not used anymore, I searched it over the repo and it's imported only in tests. Probably the solution is to remove this file.

**Comment by brentvatne** [comment]
replace: https://github.com/react-navigation/react-navigation/blob/master/src/routers/StackActions.js
opendrawer: https://github.com/react-navigation/react-navigation/blob/master/src/routers/DrawerActions.js
