### ISSUE TITLE
navigation.setParams() hides software keyboard

### ISSUE THREAD

**Issue by dluksza** [react-navigation/react-navigation#4148]
### Current Behavior

Software keyboard on iOS is hidden after calling `this.props.navigation.setParams`. This makes impossible to validate and enable/disable navigation header button, since each call to `setParams` from `onEndEditting` of TextInput will also hide the keyboard.

### Expected Behavior

As in 1.x version keyboard should not be hidden when `setParams` is invoked.

### How to reproduce

Create a screen with TextInput with `autoFocus` set to `true` and then in components `componendDidMount` call `this.params.navigation.setParams()`. You will see software keyboard appearing and disappearing when view is loaded.

Another scenario to reproduce this to also use TextInput, but this time set `onEndEditing` property to a callback function that will call `this.params.navigarion.setParams()`.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.0.0-rc.9 
| react-native     | 0.55.3
| node             | v10.0.0
| npm or yarn      |

**Comment by brentvatne** [comment]
thanks for the report! this is fixed in 2.0.0-rc.13
