### ISSUE TITLE
Cannot access props.navigation.navigate() in custom tabBarComponent

### ISSUE THREAD

**Issue by tobby1177** [react-navigation/react-navigation#4150]
### Current Behavior

I have a `tabNavigator` created with `createBottomTabNavigator,` and want to create a custom `tabBarComponent` which I easily passed and used `withNavigation()` on my custom `tabBarComponent` to pass the `navigation` object to my `props`. On my custom `tabBarComponent`, I of course have button so I could use for navigation between the tabs, but I just can't access `navigation.navigate()` as it keeps returning `undefined`. Other properties are being passed but not `.navigation.navigate()`.

### Expected Behavior

I should be able to use navigation.navigate().

### How to reproduce

First, here is my app navigator
```
import React, { Component } from 'react';
import {
	createBottomTabNavigator,
	createMaterialTopTabNavigator,
	NavigationActions,
} from 'react-navigation';
import {
	createReduxBoundAddListener,
	createReactNavigationReduxMiddleware,
} from 'react-navigation-redux-helpers';
import { connect } from 'react-redux';

import BottomNavigation from './components/BottomNavigation';
import * as Routes from './components/Routes';
import ActionOptions from './components/ActionOptions';

export const Navigation = createBottomTabNavigator(
	{
		Home: {
			screen: createMaterialTopTabNavigator(
				{
					HomeGallery: { screen: Routes.Gallery.Home },
					HomeTasks: { screen: Routes.Tasks.Home },
					HomeServices: { screen: Routes.Services.Home },
					HomeClients: { screen: Routes.Clients.Home },
				},
				{
					initialRouteName: 'HomeGallery',
				}
			),
		},
		Search: { screen: Routes.Gallery.Search },
		Insights: { screen: Routes.Gallery.Search },
		Settings: { screen: Routes.Gallery.Home },
		ActionOptions: { screen: ActionOptions },
	},
	{
		initialRouteName: 'Home',
		tabBarComponent: BottomNavigation,
	}
);

export const middleware = createReactNavigationReduxMiddleware(
	'root',
	state => state.nav
);

const AppNavigator = ({ dispatch, nav }) => (
        <Navigation navigation={{ dispatch, state: nav, addListener }} />;
);

const mapStateToProps = state => ({
	nav: state.nav,
});

export default connect(mapStateToProps)(AppNavigator);
```

And here is my custom `tabBarComponent`

```
const BottomNavigation = props => (
	<TouchableHighlight
		onPress={
			getCurrentRoute(props.navigation.state) === 'ActionOptions'
				? () => props.navigation.goBack()
				: () => props.navigation.navigate('ActionOptions')
		}
	>
		+
	</TouchableHighlight>
);
```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.0.0-rc.9
| react-native     | 0.55.2
| node             | 9.9.0
| npm or yarn      | yarn 1.5.1

**Comment by brentvatne** [comment]
hi! as of react-navigation@2 you can't access navigation helpers from navigation views, instead you need to use `dispatch` and `NavigationActions`. see this diff for an example: https://github.com/react-navigation/react-navigation-deprecated-tab-navigator/commit/cd40877cd8039756139ad6b128f2a1f687855d73

i'll update the release notes accordingly. thanks for reposting the issue with more context!
