### ISSUE TITLE
props.navigation.replace is not doing anything on 1.5.12

### ISSUE THREAD

**Issue by jgfidelis** [react-navigation/react-navigation#4152]
React-navigation version 1.5.12

In our application, when we use`props.navigation.navigate(routeName, params)` it works flawlessly.

We wanted the replace behaviour in one of our screens, so we were doing:

`props.navigation.replace(routeName, params)`

But nothing happens, the action is dispatched but the screen does not change and the navigation state in the redux stays the same.

**Comment by brentvatne** [comment]
hi there!

just wanted to point out this tidbit from the issue template:

> Bugs with react-navigation must be reproducible *without any external libraries that operate on it*. This means that if you are attempting to use Redux or MobX with it and you think you have found a bug, you must be able to reproduce it without Redux or MobX in this report. Redux related issues belong in [react-navigation-redux-helpers](https://github.com/react-navigation/react-navigation-redux-helpers), and we do not have any first-class integration with MobX at the moment.

could you repost this to the redux helpers issue as mentioned above?

**Comment by n1ru4l** [comment]
@jgfidelis Do you still experience this problem? I am currently forced to use a pre 2.0 version because I did some custom adjustments which are not part of master yet.

For me this occurs if the active route is the initial (and first) route in your stack navigator. If it is the second one it works.

**Comment by motogod** [comment]
@n1ru4l Do you mean Replace function won't work if use it in the initial route ?

I create a `Welcome` screen want to replace to `MainActivity` screen.

Welcome is my initialRouteName:
```
{
  initialRouteName: 'Welcome'
}
```
And i use the code in Welcome screen:

  // Test replace
```
  replaceToMainActivity() {
    const replaceAction = StackActions.replace({
      key: 'MainActivity',
      type: 'ReplaceCurrentScreen',
      routeName: 'MainActivity'
    });

    this.props.navigation.dispatch(replaceAction);
  }
```

I find that it is no wroking.  That is what you mean right ?
