### ISSUE TITLE
NavigationActions reset broken in 2.0.0-rc.9

### ISSUE THREAD

**Issue by andrewrt** [react-navigation/react-navigation#4153]
### Current Behavior

- What code are you running and what is happening?
When running with 2.0.0-rc.9 - and running the reset code (verbatim as per the example: https://reactnavigation.org/docs/navigation-actions.html#reset) - debugger finds exception:
TypeError: _reactNavigation.NavigationActions.reset is not a function. 
```js
import { NavigationActions } from 'react-navigation';

const resetAction = NavigationActions.reset({
  index: 0,
  actions: [NavigationActions.navigate({ routeName: 'Profile' })],
});
this.props.navigation.dispatch(resetAction);
```

### Expected Behavior

- What do you expect should be happening?
By downgrading back to 1.5.2 - same code works. 
(Running this code from a view pushed onto the stack will pop back to the requested view). 

### How to reproduce
Update packager.json to 
    "react-navigation": "^2.0.0-rc.9",
push a view or 2 onto the navigation stack, then run the code snippet listed above -> UI will not respond. 

To fix right now - downgrade back to 1.5.2, leave react/react-native the same - and run again. 

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | "^2.0.0-rc.9",
| react-native     |  "0.55.3",
| node             | 9.5.0
| npm      |"^6.0.0",

**Comment by andrewrt** [comment]
Actually - looks like might have already been fixed by @ericvicenti - just missed it as rc9 is the latest release showing on npm when i tested

**Comment by andrewrt** [comment]
issue appears to still be in 2.0.0 release tho...?

**Comment by brentvatne** [comment]
reset exists on StackActions and is properly used in DrawerSidebar: https://github.com/react-navigation/react-navigation/blob/c1a94895f5f816d7fbe6ba6edb281e4ebbe600bf/src/views/Drawer/DrawerSidebar.js#L47-L69

feel free to open a new issue with the issue template fully filled out if you think you've found a bug! :)

**Comment by pablo-albaladejo** [comment]
@andrewrt user `StackActions.reset` instead of  `NavigationActions.reset`. At your code:

```
import { NavigationActions, StackActions } from 'react-navigation';
const resetAction = StackActions.reset({
  index: 0,
  actions: [NavigationActions.navigate({ routeName: 'Profile' })],
});
this.props.navigation.dispatch(resetAction);
```
It is answered at SO: [https://stackoverflow.com/a/50781113/3395884](https://stackoverflow.com/a/50781113/3395884)

Hope It helps.
