### ISSUE TITLE
Drawer nesting umbrella issue

### ISSUE THREAD

**Issue by brentvatne** [react-navigation/react-navigation#4154]
Users have reported issues when nesting drawers in various ways over time. This issue is meant to collapse all of those reports into one issue for convenience of maintainers.

- Usability - nesting drawers within drawers and programmatically opening/closing a specific drawer: https://github.com/react-navigation/react-navigation/issues/1261
- Bug - drawer with a stack with a tab: https://github.com/react-navigation/react-navigation/issues/3954
- Usability/confusion: stack header appears over drawer - https://github.com/react-navigation/react-navigation/issues/1305
- Bug - stack with drawer, drawer visible in back animation - https://github.com/react-navigation/react-navigation/issues/2539
- Bug - tab with drawer on Android, drawer not visible - https://github.com/react-navigation/react-navigation/issues/2743
- Bug - top tabs with drawer as screen has weird animation ([snack](https://snack.expo.io/Sk4Y4vRTG)) - https://github.com/react-navigation/react-navigation/issues/1849

**Comment by mcottingham** [comment]
@brentvatne are there any updates on this issue?  Is there a projected ETA or a workaround?

**Comment by brentvatne** [comment]
I'm not working on this at the moment, these are all things that I'd love to see contributors help out with

**Comment by MsMayuaner** [comment]
#2743 it is normal to slide out the drawer from the screen. Only by calling the method of opening can you not see it.

**Comment by MrWangjiahuan** [comment]
#2743 it is normal to slide out the drawer from the screen. Only by calling the method of opening can you not see it.

**Comment by diickens** [comment]
Still no fix for this? Same behavior when I use router-flux?

**Comment by callcter** [comment]
same issue while drawerNavigator nested in bottomTabNavigator

**Comment by kylemarshall18** [comment]
I'm having the same issue with nesting drawers inside of tabs.

Not sure if anyone has found the issue yet but It looks like this behaviour is being caused by the `ResourceSavingScene` component from the **react-navigation-tabs** package. The top level View of that component implements `removeClippedSubviews` which is always true on android but only true on iOS if the view is not in focus. See [line #27](https://github.com/react-navigation/react-navigation-tabs/blob/master/src/views/ResourceSavingScene.js#L27) of that file.

I changed it locally to always pass `!isVisible` to the `removeClippedSubviews` prop and it seemed to do the trick. The drawer was opening as expected on android, both when swiping and calling `navigation.openDrawer()`.

**Comment by jacquesdev** [comment]
Hi @kylemarshall18 - new to react-native and react-navigation, so just wanted to ask a question.

I would like to try the issue that you mentioned in https://github.com/react-navigation/react-navigation-tabs/pull/42, however, I don't have react-navigation-tabs installed (from what I can see anyway), only react-navigation (v2.12.1), so I wanted to understand if this issue only affects users who have that project only, and if it does also extend to react-navigation, how would I go about testing/installing that on my project to try and test it?

**Comment by nickfla1** [comment]
Even after the switch to `react-native-screens` for `ResourceSavingScene` the only way I can "solve" the 
issue is to force my application to not use Screens and hard-code  `removeClippedSubviews` to false
.

**Comment by choo737** [comment]
I am using react-navigation v2.18, I have a bottomTabNavigator with another DrawerNavigator in it, the dark overlay issue is still happening..

Same issue with [this](https://github.com/react-navigation/react-navigation/issues/4692)

Refer to screenshot -> [here](https://github.com/react-navigation/react-navigation/issues/4740#issuecomment-429200686)

tried setting `removeClippedSubviews` to false but still the same.

```
export const NavigatorRouteConfig = createBottomTabNavigator({
  Login: { screen: LoginScreen },
  Register: { screen: RegisterScreen },
  Main: { screen: AppDrawer },
},
  {
    navigationOptions: {
      tabBarVisible: false,
    },
    swipeEnabled: false,
    removeClippedSubviews: true,
  });
```

**Comment by dianbagus96** [comment]
any update on this isue? im still got dark overlay issue when my drawerNavigator inside bottomTabNavigator, please help

**Comment by choo737** [comment]
@dianbagus96 I figured out mine, maybe it is the same for yours.
adding `drawerLockMode: 'unlocked'` to the `navigationOptions` fixed partially.

However, my app includes Facebook Login feature, after facebook login, the problem re-occurs..

**Comment by choo737** [comment]
@dianbagus96 same here. still couldn't fix it, only happen in a certain pattern. I've created a new issue for that. https://github.com/react-navigation/react-navigation/issues/5124

**Comment by BogdanRad** [comment]
same here... :(

**Comment by brentvatne** [comment]
most of this should be resolved in react-navigation v3 because we move to a custom implementation of drawer provided by react-native-gesture-handler.

**Comment by diickens** [comment]
So this is a future release? When do you think this gonna roll out? By the way.. thanks for your efforts! Great project!

**Comment by apswak** [comment]
I had the overlay android issue when a drawer (`createDrawerNavigator`) was nested within a Tab Bar (`createBottomTabNavigator`).

Changing... 
`"react-navigation": "^2.4.1"` to `"react-navigation": "^3.0.0-alpha.7"` in `package.json`

Then running `rm -rf node_modules && yarn` fixed it for me. 

Or simply `yarn add react-navigation@3.0.0-alpha.7` should do the trick.

Obviously wouldn't recommend for production, but for development with the intention of upgrading to V3 when it's released... suitable fix for me compared to manually messing around in `node_modules` or using `react-native-screens` which was giving me a `Tried to register two views with the same name RNSScreen` error.

**Comment by brentvatne** [comment]
i believe these are resolved in react-navigation v3, if not please open a new issue for whatever hasn't been fixed
