### ISSUE TITLE
Transitioner mounting umbrella issue

### ISSUE THREAD

**Issue by brentvatne** [react-navigation/react-navigation#4155]
The Transitioner, used by stack navigator, can in some cases where the user executes a back action and then navigate action quickly (to anywhere, not to return to the same screen) in succession, may remount the screen we went back from and unmount it again. 

- https://github.com/react-navigation/react-navigation/issues/3990
- https://github.com/react-navigation/react-navigation/issues/1724
- https://github.com/react-navigation/react-navigation/issues/3592
- https://github.com/react-navigation/react-navigation/issues/4509

The Transitioner rewrite we are planning for v3 should address this.

**Comment by msageryd** [comment]
@brentvatne Are there any official plans for v3? I've had to implement some nasty workarounds for the componentDidMount issue (called when navigating back from a screen).

It would be really great to be able to trust that the events are called only when appropriate.

**Comment by aksonov** [comment]
@brentvatne Any fix/workaround for v2? We use `Transitioner` with custom animations and it remounts popped components after 'back' action (i.e. index >= current index) (but some components with the same animations/setup are processed correctly)

**Comment by brentvatne** [comment]
there is no solution right now. someone needs to dig in and rewrite the Transitioner component. this is kind of difficult to do... but if you're up for it :P

**Comment by brentvatne** [comment]
I think this fixes it: https://github.com/react-navigation/react-navigation-stack/commit/77cdfabe8cb195f7ffc903fbbda544ea4450b31d

**Comment by xy371661665** [comment]
But it can't use that the version 3.0.0-alpha.15

**Comment by brentvatne** [comment]
we'll release a rc soon with instructions for how you can use it
