### ISSUE TITLE
migration guide from 1.x to 2.0？

### ISSUE THREAD

**Issue by cbjs** [react-navigation/react-navigation#4157]
thanks

**Comment by xanderberkein** [comment]
See the blog post with breaking changes: https://reactnavigation.org/blog/2018/05/07/react-navigation-2.0.html

**Comment by cbjs** [comment]
@xanderberkein thanks~

**Comment by sitanjob** [comment]
> [](https://reactnavigation.org/blog/2018/05/07/react-navigation-2.0.html)

Page Not Found

**Comment by raajnadar** [comment]
Try this page https://reactnavigation.org/blog/2018/05/07/react-navigation-2.0
