### ISSUE TITLE
How to solve Header issue in react-navigation v-2.0 ?

### ISSUE THREAD

**Issue by Nitingadhiya** [react-navigation/react-navigation#4159]
### Current Behavior

![screen shot 2018-05-08 at 12 29 37 pm](https://user-images.githubusercontent.com/7464953/39742628-d51b6764-52bb-11e8-9859-520ec01b7cc1.png)

### Expected Behavior
![screen shot 2018-05-08 at 12 36 54 pm](https://user-images.githubusercontent.com/7464953/39742817-902621a2-52bc-11e8-9c79-bd176883fb43.png)

### How to reproduce
I have upgrade react-navigation version 
"react-navigation": "^1.5.12" . to "react-navigation": "^2.0.0".
- You have to run this cmd in your project code 
"npm i react-navigation@2.0"

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.0
| react-native     |0.55.3
| node             |6.11.0
| npm or yarn      |5.7.1

**Comment by pontusab** [comment]
If you want to configure sceen based here is an example: https://github.com/react-navigation/react-navigation/issues/4120

**Comment by brentvatne** [comment]
https://reactnavigation.org/docs/en/navigation-options-resolution.html
