### ISSUE TITLE
DrawerNavigatior Is Not Displaying 

### ISSUE THREAD

**Issue by ananth10** [react-navigation/react-navigation#4162]
I am trying to implement **DrawerNavigator** in my React Native Application. I have already added some screens in **StackNavigator** then i have added DrawerNavigator inside StackNavigator. but Navigator menu is not showing. can anyone tell me why its not showing . thanks in advance

**Router.js**

`import Home from './Home';
import Profile from './Profile ';
import Settings from './Settings';
import Cart from './Cart ';
import SideMenu from './SideMenu/SideMenu';
import {DrawerNavigator, StackNavigator} from 'react-navigation';

const Stack = {
  Profile: {
    screen: Profile
  },
  Settings: {
    screen: Settings
  },
  Cart: {
    screen: Cart
  }

};

const DrawerRoutes = {
  FirstViewStack: {
    name: 'FirstViewStack',
    screen: StackNavigator(Stack, {initialRouteName: 'Profile'})
  },
  SecondViewStack: {
    name: 'SecondViewStack',
    screen: StackNavigator(Stack, {initialRouteName: 'Settings'})
  },
  ThirdViewStack: {
    name: 'ThirdViewStack',
    screen: StackNavigator(Stack, {initialRouteName: 'Cart'})
  }

};

export const RootNavigation = StackNavigator(
  {

    Drawer: {
      name: 'Drawer',
      screen: DrawerNavigator(DrawerRoutes, {
        contentComponent: SideMenu
      })
    },
    Home: {
      screen: Home,
      navigationOptions: {
        header: null,
        statusBarHidden: true
      }
    }
  },

  {
    initialRouteName: 'Home'
  },

  {
    mode: 'modal',
    headerMode: 'none'
  },
);

`

**Profile Screen. other 2 screens are same like below**

import React, {Component} from 'react';
import {
  Text,
  View
} from 'react-native';

class Profile extends Component {
  render () {
    return (
      <View style={{padding: 50}}>
        <Text>
          Profile
        </Text>
      </View>
    );
  }
}

export default Profile;

`
**SideMenu Component**

import PropTypes from 'prop-types';
import React, {Component} from 'react';
import styles from './SideMenu.style';
import {NavigationActions} from 'react-navigation';
import {ScrollView, Text, View} from 'react-native';

class SideMenu extends Component {
  navigateToScreen = (route) => () => {
    const navigateAction = NavigationActions.navigate({
      routeName: route
    });
    this.props.navigation.dispatch(navigateAction);
  }

  render () {
    return (
      <View style={styles.container}>
        <ScrollView>
          <View>
            <Text style={styles.sectionHeadingStyle}>
              Section 1
            </Text>
            <View style={styles.navSectionStyle}>
              <Text style={styles.navItemStyle} onPress={this.navigateToScreen('Profile')}>
              Profile
              </Text>
            </View>
          </View>
          <View>
            <Text style={styles.sectionHeadingStyle}>
              Section 2
            </Text>
            <View style={styles.navSectionStyle}>
              <Text style={styles.navItemStyle} onPress={this.navigateToScreen('Settings')}>
                Settings
              </Text>
              <Text style={styles.navItemStyle} onPress={this.navigateToScreen('Cart')}>
                Cart
              </Text>
            </View>
          </View>
        </ScrollView>
        <View style={styles.footerContainer}>
          <Text>footer</Text>
        </View>
      </View>
    );
  }
}

SideMenu.propTypes = {
  navigation: PropTypes.object
};

export default SideMenu;
`

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!

**Comment by ananth10** [comment]
@brentvatne I understand it now. i have pushed my sample code in my repo and re-created issue .
**https://github.com/react-navigation/react-navigation/issues/4170**
