### ISSUE TITLE
Wrong parameters for tabBarOnPress

### ISSUE THREAD

**Issue by dino115** [react-navigation/react-navigation#4164]
Hi,
first of all, thank you very much for the great work you are all doing with react-navigation!

I've installed the current version of react-navigation (2.0.0) and my custom `tabBarOnPress` doesn't work anymore. The callback receives an object, only with the `navigation` key.
The missing keys are `previousScene`, `scene` and `jumpToIndex `, still described in the v2 docs.
see: https://reactnavigation.org/docs/en/tab-navigator.html#tabbaronpress

The custom `tabBarOnPress` callback is used to pop scenes in the currently active tab. For now i can use the new pop-to-top feature built into react-navigation. But it pops directly to the root scene, and doesn't navigate back step by step, which is my preferred behaviour.

I think this is the associated line of code: https://github.com/react-navigation/react-navigation-tabs/blob/18c0d5bae8e8f862e2fcdab2a3fa933665261bc2/src/utils/createTabNavigator.js#L79

### Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.0.0
| react-native     | 0.55.3
| node             | 10.0
| npm or yarn      | yarn 1.6.0

**Comment by brentvatne** [comment]
@satya164 - was this change intentional when extracting react-navigation-tabs out?

also related:

https://github.com/react-navigation/react-navigation-tabs/blob/d2aa789109ed0df61c0c0ac7b759ac386a720804/src/views/BottomTabBar.js#L203-L206

https://github.com/react-navigation/react-navigation/blob/6475e32dba16fa27d1df4027ebc83ab76bd7a086/src/views/TabView/TabBarBottom.js#L259-L269

**Comment by satya164** [comment]
@brentvatne yes. I removed the `scene` and `jumpToIndex` parameters since the `navigation` parameter does the same things. and the justification for `previousScene` in this PR is no longer valid since there are focus events that can be used when navigating away from a scene: https://github.com/react-navigation/react-navigation/pull/2790 which is more accurate than doing it in `tabBarOnPress` since it doesn't trigger on navigation changes. I'll go through the docs today and fix any inconsistencies.

@dino115 can you share your code?

**Comment by dominiclind** [comment]
So, jumping in; If i then want to;
Press tab bar icon -> Run action to see if (goto pressed tab OR navigate to modal route AND prevent navigation to pressed tab)

How would i do this?

**Comment by ritz078** [comment]
@satya164 

I was doing this early. How do you recommend this to be done now ?

```js
static navigationOptions = ({ navigation }: { navigation: Navigation }) => ({
    tabBarLabel: "LEADS",
    tabBarIcon: ({ tintColor }: { tintColor: string }) => (
      <Icon name="home" color={tintColor} size={26} />
    ),
    // TODO: Bring this back
    tabBarOnPress: ({ previousScene, scene, jumpToIndex }: any) => {
	  // in the argument I am getting navigation object now
      if (previousScene.index === scene.index) {
        navigation.navigate("summary");
      } else {
        jumpToIndex(scene.index);
      }
    }
  });
```

The behaviour I want to achieve is on the second tap of the active tab, go to the initialRoute of that tab.

**Comment by dino115** [comment]
Sorry for the late response. Here is my old `tabBarOnPress` code:

```javascript
navigationOptions: ({ navigation }) => ({
  tabBarLabel: createTabLabel('module.label'),
  tabBarIcon: createTabIcon('icon-name', 'module-name'),
  tabBarOnPress: ({ previousScene, scene, jumpToIndex }) => {
    if (scene.focused) {
      if (previousScene.routes.length > 1) {
        navigation.goBack(null);
      } else {
        // maybe, some code to scroll to top
      }
    } else {
      return jumpToIndex(scene.index);
    }
  })
})
```

My navigation tree looks like this:

| Drawer navigator
|-- Tab navigator
|---- Stack navigator for module 1
|------- Module 1 scene 1
|------- Module 1 scene 2
|------- Module 1 scene 3
|---- Stack navigator for module 2
|------- Module 2 Scene 1
|------- Module 2 Scene 2
|------- Module 2 Scene 3

**Comment by UlanaXY** [comment]
Hi, in my app every tab in tab navigator has a stack navigator. Now when user selects focused tab, the stack navigator returns to the default screen, I want to prevent this behavior.

I'm using react-navigation 2.0.1.

For now I have something like this:
```javascript
tabBarOnPress: ({ navigation }) => {
    if (navigation.isFocused()) {
        //    do nothing
    } else {
        // normally change tab
    }
},
```
But the [documentation](https://reactnavigation.org/docs/en/bottom-tab-navigator.html#tabbaronpress
) is for old version of this method. I don't know how to prevent default behavior of of tab pressing. @satya164 Could you update the docs or could anyone help with this?

**Comment by satya164** [comment]
@ritz078 you don't need `previousScene` for that. you can use `navigation.isFocused()` for this. the latest version of `react-navigation-tabs` includes a bug fix for this function.

@dino115 you can do `navigation.state.routes.length > 1` with the latest version of `react-navigation-tabs`.

@UlanaXY the latest version of `react-navigation-tabs` should handle this.

**Comment by brentvatne** [comment]
also @dino115 - when you tap an active tab it will pop to top by default, you don't need to implement this on your own. https://github.com/react-navigation/react-navigation-tabs/blob/e257d5db7cac861317d4de574902ceaa24f13b33/src/utils/createTabNavigator.js#L80-L91

**Comment by aks1994** [comment]
@brentvatne when using redux with react navigation, I get "Cannot read property 'routes' of null" when clicking on the active tab of my BottomTabNavigator. I also want to get it to pop to top when clicking on active tab so is there something different I need to do if using Redux? Thanks

**Comment by brentvatne** [comment]
i have no idea, you will want to ask that question on the redux repo https://github.com/react-navigation/react-navigation-redux-helpers
