### ISSUE TITLE
Swipe-Back gesture stuck/doesn't work in Release build, fine in Debug.

### ISSUE THREAD

**Issue by VolkRiot** [react-navigation/react-navigation#4166]
Hey guys, posting this issue here to see if anyone has any insights. Swipe back gestures are stuck and generally do not work when the app is build for Release. True on real devices as well. If you hold down the touch and then drag it works! Some sort of race condition? 

A bit time crunched now to recreate in a separate example app, will try to do so a bit later. 

Has anyone encountered this problem?
Any insight will be appreciated.

### Current Behavior

#Release
![Release](https://thumbs.gfycat.com/EmbarrassedPlasticAntlion-size_restricted.gif)

#Debug
![Debug](https://thumbs.gfycat.com/SophisticatedFlippantAntarcticgiantpetrel-size_restricted.gif)

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.5.11
| react-native     | 0.55.2
| node             | 10.0.0
| npm or yarn      | yarn

**Comment by brentvatne** [comment]
heya, feel free to re-create this when you have a repro case.

**Comment by janziemba** [comment]
The same happens to me. This is a real issue and should not be closed.

**Comment by VolkRiot** [comment]
This was caused by the incorporation of an iOS library called UXCam. Essentially UXCam records the user interacting with the UI and uploads it to their service. It would interrupt the gesture as RN essentially yields to other gesture recognizers over its own views.

See here -- 
https://github.com/alexbrillant/react-native-deck-swiper/issues/122

Hope that helps!

**Comment by janziemba** [comment]
@VolkRiot Thank you very much! 😊

**Comment by kfitzsimons** [comment]
Thanks @VolkRiot
