### ISSUE TITLE
SwitchNavigator.router is undefined. "Cannot read property getStateforAction of undefined

### ISSUE THREAD

**Issue by kevinNejad** [react-navigation/react-navigation#4169]
I was trying to implement redux with SwitchNavigator

`const ProfileStack = createStackNavigator(ProfileScenes, {
  headerMode: 'none',
  transitionConfig: TransitionConfiguration,
});
const MessageStack = createStackNavigator(MessageScenes, {
  headerMode: 'none',
  transitionConfig: TransitionConfiguration,
});
`

`const AppNavigator = createBottomTabNavigator(
  {
    Message: { screen: MessagetStack },
    Profile: { screen: ProfileStack },
  },
  {
    initialRouteName: 'Profile',
    navigationOptions: ({ navigation }) => ({
      tabBarIcon: ({ focused, tintColor }) => {
        const { routeName } = navigation.state;
        switch (routeName) {
          case 'Message':
            return <TabBarIcon name="message" focused={focused} />;
          case 'Profile':
            return <TabBarIcon name="profile" focused={focused} />;
          default:
            return null;
        }
      },
    }),
    tabBarOptions: {
      activeTintColor: 'tomato',
      inactiveTintColor: 'gray',
      style: {
        backgroundColor: 'rgba(255,255,255, 0.95)',

        position: 'absolute',
        left: 0,
        right: 0,
        bottom: 0,
      },
    },
    tabBarPosition: 'bottom',
    animationEnabled: false,
    swipeEnabled: false,
  },
);`

`const rootNavigator = authorised => createSwitchNavigator(
  {
    authorised: {
      screen: AppNavigator,
    },
    unauthorised: {
      screen: LoginNavigator,
    },
  },
  {
    initialRouteName: authorised ? 'authorised' : 'unauthorised',
    headerMode: 'none',
  },
);`

`const initialState = rootNavigator.router.getStateForAction(rootNavigator.router.getActionForPathAndParams('authorised'));

const navReducer = (state = initialState, action) => {
  switch (action.type) {
    case actionsTypes.NAVIGATION_NAVIGATE:
    case actionsTypes.NAVIGATION_BACK:
    case actionsTypes.NAVIGATION_SET_PARAMS:
    case actionsTypes.NAVIGATION_INIT:
    case actionsTypes.NAVIGATION_RESET:
    case actionsTypes.NAVIGATION_URI:
      return rootNavigator.router.getStateForAction(action, state) || state;
    default:
      return state;
  }
};`

`const navMiddleware = createReactNavigationReduxMiddleware(
  'root',
  state => state.nav,
);
const addListener = createReduxBoundAddListener('root');`

`render() {
    const { loginState } = this.state;

    this.navigation = {
      dispatch: this.props.dispatch,
      state: this.props.navigation,
      addListener,
    };

    const Layout = rootNavigator(loginState);

    return (
      <View style={{ flex: 1 }}>
        <Layout navigation={this.navigation} />
      </View>
    );
  }`

| software         | version
| ---------------- | -------
| react-navigation | 2.0.0
| react-native     | 0.55.3
| node             | 8.0.0
| npm or yarn      | 5.6.0

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!

**Comment by kevinNejad** [comment]
@brentvatne sorry for messy writing, I was trying to put a github link, but you replied back in no time.
I am now reproducing code and will report if I coudnt manage to get it work.

**Comment by brentvatne** [comment]
thanks @kevinNejad!

**Comment by zmnv** [comment]
Any solutions?
