### ISSUE TITLE
openDrawer (v2) for DrawerNavigation 

### ISSUE THREAD

**Issue by Ronnyrr** [react-navigation/react-navigation#4174]
### Current Behavior
I'm using react-navigation V2 with multiple navigation types in it. As main navigation I'm using a `TabNavigator` called `MainTab`. This TabNavigator includes multiple `StackNavigator` components. In the StackNavigator I'll use `navigationOptions` to change the `headerLeft` render a hamburger icon. From the hamburger icon I want to open a `DrawerNavigator`. This is where I got stuck.

![img_0782](https://user-images.githubusercontent.com/4519142/39814945-b1187146-5396-11e8-9892-a2e6701ad589.PNG)

As mentoined I'm running V2 of react-navigation, so I did read the change log. Using `props.navigation.openDrawer()` instead of the old API seems like a good update to me. 

**MainTab**
```
import { createBottomTabNavigator } from 'react-navigation';

import ReservationsStack from './ReservationsStack';
import ClassificationsStack from './ClassificationsStack';

const MainTab = createBottomTabNavigator(
  {
    Reservations: { screen: ReservationsStack },
    Classifications: { screen: ClassificationsStack },
  },
  {
    tabBarOptions: {
      inactiveTintColor: 'gray',
    },
    animationEnabled: false,
    swipeEnabled: false,
  },
);

export default MainTab;
```

**ReservationsStack**
```
import React from 'react';
import { createStackNavigator } from 'react-navigation';

import MainDrawer from './MainDrawer';

import { DrawerOpen } from '../components';
import Reservations from '../screens/Reservations';
import ReservationDetail from '../screens/ReservationDetail';

const ReservationsStack = createStackNavigator({
  ReservationOverview: {
    screen: Reservations,
    navigationOptions: () => ({
      title: 'Mijn reserveringen',
      headerLeft: <DrawerOpen />,
      headerStyle: {
        paddingRight: 15,
        paddingLeft: 15,
      },
    }),
  },
  ReservationDetail: {
    screen: ReservationDetail,
    navigationOptions: props => ({
      title: `Reservering ${props.name}`,
    }),
  },
  Drawer: { screen: MainDrawer },
}, {
  initialRouteName: 'ReservationOverview',
});

export default ReservationsStack;
```

**MainDrawer**
```
import { createDrawerNavigator } from 'react-navigation';

import Dashboard from '../screens/Dashboard';

const MainDrawer = createDrawerNavigator({
  Dashboard: {
    screen: Dashboard,
    navigationOptions: {
      drawerLabel: 'Dashboard',
    },
  },
});

export default MainDrawer;
```

**DrawerOpen**
```
import React from 'react';
import { TouchableOpacity } from 'react-native';
import { withNavigation } from 'react-navigation';
import { Ionicons } from '@expo/vector-icons';
import PT from 'prop-types';

const DrawerOpen = (props) => {
  console.log('navigate', props.navigation);

  return (
    <TouchableOpacity onPress={() => props.navigation.openDrawer()}>
      <Ionicons name="md-menu" size={32} />
    </TouchableOpacity>
  );
};

DrawerOpen.propTypes = {
  navigation: PT.shape({
    openDrawer: PT.func,
  }),
};

export default withNavigation(DrawerOpen);
```

### Expected Behavior
I expect that the `DrawerNavigator` should open, instead I got the error `undefined is not a function (evaluating 'props.navigation.openDrawer()')`:

![img_0781](https://user-images.githubusercontent.com/4519142/39814944-b0dd2e9c-5396-11e8-98d5-e9ee72cf105f.PNG)

This suggest the new react-navigation v2 API doens't work as expected. As you can see above I log the navigation, response. The log shows there is no `openDrawer` function indeed.

<img width="594" alt="screen shot 2018-05-09 at 14 38 01" src="https://user-images.githubusercontent.com/4519142/39814967-c39871b8-5396-11e8-9aa7-c388e8d65af8.png">

When I switch back to the old API `props.navigation.navigate('DrawerOpen')` the error disappears. The hamburger icon flickers opacity on click, but no action happens. 

### Questions
**1. Correct usage of navigations**
Am I using this navigations the right way? Drawer inside Tab and Stack navigators. The Drawer should be global. In this example it's used in the ReservationsStack, but also the other tab, ClassificationsStack, should be able to use the DrawerNavigator. 

**2. v2 API doesn't work?**
Why does the v2 API not work at all and throws an error? Is my code incorrect? 

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^2.0.0
| react-native     | ~0.55.2
| node             | v9.11.1
| yarn      | 1.3.2
| expo      | ^27.0.1

**Comment by theohdv** [comment]
I have the same problem, as a workaround you can use:
```javascript
import { DrawerActions } from 'react-navigation';

this.props.navigation.dispatch(DrawerActions.closeDrawer());
```

**Comment by Ronnyrr** [comment]
Thanks for your reply. This did fix the error indeed, but it still doesn't open the `DrawerNavigation`. It triggers the same action as the old API syntax mentioned in my first post. The icon flickers, but no further action is fired. Is my Drawer in Stack in Tab navigator the correct usage?

**Comment by brentvatne** [comment]
the problem is the order of nesting - if the stack navigator is not inside of the drawer, it will not have the `openDrawer` function and you will need to use the approach @theohdv mentioned above. @ericvicenti perhaps we need to improve release notes to explain this better

**Comment by theohdv** [comment]
@brentvatne I am using the `contentComponent` prop and in my component I also don't have access to `openDrawer()` and `closeDrawer()`.

```javascript
const ABC = createDrawerNavigator({
  // screens...
}, {
	contentComponent: DrawerMenu, <== This component does not have access to drawer actions
});
```

**Comment by Ronnyrr** [comment]
@brentvatne Ok, clear. But how can I use a TabNavigator and a DrawerNavigator both as main navigation? In my screenshot from the first post you can see I use a TabNavigator in the bottom as main navigation, but I would like to access my DrawerNavigation as secondary navigation.  Is this even possible?

**Comment by brentvatne** [comment]
@Ronnyrr - you can always call openDrawer by dispatching the action like @theohdv above. you don't have access to the helper if the screen you're trying to call it from is in a different navigator subtree. you can reorganize where the drawer navigator is so that it's shared among screens that would want to open the drawer if you like.

@theohdv - the content component (and tab bar component) doesn't have access to the "child navigation" object that the routes do. we need to clarify this - I opened this issue a couple of days ago to discuss https://github.com/react-navigation/rfcs/issues/42 - I'm not sure what the best approach is.

**Comment by filipencus** [comment]
I don't understand why this issue is closed? It still happens and is very very poor explained into the docs. What solution do you provide guys? At least recognise that it is a bug.
Thank you so much.

**Comment by brentvatne** [comment]
@filipencus - it's not a bug, as explained in my comment above. you're welcome to open an issue against the website repo if you would like the documentation to be improved: http://github.com/react-navigation/website

**Comment by brentvatne** [comment]
no need to call dispatch anymore as per 2.3.0 https://github.com/react-navigation/react-navigation/releases/tag/2.3.0
