### ISSUE TITLE
Android hardware back not working

### ISSUE THREAD

**Issue by tapz** [react-navigation/react-navigation#4175]
### Current Behavior

Android hardware back button does nothing.

### Expected Behavior

After pushing a route a back arrow appears on the navigation bar. It takes you back to the previous screen. Clicking Android hardware back button should do the same.

### How to reproduce

createStackNavigator
StackActions.push(

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.0.0
| react-native     | 0.55.3
| node             | 
| npm or yarn      | 1.6.0

Android 8 (OnePlus 5T)
Android 7 (Samsung Galaxy J5 2017)

**Comment by brentvatne** [comment]
this works as expected: https://snack.expo.io/rknjJce0f

perhaps you are using redux and didn't add back button handling. we'll need a repro case. either way, please put more effort into issues in the future.

**Comment by domingoxx** [comment]
@brentvatne I'm using redux too, And have same issue, Can you write a sample code to explain `didn't add back button handling`, how can i to do it.

**Comment by shekharskamble** [comment]
same issue here :(

**Comment by noambonnie** [comment]
@tapz were you able to resolve this issue? It happens to me. I'm not using redux for navigation (though I am using it in my project for other things).

**Comment by fukemy** [comment]
same issues I dont know why hardware back button miniminize my app for Android >= 10, on lower version it's work normally
