### ISSUE TITLE
Add navbar alert to Header

### ISSUE THREAD

**Issue by renanpupin** [react-navigation/react-navigation#4177]
Hello,
I would like to add a alert component under the Navbar (Header) similar to Facebook and instagram.

<img width="752" alt="captura de tela 2018-05-09 as 12 00 35" src="https://user-images.githubusercontent.com/8743530/39822335-b1cb487c-5380-11e8-8624-5fcabf407046.png">

I search the documentation and it does not describe how to override that Header, so can I add this black alert at the bottom of navbar?

Thanks.

**Comment by brentvatne** [comment]
hi there! this is a question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.
