### ISSUE TITLE
Reset action causes animation "glitches" on iOS

### ISSUE THREAD

**Issue by benjaminreid** [react-navigation/react-navigation#4178]
### Current Behavior

In React Native, when using using a reset action, the animation in `2.0` is like this... It’s also not often the same, black headers, flickers...

![2 0](https://user-images.githubusercontent.com/713128/39825038-bf85be2a-53a8-11e8-91e3-679f577578f9.gif)

### Expected Behavior

In `1.5` the animation (with the same code, minus the replacement of `StackActions`) the animation is as expected.

![1 5](https://user-images.githubusercontent.com/713128/39825092-e2094282-53a8-11e8-8e7d-4af883d2f65d.gif)

### How to reproduce

This can be reproduced by simply firing a reset action.

```js
const resetAction = StackActions.reset({
  index: 0,
  actions: [NavigationActions.navigate({ routeName: "Intro" })],
});

<Button onPress={() => navigation.dispatch(resetAction)}>Continue</Button>
```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.0.0
| react-native     | 0.55.3
| node             | 9.3.0
| npm or yarn      | 1.3.2

**Comment by sunweiyang** [comment]
I observe this exact glitchy flashing issue, on both iOS and Android.

**Comment by ericvicenti** [comment]
The code example here is incomplete. I’m guessing this is a stack inside a stack? Or is the header disabled on one of the screens?

If the latter, the issue might be related to @skevy’s work on the header transition

**Comment by sunweiyang** [comment]
@ericvicenti We're trying to get the same result as in #1493 -- it was a different problem back in v1 (`NavigationActions.reset` instead of `StackActions.reset`), but the result want is the same (smoothly transitioning from top of stack back to view we want to reset to).

**Comment by brentvatne** [comment]
please create an example on snack that reproduces this if you care about the issue

**Comment by ikhilko** [comment]
@brentvatne created a Snack as you asked: https://snack.expo.io/SJBT_tqym

**Comment by ericvicenti** [comment]
Ah, this is bad. I'll fix it
