### ISSUE TITLE
undefined is not a function => this2_.props.navigation.navigate

### ISSUE THREAD

**Issue by alexvaltin97** [react-navigation/react-navigation#4180]
I can't find the problem... Using this guide: http://docs.nativebase.io/docs/examples/navigation/StackNavigationExample.html

My Navigator:

> import React, { Component } from 'react';
> import { TabNavigator } from 'react-navigation';
> 
> import Feed from '../components/Feed';
> import Camera from '../components/Camera';
> 
> import MainMenu from './MainMenu';
> 
> const MainRouter = TabNavigator(
>   {
>     Feed: { screen: Feed },
>     Camera: { screen: Camera },
>   },
>   {
>     tabBarPosition: 'bottom',
>     tabBarComponent: props => <MainMenu {...props} />
>   }
> );
> 
> export default MainRouter;

MainMenu:

> import React, { Component } from 'react';
> import { Button, Text, Icon, Footer, FooterTab } from 'native-base';
> 
> class MainMenu extends Component {
>   render() {
>     return (
>       <Footer>
>         <FooterTab>
>           <Button
>             vertical
> 
>             onPress={() => this.props.navigation.navigate('Feed')}
>           >
>             <Icon name="bowtie" />
>             <Text>Lucy</Text>
>           </Button>
>           <Button
>             vertical
> 
>             onPress={() => this.props.navigation.navigate('Camera')}
>           >
>             <Icon name="briefcase" />
>             <Text>Nine</Text>
>           </Button>
>           <Button
>             vertical
>           >
>             <Icon name="headset" />
>             <Text>Jade</Text>
>           </Button>
>         </FooterTab>
>       </Footer>
>     );
>   }
> }
> 
> export default MainMenu;

App.js:

> import React, { Component } from 'react';
> import { YellowBox } from 'react-native';
> import { Provider } from 'react-redux';
> import { createStore } from 'redux';
> import MainRouter from './config/MainRouter';
> 
> import reducers from './reducers';
> 
> YellowBox.ignoreWarnings(['Warning: isMounted(...) is deprecated', 'Module RCTImageLoader']);
> 
> class App extends Component {
>   render() {
>     const store = createStore(reducers);
>     return (
>       <Provider store={store}>
>           <MainRouter />
>       </Provider>
>     );
>   }
> }
> 
> export default App;

When I click on the menu I always get "undefined is not a function this2_.props.navigation.navigate('Camera)"

What is wrong with my code? 

Thank you

**Comment by brentvatne** [comment]
might want to post this issue to the nativebase docs, given that's the guide you're following :)
