### ISSUE TITLE
Tab titles aren't inherited from a wrapped Stack Navigation's navigationOptions.title [v2]

### ISSUE THREAD

**Issue by cmelendez** [react-navigation/react-navigation#4182]
### Current Behavior

- When a Tab Navigator is wrapped around 1 or more Stack Navigators, tab titles are inherited from the Stack's `navigationOptions.title` attribute. [docs](https://reactnavigation.org/docs/en/stack-navigator.html#title).
- Currently the title is being ignored in tabs but used properly in the header.
- This is working in v1.

### Expected Behavior

- The tab's title should be inherited from the wrapped Stack Navigator `navigationOptions.title` attribute.

### How to reproduce

- Example code (can be run in Expo)

```
import React, { Component } from 'react';
import { Text, View } from 'react-native';
import { createStackNavigator, createBottomTabNavigator } from 'react-navigation';

import { Constants } from 'expo';

class HomeScreen extends React.Component {
  render() {
    return (
      <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
        <Text>Home!</Text>
      </View>
    );
  }
}

const MyStackNavigator = createStackNavigator({
  "Bad.Home": {
    screen: () => {
      return <HomeScreen />
    }
  }
}, {
  navigationOptions: {
    title: "Correct Title"
  }
});

export default createBottomTabNavigator({
  "Bad.TabTitle": {
    screen: () => {
      return <MyStackNavigator />
    }
  }
});
```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.0.1
| react-native     | 0.55.3
| node             | 9.9.0
| yarn      | 1.6.0

**Comment by cmelendez** [comment]
In the example, the `Correct Title` string is used as the header's title, but the `Bad.Tabtitle` string is used as the tab's label but it should be `Correct Title`

**Comment by brentvatne** [comment]
see the discussion here: https://github.com/react-navigation/react-navigation-tabs/issues/19
also see: https://reactnavigation.org/docs/en/navigation-options-resolution.html
