### ISSUE TITLE
StacksOverTabs-TabNav-navigationOptions-title doesn't always work

### ISSUE THREAD

**Issue by cocoay** [react-navigation/react-navigation#4184]
### Current Behavior

StacksOverTabs-TabNav-navigationOptions-title doesn't always work

### How to reproduce

Example-NavigationPlayground

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.0.1
| react-native     | 0.55.3
| node             | 9.11.1
| npm or yarn      | 1.6.0

**Comment by shoaibehmed** [comment]
tabBarVisible: false doesn't either.

**Comment by brentvatne** [comment]
@cocoay - please follow the template and provide sufficient information so i have some idea what is going on. I don't much like guessing :)

@shoaibehmed https://github.com/react-navigation/react-navigation-tabs/issues/19
