### ISSUE TITLE
StackActions can't use

### ISSUE THREAD

**Issue by flasco** [react-navigation/react-navigation#4200]
### Current Behavior

I want to use `StackActions.reset` to reset, but it can't work.
some code
```js
import { StackActions, NavigationActions } from 'react-navigation';

onLogin = () => {
    this.props.navigation.dispatch(StackActions.reset({
      index: 0,
      actions: [NavigationActions.navigate({ routeName: 'Main' })],
    })
    )
  }
// it not work, can't jump.
```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.0.1
| react-native     | 0.55.4
| node             | 8.11.1
| npm or yarn      | yarn 1.6.0

**Comment by stevemk14ebr** [comment]
This doesn't work for me either. The reset function seems undefined

**Comment by mbret** [comment]
The reset action does not exist anymore in react-nav v2 -> https://reactnavigation.org/docs/en/navigation-actions.html. do you have any idea on what we should use instead ?

**Comment by stevemk14ebr** [comment]
Yea it seems to have moved, i use this snippet from the docs and it worked:
```
const resetAction = StackActions.reset({
    index: 0,
    actions: [NavigationActions.navigate({ routeName: 'Home' })],
});
this.props.navigation.dispatch(resetAction);
```

**Comment by flasco** [comment]
@stevemk14ebr 
can you show me the code that how to import StackActions? is that your react-navigation version is 2.0.1?

**Comment by stevemk14ebr** [comment]
Sure
`import {StackActions, NavigationActions } from 'react-navigation';`

full code called from my login module to navigate to 'home'
```
componentDidMount() {
    /*This prevents the
    hardware back button from being able to go back to loading screen
    */

    setTimeout(() => {
        const resetAction = StackActions.reset({
            index: 0,
            actions: [NavigationActions.navigate({ routeName: 'Home' })],
        });
        this.props.navigation.dispatch(resetAction);
    }, 3000);
}
```

**Comment by flasco** [comment]
I tried but it not work either. I use console.log to print StackActions, it's not undefined. I think it should be fixed...
there is my code
```js
  onLogin = () => {
    console.log(StackActions);
    const resetAction = StackActions.reset({
      index: 0,
      actions: [NavigationActions.navigate({ routeName: 'Home' })]
    });
    this.props.navigation.dispatch(resetAction);

    // this.props.dispatch(createAction('app/login')())
  }
```
and the next is print log 

![image](https://user-images.githubusercontent.com/20221600/39976719-ce31f34a-5767-11e8-98c2-6195d4b513d8.png)

**Comment by flasco** [comment]
I know NavigationActions.reset is usable in version 1.5, but v2 solved many problems of my project, I just hope this bug can be fixed, rather than downgrade version. thanks for your reply~

**Comment by stevemk14ebr** [comment]
What issue exactly are you guys having, this is working for me once i switched to stackactions?

**Comment by mmmikeal** [comment]
@stevemk14ebr this was last week so I kind of forgot but I believe StackActions.reset was throwing an error cannot read reset of undefined. That's why the author asked if he was importing StackActions wrong. 

If it is working for others, but not for some, then I imagine it'd be some problem with varying react/redux/package.json/webpack versions or something

**Comment by mmmikeal** [comment]
@flasco out of curiosity what advntages did the new version give?

**Comment by vatex** [comment]
I installed latest version of stack navigation and when I execute reset block of code, it isn't doing anything :/

**Comment by brentvatne** [comment]
hello! for anyone who runs into an issue that seems related to this, please create a new issue and follow the issue template and we can help out :)
