### ISSUE TITLE
Headers of tabs are empty after react-navigation updated to v2

### ISSUE THREAD

**Issue by Gentlee** [react-navigation/react-navigation#4203]
### Current Behavior

Headers of tabs (components from TabNavigator's routeConfig) are empty after react-navigation updated to v2. For components other than tabs it works well. In v1 it works well.

### Expected Behavior

There should be titles and buttons.

### How to reproduce

Here is a question on [stackoverflow](https://stackoverflow.com/questions/50275854/header-is-empty-after-react-navigation-updated-to-v2) with code examples.
It appears in 100% cases, just run the app with tab bar, nested in stack navigator.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.0.1
| react-native     | 0.55.4
| node             | 9.11.1
| npm or yarn      | npm 6.0.0

**Comment by someok** [comment]
I think v2 is a incomplete version, the tabbar's view not include header:

createTabNavigator:

```
 _renderScene = ({ route }) => {
      const { screenProps, descriptors } = this.props;
      const descriptor = descriptors[route.key];
      const TabComponent = descriptor.getComponent();
      return <SceneView screenProps={screenProps} navigation={descriptor.navigation} component={TabComponent} />;
    };
```

The `TabComponent` just only render the `screen` component, not include the header.

**Comment by Bonobomagno** [comment]
they set createTabNavigator as deprecated on the docs

**Comment by brentvatne** [comment]
https://github.com/react-navigation/react-navigation-tabs/issues/19

**Comment by leethree** [comment]
@brentvatne I don't think the linked issue is identical to this one. Our project have multiple screens inside BottomTabNavigator _nested in_ StackNavigator. What is the official way to set titles and nav buttons from screens inside BottomTabNavigator?

This used to work as intended in v1. All the v2 documentations only mention the case when StackNavigator is nested *inside* TabNavigator. But not the other way around.

Also, what if we need to update `navigationOptions` dynamically from the screens nested in two layers of Navigators? Is that still supported?

Thanks!

**Comment by leethree** [comment]
I found a workaround. You can manually pass `navigationOptions` from screen component to outside navigator.

```js
TabBarNavigator.navigationOptions = ({ navigation }) => {
  const component = TabBarNavigator.router.getComponentForState(navigation.state);
  if (typeof component.navigationOptions === 'function') {
    return component.navigationOptions({ navigation });
  }
  return component.navigationOptions;
};
```

It's not very clean but should work OK.

**Comment by brentvatne** [comment]
> Our project have multiple screens inside BottomTabNavigator nested in StackNavigator. What is the official way to set titles and nav buttons from screens inside BottomTabNavigator?

I would put a *stack inside each tab* rather than put the tab inside of a stack. Or have stack -> tab -> stack, and disable the header on the tab navigator, so the header when inside of the tab navigator comes from the stacks inside of it rather than the parent stack.

We do need to improve docs here for sure!

> Also, what if we need to update `navigationOptions` dynamically from the screens nested in two layers of Navigators? Is that still supported?

probably you shouldn't do this. if you're doing this you might want to consider using a custom navigator or some other way to pass data around. organizing navigators differently can also clean this up, like the approach I mention above.

**Comment by leethree** [comment]
@brentvatne Thanks for your response. I added my input to this thread: https://github.com/react-navigation/react-navigation.github.io/issues/152

**Comment by Piusha** [comment]
any Solution for this ?

https://stackoverflow.com/questions/50502090/react-native-react-navigation-v2-not-showing-screen-header

**Comment by Alisan26** [comment]
I  had same ıssue too my solution is added my stacknavigator headerMode: 'auto' property, I using expo template and RootNavigation file is added headerMode: 'auto' too, it worked for me,

Roote navigation like this =>

const RootStackNavigator = createStackNavigator(
  {
    Main: {
      screen: MainTabNavigator,
    },
  },
  {
    navigationOptions: () => ({
      headerTitleStyle: {
        fontWeight: 'normal',
      },
    }),
 headerMode: 'auto'
  }
);

**Comment by shuchenliu** [comment]
According to v2 [RFCs](https://github.com/react-navigation/rfcs/blob/master/text/0005-shallow-navigation-options.md), 

`navigationOptions` are **no longer recursively** extracted from nestedNavigator, 

Thus `title` defined in `static navigationOptions` **or** in route config would **only** apply to the specific component or that route, rather than the top navigator like before. 

In this case, ` title` field has no effect on `TabNavigator` (or `createBottomTabNavigator` ), so it is natural that header would be empty.

Solution: 

Avoid writing:
```javascript
class MyComponent extends React.Component {
 static navigationOptions = ({ navigation }) => {
        return {
            title: 'MyTitle',
        };
   };
 ...
}

// or

const MyTabs = createBottomTabNavigator({
  MyTab: {
    screen: MyScreen,
    navigationOptions : {
     title: 'MyTitle',
  },
  }
})

```

Instead, explicitly define navigationOptions for your TabNavigator:
```javascript
const MyTabs = createBottomTabNavigator({
  MyTab: {
    screen: MyScreen,
  }
 ...
})

// right after declare `MyTabs`
MyTabs.navigationOptions = ({ navigation }) => {
  const { routes, index } = navigation.state;
  const navigationOptions = {};
  
 // here's an example, but you can dynamically define title 
 // however you like given `routes` & `index`
  
 if (routes[index].routeName === 'MyTab') {
    navigationOptions.title = 'MyTitle'; 
 }
  
  return navigationOptions;
}
```

**Comment by rayzor65** [comment]
Hi @brentvatne I change my setup to the suggested "stack inside each tab" but now I have the situation where the 'active' tab does not change, it just stays on the main one. I can navigate between tabs though. Wondering is this an issue particular to my setup or a known issue?

**Comment by brentvatne** [comment]
if you for some reason you don't like the perfectly fine solution that @shuchenliu proposed there are other options in https://reactnavigation.org/docs/en/navigation-options-resolution.html

@rayzor65 - what do you mean by 'give stack properties the same names'? curious to hear what went wrong

**Comment by rayzor65** [comment]
@brentvatne it was my mistake I realised, I read your response in https://github.com/react-navigation/react-navigation/issues/3662 regarding the clashing route names. I wasn't aware I couldn't name them the same inside tab and stack. After renaming the tab was able to pick up the active tab again. Thanks for the response.
