### ISSUE TITLE
Custom Tabs don't remember screen state.

### ISSUE THREAD

**Issue by dylancompanjen** [react-navigation/react-navigation#4204]
### Current Behavior

I'm running the 'CustomTabs' example. If you switch a tab and return back, the state from the previous screen is lost.

### Expected Behavior

Screen state should be remembered. So if for e.g. I scroll all the way down on screen 1, switch to screen 2 and switch back to screen 1, the scroll position should be down like it was before switching tabs.
This behavior exists when using the standard TabNavigator, but is lost when using the CustomTabs example.

### How to reproduce

I made a snack which uses the CustomTabs example and added extra lipsum text.
https://snack.expo.io/HkD-jCf0G

If you scroll down on the 'Home' screen, switch to the 'Notifications' screen and go again to the 'Home' screen you will notice that the screen state of 'Home' has been reset. (Scroll pos is at the top again)

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.0.1
| react-native     |
| node             |
| npm or yarn      |

**Comment by brentvatne** [comment]
this isn't a bug. this is just a very basic custom tabs example. remember that with custom navigators the view layer is entirely up to you. you need to make keeping the views around but hiding them when you switch tabs
