### ISSUE TITLE
Static navigationOptions no longer works v2

### ISSUE THREAD

**Issue by calintamas** [react-navigation/react-navigation#4207]
### Current Behavior

The TabNavigator seems to ignore the options returned by a static `navigationOptions` method from inside a (connected with redux) component.

```javascript
static navigationOptions = ({ navigation }) => ({
    tabBarVisible: false
})
```

Works fine in `1.5.11` or when the component is not redux connected.

### Expected Behavior

Should be able to return `navigationOptions` from within a redux connected component.

### How to reproduce

- Create a `SwitchNavigator` that contains a `StackNavigator` and a `TabNavigator`.
- Within the `TabNavigator`, there are 3 tabs.
- The first tab contains 2 screens in a `StackNavigator`.
- Within the first tab, The initialScreen should have `tabBarVisible: true`, while when navigating to the second screen the tab bar should be hidden.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.0.1
| react-native     | 0.55.3
| node             | 8.5.0
| npm or yarn      | 5.3.0

Thanks

**Comment by skabbes** [comment]
It sounds like potentially this is explained by this breaking change https://reactnavigation.org/blog/#shallow-navigation-options

Can you confirm?

**Comment by calintamas** [comment]
@skabbes That is right. But, in this case, how can I set `tabBarVisible: false` for a particular screen inside a `StackNavigator` (only for ScreenB, for example)?

```javascript
const LoggedInNavigator = createBottomTabNavigator({
  Dashboard: {
     screen: DashboardStack
  }
});

const DashboardStack = createStackNavigator({
  ScreenA: {
     screen: ScreenA
  },
  ScreenB: {
    screen: ScreenB
  }
});
```

Thank you for your help!

**Comment by brentvatne** [comment]
https://github.com/react-navigation/react-navigation-tabs/issues/19
