### ISSUE TITLE
MaterialTopTabNavigator with null header in StackNavigator cause empty space between tabs and top of the phone screen

### ISSUE THREAD

**Issue by vshab** [react-navigation/react-navigation#4208]
### Current Behavior

I have `MaterialTopTabNavigator` with `header: null` in `StackNavigator`.  Setting `height` more than 44 for a header causes a gap between screen top and the header top. I've tested on iOS less than iPhone X.

<img width="344" alt="screen shot 2018-05-12 at 02 21 43" src="https://user-images.githubusercontent.com/6755908/39943101-df38a270-558b-11e8-8511-d87c83833f17.png">

Setting negative `margin` for the stack header fixes appearance but breaks screen change animation on iOS.

### Expected Behavior

Header should start from the top of the screen.

<img width="353" alt="screen shot 2018-05-12 at 02 22 40" src="https://user-images.githubusercontent.com/6755908/39943110-e9ce5e5a-558b-11e8-89d9-fe5d6e7f9465.png">

### How to reproduce

Put `StackNavigator` inside `MaterialTopTabNavigator`. Set `header: null` for MaterialTopTabNavigator screen.  Set `tabBarOptions.style` for first and  `navigationOptions.headerStyle` for second to `{ height: 64 }`.

https://snack.expo.io/SyMs6vXCf

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.0.1
| react-native     | 0.54.2
| node             | 10.1.0
| yarn      | 1.6.0

**Comment by brentvatne** [comment]
discussion in https://github.com/react-navigation/rfcs/issues/13

feel free to open a pr for a temporary fix
