### ISSUE TITLE
creating simple stacknavigator using createStackNavigator

### ISSUE THREAD

**Issue by dheerajsinghanktech** [react-navigation/react-navigation#4209]
Using react-navigation less 2.0 everythings running perfectly. But as I upgraded the react-navigation "react-navigation": "^2.0.1" and then I am getting bellow error.

Attempted to assign to readonly property.
popProvider
    ReactNativeRenderer-dev.js:8624:10
unwindWork
    ReactNativeRenderer-dev.js:10368:20
completeUnitOfWork
    ReactNativeRenderer-dev.js:12288:31
renderRoot
    ReactNativeRenderer-dev.js:12450:44
performWorkOnRoot
    ReactNativeRenderer-dev.js:13034:34
performWork
    ReactNativeRenderer-dev.js:12951:26
performSyncWork
    ReactNativeRenderer-dev.js:12913:16
requestWork
    ReactNativeRenderer-dev.js:12799:6
scheduleWorkImpl
    ReactNativeRenderer-dev.js:12666:24
scheduleWork
    ReactNativeRenderer-dev.js:12622:28
scheduleRootUpdate
    ReactNativeRenderer-dev.js:13324:17
_updateContainerAtExpirationTime
    ReactNativeRenderer-dev.js:13360:6
updateContainer
    ReactNativeRenderer-dev.js:13385:8
render
    ReactNativeRenderer-dev.js:14119:35
renderApplication
    renderApplication.js:58:21
run
    AppRegistry.js:104:10
runApplication
    AppRegistry.js:196:26
__callFunction
    MessageQueue.js:353:47
<unknown>
    MessageQueue.js:118:26
__guardSafe
    MessageQueue.js:316:6
callFunctionReturnFlushedQueue
    MessageQueue.js:117:17

**Comment by dcvz** [comment]
I have a similar issue on the same line but my issue reads as `undefined is not an object (evaluating 'context._currentValue = currentValue')

**Comment by dcvz** [comment]
Solved my particular issue! Looks like [this commit] https://github.com/facebook/react/commit/ba245f6f9b0bf31c2ebff5c087c21bcae111e6c3 changed the way context works in React `16.3.1+`.

Downgrading back to v16.3.0 fixed my issue.

**Comment by rizwanahmed19** [comment]
I'm having the same problem :(

**Comment by zacherkkila** [comment]
Same issue here, downgrading to 2.0.0 worked for me as well

react-native:0.54.4

**Comment by alex-mironov** [comment]
are there any plans to fix this?

**Comment by sasurau4** [comment]
Same issue here, downgrading to react *v16.3.0* fixed it.
react-navigation is still *v2.0.1* work fine.
