### ISSUE TITLE
 how can i hide the bottomtabbar  in some screen

### ISSUE THREAD

**Issue by tangxuelei** [react-navigation/react-navigation#4214]
### Current Behavior

- i used the createBottomTabNavigator in my app ,but how can i hide the bottomtabbar  in some screen

### Expected Behavior
-hide the bottomtabbar  in some screen

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |2.0.0-rc.9
| react-native     |0.55.3
| node             |0.2.0
| npm or yarn      |yarn

**Comment by jozan** [comment]
You can set tabBarVisible as false in navigationOptions for your route.

However I think there is regression or at least some confusion how to hide bottom tab bar from a child stack nav. I try to post repro along with another issue regarding this. :)

**Comment by durdevic** [comment]
I have the same problem, I tried putting other options and they're working correctly except the tabBarVisible. Would be nice if somebody has a solution to this because it's a bit frustrating keeping in mind that it worked in the v1 version.

Just a normal StackNavigator
```
const EventsStack = createStackNavigator({
  EventsScreen: EventsScreen,
  EventDetail: {
    screen: EventDetailScreen,
    navigationOptions: ({ navigation }) => ({
      header: null,
      tabBarVisible: true,
      headerMode: "screen",
      headerTintColor: COLOR.HEADER_TINT,
      headerStyle: {
        backgroundColor: COLOR.HEADER
      }
    }),
  },
  NewEvent: NewEventScreen
}); 
```
And deploying it in the BottomTabNavigator

```
const AppStack = createBottomTabNavigator(
  {
    Events: EventsStack,
    Upcoming: UpcomingStack,
    Profile: ProfileStack
  },
  {
    navigationOptions: ({ navigation }) => ({
      tabBarIcon: ({ focused, tintColor }) => {
        const { routeName } = navigation.state;
        let iconName;
        if (routeName === "Events") {
          // iconName = `ios-information-circle${focused ? '' : '-outline'}`;
          iconName = "home";
        } else if (routeName === "Upcoming") {
          iconName = "check-circle";
        } else if (routeName === "Profile") {
          iconName = "account";
        }
        // You can return any component that you like here! We usually use an
        // icon component from react-native-vector-icons
        return <Icon name={iconName} size={25} color={tintColor} />;
      }
    }),
    initialRouteName: "Events",
    tabBarOptions: {
      activeTintColor: COLOR.ICON,
      labelStyle: {
        fontSize: 12
      },
      style: {
        // backgroundColor: 'blue',
        // height: 0
      }
    },
  }
);
```

**Comment by brentvatne** [comment]
https://github.com/react-navigation/react-navigation-tabs/issues/20

**Comment by Sadac** [comment]
You can try this code to hide  the bottom app bar
```
// Your own stack
const StackHome = createStackNavigator(
  {
    Home: Home,
    CustomHide: CustomHide,
  }
);

// This code let you hide the bottom app bar when "CustomHide" is rendering
StackHome.navigationOptions = ({ navigation }) => {
  let tabBarVisible;
  if (navigation.state.routes.length > 1) {
    navigation.state.routes.map(route => {
      if (route.routeName === "CustomHide") {
        tabBarVisible = false;
      } else {
        tabBarVisible = true;
      }
    });
  }

  return {
    tabBarVisible
  };
};

export default StackHome;
```

Make you sure that in the "CustomHide" component definition you have not a static navigationOptions object wich have a tabBarVisible prop inside

**Comment by mgscreativa** [comment]
Seems it was already added to docs https://reactnavigation.org/docs/en/navigation-options-resolution.html#a-tab-navigator-contains-a-stack-and-you-want-to-hide-the-tab-bar-on-specific-screens

**Comment by jqn** [comment]
@Sadac and @mgscreativa the official solution doesn't work with createMaterialTopTabNavigator. I'm not sure if it's by design or if it's a bug. This used to work on React navigation V 2

**Comment by hilkbahar** [comment]
@jqn You can write code more less.

```javascript
const FeedStack = createStackNavigator({
  FeedHome: FeedScreen,
  Details: DetailsScreen,
}, {
  navigationOptions: ({ navigation }) => ({
    tabBarVisible: navigation.state.index < 1,
  })
});
```

**Comment by mt11i** [comment]
is there anyt= w=

> @jqn You can write code more less.
> 
> ```js
> const FeedStack = createStackNavigator({
>   FeedHome: FeedScreen,
>   Details: DetailsScreen,
> }, {
>   navigationOptions: ({ navigation }) => ({
>     tabBarVisible: navigation.state.index < 1,
>   })
> });
> ```

is there any way to detect that page/screen open from bottom navigation ?

**Comment by dukeeagle** [comment]
Still isn't working for me unless I set the `tabBarVisible: false` for the root navigator. All children are bound by this property no matter where I try to change it.

**Comment by nihp** [comment]
How to hide the tab bars. I have the same screens in **createTabBarBottom** also. All the above solution did not work for me

This is my code snippet for reference

```
const AppNavigator = createBottomTabNavigator({
Home: {
    screen: createStackNavigator({
      Users: {
        screen: Users
      },
      Location: {
        screen: Location
      },
      navigationOptions: {
      headerStyle: {
          backgroundColor: 'white',
          borderWidth:0,
          borderBottomWidth:0
      }
  navigationOptions: {
      headerStyle: {
          backgroundColor: 'white',
          borderWidth:0,
          borderBottomWidth:0
      },
      tabBarIcon: ({focused}) =>  (<Image   source={{uri: IMAGE}} />)
    },
  }Screen1: {
    screen: createStackNavigator({
      UserDetail: {
        screen: UserDetail
      },
      LocalisedPlace: {
        screen: LocalisedPlace
      },
      navigationOptions: {
      headerStyle: {
          backgroundColor: 'white',
          borderWidth:0,
          borderBottomWidth:0
      }
  navigationOptions: {
      headerStyle: {
          backgroundColor: 'white',
          borderWidth:0,
          borderBottomWidth:0
      },
      tabBarIcon: ({focused}) =>  (<Image   source={{uri: IMAGE}} />)
    },
const App = createAppContainer(AppNavigator);

export default class Routes extends Component {
  render() {
    return (
  
        <App onNavigationStateChange={(prevState, currentState) => {
        const currentScreen = getActiveRouteName(currentState);

        if (SCREENS_TO_HIDE_STATUS_BAR.includes(currentScreen))
          StatusBar.setHidden(true);
        else
          StatusBar.setHidden(false);
        }}/>
     );
  }
}
........
```

**Comment by koSiukaS** [comment]
> @jqn You can write code more less.
> 
> ```js
> const FeedStack = createStackNavigator({
>   FeedHome: FeedScreen,
>   Details: DetailsScreen,
> }, {
>   navigationOptions: ({ navigation }) => ({
>     tabBarVisible: navigation.state.index < 1,
>   })
> });
> ```

Same concept, but with a bit more working logic:
`const SurveysStack = createStackNavigator({
    Surveys: SurveysScreen,
    Survey: SurveyScreen
  },
  {
    navigationOptions: ({ navigation }) => ({
        tabBarVisible: navigation.state.routes[navigation.state.index].routeName === 'Survey' ? false : true
      })
});`

**Comment by Mikecoon** [comment]
> tabBarVisible: navigation.state.routes[navigation.state.index].routeName === 'Survey' ? false : true

just `navigation.state.routes[navigation.state.index].routeName === 'Survey'`

**Comment by export-mike** [comment]
I've been banging my head with this problem for some time, I've since written a function which recurses down the routes to the screen on show. Then checks if its a Modal by naming convention then disable the navBar.

to give you an idea our profile stack within a tabBottomBarNavigation is about 6 levels deep where a modal may occur. In which case hide the tabBar.

```js
function getDeepestRoute(route) {
  if (!route.routes) return route.routeName;
  return getDeepestRoute(route.routes[route.index]);
}

ProfileStack.navigationOptions = ({ navigation }) => {
  const deepestRoute = getDeepestRoute(navigation.state);
  return {
    tabBarVisible: !deepestRoute.startsWith('Modal'),
  };
};```

**Comment by LuisRuda** [comment]
https://reactnavigation.org/docs/en/navigation-options-resolution.html#a-tab-navigator-contains-a-stack-and-you-want-to-hide-the-tab-bar-on-specific-screens

**Comment by spanwair** [comment]
after 12 hours of solving:

`
import { createBottomTabNavigator, NavigationTabProp } from 'react-navigation-tabs';
import { NavigationRoute, NavigationParams } from 'react-navigation';
import { CasesNavigator } from './Cases/CasesNavigator';
import { TodoScreen } from './Todo/TodoScreen';

let tabBarVisible: boolean;

const isTabsHidden = (navigation: NavigationTabProp<NavigationRoute<NavigationParams>>) => {
  const route: { path: string } | {} =
    navigation.router?.getPathAndParamsForState(navigation.state) || {};
  tabBarVisible = !('path' in route && route.path === 'Detail');
  return tabBarVisible;
};

export const AppNavigator = createBottomTabNavigator(
  {
    Cases: {
      screen: CasesNavigator,
      navigationOptions: ({navigation}) => ({
        title: 'Cases',
        tabBarVisible: isTabsHidden(navigation),
        tabBarIcon: ({tintColor}) => (
          <View style={styles.bottomButtons}>
            <SvgComp
              color={tintColor}
              icon='caseIcon'
              backgroundColor={colors.white}
            />
          </View>
        )
      })
    },
    Todo: {
      screen: TodoScreen,
      navigationOptions: () => ({
        title: 'To-Do',
        tabBarVisible,
        tabBarIcon: ({tintColor}) => (
          <View style={styles.bottomButtons}>
            <SvgComp
              color={tintColor}
              icon='todoIcon'
            />
          </View>
        )
      }),
    },

.... adtional tabs comme's here`

**Comment by hayyaun** [comment]
Simply set display to 'none'

**Comment by mambalex** [comment]
> Still isn't working for me unless I set the `tabBarVisible: false` for the root navigator. All children are bound by this property no matter where I try to change it.

You need to restart the app. 
`npm start -- -c` does the trick for me

**Comment by lylest** [comment]
SuperNavigator: {
      screen: SuperNavigator,
      navigationOptions: {
        tabBarVisible:false,
        
      },
  
    },

**Comment by odanicola** [comment]
@spanwair this works properly, but i just modified for my own code 
`const isTabHidden = (navigation) => {
  let { routeName } = navigation.state.routes[navigation.state.index]
  
  let tabBarVisible = true
  if (routeName === 'Detail') {
    tabBarVisible = false
  }
  return tabBarVisible
}`

**Comment by odanicola** [comment]
@spanwair this works properly, but i modified for my own

```
const isTabHidden = (navigation) => {
  let { routeName } = navigation.state.routes[navigation.state.index]
  
  let tabBarVisible = true
  if (routeName === 'DetailFaskes') {
    tabBarVisible = false
  }
  return tabBarVisible
}
```

**Comment by MentalisteN7** [comment]
> Seems it was already added to docs https://reactnavigation.org/docs/en/navigation-options-resolution.html#a-tab-navigator-contains-a-stack-and-you-want-to-hide-the-tab-bar-on-specific-screens

This link is not working anymore. Here the new one:
https://reactnavigation.org/docs/hiding-tabbar-in-screens

**Comment by usama-asfar** [comment]
In Reac Navigation v5 you can use getFocusedRouteNameFromRoute to show the  bottom tab for a specific screen, This example demonstrates showing bottom tab only on `AuthScreen`

```js
import { getFocusedRouteNameFromRoute } from '@react-navigation/native';

function AuthenticationStack({ navigation, route }) {
  const routeName = getFocusedRouteNameFromRoute(route) ?? 'Auth';

  useEffect(() => {
    console.log(routeName);
    navigation.setOptions({
      tabBarVisible: routeName === 'Auth',
    });
  }, [navigation, routeName]);

  return (
    <AuthStack.Navigator headerMode="none" initialRouteName="Auth">
      <AuthStack.Screen name="Auth" component={AuthScreen} />
      <AuthStack.Screen name="Login" component={LoginScreen} />
      <AuthStack.Screen name="Register" component={RegsiterScreen} />
    </AuthStack.Navigator>
  );
}

```
