### ISSUE TITLE
createBottomTabNavigator doesn't show tab icon in v2.0.1

### ISSUE THREAD

**Issue by wellyshen** [react-navigation/react-navigation#4215]
### Current Behavior

I wrap 2 routes with `createStackNavigator` inside a `createBottomTabNavigator`, the tab icons won't show in v2.0.1. If I don't wrap the routes with `createStackNavigator`, the tab icons will show.

### Expected Behavior

Tab icon will be show as expect.

### How to reproduce

Bug reproduce is here : https://github.com/wellyshen/react-navigation-bug-reproduce

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | v2.0.1
| react-native     | v0.55.4
| node             | v9.11.1
| yarn      | v1.3.2

**Comment by jozan** [comment]
Can you post a link to a Snack where this issue is reproed? https://snack.expo.io

Thanks :)

**Comment by wellyshen** [comment]
@jozan I already share a reproduced repo. Does that not enough?

**Comment by creativeaura** [comment]
Seems like you are tabBarIcon in the StackNavigator view. You need to move the navigationOptions where you define your TabNavigator.

Please refer to the example in the code

[](https://github.com/react-navigation/react-navigation/blob/master/examples/NavigationPlayground/js/StacksInTabs.js#L97)

I had the same problem where I defined the tabBarIcon in my Home.js but I moved the tabBarIcon code in the file where I initialise the TabNavigator.

**Comment by boubrives** [comment]
Doc specifies following navigationOptions available inside of navigator (I am assuming createStackNavigator like @wellyshen):
https://reactnavigation.org/docs/en/bottom-tab-navigator.html#navigationoptions-for-screens-inside-of-the-navigator
    `tabBarVisible`: a boolean
    `tabBarLabel`: string or component
   ` title`: string or React Element
    `tabBarIcon`: React Element or function that given 
    `tabBarOnPress`: callback with different arguments

There appears  to be an other option which is not mentionned in doc: `header`, which can be set to null to hide the header.

Running some tests, it appears clear that most of the options are not working. The only 2 options which have an effect on my view are `header` and `title` (affecting the header only).
Nothing in bottomTabBar is taken into account.
All this worked find before I upgraded from:

react-native: 0.48.3
react-navigation: 1.0.0-beta.21

to 

react-native: 0.55.4
react-navigation": 2.0.1

following code:
    
```
static navigationOptions = {
          //header: null,
          title: 'MainScreen',
          tabBarLabel: 'inScreen',
          tabBarVisible:false,
          tabBarIcon: <Image
            source={require('../../../images/icon/TabBar/search.png')}
            resizeMode = {Image.resizeMode.contain}
            style={{ height: 30, width: 30, tintColor: 'white'}}
           />  
        }
   ```
will render Title in header (or no header if first option is uncommented).
all the rest just does nothing at all.

Happy to hear any suggestions...

**Comment by henrikland** [comment]
Would be nice to get some clarification as to whether this is a bug or a documentation issue.
It seems to me that it makes more sense to be able to define `tabBarIcon` etc in the screen component, instead of following the example in https://github.com/react-navigation/react-navigation/blob/master/examples/NavigationPlayground/js/StacksInTabs.js#L97 where you define it where you create the `StackNavigator`.

**Comment by zodlanier** [comment]
It seems like i'm not the only one who went through the same issue. In my case, both ways of placing the `tabBarIcon` (screen component or navigator component) do not work out at all. 
Any update regarding this matter is highly appreciated.

**Comment by brentvatne** [comment]
> @jozan I already share a reproduced repo. Does it not enough? What's the purpose of sharing the reproduced on expo?

@wellyshen - because we can run it without taking 5 mins to clone and build

**Comment by brentvatne** [comment]
@henrikland - the behavior is intentional, see https://reactnavigation.org/docs/en/navigation-options-resolution.html for more information

**Comment by donni106** [comment]
I wonder how to solve `tabBarOnPress` for `createBottomTabNavigator` in v2 (currently 2.11.2).

In v1 the following was working:

```
static navigationOptions = ({ navigation }) => {
  const { params } = navigation.state;

  return {
    tabBarOnPress({ scene }) {
      const { route, index } = scene;

      // call the method defined for the clearSearch param
      params.clearSearch();

      ...
    }
  };
};
```

The method `clearSearch()` is set in `componentDidMount()` of the screen inside Stack inside the Tab.

```
// set a custom param on the navigation object to call it in tabBarOnPress
this.props.navigation.setParams({
  clearSearch: this._clearSearch,
});
```

> @brentvatne ...see https://reactnavigation.org/docs/en/navigation-options-resolution.html for more information. basically navigation options for a navigator are only computed from the direct children, so when you nest navigators then you need to set the navigationOptions on the nested navigator itself, not the screens in it

Does this mean, that setting `static navigationOptions` in the screen inside Stack inside the Tab is not working anymore, because the screen is not the direct children of the Tab?

I tried to set the `tabBarOnPress` in the `navigationOptions` right on `createBottomTabNavigator`. But there the `navigation.params` never have my set method to call.

Where can I call my method on Tab click now? Thanks

**Comment by donni106** [comment]
I found out, that my params are nested inside `navigation.state.routes`:

<img width="617" alt="bildschirmfoto 2018-08-14 um 16 36 37" src="https://user-images.githubusercontent.com/1942953/44098602-eac313ba-9fe0-11e8-8db8-3504eee7a0bd.png">

So as a workaround when I set `params = navigation.state.routes[navigation.state.index].params` I can finally call `params.clearSearch()`!
