### ISSUE TITLE
Title is not displayed on navigation bar

### ISSUE THREAD

**Issue by mrarronz** [react-navigation/react-navigation#4224]
### Current Behavior

Cannot show title on navigation bar even when I set the value of title property. The navigation bar is blank without any title.

### Expected Behavior

Title displayed normally

### How to reproduce

1. yarn add react-navigation
2. The version of react-navigation is 2.0.1
3. Create a TabBar based App using react-navigation, part of my code are 
```
Home: {
      screen: HomeScreen,
      navigationOptions: ({navigation}) => ({
        tabBarLabel: 'Home',
        tabBarIcon: ({focused}) => (
          <Icon name={'home'} size={24} color={focused ? AppColor.themeColor : AppColor.inactiveIconColor}/>
        )
      })
    },
```
And in the related screen, I set headerTitle as 'Home'， but nothing showed in the navigation bar.
```
static navigationOptions = ({navigation}) => ({
    headerTitle: 'Home',
  });
```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.0.1
| react-native     | 0.55.3
| node             | v9.5.0
| npm or yarn      | yarn 0.22.0

**Comment by mrarronz** [comment]
After I change the version of react-navigation to 1.5.11, this issue is resolved, title is displayed normally in navigation bar. I think this may be a regression issue when you are updating this library.

**Comment by mrarronz** [comment]
Thank you @kurzyx , I will follow the docs and try again to see if that works

**Comment by livv** [comment]
In  NavigationPlayground Example App have the same question。 ‘Stacks over Tabs’   Title is not displayed on navigation bar

**Comment by Hi-Sen** [comment]
已解决，刚玩 github [，大佬们给点星支持一下,
( https://github.com/Hi-Sen/react-native-navigation2.0.1 )

**Comment by brentvatne** [comment]
https://reactnavigation.org/docs/en/navigation-options-resolution.html
