### ISSUE TITLE
isMounted method deprecated 

### ISSUE THREAD

**Issue by HamidReazaNikoonia** [react-navigation/react-navigation#4227]
i use second edition of React Navigation , and after implement that in my project ( created by react-native CLI ) and project blank , nothing else code  added 

and  i give this warning error in Android

![image](https://user-images.githubusercontent.com/24862548/39986353-a4a8631a-5776-11e8-867b-11ee7fb58906.png)

**Comment by HamidReazaNikoonia** [comment]
nom my question , this matter can be reduce performance , because im see " to prevent memory ..." in warning ??

how can i solve this ??

**Comment by brentvatne** [comment]
this is internal to react-native, nothing we can do from react-navigation

**Comment by sajaddp** [comment]
Hi @brentvatne 
All the responses you have provided for different users in each related issues, they are not persuasive and we can not use the package properly and thoroughly. 

Regarding the performance, it is your personal opinion!

Notably, it is just a feedback to help you :)

**Comment by brentvatne** [comment]
people who thumbs down this seem like very confused individuals. :P
