### ISSUE TITLE
Sequencial animations behave differently between sync & async methods

### ISSUE THREAD

**Issue by ysdanielkim** [react-navigation/react-navigation#4232]
### Current Behavior

When running two navigation actions back to back (e.g. `.back() && .navigate()`) the animation behaves differently depending on whether call is from async or sync methods.

When run from a _sync_ method, the two animations run simultaneously. When run from an _async_ method, the two animations run sequentially. Please see attached animation.

Sync method runs animations simultaneously:
<http://giphy.com/gifs/9Y01ONqR2RHfqy9UEG>

Async method runs animations sequentially
<https://giphy.com/gifs/X7ZaN9aMBPc6KCbdGc>

### Expected Behavior

Whether or not the navigation actions are run from an async or a sync method, the behavior should be the same.

For my usecase I need the two animations to happen simultaneously.

### How to reproduce
Async Code <https://snack.expo.io/SkjjNEDAG>
Sync Code <https://snack.expo.io/HJBVS4w0z>

Note: Only difference between the two snippets is the `setTimeout` in line 30

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.0.1
| react-native     | 0.55.4
| node             | 8.10.0
| npm or yarn      | yarn

**Comment by brentvatne** [comment]
I think this is a result of `setState` sometimes behaving asynchronously but honestly I'm not totally clear on why this happens
