### ISSUE TITLE
Toggling a drawer causes Maximum update depth exceeded error

### ISSUE THREAD

**Issue by gogumai** [react-navigation/react-navigation#4233]
Hey! I have the following navigators structure:

- SwitchNavigator ---> (used for auth, like the example in the docs )
  - StackNavigator ---> (provides an app top level header with a button to toggle the drawer)
    - DrawerNavigator ---> (main app drawer with multiple StackNavigator as children)
      - (1..n) StackNavigator(s) ---> (app screens)

### Current Behavior

Happening only in iOS, Android works fine.

If I tap the toggle button quickly, in such a way that the drawer didn't finished the toggle animation, the app crashes with the following error:

![simulator screen shot - iphone 6 - 2018-05-14 at 12 18 09](https://user-images.githubusercontent.com/16405232/40006677-5f9caaec-5771-11e8-8059-9baa5025a826.png)

### Expected Behavior
Pressing the button (no matter the tapping speed) should open and close the drawer.

### How to reproduce

Expo repro here: https://snack.expo.io/HJRi3WP0M

Just tap the button fast and repeatedly

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^2.0.1
| react-native     | 0.55.4
| node             | v9.1.0
| npm or yarn      | yarn 1.5.1

**Comment by wouterNL** [comment]
Same issue here.

**Comment by Ronnyrr** [comment]
Same issue. Happens sometimes (nice, I know) while clicking an item in the drawer.

**Comment by gethighruletheworld** [comment]
Yea this is becoming a deal breaking issue

**Comment by Taglohner** [comment]
Facing same issue here

**Comment by mikeynova** [comment]
Likewise. Had to revert to an older working version.

**Comment by ericvicenti** [comment]
Ok, I see this issue when pressing the toggle drawer button quickly. I'll get this fixed ASAP

**Comment by ericvicenti** [comment]
Yeah there is a bug in the DrawerView component. Workaround is here, although somebody should actually go fix it within `react-native-drawer-layout-polyfill`...

https://github.com/react-navigation/react-navigation/pull/4392
