### ISSUE TITLE
createBottomNavigation did not switch animations,like swipeEnabled,animationEnabled

### ISSUE THREAD

**Issue by chaoyue1217** [react-navigation/react-navigation#4236]
# How to add a toggle animation to createBottomNavigation????

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.0.1
| react-native     |0.55.4
| node             |
| npm or yarn      |

**Comment by nathvarun** [comment]
From the official blog post : https://reactnavigation.org/blog/

> Previously, TabNavigator would render a navigation bar on the top of the screen on Android and the bottom on iOS. We’ve now pulled these navigators apart, so you can use createBottomTabNavigatorand createMaterialTopTabNavigator explicitly depending on what you need. You can use createTabNavigator to have the same behavior as before, but it will be removed in 3.0.
It is worth noting additionally that createBottomTabNavigator is different from the bottom tab navigator that is available through TabNavigator in that it does not support animationEnabled or swipeEnabled properties.

**Comment by nathvarun** [comment]
@brentvatne has there been a change?

**Comment by geordidearns** [comment]
@brentvatne Hey! 

Reading on feedback on multiple issues, and you are mentioning these features coming back into the fold (another +1 if you can make it happen 🥇 ) - But **when are you looking to version to 3.0**? 

I saw you are at 2.4.X and wondered if it was worth using the older one until the next Version bump, as it does make the app much nicer. Thanks, Geordi

**Comment by brentvatne** [comment]
we do not plan on adding these back, you're welcome to discuss further on https://github.com/react-navigation/react-navigation-tabs if you disagree with the decision :)
