### ISSUE TITLE
custom animation per screen

### ISSUE THREAD

**Issue by Bonobomagno** [react-navigation/react-navigation#4238]
### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2
| react-native     | expo 27 
| node             | 9.x
| npm or yarn      | yarn 1.6

there is way to use transitionConfig for only specific pages?
I have a page (a search one) that i want to give it no animation, leaving  the rest as is..
any solution?

**Comment by Bonobomagno** [comment]
My actual solution is:
switchNavigator with privateRoute and publicRoute.

privateRoute is a switchNavigator with MyStackNavigar and SearchScreen.
Now calling SearchScreen don't call the animation.

Instead using transitionConfig has effects on every page of that navigator tree level.

**Comment by Tomatoo** [comment]
you can use transtionConfig.

```
transitionConfig: (prop) => {
    const routeName = prop.scene.route.routeName;

    if (routeName === 'Login') {
      // ...
    } else {
     // ...
    }
  },
```

**Comment by Bonobomagno** [comment]
you say to use transitionConfig on parent route?
I don't like it a lot because you have to mix them all, but thanks

**Comment by brentvatne** [comment]
you can discuss here https://github.com/react-navigation/rfcs/issues/10

**Comment by gasolin** [comment]
can get currentScene/prevScene through `navigation` params.

ex:
```
import { fromRight } from 'react-navigation-transitions'

const handleTransition = ({ scene, scenes }) => {
  const currentScene = scene.route.routeName;
  const prevScene = scenes[scenes.length - 2]; // not used in this example
  if (currentScene === 'ScreenA') {
    return fromRight();
  }
  return {} // return to the default
}

const Stacks = createStackNavigator({
...
}, {
  transitionConfig: nav => handleTransition(nav),
})
```
