### ISSUE TITLE
How to change language label tabbar ?

### ISSUE THREAD

**Issue by safeimuslim** [react-navigation/react-navigation#4239]
How to change language label tabbar ? because my app is multi language.
![screen shot 2018-05-15 at 16 51 05](https://user-images.githubusercontent.com/12455939/40049933-40291246-5860-11e8-940b-2dcd08caa734.png)

**Comment by brentvatne** [comment]
hi there! this is a question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.

**Comment by jinzunyue** [comment]
"react-navigation": "^2.17.0",
I had this problem,but i solved this by the flowering code.
`const profileAction = NavigationActions.setParams({
      params: { title: "After change" },
      key: "ProfileScreen",
    });
    this.props.navigation.dispatch(profileAction);`
[Offericial Doc](https://reactnavigation.org/docs/zh-Hans/navigation-actions.html)
