### ISSUE TITLE
Go back not working

### ISSUE THREAD

**Issue by pekubu** [react-navigation/react-navigation#4240]
I performed the same as this example to move to Screen2.
`NavigationService.navigate('Screen2', { id: 1 });`
https://reactnavigation.org/docs/en/navigating-without-navigation-prop.html
It works.  But when I use at `this.props.navigation.goBack()` or `this.props.navigation.goBack(null)` or `this.props.navigation.goBack('Screen1')` on Screen2, no reaction occurred.
Tell me how to do it. Thank you

### Your Environment
| software         | version
| ---------------- | -------
| react-navigation | 2.0.1
| react-native     | 0.55.4

**Comment by MrLoh** [comment]
Please provide more code where and how are you calling `goBack`? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by pekubu** [comment]
my demo
[testNavigation.zip](https://github.com/react-navigation/react-navigation/files/2013458/testNavigation.zip)

**Comment by MrLoh** [comment]
I moved this to a snack: https://snack.expo.io/Sy44RZs0M

Why are you using a drawer navigator and why are you rendering it inside the StackNavigator? I don't have much experience with drawers, but from my understanding they are usually used as a top level navigator and they work more like a tab navigator in that they don't actually create a stack of views that you slide back on. Could you try to specify, what kind of navigation structure you want to achieve?

**Comment by pekubu** [comment]
If I do not use StackNavigator, how can I change it? I just want to switch from Screen1 -> Screen 2 -> Screen 3 -> Screen 2 (goBack) -> Screen 1 (goBack)

**Comment by MrLoh** [comment]
What are you using the drawer for. Normally you’d put your three screens in a stack than you can go back easily. If you have a drawer, you usually have stacks inside drawers, not a drawer in stacks. Drawers simply don’t support the back behavior you are looking for. 

Maybe this post helps: 
https://stackoverflow.com/questions/47094753/goback-always-taking-to-home-first-screen-in-react-navigation

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by pekubu** [comment]
thank you so much.
