### ISSUE TITLE
isMounted(...) is deprecated in plain JavaScript React classes

### ISSUE THREAD

**Issue by zuijiaoluo** [react-navigation/react-navigation#4241]
### Current Behavior

- What code are you running and what is happening?
I use react-navigation tab, when I set "navigationOptions: {header: null}", the warning disappeared, 
On the contrary, it has a warning.When warning occurs, my memory usage is also rising. When there is no warning, the memory will not rise, and the rising memory will not be recovered.
- Include a screenshot if it makes sense.

### Expected Behavior

- What do you expect should be happening?
I hope that no matter whether I set "header", there will be no memory leak.
- Include a screenshot if it makes sense.

### How to reproduce

Frequent switching of TabNavigator

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  1.5.11
| react-native     | 0.55.3
| node             | 8.9.1
| npm or yarn      | npm: 5.6.0  yarn: 1.3.2

**Comment by thiso** [comment]
YellowBox.ignoreWarnings(['Warning: isMounted(...) is deprecated', 'Module RCTImageLoader']);

**Comment by wcandillon** [comment]
@zuijiaoluo @thiso That doesn't sound like a satisfactory solution. Maybe there are packages that are using `isMounted` that should be updated?

**Comment by zuijiaoluo** [comment]
When I tried it, memory was not going to grow in development, but when I was in the official version, memory was still growing taller.

**Comment by zuijiaoluo** [comment]
@wcandillon I've done troubleshooting. I only have warnings when I switch routings. I've read other issues. Others may be react-native itself. I'm not sure if it's caused this, but I set it up. "navigationOptions: {header: null}", the warning disappears

**Comment by zuijiaoluo** [comment]
This memory overflow problem is very serious in my presence here. My memory is now occupying 200M, and it is still growing.

**Comment by zuijiaoluo** [comment]
https://github.com/facebook/react-native/issues/18868   This seems to be fixing the warning, but I'm not sure if my memory increase can be solved.

**Comment by zuijiaoluo** [comment]
OK, I'll close this issue for the time being. Hopefully, my memory problems will be solved together. Thank you for your support.
