### ISSUE TITLE
closeDrawer not available in navigation within Drawer component but DrawerActions.closeDrawer works

### ISSUE THREAD

**Issue by wcandillon** [react-navigation/react-navigation#4242]
### Current Behavior

- In a drawer navigator, following methods are available:
  * this.props.navigation.openDrawer();
  * this.props.navigation.closeDrawer();
  * this.props.navigation.toggleDrawer();

However these 3 methods are not available within the DrawerComponent. But if I use:
this.props.navigation.dispatch(DrawerActions.closeDrawer()) instead, things work smoothly.

### Expected Behavior

- The following 3 methods should be available within the Drawer component:
- In a drawer navigator, following methods are available:
  * this.props.navigation.openDrawer();
  * this.props.navigation.closeDrawer();
  * this.props.navigation.toggleDrawer();

### How to reproduce

Build a simple drawer component with one screen. Open the drawer from the screen component and try to close the drawer from the drawer component.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.0.1

**Comment by sonaye** [comment]
Same here.

**Comment by Ronnyrr** [comment]
Seems duplicate to my issue; https://github.com/react-navigation/react-navigation/issues/4174

Do you have some example code? 
My issue happend because I wasn't using the Drawer correctly. Maybe I can help you point it out?

**Comment by wcandillon** [comment]
@Ronnyrr Thank you for pointing me to the relevant thread, really appreciate it.

**Comment by kaitlynbrown** [comment]
Why is this closed? It isn't fixed. There's absolutely no reason that these methods shouldn't be available inside of a custom Drawer component, *especially* given the fact that you have to explicitly close the drawer after navigating from within the Drawer Component.
