### ISSUE TITLE
Cannot hide BottomTabNavigator to show full screen modal (v2)

### ISSUE THREAD

**Issue by scriptum** [react-navigation/react-navigation#4243]
New version ignores tabBarVisible option.

| software         | version
| ---------------- | -------
| react-navigation |2.0.1

Snack example:

https://snack.expo.io/Bk0xkFuCf

This example works with 1.5.4.

**Comment by jeffreyffs** [comment]
Did you read the breaking changes guide for v2? Only direct children of the TabBarNavigator can show/hide the tab bar. You could fix your issue by dynamically checking if your modal screen is up in the HomeStack navigation options:

`HomeStack.navigationOptions = ({navigation}) => {
  return {
    tabBarVisible: navigation.state.index === 0,
  }  
}`

Or check if a specific route is being shown, etc.

**Comment by minooo** [comment]
Thank you master, it works!

**Comment by JayricMok** [comment]
well this is what I learned from last version, but in v2 , you can go to `node_modules/react-navigation-tabs/dist/navigators/createBottomTabNavigator.js`

1. in `createBottomTabNavigator.js` add `showbar:true` to the `state`
2. in `componentWillReceiveProps(nextProps)` add code below : 

    `const oldState = this.props.navigation.state;`
    `const oldRoute = oldState.routes[oldState.index];`
   ` const oldParams = oldRoute.params;`
    `const wasVisible = !oldParams || oldParams.visible;`

    `const newState = nextProps.navigation.state;`
    `const newRoute = newState.routes[newState.index];`
    `const newParams = newRoute.params;`
    `const isVisible = !newParams || newParams.visible;`

   ` if (wasVisible && !isVisible) {`
    `  this.setState({showbar:false});`
    `} else if (isVisible && !wasVisible) {`
    `  this.setState({showbar:true});`
   ` }`
 
3. in `render()` replace `{this._renderTabBar()}` to `{this.state.showbar ? this._renderTabBar() : false}`
4. then you can call `this.props.navigation.setParams({visible: false});` to hide the tabbar or `true` to show it again

**Comment by brentvatne** [comment]
i'd re-order the modal navigator so that you have it at the root of the app like in this example https://reactnavigation.org/docs/en/modal.html

**Comment by renato-bvdash** [comment]
@JayricMok's code is deprecated now. Does anyone know of an updated version of it? I don't quite understand enough of the lifecycle to be able to mutate it.
