### ISSUE TITLE
didFocus events not riggered on initial Tab Mount when integrating with Redux

### ISSUE THREAD

**Issue by MrLoh** [react-navigation/react-navigation#4244]
### Current Behavior

As described in #4087 there was a problem with `didFocus` events not being fired in Tab Navigators on initial render of the route. The issue has been fixed, but it persists when integrating the navigator with redux. 

### Expected Behavior

The redux integration shouldn't break `didFocus` events. 

### How to reproduce

The following expo snack reproduces the issue. You can switch the `ReduxNavigator` and `Navigator` export in the last line to see how integration with redux break the functionality. 

https://snack.expo.io/@mrloh/tabnavigator-with-redux-didfocus

### Your Environment

react-navigation: `v2.0.1`
expo: `v27.0.0`
redux: `v4.0.0` / `v3.7.2`

**Comment by Ashoat** [comment]
Are you using `initializeListeners`?

**Comment by Ashoat** [comment]
Oh, the issue you're encountering is that you expect `addListener` to fire for `didFocus` events, but it only fires for `action` events. See [here](https://github.com/react-navigation/react-navigation/blob/master/src/createNavigationContainer.js#L367-L369). This logic is duplicated [here](https://github.com/react-navigation/react-navigation-redux-helpers/blob/master/src/middleware.js#L58-L60). More context [here](https://github.com/react-navigation/react-navigation-redux-helpers/issues/25) and [here](https://github.com/react-navigation/react-navigation-redux-helpers/issues/26).

If you want to catch these events you can always fork `react-navigation-redux-helpers` and remove the linked lines. Keep in mind that this behavior isn't supported by `react-navigation`, though, and you might see strange behavior.

**Comment by MrLoh** [comment]
@Ashoat as you can see in my example it does work as expected in react-navigation without redux though, so I think there is an issue with the redux integration.

**Comment by Ashoat** [comment]
This is happening because the Redux middleware used for triggering the listeners fires before `react-redux`'s `connect` delivers the updated state. In contrast, `createNavigationContainer` is explicitly set up to propagate the updated state before triggering any listeners.

**Comment by Ashoat** [comment]
Okay, I have a solution. `react-navigation-redux-helpers@1.1.1` introduces a new export called `createDidUpdateCallback`. Refer to the [docs](https://github.com/react-navigation/react-navigation-redux-helpers) for how it's used.

Let me know if that doesn't fix your issue.

**Comment by MrLoh** [comment]
@Ashoat thanks a lot for the quick fix. There’s still a misspelling in the README, it says `createNavigationReducer` in the description under the correct heading. 

However I can’t get it to work yet. Maybe my setup isn’t correct. I updated the snack example, could you have a look what I missed. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Ashoat** [comment]
Typo fixed. Make sure you don't use `createNavigationPropConstructor`, since that won't be available until a PR on this repo is merged.
