### ISSUE TITLE
tabBarOnPress not working on MaterialTopTabNavigator

### ISSUE THREAD

**Issue by brunoandradebr** [react-navigation/react-navigation#4246]
tabBarOnPress is not working on MaterialTopTabNavigator, only works when using deprecated TabNavigator

```
navigationOptions: (navigation) => ({
    tabBarOnPress: (scene, jumpToIndex) => {
        alert('test')
    }
})
```

**Comment by martinezguillaume** [comment]
`tabBarOnPress` is just giving me `navigation` object, not `previousScene`, `scene`, or `jumpToIndex`

**Comment by brunoandradebr** [comment]
I didn't check params yet, just tested alert callback on old TabNavigator and new MaterialTopTabNavigator. Only works on old version.

**Comment by brentvatne** [comment]
it's on implemented there. cc @satya164

**Comment by satya164** [comment]
the PR was merged. need to do a release :)

**Comment by brentvatne** [comment]
it's released in 2.0.3

**Comment by serranoarevalo** [comment]
This is still happening on version 2.5.5.

https://snack.expo.io/r1gNgp4fm

Tap the + sign and there is a console log of the arguments passed to onTabBarPress, you will see it's only the navigation object.

**Comment by dNitro** [comment]
@satya164 , Tnx for implementing this feature for MaterialTopTabNavigator, but we also need `tabBarOnPress` callback to get called when **swipping*. Already clicking a tab with a tabBarOnPress callback on it, call this function but if we swipe to that tab tabBarOnPress does not get called.

**Comment by satya164** [comment]
As the name implies, `tabBarOnPress` is supposed to be called on tab bar press. If you need to get notified of focus, use focus events: https://reactnavigation.org/docs/en/navigation-prop.html#addlistener-subscribe-to-updates-to-navigation-lifecycle

**Comment by ganesh-trabacus** [comment]
it's not working as of now in V3.x+, could you please give solution?
