### ISSUE TITLE
onTransitionStart and onTransitionEnd callbacks not firing

### ISSUE THREAD

**Issue by stigi** [react-navigation/react-navigation#4252]
Hi, I'm currently in the process of upgrading one of our projects to version 2.0.1.

I tried to get the `onTransitionEnd` callback working on a stack, but it simply does nothing.

```
createStackNavigator({
  Dummy: { screen: Dummy }
},{
  onTransitionEnd: (props) => { Alert.alert('Just did it!'); }
})
```

Here's a snack with my full example: https://snack.expo.io/@stigi/ontransitionstart-react-navigation-2.0.1

Here's the same example working in an older version https://snack.expo.io/@stigi/ontransitionend-react-navigation-1.5.4

The [documentation](https://reactnavigation.org/docs/en/stack-navigator.html) for v2 still mentions `onTransitionStart` and `End` so I'm positive it didn't go away.

---

### Current Behavior

Using the code from above I push the same Dummy screen onto the stack.  
The `onTransitionEnd` callback doesn't get triggered and no Alert is shown.

### Expected Behavior

Using the code from above I push the same Dummy screen onto the stack.  
The `onTransitionEnd` callback gets triggered and an Alert is shown.

### How to reproduce

See my snack. There's a push button. Push it :)

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.0.1
| react-native | 0.54.4
| node             | 9.4.0
| yarn      | 1.6.0

**Comment by MrLoh** [comment]
You can always add a listener to didFocus events, maybe that’s at least a workaround. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by allmaxgit** [comment]
@stigi Now you can pass it in component
```
<Navigator onTransitionStart={this.onTransitionStart} />
```

**Comment by stigi** [comment]
I think it's actually a bug and I attempted a fix in #4255

**Comment by Bardiamist** [comment]
@stigi Ni, [see this comment](https://github.com/react-navigation/react-navigation/pull/4100#issuecomment-389798839)

**Comment by stigi** [comment]
@Bardiamist Then I believe the documentation to be wrong, as it states that `onTransitionStart` and `onTransitionEnd` both can be passed directly to `createStackNavigator`: https://reactnavigation.org/docs/en/stack-navigator.html

**Comment by brentvatne** [comment]
hi there! this should be fixed. if you find that this is still a bug can you create a new issue that reproduces the bug on https://snack.expo.io? thanks!

**Comment by brentvatne** [comment]
snack from original post updated to react-navigation@2.3.1: https://snack.expo.io/SyMFxLx-Q
