### ISSUE TITLE
How to Navigate to a screen outside a Tab

### ISSUE THREAD

**Issue by mopilo** [react-navigation/react-navigation#4253]
How do i go o a screen that isn't part of my tab navigator

**Comment by MrLoh** [comment]
Please add a code example. Generally just use `navigation.navigate(routeName)` if you want to push a stack, but you have provided no information as to what your setup is and what you mean with outside your tab. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by qingma1** [comment]
just like this: 
this.props.navigation.navigate('Mine',{info:'someParams'});

**Comment by mopilo** [comment]
i was able to solve this thanks to @qingma1, the reason why i could navigate to the intended screen was because i didnt add the screen to the stacknavigator.

**Comment by mopilo** [comment]
What if i want my tab to be persistent across all screens, how to i go about it?

![white-3-tab](https://user-images.githubusercontent.com/7842458/40167003-cfd25710-59b7-11e8-9058-3c630eace6c4.gif)

**Comment by brentvatne** [comment]
hi there! this is a question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.
