### ISSUE TITLE
Lazy off with a loader page?

### ISSUE THREAD

**Issue by Bonobomagno** [react-navigation/react-navigation#4254]
### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |2
| react-native     | 55
| node             | 9.x
| npm or yarn      |1.6

How can i do this?
I found that you are using lazy on by default on createBottomTabNavigator,
but lazy is no more settable now.
I want to try showing a loader before app is ready, so all navigation will be full.any idea on how to do that now?

**Comment by tamdesktop** [comment]
+1 on this issue.
I have to use createTabNavigator and ignore warning message

**Comment by brentvatne** [comment]
you can submit a pull request to https://github.com/react-navigation/react-navigation-tabs to add a lazy option if you like. added an issue for it: https://github.com/react-navigation/react-navigation-tabs/issues/23
