### ISSUE TITLE
Cannot read property 'params' of null

### ISSUE THREAD

**Issue by tindery** [react-navigation/react-navigation#4263]
Hello, i've updated to react-navigation 2.0.1 and i've encountered following error when nesting navigations: 

![image](https://user-images.githubusercontent.com/31622405/40180578-76d6303e-59e7-11e8-9ba3-ac16427cf81d.png)

to reproduce:

```
export default class App extends React.Component {
  render() {
    return (
      <View style={styles.container}>
        <StackNav />
      </View>
    );
  }
}

const DrawerNav = createDrawerNavigator({
  Main: Home, 
  Page: Page
});

const StackNav = createStackNavigator({
  Main: DrawerNav,
  Stack: Stack
});
```

Is this a bug or was there a change to how nesting works?

| react-navigation | 2.0.1
| react-native     | 0.55.2

**Comment by mahshadalishahi** [comment]
+1

**Comment by brentvatne** [comment]
the example you provided is not runnable. please re-create the issue with a runnable example (link to github repo works, or full code of a single file that can repro it so I can copy and paste it into a local project)
