### ISSUE TITLE
DefinitelyTyped of 2.0

### ISSUE THREAD

**Issue by PMExtra** [react-navigation/react-navigation#4265]
Is version 2.0 of [`@types/react-navigation`](https://www.npmjs.com/package/@types/react-navigation) in progress?

**Comment by erandagan** [comment]
You might want to have a look at https://github.com/react-navigation/react-navigation/pull/4075 and these related PRs & RFC
* https://github.com/react-navigation/react-navigation/pull/4101
* https://github.com/react-navigation/react-navigation/pull/4096
* https://github.com/react-navigation/rfcs/issues/34

**Comment by brentvatne** [comment]
we don't maintain typescript types at the moment, it's built by folks outside of react-navigation team, so you will need to ping them
