### ISSUE TITLE
navigation.navigate('DrawerToggle') it not toggling the drawer in version 2.0.1

### ISSUE THREAD

**Issue by eranbaroz** [react-navigation/react-navigation#4266]
In version 2.0.1 this code
```
 StackNavigator({
    drawerStack
    }, {
    navigationOptions: ({ navigation }) => ({
        headerLeft: <Text style={{ fontSize: 28, marginLeft: 20 }} onPress={() => {
            console.log('press');
            navigation.navigate('DrawerToggle');
        }}>&#9776;</Text>,
    })
})
```

is not toggling the drawer any more as it used to in version 1.4.0

### Current Behavior
Only the log is printed when pressing the text.

### Expected Behavior

The drawer open/close

### How to reproduce

if needed I'll supply more code. Maybe consider update the documentation and split it into version 1 and version 2. 

### Your Environment

macOS Hight Sierra 10.13.4 

| software         | version
| ---------------- | -------
| react-navigation | 2.0.1
| react-native     | 0.55.3
| node             | 8.11.1
| npm or yarn      | yarn 1.6.0

**Comment by 1987cr** [comment]
Documentation for v1 is located [here](https://v1.reactnavigation.org/docs/getting-started.html).

**Comment by FranciscoMSM** [comment]
Hi! Are you doing redux integration? If yes you have to dispatch from navigation prop in v2

**Comment by vonovak** [comment]
navigation.navigate('DrawerToggle') was removed in v2. Please refer to the documentation or release notes on how to do this in v2 https://reactnavigation.org/docs/en/drawer-based-navigation.html

**Comment by eranbaroz** [comment]
@FranciscoMSM - Hi, I'm not using redux.
@vonovak - I know that navigate('DrawerToggle') was removed. How ever the documentation is not providing an explanation on how do it in the new version when using  react element (as appear in my example) for the headerLeft property settings.
I would love if you could point me to an working example if there is any out there in case I missed it.
Thanks.

**Comment by vonovak** [comment]
@eranbaroz if the documentation did not help, then please open a new issue and provide a minimal runnable repro. Thanks.

**Comment by eranbaroz** [comment]
Hi @vonovak I created this issue: [https://github.com/react-navigation/react-navigation/issues/4285](https://github.com/react-navigation/react-navigation/issues/4285) with all the details and runnable snack.
Thanks.

**Comment by CaptainN** [comment]
The link in the above comment does not resolve to the v2 documentation. Here is the correct link:
https://reactnavigation.org/docs/en/2.x/drawer-based-navigation.html

To answer the question directly, you have to change this:

`this.props.navigation.navigate("DrawerToggle");`

to this:

`this.props.navigation.openDrawer();`
