### ISSUE TITLE
Conflict with SafeAreaView 

### ISSUE THREAD

**Issue by Bonobomagno** [react-navigation/react-navigation#4268]
using 
`import {  SafeAreaView } from 'react-native'`
```
       <SafeAreaView style={styles.applicationView}>
        <AppNavigation />
      </SafeAreaView>
```
bring conflict on IOS 11+ on header height calculation of the title header.
How is the rfc way to handle this classic situation?

**Comment by Bonobomagno** [comment]
They changed the docs, thanks! I will try

**Comment by Bonobomagno** [comment]
Checked but it is incomplete.
Own header component not only use own safeAreaView, but also use own top padding for avoiding overlap to statusbar. A bit confusing having so much custom condition.

**Comment by brentvatne** [comment]
i agree it's not ideal, discussion here https://github.com/react-navigation/rfcs/issues/13

**Comment by krozett** [comment]
The documentation is wrong. This very example (https://reactnavigation.org/docs/en/handling-iphonex.html) implies you are meant to wrap your whole App in it.

I was pulling my hair out for hours trying to figure out why I was getting double the space in the header and footer.

If you are struggling like I was:
*do NOT use SafeAreaView with react-navigation*

**Comment by brentvatne** [comment]
cc @vonovak maybe we should clarify the example provided there and be extra clear that you shouldn't wrap the whole app in it
