### ISSUE TITLE
How can I pass data across screens using props.navigation, and how to set an initial default value?

### ISSUE THREAD

**Issue by sopdock** [react-navigation/react-navigation#4269]
Hello, I'm new to react-native. I was following the tutorials and I read that `this.props.navigation` is passed to all screens automatically. I have a SwitchNavigator() after following the Auth flow tutorial. When the user 'logs-in' like in the Tutorial, I switch to a TabNavigator. The TabNavigator has several StackNavigators, and each StackNavigator has stacked screens. I have one screen where the user does a search and it produces an array of results, and I want to pass the results to two more screens if the user navigates there. 

In the first screen, this is how I set the navigation props, after a user has done a search:
```
    doSearch = (e) => {
        let results = searchData(this.state.userInput);
        this.props.navigation.setParams({ searchResults: results });
    }
```

Then in another screen, I want to use the results:

```
    render() {
        return (
            <Text>{this.props.navigation.state.params.searchResults[0].name}</Text>
        )
    }
```

However, I see `TypeError: undefined is not an object (evaluating 'this.props.navigation.state.params.searchResults')`

I don't think I have done this correctly. Can someone help with an example of passing data across different screens? Also, I didn't see this mentioned in the tutorial, but is there a proper way to set a default value when the application first boots up for the props.navigation? I'd like to set my `searchResults = []` initially.

Here is a really simple demo:

```
import React from 'react';
import { Button, Text, View } from 'react-native';
import {
  createBottomTabNavigator,
  createStackNavigator,
} from 'react-navigation';


class HomeScreen extends React.Component {
  doIt = () => {
    this.props.navigation.setParams({results: ['one', 'two']});       // <------- set data when user clicks button.
  }

  render() {
    return (
      <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
        {/* other code from before here */}
        <Button
          title="Set Results"
          onPress={this.doIt}
        />
      </View>
    );
  }
}

class SettingsScreen extends React.Component {
  render() {

    console.log(this.props.navigation);      // <------- console out when user clicks on this tab

    return (
      <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
        <Text>Settings</Text>
      </View>
    );
  }
}

const HomeStack = createStackNavigator({
  Home: HomeScreen,
});

const SettingsStack = createStackNavigator({
  Settings: SettingsScreen,
});

export default createBottomTabNavigator(
  {
    Home: HomeStack,
    Settings: SettingsStack,
  },
  {
  }
);
```

**Comment by Bonobomagno** [comment]
If you want to share data, redux is a better solution.
Instead if you just want to pass data from the parent stack, just  pass them with `this.props.navigation.navigate('page_key', { data_Object})`
On the opened page you will have access to data_Object through `this.props.navigation.state.params.data_Object_keys`

so for egs 
`this.props.navigation.navigate('page_key', { results: [0,1,2,4,8]})`

`const results = this.props.navigation.state.params.results`

**Comment by sopdock** [comment]
Thanks for the suggestion. Is there a way to pass data without using Redux though? 

The example you gave is used only if I directly call the other screen from the current screen. But in a TabNavigator, how do I set the results in one screen in the first tab, and give it to the other screen in the second tab? They don't call each directly; TabNavigator is handling the changes across the screens in each tab.

**Comment by Bonobomagno** [comment]
Use redux or other data centric library. 
Or create your own with context api. React is one way data binded.

**Comment by sopdock** [comment]
@Bonobomagno I can take a look at Redux, but I've never used it before. Could you give an example using the sample demo code I have?

**Comment by Bonobomagno** [comment]
you can find a lot of demo around. redux website is fine, there are no difference from redux with react or with react-native

**Comment by brentvatne** [comment]
hi there! this is a question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.
