### ISSUE TITLE
ReduxExample crash with DrawerNavigation

### ISSUE THREAD

**Issue by thienhaole92** [react-navigation/react-navigation#4270]
I download ReduxExample and changed some things in AppNavigator.js to the code below
`export const AppNavigator = DrawerNavigator({`
 ` Login: { screen: LoginScreen },`
  `Main: { screen: MainScreen },`
 ` Profile: { screen: ProfileScreen },`
`});`
and try to run the example everythings seem OK. If I open and close drawer many times the app has crashed and show log:

`Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.`

I tried to debug then I saw action `Navigation/OPEN_DRAWER` or  `Navigation/CLOSE_DRAWER `auto call many times

**Comment by erandagan** [comment]
Same as https://github.com/react-navigation/react-navigation/issues/4233

**Comment by ereenyessamhanna** [comment]
any updates ?
