### ISSUE TITLE
How to load from AsyncStorage on a tabBarOnPress(), and then pass to a screen?

### ISSUE THREAD

**Issue by sopdock** [react-navigation/react-navigation#4272]
I have a setup like this:
```
TabNavigator
   StackNavigatorX
       ScreenA
       ScreenB
    StackNavigatorY
       ScreenC
       ScreenD
```

Using `tabBarOnPress()` on the TabNavigator, how can I load data from `AsyncStorage`, and then pass it to their respective screens? ie, I press the Tab for `StackNavigatorY` and it loads from AsyncStorage and then sends the data to ScreenC or ScreenD.

I have seen some work-arounds using `componentWillMount()` or `screenprops`, but both these are being deprecated, so I would not like to use them.

Is there a way to do this without Redux, using just react-native and react-navigation?

**Comment by vonovak** [comment]
Hi there! The issue tracker is reserved for bugs only, while this is a usage question better suited for stackoverflow. Please ask your question there. Thanks!
