### ISSUE TITLE
Call parent navigator and change its “cardStyle” and “navigationOption” 's attributes

### ISSUE THREAD

**Issue by devMozo** [react-navigation/react-navigation#4274]
## The issue tracker is reserved for bug reports only.

I have a hidden TabNavigator, that is inside a StackNavigator, and I want to animate the header of this last like the headers of the most common apps that when the screen scrolls down then the header goes up until disappear.

Now, I'm inside the PostFriend's Screen that has a ScrollView with a lot of data, therefore, I want to access to the HomeStack, when I scroll on this screen, to change the attributes of "cardStyle" and "navigationOption" to change its values and can make the animation.

---

### Current Behavior

My navigator.js

```
const HomeTab = createMaterialTopTabNavigator({
  //Home: Home,
  PostFriends: PostFriends,
  // Another screens
}, {
  tabBarComponent: null,
  mode: 'hide',
  navigationOptions: {
    visible: false // Now I don't want to see this tab, but I'll need it in the future
  }
});

const HomeStack = createStackNavigator({
  HomeTab: HomeTab,
  // Another screens
}, {
  headerMode: 'float',
  cardStyle: {
    top: -20 // This is the value that I want to change it to make the animation
  }
});
```
My PostFriend's Screen
```
export default class PostFriends extends React.Component {
    static navigationOptions = ({ navigation }) => {
        const { params } = navigation.state;
       // I tried a lot of black magic to 
       // connect with the HomeStack
    }; 
    /**
     * Constructor of the component
     * @param  {[type]} props [description]
     * @return {[type]}       [description]
     */
    constructor(props) {
        super(props);
        // Some attributes
    }

    render() {
        return (
              <ScrollView>
                  // A lot of data
              </ScrollView>
        );
    }
}
```

### Expected Behavior

The header of the StackNavigator achives to hide itself when the screen inside the TabNavigator will scroll down.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.0.1
| react-native     | 0.55.2
| node             | 9.11.1
| npm or yarn      | 4.6.1

**Comment by brentvatne** [comment]
hi there! this is a question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.
