### ISSUE TITLE
send params between tabs

### ISSUE THREAD

**Issue by jsina** [react-navigation/react-navigation#4277]
## there is no params when navigate to another tab

I want to pass parameter to another tabView component but as you see in the picture there is no params after page navigated.

<img width="284" alt="screen shot 1397-02-30 at 18 12 35" src="https://user-images.githubusercontent.com/2977960/40279549-8e297772-5c59-11e8-89b6-9b59a8a24746.png">

```
<Button
            title="d"
            onPress={() =>
              this.props.navigation.navigate(routeNameConstant.RESERVED, { forceUpdate: true })
            }
          />
```

| software         | version
| ---------------- | -------
| react-navigation | "^1.5.11"
| react-native     | "0.55.2"

**Comment by brentvatne** [comment]
you need to navigate to a screen within the tab to pass a param, it's unclear what the best behavior is here and there is an open rfc thread for discussion: https://github.com/react-navigation/rfcs/issues/43

**Comment by jsina** [comment]
@brentvatne what do u mean to navigate to a screen within the tab? In my situation I want to pass param from e.g tab A to tab B. Is there any way to that or not?

**Comment by brentvatne** [comment]
no. if tab A has screen A, then navigate to screen A

**Comment by jsina** [comment]
@brentvatne here is my code, as you could see the target tab `Reserved` is in a `StackNavigator`. you mean I have to `renamedScreen` instead of `Reserved` like below:

```
              this.props.navigation.navigate('renamedScreen', { forceUpdate: true })

```


```
const ReservedNavigator = StackNavigator({
  renamedScreen: { screen: ReservedScreen },
  ReservedDetail: { screen: ReservedDetailScreen },
});

const Stack = TabNavigator(
  {
    Home: HomeNavigator,
    Favorite: FavoriteNavigator,
    Search: SearchWithModal,
    Reserved: ReservedNavigator,
    Profile: ProfileNavigator,
  },
```

**Comment by brentvatne** [comment]
@jsendros - if this doesn't work then please open a new issue with a minimal runnable example (https://stackoverflow.com/help/mcve) on either https://snack.expo.io or a github repo. thanks! :)
