### ISSUE TITLE
reactnavigation

### ISSUE THREAD

**Issue by fatemehmemat** [react-navigation/react-navigation#4279]
I am using this type of navigation and it is working well.
https://docs.nativebase.io/docs/examples/navigation/StackNavigationExample.html
However, in react navigation version 2, the documents in the example do not work. In second page goBack() does not work and it does not go back to the homeScreen and when I use the hardware back button I exit the application.

**Comment by erandagan** [comment]
See https://github.com/react-navigation/react-navigation/issues/4292
