### ISSUE TITLE
[V2] disable drawer on pushed screens

### ISSUE THREAD

**Issue by karlmosenbacher** [react-navigation/react-navigation#4280]
### Issue
I have been searching around on both stackoverflow and this git, but I still havent found any solution.
I am developing an application where I want to use a tabsnavigator where each tab is a stack.
On the initial screen on each stack I want to use a drawer, and I only want to be able to open the drawer on these two initial screens.

So this is how it looks like from one tab, where you can see that you can push another screen, this works perfectly btw. But after I have pushed a new screen to the stack I want to disable the drawer.
<img width="253" alt="screen shot 2018-05-20 at 9 04 56 pm" src="https://user-images.githubusercontent.com/34436446/40282560-84e6049c-5c71-11e8-945d-652646e17553.png">

So, how do i disable the drawer on the other screens? I have been testing with drawerLockMode in the navigationOptions object on the createDrawerNavigator and I have been testing with navigationOptions on those screens where I want disable the drawer on, but with no luck.

### My code

```
const TabAStack = createStackNavigator(
  {
    TabA: { 
      screen: ScreenA,
    },
    ScreenC: { 
      screen: ScreenC
    },
    ScreenD: { 
      screen: ScreenD,
    }
  },
);

const TabBStack = createStackNavigator(
  {
    TabB: {screen: ScreenB}
  }
);

const Tabs = createBottomTabNavigator({
  TabA: {
    screen: TabAStack,
    navigationOptions: ({navigation}) => {
      return {
        tabBarVisible: hideTabBar(navigation),
      }
    },
  },
  TabB: {
    screen: TabBStack,
    navigationOptions: ({ navigation }) => {
      return {
        tabBarVisible: hideTabBar(navigation),
      }
    }
  },
});


export const SignedInStack = createDrawerNavigator({
  TabsWithDrawer: {
    screen: Tabs,
  },
});

```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^2.0.1
| react-native     | 0.55.2
| node             | 9.4.0
| npm or yarn      | 5.6.0

**Comment by giantss** [comment]
+1 Same problem here.

**Comment by superhawk610** [comment]
@giantss that configuration does not work on iOS, the back swipe gesture pulls the drawer half the time and goes back in the stack the other half of the time, at random.

**Comment by brentvatne** [comment]
https://reactnavigation.org/docs/en/navigation-options-resolution.html

**Comment by giantss** [comment]
@superhawk610 I realized this way, only on the front side slide can call out the sidebar other interface will not call out the sidebar.
