### ISSUE TITLE
createStackNavigator和createBottomTabNavigator结合使用后headerTitle不能显示出来

### ISSUE THREAD

**Issue by 601939654** [react-navigation/react-navigation#4281]
具体代码如下：
/**
 * @author taony
 * @description my future app
 * @since 2018-05-15
 */

import React, {Component} from 'react';
import {Platform} from 'react-native';
import {createStackNavigator, createBottomTabNavigator} from 'react-navigation';
import Home from './js/home/Home';
import Module from './js/modules/Module';
import Apply from './js/app/App';
import My from './js/my/My';
import Others from './js/Others';

const TabContainer = createBottomTabNavigator(
    {
        Home: {screen: Home},
        Module: {screen: Module},
        Apply: {screen: Apply},
        My: {screen: My},
    },
    {
        backBehavior: 'none',
        tabBarOptions: {
            activeTintColor: '#6699FF',
            inactiveTintColor: '#999999',
            style: {
                backgroundColor: '#F8F8F8'
            },
            indicatorStyle: {
                opacity: 0
            },
            tabStyle: {
                padding: 0
            },
            labelStyle: {
                fontSize: 12,
            },
        },
    }
);

const RootStack = createStackNavigator(
    {
        Index: {
            screen: TabContainer,
        },
        Others: {
            screen: Others,
        },
    },
    {
        initialRouteName: 'Index',
        headerMode: 'screen',
        mode: Platform.OS === 'ios' ? 'modal' : 'card',
        navigationOptions: {
            headerStyle: {
                backgroundColor: '#6699FF',
            },
            headerTintColor: '#ffffff',
            headerTitleStyle: {
                fontWeight: 'normal',
            },
        },
    }
);

export default class App extends React.Component {
    render() {
        return <RootStack/>;
    }
};

/**
 * @author taony
 * @deprecated home
 * @since 2018-05-15
 */

"use strict";

import React, {Component} from 'react';
import {View, Text, Button, StyleSheet, Alert} from 'react-native';
import Icon from 'react-native-vector-icons/Ionicons';

export default class Home extends React.Component {

    static navigationOptions = ({navigation}) => ({
        title: '首页',
        tabBarIcon: ({tintColor}) => (<Icon name='md-home' size={25} color={tintColor}/>),
    });

    constructor(props) {
        super(props);
    }

    render() {
        return (
            <View style={styles.main}>
                <Text style={styles.title}>首页</Text>
                <View style={styles.buttonMarginBottom}>
                    <Button title='其他' color='#6699FF' onPress={() => {
                        this.props.navigation.navigate('Others');
                    }}/>
                </View>
            </View>
        );
    };
}

const styles = StyleSheet.create({
    main: {
        flex: 1,
        backgroundColor: '#ffffff',
        alignItems: 'center',
        justifyContent: 'center'
    },
    buttonMarginBottom: {
        marginBottom: 10,
    },
    title: {
        fontSize: 20,
    }
});

问题截图：
![image](https://user-images.githubusercontent.com/17807702/40287660-85339cdc-5ce1-11e8-87b2-12616edf303f.png)

具体说明：
我使用的是createStackNavigator和createBottomTabNavigator结合来实现导航，把createBottomTabNavigator嵌入在createStackNavigator中，并在createBottomTabNavigator的每个tab组件中添加了navigationOptions的title参数，可以在createStackNavigator的导航中并并没有出现headerTitle，不知道是为什么？

| software         | version
| ---------------- | -------
| react-navigation | 2.0.1
| react-native     | 0.55.4
| node             | 6.11.3
| npm or yarn      | 6.0.1

**Comment by leethree** [comment]
I got the same issue with v2. Header is always empty when `BottomTabNavigator` is nested inside `StackNavigator`.

**Comment by 601939654** [comment]
to leethree：yes. but Can you solve the problem?please tell me how.thank you so much.

**Comment by brentvatne** [comment]
please search issues, there are many related to this. more info in https://github.com/react-navigation/react-navigation-tabs/issues/19
