### ISSUE TITLE
Constructor called twice when navigate with both routeName and key specified

### ISSUE THREAD

**Issue by Xing-He** [react-navigation/react-navigation#4283]
### Current Behavior

the constructor called twice when nav.

<img src="https://user-images.githubusercontent.com/11990205/40289426-c586b888-5cea-11e8-84f2-be31b47fd8bd.png" width="300"/>

**i tried specify routeName only, and it works well.**

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.0.1
| react-native     | 0.52.0
| node             | 10.0.0
| npm or yarn      | 5.6.0

### my route stack construct

```js
rootStack = createSwitchNavigator({
    authStack,
    mainStack
})

mainStack = createStackNavigator({
   tabStack,
   ...others
})

tabStack = createBottomTabNavigator({
   home,
   user
})

home = createStackNavigator({
  homeView
})

user = createStackNavigator({
  userView
})
```

- HomeView

```jsx
...
navigation.navigate({
  routeName: 'UserView',
  key: 'UserView',
  params: { initialPage: 2 },
});
...
```

- UserView

```jsx
...
 constructor(props) {
    super(props);
    console.log('------>I\'m constructor');
 }
...
```

there is a button in homeView, when it clicked ,i want to nav from homeView to userView with some params.

**Comment by Tomatoo** [comment]
why use key in navigate? try

```
navigation.navigate({
  routeName: 'UserView',
  params: { initialPage: 2 },
});
```

**Comment by Xing-He** [comment]
@Tomatoo i’ve tried that and  performance well.  but I've noticed that the document can pass the `key ` attribute.  And i think it might be a bug

**Comment by brentvatne** [comment]
can't repro this. feel free to create a new issue with a runnable example if you think it's still a bug
