### ISSUE TITLE
.toggleDrawer() not working / missing documentation on how to use it in nested stacks

### ISSUE THREAD

**Issue by eranbaroz** [react-navigation/react-navigation#4285]
In addition to this closed issue:
[https://github.com/react-navigation/react-navigation/issues/4266](https://github.com/react-navigation/react-navigation/issues/4266)

I'm facing difficulty in code and method that used to work in version 1.4.0.

### Current Behavior

in navigation.toggleDrawer() and error occurred - undefined is not function.

### Expected Behavior

The drawer should toggle 
### How to reproduce

- The code example can be found in this snack:
[https://snack.expo.io/@eranbo/react-navigation---nested-stacks-header-left-not-working](https://snack.expo.io/@eranbo/react-navigation---nested-stacks-header-left-not-working)
- just press the hamburger icon for open and close the drawer

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.0.1
| react-native     | 0.55.3
| node             | 8.11.1
| npm or yarn      | yarn 1.6.0

**Comment by achmadk** [comment]
I have same problem with you, Mr @eranbaroz . My temporary solutions is using `DrawerActions.toggleDrawer()`'s action, then use it into `dispatch` function from `navigation` props.

For example:
```js
import React, { PureComponent } from 'react'
import { withNavigation, DrawerActions } from 'react-navigation'

import { Header, Left, Body, Title, Right, Button, Icon } from 'native-base'

class OverviewsHeader extends PureComponent {
  toggleDrawer = () => {
    this.props.navigation.dispatch(DrawerActions.toggleDrawer())
  }
  render () {
    return (
      <Header>
        <Left>
          <Button transparent onPress={this.toggleDrawer}>
            <Icon name='menu' />
          </Button>
        </Left>
        <Body>
          <Title>Overviews</Title>
        </Body>
        <Right>
          <Button transparent>
            <Icon name='more' />
          </Button>
        </Right>
      </Header>
    )
  }
}

export default withNavigation(OverviewsHeader)
```

**Comment by aboobakkar** [comment]
`onPress={() => this.props.navigation.navigate('DrawerToggle')} ` worked for me

**Comment by edualm** [comment]
I ran into this problem when trying to get a drawer to close itself. `this.props.navigation.closeDrawer()` would not work, but `this.props.navigation.dispatch(DrawerActions.toggleDrawer())` worked just fine.

Note that `this.props.navigation.navigate('DrawerToggle')` did **NOT** work in this case.

**Comment by brentvatne** [comment]
@linux08 - not on the latest version

**Comment by brentvatne** [comment]
no need to call dispatch anymore, `closeDrawer()` will work as expected on `navigationOptions` for screens within drawer and other screens deeper in that hierarchy as of 2.3.0 - https://github.com/react-navigation/react-navigation/releases/tag/2.3.0

**Comment by gwl002** [comment]
@edualm You can log the navigation props.Function openDrawer can only been found on the drawer navigator, the child navigator will not inherit it anymore.

**Comment by LesedimotaungNC** [comment]
@eranbaroz did you find a solution for this?

**Comment by eranbaroz** [comment]
Hi @LesedimotaungNC yes I did, I used the dispatch method with version 2.12.1.
```
import { createStackNavigator, DrawerActions } from 'react-navigation';

let myStackNavigat = createStackNavigator({
            nestedDrawerStack
        }, {
            navigationOptions: ({ navigation }) => {
                return {
                    headerLeft: (<TouchableWithoutFeedback onPress={() => {
                        navigation.dispatch(DrawerActions.toggleDrawer());
                    }}>
                        <View style={styles.leftIconContainer}>
                            <View style={styles.leftIconLine}></View>
                            <View style={styles.leftIconLine}></View>
                            <View style={styles.leftIconLine}></View>
                        </View>
                    </TouchableWithoutFeedback>),
                    ...
                }
            }
        });
```

**Comment by brentvatne** [comment]
this should be resolved. if it is not working as expected still on the latest version, please create a new issue with a runnable example on https://snack.expo.io -- thanks!
