### ISSUE TITLE
getScreenDetails do not works no more after migrating to v2

### ISSUE THREAD

**Issue by realtebo** [react-navigation/react-navigation#4286]
In v1 i was using this code

```
const AppStack = StackNavigator(
  {
    Home: HomeScreen,
    Example: ExampleContentScreen
  },
  {
    navigationOptions: {
      header: (navigationOptions) => {

        console.log (navigationOptions);

        const { scene, getScreenDetails } = navigationOptions;
        const screenDetails = getScreenDetails(scene);
        const { options } = screenDetails;

        return (
          <CustomHeader
            onLeftIconPress={options.onLeftIconPress}
            leftIconName={options.leftIconName}
            title={options.headerTitle}
          />
        );
      }
    }
  }
);
```

I changed `StackNavigator` into `createStackNavigator`.

Running this code i got an error about `getScreenDetails()` that doesn't exists.

what the migration path for this function?

**Comment by carlosa54** [comment]
I'm having the same issue, was using `getScreenDetails` to get some state from the current scene but after updating to v2.0. `getScreenDetails` breaks my code.

**Comment by brentvatne** [comment]
@ericvicenti - can you provide context on this?

**Comment by ericvicenti** [comment]
Yes, this is a breaking change in v2. `getScreenDetails` was an undocumented API which is no longer needed.

Now you have access to the options in this way:

```js
const AppStack = createStackNavigator(
  {
    Home: MyHomeScreen,
    Profile: MyProfileScreen,
  },
  {
    navigationOptions: {
      header: headerProps => {
        const { scene } = headerProps;
        const { options } = scene.descriptor;
        return (
          <CustomHeader
            onLeftIconPress={options.onLeftIconPress}
            leftIconName={options.leftIconName}
            title={options.headerTitle}
          />
        );
      }
    }
  }
);
```

Also changed in v2, the options are no longer deeply nested, so you will no longer see the options from grandchildren screens.

Hopefully this new way is easier for you!

**Comment by dawnmist** [comment]
The descriptor field in scene is not documented in the flow types for react-navigation, and is only mentioned in the [Custom Navigators](https://reactnavigation.org/docs/en/custom-navigators.html#scene-descriptors) section of the Docs (not somewhere I would have expected to need to look). Nothing was mentioned when discussing [replacing the Header component](https://reactnavigation.org/docs/en/custom-navigators.html#scene-descriptors), which I would expect to be one of the places where this would more commonly want to be used. It would probably be a good idea to update these (especially the flow types) at some point to match the description you've provided here. :)

**Comment by ranadeep47** [comment]
also `options` in `descriptor` is not documented in the flow types file. Please update
https://github.com/react-navigation/react-navigation/blob/master/flow/react-navigation.js#L818

**Comment by jbrodriguez** [comment]
@ericvicenti How do you suggest to model a custom Header, which needs data from a redux store ?

In createStackNavigator you don't have acces to redux state.

What I've done is wrap the Header around a connected component and the 'hacked' the options as in

```javascript
class CustomHeader extends PureComponent {
	render() {

		const props = {
			...this.props,
			scene: {
				...this.props.scene,
				descriptor: {
					...this.props.scene.descriptor,
					options: {
						...this.props.scene.descriptor.options,
						headerBackTitleStyle: this.props.colors.headerBackTitleStyle,
						headerTintColor: this.props.colors.headerTintColor,
						headerTitleStyle: {
							color: this.props.color.headerTitleStyle,
						},
						headerStyle: { backgroundColor: this.props.colors.headerStyle },
					},
				},
			},
		}

		return <Header {...props} />
	}
}

const mapStateToProps = (state: AppState) => ({
	colors: getColors(state),
})

export default connect(mapStateToProps)(NavBar)
```

but it doesn't work, except for headerStyle (backgroundColor).

Any suggestions ?

**Comment by jbrodriguez** [comment]
Hi @dawnmist, thanks for the reply.

So, using this.props.scene.descriptor is supported, that's good to know.

In my case I want to reuse the stock Header component

```
import { Header } from 'react-navigation'
```

so as to not rewrite behaviour, but just re-style it via the exposed props (headerStyle, headerTintColor, etc.)

But, internally, ```<Header />``` expects those properties in this.props.scene.descriptor.options.

This is why I was mergining props in my example, and it seemed to work only for headerStyle.

Any thoughts ?

**Comment by dawnmist** [comment]
Hi jbrodriguez,

My other suggestion would be to use the "screenProps" property when rendering the Stack to pass them in, so that they are there to use when defining the normal navigation options (the below example is assuming you are [using redux integration as documented here](https://reactnavigation.org/docs/en/redux-integration.html)).

Stack Component definition:
```js
import React from 'react';
import {
  createNavigationPropConstructor,
  initializeListeners
} from 'react-navigation-redux-helpers';
import { connect } from 'react-redux';

// Note: createReactNavigationReduxMiddleware must be run before createNavigationPropConstructor
// Note2: I created both the middleware and prop constructor inside the reducer definitions rather
// than in the component here, and then imported the navigationPropConstructor itself into the 
// component. I've put the prop constructor here simply to show where the function 
// navigationPropConstructor came from.
const navigationPropConstructor = createNavigationPropConstructor('root');

// Actual component.
class RootStack extends React.Component {
  componentDidMount() {
    initializeListeners('root', this.props.nav);
  }

  render() {
    const nav = navigationPropConstructor(this.props.dispatch, this.props.nav);
    return <Stack navigation={nav} screenProps={colors: this.props.colors} />;
  }
}

const mapStateToProps = (state) => {
  return {
    nav,
    colors: getColors(state)
  };
};
const mapDispatchToProps = (dispatch) => ({ dispatch });
export default connect(mapStateToProps, mapDispatchToProps)(MainStack);
```

Stack definition:
```js
import Header from 'Header';
import Home from 'Home';
import Settings from 'Settings';

export const Stack = createStackNavigator(
  {
    Home: { screen: Home },
    Settings: { screen: Settings }
  },
  {
    navigationOptions: ({ navigation, screenProps }) => ({
      headerBackTitleStyle: screenProps.colors.headerBackTitleStyle,
      headerTintColor: screenProps.colors.headerTintColor,
      headerTitleStyle: { color: screenProps.colors.headerTitleStyle },
      headerStyle: { backgroundColor: screenProps.colors.headerStyle }
    })
  }
);
```

**Comment by jbrodriguez** [comment]
Thanks a lot @dawnmist !!

I like your solution and will test it out, I'm pretty sure it will work, so I'll use that.

I was looking for a solution in the meantime and found that the issue for me was that react-navigation's Header reads from this.props.scenes, rather than this.props.scene (starting from https://github.com/react-navigation/react-navigation/blob/8ec2466fefc7b0a22dde088bd982e20bdfb2c767/src/views/Header/Header.js#L434)

So, I came up with the following, which feels hacky, but works 😄

```javascript
import { Header } from 'react-navigation'

class CustomHeader extends PureComponent {
  render() {
    const { colors, ...props } = this.props;
    const { scenes, scene } = props;

    scenes[scene.index].descriptor.options = {
	...scenes[scene.index].descriptor.options,
	headerStyle: colors.headerStyle,
	headerTitleStyle: colors.headerTitleStyle,
	headerBackTitleStyle: colors.headerBackTitleStyle,
	headerTintColor: colors.headerTintColor,
    }

    return <Header { ...props } />
  }
};

const mapStateToProps = (state) => ({ colors: getColors(state) });
export default connect(mapStateToProps)(CustomHeader);
```

**Comment by dzotos** [comment]
Hi, tried the new way (v2) @ericvicenti mentioned, but I'm getting this error.

<img width="366" alt="screenshot 2018-06-08 23 14 45" src="https://user-images.githubusercontent.com/1688237/41179017-df511430-6b71-11e8-97a7-194c88ab33b9.png">


The stack
```javascript
const AppNavigator = createStackNavigator({
   PostJobStep1: {
        screen: PostJobStep1,
        navigationOptions: ({ navigation }) => ({
            header: headerProps => {
                const { scene } = headerProps;
                const { options } = scene.descriptor;
                return (
                    <CustomHeader {...options} />
                );
            },
            headerLeft: <HeaderLeft navigation={navigation} icon="close" />,
        }),
    },
});,
```

CustomHeader.js
```javascript
import React from 'react';
import { Header } from 'react-navigation';
import { View } from 'react-native';
import SimpleProgressBar from '../../../components/progress/SimpleProgressBar';

const CustomHeader = (props) => {
    return (
        <View>
            <Header {...props} />
            { props.progressBar &&
                <View>
                    <SimpleProgressBar progress={props.progress} />
                </View>
            }
        </View>
    )
};

export default CustomHeader;
```

Any ideas?

**Comment by brentvatne** [comment]
hi there! if this is still a bug can you create a new issue that reproduces the bug on https://snack.expo.io? thanks!
