### ISSUE TITLE
createDrawerNavigator ignoring initialRouteParams

### ISSUE THREAD

**Issue by luchoct** [react-navigation/react-navigation#4287]
createDrawerNavigator relies on a SwitchRouter, but on building configs does not support initialRouteParams anymore so it's not possible to provide initialRouteParams.

This looks to be a regression, since this behavior worked well before migrating to version v2.

Just by adding initialRouteParams to routeConfig, SwitchRouter should be able to handle that value.

**Current Code in createDrawerNavigator**
```
const {
    order,
    paths,
    initialRouteName,
    backBehavior,
    ...drawerConfig
  } = mergedConfig;

  const routerConfig = {
    order,
    paths,
    initialRouteName,
    backBehavior,
};
```

**Suggested Fix**
```
const {
    order,
    paths,
    initialRouteName,
    initialRouteParams,
    backBehavior,
    ...drawerConfig
  } = mergedConfig;

  const routerConfig = {
    order,
    paths,
    initialRouteName,
    initialRouteParams,
    backBehavior,
};
```

**Comment by brentvatne** [comment]
fixed in https://github.com/react-navigation/react-navigation-drawer/commit/22491e15e9b0994bb96101bfec82d8c4d1928aae - will go in next release
