### ISSUE TITLE
You should only render one navigator explicitly in your app, and other navigators should by rendered by including them in that navigator

### ISSUE THREAD

**Issue by Shabnam-Veranloo** [react-navigation/react-navigation#4291]
I want add tab inside view {my view has image and i want add tab between image} when i add tab as a class like <tab> from other class that export show me this error and when i false (JS Dev mode) work it!!!

**Comment by brentvatne** [comment]
see the resolution of this issue https://github.com/react-navigation/react-navigation/issues/4196

**Comment by Shabnam-Veranloo** [comment]
i cant find any solution this issue(#4196) and i cant write my issue or comment there
why close issues without  find any solution!!!
