### ISSUE TITLE
[Question] Is it possible to bind custom props to navigationOptions?

### ISSUE THREAD

**Issue by redstubble** [react-navigation/react-navigation#4296]
I apologise but I have researched documentation and stack but cannot find anything that is similar to my situation.

```
const rootNav = createBottomTabNavigator(
  {
    Trade: {
      screen: Trade,
      path: '/',
      navigationOptions: {
        title: 'Position',
        tabBarLabel: 'Trade',
        tabBarIcon: CustomTabBarIcon, // CustomTabBarIcon.bind("foo") OR
        // customProp: foo
      },
    }, ...
```

I want to bind a custom property to CustomTabBarIcon so that I can create a generic function for all my screens. Can I bind it or add a custom property. Or am I looking at this in the wrong way?

```
const TradeTabBarIcon = ({ tintColor, focused }, foo) => {
// foo = foo OR foo = this.customProp
  return (
    <Ionicons
      name={`${foo}-icon`}
      size={26}
      style={{ color: tintColor }}
    />
  );
};
```
Can this be done?
PS I want to extract my function so that I can manage PropTypes (ESLint)

**Comment by brentvatne** [comment]
this seems like a general javascript question - "how do I curry a function?"

you might want to do something like this

```js
const CustomTabBarIcon = (foo) => {
  return ({ tintColor, focused }) => (
    <Ionicons
      name={`${foo}-icon`}
      size={26}
      style={{ color: tintColor }}
    />
  );
}
```
