### ISSUE TITLE
custom tabBarComponent with TabBarBottom broken

### ISSUE THREAD

**Issue by mtt87** [react-navigation/react-navigation#4297]
### Current Behavior

When you use a `createBottomTabNavigator` and a custom `tabBarComponent` using `TabBarBottom` and just passing props, it gives a type error `layout.width` is `undefined`

I suspect there are missing props passed through `tabBarComponent`.

### How to reproduce

Snack to reproduce:
https://snack.expo.io/H1Hi61G1Q

Code:
```js
import React, { Component } from 'react';
import { Text, View, StyleSheet } from 'react-native';
import { createBottomTabNavigator, TabBarBottom } from 'react-navigation';

const TabScreen = (props) => (<View><Text>HELLO WORLD</Text></View>);

const TabBarComponent = (props) => (<TabBarBottom {...props} />);

const TabScreens = createBottomTabNavigator(
  {
    Tab1: {
      screen: TabScreen,
    },
    Tab2: {
      screen: TabScreen,
    },
  },
  {
    tabBarComponent: props => <TabBarComponent {...props} style={{ borderTopColor: '#605F60' }} />,
    tabBarPosition: 'bottom',
    animationEnabled: false,
    tabBarOptions: {
      activeTintColor: '#D3D2D3',
      inactiveTintColor: '#605F60',
      inactiveBackgroundColor: '#151517',
      activeBackgroundColor: '#151517',
      labelStyle: {
        fontSize: 10,
        paddingBottom: 3,
      },
      style: {
        backgroundColor: '#151517',
      },
    },
    showIcon: false,
    swipeEnabled: false,
  },
);

export default TabScreens;
```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.0.1
| react-native     | 0.55.4
| node             | 9.10.0
| npm or yarn      | 5.6.0

**Comment by brentvatne** [comment]
cc @satya164

**Comment by satya164** [comment]
@brentvatne this is because the exported `createBottomTabNavigator` is from `react-navigation-tabs` and `TabBarBottom` is from `react-navigation-deprecated-tab-navigator`. They are not compatible with each other.

You need to install `react-navigation-tabs` package and import them from there.

```js
import { createBottomTabNavigator, BottomTabBar } from 'react-navigation-tabs';
```

**Comment by mtt87** [comment]
@satya164 Thanks for the reply, I thought about that but then I saw this and it's a bit misleading
<img width="421" alt="screen shot 2018-05-24 at 15 11 09" src="https://user-images.githubusercontent.com/2150927/40487518-b2d80954-5f64-11e8-939d-9ef6032c0b75.png">
Should I install `react-navigation-tabs` separately?

**Comment by satya164** [comment]
@mtt87 you don't need to explicitly install it since yarn and npm 3 flattens your node_modules as it's a dependency of react-navigation, but it's always confusing to me to not have a package I use in package.json.

**Comment by mtt87** [comment]
@satya164 it is indeed confusing to me as well (and not a good practice), I will do thank you!

That said, wouldn't it be easier to just make `TabBarBottom` the correct one?

I mean if you are using `react-navigation > 2.0.0` importing `TabBarBottom` should come from `react-navigation-tabs` while if you are using `react-navigation < 2.0.0` importing it should come from `react-navigation-deprecated-tab-navigator`?

**Comment by satya164** [comment]
@mtt87 yeah. it should be exported from `react-navigation`, but we would need to add a separate export for `BottomTabBar`. the current `TabBarBottom` export is deprecated and is there for compatibility with old versions, so we can't change that one. also, I think it's pretty confusing to have exports for different tab navigators and tab bars in react-navigation and it's going to confuse people even with good docs :(

**Comment by Albert-Gao** [comment]
I figure it out by reading the source code. I think it might be better that we add it to the doc so people can know how to use it. The current doc only say can use `tabBarComponent` to customize but doesn't say how. Took a while to figure it out. Need a PR for this? :D

**Comment by mtt87** [comment]
@satya164 Sorry to bother you but I'm a bit confused: is there a **new** version of the `TabBarBottom` component that is called `BottomTabBar` and I am using an old deprecated component?

**Comment by satya164** [comment]
@mtt87 yes. it's confusing. `createTabNavigator` and `TabBarBottom` are from `react-navigation-deprecated-tab-navigator` which is old version and they are exported from `react-navigation` for compatibility. `createBottomTabNavigator` and `BottomTabBar` are from `react-navigation-tabs` and only `createBottomTabNavigator` is exported from `react-navigation`.

**Comment by Albert-Gao** [comment]
@satya164 Hi, in the middle of adding more info to the tab, 2 questions

1. For the `tabComponent` on `createBottomTabNavigator ` [page](http://localhost:3000/docs/en/bottom-tab-navigator.html), I just add one more sentence:
`You need to import `BottomTabBar` from `react-navigation-tabs` in order to receive the passing `props`.`

1. For the `tabComponent` on `createTabNavigator` [page](http://localhost:3000/docs/en/tab-navigator.html) It said:
> Component to use as the tab bar, e.g. TabBarBottom (this is the default on iOS), TabBarTop (this is the default on Android).

I checked its code, but can't quite tell if the `TabBarBottom` here is the deprecated one or a new alternative. Because it seems it uses a passing-in prop as the base to render.

Do I need to add explanation here too?

**Comment by mtt87** [comment]
@satya164 I think the problem here is that `react-navigation` is not exporting `BottomTabBar` but only the deprecated `TabBarBottom`
```js
  get TabBarBottom() {
    console.warn(
      'TabBarBottom is deprecated. Please use the react-navigation-tabs package instead: https://github.com/react-navigation/react-navigation-tabs'
    );
    return require('react-navigation-deprecated-tab-navigator').TabBarBottom;
  },
```

Why isn't there an export for `BottomTabBar`?
i.e.
```js
  get BottomTabBar() {
    return require('react-navigation-tabs').BottomTabBar;
  },
```

**Comment by Albert-Gao** [comment]
@mtt87 I think this is for the compatibility of the old version

**Comment by mtt87** [comment]
@Albert-Gao then it must be clear that you **need** to install `react-navigation-tabs` if you wanna use a custom `BottomTabBar` and that's fine.

**Comment by Albert-Gao** [comment]
@mtt87 Exactly how I modified the document :)

**Comment by brentvatne** [comment]
react-navigation-tabs is included in react-navigation@^2.0.0

**Comment by mtt87** [comment]
@brentvatne indeed it is, but it's not a good practice that you need to include a module imported by one of your modules not listed in your app `package.json`.

If doing this is not what you want to do inside `react-navigation`
```js
  get BottomTabBar() {
    return require('react-navigation-tabs').BottomTabBar;
  },
```
Then again, it needs to be clear in both `react-navigation` and `react-navigation-tabs` that you **must** include `react-navigation-tabs` whenever you wanna use a `customTabBar` component and use the default `BottomTabBar` which is only exported by `react-navigation-tabs` and not `react-navigation`.

**Comment by mtt87** [comment]
I'm closing the issue, it's just about documentation I believe @Albert-Gao wanted to add it to the documentation, otherwise people can find the issue here and how to solve it.

Thanks everyone 😄

**Comment by hahtml** [comment]
This one is pretty tricky. Figure it out after going through the conversation. Need to update the misleading docs or export BottomTabBar in react-navigation as well.

**Comment by Kishanjvaghela** [comment]
> @mtt87 you don't need to explicitly install it since yarn and npm 3 flattens your node_modules and it's a dependency of react-navigation, but it's always confusing to me to not have a package I use in package.json.

This saved my lots of time
