### ISSUE TITLE
Shifting and focused boolean with createMaterialBottomTabNavigator

### ISSUE THREAD

**Issue by divdotshoya** [react-navigation/react-navigation#4299]
### Current Behavior
My aim is to make a MaterialBottomTabNavigator which changes the icon for the selected tab, among 5 tabs, however, the focused boolean appears to be broken when shifting is enabled.
Code example:  
```js
import React from 'react';
import { createMaterialBottomTabNavigator } from 'react-navigation-material-bottom-tabs';

class Screen1 extends React.Component {
  static navigationOptions = {
    tabBarIcon: ({ focused }) => {
      console.log('Screen1', focused);
    },
    activeTintColor: 'blue',
  };
  render() {
    return null;
  }
}
class Screen2 extends React.Component {
  static navigationOptions = {
    tabBarIcon: ({ focused }) => {
      console.log('Screen2', focused);
    },
    activeTintColor: 'red',
  };
  render() {
    return null;
  }
}

const MaterialBottomTabNavigator = createMaterialBottomTabNavigator(
  {
    Screen1: Screen1,
    Screen2: Screen2,
  },
  {
    shifting: true,
  }
);

export default class App extends React.Component {
  render() {
    return <MaterialBottomTabNavigator />;
  }
}
```  
Console shows:  
![image](https://user-images.githubusercontent.com/39280494/40396042-d195ea2c-5ddf-11e8-91a8-8ef479829d84.png)

However, if shifting is changed to false, the focused boolean works as expected, although the tabBarIcon still appears to be referenced twice:  
![image](https://user-images.githubusercontent.com/39280494/40396077-fbec057c-5ddf-11e8-9331-2cd5da56d70b.png)

### Expected Behavior

- The focused variable should work consistently between shifting enabled or disabled

### How to reproduce

- To see the error run the above code and compare console logs between shifting: true, and shifting: false

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^2.0.1
| react-native     | 0.55.4
| node             | v8.11.2
| yarn      | 1.6.0

**Comment by divdotshoya** [comment]
Hey there, any thoughts or updates on this issue?
@brentvatne

**Comment by brentvatne** [comment]
no updates

**Comment by brentvatne** [comment]
hello! I got around to looking at this, ran it on the latest version of react-navigation and it works as expected (although it was difficult to tell what was going on from console.log, so i added some text instead). check package.json and make sure your versions align: https://snack.expo.io/B1IZQyJGm

**Comment by divdotshoya** [comment]
Thank you!
