### ISSUE TITLE
[V2] Title cannot be edited on navigation bar

### ISSUE THREAD

**Issue by ycman0307** [react-navigation/react-navigation#4301]
**Current Behavior**
I want to change the header title for each page but it always shows the first page title. This code work in Version 1.

const StackNav = createStackNavigator({
    Langing: {
      screen: LangingPage,
      navigationOptions: ({ navigation }) => ({
        title: 'The first Page',
        headerLeft: <DrawerButton navigation={navigation} />
      })
    },
    Login: {
        screen: Login,
    },
});

**Login.js**
class Login extends Component {
    static navigationOptions = ({ navigation }) => {
        const { params } = navigation.state;
        
        return {
            title: params ? params.headerTitle : 'Login',
            headerLeft: null,
            headerStyle: {
                backgroundColor: '#32add8',
            },
        };
    };
    render() {
        return (
        ...................
     )}
}

**Comment by brentvatne** [comment]
https://reactnavigation.org/docs/en/navigation-options-resolution.html

**Comment by ycman0307** [comment]
I tried to this method but it is not my expectation.

This is my first page.
![first page](https://user-images.githubusercontent.com/13992428/40460796-0d36dca6-5f3b-11e8-8758-27ff76411e61.png)

When i click another page from the drawer menu, the Header title did not change. I can only change the menu label.
![loginpage](https://user-images.githubusercontent.com/13992428/40460836-46906ee0-5f3b-11e8-9829-9cc999f04c11.png)

Would you mind provide another method for me??

**Comment by brentvatne** [comment]
you can use the same approaches discussed here https://github.com/react-navigation/react-navigation-tabs/issues/19

**Comment by ycman0307** [comment]
Thank you for your help. i can edit the title now.
