### ISSUE TITLE
Force re render on Back action

### ISSUE THREAD

**Issue by VKGraphics** [react-navigation/react-navigation#4302]
Using stack navigator when I go from the screen(A) -> screen(B) and click Back on Screen(B), I see Screen(A) with previous state and data as expected.

But now I want to do a force re-render based on some condition. Is there any way to this?

Here is the use case:-

For example, I have a List and details screen.

When the user clicks on listItem L, then it will go details. let's say If the user set that particular Item favourite in details and come back to the list, then that item should update with that favourite tag

**Comment by brentvatne** [comment]
https://reactnavigation.org/docs/en/with-navigation-focus.html
