### ISSUE TITLE
Drawer miss the close event if performed before the open animation finish

### ISSUE THREAD

**Issue by sebastienbarbier** [react-navigation/react-navigation#4304]
### Current Behavior

Using `this.props.navigation.toggleDrawer();` on a menu button, an issue occur if you close the drawer by sliding it out of the screen before the opening animation finish. Seams like `navigation.state.isDrawerOpen` is not updated.

![drawermisscloseevent](https://user-images.githubusercontent.com/3018618/40432725-a543106e-5eaa-11e8-940a-b9a8e0b9f8c9.gif)

### Expected Behavior

Close event should be catched even if the open animation does not finish.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.0.1
| react-native     | 0.55.4
| node             | 8+
| npm or yarn      | 5.8.0

**Comment by sebastienbarbier** [comment]
Looking at [react-native-drawer-layout repository](https://github.com/react-native-community/react-native-drawer-layout), seams like `<DrawerLayout>` used in `DrawerView.js` accept a property called `onDrawerStateChanged` which return some inputs: **`Settling`, ` Dragging`, `Idle`**.

**react-navigation** currently does not implement any behaviour for this event so I guess one option is to add support for it. I don't think I will have time to help for now, but that's an idea.

**Comment by vladikoff** [comment]
Had the same issue on my Android devices as well. Let me know if you need help reproducing this issue

**Comment by eranbaroz** [comment]
@sebastienbarbier Can you share a snack of the problem? or any other way that we can see the code with the problem?

**Comment by PaijoRX** [comment]
I got same error,  the drawer will open and close forever.

**Comment by sebastienbarbier** [comment]
@eranbaroz Can easily be reproduced using the **Drawer Example** from the **NavigationPlayground** application on any android device ([link](https://expo.io/@react-navigation/NavigationPlayground)). 

If you **click on "Open Drawer",** **wait** for the drawer to fully open, then **close it**, you can click again and have the drawer opening normally. If this time you **click on Open Drawer**, and **before having the open animation finished** you grab the drawer and **slide it our of the screen to close it**, you will not be able to open it again.

![drawerissue](https://user-images.githubusercontent.com/3018618/40547975-aa84e66c-6033-11e8-8765-f5c911be757f.gif)

Looking at `DrawerLayout` from `'react-native-drawer-layout-polyfill'` then `'react-native-drawer-layout' `, we have the following code:
Source : [https://github.com/react-native-community/react-native-drawer-layout/blob/master/src/DrawerLayout.js#L222](https://github.com/react-native-community/react-native-drawer-layout/blob/master/src/DrawerLayout.js#L222)

```
openDrawer = (options: DrawerMovementOptionType = {}) => {
        this._emitStateChanged(SETTLING);
        Animated.spring(this.state.openValue, {
            toValue: 1,
            bounciness: 0,
            restSpeedThreshold: 0.1,
            useNativeDriver: this.props.useNativeAnimations,
            ...options,
        }).start(() => {
            if (this.props.onDrawerOpen) {
                this.props.onDrawerOpen();
            }
            this._emitStateChanged(IDLE);
        });
};
```

My guess is that react-navigation only handle the `onDrawerOpen` event to update the `state.isDrawerOpen`. One solution should be to catch the `this._emitStateChanged(SETTLING);` event throught the `onDrawerStateChanged` props available on `<DrawerLayout />` component to check if the drawer acutally opened.

**Comment by ezekel** [comment]
@sebastienbarbier , how to do that your example is that gif ?can you help me plesae how to do that because I have also problem and I want to show my screen and post like that.

Thank you in advance.

**Comment by sebastienbarbier** [comment]
@ezekel You need to download a screen record application, and export as Gif. On MacOS I use [LICEcap](https://licecap.en.softonic.com/), but there is existing application for every platform. I'm sure you'll find the latest shinny app for your system with a [search on stackoverflow](https://stackoverflow.com/search?q=screen+record+gif) 😉.

**Comment by ezekel** [comment]
@sebastienbarbier . Ok thank you I am on windows I will try find that screen recorder.

Thank you.

**Comment by brentvatne** [comment]
i refactored the drawer navigator and this is no longer an issue in the latest version

**Comment by vladikoff** [comment]
Thank you so much!
