### ISSUE TITLE
How to use native driver for transition ?

### ISSUE THREAD

**Issue by userbq201** [react-navigation/react-navigation#4308]
How to use native driver for transition in stack navigator ? REnder google map lock thread and transition not working/ How add in config `useNativeDrawer: true` ?

**Comment by brentvatne** [comment]
it uses native driver by default. google map would lock the animation because it's doing a lot of work on the main thread, not on the JS thread. you should delay showing the map until the transition is complete to avoid this problem

**Comment by brentvatne** [comment]
also, this is a question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.
