### ISSUE TITLE
Nested createBottomTabNavigator inside createStackNavigator - Can't set tab header

### ISSUE THREAD

**Issue by Futy99** [react-navigation/react-navigation#4310]
Hey, it seems to me like an easy problem. I want to set different title for each tab's header in my createBottomTabNavigator which is nested in createStackNavigator. Unfortunately I can't get result which I want. I tried it several ways without success. 

Code - https://snack.expo.io/HJnDDLQk7

Is there any way how to achieve that or it is a bug?

| software         | version
| ---------------- | -------
| react-navigation | 2.0.1
| react-native     | 0.51.1
| node             | 9.4.0
| npm or yarn      | 5.6.0 and 1.6.0

**Comment by brentvatne** [comment]
see: https://reactnavigation.org/docs/en/navigation-options-resolution.html
also: https://github.com/react-navigation/react-navigation/issues/4120#issuecomment-386840216

also, you should probably put stacks in tabs rather than tab in stack.

**Comment by f3ist** [comment]
The NavigationPlayground example still has `title` defined for tab screens

https://github.com/react-navigation/react-navigation/blob/master/examples/NavigationPlayground/js/StacksOverTabs.js

**Comment by Futy99** [comment]
Fixed my problem

`Tabs.navigationOptions = ({ navigation }) => {
  let title;
  let focusedRouteName = navigation.state.routes[navigation.state.index].routeName;
  if (focusedRouteName === 'Home') {
    title = 'Home'; // of course in this case it's the same, but do whatever you want here
  } else if (focusedRouteName === 'Settings') {
    title = 'Settings';
  }

  return {
    title,
  };
};`

**Comment by brentvatne** [comment]
@f3ist - fixed

other ppl who see this: https://reactnavigation.org/docs/en/navigation-options-resolution.html for more information
