### ISSUE TITLE
How should I get data from urls in react-native-web

### ISSUE THREAD

**Issue by Pneumatic95** [react-navigation/react-navigation#4312]
**The problem**
My app project use` react-navigation`, in react-native-web, how can I get the data that I want through `path`, or have other api..?

router.js
```javascript
import {StackNavigator, NavigationActions} from 'react-navigation/lib/react-navigation.js';
import { enhance } from './dependence/react-native-addons'
const myApp = enhance(StackNavigator){
  ProductDetailPage:{
    screen: ProductDetailPage,
    path: 'product/:packIdEn',
  }
}
```
ProductDetailPage.js
```javascript
class ProductDetailPage extends Component {
  constructor(props) {
    super(props);
    console.log('props', props);
  }
}
```
![tm20180523180438](https://user-images.githubusercontent.com/20735608/40418124-14c18bce-5eb4-11e8-967b-36dfaf54bb8c.png)

In the props, it shows `props.navigation.state` contain some data. Is there any way I can get `packIdEn` here?

**Environment (include versions). Did this work in previous versions?**

* OS: Windows 7
* Device:
* Browser: Chrome 66.0.3359.181
* React Native for Web (version):  0.5.4
* React (version): 16.0.0-alpha.12
* React Navigation (version):1.0.0-beta.22

**Additional context**
Thank you

**Comment by ericvicenti** [comment]
@Pneumatic95, that API should work just fine, I've just double checked that it works! The question is, how have you set up your react-native-web environment? If you don't have a container that sets up your browser, then it wont work. I have one in progress over here, and I'll have it published to npm soon: https://github.com/ericvicenti/universe/tree/master/universal/src/react-navigation-web

I see you're also using an older version of React Navigation. I'm not sure how well the feature worked back in that version.

**Comment by Pneumatic95** [comment]
@ericvicenti , thank you, I have solved it, but I will try what you say

**Comment by DaKaZ** [comment]
@Pneumatic95 please share what you did.  I too am trying to get deep linking working in a react-native-web project and can't seem to get the path to the router.

**Comment by Pneumatic95** [comment]
@DaKaZ , I only get some params through `initialProps:{'location':window.location}` in the `index.web.js` , it didn't solve the path problem , I still can't get the path to the router

**Comment by geminiyellow** [comment]
hi @Pneumatic95 , i got same question, because ` I still can't get the path to the router` , i think  you can reopen this issue.
and hi @ericvicenti , i check the react-navigation/react-navigation-web , you use redux manage the navigation state, but i just simply want to get the param from url, looks cannot get the right one. 
could you give some example?
