### ISSUE TITLE
createBottomTabNavigator  , undefine is not a function

### ISSUE THREAD

**Issue by aqnaruto** [react-navigation/react-navigation#4313]
here is my code

> import React from 'react';
import {StyleSheet} from 'react-native';
import Scene1 from '../pages/Scene1';
import Scene2 from '../pages/Scene2';
// import Icons from '../components/Icons';
import { createBottomTabNavigator} from 'react-navigation';
export default  MainContainer = createBottomTabNavigator(
    {
        Scene1: {screen: Scene1},
        Scene2: {screen: Scene2}
    },
    {
        backBehavior: 'none',
        tabBarOptions: {
            activeTintColor: '#6699FF',
            inactiveTintColor: '#999999',
            style: {
                backgroundColor: '#F8F8F8'
            },
            indicatorStyle: {
                opacity: 0
            },
            tabStyle: {
                padding: **0**
            },
            labelStyle: {
                fontSize: 12,
            },
        },
    }
);

 the error is 

![qq 20180524104920](https://user-images.githubusercontent.com/9067159/40461954-56f408f0-5f40-11e8-9f3a-0333427686bb.jpg)

**Comment by vjsingh** [comment]
how did you fix this?
