### ISSUE TITLE
tab is still changed even though tabBarOnPress did not call jumpToIndex

### ISSUE THREAD

**Issue by jarvisluong** [react-navigation/react-navigation#4315]
### Current Behavior

I use ```createBottomTabNavigator``` and make a tabButton to have a custom ```tabBarOnPress```, which does not call ```jumpToIndex``` inside it. When I press that tab Button, the functions inside ```tabBarOnPress``` was called but then the tab also change.

### Expected Behavior

The tab should not change if I don't call ```jumpToIndex```

### How to reproduce

Snack: https://snack.expo.io/SJzq3J4k7

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.0.1
| expo | 27.0.0

**Comment by brentvatne** [comment]
fixes in 2.0.3
