### ISSUE TITLE
Cannot read property 'params' of null

### ISSUE THREAD

**Issue by tindery** [react-navigation/react-navigation#4322]
Hello (this is re-created issue #4263), i've updated to react-navigation 2.0.1 and i've encountered following error when nesting navigations:

![image](https://user-images.githubusercontent.com/31622405/40482340-c770baf6-5f54-11e8-9682-dd69f4a92eec.png)

to reproduce:

```
import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { createStackNavigator, createDrawerNavigator } from 'react-navigation';

export default class App extends React.Component {
  render() {
    return (
      <View style={styles.container}>
        <StackNav />
      </View>
    );
  }
}

class Home extends React.Component {
  render() {
    return (
      <View style={styles.container}>
        <Text>Home</Text>
      </View>
    );
  }
}

class Page extends React.Component {
  render() {
    return (
      <View style={styles.container}>
        <Text>Page</Text>
      </View>
    );
  }
}

class Stack extends React.Component {
  render() {
    return (
      <View style={styles.container}>
        <Text>Hello world! Stack</Text>
      </View>
    );
  }
}

const DrawerNav = createDrawerNavigator({
  Main: Home, 
  Page: Page
});

const StackNav = createStackNavigator({
  Main: DrawerNav,
  Stack: Stack
});

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
```

Is this a bug or was there a change to how nesting works?

| react-navigation | 2.0.1
| react-native | 0.55.2

**Comment by Jekiwijaya** [comment]
@tindery this because you put DrawerNavigator first.

try to change into
`
const StackNav = createStackNavigator({
  Stack: Stack,
  Main: DrawerNav,
});
`

**Comment by tindery** [comment]
@Jekiwijaya well now i feel silly :D my main project is way too messy didn't think updating to v2 would have problem with route names.
Thank you :)

**Comment by a1292999652** [comment]
> @tindery that's because you have 2 same routeName, `Main`.
> 
> ```
> 
> const DrawerNav = createDrawerNavigator({
>   Main: Home, 
>   Page: Page
> });
> 
> const StackNav = createStackNavigator({
>   Drawer: DrawerNav, 
>   Stack: Stack
> });
> ```
> 
> Try change one of them.
> 
> note. Don't put style in App. The drawer would become messy.

Inspired by you, I found out that I was wrong to define a nonexistent initialRouteName
