### ISSUE TITLE
Passing graphql data into all the tab navigator routes

### ISSUE THREAD

**Issue by AndreBastos23** [react-navigation/react-navigation#4324]
Hello,

I'm currently doing an application with react-navigation and graphql(react-apollo) and i'm having some difficulty passing information from 1 route to all the routes inside a tab navigator.
What i want to do is pass an ID of an object to be accessible to all the routes inside a tab navigator.
For example, this is my code:

Navigator:
```
const GroupTabNavigator = createBottomTabNavigator(
  {
    GroupDetails: {
      screen: GroupScreen,
    },
    Events: {
      screen: EventListTab,
    },
    Polls: {
      screen: PollsScreen,
    },
  },
  {
    initialRouteName: 'GroupDetails',
  },
);

// connect the full GroupTabNavigator to the graphql response
const ConnectedGroupTabNavigator = graphql(fetchGroupInfo, {
  options: props => ({
    variables: { groupId: props.navigation.getParam('groupId') },
  }),
  screenProps: data => data,
})(GroupTabNavigator);
```

When i navigate to the GroupDetails route, i pass the param i want to that route, and that works fine, but i also want to have access to that parameter in the Events route.. Is there a way to share props between tab navigator screens?

PS: The ConnectedGroupTabNavigator doesn't work, that's something i was trying to do to connect the full navigator to the graphql.

**Comment by brentvatne** [comment]
hi there! this is a question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.
