### ISSUE TITLE
When redux rerenders a view containing a StackNavigator it reset itself to initial screen

### ISSUE THREAD

**Issue by fcaride** [react-navigation/react-navigation#4325]
Hi, im using v: 1.5.11 and somehow 

in this code:
```javascript
export default class Login extends React.Component {
  render() {
    const { login } = this.props;
    const StackLogin = StackNavigator({
      Login: {
        screen: Login,
      },
      SignIn: {
        screen: SignIn
      }
    });
    return (
      <View >
        <Text>login.userName</Text>
        <StackLogin/>
      </View>
    );
  }
}

export default connect(state => ({ login: state.login}), mapDispatchToProps)(Profile);
```

If i change the login property of the redux state when redux rerenders the View my StackLogin resets to initial state (If i am in the SignIn view it goes back to Login). Its like its not maintaining its own state. Maybe its something im missing about this library.
Regards

**Comment by brentvatne** [comment]
hi there!

just wanted to point out this tidbit from the issue template:

> Bugs with react-navigation must be reproducible *without any external libraries that operate on it*. This means that if you are attempting to use Redux or MobX with it and you think you have found a bug, you must be able to reproduce it without Redux or MobX in this report. Redux related issues belong in [react-navigation-redux-helpers](https://github.com/react-navigation/react-navigation-redux-helpers), and we do not have any first-class integration with MobX at the moment.

could you repost this to the redux helpers issue as mentioned above?

**Comment by damian-pf** [comment]
I recently upgraded a project from 1.0.0-beta.21 to 1.5.11 and am having the same issue. 

@fcaride have you had any luck getting this to work?
