### ISSUE TITLE
The back button always closes the app after a reload due to app being closed from memory pressure

### ISSUE THREAD

**Issue by phorque** [react-navigation/react-navigation#4329]
Hello there! I originally posted this issue on Expo but maybe you guys have some thoughts about it.

After the app is reloaded from background the back button always closes the app, it works great inside the Expo client but not in standalone apps.

I built a version of the NavigationPlayground app where I can reproduce the issue : https://expo.io/@phorque/NavigationPlayground (the APK is here https://exp-shell-app-assets.s3-us-west-1.amazonaws.com/android%2F%40phorque%2FNavigationPlayground-dfc90ac0-5e97-11e8-9603-0a580a780605-signed.apk )

I also made a small test app with Sdk 27 here https://expo.io/@phorque/lol2 (the code can be found here https://github.com/phorque/test-expo-navigation-bug and the APK is here https://exp-shell-app-assets.s3-us-west-1.amazonaws.com/android%2F%40phorque%2Flol2-42cbd554-5ea1-11e8-bb3e-0a580a780305-signed.apk )

### Environment

```
Environment:
  OS: Linux 4.13
  Node: 8.11.1
  Yarn: 1.2.1
  npm: 5.6.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  expo: 26.0.0 => 26.0.0
  react: 16.3.0-alpha.1 => 16.3.0-alpha.1
  react-native: https://github.com/expo/react-native/archive/sdk-26.0.0.tar.gz => 0.54.2

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/phorque-a3331f72-2433-4d7a-8181-8d4487f63e7b.tar.gz
```

The issue occurs on Android standalone app, I couldn't test it on iOS.

### Steps to Reproduce

Every time the application reloads after it was backgrounded the back button always close the app. The best way to reproduce it is to:

* set the background process limits to "No background process" in developper options ;
* open the app (ex NavigationPlayground)
* switch to another app to put the first one in background
* go back to the first app 
* click on a subroute (for example the "Stack example" in NavigationPlayground)
* press the back button.

The process is pretty much the same with my small test app : 

##### Before background

* open the app
* click on profile
* click on the back button
* the app goes back to users

##### After the app is reloaded from background

* click on profile
* click on the back button
* the app closes

### Expected Behavior

I'd expect the app to goes back to the main menu.

### Actual Behavior

The app close and never goes back to the main menu.

### Reproducible Demo

https://expo.io/@phorque/NavigationPlayground and https://expo.io/@phorque/lol2 

```
import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { createStackNavigator, createBottomTabNavigator } from 'react-navigation';

class Users extends React.Component {
  render() {
    return (<Text>Users</Text>)
  }
}

class Profile extends React.Component {
  render() {
    return (<Text>Profile</Text>)
  }
}


const Home = createBottomTabNavigator(
  {
    Users,
    Profile
  }
);

const MainNavigator = createStackNavigator(
  {
    Home,
  }
);

export default MainNavigator;
```

### Stuff I already tried

I tried a lot of stuff x)

* pretty much all combinations of navigators
* setting the `BackHandler` event by hand to make it always return true
* setting the `BackHandler` event in a setInterval and make it always return true so I'm sure I wasn't hijacked by another library (of course react-navigation stops working with this solution, it was just to investigate)
* make the `BackHandler` event of react-navigation always return true
* I tried react-navigation ~1.5 and ~2.0
* I tried with Expo SDK26 and Expo SDK27

Before the application is backgrounded the `BackHandler` events are fired and I can successfully prevent the app from closing at all (it's not the behavior I intended at first, but I was pretty desperate), however if the application reloads after being backgrounded the `BackHandler` doesn't seem to fire at all and the app always close, whatever I do.

AFAIK, all people who tested the app had the same behavior. I also can reproduce this issue in an emulator. Also, the NavigationPlayground on the PlayStore works great, so I'm really confused :c 

Please let me know if you need more explanations or tests from me! Thanks a lot for your great work :3

**Comment by Freeminderus** [comment]
I have same problem, my setup:
react-navigation: 2.0.0
expo: sdk 27
react: 16.3.1
react-native: https://github.com/expo/react-native/archive/sdk-27.0.0.tar.gz

**Comment by brentvatne** [comment]
thanks, I'll look into it

**Comment by ericvicenti** [comment]
Does this issue happen in all expo apps, or just inside of expo "snack"?

I think this may be a special problem with the way Snack works.

**Comment by phorque** [comment]
More stuff, I tried without react-navigation.

```
import React from 'react';
import { View, Text, BackHandler } from 'react-native';

class App extends React.Component {
  componentDidMount() {
    BackHandler.addEventListener('hardwareBackPress', function() {
      return true;
    });
  }

  render() {
    return (
      <View><Text>I'm a text</Text></View>
    )
  }
}

export default App;
```

And I can still reproduce the issue, now it's time to try without Expo.

**Comment by phorque** [comment]
More stuff, I tried without react-navigation.

```
import React from 'react';
import { View, Text, BackHandler } from 'react-native';

class App extends React.Component {
  componentDidMount() {
    BackHandler.addEventListener('hardwareBackPress', function() {
      return true;
    });
  }

  render() {
    return (
      <View><Text>I'm a text</Text></View>
    )
  }
}

export default App;
```

And I can still reproduce the issue, now it's time to try without Expo.

**Comment by brentvatne** [comment]
thanks @phorque - what did you find?

**Comment by phorque** [comment]
@brentvatne I can't reproduce the issue with react-native alone, the BackHandler callback is always called, so I guess it's an expo issue. Maybe I should update my issue on the Expo repository on close this one here, except if you mind having an Expo-related issue here.

**Comment by brentvatne** [comment]
minimal repro:

```js
import React from 'react';
import { View, Text, BackHandler } from 'react-native';

class App extends React.Component {
  componentDidMount() {
    BackHandler.addEventListener('hardwareBackPress', function() {
      return true;
    });
  }

  render() {
    return (
      <View><Text>I'm a text</Text></View>
    )
  }
}

export default App;
```

**Comment by hendra47** [comment]
if you using firebase downgrade to firebase@5.0.3,that work for me.

**Comment by phorque** [comment]
@hendra47 I don't use Firebase but maybe Expo does :o

**Comment by brentvatne** [comment]
expo does not use firebase

**Comment by brentvatne** [comment]
closing this because it's an expo issue and we're tracking it on https://github.com/expo/expo/issues/1786

**Comment by techlando** [comment]
Still a problem
