### ISSUE TITLE
goBack(null) is undefined in Stacks with just one screen

### ISSUE THREAD

**Issue by SaraChicaD** [react-navigation/react-navigation#4332]
### Current Behavior
In StackNavigators, `goBack(null)` will only work if there is more than one screen in the stack. We've been using this to "close" screens and would love to get it back. If you click it in a screen that's a single in a stack, nothing happens or you get an error. If you do the same with multiple stacks, it "closes" or goes back, as expected.

### Expected Behavior
I expect the `goBack(null)` to close the screen you're on, even if there's only one. 

### How to reproduce
See the code [here](https://github.com/react-navigation/react-navigation/issues/4292#issuecomment-391457651).

Here's the [snack](https://snack.expo.io/@sarachicad/back-nav---react-nav-v2).
- If you click on `DoubleStack` and click on `GO TO SCREEN THREE`, you can go back/close that screen by pressing the X — which uses `goBack(null)`
- If you click on `SingleStack` and do the same — click on the X, which uses `goBack(null)` — you get an undefined error. See below.

![screen shot 2018-05-24 at 4 11 50 pm](https://user-images.githubusercontent.com/6945122/40514818-36dd14be-5f70-11e8-9464-0d54c24bffa9.png)

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.0.1
| react-native     | 0.55.3
| node             | 8.9.4
| npm or yarn      | 5.6.0

**Comment by ericvicenti** [comment]
I think the problem, in this case, is that the code calls `goback`, and it needs to be `goBack` with the capital B. If that isn't the only problem, feel free to update the example snack code and re-open this issue.

Also if you're in a switch navigator, the back button doesn't usually make any changes. If you want the back action to take you back to the initial screen within a switchNavigator you can configure it with "backBehavior: 'initialRoute'"

**Comment by SaraChicaD** [comment]
hi there, thanks for that. unfortunately, that doesn't fix the problem. my issue said: "If you click it in a screen that's a single in a stack, nothing happens or you get an error." If i change the capitalization, nothing happens. I'm not using a switch navigator.

**Comment by ashermja** [comment]
As suggested if you add backBehavior: 'initialRoute'

To createDrawerNavigator, DrawerNavigatorConfig, please see my snack below (routes line 105)

https://snack.expo.io/B1IRm9Ak7

It works with a Single screen, however it does not 'goBack' to the Drawer but to the initialScreen i.e. ScreenTwo, maybe you need to do this in combination with openDrawer().

**Comment by ashermja** [comment]
I have been having a similar problem, however in my case using backBehavior: 'initialRoute' has been causing my child navigates to all 'goBack' to the initial route, not to their previous screens, even though I don't have backBehavior: 'initialRoute' on those Navigators. I will post more information when I've done some more testing. (Again this was working ok in version 1.0)

**Comment by karthikpala** [comment]
Hey guys, I'm also facing same issue. We are expecting goBack() to
 1) go to previous screen if there is a screen available
 2) if that is the last screen in the stack, exit the application (like how the android back button behaves)

Was there any update on this issue?

**Comment by SaraChicaD** [comment]
@karthikpala i never heard back from these folks, even after i made the snack. if you find a solution, could you post please? thx.

**Comment by brentvatne** [comment]
hey @SaraChicaD - sorry about that, this appears to be the same issue as https://github.com/react-navigation/react-navigation/issues/4474
