### ISSUE TITLE
Add getLastPosition method to the props of `tabBarComponent` property of the 1st parameter of `createBottomTabNavigator` to enable the real modal tab

### ISSUE THREAD

**Issue by Albert-Gao** [react-navigation/react-navigation#4333]
So I have a bottom tab bar from `createBottomTabNavigator` which works great. Only one problem, one of the tab needs to be a modal.

I found online that you can use a stackNavigator to wrap a tabNavigator to do the trick, it works. But the problem is after you opening that modal screen with setting its `backgroundColor` to `transparent`, the background will be `white` and the previous screen is not underneath. I think it's simply because it's a navigator after all, so the other screen is temporarily not there.

So I try to implement something like this:

1. Don't use that navigator combination, but only `bottomTabNavigator`

2. override the `jumpTo(routeName)` prop in the `tabBarComponent` property, if the `routeName` equals modal screen, then we re-navigate to the current screen with an extra `param`, to let it open a modal on top of itself.

So, now the problem narrows down to how to get the last position when the tab navigation has been triggered, which means, when user is on tab 1 and pressing tab modal, I need to know that the action is starting from tab 1.

I read in one of the [issue](https://github.com/react-navigation/react-navigation/issues/486#issuecomment-334419604), He said there is a `getLastPosition` method which you can use to get the last position.

But it seems that it has been removed from the current version.

Can we add it back? Or am I missing something here?

I'm willing to help if more information could be given.

Maybe @satya164 knows this? :) Thanks

**Comment by brentvatne** [comment]
https://github.com/react-navigation/react-navigation/issues/4390#issuecomment-394505165
