### ISSUE TITLE
drawerLabel not change when localization change

### ISSUE THREAD

**Issue by insaneadinesia** [react-navigation/react-navigation#4335]
Hi there..
I found something with drawerLabel which it not change if I change the localization.
For the localization, I use package from [ReactNativeLocalization](https://github.com/stefalda/ReactNativeLocalization).

Some how, when localization change, the whole language in app change but not the drawerLabel.
Heres some of my implementations code to generate the drawerLabel 
```
const DrawerNavigationOptions = (label, icon) => ({
  drawerLabel: label,
  drawerIcon: ({ tintColor }) => (
    <Image
      source={icon}
      style={{ width: 20, height: 20, tintColor: tintColor }}
      resizeMode='contain'
    />
  ),
})

const MainAppNavigator = createDrawerNavigator({
  homeNav: {
    screen: HomeNavigator,
    navigationOptions: DrawerNavigationOptions(strings.drawer.home, ic_home),
  },
  bookingNav: {
    screen: BookingNavigator,
    navigationOptions: DrawerNavigationOptions(strings.drawer.booking, ic_my_bookings),
  },
  benefitNav: {
    screen: BookingNavigator,
    navigationOptions: DrawerNavigationOptions(strings.drawer.benefit, ic_benefits),
  },
  favoriteNav: {
    screen: BookingNavigator,
    navigationOptions: DrawerNavigationOptions(strings.drawer.favorite, ic_favorite),
  },
  promoNav: {
    screen: BookingNavigator,
    navigationOptions: DrawerNavigationOptions(strings.drawer.promo, ic_promo),
  },
  loyaltyNav: {
    screen: BookingNavigator,
    navigationOptions: DrawerNavigationOptions(strings.drawer.loyalty, ic_tnc),
  },
  faqNav: {
    screen: BookingNavigator,
    navigationOptions: DrawerNavigationOptions(strings.drawer.faq, ic_faq),
  }
},
  {
    contentComponent: props => <MisterDrawer {...props} />,
    initialRouteName: 'homeNav',
    backBehavior: 'initialRoute',
    contentOptions: {
      activeTintColor: orange,
      inactiveTintColor: primary,
      activeBackgroundColor: '#ffffff',
      inactiveBackgroundColor: '#ffffff',
      labelStyle: {
        fontWeight: 'normal',
      },
    }
  });
```

In the localization file, i set like this
```
import LocalizedStrings from 'react-native-localization';

export let strings = new LocalizedStrings({
  en: {
    ...,
    drawer: {
      login: 'Sign In',
      askAssistant: 'Ask Your Personal Assistant',
      credit: 'Credits',
      home: 'Home',
      booking: 'My Bookings',
      benefit: 'Benefits',
      favorite: 'Favorite',
      promo: 'Promo',
      loyalty: 'Loyalty',
      faq: 'FAQs',
      language: 'Language',
    },
  },
  id: {
  ...,
  drawer: {
      login: 'Sign In',
      askAssistant: 'Tanya Asisten Pribadi Anda',
      credit: 'Credit',
      home: 'Beranda',
      booking: 'History Pemesanan',
      benefit: 'Keuntungan',
      favorite: 'Favorit',
      promo: 'Promo',
      loyalty: 'Loyalty Program',
      faq: 'FAQ',
      language: 'Bahasa',
    },
  }
})
```

Is there any solution?

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!

**Comment by Preeternal** [comment]
https://github.com/react-navigation/react-navigation/issues/1274#issuecomment-437475085

**Comment by narithtyty** [comment]
I got the same issue too..

**Comment by jdmueller** [comment]
I have having this issue as well. I am using v3 of react-navigations on expo. My drawerNavigator looks like this:

let AppDrawerNavigator = createDrawerNavigator(
  {
    'Home': {
      screen: HomeStackNavigator,
      params: { siteUrl },
      navigationOptions: { drawerLabel: i18n.t('Home') }
    },
...
I am using the recommended i18n-js module from the Expo docs. It is working correctly on every single screen and everywhere else in the app except the drawerItems. Any insight into a fix for this would be greatly appreciated!

**Comment by pablozandona** [comment]
I got the same issue too..

**Comment by jdmueller** [comment]
I will post on here what I finally found that fixed it:
My main home screen had a stack navigator inside it and this finally got it working.
`
const AppDrawerNavigator = createDrawerNavigator(
  {
    'Home': {
      screen: HomeStackNavigator,
      navigationOptions: ({ navigation, navigationOptions }) => ({
        drawerLabel: i18n.t('Home')
      }),
    },
`
The rest of them that didn't have a stack inside I got working on the individual Component: 
`
static navigationOptions = ({navigation}) => ({
        title: i18n.t('Agents'),
    })
`

**Comment by jdmueller** [comment]
Sorry and this:
`
static navigationOptions = ({navigation}) => ({
        drawerLabel: i18n.t('Find An Agent'),
`

**Comment by Shhzdmrz** [comment]
@jdmueller it is working thank you for this code snippet
BTW how it is even working can you please explain ?

**Comment by LisandroRp** [comment]
> I will post on here what I finally found that fixed it:
> My main home screen had a stack navigator inside it and this finally got it working.
> `const AppDrawerNavigator = createDrawerNavigator( { 'Home': { screen: HomeStackNavigator, navigationOptions: ({ navigation, navigationOptions }) => ({ drawerLabel: i18n.t('Home') }), },`
> The rest of them that didn't have a stack inside I got working on the individual Component:
> `static navigationOptions = ({navigation}) => ({ title: i18n.t('Agents'), })`
> `static navigationOptions = ({navigation}) => ({ drawerLabel: i18n.t('Find An Agent'), ...`

TE AMO BROH, YOU ARE THE BEST. LOVE U :)
