### ISSUE TITLE
hiding statusbar leaves space above header

### ISSUE THREAD

**Issue by udarts** [react-navigation/react-navigation#4336]
### Current Behavior

When I hide the statusbar it leaves an empty space above the header:

![img_3966](https://user-images.githubusercontent.com/11528890/40540418-67f760a6-6018-11e8-9dbe-9f944528e561.jpg)

### Expected Behavior

The space above the header (above the light-blue, circled in red), should be removed.

### How to reproduce

    import React from 'react';
    import { Platform, View, StatusBar } from 'react-native';
    import { Tabs, Drawer } from './config/router';

    const App = () => (
        <View style={{flex:1}}>
            <StatusBar hidden={true} />
            <Drawer />
        </View>
    );

    export default App;`

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.0.1
| react-native     | 0.55.4
| node             | 8.10.0
| npm or yarn      | 5.6.0

**Comment by brentvatne** [comment]
I believe you can do this to fix it:

```
import { SafeAreaView } from 'react-navigation';
SafeAreaView.setStatusBarHeight(0);
```

but we generally don't handle edge cases in status bar layout well at all right now. let's move discussion for this over to https://github.com/react-navigation/rfcs/issues/13

**Comment by udarts** [comment]
Thanks that did the trick.

**Comment by pxmage** [comment]
> I believe you can do this to fix it:
> 
> ```
> import { SafeAreaView } from 'react-navigation';
> SafeAreaView.setStatusBarHeight(0);
> ```
> 
> but we generally don't handle edge cases in status bar layout well at all right now. let's move discussion for this over to [react-navigation/rfcs#13](https://github.com/react-navigation/rfcs/issues/13)

Hey, I got this same problem now, but I found `SafeAreaView.setStatusBarHeight(0);` api has gone.

What is the correct way to do the trick now?

Thank you!
