### ISSUE TITLE
navigation bar in StackNavigator incorrect in Lanscape

### ISSUE THREAD

**Issue by DCRichards** [react-navigation/react-navigation#4338]
### Current Behavior

The title and navigation bar do not respect the correct layout and size when in landscape orientation.

![Nav bar lanscape](https://i.imgur.com/VoI15KM.png)

### Expected Behavior

The navigation bar should be correctly shown below status bar and title not obscured by it.

### How to reproduce

See https://snack.expo.io/S13bk0rym for minimal example, note that Expo does not support rotation with the app... so you might need to use Appetize or create your own locally.

### Your Environment

react-navigation: 2.0.1
react-native: 0.55.3
iPhone 8 simulator
yarn

**Comment by brentvatne** [comment]
the default behavior on ios is to hide the status bar in landscape (apparently iphonex even ignores any setting that you might add to change that: https://stackoverflow.com/questions/46666603/status-bar-in-landscape-for-iphone-x), and we don't currently handle the case where the user explicitly shows the status bar in landscape. this seems like another issue worth discussing in https://github.com/react-navigation/rfcs/issues/13. for now, i'd say just don't show the status bar in landscape.

i added a note to https://github.com/react-navigation/rfcs/issues/13 to discuss further
