### ISSUE TITLE
Drawer lock mode not working after upgrade to react-navigation v2

### ISSUE THREAD

**Issue by DaniAkash** [react-navigation/react-navigation#4341]
I'm trying to disable the swipe gesture which will open the drawer in some of the screens.

### Current Behavior

I have a drawer navigator with multiple stack navigators like this:
```js
const AppNavigator = createDrawerNavigator({
    Home: {
      screen: HomeStack
    },
    Notifications: {
      screen: NotificationStack
    }
})
```

Where in my Home StackNavigator, i have starter screen and home screen:

```js
const HomeStack = createStackNavigator({
    Starter: {
      screen: Starter,
      navigationOptions: { // Using drawer lock mode here...
        drawerLockMode: "locked-closed"
      }
    },
    AppHome: {
      screen: HomeTabs,
      navigationOptions: {
        header: null
      }
    },
});
```

In the starter screen, I don't want the drawer to appear if the user swipes from the left end of the screen. Hence I used:
```js
      navigationOptions: { 
        drawerLockMode: "locked-closed"
      }
```

It used to work well in v1, however after upgrading to v2 this configuration no longer works.

### Expected Behavior

Drawer should not appear when the user swipes from the left edge of the screen in the Starter screen.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.0.1
| react-native     | 0.55.3
| node             | 9.11.1
| npm or yarn      | 1.6.0

**Comment by brentvatne** [comment]
https://reactnavigation.org/docs/en/navigation-options-resolution.html#a-drawer-has-a-stack-inside-of-it-and-you-want-to-lock-the-drawer-on-certain-screens

**Comment by DaniAkash** [comment]
@brentvatne It's same as what i'm doing... I did exactly as mentioned in the documentation but it's not working at all. I can still see the drawer using the gesture...

**Comment by pbandjs** [comment]
I too see no change in swipe behaviour when using "locked-closed" like so:

```
const RootDrawerNavigator = createDrawerNavigator(
  {
    Home: {
      screen: HomeTabNavigator
    }
   },
  {
    drawerPosition: "right",
    navigationOptions: {
      drawerLockMode: "locked-closed"
    }
  }
)
```

**Comment by brentvatne** [comment]
re-create issue with a link to a snack that reproduces this or a runnable example on github. the issue template is pretty clear about this requirement
