### ISSUE TITLE
Firing a function in screen that succeeds the current one

### ISSUE THREAD

**Issue by jskidd3** [react-navigation/react-navigation#4343]
My app has a welcome screen, and when a user presses 'continue' the app then transitions to the setup screen.

The first thing the setup screen does upon mounting is make a fetch to grab some configurable options from the server.

As users sit for a few seconds on the welcome screen, it would make more sense fire this fetch then so that the welcome screen is effectively 'pre-loaded' with the options.

One option would be to make the fetch on the welcome screen and pass the options via props. I don't really like this option though as the fetch isn't really to do with the welcome screen, it's for the setup screen.

Is it possible to 'pre-load' the setup screen, or perhaps fire a function from the welcome screen allowing me to make this fetch before the setup screen is loaded?

**Comment by brentvatne** [comment]
hi there! this is a question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.
