### ISSUE TITLE
iOS segment tabs instead of Material Design tabs?

### ISSUE THREAD

**Issue by booboothefool** [react-navigation/react-navigation#4344]
https://cdn-images-1.medium.com/max/2000/1*ojKHWQt9aUWUlaXg9vvKOg.png

I really like iOS segment tabs over Material Design tabs. I tried out `createMaterialTopTabNavigator` and it works great, but was wondering if there was a recommended way to do the iOS segment tabs style instead, or if it's already implemented and I'm just not seeing it? Thanks.

**Comment by brentvatne** [comment]
this isn't implemented, it would be a great idea for a custom navigator to build and publish to npm! you can post a feature request here if you like https://react-navigation.canny.io/feature-requests but it's unlikely that we will build it as it should be easy enough for someone in the community to do it and maintain it
