### ISSUE TITLE
everything rerender when navigate between screens cause low performance

### ISSUE THREAD

**Issue by jiqimaogou** [react-navigation/react-navigation#4346]
I use react navigation with redux, the root component is this:
```
class App extends React.Component {

  componentDidMount() {
    initializeListeners("root", this.props.nav);
  }

  render() {
    const navigation = navigationPropConstructor(
      this.props.dispatch,
      this.props.nav,
    );
    return <AppNavigator navigation={navigation} />;
  }

}
```

when I navigate between screens, `this.props.nav` change everytime, cause all components rerender, do you have any suggestion like this?

**Comment by mortezaalizadeh** [comment]
I have got the same issue after upgraded react-navigation from V1.15.12 to V2.0.4. The component re-render is causing the relay renderer to re-fetch the data for screens which are not shown anymore. My app is not using navigation params (it is all stored in redux to decouple the app from routing library) and re-rendering components that are not shown on screen dispatches different actions that end up in having the wrong state in my redux. Is there any way to fix this?

**Comment by cbjs** [comment]
same

**Comment by brentvatne** [comment]
hi there!

just wanted to point out this tidbit from the issue template:

> Bugs with react-navigation must be reproducible *without any external libraries that operate on it*. This means that if you are attempting to use Redux or MobX with it and you think you have found a bug, you must be able to reproduce it without Redux or MobX in this report. Redux related issues belong in [react-navigation-redux-helpers](https://github.com/react-navigation/react-navigation-redux-helpers), and we do not have any first-class integration with MobX at the moment.

could you repost this to the redux helpers issue as mentioned above?

**Comment by mortezaalizadeh** [comment]
I do not think it has anything to do with Redux. All screens in react-navigation stack history are getting re-rendered while they are not even shown on the screen. The consequences of having them re-rendered for each could be different. For mine, it is messing with my Redux state, for others is causing performance degradation.

**Comment by cbjs** [comment]
in shouldComponentUpdate, nextProps.navigation is not equal with props.navigation.

and all the functions from mapDispatchToProps also changed.

**Comment by wesleymooiman** [comment]
Solved it. Every time the nav state updates a re-render was triggered this caused the reduxifyNavigator() function to give back a new navigator instance.

```javascript
	render() {
		const {nav, dispatch} = this.props;

		const ReduxifiedNavigator = reduxifyNavigator(this.props.navigator, 'root');

		return (
			<ReduxifiedNavigator state={nav} dispatch={dispatch}/>
		);
	}
```

fix:
```javascript

	constructor(props) {
		super(props);

		this.reduxifiedNavigator = reduxifyNavigator(navigator, worldName);
	}

	render() {
		const {nav, dispatch} = this.props;

		const ReduxifiedNavigator = this.reduxifiedNavigator;

		return (
			<ReduxifiedNavigator state={nav} dispatch={dispatch}/>
		);
	}
```

**Comment by annelorraineuy** [comment]
Thanks @wesleymooiman. This fixed the issue for me, and even fixed another issue where my screen transitions were lost (navigating from screen to screen was instantaneous) prior to your tip!
