### ISSUE TITLE
I have a similar issue on the same line but my issue reads as `undefined is not an object (evaluating 'context._currentValue = currentValue')

### ISSUE THREAD

**Issue by gtsluk** [react-navigation/react-navigation#4348]
package.json
  
"dependencies": {
    "react": "^16.3.1",
    "react-native": "0.54.4",
    "react-navigation": "^2.0.1"
  },
 I upgrade the react-navigation to 2.0.1 

It displays  red screen in IOS simulator. The problem solved by downgrade the react version from 16.3.1. to 16.3.0-rc.0

**Comment by MSSPL-PiyaleeMaiti** [comment]
@gtsluk  I also getting the same error on iOS and also android.  What is the compatibility with react native version and react navigation version? It's should be given in docs.

**Comment by brentvatne** [comment]
previously it has been compatible with most react-native versions but there is a bug in 0.54 with react context: https://github.com/react-navigation/react-navigation/issues/4375
