### ISSUE TITLE
tabBarVisible does not affect nested StackNavigator inside TabNavigator

### ISSUE THREAD

**Issue by jarvisluong** [react-navigation/react-navigation#4350]
### Current Behavior

- I have a nested ```StackNavigator``` inside a ```createBottomTabNavigator``` with one nested screen inside the ```StackNavigator``` has ```navigationOptions``` that set ```tabBarVisible``` to ```false```.

### Expected Behavior

- The nested screen inside ```StackNavigator``` that has ```tabBarVisible``` to ```false``` in ```navigationOptions``` should not show the tabBar

### How to reproduce

Snack: https://snack.expo.io/HJrL-luy7

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.0.4
| expo | 27.0.0

**Comment by itsmeek** [comment]
@jarvisluong https://reactnavigation.org/docs/en/navigation-options-resolution.html#a-tab-navigator-contains-a-stack-and-you-want-to-hide-the-tab-bar-on-specific-screens

**Comment by jarvisluong** [comment]
Could the behavior be the same as in v1? Since I have the setup that there are even nested StackNavigator inside another StackNavigator that using navigation.state.index itself can't fully solve the whole problem?

**Comment by brentvatne** [comment]
the doc that @itsmeek linked to handles the exact problem that you describe. this is also listed as a breaking change in the release notes :)

**Comment by brentvatne** [comment]
if you think the doc doesn't handle your use case then please comment on this thread with more information: https://github.com/react-navigation/rfcs/issues/44
