### ISSUE TITLE
How to dynamically add title when switching tabs?

### ISSUE THREAD

**Issue by ezekel** [react-navigation/react-navigation#4352]
I have 2 tabs and I put inside in `createStackNavigator`

I am using 

***"react-navigation": "^2.0.1",*
 "react-native": "0.55.3",**

```
    const Cstack = createStackNavigator({
        cstack: {
            screen: Screen1,
        }
    },{
        headerMode:'none'
    });
    
    
    const Dstack = createStackNavigator({
        dstack: {
            screen: Screen2,
        },
    },{
        headerMode:'none'
    });
    const mytabnavigator= createTabNavigator({
        Tab1: {
            screen: Cstack,
            navigationOptions: ({navigation}) => ({
                headerTintColor: 'white',
                tabBarIcon: ({focused, tintColor}) => {
                    return (
                        <IconIonicons
                            name='ios-cash'
                            type='ionicon'
                            color="#FFFFFF"
                            size={26}
                        />
                    );
                },
    
            })
        },
        Tab2: {
            screen: Dstack,
            navigationOptions: ({navigation}) => ({
                headerTintColor: 'white',
                tabBarIcon: ({focused, tintColor}) => {
                  
                    return (
                        <IconIonicons
                            name='ios-card'
                            type='ionicon'
                            color="#FFFFFF"
                            size={26}
                        />
                    );
                },
    
            })
        }
    }, {
        tabBarOptions: {
            showIcon: true,
            style: {
                backgroundColor: '#3f51b5',
            },
            inactiveTintColor: '#FFFFFF',
            activeTintColor: "#FFFFFF"
        },
    
    });




    const StackTab = createStackNavigator({
         stacktab: mytabnavigator,
        navigationOptions: ({navigation}) => ({
             title: 'Welcome'
          })
    });
```
My problem is that they both share the same title **Welcome**
how can I dynamically change the title when I switch to other tab example I will switch `tabsettings` then my title would be **Settings**.

I tried to put static navigationOptions in each screen in order to dynamically change but it did not

Screen2.js
```
 static navigationOptions = ({navigations}) =>({
        title:'Hello dynamic here'
    });

```

my expectation that it would dynamically change when I tap on the 2nd tab bar or switch to other tab.
did I miss something ?

Thank you in advance.

**Comment by tharzeez** [comment]
i think, in your screen one add the title not in stack navigator 

const StackTab = createStackNavigator({
         stacktab: mytabnavigator,
        navigationOptions: ({navigation}) => ({
             title: 'Welcome'
          })
    });

remove the navigationOptions from here and paste it in the screen one and check it .

**Comment by ezekel** [comment]
@tharzeez ,

I think that would not work because I declared headerMode:'none'

see

```

const Cstack = createStackNavigator({
        cstack: {
            screen: Screen1,
                //navigatioinOPtions  <- you want to put it here ? but my mode is none
        }
    },{
        headerMode:'none'
    });

``

**Comment by tharzeez** [comment]
And by title did you meant stack navigation title ? . please find the below gif if that is what you are expecting

![ezgif-3-91857cda51](https://user-images.githubusercontent.com/24750567/40588997-c7906610-6203-11e8-94ab-4ac66ab8b1c3.gif)

**Comment by ezekel** [comment]
@tharzeez ,
 yeah that is what I mean I wonder my code doesn't work. I tried your suggestion... I will try it back later to review my code.

**Comment by ezekel** [comment]
@tharzeez 

did you remove the headerMode here
```
 const Cstack = createStackNavigator({
        cstack: {
            screen: Screen1,
        }
    },{
        headerMode:'none' <- did you remove ?
    });
    

```

**Comment by tharzeez** [comment]
const StackTab = createStackNavigator({
         stacktab: mytabnavigator,
        navigationOptions: ({navigation}) => ({
             title: 'Welcome'
          })
    });

In this code you are embedding tab navigator inside stack navigator and giving the title as welcome TO STACK thats why both tab navigation has same title .

i added `header : null `in the StackTab  <- ur Stack Navigation which contains tabs
and in C stack and Dstack, i removed headerMode and added Title there.
One thing that happens here is that now the Cstack  and DStack navigation is inside the tab bar .
So in android if you give tab postion default it will occupy top and navigation title will be below tab bar .
So you can place the tab bar in android at bottom.

Hope this helps .

**Comment by ezekel** [comment]
@tharzeez, but I don't want to put in the bottom my tabbar. I want my tabbar on top and then the title is on top of it.

**Comment by tharzeez** [comment]
@ezekel if thats the case wrap the tab navigation inside stack, and change the title based on the opened tab. You will get the opened tab in navigation object state.

**Comment by ezekel** [comment]
@tharzeez , can you please show me how I am confuse how to apply your suggestion.

Thank you in advance.

**Comment by brentvatne** [comment]
please read https://reactnavigation.org/docs/en/navigation-options-resolution.html - it covers various common situations including this
