### ISSUE TITLE
v2 Android back button closes app when using createSwitchNavigator

### ISSUE THREAD

**Issue by eMatsiyana** [react-navigation/react-navigation#4354]
Please have a look at the code sample here: [https://snack.expo.io/BkyGuF_kQ](https://snack.expo.io/BkyGuF_kQ)

When you navigate to the second route (Other Screen) after signing in to the home screen then click the back button. 
One would expect to go back to the home screen but the whole app closes.

Is this normal navigation behaviour or we need to make the android back button go to the home screen before closing the app.

**Comment by phorque** [comment]
Did you tried to set the `backBehavior` option to `"initialRoute"` ? https://reactnavigation.org/docs/en/switch-navigator.html

**Comment by ericvicenti** [comment]
Yes, this is the behavior of switch router. By default it does not allow you to go back, but you can configure it to go back with the backBehavior option as @phorque mentioned:

```js
const App = createSwitchNavigator({
  ...routeConfigs,
}, {
  backBehavior: 'initialRoute'
});
```
