### ISSUE TITLE
How can i make the custom drawer menu??

### ISSUE THREAD

**Issue by ycman0307** [react-navigation/react-navigation#4355]
I would like to have different sections in a drawer menu. Just like the followings picture.
![66832](https://user-images.githubusercontent.com/13992428/40594982-bf4a9118-6264-11e8-93d2-4f0bd8f3bb48.jpg)

How can i do that??

**Comment by dev4xy** [comment]
+1

**Comment by vikrantnegi** [comment]
You can create a separate component for the sidebar and then use that component for the drawer menu.

Here is how I use a custom drawer menu:

```
import DrawerMenu from "./DrawerMenu";
```
```
const DrawerStack = createDrawerNavigator(
  {
    Home: {
      screen: stackNavigator
    }
  },
  {
    contentComponent: DrawerMenu
  }
);
```
Thanks.

**Comment by dev4xy** [comment]
@vikrantnegi 

Thank you very very much ♥ It was awesome!!!

Can you also put your `DrawerMenu` code here?

I use [react-native-drawer](https://github.com/root-two/react-native-drawer), But I think this is not optimal.
Do you have a better case? (Similar to the question image)

Thanks ♥

**Comment by vikrantnegi** [comment]
Great that it works for you. 
Well I did not required a complicated `Drawer` menu so I just have a simple component. I'm just using a `FlatList` to render items.

I've not used `react-native-drawer`.

Here is the code for my Drawer:
```
class DrawerMenu extends React.Component {
  render() {
    const { navigate } = this.props.navigation;
    return (
      <View style={styles.container}>
        <Profile name="John Doe" email="contact@example.com" />
        <FlatList
          data={menuData}
          keyExtractor={item => item.key.toString()}
          renderItem={({ item }) => (
            <MenuItem
              title={item.name}
              navigation={this.props.navigation}
              screenName={item.screenName}
              icon={item.icon}
            />
          )}
        />

        <MenuItem
          icon="power-settings-new"
          title="Logout"
          logoutUser
          navigation={this.props.navigation}
        />
      </View>
    );
  }
}
```

ScreenShot: 
![drawermenu](https://user-images.githubusercontent.com/3294287/40655044-b1f9b99a-635d-11e8-890c-7b74b3362377.png)

**Comment by dev4xy** [comment]
@vikrantnegi 
Hi ♥, can you answer this question? https://github.com/react-navigation/react-navigation/issues/4384
Thanks.
