### ISSUE TITLE
navigationOptions from nested TabNavigator inside StackNavigator are not respected in v2.0 

### ISSUE THREAD

**Issue by ravirajn22** [react-navigation/react-navigation#4357]
### Current Behavior

```
const RootNavigator = createStackNavigator (
  HomeTabs: HomeTabs,
  Screen1: normalScreen,
  Screen2: normalScreen,
  ....
)

const HomeTabs = createBottomTabNavigator (
  SubTab1: createMaterialTopTabNavigator,
  SubTab2: createMaterialTopTabNavigator
) 
```
i.e Tabs nested inside Tabs nested inside parent Stack.

Previously I used to control the navigation options of the Stack from any deeply nested child, it was smooth and easy to understand once you know how it works.

For example, Say SubTab1 has two tabs, Profile and Rank. I need to change the header button, Title for Profile screen and Rank screen. How do I do it without performing heavy hacks?. 

Now with the changes in v2.0.0, I can't find the solution to this problem. Moreover, it's not a simple change like title, I also change the header, headerRight based on the nested screen. Moreover keeping navigationOptions at screen level is more intuitive then keeping it at the Navigator creation level.

If no easy solution, then as discussed in the RFC can you add the toggle for merging of navigationOptions from the nested child screens?

Kind of similar to these issues but I use nested TabNavigators which is in turn nested inside a StackNavigator,

#4120
#4159 
#4303 
#4310  

### Your  #Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.0.1
| react-native     | 0.55.3

**Comment by ritz078** [comment]
Have you gone through this ? https://reactnavigation.org/docs/en/navigation-options-resolution.html#a-tab-navigator-contains-a-stack-and-you-want-to-hide-the-tab-bar-on-specific-screens

**Comment by brentvatne** [comment]
see @ritz078's suggested link
