### ISSUE TITLE
How Do I Properly write and Import 'Navigator' in React Native 0.55.4?

### ISSUE THREAD

**Issue by Timhargrow** [react-navigation/react-navigation#4358]
I've been stuck on this video at https://www.udemy.com/projects-in-react-native-learn-by-building-real-world-apps/learn/v4/t/lecture/7286310?start=0 and the instructor is using 'Navigator' but I believe this to be an older version. how would I manage to write this code in the current react native v0.55.4?

environment: react-native 0.55.4, npm 6.1.0 etc...

error message: Failed to load bundle (http://localhost: 8081/index.bundle?platform=ios&dev==true&minify=false) with error:(Unable to resolve module 'rebound' from
'/Users/shaquilaparrish/Projects/react-native/BookFinder/react-native-custom-components-master/src/Navigator.js': Module 'rebound' does not exist in the Haste module map.

react-native code ie:

import React, { Component } from 'react';
import {
  Platform,
  StyleSheet,
  Text,
  View,
  AppRegistry,
  Dimensions,

} from 'react-native';
import Toolbar from './app/components/Toolbar/Toolbar';
import Books from './app/components/Books/Books';
import NavigationExperimental from 'react-native-deprecated-custom-components';

export default class bookfinder extends Component {
  renderScene(route, navigator){
    switch(route.id){
      case 'books':
        return(
          <View style={styles.container}>
            <Toolbar />
            <Books navigator={navigator} title="books"/>
          </View>
        )
    }
  }

  render() {
    return (
      <NavigationExperimental.Navigator
        initialRoute={{id: 'books'}}
        renderScene={this.renderScene}
        configureScreen={(route, routeStack) => Navigator.SceneConfigs.FloatFromRight}
      />
    );
  }
}

const styles = StyleSheet.create({
  container: {
    backgroundColor:'#cccccc',
    height: Dimensions.get('window').height
  }
});

AppRegistry.registerComponent('bookfinder', () => bookfinder);

**Comment by Timhargrow** [comment]
@ravirajn22 Thank you, the info on the website is very useful but because my first time around learning the navigator I was learning using a deprecated version, now I'm just stuck on how to translate the information above from the old 'Navigator' to the new 'React-Navigation'. Please help!

**Comment by ravirajn22** [comment]
@Timhargrow I have not used NavigationExperimental, I started directly with react-navigation. I think with little effort you should be able to change the navigation library or create a new project, set up the new navigator and copy over your scene logic. I don't know the best way to do. Also please close this issue.

**Comment by Timhargrow** [comment]
***UPDATE*** To anybody else that runs into this issue, and your not clearly understanding React Native or React Navigation, this is your best place to start. Good Luck! https://www.youtube.com/watch?v=Rl8kSCZoXEk&list=PLy9JCsy2u97nQCTbpC3APx5OlpcPwyaVv&index=2
