### ISSUE TITLE
null is not an object (evaluating 'route.params') while nesting drawer navigator within stack navigator. 

### ISSUE THREAD

**Issue by rbsl-yasmin** [react-navigation/react-navigation#4359]
Both DrawerNavigator and Stacknavigator are working fine. but when I am nesting drawer navigator inside stack navigator there is this error  - "null is not an object (evaluating 'route.params')".
On the other hand when I am nesting stack navigator inside drawer navigator its working fine.
This is all happening in react navigation version 2.

**Comment by rbsl-yasmin** [comment]
Current Situation 
## screenshot
![screenshot_1527500529](https://user-images.githubusercontent.com/20413818/40608689-e823afaa-6289-11e8-9288-d28293483c13.png)

## Code

import React, { Component } from 'react';
import {createStackNavigator, createDrawerNavigator} from 'react-navigation';

import Home from '../screens/Home/index';
import {View,Text,StyleSheet,Platform,TouchableOpacity,Image,StatusBar} from 'react-native';

const stackNavigator = createStackNavigator(
    {
      Home: {
        screen : Home
      }
    },
    {
      initialRouteName: 'Home',
      /* The header config from HomeScreen is now here */
      navigationOptions: {
        headerStyle: {
          backgroundColor: '#f4511e',
        },
        headerTintColor: '#fff',
        headerTitleStyle: {
          fontWeight: 'bold',
        },
      },
    }
);

export default createDrawerNavigator({
  Home: {
    screen: stackNavigator
  }
});

## What I want
Right now drawer and Orange top bar are aligned.  I want the orange top bar to be above the drawer, what should I do to achieve that ?

**Comment by vikrantnegi** [comment]
If you want drawer behind the header you should put drawer stack inside `StackNavigator`.

```
const DrawerStack = createDrawerNavigator(
  {
    Home: {
      screen: Home,
    },
  },
  {
    initialRouteName: 'Home',
    /* The header config from HomeScreen is now here */
    navigationOptions: {
      headerStyle: {
        backgroundColor: '#f4511e',
      },
      headerTintColor: '#fff',
      headerTitleStyle: {
        fontWeight: 'bold',
      },
    },
  },
);

const StackNavigator = createStackNavigator({
  DrawerStack: {
    screen: DrawerStack,
  },
});
```
This should work fine.

**Comment by rbsl-yasmin** [comment]
Yes, It's working! Thanks @vikrantnegi

**Comment by vikrantnegi** [comment]
Happy to help. You are welcome @rbsl-yasmin

**Comment by rbsl-yasmin** [comment]
I used drawerNavigator inside StackNavigator but I can't  access props of drawer navigation such as open drawer and close drawer 
## code
import React, { Component } from 'react';
import {createStackNavigator, createDrawerNavigator, createTabNavigator} from 'react-navigation';

import Home from '../screens/Home/index';
import MustRead from '../screens/MustRead/index';
import {View,Text,StyleSheet,Platform,TouchableOpacity,Image,StatusBar, Icon, Button} from 'react-native';
import SideMenu from '../screens/SideMenu/index';

const Tabs = createTabNavigator({
  Home: Home,
  MustRead: MustRead
})

const Drawer = createDrawerNavigator(
{
  Tabs: {
    screen: Tabs
  }
},{
    contentComponent: SideMenu,
    drawerWidth: 300
});

const StackNavigator = createStackNavigator({
  Drawer: {
    screen: Drawer
  }
},{
  navigationOptions: ({ navigation }) => ({
    title: 'NewsApp',  // Title to appear in status bar
    headerLeft: <Button title="open" onPress={ () => navigation.openDrawer() } />
  })
});

export default StackNavigator;

##error
 undefined is not a function (evaluating 'navigation.openDrawer()')
onPress
    react-navigation.js:69:19

##issue
One more thing is navigation Drawer not close after I click the menu item.
If I remove tab navigator then DrawerNavigator closed. 

what went wrong ?

**Comment by vikrantnegi** [comment]
See if this works:

First import 
```
import { DrawerActions } from 'react-navigation';
```

Then try this:
```
this.props.navigation.dispatch(DrawerActions.openDrawer());
```

**Comment by rbsl-yasmin** [comment]
Again Thank you so much @vikrantnegi! 
React navigation documentation is very poorly written. These things should be mentioned in the Doc.

**Comment by brentvatne** [comment]
@rbsl-yasmin - I tried to make the docs clear but it's not really possible for one person to anticipate every use case, and I'm the main person that works on the docs. please open an issue and describe what you think can be improved in the docs and I'd be happy to try to address it. https://github.com/react-navigation/react-navigation.github.io
