### ISSUE TITLE
getCustomActionCreators is not get called

### ISSUE THREAD

**Issue by Xyzor** [react-navigation/react-navigation#4360]
I was trying to fix an issue where I can't tell the navigator which drawer I'd like to toggle, since in v2 the previous solution isn't working anymore.

I found an alternative for this, [here](https://github.com/react-navigation/react-navigation/issues/1261#issuecomment-387234411)

Unfortunately, for some reason the `getCustomActionCreators` isn't get called.

### Current Behavior

[Demo](https://snack.expo.io/Hy0O2SY1X)

### Expected Behavior

For the getCustomActionCreators to be called.

### How to reproduce

In the demo click on the button with the `Left` title.
It should throw an error `undefined is not a function (evaluating 'navigation.toggleLeftDrawer()')`

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.0.4
| react-native     | 0.55.2
| node             | 8.11.2
| npm or yarn      | npm

**Comment by Xyzor** [comment]
I've checked with the 2.1.0 version, but it seems to me the problem is still unresolved.

[Updated demo](https://snack.expo.io/HyxUy7NgQ)

**Comment by Xyzor** [comment]
I did those changes that @kyo504 did, but on the Drawer navigator. Now it get passed to the drawer routes, but that just the half of the solution.

if the drawer is in a stack, I still can't toggle the drawer from the stacks menu, no matter if I pass the custom actioncreators to the stack or the drawer.

**Comment by ericvicenti** [comment]
Sorry, this was a broken reference in drawerNavigator. I fixed it just now: https://github.com/react-navigation/react-navigation/commit/f92d671746e0d0fb3f9ca5caa56c398d0e546f96

There will be a 2.1.1 release today with this fix included
