### ISSUE TITLE
Loads initial screen instead of last opened screen in Android

### ISSUE THREAD

**Issue by vikrantnegi** [react-navigation/react-navigation#4361]
This issue is on Android caused due to the fix patch of the issue #4196 in react-navigation@2.0.2.
### Current Behavior
After opening the app second time without closing the first instance in android, it loads the intial screen.

### Expected Behavior
It should open the screen which was there when we go to the home without closing the app.

### How to reproduce
Just follow the reproduction method in the issue #4196. It doesn't give any error like in that issue but forces to load the initial screen when it should have load the last opened screen.

### Your Environment
| software         | version
| ---------------- | -------
| react-navigation | 2.0.2
| react-native     | 0.55.2
| node             | 8.9.4
| npm or yarn      | 5.6.0

**Comment by brentvatne** [comment]
this is a bug in react-native and we can't do anything about it. feel free to fix it upstream here: https://github.com/facebook/react-native/issues/19377
