### ISSUE TITLE
[v2] Import side effects causing Android Back Button to close App

### ISSUE THREAD

**Issue by kr31n3r** [react-navigation/react-navigation#4364]
### Current Behavior

e.g. using the following statement causes Android Back Button to close the App:
```javascript
import * as firebase from "firebase"
```
Possibly related to #4354 and #4329.

Using the following import statement instead seems to work as expected in my environment:
```javascript
import firebase from "@firebase/app"
import "firebase/auth"
import "firebase/database"
...
```
Might be Expo and not react-navigation related. 

### Expected Behavior

Android Back Button should navigate back.

### How to reproduce

https://snack.expo.io/@languste/androidbackbutton

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.0.4
| react-native | https://github.com/expo/react-native/archive/sdk-27.0.0.tar.gz
| react | 16.3.1
| expo SDK | 27.0.2
| expo client | 2.5.2

**Comment by Rishi-ubuntu** [comment]
having the same issue

**Comment by brentvatne** [comment]
uhhh.. what is the firebase library doing? can you repro this with any other smaller library that is easier to peek into?

**Comment by ericvicenti** [comment]
Yeah, I think the issue has been properly reported in https://github.com/react-navigation/react-navigation/issues/4329, so we can discuss there.

Next time, please only post issues here about react-navigation and react-native, no external libraries like firebase!

**Comment by faozi07** [comment]
just downgrade using firebase@5.0.3 it's work for me
