### ISSUE TITLE
Redux - AddListener events not firing

### ISSUE THREAD

**Issue by rendomnet** [react-navigation/react-navigation#4365]
### Current Behavior

```
  componentDidMount() {
    this.subs = [
      this.props.navigation.addListener("didFocus", () => console.log("focus")),
      this.props.navigation.addListener("didBlur", () => console.log("blur"))
    ];
  }

  componentWillUnmount() {
    this.subs.forEach(sub => sub.remove());
  }
```

not firing events.

### Expected Behavior

log focus on screen focus
log blur on screen blur

### How to reproduce
I followed example https://github.com/Ashoat/react-navigation/blob/master/examples/ReduxExample/src/navigators/AppNavigator.js

**AppNavigator.js**
...

```
class AppWithNavigationState extends Component {
  static propTypes = {
    dispatch: PropTypes.func.isRequired,
    nav: PropTypes.object.isRequired
  };

  componentDidMount() {
    initializeListeners("root", this.props.nav);
  }

  render() {
    const { dispatch, nav } = this.props;
    const navigation = navigationPropConstructor(dispatch, nav);

    return <AppNavigator navigation={navigation} />;
  }
}

const mapStateToProps = state => ({
  nav: state.nav
});

export default connect(mapStateToProps)(AppWithNavigationState);
```

**redux.js** 
```
import {
  createReactNavigationReduxMiddleware,
  createNavigationPropConstructor
} from "react-navigation-redux-helpers";

const middleware = createReactNavigationReduxMiddleware(
  "root",
  state => state.nav
);
const navigationPropConstructor = createNavigationPropConstructor("root");

export { middleware, navigationPropConstructor };
```

### Your Environment

"react": "16.3.2",
"react-native": "0.55.4",
"react-navigation": "2.0.4",

**Comment by thomasobrien99** [comment]
I also am experiencing this.

**Comment by brentvatne** [comment]
hi there!

just wanted to point out this tidbit from the issue template:

> Bugs with react-navigation must be reproducible *without any external libraries that operate on it*. This means that if you are attempting to use Redux or MobX with it and you think you have found a bug, you must be able to reproduce it without Redux or MobX in this report. Redux related issues belong in [react-navigation-redux-helpers](https://github.com/react-navigation/react-navigation-redux-helpers), and we do not have any first-class integration with MobX at the moment.

could you repost this to the redux helpers issue as mentioned above?

**Comment by psyanite** [comment]
https://github.com/react-navigation/react-navigation-redux-helpers/issues/51

**Comment by flyskywhy** [comment]
https://github.com/shyaniv7/react-navigation/commit/20594229df37a9a08c8a8f117b680498365f1316 mentioned in https://github.com/react-navigation/react-navigation/issues/4670#issuecomment-404299410 works for me.
