### ISSUE TITLE
Re-renders initial route while navigating to another route.

### ISSUE THREAD

**Issue by tusharkhatiwada** [react-navigation/react-navigation#4369]
### Current Behavior

Here's the snack: https://snack.expo.io/@tushark/react-navigation

I've created **2 Stack Routes:** "Stack One and Stack Two" and **1 Drawer Route**: "Drawer One". Initial Route is Stack One. I've an **alert box on componentDidMount of Stack One**. If you _navigate to DrawerOne from StackOne_ and _again to StackTwo from DrawerOne_, the alert box from StackOne pops up. The StackOne screen is being re-rendered while navigating from DrawerOne to StackTwo.

### Expected Behavior

The initial route shouldn't re-render.

### How to reproduce

 [Snack](https://snack.expo.io/@tushark/react-navigation)

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.0.2
| react-native     | 0.55.4
| node             | 8.11.1
| npm or yarn      | yarn: 1.6.0

**Comment by brentvatne** [comment]
search this repo for similar questions and you'll see an answer for why this is
