### ISSUE TITLE
willFocus not called when app is coming from the background

### ISSUE THREAD

**Issue by scientist1642** [react-navigation/react-navigation#4371]
Not sure if it's a bug, but what do you think, should it be added? It's an intuitive behavior of  'WillFocus' for me.

### Current Behavior

- 'WillFocus' of certain navigation does not fire on IOS when app is on background and comes on foreground on that screen.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.5.2
| react-native     | 0.55.3
| node             |
| npm or yarn      |

**Comment by Tomatoo** [comment]
same problem.

**Comment by brentvatne** [comment]
this is intentional, focus events refer to changes in navigation state, and no navigation state has changed here. you need to subscribe to `AppState` if you want this, see react-native docs for more info
