### ISSUE TITLE
createBottomTabNavigator ripple effect

### ISSUE THREAD

**Issue by Futy99** [react-navigation/react-navigation#4372]
Hey guys, is there any way how to add ripple effect to createBottomTabNavigator? I really couldn't find it anywhere.

**Comment by havinhthai** [comment]
+1

**Comment by brentvatne** [comment]
`createMaterialBottomTabNavigator` https://reactnavigation.org/docs/en/material-bottom-tab-navigator.html

but it would be nice to have some option to choose what button component to use on tab bar in normal bottom tab navigator
