### ISSUE TITLE
DrawerNavigator inside the redux is always redrawn

### ISSUE THREAD

**Issue by eeeman1** [react-navigation/react-navigation#4373]
## The issue tracker is reserved for bug reports only.

When the DrawerNavigator is embedded in redux, then any dispatch in the application causes the DrawerNavigator to be repainted, which is why performance is severely affected.

---
the main component is wrapped in redux -

```
           <Provider store={store}>
                <Main/>
            </Provider>
```
settings for the DrawerNavigator -

```
let MainNavigator = DrawerNavigator(
...
contentComponent: props => <Menu items={props}/>
...
)
```
a menu component that will be redrawn each time when somewhere in the application there is a dispatch - 

```
render() {

        console.log('redrawing')

        return (

           <Text/>

       )
```

### Your Environment

| software         | version
| ---------------- | -------
|"react-navigation": "^1.5.9" |
| "react-native": "0.52.0" |
| npm 4.6.1 |

**Comment by eeeman1** [comment]
what is the progress in resolving the issue?

**Comment by brentvatne** [comment]
please read the issue template more closely when filing an issue! :)
