### ISSUE TITLE
StackActions.reset transition problem

### ISSUE THREAD

**Issue by chengxiaodong1** [react-navigation/react-navigation#4374]
![2018-05-30 19_07_28](https://user-images.githubusercontent.com/24641641/40717087-b345f7f6-643d-11e8-94f3-7e703ee48983.gif)

![qq20180530-193349](https://user-images.githubusercontent.com/24641641/40718158-9ef8d0e4-6441-11e8-970b-2c01d662d9c2.png)

### How to reproduce
```
export default createStackNavigator({
  Home1: {
    screen: ({navigation})=>(
      <Text onPress={()=> navigation.navigate('Home2')}>Home Screen 1</Text>
    ),
  },
  Home2: {
    screen: ({navigation})=>(
      <Text onPress={()=> {
        // this is ok
        //navigation.navigate('Home1')
        const resetActions = StackActions.reset({
          index:0,
          actions:[
            NavigationActions.navigate({routeName:'Home1'})
          ],
        });
        navigation.dispatch(resetActions);
      }}>reset to Home Screen1</Text>
    )
  }
})
```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.0.4
| react-native     | 0.55.4

**Comment by brentvatne** [comment]
dup of https://github.com/react-navigation/react-navigation/issues/4178
