### ISSUE TITLE
isMounted(...) is deprecated when use createBottomTabNavigator

### ISSUE THREAD

**Issue by havinhthai** [react-navigation/react-navigation#4378]
### Current Behavior
Every time I navigate to screen, which have Tab created by createBottomTabNavigator, I received this warning:
`Warning: isMounted(...) is deprecated in plain JavaScript React classes. Instead, make sure to clean up subscriptions and pending requests in componentWillUnmount to prevent memory leaks.`

### Expected Behavior
I wish this warning won't appear.

### How to reproduce
I used `YellowBox.ignoreWarnings(['Warning: isMounted(...) is deprecated', 'Module RCTImageLoader']);` but I think It not best way.

### My Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.0.1
| react-native     | 0.55.4
| react    | 16.3.1
| node             |  10.1.0
| yarn      | 1.6.0

**Comment by vikrantnegi** [comment]
Repeated issue #3956.

As mentioned in the original issue:
```
react-navigation does not use isMounted(), this is coming from somewhere inside react-native itself
```

Thanks.

**Comment by havinhthai** [comment]
@vikrantnegi I don't really understand, this problem appear when I use createBottomTabNavigator.
After I remove createBottomTabNavigator or use tabBarComponent property, this warning not appear anymore.

Do you know how to fix this problem?

**Comment by brentvatne** [comment]
> react-navigation does not use isMounted(), this is coming from somewhere inside react-native itself
