### ISSUE TITLE
How to monitor the sidebar(DrawerNavigator) has been opened

### ISSUE THREAD

**Issue by giantss** [react-navigation/react-navigation#4380]
How to monitor the sidebar((DrawerNavigator) ) has been opened?

**Comment by vikrantnegi** [comment]
Did you tried this?
 
https://stackoverflow.com/questions/45122179/how-to-detect-when-the-drawer-is-opened-in-react-navigation

**Comment by giantss** [comment]
thanks. `componentWillReceiveProps` This method will be abandoned in the official new version update log. Is there a better way? i can't seem to find a solution in the docs.

**Comment by brentvatne** [comment]
`static getDerivedStateFromProps`
