### ISSUE TITLE
How to reset route stack and switch tab.

### ISSUE THREAD

**Issue by Tomatoo** [react-navigation/react-navigation#4381]
I create a tabStack (three tab A B C)with `createBottomTabNavigator`. now I am in tab A, and then I push a , b ,c.and then I want rset tabStack A and go to tabB init route, what should I do?

**Comment by vikrantnegi** [comment]
Try using [`NavigationActions`](https://reactnavigation.org/docs/en/navigation-actions.html#docsNav) to reset stacks. 

For Eg. 
```
this.props.navigation.dispatch(
      NavigationActions.reset({
        index: 0,
        actions: [NavigationActions.navigate({ routeName: "HomeScreen" })]
      })
    );
```

**Comment by anhhai680** [comment]
Hi @Tomatoo , I think you need integration Redux with React Navigation to manage Route, State of your app's navigation. You can read more details here: https://reactnavigation.org/docs/en/redux-integration.html

To resolve your issue I think you should try use @vikrantnegi code when you navigated to other screen or use it in Reduce of Redux. For example:

` case CHANGE_TO_OTHER_TAB:
            nextState = AppNavigator.router.getStateForAction(
                NavigationActions.reset({
                    index: 0,
                    actions: [
                        NavigationActions.navigate({ routeName: 'MainStack' }),
                    ]
                }), state
            );
            break;`

**Comment by Tomatoo** [comment]
thanks @anhhai680 . But I do not want to integrate redux or mobx, I want keep it simple, could I do this  only with functions that react-navigation provide?

**Comment by anhhai680** [comment]
Hi @Tomatoo , you can do it easy without integrate redux navigation. You can use @vikrantnegi code on your component. 
For example:
`
onClick = () => {
      this.props.navigation.dispatch(
            NavigationActions.reset({
               index: 0,  //Home screen of Tab A
               actions: [
                   NavigationActions.navigate({ routeName: "SecondScreen" }), //Tab B
              ]
          })
      );
}
`

**Comment by ChrisRyuGS** [comment]
@Tomatoo, I just upgrade 1.5.x to 2.0.4. 
I got error 
_reactNavigation.NavigationActions.reset is not a function....

Is NavigationActions.reset function changed in v2?

**Comment by brentvatne** [comment]
`StackActions.reset`

**Comment by Tomatoo** [comment]
@anhhai680 @vikrantnegi thanks, I have try with `StackActions.reset`, but throw a error, this is [my code](https://snack.expo.io/HkFOg5AJm). is any problem? thanks～

@bartolkaruza please reopen this issue? thanks your time 😄

**Comment by vikrantnegi** [comment]
Hi @Tomatoo 
Check this: https://snack.expo.io/@vikrantnegi/how-to-reset-route-stack-and-switch-tab4381

Let me know if this solves your problem.

**Comment by Tomatoo** [comment]
@vikrantnegi sorry，cannot solve my problem. I want to navigate to tab FeedStack init route from ReportDetail scene, but it navigate to ReportStack init route.😄

**Comment by iMerica** [comment]
Created an RFC to improve this API @ https://github.com/react-navigation/rfcs/issues/50
