### ISSUE TITLE
createMaterialTopTabNavigator the active tab isn't same with indicatorStyle 

### ISSUE THREAD

**Issue by gaopeng0108** [react-navigation/react-navigation#4382]
### Current Behavior
when i use createMaterialTopTabNavigator，this is a question on the platform of ios，
android is normal
![](https://user-gold-cdn.xitu.io/2018/5/31/163b4f0fc1d13baa?w=454&h=772&f=gif&s=1418821)
but on the platform of ios，the active tab isn't same with indicatorStyle 
![](https://user-gold-cdn.xitu.io/2018/5/31/163b4f05b2f89192?w=342&h=606&f=gif&s=1145303)

### Expected Behavior

the active tab is same with indicatorStyle 

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  ^2.0.4
| react-native     | 0.55.4
| node             | 8.10.0
| npm      | 5.6.0

**Comment by anhhai680** [comment]
Hi @gaopeng0108 , please shows me your AppNavigator code. I think this issue relative with AppNavigator to create TabBarBottom.

**Comment by brentvatne** [comment]
please post to https://github.com/react-navigation/react-navigation-tabs and include an example as per @vikrantnegi and @anhhai680's requests :)

**Comment by gaopeng0108** [comment]
@anhhai680 sorry the late reply
```
const HomeTab = createMaterialTopTabNavigator({
  Tab1: HomeScreen,
  Tab2: HomeScreen02,
  Tab3: HomeScreen03,
  Tab4: HomeScreen04,
  Tab5: HomeScreen05,
  Tab6: HomeScreen06,
  Tab7: HomeScreen07,
}, {
  tabBarOptions: {
    scrollEnabled: true,
    labelStyle: {
      fontSize: 12,
    },
    tabStyle: {
      width: Dimensions.get('window').width / 4,
    },
    style: {
      backgroundColor: 'tomato',
    },
    indicatorStyle: {
      backgroundColor: '#fff'
    }
  },
});

HomeTab.navigationOptions = {
  header: null
};

const HomeTabStack = createStackNavigator({
  Home: HomeTab,
  Detail: DetailScreen,
});

export const AppNavigator =  createBottomTabNavigator(
  {
    Home: HomeTabStack,
    Setting: SettingStack,
    Profile: ProfileScreen,
  },
  {
    navigationOptions: ({ navigation }) => ({
      tabBarIcon: ({ focused, tintColor }) => {
        const { routeName } = navigation.state;
        let iconName;
        if (routeName === 'Home') {
          iconName = `ios-information-circle${focused ? '' : '-outline'}`;
        } else if (routeName === 'Setting') {
          iconName = `ios-options${focused ? '' : '-outline'}`;
        } else if (routeName === 'Profile') {
          iconName = `ios-person${focused ? '' : '-outline'}`;
        }

        // You can return any component that you like here! We usually use an
        // icon component from react-native-vector-icons
        return <Ionicons name={iconName} size={25} color={tintColor} />;
      },
    }),
    tabBarOptions: {
      activeTintColor: 'tomato',
      inactiveTintColor: 'gray',
    },
  }
);
```

**Comment by brentvatne** [comment]
@Morriz - see my previous reply

<img width="821" alt="screen shot 2018-12-10 at 10 41 29 pm" src="https://user-images.githubusercontent.com/90494/49782886-c7c67480-fccc-11e8-8fc7-2880e853909a.png">
