### ISSUE TITLE
react-navigation 有没有获取栈的长度的api啊？

### ISSUE THREAD

**Issue by xiao0502** [react-navigation/react-navigation#4383]
因为和IOS手势冲突，需要判断是否是RN入口，想通过路由的栈的长度来判断，找了半天，没发现

**Comment by JarRySW** [comment]
![image](https://user-images.githubusercontent.com/16318164/40778333-65daf4be-6503-11e8-92c9-0ac474d18f97.png)

this.props.navigation.state

超过2个state就是routes

**Comment by xiao0502** [comment]
this.props.navigation.state 只会返回当前的路由信息

**Comment by brentvatne** [comment]
answered in this one https://github.com/react-navigation/react-navigation/issues/4385
