### ISSUE TITLE
Custom Drawer (side-menu)

### ISSUE THREAD

**Issue by dev4xy** [react-navigation/react-navigation#4384]
Hi,

I want use [react-native-drawer](https://github.com/root-two/react-native-drawer) or [react-native-side-menu](https://github.com/react-native-community/react-native-side-menu) or something like this in my own project with react-navigation.

What is your solution for this?

[react-native-router-flux](https://github.com/aksonov/react-native-router-flux) v3, have a way like this : 

```
<SideMenu menu={menu}>
    <Router>
        <Stack key="root">
            <Scene key="login" component={Login} title="Login"/>
            <Scene key="register" component={Register} title="Register"/>
            <Scene key="home" component={Home}/>
        </Stack>
    </Router>
</SideMenu>
```
react-navigation Does not something like this?

Thanks.

**Comment by vikrantnegi** [comment]
Why do you want to use third-party Drawer libraries with react-navigation? 
React navigation provides inbuilt Drawer and also works with custom drawer.

**Comment by dev4xy** [comment]
@vikrantnegi 
React navigation have Overlay Drawer. But i want static or displace drawer. (main content moves)

I want this:
![side-menu](https://user-images.githubusercontent.com/36417203/40789128-e90e3cb2-6506-11e8-9b4a-67e74e7031ad.jpg)

But react navigation have this:

![ree](https://user-images.githubusercontent.com/36417203/40789323-689db0fc-6507-11e8-9134-36c367cb5988.png)

**Comment by brentvatne** [comment]
https://reactnavigation.org/docs/en/custom-navigator-overview.html

**Comment by dev4xy** [comment]
@brentvatne 
Thanks. Excellent!!!

**Comment by mayankbaiswar-CSE** [comment]
@dev4xy did you happen to achieve this? I need to do it too.

**Comment by dev4xy** [comment]
@mayankbaiswar-CSE Yes. You must write custom navigator for this.
 https://reactnavigation.org/docs/en/custom-navigator-overview.html

**Comment by Abdul-Moiz-Lakhani** [comment]
It can also be achieved with the help of two stack navigators, no need of drawer navigator at all, if you want  drawer of react-native-side-menu with react navigation.

I achieved this by:
```
const IntegeratedNavigator = createStackNavigator({
  AppWelcomeScreen: WelcomeScreen,
  SignInScreen: SignInScreen,
  SignUpScreen: SignUpScreen,
},
  {
    initialRouteName: "AppWelcomeScreen"
  }
)

const AppRoutes = createStackNavigator({
  SplashScreen: SplashScreen,
  AppWelcomeScreen: props => {
      
    let SideComponent = createAppContainer(IntegeratedNavigator); 

    return (
      <Drawer {...props}> // SideMenu component from react-native-side-menu <SideMenu menu={menu}>{props.children}</SideMenu>
        <SideComponent />
      </Drawer>
    )
  }
},
  {
    initialRouteName: "SplashScreen",
    defaultNavigationOptions: {
      header: null
    }
  }
)
```
