### ISSUE TITLE
Is there an API for getting the stack length?

### ISSUE THREAD

**Issue by xiao0502** [react-navigation/react-navigation#4385]

**Comment by joshuapinter** [comment]
@xiao0502 Did you ever find out how to do this?

**Comment by xiao0502** [comment]
@joshuapinter  The current solution is to addListener didFocus or didBlur at the entry

**Comment by joshuapinter** [comment]
@xiao0502 What? Are we talking about the same things? 😕

**Comment by brentvatne** [comment]
@joshuapinter - what's the use case? you can do `this.props.navigation.dangerouslyGetParent().routes.length` but there may be a more elegant approach depending on what you're trying to accomplish. can you create a new issue with more info? thanks :)

**Comment by joshuapinter** [comment]
🙋‍♂️ Hi there!

Use case is a custom `BackButton` component that detects when it's at the root of the stack (i.e. no more screens to navigate back to) and calls `BackHandler.exit()` instead of `navigation.goBack()`.

In v1 calling `navigation.goBack()` would return `undefined` when at the root so we could just check for that. 

But with v2, calling `navigation.goBack()` _always_ returns `undefined`.

**Comment by brentvatne** [comment]
created an issue for that https://github.com/react-navigation/react-navigation/issues/4445

**Comment by joshuapinter** [comment]
👍 Nice, thanks!

**Comment by brentvatne** [comment]
@xiao0502 - it sounds like you're not using react-navigation 2.x

**Comment by xiao0502** [comment]
@brentvatne  ok. it's ok

**Comment by agm1984** [comment]
`his.props.navigation.dangerouslyGetParent().routes.length` seems great and all but I don't feel comfortable using it with that name and baking it into the app

I'm having a problem currently where I am using a custom header component and the back button doesn't render or push the custom header over to the right so it can display.

It seems impossible to use a custom header without making a fully controlled custom back button also

**Comment by mbrucher** [comment]
Same here, as navigating a drawer navigator doesn't have native back buttons (only stack does, which is wrong IMHO), there is no simple way of adding functionality that is central to application usability.
