### ISSUE TITLE
Undefined is not a dunction SwitchNavigator error

### ISSUE THREAD

**Issue by safacaki** [react-navigation/react-navigation#4386]
I'm using React Native and create a navigation. But this module gives an "undefined is not a dunction SwitchNavigator" fault. How can i fix?

```
const NonAuthNavigator = StackNavigator(
    {
        Main: { screen: Main },
        Login: { screen: Login },
        Register: { screen: Register },
    },
    {
        initialRouteName: "Main",
        headerMode: "none"
    }
);
const AuthTabNavigator = TabNavigator(
    {
        Home: { screen: Home },
        Camera: { screen: Camera },
        Document: { screen: Document },
        Settings: { screen: Settings },
    },
    {
        initialRouteName: "Home",
        headerMode: "none"
    }
);
const LeftButtonNavigator = StackNavigator(
    {
        Menu: { screen: Menu },
    },
    {
        initialRouteName: "Main",
        headerMode: "none"
    }
);
const AuthMainNavigator = StackNavigator(
    {
        AuthTabNav: { screen: AuthTabNavigator },
        LeftButtonNav: { screen: LeftButtonNavigator }
    },
    {
        initialRouteName: "AuthTabNav",
        headerMode: "none"
    }
);
const AppNavigator = SwitchNavigator(
    {
        NonAuthNav: NonAuthNavigator,
        AuthMainNav: AuthMainNavigator,
    },
    {
        initialRouteName: 'NonAuthNav',
        headerMode: "none"
    }
);
```

<img width="325" alt="ekran resmi 2018-05-31 12 45 04" src="https://user-images.githubusercontent.com/6898758/40775343-7e2f39ae-64d0-11e8-8a58-76695958883e.png">

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.15
| react-native     | expo

**Comment by gyss** [comment]
better upgrade to version 2.0.0, no?

**Comment by safacaki** [comment]
Version 2.0 gived 
`Cannot listen for a key that isn't associated with a Redux store. First call createReactNavigationReduxMiddleware so that we know when to trigger your listener` 
error.

**Comment by brentvatne** [comment]
hi there! this is a question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.
