### ISSUE TITLE
remove shadow under the header 

### ISSUE THREAD

**Issue by zhishanggao** [react-navigation/react-navigation#4388]
![image](https://user-images.githubusercontent.com/16753441/40778604-4eee6028-6504-11e8-9b30-ef80e500481f.png)

i want to remove the line, i use this options but no work, version is 2.0.0
![image](https://user-images.githubusercontent.com/16753441/40778692-b29aefd8-6504-11e8-90eb-3f53f83c569f.png)

**Comment by brentvatne** [comment]
borderBottomWidth: 0

**Comment by zhishanggao** [comment]
@brentvatne thank you my bro
