### ISSUE TITLE
tabBarOnPress, don't have access to previous scene

### ISSUE THREAD

**Issue by martinezguillaume** [react-navigation/react-navigation#4390]
previous issue: https://github.com/react-navigation/react-navigation/issues/4246

### Current Behavior

`tabBarOnPress` callback receives `defaultHandler` and `navigation` in arguments with `createBottomTabNavigator`

### Expected Behavior

`tabBarOnPress` callback should receive `previousScene`, `scene` and `jumpToIndex` in arguments

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^2.0.4

EDIT: I saw that it was replaced by these new arguments, but now, how do we access to the previous scene ?

**Comment by chengkaigithub** [comment]
I have the same problem.
At present, I only find a way to solve this problem.

        tabBarOnPress: ({navigation}) => {
            navigation.dispatch(NavigationActions.navigate({ routeName: navigation.state.routeName }));
        },

**Comment by brentvatne** [comment]
what do you need to know the previous scene for? you can get focused state by calling `navigation.isFocused()`. if this doesn't handle your use case, you can use `dangerouslyGetParent()` like so:

```js
    navigationOptions: {
      tabBarOnPress: ({ navigation, defaultHandler }) => {
        let parentNavigation = navigation.dangerouslyGetParent();
        let prevRoute = parentNavigation.state.routes[parentNavigation.state.index];
        let nextRoute = navigation.state;
        console.log({ prevRoute, nextRoute });
        defaultHandler();
      },
    },
```

**Comment by popo63301** [comment]
Thank you so much @brentvatne ! I've been struggling hours until I found your solutions.
