### ISSUE TITLE
FPS drop to -2 when navigating from StackNavigator to nested TabNavigator

### ISSUE THREAD

**Issue by Futy99** [react-navigation/react-navigation#4391]
Hey, another question. When I navigate from Main stack navigator to nested bottomTab navigator it is terribly slow. It takes at least 1 second. I tried delete everything on screens, simply I let there navigating button. Didn't help, fps droped to -2 in both cases so I guess it is react-navigation bug. Also createMaterialTopTabNavigator animation often freeze when I swipe between screens.

E: Right now I checked my old project which runs react-navigation 1.0.0-beta.27 and everything is fine.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.0.1
| react-native     | 0.55.1
| node             | 9.4.0
| npm or yarn      | 1.6.0

**Comment by brentvatne** [comment]
hi there! this is a question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.

**Comment by ericvicenti** [comment]
I'd be happy to look into this, but you haven't provided a code example. If you post a sample repository or paste an example app into Expo snack, I'll take a look and try to see what is going wrong.

We have a similar example in the Navigation playground, and I havent seen the FPS drop.

**Comment by Futy99** [comment]
So simplified structure on snack https://snack.expo.io/r1eSICpk7 just deleted all content and typescript for better understanding

And there is a whole project https://github.com/Futy99/EIM you can run it on expo app.

If I navigate from my home screen to another simple screen it's fine, probably because it's inside Main stackNavigator in my case. But if I navigate from home screen to tabNavigator, perf monitor shows huge fps drop to -2 as I said.

**Comment by ericvicenti** [comment]
The snack example doesn't run unfortunately, so I haven't seen the bug yet.

**Comment by Futy99** [comment]
So I rewrote it and it works like a charm https://snack.expo.io/rJnn00TkX. I guess problem will be in anything else, I think it might be caused by some package (package json - https://github.com/Futy99/EIM/blob/master/package.json)

**Comment by ericvicenti** [comment]
Let me know if you manage to isolate the issue! Just keep on experimenting until you can tell exactly what causes it 😄

**Comment by Futy99** [comment]
Okey so I find problem, it seems "react-native-svg-charts": "^5.0.0" and "react-native-collapse-view": "^1.0.0", don't go well with react navigation. Removing them helped and it's much smoother.

Unfortunately it was big part of my project :(

**Comment by brentvatne** [comment]
@Futy99 - you could still use those, just experiment with maybe rendering them after the transition is complete. you could do something like `setTimeout` on mount and then render after a second or something

**Comment by Futy99** [comment]
Despite the fact that the application was still a bit slow I made signed apk file and everything works fine. App is fast as I would expect. So probably there is an issue in expo I guess.

Anyway if you have similar issue try to build apk file before you start rebuilding your project. 👍

**Comment by brentvatne** [comment]
@Futy99 - you can disable development mode: https://docs.expo.io/versions/v28.0.0/workflow/development-mode
