### ISSUE TITLE
React-Native-Vector-Icons Installation Issue

### ISSUE THREAD

**Issue by Timhargrow** [react-navigation/react-navigation#4393]
After I install React-Native-Vector-Icons, I'm instructed to restart the terminal and run react-native run-ios. When I run the command I get this message:

Terminal: ** BUILD FAILED **

The following build commands failed:
	PhaseScriptExecution Install\ Third\ Party /Users/shaquilaparrish/Projects/react-native/TabNavigator2/ios/build/Build/Intermediates.noindex/React.build/Debug-iphonesimulator/double-conversion.build/Script-190EE32F1E6A43DE00A8543A.sh
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/TabNavigator2.app
Launching org.reactjs.native.example.TabNavigator2
org.reactjs.native.example.TabNavigator2: 57609

iPhone 6: No bundle URL present.

I have followed the following instructions at https://github.com/oblador/react-native-vector-icons 

Environment: 
react-native v.0.55.4
npm v.6.1.0

here's my code: 
import React, { Component } from 'react';
import {
  Platform,
  StyleSheet,
  Text,
  View
} from 'react-native';
import {createBottomTabNavigator} from 'react-navigation';
import FontAwesome from 'react-native-vector-icons/FontAwesome';
export class Home extends Component {
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>
          Welcome to Home!
        </Text>
      </View>
    );
  }
}
export class Settings extends Component {
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>
          Welcome to Settings!
        </Text>
      </View>
    );
  }
}
export default createBottomTabNavigator({
  Home: {screen: Home,
    navigationOptions:{
      tabBarLabel: 'Home',
      tabBarIcon: ({tintColor}) => (
        <Icon name="ios-home" size={24} />
      )
    }
  },
  Settings: {screen: Settings}

});

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
});

**Comment by brentvatne** [comment]
hi there! this is a question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.
