### ISSUE TITLE
is addListener function supported for react-navigation 1.0.0-beta.7?

### ISSUE THREAD

**Issue by VanessaChu** [react-navigation/react-navigation#4396]
### Current Behavior

called this.props.navigation.addListener('willBlur', this._function()) throws error that addListener is not a function

### Expected Behavior

Should be able to call addListener

### How to reproduce

call this.props.navigation.addListener in componentDidMount

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.7
| react-native     | 0.55.4
| node             | 8.11.2
| npm or yarn      | 6.1.0

**Comment by brentvatne** [comment]
it is not, you should update to a new version of react-navigation
