### ISSUE TITLE
DrawerNavigator inside the redux is always redrawn

### ISSUE THREAD

**Issue by eeeman1** [react-navigation/react-navigation#4397]
## The issue tracker is reserved for bug reports only.

When the DrawerNavigator is embedded in redux, then any dispatch in the application causes the DrawerNavigator to be repainted, which is why performance is severely affected.

---
the main component is wrapped in redux -

```
           <Provider store={store}>
                <Main/>
            </Provider>
```
settings for the DrawerNavigator -

```
let MainNavigator = DrawerNavigator(
...
contentComponent: props => <Menu items={props}/>
...
)
```
a menu component that will be redrawn each time when somewhere in the application there is a dispatch - 

```
render() {

        console.log('redrawing')

        return (

           <Text/>

       )
```
---

### Current Behavior

- What code are you running and what is happening? - described above
- Include a screenshot if it makes sense. - no screenshot required

### Expected Behavior

- What do you expect should be happening? - I expect that when I do dispatch that menu does not redraw
- Include a screenshot if it makes sense. -  no screenshot required

### How to reproduce

- You must provide a way to reproduce the problem. If you are having an issue with your machine or build tools, the issue belongs on another repoistory as that is outside of the scope of Rect Navigation.
- Either re-create the bug on [Snack](https://snack.expo.io) or link to a GitHub repository with code that reproduces the bug.
- Explain how to run the example app and any steps that we need to take to reproduce the issue from the example app. - you just need to wrap the DrawerNavigator in the react-redux (store)

### Your Environment

| software         | version
| ---------------- | -------
|"react-navigation": "^1.5.9" |
| "react-native": "0.52.0" |
| npm 4.6.1 |

**Comment by matthamil** [comment]
Hi! Can you create a reproducible example with [Snack](https://snack.expo.io)?

**Comment by gwl002** [comment]
I think you should use a pure component.Or call componentshouldUpdate in the drawer menu component.
