### ISSUE TITLE
drawerLockMode not working in v2

### ISSUE THREAD

**Issue by Ronnyrr** [react-navigation/react-navigation#4398]
More people start commenting on this issue about the `drawerLockMode` not working on v2 anymore, I thought I start a new issue since there isn't one about v2 yet.  https://github.com/react-navigation/react-navigation/issues/1082

I'm trying to hide the drawer on specific pages.
For example I use the following code as shown in the documentation:
```
  ReservationDetail: {
    screen: ReservationDetail,
    navigationOptions: () => ({
      drawerLockMode: 'locked-open',
    }),
  },
```

In the docs I can only find the DrawerLayoutAndroid spec: https://facebook.github.io/react-native/docs/drawerlayoutandroid.html#drawerlockmode and https://github.com/react-navigation/react-navigation/issues/390 doesn't seem to work.

The expected behaviour is that the drawer won't open when you swipe from the left, but It still unfortunately. You can reproduce using v2.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^2.0.1
| react-native     | ~0.55.2
| node             | v9.11.1
| yarn      | 1.3.2
| epxo | ^27.0.1

**Comment by developer-ocansey** [comment]
Also having the same issue.
similar environment and configuration.
here is my code below.
`const App = createStackNavigator({
    Home: { screen: Start, navigationOptions: { drawerLockMode: 'locked-closed' } },
    Login: { screen: Login },
    Index: { screen: Index },
    Signup:{screen: Signup},
    Offer:{screen:Offer},
    Verify:{screen: Verify},
    successReq:{screen: successReq},
    successBook:{screen:successBook},
    Chat:{screen:Chat},
    Dispute:{screen:Dispute},
  },{ 
    headerMode: 'none',
  });
  const Dwawer = createDrawerNavigator({
    Home: {screen: App},
    Offers: {screen: Offers},
    Inbox: {screen: Inbox},
    MyTrips:{screen:MyTrips},
    Payments:{screen:Payments},
    Settings:{screen:Settings},
  },{
    contentComponent: props => <Sidebar {...props}/>
  });`

**Comment by vm-dezertir** [comment]
In my case works great (https://reactnavigation.org/docs/en/navigation-options-resolution.html#a-drawer-has-a-stack-inside-of-it-and-you-want-to-lock-the-drawer-on-certain-screens)

**Comment by kirillplatonov** [comment]
@vm-dezertir for iOS too? Could you please should example of your code?

**Comment by vm-dezertir** [comment]
@kirillplatonov Also work (i tested on simulator only)
My config - the same like in docs

`const navigationOptions = ({navigation}) => {
	let drawerLockMode = 'unlocked';
	if (navigation.state.index > 0) {
		drawerLockMode = 'locked-closed';
	}

	return {
		drawerLockMode
	};
};

const AppNavigator = createDrawerNavigator({
		Home: {
			screen: HomeStack
		},
.
.
.
})

const HomeStack = createStackNavigator({
		Home: {screen: HomeScreen},
		Stats: {screen: StatsScreen},
	}, {
		initialRouteName: 'Home',
		headerMode: 'none'
	}
);

HomeStack.navigationOptions = navigationOptions;
`

**Comment by developer-ocansey** [comment]
Thanks @vm-dezertir, Example 2 work perfectly for me.

const FeedStack = createStackNavigator({
  FeedHome: FeedScreen,
  /* any other route where you want the drawer to remain available */
  /* keep in mind that it will conflict with the swipe back gesture on ios */
});

const DrawerNavigator = createDrawerNavigator({
  Feed: FeedScreen,
  Profile: ProfileScreen,
});

const HomeStack = createStackNavigator({
  Drawer: DrawerNavigator,
  Details: DetailsScreen,
  /* add routes here where you want the drawer to be locked */
});

const AppNavigator = createSwitchNavigator({
  Auth: AuthScreen,
  Home: HomeStack,
});

**Comment by Maxeh** [comment]
So I got the same issue.

```
const navigationOptions = ({navigation}) => {
let drawerLockMode = 'unlocked';
if (navigation.state.index > 0) {
drawerLockMode = 'locked-closed';
}
```
This code from the docs does not work.

Adding another StackNavigator also does not work for me because I also use "headerMode:none" which makes things a bit more complicated. I just moved back to react-navigation ^1.5.11 where everything works fine when you simply use "drawerLockMode: 'locked-closed'" on each screen you need it. Dont know why this feature was removed in version2.

**Comment by ericvicenti** [comment]
Hey folks, if there is still an issue with the library, can you please open a new issue and include a minimal example of the bug on expo snack?

https://stackoverflow.com/help/mcve

**Comment by balapkm** [comment]
#1082

**Comment by Ronnyrr** [comment]
@ericvicenti done, see https://github.com/react-navigation/react-navigation/issues/4441
