### ISSUE TITLE
Passing custom props from stack to tab navigator

### ISSUE THREAD

**Issue by iremlopsum** [react-navigation/react-navigation#4400]
I'm building out an app and it's nested `createStackNavigator` in `createBottomTabNavigator`. I use a custom tab bar component. To display a corresponding icon to the stack I need to do extra mapping which means that I have to do name depending code, which can go really wrong in an organization.

My current logic of the code

```
const MapStack = createStackNavigator({
  Map: MapScreen
});

const PlacesStack = createStackNavigator({
  Places: PlacesScreen,
});

const ArticlesStack = createStackNavigator({
  Articles: ArticlesScreen,
});

const ProfileStack = createStackNavigator({
  Profile: ProfileScreen,
});

export default createBottomTabNavigator(
  {
    Map: MapStack,
    Places: PlacesStack,
    Articles: ArticlesStack,
    Profile: ProfileStack,
  },
  {
    tabBarComponent: Tabbar
  }
);
```

I would love to be able to to something like this.

```
const MapStack = createStackNavigator({
  Map: {
    screen: MapScreen,
    props: {
      icon: 'Map'
    }
  }
});
```

This way I can define my my tab bar from a single place and don't have to do extra name dependent mapping in the tab bar component which will lead to better code.

Am I missing the place in documentation that this would be possible or is this maybe in the pipeline?

Thanks in advance.

PS! Didn't know where to post this, tried stackOverflow, but no answer from there.

**Comment by mtt87** [comment]
I wanted to help but I don't fully understand what you are trying to do.

I believe you can do something like this
```
    Map: {
      screen: MapScreen,
      navigationOptions: {
        tabBarLabel: 'Map',
        tabBarIcon: ({ tintColor }) => <Icon name="map" size={20} color={tintColor} />,
      },
    },
```

**Comment by iremlopsum** [comment]
Hey,

So, the `navigationOptions` provide an easy way to pass predefined properties (as well, whatever I do I can't seem to receive them in my tab bar). What I want to do is pass custom properties that work with my custom tab bar.

**Comment by iremlopsum** [comment]
@mtt87 Hey, did my extra info help understand the problem?

**Comment by mtt87** [comment]
I'm not sure tbh 😄 
I understand you want to pass a prop, but seems to be a constant, unless you are planning to change your tab bar icons during the app (which seems strange and anti-pattern?)

If it's a constant why do you want to pass it to the component? Can't you just declare it in the component itself?
```js
const MapStack = createStackNavigator({
  Map: {
    screen: MapScreen,
    props: {
      icon: 'Map'
    }
  }
});
```

**Comment by iremlopsum** [comment]
Yeah, the prop is a constant.

So, the reason why I want to define it within the stack is that then the data lives in a single place, otherwise there would have to be mapping icons to stacks (based on screen name or something), this can lead to errors in a large org.

I would much rather define them to be apart of the stack so when the stack data reaches my tabbar I can just render the icon from the data that I got from the stack. This would be a lot less error prone.

To illustrate this, what I currently have to do is

```
const MapStack = createStackNavigator({
  Map: MapScreen
});

export default createBottomTabNavigator(
  {
    Map: MapStack,
  },
  {
    tabBarComponent: Tabbar
  }
);
```

and then either have my icon named the same as the `routeName` or do some mapping like

```
if (routeName === 'Map') icon = 'MapIcon'
```

or I could map this to the index. But no as soon as something needs to be changed in the navigational structure this can break and needs to be dealt with in multiple locations.

It's not that I can't achieve the desired effect visually, but I just want to have less error prone code.

**Comment by mtt87** [comment]
You say you don't wanna end up changing code in multiple location but my first suggestion actually lets you only declare and write this code once and it's also what they show you in the examples
```jsx
    Map: {
      screen: MapScreen,
      navigationOptions: {
        tabBarLabel: 'Map',
        tabBarIcon: ({ tintColor }) => <Icon name="map" size={20} color={tintColor} />,
      },
    },
```
I'm not sure there is a way to pass props but again it doesn't feel natural / good pattern to me.
If you wanna change something related to that tab icon/label you can do it in one place.
If you wanna pass props, then it just makes sense to have them in the screen.

If you are sharing a layout or some elements or the entire page (this case seems impossible to me) you just wrap everything into different components `<MapScreen />` `<AnotherScreen />` and each of them will have their own `tabBar` properties.

You are in fact not writing it more than once, they live in that screen instead of the routes declaration screen.

**Comment by brentvatne** [comment]
thanks for helping out on this @mtt87!
