### ISSUE TITLE
params with nested tabpanel

### ISSUE THREAD

**Issue by venelin-mihaylov** [react-navigation/react-navigation#4401]
### Current Behavior

I am trying to pass a parameter to a route. If the receiving screen is a normal component it works.
However, if the receiving screen is a child tabpanel (created with react-navigation) it does not work

### Expected Behavior

this.props.navigation.state.params should be present

### How to reproduce

https://snack.expo.io/@vmihaylov/params-with-nested-tabpanel

**Comment by brentvatne** [comment]
this is an open discussion and you can weigh in on it here: https://github.com/react-navigation/rfcs/issues/43

in that thread can you explain why you can't just navigate to the screen directly? why do you need to go to the tab route rather than the screen route?
