### ISSUE TITLE
How to set navigationOptions from a Tab nested inside another Tab which in turn nested inside a Stack

### ISSUE THREAD

**Issue by ravirajn22** [react-navigation/react-navigation#4406]
Please forgive me for asking this question again, but I am unable to implement it properly with the way how navigationOptions is resolved in v2.0.0. Moreover you guys have started to lock the issue thread after closing. So I am not able to comment there and forced to open new issue. You could keep it unlocked for getting valid feedbacks or un detected bugs. 

# Current Behavior
```
const RootNavigator = createStackNavigator (
  HomeTabs: HomeTabs,
  Screen1: normalScreen,
  Screen2: normalScreen,
  ....
)

const HomeTabs = createBottomTabNavigator (
  SubTab1: createMaterialTopTabNavigator,
  SubTab2: createMaterialTopTabNavigator
) 
```
i.e Tabs nested inside Tabs nested inside parent Stack.

Previously I used to control the navigation options of the Stack from any deeply nested child, it was smooth and easy to understand once you know how it works.

For example, Say SubTab1 has two tabs, Profile and Rank. I need to change the header button, Title for Profile screen and Rank screen. How do I do it without performing heavy hacks?.

Now with the changes in v2.0.0, I can't find the solution to this problem. Moreover, it's not a simple change like title, I also change the header, headerRight based on the nested screen. Moreover keeping navigationOptions at screen level is more intuitive then keeping it at the Navigator creation level.

If no easy solution, then as discussed in the RFC can you add the toggle for merging of navigationOptions from the nested child screens?

Kind of similar to these issues but I use nested TabNavigators which is in turn nested inside a StackNavigator,

#4120
#4159
#4303
#4310 

I have made a simple snack, here I have solved the problem using your guidlines of Stacks over Tabs from docs. Please go through it and comment if is it the best way for setting navigationOptions for parent navigators.
https://snack.expo.io/BJI1f6klQ

Thanks

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.0.1
| react-native     | 0.55.3

**Comment by brentvatne** [comment]
see: https://reactnavigation.org/docs/en/navigation-options-resolution.html#a-stack-contains-a-tab-navigator-and-you-want-to-set-the-title-on-the-stack-header
jump to "Another option is to re-organize your navigators, such that each tab has its own stack"

**Comment by brentvatne** [comment]
if this doesn't work for you then let me know.

**Comment by ravirajn22** [comment]
@brentvatne Thanks for your reply. But I cannot understand how to set up the navigator with your new functionality.

I have a few problems,

1. How to do it for the below navigator setup,

Root (StackNavigator)
- Login
- Home Tabs (Tab Navigator)
    - Dashboard 
    - Schedule (Tab Navigator)
      - My Schedule
      - All Schedule
    - More
- Profile
- Notification
- Settings

In the above navigator setup, I am able to control the Stack header from 'Dashboard' screen through your guidelines. But How to do from 'My Schedule' screen?. Even handling from 'Dashboard' screen is not easy and complete.

2.  Your second option of changing a Tab screen to own Stack is not intuitive because I just use one screen in the tab.

3. I set headerRight button, which must have access to 'navigation' object. How will that work inside nested navigators?. The right 'navigation' object for the screen cannot be accessed. Hence setParams etc does not work from headerButtons.

4. It feels natural to have all navigationOptions at the screen level.

5. I read through the [RFC](https://github.com/react-navigation/rfcs/blob/master/text/0005-shallow-navigation-options.md) which made this change. But the motivation cases looks easily solved.

6. If you think it can be solved with existing functionality, please add an example how to set up Stack header from deep nested Tabs. 

Thanks...

**Comment by brentvatne** [comment]
> Your second option of changing a Tab screen to own Stack is not intuitive because I just use one screen in the tab.

you can use the first approach then. either works
