### ISSUE TITLE
new screens in react-navigation StackNavigator are pushing under React Native's Modal

### ISSUE THREAD

**Issue by abstruse9** [react-navigation/react-navigation#4407]
### Current Behavior

The react-native `Modal` is the highest zIndex. All the screens pushed onto the StackNavigator by react-navigation are below it.

### Expected Behavior

The new screen should be pushed on top of the react-native `Modal` 

### How to reproduce

Render a react-native `Modal` with some boilerplate code, and then on click button in your custom modal, just run `this.props.navigation.navigate(SCREEN_NAME);`

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  2.0.0-rc.9
| react-native     |  0.55.2

**Comment by brentvatne** [comment]
this isn't going to happen. use the built-in modal stack navigator style if you want that. you can discuss ideal api for modals here https://github.com/react-navigation/rfcs/issues/15
