### ISSUE TITLE
testIDs not working any more

### ISSUE THREAD

**Issue by PvanHengel** [react-navigation/react-navigation#4408]
I want to reference the issue: https://github.com/react-navigation/react-navigation-tabs/pull/26 here since many of use use this library and may not be aware that its since been broken into a few smaller projects.  As a part of that the ability to set testIDs on tabbars has broken.

**Comment by Taylor123** [comment]
Is there an example of the best way to set the `testID` for a Bottom Tab Navigator that has nested Stack Navigators?

Can't seem to get any of the online examples working for 2.2.0

**Comment by brentvatne** [comment]
`tabBarTestID` on navigationOptions?

**Comment by Taylor123** [comment]
@brentvatne Thanks for the quick response! I've tried setting the `tabBarTestID` on navigationOptions, as well as:

```
BottomTabNav.navigationOptions = () => ({
  tabBarTestIDProps: () => ({ testID: 'this-is-my-test-id' }),
});
```

I've tried setting navigationOptions to a static object as well as static method. I'm using [detox](https://github.com/wix/detox) for testing, and it can't seem to pick up the `testID`

**Comment by brentvatne** [comment]
where did you get `tabBarTestIDProps` from?

```
class MyScreen extends React.Component {

 static navigationOptions = {
   tabBarTestID: 'this-is-my-test-id',
 };
  // etc
}
```

**Comment by Taylor123** [comment]
@brentvatne I saw it in some PR from a few months ago, and figured it was worth a shot while I had the time.

I was trying to set the `testID` on the Bottom Navbar itself, in order to test clicking the separate tabs. Your example shows it for an individual screen, but is it possible to set it on individual tabs of the bottom navbar, where each tab is a stack navigator?

**Comment by brentvatne** [comment]
the same way you'd set the icon for the screen

**Comment by MayeuldP** [comment]
Hi Brent ! 
Just have a quick question, I did right in the js file concerning `tabBarTestID` like this 
=>
```
 Projects.navigationOptions = {
  tabBarTestID: 'navigateProject',
  tabBarLabel: I18n.t("Projects"),
  tabBarIcon: ({ tintColor, focused }) =>
      <Image source={Images.tab[`projectsOn`]} />
   header: () => ({
    visible: false
  })
};
```

But how can we access to it in Xcode ? I tried all of this 3, none worked.
   ```
   app.toolbarButtons["navigateProject"].tap()
    app.otherElements["navigateProject"].tap()
    app.buttons["navigateProject"].tap()
```

Thank !

**Comment by limaAniceto** [comment]
I'm afraid this is a matter that persists and should not be closed

Assuming you have a layout such as the following (relatively standard, an auth stack + navigation with bottom tabs):
```
const AppNavigator = createSwitchNavigator(
    {
        AuthLoading: AuthLoadingScreen,
        Auth: {
            screen: AuthStack,
            path: ''
        },
        App: {
            screen: TabNavigator,
            path: ''
        }
    },
    {
        initialRouteName: 'AuthLoading'
    }
);


export const TabNavigator = createStackNavigator(
    {
        Main: {
            path: '',
            screen: createBottomTabNavigator(
                {
                    Home: wrappedByStack(HomeStack),
                    Library: wrappedByStack(LibraryStack)
                },
                {
                    defaultNavigationOptions: ({ navigation }) => ({
                            tabBarTestID: navigation.state.routeName,
                        })
                }
            )
        }
    }
);
``` 

You can see from the screenshot below (taken from xCode debug mode) that the identifier is not defined
![image](https://user-images.githubusercontent.com/2905749/70334641-b3fd1200-183d-11ea-968c-90adc7e29f94.png)

**Comment by robto09** [comment]
Does anyone know how to do it in a setting like this?

```
const TabNavigator = createMaterialTopTabNavigator(
  {
    [routes.FIRST_SCREEN]: FirsScreen,
    [routes.SECOND_SCREEN]: SecondScreen,
    [routes.THIRD_SCREEN]: ThirdScreen,
  },
  {
    initialRouteName: routes.FIRST_SCREEN,
    tabBarOptions,
  },
```
