### ISSUE TITLE
Set default params?

### ISSUE THREAD

**Issue by jeffreymendez1993** [react-navigation/react-navigation#441]
Is there any way to set a default param on the component itself?

**Comment by grabbou** [comment]
See https://reactnavigation.org/docs/navigators/navigation-options, section `Default parameters`

**Comment by jeffreymendez1993** [comment]
@grabbou I do not see this section.

**Comment by grabbou** [comment]
Try Default navigation options 😊

**Comment by jeffreymendez1993** [comment]
@grabbou ` static navigationOptions = {
    state: {
      params: {
        something: false,
        somethingElse: false
      }
    }
  }` did not work.

**Comment by grabbou** [comment]
Ah, sorry. I thought you were talking about navigation options (and its
default values). Do you mean default parameters for a scene? Can you post a
simple code to demonstrate what you want to achieve? That would help me
understand it a bit more.

**Comment by jeffreymendez1993** [comment]
@grabbou  Sure. I want to achieve this but for navigation state params since I have a statement checking to see if the prop has been passed down and set to true and need to default it to false.
<img width="694" alt="screen shot 2017-02-22 at 12 57 59 pm" src="https://cloud.githubusercontent.com/assets/8095978/23225121/c8c06a86-f8fe-11e6-8893-9611be9d4394.png">

**Comment by jeffreymendez1993** [comment]
<img width="372" alt="screen shot 2017-02-22 at 1 00 18 pm" src="https://cloud.githubusercontent.com/assets/8095978/23225160/ebe80064-f8fe-11e6-8bc1-553c62a9eff9.png">
 I would like to be able to set this default value.

**Comment by ddeanto** [comment]
This may be related to https://github.com/react-community/react-navigation/issues/232

**Comment by grabbou** [comment]
@jeffreymendez1993 why wouldn't `const value = params.popToStart || 'defaultValue';` work?

**Comment by jeffreymendez1993** [comment]
@grabbou It would work, but wouldn't you want to be able to setDefault params just how you setDefault props to have a clear vision on what the default to certain things would be. If not I guess that would work for now.

**Comment by thurt** [comment]
as far as I'm aware, you currently cannot set default parameters for a scene/screen. but seems like there is a good argument for adding them

**Comment by jeffreymendez1993** [comment]
@thurt  I think this should be added as for this makes code clean and easy to read.

**Comment by dantman** [comment]
This is especially important for things like the `DrawerNavigator` where routes are not opened by a `navigator.navigate(..., params)` call within the app, but instead are navigated to by the DrawerRouter without any params.

Without default params it's not possible (at least not without fudging things using the routeName) to have a bunch of drawer items with the same screen but different params, like:
```js
DrawerNavigator({
  Inbox: {
    screen: MessageList,
    params: {
      filter: {
        archived: false
      }
    },
  },
  Archives: {
    screen: MessageList,
    params: {
      filter: {
        archived: true
      }
    },
  },
  AllMessages: {
    screen: MessageList,
  },
});

**Comment by jeffreymendez1993** [comment]
@dantman  that would be perfect

**Comment by ntkzwane** [comment]
I share the same sentiments with @dantman, except my scenario involves use of the `TabNavigator`. I see you made reference to #838, however this wouldn't be the cleanest solution in my opinion.

**Comment by 0x5e** [comment]
Same problems with @dantman . Same screen with different params.

**Comment by jiyarong** [comment]
Has the problem been solved?

**Comment by brentvatne** [comment]
hi there! I moved this feature request to canny, as it's our new home for feature requests: https://react-navigation.canny.io/feature-requests/p/set-default-params-in-a-screen-component

issues are now only for bugs

**Comment by brentvatne** [comment]
where you use the param, you can do this:

`this.props.navigation.getParam('name', defaultValueHere)`

**Comment by brentvatne** [comment]
the api that @dantman suggested above was implemented in https://github.com/react-navigation/react-navigation-core/pull/11
