### ISSUE TITLE
Navigator is deprecated and has been removed from this package

### ISSUE THREAD

**Issue by djellalmohamedaniss** [react-navigation/react-navigation#4411]
### Current Behavior
hi , am getting this error since yesterday and i don't really know the problem  , i did not run npm install or yarn add .

i have tried to change my version to the latest one ( react navigation v2 ) and making changes on my code ( like changing stackNavigator to createStackNavigator ) but it does not work also
this is the error that am getting : 
Navigator is deprecated and has been removed from this package. It can now be installed and imported from `react-native-deprecated-custom-components` instead of `react-native`. Learn about alternative navigation solutions at http://facebook.github.io/react-native/docs/navigation.html
    

![screenshot_1528029378](https://user-images.githubusercontent.com/24865594/40886618-5dc1279e-6733-11e8-803d-680c66a6c28b.png)

My Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.5.11
| react-native     | 0.55.3
| node             |  9.11.0
| yarn      | 1.5.1

**Comment by vonovak** [comment]
This is because you're using the legacy navigator: https://facebook.github.io/react-native/docs/0.43/navigator.html

this error is not related to react-navigation

**Comment by gaguevaras** [comment]
I'm seeing the same behavior and I am not using the legacy navigator:

This is the code I'm using to create a StackNavigator:

```
import React from 'react'
import {createStackNavigator} from 'react-navigation';

// import the different screens
import Loading from './Loading'
import SignUp from './SignUp'
import Login from './Login'
import Main from './Main'

export default createStackNavigator({
    Loading,
    SignUp,
    Login,
    Main
},
{
    initialRouteName: 'Loading'
});
```

These are the dependencies I'm using in my package.json file:

```
...
"dependencies": {
    "eslint": "^4.19.1",
    "react": "16.3.1",
    "react-native": "0.55.4",
    "react-navigation": "^2.1.0"
  },
...
```

AFAIK I am not using the legacy navigator but the latest `react-navigation` version's implementation of `StackNavigator`.

**Comment by brentvatne** [comment]
@gaguevaras - you can confirm that there is no mention of this error message or anything to do with the legacy navigator in react-navigation by searching the code. please create a new issue with a repro case on https://snack.expo.io or in a github repo :)

**Comment by rottenoats** [comment]
I got the exact same problem with OP. It was working a second ago and all of a sudden stopped working. The stack trace doesn't help at all. I'm not using legacy navigation, I'm only using react-navigation. I've updated react-navigation to v2 but that still hasn't solved the problem. 

I don't think this is an issue with react-navigation and I'm unsure what I need to do to solve this issue.

**Comment by rh389** [comment]
Check your imports - `import * as RN from "react-native"` will trigger this error because you'll accidentally trip [this guard](https://github.com/facebook/react-native/blob/v0.56.0/Libraries/react-native/react-native-implementation.js#L321).

**Comment by silas13579** [comment]
I was having the same issue as @rottenoats and @gaguevaras. One of my files had `import * as RN from "react-native"` and when I changed that it got fixed. Thanks @rh389!

**Comment by ashlgs** [comment]
Thanks for your solution.
