### ISSUE TITLE
how to reset currentTab RouteStack and then switch tab?

### ISSUE THREAD

**Issue by Tomatoo** [react-navigation/react-navigation#4413]
I create a TabNavigator(Tab ReportStack which contains ReportHome and ReportDetail screen, Tab FeedStack which contains FeedHome and FeedDetail screens).

[this is the code in expo](https://snack.expo.io/BkclDQzl7)

now I am in ReportDetail, I want to clear ReportStack and goto FeedDetail, this is my code:

```
this.props.navigation.popToTop();
this.props.navigation.navigate('FeedStack');
this.props.navigation.navigate('feed/detail');
```

this is little weird，then I use reset function:

```
const resetAction = StackActions.reset({
    index: 1,
    actions: [NavigationActions.navigate({ routeName: 'FeedStack' }), NavigationActions.navigate({routeName: 'feed/detail'})],
});
this.props.navigation.dispatch(resetAction);
```

but is throw a Error:
![2018-06-04 10 47 39](https://user-images.githubusercontent.com/15502063/40896009-2531947e-67e5-11e8-96f7-fd59a7ae67d1.png)

so what should I do? 

thanks😄

**Comment by brentvatne** [comment]
hi there! this is a question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.
