### ISSUE TITLE
confused by createBottomTabNavigator

### ISSUE THREAD

**Issue by Tomatoo** [react-navigation/react-navigation#4414]
I create a TabNavigator(Tab FeedStack with FeedHome and FeedDetail screen, Tab ReportStack with ReportHome and ReportDetail).

[this is demo in expo](https://snack.expo.io/Sycy7NzgQ)
```
const ReportStack = createStackNavigator({
  'report/home': ReportHome,
  'report/detail': ReportDetail
});

const FeedStack = createStackNavigator({
  'feed/home': FeedHome,
  'feed/detail': FeedDetail,
});

const MainStack = createBottomTabNavigator({
  ReportStack,
  FeedStack,
});
```

if I navigate ReportDetail from FeedDetail and then **goback**, I go to FeedHome but not ReportDetail. if I really want to back ReportDetail not FeedHome, I must add ReportDetail to FeedStack's routelist:

from:
```
const ReportStack = createStackNavigator({
  'report/home': ReportHome,
  'report/detail': ReportDetail
});
```
to

```
const ReportStack = createStackNavigator({
  'report/home': ReportHome,
  'report/detail': ReportDetail,
  'feed/detail': FeedDetail, // add this line
});
```

In our real app, there are almost 100 screens, and most page can open in ReportTab and FeedTab, should I add this route to both ReportStack and FeedStack? if yes, may be there are many same code.

is Any suggestions?

Hope I describe my question clearly, thanks.

**Comment by brentvatne** [comment]
if you want the screen to be in the stacks in both tabs, then yes, you should add them to both. you can make some common route object and share it between them

```
const CommonRoutes = {
  'report/home': ReportHome,
  'report/detail': ReportDetail
};

const ReportStack = createStackNavigator({
 ...CommonRoutes,
 // other routes here
});
```
