### ISSUE TITLE
How to set tabBarIcon Animation?

### ISSUE THREAD

**Issue by Darkhorse-Fraternity** [react-navigation/react-navigation#4415]
| software         | version  
| ---------------- | -------
| react-navigation | 2.0.4
| react-native     | 0.53.0
| node             | 9.1.0
| npm or yarn      | npm

How to set tabBarIcon Animation?

my code :

`import Ionicons from 'react-native-vector-icons/Ionicons';

import * as Animatable from 'react-native-animatable';

const AniIonicons = Animatable.createAnimatableComponent(Ionicons);`

![c4d6d055-8007-412c-943f-3f6a9a93493b](https://user-images.githubusercontent.com/5756752/40903758-19b0e2aa-680b-11e8-8425-c191c9b2e808.png)

**Comment by brentvatne** [comment]
https://reactnavigation.org/docs/en/bottom-tab-navigator.html#tabbarbuttoncomponent

eg: https://github.com/react-navigation/react-navigation-tabs/blob/master/example/src/BottomTabs.js#L25
