### ISSUE TITLE
jump to the page and reload data

### ISSUE THREAD

**Issue by suwu150** [react-navigation/react-navigation#4422]
When I jump to the page, I have a total of 3 layers, from layer 1 to layer 2 to layer 3, and then I want to jump to layer 2. After jumping, when I click the back button in the upper left corner, jump directly to me. Layer 1, without jumping to 3, that is to delete the 3 layers in the stack, how to do this??

**Comment by brentvatne** [comment]
hi there! this is a question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.
