### ISSUE TITLE
scrollEnabled no working for bottom tab bar

### ISSUE THREAD

**Issue by MSSPL-PiyaleeMaiti** [react-navigation/react-navigation#4432]
### Current Behavior

- `scrollEnabled: true`  not working for bottom tab bar in iOS only.
- in iOS tab bar labels are overlapping.

### Expected Behavior

- I want scroll tab bar in the bottom tab bar, which is working fine in Android but in iOS not working.
- In iOS I want that scrollable tab bar facility with bottom tab bar.

### How to reproduce

- Example in below link
https://snack.expo.io/BJeoskHxm
Here scroll not working for iOS for specific bottom tabbar.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^1.5.10
| react-native     | 0.54.4
| node             | v6.14.1
| npm or yarn      | 3.10.10

**Comment by brentvatne** [comment]
you need to use `tabBarComponent: TabBarTop` in order to use this on ios on react-navigation 1.5, notice that this option is only available for that component: https://v1.reactnavigation.org/docs/tab-navigator.html#tabbaroptions-for-tabbartop-default-tab-bar-on-android

**Comment by MSSPL-PiyaleeMaiti** [comment]
So @brentvatne I can't use scrollEnable in bottom tabbar. Right?

**Comment by brentvatne** [comment]
you can enable it on a TabBarTop component that is positioned on the bottom

**Comment by MSSPL-PiyaleeMaiti** [comment]
ok @brentvatne thanks for your reply, I'll follow your suggestion and catch you soon.

**Comment by MSSPL-PiyaleeMaiti** [comment]
@brentvatne thanks, it's working. :blush:

**Comment by AbdelhalimAhmed** [comment]
i publish a new article of my solution on Medium , you can see what am doning.
[https://medium.com/@abdelhalim.ahmed95/how-to-create-scrollable-and-dynamic-top-tabsbar-using-react-navigation-17ca52acbc51?fbclid=IwAR3B03f2uyvSPLDUmmMSbYdMelEZkujUJNr_yg9xpMpxtvaghg7wo9u24hc](url)
