### ISSUE TITLE
Why not? please help me.

### ISSUE THREAD

**Issue by pheromone** [react-navigation/react-navigation#4438]
static navigationOptions = {
        header:null
    };

Can't hide  navigation bar?
    "react-native": "0.55.4",
    "react-navigation": "2.2.0"

**Comment by matthamil** [comment]
Hi, please follow the Issue Template. Thanks!

**Comment by elanpang** [comment]
I also met this issue on RN 0.56（0.55.4 works）
set headerStyle={} and header=null in the page works for me
