### ISSUE TITLE
How do you route the same screen from multiple tabs with TabNavigation 

### ISSUE THREAD

**Issue by mypark** [react-navigation/react-navigation#444]
Say I have a standard tab navigation and all the tab screens can navigate into a ProfileScreen.  How should I declare this ProfileScreen in the route?  Should I declare a duplicate route under each tab referencing the same screen, or should I nest it in a parent stack navigation?

If I nest the TabNavigation in a StackNavigation, all the tabs can navigate to the ProfileScreen, but the tab navigation goes away from the screen - and I'd like to keep that tab navigation on screen.

If I nest a ProfileScreen inside a StackNavigation in each Tab, then I get strange behavior if I name the routenames the same in each tab, otherwise I'll have to name the routes with similar names like HomeProfileScreen, PhotosProfileScreen, etc...  It's a bit fragile as any universal component that appears under multiple tabs will have a messy time figuring out which copy of the route to navigate to.

**Comment by grabbou** [comment]
I don't think we have an easy way to push an arbitrary scene without it being declared in a `router`. That indeed makes it a bit cumbersome to declare e.g. `ProfileScreen` so many times.

**Comment by jemmyphan** [comment]
have you found the better approach for this case? @mypark

**Comment by WillyRamirez** [comment]
Any update on this? I'm having the same issue

**Comment by joncursi** [comment]
Same issue here, as per the issue linked above

**Comment by joncursi** [comment]
It's also not just an issue of declaring the same screen with multiple names. If your UI components can render in more than one tab, then your UI components also have to take on more logic to figure out what tab you're in so they can pick the right screen variant to push to. Very very brittle code.

**Comment by kelset** [comment]
To be honest I find it hard to find a case where you may have multiple screens/tabs navigating to a same new screen - and still want to keep the tabbar on the bottom. It sort of creates a "dissonance" in the UX if multiple places lead to the same end... but still sort of different since the tabbar on bottom says you are in the same place :/

That said, if any of you can formulate better as a feature request this feature it would be awesome.

**Comment by joncursi** [comment]
@kelset do you use the Instagram app or Facebook app? I disagree. I think you allow the user to arrive at the destination using whichever route they please, rather than forcing them to use predefined pathways.

**Comment by kelset** [comment]
I do use them both, can you provide me on an example of a navigation that from two different tabs brings you to the exact same "next screen" while keeping the tabbar?

Because as far as I can tell, they implement the solution OP didn't want to go for which is having a nested navigator per each Tab.

That said this is a UX talk, not a feature request. So out of the scope for a GitHub issue.

**Comment by joncursi** [comment]
Facebook, Instagram, Spotify... most of the popular apps that I use utilize this paradigm of being unopinionated on how the user gets to the end destination. Example with screenshots: https://github.com/react-community/react-navigation/issues/2614

**Comment by joncursi** [comment]
If you can show me a code sample on how to achieve this with react navigation, I will be thrillled. But this is UX I want, but haven’t been able to get past the limitations of react navigation in order to implement it

**Comment by kelset** [comment]
As I already said, it looks quite clear to me that they achieve the "paradigm of being unopinionated on how the user gets to the end destination" by using nested navigators per each tab (which is easily provable in Instagram by navigating to a profile, then changing tab, going to another profile, then going back to the original tab).

**Comment by HristoEftimov** [comment]
My routing looks something like this:
```
 main: {
    screen: TabNavigator({
        all: {
            screen: StackNavigator({
                allEvents: { screen: AllEventsScreen },
                details: { screen: EventDetailsScreen },
            }
        },
        upcoming: {
            screen: StackNavigator({
                allUpcoming: { screen: AllUpcomingEventsScreen },
                details: { screen: EventDetailsScreen },
            }
        }
    }),
 }
```
On each tab I am sharing the same screen component with the same key. It works ok for now 😄

**Comment by kelset** [comment]
@HristoEftimov that's an interesting "mixed" approach; you sort of duplicate the `EventDetailsScreen ` screen and keep them in sync, basically, right? 🤔

**Comment by HristoEftimov** [comment]
@kelset yes, that's right 👍

**Comment by brentvatne** [comment]
please create a feature request for this if you think it is important: https://react-navigation.canny.io/feature-requests

**Comment by WillyRamirez** [comment]
@brentvatne  done

Please upvote if you'd like to see this implemented 
https://react-navigation.canny.io/feature-requests/p/route-to-the-same-screen-from-multiple-tabs

**Comment by nthgol** [comment]
@HristoEftimov did you have any issues with having the same key (i.e. navigation confused between tabs?)

**Comment by HristoEftimov** [comment]
@nthgol No, I don't have any problems. To avoid issues with the same key ( tab key ), you can use the following action:
```
const upcomingNavigationAction = NavigationActions.navigate({
    routeName: 'upcoming',
    action: NavigationActions.navigate({
        routeName: 'details',
        params: {
            id: eventId,
        },
    }),
});

this.props.navigation.dispatch(upcomingNavigationAction);
```
