### ISSUE TITLE
drawerLockMode not working in nested navigations

### ISSUE THREAD

**Issue by Ronnyrr** [react-navigation/react-navigation#4441]
In advance of this issue https://github.com/react-navigation/react-navigation/issues/4398 I've created a snack exposing the bug: [https://snack.expo.io/H1rUNwrlX](https://snack.expo.io/H1rUNwrlX)

As you can see in the snack I can't set `drawerLockMode` inside a nested Drawer > Tab > Stack navigator.  Example provided in https://reactnavigation.org/docs/en/navigation-options-resolution.html is used. 

The `console.log` in `ReservationsStack.navigationOptions` is logging `locked-closed`, but nothing happens.

Looking forward to your reply's. Hopefully the snack is clear and this can be fixed ;)

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^2.0.1
| react-native     | ~0.55.2
| node             | v9.11.1
| yarn      | 1.3.2
| epxo | ^27.0.1

**Comment by brentvatne** [comment]
the problem is that this needs to be set on MainTab and not on ReservationsStack.

you have this configured:

```
            +------+ MainTab +----+ ReservationStack
            |
 MainDrawer |
            |
            |
            +------+ Support
```

MainDrawer will only look at its direct children, so MainTab or Support. So you need to set `navigationOptions` on MainTab.

```js
const MainTab = createBottomTabNavigator(
  {
    Reserveringen: { screen: ReservationsStack },
  },
);

MainTab.navigationOptions = ({ navigation }) => {
  let drawerLockMode = 'unlocked';
  let activeRoute = navigation.state.routes[navigation.state.index];
  if (activeRoute.routes && activeRoute.index > 0) {
    drawerLockMode = 'locked-closed';
  }

  console.log('drawerLockMode', drawerLockMode);

  return {
    drawerLockMode,
  };
};
```
https://snack.expo.io/r1zx6nSg7

I thought the doc was pretty clear about only using navigationOptions from direct children but maybe not. Can you suggest how we can improve the doc or do you think you just misread it?

**Comment by Ronnyrr** [comment]
@brentvatne I didn't knew, or read this somewhere. Thanks for your explanation. Where could I've found this in the docs? 

The only line in this doc (https://reactnavigation.org/docs/en/navigation-options-resolution.html) where I could have known it from is:

`If we were to set navigationOptions on the DetailsScreen, they would be configuring the feed stack (its direct parent) and not the drawer.`

But I think it isn't that clear. If you see how many people had the same question I think I could be improved by stating it in that document.

**Comment by brentvatne** [comment]
makes sense. I guess this sentence is kind of hard to understand: ![](http://url.brentvatne.ca/osTrnz.png)

how would you re-word that?

**Comment by Ronnyrr** [comment]
@brentvatne Maybe provide a little example to make it clearer?

"You can only modify navigation options for a navigator it's screen components **that are direct children**. This applies equally to navigators that are nested as screens."

For example, you can't update a  a top level DrawerNavigator it's `navigationOptions` from within a StackNavigation that's inside a TabNavigator (direct child of the DrawerNavigator). You should update the TabNavigator it's `navigationOptions` instead.

Don't know if this is clear to everyone, but it would be to me ;)

**Comment by brentvatne** [comment]
thanks! can you submit a PR to docs to change that? lgtm

**Comment by brentvatne** [comment]
http://github.com/react-navigation/website

**Comment by xxramonxx** [comment]
This solution works for me:
https://reactnavigation.org/docs/en/navigation-options-resolution.html#a-drawer-has-a-stack-inside-of-it-and-you-want-to-lock-the-drawer-on-certain-screens

`
const FeedStack = createStackNavigator({
  FeedHome: FeedScreen,
  Details: DetailsScreen,
});

FeedStack.navigationOptions = ({ navigation }) => {
  let drawerLockMode = 'unlocked';
  if (navigation.state.index > 0) {
    drawerLockMode = 'locked-closed';
  }

  return {
    drawerLockMode,
  };
};

export default FeedStack
`

**Comment by dipo1** [comment]
This worked on react-navigation-drawer 2.5.0

App.js
```javascript
render() {
    const stackNavigator = createStackNavigator({
        home: Homescreen,
        auth: AuthScreen,
        dashboard: DashboardScreen,
        membership: MembershipScreen,
        setting: SettingScreen
    }, {
        initialRouteName: 'home'
    });

    stackNavigator.navigationOptions = ({navigation}) => {
        const lockedScreens = ['home', 'auth'];
        const navigationOptions = lockedScreens.indexOf(navigation.state.routes[navigation.state.index].routeName) === -1 ? 'unlocked' : 'locked-closed'
        return navigationOptions;
    };

    const DrawerNavigator = createDrawerNavigator({
        main: stackNavigator
    }, {
        initialRouteName: 'main'
    });

    const AppContainer = createAppContainer(DrawerNavigator);
    
    return (
        <AppContainer />
    );
}
```
