### ISSUE TITLE
Drawer Stuck Open when Tapping Drawer Item Quickly (while drawer animates)

### ISSUE THREAD

**Issue by solomonhawk** [react-navigation/react-navigation#4444]
Note: I have a PR that covers a simple fix for this: #4443 

### Current Behavior

I simply have a drawer that I toggle with `navigation.toggleDrawer()` and a custom drawer component that doesn't do anything special except render some stuff at the bottom of the sidebar. After updating to get the fix in #4392 which fixes a terrible infinite loop scenario, I noticed that when I open the drawer and then quickly tap a drawer item before the drawer finishes animating open that the navigation occurs correctly but the drawer remains open. Furthermore, once this has occurred, no subsequent taps on other drawer items will cause the drawer to close. The navigation actions do happen and I can see the screen changing (underneath the drawer underlay) but the drawer itself remains open.

### Expected Behavior

I believe that the drawer should allow users to navigate to screens by quickly tapping on a drawer item, even while it is still animating.

### How to reproduce

I'd like to create a Snack to repro this but I'm crunching on some work so I'll try to append that later on.

The repo should be simple - just set up a drawer navigator with some screens inside. Observe that when you open the drawer and quickly tap on a drawer item that the navigation correctly occurs but the drawer gets stuck open and will not close until you tap on the underlay (outside the drawer).

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.2.0
| react-native     | 0.53.0
| node             | 8.9.4
| npm or yarn      | yarn 1.7.0

**Comment by brentvatne** [comment]
thanks for the PR! fixed in 2.2.2
