### ISSUE TITLE
navigation.goBack() always returns undefined

### ISSUE THREAD

**Issue by brentvatne** [react-navigation/react-navigation#4445]
> In v1 we could just check the return value of navigation.goBack() because it was undefined only when at the root of the StackNavigation. In v2, this is no longer the case, it returns undefined always.

from https://github.com/react-navigation/react-navigation/issues/3349#issuecomment-394097826

**Comment by joshuapinter** [comment]
👍 Nice job! Thanks!

**Comment by brentvatne** [comment]
released 2.2.3 with the fix

**Comment by joshuapinter** [comment]
Works a treat! 🍭 

Thanks, Brent! 🙏
