### ISSUE TITLE
Docs Broken

### ISSUE THREAD

**Issue by TylerSustare** [react-navigation/react-navigation#4447]
In the 'Summary' section of the documentation on this page https://reactnavigation.org/docs/en/hello-react-navigation.html takes me here https://snack.expo.io/@react-navigation/hello-react-navigation-v2. When attempting to run it to see the two nav elements working together I'm getting the error 
```
Device: (159:22) Attempted to import missing module 'react-navigation'
```

**Comment by brentvatne** [comment]
hi! not sure what happened there - when i typed something in the editor the error went away. i updated it and it appears to work properly now. i also alerted the maintainer of snack and he is investigating. thanks for the report!
