### ISSUE TITLE
Nesting a carousel inside a TabNavigator on iOS.

### ISSUE THREAD

**Issue by burakkarakaya** [react-navigation/react-navigation#4454]
I am trying to use a carousel inside a TabNavigator. The problem is on iOS when I slide the carousel the tab navigator is also sliding. Tried to use the callback function from the carousel to set the parent tabNavigator swipeEnabled property to false. and then back to true when the touch is terminated but it didn’t work.
Do you have any suggestions. Many Thanks!

**Comment by brentvatne** [comment]
you should disable scrolling for the tab navigator.

also, his is a question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.
