### ISSUE TITLE
Transitioner doesn't animate View out

### ISSUE THREAD

**Issue by MrLoh** [react-navigation/react-navigation#4457]
### Current Behavior

I just encountered a super strange behaviour in Transitioner that took me a whole day to figure out. 

I am building a custom Navigator and my Transitioner wasn't behaving as expected, it just wouldn't animate out the Element, but it would disappear without an Animation. 

### Expected Behavior

The Transitioner should keep the element around and only remove it after the animation has finished. 

### Source of the Issue

I found that the responsible code is located in the Transitioner check for wether the index has actually changed, because somehow the Animated values `__getValue` function doesn't work properly for native animations.

https://github.com/react-navigation/react-navigation/blob/b68c3a755dc1f7c681848833175b32f50d590cc7/src/views/Transitioner.js#L130-L142

I found this strange code with a comment in the `StackViewLayout` where everything is working properly. But `_animatedSubscribe` isn't ever called so I am not sure what is going on. 

https://github.com/react-navigation/react-navigation/blob/b68c3a755dc1f7c681848833175b32f50d590cc7/src/views/StackView/StackViewLayout.js#L134-L145

When I do a `transitionProps.position.addListener(() => {})` in the component, the index value actually changes to 1 and the Modal animates out. But this just works on the first

### How to reproduce

The following Snach reproduces the issue. The interesting code all lives inside the `ModalNavigator.js` file: 
https://snack.expo.io/@mrloh/transitioner-issues

In my own debugging I added some `console.logs` in the `Transitioner` inside the react-navigation lib in my node modules. If you add 

`console.log(' animation finished at position', this.state.position.__getValue())` in the finished callback of `Animation.parallel.start` in line 181 of Transitioner you can see that the Value somehow stays at 0, which is causing the issue at the next rerendering. 

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.2.3
| react-native     | 0.55.4
| react             |  16.3.1

**Comment by MrLoh** [comment]
If someone can help me figure out what's going on here. I'd be happy to create a PR with a fix. But whoever wrote the code and has a really deep knowledge of Animated would probably have to give me a pointer what's going on.

**Comment by MrLoh** [comment]
It seems that when I add a listener in `onTransitionStart` and then remove it in `onTransitionEnd` the animation always works.

```js
<Transitioner
  render={this._render}
  configureTransition={this._configureTransition}
  navigation={this.props.navigation}
  descriptors={this.props.descriptors}
  onTransitionStart={(transitionProps) => {
    this.transitionListener = transitionProps.position.addListener(() => {})
  }}
  onTransitionEnd={(transitionProps) => {
    transitionProps.position.removeListener(this.transitionListener)
  }}
/>

**Comment by brentvatne** [comment]
cc @ericvicenti

**Comment by brentvatne** [comment]
transitioner rewrite still start soon, not going to look at this until then sorry

**Comment by MrLoh** [comment]
Sure no hurry, I have a workaround for me. 

It might just make sense to understand what's going on here before rewriting, as this error is clearly caused by a missunderstanding about how transitioner works, as events are simply not all bubbled up to the js thread, if there is no scubsciption to the native event.

**Comment by fjcaetano** [comment]
Any news on this? I'm having the same issue and there's no functioning example on how to work with the Transitioner for the current version of `react-navigation`

**Comment by satya164** [comment]
I'd suggest to implement your own logic for managing transitions in your custom navigator. `Transitioner` has been removed from stack.

**Comment by fjcaetano** [comment]
Yes, we have our own animation logic, but it's really hard to do that since the documentation is very limited and there's no example on how to do it.

**Comment by satya164** [comment]
What kind of documentation you're looking for?

It's your own navigator, so I think it's upto your code to handle animations for state changes. We do the same for all of our recent navigators, none use `Transitioner`.

**Comment by fjcaetano** [comment]
We're currently using v3.11 and we have a few custom transitions between screens, but it's really hard figuring out how to achieve that without any guidance and with the current documentation.

We went with the `Transitioner` approach, because that's how it used to be done (I had no idea `Transitioner` was deprecated/obsolete). The current react-navigation documentation does not indicate how to handle custom transitions and it may actually be misleading, since there's still references to `Transitioner`. Also, I couldn't find any examples on how to implement a custom transition. If you have any references, it'd be much appreciated.

I'm not trying to point fingers nor do I want to be too harsh on criticizing anything, because I think you guys do an amazing work and I'm thankful for your open source contribution, but I believe there's still room for improvement in regards of documenting guides and API reference for this package. ❤️

**Comment by satya164** [comment]
I mean, if you have a custom navigator, you're on your own regarding implementing animation. `Transitioner` is how stack v1 implements its animation, all other navigators implement animations their own way. With custom navigators, you're in charge of rendering the components, so it's upto you on how do you want to handle animations for state changes and how you approach it, which libraries you use for animation etc.

If you use the built-in stack navigator, you can find some articles which show you examples on how to implement animations.

For stack v1: https://dev.to/kris/custom-react-navigation-transition-implementation-and-demo-d1m

For stack v2: https://callstack.com/blog/custom-screen-transitions-in-react-navigation/
