### ISSUE TITLE
onTransitionEnd is not triggered

### ISSUE THREAD

**Issue by ensecoz** [react-navigation/react-navigation#4458]
onTransitionEnd is not triggered properly. I'll create PR to fix this. The problem is that it extract wrong property name from the props.

```
createStackNavigator(
  {
    HomeScreen: { screen: HomeScreen },
    DetailScreen: { screen: DetailScreen }
  },
  {
    onTransitionEnd: () => console.log('ended')
  }
);
```

**Comment by brentvatne** [comment]
merged your pr #4459 which fixed this and released in react-navigation@2.2.5
