### ISSUE TITLE
[Flow] Issue with NavigationRouteConfig

### ISSUE THREAD

**Issue by angly-cat** [react-navigation/react-navigation#4461]
Hi!

In my app I wrap all routes' screens with some custom HOCs for some purpose. To do that properly, in my code I check how a route is set (with `screen`, with `getScreen` or with short-hand syntax).

Despite it working as is, flow produces scary errors, which I don't know how to handle.

Basically, my problem can be reduced to [this snippet](https://flow.org/try/#0PTAEAEDMBsHsHcBQjgCpWNK0AxAlgE4DOALgDSgCGoARgK4B2AxgBaiySgkt4MDmRUPACmQ2HWgATUHABuokrFB4AtgAdYBErTrbepYZWkq6pTNgLCmsBqQJ0m2gBQrYpaAE9Q1tR4C0apQGkgCUAHTmwMggoAAqPIJ4gtQ0QSSUBJJ4AF6UJHg27JzcCvaiAMokHtDCAPI0AFZcHmqicEx5wtK8KGCWlI5+DHl48sAAMng0BBl4wkTAldXC5SzCwiSLVTWr6ySxLfNhoADqooyQmiSMnZ7elAwA5CS9yupXXCx5oGuWFA-dEiPQSKJQ1fjcLxOAHeGxEYQARzowgYJDuoNoBDwJDRwhCXFgrx8-kCBh+wksoGE2N+ESqrVASxq9SaAF5MKAAD6gBgSaAc7myWB4SQCnl0FQ0CliyCUaDwsWPR5igAkACVDJJagxPABBAgzDwAHiZdUaAD4xQBvUAAbWGKmEAC5QHZeHwALouh5eAC+AG5EPTRAA1ObwU0ABQIsDUoFZjO2ZoageDcWEAA8SFGY3GE6aWanDqBdQxVJ1JGHhBGk9HY-HE8tC0Hi6XyyQurFM9na7mGwXGoHXvEkspBD45tJIDGVJ9RONKB5xNo0z0Yv1BsN8vI-OkaH5ZOHgEQCExgLFKDQq-ADq0ACLCSC8bEFWwthkXq-hhdL3QNq0cmseB8CwJAurykoUmQHLwCK3DgRKUoENBAbRGAI6JOOsaTqA06wLOG4kEMIxjJM0yzPMwAAJIqJQfDCNRtH0eU4insIYQNEQ76iDRdHCAAqmqVEsXQbH-hyol4AA-C6br8NBoA6Awkg1DJrokFi8kco63CwJIalyXwCnkkYFJEGpLJWOQHI0HpHgGRp7rGR0rDCGpjySI+lASECXKgI8lhwEYjx+Y8lxsX4LlrCF3KPDYnh+HgkCRQMaySI8xmwZI3BqRBSHGUBIEkLliFQRyRAdKpCGQchiCoWmvHMaxTCiAmjUCUJIlidyeUUn5+qGka7WCcJzXCOaQ4xBh7AMKIo4YtAGT0QSsK+McuqOHQcqgJ5T5lvkhSjmufSGJuJEMWRMxYpRba0R2kjHqewAMHpN1lndXQhnKyIcVxaa3RWX3QMiDaWY4Q5pgAEpqFI4JoLVUbYGziYpLCaDkNjpNADmaUZHLyFoeCVTjTkcjUkDFbJjlaYpWJFSTNMEmoDN44ptk4vhLMoZN6DmKAABy3b-NA0Bzs0DKeUwi0zAdb5YFEKC81gAuUIefAjIUlSdKAADUJaOK+kTIJmGhaOLoj86rwEawwkYZJQKiCAmAGKbaADWwgeFTuNeqAKh4BmXTc8bGamyuxaW2rNsAEIDG7G2y-+nIcsGLqPJH1uy8A0e6gAwgA0hlHIe-ZLpSYZ0GcqhJsfGmGfq7LiPYgnr5Jynhxp-XNvUfzVGxEXimBDMjtqV3st28PRCV9Xoe1xHVsN6+Y-CC3hTO8nimp-5Y+vsA-O6iGVEAOK6rEACiA+gDGujCJbjre6Tg-2yPLo7zYE8O1PyCKVNaxUAbhRFBX0YMoWwIoFB-yIHQfc18OwEA5AMWWo8F422XqvBg0Fi6ey5ogKugYa5mzrig2W5QNgf0dugtum8O7b2IbvcoZ9YgAH1Iy6jVLqAAsuUIuHJf6iBLkUMWsDRDwF+BA0QQ9P6ujRhIaQUpXQbCwV7dSuNME-3Qn-Wa8BQCSMditR0BBlq8CASUKkGYkj5H4FfZcEjn5cSfpPV+dD352OnkOAh4cGRv1trGSh68OQ6y3unZxDBgCRlqJGS+OsGAlRqsZHWqhHRZE6GpWysAagPDcYgDx5sVZR3HrGWIsAilqD8aAK0G9dZBO8WEiJTDYi1HqREqJiSuh4BSS6NJGSMG4JnmHXJ3jIymBYGUipATqkhLCfxcokMonCLvs6FRj9da6PMk4-Jr5yFf0UjrRBr5kEbJsGggBPSdklxwXg7Js9CHz0OQwDU8ISCjMqRMu5wA1RnwYf3YyvBPIZmqvlJRaly7U1Zv-WWRAXQDUXEabxxzZbmiyTkohdyNRqEWi1Z54yaHBLeR8yM4w84X3iSXB+jMdbzIdosiuATVkHMzps1xAS9k2HpYvI5xCV4nKRdczxFsQm53wuijYwhYgzDAbLLFOzXkMpsMAXOtQOEEsYWfep7D+blD7lRWo-MonnLJXjS5Vz+kotlQwWorQGB3hmCIAgUqqk4pqREs+-MmF3nYScM+ao9XYINTyk1tyzW5zgPCa1lBbX2sCY6yZudxi1AYW6j1XqfWlyWVpS5yLA3soYEUvgfAahhojScqhDrWid0mQ0o+R9xiqvdbqT13qSW+rTYa1Cxq55eJCX4sU3jY5MHjicntISm5PMHYpbkcLOXoKHXc0hJAtnTvHXks1kZfFjr8oMwpxS12yxnSu4Zi6N0hIeRsQ9E7j3CHRQMLlu6l3eMFeoGoHYxUPCIC+GwZ7l3ZotSiQtFJP33pDcIP9dr13nrubm-NwGbX-pOTzDAytvFaw7GOKgXBLCiA4NYm+ghwpobffwGoPJiGaAoKIikohTosD5qwPAUhsModol4akJQCC0FENQJDTAMP3JsewNjlA+beLVDYggImb7HC4zx8TKHLBqEsPCVEyQZCGE4BVHjClsCiLo+Ir9NsZMUgM1fS9CmUQkBBJA9IKGsPUFo-R4Y+TNARCwEJ2o591lmuQ3NZTpBtYaXWDIWAlUVrUAI1B4jjmBPKT5ticcPB7MkeIKAJwh5qCmOEbhuYUhwh8yopwEQAU5oMAi5nTQPJ5j3R2usOM+hwFi0oGoNQFBTG+ZQ7BEWM07hSj5i1qzog8PcG+A50rBBnPYHiKIVr-WyvpdgLAbQw2G5law6xKgjXjPyfmGZizIi0ZEcWzbPmU3cIzb-qI9JHHGtjaiJmzts6+so1AGgBDilsCIz+cZyAZkVqmL2fIbw8XpDCNAUImxyQDSLmc69qIilfmZgBWVWmYOoUQ+NMJmxiK6ruN5QM49fH2R3pCeMVTBm93Zq8wZ7HAa7tmuJ5QSARnna8KVq90AGpEHAlAAI0wXRaBeCIPhUQB3FDEEk0oWavOgFEFaEwJKXgSjwj9g8LaIsPDGWViULw7XRbyN2rwXnNB5d-2EaNjk8slF+uZy95WcM2OZgdsK-ykNBePCh8raao4efSCCGhgRvA0PA+sAwJ8fAhBrGK9xwwljQ-UGF05s3qAYcMdvlSy3P8WfKzttwVDDwqCSFkA8FqU4o+iXOPCKcZXPKXpkLwN27oqDKRmmLEQNA3eJ45IEHKaensZ+wFsnRQRy8-YSMnsPKISuLysUA7E6vsDsT4McAABjaDoBAmEihdAARgAEwAGZQC+kXyD6gwPBvaCyNLxaHhlOr7b0nulHns1bODu2m5NPyd9cZ3p2WdOGd8YAGQchIZ9bwZ8wGbwLm6v58rf6vjlCR4ogWoQpHwbBwJGiIGviQrlK+jmgNhOAcjC6viP42xwE8Z1hqCwp443yY6KTqbrC2y5hrJYGID4isg4HoFwhU4dr8qoqiYmh9ZEEkJ9YUDsG2AuhWjYGPbPYJ5xDG5dAOB9Rn7sC6BqC6A7blbaIEGFDHZ4bUB8CjDj4sqnKs6wTZ656xiyzbSbaHjiCCBTbHAnDh71bFqjhB5vqeSWDSBfDKQ1CiiKTKz0AriWbaye7MBeH0SSDNZ-zLgqHaDHaji8gix34cj0Q9idC27oIujQgnICGvjoIUCLSkBeZlxeYsE4FSReZqI97W7YAcINbKYjR+DQB4AewtohbFaGHHDTQdDFbyK0SNaS5KChZ9bSGmD16L4pFebpEnKL5JGKQpHoK25Z4jLKRbKZFm4D7wQtrq4D6Txso2xbIcilGgBSTeJ5HfygApFLGliSBbK25FHJbrFTYuheaHHxg4Eux+Gd4sDd4OKfx7HjxMqKS+iVEpEPoaCzSoi24GYLKZGUr3wtpHH3pCo2BmYgkbBgkomQmaD3FOBPGJidCIkCrIkQnWRW7SHIHmZiy0Hj6aHFbmEYEnYCYXH6HFbUkMBt7SG25mIO41BkaiDWCyIXHIymJB4h6MliyPBwywAhRslj7FYlDSGL60lhBTZH5JBOgJ7SHlJwmLKSlzYZRc6expw7676PC+gJ5J4THwHmpqAQo5E2AkF0EiFEAUmoHOmY5tq3bcGebWkPjpB0ZEBGixA4FM6KT0lwguixDGR4no43zGS0n2kMCOkohkEUE8FUEv5ekwEOnWnOmPb5C4g4Kek46mrk7WmCrB7ARkFOygAqirANbCBGgfEJnZlJnWmpmxkdjUGujtkMFiHAl1QTQhzU7ellk8YVkh5oG2kYEhlijOlihOBOAfF+GgBhBrkqhnwZiIJpk+njk2Ah7Vndkrm0nOkujOnbG+hHHOkhCcFv6jk2wYkknxhk7EHlnElmY7nZoGYUCoA-mWiE53IVn+mzQEBGi-lYB-lDjGIUiygtRCA0giFyjeLOlTkQrvH4EhLOn-GwFvmVl8CoUzkoTDlcGtnJkMCPkfkcgGaJnfkcinlYHGTVn9mIAhls6nQkAqgUWoi3iNkfFrlhDVnGT8WTqRbVkEVwgUAGYek4H-7wXcCIXQDIXTlwjiW2BDmIDQUECwUiI0jgF8GdDCHKVqXlIcgm40W8EVGgDulEVQG453JjyaBGgcj3HAEGV0VGWYHiGMV9lMGsXs6OCcXvncWHBNkcj8WCVhVrkiUjZiXnn4ldkoQyVyUsB6WWXumgCyUmEsAKVKUQqqVEDqVZmdnCATnATPkAVBpBUvBLpLnrGKQnkeXYU5l7l4VgVHmfF5AsA4Irm+gZWkXWkGalV8A3nEV3n9XSY2JDXlV+TLl+FsmJlcXWQ9XWh1VCnZjWmZGEmAVVUXm3nQGDKdVEBTWhl2g6kGq+w0rFkjmtmDX7nAS1F5gmWuxnUtq+zFVDUv5SHKzQymQQHt62VQwwwEAcKvQNhhRBS+SxRskxT+QvSzSPB7W5I-XuHVkNh1lfCtBOWKRcYojCAajKQUYECo2yWzWuCeQujI0Ugg2eTbFmU3W8GuUdgUCuX9pkXWXrFWk8Z+mUABmJlwG41vHjV0Hc0BlY0rmkXpCs25keXrHtXkwkCIxwIaCLQi6ZHyaxiYE42zT43uEUjVlHFeXrEFk1CK0UjK15CaBq0+Va140oi61E0MEG0Dkrl0ygSm0EDm2q3Jbq1qCa0hL83a122E362C2G1AksWgHKxaz9rf6aBGwA1ZrEGS1uxs0eUNhSZOlp0k2ARA3ApOD+UcX8yg3chOCU0O0a2C0F0qhF2eQhAhAFRA0vq2BDxmapJzbdIN2-WxDYhVStHchV012iD93sUbk1COjBWtCd3uHd24imhqQAz3RdhZg5ixhT0Ugz01C6giwIBwyohwFyjuht0XaZI51d3GKCpwAEDdUmTuHE4UxqQD3F1sWIKj3CDj37CHBr0EB9puwb1uTd5rC-U-3tQP0j2D1+RV1nxj1mY8Vf1iqMAdD3Q-1-3X2APuHIM90rBJhqRL09jLBkFf3RjzBHXpKaDXExgiioNA1qjASgSgMv2D1f1z0ujXgr1Nan3uG24IxIyUygBl1cPCCIyPJf0-18DXzKT0MBXgPD0v1QNv0wOf3JEVal5EBnzDA0A+FH0d1KOkCl4PLgmhoWKF7-3lKgAEz5DEwI7IQ-DozZCYxyixJIQH7GT0S6OWB3iEBWT7Jpy7TeTQCQ3+S8DmNdBFxXUkUs1uzgHHXlKVLPj5ByjQlUrX1xPtLQAGZbJNW2yAkbEsCMEHXcAkN4XxmYWNV824WTmoDdkpMJM2L5zNo0pGpFX+3J3XjRNjKKRk0mOPCr7pShRk1yiXxoNU2vRqRl3U3CBwPipvrjyma8NhSmSJQMABAYrCAw2PB0DNHYiXw9PMOgCsO9ir0pxTPvrkV3V8BqROBHFN3TOvgfUcg2DXMnNaxaAXNHFCgijGQPPHOyxqP6SbWC3vMRG9KI1pjR1uwOUEBtOVLCXNNxytNnNCVRWwv9pRMIvAvRBKzYDlAmGsCx1-UKxNOzo4spWiZQscjVNpM2ILLJP7SpPpN2KZPP4d6HWMuHV3P1UlMQqZNkVDVtWfOZAUjz2o5GiGTdmpD9rRzCBfDWFX1pxw2rOhQUsGYGkxC+M+QghKCL6PDyuPCL6mVbYkDajRzAyyu0Dt2GAYJPZgBqv+MaugCL4aTIh6tGpfXjaXh4vx2Etmqfiot4UlpKtUtJPd4Bs3wZOJlMtPwFOssFPssT42xYVlMtUVPdkxCKCSCwAuhpgK4cZqH9CizA4OjzBXydUKFeH+SGTKhhkCumvQrGiivGQxB3iwBFumLituw6AcwR7eSK6zY3xsZS7EvD5FYvjbR7g2RxySvSsFCmvasolrMhsdgqvWteTqv2sLvCDOttppifgB2tRPXJ7mVxkciXBMBe6dLmsn2w4E3-LihxIpzn2kOmsgqqJY6jX7UhI7vS0Qolr8UblbmOCfmvk8bs2byXixwEBURB4yTrEyNSOvQwfJZODhmiGmOWIkAX2W3HEVwnanvl7nvH3FaXmC1SSP213GR7jgcLhSjYwakrnciGQIekfCAIeLnIeeVcAPuX1lzYcntntmsEcH5HEkdgOvT10pxgcZBhhvoaMmNdIWvkcScEBdikBUR3jVlqQ2gdgqd3hcz-wtREDSd0bYgeBUfCA0etHO1cCKfahEMGcXOzUtkZ0pm5iAeyxSXGREesFmPChAsuuYugAgaeslmJ2ywgap3fv+KKS-ubnblOc2loXGSSAwYQdQe0d+GweF3wd0eIdsdiEceogYcEDcegoUC8d4f8fdKCfEdMdieKRJfhoUimc0eMcieeQsdIceV5doeFfFeqI4d8dye56edlE1eJfJfjBBZuzjPuSMDtAey9OxRzddCRRAYLf+RLeSB+CxgohFx+cIbYAQugBkFBfXXeIePS55C4sJh4GKSGGJnTpHGDcMAgshebIuflCsUfE6x4nlCJdJCd6sCJnncA8sCZnBcMhnzyAT2tSKja5wy4eVuhRZCSDw+mCI+xTa7GuiTo-+TI9Y8EA4+PCGEI1vt2VmqQ9mZ2zVCwBGD5k0IU-Q-GR3etlnE0H8ES1uWKQFGpEdhlyM0TOvsJ3v42wM-odyjQBtu4HMvU9GCJmi9U9BSihvM+cvfC8-NQ-ZjQLqZ4BGWPaWCuDyD-NeeAtg+nf+29mxhGg6wfePa-ssgPVi2KRuorv+PoK5z9Ai7bJ+FGj6gCDmiLn8VLSYG+9EBHGoBHFOCB+GLB-R+PcXsMAcjdnffs+-ccgX4g9A--eXeg8IKSCSCTAGAgVrErnCAa8wlbHrGVQS9xxy8a+5zi9tuvFefeKi-lBa-cY6+ywuNkLPxq3Pzl88cN9xxqQ+hHE+g-JECo-leXOC1PcNtgBgvgHgqtyR4W3EAd6xgXMxJWMUAP6mOtLJIdhaMWtVdedz8b9qBFIlIXN782gH-tJH-4eVfDcVfycd7DIXPrEvU0orl78HWTzbFDCmTeFIbEUhx8COxkOTCs0-4u1A28JH-h1V2Lhtsmt3E5MAKnTrpwB2jWmAawuaGE-adydBLaA9AUA4cN7XqAQCwFv86uSQf2HZyN44Fz+6iALslyX6GFvAHvTQPYnYCWoQMrzWfvH2chAY+BDA1-pewJB5oC0yXfgWf0EGC8vW2aCFrFX7IUByg-ZViujQbKhUOWdyRNnQVTIfdoyFvX2hp0s4NUuWZ5RKpHQO4hJYQqIHmiBRO7hMiS9g-XKBWcrs9+exkeimHSO4+VxCLFBsFXUWo8VtBq5NchFSi5IttqrgkCmJTSoeVpKfVLKqlSEJWVEhyQhCkZSQqcsMC+VQquD3vKywgKDgvWgwRNAqCrK6gtGvWUxofFJIRDJ8BmBZgQNhAfATcuwzDIMB+eucMIiYykg3c-CXg9YsMJXKnFMBALHzsUzuTctjBJobsq0GIAWIUQLUOpqmmfbLJLABNAgBNyMDugOhFIVQGZgcYuhghVVUIeIW7Jsl1OLoX8hhTuQJsrKVgjFvt1ADIE3G8wCgAvQwL-BG87tT2lwKcFjVvE7w64O408bFoEwjwNGFiDsb2DoAazcxkTAGaq8ihr4H8MuEeyFRQIUKd6IDG+gC8r22IaGLQzAi3tAURIkgCcDgjfFyRiOMcBwkMBQIPCT-agfBWyi0iF6n0Akab2cGzoWos0R7GQJ37ksiALcQ3mIKMJJAtYNQVkeINJQV8kcN8Q9kzXkGFDWyjzGZhXQTCaC6hvCDRG0EXCYisMLWa0nYOArSgueRo3QImQxG6BKifCKrKQF4A2w42icY7CaL-gaRX0Jze4Waj0HOdLe-PTHPqJkISIYwYjYhvoVAQfZPRpQH0bLApCc5aS6kToFDg0A3MbAuI9sNyOBgC9QxE2MxgSM+DfA5MpmJTGLHVqRiDOgiUxN6IlStxyMxWWkqGOOysAHgrjXCDOBmgKBBiL0VjMcCoiUkIIhwpgEWLzHwUOs4qZaHhFnAAAGUMUAk3xQ4YgOiCMQpiIBhAmETCeYniPuhAxkQM-I0KAE3ygBM2UzROKOAxqWp3QK4sAGuNgDVjNx243cTmMrAEiZ+rIBMKePPGvpE41gR9CKk3Ed51xxDbMR9HfF5iHRYALeqLFNG41BAcY9DAmNfAUgocFUBCSjkGg20QxzAwsX9kmwCiJmsIA0PMHBJZAp8SgXtihjyChilSISFUn1jCAZZ7QDEuwmQI9AzFTgjhLYe4XdChibaOtYOgwXeyZhIihEgWumyLb9jPsChKiX-AImtiiJFAAIqAgMC094JgoxQqOClD15eJFGSQJ0T-hkCqA0AeAIuG4ExB5oxk69rWMgRETyoREsprjR+TXsRRjk0ggwVMHPDhw9kgWvpMsBsYfa4OIXIYAIB3BwEqIZEXBPknhiK6XuRkq8ACn140s3zV8EZMowZgWouvayd8FMSkgh8GEwUfEXmxzhXgBEnsgLVUlHRbAHYDSX5K0lfBAiogAKX1CIAyJ6MAUokJjDMyMkIgCg18rjSEmBTUaCYbxJqLe4a1URGotKQ6RlyPZJAokG2I43pExBSwVIIIPXkgAINE4s4+1mfE2n8AZiHIJkYfUyJkiKBRxCgfPxLAcd-YVibacwHdEOA2APuRfFyMMn5B7pfAY6ZvFUBnTksBePMeBPxFQS7BIeb0AwA8Bj8oZn1fzg+G15ShlMh4KBKO1mnFY9pKJHsjxjaLzZaQRsLMhNJsBtMCxf8VIG+iYCCAfaFIfIEWyQkPB2wr4CgFAlxY+5FpMsVuDCFOn8AjmKEuaVYEyZEykyMuG6c7m0RAIGZH0HRG4BOYN5pAsYAYMZzsmESeMoY8mbzkAR-wgZIMeiCBQrB84xY9YzMcLKsAeS6C-w9JGvxv7W1zeQ0oOiNMdqh1LOMQMWW0RzHSzjZcsngYrKqDKyb6fUACeCQ2BywrWtAIIBrPlJazixusikPrMNyGz0Z5QGXBw0a6PgFaqIM2pbJFzWyNazkwOtsLKEa0nacDTBhbJVqaAc5vtPObbQLnl1faxclOWJlJFlyrZVtXOf1Ttm1yQ6XnXwY6NIDLA-ZQeC0aNlAD8R4Q200WE2PwxESdozbIgE8G0DStmOzAzfHOLnEABSb2bLl9kwhTEjAdwp4HrxDzShbGUcCjKmA1Aocx8twbs32b4NcwvI4EV2j3GwEUCfUa7hv2Nkgz9xPI-AtWBcqwtVRVowop4MAXMdleIoaaYJPtnvzksRxJjlAuabLAW5IuKXoPBtn8jO59tasswUFofS75NQMgtNLtEkBRej2LcPoVF5iF1iV+ZcNQvFqgByBpUWqAwuUTXTVqWUTYuwoYXYiLpzCi8h50fnQFd272ImPMFtwoLXwiMGImqA7F7sPiT4YgHwrvbALlFgKVCCuW4igBnesoHyG704FJZIuFxWAD-VhK1Nm0Gw-gFtTNQ-1WeboxZIMKVEdgYSq1ejqClcX7sGFTilPPAJK6rVf+DLZAQAP8V+EgBiZEATYG2IML9UiorxZZ1+IvxWyEbUJWgPCUYDb0oAaxYoPSVMzyoPfRxMli0SrEkldiLJcQXyWfwziRqTRY9OLRacSATgYRENRVElUzm+ID4klGSxNKzmKpa0u0vWKNslAAuHSDwH4BQ5zSvoIAA). I've copied latest types without changes from `flow-typed` there and simple code at the very bottom that illustrates the issue:

```
function test(routeConfig: NavigationRouteConfig) {
  if (routeConfig.screen) {
    // Do something.
  }
}
```

The line `if (routeConfig.screen) {` alone produces 3 different `all branches are incompatible` errors.

Maybe you have some ideas on how to approach this situation in order to fix it?

### Current Behavior

Currently, 3 flow errors are raised.

### Expected Behavior

I expect there no errors.

### How to reproduce

Link from the description above.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2

**Comment by Ashoat** [comment]
`NavigationRouteConfig` is a union of types, only some of which have a `screen` property. Can you use a more specific type (that definitely has that property) in the typehint for your function? If not, you’ll need to do runtime checks in your function to “refine” (ie. narrow) your type to one that has that property.
