### ISSUE TITLE
Fail to compile in baseline project

### ISSUE THREAD

**Issue by stevestarck** [react-navigation/react-navigation#4462]
### Current Behavior

Failed to compile:

	./node_modules/react-navigation/src/routers/StackActions.js
	Module parse failed: Unexpected token (10:2)
	You may need an appropriate loader to handle this file type.
	| const pop = payload => ({
	|   type: POP,
	|   ...payload,
	| });
	|

### Expected Behavior

expected this to not have a compile error on an unmodified project (see repro steps below) not sure what I need to adjust to make this succeed.

### How to reproduce

create-react-app a9
cd a9
npm start
// works OK
^c

npm install react-native
npm start
// works OK.
^c

npm install react-navigation
npm start
// works OK
^c

edit src/App.js // add:
	import { createStackNavigator } from 'react-navigation';
npm start
//error:
Failed to compile:

	./node_modules/react-navigation/src/routers/StackActions.js
	Module parse failed: Unexpected token (10:2)
	You may need an appropriate loader to handle this file type.
	| const pop = payload => ({
	|   type: POP,
	|   ...payload,
	| });
	|

### Your Environment

macOS 10.13.5 (also happens on windows as well)

| software         | version
| ---------------- | -------
| react-navigation | 2.2.4
| react-native     | 0.55.4
| node             | 6.10.2
| npm or yarn      | npm 6.1.0

**Comment by brentvatne** [comment]
it sounds like you are using webpack and don't have a babel transform enabled that supports rest object spread

**Comment by stevestarck** [comment]
okay. i'll track down where to put the babel transform.  (suggestions might be helpful for a noob.)

**Comment by brentvatne** [comment]
we don't explicitly support using webpack right now and this project works out of the box with the babel-preset-react-native so that's why we don't give any instructions around it

**Comment by stevestarck** [comment]
Hmm. Ok. I thought I could use this from react-native-web. I’ll have to play around and figure out how to make this work without webpack. Thanks for the clarification.

**Comment by brentvatne** [comment]
it can but we don't provide instructions for that yet because it's pretty rough at the moment. @ericvicenti is working on improving that experience

**Comment by stevestarck** [comment]
ok.  I'll see if there's an alternative way I can work around this.  @ericvicenti it would be interesting to see how 'rough' the scenario is right now, and see what I can do with what is already in place, if that's possible.

**Comment by jas99** [comment]
Geting same issue while trying to use with react-native-web.

**Comment by brentvatne** [comment]
we don't explicitly support react-native-web, hopefully you can figure out how to get it working by just using some babel config, it should not be difficult

**Comment by dwilt** [comment]
Running into this with `create-react-app`

**Comment by dwilt** [comment]
@brentvatne shouldn't the _distributed_ react-navigation code that is ultimately being imported in a project be compiled down to ES5 so there isn't any of these kind of dependencies? I understand that a React Native project comes out of the box with this support but plenty of other popular setups don't (like create-react-app).

![image](https://user-images.githubusercontent.com/1065539/42479215-cb806e6e-83a5-11e8-9b54-098cd79652c8.png)

I shouldn't be seeing the spread operator in distributed code, right?

**Comment by jas99** [comment]
@dwilt React navigation is designed for react native and not for reactjs. So they are delivering right version of javascript supported my react-native.

**Comment by jas99** [comment]
I was trying to use it with react-native-web and wasn't able to compile

**Comment by jaredreich** [comment]
Same here, I can't for the life of me get this to work inside a `react-native-web` app.

**Comment by dejamic** [comment]
Same here - getting: 
```
./node_modules/react-navigation/src/routers/StackActions.js
Module parse failed: Unexpected token (10:2)
You may need an appropriate loader to handle this file type.
| const pop = payload => ({
|   type: POP,
|   ...payload,
| });
|
```
