### ISSUE TITLE
Double tapping button to open drawer crashes app 

### ISSUE THREAD

**Issue by linux08** [react-navigation/react-navigation#4464]
I've a button which opens the drawer and close it once pressed.If a user mistakenly double tap the button app crashes.
```
 <TouchableOpacity
      onPress={() =>
        navigation.dispatch(DrawerActions.toggleDrawer())
      }
    >
      <Ionicons name={leftIcon} color="white" size={35} />
    </TouchableOpacity>
```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.0.1
| react-native     | 0.55.2
| node             | 8.11.1
| npm or yarn      | 5.80

**Comment by brentvatne** [comment]
update to 2.2.4 and try again

**Comment by linux08** [comment]
worked.thanks
