### ISSUE TITLE
Hot Reloading not working in 1.5.4

### ISSUE THREAD

**Issue by luco** [react-navigation/react-navigation#4465]
### Current Behavior

Changes are not updated in `StackNavigator` while it updates in React Native.

### Expected Behavior

Update the changes and re-render.

### How to reproduce

Install react@0.55.4 and react-navigation@1.5.4.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.5.4
| react-native     | 0.55.4
| node             | 6.9.2
| npm or yarn      | 3.10.9

**Comment by brentvatne** [comment]
hi there! please file issues against the latest version of react-navigation, 2.2.5 at the time of writing

**Comment by luco** [comment]
@brentvatne Ok, it's not working on 2.2.5 either.
