### ISSUE TITLE
Several files removed after update to 2.2.5?

### ISSUE THREAD

**Issue by udarts** [react-navigation/react-navigation#4469]
### Current Behavior

After updating react-navigation to 2.2.5, I am getting errors that some files are missing.

/node_modules/react-navigation/src/navigators/createDrawerNavigator.js

and

node_modules/react-navigation/node_modules/react-native-safe-area-view/index.js

### Expected Behavior

I am creating drawers.

### How to reproduce

Update to version 2.2.5

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.2.5
| react-native     | 0.55.4
| node             | 8.10.0
| npm or yarn      | 6.1.0

**Comment by udarts** [comment]
I just noticed that there was a commit to place all drawer code into: react-navigation-drawer: https://github.com/react-navigation/react-navigation/commit/45391db7d9f48de9c5def57f9a1e77d69221faa7#diff-0cbbd6479f5838e3482c6c948d32d0c0

As dependency. Would be nice to have the documentation to be updated.

**Comment by brentvatne** [comment]
why does this matter? you should be importing these through the public interface, `import { createDrawerNavigator } from 'react-navigation';` and not through their paths

**Comment by brentvatne** [comment]
further, please consider in the future that your the repro steps you provided are not sufficient to reproduce the issue. as the issue template points out, *you need to provide a runnable example*

**Comment by udarts** [comment]
@brentvatne thanks for your reply, now it suddenly works. weird didn't work yesterday. Already had the import as it suppose to be. Just needed a clearing probably. Cheers, will close this issue.
