### ISSUE TITLE
Improve the API for making a screen a modal

### ISSUE THREAD

**Issue by iMerica** [react-navigation/react-navigation#4470]
Hi,

Thanks for working on this library. I've studied the docs for opening a screen as a modal and I'm finding it intentionally more complex then it needs to be. The example [here](https://reactnavigation.org/docs/en/modal.html) shows how to make a screen a modal by passing in some options to a **stack** configuration. 

This is counter-intuitive because a stack is a container for multiple screens. So passing in options to the entire stack is not what we want intuitively. We want to make a **single** screen a modal in a straight forward way ideally at the screen option level or the component level. 

Like this for example:

```js
const HomeStack = createStackNavigator({
  A: { screen: ScreenA },
  B: { screen: ScreenB, modal: true },
  C: { screen: ScreenA }
});
```

or in the component level, like so:
```js
class ScreenB extends React.Component {
  static navigationOptions = {
    modal: true
  };
}
```

**Comment by brentvatne** [comment]
hi! we have an open issue on the rfc repo to discuss this, can you repost as a comment in that thread? thanks! https://github.com/react-navigation/rfcs/issues/15
