### ISSUE TITLE
this.props.navigation.goBack() not working in DrawerNavigator

### ISSUE THREAD

**Issue by theapache64** [react-navigation/react-navigation#4474]
Ok, let's make this straight. I am new in 'react-native'/'react-navigation'.

 I've two screens, let's say A and B.It's wrapped under a `DrawerNavigator`. The screen `A` is the `initialRoute`, and when a button clicks from `A`, it navigates to `B` using `this.props.navigation.navigate('B');`, but when i try to `goBack` from B using `this.props.navigation.goBack()`. It doesn't work. 

I've googled a lot, but couldn't find anything helpful. Why it's not working ? Am i missing something? 

    const HomeDrawerNavigator = createDrawerNavigator({
        A: A,
        B: B,
    }, {
        initialRouteName : 'A'
    });

**Comment by brentvatne** [comment]
@ericvicenti - any idea what the justification is for `isBackEligible`? https://github.com/react-navigation/react-navigation/blob/89a24bdc1236981a3c9d6e4f35afb5af487aaa44/src/routers/SwitchRouter.js#L166-L167

**Comment by ericvicenti** [comment]
If the action.key is specified, we should only let the matching router handle it. It sounds like the action key is incorrectly specified? If you want the deepest active router to handle the back action, it should have `key` set to null or undefined.

**Comment by yoler** [comment]
Same question

and in contentComponent I can not get closeDrawer, is undefined

**Comment by brentvatne** [comment]
@yoler - that is not at all the same question. that is fixed in 2.3.1

**Comment by xanderberkein** [comment]
Having the same problem here.

I made this snack based on the [example in the docs](https://reactnavigation.org/docs/en/drawer-based-navigation.html)

https://snack.expo.io/@x11n/drawernavigator-goback

**Comment by brentvatne** [comment]
fixed in 2.4.1

**Comment by poptocrack** [comment]
Thanks for your work! My solution is related to [react-navigation/react-navigation-drawer#4](https://github.com/react-navigation/react-navigation-drawer/issues/4)

**Comment by xanderberkein** [comment]
@brentvatne This doesn't seem to be completely fixed. See my updated snack (https://snack.expo.io/@x11n/drawernavigator-goback).

When you go to "Another Screen", then browse to "Notifications" and press `goBack`, you get sent back to the HomeScreen, while you would expect to jump to the previous screen, "Another Screen", again.

**Comment by brentvatne** [comment]
those are the only two back behaviors available - none or initialRoute. this has always been the case. if you'd like to add more you can implement this rfc! https://github.com/react-navigation/rfcs/pull/2
