### ISSUE TITLE
Warning on stackNavigator and Error on createStackNavigator

### ISSUE THREAD

**Issue by HoangThongBui** [react-navigation/react-navigation#4475]
I have a StackNavigator defined in App.js. The problem is, when I start the package, it runs normally with a warning 'The StackNavigator function name is deprecated, please use createStackNavigator instead', but when I change to createStackNavigator, it throws an error: 'Can't find createStackNavigator'.
## App.js
   `import React from 'react';
import {StackNavigator} from 'react-navigation';
import Home from './Components/Home';
import Main from './Components/Main';

const App = StackNavigator({
     First: { screen: Home }, 
     Second: { screen: Main },
})

export default App;`

## Home.js 
   `import React, {Component} from 'react';
import {View, Text, Button} from 'react-native';

export default class Home extends Component{
      static navigationOptions = {
            header: null
      };
      render() {
             var {navigate} = this.props.navigations;
             return(
                   <View> 
                        <Text>This is page 1</Text>
                        <Button onPress={() => navigate('Second',{})} title='Click to go to page 2' />
                   </View>
             )
       }
}`

## Main.js 
`import React, {Component} from 'react';
import {View, Text, Button} from 'react-native';

export default class Main extends Component{
      static navigationOptions = {
            header: null
      };
      render() {
             var {navigate} = this.props.navigations;
             return(
                   <View> 
                        <Text>This is page 2</Text>
                        <Button onPress={() => navigate('First',{})} title='Click to go to page 1' />
                   </View>
             )
       }
}`

## My Environment
react-navigation    2.2.5
react-native           0.55.4 
node                       8.11.2
npm                        5.6.0

**Comment by HoangThongBui** [comment]
ah, i found out myself, no need to working on it, you can close this.

**Comment by KAPIL888** [comment]
please can you tell me how you solve this error

**Comment by nickjuntilla** [comment]
@HoangThongBui What was the answer? I have the same problem after following the tutorial.

**Comment by nickjuntilla** [comment]
I solved this problem by upgrading to "react-navigation": "^2.13.0",

**Comment by HoangThongBui** [comment]
just import {createStackNavigator} instead of {StackNavigator}
