### ISSUE TITLE
How can I turn off lazy loading for BottomNavigation in V2?

### ISSUE THREAD

**Issue by leosurwiki** [react-navigation/react-navigation#4477]
I used to set `lazy` in `tabnavigatorconfig` of TabNavigator 
https://reactnavigation.org/docs/en/tab-navigator.html#tabnavigatorconfig. What is the best practice for `createBottomTabNavigator` in v2?

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.2.5

**Comment by brentvatne** [comment]
it's the same

https://github.com/react-navigation/react-navigation-tabs/blob/3f0ceb572ddf7cb09435a0ec0c93fdb96befe1d5/src/navigators/createBottomTabNavigator.js#L13
