### ISSUE TITLE
Method `jumpToIndex` is deprecated.

### ISSUE THREAD

**Issue by shizhiang** [react-navigation/react-navigation#4479]
### Current Behavior

```
import React from 'react'
import { View, Text } from 'react-native'
import { StackNavigator, TabNavigator, TabBarBottom } from 'react-navigation'

class HomeScreen extends React.Component {
	render() {
		return (
			<View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
			<Text>Home!</Text>
			</View>
		  )
	}
}

class SettingsScreen extends React.Component {
	render() {
		return (
			<View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
			<Text>Settings!</Text>
			</View>
		  )
	}
}

const HomeStack = StackNavigator({
	Home: { screen: HomeScreen }
})

const SettingsStack = StackNavigator({
	Settings: { screen: SettingsScreen }
})

const RootTab = TabNavigator(
	{
		Home: { screen: HomeStack },
		Settings: { screen: SettingsStack }
	},
	{
		tabBarComponent: TabBarBottom,
		tabBarPosition: 'bottom',
		tabBarOptions: {
			activeTintColor: 'tomato',
			inactiveTintColor: 'gray',
		},
		animatedEnable: false,
		swipeEnable: false,
	}
)

export default class App extends React.Component {
	render() {
		return <RootTab />;
	}
}
```
![jumptoindex](https://user-images.githubusercontent.com/9928255/41268809-7e0091f4-6e34-11e8-900e-4f8084fa5ad9.png)

### How to reproduce

when switch bottomBars the warning will appear.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.3.0
| react-native     | 0.55.4
| node             | 8.11.2
| npm or yarn      | 4.6.1

**Comment by brentvatne** [comment]
`TabNavigator` is deprecated

**Comment by shizhiang** [comment]
This issue is resolved. Thank you for your help. I want to know whether `StackNavigator` is deprecated.

**Comment by izikandrw** [comment]
@shizhiang you can read what has been deprecated in the 2.0 release here: https://reactnavigation.org/blog/2018/05/07/react-navigation-2.0.html#deprecations

**Comment by brentvatne** [comment]
@shizhiang - only the name. change it to `createStackNavigator`

**Comment by fullstackdeveloper90** [comment]
I've updated  like this: StackNavigator to createStackNavigator, TabNavigator to createBottomTabNavigator in react-navigation 2.*

Warning is removed.

**Comment by cyb3rsalih** [comment]
Thank you @fullstackdeveloper90 . Problem solved. When I rename
StackNavigator -> createStackNavigator
TabNavigator    ->  createBottomTabNavigator  in the import and initialize statements.

**Comment by truongluuxuan** [comment]
Insert this code:   "console.disableYellowBox = true; " to class index.js
