### ISSUE TITLE
TabBarIcon didn't show up 

### ISSUE THREAD

**Issue by monkeykingblack** [react-navigation/react-navigation#4494]
I using createBottomTabNavigator, but I can create TabBarIcon on it
Im trying [this code](https://snack.expo.io/HyLz-QRlm) to text on expo, every thing is ok. 
But without expo just use react-native-cli I have below problem

![screenshot_2018-06-13-12-07-47-319_com iotcore](https://user-images.githubusercontent.com/29424003/41331281-70b84928-6f02-11e8-82ba-1953ff9b23ab.png)

| software         | version
| ---------------- | -------
| react-navigation | 2.2.0
| react-native     | 0.55.4
| node             | v9.11.1
| npm or yarn      | 1.7.0

**Comment by brentvatne** [comment]
please provide repro that causes that error, as you pointed out it works fine on snack. we need something we can clone and run

**Comment by monkeykingblack** [comment]
@brentvatne i found the problem, it my fault when import library
thanks for your time

**Comment by badrshs** [comment]
at least give your solution someone maybe has same as what did you got  :)

**Comment by monkeykingblack** [comment]
@badrshs i code in native so when i import FontAwesome in @expo/vector-icon, TabBarIcon can't show up.
I think nobody will get silly mistake like me :)

**Comment by badrshs** [comment]
@monkeykingblack 
thank you ❤️ 
 because I got same errors as yours , it was also silly mistake but i solved it  ,I wrote   
`import Icon from 'native-base'
`instead of 
`import {Icon} from 'native-base'
`
I post it maybe someone have same problem 🤓
