### ISSUE TITLE
Deep linking with variable in path broken for SwitchNavigator

### ISSUE THREAD

**Issue by greyvugrin** [react-navigation/react-navigation#4496]
### Current Behavior

When using a deep link with a "variable" in the path (eg `/path/:id`), switch navigator fails to navigate to screen. It seems that the variable format isn't parsed by SwitchNavigator. If I send an exact match, including the variable (send exactly: `myapp://path/:id`) to the simulator, it works.

The variables behave correctly with StackNavigator under the same conditions. More info below.

It could be that this isn't the intention for StackNavigator (I'm using this for an auth flow and need a Reset password route, with a hash in the deep link). In that case I'm happy to create a doc PR  for the Deep Link section, mentioning that SwitchNavigator is not intended for this.

### Expected Behavior

Switch navigator handles variable, navigates to route, and passes variable in params.

### How to reproduce

Issue repo: https://github.com/greyvugrin/react-navigation-deep-link-issue

To reproduce:

- download repo
- run `react-native run-ios`
- go to a dynamic deep link: `xcrun simctl openurl booted deeplinkexample://chat/Testing`

You will see that the app does not navigate to the Chat screen.

If you uncomment the `<StackExample />` instead, in the App render method, and try the deep link command, it navigates correctly, and shows the variable coming from the path.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.3.1
| react-native     | 0.55.4
| node             | 9.7.1
| npm or yarn      | 5.6.0

**Comment by ericvicenti** [comment]
I actually observed this yesterday while working on a website with react-navigation! Will fix this today.

**Comment by brentvatne** [comment]
ping @ericvicenti

**Comment by ericvicenti** [comment]
Ok, I finally have a cleaner implementation of path handling, shared between Stack router and Switch router: https://github.com/react-navigation/react-navigation/pull/4590 . The same path tests run on each router

@greyvugrin, would you do me a favor and check if this fixes the problem for you?

**Comment by greyvugrin** [comment]
@ericvicenti yep - like a charm!!!
