### ISSUE TITLE
[Android] Previous deep link is called when stack is redefined

### ISSUE THREAD

**Issue by anniewey** [react-navigation/react-navigation#4499]
Behaviour is only occurred in Android given the scenario as below:

**Observed behaviour:**
1) Open deep link to go screen B (works perfectly)
2) Go back to screen A
3) Reset stack navigator in App.js (this step is necessary)
4) Auto redirect to screen B again

**Expected behaviour:**
1) Open deep link to go screen B 
2) Go back to screen A
3) Reset stack navigator in App.js 
4) Stay in screen A

Currently on `"react-navigation": "^1.0.0-beta.19"`, any help on this please?

`AndroidManifest.xml`
```
...
<activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:launchMode="singleTask"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        android:windowSoftInputMode="adjustPan">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
          <intent-filter>
              <action android:name="android.intent.action.VIEW" />
              <category android:name="android.intent.category.DEFAULT" />
              <category android:name="android.intent.category.BROWSABLE" />
              <data android:scheme="myapp" android:host="myapp" />
          </intent-filter>
      </activity>
...
```

**Comment by brentvatne** [comment]
sorry we don't support beta versions of the library that are a major version behind. i'd suggest updating to the latest version and trying to reproduce there
