### ISSUE TITLE
Typo in createKeyboardAwareNavigator?

### ISSUE THREAD

**Issue by angly-cat** [react-navigation/react-navigation#4500]
Currently, there's the following code in [`src/navigators/createKeyboardAwareNavigator.js`](https://github.com/react-navigation/react-navigation/blob/master/src/navigators/createKeyboardAwareNavigator.js#L29):

```
_handleGestureCanceled = () => {
  /* ... */
  this.props.onGestureFinish && this.props.onGestureFinish();
};

_handleGestureFinish = () => {
  /* ... */
  this.props.onGestureCanceled && this.props.onGestureCanceled();
};
```

It seems like a typo, that in `Canceled` method original `Finish` prop is called and vise versa. @skevy, is this a typo?

**Comment by brentvatne** [comment]
yeah this is a typo, thanks for pointing it out. https://github.com/react-navigation/react-navigation/commit/ee6a6c53b110fb732daecd4d2b3e85e77617d390
