### ISSUE TITLE
how hide the headers / tab bars?

### ISSUE THREAD

**Issue by pheromone** [react-navigation/react-navigation#4501]
I'm using react-native-af-video-player, which requires a full screen, the article said:
If you’re using react-navigation you need to manually hide the headers / tab bars to take advantage of fullscreen videos.What do I need to do?please help me?
    "react-navigation": "1.5.3",
    "react-native": "0.55.4",

**Comment by brentvatne** [comment]
hi there! this is a question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.
