### ISSUE TITLE
The navOption headerLeft doesn't render components

### ISSUE THREAD

**Issue by xanderberkein** [react-navigation/react-navigation#4502]
### Current Behavior

When trying to use a Component to render the `headerLeft` of a StackNavigator, nothing happens:

```
const Hamburger = () => <Text>text</Text>

static navigationOptions = {
  headerLeft: Hamburger,
}
```

The documentation mentions you get access to a number of props when using a Component, but the Component doesn't get rendered at all.

### Expected Behavior

I expect the component to get rendered ([because the docs say it should](https://reactnavigation.org/docs/en/stack-navigator.html#headerleft))

### How to reproduce

See this snack: https://snack.expo.io/@x11n/headerleftcomponent

The header renders as a React Element, but not as a Component

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.3.1

**Comment by Jobeso** [comment]
Hey xanderberkein,
you have the solution as a comment:
`headerLeft: <Hamburger />`

**Comment by brentvatne** [comment]
the version of react-navigation in that snack is 2.0.1. i updated it to 2.3.1 (in package.json) and it worked as expected: https://snack.expo.io/ByGKlf1ZX

**Comment by brentvatne** [comment]
oh I see what you mean, you want to use `headerLeft: Hamburger,` but not `headerLeft: <Hamburger />,`

docs are wrong here, created issue for it https://github.com/react-navigation/react-navigation.github.io/issues/194

**Comment by vonovak** [comment]
the docs are not wrong here, they are semi-correct. This is probably a bug. The problem is, you're defining the `headerLeft` in the root of the stack, and since there is no screen in the stack before this one, no `headerLeft` is rendered when a react component is specified. 
However, if you add more screens to the stack, the component in `headerLeft` starts working, as seen here: https://snack.expo.io/Bkb9UMkWm

**Comment by vonovak** [comment]
@xanderberkein out of curiosity, can you please share your use case for using a component in `headerLeft` of a screen that is at the bottom of a stack? Which of the [passed props](https://github.com/react-navigation/react-navigation/blob/5598c3e28f2573be3fc6ae18c9bd8614c81f1ce6/src/views/Header/Header.js#L153) did you need?

**Comment by xanderberkein** [comment]
@vonovak I wanted to display the built-in `HeaderBackButton` of react-navigation on some screens that didn't get them automatically (like the children of a DrawerNavigator). This button assumes to receive some of these passed props however (like `onPress`, `tintColor` and `title`). I solved this easily like this though:

```
import { HeaderBackButton } from 'react-navigation';

...

  static navigationOptions = ({ navigation }) => ({
    headerLeft: (
      <HeaderBackButton
        onPress={() => navigation.goBack(null)}
        tintColor={Colors.white}
        title="Back"
      />
    ),
}
```
