### ISSUE TITLE
'BackHandler' with DrawerNavigator inside to StackNavigator

### ISSUE THREAD

**Issue by nobady90** [react-navigation/react-navigation#4503]
Hi guys,
i can not figure out how to simply manage BackHandler, here is my project:

https://snack.expo.io/BkB4ojRxm

In practice for each page (Login, News, Contacts) I would like that if the user clicks on the back button hardware (android) always return to the 'Home' page.

In addition, later I will have to implement sub-pages, for example pages related to the News, and I would like to always return to the previously viewed page.

The official documentation does not help much, and looking on the web many have these problems (it is not a criticism but an observation :-D )...
How do you manage all this? thank you so much.

**Comment by fnicastri** [comment]
have you tried to set `backBehavior` to `true` and `intialRoute` to the home screen in the DrawerNavigationConfig?

**Comment by brentvatne** [comment]
hey there - i might have mislabeled this at first. the behavior you describe is exactly what is expected:

> In practice for each page (Login, News, Contacts) I would like that if the user clicks on the back button hardware (android) always return to the 'Home' page.

this is the default although there was briefly a regression that broke this it is resolved in 2.4.1.

> In addition, later I will have to implement sub-pages, for example pages related to the News, and I would like to always return to the previously viewed page.

I don't understand this question but it seems better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.
