### ISSUE TITLE
No transition animation when navigating to child stack

### ISSUE THREAD

**Issue by cranberyxl** [react-navigation/react-navigation#4506]
### Current Behavior
Since `2.1.0`, when using `navigate` to go to a screen in a child stack, the transition animation does not happen, the change is instantaneous, however, it does animate when using `goBack` from the child screen.

### Expected Behavior
Navigating to a child screen should use a transition animation as in version `2.0.1`

### How to reproduce
Working in 2.0.1: https://snack.expo.io/@cranberyxl/nested-stack-navigate-with-animation
Not working in 2.3.1: https://snack.expo.io/@cranberyxl/nested-stack-navigate-no-animation
Probable cause: https://github.com/react-navigation/react-navigation/pull/4404

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.3.1
| react-native     | 0.55.4
| node             |  8.9.4
| npm or yarn      | yarn

**Comment by brentvatne** [comment]
heya @cranberyxl! it looks like you didn't hit save on the no animation snack, it is showing me the default example there. can you update it?

**Comment by brentvatne** [comment]
actually that was easy enough: https://snack.expo.io/ByV99-y-X

**Comment by ericvicenti** [comment]
Thanks for reporting this! I found the issue and fixed it here: https://github.com/react-navigation/react-navigation/pull/4520
