### ISSUE TITLE
Memory leak with nested navigators, modal navigator, and drawer navigator.

### ISSUE THREAD

**Issue by adam-s** [react-navigation/react-navigation#4508]
### Current Behavior

- What code are you running and what is happening?

I recreated the nested navigation I'm using for my app using only one module, React Navigation, and posted it in a GitHub repository at https://github.com/adam-s/react-navigation-memory-leak

It includes an alternative navigation stack to use for an authentication workflow, a switch navigator to switch between the authenticated portion and log in portion of the app, a drawer used for user navigation buttons, a modal for the first screen of the authenticated portion, and two more screens for the user to navigate into.

In the demo, I used setTimeout() in componentDidMount() to trigger a navigation actions, however, the memory leak exists when I'm just clicking links like a normal user without the automation.

I, also, correctly configured AppDelegate.m with

````
  // jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
  jsCodeLocation = [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
````

checked for console.log() statements and set the Scheme Build Configuration to Release in Xcode.
![screen shot 2018-06-13 at 10 58 51 pm](https://user-images.githubusercontent.com/232388/41391420-3343401c-6f60-11e8-81b1-907179c17247.png)

- Include a screenshot if it makes sense.

Here is a screenshot showing the memory allocation slowly climbing. Also, if I just check them memory using the activity monitor process it climbs just the same.

![screen shot 2018-06-13 at 11 04 54 pm](https://user-images.githubusercontent.com/232388/41391437-4af0835a-6f60-11e8-85c8-630b7d594395.png)

### Expected Behavior

- What do you expect should be happening?

There shouldn't be memory leaks when navigating between screens normal per the instructions given in the documentation.

This entirely might be a documentation problem where I'm not taking the correct steps when navigating between screens to prevent this memory leak.

- Include a screenshot if it makes sense.

### How to reproduce

I recreated the navigation structure and posted the complete app at https://github.com/adam-s/react-navigation-memory-leak

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.3.1
| react-native     | 0.55.4
| node             | 8.11.1
| npm or yarn      | 1.5.1

**Comment by brentvatne** [comment]
can you explain why you think this is a memory leak? the graph that you showed doesn't really demonstrate anything material. over ~150s memory usage increases by a few hundred kb. gc will probably kick in at some point and bring it back down. if you want to do more detailed analysis and share your findings in another thread that would be welcome.

**Comment by brentvatne** [comment]
additionally - if there is a memory leak you should be able to do the thing that causes it over and over and get to the point where the app is consuming hundreds of mb of memory and eventually ooms. if you can share that it'd be helpful to know.
