### ISSUE TITLE
Unmounting Async Rendering Issue? - Lifecycles (componentDidMount)

### ISSUE THREAD

**Issue by EthanDM** [react-navigation/react-navigation#4509]
### Current Behavior

- What code are you running and what is happening?

I've got two screens with a console.log() in componentDidMount [(source).](https://github.com/EthanDM/rn-lifecycle-issue/blob/master/App.js) When navigating fast between them, componentDidMount gets called from the other screen which is about to unmount. I don't think this could have happened prior to react introducing async rendering, since the unmounting component would have needed to unmount before the new one mounts. If I give the component enough time to unmount this issue doesn't happen.

See video: https://youtu.be/Ghh_smT-Gfk

In the real world, there is likely more component teardown so this time window is larger. If there are ajax calls in componentDidMount, data will be refetched for a component that is about the unmount.

### Expected Behavior

- What do you expect should be happening?

componentDidMount should not be called from the unmounting component. Other lifecycle methods are also being called along with the class constructor.

### How to reproduce

GitHub repo: https://github.com/EthanDM/rn-lifecycle-issue

Clone, npm install, react-native run-ios. Turn on debugger and look at console.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.3.1
| react-native     | 16.3.1
| node             | 9.5.0
| npm or yarn      | npm 5.6.0

**Comment by EthanDM** [comment]
@kestasb thanks for the input. I can confirm as well that this issue does not exist on Android.

**Comment by brentvatne** [comment]
hey @EthanDM! thank you for the detailed report. this is a known issue and we are tracking it in https://github.com/react-navigation/react-navigation/issues/4155

**Comment by brentvatne** [comment]
I added this issue to the list in that umbrella issue so that we can test against your provided example when the fix is ready
