### ISSUE TITLE
Drawer custom items

### ISSUE THREAD

**Issue by stychu** [react-navigation/react-navigation#4510]
Can I use somehow the current drawer navigator items or view to display my custom items? Like I have one route in the drawerNavigator and I want a custom drawer to contain my custom items not the one from the navigator but I would like to keep the styling etc. When I create my custom drawer items start rendering under the phone bar and don't have any styling. I know I need adjust this myself but wondering if I can derive from the DrawerItems or DrawerView somehow so I have same stylings ...???

**Comment by brentvatne** [comment]
hi there! this is a question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.
