### ISSUE TITLE
Component in headerBackground can't be pressed

### ISSUE THREAD

**Issue by jordenchang55** [react-navigation/react-navigation#4514]
### Current Behavior
I followed [StackWithTranslucentHeader.js](https://github.com/react-navigation/react-navigation/blob/9c3fffa47fba0ef64e580ce96ee3cb5cbc3f69f0/examples/NavigationPlayground/js/StackWithTranslucentHeader.js) to create custom translucent header. But I found that components, such Button or TextInput, which are set into headerBackground can not be pressed or typed. When I click the button on the header, the `onPress` callback is not called anyway. 

### Expected Behavior
The components in header should be worked as they are not in header. 

### How to reproduce
I tried by simplest component for preventing from dependency, but the Button is just not worked once I put it into header.

Here's my navigation options:
```
static navigationOptions = {
    headerTransparent: true,
    headerBackground: (
      <View style={{ flex: 1 }}>
        <Button
          title="test"
          onPress={() => console.log('press test')}
        />
      </View>
};
```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.0.4
| react-native     | 0.53.3
| node             | v8.11.1
| npm or yarn      | npm 6.1.0

**Comment by brentvatne** [comment]
why would you expect something in the background to be touchable? `headerBackground` is the view that's rendered below the header view. just render the thing in the header view :P

**Comment by benevbright** [comment]
@brentvatne  I agree with your point that the background won't need to be touchable. 
But it also should not allow the element that is under the background to be touchable. It passes the touch to the next layer and it's a problem.
