### ISSUE TITLE
Disable the gestures for react-navigation V2

### ISSUE THREAD

**Issue by JonsonHI** [react-navigation/react-navigation#4515]
Hello, can you tell me how to disable gesture in drawer
```
static navigationOptions = () => {
        return Object.assign({}, {
          drawerLockMode: 'locked-closed', 
          title
        }, navigationOptions)
      }
```

drawerLockMode  No effect. How do you handle it? Thank you very much

**Comment by JonsonHI** [comment]
/DrawerView.js        90-98line
![image](https://user-images.githubusercontent.com/18373125/41449185-254b1510-7092-11e8-8601-8c2578c3dfc7.png)
Cannot get the value

**Comment by brentvatne** [comment]
https://reactnavigation.org/docs/en/navigation-options-resolution.html
