### ISSUE TITLE
transition from screen without header to screen with header when use custom height of header

### ISSUE THREAD

**Issue by tsaohucn** [react-navigation/react-navigation#4518]
## The issue tracker is reserved for bug reports only.

#2732
---

### Current Behavior

```
  const headerStyle = ({ navigation }) => {

    const onPress = () => { navigation.goBack() }

    return({
      headerTintColor: headerTintColor,
      headerStyle: {
        backgroundColor: themeColor,
        height: HEIGHT,
        paddingBottom: PADDING
      },
      headerLeft: (
        <TouchableWithoutFeedback
          onPress={onPress} 
        >
          <View style={styles.backIconView}>
            <Icon
              iconStyle={styles.backIcon}
              name='arrow-left'
              type='material-community'
              color='white'
            />
          </View>
        </TouchableWithoutFeedback>
      )
    })

  }
```

### Expected Behavior

I expect transition smooth, actually it translate smoothly when I didn't set height of header, but when I set height of header, then it translate not smoothly

### How to reproduce

set height of headerStyle

### Your Environment

Environment:
  OS: macOS High Sierra 10.13.4
  Node: 9.6.1
  Yarn: 1.6.0
  npm: 6.1.0
  Watchman: 4.9.0
  Xcode: Xcode 9.4 Build version 9F1027a
  Android Studio: 3.1 AI-173.4819257

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4

**Comment by brentvatne** [comment]
https://github.com/react-navigation/react-navigation/pull/4353
