### ISSUE TITLE
Reset to another stack navigator ignore sub-actions 

### ISSUE THREAD

**Issue by colinux** [react-navigation/react-navigation#4524]
I have some trouble when I want to reset to another stack navigator then navigate to another screen.
Sub-action inside the reset actions key seems to be not executed. The first screen of the targeted navigator is shown instead.  

### Current Behavior

```js
const deepResetAction = StackActions.reset({
  index: 1,
  key: null,
  actions: [
    NavigationActions.navigate({ routeName: 'otherNavigator' }),
    NavigationActions.navigate({
      routeName: 'otherNavigator',
      action: NavigationActions.navigate('screen2'), // not executed ?
    }),
  ],
});
```

With this example, we're staying in the first screen of `otherNavigator`.

(The same occurs if I remove the first action and set the index to 0.)

### Expected Behavior

- Navigation should go to Screen 2 when reset action is called, and should have the Screen 1 on top.

### How to reproduce

Here is a a snack : https://snack.expo.io/HJrRsYM-X
In this snack, I want to reset from `AlphaNavigator` to `NumericNavigator => Screen2`

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.3.1 (also reproduced in 1.5.11)
| react-native     | 0.55.4 (also reproduced in previous versions)
| node             | 9.11.1
| npm or yarn      | 1.6.0

**Comment by vonovak** [comment]
I don't have an answer to why it doesn't work, but dividing the navigation actions seems to do the job. https://snack.expo.io/rJy_C4EbX

**Comment by pincheira** [comment]
Thanks a lot @vonovak, your workaround works wonders 🎉

**Comment by patrickomeara** [comment]
Am I missing something or are these snacks exactly the same? I'm interested in @vonovak's dividing solution

**Comment by colinux** [comment]
@patrickomeara they are not the same. The snack from @vonovak, in `screens.js` contains 2 reset actions, called with 2 distinct dispatchs when reset button is pressed

**Comment by patrickomeara** [comment]
Thanks @colinux I completely missed `screens.js`.

**Comment by satya164** [comment]
Closing since reset has been revamped in v5.
