### ISSUE TITLE
Material Bottom Tabs Navigation

### ISSUE THREAD

**Issue by MehranAbghari** [react-navigation/react-navigation#4525]
### Current Behavior

Hello, I'm using react navigation for creating bottom tabs with `createMaterialBottomTabNavigator`,
I have three tabs with label and icon, but icons showing defective!
( I'm using **Persian** language in app )

#### See this screenshot

![screenshot_1](https://user-images.githubusercontent.com/30838541/41508766-f8dabb7e-725e-11e8-906a-b76e5a84d5a2.png)

#### My Code
```
import React, { Component } from 'react';
import { Platform } from 'react-native';
import { createMaterialBottomTabNavigator } from 'react-navigation-material-bottom-tabs';
import Icon from 'react-native-vector-icons/Ionicons';

import I18n from '../../locale/LocaleHelper';

import HomeScreen from '../../screen/HomeScreen';
import ProfileScreen from '../../screen/ProfileScreen';
import SettingsScreen from '../../screen/SettingsScreen';

const Colors = require('../../assets/colors');

export default createMaterialBottomTabNavigator(
  {
    Home: {
      screen: HomeScreen,
      navigationOptions: {
        title: I18n.t('homeTitle'),
        tabBarLabel: I18n.t('homeTabTitle'),
        tabBarColor: Colors.bottomHomeColor,
        tabBarIcon: ({ tintColor, focused }) => (
          <Icon size={30} name={ Platform.OS === 'ios' ? (focused ? 'ios-home' : 'ios-home-outline') : 'md-home' } style={{ color: tintColor }} />
        )
      }
    },
    Profile: {
      screen: ProfileScreen,
      navigationOptions: {
        title: I18n.t('profileTitle'),
        tabBarLabel: I18n.t('profileTabTitle'),
        tabBarColor: Colors.bottomProfileColor,
        tabBarIcon: ({ tintColor, focused }) => (
          <Icon size={30} name={ Platform.OS === 'ios' ? (focused ? 'ios-contact' : 'ios-contact-outline') : 'md-contact' } style={{ color: tintColor }} />
        )
      }
    },
    Settings: {
      screen: SettingsScreen,
      navigationOptions: {
        title: I18n.t('settingsScreenTitle'),
        tabBarLabel: I18n.t('settingsTabTitle'),
        tabBarColor: Colors.bottomSettingsColor,
        tabBarIcon: ({ tintColor, focused }) => (
          <Icon size={30} name={ Platform.OS === 'ios' ? (focused ? 'ios-settings' : 'ios-settings-outline') : 'md-settings' } style={{ color: tintColor }} />
        )
      }
    }
  },
  {
    shifting: true,
    activeTintColor: Colors.bottomBarActive,
    inactiveTintColor: Colors.bottomBarInactive,
    barStyle: {
      height: 55
    }
  }
);
```

### Expected Behavior

I expect to show icons perfectly and completely!

### How to reproduce

You can use my code that posted in top, to reproduce this issue!

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^2.2.5
| react-native     | ^0.55.4
| node             | v8.11.2
| npm or yarn      | yarn - version 1.7.0

### SOLVE
This problem can be solved by setting icon's size to 26 --- BUT i want bigger size

**Comment by vonovak** [comment]
Having a snack that reproduces the issue would help. The code you pasted above is not a runnable reproduction since it depends on `LocaleHelper`, `HomeScreen`, `colors` and other modules that are not available. Kindly create a snack that people can run and reproduce your situation.

**Comment by JoseVf** [comment]
@MehranAbghari Try to reduce the icon size, maybe 26?

**Comment by brentvatne** [comment]
the icons need to be smaller - i changed them from 30 to 25 and it worked as expected. also i don't recommend setting the height of the tab bar manually unless you account for iPhoneX otherwise you lose out on safe area
