### ISSUE TITLE
Style for Left and Right header

### ISSUE THREAD

**Issue by nvhungkt** [react-navigation/react-navigation#4528]
Hi, I'm using the default header of react-navigation.
When I add the Right header, a button icon, it aligns top-right. However, I want to center it vertically.
Do you have anything like 'headerRightStyle'?
![image](https://user-images.githubusercontent.com/23579087/41529230-9cf51544-7316-11e8-9619-c5005006cefa.png)

**Comment by abn-volk** [comment]
Have you tried this package?
https://github.com/vonovak/react-navigation-header-buttons

It'll give you appropriate styling for each platform.

**Comment by brentvatne** [comment]
hi there! this is a question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.
