### ISSUE TITLE
The ability to remove tab label on one specific tab

### ISSUE THREAD

**Issue by mxdi9i7** [react-navigation/react-navigation#4530]
Hi, I've been working on a custom tab button that shows a 'plus' button in the center of the bottom tab navigator, however, the label text still shows underneath my custom tab button, I tried to remove it  by doing this: 
```
const tabBarOptions = ({navigation}) => ({
  tabBarOptions: {
    showLabel: () => {
      const { routeName } = navigation.state
      if (routeName === 'Create') return false
    }
  }
})
```

However, it seems like tabBarOptions does not accept a function that returns an object. Do you guys have any config option available to turn off label for one specific tab component? if it's custom component.
![image](https://user-images.githubusercontent.com/13799221/41573017-a0937f9c-7348-11e8-8690-c7cc9d7e0f5e.png)

**Comment by brentvatne** [comment]
set the label to empty string for that tab.

that said, this is a question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.

**Comment by mxdi9i7** [comment]
@brentvatne But that tab isn't pointing to any route, I can't set the navigationOptions if it doesn't point to any route

**Comment by NikoMontana** [comment]
@mxdi9i7 did you solve your problem?

**Comment by nikhiysham** [comment]
@NikoMontana it worked, thanks man but still got padding below hidden text.How to remove it?

**Comment by beeglebug** [comment]
I've just tried to do the same, and found the easiest way to remove the label for one screen is to set `tabBarLabel` on that particular screen to a function which returns null, e.g:

```
navigationOptions: {
  tabBarLabel: () => null
}
```

**Comment by stanrud** [comment]
In react navigation v5 just put a boolean attribute into Tab.Navigator:
`<Tab.Navigator labeled={false}>`

**Comment by devnasim** [comment]
You can hide the label by specifying tabBarShowLabel: false for the screenOptions object:

``` screenOptions={{
        headerShown: false,
        tabBarStyle: { backgroundColor: "#000000", borderTopWidth: 0 },
        tabBarShowLabel: false,
      }}```

**Comment by Edgar256** [comment]
Hey , i am late for the party but hope this helps. 
On the options object, add ` tabBarLabel: () => null `attribute like in the example below.


```
 <Tab.Navigator>
   <Tab.Screen
        name="NewsFeed"
        options={{
          headerShown: false,
          tabBarIcon: ({color, size}) => (
            <Icon name="users" color={color} size={size} />
          ),
        }}
        component={NewsFeed}
      />
      <Tab.Screen
        name="NewItem"
        options={{
          headerShown: false,   
          // hide label using this line      
          tabBarLabel: () => null,
          tabBarIcon: ({color, size}) => (
            <MaterialCommunityIcons name="plus" color={color} size={50} />
          ),
        }}
        component={NewItem}
      />
    </Tab.Navigator>
```

**Comment by DianaKoenraadt** [comment]
How can I hide all labels except for the active one? This used to be possible with the old react-navigation.
