### ISSUE TITLE
SwitchNavigator and Android BackHandler wrong behavior (closes the app)

### ISSUE THREAD

**Issue by renanpupin** [react-navigation/react-navigation#4535]
### Current Behavior

When a user press the BackHandler button on the android and it is in the last scene of a stack browser, the application closes normally and goes to the background. After returning from background to active, he returned to the router's AuthLoading router.

SwitchNavigator structure:
-> Loading
-> Authorized
-> Unauthorized

### Expected Behavior
After pressing the BackButton and the application goes to background, after returning to the active state it should remain in the same scene that went to background.

### How to reproduce

* The implementation is exactly like ReactNavigation Auth Flow
[](https://reactnavigation.org/docs/en/auth-flow.html)

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | v1
| react-native     | 0.51.0
| node             | v9.10.0
| yarn      | 1.5.1

**Comment by brentvatne** [comment]
hello!

I ran this on the latest version of react-navigation, 2.4.0, and this is not an issue: https://snack.expo.io/ByHrvBdb7

I don't plan on investigating what may be happening in your case in v1, I recommend updating to the latest version.

**Comment by RicardoBer** [comment]
I works on example beacause it calls 
`this._bootstrapAsync()`; 
on constructor, in this function checks login state and navigate to other screen, but the behavior is as described in @renanpupin comment. 
If you send the app to background with back button on open it again the app is in initialRouteName screen.

The correct behavior will be start again in the screen visible at the moment on send it to background.
