### ISSUE TITLE
createBottomTabNavigator indicatorStyle?

### ISSUE THREAD

**Issue by juuudeeeee** [react-navigation/react-navigation#4539]
I want to have my Tabs to have a border bottom on its active state but createBottomTabNavigator dont have this yet. Is there any alternative for this to achieve? Thanks in advance and cheers!

**Comment by lichenglu** [comment]
You can use your custom `tabBarLabel` or `tabBarIcon` in `navigationOptions` in order to have a bottom. A minimum example:

```javascript
const Tabs = createBottomTabNavigator({
    Home: {
	screen: HomeScreen,
	navigationOptions: {
		tabBarLabel: ({ tintColor, focused }) => (
			<TabBarLabel text={I18n.t('home')} focused={focused} />
		),
		tabBarIcon: ({ tintColor, focused }) => (
			<TabbarIcon img={focused ? Images.homeTabFocused : Images.homeTab} />
		),
	},
    },
})
```
I would love to hear what other options we can have!

**Comment by brentvatne** [comment]
use material top tabs but position them on bottom if you want. not going to support this for bottom tabs but you can make your own navigator for it or fork if you like https://github.com/react-navigation/react-navigation-tabs
