### ISSUE TITLE
Undesired spaces (margins) are added randomly between items in a SectionList or FlatList from React Native

### ISSUE THREAD

**Issue by gervasioaraujo** [react-navigation/react-navigation#4541]
### Current Behavior

- What code are you running and what is happening?
Undesired spaces (margins) are added randomly between items in a SectionList/FlatList from React Native when I use react-navigation and an Android 5.1.1 device (Tablet). When I use Android 4.4 and Android 7.1, the spaces doesn't appear.

![](mtp://[usb:001,024]/Tablet/DCIM/Screenshots/Screenshot_2018-06-20-16-47-53.png)

### Expected Behavior

- What do you expect should be happening?
Spaces should not appear

### How to reproduce
- App.js file:

```
import React, { Component } from 'react';
import {
  Text,
  View,
  SectionList
} from 'react-native';
import {
  StackNavigator,
  TabNavigator,
  TabBarBottom
} from 'react-navigation';

import ProfileScreen from './app/containers/ProfileScreen';
import OverviewScreen from './app/containers/OverviewScreen';
import LessonListScreen from './app/containers/LessonListScreen';
import DisciplineListScreen from './app/containers/DisciplineListScreen';
import SplashScreen from './app/containers/SplashScreen';

const CourseStack = StackNavigator({
  OverviewScreen: { screen: OverviewScreen },
  LessonListScreen: { screen: LessonListScreen },
})

const DownloadStack = StackNavigator({
  DisciplineListScreen: { screen: DisciplineListScreen },
})

const ProfileStack = StackNavigator({
  ProfileScreen: { screen: ProfileScreen },
})

const MainTabNavigator = TabNavigator({
  CourseStack: { screen: CourseStack },
  DownloadStack: { screen: DownloadStack },
  ProfileStack: { screen: ProfileStack },
}, {
  tabBarComponent: TabBarBottom,
  tabBarPosition: 'bottom',
  swipeEnabled: false,
})

const AuthStack = StackNavigator({
  SplashScreen: { screen: SplashScreen },
}, {
  headerMode: 'none'
})

const MainStack = StackNavigator({
  AuthStack: { screen: AuthStack },
  MainTabNavigator: { screen: MainTabNavigator }
}, {
  headerMode: 'none',
  title: 'Main',
  initialRouteName: 'AuthStack'
})

export default class App extends Component {
  render() {
    return (
      <MainStack />
    );
  }
}
```

The SectionList is used in LessonListScreen.

It seems to me that the bug happens depending on the level of navigation of the screen. For example, when I do not use the AuthStack, the bug does not happen.

const MainStack = StackNavigator({
  MainTabNavigator: { screen: MainTabNavigator }
})

Below has a link in github for a sample code.
[https://github.com/gervasioaraujo/sectionListBug](url)

### Environment
| react-navigation  ^2.3.1
| react-native  0.55.4
| node 8.11.1
| npm 5.6.0

**Comment by brentvatne** [comment]
hi there! my initial guess is that this has nothing to do with react-navigation. can you post a screenshot of what you're seeing?

**Comment by artutra** [comment]
Here is a screenshot:
![screenshot_2018-06-20-16-47-53](https://user-images.githubusercontent.com/15269475/41720679-2e53e586-753a-11e8-93fd-547a7df38b92.png)

**Comment by brentvatne** [comment]
hey @artutra - if you can demonstrate that this is related to react-navigation i would be happy to investigate but from quickly looking at it i can't see anything about this that is related to react-navigation :(

**Comment by artutra** [comment]
The problem is that it only happen when you put the ListView on a nested navigator like:

```
This way it shows the red lines
--MainStack
  --MainTabNavigator
    --CourseStack
      --LessonListScreen

This way it doesn't show the red lines
--MainStack
  --MainTabNavigator
    --LessonListScreen
```
Any suggestion @brentvatne ?

**Comment by mateuspiresl** [comment]
I have this same problem on every FlatList form my app. It gets visible when the FlatList background color is different from the item color. @gervasioaraujo and @artutra, did you create this issue in the react native project or found a solution yourselves?

**Comment by gilnicki** [comment]
@mateuspiresl @gervasioaraujo Did you find a solution?

**Comment by satheeshwaran** [comment]
We are also facing this issue with RN 0.59 on a SectionList used with react-navigation.

**Comment by GabrielMottaDev** [comment]
Still happening, same here.
Any updates?

**Comment by bitkraft-apatel** [comment]
+1,
This I'm facing same issue, You can reproduce it when you put `<Link />` component with mix of `<View />`
So the issue can reproduce when you put structure something like this
```
<Link ... />
<Link ... />
<View .../>
<Link ... />
<Link ... />
```
Now if you wrap all these in View and apply background color, You will notice the unwanted space at below of 2nd and last Link. So the issue can be refactor as ** Unwanted spaces added at bottom of `List` in last occurrence of `List` component**
