### ISSUE TITLE
custom transition when navigating back failed on v2

### ISSUE THREAD

**Issue by jemmyphan** [react-navigation/react-navigation#4542]
previously [this](https://github.com/react-navigation/rfcs/issues/10) is working on v1, but a few days ago i started to upgrade to v2 and noticed that it's not working when navigating back.

### How to reproduce

https://snack.expo.io/rkhRJzuZm

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.3.1
| react-native     | 0.55
| node             |
| npm or yarn      |

**Comment by brentvatne** [comment]
hello! perhaps you were depending on some broken behavior - I looked at this snack you provided and the logic for what you seem to be trying to be doing (different transition only when you go back to the 'App2' screen). this fixes that: https://snack.expo.io/r1aXnPFZQ

if this isn't what you want and you just always want transitions to and from App2 to have this transition, remove the `isBack &&` bit

**Comment by jemmyphan** [comment]
thanks for responding @brentvatne, what intended is using this transition when navigating to App2 and navigating back from App2.
I've created 2 snack with the same logic or code but different version
[v1](https://snack.expo.io/By20XOtZX)
[v2](https://snack.expo.io/H10RmuFZm)

**Comment by brentvatne** [comment]
ok then just change `if (isBack && toRouteName === 'App2') {` to `if (toRouteName === 'App2') {

**Comment by jemmyphan** [comment]
I've tried it, but the behaviour that I want is when App1 -> App2 and App2 -> App1 will be using the custom transition.
using `if (toRoutename === 'App2')` will trigger the custom transition on App3 -> App2.
sorry if i'm not clear enough. If you don't mind can you try this v1: https://snack.expo.io/By20XOtZX (intended behaviour), v2: https://snack.expo.io/H10RmuFZm

**Comment by brentvatne** [comment]
@jemmyphan - if you want that logic i see no barrier to you modifying the example to make it happen. if you narrow down what isn't working as you expect specifically (eg: something like "route when going back isn't the correct route") i can help but otherwise this is just a logic problem for you to deal with

**Comment by jemmyphan** [comment]
Actually, the logic is taken from [your's](https://github.com/react-navigation/rfcs/issues/10) and it's what I intended.
using this logic on v1.5.11 fulfilled this
![transition](https://user-images.githubusercontent.com/7644274/41755822-6fc33fe8-7603-11e8-9d0b-4dc45f1778bf.gif).
However on v2.3.1 when navigating back, the fromTransitionProps was removed immediately before the transition is finished, so it's unable to get the routeName from fromTransitionProps while transitioning since it's already undefined.
`console.log(fromTransitionProps, toTransitionProps)`
![image](https://user-images.githubusercontent.com/7644274/41757772-59983db2-760e-11e8-85f0-7feacb473b60.png)

while on v1.5.11 the fromTransitionProps still available while transitioning and removed when it's finished transitioning, so we are still able to get screenName.
![image](https://user-images.githubusercontent.com/7644274/41757897-355fafce-760f-11e8-99d6-446c0f8b6a18.png)

Is it an intended change on v2? if it is, how can we achieve this with v2?

**Comment by brentvatne** [comment]
> @brentvatne I've tried it, but the behaviour that I want is when App1 -> App2 and App2 -> App1 will be using the custom transition. using if (toRoutename === 'App2') will trigger the custom transition on App3 -> App2. sorry if i'm not clear enough. If you don't mind can you try this v1: https://snack.expo.io/By20XOtZX (intended behaviour), v2: https://snack.expo.io/H10RmuFZm?

I feel like I'm missing something here. both of these examples run exactly the same as far as I can tell.

**Comment by jemmyphan** [comment]
it's different when navigating back, the first one is v1 and the second one is v2.
the first one is navigating back with the custom transition, but the second one isn't
![transition](https://user-images.githubusercontent.com/7644274/41795850-714afdc0-768e-11e8-8cc1-6b227fa4c4c5.gif)

**Comment by brentvatne** [comment]
oh interesting, on ios they are identical

**Comment by jemmyphan** [comment]
sorry it's my bad, forgot to mention that ios' is using this animation as default, should have used another transition animation.

**Comment by brentvatne** [comment]
notice that if you adjust the duration it works as expected. i was testing on ios before because you never mentioned android and posted a screenshot of ios :P

**Comment by jemmyphan** [comment]
sorry for that :sweat_smile:
can i have the exact number of the duration?
tried on increasing and decreasing but still not happen, just to make sure that the duration that you mentioned was the transitionSpec right?

**Comment by brentvatne** [comment]
you can install 2.5.1 and it includes a fix: https://github.com/react-navigation/react-navigation/commit/de112565d3890276c59d7902bcad2cdfd4d7e248

**Comment by jemmyphan** [comment]
it's working on 2.5.1.
thanks so much for fixing this. :tada:
