### ISSUE TITLE
Poor tab bar scroll performance in createMaterialTopTabNavigator

### ISSUE THREAD

**Issue by paulpopiel** [react-navigation/react-navigation#4543]
### Current Behavior

When using `createMaterialTopTabNavigator` with swipe and scroll enabled, the tab bar scrolling/swiping performance is very poor. The tab bar does not smoothly scroll with the screen.
See:
https://snack.expo.io/SkeF0iuZ7

This is even more evident in Debug mode or on slow devices.

### Expected Behavior

Compare that to the old behaviour in v1 with the `TabBarTop` component with `tabBarPosition: 'top'` in the `TabNavigator`, where the tab bar smoothly scrolls (on swipe) with the screen:
See:
https://snack.expo.io/HkEYpiuWm

### How to reproduce

New v2 behavior: https://snack.expo.io/SkeF0iuZ7
Old v1 behavior: https://snack.expo.io/HkEYpiuWm

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.4.1
| react-native     | 0.55.4

**Comment by brentvatne** [comment]
hey @paulpopiel can you create this issue on https://github.com/react-navigation/react-navigation-tabs instead? thanks!

**Comment by brentvatne** [comment]
cc @satya164

**Comment by brentvatne** [comment]
moved issue over

**Comment by EmmanuelKD** [comment]
having the same issue here ,it seems like when swiping fast, the the screen moves relatively fast but the tab goes through ever tab between the from tab and destination tab, creating slow effect
