### ISSUE TITLE
Nested StackNavigator inside a Custom Tab navigator -- Can't go back

### ISSUE THREAD

**Issue by vjsingh** [react-navigation/react-navigation#4546]
### Current Behavior

There seems to be a bug with a nested StackNavigator inside a custom tab navigator (createNavigator). I can't go back from inside the nested navigator.

### Expected Behavior

I expect to be able to go back from the "Settings" screen

### How to reproduce

https://snack.expo.io/Bk5w_XFWX

To Reproduce
- Login
- Go to settings
- Go to screen two
- Observe that you can go back here
- Observe that now you can't go back

### Other Notes
I know about the static router trick in the documentation, but I couldn't find a way to do that with a "createNavigator" custom navigator.

**Comment by brentvatne** [comment]
I know this is confusing but you need to use `goBack(null)`. the `goBack()` helper automatically provides the key that you're going back from and is then limited to the stack that it's inside of. `goBack(null)` says to go back from anywhere.

**Comment by vjsingh** [comment]
Thanks @brentvatne. That is indeed quite confusing. I'm relatively new to react-navigation, but it seems like there might be a better API to express that.

My issue is fixed by adding null though, as you say.
