### ISSUE TITLE
withNavigation(Focus) cannot be used with pure or shouldUpdate 

### ISSUE THREAD

**Issue by macrozone** [react-navigation/react-navigation#4547]
I have a tab navigator and i want to controll polling of apollo-client (graphql) by whether the current tab is visible or not. I created a HOC that uses `withNavigationFocus` to define the polling interval.

But i noticed serious performance problems as withNavigation forces rerenderings of all components that use this HOC on every navigation change.

I then tried to find a solution and played around with `componentShouldUpdate`  and noticed that every component using `withNavigation` will rerender, no matter what i do there. 

Even if you do this:

```
compose(
    withNavigationFocus,
    shouldUpdate(() => false),
)
```

the composed component WILL update on every navigation change. That's odd, I would expect that the component would not update in this case

**Comment by brentvatne** [comment]
@macrozone - please provide a runnable example, the issue template is abundantly clear that this is necessary

**Comment by macrozone** [comment]
@brentvatne reproductions are a lot of effort and sometimes it makes more sense to gather more insights and information. 

In this case i learned that context api does a force rerender when the context changes,

also `withNavigationFocus` always has a new `navigation` object, so you can't shallow compare that if you are only interested in the `isFocused`  part.

In my case, there is something else also wrong, so i will come back here if i have more insights (and hopefully a reproduction)
