### ISSUE TITLE
how to nest createDrawerNavigator createBottomTabNavigator createStackNavigator

### ISSUE THREAD

**Issue by SilenceBurst** [react-navigation/react-navigation#4548]
I have tried many ways, but I have not found a good solution to nest createDrawerNavigator  createBottomTabNavigator createStackNavigator

# now
- Drawer (createDrawerNavigator)
  - MainStack(createStackNavigator)
    - TabNav(createBottomTabNavigator)
      - HomeScreen
      - StructureScreen
      - ClassifyScreen
      - ProjectScreen
    - DetailScreen
    - LoginScreen
    - RegisterScreen
    - AboutMeScreen
    - CollectScreen
  - LoginScreen
  - AboutMeScreen
  - CollectScreen

When i open drawer in MainStack, then click AboutMe open AboutMeScreen , at this time is in the AboutMeScreen , but when i open drawer , focus is **MainStack** 
- Why focus item is **MainStack** ? I think should be **AboutMe** at this time.

[here is my code](https://github.com/SilenceBurst/ReactNative_WanAndroid/blob/master/src/navigator/DrawerNav.js)

# previous
- Drawer(createDrawerNavigator)
  - MainStack(createStackNavigator)
    - TabNav(createBottomTabNavigator)
      - HomeScreen
      - StructureScreen
      - ClassifyScreen
      - ProjectScreen
    - DetailScreen
  - LoginStack(createStackNavigator)
    - LoginScreen
    - RegisterScreen
  - AboutMeStack(createStackNavigator)
    - AboutMeScreen
  - CollectStack(createStackNavigator)
    - CollectScreen

In this way , when i open drawer in MainStack , then click AboutMe open AboutMeScreen 
- AboutMeStack don't have headerLeft to goBack

and , when i open drawer in MainStack , then open LoginScreen , then open RegisterScreen 
- I don't know how to direct navigate to MainStack . 

---
I don't know which method is right . 
My English is not very good , and first learn react-native , Thanks

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.2.0
| react-native     | 0.55.4

**Comment by brentvatne** [comment]
hi there! this is a question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.

**Comment by SilenceBurst** [comment]
I have asked a question in stackoverflow but no one has responded . I have been looking for this issue for a long time . 
- Drawer (createDrawerNavigator)
  - MainStack(createStackNavigator)
    - TabNav(createBottomTabNavigator)
      - HomeScreen
      - StructureScreen
      - ClassifyScreen
      - ProjectScreen
    - DetailScreen
    - LoginScreen
    - RegisterScreen
    - AboutMeScreen
    - CollectScreen
  - LoginScreen
  - AboutMeScreen
  - CollectScreen

When i open drawer in MainStack, then click AboutMe open AboutMeScreen , at this time is in the AboutMeScreen , but when i open drawer ,drawer focus item is **MainStack** 
- Why focus item is **MainStack** ? I think should be **AboutMe** at this time.

**Comment by reyalpsirc** [comment]
I'm having exactly the same problem with version 2.17.
Searched around on web and found nothing so far besides this issue and unanswered stackoverflow posts
