### ISSUE TITLE
absolutly positioned header with `headerMode: float` breaks in react-native 0.56.0-rc.2 on android

### ISSUE THREAD

**Issue by macrozone** [react-navigation/react-navigation#4557]
Absolutly positioned header are invisible on react-native0.56.0-rc.2 on android when you use `headerMode: float`.

I think this has to do with https://github.com/react-navigation/react-navigation/blob/master/src/views/StackView/StackViewLayout.js#L413

measuring the size of the header returns 0 on react-native 0.56 and maybe it cuts away its content. Not sure why it used to work before

Solution would be that we can override that calculated height. (headerHeight property or so)

Context: The reason we use a absolutly positioned header in this case is, that we fade it out under certain conditions and it should reveal the content that is underneath it.

### Current Behavior

absolutly positioned headers do not render on android and react-native 0.56.0-rc2 when you set headerMode: "float"

### Expected Behavior

absolutly position headers should render as in react-native 0.55 with headerMode: "float"

### How to reproduce

```

const Header = (props) => (
 <View style={{position: "absolute", top: 0, left: 0, right:0, height: 50, backgroundColor: "red"}}><Text>I am the header</Text></View>
)

const Main = createStackNavigator(
  {
    Home,
    Profile,
    Infos,
  },
  {
    headerMode: 'float',
    mode: 'modal',
    navigationOptions: {
      header: props => <Header {...props}  />,
    },
  },
)
```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.0.4, also happens on latest 2.4.1
| react-native     | 0.56.0-rc.2
| node             | 8?
| npm or yarn      | yarn

**Comment by brentvatne** [comment]
can you try to repro this without react-navigation to see if there is some measurement bug in react-native on android in 0.56?

**Comment by JackHowa** [comment]
is it possible that this would work with createMaterialTopTabNavigator? I'm not being able to replicate this
