### ISSUE TITLE
Override header navigation options of grandparent

### ISSUE THREAD

**Issue by giacomocerquone** [react-navigation/react-navigation#4562]
### Current Behavior

As I've written here: #3947 

This is due to the way you structured the new navigationoptions override and I'd like to know how to solve this. You have this rule printed in your doc:

`You can only modify navigation options for a navigator from one of its screen components. This applies equally to navigators that are nested as screens`

But since tab hasn't a header, the only way to let it have a header is to wrap the tab navigator in a stack navigator.
Then what do you do to try to override that stack header? You put a navigationoptions inside one screen of a tab but this doesn't work for the previous rule... kaboom.

In my real use case scenario, I can't make every tab screen a stacknavigator to solve this problem because they're already stacknavigator and i need the nested header to show other information about those tabs screens.

### Expected Behavior

The new way overrides works is great, but I've never had troubles understanding the previous one and now I'm having troubles to accomplish the same results.

In the example, the expected behaviour, is to make appear "My real stack title" as headerleft of the main stacknavigator

### How to reproduce

https://snack.expo.io/Hk0_OaiZ7

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.5.1
| react-native     | 0.55.4
| node             | 9.2.1
| npm or yarn      | npm 6

**Comment by brentvatne** [comment]
hello! does this not work for you? https://reactnavigation.org/docs/en/navigation-options-resolution.html#a-stack-contains-a-tab-navigator-and-you-want-to-set-the-title-on-the-stack-header

**Comment by giacomocerquone** [comment]
I had seen you answering to another issue proposing the second solution that that link proposes too and it couldn't work as I said in the text of the first issue because (quoting):

>  I can't make every tab screen a stacknavigator to solve this problem because they're already stacknavigator and i need the nested header to show other information about those tabs screens.

And I was about to say that not even the first way from the link would have been ok for me, but actually I had the idea to do this:

```jsx harmony
MyTabNav.navigationOptions = ({ navigation }) => {
  const { routeName } = navigation.state.routes[navigation.state.index];

  if (routeName === 'MyRoute') {
    return {
      bla,
      bla,
    };
  }

  return {
    otherbla,
    otherbla,
  };
};
```

So that `if` targets exactly the route where I was trying to override the header.

Thanks for your great work, v2 is awesome!
