### ISSUE TITLE
DrawerRouter and DrawerView Expect Different Names for isDrawerOpen State

### ISSUE THREAD

**Issue by EricShell** [react-navigation/react-navigation#4563]
### Current Behavior
- I am calling `navigator.dispatch(DrawerActions.toggleDrawer({}));` This will open the drawer but will never close it. I am doing this in a set of nested navigators (Drawer within Stack within Stack), but looking at the code, I believe it is a more general problem.

### Expected Behavior
- Toggling the drawer should open/close it.

### Cause of Issue:
- Introduced in https://github.com/react-navigation/react-navigation-drawer/commit/471b7ce52b55ec46a8c402c127d13665d99f1821
- In DrawerView, new code was added to determine whether the drawer needs to be closed or opened. It checks 'drawerIsOpen' from the current state to determine whether it is currently open.
- However, in DrawerRouter, the events for when the drawer was opened/closed use 'isDrawerOpen' instead. This is the name that was already being used prior to the changes.
- This means that the drawer will never get closed once opened by using toggleDrawer. There are also probably several other related issues due to this naming mismatch.

**Comment by brentvatne** [comment]
thanks @EricShell - this is certainly where having static types would have helped. I fixed this and released 2.5.2
