### ISSUE TITLE
screen title not being showed when nested drawer in stack

### ISSUE THREAD

**Issue by AbanoubNassem** [react-navigation/react-navigation#4564]
### Current Behavior

What am trying to accomplish here , is having a Top StackNavigator, and nest the DrawerNavigator into it , by doing the following :

```
export default createStackNavigator({
  initial: createDrawerNavigator({
    Home: {
      screen: Home,
      navigationOptions: {
        title: 'Home',
      },
    },
    Nutrition: {
      screen: Nutrition,
      navigationOptions: {
        title: 'Nutrition',
      },
    },
  }, {
    navigationOptions: {
      header: null,
    },
  }),
});
```
but all I see is an empty white header , that doesn't show anything

https://i.imgur.com/o5rJlbJ.png
![screen shot 2018-06-24 at 9 52 05 am](https://user-images.githubusercontent.com/13698722/41816442-827b8a66-7796-11e8-8316-84f7be2eac68.png)

any suggestions of what I could be doing wrong ?

### Expected Behavior

It should render the Screen title

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.4.1
| react-native     | 0.55.4

**Comment by VLemon** [comment]
+ 1

**Comment by brentvatne** [comment]
``https://reactnavigation.org/docs/en/navigation-options-resolution.html

**Comment by arapocket** [comment]
Does anyone have an example of doing this with drawers? I've tried the solutions in that link to no avail.

**Comment by brentvatne** [comment]
it's the same as this https://reactnavigation.org/docs/en/navigation-options-resolution.html#a-stack-contains-a-tab-navigator-and-you-want-to-set-the-title-on-the-stack-header

**Comment by arapocket** [comment]
Not sure why it didn't work the first time I tried. Thanks @brentvatne
