### ISSUE TITLE
Q: How to get a list of ALL existing routes in a WHOLE navigator tree?

### ISSUE THREAD

**Issue by wzup** [react-navigation/react-navigation#4566]
Returning to my previous issue https://github.com/react-navigation/react-navigation/issues/4555

So we have following configuration:
```
SwitchNavigator
    LoadingScreen: Component
    App: StackNavigator
        ProfileScreen
        DashboardScreen
    SignInFlow: StackNavigator
        LoginScreen
        LikeScreen
    SignUpFlow: StackNavigator
        SignUpScreen
        TCScreen
```

#### The goal
To get all existing screens in `SwitchNavigator` and its descendants within any screen.

#### Example
Suppose I'm in `DashboardScreen`. Which method can I call to get everything that exists in `SwitchNavigator`? Just a list, not instances.

```javascript
render() {
    let allExistingRoutes = this.props.navigation.getAllRoutes()
    return (
    )
}

// And allExistingRoutes should be something like:
{
    SwitchNavigator: ['LoadingScreen', 'App', 'SignInFlow', 'SignUpFlow']
    SignInFlow: ['LoginScreen', 'LikeScreen'],
    ... and so on ...
}
```

**Comment by brentvatne** [comment]
hi there! this is a question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.

**Comment by wzup** [comment]
@brentvatne 
You're wrong.
This is not a question to a community. Because there is NOTHING in your docs about it so a community can know how to solve it.

This question is exactly to developers of the library.

**Comment by brentvatne** [comment]
the issue template clearly states that issues are for bug reports only.

**Comment by RecanN** [comment]
Is there any news about this ?
