### ISSUE TITLE
How to show which page is currently opened in sidebar using React Navigation?

### ISSUE THREAD

**Issue by gupta-ji6** [react-navigation/react-navigation#4567]
I want to show which page is currently opened by the user in the sidebar in a React Native app, which incorporates React Navigation (v1.5). 

### Current Behavior
My current sidebar looks like this.
![audrix sidebar](https://user-images.githubusercontent.com/21218732/41835873-ab00c86c-7876-11e8-8b33-53b1f0bc6da6.jpg)

### Expected Behavior
I want to implement something like this to show an indication that which page is currently opened (like the `Home` ListItem is greyed out in the image below)
![sidebar](https://user-images.githubusercontent.com/21218732/41836001-07817a0a-7877-11e8-8776-973c2b155bc5.jpg)

### What I tried
I've tried doing this using `this.props.navigation.state` (reference) which shows current states/routes in the app, but that didn't work out for me.

Someone suggested to use [global variable](https://stackoverflow.com/a/42149659/8334159) in React Native but that was again disappointing.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.5.0
| react-native     | 0.55.4
| node             | 8.11.1
| npm or yarn      | 5.6.0
| native-base | 2.4.4

**Comment by prateek3255** [comment]
I am also facing the same issue.

**Comment by Dror-Bar** [comment]
You need to track which screen is currently active. [Here](https://reactnavigation.org/docs/en/screen-tracking.html) is an example how to do it.

It's easier and probably more correct to do it with Redux but not necessary. In your Sidebar component, add this code (untested):

```
  constructor(props) {
    super(props);
    this.state = { screen: 'Home' };
    this.getCurrentRouteName = this.getCurrentRouteName.bind(this);
  }

    componentDidMount() {
        this.getCurrentRouteName(this.props.navigation.state);
    }

    componentWillReceiveProps() {
        this.getCurrentRouteName(this.props.navigation.state);
    }

    getCurrentRouteName(navState) {
        if (navState.hasOwnProperty('index')) {
            const route = navState.routes[navState.index];
            if (route.routes)
                this.getCurrentRouteName(route);
            else
                this.setState({ screen: route.routeName });
        }
    }

  render() {
    const { screen } = this.state;
      <TouchableOpacity style={[styles.touchable, screen == 'Home' && styles.active ]}>
          <Image source={'Home.jpg'}/>
          <Text>Home</Text>
      <TouchableOpacity>
       ...
  }
```

Hope this is clear and works for you.

**Comment by brentvatne** [comment]
hi there! this is a question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.
