### ISSUE TITLE
react-navigation: two StackNavigator navigate each other

### ISSUE THREAD

**Issue by YHQiu** [react-navigation/react-navigation#4568]
I registed at two react-navigation StackNavigator.one StackNavigator  was called StackA, has page A、B、C、D、E;another was called StackB, has page E、F、G.
 The page B navigate to page E,the page E maybe navigate to page F,but the page E could not navigate to page F. Because the StackA not had page F.
 If you want to include page F in stackA in advance, it's probably not very friendly, maybe I don't know how to use it better.

**Comment by brentvatne** [comment]
hi there! this is a question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.
