### ISSUE TITLE
isDrawerOpen undefined when focused on TextInput

### ISSUE THREAD

**Issue by Dror-Bar** [react-navigation/react-navigation#4569]
### Current Behavior

I've encountered a pretty serious bug that leads to undesirable behaviour - When pressing the Android Back Button with the Drawer open, you expect it to close. But if you are focused on a TextInput and attempt to open the Drawer, isDrawerOpen remains undefined. This means that pressing the Back Button goes back to last screen as seen in the gif below. I've tried updating to latest version but the bug remains. I don't know how to solve this.

![android](https://user-images.githubusercontent.com/34343333/41842533-be93ab9a-7873-11e8-9e0c-b68ccc28885b.gif)

### Expected Behavior

When opening the drawer, isDrawerOpen should always update to true.

### How to reproduce

As seen in the gif, just add a TextInput to a screen with a Drawer. Tap the TextInput, then drag open the Drawer and press the Android Back Button.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.4.1
| react-native     | 0.55.4
| node             | 9.4.0
| npm or yarn      | 6.1.0

**Comment by brentvatne** [comment]
post to https://github.com/react-navigation/react-navigation-drawer

**Comment by brentvatne** [comment]
https://github.com/react-navigation/react-navigation-drawer/issues/9
