### ISSUE TITLE
componentDidMount is not calling everytime. i want to recall it when i click on tab everytime. i'm using tabnavigator

### ISSUE THREAD

**Issue by Irtizapk** [react-navigation/react-navigation#4572]
### Current Behavior

- for now componentDidMount is running only first time.

### Expected Behavior

- ComponentDidMount function should be called every time.

### Your Environment

| software         | android
| ---------------- | -------
| react-navigation | 1.5.11
| react-native     | 0.54.1
| node             | latest
| npm or yarn      | 1.7

**Comment by acroix** [comment]
+1 I have the same issue ..

I want the componentDidMount to be called only one the tab I am, not all tabs

**Comment by brentvatne** [comment]
hi there! this is a question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.

https://reactnavigation.org/docs/en/navigation-prop.html#addlistener-subscribe-to-updates-to-navigation-lifecycle
