### ISSUE TITLE
Bundling failed: Error: Unable to resolve module `react-native-tab-view`

### ISSUE THREAD

**Issue by JakeRawr** [react-navigation/react-navigation#4576]
I'm on version v1.5.12 (yes, I know, I need to upgrade to v2, but don't have the time just yet)

in your package.json, there is a 
```
    "react-native-tab-view": "github:react-navigation/react-native-tab-view"
```
However, I can't find react-navigation/react-native-tab-view, it may have been removed. 
Can we please add it back?

Thanks

**Comment by JakeRawr** [comment]
Okay, seems like it does still exist. But for some reason, `npm i` doesn't install it. I had to manually `npm i github:react-navigation/react-native-tab-view`. Anyway, hope this helps someone. 
Closing

**Comment by RitikPatil** [comment]
Thanks Man It Helps Me.

**Comment by Slapbox** [comment]
This is still an issue in 2021. It would be great if React-Navigation would install this as a dependency, since it apparently is one.

**Comment by MarquisAlexander** [comment]
is happening in 2021 aff

**Comment by adriaanbalt** [comment]
@Slapbox https://reactnavigation.org/docs/material-top-tab-navigator
`yarn add @react-navigation/material-top-tabs react-native-tab-view react-native-pager-view`

**Comment by Slapbox** [comment]
@adriaanbalt correct me if I'm wrong, but it's not mentioned in any of the upgrade guide materials. 

And even though it's mentioned on that particular page, I cannot understand why it's not listed as a dependency or a peer dependency. It's what the whole package management ecosystem is for. I'd expect there's a good reason for this choice, but, if there is, it's not apparent to me.

**Comment by flynn31** [comment]
I resolve the issue until now.
help me
![image](https://user-images.githubusercontent.com/104705781/172086439-3de26601-e16a-49e4-9c87-e76d360df2bf.png)

**Comment by KrushnaNaghate** [comment]
I'm still getting this in the latest how to solve it

**Comment by samirbaaz** [comment]
> I'm still getting this in the latest how to solve it

Explicitly installing `react-native-tab-view` is still the easiest solution
```
npm install react-native-tab-view
```
