### ISSUE TITLE
Absolute positioned custom tab bar component renders behind tab screen

### ISSUE THREAD

**Issue by ndillon1** [react-navigation/react-navigation#4583]
### Current Behavior

Using the setup below , position absolute renders the tab bar component behind the screen. The issue can be reproduced across, iOS , Android and Web. 

```js
export const MainStack = createMaterialTopBarNavigator(
  {
    Home: {
      screen: Home,
    },
    Search: {
      screen: Search,
    },
  },
  {
    initialRouteName: 'Home',
    tabBarComponent: TabBar,
    swipeEnabled: false,
    animationEnabled: false,
);

export const RootStack = createStackNavigator(
  {
    Splash: {
      screen: Splash,
      navigationOptions: {
        header: null,
      },
    },
    Main: {
      screen: MainStack,
      navigationOptions: {
        header: null,
      },
    },
  },
  {
    initialRouteName: 'Main',
  },
);
```

Tab Bar Styles used in custom component , which is currently just an empty view for testing purposes 

```js
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    height: 75,
    backgroundColor: 'rgba(0, 0,0, 0.4)',
    paddingHorizontal: 10,
    position: 'absolute',
    top: 0,
    right: 0,
    left: 0,
```

### Expected Behavior

When I set position absolute on the custom Tab Bar component it's expected that the Tab Bar will be rendered on top of the Tab View e.g Home. Currently Home is rendered on top of the Tab Bar component. 

If the same styles are used an passed to createMaterialTopBarNavigator with the default Tab Bar it renders correctly.

### How to reproduce

- Use a blank project with react-navigation and react-native or react-native web
- Render a empty view with a background color as the tab bar component 
- Style with above styles

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.5.2
| react-native     | 0.552
| react-native-web | 0.8.4
| node             | v9

**Comment by brentvatne** [comment]
runnable example: https://snack.expo.io/H1M0I_WGX

this is actually expected behavior because the tab bar is rendered as a sibling to the scene, like this:

```
<View>
  <TabBar />
  <Scene />
</View>
```

so if you want to absolute position it, you need to set `zIndex` to 1 or more (the default is 0). that will solve the issue

**Comment by guergana** [comment]
I still have this problem. I am setting zIndex: 1 or whatever number and I do see the icons but the click event doesn't work.

**Comment by alepdb** [comment]
> I still have this problem. I am setting zIndex: 1 or whatever number and I do see the icons but the click event doesn't work.

Did you solve in some way?

**Comment by guergana** [comment]
> > I still have this problem. I am setting zIndex: 1 or whatever number and I do see the icons but the click event doesn't work.
> 
> Did you solve in some way?

Ño. :( Will make it relative and same color as background for now.

**Comment by mcmar** [comment]
@guergana @alepdb Fixed and awaiting merge/publish. Until then, feel free to use my fork https://github.com/react-navigation/react-navigation/issues/5994#issuecomment-521806991

**Comment by musabgulfam** [comment]
Still facing the same issue, that is, the tab icons gets rendered below the screen in custom tab bar.
