### ISSUE TITLE
iOS Back-button in header doesn't include title of previous screen

### ISSUE THREAD

**Issue by dickerpulli** [react-navigation/react-navigation#4585]
### Current Behavior
The Back-Button in iOS navigation header does not have the title of the previous screen if the title of this previous screen ist defined in a function.

<img width="535" alt="bildschirmfoto 2018-06-27 um 20 51 22" src="https://user-images.githubusercontent.com/1300393/41993811-c4c62d00-7a4c-11e8-808f-974057439a2b.png">

The title is "Back" if the title is defined in a function like.
```
static navigationOptions = ({ navigation }) => {
    return {
      title: 'Title',
    };
  };
```
with this it work correctly:
```
static navigationOptions = {
    title: 'Title',
  };
```

### Expected Behavior
Display title of previous screen in the Back-button of iOS header.

| software         | version
| ---------------- | -------
| react-navigation | 2.4.1
| react-native     | 0.55.2
| node             | 6.9.2
| npm or yarn      | 6.1.0

**Comment by brentvatne** [comment]
hello! we ask in the issue template for a runnable example that reproduces the problem. we were unable to reproduce it in our tests, can you share a repro please?

**Comment by ericvicenti** [comment]
I tried to test this issue but it worked fine for me. Sometimes the title will get truncated to "Back" if it is too long

If you still see the bug, please show us a simplified example in expo snack or a standalone repo

**Comment by dickerpulli** [comment]
You are right. The problem was the length of the title, so that after modifying `headerBackTitle: null` everything works fine.
