### ISSUE TITLE
Conditional Rendering for React-Navigation Authentication Flow?

### ISSUE THREAD

**Issue by alfonsosn** [react-navigation/react-navigation#4591]
So, in my app, I'm implementing an auth-flow. I have implemented three separate `StackNavigators`. They look like below. 

```javascript
const AuthStack = StackNavigator({
  Login: { screen: LoginScreen }
})

const LoadingStack = StackNavigator({
  Welcome: { screen: WelcomeScreen },
})

const AppStack = StackNavigator({
  Main: { screen: DrawerScreen }, //<== tab navigator
  Other: { screen: OtherScreen },
  Another: { screen: AnotherScreen },
})
```

The main reason that I've created three separate stacks is so the user cannot `go back` with gestures to login or loading screens. So I've implemented the code below that successfully renders the screens with my authentication flow. Basically, what I've done is hook up the ReduxNavigation component to Redux, and created a conditional rendering hack that renders the appropriate screens based on the state of redux.

```javascript
class ReduxNavigation extends React.Component {
  render() {
    if (this.props.complete) {
      return (
        <AppStack/>
      );
    } else if (this.props.loading) {
      return(
        <LoadingStack/>
      )
    } else {
      return (
        <AuthStack />
      )
    }
  }
}

const mapStateToProps = (state) => {
  return {
    loading: state.login.requesting,
    complete: state.login.complete,
  }
}

export default connect(mapStateToProps)(ReduxNavigation);
```
Are there flaws with using conditional rendering to manage an authentication flow? Ideally, I would want to navigate through these stacks, when one of my Action creators dispatches a certain action type, or better yet, when a certain property in the store is changed (like I'm doing above).

Thank you!

**Comment by brentvatne** [comment]
you can do this if you like, it's fine. or you can use switch navigator:
- https://reactnavigation.org/docs/en/switch-navigator.html
- https://reactnavigation.org/docs/en/auth-flow.html

in the future please post these sorts of questions to stackoverflow or other places mentioned here https://reactnavigation.org/en/help.html
