### ISSUE TITLE
createDrawerNavigator goBack redirecting to Initial Screen instead of Previous Screen 

### ISSUE THREAD

**Issue by KalaiselvanMahendran** [react-navigation/react-navigation#4593]
Am using SwitchNavigator for Authentication flow. goBack redirecting me to initial screen instead of previous screen

i have reproduced the issue in expo, please go through the link https://snack.expo.io/S1Jrqxbz7

**Comment by brentvatne** [comment]
this is expected behavior, search issues before posting please :) also see https://github.com/react-navigation/react-navigation/issues/4474
