### ISSUE TITLE
headerMode: "none" does not work with iOS Notification Bar

### ISSUE THREAD

**Issue by ethanneff** [react-navigation/react-navigation#4600]
### Expected Behavior

I want no header and my content to still be visible when the Notification Bar is shown on iOS.

### Current Behavior

**works**
<img src="https://user-images.githubusercontent.com/2933593/42059968-1194ecc4-7ada-11e8-9afc-b0b818563043.png" width="400" />

```js
export default createStackNavigator({ Workout });
```

**fails** (Back Assessment is hidden)

<img src="https://user-images.githubusercontent.com/2933593/42059975-1aaa7202-7ada-11e8-8e2e-8cd6da9a0deb.png" width="400" />

```js
export default Workout;
```

```js
export default createStackNavigator(
  { Workout },
  {
    headerMode: "none"
  }
);
```

```js
export default createStackNavigator(
  { Workout },
  {
    navigationOptions: {
      header: null
    }
  }
);
```

```js
export default createStackNavigator(
  { Workout },
  {
    navigationOptions: {
      header: false
    }
  }
);
```

```js
export default createStackNavigator(
  { Workout },
  {
    headerMode: "none",
    navigationOptions: {
      header: false
    }
  }
);
```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.5.5
| react-native     | 0.55.4
| node             | 8.11.2
| npm or yarn      | 1.7.0

**Comment by brentvatne** [comment]
this isn’t an issue specific to react-navigation, currently it’s up to you to offset content according to status bar size
