### ISSUE TITLE
props and navigation is undefined in segment component.

### ISSUE THREAD

**Issue by Ravi448** [react-navigation/react-navigation#4604]
<h3>I am beginner and creating first app in react-native. I have made it but stuck at one place. I just added a segment in header and hide/shown Login/Signup page in base of segment click, but the issue is with navigation, I have a button in login page but this is not working and throwing error. </h3>

<h2 style="color:#006699">Here is my segment page Code</h2>
<code>
import React, { Component } from 'react';
import {
  Platform,
  StyleSheet,
  Text,
  ScrollView
} from 'react-native';
import { Container, Header, Left,Button,Icon,Body,Title, Segment, View, Content } from 'native-base';

import Login from './login';
import Signup from './signup';

const forgot = (props) =>  (
  <View style={{flex:1,flexDirection:'row',justifyContent:'center',alignItems:'center'}} padder >
      <Button transparent>
          <Text style={{fontSize:17,justifyContent:'center'}}>
              Register a new account
          </Text>
      </Button>
  </View>
)

export default class Choices extends Component{
  constructor(props) {
    super(props);
    this.state = {
      seg: 1,
      login:1
    };
  }
  render() {
    const { navigate } = this.props.navigation;
    return (
        <Container>
          <Header hasSegment style={{backgroundColor:'#ff9102'}} androidStatusBarColor="#ed8702" iosBarStyle="light-content">
          <Left>
            <Button
              transparent
              onPress={() => this.props.navigation.goBack()}
            >
              <Icon name="arrow-back" />
            </Button>
          </Left>
          <Body>
            <Title>Login</Title>
          </Body>
        </Header>
        <Segment style={{backgroundColor:'#F5FCFF',display:'flex',height:50}}>
          <Button
            first
            active={this.state.seg === 1 ? true:false}
            onPress={()=>this.setState({seg:1,login:1})}
            style={{flex:1,justifyContent:'center',height:60}}
          >
            <Text style={{fontSize:18,marginVertical:10}}>
                <Icon name='briefcase'/>
                 JOBSEEKER
            </Text>
          </Button>
          <Button
            last
            active={this.state.seg === 2 ? true : false}
            onPress={() => this.setState({ seg: 2,login:2 })}
            style={{flex:1,justifyContent:'center',height:60}}
          >
            <Text style={{fontSize:18}}>
                <Icon name="person" />
                 EMPLOYER
            </Text>
          </Button>
        </Segment>
        <ScrollView style={styles.container}>
          <Content >
          {this.state.seg === 1 && <Login padder />}
          {this.state.seg === 2 && <Login padder />}
          
          </Content>
        </ScrollView>
        </Container>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F5FCFF',
  }
});

</code>

<h2 style="style="color:#006699"">Here is my Login Page Code</h2>

<code>
import React, { Component } from 'react';
import {
  Platform,
  StyleSheet,
  Text,
  ScrollView
} from 'react-native';
import { Container,Content,View,Button } from 'native-base';
import t from 'tcomb-form-native';
var _ = require('lodash');

const Form = t.form.Form;
const stylesheet = _.cloneDeep(t.form.Form.stylesheet);

Form.stylesheet.textbox.normal.height = 50;
Form.stylesheet.textbox.normal.marginBottom = 20;
Form.stylesheet.textbox.normal.borderRadius = 30;
Form.stylesheet.textbox.normal.paddingHorizontal = 30;
Form.stylesheet.textbox.normal.borderWidth = 2;
Form.stylesheet.textbox.normal.fontSize = 20;
Form.stylesheet.textbox.normal.color = '#66747c';

var loginForm = t.struct({
    email:t.String,
    password:t.String
});

var formOptions = {
    fields:{
        email:{
            placeholder:'Email',
        },
        password:{
            placeholder:'Password'
        }
    },auto:'none'
}

export default class Login extends Component{
  constructor(props) {
    super(props);
    this.state = {
      seg: 1
    };
  }
  render() {
      alert(JSON.stringify(this.props))
    return (
        <Container>
            <Content padder style={{marginVertical:40,marginHorizontal:10}}>
              <Form
                ref="form"
                type={loginForm}
                options={formOptions}
              />
              <View style={{flex:1,flexDirection:'row',justifyContent:'center',alignItems:'center'}}>
                  <Button
                      rounded={true}
                      large={true}
                      style={{backgroundColor:'#ff9102',paddingHorizontal:30,flex:1,justifyContent:'center'}}
                  >
                      <Text style={{fontSize:27,color:'#fff'}}>Login</Text>
                  </Button>
              </View>
              <View style={{flex:1,flexDirection:'row',justifyContent:'center',alignItems:'center'}} padder >
                  <Button transparent>
                      <Text style={{fontSize:17,justifyContent:'center'}}>
                          Register a new account
                      </Text>
                  </Button>
              </View>
              <View style={{flex:1,flexDirection:'row',justifyContent:'center',alignItems:'center'}} padder >
                  <Button transparent onPress={()=>this.props.navigation.navigate('Forgot')} >
                      <Text style={{fontSize:17,justifyContent:'center', color:'#ff9102'}}>
                          Forgot Password
                      </Text>
                  </Button>
              </View>
            </Content>
        </Container>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F5FCFF',
  }
});

</code>
<p>
Please help what I am doing wrong in this code.
</p>

<h4>Here is the error log</h4>

![image](https://user-images.githubusercontent.com/29150136/42094252-cd6782b6-7bcc-11e8-9c0e-70ca15fc8b63.png)

<h3>Thank you in advance</h3>

| software         | version
| ---------------- | -------
| react-navigation | ^2.4.1
| react-native     | 0.55.4
| node             | v8.9.3
| npm or yarn      | 6.1.0 / 1.3.2

**Comment by brentvatne** [comment]
hi there! this is a question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.
