### ISSUE TITLE
Background color cannot be set as transparent

### ISSUE THREAD

**Issue by giregk** [react-navigation/react-navigation#4605]
### Current Behavior

- What code are you running and what is happening?
```
const RouteConfigs = {...}
const StackNavigatorConfig = {
  initialRouteName: 'login',
  cardStyle: {
    backgroundColor: 'transparent',
  },
  navigationOptions: {
    headerStyle: {
      backgroundColor: 'transparent',
      borderBottomWidth: 0,
      elevation: 0,
      paddingRight: 16,
      paddingLeft: 8,
    },
    headerTintColor: '#FFF',
  },
};

export const RootNavigation = createStackNavigator(RouteConfigs, StackNavigatorConfig);

```
- Include a screenshot if it makes sense.
![image](https://user-images.githubusercontent.com/20740580/42099015-af8ccbe4-7bbc-11e8-95fc-8184a2f23f1f.png)

### Expected Behavior

- What do you expect should be happening? => my header background should be transparent
- Include a screenshot if it makes sense.
![image](https://user-images.githubusercontent.com/20740580/42098970-95bced20-7bbc-11e8-8dc0-e7a737137a0e.png)

### How to reproduce
=> use code above

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.5.5
| react-native     | 0.55.4
| node             | 8.11.3
| npm or yarn      | yarn 1.7.0

**Comment by brentvatne** [comment]
https://reactnavigation.org/docs/en/stack-navigator.html#headertransparent
