### ISSUE TITLE
setParams not working with custom navigators

### ISSUE THREAD

**Issue by vjsingh** [react-navigation/react-navigation#4606]
Related to: https://github.com/react-navigation/react-navigation/issues/143

We can see that this snack is working: https://snack.expo.io/@vjsingh/setparams-working-with-no-custom-navigator

But this snack is not: https://snack.expo.io/@vjsingh/setparams-with-custom-navigator

I tried to make the example as minimal as possible. In my app, I have a custom tab navigator, which has a custom tab header and the active screen. I'm trying to send information to the current active screen when a button in the header is clicked, but can't get the params to make it to the current screen.

@brentvatne

**Comment by brentvatne** [comment]
1) you can't access it from the header, the param is available on a specific route
2) i'm surprised that params are passed through at all in the case where you navigate to a stack navigator rather than a specific route in it. that seems like a bug to me. you should only get params when you navigate to a specific route within a navigator, not to a route that belongs to a navigator, in that case the params should be for that navigator and not for any of the children

see here https://snack.expo.io/rJHRPQNzm

**Comment by brentvatne** [comment]
discussion around this should carry on in https://github.com/react-navigation/rfcs/issues/43

**Comment by vjsingh** [comment]
Hey @brentvatne,

Thanks for the quick response. I'm happy to discuss in that other issue, but I want to understand the problem first.

I actually do want to navigate to a specific route on the navigator. Here is a stack with that example: https://snack.expo.io/SkD0qm4GX

But, in that stack I'm still not seeing the name param being passed to the child view. Is there something I'm doing wrong?

**Comment by vjsingh** [comment]
Any updates or ideas on this? Should I make a new issue?

**Comment by brentvatne** [comment]
why not use the same thing i shared in the above snack?

```
        <Button
          title="Second"
          onPress={() => navigate('SecondView', { name: 'Jo' })}
        />
```

**Comment by vjsingh** [comment]
OK, I think I understand you now. The good news is it is working now in my app. A couple lingering questions:

Snack: https://snack.expo.io/Hyth2UtMm

1. Is this correct for CustomTabView? Passing in two different navigators, one to the custom header and a different one to the active screen? It appears to be working. (line 101 in snack)
<CustomTabHeader navigation={navigation} />
      <ActiveScreen navigation={descriptor.navigation} />

2. Given the below setup:
const CustomTabRouter = TabRouter({
  FirstView,
  HeaderStack,
});
const HeaderStack = createStackNavigator(
  {
    SecondView,
    ThirdView
  },
);

How come A works but not B (from the custom header) (line 84 in snack()
A: navigate('ThirdView', {name: 'Jo'})
B: navigate('HeaderStack', {}, {
           type: 'Navigate',
           routeName: 'ThirdView',
           params: {name: 'Coming from Header'}
        })

Thank you for your help @brentvatne, it is massively appreciated.

**Comment by vjsingh** [comment]
I managed to fix my second question by using NavigationActions.navigate instead of an object:

       navigate('HeaderStack', {}, NavigationActions.navigate({ routeName: 'ThirdView', params: {name: 'coming from header'} }))

https://snack.expo.io/By_XYnszm
