### ISSUE TITLE
Can't specify a headerLeft component when at the starting index of a StackNavigator

### ISSUE THREAD

**Issue by Nickersoft** [react-navigation/react-navigation#4608]
### Current Behavior
Just upgraded to v2. I found that I can no longer specify a `headerLeft` component in the StackNavigator when the scene index is at zero due to [this line](https://github.com/react-navigation/react-navigation/blob/3d06d19d6add53e8951e8f0bc793bf2bb8946940/src/views/Header/Header.js#L144).

### Expected Behavior
To maintain consistency with the previous version of my app, I need to be able to specify this component on the main screen, before navigation occurs. I am not sure if with v2 the API changed and there is now a preferred other way of achieving this.

### How to reproduce
1. Create a new StackNavigator
2. Assign it a `headerLeft` component in `navigationOptions`
3. Navigate between scenes, and the component should not render on the initial scene

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.4.1
| react-native     | 0.55.4
| node             | 8.11.3
| npm or yarn      | 1.7.0

Is there a known workaround to this issue?

**Comment by simonedavico** [comment]
Stuck for the same reason, the rendering logic for `headerLeft` will happily render an Element but will skip on the scene with index 0 if I pass a Component.

**Comment by simonedavico** [comment]
For anyone bumping into this, I modified [this line](https://github.com/react-navigation/react-navigation/blob/3d06d19d6add53e8951e8f0bc793bf2bb8946940/src/views/Header/Header.js#L144) into

```
if (props.scene.index === 0 && !options.headerLeft) {
```

**Comment by ericvicenti** [comment]
thanks @papasmurf17  for the fix!
