### ISSUE TITLE
React Navigation transparent bar missing title and buttons on android

### ISSUE THREAD

**Issue by tfsjohan** [react-navigation/react-navigation#4612]
I'm building a `React Native` app with `React Navigation 2.5.x`. I have a transparent navigation bar. On iOS everything is fine, but on Android the title, back button and any barButton I put there is missing. It's like I had set header: null. 

The navigation options is defined like this:

    const navigationOptions = {
        headerStyle: {
            borderBottomWidth: 0,
        },
        headerTransparent: true,
        headerTintColor: Colors.barTintColor,
    };

If I try to inspect the view I get the header component when tapping, but on Android I get the scenes content view instead. 

Previously I had the header style positioned absolutely and a transparent background color. **I would like the bar to be transparent and visible above the rest of content screen.** But positioning it absolutely, setting headerMode och headerTransparent all makes the headers disappear.

This seems like a bug on the Android implementation.

**Comment by jfdominguezp** [comment]
+1

**Comment by KubaGL** [comment]
I have the same issue, everything works fine on ios but header on android is not there.

**Comment by mikeygee** [comment]
Just spent too long chasing this down, appears to be a regression from 2.5.3 to 2.5.4. I see some header related commits there.

**Comment by KubaGL** [comment]
I can confirm that it works fine in 2.5.3

**Comment by dluksza** [comment]
I'm experiencing the same issue. It seams to exist from 2.5.4 up to 2.6.0. Reverting to 2.5.3 is solving it.

I've did small investigation with the inspector and it seams that buttons (and whole menu bar) is rendered underneath screen. Unfortunately adding `zIndex: 10` didn't fixed it in my case.

**Comment by Maxence-Machu** [comment]
Same issue for us, i'm reverting

**Comment by brentvatne** [comment]
works as expected for me on 2.6.1

<img width="941" alt="screen shot 2018-07-05 at 3 15 22 pm" src="https://user-images.githubusercontent.com/90494/42350663-4ecb9b7e-8066-11e8-9de0-d9f4a86d6150.png">

```
import { createStackNavigator } from 'react-navigation';
import React, { Component } from 'react';
import { Text, View } from 'react-native';

class Demo extends Component {
  static navigationOptions = {
    headerStyle: {
      borderBottomWidth: 0,
      backgroundColor: 'rgba(0,0,0,0.2)',
      elevation: 0,
    },
    headerTransparent: true,
    headerTintColor: '#000',
    headerLeft: <Text>left</Text>,
    title: 'title',
    headerRight: <Text>right</Text>,
  };
  render() {
    return (
      <View
        style={{
          flex: 1,
          backgroundColor: 'powderblue',
        }}
      />
    );
  }
}

const RootNavigator = createStackNavigator({
  Home: Demo,
});

export default RootNavigator;
```

if you are still having this issue then you will need to create a new issue with a repro as per the issue template. thank you!
