### ISSUE TITLE
NavigationActions.reset is not a function after updating react-navigation

### ISSUE THREAD

**Issue by bgold0** [react-navigation/react-navigation#4613]
I was recently on version `1.5.8` and the following code worked:

    import { NavigationActions } from 'react-navigation';

    const actionToDispatch = NavigationActions.reset({
	  index: 1,
	  actions: [
	    NavigationActions.navigate({ routeName: 'Home'}),
	    NavigationActions.navigate({ routeName: 'Settings'})
	  ]
	})
	this.props.navigation.dispatch(actionToDispatch)

Now I updated to `2.5.5` and I get the following error:

> TypeError: _reactNavigation.NavigationActions.reset is not a function

Is there a new way to reset the navigation now?

**Comment by barbieri** [comment]
`StackActions.reset()` is your friend.

**Comment by bgold0** [comment]
@barbieri so it works the same way as the above?

**Comment by barbieri** [comment]
@bgold0 yes, just hosted in a better namespace (the string is even the same).

**Comment by TranVanThaiSon** [comment]
import { NavigationActions, StackActions } from 'react-navigation';
const resetAction = StackActions.reset({
          index: 0,
          actions: [
            NavigationActions.navigate({ routeName: 'App'})
          ],
        });
        this.navigation.dispatch(resetAction);
I it hope help someone

**Comment by kumarideepika** [comment]
> StackActions.reset()

Its not working
_native.stackAction.reset is not a function

**Comment by brentvatne** [comment]
@kumarideepika - see the docs, this is not on stackactions anymore: https://reactnavigation.org/docs/stack-actions/

it's here: https://reactnavigation.org/docs/navigation-actions/#reset
