### ISSUE TITLE
How to restart stacks to re-render all the screen components?

### ISSUE THREAD

**Issue by kolyneh** [react-navigation/react-navigation#4614]
### Current Behavior

- What code are you running and what is happening?
   We have navigation schema :
  ````
  const AppStack = createStackNavigator({
    Home: {
        screen: HomeTabNav,
    },
    Setting: SettingScreen,
    Language: SettingLanguageScreen,
    }, {
      navigationOptions: {
        headerBackImage: back,  
     },
    initialRouteName: 'Home',
   });

   const StartSwitch = createSwitchNavigator({
    Starting: App, 
    App: AppStack,  
    Auth: AuthStack, 
    Preview: PreviewScreen, 
   }, {
       initialRouteName: 'Starting',
  });

  ````

 Now it's in 'App' stack 'Language' screen, we setup the display language, and then need to re-render all the screen components to make the language setting  take effects. (For example, restart to 'Starting', )

 How to restart it?
 
 We used  `react-native-navigation` before, 
 And it provides Api `Navigation.startSingleScreenApp` to start (or restart) a new stack of the whole app.

 How can we do it using `react-navigation`?

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.5.5
| react-native     | 0.55.4
| node             | 8.9
| npm or yarn      | 5.6.0

**Comment by brentvatne** [comment]
here's an example of using i18n https://github.com/i18next/react-i18next/blob/master/example/react-native-expo/App.js

**Comment by s349856186** [comment]
> here's an example of using i18n https://github.com/i18next/react-i18next/blob/master/example/react-native-expo/App.js

@brentvatne The example is 404, 3.x dynamic change tabBarLabel ?  Thanks
