### ISSUE TITLE
How to center headerTitle on Android?

### ISSUE THREAD

**Issue by kolyneh** [react-navigation/react-navigation#4615]
### Current Behavior

- What code are you running and what is happening?
````
 static navigationOptions = ({navigation}) => {
        return {
            title: strings.device,
            headerTitleStyle: {
                textAlign: 'center',
                backgroundColor: 'red',
                flexGrow:1,
                alignSelf:'center',
            },
            headerStyle: {
                paddingHorizontal: 8,
            },
            headerRight: (
                <HeaderButtons>
                    <HeaderButtons.Item
                        title="add"
                        buttonWrapperStyle={{padding: 6}}
                        IconElement={<Image source={i_add}/>}
                        onPress={(event) => navigation.getParam('onRightBtnPress')(event)}
                    />
                </HeaderButtons>
            )
        };
    };
````
- Include a screenshot if it makes sense.
 
![tim 20180701133434](https://user-images.githubusercontent.com/13062910/42131413-2d87d188-7d34-11e8-836f-c700e8053577.png)

### Expected Behavior

- What do you expect should be happening?
  The headerTitle is centered on Android like it appears on iOS.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.5.5
| react-native     | .055.4
| node             | 8.9
| npm or yarn      | 5.6.0

**Comment by proutek** [comment]
Hello. I did it on android with empty headerRight and formatting of content in center. It's not best solution but it worked ok in my case.

**Comment by kolyneh** [comment]
@proutek Thanks!
It's OK if there is no headerRight. But I need headerRight buttons.

**Comment by Amurmurmur** [comment]
@kolyneh Why dont you just do something like:
```
position: 'absolute',
left: screenWidth / 2,
top: 27
```

**Comment by kolyneh** [comment]
@Amurmurmur It's not working, still not in center.
Your have `left:screenWidth/2` but title have it's own width, we can't get it for it's not referenced by us.

**Comment by zxccvvv** [comment]
Just use your `headerRight style` to your `headerLeft style` but leave empty `<View>`

```
static navigationOptions = ({navigation}) => {
        return {
            title: strings.device,
            headerLeft:<View style={{padding:6}}></View> //add this
            headerTitleStyle: {
                textAlign: 'center',
                backgroundColor: 'red',
                flexGrow:1,
                alignSelf:'center',
            },
            headerStyle: {
                paddingHorizontal: 8,
            },
            headerRight: (
                <HeaderButtons>
                    <HeaderButtons.Item
                        title="add"
                        buttonWrapperStyle={{padding: 6}}
                        IconElement={<Image source={i_add}/>}
                        onPress={(event) => navigation.getParam('onRightBtnPress')(event)}
                    />
                </HeaderButtons>
            )
        };
    };
```

**Comment by kolyneh** [comment]
@zxccvvv Good idea! Thanks!

**Comment by kolyneh** [comment]
Hope the team will give us official work around.

**Comment by zxccvvv** [comment]
@kolyneh glad to help, you can close the issue then :)

**Comment by brentvatne** [comment]
this is wip to make this easier https://github.com/react-navigation/react-navigation/pull/4588

**Comment by samparhizkar** [comment]
To everyone still having this issue. This is how I fixed on android.
`const navOptions = {
    headerTitleStyle: {
        color: 'white',
        alignSelf: 'center',
        textAlign: "center",
        justifyContent: 'center',
        flex: 1,
        fontWeight: 'bold',
        textAlignVertical: 'center'
    },
    headerTitle:    <Image source={require("../assets/images/drawer/Stars.Club.png")} resizeMode={'contain'} style={{ height: 15, alignSelf: "center", marginLeft: "auto", marginRight: "auto"}}/>,


    headerStyle: {
        backgroundColor: colors.darkSlateBlue
    },
    headerTintColor: "white",
};`

It is important to have ` marginLeft: "auto", marginRight: "auto"` in your style.

**Comment by brentvatne** [comment]
the correct solution is to use `headerLayoutPreset`, eg: `createStackNavigator(routes, { headerLayoutPreset: 'center' })`
