### ISSUE TITLE
Should warn when using padding in headerStyle

### ISSUE THREAD

**Issue by kolyneh** [react-navigation/react-navigation#4616]
### Current Behavior

- What code are you running and what is happening?
  I have this headerStyle:
  ````
   const AppStack = createStackNavigator({
    Home: {
        screen: HomeTabNav,
    },
    Control: ControlTabNav,
    AddDevice: DeviceAddScreen,
    Info: {
        screen: DeviceInfoScreen,
        navigationOptions: {
            title: 'Info',
        }
    },
  }, {
    navigationOptions: {
        headerBackImage: back,   
        headerStyle: {
            paddingHorizontal: 8,
            //paddingLeft:8,
           // paddingRight:8,
        },
    },
    initialRouteName: 'Home',
  });
  ````
  Screenshot:
  
![tim 20180701141327](https://user-images.githubusercontent.com/13062910/42131640-04099bf2-7d39-11e8-9891-de479c0d67f6.png)

 If add `marginHorizontal` into headerStyle:
 ````
 navigationOptions: {
        headerBackImage: back,
        headerStyle: {
            paddingHorizontal: 8,
            marginHorizontal:8,
        },
    },
 ````
 ScreenShot:
 
![tim 20180701141332](https://user-images.githubusercontent.com/13062910/42131651-336d9470-7d39-11e8-9e77-74285737bf29.png)

 Seems `paddingHorizontal`, `paddingLeft` or `paddingRight` is not working, but `marginHorizontal`.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.5.5
| react-native     | 0.55.4
| node             | 8.9
| npm or yarn      | 5.6.0

**Comment by brentvatne** [comment]
left / title / right components are absolute positioned so padding has no impact. we should warn here https://github.com/react-navigation/react-navigation/blob/master/src/views/Header/Header.js#L479-L487

**Comment by kolyneh** [comment]
@brentvatne How about add `marginLeft` to `headerLeft`'s container component, or make it customizable.

**Comment by brentvatne** [comment]
I added a warning to this now: https://github.com/react-navigation/react-navigation/commit/dc436e4d01b442bbca6f66804997b40139349c47

why not just add the margin / padding in the custom headerLeft / headerRight components?

**Comment by yiky84119** [comment]
@brentvatne if we set transparent status bar in Android, we need set paddingTop to Header.

no paddingTop
![1](https://user-images.githubusercontent.com/3356845/42368934-f236d952-813a-11e8-9f17-d637cdd0ca7e.png)

set marginTop looks good, but backgroudcolor is not white
![2](https://user-images.githubusercontent.com/3356845/42368942-fc0ff670-813a-11e8-930b-de792ceb4804.png)

**Comment by brentvatne** [comment]
@yiky84119 - this should be handled automatically by SafeAreaView but it isn't yet. you can do this for now.

```
import { Platform, StatusBar } from 'react-native';
import { SafeAreaView } from 'react-navigation';

if (Platform.OS === 'android') {
  SafeAreaView.setStatusBarHeight(StatusBar.currentHeight);
} 
```

**Comment by brentvatne** [comment]
@yiky84119 - that said, I removed the warning against paddingVertical, paddingTop and paddingBottom in 2.6.2 for you

**Comment by makhardy** [comment]
@kolyneh  You can use "paddingStart" instead of using paddingLeft or marginLeft, It works.
```
headerStyle: {
          paddingStart: 8, 
          //marginLeft: 8,
          //paddingLeft:8,
         // paddingRight:8,
      },
```

**Comment by kolyneh** [comment]
@makhardy Thanks!

**Comment by andreicruz** [comment]
> @makhardy Thanks!

Heeey kolyneh, using 'paddingStart' this works for you? I'm still having warning even using paddingStart.

**Comment by kolyneh** [comment]
@andreicruz Hi, I've upgraded to version 4.x. I'll check if 'paddingStart' works on version 2.x.

**Comment by rageon-chlela** [comment]
you can use headerLeftContainerStyle to set the left margin, for example
`defaultNavigationOptions: {
      headerLeftContainerStyle: { marginLeft: 20 }
    },`

**Comment by SamerIstambouli** [comment]
You can use headerLeftContainerStyle to set the left margin for the header
`defaultNavigationOptions: {
      headerLeftContainerStyle: { margin: 20 },
    },`

**Comment by GusMartins499** [comment]
Hi, my name is Gustavo, i'm from Brazil and i'm not fluent english yet. Someone can help me ? I have this component:
```
import React from 'react';
import { NavigationContainer } from '@react-navigation/native';
import { createStackNavigator } from '@react-navigation/stack';

import OrderOfService from './pages/OrderOfService/index';
import Detail from './pages/Detail/index';
import Login from './pages/Login/index';
import Menu from './pages/Menu/index';
import Produtos from './pages/Produtos/index';

const AppStack = createStackNavigator();

export const Routes: React.FC = () => {
    return (
        <NavigationContainer >
            <AppStack.Navigator initialRouteName="login" screenOptions={{ headerShown: true }}>
                <AppStack.Screen
                    name="login"
                    component={Login}
                    options={{
                        headerShown: false
                    }}
                />
                <AppStack.Screen
                    name="Menu"
                    component={Menu}
                    options={{
                        headerShown: false
                    }}
                />
                <AppStack.Screen
                    name="OS"
                    component={OrderOfService}
                    options={{
                        title: "Ordens de serviço",
                        headerTitleStyle: { color: '#15325a' },
                        headerTintColor: '#15325a',
                    }}
                />
                <AppStack.Screen
                    name="Detail"
                    component={Detail}
                    options={{
                        title: "Detalhes da OS",
                        headerTitleStyle: { color: '#15325a' },
                        headerTintColor: '#15325a',
                    }}
                />
                <AppStack.Screen
                    name="Produtos"
                    component={Produtos}
                    options={{
                        title: "Produtos",
                        headerTitleStyle: { color: '#f27235' },
                        headerTintColor: '#f27235',
                        headerStyle: {
                            backgroundColor: '#15325a',
                            paddingStart: 8
                        },
                    }}
                />
            </AppStack.Navigator>
        </NavigationContainer>
    )
}
```

But when i using padding or margin in headerstyled is not work. I'm using Expo.

Screenshot:

![Screenshot_20210106-084304](https://user-images.githubusercontent.com/43645525/103766136-10140600-4ffd-11eb-99d4-2d994673b627.png)

this is my dependencies:

```
  "dependencies": {
    "@expo/vector-icons": "^12.0.2",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-native-picker/picker": "^1.9.8",
    "@react-navigation/bottom-tabs": "^5.11.2",
    "@react-navigation/drawer": "^5.11.4",
    "@react-navigation/native": "^5.8.10",
    "@react-navigation/stack": "^5.12.8",
    "@types/styled-components-react-native": "^5.1.0",
    "expo": "~40.0.0",
    "expo-constants": "~9.3.3",
    "expo-status-bar": "~1.0.3",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz",
    "react-native-gesture-handler": "~1.8.0",
    "react-native-picker-select": "^8.0.4",
    "react-native-reanimated": "^1.13.2",
    "react-native-safe-area-context": "^3.1.9",
    "react-native-screens": "~2.15.0",
    "react-native-svg": "^12.1.0",
    "react-native-web": "~0.13.12",
    "react-number-format": "^4.4.1",
    "styled-components": "^5.2.1"
  },
```

thank you very much

**Comment by cpres** [comment]
I was able to solve this by using safeareaInsets:
```
<Stack.Screen
      name="Menu"
      component={Menu}
      options={{headerShown: true, 
        safeAreaInsets: {top:0},
        title: "Sweet Menu"}}
    />
```
