### ISSUE TITLE
Reduce speed of drawer open

### ISSUE THREAD

**Issue by saeedhei** [react-navigation/react-navigation#4618]
I'm using `createDrawerNavigator` with your library.

How to reduce the speed of drawer open?
```js
    const DrawerStack = createDrawerNavigator(
      {
        Home: {
          screen: HomeStack,
        },
        About: {
          screen: Screen2Stack,
        },
      },
      {
        initialRouteName: 'Home',
        contentOptions: {
          activeTintColor: '#e91e63',
        },
        drawerWidth: 300,
      }
    );
```

**Comment by brentvatne** [comment]
not possible with current api, would need to submit a pr to https://github.com/react-navigation/react-navigation-drawer or open a feature request at http://reactnavigation.canny.io/

**Comment by crystalarcus** [comment]
Hello there,, It's been 5 years, is there a way to control drawer speed ?  I  really need to reduce speed of drawer navigator's drawer.
