### ISSUE TITLE
Require API to block pressing headerBackImage to pop.

### ISSUE THREAD

**Issue by kolyneh** [react-navigation/react-navigation#4619]
Require API to block pressing headerBackImage to pop.

We need to do something after headerBackImage is pressed. 

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.5.5
| react-native     | 0.55.4
| node             | 8.9
| npm or yarn      | 5.6.0

**Comment by brentvatne** [comment]
render a custom back button and do whatever you like! if you'd like to propose an api to make this easier then please refer to https://github.com/react-navigation/rfcs
