### ISSUE TITLE
passing params to TabNavigator that being rendered inside another screen

### ISSUE THREAD

**Issue by obiwankenoobi** [react-navigation/react-navigation#4621]
### Current Behavior

I have `TabNavigator` that is being render inside another screen. I navigate to the screen using:

```
this.props.navigation.navigate('VisitUserPageNew',{
    visitorProps: {
      visitorNickName:this.props.linkPublisherNickName,
      visitor:true
    }
})
```
as you can see I am passing some params to that screen, when the screen is rendered Im fetching the params this way: 

`visitorProps = this.props.navigation.getParam('visitorProps')`
then if I `console.log(this.visitorProps)` it return my props and everything is fine.

The problem is that I have in this screen another component which is a `TabNavigator` and Its rendered together with this screen.  The propose of this `TabNavigator` is creating this behavior #903. It works ok, I do get the worning 

> you should only render one navigator explicitly in your app

but I read here #4196 that it might be a bug , so I didnt payed attention to it. 

Now I need to pass to this `TabNavigator` the props I passed to the screen and I can't make it work. I tried inside each of the screens that being rendered inside the `TabNavigator` call `visitorProps = this.props.navigation.getParam('visitorProps')` again without much luck. Then I tried to pass the props like this: 

```
          <UserSection
            someTest={'sometest'}
            visitorProps={this.visitorProps}
          /> 
```
and I still get `undefined` . Am I doing something wrong here? I tried to ask in [SO](https://stackoverflow.com/questions/51133318/passing-params-to-nested-tabnavigator) but couldnt get any answer. 

CODE:

```
export const UserSection = createMaterialTopTabNavigator({

    UserFeed: {
        screen: UserLinks,
    },
    Saved: {
        screen: UserBookmarks,
    },

})

export const UserPageNew = StackNavigator({
    UserSectionPage: {
        screen: UserPage
    },
    UserSection: {
        screen: UserSection
    },
})

export const Home = StackNavigator({
    Main: {
        screen: Main
    }, 
    VisitUserPageNew: {
        screen: UserPageNew
    },
})

this.props.navigation.navigate('VisitUserPageNew',{
    visitorProps: {
      visitorNickName:this.props.linkPublisherNickName,
      visitor:true
    }
})


class UserPage extends Component {
    visitorProps = this.props.navigation.getParam('visitorProps')

    render() {
        console.log(this.visitorProps) // return the object I need
        return(
            <View style={styles.container}>

                <Text>Text</Text>

                <View  style={{width:'100%',height:'100%',flex:1}}>
                    <UserSection
                        visitorProps={this.visitorProps}
                    />
                </View>    
            </View> 
        )
    }
} 

export default class UserLinks extends Component {

    render() {
        console.log(this.props.visitorProps) // return undefined
        return;
    }

}

export default class UserBookmarks extends Component {

    render() {
        console.log(this.props.visitorProps) // return undefined
        return;
    }

}
```

### Expected Behavior

the props will be passed to the rendered `TabNavigator` from the rendered screen

**Comment by ericvicenti** [comment]
You cannot use the `UserSection` navigator within `UserPage` without passing through the navigation prop, and exposing the `static router`

https://reactnavigation.org/docs/en/common-mistakes.html#explicitly-rendering-more-than-one-navigator
