### ISSUE TITLE
Android back button doesn't work as navigation.goBack()

### ISSUE THREAD

**Issue by aroucha-miguel** [react-navigation/react-navigation#4623]
### Current Behavior

Using a structure of a StackNavigator with a TabNavigator as its initial route and a ScreenModal, Android back button misbehaves when returning from the ScreenModal to the TabNavigator.

Back Button closes the modal, returns the TabNavigator to its initial route and "freezes". With more screens stacked, a press on Android back button returns all the way to the inital route and "freezes".

If the modal is open from TabNavigator initial route, the modal is closed and the TabNavigator continues working normally. Programmatically calling navigation.goBack(), it works as expected.

### Expected Behavior

Android Back Button should have the same behaviour as this.props.navigation.goBack();

### How to reproduce

Expo snack example: https://snack.expo.io/SJbXZqvMQ
Just have to play around with it.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^2.4.1

**Comment by mbloody** [comment]
Some issues with react-navigation 2.5.5.

**Comment by brentvatne** [comment]
Android back button behavior is the same as `this.props.navigation.goBack(null)` but not this.props.navigation.goBack()`

**Comment by aroucha-miguel** [comment]
Hey Brent,
Thanks for the quick fact check. Indeed changing the code to programmatically `this.props.navigation.goBack(null)` it has the same behaviour as the android back button. That is, it crashes the navigation.

However, I still feel like the android back button should mimic the `goBack()` behaviour, as it reflects the desired action by an end user (`goBack(undefined)` also creates this desired action), instead of crashing/freezing the app.

Is there some kind of limitation or other explanation to why the back button follows this behaviour that crashes the app?

**Comment by kilidon** [comment]
Is there no solution?

**Comment by aroucha-miguel** [comment]
From my understanding, it would be needed to manage the android back button on all screens with react native BackHandler, which can be overwhelming on a complex app with lots of screens.

Or to prevent the freeze/crash, add a `backBehavior: 'none',` to the TabNavigator `TabNavigatorConfig` as suggested by kolyneh in https://github.com/react-navigation/react-navigation/issues/4625. The downside is that pressing back it will not return to the TabNavigator initial route.

**Comment by brentvatne** [comment]
you can think of `navigation.goBack(null)` to `navigation.globalGoBack()` and `navigation.goBack()` as `navigation.localGoBack()` where by local i mean it applies to the route that it's being called on

**Comment by brentvatne** [comment]
> That is, it crashes the navigation.

can you create a new issue that describes this problem? probably should be fine to modify the snack from this issue for it. thanks!

**Comment by aroucha-miguel** [comment]
Hey!
It seems that the above PR (#4635) fixes the problem I was having. I believe the issues https://github.com/react-navigation/react-navigation/issues/4625 and https://github.com/react-navigation/react-navigation/issues/4626 are also related to this.
Thanks for the great work, will be looking for the new release with this fix.
Cheers

**Comment by eshantbist** [comment]
> From my understanding, it would be needed to manage the android back button on all screens with react native BackHandler, which can be overwhelming on a complex app with lots of screens.
> 
> Or to prevent the freeze/crash, add a `backBehavior: 'none',` to the TabNavigator `TabNavigatorConfig` as suggested by kolyneh in #4625. The downside is that pressing back it will not return to the TabNavigator initial route.

Hey,
Can you show some example where BackHandler is used for navigation because Backandler needs a function which writes true or false. How can we add navigation properties to it.
