### ISSUE TITLE
Incorrect goBack() with BottomTabNavigator

### ISSUE THREAD

**Issue by barbieri** [react-navigation/react-navigation#4625]
### Current Behavior

Given the navigation structure:
 - Stack Navigator
   - Tab Navigator
      - Main Tab (initial route)
      - Second Tab
   - Stand Alone Navigator (Stack)
      - Stand Alone Route

Given the events:
 1. navigate to second tab
 2. navigate to stand alone route (not a direct sibling inside Tab Navigator)
 3. navigate back `goBack(null)`

This is navigating back to the Tab Navigator (as expected), but using the Main Tab (initial route), not the last selected tab (Second Tab).

### Expected Behavior

- Second tab should be selected

This was the case with 2.5.4 (commit c7fff52408bc5cd4d88a636d1053564289e150c1 broke it).

### How to reproduce

https://snack.expo.io/BywyJGdMX

```js
import React from 'react';
import { View, Text, Button } from 'react-native';
import {
  createStackNavigator,
  createBottomTabNavigator,
} from 'react-navigation';

const B = ({ children }) => (
  <Text style={{ fontWeight: 'bold' }}>{children}</Text>
);

const MainTab = ({ navigation }) => (
  <View>
    <Text>
      <B>MainTab</B>: go to SecondTab
    </Text>
    <Button
      title="navigate"
      onPress={() => navigation.navigate({ routeName: 'SecondTab' })}
    />
  </View>
);
MainTab.navigationOptions = { title: 'MainTab' };

const SecondTab = ({ navigation }) => (
  <View>
    <Text>
      <B>SecondTab</B>: go to StandAlone
    </Text>
    <Button
      title="navigate"
      onPress={() => navigation.navigate({ routeName: 'StandAlone' })}
    />
  </View>
);
SecondTab.navigationOptions = { title: 'SecondTab' };

const StandAlone = ({ navigation }) => (
  <View>
    <Text>
      <B>StandAlone</B>: go back. Should go to <B>SecondTab</B>
      (last selected/active)
    </Text>
    <Button title="Back!" onPress={() => navigation.goBack(null)} />
  </View>
);
StandAlone.navigationOptions = { title: 'StandAlone' };

const StandAloneNavigator = createStackNavigator({
  StandAlone,
});

const TabNavigator = createBottomTabNavigator({
  MainTab,
  SecondTab,
});
TabNavigator.navigationOptions = { title: 'TabNavigator' };

export default createStackNavigator(
  {
    TabNavigator,
    StandAloneNavigator,
  },
  {
    initialRouteName: 'TabNavigator',
  }
);
```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.5.5
| react-native     | 0.55.4
| node             | 9.2.0
| yarn      | 1.7.0

**Comment by kolyneh** [comment]
@barbieri Hi barbieri ,
You should add `backBehavior: 'none',` to your `TabNavigator`.
For more : [https://reactnavigation.org/docs/en/bottom-tab-navigator.html](url)

**Comment by barbieri** [comment]
@kolyneh not really. When I'm in my TabNavigator I do want a Back to go back to initial route once it was a top most route (ie: back -> pop to root; second back -> initial screen, using Android's back button).

My structure follows the recommended (AFAIU) layout to cope with some screens inside the tab, some screens without the tab bar using modal animations and others without the tab bar with card animation (on iOS), at the end the app looks like:

 - App Navigator
    - Logged In Navigator (stack)
       - switch of modal routes (or sub navigators), those without the tab bar and with modal animation
       - stack of stand alone routes, with card animation
          - tab bar (hosted as initial route)
             - home route (hosted as initial route inside tab bar)
             - profile
             - other tab bar routes or navigators
          - some dialogs to show as "card" animation, without tab bar (ie: filter selection)
    - Logged Out Navigator (stack)
       - Login Screens (social, forgot my password...)

I understood this structure from https://reactnavigation.org/docs/en/navigation-options-resolution.html Let me know if I got it wrongly.

**Comment by kolyneh** [comment]
@barbieri 
Have you try it?
Seems it's some issue with the TabNavigator if it's hosted as initial route, it will listen the backPress event even it's not on the top stack.
But with `backBehavior: 'none'` options set, it will behaves like you need.

I add a new issue #4626 
In my case, the screen will freeze when push to another stack from TagNavigator's second tab then back to the TabNavigator using Android's back button.

**Comment by barbieri** [comment]
@kolyneh I just tested and it seems to work with `backBehavior: 'none'`, however is this expected? Why is it handling "back" if I set its behavior to "none"? Seems to me like another bug, or at least something that is undefined and would break in future releases. Documentation says:

> `backBehavior` - Should the back button cause a tab switch to the initial tab? If yes, set to `initialRoute`, otherwise `none`. Defaults to `initialRoute` behavior.

**Comment by kolyneh** [comment]
@barbieri  
 'Cause pressing `headerLeft` button won't have this problem, I think the TabNavigator who's bellow the top stack will listen the hardware 'backPress' event.
But `backBehavior` is only expected to take effect when the TabNavigator is on top stack.

**Comment by barbieri** [comment]
@kolyneh are you sure about that? I didn't look into all the react-navigation codebase, but from their docs and some code I've seen, the back handler is done when the first navigator is created and will dispatch actions `NavigateActions.goBack(null)`, which are handled the same. The tab navigator is not (AFAIU) listening for the back button, it just get to process the request.

What seems to be wrong in the handling with my use case is that the current screen `Stand Alone Route` is *NOT* in the same direct hierarchy as the previously active route `Second Tab`, thus the `Tab Navigator` (parent of `Second Tab`) is getting the event, while `Second Tab` should.

Test Case Hierarchy
```
- Stack Navigator
  +-> Tab Navigator
  |   +-> Main Tab (initial route)
  |   +-> Second Tab [Previously Selected]
  + Stand Alone Navigator (Stack)
      +-> Stand Alone Route   [Currently Selected]
```

Code from c7fff52408bc5cd4d88a636d1053564289e150c1 says:
```js
        // Traverse routes from the top of the stack to the bottom, so the
        // active route has the first opportunity, then the one before it, etc.
        for (let childRoute of state.routes.slice().reverse()) {
```

This means visiting:
 1. Stack Navigator (root), which recurses
 2. Stand Alone Navigator (stack), which has no child router for Stand Alone *Route* (since it's a single screen, not another navigator)
 3. proceed with the sibling Tab Navigator, which handles "back" action as going back "initial route"

To me, there is a missing step between 2 and 3. Since the root navigator is a stack on its own, it shouldn't propagate to the sibling (Tab Navigator), just change the index to "previous - 1". Looking at the rest of `StackRouter.js` we see:

```js
      if (
        action.type === NavigationActions.BACK ||
        action.type === StackActions.POP
      ) {
        const { key, n, immediate } = action;
        let backRouteIndex = state.index;
        if (action.type === StackActions.POP && n != null) {
          // determine the index to go back *from*. In this case, n=1 means to go
          // back from state.index, as if it were a normal "BACK" action
          backRouteIndex = Math.max(1, state.index - n + 1);
        } else if (key) {
          const backRoute = state.routes.find(route => route.key === key);
          backRouteIndex = state.routes.indexOf(backRoute);
        }

        if (backRouteIndex > 0) {
          return {
            ...state,
            routes: state.routes.slice(0, backRouteIndex),
            index: backRouteIndex - 1,
            isTransitioning: immediate !== true,
          };
        }
      }
```
In my case, `backRouterIndex === 0`.

**Comment by barbieri** [comment]
Seems e8c1833053e37d28f0ce505ff323565abf23b6a2 fixed it!

**Comment by b3hz4d** [comment]
> @barbieri Hi barbieri ,
> You should add `backBehavior: 'none',` to your `TabNavigator`.
> For more : [https://reactnavigation.org/docs/en/bottom-tab-navigator.html](url)

I want to navigate back from TabNavigator to the previous screen (TabNavigator was pushed to screen like Instagram) and this one is the exact thing that can get worked
Thank you <3

**Comment by joaoSouza-js** [comment]
guys, if you wanna goback  to previous screen use backBehavior as history

`<AppRootTab.Navigator
      backBehavior='history'
        screenOptions={{
          headerShown: false,
          tabBarShowLabel: false,
          tabBarStyle: {
            height: insets.bottom > 0 ? 85 : 75,
            paddingTop: insets.bottom > 0 ? 0 : 10,
            paddingBottom: insets.bottom > 0 ? 15 : 10
          }
        }}
      >`
