### ISSUE TITLE
react-native init Myawesomeapp with "npm i --save react-navigation" deleted some file in node_modules/react-native

### ISSUE THREAD

**Issue by zxccvvv** [react-navigation/react-navigation#4627]
## The issue tracker is reserved for bug reports only.

---

### Expected Behavior

**Running as default**

### How to reproduce

I just create a new project with `RN init myapp` and installing `react-navigation` with `react-native-vector-icons` but i don't know why when i try to run `react-native link`

the cmd showing 

> Command `link` unrecognized. Make sure that you have run `npm install` and that you are inside a react-native project.

so i run `react-native --version` and the cmd showing:

> react-native-cli: 2.0.1
react-native: n/a - not inside a React Native project directory

when i check the `./node_modules/react-native` i only have these file:

![image](https://user-images.githubusercontent.com/19633881/42198277-2be243c6-7eb1-11e8-8f76-668f7030dc50.png)

am i doing something wrong?

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.5.5
| react-native     | 0.55.4
| node             | 5.6.0
| npm or yarn      | both

**Comment by brentvatne** [comment]
post an issue to npm maybe?

**Comment by zxccvvv** [comment]
Can you take a look at this issue https://github.com/oblador/react-native-vector-icons/issues/726 @brentvatne ?
