### ISSUE TITLE
tabBarIcon not called in static navigationOptions

### ISSUE THREAD

**Issue by waloc** [react-navigation/react-navigation#4630]
Hello,

Thanks for this awesome project.

After upgrading from version 1 to version 2, all my tabbaricons disappear.

I set it like that in each screen:

```
static navigationOptions = {
		header: null,
		tabBarIcon: ({focused}) => {
			console.log('TABBAR ICON')
			return <MenuIcon focused={focused} name='pin'/>
		}
	}
```

If i set the tabbaricon at the tabbarbottom creation it works but not in separate files.

Also, if I pass a function in static navigationOptions for header like: 
```
static navigationOptions = {
		header: () => console.log('hello'),
                ...
}
```

It's working, i have "hello" in the console. But this doesn't work with tabBarIcon, so maybe we can do the same as header for tabBarIcon function in static navigationOptions ?

| software         | version
| ---------------- | -------
| react-navigation | 2.5.5
| react-native     | 0.55.4

**Comment by JoseVf** [comment]
This behavior is intentional. If you have `Stacknavigators` in each tab of your `TabNavigator` you have to pass the icon when you define the routes. More information [here.](https://github.com/react-navigation/react-navigation/issues/4215#issuecomment-391422206)

**Comment by donni106** [comment]
@waloc did you solved it?

**Comment by waloc** [comment]
Hello no you need to do like @JoseVf

**Comment by donni106** [comment]
Yes, thanks. My problem was a bit different, but I could solve it at finally: https://github.com/react-navigation/react-navigation/issues/4215#issuecomment-412874384
