### ISSUE TITLE
UWP/Windows: headerTintColor is ignored

### ISSUE THREAD

**Issue by acuntex** [react-navigation/react-navigation#4631]
### Current Behavior

I'm using navigationOptions to color the back-button with "headerTintColor".
It works fine on Android and iOS.
Unfortunatelly the back-button on UWP (created with react-native-windows) does remain blue (#037aff).

### Expected Behavior

The navigationOption headerTintColor should be used to color the back button.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.4.1
| react-native     | 0.55.4
| node             | 10.3.0
| npm       | 6.1.0

**Comment by creambyemute** [comment]
I think that's a limitation by UWP at the moment

**Comment by creambyemute** [comment]
@acuntex I can give you a tip to circumvent for the moment: If you replace the headerLeft/Right (whereever your back button is) with a react-native-vector-icon backIcon u can color it on UWP.

Cheers
