### ISSUE TITLE
Header Back button and Gesture Back fire willBlur events at different times causing inconsistent results

### ISSUE THREAD

**Issue by reedyrm** [react-navigation/react-navigation#4637]
### Current Behavior

I'm listening to the willBlur events from the navigation and noticing that willBlur is fired consistently when clicking the back button in the header. But, when a transition occurs using gesture, it will not fire the willBlur event consistently, it feels almost like its being called during a different part of the lifecycle where its racing the componentWillUnmount on my component.

In trying to track down the issue, I added a didBlur event which caused both the willBlur and the didBlur to fire consistently on both gesture back and header back button.  But without the didBlur event, there was inconsistent behavior for the willBlur firing on Gesture Back action

### Expected Behavior

I expect that both Header Back button and the gesture "GoBack" action (in my case left to right) should fire the willBlur event before the component is in the process of unmounting. I'd like the Gesture Back functionality to match Header back button functionality.

### How to reproduce

I have a snack with the example.
https://snack.expo.io/@reedyrm/gesture-back-vs-back-button

EDIT:  I'm trying to track down the code that is causing the issue and I think it may be due to the isTransitioning flag in  https://github.com/react-navigation/react-navigation/blob/e8c1833053e37d28f0ce505ff323565abf23b6a2/src/getChildEventSubscriber.js#L132
I think the variable is only taking into account UI transitioning and ignoring that any action might need to take place during the willBlur event and its automatically firing off the didBlur.  

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |   2.5.5  |
| react-native     | 0.55.2 |
| node             | 8.9.0 |
|  yarn      | 1.7.0 |

### Context
EDIT:
For what its worth, I run into this issue using a redux-form and calling remoteSubmit on gesture back or Header back button to have auto save.  On the Header back, the form has not been unmounted so the remote submit goes thru successfully.  While on Gesture back, the form is destroyed and unmounted before the remote submit is registered

**Comment by ericvicenti** [comment]
This is a known behavior of the current design, which we may want to change in the future. As of the current StackView behavior:

### When pressing the back button

- Back action happens - willFocus/willBlur gets called
- Perform animation
- Animation completes - didFocus/didBlur gets called

### While swiping back

- Gesture starts. We don't know if the user will swipe all the way
- User releases gesture. At this point we are definitely going back. But we don't want to interrupt the gesture code and cause stutter in the animation. Changing states would do that, so we wait until:
- Back animation completes. Immediately fire willBlur/willFocus and then didBlur/didFocus

So it isn't perfect, but we do this right now to keep our gestures very smooth. You can disable gestures if you want consistent behavior with the current version of the library. In the future we may use react-native-gesture-handler which allows us to smoothly handle the gesture release no matter what, and we could change this behavior.

**Comment by reedyrm** [comment]
Thanks for the explanation.
