### ISSUE TITLE
[IOS] App is crashing during opening notification center

### ISSUE THREAD

**Issue by kidasov** [react-navigation/react-navigation#4641]
### Current Behavior

- What code are you running and what is happening?
App crashed after opening notification center.
```
class TermsAndConditions extends React.Component<Props> {
  static navigationOptions = ({ screenProps }) => ({
    headerLeft: <BackButton onPress={() => screenProps.dismiss()} />,
    headerTitle: <Title title="Terms and Conditions" />
  });

  render() {
    return (
      <Text>Hello</Text>
    );
  }
}
```
- Include a screenshot if it makes sense.
![simulator screen shot - iphone 8 plus - 2018-07-04 at 13 30 28](https://user-images.githubusercontent.com/2575852/42269356-fbf36eb8-7f8e-11e8-9587-db2a1238473c.png)

### Expected Behavior
The app is not crashing.

### How to reproduce
There is a code in StackViewLayout.js where index variable do not exist in local scope.
`onPanResponderTerminate: () => {
      this._isResponding = false;
      this._reset(index, 0);
      this.props.onGestureCanceled && this.props.onGestureCanceled();
    },`

### Your Environment

| software              | version
| -----------------| -------
| react-navigation | 2.0.4
| react-native        | 0.55.1
| node                    | 9.6.1
| yarn                     | 1.3.2

**Comment by taschik** [comment]
Would you mind sharing your solution to the problem?

**Comment by kidasov** [comment]
@taschik The issue was fixed in the latest version. Just upgrade library version.
