### ISSUE TITLE
Navigate from nested StackNavigator to parent's route?

### ISSUE THREAD

**Issue by lucasharada** [react-navigation/react-navigation#4642]
### Current Behavior

- What code are you running and what is happening?

I have 3 levels of Navigators in my app: a `StackNavigator`, which is the root of the application, that contains a bunch of Screens and one `BottomTabNavigator`; the `BottomTabNavigator` contains 3 `StackNavigators` (Home, Profile and Support), which contain simple Screens. I searched for a solution on this and found [this comment](https://github.com/react-navigation/react-navigation/issues/335#issuecomment-285888685) on a similar issue of mine, but it uses the `react-navigation v1` while I'm using `react-navigation v2`.

When using the same approach to navigate, I get the parent navigation object on the initial Screen of the Profile StackNavigator (checked with a `console.log(props);` on the constructor, but I also get an error:

> You should only render one navigator explicitly in your app, and other navigators should by rendered by including them in that navigator.

Here is my code:

```
const RootNavigator = createStackNavigator({
    Login: { screen: LoginScreen },
    [...]
    Authorized: { screen: AuthorizedNavigator }
}, {
        initialRouteName: 'Login',
        navigationOptions: { gesturesEnabled: false },
        headerMode: 'none'
    }
);

const AuthorizedNavigator = createBottomTabNavigator({
    Home: {
        screen: HomeNavigator,
        [...]
        })
    },
    Support: {
        screen: SupportNavigator,
       [...]
    },
    Profile: {
        screen: ({navigation}) => <ProfileNavigator screenProps={{ rootNavigation: navigation }} />,
        navigationOptions: {
            tabBarLabel: null,
            tabBarIcon: ({ tintColor }) => (
                <Icon
                    type='feather'
                    name='user'
                    color={tintColor}
                />
            )
        }
    },
}, {
        tabBarPosition: 'bottom',
        tabBarOptions: {
            style: {
                backgroundColor: 'white',
                height: 46
            },
            showLabel: false,
        },
        initialRouteName: 'Home'
    }
);

const ProfileNavigator = createStackNavigator({
    Main: {
        screen: ProfileScreen
    },
    [...]
}, {
        initialRouteName: 'Main',
        headerMode: 'none',
        navigationOptions: {
            gesturesEnabled: false
        }
    }
);
```

### Expected Behavior

- What do you expect should be happening?

Be able to get the parent navigation object without any error.

### How to reproduce

- Explain how to run the example app and any steps that we need to take to reproduce the issue from the example app.

1. Create a new RN app with CRNA;
2. Include all 3 Navigators to match the explained structure;
3. Navigate to the Profile Tab on BottomTabNavigator;
4. The error should pop up for `react-navigation-v2`

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.0.1
| react-native     | 0.55.4
| node             | 8.11.2
| npm or yarn      | npm 6.1.0

**Comment by lucasharada** [comment]
Upgrading `react-navigation` to 2.5.5 changed the error to warning, but it's still not working properly: the `rootNavigation` object on the `ProfileScreen` is referring to `HomeNavigator` navigation object.

**Comment by lucasharada** [comment]
Got to work by changing `Authorized: { screen: AuthorizedNavigator }` to `Authorized: { screen: ({ navigation }) => <AuthorizedNavigator screenProps={{ rootNavigation: navigation }} /> }` on `RootNavigator`. Following the change, also updated `screen: ({navigation}) => <ProfileNavigator screenProps={{ rootNavigation: navigation }} />,` to `screen: ({ screenProps }) => <ProfileNavigator screenProps={{ rootNavigation: screenProps.rootNavigation }} />,`.

Although, I'm still getting this warning:

> You should only render one navigator explicitly in your app, and other navigators should by rendered by including them in that navigator.

Is there a better/correct way to do this?

**Comment by brentvatne** [comment]
read the doc that it links to to learn why the following is incorrect

```
 Profile: {
        screen: ({navigation}) => <ProfileNavigator screenProps={{ rootNavigation: navigation }} />,
 // etc..
```


for your convenience: https://reactnavigation.org/docs/en/common-mistakes.html#explicitly-rendering-more-than-one-navigator
