### ISSUE TITLE
[Android] 'absolute' position hides header - happened sometime between 2.0.4 & 2.5.5

### ISSUE THREAD

**Issue by noambonnie** [react-navigation/react-navigation#4643]
### Current Behavior
Using Stack Navigator, trying to set header position to absolute (with the intention of animating it). In 2.0.4 works as expected. In 2.5.5 the header is hidden. I tried modifying `zIndex` to no avail.

When removing `position: 'absolute'` from the headerStyle in `navigationOptions`, the header shows as expected.

I compared the diff between the two versions. I found a diff in src/views/Header/Header.js. In 2.5.5 line 503 of Header.js: 
```
      <Animated.View
        style={[
          this.props.layoutInterpolator(this.props),
          { backgroundColor: DEFAULT_BACKGROUND_COLOR },
        ]}
      >
```
The "backgroundColor" part is new. Oddly enough, if I remove that line I do see the header. This works:
```
      <Animated.View
        style={[
          this.props.layoutInterpolator(this.props),
        ]}
      >
```

I can't find a good explanation as to why this works but I've tested it a bunch of times.

### Expected Behavior
Absolute positioning of header should not hide the header. 

### How to reproduce

Snack: https://snack.expo.io/BJskvP9Mm

Since it's my first time using snack I'll also post my `App.js` here just in case - it's short:

```
import React from 'react';
import { View, Text } from 'react-native';
import { createStackNavigator } from 'react-navigation';

class PostScreen extends React.Component {
    render() {
        return (
            <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
                <Text>Test Screen</Text>
            </View>
        );
    }
}

const HeaderStack = createStackNavigator(
    {
        Post: {
            screen: PostScreen,
            navigationOptions: {
                title: "Test"
            }
        },
    },
    {
        navigationOptions: {
            headerStyle: {
                position: 'absolute', // <==== Comment this out and the header would show
                top: 0,
                left: 0,
                right: 0,
                bottom: 0,
                // zIndex: 1,
                // What I'm really trying to do is animate, but once the absolute issue is resolved I think the rest will be too.
                // transform: [{ 
                //     translateY: navbarTranslate
                // }],
            },
        },
    }
);

export default class App extends React.Component {
    render() {
        return (
            <HeaderStack/>
        )
    }
}

```

Simply run the above code and header would not show. Comment out the `position: 'absolute'` line and header appears.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.5.5
| react-native     | 0.55.4
| node             | 8.9.1
| npm or yarn      | npm 6.1.0
| platform         | Android

**Comment by brentvatne** [comment]
position: absolute isn't supported in headerStyle, I added a warning for it now: https://github.com/react-navigation/react-navigation/commit/dc436e4d01b442bbca6f66804997b40139349c47

you should use the `headerTransparent` navigationOption, or just set `header: null` and render your own header / animate it separately, eg: https://github.com/brentvatne/growler-prowler/blob/master/components/BreweryDetails.js

**Comment by JulienMalige** [comment]
@brentvatne 
> isn't supported in headerStyle

but still usable with custom header component isn't ?
