### ISSUE TITLE
Custom back button navigates to the wrong screen

### ISSUE THREAD

**Issue by markgoodyear** [react-navigation/react-navigation#4644]
### Current Behavior
Using this setup:

- StackNavigator
  - TabNavigator
      -  StackNavigator (`TabOne`)
          - StackNavigator (`ScreenOne`)
  - StackNavigator (`ScreenTwo`)
  
When on `ScreenTwo` from `TabOne` > `ScreenOne` > `ScreenTwo`, going back with a custom back button doesn't work as expected. Rather than going back to `ScreenOne`, it goes back to `TabOne`. Gesture navigation works as expected, along with the standard header back button. I've tried with `goBack` and `pop`.

### Expected Behavior
To be on the `ScreenOne` screen.

### How to reproduce
See this Snack and navigate through the screens: https://snack.expo.io/B1trTD5Mm

_This was a non-issue on react-navigation 2.0.4, see this Snack running 2.0.4:
https://snack.expo.io/HJKSgu5z7_

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |2.5.5
| react-native     | 0.55.4 (Expo SKD 28)

**Comment by brentvatne** [comment]
this should be resolved in 2.6.0, let me know if the issue persists

**Comment by tonlen** [comment]
same issues, `goBack` back to first tab screen, and Interface cannot interact.

**Comment by markgoodyear** [comment]
@brentvatne 0.6.0 looks to have fixed the issue for me. I can also confirm it fixes the error/crash when calling isFocused too. It goes a little funky in the Snack still, but can't re-create on the sim/devices so I'll put that down to an issue with Snack/Expo client. Excellent work, thank you! 👍🏻 

I'll leave this open for @tonlen — did you try with 0.6.0?

**Comment by tonlen** [comment]
@markgoodyear Thanks for the tip. upgrade to 2.6.0 have fixed.
