### ISSUE TITLE
Navigator prop inside custom navigator is undefined

### ISSUE THREAD

**Issue by gabrielhpugliese** [react-navigation/react-navigation#4646]
### Current Behavior

I'm creating a custom navigator and navigation prop is undefined

### Expected Behavior

navigation prop is expected not to be undefined

### How to reproduce

Expo Snack link: https://snack.expo.io/B1lLaojM7

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.5.5
| react-native     | 0.55.4
| node             | v10.5.0
| npm or yarn      | 1.7.0

**Comment by brentvatne** [comment]
this looks like a docs issue, @ericvicenti https://reactnavigation.org/docs/en/custom-navigators.html doesn't seem to explain so clearly how to do this.

@gabrielhpugliese - here's how you can use it: https://snack.expo.io/@notbrent/4646

**Comment by gabrielhpugliese** [comment]
So what I understand the Root navigator cannot be a custom one, right?
