### ISSUE TITLE
Deep link parameters are not available below root navigator

### ISSUE THREAD

**Issue by lwansbrough** [react-navigation/react-navigation#4647]
I'm using version 2.6.0. I've got a React Native app which is deep linked using the following URL: `myscheme://user/123/posts/456/edit`

The navigation stack looks like this:

```
App [StackNavigator]
  Welcome [Screen] (welcome)
  Login [Screen] (login)
  User [BottomTabNavigator] (user/:userId)
    Profile [Screen] (profile)
    Posts [MaterialTopNavigator] (posts/:postId)
      View [Screen] (view)
      Edit [Screen] (edit)
```

What I need is to be able to pull out the URL parameters at their respective navigator levels. Ideally I can access `userId` on the Profile screen, as well as in the Posts navigator (this navigator is static, so I'd expect some way to be able to hook into the params at this level via a static method, or they'd just be propagated down to the child screens/navigators). And again, I need to be able to access `postId` in either a static method on the static MaterialTopNavigator, or it would be propagated down to the View and Edit screens.

Is what I want possible? I actually have a fork that was capable of this for a while but it's fallen behind master. I'm curious why this hasn't been done yet.

**Comment by hegelstad** [comment]
Just step through the debugger and try to experience the black vodoo magic that is happening :)

**Comment by brentvatne** [comment]
when you get a chance can you look into this @ericvicenti?

**Comment by ericvicenti** [comment]
This should work if your profile screen has a path of `user/:userId`, your post screen would have a path of `user/:userId/posts/:postId`, and both your User navigator and Posts navigator have paths set to be empty (`""`)

The path needs to explicitly specify all of the screen's required parameters. We don't want params to implicitly fall through because each navigator would become coupled to the place where it is used.

If you have trouble doing this, please post a simplified code example of the bug so I can reproduce it and help you figure it out.

**Comment by lwansbrough** [comment]
The following have no effects:

`xcrun simctl openurl booted navtest://user/123/posts/456/edit`
`xcrun simctl openurl booted navtest://user/123`
`xcrun simctl openurl booted navtest://user`

**Comment by ericvicenti** [comment]
Thanks for creating the standalone example! Much easier to see whats going on now.

I've just made a bunch of improvements to the path handling logic here: https://github.com/react-navigation/react-navigation/pull/4671

Would you mind testing out this new path handling code to see if it helps? 

If you want to see what is going on under the hood, you can add logging to `createNavigationContainer.js`. You can see what action gets returned from the router's `getActionForPathAndParams` inside `_handleOpenURL`.

**Comment by lwansbrough** [comment]
@ericvicenti Nice, this seems to work well on the demo project and my real project.
