### ISSUE TITLE
createBottomTabNavigator / createStackNavigator nesting confusion with header

### ISSUE THREAD

**Issue by yangbo5207** [react-navigation/react-navigation#4649]
code like this:

```js
const Demo1 = () => (
  <View><Text>hello first</Text></View>
)
Demo1.navigationOptions = {
  title: 'screen demo1',
  headerTitle: 'Screen'
};


const AppTabNavigator = createBottomTabNavigator(
  {
    First: Demo1,
    Second: () => <View><Text>hello Second</Text></View>,
    Third: () => <View><Text>hello Third</Text></View>,
  }
);

```
no header.

![image](https://user-images.githubusercontent.com/13758605/42355318-04720010-80ff-11e8-8816-8f982362ca29.png)

and I change code

```js
const Stack1 = createStackNavigator({
  '1': {
    screen: ({ navigation }) => <Text onPress={() => navigation.navigate('4')}>Screen 1</Text>,
    navigationOptions: {
      title: 'Screen 1'
    }
  },
  '4': {
    screen: ({ navigation }) => <Text onPress={() => navigation.navigate('1')}>Screen 4</Text>,
    navigationOptions: {
      title: 'Screen 4',
      // tabBarVisible: false
    }
  },
})


const Stack2 = createStackNavigator({
  '2': {
    screen: () => <Text>Screen 2</Text>,
    navigationOptions: {
      title: 'Screen 2',
      // tabBarVisible: false
    }
  },
})

const Stack3 = createStackNavigator({
  '3': {
    screen: () => <Text>Screen 3</Text>,
    navigationOptions: {
      title: 'Screen 3'
    }
  },
})

const AppTabNavigator = createBottomTabNavigator(
  {
    First: Stack1,
    Second: Stack2,
    Third: Stack3,
  }
);

```

but

![image](https://user-images.githubusercontent.com/13758605/42355344-3221d922-80ff-11e8-9f7b-9be268fdb51e.png)

![image](https://user-images.githubusercontent.com/13758605/42355354-3faa7e1e-80ff-11e8-966a-3850473d421f.png)

please help me to resolve it.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  2.6.0
| react-native     | 16.2
| node             | 9 +
| npm or yarn      |  yarn 1.3.2

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please post a link to a github repo or snack that repros this and i'd be happy to investigate further

**Comment by bang88** [comment]
@brentvatne  A repro with these code snippets :)

```jsx

/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 *
 * @format
 * @flow
 */
import React from 'react';
import { View, Text } from 'react-native';
import { createStackNavigator,createBottomTabNavigator } from 'react-navigation';

class HomeScreen extends React.Component {
	static navigationOptions = {
		title: 'Home',
	};
	render() {
		return (
			<View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
				<Text>Home Screen</Text>
			</View>
		);
	}
}

const Tab = createBottomTabNavigator({
	Home: {
		screen: HomeScreen,
	},
});
const RootStack = createStackNavigator({
	Home1: {
		screen: Tab,
	},
});
export default class App extends React.Component {
	render() {
		return <RootStack />;
	}
}

```
![image](https://user-images.githubusercontent.com/433259/42683372-c165ff1c-86bf-11e8-90c5-4e9aa39b85a2.png)

**Comment by fukcup** [comment]
I've also met this problem and I'm looking forward to it！！！

**Comment by jameslporter** [comment]
You probably need to have a stack per tab navigator. I have an app with 4 bottom tabs, each tab is a stack.

Hope that helps.

**Comment by brentvatne** [comment]
@bang88 - this is well documented in https://reactnavigation.org/docs/en/navigation-options-resolution.html

**Comment by bang88** [comment]
Get it. I just upgrade from an existing application. I think it should work withou too many changes. and I did not find any documents about these changes from the upgrade documentation.

**Comment by brentvatne** [comment]
@bang88 - it is in both release notes in the releases tab here on github and on the blog post announcing the release: https://reactnavigation.org/blog/2018/05/07/react-navigation-2.0.html

**Comment by eduardodcastro** [comment]
can solve by following this reasoning link: https://github.com/eduardodcastro/react-native/blob/master/control-navigate.js
