### ISSUE TITLE
didFocus listener is not receiving navigation params in payload.action

### ISSUE THREAD

**Issue by facuescobar** [react-navigation/react-navigation#4653]
### Current Behavior
This is my navigator structure:
```
app
--signed-out
--signed-in
```

When the user is `signed-in` and clicks on **Sign Out** it will navigate to `signed-out`, and it will send **onSignedOut: true** so I can run the proper actions in `signed-out` screen:
```
this.props.navigation.navigate(NavigationRoutes.SIGNED_OUT, {
  onSignedOut: true,
});
```

In `signed-in` screen I have a `didFocus` listener to check if the user has signed out.
```
constructor(props) {
  super(props);

  const { navigation } = props;

  this.didFocusListener = navigation.addListener(
    'didFocus',
    this.componentDidFocus,
  );
}

componentDidFocus = payload => {
  const { params } = payload.action;

  if (params && params.onSignedOut) {
    ... actions to sign out
  }
};
```

And the issue is that `onSignedOut`  doesn't exist in the `payload.action`.

If I try with `willFocus` listener, the `onSignedOut` parameter exist, but I need to receive this action once the component `didFocus` because I don't want to clear the data when other components are mounted.

### Expected Behavior
`didFocus` listener should receive navigation params in `payload.action` as we receive in `willFocus` listener.

### How to reproduce

Navigators
```
app (stack navigator)
--signed-out (screen)
--signed-in (screen)
```

Signed Out
```
constructor(props) {
  super(props);

  const { navigation } = props;

  this.didFocusListener = navigation.addListener(
    'didFocus',
    this.componentDidFocus,
  );
}

componentDidFocus = payload => {
  const { params } = payload.action;

  if (params && params.onSignedOut) {
    // The flow never gets here because `didFocus` does not receive navigation params
  }
};
```

Signed In
```
this.props.navigation.navigate(NavigationRoutes.SIGNED_OUT, {
  onSignedOut: true,
});
```
### Your Environment

Environment:
  OS: macOS High Sierra 10.13.3
  Node: 7.9.0
  Yarn: 0.23.2
  npm: 5.8.0
  Watchman: 4.7.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 2.3 AI-162.4069837

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4

**Comment by ericvicenti** [comment]
You're accessing the params from the navigate action instead of the navigation state. The navigate action is what triggers `willFocus`.. another action is the cause of `didFocus`.

You can always access the screen's parameters if you do:

```js
this.props.navigation.getParam('onSignedOut')
```

**Comment by MrHubble** [comment]
@ericvicenti is `payload.state.params` also an acceptable option for accessing the params? Within my `listener` function `this.props` is not defined:

````js
this.props.navigation.addListener('willFocus', (payload) => {
  // correctly gives params  
  console.log(payload.state.params)

  // undefined
  console.log(this.props)
})
````
