### ISSUE TITLE
Windows 10/UWP: FlatList scrolling does not work when the screen is part of DrawerNavigator

### ISSUE THREAD

**Issue by npmun** [react-navigation/react-navigation#4654]
### Current Behavior

When the screen is part of DrawerNavigator, FlatList component does not scroll. When the same screen is part of other navigators (Stack or Tab), scrolling works perfectly. This issue is seen only in UWP app, works correctly in Android/iOS. I am not sure if the issue is related react-native-windows or react-navigation (This issue already open with react-native-windows https://github.com/Microsoft/react-native-windows/issues/1617 )

### Expected Behavior

Scrolling should work correctly.

### How to reproduce

Please create a screen using this code to see the issue.

import React from "react";
import {DrawerNavigator} from "react-navigation";
import {Button, ScrollView, StyleSheet, Text, View} from "react-native";

class MyHomeScreen extends React.Component {

static navigationOptions = {
    drawerLabel: 'Home',

};
state = {
    names: [
        {'name': 'Ben', 'id': 1},
        {'name': 'Susan', 'id': 2},
        {'name': 'Robert', 'id': 3},
        {'name': 'Mary', 'id': 4},
        {'name': 'Daniel', 'id': 5},
        {'name': 'Laura', 'id': 6},
        {'name': 'John', 'id': 7},
        {'name': 'Debra', 'id': 8},
        {'name': 'Aron', 'id': 9},
        {'name': 'Ann', 'id': 10},
        {'name': 'Steve', 'id': 11},
        {'name': 'Olivia', 'id': 12}
    ]
}
render() {
    return (
        <View style={{flex:1}}>
            <ScrollView>
                {
                    this.state.names.map((item, index) => (
                        <View key = {item.id} style = {styles.item}>
                            <Text>{item.name}</Text>
                        </View>
                    ))
                }
            </ScrollView>
        </View>
    )
}
}

const styles = StyleSheet.create ({
item: {
flexDirection: 'row',
justifyContent: 'space-between',
alignItems: 'center',
padding: 30,
margin: 2,
borderColor: '#2a4944',
borderWidth: 1,
backgroundColor: '#d2f7f1'
}
})

class MyNotificationsScreen extends React.Component {
static navigationOptions = {
drawerLabel: 'Notifications',
};

render() {
    return (
        <Button
            onPress={() => this.props.navigation.goBack()}
            title="Go back home"
        />
    );
}
}

export default MyApp = DrawerNavigator({
Home: {
screen: MyHomeScreen,
},
Notifications: {
screen: MyNotificationsScreen,
},
});

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |2.6.1
| react-native     |0.55.4
| node             |8.10.0
| npm or yarn      |1.7.0
| react-native-windows      |0.55.0-rc.0

**Comment by brentvatne** [comment]
we don't explicitly support uwp, if react-navigation works on there that's nice but we won't take any issues related to it unless someone volunteers to manage this.

**Comment by creambyemute** [comment]
@npmun Try with `zIndex: 1` on the parent view of flatlist. Hope this helps

**Comment by brentvatne** [comment]
@matthargett may be interested in owning uwp support for react-navigation

**Comment by paulbx81** [comment]
@creambyemute 

FIX : https://github.com/anumang/react-native-drawer-layout/blob/5054bfa28fd60a13c1de0b0deb3cb144c876fa5c/src/DrawerLayout.js

**Comment by creambyemute** [comment]
@brentvatne Just FYI: I tried the "Fix" mentioned by @paulbx81 and it indeed works with the small change to DrawerLayout.js.

I also tested if there were any differences on Android/iOS with this change but couldn't find any.

**Comment by cchakkaravarthi** [comment]
> @creambyemute
> 
> FIX : https://github.com/anumang/react-native-drawer-layout/blob/5054bfa28fd60a13c1de0b0deb3cb144c876fa5c/src/DrawerLayout.js

Thank you so much.It is really good solution for UWP.
