### ISSUE TITLE
How to add accordion/expandable menu in navigator drawer.

### ISSUE THREAD

**Issue by iam1208** [react-navigation/react-navigation#4656]
I am an Android Application Developer. I have started working on React-Native. I am unable to find a way to show expandable list inside navigation drawer.

![arvky](https://user-images.githubusercontent.com/23047511/42415279-a7d3046c-8266-11e8-918a-d73062b85ad2.png)

**Comment by brentvatne** [comment]
hi there! this is a question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.
