### ISSUE TITLE
Drawer not working on 2.6.1

### ISSUE THREAD

**Issue by AlirezaAkbarix** [react-navigation/react-navigation#4657]
Updating the package to `2.6.2` caused app not to be able to use drawer for navigating, while it was fine at `2.3.1`.

expected:
when click on drawer item, navigate to the page and stay on it!!

current:
when click on drawer item, navigates to the page and immediately goes back to the page that holds the drawer!

I'm using `createDrawerNavigator` and sub pages It opens, are separated pages that are not at drawerNavigator (they're in the parent navigator).

Bro just check if it works! please don't ask for reproducing the error, I'm at high schedule work...

Environment:
  OS: macOS High Sierra 10.13
  Node: 8.9.4
  Yarn: 1.6.0
  npm: 6.0.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.1 AI-173.4720617

Packages: (wanted => installed)
  react: ^16.4.1 => 16.4.1
  react-native: 0.55.4 => 0.55.4

**Comment by brentvatne** [comment]
> Bro just check if it works! please don't ask for reproducing the error, I'm at high schedule work...

sorry, no :(

we require repro cases for everything. everyone is busy and if you need help you must follow the issue template.
