### ISSUE TITLE
react navigation pass param to navigator

### ISSUE THREAD

**Issue by dakoto747** [react-navigation/react-navigation#4659]
It'll be nice if I could pass parameters to a navigator. 
Here's my scenario: 
I'm using the auth flow as described on : [Creating auth flows](https://reactnavigation.org/docs/auth-flow.html).
I have stack navigators stacked inside a tabnavigator, and I would like to set the one of the tabs to be an image who's source is gotten from the authentication. I've been googling for 2 days, with no luck. Any ideas for an alternative? I feel using redux for this is overkill and unnecessary.

**Comment by brentvatne** [comment]
you can use `screenProps`, react context, redux, mobx, or any other state management tool. i like to use this https://github.com/brentvatne/react-native-authentication-helpers

**Comment by jasan-s** [comment]
@brentvatne  `screenProps` seem to always be empty object `{}` in v3
