### ISSUE TITLE
[IOS] Back button does not work on the device

### ISSUE THREAD

**Issue by tolgaduzenli** [react-navigation/react-navigation#4661]
Back button does not navigate to the previous screen on IOS devices.  On simulator or debug mode devices, it works properly. And also on Android devices, everything is fine.
There is no any differences, and in the past(2-3 months ago) everything was fine. During this time, we didnt change anything.
react-navigation version was really old (1.0.0-beta.11), I upgraded to the 2.4.1 but still same issue.

I checked open and closed issues, couple people had similar issue but solutions didnt work for me.
Here is the sample code from our project;

    static navigationOptions = ({ navigation }) => ({
	    title: `News`,
          headerTitleStyle: {
              color:Config.getNavColor().title
          },
          headerStyle: {
              backgroundColor:Config.getNavColor().bg
          },
          headerTintColor: Config.getNavColor().backButton
	  });

Almost every screen has same code. All screens have same problem, there is no any screen which works as we expected.

And developers, PLEASE dont say, create https://snack.expo.io  demo because this is not that kind of issue.

Thanks everybody for your time and work.

### Current Behavior

Back button does not navigate to the previous screen on ios devices. 
But it works properly on debug mode(ios).
Android side is totally fine.

### Expected Behavior

Navigate to previous screen.

### How to reproduce
Try to run your app on ios device, not enabled debug mode. Go to sub page and click back button.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.4.1
| react-native     |  0.43.3
| node             | 8.11.1
| npm or yarn      | 5.3.0 npm

**Comment by brentvatne** [comment]
> And developers, PLEASE dont say, create https://snack.expo.io demo because this is not that kind of issue.

it *is* that kind of issue, because the back button works fine as far as i can tell. the steps you provide to repro this do not repro the issue.

you need to provide a project that we can clone and run and see this in or there's nothing we can do to help

**Comment by AlexKotov** [comment]
same issue
RN: 0.55.2
