### ISSUE TITLE
[BUG] Some R-N Windows components not working in DrawerNavigator

### ISSUE THREAD

**Issue by paulbx81** [react-navigation/react-navigation#4666]
### Current Behavior

******THIS IS A WINDOWS 10 APP******

When i try to use the Picker element inside a StackNavigator it work perfectly but it don't work when i am into a drawernavigator.

For exemple : my login screen : 

`const AuthStack = createStackNavigator({ Login: Login },{headerMode:'none'});`

If i use a Picker inside this screen it will work perfectly : 

![screen1](https://user-images.githubusercontent.com/40029591/42439399-1c11a6c4-8363-11e8-94d3-7807a498fde6.PNG)
![screen2](https://user-images.githubusercontent.com/40029591/42439404-1dcb0d02-8363-11e8-8ac7-bf0396d20316.PNG)

But if i change : 

`const AuthStack = createStackNavigator({ Login: Login },{headerMode:'none'});`

with : 

`const AuthStack = createDrawerNavigator({ Login: Login },{headerMode:'none'});`

my Picker is always visible but nothing append when i try to use it, nothing... and this is the same result for all my other screen..

![screen3](https://user-images.githubusercontent.com/40029591/42439511-67940e66-8363-11e8-8676-609e30d6dbb5.PNG)

### Expected Behavior

Picker should work perfectly if i use into component inside DrawerNavigator

### How to reproduce

Use a simple Picker into screen inside DrawerNavigator

    this.state = {
        villeRisk : "prs",
    }

    <Picker
        selectedValue={this.state.villeRisk}
        style={{ height: 30, width: 200 }}
        onValueChange={(itemValue, itemIndex) => this.setState({villeRisk: itemValue})}
    >
        <Picker.Item label="Toulouse" value="tls" />
        <Picker.Item label="Paris" value="prs" />
    </Picker>

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.6.2
| react-native     | 0.56.0
| node             | 9.11.1
| npm or yarn      | npm 5.6.0

**Comment by paulbx81** [comment]
It's very annoying.
So for now, we can't use any input form component if we use DrawerNavigator on WindowsNT..

May be try another library for form component ?

**Comment by creambyemute** [comment]
@paulbx81 I think we should also create an issue on rn-windows with a small and simple reproduction repository.

**Comment by paulbx81** [comment]
@creambyemute 

https://github.com/Microsoft/react-native-windows/issues/1889

**Comment by creambyemute** [comment]
@paulbx81 Great, I'll post a small reproduction repository

**Comment by paulbx81** [comment]
@creambyemute https://github.com/Microsoft/react-native-windows/issues/715

**Comment by creambyemute** [comment]
@paulbx81 That's not really the case here I think. Normal Buttons etc receive the press. It's really that the Switch/Picker view isn't fully created if you look at the dom with react-devtools

**Comment by paulbx81** [comment]
i tried with other versions of react-native, react-native-windows, react-navigation... same

**Comment by paulbx81** [comment]
@brentvatne ? :/

**Comment by brentvatne** [comment]
@matthargett

**Comment by brentvatne** [comment]
we don't explicitly support react-native-windows. if you find that this is a bug with react-navigation you can submit a PR to fix it and we will check it out. @matthargett expressed interest in leading react-native-windows support for react-navigation but until we get him onboarded we don't take issues related to windows.
