### ISSUE TITLE
How to hidden the navigationBar bottom line?

### ISSUE THREAD

**Issue by heyode** [react-navigation/react-navigation#4668]
---

### Current Behavior

- I use the createStackNavigator function to create the WelcomPage, but there is a gray line  at bottom of the NavigationBar.
![image](https://user-images.githubusercontent.com/12412023/42501160-af681fcc-8465-11e8-9993-dedd90c2c360.png)

### Expected Behavior

- hidden the line

### How to reproduce

```
export const setup = createStackNavigator({
    Welcome: {
        screen: WelcomPage
    },
    Home:{
        screen:HomePage
    },
    // TabNav:{
    //     screen:AppTabNavigator,
    //     navigationOptions:{
    //         headerTitle:'最热',
    //         headerTitleStyle:{
    //             color:'white',
    //
    //         },
    //         headerForceInset: {bottom:'never'},
    //         headerStyle:{
    //             backgroundColor:'#2196F3'
    //         },
    //     }
    // }
},
```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |^2.5.5
| react-native     | 0.55.4
| node             | v10.6.0
| npm or yarn      | 1.7.0

**Comment by ericvicenti** [comment]
This should work

```
createStackNavigator(
  {
      Foo,
      Bar,
   },
   {
      navigationOptions: { headerStyle: { borderBottomWidth: 0 } }
   }
);
```

**Comment by heyode** [comment]
@ericvicenti thanks，How to view the properties in headerStyle？I didn't find it here (https://reactnavigation.org/docs/en/stack-navigator.html).
