### ISSUE TITLE
Navigate to a stack in createSwitchNavigator using NavigationActions

### ISSUE THREAD

**Issue by srajchevski** [react-navigation/react-navigation#4669]
Given the switchNavigator below (taken from the [official example](https://reactnavigation.org/docs/en/auth-flow.html)),  how can one navigate to the AuthStack, from outside a component, which means without this.props.navigation ?

```
export default createSwitchNavigator(
  {
      AuthLoading: AuthLoadingScreen,
      App: AppStack,
      Auth: AuthStack,
   },
   {
      initialRouteName: 'AuthLoading',
   }
);
```

I already tried `NavigationActions.navigate({ routeName: 'Auth' });` , but with no luck.

Version:
"react-navigation": "~2.3.1",

**Comment by srajchevski** [comment]
Yes, but I'm trying to dispatch from outside a screen, in my actions to be exact, where I don't have the `this.props.navigation` object. I'm pretty sure this is solvable by using NavigationActions but just can't seem to make it work. Appreciate the help.
I also tried `dispatch(NavigationActions.navigate({ routeName: 'Auth' })`, but no-go.
```
export const getData () => dispatch => {
fetch(`...`)
.then(res => 
   if (res.success) {
       // successful, do stuff
   } else {
      // unauthenticated call, navigate back to AuthStack
   }
).catch(() => {
     // handle err or navigate back to AuthStack
});
}
```

**Comment by lidiexy** [comment]
@srajchevski Please check this Snak https://snack.expo.io/SyGZleEm7 may help you... I did it to test Dynamic Routes within Drawer with not luck.

**Comment by srajchevski** [comment]
https://reactnavigation.org/docs/en/navigating-without-navigation-prop.html

**Comment by RicardoBer** [comment]
I try with @srajchevski  proposal and when use createSwitchNavigator with example in NavigationService.js, and call 

`navigationservice.navigate('StackNoLogado')`
or
`navigationservice.navigate({routeName:'StackNoLogado'})`

it fires one error:

TypeError: _navigator.dispatch is not a function

**Comment by elizaMathaai** [comment]
Hi  srajchevski, 
can u tell me how u managed to navigate to Authcreen?
I have notification screen whihc should be displayed only when tapping on push notification. 
the push notificcation listener is in app.js and the switch navigator is being called here.
How to call the notification screen here?
I am wondering as to identify which is the root level navigator . Please help
