### ISSUE TITLE
addListener with Redux

### ISSUE THREAD

**Issue by ysdanielkim** [react-navigation/react-navigation#4670]
@ericvicenti - regarding #3345, I've been having problem with all listeners being removed when a non-navigational action is emitted by Redux.

getChildEventSubscriber.js:146 seems to be the culprit.

I'm thinking about applying the fix below. Please let me know if this makes sense to you.

```
/* getChildEventSubscriber.js:67 */  
const upstreamSubscribers = upstreamEvents.map(eventName =>
    addListener(eventName, payload => {
      const { state, lastState, action } = payload;

      if (!action.type.startsWith('Navigation/')) return; // <---- added this

      const lastRoutes = lastState && lastState.routes;
      const routes = state && state.routes;
```

It's sort of introducing coupling with Redux, but I'm not sure how this could be fixed from react-nativgation-redux-helper package. I'd appreciate any further insights.

If you think this makes sense, I can work on modifying tests.

    "react-navigation": "^2.4.1",
    "react-navigation-redux-helpers": "^2.0.2",
    "react-redux": "^5.0.7",
    "redux": "^4.0.0",

Thanks,
Daniel

**Comment by ysdanielkim** [comment]
https://github.com/ysdanielkim/react-navigation/commit/2bd6d909b253bcd557db74e9916db1159a48f9d5

**Comment by ericvicenti** [comment]
Hmm. We should probably make the event system resilient to unknown actions. We can probably find a more robust solution than matching against the action name.

I can't think of why all the subscriptions would go away when dispatching a non-navigation event.

Can you post reproduction steps to get this bug to appear? Ideally it would be a test, or a simplified code example that demonstrates the bug without a bunch of redux boilerplate. Thanks!

**Comment by xiongcaichang** [comment]
me too

**Comment by ahce** [comment]
+1

My Environment
| software         | version
| ---------------- | -------
| react-navigation | 2.6.2
| react-navigation-redux-helpers | 2.0.2
| react-native     | 0.55.4
| react-redux      | 5.0.7
| redux       | 4.0.0

**Comment by ericvicenti** [comment]
Can anybody please post a simplified example of the bug? Its hard for me to fix a bug I haven't seen!

**Comment by xiongcaichang** [comment]
this bug resolved at neweset version

**Comment by John251314** [comment]
if (action.type.startsWith('Navigation')) {
            return middleware(redux)(next)(action);
        } else {
            return next(action);
        }

**Comment by satya164** [comment]
Closing due to no response.

**Comment by flyskywhy** [comment]
> I have the exact same issue with the same dependencies setup.
> 
> Seems like the first time I navigate into a view that has a `didFocus` listener the event registers but does not fire.
> Then navigate into a different view and press back to go back into the view with the focus event. You will see that the event does not trigger.
> 
> If you navigate back again to your initial view then again into the view with the focus event itll work.
> My conclusion is that it works only the second time it registers the view and im not sure exactly why that is happening.

https://github.com/shyaniv7/react-navigation/commit/20594229df37a9a08c8a8f117b680498365f1316 works for me, thank you @shyaniv7
