### ISSUE TITLE
android hardware back button doesn't work at all

### ISSUE THREAD

**Issue by hyoungbin** [react-navigation/react-navigation#4672]
### Current Behavior

Hi, I'm using react-navigation to make Expo standalone app. 
My navigation structure is, 

- RootNavigation : Stack Navigator (in case user logged in)
  - Bottom Tab Navigator
    - each tab has 2~3 screens ( Stack Navigator ) 
  - other screen

- LoggedOutNavigation : another Stack Navigator (in case user not logged in)
  - login screen

in short, stack navigator -> bottom tab navigator - stack navigator

in App.js
`
return (
      <View style={styles.container}>
        {isLoggedIn ? (
            <RootNavigation/>
        ) :  (
          <LoggedOutNavigation />
        )}
      </View>
    );
`

The problem is when I press hardware back button on android device, app always exits. 
What I expected is poping current screen when I press back button in screens in each tab. 

> By default, when user presses the Android hardware back button, react-navigation will pop a screen or exit the app if there are no screens to pop. 
[https://reactnavigation.org/docs/en/custom-android-back-button-handling.html](url). 

I use redux to control app's states, but headerLeft back button works perfectly. 
Only android hardware back button doesn't work

I tried to use `react-navigation-backhandler` and add listener to each class component based on [https://reactnavigation.org/docs/en/custom-android-back-button-handling.html](url). 
but I failed. 

I can't understand what's wrong with my code.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.6.0
| react-native     | "https://github.com/expo/react-native/archive/sdk-27.0.0.tar.gz"
| expo             | 27.0.1
| redux      | 4.0.0
| redux-persist      | 5.9.1

**Comment by brentvatne** [comment]
hi @hyoungbin - I attempted to reproduce this by just running the [NavigationPlayground test app](https://github.com/react-navigation/react-navigation/tree/master/examples/NavigationPlayground) and the back button worked as expected. please provide a minimal example that reproduces the problem and that i can either run in https://snack.expo.io or that i can clone from github and run

**Comment by shixiaoquan** [comment]
@hyoungbin  You may need to read the documentation carefully first.

As follows:
Keep in mind that when a navigator is given a navigation prop, it relinquishes control of its internal state. That means you are now responsible for persisting its state, handling any deep linking, [Handling the Hardware Back Button in Android](https://reactnavigation.org/docs/en/redux-integration.html#handling-the-hardware-back-button-in-android), etc.

I have solved this problem according to the tutorial.

```

class App extends React.Component {
  componentDidMount() {
    BackHandler.addEventListener('hardwareBackPress', this.onBackPress);
  }

  componentWillUnmount() {
    BackHandler.removeEventListener('hardwareBackPress', this.onBackPress);
  }

  onBackPress = () => {
    const { dispatch, state } = this.props;
    // console.log('this.props:', this.props);
    // console.log({ ...state });
    if (state.index === 0) {
      return false;
    }

    dispatch(NavigationActions.back());
    return true;
  };

  render() {
    const {
      dispatch,
      state,
      language,
      i18n,
    } = this.props;
    return (
      <AppNavigator
        dispatch={dispatch}
        state={state}
        screenProps={{ language, i18n }}
        ref={navigatorRef => registerTopNavigator(navigatorRef)}
      />
    );
  }
}
```
