### ISSUE TITLE
Custom header for each MaterialTopTabNavigator tabs

### ISSUE THREAD

**Issue by tinmar33** [react-navigation/react-navigation#4673]
Hi,

I have created a MaterialTopTabNavigator inside my StackNavigator, and I want to add a "+" button on the header of only one of my 3 tabs.

I can't use headerRight on my StackNavigator because it will add it on my 3 tabs.
I also tried to create a new stackNavigator inside each tabs but I can't do this because I need to get some props from my parent page

Any solution ?

<img width="315" alt="image" src="https://user-images.githubusercontent.com/7252474/42576125-f95fe058-8521-11e8-94cc-3377a1a9fb60.png">

**Comment by brentvatne** [comment]
hi! you can check the route that is active and change the button based on that. 

```
const tabNavigator = createMaterialTopTabNavigator({ /* */ });
tabNavigator.navigationOptions = ({ navigation }) => {
  let activeRoute = navigation.state.routes[navigation.state.index];
  if (activeRoute.routeName === 'contacts') { // or whatever the name is
    return {
      headerRight: <SomeThingHere />
    };
  } else {
    return {};
  }
};
```

something approximately like that should work.

for future reference, the issues are only meant to be for bug reports. see https://reactnavigation.org/help for info on where to get help
