### ISSUE TITLE
[2.0] gesturesEnabled = false not working for modal

### ISSUE THREAD

**Issue by Jonovono** [react-navigation/react-navigation#4675]
Here is a reproducible project: https://github.com/Jonovono/TestRNNav. Has the API changed since V1? Not that I could tell
---

### Current Behavior

I am trying to make it so you can't dismiss a modal by dragging down. I do the following: 

```
const RootStack = createStackNavigator({
  Home: { 
    screen: Home,
    navigationOptions: ({navigation}) => ({
        gesturesEnabled: false
    })
},
  Modal: Modal
}, {
  initialRouteName: 'Home',
  mode: 'modal',
  headerMode: 'none'
})

```

Yet, its still dismissable. This worked for me on V1. 

### Expected Behavior

I expect the screen to be unable to dismiss via dragging down

### How to reproduce

https://github.com/Jonovono/TestRNNav

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.6.2
| react-native     | 0.56.0
| node             | 8.10.0
| npm or yarn      | yarn 0.27.5

**Comment by ericvicenti** [comment]
Hmm. I just tried to reproduce this inside the navigation playground and it seems to work.. maybe its been fixed? I haven't run your example yet. usually its easiest for us if you put the whole example into one file and put it into an expo snack.

**Comment by Jonovono** [comment]
@ericvicenti wow, expo snacks are awesome :)

Here is a snack that reproduces the issue: https://snack.expo.io/SkfBsx4Q7

I noticed that it seems to only be reproducible in iOS. On android it doesn't let me dismiss the modal, but on iOS I can.

**Comment by ericvicenti** [comment]
> ios only

Thats because Android has a different default, gesturesEnabled: false.


Ok heres the issue. Your code currently is:

```js
const RootStack = createStackNavigator({
  Home: { 
    screen: Home,
    navigationOptions: ({navigation}) => ({
        gesturesEnabled: false
    })
  },
  Modal,
}, {
  ...
})
```

You have configured the home (green) screen to have gestures disabled, but you already cant swipe back from it. You should disable the gesture of the modal instead:


```js
const RootStack = createStackNavigator({
  Home,
  Modal: {
    screen: Modal,
    navigationOptions: {gesturesEnabled: false}
}, {
  ...
})
```

Or, you could disable gestures for all screens in the stack like this:

```js
const RootStack = createStackNavigator({
  Home,
  Modal,
}, {
  ...
  navigationOptions: {gesturesEnabled: false},
})
```

**Comment by mpmprudencio** [comment]
For me works when config to each screen, although it increases the memory a lot (iOS). Tried bunch of config just once on stack level and none worked out.
