### ISSUE TITLE
low performance for createDrawerNavigator

### ISSUE THREAD

**Issue by gwl002** [react-navigation/react-navigation#4676]
navigate from one page to another page in DrawerNavigaor

### Current Behavior

- What code are you running and what is happening?

Every time navigate from one page to another page ,the former page is destroyed.This is too bad for performance.When goBack the former screen ,It has to been re-rendered.

### Expected Behavior

- What do you expect should be happening?
- Include a screenshot if it makes sense.

### How to reproduce
- the snack url to reproduce :  https://snack.expo.io/@gwl002/base 

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.0.4
| react-native     | 0.52.0
| node             |  8.0.0
| npm or yarn      | 5.0.0

**Comment by brentvatne** [comment]
dup https://github.com/react-navigation/react-navigation-drawer/issues/4
