### ISSUE TITLE
How to do what the screen showed tabbar but did not belong to it?

### ISSUE THREAD

**Issue by sinevitch** [react-navigation/react-navigation#4680]
![image](https://user-images.githubusercontent.com/35930695/42639262-43ad27a2-85f8-11e8-9da4-11cfc211e213.png)

How to do what the screen showed tabbar but did not belong to it?

![image](https://user-images.githubusercontent.com/35930695/42639958-e7728f7a-85f9-11e8-85c0-d684ac3e49ed.png)

**Comment by brentvatne** [comment]
hi there! this is a question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.

**Comment by sinevitch** [comment]
On the stack there is already such a question but nobody answered it
https://stackoverflow.com/questions/45035562/is-it-possible-to-show-tab-bar-in-a-screen-but-the-screen-does-not-appear-in-the
