### ISSUE TITLE
toggleDrawer is showing black screen on android if createDrawerNavigator is nested inside of TabNavigator

### ISSUE THREAD

**Issue by radroot1** [react-navigation/react-navigation#4681]
### Current Behavior

`export const MainScreenNavigator = createMaterialTopTabNavigator({
    UserInfoMy: {
        screen: createDrawerNavigator({
            Main: {
                screen: customStackNav({
                    UserInfoMyMain: { screen: UserInfoMyViewContainer},
                    TasksAdd: { screen: TasksAddViewContainer},
                }), navigationOptions: {
                    drawerLabel: ' ',
                    drawerLockMode:"locked-closed"
                }
           },
            AboutPage: {screen: AboutPageView, navigationOptions: {drawerLabel: strings("sideMenu._aboutPage-1") }},
        },{
            drawerPosition:'right',
            contentComponent:CustomDrawerContentComponent
        }),
        navigationOptions: {
            tabBarLabel: strings("navigation._account-1"),
            tabBarIcon: ({focused}) => (
                <Image source={focused ? c.images.MENU_PROFILE_ACTIVE : c.images.MENU_PROFILE} style={style.menuIcons}/>
            )
        }
    },
})`

![image](https://user-images.githubusercontent.com/38936506/42646591-5d294282-8612-11e8-881e-a5ebf4cf1860.png)

### Expected Behavior

Should show the drawer. It worked on react-navigation 1.5.11, it is also working on ios 

### How to reproduce

Stack drawer inside of tabnavigator like in the code above

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |2.6.2
| react-native     |0.56.0
| node             |9.10.1
| npm      |6.1.0

**Comment by ericvicenti** [comment]
Hi, can you please post a minimum example of the bug? Either a standalone repo, or using Expo snack.

Otherwise I cannot see how to reproduce the issue

https://stackoverflow.com/help/mcve

**Comment by radroot1** [comment]
Hello, here it is https://github.com/radroot1/toggleDrawerTest
After fiddling with the code, I found that bug appears when DOM was updated like so 
```
if (!this.state.ready) {
            return (
                <View style={{flex: 1}}>
                    <ActivityIndicator style={styles.centered}/>
                </View>
            );
 };
        return (
            <View style={{flex: 1}}>
                <StatusBar backgroundColor='#455a64' barStyle='light-content'/>
                <Navigator/>
            </View>
);
```

**Comment by radroot1** [comment]
I committed second variant of the bug, it seems that it is not updating the DOM is the issue, but rather ActivityIndicator

**Comment by radroot1** [comment]
Committed third example with nesting tab navigator in  createStackNavigator

**Comment by vriyeit** [comment]
Good day. 

Does anyone have a solution to this? 

Thanks you.

**Comment by brentvatne** [comment]
this should be solved on react-navigation 3
