### ISSUE TITLE
cannot read property options on backbutton

### ISSUE THREAD

**Issue by Djinne** [react-navigation/react-navigation#4686]
### Current Behavior

When I navigate from a page and replace it by pop then navigate or replace and then
hitting the back button quickly before the page fully loads results in "cannot read property options of undefined" in the stackviewlayout. 

I have tried putting the replace/pop then navigate in a componenthasmounted, and conditional ismounted to no avail. I am guessing the pop is causing a race condition to where the back button is hit it triggers on the first screen and tries to navigate on a stack that has been removed

`const ViewProfileScreen = createStackNavigator({
  ViewProfile: {key:"ViewProfile", screen: ViewProfile,path:"ViewProfile/:id",
    navigationOptions: ({ navigation }) => ({
    headerMode:"float" ,
    headerLeft: <HeaderBackButton onPress={() =>{navigation.goBack(null);  }} />,
  }),
  },
});

const EditProfileScreen = createStackNavigator({
  EditProfileScreen: { key:"EditProfile",screen: EditProfile,path:"editProfile/:id",
    navigationOptions: ({ navigation }) => ({
    headerMode:"float" ,
    headerLeft: <HeaderBackButton onPress={() =>{navigation.goBack(null)}} />,
    }),
  },
});`

![screen shot 2018-07-13 at 17 39 18](https://user-images.githubusercontent.com/29455151/42700326-b08bfcd8-86c3-11e8-8fa8-926127a8d074.png)

### Expected Behavior

Back button not to break

**Comment by Djinne** [comment]
It works fine if i replace if they are on the same stack

**Comment by ericvicenti** [comment]
Thanks for the report. It definitely shouldn't crash. What version are you using?

Out of curiosity, what happens if you call `navigation.goBack()` without `null`? In v2 of the library, I don't think you need to use null in this case.

Can you do me a favor and re-create this bug within a single file on Expo snack? It will help me see the error on my computer such that I can fix it.

**Comment by Djinne** [comment]
I have made an expo: https://snack.expo.io/SyyC1g5Qm

I must be using V1 since I do require the null for the back buttons to work.
Basically, after clicking the blue button, start clicking the top left back button and an error could occur if you are fast enough

**Comment by eriveltonelias** [comment]
Hi @Djinne!

if you update your `react-navigation` to the last, will works fine.
