### ISSUE TITLE
Detect navigation action that moves between navigators

### ISSUE THREAD

**Issue by haseebnaseem** [react-navigation/react-navigation#4688]
## The issue tracker is reserved for bug reports only.

If you have a question, feature request, or an idea for improving the library or its related tools, please try one of the following resources:

- [Read the documentation](https://reactnavigation.org/)
- [Post an issue to the website repository if you'd like to see a documentation change](http://github.com/react-navigation/website)
- [Post a feature request to Canny](https://react-navigation.canny.io/feature-requests)
- [Write a RFC if you have ideas for how to implement a feature request](https://github.com/react-navigation/rfcs)
- [Get help on Discord chat (#react-navigation on Reactiflux)](https://discord.gg/4xEK3nD) or [on StackOverflow](https://stackoverflow.com/questions/tagged/react-navigation)
- Search for your issue - it may have already been answered or even fixed in the development branch. However, if you find that an old, closed issue still persists in the latest version, you should open a new issue.

Bugs with react-navigation must be reproducible *without any external libraries that operate on it*. This means that if you are attempting to use Redux or MobX with it and you think you have found a bug, you must be able to reproduce it without Redux or MobX in this report. Redux related issues belong in [react-navigation-redux-helpers](https://github.com/react-navigation/react-navigation-redux-helpers), and we do not have any first-class integration with MobX at the moment.

---

### Current Behavior
This is how my navigators are defined:
```
const navigatorA = TabNavigator({
    screenA :{screen: navigatorX},
    screenB: {screen: navigatorY},
});

const navigatorX = Stacknavigator({
     home: {screen: home},
      options: {screen: options},
});

const navigatorY = StackNavigator({
     profile: {screen: profile},
     settings :{ screen: settings}
})
```
I pass params like `this.props.navigation.navigate({routeName:'profile', params:{user:{thisUser}});`

I want to reset the navigation params when the user navigates back to the home screen from profile screen but not when the user navigate to the settings screen from the profile screen.

using `this.props.navigation.setParams({user:nulll});` in `componenWillUnmount` does not achieve the task as it resets the params even when user navigate from profile to settings.

I have tried using the `willBlur` event listener as well but it does not work in stack navigator and only tab navigators. 
### Expected Behavior

The navigation param reset when there is a navigation action that changes the navigator. 

### How to reproduce

- You must provide a way to reproduce the problem. If you are having an issue with your machine or build tools, the issue belongs on another repoistory as that is outside of the scope of React Navigation.
- Either re-create the bug on [Snack](https://snack.expo.io) or link to a GitHub repository with code that reproduces the bug.
- Explain how to run the example app and any steps that we need to take to reproduce the issue from the example app.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.5.11
| react-native     | 0.49.5
| node             | 7.10
| npm or yarn      | 4.2.0

**Comment by ericvicenti** [comment]
Hello, can you please open a new issue with the template filled out correctly?

The willBlur event should work fine if you upgrade to v2 of the library
