### ISSUE TITLE
how to navigate to another screen with react-navigation when the token is fetched and stored

### ISSUE THREAD

**Issue by dcalixto** [react-navigation/react-navigation#4689]
After setup 2 screens with react-navigation. The first screen there is a Login and on button pressed fetch the token from the server. And I need to navigate to another screen only when fetch and the token is stored. All I found at react-navigation docs is a solution with button and navigation header, but it's not this case.

I've tried to place the redirect prop inside the function but did not worked.

> 
in the logs show: Invariant Violation: Objects are not valid as a React child (found: TypeError: undefined is not an object (evaluating 'this.props.navigation.navigate')). If you meant to render a collection of children, use an array instead.

Please someone has any hint to spare?

Thanks a lot!

here is the code

import React, { Component } from 'react';
import { Text, TextInput, View, StyleSheet, AsyncStorage } from 'react-native';
import { Card, Button, CardSection, Input, Spinner } from '../components';
import { createStackNavigator } from 'react-navigation';

const AUTH_TOKEN = 'auth_token';

class Login extends Component {

    constructor() {
        super();
        this.state = {
            email: "",
            password: "",
            error: ""
        }

    }

   storeToken(responseData){
    AsyncStorage.setItem(AUTH_TOKEN, responseData, (err)=> {
      if(err){
        console.log("Something went wrong");
        throw err;
      }
      console.log("Success");
    }).catch((err)=> {
        console.log("error is: " + err);
    });
  }

**Comment by kirakik** [comment]
Hey @dcalixto! It seems like you haven't configured your routes yet, did you [check out this part of the documentation](https://reactnavigation.org/docs/en/hello-react-navigation.html)? If you have configured them, then you need to navigate using `this.props.navigate("YOUR_ROUTE)`, once your token is fetched and stored.

It's great that you started working with React Navigation, myself and many others would love to help you out, but to make sure the issues here don't get too out of hand, and strictly contain bug reports and feature requests, it would be better if you could ask your questions on StackOverflow, [reactiflux](https://www.reactiflux.com/) or [Infinited Red Community](https://infiniteredcommunity.herokuapp.com/)
