### ISSUE TITLE
[v2] navigationOptions does not work in  createBottomTabNavigator

### ISSUE THREAD

**Issue by mechanizzed** [react-navigation/react-navigation#4690]
I'm trying to put a HOME title in the header using createBottomTabNavigator, but nothing happens. The same problem happens if I try to disable the header using `header: null`.

I also tried to use `headerTitle: 'HOME'`, but the problems persist.

Anything I do in navigationOptions is not working in createBottomTabNavigator.

![captura de tela 2018-07-13 as 14 56 32](https://user-images.githubusercontent.com/4992281/42717784-f43a956e-86d9-11e8-96de-b0c0ea0c5a38.png)

**Comment by brentvatne** [comment]
https://reactnavigation.org/docs/en/navigation-options-resolution.html

**Comment by mechanizzed** [comment]
I've changed my code for this and it's working fine.

![captura de tela 2018-07-13 as 23 15 18](https://user-images.githubusercontent.com/4992281/42719915-4ebbc3cc-86f4-11e8-9278-12a007577939.png)
