### ISSUE TITLE
toggleDrawer is showing black screen on android if createDrawerNavigator is nested inside of TabNavigator

### ISSUE THREAD

**Issue by radroot1** [react-navigation/react-navigation#4692]
Hello.
### Current Behavior

![image](https://user-images.githubusercontent.com/38936506/42646591-5d294282-8612-11e8-881e-a5ebf4cf1860.png)

### Expected Behavior

Should show the drawer. It worked on react-navigation 1.5.11, it is also working on ios 

### How to reproduce

https://github.com/radroot1/toggleDrawerTest
There are 3 variants of the bug committed one by one
One with ActivityIndicator that causes the bug, with dom update and third example with tab navigator nested inside of createStackNavigator. All with the same problem: drawer not showing with toggleDrawer  on android
### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |2.6.2
| react-native     |0.56.0
| node             |9.10.1
| npm      |6.1.0

**Comment by brentvatne** [comment]
hi! thanks for reporting. this is covered by this umbrella issue: https://github.com/react-navigation/react-navigation/issues/4154
