### ISSUE TITLE
Clearing navigation stack while navigating to new tab

### ISSUE THREAD

**Issue by SrujithPoondla** [react-navigation/react-navigation#4696]
My navigation looks like this 

TabNavigator
--Home
--Camera
--User (StackNavigator)
-------camera
-------settings

initially if i am in User --> Camera and then if i go to camera tab it works fine. But when i go back to User tab, it still shows the Camera screen and it is just stuck as the component in camera tab is not unmounting.  

It works normal if i go back to user from  user--camera and then to camera tab. 

Is my my navigation flow correct? If yes how to resolve this issue?
(I am using expo camera component)

**Comment by ericvicenti** [comment]
Its hard to see what the issue is, unless you post a simple code example of the bug

**Comment by SrujithPoondla** [comment]
Thanks for the feedback. I added the navigation code, hope this helps.

```
const cameraScreens = createStackNavigator(
  {
    cameraScreen: { screen: CameraScreen },
    scanItemScreen: { screen: ScanItemScreen }
  },
  {
    headerMode: 'none'
  }
);

const userScreens = createStackNavigator({
  userScreen: { screen: UserScreen },
  settingsScreen: { screen: SettingsScreen },
  scanItemScreen: { screen: ScanItemScreen },
  createNewItemScreen: { screen: CreateNewItemScreen }
});

const eventScreens = createStackNavigator(
  {
    homeScreen: { screen: HomeScreen },
    listScreen: { screen: ListScreen }
  }
);

const tabScreens = createBottomTabNavigator(
  {
    homeScreen: { screen: listScreens },
    cameraScreen: { screen: cameraScreens },
    notificationsScreen: { screen: NotificationsScreen },
    userScreen: { screen: userScreens }
  });

const loginSwitch = create SwitchNavigator({
  loginScreen: {screen: loginscreen}
});

const RootNav = createSwitchNavigator(
  {
    login: { screen: LoginSwitch },
    tabs: { screen: tabScreens }
  },
  {
    headerMode: 'none',
    initialRouteName: 'login'
  }
);
```
The app flow looks like this: (camera component is in scanItemScreen)

In the tab navigator assume i am in userScreen tab and can go to scanItemScreen using a button.
While i am in scanItemScreen if i go to cameraScreen tab directly, the camera works fine. 
From cameraScreen tab if i go to userScreen tab using the tab button then it is still showing the previous stack i.e scanItemScreen(camera component) which is just stuck and camera not working. 

Is there any way to reset the navigation stack while moving between tabs?

**Comment by brentvatne** [comment]
you can add a listener to get updates when a screen is focused / blurred and do what you need in response to that - https://reactnavigation.org/docs/en/navigation-prop.html#addlistener-subscribe-to-updates-to-navigation-lifecycle

**Comment by audiolion** [comment]
I am having issues with this as well. I would love to be able to say, when you click a tab it always takes you to the initial route. doing a subscription would start navigating to the old screen then reset it, could be problematic right? Shouldn't there be a navigation option as part of tab navigator (as this is a common nav for main app navigation) to always return to the initial route?

This is how an app like Spotify will work:
```
Home
Browse
Your Library
  -- Playlists
    -- Individual Playlist
```

If I go to `Your Library => PlayLists => Individual Playlist` on Spotify then click "Browse" tab navigator then click "Your Library" tab navigator, it brings me back to the initial route. The behavior with react-navigation will bring you back to that individual playlist.

**Comment by keithics** [comment]
+1 for this, I need a way for a tab to show/reset the stack when clicked.

**Comment by jacek213** [comment]
the same for me, it seems like a natural app flow to me, should be documented how to do it

**Comment by brentvatne** [comment]
another easy way to do this is with the `resetOnBlur` option - https://snack.expo.io/@notbrent/supportive-pastry

it doesn't popToTop for the contents but instead just re-creates the entire tab state, so you'll see that it resets to a screen with a new key

**Comment by jacek213** [comment]
thanks a lot @brentvatne, that's exactly what I needed! The only problem is that `@types/react-navigation` do not include `resetOnBlur` option for `BottomTabNavigatorConfig`. However that's not a problem with the lib itself, but the third-party typings. I'm going to submit a PR for this.

**Comment by brentvatne** [comment]
ah yes, I added it a while ago specifically for switch navigator, and since tabrouter just extends switchrouter it works here. https://reactnavigation.org/docs/en/switch-navigator.html#switchnavigatorconfig

can you open a pr to add it to docs? https://github.com/react-navigation/website

**Comment by jacek213** [comment]
@brentvatne  Sure. Added and references above.
