### ISSUE TITLE
Redux Support Warning

### ISSUE THREAD

**Issue by ayehia** [react-navigation/react-navigation#4697]
I am new to react-native-navigation coming from wix navigation

I have a confusion about this statement 

**"Warning: in the next major version of React Navigation, to be released in Fall 2018, we will no longer provide any information about how to integrate with Redux and it may cease to work. "** 

Mentioned in the documentation about Redux .... I need to manage my application state NOT the navigation state so I need to know if there is any method to achieve that using Redux

Seems that all articles speak about managing the navigation state

**Comment by brentvatne** [comment]
you can do whatever you like with your application state, the paragraph in the docs is just to warn you that the approach mentioned on that page will no longer by documented in the future and the ability to put your navigation state in a redux store alongside the rest of your application state may or may not continue to work
