### ISSUE TITLE
NavigationActions POP is undefined

### ISSUE THREAD

**Issue by ahce** [react-navigation/react-navigation#4698]
### Current Behavior

- console.warn(NavigationActions.POP) = undefined

### Expected Behavior

- console.warn(NavigationActions.POP) = Navigation/POP

### Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.6.2
| react-native     | 0.55.4
| node             | 8.11.3
| npm       | 5.6.0

**Comment by ericvicenti** [comment]
Please post some simple example code that demonstrates this issue.

**Comment by ahce** [comment]
@ericvicenti Check console warn in LoginScreen of this code:
[ReduxExample.zip](https://github.com/react-navigation/react-navigation/files/2199861/ReduxExample.zip)

**Comment by brentvatne** [comment]
`StackActions.POP`

**Comment by brentvatne** [comment]
https://reactnavigation.org/docs/en/stack-actions.html#pop

**Comment by brentvatne** [comment]
`StackActions.POP`
