### ISSUE TITLE
How to jump to a page of TabNavigator after NavigationActions.reset

### ISSUE THREAD

**Issue by ZhangTaoK** [react-navigation/react-navigation#4703]
The initialization is on the home page, then resetting the route from one page to the tab page, and how to jump to the ShoppingCart page in the tab page.

I need help, thank you！

NavigationActions.reset => Go to the ShoppingCart in TabNavigator ？
code:
const resetAction = NavigationActions.reset({     
     index: 0,
     actions: [
         NavigationActions.navigate({ routeName: 'Tab'}),
         //NavigationActions.navigate({ routeName: 'ShoppingCart'}),
     ]
 })
======
const Tab = TabNavigator({
    Home: {
        screen: HomeFragment,
    },
    AllGoods: {
        screen: AllGoodsFragment,
    },
    ShoppingCart: {
        screen: ShoppingCartFragment,
    },
    User: {
        screen: UserFragment,
    }
}, {
      initialRouteName: 'Home',
      ...
});

**Comment by ZhangTaoK** [comment]
Is there a better way to do it besides this ？

const Tab = TabNavigator({
A: {
screen: A,
},
B: {
screen: B,
},
}, {
initialRouteName: 'A',
...
});

const Tab2 = TabNavigator({
A: {
screen: A,
},
B: {
screen: B,
},
}, {
initialRouteName: 'B',
...
});

const resetAction = NavigationActions.reset({
index: 0,
actions: [
NavigationActions.navigate({ routeName: 'Tab2'}),
]
})

**Comment by brentvatne** [comment]
@ZhangTaoK - can you create a runnable example on https://snack.expo.io or in a github repo we can clone? when you do, please post a new issue with a link to it and more information. thanks!
