### ISSUE TITLE
Inverted gestures not working in modal stack navigator

### ISSUE THREAD

**Issue by niocncn** [react-navigation/react-navigation#4705]
https://snack.expo.io/S1mlvQs7Q
As you can see gestures direction is 'inverted', but really gestures works from top to bottom.

in 1 version of react-navigation all works good, but in version 2 direction does not change.

| software         | version
| ---------------- | -------
| react-navigation |  2.6.2
| react-native     | 0.55.4
| npm or yarn      | 5.8

**Comment by brentvatne** [comment]
this is fixed in 3.0-alpha, however it does not actually invert the direction of the animation, that's up to you still. https://github.com/react-navigation/react-navigation-stack/commit/4f4b8e4d41ec8291ba2dec9b526296a895a8b6ea
