### ISSUE TITLE
force rerender page on .pop()

### ISSUE THREAD

**Issue by barron9** [react-navigation/react-navigation#4707]
how can i force a funtion to run after pop back to some page?

**Comment by JoseVf** [comment]
Try passing the function as a param to the nested route and call it before you execute the `.pop()`.

**Comment by brentvatne** [comment]
you can use focus events (eg: https://reactnavigation.org/docs/en/with-navigation-focus.html or https://reactnavigation.org/docs/en/navigation-events.html)
