### ISSUE TITLE
Add warning for when people use drawer navigator inside tab navigator

### ISSUE THREAD

**Issue by brentvatne** [react-navigation/react-navigation#4714]
This doesn't work on Android currently and nobody is working on fixing that at the moment, so we should warn. https://github.com/react-navigation/react-navigation/issues/4154

**Comment by daviscabral** [comment]
@brentvatne would you consider accept a PR that fixes that? Just checking before considering workarounds in other libs that consumes react-navigation.

**Comment by brentvatne** [comment]
in https://github.com/react-navigation/react-navigation-drawer/tree/next i switched to using drawerlayout from react-native-gesture-handler, and that should resolve the issue, but I haven't verified that yet

**Comment by brentvatne** [comment]
i believe it's fixed but created an issue to verify it here: https://github.com/react-navigation/react-navigation-drawer/issues/21
