### ISSUE TITLE
Getting state to header (navigationOptions)

### ISSUE THREAD

**Issue by mkloar** [react-navigation/react-navigation#4717]
Hey guys.

I want to access my state from constructor in header, I want to display some data in header from my state. I do not see what is wrong with code. I got an error: undefined is not an object (this.state.user.name)....

### Current Behavior
My code in Home.js:
```
static navigationOptions = ({ navigation }) => ({

        headerTitle: "Tab1",
        headerLeft: (
          <View style={styles.oval}>
          	<Text>Logo</Text>
          </View>
        ),
        headerRight: (
          <View style={styles.headerRight}>
	        <TouchableOpacity
		        title="Ok" 
		        		//onPress={ this.changeScreen.bind(this) }>
		        onPress={() => navigation.navigate('MyProfil')}>
		        	
		        <View style={styles.circle}>
		        	<Text style={styles.txtInside}>{this.state.user.name}</Text> 
		        </View>
	        </TouchableOpacity>
	      </View>
        )
    });
constructor(props) {
    	super(props);

    	this.state = {
    		user: null,
    	}
    	
    }

    //is called before render
    componentWillMount() {

    	const {setParams} = this.props.navigation;

    	AsyncStorage.getItem('user', (err, result) => {
      		this.setState({
				user: JSON.parse(result),
			});
			
			setParams({
				user: this.props.user,
			});
	
		});

    	    
		
		//alert('sem not');
 	}
```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |
| react-native     |
| node             |
| npm or yarn      |

**Comment by brentvatne** [comment]
hi, you need to use setParams to pass state to header, eg: https://reactnavigation.org/docs/en/header-buttons.html#header-interaction-with-its-screen-component

**Comment by mohmdalfaha** [comment]
Using setParams and getParams doesn't guarantee re-rendering when the state changes. What should be used in this case?

**Comment by andy-h-dev** [comment]
> hi, you need to use setParams to pass state to header, eg: https://reactnavigation.org/docs/en/header-buttons.html#header-interaction-with-its-screen-component

I was stuck on this for ages! Thanks for the link to documentation!

**Comment by AnasAlamin** [comment]
> Using setParams and getParams doesn't guarantee re-rendering when the state changes. What should be used in this case?

i think you should probably use redux
