### ISSUE TITLE
headerTransitionPreset without fade?

### ISSUE THREAD

**Issue by donni106** [react-navigation/react-navigation#4718]
### Current Behavior

Currently there are two options for `headerTransitionPreset`: `fade-in-place` and `uikit`, right? Fading is the default.
When I navigate to from one screen to another it fades, no matter the header title.

### Expected Behavior

Is there a way to disable the fade when labels are not changing? So when there is "Selections" on one screen and I navigate to another which also has "Selections" as header title, the fade effect is not absolutely necessary. In my case I would like to have no effect for same titles on different screens.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.5.12
| react-native     | 0.55.4
| node             | 8.11.3
| npm or yarn      | yarn 1.7.0

**Comment by brentvatne** [comment]
nope. you can do this by putting a stack inside another stack and putting the header on the outer one then pushing screens to the inner one if you want to.
