### ISSUE TITLE
createDrawerNavigator contentComponent 

### ISSUE THREAD

**Issue by giantss** [react-navigation/react-navigation#4719]
### Current Behavior

Any operation will triggered the custom CustomDrawerContentComponent render method  twice.
Please see the gif image below.
![image](https://user-images.githubusercontent.com/13778798/42893281-7861a19c-8ae6-11e8-98cc-8e7cde7d13c6.gif)

### Expected Behavior

The render method is only triggered when the DrawerNavigator is opened.

### How to reproduce

simple code
```
const HomeStack = createStackNavigator(
    {
        Home: HomeScreen,
        Details: DetailsScreen,
    },
    {
        navigationOptions:{
            headerStyle:{
                backgroundColor: '#fff'
            },
            headerTintColor: '#111111',
            headerTitleStyle: {
                fontWeight: 'bold',
            },
        }
    });

const NewsStack = createStackNavigator({
    News: NewsScreen,
    newsDetail: NewsDetail
},
    {
        navigationOptions:{
            headerStyle:{
                backgroundColor: '#fff'
            },
            headerTintColor: '#111111',
            headerTitleStyle: {
                fontWeight: 'bold',
            },
        }
    });

const Tab = createBottomTabNavigator({
    Home: HomeStack,
    News: NewsStack
},{
    initialRouteName: 'Home',
    tabBarOptions: {
        showLabel: false,
        style:{
            height:0
        }
    }
});

const CustomDrawerContentComponent = (props) => (
    <ScrollView>
        <SafeAreaView style={{flex: 1}} >
            <CusDrawerNavigatorItems userData={Global.userInfo} {...props}/>
        </SafeAreaView>
    </ScrollView>
);

// export default createBottomTabNavigator({
export default createDrawerNavigator({
    bottomTab: Tab,
},{
    drawerWidth: width-120,
    contentComponent: CustomDrawerContentComponent
});
```
`CusDrawerNavigatorItems`
```
export default class CusDrawerNavigatorItems extends Component {
 render(){
    console.log('CusDrawerNavigatorItems');  //Any operation (push、pop ...) will triggered  render method  twice.
   return null;
 }
}
```

### Your Environment

Environment:
  OS: macOS Sierra 10.12.6
  Node: 6.11.0
  Yarn: 0.24.5
  npm: 4.6.1
  Watchman: 4.7.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 2.3 AI-162.3934792

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.53.0 => 0.53.0

I personally think that this is a waste of performance, what do you think?

**Comment by brentvatne** [comment]
this is happening because the drawer state is changing when the drawer opens or closes. you can use shouldComponentUpdate or some other technique that react gives you like PureComponent on some of the children to improve this if you want to - here are the props that are passed in https://github.com/react-navigation/react-navigation-drawer/blob/1402e23a422c1f885d0587631a6e43efce815738/src/views/DrawerSidebar.js#L79-L92
