### ISSUE TITLE
Adding component inside drawer menu item 

### ISSUE THREAD

**Issue by bonbonio** [react-navigation/react-navigation#4720]
How to add a notification number next to a react-navigation drawer menu?

I want a notification count component next to a drawer menu item which shows the classic number bubble and I’d like it to fetch the count every time it’s displayed.

Has anyone got an example in the docs or something I could see? I’d post on SO but maybe this is too niche to yet get answers.

By the way v2 is much improved over v1 in every way!

**Comment by brentvatne** [comment]
hi! you probably want to have a completely custom `contentComponent` for the drawer: https://reactnavigation.org/docs/en/drawer-navigator.html#providing-a-custom-contentcomponent
