### ISSUE TITLE
DrawerNavigator why need createStackNavigator?

### ISSUE THREAD

**Issue by daniele-zurico** [react-navigation/react-navigation#4721]
Hi everyone,
is almost one day that I'm going around looking the best option to create a simple scenario:
![screenshot 2018-07-18 16 22 58](https://user-images.githubusercontent.com/3193095/42898019-d60aee5c-8ab9-11e8-9f77-8ed2e4ef83b0.png)

The spec is quite easy:
I want a menu bar with an hamburger that open the DrawBar.

Is it possible to have this result using ONLY the `createDrawerNavigator` ? Or I need a `createStackNavigator` in any case?

Of course I don't want to import in each view the menu bar so I would like to avoid the case to import in each view my hamburger component.
At the moment the option I saw are:
1) create stackNavigation with 1 screen that is the drawer navigator:
```
const Drawer = createDrawerNavigator({
  Home: {
    screen: Home,
  },
  Categories: {
    screen: Categories,
  },
});

export const StackNavigator = createStackNavigator(
  {
    DrawerScreen: {
      screen: Drawer,
    },
  },
  {
    navigationOptions: ({ navigation }) => ({
      headerLeft: <MenuButton navigation={navigation} />,
```

2) the opposite: create 1 Drawer and n stack navigator

3) create only the DrawerNavigator and in each component you import the 
`<MenuButton navigation={navigation} />,`

I think that all of them are not good because I would like to have only the createDrawerNavigator adding the navigation option.

Can someone help me on that please?

**Comment by brentvatne** [comment]
hi there! this is a question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.

**Comment by daniele-zurico** [comment]
Hi @brentvatne I'm on discord for almost this morning and us I said the option I got are really a lot and the documentation doesn't help on that. Can you please be so kind to reopen the ticket and or provide a solution that can be used as source of truth for this easy scenario?
