### ISSUE TITLE
How to control the bottom menu in deep nesting

### ISSUE THREAD

**Issue by pengkun007** [react-navigation/react-navigation#4725]
hello everyone ， 
First I created createMaterialBottomTabNavigator in my project,

![w vd47 1zsn0 7ne tgpxbk](https://user-images.githubusercontent.com/39861368/42926641-9be4f492-8b64-11e8-8740-04386033957a.png)

Then go to create createStackNavigator on each page.
![vcr5 udq8 spk8 f 0yq](https://user-images.githubusercontent.com/39861368/42926703-c58797b4-8b64-11e8-9955-25c4c32d5f0f.png)

This is the find_index mentioned above
![c jk4c1 wn dmi 7t 0a d](https://user-images.githubusercontent.com/39861368/42926814-1745666c-8b65-11e8-8950-966d29a3640f.png)

How do I control the display and hiding of the bottom navigation bar here?
Can anyone help me? Many thanks

**Comment by brentvatne** [comment]
https://reactnavigation.org/docs/en/navigation-options-resolution.html

**Comment by pengkun007** [comment]
@brentvatne Thank you for solving my problem. May you have a good mood. I ignored this piece when I read the document.
