### ISSUE TITLE
can't navigate to Auth in createSwitchNavigator when App is component

### ISSUE THREAD

**Issue by yooouuri** [react-navigation/react-navigation#4728]
### Current Behavior

- See the code please.
- It does not navigate to the Auth inside the createSwitchNavigator.

### Expected Behavior

- It should navigate to the Auth.

### How to reproduce

Inside the `More` component I perform a `this.props.navigation.navigate('Auth')`

When the `App` in the `createSwitchNavigator` is a component, the navigate to Auth does not work. When I change it to `AppStack` instead of the component it works...

But it needs to be a component because I need to.

```javascript
const AppStack = createBottomTabNavigator(
  {
    More: MoreStack,
  }
);

const MoreStack = createStackNavigator(
  {
    More: More,
  }
);

class App extends React.Component {
  render() {
    return (
      <AppStack uriPrefix={prefix} />
    );
  }
}

export default createSwitchNavigator(
  {
    AuthLoading: LoadingScreen,
    App: App, // <--- component, instead of AppStack
    Auth: AuthStack,
  },
  {
    initialRouteName: 'AuthLoading'
  }
);
```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.6.2
| react-native     | 0.55.4
| node             | v8.11.3
| npm or yarn      | yarn

**Comment by brentvatne** [comment]
you probably get a warning about having multiple navigators, you should pay attention to that warning :) it will guide you to this: https://reactnavigation.org/docs/en/common-mistakes.html#explicitly-rendering-more-than-one-navigator

**Comment by yooouuri** [comment]
Thanks for replying, the solution of **Explicitly rendering more than one navigator** did it!
