### ISSUE TITLE
Drawer navigator view remains visible when navigating to parent route

### ISSUE THREAD

**Issue by mishkamishka47** [react-navigation/react-navigation#4731]
### Current Behavior
This bug is only present on iOS. The following code works as expected on Android.

I have this view configuration (truncated to relevant pieces):

```typescript
const AppNavigator = SwitchNavigator({
  AuthorizationLoading: { screen: AuthorizationLoading },
  Authorization: { 
    screen: StackNavigator({
      Branch: { screen: Branch },
      Login: { screen: Login },
      Signup: { screen: Signup }
    }, {
      initialRouteName: 'Branch'
    })
  },
  Main: {
    screen: SwitchNavigator({
      MainLoading: { screen: MainLoading },
      MainApp: {
        screen: DrawerNavigator({
          Home: { screen: Home },
          Logout: { screen: Logout }
        })
      }
    })
  }
})
```

I want to be able to navigate back to `Branch` from `Logout`. However, when accessing the `Logout` component, which has this method...

```typescript
componentDidMount() {
  this.props.navigation.navigate('Branch')
}
```

...the lifecycle events of the `Branch` screen trigger but the `Home` screen is displayed over it. Interestingly, when navigating to the `AuthorizationLoading` screen from `Logout`, which in its `componentDidMount` method ultimately redirects to `Branch`, the navigation is successful. My guess is that this navigation is happening on a higher-level navigator instance, and so it's working.

#### Things I've tried
1. Write a navigation service that stores a reference to the top-level navigator
    * Result: Same as above - drawer view remains on top of navigated view

1. Store a reference to the switch navigator that contains the drawer navigator (`MainApp`) and navigate with that
    * Result: This works, but it's bad practice since I need to explicitly render the `MainApp` navigator

1. Navigate to `AuthorizationLoading` instead with some route params that dynamically select where to re-route
    * Result: This works, too, but there's still a flicker of the `Home` screen before navigation, and it's a pretty obtuse workaround

### Expected Behavior

Navigating to `Logout` should immediately navigate back to `Branch`, and the drawer navigator's views should no longer be visible. As stated above, this is the behavior on Android.

### How to reproduce

See this [Snack](https://snack.expo.io/Bko8GuJ47).

1. Open the app and click "Go to Main"
1. Click "Open Drawer"
1. Click "Logout", which is set up to navigate to `Branch`
1. Note that the `Main` view is still visible
1. Click "Open Drawer"
1. Click "Logout w/ Redirect"
1. Note that the `Branch` screen is now visible, since we navigated to `AuthorizationLoading`, which in turn navigates to `Branch`

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^2.5.5
| react-native     | 0.55.4
| node             | 8.9.4
| npm or yarn      | 1.7.0

**Comment by ericvicenti** [comment]
Hmm, seems like there is a real problem because this should behave the same on both platforms.

But.. I don't think it is such a good idea to navigate immediately when a screen mounts. Instead of navigating to a logout screen, why don't you just call some code to log out, and then navigate to the branch screen normally?

**Comment by mishkamishka47** [comment]
As it turns out, it had been a workaround to navigate then navigate again the way we were doing it. It's been refactored to just log out and navigate to the branch screen as as result of the button press in the drawer navigator instead of going to a view to do it, like you suggested. I left the issue open in case you felt that there are still some use cases that this bug could affect, but the new code is working well.

**Comment by brentvatne** [comment]
on the react-navigation-drawer next branch we use react-native-gesture-handler ("rngh") which resolves this issue. you can install `react-navigation-drawer@1.0.0-alpha.2` and use it by importing `createDrawerNavigator` directly from that package rather than react-navigation. you will also need to install and link rngh (already included in expo so no need if you use that).

this will be default in react-navigation 3
