### ISSUE TITLE
Navigate between a StackNavigator from an inner TabNavigator

### ISSUE THREAD

**Issue by Naeoth** [react-navigation/react-navigation#4732]
### Current Behavior

I would like to navigate to a StackNavigator from a TabNavigator, but it does not work because the TabNavigator does not recognize the others routes. I know it is possible if I return directly my createMaterialTopTabNavigator. But in my case, I need to pass props for each tab so, I use an arrow function which returns a component TabNavigator.

### Expected Behavior

I expect to navigate between the Navigator with the same Router, but in my case, 2 navigators are created because of the arrow function. Seems to be this "common mistake" : [Doc from React Navigation](https://reactnavigation.org/docs/en/common-mistakes.html). However, I do not succeed 
to share the routers between my navigators and call this.props.navigation.navigate with the given example.

### How to reproduce

```
import React from "react";
import { Text, View, Button } from "react-native";
import {
  createStackNavigator,
  createMaterialTopTabNavigator
} from "react-navigation";

class HomeScreen extends React.Component {
  render() {
    return (
      <View style={{ flex: 1, alignItems: "center", justifyContent: "center" }}>
        <Text>Home Screen</Text>
      </View>
    );
  }
}

type Props = { number: number };
class Tab extends React.Component<Props> {
  onPressClick = () => this.props.navigation.navigate("HomeScreen");

  render() {
    return (
      <View style={{ flex: 1, alignItems: "center", justifyContent: "center" }}>
        <Text>Tab {this.props.number}</Text>
        <Button title="Click Me" onPress={this.onPressClick} />
      </View>
    );
  }
}

class TabsNav extends React.Component {
  render() {
    const Tabs = createMaterialTopTabNavigator({
      Tab1: {
        screen: ({ navigation }) => <Tab navigation={navigation} number={1} />
      },
      Tab2: {
        screen: ({ navigation }) => <Tab navigation={navigation} number={2} />
      }
    });

    return <Tabs />;
  }
}

const RootNavigator = createStackNavigator(
  {
    Home: HomeScreen,
    Tabs: TabsNav
  },
  {
    initialRouteName: "Tabs",
    headerMode: "null"
  }
);

export default RootNavigator;
```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.8.0
| react-native     | 0.56.0
| node             | 10.3.0
| npm or yarn      | 6.1.0

**Comment by brentvatne** [comment]
`TabsNav` needs to expose a `router` static property as the doc you linked to explains. You can't dynamically create the navigator in the `render()` function because you need it to set the static when you define the component.

**Comment by ds8k** [comment]
@brentvatne The docs don't seem to be applicable to a dynamically built navigator. @Naeoth even mentioned in his issue that he was unsuccessful in trying to expose the router:

>However, I do not succeed to share the routers between my navigators and call this.props.navigation.navigate with the given example.

I'm trying to do something similar. I have a react-navigation modal component that needs to build tabs and views based on an array of data passed through the nav params. How can I expose a static router of a dynamically built navigator?

**Comment by Naeoth** [comment]
@ds8k I partially found a solution for my case. The idea is to build dynamically the screens before the creation of the stack withouth using a React Native components. So if you need to pass parameters via props from a parent router (for example), my solution does not work. But if you want data from a redux store or a webservice, it works.

```
import React from "react";
import { Text, View, Button } from "react-native";
import {
  createStackNavigator,
  createMaterialTopTabNavigator
} from "react-navigation";

class HomeScreen extends React.Component {
  render() {
    return (
      <View style={{ flex: 1, alignItems: "center", justifyContent: "center" }}>
        <Text>Home Screen</Text>
      </View>
    );
  }
}

type Props = { number: number };
class Tab extends React.Component<Props> {
  onPressClick = () => this.props.navigation.navigate("HomeScreen");

  render() {
    return (
      <View style={{ flex: 1, alignItems: "center", justifyContent: "center" }}>
        <Text>Tab {this.props.number}</Text>
        <Button title="Click Me" onPress={this.onPressClick} />
      </View>
    );
  }
}

buildScreens = () => {
  // Get your data from your web services
  // Or use getState from the redux store to access of your redux data
  return { 
    Tab1: {
      screen: ({ navigation }) => <Tab navigation={navigation} number={1} />
    },
    Tab2: {
      screen: ({ navigation }) => <Tab navigation={navigation} number={2} />
    }
  };  
}

const RootNavigator = createStackNavigator(
  {
    Home: HomeScreen,
    Tabs: createMaterialTopTabNavigator(buildScreens())
  },
  {
    initialRouteName: "Tabs",
    headerMode: "null"
  }
);

export default RootNavigator;
```

In your case, it is not possible. If you try to encapsulate the RootNavigator in a component to get your _nav params_, the navigation will not work anymore.
