### ISSUE TITLE
Header backgroundColor is no longer overridden (for transluscent/transparent BG)

### ISSUE THREAD

**Issue by JulianKingman** [react-navigation/react-navigation#4734]
### Current Behavior

When I set the backgroundColor in headerStyle, the wrapping view behind the styled component has a hardcoded backgroundColor that cannot be overridden (#f7f7f7).

### Expected Behavior

It should be possible to override the backgroundColor.

### How to reproduce

The relevant code is here: https://github.com/react-navigation/react-navigation/blob/master/src/views/Header/Header.js#L546-L548
From this commit: https://github.com/react-navigation/react-navigation/blob/54448ed070d87b590cb5f7c9bc2c7bd93a126714/src/views/Header/Header.js#L497

### Your Environment

Environment:
  OS: macOS High Sierra 10.13.6
  Node: 10.2.1
  Yarn: 1.5.1
  npm: 6.1.0
  Watchman: 4.9.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 3.1 AI-173.4819257

Packages: (wanted => installed)
  expo: ^28.0.0 => 28.0.0
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-28.0.0.tar.gz => 0.55.4

**Comment by JulianKingman** [comment]
Submitted a PR to fix: https://github.com/react-navigation/react-navigation/pull/4735

**Comment by brentvatne** [comment]
are you setting a background color with alpha or what exactly leads to this being a problem?

**Comment by brentvatne** [comment]
fixed in 2.9.0
