### ISSUE TITLE
Stack Navigator not working when used with brownfield app

### ISSUE THREAD

**Issue by sarvabowmen** [react-navigation/react-navigation#4738]
## The issue tracker is reserved for bug reports only.

If you have a question, feature request, or an idea for improving the library or its related tools, please try one of the following resources:

- [Read the documentation](https://reactnavigation.org/)
- [Post an issue to the website repository if you'd like to see a documentation change](http://github.com/react-navigation/website)
- [Post a feature request to Canny](https://react-navigation.canny.io/feature-requests)
- [Write a RFC if you have ideas for how to implement a feature request](https://github.com/react-navigation/rfcs)
- [Get help on Discord chat (#react-navigation on Reactiflux)](https://discord.gg/4xEK3nD) or [on StackOverflow](https://stackoverflow.com/questions/tagged/react-navigation)
- Search for your issue - it may have already been answered or even fixed in the development branch. However, if you find that an old, closed issue still persists in the latest version, you should open a new issue.

Bugs with react-navigation must be reproducible *without any external libraries that operate on it*. This means that if you are attempting to use Redux or MobX with it and you think you have found a bug, you must be able to reproduce it without Redux or MobX in this report. Redux related issues belong in [react-navigation-redux-helpers](https://github.com/react-navigation/react-navigation-redux-helpers), and we do not have any first-class integration with MobX at the moment.

---

### Current Behavior
I am working on integrating react-native to my existing android app (Brownfield App), For navigating between two React Native screens i am trying to use ReactNavigation as js based solution is fine for me.

- What code are you running and what is happening?
 **routes.js**
`
export const Root = createStackNavigator({
    Home: {
      screen: BaseApp,
      navigationOptions: {
        title: 'Dashboard',
      },
    },
    Detail: {
        screen:TopicDetail,
        navigationOptions: {
            title: 'Topic1',
          },
    }
    },{
        initialRouteName: 'Home',
      });`

**index.js**
`import React from 'react';
import {AppRegistry, Text, View, Navigator} from 'react-native';
import {styles} from './app/styles/theme';
import { Provider } from 'react-redux'
import configureStore from './configureStore'
import { setToken } from './app/redux/actions/actions';
import NavigationService from './app/config/navigationService';
import {Root} from './app/config/routes';

const store = configureStore();

class Appextends React.Component {

    render() {
      const {token} = this.props;
      store.dispatch(setToken(token));
        return(
        <Provider store={store}>
            <View style={styles.container}>
            <Root  ref={navigatorRef => {
          NavigationService.setTopLevelNavigator(navigatorRef);
        }} />
             {/* <BaseApp  />   */}
            </View>
        </Provider>
    )
}
}

export default App;

AppRegistry.registerComponent('ReactNavigation', () => App);`

**BaseApp.js**

````
class BaseApp extends React.Component {
  constructor(props){
    super(props);
  }
 
componentDidMount() {
}

  onPress=()=> {
      console.log('clicked')
      NavigationService.navigate('TopicDetail');
    }

  render() {
      return(
          <View>
  <TouchableOpacity key={u.id} onPress={ ()=> this.onPress()}><Text> This is dashboard </Text></TouchableOpacity >
          </View>
      )                            
  }
}
`

**TopicDetail.js**
`class TopicDetail extends Component {

    constructor(props){
        super(props);
    }

    render(){
        <View><Text>You are in detail page</Text></View>
    }

}

export default TopicDetail;
````
 
### Expected Behavior

When clicking on the button in the base app page i am calling      NavigationService.navigate('TopicDetail'); but the TopicDetailComponent is not rendered in my android emulator

Please let me know if you need more details or info on this, looking for help from you guys to findout what is wrong...

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
