### ISSUE TITLE
Props inactiveBackgroundColor & activeBackgroundColor for createMaterialTopTabNavigator 

### ISSUE THREAD

**Issue by Donhv** [react-navigation/react-navigation#4739]
Hello everyone! I have question about createMaterialTopTabNavigator .
have it support change background color when tab focused or unFocused?
If it not support how i can make it by tabBarComponent?
thanks all!
My Environment:
react-navigation | ^2.6.2
react-native | ~0.55.4
node |  
npm

**Comment by brentvatne** [comment]
hi there! this is a question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.
