### ISSUE TITLE
Opening Drawer from a Stack navigator nested in a Drawer navigator

### ISSUE THREAD

**Issue by lanzosuarez** [react-navigation/react-navigation#4740]
### Current Behavior

``` const HomeStackNavigator = createStackNavigator(
  {
    Courses: { screen: Courses },
    SpecificCourse: { screen: SpecificCourse },
    ViewSchedule: { screen: ViewSchedule }
  },
  {
    initialRouteName: "Courses",
    headerMode: "none"
  }
);

const MainDrawerNavigator = createDrawerNavigator(
  {
    Home: HomeScreen
  },
  {
    contentComponent: CustomDrawerComponent,
    drawerWidth: width * 0.6,
    drawerOpenRoute: "DrawerOpen",
    drawerCloseRoute: "DrawerClose",
    drawerToggleRoute: "DrawerToggle"
  }
);

```
I tried using the ff  inside the Courses component that's in the HomeStackNavigator but nothing worked
    - this.props.navigation.dispatch(DrawerActions.openDrawer()); //no error but drawer didnt open
    - this.props.navigation.openDrawer() // error: openDrawer is undefined
    - this.props.navigation.navigate("DrawerOpen"); //no error but drawer didnt open

### Expected Behavior

Drawer should open

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | "^2.6.2"
| react-native     | "~0.55.2"
| node             | "8.9.0"
| npm or yarn      | npm "6.1.0" , yarn 1.3.2

**Comment by lanzosuarez** [comment]
Closing. i followed this https://github.com/react-navigation/react-navigation/issues/1979

**Comment by rebirthtobi** [comment]
@lanzosuarez please how were you able to solve this as my drawer is not opening but only showing a dark overlay without the white background and content

**Comment by choo737** [comment]
Same issue here.. only dark overlay like this
![image](https://user-images.githubusercontent.com/23527099/46848062-4d878a00-ce1a-11e8-8bdd-17aa3a55cf5e.png)

Any of you found the solution?

**Comment by choo737** [comment]
@rebirthtobi did you managed to resolve your issue?

> @lanzosuarez please how were you able to solve this as my drawer is not opening but only showing a dark overlay without the white background and content

**Comment by rebirthtobi** [comment]
@choo737 i have to construct my navigation in another way.
