### ISSUE TITLE
2.9.0 Not Published to npm

### ISSUE THREAD

**Issue by jstheoriginal** [react-navigation/react-navigation#4742]
### Current Behavior

https://www.npmjs.com/package/react-navigation shows that the latest release is 2.8.0, not 2.9.0 (published 2 days ago).

### Expected Behavior

It should show 2.9.0 by now.

### How to reproduce

N/A

### Your Environment

yarn

**Comment by brentvatne** [comment]
my mistake, it's published now, thanks
