### ISSUE TITLE
Bundling error: Unable to resolve module ./navigators/createDrawerNavigator

### ISSUE THREAD

**Issue by joshua-turner** [react-navigation/react-navigation#4745]
### Current Behavior

Bundling error

```
error: bundling failed: Error: Unable to resolve module `./navigators/createDrawerNavigator` from `{projdir}/node_modules/react-navigation/src/react-navigation.js`: The module `./navigators/createDrawerNavigator` could not be found from `{projdir}/node_modules/react-navigation/src/react-navigation.js`. Indeed, none of these files exist:

  * `{projdir}/node_modules/react-navigation/src/navigators/createDrawerNavigator(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json)`
  * `{projdir}/node_modules/react-navigation/src/navigators/createDrawerNavigator/index(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json)`
```

### Expected Behavior

-

### How to reproduce

This bundling error happens with both 2.9.0 and 2.8.0. After failing both I just reverted back to 2.3.0 to wait for a resolution to this.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.9.0 & 2.8.0
| react-native     | 0.56.0
| node             | 8.11.1
| yarn      | 1.7.0

**Comment by brentvatne** [comment]
it looks like you're trying to import that by module by path, you should instead just use the public export - `import { createDrawerNavigator } from 'react-navigation';` - we moved it out to a separate lib in 2.4.0 so you can't import by path anymore (it was never recommended to do so in the first place)

**Comment by joshua-turner** [comment]
I'm not - that was immediately what I searched for in the project.

I'm not using `createDrawerNavigator` anywhere, nor am I importing it at any time.

**Comment by brentvatne** [comment]
well you're the only one encountering this error it would seem, so please provide a way for us to reproduce it and i'll be happy to investigate! 

you might want to try clearing node_modules and reinstalling, including deleting npm-lock or yarn.lock

**Comment by brentvatne** [comment]
also for your reference, the code from the error you encountered above does not live in 2.8.0 or 2.9.0 at all: https://github.com/react-navigation/react-navigation/blob/9a82706fbafb5b4ddf312a256ff715cdc5280923/src/react-navigation.js#L37-L45

notice there is no `./navigators/createDrawerNavigator`

**Comment by joshua-turner** [comment]
You're right - when I reinstalled with yarn I didn't delete my yarn.lock file, such a stupid mistake.

I appreciate your time - sorry for the needless issue
