### ISSUE TITLE
Modification time of files in npm package

### ISSUE THREAD

**Issue by dbasedow** [react-navigation/react-navigation#4749]
### Current Behavior
If you install a version of react-navigation > 1.5.7 the files have a modified time of January 1st 1970. This prevents caches from being invalidated when updating the version.

WebStorm did not pick up the change and neither did the bundler. Even restarting the programs didn't work. Rebooting or running touch on the files worked.

### Expected Behavior
Different versions should have different timestamps.

### How to reproduce
Take a look at the tarballs: 
https://registry.npmjs.org/react-navigation/-/react-navigation-1.5.7.tgz -> has mtime set
https://registry.npmjs.org/react-navigation/-/react-navigation-1.5.8.tgz -> mtime is 0
...
https://registry.npmjs.org/react-navigation/-/react-navigation-2.9.0.tgz -> mtime is 0

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.2.4
| react-native     | 0.56
| node             | 8.9.4
| npm or yarn      | yarn

**Comment by brentvatne** [comment]
hi! maybe you can post this as a bug report to npm. we aren't doing anything fancy here, just `npm publish`. let me know what you find!
