### ISSUE TITLE
Navigating without navigation prop not working (site example)

### ISSUE THREAD

**Issue by vinipachecov** [react-navigation/react-navigation#4750]
Hi there, I've read recently that redux integration for navigation prop will be deprecated in the next releases and I've found the lib example for navigating outside the components without the navigation prop:
https://reactnavigation.org/docs/en/navigating-without-navigation-prop.html

While I was using the js debugger it was running fine but when I turned it off it just stopped working. Did anyone use this approach and got it working correctly?

My app
`import React from 'react';
import { Provider } from 'react-redux';
import { createStore, applyMiddleware } from 'redux';
import EStyleSheet from 'react-native-extended-stylesheet';
import ReduxThunk from 'redux-thunk';

import reducers from './reducers';
import AppNavigation from './Navigation';

EStyleSheet.build({  
  $lightbackground: '#F5FCFF',
  $fullblack: '#000',
  $primaryBlue: '#4F6D7A',
  $white: '#fff',
  $border: 'lightgray',
  $inputText: '#797979',
  $lightGray: '#F0F0F0',
  $headerBlue: '#3281de',
  $primaryGray: '#f6f6f6'
  // $outline: 1
});

const middlewares = [ReduxThunk];

class App extends React.Component {  
   
  render() {     
    const store = createStore(reducers, {}, applyMiddleware(...middlewares));
    return (          
      <Provider store={store}>  
        <AppNavigation />    
      </Provider>  
    );
  }    
}

export default App;
`

And the navigator component:
`import React from 'react';
import { bindActionCreators } from 'redux';
import { connect } from 'react-redux';
import NavigationService from './NavigationService';

import { ActionCreators } from '../Actions'; 

import AppNavigator from './RootNavigator';

// export const navReducer = createNavigationReducer(AppNavigator);

// export const reduxMiddleware = createReactNavigationReduxMiddleware(
//   'root',
//   state => state.navigation,
// );

// const App = reduxifyNavigator(AppNavigator, "root");
// const mapStateToPropsApp = (state) => ({
//   navigation: state.navigation
// });

// const AppWithNavigationState = connect(mapStateToPropsApp)(App);

class AppNavigation extends React.Component {
  render() {    
    return (
      <AppNavigator 
        ref={ref => NavigationService.setTopLevelNavigator(ref)        
        } 
      />
    );
  }
}    

const bindAction = dispatch => {
  return Object.assign({ dispatch }, bindActionCreators(ActionCreators, dispatch));   
};

const mapStateToProps = state => ({
  navigation: state.navigation
});  

export default connect(mapStateToProps, bindAction)(AppNavigation);
`

---

### Current Behavior
Not navigating to other screens, but only with the JS debugger turned on.

### Expected Behavior
To be able to navigate to other screens.

### How to reproduce
Create an app and add the NavigationService just like the tutorial to your component that has your routes (like the stackNavigator).

### Your Environment
react-native: 0.55.3
react-navigation: 2.5.3
node: 9.11.1
npm: 5.6.0

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!

**Comment by adamnator92** [comment]
Hi @brentvatne,
https://snack.expo.io/rkeByAQuQ here is the snack
i face this issues too, blank screen while i turn off the js debugger. can we reopen this issues?

**Comment by developercode1** [comment]
Hi @adamnator92,
 I am also facing this issue. Were you able to solve it?

**Comment by adamnator92** [comment]
@developercode1 update to the react-navigation@latest should be solve this issues

**Comment by brentvatne** [comment]
if someone can open a new issue and properly fill out template i'm happy to look
