### ISSUE TITLE
How to swipe horizontally between stackNavigator screens 

### ISSUE THREAD

**Issue by jackmatrix** [react-navigation/react-navigation#4751]
I'm trying to create a swipe navigation between different screens from a same `StackNavigator`

when i set `swipeEnabled:true` in `navigationOptions`, my app rather navigate between different Tabs. 

I'd rather want to navigate inside a same stack from `Screen A` to `Screen B` for example.

How can i do this trick ?

**Comment by brentvatne** [comment]
hi there! this is a question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.
