### ISSUE TITLE
uncompiled PNG file passed as argument. Must be compiled first into .flat file.. error: failed parsing overlays.

### ISSUE THREAD

**Issue by RameshSain** [react-navigation/react-navigation#4755]
**In android release build.** 
while creating release build in android.

Its really painful : - please help me to sort it out.

> 
all available solution is not working for me .

Using command line cd android && ./gradlew assembleRelease
mac os : 10.13.1
android studio :3.1.3
React-native : 0.55.3

**Comment by brentvatne** [comment]
https://github.com/react-navigation/react-navigation/issues/3097

**Comment by MiiNoe879** [comment]
But when I try with android.enableAapt2=false... I am getting following warnings

The option 'android.enableAapt2' is deprecated and should not be used anymore.
Use 'android.enableAapt2=true' to remove this warning.
It will be removed at the end of 2018..

And I can't execute the app as the debug mode with following error.

Failed to execute aapt

Could you please help me?

**Comment by MiiNoe879** [comment]
And when I try to build the signed apk - ./gradlew assembleRelease
I can build the apk with android.enableAapt2=false

But when install apk and execute it some features are not working
1.react native geolocation
2.https://www.npmjs.com/package/react-native-location-switch
And this is not working either and when I try enable location, app is always crushed

**Comment by ggdegreat** [comment]
`android.enableAapt2=false` only for a workaround and its not recommended. Should waiting for them to release an official fixed on this issue.

**Comment by NaleenDissanayake** [comment]
I'm also in trouble with that.

**Comment by jayfour000** [comment]
Why was this issue closed? It is still a blocking issue for me.

**Comment by NaleenDissanayake** [comment]
yes. This is the solution for this `android.enableAapt2=false`

**Comment by mekaVR** [comment]
is not a solution @NaleenDissanay but a circumvention of the problem. 
I have the same problem.

**Comment by NaleenDissanayake** [comment]
But it works however

**Comment by bearty** [comment]
Same problem.
`android.enableAapt2=false` helps, but build give thit message
```
Use 'android.enableAapt2=true' to remove this warning.
It will be removed at the end of 2018..
```
I think we need another solution

**Comment by jdegger** [comment]
@mekaVR what gradle version are you on?

**Comment by mekaVR** [comment]
hi @jdegger my solution posted 15 days ago is not stable. The only solution I found that works every day and delete in the node_modules the images that block the build, and remove the piece of code I posted earlier in android/build.gradle. 

**My gradle version** 
```
------------------------------------------------------------
Gradle 4.10
------------------------------------------------------------

Build time:   2018-08-27 18:35:06 UTC
Revision:     ee3751ed9f2034effc1f0072c2b2ee74b5dce67d

Kotlin DSL:   1.0-rc-3
Kotlin:       1.2.60
Groovy:       2.4.15
Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
JVM:          1.8.0_181 (Oracle Corporation 25.181-b13)
OS:           Linux 3.10.0-862.11.6.el7.x86_64 amd64
```
I hope this will help you

**Comment by mekaVR** [comment]
hi @motogod for my case i I had to delete images that did not have a @X prefix in react navigation and react-datepicker i follow the instruction of RameshSain upper. 

the path is indicated in the error message when you build

**Comment by motogod** [comment]
Hi @mekaVR . Thanks for respond, In my error:

`/Users/motogod19/ReactNativeTutorial/MovieToGo/android/app/build/intermediates/res/merged/release/drawable-xhdpi/node_modules_teaset_icons_success.png: error: uncompiled PNG file passed as argument. Must be compiled first into .flat file..
error: failed parsing overlays.
`

,I try to delete the folder `drawable-xhdpi` when I type `cd android && ./gradlew assembleRelease
` . It looks like the foler re-create and stills show the same error.

**Comment by mekaVR** [comment]
don't delete the folder juste img without prefix @x if I'm wrong the way is `node_modules/teaset/icons/success.png` no ? after deleting the image do not forget to delete where it is called in the code of the same module and do not forget to make a  `./gradlew clean`  before `./gradlew assembleRelease`

I hope I was able to help you

**Comment by motogod** [comment]
Thnkas @mekaVR , it's really helpful from your help.  Following your suggestion, I delete `node_modules/teaset/icons/success.png` then `./gradlew clean` and `./gradlew assembleRelease` (also comment the image code) that I can see the process has something different before, but it stills shows another image error. 

So  I try a lots of times to delete and gradlew. All I delete the images are `success.png` `smile.png` `stop.png` `info.png` `indicator.png` .

When the error comes to the image `node_modules_reactnavigationstack_dist_views_assets_backicon.png`, I can't find it from `node_modules/teaset/icons/`.  I stuck here now. Any idea? Thanks in advance.

**Comment by doomsower** [comment]
So the upstream issue https://github.com/facebook/react-native/issues/16906 seems to be [fixed](https://github.com/facebook/react-native/issues/16906#issuecomment-418927905), but it still doesn't work for me in RN0.57.2 without `android.enableAapt2=false`

**Comment by michaelknoch** [comment]
still facing this issue in rn 0.57.5

**Comment by GaneshSaiKumar** [comment]
@motogod 
this solution is working sometimes and failing some times
i'm using gradle 4.6
build tools 3.1.0
react-native 55.2

**Comment by motogod** [comment]
@GaneshSaiKumar 

If you fix the issue and meet the issue agian next time.

Make sure you do not type the command somthing like `react-native bundle --platform android --dev false --entry-file index.android.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res` before `./gradlew assembleRelease`

If you type the command that will cause the issue happen agian. I have encountered such a situation before.

Just type `./gradlew assembleRelease`.

Hope my response can helps.

My environment:
gradle 3.1.4
react-native 55.2

**Comment by policz** [comment]
Hello I'm also facing the similar issue, did anyone found the solution for the below issue

uncompiled PNG file passed as argument. Must be compiled first into .flat file..
error: failed parsing overlays.
FAILURE: Build failed with an exception.

**Comment by GaneshSaiKumar** [comment]
Thank you @motogod 

Is there a way to take off android.enableAapt2=false, since support for aapt version 1 is being removed by the end of 2018.

**Comment by motogod** [comment]
@GaneshSaiKumar Unfortunately, I'm looking for another solution too.

**Comment by GaneshSaiKumar** [comment]
@motogod, Following solution worked for me :+1:  try it out 
I've upgraded my react native to 57.7
react to 16.3.2
build tools gradle to 3.2.0
gradle to 4.6

> and removed all drawable* folders

`rm -rf android/app/src/main/res/drawable-*`

from gradle.properties **remove android.enableAapt2=false**

#use the following command to bundle assets:

`react-native bundle --platform android --dev false --entry-file index.android.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/build/intermediates/res/merged/release/`

now generate release apk using following command.
`cd android && ./gradlew assembleRelease && cd ..`

> **Note**: bundled assets folder in RN > 57 has changed to `android/app/build/intermediates/res/merged/release/`

**Comment by policz** [comment]
Hello @GaneshSaiKumar @motogod 

I Still have some issue with Android build, please check the attachment or the screen shot below
Actually i used to build my application a month ago, but all of sudden i'm facing issue(scrrenshot)
Can you please me out from this issue.
Hey @GaneshSaiKumar i have tried your solution but it didn't worked for me.

My application has following configuration:
react-native: 0.52.2
react: 16.2.0


<img width="1440" alt="screen shot 2019-01-09 at 2 17 23 pm 1" src="https://user-images.githubusercontent.com/6464037/50923070-09f0ec00-141a-11e9-8039-f799c2059f92.png">

**Comment by motogod** [comment]
@policz Try my EDIT My solution of 09-25-2018.

It may helps.

**Comment by GaneshSaiKumar** [comment]
@policz  sry for the late response.

I guess that you have to upgrade react native to 57+ to use my solution.

if you insist that you should be using RN 52 then @motogod 's solution is definitely one, that you can use.

by the way can you quote your build tools version and gradle version
