### ISSUE TITLE
React Navigation InitialRouteName with OneSignal Notification?

### ISSUE THREAD

**Issue by zxccvvv** [react-navigation/react-navigation#4760]
How to change the `initialRouteName` of `ReactNavigation tabBar` in-case the `onOpened` of OneSignal is triggered?

my routes look's like:
```
    const TabLoged= TabNavigator({
      Home: {
        screen: HomeStack,
      },
      MyInbox: {
        screen: MyInboxStack,
      },
    },{
      initialRouteName:'Home', //change the value if openResult.action.actionID === 'inbox' is true
      tabBarPosition: 'bottom',
      tabBarComponent: TabBarBottom,
      tabBarOptions: {
        //list Options
      },
    });

    export const Check = SwitchNavigator({
      Auth: Auth,
      AlreadyLogin : TabLoged,
      Login : Tab
    })
```
and on `App.js`:

```
onOpened(openResult) {
  console.log('openResult: ', openResult);
  if(openResult.action.actionID === 'inbox'){
    console.log("LIKED")
    //Using `this.props.navigation.navigate("MyInbox");` throwing an error undefined navigate
    //Here I want to handle the initialRouteName from 'Home' To 'MyInbox'
  } else{
    console.log("else")
  }
}

render() {
  console.disableYellowBox = true;
  return <Check />;
}
```

there's a way to change the `initialRouteName` like `<Check initialRouteName={true ? 'MyInbox' : 'Home'} />`

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^1.4.0
| react-native     | ^0.53.0
| node             | v8.9.1
| npm or yarn      | 5.6.0

**Comment by brentvatne** [comment]
you can't change the initial route name. you can navigate to another route though.

**Comment by ericvicenti** [comment]
It sounds like you want to do a navigation action to change the route rather than set the initial route, because the app is already open. I think this approach should work:

```
this.props.navigation.navigate("MyInbox");
```

But you say this is "throwing an error undefined navigate". That sounds like a bug.. can you send some example code for that error?

**Comment by brentvatne** [comment]
related: https://github.com/react-navigation/react-navigation.github.io/issues/79

@ericvicenti - he's using react-navigation@1.4.0 so probably not an actual bug anymore

**Comment by zxccvvv** [comment]
@ericvicenti @brentvatne 

I just thinking because the `react-navigation` is not imported on `App.js`, because I don't need it to routing on `App.js`,

so I just `import { Check } from './router/router';` to let `App.js` rendering `<Check/>` to let `router.js` handle which screen should rendering first time

Am I wrong that i'm not use `import { allneeded function  } from 'react-navigation';` in `App.js`?
