### ISSUE TITLE
[v2.9][Android] Collapse or shrink StackNavigator's header (navbar) when scrolling down inside of a nested MaterialTopTabNavigator's tab page.

### ISSUE THREAD

**Issue by lastminutegoals** [react-navigation/react-navigation#4764]
### Current Behavior

This is my current navigator structure:

    - RootNavigator (StackNavigator)
        - HomeNavigator (MaterialTopTabNavigator)
            - .... other navs here that are not relevant
        - SinglePageNavigator (MaterialTopTabNavigator)
            - Tab1.js
                - Custom Header.js component
            - Tab2.js
                - Custom Header.js component

I have 3 navigation files:

- HomeNavigator.js
- SinglePageNavigator.js
- RootNavigator.js

I import the first two inside of **RootNavigator.js** which is a StackNavigator.

_(Don't mind any small errors, this is just to illustrate my problem, **Expo snack example is provided below**)_

    import { createStackNavigator } from 'react-navigation';
    import SinglePageNavigator from './SinglePageNavigator';
    import HomePageNav from './Home';

    const RootNavigator = createStackNavigator(
      {
        HomePageNav: {
          screen: HomePageNav,
        },
        SinglePageNavigator: {
          screen: SinglePageNavigator,
        },
      },
    );

And inside of my **SinglePageNavigator.js** I have the following custom Header component defined:

    import Header from '../views/Single/Header';

    const SinglePageNavigator = createMaterialTopTabNavigator(
      {
        Stats: {
          screen: Tab1,
        },
        Info: {
          screen: Tab2,
        },
      },
    );

    SinglePageNavigator.navigationOptions = ({ navigation }) => {
      return {
        header: <Header navigation={navigation} />,
      };
    };

    export default SingleMatchNav;

Finally, the custom header component (**Header.js**)- nothing special about it, I want to put some content in there and it has a `height` property which I would like to modify dynamically when I scrolling  inside of **Tab1.js** or **Tab2.js** which are screens components of **SinglePageNavigator**:

    export default class HeaderSingle extends React.Component {
      render() {
        return (
          <View style={{ backgroundColor: '#212121', elevation: 0, height: 120, paddingTop: 20 }}>
            <Text style={{color:'#fff'}}>My Custom header component</Text>
            <TouchableOpacity onPress={() => this.props.navigation.goBack()}>
              <Text style={{ fontSize: 20, color: '#fff' }}>GO BACK</Text>
            </TouchableOpacity>
              <Text style={{ fontSize: 20, color: 'orange', paddingTop: 20}}>Some other stuff here</Text> 
          </View>
        );
      }
    }

My main problem comes from the fact that earlier threads on a similar topic like this one: 
[https://github.com/react-navigation/react-navigation/issues/480](https://github.com/react-navigation/react-navigation/issues/480) only cover examples for a single StackNavigator.

The one I have is a MaterialTopTabNavigator which is a child of a StackNavigator (Root). Additionally I want to use a custom Header component as I showed in the example above.

So how exactly do I make SinglePageNavigator and Header.js speak to one another? Or maybe my approach was incorrect? I have seen a lot of apps use this technique, it's quite popular, but it's not covered in the documentation yet.

### Expected Behavior

[This example is not my code, it's just a video recording of another app - I want to achieve the same result](https://gfycat.com/SpectacularHeftyGentoopenguin)

[Another example from around the web, this hides the navbar completely](https://i.stack.imgur.com/tW209.gif)

### How to reproduce

Inside of this expo snack I have created a third tab which is based on this reply from StackOverflow.com:

[https://stackoverflow.com/a/49109815/3258251](https://stackoverflow.com/a/49109815/3258251)

**[https://snack.expo.io/@dechovek/frisky-cereal](https://snack.expo.io/@dechovek/frisky-cereal)**

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.9.1
| react-native     | 0.55.2
| node             | 8.9.3
| npm or yarn      | 6.1.0

Thanks to anyone kind enough to help.

**Comment by brentvatne** [comment]
you can submit a feature request to https://react-navigation.canny.io/ - for now you need to implement this on your own as i explained in the other issue you opened

**Comment by benevbright** [comment]
Please checkout. 
https://github.com/benevbright/react-navigation-collapsible

**Comment by lastminutegoals** [comment]
Amazing, thanks a lot @benevbright this seems to do exactly what I'm looking for so I'm going to test it out next week.

**Comment by vaibhav5923** [comment]
@lastminutegoals  did u able to make like what u want...I also have same requirement in one of my project. can u help me out
