### ISSUE TITLE
(Sometimes) Nested Stack Navigator Resetting to first screen after pressing Home (Android) [Emulator

### ISSUE THREAD

**Issue by zxccvvv** [react-navigation/react-navigation#4765]
### Current Behavior

I have a nested Stack Screen inside tabBar, let say I'm in tabBar `C` which have screen A->B->C->D
when I'm on screen D(or any screen) and pressing `Home` (hardware button android), and reopen the app without `swipe` the `recent apps`, my route's resetting to the first render,

here's an example:
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/19633881/43199518-7877a8b0-903c-11e8-9b3b-1cb9c5a2f945.gif)

`routes.js` :
```
const TabLoged= TabNavigator({
      Home: {
        screen: HomeStack,
      },
      MyInbox: {
        screen: MyInboxStack,
      },
    },{
      tabBarPosition: 'bottom',
      tabBarComponent: TabBarBottom,
      tabBarOptions: {
        //list Options
      },
    });

    export const Check = SwitchNavigator({
      Auth: Auth,
      AlreadyLogin : TabLoged,
      Login : Tab
    })
```

`App.js`

```
{import}
class App extends Component {
  render() {
    console.disableYellowBox = true;
    return <Check />;
  }
}
```

### Expected Behavior

I want to keep the current screen show up even after pressing Home and re-open the apps

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^1.4.0
| react-native     | ^0.53.0

**Comment by zxccvvv** [comment]
Does the problem appears only for me?

**Comment by brentvatne** [comment]
you're using react-navigation 1.4.0, we don't take issues for this. react-navigation's latest version is 2.9.2. if you update and the problem persists then feel free to make another issue! thanks!

**Comment by zxccvvv** [comment]
So i assume the lower version of react navigation is "useless" to be used,

Thanks anyway

**Comment by brentvatne** [comment]
depends on how you interpret that. it's not supported, so if you consider that useless then yeah
