### ISSUE TITLE
[Question] Dynamic TabNavigator routes

### ISSUE THREAD

**Issue by pckz** [react-navigation/react-navigation#4767]
I have a TabNavigator (react-navigator) with 5 tabs. Mi intention is hide some tabs dynamically, depending of a parameter of the user mode.

I can recover the value of the parameter via redux (via compose, I can get the var just using user), but I don't know how to pass the param to the definition of first argument in the TabNavigator() function.

For example, I have this code:

```
const App = TabNavigator({
      Stack1: {screen: Stack1},
      Stack2: {screen: Stack2},
      Stack3: {screen: Stack3},
      Stack4: {screen: Stack4},
      Stack5: {screen: Stack5},
    },   {
    initialRouteName: 'Stack1',
```

And my intention is do something like:

```
const App = {user} => TabNavigator({
      Stack1: {screen: Stack1},
      ...((user.mode === 'traveler') ? { Stack2: {screen: Stack2}} : {} ),
      Stack3: {screen: Stack3},
      Stack4: {screen: Stack4},
      Stack5: {screen: Stack5},
    },   {
    initialRouteName: 'Stack1',
```
but it seems that I don't know how the syntax are

Thanks for help

PD: I don't know if additional to this I should have to do a refresh of TabNavigator

**Comment by souzamarcos** [comment]
First, update you react-navigation to 2.x version as possible.

Try to create TabNavigator for each user mode and put them inside a StackNavigator.
When you get the user mode you would to navigate to the specific TabNavigator screen of the user mode. So you can simulate "dynamic TabNavigator routes".

Read more about in https://reactnavigation.org/docs/en/limitations.html#dynamic-routes
