### ISSUE TITLE
Android physical button has a different outcome for nested drawer nav

### ISSUE THREAD

**Issue by kriskate** [react-navigation/react-navigation#4768]
Hello,

When having a nested Drawer Stack inside a regular Stack, physical android button behaves differently than header-backButton || swipe to back on ios; this happens if the screen you're on is not the first in a drawer.
We have this:
```
stackNavigator: { MainScreen, drawerNavigator: { Screen1, Screen2 } }
```
steps to reproduce:
```
MainScreen - Screen1 - openDrawer - Screen2 - back
|| MainScreen - Screen2
```
IOS - goBack() || swipe goes to MainScreen
Android - goBack() goes to screen MainScreen
Android - physical button back - goes to Screen1 

[:heart: snack](https://snack.expo.io/S1oXZUUNQ)

I actually prefer the goBack() / IOS functionality; not sure if it's how it's supposed to be though, if you're navigating through the drawer screens.

**Comment by ericvicenti** [comment]
I think this is a bug in drawer, so I've sent a fix here: https://github.com/react-navigation/react-navigation-drawer/pull/15

**Comment by kriskate** [comment]
Unfortunately, as I see in the above pull, the drawer being open is taken into account ``` && state.isDrawerOpen```.

This issue refers to the fact that if you press the physical back within a nested Drawerstack, regardless of the drawer being open or not, it takes you back to the previous screen in the Drawerstack (even if you have not accessed it), which is different from the functionality of ```this.props.navigation.goBack()```.

**Comment by kriskate** [comment]
I've upgraded reat-navigation-drawer and can confirm that this issue is not fixed

I've even manually removed ```&& state.isDrawerOpen``` just to see what comes out 😅
