### ISSUE TITLE
"Cannot read property 'routes' of undefined" when storing current route

### ISSUE THREAD

**Issue by peacechen** [react-navigation/react-navigation#4769]
### Current Behavior

I'm using react-navigation 2 *without* Redux integration.  There's a TabNavigator nested within a StackNavigator.  It's working properly until I try to save the current route in `onNavigationStateChange`.
> TypeError: Cannot read property 'routes' of undefined

```
  onNavigationStateChange(prevState, newState, action) {
    if (newState.routes[newState.index]) {
      this.props.setCurrentRoute({currentRoute: newState.routes[newState.index].routeName});
    }
  }

  render() {
    return (
      <MyStackNav
        ref={this.saveNavigator}
        onNavigationStateChange={this.onNavigationStateChange}
      >
      </MyStackNav>
    );
  }

//...

const mapDispatchToProps = dispatch => {
  return {
    setCurrentRoute: params => {
      dispatch(State.Actions.RouterState.setCurrentRoute(params))
    },
  }
```

While the stack navigator does not use Redux, I'm trying to save the current route in the app's own Redux store in the call `this.props.setCurrentRoute()`.

If anything touches Redux inside of `onNavigationStateChange()` or `saveNavigator()`, it throws the error "Cannot read property 'routes' of undefined".  But if I remove any Redux dispatches, it works fine. 

I'm using `connect` to update child component props with Redux state to better manage features such as management of server calls, UI layout, etc.  For example, orders may be added to the cart on one screen, which updates the cart icon in the header, then the order is submitted to the server only when the cart screen is navigated to.  The order service is an independent component because multiple screens can alter the cart.

### Expected Behavior

Screens should render with no error.

### How to reproduce

code sample above

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.6.2
| react-native     | 0.56
| node             | 9
| npm or yarn      | 4.5

**Comment by peacechen** [comment]
@brentvatne @ericvicenti 
Sorry to bother you guys, but I'm stumped and would be grateful for any insight into this.   Why would dispatching Redux inside `onNavigationStateChange` break react-navigation?

**Comment by brentvatne** [comment]
hi! sorry we don't provide support for redux. you can post questions about it here if you like: https://github.com/react-navigation/react-navigation-redux-helpers

**Comment by brentvatne** [comment]
oops read this wrong 😅

**Comment by brentvatne** [comment]
please create a repro of this on https://snack.expo.io and i'll look!

**Comment by peacechen** [comment]
Will do @brentvatne 

Is a github repo acceptable?  Creating a complex project on snack is painful.

**Comment by brentvatne** [comment]
@peacechen - i really don't want a "complex project" - this should be minimal and contain nothing extra. why is it painful? you can build it locally than just drag the files in ;O

**Comment by peacechen** [comment]
I'm making a minimal example, but it's more complex than a Hello World app setting up Redux actions & reducers, along with nested navigators.

I've not yet been able to repro it in as a stand-alone example.  Will continue adding pieces in.
