### ISSUE TITLE
Margin right on header right (button) missing

### ISSUE THREAD

**Issue by yooouuri** [react-navigation/react-navigation#4770]
## The issue tracker is reserved for bug reports only.

If you have a question, feature request, or an idea for improving the library or its related tools, please try one of the following resources:

- [Read the documentation](https://reactnavigation.org/)
- [Post an issue to the website repository if you'd like to see a documentation change](http://github.com/react-navigation/website)
- [Post a feature request to Canny](https://react-navigation.canny.io/feature-requests)
- [Write a RFC if you have ideas for how to implement a feature request](https://github.com/react-navigation/rfcs)
- [Get help on Discord chat (#react-navigation on Reactiflux)](https://discord.gg/4xEK3nD) or [on StackOverflow](https://stackoverflow.com/questions/tagged/react-navigation)
- Search for your issue - it may have already been answered or even fixed in the development branch. However, if you find that an old, closed issue still persists in the latest version, you should open a new issue.

Bugs with react-navigation must be reproducible *without any external libraries that operate on it*. This means that if you are attempting to use Redux or MobX with it and you think you have found a bug, you must be able to reproduce it without Redux or MobX in this report. Redux related issues belong in [react-navigation-redux-helpers](https://github.com/react-navigation/react-navigation-redux-helpers), and we do not have any first-class integration with MobX at the moment.

---

### Current Behavior

![screenshot_20180725-231302](https://user-images.githubusercontent.com/12934957/43228224-36b81fa2-9061-11e8-8e5d-6af280d8ee9d.jpg)

### Expected Behavior

There should be a margin right from the button.

### How to reproduce

Set a header right button:

```
static navigationOptions = ({ navigation }) => {
  return {
    headerTitle: 'Home',
    headerRight: (
      <Button
        onPress={navigation.getParam('signOut')}
        title="Bye"
      />
    ),
  };
};
```

I am debugging on a Oneplus 6 (Android 8.1.0).

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.9.2
| react-native     | 56.0
| node             | v8.11.3
| npm or yarn      | yarn

**Comment by brentvatne** [comment]
yeah you need to add it if you want it. we leave the styling up to you if you customize it. this might be helpful for you https://github.com/vonovak/react-navigation-header-buttons

**Comment by ReeceKenney** [comment]
Can you tell us _how_ to add it? I can't seem to find a way to add any sort of spacing between the buttons and the edge of the screen.

**Comment by jcerone-boom** [comment]
I'm seeing this issue as well - haven't yet found a way to add spacing. `marginRight` and `paddingRight` are not working.
