### ISSUE TITLE
Wrong position of global footer when used with react-navigation

### ISSUE THREAD

**Issue by fasci** [react-navigation/react-navigation#4771]
### Current Behavior

As I'm not quite sure if this is a bug or if I'm doing something wrong here, I also posted my problem as a question on [StackOverflow](https://stackoverflow.com/questions/51524352/wrong-position-of-global-footer-when-used-with-react-navigation).
I want to have a StackNavigator in a React Native app on top of a global footer to avoid having to add the footer to each and every stacked component. This is the code of my base App.js:

```
import React, { Component } from "react";
import { View, Text } from "react-native";
import { createStackNavigator } from "react-navigation";

class TestScreen extends Component {
  render() {
    return (
      <View style={{}}>
        <Text>
          Hello, WorldHello, WorldHello, WorldHello, WorldHello, WorldHello,
          WorldHello, WorldHello, WorldHello, WorldHello, WorldHello,
          WorldHello, WorldHello, WorldHello, WorldHello, WorldHello,
          WorldHello, WorldHello, WorldHello, WorldHello, WorldHello,
          ...
          WorldHello, WorldHello, WorldHello, WorldHello, WorldHello,
          WorldHello, WorldHello, WorldHello, WorldHello, WorldHello,
          WorldHello, WorldHello, WorldHello, WorldHello, WorldHello,
          WorldHello, WorldHello, WorldHello, WorldHello, World
        </Text>
      </View>
    );
  }
}

const Stack = createStackNavigator(
 {
   Test: { screen: TestScreen }
 },
 {}
);

class App extends Component {
  render() {
    return (
      <View>
        <View>
            <Stack />
        </View>
        <View style={{backgroundColor: 'orange', height: 50}}/>
      </View>
    );
  }
}

export default App;
```

### Expected Behavior

I expect the StackNavigator's content to be displayed on top, and the orange footer below.
However, this is the result:
![Actual result](https://i.stack.imgur.com/cO4qM.png)

If I don't use the stack navigator, but TestScreen directly, everything works fine as expected:

```
render() {
    return (
      <View>
        <View>
            <TestScreen />
        </View>
        <View style={{backgroundColor: 'orange', height: 50}}/>
      </View>
    );
  }
```

![Expected result](https://i.stack.imgur.com/6HNEy.png)

### Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.0.1
| react-native     | 0.55.4

In case that this is not a bug, sorry for the question here. However, any help is highly appreciated.

**Comment by brentvatne** [comment]
stack navigator is absolutely positioned, make the parent view have flex: 1.

**Comment by brentvatne** [comment]
example: https://snack.expo.io/S1KBY_DE7

**Comment by fasci** [comment]
Thank you, @brentvatne. Unfortunately, I forgot to mention that I'm trying to get this running in a browser, and not (only) natively. I already tried flex: 1 for the parent(s), without the expected result. But thank you anyway!
