### ISSUE TITLE
"/bin/sh: expo: command not found" when cloning the repo and running yarn start

### ISSUE THREAD

**Issue by besarthoxhaj** [react-navigation/react-navigation#4774]
### Current Behavior

Hello, I'm trying to run the NavigationPlayground from master in order to play a bit with react-navigation and understand how it works.

When cloning the repo and running `yarn start` it fails with an `/bin/sh: expo: command not found` error.

### Expected Behavior

I guess I would expect the simulator to fire up and run the example up

### How to reproduce

```
git clone git clone git@github.com:react-navigation/react-navigation.git
yarn install
cd examples/NavigationPlayground
yarn install
yarn start
```

This fails with:

```
yarn run v1.6.0
$ expo start
/bin/sh: expo: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | -
| react-native     | -
| node             | v9.11.1
| npm or yarn      | yarn 1.6.0

I'm trying to install expo manually and trying to run it that way.

**Comment by brentvatne** [comment]
`npm i -g expo-cli`

when we update this to expo sdk 29 shortly this will give a better error msg!
