### ISSUE TITLE
Huge MemoryLeak in StackNavigator , components / cards not removed from memory

### ISSUE THREAD

**Issue by ashutosh-akss** [react-navigation/react-navigation#4775]
There is huge memory leak in react-navigation StackNaigator.

### Current Behavior

Every Navigation is increasing memory, keeps reference to component ,Card , SceneView etc

I am using following code
```
import React from "react";
import {createStackNavigator} from "react-navigation"

import Login from "./Login";
import Details from "./Details";
import UsersList from "./UsersList";

const rootNavigation = createStackNavigator({
    Login:Login,
    Details:Details,
    UsersList:UsersList
});

export default rootNavigation;
```

### How to reproduce
Just navigate to any screen using "this.props.navigation.navigate("UsersList");" and come back, 
It creates a instance of UserList, Card, SceneView and never removes it

### Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.9.0
| react-native     | 0.56.0
| node             | 10.4.1
| npm or yarn      |  6.1.0
<img width="1147" alt="screen shot 2018-07-26 at 9 11 50 pm" src="https://user-images.githubusercontent.com/11007583/43273368-e361ad8c-9119-11e8-9bf8-6bcfc6d7843a.png">
<img width="1152" alt="screen shot 2018-07-26 at 9 17 34 pm" src="https://user-images.githubusercontent.com/11007583/43273370-e38a9fd0-9119-11e8-942b-6ee9bbba82e6.png">
<img width="1149" alt="screen shot 2018-07-26 at 9 17 54 pm" src="https://user-images.githubusercontent.com/11007583/43273371-e3b23342-9119-11e8-8123-699208ebb3c8.png">

**Comment by brentvatne** [comment]
try looking at old issues about this, we explain why this is expected behavior. notice how when you go back the screen is still there and with all of the state from before. this is not a memory leak.

**Comment by ashutosh-akss** [comment]
Hi @brentvatne  I believe this is a leak because navigator is creating new instances of passed component and not reusing existing , as you can see in screenshots UsersList is created 9 Times.

even if we navigate back there are 8 additional instances in memory with all props. this is crasing our app in every 30 mins. can you help me with any solution for this

Thanks

**Comment by ashutosh-akss** [comment]
Reason I am calling it as memory leak becasue every time you navigate it creates a new instance of the screen and keeps in memory. can you please reopen this issue.

**Comment by brentvatne** [comment]
> Reason I am calling it as memory leak becasue every time you navigate it creates a new instance of the screen and keeps in memory. can you please reopen this issue.

that's not a leak because that is needed in order for it to function as you expect. it would be a leak if you closed the screen and the components remained, but you still have the screen open, it's just in the background.
