### ISSUE TITLE
Static navigation options not passing props successfully

### ISSUE THREAD

**Issue by Adokiye** [react-navigation/react-navigation#4776]
Any help will go a great mile :), I started using react-navigation for my app, I have a child component as the header of my parent component, This child component contains a `<TextInput/>` I want to update the parent component on change of the child component's TextInput, normally passing down a function as the value of the props will work, But since I am using `static navigationOptions` to access the child component, that won't work, I have to set the navigation.params.state, I have done this, I have read through documentations, I looked through this link https://github.com/react-navigation/react-navigation/issues/147  But it always comes back with this error `undefined is not an object(evaluating 'params.update')`
Please how can I make this work and pass the function successfully to the `Box` component

**BOX COMPONENT**

    class Box extends React.Component {

    constructor(props) {
        super(props);
        this.state = {
            search: ""
        }
    }

    handleChange = (e) => {
        this.props.onUpdate(e.target.value);
        this.setState({search: e.target.value});
    }

    render() {
        return (
            <TextInput placeholder="Search for your herbs by name,type..." value={this.state.search}
                       onChange={this.handleChange}
                       underlineColorAndroid={'transparent'}
                       style={BackStyles.textBox}/> ); }}

**HOME COMPONENT**
    
     export default class Home extends React.Component {
    onUpdate = (val) => {
        this.setState({
            search: val
        });
        let db = SQLite.openDatabase({
            name: 'test.db',
            createFromLocation: "~Herbo.db",
            location: 'Library'
        }, this.openCB, this.errorCB);
        db.transaction((tx) => {
            tx.executeSql("SELECT * FROM data where name like '" + this.state.search + "' ", [], (tx, results) => {
                console.log("Query completed");
                var len = results.rows.length;
                for (let i = 0; i < len; i++) {
                    let row = results.rows.item(i);
                    this.setState(prevState => ({
                        record: [...prevState.record, row],
                        pressed: [...prevState.pressed, false]
                    }));
                    console.log(`Record: ${row.name}`);
                    //this.sleep(2);
                    //this.setState({record: row});
                }
                this.setState({loader: false})
            });
        });
    };
    static navigationOptions = ({navigation}) => {
        const {params} = navigation.state.params || {};
        return {
            headerTitle: <Box onUpdate={params.update}/>,
        };
        //   header:  null
    };

    componentDidMount() {
        this.navigation.setParams({
            update: this.props.onUpdate()
        })
    }

    constructor(props) {
        super(props);
        this.state = {
            record: [],
            header: null,
            loader: true,
            pressed: {},
            ar: [],
            search: ''
        };

        let db = SQLite.openDatabase({
            name: 'test.db',
            createFromLocation: "~Herbo.db",
            location: 'Library'
        }, this.openCB, this.errorCB);
        db.transaction((tx) => {
            tx.executeSql('SELECT * FROM data', [], (tx, results) => {
                console.log("Query completed");
                var len = results.rows.length;
                for (let i = 0; i < len; i++) {
                    let row = results.rows.item(i);
                    this.setState(prevState => ({
                        record: [...prevState.record, row],
                        pressed: [...prevState.pressed, false]
                    }));
                    console.log(`Record: ${row.name}`);
                    //this.sleep(2);
                    //this.setState({record: row});
                }
                this.setState({loader: false})
            });
        });
    }

    handlePressedIn = (i, value) => {

        if (this.state.ar.length > 0) {
            this.state.ar.map((value) => {
                this.setState(prevState => {
                    const pressed = {...prevState.pressed};
                    pressed[value] = false;
                    return {pressed};
                })
            });
        }
        this.setState(prevState => {
            if (!this.state.ar.includes(i)) {
                this.setState(prevState => ({
                    ar: [...prevState.ar, i]
                }));
            }
            const pressed = {...prevState.pressed};
            pressed[i] = !pressed[i];
            return {pressed};
        });
        this.props.navigation.navigate('Details', {
            itemId: i + 1,
            otherParam: value
        });
    };

    errorCB(err) {
        console.log("SQL Error: " + err);
    }

    successCB() {
        console.log("SQL executed fine");
    }

    openCB() {
        console.log("Database OPENED");
    }

    render() {
        const herbs = this.state.record.map((herb) =>
            <TouchableNativeFeedback onPress={() => this.handlePressedIn(herb.id - 1, herb.name)} key={herb.id}>
                <View style={this.state.pressed[herb.id - 1] ? BackStyles.herbBox : BackStyles.herb_box}>
                    <Image style={BackStyles.image} source={{uri: `${herb.name.replace(/ /g, '')}`}}/>
                    <View style={{flexDirection: 'column',}}><Text
                        style={this.state.pressed[herb.id - 1] ? BackStyles.header2 : BackStyles.header}>{herb.name}</Text>
                        <Text
                            style={this.state.pressed[herb.id - 1] ? BackStyles.sub2 : BackStyles.sub}>{herb.bot}</Text></View>
                </View></TouchableNativeFeedback>
        );
        const view = <ScrollView overScrollMode={'never'}>{herbs}</ScrollView>;
        return (
            <View style={BackStyles.main}>
                <View style={{flex: 1}}>
                    {
                        this.state.loader ?
                            <ActivityIndicator animating={this.state.loader} color='#28B564' size="large"
                                               style={BackStyles.activityIndicator}/> : <View>{view}</View>
    } </View></View> ); }}

**APP.js(Main Component)**

    import Splash from './components/Splash';
    import {createStackNavigator} from 'react-navigation';

    const RootStack = createStackNavigator(
    {
        Home: {
            screen: Home,
        },
        Details: {
            screen: Details,
        },
       },
       {
        initialRouteName: 'Home',
        navigationOptions: {
            headerStyle: {
                backgroundColor: '#fff',
            },
            headerTintColor: '#28B564',
            headerTitleStyle: {
                fontWeight: 'bold',
            },
        },
    }
    );
    export default class App extends Component {
    constructor(props) {
        super(props);
        this.state = {
            timePassed: false,
        };
    }

    render() {
        setTimeout(() => {
            this.setState({timePassed: true})
        }, 4000);
        if (!this.state.timePassed) {
            return <View style={{flex: 1}}>
                <StatusBar backgroundColor='#28B564' barStyle='light-content'/><Splash/></View>;
        } else {
            return (<View style={{flex: 1}}>
                    <StatusBar backgroundColor='#28B564' barStyle='light-content'/>
                    <RootStack/></View>
            );} }}

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!

**Comment by brentvatne** [comment]
also read https://reactnavigation.org/docs/en/navigation-options-resolution.html

**Comment by jimbol** [comment]
^ This link no longer works
