### ISSUE TITLE
Increase area of swipe back

### ISSUE THREAD

**Issue by NikoMontana** [react-navigation/react-navigation#4779]
How can I increase the area of the swiping back function? 
Because the area is actually very small and totally left on the screen, which is not very user friendly.

**Comment by NikoMontana** [comment]
Found a soultion in the [API Documentation](https://reactnavigation.org/docs/en/stack-navigator.html#gestureresponsedistance)

added this line of code to the navigationOptions: ` gestureResponseDistance: { horizontal: 300, vertical: 300 },`

**Comment by devjiro76** [comment]
@NikoMontana Did you really solved this with that options?
For me that option is not work.

```gestureResponseDistance: {
      horizontal: 25
    }
```
is working as same with

```
gestureResponseDistance: {
      horizontal: 300
    }
```
