### ISSUE TITLE
Transition on stack with / without header sometimes leaves empty space at top when going back

### ISSUE THREAD

**Issue by ragunaru** [react-navigation/react-navigation#4780]
I'm using basic stackNavigators and I'm having this buggy screen transition animation:

![kapture 2018-07-28 at 9 34 52](https://user-images.githubusercontent.com/795389/43354751-997a3140-9249-11e8-8e30-d0234bfe57ef.gif)

How do I fix this?

**Comment by brentvatne** [comment]
hi! as i'm sure you read in the issue template, we require a reproducible example - preferably minimal, complete and verifiable (https://stackoverflow.com/help/mcve). a github repo or [snack](https://snack.expo.io/) are a good way to share this.

**Comment by eriveltonelias** [comment]
Hi! 

as @brentvatne said, we require that you provide a runnable example. I'll close this, but if you still need help, please create a new issue following the issue template.
