### ISSUE TITLE
Setting custom (dynamic) header for TabNavigator doesn't work anymore

### ISSUE THREAD

**Issue by greenais** [react-navigation/react-navigation#4782]
### Current Behavior
Setting custom header for tab screen like it was before (and as it's described in current docs):

```
static navigationOptions = ({navigation})=> {
 //...some assignments here   
 let title = t.week.yesterday + ', ' + dateShort;
    
    return {
      headerTitle: <Header title={title}/>,
      headerLeft: <Menu />,
     }
  }

```
doesn't work for tab screens anymore - header doesn't show up at all.
In "react-navigation": "1.5.8" (from which I recently upgraded) it worked.

### Expected Behavior
Dynamic header setting works for TabNavigator

### Your Environment
"react-native": "0.55.4"
"react-navigation": "2.9.3"

Does this mean that in the most recent react-navigation version there is no way to set custom header for TabNavigator anymore? 
For StackNavigator it works.
I doublechecked across react-navigation versions - it's broken since 2.0.0 major release.

**Comment by brentvatne** [comment]
https://reactnavigation.org/docs/en/navigation-options-resolution.html

**Comment by greenais** [comment]
Probably your code example could be included in docs for more clarity:
https://github.com/react-navigation/react-navigation/issues/4120
Thanks.
