### ISSUE TITLE
Performance issues and jumpy animations on Android when using setParams to pass Animated Value from one component to another.

### ISSUE THREAD

**Issue by lastminutegoals** [react-navigation/react-navigation#4786]
Please help me out, I've been stuck with this problem for the last 4-5 days.

The problem: **[https://gfycat.com/CelebratedVapidBadger](https://gfycat.com/CelebratedVapidBadger)**

This is my **MainTab1.js** component which holds the `ScrollView` with the `onScroll`. I am using `setParams` in `componentWillMount` and I access those in my Header.js file.

    const HEADER_MAX_HEIGHT = 150;
    const HEADER_MIN_HEIGHT = 50;
    const HEADER_SCROLL_DISTANCE = HEADER_MAX_HEIGHT - HEADER_MIN_HEIGHT;

    export default class MatchInfo extends React.Component {
        state = {
          animatedValue: new Animated.Value(0),
        }

        componentWillMount() {
          this.props.navigation.setParams({
            headerHeight: this.state.animatedValue.interpolate({
              inputRange: [0, HEADER_SCROLL_DISTANCE],
              outputRange: [HEADER_MAX_HEIGHT, HEADER_MIN_HEIGHT],
              extrapolate: 'clamp',
            }),
          });
        }

        render() {
          return (
            <ScrollView
              scrollEventThrottle={16}
              onScroll={Animated.event(
                [{ nativeEvent: { contentOffset: { y: this.state.animatedValue } } }],
                { useNativeDriver: false },
              )}
            >
              <Text style={{ fontSize: 20, textAlign: 'center', paddingVertical: 500 }}>MatchInfoTab</Text>
              <Text style={{ fontSize: 20, textAlign: 'center', paddingVertical: 500 }}>MatchInfoTab</Text>
            </ScrollView>
          );
        }
    }

This is my custom **Header.js**:

    export default class Header extends React.Component {
      render() {
        return (
          <Animated.View style={{
            backgroundColor: 'orange',
            elevation: 0,
            height: this.props.navigation.state.routes[1].params.headerHeight,
          }}
          >
            <TouchableOpacity onPress={() => this.props.navigation.goBack()}>
              <Text style={{ fontFamily: 'materialdesignicons', fontSize: 20, color: '#000' }}>&#xf04d;</Text>
            </TouchableOpacity>
          </Animated.View>
        );
      }
    }

Finally, this is my Navigators config, it's a materialTopTabsNavigator nested inside a stackNavigator:

    const SingleMatchNav = createMaterialTopTabNavigator(
      {
        Stats: {
          screen: MainTab2.js,
        },
        Info: {
          screen: MainTab1.js,
        },
      },
      {
        initialRouteName: 'Info',
        scrollEnabled: true,
        tabBarOptions: {
          style: {
            backgroundColor: '#212121',
            paddingBottom: 8,
          },
        },
      },
    );

    SingleMatchNav.navigationOptions = ({ navigation }) => {
      return {
        header: <Header navigation={navigation} />,
      };
    };

    const RootNavigator = createStackNavigator(
      {
        SingleMatchNav: {
          screen: SingleMatchNav,
        },
      },
    );

I don't know why and I can't find a workaround for this, but the animation when scrolling down is stuttering/jumping as if is constantly missing frames.

When I set ` useNativeDriver: true` to true inside of the `Animated.event` it becomes really smooth and the problem goes away, but that has it's limitations and I can no longer use the `height` property because useNativeDriver doesn't support that, only things like `opacity` or `transformY/X/Z` etc.

So the only option is to set `translateY`, but that way the top tabs no longer go up when I scroll the ScrollView, they only seem to respect the height property.

[https://gfycat.com/AcclaimedSophisticatedGander](https://gfycat.com/AcclaimedSophisticatedGander)

Is there any workaround for all of this? React-navigation is quite popular, I believe there should be some more easily understandable tutorial or example available on how to achieve this functionality, it's quite common even the Google play store uses it - [https://i.stack.imgur.com/tW209.gif](https://i.stack.imgur.com/tW209.gif) but I'm pretty much stuck with this for the last few days and I can't figure it out.

| software         | version
| ---------------- | -------
| react-navigation | 2.9.1
| react-native     | 0.55.2

EDIT: I forgot to mention that clearing all console logs, disabling dev mode or running this on a real device doesn't really seem to improve the performance, the problems still persists.

**Comment by brentvatne** [comment]
we don't provide a solution for this currently. i agree it would be nice to have. this is more of a feature request though.

a hint for how you could tackle this better is to create your own navigator (see docs) and follow this guide for how to implement the view https://medium.com/appandflow/react-native-scrollview-animated-header-10a18cb9469e

**Comment by Albert0405** [comment]
@lastminutegoals  Did you fix this already?

**Comment by lastminutegoals** [comment]
> 
> 
> @lastminutegoals Did you fix this already?
> 
> someone created a lib similar to this unfortunately the `Jumpy Bug` still exist on tabs
> `https://github.com/benevbright/react-navigation-collapsible`

No, I gave up on this library for now, it's just too much stuff going on that I don't like. Using react-native-easy-router for now.

It's worth mentioning that I took a different approach to my app, but you can take a look at this reddit thread from a few months ago (the comment at the end of the comment chain):

https://www.reddit.com/r/reactnative/comments/92x9zc/performance_issues_and_jumpy_animations_on/e3a0poy/

https://www.reddit.com/r/reactnative/comments/92x9zc/performance_issues_and_jumpy_animations_on/e3sil2v/
