### ISSUE TITLE
Unhandled JS Exception: TypeError: TypeError: Cannot read property 'bind' of undefined

### ISSUE THREAD

**Issue by BarryYan** [react-navigation/react-navigation#4788]
### Current Behavior
```js
Unhandled JS Exception: TypeError: TypeError: Cannot read property 'bind' of undefined

This error is located at:
    in AnimatedComponent (at StackViewCard.js:12)
    in Card (at createPointerEventsContainer.js:28)
    in Container (at StackViewLayout.js:612)
    in RCTView (at View.js:43)
    in RCTView (at View.js:43)
    in StackViewLayout (at withOrientation.js:30)
    in withOrientation (at StackView.js:63)
    in RCTView (at View.js:43)
    in Transitioner (at StackView.js:21)
    in StackView (at createNavigator.js:59)
    in Navigator (at createKeyboardAwareNavigator.js:11)
    in KeyboardAwareNavigator (at createNavigationContainer.js:376)
    in NavigationContainer (at reduxify-navigator.js:63)
    in NavigatorReduxWrapper (at dva-rn.js:56)
    in Router (created by Connect(Router))
    in Connect(Router) (at dva-rn.js:90)
    in Provider (at dva-rn.js:89)
    in Unknown (at renderApplication.js:32)
    in RCTView (at View.js:43)
    in RCTView (at View.js:43)
    in AppContainer (at renderApplication.js:31)

This error is located at:
    in NavigationContainer (at reduxify-navigator.js:63)
    in NavigatorReduxWrapper (at dva-rn.js:56)
    in Router (created by Connect(Router))
    in Connect(Router) (at dva-rn.js:90)
    in Provider (at dva-rn.js:89)
    in Unknown (at renderApplication.js:32)
    in RCTView (at View.js:43)
    in RCTView (at View.js:43)
    in AppContainer (at renderApplication.js:31)
```

My project: [https://github.com/BarryYan/musicApp](https://github.com/BarryYan/musicApp)

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.9.3
| react-native     | 0.56.0
| node             | 10.0.0
| npm or yarn      | 6.0.0

**Comment by brentvatne** [comment]
how does one reproduce this using your app?

**Comment by BarryYan** [comment]
@brentvatne I'm sorry.
I had add README.md file, you can see usage.
Just install `dependencies` and `devDependencies`, then run `npm run ios`, you will see the error info.

**Comment by ericvicenti** [comment]
I see your example app uses redux:

https://github.com/BarryYan/musicApp/blob/master/app/utils/dva-rn.js

It looks like your issue is something to do with the redux helper. Can you post the issue in the appropriate repo?

https://github.com/react-navigation/react-navigation-redux-helpers

If you can find a way to reproduce this error with just react-navigation, please post that example code in a new issue. Thanks!

**Comment by ixre** [comment]
I happend the same problem
