### ISSUE TITLE
Opening a screen in an outside stack navigator results in a flash of the initial screen in the stack

### ISSUE THREAD

**Issue by SvetlinStaev** [react-navigation/react-navigation#4790]
### Current Behavior

I have a main tab navigator which carries 5 tabs. In each tab I have placed stack navigators. In one of the stack navigator I am trying to navigate to a screen of the stack in another tab which is not the initial screen of the stack. It navigates fine but it flashes through the initial screen of the stack and then goes to the requested screen thus creating a back button behavior to the initial screen of the stack.

Example:

MainTabNavigator
  - Tab Home with HomeStackNavigator
     - HomeScreen
     - PrivacyPolicyScreen
     - UserAgreementScreen
 - Tab Register with RegistrationStackNavigator
    - RegistrationScreen
  ....

A call from the RegistrationScreen to the UserAgreementScreen goes through the HomeScreen. Back button on the top left brings back the user to the HomeScreen rather than the RegistrationScreen

### Expected Behavior

The screen of the stack should be displayed without a flash of the initial screen of the stack and creating a back button to that initial screen. Since the call is from outside the stack, the back button should not be displayed or be present to bring back to the caller which is in a different stack.

### How to reproduce
I have created a simple reproducer at https://github.com/SvetlinStaev/react-navigation.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.9.3
| react-native     | 0.55.4
| node             | 10.6
| npm or yarn      | 1.7

**Comment by rumbogs** [comment]
As a workaround, I’m adding the same screen in both the stacks, and just calling navigate on the specific version based on the current stack.

**Comment by brentvatne** [comment]
@tonmanayo - using react-native-screens?

**Comment by tonmanayo** [comment]
@brentvatne No, let me try using react-native-screens and see if there is a difference, I actually just noticed it's worse with v3 probably why we didn't notice before upgrading

**Comment by tonmanayo** [comment]
@brentvatne same problem using react-native-screens

**Comment by tonmanayo** [comment]
@brentvatne  soooo I found my bug, we have our own custom headers, so in all our stacks we disable headermode. When I enable headermode I do not get this jump.

**Comment by sonaye** [comment]
Not sure if this is helpful or not, but it fixed all of my flickering/flash issues `3.0.8`.

```js
cardShadowEnabled: false,
cardStyle: {
  backgroundColor: 'rgba(0, 0, 0, 0)',
},
transitionConfig() {
  return {
    containerStyle: {
      backgroundColor: 'rgba(0, 0, 0, 0)',
    },
    transitionSpec: {
      // For an instant transition
      // duration: 0,
      // timing: Animated.timing,
      useNativeDriver: true,
    },
  }
},
```

**Comment by SvetlinStaev** [comment]
@sonaye, where do you add that config - in the target stack navigator or the source one, or both? Does this workaround has any negative effects on the transition or it works seamlessly?

**Comment by sonaye** [comment]
@SvetlinStaev In the `createStackNavigator` config object. I saw/see no negative effects, transitions look great.

**Comment by sonaye** [comment]
Follow up to my proposed fix above, it seems that the flickering is gone only when using `duration: 0`, changing it to 400 ms for example brings the flickering back.

> we have our own custom headers, so in all our stacks we disable headermode. When I enable headermode I do not get this jump. So the issue would be that, the drawer is showing in front animation when headermode: 'none' and only effects IOS

Same here, custom headers with `header: null`.

**Comment by FelipeGatti** [comment]
@SvetlinStaev Were you able to fix the flickering ? 
I've tried the @sonaye fix, but it didn't work.
I am experiencing a flicker like that https://github.com/react-navigation/react-navigation/issues/4790#issuecomment-442345865
But mine is flickering in Android too and setting all the stacks to have a headerMode does not fix the issue.

Currently i have a Stack navigator that creates the Login Page and the Drawer Navigator wich is composed of multiples Stack navigators.

**Comment by FelipeGatti** [comment]
Oh, my dependencies are:

  "dependencies": {
    "native-base": "^2.13.8",
    "react": "16.8.6",
    "react-native": "0.60.5",
    "react-native-gesture-handler": "^1.4.1",
    "react-native-reanimated": "^1.3.0",
    "react-native-screens": "^1.0.0-alpha.23",
    "react-native-splash-screen": "^3.2.0",
    "react-native-vector-icons": "^6.6.0",
    "react-navigation": "^4.0.10",
    "react-navigation-drawer": "^2.2.2",
    "react-navigation-stack": "^1.9.1"
  }

**Comment by FelipeGatti** [comment]
![ezgif com-gif-maker](https://user-images.githubusercontent.com/2623428/65980682-0260ef80-e44e-11e9-91b9-2c3519945a51.gif)

**Comment by SvetlinStaev** [comment]
Unfortunately I was not able to solve it and I had to duplicate the screens in each navigator to make it work and it does the job.
