### ISSUE TITLE
How to update all Tabnavitor'tabs in another screen?

### ISSUE THREAD

**Issue by jinzunyue** [react-navigation/react-navigation#4792]
I want to achieve dynamic language switching,so i get this question.

const getTitle = (navigation, name) => {
  switch (name) {
    case "OfferScreen":
      return Strings.t(AppMessage.home);
    case "OrderScreen":
      return Strings.t(AppMessage.order);
    case "ProfileScreen":
      return Strings.t(AppMessage.my);
  }
};
const AppNavigation = TabNavigator({
  OfferScreen: {
    screen: OfferScreen,
    navigationOptions: (navigation) => ({
      title: getTitle(navigation, "OfferScreen"),
      tabBarIcon: (config: any) => (
        <Image
          resizeMode="contain"
          source={Images.home}
          style={[styles.icon, {tintColor: config.tintColor}]}
        />
      ),
    })
  },
  OrderScreen: {
    screen: OrderScreen,
    navigationOptions: (navigation) => ({
      title: getTitle(navigation, "OrderScreen"),
      tabBarIcon: (config: any) => (
        <Image
          resizeMode="contain"
          source={Images.account}
          style={[styles.icon, {tintColor: config.tintColor}]}
        />
      ),
    })
  }
})
const StackNavigation = StackNavigator({
    Root: {
      screen: HelloPage,
    },
    AppNavigation: {
      screen: AppNavigation,      }
    },
    Set: {
      screen: SetScreen,
    }
})
Question:
	How can make "AppNavigation" to render again to change tab's title in SetScreen?

with verion 2.0.1
I send a event with DeviceEventEmitter in SetScreen when language changed.The OrderScreen listeners the event, do "this.props.navigation.setParams({title: ""});" when listeners then event.Then then OrderScreen's title and OfferScreen's title changes.

Recently i update to version 2.9.3,then i saddly found it doesn't works.Is there anyone who can help me ?

**Comment by vonovak** [comment]
hi, sorry you're having a problem, but your issue seems to be a usage question rather than a bug report. For usage questions, please refer to stackoverflow. If you believe there is a problem with `setParams`, please create a new issue and include a runnable reproduction. Thanks.
