### ISSUE TITLE
navigation.pop and navigation.push not working with drawer navigation

### ISSUE THREAD

**Issue by naiduprakash** [react-navigation/react-navigation#4793]
Whenever i used `navigation.push('ScreenName');` is not  working for **DrawerNavigator** 
while same code is working when i used  **StackNavigator**

**Example** 
```
// Manifest of possible screens
const AppDrawerNavigation = createDrawerNavigator({
  HomeScreen: { screen: HomeScreen },
  MenuScreen: { screen: MenuScreen },
},{
  initialRouteName: 'HomeScreen',
})
```
whenever i used  `navigation.push('MenuScreen');` inside the HomeScreen component its not working and event no error in console.
But if i used **createStackNavigator** instead of **createDrawerNavigator** it works.

**Comment by vonovak** [comment]
hi! Thanks for reporting, this is expected behavior, as documented here https://reactnavigation.org/docs/en/navigation-prop.html.

**Comment by Just01** [comment]
@vonovak this is not an answer)) pop still not working)

**Comment by pistou** [comment]
So what if we **actually want to** push from a Drawer?
Any hint would've been appreciated.

**Comment by bonbonio** [comment]
I am having the same issue, my DrawerStack passes its properties down but the .push property is not available inside the component.

```
  contentComponent: props => {
    return (<AuthDrawer {...props} />);   
  },
```

I want to use this.props.navigation.push() inside AuthDrawer - how can I do this?

**Comment by Just01** [comment]
@pistou  and @bonbonio and @naiduprakash 

DrawerNavigation can't do it, because it's simply do not have STACK of screens inside...so...
All you must to do it's just WRAP StackNavigation in DrawerNavigation.

```javascript
const Stack = StackNavigator({
  logo: {
    screen: Logo,
  },
  main: {
    screen: Main,
  },
})



const AppNavigator = DrawerNavigator({
  stack: {
    screen: Stack,
},
})
```

Here is the nice article that explains all:
https://medium.com/async-la/react-navigation-stacks-tabs-and-drawers-oh-my-92edd606e4db

Your welcome ^_^

**Comment by bonbonio** [comment]
It just seems a very messy workaround rather than a solution, my DrawerStack has drawerLabels and contentComponent will these work when the drawerStack becomes a stack which is then embedded in a DrawerStack (if I understand the above you mean wrap a stack around a Drawer). @Just01 

Thanks for your help/clarification.

**Comment by Just01** [comment]
@bonbonio no it's not. DrawerNavigation is NOT A STACK, it doesn't have any screens inside, so it can't push or pop. Logic? :)
I gave you a good article on medium, just read it.

and no, wrap DRAWER around STACK, as on example above.

**Comment by pistou** [comment]
@Just01 I apologize, but both your solution and article are off-topic.
With your solution, the Drawer will have only one link, `stack`, in which we could push `logo` or `main` ; the drawer won't display `logo` or `main` itself - and won't be able to push them as this feature is not available (yet?).

If you want a clearer insight of what I wanted to achieve, just take a look at the Twitter App (Android version at least):
- There is a DrawerNavigator, that pushes pages
- There is a BottomTabNavigator, with each Tab being able to push pages (StackNavigator)

**As it, you simply can't achieve this with react-navigation.**
I'll try to create a dummy app with a super hacky way of doing it later in the day.

**Comment by bonbonio** [comment]
@pistou you mean putting things in CAPS didn't make it correct?

Please do share any solution you find, as like yourself after reading the article I did not deem it a solution, and like yourself I understand that the Drawer is not a stack, but there should perhaps be a global way to make a view transition to a specific screen always, navigate works, so surely to extend the functionality to a push within the same confines might make sense (or atleast for our use case).

**Comment by pistou** [comment]
@bonbonio @naiduprakash You can find an example of what I did on [snack.expo.io](https://snack.expo.io/@pye/ZXhhbX)
*Sorry there is no style, it was just a fast example*

The routes are _mainly_ stored in `/components/Routes.js`
What I did is making a `StackNavigator` with my `DrawerNavigator` in it, aswell as the screen that the `Drawer` will push.
I then did a **custom Drawer component** (see `/components/Drawer`) and created the actual menu directly in the component (`sideMenu` is my array of available routes).

One issue though: when you `goBack()` from a pushed screen, the drawer is still open. I tried to add `this.props.navigation.closeDrawer()` in the `openScreen()` function, but it breaks everything.
I believe that `closeDrawer` pushes some state after the animation is done or something like that, and it look likes it breaks the stack.

**Remember that I'm really not sure about this. It doesn't look that right, but it seems to work well enough.**

**Comment by ammoradi** [comment]
push and pop are StackNavigator's functions.
if you have StackNavigators inside your DrawerNavigator and you want to use StackNavigators functions inside DrawerNavigator you should do this inside your drawer component:
```
this.props.navigation.getChildNavigation('STACK_KEY').pop() // or anything else
```

**Comment by perfectAlways1028** [comment]
I was able to navigate to same route using different key
      props.navigation.navigate({ name: "DetailScreen",
                                  key: 'article'+props.item.article_id,
                                  params: {articleId: props.item.article_id}})

**Comment by mehdiChibani** [comment]
> hi! Thanks for reporting, this is expected behavior, as documented here https://reactnavigation.org/docs/en/navigation-prop.html.
> 
> You should just use `navigate` in drawer.

use navigation.goBack()

**Comment by Kylen513** [comment]
I traced the answer https://respective2.github.io/alfie/
