### ISSUE TITLE
Android Custom Header shadow (elevation) not visible when using headerMode: 'float'

### ISSUE THREAD

**Issue by hamzahayat** [react-navigation/react-navigation#4794]
### Current Behavior

What code are you running and what is happening?
- **Shadow doesn't display when using `headerMode: 'float'`**

![image](https://user-images.githubusercontent.com/20138310/43491962-b0cdc908-94f4-11e8-8999-ed223885eca2.png)

### Expected Behavior

What do you expect should be happening?
- **NOTE:** There is a clear and visible shadow under the header when `headerMode: 'float'` is removed.

![image](https://user-images.githubusercontent.com/20138310/43492005-f87eec6e-94f4-11e8-85e6-21cd42addaab.png)

### How to reproduce
_Create a custom header, and add  `headerMode: 'float'` to the options when declaring a `stackNavigator`_
- [Snack Link](https://snack.expo.io/SJ-2qDR4Q) 

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.9.3
| react-native     | 0.55.2

**Comment by dlittig** [comment]
Also happening with `react-navigation` 2.13.0 and `react-native` 0.55.4

**Comment by hagaigold** [comment]
not a custom header related.
same problem with "normal" header on float mode https://snack.expo.io/BydWR23FX

on rn 0.57.0 it is seems to work.

**Comment by hamzahayat** [comment]
@hagaigold I shall test it out on **React Native 0.57.0** and update the thread accordingly.

**Comment by tienf4m** [comment]
Looks like it works on rn 0.57.0 because of overflow support on android https://github.com/facebook/react-native/commit/b81c8b51fc6fe3c2dece72e3fe500e175613c5d4

**Comment by edmundojr** [comment]
I'm seeing this issue on react-native 0.57.8 and react-navigation 3.0.9.
