### ISSUE TITLE
react-navigation 2.x 把TabNavigator放在StackNavigator里 页面设置标题栏没生效

### ISSUE THREAD

**Issue by DreamboyA** [react-navigation/react-navigation#4795]
我不太会英文，为了避免用谷歌翻译出来的英文产生误解，只好使用中文提这个issues<br/>

如题，react-navigation 2.x 把TabNavigator放在StackNavigator里，页面设置标题栏文字没生效，1.x是可以的，但是2.x不行了，翻了官方文档也没看到说明。是不是包裹方式改变了？还是哪里改了？<br/>

### Current Behavior
代码如图
<img src="https://ws1.sinaimg.cn/large/006tNc79ly1ftuap3dz4fj30de02wglr.jpg"/>
<img src="https://ws4.sinaimg.cn/large/006tNc79ly1ftuapoa1e6j30nr09875k.jpg"/>
<img src="https://ws2.sinaimg.cn/large/006tNc79ly1ftuaqpznnpj30qk0f2abw.jpg"/>
<img src="https://ws2.sinaimg.cn/large/006tNc79ly1ftuar5jtarj30cf0o5dgi.jpg"/>

<br/>

### Expected Behavior

预期显示标题栏文字

<br/>
<br/>

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.9.3
| react-native     | 0.56.0
| node             | 8.9.4
| npm or yarn      | 5.6.0

**Comment by huangdou0204** [comment]
我也是，遇到了，弄了好久，文档也看了几遍，没漏东西，应该是bug？

**Comment by DreamboyA** [comment]
@huangdou0204 应该不是Bug，可能是API设计变化。期待开发人员回复

**Comment by huangdou0204** [comment]
@DreamboyA 其实我看了官方文档，但是这种操作我测试了下，好想无法满足我的要求。
官方的解决方案就是这个：https://reactnavigation.org/docs/zh-Hans/navigation-options-resolution.html

**Comment by DreamboyA** [comment]
@huangdou0204 可否分享下解决过程，我将页面上加上文档说的代码，标题栏并没有生效
<img src="https://ws1.sinaimg.cn/large/006tNc79ly1ftuezpoy5uj30w40d70v6.jpg"/>

**Comment by huangdou0204** [comment]
@DreamboyA 
![image](https://user-images.githubusercontent.com/2827261/43519113-c07b7b12-95c0-11e8-9ffb-0db74d87d8bd.png)
![image](https://user-images.githubusercontent.com/2827261/43519122-c90a84b2-95c0-11e8-96d0-dfb472d595c8.png)
这种做法有一个问题，那就是TabNav的顶部的标题栏被隐藏了，所有在TabNav中的StackNav不会显示返回和前一个页面的标题。
另一种做法对于我需要在某些页面的Title上加入自定义组件的需求来看并不好实现，或者说我觉得这种方式无法解决。

**Comment by huangdou0204** [comment]
@DreamboyA 这是我说的另一种方式
![image](https://user-images.githubusercontent.com/2827261/43519270-5ff062d4-95c1-11e8-8d1c-8c4ad2fa6442.png)
图片都来自官方的文档，自己多看

**Comment by DreamboyA** [comment]
@huangdou0204 看了文档，暂时写了种不完美的写法，甚至有点尬，不过解决了我的问题，以后多交流哈~
<img src="https://ws2.sinaimg.cn/large/006tNc79ly1ftufs2r1sej30f709imyu.jpg"/>

**Comment by huangdou0204** [comment]
@DreamboyA 
![image](https://user-images.githubusercontent.com/2827261/43521092-9a1a59c8-95c7-11e8-997b-62bd276a31fb.png)

注释也是一种方式，但是目前执行常量有点问题，解决下就2句代码搞定了

**Comment by eriveltonelias** [comment]
Hi @DreamboyA 

Can you write it in English? Maybe we can help your or this is solved?

**Comment by huangdou0204** [comment]
@eriveltonelias 
There is already a solution to this problem in the official documentation. thx

**Comment by eriveltonelias** [comment]
Awesome @huangdou0204! 

Thanks.  :)
