### ISSUE TITLE
StackNavigator inside TabNavigator - iOS swipe back

### ISSUE THREAD

**Issue by gunnartorfis** [react-navigation/react-navigation#4796]
I think I've found a bug with react-navigation, but point me towards StackOverflow if that's not the case.

We have a MaterialTopTabNavigator with a bottom navigation bar (to be able to swipe between tabs on iOS). Inside each of the tabs, there’s a StackNavigator.

- MaterialTopTabNavigator (swiping is enabled between StackNavigator 1 and 2)
    - StackNavigator 1
        - Screen A
        - Screen B
    - StackNavigator 2

We want to be able to control swipeEnabled in navigationOptions and have it disabled once something is pushed onto any of the stacks, i.e. so the MaterialTopTabNavigator doesn't get swiped when swiping horizontally inside one of the StackNavigators' child. 

We added a listener (willFocus and willBlur) to enable/disable swiping accordingly. This works as expected but with one exception.

Inside both the StackNavigators' childrens (Screen A and B), we have the listener:
`
this.props.navigation.addListener('willFocus', () => {
    StackNavigator12.navigationOptions = {
        swipeEnabled: true
     };
});
`

Everything works fine on Android and on iOS if one taps on the back arrow. But if one swipes to navigate back on iOS, swiping between the main tabs is disabled (e.g. swiping back from Screen B to Screen A). 

The listener event is fired and the same code is executed when swiping back on iOS and when tapping the back arrow.

### My environment
| software         | version
| ---------------- | -------
| react-navigation | ^2.5.2
| react-native     | 0.55.4
| node             |  8.11.2
| npm or yarn      | npm 5.6.0

**Comment by eriveltonelias** [comment]
Hi @gunnartorfis! 

Please make your code runnable either on https://snack.expo.io or in a project I can clone from Github.

**Comment by gunnartorfis** [comment]
I've sent you an invite, but here's a link as well: https://github.com/gunnartorfis/ReactNavigationShowcase

Let me know if you have any questions about how to reproduce the issue.

**Comment by gunnartorfis** [comment]
Hi again mate. 

I just wanted to follow up and check if you had looked into this. I also wanted to check if there's a possibility to set a bounty for this issue?

**Comment by gunnartorfis** [comment]
Thanks for the time @eriveltonelias!

This solves that issue but produces the behavior we were trying to avoid, to begin with - now you can navigate to a "Screen 2" and still swipe between the two main tabs. 

Any thoughts on how we'd accomplish that result?

**Comment by gunnartorfis** [comment]
Is there anyone that is willing to look into this for me? Can I set a bounty somehow for this issue?

**Comment by brentvatne** [comment]
https://snack.expo.io/@notbrent/laughing-truffle

you can set swipeEnabled on the navigationOptions stacks themselves depending on what route you're on
