### ISSUE TITLE
Drawer Navigator turns Action bar to white background with back arrow

### ISSUE THREAD

**Issue by rAnAaRsl** [react-navigation/react-navigation#4799]
I have managed to open drawer navigator with hamburger icon in my action bar but when drawer opens my action bar hides and a white action bar visible with back arrow on its left to close the drawer.
I want to open drawer above my action bar and does not show white action bar instead it should show my action bar how this can be achieved.

here is my code 

const Navigation = DrawerNavigator({
    Home: {
        header: {visible: true},
        screen: MyMap,
        drawerLabel: 'Home',

        navigationOptions: ({navigation}) => ({

            title: 'Home', headerLeft: <DrawerButton navigation={navigation}/>,
            drawerIcon: ({tintColor}) => (<Image
                style={{
                    height: 25,
                    width: 25
                }} source={require('../Images/home_icon.png')}/>),
            headerStyle: {
                backgroundColor: '#00bfff',
                height: 50,
                justifyContent: 'flex-end',
                elevation: 0
            },
            headerTitleStyle: {
                color: '#ffffff'
            },
            activeTintColor: {
                color: '#e91e63'
            }
        })
    },
    Campaigns: {
        screen: Campaigns,
        drawerLabel: 'Campaigns',
        navigationOptions: ({navigation}) => ({
            title: 'Campaigns', headerLeft: <DrawerButton navigation={navigation}/>,
            drawerIcon: ({tintColor}) => (<Image
                source={require('../Images/car_icon.png')}
                style={{
                    height: 25,
                    width: 25
                }}/>),
            headerStyle: {
                backgroundColor: '#00bfff',
                height: 50,
                justifyContent: 'flex-end',
                elevation: 0
            },
            headerTitleStyle: {
                color: '#ffffff'
            },
            activeTintColor: {
                color: '#e91e63'
            }
        })

    },
    Profile: {
        screen: Profile,
        drawerLabel: 'Profile',
        navigationOptions: ({navigation}) => ({
            title: 'Profile', headerLeft: <DrawerButton navigation={navigation}/>,
            drawerIcon: ({tintColor}) => (<Image
                source={require('../Images/mail_icon.png')}
                style={{
                    height: 25,
                    width: 25
                }}/>),
            headerStyle: {
                backgroundColor: '#00bfff',
                height: 50,
                justifyContent: 'flex-end',
                elevation: 0
            },
            headerTitleStyle: {
                color: '#ffffff'
            },
            activeTintColor: {
                color: '#e91e63'
            }
        })
    },
    VehiclePhotos: {
        screen: VehiclePhotos,
        drawerLabel: 'Vehicle Photos',
        navigationOptions: ({navigation}) => ({
            title: 'Vehicle Photos', headerLeft: <DrawerButton navigation={navigation}/>,
            drawerIcon: ({tintColor}) => (<Image
                source={require('../Images/camera_icon.png')}
                style={{
                    height: 25,
                    width: 25
                }}/>),
            headerStyle: {
                backgroundColor: '#00bfff',
                height: 50,
                justifyContent: 'flex-end',
                elevation: 0
            },
            headerTitleStyle: {
                color: '#ffffff'
            },
            activeTintColor: {
                color: '#e91e63'
            }
        })
    },
    DrivingHistory: {
        screen: DrivingHistory,
        drawerLabel: 'Driving History',
        navigationOptions: ({navigation}) => ({
            title: 'Driving History', headerLeft: <DrawerButton navigation={navigation}/>,
            drawerIcon: ({tintColor}) => (<Image
                source={require('../Images/driving_history.png')}
                style={{
                    height: 25,
                    width: 25
                }}/>),
            headerStyle: {
                backgroundColor: '#00bfff',
                height: 50,
                justifyContent: 'flex-end',
                elevation: 0
            },
            headerTitleStyle: {
                color: '#ffffff'
            },
            activeTintColor: {
                color: '#e91e63'
            }
        })
    },

    AboutUs: {
        screen: AboutUs,
        drawerLabel: 'About Us',
        navigationOptions: ({navigation}) => ({
            title: 'About Us', headerLeft: <DrawerButton navigation={navigation}/>,
            drawerIcon: ({tintColor}) => (<Image
                source={require('../Images/about.png')}
                style={{
                    height: 25,
                    width: 25
                }}/>),
            headerStyle: {
                backgroundColor: '#00bfff',
                height: 50,
                justifyContent: 'flex-end',
                elevation: 0
            },
            headerTitleStyle: {
                color: '#ffffff'
            },
            activeTintColor: {
                color: '#e91e63'
            }
        })
    }

}, {
    
    headerMode: 'float',
    drawerPosition: 'left',
    drawerOpenRoute: 'DrawerOpen',
    drawerCloseRoute: 'DrawerClose',
    drawerToggleRoute: 'DrawerToggle'
});

Environment linux ubuntu 16.0.4
React native version 0.51.0
React navigation version ^1.0.0-beta.22
target OS version Android

**Comment by vikrantnegi** [comment]
Can you create a minimal required [snack](https://snack.expo.io/)? 
I'll be able to help you better.

Thanks.

**Comment by EyMaddis** [comment]
The problem here is probably that there are two StackNavigators layered on top of each other.

Basically this setup:
https://snack.expo.io/@eymaddis/react-navigation-v2---duplicate-headers

Due to the fact that you did set `headerMode: 'float'` it will probably be directly on top of each other.

This is actually a huge pain for me right now. This was not an issue in v1 (at least I did not notice it).

**Comment by brentvatne** [comment]
your react navigation version is very old and this is not an issue in the latest version
