### ISSUE TITLE
goBack Between StackNavigators

### ISSUE THREAD

**Issue by max-zu** [react-navigation/react-navigation#4800]
I have next navigation Structure: SwitchNavigator with nested TabNavigaror(with nested StackNavigators) and StackNavigator. 
```
const AppNavigation = createSwitchNavigator({
  TabApp: TabNavigation,
  AuthLoading: AuthLoadingScreen,
  Auth: AuthStack,
}, {
  initialRouteName: 'AuthLoading',
});
```
```
const TabNavigation = createBottomTabNavigator({
  App: AppStack,
  TabSearch: SearchStack,
}, {
  initialRouteName: 'App',
  swipeEnabled: false,
})
```

```
const AppStack = createStackNavigator({
  NewsList: NewsListScreen,
  News: NewsScreen,
}, {
  headerMode: 'none',
});
```
```
const SearchStack = createStackNavigator({
  Search: SearchScreen,
}, {
  headerMode: 'none',
  cardStyle,
});
```
The problem is this:  I turn to SearchSсreen. Then I turn to NewsScreen. Then i press Back button (`navigation.goBack()`). I expect that I will go to the previous screen (SearchScreen in my example), but I turn to the InitialRoute from TabNavigator

Environment linux ubuntu 18.0.4
React native version 0.55.4
React navigation version 2.0.4
Node: 8.11.3

**Comment by audiolion** [comment]
What happens here is that goBack only goes back within the current stack navigator that you are in, so `goBack` won't return you to the `AppStack` navigator that you just came from, it will go back up the chain from `SearchStack` navigator history, or, in your case, the initial route if there isn't anything.

Not sure if there is a better way to do this but when I navigate between stack navigators I pass the data to navigate back to them:

```js
this.props.navigation.navigate('DifferentStackNavigator', { backKey: 'CurrentStackNavigator' });
```

Then in my `DifferentStackNavigator` I have my `goBack` defined as:

```js
goBack = () => {
  let backKey = this.props.navigation.getParam('backKey', false);
  if (backKey) {
    // clear backKey so navigation doesnt break
    this.props.navigation.setParams({ backKey: null });
    // navigate back to other stack navigator
    this.props.navigation.navigate(backKey);
  } else {
    // regular go back
    this.props.navigation.goBack();
};
```

**Comment by londonoliver** [comment]
@audiolion This works, but if you press the hardware back button on Android after navigating back to `CurrentStackNavigator` it will navigate back to `DifferentStackNavigator`. Is there any way to stop this from happening?

**Comment by audiolion** [comment]
for android specific back handling I would check out https://reactnavigation.org/docs/en/custom-android-back-button-handling.html

**Comment by ericvicenti** [comment]
Yep, @audiolion is correct about the behavior here and other ways to handle it.

If people have ideas on how to improve the back handling API, feel free to publish an RFC or post an issue in the RFCs repo so we can discuss it!

https://github.com/react-navigation/rfcs/pulls

**Comment by gsklee** [comment]
Curious about this issue as well; any RFC on this one so far?

**Comment by peisenmann** [comment]
I don't specifically have a suggestion for how to improve this, but it's definitely still an issue that I tripped over for a bit. I have the exact same navigation layout as the original post, and it's very unintuitive that it doesn't work as the original post describes. Perhaps there's some context that the navigators could share to each other behind the scenes when one routes between them. Another possible option is that I could imperatively call some function that intentionally "merges" multiple stacks together such that I can keep my overall structure but have certain stacks be "cross-stack back aware".
