### ISSUE TITLE
`headerMode: none` doesn't work - renders header effectively

### ISSUE THREAD

**Issue by wzup** [react-navigation/react-navigation#4801]
### Current Behavior

`headerMode: 'node',` renders header all right. 

But docs says:
> none - No header will be rendered.

### Expected Behavior

> none - No header will be rendered.

### How to reproduce

```javascript
export const TabsMain = TabNavigator({
  Home: {
    screen: DashboardStack,
    navigationOptions: {
      headerStyle,
      headerMode: 'none',  // doesn't work
      headerTitleStyle,
      header: null, // only this works
    }
  },
```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.5.8
| react-native     |0.54.2
| node             |8.11.3
| npm or yarn      |5.6.0

**Comment by wzup** [comment]
@benprebble 
Typo, sorry. Should be `none`

**Comment by vikrantnegi** [comment]
`headerMode ` is not a property of `navigationOptions` but of the navigator. Use it for navigator instead.

```
export const TabsMain = TabNavigator({
  Home: {
    screen: DashboardStack,
    navigationOptions: {
      headerStyle,      
      headerTitleStyle,
      header: null, // only this works
    },
  {
     headerMode: 'none',  // should work here
  }
},
```
