### ISSUE TITLE
The website 'https://reactnavigation.org/' is dead

### ISSUE THREAD

**Issue by brianyeh01** [react-navigation/react-navigation#4803]
I'm viewing the React Navigation website, but it is unavailable now.

**Comment by maxmagee** [comment]
I just came here to open this issue as well. More specifically, reactnavigation.org gives the following Github pages 404 error:

> There isn't a GitHub Pages site here.

> If you're trying to publish one, read the full documentation to learn how to set up GitHub Pages for your repository, organization, or user account.

**Comment by kenyasue** [comment]
me too

**Comment by maxmagee** [comment]
It's back for me now.
