### ISSUE TITLE
Quickly slide the Flatlist page while switching the tabbar, causing the Flatlist page to load blank

### ISSUE THREAD

**Issue by MistyRain5** [react-navigation/react-navigation#4804]
I have next navigation Structure:

const Tab = createBottomTabNavigator({
  Home: {
    screen: Home,
    navigationOptions: ({navigation}) => ({
        tabBarLabel: 'Home',
    })
  },
  Nearby: {
    screen: Nearby,
    navigationOptions: ({navigation}) => ({
        tabBarLabel: 'Nearby',
    })
  }}, {
    swipeEnabled: false,
    animationEnabled: false,
    lazy: true,
    tabBarOptions: {
        activeTintColor:'#910910',
        inactiveTintColor:'gray',
        style:{backgroundColor:'#fff'},
        showIcon: true
    }
});

const Navigator = createStackNavigator({
  Tab,
});

Home and Nearby are a Flatlist page with lots of data.

The problem is this: when i quickly slide the Nearby and switching the tabbar, causing the Nearby page render none. 

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.10.0
| react-native     | 0.56.0
| node             | 16.4.1
| npm      | 5.6.0

System:
      OS: macOS High Sierra 10.13.4
iOS SDK:
        Platforms: iOS 11.4
IDEs:
      Xcode: 9.4.1/9F2000

**Comment by eriveltonelias** [comment]
Hi @MistyRain5! 

Can you reproduce this issue on https://snack.expo.io/  ? And then we can help you to fix it.

**Comment by MistyRain5** [comment]
[https://snack.expo.io/rkDKCPHr7](url)

**Comment by MistyRain5** [comment]
Hi @eriveltonelias 
i reproduce my issue on [https://snack.expo.io/@mistyrain/flatlistdemo](url), thank you for your help.

**Comment by MistyRain5** [comment]
https://snack.expo.io/@mistyrain/flatlistdemo

**Comment by MistyRain5** [comment]
Hi @eriveltonelias 
i reproduce my issue on https://snack.expo.io/@mistyrain/flatlistdemo, thank you for your help.

**Comment by MistyRain5** [comment]
Hi @eriveltonelias 
i reproduce my issue on https://snack.expo.io/@mistyrain/flatlistdemo, thank you for your help.

**Comment by Liqiankun** [comment]
@MistyRain5 Same issue here! I will upload some pics!

**Comment by brentvatne** [comment]
see the comment that i posted on that other issue - https://github.com/react-navigation/react-navigation-tabs/pull/42#issuecomment-426013264

enable react-native-screens with this: https://github.com/react-navigation/react-navigation.github.io/issues/255
