### ISSUE TITLE
navigation plugin breakage

### ISSUE THREAD

**Issue by n7229** [react-navigation/react-navigation#4808]
error: bundling failed: Error: Unable to resolve module `./routers/pathUtils` from `/Volumes/Personal/Documents/Mobile/Consumer/node_modules/react-navigation/src/createNavigationContainer.js`: The module `./routers/pathUtils` could not be found from `/Volumes/Personal/Documents/Mobile/Consumer/node_modules/react-navigation/src/createNavigationContainer.js`. Indeed, none of these files exist:

**Comment by brentvatne** [comment]
please fill out the issue template correctly
