### ISSUE TITLE
An fetch error in RN 0.56

### ISSUE THREAD

**Issue by wm2zfei** [react-navigation/react-navigation#4814]
```
import React, { Component } from 'react';
import { Platform, StyleSheet, Text, View, Button } from 'react-native';

export default class App extends Component {
  postfun() {
    return new Promise(function (resolve, reject) {
      fetch('http://localhost/app/posttest', {
        method: 'post',
        headers: {
          "Content-Type": "application/json;charset=UTF-8",
        },
        body: ""
      }).then((response) => {
        console.log(response)
      })
    });
  }
  render() {
    return (
      <View style={styles.container}>
        <Button
          style={styles.welcome}
          onPress={this.postfun}
          title="Post Test"
        ></Button>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  }
});

```
The above code works fine in RN v_0.55, but throws an exception in version 0.56:
Response {type: "default", status: 400, ok: false, ....
 how to fix ?

| software         | version
| ---------------- | ------- 
| react-native     |v0.56.0
| node             |v10.5.0
| npm or yarn      |6.3.0

**Comment by eriveltonelias** [comment]
@wm2zfei ! 

Sorry but looks like this issue isn't related with **react-navigation**. Please consider to ask it on [StackOverflow](https://stackoverflow.com/questions/tagged/react-native).

**Comment by vonovak** [comment]
@wm2zfei sorry to see you're having an issue, but this is not related to react-navigation. Also, an issue with fetching from localhost is likely something you will have to solve yourself if you do not share the server code
