### ISSUE TITLE
routing issue in react-navigation with createStackNavigator  and createDrawerNavigator

### ISSUE THREAD

**Issue by HemanthNGovindan** [react-navigation/react-navigation#4815]
Below is my partial code, where i have an base route as stack navigator and after login i have both tab navigator and drawer navigator. But now I'm unable to set drawer navigator to stack navigator as its giving error saying 

> **The component for route 'Home' must be a React component**

I want to implement a root stack navigator and after login i should populating drawer component with other options.  Please help me on this

`import { createStackNavigator, createDrawerNavigator } from 'react-navigation';

//Component Imports
import { DrawerScreen } from './drawer';
import { LoginComponent, RegisterComponent, RecoverComponent } from '../components';
import { BaseBottomTabRouteStack } from './base.bottom.tab.route';
export const BaseRouteStack = createStackNavigator(
    {
        Login: {
            screen: LoginComponent,
            navigationOptions: () => ({
                header: null
            })
        },
        Recover: {
            screen: RecoverComponent,
            navigationOptions: () => ({
                title: 'Recover Account'
            })
        },
        Home: {
            screen: BaseDrawerNavigator
        },
        Register: {
            screen: RegisterComponent,
            navigationOptions: () => ({
                title: `Register`
            })
        }
    },
    {
        initialRouteName: 'Login',
        contentComponent: DrawerScreen,
        drawerWidth: 300
    }
);
const BaseDrawerNavigator = createDrawerNavigator (
    {
        Home: {
            screen: BaseBottomTabRouteStack,
            navigationOptions: () => ({
                // header: {
                //     visible: false
                // }
            })
        }
    },
    {
        initialRouteName: 'Login',
        contentComponent: DrawerScreen,
        drawerWidth: 300
    }
);
`

**Comment by eriveltonelias** [comment]
Hi @HemanthNGovindan ! 

Please, try to reproduce your issue on https://snack.expo.io/ and then we can help you.

**Comment by HemanthNGovindan** [comment]
Thanks and I have updated snack, I'm very new to react native. Please help me out with navigation.

**Comment by eriveltonelias** [comment]
you're welcome, @HemanthNGovindan can you share the snack link in here ?

**Comment by HemanthNGovindan** [comment]
Sorry, I missed it.
Its here: https://snack.expo.io/BkZMo2USm

**Comment by eriveltonelias** [comment]
Hi @HemanthNGovindan! 

I created a simple example for you, I hope that it can help you. 

https://snack.expo.io/SyWOaDcHm
