### ISSUE TITLE
Child action are not execute on deep linking with nested navigators

### ISSUE THREAD

**Issue by charpeni** [react-navigation/react-navigation#4820]
### Current Behavior

Nested actions triggered from deep linking are not execute if we're already on destination of the first action.

```
xcrun simctl openurl booted test://potato/123
```

The action is:

```json5
{
  type: 'Navigation/NAVIGATE',
  routeName: 'Potato',
  params: {},
  action: {
    type: 'Navigation/NAVIGATE',
    routeName: 'PotatoDetails',
    params: { id: '123' }
  }
}
```

#### If we're in the stack.

```
-- TabNavigator
---- ScreenA
---- Potato (StackNavigator)
------ Potato <-------------- We're here
------ PotatoDetails
```

We stay at `Potato` screen.

#### If we're elsewhere in the root tab.

```
-- TabNavigator
---- ScreenA <--------------- We're here
---- Potato (StackNavigator)
------ Potato
------ PotatoDetails
```

We go in `Potato` stack and then `PotatoDetails`.

#### Possible Cause

It seems caused by a name collision between `routeName` and `path`, if we rename our first stack screen to something else, we have the expected behavior:

```diff
const StackNavigator = createStackNavigator({
- Potato: {
+ SomethingElse: {
    screen: screenGenerator('Screen 1'),
  },
  PotatoDetails: {
    screen: screenGenerator('Screen 2'),
    path: 'potato/:id',
  },
});
```

But even with path set to null, it doesn't work:

```diff
const StackNavigator = createStackNavigator({
  Potato: {
    screen: screenGenerator('Screen 1'),
+   path: null,
  },
  PotatoDetails: {
    screen: screenGenerator('Screen 2'),
    path: 'potato/:id',
  },
});
```

### Expected Behavior

Child action should be executed even if we're on all set with the current one.

### How to reproduce

https://github.com/charpeni/react-navigation-deep-linking-issue

1. Go to Potato tab.
1. Execute `xcrun simctl openurl booted test://potato/123`.
1. You won't see any changes.
1. Go to the first tab (Screen1).
1. Execute `xcrun simctl openurl booted test://potato/123`.
1. You'll be on `PotatoDetails` screen.

```javascript
import React, { Component } from 'react';
import { Text, View } from 'react-native';
import { createTabNavigator, createMaterialTopTabNavigator, createStackNavigator } from 'react-navigation';

const screenGenerator = screen => () => (
  <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
    <Text>{screen}</Text>
  </View>
);

const StackNavigator = createStackNavigator({
  Potato: {
    screen: screenGenerator('Screen 1'),
  },
  PotatoDetails: {
    screen: screenGenerator('Screen 2'),
    path: 'potato/:id',
  },
});

const tabs = {
  ScreenA: screenGenerator('Screen A'),
  Potato: StackNavigator,
};

const TabNavigator = createMaterialTopTabNavigator(tabs, {
  paths: Object.keys(tabs).reduce((paths, path) => ({ ...paths, [path]: null }), {}),
});

export default class App extends Component {
  render() {
    return <TabNavigator uriPrefix='test://' />;
  }
}
```

### Your Environment

```
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.4
      CPU: x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
      Memory: 1.15 GB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.11.3 - ~/.nvm/versions/node/v8.11.3/bin/node
      Yarn: 1.9.2 - /usr/local/bin/yarn
      npm: 5.6.0 - ~/.nvm/versions/node/v8.11.3/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        Build Tools: 26.0.3, 27.0.3
        API Levels: 21, 23, 25, 26, 27
    IDEs:
      Android Studio: 3.1 AI-173.4720617
      Xcode: 9.4/9F1027a - /usr/bin/xcodebuild
    npmPackages:
      react: 16.4.1 => 16.4.1
      react-native: 0.56.0 => 0.56.0
     react-navigation: 2.10.0 => 2.10.0
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

**Comment by ericvicenti** [comment]
Seems like we have two issues in one here.

1. Unclear path handling API with regard to default paths being routeName instead of null, when null is needed to pass through the path to child routers

2. action.action is reportedly not working on a navigate action. I have attempted to replicate your bug in the following router test, but it passes on master: 

```js

test('Handles no-op actions with tabs within stack router', () => {
  const Foo = () => <div />;
  const Bar = () => <div />;
  const Baz = () => <div />;
  const Potato = () => <div />;
  Potato.router = StackRouter({
    Foo,
    Bar,
  });
  const TestRouter = TabRouter({
    Baz,
    Potato,
  });

  const state1 = TestRouter.getStateForAction({ type: NavigationActions.INIT });

  const state2 = TestRouter.getStateForAction(
    {
      type: NavigationActions.NAVIGATE,
      routeName: 'Potato',
    },
    state1
  );
  const child2 = state2.routes[state2.index];
  expect(child2.routeName).toEqual('Potato');
  expect(child2.routes[child2.index].routeName).toEqual('Foo');

  const state3 = TestRouter.getStateForAction(
    {
      type: NavigationActions.NAVIGATE,
      routeName: 'Potato',
      action: {
        type: NavigationActions.NAVIGATE,
        routeName: 'Bar',
      },
    },
    state2
  );
  const child3 = state3.routes[state3.index];
  expect(child3.routeName).toEqual('Potato');
  expect(child3.routes[child3.index].routeName).toEqual('Bar');
});
```

So I'm not sure why you're having troubles with `action.action`. If you can replicate the bug in an Expo Snack without the path handling stuff, I should be able to fix it tomorrow morning.

**Comment by charpeni** [comment]
Here's a snack without the path handling stuff: https://snack.expo.io/rJzH5DPHX

I've been able to replicate the state from the path handling.

From tab ScreenA, you can click on `Go to PotatoDetails` to go on Potato tab and then Screen2. Then, back to Screen1, and from there you can't press `Go to PotatoDetails` to go to Screen2. But if you rename the Potato screen from the nested stack, everything works.

**Comment by ericvicenti** [comment]
I'm not sure why both routes need to be named "Potato". Couldn't you avoid that name collision?

Also, in this case I don't think you need to use a nested action. It should be fine if you always fire a navigate action to PotatoDetails

Changed your snack a bit to reflect that:
https://snack.expo.io/ryWDP9kUm

**Comment by charpeni** [comment]
Of course, I have renamed the route to avoid the name collision, I was just curious if this behavior was intentional.

I'd agree with you here about the nested action in this context, but my main issue was the same nested action being dispatched by the path handling (deep linking), which I can't choose the action format.

**Comment by syedamirali14** [comment]
it is still not working
