### ISSUE TITLE
Drawer Not Closing if "Current Scene" is Tapped

### ISSUE THREAD

**Issue by telkandrew** [react-navigation/react-navigation#4821]
Not a huge deal, but the Drawer should probably close if the user taps to navigate to the scene they're currently on.

**Comment by Djinne** [comment]
I added this to my createDrawerNavigator after the screens object
contentComponent: (props) => (
   <View>
        <DrawerItems labelStyle={[styles.drawerStyle]} {...{...props, onItemPress:
        (route)=>{
          props.navigation.closeDrawer(); props.navigation.navigate(route.route.routeName);
        }}}
       />
   </View>)

**Comment by brentvatne** [comment]
moved to https://github.com/react-navigation/react-navigation-drawer/issues/20
