### ISSUE TITLE
react native tabbar navigation menu

### ISSUE THREAD

**Issue by Uzairrrr** [react-navigation/react-navigation#4823]
this is my code i want menu when i click on settings tab? Help me
import React,{Component} from 'react';
import {
  DrawerNavigator,
  StackNavigator,
  TabNavigator
} from 'react-navigation';
import Icon from 'react-native-vector-icons/Ionicons';
import HomeScreen from './tabs/HomeScreen';
import CompanyScreen from './tabs/CompanyScreen';
import TimeCardScreen from './tabs/TimeCardScreen';
import DocumentScreen from './tabs/DocumentScreen';

const TabNavigation = TabNavigator({
    Home: {
      screen: HomeScreen,
      navigationOptions: {
        tabBarLabel: 'Home',
        tabBarIcon: ({ tintColor, focused }) => <Icon
          name={focused ? 'ios-home' : 'ios-home'}
          size={28}
          style={{ color: tintColor }}
        />
      },
    },
    TimeCard: {
      screen: TimeCardScreen,
      navigationOptions: {
        tabBarLabel: 'TimeCard',
        tabBarIcon: ({ tintColor, focused }) => <Icon
          name={focused ? 'ios-card' : 'ios-card'}
          size={28}
          style={{ color: tintColor }}
        />
      },
    },
    Company: {
      screen: CompanyScreen,
      navigationOptions: {
        tabBarLabel: 'Company',
        tabBarIcon: ({ tintColor, focused }) => <Icon
          name={focused ? 'ios-business' : 'ios-business'}
          size={28}
          style={{ color: tintColor }}
        />
      },
    },
    Document: {
      screen: DocumentScreen,
      navigationOptions: {
        tabBarLabel: 'Document',
        tabBarIcon: ({ tintColor, focused }) => <Icon
          name={focused ? 'ios-document' : 'ios-document'}
          size={28}
          style={{ color: tintColor }}
        />
      },
    },
    Settings: {
      screen: HomeScreen,
      navigationOptions: {
        tabBarLabel: 'Settings',
        tabBarIcon: ({ tintColor, focused }) => <Icon
          name={focused ? 'ios-settings' : 'ios-settings'}
          size={28}
          style={{ color: tintColor }}
        />
      },
    }
  });
  
  // Wrap tab navigation into drawer navigation
  export default TabsWithDrawerNavigation = DrawerNavigator({
    Tabs: {
      screen: TabNavigation,
    }
  });

**Comment by Uzairrrr** [comment]
my output is 
![screen shot 2018-08-07 at 6 09 56 pm](https://user-images.githubusercontent.com/23259529/43777729-1fb4f468-9a6d-11e8-9eca-2949461b8caf.png)

and i want this to happen.. click on setting show the menu
![screen shot 2018-08-07 at 6 10 37 pm](https://user-images.githubusercontent.com/23259529/43777766-39438de0-9a6d-11e8-95bf-9dd7ac36d8b4.png)

**Comment by ericvicenti** [comment]
This sort of UI is not supported by react-navigation. You can make a custom version TabNavigator instead
