### ISSUE TITLE
createBottomTabNavigator gets route-name instead of tabBarLabel in some case

### ISSUE THREAD

**Issue by HaJo10** [react-navigation/react-navigation#4825]
Hi, having some troubles translating tabs using react-i18next I tested with your example at
https://github.com/i18next/react-i18next/tree/master/example/react-native-expo
I changed the stack used in wrappedStack (App.js) from StackNavigator to BottomTabNavigator using createBottomTabNavigator.
As long as all routes are defined directly with screens all works as expected. When for example defining first route/tab using a stack (to navigate lets say from a settings tab to a screen changing language) and second route with screen then the "stack-route" is labeled with the route-name instead of using tabBarLabel or title at least.
What I am doing wrong? Is there a way to change (translate) the route-name? I don't think so because of stack handling.

react-i18next (issue #484) saying: "overall i guess it's more a problem / limitation of react-navigation"
so I opened this issue.

I made changes to app.js, i18n.js, Home.js, Page2.js and added Language.js.

### Current Behavior
tabbar is labeled with route-name when route is a stack

### Expected Behavior
tabbar labeled with tabBarLabel as it is when route is a screen

### How to reproduce
https://github.com/HaJo10/react-i18next

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^2.11.2
| react-native     |      0.55.4          
| node             |         10.4.0
| npm or yarn      | npm 6.2.0

**Comment by gunnartorfis** [comment]
Having the same issue here using createBottomTabNavigator with createStackNavigator for each of the tab screens.

**Comment by HaJo10** [comment]
Take a look at issue #493
it helped me

**Comment by brentvatne** [comment]
> As long as all routes are defined directly with screens all works as expected. When for example defining first route/tab using a stack (to navigate lets say from a settings tab to a screen changing language) and second route with screen then the "stack-route" is labeled with the route-name instead of using tabBarLabel or title at least.

more information on this here: https://reactnavigation.org/docs/en/navigation-options-resolution.html

let me know if this resolves your issue

**Comment by brentvatne** [comment]
closing because no reply
