### ISSUE TITLE
The back button does not work on all devices

### ISSUE THREAD

**Issue by eugenio-caicedo** [react-navigation/react-navigation#4826]
### Current Behavior

I have the following navigation with 2 screens. A parent screen (HomeScreen) and a daughter screen (SignInScreen).

````
const AuthStack = createStackNavigator(
    {
        Home: HomeScreen,
        SignIn: SignInScreen,
    },
    {
        initialRouteName: 'Home',
    }
);
````

Currently, the backspace button that is displayed on the daughter screen shows the parent screen again, but this only happens with some devices.

### Expected Behavior

It is expected that in the back button that is shown on the daughter screen it will show the parent screen again.

### Your Environment

| Software         | version
| ---------------- | -------
| react-navigation | 2.9.3
| react-native     | 0.55.4
| node             | 8.11.3
| npm      | 5.6.0

| Devise | version
| ---------------- | -------
| Android | 6.0.0
| Android SDK     | 23
| Phone Model            | Blu Dash M2

**Comment by ericvicenti** [comment]
Can you provide more information about what devices work and do not work?

If it only works on some Android devices, then it seems that this is an issue with React Native's underlying BackHandler API, or a problem with Android itself. Can you test the React Native BackHandler API, and file an issue on the RN repo, if you still see differences between the different device types?

https://facebook.github.io/react-native/docs/backhandler

https://github.com/facebook/react-native/issues/new
