### ISSUE TITLE
Custom Transition giving error : Cannot call a class as a function

### ISSUE THREAD

**Issue by samuelltk** [react-navigation/react-navigation#4829]
I meet the bug  "Custom Transition giving error : Cannot call a class as a function". Please help us, thanks.
My repository address: https://github.com/samuelltk/RnDemo
The demo is ok when i use react-navigation 1.4.0. but the error will be show with "react-navigation": "2.9.3".

@vonovak @brentvatne @jugglebird @gabriel @BrandonSmith @jlongster @plasticine

**Comment by samuelltk** [comment]
My code:

const r = createNavigator(StackRouter({
  A: {
    screen: Template
  }, B: {
    screen: Template
  }
}, {
  initialRouteName: 'A',
  headerMode: 'float',
}));

const Navigator = createNavigationContainer(r(BubbleTransition))

export default class AppWithNavigationState extends Component {
  render () {
    return (
      <View style={{flex: 1}}>
        <Navigator/>
      </View>
    )
  }
}

export default class BubbleTransition extends Component {
  ...
  render () {
    return (
      <Transitioner
        configureTransition={() => ({
          timing: Animated.timing,
          duration: 1000,
          easing: Easing.linear(),
          useNativeDriver: true
        })}
        ...
      />
    )
  }
}

**Comment by Ketn** [comment]
There were some breaking changes in react-navigation 2.x from 1.x.

Your code and the tutorial you followed is from react-navigation@1.4.x. You need to make appropriate changes as per the updated documentation: https://reactnavigation.org/docs/en/getting-started.html
