### ISSUE TITLE
Migrated to RN 0.56.0 and encountering an error with StackNavigator

### ISSUE THREAD

**Issue by reedyrm** [react-navigation/react-navigation#4830]
StackNavigator errors out.  I've been trying to track down if this is an issue with babel or with react-navigation for a better part of a day since I upgraded my project from RN 0.55.2 to RN 0.56.0.  I am able to run the project in release mode and everything works.  I only encounter this error in debug.

I'm still actively looking into the issue, but I thought I would throw a repo on here to see if there was any insight on this problem.

I found a react-native thread earlier in RN 0.56.0 release cycle that had similar problems.  I ended up filing a bug around the core problem: https://github.com/facebook/react-native/issues/20588

### Current Behavior

App crashes with:

```
TypeError: undefined is not an object (evaluating '_this._setComponentRef.bind')

This error is located at:
    in AnimatedComponent (at StackViewCard.js:12)
    in Card (at createPointerEventsContainer.js:28)
    in Container (at StackViewLayout.js:612)
    in RCTView (at View.js:43)
    in RCTView (at View.js:43)
    in StackViewLayout (at withOrientation.js:30)
    in withOrientation (at StackView.js:63)
    in RCTView (at View.js:43)
    in Transitioner (at StackView.js:21)
    in StackView (at createNavigator.js:59)
    in Navigator (at createKeyboardAwareNavigator.js:11)
    in KeyboardAwareNavigator (at createNavigationContainer.js:376)
    in NavigationContainer (at App.js:8)
    in App (at renderApplication.js:32)
    in RCTView (at View.js:43)
    in RCTView (at View.js:43)
    in AppContainer (at renderApplication.js:31)

AnimatedComponent
    index.bundle?platform=ios&dev=true&minify=false:45418:56
constructClassInstance
    index.bundle?platform=ios&dev=true&minify=false:20994:32
updateClassComponent
    index.bundle?platform=ios&dev=true&minify=false:22561:35
performUnitOfWork
    index.bundle?platform=ios&dev=true&minify=false:25090:27
workLoop
    index.bundle?platform=ios&dev=true&minify=false:25123:47
renderRoot
    index.bundle?platform=ios&dev=true&minify=false:25156:21
performWorkOnRoot
    index.bundle?platform=ios&dev=true&minify=false:25717:23
performWork
    index.bundle?platform=ios&dev=true&minify=false:25649:30
performSyncWork
    index.bundle?platform=ios&dev=true&minify=false:25624:20
requestWork
    index.bundle?platform=ios&dev=true&minify=false:25530:26
scheduleWork
    index.bundle?platform=ios&dev=true&minify=false:25392:28
scheduleRootUpdate
    index.bundle?platform=ios&dev=true&minify=false:25920:21
render
    index.bundle?platform=ios&dev=true&minify=false:26375:26
renderApplication
    index.bundle?platform=ios&dev=true&minify=false:64535:59
run
    index.bundle?platform=ios&dev=true&minify=false:64209:28
runApplication
    index.bundle?platform=ios&dev=true&minify=false:64259:28
__callFunction
    index.bundle?platform=ios&dev=true&minify=false:2630:49
<unknown>
    index.bundle?platform=ios&dev=true&minify=false:2407:31
__guard
    index.bundle?platform=ios&dev=true&minify=false:2583:15
callFunctionReturnFlushedQueue
    index.bundle?platform=ios&dev=true&minify=false:2406:21

```

### Expected Behavior

The navigator should render out without error.  

### How to reproduce

- I have a repo where you can get and just run `yarn run ios` to see the error
https://github.com/reedyrm/react-native-bind-undefined

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.11.2 |
| react-native     | 0.56.0 |
| node             | 8.10.0 |
| npm or yarn      | yarn |

**Comment by scttmthsn** [comment]
Seems to be a regression in 2.11.2; rolling back to 2.11.1 resolves it for me.

**Comment by reedyrm** [comment]
On the repo project, I tried bumping the version of react-navigation down to 2.11.1 and I still run into the same issue.

**Comment by brentvatne** [comment]
this appears to be a react-native upstream bug, `this._setComponentRef` does not exist anywhere in the react-navigation codebase
