### ISSUE TITLE
FlatList not re-rendering when using goBack with StackNavigator

### ISSUE THREAD

**Issue by kyunkakata** [react-navigation/react-navigation#4831]
Here is my FlatList
<FlatList
          removeClippedSubviews={false}
          data={this.state.meals_MAIN}
          showsVerticalScrollIndicator
          numColumns={3}
          extraData={this.state.meals_MAIN}
          renderItem={({item}) => 
            <MenuListItem 
              id={item.id}
              image={item.image}
              name={item.name}
              amount={item.amount}
              desc={item.desc}
              onPressItem={this._onPressItem}
              onLongPressItem={()=>this._gotoShowItem(item.id)}
              selected={!!this.state.selected.get(item.id)}
              
            />
          }
          keyExtractor={(item) => item.id}
          />
...
handleOnNavigateBack=(foo)=>{
  this.setState({refresh:!this.state.refresh});
  alert('Hello')
  this.setState({refresh:!this.state.refresh});
  
} 
But the flatlist won't re-render.

**Comment by eriveltonelias** [comment]
@kyunkakata did you try to add [extraData](https://facebook.github.io/react-native/docs/flatlist#extradata) prop on FlatList?

**Comment by neilhamilton** [comment]
The FlatList will only re-render if the data or extraData changes. I would leave the `this.state. meals_MAIN` as the data prop and then pass the `this.state.refresh` as the extraData prop.

**Comment by kyunkakata** [comment]
@neilhamilton  how to pass this.props.navigation.isFocused() to the extraData.

**Comment by neilhamilton** [comment]
@kyunkakata just replace this.state.meals_MAIN in extra data with this.props.navigation.isFocused(). isFocused returns a boolean value. So if you want to only re-render when the screen becomes focused you could try:

<FlatList\
...\
extraData={this.props.navigation.isFocused === true}\
... >

**Comment by kyunkakata** [comment]
@neilhamilton  I have try, but it didn't re-render, i don't know what is wrong with it...

**Comment by kyunkakata** [comment]
@neilhamilton  Thank you. I solved it. Thank you very much.
