### ISSUE TITLE
No activeTabStyle for createMaterialTopTabNavigator

### ISSUE THREAD

**Issue by RitikPatni** [react-navigation/react-navigation#4832]
### Current Behavior

*My Code*
``` 
 tabBarOptions: {
    activeTintColor: '#fff',
    inactiveTintColor: '#fff',
    showLabel: true,
    upperCaseLabel: false,
     tabStyle: {
       backgroundColor: '#5A5F68',
       borderRadius: 30,
       height: 31,
     },
    style: {
      backgroundColor: '#fff',
      shadowColor: '#fff',
      shadowOffset: {
        width: 0,
        height: 0,
      },
      shadowOpacity: 0,
      shadowRadius: 0,
      elevation: 0,
    },
    indicatorStyle: {
      backgroundColor: '#fff',
    },
    labelStyle: {
      fontFamily: 'montserratSemiBold',
      flexWrap: 'nowrap',
    },
```
and the result I achieved was this
![screenshot_20180808-222236](https://user-images.githubusercontent.com/16117262/43876397-777eecbc-9bb2-11e8-9c8d-01ca72d23df7.png)

### Expected Behavior

- I expected that the other two tabs will have a white background something like this
![annotation 1](https://user-images.githubusercontent.com/16117262/43876450-b7a5a9f2-9bb2-11e8-9033-74e50b937808.png)

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^2.0.4
| react-native     | 55.0.4
| node             | 8.10
| npm or yarn      | 5.60

**Comment by eriveltonelias** [comment]
Hi @RitikPatni Can you reproduce that on https://snack.expo.io/ ?

**Comment by RitikPatni** [comment]
@eriveltonelias Here's a snack it's not exactly all mine but I have recreated the createMaterialTopTabNavigator to do the same functionality [https://snack.expo.io/B13tiKqrQ](url)

**Comment by RitikPatni** [comment]
Fixed it by modifying indicatorStyle. Here is the snack preview [Tab Navigator Example](https://snack.expo.io/SJ_5zrJI7)
