### ISSUE TITLE
lazy isn't respected in createMaterialTopTabNavigator 

### ISSUE THREAD

**Issue by greenais** [react-navigation/react-navigation#4833]
### Current Behavior
I have this TabBar inside StackNavigator

```
export const Week= createMaterialTopTabNavigator(
  {
    Day0: Day0,
    Day1: Day1,
    Day2: Day2,
   //...
   Day7
    },
  
  {
    tabBarPosition: 'bottom',
    lazy: true,
    swipeEnabled: true,
    animationEnabled: true,
    initialRouteName: 'Day1',
    optimizationsEnabled: true,
  }
);
```

Days are PureComponents with 
```
componentDidMount() {
    console.log('========== MOUNT Day 3')
    this._getEvents()
  }
```

Once Week is mounted all tabs are mounted and rendered immediately causing massive and costy _getEvents() calls - I can ensure this by console.log above

### Expected Behavior
"lazy - Defaults to false. If true, tabs are rendered only when they are made active or on peek swipe."

### Your Environment
| react-navigation |  2.9.3
| react-native     | 0.55.4

**Comment by charpeni** [comment]
`lazy` and `optimizationsEnabled` options are available from `react-navigation@2.10.0`, please update your version of react-navigation.

**Comment by nebulashine** [comment]
I'm using "react-navigation": "^2.14.2", but still seeing lazy not effective.

My config is:
--------------
tabBarOptions: {
    upperCaseLabel: false,
    pressOpacity: 1,
    swipeEnabled: true,
    lazy: true,
    optimizationsEnabled: true,
  },
--------------

Is there's anything I'm missing to use lazy properly?

Thanks!

**Comment by ALawliet** [comment]
@nebulashine Looks like it should be on the same level as `tabBarOptions` and not inside of it: https://reactnavigation.org/docs/en/tab-navigator.html#tabnavigatorconfig

**Comment by NasreenUstad** [comment]
[https://github.com/react-navigation/react-navigation/issues/4737#issuecomment-691163809](https://github.com/react-navigation/react-navigation/issues/4737#issuecomment-691163809)

Please follow this
