### ISSUE TITLE
Can not pass custom navigation prop to Screen components

### ISSUE THREAD

**Issue by MikhailVolkov350504** [react-navigation/react-navigation#4834]
Hello, everyone! I have faced an issue with custom navigation prop after updating to 2.9.1 version of react-navigation from 2.2.5

I need to dispatch actions from components with custom navigation.dispatch. For that reason I pass custom _navigation prop_ for Navigator:

```javascript
export default function createNavigator(routeConfig) {
  const Navigator = createStackNavigator(routeConfig, navigatorConfig);

  return connect(
    null,
    null,
    (stateProps, dispatchProps, { screenProps, navigation }) =>
      ({
        navigation: {
          ...navigation,
          dispatch: dispatchWrapper(navigation.dispatch)
        },
        screenProps
      })
  )(Navigator);
}
```

```javascript
const RootNavigator = createNavigator({
  Main: { screen: MainScreen },
  SubScreen: { screen: SubScreen },
});
```

It looks like that SceneView gets navigation prop from descriptors. And navigation prop in descriptors was completely changed in MR #4453.
Previously, it was formed taking into account the custom navigation prop, but now it creates completely new navigation prop:
```javascript
const childNavigation = navigation.getChildNavigation(route.key);
```

### Current Behavior
Custom navigation prop is not passed to screen components (latest version of react-navigation after MR #4453)

### Expected Behavior

Custom navigation prop is passed to connected components 

### How to reproduce

I have created a repo where I have reproduced an issue.
You can see in logs that _Navigation/COMPLETE_TRANSITION_ and _TEST_ACTION_ actions are dispatched with custom _navigation.dispatch_ function, but _Navigation/NAVIGATE_ (that is fired on main screen) **is not**

Repo on GitHub: https://github.com/MikhailVolkov350504/react-navigation-issue

Expo: https://expo.io/@mikhail_volkov/react-navigation-issue
![image](https://user-images.githubusercontent.com/14074438/44041629-eeb92dc0-9f26-11e8-9fd7-274ecd7490e0.png)

### Your Environment

| software               | prev version (no issue) | current version (with issue) |
| ----------------- | ----------------------  | --------------------------   |
| react-navigation  | 2.2.5                               | 2.9.1                                       |

**Comment by MikhailVolkov350504** [comment]
@ericvicenti @brentvatne Can you please have a look?

**Comment by ericvicenti** [comment]
Hi, can you please demonstrate this issue without redux integration? We are only able to maintain this core library, and its not clear if the issue is coming from the redux code.

If this cannot be reproduced with react-navigation alone, maybe the issue is in https://github.com/react-navigation/react-navigation-redux-helpers

**Comment by MikhailVolkov350504** [comment]
Hi, @ericvicenti. Sorry for the delay.
I have created a repo that reproduces the issue without redux.

Repo on GitHub: https://github.com/MikhailVolkov350504/react-navigation-issue-no-redux

Expo: https://expo.io/@mikhail_volkov/react-navigation-issue-no-redux
![image](https://user-images.githubusercontent.com/14074438/44041153-c098e670-9f25-11e8-968f-2b096734ab34.png)

In the example you can see that I pass custom navigation prop in Navigator, however Screen components don't get custom prop.

You can read more info in my first comment.

**Comment by SergeyShatter** [comment]
Hi, any updates??

**Comment by Hirurgo** [comment]
have ideas how to temporarily bypass this problem?
