### ISSUE TITLE
Color can't be set on back button

### ISSUE THREAD

**Issue by anchpop** [react-navigation/react-navigation#4840]
### Current Behavior

With this code in the rootstack I would expect a black header, with a white title and white back button:

```
        let RootStack = createStackNavigator(
                ...
                navigationOptions: {
                    headerStyle: {
                        backgroundColor: "#000000",
                    },
                    headerTitleStyle: {
                        color: "#FFFFFF",
                    },
                    headerBackTitleStyle: {
                        color: "#FFFFFF",
                    }
         }
```

But the back button retains its default black color, making it invisible

| software         | version
| ---------------- | -------
| react-navigation | latest
| react-native     | latest
| node             | v10.8.0
|  yarn      | 1.9.4

**Comment by DanNeenan** [comment]
I ran into this issue too, using `headerTintColor` seems to change the colour of the default back button. Try 
```
    navigationOptions: {
      headerTitle: Header,
      headerStyle: {
        // header styling
      },
      headerTintColor: 'white'
    }
```

**Comment by vonovak** [comment]
closing as resolved

**Comment by anchpop** [comment]
@DanNeenan many thanks 👍

**Comment by LZQdingyuan** [comment]
我也遇到了同样的问题
