### ISSUE TITLE
can't use swipeEnabled and animationEnabled when i use command createBottomTabNavigator

### ISSUE THREAD

**Issue by daniel031699** [react-navigation/react-navigation#4841]
### Current Behavior

- What code are you running and what is happening?
i want to use swipeEnabled and animationEnabled in command createBottomTabNavigator
- Include a screenshot if it makes sense.
![image](https://user-images.githubusercontent.com/15700134/43993951-7fa47882-9dc7-11e8-9407-7e1c94ad69f0.png)

### Expected Behavior

- What do you expect should be happening?
i want to Switch pages with gestures by set swipeEnabled and animationEnabled,but it not work

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |2.9.1
| react-native     |0.55.4
| node             |8.11.1
| npm or yarn      |1.9.2

**Comment by brentvatne** [comment]
this isn't supported on bottom tab navigator, you can use top tab navigator and position it to the bottom if you like
