### ISSUE TITLE
Using non-native animated modules in transitionConfig screenInterpolator

### ISSUE THREAD

**Issue by Ketn** [react-navigation/react-navigation#4845]
As given in the documentation [here](https://reactnavigation.org/docs/en/stack-navigator.html#modal-stacknavigator-with-custom-screen-transitions), we can play with opacity and translation props to create a custom transition. However, I have a requirement to play with a non-native animated module: borderRadius i.e. the border Radius goes from a certain value to 0 as the transition takes place.

### Current Behavior

I'm receiving the error that "borderRadius" is not a native animated module.

### Expected Behavior

I want to use this non-native animated module without the native driver being involved. Is there any way to enable transition screenInterpolation for non-native modules?

### How to reproduce

```
transitionConfig: () => ({
  transitionSpec: {
      duration: 300,
      easing: Easing.out(Easing.poly(4)),
      timing: Animated.timing,
  },
  screenInterpolator: sceneProps => {
      const { layout, position, scene } = sceneProps;
      const { index } = scene;

      console.log("layout",layout);

      const height = layout.initHeight;
      const translateY = position.interpolate({
          inputRange: [index - 1, index, index + 1],
          outputRange: [height, 0, 0],
      });

      const opacity = position.interpolate({
          inputRange: [index - 1, index - 0.99, index],
          outputRange: [0, 1, 1],
      });

      const borderRadius = layout.interpolate({
          inputRange: [index - 1, index - 0.99, index],
          outputRange: [Values.ScreenWidth/2, 0, 0],
      });

      return { opacity, transform: [{ translateY }], borderRadius };
  },
}),
```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.6.2
| react-native     | 0.53.3
| node             | 10.7.0
| yarn      | 1.7.0

**Comment by brentvatne** [comment]
soon we will be moving away from using animated here and will use reanimated instead, this supports every property and will resolve this issue
