### ISSUE TITLE
Introducing 'react-navigation-collapsible'. Make your header collapsible.

### ISSUE THREAD

**Issue by benevbright** [react-navigation/react-navigation#4846]
![demo](https://user-images.githubusercontent.com/916690/44006654-00add8ae-9e88-11e8-98d4-4cf6adf1fff2.gif)

Hi all, I just made and published `react-navigation-collapsible` module. It’s HOC component, so you can make your current `react-navigation` collapsible by adding only a few lines. 
https://medium.com/@brightlee/introducing-react-navigation-collapsible-3ff80ac097a

**Comment by DISKONEKTeD** [comment]
I tried implementing something myself a bit back and it always gave me issues. So this is a pleasant surprise to see. I'll definitely be checking out. Thank you.

**Comment by eriveltonelias** [comment]
Hi @benevbright, thanks for your awesome library. Looks great :) 

@brentvatne  @ericvicenti since isn't an issue on react-navigation, can we close this?

**Comment by benevbright** [comment]
Oh yes sure.
