### ISSUE TITLE
What does `navigation.back` really do? It doesn't unmount component

### ISSUE THREAD

**Issue by wzup** [react-navigation/react-navigation#4848]
### Current Behavior

When I do any of these actions, I expect current component (the one I navigate from) to be unmounted completely. It means if I return to the component back right away its `componentWillMount` and `componentDidMount` are called like for a brand new component. But it doesn't.

When I return to component its state is the same it was before I navigated back from it.
Texts fields are not changed.

```javascript
// all these actions should UNmount component completely

this.props.navigation.goBack(null);
this.props.navigation.dispatch( NavigationActions.back({key:null}) );
this.props.navigation.pop();
```

### Expected Behavior

Current components unmounts completely on any `back` action.

How to achieve it?

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.5.8
| react-native     |0.54.2
| node             |8.11.3
| npm or yarn      |5.6.0

**Comment by nol13** [comment]
Any way to have explicit control over this behavior?

**Comment by brentvatne** [comment]
it depends what navigator you use, the behavior can change. stack will behave as you expect. tabs will retain the state. switch doesn't support back by default even. also, we don't take issues against old versions of react-navigation, please file a new issue with more info and against version 2.11.2 or greater and i'd be happy to look! :)

**Comment by brentvatne** [comment]
@nol13 - in the case of tabs where state is retained you can subscribe to focus events and do whatever you want when it's blurred/focused

**Comment by nol13** [comment]
Thanks. Ya I guess on 2nd look my case is a little different, but that's more or less where I'm at.

Have a stack navigator with potentially multiple instances of a screen containing a connected component, where we would want to keep it mounted if navigating to another screen, but unmount when navigating to a new instance of the connected screen. Mostly to avoid extra rendering but also had some stuff running on didMount. Now checking key of previous screen on focus event, and added in..

`
shouldComponentUpdate(nextProps) {
    return nextProps.navigation.isFocused();
  }
`

Still not 100% sure if the timings are guaranteed correct, but seems to be working reliably.

**Comment by Aryk** [comment]
Is there any way to keep a screen mounted? For a example a chat window that you want to constantly come back to?
