### ISSUE TITLE
undefined is not an object (evaluating '_TabRouter.default')

### ISSUE THREAD

**Issue by DISKONEKTeD** [react-navigation/react-navigation#4850]
### Current Behavior
I can't find a thread that references the following. My code / app works fine when in JS Dev Mode, but as soon as I disable it on my android phone, i get this: 

**undefined is not an object (evaluating '_TabRouter.default')**

![Image of Error](https://i.imgur.com/WvIX1dh.jpg)

### Expected Behavior

For the app to load lol.

### How to reproduce

I'm not sure how to. I tried removing all the routes I had set up:

switch > drawer > stack > tabs > the first tab is another set of tabs and then finally just screens

I switch it all out for just one of the screens and it still does this error, even on one simple screen is placed as the sole root. So I'm wondering if this is actually related to something in the module itself? or is it something with babel or what?

I did create a two custom tabs, I don't know if that would cause any of this. But I literally copied the code from the module itself a bit back ( i think it no longer is in version 2). All i did was modify it, in order to add a drop down menu for one, and the other I just added a "+" or  "create" button, which just pops up a stack screen to create a post. 

Should i actually delete any file that references tabs to see what happens? Or is it actually related to the drawer navigator?
  
### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.5.12
| react-native     |  0.56.0
| node             | v8.9.4
| npm       | 5.10.0

These are all my dependencies:

  "dependencies": {
    "axios": "^0.18.0",
    "immutability-helper": "^2.7.1",
    "moment": "^2.22.2",
    "npm": "^5.10.0",
    "prop-types": "^15.6.2",
    "react": "^16.4.1",
    "react-native": "^0.56.0",
    "react-native-extended-stylesheet": "^0.8.1",
    "react-native-material-dropdown": "^0.11.1",
    "react-native-modal": "^5.4.0",
    "react-native-vector-icons": "^4.5.0",
    "react-navigation": "^1.5.12",
    "react-redux": "^5.0.7",
    "redux": "^3.7.2",
    "redux-saga": "^0.16.0"
  },
  "devDependencies": {
    "@babel/core": "^7.0.0-beta.41",
    "babel-eslint": "^8.2.6",
    "babel-jest": "22.1.0",
    "babel-preset-react-native": "^5.0.0",
    "eslint": "^4.19.1",
    "eslint-config-airbnb": "^16.1.0",
    "eslint-plugin-import": "^2.13.0",
    "eslint-plugin-jsx-a11y": "^6.1.1",
    "eslint-plugin-react": "^7.10.0",
    "jest": "22.1.4",
    "prettier-eslint": "^8.8.2",
    "react-test-renderer": "16.2.0"

**Comment by DISKONEKTeD** [comment]
nevermind, i decided to just upgrade to version 2. seems to have gone away.

**Comment by damrem** [comment]
Hi, same issue here.

But upgrading `react-navigation` along with `react-native`+`babel` is not an option for me right now, I have to stick to `1.5.x`.

Commit [#103f448](https://github.com/react-navigation/react-navigation/commit/103f4488835ec9201a6e8f143e4f5a39fa905f3f) fixes it, but has not been released yet.

Instead of referencing this specific commit in project deps, could maintainers please publish a patch?
