### ISSUE TITLE
Tapping back fast enough in a stack navigator will remount a previously unmounted component

### ISSUE THREAD

**Issue by danielmartinprieto** [react-navigation/react-navigation#4851]
We were experiencing an issue using a stack navigator in our project and we were able to reproduce it in a minimal example in this [snack](https://snack.expo.io/@danielmartin/remounted-component) (check the logs!), where a popped component is being remounted only if the user presses `Back` fast enough.

If we use a stack navigator to show three components `A -> B -> C` with a default header, when going back in the stack it works fine. If we use a custom header with a back button implemented just calling `navigation.pop()`, the user can tap on it twice faster than with the default header, producing a weird effect where the third component `C` is mounted and then unmounted again (even though it was already unmounted as one would expect).

Note that if the user doesn't tap `Back` fast, the problem doesn't appear, but in order to reproduce it, the tapping doesn't need to be unrealistically fast, and actually this is something that's happening quite often in our application right now.

**Comment by eriveltonelias** [comment]
Hi @danielmartinprieto! 

Thanks for the report, this issue is related with https://github.com/react-navigation/react-navigation/issues/5152

**Comment by xiJieGuYuan** [comment]
0.57 me too
