### ISSUE TITLE
Standard header is too high and back button hides when header is small

### ISSUE THREAD

**Issue by vatex** [react-navigation/react-navigation#4852]
Hello,

Firstly I just enabled header:
![39080774_1168831506609047_1768132718870134784_n](https://user-images.githubusercontent.com/12797806/44055490-97927512-9f56-11e8-8a2a-ae8e9ea7fc20.png)

It's really high, then I tried to make it small but when it's small, then back button hides and can anyone help me?

I started working on react native yesterday and I have latest version of depencencies.

Thanks

**Comment by eriveltonelias** [comment]
Hi @vatex! 

Can you reproduce part of your code on https://snack.expo.io ?

**Comment by vatex** [comment]
Hi @eriveltonelias!

I couldn't find any import option on snack.expo.io, so I can give you access on my repository, it's really big and I'm not able to move whole code on snack.expo.io

Thanks!

**Comment by vatex** [comment]
Hi @eriveltonelias!

I found a solution :3 
https://github.com/react-navigation/react-navigation/issues/3522#issuecomment-365718266

I've never seen in docs about that requirement...

Thanks!

**Comment by eriveltonelias** [comment]
@vatex Cool! :)
