### ISSUE TITLE
Push multiple routes at once in StackActions

### ISSUE THREAD

**Issue by AkilLis** [react-navigation/react-navigation#4855]
Hello there i have a question about:

What am i trying to achieve is something draft scenes and after loading all those scenes

Push multiple routes at once in StackActions
I tried two different methods but it doesn't work for me
1. dispatch NavigationActions few times then only first route affected.
2. Inside the saga same as well

it seems to me this problem related to [this](https://github.com/react-navigation/react-navigation/issues/1206)

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.0.4
| react-native     | .  0.55.4
| node             |
| npm or yarn      | . yarn

**Comment by brentvatne** [comment]
hi there! this is a question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.

**Comment by kemicofa** [comment]
This is actually well [documented](https://reactnavigation.org/docs/en/stack-actions.html#how-to-use-the-index-parameter)

> How to use the index parameter
> The index param is used to specify the current active route.
> 
> eg: given a basic stack navigation with two routes Profile and Settings. To reset the state to a point where the active screen was Settings but have it stacked on top of a Profile screen, you would do the following:

```
import { StackActions, NavigationActions } from 'react-navigation';

const resetAction = StackActions.reset({
  index: 1,
  actions: [
    NavigationActions.navigate({ routeName: 'Profile' }),
    NavigationActions.navigate({ routeName: 'Settings' }),
  ],
});
this.props.navigation.dispatch(resetAction);
```

**Comment by kylanhurt** [comment]
Is there a way to do this to a sibling / neighbor stack navigator?

**Comment by gyani-sunkara** [comment]
Is there a way to push multiple routes without resting the stack?

**Comment by raajnadar** [comment]
@gyani-sunkara you can read the docs, https://reactnavigation.org/docs/navigation-actions#reset

We have an example showing how to get the previous navigation state from `navigation.dispatch` & appending new screens
