### ISSUE TITLE
Navigating to the first component in a stack navigator with params doesn't work correctly

### ISSUE THREAD

**Issue by bdzim** [react-navigation/react-navigation#4858]
### Current Behavior

The first time I navigate to a component in a stack navigator with params it's mounted twice. The first time it's mounted without params. 

If I go back I'm taken to the component without params. So I have to press back twice to get back to where I was even though I only navigated once. 

### Expected Behavior

- When navigating to a component with params the component should be loaded once with params. 
- After navigating I should only need to go back once to get back to where i was. 

### How to reproduce
I have a component within a StackNavigator that I always want to pass params to. This doesn't seem to work if my component is the first component loaded in a StackNavigator. Here's some code that illustrates the problem.

- I start in component A. 
- I press the button to navigate to component B. 
- In the logs you can see that component B is loaded twice. The first time it's loaded without params.

    Android SDK built for x86: rendering with: undefined
    
    Android SDK built for x86: rendering with: ►{data:"from A"}

- Also if you click the device back button it goes back to the screen with undefined params.

So there are two issues:

 1. I only navigated once, but I have to go back twice to get back to where I was.
 2. My component is loaded with no params even though I navigated with params.

Here's the code running in an expo snack: https://snack.expo.io/@bdzim/navigate-to-tab-from-parent

    class A extends React.Component {
      render() {
        return (
          <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
            <Button
              title="This is A. Press to go to B"
              onPress={() => this.props.navigation.navigate(
                'B',  { data: 'from A' }
                )}
            />
          </View>
        );
      }
    }
    
    class B extends React.Component {
      render() {
        console.log('rendering with: ', this.props.navigation.state.params)
        let params = JSON.stringify(this.props.navigation.state.params)
        return (
          <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
            <Text>
              params: {params}
            </Text>
            <Button
              title="This is.. B! Press to go to A"
              onPress={() => this.props.navigation.navigate('A')}
            />
          </View>
        );
      }
    }
    
    const Stacks = StackNavigator({ B })
    const Tabs = TabNavigator({ A, Stacks });

**Comment by eriveltonelias** [comment]
Hi @bdzim! 

I think that you're using an old version of [react-navigation](https://www.npmjs.com/package/react-navigation), did you tried to get the last?

**Comment by brentvatne** [comment]
as @eriveltonelias pointed out, it looks like the version of react-navigation that you're using in this example is quite old. I updated it to latest here: https://snack.expo.io/SJ8CffcIQ - if you run this you'll see that it's no longer a problem :)
