### ISSUE TITLE
Can't manipulate the state of the previous tab in tabBarOnPress

### ISSUE THREAD

**Issue by lukasgjetting** [react-navigation/react-navigation#4859]
### Overview

A TabNavigator with each tab having their own StackNavigator seems to be pretty standard. `tabBarOnPress` is offered as a way to handle what happens when a tab is pressed - great! This can be used to reset the child stack navigator of the tab being navigated to. However, there is currently no way to reset the stack navigator of the tab being navigated away from. As I see it, this could be fixed by re-adding the `previousScene` (or something like it) as a parameter to `tabBarOnPress`.

This has been discussed in #4164 where it was concluded that `navigation` does the same thing as `scene` and `jumpToIndex`. Seems right. However, the only mention of why `previousScene` was removed, is @satya164's comment [here](https://github.com/react-navigation/react-navigation/issues/4164#issuecomment-388076206). It is mentioned that there are focus events that can be used instead - however, the linked pull request [#2790](https://github.com/react-navigation/react-navigation/pull/2790) doesn't mention them?

If the events in question are the `willFocus`/`willBlur`/etc. that can be subscribed to in a screen component via `navigation.addListener`, I don't think it's going to work. These events will also be called when navigating to a new screen in the tab's StackNavigator.

### Current Behavior

`tabBarOnPress` is called only with `navigation` and `defaultHandler`. This makes it impossible to do things to the previous tab's navigator. For example `popToTop`.

### Expected Behavior

`tabBarOnPress` should be called with an additional parameter `previousScene` (like in previous versions) so we can manipulate the previous tab's child navigator.

### How to reproduce

Implement `tabBarOnPress` in `navigationOptions` of `TabNavigatorConfig`.

````
const MainTabsNavigatorConfig = {
  navigationOptions: () => ({
    tabBarOnPress: ({ navigation, defaultHandler }) => {
      // Do stuff
    },
  }),
};

const MainTabs = createBottomTabNavigator(MainTabsRouteConfigs, MainTabsNavigatorConfig);
````

Inside `tabBarOnPress` we can `popToTop` like so.

````
tabBarOnPress: ({ navigation, defaultHandler }) => {
  if(navigation.state.index > 0) {
    navigation.dispatch(StackActions.popToTop());
  }
  defaultHandler();
},
````

However, this pops the tab we're navigating *to*, not the one we're navigating *from*.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.9.0
| react-native     | 0.55.4
| node             | v8.11.1
| npm | 5.6.0

Thanks in advance, guys. Keep up the great work!

**Comment by satya164** [comment]
> However, this pops the tab we're navigating to, not the one we're navigating from.

The `navigation` prop refers to the current tab, which is the "previous tab" since the navigation only happens after you call `defaultHandler`.

**Comment by lukasgjetting** [comment]
@satya164 Thanks for the quick response!

That's what I thought too. I don't think that's how it is, though.

1) Calling `popToTop` before `defaultHandler` still pops the soon-to-be current tab.

2) Doing the following:  
````
tabBarOnPress: ({ navigation: onPressNavigation, defaultHandler }) => {
  console.log('navigation', onPressNavigation);
  defaultHandler();
  console.log('navigation2', onPressNavigation);
},
````

Logs the following:

![alt text](https://i.imgur.com/6hYRm28.png "navigation")

![alt text](https://imgur.com/e9zwl93.png "navigation2")

Where `Favorites` is the tab being navigated to

**Comment by satya164** [comment]
The current tab means the tab where you have `tabBarOnPress` specified. If you specify it in the `Favorites` tab, then it'll refer to the `Favorites` tab. Maybe we can change it to refer to the currently focused tab instead.

**Comment by lukasgjetting** [comment]
I currently define it the navigationOptions of TabNavigatorConfig, like so:

````
const MainTabsNavigatorConfig = {
  navigationOptions: () => ({
    tabBarOnPress: ({ navigation, defaultHandler }) => {
      // Do stuff
    },
  }),
};

const MainTabs = createBottomTabNavigator(MainTabsRouteConfigs, MainTabsNavigatorConfig);
````

So the navigationOptions function is called for each tab, which means that each tab owns their own tab icon (and with that, the "tabBarOnPress"). Therefore, `navigation` will always refer to the tab icon being pressed..

I like your idea of changing it, so the `navigation` argument refers to the currently active tab. However, this might create issues with calling `defaultHandler` in the middle of the function? We can't just change the whole `navigation`-object, right?

Maybe a parameter `previousNavigation` which refers to the navigation prop of the tab we're navigating from?

I don't think I'm familiar enough with the code behind the scenes to tell if any of these suggestions will have unexpected consequences.

**Comment by lukasgjetting** [comment]
@satya164 What are your thoughts on this? I don't think I'm familiar enough with the code behind the scenes to tell if any of these suggestions will have unexpected consequences.

**Comment by eriveltonelias** [comment]
Hi @lukasgjetting, 

Maybe it can help you https://github.com/react-navigation/react-navigation/issues/4390#issuecomment-394505165

**Comment by lukasgjetting** [comment]
@eriveltonelias Thank you so much! It worked perfectly. :1st_place_medal:
