### ISSUE TITLE
Nested stack gets reset

### ISSUE THREAD

**Issue by fbn4sc** [react-navigation/react-navigation#4860]
### Current Behavior

I'm trying to replicate Netflix's Android navigation and for that I have a stack navigator with two nested stack navigators.

The issue I'm facing is that, when going back to a stack its state gets reset.

![bug](https://user-images.githubusercontent.com/35103234/44154630-8823797e-a081-11e8-90e6-83dd7215f9f8.gif)

### Expected Behavior

In my example, AuthorsStack should not transition back to its first screen.

### How to reproduce

Here is my navigation structure:

`const tabNavigator = createBottomTabNavigator({
  VideosStack: { screen: VideossStack },
  AuthorsStack: { screen: AuthorsStack }
});`

`const AuthorsStack = createStackNavigator({ AuthorsPage, AuthorDetailsPage });`

`const VideossStack = createStackNavigator({ CoversPage, CourseDetailsPage });`

### Your Environment

I'm using:

- react-native: 0.55.4
- react-navigation: ^2.3.0

**Comment by fbn4sc** [comment]
I was trying to get around the issue and found this:

![bug2](https://user-images.githubusercontent.com/35103234/44165742-e8284e80-a09f-11e8-9f66-130b71c4970d.gif)

After reaching "ThirdStack/LevelTwo" the order should be

1. "ThirdStack/LevelOne"
2. "SecondStack/LevelTwo"
3. "SecondStack/LevelOne"
4. "FirstStack/LevelOne"

**Comment by eriveltonelias** [comment]
Hi @fbn4sc! 

Can you reproduce your issue on https://snack.expo.io/ ?

**Comment by eriveltonelias** [comment]
Hi @fbn4sc! 

I'll close this, let me know if you still need help.
