### ISSUE TITLE
Cannot `navigate.goBack` in parent of Drawer Stack

### ISSUE THREAD

**Issue by jjenzz** [react-navigation/react-navigation#4864]
### Current Behavior

When a Drawer Navigator is a child of a Stack Navigator, calling `navigate.goBack` from within the Stack Navigator's `navigationOptions` does not go back in the Drawer Stack.

### Expected Behavior

I expected to be able to go back in the Drawer Stack when triggered from the parent Stack Navigator. This may be an incorrect expectation. If so, how would I create a Drawer that sits below the header while maintaining the stack?

### How to reproduce

https://snack.expo.io/r1pL3AfLQ

- Click "About" button
- Click "Back" button in header of about screen

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.9.3
| react-native     | 0.55.2
| node             | 10.3.0
| npm or yarn      | yarn

**Comment by eriveltonelias** [comment]
Hi @jjenzz! 

https://snack.expo.io/HJLLs0SIQ

You can also find this example on https://github.com/react-navigation/react-navigation/blob/master/examples/NavigationPlayground/js/Drawer.js

**Comment by jjenzz** [comment]
@eriveltonelias Thank you for taking the time to respond. That doesn't meet the following requirement though unfortunately:

> create a Drawer that sits below the header 

See how in my example, opening the drawer makes it appear below the header: https://snack.expo.io/SJt66ZdUX

Perhaps I am attempting something that is not possible currently?

**Comment by eriveltonelias** [comment]
@jjenzz I see. 
I created a new example: https://snack.expo.io/rkoSB4_Lm   I think that can help you.

**Comment by brentvatne** [comment]
another option here is to use `goBack(null)` - https://snack.expo.io/rkOC2b5Um

`goBack()` and `goBack(null)` are quite confusing still and we're having a hard time thinking of how to improve this api. `goBack()` dispatches an action to go back from the key for the navigation object that it's called on. in this case that would be on the stack navigator. but what we actually want is to just go back on the first navigator that will handle the back action, to do this we pass in `null` as the key.

**Comment by eriveltonelias** [comment]
Hi @jjenzz! I'll close this. Tell us if still need help.
