### ISSUE TITLE
Weird space on the left component of the header using navigationOptions (doesn't match right side)

### ISSUE THREAD

**Issue by kev2316** [react-navigation/react-navigation#4868]
### Current Behavior

```
static navigationOptions = {
		//header: null,
		headerLeft: (<HomeScreenSearchHeaderButton onPress={() => self.setState({ search: !self.state.search })} />),
		//headerStyle: { backgroundColor: '#f4511e', },
		headerBackImage: null,
		title: "Feed",
		headerTitleStyle: styles.headerTitleStyle,
		headerRight: (<HomeScreenFilterHeaderButton onPress={() => self.setState({ showModal: true })} />)
	};
```

### Expected Behavior

For the Button that gets aligned to the right properly towards the edge of the screen, to match that of the left, but there is space between the left and the edge that is unaccounted for. 

### How to reproduce

Using the code above in any header, I think you will notice with no other properties in my buttons other than width 100% that the spacing on each side is not the same. 

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | "^1.5.11"
| react-native     | 28.0.0
| node             | 10.5.0
| npm or yarn      | 6.1.0

**Comment by eriveltonelias** [comment]
Hi @kev2316! 

Can you reproduce a minimal example on https://snack.expo.io ?

**Comment by brentvatne** [comment]
additionally, this is for an old version of react-navigation that we don't provide fixes for unless they're essential. i recommend updating to the latest version
