### ISSUE TITLE
Wrong transition for BottomTabNavigator after closing a modal screen from StackNavigator container

### ISSUE THREAD

**Issue by alexandrecanuto** [react-navigation/react-navigation#4873]
### Current Behavior

**Problem:** I have a StackNavigator with `mode: modal` that holds a TabNavigator and a standalone screen. Navigating between tabs work properly, but after I navigate to the standalone modal screen and back, the first tab navigation uses the modal transition animation.

GIF of the problem:
![ezgif-3-111d78bab4](https://user-images.githubusercontent.com/6773794/44354959-a1609d00-a481-11e8-88f6-6a295bb364e7.gif)

### Expected Behavior

TabNavigator should use non-modal transition animation when navigating between tabs.

### How to reproduce

```
const TabNavigator = createBottomTabNavigator({
  TabA,
  TabB,
});

const StackNavigator = createStackNavigator({
  TabNavigator,
  ModalScreen,
}, {
  mode: 'modal'
});
```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^2.2.2
| react-native     | 0.55.4
| node             | v6.11.1
| npm or yarn      | yarn 1.3.2

**Comment by vonovak** [comment]
hi! Thanks for reporting. It is unclear whether `TabA` and `TabB` are screen components or stack navigators (that may be a workaround). Can you create a reproducible demo on https://snack.expo.io/?

**Comment by alexandrecanuto** [comment]
Hey, @vonovak, thanks for replying. They are other stack navigators, yes!
I've tried to reproduce my problem as best as I could on Snack, but it doesn't seem to happen there: https://snack.expo.io/SytyuRY87

What I have tried so far:
- Switching between `goBack()`, `goBack(null)` and `goBack(navigation.state.key)` inside the Header component;
- Removing `{...headerProps}` from the Header component;
- Removing `LayoutAnimation.configureNext` inside the ModalScreen (I animate a View inside the ModalScreen when the keyboard appears / disappears).
- Setting `mode: card` inside TabNavigator, TabA and TabB.

**Comment by brentvatne** [comment]
hey @alexandrecanuto! that's indeed quite strange! please ping me again when you manage to get it reproducing in a minimal setup (snack or otherwise)

**Comment by lapto** [comment]
Seen the same thing before and it's usually caused by a component that calls LayoutAnimation.configureNext.  @alexandrecanuto In your case, do you have eventlistener on keyboard that trigger LayoutAnimation?

I updated your example to force the glitch to occur. (Just make sure you have triggered the modal before the timer on greenpage kicks inn)

https://snack.expo.io/Hk57Y4yT7

**Comment by brentvatne** [comment]
nothing we can do here about LayoutAnimation unfortunately, it's a global API and it'll impact any state change in the frame that it's called in. i'd recommend staying away from it if this is a concern for you

**Comment by alexandrecanuto** [comment]
Thanks for the reproduction, @lapto ! We are still having this issue and, at least for now, it's in backlog since it's not that big of a deal.

Shame to see it won't have a fix, since it's not a proper bug, but... at least now I can explain it better when it comes up again, and explain we have to tone down LayoutAnimation use.
