### ISSUE TITLE
Problems using Header with React Navigation + Native Base

### ISSUE THREAD

**Issue by gcmatheusj** [react-navigation/react-navigation#4874]
Current Behavior

I'm trying to create a header with a menu button using the native-base component Header, but I'm having problems,
if I use headerMode: 'none' and static navigatioOptions = {header: null} in the other screen the header looks like this:

![desktop screenshot 2018 08 20 - 15 37 10 40](https://user-images.githubusercontent.com/38117213/44363994-3b354380-a49c-11e8-94d2-3585cb4fbd80.png)

If I remove the headerMode: 'none', the screen looks like this:

![desktop screenshot 2018 08 20 - 15 43 31 28](https://user-images.githubusercontent.com/38117213/44364130-96673600-a49c-11e8-8ed8-ed21c07c6c53.png)

And I get a header on the login screen, but I do not want any header on the login screen, only on the following screens.

--- App.js
import React, { Component } from 'react'
import { StyleSheet } from 'react-native'
import { createStackNavigator } from 'react-navigation'

import LoginScreen from './src/components/login/Login'
import HomeScreen from './src/components/home/Home'

export default class App extends Component {

  render() {
    return (
      <AppStackNavigator/>
    )
  }
}

const AppStackNavigator = createStackNavigator({
  Login: LoginScreen,
  Home: HomeScreen
},
{
  headerMode: 'none'
},
  {
    navigationOptions: {
      headerStyle: {
        backgroundColor: '#00CAC9',
      },
    }
  }
)

--- Login.js
import React, { Component } from 'react'
import { StyleSheet, View, Text, TextInput, Button, Image, ScrollView, TouchableOpacity } from 'react-native'
import { createStackNavigator } from 'react-navigation'

import logo from '../../assets/consulte-aqui.png'

class LoginScreen extends Component {

    static navigationOptions = {
        header: null, 
    }

    render() {
        return (
            <ScrollView>
                <View style={styles.container}>
                    <View style={styles.logoContainer}>
                        <Image
                            style={styles.logo}
                            source={logo}
                        />
                    </View>
                    <View style={styles.formContainer}>
                        <TextInput
                            placeholder="Usuário ou Email"
                            placeholderTextColor="rgba(255,255,255,0.7)"
                            style={styles.input}
                        />
                        <TextInput
                            placeholder="Senha"
                            placeholderTextColor="rgba(255,255,255,0.7)"
                            style={styles.input}
                        />
                        <Button color='#009094' title="Entrar" onPress={() => this.props.navigation.navigate('Home')} />
                        <TouchableOpacity style={styles.button}>
                            <Text style={styles.txt_es}>ESQUECI MINHA SENHA</Text>
                        </TouchableOpacity>
                    </View>
                </View>
            </ScrollView>
        )
    }
}

--- Home.js
import React, { Component } from 'react'
import { StyleSheet, View, Text } from 'react-native'
import { createStackNavigator, createDrawerNavigator } from 'react-navigation'

import ConsultaScreen from '../consultas/Consultas'
import ExameScreen from '../exames/Exames'

class HomeScreen extends Component {
    static navigationOptions = {
        header: null,  
    }

    render(){
        return(
            <DrawerMenu></DrawerMenu>
        )
    }
}

export default createStackNavigator({
    Home: {
        screen: HomeScreen,
    },
})

const DrawerMenu = createDrawerNavigator({
    Consultas: {
        screen: ConsultaScreen,
    },
    Exames: {
        screen: ExameScreen
    },    
})

Expected Behavior

I just wanted the header with the menu button to appear correctly on the Home component screens.

![navigationdrawerimg](https://user-images.githubusercontent.com/38117213/44364697-0fb35880-a49e-11e8-9a12-a1383780c7ef.gif)

**Comment by brentvatne** [comment]
hi! please post this issue on native-base, we don't handle issue reports where you can't narrow it down to just react-navigation

**Comment by allan-simon** [comment]
@gcmatheusj  did you find a fix for your issue ?

**Comment by sorxrob** [comment]
**UPDATE for React Navigation 5.x**

If you want to use Nativebase's header with react navigation 5, you can do it like this:

```javascript
    import { NavigationContainer } from '@react-navigation/native';
    import { createStackNavigator } from '@react-navigation/stack';
    
    import {
      Header,
      Left,
      Body,
      Title,
      Button,
      Icon,
      View,
      Text
    } from 'native-base';
    
    const Stack = createStackNavigator();
    
    const Home = () => {
        return (
            <View>
                <Text>Hello World</Text>
            </View>
        )
    }
    
    const CustomHeader = ({scene, previous, navigation}) => {
      const {options} = scene.descriptor;
      const title =
        options.headerTitle !== undefined
          ? options.headerTitle
          : options.title !== undefined
          ? options.title
          : scene.route.name;
    
      return (
        <Header>
          <Left>
            {previous ? (
              <Button transparent onPress={navigation.goBack}>
                <Icon name="arrow-back" />
              </Button>
            ) : (
              undefined
            )}
          </Left>
          <Body>
            <Title>{title}</Title>
          </Body>
        </Header>
      );
    };
    
    const App = () => {
        return (
            <NavigationContainer>
                <Stack.Navigator initialRouteName="Home">
                    <Stack.Screen
                    name="Home"
                    component={Home}
                    options={{
                    header: (props) => <CustomHeader {...props} />,
                  }}
                    />
                </Stack.Navigator>
            </NavigationContainer>
        )
    }
```

More of the options here https://reactnavigation.org/docs/en/stack-navigator.html

**Comment by philoskim** [comment]
I solved this problem as follows.

```
   const App = () => {
        return (
            <NavigationContainer>
                <Stack.Navigator initialRouteName="Home"
                                 screenOptions={{headerShown: false}}>
                    <Stack.Screen
                        name="Home"
                        component={Home}
                    />
                </Stack.Navigator>
            </NavigationContainer>
        )
    }
```

**Comment by Jiraphat-X86** [comment]
translucent={false}
