### ISSUE TITLE
Cannot automatically login after updating from apple store or play store

### ISSUE THREAD

**Issue by lilosir** [react-navigation/react-navigation#4879]
Currently I meet a problem, since I uploaded a new package to play store or apple store, it always brought me to the login screen after I updated the app version, instead of bring to the screen i stayed last time. It is working when I close the app, then reopen it.  Any solutions about this? Check the status by adding a splash screen?

### Expected Behavior

Bring the users to the screen where they left last time, after they update the app

**Comment by brentvatne** [comment]
hi! this seems unrelated to react-navigation - presumably you're tracking the signed in state through something like AsyncStorage, but react-navigation has no control over that
