### ISSUE TITLE
Can not specify/define what the display sequence application start-up.

### ISSUE THREAD

**Issue by lc-rod** [react-navigation/react-navigation#4880]
## The issue tracker is reserved for bug reports only.

If you have a question, feature request, or an idea for improving the library or its related tools, please try one of the following resources:

- [Read the documentation](https://reactnavigation.org/)
done
- [Post an issue to the website repository if you'd like to see a documentation change](http://github.com/react-navigation/website)
n/a
- [Post a feature request to Canny](https://react-navigation.canny.io/feature-requests)
n/a
- [Write a RFC if you have ideas for how to implement a feature request](https://github.com/react-navigation/rfcs)
`n/a
- [Get help on Discord chat (#react-navigation on Reactiflux)](https://discord.gg/4xEK3nD) or [on StackOverflow](https://stackoverflow.com/questions/tagged/react-navigation)
`site has problem verifying my account, tried multiple times`
- Search for your issue - it may have already been answered or even fixed in the development branch. However, if you find that an old, closed issue still persists in the latest version, you should open a new issue.
`did not find one`

Bugs with react-navigation must be reproducible *without any external libraries that operate on it*. This means that if you are attempting to use Redux or MobX with it and you think you have found a bug, you must be able to reproduce it without Redux or MobX in this report. Redux related issues belong in [react-navigation-redux-helpers](https://github.com/react-navigation/react-navigation-redux-helpers), and we do not have any first-class integration with MobX at the moment.
the only lib involved is the `react-native-navigation` lib
---

### Current Behavior
problem: 

I have a TabBar with 5 icons in it and want to remove one of the icons. When I remove the  code below by commenting it out and removing any references to icon component in question, any and all links or anything dealing with the icon.
Once I save the changes and reload the simulator/device, the screen sequence now refuses to display the TabBar icons in the familiar sequence but the react-native-navigation now selects the last icon as the startup screen instead of the first icon as was being done before.

The removed icon was the next to the last icon in the sequence and the icon being activated now is the last icon.

Question:

where in or how is the screen sequence define/declared for the tab navigatin sequences?

The following code for a react-native screen was removed by commenting it out.

```
// const ChatStack = StackNavigator(
//   {
//     Home: {
//       screen: Chat,
//     },
//     ChatContacts: { screen: ChatContacts },
//     ChatContent: { screen: ChatContent },
//     ...
//   },
//   {
//     headerMode: 'none',
//   },
// );

```
### Your Environment

| software         | version
| ---------------- | -------
react:              16.4.1
react-native:       0.53.0
react-navigation:   1.2.1
react-redux:        5.0.6
redux:              3.7.2
redux-thunk:        2.2.0
node:               8.11.3
npm:                5.6.0
yarn:               1.9.4
macOS-High Sierra:  10.13.6

**Comment by brentvatne** [comment]
you should use `initialRouteName`. anyhow, this is a question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.
