### ISSUE TITLE
Unexpected delay before COMPLETE_TRANSITION causing problems

### ISSUE THREAD

**Issue by AlexDM0** [react-navigation/react-navigation#4884]
### Current Behavior

- What code are you running and what is happening?

RN 0.53, ios, react-navigation 2.11.2
I noticed that there is a delay after tapping a button to navigate to another screen and it being ready to use (when Navigation/COMPLETE_TRANSITION was called). When navigation from view A to view B the buttons on view B were unresponsive until Navigation/COMPLETE_TRANSITION was called. I timed this and it was around 700ms instead of the 250 you'd expect from this: https://github.com/react-navigation/react-navigation/blob/d746a587b09676c9ac85d64298340fd5cd0df7e4/src/views/Transitioner.js#L9

I put some time checks in your lib and found out that it was because of this waiting for the animation to finish here:
https://github.com/react-navigation/react-navigation/blob/d746a587b09676c9ac85d64298340fd5cd0df7e4/src/views/Transitioner.js#L163

Now for a timing, this should not be a problem, but you're using a Spring:
https://github.com/react-navigation/react-navigation/blob/d746a587b09676c9ac85d64298340fd5cd0df7e4/src/views/StackView/StackViewTransitionConfigs.js#L9
for RN 0.50 and up.

This spring does a lot of tiny tiny movements at the end before it fades out and this causes a delay of 500ms from the expected result. 

I actually noticed this because of a second issue, if you'd like me to make a separate issue for this, let me know and I'll edit this one.

If you navigate from View A to View B, then tap a button in the navbar of view B to go to view C and you do this quick enough that the COMPLETE_TRANSITION for B was not called, then view C animates away and we're back on B. View C is not destroyed however, if you tap the button in the nav bar again you'll see 2 instances of view C stacked on top of eachother.

- Include a screenshot if it makes sense.
  It does not

### Expected Behavior

- What do you expect should be happening?
  COMPLETE_TRANSITION to be fired when the view is on screen and that all touchable buttons work once they are on screen. (also, that COMPLETE_TRANSITION does not bring the view to the front if it is not the currentScene)

- Include a screenshot if it makes sense.
it doesnt

### How to reproduce

If it's not immediately clear I can make an example. Let me know and I'll post one.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.11.2
| react-native     | 0.53
| node             | 8.11
| npm or yarn      | yarn 1.9.4

**Comment by AlexDM0** [comment]
Added reproduction of issue2 here:
https://github.com/AlexDM0/react-navigation-issue1

Sorry it took a while, I only had a few spare hours and I never used your library directly (usually through react-native-router-flux) nor expo :)

**Comment by ericvicenti** [comment]
Hmm, thanks for the detailed explanation and repro!

The spring issue is interesting and I don't know of an easy way to fix it. It does probably merit its own issue though.

Your core issue does make sense to me, and given the complexity of the transitioner code, I'm not entirely surprised. I'm working on a newer version that is much simpler, and will definitely not suffer from this issue. It will, however, be a while before we switch over the StackView implementation. The new Transitioner's first and primary use-case is modals, but I'm definitely designing it with the StackView in mind.

**Comment by AlexDM0** [comment]
I suppose a quick fix for the spring delay would be to tweak it with the options RN has available:
```
overshootClamping: Boolean indiciating whether the spring should be clamped and not bounce. Default false.
restDisplacementThreshold: The threshold of displacement from rest below which the spring should be considered at rest. Default 0.001.
restSpeedThreshold: The speed at which the spring should be considered at rest in pixels per second. Default 0.001.
```
There is a rather easy gain of about 300ms by tweaking this without it looking any different.

The second issue is more tricky... The transitioner seems to have an odd way of calling/updating iteself. This together with the _queuedTransition seems to be a racecondition/mismatch of the state that is being set once there are no more inputs. 

Do you have some sort of ETA for a version that would solve this issue? I'm forced to go back to 1.5.8 due to this, which presents me with working around the issues with the navbar.. (https://github.com/react-navigation/react-navigation/issues/4185)

Cheers

**Comment by iamsoorena** [comment]
finally someone found [underlying issue](https://github.com/react-navigation/react-navigation/issues/3351) to almost a year old problem.

**Comment by AlexDM0** [comment]
I was wondering if there was an update on this behaviour? My usecase seems very standard, any overview that goes to a view with an edit menu would be affected by this.

**Comment by brentvatne** [comment]
hey @AlexDM0, thanks for pushing on this. I'll tweak the rest displacement / speed threshold so it is responsive more quickly

**Comment by brentvatne** [comment]
https://github.com/react-navigation/react-navigation-stack/commit/7eab1628d1a8199b548e908ac188b38368675c88

I played with the iOS settings app and the react-navigation-stack example app side-by-side and the time when the new screen becomes interactive after push is very similar between the two, I couldn't tell the difference.

**Comment by brentvatne** [comment]
the above said, I don't plan on releasing this backported to react-navigation@2.x as we're working on 3.0 right now and will release a beta for it next week

**Comment by AlexDM0** [comment]
Hi Brent,

That’s great to hear! I suppose the changes in v3 are in no way compatible with 2.x so I completely understand not backporting. I hope the guys at react native router flux will update to your v3 branch as it’s what we’re using :).

Thanks for the update and I look forward to v3!

Cheers


________________________________

**Comment by csterwa** [comment]
@brentvatne @AlexDM0 I'm having this same issue where there seems to be delays on all transitions. And at times, my app crashes. I don't think that our code is doing anything interesting in the navigation except I am passing a whole JS object in the `.navigate()`. Is there a way to remove this delay in our codebase using react-navigation@2.x? Thanks.

**Comment by brentvatne** [comment]
@csterwa - please create a new issue with the template fully filled out and mention me on it and i'll be happy to investigate! :)
