### ISSUE TITLE
this.props.navigation.navigate('xxx') not work

### ISSUE THREAD

**Issue by asd8855** [react-navigation/react-navigation#4885]
react-navigation:2.12.0    This method doesn't work
react-navigation:2.0.0-beta.6  This method works

iOS: 11.4
yarn: 1.7.0
npm: 6.4.0

**Comment by asd8855** [comment]
The error is the same

**Comment by sagardvora** [comment]
Even I am getting this issue

**Comment by hrastnik** [comment]
The weird thing is, it works when the remote JS debugger is connected.

**Comment by joeyscarim** [comment]
I'm experiencing this issue also

**Comment by guptaamol** [comment]
Experiencing the same issue.

**Comment by brentvatne** [comment]
seems to have impacted react-native 0.56+, see https://github.com/react-navigation/react-navigation/issues/4886 for more info, update to latest version of react-navigation for fix

**Comment by asd8855** [comment]
It's working fine now
