### ISSUE TITLE
[REGRESSION][iOS] Fatal Exception: RCTFatalException: Unhandled JS Exception: Invariant Violation: Invariant Violation: Invariant Violation: Attempt to get native tag from node not marked as "native" 

### ISSUE THREAD

**Issue by Dallas62** [react-navigation/react-navigation#4886]
Hi!

I'm do not have a reproducible project for this bug, but I found it **ONLY** on **iOS** in **RELEASE** mode.

It's crash when you navigate.

Configuration:
BottomTab + Stack (crash on the root)

In the body:

Scrollview (vertical) => Scrollview (horizontal) => TouchableOpacity
 
---

### Current Behavior

- Crash in 2.12.0:
Fatal Exception: RCTFatalException: Unhandled JS Exception: Invariant Violation: Invariant Violation: Invariant Violation: Attempt to get native tag from node not marked as "native" 

### Expected Behavior

- No crash

### How to reproduce

No informations at the moment...

### Workaround

Roll back to 2.11.2

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.12.0
| react-native     | 0.56.0
| node             | v8.11.2
| yarn          | 1.7.0

**Comment by Dallas62** [comment]
@TingSyuanWang Did you run `yarn add react-navigation@2.11.2` ? Try to reinstall dependencies to remove this message

**Comment by TingSyuanWang** [comment]
Yes, I even tried to delete the node_modules and `yarn` again.
then, try the following command
`rm -rf ios/build/; kill $(lsof -t -i:8081); react-native run-ios`
The error message is identical, too.

**Comment by TingSyuanWang** [comment]
@Dallas62 I try to use link `https://github.com/react-navigation/react-navigation/archive/2.11.2.tar.gz` to replace the `yarn add react-navigation@2.11.2`, it is working, thanks!

**Comment by Dallas62** [comment]
Seems to come from a broken animation:

https://github.com/facebook/react-native/blob/c6b96c0df789717d53ec520ad28ba0ae00db6ec2/Libraries/Animated/src/nodes/AnimatedNode.js#L48

I have no proof, but maybe from:

https://github.com/react-navigation/react-navigation-stack/commit/6a76bf6703726e6aceb5db8fc8ccba2f4e66f326

**Comment by Dallas62** [comment]
@brentvatne Yes it's working on 2.11.2 ;-)

**Comment by brentvatne** [comment]
can you give me some code that causes this crash?

**Comment by brentvatne** [comment]
able to repro it in dev mode on react-native 0.56, didn't test against this version, interesting I suppose they may have been a regression in animated

**Comment by brentvatne** [comment]
the fix here is not obvious because fixing it on 0.56 breaks it on < 0.56....

**Comment by brentvatne** [comment]
ok I disabled a feature that we weren't using yet and that resolved the problem, will try to find underlying cause. install 2.12.1 for fix

**Comment by mjmasn** [comment]
@brentvatne just for reference I don't think this was an iOS-specific or release-build-specific issue - in debug mode we saw the crash on a couple of Android 8.0.0 devices (`Moto Z Play` and `Samsung Galaxy S9+`), although not on a `Galaxy A5 2016` (7.0.0), an `LG Nexus 5X` (8.1.0) or a different `Galaxy S9+` (also 8.0.0) which is a bit weird :thinking:

**Comment by brentvatne** [comment]
yeah I saw it in debug as well

**Comment by brentvatne** [comment]
if anyone is curious, this PR fixes the upstream bug that led to this issue https://github.com/facebook/react-native/pull/20658

**Comment by Stan92** [comment]
Using the latest version (v2.12.1), I have the same issue.
However but it doesn't help, it doesn't crash while the remote JS debugging is active..

**Comment by brentvatne** [comment]
make sure you clean node_modules and reinstall, clear packager cache. if that doesn't fix it then please create a new issue following the issue template
