### ISSUE TITLE
TabBarIcon missing after putting in tabBarVisible

### ISSUE THREAD

**Issue by SkyYap** [react-navigation/react-navigation#4888]
I am trying to hide the bottom TabNavigator on my second screen of createStackNavigator. So basically I make HomeScreen as my first screen then Detail as my second screen. When I implement the tabBarVisible feature inside my HomeStack, the tabBarIcon for my bottom TabNavigator in first screen went gone. 

**### Current Behavior**
 The tabBarIcon in my createBottomTabNavigator is missing. 

```
const HomeStack = createStackNavigator({
Home: HomeScreen,
  Detail: Detail,
});

HomeStack.navigationOptions = {
  tabBarLabel: 'Home',
  tabBarIcon: ({ focused }) => (
    <TabBarIcon
      focused={focused}
      name={
        Platform.OS === 'ios'
          ? `ios-home${focused ? '' : '-outline'}`
          : 'md-home'
      }
    />
  ),
  
};

HomeStack.navigationOptions = ({ navigation }) => {
  let tabBarVisible = true;
  if (navigation.state.index > 0) {
    tabBarVisible = false;
  }

  return {
    tabBarVisible,
  };
};
```

**### Expected Behavior**

Should expected a Home Icon showing in HomeScreen.
![screenshot_1535036262](https://user-images.githubusercontent.com/32660903/44533391-04735d80-a728-11e8-932f-9b236e6e5f75.png)

**### How to reproduce**
By taking out the tabBarVisible components, the Icon is showing as screenshot below.

```
const HomeStack = createStackNavigator({
  Home: HomeScreen,
  Detail: Detail,
});

HomeStack.navigationOptions = {
  tabBarLabel: 'Home',
  tabBarIcon: ({ focused }) => (
    <TabBarIcon
      focused={focused}
      name={
        Platform.OS === 'ios'
          ? `ios-home${focused ? '' : '-outline'}`
          : 'md-home'
      }
    />
  ),
};
```
![screenshot_1535036778](https://user-images.githubusercontent.com/32660903/44533932-2d482280-a729-11e8-97de-45dd5c906795.png)

**### Your Environment**

expo version: 1.0.0
sdkVersion: 28.0.0
react-navigation@2.3.1

**Comment by brentvatne** [comment]
https://reactnavigation.org/docs/en/navigation-options-resolution.html#a-tab-navigator-contains-a-stack-and-you-want-to-hide-the-tab-bar-on-specific-screens
