### ISSUE TITLE
[Question] How to remove one screen from screen-stack?

### ISSUE THREAD

**Issue by YouCii** [react-navigation/react-navigation#4893]
There are three screens: A=>B=>C.
I want to remove the B from screen-stack while going to C from B, in order to return to A when i click back button in C without listener of the back button. 

I have searched the solution for two days. Can anyone help me?

**Comment by TRutte** [comment]
I think without listening or executing a manual function call to the event it is not possible. You have to do a manual action to skip screen B.
this.props.navigation.dispatch(StackActions.pop({n: 2}));

**Comment by YouCii** [comment]
Thanks for your reply. This code should be useful in the listener of back button, but how about the Gesture -Back? Users may see the B screen while right-sliding the C.

I hope that you can understand my words because of my bad English.

**Comment by eliasrodeloso** [comment]
@YouCii in that case, you can disable the gestures in your stack as follows:

```javascript
  {
     ...anotherStackNavigatorConfig,
     navigationOptions: {
      header: props => <AppHeader {...props} />,
      gesturesEnabled: false
    }
  }
    
```

**Comment by brentvatne** [comment]
hi there! this is a question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.

**Comment by YouCii** [comment]
Sorry, but this question appears here because it can't find a solution elsewhere. As a member of the project, do you know how to solve the problem? @brentvatne

**Comment by YouCii** [comment]
This is just a way to circumvent. Is there a listener of Gesture-Back? @eliasrodeloso

**Comment by PragyaSingla** [comment]
I have same required as mentioned above but didn't find any solution. Anyone has any solution. Would be very helpful.
