### ISSUE TITLE
Android swipeEnabled:false not working (v2.12.1)

### ISSUE THREAD

**Issue by dominikeinkemmer** [react-navigation/react-navigation#4894]
### Current Behavior

- What code are you running and what is happening?
The problem I have is on Android (iOS is fine) in the Tab-navigation. Even though I have `gesturesEnabled: false` and `swipeEnabled: false` I can still swipe between the tabs. 

This is a problem because I dynamically remove tab buttons to not show them to the user depending on some data I receive via bluetooth. 

So the user can still navigate by swiping on Android even though he can't see the tab-bar buttons for those screens.

**The following code shows my navigation configuration setup:**

initial stack-navigator:
```typescript
createStackNavigator(AppRouteConfigs, {
    headerMode: 'float',
    navigationOptions: {
        gesturesEnabled: false
    }
});
```
AppRouteConfigs:
```typescript
{
Home: {
        screen: Home,
        navigationOptions: {
            header: null
        }
    },
    StandBy: {
        screen: StandBy,
        navigationOptions: {
            header: null
        }
    },
    Drawer: {
        screen: createDrawerNavigator(drawerNav, {
            drawerWidth: 60,
            contentComponent: CustomNavigationItems
        }),
        navigationOptions: ({ navigation }): any => ({
            gesturesEnabled: false
        })
    }
};

const drawerNav = {
 Remote: {
        screen: createTabNavigator(remoteTabNav, {
            tabBarComponent: CustomTabBar,
            tabBarPosition: 'bottom',
            backBehavior: 'none'
        }),
        navigationOptions: {
            gesturesEnabled: false,
            swipeEnabled: false
        }
    },
    Settings: {
        screen: createStackNavigator(settingsStackNav, {
            headerMode: 'screen',
            navigationOptions: {
                gesturesEnabled: false
            }
        })
    },
};

const remoteTabNav = {
     RegularSaunaControl: {
        screen: RegularSaunaControl,
        navigationOptions: {
            tabBarLabel: 'sauna'
        }
    },
    SteamSaunaControl: {
        screen: SteamSaunaControl,
        navigationOptions: {
            tabBarLabel: 'steam'
        }
    },
};

const settingsStackNav = {
    Settings: {
        screen: Settings
    },
    ColorSettings: {
        screen: ColorSettings
    },
}
```

### Expected Behavior

- What do you expect should be happening?
That navigation by swiping should not work anymore if I use `swipeEnabled: false` and `gesturesEnabled: false` inside my createTabNavigator.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.12.1
| react-native     | 0.55.4

**Comment by brentvatne** [comment]
hi! please make your code runnable either on https://snack.expo.io or in a project i can clone from github, without any extraneous code

**Comment by dominikeinkemmer** [comment]
Hi, thanks I will make a running example and provide you with the link to it.

**Comment by dominikeinkemmer** [comment]
@brentvatne Hi, sorry for the late response, please access the example through the following link:
https://snack.expo.io/@guseindo/tabbar_android_swipedisable

Let me know if you need anything else. Thanks in advance.

**Comment by eriveltonelias** [comment]
Hi @dominikeinkemmer 

I just fixed, try to see it on https://snack.expo.io/Hy_iocQvQ

**Comment by dominikeinkemmer** [comment]
thanks a lot, I could confirm it and this works :)
