### ISSUE TITLE
this.props.navigation.navigate not Work

### ISSUE THREAD

**Issue by bitbeen** [react-navigation/react-navigation#4896]
#4885 this.props.navigation.navigate("XXX") 
some time while i use this.props.navigation.navigate("XXX")  by the react-navigation new ,it not work

**Comment by brentvatne** [comment]
https://github.com/react-navigation/react-navigation/issues/4885#issuecomment-415808178

share an example that reproduces the issue on the latest version (2.12.1) or we can't help. follow issue template please.
