### ISSUE TITLE
Requiring module "Linking.js" - Native module cannot be null 

### ISSUE THREAD

**Issue by jforaker** [react-navigation/react-navigation#4897]
Getting the RSOD (red screen of death) using the example provided from the docs website/snack. I do believe this is a bug as I have searched every other outlet suggested with no luck. 

Versions below.

Interestingly, when I dismiss the red screen, I can interact with the screens/navigation - though there is a yellow box warning and the same in chrome debugger: 

```
Possible Unhandled Promise Rejection (id: 0):
TypeError: Cannot read property 'addEventListener' of undefined
TypeError: Cannot read property 'addEventListener' of undefined
```

My app, which is essentially copied from https://snack.expo.io/@react-navigation/our-first-navigate-v2 : 

```js
import React from 'react';
import { View, Text, Button } from 'react-native';
import { createStackNavigator } from 'react-navigation';

class HomeScreen extends React.Component {
  render() {
    return (
      <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
        <Text>Home Screen</Text>
        <Button
          title="Go to Details"
          onPress={() => this.props.navigation.navigate('Details')}
        />
      </View>
    );
  }
}

class DetailsScreen extends React.Component {
  render() {
    return (
      <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
        <Text>Details Screen</Text>
      </View>
    );
  }
}

const RootStack = createStackNavigator(
  {
    Home: HomeScreen,
    Details: DetailsScreen
  },
  {
    initialRouteName: 'Home'
  }
);

export default class Stack extends React.Component {
  render() {
    return <RootStack />;
  }
}
```

And in my `index.js`

```js
AppRegistry.registerComponent('ViewStack', () => Stack);
```

![image](https://user-images.githubusercontent.com/2042031/44597526-ef391600-a79d-11e8-9cad-34830d676279.png)

![image](https://user-images.githubusercontent.com/2042031/44595179-4804b080-a796-11e8-8463-7a9d4a62b23d.png)

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.12.1
| react-native     | 0.56
| node             | 9.0
| npm or yarn      | npm

Any thoughts, ideas or pointers in the right direction would be greatly appreciated :)

**Comment by brentvatne** [comment]
there is no mention of Linking.js in the code you shared. you need to share an example that actually reproduces the issue or we can't help, sorry! that said, i'm very confident that it's something to do with you or some other library you're using importing Linking incorrectly

**Comment by brentvatne** [comment]
bad wording sorry, i meant to say your code

**Comment by brentvatne** [comment]
i suppose maybe someone working on your project removed this library ![](http://url.brentvatne.ca/RoNk8C.png)

it's included by default on all react-native projects so that's all i can think of

**Comment by jforaker** [comment]
Thank you @brentvatne ! 👍  This was it. We have a hybrid app with a lot of custom set up. I knew deep down that it wasn't an issue with react-navigation, and you just saved my day so thanks alot!

**Comment by brentvatne** [comment]
no problem!

**Comment by antunesgabriel** [comment]
I have almost the same problem, react-native: 0.61.2, node: 10.16.3
