### ISSUE TITLE
Animate backgroundColor of screen (transparent to semi-transparent)

### ISSUE THREAD

**Issue by ratskin** [react-navigation/react-navigation#4898]
### Current Behavior
I've got code like this:
```
const RootStack = createStackNavigator(
  {
    Home: HomeScreen,
  },
  {
    mode: 'modal',
    headerMode: 'none',
    transitionConfig: () => ({
      transitionSpec: {
        duration: 400,
        easing: Easing.out(Easing.poly(4)),
        timing: Animated.timing,
        useNativeDriver: false,
      },
      screenInterpolator: (sceneProps) => {
        const { position, scene } = sceneProps;
        const thisSceneIndex = scene.index;
        return {
          backgroundColor: position.interpolate({
            inputRange: [thisSceneIndex - 1, thisSceneIndex],
            outputRange: ['rgba(33, 33, 33, 0)', 'rgba(33, 33, 33, 0.9)'],
          }),
        };
      },
    }),
  },
);

const App = () => (
  <RootStack />
);

export default App;

```

When I run this, there is no animation on modal open, `navigation.goBack()` doesn't do anything, and I get the warning:
```
Possible Unhandled Promise Rejection (id: 0):
Error: Style property 'backgroundColor' is not supported by native animated module
```

### Expected Behavior

I'm trying to animate the background colour so that it goes from transparent to a semi-transparent dark colour. My modal looks like this (98% of full height):
```
<View style={{ flex: 1, flexDirection: 'column', justifyContent: 'flex-end' }}>
  <View style={{
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    height: '98%',
    width: '100%',
    backgroundColor: 'white',
    justifyContent: 'center',
  }}>
    <Text>Details!</Text>
  </View>
</View>
```

While animating using the above method doesn't work, I can get a semi-transparent dark colour (without animation) by doing this:
```
const RootStack = createStackNavigator(
  {
    Home: HomeScreen,
  },
  {
    cardStyle: { backgroundColor: 'rgba(33, 33, 33, 0.9)', opacity: 1 },
...
```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.11.2
| react-native     | https://github.com/expo/react-native/archive/sdk-29.0.0.tar.gz
| node             | 10.1.0
| npm or yarn      | npm 6.1.0

**Comment by brentvatne** [comment]
you can use transparent option on stack: https://github.com/react-navigation/react-navigation-stack/commit/a380437f354ab05be0932c826e9c0e8a6bd59147

then animate background color manually for each screen without using native driver
