### ISSUE TITLE
Unable to get "TabBarTop" to work

### ISSUE THREAD

**Issue by yasir-netlinks** [react-navigation/react-navigation#4899]
### Current Behavior
I am trying to render `TabBarTop`. The only reason I am trying out the custom one is because of the extra height in `TabNavigator` when using `iphoneX` , the tab bar is positioned top.
At the moment, the tab is un-responsive and no icons appear, although the indicator does appear. 

<img width="346" alt="screen shot 2018-08-17 at 2 05 19 am" src="https://user-images.githubusercontent.com/26054956/44615078-0b908d80-a846-11e8-8950-cabffe50ca36.png">

 
### Expected Behavior
It supposed to work and behave normally

### How to reproduce
Im not sure if you can reproduce the problem but this is how I have put my code, I have been stuck on this for a while now trying to find appropriate solution, all this hustle is because of the extra height when using `iphoneX`. 
There is also a similar issue (extra height): https://github.com/react-navigation/react-navigation/issues/3054

```
import React from 'react'
import { TabNavigator, TabBarTop } from 'react-navigation'

const RouteConfigs = {
    // screen
}
const TabNavigatorConfig = {
    tabBarComponent: TabBarTop,
    animationEnabled: false,
    swipeEnabled: false,
    tabBarOptions: {
         activeTintColor: //color,
         inactiveTintColor: //color,
         activeBackgroundColor: '#fff'
         inactiveBackgroundColor: //color,
         showIcon: true,
         showLabel: false
    }
}
```
this `TabNavigator` is within (a screen) of another TabNavigator (positioned bottom) and in turn within (a screen) of a stackNavigator (in order to have the header)

### Your Environment
react-navigation 1.5.11
react-native 0.55.1

**Comment by brentvatne** [comment]
hello! we don't provide support for old versions of react-navigation. please update to the latest version and feel free to re-create the issue with a reproducible example if it still exists :)
