### ISSUE TITLE
How to hide the status bar in a particular pages inside the react-native app

### ISSUE THREAD

**Issue by nihp** [react-navigation/react-navigation#4901]
I need to hide the status bar in a particular page in my app. I have used status bar hidden. It working for that page, but while navigating to other page after doing anything inside that page status bar is not showing for the entire app.

Kindly give any other thoughts. I tried with the below mentioned stackoverflow answer but it not resolved my problem.

https://stackoverflow.com/questions/36186385/hiding-the-status-bar-with-react-native

**Comment by eriveltonelias** [comment]
Hi @nihp!

Looks like this isn't a problem related with react navigation.

Please try reading the docs: https://facebook.github.io/react-native/docs/statusbar#hidden

@brentvatne since this isn't related with react-navigation, can we close this?

**Comment by brentvatne** [comment]
yup, this isn't currently within the scope of react-navigation however we will in the future be tackling this. this rfc landed but we still need to implement it - https://github.com/react-navigation/rfcs/pull/59
