### ISSUE TITLE
MaskedViewIOS breaks react-native-web

### ISSUE THREAD

**Issue by wiltonlazary** [react-navigation/react-navigation#4902]
//My solution was remove from imports and put it dynamically:
//node_modules/react-navigation-stack/dist/views/Header/Header.js

const APPBAR_HEIGHT = Platform.OS === 'ios' ? 44 : 56;
const STATUSBAR_HEIGHT = Platform.OS === 'ios' ? 20 : 0;
const MaskedViewIOS = Platform.OS === 'ios' ? require('react-native').MaskedViewIOS : undefined;

**Comment by brentvatne** [comment]
https://github.com/necolas/react-native-web/blob/0e81c6ef2758d4ca9b2099b1d04a4f8c417f0f43/packages/react-native-web/src/index.js#L84

maybe you need to update react-native-web

**Comment by dcods22** [comment]
@brentvatne Im having a similar issue with that import

```ERROR in ./node_modules/react-navigation-stack/dist/views/Header/Header.js
Module not found: Error: Can't resolve 'react-native-web/dist/exports/MaskedViewIOS' in '/Users/Dan/Documents/Development/codys-corner/node_modules/react-navigation-stack/dist/views/Header'
 @ ./node_modules/react-navigation-stack/dist/views/Header/Header.js 1:1694-1748
 @ ./node_modules/react-navigation-stack/dist/index.js
 @ ./node_modules/react-navigation/src/react-navigation.js
 @ ./src/navigation/Navigation.js
 @ ./src/content/AppContent.js
 @ ./src/App.js
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/index.js
```
