### ISSUE TITLE
Icon does not show in nested navigation

### ISSUE THREAD

**Issue by ahmadabdolsaheb** [react-navigation/react-navigation#4903]
### Current Behavior

All of the icons for the main tab navigators are displayed but _friends_ which is a nested 
createStackNavigator.

Additionally, the tab is not tab title is not displayed according to the _friends_ component's _navigationOptions_

![image](https://user-images.githubusercontent.com/4591597/44621748-6bbe1880-a8b4-11e8-882b-a5e8acd77afe.png)

the MainNavigator consists of three levels of nested navigation
```js    
    const MainNavigator = createBottomTabNavigator({
      welcome: { screen: WelcomeScreen },
      auth: { screen: AuthScreen },
      main: {
        screen: createBottomTabNavigator({
          settings: SettingsScreen,
          pomodoro: PomodoroScreen,
          Stats: StatScreen,
          friends: {
              screen: createStackNavigator({
              friendsList: FriendsListScreen,
              friendProfile: FriendProfileScreen
            })
          }
        })
      }
    });
```
the navigation options inside the FriendsListScreen component is set in the following way similar to the other tabs in the _main_ tab.
```js
  static navigationOptions = {
    title: 'Friends',
    header: null,
    tabBarIcon: ({ tintColor }) => <Icon
              name="ios-stats"
              size={30}
              type="ionicon"
              color={tintColor}
    />
  }
```

However when friends tab's nested navigation is removed and is set to a component, the icon and the tabs title are correctly displayed.

```js
main: {
        screen: createBottomTabNavigator({
          settings: SettingsScreen,
          pomodoro: PomodoroScreen,
          Stats: StatScreen,
          friends: FriendsListScreen
        })
      }
```

![image](https://user-images.githubusercontent.com/4591597/44621747-62cd4700-a8b4-11e8-88d5-e308e66c2ab0.png)

### How to reproduce

https://github.com/ahmadabdolsaheb/pomo

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |    "^2.11.2",
|expo| "^29.0.0"
| react-native     | "https://github.com/expo/react-native/archive/sdk-29.0.0.tar.gz",
| node             | v10.8.0
| npm or yarn      | 6.2.0

any feedback is appreciated.

**Comment by brownieboy** [comment]
Hmm....hunting around the documentation and StackOverflow, many of the examples that I'm seeing now defined the tab icons and labels directly in the createBottomTabNavigator setup, by way of if/then statements, e.g:

```
export default createBottomTabNavigator(
    {
        Home: HomeStack,
        Favorites: FavoritesStack,
        Account: AccountStack,
    },
    {
        navigationOptions: ({ navigation }) => ({
            tabBarIcon: ({ focused, tintColor }) => {

                const { routeName } = navigation.state;
                let iconName;
                if (routeName === 'Home') {
                    iconName = `tag${focused ? '' : '-outline'}`;
                } else if (routeName === 'Favorites') {
                    iconName = `heart${focused ? '' : '-outline'}`;
                } else {
                    iconName = `account-box${focused ? '' : '-outline'}`;
                }

                return <I name={iconName} size={25} color={tintColor} />;
            },
            tabBarLabel: () => {
                const { routeName } = navigation.state;
                return routeName.toUpperCase();

            }
        }),
```

The documentation _does_ say that you can use navigationOptions on your screen components, which is how I'm doing it.

I'm going to try moving these configs to the createBottomTabNavigator too and see if that works.


- https://reactnavigation.org/docs/en/tab-based-navigation.html
- https://stackoverflow.com/questions/52022191/label-of-createbottomtabnavigator-not-showing-react-native
- https://stackoverflow.com/questions/52021301/react-navigation-handle-header-on-nested-navigators

**Comment by brownieboy** [comment]
I now have this working.

Following the documentation at https://reactnavigation.org/docs/en/navigation-options-resolution.html I am now using the syntax where I set the navigationOptions properties after I import the stacks into the module where I create the Tab Navigator, but _before_  I actually create it, like so:

```javascript
import Home from "./screens/home-conn.js";
import BandsListStack from "./screens/bands-list-nav.js";
import AppearancesListStack from "./screens/appearances-nav.js";
import StagesListStack from "./screens/stages-list-nav.js";
import ContactUs from "./screens/contactus-conn.js";

Home.navigationOptions = {
  tabBarLabel: "Home",
  tabBarIcon: ({ tintColor }) => (
    <IconFontAwesome
      name="home"
      style={{ color: tintColor }}
      size={Platform.OS === "ios" ? 28 : 20}
    />
  )
};

BandsListStack.navigationOptions = {
  tabBarLabel: "Bands",
  tabBarIcon: ({ tintColor }) => <BandsTabIcon tintColor={tintColor} />
};

AppearancesListStack.navigationOptions = {
  tabBarLabel: "Schedule",
  tabBarIcon: ({ tintColor }) => <ScheduleTabIcon tintColor={tintColor} />
};

StagesListStack.navigationOptions = {
  tabBarLabel: "Stages",
  tabBarIcon: ({ tintColor }) => <StagesTabIcon tintColor={tintColor} />
};

ContactUs.navigationOptions = {
  tabBarLabel: "Info",
  tabBarIcon: ({ tintColor }) => (
    <MaterialCommunityIcons
      name="information"
      style={{ color: tintColor }}
      size={Platform.OS === "ios" ? 28 : 25}
    />
  )
};

const AppNavigator = createBottomTabNavigator(
  {
    Home: {
      screen: Home
    },
    BandsList: {
      screen: BandsListStack
    },
    Appearances: { screen: AppearancesListStack },
    Stages: {
      screen: StagesListStack
    },
    ContactUs: {
      screen: ContactUs
    }
  },
```

I've now remove all of the navigationOptions code from my screen and Stack Navigator components.

**Comment by lylest** [comment]
I tried the above example it brings me an error of can't  find variable  seems like  I am using a screen name which is not defined as a variable
