### ISSUE TITLE
(V1) tab navigation: Can't reset nested stack in tab A when currently in tab B

### ISSUE THREAD

**Issue by assafb81** [react-navigation/react-navigation#4907]
## The issue tracker is reserved for bug reports only.

I have read several issue but all of them are closed without any solution.
Can't use `popToTop` when Stack navigator are nested inside Tab navigator.
I have Tab stack, each tab is stack navigator

My tab stack looks like this:
stackName ->`mainStack`
1. `Tab A`
1.1 `Screen1` in stack navigator
1.1.1 `Screen11`
2. `Tab B`
2.1 `Screen2`
3. `Tab C`
3.1 `Screen3`
4. `Tab D`
4.1 `Screen4` in stack navigator
4.1.1 `Screen44`
4.1.1.1 `Screen444`

The scenario is:
1. user in Tab A in `Screen1`, which is the root of the stack navigator of `tab A`
2. user navigate to `Screen11`, which is the next screen in stack navigator of `tab B`
3. user navigates to `TabD` - now the user in `Screen4` which is the root of the stack navigator of `tabD`
4. user navigates to `Screen44`, which is the next screen in stack navigator of `tabD`
4. user navigates to `Screen444`, which is the next screen in stack navigator of `tabD`
5. in `screen444` the user fetch data and as a result the `tab A`, `Tab B` and `Tab C` should reset to the root of the stack navigators and the app navigate back to `Screen44` in `Tab D`.

The stack should look like this:
1. `Tab A`
1.1 `Screen1`
2. `Tab B`
2.1 `Screen2`
3. `Tab C`
3.1 `Screen3`
4. `Tab D`
4.1 `Screen4`
4.1.1 `Screen44`
4.1.1.1 `Screen44`

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.5.11
| react-native     | 0.55.4
| node             | 8.11.3
| npm or yarn      | 1.7.0

I tried using reset

```
export default(navigation, 'mainStack`, [`Screen4`, `Screen44`]) => {
    const resetAction = NavigationActions.reset({
        index: 0,
        key: null,
        actions: [
            NavigationActions.navigate({ routeName: 'mainStack` }),
        ],
    });
    navigation.dispatch(resetAction);
    if ([`Screen4`, `Screen44`]) {
        [`Screen4`, `Screen44`].forEach(screenName =>
            navigation.navigate(screenName));
    }
};
```

It works ok, it a nice workaround.
All I want to see is the navigation back from `Screen444` to `Screen44`, but sometime the application is slow and I can see 2 navigations:
1. `Screen444` to `Screen44`
2. `Screen4` to `Screen44` <- this one is as a result from the workaround.

Is there another way to reset tabs - `Tab A`, `Tab B` and `Tab C`?

Thanks

**Comment by brentvatne** [comment]
hi! i see you went through a lot of trouble to put this issue together, thanks for writing it up. unfortunately we don't provide support for old react-navigation versions due to limited bandwidth. i'd suggest updating to the latest version and seeing if your issue is resolved. if it is not, then you can re-create this issue and link to a reproducible example that we can run on our machine, preferably on https://snack.expo.io for convenience. thanks and good luck!
