### ISSUE TITLE
Keep same component instance for different tabs in BottomTabNavigator

### ISSUE THREAD

**Issue by Tibolte** [react-navigation/react-navigation#4908]
I am developing an app which currently looks like this:

```
TabNavigator:
   Home
   Racing
   Sports
 ```

And per requirements I have to use a webview that links to the /home, /Racing, /Sports urls of the company website I am working for. My current implementation looks like so:

```
const BottomNavigator = createBottomTabNavigator(
      {
        Home: {
          screen: HomeScreen
        },
        Racing: {
          screen: HomeScreen
        },
        Sports: {
          screen: HomeScreen
        }
      });
``` 

```HomeScreen``` here is a component that holds a webview. The problem with this approach is that I have 3 different instances of the same component. I would like to instantiate this component no more than once. Just simply mount the component once and pass the correct url to it. I am not passing the correct url yet here, just trying to solve this instantiation issue.

Is it something that is possible with BottomTabNavigator?

**Comment by Titozzz** [comment]
What is doing to achieve exactly this is having an absolute positioned webview next to the navigator and I control it from the children

**Comment by Tibolte** [comment]
I'm having a hard time picturing it @Titozzz , do you have a code snippet for that?

**Comment by eriveltonelias** [comment]
Hi @Tibolte! 

How about this: https://snack.expo.io/SkLaNSzPm 
I hope that it can help you. 


Please, next time try to follow the issue template.

**Comment by Tibolte** [comment]
Hmm not what I was looking for @eriveltonelias. But thanks for the help, it looks like we're gonna have to do things differently as what we're trying to accomplish is a bit difficult. Cheers

**Comment by eriveltonelias** [comment]
Sure @Tibolte! 

Thanks!
