### ISSUE TITLE
Update badge number TabBarIcon and other places

### ISSUE THREAD

**Issue by vohoangankhanh** [react-navigation/react-navigation#4911]
### Current Behavior
I had seen #766 and #1941 and I can add badges number to tabBarIcon, but now my problem occurs:
1. I have the Main component contains all the Stack(Switch,Stack,TabBar), after login is the Dashboard component that have badge numbers on each main items, then click one item have badge number, the main tabar with some icon and badges number is at bottom and a news component is showing. After click on single row of news to view detail in another component(also run actions redux) but it go back immediately to Main component to update badge numbers. If I don't run the actions to update badge number I can go to details of the news. I research everywhere  and try everything several days but cannot find the solution for this.
### Expected Behavior
Now I want when I click on the single row, it navigate to detail page and also update the badge number of tabBarIcon at the bottom that belong to Main component without move back to Main component.
### My Environment
| software         | version
| ---------------- | -------
| react-navigation | ^2.11.2
| react-native     |^0.55.4
| node             | 10.5.0
| npm or yarn      |npm 6.3.0

**Comment by vohoangankhanh** [comment]
I cannot believe that no one just gives me some advice or no one used to update the badge numbers backward to the parent component or this is the new feature that is uncompleted?

**Comment by vohoangankhanh** [comment]
Now I manage to find the cause. That is the RootNavigator I had created outside the App.js like this
```
export default class App extends React.PureComponent {
................
render() {
        const Layout = RootNavigator();
        if (!this.state.isReady) {
            return (
                <AppLoading
                    startAsync={this._loadResourcesAsync}
                    onError={this._handleLoadingError}
                    onFinish={this._handleFinishLoading}
                />
            );
        }
        return (
            <Root>
                <Layout/>
            </Root>
        );
}
const RootNavigator = () => {
return createStackNavigator({
...........
});
}
```
this lead to the behavior above. 
now I rewrite it again and then no more problem, the badge numbers is updated without going back to initial screen App.js. But I don't know why putting RootNavigator outside the class App.js causes that problem?
```
export default class App extends React.PureComponent {
................
render() {
        const {appIsReady} = self.state;
        if (!appIsReady) {
            return (
                <AppLoading
                    startAsync={self._loadResourcesAsync}
                    onError={self._handleLoadingError}
                    onFinish={self._handleFinishLoading}
                />
            );
        }
        let Layout = this.rootNavigator();
        return <Root>
            <Layout/>
            {!appIsReady && <LoadingView/>}
        </Root>;
    }
rootNavigator = () => {
        return createSwitchNavigator({
.............
});
}

**Comment by percyavaur** [comment]
bro than so much
