### ISSUE TITLE
Reopening #3184 : StackNavigator Header adds SafeAreaView inset padding even when nested 

### ISSUE THREAD

**Issue by Titozzz** [react-navigation/react-navigation#4912]
Following #3184 

### Current Behavior

Even if the stack navigator is not in an unsafe area, it gets bigger on iphone X.
- What code are you running and what is happening?
https://snack.expo.io/@titozzz/stacknavigator-safeareaview-bug
Run in on an iphoneX to see the bug.
- Include a screenshot if it makes sense.
![simulator screen shot - iphone x - 2018-08-28 at 12 00 30](https://user-images.githubusercontent.com/6181446/44716224-00de2e80-aaba-11e8-86d4-4606db686441.png)

### Expected Behavior

- What do you expect should be happening?
The navigator should only resize if the view is inside the unsafe area

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.12.1
| react-native     | expo v29

Is there any reason for using react-native-safe-area-view instead of importing it from react-native ?

**Comment by eriveltonelias** [comment]
Hi @Titozzz! 


https://snack.expo.io/H1sFsRGw7  maybe it can help you.

**Comment by Titozzz** [comment]
Hi @eriveltonelias , sorry if I wasn't clear enough in my issue, I do want the nav bar to display, the issue here is the height of the navbar on iphoneX, because it assumes it need to expand to avoid the notch

**Comment by brentvatne** [comment]
hey @Titozzz! thanks for providing the screenshot. you can use `headerForceInset` prop, eg: `headerForceInset: {vertical: 'never'}` and that will solve your problem. we're working on a better primitive for handling safe area insets but for now this is a little manual. see https://snack.expo.io/@notbrent/stacknavigator-safeareaview-bug for a working example

**Comment by byk04712** [comment]
I resolve this with below

[docs](https://reactnavigation.org/docs/en/stack-navigator.html#stacknavigatorconfig)

```

createStackNavigator({
    //...
},{
    // Center the title, this is the default on iOS.
    headerLayoutPreset: 'center'
})

```
