### ISSUE TITLE
Deep linking and SwitchNavigator

### ISSUE THREAD

**Issue by 3luyka** [react-navigation/react-navigation#4913]
Hi, how to combine "deep-linking" with "createSwitchNavigator" when "initialRouteName" runs firsts and literally ignore deep-linking url?

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.12.0
| react-native     | 0.56.0
| npm or yarn      | yarn

**Comment by RichardLindhout** [comment]
How did you fix this?

**Comment by speedyankur** [comment]
How to fix this problem?

**Comment by scalfs** [comment]
Any news on this?

**Comment by shem8** [comment]
The problem still exists =|

**Comment by HugoLiconV** [comment]
I have the same problem

**Comment by arifb** [comment]
Anyone on this thread manage to resolve this issue? I'm using react navigation 4 and deep linking works well if the app is already in the background.

But if the app is killed, the deep link is ignored and initialRouteName opens.
