### ISSUE TITLE
Horizontal scroll position in Tab Navigation

### ISSUE THREAD

**Issue by mrafei** [react-navigation/react-navigation#4919]
Hi,

I have read the docs and I am not able to find the following feature:
I need a handle on the position of the horizontal `ScrollView` containing the screens in `TabNavigator`.

Can you help me achieve this? Thanks.

**Comment by eriveltonelias** [comment]
Hi @mrafei !


https://reactnavigation.org/docs/en/material-top-tab-navigator.html#tabnavigatorconfig
