### ISSUE TITLE
Android Crash 2.11.1

### ISSUE THREAD

**Issue by taxidermic** [react-navigation/react-navigation#4920]
### Current Behavior
Got crash on Android. iOs works as expected.

### Expected Behavior
I expected not to have a crash :)

### How to reproduce

Install `react-navigation: 2.11.1`.
I have also different native module installed: `react-native-charts-wrapper`. Maybe changing any files under `./android` folder makes impact?

### Your Environment

| software         | version
| ----------------   -------
| react-navigation | 2.11.1
| react-native        | 0.55.4
| node                    | 9.8.0
| npm                     | 5.6.0

**Comment by eriveltonelias** [comment]
Hi @jhalborg, 

I'm sorry that you're having this issue. Have you tried to delete your _**node_modules**_ and reinstall again without **react-native-charts-wrapper** ? 

I just created an example with react-navigation 2.11.1 on Android and works as expected. 

https://snack.expo.io/@eriveltonelias/android-react-navigation-2-11-1-test

**Comment by taxidermic** [comment]
I'm not jhalborg :) Thank for your reply, nothing to be concerned here.

Issue gone away after I fixed bug that was not linked to this lib, but somehow started being serious after connecting this lib. Guess timers did their work here!

**Comment by eriveltonelias** [comment]
hahaha sorry @taxidermic! :)
