### ISSUE TITLE
Persist header view on StackNavigator

### ISSUE THREAD

**Issue by RuudBurger** [react-navigation/react-navigation#4921]
Maybe I'm using the wrong search terms but I can't seem to find what I'm looking for.

I have a StackNavigator with multiple screens in them and I want the `headerRight` component to be the same on all the screens. I can add them to each screen in `navigationOptions`, but then it creates duplicate instances of the same thing (+ it fades the component in/out)

Is this easy to do with current version, or do I need to extend the `Header` component and use it in `navigationOptions.header`?

If this isn't possible, can I make it so that at least it won't fade in or out? I would like the tilte and headerLeft to transition though.

**Comment by jbkuczma** [comment]
Have you tried setting `headerRight` in `navigationOptions` where you create your stack navigator? Something similar to the following:
```js
const Stack = createStackNavigator({
  Screen1: { screen: Screen1 },
  Screen2: { screen: Screen2 },
  Screen3: { screen: Screen3 }
}, {
  navigationOptions: ({ navigation }) => {
    return {
      headerRight: <YourIcon />,
    }
  }
});
```

**Comment by RuudBurger** [comment]
I did, which doesn't make a difference.

**Comment by eriveltonelias** [comment]
Hi @RuudBurger, 

I just created an example on the snack with a custom icon on right writing once. 

https://snack.expo.io/@eriveltonelias/ashamed-truffles

**Comment by RuudBurger** [comment]
Hi @eriveltonelias 
Thanks for the snack, but this isn't really my question. I understand how to do it only once "code wise". But the `<Icon />` still gets created for each screen.

Seeing it on Android I understand this, because the header transitions in with the new screen. But on iOS the header is stuck to the top with only the content changing. So what I'm trying to achieve is the `<Icon />` component only renders once, so it doesn't animate. 

The main reason I want to do this, is that the element I want there is a `<Timer />` (instead of the `<Icon />`) counting down. If it gets rendered multiple times, all the lifecycle events also trigger multiple times ("timer finished", etc).

**Comment by eriveltonelias** [comment]
HI @RuudBurger, 

Gotcha! Thanks for explaining it, Have tried to send the timer value for the `next` or `preview` screen as params? 

For example `Screen A` you have the time with 100 secs as value when you navigate to a next screen you can the last value as params to next screen and update the `Header`. 

Or maybe you can create a custom fixed header for that on top of your project. 

maybe also use `screenProps`

Let me know if you have issues with that.

**Comment by RuudBurger** [comment]
Was just hoping there was something I was missing.

I think I will implement it with StackNavigation + headerMode 'none' and then put a fake header on top of that (hooked into navigationOptions from the StackNavigation)
