### ISSUE TITLE
Should I use the React Navigation Redux helper??

### ISSUE THREAD

**Issue by kenji-1996** [react-navigation/react-navigation#4922]
## The issue tracker is reserved for bug reports only.

If you have a question, feature request, or an idea for improving the library or its related tools, please try one of the following resources:

- [Read the documentation](https://reactnavigation.org/)
- [Post an issue to the website repository if you'd like to see a documentation change](http://github.com/react-navigation/website)
- [Post a feature request to Canny](https://react-navigation.canny.io/feature-requests)
- [Write a RFC if you have ideas for how to implement a feature request](https://github.com/react-navigation/rfcs)
- [Get help on Discord chat (#react-navigation on Reactiflux)](https://discord.gg/4xEK3nD) or [on StackOverflow](https://stackoverflow.com/questions/tagged/react-navigation)
- Search for your issue - it may have already been answered or even fixed in the development branch. However, if you find that an old, closed issue still persists in the latest version, you should open a new issue.

Bugs with react-navigation must be reproducible *without any external libraries that operate on it*. This means that if you are attempting to use Redux or MobX with it and you think you have found a bug, you must be able to reproduce it without Redux or MobX in this report. Redux related issues belong in [react-navigation-redux-helpers](https://github.com/react-navigation/react-navigation-redux-helpers), and we do not have any first-class integration with MobX at the moment.

---

### Current Behavior

Currently the docs for using the redux helper created by the react-navigation team is said to not be supported in future builds and is written in terms that seem 'Use at your own risk'.
Now the library seems great and helpful but should I try and integrate redux this way or avoid it as it seems its like it will be depreciated soon and then I will be back to where I started

### Expected Behavior

Use the redux helper to control the state of the nvaigation along with whatever else redux you would like to help

### How to reproduce

https://reactnavigation.org/docs/en/redux-integration.html#docsNav
Written explicticly at the top is this:

> Warning: in the next major version of React Navigation, to be released in Fall 2018, we will no longer provide any information about how to integrate with Redux and it may cease to work.

### What now
I am fine with the fact that this helper tool for reac-nav might well be depreciated; but has anyone got examples of integration with react native, react navigation and redux without using this helper?

Redux, React, React Native and React Navigation are all extremely new to me; I have been developing C#/Java software for a few years and only in the past few years got into Angular 5 and now making a choice to also learn React/React Native so please excuse my ignorance; its not from a lack of trying

**Comment by eriveltonelias** [comment]
Hi @kenji-1996. 

Have you tried this https://reactnavigation.org/docs/en/navigating-without-navigation-prop.html ?

**Comment by kenji-1996** [comment]
I will say that in the end I didnt use the helper, I included redux by merging the props of the navigation stacks with my own redux
Now I can use all my own redux easily and still use the great functionality of react navigation prop with my own probs
