### ISSUE TITLE
TopLevelNavigator(root) navigatorRef is very slowly  

### ISSUE THREAD

**Issue by 990094523** [react-navigation/react-navigation#4924]
### Current Behavior
There is no problem with debugging. In normal mode, the home page is very slow.

### How to reproduce
```
const TopLevelNavigator = createStackNavigator({
  Login: (() => (
    <View style={{flex: 1, backgroundColor: '#F5FCFF', justifyContent: 'center', alignItems: 'center'}}>
      <Text>Login Screen</Text>
    </View>
  ))
})

export default class App extends Component {

  componentDidMount() {
    console.log('navigatorRef: ', this.navigatorRef);
  }

  render() {
    return (
      <TopLevelNavigator ref={(navigatorRef) => this.navigatorRef = navigatorRef}/>
    );
  }
}
```
### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.12.1
| react-native     | 0.56.0
| node             | 8.9.0
| npm or yarn      | 1.9.4

**Comment by eriveltonelias** [comment]
Hi @990094523, 

I just created an example on https://snack.expo.io/@eriveltonelias/basic-example-react-navigation

and looks nice. Can you check it? 

And please, follow the issue template.

**Comment by brentvatne** [comment]
yeah we need a better solution for this. if you have ideas for how to improve please weigh in at https://github.com/react-navigation/rfcs/issues/61
