### ISSUE TITLE
Can i Reload screen after navigate?

### ISSUE THREAD

**Issue by ducvu91** [react-navigation/react-navigation#4927]
Hi, i have issue
I have a some screen
C : is screen list all
A > B > C > Action CURD to D > E> F.
and after CURD i navigate F > C.
In case screen A i can controll, another screen i can'i control it :(
how can i reload screen C after navigate ?

**Comment by eriveltonelias** [comment]
HI @ducvu91! 

You can pass `functions` as params on navigate to `reload` the state of your components / preview screens.

Please, follow the issue template.
