### ISSUE TITLE
React navigation not work if we create dynamic navigation

### ISSUE THREAD

**Issue by anehkumar** [react-navigation/react-navigation#4928]
Hi, I already ask about this issue at https://github.com/react-navigation/react-navigation/issues/4900 but it was closed without any information which help me. I already share sample code on github https://github.com/anehkumar/NavigationCategorySample

What I am doing is I have a list of the category which loads dynamically from the server and I create a navigation drawer in which I show that list of category. Now when the first time I click on category link it will open the screen without any issue but when I am in category page and want to open another category it did not change or do anything.  Please help thanks.

**Comment by eriveltonelias** [comment]
Hi @anehkumar, 

Please read this:

https://reactnavigation.org/docs/en/limitations.html#dynamic-routes
