### ISSUE TITLE
In TabNavigator, ViewPagerAndroid cannot be rendered

### ISSUE THREAD

**Issue by 2534290808** [react-navigation/react-navigation#4930]
### My Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.12.1
| react-native     | 0.53.3

**Comment by eriveltonelias** [comment]
Hi @2534290808, 

Can you reproduce a runnable example on https://snack.expo.io ?

**Comment by 2534290808** [comment]
I guess it's probably due to a different version of react native

**Comment by eriveltonelias** [comment]
Hi @2534290808, 

Try to update your environment. Please, let we know if you still have problems.
