### ISSUE TITLE
Header flashes when using createMaterialBottomTabNavigator

### ISSUE THREAD

**Issue by amhinson** [react-navigation/react-navigation#4932]
### Current Behavior

When using `createStackNavigator` with `createMaterialBottomTabNavigator` on iOS, it is causing the header to quickly flash when switching between tabs. This behavior doesn't happen when using `createBottomTabNavigator`.

![screen recording 2018-08-31 at 11 43 am](https://user-images.githubusercontent.com/17091790/44922357-392c7980-ad13-11e8-8f8a-3df77439c75c.gif)

NOTE: The gif doesn't catch all the frames, but it happens on every tab switch.

### Expected Behavior

Header should behave in a similar fashion, regardless of the tab bar.

### How to reproduce

It is hard to see on the snack simulator, but it shows up very well running locally.

Snack: https://snack.expo.io/rkSXgJDvm

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.12.1
| react-native     | 0.56.0
| node             | 108..0
| npm or yarn      | 1.9.4

**Comment by jasoncharnes** [comment]
This same flash happened to me when using `createMaterialBottomTabNavigator` by itself, without `createStackNavigator`.

**Comment by brentvatne** [comment]
@satya164 - does this seem familiar to anything you've seen in issues for paper bottom navigation?

**Comment by oriharel** [comment]
Why is this issue closed? That's still happens and the suggested solution doesn't work (I have my material tab controller nested inside a stack and the issue exist)

**Comment by fahadrehman** [comment]
I am also facing this issue, is there any workaround to fix this problem?

**Comment by arisferyanto** [comment]
@satya164 @brentvatne, is it possible to make the cross-fade effect configurable? With the effect, createMaterialBottomTabNavigator is causing glitch on all apps that have non-white header.

**Comment by spewarren** [comment]
I'm experiencing this issue too

**Comment by victorkvarghese** [comment]
is this issue fixed in latest version ? Any workarounds would be helpful. I tried dark theme, nesting inside stack. Didn't work

**Comment by mandeep115** [comment]
Nesting tab navigator inside a drawer navigator solves the issue.

Also try setting `sceneAnimationEnabled={true}` or `false` in tab navigator (no nesting required)
