### ISSUE TITLE
Sporadic Crash (descriptor.options)

### ISSUE THREAD

**Issue by jose920405** [react-navigation/react-navigation#4933]
hello, with the help of appsee I have been able to detect a sporadic crash that happens to few users. I have not found an easy way to replicate it, because as I mentioned earlier, the crash is sporadic.

Currently my app has more than 70k of active users.

![captura de pantalla 2018-08-31 a la s 1 50 22 pm](https://user-images.githubusercontent.com/12536184/44930771-04292280-ad25-11e8-9475-7c6149e51e6e.png)

It affects 0.3% of users. A little more than 200 users

The crash is:

`
Terminating app due to an uncaught exception 'RCTFatalException: Unhandled JS Exception: Error: TypeError: TypeError: undefined is not an object (evaluating 'e.descriptor.options') This error is located at: in t in i in RCTView in t in r in s in n in n in Unknown in Connect(Component) in RCTView in t in Connect(t) in n in t in RCTView in RCTView in t This error is located at: in n in Unknown in Connect(Component) in RCTView in t in Connect(t) in n in t in RCTView in RCTView in t', reason: 'Unhandled JS Exception: Error: TypeError: TypeError: undefined is not an ob..., stack: value@713:4644 oe@46:50434 X@46:45612 G@46:46302 ee@46:47921 te@46:48702 ne@46:49098 le@46:51343 enqueueSetState@46:25514 setState@53:915 _onTransitionEnd@752:3342 s@172:1767 <unknown>@174:3109 value@192:479 value@18:3368 <unknown>@18:1141 value@18:2507 value@18:1111 '
`

The line that cause the crash is

`this.props.navigation.goBack();`

Any idea that it may be causing it?

"react-navigation": "2.0.4",

```
Environment:
  OS: macOS Sierra 10.12.6
  Node: 8.9.1
  Yarn: 1.3.2
  npm: 5.5.1
  Watchman: 4.7.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.1 AI-173.4819257

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.51.0 => 0.51.0

```

**Comment by eriveltonelias** [comment]
Hi @jose920405! 

Have you tried to update your `react-navigation`? If you have more information about this crash, please tell us will be much easier to help/understand it.

**Comment by ronastlelobo** [comment]
I am getting same issue here as specified above. Did you find any solution @jose920405 ??

**Comment by jose920405** [comment]
hi @ronastlelobo 

Unfortunately, im not giving more maintenance on the project where this was happening. I remember updating to the latest version of `react-navigation`, but I could not check if that solved the problem. In projects with less user flow I have not had any problem.

**Comment by godf4ther** [comment]
I am getting same issue here as specified above. Did you find any solution @jose920405
