### ISSUE TITLE
create-react-context is no longer Open Source in 0.2.3

### ISSUE THREAD

**Issue by ckknight** [react-navigation/react-navigation#4934]
As per https://github.com/jamiebuilds/create-react-context/commit/392ef2b40a4a6239ff63131c03797b7607708040, `create-react-context` is no longer Open Source. This was released as 0.2.3, which is inappropriately not a major version release because this is a breaking change.

`react-navigation` is currently depending on `create-react-context` `^0.2.1`, which will automatically install `0.2.3`

An easy solution would be to pin the dependency at either version `0.2.1` or `0.2.2`, without a `^` or `~`.

React Navigation's license is currently BSD, an Open Source license, but because of its dependency on `create-react-context`, installing it today necessarily means installing non-Open Source code.

**Comment by naddeoa** [comment]
I notice that parts of react-navigation still carry a transitive dependency on `0.2.3`. If you install `3.0.5` today then you'll get `create-react-context@0.2.3` from `@react-navigation/core`. Was that an active choice or is it just a matter of someone submitting a pr to make it happen?

**Comment by brentvatne** [comment]
just a pr needed to change it, probably @ericvicenti copied dependency over incorrectly by accident when splitting the project apart, can you open a pr @naddeoa?

**Comment by naddeoa** [comment]
Normally I would love to! Unfortunately, I think it looks a bit awkward for me to do it since I'm working at one of the companies on that list. I think its best if I just cross my fingers and wait a bit. Thanks for getting back to me though, that's good to know.

**Comment by bySabi** [comment]
@naddeoa It seems LICENSE was changed back on current master: https://github.com/jamiebuilds/create-react-context/commit/f31c9edb9a1f93d5e673de5ea8b1e09a46f9b407 but updated npm is not release yet.

Developer @jamiebuilds is not being very responsive with request and PR's. Probably the recurrent "lack of time problem" of OSS.

**Comment by naddeoa** [comment]
Ah, ok so the work is done. Yeah, I understand that. I'm sure everyone has plenty to do.

**Comment by brentvatne** [comment]
@naddeoa - ah, fair, ok I fixed the version in @react-navigation/core to 0.2.2 and released a new version of it and react-navigation with the change. see react-navigation@3.0.8

**Comment by naddeoa** [comment]
@brentvatne Awesome, thanks a lot for that! I'll contribute something in its place in the future that actually interesting.
