### ISSUE TITLE
goBack Api not working

### ISSUE THREAD

**Issue by zhaozhiming** [react-navigation/react-navigation#4935]
### Current Behavior

The `goBack` API not working

### Expected Behavior

I expect it can go back to pre page 

### How to reproduce

This is my reproduce snack: [go-back-no-working](https://snack.expo.io/@tik-zhaozhiming/go-back-no-working) . 

Steps:  
* go to Screen2Component 
* click Go2
* click GoBack // not working

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.12.1
| react-native     | https://github.com/expo/react-native/archive/sdk-29.0.0.tar.gz
| node             | 10.0.0
| npm or yarn      |  5.6.0

**Comment by eriveltonelias** [comment]
Hi @zhaozhiming, 

https://snack.expo.io/@eriveltonelias/go-back-no-working

**Comment by zhaozhiming** [comment]
@eriveltonelias Thanks, but I want to go back to Screen2Component. Is it possible? Maybe I should not use `createSwitchNavigator`?

**Comment by adirzoari** [comment]
@zhaozhiming same issue with createStackNavigator. did you find solution?

**Comment by zhaozhiming** [comment]
Yes, put the screen3 to the screen2 stack will work. Some code as follow:  

```js
const Drawer = createBottomTabNavigator(
    {
        Screen1Component: {screen: Screen1Component},
        Screen2Component: createStackNavigator({Screen2Component, Screen3Component})
    },
);
```

**Comment by adirzoari** [comment]
why you declare createBottomTabNavigator? in my case it's not tabs, it's stack as auth and then any user who has go to nestedNavigator.
