### ISSUE TITLE
Can't change drawer label on a stack navigator

### ISSUE THREAD

**Issue by anonrig** [react-navigation/react-navigation#4940]
### Current Behavior
I'm running on react-navigation 2.9.2 with react-native 0.56.0

### Expected Behavior

Adding a drawerLabel on either the component's navigationOptions or in the definition of the navigator should change the drawer label. But currently it just get's the root's name on the navigator.

### How to reproduce

My navigator is like follows:

```javascript
const Navigator = createSwitchNavigator({
  Loading: {
    screen: Loading
  },
  Onboarding: {
    screen: Onboarding
  },
  Drawer: createDrawerNavigator({
    Home: createStackNavigator({
      Authorized: {screen: Authorized},
      StoreModal: {screen: Store}
    }, {
      headerStyle: {backgroundColor: '#F4F8F8'},
      mode: 'modal'
    }),
    About: createStackNavigator({
      About: {
        screen: About
      }
    })
  })
})

export default Navigator
```

Can't change the drawer label in either from the definition of the navigator or inside Authorized  or About component

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.9.2
| react-native     | 0.56.0

**Comment by eriveltonelias** [comment]
Hi @anonrig, 

https://snack.expo.io/@eriveltonelias/custom-drawer-label

**Comment by tuzmusic** [comment]
I just wanted to leave the answer to save time for future readers. I did get this from @eriveltonelias's Snack, so thanks!

This example is from my code (rather than the OP's code) but I think the implementation is pretty clear.
```js
const DrawerNavigator = createDrawerNavigator(
  {
    Search: {
      screen: SearchStack,
      navigationOptions: {
        drawerLabel: "Find a Customer"
      }
    },
    NewCustomer: {
      screen: NewCustomerStack,
      navigationOptions: {
        drawerLabel: "Add a New Customer"
      }
    }
  },
  { contentComponent: DrawerContentView }
);
```
