### ISSUE TITLE
drawer navigation didn't close 

### ISSUE THREAD

**Issue by diksha-valuecoders** [react-navigation/react-navigation#4942]
### Current Behaviour
When picking an option from the drawer menu, you are able to catch it before it fully closes. When doing that it will not close regardless of what you pick.

### Expected Behaviour
if we catch the drawer before it fully closes it should open and when we pick other option then it will close.

Environment

| software         | version
| ---------------- | -------
| react-navigation |1.0.3
| react-native     |0.55.2
| node             |7.2.0

**Comment by eriveltonelias** [comment]
Hi @diksha-valuecoders, I'll close this, but if still need help, please add a runnable example.
