### ISSUE TITLE
How to go back to same stack's initial route in createDrawerNavigator

### ISSUE THREAD

**Issue by wiadev** [react-navigation/react-navigation#4943]
Hi

Here is the createDrawerNavigator.
```
export default createDrawerNavigator(
  {
    Shop: {
      screen: shopStack,
      navigationOptions: {
        drawerIcon: <Image source={require('../../assets/shopIcon.png')} />,
        drawerLabel: 'SHOP',
      },
    },
    Account: {
      screen: accountStack,
      navigationOptions: {
        drawerIcon: <Image source={require('../../assets/accountIcon.png')} />,
        drawerLabel: 'ACCOUNT',
      },
    },
}
```

Here is the shopStack.
```
export default createStackNavigator(
  {
    Shop: {
      screen: ShopScreen,
      navigationOptions: {
        headerTitle: 'Shop',
        headerLeft: <MenuButton />,
      },
    },
    SearchView: {
      screen: SearchViewScreen,
    },
  },
  {
    initialRouteName: 'Shop',
    navigationOptions: {
      headerStyle: {
        backgroundColor: theme.primary,
      },
      headerTintColor: theme.white,
      headerRight: <ShoppingCart />,
    },
  }
);
```

What I'm trying to do is that I'm on Search page and I need to go back to Shop page by clicking shop icon in drawer.

![screenshot at sep 03 01-58-19](https://user-images.githubusercontent.com/18234060/44978009-829ce480-af1e-11e8-9403-bbd212604e9f.png)

But since I'm in Search page which is same stack of Shop stack, Nothing happens when I click on Shop from drawer and I can't go back to shop page.

How can I resolve this?

Thanks

**Comment by wiadev** [comment]
@ericvicenti 

![picker](https://user-images.githubusercontent.com/18234060/45008898-153e9180-afba-11e8-9dec-92d618e5ac29.gif)

Check out the above screenshot, please.
As you can see, I'm trying to go back to shop page from search page but it's not working because both of Shop and Search was created in shopStack.

```
export default createStackNavigator(
  {
    Shop: {
      screen: ShopScreen,
      navigationOptions: {
        headerTitle: 'Shop',
        headerLeft: <MenuButton />,
      },
    },
    SearchView: {
      screen: SearchViewScreen,
    },
  },
  {
    initialRouteName: 'Shop',
    navigationOptions: {
      headerStyle: {
        backgroundColor: theme.primary,
      },
      headerTintColor: theme.white,
      headerRight: <ShoppingCart />,
    },
  }

```

**Comment by Jekiwijaya** [comment]
@wiadev are you navigate using this.props.navigation? Try use NavigationService
https://reactnavigation.org/docs/en/navigating-without-navigation-prop.html

Because this.props.navigation only able to navigate from same navigator. But with NavigationService, it's navigate from root navigator.

**Comment by wiadev** [comment]
I've managed to resolve it via navigation.setParams.
