### ISSUE TITLE
User is pushed back to the previous route after closing drawer and navigating

### ISSUE THREAD

**Issue by jamsch** [react-navigation/react-navigation#4945]
### Current Behavior

1. Dispatch an action to close the drawer
2. call `navigation.navigate("screenName")` to navigate to a different screen on a different stack router root
3. `COMPLETE_TRANSITION` triggers for closed drawer
4. User gets pushed back to previous route

### Navigation structure

```javascript
StackNavigator({
  DrawerNavigator: {
     DashboardScreen,
  },
  InAppPurchasesScreen,
})
```

### Expected Behavior

Drawer should close while navigating to the next screen instead of sending the user back to the previous screen.

### How to reproduce
Snack: https://snack.expo.io/Hyk-cKiDm

```js
const { navigation } = this.props;
// Close drawer
navigation.dispatch(DrawerActions.closeDrawer({}));
// Navigate to different screen
navigation.navigate('InAppPurchaseScreen');
```

![peek 2018-09-04 16-51](https://user-images.githubusercontent.com/12927717/45010694-dfa1b300-b062-11e8-8410-524db4e75a4b.gif)

### Your Environment

| software         | version |
| ---------------- | ------- |
| react-navigation | 2.12.1 |
| react-native     | 0.57.0-rc.3 |
| node             | 10.9.0 |
| npm or yarn      | npm 6.2.0 |

**Comment by valtlfelipe** [comment]
I'm having a similar issue, when I close a modal, and quickly navigate to another route, I get redirected back to the last route, where the modal was closed.

![ezgif-1-3a77877942](https://user-images.githubusercontent.com/3065339/45930311-f5551a80-bf34-11e8-84da-7c9ef27fa42d.gif)


Logs that I added using `onNavigationStateChange`
```
[NAVIGATION] Navigation/NAVIGATE ProductDetail
[NAVIGATION] Navigation/COMPLETE_TRANSITION undefined
[NAVIGATION] Navigation/BACK undefined
[NAVIGATION] Navigation/NAVIGATE Cart
[NAVIGATION] Navigation/COMPLETE_TRANSITION undefined
[NAVIGATION] Navigation/COMPLETE_TRANSITION undefined
```

**Comment by timothylui** [comment]
I have this exact problem too. It worked fine in 2.0.8, however lazy loading was broken in that version thus the upgrade.

**Comment by eriveltonelias** [comment]
Hi guys! 

https://snack.expo.io/@eriveltonelias/react-navigation-drawer-navigate

Let me know if you still having problems.

**Comment by valtlfelipe** [comment]
I still having the same issue as I commented. I updated the dependencies, but still the same

**Comment by eriveltonelias** [comment]
Ho @valtlfelipe! 

Can you create a runnable example on https://snack.expo.io, please?

**Comment by valtlfelipe** [comment]
@eriveltonelias Yes, here it is: https://snack.expo.io/@valtlfelipe/react-navigation-go-back-error

Sometimes it does not happen. But I can reproduce it several times. Running on the device happens more time, because se browser simulator is to slow.

Basically you open the modal, close it, and quickly open the cart.

**Comment by valtlfelipe** [comment]
@eriveltonelias Could you reproduce it?

**Comment by eriveltonelias** [comment]
Hi @valtlfelipe! 

I spend a couple of hours trying to reproduce this without success, are you using the last `react-navigation`?

**Comment by valtlfelipe** [comment]
I just took the snack example, and ran it on my device, and could easily reproduce it. See the video: https://drive.google.com/file/d/1PomOmNXy_SYpewhZoaDGa0tK7HwGB77Q/view?usp=sharing

What can I help you to reproduce this? I'm using the latest version of `react-navigation` as in the snack example.

**Comment by manhha1006** [comment]
Hi @eriveltonelias.
in ur example, u have two screens and add InAppPurchaseScreen on both stackNavigator & drawerNavigator. Then when u back from InAppPurchaseScreen and go back to Dashboard it's normally. 
But If I add more screen to drawer and then go to InAppPurchaseScreen then go back I want to go back to screen that I on it before. So I have to remove InAppPurchaseScreen from drawer because backbehavior go to init route.
Afterthat when I navigate to InAppPurchaseScreen and go back, the drawer doesn't close and I have to dispatch closeDrawer before navigate to InAppPurchaseScreen. Then the issue is exactly that @jamsc  had described.

**Comment by jordenchang55** [comment]
I had the same issue.
What I did before is something like this.
```javascript
const DrawerStack = createDrawerNavigator({
  Main,
}) 
const AppStack = createStackNavigator({
  DrawerStack,
  ScreenA,
  ScreenB,
});
const RootStack = createSwitchNavigator({
  LaunchScreen,
  LoginScreen,
  AppStack,
});
```
And it broke after I upgrade to 2.17.0.
When I clicked ScreenA or ScreenB in drawer, it would push me back to Main.

Based on @eliperkins ' example, I changed the structure to the following.
```javascript
const DrawerStack = createDrawerNavigator({
  AppStack,
}) 
const AppStack = createStackNavigator({
  Main,
  ScreenA,
  ScreenB,
});
const RootStack = createSwitchNavigator({
  LaunchScreen,
  LoginScreen,
  DrawerStack,
});
```
It works as expected now. Hope this can help you.

**Comment by Daimension** [comment]
hope this helps
https://github.com/react-navigation/react-navigation/issues/5329
