### ISSUE TITLE
App sometimes initializes with blank screen

### ISSUE THREAD

**Issue by sjaakluthart** [react-navigation/react-navigation#4948]
### Current Behavior

This rarely occurs and when it does the app doesn't respond to 'Navigation' dispatches. This is something I am not able to reproduce every time I open my app. I think it could be a race condition of some sort. 

When I inspect the state I can see all my defined routes, but dispatching any action has no effect. The state diff is always empty.

I'm using a combination of Tab and Stack routes. My app has three tabs which each have multiple stacked routes. I'm using expo SDK v28.

### Expected Behavior

I expect my app to navigate to the initial screen, the second or middle tab, when I open it. I expect the app to respond to 'Navigation' dispatches such as the one listed below.

```json
{
  "type": "Navigation/NAVIGATE",
  "routeName": "Settings"
}
```

### How to reproduce

I'm not able to reproduce consistently, it just happens sometimes.

#### Steps

1. Open app
2. Wait for app load
3. See blank screen

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.11.2 |
| react-native     | 0.55.4 |
| node             | 8.11.1 |
| npm or yarn      | 1.9.2 |

**Comment by brentvatne** [comment]
are you using this pattern? https://reactnavigation.org/docs/en/connecting-navigation-prop.html

**Comment by sjaakluthart** [comment]
Yes I use `NavigationActions` inside my redux action creators.

Like this:
```js
dispatch(NavigationActions.navigate({ routeName: 'App' }));
```

**Comment by brentvatne** [comment]
can you provide a reproducible example?

**Comment by vonovak** [comment]
closing, as it's fairly outdated and repro was not provided. thanks.
