### ISSUE TITLE
When I quickly enter the application and jump from page A to page B, the program automatically rolls back to page A.

### ISSUE THREAD

**Issue by 928255095** [react-navigation/react-navigation#4949]
When I quickly enter the application and jump from page A to page B, the program automatically rolls back to page A.

### Current Behavior

/**
     * 点击菜单按钮
     *
     * @private
     */
    _onPressMenu(routeName,name){
        let tmpName = name.endsWith('订单')?name:name+"订单";

        this.props.navigation.navigate(routeName,{'name':tmpName});
    }

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.11.2
| react-native     | 0.55.4
| node             | v8.4.0
| npm or yarn      |6.3.0

![image](https://user-images.githubusercontent.com/10703617/45035696-30c69c80-b08d-11e8-88a3-64a6a7ac69b9.png)

after enter OrderListPage page,auto rolls back OrderPage page

**Comment by 928255095** [comment]
the code https://github.com/java110/MApp/tree/master/app/pages/order

**Comment by brentvatne** [comment]
hi! we need a *minimal* reproducible example here - see https://stackoverflow.com/help/mcve for more info on how to do this. feel free to re-create the issue with that and i will happily investigate!
