### ISSUE TITLE
DrawerNavigator : Passing Params

### ISSUE THREAD

**Issue by paulbx81** [react-navigation/react-navigation#4952]
hello everybody can you try to help me please

this my navigation system : 

```
const homePageScreenStack = createStackNavigator({
    "HomePage": {
        screen: HomePage,
    }
},navigationOptions)

const suiviRiskScreenStack = createStackNavigator({
    "SuiviRiskPage": {
        screen: SuiviRiskPage,
    }
},navigationOptions)

const AppStackDrawer = createDrawerNavigator(
  {
    HomePageDrawer: {
      screen: homePageScreenStack,
    },
    SuiviRiskPageDrawer: {
      screen: suiviRiskScreenStack,
    }
  },
  {
    initialRouteName: 'HomePageDrawer',
  }
);
```

In my HomePage i want to go in my SuiviRiskPage and pass some params but it don't work

In my HomePage i try this first : 

`    this.props.navigation.navigate('SuiviRiskpageDrawer', {name: "Paul"});`

it don't work so i tried to do this : 

```
    this.props.navigation.navigate({
      routeName: 'SuiviRiskPageDrawer',
      action: {
        type: "Navigate",
        routeName: "suiviRiskScreenStack",
        params: { name: "Paul" }
      }
    });
```

it do'nt work also so i tried this : 

```
    this.props.navigation.navigate({
      routeName: 'SuiviRiskPageDrawer',
      action: {
        type: "Navigate",
        routeName: "suiviRiskScreenStack",
        action: {
          type: "Navigate",
          routeName: "SuiviRiskPage",
          params: { name: "Paul" }
        }
      }
    });
```

And it don't work again... this.props.navigation.state.params is not defined...

**Comment by vonovak** [comment]
@paulbx81 have you tried navigating to `SuiviRiskPage`? It's hard to help without a runnable repro of your problem though - if you want help, I recommend making it easy for others to help you. By creating a runnable repro on https://snack.expo.io/, it's much more likely people will try to help you :)

**Comment by eriveltonelias** [comment]
Hi @paulbx81! 

I'll close this, as @vonovak said it's hard to help you without a runnable code and with without following the issue template. But if you still need help, create a new issue following the issue template, please.
