### ISSUE TITLE
Send StackNavigator props to Drawer Navigator contentComponent

### ISSUE THREAD

**Issue by panda0603** [react-navigation/react-navigation#4959]
### Current Behavior

At the moment I have Stack Navigator inside the drawer navigator. My stack navigator is as follows: 

```
const AppNavigator = createStackNavigator(
  {
    Home: {
      screen: City,
      navigationOptions: () => ({
        header: null
      })
    },
    selectCity: {
      screen: CityApp,
    },
    sideBar: {
      screen: SidebarScreen
    }
  },
  {
    cardStyle: {
      paddingTop: Expo.Constants.statusBarHeight
    }
  }
);
```

And in drawer navigator, I have put in the stack navigator above. 

```
const DrawerNavigator = createDrawerNavigator(
  {
    Home: { screen: AppNavigator }
  },
  {
    contentComponent: SidebarScreen
  }
);
```
SidebarScreen component is the custom component I wish to render in the drawer.

### Expected Behavior

I wish to use StackActions such as 'replace, push' in the contentComponent of the drawerNavigator. I am able to use those actions in the components listed in AppNavigator(City and CityApp), but I cannot access them in SidebarScreen component of the contentComponent in drawerNavigator. I have included SidebarScreen component in the Stack Navigator as sideBar already, but still does not seem to work. I am expecting I have to seperately send the Stack navigation props to contentComponent, but I can't get it to work (ordinary navigation action, such as this.props.navigation.navigate works). 

I have tried 

```
contentComponent: ({navigation}) => (
        <SidebarScreen navigation={navigation} />
      ),
```

but I still get the undefined is not a function(evaluating this.props.navigation.replace...)

Any way to use the StackActions in contentComponent?

**Comment by brentvatne** [comment]
you could wrap that drawer in another stack and it will expose the actions to the drawer. or you can use `StackActions` directly, `navigation.dispatch(StackActions.push` :)
