### ISSUE TITLE
TopLevelNavigator sets the navigation reference in the Navigation Service after the mounting of the initial component.

### ISSUE THREAD

**Issue by chiraggupta1001** [react-navigation/react-navigation#4962]
Currently, my TopLevelNavigator sets the navigation reference in the Navigation Service after the mounting of the initial component. So, if I try to dispatch the action using navigation service in componentDidMount of my initial component, it doesn't found the reference to the navigation and throws an error saying "Cannot read property 'props' of undefined".

I'm able to use this in other components but it doesn't work in my first component or initial component.

Steps to reproduce:-
Create a navigation service by passing the reference of navigator from your top-level component, as mentioned in the docs [here](https://reactnavigation.org/docs/en/navigating-without-navigation-prop.html). Then try to dispatch any action in the componentWillMount or componentDidMount using that NavigationService.

| software         | version
| ---------------- | -------
| react | 16.2.0
| react-navigation | 1.0.0-beta.30
| react-native | 0.53.0

**Comment by vonovak** [comment]
Assuming your TopLevelNavigator gets rendered, the ref should be set before componentDidMount. However, if in your root component you first show some splash screen and only then render the navigator, then componentDidMount is called before the ref is set.

You did not share any issue repro so it's hard to be more specific. Can you please follow the issue template? Thanks.

**Comment by eriveltonelias** [comment]
Hi @chiraggupta1001!

as @vonovak  said you're using an extremely old version of react-navigation. I'll close in favor this but if you still need help open a new issue following the issue template, please.
