### ISSUE TITLE
Bottom navigation buttons do not work on FIRST click after pull down in flat list

### ISSUE THREAD

**Issue by pietro3092** [react-navigation/react-navigation#4963]
### Current Behavior

The bottom navigation buttons are not responding to first click after pull down in flat list

### Expected Behavior

Everything should be working on first click

### How to reproduce

Way to reproduce this bug(on iOS, RN version is 0.56): 
- pull down (no refresh action), then click on any navigation button. I did not get any response

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.13.0
| react-native     | 0.56.0
| node             | ?
| npm or yarn      |?

**Comment by eriveltonelias** [comment]
Hi @pietro3092, 

Can you create a runnable example on https://snack.expo.io ?

**Comment by eriveltonelias** [comment]
Hi @pietro3092! 

I'll close this, but if you still need help. Please, add a runnable example.
