### ISSUE TITLE
Custom header component is not replaced in 2.12.0 and later (iOS only)

### ISSUE THREAD

**Issue by Jakst** [react-navigation/react-navigation#4965]
### Current Behavior

Header is not updated when navigating from a custom header component to a standard header (header: undefined) with background color in a stack navigator in v2.12.0 on and later on iOS. 

### Expected Behavior

- When navigating to the new view, the header background color should update.

### How to reproduce

- Run the following snack on iOS: https://snack.expo.io/@jakst/react--navigation-header-regression
- Click the go away button
- Notice how the header does not change color

- Now downgrade react-navigation to 2.11.2 in the snack
- Click the go away button
- Notice how header changes color

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.12.0 and later
| react-native     | 0.56.0
| platform     | iOS

**Comment by Jakst** [comment]
This issue is still present in 2.18.0.

Any plans to take a look at it?

**Comment by brentvatne** [comment]
hi! I haven't had a chance to look yet. can you investigate and let me know if you find anything?

**Comment by eyalabadi98** [comment]
@brentvatne thanks for the info. My issue is that I cant get the function to rerender. Im getting in new props but the drawer isnt 'reloading'. I tried to setState to force it but i wasn't successful.

I am doing `componentWillReceiveProps(props) {
        console.log("Receiving new props!")
        if (this.props.isFocused) { 
            console.log("Is focused!");
            this.setState({ userType: 'ADMIN' });
        };

    }`

but its not making the component rerender. 

Any tips?

Thanks!

**Comment by eriveltonelias** [comment]
Hi @Jakst! 

@brentvatne solved this on v3. 

https://snack.expo.io/@eriveltonelias/react--navigation-header-regression
