### ISSUE TITLE
open a stackview from inside a modal

### ISSUE THREAD

**Issue by alainib** [react-navigation/react-navigation#4967]
I have the following react-navigation setup :

	const MyTabView = TabNavigator(
	  { ...
		NewObservation: { screen: NewObservation },
	  },
	  { ... }
	);

	const StackView = StackNavigator(
	  {
		global: {
		  screen: MyTabView,
		  headerMode: "none",
		  header: null,
		  navigationOptions: {header: null}
		},
		...
		SeeDetails: { screen: SeeDetails }
	  },
	  {	mode: 'modal' }
	);

	<StackView/>

	

NewObservation simplified code 

    class NewObservation extends React.Component {
      ... 
	  render() {
		return (
		  <Modal
			animationType={"none"}
			transparent={false}
			visible={this.state.visibleModal}
			onRequestClose={() => this.setState({visibleModal:false}) }
		  >
			<View style={{ flex: 1 }}>
			  <Text>modal</Text>
			  <TouchableOpacity underlayColor={Config.touchOpacityColor} style={styles.backButton}
				onPress={() =>
				  this.props.navigation.navigate("SeeDetails", { ... })
				} >
				<Text>go to stack</Text>
			  </TouchableOpacity>
			</View>
		  </Modal >
		)
	}

So i'm in "NewObservation tab", inside it i have a modal displayed.

### Current Behavior

If i click on the "go to stack" , the stack view appair under this modal,so it show only when i close the modal and i cannot close because content is dynamic.

### Expected Behavior

How to make the stackview appear over the modal ? 

| software         | version
| ---------------- | -------
 "react": "16.5.0",
 "react-native": "0.56.1",
"react-navigation": "2.13.0",

**Comment by eriveltonelias** [comment]
Hi @jugglebird, 

Have you tried with this https://reactnavigation.org/docs/en/modal.html ?

**Comment by alainib** [comment]
Hello , sorry maybe i'm missing something but what i should use ? i already using modals
