### ISSUE TITLE
undefined is not an object (evaluating 'RNGoogleSignin.BUTTON_SIZE_ICON')

### ISSUE THREAD

**Issue by Uzairrrr** [react-navigation/react-navigation#4968]
![screen shot 2018-09-10 at 6 24 49 pm](https://user-images.githubusercontent.com/23259529/45300087-dd3dce00-b526-11e8-9989-d30658f4d085.png)
Help me figure it out

**Comment by brentvatne** [comment]
unrelated to this project

**Comment by Uzairrrr** [comment]
brentvatne why this is unrelated?

**Comment by brentvatne** [comment]
because RNGoogleSignIn has nothing to do with react-navigation

**Comment by brentvatne** [comment]
also the package.json you shared doesn't even have react-navigation in it

**Comment by Uzairrrr** [comment]
@brentvatne  now
![screen shot 2018-09-10 at 8 09 35 pm](https://user-images.githubusercontent.com/23259529/45306203-84c1fd00-b535-11e8-8ed4-bdda067d3936.png)

**Comment by Uzairrrr** [comment]
@jugglebird 
look it works without navigation.
![screen shot 2018-09-11 at 3 27 27 pm](https://user-images.githubusercontent.com/23259529/45354620-7cba9980-b5d7-11e8-97ce-3c5e270cc104.png)
![screen shot 2018-09-11 at 3 27 49 pm](https://user-images.githubusercontent.com/23259529/45354621-7d533000-b5d7-11e8-8c59-aa2b6b33273d.png)

**Comment by Uzairrrr** [comment]
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 * @flow
 */

import React, { Component } from 'react';
import {
  Platform,
  StyleSheet,
  TouchableOpacity,
  Text,
  View
} from 'react-native';
import { GoogleSignin, GoogleSigninButton } from 'react-native-google-signin';

export default class App extends Component {

  componentDidMount() {
    try {
      GoogleSignin.hasPlayServices({ autoResolve: true });
      // google services are available
    } catch (err) {
      console.error('play services are not available');
    }
    GoogleSignin.configure({
      scopes: ['https://www.googleapis.com/auth/drive.readonly'], // what API you want to access on behalf of the user, default is email and profile
      iosClientId: '174271824777-4no0clk6g00s1dvu5p08i5i1t7dfda3a.apps.googleusercontent.com', // only for iOS
      // webClientId: '258892644892-4i0kqfh06sllcqse4ngr3oqttgnsahod.apps.googleusercontent.com', // client ID of type WEB for your server (needed to verify user ID and offline access)
      //offlineAccess: true, // if you want to access Google API on behalf of the user FROM YOUR SERVER
      //hostedDomain: '', // specifies a hosted domain restriction
      //forceConsentPrompt: true, // [Android] if you want to show the authorization prompt at each login
      //accountName: '', // [Android] specifies an account name on the device that should be used
      // webClientId: '258892644892-9gmmca4g50prjnj62f108j20uv2haj8f.apps.googleusercontent.com',
    })
  }

  _signIn = async () => {
    // console.log("RUNNNN");
    try {
      await GoogleSignin.hasPlayServices();
      const userInfo = await GoogleSignin.signIn();
      // this.setState({ userInfo });
      if (userInfo) {
        this.handleGoogle(userInfo);

      }

    } catch (error) {
      console.log("Error123", error);
      if (error.code === statusCodes.SIGN_IN_CANCELLED) {
        // user cancelled the login flow
      } else if (error.code === statusCodes.IN_PROGRESS) {
        // operation (f.e. sign in) is in progress already
      } else if (error.code === statusCodes.PLAY_SERVICES_NOT_AVAILABLE) {
        // play services not available or outdated
      } else {
        // some other error happened
      }
    }
  };

  render() {
    return (
      <View style={{ flex: 1, justifyContent: 'center' }}>
        <TouchableOpacity
          onPress={this._signIn}>
          <Text>
            {"Sign IN"}
          </Text>
        </TouchableOpacity>

      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
