### ISSUE TITLE
Pass uriPrefix prop to createBottomTabNavigator

### ISSUE THREAD

**Issue by yooouuri** [react-navigation/react-navigation#4969]
## The issue tracker is reserved for bug reports only.

If you have a question, feature request, or an idea for improving the library or its related tools, please try one of the following resources:

- [Read the documentation](https://reactnavigation.org/)
- [Post an issue to the website repository if you'd like to see a documentation change](http://github.com/react-navigation/website)
- [Post a feature request to Canny](https://react-navigation.canny.io/feature-requests)
- [Write a RFC if you have ideas for how to implement a feature request](https://github.com/react-navigation/rfcs)
- [Get help on Discord chat (#react-navigation on Reactiflux)](https://discord.gg/4xEK3nD) or [on StackOverflow](https://stackoverflow.com/questions/tagged/react-navigation)
- Search for your issue - it may have already been answered or even fixed in the development branch. However, if you find that an old, closed issue still persists in the latest version, you should open a new issue.

Bugs with react-navigation must be reproducible *without any external libraries that operate on it*. This means that if you are attempting to use Redux or MobX with it and you think you have found a bug, you must be able to reproduce it without Redux or MobX in this report. Redux related issues belong in [react-navigation-redux-helpers](https://github.com/react-navigation/react-navigation-redux-helpers), and we do not have any first-class integration with MobX at the moment.

---

### Current Behavior
The component should be openend from deeplinking.

### Expected Behavior
The app opens and nothing else happens.

### How to reproduce

I have a `App` class, that returns a `createSwitchNavigator`

```js
export default class App extends React.Component {
  ...

  render() {
    return <AppNavigator />;
  }
}
```

```js
const AppNavigator = createSwitchNavigator(
  {
    AuthLoading: LoadingScreen,
    App: AppStack,
    Auth: AuthStack
  },
  {
    initialRouteName: 'AuthLoading',
  }
);
```

My AppStack is a `createBottomTabNavigator` and contains (for example) one stack navigator.

```js
export default createBottomTabNavigator(
  {
    FirstStack: SomeStack,
  }
);
```

```js
export default createStackNavigator(
  {
    SomeScreen: {
      screen: SomeScreen,
      path: 'some_screen',
    },
  }
);
```

When I change `App: AppStack` to `App: { screen: () => (<AppStack uriPrefix={prefix}/>) }` in my createSwitchNavigator deeplinking is working, but calling `this.props.navigation.navigate('Auth');` won't work anymore. I am also getting the "Explicitly rendering more than one navigator" error, that makes sense because you return a `AppNavigator` and `AppStack`.

So i can't "logout" to say...

When I add the `uriPrefix` prop to my AppNavigator (in the App's render). Calling `this.props.navigation.navigate('Auth');` works but deeplinking don't.

How can I pass the uriPrefix prop to my `createBottomTabNavigator` without breaking the `this.props.navigation.navigate('Auth');`

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.6.2
| react-native     | 0.56.0
| node             | v10.9.0
| npm or yarn      | yarn

**Comment by eriveltonelias** [comment]
Hi @yooouuri! 

You can use `screenProps` 

https://snack.expo.io/@eriveltonelias/screenprops-example

**Comment by jasan-s** [comment]
screenProps are not being passed in v3
