### ISSUE TITLE
undefined is not an object (evaluating 'RNGoogleSignin.configure')

### ISSUE THREAD

**Issue by Uzairrrr** [react-navigation/react-navigation#4970]
![screen shot 2018-09-10 at 8 20 12 pm](https://user-images.githubusercontent.com/23259529/45307245-f8650980-b537-11e8-99ba-e347b56d5629.png)

**Comment by brentvatne** [comment]
once again this has nothing to do with react-navigation. consider creating an issue on the react-native-google-signin repo
