### ISSUE TITLE
Bump react-native-safe-area-view version to 0.10.0

### ISSUE THREAD

**Issue by BKova** [react-navigation/react-navigation#4973]
`react-native-safe-area-view@0.9.0` had a cyclical dependency problem.
This causes RN 0.57-rc.4 to throw a warning.
3 day ago this issue was fixed with the `react-native-safe-area-view@0.10.0` release.
Between 0.9.0 & 0.10.0 there was only this fix applied and nothing else.
[Original issue](https://github.com/react-community/react-native-safe-area-view/issues/40)
[Merged PR](https://github.com/react-community/react-native-safe-area-view/pull/41)
I can open a PR to bump dependency to 0.10.0 if you want?

**Comment by Titozzz** [comment]
https://github.com/react-navigation/react-navigation/pull/4980

**Comment by eriveltonelias** [comment]
Hi @BKova! 

I'll close this because @Titozzz already sent a PR.
