### ISSUE TITLE
How to pass props from parent

### ISSUE THREAD

**Issue by andrewyohanes123** [react-navigation/react-navigation#4975]
I have some trouble to pass some props from the parent to BottomTabNavigator
from parent component
 ```
<View style={[styles.container]} >
   <Navigator logout={somePropsfromparent} />
</View>
```
to navigator component
```
const Navigator = createBottomTabNavigator({
 ....
  Settings : {
    screen : props => <Settings logout={props.logout} />,
    navigationOptions : {
      tabBarLabel : "Settings" ,
      tabBarIcon : ({tintColor}) => (<Icon name="ios-contact" color={tintColor} size={24} />),
    }
  },
})
```
in the Setting component i console log the props i pass and got undefined
```
render() {
    const {user} = this.state;
    console.log(this.props)
}
```
log results
`{ logout: undefined }`

### My Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.12.1
| react-native     | 0.56.0

**Comment by eriveltonelias** [comment]
Hi @andrewyohanes123, 

you can use `screenProps` 

Follow this example: https://snack.expo.io/@eriveltonelias/screenprops-example

**Comment by jasan-s** [comment]
@eriveltonelias the screenProps for navigator in the v3 is always an empty object.
