### ISSUE TITLE
Conflicting custom action creators on nested navigators

### ISSUE THREAD

**Issue by berrytj** [react-navigation/react-navigation#4979]
### Current Behavior
I have an outer navigator and an inner navigator. I'd like to enrich both of them with the same set of custom action creators. But the custom action creator for the child overrides the custom action creator for the parent, even when invoked from the parent's navigation prop.

### Expected Behavior
Custom action creators would not be overridden by child navigators.

### How to reproduce
https://snack.expo.io/S18xoaBO7

I've written a custom action creator (`goBack2`) with the same implementation as `goBack` from the library, and added it to both an outer navigator and an inner navigator.

Press "Next", then "go back 2". This invokes `goBack2` on the navigation prop from the outer navigator. But the outer navigator does not go back. (If you get rid of the inner navigator, it works.)

### Proposed Solution
I have a brief solution that works for me, but I'm not sure of all the implications: https://github.com/mdcollab/react-navigation/commit/30a196ac54e9d30015f392303a209e8873a26636

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.13.0
| react-native     | 0.56.0
| node             | 10.7.0
| yarn             | 1.9.2

Also, the library is fantastic. Thanks hugely for all your hard work!

**Comment by brentvatne** [comment]
I think we don't want this behavior - the inner navigator should override the parent's custom actions. For example: if you have a stack within a stack, when we call `goBack` we want to call it on the inner stack and not on the outer one. If we inverted this logic for custom action creators only it would probably be confusing. I'm open to being convinced though, just open up an issue on https://github.com/react-navigation/rfcs/issues and let me know more about your use case and why you think this is important! Thanks
