### ISSUE TITLE
Warn Peer dependency in v2.14.0

### ISSUE THREAD

**Issue by ahce** [react-navigation/react-navigation#4982]
### Current Behavior

npm WARN react-native-screens@1.0.0-alpha.9 requires a peer of react@16.0.0-alpha.6 but none is installed. You must install peer dependencies yourself.
npm WARN react-native-screens@1.0.0-alpha.9 requires a peer of react-native@^0.44.1 but none is installed. You must install peer dependencies yourself.

### Expected Behavior

No peer warn

### How to reproduce

- npm install --save react-navigation@2.14.0

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.14.0
| react-native     | 0.57.0
| node             | 8.11.4
| npm or yarn      | 5.6.0

**Comment by eriveltonelias** [comment]
Hi @ahce, 

follow this https://github.com/react-navigation/react-navigation/issues/4973

**Comment by dsznajder** [comment]
@eriveltonelias This issue is not related to `react-native-safe-area-view` but to `react-native-screens`. Shouldn't be closed.
