### ISSUE TITLE
iphone xr xs xs max

### ISSUE THREAD

**Issue by lukasa1993** [react-navigation/react-navigation#4985]
any planed update for new iphones ?

**Comment by brorhb** [comment]
In my experience Xs and Xs Max is fine on the latest version. But Xr is semi broken. I've figured out there are some differences in the Dimensions.get('window')

<img width="432" alt="iPhone X / Xs / Xs Max" src="https://user-images.githubusercontent.com/12571304/45492770-752cf900-b76d-11e8-9052-60fd8435b74c.png">
this image shows the attributes for window on the X / Xs / Xs Max

<img width="470" alt="iPhone Xr" src="https://user-images.githubusercontent.com/12571304/45492832-a0174d00-b76d-11e8-9c16-60d93b1920fd.png">
this image shows the attributes for iPhone Xr

The result is a slightly off tabbar and stack title bar

<img width="495" alt="Off tabbar" src="https://user-images.githubusercontent.com/12571304/45492901-c341fc80-b76d-11e8-8dc6-760144703ee6.png">
Tabbar kind-of broken

<img width="526" alt="Titlebar broken" src="https://user-images.githubusercontent.com/12571304/45492919-cfc65500-b76d-11e8-83ec-a2877bca4ae2.png">
Titlebar kind-of broken

**Comment by brentvatne** [comment]
yup we will release a new update for this soon

**Comment by brentvatne** [comment]
cc @davepack re: https://github.com/react-community/react-native-safe-area-view

**Comment by brentvatne** [comment]
also I want to mention that this won't be an issue in the future once we get a proper safe area insets api in react-native upsteam. @janicduplessis is currently working on this. a lack of this api has necessitated detecting the device through screen dimensions which is very flakey for obvious reasons

**Comment by hagaigold** [comment]
and there is that as well facebook/react-native#18534, by @vonovak

**Comment by andrewmarmion** [comment]
I am finding that I get the same issue with the tab navigator, like @brorhb, but I get it in both the XS Max and the XR in react-navigation 2.14.2

**Comment by hagaigold** [comment]
this make sense cause XS Max & XR have the same number of points ("logical" resolution) of 414 * 896.
currently Iphone X is  identified in `react-native-safe-area-view` by looking for screen dimension of 375 * 812 .. which happened to be the size also for the 5.8" XS model, so we are lucky only for 1 of the 3 :)

**Comment by hagaigold** [comment]
something is very strange : I tried to get the dimension for XS Max with  [appetize.io](https://appetize.io), supposed to be real device, and it was 375 * 812, like @brorhb results.

the test was compiled with xcode 9.4.1, sdk 11.4 (no access to sdk 12 yet).

I am not familiar how react-native access to the dimension properties of the screen, but something look broken, I guess we need some tests on real devices.

**Comment by andrewmarmion** [comment]
@hagaigold When I tried in the simulator, using Xcode 10 and iOS 12, I got 896 for the XS Max and the XR.

**Comment by hagaigold** [comment]
soon enough, we all have to move to sdk 12 **anyway**, from [apple](https://developer.apple.com/news/?id=09122018c):

> Starting March 2019, all new apps and app updates for iPhone, including universal apps, will need to be built with the iOS 12 SDK and support iPhone XS Max.

but still curious if it's  only a simulator error, or also a real device problem. is an application, compiled with  sdk < 12 (11.4), will see wrong screen dimension on XS Max / XR ???

**Comment by timwangdev** [comment]
Please release this patch to v1 branch afterwards also, thx

**Comment by iRoachie** [comment]
Just adding pictures to show. iPhone X on left, iPhone Xs Max on right

<img width="1137" alt="screen shot 2018-09-19 at 9 45 27 am" src="https://user-images.githubusercontent.com/5962998/45757369-2b229800-bbf1-11e8-9190-814fae7eb303.png">

**Comment by brentvatne** [comment]
I'll deploy a fix for this today thanks to this PR https://github.com/react-community/react-native-safe-area-view/pull/44

**Comment by brentvatne** [comment]
released 2.15.0 with support for this. also backported it to 1.x branch and released 1.6.0.

**Comment by ducpt2** [comment]
+1 i update react-navigation to  2.17.0, iphone X safe area work.
But Xs max it not work.
Any help pls?

**Comment by brentvatne** [comment]
@ducpt2 - please create a new issue and show me what you are referring to. follow the template. thank you
