### ISSUE TITLE
After putting deep linking with nested navigator, regular navigation does not work

### ISSUE THREAD

**Issue by khat33b** [react-navigation/react-navigation#4986]
### Current Behavior

After implementing deep linking for nested navigators, deep linking is working perfectly but regular navigation like going from `login` to `main` eg. `this.props.navigation.navigate('main')` is not working.

### Expected Behavior

Navigation from screens of `auth` to screens of `main` should work.

### How to reproduce

Code Sample: 

```
const App = () => <AppNavigator />;

const AppNavigator = createSwitchNavigator({
  splash: SplashScreen,
  auth: () => <AuthStack uriPrefix={`${prefix}auth/`} />,
  main: () => <MainDrawer uriPrefix={`${prefix}main/`} />,
});

const AuthStack = createStackNavigator({
  landing: LandingScreen,
  login: {
    screen: LoginScreen,
    path: 'login',
  },
  register: {
    screen: RegisterScreen,
    path: 'signup',
  },
});

const MainDrawer = createDrawerNavigator({
  Home: {
    screen: HomeStack,
    path: 'home',
  },
  Upsell: {
    screen: UpsellScreen,
    path: 'upsell',
  },
});
```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |^2.11.2
| react-native     |0.56
| node             |8.11.4
| npm or yarn      |6.4.1

**Comment by eriveltonelias** [comment]
Hi @khat33b! 

Can you create a runnable example on https://snack.expo.io please ?

**Comment by brentvatne** [comment]
you would certainly get a warning if you did this and that warning would tell you what you are doing wrong. see: https://reactnavigation.org/docs/en/common-mistakes.html#explicitly-rendering-more-than-one-navigator

**Comment by InVincible2016** [comment]
Change to this should resolve your issue. 
```js
 const AppNavigator = createSwitchNavigator({
  splash: SplashScreen,
  auth: {screen: AuthStack,  uriPrefix: `${prefix}auth/` },
  main: {screen: MainDrawer, uriPrefix:`${prefix}main/`}
});
```
