### ISSUE TITLE
ScrollView is not working with createMaterialTopTabNavigator in Android

### ISSUE THREAD

**Issue by listingzhao** [react-navigation/react-navigation#4987]
### Current Behavior

- Sample code contains a normal TabNavigator, and a TabNavigator inside the scrollview.
- Inside the scrollview TabNavigator work normally under the ios, disappear under the android TAB panel, TAB to switch failure.

### Expected Behavior

- The inside of the scrollview TabNavigator under the ios and under the android can work normally.

### How to reproduce

- re-create the bug on [Snack](https://snack.expo.io/@15101668168/joyous-tortilla) with code that reproduces the bug.
- When the TabNavigator inside the ScrollView, It is working in ios, but not in the android, TAB panel is disappearing in the android, the links below you can see effect.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  2.14.0
| react-native     | 0.57.0
| node             |  v8.11.3
| npm or yarn      | yarn v1.9.2

**Comment by eriveltonelias** [comment]
Hi @listingzhao 

check it  https://snack.expo.io/@eriveltonelias/creatematerialtoptabnavigator-with-scrollview

**Comment by listingzhao** [comment]
Hi, my friend @eriveltonelias 
### Expected Behavior

- The inside of the scrollview TabNavigator under the ios and under the android can work normally.
- createMaterialTopTabNavigator with rolling and rolling of the page, rather than the TAB pane scroll.

example：https://snack.expo.io/@15101668168/creatematerialtoptabnavigator-with-scrollview  In the ios environment operation and have a look,but it is not working in the android environment.

**Comment by brentvatne** [comment]
please post this to http://github.com/react-navigation/react-navigation-tabs
