### ISSUE TITLE
TabBarTestId is always a not found element with detox

### ISSUE THREAD

**Issue by hajermay** [react-navigation/react-navigation#4988]
const MoreStack = createStackNavigator({
MoreScreen: {
screen: MoreScreen,
navigationOptions: {
headerTitle: ,
headerStyle: styles.headerCentered,
},
},

MoreStack.navigationOptions = {
tabBarIcon: ({ tintColor }) => (),
TabBarTestId: 'Child',
};

const PrimaryNav = createBottomTabNavigator({
HomeStack,
NotificationsStack,
InboxStack,
MoreStack,
},

it('should open second menu on tabbar', async () => {
await element(by.id('Child')).tap();
});

**Comment by vonovak** [comment]
You seem to be putting the TabBarTestID on the stack navigator - it needs to go on the tab navigator instead:

```
  createBottomTabNavigator(
    {
      SomeStack: {
        screen: SomeStack,
        navigationOptions: {
          tabBarTestID: yourTestId,
        },
      },
    }
  );
```
