### ISSUE TITLE
The component for route 'Details' must be a react component...

### ISSUE THREAD

**Issue by aidanw** [react-navigation/react-navigation#4989]
### Current Behavior

When I try and import a screen from a seperate file to the 'Rootstack' I cannot navigate to it.
This snack shows my exact problem

https://snack.expo.io/rJ2tCb__m

The error is here https://imgur.com/a/u0A8093

If the 'Details' class is in the 'App.js' file it works, move it out to 'Deets.js' then I get the error

### Expected Behavior

That I don't have to keep my project all in one file :)

### How to reproduce

See this snack
https://snack.expo.io/rJ2tCb__m

### Your Environment
(this is for my real project, the snack just has react-navigation:"2.14.0" and I guess some expo magic fills in the others)
| software         | version
| ---------------- | -------
| react-navigation | "2.14.0"
| react-native     | "0.55.4"
| node             | v8.11.4
| npm or yarn      | Yarn 1.7.0

I hope I am not being an idiot!

**Comment by brentvatne** [comment]
`import DetailsScreen from './Deets'` not `import {DetailsScreen} from './Deets'`
