### ISSUE TITLE
BottomTabNavigator iPhone is ok but iPad the icon and text wrong position 

### ISSUE THREAD

**Issue by luoshuisheng** [react-navigation/react-navigation#4994]
### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |2.12.1
| react-native     |0.55.2
| node             |8.11.3
| npm or yarn      |yarn

```
{navigationOptions: ({navigation}) => ({
            tabBarVisible: !(navigation.state.index > 0),
            tabBarIcon: ({focused, tintColor}) => {
                const {routeName} = navigation.state;
                let iconName;
                if (routeName === 'ZJHome') {
                    iconName = `ios-home${focused ? '' : '-outline'}`;
                } else if (routeName === 'ZJMessage') {
                    iconName = `ios-mail${focused ? '' : '-outline'}`;
                } else if (routeName === 'ZJFind') {
                    iconName = `ios-eye${focused ? '' : '-outline'}`;
                } else if (routeName === 'ZJMy') {
                    iconName = `ios-person${focused ? '' : '-outline'}`;
                }
                return <Ionicons name={iconName} size={28} color={tintColor}/>;
            },
            tabBarLabel: ({focused, tintColor}) => {
                const {routeName} = navigation.state;
                let tabBarLabel;
                if (routeName === 'ZJHome') {
                    tabBarLabel = 'home'
                } else if (routeName === 'ZJMessage') {
                    tabBarLabel = 'message'
                } else if (routeName === 'ZJFind') {
                    tabBarLabel = 'find'
                } else if (routeName === 'ZJMy') {
                    tabBarLabel = 'me'
                }
                return <Text style={{color: tintColor}}>{tabBarLabel}</Text>;
            },
        }),
        tabBarOptions: {
            activeTintColor: zjStyle.color.tabBarActiveTintColor,
            inactiveTintColor: zjStyle.color.tabBarInactiveTintColor,
            style: {
                backgroundColor: zjStyle.color.tabBarColor,
            },
            allowFontScaling:true,
        },
    }
```
iPhone is ok
<img width="306" alt="qq20180914-210314 2x" src="https://user-images.githubusercontent.com/5733846/45551901-d1714500-b861-11e8-9788-fbb3f03a0a89.png">

but iPad is wrong

![image](https://user-images.githubusercontent.com/5733846/45551876-be5e7500-b861-11e8-9e1d-2cfbc57010be.png)

what's wrong ? I have searched the issues, some people have the same problem

**Comment by luoshuisheng** [comment]
I did it according to the official document, but still have this problem

**Comment by brentvatne** [comment]
if you render the text component on its own then you need to style it accordingly. if you change `tabBarLabel` to just return a string then your problem is solved

**Comment by luoshuisheng** [comment]
> if you render the text component on its own then you need to style it accordingly. if you change `tabBarLabel` to just return a string then your problem is solved

sorry, when return a string , like this`tabBarLabel:'haha',`, it works,
<img width="310" alt="qq20180915-010525 2x" src="https://user-images.githubusercontent.com/5733846/45564572-72bcc300-b883-11e8-89d1-a32e8737769b.png">

but when return a different string according to condition, then string disappear, In fact , I need to return different string, maybe I did incorrectly, please help find it out , thanks 
```
 tabBarLabel: ({focused, tintColor}) => {
                const {routeName} = navigation.state;
                let tabBarLabel;
                if (routeName === 'ZJHome') {
                    tabBarLabel = 'home'
                } else if (routeName === 'ZJMessage') {
                    tabBarLabel = 'message'
                } else if (routeName === 'ZJFind') {
                    tabBarLabel = 'find'
                } else if (routeName === 'ZJMy') {
                    tabBarLabel = 'me'
                }
                return tabBarLabel;
            },
```
<img width="321" alt="qq20180915-004847 2x" src="https://user-images.githubusercontent.com/5733846/45563857-36886300-b881-11e8-8093-173563d243a9.png">

**Comment by luoshuisheng** [comment]
> if you render the text component on its own then you need to style it accordingly. if you change `tabBarLabel` to just return a string then your problem is solved

sorry , when return like ` tabBarLabel:'haha',`, it works
<img width="310" alt="qq20180915-010525 2x" src="https://user-images.githubusercontent.com/5733846/45564934-97fe0100-b884-11e8-8f80-60ca7defb4d0.png">
but when return different string according to routeName, then string disappear
maybe I did incorrectly , please help find it out , thanks 
```
 tabBarLabel: ({focused, tintColor}) => {
                const {routeName} = navigation.state;
                let tabBarTitle = '';
                if (routeName === 'ZJHome') {
                    tabBarTitle = '首页'
                } else if (routeName === 'ZJMessage') {
                    tabBarTitle = '消息'
                } else if (routeName === 'ZJFind') {
                    tabBarTitle = '发现'
                } else if (routeName === 'ZJMy') {
                    tabBarTitle = '我'
                }
                 return tabBarTitle;
            },
```
<img width="321" alt="qq20180915-004847 2x" src="https://user-images.githubusercontent.com/5733846/45565007-e8755e80-b884-11e8-99fc-01ac8535eddd.png">
