### ISSUE TITLE
Stack navigator momentarily flashes header incorrectly

### ISSUE THREAD

**Issue by robertsami** [react-navigation/react-navigation#4997]
### Current Behavior

https://snack.expo.io/@robsami/reactnavigationbug

This code opens to one screen, and then sets a timeout to navigate to another screen which is a wrapper around a separate stack. All screens involved have null header

The incorrect behavior here is the quick display of a header when navigation between the initial and the second screen occurs. A header renders on the first screen right as its being animated away. It's visible and jarring

### Expected Behavior

The first screen should remain unchanged as the second screen animates on top of it

### How to reproduce

https://snack.expo.io/@robsami/reactnavigationbug

![ezgif-1-f5613a9d7d](https://user-images.githubusercontent.com/1457684/45578839-be964a80-b838-11e8-9d8b-b3ca0f9b89ce.gif)

**Comment by eriveltonelias** [comment]
Hi @robertsami, 

if you add `headerMode: 'none'` will works. 

https://snack.expo.io/@eriveltonelias/reactnavigationbug
