### ISSUE TITLE
IOS Bug: Different colors in the header bug.

### ISSUE THREAD

**Issue by iiandrade** [react-navigation/react-navigation#4999]
### Current Behavior

When I have two screens with a different background color header, when I click the back button, while the screen transition data 2 to 1 (returning to previous) occurs, the background of the screen 2 header changes.

This only occurs when I use the back button. When I use the back gesture, it does not happen.

![Screenshot](https://img.vim-cn.com/cf/00d5fc5eaf39cfe29308093fb7173f9f17b23f.gif)

**This happens only in IOS.**

### Expected Behavior

The desired behavior should be the same when using the return gesture.

### How to reproduce

Create two screens with a header with different background colors. Then navigate among them!

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.14.0
| react-native     | 0.56.0
| node             | 10.9.0
| npm or yarn      | 1.10.0

**Comment by eriveltonelias** [comment]
Hi @iiandrade! 

Try to add `headerMode ` on your stack and then will works. :) 

https://reactnavigation.org/docs/en/stack-navigator.html
