### ISSUE TITLE
Navigating to previous screen automatically

### ISSUE THREAD

**Issue by dhiidemo1** [react-navigation/react-navigation#5000]
This is my router class:

export const RootStack = createStackNavigator({
  Login: {
    screen: Login,
    navigationOptions: {
      title: 'Login',
      header: null //this will hide the header
    },
  },
  Home: {
    screen: Home,
    navigationOptions: {
      headerTitleStyle: {position: 'absolute', start:0, fontSize:25}, //this will put title on left side
      title: 'Home',
      headerLeft: null, //this will hide the back button
      headerStyle: {backgroundColor: '#283593',borderBottomWidth: 0},
      headerTintColor: '#ffd600', //this will change title color
      headerBackTitle: ' ',
      gesturesEnabled: false,
    },
  },
  Dashboard: {
    screen: Dashboard,
    navigationOptions: {
      headerTitleStyle: {position: 'absolute', start:0, fontSize:25}, //this will put title on left side
      title: 'Dashboard',
      headerStyle: {backgroundColor: '#283593', borderBottomWidth: 0},
      headerTintColor: '#ffd600', //this will change title color
    },
  },
});

**When navigating from Home screen to Dashboard Screen, the Dashboard screen renders and navigating back to Home screen automatically. I tried so many things but haven't found any solution.**

**Comment by roman-osadchuk** [comment]
have the same problem and my createStackNavigator configuration is kind of identical

**Comment by eriveltonelias** [comment]
Hi @dhiidemo1, 

Can you reproduce a runnable example on https://snack.expo.io please?

**Comment by YongzhaoZhang** [comment]
Same issue for me. When I use navigation.navigate go to next page, it automatic go back and then go to next page, but it's only for one flow, I spent a few hours and I didn't find any bug in the code.

**Comment by dhiidemo1** [comment]
The Problem is with timer interval, i put an interval in my login page before navigating to home screen.

`this.interval = setInterval(() => {
            if (value === 'true') {
               //navigating to home screen
                this.props.navigation.navigate('Home')
            }else{
                this.setState({isLoggedIn: false});
            }
          }, 2000);`
