### ISSUE TITLE
App initializes with blank screen 

### ISSUE THREAD

**Issue by adamnator92** [react-navigation/react-navigation#5002]
### Current Behavior
https://reactnavigation.org/docs/en/navigating-without-navigation-prop.html
I'm try to navigation to other screen without navigation props, after setting up NavigationService
App initialized with blank screen, after apply this line of code
`ref={navigatorRef => { NavigationService.setTopLevelNavigator(navigatorRef) }}`
it work well when turn on chrome debugger.

### Expected Behavior
able to navigation without navigation props

### How to reproduce
https://snack.expo.io/rkeByAQuQ

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.13.0
| react-native     | 0.56.0
| node             | v9.6.1
| npm or yarn      | 6.4.0

**Comment by brentvatne** [comment]
@adamnator92 - the snack that you linked to works as expected for me. the problem is likely a race condition - you try to call navigate on the navigation service before `setTopLevelNavigator` has been called

**Comment by adamnator92** [comment]
@brentvatne i have a previous project using 2.12.0 version or react-navigation, i reuse the code like the snack i provided, it worked. but since 2.13.0 start, it only work when chrome debugger is turn on.

**Comment by brentvatne** [comment]
@adamnator92 - I need to be able to reproduce it. I ran the snack you shared and it works properly

**Comment by adamnator92** [comment]
@brentvatne thank for you assist, finally it works! 

after i upgrade it to latest version 2.17.0 and did some
```
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.
  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.
```

**Comment by brentvatne** [comment]
thanks for following up @adamnator92!

if you run into this issue again and manage to create a reproducible example i'd be very interested in testing it out!
