### ISSUE TITLE
How to style a Navigator in a async way

### ISSUE THREAD

**Issue by dengue8830** [react-navigation/react-navigation#5003]
This is a question, sorry but i already asked in discord and stackoverflow and i don't know who else to ask

### Question

https://stackoverflow.com/questions/52256950/how-to-style-a-navigator-in-a-async-way

### Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.12.1
| react-native     | 0.55.4
| node             | 8.11.3
| npm      | 5.6.0

**Comment by eriveltonelias** [comment]
Hi @dengue8830. 

https://snack.expo.io/@eriveltonelias/createbottomtabnavigator-with-style-from-server

**Comment by dengue8830** [comment]
hi @eriveltonelias i just found the problem, when the tab navigator is generated within the wrapper their components can't navigate outside the tab navigator's routes. [Here](https://snack.expo.io/@dengue8830/createbottomtabnavigator-with-style-from-server) is an example. Can you help me with this? thanks

**Comment by dengue8830** [comment]
sorry, this is a separate case, so i have created the correct issue for it #5069
