### ISSUE TITLE
react-native-screens breaks use in react-native-web

### ISSUE THREAD

**Issue by enewbury** [react-navigation/react-navigation#5004]
### Current Behavior

When using react-navigation 2.14 with react-native-web, app crashes with:
`Uncaught TypeError: (0 , _reactNative.requireNativeComponent) is not a function`

### Expected Behavior

React navigation should continue to work with react-native-web

### How to reproduce

```
create-react-native-app myApp --with-web-support
yarn add react-navigation
yarn web
```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.14.2
| react-native     | 0.56.1
| node             | 8.11.2
| npm or yarn      | 1.9.4

Note: Based on my research, this error occurs because in the new version of react-navigation, react-native-screens is used by default, importing NativeView.  screens.js uses requireNativeComponent from react-native which is not implemented in react-native-web.  Perhapse making the use of react-native-screens optional would solve.

**Comment by flybayer** [comment]
Same

**Comment by MrPluto** [comment]
[discuss](https://github.com/necolas/react-native-web/issues/507)

**Comment by brentvatne** [comment]
@kmagiera - I guess we need to provide a screens.web.js

**Comment by brentvatne** [comment]
this is resolved upstream now, next time we update react-native-screens this will be resolved. you can use custom yarn resolution to workaround it for now

**Comment by grit96** [comment]
@brentvatne can you update `react-native-screens` to `alpha.14` to fix this bug?

**Comment by benevbright** [comment]
I suppose it breaks Expo Snack as well.

**Comment by EthanCo81** [comment]
It's been over a year, is there any update to this issue where it doesn't break expo snacks anymore?
