### ISSUE TITLE
Header.js link in createStackNavigator docs is broken

### ISSUE THREAD

**Issue by thallada** [react-navigation/react-navigation#5009]
Specifically in this section: https://reactnavigation.org/docs/en/stack-navigator.html#headerleft

Leads to a github 404 and I'm having trouble figuring out what file it was supposed to link to.

**Comment by JoseVf** [comment]
Actually that fix was merged 20 days ago. [PR here](https://github.com/react-navigation/react-navigation.github.io/pull/238)

**Comment by brentvatne** [comment]
oh great, I guess we just need to re-deploy

**Comment by brentvatne** [comment]
cc @vonovak

**Comment by eriveltonelias** [comment]
Solved! :D
