### ISSUE TITLE
react-navigation v2 + modalbox + flatlist cause crash

### ISSUE THREAD

**Issue by tandat2209** [react-navigation/react-navigation#5011]
### Current Behavior

- What code are you running and what is happening?
I was using react-navigation@1, and then I upgrade to v2. Everything works fine, except for one screen in **TabNavigator** which I am using [react-native-modalbox](https://github.com/maxs15/react-native-modalbox) + **FlatList**. When I open the modal first time, it's okay. but when I reopen it. It crashes. 

Especially, it happens on ANDROID when:
1. The screen inside tab navigator
2. The screen has a list (FlatList, not sure if same with other lists)
3. The screen has modalbox 

### Expected Behavior
The modal shows again.

### How to reproduce
Example code on snack: https://snack.expo.io/@dattannguyen/react-navigation-modalbox-flatlist

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.14.2
| react-native     | ^0.55.3
| node             | 8.11.2
|  yarn      | 1.7.0

### Workaround
Render ModalBox before FlatList

**Comment by eriveltonelias** [comment]
Hi @tandat2209! 

Sorry that you're having this issue, but looks like this isn't related with react navigation.
