### ISSUE TITLE
react-navigation createMaterialTopTabNavigator does not back sequentially

### ISSUE THREAD

**Issue by forster-thomas** [react-navigation/react-navigation#5012]
Hey guy's, what'is up?
I have a big problem, and I don't know what to do.

I have 3 Tabs inside a StackNav.
If am I on the third tab, and click on android back button, I just go back to the FIRST tab, not to the second tab. Why does it happen?

I wanna to pass from the first tab, to the second and finaly to the third tab, and back in the same order: third > second > first.

![image](https://user-images.githubusercontent.com/38217705/45795889-75992880-bc74-11e8-9ce0-651d32e4b429.png)

Here is the tabs.

Thanks for now.

### My Environment
    "color": "^3.0.0",
    "core-js": "^2.5.7",
    "firebase": "^5.5.0",
    "hoist-non-react-statics": "^3.0.1",
    "lodash": "^4.17.11",
    "moment": "^2.22.2",
    "native-base": "^2.8.0",
    "prop-types": "^15.6.2",
    "react": "16.4.1",
    "react-native": "0.57.0-rc.4",
    "react-native-datepicker": "^1.7.2",
    "react-native-dropdownalert": "^3.5.0",
    "react-native-elements": "^1.0.0-beta5",
    "react-native-extended-stylesheet": "^0.9.0",
    "react-native-sha256": "^1.1.1",
    "react-native-vector-icons": "^5.0.0",
    "react-navigation": "^2.14.2",
    "react-redux": "^5.0.7",
    "redux": "^4.0.0",
    "redux-form": "^7.4.2",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.3.0"

**Comment by brentvatne** [comment]
this is just the behavior for back right now. if you'd like to implement more behavior types there is an open rfc for it: https://github.com/react-navigation/rfcs/pull/2
