### ISSUE TITLE
Configure lint / snippets for react-navigation

### ISSUE THREAD

**Issue by AleksanderDudek** [react-navigation/react-navigation#5016]
Hello,

Has anyone perhaps configured lint or code snippets for react-navigation? I just lost like 14hrs 
in nested navigator just because I didn't notice spelling mistake in navigation... 

Just wondering if someone did that or has idea where to start.

Thanks!

**Comment by brentvatne** [comment]
you could try using typescript or flow or something. if you can provide more information then please open an issue on https://github.com/react-navigation/rfcs/issues and we can discuss further there! thanks
