### ISSUE TITLE
getParam function with parameter

### ISSUE THREAD

**Issue by fauzynurn** [react-navigation/react-navigation#5020]
I actually implemented search bar in header and i have to use a function to be implemented on navigationOptions. And the only one way i take is to send the function to navigationOptions with setParams and receive the function inside navigationOptions with getParam. But the problem is that i have to send the user's input from the search bar to the function and getParam function seems not allows me to put any parameter to my function. Here's my piece of code : 

    class SearchUser extends Component {
         componentDidMount() {
            this.props.navigation.setParams({ doSomething: this.doSomething });
         }
         //below is the function i want to use inside navigationOptions
        doSomething = _.debounce(text => {
            console.log(text);
        }, 25);

        static navigationOptions = ({ navigation }) => {
             return {
                headerTitle: (
                    <TextInput
                           style={{ height: 48, fontSize: 17}}
                           autoFocus={true}
                           placeholder="Search"
                           onChangeText={text => navigation.getParam('doSomething')} // how can i put 'text' as 
                           a parameter on doSomething method?
                     />
                 ),
                 headerStyle: { height: 50}
                };
             };

I did searching a lot and find simpler way to solve this. i made a variable which references to SearchUser and use that variable in my onChangeText. The code now should look like this : 

    let instances = null
    class SearchUser extends Component {
         componentDidMount() {
            instances = this
         }
        doSomething = _.debounce(text => {
            console.log(text);
        }, 25);

        static navigationOptions = ({ navigation }) => {
             return {
                headerTitle: (
                    <TextInput
                           style={{ height: 48, fontSize: 17}}
                           autoFocus={true}
                           placeholder="Search"
                           onChangeText={text => instances.doSomething(text)}
                     />
                 ),
                 headerStyle: { height: 50}
                };
             };

The code above worked but i'm not sure if this is considered as good practice or not. Is there any better way to do this? Thanks!

**Comment by Jekiwijaya** [comment]
Becareful with these pattern.

if component `SearchUser` is double in Navigation state, the variable `instance` will always refer to the latest, even the latest SearchUser have been unmounted.

Even the pattern similiar with being used in [`NavigationService`](https://reactnavigation.org/docs/en/navigating-without-navigation-prop.html) is kind of valid, because Navigator usually just one in entire application.

Anyway, I think better to ask this things in StackOverflow.

**Comment by giantss** [comment]
@fauzynurn 
```
_doSomething = (text) => {
   console.log(text);
}

 componentDidMount() {
        this.props.navigation.setParams({
            doSomething: this._doSomething
        })
    }

```
