### ISSUE TITLE
Can i use withNavigation with Function instead of using React.Component?

### ISSUE THREAD

**Issue by zxccvvv** [react-navigation/react-navigation#5024]
I have read the docs and search for the similar step to solve my issue, the first step I have read [Navigation Prop](https://v1.reactnavigation.org/docs/navigation-prop.html) that tell me 
> It's important to highlight the navigation prop is not passed in to all components; only screen components receive this prop automatically! React Navigation doesn't do anything magic here

so my next question is how to **manually** add `navigation prop` to specific component?
but I found [withNavigation](https://v1.reactnavigation.org/docs/connecting-navigation-prop.html).
so my next question is can I used `withNavigation` with the function instead of `React.Component`?
but I can't find the answer for now

actually I want to navigating any failed token to login screen, so I used `interceptor axios` (i'm installed apisauce) and the code look's like :

```
export default api = create({
  baseURL: "URL",
  headers: {Authorization: Token},
  timeout: 40*1000
})
api.axiosInstance.interceptors.response.use((response)=>{
  return response
}, (error) => {
  if(error.response == undefined){
    return Promise.reject(
    Alert.alert("Perhatian","Tidak dapat terhubung ke server \n\n Cek koneksi internet anda",[
      {text:"OK", onPress:()=>BackHandler.exitApp()}
    ])
    )
  } else if (error.response.status === 401) {
    return Promise.reject(
      goToLogin("Login", null)
    );
  }
})
```
and I have a file called `routeNavigate.js` with this function:
```
export function goToLogin(){
  return(
    Alert.alert("Peringatan", "Sepertinya akun ini sudah login di perangkat lain\n\nsilahkan logout dan login kembali untuk dapat mengakses kembali",[
      {text:'Logout', onPress:()=>{
        console.log(this.props) // i got undefined on this line
        this.props.navigation.dispatch(
          NavigationActions.navigate({
            routeName:"Login",
            key:"Login",
          })
        ),
        deleteAllUser()
      }}
    ],{cancelable: false})
  )
}
```

have tried this but still got an error :
```
export function goToLogin2(){
  withNavigation(goToLogin())
}
```

is there some way to use `this.props.navigation` in `goToLogin()` and used it globally?

and additional question is what the latest version of react-navigation V1?

| software         | version
| ---------------- | -------
| react-navigation | ^1.5.13
| react-native     | ^0.53.0
| node             | 8.9.1
| npm | 6.4.1
| yarn | 1.10.0

**Comment by brentvatne** [comment]
https://reactnavigation.org/docs/en/navigating-without-navigation-prop.html

**Comment by brentvatne** [comment]
> and additional question is what the latest version of react-navigation V1?

I like to use https://semver.npmjs.com/ to explore versions

**Comment by shen-lan** [comment]
Hi, Do you have others way?
