### ISSUE TITLE
StackNavigation swipe gesture animation doesn't work on iPhone XR

### ISSUE THREAD

**Issue by gaykov** [react-navigation/react-navigation#5025]
### Current Behavior

I have an application that uses StackNavigator. I'm creating navigation this way:
```
export default createSwitchNavigator({
  Home,
  MainScreen: createStackNavigator({
    NotificationsList,
    AddNew,
  }, {
    headerMode: 'none',
    initialRouteName: 'NotificationsList',
  }),
}, {
  headerMode: 'none',
  initialRouteName: 'Home',
});
```

Swiping to get back to previous screen works fine on all iPhones except new ones (XR, XS). On the new iPhones swiping animation is broken.

Here's the video that explains it (the same app is running on iPhone X and iPhone R, both on iOS 12): https://www.dropbox.com/s/se6dkf8iew6bc5g/stack-navigator-animation-issue.mov?dl=0

### Expected Behavior

- I expect that animations between screens will work just as on old iPhones.

### How to reproduce

I wasn't be able to open react navigation's demo app because of the `AccesebilityInfo`, but the issue should be also available there: https://github.com/react-navigation/react-navigation/tree/master/examples/NavigationPlayground

Also, it can be found inside this app: https://github.com/insiderdev/office-assistant, Navigator is created here: https://github.com/insiderdev/office-assistant/blob/master/src/modules/navigation/Navigator.js

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | `2.16.0`
| react-native     | `0.57.1`
| node             | `v8.11.3`
| npm or yarn      | `yarn 1.5.1`

**Comment by brentvatne** [comment]
this seems to just be an issue with the iphone xr simulator. notice that the same thing happens if you use the settings app, for example.

http://url.brentvatne.ca/98AXaI

**Comment by s349856186** [comment]
@gaykov Do you fix it? How to do
