### ISSUE TITLE
Fix iOS voiceover for tabs

### ISSUE THREAD

**Issue by brentvatne** [react-navigation/react-navigation#5029]
> Tabs — When reading a selected tab in the tab bar at the bottom, assuming there are 5 tabs named Home, People, Chat, Settings, natively it should say "Selected, home, tab, one of five" and for an unselected tab it should say "People, tab, two of five". In RN it just says "Home" and "People".

**Comment by pzatorski** [comment]
@brentvatne I think no one is up to this one, so I can go ahead to create PR for this tomorrow or Friday.

**Comment by superburrito** [comment]
Hey @brentvatne @pzatorski I followed up on this issue with a PR a few days ago: https://github.com/react-navigation/react-navigation-tabs/pull/61

**Comment by pzatorski** [comment]
Hey @superburrito, thanks for the fix, everything looks good to me

**Comment by eriveltonelias** [comment]
hey @brentvatne, should we close this issue? looks like the solution is merged.

**Comment by MoOx** [comment]
FYI current solution is "hand made". `accessibilityLabel` currently generate this text, while now, we have the ability to describe (https://github.com/react-navigation/tabs/pull/90#issuecomment-516785800) that we have a tab in a tablist, which should generate the correct sentence without manual trick (better for i18n, OS will handle that). 
I will see if I can do something about it but I just saw that react-navigation currently use tabs v1.x...

**Comment by MoOx** [comment]
AFAIK it still an issue
