### ISSUE TITLE
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined

### ISSUE THREAD

**Issue by thaprozz** [react-navigation/react-navigation#5030]
I'm dealing with a JSON response in React Native that's coming from the WordPress REST API, containing pages with each an (profile page) ID, title and featured image.

Using a FlatList, I have created a screen with featured images and titles for each (Artist) page. I want to add the functionality to navigate to each individual page by clicking on an item in the FlatList, and passing the title, featured image and (later) the content of the regarding page to the next screen to display this information (probably based on the ID). Here is the code:

https://snack.expo.io/@jvdl2711/artist-navigation

I'm getting an error at the moment - saying that the a string is expected, but an undefined type was found. I used to do it in a different way, but I'm unable to pass the ID (which should be the identifier to pass the data to the next screen) to open a specific generated screen for each artist.

**Notes**

Please, don't mind the titles at the moment. I still have a small unsolved issue regarding unicodes, but I think this won't matter when passing the titles to another screen.

**Comment by brentvatne** [comment]
this is unrelated to react-navigation. `renderItem` is incorrect, if you change it to `renderItem={({ item }) => this.renderRow(item)}` it works

**Comment by thaprozz** [comment]
Unfortunately it does not. That's a function that renders the elements, but it removes the functionality that makes them clickable, and now it's not possible to trigger the navigation part at all.

**Comment by brentvatne** [comment]
@thaprozz - `(({ item }) => this.renderRow(item), this._renderListItem)` - what do you expect this to do? regardless again this is unrelated to react-navigation, this is a question for stackoverflow about how to use flatlist

**Comment by thaprozz** [comment]
@brentvatne It was supposed to trigger to different function: one to render the elements (like it does when you remove the second parameter), and one that gathers the data to 'push' them to a specific page based on the objects's ID (using navigation):

```
_onAlertTypePressed(typeId: any, typeName: any, imageUrl: any){

        this.props.navigator.push({
            screen: 'Artist',
            title: 'Artist',
            passProps: {
                alertId: typeId,
                alertName: typeName,
                alertImage: imageUrl,
            }
        });
    }
```

**Comment by brentvatne** [comment]
renderItem accepts one parameter which is a function: https://facebook.github.io/react-native/docs/flatlist#renderitem

`renderItem={({ item }) => this.renderRow(item), this._renderListItem}` makes no sense. see https://snack.expo.io/@notbrent/humiliated-truffle for an example. notice that 2 is being rendered as the value. so in your code, the function after the comma is being used fo renderItem

**Comment by brentvatne** [comment]
if you're still confused please open a question on stackoverflow! :)
