### ISSUE TITLE
Fix iOS "Button Shapes"

### ISSUE THREAD

**Issue by sfcgeorge** [react-navigation/react-navigation#5031]
Turning on the "Button Shapes" accessibility setting should make toolbar and tab bar buttons underlined to be consistent with iOS native navigation elements. 

---

### Current Behavior

Top navigation buttons look the same. Tab bar buttons look the same.

### Expected Behavior

Buttons should be underlined when "Button Shapes" is turned on.

### How to reproduce

- Load an example app that has navigation screens with button text (not just the back chevron).
- Turn on "Button Shapes" in Settings > General > Accessibility
- Compare to a native UI app such as Contacts

### Your Environment

iOS 11 or iOS 12

In iOS 10 "Button Shapes" actually gave buttons an arrow shaped box around them, which would be far harder to mimic.

**Comment by danibonilha** [comment]
Hi is there anyone tracking this issue ?  Can I take it? 

Thanks

**Comment by brentvatne** [comment]
@danibonilha - go for it! as far as I know, nobody is working on it

**Comment by danibonilha** [comment]
From what I'm looking at the code, the changes should be done in react-navigation-stack, am I  at the right track ? haha

**Comment by brentvatne** [comment]
yup!

**Comment by danibonilha** [comment]
Sorry, I couldn't keep track on this, if anyone is interested is up for grabs!

**Comment by hawkrives** [comment]
If I comment on this, will the stale bot reopen this?

I'm interested in working on this enhancement, as well :-)
