### ISSUE TITLE
How to update contentComponent with new screen at run time.

### ISSUE THREAD

**Issue by minhaj** [react-navigation/react-navigation#5034]
Hi,

I have a createDrawerNavigator in my App with some screen(side menu) assigned to contentComponent.
I want to update contentComponent with new screen at run time, like on button click on side menu new screen will replace the side menu and drawer would remain open.

Any help would be highly appreciated. Thanks!!!

**Comment by brentvatne** [comment]
hi there! this is a question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.
