### ISSUE TITLE
BackHandler throws error Subscriptions[i] is not functions

### ISSUE THREAD

**Issue by adirzoari** [react-navigation/react-navigation#5037]
### Current Behavior

BackHandler in android throws error 
'subscriptions[i] is not function

### Expected Behavior

goBack or exit from app

```
  componentWillMount() {
        this.setState({ nowMounted: true })
        BackHandler.addEventListener('hardwareBackPress', this.backPressed);
        AppState.addEventListener('change', this._handleAppStateChange)
    }

    componentWillUnmount(){
        BackHandler.removeEventListener('hardwareBackPress', this.backPressed);
        AppState.removeEventListener('change', this._handleAppStateChange)
    }


    backPressed = (navigationState) => {
        return false;
    }




```
![screenshot_2018-09-25-15-52-49-249_com nirzoari](https://user-images.githubusercontent.com/20258998/46015570-5159a380-c0db-11e8-9cf5-e38ee6d70cb7.png)
### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |^2.16.0
| react-native     | 0.55.4
| node             | v8.11.3
| npm or yarn      | 6.3.0

**Comment by brentvatne** [comment]
this error is coming from react-native, not react-navigation ;)

**Comment by vonovak** [comment]
@adirzoari I recommend you read the docs on custom android back handling https://reactnavigation.org/docs/en/custom-android-back-button-handling.html

**Comment by dragonStandard123** [comment]
I tried as that doc described, but failed.
I had some doubt about the possibility to handle (e.g. register, addListener) the methods of a object on its constructor function.
So I created a static function, and handled on it.

```
function onBack() {
    console.log('onBack');
    // Customizing...
    // NavigationService.goBack();
    // return true;
}

class TestScene extends PureComponent {
    _didFocusSubscription;
    _willBlurSubscription;
   static navigationOptions = ({navigation}: any) => { ... }
   constructor(props) {
         this._didFocusSubscription = props.navigation.addListener(
            'didFocus',
            payload =>
                BackHandler.addEventListener(
                    'hardwareBackPress',
                    onBack
                )
        );
  }
...
}

```

**Comment by ydv0121** [comment]
+1
