### ISSUE TITLE
Header.HEIGHT off by 24 on iPhone X

### ISSUE THREAD

**Issue by raphaelrk** [react-navigation/react-navigation#5041]
### Current Behavior

I'm using `Header.HEIGHT` (from `import { Header } from 'react-navigation';`) for positioning a view, but it shows up incorrectly on iPhoneX. Specifically, it's 24 units too short. Screenshots from the snack simulator and my iPhone X:

<img width="427" alt="screen shot 2018-09-26 at 4 52 44 pm" src="https://user-images.githubusercontent.com/3377845/46108687-a5808880-c1ac-11e8-825c-1baa6a26151c.png">

![img_4324](https://user-images.githubusercontent.com/3377845/46108616-808c1580-c1ac-11e8-87f4-88738f44f3b6.PNG)

### How to reproduce

- [Snack link](https://snack.expo.io/@raphaelrk/intelligent-bubblegum)

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.17.0
| react-native     | https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz
| node             | v10.10.0
| npm or yarn      | npm 6.4.1

**Comment by brentvatne** [comment]
you shouldn't depend on the height unfortunately. you need to add the additional offset for the safe area to that. the `HEIGHT` constant is not the ideal way to do things it's just the current state. it should be thought of as the base height not including safe areas

**Comment by brentvatne** [comment]
I marked this as wontfix because `Header.HEIGHT` is just a temporary workaround and once https://github.com/facebook/react-native/pull/20999 lands we can build a more comprehensive API for this

**Comment by Bautista-Baiocchi-lora** [comment]
![Screen Shot 2019-04-26 at 17 11 24](https://user-images.githubusercontent.com/14324229/56833934-6c91ba80-6846-11e9-9b9a-d9b7a03211fe.png)
Is this issue causing my iOS header to render incorrectly(picture attached)? @brentvatne

**Comment by Bautista-Baiocchi-lora** [comment]
> ### Current Behavior
> I'm using `Header.HEIGHT` (from `import { Header } from 'react-navigation';`) for positioning a view, but it shows up incorrectly on iPhoneX. Specifically, it's 24 units too short. Screenshots from the snack simulator and my iPhone X:
> 
> <img alt="screen shot 2018-09-26 at 4 52 44 pm" width="427" src="https://user-images.githubusercontent.com/3377845/46108687-a5808880-c1ac-11e8-825c-1baa6a26151c.png">
> 
> ![img_4324](https://user-images.githubusercontent.com/3377845/46108616-808c1580-c1ac-11e8-87f4-88738f44f3b6.PNG)
> 
> ### How to reproduce
> * [Snack link](https://snack.expo.io/@raphaelrk/intelligent-bubblegum)
> 
> ### Your Environment
> software	version
> react-navigation	2.17.0
> react-native	https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz
> node	v10.10.0
> npm or yarn	npm 6.4.1

How did you fix this?

**Comment by PavelPolyakov** [comment]
In my case I had component inside `SafeAreaView` and wanted to make an offset with a height of the `react-navigation` header. So I had to explicitly grab the values from the library source code:
```
                paddingTop: Platform.select({ ios: 44, android: 56 }),
```

It would be useful, if you export `APPBAR_HEIGHT` separately from the `Header.HEIGHT`.

Thanks for the library, it's great!

**Comment by hyochan** [comment]
@brentvatne Is there any chance to use `Header.HEIGHT` in `react-navigation@next` which I believe will be `v5`? I can't find anything related to `Header.HEIGHT` currently.

**Comment by hyochan** [comment]
Could anyone kindly give any story for this?
