### ISSUE TITLE
How to navigate/redirect from HOC?

### ISSUE THREAD

**Issue by ddereszewski** [react-navigation/react-navigation#5043]
I cannot figure this out. My case is the APP which doesn't require a login, but some screens do. My idea is to create HOC which will check permission and redirect back to log in on chosen screens.

I redirect with normal navigate function. 
When I click the button that should redirect me to forbidden screen effect is like that:
1. I see the transition to the forbidden screen, 
2. then login screen is shown as Modal
3. Then I'm redirected back to the forbidden screen. 

What I want to achieve is a nice solution that avoids redirecting to the forbidden screen showing instead login screen or complete your profile screen.

My HOC

```javascript
export function MustBeLoginAndCompleteProfile(Comp) {
    class NewComp extends React.PureComponent {

        constructor(props){
          super(props);

          if(!props.isAuthenticated){
              setTimeout(()=> {
                  props.navigation.navigate({
                      routeName: 'Login'
                  })
              },0);

          }
        }

        componentWillReceiveProps (newProps) {
          console.log(newProps);
        }

        render() {
            return <Comp />
        }
    }


    const mapStateToProps = (state) => {
        return {
            isAuthenticated: state.login.isAuthenticated,
        }
    }

    return withNavigationFocus(connect(mapStateToProps, null)(NewComp))
}
```

My Router definition. **GameDetails** is the forbidden screen. 

```javascript 
const gameTab = createStackNavigator({
    Games: {
        screen: GamesScreen,
        cardStyle: Styles.cardStyle,
        navigationOptions : {
            ...defaultHeaderOptions,
            cardStyle: Styles.cardStyle,
            title: I18n.t('title_scores'),
        },
    },
    GameDetails: {
        screen: MustBeLoginAndCompleteProfile(GamesDetailsScreen),
        navigationOptions : {
            ...defaultHeaderOptions,
            title: I18n.t('title_score_details'),
        },
    },
    GamesDetailsPreviewScreen: {
        screen: GamesDetailsPreviewScreen,
        navigationOptions : {
            ...defaultHeaderOptions,
            title: I18n.t('title_score_details'),
        },
    }
},{

});
```

**Comment by brentvatne** [comment]
hi there! this is a question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.

**Comment by ihwf** [comment]
I have this issue too, I hope that can have  <Redirect to="route name" /> react element
