### ISSUE TITLE
There is any way to createStackNavigator in an Alert/Dialog?

### ISSUE THREAD

**Issue by mydesweb** [react-navigation/react-navigation#5044]
There is any way to navigate in a custom  Alert View / Dialog ? I need some hints to know how to implements this. Please check the image below.

![img_7749](https://user-images.githubusercontent.com/5901386/46169496-fd4deb00-c2a3-11e8-8314-be2a5ba609b0.PNG)

**Comment by brentvatne** [comment]
i don't think stack navigator will handle this cause very well right now. you can post a feature request to https://expo.canny.io/feature-requests or try to build it yourself :) see https://reactnavigation.org/docs/en/custom-navigators.html and look at https://github.com/react-navigation/react-navigation-stack and https://github.com/react-navigation/react-navigation-tabs to learn how to build navigators
