### ISSUE TITLE
 error: uncompiled PNG file passed as argument. Must be compiled first into .flat file..

### ISSUE THREAD

**Issue by smaltby** [react-navigation/react-navigation#5045]
### Current Behavior

When trying to build an .apk, the build fails with the following error:

\<project-directory\>/android/app/build/intermediates/res/merged/debug/drawable-hdpi/node_modules_reactnavigationstack_dist_views_assets_backicon.png: error: uncompiled PNG file passed as argument. Must be compiled first into .flat file..
error: failed parsing overlays.

### Expected Behavior

The build show not fail.

### How to reproduce

[Here's the simplest repo that demonstrates the bug](https://github.com/smaltby/ExampleProject).

All it has is the code from the first example in the [tutorial](https://reactnavigation.org/docs/en/hello-react-navigation.html)

The commands I'm using to build the apk after cloning the example repository are as follows:
```
yarn install
react-native run-android
react-native bundle --dev false --platform android --entry-file index.js --bundle-output ./android/app/build/intermediates/assets/debug/index.android.bundle --assets-dest ./android/app/build/intermediates/res/merged/debug
cd android
./gradlew assembleDebug
```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.17.0
| react-native     | 0.57.1
| node             | 8.10.0
| yarn      | 1.9.4

**Comment by brentvatne** [comment]
please search issues before posting a new one. there is discussion in an issue on this repo already where i link to the upstream issue causing this: https://github.com/facebook/react-native/issues/16906

**Comment by smaltby** [comment]
That issue is closed as being fixed in the latest version of react native, but the error still occurs with specifically this library.

**Comment by brentvatne** [comment]
look at the contents of this library and you will see it is nothing more than some js files and some png files. there is nothing specific about react-navigation that would cause this problem
