### ISSUE TITLE
StackActions reset is not working

### ISSUE THREAD

**Issue by vatex** [react-navigation/react-navigation#5049]
https://snack.expo.io/@vatex/hello-world-v2

**Comment by vonovak** [comment]
please check out https://snack.expo.io/@react-navigation/hello-world-v2 - I updated the onPress function and moved the react-navigation dep out of beta - it works now

**Comment by vonovak** [comment]
@vatex could you please ask the question on stackoverflow and then paste it here? (SO is more fitting for questions) also please include a runnable expo demo of what does not work, it's hard to help without seeing any code.

**Comment by vonovak** [comment]
locking since the question is here https://github.com/react-navigation/react-navigation/issues/5149
