### ISSUE TITLE
Screen title gets truncated on Android 

### ISSUE THREAD

**Issue by luiskhernandez** [react-navigation/react-navigation#5050]
Hey guys, following a basic tutorial I see that titles always get truncated.
<img src="https://user-images.githubusercontent.com/4315997/46260055-ecb99280-c4a6-11e8-87c0-7455e1bd2204.jpg" width="400" height="590">

### Its also happening on the expo app
<img src="https://user-images.githubusercontent.com/4315997/46260056-ecb99280-c4a6-11e8-867c-e76fd162c7de.jpg" width="400" height="590">

 ###  and in the react-navigation example app 

<img src="https://user-images.githubusercontent.com/4315997/46260057-ecb99280-c4a6-11e8-8369-95431285aff9.jpg" width="400" height="590">

Running in a oneplus 5t.

### Environment

| software         | version
| ---------------- | -------
| react-navigation | ^2.17.0
| react-native     | 0.57.1
| node             | 10.7.0
| npm or yarn      | 6.1.0

**Comment by ravirajn22** [comment]
I think this issue could also be due to the different typeface used in the onePlus OS. Maybe try changing it to default Roboto of Android and check.

**Comment by luiskhernandez** [comment]
@ravirajn22 Thanks so much, that fixed all the apps.  That means that I need to force in my code to use Roboto font, to avoid these?

**Comment by brentvatne** [comment]
wow that's very strange :( I wonder what we should do about that as a library..

**Comment by d3orn** [comment]
Having the exact same issue on my OnePlus 5T. 
The Drawer Items are truncated as well

**Comment by Biplovkumar** [comment]
@d3orn  please send error pic & Environment here. if possible ?

**Comment by d3orn** [comment]
Ok there is no need for pics. I went to the System Settings and changed my phones font from OnePlus Slate(TM) to Roboto and everything works fine

**Comment by Biplovkumar** [comment]
good luck.

**Comment by melbourne2991** [comment]
Had this issue on OPPO models as well, fix was to change the font to Roboto as described above

**Comment by Elias-Graf** [comment]
So just bumped into that issue as well. Is there no fix for it? I mean, surely there is a better way than just changing the font face
