### ISSUE TITLE
Disable navigation gestures when modal is open

### ISSUE THREAD

**Issue by amitv87** [react-navigation/react-navigation#5059]
### Current Behavior

- Gestures performed on [modal](https://facebook.github.io/react-native/docs/modal.html) are passed on to react-navigation
- This causes undesired behaviour if **gesturesEnabled** is set to true in **navigationOptions**

### Expected Behavior

- react-navigation should silently ignore the gestures when modal is open

### How to reproduce

- [Snack](https://snack.expo.io/HJ2YYZW97) to reproduce the bug 
- Open modal from any screen(Screen2 on android) by pressing **open modal** button
- Then swipe from left edge of the screen
- This swiping action either opens drawer or dismisses screen

### My Environment

| software         | version
| ---------------- | -------
| ios          | 11
| android   | 8
| react-navigation | 2.17.0
| react-native     | 0.57.0
| node             | v8.10.0
| npm or yarn      | 5.6.0

related issues https://github.com/react-navigation/react-navigation/issues/4633

**Comment by guopeng1994** [comment]
same issues!

**Comment by lxcid** [comment]
I had same issue as well.

**Comment by fbartho** [comment]
Counter-voice: I would & do expect my modals to support gestures for dismissal unless otherwise configured. So I think this is instead an enhancement request.

**Comment by brentvatne** [comment]
you need to disable the gesture if the modal is open. i don't know how we would detect if someone opened a modal via a component external to react-navigation so this is up to the user. we hope to obviate the need using the modal component in the future.
