### ISSUE TITLE
When using react-native-screens the app will not respond to any interaction after navigate back from modal mode StackNavigator with empty screen interpolator

### ISSUE THREAD

**Issue by jarvisluong** [react-navigation/react-navigation#5066]
### Current Behavior

So basically I make a StackNavigator, make the mode to be 'modal' and then customize the transition that make the duration to be 0 (this is in my own app use case when I'm deciding to test out this library). After navigating back to the previous screen, the app won't respond to any interaction from user.

### How to reproduce

Snack: https://snack.expo.io/@bankify_expo_admin/react-native-screen-stack-empty-interpolation-bug

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.16.0
| expo     |  SDK 30
| node             | 8.10.0
| npm or yarn      | 1.10.4

**Comment by jarvisluong** [comment]
opened a similar issue in https://github.com/kmagiera/react-native-screens/issues/21

**Comment by brentvatne** [comment]
thanks for sharing! you can close this in rn-screens, seems more related to this repo

**Comment by jarvisluong** [comment]
@brentvatne i just got an update
--UPDATE--
It's seem that the 0 duration was not the culprit but because of the empty screenInterpolator: () => ({}), in the transitionConfig

**Comment by DimitryDushkin** [comment]
Kind of the same bug with rn-screens, but I'm just opening within stack navigator Modal from 'react-native' and it is not calling onRequestClose on swipe from left to right gesture. Without rn-screens it works.

It's on iOS.

**Comment by brentvatne** [comment]
this is fixed on the latest version: https://snack.expo.io/@notbrent/react-native-screen-stack-empty-interpolation-bug
