### ISSUE TITLE
Unable to resolve module './withSafeArea'

### ISSUE THREAD

**Issue by lebronjl** [react-navigation/react-navigation#5068]
### Current Behavior

I am trying to use "react-navigation": "2.17.0" with "react-native": "0.57.1" and I get the next error when bundleling:

error: bundling failed: Error: Unable to resolve module `./withSafeArea` from...

### Expected Behavior

react-native run-android to bundle the project correctly.

### How to reproduce

Create a RN 0.57.1 project and add react-navigation 2.17.0. Try to bundle the application

### Your Environment

  React Native Environment Info:
    System:
      OS: Windows 10
      CPU: x64 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
      Memory: 4.17 GB / 15.43 GB
    Binaries:
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.2.0.0 AI-181.5540.7.32.5014246

**Comment by hagaigold** [comment]
i was just set up a test project who work for me (rn 0.57.1 & react-navigation 2.17.0).
you can check-it-out https://github.com/hagaigold/TestSafeArea, and see if it is build for you.

don't open Android Studio, just build it for the command line please.
I used yarn (not npm) so maybe this is the difference..

**Comment by brentvatne** [comment]
https://github.com/react-navigation/react-navigation/search?q=withSafeArea&unscoped_q=withSafeArea

there is no such code in react-navigation

**Comment by GutteApps** [comment]
reverting to 2.14.2 fixed the issue

**Comment by lebronjl** [comment]
@hagaigold thanks for the repo. It worked well for me.
Anyway, my project does not work. I reverted to 2.17.0 and it's working

**Comment by Damoness** [comment]
> d after executing the following command:
> 
> react-native start --reset-cache

thanks
