### ISSUE TITLE
"<" back image not shown in release build

### ISSUE THREAD

**Issue by shinriyo** [react-navigation/react-navigation#5075]
### Current Behavior

- "<" didn't show on release build.

![img_4822](https://user-images.githubusercontent.com/396927/46591078-19972680-caf3-11e8-9f1c-5d6b48119a79.PNG)

### Expected Behavior

- just show "<" image

### How to reproduce

I opened `ios/kazoemon.xcworkspace`. (`kazoemon` is my app name.)
build for release build and I released AppStore.
I downloaded but no "<" image./

My code is below in TypeScript.

```
const RootStack = createStackNavigator(
  {
    Home: {
      screen: HomeScreen,
      navigationOptions: () => ({
        title: "Home"
      })
    },
    Game: {
      screen: GameScreen,
      navigationOptions: () => ({
        title: "トレーニング"
      })
    },
    Details: {
      screen: DetailScreen,
      navigationOptions: () => ({
        title: "設定"
      })
    }
  },
  {
    initialRouteName: 'Home',
  }
);

export default class App extends React.Component {
  render() {
    return (
      <Provider {...stores}>
        <RootStack />
      </Provider>
    );
  }
}
```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.16.0
| react-native     | 0.57.0-rc.3
| node             |  9.10.1
|  yarn      |1.5.1

**Comment by vonovak** [comment]
Thanks for reporting, I believe this is not a problem with react-navigation but react-native itself: https://github.com/facebook/react-native/issues/21309

does this work for you in 0.56?

**Comment by brentvatne** [comment]
yeah the back image is literally just an image, it's nothing special. if it doesn't work then it's another problem unrelated to react-navigation

**Comment by shinriyo** [comment]
is it `react-native`'s bug? mine ios

**Comment by brentvatne** [comment]
yes
