### ISSUE TITLE
accessibilityLabel for back button

### ISSUE THREAD

**Issue by tfsjohan** [react-navigation/react-navigation#5077]
### Current Behavior
- When VoiceOver stops at a back button it only reads "button". I would to be able to set the accessbibilityLabel for the back button both globally for the StackNavigator and individually for each screen.

### Expected Behavior

- Voice Over only reads "button"

### How to reproduce

- Make a StackNavigation with two screens. In my case I do not display the back button title.

**Comment by pzatorski** [comment]
Hi @tfsjohan ;) Thank you for reporting this. PR is already sent for this issue, could you please close this.. in favour of https://github.com/react-navigation/react-navigation/issues/5028
Thank you.
