### ISSUE TITLE
Nested drawer in stackNavigator closes modal on hide

### ISSUE THREAD

**Issue by rborn** [react-navigation/react-navigation#5079]
I'm trying to open a modal defined in  a stackNavigator that contains a drawerNavigator from within this drawerNavigator.
On closing the drawer, the modal closes as well. 

(pseudocode)

StackNavigator({mode:modal})
--MainScreen (the drawer)
--ModalScreen

DrawerNavigator
  == CustomDrawer onPress={navigate('ModalScreen), closeDrawer()}
  -- Screen

So the app goes to the ModalScreen just fine, the problem is that if I close the drawer the ModalScreen closes as well

If I delete closeDrawer() the ModalScreen stays but when I close it the drawer is there behind still opened.

The only "workaround" I found was to ignore the warning saying I cannot render multiple navigators, pass the StackNavigator.navigation as screenProps.rootNavigation and do

onPress={this.props.screenProps.rootNavigation.navigate('ModalScreen), closeDrawer()}

which is not so good.

Example here https://snack.expo.io/rJ9jkvm5X

Is there any good solution for this? Thank you 🤗

I also asked on [Stackoverflow](https://stackoverflow.com/questions/52643608/nested-drawer-in-stacknavigator-closes-modal-on-hide) but it seems nobody knows.

**Comment by eriveltonelias** [comment]
Hi @rborn! 

Sorry that you're seeing this error, you can use `onItemPress` on your custom `DrawerItem`, but we already tracking it on:

https://github.com/react-navigation/react-navigation/issues/4821
and
https://github.com/react-navigation/react-navigation-drawer/issues/20
