### ISSUE TITLE
Navigating with physical keyboard or TV remote gets focus out of the screen (stacknavigator)

### ISSUE THREAD

**Issue by marabej** [react-navigation/react-navigation#5081]
Hi

I have a problem with moving focus by physical keyboard or TV remote.
The situation is simple:
1) let's have one screen with multiple buttons
2) one button opens second screen with with 2 buttons inside.
Buttons are touchablehighlight in both screens.  I'm changing the focus between the buttons
in the second screen (for instance 'modal' screen) with the keyboard arrows
but the focus is moving out from the modal screen to the parent screen's buttons and back again
How can I make a modal screen which "holds" the keyboard inside, and can change the focus only
between the components inside the modal?

I'm using react-native+StackNavigator and android

best regards

**Comment by brentvatne** [comment]
hello! we have not tested with a tv remote. please create a new issue and follow the issue template and explain to us how we can reproduce it **along with an example that we can run for it**, and we can look at it.
