### ISSUE TITLE
react-navigation no longer works on web out of the box due to dependency on react-native-screens

### ISSUE THREAD

**Issue by rmevans9** [react-navigation/react-navigation#5085]
### Current Behavior

When running a app via `react-native-web` instead of rendering the app you get a blank screen with the following error:

```
screens.js:26 Uncaught TypeError: (0 , o.requireNativeComponent) is not a function
    at Object.<anonymous> (screens.js:26)
```

The code at this location is this:

```
const NativeScreen = Animated.createAnimatedComponent(
  requireNativeComponent('RNSScreen', null)
);
``` 

I realize this problem is in `react-native-screens` but given that library has a hard dependency on native components I am not sure they will be open to solving for web so I am hoping we might be able to find a solution in `react-navigation`

### Expected Behavior

The app should render without error

### How to reproduce

Setup an app using `react-native-web` that uses `react-navigation` and try and load the app. I will work on getting a small repo up within the next few hours to show

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.17.0
| react-native     | 0.56.0
| react-native-web | 0.8.9
| node             | 8.11.3
| npm or yarn      | 1.10.1

**Comment by eriveltonelias** [comment]
Hi @rmevans9! 

Thanks for your report, we're tracking this issue on https://github.com/react-navigation/react-navigation/issues/5004

But if you think that's a different issue, we can reopen this.
