### ISSUE TITLE
Navigating with physical keyboard or TV remote gets focus out of the screen

### ISSUE THREAD

**Issue by marabej** [react-navigation/react-navigation#5086]
He
I have a problem with moving focus by physical keyboard or TV remote. I'm testing with an Android Emulator TV Box image
### Current Behavior
I'm moving the focus with the keyboard arrows (or Android Studio Android Emulator Direction Pad) between TouchableHighlight components.
When I navigate to a second screen, it's components doesn't get the focus or the focus gets out of the them when move it.
I should press in my example the right arrow key 2-3 times to get the focus on some component inside the second screen. Also the focus is getting out of the second screen when I move it with arrows. 
you can press "enter" key of the keyboard and see in the log which component got the focus. Just press
keyboard arrows and enter and watch the log in console
Here is the Code:
```
/* App.js */
import React, {Component} from 'react';
import {Platform, Text, View, TouchableHighlight} from 'react-native';
import {createStackNavigator} from 'react-navigation';

class HomeScreen extends Component<Props> {
  static navigationOptions = {  title: 'Home Screen',  header: null  };
  render() {
    return (
      <View style={{flexDirection: 'row'}}>
        <View>
          <TouchableHighlight onPress={() => console.log('button 1')}>
            <Text>Button 1</Text>
          </TouchableHighlight>
          <TouchableHighlight onPress={() => console.log('button 2')}>
            <Text>Button 2</Text>
          </TouchableHighlight>
          <TouchableHighlight
            onPress={() => this.props.navigation.navigate('Second')}>
            <Text>Open SecondScreen</Text>
          </TouchableHighlight>
        </View>
        <View>
          <Text>Some Text</Text>
        </View>
      </View>
    );
  }
} /* end class */

class SecondScreen extends Component<Props> {
  static navigationOptions = { title: 'Home Screen',  header: null };
  render() {
    return (
      <View style={{flex: 1, alignItems: 'center'}}>
        <TouchableHighlight
          onPress={() => console.log('button 3')}>
          <Text>Button 3</Text>
        </TouchableHighlight>
        <TouchableHighlight
          onPress={() => console.log('button 4')}>
          <Text>Button 4</Text>
        </TouchableHighlight>
        <TouchableHighlight
          onPress={() => this.props.navigation.goBack() }>
          <Text>Close Screen</Text>
        </TouchableHighlight>
      </View>
    );
  }
} /* end class */

const MainStack = createStackNavigator({
  Home: {screen: HomeScreen},
  Second: {screen: SecondScreen},
});

export default class App extends Component<Props> {
  render() {
    return <MainStack />;
  }
}
```
### Expected Behavior
When user opens a new screen with 'navigate' the opened screen should get focus and "locks"
inside it's components focus. 
Keyboard/ direction pad/ TV remote should move the focus between the components inside
the new screen. (Like a trully modal window).
At the moment focus is moving out from the second screen to the parents screen's buttons and back again. The second screen behaves like a "part of the parent screen"

I can't make a snack example because the emulator of the snack doesn't support keyboard or 
direction pad interaction, but in Android Studio's emulator the problem is clearly reproductable

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |2.12.1
| react-native     |0.56.0
| node             |
| npm or yarn      |npm 5.6.0

Best Regards

**Comment by marabej** [comment]
Hello
Thank you, It works
Do you know hot to set focus programatically on a given TouchableHighlight component.
For example, if we have a group of TouchableHighlight components and every of them
opens a modal dialog, how to force a clicked button to stay focused after the modal closes?
react-native-screens works and the modal gets the focus inside, but when the modal is closed, focus didn't remain on the TouchableHighlight which opened the modal. 
I'm using TV Remote.
Another example is when we have a modal with 3 TouchableHighlights inside, how can we set the focus initially on the second button of them when the modal opens? If we have
a textinput then there is no problem , because It has autoFocus prop, but TouchableHighlight doesn't have autoFocus

**Comment by sJJdGG** [comment]
There are onFocus and onBlur callback props which you should already know about
there is hasTVPreferredFocus boolean prop which is usable on any tochable componenet except touchableWithoutFeedback. it gives and removes focus to the touchable componenet on change. The doc says it's only usable on apple tv which is outdated. It's usable on Android TV too.
But there's a catch. From what i know it does NOT call onFocus and onBlur respectively on change which means you need to call it yourself by using TVEventHandler.
```javascript
import React from 'react';
import {TVEventHandler, TouchableHighlight, findNodeHandle} from 'react-native'

export class CustomTouchable extends React.Component {
  myRef = React.createRef();
  nodeHandle = null;
  evtHandler = null;

  enableTVEventHandler() {
    this.evtHandler = new TVEventHandler();
    this.evtHandler.enable(this, this.handleTVRemoteEvent);
  }

  disableTVEventHandler() {
    if (this.evtHandler) {
      this.evtHandler.disable();
      delete this.evtHandler;
    }
  }

  handleTVRemoteEvent = (cmp, event) => {
    const { eventType, tag } = event;
    if (tag !== this.nodeHandle) {
      return;
    }

    if (eventType === "focus") {
      this.myRef.current.props.onFocus();
    }

    if (eventType === "blur") {
      this.myRef.current.props.onBlur();
    }
  }

  componentDidMount() {
    this.nodeHandle = findNodeHandle(this.myRef.current)
    this.enableTVEventHandler();
  }

  componentWillUnmount() {
    this.disableTVEventHandler();
  }

  render() {
    const {children, ...props} = this.props;
    return (
      <TouchableHighlight {...props} ref={this.myRef}>
        {children}
      </TouchableHighlight>
    )
  }
}
```
We're simply listening for focus and blur events and if it's our designated component we call onFocus and onBlur ourselves. there can be duplicate calls when we focus the thouchable by remote and if its important it can be taken care of by calling them conditionally on hasTVPreferredFocus changes.
Also there is another problem i encountered. disabled touchables are still focusable which means when you'r navigating using the remote it also focuses on disabled touchables too. This needs monkey patching react-native itself both on javascript and native side which can be cumbersome and confusing. If you want you can take a look at my [forked react-native](https://github.com/facebook/react-native/compare/master...sJJdGG:projectMovie) which takes care of it by using isTVSelectable prop on Touchables.

There are other problems like restoring focus to the first Touchable in view hierarchy on pushing a new screen and poping it when you use react-native-screens which i'm not quite certain it's a react-native bug or react-native-screens bug or both. Maybe something @kmagiera can take a look at.

**Comment by marabej** [comment]
He
thank you for "hasTVPreferredFocus". I saw that in the doc. but I din't thing that will
work for Android TV. It works like a charm in the emulator. (I didn't try it in a real device yet, but it will work I suppose).
Interestingly that onFocus works.
"But there's a catch. From what i know it does NOT call onFocus and onBlur respectively on change which means you need to call it yourself by using TVEventHandler."
I tried that in the emulator and onFocus event fired automatically for TouchableHighlight with hasTVPreferredFocus={true}.
I saw your forked react-native. At first glance I saw that you added more Remote KEYS definitions (ex. put(KeyEvent.KEYCODE_MEDIA_PREVIOUS, "previous")).
I'm not using TVEventHandler at all, but this one: react-native-key-event: ^1.0.0
Now, I'm trying react-native-screens without "react-navigation", but with no success.
I'm trying to use <ScreenContainer> <Screen actyve={1}> constructions
Do you know a way with react-native-screens to lock focus inside a group of controls? Is it possible without changing theoriginal react-native code? For example let's have 3 <TouchableHighlight>, can we
lock the focus inside the first two? For example with 
```
<TouchableHighlight>                                                                                         
  <Text>Button 1</Text>                                                                                 
</TouchableHighlight>                                                                                         
<TouchableHighlight>
  <Text>Button 2</Text>                                                                                       
</TouchableHighlight>                                                                                            
<TouchableHighlight>                            
  <Text>Button 3</Text>                                                                                    
</TouchableHighlight> 
```
How can I lock the focus for Button 1 and Button 2, I mean moving with a TVRemote 
between Button 1 and Button 2 only. I thought wrapping them with `<screen>` from react-native-screens will be a solution, but I was wrong obviously.

**Comment by sJJdGG** [comment]
> I tried that in the emulator and onFocus event fired automatically for TouchableHighlight with hasTVPreferredFocus={true}. I'm using react-native 0.57.1

Good to know there are always new enhancements. I haven't checked it for a long time.

> Do you know a way with react-native-screens to lock focus inside a group of controls? Is it possible without changing theoriginal react-native code? For example let's have 3 , can we lock the focus inside the first two?

Sorry I can't think of a workaround right now that wouldn't need to change react-native code itself. Ideally react-native should automatically set disabled Touchables unfocusable. even a PR that gets accepted wouldn't find its way to mainstream until RN 0.58 release.

**Comment by armagedan** [comment]
> It can be fixed using [react-native-screens](https://github.com/kmagiera/react-native-screens).
> Add it to your project and call useScreens(). It should take care of the task.

This does not work with react navigation 5. What could be the problem? I have the same issue as the OP

**Comment by armagedan** [comment]
Is it a bug with react navigation 5? Using `userScreens()` does not work

**Comment by olafurnsig** [comment]
createNativeStack  fixes this issue, keeps the focus within the newest screen in the stack.

**Comment by mehthabux** [comment]
Same for me. Previous screen get focused when using react navigation modal

**Comment by olafurnsig** [comment]
@mehthabux - use createNativeStack() from react-native-screens, and enableScreens() needs to be called at app start.

This fixed it for me

**Comment by mehthabux** [comment]
@olafurnsig I tried it actually, but its not working for me in the case of modal. have you tried with modal from createNativeStack()

**Comment by sachinv2r** [comment]
I am using 

`<NavigationContainer>
 <Stack.Navigator>
   <Stack.Screen name={"Splash"} component={SplashScreen} />
   <Stack.Screen name={"Dashboard"} component={DashboardScreen} />
 </Stack.Navigator>
</NavigationContainer>`

Previous screen touchables still taking focus, please help.. (Navigation v5)

I've used useScreens(), enableScreen()

It doesn't seem to work, I don't want previous screen to take focus

**Comment by stephane-r** [comment]
Same for me. I've try multiple method like `focusable` on View screen (using isFocused hook) but no result.

I'm using latest react-navigation with tab module.
