### ISSUE TITLE
TabNavigator nested in StackNavigator - Header blank issue (or wanted behaviour?)

### ISSUE THREAD

**Issue by adrienthiery** [react-navigation/react-navigation#5087]
### Current Behavior

- What code are you running and what is happening?

Nesting a TabNavigator as the 1st screen of a StackNavigator.

- Include a screenshot if it makes sense.

![screenshot](https://user-images.githubusercontent.com/2392118/46762540-51de6680-cca5-11e8-8bea-beb1c33b1d7c.png)

### Expected Behavior

- What do you expect should be happening?

 I expected the `navigationOptions` of my tabs' screens to impact the Header, but I end up with a blank header.

### How to reproduce

Tried to do a Snack but it fails with a cryptic error : https://snack.expo.io/BkyxiAi97 😢 
Reproduction repo: git@github.com:adrienthiery/react-navigation-tabs-header-example.git

```
yarn
react-native run-ios
npm start --reset-cache ('cause of https://github.com/facebook/react-native/issues/21490)
```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.17.0
| react-native     | 0.57.2
| node             |  8.12.0
| npm or yarn      | 1.10.1

**Comment by brentvatne** [comment]
https://reactnavigation.org/docs/en/navigation-options-resolution.html#a-stack-contains-a-tab-navigator-and-you-want-to-set-the-title-on-the-stack-header

**Comment by adrienthiery** [comment]
Damn, I was so sure I had seen all the pages of the documentation! 😥 sorry about that. Thanks @brentvatne
