### ISSUE TITLE
How dynamically append Navigator?

### ISSUE THREAD

**Issue by esipavicius** [react-navigation/react-navigation#5112]
Hello,

I do not know best way to append current navigation. I need add some tabs when user logged in. For example:

```
        const HomeNavigator = createStackNavigator({
            Home: HomeScreen,
            RegisterCar: RegisterCar,
            CameraScreen: CameraScreen,
            CarVinWebView: CarVinWebView,
            GalleryScreen: GalleryScreen,
            CarStatusVerifier: CarStatusVerifier,
        }, {
            mode: Platform.OS === 'ios' ? 'modal' : 'card',
        });

        const NAVIGATION = createSwitchNavigator({
            HomeNavigation: HomeNavigationDrawer,
        }, {
            initialRouteName: 'Loading',
        });
```

And I want to HomeNavigator add TabNavigator when logged in. So what is best way with v2?

**Comment by eriveltonelias** [comment]
hi there! this issue tracker is reserved for bugs only. your post seems to be a usage question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help. thanks!
