### ISSUE TITLE
Reset stack from another stack

### ISSUE THREAD

**Issue by clementino36** [react-navigation/react-navigation#5114]
This issue is very similar to https://github.com/react-navigation/react-navigation/issues/2291 but for react navigation v2. 
I'm trying to reset the stack and navigate to a route of another stack this way:
``` javascript
export const resetStack: Function = StackActions.reset({
    actions: [NavigationActions.navigate({ routeName: 'Home' })],
    index: 0,
});
```

This gives me 
> Invariant Violation: There is no route defined for key Home. Must be one of *routes in the other stack*

If I simply `navigate('Home')` from the other stack, it works, only the `reset` does not work.
I've tried setting `key: null` as suggested in the issue above but it didn't do the trick.

Reproductible demo: https://snack.expo.io/@emixis/resetstack

**Comment by eriveltonelias** [comment]
Hi @clementino36! 

https://snack.expo.io/@eriveltonelias/resetstack

**Comment by clementino36** [comment]
Hi @eriveltonelias this works only because `Home` is set as the `initialRouteName` of `MainStackNavigator`, but what if you want to resetStack and navigate to another route ? https://snack.expo.io/@emixis/resetstack

**Comment by eriveltonelias** [comment]
Hi @clementino36! 
try to use it:

https://snack.expo.io/@eriveltonelias/resetstack

**Comment by clementino36** [comment]
Should've thought about it, thank you for your help!

**Comment by eriveltonelias** [comment]
You're welcome!

**Comment by fantasy525** [comment]
```
const resetActions=StackActions.reset({
			index:0,
			actions:[NavigationActions.navigate({routeName:"Register"})]
		})
		this.props.navigation.dispatch(resetActions)
```
so why  there is no transition animations?
