### ISSUE TITLE
Add Custom Big Button in the  Middle of TabBar

### ISSUE THREAD

**Issue by tusharmutreja** [react-navigation/react-navigation#5126]
## The issue tracker is reserved for bug reports only.

If you have a question, feature request, or an idea for improving the library or its related tools, please try one of the following resources:

- [Read the documentation](https://reactnavigation.org/)
- [Post an issue to the website repository if you'd like to see a documentation change](http://github.com/react-navigation/website)
- [Post a feature request to Canny](https://react-navigation.canny.io/feature-requests)
- [Write a RFC if you have ideas for how to implement a feature request](https://github.com/react-navigation/rfcs)
- [Get help on Discord chat (#react-navigation on Reactiflux)](https://discord.gg/4xEK3nD) or [on StackOverflow](https://stackoverflow.com/questions/tagged/react-navigation)
- Search for your issue - it may have already been answered or even fixed in the development branch. However, if you find that an old, closed issue still persists in the latest version, you should open a new issue.

Bugs with react-navigation must be reproducible *without any external libraries that operate on it*. This means that if you are attempting to use Redux or MobX with it and you think you have found a bug, you must be able to reproduce it without Redux or MobX in this report. Redux related issues belong in [react-navigation-redux-helpers](https://github.com/react-navigation/react-navigation-redux-helpers), and we do not have any first-class integration with MobX at the moment.

---

### Current Behavior

- What code are you running and what is happening?
- Include a screenshot if it makes sense.

### Expected Behavior

- What do you expect should be happening?
- Include a screenshot if it makes sense.

### How to reproduce

- You must provide a way to reproduce the problem. If you are having an issue with your machine or build tools, the issue belongs on another repository as that is outside of the scope of React Navigation.
- Either re-create the bug on [Snack](https://snack.expo.io) or link to a GitHub repository with code that reproduces the bug.
- Explain how to run the example app and any steps that we need to take to reproduce the issue from the example app.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |
| react-native     |
| node             |
| npm or yarn      |

**Comment by tusharmutreja** [comment]
I need to make the Custom Tab bar , and i need to show little big button in the middle of tabbar [
![screen shot 2018-08-28 at 12 37 26 pm](https://user-images.githubusercontent.com/42165403/46939118-1b2c9580-d083-11e8-8614-b8eacf1fe959.png)
](url)

**Comment by tusharmutreja** [comment]
![screen shot 2018-10-15 at 1 59 51 pm](https://user-images.githubusercontent.com/42165403/46939176-431bf900-d083-11e8-9bf3-eb61b5f8361b.png)

I need to make tabBar with little big Button in the middle of tabBar
How can i do this? 
Any Help?

**Comment by nangezi123** [comment]
use tabBarComponent
example:
const TabNavigatorConfigs = {
    tabBarComponent: prop => <CustomTabBarBottom {...prop} />
}

**Comment by tusharmutreja** [comment]
Thanks , I already use "tabBarComponent". But My problem is to show big Button in the middle

**Comment by nangezi123** [comment]
"tabBarComponent"  can rewrite this tab, so it can help you add Big Button in the middle

CustomTabBarBottom.js:
import React, {Component} from "react";
import {
  TabBarBottom
} from "react-navigation";
import { 
  View, 
  Dimensions, 
  TouchableOpacity, 
  DeviceEventEmitter,
} from "react-native";
import Ionicons from 'react-native-vector-icons/Ionicons';
import Feather from 'react-native-vector-icons/Feather';

const {width, height} = Dimensions.get('window');

class CustomTabBarBottomChild extends Component {
  constructor(props){
    super(props);
    this.state={
      visible: false,
    }
  }
  startEmit() {
    DeviceEventEmitter.emit('showPlusModel', '123')
  }
  render() {
    return (
      <View style={styles.plusContainer}>
        <TouchableOpacity 
          style={styles.plusTouchButton}
          // onPress={() => this.showDialog()}
          onPress={() => this.startEmit()}
        >
          <Ionicons name='md-add' size={35} color='#fff'/>
        </TouchableOpacity>
        {/* <PlusModal 
          _dialogVisible={this.state.visible}
          _dialogOnPress={()=> {this.hideDialog()}} /> */}
      </View>
    );
  }
};
const CustomTabBarBottom = props => {
  return(
    <View>
      <CustomTabBarBottomChild />
      <View style={{backgroundColor: "#fff",}}>
          <TabBarBottom {...props} />
        </View>
    </View>
  )
}

const styles = {
  plusContainer: {
    position: 'absolute', 
    top: 1,bottom: 0,left: '50%',
    zIndex: 999, 
    marginLeft: -0.1*width , 
    width: 0.2*width, 
    height: (height*0.08 < 65) ? 65 : height*0.08, //65
    backgroundColor: '#fff',
    justifyContent: 'center', 
    alignItems: 'center'
  },
  plusTouchButton: {
    height: (height*0.08 < 65) ? 45 : height*0.08*9/13, //45
    width: (height*0.08 < 65) ? 45 : height*0.08*9/13, //45
    borderRadius: 50, 
    backgroundColor: '#fb7299', 
    justifyContent: 'center', 
    alignItems: 'center',
  },
}

export default CustomTabBarBottom;

**Comment by eriveltonelias** [comment]
hi there! this issue tracker is reserved for bugs only. your post seems to be a usage question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help and also maybe it can help you https://github.com/react-navigation/react-navigation/issues/2601, Thanks!

**Comment by drewandre** [comment]
Here's a snippet that may help:

```import React from 'react'
import {
  SafeAreaView,
  TouchableOpacity
} from 'react-native'

import { createBottomTabNavigator } from 'react-navigation-tabs'

import { defaultFooterStyle } from '../assets/styles/nav'

import FeedStack from '../screens/feed/navigation/FeedStack'
import InboxStack from '../screens/inbox/navigation/InboxStack'

import UploadIcon from '../screens/upload/components/UploadIcon'
import InboxIcon from '../screens/inbox/components/InboxIcon'

import { Feed, FeedActive } from '../shared/components/icons'
import Colors from '../assets/styles/Colors'

const FooterTabNavigator = (props) => {
  let currentRouteName = props.navigation.state.routes[props.navigation.state.index].key
  return (
    <SafeAreaView style={defaultFooterStyle}>
      <TouchableOpacity
        activeOpacity={0.6}
        hitSlop={{
          top: 20,
          bottom: 50,
          left: 50,
          right: 50
        }}
        onPress={() => props.navigation.navigate('Feed')}>
        {currentRouteName === 'Feed'
          ? <FeedActive fill={Colors.white} />
          : <Feed fill={Colors.white} />}
      </TouchableOpacity>
      <UploadIcon navigation={props.navigation} />
      <TouchableOpacity
        activeOpacity={0.6}
        hitSlop={{
          top: 20,
          bottom: 50,
          left: 50,
          right: 50
        }}
        onPress={() => props.navigation.navigate('Message')}>
        <InboxIcon focused={currentRouteName === 'Message'} />
      </TouchableOpacity>
    </SafeAreaView>
  )
}

const FooterNavigator = createBottomTabNavigator(
  {
    Feed: { screen: FeedStack },
    Message: { screen: InboxStack }
  },
  {
    tabBarComponent: props => <FooterTabNavigator {...props} />
  }
)

export default FooterNavigator
```

This let us create a footer like so: https://image.ibb.co/n8tQSf/Screen-Shot-2018-10-30-at-1-29-55-PM.png

`<UploadIcon />` is a regular react component that is connected to redux. Hope this helps.

**Comment by mymai91** [comment]
I wrote a blog post share about "Add Custom Button in the Middle of TabBar" react-navigation version 5.x

https://medium.com/@my.maithi/react-native-navigation-add-custom-button-in-the-middle-of-tabbar-6c390201a2bb

**Comment by rameshvishnoi90904** [comment]
const customTabBarStyle = {
		activeTintColor: '#0091EA',
		inactiveTintColor: 'gray',
		style: {backgroundColor: 'white' },
	}
	return (
		<Tab.Navigator
		initialRouteName="Home"
		activeColor="#fff"
		tabBarOptions={customTabBarStyle}
		shifting="false">
		<Tab.Screen
		name="Home"
		options={{
			tabBarLabel: '',
			tabBarIcon: ({ color }) => (
				<Icon name="home" color={color} size={26} />
			)
		}}
		component={HomeScreen} />
		<Tab.Screen
		name="Workout"
		options={{
			tabBarLabel: '',
			tabBarIcon: ({ color }) => (
				<Icon name="fitness-center" color={color} size={26} />
			)
		}}
		component={WorkoutTabScreen} />
		<Tab.Screen
		name="Add"
		options={{
			tabBarLabel: '',
			tabBarIcon: ({ color }) => (
				<View
				style={{
					position: 'absolute',
					bottom: 0, // space from bottombar
					height: 68,
					width: 68,
					borderRadius: 68,
					justifyContent: 'center',
					alignItems: 'center',
				}}
				>
				<Icon name="add-circle-outline" color="grey" size={68}/>
				</View>
			)
		}}
		component={PayScreenComponent}/>
		<Tab.Screen
		name="Store"
		options={{
			tabBarLabel: '',
			tabBarIcon: ({ color }) => (
				<Icon name="store" color={color} size={26} />
			)
		}}
		component={StoreLandingScreen} />
		<Tab.Screen
		name="Profile"
		options={{
			tabBarLabel: '',
			tabBarIcon: ({ color }) => (
				<Icon name="perm-identity" color={color} size={26} />
			)
		}}
		component={ProfileScreen} />
		</Tab.Navigator>
	);


Output: 
![image](https://user-images.githubusercontent.com/13585002/86389448-f2638e00-bcb3-11ea-9c50-8c0f5c8fb98e.png)

**Comment by FatemeMirzaeii** [comment]
> 
> 
> ```
> const customTabBarStyle = {
> 	activeTintColor: '#0091EA',
> 	inactiveTintColor: 'gray',
> 	style: {backgroundColor: 'white' },
> }
> return (
> 	<Tab.Navigator
> 	initialRouteName="Home"
> 	activeColor="#fff"
> 	tabBarOptions={customTabBarStyle}
> 	shifting="false">
> 	<Tab.Screen
> 	name="Home"
> 	options={{
> 		tabBarLabel: '',
> 		tabBarIcon: ({ color }) => (
> 			<Icon name="home" color={color} size={26} />
> 		)
> 	}}
> 	component={HomeScreen} />
> 	<Tab.Screen
> 	name="Workout"
> 	options={{
> 		tabBarLabel: '',
> 		tabBarIcon: ({ color }) => (
> 			<Icon name="fitness-center" color={color} size={26} />
> 		)
> 	}}
> 	component={WorkoutTabScreen} />
> 	<Tab.Screen
> 	name="Add"
> 	options={{
> 		tabBarLabel: '',
> 		tabBarIcon: ({ color }) => (
> 			<View
> 			style={{
> 				position: 'absolute',
> 				bottom: 0, // space from bottombar
> 				height: 68,
> 				width: 68,
> 				borderRadius: 68,
> 				justifyContent: 'center',
> 				alignItems: 'center',
> 			}}
> 			>
> 			<Icon name="add-circle-outline" color="grey" size={68}/>
> 			</View>
> 		)
> 	}}
> 	component={PayScreenComponent}/>
> 	<Tab.Screen
> 	name="Store"
> 	options={{
> 		tabBarLabel: '',
> 		tabBarIcon: ({ color }) => (
> 			<Icon name="store" color={color} size={26} />
> 		)
> 	}}
> 	component={StoreLandingScreen} />
> 	<Tab.Screen
> 	name="Profile"
> 	options={{
> 		tabBarLabel: '',
> 		tabBarIcon: ({ color }) => (
> 			<Icon name="perm-identity" color={color} size={26} />
> 		)
> 	}}
> 	component={ProfileScreen} />
> 	</Tab.Navigator>
> );
> ```
> 
> Output:
> ![image](https://user-images.githubusercontent.com/13585002/86389448-f2638e00-bcb3-11ea-9c50-8c0f5c8fb98e.png)

this will behave in this way:
![Screenshot_1610618465](https://user-images.githubusercontent.com/33895649/104576089-02015d80-566d-11eb-99c0-bdb153517c84.png)
what is wrong with this?

**Comment by russelRajitha** [comment]
I have same issue

**Comment by jeffngugi** [comment]
> > ```
> > const customTabBarStyle = {
> > 	activeTintColor: '#0091EA',
> > 	inactiveTintColor: 'gray',
> > 	style: {backgroundColor: 'white' },
> > }
> > return (
> > 	<Tab.Navigator
> > 	initialRouteName="Home"
> > 	activeColor="#fff"
> > 	tabBarOptions={customTabBarStyle}
> > 	shifting="false">
> > 	<Tab.Screen
> > 	name="Home"
> > 	options={{
> > 		tabBarLabel: '',
> > 		tabBarIcon: ({ color }) => (
> > 			<Icon name="home" color={color} size={26} />
> > 		)
> > 	}}
> > 	component={HomeScreen} />
> > 	<Tab.Screen
> > 	name="Workout"
> > 	options={{
> > 		tabBarLabel: '',
> > 		tabBarIcon: ({ color }) => (
> > 			<Icon name="fitness-center" color={color} size={26} />
> > 		)
> > 	}}
> > 	component={WorkoutTabScreen} />
> > 	<Tab.Screen
> > 	name="Add"
> > 	options={{
> > 		tabBarLabel: '',
> > 		tabBarIcon: ({ color }) => (
> > 			<View
> > 			style={{
> > 				position: 'absolute',
> > 				bottom: 0, // space from bottombar
> > 				height: 68,
> > 				width: 68,
> > 				borderRadius: 68,
> > 				justifyContent: 'center',
> > 				alignItems: 'center',
> > 			}}
> > 			>
> > 			<Icon name="add-circle-outline" color="grey" size={68}/>
> > 			</View>
> > 		)
> > 	}}
> > 	component={PayScreenComponent}/>
> > 	<Tab.Screen
> > 	name="Store"
> > 	options={{
> > 		tabBarLabel: '',
> > 		tabBarIcon: ({ color }) => (
> > 			<Icon name="store" color={color} size={26} />
> > 		)
> > 	}}
> > 	component={StoreLandingScreen} />
> > 	<Tab.Screen
> > 	name="Profile"
> > 	options={{
> > 		tabBarLabel: '',
> > 		tabBarIcon: ({ color }) => (
> > 			<Icon name="perm-identity" color={color} size={26} />
> > 		)
> > 	}}
> > 	component={ProfileScreen} />
> > 	</Tab.Navigator>
> > );
> > ```
> > 
> > 
> > Output:
> > ![image](https://user-images.githubusercontent.com/13585002/86389448-f2638e00-bcb3-11ea-9c50-8c0f5c8fb98e.png)
> 
> this will behave in this way:
> ![Screenshot_1610618465](https://user-images.githubusercontent.com/33895649/104576089-02015d80-566d-11eb-99c0-bdb153517c84.png)
> what is wrong with this?

Hello @FatemeMirzaeii , did you figure our how to solve this. The problem seem to occur when you put BottomTabBar inside Drawer navigator

**Comment by LefterisL** [comment]
> ```
> const customTabBarStyle = {
> 	activeTintColor: '#0091EA',
> 	inactiveTintColor: 'gray',
> 	style: {backgroundColor: 'white' },
> }
> return (
> 	<Tab.Navigator
> 	initialRouteName="Home"
> 	activeColor="#fff"
> 	tabBarOptions={customTabBarStyle}
> 	shifting="false">
> 	<Tab.Screen
> 	name="Home"
> 	options={{
> 		tabBarLabel: '',
> 		tabBarIcon: ({ color }) => (
> 			<Icon name="home" color={color} size={26} />
> 		)
> 	}}
> 	component={HomeScreen} />
> 	<Tab.Screen
> 	name="Workout"
> 	options={{
> 		tabBarLabel: '',
> 		tabBarIcon: ({ color }) => (
> 			<Icon name="fitness-center" color={color} size={26} />
> 		)
> 	}}
> 	component={WorkoutTabScreen} />
> 	<Tab.Screen
> 	name="Add"
> 	options={{
> 		tabBarLabel: '',
> 		tabBarIcon: ({ color }) => (
> 			<View
> 			style={{
> 				position: 'absolute',
> 				bottom: 0, // space from bottombar
> 				height: 68,
> 				width: 68,
> 				borderRadius: 68,
> 				justifyContent: 'center',
> 				alignItems: 'center',
> 			}}
> 			>
> 			<Icon name="add-circle-outline" color="grey" size={68}/>
> 			</View>
> 		)
> 	}}
> 	component={PayScreenComponent}/>
> 	<Tab.Screen
> 	name="Store"
> 	options={{
> 		tabBarLabel: '',
> 		tabBarIcon: ({ color }) => (
> 			<Icon name="store" color={color} size={26} />
> 		)
> 	}}
> 	component={StoreLandingScreen} />
> 	<Tab.Screen
> 	name="Profile"
> 	options={{
> 		tabBarLabel: '',
> 		tabBarIcon: ({ color }) => (
> 			<Icon name="perm-identity" color={color} size={26} />
> 		)
> 	}}
> 	component={ProfileScreen} />
> 	</Tab.Navigator>
> );
> ```
> 
> Output:
> ![image](https://user-images.githubusercontent.com/13585002/86389448-f2638e00-bcb3-11ea-9c50-8c0f5c8fb98e.png)

The issue with this  solution while it is ok visually, the top part that is outside of the bottom bar is not clickable. I still haven't found a valid solution however

**Comment by russelRajitha** [comment]
I Found A solution for this. bottom tab navigator add a route in the middle with null tab button. You should create your own bottom tab bar by providing new component to the prop `tabBar`. 
then you can align your button into the center. write onclick handler for your plus button and redirect into plus button route. remember that You should handle keyboard also. the problem is they are using safe area component to wrap the bottom tab bar and overflow is set to hidden. even we change it it works for ios, but not for android. 

https://reactnavigation.org/docs/bottom-tab-navigator#tabbar

**Comment by cristianbriscaru** [comment]
A solution that works for both ios and android, the entire button is clickable and also changes the bottom tab bar border around the raised button 

`import { createBottomTabNavigator } from '@react-navigation/bottom-tabs';
import { ImageProps } from 'react-native';
import { Image, View } from 'react-native';
import { useTheme } from '@rneui/themed';
import i18n from 'i18n-js';


import {  RootTabParamList } from '../types';

import HomeScreen from '../screens/home/HomeScreen';
import CardsScreen from '../screens/cards/CardsScreen';
import PaymentsScreen from '../screens/payments/PaymentsScreen';
import AccountScreen from '../screens/account/AccountScreen';
import EmptyScreen from '../screens/general/EmptyScreen';

const BottomTab = createBottomTabNavigator<RootTabParamList>();

export function BottomTabNavigator() {

  const { theme } = useTheme();

  return (
    <BottomTab.Navigator
      initialRouteName="Home"
      screenOptions={{
        tabBarShowLabel: false,
        tabBarActiveTintColor: theme.colors.greenHighlight,
        tabBarInactiveTintColor: theme.colors.secondary,
      }}
    >
      <BottomTab.Screen
        name="Home"
        component={HomeScreen}
        options={{
          title: i18n.t('tabs.home'),
          tabBarIcon: ({ color }) => <TabBarIcon source={require('../assets/images/home.png')} color={color} />,
        }}
      />

      <BottomTab.Screen
        name="Cards"
        component={CardsScreen}
        options={{
          title: i18n.t('tabs.cards'),
          tabBarIcon: ({ color }) => <TabBarIcon source={require('../assets/images/cards.png')} color={color} />,
          
        }}
      />

      <BottomTab.Screen
        name="NewPaymentTab"
        component={NewPayment}
        options={{
          headerShown: false,
          title: i18n.t('payment.newPayment'),
          tabBarIcon: () =>  <HighTabBarIcon source={require('../assets/images/add.png')} />,
        }}
      />

      <BottomTab.Screen
        name="Payments"
        component={PaymentsScreen}
        options={{
          title: i18n.t('tabs.payments'),
          tabBarIcon: ({ color }) => <TabBarIcon source={require('../assets/images/history.png')} color={color} />,
        }}
      />

      <BottomTab.Screen
        name="Account"
        component={AccountScreen}
        options={{
          title: i18n.t('tabs.account'),
          tabBarIcon: ({ color }) => <TabBarIcon source={require('../assets/images/settings.png')} color={color} />,
        }}
      />
      
    </BottomTab.Navigator>
  );
}


function HighTabBarIcon(props:ImageProps) {

  const { theme } = useTheme();

  return (
    <View
      style={{
        justifyContent: 'center',
        alignItems: 'center',
        width: 60,
        height: 60,
        borderTopWidth: 0.2,
        borderLeftWidth: 0.2,
        borderRightWidth: 0.2,
        borderRadius: 100,
        borderColor: theme.colors.grey4,
        marginBottom: 20,
        backgroundColor: theme.colors.white,
      }}
    >
      <View
        style={{
          width: 65,
          height: 45,
          backgroundColor: theme.colors.white,
          justifyContent: 'center',
          alignItems: 'center',
          borderRadius: 10,
          marginTop: 15,
        }}
      >
        <View
          style={{
            justifyContent: 'center',
            alignItems: 'center',
            width: 50, 
            height: 50, 
            backgroundColor: theme.colors.greenHighlight,
            borderRadius: 100,
            marginTop: -10, 
          }}
        >
          <Image
            fadeDuration={0}
            style={{ 
              width: 36, 
              height: 36,
              tintColor: theme.colors.white,
            }}
            {...props}
          />
        </View>
      </View>
    </View>
  )
}

type TabBarIconPropsType = ImageProps & {
  color:string,
}

function TabBarIcon({color, ...rest}: TabBarIconPropsType) {
  return (
    <View
      style={{
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
      }}
    >
      <Image
        fadeDuration={0}
        style={{ 
          width: 32, 
          height: 32,
          tintColor: color,
        }}
        {...rest}
      />
    </View>
  )
}`
