### ISSUE TITLE
Passing params from stack navigator to tabs(each tab is stack navigator)

### ISSUE THREAD

**Issue by alexstoyanov** [react-navigation/react-navigation#5128]
I use react-navigation v2. I am trying to implement a StackNavigator which navigates to MaterialTopTabNavigator. Each route of the MaterialTopTabNavigator is a Stack Navigator. So something like this:

    Absences: {
        screen: AbsencesStack,
    },
    Grades: {
        screen: GradesStack,
    },
    SHIFeedback: {
        screen: FeedbackStack,
    },

When I navigate to the tab navigator and pass a navigation prop.
    _navigator.dispatch(
        NavigationActions.navigate({
            TEACHER_HOME,
            school_hour, //navigation param
        })
    );
I receive the school_hour navigation param in the tab navigator navigation options but I don't receive it in ANY of the nested Stacks(AbsencesStack,GradesStack,FeedbackStack)

### Current Behavior
- Not receiving navigation param

### Expected Behavior
-  Should somehow get the navigation param in the screens that are in AbsencesStack,GradesStack,FeedbackStack
### How to reproduce
- Create main app stack navigator with routes - 1. home screen 2. Tab navigator
- Create Tab navigator with stack in each route
- Navigate with to Tab navigator with navigation param
- Screens in each stack of the tab navigator don't receive navigation props

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.17.0
| react-native     | 0.55.2
| node             | 10.4.1
| npm or yarn      | 6.1.0

**Comment by vonovak** [comment]
Hi and thanks for reporting. I think your `_navigator.dispatch` call is wrong, please see the docs: https://reactnavigation.org/docs/en/navigation-actions.html#navigate

If this is not the problem, please create a runnable repro and I'll reopen. Thanks.
