### ISSUE TITLE
headerLeft provided to navigationOptions renders even at root of stack (Android)

### ISSUE THREAD

**Issue by peacechen** [react-navigation/react-navigation#5130]
### Current Behavior

When providing `headerLeft` to a StackNavigator's navigationOptions, the component always displays, even when at the root of the stack.  The built-in headerLeft back button renders only when there's more than one screen on the stack; when it navigates to the root of the stack, it disappears.

This appears to be specific to Android.  From what I recall, it doesn't render at the root of the stack on iOS.

### Expected Behavior

I'd like to either replace only the icon with a custom one (keeping the default header behavior), or receive a prop in the headerLeft method to determine whether it's at the root of the stack.  I haven't found a way in the headerLeft callback to retrieve the stack of the StackNavigator stack.

### How to reproduce

```
    return createStackNavigator(
      {
        'LOGIN': { screen: Login, navigationOptions: { header: null } },
        'BOOKINGS': { screen: Bookings, navigationOptions: {title: 'Bookings', headerStyle: {elevation: 0}} },
        // ... etc
      },
      {
        initialRouteName: this.props.initialRouteName,
        headerMode: 'screen',
        headerLayoutPreset: 'center',
        navigationOptions: {
          headerStyle: {backgroundColor: 'blue'},
          headerTitleStyle: {color: 'white'},
          headerTintColor: {color: 'white'},
          headerLeft: this.renderHeaderLeft,  // renders a white left-carat icon
          gesturesEnabled: false,
        },
      }
    );
```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.17.0
| react-native     | 0.56.2
| node             | 9.3.0
| npm or yarn      | 5.5.1

**Comment by brentvatne** [comment]
that's the point of it - you can render anything in header left, you may use it for things other than back buttons ;) https://github.com/react-navigation/react-navigation.github.io/issues/267 is an issue to document how you can replace the back button. there is a link in that thread to a solution for that

**Comment by peacechen** [comment]
@brentvatne   Good to see that it's been asked for already.

Note that on iOS, supplying `headerLeft` conditionally draws the button.  It's only on Android that it always renders, even at the root of the stack.  Is there conditional code that's platform-specific for headerLeft?

**Comment by peacechen** [comment]
It might be that the iOS build of our app was using a prior version of react-navigation (around 2.6.2).  Updating to 2.17 has broken that behavior unfortunately.

The reason we upgraded to 2.17 was to fix the centering of the header title.  The choice at this point is to between conditional back button rendering, or title centering on Android 🤕

**Comment by brentvatne** [comment]
that would have been a bug in 2.6.2 for it to not render headerLeft on the first screen. just use the thing I linked to before - https://github.com/react-navigation/react-navigation/issues/779#issuecomment-402579323
