### ISSUE TITLE
Gesture swiping back one screen in nested stack 

### ISSUE THREAD

**Issue by tonmanayo** [react-navigation/react-navigation#5132]
## The issue tracker is reserved for bug reports only.

If you have a question, feature request, or an idea for improving the library or its related tools, please try one of the following resources:

https://snack.expo.io/@tmack/react-navigation-swiping-back-bug

### Current Behavior

- What code are you running and what is happening?

When navigating into a nested stack and then using the gesture swipe back, the whole stack is removed instead of navigating back one screen

### Expected Behavior

When in the Change password screen and you swipe back, you should be navigated back to the account screen instead you are navigated back to the home screen 

### How to reproduce

https://snack.expo.io/@tmack/react-navigation-swiping-back-bug

navigate to the account screen by clicking on account, then press change password, then swipe back and you will see that you are taken home instead of been taken back to the account screen 

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | current
| react-native     | current
| node             | v10
| npm or yarn      | yarn

**Comment by brentvatne** [comment]
can you post a screen recording of what you are seeing? sorry it's a bit hard to understand text sometimes

**Comment by tonmanayo** [comment]
@brentvatne all you need to do is go to my example. Navigate to the middle or the end of the stack.  Swipe from right to left on the screen. You will not be taken one screen back. You will be taken to the home screen.

**Comment by brentvatne** [comment]
@tonmanayo - i tried it and it didn't make sense, there is a drawer that was not mentioned. please post a video, thanks!

**Comment by brentvatne** [comment]
closing because inexplicable :-1: and no followup
