### ISSUE TITLE
withNavigation break hot reload

### ISSUE THREAD

**Issue by njleonzhang** [react-navigation/react-navigation#5135]
## Current Behavior

```
class Orders extends React.Component {
      ........
}

export default withNavigation(Orders)
```
### Expected Behavior
revise the code in `Orders`, hot reload should work, but it doesn't. if remove the withNavigation function, then hmr works

### How to reproduce
I can provide on if needed.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  2.17.0
| react-native     |  0.57.2
| node             |  v8.11.3
| npm or yarn      | yarn

**Comment by eriveltonelias** [comment]
I'll close the issue for now, but you can add the repro to the original post and then ping me and I'll reopen to investigate. Thanks for understanding.
