### ISSUE TITLE
Cannot read property 'State' of undefined

### ISSUE THREAD

**Issue by dblommesteijn** [react-navigation/react-navigation#5137]
I'm running into a probable bug in the 3.0.0-alpha.6 release, your other release 2.17.0 does not have this issue. The exception message: Cannot read property 'State' of undefined thrown by: 
* ExceptionsManager.js:76
<img width="1172" alt="screenshot 2018-10-17 at 12 13 39" src="https://user-images.githubusercontent.com/395001/47079560-1a703c80-d206-11e8-8507-bf3a9a690416.png">

### Current Behavior

- After bundling via`yarn add react-navigation`
- Package.json adds a dependency for: `"react-navigation": "^3.0.0-alpha.6"`
- Running the code (listed below)

### Expected Behavior

- I expect the screen: `Home Screen` and text: `Home Screen` for the initial-route
- Not to receive an exception and stack-trace and large overlay with the Exception.

### How to reproduce

* Add yarn dependency: `yarn add react-navigation` for 3.0.0-aplpha.6

Run the following code:

```javascript
import React, { Component } from "react";
import { View, Text } from "react-native";
import { createStackNavigator } from "react-navigation";

class HomeScreen extends Component {
	render() {
		return (
			<View style={{ flex: 1, alignItems: "center", justifyContent: "center" }}>
				<Text>Home Screen</Text>
			</View>
		);
	}
}

const RootStack = createStackNavigator(
	{
		Home: HomeScreen
	},
	{
		initialRouteName: "Home"
	}
);

type Props = {};
export default class App extends Component<Props> {
	render() {
		return <RootStack />;
	}
}
```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.0.0-alpha.6
| react-native     | 0.57.2
| node             | v10.11.0
| yarn      | 1.10.1

**Comment by istvanmakary** [comment]
Hey I had the same issue just now... It's caused by `react-native-gesture-handler` is not linked to the xCode project. Do it manually, and it's going to be resolved ;)

**Comment by brentvatne** [comment]
sorry it was not intentional to release 3.0.0-alpha with the latest tag. i've changed it to 2.18.0 again

**Comment by Lyks-tech** [comment]
> Hey I had the same issue just now... It's caused by `react-native-gesture-handler` is not linked to the xCode project. Do it manually, and it's going to be resolved ;)

Dude you're a god. Spent hours with this....
Just a "react-native link react-native-gesture-handler" then "react-native run-android" resolved it.
React-navigation 3.0.0 works like charm!

**Comment by BengBu-YueZhang** [comment]
> Hey I had the same issue just now... It's caused by `react-native-gesture-handler` is not linked to the xCode project. Do it manually, and it's going to be resolved ;)

Thank you very much indeed. I almost broke down because of this problem
