### ISSUE TITLE
How to update screenProps on other screen?

### ISSUE THREAD

**Issue by navneetccna** [react-navigation/react-navigation#5138]
how I can update screenProps when I navigate to different screens? What is actual use of screenProps ?
I am using StackNavigator and I want to change screenProps when ever user go to new screen. Can we change screenProps value using redux dispatch ?

**Comment by brentvatne** [comment]
hi there! this is a question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.
