### ISSUE TITLE
Invariant Violation: Navigation containers!

### ISSUE THREAD

**Issue by MamyChow** [react-navigation/react-navigation#5139]
I'm running into a probable bug in the 3.0.0-alpha.6 release, i had no problem with the 2.16.0 but know i have this error:

<img width="327" alt="capture d ecran 2018-10-17 a 15 19 01" src="https://user-images.githubusercontent.com/31539767/47088989-1c46f980-d220-11e8-83ba-212280630e11.png">

---
### Current Behavior

- What code are you running and what is happening?
- Include a screenshot if it makes sense.

### Expected Behavior

No error

### How to reproduce

-Add yarn dependency: yarn add react-navigation for 3.0.0-aplpha.6
-Add yarn dependency: react-native-gesture-handler and link

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.0.0-alpha.6
| react-native     | 0.57.1
| node             | 8.12.0
|  yarn      | 1.3.2

**Comment by kriiissstoff** [comment]
Same problem... :(

**Comment by sgh370** [comment]
same problem :(

**Comment by sgh370** [comment]
but react native 0.57.1 and react navigation 2.18.0 works correctly for me. the latest versions maybe has some bugs

**Comment by arizzitano** [comment]
I ran into this and #5137 with `3.0.0-alpha.6` and attempted to downgrade to `2.18.0` as other folks suggested, but ran into build issues with the newer versions of `react@16.6.0-alpha.8af6728` and `react-native@0.57.3` in my project. In case others are having the same problem, this version combination worked for me after a good deal of trial and error:
```
    "react": "16.5.0",
    "react-native": "0.57.1",
    "react-navigation": "2.18.0"
```

**Comment by brentvatne** [comment]
sorry it was not intentional to release 3.0.0-alpha with the latest tag. i've changed it to 2.18.0 again

**Comment by PasinduDineth** [comment]
have the same problem. Waiting for solution.

**Comment by brentvatne** [comment]
@PasinduDineth - literally read the post directly above yours :P just change your version to 2.18.0

**Comment by CharlyPoppins** [comment]
Hi, this error occurred also with 3.0.0-rc when the root navigator is not wrapped into `createAppContainer`

**Comment by brentvatne** [comment]
that is to be expected. the latest rc has a better error message that points to https://reactnavigation.org/docs/en/app-containers.html
