### ISSUE TITLE
Component sent by the params is missing when updating the screen

### ISSUE THREAD

**Issue by henriqueweiand** [react-navigation/react-navigation#5142]
Component A:

A list of which calls a modal passing through params a component

```js
this.props.navigation.navigate('ModalInput', {
              component: <Input />,
            });
```

Component B (ModalInput):

```js
...
render() {
    const { params } = this.props.navigation.state;
    console.tron.log(params);
    return (
      <SafeAreaView style={styles.root}>
        <StatusBar barStyle="dark-content" />
        <View>
          {params?.component}
        </View>
...
```

The problem:

When updating the screen apparently the component sent previously is lost (I'm using redux-persist)

![1](https://user-images.githubusercontent.com/6539492/47107808-aee79880-d220-11e8-8e07-b1b4720c79e3.gif)

State with redux:

https://i.imgur.com/1VvdNXV.mp4

**Comment by brentvatne** [comment]
you can't serialize non-serializable state like classes and functions. you can only serialize basic data structures like objects, arrays, numbers, strings. you should pass this as a string and then in the place where you use the param you should have some switch that turns it into a component depending on what the string is
