### ISSUE TITLE
TextInput/Text press in bottomtabnavigator doesnt call context options

### ISSUE THREAD

**Issue by SexWexPex** [react-navigation/react-navigation#5143]
### Current Behavior

TextInput component inside bottomtabnavigator longpress doesnt call context options (Select/Copy/Paste)
Text component inside bottomtabnavigator longpress with selectable=true doest call context options (Copy)
while in StackNavigator all is ok!

### Expected Behavior

Context menu should appear

### How to reproduce

App uses tabnav architecture from official api [docs](https://reactnavigation.org/docs/en/navigation-options-resolution.html#a-tab-navigator-contains-a-stack-and-you-want-to-hide-the-tab-bar-on-specific-screens)

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.18.0
| react-native     | 0.57.1

**Comment by bachlongkocanh** [comment]
same error for me.
My issues: https://github.com/react-navigation/react-navigation/issues/5151

**Comment by SexWexPex** [comment]
Heh. Seems like React Native 0.57 is broken :(

Just downgrade and all will works fine

**Comment by bachlongkocanh** [comment]
My version React 0.56 :(. Which version do you use??

**Comment by SexWexPex** [comment]
@bachlongkocanh use 0.55.4

**Comment by bachlongkocanh** [comment]
Not work for me :( :( :(

**Comment by brentvatne** [comment]
you could also try enabling react-native-screens:

```
import { useScreens } from 'react-native-screens';
useScreens()
```

you'll need the latest version of react-navigation to do this. i found it resolved the issue in my case

**Comment by bachlongkocanh** [comment]
@brentvatne Can you send to me you case. I use TabNavigator inside DrawerNavigator. I removed native-base component.
`          <View style={{
                flex: 1,
                alignItems: 'center',
            }}>
                <View style={{
                    backgroundColor: '#FFFFFF',
                    borderRadius: 5,
                    shadowColor: "#000",
                    shadowOffset: {
                        width: 0,
                        height: 5,
                    },
                    shadowOpacity: 0.34,
                    shadowRadius: 6.27,
                    elevation: 10,
                    justifyContent: 'center',
                    flexDirection: 'row',
                    flexWrap: 'wrap',

                }}>
                    <TextInput
                        style={{
                            width: Dimensions.get('window').width / 1.4,
                            fontSize: 20
                        }}
                        placeholder="input text"
                        editable={true}
                    />
                    <TouchableOpacity
                        style={{ justifyContent: 'center' }}
                    >
                        <Icon name="md-qr-scanner" size={40} />
                    </TouchableOpacity>
                </View>
            </View>`

**Comment by SexWexPex** [comment]
> you could also try enabling react-native-screens:
> 
> ```
> import { useScreens } from 'react-native-screens';
> useScreens()
> ```
> you'll need the latest version of react-navigation to do this. i found it resolved the issue in my case


Not working for me, same, cant select text :(

**Comment by bachlongkocanh** [comment]
@SexWexPex me too

**Comment by brentvatne** [comment]
@SexWexPex - post reproducible example

**Comment by brentvatne** [comment]
i'm not sure but maybe due to resourcesavingcontainer

**Comment by SexWexPex** [comment]
@brentvatne would you fix this?

**Comment by brentvatne** [comment]
i'm going to lock this issue because i'm not getting any responses to my actual questions. please create a new issue and follow the issue template properly including providing a reproducible example.
