### ISSUE TITLE
Android back doesn't work as expected when having TextInput control in a screen with an open drawer behind

### ISSUE THREAD

**Issue by joel-bitar** [react-navigation/react-navigation#5147]
Android back doesn't work as expected when having a TextInput in a screen and an open drawer behind the screen.

### Current Behavior

Imagine this setup:

* StackNavigator1
  * DrawerNavigator
    * Screen1
  * StackNavigator2
    * Screen2
    * Screen3

In the drawer you have  custom contentComponent which have a link to Screen2. Screen2 has a TextInput. Screen2 links to Screen3.

If you do a navigation from the Drawer to Screen2 and don't touch the TextInput in Screen2, just click the Screen3 link. Now from Screen3 go back using Android back button, this takes you as expected to Screen2, back again takes you to Screen1. This is all well and expected.

However if you click the link to Screen2 from the Drawer and when you're on Screen2 click the TextInput field so it's highlighted, dismiss the keyboard. Now click the link to Screen3. Press Android back button.
You will now end up on Screen1 with a closed drawer and unable to interact with the Drawer. Pressing back again will take you to Screen2 and once more and you're back to Screen1.

### Expected Behavior

The expected behaviour is the one first described, having focused a TextInput controll shouldn't matter.

### How to reproduce

Snack: https://snack.expo.io/@bennyb/react-navigation-drawer-android-back-bug

Steps triggering the bug (make sure you run in android):
* Click open drawer button or swipe it in.
* In drawer click "Navigate to registerscreen"
* Focus the textinput text "i'm a textinput"
* Dismiss keyboard and press the button "registerscreen2"
* Press android back button
* Tada - you are now on DrawerScreen1 but you should have been on RegisterScreen. Also the drawer can't be opened and pressing back takes you to RegisterScreen1.

You can do the above steps again but don't focus the textinput and things will work as expected.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.17.0
| react-native     | 0.57.0

**Comment by brentvatne** [comment]
this is similar to https://github.com/react-navigation/react-navigation/issues/5183

it is resolved in 3.0.0-rc.0. here's your example updated and working as expected: https://snack.expo.io/@notbrent/react-navigation-drawer-android-back-bug
