### ISSUE TITLE
gestureEnabled: false with the following Router configuration

### ISSUE THREAD

**Issue by clementino36** [react-navigation/react-navigation#5148]
### Current Behavior

Here's the code i'm running: https://snack.expo.io/@emixis/resetstack

### Expected Behavior

I would like the swipe gesture recognition for the navigation "back" action on iOS to be disabled.

**Comment by brentvatne** [comment]
https://snack.expo.io/@notbrent/resetstack

it's under navigationOptions, see https://reactnavigation.org/docs/en/stack-navigator.html#navigationoptions-for-screens-inside-of-the-navigator

**Comment by clementino36** [comment]
Thank you, my bad.
