### ISSUE TITLE
StackActions reset is not working with createDrawerNavigator

### ISSUE THREAD

**Issue by vatex** [react-navigation/react-navigation#5149]
StackActions reset is not working with createDrawerNavigator
Example: https://snack.expo.io/@vatex/hello-world-v2

**Comment by brentvatne** [comment]
it's in the same :) `StackAction` not `DrawerAction`

**Comment by vatex** [comment]
@vonovak I want to reset history and move on another page, so when I press back button, then it won't be redirected on previous page. I don't use StackNavigator, I use DrawerNavigator and how to do that with it?

**Comment by renatosistemasvc** [comment]
I need it too
