### ISSUE TITLE
Timeline for v3 and migration questions

### ISSUE THREAD

**Issue by siderakis** [react-navigation/react-navigation#5150]
I'm finally migrating off of the original deprecated "navigator" library. This project that has 40+ screen so it's going to be a bit of work.

I'd like to use the v3 of react-navigation, so I'm wondering if you have any info that could help me decide between migrating to the v3 alpha directly, or migrating to react navigation v2 and then v3 once its out of alpha. 

Thanks

**Comment by brentvatne** [comment]
hey @siderakis! we plan to release a rc version hopefully before the end of next week, along with updated documentation.

**Comment by siderakis** [comment]
Excellent, this is moving fast! Thanks :-)
