### ISSUE TITLE
Can't select/copy/paste input when use drawerNavigator + TabNavigator [ANDROID]

### ISSUE THREAD

**Issue by bachlongkocanh** [react-navigation/react-navigation#5151]
My app using nativeBase with react-navigation like diagram:
```sh
- Login
- Drawer
-- MaterialTopTab
--- Tab1
--- Tab2
-- Other Page
```
In file Tab1 use nativeBase,
```sh
<Form>
   <Item floatingLabel >
      <Label>Username</Label>
      <Input />
   </Item>
</Form>
```
Then Input can't handle `select/copy/paste`. Please check my issues. <Error only on android>
- Snack expo: https://snack.expo.io/@huutho/errornavigation
- Github: https://github.com/bachlongkocanh/ErrorNavigation

**Comment by bachlongkocanh** [comment]
@brentvatne please help me

**Comment by eriveltonelias** [comment]
Hi @bachlongkocanh!

Just tried to reproduce your example and looks fine, check the Video on:

https://streamable.com/vrl7d

Please, next time follow the issue template.

**Comment by brentvatne** [comment]
hi @bachlongkocanh! this is a bug with ViewPagerAndroid in React Native: https://github.com/react-native-community/react-native-tab-view/issues/485

**Comment by brentvatne** [comment]
ok in your case i'm not really sure what's going on, i tried this without nativebase and it works fine: https://snack.expo.io/@notbrent/insane-milkshake

please test without external libraries in the future

**Comment by bachlongkocanh** [comment]
hi @eriveltonelias Can you check on real android device?.

**Comment by bachlongkocanh** [comment]
hi @eriveltonelias Can you check error on real android device.

**Comment by bachlongkocanh** [comment]
hi @eriveltonelias Can you check error on real android device?

**Comment by bachlongkocanh** [comment]
@eriveltonelias Please open again, my issue not resolve :( :(

**Comment by brentvatne** [comment]
@bachlongkocanh - see the other issue where i asked for a reproducible example. i tried the thing that i shared above on a real android above and it worked fine. move conversation into new issue with more info please

**Comment by eriveltonelias** [comment]
Thanks @brentvatne for you help and explanation.
