### ISSUE TITLE
go back problem

### ISSUE THREAD

**Issue by skokon** [react-navigation/react-navigation#5154]
When I'm scrolling in flat list to the center and then navigating to the next screen then navigate back to the pervious screen, the scroll will go back to the start on the flatlist.

I'm navigating using

`this.props.navigation.navigate('SCREEN_A')

Any ideas?

**Comment by brentvatne** [comment]
hi there! this is a question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.
