### ISSUE TITLE
Nested doc URLs 404

### ISSUE THREAD

**Issue by bwobst** [react-navigation/react-navigation#5155]
E.g. This 404's: https://reactnavigation.org/docs/en/material-bottom-tab-navigator.html#docsNav

**Comment by SteffeyDev** [comment]
It actually looks like the entire website has been reverted, this page is displaying the old api `TabNavigator`, instead of the new `createTabNavigator`, even though it says it is the latest version.

**Comment by brentvatne** [comment]
bothced deploy sorry, rolled back
