### ISSUE TITLE
2.18.0 documentation shows deprecated API

### ISSUE THREAD

**Issue by s-ho-hosseini** [react-navigation/react-navigation#5157]
All 2.18.0 guides and API documents uses deprecated API. It looks like this shows 1.5.13 version's documentation.

**Comment by brentvatne** [comment]
there was a bug when updating to the latest version of docusaurus and switching to the built-in versioning. i rolled that back for now and will fix that on monday.

> However, the lib's releases are often causes a lot of inconvenience. We should think about writing more tests, integrate partially release.

feel free to provide PRs or provide more concrete feedback
