### ISSUE TITLE
Height of header after go to other screen

### ISSUE THREAD

**Issue by alexalannunes** [react-navigation/react-navigation#5159]
### Current Behavior
After I go to another screen, the navigation header is larger. As if it had the statusBar

### Expected Behavior
The Height must be (-(StatusBar.currentHeight))

### HeaderStyle
```javascript
static navigationOptions = {
    title: 'Pesquisa',
    headerStyle: {
      backgroundColor: IMC.colors.primary,
      marginTop: -(StatusBar.currentHeight), // here is my solution
    },
    headerTintColor: '#fff'
 }
```

##### OS: Linux
| software         | version
| ---------------- | -------
| react-navigation | ^2.18.0
| react-native     | 16.3.1 (react-native: 30.0.0)
| node             | 8.11.3
| npm or yarn      | 6.4.1

Prints
![screenshot_20181021-103643](https://user-images.githubusercontent.com/16847836/47267812-0c306200-d51f-11e8-9a11-39e4f28715bf.png)
![screenshot_20181021-103646](https://user-images.githubusercontent.com/16847836/47267813-0c306200-d51f-11e8-834c-034be8fe8147.png)

**Comment by alexalannunes** [comment]
Hi @eriveltonelias ( seu nome parece português )
If you want the demo follow my expo profile:

https://expo.io/@alexalannunes/imc

**Comment by eriveltonelias** [comment]
Hey @alexalannunes! 

Yes, I'm Brazilian hahahahaha

Can you create the example on https://snack.expo.io please ? Because I can see the code and work around that to help you, Thanks!

**Comment by alexalannunes** [comment]
Hey @eriveltonelias 
Follow the example on SnackExpo
https://snack.expo.io/@alexalannunes/routeexamplestatusbarheight

**Comment by hungdev** [comment]
I get the same issue.

**Comment by brentvatne** [comment]
react-navigation doesn't adjust to the status bar height currently. there is no api to do this in react-native itself. when https://github.com/facebook/react-native/pull/20999 lands we will be in a better position to

**Comment by brentvatne** [comment]
you can tell react-navigation about the status bar height like this:

```
import { SafeAreaView } from 'react-navigation';

SafeAreaView.setStatusBarHeight(0); // or whatever the height is
```

**Comment by hungdev** [comment]
@brentvatne thank you.

**Comment by hungdev** [comment]
@brentvatne thank you, but if i setStatusBarHeight(20), i can not center item. it always deviates.
look at the border in the example: https://snack.expo.io/@hungdev/routeexamplestatusbarheight
![image](https://user-images.githubusercontent.com/12009276/47625696-55089c00-db59-11e8-9fba-511faec501fe.png)

**Comment by alexalannunes** [comment]
and now? We have to wait for a solution. :( .

**Comment by hungdev** [comment]
@brentvatne it still related this issue. so i don't want to create new issue. I want to increase header size.  When setStatusBarHeight(20), the header left item will be deviates from center. (look at the green border item). I want it located in the center.

**Comment by brentvatne** [comment]
if you want to increase the size of the header then use `headerStyle: { height: _YOUR_HEIGHT_HERE }`. changing the status bar height only tells the header how much space to leave for the status bar at the top of the header, it doesn't change the height of the header..

**Comment by alexalannunes** [comment]
@brentvatne In the images that I put in the issue, the header appears along with a space reserved for the statusbar, in the code the statusbar is with the prop hidden!
I wanted a different solution than this.

```javascript
 headerStyle: {
      ...,
      marginTop: -(StatusBar.currentHeight), // correct the reserved height
 },
```

**Comment by brentvatne** [comment]
@alexalannunes - you didn't explain what was wrong with my suggestion where i closed the issue. i said set the status bar height to 0, did that not do what you needed? @hungdev then chimed in with a different issue, making this thread confusing. if this issue persists for you @alexalannunes please create a new issue with new screenshots and a runnable example on https://snack.expo.io that demonstrates the problem
