### ISSUE TITLE
DrawerNavigator does not close Keyboard

### ISSUE THREAD

**Issue by bonbonio** [react-navigation/react-navigation#5160]
Hello,

If a keyboard is open when the menu is tapped, the keyboard does not close and overlaps the menu; should it not close the keyboard?

If it's down to us to add the functionality, which event should a keyboard dismiss be added to?

Thanks

**Comment by bachlongkocanh** [comment]
`onPress={() => { this.props.navigation.openDrawer(); Keyboard.dismiss() }}`

**Comment by bonbonio** [comment]
Ok, so I would infer that means everyone else adds the call manually too.

Thanks @bachlongkocanh

**Comment by utlinkedlist** [comment]
> `onPress={() => { this.props.navigation.openDrawer(); Keyboard.dismiss() }}`

In which function property you have used this function call

**Comment by oliverlu-cymbus** [comment]
can repro on old builds but not happening on newer builds. See test result in STRATUS-1710
