### ISSUE TITLE
Navigator inside Drawer's contentComponent

### ISSUE THREAD

**Issue by EstebanBP** [react-navigation/react-navigation#5163]
### Current Behavior

DrawerNavigator as root navigator, which renders a StackNavigator (could be anything else). Inside drawerNavigator's contentComponent render a View which renders other StackNavigator
- DrawerNavigator
    - StackNavigatorA
    contentComponent: SomeView (which renders StackNavigatorB)

Im getting this warning because StackNavigatorB is not "linked" with other navs.
![simulator screen shot - iphone x - 2018-10-22 at 18 35 44](https://user-images.githubusercontent.com/23704234/47305478-d88e2e80-d629-11e8-859b-866044f0c164.png)

### Expected Behavior

No warnings or at least provide a way to link everything.
I've tried to do something like this https://reactnavigation.org/docs/en/common-mistakes.html to link StackNavigatorB and DrawerNavigator but had no success

### How to reproduce

- Snack: https://snack.expo.io/@estebanbp/react-navigation-issue

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.18.0
| react-native     | 0.57.3
| node             | 10.12.0
| npm or yarn      | 6.4.1

**Comment by vonovak** [comment]
hi! Can you please expand on why you want to have a stack navigator inside a drawer's `contentComponent`? I'm not sure why one would do this..?

**Comment by brentvatne** [comment]
you're going to have a bad time if you try to do this, react-navigation-stack doesn't behave well outside of full-screen views at the moment

**Comment by EstebanBP** [comment]
@vonovak @brentvatne 
This is the basic navigation structure I had:
- SwitchNavigator
   - AuthStack
        - Login
        - Register
   - MainStack
        - ScreenA: Cars List
        - ScreenB: Car Info


The problem is that I need 1 extra view (full-screen and always accesible from MainStack) which contains other navigators inside (stack/tab) and should not be dismounted nor lose state unless user navigates to AuthStack. That's why I though this should be the new navigation structure:

- SwitchNavigator
    - AuthStack
        - Login
        - Register
    - DrawerNavigator
        - ScreenA: Cars List
        - ScreenB: Car Info
        - contentComponent: This view(full-screen) allows the user to navigate through DrawerNav screens (this works nice because it is what Drawer is designed for) but it also renders a navigator. 
E.g TabNavigator
   - Tab1: My cars
   - Tab2: Car wish list

I'm not sure I have explained it clear (to be honest my english is not good).

What do you think is the best solution to this problem? Should I just try to change app's design?

Thanks in advance! React-navigation is growing fast!

**Comment by brentvatne** [comment]
i think for now you should either use react-native-navigation (which has support for split views) or change the app design. sorry we just don't support this yet. you can post a feature request to https://react-navigation.canny.io/ :)

**Comment by tolik85** [comment]
Is this supported now? I need to have the drawer display 2 submenus, each one replacing the other.
Any other way to achieve the same effect? (like chaning
