### ISSUE TITLE
Huge Delay When Transitioning To Stack Nav in Drawer Nav

### ISSUE THREAD

**Issue by robbiemilejczak** [react-navigation/react-navigation#5165]
### Current Behavior

Title is not super accurate, what is happening is highly specific and a little strange. I have a horizontal `ScrollView` that is passing an `Animated.event` to the `onScroll` function with `useNativeDriver` set to `true` as the main screen of a stack navigator that is nested in a drawer navigator. When I navigate to that screen there is a huge delay (sometimes 20+ seconds) if `useNativeDriver` is set to true. If I set `useNativeDriver` to false the behavior stops. No other changes seem to affect the behavior, including render efficiency (even if it only renders once this happens) background code such as API calls, or the content nested in the `ScrollView`. I also feel I should mention I have only tested this on iOS

Basically I have this setup:

```
const StackWithModal = createStackNavigator(
  {
    MainScreen: {
      screen: Main
    },
    Form: {
      screen: Form 
    }
  },
  {
    mode: 'modal',
    headerMode: 'none'
  }
)

const Drawer = createDrawerNavigator(
  {
    Dashboard: {
      screen: Dashboard,
       //options
    },
    FormStack: {
      screen: StackWithModal
    }
```

so `StackWithModal` is a screen with a modal setup basically exactly how your docs describe, and it's nested inside `Drawer` and the `Main` component of the `StackWithModal` returns basically this:

```
<Animated.ScrollView
  bounces={false}
  style={{ flex: 1 }}
  onScroll={Animated.event(
    [
      {
        nativeEvent: {
          contentOffset: { y: this.transY },
        },
      },
    ],
    { useNativeDriver: true }
  )}
  contentContainerStyle={{
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
  }}
  minimumZoomScale={0.1}
  maximumZoomScale={2}
  scrollEventThrottle={16}>

  //any content can be returned it does not affect the behavior

</Animated.ScrollView>
```

### How to reproduce

See above, that is the minimal amount of code required to make this happen. I am currently unable to make a repo to showcase this but if needed I can find the time to do so sometime after my work day tomorrow.

I have seen a few other issues with similar problems (slow transitions with stack navigators) but I am certain this is not caused by any sort of DidMount or WillMount logic, or API calls, or expensive renders. This behavior is immediately improved upon setting useNativeDriver to false. I saw one maintainer say this would be fixed or at least improved with a 3.0 release. Is there a timeline for that? 

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.18
| react-native     | 57.2
| node             |  10.11
| yarn      | 1.10

**Comment by brentvatne** [comment]
heya feel free to create a new issue when you've had a chance to repro it! i would love to look at it

**Comment by robbiemilejczak** [comment]
@brentvatne I am unable to reproduce this on an actual physical device running a release variant, so I'm thinking the issue has more to do with the iOS simulator and my machine's resources (or lack thereof) and not actually a probably with your transition code.

I am still more than happy to make a repro if it would benefit you and your work

**Comment by brentvatne** [comment]
interesting! if you can create an example that reproduces it in the simulator that would be helpful
