### ISSUE TITLE
TypeError: Cannot read property 'state' of undefined in react-navigation@2.18.1

### ISSUE THREAD

**Issue by aixiaobenaixiaoben** [react-navigation/react-navigation#5167]
code is ok with react-navigation@2.6.2 but throw error with react-navigation@2.18.1.
page A navigate to page B.

code in A

    componentWillMount() {
	    if (!this.props.isLogin) {
	      this.jumpToLogin()
	    }
	  }

    shouldComponentUpdate(nextProps) {
	    if (!nextProps.isLogin) {
	      this.jumpToLogin()
	      return false
	    }
	    return true
	  }

    jumpToLogin = () => {
	    const resetAction = StackActions.reset({
	      index: 0,
	      actions: [NavigationActions.navigate({routeName: 'MyLogin'})],
	    })
	    this.props.navigation.dispatch(resetAction)
	  }
code in B(is not login page)

	logoutFunc = () => {
	    this.props.navigation.pop()
	    this.props.logout()//redux action
	  }
---

### Current Behavior
when logoutFunc is called, react-navigation@2.18.1 throws error:
TypeError: Cannot read property 'state' of undefined
![image](https://user-images.githubusercontent.com/5835729/47430375-ab798180-d7cb-11e8-86d5-ad13253a7eb6.png)

with react-navigation@2.6.2 everything is ok

shouldn't be compatible under version@2.x.x?

### Expected Behavior
no error with react-navigation@2.18.1

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |2.18.1
| react-native     |0.55.4
| node             |v10.0.0
| npm or yarn      |v1.6.0

**Comment by pdawson** [comment]
Same for me, just updated to the latest version. 

I think it may stem from nested navigators as when I call it on the 'Main' navigator, it works fine.

**Comment by brentvatne** [comment]
is this only with redux? can you reproduce without it? does it happen with 2.18.0 in addition to 2.18.1?

**Comment by aixiaobenaixiaoben** [comment]
@brentvatne no this error with 2.18.0
actually this scenario will be totally changed without redux

**Comment by brentvatne** [comment]
ok. sorry we don't support redux in this repo as per the issue template. see https://github.com/react-navigation/react-navigation-redux-helpers
