### ISSUE TITLE
didFocus fires too long after a navigate transition completes

### ISSUE THREAD

**Issue by robinclaes** [react-navigation/react-navigation#5168]
### Current Behavior

The didFocus event is called after the transition completed, making it feel laggy when firing another animation on "didFocus"

(I need to do it on didFocus because I need an elements X and Y)

### Expected Behavior

didFocus should be fired faster, making it feel snappy.

### How to reproduce

Register the didFocus event and start any animation.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.17.0
| react-native     | 0.57.0
| node             | 8.11.1
| npm or yarn      | yarn 1.3.2

**Comment by brentvatne** [comment]
can you try the latest alpha version and let me know if that addresses your concerns? 3.0.0-alpha.12, it includes this commit: https://github.com/react-navigation/react-navigation-stack/commit/7eab1628d1a8199b548e908ac188b38368675c88

**Comment by robinclaes** [comment]
@brentvatne  I could try, but looking at the code this only affects iOS? The problem exists on both platforms.

**Comment by brentvatne** [comment]
@robinclaes - i do not know about how it would impact android because that uses a timing based animation and it should be fired once the transition completes. i think if you care about knowing sooner you could use willFocus rather than didFocus?

**Comment by robinclaes** [comment]
@brentvatne willFocus doesn't have the final X and Y positions of my element yet.
On iOS I can calculate the X by doing X - screen width (because the transition comes from right)
On Android this isn't consistent. The transition comes from the bottom, and the first time this happens (when my screen is added to the stack) my Y is about 50 pixels too much, but once the screen is in the stack the Y value is about right.

**- What is the soonest way, in combination with React navigation, to find an elements X and Y?
- Is there a way to detect if the screen is being added to the stack or if it is already in the stack?**

Those questions could help me.

_PS: I'm using react native's measure to find the X and Y.
PPS: I've tried onLayout, and InteractionManager_

**Comment by robinclaes** [comment]
@brentvatne  see this gif to see what I mean with the animation delay. It doesn't feel fluid enough.
https://cl.ly/63b58b6007cb

**Comment by robinclaes** [comment]
Here's an example:
https://snack.expo.io/H1wtuURim

It doesn't run because the dependency  doesn't resolve, not sure. I haven't really worked with expo snack but the code is all there.

**Comment by brentvatne** [comment]
i updated it here - https://snack.expo.io/@notbrent/hello-react-navigation
the problem was that it said `this.props.navigate` and not `this.props.navigation.navigate`.. and `DidFocus` and not `didFocus`. i'm still not sure what i'm supposed to take from this example.

**Comment by brentvatne** [comment]
updated it again, this time i called `this.getLocation` in `onLayout` for the view - this is the earliest that you'd be able to measure it because it's after layout completes

**Comment by robinclaes** [comment]
https://snack.expo.io/B1TSRURjm 

Updated the snack. There's a 400ms delay right now between mounting and didFocus, which is quite alot faster than in my app...

**Comment by robinclaes** [comment]
onLayout is faster, but I need to subtract 50 from the Y: https://snack.expo.io/SyoHywRiQ

**Comment by brentvatne** [comment]
i think you have unrealistic expectations / a misunderstanding of what didFocus is supposed to do for you. the whole purpose of it is to fire when the animation completes. there is no single time where it can fire that it will satisfy what you are hoping it will do.

you can just use onLayout and get the position of the view within the parent to do what you want to do: https://snack.expo.io/@notbrent/hello-react-navigation

just keep in mind that onLayout gives you the x/y relative to the parent.
