### ISSUE TITLE
MaterialTopTabNavigator scroll position?

### ISSUE THREAD

**Issue by Jonovono** [react-navigation/react-navigation#5169]
Hi. One thing I would like to do is in my custom tab bar component get access to the scroll position as a user is swiping between tabs so that I can have an animation in my tab bar component that animates with you as you scroll. Is this possible?

Thanks!

**Comment by brentvatne** [comment]
hi there! this is a question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.
