### ISSUE TITLE
How to use tabBarIcon? why tell React is not undefind

### ISSUE THREAD

**Issue by yazhengwang** [react-navigation/react-navigation#5172]
### Current Behavior

- What code are you running and what is happening?
- Include a screenshot if it makes sense.
![image](https://user-images.githubusercontent.com/14901532/47470535-bb7b7a80-d838-11e8-9bdb-f4f64992d76e.png)

### Expected Behavior

- What do you expect should be happening?
- Include a screenshot if it makes sense.
![image](https://user-images.githubusercontent.com/14901532/47470448-617ab500-d838-11e8-8b95-4d28a182c0cd.png)

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.8.0
| react-native     |0.56.1
| node             |8.11.2
| npm or yarn      | npm

**Comment by yazhengwang** [comment]
![image](https://user-images.githubusercontent.com/14901532/47471105-71e05f00-d83b-11e8-9eee-0246aedbcdcb.png)

**Comment by brentvatne** [comment]
you need to have that import in the same file - imports are scoped to a single file. if that doesn't help please post a minimal reproducible example :) thanks
