### ISSUE TITLE
Is it possible to employ the sliding transition from createMaterialTopTabNavigator in createMaterialBottomTabNavigator?

### ISSUE THREAD

**Issue by nextriot** [react-navigation/react-navigation#5174]
I know this is for bugs, but I'd figured I'd ask anyways as questions regarding React Navigation tend to get overlooked or go unanswered on SO.

***
createMaterialTopTabNavigator has a sliding transition from screen to screen as you press the tabs, whereas createMaterialBottomTabNavigator uses a fading-in animation when it transitions.

Is there anyway to use the transition from the former with the latter?
***

SO Link: https://stackoverflow.com/questions/52998858/is-it-possible-to-employ-the-sliding-transition-from-creatematerialtoptabnavigat

Thanks for any help anyone can offer 👍

**Comment by brentvatne** [comment]
it is not possible at the moment. material bottom tab navigator uses https://callstack.github.io/react-native-paper/bottom-navigation.html which doesn't support this type of animation. if it were made to support this, then it could be exposed in react-navigation, but i don't think @satya164 is interested in doing that as it's not part of the material spec i believe.
