### ISSUE TITLE
i cant Authentication with facebook and i dont know whats problem

### ISSUE THREAD

**Issue by RobbieReyes1** [react-navigation/react-navigation#5176]
![image](https://user-images.githubusercontent.com/42710810/47592642-4cb83180-d99e-11e8-925f-2ee0b524d5e8.png)

and this is error on my emulator..

![screenshot_1540588371](https://user-images.githubusercontent.com/42710810/47592653-5fcb0180-d99e-11e8-949a-e00893ec23ec.png)

**Comment by RobbieReyes1** [comment]
please help me

**Comment by brentvatne** [comment]
glad you fixed it!
