### ISSUE TITLE
StackActions.reset did not trigger the transition animation

### ISSUE THREAD

**Issue by fantasy525** [react-navigation/react-navigation#5178]
### Current Behavior
![gif](https://user-images.githubusercontent.com/22516157/47614581-2fd64800-dadd-11e8-9c59-ce4893adee4c.gif)
```

		const resetActions=StackActions.reset({
			index:0,
			actions:[NavigationActions.navigate({routeName:"Register"})]
		})
		this.props.navigation.dispatch(resetActions)
```
when i click login Button,page jumps.but no transition animation,why?
I have set  the transitonConfig:
```
const LoginStack=createStackNavigator({
		Main:{
			screen:LoginHome
		},
		Register:{
				screen:Register
		}
},
	{
		initialRouteName:"Main",
		transitionConfig:()=>StackViewTransitionConfigs.SlideFromRightIOS,
		navigationOptions:{
			header:null
		}
	})
```

### Expected Behavior
![gif](https://user-images.githubusercontent.com/22516157/47614616-a115fb00-dadd-11e8-8052-61c7d3c33be5.gif)

Show the page switch animation` SlideFromRightIOS`

### How to reproduce

- You must provide a way to reproduce the problem. If you are having an issue with your machine or build tools, the issue belongs on another repository as that is outside of the scope of React Navigation.
- Either re-create the bug on [Snack](https://snack.expo.io) or link to a GitHub repository with code that reproduces the bug.
- Explain how to run the example app and any steps that we need to take to reproduce the issue from the example app.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.18.0
| react-native     | 0.57.1
| node             | 8.11.3
| npm or yarn      | 1.6.0

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!

**Comment by fantasy525** [comment]
I provide a example,[,https://snack.expo.io/rkqCWxEnQ](,https://snack.expo.io/rkqCWxEnQ)
@brentvatne

**Comment by fantasy525** [comment]
> hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.
> 
> you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.
> 
> please create a new issue with this and i'd be happy to review it!

you can run it

**Comment by bijuC1983** [comment]
Hello. Facing the same issue.
Basically, the transitionConfig animation do not run during Reset & Navigate. 
It runs fine during just navigate.
Is there a resolution to this?

**Comment by JuBertoo** [comment]
Hello, I have the same Problem. 
Do you have a solution ?

**Comment by johnlim5847** [comment]
Hey is there any update on this? like what @bijuC1983  mentioned the `transitionConfig` never fired during Reset is there any alternative solution for this?

**Comment by viirak** [comment]
Any update to this problem?
