### ISSUE TITLE
Constructor two screen component

### ISSUE THREAD

**Issue by xy371661665** [react-navigation/react-navigation#5179]
react-native info :
React Native Environment Info:
    System:
      OS: macOS 10.14
      CPU: x64 Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz
      Memory: 301.44 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.0.0 - /usr/local/bin/node
      Yarn: 1.7.0 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.0-alpha.8af6728 => 16.6.0-alpha.8af6728 
      react-native: 0.56.0 => 0.57.4 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-create-library: 3.1.2
      react-native-git-upgrade: 0.2.7

I have three screen:
![wx20181029-181926](https://user-images.githubusercontent.com/12904435/47643708-3b8e4100-dba7-11e8-9bb1-48495be12755.png)

App screen can navigate to Page1 and Page2

![wx20181029-182034](https://user-images.githubusercontent.com/12904435/47643830-8e67f880-dba7-11e8-8ef9-e88a40688292.png)

then I navigate to Page1 , back to App ,and navigate to Page2 fast.

Page1 will be constructor again,like this:
![wx20181029-182434](https://user-images.githubusercontent.com/12904435/47643975-eb63ae80-dba7-11e8-910a-f51b0ce016d5.png)

How can I fix it?

**Comment by brentvatne** [comment]
dup: https://github.com/react-navigation/react-navigation/issues/4155

this is fixed in the latest alpha version of react-navigation

**Comment by brentvatne** [comment]
yes. we will have instructions for it soon, as it's alpha we haven't prepared install instructions yet

**Comment by xy371661665** [comment]
thanks. what is the version we can use?3.0.0-alpha-15?or?

**Comment by brentvatne** [comment]
the latest alpha version for now, and we will release 3.0 proper soon
