### ISSUE TITLE
How can can I add existing page to route stack?

### ISSUE THREAD

**Issue by flyinghawker** [react-navigation/react-navigation#5181]
The case simply is that
I have an existing page displayed on top, want to add it to the  route stack so that I can use `goBack()` to leave the page. In another word, I don't need any screen entering animation for this case.
Is there any solution for this case? Thanks.

**Comment by brentvatne** [comment]
hi there! this is a question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.
