### ISSUE TITLE
 react-native-gesture-handler must install with 3.0.0-alpha-16

### ISSUE THREAD

**Issue by xy371661665** [react-navigation/react-navigation#5182]
React Native Environment Info:
    System:
      OS: macOS 10.14
      CPU: x64 Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz
      Memory: 255.42 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.0.0 - /usr/local/bin/node
      Yarn: 1.7.0 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0 
      react-native: 0.57.2 => 0.57.2 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-create-library: 3.1.2
      react-native-git-upgrade: 0.2.7

it is always need to install react-native-screens and react-native-gesture-handler when I use the version 3.0.0-alpha-16.when the version 3.0.0 release can be upload.

**Comment by tharindukulasinghe** [comment]
can you explain a bit more @

**Comment by brentvatne** [comment]
react-navigation@3.0.0-alpha.16 was accidentally published as latest, we marked the latest as 2.18.2 again. run `npm install react-navigation@^2.18.2` in your project to resolve.

we'll have instructions for installing 3.0.0 when we put out a rc release.
