### ISSUE TITLE
Application is frozen after calling Keyboard.dismiss() and pressing Back hardware Android.

### ISSUE THREAD

**Issue by tconns** [react-navigation/react-navigation#5183]
## Application is frozen after calling Keyboard.dismiss() and pressing Back hardware Android

Hi, brentvatne!
Sorry for the inconvenience that I made in the previous post.
This is the Repository I created to simulate the Issue: https://github.com/tconns/my-app-react-navigation

---

### Current Behavior

- Application is frozen after calling Keyboard.dismiss() and pressing Back hardware Android.

### Expected Behavior

- The application works normally.

### How to reproduce
- Example: "https://github.com/tconns/my-app-react-navigation"
- After calling Keyboard.dismiss() .
- Pressing Back hardware Android.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | v2.18.2
| react-native     | v0.57.4
| node             | v10.4.1
| npm or yarn      | npm-v6.4.1

**Comment by tconns** [comment]
Also, the problem occurs when the DrawerMenu opens.

**Comment by brentvatne** [comment]
thanks for reporting this! I fixed it on `react-navigation@3.0.0-alpha.18` - we'll release instructions soon on how to update along with the rc release.

here's a repo you can try to confirm that it works as expected now: https://github.com/brentvatne/lol-react-navigation-5183

**Comment by tconns** [comment]
You're amazing, brentvatne :))) I checked your repo, it works fine. Thank you!!
