### ISSUE TITLE
Is it possible to add a custom breadcrumb under the header component?

### ISSUE THREAD

**Issue by boonlai** [react-navigation/react-navigation#5189]
![breadcrumb](https://user-images.githubusercontent.com/23181321/47779177-7329f400-dd33-11e8-8907-512448240cae.PNG)

Hi, I would like to add a custom component, like a breadcrumb under the header component (as highlighted). I have tried to search for answer in stackoverflow and closed issues but failed. Sorry to bother you. 

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |2.16.0
| react-native     |0.57
| node             |
| npm or yarn      |

**Comment by eriveltonelias** [comment]
Hi @boonlai, 

you can do something like this

https://snack.expo.io/@eriveltonelias/our-first-navigate-v2
