### ISSUE TITLE
How to create component for static navigationOptions in React Navigation?

### ISSUE THREAD

**Issue by philong9192** [react-navigation/react-navigation#5192]
Hello everyone,

I want create navigationOptions in all component is same with props like below but not work:

`
static navigationOptions =  ({ navigation }) => {
    return (<NavigationOptions title: 'Sales Report'/>);
 };
`

`
class NavigationOptions extends Component {
  render() {
    return ({
    	title: this.props.title
    })
  }
}
`

Thank you so much!

**Comment by eriveltonelias** [comment]
hi there! this is a question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.

and also, please read the **navigationOptions** resolution:

https://reactnavigation.org/docs/en/navigation-options-resolution.html
