### ISSUE TITLE
createStackNavigator not accepting React component create with React.forwardRef

### ISSUE THREAD

**Issue by chunghe** [react-navigation/react-navigation#5193]
### Current Behavior

createStackNavigator not accepting React component create with `React.forwardRef`

snack: https://snack.expo.io/@chunghe/hello-world-v2

createStackNavigator accepts class-based component (HomeScreen), also works for functional component (FunctionComponent), but not working for forwarded component

![screenshot_20181101-122917](https://user-images.githubusercontent.com/78242/47832739-14678780-ddd2-11e8-8b84-396296bc1d5c.png)

### Expected Behavior

it should render correctly.

### How to reproduce

https://snack.expo.io/@chunghe/hello-world-v2

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.7.0

**Comment by brentvatne** [comment]
this is fixed in 3.0.0-rc.0, we'll post instructions for updating soon - https://snack.expo.io/@notbrent/thankful-orange

**Comment by sibelius** [comment]
@brentvatne can we do a path on react-navigation 2.x?

**Comment by brentvatne** [comment]
yeah if you open a pr for the branch i'll land it and do a release

**Comment by sibelius** [comment]
is there any reference commit ?

try to see in the commits of this repo, but I haven't find any

one workaround is to wrap the component with forwardref in a simple component using a hoc

```jsx
const withoutRef = (
   Component
) => {
  class Wrapper extends React.Component {
    render() {
      return <Component {...this.props} />
    }
  }

  return Wrapper;
}
```

**Comment by brentvatne** [comment]
https://github.com/react-navigation/react-navigation-core/commit/e4857b6c24ffa8c657887250954490ce1d3fe925

**Comment by deckyfx** [comment]
Still broken at @react-navigation/stack:^6.0.7
