### ISSUE TITLE
createBottomTabNavigator  can't recognize 'Ionicons'

### ISSUE THREAD

**Issue by BeatsX** [react-navigation/react-navigation#5196]
<img width="678" alt="wx20181101-175610 2x" src="https://user-images.githubusercontent.com/26688426/47845235-712d6700-ddff-11e8-820a-381d8b8c99ad.png">
<img width="725" alt="wx20181101-175233 2x" src="https://user-images.githubusercontent.com/26688426/47845237-72f72a80-ddff-11e8-9a59-6228f4c37818.png">
<img width="1098" alt="wx20181101-175144 2x" src="https://user-images.githubusercontent.com/26688426/47845239-74285780-ddff-11e8-98c6-9560085cce96.png">
<img width="363" alt="wx20181101-175051 2x" src="https://user-images.githubusercontent.com/26688426/47845242-75f21b00-ddff-11e8-91c1-262bcd2a51b0.png">
<img width="1111" alt="wx20181101-175028 2x" src="https://user-images.githubusercontent.com/26688426/47845245-77234800-ddff-11e8-8bb2-e845081d5f72.png">

**Comment by BeatsX** [comment]
Please help me!  I google methods to resolve this issue all two days.  but not ok

**Comment by eriveltonelias** [comment]
Hi @BeatsX! 

Ins't related with react-navigation but I just created an example to you on snack https://snack.expo.io/@eriveltonelias/create-tab-custom-navigation-stack

and also make sure if you're following all steps to linking react-native-vector icons into your project, please read on https://github.com/oblador/react-native-vector-icons
