### ISSUE TITLE
Nested DrawerNavigator header gap problem

### ISSUE THREAD

**Issue by erdouzun** [react-navigation/react-navigation#5199]
Hi everyone,

I use a nested drawer navigator in stack navigator. I researched same issues, found and tried to solve but nothing has changed.

In here, I have the same problem.

#1305

![img_0174](https://user-images.githubusercontent.com/34140509/47898825-89959400-de88-11e8-8c0f-fc2920727012.PNG)

Code is 

const mainScreenStack = createStackNavigator(
  
  {
    MainScreen: {
      screen: MainView,
    }
  },
  {
    navigationOptions: ({ navigation }) => ({
      initialRouteName: 'MainScreen',
      headerStyle: appStyle.genericHeaderStyle,
      
        headerTitle: headerTitle(),
        headerRight: headerRight(navigation),
        headerLeft: headerLeft(navigation),
        drawerLabel:'Erdo'
    }),
  }

)

export const MenuNavigator = createDrawerNavigator({

    MainScreen : {screen : mainScreenStack,
      navigationOptions: {
        //header:false, //hide header if not needed so whole screen slide  
        drawerLabel: () => null ,
          header: () => null
  }
    },
    ProfileScreen : Profile,
    ChangePasswordScreen : ChangePassword,
},
{
// contentOptions : 
// {
//   headerTintColor:'black'
// }

navigationOptions: {
  header:false, //hide header if not needed so whole screen slide  

}
}

versions 

"expo": "^27.0.1",
    "react": "16.3.1",
    "react-native": "~0.55.2",

**Comment by eriveltonelias** [comment]
Hi @erdouzun! 

Just add on your drawer config 

`header: null`

If it doesn't work for you, please add runnable example on https://snack.expo.io as the issue template explain.

**Comment by erdouzun** [comment]
Hi @eriveltonelias ,

I solved the problem with this 

MenuNavigator.navigationOptions = {
	header: () => null
};

I tried before "header : null" but it didn't work for me. 

Thanks for your help.
