### ISSUE TITLE
transitionConfig inside createNavigator.

### ISSUE THREAD

**Issue by kalraneeraj24550** [react-navigation/react-navigation#5202]
i want to have transition from right to left when navigate to other screen using StackRouter. 
we can use transitionConfig in case of stackNavigator. transitionConfig not working with StackRouter. plz help me...

import React, { Component } from 'react';
import { 
  Animated,
  Easing,
  Platform,
  Alert 
} from 'react-native';
import ScalingDrawer from 'react-native-scaling-drawer';
import Home from './screens/Home';
import OrderHistory from './screens/OrderHistory';
import LeftMenu from './ContainerMenu/LeftMenu';
import AddtoCart from './screens/AddToCart';
import SecondScreen from './screens/SecondScreen';
import Wine from './screens/Wine';
import MyCart from './screens/MyCart';
import Beer from './screens/Beer';
import Liqour from './screens/Liqour';
import BeerContainer from './screens/BeerContainer';
import Whisky from './screens/Whisky';
import CurrentOrder from './screens/CurrentOrder';
import Login from './screens/Login';
import SignUp from './screens/SignUp';
import Settings from './screens/Settings';
import CustomerAddPlace from './screens/CustomerAddPlace';
import EditProfile from './screens/EditProfile';
import ChangePassword from './screens/ChangePassword';
import LandingScreen from './screens/LandingScreen';
import customerSignup from './screens/customerSignup';
import Products from './screens/Products';
import DummyTextInput from './screens/DummyTextInput';
import SplashScreen from './components/SplashScreen';
import {
  createNavigator,
  createNavigationContainer,
  StackRouter,
  createStackNavigator,
  addNavigationHelpers,
  StackNavigator,
} from 'react-navigation';
import Transition from './components/Transition';

const defaultScalingDrawerConfig = {
  scalingFactor: 0.6,
  minimizeFactor: 0.6,
   swipeOffset: 20,

};

class CustomDrawerView extends Component {
  constructor(props) {
    super(props);
  }

  componentWillReceiveProps(nextProps) {
    /** Active Drawer Swipe **/
    if (nextProps.navigation.state.index === 0)
      this._drawer.blockSwipeAbleDrawer(false);

    if (nextProps.navigation.state.index === 0 && this.props.navigation.state.index === 0) {
      this._drawer.blockSwipeAbleDrawer(false);
      this._drawer.close();
    }

    /** Block Drawer Swipe **/
    if (nextProps.navigation.state.index > 0) {
      this._drawer.blockSwipeAbleDrawer(true);
    }
  }

  setDynamicDrawerValue = (type, value) => {
    defaultScalingDrawerConfig[type] = value;
    /** forceUpdate show drawer dynamic scaling example **/
    this.forceUpdate();
  };

  render() {
    const { routes, index } = this.props.navigation.state;
   const ActiveScreen = this.props.router.getComponentForState(this.props.navigation.state);
   TransitionConfiguration();
    return (
      <ScalingDrawer
        ref={ref => this._drawer = ref}
        content={<LeftMenu navigation={addNavigationHelpers({
          ...this.props.navigation,
          state: routes[index],
          openDrawer: () => this._drawer.open(),
          closeDrawer: () => this._drawer.close()
          })}
          // closeDrawerFun={this.closeDrawer.bind(this)}
          />}
        {...defaultScalingDrawerConfig}
        onClose={() => console.log('close')}
        onOpen={() => console.log('open')}
      >
        <ActiveScreen
          navigation={addNavigationHelpers({
            ...this.props.navigation,
            state: routes[index],
            openDrawer: () => this._drawer.open(),
          })}
          dynamicDrawerValue={(type, val) => this.setDynamicDrawerValue(type, val)}
        />
      </ScalingDrawer>
    )
  }

}

const CollapseExpand = (index, position) => {
  const inputRange = [index - 1, index, index + 1];
  const opacity = position.interpolate({
    inputRange,
    outputRange: [0, 1, 1],
  });

  const scaleY = position.interpolate({
    inputRange,
    outputRange: ([0, 1, 1]),
  });

  return {
    opacity,
    transform: [
      { scaleY }
    ]
  };
};

const SlideFromRight = (index, position, width) => {
  const inputRange = [index - 1, index, index + 1];
  const translateX = position.interpolate({
    inputRange: [index - 1, index, index + 1],
    outputRange: [width, 0, 0]
  })
  const slideFromRight = { transform: [{ translateX }] }
  return slideFromRight;
};

const TransitionConfiguration = () => {

  return {
    transitionSpec: {
      duration: 750,
      easing: Easing.out(Easing.poly(4)),
      timing: Animated.timing,
      useNativeDriver: true,
    },
    screenInterpolator: (sceneProps) => {
      const { layout, position, scene } = sceneProps;
      const width = layout.initWidth;
      const { index, route } = scene;
      const params = route.params || {}; // <- That's new
      const transition = params.transition || 'default'; // <- That's new
      return {
        collapseExpand: CollapseExpand(index, position),
        default: SlideFromRight(index, position, width),
      }[transition];
    },
  };
};

//  const navigators = StackNavigator ({
 

// }, 

//   {
//          initialRouteName: 'SplashScreen',
//       headerMode: 'screen',
//       mode: Platform.OS === 'ios' ? 'modal' : 'card',
//       navigationOptions: {
//           cardStack: {
//               gesturesEnabled: false
//           },
//           gesturesEnabled: false
//       },
//       gesturesEnabled: false,

//       transitionConfig: TransitionConfiguration,
//   });

const AppNavigator = StackRouter({
  DummyTextInput: { screen: DummyTextInput },
  OrderHistory: { screen: OrderHistory },
  Home: { screen: Home }, 
  Beer: { screen: Beer },
  AddtoCart: { screen: AddtoCart },
  SecondScreen: { screen: SecondScreen },
  BeerContainer: { screen: BeerContainer },
  MyCart: { screen: MyCart },
  Wine: { screen: Wine },
  Whisky: { screen: Whisky },
  Liqour: { screen: Liqour },
  CurrentOrder: { screen: CurrentOrder },
  Login: { screen: Login },
  SignUp: { screen: SignUp },
  Settings: { screen: Settings },
  CustomerAddPlace: { screen: CustomerAddPlace },
  EditProfile: { screen: EditProfile },
  ChangePassword: { screen: ChangePassword },
  LandingScreen: { screen: LandingScreen },
  customerSignup: { screen: customerSignup },
  Products: { screen: Products },
  SplashScreen: { screen: SplashScreen }

}, {
    initialRouteName: 'SplashScreen',
    headerMode: 'screen',
    drawerPosition: 'right',
    mode: Platform.OS === 'ios' ? 'modal' : 'card',
    navigationOptions: {
      cardStack: {
        gesturesEnabled: true,
        gesturesDirection: 'inverted'
      },
      gesturesEnabled: true,
      gesturesDirection: 'inverted'
    },
    gesturesEnabled: true,
    gesturesDirection: 'inverted',
    
    transitionConfig: () => ({
      transitionSpec: {
        duration: 250,
        easing: Easing.out(Easing.poly(4)),
        timing: Animated.timing,
      },
      screenInterpolator: sceneProps => {
        const { layout, position, scene } = sceneProps;
        const { index } = scene;
  
        const height = layout.initHeight;
        const translateX = position.interpolate({
          inputRange: [index - 1, index, index + 1],
          outputRange: [height, 0, 0],
        })
  
        const opacity = position.interpolate({
          inputRange: [index - 1, index - 0.99, index],
          outputRange: [0, 1, 1],
        })
  
        return { opacity, transform: [{ translateX }] }
      },
    }),
    });

 

const CustomDrawer = createNavigationContainer(createNavigator(AppNavigator)(CustomDrawerView));

export default CustomDrawer;

this is my code plz help me, am begging, i badly need help

**Comment by eriveltonelias** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.
you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.
please create a new issue with this and i'd be happy to review it!
