### ISSUE TITLE
react navigation V1 - setParams does not work

### ISSUE THREAD

**Issue by assafb81** [react-navigation/react-navigation#5206]
### Current Behavior
I have this code:
```
    static navigationOptions = ({ navigation }) => {
        const { state } = navigation;
        // Setup the header and tabBarVisible status
        const header = state.params && (state.params.fullScreen ? undefined : null);
        const tabBarVisible = state.params ? state.params.fullScreen : true;
        return {
            // If you're using stack navigators, you can hide the header bar like so
            header,
            // If you're using the tab navigators, you can hide the tab bar like so
            tabBarVisible,
        };
    }
```
and I update the `navigation.params` here:
```
    onFullScreen = (isFullScreen) => {
        this.props.navigation.setParams({
            fullScreen: !isFullScreen,
        });
    }
```
I am trying to hide tab bar when I have a video in full screen, But `naviation.params` is always undefined, `setParams` never adds `fullScreen` param.

If I modify the above method like:
```
    onFullScreen = (isFullScreen) => {
        this.props.navigation.state.params.fullScreen = !isFullScreen;
    }
```
Than `navigation.params` is not undefined and contain the proper value **BUT** it does not "hide" tabBar - I am guessing its because its not this is not the proper way to update tab navigator params.

I have a stack navigator that is nested inside tab navigator

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |1.5.2
| react-native     |0.55.4
| node             |8.11.3
| yarn      |1.7.0

**Comment by brentvatne** [comment]
we don't support v1, I recommend updating

**Comment by brentvatne** [comment]
it does work but maybe there is some edge case where it's not working for you, i'm unsure. you should update to v2 though
