### ISSUE TITLE
how can i create fixed drawer that always opened? 

### ISSUE THREAD

**Issue by MoeMamdouh** [react-navigation/react-navigation#5207]
Hi, i need to make app in tablets with fixed drawer.
the drawer opened by default and its always open in all the app screens and never closed, event if tap another scene from the drawer.
it's possible to do this case?

**Comment by brentvatne** [comment]
hi there! this is a question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.
