### ISSUE TITLE
How to use SwitchNavigator in hybrid iOS applications

### ISSUE THREAD

**Issue by HaloWang** [react-navigation/react-navigation#5211]
I'm now developing a hybrid iOS App. 
Currently I use one `RCTBridge` and multiple `RCTRootView` in my application to display page written by RN code. Each `RCTRootView` init with a module which is a `StackNavigator`. For example:
react side
```javascript

// A_Navigator.js
import {
  createStackNavigator,
} from 'react-navigation';
import Page from "./Page";

export default createStackNavigator({
  kPage: { screen: Page },
});

// index.js
...
import A_Navigator from './js/A_Navigator'
import B_Navigator from './js/B_Navigator'
import C_Navigator from './js/C_Navigator'
...
AppRegistry.registerComponent("A_Navigator", () => A_Navigator)
AppRegistry.registerComponent("B_Navigator", () => B_Navigator)
AppRegistry.registerComponent("C_Navigator", () => C_Navigator)
...
```
native side
```Objective-C
...
RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:sharedbridge moduleName:@"A_Navigator" initialProperties:initialProperties];
...
RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:sharedbridge moduleName:@"B_Navigator" initialProperties:initialProperties];
...
RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:sharedbridge moduleName:@"C_Navigator" initialProperties:initialProperties];
```

And I got a warning: 
> You should only render one navigator explicitly in your app, and other navigators should by rendered by including them in that navigator.

Is there any method to set `SwitchNavigator.initialRouteName` each time by params sent from Objective-C side?

**Comment by brentvatne** [comment]
you can silence that warning by adding the `detached={true}` prop to the navigator when you render it.

as for setting the initial route name, you can create the navigator from the initial props

```
class A extends React.Component {
  constructor(props) {
    super(props);
    this.A_Navigator = createStackNavigator({ .... }, { initialRouteName: this.props.whatever })
  }

  render() {
    let { A_Navigator } = this;
    return <A_Navigator detached={true} />;
  }
}
```

but by doing this you won't be able to navigate between A and B navigators, so i'm not sure how useful this is. we don't really support this use case though so i'll close the issue, sorry.

**Comment by HaloWang** [comment]
Thank you, no warning again after using `detached={true}`

**Comment by lazaronixon** [comment]
How use it with version 3?
