### ISSUE TITLE
jumpTo doesn't work

### ISSUE THREAD

**Issue by luco** [react-navigation/react-navigation#5213]
### Current Behavior

I'm trying to make a custom tabbar, but the `jumpTo` function doesn't work.

![image](https://user-images.githubusercontent.com/246373/48132522-0ce52a00-e27b-11e8-9d6d-f878eabf6b28.png)

### Expected Behavior

Jump to specified tab.

### How to reproduce

https://snack.expo.io/@lucoveiga/anVtcH

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  2.18.1
| react-native     | 0.56.0
| node             |  v11.0.0
| npm or yarn      | 6.4.1

**Comment by luco** [comment]
@eriveltonelias Hey!
What did you change?

**Comment by luco** [comment]
@eriveltonelias This actually works, but I can't figure out why it doesn't work on my custom tabbar. It's the same code but doesn't work.

**Comment by eriveltonelias** [comment]
@luco are you using the same version of react-navigation and expo ? 

Expo SDK 31 and react navigation 2.18.2

**Comment by luco** [comment]
@eriveltonelias Somehow I just switched my code with yours and it worked. I'm trying to understrand what I did wrong.
