### ISSUE TITLE
setting opacity in headerRightContainerStyle or headerLeftContainerStyle does not work

### ISSUE THREAD

**Issue by beaurushton** [react-navigation/react-navigation#5214]
### Current Behavior

Setting
```
static navigationOptions = ({ navigation }) => ({
  headerLeftContainerStyle: {
    backgroundColor: 'red',
    opacity: 0.5,
  },
});
```
Background color applies but opacity does not.

### Expected Behavior

All styles should apply.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.16.0

**Comment by brentvatne** [comment]
opacity is determined by the animation on this component, it fades when you transition away from it. if you want to customize the opacity then do it on the component inside. i don't see a use case why you would need this

**Comment by beaurushton** [comment]
My use case is I am creating an iOS11 style header and want to fade in my headerLeft component as the user scrolls a ScrollView in the main window.  This is tied to an Animated value which I haven't found a way to pass though any other way.
