### ISSUE TITLE
Installation via npm stops at "math-random@1.0.1 checking installable status"

### ISSUE THREAD

**Issue by xjrimus** [react-navigation/react-navigation#5216]
![screen shot 2018-11-08 at 15 43 13](https://user-images.githubusercontent.com/11455982/48206011-af7dd580-e36d-11e8-8f85-32bc93efb8e8.png)

My Installation of the npm module stucks everytime at the same place "math-random@1.0.1 checking installable status". I've tried with different releases, no success. 

Node v10.12.0
NPM v6.4.1

This project I'm running with Expo, one other which I've created with React Native CLI and where the module installation works.. any ideas?

**Comment by brentvatne** [comment]
sounds like an issue with npm. maybe run `npm cache clean` or post to npm support forums
