### ISSUE TITLE
How to reset params when returning to a screen

### ISSUE THREAD

**Issue by auzair92** [react-navigation/react-navigation#5219]
I am facing unexpected behavior using `StackNavigator` and `addListener`.

### Current Behavior
I have three screens in a `StackNavigator`: `Dashboard`, `EditProfile`, and `Preferences`. For simplicity, suppose any screen can be accessed from any other screen using `navigate()`. Consider the use case: User starts out at `Dashboard` and navigates to `EditProfile`. When I set params when navigating back from `EditProfile` to `Dashboard`, they persist in the navigation object's `state` and I can't seem to get rid of them when navigating from this point forward. 

### How to reproduce
I have a simple Expo Snack [here](https://snack.expo.io/@auzair/reactnavigationsnack). To reproduce the issue, follow these steps:
- Tap `Go to EditProfile`
- In the `EditProfile` screen, tap `Go to Dashboard` to return to Dashboard
- Now the param `previousScreen` is set to `EditProfile`
- Tap `Go to Preferences`
- Now tap the **Back button** to return to Dashboard screen
- The param `previousScreen` is _still_ set to `EditProfile`

### Expected Behavior
My understanding was that params are only used when navigating from one screen to other. Why is the param `previousScreen` persisting? I want to clear the params when I return to `Dashboard` screen.

### Environment

| software         | version
| ---------------- | -------
| react-navigation |2.11.2
| react-native     |0.55.4

**Comment by eriveltonelias** [comment]
Hi @auzair92! 

you can create a custom android back button behavior, read this on https://reactnavigation.org/docs/en/custom-android-back-button-handling.html#docsNav

and also, I updated your example: https://snack.expo.io/@eriveltonelias/reactnavigationsnack

Tell me if is that what you're looking for.

**Comment by auzair92** [comment]
In addition to the custom back button functionality, I also found that I can use `this.props.navigation.setParams()` to manually set the params (I initially thought the params were only the variables which can be passed when navigating from one screen to other). 

Thank you very much for the response, it helped!
