### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by alshamynet** [react-navigation/react-navigation#5221]
Hi !
I do not speak English but I do translate in Google Translate.
When I install (React Navigation) the download reaches about 35% and is not complete then the error messages appear and I do not know what the problem is.
Do you help me with that? Here is the picture below in the link , sorry for the translation 
Note that my OS is Windows 7   32 bit
Thank you
[https://goo.gl/mXtULP](url)

**Comment by abn-volk** [comment]
Please download and install Git: https://git-scm.com/downloads

**Comment by eriveltonelias** [comment]
Hi @alshamynet! 

Sorry, but it isn't related with react-navigation.

read this https://github.com/react-navigation/react-navigation/issues/5216 and also maybe it can help you too https://stackoverflow.com/questions/26620312/installing-git-in-path-with-github-client-for-windows
