### ISSUE TITLE
Unable to resolve module './createNavigationContainer'

### ISSUE THREAD

**Issue by Kasendwa** [react-navigation/react-navigation#5222]
Hey,

I just installed "react-navigation": "3.0.0-rc.5", but I can't get the project to bundle. I get the error

error: bundling failed: Error: Unable to resolve module `./createNavigationContainer` from `/Users/[...]/node_modules/react-navigation/src/react-navigation.js`: The module `./createNavigationContainer` could not be found from `/Users/[...]/node_modules/react-navigation/src/react-navigation.js`. Indeed, none of these files exist:
  * `/Users/[...]/node_modules/react-navigation/src/createNavigationContainer(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)`

I am using;

"react": "16.6.0-alpha.8af6728",
"react-native": "0.57.4",

**Comment by eriveltonelias** [comment]
Hi @Kasendwa, 

on V3 is required that you use the `createAppContainer`

read on: https://reactnavigation.org/docs/en/app-containers.html#docsNav

and https://reactnavigation.org/blog/2018/11/01/react-navigation-3.0-rc.html

**Comment by wangdicoder** [comment]
I got the same situation like Kasendwa when I upgrade the library from v1 to v3. However, if I create a new project using v3 directly, this situation doesn't have.

**Comment by Kasendwa** [comment]
@wangdicoder exactly! I was also coming from v1 to v3.

@eriveltonelias no, I did not even try to use createNavigationContainer; I was using createAppContainer but somehow the library points to createNavigationContainer itself.

**Comment by eriveltonelias** [comment]
Yeah, on v3 to work you need  import createAppContainer in the root of your app and use it to wrap the root navigator.

https://reactnavigation.org/blog/2018/11/01/react-navigation-3.0-rc.html#explicit-app-container-required-for-the-root-navigator

**Comment by Kasendwa** [comment]
@eriveltonelias I followed that same tutorial. I think like @wangdicoder stated this issue occurs if you updated an alreday existing project.

**Comment by eriveltonelias** [comment]
hi @Kasendwa 

try to clear all cache from your project  yarn.lock or package-lock.json

**Comment by kraffslol** [comment]
Had the same issue when migrating from V2 to V3 on Windows. Managed to fix it by going to the %TEMP% directory and removing the directory called metro-cache.

**Comment by rahmatputrawiranata** [comment]
> Had the same issue when migrating from V2 to V3 on Windows. Managed to fix it by going to the %TEMP% directory and removing the directory called metro-cache.

you really da best mvp here it should be noted

**Comment by tonycoco** [comment]
You can also just `expo start -c` if using Expo. This clears the packager.

**Comment by JonnyBurger** [comment]
`react-native --reset-cache` the easy way if you have a standalone React Native project.

**Comment by onmyway133** [comment]
Had this issue after upgrading from v2 to v3, need to clear the cache too with `npm start -- --reset-cache`

**Comment by laurentsmohr** [comment]
@JonnyBurger 
> react-native --reset-cache
`error: unknown option '--reset-cache'`

**Comment by Joyreece** [comment]
> @JonnyBurger
> 
> > react-native --reset-cache
> > `error: unknown option '--reset-cache'`

Hey, bro, try `npm start -- --reset-cache`.

**Comment by JonnyBurger** [comment]
@laurentsmohr @Joyreece Should have been `react-native start --reset-cache`. Updated my comment

**Comment by koreus7** [comment]
@jwilliamson1 You must be new to react native though I agree. It's the wild west, we are still pre version 1.0 and production apps are being made with this stack.

Here is a little shell script to clean up everything, comes in handy often, fire and forget.

```
watchman watch-del-all
rm -rf /tmp/metro-bundler-cache-*
rm -rf /tmp/haste-map-react-native-packager-*
react-native start --reset-cache
```
