### ISSUE TITLE
can i use `TabNavigator` and `DrawerNaigator` share same screen ?

### ISSUE THREAD

**Issue by geminiyellow** [react-navigation/react-navigation#5226]
hi all, i try to find out how to use  `TabNavigator` and `DrawerNaigator` to control same screen,
but looks cannot do this. anybody can help me ?

what i want is like this image:

![image](https://user-images.githubusercontent.com/929878/48329576-b9b11400-e68c-11e8-8882-e60dc27284d5.png)

**Comment by eriveltonelias** [comment]
hi there! this is a question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.
