### ISSUE TITLE
use `createMaterialTopTabNavigator` in `render` will cause Red WARNING

### ISSUE THREAD

**Issue by geminiyellow** [react-navigation/react-navigation#5227]
### Current Behavior

```
render() {
    const { categories } = this.props;
    if (!categories) return null;

    const Tabs = createMaterialTopTabNavigator(this.tabs(categories), options);
    if (!Tabs) return null;

    return (<Tabs />);
  }
```

then

>
> Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.

use `createTabNavigator` can fix it , but 

>
> react-navigation.js:56 createTabNavigator is deprecated. Please use the createBottomTabNavigator or createMaterialTopTabNavigator instead.

### Expected Behavior

no Red WARNING

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | "^2.18.2",

**Comment by eriveltonelias** [comment]
hi! please make your code runnable either on https://snack.expo.io without any extraneous code

**Comment by geminiyellow** [comment]
hi @eriveltonelias , not in native app, i use it in `react-native-web`

**Comment by brentvatne** [comment]
we don't explicitly support react-native-web right now, ymmv
