### ISSUE TITLE
Error navigating between stack 

### ISSUE THREAD

**Issue by jonathangreco** [react-navigation/react-navigation#5231]
### Current Behavior

I've a Screen named ProjectScreen (listing all project I have on my device). For each project I've the code below :

```
<TouchableOpacity onPress={() => this.handleContinue()} style={styles.touchableImage}>
	<ImageBackground
	    imageStyle={{borderRadius: 26}}
	    source={{uri: path}}
	    style={[styles.imageInTouchable]}
	    resizeMode='cover'>
	  <View style={{position:'absolute', borderRadius: 26, height:"100%", width: "100%", backgroundColor:'rgba(0,0,0,0.3)'}}/>
	  <Text style={styles.continueText}> {I18n.t("continue")} > </Text>
	</ImageBackground>
</TouchableOpacity>
```
Runnning this code with

```
handleContinue() {
  this.props.navigation.navigate("BeginTemplateScreen");
}
```
On click from this touchable I'll go to the BeginTemplateScreen (wich belongs to another stack (see the following post to know how my navigation is built))

This behaviour is working well. But from BeginTemplateScreen's stack I've a button back that make a dismiss, and from there, problems begins.

## Step to reproduce (navigation construction is in the post below this one)
I Have two screen :
- ProjectScreen (Initial Route Name) of its stack.
- BeginTemplateScreen is in another stack

From ProjectScreen I navigate to the beginTemplateScreen. Then I use a navigation.dismiss() to go back.
Then i click again on the touchable twice.

If I'm fast enouth, I get an error :

> undefined is not an object (evaluating 'navigation.state')
![capture d ecran 2018-11-13 a 14 29 22](https://user-images.githubusercontent.com/1587180/48416460-918ae900-e750-11e8-8169-de7c0a56e94f.png)

This error is only happening when a user press really fast the button twice.

### Expected Behavior

- The bug does not occur when the ProjectScreen is Mounted for the first time and BegintemplateScreen was never called. The bug only start to occur when the Dismiss (or navigate I tried to replace it) is called. So we expect that the navigation behaviour keeps the same anytime we navigate trougth screens.
- The bug also not occur when I add my BeginTemplateScreen's stack to the projectScreen's stack.
- The bug will not occur if we wait long enouth (1-2 seconds) and press one time the touchable (in other words : be gentle)

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^2.11.2
| react-native     | 0.57.4
| node             | 8.9.0
| npm or yarn      | yarn 1.10.1

**Comment by jonathangreco** [comment]
Here's is my whole stack construction :

```
import React from "react";
import {
  createDrawerNavigator,
  createStackNavigator,
  createSwitchNavigator,
  DrawerItems,
} from "react-navigation";
import { Button, Icon } from "native-base";

import I18n from "../i18n/i18n";

import LoginScreen from "../screens/LoginScreen";
import ProfileScreen from "../screens/ProfileScreen";
import ProjectScreen from "../screens/ProjectScreen";
import AuthLoadingScreen from "../screens/AuthLoadingScreen";
import SettingsScreen from "../screens/SettingsScreen";
import LogoutScreen from "../screens/LogoutScreen";
import TemplateMainContainer from "./TemplateMainContainer";
import NewFilmScreen from "../screens/NewFilmScreen";
import ForgottenPasswordScreen from "../screens/ForgottenPasswordScreen";

import { getStatusBarHeight } from 'react-native-status-bar-height';
import {View} from "react-native";

// drawer stack
const AppNavigation = createDrawerNavigator(
  {
    ProjectScreen: { screen: ProjectScreen },
    NewFilmScreen: { screen: NewFilmScreen },
    ProfileScreen: { screen: ProfileScreen },
    //SettingsScreen: { screen: SettingsScreen },
    LogoutScreen: { screen: LogoutScreen }
  },
  {
    drawerBackgroundColor: "#ff4559",
    // Default config for all screens
    headerMode: "none",
    initialRouteName: "ProjectScreen",
    contentOptions: {
      activeTintColor: "#fff",
      inactiveTintColor: "#fff",
      itemsContainerStyle: {
        marginVertical: 0
      },
      itemStyle: {
        flexDirection: "row-reverse"
      },
      iconContainerStyle: {
        opacity: 0.8
      }
    },
    contentComponent: props => (
      <View style={{paddingTop: getStatusBarHeight() + 10 }}>
        <Button transparent>
          <Icon
            name="close"
            style={{ fontSize: 40, color: "white" }}
            onPress={() => {
              props.navigation.closeDrawer();
            }}
          />
        </Button>
        <DrawerItems {...props} />
      </View>
    )
  }
);

const WrapperStack = createStackNavigator({
    AppDrawer: AppNavigation,
    TemplateMainContainer: {
      screen: TemplateMainContainer,
      navigationOptions: {
        headerMode: "none",
        drawerLabel: I18n.t("newFilm"),
        drawerIcon: () => (
          <Icon
            type={"MaterialIcons"}
            name={"add-circle-outline"}
            style={{ color: "#fff", fontSize: 25 }}
          />
        )
      }
    },
  },
  {
    headerMode: "none"
  }
);

/**
 * New stack
 */
const LoginStack = createStackNavigator(
  {
    LoginScreen: LoginScreen,
    ForgottenPasswordScreen: ForgottenPasswordScreen
  },
  {
    initialRouteName: "LoginScreen",
    headerMode: "none"
  }
);

// Manifest of possible screens, when the user sign in the loginStack will be unmount to never logged out the user with
// the back button
const PrimaryNav = createSwitchNavigator(
  {
    AuthLoading: { screen: AuthLoadingScreen },
    Auth: { screen: LoginStack },
    App: { screen: WrapperStack }
  },
  {
    initialRouteName: "AuthLoading"
  }
);

export default PrimaryNav;

```


```
import React  from "react";
import { createStackNavigator } from "react-navigation";
import BeginTemplateScreen from "../screens/BeginTemplateScreen";
import WorkflowScreen from "../screens/WorkflowScreen";
import ValidationScreen from "../screens/ValidationScreen";
import RenderedScreen from "../screens/RenderedScreen";
import CompareScreen from "../screens/CompareScreen";
import CameraScreen from "../screens/CameraScreen";
import UploadScreen from "../screens/UploadScreen";

export default createStackNavigator(
  {
    BeginTemplateScreen: {
      screen: BeginTemplateScreen
    },
    CameraScreen: {screen: CameraScreen},
    CompareScreen: { screen: CompareScreen },
    WorkflowScreen: { screen: WorkflowScreen },
    ValidationScreen: { screen : ValidationScreen },
    UploadScreen: { screen: UploadScreen },
    RenderedScreen: { screen: RenderedScreen }
  },
  {
    initialRoute: "BeginTemplateScreen",
    headerMode: "none"
  }
);

```


The bug will not occur in this configuration (but I can't stay with this) :

```
// drawer stack
const AppNavigation = createDrawerNavigator(
  {
    ProjectScreen: { screen: ProjectScreen },
    NewFilmScreen: { screen: NewFilmScreen },
    ProfileScreen: { screen: ProfileScreen },
    //SettingsScreen: { screen: SettingsScreen },
    LogoutScreen: { screen: LogoutScreen },
    TemplateMainContainer: {
      screen: TemplateMainContainer,
      navigationOptions: {
        headerMode: "none",
        drawerLabel: I18n.t("LastTemplate"),
        drawerIcon: () => (
          <Icon
            type={"MaterialIcons"}
            name={"add-circle-outline"}
            style={{ color: "#fff", fontSize: 25 }}
          />
        )
      }
    },
  },
  {
    drawerBackgroundColor: "#ff4559",
    // Default config for all screens
    headerMode: "none",
    initialRouteName: "ProjectScreen",
    contentOptions: {
      activeTintColor: "#fff",
      inactiveTintColor: "#fff",
      itemsContainerStyle: {
        marginVertical: 0
      },
      itemStyle: {
        flexDirection: "row-reverse"
      },
      iconContainerStyle: {
        opacity: 0.8
      }
    },
    contentComponent: props => (
      <View style={{paddingTop: getStatusBarHeight() + 10 }}>
        <Button transparent>
          <Icon
            name="close"
            style={{ fontSize: 40, color: "white" }}
            onPress={() => {
              props.navigation.closeDrawer();
            }}
          />
        </Button>
        <DrawerItems {...props} />
      </View>
    )
  }
);

```


Any help would be very appreciated

**Comment by eriveltonelias** [comment]
Hi @jonathangreco, 
create a runnable example on https://snack.expo.io please.

**Comment by jonathangreco** [comment]
Hi @eriveltonelias  Thanks for yor answer, I tried to reproduce it here

https://snack.expo.io/@jonathan01/vengeful-chip

But the bug not comes up.
It seems the bug only occurs because consecutive redux calls during navigation. I don't know if I can fix this at the moment.

Then I suppose it's not directly relative to react-navigation.

**Comment by eriveltonelias** [comment]
@jonathangreco you're welcome

please read https://github.com/react-navigation/react-navigation-redux-helpers 
and also `react-navigation-redux-helpers` https://github.com/react-navigation/react-navigation-redux-helpers

**Comment by tbergq** [comment]
Hi, I had the exact same error using
• React-navigation 2.18.1
• react-native: 0.57.4

I could only reproduce the error on an actual device, and it happened when closing a modal screen, and opening the same modal screen directly after it closed. 

Our project does not use redux, but we use relay and react context api for state management. 

We are in the process of upgrading to react-navigation 3.0, and I have not been able to reproduce the bug in our branch with 3.0. So it seems to be fixed with that release. 

![img_0001](https://user-images.githubusercontent.com/7705041/48903704-95a7bc80-ee5c-11e8-87a6-e68d94558e60.PNG)

**Comment by jonathangreco** [comment]
hi @tbergq it's funny that I received your message now because I was just fixing it on my application.

Personnaly I had this issue because I was using a stackNavigator instead of SwitchNavigator.
But I don't think that it will fix your issue
