### ISSUE TITLE
(0, _reactNavigation.createDrawerNavigator) is not a function.

### ISSUE THREAD

**Issue by xanderberkein** [react-navigation/react-navigation#5232]
### Current Behavior

When trying to create a DrawerNavigator in the v3-rc.5, I get the error below. The error only appears when I try to run the project.

```
Device: (945:881) (0, _reactNavigation.createDrawerNavigator) is not a function. (In '(0, _reactNavigation.createDrawerNavigator)({
  Home: {
    screen: HomeScreen
  }
})', '(0, _reactNavigation.createDrawerNavigator)' is undefined)
  Evaluating module://App.js
  Loading module://App.js
```

### How to reproduce

See this snack : https://snack.expo.io/@x11n/grounded-milkshake

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.0.0-rc.5

**Comment by brentvatne** [comment]
this appears to be a bug with snack, this same project works fine locally

**Comment by AftabUfaq** [comment]
I have the  Issue : reactNavigation.Drawer is not a funtion .In '(0,_reactnavigation.DrawerNavigator) ({

)}

import React,{Component} from 'react';
import {Text,View,StyleSheet,Image,Alert,Dimensions,TouchableOpacity,Button} from 'react-native';
const {width: WIDTH} = Dimensions.get('window').width ;
import { DrawerNavigator } from 'react-navigation'
import  HomeScreen  from './src/screens/HomeScreen/index'
import  DetailsScreen  from './src/screens/DetailsScreen/index'

class App extends Component {
  render() {
    return <MyApp />;
  }
}


const MyApp = DrawerNavigator({
  HomeScreen:
  {
    screen: HomeScreen
  },
  DetailsScreen:
  {
    screen: DetailsScreen
  }

})


export default App ;
const styles = StyleSheet.create({
  container: {
    flex:1,
    flexDirection: 'column',
    backgroundColor: '#ffffff',
    alignItems:'center',
    justifyContent:'center'

  },

  imagecont:{
    flex: 0.60,
    justifyContent:"flex-start"  
  },
 btn:{
   color:"purple",

 },
  txtDefault: {
    paddingTop:20,   
    height:50,
    color: '#010311',
    fontSize: 14,
    color:'purple',
    fontWeight:'bold',
    position: 'absolute',
    bottom: 0,
    borderWidth:2,
    borderColor:'black',
    backgroundColor:'gray',
    width:WIDTH,
  },
  footer:{
    flex:1,
    height:70,
    backgroundColor:'gray',
    position: 'absolute',
    bottom: 0,
    justifyContent:'center',
    alignContent:'center',
    alignItems:"center",
    width:WIDTH,
    opacity:.6,
  }  
});
