### ISSUE TITLE
present ios landspace page, react-navigation's navigation bar  bouncing up and down

### ISSUE THREAD

**Issue by lhjzzu** [react-navigation/react-navigation#5235]
when I communicate with iOS by native modules 。 i present a ios native landspace  page, But I saw the react-navigation's navigation bar bouncing up and down。

The following code：

## js
 onPress = () =>  {
      const CommunicationModule = NativeModules.CommunicationModule; 
      CommunicationModule.test()     
    }

## ios 
CommunicationModule.m

RCT_EXPORT_METHOD(test){
  dispatch_async(dispatch_get_main_queue(), ^{
    UIViewController *rootVC = [UIApplication sharedApplication].keyWindow.rootViewController;
    TestViewController *testVC = [TestViewController new];
    [rootVC presentViewController:testVC animated:YES
                       completion:nil];
  });
} 

TestViewController.m

- (void)viewDidLoad {
    [super viewDidLoad];
    // Do any additional setup after loading the view.
    self.view.backgroundColor = [UIColor redColor];
    
    UILabel *text = [[UILabel alloc] init];
    text.text = @"哈哈哈哈哈哈哈哈哈哈";
    text.frame = CGRectMake(100, 100, 100, 50);
    [self.view addSubview:text];
}

- (void)touchesBegan:(NSSet<UITouch *> *)touches withEvent:(UIEvent *)event {
    [self dismissViewControllerAnimated:YES completion:nil];
}

- (UIInterfaceOrientationMask)supportedInterfaceOrientations {
    return UIInterfaceOrientationMaskLandscapeLeft | UIInterfaceOrientationMaskLandscapeRight;
}

- (UIInterfaceOrientation)preferredInterfaceOrientationForPresentation {
    if ([UIApplication sharedApplication].statusBarOrientation == UIInterfaceOrientationLandscapeLeft) {
        return UIInterfaceOrientationLandscapeLeft;
    } else  if ([UIApplication sharedApplication].statusBarOrientation == UIInterfaceOrientationLandscapeRight) {
        return UIInterfaceOrientationLandscapeRight;
    }

    return UIInterfaceOrientationLandscapeLeft;
}
- (BOOL)shouldAutorotate {
    return YES;
}

![simulator screen shot - iphone 6 - 2018-11-15 at 15 02 00](https://user-images.githubusercontent.com/10206335/48536195-cd58b680-e8e8-11e8-9664-947d889a0f10.png)

![simulator screen shot - iphone 6 - 2018-11-15 at 15 01 49](https://user-images.githubusercontent.com/10206335/48536206-d47fc480-e8e8-11e8-8b10-e31a67844532.png)

![simulator screen shot - iphone 6 - 2018-11-15 at 15 02 16](https://user-images.githubusercontent.com/10206335/48536215-d9447880-e8e8-11e8-8beb-bb376d025bd8.png)

![aaaaa](https://user-images.githubusercontent.com/10206335/48536303-21fc3180-e8e9-11e8-8f79-66b3ee237f30.gif)

| software              | version
| ---------------- | -------
| react-navigation |  2.18.2
| react-native         | 0.57.1
| node                     | v8.8.1  
| yarn                      |  1.7.0

**Comment by brentvatne** [comment]
the header adjusts according to the status bar height using react-native-safe-area-view, please create a minimal reproducible example and re-post to that repository: https://github.com/react-community/react-native-safe-area-view.
