### ISSUE TITLE
Using withNavigation with a named export

### ISSUE THREAD

**Issue by bonbonio** [react-navigation/react-navigation#5236]
Hi,

How can I apply withNavigation to a component where I want the export to be named? The examples only provide an example when the export is default.

```
import React from 'react';
import { withNavigation } from 'react-navigation';

class RandomComponent extends React.Component {
   // ...
}

export withNavigation(RandomComponent);
```

I want to export this named as RandomComponent not as default, its probably something obvious :(

**Comment by vonovak** [comment]
hi! use `export cont NamedComponent = withNavigation(RandomComponent);`

**Comment by bonbonio** [comment]
@vonovak Thanks!
