### ISSUE TITLE
Can't check whether the drawer is open or not!!

### ISSUE THREAD

**Issue by bachlongkocanh** [react-navigation/react-navigation#5237]
Hi, I has problem, I can't check whether the drawer is open or not.
``this.props.navigation.state.isDrawerOpen`` return error not found.
`* React-native version: 0.55.3`
`* React-navigation: ^2.18.2`.
Console log this.props.navigation:
<img width="603" alt="screen shot 2018-11-15 at 8 16 34 pm" src="https://user-images.githubusercontent.com/28125294/48555677-7537a980-e914-11e8-8de6-28b939ea894d.png">
Please help me. Thanks!

**Comment by eriveltonelias** [comment]
Hi @bachlongkocanh, 

you can do the following: 

```js
const parent = this.props.navigation.dangerouslyGetParent();
 
const isDrawerOpen = parent && parent.state && parent.state.isDrawerOpen;
```

**Comment by bachlongkocanh** [comment]
Thanks you, it woking!! thank you so much.😍😍😍😍

Vào Th 5, 15 thg 11, 2018 vào lúc 20:56 Erivelton Elias <
notifications@github.com> đã viết:

**Comment by bachlongkocanh** [comment]
thank you, it work for me.

**Comment by eriveltonelias** [comment]
you're welcome! :)
