### ISSUE TITLE
Drawer navigation doesn't always navigate

### ISSUE THREAD

**Issue by rauldeheer** [react-navigation/react-navigation#5239]
#### Current Behavior

I'm running a normal app, nothing special with a `bottomTabNavigator` a `drawerNavigator` and a few `stackNavigators`. I'm sometimes unable to navigate to a certain route within the `drawerNavigator`. 

You can see the video below if you want to visualize it:
![ezgif-3-3c5d73bdaf9c](https://user-images.githubusercontent.com/25283219/48635221-dff5ed00-e9c7-11e8-8562-cf51023c9a1b.gif)

#### Expected Behavior

I'm expecting it to function normally and allow everyone to route to any page.

I'm not sure if I'm doing something wrong but it looks like a bug. I've also made a [Stackoverflow](https://stackoverflow.com/questions/53338089/drawer-navigation-doesnt-always-navigate) post.

Any help is much appreciated!

#### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.18.2
| react-native     | Expo's version [SDK 31.0.0]
| node             | 11.1.0
| npm or yarn      | NPM / v6.4.1

**Comment by brentvatne** [comment]
this should be resolved in 3.0, try updating to see :) if not please create new issue with reproducible example

**Comment by rauldeheer** [comment]
@brentvatne while creating a reproducible example I found the error. I forgot to change some things, totally my fault. Sorry and thanks for helping. v3.0 looks awesome by the way! @brentvatne
