### ISSUE TITLE
react navigation 3.0  "'State' " is undefined

### ISSUE THREAD

**Issue by dxc0522** [react-navigation/react-navigation#5240]
new React navigation 3.0.0.
error is Cannot read property 'State' of undefined.

**Comment by brentvatne** [comment]
please follow the issue template

**Comment by msweetland** [comment]
react-native-gesture-handler is not linked to the xCode project

**Comment by wilywork** [comment]
Not work for me, I don't have react-native-gesture-handler in my project

**Comment by brentvatne** [comment]
you need to add it @wilywork

**Comment by brentvatne** [comment]
https://reactnavigation.org/docs/en/getting-started.html#installation

**Comment by wilywork** [comment]
@brentvatne not work. Give me error "undefined is not an object (evaluating 'RNGestureHandlerModule.State')".
I tried to use ( #5250 ) the solution but it did not work.

**Comment by brentvatne** [comment]
sounds like you didn't link it. sorry i can't really help you with how to link native projects, if you can't figure that out you may be better off using expo

**Comment by appletxm** [comment]
react-native-gesture-handler is already linked still get the error  cannot read property 'State' of undefined

**Comment by Epiczzor** [comment]
linking did not fix it for me, has anyone found a solution ?

**Comment by YYL1999** [comment]
> react-native-gesture-handler已经链接仍然得到错误无法读取属性'state'的undefined

me too .what should l do?

**Comment by appletxm** [comment]
I solved this problem for me just run   'react-native run-android' in the terminal , after completed, then run 'react-native start' it worked for me

**Comment by CGottschallJ** [comment]
Has anyone found a fix for this yet?

I have followed the docs by running `yarn add react-navigation`. I then ran `yarn add react-native-gesture-handler@~1.0.14`. Finally, I ran `react-native link react-native-gesture-handler` but I am still receiving the error. Cannot read property "State" of undefined.

![image](https://user-images.githubusercontent.com/27632563/54501067-5b759580-48f9-11e9-9c08-19f4807497b8.png)

**Comment by lamtan92** [comment]
@CGottschallJ 
Did you try to run `pod install` after link `react-native link react-native-gesture-handler`?
This solution work for me, please try :)

**Comment by CGottschallJ** [comment]
Hey @lamtan,

Thanks for getting back to me.  I forgot to come back here and mention that a clean build (Shift + Cmd + K) in Xcode did the trick for me.  I guess it just needed to rebuild the project files in Xcode.

**Comment by BenjErgizerBunny** [comment]
My problem for iOS was also solved once I ran pod install.  This should be included in the React-Navigation documentation as it seems many people have the same issue.  The pod was not installed previously.
