### ISSUE TITLE
FlatList requires RefreshControl prop to be provided when it should have a default

### ISSUE THREAD

**Issue by nonotest** [react-navigation/react-navigation#5241]
### Current Behavior

-  When trying to pull to refresh with a `FlatList` from `react-navigation` (v3) nothing happens

### Expected Behavior

- What do you expect should be happening?

Should be able to pull to refresh

### How to reproduce

Here is a basic snack:
https://snack.expo.io/HyZeZ8TpX

**Comment by eriveltonelias** [comment]
Hi @nonotest 

isn't related with react-navigation, you need add RefreshControl component on your FlatList:

```javascript
<FlatList
  data={data}
  renderItem={this.renderItem}
  refreshControl={
    <RefreshControl
      refreshing={this.state.refreshing}
      onRefresh={this.onRefresh}
    />
}
```
you can find it on react-native docs: https://facebook.github.io/react-native/docs/refreshcontrol

**Comment by nonotest** [comment]
Hi thanks,

Manually adding the refreshcontrol does make it work however setting
onRefresh should suffice. (From the doc: if provided a standard refresh
control will be added ...)

This doesnt seem to work using react-navigation flatlist - maybe worth
documenting as people would except the same api?

Appologies if I missed something.

**Comment by brentvatne** [comment]
@eriveltonelias - I think it should work the same as the react-native flatlist with the exception of adding scroll to top behavior, so this seems like it might be a bug

**Comment by brentvatne** [comment]
if anyone wants to puzzle together a solution, the code is pretty minimal for this, it's all right here: https://github.com/react-navigation/react-navigation-native/blob/master/src/Scrollables.js

**Comment by eriveltonelias** [comment]
@brentvatne gotcha. :)

**Comment by brentvatne** [comment]
another thing to try - does it work without refreshControl if you import ScrollView from react-native-gesture-handler? maybe the bug rests there

**Comment by eriveltonelias** [comment]
@brentvatne I tried to use `ScrollView` and `FlatList` from `react-native-gesture-handler`

and looks like a bug related with `react-native-gesture-handler` here the snack: https://snack.expo.io/@eriveltonelias/flatlist-bug-with-react-navigation-3

and it is related with https://github.com/kmagiera/react-native-gesture-handler/issues/158 and https://github.com/kmagiera/react-native-gesture-handler/issues/285

**Comment by nonotest** [comment]
just a quick note;
manually adding a `RefreshControl` leads to weird behaviours (sometimes the activity indicator gets stuck at the top)
or the app crashes with
```
TypeError TypeError: TypeError: this._scrollRef.scrollTo is not a function. (In 'this._scrollRef.scrollTo(s?{x:v,animated:p}:{y:v,animated:p})', 'this._scrollRef.scrollTo' is undefined)
```

**Comment by brentvatne** [comment]
@nonotest - that is fixed in the latest version now.

I'll look into why we need to add a refresh control manually

**Comment by jermaine** [comment]
> I'll look into why we need to add a refresh control manually

@brentvatne Just bumped in to this issue as well. Did you happen to find a way without having to add the refreshControl manually?

I'm not sure, but it looks like the scroll component defined in react-navigation-native...
https://github.com/react-navigation/react-navigation-native/blob/master/src/Scrollables.js#L12

...is overriding the (default) scroll component from react-native?
https://github.com/facebook/react-native/blob/master/Libraries/Lists/VirtualizedList.js#L1031

**Comment by felixus95** [comment]
Ran into this problem to :)

**Comment by eriveltonelias** [comment]
this issue was fixed on the last version of react-navigation ( 3.9.1 )

here's the snack https://snack.expo.io/@eriveltonelias/flatlist-bug-with-react-navigation-3

thanks @brentvatne
