### ISSUE TITLE
NavigationAwareScrollable does not proxy some of ScrollView methods

### ISSUE THREAD

**Issue by ikhilko** [react-navigation/react-navigation#5243]
### Current Behavior

react-navigation provides FlatList/SectionList/ScrollView with navigation aware behavior. To be able this working you are replacing underlying scroll component with wrapped into ```createNavigationAwareScrollable``` component. But looks like this broke some functionality, because VirtualizedList (used inside scrollable components provided by RN) are relying on calling some methods of scrollable via ref. Looks like wrapped into ```createNavigationAwareScrollable``` component doesn't proxy needed methods.

This actually broke some api's of underlying RN VirtualizedList: ```scrollToEnd```, ```scrollToIndex```, ```scrollToOffset```, ```flashScrollIndicators```,  ```getScrollResponder``` , ```getScrollableNode``` ,  ```setNativeProps```

### Expected Behavior

FlatList/SectionList provided by react-navigation should provide all underlying functionality of RN scrollable's.

### How to reproduce

I've prepared a demo:
https://snack.expo.io/@ikhilko/broken-api-of-scrollables

When you click on card in FlatList, I'm calling ```this.listRef.current.scrollToOffset``` method and it's broken

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.0.0-rc.5
| expo     | 31.0.4
| node             | v9.11.2
| npm or yarn      | yarn

If you want I can create a PR, but maybe it's need to be discussed a bit here

**Comment by ikhilko** [comment]
Just republished issue from https://github.com/react-navigation/react-navigation-native/issues/5

**Comment by brentvatne** [comment]
you can call `getNode()` on it to get the underlying ref and then call any method you want, this is the same as how Animated works.

**Comment by brentvatne** [comment]
thanks for the example -- i was able to fix this, it's live now in @react-navigation/native@3.0.2. if you remove your yarn.lock (or package-lock) and install the latest react-navigation version you should get this due to ^ matcher: https://github.com/react-navigation/react-navigation/blob/03be0324a34ce4ffa790919326e220a86266a65f/package.json#L38

**Comment by ikhilko** [comment]
Hi! I've tested it, and looks like it's still not work :) As I can see it's due to wrapping Scrolling HOC in [another one HOC](https://github.com/react-navigation/react-navigation-native/blob/master/src/createNavigationAwareScrollable.js#L90)

**Comment by brentvatne** [comment]
good point, can you submit a PR to fix that now that you've seen my attempt to fix it last week?

**Comment by brentvatne** [comment]
an easy fix would be to just in-line the withNavigation logic into the scrolling HOC

**Comment by ikhilko** [comment]
Yes, I can try to fix it :) Thanks!

**Comment by ikhilko** [comment]
I fixed it other way (reusing withNavigation HOC from core) wrapping it into another one HOC.. Not sure it's a good idea but it works. https://github.com/react-navigation/react-navigation-native/pull/8
