### ISSUE TITLE
Navigation crashed on latest version 3.0

### ISSUE THREAD

**Issue by dukemai** [react-navigation/react-navigation#5244]
I got the navigation crashed on the sample code from the offical site. The error was: `TypeError: undefined is not an object(evaluating 'this._callListeners.bind')`

<img width="290" alt="skarmavbild 2018-11-18 kl 13 22 18" src="https://user-images.githubusercontent.com/11334099/48672393-a17e4080-eb35-11e8-95bb-c71a02fb2553.png">

**Comment by eriveltonelias** [comment]
Hi @dukemai, 

Can you share a url from the docs that found the problem?

**Comment by cgdstnc** [comment]
@dukemai 
to reproduce issue, create a fresh rn project and go through getting started and hello react navigation pages.

**Comment by eriveltonelias** [comment]
I tried as you mentioned @cgdstnc but works fine https://snack.expo.io/@eriveltonelias/hello-react-navigation

**Comment by dukemai** [comment]
I created project with react-native init. I did not use expo. I followed this link https://reactnavigation.org/docs/en/hello-react-navigation.html

**Comment by eriveltonelias** [comment]
did you follow the installation instructions ? https://reactnavigation.org/blog/#installation

because react navigation 3.0 depends `react-native-gesture-handler`. 

`yarn add react-native-gesture-handler && react-native link`

**Comment by dukemai** [comment]
yes, I did according the guidance in the link.

**Comment by dukemai** [comment]
here are my dependencies
`
 "dependencies": {
    "react": "16.6.1",
    "react-native": "0.57.5",
    "react-native-gesture-handler": "^1.0.9",
    "react-native-ui-lib": "^3.4.0",
    "react-navigation": "3.0.0-rc.5",
    "react-navigation-tabs": "^1.0.0"
  },
`

**Comment by eriveltonelias** [comment]
@dukemai the last one is `3.0.0` can you update it and remove all cache ?

**Comment by dukemai** [comment]
actually it was `^3.0.0` in the beginning but it did not work so I changed to rc.5 as in the sample code. I also deleted node_modules several times. I can try once again with your suggestion.

**Comment by anilkumar1505** [comment]
@eriveltonelias  How i can resolve this issue. Can you help regarding on that.

**Comment by anilkumar1505** [comment]
@eriveltonelias  Error is " Native module can not be null"

**Comment by dukemai** [comment]
@ericvicenti I tried again: installed react-navigation with versions ^3.0.0 and link again, but it did not help. I got the same error :(.

**Comment by anilkumar1505** [comment]
@eriveltonelias  and @dukemai  Same  error  " Native module can not be null"

**Comment by benadamstyles** [comment]
I was having this error yesterday, but then I ran a new build of the native app using `react-native run-ios`, and it went away. Have you tried that?

**Comment by anilkumar1505** [comment]
@benadamstyles  yes.. but not hope

**Comment by dukemai** [comment]
@benadamstyles it did not help since I tried many times.
@anilkumar1505 I am not sure if I have the same problem as you. it seems that you have something to do with native modules instead.
@ericvicenti and all: Update on this issue, I got it to work when downgrade react-native version from 0.57.4  to  "react-native": "0.56.0" and changed my .babelrc from `{
    "presets": ["module:metro-react-native-babel-preset"],
    "plugins": [
        "@babel/plugin-proposal-class-properties"
      ]
  }
` to `presets": ["react-native"]`

So my guess is that something is wrong with the latest react-native

**Comment by eriveltonelias** [comment]
sure, thanks @dukemai for you report!

**Comment by fardeen-panjwani** [comment]
> did you follow the installation instructions ? https://reactnavigation.org/blog/#installation
> 
> because react navigation 3.0 depends `react-native-gesture-handler`.
> 
> `yarn add react-native-gesture-handler && react-native link`

I installed `react-native-gesture-handler`. I also added `import com.poc_rn_2.RNGestureHandlerEnabledRootView;` to MainApplication.java. But its showing me that `cannot resolve symbole RNGestureHandlerPackage`

`package com.poc_rn_2;

import android.app.Application;

import com.facebook.react.ReactApplication;
import io.invertase.firebase.RNFirebasePackage;
import io.invertase.firebase.RNFirebasePackage;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;
import com.facebook.soloader.SoLoader;
import com.poc_rn_2.RNGestureHandlerPackage;

import java.util.Arrays;
import java.util.List;

public class MainApplication extends Application implements ReactApplication {

  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
    @Override
    public boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
          new RNFirebasePackage(),
          new RNGestureHandlerPackage()
      );
    }

    @Override
    protected String getJSMainModuleName() {
      return "index";
    }
  };

  @Override
  public ReactNativeHost getReactNativeHost() {
    return mReactNativeHost;
  }

  @Override
  public void onCreate() {
    super.onCreate();
    SoLoader.init(this, /* native exopackage */ false);
  }
}
`

package.json: 
`
    "react-native-gesture-handler": "^1.0.9",
    "react-navigation": "^3.0.0"
`

**Comment by beng970804** [comment]
So anyone have the solution for this? Im having the same problem also

**Comment by brentvatne** [comment]
create a new issue and follow the issue template if you believe you have found a bug, thanks!
