### ISSUE TITLE
'Require cycles are allowed, but can result in uninitialized values' warning after v3 update. 

### ISSUE THREAD

**Issue by panda0603** [react-navigation/react-navigation#5246]
### Current Behavior

I've just updated to v3 and followed the docs to wrap stackNavigator with createAppContainer. 
I've managed it to work, but i'm getting this require cycles warning which I didn't have in v2. 
Didn't change any other code, just the update of react navigation and createAppContainer. 

complete warning is:
'Require cycle: node_modules/react-native-gesture-hander/index.js -> node_modules/react-native-gesture-handler/DrawerLayout.js-> node_modules/react-native-gesture-handler/index.js

I'm also using tab and drawer. Following is the code: 

//in stackNavigator.js
```
const AppNavigator = createStackNavigator(
  {
      .....
  });

const AppContainer = createAppContainer(AppNavigator);
export default AppContainer;
```

I have separate file for drawer and tab. 
//in drawerTab.js
```
import { createDrawerNavigator, createBottomTabNavigator} from "react-navigation";
import AppContainer from "./stackNavigator.js";

const Tabs = createBottomTabNavigator({
  Home: {
    screen: AppContainer, //put stacknavigator here
    navigationOptions: {
      title: "Main",
      ...
    }
  },
  //More tabs...
});
const tabContainer = createAppContainer(Tabs);

const DrawerNavigator = createDrawerNavigator(
  {
    Home: { screen: tabContainer } //put tabs here
  },
  {
    contentComponent: SidebarScreen
  }
);

export default createAppContainer(DrawerNavigator); //this is the entry point in app.js
```
P.S. is this the right way of using the createAppContainer, for every stack, tab and drawer? or do I have to just use the createAppContainer onto the entry point component which is the drawerNavigator?

### Expected Behavior

I shouldn't be getting the required cycles warning. 

### How to reproduce

Not sure if the code above is the problem, or v3 itself is the problem. All i have changed is the version and createAppContainer. Using Expo at the moment, might this be problem?

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.0.0
| react-native     | 0.57
| node             | 8.11.3
| npm or yarn      |6.4.1

**Comment by eriveltonelias** [comment]
Hi @panda0603, 

this issue is related with `react-native-gesture-handler` this PR will fix it https://github.com/kmagiera/react-native-gesture-handler/pull/340

**Comment by echokk11** [comment]
so in our project, just do 
```
npm install react-native-gesture-handler
```
upgrade the latest version ?

**Comment by baryla** [comment]
I'm quite new to RN so I'm not sure if I'm doing things correctly however, I still seem to get this warning. I am running the latest versions of `react-native`, `react-navigation`, `react-native-gesture-handler`, `node` so I'm unsure what else I can do here?
Here's the warning:
```
Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
- node_modules/expo/build/environment/logging.js:25:23 in warn
- node_modules/metro/src/lib/polyfills/require.js:109:19 in metroRequire
- node_modules/react-native-gesture-handler/Swipeable.js:11:0 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:292:12 in loadModuleImplementation
- node_modules/react-native-gesture-handler/index.js:1:0 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:292:12 in loadModuleImplementation
- node_modules/react-navigation-stack/src/views/StackView/StackViewLayout.js:19:0 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:292:12 in loadModuleImplementation
- node_modules/react-navigation-stack/src/views/StackView/StackView.js:4:0 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:292:12 in loadModuleImplementation
- node_modules/react-navigation-stack/src/navigators/createStackNavigator.js:3:0 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:292:12 in loadModuleImplementation
- node_modules/react-navigation-stack/src/index.js:9:18 in createStackNavigator
- node_modules/react-navigation/src/react-navigation.js:107:45 in createStackNavigator
* stacks/HomeStack.js:7:18 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:292:12 in loadModuleImplementation
* navigation/MainTabNavigator.js:3:0 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:292:12 in loadModuleImplementation
* navigation/AppNavigator.js:3:0 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:292:12 in loadModuleImplementation
* App.js:4:0 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:292:12 in loadModuleImplementation
- node_modules/expo/AppEntry.js:2:0 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:292:12 in loadModuleImplementation
- node_modules/metro/src/lib/polyfills/require.js:179:45 in guardedLoadModule
* null:null in global code
```

Any ideas?

**Comment by baryla** [comment]
I have found that the warning for me was caused by having `react-native` from the Expo's SDK archive. Literally all I did was:
```$ npm uninstall react-native```
```$ npm install react-native --save```

**Comment by Djotchuang** [comment]
None of these worked for me. Could anyone propose a solution please?

**Comment by raajnadar** [comment]
@Djotchuang upgrade to v5 or v6 if you are still using v3
