### ISSUE TITLE
Navigate from within constructor not working as expected

### ISSUE THREAD

**Issue by isaaclem** [react-navigation/react-navigation#5247]
Below is the configuration for my navigation:

```
const MainNavigator = createStackNavigator({
  auth: { 
    screen: createStackNavigator({
      auth: {
        screen: LoginScreen,
        navigationOptions: {
          header: null,
        }
      }
    })
  },
  main: {
    screen: createBottomTabNavigator({
      calendar: {
        screen: createStackNavigator({
          calendar: {
            screen: CalendarScreen,
            navigationOptions: {
              ...STANDARD_NAVIGATION_OPTION,
              title: strings.labelCalendar
            }
          }
        }, {
          headerMode: 'screen'
        }),
        navigationOptions: () => ({
          tabBarLabel: strings.labelCalendar,
          tabBarIcon: ({ tintColor }) => <Icon type='MaterialCommunityIcons' name='calendar-text' style={{ color: tintColor, fontSize: 25 }} />,
        })
      }
    }, {
      tabBarPosition: 'bottom',
      tabBarOptions: {
        labelStyle: { fontSize: 12 },
        activeTintColor: '#fa5d66',
        pressColor: 'red',
      }
    })
  }
}, {
  initialRouteName: 'auth',
  defaultNavigationOptions: {
    header: null
  },
  lazy: false
});

const App = createAppContainer(MainNavigator);

export default App;
```

And below is my `loginScreen.js`

```
class LoginScreen extends Component {
  constructor(props) {
    super(props);
    if (this.props.isVerified) {
      props.navigation.navigate('calendar');
    } else if (!this.props.isVerified) {
      this.props.general_resetState();
    }

    this.state = { 
      showLoginModal: false,
      showErrorModal: false 
    };
  }
}
```

As shown above, upon loading LoginScreen, it will check value of `isVerified` from redux store and navigate to `CalendarScreen.js`. It used to work in v2 but now I'm hitting warning below and the app freeze in `LoginScreen.js`

### Exception
```
Possible Unhandled Promise Rejection (id: 0):
TypeError: Cannot read property 'index' of null
TypeError: Cannot read property 'index' of null
    at Object.KeyboardAwareNavigator._this._handleTransitionStart [as onTransitionStart] (blob:http://localhost:8081/bb9e0fa8-1275-48b6-bd38-049f0cc3b8d9:121069:61)
    at Transitioner._callee3$ (blob:http://localhost:8081/bb9e0fa8-1275-48b6-bd38-049f0cc3b8d9:128508:40)
    at tryCatch (blob:http://localhost:8081/bb9e0fa8-1275-48b6-bd38-049f0cc3b8d9:28068:19)
    at Generator.invoke [as _invoke] (blob:http://localhost:8081/bb9e0fa8-1275-48b6-bd38-049f0cc3b8d9:28241:24)
    at Generator.prototype.(anonymous function) [as next] (blob:http://localhost:8081/bb9e0fa8-1275-48b6-bd38-049f0cc3b8d9:28111:23)
    at tryCatch (blob:http://localhost:8081/bb9e0fa8-1275-48b6-bd38-049f0cc3b8d9:28068:19)
    at invoke (blob:http://localhost:8081/bb9e0fa8-1275-48b6-bd38-049f0cc3b8d9:28144:22)
    at blob:http://localhost:8081/bb9e0fa8-1275-48b6-bd38-049f0cc3b8d9:28172:13
    at tryCallTwo (blob:http://localhost:8081/bb9e0fa8-1275-48b6-bd38-049f0cc3b8d9:3743:7)
    at doResolve (blob:http://localhost:8081/bb9e0fa8-1275-48b6-bd38-049f0cc3b8d9:3907:15)
```
### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^3.0.0
| react-native     | 0.56.0
| node             | v11
| yarn      | 1.10.1

**Comment by eriveltonelias** [comment]
Hi @isaaclem, 

Can you create a runnable example on https://snack.expo.io ?

**Comment by isaaclem** [comment]
Hi @ericvicenti , I've created a runnable example @ https://snack.expo.io/ByyK0mxA7

Basically in react navigation v2, the example should load Screen 2 component. But now instead, it is loading screen 1 component, and if we wished to load to screen 2, change `defaultNavigationOptions` to v2 `navigationOptions` instead, you will see the example will be showing `screen 2`, however, header will not be null, anyway I think `defaultNavigationOptions` should be the right option
```
 {
  initialRouteName: 'auth',
  navigationOptions: {
    header: null
  },
  lazy: false
}
```

**Comment by eriveltonelias** [comment]
hi @isaaclem, 

tell me if is that what you're looking for https://snack.expo.io/@eriveltonelias/transition-config

**Comment by reactionic127** [comment]
I am getting same issue

**Comment by brentvatne** [comment]
I don't understand what you're trying to get at here @isaaclem - the title of the post for example is extremely broad and says very little about what you're encountering. @reactionic127 - you need to provide info if you want to weigh in here, so I hid your comment as it's essentially spam.

@isaaclem - I believe the issue you're trying to articulate is that when you navigate to another screen inside of a constructor then it doesn't work as you would expect. In this case, you start on Screen1 and in the constructor for Screen1 you navigate to Screen2, but you don't see Screen2 when the app loads. Is this a correct understanding? As for 'freezing', I don't know how to repro this in your example.

**Comment by brentvatne** [comment]
I looked into this some more and there is indeed a bug when you navigate in the first tick that the app is loaded. This seems like a bit of a strange use case but we should fix it anyways.

**Comment by brentvatne** [comment]
the problem seems to be that in the Transitioner the animation is interrupted immediately so it never reaches its destination state, and in addition to that onTransitionEnd is called before onTransitionStart because of this

**Comment by isaaclem** [comment]
>  In this case, you start on Screen1 and in the constructor for Screen1 you navigate to Screen2, but you don't see Screen2 when the app loads. Is this a correct understanding? 

Yes

> As for 'freezing', I don't know how to repro this in your example.

From the snack: https://snack.expo.io/Sy1kQEGCQ , it was showing Screen1 with the button on it, but it's not clickable and have the feeling of "freeze"

**Comment by brentvatne** [comment]
thanks @isaaclem. I have a tentative fix ready but will play with it more tomorrow. another thing I noticed is that enabling react-native-screens fixes this

**Comment by isaaclem** [comment]
No problem @brentvatne take your time. Many thanks for the constant support in producing this beautiful package that benefits a ton of us!

**Comment by brentvatne** [comment]
fixed in the latest release, thanks
