### ISSUE TITLE
Native module can not be null" Error getting after install "react-navigation": "^3.0.0

### ISSUE THREAD

**Issue by anilkumar1505** [react-navigation/react-navigation#5249]
### Current Behavior

- What do you expect should be happening?
-I installed RN version 3.0.0 then i got the error for " native module can not be null.
![simulator screen shot - iphone 6 - 2018-11-19 at 17 11 33](https://user-images.githubusercontent.com/33411228/48705142-6ad02500-ec1e-11e8-88a7-28b30edc79e6.png)

- Include a screenshot if it makes sense.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |3.0.0
| react-native     |0.57.2
| node             |
| npm or yarn      |

**Comment by anilkumar1505** [comment]
Please help me regarding on that.

**Comment by eriveltonelias** [comment]
Hi @anilkumar1505 

see my comment https://github.com/react-navigation/react-navigation/issues/5244#issuecomment-439730726

**Comment by anilkumar1505** [comment]
@eriveltonelias i followed the same instructions but i could not added react-native-gesture-handler && react-native so it is mandatory to add this package manager. i have different app architecture so i cant not linking.

**Comment by anilkumar1505** [comment]
@eriveltonelias I install react-native-gesture-handler and link by pod in native iOS project pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler/ios'    so it is right way to link?

**Comment by anilkumar1505** [comment]
This is happening after install "react navigation version 3.0.0"

**Comment by anilkumar1505** [comment]
@eriveltonelias  Please provide the solution this is happening after react navigation installation.

**Comment by anilkumar1505** [comment]
@eriveltonelias It is working Problem was RCTLinking need to install

**Comment by eriveltonelias** [comment]
> @eriveltonelias i followed the same instructions but i could not added react-native-gesture-handler && react-native so it is mandatory to add this package manager. i have different app architecture so i cant not linking.

hi @anilkumar1505, can you explain why you could not install and link `react-native-gesture-handler` on your project ? 

because react-navigation v3 need this module.

**Comment by anilkumar1505** [comment]
@eriveltonelias I already installed it and tried but I have hybrid code like objective C/Swift/ and React native. so only problem is i missing " RCTLinkingIOS" in React pod spec like   # Your 'node_modules' directory is probably in the root of your project,
  # but if not, adjust the `:path` accordingly
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # needed for debugging
    'RCTImage',
    **'RCTLinkingIOS'**
  ]

so our linked " react-native-gesture-handler" on my project not linking. so error was prompted.

**Comment by anilkumar1505** [comment]
@eriveltonelias  close the issue.

**Comment by eriveltonelias** [comment]
Cool! Thanks for you report @anilkumar1505!
