### ISSUE TITLE
undefined is not an object (evaluating 'RNGestureHandlerModule.State' in "react-navigation": "^3.0.0"

### ISSUE THREAD

**Issue by depressedlixiaobo** [react-navigation/react-navigation#5250]
When I use  react-native 0.57.3 or high (my system : OSX 10.13.4,node:10.3.0)

replace default App.js content:

`import React from "react";
import { View, Text } from "react-native";
import { createStackNavigator, createAppContainer } from "react-navigation";

class HomeScreen extends React.Component {
  render() {
    return (
      <View style={{ flex: 1, alignItems: "center", justifyContent: "center" }}>
        <Text>Home Screen</Text>
      </View>
    );
  }
}

const AppNavigator = createStackNavigator({
  Home: {
    screen: HomeScreen
  }
});
const AppContainer = createAppContainer(AppNavigator);

export default class App extends React.Component {
  render() {
    return <AppContainer />;
  }
} 
`

I get an error : **undefined is not an object (evaluating RNGestureHandlerModule.State')**

How  I can solve it?

**Comment by eriveltonelias** [comment]
Hi @depressedlixiaobo, 

see my comment https://github.com/react-navigation/react-navigation/issues/5244#issuecomment-439730726

**Comment by macaetano** [comment]
Hi @eriveltonelias, 
the docs uses createAppContainer, that is not present on the react-navigation.

I'm using @types/react-navigation, btw.

**Comment by macaetano** [comment]
These two:
@types/react-navigation: ^2.13.4,
react-navigation: 3.0.0.

**Comment by nihp** [comment]
@macaetano Install react-navigation-gesture-handle. Read the installation guide

https://reactnavigation.org/blog/#installation

**Comment by AmirhosseinBayat** [comment]
I have this issue and solved by:
- npm install
- npm install --save react-navigation
- npm install --save react-native-gesture-handler
- react-native link
[using this](https://stackoverflow.com/questions/52861437/undefined-is-not-an-object-evaluating-rngesturehandlermodule-state)
