### ISSUE TITLE
Drawer does not respond to touch (v3)

### ISSUE THREAD

**Issue by SergeyMyssak** [react-navigation/react-navigation#5251]
### Current Behavior
Drawer does not respond to touch.

**App.js**
```
import * as React from 'react';
import { View, Button, Image, StyleSheet, Text } from 'react-native';
import { createDrawerNavigator, createAppContainer, createBottomTabNavigator } from 'react-navigation';

class TabOne extends React.Component {
  render() {
    return (
      <View>
        <Button
          onPress={() => this.props.navigation.openDrawer()}
          title="Open Drawer"
        />
      </View>
    );
  }
}
class MyHomeScreen extends React.Component {
  static navigationOptions = {
    drawerLabel: 'Home',
  };

  render() {
    return (
      <View style={{ flex: 1, justifyContent: 'center' }}>
        <Button
          onPress={() => this.props.navigation.navigate('Notifications')}
          title="Go to notifications"
        />

        <Button
          onPress={() => this.props.navigation.openDrawer()}
          title="Open Drawer"
        />

      </View>
    );
  }
}

class MyNotificationsScreen extends React.Component {
  static navigationOptions = {
    drawerLabel: 'Notifications',
  };

  render() {
    return (
      <View style={{ flex: 1, justifyContent: 'center' }}>
        <Button
          onPress={() => this.props.navigation.goBack()}
          title="Go back home"
        />
      </View>
    );
  }
}


const BottomNavigator = createBottomTabNavigator(
  {
    HomeTab: TabOne,
    SettingsTab: TabOne,
    DetailsTab: TabOne,
  }
);


const MyApp = createDrawerNavigator({
  BottomNavigator: {
    screen: BottomNavigator,
  },
  Home: {
    screen: MyHomeScreen,
  },
  Notifications: {
    screen: MyNotificationsScreen,
  },
}, {
    navigationOptions: {
      drawerLockMode: 'locked-closed'
    }
  });


export default createAppContainer(MyApp);
```
**package.json**
```
{
  "name": "Drawer",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.6.1",
    "react-native": "0.57.5",
    "react-native-gesture-handler": "^1.0.9",
    "react-navigation": "^3.0.0"
  },
  "devDependencies": {
    "babel-jest": "23.6.0",
    "jest": "23.6.0",
    "metro-react-native-babel-preset": "0.49.2",
    "react-test-renderer": "16.6.1"
  },
  "jest": {
    "preset": "react-native"
  }
}
```
![](https://s8.hostingkartinok.com/uploads/images/2018/11/b0224d2f84647d441722d232fbcd79cf.gif)

### Expected Behavior

He must react to touch. In the project created by Expo everything works, and in the project created by react-native init does not work.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.0.0
| react-native     | 0.57.5
| node             | 10.4.1
| npm or yarn      | npm and yarn

**Comment by tmmgn** [comment]
Have same issue with gesture and also drawer not closing on tap drawer overlay

**Comment by vonovak** [comment]
hi, thanks for reporting. We require a runnable repro of the issue so we can tackle it, can you please add it?
Can you please confirm that you have installed and linked `react-native-gesture-handler`?

**Comment by SergeyMyssak** [comment]
> hi, thanks for reporting. We require a runnable repro of the issue so we can tackle it, can you please add it?
> Can you please confirm that you have installed and linked `react-native-gesture-handler`?

1) My repo: https://github.com/SergeyMyssak/Drawer
2) Yes, of course, I have installed and linked `react-native-gesture-handler`!

**Comment by billel-boudchicha** [comment]
have same issue here
`react-native-gesture-handler` installed and linked

**Comment by kyungjoongo** [comment]
Same problem.
Did this remove functionality? I wonder if it is a bug.

**Comment by NoRamadon** [comment]
I think this solution will help

https://stackoverflow.com/questions/53394982/react-navigation-swipe-on-drawer-does-not-work-in-android

**Comment by SergeyMyssak** [comment]
> I think this solution will help
> 
> https://stackoverflow.com/questions/53394982/react-navigation-swipe-on-drawer-does-not-work-in-android

The solution works, but I have one problem. When I click on the gray space around it, it closes! (it's OK) But I can't close it with the movement of a finger to the left.

[Gif with the problem](https://s8.hostingkartinok.com/uploads/images/2018/11/f60e1b2b1c9b15c650f90d20584f8714.gif)

**Comment by NoRamadon** [comment]
> > I think this solution will help
> > https://stackoverflow.com/questions/53394982/react-navigation-swipe-on-drawer-does-not-work-in-android
> 
> The solution works, but I have one problem. When I click on the gray space around it, it closes! (it's OK) But I can't close it with the movement of a finger to the left.
> 
> [Gif with the problem](https://s8.hostingkartinok.com/uploads/images/2018/11/f60e1b2b1c9b15c650f90d20584f8714.gif)

It is default attribute for drawer if u want modify it u can use 'drawerLockMode'.

**Comment by SergeyMyssak** [comment]
> > > I think this solution will help
> > > https://stackoverflow.com/questions/53394982/react-navigation-swipe-on-drawer-does-not-work-in-android
> > 
> > 
> > The solution works, but I have one problem. When I click on the gray space around it, it closes! (it's OK) But I can't close it with the movement of a finger to the left.
> > [Gif with the problem](https://s8.hostingkartinok.com/uploads/images/2018/11/f60e1b2b1c9b15c650f90d20584f8714.gif)
> 
> It is default attribute for drawer if u want modify it u can use 'drawerLockMode'.

You misunderstood my problem. The driver doesn't close swipe to the left. I can use drawerLockMode when I need disable or enable the drawer on any screen. This doesn't solve my problem.

**Comment by divisumma** [comment]
> I can confirm @NoRamadon 's [comment](https://github.com/react-navigation/react-navigation/issues/5251#issuecomment-440598781) resolved this issue for us.

I don't know if it's only my case, but even if this fixes completely the gesture issue, now opening/closing the drawer with a swipe is not as fluid as in RN2. The animation is sluggish and stutters every now and then.

**Comment by auzwang** [comment]
Perhaps close this issue and those who are experiencing a sluggish animation -- open a new issue.

**Comment by SergeyMyssak** [comment]
> Perhaps close this issue and those who are experiencing a sluggish animation -- open a new issue.

My problem doesn't solve. The drawer doesn't close swipe to the left.

**Comment by brentvatne** [comment]
@SergeyMyssak - you need to make sure you're using the latest version of react-native-gesture-handler. if you are and still having the issue, please create a new issue with a runnable example
