### ISSUE TITLE
AppContainer ref always equals null

### ISSUE THREAD

**Issue by Kison** [react-navigation/react-navigation#5252]
### Current Behavior
AppContainer ref does not return navigation instance

### Expected Behavior
I guess it should return navigation instance as in current example
https://reactnavigation.org/docs/en/navigating-without-navigation-prop.html

### How to reproduce
I am using such structure for navigation
```
const AppNavigator = createStackNavigator(
  {
    LoginStack: { screen: LoginStack },
    DrawerStack: { screen: DrawerNavigation }
  },
  {
    headerMode: 'none',
    initialRouteName: 'DrawerStack'
  }
);


const AppContainer = createAppContainer(AppNavigator);
class Navigator extends React.Component {
  render() {
    return <AppContainer ref={ref => {
      // Here ref will be always null
      NavigationService.setTopLevelNavigator(ref);
    }}/>;
  }
}

const mapStateToProps = (state) => {
  return {
    login: state.root.login,
    username: state.root.username
  }
};

export default connect(mapStateToProps)(Navigator);
```

### Your Environment
OS: Windows 10
react-navigation:  v3.0.0
react-native: Expo SDK 31.0.1
node:  v8.11.1
npm: 6.4.1

**Comment by vonovak** [comment]
hi! Thanks for reporting. There is a small issue in your snippet, you're asking for the ref of `Navigator`, but you should be asking for the ref of `AppNavigator`. That'll do the trick.
