### ISSUE TITLE
Documentation website is down

### ISSUE THREAD

**Issue by swese44** [react-navigation/react-navigation#5254]
https://reactnavigation.org/

**Comment by heyman333** [comment]
same👍

**Comment by anoopmm** [comment]
same :(

**Comment by conghai** [comment]
opo! down down... go away... come again another day!

**Comment by cjhowe7** [comment]
It's a DNS issue. The records don't seem to be propagating at all. I've proxied to California and tested from DC and the issue occurs in both locations. See https://www.whatsmydns.net/#A/reactnavigation.org

```
$ nslookup reactnavigation.org 8.8.8.8
Server:        8.8.8.8
Address:    8.8.8.8#53

** server can't find reactnavigation.org: NXDOMAIN
```

**Comment by juanorellana13** [comment]
Looks like the site is still down. Trying to read docs to find out how to implement a stack navigator on version 3.

**Comment by socceroos** [comment]
As a workaround while the site is down, you can set up the documentation on your local computer very quickly here: https://github.com/react-navigation/react-navigation.github.io

**Comment by brentvatne** [comment]
I'm not sure what's going on right now, there appear to be some issues with the domain but I am not the owner of it. We need @ericvicenti to look into this. I'm away in Thailand at the moment. You can access the docs for now by running them locally, see the instructions in the README: https://github.com/react-navigation/react-navigation.github.io

**Comment by AshishKapoor** [comment]
Works if you switch DNS to cloudflare's 1.1.1.1

**Comment by ericvicenti** [comment]
Sorry about the website interruption, folks! I renewed the domain and it should be back shortly

**Comment by cjhowe7** [comment]
> Works if you switch DNS to cloudflare's 1.1.1.1

BTW, I did test this and it didn't work at the time.

Thank you @ericvicenti!

**Comment by eriveltonelias** [comment]
is online again! Can someone test that too ?

**Comment by eriveltonelias** [comment]
yeah, fixed! Thanks @ericvicenti !

**Comment by james2m** [comment]
Down again.
