### ISSUE TITLE
Cannot read property 'shadowOpacity' of undefined

### ISSUE THREAD

**Issue by loug38** [react-navigation/react-navigation#5255]
### Current Behavior
![alt-text](https://i.imgur.com/PXkdRws.png)
### Expected Behavior

The Transition from Screen1 should fade into Screen2, but Screen 2 to Screen 3 should have a regular transition.

### How to reproduce

Transition based on fade solution found here:
https://github.com/react-navigation/react-navigation/issues/2493#issuecomment-325934240

I set up the fade animation, and choose to only use it if the route being currently taken is to Screen 2.
```JavaScript
export const Stack = createStackNavigator({
  Screen1: { screen: ScreenOne },
  Screen2: { screen: ScreenTwo },
  Screen3: { screen: ScreenThree }
}, {
  initialRouteName: 'Screen1',
  transitionConfig: () => ({
    screenInterpolator: (props) => { 
      if (props.scene.route.routeName === "Screen2") return fade(props) 
    }
  })
},
);
```
The line that throws the error is:
```JavaScript 
if (props.scene.route.routeName === "Screen2")
``` 
I need the check because without it the fade animation works but now it's applied to every screen instead of just the ones I would want it to. 
Snack:
https://snack.expo.io/@loug38/graceful-mixed-nuts

I've used this solution since react-navigation beta, and it's worked fine, but it seems to have broken with 3.0.0
Here is the same project but running with react-navigation 2.17.0
https://snack.expo.io/@loug38/playful-kiwi

### My Environment
| software         | version
| ---------------- | -------
| react-navigation | ^3.0.0
| react-native     | ^0.57.4
| node             | v8.8.1
| npm      | 6.4.1

**Comment by eriveltonelias** [comment]
hi @loug38,

tell me if is that what you're looking for https://snack.expo.io/@eriveltonelias/transition-config

**Comment by eriveltonelias** [comment]
great! :)
