### ISSUE TITLE
createDrawerNavigator(v3) has problem with rtl layout!

### ISSUE THREAD

**Issue by dream46453** [react-navigation/react-navigation#5257]
hi
i found some issue #270 on this problem that they refer to the version of (react-native-drawer-layout) dependency, but in react navigation v3 i cannot find any dependency with this name nor (react-native-drawer-layout-polyfill)

now what should i do?

**Comment by eriveltonelias** [comment]
Hi @dream46453! 

that is related with https://github.com/react-navigation/react-navigation-drawer/issues/29 if not, please a new issue on https://github.com/react-navigation/react-navigation-drawer
