### ISSUE TITLE
.push() not working in v3

### ISSUE THREAD

**Issue by Rockatweb** [react-navigation/react-navigation#5258]
Hi there, im trying the new version of this dependency and as it is described in the documentation: when you use the .push() function the page should navigate to the next screen.
But in my project nothing happens after i click on a button with the code below.
The item variable is an object with fakedata. But there is no difference if the push action is with or without the params.

---

### Current Behavior

```
_onPress = (item) => {
            let pushAction = StackActions.push({
                routeName: 'Folder',
                params: {
                    'children': item.children,
                    'id': item.id
                },
            });

            this.props.navigation.dispatch(pushAction);
    };
```

### Expected Behavior

- the app should navigate to the next screen, as it is described in the documentation (https://reactnavigation.org/docs/en/stack-actions.html#push)

### How to reproduce

- snack doesn't work with the new v3 version. should i upload it to github?

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.0.0
| react-native     | 0.57.4
| node             | v11.2.0
| npm or yarn      | npm

**Comment by eriveltonelias** [comment]
Hi @Rockatweb 

I created an example in v3 using `push` and `pop`with `StackActions` and works as expected  https://snack.expo.io/@eriveltonelias/stack-actions
:)
