### ISSUE TITLE
drawer does not slide out when swipe from left and does not close when tap on background screen

### ISSUE THREAD

**Issue by jendev85** [react-navigation/react-navigation#5259]
### Current Behavior

Recently updated to v3.0.0 and the DrawerNavigator no longer slides out when swiped and will not close when background screen is tapped

### Expected Behavior

Before the upgrade, the Drawer would slide out when swiped left to right and would close when the screen in the background was tapped.

### How to reproduce

The current stack:
AppContainer 
 -SwitchNavigator
      -DrawerNavigator
          -StackNavigator

### Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.0.0
| react-native     | 0.57.4
| node             | 8.12.0
| npm or yarn      | 6.4.1

**Comment by eriveltonelias** [comment]
Hi @jendev85, 

Can you create a runnable example on https://snack.expo.io ?

**Comment by xanderberkein** [comment]
Same problem here, Android only.

**Comment by vadimkorr** [comment]
Hello @eriveltonelias. Drawer can't be used in expo (issue is below). When I'm using another type of Navigator, it works. But this is kind of snack issue ([(0, _reactNavigation.createDrawerNavigator) is not a function](https://github.com/react-navigation/react-navigation/issues/5232))
![image](https://user-images.githubusercontent.com/17295572/48831483-f913ea80-ed87-11e8-90d9-7946b0866be5.png)

Source code: https://snack.expo.io/@vadimkorr/drawer-navigator

**Comment by vadimkorr** [comment]
Seems this relates to https://github.com/react-navigation/react-navigation/issues/5251

**Comment by eriveltonelias** [comment]
> Hello @eriveltonelias. Drawer can't be used in expo (issue is below). When I'm using another type of Navigator, it works. But this is kind of snack issue ([(0, _reactNavigation.createDrawerNavigator) is not a function](https://github.com/react-navigation/react-navigation/issues/5232))
> ![image](https://user-images.githubusercontent.com/17295572/48831483-f913ea80-ed87-11e8-90d9-7946b0866be5.png)
> 
> Source code: https://snack.expo.io/@vadimkorr/drawer-navigator

yeah, you're right @vadimkorr.

**Comment by eriveltonelias** [comment]
> Seems this relates to #5251
> Fortunately, this solution fixes the issue: https://stackoverflow.com/a/53396072

Thanks @vadimkorr! :) can you confirm if that works for you @jendev85  ?

**Comment by brentvatne** [comment]
cc @tcdavis there appears to be a snack bug here

**Comment by brentvatne** [comment]
also @jendev85 - as @vadimkorr suggested https://stackoverflow.com/questions/53394982/react-navigation-swipe-on-drawer-does-not-work-in-android/53396072#53396072 should solve your issue. it's important to follow the instructions for adding react-native-gesture-handler to your app :)
