### ISSUE TITLE
Invariant Violation: The Navigation props is missing for this navigator. In react-navigation 3 you must set app container

### ISSUE THREAD

**Issue by anilkumar1505** [react-navigation/react-navigation#5260]
### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |3.0.0
| react-native     |0.57.5
![simulator screen shot - iphone x - 2018-11-21 at 13 05 02](https://user-images.githubusercontent.com/33411228/48825658-164bb780-ed8e-11e8-9b9f-72e29c30fae7.png)

| node             |
| npm or yarn      |

**Comment by anilkumar1505** [comment]
Please help me regarding on that.

**Comment by brentvatne** [comment]
did you read the error message and follow the link?

**Comment by anilkumar1505** [comment]
@brentvatne  yes

**Comment by brentvatne** [comment]
share reproducible example

**Comment by anilkumar1505** [comment]
@brentvatne  below is my code.  let me correct if anything wrong.

const AppNavigator = createStackNavigator(
  {
    Home: {
      screen: Home,
    },
    Setting: {
      screen: Settings,
    },
  },
  {
    initialRouteName: 'Home',
  }
);
export default createAppContainer(AppNavigator);

**Comment by anilkumar1505** [comment]
Thanks !!!! it is working

**Comment by eriveltonelias** [comment]
thanks @brentvatne!

**Comment by priya0607jain** [comment]
I followed the same convention but still getting the error. Here is my code from App.js:


`/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 *
 * @format
 * @flow
 */

import React, {Component} from 'react';
import {Platform, StyleSheet, Text, View} from 'react-native';
import { createAppContainer, createDrawerNavigator, createStackNavigator, DrawerItems, SafeAreaView } from 'react-navigation';


import Home from './components/home/home'
import MainCategory from './components/maincategory/maincategory';
import Login from './components/account/login';
import Register from './components/account/register';
import Description from './components/description/description'
import Settings from './components/settings/settings';
import SmartDrawer from './components/drawer/drawer'


export const CustomDrawer = createDrawerNavigator({
  
  Home: Home,
  MainCategory: MainCategory,
  Login: Login,
  Register: Register,
  Settings: Settings,
  Description: Description
  
}, {
 
  contentComponent: props => 
    <SmartDrawer props={props} />
});



const MainNavigator = createStackNavigator({
  Home: {screen: props =>  <CustomDrawer screenProps={props} />},
  MainCategory: MainCategory,
  Description: Description,
  Settings: Settings
},
{
  navigationOptions:
    {
      header: null
    }
  })



const App = createAppContainer(MainNavigator);


export default App;


const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
`
and here is the snippet of the error that came after trying that code:

![whatsapp image 2018-11-26 at 5 36 08 pm](https://user-images.githubusercontent.com/40720034/49013333-649ff280-f1a2-11e8-96c8-1a7e993734e6.jpeg)

**Comment by brentvatne** [comment]
hi! create a new issue with a reproducible example on https://snack.expo.io, thanks
