### ISSUE TITLE
Authorization and several menus depending on the type of user

### ISSUE THREAD

**Issue by nikell28** [react-navigation/react-navigation#5263]
Hi! 
Please tell me how I can make an authorization page based on react-navigator? 
Also, how can I change the sidebar depending on the type of authorized user?

**Comment by eriveltonelias** [comment]
Hi @nikell28! 

for authentication flow use can use it: https://reactnavigation.org/docs/en/auth-flow.html#set-up-our-navigators
and for change the sidebar react-navigation doesn't support yet dynamic routes you can check it on 
https://reactnavigation.org/docs/en/limitations.html#dynamic-routes 

for question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.
