### ISSUE TITLE
jest / react-native-gesture-handler: Cannot read property 'directEventTypes' of undefined

### ISSUE THREAD

**Issue by rsmelo92** [react-navigation/react-navigation#5264]
### Current Behavior
Followed every step of the tutorial but I'm running tests with jest and it's breaking since update. The app runs successfully

`node node_modules/jest/bin/jest.js`
![image](https://user-images.githubusercontent.com/16295402/48872605-968f0e80-edc8-11e8-9c4b-878a2ec54d46.png)

### Expected Behavior

The tests should pass as it was passing in version 2

### How to reproduce

Update to version 3

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |^3.0.0
| react-native     |0.57.0
| node             |11.0.0
| yarn      |1.12.3

**Comment by eriveltonelias** [comment]
Hi @rsmelo92! 

seems like this is related with `react-native-gesture-handler`
please read this: https://github.com/kmagiera/react-native-gesture-handler/issues/344#issuecomment-440572584 and https://forums.expo.io/t/jest-and-react-native-gesture-handler/13449


if it do not work, please create a runnable example to people help you.

**Comment by eriveltonelias** [comment]
I'll close the issue for now because is related with `react-native-gesture-handler`, but if you disagree please tell me to reopen. Thanks for understanding.

**Comment by dannyheard7** [comment]
`jest.mock('react-navigation', () => {
    return {
        createAppContainer: jest.fn().mockReturnValue(function NavigationContainer(props) {return null;}),
        createDrawerNavigator: jest.fn(),
        createMaterialTopTabNavigator: jest.fn(),
        createStackNavigator: jest.fn(),
        StackActions: {
            push: jest.fn().mockImplementation(x => ({...x,  "type": "Navigation/PUSH"})),
            replace: jest.fn().mockImplementation(x => ({...x,  "type": "Navigation/REPLACE"})),
        },
        NavigationActions: {
            navigate: jest.fn().mockImplementation(x => x),
        }
    }
});`

Mocking example that removes this issue

**Comment by brentvatne** [comment]
leaving this issue open because RNGH is a dependency and this behavior impacts react-navigation users

**Comment by brentvatne** [comment]
it's also worth noting that this issue doesn't currently impact expo users because the jest expo preset mocks UIManager.RCTView.directEventTypes

**Comment by ttruongatl** [comment]
Thanks @dannyheard7 . It works for me.

**Comment by brentvatne** [comment]
we do this in jest-expo: https://github.com/expo/expo/blob/f882ffbc52ba910ecacefe264081e7eeb77c9665/packages/jest-expo/src/setup.js#L167-L199

**Comment by mehranabi** [comment]
@brentvatne @eriveltonelias 

Hi everyone! Please check my repo on Github: https://github.com/mehranabi/rn-gh-error

I had the same issue but fixed it by this mock:
```
jest.mock('NativeModules', () => ({
  UIManager: {
    RCTView: () => ({
      directEventTypes: {},
    }),
  },
  KeyboardObserver: {},
  RNGestureHandlerModule: {
    attachGestureHandler: jest.fn(),
    createGestureHandler: jest.fn(),
    dropGestureHandler: jest.fn(),
    updateGestureHandler: jest.fn(),
    State: {},
    Directions: {},
  },
  PlatformConstants: {
    forceTouchAvailable: false,
  },
}))
```
But after that, When I run the test, I get this error:
```
D:\Mehran\Projects\ReactNative\RNGestureHandlerError\node_modules\@react-navigation\native\dist\withOrientation.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import React from 'react';
                                                                                                    ^^^^^

    SyntaxError: Unexpected identifier

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/ScriptTransformer.js:440:17)
      at Object.get withOrientation [as withOrientation] (node_modules/@react-navigation/native/dist/index.js:17:12)
      at Object.<anonymous> (node_modules/react-navigation-stack/dist/views/Header/Header.js:538:16)
```

And I think it's releated to `react-navigation`...

**Comment by 6thCode** [comment]
Hi guys, this was what worked for me and most likely work for you...

After installing jest

npm install --save-dev jest
npm install --save-dev babel-jest regenerator-runtime

Then go to your package.json file, under your

 "jest": {
    "preset": "react-native"
 }

include this

"setupFiles": [
     "./node_modules/react-native-gesture-handler/jestSetup.js"
   ],
   "transformIgnorePatterns": [
     "/node_modules/(?!native-base)/"
   ]
 }
The end result will be

  "jest": {
     "preset": "react-native",
     "setupFiles": [
       "./node_modules/react-native-gesture-handler/jestSetup.js"
     ],
     "transformIgnorePatterns": [
       "/node_modules/(?!native-base)/"
     ]
  }
Then run npm test 🙂🙂

**Comment by SMcDonald1** [comment]
That worked for me @6thCode !
Thanks.
