### ISSUE TITLE
Navigation back with DrawerNavigator 

### ISSUE THREAD

**Issue by Er-rchydy** [react-navigation/react-navigation#5265]
If i'm using only `DrawerNavigator`  how can i add back button?

**Comment by eriveltonelias** [comment]
hi there! this is a question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.

**Comment by Er-rchydy** [comment]
@eriveltonelias  you remind me of responses i get on stackoverflow  when i was learning `HTML` . when i didn't understand something i search for it then when i don't find anything i ask on stackoverflow, i was asking a simple questions like someone can give an answer in one line, but instead i get 5 answer with 4 lines each talking about 'you should start with capital letter' , 'you didn't put a dot at the end of the sentence ', i mean what the hell, my question was about programing not about how to be Shakespeare, at least answer the question then say here is how to ask a question on here or something like that, but be helpful first.
you just did the exact same thing. i'm not saying you shouldn't say this is not stackoverflow or discord, but always be helpful.

**Comment by eriveltonelias** [comment]
Hi @Er-rchydy! 

Sorry if offended you, wasn't my intention, this repo is for bug only we have a channel on discord that people can help you.
I don't know if is that what are you looking for but check it https://snack.expo.io/@eriveltonelias/drawer-with-back-button

**Comment by Er-rchydy** [comment]
@eriveltonelias  i wasn't expecting what you did 👍 , thanks a lot, that was really helpful
