### ISSUE TITLE
Question about two navigation on one page

### ISSUE THREAD

**Issue by alfredacs** [react-navigation/react-navigation#5269]
### Current Behavior

Hi everyone, I am a newbie to react-native and just start developing a horizontal IPad App. Now I am facing a problem how to place two navigator inside one page like the picture. As you see, the idea is that a page is separated by two panels and the right panel (yellow part) is supposed to navigate among its detail pages. Please note that there is already a drawer navigator developed on the far right. Many Thanks

![test](https://user-images.githubusercontent.com/45260585/48899663-26958c80-ee8b-11e8-9e6e-4e55cf49a5ff.png)

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | "^2.16.0"
| react-native     | https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz
| node             | v11.1.0
| npm or yarn      | 6.4.1

**Comment by eriveltonelias** [comment]
hi there! this is a question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.
