### ISSUE TITLE
React-native with react-navigation. How to make screen from tabBarNavigator invisible on TabBar?

### ISSUE THREAD

**Issue by Hannibal2** [react-navigation/react-navigation#5270]
I really need your help. I use react-navigation version 3.x. How to make screen from tabBarNavigator invisible on TabBar? I need to remove main screen from tabBar(it should be invisible) but TabBar must be on main screen. My screen structure is next:

```
const AppStackNavigator = createStackNavigator({
    loginFlow: { 
      screen: createStackNavigator({
        intro: { screen: Intro },
        login: { screen: Login },
        registration: { screen: Registration }
      })
    },
    mainFlow: {
      screen: createStackNavigator({

        // settings: { screen: SettingsScreen },
        someTab: { 
          screen: createBottomTabNavigator({
            main: { screen: Home },
            Tab1: { screen: Tab1 },
            Tab2: { screen: Tab2 },
            Tab3: { screen: Tab3 },
            Tab4: { screen: ChatMain }
          })
        }
      })
    }
  });
```

**Comment by vonovak** [comment]
hello, as the issue template explains, this issue tracker is reserved for bugs only. Please use stackoverflow to ask your questions. That being said, I'd check out the docs [here](https://reactnavigation.org/docs/en/bottom-tab-navigator.html#tabbarbuttoncomponent) and [here](https://reactnavigation.org/docs/en/bottom-tab-navigator.html#bottomtabnavigatorconfig). Thanks.
