### ISSUE TITLE
[V2] is it possible to have a stand-alone stack navigator inside a react-native modal?

### ISSUE THREAD

**Issue by kadoshms** [react-navigation/react-navigation#5271]
My goal is to have something like that:

<Modal ....> 
  <Navigator />
</Modal>

In such way that the Navigator is a totally stand alone navigation router without any relation to the main app navigation.

It used to be pretty simple in V1, but now it seems like react-navigation doesn't like having multiple router components.

Thanks.

**Comment by eriveltonelias** [comment]
Hi @kadoshms. 

 you can create a stack navigator to open as modal https://reactnavigation.org/docs/en/modal.html#creating-a-modal-stack which makes sense but I don't think that will works as expect if you add it inside react-native modal.
