### ISSUE TITLE
DeepLinking is not working when combine createDrawerNavigator 

### ISSUE THREAD

**Issue by motogod** [react-navigation/react-navigation#5272]
### Current Behavior

Type command  `xcrun simctl openurl booted mychat://chat` will open `A `screen not `Second` screen.

### Expected Behavior

It should open Second screen when type `xcrun simctl openurl booted mychat://chat` on terminal

### How to reproduce

With the code `const SimpleApp = createAppContainer(Router);`.

If use `createAppContainer(Stack2)` that is only two screen with createStackNavigator, DeepLinking is working.

If use `createAppContainer(Stack)` that combine with `createBottomTabNavigator`, DeepLinking is working too.

If use `createAppContainer(Router)` that combine with `createDrawerNavigator`,DeepLinking is not working any more.

I create a simple repo on github https://github.com/motogod/DeepLinkingDrawer

Here is the code.

Router.js:
```
import { createMaterialTopTabNavigator, createStackNavigator, 
  createDrawerNavigator, createTabNavigator,
  createBottomTabNavigator, createAppContainer
} from 'react-navigation';
import React, { Component } from 'react';
import { Platform } from 'react-native';
import A from './components/A';
import B from './components/B';
import C from './components/C';
import D from './components/D';
import E from './components/E';
import F from './components/F';
import G from './components/G';
import Second from './components/Second';
import DrawerPanel from './components/DrawerPanel';

const Stack = createStackNavigator({
  A: {
    screen: createBottomTabNavigator({
      'A Screen': A,
      'B Screen': B,
      'C Screen': C,
      'D Screen': D,
      'E Screen': E,
      'F Screen': F,
      'G Screen': G
    },
    {
      swipeEnabled: false,
      lazyLoad: false,
      tabBarOptions: {
        activeTintColor: 'tomato',
        inactiveTintColor: 'gray',
          tabStyle: {
            width: 125,
            height: 50
        },
        scrollEnabled: true 
      }  
    })
  },
  Second: {
    screen: Second,
    // path: 'chat/:user'
    path: 'chat'
  }
},
  {
    initialRouteName: 'A',
    headerMode: 'screen'
  }
);

const Stack2 = createStackNavigator({
  A: { 
    screen: A,
    path: 'chatA'
  },
  B: {
    screen: B,
    path: 'chatB',
  },
});

// const MainApp = () => <Stack uriPrefix={prefix} />;

const Router = createDrawerNavigator({
  FirstScreen: {
    screen: Stack
    // screen: () => (<Stack uriPrefix={prefix} />)
  }
},
{
  contentComponent: DrawerPanel,
  drawerWidth: 200
});

// about Deep linking
const prefix = Platform.OS == 'android' ? 'mychat://mychat/' : 'mychat://';

// Situation 1
// terminal command is: xcrun simctl openurl booted mychat://chatB
// It is working if only use createStackNavigator
// params can be Stack or Stack2
// const SimpleApp = createAppContainer(Stack2);
// const MainApp = () => <SimpleApp uriPrefix={prefix} />;
// export default MainApp;

// Situation 2
// terminal command is: xcrun simctl openurl booted mychat://chat
// It is not wroking when combine createDrawerNavigator
const SimpleApp = createAppContainer(Router);
const MainApp = () => <SimpleApp uriPrefix={prefix} />;
export default MainApp;
```

### Your Environment
```
Environment:
  OS: macOS High Sierra 10.13.6
  Node: 8.11.2
  Yarn: 1.12.3
  npm: 6.4.1
  Watchman: 4.9.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 3.2 AI-181.5540.7.32.5056338


  "dependencies": {
    "react": "16.3.1",
    "react-native": "0.55.4",
    "react-native-gesture-handler": "^1.0.9",
    "react-navigation": "^3.0.0"
  },
```

**Comment by auzwang** [comment]
This happens because the screen you want to deep link to uses the _DrawerNavigator_ navigation context. That context is not exposed and nested underneath another top level navigator with its own navigation context.

You can solve this by setting the _DrawerNavigator_ screen (`Router`) as a screen in the top-level app navigator. Then thread through the app navigation prop through DrawerNavigator. See the last example [here](https://reactnavigation.org/docs/en/common-mistakes.html#explicitly-rendering-more-than-one-navigator).

**Comment by eriveltonelias** [comment]
Cool, thanks @auzwang! Can you confirm if works for you @motogod  ?

**Comment by motogod** [comment]
Hi @auzwang  thanks for reply. According your suggestion, I try to fix const Stack like this:

```
const Stack = createStackNavigator({
  A: {
    screen: createBottomTabNavigator({
      'A Screen': A,
      'B Screen': B,
      'C Screen': C,
      'D Screen': D,
      'E Screen': E,
      'F Screen': F,
      'G Screen': G
    },
    {
      swipeEnabled: false,
      lazyLoad: false,
      tabBarOptions: {
        activeTintColor: 'tomato',
        inactiveTintColor: 'gray',
          tabStyle: {
            width: 125,
            height: 50
        },
        scrollEnabled: true 
      }  
    })
  },
  Second: {
    screen: Second,
    path: 'chat'
  },
  TestDrawer: {
    screen: createDrawerNavigator({
      screen: DrawerPanel
    },
    {
      drawerWidth: 200
    })
  }
},
  {
    initialRouteName: 'A',
    headerMode: 'screen'
  }
);
```

Obviously my Drawer setting is wrong. Do I misunderstand something ?

**Comment by auzwang** [comment]
@motogod that's very close. Now add a `path` to your `TestDrawer` and `DrawerlPanel` like so:
```
TestDrawer: {
    screen: createDrawerNavigator({
      screen: DrawerPanel,
      path: 'drawerPanel'
    },
    {
      drawerWidth: 200
    }),
    path: 'testDrawer'
  }
```
Now try `xcrun simctl openurl booted mychat://testDrawer` and it should deep link to the `TestDrawer` screen. Or run `xcrun simctl openurl booted mychat://testDrawer/drawerPanel` to deep link into your `DrawerPanel` screen. If this doesn't work, make sure your `DrawerPanel` component has `router` exposed and `navigation` threaded as described in the last example [here](https://reactnavigation.org/docs/en/common-mistakes.html#explicitly-rendering-more-than-one-navigator).

**Comment by motogod** [comment]
@auzwang Thanks, but this code will lose my drawer if I set the TestDrawer under `createStackNavigator`, any suggestion ? Thanks again truly.

**Comment by auzwang** [comment]
@motogod sorry I'm not sure what you mean by losing the drawer. The issue your facing here might be related to the composition of your navigators. Have a look at this point [here](https://reactnavigation.org/docs/en/navigation-options-resolution.html#a-drawer-has-a-stack-inside-of-it-and-you-want-to-lock-the-drawer-on-certain-screens)?

**Comment by motogod** [comment]
@auzwang  Hmm... In my code just like the question, I have 7 tabs (ABCDEFG), all the tabs has a drawer that comes from `contentComponent: DrawerPanel` . If I set the drawer like this:
```
TestDrawer: {
    screen: createDrawerNavigator({
      screen: DrawerPanel,
      path: 'drawerPanel'
    },
    {
      drawerWidth: 200
    }),
    path: 'testDrawer'
  }
```

The drawer will disappear.

If I type `xcrun simctl openurl booted mychat://testDrawer` and yes the DeepLinking works, but DrawerPanel just become a screen not a drawer.

I still try to fix the code from your share the link title **A drawer has a stack inside of it and you want to lock the drawer on certain screens**.

Can't find the way. Hope can get some suggestion. Thanks in advance.

**Comment by guohuihot** [comment]
tomato？^_^

**Comment by rodrigorm** [comment]
@motogod I maybe have some relatable problem.

I am debugging the navigation with deeplink and looks like the switch navigator does not dispatch action to child router. The closest I get in the `react-navigation` code is this line https://github.com/react-navigation/core/blob/master/src/routers/SwitchRouter.js#L266, in my setup the `action.action` value exists but the `childRouter` does not which does not dispatch the `childRouter.getStateForAction`.

**Comment by rodrigorm** [comment]
Ok, found the solution in my scenario, the problem is I have the same routeName "Home"  Stack > Drawer > Stack navigators on last Drawer and Stack and this caused the Stack to not receive the correct action to execute.

**Comment by mohamed-ikram** [comment]
@rodrigorm what do u mean by not receive the correct action to execute I'm using switch->drawer->stack  and I cant able to navigate to the stack path via deeplink can u help
