### ISSUE TITLE
Why the first scene does not response swipe back action?

### ISSUE THREAD

**Issue by lvst09** [react-navigation/react-navigation#5273]
My code is like this , while the second and after scene can response the swipe back gesture to pop current scene ,but at the root scene , the swipe back gesture is not responsed .
The question is where is the code does the router judge if or how to responsed the swipe back guesture, i want to hack the callback to implement the function to pop out from react native root scene to native VC

            {/*<Provider store={store}>*/}
                {/*<Router hideNavBar={true}>*/}
                    {/*<Stack key="root" hideNavBar={true} >*/}
                        {/*<Scene key='RootTab'*/}
                               {/*component={RootTabRD}*/}
                               {/*duration={1}/>*/}

i use react-native-router-flux which is based on react-navigation

**Comment by eriveltonelias** [comment]
Hi @lvst09! 

seems that is related with `react-native-router-flux`, so create an issue on https://github.com/aksonov/react-native-router-flux please, thanks!
