### ISSUE TITLE
navigation.dispatch(StackActions.reset(...)) fails silently 

### ISSUE THREAD

**Issue by edzillion** [react-navigation/react-navigation#5274]
### Current Behavior
```
    this.props.navigation.dispatch(StackActions.reset({
      index: 0,
      key: 'NonExistentKey',
      actions: [NavigationActions.navigate({ routeName: 'HomeScreen' })]
    }))
```
This code will fail without an error. 

### Expected Behavior

Return some kind of error describing what went wrong. `KeyNotFound` would be good start.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.1
| react-native     | 31.0.1
| node             | 10.13.0
| npm or yarn      | 6.4.1

**Comment by eriveltonelias** [comment]
Hi @edzillion, 

please make your code runnable either on https://snack.expo.io without any extraneous code.

**Comment by brentvatne** [comment]
similar to how when you dispatch an action that isn't handled by a reducer in redux and nothing happens, react-navigation actions don't throw errors or anything when they are unhandled.

however, if the app state doesn't change as a result of dispatch then the return value for dispatch is false. if it does, then the return value is true - https://github.com/react-navigation/react-navigation-native/blob/a7311ca18da898219e456c4929cec8a654a5023f/src/createAppContainer.js#L349-L361.

@eriveltonelias - if you have time can you open a PR to the docs to add this?

**Comment by eriveltonelias** [comment]
for sure @brentvatne, I can work on this. :)
