### ISSUE TITLE
Add TypeScript types to this repository

### ISSUE THREAD

**Issue by janhesters** [react-navigation/react-navigation#5275]
I know these issues are for bugs only, but I couldn't find a good place to ask this.

Is there any interest in moving type definitions to this repository?

I would volunteer and add these in the following days. I just didn't want to create a PR without having a green light from anyone. The types of definitely typed are terribly outdated, especially now that V3 is out.

**Comment by eriveltonelias** [comment]
Hi @janhesters! 

Thanks for your interest to work on this, you can follow this conversation: https://github.com/react-navigation/react-navigation-core/issues/2
