### ISSUE TITLE
undefined is not an object (evaluating 'component.router')

### ISSUE THREAD

**Issue by teovillanueva** [react-navigation/react-navigation#5280]
Hi everyone, after some time digging for a solution for my error i decided to open an issue here since it appears to be a bug. I have never posted an issue on github, but im trying to make a usefull post so if anyone else is having this issue, it can be understood properly. I have these three separate files, **_App.js_** which is the main entry point, **_Application.js_** where there is a check and then so rendered **_AuthNavigation.js_**.

React-navigation version: **_3.0.0_**

Error: 
> undefined is not an object (evaluating 'component.router')

This is **_App.js_**:
```
import React, {Component} from 'react';

import Application from './src/Application';

export default class App extends Component {
    state = {
        auth_state: false
    }
    _CheckForAuthStatus = async () => {
        try {
          const value = await AsyncStorage.getItem('AUTH_TOKEN');
            if (value !== null) {
                // User is signed in.
                this.setState({auth_state: true});
            } else {
                // User is not signed in
                this.setState({auth_state: false});
            }
        } catch (error) {
            // Error retrieving data
        }
    }

    componentWillMount = () => {
        this._CheckForAuthStatus;
    }

    render() {
        return (
            <Application auth_state={this.state.auth_state}/>
        );
    };
};
```
This is **_Application.js_**:
```
import React, { Component } from 'react'
import { Text, View } from 'react-native'

// Auth navigator.
import AuthNavigation from './screens/auth/AuthNavigation';

export class Application extends Component {
    state = {
        auth_state: this.props.auth_state,
    }
    render() {
        if (this.state.auth_state === true) {
            
        } else {
            return(
                <AuthNavigation/>
            );
        };
    };
};

export default Application;
```
And this is **_AuthNavigation.js_**: 
```
import React, { Component } from 'react';
import { createSwitchNavigator, createNavigationContainer } from 'react-navigation';

// Auth screens.
import Login from './login';
import Register from './register';

// Create switch navigator.
const AuthSwitchNavigator = createSwitchNavigator({
    Login: Login,
    Register: Register
});

// Create container for switch navigator.
const AuthNavigationContainer = createNavigationContainer(AuthNavigationContainer);

// Export authNavigationContainer
export default AuthNavigationContainer;
```

Thanks in advance for any kind of reply.
(I dont know if my english is the best but i hope you can understand it :) )

Snack for error:
https://snack.expo.io/@teovilla/undefined-is-not-an-object-(evaluating-'component.router')

**Comment by vonovak** [comment]
hi @teovillanueva as the issue template explains, we require you to include a runnable repro (please see https://stackoverflow.com/help/mcve for details) of the issue, since otherwise it's hard to help. Can you please add a link to https://snack.expo.io that reproduces the issue? Thanks.

**Comment by teovillanueva** [comment]
Thanks for your reply @vonovak
I will edit now the issue so it matchs.
Here is the snack, the issue is recreated successfully :)
https://snack.expo.io/@teovilla/undefined-is-not-an-object-(evaluating-'component.router')

**Comment by swellingt0n** [comment]
Working snack:
https://snack.expo.io/B1Z8dFvRX

1. You needed to use `createAppContainer`, not `createNavigationContainer`
2. `const AuthNavigationContainer = createNavigationContainer(AuthNavigationContainer)` is clearly not going to work, it should be `const AuthNavigationContainer = createAppContainer(AuthSwitchNavigator)`

**Comment by teovillanueva** [comment]
@swellingt0n Thank you very much! I saw in the docs about createAppContainer, but in VSCode when importing it i wasnt appearing in the intellisense so i tried using createNavigationContainer! Thanks :)
