### ISSUE TITLE
"You should only render one navigator" - but why?

### ISSUE THREAD

**Issue by kadoshms** [react-navigation/react-navigation#5284]
Hey there,

I am working on an application that has some sort of form component.
This form includes some modal windows, which each has more inner pages - for instance, this form shows a list of items - I then can press on an item, open a editor modal, and edit the item's details by clicking on the detail, opening it's inner editor, and save.
This form is also reusable across the app, meaning that the whole navigation system of this form is totally isolated from the rest of the app.

With react-navigation, at least in my humble and short time experience it is complicated as hell. I face the choices between endless nesting of navigators, different modes and so much more. In fact, I spent hours doing it the "right way" but kept failing.

The docs (https://reactnavigation.org/docs/en/2.x/common-mistakes.html) state that: 

> In a screen inside of the navigator we are rendering another navigator 
> You should avoid this! It will have its own navigation state and be unable
> **To interact with any parent navigator, eg: it would not know the route "Home" exists**
   
But in this case this is exactly what i want! I don't want to have any interaction between those navigators, and I simply want to give a good looking isolated navigation experience, just like **JIRA** give in their mobile IOS app.

When I do it "my way" (of rendering more than one navigator), I keep get this warning "You should only render..." .

I'd love to hear your opinions about that.
Thanks.

**Comment by brentvatne** [comment]
you can add a `detached={true}` prop to it if you want to do this! i still don't think it makes sense even given the case that you explained but it's up to you!

**Comment by kadoshms** [comment]
@brentvatne can you please elaborate?
I might have not mentioned that but this form component is **just a part** of a page (it is and old plain react component), and it has it's own flows of modal windows and navigation.
Is it still possible to achieve this flow the "right way"?

**Comment by brentvatne** [comment]
@kadoshms - if you can post a minimal example trying to demonstrate what you are doing to https://snack.expo.io/ i can help

**Comment by kadoshms** [comment]
@brentvatne sure, here it is: https://snack.expo.io/@morkadosh/standalone-navigation
It is pretty **dumb and ugly** because I only had 10 minutes for doing that but it does demonstrate the goal :)

Anyway, as you can see, the Form component is reusable and is just embedded as a regular component in some pages. It's internal navigation can not be part of the main one since It is an isolated component .
Maybe my all approach to that is not relevant or wrong, I would love to be enlightened. 

BTW For some reason I don't see the warning here :/

Thanks!

**Comment by kadoshms** [comment]
@brentbatne I'd love to hear your opinion :)
