### ISSUE TITLE
How to navigate to different routed and go back dismiss to self route?

### ISSUE THREAD

**Issue by socheat1994** [react-navigation/react-navigation#5286]
I have several nested navigator with above structure: 

- StackNavigator
   - authNav
   - homeNav
      - main(default)
      - create
        - subCreate1(default)
        - subCreate2
        - subCreate3
      - list
        - subList1(default)
        - subList2

actually I play to navigate it. it's work as i expect. 
But when I stay on `subCreate3` screen, I want to navigate to `subList1` screen, then when back or dismiss from `subList1` it should go to `main` screen not go to `subCreate3`. 
any idea with this ?. thank react-native user :D

**Comment by brentvatne** [comment]
hi there! this is a question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.
