### ISSUE TITLE
Drawer gesture / animation sluggish on Android

### ISSUE THREAD

**Issue by brentvatne** [react-navigation/react-navigation#5287]
Compared to the the DrawerLayout used in react-navigation 2, the one in 3 is reported to [feel more sluggish](https://github.com/react-navigation/react-navigation/issues/5251#issuecomment-440978123). The change that occurred between these versions is that we now use a drawer implemented with react-native-gesture-handler rather than the built in DrawerLayout, because the built-in one caused all sorts of issues when nesting.

@divisumma and @xanderberkein can you elaborate on what you meant by sluggish with as much detail as possible? Thanks!

**Comment by panda0603** [comment]
Same problem. One crucial reason why I downgraded back down to version 2 until this problem is fixed. The way I experience is that when I use slide gesture to open (not by calling toggleDrawer method), the drawer doesn't open smoothly like version 2 but kind of stops? lags? for very short period of time while opening.

**Comment by brentvatne** [comment]
cc @kmagiera - maybe time for reanimated

**Comment by divisumma** [comment]
I wrote a minimal app, with just a main screen and a drawer.
These two examples share the exact same code, except for the "AppContainer" required by RN3.
As you can see, the animation on RN3 stutters visibly.

**React Navigation 2**:
![drawerrn2](https://user-images.githubusercontent.com/39595678/49147376-ce381200-f304-11e8-88fc-65df2a22c12e.gif)

The code:
```
const Home   = () => (<View><Text>Home</Text></View>);
const Drawer = () => (<View><Text>Drawer</Text></View>);

const MyDrawer = createDrawerNavigator({
    'Home' : {
        screen : Home
    }
}, {
    contentComponent : Drawer
});

export default class App extends Component<Props> {
    render() {
        return (
            <MyDrawer></MyDrawer>
        );
    }
}
```

**React Navigation 3**:
![drawerrn3](https://user-images.githubusercontent.com/39595678/49147782-e6f4f780-f305-11e8-877d-952b03dc3a8a.gif)

The code:
```
const Home   = () => (<View><Text>Home</Text></View>);
const Drawer = () => (<View><Text>Drawer</Text></View>);

const MyDrawer = createDrawerNavigator({
    'Home' : {
        screen : Home
    }
}, {
    contentComponent : Drawer
});

const MyContainer = createAppContainer(MyDrawer);

type Props = {};
export default class App extends Component<Props> {
    render() {
        return (
            <MyContainer></MyContainer>
        );
    }
}
```

**Comment by neel132** [comment]
Experiencing same for createMaterialTopTabNavigator.

**Comment by brentvatne** [comment]
if you want to you can fork react-navigation-drawer and use the old version rather than the one included in v3. perf is not going to be quite as good for now because we need to switch it to use react-native-reanimated which we will do once we add that as a dependency and switch stack over to it as well

**Comment by brentvatne** [comment]
it's possible to improve the performance of the drawer considerably with some optimizations. if someone wants to give it a shot, you can clone the drawer repo and edit this file: https://github.com/react-navigation/react-navigation-drawer/blob/master/src/views/DrawerLayout.js

suggestion via @kmagiera:
when the gesture ends we call `setState` which re-renders drawer along with its children - https://github.com/kmagiera/react-native-gesture-handler/blob/master/DrawerLayout.js#L270. we only do this to update the accessibility and pointerEvents props, so we could use setNativeProps for this instead, similar to https://github.com/react-navigation/react-navigation-stack/blob/master/src/views/StackView/createPointerEventsContainer.js

**Comment by zvs001** [comment]
Also have some issue.
Drawer has really ugly animation. Particularly for children routes.
In @divisumma example you can see 2 jumps. I see at least 4-5 jumps

My structure like: stack => tabs => stack => drawer

**Comment by brentvatne** [comment]
@zvs001 - post a new issue and share a repro and an animation. hid your comment because it's off topic

**Comment by eriveltonelias** [comment]
@panda0603 @divisumma 

can you test it again with the last version of `react-native-gesture-handler` ( 1.0.12)? 
see this commit https://github.com/kmagiera/react-native-gesture-handler/commit/bed9707061e9e70f95a1908fac60d0c544b1e8d9

**Comment by phamdungkma** [comment]
Confirm. Same problem
```
"react": "16.6.3",
"react-native": "0.57.8",
"react-native-gesture-handler": "^1.0.12",
"react-navigation": "^3.0.8",
```

**Comment by brentvatne** [comment]
this is fixed upstream in react-native-gesture-handler and on this branch in drawer: https://github.com/react-navigation/react-navigation-drawer/tree/%40brent/update-rngh

i'm off for holidays but will release this update in the new year

**Comment by i1990jain** [comment]
@brentvatne Happy New Year! Are you back from holidays

**Comment by i1990jain** [comment]
> this is fixed upstream in react-native-gesture-handler and on this branch in drawer: https://github.com/react-navigation/react-navigation-drawer/tree/%40brent/update-rngh
> 
> i'm off for holidays but will release this update in the new year
@brentvatne Happy New Year! Are you back from holidays?

**Comment by brentvatne** [comment]
yeah i might have time for this later in the week

**Comment by brentvatne** [comment]
can you try out react-navigation@3.1.0 and let me know if this helps? this includes the upstream changes from react-native-gesture-handler to improve performance.

i haven't tagged this release as latest yet but if a few people confirm that it at least improves their situation then i will. note that if you use expo you need to update to sdk32 because it requires some updates to react-native-gesture-handler

**Comment by rzdev** [comment]
i tried react-navigation@3.1.0, the animation is slightly smoother than before, but still not as smooth as react navigation 2. And i found a problem with 3.1.0, in previous versions the drawer open when we make gesture/dragging from the edge of the left/right side of the screen, now i can open the drawer by dragging from the center or the opposite side of the screen, and because in my application there is a carousel in the UI, the swipe function of the carousel stopped working.

**Comment by i1990jain** [comment]
> can you try out react-navigation@3.1.0 and let me know if this helps? this includes the upstream changes from react-native-gesture-handler to improve performance.
> 
> i haven't tagged this release as latest yet but if a few people confirm that it at least improves their situation then i will. note that if you use expo you need to update to sdk32 because it requires some updates to react-native-gesture-handler

I have tried it out using react-navigation@3.1.0 on Android 8.0.0 and iOS 12.1.1
on emulators the performance is satisfactory for both android and iOS,  on devices for iOS it works smooth but for Android it isn't working fine and seems to show the sluggish behaviour

**Comment by jfreak** [comment]
```
 "react-native": "0.57.7",
 "react-navigation": "3.1.0"
```
Tried it out still laggy and if there are continuous swipe to the drawer there is a delay in the app navigation.

**Comment by brentvatne** [comment]
at this point the only further optimization we can do is switch over to using reanimated for the gesture, which we plan to do for v4. we won't switch back from the rngh drawerlayout to using drawerlayoutandroid because there are too many issues with it despite performance being good. you're welcome to fork react-navigation-drawer and switch it to use the drawerlayoutandroid component if you like.

**Comment by mithunmo** [comment]
When is the v4 planned?

**Comment by jayzyaj** [comment]
Is there any update for the relase of v4? Thanks :)

**Comment by brentvatne** [comment]
no, if you want to work on this you can add reanimated to react navigation drawer but I don’t have time at the moment to work on it

**Comment by HarshitMadhav** [comment]
@brentvatne  Hi! I am using 3.0.7 version of react-navigation ` "react-navigation": "^3.0.7"` and facing this sluggish drawer problem in android. Should I use the version to 3.1.0?

**Comment by jamsch** [comment]
@HarshitMadhav I don't think much will change (on v3) as react-native-gesture-handler is used for the drawer and adding/changing native libraries will require a major release.

Personally, I've downgraded back to v2.18.3 for the time being and will look in to reworking react-navigation-drawer to either use reanimated or DrawerLayoutAndroid.

**Comment by mnlbox** [comment]
Any plan to fix this?
I update from RN2 to RN3 and it's performance is too bad in Android

**Comment by brentvatne** [comment]
i'm going to lock this because i've already mentioned that we plan to improve the perf, we just don't have time to do it right now. you can install an old version of the drawer if you prefer, or fork it to build your own drawer navigator. hopefully we'll get something out in the next month or two for you! sorry for the hassle

**Comment by brentvatne** [comment]
@satya164 recently rewrote the drawer to use react-native-reanimated. install the latest 2.0.0 release (currently alpha.1 at the time of writing) and you should see improvements

**Comment by devsrv** [comment]
@brentvatne installed the alpha.1 working absolutely fine & smooth.

**Comment by Albeenos** [comment]
@brentvatne very nice, thanks!

**Comment by michal-th** [comment]
I'm facing a below error after importing createDrawerNavigator from react-navigation-drawer:

> TypeError: Cannot read property 'configureProps' of undefined
 
If imported from react-navigation, everything is fine.. any ideas please?

**Comment by Ashkan-Oliaie** [comment]
I still have this issue that drawer opens in 2 stages and not smooth

**Comment by ManasN** [comment]
> I still have this issue that drawer opens in 2 stages and not smooth

Same here, using latest Navigation version 3. Drawer lags in opening.

**Comment by gabriel1lima** [comment]
I have the same problem. (Version 3.9.0)

**Comment by brentvatne** [comment]
as mentioned above, install react-navigation-drawer@2.0.0-alpha.3 and import from there instead

**Comment by panda0603** [comment]
@brentvatne when do you think it will be integrated to main version of react-navigation?

**Comment by pedrobrost** [comment]
@brentvatne I don't understand what 2.0.0 alpha.1 version are you talnking about. [react-native-reanimated](https://github.com/kmagiera/react-nat) does not have that version.

**Comment by satya164** [comment]
@panda0603 it won't be. you should use that package directly

**Comment by panda0603** [comment]
@satya164 then from now on no more

import {createDrawerNavigator} from 'react-navigation' 

as before? or is it two seperate packages updated independentely? Im confused

**Comment by brentvatne** [comment]
`import { createDrawerNavigator } from 'react-navigation-drawer';`

in the future we won't re-export from the react-navigation package but we do for now

**Comment by ManasN** [comment]
> @satya164 recently rewrote the drawer to use react-native-reanimated. install the latest 2.0.0 release (currently alpha.1 at the time of writing) and you should see improvements. be sure to import the drawer from that pkg directly rather than react-navigation -- `import { createDrawerNavigator } from 'react-navigation-drawer';`

Thank you for your solution :) 

Upon installing, configuring and importing the new @alpha createDrawerNavigator from the pkg directly, I get **"Cannot read property 'configureProps' of undefined"**. I am using "contentComponent". Same code works fine when I change my import from direct pkg to react-navigation one. 

I am using react navigation version 3.9.1, please advice.

**Comment by satya164** [comment]
@ManasN please read the release notes https://github.com/react-navigation/drawer/releases/tag/v2.0.0

**Comment by ManasN** [comment]
> @ManasN please read the release notes https://github.com/react-navigation/drawer/releases/tag/v2.0.0

Sorry, it was a non-issue, after I cleared the cache using reset cache command and reran "run-android" it worked. It is working fine and super smooth now!

Thank you very much for quick response and this amazing libaray.

**Comment by viveKing21** [comment]
make sure that you are not using overflow style property on your screen...

**Comment by rajatmadaan786** [comment]
@brentvatne After installing `react-navigation-drawer@2.0.0-alpha.3` and linking react-native-animated via `react-native link react-native-reanimated`, When I started app via `npx react-native run-android`.

**React native throwing me below error:**

![image](https://user-images.githubusercontent.com/60581494/140636506-d9b33d4d-47a6-4986-ad75-a78f48af11f0.png)

**Here's my package.json content:**

    "react": "17.0.2",
    "react-native": "0.66.1",
    "react-native-gesture-handler": "^1.10.3",
    "react-native-reanimated": "^2.2.3",
    "react-navigation-drawer": "^2.0.0-alpha.3",

I am not sure If I am missing anything. Can you please guide on this?
