### ISSUE TITLE
Pass initial params to screens

### ISSUE THREAD

**Issue by zRelux** [react-navigation/react-navigation#5288]
I tried to implement a drawerNavigator with a stackNavigator inside, I wanted to pass some initial params to the routes in the drawerNavigator but I can't seem to access them when it gets rendered. I need to get those params and pass them to the stack navigator that is inside the drawerNavigator

### Current Behavior

I'm not able to pass the params to the stackNavigator. I want to access the params in the Content screen but I can't since they don't get passed from the drawerNavigator. If I change the drawerNavigator with a stacknavigator it works fine.

 In MainTabNavigator.js as you can see I pass the default params:
```
import React from "react"; 
import {
  createStackNavigator,
  createDrawerNavigator,
  createAppContainer
} from "react-navigation";

import SerieNavigation from "./SerieNavigation";

const MyDrawerNavigator = createDrawerNavigator({
  Anime: {
    screen: SerieNavigation,
    params: { type: "anime" },
    path: "anime/:anime"
  },
  Tv: {
    screen: SerieNavigation,
    params: { type: "tv-show" },
    path: "tv/:tv"
  },
  Film: {
    screen: SerieNavigation,
    params: { type: "film" },
    path: "film/:film"
  }
});

const AppContainer = createAppContainer(MyDrawerNavigator);

export default AppContainer;
```

but then in SerieNavigation i cannot pass them to the Search content:

```
import React, { Component } from "react";

import { createStackNavigator } from "react-navigation";

import SearchScreen from "../components/SearchContent";
import SearieScreen from "../components/SeriePage";
import EpisodePage from "../components/EpisodePage";

const SerieStack = createStackNavigator(
  {
    Content: {
      screen: SearchScreen,
    },
    Serie: SearieScreen,
    Episode: EpisodePage
  },
  {
    headerMode: "none",
    navigationOptions: {
      headerVisible: false
    }
  }
);

SerieStack.defaultNavigationOptions = {};

export default SerieStack;
```
For the nested navigators, I followed the docs https://reactnavigation.org/docs/en/common-mistakes.html

### Expected Behavior

Access the initial params. from the search content component. When I log the props I don't get the params passed.

### How to reproduce

https://snack.expo.io/@relux/drawernavigator
There is a issue with the snack it can't create a drawer navigator but if you reproduce it locally it works.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.0.0
| react-native     |  "https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz"
| node             | v10.8 
| npm or yarn      | yarn

**Comment by brentvatne** [comment]
would you expect these params to be available on the initial route in the stack only?

you can also get parent params by doing `this.props.navigation.dangerouslyGetParent().getParam('type');`

**Comment by zRelux** [comment]
Yes thank that is what I was looking for
