### ISSUE TITLE
createDrawerNavigator from 2.18 to 3.0 does not compile

### ISSUE THREAD

**Issue by blubberbo** [react-navigation/react-navigation#5289]
I have an application built with react-navigation 2.18 and I just upgraded to 3.0 and am getting the following:

![image](https://user-images.githubusercontent.com/17286750/49041318-c13ae780-f179-11e8-8d10-cde4ccc49d69.png)
 
The code that seems to break it is the call to `createDrawerNavigator`:

```
const BaseNavigation = createDrawerNavigator(
  {
    Home: {
      screen: HomeScreen,
    },
    Profile: {
      screen: ProfileScreen,
    }
  }
)
```

is this a known issue?

**Comment by brentvatne** [comment]
this means you didn't follow the instructions for installing react-native-gesture-handler :\ you could search existing issues to find this answer. i'm really not sure where else we can explain that this is necessary: 1) https://reactnavigation.org/docs/en/getting-started.html#installation 2) https://reactnavigation.org/blog/#installation

**Comment by blubberbo** [comment]
@brentvatne I missed that. Thank you very much for the help!
