### ISSUE TITLE
resetOnBlur: false should keep the state of screen react component

### ISSUE THREAD

**Issue by sapjax** [react-navigation/react-navigation#5291]
### Current Behavior

When using SwitchNavigator and set `resetOnBlur: false`.

SwitchNavigator contains two stack navigator A and B.
Switch from A to  B 
then switch back to A

Navigator just keep the route state, but all screen components lost the state of react component.

### Expected Behavior

I think most time, screen component should keep the state after user switch from other stackNavigator

For example, when the app became `active` from `background`,  we need to display the **lock screen**, so we switch the navigator to lockNavigator.

User unlock it with TouchID or FaceID,  then we switch it back to the main navigator, the screen components in the main navigator should not lose the component state.

**Comment by brentvatne** [comment]
the only purpose of resetOnBlur is to maintain the route state, as you have observed. i agree it may be useful in some situations to also keep the screen in memory, perhaps you can open a pr for this? either way it's a feature request so i will close and you can either open a pr, a rfc, or a feature request :)

**Comment by L-x-C** [comment]
@sapjax any ideas how to achieve that now?
I use  ```resetOnBlur: false``` to keep the route.
And after unlocking the screen, it navigates to previous screen successfully.
But it will trigger all the routes' componentDidMount.

Such as I navigate to ```screenA``` then ```screenB```, then make the app in ```background```
after unlock, the app will navigate to screenB, but it will trigger screenA's componentDidMount as well, which i make a lot of request.

any ideas how to avoid trigger all routes' componentDidMount?

**Comment by sapjax** [comment]
> @sapjax any ideas how to achieve that now?
> I use `resetOnBlur: false` to keep the route.
> And after unlocking the screen, it navigates to previous screen successfully.
> But it will trigger all the routes' componentDidMount.
> 
> Such as I navigate to `screenA` then `screenB`, then make the app in `background`,
> after unlock, the app will navigate to screenB, but it will trigger screenA's componentDidMount as well, which i make a lot of request.
> 
> any ideas how to avoid trigger all routes' componentDidMount?

It just keep the route  history, but no component state,  so every screen component is need create again, of cause will trigger `componentDidMount`.

For me, now I only use SwitchNavigator  for lockScreen when the app starts,  if reactive app from `background`,  I use `navigate.push` instead SwitchNavigator, it's not an ideal solution,  and make question became very complicated.

And another solution is to use a LockScreen Component to cover the whole app, do not use it as a react-navigation screen.

```ts
return <Provider store={store}>
      <View style={{ flex: 1 }}>
        <AppContainer
          onNavigationStateChange={(prevState, newState, action) => { }}
          ref={navigatorRef => {
            NavigationService.setTopLevelNavigator(navigatorRef)
          }}
        />
        <LockScreen />
      </View>
    </Provider>
```
