### ISSUE TITLE
drawerLockMode ist not working with v3

### ISSUE THREAD

**Issue by onitzschke** [react-navigation/react-navigation#5292]
Both is not working.
```
const FeedStack = createStackNavigator({
  FeedHome: FeedScreen,
  Details: DetailsScreen,
});

FeedStack.navigationOptions = ({ navigation }) => {
  let drawerLockMode = 'unlocked';
  if (navigation.state.index > 0) {
    drawerLockMode = 'locked-closed';
  }

  return {
    drawerLockMode,
  };
};
```

```
defaultNavigationOptions: {
 drawerLockMode: 'locked-closed'
}
```

**Comment by pzatorski** [comment]
Thanks @onitzschke for reporting it. This is related to: 
https://github.com/react-navigation/react-navigation-drawer/issues/33

**Comment by brentvatne** [comment]
this is fixed now, if you clear your yarn.lock and reinstall react-navigation you'll get react-navigation-drawer@1.0.2 with the fix

**Comment by amriteshkumarsharma** [comment]
See my ans @ https://stackoverflow.com/a/57028746/7209253
It's working for me..
