### ISSUE TITLE
Deep Linking params not available in componentDidMount.

### ISSUE THREAD

**Issue by micnil** [react-navigation/react-navigation#5295]
### Current Behavior

When launching an app with deep linking, the query params are not passed to the component on first mount **if** this component is also the initial route. They are available later in `componentDidUpdate` lifecycle.

### Expected Behavior

When launching a route via deep linking, I expect the params to always be available in `componentDidMount` of that component.

### How to reproduce

1. `git clone git@github.com:micnil/Potato.git`
2. `yarn install`
3. start android emulator
4. run: `react-native run-android`
5. run: `react-native log-android`
6. run: `adb shell am start -W -a android.intent.action.VIEW -d "potato://app/red/?result=success" com.potato`
    - or run `link.bat`

relevant code in: [https://github.com/micnil/Potato/blob/master/App.js](https://github.com/micnil/Potato/blob/master/App.js)

When initial route is set to RedPotato (or not set at all), the output will be: 
```
Red Mounted: failure
componentDidUpdate: success
```

When initial route is set to BluePotato, the output is:
```
Blue Mounted
Red Mounted: success
```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.0.0
| react-native     | 0.57.6
| node             | 10.13.0
| yarn      | 1.5.1
| react-native-gesture-handler | 1.0.9

### Related

Might be related to: "Deep linking: load only exact Screen" #4133 
because it is about the initial route being mounted before 
the route specified by the linking does.

**Comment by stefanmoser** [comment]
👍 
I've been struggling with this for a while so glad to see it's a known issue. As a workaround, is there a simple no-op to force `componentDidUpdate` to execute? I'm new to React/Native/Navigation, so I'm not sure.

**Comment by stefanmoser** [comment]
I added the following code as a workaround. It works for me in my scenario, but may not be right for your scenario.

```
componentDidMount() {
  this.forceUpdate();
}
```

**Comment by micnil** [comment]
Great that it worked for you. My issue is rather that I need to have the params passed to `componentDidMount`. 

What I want to do is something like this (simplified):

```
class AuthLoading extends React.Component {

    componentDidMount() {

        const apiToken = this.props.navigation.getParam('api_token');

        // also check if token is in AsyncStorage
        ...

        this.props.autoLogin(apiToken);
    }

    componentDidUpdate(prevProps) {
        const isLoggedIn = this.props.isLoggedIn; 
        if (isLoggedIn && isLoggedIn != prevProps.isLoggedIn) {
            this.props.navigation.navigate(isLoggedIn ? 'Main' : 'Auth');
        }
    }

    render() {
        return (
            <View style={styles.container}>
                <ActivityIndicator />
            </View>
        );
    }
}
```
My server will redirect the client to this component via deep linking with a jsonwebtoken as a param (OAuth). I want to log in (get the user information), and then navigate to either Main screen or Login screen depending on if it succeeded or not. 

Things get unnecessarily complicated if the token is not available in componentDidMount.

This component is also naturally also my inital route (since the token can also be in AsyncStorage), which is what is causing the problem.

**Comment by stefanmoser** [comment]
What you described is exactly the same usage I have. Same thing that the server redirects to this component via deep linking and the token is the param that I'm after. I totally agree that this _should_ be done in `componentDidMount`, but I find it acceptable workaround to do it all in `componentDidUpdate` since I know that the end result is the user being redirected to another screen, either login or the main screen. I'm fairly sure that `componentDidUpdate` is guaranteed to only run once in this scenario.

Here's what I've got:

```
class LoadingScreen extends React.Component {
  componentDidMount() {
    this.forceUpdate();
  }

  componentDidUpdate() {
    const { navigation, session } = this.props;
    const token = navigation.getParam('token');
    if (token !== null) {
      this.props.setToken(token, navigation);
      return;
    }
    if (session.token !== null) {
      this.props.setToken(session.token, navigation);
      return;
    }
    navigation.navigate('SignIn');
  }

  render() {
    return (
      <LoadingView />
    );
  }
}
```

**Comment by brentvatne** [comment]
hey folks, it seems like you've thought a decent amount about this - if you'd like to propose a change to how this works please open a rfc :) https://github.com/react-navigation/rfcs
