### ISSUE TITLE
React navigation: React Invariant Violation: Element type is invalid: Check the render method of `NavigationContainer`

### ISSUE THREAD

**Issue by nihp** [react-navigation/react-navigation#5296]
I am using the react-navigation version 3.0.0 and react 16.6.3. I am facing Invariant violation issue

"Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of `NavigationContainer`"

My sample code:

**App.js** 

```
import React from "react";
import { View, Text } from "react-native";
import { createStackNavigator, createAppContainer } from "react-navigation";
import HomeScreen from './screens/Home';

const AppNavigator = createStackNavigator({
  HomeScreen: {
    screen: HomeScreen
  }
});

const AppContainer = createAppContainer(AppNavigator);

export default class App extends React.Component {
  render() {
    return <AppContainer/>;
  }
}

```

**HomeScreen.js**

```
import React, { Component } from 'react';

import {
  Text,
  View
} from 'react-native';

export default class HomeScreen extends Component {
  render() {
      return (
        <View style={{ flex: 1, alignItems: "center", justifyContent: "center" }}>
          <Text>Home Screen</Text>
        </View>
      );
    }
}

```
**Version:**

"react": **"^16.6.3"**
"react-navigation": **"^3.0.0"**

![screen shot 2018-11-24 at 5 13 20 pm](https://user-images.githubusercontent.com/36992338/49134457-97182f80-f309-11e8-9202-a98382b35281.png)

**Comment by Durgaganesh-Palmtree** [comment]
I too experiencing the same issue for android. I just followed the example as given https://reactnavigation.org/docs/en/hello-react-navigation.html

```
import React from "react";
import { View, Text } from "react-native";
import { createStackNavigator, createAppContainer } from "react-navigation";

class HomeScreen extends React.Component {
  render() {
    return (
      <View style={{ flex: 1, alignItems: "center", justifyContent: "center" }}>
        <Text>Home Screen</Text>
      </View>
    );
  }
}

const AppNavigator = createStackNavigator({
  Home: {
    screen: HomeScreen
  }
});

export default createAppContainer(AppNavigator);
```

**Error  screen:**

![screenshot from 2018-11-27 14-53-43](https://user-images.githubusercontent.com/43339938/49134858-10645200-f30b-11e8-814c-cb97126c738e.png)

**Comment by brentvatne** [comment]
https://snack.expo.io/@notbrent/funny-churros

need a reproducible example, feel free to create a new issue when you have one

**Comment by nihp** [comment]
@brentvatne I have created a new ticket regarding this. I am facing a warning message as mentioned below.

So I tried to upgrade the react-navigation version. After updating this. I am getting the Invariant violation.

'Method `jumpToIndex` is deprecated. Please upgrade your code to use `jumpTo` instead.', 'Change your code from `jumpToIndex(2)` to `jumpTo(\'HOME SCREEN\').

You should only render one navigator explicitly in your app, and other navigators should by rendered by including them in that navigator. Full details at: https://reactnavigation.org/docs/common-mistakes.html#explicitly-rendering-more-than-one-navigator
