### ISSUE TITLE
setParams does not trigger while transitioning

### ISSUE THREAD

**Issue by scarlz** [react-navigation/react-navigation#5299]
### Current Behavior

- What code are you running and what is happening?

After migrating from 2.x to 3.x, any call to `setParams` from a screen being navigated to (either in the constructor, or lifecycle hook) is now deferred until the navigation transition completes.

This affects instances where the mounted screen will configure its own header title/buttons, as the header will now render incomplete until the transition is over.

### Expected Behavior

- What do you expect should be happening?

Setting params should not be deferred by any transition (as in 2.x).

### How to reproduce

React Navigation 2.x: https://snack.expo.io/rJ5AIWnCX
React Navigation 3.x: https://snack.expo.io/By--wZ3Rm

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.0.2
| react-native     | 0.57.4
| node             | 8.12.0
| yarn      | 1.9.4

**Comment by brentvatne** [comment]
I believe this is related to: https://github.com/react-navigation/react-navigation/issues/531 / https://github.com/react-navigation/react-navigation-stack/pull/49

**Comment by terrysahaidak** [comment]
I'm experiencing the same. We are using a custom HoC for passing some of our props to navigation via `setParams` on `componentDidMount`, with the react-navigation 2.18.3 it's just worked, but when I've updated to the latest one, it takes 1-3 second to set params and update the header (I'm using some of the params to conditionally display some things inside the header) after transition.

**Comment by brentvatne** [comment]
this is a known issue, you can see more discussion in https://github.com/react-navigation/react-navigation/issues/5318 and in particular why it works the way that it does. if you want to propose an alternative please open a rfc
