### ISSUE TITLE
Unable to npm install v3: 401 Unauthorized: @react-navigation/native@^3.0.1

### ISSUE THREAD

**Issue by superKalo** [react-navigation/react-navigation#5300]
### Current Behavior

For some reason, I can't npm install v3 of the package (I tried with any of the minor patches up to 3.0.2).

However, npm installing v2 works as a charm.

<img width="641" alt="screenshot 2018-11-28 at 17 25 18" src="https://user-images.githubusercontent.com/2548061/49162077-d1e28d80-f332-11e8-9aef-ff6e8ce5cc3b.png">

### Expected Behavior

To be able to install v3.

### How to reproduce

```
(sudo) npm install react-navigation@3.0.2
```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.0.2
| react-native     | Expo SDK 31 with React Native v0.57
| node             | v9.6.1
| npm or yarn      | npm v6.4.1

**Comment by zwigglers** [comment]
Logging into npm fixed this for me. Check npm whoami

**Comment by superKalo** [comment]
I don't know if react-navigation changed something, but after going back and forth... logging / logging out of npm, updating npm and fixing the [resolving EACCES permissions errors](https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally) finally fixed it for me! Thanks @zwigglers !

PS: It was very strange that this was the only package which caused an issue. When I npm installed v2 instead of v3, it was all good and all other packages installed as well. Strange!

**Comment by brentvatne** [comment]
we didn't change anything, it was on a bug on the npm side i imagine 😓
