### ISSUE TITLE
Typescript @types/react-navigation v3

### ISSUE THREAD

**Issue by nicolashemonic** [react-navigation/react-navigation#5302]
Hi,
You have done a great stuff for the v3 👍
I'm waiting the update of [Typescript definition](https://www.npmjs.com/package/@types/react-navigation) (actually v2.13.5) before upgrade my project.
Do you know if it's on the way ?
Thanks !

**Comment by brentvatne** [comment]
looks to be in progress here: https://github.com/react-navigation/react-navigation/pull/5276

let's discuss on that issue. happy to land that sometime in the next couple of days but we don't actually manage updating the types on definitelytyped, that's managed by the community
