### ISSUE TITLE
Goback always redirecting to initial screen

### ISSUE THREAD

**Issue by Er-rchydy** [react-navigation/react-navigation#5304]
I don't know why back button `this.props.navigation.goBack()` is always sending me to the initial screen even when i set `backBehaviour` to `none`. 
I found many issues talking about the same problem, but none of them got fixed, i don't know if there are a solution for this or not. in the documentation it says when you set  `backBehaviour` to `none` it will work, but it doesn't 

```
const MyApp = DrawerNavigator({
  Screen1: {
    screen: Screen1
  },
  Screen2: {
    screen: Screen2
  },
  Screen3: {
    screen: Screen3
  }
},
  {
    initialRouteName: 'Screen1',
    drawerPosition: 'left',
    backBehaviour: 'none',
    contentComponent: CustomDrawerContentComponent,
    drawerOpenRoute: 'DrawerOpen',
    drawerCloseRoute: 'DrawerClose',
    drawerToggleRoute: 'DrawerToggle'
  });
```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.18.2
| react-native     | 0.57.5
| node             | v8.9.3
| npm or yarn      | 6.2.0

**Comment by abn-volk** [comment]
@Er-rchydy: Have you tried `backBehavior` without the U?

**Comment by Er-rchydy** [comment]
@abn-volk  , @MoudiZd  i removed the `u`, i made it like this `backBehavior: 'none',` but it didn't work at all this time, it didn't load neither the previous screen neither the initial screen.

**Comment by brentvatne** [comment]
this is how it behaves. feel free to implement this rfc: https://github.com/react-navigation/rfcs/pull/2
