### ISSUE TITLE
Could not find method compileOnly()

### ISSUE THREAD

**Issue by maopixin** [react-navigation/react-navigation#5305]
I configure it according to official documents
then 
react-native run-android 
find error
![image](https://user-images.githubusercontent.com/30068481/49197760-19b4f380-f3cb-11e8-9fb5-acf7a169ab77.png)

MainActivity.java
```java
package com.mpx;

import com.facebook.react.ReactActivity;
// add start （react-native-gesture-handler）
import com.facebook.react.ReactActivityDelegate;
import com.facebook.react.ReactRootView;
import com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView;
// add end
public class MainActivity extends ReactActivity {

    /**
     * Returns the name of the main component registered from JavaScript.
     * This is used to schedule rendering of the component.
     */
    @Override
    protected String getMainComponentName() {
        return "mpx";
    }
    // add start （react-native-gesture-handler）
    @Override
    protected ReactActivityDelegate createReactActivityDelegate() {
        return new ReactActivityDelegate(this, getMainComponentName()) {
            @Override
            protected ReactRootView createRootView() {
                return new RNGestureHandlerEnabledRootView(MainActivity.this);
            }
        };
    }
    // add end
}
```

**Comment by maopixin** [comment]
my package.json
```json
{
  "name": "mpx",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.3.1",
    "react-native": "0.55.4",
    "react-native-gesture-handler": "^1.0.10",
    "react-native-scrollable-tab-view": "^0.10.0",
    "react-native-vector-icons": "^6.1.0",
    "react-navigation": "^3.0.2",
    "teaset": "^0.5.10"
  },
  "devDependencies": {
    "babel-jest": "23.6.0",
    "babel-preset-react-native": "4.0.1",
    "jest": "23.6.0",
    "react-test-renderer": "16.3.1"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

**Comment by brentvatne** [comment]
you can post this to react-native-gesture-handler if you like, but this isn't the right place for this issue.

**Comment by maopixin** [comment]
> 我通过以下更改解决了这个问题：
> 
> 1. 改变配置`android/build/gradle`。这是我的代码的一部分：
> 
> ```
> buildscript {
>     repositories {
>         jcenter()
>         google()
>     }
>     dependencies {
>         classpath 'com.android.tools.build:gradle:3.1.4'
> 
>         // NOTE: Do not place your application dependencies here; they belong
>         // in the individual module build.gradle files
>     }
> }
> 
> allprojects {
>     repositories {
>         mavenLocal()
>         jcenter()
>         maven {
>             // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
>             url "$rootDir/../node_modules/react-native/android"
>         }
>         google()
>     }
> }
> ```
> 添加`google()`到`buildscript`和`allprojects`，并更改类路径中的gradle版本。打开`...\node_modules\react-native-vector-icons\android\build.gradle`，你会发现classpath中的gradle版本是3.1.4，这就是我们需要进行此更改的原因。
> 
> 1. 在你的android项目中，打开`android/gradle/wrapper/gradle-wrapper.properties`，修改distributionUrl：
> 
> ```
> distributionUrl=https\://services.gradle.org/distributions/gradle-4.4-all.zip
> ```
> 由于此库依赖于3.1.4之上的gradle版本，因此我们应该设置一个新版本。
> 
> 重建项目，它终于有效了。



> Hey guys, I've just met the same issue after installing this library. The default version in package.json is 6.0.2.
> 
> I've solved this problem by below changes:
> 
> 1. change configuration in `android/build/gradle`. This is part of my code:
> 
> ```
> buildscript {
>     repositories {
>         jcenter()
>         google()
>     }
>     dependencies {
>         classpath 'com.android.tools.build:gradle:3.1.4'
> 
>         // NOTE: Do not place your application dependencies here; they belong
>         // in the individual module build.gradle files
>     }
> }
> 
> allprojects {
>     repositories {
>         mavenLocal()
>         jcenter()
>         maven {
>             // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
>             url "$rootDir/../node_modules/react-native/android"
>         }
>         google()
>     }
> }
> ```
> add `google()` to `buildscript` and `allprojects`, and change the gradle version in classpath. Open `...\node_modules\react-native-vector-icons\android\build.gradle`, you will find the gradle version in classpath is 3.1.4, that's why we need to make this change.
> 
> 1. In your android project, open `android/gradle/wrapper/gradle-wrapper.properties`, modify the distributionUrl:
> 
> ```
> distributionUrl=https\://services.gradle.org/distributions/gradle-4.4-all.zip
> ```
> Since this library depends on gradle version above 3.1.4, we should set a new version than that.
> 
> Rebuild the project, it finally works.
