### ISSUE TITLE
_react2.default.createContext is not a function

### ISSUE THREAD

**Issue by Nocturne-FFG** [react-navigation/react-navigation#5307]
## The issue tracker is reserved for bug reports only.

If you have a question, feature request, or an idea for improving the library or its related tools, please try one of the following resources:

- [Read the documentation](https://reactnavigation.org/)
- [Post an issue to the website repository if you'd like to see a documentation change](http://github.com/react-navigation/website)
- [Post a feature request to Canny](https://react-navigation.canny.io/feature-requests)
- [Write a RFC if you have ideas for how to implement a feature request](https://github.com/react-navigation/rfcs)
- [Get help on Discord chat (#react-navigation on Reactiflux)](https://discord.gg/4xEK3nD) or [on StackOverflow](https://stackoverflow.com/questions/tagged/react-navigation)
- Search for your issue - it may have already been answered or even fixed in the development branch. However, if you find that an old, closed issue still persists in the latest version, you should open a new issue.

Bugs with react-navigation must be reproducible *without any external libraries that operate on it*. This means that if you are attempting to use Redux or MobX with it and you think you have found a bug, you must be able to reproduce it without Redux or MobX in this report. Redux related issues belong in [react-navigation-redux-helpers](https://github.com/react-navigation/react-navigation-redux-helpers), and we do not have any first-class integration with MobX at the moment.

---

### Current Behavior

![image](https://user-images.githubusercontent.com/45280212/49222676-73430f80-f417-11e8-9310-54d48083700d.png)
![image](https://user-images.githubusercontent.com/45280212/49222872-12680700-f418-11e8-8ab3-9395d3a3d88a.png)

It used to work. This error occurred on the version of react-native 0.52.2. For some reason I can only use the version 0.52.2, so... please help.

### Expected Behavior

It should work properly

### How to reproduce

react-native init app
npm install react-navigation (3.0.2)
App.js :
`const AppStack = createStackNavigator({
    Home: initPage(Home),
    OrderDelivery: initPage(OrderDelivery)
}, {
    initialRouteName: "Home",
   	headerMode:'none',
    transitionConfig: () => ({
        screenInterpolator: StackViewStyleInterpolator.forHorizontal,
        transitionSpec:{
            duration:400,
            easing:Easing.out(Easing.poly(4))
        }
    })
});`
### Your Environment
react : 16.2.0
react-native : 0.52.2
react-navigation : 3.0.2

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!

**Comment by Nocturne-FFG** [comment]
Sorry! But after I checked it out for a night, I have solved this problem  😁

**Comment by Salman98** [comment]
how you resolve it ?

**Comment by BotaniQue** [comment]
In my case this was a bad combination of modules. So I've created a new project from scratch, adding Expo, react-native, react-navigation – and then it worked.

**Comment by AE0011** [comment]
If your react version is below 16.3 this would happen because context doesn't exist below 16.3
```
"react": "^16.3.1",
 "react-native": "^0.55.4",
```

**Comment by mooniitt** [comment]
I solve this problem is update "react": "16.2.0" to "16.3.1"
