### ISSUE TITLE
disable swipe from createDrawerNavigation

### ISSUE THREAD

**Issue by adviraj** [react-navigation/react-navigation#5308]
I want to disable sidemen or drawer from DrawerNavigation.it's not working in iOS.

here is my code so please me know how can I resolved it.

Index.js -------

import { createDrawerNavigator, createAppContainer } from 'react-navigation';
import App from './App';
import SideMenu from './src/components/SideMenu';

const drawernav = createDrawerNavigator({
    App: {
      screen: App
    }
  }, {
    contentComponent: SideMenu,
    drawerWidth: Dimensions.get('window').width - 100, 
    drawerBackgroundColor:'#e91e63',
    drawerType:'back',
    drawerLockMode: 'locked-closed',
    gesturesEnabled:'false'
});

const SideMenuApp = createAppContainer(drawernav);

AppRegistry.registerComponent(appName, () => SideMenuApp);

App.js is here ---

class LoginPage extends Component {

  static navigationOptions = {
    header:null,
    drawerLockMode: 'locked-closed',
    gesturesEnabled:false
  };
  
  render() {
    return (
      <View style={{ flex:1}}>
        <Text style={{color: 'blue', fontSize: 30, marginTop:40, textAlign:'center'}}>
          Login Screen
        </Text>
      </View>
    );
  }
}

class SignupPage extends Component {
  render() {
    return (
      <View>
        <Text>Hello World App</Text>
      </View>
    );
  }
}

export default  createStackNavigator({
  LoginPage:{
    screen:LoginPage
  },
  SignupPage: {
    screen: SignupPage
  }
},{
  initialRouteName: 'LoginPage'
});

**Comment by brentvatne** [comment]
update to the latest version, and follow the issue template next time please
