### ISSUE TITLE
Add headings and separators to drawer navigation?

### ISSUE THREAD

**Issue by FrazeColder** [react-navigation/react-navigation#5311]
Hey Guys,

I have been searching quite a lot now but haven't find any solution yet.. I want to have a drawer navigation which contains two separators and two headings so I can give the screens a heading besides the actual screen title. 

An example is the Google Gmail app navigation:
https://phip1611.de/wp-content/uploads/2014/11/Vergleich-Inbox-und-Gmail-Android-App-Tablet-Posteingang-mit-Navi-Men%C3%BC-hochformat.png

You guys have any ideas or suggestions?

Kind regards and Thank You!

**Comment by brentvatne** [comment]
hi there! this is a question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.
