### ISSUE TITLE
Compile issue when using react navigation v3 with haul v1.0.0-rc.9

### ISSUE THREAD

**Issue by yongching** [react-navigation/react-navigation#5313]
### Current Behavior

I'm trying to use `react-navigation v3.0.2` together with `haul v1.0.0-rc.9` and bumped into the following issues:

It happens whenever I `import { createStackNavigator } from 'react-navigation`
And this is not happening in version 2 back then.

<img width="559" alt="screenshot 2018-11-30 at 11 49 07 am" src="https://user-images.githubusercontent.com/10132189/49268387-2a806a80-f49a-11e8-8a29-e53c7d619af7.png">

Here'ss the link to the err log generated by haul https://codeshare.io/GkPDqp

I guess the error was there due to no parser is available for `NavigationContext.Provider`, but I'm not sure how can I fix it. Hope someone could help.

<img width="512" alt="screenshot 2018-11-30 at 12 25 00 pm" src="https://user-images.githubusercontent.com/10132189/49268551-05402c00-f49b-11e8-9710-d71fd6103a45.png">

### Expected Behavior

It should be compiled without any errors like the screenshot below:

<img width="305" alt="screenshot 2018-11-30 at 12 20 46 pm" src="https://user-images.githubusercontent.com/10132189/49268419-69aebb80-f49a-11e8-8e0c-89307ab95535.png">

### How to reproduce
1. clone this repo https://github.com/yongching/react-navigation-v3-with-haul
2. run yarn && yarn ioshaul

### My Environment

| software         | version
| ---------------- | -------
| haul | 1.0.0-rc.9
| react-navigation | 3.0.2
| react-native     | 0.57.7
| node             | v10.11.0
| yarn      | 1.10.1

**Comment by brentvatne** [comment]
as per https://github.com/callstack/haul/issues/502#issuecomment-443130900

> What you can do is send us PR with @react-navigation added to the list, or adjust your babel-loader config following this guide https://github.com/callstack/haul/blob/next/docs/Configuration.md

so either send haul a PR or change your config
