### ISSUE TITLE
Exporting AppContainer as React Class not working in non-debugging mode. (Objects are not valid...)

### ISSUE THREAD

**Issue by stonecold123** [react-navigation/react-navigation#5317]
### Current Behavior

This error comes up when debugging is off:

![Image of Yaktocat](https://i.imgur.com/WrA2M9m.png)

### Expected Behavior

I expect the app to work when debugging is off.

### How to Reproduce

I export the `AppContainer` as a react class like this:

App.tsx
````
const AppNavigator = createStackNavigator(
    {....},
    {
        initialRouteName: "Home",
    }
);

const AppContainer = createAppContainer(AppNavigator);

export default class App extends React.Component{
    render(){
        return  <AppContainer ref={nav =>  this.navigator = nav } />
    }
}
````

index.js

````
import {AppRegistry} from 'react-native';
import App from './src/App';
import {name as appName} from './app.json';
AppRegistry.registerComponent(appName, () => App);
````

It works fine when debugging is on. However, when debugging is off, it throws the `Objects are not valid as a React child` error.

I have tried both on a real device and simulator. Both have the same error. It is confusing because the document suggests that exporting `AppContainer` as a React class is possible : https://reactnavigation.org/docs/en/app-containers.html

However, there's no error when the `AppContainer` is exported like this:

````
const AppContainer = createAppContainer(AppNavigator);

export default AppContainer
````

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.0.4
| react-native     | 0.57.7
| node             | 10.7
 npm or yarn      | npm

**Comment by brentvatne** [comment]
needs runnable reproducible example, the code you shared is not enough to reproduce. i suspect the problem is actually that you didn't import the component used for your initial route in the stack properly. feel free to create new issue with a link to a github repo that reproduces it
