### ISSUE TITLE
Nested Stacks (with nested Tabs) not honoring navigationOption's title in 2.x (worked in 1.x)

### ISSUE THREAD

**Issue by dajaffe** [react-navigation/react-navigation#5319]
### Current Behavior
Sub-stack header titles are not functioning in 2.x as they did in 1.x.

A TabNavigator (Tab A) as the very top level screen of the application. One screen in this Tab A is a Stack (Stack A). Stack A contains various routes, either to simple screens or other stacks. In the default screen for Stack A, something is pressed which takes us to a route pointing to screen Stack B. The bar for Tab A is hidden.

In Stack B, the default route is another TabNavigator (Tab B), containing various simple screens. This works fine. **The issue is Stack B is configured to have a title for the header, which is not showing.** 

**This worked fine in react-navigation 1.x.**

### Expected Behavior
Nested Stacks should have the navigationOptions.title displayed in 2.x as they do in 1.x

### How to reproduce
**react-navigation 2.x (broken)**
Snack: https://snack.expo.io/@djaffe89/tab-stack-tab-stack
**react-navigation 1.x (working)**
Snack: https://snack.expo.io/@djaffe89/tab-stack-tab-stack-1

1. Swipe to '2'
2. Press 'Screen to Inner Tabs'
3. Notice that the 'InnerStack' title set on the Tab screen in this sub-stack is not displaying in the header on the 2.x Snack link, but does display for the 1.x Snack link.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.0.0 (broken), 1.5.13 (working)
| react-native     | N/A - Reproduced on Snack
| node             | N/A - Reproduced on Snack
| npm or yarn      | N/A - Reproduced on Snack

**Comment by brentvatne** [comment]
https://reactnavigation.org/docs/en/navigation-options-resolution.html

**Comment by dajaffe** [comment]
Got it - I misunderstood the shallow options piece when I was reading that earlier. Switched to setting it per the resolution documentation and it's working great. Thanks!

**Comment by dajaffe** [comment]
@brentvatne One question about using the new navigationOptions strategy. I had been dynamically setting the title later in a componentDidMount / componentDidUpdate after something loads. I had been following the method in this documentation: https://reactnavigation.org/docs/en/headers.html

`this.props.navigation.setParams({title: 'New Title'})}`

After debugging the code added following that options resolution guide, it doesn't appear the stacks' navigation options receive those new params. Is there something I'm missing? I can put a snack together if needed.

**Comment by brentvatne** [comment]
you could do something like this:

```
function findActiveRoute(state) {
  return state.routes[state.routes.index];
}

function paramsForActiveRoute(state) {
  return findActiveRoutes(state).params || {};
}

// later
paramsForActiveRoute(state).title
```

might also want to consider just reorganizing how you layout your navigators
