### ISSUE TITLE
createTopTabNavigator does not exist, only createMaterialTopTabNavigator

### ISSUE THREAD

**Issue by Morriz** [react-navigation/react-navigation#5321]
This is not a feature request, I am merely stating an obvious omission that is a breaking change:

Like the title says: createTopTabNavigator does not exist, only createMaterialTopTabNavigator.
And there is no info as to why not. There used to be the possibility to render a TabBarBottom with position 'top'. That has been made impossible.

Please don't break our apps!

And please don't make me fill in your template as this is a simple observation.

**Comment by brentvatne** [comment]
createMaterialTopTabNavigator is createTopTabNavigator renamed, I believe you can still render tab bar bottom with it as it supports both `tabBarPosition` and `tabBarComponent`

**Comment by AE0011** [comment]
In previous version we could choose position and component of tab view and we could put TabBarBottom in top instead of bottom! but now for top there is just MaterialTop which cant be customize as Bottom one.

Totally i want a TopTab which is not material!! how could i implement this?

**Comment by brentvatne** [comment]
you can use `tabBarComponent` to provide any component you'd like for the tab bar https://reactnavigation.org/docs/en/material-top-tab-navigator.html#tabnavigatorconfig

**Comment by SrBrahma** [comment]
I have no clue on why there isn't a single createTabNavigator and createMaterialTabNavigator and a position prop for both components. It just doesn't make any sense. Sorry for commenting it here.
