### ISSUE TITLE
Expected a string - CHeck the render method of 'TabBarIcon'

### ISSUE THREAD

**Issue by rssluca** [react-navigation/react-navigation#5323]
## Current Behavior

Hello,
Using react-native-firebase starter pack.

for some reason I cannot setup tab icons. Error below.

![image](https://user-images.githubusercontent.com/11591556/49351485-cebb1900-f707-11e8-9130-7e1bd71b2031.png)

If I remove the tabBarIcon option the app works fine.

Complete error output at the bottom.

### Code
Code is similar to example in https://reactnavigation.org/docs/en/tab-based-navigation.html

```
const MainStack = createAppContainer(
  createBottomTabNavigator(
    {
      Home: { screen: HomeScreen },
      Search: { screen: SearchScreen },
      Alerts: { screen: AlertsScreen },
      Settings: { screen: SettingsScreen }
    },
    {
      initialRouteName: "Search",
      defaultNavigationOptions: ({ navigation }) => ({
        tabBarIcon: ({ focused, horizontal, tintColor }) => {
          const { routeName } = navigation.state;
          let iconName;
          if (routeName === "Home") {
            iconName = `${focused ? "ios" : "md"}-home`;
          } else if (routeName === "Search") {
            iconName = `${focused ? "ios" : "md"}-search`;
          } else if (routeName === "Alerts") {
            iconName = `${focused ? "ios" : "md"}-list-box`;
          } else if (routeName === "Settings") {
            iconName = `${focused ? "ios" : "md"}-settings`;
          }

          return (
            <Icon
              name={iconName}
              size={horizontal ? 20 : 25}
              color={tintColor}
            />
          );
        }
      }),
      tabBarComponent: TabBarBottom,
      tabBarPosition: "top",
      tabBarOptions: {
        activeTintColor: "#3498db",
        inactiveTintColor: "gray"
      },
      animationEnabled: false,
      swipeEnabled: false
    }
  )
);
```

### Your Environment
```
{
  "name": "####",
  "version": "5.1.0",
  "private": true,
  "devDependencies": {
    "babel-jest": "23.6.0",
    "fs-extra": "^6.0.1",
    "jest": "23.6.0",
    "metro-react-native-babel-preset": "0.48.0",
    "react-test-renderer": "16.5.0",
    "replace-in-file": "^3.4.0"
  },
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "apk": "cd android && ./gradlew assembleRelease",
    "rename": "node ./bin/rename.js",
    "start": "react-native start",
    "test": "jest"
  },
  "jest": {
    "preset": "react-native"
  },
  "dependencies": {
    "axios": "^0.18.0",
    "react": "16.5.0",
    "react-native": "0.57.1",
    "react-native-elements": "^0.19.1",
    "react-native-firebase": "^5.1.1",
    "react-native-gesture-handler": "^1.0.10",
    "react-native-vector-icons": "^6.1.0",
    "react-navigation": "^3.0.1"
  }
}
```

### Complete error info 

 Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `TabBarIcon`.

This error is located at:
    in RCTView (at View.js:44)
    in AnimatedComponent (at CrossFadeIcon.js:34)
    in RCTView (at View.js:44)
    in TabBarIcon (at BottomTabBar.js:151)
    in RCTView (at View.js:44)
    in TouchableWithoutFeedback (at BottomTabBar.js:63)
    in TouchableWithoutFeedbackWrapper (at BottomTabBar.js:237)
    in RCTView (at View.js:44)
    in AnimatedComponent (at react-native-safe-area-view/index.js:134)
    in SafeView (at withOrientation.js:54)
    in withOrientation (at BottomTabBar.js:219)
    in TabBarBottom (at withDimensions.js:32)
    in withDimensions(TabBarBottom) (at createBottomTabNavigator.js:72)
    in RCTView (at View.js:44)
    in TabNavigationView (at createTabNavigator.js:197)
    in NavigationView (at createNavigator.js:62)
    in Navigator (at createAppContainer.js:388)
    in NavigationContainer (at SceneView.js:9)
    in SceneView (at StackViewLayout.js:774)
    in RCTView (at View.js:44)
    in AnimatedComponent (at StackViewCard.js:69)
    in RCTView (at View.js:44)
    in AnimatedComponent (at screens.native.js:58)
    in Screen (at StackViewCard.js:57)
    in Card (at createPointerEventsContainer.js:27)
    in Container (at StackViewLayout.js:831)
    in RCTView (at View.js:44)
    in ScreenContainer (at StackViewLayout.js:300)
    in RCTView (at View.js:44)
    in AnimatedComponent (at StackViewLayout.js:298)
    in Handler (at StackViewLayout.js:279)
    in StackViewLayout (at withOrientation.js:30)
    in withOrientation (at StackView.js:96)
    in RCTView (at View.js:44)
    in Transitioner (at StackView.js:22)
    in StackView (at createNavigator.js:62)
    in Navigator (at createKeyboardAwareNavigator.js:12)
    in KeyboardAwareNavigator (at createAppContainer.js:388)
    in NavigationContainer (at App.js:99)
    in App (at renderApplication.js:34)
    in RCTView (at View.js:44)
    in RCTView (at View.js:44)
    in AppContainer (at renderApplication.js:33)

createFiberFromElement
    index.bundle?platform=ios&dev=true&minify=false:12275:26
reconcileSingleElement
    index.bundle?platform=ios&dev=true&minify=false:14881:51
reconcileChildFibers
    index.bundle?platform=ios&dev=true&minify=false:14928:63
reconcileChildren
    index.bundle?platform=ios&dev=true&minify=false:15325:50
updateHostComponent
    index.bundle?platform=ios&dev=true&minify=false:15555:26
performUnitOfWork
    index.bundle?platform=ios&dev=true&minify=false:18127:27
workLoop
    index.bundle?platform=ios&dev=true&minify=false:18159:47
renderRoot
    index.bundle?platform=ios&dev=true&minify=false:18222:21
performWorkOnRoot
    index.bundle?platform=ios&dev=true&minify=false:18913:23
performWork
    index.bundle?platform=ios&dev=true&minify=false:18837:30
performSyncWork
    index.bundle?platform=ios&dev=true&minify=false:18812:20
requestWork
    index.bundle?platform=ios&dev=true&minify=false:18710:26
scheduleWork
    index.bundle?platform=ios&dev=true&minify=false:18570:22
scheduleRootUpdate
    index.bundle?platform=ios&dev=true&minify=false:19101:21
render
    index.bundle?platform=ios&dev=true&minify=false:19530:26
renderApplication
    index.bundle?platform=ios&dev=true&minify=false:65923:59
run
    index.bundle?platform=ios&dev=true&minify=false:65596:28
runApplication
    index.bundle?platform=ios&dev=true&minify=false:65646:28
__callFunction
    index.bundle?platform=ios&dev=true&minify=false:2783:49
<unknown>
    index.bundle?platform=ios&dev=true&minify=false:2556:31
__guard
    index.bundle?platform=ios&dev=true&minify=false:2737:15
callFunctionReturnFlushedQueue
    index.bundle?platform=ios&dev=true&minify=false:2555:21

**Comment by Naeoth** [comment]
Is TabBarBottom a custom TabBar ? If yes, share your class for more help.

**Comment by vonovak** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and we'll be happy to review it!
