### ISSUE TITLE
Losing pinch gesture state

### ISSUE THREAD

**Issue by ben-snaize** [react-navigation/react-navigation#5326]
Hi,

Since migrating from v2 to v3, I've observed the following issue. It is oddly specific and involves a combination of the underlying `react-native-gesture-handler` introduced in v3, `react-native-photo-view` and `react-swipeable-views-native`.

On Android, it's all fine. However on iOS, no 'pinch to scale' action works if the `PhotoView` is placed inside a swiper view. This works on v2, you can try the below by reverting and switching out the `createAppContainer` call.

It's also worth noting that *not* putting the `PhotoView` in the swiper results in correct behaviour.

Any advice on whether this is something that can be fixed in React Navigation directly or reported to `react-native-gesture-handler`?

### Current Behavior

Pinch to scale is not permitted

### Expected Behavior

Pinch to scale is permitted, `PhotoView` scales accordingly.

### How to reproduce

* Init RN App
* Install dependencies below
* Use the following `App.js`

#### App.js
```
import React, {Component} from 'react';
import {createStackNavigator, createAppContainer} from "react-navigation";
// v2: import {createStackNavigator} from "react-navigation";
import SwipeableViews from 'react-swipeable-views-native';
import PhotoView from 'react-native-photo-view';

class HomeScreen extends Component {
  render () {
    return (
        <SwipeableViews
          style={{ flex: 1 }}
          threshold={1}>
          <PhotoView
            source={{
              uri: 'http://fillmurray.com/500/500'
            }}
            minimumZoomScale={1}
            maximumZoomScale={3}
            androidScaleType='center'
            resizeMode='contain'
            style={{
              height: 500,
              width: 500
            }}
          />
          <PhotoView
            source={{
              uri: 'http://placecage.com/500/500'
            }}
            minimumZoomScale={1}
            maximumZoomScale={3}
            androidScaleType='center'
            resizeMode='contain'
            style={{
              height: 500,
              width: 500
            }}
          />            
        </SwipeableViews>
    )
  }
}

const StackNavigator = createStackNavigator({
  Home: {
    screen: HomeScreen
  }
});

module.exports = createAppContainer(StackNavigator)
// v2: module.exports = StackNavigator
```
#### package.json

```
...
    "react-native-gesture-handler": "^1.0.10",
    "react-native-photo-view": "^1.5.2",
    "react-navigation": "^3.0.4",
    "react-swipeable-views-native": "^0.13.2"
...
```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^3.0.4
| react-native     | 0.57.7
| node             | 8.12
| npm or yarn      | npm 6.41

**Comment by ben-snaize** [comment]
If I’m honest I’m gonna struggle for time here as I’ve already put together the demo above. It might be a case or pinch responder inside of a horizontal scroll view, but there could be other factors. 

I’ll see what I can do but my fear is that it ends up being a non starter due to some setting in one of the dependencies conflicting with this library.

**Comment by brentvatne** [comment]
@ben-snaize - sorry, we are all short on time - it's important when reporting a bug to isolate it to only the dependencies from the project itself otherwise we have no way of being sure that the bug is actually in this project

**Comment by ben-snaize** [comment]
Update. Doesn't repro with a single `ScrollView` set to horizontal and with a zoom scale...

**Comment by ben-snaize** [comment]
@brentvatne I've decided to disable the scroll on this, and use pagination only. Closing.
