### ISSUE TITLE
Expected a string - Check the render method of 'TabBarIcon' - Ref. 5323

### ISSUE THREAD

**Issue by rssluca** [react-navigation/react-navigation#5327]
Hi,

This is from issue 5323. I created a git repo for testing as requested (apology for not having done this earlier)

https://github.com/rssluca/rnf-test.git

Its the react-native-firebase starter pack + my code - issue is in app.js file.

### Error message

Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of TabBarIcon.

**Comment by rssluca** [comment]
Hi again, 

It was my fault, I was not importing vector icons properly. 

Sorry for the pain!

**Comment by mecoFarid** [comment]
@rssluca I'm having the same issue. What do you mean by "you weren't importing vectors icons properly"?

**Comment by emreozdincer** [comment]
@mecoFarid I had the same issue. Skipped it with
 
`npm install react-native-vector-icons --save`

```
import Icon from 'react-native-vector-icons/Ionicons';

...

const { routeName } = navigation.state;
let iconName;
if (routeName === 'Home') {
  iconName = `ios-information-circle${focused ? '' : '-outline'}`;
} else if (routeName === 'Settings') {
  iconName = `ios-options`;
}

return <Icon name={iconName} size={25} color={tintColor} />;
```
