### ISSUE TITLE
How to make sure a Drawer Navigation is completely removed when I navigate to another BottomTabNavigator ?

### ISSUE THREAD

**Issue by moussasarr** [react-navigation/react-navigation#5329]
I have a BottomTabNavigator which, contains another BottomTabNavigator and two DrawerNavigator s. 

One of the DrawerNavigators represents the authenticated state. I just implemented a log out button in this drawerNavigation. The button purges the redux state and navigates to the BottomTabNavigator, more specifically, to the Login route of the Welcome navigator.

However, once in the Welcome Navigato after logout, the authenticated Drawer shows up when I try to navigate to another route of the BottomTabNavigator. 

I am not sure why this is happening. When I refresh the expo project, I realize that indeed the application is in a non-authenticated state.

Is there a way to make sure the Authenticated Drawer Navigator does not show up when I log out ?

Here is my main navigator:

    import React, { Component } from 'react';
    import {
      AppRegistry,
      View,
      SafeAreaView,
      Button,
      AsyncStorage,
      TouchableOpacity,
      Text,
    } from 'react-native';
    import { Ionicons } from '@expo/vector-icons';
    import { PersistGate } from 'redux-persist/integration/react';
    import {
      createBottomTabNavigator,
      createSwitchNavigator,
      createDrawerNavigator,
      createStackNavigator,
      DrawerItems,

     } from 'react-navigation';
    import { Provider } from 'react-redux';
    import Welcome from './screens/Welcome';
    import Register from './screens/RegisterScreen';
    import Login from './screens/LoginScreen';
    import Home from './screens/Home';
    import Events from './screens/Events';
    import Board from './screens/Board';
    import HomePage from './screens/HomePage';
    import SettingsScreen from './screens/BusinessSettings';
    import BusinessEvents from './screens/BusinessEvents';
    import EventListings from './screens/EventListings';
    import BusinessListings from './screens/BusinessListings';
    import Business from './screens/Business';
    import BusinessForm from './screens/BusinessForm';
    import EventForm from './screens/EventForm';
    import Logout from './screens/Logout';
    import { persistor, store } from './store';
    
    
    const MainNavigator = createBottomTabNavigator(
      {
        Welcome: createBottomTabNavigator({
          Welcome: Welcome,
          Login: Login,
          Register: Register,
          Board: Board,
        }),
    
        Home: createDrawerNavigator({
          Home: {
            screen: Home,
          },
          Events: {
            screen: Events,
          },
          Business: {
            screen: Business
          }
        }),
        HomePage: createDrawerNavigator({
          HomePage: {
            screen: HomePage,
          },
          Settings: {
            screen: SettingsScreen,
          },
          EventListings: {
            screen: EventListings
          },
    
          EventForm: {
            screen: EventForm
          },
    
          BusinessEvents: {
            screen: BusinessEvents
          },
          BusinessListings: {
            screen: BusinessListings
          },
          NewBusiness: {
            screen: BusinessForm
          },
          Business: {
            screen: Business
          }
        }, {
    
          contentComponent: (props) => (
            <View style={{ flex:1 }}>
             <SafeAreaView forceInset={{ top: 'always', horizontal: 'never' }}>
               <DrawerItems {...props} />
               <TouchableOpacity style={{  flexDirection: 'row', marginLeft: '8%', paddingTop: '2%' }} onPress={ async () => {
                 await AsyncStorage.clear();
                 await persistor.purge();
                 props.navigation.navigate("Welcome");
               }}>
                   <Ionicons name="ios-log-out-outline" size={24} color="#053541" /><Text style={{ marginLeft: '14%', fontWeight: 'bold', color: 'black' }}>Log Out</Text>
               </TouchableOpacity>
             </SafeAreaView>
       </View>
         ),
         drawerOpenRoute: 'DrawerOpen',
         drawerCloseRoute: 'DrawerClose',
         drawerToggleRoute: 'DrawerToggle'
    
        })
      },
      {
       headerMode: 'none',
       navigationOptions: {
            header: null,
            tabBarVisible: false,
            headerVisible: false,
            headerMode: 'none',
      },
        tabBarVisible: false,
        swipeEnabled: false,
        animationEnabled: false,
        lazy: true,
        transitionConfig: () => ({
          transitionSpec: {
            duration: 0,
          },
        }),
    
        /* Other configuration remains unchanged */
      }
    );
    
    export default class App extends Component {
      render() {
        return (
          <Provider store={store}>
            <PersistGate loading={null} persistor={persistor}>
              <MainNavigator />
            </PersistGate>
          </Provider>
        );
      }
    };

**Comment by samfriend** [comment]
I have the same problem after upgraded to 3.x

'Drawer Closed' event will also navigate back to the Tab in which the Drawer reside. 

E.g. I have 4 tabs, tab1 (with a drawer), tab2, tab3, and tab4

When I am in tab1, I opened the drawer, and then close the drawer, then I press tab2 to browser other stuffs.... suddenly, react-navigation automatically jump back to tab1 (things begin to mess up, the buttons, events...)

I think this is caused by the drawer-close-animation-ended -> navigate-to-something-previous

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!

**Comment by Daimension** [comment]
> I have the same problem after upgraded to 3.x
> 
> 'Drawer Closed' event will also navigate back to the Tab in which the Drawer reside.
> 
> E.g. I have 4 tabs, tab1 (with a drawer), tab2, tab3, and tab4
> 
> When I am in tab1, I opened the drawer, and then close the drawer, then I press tab2 to browser other stuffs.... suddenly, react-navigation automatically jump back to tab1 (things begin to mess up, the buttons, events...)
> 
> I think this is caused by the drawer-close-animation-ended -> navigate-to-something-previous

facing same issue after upgrade to v3, also with drawer open event

**Comment by Daimension** [comment]
I have forked react-navigation-drawer and trying fix it for myself, take a look at it if you want, use at your own risk(not well tested) ~_~

also fixed animation sluggish problem, as described below
https://github.com/react-navigation/react-navigation/issues/5287
