### ISSUE TITLE
Unable to resolve react-navigation

### ISSUE THREAD

**Issue by jsrsonu** [react-navigation/react-navigation#5337]
When i create a new project using react-native init test, it works fine. However when i add react-navigation library and try stackNavigator , i got an error.Please help me on this.Below are my configuration.Attaching the code and error screenshots.
![cli-error](https://user-images.githubusercontent.com/36218484/49502558-51c0a880-f89b-11e8-94ce-d973f87705db.png)
![simulator](https://user-images.githubusercontent.com/36218484/49502567-584f2000-f89b-11e8-8c6c-5dc6d72030c0.jpg)
![code](https://user-images.githubusercontent.com/36218484/49502569-58e7b680-f89b-11e8-91ce-5ae5e8d0d219.jpg)

 "react": "16.6.1",
 "react-native": "0.57.7",
 "react-native-gesture-handler": "^1.0.10",
 "react-navigation": "^3.0.2"

 react-native-cli: 2.0.1
node - v8.9.3
npm - 6.0.1

**Comment by FirdousNath** [comment]
With 3.0, just use createStackNavigator and you are good to go
```
import {createStackNavigator} from 'react-navigation'

 const AppStackNavigator = createStackNavigator({
  Login: Login,
  Home: Home
})
```

**Comment by iiiwower** [comment]
Cannot read property 'State' of undefined
<unknown>
    D:\reactNative\sss\node_modules\react-native-gesture-handler\GestureHandler.js:54:37
loadModuleImplementation
    D:\reactNative\sss\node_modules\metro\src\lib\polyfills\require.js:319:4
guardedLoadModule
    D:\reactNative\sss\node_modules\metro\src\lib\polyfills\require.js:214:11
metroRequire
    D:\reactNative\sss\node_modules\metro\src\lib\polyfills\require.js:136:6
<unknown>
    D:\reactNative\sss\node_modules\react-native-gesture-handler\Swipeable.js:11
loadModuleImplementation
    D:\reactNative\sss\node_modules\metro\src\lib\polyfills\require.js:319:4
guardedLoadModule
    D:\reactNative\sss\node_modules\metro\src\lib\polyfills\require.js:214:11
metroRequire
    D:\reactNative\sss\node_modules\metro\src\lib\polyfills\require.js:136:6
<unknown>
    D:\reactNative\sss\node_modules\react-native-gesture-handler\index.js:1
loadModuleImplementation
    D:\reactNative\sss\node_modules\metro\src\lib\polyfills\require.js:319:4

**Comment by FirdousNath** [comment]
run` npm install react-native-gesture-handler` and error will go away

**Comment by brentvatne** [comment]
installation steps here: https://reactnavigation.org/docs/en/getting-started.html#installation
