### ISSUE TITLE
Providing an action to `navigate` is never dispatched, while trying to replace a screen

### ISSUE THREAD

**Issue by janhesters** [react-navigation/react-navigation#5338]
---

### Current Behavior

- What code are you running and what is happening?

I have a Stack with three screens (Root, First and Second). I'm trying to follow [the docs](https://reactnavigation.org/docs/en/navigation-actions.html#navigate) to navigate to a screen while simultaneously dispatching a navigation action.

The goal is to navigate from the root screen to the first screen. After wards navigate from the First screen to the Second screen, but have the back button point to the HomeScreen again (as if the First screen never was in the stack in the first place).

Using the action parameter I'm trying to dispatch a stack action to reset the state to the desired state while the animation is playing.

The current behaviour is dependent on the way I attempt this. In the demo below you can read, see and try out all my attempts (on `FirstScreen`). **It seems like the StackAction provided is never dispatched.**

### Expected Behavior

- What do you expect should be happening?

What should be happening is the animation should play out and you should be able to directly go back from the SecondScreen to the HomeScreen, without crossing the FirstScreen.
~~- Include a screenshot if it makes sense.~~

### How to reproduce

See my attempts at demo and corresponding bugs in the demo. 

https://snack.expo.io/SklozIBJE

If this isn't a bug and I'm just not capable of understanding the API could you kindly give a example how one would achieve this? (It's entirely possible that this is not a bug, but I'm just bad at understanding the docs).

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.18 and above
| react-native     | 0.5.7.1
| node             | v9.4.0
| npm or yarn      | 6.4.1

**Comment by brentvatne** [comment]
you can use `getStateForAction` to implement a way to control exactly what the state is reset to. imo this is actually how reset should work, rather than it dispatching actions it should just say set the state to this. see FirstScreen and SecondScreen in https://snack.expo.io/@notbrent/awkward-peach for an example. i updated this to 3.x and did not test in 2.x because i don't take issues for 2.x anymore.

**Comment by brentvatne** [comment]
also just wanted to mention that in the example 2 the replace action will attempt to replace SecondScreen with SecondScreen, so that's why you don't see anything happen

**Comment by janhesters** [comment]
@brentvatne Thank you for your help!

**Comment by brentvatne** [comment]
hmm it seems like my snack doesn't show the latest change i made to it :( if you need help figuring it out i can rewrite it, sorry

**Comment by brentvatne** [comment]
went ahead and rewrote it, should be fine now at https://snack.expo.io/@notbrent/awkward-peach

**Comment by janhesters** [comment]
@brentvatne Wow, thank you. This helps me a lot!😊
