### ISSUE TITLE
onNavigationStateChange error in v3

### ISSUE THREAD

**Issue by jbrown** [react-navigation/react-navigation#5339]
### Current Behavior

- What code are you running and what is happening?

```javascript
const AppContainer = createAppContainer(AppStackNavigator);

// gets the current screen from navigation state
function getActiveRouteName(navigationState) {
  console.log('getActiveRouteName', navigationState);
  if (!navigationState) {
    return null;
  }
  const route = navigationState.routes[navigationState.index];
  // dive into nested navigators
  if (route.routes) {
    return getActiveRouteName(route);
  }
  return route.routeName;
}

export default class App extends React.Component {
  render() {
    return (
      <AppContainer
        onNavigationStateChange={(prevState, currentState) => {
          const currentScreen = getActiveRouteName(currentState);
          const prevScreen = getActiveRouteName(prevState);

          if (prevScreen !== currentScreen) {
            Segment.screen(currentScreen);
          }
        }} />
    );
  }
}
```

### Expected Behavior

In v2 this used to work just fine, and I was able to track screens.

The screen tracking example has **not** been updated for the new App container changes in v3.

### How to reproduce

I'm using the [screen tracking](https://reactnavigation.org/docs/en/screen-tracking.html#listening-to-state-changes) code verbatim and getting this error:

`Error: Error: This navigator has both navigation and container props, so it is unclear if it should own its own state. Remove props: "onNavigationStateChange" if the navigator should get its state from the navigation prop. If the navigator should maintain its own state, do not pass a navigation prop.`

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | `v3.0.5`
| react-native     | `https://github.com/expo/react-native/archive/sdk-31.0.1.tar.gz`
| node             | `v9.3.0`
| npm or yarn      | `yarn v1.12.3`

**Comment by brentvatne** [comment]
can you post a runnable example on snack.expo.io?

**Comment by eriveltonelias** [comment]
Hi @jbrown! 

as @brentvatne said, we require to have a runnable example to help you but I created an example that shows it working with some updates on your code:

https://snack.expo.io/@eriveltonelias/hello-react-navigation

@brentvatne I'll send a PR on our docs to fix this example ( on V3 ) :)

**Comment by jasan-s** [comment]
i have the following code and the console log never outpus on screen changes:
```
import React, { Component } from 'react'
import { Platform } from 'react-native'
import RootNav from '../Navigation/RootNav'
import { name as appName } from '../../app.json'

// DYNAMIC LINKING prefix for react-navigation also add URL Type in Xcode
// on Android, the URI prefix typically contains a host in addition to scheme
const prefix =
  Platform.OS === 'android' ? `${appName}://${appName}/` : `${appName}://`

export default class Root extends Component {
  render() {
    return (
      <RootNav
        screenProps={{ name: 'hello' }}
        uriPrefix={prefix}
        onNavigationStateChange={(prevState, currentState) => {
          const currentScreen = getActiveRouteName(currentState)
          const prevScreen = getActiveRouteName(prevState)

          if (prevScreen !== currentScreen) {
            console.log(`changed to : ${currentScreen}`)
          }
        }}
      />
    )
  }
}
```

```
import { createStackNavigator, createAppContainer } from 'react-navigation'
import HomeScreen from '../Containers/HomeScreen'
import SecondaryScreen from '../Containers/SecondaryScreen'

// Manifest of possible screens
const RootNav = createStackNavigator(
  {
    Home: {
      screen: HomeScreen,
      path: 'home/',
      navigationOptions: {
        header: null,
        gesturesEnabled: false,
        headerBackTitle: 'Home',
        headerTruncatedBackTitle: `Home`,
      },
    },
    Secondary: {
      screen: SecondaryScreen,
      path: 'secondary/',
      navigationOptions: props => {
        const { navigation, screenProps } = props
        console.log('====================================')
        console.log('screenProps props at navigator:', screenProps)
        console.log('====================================')
        return {
          title: 'Secondary',
          headerTitleStyle: { alignSelf: 'center' },
          gesturesEnabled: false,
          headerStyle: {
            backgroundColor: 'white',
            shadowOpacity: 0,
            elevation: 0,
          },
        } // removes shadow of header in ios and android
      },
    },
  },
  {
    // Default config for all screens
    initialRouteName: 'Home',
  },
)

export default createAppContainer(RootNav)
```

**Comment by jasan-s** [comment]
Very odd I see the snack example works and logs it in the console, but Locally using remote JS debugging nothing prints to the console.

**Comment by JanithaR** [comment]
It seems this does not work in certain cases. Here's my snack.
https://snack.expo.io/@janithar/auth-flow-v3
The code in question is in `homeScreen.js`. Just launch the app and navigate to the home screen by pressing on any of the 'select an entity' buttons.

**Comment by csumrell** [comment]
I am getting this same error in my root navigator after upgrading from v2 to v3
