### ISSUE TITLE
Error when pass a component to drawerLabel in DrawerNavigator

### ISSUE THREAD

**Issue by rodrigowpl** [react-navigation/react-navigation#5342]
### Current Behavior

There is an error when set a component to drawerLabel option in createDrawerNavigator

See code:
```
Screen1: {
    screen: Screen1,
    navigationOptions: () => ({
      drawerLabel: (
        <View>
           <Text>Screen1</Text>
        </View>
      )
    })
```

And, if to pass a string like drawerLabel:'Screen1' it works properly

See error

on IOS iphone6 simulator
![image](https://user-images.githubusercontent.com/18172307/49584392-568c6780-f942-11e8-94b2-cc0100e243ca.png)

on Android nexus5 simulator
![image](https://user-images.githubusercontent.com/18172307/49584404-6310c000-f942-11e8-9f94-35607b3ca08e.png)

### Expected Behavior

Be possible to pass a component in drawerLabel

### How to reproduce

I did an app example and I could simulate, please check it
https://github.com/rodrigowpl/rn-navigation-simulate

Just follow the instructions on readme, just install and start, open the app and you can see 
the problem that I attached above.
You can try to pass a string to *drawerLabel* and works normally, but not work with a component. Is that right?

Thanks!

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.0.5
| react-native     | 0.57.7
| node             | 8.12.0
| npm or yarn      | yarn 1.12.3

**Comment by lucianomlima** [comment]
You try with a simple string?

**Comment by rodrigowpl** [comment]
@lucianomlima Yep, as I said, with a simple string works normally

**Comment by lucianomlima** [comment]
Try with a function:

```js
    navigationOptions: () => ({
      drawerLabel: ({ focused, tintColor }) => (
        <View>
           <Text>Screen1</Text>
        </View>
      )
    })
```

**Comment by rodrigowpl** [comment]
not working too
![image](https://user-images.githubusercontent.com/18172307/49604923-560dc400-f976-11e8-9a2d-dad3b036669d.png)

**Comment by alangumer** [comment]
The accessibility label is causing the issue [fixed here](https://github.com/react-navigation/react-navigation-drawer/commit/b29c72ba918f84afc6a4ab062a820b7ec92a292e)

**Comment by rodrigowpl** [comment]
Pretty cool @alangumer , and Is already released?

**Comment by alangumer** [comment]
It is but for some reason react-navigation is not pulling the latest version of react-navigation-drawer , I edited my local file for the time being.

**Comment by rodrigowpl** [comment]
Nice! Thanks for the answer :)

**Comment by rodrigowpl** [comment]
There is another issue about that? Should I close this or wait for the release?

**Comment by alangumer** [comment]
I'd say close it since the [issue](https://github.com/react-navigation/react-navigation-drawer/issues/36) is already fixed on the react-navigation-drawer repo.

**Comment by eriveltonelias** [comment]
Hi guys! 

Thank you so much for the help @alangumer and @lucianomlima. 

@rodrigowpl,  as @alangumer mentioned, the solution is already merged on ` react-navigation-drawer` and it will be released soon. If you disagree, please tell me to reopen it.
