### ISSUE TITLE
NavigationOptions are being ignored when screens called as arrow functions

### ISSUE THREAD

**Issue by augustosamame** [react-navigation/react-navigation#5343]
Is this a bug? Or am I missing something obvious ? (sorry I'm a newbie to RN)

My screen's NavigationOptions are being ignored when called as an arrow function.

I am calling my TabNavigator like this:

```
return (
        <View style={styles.container}>
          {Platform.OS === 'ios' && <StatusBar barStyle="default" />}
          <TabNavigator screenProps={{deleteToken: this.deleteJWT }} />
        </View>
      );
```

My TabNavigator:

```
const TabNavigator = createBottomTabNavigator(
  {
  Profile: (props) => {
    return <ProfileScreen {...props.screenProps} />;
  },
  Home: () => {
     return <HomeScreen />;
      },
  Quotes: { screen: QuotesScreen,
              navigationOptions: {
                //tabBarLabel: 'Perfil',
                tabBarIcon: ({ tintColor, focused }) => (
              <Ionicons
                name={focused ? 'ios-list-box' : 'ios-list-box'}
                size={26}
                style={{ color: tintColor }}
              />
            ),
      }
  },
```

My ProfileScreen:

```
export default class ProfileScreen extends React.Component {
  static navigationOptions = {

        tabBarLabel: 'Perfil',
        tabBarIcon: ({ tintColor, focused }) => (
      <Ionicons
        name={focused ? 'ios-person' : 'ios-person'} //TODO change to focused icon
        size={26}
        style={{ color: tintColor }}
      />
    )
  }


  render() {
    return (
      <View style={{ flex: 1 }}>
        <Header title="Profile" />
        <Button
          title="Log Out"
          onPress={this.props.deleteJWT}

        />
      </View>
```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.0.2
| react-native     | https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz
| node             | 10.7.0
| npm or yarn      | npm 6.2.0

**Comment by vonovak** [comment]
hi! please include a runnable repro of your issue using [https://snack.expo.io](https://snack.expo.io ). Also, it's hard to see what the problem is - can you include expected and actual behavior in your post? Thanks.

**Comment by eriveltonelias** [comment]
Hi @augustosamame, may be you want to use `defaultNavigationOptions`, check this please https://reactnavigation.org/blog/

**Comment by brentvatne** [comment]
@eriveltonelias - I think the way he is using it here, `navigationOptions` is fine. like @vonovak mentioned a reproducible example would be useful
