### ISSUE TITLE
drawer and headers at the same time

### ISSUE THREAD

**Issue by broros** [react-navigation/react-navigation#5348]
is it possible to create an header ( https://reactnavigation.org/docs/en/headers.html )
and a Drawer navigation ( https://reactnavigation.org/docs/en/drawer-based-navigation.html ) at the same time?  there is no code sample for this...

**Comment by eriveltonelias** [comment]
Hi @broros 

Maybe it can help you https://snack.expo.io/@eriveltonelias/drawer-with-back-button

if not, questions which are better suited for StackOverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.
