### ISSUE TITLE
react-navigation How to solve the problem of page overload caused by two quick clicks

### ISSUE THREAD

**Issue by xifumengmengda** [react-navigation/react-navigation#5353]
[https://github.com/react-navigation/react-navigation/issues/1532](url)

Just like the link above ,
Quick click, jump many times,and the solution obsolescence ,it doesn't work .

how to solve the latest code 2018

 thanks

**Comment by brentvatne** [comment]
if you use react-navigation >= 2 and you use `navigate` instead of `push` then it will do what you want: https://reactnavigation.org/blog/2018/05/07/react-navigation-2.0.html#navigateroutename-in-stacknavigator-is-less-pushy
