### ISSUE TITLE
Transitioner immediately unmounts active screen

### ISSUE THREAD

**Issue by nickstamas** [react-navigation/react-navigation#5354]
### Current Behavior

- What code are you running and what is happening?

Snack here: https://snack.expo.io/HkWp51ikE

When using a custom Navigator with Transitioner, the child screen is unmounted immediately, and no "exit" animation can take place.

### Expected Behavior

The example above works for the "entrance" animation, but not the exit. It seems that the child screen is being immediately unmounted, with no chance for the animated components to be seen doing the "exit" animation.

### How to reproduce

Click "Share". Watch as background animates from blue to red. Click "Back", and notice the animation does not reverse, as the child screen is immediately unmounted.

https://snack.expo.io/HkWp51ikE

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |
| react-native     |
| node             |
| npm or yarn      |

**Comment by brentvatne** [comment]
I would recommend to use this implementation instead: https://github.com/react-navigation/react-navigation-transitioner - the Transitioner that we use for the stack navigator currently is mainly useful for the stack navigator and I think it's tough to use in other contexts

**Comment by nickstamas** [comment]
Thanks @brentvatne. I originally switched to the one from react-navigation-stack based on a warning that importing from react-navigation directly was deprecated, and it explicitly recommends using one from react-navigation-stack. I couldn't get the on from react-navigation-transitioner working, so I'm back to importing directly from react-navigation for now.
