### ISSUE TITLE
react-navigation 3 dispatch(StackActions.reset(...)); do nothing.

### ISSUE THREAD

**Issue by romreed** [react-navigation/react-navigation#5358]
I try navigate with dispatch of redux from action and nothing happened. In version react-navigation 2 this work.
`const resetActionToMain = StackActions.reset({
    index: 0,
    actions: [NavigationActions.navigate({ routeName: "Profile" })],
  });
  dispatch(resetActionToMain);
`
I create this simple project on expo https://snack.expo.io/@romreed/redux-+-react-navigation.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |^3.0.6
| react-native     |^0.57.4
| node             |v8.11.3
| npm or yarn      |yarn version 1.10.1

**Comment by brentvatne** [comment]
I think the correct way to phrase this is "how do I use StackActions.reset?" which is a legitimate question as it's not very ergonomic. you need to file issues with a MCVE (https://stackoverflow.com/help/mcve), the example you provided includes a lot of unrelated code. if you can simplify this (remove redux, put it in a single file, nothing that is unrelated to demonstrating this problem that you are having) and repost as an issue I will help, thanks!

**Comment by srivastavaprabhat23** [comment]
can we modify index in StackActions?
