### ISSUE TITLE
Open drawer on a StackNav within a TabNav on a single page

### ISSUE THREAD

**Issue by martinappberg** [react-navigation/react-navigation#5359]
Hi, I am struggling to get my home page to be the only one with a drawer navigation. This is because it should be a side menu to the home page for selecting groups.
The layout looks like this:
TabNav -> HomePage with drawer menu.

I've managed to put something together but there are a lot of bugs and the State Persistence has stopped working.

My code looks like this:

```
const HomeStack = createStackNavigator({
  Home: HomeScreen
},{
  initialRouteName:'Home',
  headerMode:'screen'
}
)

const Drawer = createDrawerNavigator({
  Home: HomeStack
},{
  contentComponent: HomeMenu,
  navigationOptions: {
    drawerLockMode: 'locked-close',
    header:null
  },
});

const AppStack = createStackNavigator({
  Home: Drawer,
})

export default AppStack;
```

The AppStack is then exported and displayed as one route inside of the TabNav.

![simulator screen shot - iphone xs - 2018-12-10 at 14 02 29](https://user-images.githubusercontent.com/17358377/49734718-852d7980-fc85-11e8-9cdf-2e7d8aab0fcc.png)
![simulator screen shot - iphone xs - 2018-12-10 at 14 02 31](https://user-images.githubusercontent.com/17358377/49734722-86f73d00-fc85-11e8-9d72-27836eeefb9b.png)

As you can see from the screenshots this works but the persistence doesn't work (Can't find any routes in NavigationState) and when pressing one of the other tabs, the navigation switches to that screen and then back to home screen again until you press the tab again and it works like it should.

Any help would be deeply appreciated! Thanks

**Comment by pzatorski** [comment]
Hey @martinappberg could you please provide your code example on https://snack.expo.io
I'm happy to help you! But please use snack for this kind of problems. You can imagine how long can it take for me or any of collaborators to run new project to reproduce particular behaviour. Thanks.

**Comment by eriveltonelias** [comment]
Hi @martinappberg! 

you can find it on examples folder https://github.com/react-navigation/react-navigation/blob/master/examples/NavigationPlayground/js/TabsInDrawer.js

and also, you can play with `NavigationPlayground` https://expo.io/@react-navigation/NavigationPlayground

**Comment by happyesthete** [comment]
@eriveltonelias Please help me. Is it possible to use same drawer and bottom tab navigation across all the screens? I understood this, but this seems impossible right now. I am able to get it working by attaching tabs to first drawer option. But, is it possible that the same bottom tab navigation just stays there in all screen. If it's possible with even a dirtier solution, please help me. I really want to keep both drawer and bottom tabs navigation at root.
