### ISSUE TITLE
Cannot navigate to toplevel switch navigator routes

### ISSUE THREAD

**Issue by atrauzzi** [react-navigation/react-navigation#5361]
### Current Behavior

When I attempt to navigate to `"login"` using either of the methods in the next code snippet, I'm given the exception that I can only choose from `"home"`.

![image](https://user-images.githubusercontent.com/115199/49752334-b140fe80-fc75-11e8-975f-69b7e0590529.png)

```typescript
    // ...
    this.navigator.dispatch(StackActions.replace({
       "login",
    }));
    // ...or...
    this.navigator.dispatch(StackActions.reset({
        index: 0,
        key: null,
        actions: [NavigationActions.navigate({ routeName: "login" })]
    }));
```

### Expected Behavior

I'd like navigation to happen on my root-level switch navigator, showing me my login screen, abandoning all stack state from my drawer navigator, downwards.

### How to reproduce

You can [see the start of my configuration graph in full here](https://github.com/atrauzzi/react-native-tinkering/blob/06b5fe895d9df7cabad48941b53a834c5df2f645/src/Layer/TinkeringRne/Component/TinkeringRneApp.tsx#L52-L72).  But for convenience, I've extracted what I feel like are the most relevant parts:

```typescript
// ...

const NavigationContainer = createAppContainer(createSwitchNavigator(
    {
        "loading": {
            screen: Loading,
        },
        "login": {
            screen: Login,
        },
        "main": {
            screen: Main,
        },
    },
    {
        initialRouteName: "loading",
        headerMode: "none",
    }
));

return <NavigationContainer 
    ref={(navigator: any) => this.props.appService.setNavigator(navigator)}
/>

// ...
```
---
```typescript
// ...

export const Main = createDrawerNavigator(
    {
        "app": {
            screen: AppStack,
        },
    },
    {
        contentComponent: Menu,
        initialRouteName: "app",
    }
);
```
---
```typescript
const AppStack = createStackNavigator(
    {
        "home": {
            screen: Home,
            navigationOptions: {
                title: "Home",
            },
        },
    },
    {
        initialRouteName: "home",
        headerMode: "none",
    }
);
```
---

> An `.env` file is required at the root of the project, but it's a standard react native project otherwise.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | `3.0.7`
| react-native     | `0.57.7`
| node             | `v11.1.0`
| npm or yarn      | `1.12.1`

**Comment by eriveltonelias** [comment]
Hi @atrauzzi, 

post a runnable example, please.

**Comment by atrauzzi** [comment]
I did. The link is in my original description.

**Comment by atrauzzi** [comment]
That's quite impractical given the nature of this project.

At this rate then, I think this ticket would serve as a sign that the documentation over surface area and lifecycle need to improve.

**Comment by eriveltonelias** [comment]
you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

**Comment by atrauzzi** [comment]
I don't wonder at all.  Understanding how people misuse (most likely in my case) your project however will help you improve your documentation though.
