### ISSUE TITLE
TypeError: undefined is not an object (evaluating '_navigation.NavigationService.setTopLevelNavigator')

### ISSUE THREAD

**Issue by jcush** [react-navigation/react-navigation#5362]
Hi,

I have been following your guide at https://reactnavigation.org/docs/en/navigating-without-navigation-prop.html so that react-navigation and redux will play nice in future. However, when I create the Navigation service as per your example and attempt to set the top level navigator in my navigator component, I receive the error in this issue's title. The line which the error points to, in Navigator.js, is:
`<NavAppContainer ref={navigatorRef => {`

Please note the same issue arises when the nav app container is in the main App.js file, but going forward it will live in the Navigator component so that I can wrap it in a Provider when implementing redux.

Please help, as this is driving me insane...

### Current Behavior

App.js
```
import React from 'react';
import { StatusBar, View } from 'react-native';
import Navigator from './src/components/navigator';

export default class App extends React.Component {

	render() {
    	return (
			<View style={{flex: 1}}>
				<StatusBar hidden={true} />
			  	<Navigator />
			</View>
		);
	  }
	  
}
```

src/components/navigator.js
```
import React, { Component } from 'react';

import { createStackNavigator, createAppContainer } from 'react-navigation';
import { NavigationService } from '../services/navigation';
import ProfileScreen from '../screens/profile';

const Navigator = createStackNavigator(
	{
		Profile: {
			screen: ProfileScreen
		}
	},
	{
		headerMode: 'none',
		initialRoutName: 'Profile'
	}
);

const NavAppContainer = createAppContainer( Navigator );

export default class Nav extends Component{
	render() {
		return (
			<NavAppContainer ref={navigatorRef => {
				NavigationService.setTopLevelNavigator( navigatorRef )
			}} />
		)
	}
}
```

src/services/navigationService.js
```
import { NavigationActions } from 'react-navigation';

let _navigator;

function setTopLevelNavigator( navigatorRef ){
	_navigator = navigatorRef;
}

function navigate( routeName, params ){
	_navigator.dispatch(
		NavigationActions.navigate({
			routeName,
			params
		})
	);
}

export default {
	navigate,
	setTopLevelNavigator
};
```

### Expected Behavior

App should not be crashing - the navigator component should function as the example at the URL provided intends.

### How to reproduce

Create an app with the above files (and any referenced files) and run it. Crash.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.0.7
| react-native     | 0.57.1
| node             | 10.13.0
| npm                | 6.4.1

**Comment by eriveltonelias** [comment]
Hi @jcush! 

I just created an example following the docs ( 
https://reactnavigation.org/docs/en/navigating-without-navigation-prop.html ), 

and is working as expected, please check it https://snack.expo.io/@eriveltonelias/navigationservice

if it is not that what are you looking for, please post a runnable example, I'll glad to review it.

**Comment by jcush** [comment]
Hi @ericvicenti 

Why have you instantly closed the issue? I hadn't had chance to respond?

Please see here: https://snack.expo.io/@cush/navigationservice for a runnable, non-working example which is much closer to what I outlined in my original post

**Comment by eriveltonelias** [comment]
Hi @jcush! 

Thanks for your repro and of course, you're welcome to respond and I'm sure that everyone wants to help you

the issue on your code is because you're importing the `NavigationService` wrong 

```js
import { NavigationService } from '../services/navigation';
```

is that the right way:
```js
import NavigationService from '../services/navigation';
```

I just updated your code, check it, please. 

https://snack.expo.io/@eriveltonelias/navigationservice

**Comment by jcush** [comment]
Hi,

I managed to get the app working by using the standard navigation prop, but I realise this apparently doesn’t work well with redux in some cases. 

How can I tell whether my app will need to use the ref prop instead of navigation? I am also, for example, using withNavigation in one of my components which is not a screen in itseld

**Comment by CHANDRAMOHANnegi** [comment]
`import { NavigationActions } from 'react-navigation';

let _navigator;

function setTopLevelNavigator(navigatorRef) {
  if (navigatorRef) _navigator = navigatorRef;
}

function navigate(routeName, params) {
  if (_navigator) {
    _navigator.dispatch(
      NavigationActions.navigate({
        routeName,
        params,
      })
    );
  }
  else {
    //todo - reports to firebase user is unable to navigate
  }

}

//options = {}
function moveBack(options) {
  if(_navigator) {
    _navigator.dispatch(
      NavigationActions.back(options)
    )
  }
  else {
    //todo - reports to firebase user is unable to navigate back
  }
  
}

// add other navigation functions that you need and export them

export default {
  navigate,
  setTopLevelNavigator,
  moveBack
};`

**Comment by VinothEI** [comment]
https://reactnavigation.org/docs/navigation-container
This will help you, Clear cut ans is here.
