### ISSUE TITLE
createDrawerNavigator not auto close

### ISSUE THREAD

**Issue by pmninh91** [react-navigation/react-navigation#5363]
## The issue tracker is reserved for bug reports only.
I'm using createDrawerNavigator as follows.

![image](https://user-images.githubusercontent.com/43737230/49794276-c8611880-fd69-11e8-81b0-3f55b60aea2c.png)

I use the **navigation.toggleDrawer()** function to open the left sidebar. But when I click outside the SideBar, the **createDrawerNavigator** does not automatically close. **This case I just met on the Android operating system. IOS operating system is still normal**. Can you help me with this problem? Thanks.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.0.7
| react-native     | 0.57.7
| node             | 10.14.0
| yarn      | 1.12.3

**Comment by eriveltonelias** [comment]
hi! please make your code runnable either on https://snack.expo.io without any extraneous code

**Comment by eriveltonelias** [comment]
Hi @pmninh91! 

try to update your `react-native-gesture-handler` to the last and make sure to add additional steps to link the library on Android ( `MainActivity.java`) https://reactnavigation.org/docs/en/getting-started.html

**Comment by yogeshmoradiya121** [comment]
same issue i face.
touch out side the drawer. drawer still open. it sould be close
same code in react navigation 2 . drawer working.
i think this is bug in react navigation 3

**Comment by pmninh91** [comment]
Thanks, @eriveltonelias
