### ISSUE TITLE
Reset the stack navigator nested within Drawer Navigator 

### ISSUE THREAD

**Issue by gowthamans268** [react-navigation/react-navigation#5364]
In our application we are having a switch navigator for authentication stack and Application stack

```
const AppContainer = createAppContainer(
      createSwitchNavigator(
          {
            App: createStackNavigator({ Login: LoginForm })
            Auth: createStackNavigator({ Main: MainPage})
          },
          {
              initialRouteName: 'Auth',
          }
      ));
```

In the Main Form i am having a Drawer Navigator, In which each menu item is itself a stack navigator with multiple screens

```
var drawer =createAppContainer(createDrawerNavigator(
     {
        Home: createStackNavigator({
                   Home: {screen: Home}
        }),
       Stack1:  createStackNavigator({
                    Form1: {screen: Form1},
                    Form2: {screen: Form2},
        }),
       Stack2:  createStackNavigator({
                    Form1: {screen: Form1},
                    Form2: {screen: Form2},
        })
     }
  );
)
```

Here the initial route for the Drawer Navigator is **"Home"** stack.

```
onPressDrawerMenuItem = (routeName) =>{
     var NavAction =  NavigationActions.navigate({ routeName: routeName })
     var  resetAction = StackActions.reset({
                index: 0,
                key: null, 
                actions: [NavAction],
              });

      this.props.navigation.dispatch(resetAction);
}
```

### Current Behavior

It is throw an error while i am clicking the **"Stack1"** 
**There is no route defined to key 'Stack1' Must be one of : 'Home'**

### Expected Behavior
I want to reset the state on the last stack menu, And in the Unmount lifecycle event of the stack pages i want to make a web api call to the server.

When i open the same stack again it shout open the fresh page with new state, currently it is maintaining the old state object

### How to reproduce

Try the same above code, It will throw the error while resetting the Old stack 

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |   : "^3.0.7"
| react-native     |:  "0.57.5"
| node             |: v8.12.0
| npm    |: 6.4.1

**Comment by eriveltonelias** [comment]
hi! please make your code runnable either on https://snack.expo.io without any extraneous code

**Comment by eriveltonelias** [comment]
I'll close the issue for now, but you can add the repro to the original post and then ping me and I'll reopen to investigate. Thanks for understanding.
