### ISSUE TITLE
Duplicate of #5350 

### ISSUE THREAD

**Issue by woodpav** [react-navigation/react-navigation#5365]
I have the same problem as #5350. I want to comment asking for help or possible solutions but the conversation is locked as off topic. 

It should be closed, but not locked. It is this package that is throwing the error. 

Could you unlock it so I could get some resolution?

**Comment by woodpav** [comment]
The answer was to change my `babel.config.js` from 

     let plugins = [
        '@babel/plugin-transform-runtime',
        '@babel/plugin-proposal-class-properties',
     ];

to

     let plugins = [
         '@babel/plugin-transform-flow-strip-types',
         '@babel/plugin-transform-runtime',
         [
             '@babel/plugin-proposal-class-properties', {
                'loose': true
            }
         ],
     ];

**Comment by brentvatne** [comment]
strange. thanks for following up. this is unrelated to react-navigation itself but maybe it will help people!
