### ISSUE TITLE
Big data breaking FPS on transition

### ISSUE THREAD

**Issue by ardyfeb** [react-navigation/react-navigation#5366]
### Current Behavior

- Open app
- Navigate to alquran screen
- when navigate to alquran details screen FPS take slow

The video with data loaded on screen (standalone apk build) : https://streamable.com/0foan
With data loaded the transition get low performance, look at bottom navigation the icon animation not animate correctly, and when navigate to alquran details screen then back to previous screen the FPS taking low performance 

### Expected Behavior

-  Smooth app transition although with big data

The video without data loaded on screen: https://streamable.com/y0llq
Without fetch data the transition get perfectly FPS

### How to reproduce

You can try the app : https://exp-shell-app-assets.s3.us-west-1.amazonaws.com/android/%40ardyfeb/Islamku-983c546ebb9a47299234a9b656c6ee59-signed.apk

My code on alquran details :
```
import React, { Component } from 'react'
import { Text } from 'native-base'

class AlquranReader extends Component {
   alquranSurah = null
   
   alquranInfo = null
   
   state = {
      loading: true
   }
   
   componentDidMount() {
      const alquran_no = this.props.navigation.getParam('no', 1)
      Expo.SQLite.openDatabase('alquran.db')
        .transaction(tx => {
            tx.executeSql(
              `SELECT arabic.surat as surat, arabic.ayat as ayat , arabic.text as arabicText, indonesia.text indonesiaText
               FROM arabic
               INNER JOIN indonesia ON arabic.id = indonesia.id
               WHERE arabic.surat = '${alquran_no}'`, 
               null, 
               (_, { rows: { _array } }) => {
                  this.alquranSurah = _array
                  this.setState({
                     loading: false
                  })
               }, 
               (_, err) => console.log(err))           
        })
   }
   
   render() {
      return <Text> Without data </Text>
      
     /* return this.alquranSurah.map(alquran => (
          <Text key={alquran.ayat}> {alquran.arabicText} | {alquran.indonesiaText} </Text>
      )) */
   }
}

export default AlquranReader
```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.18
| react-native     | Expo SDK 31
| node             |
| npm or yarn      |

**Comment by brentvatne** [comment]
nothing we can do about this, if you turn on the performance monitor in development mode you will see that you are dropping frames on the main thread, not just on js thread. we already run this transition on the main thread using the native driver. you will have to be more careful about what you do during the transition
