### ISSUE TITLE
<Text selectable /> not working in DrawerNavigator

### ISSUE THREAD

**Issue by Enricopv** [react-navigation/react-navigation#5367]
Currently doesn't not work on Android.

I am trying to have selectable text in a Drawer Navigator. Using `<Text selectable>Some text</Text>` works fine in a Switch Navigator. 

### How to reproduce

Create two different stacks that render the same component. The Switch Navigator will allow you to press and hold to get a select context menu. The Drawer Navigator will not give you the same functionality. To switch between the two just change the  initialRouteName: "SwitchStack" | "DrawerStack". When using the snack with an iOS device it works fine, in Android it does not.

https://snack.expo.io/@enricopv/text-select-issue

```

import * as React from 'react';
import { Text, View} from 'react-native';
import { createSwitchNavigator, createAppContainer, createDrawerNavigator } from "react-navigation"

const TextPage = () => {
  return (
    <View style={{paddingTop: 50}}>
      <Text selectable>Long press me see  works</Text>
    </View >
  )
}

const SwitchStack = createSwitchNavigator(
  {
    TextPage
  }
)

const DrawerStack = createDrawerNavigator(
  {
    TextPage
  }
)

const AppStack = createSwitchNavigator(
  {
    SwitchStack,
    DrawerStack
  },
  {
    initialRouteName: "SwitchStack"
  }
)

export default createAppContainer(AppStack)
```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^3.0.5
| react-native     | https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz

**Comment by ScottDikowitz** [comment]
I'm experiencing a similar problem with stackNavigator. It works when it first mounts, but if i press back and navigate again to the same screen it won't be selectable.

**Comment by brentvatne** [comment]
grouping this into https://github.com/react-navigation/react-navigation/issues/5476
