### ISSUE TITLE
navigationOptions setting for BottomTabNavigator doesn't work

### ISSUE THREAD

**Issue by khanhlu2013** [react-navigation/react-navigation#5368]
```
const nav = createBottomTabNavigator({
  Home,
  About
})
nav.navigationOptions = {
    title: "something",
}
```

I expect the title for both bottom tab to be "something". but it is still "Home" and "About"

<img width="322" alt="screen shot 2018-12-11 at 12 07 10 pm" src="https://user-images.githubusercontent.com/5914159/49827082-4fe46280-fd3d-11e8-9c65-80714fa902bf.png">

https://snack.expo.io/@khanhlutran/courageous-scones

**Comment by brentvatne** [comment]
I think you need to read the docs step by step as you haven't described the correct way to use the library here. You would need to set the `navigationOptions` on both the Home and About screens, or set `defaultNavigationOptions` in the navigator config: https://snack.expo.io/@notbrent/courageous-scones
