### ISSUE TITLE
undefined is not a function (evaluating '(0, _reactNavigation.TabNavigator)')

### ISSUE THREAD

**Issue by gildascy** [react-navigation/react-navigation#5369]
I'm building an app that looks a lot like Whatsapp (the ui only). So i have a top navigation bar, icons with labels. 
![image](https://user-images.githubusercontent.com/45181981/49860759-be3b2a80-fdfa-11e8-8dbb-78942f3477b3.png)
When launching in my emulator, i have that problem **undefined is not a function (evaluating '(0, _reactNavigation.TabNavigator)')**
I have a main file in which i import all the tabs
And the problem seems to be comming 

`//Main.js
//import { Container, Text, Content } from 'native-base';
//import { Icon } from 'native-base';
import React, { Component } from 'react';
import { TabNavigator } from 'react-navigation';
//import {Platform} from 'react-native';
import QbTab from './tabs/QbTab';
import ScannerTab from './tabs/ScannerTab';
import SaveTab from './tabs/SaveTab';
import ReglageTab from './tabs/ReglageTab';
//import CartTab from './tabs/CartTab';

export default class Main extends Component {
    static navigationOptions = {
        headerLeft: "QB",
    }
    render() {
        return (<MainNavigator />) 
    }
}
const MainNavigator = TabNavigator({
    QbTab: {
        screen: QbTab,
        title: "QB"
    },
    ScannerTab: {
        screen: ScannerTab,
        title: "SCANNER"
    },
    SaveTab: {
        screen: SaveTab,
        title: "SAUVEGARDER"
    },
    ReglageTab: {
        screen: ReglageTab,
        title: "REGLAGES"
    }/* ,
    CartTab: {
        screen: CartTab
    }, */
}, {
    animationEnabled: true,
    swipeEnabled: true,
    tabBarPosition: 'top', 
    tabBarOptions: {
        showIcon: true,
        showLabel: true,  
        style: {
            backgroundColor: 'teal',
        },          
        activeTintColor: 'blue',
        inactiveTintColor: 'gray',   
    }
});`

and in the App.js
`import React, { Component } from 'react';
import {
  Platform,
  StyleSheet,
  Text,
  View
} from 'react-native';
import { StackNavigator } from 'react-navigation';
import Main from './screens/Main';

const Navigator = StackNavigator({
  Main: {
    screen: Main
  }
});

export default class App extends Component {
  render() {
    return (<Navigator />);
  }
}`

**Comment by gildascy** [comment]
Here's the link to snack expo [https://snack.expo.io/HkZyxPAkV](url)

**Comment by vonovak** [comment]
hi! Please use `createStackNavigator` / `createBottomTabNavigator` as documented here https://reactnavigation.org/docs/en/api-reference.html

**Comment by Mateodiaz401** [comment]
Este es mi aporte que encontre que explica como resolver este detalle 
https://medium.com/@saishaddai/react-native-undefined-is-not-a-function-evaluating-0-reactnavigation-stacknavigator-1d9979eba2e8
