### ISSUE TITLE
Hide parent bottom navigation bar from nested child

### ISSUE THREAD

**Issue by tufailra97** [react-navigation/react-navigation#5376]
Is it possible to hide a parents bottomTabBar from a child components?

I found [this](https://github.com/react-navigation/react-navigation/issues/888) and following the fix by[@gamingumar](https://github.com/react-navigation/react-navigation/issues/888#issuecomment-357757943), however the bottom bar is hidden at all the time.

Sample structure app:
App.js
  -Home //parent bottom
   -----News // child stacknav
   -----Media // child stacknav
   ---------Camera //deeper child stacknav <- Here I want home bottom nav to be hidden
  -Settings //parent bottom
  ------Logout

### Current Behavior

- Hidden at all the time

### Expected Behavior

- Hide Bottom from child component

### How to reproduce

Basic [Snack (react nav v2)](https://snack.expo.io/@tufailra97/dW5uYW)
Structured [Snack(react nav v3)](https://snack.expo.io/@tufailra97/dW5uYW)

### Your Environment

Expo CLI 2.4.0 environment info:
System:
OS: Windows 10
Binaries:
Yarn: 1.9.4 - ~\AppData\Roaming\npm\yarn.CMD
npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
IDEs:
Android Studio: Version 3.2.0.0 AI-181.5540.7.32.5056338
VS Code

**Comment by brentvatne** [comment]
https://reactnavigation.org/docs/en/navigation-options-resolution.html

**Comment by tufailra97** [comment]
I've already read [this](https://reactnavigation.org/docs/en/navigation-options-resolution.html#a-tab-navigator-contains-a-stack-and-you-want-to-hide-the-tab-bar-on-specific-screens), before opening an issue. The solution works only with stack navigator and it doesn't with createBottomNavigation.

**Comment by brentvatne** [comment]
i think you need to try to clean this example up so you can model it more cleanly in your mind.
-  you call `setParams` on the Camera component, which is a route inside of a stack in home, and the param isn't available to the home component. you can verify that the issue you describe is not correct by just changing the tabBarVisible thing to true and false and you will see it toggles visibility as expected.
- you're defining navigators in multiple files and rendering them in different places in the navigation hierarchy. that's not how this library works (https://reactnavigation.org/docs/en/common-mistakes.html#explicitly-rendering-more-than-one-navigator).

anyhow, this isn't a forum for help, i'd suggest you check out https://reactnavigation.org/ for that. i appreciate you trying to provide examples though! in the future try to isolate the problem further and make the example as small as possible

**Comment by tufailra97** [comment]
> i think you need to try to clean this example up so you can model it more cleanly in your mind.
> 
> * you call `setParams` on the Camera component, which is a route inside of a stack in home, and the param isn't available to the home component. you can verify that the issue you describe is not correct by just changing the tabBarVisible thing to true and false and you will see it toggles visibility as expected.
> * you're defining navigators in multiple files and rendering them in different places in the navigation hierarchy. that's not how this library works (https://reactnavigation.org/docs/en/common-mistakes.html#explicitly-rendering-more-than-one-navigator).
> 
> anyhow, this isn't a forum for help, i'd suggest you check out https://reactnavigation.org/ for that. i appreciate you trying to provide examples though! in the future try to isolate the problem further and make the example as small as possible

I tried to ask on slack overflow but got no help. 
I also tried to set param on the camera component however I couldn't get the param on the home navigator. 
I isolated the issue also attached a diagram (hopefully this will help to understand).

[Snack](https://snack.expo.io/@tufailra97/aGlkZS)
[Diagram](https://drive.google.com/open?id=1jkw7Lz9kNp5AOd_TJaqt_h4x2uZP9EOb)

**Comment by alexpereira** [comment]
Try this:
```javascript
YourStackWithNestedRoutes.navigationOptions = ({ navigation }) => {
  const currentRoute = navigation.state.routes[navigation.state.index];
  const { routeName } = currentRoute;

  let tabBarVisible = true;
  if (routeName === 'StackWithNestedRoutes') {
    const { routeName } = currentRoute.routes[currentRoute.index];

    if (routeName === 'NestedRoute') {
      tabBarVisible = false;
    }
  }

  return {
    tabBarVisible
  }
});
```

**Comment by pragneshpj** [comment]
@alexpereira 
thank you, 
your code is working.

**Comment by muriloao** [comment]
@alexpereira 
thanks, working for me too

**Comment by sanjeevkse** [comment]
Thank you for the solution, May I know how can this be achieved?

**Comment by xXstekkaXx** [comment]
@sanjeevkse 
> Thank you for the solution, May I know how can this be achieved in the latest 5.x?

Yes, this is my version update for react-navigation v5.x

in the specific, this is a top Tab, but it works also with the bottom Tab, using style or tabBarVisible

```const Tab = createMaterialTopTabNavigator();

export function bottomTabNavigator({ navigation, route }) {

  let isSwipeEnabled = true;
  let tabBarStyle;

  if (route && route.state && route.state.history) {

    const currentRoute = route.state.history[route.state.history.length - 1]
    const currentRouteName = currentRoute.key.split("-")[0]
    const currentNestedNavigator = route.state.routes.find(route => route.name === currentRouteName)
    let currentNestedNavigatorIndex;

    if (currentNestedNavigator && currentNestedNavigator.state) {

      currentNestedNavigatorIndex = currentNestedNavigator.state.index;

      if (currentNestedNavigatorIndex && currentNestedNavigatorIndex > 0) {
        tabBarStyle = { display: "none" }
      }

    }

  }

  return (
    <Tab.Navigator
      tabBarPosition="bottom"
      tabBarOptions={{
        showIcon: true,
        activeTintColor: color.primary,
        inactiveTintColor: color.palette.grey3,
        style: tabBarStyle
      }}
    >
      <Tab.Screen name="home" component={HomeNavigator} />
      <Tab.Screen name="userEvents" component={UserEventsNavigator} />
      <Tab.Screen name="groups" component={GroupsNavigator} />
      <Tab.Screen name="tasks" component={TasksNavigator} />
    </Tab.Navigator>
  );
}```

**Comment by sanjeevkse** [comment]
> Thank you for the solution, May I know how can this be achieved in the latest 5.x?

Thank you so much for the reply and the solution is working awesome. The 5 days struggle came to an end and came to a learning.

**Comment by tanteemmie** [comment]
I solved it for v5 by following this: https://reactnavigation.org/docs/screen-options-resolution/

**Comment by arwysyah** [comment]
@tanteemmie  can you share your code ?

**Comment by arwysyah** [comment]
const Stack = createStackNavigator();
const HomeScreen=()=>{
  return(
   
    <Stack.Navigator initialRouteName="Home"
    options={{ headerShown: false }}
    >
      <Stack.Screen name="Home" component={Home}
      options={{ headerShown: false }} />
      <Stack.Screen name="CountryList" component={CountryList}
      options={{ headerShown: false }} />
    </Stack.Navigator>
  
  )
}


const Tab = createBottomTabNavigator();
 function App() {
  return (
    <NavigationContainer
    >
      <Tab.Navigator
      screenOptions={({ route }) => ({
        tabBarIcon: ({ focused, color, size }) => {
          let iconName;

          if (route.name === 'HomeScreen') {
            iconName = focused
              ? 'ios-information-circle'
              : 'ios-information-circle-outline';
          } else if (route.name === 'Indonesia') {
            iconName = focused ? 'ios-list-box' : 'ios-list';
          }

          // You can return any component that you like here!
          return <Ionicons name={iconName} size={size} color={color} />;
        },
      })}
      tabBarOptions={{
        activeTintColor: 'tomato',
        inactiveTintColor: 'gray',
        style:{
          height:80,
          marginVertical:-30,
          backgroundColor:color,
        },
        tabStyle:{height:40}
      }}
    >
        <Tab.Screen name="HomeScreen" component={HomeScreen} />
        <Tab.Screen name="Indonesia" component={Indonesia} />
      </Tab.Navigator>
    </NavigationContainer>
  );
}
i want to hide CountryList screen

**Comment by tanteemmie** [comment]
@arwysyah https://stackoverflow.com/a/60868167/12157659

You can find it here
