### ISSUE TITLE
infinite loop Get Params

### ISSUE THREAD

**Issue by Erenner** [react-navigation/react-navigation#5378]
Secreen A
onPress
                this.props.navigation.navigate('example', {
                 data: this.state.data

ScreenB
  const { navigation } = this.props;
  let data= null
  data=  navigation.getParam('data', null);
  if(data) {
    this.setState({
      data: data
    })  
  }

**Comment by brentvatne** [comment]
hello please create a runnable minimal example on https://snack.expo.io or in a github repo and then create a new issue with a link to it, thanks!
