### ISSUE TITLE
splash screen to login screen doesn't have transition animation

### ISSUE THREAD

**Issue by farshidshahmoradi1996** [react-navigation/react-navigation#5379]
Hi everyone, I hope you are good  
I have a problem with changing `splash screen` to `login screen` or `Main Screen` of my app
in splash screen we check the `apitoken` with server if user found you will go to main screen and if user not found you will redirect to login screen . from here isn't any problem 
problem is in changing screen with `reset` action 
reset or replace action doesn't have transition animation and this problem doesn't have nice face for my app
i want changing screen (between splash screen and login \ main ) have transition effect 

thanks you dear ,

**Comment by brentvatne** [comment]
sorry you need to follow the issue template when you file an issue
