### ISSUE TITLE
Passing props from contentComponent to another screen shows as screenprops undefined

### ISSUE THREAD

**Issue by udarts** [react-navigation/react-navigation#5380]
### Current Behavior

I use the app.navigator.js and the following code is part of it:

```javascript
const MainStack = createStackNavigator(
{
    Home: {screen: HomeStack},
    Login: {screen: LoginStack},
    Forgot: {screen: ForgotStack},
    Agenda: {screen: AgendaStack},
    Info: {screen: InfoStack},
    Register: {screen: RegisterStack},
    Settings: {screen: SettingsStack},
    Contact: {screen: ContactStack},
    Account: {screen: AccountStack},
    Announcements: {screen: AnnouncementsStack},
},
    RouteConfig
);
const AppNavigator = createDrawerNavigator(
{
    Main: {
        screen: MainStack,
    },
    WebDetail: {
        screen: WebDetailStack
    },
},
{
    contentComponent: props => <SideScreen {...props}/>,
},
)
```

Then in the contentComponent (the sidebar), I use the following code on a button click:

```javascript
shownWeb(url) {
    const { navigation } = this.props;
    const navigateAction = NavigationActions.navigate({
      routeName: 'WebDetail',
      params: {sourceHtml: url}
    });
    navigation.closeDrawer();
    navigation.dispatch(navigateAction);
};
```

It goes to the WebDetail screen, but without props / params.

### Expected Behavior

It should go to the WebDetail screen, passing any props / params.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.0.0
| react-native     | 0.57.5
| node             | 11.0
| npm or yarn      | 6.4.1 (npm)

**Comment by brentvatne** [comment]
hi! you need to provide a reproducible example. please open a new issue with a runnable minimal reproducible example (only the minimal amount of code to re-create the alleged bug). i suspect in doing this exercise you will find out some issue in your code and it won't be a bug but otherwise will definitely look at your new issue when its ready!
