### ISSUE TITLE
navigate from nested tab navigator in drawer navigator to screen in drawer navigator

### ISSUE THREAD

**Issue by aquibyatoo** [react-navigation/react-navigation#5381]
i have this structure of my app

root *drawernavigator* {
dashboard: *tabnavigator*(...screens),
profile,
settings
}

I want to navigate from screen in tabnavigator to the screen in drawer navigator e.g(profile..).

**Comment by brentvatne** [comment]
hello! the issues are only for bug reports, if you want help see https://reactnavigation.org/en/help.html
