### ISSUE TITLE
createBottomTabNavigator together with react-native-screens cause blinking for each tab

### ISSUE THREAD

**Issue by dsznajder** [react-navigation/react-navigation#5382]
This happens only on Android, I made reproduction on a snack, hope this helps

### Current Behavior
- When I click on a tab the screen blinks before render.

### Expected Behavior
- The screen should just render as without `useScreens()` function.

### How to reproduce
- https://snack.expo.io/rklSkM-xE

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.0.8
| react-native     | 0.57.5
| node             | 10.11.0
| npm or yarn      | 1.12.3

**Comment by brentvatne** [comment]
cc @kmagiera

**Comment by brentvatne** [comment]
for additional context, i tried this out and it seems to only happen intermittently

**Comment by kmagiera** [comment]
Submitted a fix to this one to the tabs repo -> https://github.com/react-navigation/react-navigation-tabs/pull/80

**Comment by brentvatne** [comment]
I'll publish a new release today with this fix!

**Comment by dsznajder** [comment]
Ok, I will check this out tomorrow on some low end device and get back with results :)

**Comment by sm1th** [comment]
I'm having the same issue with stackNavigator on Android. A white flash appears before the next screen slides up over top of it. Similarly on back press.

**Comment by dsznajder** [comment]
@kmagiera @brentvatne I think it's resolved in `3.0.9` as i did not see the flickering ;) Thanks! I'm closing issue
