### ISSUE TITLE
NavigationActions.back() does not guarantee order of mounting components

### ISSUE THREAD

**Issue by airlaser** [react-navigation/react-navigation#5385]
EDIT: It turns out this is also causing `componentDidMount` and `componentWillUnmount` to be out of order on the RN component itself. Very annoying to deal with. 

**TL:DR:** Rapidly opening/closing a stack navigator using `NavigationActions.back()` can cause `componentDidMount` on the new component to fire before the previous one has 
`componentWillUnmount` fire. This does not happen if using swipe gestures & `gesturedEnabled`. 

### Setup

In React Native on iOS. I have a stack navigator with gestures enabled and a close button in the top right. Swiping down dismisses this screen. Tapping the close button calls `navigator.current.dispatch(NavigationActions.back());` which also dismisses this screen. The screen underneath has a button which opens the screen again. The screen has a bridged Swift component which relies on the order of `layoutSubviews` and `removeFromSuperview` being called. 

(this issue also applies to any bridged component that needs to garbage collect or `removeFromSuperview` before a new view is created or `layoutSubviews`'d)

### Current Behavior

Rapidly closing and opening the screen using gestures to close works perfectly. It won't create/lay out a new bridged view until the old one is gone. Rapidly closing and opening via the close button easily causes a new view to be created/laid out before the old one is gone. 

### Expected Behavior

I expect for the behavior to be the same for gesture and `NavigationActions` based closure. Since gesture nav seems to handle the order of things properly I expect that using `NavigationActions` would do so as well. 

### How to reproduce

See `Setup`. 

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.18.3
| react-native     | 0.56.0
| node             |  11.2.0
| npm or yarn      | yarn

Targeting iOS 11, xcode 10.1

**Comment by brentvatne** [comment]
if you update to v3 this is resolved

**Comment by airlaser** [comment]
@brentvatne how do I upgrade to v3? It hasn't worked and there is zero documentation on getting it to work post-upgrade

**Comment by brentvatne** [comment]
uh what? https://reactnavigation.org/blog/2018/11/17/react-navigation-3.0.html

Also in changelog

**Comment by brentvatne** [comment]
what should we do to make it more obvious? where can we put a link to the changelog so it's easy to find? i used to update the releases tab but users asked for a changelog so i switched. we could update both but that's yet another menial task for maintainers, and probably still some folks wouldn't find it and would ask for us to update yet another place :P hopefully you have some ideas for how we can make it very clear.

**Comment by airlaser** [comment]
I didn't mean to be a dick about it. 

I feel like changelog vs releases is more on GH than you - GH should be able to parse `CHANGELOG.md` into their releases tab. The concept is strong, just needs wider adoption. 

I think what fell thru here for me is that the upgrade notes were in a blog instead of the documentation. Linking the blog page from Docs, the Help page and the FAQs section of the readme makes it clear that the blogs have actual information and not just blog stuff.

**Comment by brentvatne** [comment]
if we had a changelog link in the header would that help? Docs / API / Changelog / Help / Blog
