### ISSUE TITLE
persistenceKey: nested tab navigator's last tab not restored

### ISSUE THREAD

**Issue by Morriz** [react-navigation/react-navigation#5389]
https://snack.expo.io/@morriz/tab-issues:-persistencekey---nested-tab-navigator's-last-tab-not-restored

nested tab navigator state is not restored like title says

**Comment by brentvatne** [comment]
the snack that you shared doesn't run at all, it just shows a syntax error. please clean it up and get it running and we can look!

**Comment by Morriz** [comment]
If it does throw an error, try changing the persistence key ;) (another bug?)

**Comment by brentvatne** [comment]
no, it is a syntax error in the app code that you shared :P

**Comment by Morriz** [comment]
I see none

**Comment by brentvatne** [comment]
<img width="1182" alt="screen shot 2018-12-15 at 1 57 17 pm" src="https://user-images.githubusercontent.com/90494/50046447-63f7cf00-0071-11e9-9e8e-be4e64d8056e.png">

**Comment by Morriz** [comment]
fak, can't find where my screenies get dumped...one sec

**Comment by Morriz** [comment]
<img width="1677" alt="screenshot 2018-12-15 20 00 15" src="https://user-images.githubusercontent.com/941865/50046469-18aae400-00a4-11e9-87d9-809abfb46aff.png">

**Comment by Morriz** [comment]
"but it works on my computer!"

**Comment by brentvatne** [comment]
I don't see what you're going for here because "NavUp" is never even rendered but the first level of tabs is rendered as expected...

**Comment by Morriz** [comment]
this source is so open you might have accidentally touched it?

**Comment by Morriz** [comment]
never rendered? want me to make screenies of that too?

**Comment by brentvatne** [comment]
I think you just didn't hit "Save" but anyways I fixed the syntax error and this Snack does not demonstrate what you think it might

**Comment by brentvatne** [comment]
@Morriz - I don't need it, I'm looking at the code and it does not render NavUp ever

**Comment by Morriz** [comment]
<img width="331" alt="screenshot 2018-12-15 20 04 41" src="https://user-images.githubusercontent.com/941865/50046495-aab2ec80-00a4-11e9-98ef-d7d5288a234c.png">

**Comment by Morriz** [comment]
I don't know where you are going with this ;)

**Comment by brentvatne** [comment]
@Morriz - open your snack in a new incognito tab.

also, see https://snack.expo.io/@notbrent/tab-issues:-persistencekey---nested-tab-navigator's-last-tab-not-restored

works as expected, not a bug. please stop filing issues without a reproducible example that actually runs. try it in an incognito tab first if you want.

**Comment by Morriz** [comment]
Please don't close this in a hurry Brent, don't you understand the bug I see? The stack nav goes to NavUp, select tab two, go "Back", and then again CLICK ME to go to NavUp, it selects tab one instead of tab 2

**Comment by Morriz** [comment]
You are way tooooo quick with closing bugs if I might say. As if you are annoyed by us setting up all those snacks (costs quite some time you know). I am grateful for all your hard work but feel your haste is not serving the project...

**Comment by Morriz** [comment]
So can you please keep this open and maybe let somebody else respond? Second opinion?

**Comment by brentvatne** [comment]
@Morriz - you need to actually explain the problem. I got your snack running and tried to reproduce it, it doesn't work. see the issue template.

there is no room for a second opinion here because you're not describing what is actually going wrong. in particular this step is missing "Explain how to run the example app and any steps that we need to take to reproduce the issue from the example app."

if you want me to spend 30 minutes trying to understand better what you're doing without you explaining it to me, you can paypal me $100 and i will do it, but otherwise you need to be clear upfront.

**Comment by Morriz** [comment]
And what is wrong with snack? Please check now. I don't understand why your code is different. I just opened the tab anew and expect others to see the same.

**Comment by brentvatne** [comment]
for example, you could say:

- open the snack on android
- click on the second tab
- add a comment somewhere to code so the app reloads
- notice that x happens, when i expect y to happen

the issue template is here for a very good reason and you need to follow it

**Comment by Morriz** [comment]
FFS: Like I said in the title the selected tab does not get restored the next time I open the nested tab navigator

**Comment by brentvatne** [comment]
morriz, i'm going to block you from the repo for a few days because this isn't productive. if you choose not to continue using this library that is fine, but i think you need to consider that when you're not properly filing issues you're wasting the time of maintainers
