### ISSUE TITLE
React navigation version 3 does not look in parent navigation object when it fails in local or nested navigation object.

### ISSUE THREAD

**Issue by aquibyatoo** [react-navigation/react-navigation#5391]
I will try to define this ... *also a side note this was working in 2.0.1 version which i was using in my previous app*

the structure of my app:

root (whicj is drawer navigator) : {
              Dashboard: ( which is a tab navigator) {
                  ....... tan screens here ...
              },
             Profile,
             Settings,
             .........
}

I need to navigate from tab screens to the screen in drawer like Profile , Settings,
am using this.props.navigation.naviagte('Profile') in tab screen , which in my opinion will look in local stack tab stack and on failed lookups will search in drawer stack means in parent stack .
*But not Working*

*Parent file which is drawer navigator containing Dashboard as a tab navigator*

*i did not add  styles and customDrawerComponet  here ..*

import React, { Component } from 'react';
import {
  View,
  Text,
  StyleSheet,
  StatusBar,
  ImageBackground,
  TouchableOpacity,
} from 'react-native';

import { createDrawerNavigator, createAppContainer } from 'react-navigation';

import Dashboard from './screens/dashboard';
import Profile from './screens/profile';
import ProductDetail from './screens/productDetail';

import Search from './screens/search';

const RouteConfigs = {
  Dashboard: { screen: Dashboard },
  Profile: { screen: Profile },
  ProductDetail: { screen: ProductDetail },
  Search: { screen: Search }
};

const DrawerNavigatorConfig = {
  initialRouteName: 'Dashboard',
  drawerWidth: 300,
  drawerPosition: 'left',
  useNativeAnimations: false,
  drawerBackgroundColor: 'transparent',
  contentComponent: BuyerDrawerContentComponent,
  contentOptions: {
    activeTintColor: 'black',
    activeBackgroundColor: 'transparent',
    inactiveTintColor: 'black',
    itemsContainerStyle: {
      marginVertical: 0,
    },
    iconContainerStyle: {
      opacity: 1,
    },
    itemStyle: {
      height: 40,
    },
    labelStyle: {
      fontSize: 25,
      fontWeight: '100',
      color: '#eee',
    },
  }
};

const BuyerStack = createDrawerNavigator(RouteConfigs, DrawerNavigatorConfig);

export default createAppContainer(BuyerStack);

*And the Tab Navigation index file *

import React from 'react';
import { View, StyleSheet } from 'react-native';

import { createMaterialTopTabNavigator, createAppContainer } from 'react-navigation';

import Header from '../../../components/Header';

import Bids from './screens/bids';
import Products from './screens/products';
import MandiPrices from './screens/mandiPrices';
import { GREEN_PRIMARY } from '../../../theme/colors';

const SellerDashboard = createMaterialTopTabNavigator({
  Bids,
  Products,
  MandiPrices
},
{
  initialRouteName: 'Bids',
  tabBarOptions: {
    style: {
      backgroundColor: '#fff'
    },
    activeTintColor: GREEN_PRIMARY,
    inactiveTintColor: '#ccc',
    indicatorStyle: {
      backgroundColor: GREEN_PRIMARY
    }
  }
});

const SellerDashboardWithAppContainer = createAppContainer(SellerDashboard);

const SellerDashboardWithHeader = () => (
  <View style={styles.wrapper}>
    <Header title="Dashboard" />
    <SellerDashboardWithAppContainer />
  </View>
);

export default SellerDashboardWithHeader;

const styles = StyleSheet.create({
  wrapper: {
    flex: 1,
  }
});

**Comment by brentvatne** [comment]
hi! we need a minimal runnable reproducible example to validate this. see https://stackoverflow.com/help/mcve for information on how to do this and create a new issue with it when it’s ready, thanks!
