### ISSUE TITLE
drawer navigator goBack returns to initial page

### ISSUE THREAD

**Issue by vatex** [react-navigation/react-navigation#5392]
Hello,

I have one problem with my project. I have the Initial route in stack navigator and after that all another route is in drawer navigator.

```
const RootStack = createStackNavigator({
  Init: {
    screen: Init,
    navigationOptions: {
      header: null
    }
  },
  Landing: {
    screen: Landing,
    navigationOptions: {
      header: null
    }
  },
  GetStarted: {
    screen: GetStarted,
    navigationOptions: {
      header: null
    }
  },
  AuthPhoneNumber: {
    screen: AuthPhoneNumber,
    navigationOptions: {
      header: null
    }
  },
  AuthPhoneReceivedCode: {
    screen: AuthPhoneReceivedCode,
    navigationOptions: {
      header: null
    }
  },
  AuthProfile: {
    screen: AuthProfile,
    navigationOptions: {
      header: null
    }
  },

  Drawer: {
    navigationOptions: {
      header: null
    },
    screen: createDrawerNavigator({
      HomePage: {
        screen: HomePage
      },
      ChooseDriverOrPassenger: {
        screen: ChooseDriverOrPassenger
      },
      SelectYourPayment: {
        screen: SelectYourPayment
      },
      SearchDriversOrPassengers: {
        screen: SearchDriversOrPassengers
      },
      CommuteHasPlanned: {
        screen: CommuteHasPlanned
      },

      SearchAddress: {
        screen: SearchAddress
      },

      MainMenu: {
        screen: MainMenu
      },
      Settings: {
        screen: Settings
      },
      Profile: {
        screen: Profile
      },
      IDCard: {
        screen: IDCard
      },
      IDCardPhoto: {
        screen: IDCardPhoto
      },
      IDCardSelfiePhoto: {
        screen: IDCardSelfiePhoto
      },
      IDCardProcessComplete: {
        screen: IDCardProcessComplete
      },
      IDCardProcessCompleteVerified: {
        screen: IDCardProcessCompleteVerified
      },

      MyAddresses: {
        screen: MyAddresses
      }
    }, {
      contentComponent: MainMenu
    })
  }

}, {
  initialRouteName: 'Init'
});
```

When "Init" screen runs, then it redirects user to "HomePage" screen, so in this video user is already on DrawerNavigator page.

I have 4 screens, I am moving forward and when I click the back button (`this.props.navigation.goBack();`) it returns to the initial page. I want to return to the previous page.

I tried `backBehavior: 'none'` but still same result :/

Video: https://photos.app.goo.gl/GNWtb5YjZ7k7L6pBA

| software         | version
| ---------------- | -------
| react-navigation | 2.10.0
| react-native     | sdk-29.0.0
| node             | 8.11.3
| npm or yarn      | npm

**Comment by brentvatne** [comment]
@vatex - the issue template clearly asks for a minimal reproducible example, if you are unsure how to make one feel free to dm me on slack with questions :)

**Comment by brentvatne** [comment]
https://stackoverflow.com/help/mcve could helpful!

**Comment by vatex** [comment]
@brentvatne Thanks. I don't have enough time to cut some part of code from the big project and make it work and spend time on it, so is there any option to easily upload the whole project on snack?

**Comment by andrewtheone** [comment]
@vatex Have you figured it out? Im having the same issue.

**Comment by vatex** [comment]
@andrewtheone Yes. DrawerNavigator doesn't have that functionality to go back with one step. You have to make DrawerNavigator and after that make nested StackNavigator in it, so you will be on stack navigator's page and you will be able to use mentioned functionality without any kind of problem.
I mean something like that:
```
Drawer: {
    navigationOptions: {
      header: null
    },
    screen: createDrawerNavigator({
        createStackNavigator({
      HomePage: {
        screen: HomePage
      },
      ChooseDriverOrPassenger: {
        screen: ChooseDriverOrPassenger
      },
      SelectYourPayment: {
        screen: SelectYourPayment
      }
        })
    })
}
```

**Comment by avlonder** [comment]
Any updates on this? Isn't the drawer navigator able to do this out of the box yet?

**Comment by developius** [comment]
Hmm. I think having a nested stack breaks the navigation hierarchy as when opening multiple screens from the drawer sequentially, you have to press 'back' multiple times to get back to the original screen. I would expect it to be just one 'back' action but adding the nested navigator means we get another history stack...

**Comment by bismarkokletey** [comment]
> Hmm. I think having a nested stack breaks the navigation hierarchy as when opening multiple screens from the drawer sequentially, you have to press 'back' multiple times to get back to the original screen. I would expect it to be just one 'back' action but adding the nested navigator means we get another history stack...

I think for your issue, try and limit your navigators to a max of two. Too much nestings accompanied with multiple navigators reduces your apps performance on a general and puts too much load on the JS Renderer. 
With proper planning, your navigation should be quite okay

**Comment by bismarkokletey** [comment]
Add `backBehavior = "history"`  props to `<Drawer.Navigator>` like so

`
<Drawer.Navigator
  ...
  backBehavior = "history"
  ...
>
... 
your tabs here
...
</Drawer.Navigator>
`

**Comment by CarlosEduardoC1** [comment]
@BismarkCodes I almost posted here that I'm having the same problem, but your comment saved me. Thank you very much

**Comment by miraclemenikelechi** [comment]
> Add `backBehavior = "history"` props to `<Drawer.Navigator>` like so
> 
> `<Drawer.Navigator backBehavior = "history"> your tabs here </Drawer.Navigator>`

the relief. tysm

**Comment by PaudelSworup** [comment]
> Add `backBehavior = "history"` props to `<Drawer.Navigator>` like so
> 
> `<Drawer.Navigator backBehavior = "history"> your tabs here </Drawer.Navigator>`

thanks mate it works perfectly

**Comment by BismarkCodes** [comment]
> > Add `backBehavior = "history"` props to `<Drawer.Navigator>` like so
> > `<Drawer.Navigator backBehavior = "history"> your tabs here </Drawer.Navigator>`
> 
> thanks mate it works perfectly

Glad I could help

**Comment by BismarkCodes** [comment]
> > Add `backBehavior = "history"` props to `<Drawer.Navigator>` like so
> > `<Drawer.Navigator backBehavior = "history"> your tabs here </Drawer.Navigator>`
> 
> the relief. tysm

Glad I could help mate

**Comment by BismarkCodes** [comment]
> @BismarkCodes I almost posted here that I'm having the same problem, but your comment saved me. Thank you very much

Glad I could help
