### ISSUE TITLE
Can't resolve '@react-navigation/web'

### ISSUE THREAD

**Issue by hyochan** [react-navigation/react-navigation#5393]
### Current Behavior

- What code are you running and what is happening?
I am currently working on my [boilerplate](https://github.com/dooboolab/dooboo-native-js/tree/web-support).
- Include a screenshot if it makes sense.
![image](https://user-images.githubusercontent.com/27461460/50058610-045b0a00-01be-11e9-9432-edec912f52cf.png)

### Expected Behavior

- What do you expect should be happening?
`webpack` to run successfully.

### How to reproduce
1. `git clone https://github.com/dooboolab/dooboo-native-js.git`
2. `git checkout web-support`
3. `npm install`
4. `webpack`

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.0.8
| react-native     |  0.57.8
| node             | 10.14.2
| npm      | 6.4.1

**Comment by brentvatne** [comment]
it looks like you didn't install @react-navigation/web in your project: https://github.com/dooboolab/dooboo-native-js/blob/web-support/package.json#L28-L40

have a look at https://github.com/react-navigation/example-web and https://github.com/react-navigation/web-server-example for more inspiration

**Comment by hyochan** [comment]
@brentvatne Thanks. I thought
```
"@react-navigation/core": "3.0.0-alpha",
"@react-navigation/web": "^1.0.0-alpha",
```
Above packages are auto installed in `react-navigation`. What's surprising is that it worked before even I haven't installed them. It suddenly didn't work (yes. I am not lying).

**Comment by brentvatne** [comment]
it includes react-navigation/core but not web

**Comment by hyochan** [comment]
Thanks for your confirm!
