### ISSUE TITLE
undefined is not an object (evaluating 'newStackActions.map')

### ISSUE THREAD

**Issue by udarts** [react-navigation/react-navigation#5401]
### Current Behavior

I am trying use an in app browser (via webview) and use the following code (url is different for each button I have):

```javascript
import { NavigationActions, StackActions } from 'react-navigation';

navigateToScreen = (url) => () => {
    const navigateAction = StackActions.reset({
      index: 0,
      action: [
        NavigationActions.navigate({ routeName: 'WebDetail', params: { sourceHtml: url } }),
      ],
    });
    this.props.navigation.dispatch(navigateAction);
    this.props.navigation.closeDrawer();
  };
```

What happens is that I get the following error:

![img_0050](https://user-images.githubusercontent.com/11528890/50118844-497c4c00-0251-11e9-89c7-127bc44de5af.jpg)

### Expected Behavior

I expect to go to the "WebDetail" screen, showing me the webview with webpage

### How to reproduce

This is the expo, to reproduce it: 

https://snack.expo.io/@udarts2/test

On the expo, the error message is slightly different:

```
undefined is not an object (evaluating '$.map')
```
The screenshot shows the error I had on my iPhone.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.0.8
| react-native     | 0.57.8
| node             | 11.0
| npm or yarn      | npm 6.4.1

**Comment by eriveltonelias** [comment]
Hi @udarts! 

check it, please: https://snack.expo.io/@eriveltonelias/test

**Comment by udarts** [comment]
Thanks for the reply, will check when I can and let you know

**Comment by eriveltonelias** [comment]
Cool!

**Comment by udarts** [comment]
Ok, I have tested your version.

I have modified your code again to match what I use as close as possible.
The first time you click on an item in the sidebar, it passes it. When I open the sidebar again, and click on any of the items (even the previous one), nothing happens.

This is basically what happens with my code. It goes to the screen, but the param is not passed to it.

Here is the expo:

https://snack.expo.io/@udarts2/test

**Comment by udarts** [comment]
@eriveltonelias can this issue be reopened? As it is not solved yet.

Thanks

**Comment by eriveltonelias** [comment]
Hi @udarts! 
 I just updated the example: https://snack.expo.io/@eriveltonelias/test

**Comment by udarts** [comment]
Hi @eriveltonelias!
Will check when I can and let you know.

**Comment by udarts** [comment]
Hi @eriveltonelias,

Just want to let you know it works, was missing the componentWillReceiveProps part.
I made a small modification to your code, so I can still use the dynamic function, instead of having multiple separate functions for each link.

https://snack.expo.io/@udarts2/test

Cheers
