### ISSUE TITLE
Toggle drawer by a tab bar button

### ISSUE THREAD

**Issue by proxyjan** [react-navigation/react-navigation#5406]
Toggle drawer by tab bar button press with an anonymous inline function

I'm having a hard time to know what to do to make this work! I tried to pass props but I could't make it work. I tried to use static methods on the drawer class, yet, failed. I can use any help, and a good solution, thanks.
Here are the relevant codes:

```js
export const MyCustomTab = createBottomTabNavigator(
{
  profile: ProfilePage,
  menu: {
    screen: () => null,
	navigationOptions: () => ({
        tabBarOptions: {
        showLabel: false
      },
	tabBarIcon: (
        <TouchableOpacity onPress = {() => [TOGGLE HERE]}> 
           <Image style = {MainStyles.TabbarMenuIcon} source={require('./resources/Icons/tab_bar_menu.png')}></Image>
        </TouchableOpacity>
      ),
		tabBarOnPress: () => {[TOGGLE HERE]}
	})
    },
},

const MyCustomDrawer = createDrawerNavigator(
  {
    Main: {
      screen: MainScreen
    },
    Setting: {
      screen: SettingScreen
    }
}
class MainScreen extends React.Component {
  constructor(props) {
    super(props);
  }

  static navigationOptions = {
    drawerLabel:  'main screen',
  };

  render() {
    return (
      <MyCustomTab/>
    );
  }
}
```

What should I type instead of [TOGGLE HERE] to access the drawer props navigation and toggle it? (We are in myCustomTab)

Just a quick note, the tab bar 'menu' button directs to nothing, no screen, I'm using it only as a button to open the drawer, which I'm having problems making it work!

---
### Environment
* React Native Navigation version: 2
* React Native version: 0.57.4
* Platform(s) (iOS, Android, or both?): BOTH
* Device info (Simulator/Device? OS version? Debug/Release?): simulator android 8

**Comment by subhendukundu** [comment]
Did you figure out how to fix it?

**Comment by proxyjan** [comment]
> Did you figure out how to fix it?

Just a workaround for now. I assigned this navigation reference to my main component's context and used it everywhere I needed it, for instance the codes above inside [toggle here].

**Comment by subhendukundu** [comment]
Umm I fixed with https://stackoverflow.com/questions/54580896/how-to-open-drawer-without-navigating-to-the-screen-from-one-of-the-tabs-of-tabn

**Comment by haymouz** [comment]
> Umm I fixed with https://stackoverflow.com/questions/54580896/how-to-open-drawer-without-navigating-to-the-screen-from-one-of-the-tabs-of-tabn

Can you help with the code sample.. I really did not understand that code sample in the link provided
