### ISSUE TITLE
StackNavigator inside StackNavigator error

### ISSUE THREAD

**Issue by maxgeraci** [react-navigation/react-navigation#5407]
I'm working on a mobile app in vue-native and I'm almost done with the navigation file but I've got 1 more problem. My code looks like this:

```
`const DashboardStack =  StackNavigator(
         {
              Dashboard: { screen: DashboardScreen },
              Content: { screen: ContentScreen },
         },
         {
              initialRouteName: "Dashboard",
              headerMode: "none"
         }
 );

 const AddLinkStack = StackNavigator(
         {
              AddLink: { screen: AddLinkScreen },
              Content: { screen: ContentScreen },
         },
         {
              headerMode: "none"
         }
 );

 const tabNavScreen = TabNavigator(
         {
              Dashboard: { screen: DashboardStack },
              AddLink: { screen: AddLinkStack },
         },
         {
              tabBarPosition: "bottom",
              tabBarComponent: TabBarBottom
         }
 );

 const Drawer = DrawerNavigator(
         {
              tabNav: { screen: tabNavScreen }
         },
         {
              contentComponent: props => <Sidebar {...props} />
         }
 );

 const AppNavigation = StackNavigator(
         {
              Home: { screen: HomeScreen },
              Login: { screen: LoginScreen },
              LoggedIn: { screen: Drawer },
         },
         {
              headerMode: "none"
         }
 );`
```

Whenever I'm logged in and in the DashboardStack I want to be able to logout and go back to the HomeScreen. I try to do this with the following function:

`const resetAction = NavigationActions.reset({
    index: 0,
    actions: [NavigationActions.navigate({routeName: "Home"})]
})`

But whenever I click on the logout button that executes that function it tells me that the route is not defined and that I have to choose between Dashboard or Content instead of Home. How do I go back to the AppNavigationStack so I can go to the Home route? Or am I doing this completely wrong and do I have to change some of my code?

Also another small question. Whenever I'm in the ContentScreen inside the DashboardStack and I slide from left to right on my screen I want to go back to the DashboardScreen but instead it opens the Drawer. Is there a way to prevent it from opening the drawer? I only want to be able to open the drawer in the DashboardScreen and not in any of the other screens in the stack? Thanks.

**Comment by gutoglup** [comment]
@maxgeraci Did you find any solution to the problem? Because I'm dealing with the same problem. When I click to return home, no action happens.

**Comment by maxgeraci** [comment]
@gutoglup Yes I did. Do you still need the solution?

**Comment by gutoglup** [comment]
@maxgeraci  yes, if you can provide. :D

**Comment by maxgeraci** [comment]
I made a SwitchNavigator instead of a StackNavigator and put 2 screens in there. LoggedOut and LoggedIn. The loggedOut screen is a StackNavigator with a Homescreen and a Loginscreen(when you open the app you get to the Homescreen, then press a login button to go to the Loginscreen). The LoggedIn screen is a Drawer (because all my LoggedIn screens have a drawer, if you don't have a drawer you should put a TabNavigator in there. If you don't have a TabNavigator you should put a StackNavigator in there. If you do have a drawer you should put the TabNavigator inside the drawer and then put all the different Tabs in the TabNavigator. All my Tabs are StackNavigators so I've got 5 StackNavigators inside the TabNavigator. If you got more questions, ask them.
