### ISSUE TITLE
Navigate outside Drawer to Stack - Nothing Happen

### ISSUE THREAD

**Issue by gutoglup** [react-navigation/react-navigation#5408]
I'm working on a mobile app in react-native and I'm almost done with the navigation file but I've got 1 more problem. My code looks like this:

``` javascript
const drawer = createDrawerNavigator({
  Dashboard: {
    screen: Dashboard,
  },
});

const Stack = createStackNavigator({
  Login: {
    screen: Login,
  },
  Drawer: {
    screen: drawer,
  },
});
```
Whenever I'm logged in and in the Dashboard, I want to be able to logout and go back to the Login screen. I try to do this with the following function:

``` javascript
const resetAction = StackActions.reset({
  index: 0,
  actions: [NavigationActions.navigate({ routeName: 'Login' })],
});
this.props.navigation.dispatch(resetAction);
```

But whenever I click on the logout button that executes that function nothing happen. How do I go back to the `Login` screen so I can go to the Home route?
Have any suggestion about that?

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2x
| react-native     | 0.57

**Comment by vonovak** [comment]
hi! have you tried adding `key: null` to the `resetAction`? (see https://reactnavigation.org/docs/en/stack-actions.html#reset)

**Comment by wbbernardes** [comment]
Same issue here, i can't go back from createDrawerNavigator to createStackNavigator

**Comment by gutoglup** [comment]
@vonovak I do that, but continue the problem. Nothing happens

**Comment by vonovak** [comment]
@gutoglup then if you think this is a bug, we'll need a repro, and if this is a question, I recommend asking on StackOverflow

**Comment by gutoglup** [comment]
@vonovak  In this case, it's a bug. 
I upload the exemple in github
https://github.com/gutoglup/exempleDrawer
Please, if anyone can see the code.
Ty

**Comment by gutoglup** [comment]
@vonovak I test with version 3.x of `react-navigation`. And have the same problem too.

**Comment by brentvatne** [comment]
of course nothing happens there, you immediately replace the screen with the Drawer route every time it mounts, so it switches to Login then immediately back to Drawer when you reset :P this is a bug in your app code, not react-navigation. notice if you change to a button it works fine. https://snack.expo.io/@notbrent/vengeful-strawberries
