### ISSUE TITLE
react-navigation is incompatible with react-native-maps

### ISSUE THREAD

**Issue by MicahSteinbrecher** [react-navigation/react-navigation#5411]
My project fails to run react-navigation's getting started code after being configured to use the react-native-maps library. This projects fails on any usage of 'createStackNavigator' with the following behavior:
<img width="348" alt="screen shot 2018-12-21 at 4 38 14 pm" src="https://user-images.githubusercontent.com/7705126/50366377-ed5e4400-053e-11e9-883d-309638a57543.png">

To reproduce:
1) create new react-native project (react-native init <project> in terminal)
2) follow the 'Installation' and 'Build configuration on iOS Using CocoaPods' procedures from these docs: https://github.com/react-native-community/react-native-maps/blob/master/docs/installation.md
3) Install react-navigation and run the 'Hello React Navigation' code as documented here: https://reactnavigation.org/docs/en/getting-started.html

Note: The 'gesture- handler' module is properly linked, and deintegrating cocoapods and reinstalling node modules without react-native-maps solves the issue

Environment:

react-navigation: 3.0.9
react-native: 0.57.8
node: 10.14.1
npm: 6.4.1

**Comment by brentvatne** [comment]
this error indicates that react-native-gesture-handler is not properly linked :\ this isn't related to react-navigation aside from the fact that react-native-gesture-handler depends on it. if you can provide an example app that reproduces the problem, as required by the issue template, please open a new issue with it. thanks!
