### ISSUE TITLE
navigation.navigate opens white page

### ISSUE THREAD

**Issue by KerimHelal** [react-navigation/react-navigation#5412]
Hello everyone,
i followed the tutorial of auth screens in react-navigation docs and i made the same flow, however it doesnt work if i use the this.props.navigation.navigate function, so the auth screen loads normally and all is good but if i use this function it just returns a white page eventhough this page has content inside it
Here's a link to my expo snack
https://snack.expo.io/BkaQhl2gV

**Comment by brentvatne** [comment]
hi there! this is a question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.
