### ISSUE TITLE
Bottom Tab Navigation with an arc/hump

### ISSUE THREAD

**Issue by imMayankRaj** [react-navigation/react-navigation#5413]
![image](https://user-images.githubusercontent.com/25002339/50385752-93a57780-0700-11e9-9ab4-b69aaa92721d.png)

How do create something as above in react native ?

**Comment by eriveltonelias** [comment]
hi there! this is a question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.
