### ISSUE TITLE
Is it possible to have header title when i am using TabNavigation?

### ISSUE THREAD

**Issue by isalo** [react-navigation/react-navigation#5414]
I am using latest vestion of everything.

Is it possible to have header title when i am using TabNavigation?

```
const RootNavigator = createStackNavigator({
	...publicScreens,
	Private: {
		screen: PrivateNavigator
	}
}, publicScreensConfig);

const privateScreens = {
	ContactList: {
		screen: ContactList
	},
	Settings: {
		screen: Settings
	}
};
.....
export default createBottomTabNavigator( privateScreens, options );
```

```
import React, { Component } from 'react'
import { Text, View } from 'react-native'
import GlobalColors from '../../config/colors';

export default class Settings extends Component {
	static navigationOptions = {
		title: 'Settings',
		headerStyle: {
			backgroundColor: GlobalColors.grayDark,
		},
		headerTintColor: 'white',
		headerTitleStyle: {
			fontWeight: 'bold',
		},
		gesturesEnabled: false,
	}

	render() {
		return (
			<View>
        <Text> Settigs </Text>
      </View>
		)
	}
}
```

But i see empty header

![image](https://user-images.githubusercontent.com/4482769/50386619-145d7700-06f3-11e9-8313-2e155b5ba338.png)

**Comment by eriveltonelias** [comment]
hi there! this issue tracker is reserved for bugs only. your post seems to be a usage question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help. thanks!

**Comment by isalo** [comment]
it looks for me like a bug, because i didn't find any way to make it work.

**Comment by eriveltonelias** [comment]
@isalo, thanks! post a new issue following the issue template, please.

**Comment by JinHoSo** [comment]
same here +1

**Comment by JinHoSo** [comment]
I solved it.
You can use 'getActiveChildNavigationOptions' for setting title on tab screen 
```
const bottomTabNavigator = createBottomTabNavigator(...)
```

```
bottomTabNavigator.navigationOptions = ({navigation, screenProps}) => {
  const childOptions = getActiveChildNavigationOptions(navigation, screenProps)
  return {
    title      : childOptions.title,
    headerLeft : childOptions.headerLeft,
    headerRight: childOptions.headerRight,
  }
}
```

**Comment by isalo** [comment]
cool, thanks. Great job. It works for me too.

**Comment by forrest23** [comment]
> I solved it.
> You can use 'getActiveChildNavigationOptions' for setting title on tab screen
> 
> ```
> const bottomTabNavigator = createBottomTabNavigator(...)
> ```
> ```
> bottomTabNavigator.navigationOptions = ({navigation, screenProps}) => {
>   const childOptions = getActiveChildNavigationOptions(navigation, screenProps)
>   return {
>     title      : childOptions.title,
>     headerLeft : childOptions.headerLeft,
>     headerRight: childOptions.headerRight,
>   }
> }
> ```

It works for me too.Thank You!

**Comment by zcgit** [comment]
@JinHoSo thank you very much,  I think it should be a bug, at version 1.x, I can set the navigationOptions like below:
```
export default class TestScreen extends Component {
   //we can hide header 
    static navigationOptions = ({navigation}) => ({header: null})
}
```
but at version 3.x, it doesn't work.

**Comment by Rutheniceye92** [comment]
> I solved it.
> You can use 'getActiveChildNavigationOptions' for setting title on tab screen
> 
> ```
> const bottomTabNavigator = createBottomTabNavigator(...)
> ```
> 
> ```
> bottomTabNavigator.navigationOptions = ({navigation, screenProps}) => {
>   const childOptions = getActiveChildNavigationOptions(navigation, screenProps)
>   return {
>     title      : childOptions.title,
>     headerLeft : childOptions.headerLeft,
>     headerRight: childOptions.headerRight,
>   }
> }
> ```

it gives error: can't find variable 'getActiveChildNavigationOptions'.
I'm using v3.11

**Comment by Rutheniceye92** [comment]
For me following approach worked..

```
const bottomTabNavigator = createBottomTabNavigator(...)

bottomTabNavigator .navigationOptions = ({ navigation }) => {
  const { routeName } = navigation.state.routes[navigation.state.index];

  // You can do whatever you like here to pick the title based on the route name
  const headerTitle = routeName;

  return {
    headerTitle,
  };
};
```
It displays the headerTitle defined in each screens navigationOptions.

**Comment by plockxng** [comment]
> > I solved it.
> > You can use 'getActiveChildNavigationOptions' for setting title on tab screen
> > ```
> > const bottomTabNavigator = createBottomTabNavigator(...)
> > ```
> > 
> > 
> > ```
> > bottomTabNavigator.navigationOptions = ({navigation, screenProps}) => {
> >   const childOptions = getActiveChildNavigationOptions(navigation, screenProps)
> >   return {
> >     title      : childOptions.title,
> >     headerLeft : childOptions.headerLeft,
> >     headerRight: childOptions.headerRight,
> >   }
> > }
> > ```
> 
> it gives error: can't find variable 'getActiveChildNavigationOptions'.
> I'm using v3.11

Hi @Rutheniceye92 I believe you will need to import `getActiveChildNavigationOptions`.

```javascript
import {
    ...
    getActiveChildNavigationOptions} from 'react-navigation';
```

Cheers.

**Comment by martinattin** [comment]
> I solved it.
> You can use 'getActiveChildNavigationOptions' for setting title on tab screen
> 
> ```
> const bottomTabNavigator = createBottomTabNavigator(...)
> ```
> 
> ```
> bottomTabNavigator.navigationOptions = ({navigation, screenProps}) => {
>   const childOptions = getActiveChildNavigationOptions(navigation, screenProps)
>   return {
>     title      : childOptions.title,
>     headerLeft : childOptions.headerLeft,
>     headerRight: childOptions.headerRight,
>   }
> }
> ```

thanks a lot for this...
i also faced similiar problem with react navigation V4,
Able to solve it using getActiveChildNavigationOptions()
