### ISSUE TITLE
How do I load my own function with 'tabBarOnPress'?

### ISSUE THREAD

**Issue by chai86** [react-navigation/react-navigation#5415]
I'm trying to load my imagePicker() function each time a particular tab is selected. Right now im trying to hijack onTabFocus, but its not working. Is there any other way that i can achieve this?

       

            export class AddImage extends Component{

               imagePicker(){
                    //definition of function.......
               }

           static navigationOptions = ({navigation}) => {
             return {
                 tabBarOnPress({jumpToIndex, scene}) {
                      navigation.state.params.onTabFocus();
                 }
             }
            }
             componentDidMount(){
                this.props.navigation.setParams({onTabFocus: this.imagePicker.bind(this)})
            }
           }

       export default createBottomTabNavigator({
                 Home: { screen: Home, 
                  navigationOptions:{
                      tabBarLabel: 'Home',
                      tabBarIcon: ({tintColor})=>(<Icon name="home" color={tintColor} size={24}/>)
                  }
                },
            AddImage: { screen: AddImage
              navigationOptions:{
               tabBarLabel: '',
               tabBarIcon: ({tintColor})=>(<Icon name="plus-square" color={tintColor} size={24}/>),
               tabBarOnPress: ({navigation})=> {navigaition.state.params.onTabFocus() },
               }
             },
                Settings: { screen: Settings,
                  navigationOptions:{
                    tabBarLabel: 'Settings',
                    tabBarIcon: ({tintColor})=>(<Icon name="cog" color={tintColor} size={24}/>)
                  }  
                 },
            },

            {//other bottom tab configurations
              order: ['Home', 'AddImage', 'Settings'],
              }
            });
```

**Comment by eriveltonelias** [comment]
hi there! this issue tracker is reserved for bugs only. your post seems to be a usage question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help. thanks!
