### ISSUE TITLE
Header back button is not working by default in react-navigation v3

### ISSUE THREAD

**Issue by TechSatya** [react-navigation/react-navigation#5417]
Sorry to post here.
I need immediate attention from you guys, so I'm asking over here.

I have already posted this question in StackOverflow and here is the [link](https://stackoverflow.com/questions/53911951/header-back-button-is-not-working-by-default-in-react-navigation-v3).

-- react-navigation version - v3.0.5

I request you to respond it asap as it is a bit urgent.

Thank you :)

**Comment by TechSatya** [comment]
@brentvatne @ericvicenti

**Comment by eriveltonelias** [comment]
Hi @TechSatya 

I just created an example: https://snack.expo.io/@eriveltonelias/default-header-back-button  and it's working as expected, if it is not what you are looking for, post a new issue following the template, please.

**Comment by TechSatya** [comment]
Hi @eriveltonelias 
Thank you for your early response but after a lot of experiment, surprisingly I found that in `headerStyle:` giving `paddingBottom:` messes up the clicking functionality in the back button.

But had no idea, why this?
If you have any words about it then please do reply.

I had my `headerStyle` like below;

```
headerStyle: {
      height: 0,
      marginTop: 0,
      paddingTop: 10,
      paddingBottom: 30,
      backgroundColor: '#cb7429'
    },
```
