### ISSUE TITLE
Mobx with react navigation 3.X

### ISSUE THREAD

**Issue by kkrishnan90** [react-navigation/react-navigation#5424]
Can anyone please guide me on how to include providers (mobx stores) using react navigation 3.X ? Earlier in 2.X we used to do it by integrating it to App.js and thereby providing stores. 
But in 3.X, there's this app container which is exported as a default one. 

Can someone quickly direct me to the right docs or tutorial to integrate it ? 
Thank you so much in advance!

**Comment by brentvatne** [comment]
you can use the result from createAppContainer the same as you did before

```js
const RootNavigator = createAppContainer(SomeNavigator);

export default class Whatever extends React.Component {
  render() {
    return <Provider><RootNavigator /></Provider>
  }
}
```

if someone wants to help out with documenting using react-navigation with state managers, we have an issue for that here: https://github.com/react-navigation/react-navigation.github.io/issues/323

**Comment by Vibing** [comment]
@brentvatne hi，this is my code:
```js
import React, { Component } from 'react';
import { createStackNavigator, createAppContainer } from 'react-navigation';
import { Provider } from 'mobx-react';
import { routes, initRoute } from './routes';
import appStore from './store';

const StackNavigato = createStackNavigator(routes, {
  initialRouteName: initRoute
});

const AppContainer: any = createAppContainer(StackNavigato);

export default class MzEntrance extends Component<any, any> {
  render() {
    return (
      <Provider appStore={appStore}>
        <AppContainer />
      </Provider>
    );
  }
}
```

but it not work.
![微信截图_20190708152617](https://user-images.githubusercontent.com/10387532/60790772-d73f6a80-a194-11e9-92ae-9b71e34acfd2.png)
![微信截图_20190708152632](https://user-images.githubusercontent.com/10387532/60790773-d7d80100-a194-11e9-8dfe-b62f1e230c39.png)

please guide me on how to include providers (mobx stores) using react navigation 3.X
