### ISSUE TITLE
The running program reports an error, the error reason: undefined is not an object (evaluating ‘RNGestureHandlerModule.State’)  but only when I try to use 'createStackNavigator'. Works as long as I stick to just 'createBottomTabNavigator'.

### ISSUE THREAD

**Issue by Shaopeng5236** [react-navigation/react-navigation#5425]
First I created a new iOS project.
then I Integration of React Native.
According to the tutorial access using React Navigation, the link has also been successful
Link: https://reactnavigation.org/docs/en/getting-started.html
The steps are as follows
1.npm install --save react-navigation
2.npm install --save react-native-gesture-handler
3.react-native link react-native-gesture-handler
4. pod 'React', :path => '../node_modules/react-native', :subspecs => [

    'RCTLinkingIOS',
    . . .
  ]

 The running program reports an error, the error reason: undefined is not an object (evaluating ‘RNGestureHandlerModule.State’)
 but only when I try to use 'createStackNavigator'. Works as long as I stick to just 'createBottomTabNavigator'.

I tried a lot of methods that I could search for, and I tried a lot of times and found no solution. I hope I can get your help, thank you!
this code in my index.js

import React from 'react';
import { View, Text ,AppRegistry} from 'react-native';

import {createStackNavigator,createAppContainer,createBottomTabNavigator} from 'react-navigation';

class HomeScreen extends React.Component {
    render() {
        return (
            <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
                <Text>Home Screen</Text>
            </View>
        );
    }
}

class DetailsScreen extends React.Component {
    render() {
        return (
            <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
                <Text>Details Screen</Text>
            </View>
        );
    }
}

const StackRouteConfigs = {
    Home: {
        screen: HomeScreen,
        navigationOptions: {
            header: null
        }
    },
    Moment: {
        screen: DetailsScreen,
        navigationOptions: {
            header: null
        }
    },

};
const StackNavigatorConfigs = {
    initialRouteName: 'Home', // 初始化哪个界面为根界面
    mode: 'card', // 跳转方式：默认的card，在iOS上是从右到左跳转，在Android上是从下到上，都是使用原生系统的默认跳转方式。
    headerMode: 'screen', // 导航条动画效果：float表示会渐变，类似于iOS的原生效果，screen表示没有渐变。none表示隐藏导航条
    gesturesEnabled: false,
    navigationOptions: {
        cardStack: {
            gesturesEnabled: false, //是否可以使用手势关闭此屏幕。在iOS上默认为true，在Android上为false
        },
    },
};

const RootStack = createStackNavigator(StackRouteConfigs,StackNavigatorConfigs);
const AppContainer = createAppContainer(RootStack);

 class TabbarTest extends React.Component {
    render() {
        return (

            <AppContainer/>
        );
    }
}

**Comment by brentvatne** [comment]
tab navigator works for you because it doesn't use react-native-gesture-handler. stack navigator does. this error means that rngh isn't linked properly in your project, be sure to follow the instructions for how to install that, it's not something we help with here though.

**Comment by Shaopeng5236** [comment]
I can use the rngh step 
1.npm install --save react-navigation
2.npm install --save react-native-gesture-handler
3.react-native link react-native-gesture-handler
4. pod 'React', :path => '../node_modules/react-native', :subspecs => [

'RCTLinkingIOS',
. . .

then  In addition to these what else can I do?

**Comment by brentvatne** [comment]
you can follow the steps here: https://kmagiera.github.io/react-native-gesture-handler/docs/getting-started.html#installation

**Comment by Gutyn** [comment]
@brentvatne Did you fix the problem eventually?

**Comment by brentvatne** [comment]
this is not a problem with the library it's a problem with the user's installation of the library. follow setup instructions and you won't have an issue
