### ISSUE TITLE
Hide header for Top Tabs 

### ISSUE THREAD

**Issue by Ahmed-Imam** [react-navigation/react-navigation#5428]
I am trying to hide the default header for the top tabs and display my custom header as the following picture

![48390053_941212549418236_6340296469714567168_n](https://user-images.githubusercontent.com/20854551/50475787-cf8e5480-0a00-11e9-9254-1bad1f3fb187.jpg)

```
const HomeTab = createMaterialTopTabNavigator({
  Tab1: InviHistory,
  Tab2: Shop
},{
  
  defaultNavigationOptions:{
    headerMode:"none"
}
});
```

**Comment by brentvatne** [comment]
const HomeTab = createMaterialTopTabNavigator({
  Tab1: InviHistory,
  Tab2: Shop
},{
  
  navigationOptions: {
    header: null
  }
});

**Comment by Ahmed-Imam** [comment]
it doesn't work @brentvatne

**Comment by zcgit** [comment]
it works for me , thank you !

**Comment by ithustle** [comment]
It doesn't work @brentvatne

**Comment by ithustle** [comment]
> ```js
> const HomeTab = createMaterialTopTabNavigator({
>   Tab1: InviHistory,
>   Tab2: Shop
> },{
>   
>   navigationOptions: {
>     header: null,
>   }
> });
> ```

It doesn't work on v3 - 3.11.0

**Comment by lommaj** [comment]
```javascript
const HomeTab = createMaterialTopTabNavigator({
  Tab1: InviHistory,
  Tab2: Shop
},{
  
  tabBarOptions: {
    style: {
      display: 'none'
    }
  }
});
```
