### ISSUE TITLE
Why can 'createBottomTabNavigator' be used, but'createStackNavigator 'can not be used.

### ISSUE THREAD

**Issue by Shaopeng5236** [react-navigation/react-navigation#5429]
Hey, it seems to me like an easy problem.

if rngh isn't linked properly in my project

I want to know Why can 'createBottomTabNavigator' be used, but 'createStackNavigator ' can not be used.

**Comment by brentvatne** [comment]
because bottom tabs does not use react-native-gesture-handler, it never imports it. stack navigator does use it, it's how we do the gesture to swipe away screens
