### ISSUE TITLE
Multiple active screens

### ISSUE THREAD

**Issue by rogerkerse** [react-navigation/react-navigation#5433]
react-native-screens support having multiple active screens at once. How is it possible through react-navigation?

**Comment by brentvatne** [comment]
what I think you're wanting is a modal stack navigator that takes up just part of the screen and the rest of the screen is still interactable, is that right? if so i don't recommend this with the current state of react-navigation, we don't support using stack navigator in small popovers

**Comment by rogerkerse** [comment]
@brentvatne yes exactly that
> a modal stack navigator that takes up just part of the screen and the rest of the screen is still interactable

**Comment by brentvatne** [comment]
sadly that's not supported by stack navigator at the moment. you can open a feature request on https://react-navigation.canny.io/feature-requests if you like but i don't plan on working on this any time soon. you're welcome to build your own navigator to do this! react-navigation was built to be extensible! you can use https://github.com/react-navigation/react-navigation-stack as a starting point
