### ISSUE TITLE
drawer menu lag on version3

### ISSUE THREAD

**Issue by imansalhi** [react-navigation/react-navigation#5434]
### Current Behavior

-drawer navigation gesture  has lag on android. 
you will face such a bug if you load just a sample project(with no custom them for drawer menu).
I think this problem is because of some bug in  react-navigation 3 

### Expected Behavior

moving drawer menu smoothly 

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |3.0.9
| react-native     |0.57.8
| react-native-gesture-handler    |0.57.8

**Comment by eriveltonelias** [comment]
hi @imansalhi, 

is the duplicate of https://github.com/react-navigation/react-navigation/issues/5287

**Comment by Daimension** [comment]
hope this helps
https://github.com/react-navigation/react-navigation/issues/5329
