### ISSUE TITLE
Idea: preloading

### ISSUE THREAD

**Issue by karsens** [react-navigation/react-navigation#5437]
Hi, this is not really an issue but more of an idea. When you navigate to a new screen for the first time, the component will be mounted and rendered. But then it stays in the background, also if you leave the page. I know this because the second time (going back to the screen), it is much faster! This is certainly the case if there are some remote images on the page. 

I care very much about the UX and it's not nice if the user sees images being loaded. That's why I was thinking... what if you could already mount and render the page before going there? Then the first time experience would be exactly the same as a second time experience and would generally improve the apps experience.

instead of this.props.navigation.navigate(options) we need something like this.props.navigation.preload(options).

**Comment by brentvatne** [comment]
hi, this is a better fit for https://github.com/react-navigation/rfcs

I agree something like this could be nice to have but there's a lot that needs to be unpacked behind what `preload` would do
