### ISSUE TITLE
RNGestureHandlerModule.State

### ISSUE THREAD

**Issue by s349856186** [react-navigation/react-navigation#5440]
I upgrade react-navigation form 1.x to 3.x , and i install "react-native-gesture-handler", According to the tutorial access using React Navigation, the link has also been successful
Link: https://reactnavigation.org/docs/en/getting-started.html 
but IOS get error: [fatal][tid:com.facebook.react.ExceptionsManagerQueue] Unhandled JS Exception: undefined is not an object (evaluating 'RNGestureHandlerModule.State')
and Android get error: undefined is not a function (evaluating '_react2.default.createContext(null)')
How can I solve it? Thanks

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | "^3.0.9",
| react-native     | "0.51.0",
| node             | V8.9.0
| npm      | 5.5.1
| react-native-gesture-handler     | "^1.0.12",

**Comment by shiroganee** [comment]
@s349856186 android error actually means that you need to have createContext available which comes with 16.3 (not really sure if alpha has it available).
I'm not really sure if React Navigation has minimum version of RN and React required, but it seems it does have so (at least version 3 of RN has). Maybe it is worth mentioning in docs that to make it work you need to have minimum version of X of RN.

**Comment by brentvatne** [comment]
the error on ios is due to it not being linked properly. sorry we don't help with that, you'll need to troubleshoot on your own. see installation steps in https://kmagiera.github.io/react-native-gesture-handler/docs/getting-started.html#installation

**Comment by brentvatne** [comment]
@shiroganee - good point re: react-native version. https://github.com/react-navigation/react-navigation.github.io/issues/335
