### ISSUE TITLE
Unmount the previous screen when user choose a new menu item from drawer menu

### ISSUE THREAD

**Issue by gowthamans268** [react-navigation/react-navigation#5441]
##Here is my Drawer Navigation stack

Drawer Navigation 
-- Home Screen (Stack Navigator)
-- Profile Screen (Stack Navigator) 
-  Stack Screen1
- Stack Screen2

-- Data Screen (Stack Navigator)
- Stack Screen3
- Stack Screen4

Say My default route is **Home Screen**, I opened the drawer menu and choose **Data Screen**  and i edited some input fields and defaulted some values fetched from the server through web api in the **Stack screen3** in **ComponentDidMount**.

Now i clicked the **Home Screen** from Menu Drawer and then If i try click the  **Data Screen** from the drawer again the system is not hitting the **ComponentDidMount** method of the **Stack Screen3** it is loading the old page with Old data. I want the system to fetch the updated data and new state when ever i clicked the menu item from DrawerMenu.

Is it possible to trigger unmount of the old StackNavigator/ Clear the stack navigator whenever i choose the new menu item in drawer. 
Or Is it possible to enforce the screen to call **constructor** and **CompoentDidiMount** whenever it is rendered.

### Current Behavior

- System is opening the menu item with old state 

### Expected Behavior

- Either it should unmount the old screen when ever it choose any menu item from the drawer 
- or the **Constructor**  & **ComponentDidMount** should be called every time  whenever i choose the Menu item  

### Your Environment

| software         | version
| ---------------- | -------
"react-navigation": "^3.0.7"
"react-native": "0.57.5",

**Comment by ivan-kaminskyi** [comment]
You can use [navigation events](https://reactnavigation.org/docs/en/navigation-events.html) instead or use unmountInactiveRoutes option. This was [changed in 3.0](https://reactnavigation.org/blog/2018/11/17/react-navigation-3.0.html#drawer-now-keeps-inactive-tabs-in-memory-by-default)

**Comment by IndianNative** [comment]
Hey ivan-kaminskyi did Navigation Events served the purpose, Since I am in same situation and I  am not able to find any solution.

**Comment by haikyuu** [comment]
You can use `unmountInactiveRoutes` or `unmountInactiveScreens` in navigation options

**Comment by antoniotex** [comment]
> You can use `unmountInactiveRoutes` or `unmountInactiveScreens` in navigation options

works for me, thanksssss!
