### ISSUE TITLE
Previous Screens Are Visible When Using TransparentCard

### ISSUE THREAD

**Issue by shanekoss** [react-navigation/react-navigation#5443]
## The issue tracker is reserved for bug reports only.

If you have a question, feature request, or an idea for improving the library or its related tools, please try one of the following resources:

- [Read the documentation](https://reactnavigation.org/)
- [Post an issue to the website repository if you'd like to see a documentation change](http://github.com/react-navigation/website)
- [Post a feature request to Canny](https://react-navigation.canny.io/feature-requests)
- [Write a RFC if you have ideas for how to implement a feature request](https://github.com/react-navigation/rfcs)
- [Get help on Discord chat (#react-navigation on Reactiflux)](https://discord.gg/4xEK3nD) or [on StackOverflow](https://stackoverflow.com/questions/tagged/react-navigation)
- Search for your issue - it may have already been answered or even fixed in the development branch. However, if you find that an old, closed issue still persists in the latest version, you should open a new issue.

Bugs with react-navigation must be reproducible *without any external libraries that operate on it*. This means that if you are attempting to use Redux or MobX with it and you think you have found a bug, you must be able to reproduce it without Redux or MobX in this report. Redux related issues belong in [react-navigation-redux-helpers](https://github.com/react-navigation/react-navigation-redux-helpers), and we do not have any first-class integration with MobX at the moment.

---

### Current Behavior

Previous screens are visible when navigating to other screens

### Expected Behavior

Expected not to see previous screens (as is the case when not using transparent cards)

### How to reproduce

https://snack.expo.io/@shanekoss/transparentcardtest

**Comment by shanekoss** [comment]
Current Behavior:

Previous screens are visible when navigating to other screens

Expected Behavior:

Expected not to see previous screens (as is the case when not using transparent cards)

shown here:

https://snack.expo.io/@shanekoss/transparentcardtest


Thanks!

**Comment by brentvatne** [comment]
I don't understand this issue, the whole reason for `transparentCard` is to get this exact behavior. Why enable it if you don't want that behavior?

**Comment by shanekoss** [comment]
@brentvatne thanks for the speedy reply.  Perhaps my misunderstanding, but I have a larger background that the navigator appears over that I want visible at all times - which is why I want the transparent card.

**Comment by brentvatne** [comment]
we don't explicitly support this use case but in your snack if you get rid of the `transparentCard` option then it should probably work using the config that you have there

**Comment by brentvatne** [comment]
actually I just tested this and indeed we don't support what you're trying to do. if you really want to do this, you can use `transparentCard` and then hide screens manually when they're no longer focused using `withNavigationFocus` or `navigation.addListener`

**Comment by brentvatne** [comment]
also see this related issue - https://github.com/react-navigation/react-navigation/issues/5433 - using stack for only part of the screen is not a well supported use case right now

**Comment by shanekoss** [comment]
@brentvatne thanks for the followup - withNavigationFocus works great.  cheers.

**Comment by cernik** [comment]
@shanekoss Guess, you can achieve it by applying fade transition:

`
    transitionConfig: () => ({
      screenInterpolator: props => {
        const { position, scene } = props;
        const { index } = scene;
        const opacity = position.interpolate({
          inputRange: [index - 0.7, index, index + 0.7],
          outputRange: [0.3, 1, 0.3],
        });
        return {
          opacity,
        };
      },
      containerStyle: {
        backgroundColor: 'transparent',
      },
    })
`

**Comment by elybit** [comment]
{
    transparentCard: true,
    transitionConfig: () => ({
      transitionSpec: {
        duration: 150,
        easing: Easing.out(Easing.poly(2)),
        timing: Animated.timing,
        useNativeDriver: true,
      },
      screenInterpolator: sceneProps => {      
        const { layout, position, scene } = sceneProps
  
        const thisSceneIndex = scene.index
        const width = layout.initWidth
  
        const translateX = position.interpolate({
          inputRange: [thisSceneIndex - 1, thisSceneIndex],
          outputRange: [width, 0],
        })
  
        return { transform: [ { translateX } ] }
      },
        containerStyle: {
            backgroundColor: 'transparent',
        },
        containerStyleLight: {
            backgroundColor: 'transparent',
        },
        containerStyleDark: {
            backgroundColor: 'transparent',
        }
    })
  }
