### ISSUE TITLE
Drawer-Navigator lags on drag-release in 3.0.9

### ISSUE THREAD

**Issue by shahab0105** [react-navigation/react-navigation#5445]
**Current Behavior**
The Drawer navigator lags/freezes when pulled and released in the targeted direction. It works perfect on pressing a button that does openDrawer()/closeDrawer()/toggleDrawer(). It's only when you try drag-then-release the drawer from screen's edge that the transition is really laggy.

**What code are you running and what is happening?**
Just passing a stack navigator to a drawer navigator. Working for a client. I can't share the exact code but it can be replicated.

**Expected Behavior**
The Drawer should open/close if pulled/dragged and then released in the target(open/close) direction. It worked like that in previous versions
 

**How to reproduce**
Just add a stacknavigator to one of the screens of Drawer and the behavior can be replicated

**Solution**
The issue can be resolved by downgrading to version 2.17.0 and locking the version in package.json. No additional changes in code are required(Except removing the createAppContainer that doesn't exist in 2.17.0 )

**Comment by eriveltonelias** [comment]
Hi @shahab0105, thanks for your report. 

we're tracking this issue in here https://github.com/react-navigation/react-navigation/issues/5287

**Comment by Daimension** [comment]
https://github.com/react-navigation/react-navigation/issues/5329
