### ISSUE TITLE
bottomTabbar hide 

### ISSUE THREAD

**Issue by legendOfKage** [react-navigation/react-navigation#5446]
const listStack = createStackNavigator({
  list: {
    screen: listScreen,
    navigationOptions: {
      title: 'list'
    }
  },
  Detail: {
    screen: Detail
  }
});

const bottomTabNavigator = createBottomTabNavigator(listStack);

In the listScreen module, when the component is rendered, I want to swipe up to hide the bottom tabbar and swipe down to show the bottom tabbar. How can I achieve it? I found it impossible to do this with existing apis

This function can be implemented if the listScreen is directly used as a parameter of createBottomTabNavigator.However, using listStack as a parameter to createBottomTabNavigator will not work, the code is as follows

export default class listScreen extends Component {
  constructor(props) {
    super(props);
    this.state = {
      dataSource: [],
      currentOffsetY:0
    };
  }

  static navigationOptions =({navigation,navigationOptions})=>{
    let obj= {
      title:'demo'
    }
    if(navigation.state)
    {
       obj.tabBarVisible=!!navigation.getParam('tabBarVisible',true);
    }
    return obj;
  };

  componentDidMount = () => {
    axios({
      url:'apiurl',
      method: "get",
      params:{
        size: 20,
        pageindex:1
      }
    }).then(response => {
          this.setState({
          dataSource: response.data.list
        });
    }).catch(function(error) {
        console.log(error);
      });
  };

  shouldComponentUpdate(nextProps,nextState){
    return !!(this.state.dataSource==nextState.dataSource)
  }
  
  _onScroll(event) {
    if (Math.abs(event.nativeEvent.contentOffset.y - this.state.currentOffsetY) < 10) {
      return;
    }
    if (this.state.currentOffsetY - event.nativeEvent.contentOffset.y < 0)
          this.props.navigation.setParams({tabBarVisible: false})
    else
          this.props.navigation.setParams({tabBarVisible: true})
    this.setState({
        currentOffsetY:event.nativeEvent.contentOffset.y
     })
  }

  render() {
    return (
      <View style={styles.container}>
        <FlatList
          showsVerticalScrollIndicator={false}
          data={this.state.dataSource}
          renderItem={this.renderItem}
          keyExtractor={item => item.id} 
          onScroll={this._onScroll.bind(this)} 
          scrollEventThrottle={0}
        />
      </View>
    );
  }
### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |3.0.9
| react-native     |0.57.8
| node             |
| npm or yarn      |

**Comment by brentvatne** [comment]
hi there! this is a question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.
