### ISSUE TITLE
BackHandler in Android

### ISSUE THREAD

**Issue by harikanammi** [react-navigation/react-navigation#5448]
This bug occurred on Android devices.

### Current Behaviour
 I am running sample application. I have 4 screens (Screen 1, Screen 2, Screen 3 and Screen 4). In Screen 3 doesn't have back button. In Screen 4 having back button.
In Screen 3 placed this below code for app closing when clicking on backHandler:-
```
handleBackButton = () => {
   const { navigation } = this.props;
   BackHandler.exitApp()
 }

 componentDidMount() {
   BackHandler.addEventListener('hardwareBackPress', this.handleBackButton);
 }

 componentWillUnmount() {
   BackHandler.removeEventListener('hardwareBackPress', this.handleBackButton);
 }
```

In Screen 4 having back button and i clicks on BackHandler app should be closed in Screen 4 also.
I placed this below code When clicking on BackHandler
```
handleBackButton = () => {
   const { navigation } = this.props;
   navigation.pop()
 }

 componentDidMount() {
   BackHandler.addEventListener('hardwareBackPress', this.handleBackButton);
 }

 componentWillUnmount() {
   BackHandler.removeEventListener('hardwareBackPress', this.handleBackButton);
 }
```
Screen 3 Screenshot:-
![screen shot 2019-01-05 at 3 42 25 pm](https://user-images.githubusercontent.com/31063894/50723223-9ccf1500-1100-11e9-8c7c-a80c525aa775.png)
Screen 4 Screenshot:-
![screen shot 2019-01-05 at 3 42 47 pm](https://user-images.githubusercontent.com/31063894/50723226-a9536d80-1100-11e9-99ff-b615fe308806.png)

### Expected Behaviour
When clicking on Screen 4 BackHandler it navigates to Screen 3. But in my case app should be closed while clicking on BackHandler.

###  Environment

>  react-navigation :- 2.17.0
>  react-native :- 0.57.3

**Comment by vonovak** [comment]
hi! We'll need a runnable repro to help. Also, please make sure to check out https://reactnavigation.org/docs/en/navigation-lifecycle.html and https://reactnavigation.org/docs/en/custom-android-back-button-handling.html

**Comment by harikanammi** [comment]
hi @vonovak, i tried this [](https://reactnavigation.org/docs/en/custom-android-back-button-handling.html) but it's not woking for me.

**Comment by brentvatne** [comment]
@harikanammi - create a new issue with a runnable reproducible example. thanks!
