### ISSUE TITLE
I want to show the header on the top of the drawer navigator

### ISSUE THREAD

**Issue by farukozdemirz** [react-navigation/react-navigation#5449]
Hi everybody,

I use react navigation v3. When I was opened the drawer navigator I want to show the header on the top of the drawer navigator. I want to do this but header stay behind.How can I fix that ? 

Thank you :)﻿

-Header-

![ekran resmi 2019-01-05 15 01 34](https://user-images.githubusercontent.com/42621246/50724379-7e1b4f00-10fd-11e9-93c6-0a9051043c26.png)

-Desired Image-

![ekran resmi 2019-01-05 15 04 00](https://user-images.githubusercontent.com/42621246/50724383-9b501d80-10fd-11e9-853a-2296be113f2e.png)

-Current Image-

![ekran resmi 2019-01-05 15 01 52](https://user-images.githubusercontent.com/42621246/50724387-af941a80-10fd-11e9-96f7-82e039a68bbb.png)

`import React, { Component } from "react";
import { StyleSheet, Dimensions } from "react-native";
import { createStackNavigator, createAppContainer, createDrawerNavigator } from "react-navigation";
import {Favori,Help,Logout,Dashboard } from "../Pages";
import CustomHeader from "../Components/Main/CustomHeader";
import DrawerComponent from "../Components/DrawerComponent";
import { colors } from "../styles/utils/styles";

const { width } = Dimensions.get("window");

export default class Navigator extends Component {
	render() {
		return <AppContainer />;
	}
}

const AppStackNavigator = createStackNavigator(
	{	
		Home: Dashboard,
		Favori:Favori,
		Help:Help,
		Logout: Logout
	},
	{
		defaultNavigationOptions: {
			header: props => <CustomHeader {...props} />,
		
		}
	}
);

const AppDrawerNavigator = createDrawerNavigator(
	{
		Favori:{
			screen:AppStackNavigator,
			navigationOptions:{
				drawerLabel:"Favori Listem"
			}
		},
		Help:{
			screen:AppStackNavigator,
			navigationOptions:{
				drawerLabel:"Yardım "
			}
		},
		Logout:{
			screen:AppStackNavigator,
			navigationOptions:{
				drawerLabel:"Çıkış"
			}
		},
	},
	{	
		drawerWidth:width,
		drawerBackgroundColor: colors.$master,
		contentOptions: {
			activeBackgroundColor: colors.$master,
			inactiveBackgroundColor: colors.$master,
			activeTintColor: colors.$white,
			inactiveTintColor: colors.$white
		},
		
		contentComponent: props => (
			<React.Fragment>
				<DrawerComponent props={props} />
			</React.Fragment>
		)
	}
);

const AppContainer = createAppContainer(AppDrawerNavigator);

`

**Comment by vonovak** [comment]
hi there! this issue tracker is reserved for bugs only. your post seems to be a usage question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help. thanks!
