### ISSUE TITLE
Error: Tried to register two views with the same name RNGestureHandlerButton

### ISSUE THREAD

**Issue by spyshower** [react-navigation/react-navigation#5453]
### Current Behavior

After upgrading Expo to 32.0.0, I get the following error:

<img width="416" alt="screenshot 2019-01-07 at 00 57 08" src="https://user-images.githubusercontent.com/7046283/50742680-41437b00-1217-11e9-8410-259bea72b1c9.png">

I check out this issue: https://github.com/react-navigation/react-navigation/issues/5293

Tried to delete react-native-gesture-handler with no luck.

<img width="569" alt="screenshot 2019-01-07 at 01 45 20" src="https://user-images.githubusercontent.com/7046283/50743230-04c74d80-121e-11e9-89fb-4003a720030f.png">

I use the latest versions of Expo, RN, react-navigation and npm.

**Comment by brentvatne** [comment]
run `expo init` to create a new project with the tabs template and notice that it works as expected with the same version of expo and react-navigation. look at the package.json there and compare with yours. it looks like you installed react-native-gesture-handler manually in your project, remove it and remove your package-lock.json and delete node_modules and reinstall. if that doesn't fix it then please share a reproducible example in a new issue as per the issue template, thanks!

**Comment by brentvatne** [comment]
it is entirely under your control, as i mentioned it works on a new project as expected. an example is a *runnable minimal example* - see https://stackoverflow.com/help/mcve for more info

if doing what i described above doesn't work then sorry you need to share a mcve and create a new issue
