### ISSUE TITLE
React Navigation doesn't show the top bar when add createMaterialBottomTabNavigator in Version 3.

### ISSUE THREAD

**Issue by zeta-o** [react-navigation/react-navigation#5454]
Hi Guys, 
I'm using createMaterialBottomTabNavigator to create a bottom tab menu. But when I run the project the header is not showing.

"react-navigation": "^3.0.9",
"react-navigation-material-bottom-tabs": "^1.0.0"

const App = createMaterialBottomTabNavigator({
    Services: {
      screen:ServicesScreen,
      navigationOptions: {
        tabBarLabel: 'Servicios',
        tabBarColor: '#493F97',
        tabBarIcon: ({ tintColor, focused }) => (
            <FontAwesome5 size={25} color="white" name='th-large' solid/>
          )
      },
    },
    Profile: {
      screen:ProfileScreen,
      navigationOptions: {
        tabBarLabel: 'Mi Perfil',
        tabBarColor: '#493F97',
        tabBarIcon: ({ tintColor, focused }) => (
            <FontAwesome5 size={25} color="white" name='user-circle' solid/>
          )
      },
    }
});

export default createAppContainer(App);

**Comment by brentvatne** [comment]
it never did this, you need to use stack navigator to get a navigation bar or just add your own
