### ISSUE TITLE
Stack.navigationOptions override other navigationOptions and removes tabBarIcon

### ISSUE THREAD

**Issue by danieldelouya** [react-navigation/react-navigation#5457]
### Current Behavior
The icon in the bottom tab navigator disappears ss soon as i include the the following code in the file it removes the tabBarIcon for the HomeStack:

```
HomeStack.navigationOptions = ({ navigation }) => {
  let tabBarVisible = true

  const { routeName } = navigation.state.routes[navigation.state.index]

  if (routeName === 'ProfileScreen') {
    tabBarVisible = false
  }

  return {
    tabBarVisible
  }
}
```

```
const HomeStack = createStackNavigator(
  {
    Home: {
      screen: HomeScreen,
      navigationOptions: {
        headerBackTitle: null,
        header: null
      }
    },
    ProfileScreen: {
      screen: ProfileScreen,
      navigationOptions: {
        gesturesEnabled: true,
        headerTitle: null,
        headerTransparent: false,
        headerBackTitle: null,
        headerBackImage: <BackIcon />,
        headerStyle: {
          elevation: 0,
          shadowOpacity: 0,
          borderBottomWidth: 0
        }
      }
    }
  },
  {
    navigationOptions: {
      tabBarLabel: ({ focused }) => {
        return (
          <Text style={focused ? styles.textActive : styles.textInactive}>
            Me
          </Text>
        )
      },
      tabBarIcon: ({ focused }) => focused
          ? <Image source={profileFilled} style={styles.tabBarIconActive} />
         : <Image source={profileOutlined} style={styles.tabBarIconInactive} />

    }
  }
)

HomeStack.navigationOptions = ({ navigation }) => {
  let tabBarVisible = true

  const { routeName } = navigation.state.routes[navigation.state.index]

  if (routeName === 'ProfileScreen') {
    tabBarVisible = false
  }

  return {
    tabBarVisible
  }
}
```

// Later down in the file:

```
export const TabNavigator = createAppContainer(
  createBottomTabNavigator(
    {
      Home: HomeStack,
      Work: WorkStack,
    },
    {
      tabBarOptions: {
        activeTintColor: 'black',
        inactiveTintColor: 'black',
        showLabel: true,
        showIcon: true
      }
    }
  )
)
```

### Expected Behavior

Should not disappear. 

### How to reproduce

- You must provide a way to reproduce the problem. If you are having an issue with your machine or build tools, the issue belongs on another repository as that is outside of the scope of React Navigation.
- Either re-create the bug on [Snack](https://snack.expo.io) or link to a GitHub repository with code that reproduces the bug.
- Explain how to run the example app and any steps that we need to take to reproduce the issue from the example app.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.0.9
| react-native     | 0.57.8
| node             | 10.14.2
| npm or yarn      |

**Comment by brentvatne** [comment]
read https://reactnavigation.org/docs/en/navigation-options-resolution.html and if you still think you have encountered a bug please create a new issue with a reproducible example that we can run, either on snack.expo.io or github

**Comment by danieldelouya** [comment]
@brentvatne Of course I read that. Does not solve my problem.

**Comment by brentvatne** [comment]
ok then please create a new issue following the issue template

**Comment by danieldelouya** [comment]
@brentvatne  Here is the expo example with same issue: 
https://snack.expo.io/@danieldelouya/react-navigation-problem 

Find this line: 
// TRY COMMENTING THIS OUT ABND THE TAB BAR ICON WILL APPEAR

and then you can comment out the following code and see the tab bar icon appear again. 


```
HomeStack.navigationOptions = ({ navigation }) => {
  let tabBarVisible = true

  const { routeName } = navigation.state.routes[navigation.state.index]

  if (routeName === 'AnotherScreen') {
    tabBarVisible = false
  }

  return {
    tabBarVisible
  }
}
```

**Comment by brentvatne** [comment]
please create a new issue

**Comment by danieldelouya** [comment]
@brentvatne Done :)
