### ISSUE TITLE
Stack Navigator is not compatible with a Modal from react-native.

### ISSUE THREAD

**Issue by AvenzaOleg** [react-navigation/react-navigation#5458]
### Bug: Navigation breaks if you try to navigate between screens with a `<Modal />`

I am trying to integrate react-native Modal into stack navigator.. but it totally breaks the navigation. Initially I was blaming it on "transparentCard" but it just breaks it without it.

### Current Behavior

I have 3 screens:
**Dashboard**
![simulator screen shot - iphone 8 - 2019-01-07 at 12 07 56](https://user-images.githubusercontent.com/37984204/50782238-78487980-1275-11e9-8154-4ed5bd265d6f.png)

**Modal A**
![simulator screen shot - iphone 8 - 2019-01-07 at 12 08 44](https://user-images.githubusercontent.com/37984204/50782236-78487980-1275-11e9-9731-bbfa5ae0e21a.png)

**Modal B**
![simulator screen shot - iphone 8 - 2019-01-07 at 12 08 51](https://user-images.githubusercontent.com/37984204/50782237-78487980-1275-11e9-90c4-b554d676431f.png)

Code:
```javascript
import React, { Component } from 'react'
import { Button, Modal, Text, View } from 'react-native'
import { createStackNavigator } from 'react-navigation'

export class DemoModalNavigationDashboard extends Component {
  static navigationOptions = ({ navigation }) => {
    let headerTitle = <View>
      <Text>Header DemoModalNavigationDashboard</Text>
    </View>

    return { headerTitle }
  }

  render () {
    return <View style={{
      backgroundColor: '#ffffff',
      flexDirection: 'column',
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center'
    }}>
      <Text>DemoModalNavigationDashboard</Text>
      <Button
        title={'Go to Modal A'}
        onPress={() => this.props.navigation.navigate('DemoModalNavigationModalA')}
      />
      <Button
        title={'Go to Modal B'}
        onPress={() => this.props.navigation.navigate('DemoModalNavigationModalB')}
      />
    </View>
  }
}

export class DemoModalNavigationModalA extends Component {
  static navigationOptions = {
    header: null
  }

  render () {
    return <View style={{ marginTop: 22 }}>
      <Modal
        transparent
        key={'DemoModalNavigationModalA'}
        visible
      >
        <View style={{
          backgroundColor: '#cccccc',
          flexDirection: 'column',
          flex: 1,
          justifyContent: 'center',
          alignItems: 'center',
          margin: 100,
          marginLeft: 20,
          borderWidth: 2,
          borderColor: '#FF0000',
        }}>
          <Text>DemoModalNavigationModalA</Text>
          <Button
            title={'Go back'}
            onPress={() => this.props.navigation.goBack(null)}
          />
          <Button
            title={'Go to Dashboard'}
            onPress={() => this.props.navigation.navigate('DemoModalNavigationDashboard')}
          />
          <Button
            title={'Go to Modal B'}
            onPress={() => this.props.navigation.navigate('DemoModalNavigationModalB')}
          />
          <Button
            title={'Replace to Modal B'}
            onPress={() => this.props.navigation.replace('DemoModalNavigationModalB')}
          />
        </View>
      </Modal>
    </View>
  }
}

export class DemoModalNavigationModalB extends Component {
  static navigationOptions = {
    header: null
  }

  render () {
    return <View style={{ marginTop: 22 }}>
      <Modal
        transparent
        key={'DemoModalNavigationModalB'}
        visible
      >
        <View style={{
          backgroundColor: '#cccccc',
          flexDirection: 'column',
          flex: 1,
          justifyContent: 'center',
          alignItems: 'center',
          margin: 100,
          marginTop: 20,
          borderWidth: 2,
          borderColor: '#00FF00',
        }}>
          <Text>DemoModalNavigationModalB</Text>
          <Button
            title={'Go back'}
            onPress={() => this.props.navigation.goBack(null)}
          />
          <Button
            title={'Go to Dashboard'}
            onPress={() => this.props.navigation.navigate('DemoModalNavigationDashboard')}
          />
          <Button
            title={'Go to Modal A'}
            onPress={() => this.props.navigation.navigate('DemoModalNavigationModalA')}
          />
          <Button
            title={'Replace to Modal A'}
            onPress={() => this.props.navigation.replace('DemoModalNavigationModalA')}
          />
        </View>
      </Modal>
    </View>
  }
}

export default createStackNavigator(
  {
    DemoModalNavigationDashboard: DemoModalNavigationDashboard,
    DemoModalNavigationModalA: DemoModalNavigationModalA,
    DemoModalNavigationModalB: DemoModalNavigationModalB
  },
  {
    headerMode: 'screen'
  }
)
```

### Expected Behavior

I want to be able to navigate using the following paths:

1) Open Dashboard -> Navigate Modal A -> Navigate Modal B
2) Open Dashboard -> Navigate Modal B -> Navigate Modal A
3) Open Dashboard -> Navigate Modal A -> Replace with Modal B
4) Open Dashboard -> Navigate Modal B -> Replace with Modal A

### How to reproduce

1. Navigate to dashboard
2. Click "Go to Modal A" button
3. Click "Go to Modal B" button
4. Screen "A" will persist, Modal B is never shown.

OR 

1. Navigate to dashboard
2. Click "Go to Modal A" button
3. Click "Replace to Modal B" button
4. You will see a blank screen
![image](https://user-images.githubusercontent.com/37984204/50782444-058bce00-1276-11e9-840a-4873a14b03f0.png)

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | react-navigation@3.0.9
| react-native     | react-native@0.57.8
| node             | v8.11.2
| npm or yarn      |  1.7.0

**Comment by olegserov** [comment]
There is a workaround when you control visibility of a modal by hooking it up using
`<NavigationEvents onWillFocus={payload => {this.setState({ visible: true })}} />` but it does not work with a replace due to: https://github.com/react-navigation/react-navigation/issues/5459

**Comment by eriveltonelias** [comment]
hi there, 

if you want to open a full screen as modal, I recommend it https://reactnavigation.org/docs/en/modal.html#docsNav 
and 
https://reactnavigation.org/docs/en/stack-navigator.html#modal-stacknavigator-with-custom-screen-transitions

**Comment by olegserov** [comment]
@eriveltonelias, in my current project I have 2 types of navigation: phone-sized devices get regular navigation, tablet-sized devices get modal-based navigation. I really don't want to go away from using react-navigation and as a solution my current workaround is to have transparentCard stack with no header on all modal screens. I had to re-write `<Modal />` to use regular Views in order to avoid this bug, but it works like a charm. 

There are few things nice to have for navigation with modal:
0. Fix this bug.
1. Backdrop (aka greyed out area in the background) should be managed by react-navigation. Having it managed by individual screens results in inconsistencies. Workaround is to manage events to show/hide this backdrop either from base screen or from each modal.
2. Have a mandatory base screen. This is a full-sized screen that takes the full screen. All other screens in the stack can be modals or full-sized screens.

**Comment by brentvatne** [comment]
i strongly recommend against using the built-in react-native modal with react-navigation. it uses its own view controller and that's not guaranteed to play nicely with react-navigation

**Comment by olegserov** [comment]
@brentvatne Then at least, if it not supported and it is not going to be fixed, it should be added somewhere in the doc.

**Comment by brentvatne** [comment]
i agree, can you open a pr for it? https://github.com/react-navigation/website
