### ISSUE TITLE
Scrollables ScrollView/FlatList from StackNavigator inside BottomTabNavigator

### ISSUE THREAD

**Issue by tronginc** [react-navigation/react-navigation#5460]
Hello, Today I have a problem with **Scrollables**.
Scroll works perfectly on root **BottomTabNavigator**.  But it not working in **StackNavigator** nested **BottomTabNavigator**.
When I press the tab, It goes back to previous stack.

    import React from 'react';
    import { Text, View, TouchableOpacity } from 'react-native';
    import { createBottomTabNavigator, createAppContainer, FlatList, createStackNavigator } from 'react-navigation';

    const data = new Array(150).fill(0);

    const HomeScreen = () => (
        <TouchableOpacity onPress={() => this.props.navigation.navigate("Scrollables")}>
            <Text>go to Scrollables</Text>
        </TouchableOpacity>
    )

    class Scrollables extends React.Component {
      renderItem = ({ index }) => {
        return (
          <View style={{ height: 50 }}>
            <Text style={{ textAlign: 'center' }}>Item {index}</Text>
          </View>
        );
      };

      render() {
        return (
          <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
            <FlatList
              data={data}
              renderItem={this.renderItem}
              contentContainerStyle={{ padding: 10 }}
            />
          </View>
        );
      }
    }

    const TabNavigator = createBottomTabNavigator({    
      Dashboard: createStackNavigator({
          HomeScreen : { screen: HomeScreen },
          Scrollables : { screen: Scrollables },
      }, { initialRouteName: HomeScreen , })
    });

    export default createAppContainer(TabNavigator);

**Comment by brentvatne** [comment]
that's intentional. the expected behavior for tabs with a stack in them is that it will pop to top when you press on an already active tab. you can override the tab press action as described in the docs if you don't want this
