### ISSUE TITLE
createMaterialTopTabNavigator higher than createBottomTabNavigator

### ISSUE THREAD

**Issue by s349856186** [react-navigation/react-navigation#5461]
createMaterialTopTabNavigator({
           tab...
}{
      tabBarPosition: 'bottom',
       indicatorStyle:{
            height:0,
        }
})

How can I make the height of createMaterialTopTabNavigator = createBottomTabNavigator height?

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.0.9
| react-native     | 0.57.8
| node             | 8.3
| npm or yarn      | 6.5

**Comment by brentvatne** [comment]
hi there! this is a question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.
