### ISSUE TITLE
screenProps are undefined

### ISSUE THREAD

**Issue by pratikghosalkar** [react-navigation/react-navigation#5462]
### Current Behavior

screenProps are undefined in component

### Expected Behavior

screenProps should have value passed from this.props

### How to reproduce

Check below code of App.js .

`import { createAppContainer, createSwitchNavigator,createStackNavigator  } from 'react-navigation'
import HomeScreen from './HomeScreen';
import MapScreen from './MapScreen';
import LoginScreen from './LoginScreen';
import TransactionList from './TransactionList';
import RegisterDeviceScreen from './RegisterDeviceScreen';
import React, { Component } from 'react';
import {
  AsyncStorage,
} from 'react-native';

class AuthLoadingScreen extends Component {
  componentDidMount() {
    this._bootstrapAsync();
  }

  _bootstrapAsync = async () => {
    const userToken = await AsyncStorage.getItem('sessionText');
    if (!userToken) {
      await AsyncStorage.clear();
    }
await this.props.navigation.navigate(userToken ? 'App' : 'Auth');
  };

  render() {
    console.log('AuthLoadingScreen Renders - ',this.props);
    return <RegisterDeviceScreen screenProps={this.props} />;
  }
}

const AppStack = createStackNavigator(
  {
    HomeScreen: { screen: HomeScreen },
    MapScreen: { screen: MapScreen },
    TransactionList:{screen: TransactionList},
    LoginScreen: { screen: LoginScreen },
    RegisterDeviceScreen: { screen: RegisterDeviceScreen },
  },
  {
    navigationOptions: {
      gesturesEnabled: false,
    }
  });

const AuthStack = createStackNavigator(
  {
    LoginScreen: { screen: LoginScreen },
    RegisterDeviceScreen: { screen: RegisterDeviceScreen },
    HomeScreen: { screen: HomeScreen },
    MapScreen: { screen: MapScreen },
    TransactionList:{screen: TransactionList},
  },
  {
    navigationOptions: {
      gesturesEnabled: false,
    }
  });

const SwitchNavigator = createSwitchNavigator(
  {
    AuthLoading: AuthLoadingScreen,
    Auth: AuthStack,
    App: AppStack,
  },
  {
    initialRouteName: 'AuthLoading',
  }
);

const AppContainer = createAppContainer(SwitchNavigator)
export default AppContainer`

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.0.9
| react-native     | 0.57.8
| node             | v8.9.4
| npm or yarn      | 5.6.0

**Comment by eriveltonelias** [comment]
hi @pratikghosalkar, 

I just created an example  https://snack.expo.io/@eriveltonelias/screenprops-example

**Comment by pratikghosalkar** [comment]
> hi @pratikghosalkar,
> 
> I just created an example https://snack.expo.io/@eriveltonelias/screenprops-example

Hi tried with your code still I am getting props as undefined, sorry I am new with react-navigation. Please check my below code. I have modified it according to your example.

`import { createAppContainer, createSwitchNavigator,createStackNavigator  } from 'react-navigation'
import HomeScreen from './HomeScreen';
import MapScreen from './MapScreen';
import LoginScreen from './LoginScreen';
import TransactionList from './TransactionList';
import RegisterDeviceScreen from './RegisterDeviceScreen';
import React, { Component } from 'react';
import {
  AsyncStorage,
} from 'react-native';

class AuthLoadingScreen extends Component {
  componentDidMount() {
    this._bootstrapAsync();
  }

  _bootstrapAsync = async () => {
    const userToken = await AsyncStorage.getItem('sessionText');
    if (!userToken) {
      await AsyncStorage.clear();
    }
    await this.props.navigation.navigate(userToken ? 'App' : 'Auth');

    console.log('init props from app - ',this.props);
  };

  render() {
    console.log('AuthLoadingScreen Renders - ',this.props);
    return <AuthStack screenProps={{worldPayIntentOutput: 'test'}} />;
  }
}

const AppStack = createStackNavigator(
  {
    HomeScreen: { screen: HomeScreen },
    MapScreen: { screen: MapScreen },
    TransactionList:{screen: TransactionList},
    LoginScreen: { screen: LoginScreen },
    RegisterDeviceScreen: { screen: RegisterDeviceScreen },
  },
  {
    navigationOptions: {
      gesturesEnabled: false,
    }
  });

const AuthStack = createStackNavigator(
  {
    LoginScreen: { screen: LoginScreen },
    RegisterDeviceScreen: { screen: RegisterDeviceScreen },
    HomeScreen: { screen: HomeScreen },
    MapScreen: { screen: MapScreen },
    TransactionList:{screen: TransactionList},
  },
  {
    navigationOptions: {
      gesturesEnabled: false,
    }
  });

const SwitchNavigator = createSwitchNavigator(
  {
    AuthLoading: AuthLoadingScreen,
    Auth: AuthStack,
    App: AppStack,
  },
  {
    initialRouteName: 'Auth',
  }
);

const AppContainer = createAppContainer(SwitchNavigator)
export default AppContainer`

And I am checking this screenprops on the login screen like this

`componentDidMount() {
    console.log('initial props login- ',this.props.screenProps);
}
`

**Comment by md98uddin** [comment]
What exactly are you trying to accomplish at the following line with screenProps. I don't think you understood props and their usage well. 


>   render() {
>     console.log('AuthLoadingScreen Renders - ',this.props);
>     return <AuthStack screenProps={{worldPayIntentOutput: 'test'}} />;
>   }
> }
