### ISSUE TITLE
How to perfectly import createStackNavigator, createTabNavigator and createDrawerNavigator with AuthenticationFlow of SignIn and SignOut through createSwitchNavigator in v3

### ISSUE THREAD

**Issue by TechSatya** [react-navigation/react-navigation#5463]
### Current Behavior

- I have two `StackNavigator`s, one for "no need of authentication" and another for "after authentication success".
- I am navigating from these two `StackNavigator`s inside createSwitchNavigator.
- Inside the app after successful SignIn, there will be `DrawerNavigator` and `TabNavigator` along with the authenticated `StackNavigator`.

### Expected Behavior

- Maybe I'm lacking on importing these 4 navigators perfectly, actually I expect the `Tabbar` and `Drawer` shouldn't be accessible in unathenticated `StackNavigator` screens, which is before login.

I have many times googled around about it, but not yet got any helpful answer, so if anyone can assist on it or show a dummy code structure, then it will seriously be helpful to everyone. 

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | v3
| react-native     | 0.57

@@brentvatne @ericvicenti @eriveltonelias

**Comment by eriveltonelias** [comment]
hi there,
this issue tracker is reserved for bugs only. your post seems to be a usage question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.
but you can find it on docs  https://reactnavigation.org/docs/en/auth-flow.html#docsNav

 thanks!
