### ISSUE TITLE
SomeStack.navigationOptions override other navigationOptions and removes tabBarIcon

### ISSUE THREAD

**Issue by danieldelouya** [react-navigation/react-navigation#5464]
### Current Behavior
The icon in the bottom tab navigator disappears ss soon as i include the the following code in the file it removes the tabBarIcon for the HomeStack:

```
HomeStack.navigationOptions = ({ navigation }) => {
  let tabBarVisible = true

  const { routeName } = navigation.state.routes[navigation.state.index]

  if (routeName === 'ProfileScreen') {
    tabBarVisible = false
  }

  return {
    tabBarVisible
  }
}
```

```
const HomeStack = createStackNavigator(
  {
    Home: {
      screen: HomeScreen,
      navigationOptions: {
        headerBackTitle: null,
        header: null
      }
    },
    ProfileScreen: {
      screen: ProfileScreen,
      navigationOptions: {
        gesturesEnabled: true,
        headerTitle: null,
        headerTransparent: false,
        headerBackTitle: null,
        headerBackImage: <BackIcon />,
        headerStyle: {
          elevation: 0,
          shadowOpacity: 0,
          borderBottomWidth: 0
        }
      }
    }
  },
  {
    navigationOptions: {
      tabBarLabel: ({ focused }) => {
        return (
          <Text style={focused ? styles.textActive : styles.textInactive}>
            Me
          </Text>
        )
      },
      tabBarIcon: ({ focused }) => focused
          ? <Image source={profileFilled} style={styles.tabBarIconActive} />
         : <Image source={profileOutlined} style={styles.tabBarIconInactive} />

    }
  }
)

HomeStack.navigationOptions = ({ navigation }) => {
  let tabBarVisible = true

  const { routeName } = navigation.state.routes[navigation.state.index]

  if (routeName === 'ProfileScreen') {
    tabBarVisible = false
  }

  return {
    tabBarVisible
  }
}
```

// Later down in the file:

```
export const TabNavigator = createAppContainer(
  createBottomTabNavigator(
    {
      Home: HomeStack,
      Work: WorkStack,
    },
    {
      tabBarOptions: {
        activeTintColor: 'black',
        inactiveTintColor: 'black',
        showLabel: true,
        showIcon: true
      }
    }
  )
)
```

### Expected Behavior

Tab bar icon should not disappear. 

### How to reproduce

Here is an expo example I've created with same issue:
https://snack.expo.io/@danieldelouya/react-navigation-problem

Find this line:
// TRY COMMENTING THIS OUT ABND THE TAB BAR ICON WILL APPEAR

and then you can comment out the following code and see the tab bar icon appear again.

HomeStack.navigationOptions = ({ navigation }) => {
  let tabBarVisible = true

  const { routeName } = navigation.state.routes[navigation.state.index]

  if (routeName === 'AnotherScreen') {
    tabBarVisible = false
  }

  return {
    tabBarVisible
  }
}

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.0.9
| react-native     | 0.57.8
| node             | 10.14.2
| npm or yarn      |

**Comment by brentvatne** [comment]
the problem is that you override the navigationOptions by setting them directly on the HomeStack.

`navigationOptions` in the second param for createStackNavigator is equivalent to `HomeStack.navigationOptions = ` - this is documented in the release notes: https://reactnavigation.org/blog/#renamed-navigationoptions-in-navigator-configuration

see the fixed version here: https://snack.expo.io/@notbrent/react-navigation-problem

**Comment by danieldelouya** [comment]
@brentvatne Gotcha, thanks :)
