### ISSUE TITLE
no function for swipping,call back and onclick on tabs name

### ISSUE THREAD

**Issue by karthikeyansundaram2** [react-navigation/react-navigation#5465]
## The issue tracker is reserved for bug reports only.

If you have a question, feature request, or an idea for improving the library or its related tools, please try one of the following resources:

- [Read the documentation](https://reactnavigation.org/)
- [Post an issue to the website repository if you'd like to see a documentation change](http://github.com/react-navigation/website)
- [Post a feature request to Canny](https://react-navigation.canny.io/feature-requests)
- [Write a RFC if you have ideas for how to implement a feature request](https://github.com/react-navigation/rfcs)
- [Get help on Discord chat (#react-navigation on Reactiflux)](https://discord.gg/4xEK3nD) or [on StackOverflow](https://stackoverflow.com/questions/tagged/react-navigation)
- Search for your issue - it may have already been answered or even fixed in the development branch. However, if you find that an old, closed issue still persists in the latest version, you should open a new issue.

Bugs with react-navigation must be reproducible *without any external libraries that operate on it*. This means that if you are attempting to use Redux or MobX with it and you think you have found a bug, you must be able to reproduce it without Redux or MobX in this report. Redux related issues belong in [react-navigation-redux-helpers](https://github.com/react-navigation/react-navigation-redux-helpers), and we do not have any first-class integration with MobX at the moment.

---

### Current Behavior

I created a material top bar navigator using react-navigation while working in that i cant detect the movement of the tabs and the swiping of the tabs.
It does not find the tabs that I am clicking 

### Expected Behavior

It must be able to detect the swippable movement and along with the tab name onclick so that the developer can be able to mount and render what is needed

### How to reproduce

Create a material top bar navigator with three or four tabs and check whether you where able to detect the swippable movement and the tab name click

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |3.x
| react-native     |0.56
| node             |
| npm or yarn      |

**Comment by eriveltonelias** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.
you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.
please create a new issue with this and i'd be happy to review it!

**Comment by karthikeyansundaram2** [comment]
if (categories.includes('pyramid')) {
leagueTabBars["Super"] = {
screen: prop => <SuperStarsScreen {...prop} {...props} />,
navigationOptions: {
tabBarIcon: ({
}) => (
<View style={styles.ScrollableTab_Item}>
<Text style={styles.ScrollableTab_Title}>Super⭐</Text>
</View>
),
}
}
}
if (categories.includes('man_of_the_match')) {
leagueTabBars["ManOftheMatch"] = {
screen: props => <ManOfTheMatchScreen {...props} />,
navigationOptions: {
tabBarLabel: "MOM",
tabBarIcon: ({
}) => (
<View style={styles.ScrollableTab_Item}>
<Text style={styles.ScrollableTab_Title}>MOM</Text>
</View>
),
}
}
}
if (categories.includes('multiplier')) {
leagueTabBars["Multiplier"] = {
screen: props => <MultiplierScreen {...props} />,
navigationOptions: {
tabBarLabel: "Multiplier",
tabBarIcon: ({

}) => (
<View style={styles.ScrollableTab_Item}>
<Text style={styles.ScrollableTab_Title}>Multiplier</Text>
</View>
),

}
}
}
if (categories.includes('head_to_head')) {
leagueTabBars["H2H"] = {
screen: props => <HeadtoHeadScreen {...props} />,
navigationOptions: {
tabBarLabel: "H2H",
tabBarIcon: ({

}) => (
<View style={styles.ScrollableTab_Item}>
<Text style={styles.ScrollableTab_Title}>H2H</Text>
</View>
),
}
}
}
return leagueTabBars;


this is the sample code. In this how can I achieve swipeback and tab
press.I need to update the tab when the tabs header is pressed or
whejn it us swipped
