### ISSUE TITLE
Default header background image

### ISSUE THREAD

**Issue by theteladras** [react-navigation/react-navigation#5466]
## The issue tracker is reserved for bug reports only.

I did not find a existing solution for header background styling, with the default header bar. So I implemented some changes to the code and made it possible. It is kinda a feature needed in most cases to be done as quick as possible.

It is strange that this is not available, so I'd like to help up with this small change...

_I have tested it on both platforms and on several phones, works as expected. Will submit a PR if allowed, otherwise someone fix this missing piece!_

### A small example:
<span>
<img src="https://scontent.fbeg2-1.fna.fbcdn.net/v/t1.15752-9/49707152_306117080039417_1419572418875228160_n.jpg?_nc_cat=109&_nc_ht=scontent.fbeg2-1.fna&oh=4eea84d93e89b91c8df6db403860c646&oe=5CD50845" alt="header example" width="220" height="360">

<img src="https://scontent.fbeg2-1.fna.fbcdn.net/v/t1.15752-9/49766557_1047481345438045_5047869153113800704_n.jpg?_nc_cat=107&_nc_ht=scontent.fbeg2-1.fna&oh=32eb4eacb11151fc3227794c81c4ebc2&oe=5CC1387A" alt="header example" width="220" height="360">
</span>

**Comment by brentvatne** [comment]
you can use the `headerBackground` property like this: https://github.com/react-navigation/react-navigation/blob/31e07e9692c3b00f63265e5235aa4e8d48d983f5/examples/NavigationPlayground/js/StackWithTranslucentHeader.js#L249-L254
