### ISSUE TITLE
Conditionally render TabNavigators

### ISSUE THREAD

**Issue by JanithaR** [react-navigation/react-navigation#5467]
Hi,

I have a requirement where I must render tabs conditionally and must maintain a single search component at the top of the screen which is common to the content of all 3 tabs. You can check [this](https://imgur.com/a/M7e0KUU) screenshot to get a better idea. Entering a text would be sent to all the tabs via `screenProps` so that they could filter accordingly.

In the screen component render() I have this,
```
return (
            <SafeAreaView style={{ flex: 1, backgroundColor: 'white' }}>

                <View style={{ flex: 1, backgroundColor: 'white' }}>

                    {this.getStatusBar()}

                    <CustomSearchBar
                        onChangeText={this.setSearchPhrase}
                        onSubmitEditing={this.onSearchPress}
                        placeholder={I18n.t('searchEntities')} />

                    {this.getTabs()}

                </View>

            </SafeAreaView>
        );
```

This is how I render the tabs conditionally,
```
getTabs = () => {
        const { entityType } = this.props.parentEntity;

        if (entityType === appConstants.entityTypeEstate) {
            return (
                <EstateDrillDownTabs
                    screenProps={screenProps}
                    navigation={this.props.navigation} />);
        } else if (entityType === appConstants.entityTypeBuilding) {
            return (
                <BuildingDrillDownTabs
                    screenProps={screenProps}
                    navigation={this.props.navigation} />);
        } else if (entityType === appConstants.entityTypeRoom) {
            return (
                <RoomDrillDownTabs
                    screenProps={screenProps}
                    navigation={this.props.navigation} />);
        } else {
            if (__DEV__) console.error(`ERROR!`);
        }
    };
```

And of course, that means I have 3 tab navigators created.

```
const EstateDrillDownTabs = createMaterialTopTabNavigator({
    Building: {
        screen: BuildingTab,
    },
    Site: {
        screen: SiteTab,
    },
    TechConst: {
        screen: TechConstTab,
    }
}, { ... });

const BuildingDrillDownTabs = createMaterialTopTabNavigator({
    Section: {
        screen: SectionTab,
    },
    Room: {
        screen: RoomTab,
    },
    Object: {
        screen: ObjectTab,
    }
}, { ... });

const RoomDrillDownTabs = createMaterialTopTabNavigator({
    Object: {
        screen: ObjectTab,
    }
}, { ... });
```

My problem occured during migrating from v1 to v3 where I must expose the `Class.router`.

As per the guide [here](https://reactnavigation.org/docs/en/custom-navigators.html) I'm exposing it as below.

```
static router = {
        ...EstateDrillDownTabs.router,
        getStateForAction: (action, lastState) => {
            return EstateDrillDownTabs.router.getStateForAction(action, lastState);
        },
    };
```

This works fine as expected when the condition for `EstateDrillDownTabs` is met but things obviously break for the others. How can I set the `static router` conditionally or somehow set the `router` in some otherway to meet my requirement?

**Comment by brentvatne** [comment]
hi there! this is a question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.

**Comment by JanithaR** [comment]
Pardon me but I posted this hear because there was no way (according to the documentation) that I could achieve this behaviour. This could be something overlooked in v3?
