### ISSUE TITLE
headerStyle not being merged with defaultNavigationOptions on iOS

### ISSUE THREAD

**Issue by sachinB94** [react-navigation/react-navigation#5468]
`headerStyle` defined at screen level is not merged with those defined in `defaultNavigationOptions`.

This only happens on iOS. On Android, it works fine.

### Current Behavior

`headerStyle` defined at screen level are not merged with those defined in `defaultNavigationOptions`.

I think `navigationOptions` are being shallow merged.

### Expected Behavior

Either
- `navigationOptions` should be merged recursively, or
- At least, `headerStyle` should be merged

### How to reproduce

Reproducible Snack: https://snack.expo.io/ryRoZkrGE

`borderBottomWidth` is defined in `defaultNavigationOptions.headerStyle`. But, in Screen2, `borderBottomWidth` is not defined. So, it shows a white border below the header.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.0.9
| react-native     | 0.57.8
| node             | 8.15.0
| npm or yarn      | yarn

**Comment by brentvatne** [comment]
`navigationOptions` only do a shallow merge, so `headerStyle` won't be handled here. perhaps we should change it to a deep merge but this would be a breaking change and require a major version bump

**Comment by sachinB94** [comment]
Yeah. That is true. Maybe we can use a flag to enable deep merge. Something like:

```js
defaultNavigationOptions: {
  deepMerge: true // default=FALSE
}
```

This is not an elegant solution. But, this change won't need a major bump.

**Comment by brentvatne** [comment]
i don't like adding another option for this. can you create a rfc to propose deep merging navigation options? thanks! https://github.com/react-navigation/rfcs

**Comment by sachinB94** [comment]
Created the RFC.
https://github.com/react-navigation/rfcs/pull/74
