### ISSUE TITLE
Cannot find reset action in { NavigationActions } v3.0.9

### ISSUE THREAD

**Issue by micabe** [react-navigation/react-navigation#5469]
Hello there, you don't seem to export reset action in `import { NavigationActions } from 'react-navigation';`.
Is there an other way to access the actionType ?

![screen shot 2019-01-10 at 18 01 27](https://user-images.githubusercontent.com/11733571/50984447-2ec08e80-1502-11e9-9057-a1aa05a23048.png)

**Comment by brentvatne** [comment]
https://reactnavigation.org/docs/en/stack-actions.html#reset
