### ISSUE TITLE
Navigate from DrawerNav to BottomTabNav doesn't pass props

### ISSUE THREAD

**Issue by LucasBrazi06** [react-navigation/react-navigation#5472]
### Current Behavior
I navigate from a DrawerNav to a BottomTab and the initial screen doesn't receive the props.

Below I navigate from the AppDrawerNavigator, screen Sites -> SiteAreas -> Chargers and then to ChargerTabNavigator with:

navigation.navigate("ChargerTabNavigator", { my_props })

The ChargerTab screen receives very well the props but not the screen ConnectorDetails (cf. below console.log)

```
// Charger Tab Navigation
const ChargerTabNavigator = createBottomTabNavigator(
  {
        ConnectorDetails: { screen: (props) => {
        // Initial Screen: No properties are passed to the component
        console.log("ConnectorDetails");
        console.log(props.navigation.state.params);
        return (<ConnectorDetails {...props} />);
      } 
    },
    ChartDetails: { screen: (props) => <ChartDetails {...props} /> },
    ChargerDetails: { screen: (props) => <ChargerDetails {...props} /> }
  },
  {
    tabBarPosition: "bottom",
    swipeEnabled: false,
    initialRouteName: "ConnectorDetails",
    animationEnabled: true,
    tabBarComponent: (props) => {
      // Here the props are available!!!
      console.log("ChargerTab");
      console.log(props.navigation.state.params);
      return (<ChargerTab {...props} />);
    }
  }
);

// Drawer Navigation
const AppDrawerNavigator = createDrawerNavigator(
  {
    Sites: { screen: Sites },
    SiteAreas: { screen: SiteAreas },
    Chargers: { screen: Chargers },
    ChargerTabNavigator: ChargerTabNavigator
  },
  {
    navigationOptions: {
      swipeEnabled: true,
    },
    drawerWidth: Dimensions.get("window").width / 1.5,
    initialRouteName: "Sites",
    drawerPosition: "right",
    contentComponent: props => <Sidebar {...props} />
  }
);

```

### Expected Behavior

I expect that the props are passed to the initial component.

### How to reproduce

Create a Drawer navigator with one screen and navigate to a BottomTab navigator with the navigate method with parameters and check that the params are passed to the initial screen of the BottomTab nav.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.18.3
| react-native     | 0.57.8
| node             | 8.11.3
| npm or yarn      | 5.6.0

**Comment by brentvatne** [comment]
you need to navigate to a screen specifically inside of the tab, not to the tab itself, or the params go into the tab navigator. params only go to the route that you are navigating to directly.

so

```
Drawer({
  MyTabs: Tab({
    A: Stack({
      A1: ScreenA1,
    }),
    B: ScreenB,  
  })
});
```

navigate to A1 rather than A

**Comment by LucasBrazi06** [comment]
@brentvatne 
I provided you an expo to reproduce: I navigate to screen A but B doesn't get the params
[Expo Test](https://snack.expo.io/@lucasbrazi06/navigation-bottomtabnavigator-and-props)
