### ISSUE TITLE
How to dynamic change createBottomTabNavigator's tabBarLabel ? 

### ISSUE THREAD

**Issue by s349856186** [react-navigation/react-navigation#5473]
I can't dynamic change the tabBarLabel when from 1.x update to 3.x

I have 4 Tabs, when i change language ,only the current tabBarLabel has changed, other tabs are not refreshed. how to do refresh all tabBarLabel? 

It's work fine at 1.x, but update 3.x not work

static navigationOptions = ({ navigation, screenProps, })=>({

        mode: 'modal',
        headerMode: 'none',
        tabBarLabel: I18n.t('main.Home1'),  //1,2,3,4
    });

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.0.9
| react-native     | 0.57.8
| node             | 8.9.0
| npm       | 6.5.0

**Comment by brentvatne** [comment]
you should use `screenProps` and then change one of the `screenProps` to indicate the language being used

feel free to create a new issue with a reproducible example as per the issue template
