### ISSUE TITLE
Freezing of screen in BottomTabNavigator when react-native-screens enabled

### ISSUE THREAD

**Issue by ikhilko** [react-navigation/react-navigation#5474]
I've prepared a demo using Expo snack: https://snack.expo.io/@ikhilko/react-native-screens-freezing-tab

![react-navigation-freeze](https://user-images.githubusercontent.com/5723540/51072543-80d4f180-1673-11e9-8956-7af6f7c57a6f.gif)

### Current Behavior

While switching between screens one of them completely freezes. It's only reproducible when react-native-screens usage enabled.

### Expected Behavior

Screen should behave as usual (not freeze) with and without using react-native-screens.

### How to reproduce

You can use Snack example I provided. To reproduce:
- Open example on Simulator or device
- Try to interact with first screen (it works normally)
- Switch to second one screen
- Try to interact with second screen (it works normally)
- Switch to first one and the again to second one
- Try to interact with second screen again (it freezes)

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.0.9
| react-native     | 0.57.1 (expo 32.0.0)
| react-native-screens     | 1.0.0-alpha.19
| node             | 10.13.0
| npm or yarn      | yarn

**Comment by ikhilko** [comment]
I don't know but maybe @kmagiera can bring a light on this one :)

**Comment by brentvatne** [comment]
https://github.com/kmagiera/react-native-screens/issues/53

**Comment by HananeAlSamrout** [comment]
solution here [](https://stackoverflow.com/questions/56752564/app-freezes-on-ios-when-navigate-to-another-screen-react-navigation)
