### ISSUE TITLE
Text and TextInput selection and context menu issues

### ISSUE THREAD

**Issue by brentvatne** [react-navigation/react-navigation#5476]
- [`<Text selectable />` not working in DrawerNavigator](https://github.com/react-navigation/react-navigation/issues/5367)
- [TextInput context menu doesn't appear inside nested StackNavigator to TabNavigator](https://github.com/react-navigation/react-navigation/issues/5297)

**Comment by kirillpisarev** [comment]
Same issue - react-native 58, react-navigation 3.3.0. My clause is "StackNavigator inside TabNavigator". For same poor fellows, this is the way how you can temporary fix it: https://github.com/facebook/react-native/issues/9958#issuecomment-365624780

**Comment by dnbrwstr** [comment]
Looks to me like this is related to https://github.com/kmagiera/react-native-screens/issues/40.

Removing the call to useScreens in my app fixes the issue for me.

**Comment by brentvatne** [comment]
as mentioned in https://github.com/kmagiera/react-native-screens/issues/40 if someone can provide a reproducible example there it would be really helpful

**Comment by rago4** [comment]
I created a reproducible example, you can find it here https://github.com/rago4/context-menu-issue
Hope you will find it useful.

**Comment by KakarN** [comment]
@brentvatne I to am facing the issue, and would like to add some more details regarding this issue.

- When using StackNavigator text can be selected and the context menu is displayed. 
- When using MaterialTopTabNavigator, only on the second screen text can be selected (and the context menu is displayed).
- When using a BottomTabNavigator, no text can be selected and no context menu is displayed.

Tested it on an android Samsung galaxy s7 phone.

Here is the link to a [snack](https://snack.expo.io/@kakarn/textinput-selection).

**Comment by nicholmikey** [comment]
I am having the same issue, it's very frustrating. Oddly if I remove all styles from the TextInput and it's parent view it works. 

@rago4 I made a snack based on your example https://snack.expo.io/rJvpq7RsE and you can see it reproduces the error. It's very odd, if you make a spelling mistake on the second screen and force autocorrect to open it fixes the issue, but if you just type in good English like 'hello world' it stays broken. 

I have a thread on it with the folks at Expo https://forums.expo.io/t/issues-with-textinput-width-on-android/22356/3 I'm hoping someone can find a workaround, i'm pretty stuck.

**Comment by adimshev** [comment]
![image](https://user-images.githubusercontent.com/33316685/65991345-dd906a80-e495-11e9-8cc0-ada636e76f1c.png)

Works for me!
react-native: 0.59.10
react-navigation: 3.11.0

**Comment by sam1463** [comment]
I'm still running into this on react-native 0.61.5 and react-navigation 4.0.10

**Comment by mistikk** [comment]
why did you close to this issue, i cannot see any comment about resolve. I can reproduce with rn 61.2 and react navigation 4.0.10

**Comment by ovy9086** [comment]
This obviously still happens and it should be addressed

**Comment by dejawho** [comment]
I can confirm this too on react native 0.61.5 and react navigation 4.0.10 and I'm not using useScreens. Also the view where I'm using the text input is fairly simple

**Comment by ovy9086** [comment]
@dejawho rn-navigation uses screens by default AFAIK. Try to call ‘useScreens(false)’ before you start your app, see if that fixes the issue

**Comment by ovy9086** [comment]
@brentvatne can we reopen this ?

**Comment by chumakoff** [comment]
I solved the problem with this little hack:

```
const SelectableText = (props) => {
  const [selectable, setSelectable] = useState(false);

  useEffect(() => {
    setSelectable(true);
  }, []);

  return (
    <Text {...props} selectable={selectable} />
  )
};
```

**Comment by asafda** [comment]
This is still an issue 
Reproduced using React-Native 0.61.5 and React-Navigation 4.1.1

**Comment by sbichenko** [comment]
Can confirm that this is still a problem.

**Comment by tacomanator** [comment]
I'm experiencing an issue in which the edit menu (textinput context menu) will no longer appear after having opened and closed the developer menu. The edit menu will appear again after closing and reopening Expo, or restarting the device.

![ezgif-7-a51e8191889b](https://user-images.githubusercontent.com/63794/77224372-4e445400-6ba8-11ea-9444-7e1b622acb99.gif)

Would someone be kind enough to confirm if this related (i.e. restarting Expo temporarily enables the menu again)?

**Comment by lsarni** [comment]
Would it be possible to reopen this issue? We are using `"@react-navigation/material-top-tabs": "^6.0.6"` on an expo app.

As a workaround we set `selectable` using a `timeout`, based on this user idea https://github.com/facebook/react-native/issues/9958#issuecomment-365624780

```
const [selectable, setSelectable] = useState(false);

  useEffect(() => {
    setTimeout(() => {
      setSelectable(selectableContext);
    }, 100);
  }, []);
```
