### ISSUE TITLE
Documentation Issues on Drawer navigation

### ISSUE THREAD

**Issue by dataf3l** [react-navigation/react-navigation#5477]
## The issue tracker is reserved for bug reports only.

Hi guys, I LOVE react-navigation! so simple!, so clean! :), I love this project!

The documentation could Really use images showcasing how the Drawer navigation looks like, in the  same way the SwitchNavigation is documented, or the SafeArea one, it's nice to be able to visualize how things will look before one copies the code from the site.

---

### Current Behavior

No images on docs for Drawer nav

### Expected Behavior
Nicer Docs, with images plz

### How to reproduce
Just open the docs

### Your Environment
Irrelevant ?
| software         | version
| ---------------- | -------
| react-navigation | 3.0.9
| react-native     | sdk-30.0.0
| node             | 8
| npm or yarn      |6.5

**Comment by eriveltonelias** [comment]
Hi @dataf3l, 

I agree, can you open a PR for it on https://github.com/react-navigation/react-navigation.github.io or post an issue, please? :)

**Comment by dataf3l** [comment]
Done
