### ISSUE TITLE
Calling dispatch on AppContainer

### ISSUE THREAD

**Issue by pal-pinter** [react-navigation/react-navigation#5478]
Hi,

sorry but I don't understand this example on page:
[Calling Dispatch or Navigate on App Container](https://reactnavigation.org/docs/en/app-containers.html)
```
const AppContainer = createAppContainer(AppNavigator);

class App extends React.Component {
  someEvent() {
    // call navigate for AppNavigator here:
    this.navigator &&
      this.navigator.dispatch(
        NavigationActions.navigate({ routeName: someRouteName })
      );
  }
  render() {
    return (
      <AppContainer
        ref={nav => {
          this.navigator = nav;
        }}
      />
    );
  }
}
```
In the someEvent function the this.navigator always 'undefined', so this.navigator.dispatch() function never called.
Could you explain this code? I cannot dispatch actions on AppContainer.

Thx
P.

**Comment by eriveltonelias** [comment]
hi there! this issue tracker is reserved for bugs only. your post seems to be a usage question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help. thanks!
