### ISSUE TITLE
Navigate from DrawerNav to BottomTabNav doesn't pass props

### ISSUE THREAD

**Issue by LucasBrazi06** [react-navigation/react-navigation#5479]
### Current Behavior

I navigate from a DrawerNav to a BottomTabNav and the initial screen doesn't receive the props.

Below I navigate from the AppDrawerNavigator: Sites -> SiteAreas -> Chargers -> ChargerTabNavigator with: navigation.navigate("...", { my_props })

The ChargerTabNavigator screen receives very well the props but not the screen ConnectorDetails (cf. below console.log)

```
// Charger Tab Navigation
const ChargerTabNavigator = createBottomTabNavigator(
  {
        ConnectorDetails: { screen: (props) => {
        // Initial Screen: No properties are passed to the component
        console.log("ConnectorDetails");
        console.log(props.navigation.state.params);
        return (<ConnectorDetails {...props} />);
      } 
    },
    ChartDetails: { screen: (props) => <ChartDetails {...props} /> },
    ChargerDetails: { screen: (props) => <ChargerDetails {...props} /> }
  },
  {
    tabBarPosition: "bottom",
    swipeEnabled: false,
    initialRouteName: "ConnectorDetails",
    animationEnabled: true,
    tabBarComponent: (props) => {
      // Here the props are available!!!
      console.log("ChargerTab");
      console.log(props.navigation.state.params);
      return (<ChargerTab {...props} />);
    }
  }
);

// Drawer Navigation
const AppDrawerNavigator = createDrawerNavigator(
  {
    Sites: { screen: Sites },
    SiteAreas: { screen: SiteAreas },
    Chargers: { screen: Chargers },
    ChargerTabNavigator: ChargerTabNavigator
  },
  {
    navigationOptions: {
      swipeEnabled: true,
    },
    drawerWidth: Dimensions.get("window").width / 1.5,
    initialRouteName: "Sites",
    drawerPosition: "right",
    contentComponent: props => <Sidebar {...props} />
  }
);

```
### Expected Behavior

I expect that the props are passed to tab navigator as it is and THIS component leads the passing of the props to the other screens in the tabs.

### How to reproduce

Link to Expo
[Expo link](https://snack.expo.io/@lucasbrazi06/navigation-bottomtabnavigator-and-props)

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.18.3
| react-native     | 0.57.8
| node             | 8.11.3
| npm      | 5.6.0

**Comment by brentvatne** [comment]
related discussion: https://github.com/react-navigation/rfcs/issues/43
