### ISSUE TITLE
 undefined is not an object (evaluating _search.default)

### ISSUE THREAD

**Issue by adirzoari** [react-navigation/react-navigation#5483]
---
### Current Behavior

- What code are you running and what is happening?
I added part of my code here
[https://pastebin.com/4di391tB](https://pastebin.com/4di391tB
)### Expected Behavior

- What do you expect should be happening?
I want to run the project with the navigation
### How to reproduce
I try to run my project and I get this issue

> undefined is not an object (evaluating _search.default)
(search is screen in my navigation)
![na](https://user-images.githubusercontent.com/20258998/51204680-d11ab080-190c-11e9-8727-43b43d3c62a4.jpg)

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^3.0.9
| react-native     | 0.57.8
| node             | v8.11.3
| npm or yarn      | yarn 1.12.1

**Comment by brentvatne** [comment]
there is no such code in react-navigation, this is a bug in your app code
