### ISSUE TITLE
Disappearing Tab Navigation and other weirdness

### ISSUE THREAD

**Issue by TrentonAdams** [react-navigation/react-navigation#5485]
### Current Behavior

1. The tab navigation disappears after returning from a stack navigation.
1. Some other bizarre behaviour happens

### Expected Behavior

1. The tab navigation should not disappear after returning from a stack navigation, and if the setup of navigation is incorrect the library should throw an error.
1. Some of the other bizarre behaviour should not happen

### How to reproduce
Use your standard react-native/expo "start" command, but there are comments in the AppNavigator.js to consider and follow.

```
git clone https://github.com/TrentonAdams/copperfield-tabnav.git
cd copperfield-tabnav
git diff expo-init HEAD --name-only 
.gitignore
navigation/AppNavigator.js
screens/HomeScreen.js
screens/MyStage.js
```

### Your Environment

    "expo": "^32.0.0",
    "react": "16.5.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz",
    "react-navigation": "^3.0.9"
```
$ yarn --version
1.12.3
```
```
$ node --version
v11.6.0
```

**Comment by brentvatne** [comment]
hello! you don't seem to understand how this library works. i suggest reading the docs from the start, and paying close attention to nesting navigators. 

```

// Just use 'MyStage' and no back is available
// then try adding the commented out ones one by one and you'll see bizarre
// behaviour.
// Use MyStage and the 3 others together results in a back button.

// this doesn't seem like a library with well defined behaviour.
```

if you nest stack navigators then one does not inherit the back button for another stack navigator. is in fact very well defined!

**Comment by brentvatne** [comment]
you might also find this to be helpful: https://www.youtube.com/watch?v=wJJZ9Od8MjM

**Comment by TrentonAdams** [comment]
I definitely wondered many times about my understanding of the library.  I've went over the documentation many times as well.  I'll see if I can identify what specifically isn't clear.

> this doesn't seem like a library with well defined behaviour.
I simply mean that I'm able to achieve something bizarre that is unintended by the authors.  Or at least I would think my use case would not be intended by the others, since it results in odd behaviour.

Anyhow, I'll take a look at the docs again, and the video you sent.
