### ISSUE TITLE
react-navigation tab bar container resize

### ISSUE THREAD

**Issue by GShadowG** [react-navigation/react-navigation#5488]
Hello, does it possible to resize the tab bar container?
![github1](https://user-images.githubusercontent.com/46745017/51241870-49d34880-19b1-11e9-91f3-0dda03770f47.PNG)
that is what i want.
I am thinking to make the tab to position absolute, then i will expand the tab content to the size of its device. how can i do it?

**Comment by eriveltonelias** [comment]
hi there! this issue tracker is reserved for bugs only. your post seems to be a usage question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help. thanks!
