### ISSUE TITLE
Can not hide tabbar in nested Stack inside Stack inside TabBar

### ISSUE THREAD

**Issue by lyseiha** [react-navigation/react-navigation#5489]
Example:
`const StackANavigation = createStackNavigator({
  Home: Home,
  Profile: Profile
})
const StackBNavigation = createStackNavigator({

  Login: Login,
  Overview: StackANavigation,
  
})
const TabBarNavigation = createBottomTabNavigator({
  AAAA: StackBNavigation
})`
I wanna use tabBarVisible to true when i stay in Home and tabBarVisible to false when i go to profile.

**Comment by brentvatne** [comment]
hi there! this is a question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.

also see https://reactnavigation.org/docs/en/navigation-options-resolution.html
