### ISSUE TITLE
Nested page with TabNavigator is rendered as blank screen (after upgrading to V3)

### ISSUE THREAD

**Issue by Simek** [react-navigation/react-navigation#5491]
### Current Behavior

Nested TabNavigator is missing and app renders blank screen (V3).
https://streamable.com/e7i4c

When I replace TabNavigator with single React Component View renders correctly.

### Expected Behavior

Render View with nested Tabs properly (like V2).
https://streamable.com/e5l7h

### How to reproduce

Have app with AppContainer(TabNavigator) as a main View, screens are StackNavigators and one of the children screens should have another TabNavigator nested in.

Rough/simplified diagram:
<img width="813" alt="screenshot 2019-01-17 at 13 43 22" src="https://user-images.githubusercontent.com/719641/51319632-e521f780-1a5d-11e9-99a1-796005e49c63.png">

### Your Environment

NO Redux implementation in app.

Note: Also to make this work on V2 I need to provide few additional options for nested navigator based on responses in others issues (#1627, #662) :
```
animationEnabled: false,
swipeEnabled: true,
removeClippedSubviews: false,
```
Changing values or disabling those props after migration to V3 do not change behaviour at all.

| software         | version
| ---------------- | -------
| react-navigation | 3.0.9
| react-native     | 0.57.8
| node             | 11.6.0
| yarn      | 1.13.0

**Comment by eriveltonelias** [comment]
hi! please make your code runnable either on https://snack.expo.io without any extraneous code, thanks

**Comment by Simek** [comment]
@eriveltonelias Unfortunately I have an urgent project deadline right know and I don't have enough spare time to work on this repro. I have included as much details as I can to allow someone to work on that. Sorry about that.

**Comment by brentvatne** [comment]
sorry we don't look at bug reports without reproducible examples. my usual message for such issues is as follows, for your reference:

```
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
```
