### ISSUE TITLE
initalRoute

### ISSUE THREAD

**Issue by adirzoari** [react-navigation/react-navigation#5493]
### Current Behavior
Im using mobx and swtichNavigator. I'm checking if there is token(means user already register), if he already register I want stack App, if not Auth Stack..
but the problem is that it always go to Auth Stack.
I print with console the UserStore and the token has value..
```
`
let MainStack = createSwitchNavigator({
  Auth: AuthStack,
  App: AppStack
}, {

    initialRouteName: UserStore.token ? 'App' : 'Auth',
    headerMode: 'none',
    lazy: true,

    defaultNavigationOptions: {
      gesturesEnabled: false,
    },


  },


);

console.log('userStore', UserStore)
export default createAppContainer(MainStack);
`

```
### Expected Behavior

I want the initalRoute determined by UserStore.token

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^3.0.9
| react-native     | 0.57.8
| node             | v8.11.3
| npm or yarn      | yarn 1.12.1

**Comment by eriveltonelias** [comment]
hi there,

check this https://reactnavigation.org/docs/en/auth-flow.html#docsNav
