### ISSUE TITLE
Typescript for ref (NavigationService example) 

### ISSUE THREAD

**Issue by infinitey** [react-navigation/react-navigation#5495]
This is regarding the example shown on the website's documentation "Navigating without the navigation prop". 

```
export default class App extends React.Component {
  // ...

  render() {
    return (
      <AppContainer
        ref={navigatorRef => {
          NavigationService.setTopLevelNavigator(navigatorRef);
        }}
      />
    );
  }
}
```
This current code failed Typescript diagnostics:

> TypeScript diagnostics (customize using `[jest-config].globals.ts-jest.diagnostics` option):
>     App.tsx:31:50 - error TS2345: Argument of type 'NavigationContainerComponent | null' is not assignable to parameter of type 'NavigationScreenProp<object, NavigationParams>'.
>       Type 'null' is not assignable to type 'NavigationScreenProp<object, NavigationParams>'.
> 
>     31           NavigationService.setTopLevelNavigator(navigatorRef); 

Is there a way to make example play nice with Typescript? Thanks in advance.

| software         | version
| ---------------- | -------
| react-navigation | ^3.0.9
| react-native     | ^0.57.27
| node             | 11.6.0
| npm or yarn      | yarn

**Comment by brentvatne** [comment]
we don't officially support typescript right now, some folks are working on it here though: https://github.com/react-navigation/react-navigation/pull/5276

so until then this q is better suited for that thread or stackoverflow

**Comment by jefelewis** [comment]
You can do this in React Navigation 5.0 with Typescript.

```javascript
// Imports
import { NavigationContainer, NavigationContainerRef } from '@react-navigation/native';

// React Hooks: Refs
const navigationRef: React.RefObject<NavigationContainerRef> = useRef(null);

<NavigationContainer ref={navigationRef}>

</NavigationContainer>
```
