### ISSUE TITLE
PanResponder on MapView

### ISSUE THREAD

**Issue by nabati** [react-navigation/react-navigation#5497]
### Current Behavior / Expected behavior

Code is shown in this [repo](https://github.com/nabati/react-navigation-taps-example). The last two commits should show the difference. In the 2.18.3, panning the map is working as expected, in 3.0.9 it is not possible to pan the map anymore. 

I discovered that setting `onShouldBlockNativeResponder` to false makes the Map-view responsive once again (even though the react native docs say it's not supported on iOS - and I tested this in the iOS simulator).

Passing the PanHandlers to a regular react-native View seems to be registering as normal in both versions.

I'm not sure if this is a code-related issue or just a documentation issue but since the issue appeared when upgrading and I couldn't find any clear information on it in previous issues, the documentation for react navigation nor in react native gesture handler, I think it would be good to create a GitHub issue as a reference for the future.

Let me know if any additional information is needed.

**Comment by brentvatne** [comment]
not sure i totally understand - are you saying that a plain mapview inside of a stack does not scroll? if not, what is the purpose of putting panresponder on mapview? is it something you could do with react-native-gesture-handler instead?

**Comment by nabati** [comment]
In both 2.x.x and 3.x.x. it does scroll without the panHandlers. In 2.x.x it scrolled even with the panHandlers, but in 3.x.x it does not scroll with the panHandlers, so I'm trying to figure what the difference is.

The panHandlers in our project were used to detect when the map went off-center (which we've circumvented now through listening to another event from the map).

**Comment by brentvatne** [comment]
the difference is that stack views are wrapped in a PanGestureHandler rather than another PanResponder, and I suppose that's leading to this interaction. to verify you can create a full screen view that has a PanGestureHandler around it, then put a MapView with a PanResponder on it inside of that. if this reproduces the issue then we have some more info on what's going on

**Comment by nabati** [comment]
Your hypothesis seems to be correct;

Removing the StackNavigator completely and then wrapping the view with PanGestureHandler leads to the same interaction. Do you know why this is?

**Comment by nabati** [comment]
Should this be covered in the documentation?

**Comment by brentvatne** [comment]
perhaps in the documentation we should recommend that you use react-native-gesture-handler for every gesture in your app unless you have a very specific reason for wanting to use PanResponder instead, not sure where that would go though!

**Comment by nabati** [comment]
If you use react-native-gesture-handler, then you also have to manage the state/which region is showing. That makes using native methods for animating to a specific region much trickier since the state of the map can be kept in two different places. 

I realise this is outside the scope of the issue for react-navigation but; for some reason using the built in panHandlers seem to work, even though they are attached to what I understand is a native view and one can pan the native map without passing any gesture information explicitly but still capturing the gesture data on the JS-side. 

Do you know if something similar is possible to accomplish with the new version of react-navigation that uses react-native-gesture-handler?

**Comment by APZelos** [comment]
We are facing a similar issue. We have a TextInput inside a ScrollView inside a StackNavigator and we want to prevent the TextInput from getting focused during scrolling. After updating to react-navigation to v3.x.x scrolling isn't working in that screen when you touch the TextInput.

How would you approach a solution to this problem with react-native-gesture-handler? Until now with react-navigation v2.x.x the code bellow worked as expected

```jsx
class MyComponent extends React.Component {
  constructor(props) {
    super(props);

    this.panResponder = PanResponder.create({
      onStartShouldSetPanResponderCapture: () => true,
    });

    this.state = {
      text: 'some text',
    };
  }

  // ... some code ...

  render() {
    return (
      <ScrollView>
        {/* ... some code ... */}
        <View {...this.panResponder.panHandlers}>
          <TextInput value={this.state.text} />
        </View>
        {/* ... some code ... */}
      </ScrollView>
    );
  }
}
```

**Comment by APZelos** [comment]
This issue is resolved in [v0.59](https://github.com/react-native-community/react-native-releases/blob/master/CHANGELOG.md#ios-specific) of react-native.

```
TextInput now has prop rejectResponderTermination to enable TextInputs inside Swipeables to function properly (11df0ea by @cmcewen)
```

**Comment by satya164** [comment]
Thanks for the update @APZelos. Closing the issue.

**Comment by nabati** [comment]
The original issue was actually *not* solved, this thread was just hijacked :)

**Comment by llaver** [comment]
This is still as issue.. this should not be closed.
