### ISSUE TITLE
goBack to recursively identical screen (??)

### ISSUE THREAD

**Issue by devautor** [react-navigation/react-navigation#5500]
I had asked this question (not sure if it's a bug) on [Stackoverflow](https://stackoverflow.com/questions/54244480/react-navigation-goback-to-recursively-identical-screen) and in the discord channel too. Since, I got no help from there, and am unable to solve with the permutations that I tried, I am asking for help here too.
 
### Current Behavior

- I have two screens in the stack, a root category screen (`CategoriesRoot`), and a sub-category screen (`SubCategoryScreen`). If I try to go back from a sub-category that is itself a child of a sub-category, I dircetly fall to the root category screen.

### What I tried

- Importantly this part of code, where I try different things that I read from other issues and QnA:
```
/**
 * For recursive SubCategoryScreens, screen ID (`navigation.state.key`) is the same,
 * so react-navigation takes to CategoriesRootScreen from any nested sub-category screen
 */
_goBack = navigation => {
  console.log(`Back button pressed from a subCategory screen`);
  //navigation.goBack(null);
  navigation.dispatch(
    NavigationActions.back({
      key: null
    })
  );
};

SubCategoryScreen.navigationOptions = ({ navigation }) => ({
  title: navigation.getParam("category").name,
  headerLeft: <HeaderBackButton onPress={() => _goBack(navigation)} />
});
```

### Expected Behavior

- `HeaderBackButton` `onPress` should take me back one screen only, and not to the root screen (of stack).

### How to reproduce

- I have reproduced the code example [here on snack](https://snack.expo.io/@devautor/reac-navigation-issue).
- Navigate to a sub-category that is itself a child of a sub-category, then back button `onPress` from there takes to root categories screen.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | "3.0.9"
| expo     | "32.0.0"

**Comment by brentvatne** [comment]
`For recursive SubCategoryScreens, screen ID (navigation.state.key) is the same` - this is not right, you should *never* have two screens in your navigation state with an identical key

**Comment by brentvatne** [comment]
also, the snack you shared doesn't run

![screen shot 2019-01-19 at 12 31 43 pm](https://user-images.githubusercontent.com/90494/51432044-3b21a700-1be6-11e9-839d-a5bbf24ccdb5.png)

lastly, can you explain what you mean in more concrete terms what a "recursively identical screen" is? this isn't something i'm familiar with

**Comment by devautor** [comment]
Oh! Thanks @brentvatne for your reply! I think I had console printed the keys when I tried to use them for nav and that didn't work (w.r.t. "you should never have two screens in your navigation state with an identical key"). Please allow me to retry more carefully!

I am really sorry for the snack, it ran with me! I used the term "recursive" to imply a condition that a category (screen 1) can have sub-categories (screen 2), that sub-category (screen 2) can have sub-categories (screen 3), and so on (screen N...).

**Comment by devautor** [comment]
> `For recursive SubCategoryScreens, screen ID (navigation.state.key) is the same` - this is not right, you should _never_ have two screens in your navigation state with an identical key

In the same snack, if I try to `console.log` `navigation.state.key`, I get these for sub-categories from screen 2 and screen 3 (in order):
```
eu-ios-12:
Category quia-id-quo has sub-categories.
eu-ios-12:
Nav state key for category quia-id-quo is id-1547930564360-1
eu-ios-12:
Category in-aut-unde has sub-categories.
eu-ios-12:
Nav state key for category in-aut-unde is id-1547930564360-1
```

That is, both the screens give me the same key: `id-1547930564360-1`

**Comment by devautor** [comment]
I just had to ["push" onto stack](https://reactnavigation.org/docs/en/stack-actions.html#push). Really sorry for the trouble @brentvatne 
Thanks for your kind patience!
