### ISSUE TITLE
createBottomTabNavigator leaves notch bar on ios x white

### ISSUE THREAD

**Issue by MrIceman** [react-navigation/react-navigation#5501]
### Current Behavior

- What code are you running and what is happening?
createBottomTabNavigator(..) causes the bottom Home Indicator in ios X to turn white ( see screen )
`
const AppStack = createBottomTabNavigator(
    {
        Feed: homeStack,
        Fragen: questionStack,
        Neu: addStack,
        Profil: profileStack,
        Board: boardStack,
    }, {
        defaultNavigationOptions: ({navigation}) => ({
            tabBarIcon: ({focused, horizontal, tintColor}) => {
                const {routeName} = navigation.state;
                let iconName: string;
                let size = 25;
                let _tintColor = tintColor;

                if (routeName == 'Feed') {
                    iconName = 'md-home';
                } else if (routeName == 'Fragen') {
                    iconName = 'md-text'
                } else if (routeName == 'Neu') {
                    _tintColor = colors.blue;
                    size = 60;
                    iconName = 'md-add-circle';
                } else if (routeName == 'Profil') {
                    iconName = 'md-person'
                } else if (routeName == 'Board') {
                    iconName = 'md-clipboard'
                } else
                    iconName = 'md-home';
                // You can return any component that you like here! We usually use an
                // icon component from react-native-vector-icons
                // @ts-ignore
                return <Ionicons name={iconName} size={size} color={_tintColor} selectionColor={colors.accent}/>;
            },
        }),
        tabBarOptions: {
            inactiveBackgroundColor: colors.toolbarInactive,
            activeBackgroundColor: colors.black,
            activeTintColor: colors.white,
            inactiveTintColor: colors.backgroundColor,
            showLabel: false,
            indicatorStyle: {
                shadowColor: colors.blue,
                backgroundColor: colors.orange,
                height: 150,
                flex: 1
            }
        }
    }
);

let nav = createAppContainer(createSwitchNavigator({
    Auth: AuthStack,
    App: AppStack
}, {
    initialRouteName: 'Auth'
}));

export default nav;`

- Include a screenshot if it makes sense.
![simulator screen shot - iphone x - 2019-01-20 at 13 49 55](https://user-images.githubusercontent.com/8811474/51439540-62e33e80-1cbc-11e9-8e7e-84ec75186755.png)

### Expected Behavior

- What do you expect should be happening?
The white indicator bar should have the same color as the toolbar.

- Include a screenshot if it makes sense.
![simulator screen shot - iphone x - 2019-01-20 at 14 01 03](https://user-images.githubusercontent.com/8811474/51439536-3fb88f00-1cbc-11e9-90a4-74aa26cf5089.png)

### How to reproduce
use createBottomTabNavigator and wrap it into a createNavigationContainer

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.0.9
| react-native     | 0.57.8
| node             | 10.11.0
| npm or yarn      | 6.4.1

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
