### ISSUE TITLE
Deeplink Included In Notification Automatically Redirects To Path Upon Being Received (without being tapped)

### ISSUE THREAD

**Issue by DISKONEKTeD** [react-navigation/react-navigation#5504]
### Current Behavior

Deeplink included in notification automatically redirects to deep link path upon being received by the app. No taps are ever made to the notification, I am simply listening for new notifications and collect them for later use. 

### Expected Behavior

The app should not redirect automatically when a notification with a uri is received. it should not hijack the user's control of the app.

Is there a way to detect deep links and prevent them manually on specific case basis?

### How to reproduce
I followed the deep link instructions. Everything works as expected on Android but on iOS the notification with an included uri deeplink (i'm receiving onesignal notifications), the navigation gets automatically hijacked to the specific uri deeplink provided by the notification.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.0.9
| react-native     | 0.57.8

**Comment by brentvatne** [comment]
you can add `enableURLHandling={false}` on the app container component, we should document this!

**Comment by DISKONEKTeD** [comment]
I actually just ended up following this flow with the custom handling of the url:

https://github.com/geektimecoil/react-native-onesignal/issues/684#issuecomment-456247063


App.js:

```
import { AppState, Linking } from 'react-native';

...

  componentWillMount() {
    AppState.addEventListener('change', this.handleAppStateChange);
  }

  componentWillUnmount() {
    AppState.removeEventListener('change', this.handleAppStateChange);
  }

  handleAppStateChange = (nextAppState) => {
    switch (nextAppState) {
      case 'active':
        setTimeout(() => {
          Linking.removeEventListener('url', NavigationService.openUrl);
        }, 300);
        break;
      default:
        Linking.addEventListener('url', NavigationService.openUrl);
        break;
    }
  };

...

```


NavigationService.js  :

```
....

const openUrl = (event) => {
  const uri = event.url.substring(event.url.lastIndexOf('/') + 1);

  if (PREFIX.test(event.url)) {
    navigator.dispatch(NavigationActions.navigate({
      routeName: 'Post',
      params: { uri },
    }));
  }
};

...

```



enableURLHandling would work if I just wanted to open the app from tapping notifications, but I wanted to still be able to route to the corresponding screen (upon tapping). This solved the issue. 

In iOS it no longer automatically re-routes the user without warning when a notification is received (without being tapped). The user simply remains in place (whatever screen they are located). And I can still tap on notifications, to open up the app to the corresponding screen based on the url provided by the notification.

I had to remove the uriPrefix={PREFIX} I was using originally to handle deeplinking as well.
