### ISSUE TITLE
[Android] : Drawer does not close when clicking outside of container

### ISSUE THREAD

**Issue by TomBerriot** [react-navigation/react-navigation#5508]
### Current Behavior

- What code are you running and what is happening?

The code I'm running : 

```
import React from 'react';
import { StyleSheet, Text, View, Button } from 'react-native';
import { createAppContainer, createDrawerNavigator } from 'react-navigation'
import { DrawerActions } from 'react-navigation';

class Home extends React.Component {
  render() {
    return (
      <View style={styles.container}>
        <Button title="PRESS ME" onPress={() => this.props.navigation.dispatch(DrawerActions.toggleDrawer())}></Button>
      </View>
    );
  }
}

const Drawer = createDrawerNavigator(
  {
    Home: { screen: Home }, 
  }
)

const AppNav = createAppContainer(Drawer)

export default class App extends React.Component {
  render() {
    return (
      <AppNav/>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});

```

When I click outside the drawer on the right side, the drawer does not close.
It is also not possible anymore for us to swipe from the left of the screen to the right to make appear the drawer.
We are not using expo. I tried the same code with Expo and it works. :/

- Include a screenshot if it makes sense.

Click happens where the green cursor is on the right side.

![capture d ecran 2019-01-22 a 15 50 45](https://user-images.githubusercontent.com/11588007/51543300-8691ba80-1e5d-11e9-8656-1e09b2c371cf.png)

### Expected Behavior

- What do you expect should be happening?

In the previous version we used (2.18.0) before upgrading to react-navigation 3.0.9, the drawer was closing fine if clicking outside the drawer container area on android.
We expect the drawer to close automatically when clicking outside the drawer container area.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.0.9
| react-native     | 0.57.5
| node             | 11.7.0
| npm or yarn      | 1.13.0

**Comment by eriveltonelias** [comment]
hi @TomBerriot,

please post a runnable example, I just tested it and works as expected.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/6811057/51650570-e8dae000-1f6f-11e9-8c8b-cb8d50f53cbd.gif)

**Comment by eriveltonelias** [comment]
I see, thanks 

so you're skipping the full installation https://reactnavigation.org/docs/en/getting-started.html#installation  you need to add additional code on `MainActivity.java`

**Comment by TomBerriot** [comment]
@eriveltonelias Thank you for your answer :)

**Comment by eriveltonelias** [comment]
cool :D

**Comment by roaugusto** [comment]
Awesome @eriveltonelias 
It worked for me too.  👍

**Comment by Kawacke** [comment]
It worked for me too, Thanks @eriveltonelias

**Comment by MithleshKumarAndroid** [comment]
When gesture handler used then other Touch not working in android

**Comment by maikosoft** [comment]
@eriveltonelias Thank you

**Comment by lyrathaprinces** [comment]
thanks

**Comment by mossiiiiiii** [comment]
> I see, thanks
> 
> so you're skipping the full installation https://reactnavigation.org/docs/en/getting-started.html#installation you need to add additional code on `MainActivity.jav

Thank you , it worked for me too @eriveltonelias

**Comment by abtuhin** [comment]
@eriveltonelias i have installed and linked react-native-gesture-handler and added code on MainActivity.java file for gesture handler support. But my drawer not closing by clicking outside.
Sometimes it closes but sometimes it does not. But when i slide to close it, it closes smoothly.
can you please help?

**Comment by AkshayP8140** [comment]
I have installed and linked react-native-gesture-handler and added code on MainActivity.java file for gesture handler support. But my drawer not closing by clicking outside.

**"react-native": "0.60.4"**
**"react-native-gesture-handler": "^1.3.0"**
**"react-navigation": "^3.11.1"**

### MainActivity.java

```
package com.Demo;
import com.facebook.react.ReactActivity;
import com.facebook.react.ReactActivityDelegate;
import com.facebook.react.ReactRootView;
import com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView;

import android.content.Intent;

public class MainActivity extends ReactActivity {

     @Override
        public void onNewIntent(Intent intent) {
         super.onNewIntent(intent);
         setIntent(intent);
        }

    @Override
    protected String getMainComponentName() {
        return "Demo";
    }

    @Override
    protected ReactActivityDelegate createReactActivityDelegate() {
      return new ReactActivityDelegate(this, getMainComponentName()) {
        @Override
        protected ReactRootView createRootView() {
            return new RNGestureHandlerEnabledRootView(MainActivity.this);
        }
      };
    }
}

```

can anyone please help?

**Comment by raman-sidhu** [comment]
@AkshayP8140 Have you read this link https://reactnavigation.org/docs/en/getting-started.html#installation

i am using "react-native": "0.57.8", i have also installed 
npm install react-native-reanimated react-native-screens 
for linking when i run following commands 
react-native link react-native-reanimated
react-native link react-native-screens

i got  Error in android studio So i manually remove code from app/build.gradle  
compile project(':react-native-screens')
compile project(':react-native-reanimated')

from settings.gradle
include ':react-native-screens'
project(':react-native-screens').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-screens/android')
include ':react-native-reanimated'
project(':react-native-reanimated').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-reanimated/android')

from Main Application 
import com.swmansion.reanimated.ReanimatedPackage;
import com.swmansion.rnscreens.RNScreensPackage;
  new ReanimatedPackage(),
  new RNScreensPackage(),

clean Project -> Rebuild Project
after that i don't know why but when i successfully run my application i am able to close drawer on clicking outside

**Comment by AkshayP8140** [comment]
@raman-sidhu 
I do this
> npm install react-native-reanimated
> react-native link react-native-reanimated
> npm install react-native-screens
> react-native link react-native-screens

Then 
> npm i jetifier
> npx jetify

After Build android project so got "**Build**: completed successfully"
Then I run the project 
But still not working

**Comment by linkanp** [comment]
> @eriveltonelias i have installed and linked react-native-gesture-handler and added code on MainActivity.java file for gesture handler support. But my drawer not closing by clicking outside.
> Sometimes it closes but sometimes it does not. But when i slide to close it, it closes smoothly.
> can you please help? it's worth to mention that, i am having this issue after migrating react-native from 0.59 to 0.60.5.
> 
> react-native: 0.60.5
> react-navigation: 4.0.0
> 
> **MainActivity.java**
> 
> ```
> import com.facebook.react.ReactActivity;
> import android.content.Intent;
> import android.net.Uri;
> import android.os.Bundle;
> import com.facebook.react.ReactActivityDelegate;
> import com.facebook.react.ReactRootView;
> import com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView;
> 
> public class MainActivity extends ReactActivity {
> 
>     /**
>      * Returns the name of the main component registered from JavaScript.
>      * This is used to schedule rendering of the component.
>      */
>     @Override
>     protected String getMainComponentName() {
>         return "Demo";
>     }
> 
>     @Override
>     public void onNewIntent(Intent intent) {
>         super.onNewIntent(intent);
>         setIntent(intent);
>     }
> 
>     @Override
>     protected void onCreate(Bundle savedInstanceState) {
>         super.onCreate(savedInstanceState);
>     }
> 
>     @Override
>     protected ReactActivityDelegate createReactActivityDelegate() {
>         return new ReactActivityDelegate(this, getMainComponentName()) {
>             @Override
>             protected ReactRootView createRootView() {
>                 return new RNGestureHandlerEnabledRootView(MainActivity.this);
>             }
>         };
>     }
> }
> ```

Have you found any solution for your case? I am using the same version of you and having the same issue.

**Comment by amerizade73** [comment]
package com.reactnavigation.example;

import com.facebook.react.ReactActivity;
+ import com.facebook.react.ReactActivityDelegate;
+ import com.facebook.react.ReactRootView;
+ import com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView;

public class MainActivity extends ReactActivity {

  @Override
  protected String getMainComponentName() {
    return "Example";
  }

+  @Override
+  protected ReactActivityDelegate createReactActivityDelegate() {
+    return new ReactActivityDelegate(this, getMainComponentName()) {
+      @Override
+      protected ReactRootView createRootView() {
+       return new RNGestureHandlerEnabledRootView(MainActivity.this);
+      }
+    };
+  }
}

**Comment by dkpapo** [comment]
thanx work for me :)

**Comment by oleg-tsalabionak** [comment]
I found an option in which drawer does not close when tapping outside. An error appears if you open drawer through method this.props.navigation.toggleDrawer().
Steps to reproduce (here, by the concept of 'open', I mean pressing the toggle button):
1. Open the drawer for the first time (here closing works nice).
2. Select an item from the drawer for navigate to another screen.
3. Open the drawer again - and now it not closing when tapping outside.
If you opens the drawer using slide out - all works nice forever.

**Comment by club9822** [comment]
> I see, thanks
> 
> so you're skipping the full installation https://reactnavigation.org/docs/en/getting-started.html#installation you need to add additional code on `MainActivity.java`

i am using 
```
"react": "^16.8.3",
 "react-native": "^0.59.10",
"react-navigation": "^3.12.1",
 "react-native-gesture-handler": "^1.2.2",
"react-native-reanimated": "^1.1.0"
```

but still have problem

**Comment by sommeshEwall** [comment]
> I found an option in which drawer does not close when tapping outside. An error appears if you open drawer through method this.props.navigation.toggleDrawer().
> 
> Steps to reproduce (here, by the concept of 'open', I mean pressing the toggle button):
> 
> 1. Open the drawer for the first time (here closing works nice).
> 2. Select an item from the drawer for navigate to another screen.
> 3. Open the drawer again - and now it not closing when tapping outside.
> 
> If you opens the drawer using slide out - all works nice forever.

The same behavior is happening. When opening the drawer by the slide to open, it's working fine. But when we customize to open the drawer by using toggleDrawer, I'm getting this issue.

**Comment by club9822** [comment]
you right. this behavior only occur in android   even open drawer wit `openDrawer()`.
ios works fine.


> > I found an option in which drawer does not close when tapping outside. An error appears if you open drawer through method this.props.navigation.toggleDrawer().
> > Steps to reproduce (here, by the concept of 'open', I mean pressing the toggle button):
> > 
> > 1. Open the drawer for the first time (here closing works nice).
> > 2. Select an item from the drawer for navigate to another screen.
> > 3. Open the drawer again - and now it not closing when tapping outside.
> > 
> > If you opens the drawer using slide out - all works nice forever.
> 
> The same behavior is happening. When opening the drawer by the slide to open, it's working fine. But when we customize to open the drawer by using toggleDrawer, I'm getting this issue.

your right. still occur in android even with `openDrawer()` . ios works fine.
i have a custom Drawer Component .maybe style problem!.

**Comment by lautaro-osacar** [comment]
On react-navigation v4:
As a workaround I had to wrap my custom drawer component with 

```

   <View
        style={{
          width: Dimensions.get("window").width,
          height: Dimensions.get("window").height
        }}
      >
        <TouchableWithoutFeedback
          onPress={() =>
            this.props.navigation.state.isDrawerOpen &&
            this.props.navigation.closeDrawer()
          }
        >
          <View
            style={{
              width: 250, //your drawer width (the same as drawerWidth prop on createDrawerNavigator())
            }}
          >
...

**Comment by telltokichu** [comment]
**Environment:**
"react": "16.9.0",
"react-native": "0.61.0",
"react-navigation": "^4.0.10",
"react-navigation-drawer": "^2.3.1",
"react-native-reanimated": "^1.3.0",
"react-native-screens": "^1.0.0-alpha.23",
"react-native-gesture-handler": "^1.4.1",

**MainActivity.java**
package com.example;

import com.facebook.react.ReactActivity;
import com.facebook.react.ReactActivityDelegate;
import com.facebook.react.ReactRootView;
import com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView;
public class MainActivity extends ReactActivity {

  @Override
  protected String getMainComponentName() {
    return "example";
  }
  @Override
  protected ReactActivityDelegate createReactActivityDelegate() {
    return new ReactActivityDelegate(this, getMainComponentName()) {
      @Override
      protected ReactRootView createRootView() {
          return new RNGestureHandlerEnabledRootView(MainActivity.this);
      }
    };
  }
}

**build.gadle**
dependencies {
    implementation project(':react-native-vector-icons')
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.facebook.react:react-native:+"  // From node_modules
    implementation 'androidx.appcompat:appcompat:1.1.0-rc01'
    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0-alpha02'


**Still Not working in Android**

**Comment by ph98** [comment]
this solved my problem : 
https://github.com/react-navigation/drawer/issues/112#issuecomment-546827443

**Comment by kikeztw** [comment]
@telltokichu 

"react": "16.11.0",
"react-native": "0.61.2",
"react-navigation": "^4.0.10",

fixed the problem by adding this to my MainActivity.java

import com.facebook.react.ReactActivity;
+ import com.facebook.react.ReactActivityDelegate;
+ import com.facebook.react.ReactRootView;
+ import com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView;

public class MainActivity extends ReactActivity {

    /**
     * Returns the name of the main component registered from JavaScript.
     * This is used to schedule rendering of the component.
     */
    @Override
    protected String getMainComponentName() {
        return "appName";
    }

   +  @Override
   +  protected ReactActivityDelegate createReactActivityDelegate() {
   +    return new ReactActivityDelegate(this, getMainComponentName()) {
   +      @Override
   +      protected ReactRootView createRootView() {
   +       return new RNGestureHandlerEnabledRootView(MainActivity.this);
   +      }
   +    };
   +  }
}
`

**Comment by senthilkumar3282** [comment]
> 
> 
> I see, thanks
> 
> so you're skipping the full installation https://reactnavigation.org/docs/en/getting-started.html#installation you need to add additional code on `MainActivity.java`

@eriveltonelias i have followed all steps from above link it's close sometime, sometime it's not close

**Comment by swapanil** [comment]
I also have the same problem.

When everything is working fine like createStackNavigator,createTabNavigator and even createDrawerNavigator without this `https://reactnavigation.org/docs/en/getting-started.html#installation` so why just drawer navigator is not closing outside because of this. It is not a justified solution.

**Comment by appify-waheed** [comment]
Make sure to add this in ```android/app/build.gradle``` along with @kikeztw solution.
``` 
implementation 'androidx.appcompat:appcompat:1.1.0-rc01'
implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0-alpha02'```

**Comment by waqaramjad** [comment]
in used all above option but no one works for me

**Comment by waqaramjad** [comment]
> @eriveltonelias i have installed and linked react-native-gesture-handler and added code on MainActivity.java file for gesture handler support. But my drawer not closing by clicking outside.
> Sometimes it closes but sometimes it does not. But when i slide to close it, it closes smoothly.
> can you please help? it's worth to mention that, i am having this issue after migrating react-native from 0.59 to 0.60.5.
> 
> react-native: 0.60.5
> react-navigation: 4.0.0
> 
> **MainActivity.java**
> 
> ```
> import com.facebook.react.ReactActivity;
> import android.content.Intent;
> import android.net.Uri;
> import android.os.Bundle;
> import com.facebook.react.ReactActivityDelegate;
> import com.facebook.react.ReactRootView;
> import com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView;
> 
> public class MainActivity extends ReactActivity {
> 
>     /**
>      * Returns the name of the main component registered from JavaScript.
>      * This is used to schedule rendering of the component.
>      */
>     @Override
>     protected String getMainComponentName() {
>         return "Demo";
>     }
> 
>     @Override
>     public void onNewIntent(Intent intent) {
>         super.onNewIntent(intent);
>         setIntent(intent);
>     }
> 
>     @Override
>     protected void onCreate(Bundle savedInstanceState) {
>         super.onCreate(savedInstanceState);
>     }
> 
>     @Override
>     protected ReactActivityDelegate createReactActivityDelegate() {
>         return new ReactActivityDelegate(this, getMainComponentName()) {
>             @Override
>             protected ReactRootView createRootView() {
>                 return new RNGestureHandlerEnabledRootView(MainActivity.this);
>             }
>         };
>     }
> }
> ```same issue

**Comment by access2fakhar** [comment]
so you're skipping the full installation https://reactnavigation.org/docs/en/getting-started.html#installation you need to add additional code on MainActivity.java

**Comment by Fred-Reis** [comment]
in the index.js of your project:

import {AppRegistry} from 'react-native';
import App from './App';
import {name as appName} from './app.json';
import { gestureHandlerRootHOC } from 'react-native-gesture-handler'

AppRegistry.registerComponent(appName, () => gestureHandlerRootHOC(App));

**Comment by 1453alabanda** [comment]
@eriveltonelias very thanks
> I see, thanks
> 
> so you're skipping the full installation https://reactnavigation.org/docs/en/getting-started.html#installation you need to add additional code on `MainActivity.java`

@Fred-Reis very thanks

> in the index.js of your project:
> 
> import {AppRegistry} from 'react-native';
> import App from './App';
> import {name as appName} from './app.json';
> import { gestureHandlerRootHOC } from 'react-native-gesture-handler'
> 
> AppRegistry.registerComponent(appName, () => gestureHandlerRootHOC(App));

worked for me

**Comment by AndersonSchmidt** [comment]
> in the index.js of your project:
> 
> ```js
> import {AppRegistry} from 'react-native';
> import App from './App';
> import {name as appName} from './app.json';
> import { gestureHandlerRootHOC } from 'react-native-gesture-handler'
> 
> AppRegistry.registerComponent(appName, () => gestureHandlerRootHOC(App));
> ```

THANK YOU!!!

**Comment by jamal-rahimzadegan** [comment]
> I see, thanks
> 
> so you're skipping the full installation https://reactnavigation.org/docs/en/getting-started.html#installation you need to add additional code on `MainActivity.java`

I've downgraded and again upgraded react-navigation, but I don't know why it doesn't give me any error.
BTW this solution is working well

**Comment by kkureli** [comment]
For me the problem was debugger mode was active. When I disabled debugger, it worked
