### ISSUE TITLE
How to add shifting on the material top tab navigator?

### ISSUE THREAD

**Issue by ManigandanRaamanathan** [react-navigation/react-navigation#5510]
### Current Behavior

How to add shifting on the material top tab navigator? Currently the top tab navigator dont have shifting feature. I'm using latest version of react navigation 3.0

**Comment by eriveltonelias** [comment]
hi there! this issue tracker is reserved for bugs only. your post seems to be a usage question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help. thanks!
