### ISSUE TITLE
Any API provides a way to get route list?

### ISSUE THREAD

**Issue by stlst** [react-navigation/react-navigation#5513]
I have referred to #4566 but there isn't a solution. When I get state of navigation, it just return a mass nested routes. So the question is that, any API provides a way to get the current route list? For example, this is the state of routes:

```js
[
  {
    "routes": [
      {
        "key": "route1",
        "routeName": "route1",
        "params": "undefined"
      },
      {
        "key": "route2",
        "routeName": "route2",
        "params": "undefined"
      },
      {
        "key": "route3",
        "routeName": "route3",
        "params": "undefined"
      }
    ],
    "index": 1,
    "isTransitioning": false,
    "routeName": "homePage",
    "key": "id-1548295808154-0"
  },
  {
    "params": "undefined",
    "routeName": "productList",
    "key": "id-1548295808154-5"
  },
  {
    "params": {
      "category": "detail",
      "baseUrl": "/T170206/detail",
      "code": "T170206"
    },
    "routeName": "productDetail",
    "key": "productDetail-T170206"
  }
]
```

What I want to get is an array of routeName, just like `["homePage","route2","productList","productDetail"]`.

**Comment by pzatorski** [comment]
Please check:
https://github.com/react-navigation/react-navigation/issues/4349#issuecomment-393684992

**Comment by eriveltonelias** [comment]
hi there! this issue tracker is reserved for bugs only. your post seems to be a usage question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help. thanks!
