### ISSUE TITLE
How to make header height dynamic???

### ISSUE THREAD

**Issue by maharjanaman** [react-navigation/react-navigation#5514]
How to make header height dynamic???

**Comment by pzatorski** [comment]
This is question to ask on https://stackoverflow.com

It will be nice if you could be a bit more specific. You can customise your headers as much as you want, please check this docs:
https://reactnavigation.org/docs/en/headers.html

If you want to change for example header height in the same screen you can setParams and use it in navigation options as describe in the link above.

**Comment by maharjanaman** [comment]
Thanks for reply but is it possible to change height based on custom header component height? For e.g. if custom component has longer title and is wrapped into next line, the title gets out of header.

**Comment by pzatorski** [comment]
Yes it is possible. This can be a bit sophisticated action. You can measure a layout of the parent View of custom Header and based on this you can change height. But I will suggest to set fixed height. Or if you don't mind to "cut" title you can always use: `numberOfLines={1}` prop for `<Text />` in react-native.

**Comment by pzatorski** [comment]
@maharjanaman I hope my answers where helpful and it will be much appreciated if you close the issue.

**Comment by maharjanaman** [comment]
@pzatorski okay I'll close this now but hope there is simpler workaround or feature in next release or something.
