### ISSUE TITLE
Need Help in react-navigation header

### ISSUE THREAD

**Issue by SatyamAccion** [react-navigation/react-navigation#5516]
I have implemented a drawer menu using react-navigation and i have made the header as null and implemented a custom header using react-native-elements. Now the issue is the left side drawer menu is not getting clicked in IOS, i have tried putting a custom component for left menu icon, but that is also not working, even removed the react-native-elements header and implemented a simple view with a left aligned TouchableHighlight, but this is also not getting clicked.

**Comment by eriveltonelias** [comment]
hi there! this issue tracker is reserved for bugs only. your post seems to be a usage question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help. thanks!
