### ISSUE TITLE
The component for route '...' must be a React component.

### ISSUE THREAD

**Issue by CorentinHeroux** [react-navigation/react-navigation#5517]
This issue -> https://github.com/react-navigation/react-navigation/issues/5515#issue-402657776
with this Snack - > https://snack.expo.io/@corentinheroux/eager-chips

**Comment by pzatorski** [comment]
you export default AppContainer, so you need to import it like this:
`import AppContainer from './Navigation';`

**Comment by CorentinHeroux** [comment]
Yes I tried, but it doesn't make any difference in the error

**Comment by CorentinHeroux** [comment]
@pzatorski Yes I tried, but it doesn't make any difference in the error

**Comment by pzatorski** [comment]
Honestly I can not find a bug in your code.. but I created same thing and it works for me. Maybe there is a problem with naming convention.
Look at this one:
https://snack.expo.io/@pzatorski/tactless-mixed-nuts

**Comment by CorentinHeroux** [comment]
Of course your code also works for me, that's not where my problem is.. !
The problem comes from my constant "Navigator" in ./Navigator, where I try to have a createBottomTabNavigator like in the example "StacksOverTabs.js" of react-navigation.

**Comment by CorentinHeroux** [comment]
@pzatorski 
Of course your code also works for me, that's not where my problem is.. !
The problem comes from my constant "Navigator" in ./Navigator, where I try to have a createBottomTabNavigator like in the example "StacksOverTabs.js" of react-navigation.
Did you launch my code with Snack?

**Comment by pzatorski** [comment]
Okey I get your point now. And I found solution for it. It seems that you need to export stackNavigators, for example `Navigation` to another file.
```
const Navigation = createStackNavigator(
    {
        HomeTabNav: HomeTabNav,
        Ecran2: Ecran2,
    },
    { initialRouteName: 'HomeTabNav' },
);
```
It will solve the error. I don't know why is that.. and you can not have everything in one file.

**Comment by pzatorski** [comment]
https://snack.expo.io/@pzatorski/eager-chips

**Comment by CorentinHeroux** [comment]
Thank you for your time and answer. The answer was fine with me but with this solution how can I access my HomeTabView? I have a "Invariant Violation" when I put it in initialRouteName in MainApplication.js.

**Comment by CorentinHeroux** [comment]
@pzatorski  Thank you for your time and answer. The answer was fine with me but with this solution how can I access my HomeTabView? I have a "Invariant Violation" when I put it in initialRouteName in MainApplication.js.

**Comment by CorentinHeroux** [comment]
https://snack.expo.io/@corentinheroux/eager-chips

**Comment by CorentinHeroux** [comment]
Resolved! 
To summarize, you can't do several "createStackNavigator" in the same file.
For the second problem with Snack, react-native-vector-icons should not be used with expo.

**Comment by pvinis** [comment]
Some more info would be nice.

I have the same problem and I do have two stack navigators in one file that include each other. One has some screens, and the other has the previous stack navigator plus more screens, and the option for mode:modal.

Why can't we have several createStackNavigator in the same file? Is this a bug in the lib? What causes this?

**Comment by satya164** [comment]
Think about why this wouldn't work:

```js
const a = { foo: b };

const b = { foo: a };
```

In short, you have a circular dependency. The file is evaluated top to bottom. In the first statement, `b` isn't initialised yet, and its value is undefined. Nothing specific to the library.
