### ISSUE TITLE
Double Tap Bottom Tab Bar No Reaction (With Modal Structure)

### ISSUE THREAD

**Issue by yuranrobin** [react-navigation/react-navigation#5528]
### Current Behavior

Double tap bottom tab no reaction.

### Expected Behavior

Double tap bottom tab return to root screen.

### How to reproduce

In order to remove bottom tab for a modal screen. I did some trick: (FilterScreen is the one I want to make it modal without bottom tab)

```javascript
const ProblemListStack = createStackNavigator(
  {
    Problems: ProblemsScreen,
    ...
  },
);

const ProblemsStack = createStackNavigator(
  {
    Problems: ProblemListStack,
    Filter: FilterScreen,
  },
  {
    mode: 'modal',
    // To hide header from filter screen modal
    headerMode: 'none',
  }
);

export default createBottomTabNavigator({
  ProblemsStack,
  ReviewStack,
}, {
  navigationOptions: ({navigation}) => ({
     // To hide tab bar from filter screen modal
      tabBarVisible: navigation.state.index === 0,
    }),
});
```

If I remove this trick back to normal tab structure everything works. And my other tab stacks work fine. Is there any way to solve this?

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.0.0
| react-native     | https://github.com/expo/react-native/archive/sdk-27.0.0.tar.gz
| node             | 8.10.0
| npm or yarn      | 6.5.0

**Comment by brentvatne** [comment]
update to the latest react-navigation version and you will see this works. you're on quite an old version

**Comment by yuranrobin** [comment]
Hi Brent,

Thanks for the quick answer. I updated to "react-navigation": "^3.0.9". However the problem still exists.
