### ISSUE TITLE
Android P: Broken animations when transitioning to a screen that contains elements with elevation

### ISSUE THREAD

**Issue by ferrannp** [react-navigation/react-navigation#5535]
### Current Behavior

Navigating to/from a screen that contains elements with elevations (e.g. Cards, Buttons, you name it) will animate incorrectly and look bad starting on Android P.

I think this issue is relatd to https://github.com/facebook/react-native/issues/23090.

See the current situation in Android P:

![nav-elevation-p](https://user-images.githubusercontent.com/774577/51906782-3b2f5d00-23c5-11e9-8628-5e602a00ccc3.png)

### Expected Behavior

- Transition to look as before Android P. See:

![nav-elevation-regular](https://user-images.githubusercontent.com/774577/51906789-42566b00-23c5-11e9-95c6-465a24a245f7.png)

### How to reproduce

https://snack.expo.io/@ferrannp/react-navigation-pie-elevation

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.0.9
| react-native     | 0.57.8
| node             | v10.11.0
| yarn      | 1.13.0

**Comment by pratishshr** [comment]
Any update on this? We are facing the same issue.

**Comment by romitamgai** [comment]
I'm also facing the same issue.. 😢

**Comment by brentvatne** [comment]
we aren't working on it and it would be great if someone could investigate it. see the "help wanted" tag ;)

if you want, you can remove the elevation style from the header to avoid this at least in the header

**Comment by SourceCipher** [comment]
Same issue for the [chat bubbles](https://i.imgur.com/m2SW7Hp.png) with `elevation`. Now we have to use this since borders dont look right at all and the animation is totally broken. Upon going back to the main screen, the chat bubbles becomes black and fades out.

**Comment by tanoabeleyra** [comment]
I'm facing the same problem when switching tabs, it's awful. Is any workaround?

I know it's actually a bug in React Native on Android P, but given that it happens when navigating to a new screen maybe there's some workaround specific to React Navigation (disable animations?).

**Comment by ferrannp** [comment]
Still there, I'll update the first post but still present in latest react-native (`0.61.x`).

**Comment by tanoabeleyra** [comment]
Why did the bot close it?

**Comment by iremlopsum** [comment]
@tanoabeleyra It's an RN bug, and doesn't really have anything to do with react-navigation

**Comment by vtoupet** [comment]
Hey, It looks like there is a workaround/solution. see https://github.com/facebook/react-native/issues/23090#issuecomment-710803743. What do you think, could it be added into react-navigation?

**Comment by stachu2k** [comment]
@vtoupet It looks promising. Any chances from react-navigation development team to implement it in the future?

**Comment by MasterRedStorm** [comment]
That would  really be nice :)
