### ISSUE TITLE
Android recent apps button breaks BackHandler event listener (REPRO)

### ISSUE THREAD

**Issue by beisert1** [react-navigation/react-navigation#5536]
### Current Behavior

Pressing the recent apps button on Android causes the BackHandler event listener to become unresponsive.

### Expected Behavior

Pressing the recent apps button should have no effect on the BackHandler event listener.

### How to reproduce

Clone the repro at https://github.com/beisert1/ReactNavigationAndroidBack.

Open the hamburger menu and press the hardware back button then press the recent apps button and try opening the hamburger menu and pressing the hardware back button.

Environment:
  OS: macOS High Sierra 10.13.6
  Node: 9.4.0
  npm: 5.6.0
  Watchman: 4.9.0
  Android Studio: 3.2.1

Packages:
  react: 16.3.1
  react-native: 0.55.4
  react-navigation: 2.18.3

Device:
  Samsung Galaxy S7

**Comment by beisert1** [comment]
I have noticed that this is a separate issue from minimizing the app with the home button. Minimizing the app with the home button while having "android:launchMode="singleTop"" in the AndroidManifest.xml file with react-native-splash-screen caused the backhandler event to stop responding. 

The recent apps button seems to effect it in a different way, this repro has no additional packages installed besides react-navigation.

**Comment by beisert1** [comment]
Tested on a physical device (Samsung Galaxy s7)

**Comment by brentvatne** [comment]
unrelated to react-navigation, all it does is subscribe to the react-native back handler. it sounds like something related to react-native-splash-screen maybe. you might also want to try installing the latest jsc for android: https://github.com/react-native-community/jsc-android-buildscripts

**Comment by beisert1** [comment]
@brentvatne This repro has no additional package installed besides react-native-splash-screen.

The splash screen was causing an issue with the home button. The recent apps button is a separate issue.

**Comment by beisert1** [comment]
@brentvatne  I think you may have misread my comment, react-native-splash-screen is not included in this REPRO but the issue is still reproducible.
