### ISSUE TITLE
Drawer in not close when click outside of drawer

### ISSUE THREAD

**Issue by onkar-dange** [react-navigation/react-navigation#5540]
## The issue tracker is reserved for bug reports only.

If you have a question, feature request, or an idea for improving the library or its related tools, please try one of the following resources:

- [Read the documentation](https://reactnavigation.org/)
- [Post an issue to the website repository if you'd like to see a documentation change](http://github.com/react-navigation/website)
- [Post a feature request to Canny](https://react-navigation.canny.io/feature-requests)
- [Write a RFC if you have ideas for how to implement a feature request](https://github.com/react-navigation/rfcs)
- [Get help on Discord chat (#react-navigation on Reactiflux)](https://discord.gg/4xEK3nD) or [on StackOverflow](https://stackoverflow.com/questions/tagged/react-navigation)
- Search for your issue - it may have already been answered or even fixed in the development branch. However, if you find that an old, closed issue still persists in the latest version, you should open a new issue.

Bugs with react-navigation must be reproducible *without any external libraries that operate on it*. This means that if you are attempting to use Redux or MobX with it and you think you have found a bug, you must be able to reproduce it without Redux or MobX in this report. Redux related issues belong in [react-navigation-redux-helpers](https://github.com/react-navigation/react-navigation-redux-helpers), and we do not have any first-class integration with MobX at the moment.

---

### Current Behavior

- What code are you running and what is happening?
- Include a screenshot if it makes sense.

### Expected Behavior

- What do you expect should be happening?
- Include a screenshot if it makes sense.

### How to reproduce

- You must provide a way to reproduce the problem. If you are having an issue with your machine or build tools, the issue belongs on another repository as that is outside of the scope of React Navigation.
- Either re-create the bug on [Snack](https://snack.expo.io) or link to a GitHub repository with code that reproduces the bug.
- Explain how to run the example app and any steps that we need to take to reproduce the issue from the example app.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |
| react-native     |
| node             |
| npm or yarn      |

**Comment by onkar-dange** [comment]
https://reactnavigation.org/docs/en/getting-started.html#installation

To finalise installation of react-native-gesture-handler for Android, be sure to make the necessary modifications to MainActivity.java

**Comment by abtuhin** [comment]
i have installed and linked react-native-gesture-handler and added code on MainActivity.java file for gesture handler support. But my drawer not closing by clicking outside.
Sometimes it closes but sometimes it does not. But when i slide to close it, it closes smoothly.
can you please help? it's worth to mention that, i am having this issue after migrating react-native from 0.59 to 0.60.5.

react-native: 0.60.5
react-navigation: 4.0.0

**MainActivity.java**

```
import com.facebook.react.ReactActivity;
import android.content.Intent;
import android.net.Uri;
import android.os.Bundle;
import com.facebook.react.ReactActivityDelegate;
import com.facebook.react.ReactRootView;
import com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView;

public class MainActivity extends ReactActivity {

    /**
     * Returns the name of the main component registered from JavaScript.
     * This is used to schedule rendering of the component.
     */
    @Override
    protected String getMainComponentName() {
        return "Demo";
    }

    @Override
    public void onNewIntent(Intent intent) {
        super.onNewIntent(intent);
        setIntent(intent);
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
    }

    @Override
    protected ReactActivityDelegate createReactActivityDelegate() {
        return new ReactActivityDelegate(this, getMainComponentName()) {
            @Override
            protected ReactRootView createRootView() {
                return new RNGestureHandlerEnabledRootView(MainActivity.this);
            }
        };
    }
}

```

**Comment by cbanning510** [comment]
Also having same issue. Drawer will not close by clicking outside of drawer when opened by toggleDrawer() event.

  "dependencies": {
    "react": "16.8.6",
    "react-dom": "16.8.6",
    "react-native": "0.60.0",
    "react-native-gesture-handler": "^1.3.0",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-orientation-locker": "^1.1.6",
    "react-native-reanimated": "^1.2.0",
    "react-native-safe-area-view": "^0.14.8",
    "react-native-vector-icons": "^6.6.0",
    "react-native-webview": "^7.0.5",
    "react-navigation": "^4.0.5",
    "react-navigation-drawer": "^2.2.1",
    "react-navigation-stack": "^1.7.3"
  },

**Comment by satya164** [comment]
This issue was closed and is describing something else. Please open a new issue for your problem with minimal runnable demo and fill the issue template.

**Comment by ThailanHigor** [comment]
This worked for me.
https://reactnavigation.org/docs/en/getting-started.html#installation
