### ISSUE TITLE
Add and remove  the tabs dynamically 

### ISSUE THREAD

**Issue by KeerthanaManoharan** [react-navigation/react-navigation#5542]
Hi

 Since I'm trying to add the tab dymnamically based on API response from class and passing it to navigator via screenProps but there is no impact in the navigator.
Please give a code sample and give a solution . Here is my conditional rendering code 

  navigationOptions: ({ navigation, screenProps }) => ({
            tabBarVisible: true,
            tabBarLabel: () => {
                const { routeName } = navigation.state;
                var isFocused = navigation.isFocused();
                console.log("my navigator props", screenProps)
                return <Text
                    style={[styles.routeName,
                    { borderBottomColor: isFocused ? '#FF5A5F' : 'transparent' },
                    { color: isFocused ? '#FF5A5F' : '#808080' }]}>
                    {routeName}
                </Text>;
            },
// based on this condition I'm trying to add a tab into the navigator 
Default tab : One Two Three 

after this condition I'm expecting the tabs to be One Two Three Four

            **...screenProps.dynamicTab ? {
                Recommended: {
                    screen: BasketsView,
                    navigationOptions: {
                    },
                }} : {},**

        }),

Thanks in advance

**Comment by brentvatne** [comment]
https://react-navigation.canny.io/feature-requests/p/dynamic-routes-for-navigators

**Comment by chandniKkpl** [comment]
This is not the answer to the question. Can you please reply to it. 
Thanks

**Comment by brentvatne** [comment]
issues are for bug reports and not feature requests or questions :)
