### ISSUE TITLE
createTabNavigator deprecated but not exported in v3.x

### ISSUE THREAD

**Issue by denissb** [react-navigation/react-navigation#5544]
### Current Behavior

When trying to use `createTabNavigator` from `react-navigation` we get:
`TypeError: (0 , _reactNavigation.createTabNavigator) is not a function`

### Expected Behavior

The documentation states that `createTabNavigator` is deprecated, but still present, so I am still expecting to be able to use it, see https://reactnavigation.org/docs/en/tab-navigator.html#docsNav

The functionality should either be removed and marked as a breaking change in the doc, or temporarily put back in place.

### How to reproduce

```
import { createTabNavigator } from 'react-navigation';
import { HomeScreen } from './screens';

const TabNavigator = createTabNavigator({
  Home: HomeScreen,
});
```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  3.0.9
| react-native     |  0.55.3
| node             |  11.7.0
| yarn      | 1.13.0

**Comment by brentvatne** [comment]
it was deprecated in 2.x, it was removed in 3.0. thanks for pointing out that we didn't remove it from the docs! created an issue on website repo for this as you can see in link directly above this comment
