### ISSUE TITLE
createSwitchNavigator behaving strange when debugging

### ISSUE THREAD

**Issue by vendramini** [react-navigation/react-navigation#5546]
Very simple setup:
```javascript
const AppStack = createStackNavigator(
    {
        Home: {
            screen: Home,
        },
    },
    {
        initialRouteName: 'Home',
    }
);

const AuthStack = createStackNavigator(
    {
        Login: Login,
        ForgotPassword: ForgotPassword
    },
    {
        initialRouteName: 'Login',
    }
);

const App = createAppContainer(
    createSwitchNavigator(
        {
            Auth: AuthStack,
            App: AppStack,
        },
        {
            initialRouteName: 'Auth',
        }
    ),
);
```
From `Login` I go to `ForgotPassword`. If I press the **back button** I would like to back to `Login`. Ok, totally fine.

BUT, if I turn on remote debugging on my device, app freezes if I press the back button once and quit the app if I press again.

I don't know if the issue is from react-navigation or is about something in react native itself (metro bundler, I dunno).

Tested only in Android 8.0.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^3.0.9
| react-native     | 0.58.3
| node             | 8.10
| npm or yarn      | 1.12.3

**Comment by vendramini** [comment]
Here: https://snack.expo.io/H1XA4ny44

This happens only in real device. Simulators works well.

Thanks!

**Comment by brentvatne** [comment]
nothing fancy happens here, it's just a back button listener the dispatches an action. i'd suggest trying to repro this with react-native without using react-navigation at all, i imagine you'll find the same issue. the fact that it occurs on your device and not in simulator makes me think that it's probably somehow related to connectivity to your machine, given that when debugging your JS is actually running inside of chrome this seems possible. if you are unable to repro it without react-navigation then let me know! thanks

**Comment by satya164** [comment]
Closing due to no response.
