### ISSUE TITLE
Erratic transition between screens when using react-native-paper with react-navigation 3.x

### ISSUE THREAD

**Issue by napolev** [react-navigation/react-navigation#5550]
Based on the official `Snack Expo` example for `react-native-paper`:

https://snack.expo.io/@satya164/github.com-callstack-react-native-paper:example

I created another `Snack Expo` just by removing all the components but:

    - BottomNavigationExample
    - CardExample

Then got the following `Snack Expo`:

https://snack.expo.io/HJvQBji7E

When I load that `Snack Expo` on my real device: `iPhone` it works totally perfect.

Then, I tried updating `react-navigation` version from: `^2.18.2` to `^3.0.9`.

For that I just did the following changes:

![git-diff](https://i.stack.imgur.com/BIF40.png)

and got the following `Snack Expo`:

https://snack.expo.io/ryLmBlA7E

**My problem is:** when I load that `Snack Expo` on my real `iPhone`, when transitioning between screens, the begining of the animation is erratic. There is some weird shake there. You can see what I mean on the following image:

Screencast: https://i.stack.imgur.com/piQvT.gif

If you try on the online simulator it is not too easy to notice that but it is still there.

Any idea on how to solve this?

If possible, please, provide back a fixed `Snack Expo`.

Thanks!

**Comment by brentvatne** [comment]
this has been fixed in the newest react-native-paper by removing the react-native SafeAreaView
