### ISSUE TITLE
Latest version 3.0.9 doesn't work anymore on tvOS

### ISSUE THREAD

**Issue by hufkens** [react-navigation/react-navigation#5552]
### Current Behavior

- I have upgraded from 2.18.0 to 3.0.9
- The app crashes on startup with the following error:

`Cannot read property 'State' of undefined`

### Expected Behavior

- The app works and starts up without any issues on tvOS

### How to reproduce

- Install 3.0.9 and launch a tvOS target in the react-native project with a stackNavigator.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.0.9
| react-native     | 0.57.7
| node             | v10.14.2
| npm or yarn      | 1.9.4

**Comment by brentvatne** [comment]
we don't explicitly support tvOS, sorry! if you want to get it working again you can look at how to add support to tvOS to react-native-gesture-handler

**Comment by tring-gowrishankaran** [comment]
Can you please guide me on how to add tvOS support to react-native-gesture-handler? 
Also please let me know if there's an alternative.

Thanks
