### ISSUE TITLE
Icons not showing in BottomTabNavigator

### ISSUE THREAD

**Issue by kufii** [react-navigation/react-navigation#5553]
https://snack.expo.io/@adpyke/courageous-kiwi

even with tabBarIcon set and showIcon: true, the icons just won't show up. I'm using Expo in case that matters.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |3.0.9
| expo     |32.0.0
| node             |11.2.0
| npm |6.7.0

**Comment by brentvatne** [comment]
`tabBarIcon` goes under `navigationOptions` https://snack.expo.io/@notbrent/courageous-kiwi

**Comment by kufii** [comment]
Thank you! Figured it would be something simple like that I was missing
