### ISSUE TITLE
headerTransparent: true on previous scene

### ISSUE THREAD

**Issue by inferusvv** [react-navigation/react-navigation#5555]
### Current Behavior

1. I have Stack Router.
2. Home page have normal header.
3. Next page (which opens on click) have `headerTransparent: true` in `static navigationOptions`

On iOS if you will try to go back with swipe right gesture - previous scene will also have `headerTransparent: true` before you finish gesture. So there is not good jump effect.

### Expected Behavior

Probably nothing should jump.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.1.2
| expo | 32.0.0
| react-native     | https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz

**Comment by brentvatne** [comment]
submit a rfc https://github.com/react-navigation/rfcs and explain what your desired behavior is. 'probably nothing should jump' - what should happen then?

**Comment by RockinRonE** [comment]
@brentvatne I must say using `headerTransparent: true` is confusing. I'm also experiencing the same issue. I've been looking for a solution but nothing is clear. 

When one looks at "headerTransparent" they expect this to make the header transparent, but that's not exactly true. It also causes the jumping issue. 

In my case, screen1 has a header and screen2 is set to `headerTransparent: true`. Transitioning from screen1 to screen2 causes the content on screen1 to jump up when transitioning to screen2.
