### ISSUE TITLE
Back button arrow disappears after stopping expo dev server

### ISSUE THREAD

**Issue by MartinMasek** [react-navigation/react-navigation#5559]
### Current Behavior

When stopping the Expo dev server and leaving the simulator open, the arrow for the back button disappears (even though it's still clickable). See the image below:
![image](https://user-images.githubusercontent.com/10037874/52221773-345f8900-28a2-11e9-920f-7de2af76a068.png)

### Expected Behavior

Back arrow is still there as when Expo server is running.

### How to reproduce

Create new project with expo init. 
Copy paste the tutorial code from react-navigation [(link)](https://snack.expo.io/@react-navigation/going-back-v3) 
Run the project
Stop the Expo dev server (ctrl + C)
Navigate to Detail screen

### Your Environment
Macbook
iOS simulator (iPhone X)

| software         | version
| ---------------- | -------
| react-navigation | 3.0.9
| react-native     | https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz
| node             | v10.15.1
| npm or yarn      | npm v6.7.0

**Comment by brentvatne** [comment]
the image is fetched from the server, so when you close the server it can't anymore. i replied to another thread answering this for you, made an issue here so we can add the info to docs: https://github.com/react-navigation/react-navigation.github.io/issues/356
