### ISSUE TITLE
KeyboardAwareNavigator broken

### ISSUE THREAD

**Issue by sdcooke** [react-navigation/react-navigation#5561]
It looks like `KeyboardAwareNavigator` is broken - navigating whilst the keyboard is open on iOS causes my app to go into what appears to be an infinite loop (you have to kill the app). I'm posting the issue to react-navigation because it spans a couple of your repos, I hope that's ok.

I've looked at the code and I think I've found three issues with potential solutions (I don't know the internals well enough to be sure, but I can open a PR if you think that would be easier).

**Problem 1**: `StackView` refers to `onGestureEnd` (https://github.com/react-navigation/react-navigation-stack/blob/master/src/views/StackView/StackView.js#L85) but `KeyboardAwareNavigator` and `StackViewLayout` (which is what `StackView` passes it to) calls it `onGestureFinish`.
**Possible Solution**: I think renaming in `StackView` should be enough.

**Problem 2**: `onGestureBegin` is never called (I've searched the entire codebase, in particular `StackViewLayout` which I think should be calling it).
**Possible Solution**: I _think_ it should be called in `_handlePanGestureStateChange` after `if (nativeEvent.state === State.ACTIVE)` - https://github.com/react-navigation/react-navigation-stack/blob/master/src/views/StackView/StackViewLayout.js#L449 - that seems to fix my issue but I'm not 100% certain that's the correct fix.

**Problem 3**: I think `KeyboardAwareNavigator` might be trying to be slightly too clever restoring focus when a gesture is canceled - when I tried that it still crashed.
**Possible Solution**: remove that functionality? I don't think it's too unexpected if the keyboard doesn't come back automatically after you've started a gesture.

I hope this is helpful - I apologise I'm not providing example code, I can if necessary but I think it's clear from the code that there's something wrong here. Let me know if you need me to do anything else to help get this fixed.

**Comment by brentvatne** [comment]
an example would indeed be useful, thanks

**Comment by sdcooke** [comment]
I'm based in the UK so will have to look into an example tomorrow but I've never used Snack or Expo so it might take a little while. In the meantime I think any react-navigation project using the stack navigator on iOS with TextInputs would probably do this. To reproduce:

1. Navigate at least once (so there is more than 1 screen in the stack) to a screen with a TextInput
2. Focus the TextInput and make sure the keyboard appears
3. Swipe to navigate back to the previous screen
4. The app will hang/crash

I've also just remembered there's another issue, which is related:

1. Go to a screen with a TextInput, focus it (make sure the keyboard is open if on simulator)
2. Navigate to another screen without actively closing the keyboard - it should close as you navigate
3. Go back to the previous screen - the TextInput will become focussed
4. The app will hang/crash

I've worked around this for now by actively calling `Keyboard.dismiss()` on my navigation buttons but if I miss one at some point the bug will come back. I'm not sure what to do about that one - there doesn't seem to be a hook/event provided by react-navigation that allows me to call `Keyboard.dismiss()` at a time that means the app doesn't crash.

**Comment by brentvatne** [comment]
the flow you suggested does not produce any crash or issues: https://snack.expo.io/@notbrent/vengeful-edamame

**Comment by sdcooke** [comment]
Interesting - I'll investigate further tomorrow but the code I mentioned above definitely doesn't look right to me and modifying it fixes my issue.

**Comment by brentvatne** [comment]
I looked over the code and you're completely right, there are a couple of issues here. Thank you for the info!

**Comment by brentvatne** [comment]
Released react-navigation@3.1.3 that should resolve this issue. If not, please create a new issue and share a reproducible example :) Thanks again!

**Comment by sdcooke** [comment]
That definitely fixes my initial issue where the gesture didn't close the keyboard - thank you!

It looks like `onGestureEnd={this.props.onGestureEnd}` in `StackView.js` hasn't been renamed to match `KeyboardAwareNavigator` and `StackViewLayout` which is `this.props.onGestureFinish`. It doesn't cause issues with the keyboard stuff but still looks like a mistake in the code you may want to fix.

**Comment by sdcooke** [comment]
I've done a deeper dive and I think I've found that the reason I was having issues that you weren't seeing was my use of `KeyboardAvoidingView` wrapping the navigator. If the keyboard is closing or opening during a transition `Transitioner._onLayout` gets called which somehow causes what seems to be an infinite loop. Calling `Keyboard.dismiss()` in `onTransitionStart` does not fix the issue since `onTransitionStart` is called slightly too late.

For anyone who hits this and finds this issue later this is the workaround I've gone with to solve the issues (note I have a transitionConfig, this would have to be modified to handle cases where that wasn't provided):

```javascript
const createKeyboardAwareStackNavigator = (routeConfigMap, stackConfig) => {
    const Navigator = createStackNavigator(routeConfigMap, {
        ...stackConfig,
        transitionConfig: (transitionProps, prevTransitionProps) => {
            if (
                prevTransitionProps &&
                prevTransitionProps.index !== transitionProps.index &&
                prevTransitionProps.position === transitionProps.position
            ) {
                // This seems to be the right moment to dismiss the keyboard without
                // calling it too much
                Keyboard.dismiss();
            }
            return stackConfig.transitionConfig(transitionProps, prevTransitionProps);
        },
        disableKeyboardHandling: true
    });

    return class KeyboardAwareNavigator extends React.Component {
        static router = Navigator.router;
        static navigationOptions = Navigator.navigationOptions;

        onGestureBegin = () => {
            Keyboard.dismiss();
            if (this.props.onGestureBegin) {
                this.props.onGestureBegin();
            }
        };

        render() {
            return <Navigator {...this.props} onGestureBegin={this.onGestureBegin} />;
        }
    };
};
```

**Comment by brentvatne** [comment]
thanks for looking into this @sdcooke, removed those remaining references to `onGestureFinish`
