### ISSUE TITLE
Transition prop

### ISSUE THREAD

**Issue by vjsingh** [react-navigation/react-navigation#5563]
### Current Behavior

Simplified explanation: I have a StackNavigator with two views, A and B. The SN is inside my root view R, which checks whether the view is A or B. If A, R adds a top header above A. If B, R does not add a top header.

With the default transition (card sliding in from right), view A shifts upwards when the transition starts. This is because R is removing the header, and thus A shifts upward.

The two solutions I've tried:
- Make the header absolutely positioned, and add a margin-top to A. This works, but adds some development overhead in terms of using onLayout, since the header can change sizes and thus I need to dynamically change the margin on A. I'm worried about performance issues here, and the development complexity added
- Implement a custom navigator with a customer Transitioner. I started doing this, but realized it is a lot of overhead since I need to remake all the transitions myself.

I think that all I would need to implement the behavior correctly, is to be able to add a marginTop to view A while in transition (when the header has disappeared). Is there a prop or some easy way of finding out if a view is in transition? I tried digging through the source code to see how these transitions are managed (surely there must be two Root views during the transition since you can see both views at the same time), but to no avail.

### How to reproduce

I started the Snack here but am having so much trouble:
https://snack.expo.io/@vjsingh/react-navigation-transition

**Comment by brentvatne** [comment]
can you follow the issue template more closely please? it's very unclear to me what the bug is that you believe you are experiencing

**Comment by vjsingh** [comment]
@brentvatne Thanks for linking me to some good examples offline. I managed to create a 3.0 repro in Snack

https://snack.expo.io/@vjsingh/react-navigation-header-v3
Click on "Details" in Home or Settings, and observe that the view that is going off the screen shifts up at the beginning of the transition.

Code-wise, search for "This is the problem here" to see what is causing the problem.

I'm not sure if it counts as a bug or a feature request. I'd be very curious to hear if you have any good or easy suggested solutions though. My suggested solutions above may make more sense now, please let me know here or on Slack if they don't.

**Comment by brentvatne** [comment]
this is an issue with your code, it jumps because the tab bar is removed and the tab bar is positioned relatively so it impacts layout of the screen. if you switch to absolute and render it after the active screen it shows up on top

**Comment by vjsingh** [comment]
@brentvatne Yes, that was the first solution I had listed in my original post. 

I agree this may not be a bug report so perhaps this is not the best place for this. But I was wondering if there was a possibility of another mechanism to enable this besides absolute positioning or a custom transition

**Comment by brentvatne** [comment]
sorry we only handle bugs here, we don't help with designing your app :)
