### ISSUE TITLE
MaterialTopTabNavigator - indicator did not follow custom tab bar width

### ISSUE THREAD

**Issue by ginsan95** [react-navigation/react-navigation#5565]
Hi, I tried to customise the width of the tab bar. I managed to successfully do so, but the indicator is still consuming the whole width of the screen.

---

### Current Behavior
<img width="353" alt="image" src="https://user-images.githubusercontent.com/18420055/52329390-a0bac380-2a2d-11e9-9afb-955593a752de.png">
<img width="348" alt="image" src="https://user-images.githubusercontent.com/18420055/52329415-ab755880-2a2d-11e9-86cc-2f0dc5902e7b.png">
<img width="349" alt="image" src="https://user-images.githubusercontent.com/18420055/52329427-b203d000-2a2d-11e9-84a5-d4c6298e120e.png">

### Expected Behavior
![image](https://user-images.githubusercontent.com/18420055/52329598-33f3f900-2a2e-11e9-93ab-b3466bf4387e.png)
![image](https://user-images.githubusercontent.com/18420055/52329618-3e15f780-2a2e-11e9-9bb3-e21e77a7d8ab.png)
![image](https://user-images.githubusercontent.com/18420055/52329642-4a9a5000-2a2e-11e9-95da-c11d03ab7ccd.png)

### How to reproduce
Below is my code

```
const PersonalInfoTabs = createMaterialTopTabNavigator(
  {
    PersonalData: {
      screen: PersonalData,
      navigationOptions: {
        title: 'A'
      }
    },
    AccountSet: {
      screen: AccountSet,
      navigationOptions: {
        title: 'B'
      }
    },
    ModifyPassword: {
      screen: ModifyPassword,
      navigationOptions: {
        title: 'C'
      }
    }
  },
  {
    tabBarOptions: {
      activeTintColor: 'black',
      inactiveTintColor: 'black',
      style: {
        backgroundColor: 'yellow',
        width: 300
      }
    }
  }
);
```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.0.8
| react-native     | 0.57.8
| node             | 10.14.2
| npm or yarn      | 6.4.1

**Comment by vonovak** [comment]
hi there! this issue tracker is reserved for bugs only. your post seems to be a usage question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help. thanks!
