### ISSUE TITLE
headerTransparent: true stopped working after upgrading to v3.1.3

### ISSUE THREAD

**Issue by yogeshchoudhary147** [react-navigation/react-navigation#5566]
Hello guys,

**headerTransparent: true** in navigationOptions has stopped working after upgrading to v3.1.3. It is not working on v3.1.4 as well. It was working fine on v3.1.2

react-native : v0.55.4
platform: android

v3.1.2
<img width="319" alt="screen shot 2019-02-06 at 3 48 21 pm 1" src="https://user-images.githubusercontent.com/45169237/52335750-29833080-2a29-11e9-91e9-a39ea33a4ad6.png">

v3.1.3 and v3.1.4 both
<img width="317" alt="screen shot 2019-02-06 at 4 04 51 pm" src="https://user-images.githubusercontent.com/45169237/52335765-30aa3e80-2a29-11e9-8905-8a41b96d43c2.png">

**Comment by grissproject** [comment]
Same behavior for me...

**Comment by brentvatne** [comment]
thanks for letting me know, i'll revert https://github.com/react-navigation/react-navigation-stack/commit/648578abc11eff8db83ac73bf298dc02d73d4725

**Comment by brentvatne** [comment]
released 3.1.5 with that commit reverted, if this doesn't fix it please create a new issue and follow the issue template next time

**Comment by yogeshchoudhary147** [comment]
@brentvatne Thanks. It is working on v3.1.5
