### ISSUE TITLE
Expo: Android status bar color results in taller navigation bar

### ISSUE THREAD

**Issue by cpboyd** [react-navigation/react-navigation#5568]
### Current Behavior

In Expo if using a solid background color for the status bar on Android, the navigation bar appears to be double height (likely because it includes the height of the status bar).

If I remove the status bar color, then it works normally.
However, using `<StatusBar>` to try to color it results in the status bar color not visibly changing, which is probably related to other issues like #3826 and #3816.

That may be connected, especially since it seems to indicate that the Navigation bar is **hiding** the underlying status bar.

My device is the Essential PH-1 running Android P, which has a notch, so that may also factor in.

### Expected Behavior

Navigation bar should be normal size.

### How to reproduce

In Expo's app.json
```json
{
  "expo": {
    ...
    "androidStatusBar": {
      "backgroundColor": "#C2185B"
    }
  }
}
```

**EDIT:** I tried to reproduce this in a Snack, but it doesn't appear possible since Snacks ignore any sort of `app.json` file.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |3.1.4
| react-native     |https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz
| node             |6.7.0
| npm or yarn      |v11.9.0

**Comment by cpboyd** [comment]
As a workaround, using this will result in removing the extra space:

```js
import { Constants } from 'expo';
import { Platform } from 'react-native';

const defaultNavigationOptions = {
  ...Platform.select({ android: { headerStyle: { marginTop: -Constants.statusBarHeight, }, }, }),
};
```

**Comment by brentvatne** [comment]
```
import { Platform } from 'react-native';
import { SafeAreaView } from 'react-navigation';
if (Platform.OS === 'android') {
  SafeAreaView.setStatusBarHeight(0);
}
```

a bit hard to find but we documented it here a while ago: https://github.com/react-navigation/react-navigation/releases/tag/v1.0.0-beta.26

not much we can do about this until there is a good primitive in react-native that lets us actually determine how tall the status bar is on android. hoping that https://github.com/facebook/react-native/pull/20999 will be that thing

**Comment by liudas-stonys** [comment]
cpboy, does setting background color in app.json works for you? The only way I was able to change status bar color is by creating a view and setting it's "height: Constants.statusBarHeight". Using <StatusBar> I can only hide and change barStyle. I have a feeling, that <StatusBar> results might vary with different Android versions.

**Comment by cpboyd** [comment]
@liudas-stonys A few things regarding the `backgroundColor`:
Setting the status bar to an opaque color (as `backgroundColor` does) leads to this height discrepancy.
However, trying to change it in Expo resulted in reloads not respecting the `backgroundColor`... I would have to force close the running Expo app (not the main Expo app, but the one I launched from Expo).

I seem to recall that switching between Expo apps seemed to also cause confusion with this parameter, as it seems like Expo may reuse the "launched" app.

Presumably, if you're planning to eventually export the app from Expo, you won't have this issue with a standalone app... But it just became too much of an issue for me to worry about dealing with.

As a result, I stopped using `backgroundColor`.  I was only trying to use it in order to have the keyboard not overlay content, but this caused other display issues when I tried to use a BottomTab navigation (the tabs would be pushed up above the keyboard in addition to the primary content).

I ended up switching to just using a `<KeyboardSpacer />` within the tab content itself from the [react-native-keyboard-spacer](https://github.com/Andr3wHur5t/react-native-keyboard-spacer)

**Comment by cpboyd** [comment]
Just wanted to add: If you're running the snack in the emulator, you may not be able to get `backgroundColor` to work, since you won't be able to force-close the app to get it to fully reload from scratch with the new app.json.

I think I remember seeing some stuff about that... If you're using a device, you should be able to just force-close the app and the backgroundColor should work (but also, potentially, mess with other Expo apps that don't explicitly set their backgroundColor).

**Comment by zapzero** [comment]
Using androidStatusBarColor and androidStatusBar in a same time solve this issue

`"androidStatusBarColor": "#333C4A",
    "androidStatusBar": {
      "barStyle": "light-content",
      "backgroundColor": "#333C4A"
    }`

**Comment by bill-pairaktaridis** [comment]
> Using androidStatusBarColor and androidStatusBar in a same time solve this issue
> 
> ` "androidStatusBarColor": "#333C4A", "androidStatusBar": { "barStyle": "light-content", "backgroundColor": "#333C4A" }`

I have NO idea why this works but it genuinely does. I'm guessing react-navigation is looking for `androidStatusBarColor` and if it's set, doesn't add the top margin. Otherwise, it assumes your app is full screen and should give a background to the status bar.

The problem, obviously, for most of us is that if we have a lighter color for our header, icons will more often than not end up almost invisible.

Either way, great fix and saved me a ton of headache.

**Comment by pyankoff** [comment]
Setting only `"androidStatusBarColor": "#333C4A"` seems to be working fine too😃

**Comment by smoak** [comment]
@brentvatne Not sure if the types are incorrect or maybe this has changed, but with react-navigation v4.0.1, I am getting the following Typescript error with your solution:

```
import { Platform } from 'react-native';
import { SafeAreaView } from 'react-navigation';
if (Platform.OS === 'android') {
  SafeAreaView.setStatusBarHeight(0); // Typescript error here:
/* Property 'setStatusBarHeight' does not exist on type 'ComponentClass<SafeAreaViewProps, any>'. */
}
```

**Comment by brentvatne** [comment]
@smoak - it looks like the type definition is missing here: https://github.com/react-navigation/react-navigation/blob/master/typescript/react-navigation.d.ts#L957 -- you can ignore the error or open a pr to add the type.

this function will be removed in the next major version of react-navigation because it will be handled automatically
