### ISSUE TITLE
Warning: WebView has been extracted from react-native core 

### ISSUE THREAD

**Issue by cwagner22** [react-navigation/react-navigation#5569]
I have this warning with `react-navigation`:
`WebView has been extracted from react-native core and will be removed in a future release. It can now be installed and imported from 'react-native-webview' instead of 'react-native'. See https://github.com/react-native-community/react-native-webview for more informations.`

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.1.4
| react-native     | 0.58.3

**Comment by brentvatne** [comment]
react-navigation doesn't use a webview anywhere

**Comment by nhu** [comment]
Hi,

it's used in https://github.com/kmagiera/react-native-gesture-handler/blob/master/GestureHandler.js of the React Native Gesture Handler which you are listing as dependency in your installation guide.

https://reactnavigation.org/docs/en/getting-started.html

This is causing the issue.

**Comment by eriveltonelias** [comment]
this PR will fix it https://github.com/kmagiera/react-native-gesture-handler/pull/438

**Comment by brentvatne** [comment]
@kmagiera will do a patch release of rngh tomorrow to incorporate this commit

**Comment by kmagiera** [comment]
Just published 1.0.16 with WebView fix, thanks for noting https://github.com/kmagiera/react-native-gesture-handler/releases/tag/1.0.16
