### ISSUE TITLE
Double Tap Bottom Tab Bar No Reaction

### ISSUE THREAD

**Issue by caseyhen** [react-navigation/react-navigation#5570]
### Current Behavior
- Double tap bottom tab no reaction when the content is long and scrollable.

### Expected Behavior
- On those tabs that have long content, when a user double taps the "Home" icon in the bottom bar, it should scroll to the top of the view.

### How to reproduce
* Example in below link
[https://snack.expo.io/@caseyhen/double-click---no-action](https://snack.expo.io/@caseyhen/double-click---no-action)

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.1.5
| react-native     | 0.58.4
| node             | 11.0.0
| npm or yarn      | 6.4.1

**Comment by brentvatne** [comment]
you need to import ScrollView from react-navigation for this: https://snack.expo.io/@notbrent/double-click---no-action

**Comment by brentvatne** [comment]
created a docs issue for this: https://github.com/react-navigation/react-navigation.github.io/issues/360

**Comment by caseyhen** [comment]
Thanks @brentvatne

**Comment by talal7860** [comment]
Can we do this with `FlatList` ?

**Comment by talal7860** [comment]
I do see it working with `FlatList` exported from `react-navigation`, but I see this error every time new elements are added in the feed (our flatlist is more or less like a Facebook wall feed)

![Simulator Screen Shot - iPhone X - 2019-10-24 at 10 04 40](https://user-images.githubusercontent.com/1233457/67504033-ed8b0c80-f645-11e9-9646-ca640c33b1f0.png)

**Comment by talal7860** [comment]
If someone is still looking for the answer to the problem above
This is how the scrollToTop is implemented: https://github.com/react-navigation/native/blob/d0b24924b2e075fed3bd6586339d34fdd4c2b78e/src/createNavigationAwareScrollable.js#L14
I added a custom listener in my FlatList using `useRef` and I have everything I need!

**Comment by sjonchhe** [comment]
this might be helpful
https://reactnavigation.org/docs/use-scroll-to-top
