### ISSUE TITLE
tabBarVisible doesn't work!

### ISSUE THREAD

**Issue by blueturtle13g** [react-navigation/react-navigation#5572]
this is my code:
```
const AppNavigator = createBottomTabNavigator(
    {
        firstScreen: {screen: firstScreen},
        secondScreen: {screen: secondScreen},
        thirdScreen: {screen: thirdScreen},
    }, {
        navigationOptions: {
            tabBarVisible: false
        }
    }
);
```
very simple and accroding to the documentatioin [https://reactnavigation.org/docs/en/bottom-tab-navigator.html](url), but it doesn't work, I still see bottom tab navigator
"react-navigation": "^3.1.5"

**Comment by eriveltonelias** [comment]
Hi @blueturtle13g,

you should use `navigationOptions` on the screen that you want to hide the tabBar or use `defaultNavigationOptions` for the entire bottomNavigator


https://snack.expo.io/@eriveltonelias/cranky-waffle

**Comment by lbonanni** [comment]
This comment helped me : https://github.com/react-navigation/material-bottom-tabs/issues/24#issuecomment-491450177 🙂
