### ISSUE TITLE
Adding extra route when navigate with key into nested StackNavigator

### ISSUE THREAD

**Issue by adimshev** [react-navigation/react-navigation#5575]
### Current Behavior

Adding extra route when navigate with key into nested StackNavigator. So we have two routes with same routeNames and different keys, one is generated automatically and the other is what we pass into navigate.

### Expected Behavior

Adding only one route with current key.

### How to reproduce

https://snack.expo.io/@adimshev/navigate-with-key-into-nested-stacknavigator

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.2.1

**Comment by adimshev** [comment]
I do not want to store all data in redundant storage. SetParams is very convenient for storing the status of an ActivityIndicator or data that is used only on one screen.
I want to use NavigationService (https://reactnavigation.org/docs/en/navigating-without-navigation-prop.html#docsNav) with redux-saga or redux-thunk and use setParams, so I need to know which key corresponds to which route.
In StackNavigator I can set key by passing into NavigationService.navigate, in other navigators key is same with routeName.
But in case with StackNavigator I can't set key of initialRoute and I can't get automatically generated key.
I can use componentDidMount to get route key but it's awful.
Maybe I'm going the wrong way?

**Comment by brentvatne** [comment]
if you don't want to add a new route then just don't specify a key, and if there is an existing route with that route name in the stack navigator then it will navigate there.

i don't really understand the use case here though, if you can make this more concrete i can maybe help.

**Comment by adimshev** [comment]
Use case:
After the user logs in, app must go to the catalog screen, download and show a list of products.

For side effects uses redux-saga or redux-thunk.

User submit the form => dispatch action with route key.
Handle this action in middleware:
 - Show spinner - `setParams ({ key: action.payload.key, params: { loading: true })`.
 - Authorization request.
 - Move to Catalog screen and show spinner, while getting products - `navigate ({ routeName: 'Catalog', { params: { loading: true } })`.
 - GetProducts request.
 - Hide spinner, show products - `setParams ({ key: 'Where to get this key, if Catalog is initialRoute of StackNavigator?', params: { loading: false, products } })`

**Comment by brentvatne** [comment]
you can use an `initialRouteKey` https://reactnavigation.org/docs/en/stack-navigator.html#stacknavigatorconfig

**Comment by adimshev** [comment]
Cool, thank you!

**Comment by jalispran** [comment]
How can I change the value of `initialRouteKey` on button press after the component has loaded. I am trying to remount the component by changing the `key` value.

**Comment by adimshev** [comment]
In react-navigation 5 Stack.Navigator has no prop initialRouteKey.
Can I set initialRouteKey other than using initialState (looks unreliable)?

**Comment by satya164** [comment]
If you need to get the existing key you can use `navigation.dangerouslyGetState()` in a navigator or `navigationRef.getRootState()` on the ref of the container and then inspect the routes.

**Comment by adimshev** [comment]
But I want to set my own initialRouteKey.

**Comment by satya164** [comment]
> But I want to set my own initialRouteKey

What's the point if you can achieve the functionality you want without setting your own initial route key?

**Comment by adimshev** [comment]
> > But I want to set my own initialRouteKey
> 
> What's the point if you can achieve the functionality you want without setting your own initial route key?

I wonna use programmer friendly keys for setParams actions for all routes including initial.
For example same as route name, and route name + entity id for multiply stack routes with same route name.
