### ISSUE TITLE
Report the Example code error(Drawer + Tabs)

### ISSUE THREAD

**Issue by chulphan** [react-navigation/react-navigation#5576]
### Current Behavior

- What code are you running and what is happening?
When i execute the example code(Drawer+Tabs example) both on my phone and simulator, appear a Warning Message.

- Include a screenshot if it makes sense.

on Android Simulator
<img width="270" alt="image" src="https://user-images.githubusercontent.com/35016301/52548136-2c0dcd80-2e0f-11e9-9171-b602366816a4.png">

on VSCode
<img width="1141" alt="image" src="https://user-images.githubusercontent.com/35016301/52548162-595a7b80-2e0f-11e9-8001-fb5cfcf554bc.png">

### How to reproduce

- You must provide a way to reproduce the problem. If you are having an issue with your machine or build tools, the issue belongs on another repository as that is outside of the scope of React Navigation.
- Either re-create the bug on [Snack](https://snack.expo.io) or link to a GitHub repository with code that reproduces the bug.
- Explain how to run the example app and any steps that we need to take to reproduce the issue from the example app.

1. Go to ReactNavigationPlayGround expo page, or clone react-native and then directly execute example code.

2. After start the application, touch the Drawer + Tabs Example.

3. You can see the warning message.

Environment.

Android
Mac

**Comment by brentvatne** [comment]
hello! you can submit a pr for this if you want. there's a bind in there somewhere, it only impacts the example code and doesn't actually come up in users apps so i'm not so bothered to fix it right now
