### ISSUE TITLE
Unnecessary top header in tab navigator

### ISSUE THREAD

**Issue by valdasgrabauskas** [react-navigation/react-navigation#5577]
I'm using react-navigation's createBottomTabNavigator for tab component but I'm getting this result.
![screenshot_1549901568](https://user-images.githubusercontent.com/47500216/52576605-5ab19580-2e5b-11e9-880c-e69f94c5a1c4.png)
Here I don't need the top header, but can't hide it.
Please help me.
I've tried this, but not working.
const TabNavigator = createBottomTabNavigator(
  {
    carOwnerVoice: {screen: CarOwnerVoicePage},
  },
  { 
    headerMode: 'none',
    header: nulll
  }
);

**Comment by brentvatne** [comment]
hi there! this is a question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.
