### ISSUE TITLE
Can l develop the dynamic routing by react-navigation?

### ISSUE THREAD

**Issue by lingxiao-Zhu** [react-navigation/react-navigation#5579]
l need to add a tab in tabbar when l click a button;
for example:
l register 'home', 'my' in createBottomTabNavigator, after APP started, there are two tabs in tabbar, now l need add a 'discovery' tab in tabbar by click a button;

thanks;

**Comment by eriveltonelias** [comment]
hi there! this issue tracker is reserved for bugs only. your post seems to be a usage question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help. thanks!
