### ISSUE TITLE
navigation doesn't have any animation like sliding, it just instantly changes the screen

### ISSUE THREAD

**Issue by blueturtle13g** [react-navigation/react-navigation#5580]
I just installed react navigation by following [https://reactnavigation.org/docs/en/getting-started.html](url).
but I don't get any animation while navigating between my screens (I'm testing it on android)!
OS windows 10
```
  "dependencies": {
      "react": "16.6.3",
      "react-native": "0.58.4",
      "react-native-gesture-handler": "^1.0.15",
      "react-navigation": "^3.2.1",
  },
```

**Comment by jacargentina** [comment]
@blueturtle13g  how do you solved it ?

**Comment by brentvatne** [comment]
don't understand this issue, please create a new one and follow the template if you have a problem @jacargentina
