### ISSUE TITLE
create drawer after login ?

### ISSUE THREAD

**Issue by souhaiebtar** [react-navigation/react-navigation#5581]
i have a login page,

when i login the screen with the drawer show up,

it's working (thanks to react-navigation),

know i'm trying to create drawer with dynamic content, the problem is that the content is only available after the login ( valid token only available after login),

when i tried, it appear that all the stacks are created on start, even the drawer which is only available on the second screen)

is there a way to postpone creation of the drawer until login, or anything like that ?

```
const LoginStack = createStackNavigator(
  {
    LoginScreen: { screen: LoginScreen },
  },
  {
    headerMode: 'none',
  }
);

const DrawerNavigation = createStackNavigator(
  {
    DrawerStack: { screen: DrawerStack },
  },
  {
    headerMode: 'none',
  }
);

const MainNavigator = createStackNavigator(
  {
    loginStack: { screen: LoginStack },
    drawerStack: { screen: DrawerNavigation },
    ChartScreen: { screen: ChartScreen },
  },
  {
    headerMode: 'none',
    initialRouteName: 'loginStack',
  }
);

const Main = createAppContainer(MainNavigator);

export default Main;
```

**Comment by eriveltonelias** [comment]
hi there! this issue tracker is reserved for bugs only. your post seems to be a usage question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help. thanks!
