### ISSUE TITLE
drawernavogator not work 

### ISSUE THREAD

**Issue by praveennamdev** [react-navigation/react-navigation#5584]
import React ,{ Component }from 'react';
import { StyleSheet, Text, View,Button } from 'react-native';
import { Constants } from 'expo';
import {DrawerNavigatior} from 'react-navigation'
import Home from './Home'
import Setting from './Setting'

const navigation= DrawerNavigatior({
   Home:{
     screen:Home
   },Setting:{
    screen:Setting
  }
})

export default navigation

**Comment by brentvatne** [comment]
https://reactnavigation.org/docs/en/drawer-based-navigation.html
