### ISSUE TITLE
Navigating back from nested StackNavigators

### ISSUE THREAD

**Issue by jdnichollsc** [react-navigation/react-navigation#5588]
### Current Behavior

`navigation.goBack()` is not working properly as you can see here: https://github.com/proyecto26/react-native-modular
**Steps:**
- Navigate to **Component2** (nested StackNavigator)
- Navigate Back // It's redirected to Component1 instead  of HomeComponent

### Expected Behavior

Navigate to the previous component 

### How to reproduce

Navigating back from a component different to the initialRouteName of a nested StackNavigator

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.1.5
| react-native     | 0.58.3

Thanks in advance
Juan

**Comment by eriveltonelias** [comment]
Hi @jdnichollsc, 

I just cloned your repro and is working as expected.

![ezgif com-video-to-gif-2](https://user-images.githubusercontent.com/6811057/52753262-11894f00-2fdd-11e9-8a43-e0632fd4366c.gif)

**Comment by jdnichollsc** [comment]
Hi @eriveltonelias

Because I added my custom workaround as you can see here https://github.com/proyecto26/react-native-modular/blob/master/src/services/Navigation/index.js#L218

**Comment by jdnichollsc** [comment]
While the issue navigating back from nested navigators is fixed, I added that workaround in order to register the history of the routes and compare after navigating to remove the initial route of the nested navigators :)

![react-navigation-back-issue](https://user-images.githubusercontent.com/2154886/52798517-146c5a00-3046-11e9-911a-264bf778bd3e.gif)


Any feedback is really appreciated 👍

**Comment by jdnichollsc** [comment]
Maybe adding a new configuration parameter to prevent that behavior would be the best option, what do you think guys?
Best, Juan

**Comment by jacargentina** [comment]
I think i've the same problem but with the modal case (like documented here https://reactnavigation.org/docs/en/modal.html)

Navigating to modal is ok, but when trying to `goBack` and the previos screen was a 2 depth nested screen, it is not working at all.

**Comment by jacargentina** [comment]
@jdnichollsc hey, i've solved my thing by just calling `goBack(null)` in place of `goBack()` as explained here https://reactnavigation.org/docs/en/navigation-prop.html

**Comment by jdnichollsc** [comment]
Cool, but that goBack(null) doesn't work for this issue

**Comment by brentvatne** [comment]
can you try to explain in more detail what the problem is, and provide a more minimal example? there is a lot going on in the repo you shared. tips for minimal examples here https://stackoverflow.com/help/mcve

**Comment by jdnichollsc** [comment]
The previous repo includes a minimal example from the master branch, without that workaround the navigation doesn't work as expected

**Comment by brentvatne** [comment]
if you read that link i sent you, you will see that it's not *minimal* - you should be able to easily fit the example to reproduce the issue you're encountering in one file.

**Comment by jdnichollsc** [comment]
Nested navigators with components in one file? 😱

**Comment by jdnichollsc** [comment]
Check the source code to reproduce the issue, **needs more info** tag doesn't make sense, the issue is very clear (this doesn't require additional steps)
[src.zip](https://github.com/react-navigation/react-navigation/files/2976393/src.zip)

**Comment by brentvatne** [comment]
your unwillingness to follow the suggestions i gave to *help me* to *help you* is a bit hard for me to understand, but i will give it one last try. i took a couple of your files and condensed them into one more minimal example here: https://snack.expo.io/@notbrent/brave-ramen. please add to this whatever you need to demonstrate the issue, without adding anything that is unnecessary or creating a bunch of files / importing other libraries.

**Comment by SantiMA10** [comment]
I had the same issue, if I properly understand this issue. 

The problem is that you execute the `goBack` method over the `UserModule` navigator which has the 'Component1' as `initialScreen`. This is why you are going back to `Component1` from the `Component3` instead of HomeScreen.

**Comment by jdnichollsc** [comment]
@SantiMA10 yeah, the idea is to return to the previous component instead of the initialScreen of that nested navigator 😅

**Comment by jdnichollsc** [comment]
@brentvatne Closing issues looks like a good idea...

**Comment by brentvatne** [comment]
you didn't respond to my last message from 29 days ago so i'm not sure what else to do

**Comment by jdnichollsc** [comment]
@brentvatne I'm very busy at this moment, I can try to do what you are asking me later, but I do not think that you have to solve all the problems. there is a community, another hero may be able to fix this in the meantime.

**Comment by brentvatne** [comment]
@jdnichollsc - ok! i will reopen the issue. hopefully you can find some time to provide a more minimal reproducible example soon :)

**Comment by satya164** [comment]
Closing due to no response.

**Comment by levepic** [comment]
Any solution for this bug? Really annoying bug.
