### ISSUE TITLE
Header disappears when navigating to a nested stack

### ISSUE THREAD

**Issue by otaviogaiao** [react-navigation/react-navigation#5589]
Hello, I have an app with nested navigators.
Basically a stack inside a topTabBar, inside another stack (to make use of the header), inside a bottom tabBar.

The issue is, when I click on an item that should open another stack, it makes the header of the main screen to disappear before the navigation animation completes. It causes a very ugly effect.

I made a video showing the issue. 

![problem](https://user-images.githubusercontent.com/3965485/52733241-61e6b980-2fa9-11e9-8db4-888d496e38ec.gif)

Pay attention to the header during the navigation.

In order to make the header disappear, I have been doing what the documentation suggests and altering the navigationOptions inside the navigator, like this:

```
const hiddenTabBars = ['AnuncioDescricao', 'CancelarIngresso'];

const anunciosTabStackNavigator = createStackNavigator(
  {
    TabEventos: {
      screen: AnunciosTabNavigator,
      navigationOptions: ({ navigation }) => {
        let headerVisible = true;
        const routeName = currentRouteName(navigation);
        if (hiddenTabBars.includes(routeName)) {
          headerVisible = false;
        }
        if (!headerVisible) {
          return {
            header: null,
          };
        }
        return {
          headerLeft: null,
          headerRight: (
            <TouchableOpacity hitSlop={hitSlop15}>
              <MaterialCommunityIcons name="magnify" size={32} color={colors.branco} />
            </TouchableOpacity>
          ),
          title: 'Eventos',
          headerTitleStyle: {
            letterSpacing: 0,
            color: colors.branco,
            fontSize: hp('2.99%'),
            fontFamily: 'roboto-bold',
          },
          headerRightContainerStyle: {
            marginRight: wp('5.57%'),
          },
          ...Platform.select({
            ios: {
              headerTitleContainerStyle: {
                marginLeft: wp('5.8%'),
              },
            },
          }),
          headerStyle: {
            backgroundColor: colors.rosaEscuro,
            height: hp('8.99%'),
          },
        };
      },
    },
  },
  {
    headerLayoutPreset: 'left',
    headerMode: 'screen',
    header: null,
  }
);
```

Did I do something wrong? Is there any way to fix this problem?

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.2.1
| react-native     | 0.57.2 (Expo SDK 32)
| node             | 9.10.0
| npm or yarn      | 1.13.0

**Comment by eriveltonelias** [comment]
Hi @otaviogaiao, 

Can you post a runnable example, please?

**Comment by otaviogaiao** [comment]
I was able to fix it by rearranging my navigators. By cutting one of the stacks from the equation, the problem went away. So I will close it.
