### ISSUE TITLE
react navigation goes to initial route after app.js rendering 

### ISSUE THREAD

**Issue by percyavaur** [react-navigation/react-navigation#5590]
## The issue.

I'm trying to receive a firebase collection on my app.js then send it to AppNavigator.js, it works the first time but when firebase collection is update in anyway, the AppNavigator goes to the initital route. pls help

## package.json
    "expo": "^32.0.0",
    "firebase": "^5.8.2",,
    "react": "16.5.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz",
    "react-navigation": "^3.0.9",

**Comment by eriveltonelias** [comment]
hi there! this issue tracker is reserved for bugs only. your post seems to be a usage question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help. thanks!
