### ISSUE TITLE
Header height issue on iPhones in landscape mode

### ISSUE THREAD

**Issue by jaltin** [react-navigation/react-navigation#5592]
### Background

I am using react-navigation in my app and I have run into an issue with the header height on iPhones (it works as expected on Android phones and on iPad).

### Current Behavior

I have a header with header buttons in it. When the app is in portrait mode the header displays as expected. The following screenshot is from an iPhone XS in portrait mode.

![iphone xs portrait](https://user-images.githubusercontent.com/2103778/52772923-06184100-303a-11e9-9077-4d9382488c82.PNG)

When the app is in landscape mode, the header height seems too low, making the header buttons feel squeezed, and even touches the bottom border of the header. This screenshot (also from the same iPhone XS) illustrate this

![iphone xs landscape](https://user-images.githubusercontent.com/2103778/52772986-2d6f0e00-303a-11e9-8824-023a571340d1.PNG)

I have the same problem for my app on iPhone 6. I have also tested running the Expo NavigationPlayground sample on iPhone 8 simulator, and the same problem exists there.

This height problem only seems to be for iPhones. Neither iPad nor Android has this problem. You can see this in a screenshot I took of the same app on an iPad:

![ipaid air 2 landscape](https://user-images.githubusercontent.com/2103778/52773193-b4bc8180-303a-11e9-863f-5c614ad576b0.PNG)

### Expected Behavior

I expect that the header height should be higher in landscape mode, so that my header buttons fit, just as it does on the iPad and on Android.

### How to reproduce

To reproduce this, simply run the NavigationPlayground example [()](https://github.com/react-navigation/react-navigation/tree/master/examples/NavigationPlayground) on iOS simulator.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.2.1
| react-native     | 0.57.2
| node             | 9.11.2
| npm or yarn      | 1.10.1

**Comment by brentvatne** [comment]
you should adjust the size of your header elements in landscape mode

**Comment by jaltin** [comment]
Thanks for the response @brentvatne.

So are you saying that the height that is shown now is the expected landscape header height on iPhones, and that the problem is that my header icons are too large?

If I would change the height of my header icons/buttons to fit the current height of the header, then they will be so small that it will be difficult to tap them (and to see the details in them). Doesn't feel right to me and I was hoping that the expected result was that they should be as high as on the iPad or Android phones.

**Comment by brentvatne** [comment]
here are a couple examples that will hopefully make this clear, from the ios photos app

![img_1676](https://user-images.githubusercontent.com/90494/52823176-d7658f00-3068-11e9-998d-bc5e3ed99328.jpg)
![img_1677](https://user-images.githubusercontent.com/90494/52823185-dfbdca00-3068-11e9-8481-cd72d3e61b01.jpg)

notice in the full resolution images (they're constrained by the width of a comment above) that the back button is smaller. maybe we should pass in the orientation to the header components so this is easier to do

**Comment by jaltin** [comment]
Thanks for the screenshots @brentvatne . I also read up a bit more and yes, you are right, this is the expected behaviour on the iPhone in landscape mode.

I will close this issue as the header is expected to be like that on iPhone.

You also wrote:

> maybe we should pass in the orientation to the header components so this is easier to do

Yes, it would be great if something could be done in react-navigation to aid users in handling this orientation change. Do you have any good approach to this in mind?

Perhaps worth adding an issue to track how this can be improved but I will either let you add it or wait for your feedback on how it could be done before adding an issue.

And thanks for your great work on react-native @brentvatne!

**Comment by brentvatne** [comment]
shouldn’t be too hard to build but haven’t thought about it yet, created an issue here to track it: https://github.com/react-navigation/react-navigation-stack/issues/85

**Comment by BrentGrammer** [comment]
I'm having the same problem with header height in landscape mode on ios.  Is there a solution to this or an example of how to solve this?
