### ISSUE TITLE
about reactnavigation installation

### ISSUE THREAD

**Issue by songhailong123** [react-navigation/react-navigation#5597]
when I  use reactnavigation and install it,I met a problem whitch is acbout “Could not compile settings file.....\android\settings.gradle'”,This is due to an installation error,we should reaplace "..\node_modules\react-native-gesture-handler\android  "with  "../node_modules/react-native-gesture-handler/android"

My English is poor ，Please forgive me.

**Comment by MyDreamWuBiLian** [comment]
Not related to this library

**Comment by brentvatne** [comment]
good luck figuring it out! :) you can do it!
