### ISSUE TITLE
Unable to resolve module `./KeyGenerator`

### ISSUE THREAD

**Issue by buzinas** [react-navigation/react-navigation#5603]
### Current Behavior

The code I'm running is:

```jsx
import React from 'react'
import { createSwitchNavigator } from '@react-navigation/core'
import { createAppContainer } from '@react-navigation/native'

import SignIn from './screens/SignIn'
import SignUp from './screens/SignUp'

const Navigator = createSwitchNavigator(
  {
    SignIn,
    SignUp,
  },
  {
    initialRouteName: 'SignIn',
  },
)

const AppContainer = createAppContainer(Navigator)

const App = () => <AppContainer />
export default App
```

### Expected Behavior

The code above contains no errors and it works when using the `react-navigation` library directly.

### Actual Behavior

The bundler fails with:

```bash
Error: Unable to resolve module `./KeyGenerator` from `node_modules/@react-navigation/core/routers/StackRouters.js`: The module `./KeyGenerator` could not be found.
```

By the way, I checked the `node_modules/@react-navigation/core/routers` folder, and indeed, there is no KeyGenerator file (nor a folder with an index.js file etc).

### How to reproduce

- Install only `@react-navigation/core` and `@react-navigation/native`
- Import `createSwitchNavigator` from the former and `createAppContainer` from the latter
- Build a navigator
- Try to open your app

### Your Environment

| software         | version
| ---------------- | -------
| @react-navigation/core | 1.1.0
| @react-navigation/native    | 3.1.4
| node             | 10.15.1
| yarn      | 1.13.0

**Comment by ericvicenti** [comment]
Very sorry about this. Should be fixed if you change `@react-navigation/core` to `3.1.1`

**Comment by buzinas** [comment]
Thanks for the fast fix @ericvicenti!
