### ISSUE TITLE
Buttons on header left/right not working

### ISSUE THREAD

**Issue by spyshower** [react-navigation/react-navigation#5604]
### Current Behavior

- What code are you running and what is happening?

```
static navigationOptions = ({ navigation }) => {
    return {
      headerLeft: (
        <TouchableOpacity onPress={() => console.log('hello')}>
          <Text>click</Text>
        </TouchableOpacity>
      ),
    }
  };
```

The TouchableOpacity (or any other Touchable class) and Button are not working. In fact, when clicked, they don't even flicker like a button would when pressed.

This is happening in a tab navigator, defined like this:

```
const HomeTabNavigator = createMaterialTopTabNavigator({
  Encountersscreen: {
    screen: createStackNavigator({
      Encountersscreen: {
        screen: Encounters,
        navigationOptions: {
          ...
```

It works ok outside a tab navigator, defined like this:

```
const RootNavigator = createStackNavigator(
  {
    Homescreen: {
      screen: HomeTabNavigator,
      navigationOptions: {
        // headerTitle: 'Home',
        headerTransparent: true,
      },
    },
```

Am I doing something wrong?

EDIT: It works on Android, but not on iOS.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^3.3.0
| react-native     |  0.57 (Expo)
| node             | latest
| npm or yarn      | latest

**Comment by eriveltonelias** [comment]
Hi @spyshower, 

https://snack.expo.io/@eriveltonelias/drawer-with-back-button 
if that isn't what you're looking for, please post a runnable example.  https://reactnavigation.org/docs/en/header-buttons.html#docsNav

**Comment by spyshower** [comment]
Hi @eriveltonelias,

I didn't mention anything about drawers or back buttons. Are you sure the snack is relevant?
