### ISSUE TITLE
Screens not responding to touch with authentication flow setup ( android )

### ISSUE THREAD

**Issue by HonzaJiran** [react-navigation/react-navigation#5606]
### Current Behavior

- Running the exact same code from react navigation 3.x.x [Authentication flows](https://reactnavigation.org/docs/en/auth-flow.html) documentation.
- Screens are all loaded and renders just fine.

### Expected Behavior

- Working touch events on android.
- on iOS everything is ok.

### Actual Behavior

- All screens become unresponsive to touch events.
- Console logs and all other screen logic is working fine. Even when I use DrawerNavigator instead of Stacknavigator in AppStack, I'm able to swipe from left and Drawer will appear. But everything else is like "frozen".
- Example with StackNavigator ![ezgif-1-9c61a54a8f25](https://user-images.githubusercontent.com/12970583/53012734-297d2a80-3444-11e9-9d73-53eb0ecd0787.gif)

### How to reproduce
- [Update your react-native-gesture-handler to the latest version](https://github.com/react-navigation/react-navigation/issues/5606#issuecomment-465230795), I was using 1.0.14 which didn't work. After updating to 1.0.15, everything is ok.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.3.0 ( also tried 3.09 )
| react-native     | 0.58.0
| node             | 10.15.1
| npm or yarn      | 6.7.0

**Comment by vonovak** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

Are you running the latest version of react-native-gesture-handler?

**Comment by HonzaJiran** [comment]
Ok, @vonovak was totally right, there was problem with react-native-gesture-handler version ( 1.0.14 ).
I have updated it to 1.0.15 and everything works fine. Thanks.
