### ISSUE TITLE
Command failed: gradlew.bat installDebug

### ISSUE THREAD

**Issue by wxy1234567890** [react-navigation/react-navigation#5607]
I install 'react-navigation' according to official documents developing Android on the window, however, when I run 'react-native run-android' ,problems as follows:

FAILURE: Build failed with an exception.

* Where:
Settings file 'F:\myRNproject\android\settings.gradle' line: 3

* What went wrong:
Could not compile settings file 'F:\myRNproject\android\settings.gradle'.
> startup failed:
  settings file 'F:\myRNproject\android\settings.gradle': 3: unexpected char: '\' @ line 3, column 127.
     ules\react-native-vector-icons\android')
                                   ^

  1 error

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html

Command failed: gradlew.bat installDebug

Error: Command failed: gradlew.bat installDebug
    at checkExecSyncError (child_process.js:616:11)
    at Object.execFileSync (child_process.js:634:13)
    at runOnAllDevices (F:\myRNproject\node_modules\react-native\local-cli\runAndroid\runAndroid.js:299:19)
    at buildAndRun (F:\myRNproject\node_modules\react-native\local-cli\runAndroid\runAndroid.js:135:12)
    at isPackagerRunning.then.result (F:\myRNproject\node_modules\react-native\local-cli\runAndroid\runAndroid.js:65:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by brentvatne** [comment]
unrelated to react-navigation

**Comment by aroldoandrade** [comment]
open your 'settings.grandler' file in the android folder

change the '\\' to '/'

save the file

run the command 'react-native run-android

Sorry for my English translator.

**Comment by Diegolaquino** [comment]
> open your 'settings.grandler' file in the android folder
> 
> change the '\' to '/'
> 
> save the file
> 
> run the command 'react-native run-android
> 
> Sorry for my English translator.

Thank you, aroldoandrade.

**Comment by luis-otavio** [comment]
> 
> 
> open your 'settings.grandler' file in the android folder
> 
> change the '\' to '/'
> 
> save the file
> 
> run the command 'react-native run-android
> 
> Sorry for my English translator.

Worked here.

**Comment by syedamirali14** [comment]
> open your 'settings.grandler' file in the android folder
> 
> change the '\' to '/'
> 
> save the file
> 
> run the command 'react-native run-android
> 
> Sorry for my English translator.

i didn't get it sorry can you guide me a little?

**Comment by PurnimaNaik** [comment]
@aroldoandrade do you mean **settings.grandle** instead of settings.grandler? I don't have a ' \ ' in my settings.grandle

**Comment by BayeuxRemy** [comment]
@PurnimaNaik  I do not have '\' either in my seettings.gradle. I do not know how to fix this error ..> <I tried all the solutions of the forums..

**Comment by codebased** [comment]
Please check my solution here: https://stackoverflow.com/questions/54776936/command-failed-gradlew-bat-installdebug/56062411#56062411

**Comment by fernandopedro** [comment]
> Please check my solution here: https://stackoverflow.com/questions/54776936/command-failed-gradlew-bat-installdebug/56062411#56062411

Perfect. Work for me.

**Comment by sivajyothisaladi** [comment]
BUILD FAILED in 5s
26 actionable tasks: 1 executed, 25 up-to-date
error Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html
error Command failed: gradlew.bat app:installDebug. Run CLI with --verbose flag for more details.

please answer this error

**Comment by asfand10** [comment]
> open your 'settings.grandler' file in the android folder
> 
> change the '\' to '/'
> 
> save the file
> 
> run the command 'react-native run-android
> 
> Sorry for my English translator.

Thanks man!! worked perfectly

**Comment by muneebahmed97** [comment]
I don't find just "/" in settings.gradle

**Comment by Hasintha-git** [comment]
> I don't find just "/" in settings.gradle

apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings)

This one

**Comment by RonBouch** [comment]
Inside your app root folder then run
Try : **chmod 755 android/gradlew**
 
Worked for me.

**Comment by arhamabeer** [comment]
I didn't find a single **'\'** in my settings.gradle file, can some one guide me on this?

**Comment by arhamabeer** [comment]
'\'

**Comment by Dhika1011** [comment]
Failed to install the app. Command failed with exit code 1: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

**Comment by C2418M31** [comment]
I also experience this error.

 error Failed to install the app. Command failed with exit code 1: gradlew.bat app:installProdGoogleDebug -PreactNativeDevServerPort=8081
 
 Integrating RN to exisiting app is very very hard and ive been doing testing for 2 weeks and havent even build it once. Need to convert everything to Kotlin DSL. I hope the core devs of RN able to fixed this and the compatibility to the latest android DSL.
