### ISSUE TITLE
2. X upgrade to 3. X encountered problems

### ISSUE THREAD

**Issue by vitozyf** [react-navigation/react-navigation#5609]
### Current Behavior

I try to `react - navigation` from 2 x upgrade to 3.3.0 and upgrade in document and installed ` react - native - gesture - handler `, then run the ` react - native link the react - native - gesture - handler `, and ` navigationOptions ` instead ` defaultNavigationOptions `.

With that done, android runs perfectly.

But on the ios side, the screen got stuck on the startup page and there was no error. I found that increased ` pod 'RNGestureHandler Podfile files, the: the path = >'.. / node_modules/react - native - gesture - ` handler ', so I again run ` pod install `, but the problem still unsolved.

### Expected Behavior

It works perfectly on ios

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.3.0
| react-native     |  0.57.2
| node             | 11.1.0
| npm or yarn      | yarn

**Comment by brentvatne** [comment]
hello! you will need to figure out how to get the react-native-gesture-handler package installed on ios, we don't provide support for that
