### ISSUE TITLE
Deep Linking Docs Outdated

### ISSUE THREAD

**Issue by alvin-toffler** [react-navigation/react-navigation#5610]
Hi,

In the [docs for deep linking](https://reactnavigation.org/docs/en/deep-linking.html), it says to implement `application:openURL:sourceApplication:annotation:` which is deprecated. The new method to be implemented is `application:openURL:options:`, but I'm not sure how to call `RCTLinkingManager application:openURL:sourceApplication:annotation:` from within this method. 

What do I pass for `sourceApplication` and `annotation`? 

I can update the docs if I get the solution. Thank you.

**Comment by alvin-toffler** [comment]
The new method has also been implemented for RCTLinkingManager:

`[RCTLinkingManager application:application openURL:url options:options];
`
Closing.

**Comment by pvinis** [comment]
Noone updated the docs..
