### ISSUE TITLE
tabBarOnPress not fired when tab is another stack

### ISSUE THREAD

**Issue by ProfessionalAmateur** [react-navigation/react-navigation#5611]
### Current Behavior

Trying to fire the tabBarOnPress when a tab is selected from a createBottomTabNavigator, this work correctly if a tab is just a component, but if the tab is a createStackNavigator the event is not fired.  I've tried to pass in the event as an option when creating the createBottomTabNavigator and have also tried to create `static navigationOptions` on the component as well.  
  
In the example below you will see the console message for the `NewTab` but not for `StackNav` tab.

### Expected Behavior

How can the event `tabBarOnPress` be fired regardless of what the tab is consisting of?

### How to reproduce

    import React from 'react';
    import { Text, View, Button } from 'react-native';
    import { createBottomTabNavigator, createStackNavigator } from 'react-navigation';

    class NewTabScreen extends React.Component {
      static navigationOptions = ({ navigation }) => {
        return {
          headerTitle: 'New Tab Screen',
          tabBarOnPress: ({navigation, defaultHandler }) => {
            console.log("New Tab Screen tabBarOnPress working")
            defaultHandler();
          }
        }
      }
      render () {
        return (  
          <View>
            <Text>New Tab Screen</Text>    
          </View>
        );
      }
    }

    class StackOneScreen extends React.Component {
      static navigationOptions = ({ navigation }) => {
        return {
          headerTitle: 'Stack One Screen',
          tabBarOnPress: ({navigation, defaultHandler }) => {
            console.log("Stack One Screen tabBarOnPress working")
            defaultHandler();
          }
        }
      }

      _nav = () => {
        this.props.navigation.navigate('StackTwo')
      }

      render () {    
        return (   
          <View>  
            <Text>Stack One Screen </Text>
            <Button title='Navigate' onPress={this._nav} />
          </View> 
        )
      }
    }

    class StackTwoScreen extends React.Component {
      static navigationOptions = ({ navigation }) => {
        return {
          headerTitle: 'Stack Two Screen',
        };
      };
      render () {
        return (         
          <View>  
            <Text>Stack Two Screen</Text>        
          </View> 
        )
      }
    }

    const AppStack = createStackNavigator(
      {
        StackOne: StackOneScreen,
        StackTwo: StackTwoScreen,    
      },
      {
        initialRouteName: "StackOne",     
      }
    );

    const AppNavigator = createBottomTabNavigator(
      {    
        'StackNav': { screen: AppStack },
        'NewTab': { screen: NewTabScreen },    
      },
      {
        navigationOptions: ({ navigation }) => ({
          title: navigation.state,      
          tabBarIcon: ({ focused, horizontal, tintColor }) => {
            const { routeName } = navigation.state;
          }
        }),
        swipeEnabled: false,     
        tabBarOptions:{
          labelStyle: {      
            fontSize: 24,
          }
        },
        tabBarOnPress: (navigation) => {
          console.log("tabBarOnPress Options Passed In")      
        }
      }
    );

    export default class App extends React.Component {
      render() {
        return (
          <AppNavigator />
        );
      }
    }

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | "^2.0.0"
| react-native     | "0.57.1",
| node             | "v8.11.3:
| npm or yarn      |  "yarn: 1.13.0"

**Comment by brentvatne** [comment]
hello! this doc will be useful for you: https://reactnavigation.org/docs/en/navigation-options-resolution.html

**Comment by ProfessionalAmateur** [comment]
Thank you for the fast response Brent, worked like a perfectly.

**Comment by sagargulati** [comment]
Did you manage to get it working? I have a similar issue. https://github.com/react-navigation/react-navigation/issues/5708#issuecomment-476720737

**Comment by ProfessionalAmateur** [comment]
Yes following the link Brent provided I was able to get this to work properly.   https://reactnavigation.org/docs/en/navigation-options-resolution.html

**Comment by sagargulati** [comment]
Have a look? https://github.com/react-navigation/react-navigation/issues/5708#issuecomment-477118828

**Comment by ryanyue123** [comment]
can you show your solution to this?

**Comment by sagargulati** [comment]
Updating it to the latest version fixed the issue.

**Comment by anggaip** [comment]
I still have this issue.

**Comment by GitHubTracey** [comment]
If others come across this, if your iOS works okay, but Android is not... 
Thanks to @Aure77 in this [tabs ticket](https://github.com/react-navigation/tabs/issues/202)

In addition to the comments above, I also had to override both `tabBarOnLongPress` and `tabBarOnPress`.

Now it works great!

**Comment by xcinnocence** [comment]
@GitHubTracey ,You're right. You solved my problem.thank you

**Comment by SampsonCrowley** [comment]
This doesn't work on react-native-web

**Comment by brentvatne** [comment]
create a new issue and provide a minimal reproducible example

**Comment by slorber** [comment]
Can confirm @GitHubTracey solution. On latest 4.x, `tabBarOnPress` does not fire consistently unless `tabBarOnLongPress` is also implemented
