### ISSUE TITLE
How do react-navigation get to the navigation component of the current routing page

### ISSUE THREAD

**Issue by iOSQiao** [react-navigation/react-navigation#5612]
How do react-navigation get to the navigation component of the current routing page?
react-navigation 1.x

**Comment by eriveltonelias** [comment]
hi there! this is a question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.

**Comment by iOSQiao** [comment]
@eriveltonelias I can't open the url.

**Comment by eriveltonelias** [comment]
https://reactnavigation.org/help.html

**Comment by iOSQiao** [comment]
It's OK.
