### ISSUE TITLE
undefined is not a function(evalution '(0,_reactNavigation.StackNavigatior)

### ISSUE THREAD

**Issue by KevinChenJin** [react-navigation/react-navigation#5613]
/**
 * @format
 * @lint-ignore-every XPLATJSCOPYRIGHT1
 */

import {AppRegistry} from 'react-native';
import App from './App';
import { StackNavigator } from 'react-navigation';
import FlatListDemo from './pages/FlatListDemo';
import { name as appName} from './app.json';

const AppRoot=StackNavigator({
   App:{
       screen:App,
   },
   FlatListDemo:{
       screen:FlatListDemo,
       navigationOptions:{
           title:'FlatListDemo'
       }
   }
});

AppRegistry.registerComponent(appName, () => AppRoot);

**Comment by KevinChenJin** [comment]
undefined is not a function(evalution '(0,_reactNavigation.StackNavigatior), 
How should this problem be solved？

**Comment by eriveltonelias** [comment]
```js
import { createStackNavigator } from 'react-navigation'
```

https://reactnavigation.org/docs/en/stack-navigator.html#docsNav
