### ISSUE TITLE
Tabs with stacks navigates incorrecly

### ISSUE THREAD

**Issue by kidcosmic** [react-navigation/react-navigation#5614]
### Current Behavior

Tabs with Stacks under each Tab
Tab 2 and Tab 3 have a screen called Profile
Tab 3's default screen is Profile

Pushing a new Profile onto the Tab 3 stack will cause react navigation to switch to Tab 2 and and push a Profile onto the Tab 2 Stack

### Expected Behavior

Pushing a new Profile onto the Tab 3 stack will push a new Profile onto the Tab 3 stacks

### How to reproduce

Create above config.
Open Tab 3, push any screen onto Tab 3, push Profile onto Tab 3

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.3.0
| react-native     | 0.58.5
| node             |  11.4.0
| npm or yarn      | 1.13.0

**Comment by eriveltonelias** [comment]
hi! please make your code runnable either on https://snack.expo.io without any extraneous code

**Comment by eriveltonelias** [comment]
I'll close the issue for now, but you can add the repro to the original post and then ping me and I'll reopen to investigate. Thanks for understanding.
