### ISSUE TITLE
Stack navigation Header doesn't work together with Context

### ISSUE THREAD

**Issue by palodelincak** [react-navigation/react-navigation#5616]
### Current Behavior

- The header in stack navigation screen does not display when the screen is wrapped into React Context.
- The header works fine once the React Context is removed from screen.

### Expected Behavior

- I expect the header to work even with screen wrapped into React Context.

### How to reproduce

- Please take a look at this Snack where issue is reproduced https://snack.expo.io/@palodelincak/react-navigation-test.
- Steps to reproduce in Snack are easy - simple press the buttons and you will see that the header works for one screen, but not for the other.

**Comment by eriveltonelias** [comment]
Hi @palodelincak, 

you can use `navigationOptions` on your route config to solve, https://snack.expo.io/@eriveltonelias/react-navigation-test

and also check the `withNavigation`, this code use React context API https://github.com/react-navigation/react-navigation-core/blob/master/src/views/withNavigation.js
