### ISSUE TITLE
Nested (3 Level) stack navigator not showing back button in header

### ISSUE THREAD

**Issue by artalat** [react-navigation/react-navigation#5617]
### Current Behavior

I'm trying to create a layout using react-navigation. This layout involves nested stack navigators. I'm 3 levels deep. The screens are structured like this:

```
RootStack (StackNavigator)
   - Root (StackNavigator)
      - Home
      - Details
      - Another (StackNavigator)
         - Deep
   - Login
```
[Snack Link of working example](https://snack.expo.io/@artalat/react-navigation-wrapped-stack)

The problem is when I navigate to the "Deep" screen, the screen header doesn't show a back button. See the gif below for a visual example:

<img src="https://user-images.githubusercontent.com/295630/53258615-e4305580-36ee-11e9-927c-8b3bbebecffa.gif" width="250">

I have also noticed when I enable header of parent navigator, back button is shown and works as expected.

<img src="https://user-images.githubusercontent.com/295630/53258658-0629d800-36ef-11e9-80c7-8ead62d06c24.gif" width="250">

### Expected Behavior

When navigating to the "Deep" screen, back button is shown in the header.

### How to reproduce

[Snack Link of working example](https://snack.expo.io/@artalat/react-navigation-wrapped-stack)

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^3.3.0
| react-native     | ^0.57.0
| node             | 11.4.0
| npm or yarn      | yarn 1.12.3

**Comment by brentvatne** [comment]
that's a different stack, back buttons only appear when the active screen index is > 0 for the stack that it's a part of

**Comment by artalat** [comment]
Thanks, but what is the proper way to achieve the desired behavior then?

**Comment by brentvatne** [comment]
sorry we don't provide support here for things that aren't bugs, you could try out https://reactnavigation.org/help to see where to get help on how to use it
