### ISSUE TITLE
Unsupperted top level event type "topGestureHandlerStateChange" dispatched

### ISSUE THREAD

**Issue by capslock35** [react-navigation/react-navigation#5618]
### Current Behavior

On iPhone emulator, when I try to go back to previous screen by swiping from left edge of screen to right I get this error.

### Expected Behavior

I expect to go back to previous screen

### How to reproduce

I do not use expo, I run my app with react-native run-ios

### Your Environment

react-native 0.55.4
react-navigation 3.2.3
react-native-gesture-handler 1.0.15

**Comment by eriveltonelias** [comment]
Hi @capslock35,

I just created an example using `react-navigation@3.3.0` is working as expected, I'll close this issue for now, but feel free to create a new issue following the issue template, please.

thanks!
