### ISSUE TITLE
Conflict between Flatlist and drawer menu 

### ISSUE THREAD

**Issue by imansalhi** [react-navigation/react-navigation#5619]
### Current Behavior

horizontal Flatlist has conflict with drawer menu. 
seems their gesture responder have some conflicts  

### Expected Behavior

swiping horizontal Flatlist when user moves finger on that and swipe drawer menu when user starts touching from the side of screen.

just as when you use a horizontal Flatlist with no **drawerPosition** !!!

### How to reproduce

create a drawer menu with ``drawerPosition: 'right'`` <<<<<<important 
and add a horizontal Flatlist in your page.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.3.0
| react-native     | 0.58.5
| node             | 10.15.0
| npm or yarn      | npm
|react-native-gesture-handler | 1.0.15

**Comment by eriveltonelias** [comment]
hi! please make your code runnable either on https://snack.expo.io without any extraneous code

**Comment by eriveltonelias** [comment]
I'll close the issue for now, but you can add the repro to the original post and then ping me and I'll reopen to investigate. Thanks for understanding.
