### ISSUE TITLE
Deeplinking without createStackNavigation() at root

### ISSUE THREAD

**Issue by NikoMontana** [react-navigation/react-navigation#5620]
### Current Behavior

Implemented multiple stacks into tabNavigator.
I want to get into the DetailsScreen `createBottomTabNavigator > MainStack > Home > Details` with `my_app://main/home/details` or `my_app://main/details`. App is always openining initialRoute from TabNavigator. 

Tested with `my_app://seccond` from default web browser while the app remained in background and still showing Home from MainStack.

`App.js` is the entry point but not a switchStack because I need a running database connection for MaintenanceScreen. So its the parent of all react-navigation logic.

**App.js**
```
  render() {
    if (this.state.isLoading) {
      return <View />;
    }
    if (!this.state.isLoading && this.state.show_maintenance && !__DEV__) {
      return <MaintenanceScreen />;
    }
    if (!this.state.isLoading && this.state.show_update_native_version) {
      return <UpdateNativeVersionScreen />;
    }
    if (!this.state.isLoading && this.state.show_taskBrowse) {
      return <MainScreen />;
    }
  }
}

export default CodePush(codePushOptions)(App);
```

**MainScreen.js**

```
const MainStack = createStackNavigator(
  {
    Home: {
      screen: MainScreen,
      path: "home"
    },
    Details: {
      screen: DetailsScreen,
      path: "details"
    },
  {
    initialRouteName: "Home"
  }
);

const BottomNav = createBottomTabNavigator(
  {
    Main: { screen: MainStack, path: "main" },
    Second: { screen: SecondStack, path: "second" },
  },
  {
    initialRouteName: "Jobs",
    tabBarPosition: "bottom",
    animationEnabled: true,
    swipeEnabled: false
  }
);

const BottomNavWithPrefix = () => <BottomNav uriPrefix={"my_app://"} />;

export default BottomNavWithPrefix;
```

### Expected Behavior

Deeplink is opening the App but is not switching to the desired Subscreen.

### How to reproduce

Read my code. Think its because `App.js`, which cannot cascade the url to the `MainScreen`.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.17.0
| react-native     | 0.57.1
| node             | 8.12.0
| npm or yarn      | 6.4.1

## Usage with the official Docs

The docs are suggesting a simple use case, where the authentification happens only once - at start. The solution for this problem is to implement `createAppContainer()` & `createStackNavigator()`. The StackNavigator is switching on condition and the condition is set in the component / screen itself.

## My use case

`App.js` is the entry point for my App. This component mimics the behaviour of `createStackNavigator()` **by rendering** either Register- or MainScreen. The difference between those two usecases is that I am able to keep the logic in `App.js` running while I am displaying a nested screen withing `App.js`, `createStackNavigator()` cant do this.

This is important to me because I have several other Screens that are not in the MainStack and should not be changeable by the user itself. For better understanding I will bring up an example, my MaintananceScreen. As you might notice this screen is for mainenance purpose, by keeping an listener on my database and reacting to changes, it switches to it.

**Comment by brentvatne** [comment]
@NikoMontana - "read my code" isn't a runnable example. please provide a git repo we can clone :)

**Comment by eriveltonelias** [comment]
I'll close the issue for now, but you can add the repro to the original post and then ping me and I'll reopen to investigate. Thanks for understanding.
