### ISSUE TITLE
Android Error Not Resolve: null is not an object (evaluating 'RNGestureHandlerModule.State'. 

### ISSUE THREAD

**Issue by Anhmike** [react-navigation/react-navigation#5624]
The issue is not yet resolved for  Android. You had only resolve with IOS.  I follow the instruction as on https://reactnavigation.org/docs/en/getting-started.html.

So other Android guys out there must have the same issue as I have. 

The result is Unhandled JS Exception: null is not an object (evaluating 'RNGestureHandlerModule.State'. 

Here are the dependencies and the java files:

  "dependencies": {
    "react": "16.6.3",
    "react-native": "0.58.5",
    "prop-types": "15.7.2"
    "react-native-screens": "1.0.0-alpha.22"
    "react-native-gesture-handler": "1.0.16",
    "react-navigation":"^3.3.0"
  }

On MainActivity.java

import com.facebook.react.ReactActivity;
import com.facebook.react.ReactActivityDelegate;
import com.facebook.react.ReactRootView;
import com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView;

public class MainActivity extends ReactActivity {

    /**
     * Returns the name of the main component registered from JavaScript.
     * This is used to schedule rendering of the component.
     */
    @Override
    protected String getMainComponentName() {
        return "reactnativethird";
    }

    @Override
    protected ReactActivityDelegate createReactActivityDelegate() {
        return new ReactActivityDelegate(this, getMainComponentName()) {
            @Override
            protected ReactRootView createRootView() {
                return new RNGestureHandlerEnabledRootView(MainActivity.this);
            }
        };
    }
}

On MainApplication.java

import android.app.Application;

import com.facebook.react.ReactApplication;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;
import com.facebook.soloader.SoLoader;

import java.util.Arrays;
import java.util.List;

public class MainApplication extends Application implements ReactApplication {

  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
    @Override
    public boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage()
      );
    }

    @Override
    protected String getJSMainModuleName() {
      return "index";
    }
  };

  @Override
  public ReactNativeHost getReactNativeHost() {
    return mReactNativeHost;
  }

  @Override
  public void onCreate() {
    super.onCreate();
    SoLoader.init(this, /* native exopackage */ false);
  }
}

**Comment by brentvatne** [comment]
you need to properly follow the setup instructions for react-native-gesture-handler on android

**Comment by Anhmike** [comment]
I did to the exact T.  I am using Windows 10. Why close it down and brush off the issue? 

Here is the instruction from https://kmagiera.github.io/react-native-gesture-handler/docs/getting-started.html#installation.

It says to do
1. yarn add react-native-gesture-handler   
2. react-native link react-native-gesture-handler
3. update MainActivity.java

import com.facebook.react.ReactActivity;
+ import com.facebook.react.ReactActivityDelegate;
+ import com.facebook.react.ReactRootView;
+ import com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView;

public class MainActivity extends ReactActivity {

  @Override
  protected String getMainComponentName() {
    return "Example";
  }

+  @Override
+  protected ReactActivityDelegate createReactActivityDelegate() {
+    return new ReactActivityDelegate(this, getMainComponentName()) {
+      @Override
+      protected ReactRootView createRootView() {
+       return new RNGestureHandlerEnabledRootView(MainActivity.this);
+      }
+    };
+  }
}

**Comment by brentvatne** [comment]
i close it because we can't possibly provide support for everyone who needs help installing react-native-gesture-handler. i know that it's working as expected, so this isn't a bug. you can check out https://reactnavigation.org/help for places to get help
