### ISSUE TITLE
Window 10 error for adding react-native-gesture-handler; Result in : null is not an object (evaluating 'RNGestureHandlerModule.State'

### ISSUE THREAD

**Issue by Anhmike** [react-navigation/react-navigation#5626]
I am using Windows 10. 
Getting same error. 
Here is the instruction from https://kmagiera.github.io/react-native-gesture-handler/docs/getting-started.html#installation.

It says to do

1. yarn add react-native-gesture-handler
2. react-native link react-native-gesture-handler
3. update MainActivity.java

import com.facebook.react.ReactActivity;

* import com.facebook.react.ReactActivityDelegate;
* import com.facebook.react.ReactRootView;
* import com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView;

public class MainActivity extends ReactActivity {

@override
protected String getMainComponentName() {
return "Example";
}

* @override
* protected ReactActivityDelegate createReactActivityDelegate() {
* return new ReactActivityDelegate(this, getMainComponentName()) {
* ```
   @Override
  ```
* ```
   protected ReactRootView createRootView() {
  ```
* ```
    return new RNGestureHandlerEnabledRootView(MainActivity.this);
  ```
* ```
   }
  ```
* };
* }
  }

**Comment by brentvatne** [comment]
https://reactnavigation.org/help
