### ISSUE TITLE
Not able to close the app on click of back button when using createSwitchNavigator

### ISSUE THREAD

**Issue by naiduprakash** [react-navigation/react-navigation#5630]
### **Not able to close the app on click of back button when using createSwitchNavigator**

---

### Current Behavior

- After navigating to AppStack on click of hardware back button nothing happen

### Expected Behavior

- After navigating to AppStack on click of hardware back button it should close the app

### How to reproduce
- you can see the example app of switchNavigator on official [Snack](https://snack.expo.io/BkyGuF_kQ)

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | "3.0.0"
| react-native     | "0.57.7"
| node             | "v10.13.0"
| npm      | "6.4.1"

**Comment by matthamil** [comment]
I am unable to reproduce the issue with the provided Snack. Navigating into the AppStack and clicking the hardware back button does close the app for me.

**Comment by matthamil** [comment]
Closing since I can't reproduce the issue and haven't heard back from the Author. Feel free to reopen another issue if you can continue to reproduce it.
