### ISSUE TITLE
How we can use swipe in react navigation V3 with bottomTabNavigator

### ISSUE THREAD

**Issue by The-Developeur** [react-navigation/react-navigation#5631]
Hello,
I'm using react navigation V3 and i want to use swipe in my bottomTabNavigator.
i can't do it because createBottomTabNavigator don't support it any yet and createBottomNavigator is actually deprecated.
It is very annoying because in react navigation V2 we can do iteasily.
Just createMaterialTopTabNavigator support swipe but i want a bottom navigator and not a top one

### How to reproduce

Create a TabNavigator

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | v3
| react-native     | 0.58.5
| node             |  10
| npm or yarn      | yarn version v1.13.0

**Comment by brentvatne** [comment]
this isn't supported. you can use the top tabs and position them to the bottom, but this isn't the platform standard behavior for ios or android for bottom tabs so we don't support it
