### ISSUE TITLE
Upgrade dependencies for react-native-gesture-handler to 1.0.16 to support react-native-web 

### ISSUE THREAD

**Issue by jclough96** [react-navigation/react-navigation#5632]
### Current Behavior

react-native-web not building due to react-navigation dependency on old version of react-native-gesture-handler in @react-nativigation

### Expected Behavior

The fix has been pushed in the latest version of react-native-gesture-handler to work with web.
https://github.com/kmagiera/react-native-gesture-handler/pull/406
Update the dependencies manually fixes all errors so please can we update the repo to match?

**Comment by brentvatne** [comment]
this is available in react-native-gesture-handler@>=1.1.0, we'll update to that soon. you can override this in your app if you want using yarn resolutions right now if you want.
