### ISSUE TITLE
Missing in DOCS "unmountInactiveRoutes: boolean"

### ISSUE THREAD

**Issue by crobinson42** [react-navigation/react-navigation#5633]
StackNavigator config option `unmountInactiveRoutes` is missing in the website docs.

**Comment by crobinson42** [comment]
I was told about this option in the Discord channel by another member

**Comment by brentvatne** [comment]
there is no such thing on stack, only on switch - https://github.com/react-navigation/react-navigation-stack/search?q=unmountInactiveRoutes&unscoped_q=unmountInactiveRoutes

**Comment by brentvatne** [comment]
sorry no it's only on drawer: https://github.com/react-navigation/react-navigation-drawer

**Comment by anmolpandeyy** [comment]
> sorry no it's only on drawer: https://github.com/react-navigation/react-navigation-drawer/blob/bf4bdba7f6a4fbc12192f5d5ba2285f6280431b7/src/routers/DrawerRouter.js#L22-L26

// when it is set unmountInactiveRoutes to true it applies to every route

Is there any way to unmount/mount only one screen every time and not all of the screens in drawer navigator?

Suppose I have 5 screens in drawer navigator, I want just one screen to be mounted always and rest other to be always unmounted when navigating. How can I achieve this?
