### ISSUE TITLE
Flatlist ("Tried to register two views with the same name RNGestureHandlerButton")

### ISSUE THREAD

**Issue by skb1129** [react-navigation/react-navigation#5634]
I see the following error when using Flatlist from react-navigation:

![img_1222](https://user-images.githubusercontent.com/24582791/53544788-540a6a00-3b4d-11e9-9161-4dfa302bc002.PNG)

react-native: 0.57.8
react-navigation: 3.0.9
react-native-gesture-handler: 1.0.12

The error can be reproduced by using a simple Flatlist:
```
          <FlatList
            initialNumToRender={5}
            keyExtractor={item => item.notificationId}
            renderItem={this.getCard}
            data={notifications}
            contentContainerStyle={{ padding: 10 }}
            onEndReached={this.loadMore}
            ListFooterComponent={this.showLoader}
          />
```
The same code works with the react-native Flatlist.

**Comment by brentvatne** [comment]
you have multiple versions of react-native-gesture-handler installed in your project.

from the project root, run `find . -name react-native-gesture-handler` or check yarn.lock/package-lock.json to see. adjust versions so that they're able to deduplicate on install
