### ISSUE TITLE
react-navigation can't work with ApolloProvider

### ISSUE THREAD

**Issue by thisisakoo** [react-navigation/react-navigation#5635]
i try to use apollo-client and react-navigation for react-native App.
then i found that navigation.navigate('Detail', {}) can't work. App crashed.

But when i  set Debug Js Remotely and Debugger is up. 
navigation.navigate worked.
#706
https://github.com/react-navigation/react-navigation/issues/706#issuecomment-292920259

part of package.js
    "react-navigation": "^3.3.2", 
    "react-apollo": "^2.5.1",

app.js:
export default class App extends React.Component {
  componentDidMount() {

  };

  render() {

    console.log(deviceinfofromapi);
    return (

      <ApolloProvider client={apolloclient}>
        <AppContainer
        />
      </ApolloProvider>
    )
  }
}

**Comment by brentvatne** [comment]
this is incorrect. here's an app that uses them together just fine: https://github.com/expo/expo/blob/master/home/package.json

create a snack with a reproducible example and generally follow the template in the future please
