### ISSUE TITLE
React Navigation Import Error

### ISSUE THREAD

**Issue by vaibhavjn** [react-navigation/react-navigation#5638]
### Current Behavior

App.js File -
import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { createStackNavigator, createAppContainer } from 'react-navigation';
export default class App extends React.Component {
  render() {
    return (
      <View style={styles.container}>
        <Text>Open up App.js to start working on your app!</Text>
      </View>
    );
  }
}
const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});

The above code I have written and on importing react-navigation, getting this error
![error](https://user-images.githubusercontent.com/8787999/53628301-b12b1c00-3c30-11e9-86ff-f884d3f447ff.png)

I have installed react native setup with expo and using react-navigation too.

please find below the package.json dependencies I am using
![package](https://user-images.githubusercontent.com/8787999/53628516-3f9f9d80-3c31-11e9-96c9-12effe19485b.png)

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.3.2
| react-native     | https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz
| node             | 10.9.0
| npm or yarn      | 6.2.0

Please if anyone can help.

**Comment by brentvatne** [comment]
here's an example of using it on the web: https://github.com/react-navigation/react-navigation-web

this library is still primarily oriented towards react-native ios and android though.
