### ISSUE TITLE
Warning: bind(): You are binding a component method to the component. React does this for you automatically in a high-performance way, so you can safely remove this call. See ScrollView

### ISSUE THREAD

**Issue by ShaggyKris** [react-navigation/react-navigation#5640]
### Current Behavior

Keep getting warning (40 times) of 

> Warning: bind(): You are binding a component method to the component. React does this for you automatically in a high-performance way, so you can safely remove this call. See ScrollView

when I call `this.props.navigation.navigate()` using the following code: 
```
async componentDidMount(){
    await this.navigateToHome();
}
	
async navigateToHome() {
    // const {navigate} = this.props.navigation;
    const userToken = await AsyncStorage.getItem("reactnativemeteor_usertoken");
    if(userToken)
        this.props.navigation.navigate( 'AppRoot' );
};
```

Stack trace is as follows:

> Stack trace:
  node_modules/react-native/Libraries/YellowBox/YellowBox.js:59:8 in error
  node_modules/fbjs/lib/warning.js:33:20 in printWarning
  node_modules/fbjs/lib/warning.js:57:25 in warning
  node_modules/create-react-class/factory.js:710:14 in bind
  node_modules/react-native-gesture-handler/GestureHandler.js:675:55 in _refHandler
  node_modules/react-native-gesture-handler/GestureHandler.js:221:14 in _refHandler
  node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:12288:10 in commitAttachRef
  node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:13505:22 in commitAllLifeCycles
  node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:92:15 in invokeGuardedCallbackImpl
  node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:306:36 in invokeGuardedCallback
  node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:13702:8 in commitRoot
  node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:15269:13 in completeRoot
  node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:15197:21 in performWorkOnRoot
  node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:15090:24 in performWork
  node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:15047:14 in performSyncWork
  node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:14925:19 in requestWork
  node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:14711:16 in scheduleWork
  node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:7700:17 in enqueueSetState
  node_modules/react/cjs/react.development.js:364:31 in setState
  node_modules/@react-navigation/native/src/createAppContainer.js:352:22 in dispatch
  screens/LoginScreen.js:41:35 in navigateToHome$
  node_modules/regenerator-runtime/runtime.js:62:44 in tryCatch
  node_modules/regenerator-runtime/runtime.js:288:30 in invoke
  node_modules/regenerator-runtime/runtime.js:288:30 in invoke
  node_modules/regenerator-runtime/runtime.js:62:44 in tryCatch
  node_modules/regenerator-runtime/runtime.js:152:28 in invoke
  node_modules/regenerator-runtime/runtime.js:162:19 in <unknown>
  node_modules/promise/setimmediate/core.js:37:14 in tryCallOne
  node_modules/promise/setimmediate/core.js:123:25 in <unknown>
  node_modules/react-native/Libraries/Core/Timers/JSTimers.js:152:14 in _callTimer
  node_modules/react-native/Libraries/Core/Timers/JSTimers.js:200:17 in _callImmediatesPass
  node_modules/react-native/Libraries/Core/Timers/JSTimers.js:464:30 in callImmediates
  node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:320:6 in __callImmediates
  node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:135:6 in <unknown>
  node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:297:10 in __guard
  node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:134:17 in flushedQueue

### Expected Behavior

No warnings should happen.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^3.0.9
| react-native     | https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz
| expo | ^32.0.0
| node             | v8.11.2
| npm or yarn      | 6.5.0

**Comment by brentvatne** [comment]
warning comes from react-native-gesture-handler, it'll be fixed next time we bump the peerDependency version

**Comment by ShaggyKris** [comment]
@brentvatne I had a feeling that was the case. I was unsure where to post this error. Given that Expo relies on version ~1.0.14 of react-native-gesture-handler, do you think there will be any conflict if I update React Navigation beyond ^3.0.9?

**Comment by brentvatne** [comment]
looking into doing patch release of rngh that includes the commit that fixes this

**Comment by ShaggyKris** [comment]
@brentvatne I found out what was causing the issue! And it also created another issue that I did not document. I was using the SectionList provided by React Navigation, and it was causing all of these issues. As well, it was causing Images on iOS to not appear.

**Comment by brentvatne** [comment]
@ShaggyKris - i know, you probably don't want to do that though. the latest release of react-navigation fixes the warnings by bumping to the latest patch version of react-native-gesture-handler
