### ISSUE TITLE
undefined is not an object- react native

### ISSUE THREAD

**Issue by adi0109** [react-navigation/react-navigation#5642]
i am new to react native
tried to do the navigation part and got stuck

Expected behaviour : on clicking the button from app component, it should show the TEST component

Actual: the app installs, first screen shows up , something like this: 
![image](https://user-images.githubusercontent.com/39994366/53664147-c08c8280-3c8d-11e9-9006-e8d35197307b.png)

but On clicking
![image](https://user-images.githubusercontent.com/39994366/53664096-90dd7a80-3c8d-11e9-8cfd-20d8ba2e97fa.png)

react-native run-android

**App.js** file:

import React, {Component} from 'react';
import {Platform, StyleSheet, Text, View, Image, TextInput, Button,Alert} from 'react-native';
import { createStackNavigator} from 'react-navigation';

type Props = {};
export default class App extends Component<Props> {
  render() {
    return (
      <View style={styles.container}>
        
        <Image style={styles.img}source={require('C:\\rnprojects\\Hello\\src\\Image\\logoimg.png')}/>
		<Text style={styles.welcome}>Welcome to React Native!</Text>
		
		<TextInput style={styles.inputsty}
		placeholder="Username"/>
		<TextInput style={styles.inputsty}
		placeholder="Password"
		/>
		<Button title="Click Me"
			color="#0044cc"
			onPress={() => this.props.navigation.navigate('test')}
		/>
		
		
      </View>
    );
  }
}

class Test extends Component {
  render() {
    return (
      <View style={styles.container}>
        
        <Text style={styles.welcome}>Hola!!</Text>
		
		
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#6AC5F3',
  },
  welcome: {
    fontSize: 20,
	fontFamily: 'bold',
	color: 'black',
    textAlign: 'center',
    marginBottom: 50,
  },
	  
  img: {
	  height: 120,
	  width:120,
	  justifyContent:'center',
  },
  inputsty: {
	  height:50,
	  width:300,
	  backgroundColor :'white' ,
	  marginBottom: 20,
	  fontSize: 20,
	  paddingHorizontal: 10,
  },
  
	  
  
});

createStackNavigator({
	
	home: App,
	test: Test,
})

**Comment by brentvatne** [comment]
hi! looks like you might want to go through the fundamentals guides, starting here: https://reactnavigation.org/docs/en/getting-started.html
