### ISSUE TITLE
null is not an object ( evaluating 'RNGestureHandlerModule.State') [ios]

### ISSUE THREAD

**Issue by smartdev619** [react-navigation/react-navigation#5645]
Getting this Error in ios
null is not an object ( evaluating 'RNGestureHandlerModule.State') [ios]

yarn add react-navigation
yarn add react-native-gesture-handler
react-native link react-native-gesture-handler
![image](https://user-images.githubusercontent.com/28682562/53680507-c40e2100-3d02-11e9-9cac-45d1da3ee524.png)

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^3.3.2
| react-native     | 0.58.5

**Comment by eriveltonelias** [comment]
this happens if you haven't installed RNGH properly. be sure to follow the steps from here: https://reactnavigation.org/docs/en/getting-started.html#installation

**Comment by Mokkapps** [comment]
@eriveltonelias I followed exactly the steps from the tutorial but still receive the same error

**Comment by brentvatne** [comment]
@Mokkapps - this error happens if the project hasn't been properly linked. if you're not familiar with how to link projects on ios and don't want to debug that, you can use [expo-cli](https://docs.expo.io/versions/v32.0.0/introduction/installation/) instead if you want. otherwise you'll need to figure this out on your own, maybe try starting from scratch and following https://kmagiera.github.io/react-native-gesture-handler/docs/getting-started.html#installation

**Comment by smartdev619** [comment]
Issue with the version
 "react-native-gesture-handler": "^1.1.0",
working fine

**Comment by skoch-tf** [comment]
remember that after installing and change the java activity file you should restart your server (yarn start) and reinstall the app (react-native run-...)

**Comment by chetstone** [comment]
Seems this is a problem with `react-native link`. I've used it to link many libraries but it doesn't seem to work with this library on a large existing project. For instructions on how to link manually for ios see [this comment](https://github.com/kmagiera/react-native-gesture-handler/issues/205#issuecomment-440592588)

**Comment by Mokkapps** [comment]
@chetstone this also solved the issue for me. I also had to remove the reference to the gesture handler from my Podfile and add some other 3rd party libs which I use to my build phase.

**Comment by rawadrifai** [comment]
is there a definitive solution for this? I'm somewhat new to rn, and it worked fine with expo but not with rn cli. I'm following the directions step by step. In xcode, I see the links properly added and everything. Still I get the error.

**Comment by astro5206771** [comment]
> this happens if you haven't installed RNGH properly. be sure to follow the steps from here: https://reactnavigation.org/docs/en/getting-started.html#installation

the native app load the bundle file has the the issue;but pure react-native app is ok;and i follow this step ,but the issue still exists;how to solve it ,pls;

**Comment by abdymm** [comment]
uninstall, and re run react-native run-ios/run-android

works for me

**Comment by jnasirur** [comment]
this error just for react-navigation
step 1:
npm install react-native-gesture-handler
npm install react-native-reanimated

step 2:
react-native link react-native-reanimated
react-native link react-native-gesture-handler

to finalize installation of react-native-gesture-handler for Android, be sure to make the necessary modifications to MainActivity.java:
import com.facebook.react.ReactActivity;
+ import com.facebook.react.ReactActivityDelegate;
+ import com.facebook.react.ReactRootView;
+ import com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView;

public class MainActivity extends ReactActivity {

  @Override
  protected String getMainComponentName() {
    return "Example";
  }

+  @Override
+  protected ReactActivityDelegate createReactActivityDelegate() {
+    return new ReactActivityDelegate(this, getMainComponentName()) {
+      @Override
+      protected ReactRootView createRootView() {
+       return new RNGestureHandlerEnabledRootView(MainActivity.this);
+      }
+    };
+  }
}
==================================
Finally, run react-native run-android or react-native run-ios to launch the app on your device/simulator.

**Comment by jnasirur** [comment]
> 
> 
> this error just for react-navigation
> step 1:
> npm install react-native-gesture-handler
> npm install react-native-reanimated
> 
> step 2:
> react-native link react-native-reanimated
> react-native link react-native-gesture-handler
> 
> to finalize installation of react-native-gesture-handler for Android, be sure to make the necessary modifications to MainActivity.java:
> 
> import com.facebook.react.ReactActivity;
> import com.facebook.react.ReactActivityDelegate;
> import com.facebook.react.ReactRootView;
> import com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView;
> 
> public class MainActivity extends ReactActivity {
> 
> Override
> protected String getMainComponentName() {
> return "Example";
> }
> # Override
> protected ReactActivityDelegate createReactActivityDelegate() {
> return new ReactActivityDelegate(this, getMainComponentName()) {
> Override
> protected ReactRootView createRootView() {
> return new RNGestureHandlerEnabledRootView(MainActivity.this);
> }
> };
> }
> }
> 
> Finally, run react-native run-android or react-native run-ios to launch the app on your device/simulator.

**Comment by williamhqs** [comment]
This saved my day!
```
cd ./ios
pod install
cd ..
```

**Comment by mjohns39** [comment]
For the monsoon of people that will spend hour(s) on this problem.  Make sure you also run `npm run ios` (`npm react-native run-ios`) after performing the steps [here](https://reactnavigation.org/docs/getting-started/).

You only have to do this once.  Afterwards, you can keep using `npm start`.
