### ISSUE TITLE
swipe DrawerNavigator not work correctly when drawerPosition is right

### ISSUE THREAD

**Issue by shemo14** [react-navigation/react-navigation#5647]
hi, 
I have problem when swipe drawer navigator when drawer position is right if I change drawer position to left it work well .

![ezgif com-crop 1](https://user-images.githubusercontent.com/12949790/53687262-503c3a80-3d3b-11e9-83d5-35b5f7115c65.gif)

in this gif in the above my problem when I swipe in the middle of screen the drawer opened so I can't control in my slider 

![ezgif com-crop](https://user-images.githubusercontent.com/12949790/53687325-0dc72d80-3d3c-11e9-9c02-b114961a1574.gif)

in this case it work well when I change  drawer position to left

this is my code 

```
import React from "react";
import { createStackNavigator, createAppContainer, createDrawerNavigator } from "react-navigation";
import Home from '../components/Home'
import Ads from '../components/Ads'


const DrawerNavigator = createDrawerNavigator({
   home: Home,
   ads: Ads,
},{
    drawerPosition: 'right',
});

const AppNavigator = createStackNavigator({
    drawerNavigator: {
        screen: DrawerNavigator,
        navigationOptions: {
            header: null
        }
    },
    ads: Ads
});

export default createAppContainer(AppNavigator);
```
```

"dependencies": {
    "expo": "^31.0.2",
    "react": "16.5.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz",
    "react-navigation": "^3.3.2"
  },
```

any help plz ??

**Comment by shemo14** [comment]
same [here](https://github.com/kmagiera/react-native-gesture-handler/issues/464)

**Comment by jpaas** [comment]
Is there a reason why this was closed? It seems that when the drawer is on the right side, on android, any swipe gesture anywhere on the screen starts to open the drawer. On iOS, you have to swipe from the edge of the screen. 

This causes the drawer to interfere with just about any touch interaction like button presses and list scrolls.

**Comment by jpaas** [comment]
Seems to be an issue with react-native-gesture-handler https://github.com/kmagiera/react-native-gesture-handler/issues/464
