### ISSUE TITLE
Two black screens with minimal TabNavigator example on fresh project

### ISSUE THREAD

**Issue by arapocket** [react-navigation/react-navigation#5651]
### Current Behavior

- I am trying to create a tab navigator on a blank project on iOS, following the [minimal example](https://reactnavigation.org/docs/en/tab-based-navigation.html)

On iOS I get two black screens for each tab. On Android it's working fine.

### Expected Behavior

- I should see two white screens, one with the text "Home!" displayed and one with "Settings!" displayed

### How to reproduce

Create an empty project with react-navigation installed and attempt to create a TabNavigator using the minimal example in the documentation.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.3.2
| react-native     | 0.58.6
| node             | 10.15.1
| npm or yarn      | npm 6.4.1

**Comment by arapocket** [comment]
To fix this make sure the app container component is not wrapped with view tags

**Comment by napalm272** [comment]
Can someone explain to me why this is the case? Why can't I wrap app container in a <View>?

**Comment by brentvatne** [comment]
i don't understand the question. i copy and pasted the example from the tab navigation docs into snack and i do not get two blank screens: https://snack.expo.io/@notbrent/playful-truffles

please create a new issue with an actual minimal reproducible example, thanks!

**Comment by napalm272** [comment]
Please see code sample above, the change is on the last 2 lines
```
import React from 'react';
import { Text, View } from 'react-native';
import { createBottomTabNavigator, createAppContainer } from 'react-navigation';

class HomeScreen extends React.Component {
  render() {
    return (
      <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
        <Text>Home!</Text>
      </View>
    );
  }
}

class SettingsScreen extends React.Component {
  render() {
    return (
      <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
        <Text>Settings!</Text>
      </View>
    );
  }
}

const TabNavigator = createBottomTabNavigator({
  Home: HomeScreen,
  Settings: SettingsScreen,
});

const Wrapper = createAppContainer(TabNavigator)
export default ()=><View><Wrapper/></View>;
```

**Comment by napalm272** [comment]
After wrapping the app container in a view, I just see a blank screen. @brentvatne

**Comment by brentvatne** [comment]
`<View style={{flex: 1}}>`

**Comment by napalm272** [comment]
Thanks! I think a good place is https://reactnavigation.org/docs/en/common-mistakes.html

**Comment by brentvatne** [comment]
@napalm272 - interesting! can you open a pr to add it?
