### ISSUE TITLE
Which version to use with RN 0.53.3 ?

### ISSUE THREAD

**Issue by philjoseph** [react-navigation/react-navigation#5654]
we have a RN app (created with `react-native init`) that is currently on 0.53.3.

We've tried to use the library and hit this issue from react-native-gesture-handler:  https://github.com/kmagiera/react-native-gesture-handler/issues/343

Does this mean we need to use a non latest release of react-native-gesture-handler or of react-navigation ? I do not see any documentation on that topic right now.

**Comment by philjoseph** [comment]
I see that the issue occured since release 1.0.16 of RNGH, so can we use RNGH v1.0.15 with react-navigation latest release ?

**Comment by brentvatne** [comment]
hello! first, i would recommend updating to react-native 0.58. if that isn't possible, then you will have to go back to react-navigation@~2.18.3
