### ISSUE TITLE
Custom Android back button behavior

### ISSUE THREAD

**Issue by onitzschke** [react-navigation/react-navigation#5657]
## Current Behavior
The code from https://reactnavigation.org/docs/en/custom-android-back-button-handling.html
is not working properly with v3.3.2

## Expected Behavior
I have a StackNavigator inside a drawer that contains 4 screens and i want to handle the backbutton to show a dialog in the 3 screen. The problem is that if i'm press the backbutton on screen 2 the backbutton not working if screen 3 was mounted and the code from the exmaple above was executed.

## How to reproduce
https://snack.expo.io/HkxEVDhUV
Open the Snack, Navigate to screenC, screenD is open from screenC if componentDidMount.
Bo back to screenC and press the back button on screenC, press ok on the dialog and try to press the back button on screenB. This is not working.

```
  React Native Environment Info:
    System:
      OS: macOS 10.14.3
      CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
      Memory: 130.34 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.6.0 - /usr/local/bin/node
      Yarn: 1.7.0 - /usr/local/bin/yarn
      npm: 6.8.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 18, 23, 25, 26, 27, 28
        Build Tools: 19.1.0, 20.0.0, 21.1.2, 22.0.1, 23.0.1, 23.0.2, 23.0.3, 24.0.0, 24.0.1, 24.0.2, 24.0.3, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.0, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.1, 27.0.2, 27.0.3, 28.0.0, 28.0.0, 28.0.0, 28.0.1, 28.0.2, 28.0.3
        System Images: android-21 | Intel x86 Atom, android-21 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom_64, android-25 | Google APIs ARM EABI v7a, android-27 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom_64
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5264788
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: ^0.58.5 => 0.58.5 
    npmGlobalPackages:
      create-react-native-app: 2.0.2
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
```

**Comment by onitzschke** [comment]
I think this problem is react-native-paper related.

**Comment by brentvatne** [comment]
@onitzschke - yeah i agree, i was just investigating and found that on that on screen B a back handler is being removed/re-added everytime you hit the back button, and that comes from react-native-paper's modal

**Comment by onitzschke** [comment]
With a callback from setState to set the visible state of the Dialog the issue was fixed. Thanks for the great work on this project^^

**Comment by brentvatne** [comment]
cc @satya164 - this might be an interesting one for you

**Comment by onitzschke** [comment]
Remove the hardwareBackPress listener if Modal will unmount might be the solution.
