### ISSUE TITLE
java.nio.file.AccessDeniedException: node_modules_reactnavigationstack_dist_views_assets_backicon.png

### ISSUE THREAD

**Issue by octopusbaba** [react-navigation/react-navigation#5658]
On trying to create release apk from my react native app. I am getting this following error:

Caused by: org.gradle.api.UncheckedIOException: 
java.nio.file.AccessDeniedException: 

/User/TestApp/android/app/build/intermediates/res/merged/release
/drawable-hdpi
/**node_modules_reactnavigationstack_dist_views_assets_backicon.png**

Debug apk , builds fine. But I'm stuck in making release apk.

reactnavigationstack_dist_views_assets_backicon : I cannot figure out this back icon issue.

**Comment by harshrajk** [comment]
Hey, how did you manage to resolve this issue ?

**Comment by octopusbaba** [comment]
@harshrajk ... I had same library installed twice so... I rechecked those files and npm install again...
and it was solved. Hope it helps.
