### ISSUE TITLE
Jest issue

### ISSUE THREAD

**Issue by mehranabi** [react-navigation/react-navigation#5662]
Hi!
I've created a simple RN project and installed `react-navigation` (you can check it on Github: https://github.com/mehranabi/rn-gh-error).
I've added the mock to fix `react-native-gesture-handler` which is mentioned in https://github.com/react-navigation/react-navigation/issues/5264 and https://github.com/kmagiera/react-native-gesture-handler/issues/344

But now, when I run the test in project, I get this error:
```
D:\Mehran\Projects\ReactNative\RNGestureHandlerError\node_modules\@react-navigation\native\dist\withOrientation.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import React from 'react';
                                                                                                    ^^^^^

    SyntaxError: Unexpected identifier

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/ScriptTransformer.js:440:17)
      at Object.get withOrientation [as withOrientation] (node_modules/@react-navigation/native/dist/index.js:17:12)
      at Object.<anonymous> (node_modules/react-navigation-stack/dist/views/Header/Header.js:538:16)
```
And I think it's related to `react-navigation`

**Comment by brentvatne** [comment]
the error that you are seeing is because jest does not automatically transpile dependencies in node modules, this is documented in the jest react-native website: https://jestjs.io/docs/en/tutorial-react-native#transformignorepatterns-customization

for example with expo our default transformIgnorePatterns looks like this: https://github.com/expo/expo/blob/efd52c55d552812b605620da56b47d1b26ce59f8/packages/jest-expo/jest-preset.json#L24-L26

**Comment by mehranabi** [comment]
@brentvatne 
Take a look at package.json... I did just what you said in react-navigation documentation...

**Comment by brentvatne** [comment]
where do we talk about jest in react-navigation docs?

**Comment by brentvatne** [comment]
from another thread: you might want to use something like this in your jest config:
- https://github.com/expo/expo/blob/7c30288bebb64ae3086b3a00f151c5982cd9fbc6/packages/jest-expo/jest-preset.json#L24-L26

and mock react-native-gesture-handler like this:
- https://github.com/expo/expo/blob/7c30288bebb64ae3086b3a00f151c5982cd9fbc6/packages/jest-expo/src/preset/setup.js#L167-L199

**Comment by mehranabi** [comment]
Hello @brentvatne , Thanks for sharing useful links... I've solved my problem...
Here's the part that you talked about Redux Integration and also talked about moking tests in jest:
https://reactnavigation.org/docs/en/redux-integration.html#mocking-tests
