### ISSUE TITLE
Animate stack navigator's background colour when navigating between screens

### ISSUE THREAD

**Issue by rhysforyou** [react-navigation/react-navigation#5666]
Currently when transitioning between two screens with different `backgroundColor`s provided in `headerStyle`, the app abruptly changes the colour with no animation. Ideally the header would be able to smoothly animate between these too colours to make this less jarring. Is there any way to achieve this?

**Comment by brentvatne** [comment]
this example shows how to use `headerBackgroundTransitionPreset` - https://github.com/react-navigation/react-navigation-stack/blob/master/example/src/HeaderBackgrounds.js

note that you need to use the `headerBackground` navigation option for this

**Comment by brentvatne** [comment]
more on those things in docs: https://reactnavigation.org/docs/en/stack-navigator.html#headerbackground

**Comment by rhysforyou** [comment]
That worked perfectly, thanks!
