### ISSUE TITLE
How to pass parameters to a TabNavigator React Native

### ISSUE THREAD

**Issue by GabrielaVillaAngeles** [react-navigation/react-navigation#5667]
## How to pass parameters to a TabNavigator React Native
How can I pass data from a screen and that in my screens that make up my TabNavigator I can access the parameter: I send the parameter from Login:

> <TouchableOpacity onPress={() => this.props.navigation.navigate('Invitado',{ IDNombre: 'Invitado'})} style={styles.buttonCerrar}></TouchableOpacity> 

and I need to receive it and send it to each of my views

>   const RootStack = createBottomTabNavigator(
                {
                    Home: {
                        screen: Servicios, 
                    },
                    History: {
                        screen: Historial,
                    },
                    Perfil: {
                        screen: Perfil, 

                    },

                },
            {
                defaultNavigationOptions: ({ navigation }) => ({
                    tabBarIcon: ({ focused, tintColor }) =>
                        getTabBarIcon(navigation, focused, tintColor),

                }),
                tabBarOptions: {
                    showLabel: false,
                    activeTintColor: '#63286A',
                    inactiveTintColor: 'gray',
                },
            },

            );

## Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^3.0.9
| react-native     | 16.5.0
| node             |
| npm or yarn      | yarn

**Comment by brentvatne** [comment]
this params are passed to the route that you navigate to, in this case it would be the tab route, and not one of the screens in the route. if from one of those screens you want to get the params that are passed to the tab navigator, you can do this:

```js
this.props.navigation.dangerouslyGetParent().getParam('paramNameHere')
```

**Comment by sekune** [comment]
llr

**Comment by EhsanSarshar** [comment]
@brentvatne what if I want the param in tab bar itself

**Comment by peyman-hakemi** [comment]
@brentvatne do you find any solution?

**Comment by geisonmcd** [comment]
I managed to get it working using the "Passing params to a screen in a nested navigator" part of the documentation in the react native docs.

```
navigation.navigate('Root', {
  screen: 'Settings',
  params: {
    screen: 'Sound',
    params: {
      screen: 'Media',
    },
  },
});
```

**Comment by yashSrathore** [comment]
any params passed to a screen in a nested navigator are in the route prop of that screen and aren't accessible from a screen in a parent or child navigator.

If you need to access params of the parent screen from a child screen, you can use React Context to expose params to children.
