### ISSUE TITLE
can't run android simulator after installing react-navigation

### ISSUE THREAD

**Issue by man-of-sbk** [react-navigation/react-navigation#5668]
Hi guys, i have just installed react navigation and found out that if u want to run your project  after doing all installation steps, u guys need to check out the settings.gradle then change all <b>backslashes ( \ )</b> to <b style="font-size:bold">forward slash ( / )</b> so that your project should work well.

p/s: i've just found this and want to share this to people who can't figure out what the hell is going on with their installation :)

**Comment by brentvatne** [comment]
hello! i'm not sure this applies to react-navigation specifically because we don't have any settings.gradle file. one library that we depend on (react-native-gesture-handler) does. seems related to https://github.com/kmagiera/react-native-gesture-handler/issues/436

**Comment by man-of-sbk** [comment]
oh, yes, that's it :))
