### ISSUE TITLE
toggle tabBarVisible using setParams?

### ISSUE THREAD

**Issue by rakibtg** [react-navigation/react-navigation#5671]
I need to toggle the `BottomTabNavigator` from a method in component!
I'm confused while reading the docs, https://reactnavigation.org/docs/en/navigation-options-resolution.html .. or is it a feature that you cant use `tabBarVisible` with `setParams` but you can do that only for header!?

### Current Behavior
This is my imaginary `navigationOptions` for one of many screen components:
```javascript
  static navigationOptions = ({ navigation }) => {
    const { state } = navigation
    return {
      title: state.params ? state.params.title : 'loading...',
      header: state.params && state.params.headerVisible,
      tabBarOptions: {
        tabBarVisible: state.params ? state.params.tabBarVisible : true,
      },
    }
  }
```
I wanted to toggle both the header and the bottom tab navigator with this method:
```javascript
  toggleHeaderAndNav() {
    const { setParams } = this.props.navigation
    setParams({
      headerVisible: null, // intentionally set to null to see if it hides the header when it sets the header value to null; Yes it does hide the header.
      title: 'i changed tho', // intentionally changing the title to see if it works for header; It changes the title!
      tabBarVisible: false, // intentionally set to false to hide the tabBar; Intentional API changes won't let me do that!?
    })
  }
```
Currently, it hides the header and changed the title on `componentDidMount`, but will not hide the tab bar in the bottom.

### Expected Behavior
In this beautiful earth i wanted to hide the bottom tab bar as i can hide the header using `setParams` (see example above)

### How to reproduce
https://snack.expo.io/@rakibtg/excited-candy ( take a look at the `PhotoScreen.js` )

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | "^3.0.9"
| react-native     | "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz"
| node             | 11.20
| npm or yarn      | yarn

**Comment by lpaz010** [comment]
anyone help me too, I came to the following conclusions in my test.
 _`tabBarVisible` only works for  StackNavigator, not BottomTabNavigator._

**Comment by eriveltonelias** [comment]
Hi there,

you can do something like that to change the `tabBarVisible` https://snack.expo.io/@eriveltonelias/tab-bar-visible-v3
