### ISSUE TITLE
Using react-navigation 3 creates an object instead of a valid component

### ISSUE THREAD

**Issue by nschurmann** [react-navigation/react-navigation#5672]
### Current Behavior

This function code creates a component inside a createDrawerNavigator function, i also use createAppContainer function, but for some reason when I use JSX it will return an object and the app will complain
```
const createTesterMenuNavigation = (
  youtubeApikey: string,
  noExternalLinks: boolean,
  App: any
) => {
  const TesterMenuNavigator = createAppContainer(
    createDrawerNavigator(
      {
        App: {
          screen: () => <View><Text>nathoehtnoa</Text></View>
        },
      },
      {
        drawerWidth: TESTER_MENU_WIDTH,
        drawerPosition: 'right',
        contentComponent: TesterMenu,
      }
    )
  );

  return <TesterMenuNavigator />;
};
```

It might be the version of react-navigation?

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.3.2
| react-native     | 0.51.0
| node             | 6.11.1
| npm or yarn      | npm 6.4.1

![Screen Shot 2019-03-11 at 9 43 19 AM](https://user-images.githubusercontent.com/5099344/54091204-24c3ea80-43e2-11e9-8edb-fc62da3124f0.png)

**Comment by brentvatne** [comment]
i think you meant to do `return TesterMenuNavigator;` - the jsx version does indeed return an object and not a component
