### ISSUE TITLE
Animated Modal right above bottom tabs

### ISSUE THREAD

**Issue by EddieEJ** [react-navigation/react-navigation#5675]
I have been following a [tutorial][1] to create a React Context Provider through which I can have a general panel across all tabs and panels of my React Native app. [Complete Expo Snack of the code here.][2]

This "general panel"(`VideoModal.js`) has a [PanGestureHandler][3] which on the event of scroll down (on the Y axis) would trigger Animations to resize the panel into a small modal somewhere on the bottom part of the screen. (similar to YouTube, SoundCloud, Spotify and Apple Music players). Animations look like this:

    // minimum height of the modal after animation has finished
    const minHeight = 64;
    // Position at which height of screen will shrink completely
    const midBound = height - 64 * 3;
    const upperBound = midBound + minHeight;

    const containerHeight = interpolate(translateY, {
          inputRange: [0, midBound],
          // height is taken from Dimensions, basically screen height
          outputRange: [height, 0],
          extrapolate: Extrapolate.CLAMP,
        });
    const videoWidth = interpolate(translateY, {
          inputRange: [0, midBound, upperBound],
          outputRange: [width, width - 16, PLACEHOLDER_WIDTH],
          extrapolate: Extrapolate.CLAMP,
        });
    const videoHeight = interpolate(translateY, {
          inputRange: [0, midBound],
          outputRange: [width / 1.78, minHeight * 1.3],
          extrapolate: Extrapolate.CLAMP,
        });
([Full code available to test on emulators from Expo Snack][2]) 

My problem is that I do not know how to place the modal right above my bottom tabs regardless of the screen size or OS (iOS/Android). 

In [this Github issue][4] I have found out that tabs would have a height of either `49` or `29`. I have been trying to experiment with those values such as:

    const midBound = height - 49 * 1/2/3;

But the modal would never be on the desired position. Sometimes it would overlap with the bottom tabs (iPhone X, XS, XR), sometimes it would be too far away from them (iPhone 6,7,8). I never seem to make it fit perfectly right above the tabs with no space between those two.

Any help regarding this would be greatly appreciated.

  [1]: https://www.youtube.com/watch?v=eLjzIM_4zlg
  [2]: https://snack.expo.io/@eddyj/aHR0cH
  [3]: https://kmagiera.github.io/react-native-gesture-handler/docs/handler-pan.html
  [4]: https://github.com/react-navigation/react-navigation-tabs/issues/97

**Comment by eriveltonelias** [comment]
hi there! this issue tracker is reserved for bugs only. your post seems to be a usage question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help. thanks!
