### ISSUE TITLE
NavigationEvents onDidBlur   not fire and when the first time enter the page or swipe back

### ISSUE THREAD

**Issue by xiongcaichang** [react-navigation/react-navigation#5676]
### Current Behavior

addListener   'didFocus' not fire with the first time enter the page
NavigationEvents onDidBlur   not fire and when the first time enter the page or swipe back

note: simulater is normal but on real device iPhoneX is not fired
### Expected Behavior

fire normal

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |2.6.2
| react-native     |0.55.3
| node             |v10.8.0
| npm or yarn      |1.12.3

**Comment by eriveltonelias** [comment]
duplicate of https://github.com/react-navigation/react-navigation/issues/5669
