### ISSUE TITLE
Delay updating navigation bar and tab bar icons/text after transitioning in a nested navigator scenario

### ISSUE THREAD

**Issue by sinewave440hz** [react-navigation/react-navigation#5677]
### Current Behavior

I am working on a music creation app with a non-typical interface that nonetheless needs some standard navigation transitions. I have created a drawer navigator inside a stack navigator. That stack navigator is the initial screen of a bottom tab navigator.   

The drawer navigator maintains the header navigation options, changing the title depending on whether the drawer is open or closed. Similarly, the bottom tab navigator changes it's icon when the drawer is open or closed - although this uses the rather unpleasant `navigation.state.routes[navigation.state.index].isDrawerOpen` to achieve this.

### Expected Behavior

- The above gives me the changes I am after, but the problem is that the delay is unacceptable. I have seen other issues referring to a similar problem, but I haven't really understood from those 1) whether or not this is a bug or 2) what a viable alternative approach would be.

![ezgif com-video-to-gif-5](https://user-images.githubusercontent.com/7300069/54264678-ec541600-4573-11e9-83f1-803c6c89c1ee.gif)

### How to reproduce

- `react-native init delayTest`
- `yarn add react-navigation react-native-vector-icons react-native-gesture-handler react-native-vector-icons`
- `react-native link react-native-vector-icons`
- `react-native link react-native-gesture-handler`

Change app.js to: 
```
import * as React from 'react';
import { Text, TouchableOpacity } from 'react-native';
import { createAppContainer, createBottomTabNavigator, createDrawerNavigator, createStackNavigator, DrawerItems } from 'react-navigation';
import Home from './Home';
import Icon from 'react-native-vector-icons/MaterialIcons';

const drawer = createDrawerNavigator(
  {
    Home: {
      screen: Home,
      params: {
        title: 'Home'
      }
     }
  },
  {
    initialRouteName: 'Home'
  }
);

const MenuBtn = (navigation) => (<TouchableOpacity onPress={() => navigation.toggleDrawer()}>
<Text>Menu</Text>
</TouchableOpacity>);

const homeStack = createStackNavigator(
  {
    Drawer: {
      screen: drawer,
      navigationOptions: ({ navigation}) => {
        return {
          headerTitle: navigation.state.isDrawerOpen ? 'Choose...' : 'Main',
          headerLeft: MenuBtn(navigation)
        }
      }
    }
  },
  {
    initialRouteName: 'Drawer'
  }
);

const tabNav = createBottomTabNavigator(
  {
    Home: homeStack
  },
  {
    defaultNavigationOptions: ({ navigation }) => {
      const { routeName } = navigation.state;
      return {
        tabBarIcon: () => {
          let iconName;
          let color = '#000000';
          let size = 40;
          switch (routeName) {
            case 'Home': {
              iconName = navigation.state.routes[navigation.state.index].isDrawerOpen ?
              'info' :
              'play-arrow';
              break;
            }
            default: iconName = 'play-arrow';
          }
          return <Icon name={iconName} size={size} color={color}/>;
        }
      }
    },
    initialRouteName: 'Home',
    tabBarOptions: {
      showLabel: false
    }
  }
)

const AppContainer = createAppContainer(tabNav);

export default class Index extends React.Component {
  render() {
    return <AppContainer />;
  }
}

```
### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.3.2
| react-native     | 0.59.0
| node             |  10.13.0
| npm or yarn      | yarn

Thanks.

**Comment by brentvatne** [comment]
hi! see the discussion here: https://github.com/react-navigation/react-navigation/issues/5318
