### ISSUE TITLE
Component in TabNavigator load twice

### ISSUE THREAD

**Issue by ttdat89** [react-navigation/react-navigation#5678]
### Current Behavior

```
export const AppNavigator = createStackNavigator({
  SignUpScreen: SignUpScreen,
  MainTab: MainTab,
}, {
  headerMode: 'none'
})

const MainTab = createBottomTabNavigator({
  HomeScreen: HomeScreen
})
```
`HomeScreen` component load twice (`componentDidMount` call twice)

this issue happened again https://github.com/react-navigation/react-navigation/issues/476
### Expected Behavior

`HomeScreen` load once

### How to reproduce

In SignUpScreen component, `this.props.navigation.navigate("MainTab")`

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.3.2
| react-native     | 0.58.6
| node             | 11.6.0
| npm or yarn      | 1.13.0

**Comment by brentvatne** [comment]
not reproducible: https://snack.expo.io/@notbrent/graceful-bacon

if you provide an example on snack to reproduce and create a new issue i'd be happy to look!

**Comment by ttdat89** [comment]
Sorry, I just check it again. It works if the screen is not connected to redux, otherwise HomeScreen will be load twice if it's connected to redux store
