### ISSUE TITLE
Hot Reload Bug (noticed when trying the v3)

### ISSUE THREAD

**Issue by AsadSaleh** [react-navigation/react-navigation#5679]
### Current Behavior
With hot reloading turned on, my app refresh to the first screen when I create change on another screen.

### Expected Behavior
I expect my app to do hot reload as it should by staying at the current screen, not refreshing to the first screen.

### How to reproduce

I'm running freshly installed "react-native init" project. After that, I added react-navigation carefully according to the docs. I also follow the "getting started" guide until we create 2 simple screens. After that I turn on Hot Reloading and then test it by changing some text to see the hot reload.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | "^3.3.2"
| react-native     | "0.59.0"
| node             | v10.13.0
| npm or yarn      | yarn

**Comment by brentvatne** [comment]
sounds like you're using live reload.

you can use this too: https://reactnavigation.org/docs/en/state-persistence.html#usage

**Comment by zlv-thisF** [comment]
same problem here, react-native 0.59.4 , use hooks.
if app is FC, hot reload not work (page not refresh);
if app is Class based component, hot reload works in a strange way :  back to initial screen( behaviour very much like live reload ), but in fact, i disabled live reload and only turn on 'hot reload',.

**Comment by MarianBe** [comment]
Having the same issue with hooks

**Comment by faxioman** [comment]
@brentvatne, why this issue is closed? This bug is still present.

**Comment by whitestonedata** [comment]
I resolved this by wrapping the navigation components in a class based component.

https://stackoverflow.com/questions/60511183/react-native-cli-project-how-to-fix-hot-reload-when-using-react-navigation?noredirect=1#comment107050205_60511183

**Comment by whitestonedata** [comment]
Reload seem to work ok here now after I wrapped the navigation components inside a class based component.

https://stackoverflow.com/questions/60511183/react-native-cli-project-how-to-fix-hot-reload-when-using-react-navigation?noredirect=1#comment107050205_60511183
