### ISSUE TITLE
AppContainer ref is null when using a SwitchNavigator and the NavigationService pattern

### ISSUE THREAD

**Issue by mreda7** [react-navigation/react-navigation#5685]
### Current Behavior

- When using an appContainer that include a SwitchNavigator , the loading screen in the switch Navigator is mounted before that the ref of the appContainer Is set , so I can't navigate until I have this ref : 
`    <AppNavigator
      ref={navigatorRef => {
        NavigationService.setTopLevelNavigator(navigatorRef);
      }}
    />`

`const AppNavigator = createSwitchNavigator(
  {
    AuthLoading: AuthLoadingScreen,
    Login:  LoginNavigator,
    MAIN: MainNavigator,
  },
  {
    initialRouteName: routeNames.REFRESH_SCREEN,
  },
);`

The same behavior was already mentioned in this [comment](https://github.com/react-navigation/react-navigation/issues/4490#issuecomment-405774241) 

### Expected Behavior

- AppContainer ref should not be null

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.3.2
| react-native     | 0.58.4
| node             | 8.9.4
| yarn      | 1.13.0

**Comment by matthamil** [comment]
Hello! Thanks for the issue. Can you create a reproducible example in either a repo or [Snack](https://snack.expo.io/)? Thanks!

**Comment by mreda7** [comment]
Thank you for your fast reply @matthamil , here is a [Snack](https://snack.expo.io/@mreda/awkward-apple)

**Comment by eriveltonelias** [comment]
Hi @mreda7, 

just verify if `_navitor` is not null before you use it, something like this will solve the problem 
```js
_navigator &&  _navigator.dispatch(...
```

check this snack: https://snack.expo.io/@eriveltonelias/navigation-actions-appcontainer

**Comment by mreda7** [comment]
Hi @eriveltonelias 
Yes the app won't crash, but this means that we can't navigate automatically either .
A solution will be to cache the actions while the navigator is null ,and execute them when it is no more null.but this mean that we should take in account that the actions could be ( navigate, push , replace ...) .
So it is not easier to have navigator initialized before that the switchNavigator mount the AuthLoadingScreen ?

**Comment by brentvatne** [comment]
you will need to save away the action until the navigator is available and then dispatch it. it'd be nice to have an automated way to do this but it doesn't exist yet

**Comment by keeth** [comment]
anyone got a working solution for this they could share?

**Comment by keeth** [comment]
here's what i've got.. still testing it but you get the idea.  using this to navigate when a push notification is tapped.

uses https://www.npmjs.com/package/retry

actual routing happens in handleNotification(), not shown here.

```
import retry from 'retry';

...

// Inside App render function

const navigator = useRef(null);
useEffect(() => {
  const subscription = Notifications.addListener(notification => {
    const operation = retry.operation({ retries: 5, minTimeout: 100 });
    operation.attempt(() => {
      if (!navigator.current) {
        if (!operation.retry(new Error('Missing navigator ref'))) {
          // give up, report error
          captureException(operation.mainError());
        }
        return;
      }
      handleNotification(notification, navigator.current);
    });
  });
  return () => subscription.remove();
}, []);

```

**Comment by nobuti** [comment]
We are talking about a pattern that is documented in the documentation: https://reactnavigation.org/docs/en/navigating-without-navigation-prop.html. How is this issue closed? Does it make sense that the reference be null?

**Comment by matthamil** [comment]
@nobuti can you open a new issue if you're experiencing a problem?

**Comment by opoze** [comment]
Im getting this error too. Its occurs when using reactHook useEffect() with second parameter as an empty array, meaning componentDidMount.
When wee change the stack, AppContainer is rendered again. (Don't know if its only with SwitchNavigator).
AppContainer ref property receives a callback to set navigator that wee don't know wen it will run.  But the children component useEffect() already ran because the component are mounted getting an undefined navigator.
It's why the setTimeOut suggested by @keeth works. 
In my case I'm making a call to NavigationService.setTopLevelNavigator(navigatorRef) on useEffect() as a workaround, but it's exhaustive.
In fact the "navigating without props" on docs are to be used outside a component with props. But in this case wee will always have two main sources to navigate an its frustrating.

**Comment by matthamil** [comment]
@opoze Can you open a new issue?
