### ISSUE TITLE
Cannot read property 'Direction' of undefined

### ISSUE THREAD

**Issue by optimatex** [react-navigation/react-navigation#5687]
### Current Behavior

I have the simples app with these lines:
```
import React from 'react';
import { View, Text } from 'react-native';
import { createStackNavigator, createAppContainer } from 'react-navigation';

export default class App extends React.Component {
  render() {
    return (
      <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
        <Text style={{ color: '#fff' }}>Home Screen 433</Text>
      </View>
    );
  }
}

const AppNavigator = createStackNavigator({
  Home: HomeScreen,
});

export default HomeScreen;
```

as you can see I even do not export the AppNavigator.  
but doing so 
```
const AppNavigator = createStackNavigator({
  Home: HomeScreen,
});
``` 
i got this error 
```
Requiring module "index.js", which threw an exception: TypeError: Cannot read property 'Direction' of undefined

moduleThrewError
    require.js:373:9
loadModuleImplementation
    require.js:274:10
guardedLoadModule
    require.js:199:20
metroRequire
    require.js:127:6
metroRequire.a.name.e.$reactNative.r
    <unknown file>:0
i
    <unknown file>:0
Object.setupDevtools
    <unknown file>:0
c
    <unknown file>:0
```

### Expected Behavior

- What do you expect should be happening?
- Include a screenshot if it makes sense.

work without exceptions

### How to reproduce

react-native run-ios

### Your Environment

| software   IOs      | version 10.14.2
| ---------------- | -------
| react-navigation | "3.0.0",
| react-native     | . "0.58.6"
| node          | .  10.13.0   
| npm or yarn      | .  yarn 1.13.0

**Comment by brentvatne** [comment]
you need to install react-native-gesture-handler properly as per the instructions in the docs https://reactnavigation.org/docs/en/getting-started.html

**Comment by optimatex** [comment]
@brentvatne I did it exactly as in the docs, but got the same. Before that, I also removed all packages and reinstall.

**Comment by brentvatne** [comment]
if you can share a reproducible example (a full project that i can clone and run and verify this) i can help you. i can assure you though it's not an issue with the library but with the configuration :)

**Comment by optimatex** [comment]
@brentvatne thanks. here is the repo https://github.com/optimatex/exvi

**Comment by brentvatne** [comment]
oh you are using haul - i have no idea how this might complicate things

**Comment by optimatex** [comment]
@brentvatne just made some small test, installing new repo with react native and haul and then add react-navigation there. Everything works fine. Probably that is because of xcode settings

**Comment by brentvatne** [comment]
gotcha, ok i'll let you figure that one out then as we don't provide support for such issues in this repo (or we'd have no time for anything else 😅)

**Comment by cassiossantos** [comment]
I had the same problem, try all the steps of the above issues but did not solve. Then, I followed the steps of installing the react navigation, including adding the code in java. Then I uninstall the old app from the emulator and install again with run react-native

**Comment by odeke** [comment]
I had to run the link command to get it to work.
`react-native link react-native-gesture-handler`

**Comment by RedTurk** [comment]
It worked for me too! I need to make all the settings on the page below. Then, you need to delete your Emulator application, restart the Emulator and get build again. You don't forgetting MainActivity.java options for Android . Page [ https://reactnavigation.org/docs/en/getting-started.html ].

**Comment by oscar-gallog** [comment]
The same problem, none of the solutions worked for me.

**Comment by Laassari** [comment]
I had the same problem on react-native 0.60.4 and solved by using [jetifier](https://github.com/mikehardy/jetifier)

**Comment by Joepus** [comment]
Had same problem. In RN 0.60 do not link manually. There is auto-linking. Actually unlink if you have linked (as suggested by manual). After unlinking it worked for me.

**Comment by mrigo** [comment]
Have same problem. Neither @Laassari or @Joepus solutions worked for me...
Any alternative?
I use react-native 0.60.0

Thanks

**Comment by TranVanThaiSon** [comment]
react-native link is my solution

**Comment by mrded** [comment]
Have you tried to update `react-native-gesture-handler`? They have different versions to match `react-native` version.

**Comment by briansage** [comment]
I got this error to go away by following @ilmatic 's [comment](https://github.com/react-navigation/react-navigation/issues/6071#issuecomment-513091678) over in issue #6071

> Hopefully this can be helpful for people running into the same thing: nothing in the above thread helped for me (working on iOS Simulator), the solve was adding this line to `ios/Podfile`:
> 
> `pod 'RNGestureHandler', :podspec => '../node_modules/react-native-gesture-handler/RNGestureHandler.podspec'`
>
> followed by running `pod install`

**Comment by tridungle** [comment]
> I had same issue in ios. I did not install pod and that was missing.
> follow these steps if you have not install pod yet:
> 
> cd ios
> pod install
> cd ..
> 
> now link:
> 
> react-native link react-native-reanimated
> react-native link react-native-gesture-handler
> 
> that should be it

just cd ios && pod install and it work fine. thank you!

**Comment by ntrjpatel** [comment]
Great!, It seems all installation done as per the doc, but still facing issue.
I just removed app from emulator, restarted emulator, and started npm server and everything works like a charm.

Thanks!

**Comment by matteocollina** [comment]
> I had same issue in ios. I did not install pod and that was missing.
> follow these steps if you have not install pod yet:
You should invert link phase with pod install
> cd ios
> pod install
> cd ..
> 
> now link:
> 
> react-native link react-native-reanimated
> react-native link react-native-gesture-handler
> 
> that should be it

**Comment by huangxiaojingCN** [comment]
I had same issue on Android, And IOS done.

![image](https://user-images.githubusercontent.com/20080084/75951350-bcb9be80-5ee6-11ea-9530-612a4efafe62.png)

## Current Behavior

Here are AppNavigators.js

```
import 'react-native-gesture-handler';
import React from 'react';
import {NavigationContainer} from '@react-navigation/native';
import {createStackNavigator} from '@react-navigation/stack';

import HomePage from '../pages/HomePage';

const HomeStack = createStackNavigator();

function Home() {
    return (
        <NavigationContainer>
            <HomeStack.Navigator>
                <HomeStack.Screen
                    name="Home"
                    component={HomePage}
                />
            </HomeStack.Navigator>
        </NavigationContainer>
    );
}

export default Home;
```
Here are  index.js

```
import {AppRegistry} from 'react-native';
//import App from './App';
import AppNavigators from './js/navigator/AppNavigators'
import {name as appName} from './app.json';

AppRegistry.registerComponent(appName, () => AppNavigators);

```

I got a error: 

> ExceptionsManager.js:44 TypeError: Cannot read property 'Direction' of undefined
> Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)

### Environment
|Software|Version|
|----|----|
|node|v12.16.1|
|react-native|0.61.5|
|react-native-gesture-handler|^1.6.0|
|react-native-reanimated|^1.7.0|
|react-native-safe-area-context|^0.7.3|
|react-native-screens|^2.2.0|

**Comment by dnsmob** [comment]
@huangxiaojingCN -- the `link` might have not worked for the android. but basically, that's what you need doing. i dont `link` my projects, i wire stuff in my java code (proper hybrid app) but it worked right after i added the correct _packages_ to the android project (if you're familiar with it):
```
...
new RNGestureHandlerPackage(),
new ReanimatedPackage()
```

**Comment by garbo-a** [comment]
For me I had to add both
`pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'
  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler/'`
to the /ios/Podfile

**Comment by hend-elsahli** [comment]
> watchman watch-del-all worked for me

**Comment by kravtsovnet** [comment]
Having the same problem.

Tried installing/uninstalling gesture handler, clearing cache, removing node_modules, linking/unlinking, pod install. Getting error with just:

import 'react-native-gesture-handler';
import * as React from 'react';

export default function App() {
  return null;
}

**Comment by melliston** [comment]
> Having the same problem.
> 
> Tried installing/uninstalling gesture handler, clearing cache, removing node_modules, linking/unlinking, pod install. Getting error with just:
> 
> import 'react-native-gesture-handler';
> import * as React from 'react';
> 
> export default function App() {
> return null;
> }

Also seeing the same issue. I cant find a solid fix for this. All i did was copy the documentation as stated like you kravtovnet.

**Comment by raajnadar** [comment]
You need to make changes in java file for react native gesture handler to work.

https://software-mansion.github.io/react-native-gesture-handler/docs/getting-started.html#android

**Comment by rahulaggarwal11** [comment]
You just need to reinstall your node packages and reinstall your app using this command-
`npx react-native run-android`

**Comment by anasbalkhadir** [comment]
> You need to make changes in java file for react native gesture handler to work.
> 
> https://software-mansion.github.io/react-native-gesture-handler/docs/getting-started.html#android

It works for me

**Comment by Rolando-Barbella** [comment]
@anasbalkhadir broken link now
