### ISSUE TITLE
What do you mean 'TypeScript type definition now included in the project'

### ISSUE THREAD

**Issue by fwh1990** [react-navigation/react-navigation#5690]
I upgrade version to 3.4.0 just now，is that mean I can remove @types/react-navigation?

### Current Behavior

`@types/react-navigation` is also required.

### Expected Behavior

This project include `.d.ts` file, and I can remove @types/react-navigation

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  3.4.0
| react-native     |  0.59.1
| node             |     8.12
| npm or yarn      |   yarn

**Comment by brentvatne** [comment]
you can remove it in 3.4.1 yeah
