### ISSUE TITLE
StackNavigator within StackNavigator within a BottomTabNavigator no popToTop on inner StackNavigator

### ISSUE THREAD

**Issue by hxiongg** [react-navigation/react-navigation#5691]
### Current Behavior

I have a StackNavigator within a StackNavigator as suggested on the [official docs](https://reactnavigation.org/docs/en/modal.html) to display some screens as modal while others as card on a StackNavigator

```ts
const InnerStack = createStackNavigator(
  {
    ScreenOne,
    ScreenTwo,
  },
  {
    initialRouteName: 'ScreenOne',
  },
);

const OuterStack = createStackNavigator(
  {
    InnerStack,
    ModalScreen,
  },
  {
    mode: 'modal',
    headerMode: 'none',
    initialRouteName: 'InnerStack',
  },
);

const TabNavigator = createBottomTabNavigator(
    {
        OuterStack, // TabOne
        TabTwo,
    }
);
```

### Expected Behavior
When I tap on TabOne icon at the bottomTabBar, the default behaviour is that it will popToTop on the StackNavigator. The issue is, that is only happening on the direct child StackNavigator (OuterStack) and not happening on the inner deeper StackNavigator (InnerStack).

As a result, tapping on the tabBarIcon will only dismiss the ModalScreen, and not popToTop on the InnerStack. E.g. if I am on ScreenOne or ScreenTwo, tapping on the tabBarIcon will not bring me back the respective tab.

Is there a way to customize screen navigated animation? If it is possible, I wouldn't have to nest those StackNavigator, thus avoiding this issue.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.12.1 and 3.4
| react-native     | 0.57.5

**Comment by brentvatne** [comment]
this is the default onPress handler for tab bar items: https://github.com/react-navigation/react-navigation-tabs/blob/e6efae6387b65e5c19f34bc6d3079c074867948e/src/utils/createTabNavigator.js#L103-L114

you can override this with `tabBarOnPress` to do whatever you want. https://reactnavigation.org/docs/en/bottom-tab-navigator.html#tabbaronpress
