### ISSUE TITLE
How to get Deep Linking parameter from route?

### ISSUE THREAD

**Issue by ManigandanRaamanathan** [react-navigation/react-navigation#5694]
I'm currently following your https://reactnavigation.org/docs/en/deep-linking.html

I've deep linked as per the tutorial with the code below.
Example code:-
Chat: {
    screen: ChatScreen,
    path: 'chat/:user',
 },

But the code is incomplete as it doesn't show how to retrieve the user name param from the screen.
Now, how do I get the user parameter from the actual chat screen?

I tried using this.props.navigation.getParam('user', '') . But it is not returning the parameter value

**Comment by brentvatne** [comment]
hi there! this is a question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.

**Comment by ManigandanRaamanathan** [comment]
:(

**Comment by mojtaba-hajishah** [comment]
@ManigandanRaamanathan Did you find a way to retrieve user name param from your component?
navigation.getParam('user') always returns undefined for me.

**Comment by evanAtFetchly** [comment]
I feel like this is something that should definitely be in the docs...

**Comment by evanb2** [comment]
I think this should be added to the docs.

**Comment by ManigandanRaamanathan** [comment]
@mojtaba-hajishah I ended up not using this deep link feature from react navigation

**Comment by rdewolff** [comment]
Looking for the same info

**Comment by wallevy** [comment]
https://www.reactnativeschool.com/handling-deep-links-with-react-navigation

**Comment by grinry** [comment]
Just found out it, it's `route` prop:

`this.props.route` (`this.props.route.params.id`)
or
```
function User({route}) {
    return <Text>User id: {route.params.id}</Text>
}
```

**Comment by bilalyaqoob** [comment]
You need to write nested config the same way you have the screens in navigation. And use props.route.params.id if you get undefined then better see the config.

**Comment by rus5665** [comment]
Chat: {
screen: ChatScreen,
path: 'chat/:user',
**parse: {  user: (user) => `${user}`   }**  <------add parse 
},

after that you can get the data **route.params.user**

**Comment by mdarifulislamroni521** [comment]
const linking = {
  prefixes: ["https://example.com"],
  config: {
    screens: {
      deeplink: {
        path: 'deeplink/details',
      },

    },

  },
};

**Make deeplink url:**
https://coingiftcard.com/deeplink/details?token=uygiuhiuhpuihpiuyiuhuihhiluhiu

**Access token from component:** 
this.props.route.params.token

**_result will be_** =uygiuhiuhpuihpiuyiuhuihhiluhiu
