### ISSUE TITLE
dynamic views on StackNavigator

### ISSUE THREAD

**Issue by faustoct** [react-navigation/react-navigation#5696]
On navigation doc I'm looking to how to make stack navigation loads dynamically. I have a set of screens 
````
Profile
Home
Search
Notification
Direct
````

Which are must have app views. Later I want to load the views on the fly. But I can add the views to stack navigator. Is there that possible?!? thank you :)

I have more 30 screens which must not be loaded when the app is initialized. 

---

### Current Behavior

N/A

### Expected Behavior

N/A

### How to reproduce

N/A

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | react-navigation@3.3.2
| react-native     | react-native-cli: 2.0.1 react-native: 0.58.6
| node             | v11.10.1
| npm or yarn      | 1.13.0

**Comment by eriveltonelias** [comment]
Hi @faustoct, 

`react-navigation` doesn't support dynamic routes, read this please https://reactnavigation.org/docs/en/limitations.html#dynamic-routes

**Comment by faustoct** [comment]
Hi @eriveltonelias ,
how do we solve app performance issues specially at loading time?!? Can I do smth to avoid loading too many views in app start?!?

**Comment by thinklinux** [comment]
@faustoct If your app has a heavy stack navigation - https://reactnavigation.org/docs/en/react-native-screens.html
