### ISSUE TITLE
Module 'react-navigation' has no exported member 'NavigationContext'

### ISSUE THREAD

**Issue by k-z** [react-navigation/react-navigation#5698]
### Current Behavior

Module 'react-navigation' has no exported member 'NavigationContext'

### Expected Behavior

Includes `NavigationContext` declaration in `.d.ts` file

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.4.1
| react-native     | 0.59.1
| node             | 11.11.0
| npm or yarn      | yarn

**Comment by brentvatne** [comment]
can you open a PR to add it? we're still working on improving the type definitions and we need help to make them solid

**Comment by brentvatne** [comment]
fixed in https://github.com/react-navigation/react-navigation/pull/5707
