### ISSUE TITLE
Tabs not swiching on tab press

### ISSUE THREAD

**Issue by caciobanita** [react-navigation/react-navigation#5699]
## The issue tracker is reserved for bug reports only.

If you have a question, feature request, or an idea for improving the library or its related tools, please try one of the following resources:

- [Read the documentation](https://reactnavigation.org/)
- [Post an issue to the website repository if you'd like to see a documentation change](http://github.com/react-navigation/website)
- [Post a feature request to Canny](https://react-navigation.canny.io/feature-requests)
- [Write a RFC if you have ideas for how to implement a feature request](https://github.com/react-navigation/rfcs)
- [Get help on Discord chat (#react-navigation on Reactiflux)](https://discord.gg/4xEK3nD) or [on StackOverflow](https://stackoverflow.com/questions/tagged/react-navigation)
- Search for your issue - it may have already been answered or even fixed in the development branch. However, if you find that an old, closed issue still persists in the latest version, you should open a new issue.

Bugs with react-navigation must be reproducible *without any external libraries that operate on it*. This means that if you are attempting to use Redux or MobX with it and you think you have found a bug, you must be able to reproduce it without Redux or MobX in this report. Redux related issues belong in [react-navigation-redux-helpers](https://github.com/react-navigation/react-navigation-redux-helpers), and we do not have any first-class integration with MobX at the moment.

---

### Current Behavior

- What code are you running and what is happening?
- Include a screenshot if it makes sense.

I have created a createMaterialTopTabNavigator. This is my code:
`{
    navigationOptions: ({ navigation }) => ({
      tabBarLabel: (props) => {
        const { routeName } = navigation.state
        let label = null
        const routes = ['Conversation', 'Locatari', 'Chatroom', 'Arhiva']
        const tabWidth = AppSizes.tabStyle.width
        const numTabsScreen =
          // eslint-disable-next-line prettier/prettier
          (AppSizes.screen.width - (AppSizes.screen.width % tabWidth)) / tabWidth

        let showNextIcon = false
        let showPrevIcon = false
        if (routeName === routes[3]) {
          if (props.focused) {
            lastFocusedRouteIndex = routes.indexOf(routeName)
          }
          label = 'Arhiva'
        } else if (routeName === routes[2]) {
          if (props.focused) {
            lastFocusedRouteIndex = routes.indexOf(routeName)
          }
          label = 'Grupuri'
        } else if (routeName === routes[1]) {
          if (props.focused) {
            lastFocusedRouteIndex = routes.indexOf(routeName)
          }
          label = 'Locatari'
        } else if (routeName === routes[0]) {
          if (props.focused) {
            lastFocusedRouteIndex = routes.indexOf(routeName)
          }
          label = 'Conversatii'
        }

        if (numTabsScreen < 4) {
          if (
            routeName === routes[2] &&
            lastFocusedRouteIndex < routes.indexOf(routes[2]) &&
            !props.focused
          ) {
            showNextIcon = true
          } else {
            showNextIcon = false
          }

          if (
            routeName === routes[1] &&
            lastFocusedRouteIndex >= routes.indexOf(routes[1]) &&
            !props.focused
          ) {
            showPrevIcon = true
          } else {
            showPrevIcon = false
          }
        }

        return (
          <View
            style={{
              flex: 1,
              padding: 5,
              flexDirection: 'row',
              alignContent: 'center',
            }}>
            {showPrevIcon && (
              <Icon
                type="material-icons"
                name="navigate-before"
                size={30}
                color={AppColors.brand.primary}
              />
            )}
            <Text
              style={{
                color: AppColors.textPrimary,
                margin: 5,
              }}>
              {label.toUpperCase()}
            </Text>
            {showNextIcon && (
              <Icon
                type="material-icons"
                name="navigate-next"
                size={30}
                color={AppColors.brand.primary}
              />
            )}
          </View>
        )
      },
    }),
    initialRouteName: 'Conversation',
    lazy: false,
    tabBarOptions: {
      scrollEnabled: true,
      style: {
        backgroundColor: AppColors.tabbar.background,
        height: 50,
      },
      tabStyle: {
        width: AppSizes.tabStyle.width,
      },
      activeTintColor: AppColors.tabbar.activeTintColor,
      inactiveTintColor: AppColors.tabbar.inactiveTintColor,
      indicatorStyle: {
        backgroundColor: AppColors.tabbar.indicatorColor,
      },
    },
    cardStyle: { backgroundColor: AppColors.background },
  }`

### Expected Behavior

- What do you expect should be happening?
- Include a screenshot if it makes sense.

On tab press he should change the tabs, but with `tabBarLabel` is working only the scroll swich.

### How to reproduce

- You must provide a way to reproduce the problem. If you are having an issue with your machine or build tools, the issue belongs on another repository as that is outside of the scope of React Navigation.
- Either re-create the bug on [Snack](https://snack.expo.io) or link to a GitHub repository with code that reproduces the bug.
- Explain how to run the example app and any steps that we need to take to reproduce the issue from the example app.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.18.3
| react-native     | 0.59.0
| node             | 10.11.0
| npm or yarn      | yarn

**Comment by rreiser-auti** [comment]
+1

**Comment by Smoothsmith** [comment]
I'm not sure how to link this properly, but is this not the same as:
https://github.com/react-navigation/react-navigation/issues/5684

(For which the workaround suggested resolves the issue for me).

**Comment by rreiser-auti** [comment]
For sure! the workaround resolves the issue. i´ve just upgraded the version of react-navigation-tabs to 2.0 alpha and changed the import of the components to react-navigation-tabs.

**Comment by brentvatne** [comment]
collapsing into https://github.com/react-navigation/react-navigation/issues/5684
