### ISSUE TITLE
How to update Tab navigation title dynamically?

### ISSUE THREAD

**Issue by jeyakumarsbe** [react-navigation/react-navigation#5700]
## How to update Tab navigation title dynamically?

I have 3 Tabs Tab1, Tab2 and Tab3. How can I Change this Tab title dynamically form any tab.

Below is My Code..

const TabNav = createBottomTabNavigator(
  {
    TabName1: {
      header: null,
      screen: HomeStackNav,
      navigationOptions: ({ navigation }) => ({
        title: 'Tab1',
        header: null,
        tabBarIcon: ({ tintColor }) => {
          return <MCIcon name="home" size={23} color={tintColor} />;
        }
      })
    },
    TabName2: {
      header: null,
      screen: SearchStackNav,
      navigationOptions: ({ navigation }) => ({
        title: 'Tab2'
      })
    },
    TabName3: {
      screen: RecentClickStackNav,
      navigationOptions: ({ navigation }) => ({
        header: null,
        title: 'Tab3'
      })
    }
  },
  {
    initialRouteName: "TabName1",
    tabBarPosition: "bottom",
    headerMode: "none",
    swipeEnabled: false,
    animationEnabled: false,
    lazy: true,
    removeClippedSubviews: true,
    order: ["TabName1", "TabName2", "TabName3"],
    backBehavior: "initialRoute",
  }
);

Please help me how can change Tab title dynamically.

Thanks,

**Comment by brentvatne** [comment]
it's a navigation option, so you can update it like this https://reactnavigation.org/docs/en/headers.html#overriding-shared-navigationoptions
