### ISSUE TITLE
`TabBarBottom` refers to class name which is exported by react-navigation as `BottomTabBar`

### ISSUE THREAD

**Issue by powersjcb** [react-navigation/react-navigation#5701]
# Current behavior
TS2305 warning when importing `BottomTabBar`.

# How to reproduce
`import { BottomTabBar } from "react-navigation";`

# Proposed fix
Type definitions for `TabBarBottom` should be `BottomTabBar`.

React-navigation exposes the api as `BottomTabBar`.
https://github.com/react-navigation/react-navigation/blob/4502061a1081704b34db82aa742a4ba8f7f04e4a/src/react-navigation.js

react-navigation-tabs exposes it as `BottomTabBar`
https://github.com/react-navigation/react-navigation-tabs/blob/master/src/index.js

react-navigation-tabs defines the class as `TabBarBottom` in `BottomTabBar.js`
https://github.com/react-navigation/react-navigation-tabs/blob/e23142ec736cf7516123e2f9ba96f102045aae85/src/views/BottomTabBar.js#L76

(I'll have PR out for this in a few min)

**Comment by brentvatne** [comment]
thanks, will publish this update shortly. still working through getting typescript types solid, the help is much appreciated!
