### ISSUE TITLE
Navigation Options in Nested Navigators

### ISSUE THREAD

**Issue by femioladipo** [react-navigation/react-navigation#5703]
### Current Behavior

Can't access navigationOptions (aka scene.descriptor.options) object for the current screen, if nested in one more than one navigator.
https://reactnavigation.org/docs/en/custom-navigators.html#scene-descriptors

### How to reproduce
Please see code extract to see where I have placed the console log statements, in an attempt to find the descriptor options.

| Statement | Output
|-----------|--------
| console.log(Object.keys(scene)) | Array [ "index", "isStale", "key", "route","descriptor","isActive",]
| console.log(scene.descriptor.options)| Object {"gesturesEnabled": false, "header": [Function HeaderBar],}
| console.log(Object.keys(descriptors))|Array ["id-1552949394639-2",]
| console.log(Object.keys(scenes))| Array ["0",]

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  3.0.9
| react-native     | 0.58.1
| node             | 11.4.0
| npm or yarn      | 6.8.0

```jsx
const HeaderBar = ({ navigation, ...props }) => {
  const { scene, descriptors, scenes } = props
  console.log(Object.keys(scene))
  console.log(scene.descriptor.options)
  console.log(Object.keys(descriptors))
  console.log(Object.keys(scenes))
  return (
    <Header>
      <Left>
        <Button transparent onPress={navigation.openDrawer}>
          <Icon name="menu" />
        </Button>
      </Left>
      <Body>
        <Title>
          {navigation.state.key.toUpperCase()}
        </Title>
      </Body>
      <Right />
    </Header>
  )
}

const withHeader = (screen, routeName) => {
  screen.navigationOptions = { ...screen.navigationOptions, header: HeaderBar }
  return createStackNavigator(
    { [routeName]: screen },
    {
      headerMode: 'screen',
      navigationOptions: {
        gesturesEnabled: false
      }
    }
  )
}

const Screens = createMaterialTopTabNavigator({
    Upcoming: UpcomingAppointmentsScreen,
    Calendar: CalendarScreen
})


const DrawerNavigator = createDrawerNavigator({
    Home: withHeader(HomeScreen, 'Home'), // can access navigation options
    Screens: withHeader(Screens, 'Screens') // CANNOT access navigation options
})

**Comment by brentvatne** [comment]
this is expected behavior. you'd be accessing the navigationOptions for the `Screens` navigator, which is a material top tab navigator.

you can use `defaultNavigationOptions` here to accomplish what you want, see https://snack.expo.io/@notbrent/belligerent-watermelon
