### ISSUE TITLE
TypeScript: headerLeftContainerStyle  not in NavigationScreenConfig<NavigationScreenOptions>

### ISSUE THREAD

**Issue by dalvikroid** [react-navigation/react-navigation#5704]
TypeScript: 

headerLeftContainerStyle not in NavigationScreenConfig<NavigationScreenOptions>

@types/react-navigation@3.0.5
react-navigation@3.3.2

**Comment by mptorz** [comment]
I have a similar problem:

TypeScript:

headerTitleStyle not in NavigationScreenConfig

"@types/react-navigation": "^3.0.1",
"react-navigation": "^3.1.5"

@dalvikroid what did you do?

**Comment by eriveltonelias** [comment]
hi @dalvikroid, 

this PR https://github.com/react-navigation/react-navigation/pull/5860 should fix this issue, try to update to the last version of react-navigation.
