### ISSUE TITLE
Nested navigators' navigationOptions not working

### ISSUE THREAD

**Issue by glacjay** [react-navigation/react-navigation#5710]
## The issue tracker is reserved for bug reports only.

If you have a question, feature request, or an idea for improving the library or its related tools, please try one of the following resources:

- [Read the documentation](https://reactnavigation.org/)
- [Post an issue to the website repository if you'd like to see a documentation change](http://github.com/react-navigation/website)
- [Post a feature request to Canny](https://react-navigation.canny.io/feature-requests)
- [Write a RFC if you have ideas for how to implement a feature request](https://github.com/react-navigation/rfcs)
- [Get help on Discord chat (#react-navigation on Reactiflux)](https://discord.gg/4xEK3nD) or [on StackOverflow](https://stackoverflow.com/questions/tagged/react-navigation)
- Search for your issue - it may have already been answered or even fixed in the development branch. However, if you find that an old, closed issue still persists in the latest version, you should open a new issue.

Bugs with react-navigation must be reproducible *without any external libraries that operate on it*. This means that if you are attempting to use Redux or MobX with it and you think you have found a bug, you must be able to reproduce it without Redux or MobX in this report. Redux related issues belong in [react-navigation-redux-helpers](https://github.com/react-navigation/react-navigation-redux-helpers), and we do not have any first-class integration with MobX at the moment.

---

### Current Behavior

- What code are you running and what is happening?

``` js
class MainScreen extends React.Component {
  static navigationOptions = ({ navigation }) => ({
    title: 'Main',
    headerRight: <Button title="Messages" onPress={() => navigation.push('Messages')} />,
  });

  render() { /* ... */ }
}

class MoreScreen extends React.Component {
  static navigationOptions = ({ navigation }) => ({
    title: 'More',
  });

  render() { /* ... */ }
}

const IndexNavigator = createBottomTabNavigator({
  Main: MainScreen,
  More: MoreScreen,
});

const AppNavigator = createStackNavigator({
  Index: IndexNavigator,
  Login: LoginScreen,
  /* other routes */
});

export default <AppNavigator ... />;
```

react-navigation.v1: on 'Index' route, switch to Main tab, it'll show 'Main' title and right button on the top navigation bar; switch to More tab, it'll show 'More' title on the top navigation bar.

react-navigation.v2/3: neither of `static navigationOptions` working, and the top navigation bar always show the blank.

- Include a screenshot if it makes sense.

### Expected Behavior

- What do you expect should be happening?

Show titles and other stuff specified by Screen components' navigationOptions in TabNavigator nest in StackNavigator.

- Include a screenshot if it makes sense.

### How to reproduce

- You must provide a way to reproduce the problem. If you are having an issue with your machine or build tools, the issue belongs on another repository as that is outside of the scope of React Navigation.
- Either re-create the bug on [Snack](https://snack.expo.io) or link to a GitHub repository with code that reproduces the bug.
- Explain how to run the example app and any steps that we need to take to reproduce the issue from the example app.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.5.1
| react-native     | 0.59.1
| node             | 10.15.3
| npm or yarn      | yarn-1.15.2, npm-6.7.0

**Comment by brentvatne** [comment]
hi! for more information on how to create a reproducible example see: https://stackoverflow.com/help/mcve

also, see https://reactnavigation.org/docs/en/navigation-options-resolution.html

**Comment by glacjay** [comment]
I see. So I think the best option for me is implementing the header bar by myself.

**Comment by brentvatne** [comment]
probably not! but if reading the docs i linked to above and creating a reproducible example is harder than that, then yeah maybe

**Comment by glacjay** [comment]
I've read the docs you linked, and found out that my use case is just the TabNavigator inside StackNavigator one, and confirmed that I can't set headerTitle in my MainScreen class and have that shown on the navigation bar. I don't want to move this navigationOptions from MainScreen to TabNavigator's definition cause it's more complicated than just setting a static title string, but also interacting with other parts of my MainScreen class (including network stuff), so...

BTW. by reproducible example, do you mean I must provide a complete example that can be run directly?

**Comment by brentvatne** [comment]
>  I don't want to move this navigationOptions from MainScreen to TabNavigator's definition cause it's more complicated than just setting a static title string, but also interacting with other parts of my MainScreen class (including network stuff), so...

if you don't want to move it then you can have the tab navigator return the child navigation options like this: https://github.com/react-navigation/react-navigation/blob/eac5feb64e2170f370a815f10af77b471e146648/examples/NavigationPlayground/app/StacksOverTabs.tsx#L123-L134

> BTW. by reproducible example, do you mean I must provide a complete example that can be run directly?

yeah, and minimal (as described in https://stackoverflow.com/help/mcve)

**Comment by glacjay** [comment]
Thanks, `getActiveChildNavigationOptions` is exactly what I need. 👍

**Comment by brentvatne** [comment]
i updated docs to add that https://reactnavigation.org/docs/en/navigation-options-resolution.html#getactivechildnavigationoptions

**Comment by Hideer** [comment]
How to cover locally navigationOptions?
when i use this not work 
```
static navigationOptions = {
 headerStyle: {
      
      borderBottomWidth: 0,
      shadowOpacity: 0,
      elevation: 0,
          },
}
I thought it was me before this was the property, but why can't it be overridden here
```
