### ISSUE TITLE
Only able to change tabs once

### ISSUE THREAD

**Issue by carlosdamiao** [react-navigation/react-navigation#5713]
### Current Behavior

- What code are you running and what is happening?
I am using createMaterialTopTabNavigator and I can only switch Tab's once using a tap, but I can switch Tab with the arrows on my laptop (using emulator). I have the same behavior on my mobile device.
I did a video to streamable showing the issue:
https://streamable.com/a8lax

Notice that when I'm pressing the buttons, the tabBarOnPress is being called, but for some reason defaultHandler is misbehaving.

- Include a screenshot if it makes sense.
Screenshot of how I'm using React Navigation:
https://cdn.discordapp.com/attachments/288388742929055765/557920242014093332/unknown.png

### Expected Behavior

- What do you expect should be happening?
I was expecting to be able to switch Tab's at will when tapping the buttons.

### How to reproduce

Repository: https://github.com/carlosdamiao/RNBottomBar

Steps: 
- Clone Repository
- run: npm install
- go to android folder
- run: gradlew clean <---- IMPORTANT: I had to do this to run the project
- go back to root
- react-native run-android

**NOTE: Didn't try in iOS**

In-App:

- Press "Sign in" button
- Change tabs

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation 3.5.1|
| react-native     0.59.1|
| node             10.13.0|
| npm or yarn      npm 6.4.1|

### Previous Environment
I have the exact same code running on a project with this environment:
| software         | version
| ---------------- | -------
| react-navigation 3.0.9|
| react-native     0.58.4|
| node             10.13.0|
| npm or yarn      npm 6.4.1|

That's why I think there might be some problem with react-navigation 3.5.1

PS: Anything else needed just ask, please. Thanks!

**Comment by condorman** [comment]
Same problem and same Upgrade Environment!
At moment I solved disabling animation and swipe

`const TabNavigator = createMaterialTopTabNavigator({
  ....
},
{
  swipeEnabled: false,
  animationEnabled: false
});`

Thanks!

**Comment by carlosdamiao** [comment]
I can confirm that disabling swipe and animation fixes the issue.

For now it's a nice quick solution, but a permanent solution is needed!

Thanks @condorman

**Comment by brentvatne** [comment]
You can use 2.0.0-alpha if you want: https://github.com/react-navigation/react-navigation-tabs/releases/tag/v2.0.0-alpha.0

We'll update to this soon but you can also just install it in your project and use it now. Another option is to use the yarn `resolutions` field to force the dependency to 2.0.0-alpha.0

**Comment by carlosdamiao** [comment]
Although I was able to use react-navigation-tabs 2.0.0-alpha.0 to use createMaterialTopTabNavigator, the performance is anywhere near of React Navigation. When I press a Tab, it drops my JS Frame Rate enough to have impact on my UI Frame Rate. It's noticeable to the user.

**Comment by satya164** [comment]
@carlosdamiao can you open a new issue regarding the frame drops preferably with a video/gif and a repro?

I'm closing this since I've released a new version of react-native-tab-view to address the breaking change in RN. You'll need to uninstall react-navigation and install it again to get the new changes.
