### ISSUE TITLE
SafeAreaView doesn't work properly with bottom bar on iPhone XR / XS max. White space has shown at the bottom

### ISSUE THREAD

**Issue by claudioviola** [react-navigation/react-navigation#5714]
---

### Current Behavior
SafeAreaView imported from react-navigation doesn't work properly with iPhone XR and iPhone XS Max, despite working fine with iPhone X and iPhone XS.

![Schermata 2019-03-20 alle 18 32 12](https://user-images.githubusercontent.com/6689594/54706943-5c4c3880-4b40-11e9-86a0-f8621a1413be.png)

### Expected Behavior
No extra white space at the bottom after the bottom bar

### How to reproduce

```
import React, {Component} from 'react';
import { Text, ScrollView } from 'react-native';
import { SafeAreaView, createAppContainer, createBottomTabNavigator } from 'react-navigation';

const testData = new Array(200).fill('hello world');

const TestScreen = () => (
	<SafeAreaView style={{ flex: 1, backgroundColor: '#fff' }}>
		<ScrollView style={{ flex: 1, backgroundColor: 'red' }}>
			{testData.map((e, i) => (<Text key={i}>{e}</Text>))}
		</ScrollView>
	</SafeAreaView>
);

const Tabs = createBottomTabNavigator({
	Tab1: {
		screen: TestScreen,
		navigationOptions: {
			title: 'Tab1',
		}
	},
	Tab2: {
		screen: TestScreen,
		navigationOptions: {
			title: 'Tab2',
		}
	},
	Tab3: {
		screen: TestScreen,
		navigationOptions: {
			title: 'Tab3',
		}
	},
	}, {
		tabBarOptions: {
			inactiveBackgroundColor: 'purple',
			activeBackgroundColor: 'yellow',
			activeTintColor: 'black',
			inactiveTintColor: 'gray',
		},
	}
);

const AppNavigator = createAppContainer(Tabs);


export default class App extends Component {
  render() {
    return (
      <AppNavigator />
    );
  }
}
```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.5.2
| react-native     | 0.55.4
| node             | 8.11.2
| npm or yarn      | 6.1.0 / 1.7.0

**Comment by brentvatne** [comment]
using the exact code you provided: https://snack.expo.io/@notbrent/authentic-cookies

<img width="456" alt="Screen Shot 2019-03-20 at 11 04 22 AM" src="https://user-images.githubusercontent.com/90494/54708154-f8a21b00-4aff-11e9-9b61-0e684a5b2109.png">
<img width="447" alt="Screen Shot 2019-03-20 at 11 05 25 AM" src="https://user-images.githubusercontent.com/90494/54708201-1e2f2480-4b00-11e9-9c50-cb39dc5b3d19.png">

**Comment by claudioviola** [comment]
@brentvatne sorry maybe there is a misunderstanding. As I can see you have the same bug that I faced: at the bottom beneath the bottom bar you have the white space.

If you try to change the color of the SafeArea of the TestScreen (`green` for example) you will see bottom bar remains white.

```
const TestScreen = () => (
	<SafeAreaView style={{ flex: 1, backgroundColor: 'green' }}>
		<ScrollView style={{ flex: 1, backgroundColor: 'red' }}>
			{testData.map((e, i) => (
				<Text key={i}>{e}</Text>
			))}
		</ScrollView>
	</SafeAreaView>
);

```
Here the header is green the bottom bar is always `green`
![Schermata 2019-03-20 alle 19 29 42](https://user-images.githubusercontent.com/6689594/54709889-b64ffc80-4b46-11e9-8724-c1f07def08b7.png)

**Comment by brentvatne** [comment]
the safeareaview only wraps the screen, which begins at the top of the screen and ends at the top of the tab bar. you can style the background color of the tab bar itself (including the part that is padded to make space for the home indicator) using the style prop on tabBarOptions - https://snack.expo.io/@notbrent/authentic-cookies

**Comment by claudioviola** [comment]
@brentvatne thanks for the helps
4 hours of struggling and frustration and at the end they were 2 lines of code
Thanks again

**Comment by FoxInFlame** [comment]
@claudioviola Would you mind sharing the solution?

**Comment by nullxx0** [comment]
@claudioviola Yes, please

**Comment by thefinnomenon** [comment]
I only wrapped my screen content in SafeAreaView (not my navigators), had the same issue with the white bar on the bottom and ended up fixing it by specifying `backgroundColor` on my TabNavigator's defaultNavigationOptions' style attribute.

```
export const TabNavigator = createBottomTabNavigator(
  { ... },
  {
    defaultNavigationOptions: ({ screenProps }) => ({
        tabBarOptions: {
          ...
          style: {
            backgroundColor: screenProps.theme.nav.background,
          },
        },
      })
    },
  }
);
```

**Comment by Urvish123** [comment]
```
const AppNavigator = createAppContainer(MainApp);

export default class App extends Component {
    render() {
      return (
<SafeAreaView style={{ flex: 1, backgroundColor: colors.app_color}}
 forceInset={{ top: 'always', bottom:'always' }}>
   
             <AppNavigator />

            
              </SafeAreaView>
      );
    }
  }
```
Add this in tabBarOptions

```
tabBarOptions: {
          safeAreaInset: { bottom: 'never', top: 'never' }
        }


```

**Comment by danhnguyeen** [comment]
how can I solve this problem in React Navigation v5 please?

**Comment by JimmySorza** [comment]
@danhnguyeen its the same that said @Urvish123 

use [react-native-safe-area-view](https://github.com/react-native-community/react-native-safe-area-view)

> ```
> const AppNavigator = createAppContainer(MainApp);
> 
> export default class App extends Component {
>     render() {
>       return (
> <SafeAreaView style={{ flex: 1, backgroundColor: colors.app_color}}
>  forceInset={{ top: 'always', bottom:'always' }}>
>    
>              <AppNavigator />
> 
>             
>               </SafeAreaView>
>       );
>     }
>   }
> ```

In my case I didn't have to use `tabBarOptions`

**Comment by federicomiralles** [comment]
> how can I solve this problem in React Navigation v5 please?

Try this:
`tabBarOptions: {
          safeAreaInsets: { bottom: 0, top: 0 }
        }`

**Comment by imanism** [comment]
I was facing the same problem in v5. Fixed by negating bottomInset with bottomPadding for screens with BottomBar.

```
import { useSafeArea } from 'react-native-safe-area-context';

export defaults function MyScreen() {
 
 const insets = useSafeArea();

  return(
    <SafeAreaView style={{ flex:1, paddingBottom: -insets.bottom }}>
      // screen contents
    </SafeAreaView>
  );
}
```

**Comment by imanism** [comment]
> I was facing the same problem in v5. Fixed by negating bottomInset with bottomPadding for screens with BottomBar.
> 
> ```
> import { useSafeArea } from 'react-native-safe-area-context';
> 
> export defaults function MyScreen() {
>  
>  const insets = useSafeArea();
> 
>   return(
>     <SafeAreaView style={{ flex:1, paddingBottom: -insets.bottom }}>
>       // screen contents
>     </SafeAreaView>
>   );
> }
> ```

Apparently, I only had to set SafeAreaView paddingBottom to 0 and all is good.

`<SafeAreaView style={{ flex:1, paddingBottom: -insets.bottom }}>`

**Comment by ravirajw** [comment]
> how can I solve this problem in React Navigation v5 please?

You can simply set background colour inside `tabBarOptions->style->backgroundColor`
```
    <NavigationContainer>
      <Tab.Navigator
        initialRouteName="AddCity"
        tabBarOptions={{
          activeTintColor: Colors.white,
          inactiveTintColor: Colors.blue500,
          labelStyle: {
            fontSize: 12,
            marginBottom: 10,
          },
          style: {
            backgroundColor: Colors.blue900,
          },
        }}>
        <Tab.Screen
          name="CitiesNavigation"
          component={CitiesNavigation}
          options={{
            title: 'Cities',
          }}
        />
        <Tab.Screen
          name="AddCity"
          component={AddCity}
          options={{
            title: 'Add City',
          }}
        />
      </Tab.Navigator>
    </NavigationContainer>
```

**Comment by xdajay** [comment]
> ```
> const AppNavigator = createAppContainer(MainApp);
> 
> export default class App extends Component {
>     render() {
>       return (
> <SafeAreaView style={{ flex: 1, backgroundColor: colors.app_color}}
>  forceInset={{ top: 'always', bottom:'always' }}>
>    
>              <AppNavigator />
> 
>             
>               </SafeAreaView>
>       );
>     }
>   }
> ```
> 
> Add this in tabBarOptions
> 
> ```
> tabBarOptions: {
>           safeAreaInset: { bottom: 'never', top: 'never' }
>         }
> ```

Thanks, this worked very well :)

**Comment by abramsamir1** [comment]
tabBarOptions={{
        style: { paddingBottom: 0}
     }}

**Comment by karthikkncash** [comment]
screenOptions={({ route }) => ({
        tabBarIcon: ({ focused, color, size }) => {
        tabBarStyle:{backgroundColor: '#436332', borderTopColor: '#23321A'},
        tabBarLabelStyle:{ fontWeight: '600',
          fontSize: 12,},
        tabBarActiveTintColor:'#f1c522',
        tabBarInactiveTintColor:'#f4f1de',
        tabBarActiveBackgroundColor:'#436332',
        tabBarInactiveBackgroundColor:'#436332'
      })}
      
      ReactNaviagtion6

**Comment by Hacanna42** [comment]
Add this lines at your TabNavigator screenOptions:

```
tabBarItemStyle: {borderWidth: 1, borderColor:'#101010'},
tabBarStyle: {paddingBottom:20, backgroundColor: '#101010'},
```
