### ISSUE TITLE
Switch Navigator hard-crash on android when using react-native-screens

### ISSUE THREAD

**Issue by TikiTDO** [react-navigation/react-navigation#5720]
### Current Behavior

When using a switch navigator in conjunction with a stack navigator, certain types of navigation in the switch navigator will cause the android app to hard-crash with an exception from `FragmentManager`.

### Expected Behavior

Normal navigation actions should not hard-crash the app.

### How to reproduce

Instructions to reproduce, and additional information available in kmagiera/react-native-screens#54

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.3.2
| react-native     | 0.58.6
| node             | 10.7.0
|  yarn      | 1.12.3

**Comment by brentvatne** [comment]
thanks! hopefully react-native-screens has a fix for it soon

**Comment by TikiTDO** [comment]
There's a usable workaround that uses reflection, but it definitely needs someone that is much more familiar with Android Fragments than me to actually do this properly.
