### ISSUE TITLE
TabBarTop component unable to override in v3

### ISSUE THREAD

**Issue by zapzero** [react-navigation/react-navigation#5721]
I like to create a dynamic hide/show tab bar depends on user mode.
 
when i am using createBottomTabNavigator + BottomTabBar ,  the code work fine, but after i change in to createMaterialTopTabNavigator + TabBarTop, the problem happened .

Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.

This code works in V2 , but not V3. No idea why.

Snack example: 
createBottomTabNavigator + BottomTabBar (Working)
[https://snack.expo.io/createbottomtabnavigator](https://snack.expo.io/@auronchoo/createbottomtabnavigator)

createMaterialTopTabNavigator + TabBarTop(Bug)
[https://snack.expo.io/creatematerialtoptabnavigator](https://snack.expo.io/@auronchoo/creatematerialtoptabnavigator)

      tabBarComponent: ({ navigation, ...rest }) => {
        const restrict = ['Admin'];
        // hide admin tab from tab bar
        const filteredTabNavigatorRoutes = navigation.state.routes.filter(
          route => restrict.indexOf(route.key) === -1
        );
        return (
          // override TabBarTop component
          <TabBarTop
            {...rest}
            navigation={{
              ...navigation,
              state: {
                ...navigation.state,
                routes: filteredTabNavigatorRoutes,
              },
            }}
          />
        );
      },
      tabBarPosition: 'top',

either i am using `tabBarComponent: (props) => <TabBarTop {...props} />`, still come out the same error

![image](https://user-images.githubusercontent.com/11909846/54747231-46567a80-4c09-11e9-8c3d-6dafd76324a7.png)

| software         | version
| ---------------- | -------
| react-navigation |^3.5.1
| react-native     | React Native 0.57 - Expo SDK v32.0.0   
| node             | v10.9.0
| npm or yarn      | 6.8.0

**Comment by eriveltonelias** [comment]
Hi @zapzero,

you need create a `React Component` to override the `tabBarComponent` see the docs https://reactnavigation.org/docs/en/material-top-tab-navigator.html#docsNav

**Comment by zapzero** [comment]
> Hi @zapzero,
> 
> you need create a `React Component` to override the `tabBarComponent` see the docs https://reactnavigation.org/docs/en/material-top-tab-navigator.html#docsNav

Hi @eriveltonelias 
So mean the only way to use tabBarComponent is create an custom react component, `overriding TabBarTop component is not possible `, right ? because I am considering reuse the native component is much more better than create a custom component, to keep the code more tidy

**Comment by mallelapavank** [comment]
Hi @zapzero 

How did you solve this issue?

**Comment by zapzero** [comment]
> Hi @zapzero
> 
> How did you solve this issue?

I still haven't find any way to use TabBarTop as tabBarComponent. Just change my code back to normal MaterialTopTabNavigator. But if you looking for custom solution maybe you can try to follow this [https://stackoverflow.com/questions/54409280/how-to-add-a-custom-component-to-creatematerialtoptabnavigator-tab-bar](https://stackoverflow.com/questions/54409280/how-to-add-a-custom-component-to-creatematerialtoptabnavigator-tab-bar)

Hope this can help

**Comment by mallelapavank** [comment]
By reading the code I just got to know that 'MaterialTopTabBar' exported now. It works same as 'TabBarTop'

`import { MaterialTopTabBar } from 'react-navigation-tabs';`
