### ISSUE TITLE
How to navigate from Stacknavigator to nested BottomTabNavigator

### ISSUE THREAD

**Issue by Heru6664** [react-navigation/react-navigation#5723]
I have two navigator, and i can't navigate to other navigator. i want to navigate to Inbox screen. wich is in Home screen. and Home are in Stack Navigator

1. StackNavigator 

_route.js_
```
import FooterTab from "../assets/Components/FooterTab";

const RootStack = createStackNavigator(
  {
    Login: {
      screen: Login,
      navigationOptions: {
        header: null
      }
    },
    Home: {
      screen: ({ navigation }) => (
        <FooterTab screenProps={{ rootNavigation: navigation }} />
      ),
      navigationOptions: {
        header: null
      }
    },
    SplashScreen: {
      . . .
  },
  {
    initialRouteName: "SplashScreen"
  }
); 

```

2. BottomTabNavigator

_footerTab.js or Home screen_
```
const MainScreenNavigator = createBottomTabNavigator(
  {
    Home: {
      screen: Home
    },
    Order: {
      screen: Order
    },
    Inbox: {
      screen: Inbox
    },
    Account: {
      screen: Account,
      navigationOptions: {
        header: null
      }
  }
);

const Tab = createAppContainer(MainScreenNavigator);
export default Tab;

```

---

### Current Behavior
- I can't access Inbox screen, no routename found in StackNavigator call "Inbox"
- Nothing happen after i triggered navigate action, because the routename 'Inbox" is not found, as you can see above. Inbox screen is in Home (Stacknavigator) and child of Home 

### Expected Behavior

- I want to navigate to Inbox screen (In BottomTabNavigator) from SplashScreen (StackNavigator)
- I want to navigate directly from splashscreen after i click action in notification open

### How to reproduce

- I already followed instruction in docs here : [Navigating without navigation prop](https://reactnavigation.org/docs/en/navigating-without-navigation-prop.html) and this is my code for implement that navigator service

```
import { NavigationActions, StackActions } from "react-navigation";

let _navigator;

setTopLevelNavigator = navigatorRef => {
  _navigator = navigatorRef;
};

navigate = (routeName, params) => {
  _navigator.dispatch(
    StackActions.reset({
      index: 0,
      actions: [
        NavigationActions.navigate({
          routeName,
          params
        })
      ]
    })
  );
};

export default {
  navigate,
  setTopLevelNavigator
};

```

and i set the top level of navigator in my index file

```
 import  NavigationService  from "./path-to/navigation-actions";
      <Root
        ref={navigatorRef => {
          NavigationService.setTopLevelNavigatornavigatorRef(navigatorRef)
        }}
      />

```

then i triggered for navigate to expected screen like this
` NavigationService.navigate("Inbox");`

but it's show error routeName Inbox can not found

### Your Environment

| software         | version

| react-navigation | 3.0.8
| react-native     | 0.57.7
| node             | v11.10.1
| npm | 6.7.0
| yarn | 1.13.0

hope you understand

**Comment by eriveltonelias** [comment]
Hi @Heru6664,

I think that you're trying to do something like this https://snack.expo.io/@eriveltonelias/basic-switch-tab
