### ISSUE TITLE
when set drawer drawerLockMode is 'locked-open', touch the outside of drawer can not close it

### ISSUE THREAD

**Issue by leer561** [react-navigation/react-navigation#5725]
## The issue tracker is reserved for bug reports only.
---

### Current Behavior

when set drawer drawerLockMode is 'locked-open', touch the outside of drawer can not close it

### Expected Behavior
when touch the outside i want it close

### How to reproduce

https://github.com/leer561/rnapp 
app.js i set the drawerLockMode

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.3.2
| react-native     | 0.59
| node             | 11.2
| npm or yarn      |

**Comment by eriveltonelias** [comment]
Hi @leer561,

this is the expected behavior, check the docs 

https://reactnavigation.org/docs/en/drawer-navigator.html#drawerlockmode

https://facebook.github.io/react-native/docs/drawerlayoutandroid.html#drawerlockmode

**Comment by leer561** [comment]
@eriveltonelias oh... i should use locked-closed....
