### ISSUE TITLE
Cannot read property 'Direction' of undefined

### ISSUE THREAD

**Issue by Akkujvl** [react-navigation/react-navigation#5728]
### Current Behavior
Cannot read property 'Direction' of undefined

### How to reproduce

```
...
import { createStackNavigator, createAppContainer } from 'react-navigation';
...
const AppNavigator = createStackNavigator({
    home: {
        screen: HomeScreen
    }
})


class Route extends Component {
    render() {
        return (
            <AppNavigator />
        )
    }
}

export default createAppContainer(Route);

```
### Your Environment

    System:
      OS: macOS 10.14.1
      CPU: (4) x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
      Memory: 330.10 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.11.4 - /usr/local/bin/node
      npm: 6.4.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.1 => 0.59.1 
    npmGlobalPackages:
      react-native-cli: 2.0.1

| react-navigation  ==> 3.5.1
| react-native    ==> 0.59.1

**Comment by brentvatne** [comment]
https://github.com/react-navigation/react-navigation/issues?utf8=%E2%9C%93&q=Cannot+read+property+%27Direction%27+of+undefined+
