### ISSUE TITLE
ExceptionsManager.js:82 Warning: ViewPagerAndroid has been extracted from react-native core and will be removed in a future release. It can now be installed and imported from '@react-native-community/viewpager' instead of 'react-native'

### ISSUE THREAD

**Issue by Steffi3rd** [react-navigation/react-navigation#5730]
<img width="977" alt="Capture d’écran 2019-03-22 à 22 35 05" src="https://user-images.githubusercontent.com/814410/54854637-d83ab200-4cf3-11e9-93bc-c7540d48da5f.png">

**Comment by eriveltonelias** [comment]
Hey @Steffi3rd, thanks for your report

we're tracking this issue in here https://github.com/react-navigation/react-navigation/issues/5729 and https://github.com/react-navigation/react-navigation/issues/5684#issuecomment-473159635

**Comment by Kevin9505** [comment]
I have the same problem. How can I solve it?

**Comment by robizzt** [comment]
Same problem, two errors:

package.json:
```
{
  "name": "TestApp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.8.3",
    "react-native": "0.59.8",
    "react-native-gesture-handler": "^1.2.1",
    "react-navigation": "^3.9.1"
  },
  "devDependencies": {
    "@babel/core": "^7.4.4",
    "@babel/runtime": "^7.4.4",
    "babel-jest": "^24.8.0",
    "jest": "^24.8.0",
    "metro-react-native-babel-preset": "^0.54.0",
    "react-test-renderer": "16.8.3"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

![react-navigation-bug](https://user-images.githubusercontent.com/30315895/57782378-63508b00-772c-11e9-9ba8-3f3472b8eb99.jpg)

**Comment by HarshitMadhav** [comment]
Any update on this issue? I am stuck with this error.

**Comment by firofame** [comment]
react-navigation uses `"react-navigation-tabs": "~1.1.4"` bumping it to the latest version could resolve the issue

**Comment by cryoten** [comment]
Any estimation on when this is to be fixed?

**Comment by naxtor** [comment]
> react-navigation uses `"react-navigation-tabs": "~1.1.4"` bumping it to the latest version could resolve the issue

Not working for me

**Comment by YajanaRao** [comment]
Any update on the issue?

**Comment by rossmacfarlane** [comment]
Any updates on this issue? I'm seeing the yellowbox warning about ViewPagerAndroid. Is it related to react-navigation or the dependency on react-navigation-tabs? 

Don't want to supress the warning so hoping for a solution

Using "react-navigation": "3.11.0"

**Comment by beeremy** [comment]
same here, dependency created by React-navigation

**Comment by Winandvdb** [comment]
The latest version of react navigation (v3.11.1) still has react-navigation-tabs v1.1.4 as dependency. When will this be fixed?

**Comment by gbalduzzi** [comment]
Updated to `react-native-gesture-handler` version 1.0.16 and I don't have ViewPagerAndroid, Slider and Webview warnings anymore.

**Comment by Winandvdb** [comment]
Strange, my react-native-gesture-handler is on 1.2.1. Downgrading the version doesn't seem ideal.

**Comment by rossmacfarlane** [comment]
I think even downgrading to 1.0.16 the warning is still there but only in the console? Just not showing as a yellowbox warning. At least for me anyway

**Comment by taschik** [comment]
I am on "react-native-gesture-handler": "^1.3.0", and "react-navigation": "^3.11.1", and still see this warning. Any plans to update?

**Comment by soban1234** [comment]
Not fixed yet

"dependencies": {
    "@mapbox/polyline": "^1.1.0",
    "@react-native-community/async-storage": "^1.5.1",
    "formik": "^1.5.8",
    "git": "^0.1.5",
    "react": "16.8.6",
    "react-native": "0.60.3",
    "react-native-background-fetch": "^2.6.1",
    "react-native-background-geolocation": "^3.0.9",
    "react-native-calendars": "^1.200.0",
    "react-native-countdown-component": "^2.5.1",
    "react-native-gesture-handler": "^1.3.0",
    "react-native-maps": "0.25.0",
    "react-native-signature-capture": "git+https://github.com/RepairShopr/react-native-signature-capture.git",
    "react-native-slide-to-unlock": "^0.1.4",
    "react-native-vector-icons": "^6.6.0",
    "react-navigation": "^3.11.1",
    "yup": "^0.27.0"
  },

**Comment by cjmoran-vw** [comment]
FYI: you can hide the yellow box for this warning in the meantime by doing this at the root level of your app:

```
import { YellowBox } from "react-native"

YellowBox.ignoreWarnings([
  "Warning: ViewPagerAndroid has been extracted",
])
```

You'll still see it in console but it's better than nothing.

**Comment by rsmzjk** [comment]
ViewPagerAndroid在react-native里被移除,那依赖此的组件无法调用该如何解决.

**Comment by cwilby** [comment]
Getting this error at the minute with `react-navigation@4.0.10` and `react-navigation-tabs@2.6.2`.

**Comment by olkunmustafa** [comment]
> ```js
> import { YellowBox } from "react-native"
> 
> YellowBox.ignoreWarnings([
>   "Warning: ViewPagerAndroid has been extracted",
> ])
> ```

Interesting why everyone downvotes this comment.

**Comment by jsamr** [comment]
@olkunmustafa I guess it goes along the lines "ain't no problem if you can't see it", and a very close cousin of "if we don't test, there's no virus!". You're basically applying censorship to the very willing and helpful Yellow Box, that's very mean and risky!
