### ISSUE TITLE
Screen content jumps when stack push from normal header to transparent header

### ISSUE THREAD

**Issue by kidcosmic** [react-navigation/react-navigation#5731]
### Current Behavior
When pushing from Screen A to Screen B. Screen B has a transparent header.
Screen A's content jumps to the top of Screen A, where the Screen A header previously was. This is really jarring when the screens are busy.

### Expected Behavior

- Screen A's content should stay in place

### How to reproduce

https://snack.expo.io/BJhajfQdE

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.5.1
| react-native     | 0.58.6
| node             | 11.11.0
| npm or yarn      | 1.15.2

**Comment by brentvatne** [comment]
use headerMode: 'screen' if you want to mix transparent header with translucent header

**Comment by ajfick** [comment]
I'm having this same issue even with `headerMode: 'screen'` in place. Below is my stack navigator code. I'm not sure if I'm doing something else that's causing problems here ... 

```
const Navigator = createStackNavigator({
    Browse: {
        screen: Browse,
        title: "Browse",
        navigationOptions: {
            headerMode: 'screen'
        }
    },
    Detail: {
        screen: Detail,
        title: "Detail",
        navigationOptions: {
            headerMode: 'screen',
            headerTitle: null,
            headerBackTitle: null,
            headerBackImage: <BackButton color="#ffffff" />,
            headerTransparent: true,
            headerStyle: {
                backgroundColor: "transparent",
            }
        }
    },
    Search: {
        screen: Search,
        title: "Search"
    },
}, {
        defaultNavigationOptions
    });
```

**Comment by kopax** [comment]
I am having my content jumping when switching view and no idea why. I can see the AppBar having multiple layer because of the way the blur is moving. Any idea how I can fix the navigation? I am on next branch.

**Comment by josermorales** [comment]
@kopax Same here. Did you managed to find a solution?
