### ISSUE TITLE
SafeAreaView entire application

### ISSUE THREAD

**Issue by Dror-Bar** [react-navigation/react-navigation#5732]
Greetings,
Firstly, do note this is a question and not a bug report, I apologize if this is not allowed - feel free to close this in that case.

From the documentation:

> Note that SafeAreaView should not wrap entire navigators, just the screen components or any content in them.

My question is, why is this? If I don't plan on using the Header component ever, why can't I simply wrap the entire application with SafeAreaView? This seems to work well:
```
<SafeAreaView style={{ flex: 1 }}>
     <AppContainer />
</SafeAreaView>
```
Why would this be wrong? And does it matter if I use SafeAreaView from react-native or react-navigation?
### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.5.1
| react-native     | 0.59.1
| node             | 9.4.0
| npm or yarn      | 6.5.0

**Comment by brentvatne** [comment]
if you use safeareaview like that then you will just have an empty space where notch / home indicators are. this is not how to properly respect safe areas.

**Comment by Dror-Bar** [comment]
Thanks, but how come? I thought the whole idea is to have empty space (that can have matching backgroundColor) in those areas. Also, wouldn't using SafeAreaView on a per-screen basis would have the same effect?

**Comment by brentvatne** [comment]
@Dror-Bar - i updated the documentation to explain more clearly why this is important, see https://reactnavigation.org/docs/en/handling-iphonex.html and read the introduction and first example

**Comment by Dror-Bar** [comment]
Nice example with the full screen image. Thanks.

**Comment by rahul7910** [comment]
cant see that example anymore :/

**Comment by shoopi12** [comment]
@rahul7910 https://reactnavigation.org/docs/handling-safe-area
