### ISSUE TITLE
How to disable/Enable drawer Swipe Gesture in react-navigation V3 Drawer?

### ISSUE THREAD

**Issue by Moonubanna** [react-navigation/react-navigation#5733]
I want to disable swipe gesture of the drawer when I am navigating to another screen in navigation drawer. But after my research I found that drawerLockMode: 'locked-closed' is not working in react-navigation version 3 and also I tried "gestureEnabled = false" in navigationOptions but it was not working. Any suggestions or help regarding this problem would be helpful to me.

**Comment by eriveltonelias** [comment]
check this https://github.com/react-navigation/react-navigation/issues/5725

**Comment by tedi** [comment]
This is not working for me either. I referenced the issue you mentioned, but no luck locking the drawer closed.

**Comment by brentvatne** [comment]
@tedi - create a new issue and follow issue template (be sure to include minimal reproducible example)
