### ISSUE TITLE
On scroll, tab bar label either disappears or active tint color gets removed

### ISSUE THREAD

**Issue by randomfrantickoala** [react-navigation/react-navigation#5734]
### Current Behavior

- On scroll, top tab navigation label disappears or active tint color gets removed

### Expected Behavior

- Label should appear and tint color shouldn't be removed

### How to reproduce

- Created this [gist](https://gist.github.com/randomfrantickoala/d3b059c14d6ca04ae6ffd4085b105eed) to show how the tabs are being created
- Added a [video](https://www.reddit.com/r/reactnative/comments/b4t9ng/on_scroll_react_navigation_tab_bar_label_either/) in to show what is happening clearly

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.0.9
| react-native     | 0.57.4
| node             | 10.10.0
| npm or yarn      | 6.4.1

**Comment by eriveltonelias** [comment]
hi! please make your code runnable either on https://snack.expo.io without any extraneous code
