### ISSUE TITLE
initialRouteName not working

### ISSUE THREAD

**Issue by ricardolousada** [react-navigation/react-navigation#5735]
Hello team,

I'm not sure if it's a bug or some error (i'm new to this...). I read the documentation and implemented the following stackNavigator:

import {createStackNavigator,createAppContainer} from 'react-navigation';
import Contacts from '../screens/Contacts';
import Details from '../screens/Details';
import Status from '../screens/Status';
import Home from '../screens/Home';
import Login from '../screens/Login';

const AppNavigator = createStackNavigator ({
    Contacts: {
        screen: Contacts,
        navigationOptions: () => ({
            title: 'Contacts',
        }),
    },
    Details: {
        screen: Details,
        navigationOptions: () => ({
            title: 'Details',
        }),
    },
    setStatus: {
        screen: Status,
        navigationOptions: () => ({
            title: 'Status',
        }),
    },
    Login: {
        screen: Login,
        navigationOptions: () => ({
            title: 'Login',
        }),
    },
    Home: {
        screen: Home,
        navigationOptions: () => ({
            title: 'Welcome',
        }),
    },

    
    initialRouteName: "Login",
    
});

export default AppContainer = createAppContainer(AppNavigator);

Them on the App.js I have the following code:

import React from 'react';
import {AppNavigator} from './Config/router.js';

export default class App extends React.Component {
  render() {
    return (
      <AppContainer />
    );
  }
}

I run the app, no errors, but instead of showing the initial route screen with should be "Login" it goes to the Contacts screen.

Can someone please help?

Thank you.

**Comment by eriveltonelias** [comment]
hi there! this issue tracker is reserved for bugs only. your post seems to be a usage question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help. thanks!
