### ISSUE TITLE
How to use createBottomTabNavigator inside another component

### ISSUE THREAD

**Issue by WebMobi59** [react-navigation/react-navigation#5736]
Maybe this issue is duplicated with #903 and #2566, but I couldn't solve this error with those solutions.  
I am updating old react-native project to new one and I am getting **Invariant Violation: The navigation prop is missing for this navigator...** error now. But I don't know how to use TabNavigator as component in the latest react-navigation version.
Any help is appreciated!

---

### Current Behavior

- Geo.js

```
...
  renderModal() {
    if (this.state.modalVisible && this.props.geoData) {
      return (
        <View style={[styles.modal, { marginTop: this.state.modalTop+this.state.modalTopDelta }]}>
          <View style={styles.modalTitlePanel} {...this.panResponder.panHandlers}>
            {this.renderTitle()}
          </View>
          <GeoResult screenProps={this.props.geoData.results} /> // error come from here.
        </View>
      );
    }
  }
...
```

- GeoResult.js

```
'use strict';

import React from 'react';
import {
  View,
  Text,
  StyleSheet,
  Platform
} from 'react-native';
import Icon from 'react-native-vector-icons/MaterialIcons';
import { createBottomTabNavigator} from 'react-navigation';
...

class Info extends React.Component {
...
}

class Transaction extends React.Component {
...
}

class Use extends React.Component {
...
}

class Planning extends React.Component {
...
}

module.exports = createBottomTabNavigator({
  GeoInfo: {
    screen: Info,
    navigationOptions: {
     ...
    }
  },
  GeoTransaction: {
    screen: Transaction,
    navigationOptions: {
      ...
    }
  },
  GeoUse: {
    screen: Use,
    navigationOptions: {
      ...
    }
  },
  GeoPlanning: {
    screen: Planning,
    navigationOptions: {
      ...
    }
  }
}, {
  tabBarOptions: {
    ...
  },
  lazy: true,
  backBehavior: 'none'
});
```

- Screenshot
![Screen Shot 2019-03-24 at 2 13 54 PM](https://user-images.githubusercontent.com/20356023/54883759-27bfe000-4ea4-11e9-9add-1c0d033fadc6.png)
)

### Expected Behavior

- Need to disappear error.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.5.1
| react-native     | 0.59.1
| node             | 10.14.1
| npm or yarn      | 6.4.1(1.12.3)

**Comment by eriveltonelias** [comment]
Hi @WebMobi59, 

as the error explain: "in react-navigation 3 you must set up your app container directly..."

read this: https://reactnavigation.org/docs/en/app-containers.html#docsNav
