### ISSUE TITLE
bug with custom tabBarIcon in createBottomTabNavigator 

### ISSUE THREAD

**Issue by seongminchoob** [react-navigation/react-navigation#5740]
## The issue tracker is reserved for bug reports only.

If you have a question, feature request, or an idea for improving the library or its related tools, please try one of the following resources:

- [Read the documentation](https://reactnavigation.org/)
- [Post an issue to the website repository if you'd like to see a documentation change](http://github.com/react-navigation/website)
- [Post a feature request to Canny](https://react-navigation.canny.io/feature-requests)
- [Write a RFC if you have ideas for how to implement a feature request](https://github.com/react-navigation/rfcs)
- [Get help on Discord chat (#react-navigation on Reactiflux)](https://discord.gg/4xEK3nD) or [on StackOverflow](https://stackoverflow.com/questions/tagged/react-navigation)
- Search for your issue - it may have already been answered or even fixed in the development branch. However, if you find that an old, closed issue still persists in the latest version, you should open a new issue.

Bugs with react-navigation must be reproducible *without any external libraries that operate on it*. This means that if you are attempting to use Redux or MobX with it and you think you have found a bug, you must be able to reproduce it without Redux or MobX in this report. Redux related issues belong in [react-navigation-redux-helpers](https://github.com/react-navigation/react-navigation-redux-helpers), and we do not have any first-class integration with MobX at the moment.

---

### Current Behavior

tab bar focused state is not working properly. 
they are both in the "focused" state when the first tab is selected and they are both in the "not focused" state when the second tab is selected.
<img width="296" alt="스크린샷 2019-03-26 오후 1 51 10" src="https://user-images.githubusercontent.com/35505959/54972294-533ee980-4fce-11e9-9f09-2424819895dc.png">
<img width="309" alt="스크린샷 2019-03-26 오후 1 51 12" src="https://user-images.githubusercontent.com/35505959/54972295-533ee980-4fce-11e9-8aa9-327cb8686462.png">

true "mainscreen"                                         MainTabStack.js:24 
false "mainscreen"                                        MainTabStack.js:24 
true "likescreen"                                            MainTabStack.js:36 
false "likescreen"                                          MainTabStack.js:36 

also when I log focused, i get this in my console every time I select a tab.

I tried to check the tintcolor, and use a static navigationoptions in each screen, instead of in the overall, but got the same issue still.

this is my current code

const MainTabStack = createBottomTabNavigator({
    HomeStack: {
        screen: HomeScreen,
        navigationOptions: {
        tabBarLabel:"검색",
        tabBarOptions: { activeTintColor:'black', inactiveTintColor: '#8E8E93'},
        tabBarIcon: ({ tintColor, focused }) => {
            console.log(focused, 'mainscreen')
            return (<Image
                style={{ width: 32, height: 32 }}
                source={focused ? require('../src/img/tabIcons/homeOnIcon.png') : require('../src/img/tabIcons/homeOffIcon.png')}/>);}
      }
    },
    LikeScreen: {
        screen: LikeScreen,
        navigationOptions: {
        tabBarLabel:"좋아요",
        tabBarOptions: { activeTintColor:'black', inactiveTintColor: '#8E8E93'},
        tabBarIcon: ({focused }) => {
            console.log(focused, 'likescreen')
            return (<Image
                style={{ width: 32, height: 32 }}
                source={focused ? require('../src/img/tabIcons/likeOnIcon.png') : require('../src/img/tabIcons/likeOffIcon.png')}/>);}
      }
    }
})

### Expected Behavior

- What do you expect should be happening?

only one tab should be selected each time.

### How to reproduce

const MainTabStack = createBottomTabNavigator({
    HomeStack: {
        screen: HomeScreen,
        navigationOptions: {
        tabBarLabel:"검색",
        tabBarOptions: { activeTintColor:'black', inactiveTintColor: '#8E8E93'},
        tabBarIcon: ({ tintColor, focused }) => {
            console.log(focused, 'mainscreen')
            return (<Image
                style={{ width: 32, height: 32 }}
                source={focused ? require('../src/img/tabIcons/homeOnIcon.png') : require('../src/img/tabIcons/homeOffIcon.png')}/>);}
      }
    },
    LikeScreen: {
        screen: LikeScreen,
        navigationOptions: {
        tabBarLabel:"좋아요",
        tabBarOptions: { activeTintColor:'black', inactiveTintColor: '#8E8E93'},
        tabBarIcon: ({focused }) => {
            console.log(focused, 'likescreen')
            return (<Image
                style={{ width: 32, height: 32 }}
                source={focused ? require('../src/img/tabIcons/likeOnIcon.png') : require('../src/img/tabIcons/likeOffIcon.png')}/>);}
      }
    }
})

this is my current code

### Your Environment

| software         | version
| ---------------- | -------
    "react-navigation": "^3.3.2",
    "react-native": "0.59.1",

**Comment by eriveltonelias** [comment]
Hi @seongminchoob, 


you should use `defaultNavigationOptions` https://snack.expo.io/@eriveltonelias/basic-createbottomtabnavigator-config

you can find this too on the docs https://reactnavigation.org/docs/en/tab-based-navigation.html

**Comment by seongminchoob** [comment]
I already tried using default navigation options but still the same issues

**Comment by seongminchoob** [comment]
I have a tab bar view embedded inside of a stackview maybe that’s causing the malfunction?
