### ISSUE TITLE
Tab navigator doesn't  work inside ScrollView

### ISSUE THREAD

**Issue by bbeckk** [react-navigation/react-navigation#5741]
### Current Behavior

I've placed a tab navigator in the middle of the screen. It has few other components above tab navigator. I need a scrollView as the parent component since I need to vertically scroll the tab navigator along with other components in the screen. But the tab navigator stops working if its parent component is ScrollView.

### Expected Behavior

The tab navigator along with the components above it should have scrolled vertically.

### How to reproduce

https://snack.expo.io/@codebyte99/tab-navigator-in-scrollview-test

### Your Environment

react-navigation  ^3.0.9
react-native     0.57.8
npm or yarn      6.1.0

**Comment by brentvatne** [comment]
you can use https://github.com/react-navigation/react-navigation-tabs/releases/tag/v2.0.0-alpha.0 and see if that helps. this is a weird case case and we don't explicitly support it so if that doesn't help then you'll have to figure it out on your own, sorry
