### ISSUE TITLE
createNavigator returns undefined with jest on RN 0.59

### ISSUE THREAD

**Issue by annakocheshkova** [react-navigation/react-navigation#5742]
### Current Behavior

After upgrading our app to react native `0.59`, we have jest tests failing because `createBottomTabNavigator` returns `undefined`.

This is the [log output](https://gist.github.com/annakocheshkova/03160096fe15623892fe7ffbae72c969).

### Expected Behavior

We have a simple jest test that checks that the page is rendering.
This test should pass after upgrading to react-native `0.59`.
This issue is really blocking us right now so we would appreciate if you give us at least some estimate on 0.59 support.

### How to reproduce

1. `npm i -g react-native@0.59`
2. `react-native init TestApp`
3. Fill `App.js` with the contents like in the [example](https://reactnavigation.org/docs/en/tab-based-navigation.html#minimal-example-of-tab-based-navigation)
4. `npm i --save-dev jest`
Jest configuration inside `package.json`:
```
"jest": {
    "preset": "react-native",
    "verbose": true,    
    "transformIgnorePatterns": [
      "!node_modules/react-native"
    ],
    "transform": {
      "^.+\\.js$": "<rootDir>/node_modules/react-native/jest/preprocessor.js"
    }
  }
```
5. `npm i --save react-navigation`
6. Add test `index.test.js` with the following contents:
```
import 'react-native';
import React from 'react';
import  App from './App';
import renderer from 'react-test-renderer';

it('renders correctly', () => {
  const tree = renderer.create(
    <App />
  );
});
```
7. `npm run test`
### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.5.1
| react-native     | 0.59
| node             | 10.15.1 (+ several other)
| npm or yarn      | 6.4.1 (+ several other)

**Comment by ksmithbaylor** [comment]
@annakocheshkova My team is in the process of upgrading to 0.59 as well (from 0.57), and we ran into this issue and successfully fixed it (about 30 minutes ago actually 😄). It's a problem with RN's Jest preprocessor, and described well [in an issue here](https://github.com/facebook/react-native/issues/22175). We solved it by using [`patch-package`](https://www.npmjs.com/package/patch-package) to change the `inlineRequires` option to false in `node_modules/react-native/jest/preprocessor.js`, like in [the PR](https://github.com/facebook/react-native/pull/23326) that was opened in the RN repo. It doesn't seem like it's the "correct" solution, but the RN team is aware of it and I'd anticipate it being fixed in a future release.

**Comment by brentvatne** [comment]
thanks for providing that context @ksmithbaylor!

**Comment by annakocheshkova** [comment]
Thanks @ksmithbaylor it works. But not the best solution, I agree :)
I still would like to hear the opinion or some kind of estimate from contributors @brentvatne 😉 .

**Comment by brentvatne** [comment]
why would you need an estimate from me? this is unrelated to react-navigation

**Comment by brentvatne** [comment]
so i looked into this and tried what @annakocheshkova shared in the original post, but changed the jest config as per @cpojer's comment here https://github.com/facebook/react-native/issues/22175#issuecomment-474795611 and it worked as expected. i also added more stuff to transformIgnorePatterns, basically just copied what we have in jest-expo - you don't have to use this but just make sure any react-native lib you're using fits the pattern

```
  "jest": {
    "preset": "react-native",
    "verbose": true,
    "transformIgnorePatterns": [
      "node_modules/(?!((jest-)?react-native|react-clone-referenced-element|expo(nent)?|@expo(nent)?/.*|react-navigation|@react-navigation/.*|sentry-expo|native-base))"
    ]
  }
```

**Comment by german970814** [comment]
@ksmithbaylor I'm working on 0.58 and it doesn't work for me, I keep getting the same issue :( and it does not work as expected
