### ISSUE TITLE
Navigation doesn't work with Detox and New changes of react native gesture handler 

### ISSUE THREAD

**Issue by yogeshthanvi** [react-navigation/react-navigation#5743]
On upgrading the react native project to RN 59 the detox starts giving the below issue 

TypeError: param is not an Object. (evaluating ''__isNative' in param')

To Solve this RNGH community contributor and owner fix the issues by modifying the code as 

return (
    param !== undefined &&
    typeof param !== 'function' &&
    // (typeof param !== 'object' || !('__isNative' in param)) &&
    (typeof param !== 'object' || (param !== null && !('__isNative' in param))) &&
    name !== 'onHandlerStateChange' &&
    name !== 'onGestureEvent'
  );
The reference of the issue can be taken from below 
https://github.com/wix/Detox/issues/1207
https://github.com/kmagiera/react-native-gesture-handler/pull/525

Now after all this it stopped working the navigation we are not able to navigate to new screen 
Detox community claims it react navigation issue and RNGH is silent . We are seriously stuck with the issue and its a complete blocker to us. Can your community and contributor can help us on this

**Comment by ddzirt** [comment]
@yogeshthanvi 
Have you tried using this:
`await device.disableSynchronization();`

**Comment by micabe** [comment]
Same here. I have used latest fix from [react-native-gesture-handler](https://github.com/kmagiera/react-native-gesture-handler) and helped me fix `__isNative` issue, now Navigate actions just do nothing while running Detox. PLease help!

**Comment by micabe** [comment]
with 

"react-native": "0.59.2",
"react-navigation": "3.5.1",

**Comment by brentvatne** [comment]
there is nothing that we can do to help with this, it seems to be a bug in react-native 0.59, i'd suggest downgrading to react-native 0.58 until they figure it out

**Comment by micabe** [comment]
Hello @brentvatne. Thanks for the quick reply. Could you then fill an issue on their side?

Thank you

**Comment by elyalvarado** [comment]
@micabe It all seems related to Detox's issue [#1234](https://github.com/wix/Detox/issues/1234). Detox (actually earl gray) is basically setting Platform.isTesting to true in React Native and that is causing a lot of issues while detox is attached. This issue is fixed in Detox 12.1 (just released).

**Comment by amphithere** [comment]
> react-native-gesture-handler

How did you get rid of the __isNative problem?

**Comment by ddzirt** [comment]
Just use latest version of RNGH, isNative was fixed

**Comment by brentvatne** [comment]
locking because the correct answer is to use latest detox and rngh and this is no longer an issue
