### ISSUE TITLE
createMaterialTopTabNavigator not working properly 

### ISSUE THREAD

**Issue by ThakurKarthik** [react-navigation/react-navigation#5748]
### Current Behavior

The below is shown : 
`ReactNativeRenderer-dev.js:2514 Cannot read property 'configureProps' of undefined`

### Expected Behavior

Tab view should be working properly after upgrading react-navigation-tabs to **v2.0.0-alpha.0**

### How to reproduce

Follow the installation instructions as per [Link to react-navigation-tabs release](https://github.com/react-navigation/react-navigation-tabs/releases/tag/v2.0.0-alpha.0)

```
import React from 'react'
import {createAppContainer} from 'react-navigation'
import {createMaterialTopTabNavigator} from 'react-navigation-tabs'
const TabNavigator=createMaterialTopTabNavigator({
    Rewatch:{
        screen:Rewatch
    },
    Bookmarks:{
        screen:Bookmarks
    }
}
)
export default createAppContainer(TabNavigator)
```
When i import createMaterialTopNavigator from react-navigation no error is shown but the tab switching doesn't work on tap as shown in other issues.

Here is the package.json
```
"dependencies": {
    "react": "16.8.3",
    "react-native": "0.59.1",
    "react-native-gesture-handler": "^1.1.0",
    "react-native-reanimated": "^1.0.0-alpha.12",
    "react-native-size-matters": "^0.1.6",
    "react-native-vector-icons": "^6.4.2",
    "react-navigation": "^3.4.1",
    "react-navigation-tabs": "2.0.0-alpha.0"
  }
```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |3.4.1
| react-native     |0.59.1
| node             |8.11.3
| npm or yarn      |npm

**Comment by xipgroc** [comment]
In our case, this is happening too with react-navigation 3.5.1 in conjunction with rn 0.59. First tap switches tab, then subsequent taps do nothing. This is only happening when tapping, and only affecting android (sweeping tabs is OK).

Using 3.5.1 with rn 0.58 works.

**Comment by ThakurKarthik** [comment]
Yes i was facing,in fact many were facing that issue following other links had a fix of updating the react-navigation-tabs to alpha version but in my case it is throwing error when i try to import createMaterialTopNavigator from react-navigation-tabs

**Comment by brentvatne** [comment]
<a href="https://imgflip.com/i/2x47e2"><img src="https://i.imgflip.com/2x47e2.jpg" title="made at imgflip.com"/></a>

https://stackoverflow.com/help/mcve

**Comment by ThakurKarthik** [comment]
Hey the issue seems to be fixed after restarting the computer :).By the way i used this code before  [Link to expo snack](https://snack.expo.io/@karthik.01/c21pbG) now changed to
` import {createAppContainer,createMaterialTopTabNavigator} from 'react-navigation'` and the tab view is working now.

**Comment by xipgroc** [comment]
Yes it's working after upgrading react-navigation-tabs to v2.0.0-alpha.0 and changing the corresponding imports, thanks.

**Comment by ghmeec** [comment]
Facing the same error when trying to 
import {createBottomTabNavigator} from 'react-navigation-tabs'

in react-navigation-tabs@2.5.5
and i followed all the set up instructions
