### ISSUE TITLE
[iOS] Slowly swiping back when hiding TabNav on new screen, also hides it on old

### ISSUE THREAD

**Issue by schumannd** [react-navigation/react-navigation#5752]
### Current Behavior

When swiping back from screen 2 to screen 1, the tab bar appears only when the screen has slid all the way into view

### Expected Behavior

The tab bar should be visible even if just "peeking" at the previous page

### How to reproduce

snack: https://snack.expo.io/BJsKomcd4

1. go to second tab (Screen 1)
2. press button to go to Screen 2
3. slowly swipe back (iOS gesture)

### Your Environment

newest environment (provided by snack)

should happen in any version.

    "react-navigation": "3.5.1"

**Comment by brentvatne** [comment]
that's not how this works with the navigator structure that you've built here. you can structure it like this instead: https://snack.expo.io/@notbrent/vigorous-chips

**Comment by schumannd** [comment]
So in general "hiding" of the tab bar nav should not be done, instead all subpages of each tab (which I previously had in one stack) should be split up into two stacks, one within the TabNavigator, one within its parent. And pages where the tabnavigator should be visible go in the first, and the others go in the second?

I.e.:

where one previously had:

Stack1: [page1, page2, page3]
Stack2: [page1, page2, page3]
Stack3: [page1, page2, page3]

Tabnav: [Stack1, Stack2, Stack3]

Rootnav: [Tabnav, LoginNav]

Where all "page1" want to show the tabnav, and the others want to hide it, the structure would have to be split up into:


Stack1a: [page1]
Stack1b: [page2, page3]
Stack2a: [page1]
Stack2b: [page2, page3]
Stack3a: [page1]
Stack3b: [page2, page3]

Tabnav: [Stack1a, Stack2a, Stack3a]

Rootnav: [Tabnav, LoginNav, Stack1b, Stack2b, Stack3b]


Just to make sure I understand the concept correctly.

**Comment by brentvatne** [comment]
yeah that might be how you do it. although probably you don't need stack1b stack2b stack3b you could just have stackb that has all of the routes in it. or add them to your rootnav which could be a stack.
