### ISSUE TITLE
gesturesEnabled not working at the stack navigator level

### ISSUE THREAD

**Issue by jd20** [react-navigation/react-navigation#5756]
### Current Behavior

I have a nested StackNavigator (inner one for card stack, and outer for modals) and previously on react-navigation 2.x I had `gesturesEnabled: false` defined at the stack level for the modal navigator, like so:

```
const CardStackNavigator = createStackNavigator({
  Card1: { ... },
  Card2: {...},
  ...
})

const ModalNavigator = createStackNavigator({
  CardStack: { screen: CardStackNavigator },
  Modal1: { screen: ModalScreen }
}, {
  initialRouteName: 'CardStack',
  headerMode: 'none',
  mode: 'modal',
  navigationOptions: { gesturesEnabled: false }
})
```

After upgrading to 3.x, I've found that gestures are working again for the modals, and I had to move `gesturesEnabled: false` to the screen level, in order to work again, like this:

```
const ModalNavigator = createStackNavigator({
  CardStack: { screen: CardStackNavigator },
  Modal1: {
    screen: ModalScreen,
    navigationOptions: { gesturesEnabled: false }
  }
}, {
  initialRouteName: 'CardStack',
  headerMode: 'none',
  mode: 'modal'
})
```

### Expected Behavior

`gesturesEnabled: false` should work at the navigator level.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.5.1
| react-native     | expo 31.0.6

**Comment by brentvatne** [comment]
````
defaultNavigationOptions: {
  gesturesEnabled: false,
};
```

**Comment by maheraldous** [comment]
If you want to enable gestures for all but disable it for one of the screen you can do this:

const CartStack = createStackNavigator(
  {
    Cart: CartScreen,
    Payment: PaymentScreen,
    Checkout: CheckoutScreen,
    OrderDone: {
      screen: OrderDoneScreen,
      navigationOptions: () => ({
        // disable it just here
        gesturesEnabled: false,
      }),
    },
  },
  {
    defaultNavigationOptions: {
      // enable it for all
      gesturesEnabled: true,
    },
   }
);
