### ISSUE TITLE
Can I store the navigation state in Redux too? - Any more explanation please?

### ISSUE THREAD

**Issue by adamgajzlerowicz** [react-navigation/react-navigation#5759]
Hi, reading the docs - you explained that this is probably not a good idea to use the integration.
I'd like to use it though, as I am missing some features (like navigation cancelling, redirecting or chaining) that can be easily achieved by connecting router to redux.

Can you please give more insight on this? What can go wrong or what are likely scenarios that I am overseeing please? I'd like to use the integration but considering notes on the official docs I am hesitant now.

Thank you!

**Comment by brentvatne** [comment]
we don't support this. there is plenty of information on why not if you search for it in the issues. you can do what you want to do by composing getStateForAction on a router, eg: https://reactnavigation.org/docs/en/routers.html#blocking-navigation-actions
