### ISSUE TITLE
willFocus event not fired on initial mount

### ISSUE THREAD

**Issue by sinansonmez** [react-navigation/react-navigation#5761]
### Current Behavior

I am trying to use react navigation props to check the current date and if date is changed, I update states and do other actions etc. 

```
  componentDidMount() {
    this.props.navigation.addListener('willFocus', payload  => {
      console.debug('focused A!');
    });
  }
```

### Expected Behavior

I expect willFocus listener will work at initial start as well but it doesnt.  However when I change the screens it works.

### How to reproduce

It is reproduced in https://snack.expo.io/@sinansonmez/tab-willfocus-event
I have reproduced it with "react-navigation": "2.0.0-rc.7" but same issue happens with 3.6.0 version as well

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.0.0-rc.7
| react-native     | "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz",
| expo      |     32.0.0

**Comment by atimetoremember** [comment]
i think this is a bug of react-navigation, i use react-navigation-is-focused-hoc instead for willFocus.

**Comment by sinansonmez** [comment]
As a workaround I am calling function two times, if you want to be sure function is called both at initial start of the app and on screen changes. 

    componentDidMount(){
        console.debug('focused A!'); // calling it here to make sure it is logged at initial start
        
        this.props.navigation.addListener('willFocus', payload  => {
      console.debug('focused A!'); // calling it here to make sure it is logged at every time screen is focused after initial start
      });
    }

**Comment by sinansonmez** [comment]
I checked once again and the problem isnt directly related to react navigation. 
Problem was I am calling AsyncStorage method inside navigation listener. Since AsyncStorage is working asynchronously, methods are not completed inside navigation listener. 

How I did solve this issue is that I made componentDidMount async function and call methods outside of navigation listener with await. 

```
async componentDidMount(){
    await console.debug('focused A!'); // calling it here to make sure it is logged at initial start
    
    this.props.navigation.addListener('willFocus', payload  => {
  console.debug('focused A!'); // calling it here to make sure it is logged at every time screen is focused after initial start
  });
}
```
