### ISSUE TITLE
Navigating to a "StackNavigation" doesn't pass through new updated parameters

### ISSUE THREAD

**Issue by bobber205** [react-navigation/react-navigation#5763]
### Current Behavior

```javascript
const AccountActionsStack = createStackNavigator(
    {
        AccountViewScreen: AccountScreen,
        ListContentsAccountScreen: ListContentsAccountScreen,
        ViewItemReviewScreen: ViewItemReviewScreen,
        GlobalItemView: GlobalItemView
    }
);

const AccountStack = createStackNavigator(
    {
        AuthLoadingScreen: AuthLoadingScreen,
        SignInScreen: SignInScreen,
        AccountScreen: AccountActionsStack,
        CreateUserStack: CreateUserStack,
    }, 
    {
        headerMode: 'none',
    }
);
```

### Expected Behavior

The Authloadingscreen navigates to "AccountScreen" with a user_id -- say 1.

When a user logs out and goes to "SignInScreen" we navigate to "AccountScreen" again but with a different user ID: say 2.

All logging says that `this.props.navigation.state.params` is `{user_id: 1}` not 2. If I navigate to "AccountViewScreen" then everything works fine. 

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.6.1
| react-native     | 0.58
| node             | Latest
| npm or yarn      | Latest

**Comment by brentvatne** [comment]
https://github.com/react-navigation/rfcs/issues/43
