### ISSUE TITLE
Navigation bug on the Stack navigator with the initial route on recalling of the stack  navigators.

### ISSUE THREAD

**Issue by mubashirrahman** [react-navigation/react-navigation#5769]
Stack navigator inside the bottom tab navigator and the bottom tab navigator inside the drawer navigator 
In code the Drawer Navigator exported default condition
//export default createDrawerNavigator()

then the bottom tab under the Drawer navigator on initial route
// Home:BottomTab

In bottom tab The initial route routes into a stack navigator
//HomeB:HomeStack

In this code, Clicking the Bottom tab HomeB Option ,That Navigating the Previous Navigation Not Navigating the first initial route of StackNavigator

I think the issue under the stack navigator,
The issue shows the navigation bug on stack navigator with navigating the Initial route of the stack navigator
how to clear the navigation bug in stack navigator 
??????????????

**Comment by matthamil** [comment]
Hi! Can you provide a reproducible example

**Comment by eriveltonelias** [comment]
I'll close the issue for now, but you can add the repro to the original post and then ping me and I'll reopen to investigate. Thanks for understanding.
