### ISSUE TITLE
updating pros in routes

### ISSUE THREAD

**Issue by itcurves** [react-navigation/react-navigation#5770]
## The issue tracker is reserved for bug reports only.

If you have a question, feature request, or an idea for improving the library or its related tools, please try one of the following resources:

- [Read the documentation](https://reactnavigation.org/)
- [Post an issue to the website repository if you'd like to see a documentation change](http://github.com/react-navigation/website)
- [Post a feature request to Canny](https://react-navigation.canny.io/feature-requests)
- [Write a RFC if you have ideas for how to implement a feature request](https://github.com/react-navigation/rfcs)
- [Get help on Discord chat (#react-navigation on Reactiflux)](https://discord.gg/4xEK3nD) or [on StackOverflow](https://stackoverflow.com/questions/tagged/react-navigation)
- Search for your issue - it may have already been answered or even fixed in the development branch. However, if you find that an old, closed issue still persists in the latest version, you should open a new issue.

Bugs with react-navigation must be reproducible *without any external libraries that operate on it*. This means that if you are attempting to use Redux or MobX with it and you think you have found a bug, you must be able to reproduce it without Redux or MobX in this report. Redux related issues belong in [react-navigation-redux-helpers](https://github.com/react-navigation/react-navigation-redux-helpers), and we do not have any first-class integration with MobX at the moment.

---

### Current Behavior

I have a stack router that has 2 routes please check the image below:
![image](https://user-images.githubusercontent.com/1397397/55540244-9533f380-5690-11e9-8a42-57bfa4e690bc.png)

I have this router class that renders this stack navigator, but I have some props updated outside of this component it did trigger getDerivedStateFromProps in this Router class but those pros not updating in the routes like in above image ChatList or Room.
How I can get updated props in ChatList or Room
![image](https://user-images.githubusercontent.com/1397397/55540198-7cc3d900-5690-11e9-9b47-fe3ea81f735f.png)

Note:
I do have getDerivedStateFromProps in both ChatList and Room but those never called on props update.

### Expected Behavior

Need updated props in the routes

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.0.9
| react-native     | 0.58.3

**Comment by vonovak** [comment]
hi there! this issue tracker is reserved for bugs only. your post seems to be a usage question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help. thanks!


also, please make sure to improve the problem description, I don't really understand what you're trying to achieve
