### ISSUE TITLE
Drawer item click some times does not respond

### ISSUE THREAD

**Issue by mithunmo** [react-navigation/react-navigation#5771]
### Current Behavior

- What code are you running and what is happening?

Clicking on the drawer item does not respond some times. Drawer navigator is the outside navigator that encompasses other stack navigators. 

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.3.2
| react-native     | 0.59
| node             | 10
| npm or yarn      | 1.12.3

**Comment by mithunmo** [comment]
[react-navigation.zip](https://github.com/react-navigation/react-navigation/files/3043186/react-navigation.zip)

**Comment by mithunmo** [comment]
[react-navigation-issue.zip](https://github.com/react-navigation/react-navigation/files/3043199/react-navigation-issue.zip)

Attached is the video of the issues ,  and navigation files

**Comment by matthamil** [comment]
@mithunmo Can you upload the video to Google Drive/YouTube/etc? I am hesitant to download a random zip :).

Can you also provide a reproducible code sample?

**Comment by mithunmo** [comment]
@matthamil 
https://www.youtube.com/watch?v=L-18mwlTVAs

Please see after 23 seconds. Some times the unresponsive behavior is more frequent. We got less issue when we were recording :)

Code for navigation 
https://github.com/mithunmo/react-navigation-drawer-item-click-issue

**Comment by eriveltonelias** [comment]
Hi @mithunmo, 

I recommend you to try this one https://github.com/react-navigation/react-navigation/issues/5287#issuecomment-491940226

if doesn't work for you, as @matthamil mentioned above, please make an runnable example without any extraneous code.
