### ISSUE TITLE
Warning: MaskedViewIOS has been extracted from react-native core

### ISSUE THREAD

**Issue by germainc** [react-navigation/react-navigation#5773]
Just updated react-native to 0.59.3 and getting this warning.  MaskedViewIOS is being moved to react-native-community.

| software         | version
| ---------------- | -------
| react-navigation | 3.6.1
| react-native     | 0.59.3

**Comment by brentvatne** [comment]
it has, we haven't decided what to do yet about this. quite possible we will require that users inject their own maskedview. this is a pretty unfortunate thing to extract from the core and in my opinion it was the wrong move :(
