### ISSUE TITLE
Custom tab bar component using the default tab bar

### ISSUE THREAD

**Issue by KakarN** [react-navigation/react-navigation#5774]
### Current Behavior

- React navigation use createMaterialTopTabNavigator from react-native-tab-view, 

- `TabView` of react-native-tab-view has  has a method `renderTabBar`, which returns a custom React Element. 

- So, this custom tab bar may have different styles. Also, within this custom tab bar, it is possible to include the default TabBar component.

[Please check out this snack](https://snack.expo.io/@kakarn/custom-of-react-native-tab-view).

### Expected Behavior

- React navigation also provides a way to use a custom react component via `tabBarComponent` for the `createMaterialTopTabNavigator`.
- However, I was unable to work with the TabBar component as it was possible with react-native-tab-view.

[Check out this snack](https://snack.expo.io/@kakarn/custom-react-navigation-tab-view)

Is there any way that I can use the default tab bar or similar to it with react-navigation, or dynamically change the **style** property of the `tabBarOptions`, so that I can work with `onScroll` methods and also the swiping gestures of the default tab bar, to achieve a UI similar to when using react-native-tab-view? 

What I am finally trying to achieve is this type of UI on the video, also you can [check out this snack](https://snack.expo.io/@kakarn/react-native-whatsapp) for the code. I tried this by [Extending the Navigators](https://reactnavigation.org/docs/en/custom-navigators.html#extending-navigators) as described on the documentation.

![WhatsAppVideo20190405at11](https://user-images.githubusercontent.com/9060759/55607851-cbf63080-579a-11e9-94a6-6df7122267d4.gif)

But the problem on the above code is, I am guessing here, that since I am scrolling the list and translating the main view containing the list on the same time, the scrolling is stuttering. Providing a higher value to `scrollEventThrottle={16}` makes it a bit smooth, but even then the performance is bad.

### Your Environment

| software         | version
| ---------------- | -------
| expo |32.0.0
| react-navigation |3.5.1
| react-native     | 0.57
| node             |v10.14.1
| npm or yarn      |6.4.1

**Comment by vonovak** [comment]
hi! I took your snack and reworked it: https://snack.expo.io/@vonovak/react-native-whatsapp

it doesn't look 100% right (you'll have to change some paddings and etc, but you get the idea. If you use this in a stack, the amount by which you will want to translate (the nav bar height) can be found [here](https://github.com/react-navigation/react-navigation-stack/blob/e05581cf197d36f7a9f6ef9d4b74a14e3962cf74/src/views/Header/Header.js#L64).

btw, your usage of computed and observer from mobx is not correct: look at https://mobx.js.org/refguide/observable.html

> By default, making a data structure observable is infective; that means that observable is applied automatically to any value that is contained by the data structure, or will be contained by the data structure in the future. This behavior can be changed by using modifiers.

that is why `@observable scroll = new Animated.Value(0)` is not what you want to do. You typically do not want to make an animated value observable at all - animated value is not a number, it is an object that wraps the animated logic and all that matters is that you hold a reference to it. If you're ever interested in a change in animated value, you'll probably be interested in the change of the reference and you should use `observable.ref` in that case https://doc.ebichu.cc/mobx/refguide/modifiers.html

**Comment by KakarN** [comment]
Aha! Your response was really very informative.

1. MaterialTopTabBar
2. **Bonus**: observable.ref

Thank you!

**Comment by vonovak** [comment]
@KakarN 

> So there's no need to for an observable value for an animated value, am I right?

that is correct. Not only is it not needed, it may actually cause problems.

**Comment by KakarN** [comment]
Okay. Thank you for clarifying!
