### ISSUE TITLE
addListener eventName prop on interface NavigationScreenProp should have type EventType

### ISSUE THREAD

**Issue by LydGol90** [react-navigation/react-navigation#5776]
### Current Behavior

I am trying to mock the navigation screen prop in jest and I am getting a type error 

Types of property 'addListener' are incompatible.
Type '(eventName: "willFocus" | "didFocus" | "willBlur" | "didBlur", callback: NavigationEventCallback)...' is not assignable to type '(eventName: EventType, callback: NavigationEventCallback) => NavigationEventSubscription'.
Types of parameters 'eventName' and 'eventName' are incompatible.
Type 'EventType' is not assignable to type '"willFocus" | "didFocus" | "willBlur" | "didBlur"'.
Type '"action"' is not assignable to type '"willFocus" | "didFocus" | "willBlur" | "didBlur"'.

<img width="522" alt="Screenshot 2019-04-05 at 16 05 38" src="https://user-images.githubusercontent.com/29592293/55637338-b3970d80-57bc-11e9-8b1b-8a3c94a12e7e.png">

### Expected Behavior
This type error should not exist and can be fixed by setting the type of eventName to 'EventType'

### How to reproduce

Try mocking the react navigation screen prop in jest

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |3.6.1
| react-native  | 58
| node | 8.15.0
| npm or yarn |  6.4.1

**Comment by matthamil** [comment]
Can you provide a reproducible example?

**Comment by LydGol90** [comment]
Hi @matthamil, thanks for your reply. I was just trying to make a reproducible example and have found the issue. It seems that I was importing the NavigationScreenProp type from @types/react-navigation (version 3.0.6) which has a slightly different type for the addListener nav prop than the types in the react-navigation library itself. I am no longer seeing this error. Sorry for wasting your time!

I have removed @types/react-navigation from my project and am not getting any type errors. Do you know if @types/react-navigation is needed anymore when using react-navigation?

**Comment by eriveltonelias** [comment]
thanks @matthamil! 

@LydGol90, yes you can remove @types/react-navigation now, types definition was included on react-navigation 3.4.0 ( https://github.com/react-navigation/react-navigation/blob/master/CHANGELOG.md#added-2 )
