### ISSUE TITLE
How to nest a component wrapping a stack navigator inside a tab navigator

### ISSUE THREAD

**Issue by JulianAssmann** [react-navigation/react-navigation#5778]
### Current Behavior

I am trying to have a tab navigator, where one of the screens/tabs has a component, that, among other stuff, has a stack navigator in it.
However, I currently get a 'No "routes" found in navigation state' error. 

### How to reproduce
 The code I'm currently running can also be found [as a snack](https://snack.expo.io/@julianassmann/react-navigation---nest-wrapped-stack-navigator-inside-a-tab-navigator).
Code: 
```
import * as React from 'react';
import { Button, Text, View, StyleSheet } from 'react-native';
import { createAppContainer, createStackNavigator, createBottomTabNavigator } from 'react-navigation';

class ScreenA extends React.Component {
  static navigationOptions = {
    tabBarLabel: 'A',
  };

  render() {
    return (
      <View>
        <Text>Screen A</Text>
      </View>
    );
  }
}

class SettingsHome extends React.Component {
  render() {
    return (
      <Button onPress={() => this.props.navigation.navigate('SettingsScreenA')}>
        <Text>Navigate to Settings A</Text>
      </Button>
    );
  }
}

class SettingsScreenA extends React.Component {
  render() {
    return (
      <View>
        <Text>Settings A</Text>
        <Button onPress={() => this.props.navigation.navigate('SettingsA')}>
          <Text>Back to SettingsHome</Text>
        </Button>
      </View>
    );
  }
}

const SettingsStackNavigator = createStackNavigator({
  SettingsHome: { screen: SettingsHome },
  SettingsScreenA: { screen: SettingsScreenA }
})

class SettingsScreen extends React.Component {
  static navigationOptions = {
    tabBarLabel: 'Settings',
  }

  render() {
    return (
      <View>
        <Text>Some other components...</Text>
        <SettingsStackNavigator navigation={this.props.navigation}/>
      </View>
    );
  }
}

const RootTabNavigator = createBottomTabNavigator({
  ScreenA: { screen: ScreenA },
  Settings: {screen: SettingsScreen },
});

const Navigation = createAppContainer(RootTabNavigator);

export default class App extends React.Component {
  render() {
    return (
      <Navigation />
    );
  }
}
```

### My Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.3.2
| react-native     | 0.57.7
| node             | 11.3.0
| npm | 4.6.1

**Comment by vonovak** [comment]
hi, thanks for reporting.

> I am trying to have a tab navigator, where one of the screens/tabs has a component, that, among other stuff, has a stack navigator in it.

It is unclear to me what you want to have there other than a stack navigator - that use case seems unusual. Can you expand on this?

changing your RootTabNavigator to this will make it work for now 
```
const RootTabNavigator = createBottomTabNavigator({
  ScreenA: { screen: ScreenA },
  Settings: {screen: SettingsStackNavigator },
});
```

**Comment by AregShahbazian** [comment]
Although the issue is closed, the question is still unanswered (and not understood).
I'm trying to do something similar to what @JulianAssmann described. Replacing `SettingsScreen` with `SettingsStackNavigator` won't always make it work because `SettingsScreen` can have other things that you will be missing this way.

Imagine the `Settings` route gets some parameter `param1`. In the `SettingsScreen` you wanna watch if `param1` changes (in `componentDidUpdate`) and accordingly make some API call that affects all screens in `SettingsStackNavigator`.

I'm trying this with a `createMaterialTopTabNavigator` nested inside a React-component. Using @JulianAssmann's domain to describe it, I added 
```  static router = SettingsStackNavigator.router;```
to `SettingsScreen` (mentioned [here](https://reactnavigation.org/docs/en/common-mistakes.html) as a possible solution). Sad to say it doesn't work, and gives:

  ```ExceptionsManager.js:44 TypeError: No "routes" found in navigation state. Did you try to pass the navigation prop of a React component to a Navigator child? See https://reactnavigation.org/docs/en/custom-navigators.html#navigator-navigation-prop```

**Comment by satya164** [comment]
@AregShahbazian you need to create a custom navigator to do that https://reactnavigation.org/docs/en/custom-navigators.html

**Comment by AregShahbazian** [comment]
@satya164 Indeed a custom navigator is what I was describing. After rebuilding a couple of times it does work now. Problem solved!
