### ISSUE TITLE
defaultNavigationOptions types on createBottomTabNavigator

### ISSUE THREAD

**Issue by guptaamol** [react-navigation/react-navigation#5781]
So i am creating a bottomTabNavigator and there seems to be an issue with type for prop `navigationOptions`,

In interface `NavigationBottomTabRouterConfig` the type for `defaultNavigationOptions` is ` NavigationScreenConfig<NavigationBottomTabScreenOptions>` which seems fine 
but the type for `navigationOptions` is `NavigationTabRouterConfigBase` which i believe should be  `NavigationScreenConfig<NavigationBottomTabScreenOptions>`,  seems a bit odd, same is the case with `NavigationTabRouterConfig`, the type seems fine for `NavigationStackRouterConfig` where the type is `NavigationScreenConfig<NavigationScreenOptions>`

**Comment by brentvatne** [comment]
open a pull request to fix it! :)

**Comment by guptaamol** [comment]
Sure I'll do it.
