### ISSUE TITLE
how can navigate a->b->c  to a->c->b

### ISSUE THREAD

**Issue by neegqi** [react-navigation/react-navigation#5782]
The general logic like this 

now stack is  a->b->c 

when from screen "c"  navigate to "b" is back to screen "b" and pop the screen "c"

i need a->c->b

**Comment by neegqi** [comment]
if i use this.props.navigation.push  it was  a->b->c->b

i need a->c->b

**Comment by vonovak** [comment]
hello, thanks for reporting, although I have to say it is not clear to me what question you're asking. 

> i need a->c->b

you need to call `this.props.navigate('a')`, then `this.props.navigate('c')`, and then `this.props.navigate('b')`

if this doesn't help please ask your question more precisely, thanks.
