### ISSUE TITLE
drawerLockMode is not working with v3

### ISSUE THREAD

**Issue by Sherif-Magdy** [react-navigation/react-navigation#5787]
i searched with previous issues but i had the same issue of drawerLockMode
My version's : 
` "react": "16.6.1",
    "react-native": "0.57.7",
     "react-navigation": "3.5.1",
    "react-navigation-drawer": "^1.2.1"`
i tried to lock drawer and not respond to gestures.
`  drawerLockMode: "locked-closed",`

i followed and did a research with the same issues mentioned before but still have it , please save my day

**Comment by matthamil** [comment]
Can you create a reproducible example? I recommend using [Snack](https://snack.expo.io/) or creating a public repo and sharing the link. Thanks!

**Comment by Sherif-Magdy** [comment]
i tried at expo, it works fine but in react native cli still the same issue.
i use ignite as a boilerplate do you think its related to my issue?

**Comment by brentvatne** [comment]
i have no idea but unless you can provide a reproducible example we cannot help you. please create a new issue when you have one to share and we would be happy to help

**Comment by matthamil** [comment]
Can you list your env info? React Native version, react-navigation version, etc.

**Comment by Sherif-Magdy** [comment]
This is my env: `"react": "16.6.1", "react-native": "0.57.7", "react-navigation": "3.5.1", "react-navigation-drawer": "^1.2.1", node-version:"v11.11.0", npm-version:"6.9.0"`

**Comment by Sherif-Magdy** [comment]
@matthamil please check this repo !! 
https://github.com/Sherif-Magdy/drawerLockModeIssue

**Comment by brentvatne** [comment]
@Sherif-Magdy - thanks! can you make a new issue and fill out the issue template along with sharing a link to that?
