### ISSUE TITLE
How do I check for a compatible version of react-native for each version of react-navigation?

### ISSUE THREAD

**Issue by chars1205** [react-navigation/react-navigation#5789]
I am using react-navigation v1 version, but I am going to update to the higher version, and I saw the doc and api of the website (https://reactnavigation.org/), but there was no compatible react-native version.

Do you have a react-native version that is compatible with each version of react-navigation?

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.5.11
| react-native     | 0.55.4
| node             | 10.15.0
| npm or yarn      | 6.8.0

**Comment by brentvatne** [comment]
we don't maintain a compatibility chart at the moment but perhaps we should. i would not recommend using v1 as it has lots of issues that have been resolved in v2 and v3, so you should update anyways.

**Comment by chars1205** [comment]
@brentvatne tankyou v3 updated and very good :)

**Comment by chars1205** [comment]
@brentvatne  tankyou v3 updated and very good :)
