### ISSUE TITLE
'enableURLHandling' missing from 'NavigationContainerProps' typescript defintion

### ISSUE THREAD

**Issue by jeffreyffs** [react-navigation/react-navigation#5793]
### Current Behavior

- Trying to disable url handling on the top level app container results in a typescript error
```
const AppContainer = createAppContainer(RootNavigator);
<AppContainer
  enableURLHandling={false}
/>
```

### Expected Behavior
- This prop should be available for typescript
https://github.com/react-navigation/react-navigation-native/blob/9c04ee979449aa0367a739563c08303b284a6a1d/src/createAppContainer.js#L139

I believe the typescript defintions can just be updated like so:
```
export interface NavigationContainerProps<S = {}, O = {}> {
    uriPrefix?: string | RegExp;
    enableURLHandling?: boolean;
    onNavigationStateChange?: (
      prevNavigationState: NavigationState,
      nextNavigationState: NavigationState,
      action: NavigationAction
    ) => void | null | undefined;
    navigation?: NavigationScreenProp<S>;
    persistenceKey?: string | null;
    renderLoadingExperimental?: React.ComponentType;
    screenProps?: any;
    navigationOptions?: O;
    style?: StyleProp<ViewStyle>;
  }
```

If this looks right, I can open a PR :)

| software         | version
| ---------------- | -------
| react-navigation | 3.6.0
| react-native     | 0.59.1
| node             | 10.15.1
| npm or yarn      | 6.4.1

**Comment by brentvatne** [comment]
looks good to me. might want to add a comment to indicate its purpose and that it defaults to true
