### ISSUE TITLE
Deep Linking not working on stackNavigator inside materialTopTabNavigator

### ISSUE THREAD

**Issue by drachyovmaxim** [react-navigation/react-navigation#5794]
Hi, been researching and trying for few days, but did't get an answer elsewhere. Plz help!

### Current Behavior
When i'm outside of materialTopTabNavigator tab, link myapp://order/:order_id works as expected. But when it's focused it's just returns to it's initial route name

### Expected Behavior
Navigate to the route in stack

### How to reproduce
This is simplified code that i use.
When i open myapp://news/list it opens from every page and even from closed app.
This link myapp://order/:order_id opens only if i away from Orders bottom navigator tab or disable createMaterialTopTabNavigator.

Here is simplified code:
```
const ChatStack = createStackNavigator(
  {
    ChatMain: {
      screen: Chat,
      navigationOptions: {
        header: null,
      },
    },
    ChatScreen: {
      screen: ChatScreen,
      path: 'list',
    }
  }
);

const HomeOrdersTopTabs = createMaterialTopTabNavigator(
  {
    MyOrders: MyOrders,
    Orders: Orders,
  },
  {
    lazy: true,
    initialRouteName: 'Orders',
  }
);

const OrderStack = createStackNavigator(
  {
    AllOrders: {
      screen: HomeOrdersTopTabs,
    },
    OrderProcess: {
      // this is a component which should open from Deep Linking
      screen: OrderProcess,
      path: ':order_id',
    }
  }
);

const HomeBottomTabs = createBottomTabNavigator(
  {
    Orders: {
      screen: OrderStack,
      path: 'order',
      navigationOptions: {
        title: 'Работа',
      }
    },
    Chat: {
      screen: ChatStack,
      path: 'news',
    },
  },
  {
    initialRouteName: 'Orders',
  }
);

const SimpleApp = createAppContainer(createSwitchNavigator(
  {
    WelcomeScreen: {
      screen: WelcomeScreen,
    },
    Registration: {
      screen: Registration,
    },
    Home: {
      screen: HomeBottomTabs,
      path: '',
    },
  },
  {
    initialRouteName: 'WelcomeScreen',
  }
));

const prefix = 'myapp://';

export default MainApp = () => <SimpleApp uriPrefix={prefix} />;
```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.3.2
| react-native        |  0.58.5
| npm or yarn        | yarn

**Comment by leesolway** [comment]
Did you manage to resolve this issue? I am experiencing something similar.

**Comment by Teal-labs-developer** [comment]
Did you find any solution for this?

**Comment by alexiri** [comment]
I was having this issue as well and it turned out to be #4820. I renamed things to avoid collisions and now it works as expected.
