### ISSUE TITLE
Change color of MaterialTopTabNavigator tab icons

### ISSUE THREAD

**Issue by spyshower** [react-navigation/react-navigation#5795]
### Current Behavior

I am trying to change the color of the tab icons in my MaterialTopTabNavigator. I tried playing with active/inactive tintColor but it's not working. Basically, I wanna make the inactive tabs more transparent.

TabNavigatorConfig:

```
{
    initialRouteName: 'Encountersscreen',

    tabBarPosition: 'bottom',
    swipeEnabled: false,
    animationEnabled: false,

    tabBarOptions: {
      activeTintColor: '#a649f2', // not working
      inactiveTintColor: 'red', // not working
      style: {
        paddingVertical: 6,
        backgroundColor: 'white',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: -3 },
        shadowOpacity: 0.13,
        shadowRadius: 5,
        elevation: 3,
      },
      indicatorStyle: {
        height: 0
      },
      showIcon: true,
      showLabel: false,

    },

  }
```

### Expected Behavior

The colors don't change.

I am not sure if this is a bug or I do something wrong. If it's a bug, let me know and I will upload a snack.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^3.6.1
| react-native     | expo 32.0.6
| node             | v10.15.3
| npm or yarn      | 6.8.0

**Comment by eriveltonelias** [comment]
Hi @spyshower, 

you need to do something like this https://snack.expo.io/@eriveltonelias/basic-creatematerialtoptabnavigator-icons

see this too on the docs: https://reactnavigation.org/docs/en/material-top-tab-navigator.html#docsNav

**Comment by spyshower** [comment]
@eriveltonelias I have seen the docs, I don't think there is anything I miss.

Also, I don't use Ion Icons, but custom SVGs. I could play with the SVG itself but is what I asked a bug or intended?

**Comment by eriveltonelias** [comment]
I don't think that is a bug with react-navigation :)

I used Ionicons as example, but you can return any React element https://reactnavigation.org/docs/en/material-top-tab-navigator.html#tabbaricon

**Comment by diamont1001** [comment]
you need to do something like this https://snack.expo.io/@eriveltonelias/basic-creatematerialtoptabnavigator-icons

```js
const Tab = createMaterialTopTabNavigator({
  Home,
  Profile
}, {
  tabBarOptions: {
    activeTintColor: 'red',
    inactiveTintColor: 'black',
    showIcon: true,
  },
  defaultNavigationOptions: ({ navigation }) => ({
      tabBarIcon: ({ focused, horizontal, tintColor }) => {
        const { routeName } = navigation.state;
        let IconComponent = Ionicons;
        let iconName;
        if (routeName === 'Home') {
          iconName = `ios-information-circle${focused ? '' : '-outline'}`;
        } else if (routeName === 'Profile') {
          iconName = `ios-options`;
        }

        return <IconComponent name={iconName} size={25} color={tintColor} />;
      },
    }),
});
```

the point is `tintColor`

**Comment by MinhajIMM** [comment]
Can you please tell me how you implement SVG in your project

**Comment by OmarOdaini** [comment]
`showIcon: true` fixed it for me. I feel like true should've been the default not false.
