### ISSUE TITLE
React Navigation as sub-navigator breaks layout of scroll view

### ISSUE THREAD

**Issue by DanForstinger** [react-navigation/react-navigation#5797]
### Current Behavior

I am attempting to nest a stack navigator within a dialog panel, and the layout doesn't seem to work properly. In the video attached, youll see how it laysout when i render the view directly, and then how it appears when inside a navigator. 

Further, I am unable to scroll my scroll view that is inside this page when using a stack navigator, although it works when i render the page directly.

Here is what it looks like when i render just the StartPartyPageView:
<img width="1403" alt="Screen Shot 2019-04-09 at 3 37 59 PM" src="https://user-images.githubusercontent.com/10439718/55834908-f4f32a00-5ae8-11e9-83c8-434cd587ea4d.png">

Here is what it looks like when i render the StartPartyPageView as a screen in a Stack Navigator:
<img width="1392" alt="Screen Shot 2019-04-09 at 3 38 17 PM" src="https://user-images.githubusercontent.com/10439718/55834909-f7558400-5ae8-11e9-921c-7ec11268dba3.png">

| software         | version
| ---------------- | -------
| react-navigation | 3.5.1
| react-native     | 0.59

**Comment by eriveltonelias** [comment]
hi! please make your code runnable either on https://snack.expo.io without any extraneous code

**Comment by brentvatne** [comment]
closing but please create a new issue with a reproducible example when you have the time, thanks!
