### ISSUE TITLE
HeaderBackButton not showing title prop

### ISSUE THREAD

**Issue by djorkaeffalexandre** [react-navigation/react-navigation#5798]
## Current Behavior

Hello, I'm working in Rocket.Chat.ReactNative Project and I'm implementing count of unread messages on headerBackButton, but my app does not show the title of HeaderBackButton Component.

On the use HeaderBackButton the prop 'title' doesn't work.

Expo Snack example:
[Expo-Navigation](https://snack.expo.io/@djorkaeff/headerbackbuttontitle)

Example:
```js
static navigationOptions = ({ navigation }) => {
  return {
    headerLeft: (
      <HeaderBackButton
        title='test'
        onPress={() => navigation.goBack()}
      />
    )
  };
}
```
![](https://i.imgur.com/KvOR2M2.png)

### Expected Behavior

I want to show the prop 'Title' in the right of the button.

### Your Environment

| software | version
| ---------------- | -------
| react-navigation | 3.3.2

**Comment by djorkaeffalexandre** [comment]
@brentvatne I opened this issue but you closed because I  didn't have  expo or code example, I created an example in expo and shared link in this issue. Regards, Djorkaeff.

**Comment by eriveltonelias** [comment]
Hi @djorkaeffalexandre, 

you can use the `headerBackTitle` prop ( check this on the docs https://reactnavigation.org/docs/en/stack-navigator.html#headerbacktitle )

I just updated your snack: https://snack.expo.io/@eriveltonelias/headerbackbuttontitle

**Comment by wolfag** [comment]
try this:
`title='test'` => `label='test'`
