### ISSUE TITLE
React Navigation StackNavigator

### ISSUE THREAD

**Issue by akisplays** [react-navigation/react-navigation#5799]
I get an error in these codes. I get an error when I write "createStackNavigator" instead of "StackNavigator". How do I update these codes.

https://github.com/spencercarli/getting-started-react-navigation/blob/master/app/config/router.js

`import React from 'react';
import { TabNavigator, StackNavigator } from 'react-navigation';
import { Icon } from 'react-native-elements';

import Feed from '../screens/Feed';
import Settings from '../screens/Settings';
import UserDetail from '../screens/UserDetail';
import Me from '../screens/Me';

export const FeedStack = StackNavigator({
  Feed: {
    screen: Feed,
    navigationOptions: {
      title: 'Feed',
    },
  },
  Details: {
    screen: UserDetail,
    navigationOptions: ({ navigation }) => ({
      title: `${navigation.state.params.name.first.toUpperCase()} ${navigation.state.params.name.last.toUpperCase()}`,
    }),
  },
});

export const Tabs = TabNavigator({
  Feed: {
    screen: FeedStack,
    navigationOptions: {
      tabBarLabel: 'Feed',
      tabBarIcon: ({ tintColor }) => <Icon name="list" size={35} color={tintColor} />,
    },
  },
  Me: {
    screen: Me,
    navigationOptions: {
      tabBarLabel: 'Me',
      tabBarIcon: ({ tintColor }) => <Icon name="account-circle" size={35} color={tintColor} />
    },
  },
});

export const SettingsStack = StackNavigator({
  Settings: {
    screen: Settings,
    navigationOptions: {
      title: 'Settings',
    },
  },
});

export const Root = StackNavigator({
  Tabs: {
    screen: Tabs,
  },
  Settings: {
    screen: SettingsStack,
  },
}, {
  mode: 'modal',
  headerMode: 'none',
});`

**Comment by eriveltonelias** [comment]
Hi @akisplays, 

you need to update your `react-navigation` to v3 ( the current is 3.6.1 ), `StackNavigator` has been deprecated in favor of `createStackNavigator`

this post will help you too https://reactnavigation.org/blog/2018/11/17/react-navigation-3.0.html

**Comment by akisplays** [comment]
<img width="1680" alt="Ekran Resmi 2019-04-10 15 27 12" src="https://user-images.githubusercontent.com/47142807/55878501-3e08b400-5ba5-11e9-8ac7-b57fbfab31c8.png">



`import React from 'react';
import { createBottomTabNavigator, createStackNavigator } from 'react-navigation';
import { Icon } from 'react-native-elements';

import Feed from '../screens/Feed';
import Settings from '../screens/Settings';
import UserDetail from '../screens/UserDetail';
import Me from '../screens/Me';

const FeedStack = createStackNavigator({
  Feed: {
    screen: Feed,
    navigationOptions: {
      title: 'Feed',
    },
  },
  Details: {
    screen: UserDetail,
    navigationOptions: ({ navigation }) => ({
      title: `${navigation.state.params.name.first.toUpperCase()} ${navigation.state.params.name.last.toUpperCase()}`,
    }),
  },
});

export const Tabs = createBottomTabNavigator({
  Feed: {
    screen: FeedStack,
    navigationOptions: {
      tabBarLabel: 'Feed',
      tabBarIcon: ({ tintColor }) => <Icon name="list" size={35} color={tintColor} />,
    },
  },
  Me: {
    screen: Me,
    navigationOptions: {
      tabBarLabel: 'Me',
      tabBarIcon: ({ tintColor }) => <Icon name="account-circle" size={35} color={tintColor} />
    },
  },
});

const SettingsStack = createStackNavigator({
  Settings: {
    screen: Settings,
    navigationOptions: {
      title: 'Settings',
    },
  },
});

const Root = createStackNavigator({
  Tabs: {
    screen: Tabs,
  },
  Settings: {
    screen: SettingsStack,
  },
}, {
  mode: 'modal',
  headerMode: 'none',
});
`

**Comment by akisplays** [comment]
> Hi @akisplays,
> 
> you need to update your `react-navigation` to v3 ( the current is 3.6.1 ), `StackNavigator` has been deprecated in favor of `createStackNavigator`
> 
> this post will help you too https://reactnavigation.org/blog/2018/11/17/react-navigation-3.0.html


<img width="1680" alt="Ekran Resmi 2019-04-10 15 27 12" src="https://user-images.githubusercontent.com/47142807/55878501-3e08b400-5ba5-11e9-8ac7-b57fbfab31c8.png">




`import React from 'react';
import { createBottomTabNavigator, createStackNavigator } from 'react-navigation';
import { Icon } from 'react-native-elements';

import Feed from '../screens/Feed';
import Settings from '../screens/Settings';
import UserDetail from '../screens/UserDetail';
import Me from '../screens/Me';

const FeedStack = createStackNavigator({
Feed: {
screen: Feed,
navigationOptions: {
title: 'Feed',
},
},
Details: {
screen: UserDetail,
navigationOptions: ({ navigation }) => ({
title: ${navigation.state.params.name.first.toUpperCase()} ${navigation.state.params.name.last.toUpperCase()},
}),
},
});

export const Tabs = createBottomTabNavigator({
Feed: {
screen: FeedStack,
navigationOptions: {
tabBarLabel: 'Feed',
tabBarIcon: ({ tintColor }) => ,
},
},
Me: {
screen: Me,
navigationOptions: {
tabBarLabel: 'Me',
tabBarIcon: ({ tintColor }) => 
},
},
});

const SettingsStack = createStackNavigator({
Settings: {
screen: Settings,
navigationOptions: {
title: 'Settings',
},
},
});

const Root = createStackNavigator({
Tabs: {
screen: Tabs,
},
Settings: {
screen: SettingsStack,
},
}, {
mode: 'modal',
headerMode: 'none',
});
`
