### ISSUE TITLE
HeaderBackButton title prop

### ISSUE THREAD

**Issue by djorkaeffalexandre** [react-navigation/react-navigation#5802]
# PROBLEM
I'm having problems, I need to set the back button title on screen two because on screen one I do not have access to the information I want to be shown in the title, I'm trying to use the prop title of the HeaderBackButton in version 3.6.1 of react-navigation but this isn't working.

## Current Behavior

Hello, I'm working in Rocket.Chat.ReactNative Project and I'm implementing count of unread messages on headerBackButton, but my app does not show the title of HeaderBackButton Component.

On the use HeaderBackButton the prop 'title' doesn't work.

Expo Snack example:
[Expo-Navigation](https://snack.expo.io/@djorkaeff/headerbackbuttontitle)

Example:
```js
static navigationOptions = ({ navigation }) => {
  return {
    headerLeft: (
      <HeaderBackButton
        title='test'
        onPress={() => navigation.goBack()}
      />
    )
  };
}
```
![](https://i.imgur.com/KvOR2M2.png)

### Expected Behavior

I want to show the prop 'Title' in the right of the button.

### Your Environment

| software | version
| ---------------- | -------
| react-navigation | 3.6.1

**Comment by brentvatne** [comment]
`backTitleVisible={true}`

**Comment by djorkaeffalexandre** [comment]
Thanks @brentvatne, love u.

**Comment by brentvatne** [comment]
we could probably make it default to true

**Comment by djorkaeffalexandre** [comment]
Would be great!
