### ISSUE TITLE
Modal wishlist

### ISSUE THREAD

**Issue by mschipperheyn** [react-navigation/react-navigation#5808]
react-native 3.5.1
@react-navigation/core 3.2.0
@react-navigation/web 1.0.0-alpha.7

My use case is: I'm coming from react-native and now I have to implement a react-native-web implementation based on it. My "mobile app" is implemented on part of the screen. The screen also contains other components. The modal implementation from react-navigation is far too limited to be able to use comfortably on a wider screen scenario. Here are some of the things I ran into. 

Initially, I implemented https://github.com/Dekoruma/react-native-web-modal/tree/master/packages/modal-enhanced-react-native-web 
It offers an experience that allows you to implement a modal that displays e.g. on a large screen as a centered box with a transparent background. It dropped the ball in one area though, it also applies the centered box with transparent background approach on a mobile screen, where you want pure full screen. But basically, it works.

So, I started looking at react-navigation. Also because I assumed that it would be better integrated with things like back button press, swipes, etc and I like to keep navigation logic centralized. Also, I like to use the default header with a back button on full screen mobile, but something more like a default modal header without back button on a desktop screen.

*First pass*
- I applied a modal stack and ran the app
- When I opened a modal, it behaved just like a normal screen, but no animation was applied (I expected bottom slide in)

*Second pass*
- I applied a contentComponent key on the modal stack, and applied a transparent wrapper that centered the children. No joy. Turns out, unlike the drawerNavigator, the stackNavigator doesn't use a contentComponent (why not? Would be great for analytics processing, customization etc)

*Third pass*
- i applied a wrapper on a per screen basis and set headerMode to `screen`. Kinda sucky bc it means duplication
- The header is full screen instead of modal width
- The wrapper does work, however, the Modal is contained to the area of the screen that contains the "mobile app" it doesn't do a full screen center. Only in the navigation area covered by `react-navigation`, I guess I have to make the wrapper fixed positioned but I already know this is a dead end
- There is no animation

So, at this point, I have to admit defeat. `react-navigation` modals are not yet ready for cross platform use. As a short term fix, I would recommend implementing contentComponent. This will allow use to create a fixed position wrapper and a centered flexbox which right away offers the basics.

Requirements for me:
- cross platform defaults (screen centered on web, full screen on mobile), with customization options (transparency colors, positioning (center, bottom, left, right, top), height width etc
- ideally screen width specific customization
- swipe close handling on mobile, click transparent area plus X for close on web, tablet mixed

**Comment by brentvatne** [comment]
moved this over to https://github.com/react-navigation/rfcs/issues/15

**Comment by brentvatne** [comment]
also i think based on what you are saying here you are using android? you should clarify the platform you have in mind. there is a gesture and slide in animation on ios with the `mode: 'modal'` in stack
