### ISSUE TITLE
Navigation navigating backwards automatically

### ISSUE THREAD

**Issue by wwwhatley** [react-navigation/react-navigation#5810]
### Current Behavior

After navigating to a particular view, the application is instantly routing BACKWARDS to the previous view. This is only happening on one view, and not any others.

### Expected Behavior

- Navigation should not be routing BACKWARDS automatically

### How to reproduce

- Happy to share the repo privately...

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^2.14.2
| react-native     | https://github.com/expo/react-native/archive/sdk-32.0.1.tar.gz
| node             | v11.9.0
| npm or yarn      | yarn 1.13.0

**Comment by brentvatne** [comment]
no private repos, you can re-create your issue and share a public repo if you like. also, please provide a repro on the latest version of react-navigation. thanks!

**Comment by prateekchachra** [comment]
+1
