### ISSUE TITLE
createStackNavigator Error

### ISSUE THREAD

**Issue by akisplays** [react-navigation/react-navigation#5812]
Where's the problem?
****
<img width="1680" alt="Ekran Resmi 2019-04-10 15 27 12" src="https://user-images.githubusercontent.com/47142807/55878501-3e08b400-5ba5-11e9-8ac7-b57fbfab31c8.png">

****
Project Files
[https://github.com/spencercarli/getting-started-react-navigation](url)
****

**router.js Update React-Navigation v3**

```
import React from 'react';
import { createBottomTabNavigator, createStackNavigator } from 'react-navigation';
import { Icon } from 'react-native-elements';

import Feed from '../screens/Feed';
import Settings from '../screens/Settings';
import UserDetail from '../screens/UserDetail';
import Me from '../screens/Me';

const FeedStack = createStackNavigator({
Feed: {
screen: Feed,
navigationOptions: {
title: 'Feed',
},
},
Details: {
screen: UserDetail,
navigationOptions: ({ navigation }) => ({
title: ${navigation.state.params.name.first.toUpperCase()} ${navigation.state.params.name.last.toUpperCase()},
}),
},
});

export const Tabs = createBottomTabNavigator({
Feed: {
screen: FeedStack,
navigationOptions: {
tabBarLabel: 'Feed',
tabBarIcon: ({ tintColor }) => ,
},
},
Me: {
screen: Me,
navigationOptions: {
tabBarLabel: 'Me',
tabBarIcon: ({ tintColor }) => 
},
},
});

const SettingsStack = createStackNavigator({
Settings: {
screen: Settings,
navigationOptions: {
title: 'Settings',
},
},
});

const Root = createStackNavigator({
Tabs: {
screen: Tabs,
},
Settings: {
screen: SettingsStack,
},
}, {
mode: 'modal',
headerMode: 'none',
});
```

| software         | version
| ---------------- | -------
| react-navigation | ^3.0.0"
| react-native     | 0.59.3
| node             | 10.15.3
| npm or yarn      | 1.13.0

**Comment by jarvisluong** [comment]
I think your stack navigators are fine, maybe you didn't import the root navigator correctly (check if you used default import instead of named import for example)

**Comment by akisplays** [comment]
> I think your stack navigators are fine, maybe you didn't import the root navigator correctly (check if you used default import instead of named import for example)

****
**index.js**
```
import React, { Component } from 'react';
import { Root, Tabs } from './config/router';

class App extends Component {
  render() {
    return <Root />;
  }
}

export default App;

```

**Comment by jarvisluong** [comment]
Can you also check the top level `App.js` file if it correctly imports the above `index.js`?

**Comment by akisplays** [comment]
> Can you also check the top level `App.js` file if it correctly imports the above `index.js`?


```
import {AppRegistry} from 'react-native';
import App from './app/index';
import {name as appName} from './app.json';

AppRegistry.registerComponent(appName, () => App);
```

**Comment by eriveltonelias** [comment]
> Project Files
> [https://github.com/spencercarli/getting-started-react-navigation](url)
> 

this repository is using the old version of react-navigation (which we do not support anymore, sorry). 

So I recommend you to create a new issue with **reproducible** example on https://snack.expo.io or git repro. 

I'll be happy to help you, thanks for understand.
