### ISSUE TITLE
How to  get  init params in getstateforaction

### ISSUE THREAD

**Issue by ceerqingting** [react-navigation/react-navigation#5813]
### Current Behavior

- What code are you running and what is happening?
   The app has several pages , some pages need to be logged in to open, some don't.   I want to
   config each page that whether need login in route config. but i can't get the init params in 
   getstateforaction
 

### Expected Behavior
  
- What do you expect should be happening?
     get init params in getstateforaction

```js
const MainNavigator = createStackNavigator({
  Home,
  Settings: createStackNavigator({ Setting: {
     screen: Setting,
     params: { auth : true}
  }})

const defaultGetStateForAction = MainNavigator.router.getStateForAction

MainNavigator.router.getStateForAction = (action, lastState) => {
  console.log(action)  
 //current  print   { type:  "Navigation/NAVIGATE" , routeName: "Setting"}
// i expect print    { type:  "Navigation/NAVIGATE" , routeName: "Setting", params: { auth: true }}
  return defaultGetStateForAction(action, lastState)
}

```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.3.2
| react-native     | 0.58.6
| node             | 11.9.0
| npm or yarn      | npm

**Comment by brentvatne** [comment]
> get init params in getstateforaction

what does this mean?

**Comment by ceerqingting** [comment]
> > get init params in getstateforaction
> 
> what does this mean? I think you are expecting to see the params that you define on the route config in some action?

yes, i want to see the params in getstateforaction, like this:

```
MainNavigator.router.getStateForAction = (action, lastState) => {
  console.log(action)  
 //current  print   { type:  "Navigation/NAVIGATE" , routeName: "Setting"}
// i expect print    { type:  "Navigation/NAVIGATE" , routeName: "Setting", params: { auth: true }}
  return defaultGetStateForAction(action, lastState)
}
```

**Comment by brentvatne** [comment]
it's not possible to access them there, but considering that this is all just defined statically you can just share some config

```js
const defaultParams = {
  Settings: { auth: true },
}

// use this in your navigator config and in getStateForAction
```

if you'd like to propose a change to how react-navigation works in order to support this then please do so at https://github.com/react-navigation/rfcs :)
