### ISSUE TITLE
Switch screen without flicker

### ISSUE THREAD

**Issue by robinv8** [react-navigation/react-navigation#5814]
### Current Behavior
![image](https://user-images.githubusercontent.com/12277531/56104582-f1d5bf00-5f6a-11e9-9946-308b2f8f5c52.png)

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.7.1
| react-native     | 0.59.4
| node             | 10.15.3
| yarn      | 1.15.2

**Comment by robinv8** [comment]
solved

**Comment by robinv8** [comment]
solved

**Comment by vnlebaoduy** [comment]
> solved

What is your solution ? Thanks ❤️
