### ISSUE TITLE
How can I change the style of TabNavigation.Item

### ISSUE THREAD

**Issue by quocanhckhd** [react-navigation/react-navigation#5817]
<TabNavigator>
					<TabNavigator.Item
						selected={this.state.selectedTab === 'signIn'}
						onPress={() => this.setState({ selectedTab: 'signIn' })}
						title="Đăng nhập"
						labelStyle={{ fontSize: 20 }}
					>
						<SignIn />
					</TabNavigator.Item>
					<TabNavigator.Item
						selected={this.state.selectedTab === 'signUp'}
						onPress={() => this.setState({ selectedTab: 'signUp' })}
						title="Đăng ký"
					>
						<SignUp />
					</TabNavigator.Item>
				</TabNavigator>

**Comment by brentvatne** [comment]
hi there! this is a question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.
