### ISSUE TITLE
createDrawerNavigator navigation prop does not incude replace function

### ISSUE THREAD

**Issue by d4rky-pl** [react-navigation/react-navigation#5822]
### Current Behavior

The navigation prop passed to `contentComponent` does not have `replace` function that should be available if drawer is nesting a stack navigator inside. Since running `navigation.navigate` will trigger the stack navigation properly, this is unexpected behaviour that makes abstracting navigation trickier.

### Expected Behavior

`navigation.replace` should be available in `navigation` prop from drawer navigator

### How to reproduce

```
const PageOne = ({ navigation }) => <Text onPress={() => navigation.replace('PageTwo')}>Go to PageTwo</Text>
const PageTwo = ({ navigation }) => <Text onPress={() => navigation.replace('PageOne')}>Go to PageOne</Text>

const Sidebar = ({ navigation }) => (
  <View>
    <Text onPress={() => navigation.replace('PageTwo')}>Go to PageTwo</Text>
    <Text onPress={() => navigation.replace('PageOne')}>Go to PageOne</Text>
  </View>
)

const routes = { PageOne, PageTwo }

const appNavigator = createStackNavigator(routes, { initialRouteName, 'PageOne' })

const hamburgerNavigator = createDrawerNavigator({
  App: appNavigator
}, {
  contentComponent: Sidebar,
  initialRouteName: 'App'
})
```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.8.1
| react-native     | 32.0.0 (Expo SDK 32)
| node             |10.15.1
| npm or yarn      |1.13.0

**Comment by brentvatne** [comment]
actions specific to a navigator are only available on routes belonging to that navigator and descendents of those routes. you can dispatch the action manually if you like with `StackActions.replace` https://reactnavigation.org/docs/en/stack-actions.html
