### ISSUE TITLE
How to change indicatorStyle in MaterialTopTabBar when switching between routes

### ISSUE THREAD

**Issue by Diyorbek** [react-navigation/react-navigation#5823]
The behavior I am going to achieve is setting different `activeTintColor`s for each tab of MaterialTopTabBar. I somehow managed to set different active colors for the tabs but couldn't make the indicator change its color accordingly.

I tried creating my own `tabBarComponent` but it was not good as the default tabBarComponent.
How can I achieve the expected behavior or is there any way to customize the library's own `tabBarComponent`?

 I have found several issues like mine here but unfortunately, they didn't work which I think probably because those issues were created before v3 and there some deprecated functions/components.

**Comment by brentvatne** [comment]
you can extend the built-in tab bar component and change it https://github.com/brentvatne/react-navigation-workshop-examples/blob/d90687777a95599a32e395f9e16aae642f5a8ee5/example/sections/MaterialTopTabs.js#L3-L48

**Comment by simonprovost** [comment]
@Diyorbek I tried to add something in forceInset and style but nothing happened. How have you done that please ?

**Comment by Diyorbek** [comment]
@simonprovost, what I have tried so far is rendering the built-in tab bar component with custom styles on `navigationStatus` change (using the code shared in the above link):

```
class MaterialTopTabBarWrapper extends React.Component {
  render() {
  const { index } = this.props.navigationState;
  const color =
    index === 0 ? Colors.theme : index === 1 ? Colors.blue : Colors.green;

    return (
      <SafeAreaView
        style={{ backgroundColor: '#2196f3' }}
        forceInset={{ top: 'always', horizontal: 'never', bottom: 'never' }}>
        <MaterialTopTabBar
          {...this.props}
          activeTintColor={color}
          indicatorStyle={{ backgroundColor: color }}
          style={{ backgroundColor: "#fff" }}
          inactiveTintColor={Colors.darkGrey}
        />
      </SafeAreaView>
    );
  }
}
```
It works very well when switching around pressing the tabs. But when you navigate via swipe, colors change with a little delay as the `navigationState` gets updated only when swipe is finished.
So it is not smooth enough.

**Comment by Diyorbek** [comment]
Well, I am not sure if I did it right but here is how I managed to make the colors change smoothly.
I dived in tothe library's source code and ejected out components that I needed.
I have created a new `MaterialTopTabBar` component based on the existing one: I have copied the source code and changed its methods.
I have used `renderIndicator` and `renderLabel` prop of `TabBar`(from `react-native-tab-view`) to override defaults.


```
/* MaterialTopTabBar.js */
...
import { SafeAreaView } from "react-navigation";
import { CustomTopTabBar } from "path/to/my/components";
...

class MaterialTopTabBarWrapper extends React.Component {
  render() {
    return (
      <SafeAreaView
        style={{ backgroundColor: "#fff" }}
        forceInset={{ top: "always", horizontal: "never", bottom: "never" }}
      >
        <CustomTopTabBar
          {...this.props}
          style={{ backgroundColor: "#fff" }}
          activeTintColor={color}
          inactiveTintColor={Colors.darkGrey}
        />
      </SafeAreaView>
    );
  }
}

```

```
/* CustomTopTabBar.js (copied from `react-navigation` library)*/
...
import { TabBar } from "react-native-tab-view";
import CrossFadeIcon from "./CrossFadeIcon"; // this component (for icon rendering) was ejected out from library source
...

const styles = {
  indicator: {
    position: "absolute",
    left: 0,
    bottom: 0,
    right: 0,
    height: 2
  },
  ...
};

export default class TabBarTop extends React.PureComponent {
  
  ...

  // modified renderLabel method
  _renderLabel = ({ route }) => {
    const {
      position,
      navigation,
      activeTintColor,
      inactiveTintColor,
      showLabel,
      upperCaseLabel,
      labelStyle,
      allowFontScaling
    } = this.props;

    if (showLabel === false) {
      return null;
    }

    const { routes } = navigation.state;
    const index = routes.indexOf(route);
    const focused = index === navigation.state.index;

    // Prepend '-1', so there are always at least 2 items in inputRange
    const inputRange = [-1, ...routes.map((x, i) => i)];

    // setting color for the each tab label
    const uniqueColor =
      index === 0 ? Colors.theme : index === 1 ? Colors.blue : Colors.green;

    const outputRange = inputRange.map(inputIndex =>
      inputIndex === index ? uniqueColor : inactiveTintColor
    );

    const color = position.interpolate({
      inputRange,
      outputRange: outputRange
    });

    const tintColor = focused ? activeTintColor : inactiveTintColor;
    const label = this.props.getLabelText({ route });

    if (typeof label === "string") {
      return (
        <Animated.Text
          style={[styles.label, { color }, labelStyle]}
          allowFontScaling={allowFontScaling}
        >
          {upperCaseLabel ? label.toUpperCase() : label}
        </Animated.Text>
      );
    }
    if (typeof label === "function") {
      return label({ focused, tintColor });
    }

    return label;
  };

  // didn't change this method as I am not using icons
  _renderIcon = ({ route }) => {...};

  // added this method (copied from the build-in component method)
  _renderIndicator = props => {
    const { position, width, navigationState } = props;

    // setting color for the each phase of the indicator, in my case I have 3 routes only
    const inputRange = [0, 1, 2];
    const outputRange = [Colors.theme, Colors.blue, Colors.green];

    const indicatorColor = position.interpolate({
      inputRange,
      outputRange
    });

    const translateX = Animated.multiply(
      Animated.multiply(
        position.interpolate({
          inputRange: [0, navigationState.routes.length - 1],
          outputRange: [0, navigationState.routes.length - 1],
          extrapolate: "clamp"
        }),
        width
      ),
      I18nManager.isRTL ? -1 : 1
    );
    return (
      <Animated.View
        style={[
          styles.indicator,
          {
            width,
            transform: [{ translateX }],
            backgroundColor: indicatorColor
          }
        ]}
      />
    );
  };

  render() {
    /* eslint-disable no-unused-vars */
    const { navigation, renderIcon, getLabelText, ...rest } = this.props;

    return (
      /* $FlowFixMe */
      <TabBar
        {...rest}
        navigationState={navigation.state}
        renderIcon={this._renderIcon}
        renderLabel={this._renderLabel}
        renderIndicator={this._renderIndicator}
      />
    );
  }
}

...

```

**Comment by johneyo** [comment]
`
import { useNavigationState } from "@react-navigation/native";

export default function App() {
  const index = useNavigationState((state) => state.index);
  const color = index === 0 ? primary : "blue";

  return (
    <Tab.Navigator
      tabBarOptions={{
        style: {
          backgroundColor: '#f5f5f5',
        },
        labelStyle: {
          fontSize: 10,
        },
        indicatorStyle: {
          // borderBottomColor: 'red',
          borderBottomWidth: 2,
          borderColor: color,
        },
        activeTintColor: 'red',
        inactiveTintColor: "lightgray",
      }}
    >
      <Tab.Screen name="A" component={a} />
      <Tab.Screen name="B" component={b} />
    </Tab.Navigator>
  );
}`

**Comment by GabrielDierks** [comment]
screenOptions={({ route }) => ({
        tabBarIndicatorStyle: {
          backgroundColor:
            route.name === "firstRoute" ? colors.primary : colors.secondary,
        },
    })}

**Comment by yasir128** [comment]
screenOptions={{
                tabBarLabelStyle: {
                    fontSize: Theme.txtTiny,
                    fontWeight: '500',
                },
                tabBarStyle: {
                    marginTop: Theme.hp('1%'),
                    borderTopWidth: 0,
                    elevation: 0,
                },
                tabBarActiveTintColor: Theme.secondary,
                tabBarInactiveTintColor: Theme.lightBlack,
            tabBarIndicatorStyle:{
                backgroundColor:Theme.secondary
            }
            }}
