### ISSUE TITLE
TypeError:undefined is not an object(evaluating `this._call Listeners.bind`)

### ISSUE THREAD

**Issue by Xiao-HuangShu** [react-navigation/react-navigation#5825]
## TypeError:undefined is not an object(evaluating `this._call Listeners.bind`)

I created an app and I get an error when I try to join react-Navigation.
TypeError:undefined is not an object(evaluating `this._call Listeners.bind`)
I followed the installation [instructions.](https://reactnavigation.org/blog/#installation)

versions：
"react-navigation": "^3.8.1"
"react-native-gesture-handler": "^1.1.0"
"react-native": "^0.59.5"
![f322c9aadef01e004f99bc03c077b32](https://user-images.githubusercontent.com/27752523/56331213-f47c2280-61bd-11e9-8361-2d6636df4951.jpg)

How should I solve this problem?

**Comment by brentvatne** [comment]
lots of answers to this on google :) https://www.google.com/search?&q=this._callListeners.bind

**Comment by arielweinberger** [comment]
Experiencing the same.

 I've read all other solutions posted here, on StackOverflow and on the Expo forum. Nothing seems to work.

**Comment by brentvatne** [comment]
sounds like the issue is the babel config there, so make sure you use the default one or that you know what you are doing if you change it. reset the cache and restart the packager `react-native start --reset-cache`

**Comment by Xiao-HuangShu** [comment]
@arielweinberger 
When I was desperate, I accidentally found this first ([](https://github.com/shooterRao/react-native-fruitStore/issues/5), and then he gave me a new address ([](https:// Github.com/facebook/react-native/issues/20588)), thank you very much, this man（@Thomazella）, he saved me, God, it looks like a babel problem, when I try it, it works, God bless

FIXED: added @babel/plugin-transform-flow-strip-types, placed first in plugins array in .babelrc
![image](https://user-images.githubusercontent.com/27752523/56409330-2d45f580-62ab-11e9-996d-eebfc1094a19.png)

I hope this problem I have encountered is useful to everyone.

**Comment by youngjuning** [comment]
This is really an unpleasant user experience. It is recommended that this be written in the document

**Comment by satya164** [comment]
The issue happens when you change your Babel configuration to something other than what React Native uses by default. The error itself comes from React Native. React Navigation just happens to use the API causing the error. It's not related to React Navigation otherwise.

**Comment by youngjuning** [comment]
I think you shirk your responsibility

**Comment by youngjuning** [comment]
![image](https://user-images.githubusercontent.com/13204332/58489925-d0d5d000-819e-11e9-9105-45b1d8dda482.png)

**Comment by Enalmada** [comment]
I read this thread and missed a [critical suggestion](https://github.com/react-navigation/react-navigation/issues/5825#issuecomment-484727104) from above so I just want to call it out again:
reset the cache and restart the packager react-native start --reset-cache or expo start -c

**Comment by Evan-Future** [comment]
> sounds like the issue is the babel config there, so make sure you use the default one (init a new project and copy it over) or that you know what you are doing if you change it. reset the cache and restart the packager `react-native start --reset-cache` or `expo start -c`

RN:0.59.10  use this method to solve

**Comment by SaphiraNgocThuy** [comment]
Hi, anybody still having this problem? I've got that problem 2 days ago after I restarted my mac

**Comment by jennmueng** [comment]
I ran into this issue as well, what fixed it was adding `@babel/plugin-transform-flow-strip-types` to `babel.config.js` and then running `react-native start --reset-cache` to get the packager to load the new babel config.

**Comment by Edweis** [comment]
`expo start -c` fixed my problem !

**Comment by tuando1993** [comment]
Fixed by adding @babel/plugin-transform-flow-strip-types to the end of the babel.config.js

**Comment by MarzV** [comment]
Confirm Fixed by adding @babel/plugin-transform-flow-strip-types to the end of the babel.config.js plugins

**Comment by youngjuning** [comment]
Fixed by adding @babel/plugin-transform-flow-strip-types to the end of the babel.config.js

**Comment by TaumuLu** [comment]
I found that adding` ['@ babel / plugin-proposal-class-properties', {loose: false}]` configuration in babel.config.js would produce the same problem

**Comment by doKill** [comment]
> @arielweinberger
> 
> Sorry, I didn't see your connection. It is 404, but my problem is solved and I hope it will be useful to you.
> 
> When I was desperate, I accidentally found this first [shooterRao/react-native-fruitStore#5](https://github.com/shooterRao/react-native-fruitStore/issues/5), and then he gave me a new address https:// Github.com/[facebook/react-native/issues/20588](https://github.com/facebook/react-native/issues/20588), thank you very much, this man（@Thomazella）, he saved me, God, it looks like a babel problem, when I try it, it works, God bless
> 
> FIXED: added @babel/plugin-transform-flow-strip-types, placed first in plugins array in babelrc.config.js
> ![image](https://user-images.githubusercontent.com/27752523/56409330-2d45f580-62ab-11e9-996d-eebfc1094a19.png)
> 
> I hope this problem I have encountered is useful to everyone.

amazing,big bro

**Comment by sanengineer** [comment]
in my case I change react-native-screens from 2.17.x to 2.15.2 and I use expo SDK 40.0.1

**Comment by zjizly** [comment]
> I ran into this issue as well, what fixed it was adding `@babel/plugin-transform-flow-strip-types` to `babel.config.js` and then running `react-native start --reset-cache` to get the packager to load the new babel config.

Thank you! you saved my day
