### ISSUE TITLE
App screen fades to blank when in app switcher

### ISSUE THREAD

**Issue by bryonCatalyst** [react-navigation/react-navigation#5829]
## The issue tracker is reserved for bug reports only.

If you have a question, feature request, or an idea for improving the library or its related tools, please try one of the following resources:

- [Read the documentation](https://reactnavigation.org/)
- [Post an issue to the website repository if you'd like to see a documentation change](http://github.com/react-navigation/website)
- [Post a feature request to Canny](https://react-navigation.canny.io/feature-requests)
- [Write a RFC if you have ideas for how to implement a feature request](https://github.com/react-navigation/rfcs)
- [Get help on Discord chat (#react-navigation on Reactiflux)](https://discord.gg/4xEK3nD) or [on StackOverflow](https://stackoverflow.com/questions/tagged/react-navigation)
- Search for your issue - it may have already been answered or even fixed in the development branch. However, if you find that an old, closed issue still persists in the latest version, you should open a new issue.

Bugs with react-navigation must be reproducible *without any external libraries that operate on it*. This means that if you are attempting to use Redux or MobX with it and you think you have found a bug, you must be able to reproduce it without Redux or MobX in this report. Redux related issues belong in [react-navigation-redux-helpers](https://github.com/react-navigation/react-navigation-redux-helpers), and we do not have any first-class integration with MobX at the moment.

---

### Current Behavior

- What code are you running and what is happening?
My Main app container has a BottomTabNavigator and I have several modal screens that are presented in different places in the app, all that stuff is working great - I am trying to see if there's a configuration change I need to make for this all to 'just work'. 

When the user sends the app to the background, the app screen 'fades' to a white screen. I'd like it to show the user's last active screen like most other apps. Can you think of what might be going on in my setup?
 
- Include a screenshot if it makes sense.

![Simulator Screen Shot - iPhone Xʀ - 2019-04-18 at 08 32 52](https://user-images.githubusercontent.com/49171610/56364760-fdb4c180-61b4-11e9-8529-4d6b11ea4970.png)

![Simulator Screen Shot - iPhone Xʀ - 2019-04-18 at 08 33 04](https://user-images.githubusercontent.com/49171610/56365565-bdeed980-61b6-11e9-9344-893e8a33b175.png)

### Expected Behavior

- What do you expect should be happening?
When app is displayed in the app switcher, I'd like to see the user's last active screen.

- Include a screenshot if it makes sense.

### How to reproduce

- You must provide a way to reproduce the problem. If you are having an issue with your machine or build tools, the issue belongs on another repository as that is outside of the scope of React Navigation.
- Either re-create the bug on [Snack](https://snack.expo.io) or link to a GitHub repository with code that reproduces the bug.
- Explain how to run the example app and any steps that we need to take to reproduce the issue from the example app.

### Your Environment

| software             | version
| ---------------- | -------
| react-navigation | 3.0.9
| react-native        | 0.57.8
| node                    |  v11.13.0
| npm or yarn        | npm 6.4.1

**Comment by brentvatne** [comment]
not related to react-navigation as far as i can tell, you might want to look into this problem in general, maybe your app is using too much memory

see screenshot here of 3 apps all using react-navigation for some proof

![IMG_3404](https://user-images.githubusercontent.com/90494/56377117-7e2bf000-61be-11e9-9491-dcc49cc93e2e.jpg)

**Comment by bryonCatalyst** [comment]
Thanks for your help, I'll keep digging...

**Comment by bryonCatalyst** [comment]
By the way, I discovered that a vendor-provided SDK was presenting a native blank preview screen that was hiding all of our UI on transition to background.  Problem solved!  Thanks again for your help - very happy with react navigation as a whole!

**Comment by brentvatne** [comment]
good to hear @bryonCatalyst! thank you for the follow up
