### ISSUE TITLE
disable swiping over specific components

### ISSUE THREAD

**Issue by OriginLive** [react-navigation/react-navigation#5831]
Hi, i'm trying to implement an app that's similar to what tinder has.
Basically you have most of the screen with a swiping picture, but i wish to disable swipeEnabled for some components only. Basically i want the app not to swipe left & right only on the field where the swipable card is, however i would still like to swipe left and right at the bottom or top where the card isn't present.
I believe swipeEnabled is global and i cannot change it for a single view component, i assume that's not intended?
Also, how would i go and implement a switch on top, as is in the aforementioned application? They have a toggle button that switches one of the screens.
Thanks!

**Comment by brentvatne** [comment]
hi there! this is a question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.
