### ISSUE TITLE
TypeError: TypeError: Cannot read property 'bind' of undefined

### ISSUE THREAD

**Issue by jakubikan** [react-navigation/react-navigation#5834]
Hi,

I have trouble running the latest react-navigation and I think there might be an issue there

### Current Behavior

![Screenshot_2019-04-19-09-54-00-268_de jaxxnet plalaty](https://user-images.githubusercontent.com/174327/56414207-2490f780-628a-11e9-9262-d43e07ff2dd0.png)

I also have deactivated all the redux stores on the components to check whether there is an issue

```jsx
class Application extends Component {
    render() {

        return (
            <Container>
            </Container>
        )

    }

}

const AppNavigator = createDrawerNavigator({
    Home: Application
});


export default createAppContainer(AppNavigator);
```

```
TypeError: TypeError: Cannot read property 'bind' of undefined

This error is located at:
    in DrawerLayout (at DrawerView.js:165)
    in DrawerView (created by Navigator)
    in Navigator (at createAppContainer.js:387)
    in NavigationContainer (at app.tsx:16)
    in RCTView (at View.js:45)
    in View (at app.tsx:15)
    in App (at App.tsx:46)
    in _default (at renderApplication.js:35)
    in RCTView (at View.js:45)
    in View (at AppContainer.js:98)
    in RCTView (at View.js:45)
    in View (at AppContainer.js:115)
    in AppContainer (at renderApplication.js:34)
```

### How to reproduce
I have followed the steps here

https://reactnavigation.org/docs/en/getting-started.html

### Your Environment
package.json
```json
{
  "name": "app",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "node node_modules/react-native/local-cli/cli.js run-android",
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "lodash": "^4.17.11",
    "moment": "^2.24.0",
    "native-base": "^2.12.1",
    "react": "16.8.3",
    "react-native": "0.59.5",
    "react-native-elements": "^1.1.0",
    "react-native-fbsdk": "^0.8.0",
    "react-native-firebase": "^5.3.1",
    "react-native-gesture-handler": "^1.1.0",
    "react-native-google-signin": "^1.2.3",
    "react-native-linear-gradient": "^2.5.4",
    "react-native-ui-kitten": "3.1.3",
    "react-native-vector-icons": "^6.4.2",
    "react-navigation": "^3.8.1",
    "react-redux": "^5.0.0",
    "react-redux-firebase": "^3.0.0-alpha.11",
    "recompose": "^0.30.0",
    "redux": "^4.0.1",
    "redux-select": "^3.5.2",
    "redux-thunk": "^2.3.0"
  },
  "devDependencies": {
    "@babel/core": "^7.4.3",
    "@babel/plugin-proposal-class-properties": "^7.4.0",
    "@babel/plugin-proposal-decorators": "^7.4.0",
    "@babel/plugin-proposal-export-namespace-from": "^7.2.0",
    "@babel/runtime": "^7.4.3",
    "@types/jest": "^24.0.11",
    "@types/react": "^16.8.13",
    "@types/react-native": "^0.57.45",
    "@types/react-native-fbsdk": "^0.6.3",
    "@types/react-redux": "^7.0.7",
    "@types/react-test-renderer": "^16.8.1",
    "@types/recompose": "^0.30.6",
    "babel-jest": "^24.7.1",
    "jest": "^24.7.1",
    "metro-react-native-babel-preset": "^0.53.1",
    "react-test-renderer": "16.8.6",
    "typescript": "^3.4.3"
  },
  "jest": {
    "preset": "react-native"
  }
}
```
node version: v11.14.0
npm version: 6.9.0

does somebody have a similar problem or knows how to solve it?

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!

**Comment by jakubikan** [comment]
@brentvatne i can understand this - but with expo I'm bound to an older version of react-native (0.57) 
currently im using the latest one (0.59) 

I cannot reproduce it with expo because it does not use the latest version of react-native. 

so you are not supporting the latest version of react-native yet?

**Comment by brentvatne** [comment]
> we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository.

you can share a snack or a github repo with a runnable example, either work

**Comment by jakubikan** [comment]
I found a workaround 
seems to be linked to this issue https://github.com/facebook/react-native/issues/22157

removing the decorators worked for me -> https://github.com/facebook/react-native/issues/22157#issuecomment-440825495

i guess this might be solved in future react-native releases

**Comment by brentvatne** [comment]
thanks for the follow up!

**Comment by oradkovsky** [comment]
Quite tough workaround (to remove decorators).
