### ISSUE TITLE
how can i connect two tabs to one screen

### ISSUE THREAD

**Issue by hamedrajabpour** [react-navigation/react-navigation#5835]
Hi Guys

I Gonna Use one Screen For Two Tabs
Ui Functionality Like Instagram Share Screen (Described Below )

The User Swipe Between Camera And Video Screen The Screen Dosen't Change But Tab Change Perfectly
And Two Tabs Use Just One Screen

I Searched on issues and internet but i didn't found any solution for this problem

Can Any One Help Me To Solve?

Best Regards

**Comment by brentvatne** [comment]
hi there! this is a question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.

https://reactnavigation.org/docs/en/bottom-tab-navigator.html#tabbaronpress
