### ISSUE TITLE
remove padding under icon in createBottomTabNavigator

### ISSUE THREAD

**Issue by shogo-takao** [react-navigation/react-navigation#5836]
Hi.
I use iPhone x Simulator.
Padding has occurred under Icon in createBottomTabNavigator
Please tell me how to remove this padding.

<img width="345" alt="スクリーンショット 2019-04-20 15 36 18" src="https://user-images.githubusercontent.com/13826178/56453777-2342f600-6382-11e9-9394-65ac3b92b06f.png">

```
const Tab = createBottomTabNavigator(
  {
    Home: {
      screen: HomeStatic,
      navigationOptions: {
        tabBarLabel: () => {
          return null;
        },
        tabBarIcon: ({ focused }: TabProps) => (
          <TabBarIcon
            focused={focused}
            name={Platform.OS === "ios" ? "ios-home" : "md-home"}
          />
        )
      }
    },
    ...
    ...
    ...
  },
  {
    tabBarOptions: {
      style: {
        backgroundColor: "#000011",
        borderTopWidth: 1,
        borderTopColor: "#D3D3D3"
      }
    }
  }
);

export default Tab;
```

Thanks.

**Comment by mvolkmann** [comment]
I think this will look better if you add this to your `tabBarOptions`:
```js
    style: {backgroundColor: 'black'},
```
But I agree that you shouldn't have to do this.

**Comment by mvolkmann** [comment]
Here is what happens to me when I set the following tab options:

```js
  tabBarOptions: {
    activeBackgroundColor: 'green',
    activeTintColor: 'white', // defaults to light blue
    inactiveBackgroundColor: 'blue',
    inactiveTintColor: 'white', // defaults to gray
    labelStyle: {
      fontSize: 18
    },
    style: {
      backgroundColor: 'blue' // needed for color to go to bottom
      //paddingBottom: 10
    }
  }
```
<img width="409" alt="Screen Shot 2019-04-21 at 10 33 17 AM" src="https://user-images.githubusercontent.com/79312/56472188-fdb8f980-6420-11e9-935d-8ac302b77a50.png">

I want the green background on the active button to go all the way to the bottom.

**Comment by shogo-takao** [comment]
Thank you for answer.
I forgot the setting of `SafeAreaView`.
It worked after adding `forceInset = {{top: "always", bottom: "never"}}`.
Thank you!

**Comment by mvolkmann** [comment]
@shogo-takao Can you share the code you used that worked?

**Comment by shogo-takao** [comment]
@mvolkmann 
OK!
It is the correspondence part in this issue.

It's padding code
```
import * as React from "react";
import { SafeAreaView } from "react-navigation";

class App extends React.Component {
  render() {
    return (
      <SafeAreaView style={{ flex: 1 }}>
        <AppNavigator />
      </SafeAreaView>
    )
  }
}
```

It's worked
```
import * as React from "react";
import { SafeAreaView } from "react-navigation";

class App extends React.Component {
  render() {
    return (
      <SafeAreaView
        style={{ flex: 1 }}
        forceInset={{ top: "always", bottom: "never" }}
      >
        <AppNavigator />
      </SafeAreaView>
    )
  }
}
```
AppNavigator is `createAppContainer(createBottomTabNavigator(...))`

Above createBottomTabNavigator has not changed :r

**Comment by cglacet** [comment]
I confirm that removing bottom inset does solve the issue but that's a bit disturbing. Any idea what is going on?

Note: if you are using [react-native-safe-area-context](https://github.com/th3rdwave/react-native-safe-area-context) you should use the following:

```diff
<SafeAreaView 
+    edges={['right', 'top', 'left']}
>
    < AppNavigator />
</SafeAreaView>
```

**Comment by raajnadar** [comment]
Never wrap the root file with SafeAreaView always wrap the required screen only

https://reactnavigation.org/docs/handling-safe-area/

**Comment by RemyNtshaykolo** [comment]
<Tab.Navigator
      initialRouteName="Exercice"
      safeAreaInsets={{bottom: 0}}
      ...
>

**Comment by ajimae** [comment]
> <Tab.Navigator initialRouteName="Exercice" safeAreaInsets={{bottom: 0}} ...
> 
> >

This worked for me on v6.x

**Comment by ser-emejia** [comment]
> <Tab.Navigator initialRouteName="Exercice" safeAreaInsets={{bottom: 0}} ...
> 
> >

Thank you, it works :)

**Comment by Ashutosh002** [comment]
> <Tab.Navigator initialRouteName="Exercice" safeAreaInsets={{bottom: 0}} ...
> 
> >

Worked for me, Thanks.

**Comment by oliseonwu** [comment]
Hey guys, I found another way that works. I just set the tabbar style padding buttom to zero in the layout file:

tabBarStyle: {
          paddingBottom: 0, // Remove the bottom padding to remove the white space
        },
