### ISSUE TITLE
param is not an object. (evaluating ''__isnative' in param')

### ISSUE THREAD

**Issue by IlinIgor** [react-navigation/react-navigation#5837]
I have this issue when I use createStackNavigator. How can I fix it?

  react-native: 0.59.4
  react-navigation: 3.8.1
  react-native-gesture-handler: 1.1.0 (Tried to use the latest version, it helps to fix this issue but then the navigation doesn't work at all)

![Simulator Screen Shot - iPhone X - 2019-04-21 at 21 42 52](https://user-images.githubusercontent.com/18753770/56474200-266fdc00-647f-11e9-906f-68f1c545c2db.png)

**Comment by flpms** [comment]
@IlinIgor You solved this problem? 

I found a similar error

**Comment by IlinIgor** [comment]
@flpms I solved it removing some subspecs in my podfile
![image](https://user-images.githubusercontent.com/18753770/56502179-27098080-651a-11e9-86db-7ce327bc3143.png)

**Comment by flpms** [comment]
Great! Help me a lot :)
