### ISSUE TITLE
drawerOption initialRouteName not working?

### ISSUE THREAD

**Issue by mvolkmann** [react-navigation/react-navigation#5838]
### Current Behavior

I created a basic demo of using `createDrawerNavigator`.
The `drawerOption` `initialRouteName` seems to be ignored.

### Expected Behavior

It should start with the `Home` screen rendered,
but instead starts with the `About` screen rendered.

### How to reproduce

- `git clone https://github.com/mvolkmann/react-navigation-drawer-demo`
- `npm install`
- `npm start`
- choose "Run on iOS simulator"
- note that the initial drawer screen displayed is `About`, not `Home`

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.8.1
| react-native     | Expo version sdk-32.0.0
| node             | 8.15.0
 npm or yarn      | npm 6.9.0

**Comment by brentvatne** [comment]
```
const drawerOptions = {
  initialRouteName: 'Home' //TODO: NOT WORKING!
};
const DrawerNav = createDrawerNavigator(
  {About, Home, Settings},
  {drawerOptions}
);
```

this should be

```
const drawerOptions = {
  initialRouteName: 'Home' //TODO: NOT WORKING!
};
const DrawerNav = createDrawerNavigator(
  {About, Home, Settings},
  drawerOptions
);
```

what you had before passes in an options object `{drawerOptions: { initialRouteName: '..' }}` in the second param rather than `{ initialRouteName: '...' }`

**Comment by mvolkmann** [comment]
Thanks so much @brentvatne! I should have caught that one.
