### ISSUE TITLE
Deep links which open the app also navigate to initial route

### ISSUE THREAD

**Issue by sesterki** [react-navigation/react-navigation#5844]
### Current Behavior

When I tap on a deep link when the app is closed/killed, the app opens and navigates to both the Initial Route screen and the screen the deep link specifies. The initial route navigation params does not have the data from the deep link. This is a problem because my Initial Route screen does some auth to check if the user is logged in, and then navigates to one of two other screens. This happens after the deep link screen is loaded, and so the app briefly displays the deep linked screen, and then navigates away.

### Expected Behavior

The app should behave as it does when it is open but backgrounded. The initialroute should not get hit and the app should only navigate to the deep linked screen.

### How to reproduce
I created a repo to demo this bug: https://github.com/sesterki/react-navigation-deep-link-bug
I listed the steps in the readme but:
1. Clone the repo, and launch the app with expo
2. Note the uriPrefix that is printed out when the app starts
3. Test [uriPrefix]/Main/one and [uriPrefix]/Main/two and note how each screen only prints (during render) once when it is opened.
4. Close/kill the app
5. Test [uriPrefix]/Main/two and note how both HomeScreen (one) and LinksScreen(two) render and print.

Again my expectation is that only LinksScreen would render.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.9.0 
| react-native     | 16.5.0
| node             | 10.11.0
| npm or yarn      | 6.4.1

**Comment by brentvatne** [comment]
https://github.com/react-navigation/react-navigation-native/pull/12 would resolve this

**Comment by sesterki** [comment]
I can't really find a good explanation anywhere, but what is the difference between "React Navigation" and "React Navigation Native" (Can I just sub react-navigation-native in my package.json or will I need to make a lot of changes)?

**Comment by brentvatne** [comment]
https://github.com/react-navigation/react-navigation/blob/bd2daa809f68badb6e4a8b111d47f8cac998b2b4/package.json#L38-L43

it's just a way of splitting up react-navigation into smaller packages that handle separate concerns

**Comment by aivantg** [comment]
Is there any recommendations for a temporary solution to this issue until the PR is merged in? Would there be a way for the Initial Screen to know whether a deep link just happened and be sure not to react to it?

**Comment by changLiuUNSW** [comment]
Is there a workaround right now?

**Comment by marian37** [comment]
I have similar issue. 
Is there any temporary solution? 
When is new release (v4) expected?

**Comment by rayzeller** [comment]
I was able to handle deep linking with `react-navigation 3.11.0` using this method. this is a stripped down version.

our stack uses a `Loading` screen that will reroute to the Authenticated stack. deep linking is only handled by the auth stack in our scenario.

https://gist.github.com/rayzeller/63b829a9f72f734df15e002587563776

**Comment by sadeghhosseini** [comment]
I have encountered the same issue. I'm using `react-native: 0.59.5` and `react-navigation: 4.0.0` and `node: v10.15.3`.
Is this a bug?
How can I fix this?

**Comment by sadeghhosseini** [comment]
> I have encountered the same issue. I'm using `react-native: 0.59.5` and `react-navigation: 4.0.0` and `node: v10.15.3`.
> Is this a bug?
> How can I fix this?

This is how I fixed it. I just had to 

> Set launchMode of MainActivity to singleTask in order to receive intent on existing MainActivity.
as the [document ](https://reactnavigation.org/docs/en/deep-linking.html) suggests.

**Comment by satya164** [comment]
https://github.com/react-navigation/react-navigation/issues/2554
