### ISSUE TITLE
React Navigation 2.0 createDrawerNavigator animation slide left to right

### ISSUE THREAD

**Issue by michaelVictoriaDev** [react-navigation/react-navigation#5845]
I'm using react navigation 2.0 and using the docs in createDrawerNavigator. How can i create like this animation, well before that i created that is in RNRF now I want to migrate to react navigation 2.0 
![ezgif-4-f686cbad4bb0](https://user-images.githubusercontent.com/44763288/56706173-906dd700-6746-11e9-9eba-2c521a0bd060.gif)

**Comment by eriveltonelias** [comment]
hi there! this is a question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.
