### ISSUE TITLE
onNavigationStateChange is not working properly

### ISSUE THREAD

**Issue by kiano0sh** [react-navigation/react-navigation#5847]
I'm trying to track screen changes in my application so i can say when to show my `GlobalFooter` component but after logging to my application (from this point screen changes to index 1) there's some kind of loop i guess that occurred (or maybe it's just because of re-render) and suddenly my CPU usage go above 70% (all 8 core) then the app crashes! Here's my code:

./App.js
```js
import React from 'react';
import {ApolloProvider} from "react-apollo";
import {client} from "./ApolloClient";
import {ThemeProvider} from 'react-native-elements';
import Navigations from './Navigations'
import GlobalFooter from './GlobalFooter'


class App extends React.Component {
    constructor(props, context) {
        super(props)
        this.state = {
            isFooter: false
        };
    }

    handleNavigationChange = (prevState, newState, action) => {
        if (newState.index === 1) {
            this.setState({isFooter: true})
        } else {
            this.setState({isFooter: false})
        }
    };

    render() {
        const {isFooter} = this.state;
        return (
            <ApolloProvider client={client}>
                <ThemeProvider>
                    <Navigations ref={nav => {this.navigation = nav}}
                                 onNavigationStateChange={this.handleNavigationChange}
                    />
                    {console.log(isFooter)}
                    {isFooter ? <GlobalFooter navigation={this.navigation}/> : null}
                </ThemeProvider>
            </ApolloProvider>
        )
    }
}

export default App
```

It's worth to mention that this behavior just occurred at logging and if i add `onNavigationStateChange` part after I'm logged in it just works perfectly fine.
### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  `3.6.1`
| react-native     | `0.59.2`
| node             | `11.14.0`
| yarn      | `1.15.2`

**Comment by eriveltonelias** [comment]
hi! please make your code runnable either on https://snack.expo.io without any extraneous code

**Comment by eriveltonelias** [comment]
I'll close the issue for now, but you can add the repro to the original post and then ping me and I'll reopen to investigate. Thanks for understanding.
