### ISSUE TITLE
How can I know on HomeScreen that the Back button was clicked?

### ISSUE THREAD

**Issue by teradopingad** [react-navigation/react-navigation#5848]
```
const HomeStack = () => createStackNavigator(
 {
  Home: {screen: HomeScreen},
  Share: {screen: ShareScreen}
 }
};
```

After moving to ShareScreen on HomeScreen and then click Back button. 
How can I know on HomeScreen that the Back button was clicked?

**Comment by eriveltonelias** [comment]
hi @teradopingad,

https://reactnavigation.org/docs/en/custom-android-back-button-handling.html#docsNav
