### ISSUE TITLE
React Navigation support useEffect Hook? Error callback is not a function

### ISSUE THREAD

**Issue by cassubianApp** [react-navigation/react-navigation#5851]
I have a problem with the useEffect hook in React Native. When I next navigate to the component with useEffect I get following error : callback is not a function.

https://github.com/cassubianApp/react-navigation-test

it looks like the hook is calling, but right after that it gets a bug. Could this be a problem with my configuration or if React Navigation does not support hooks

react-navigation 3.9
react-native 0.59

**Comment by jeveloper** [comment]
did you get it figured out? feel free to share

**Comment by sedenardi** [comment]
Also seeing this issue with navigating to components that implement `useEffect`.

```
callback is not a function. (In 'callback()', 'callback' is 3)

flushFirstCallback
    scheduler.development.js:107:35
flushWork
    scheduler.development.js:219:28
_flushCallback
    scheduler.development.js:522:18
_callTimer
    JSTimers.js:152:14
callTimers
    JSTimers.js:414:17
__callFunction
    MessageQueue.js:366:47
<unknown>
    MessageQueue.js:106:26
__guard
    MessageQueue.js:314:10
callFunctionReturnFlushedQueue
    MessageQueue.js:105:17
callFunctionReturnFlushedQueue
    [native code]:0
```

**Comment by rafgoncalves** [comment]
I'm getting the same behaviour here. It doesn't matter what's the effect even useEffect(() => null, []) crashes

**Comment by ryleyrandall22** [comment]
Getting the same issue. Has anyone figured out a solution?
