### ISSUE TITLE
Allow disable some tabs

### ISSUE THREAD

**Issue by rabindrachhachan** [react-navigation/react-navigation#5852]
My use case is that based on  user's permission profile, he has access to 2 tabs and the other 2 should be grayed out and disabled (no press handler). We don't want to hide the tabs, only disable some, because we want them to transition to grayed out tab after he has the required permission profile.So every time app is open , i will fetch the permission profile and dynamically enable/disable these tab

I don't see any way to disable some specific tabs on react-navigation.
I see it's possible to change icon colour on active, but not disable the press handler.

**Comment by eriveltonelias** [comment]
hi there! this is a question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.

**Comment by jatrijori** [comment]
@rabindrachhachan did you find out how to do it? I want to do the same thing that you explained but I did not find how to do it :(

**Comment by eriveltonelias** [comment]
might be this can help https://snack.expo.io/@eriveltonelias/defaulthandler-with-valid-routes

**Comment by jatrijori** [comment]
@eriveltonelias thanks for the example! it worked
