### ISSUE TITLE
[Bug][3.9.1][iOS] App crashes on launch release build

### ISSUE THREAD

**Issue by kesha-antonov** [react-navigation/react-navigation#5854]
Hey guys!

I used version ```3.9.0``` and build was launching.
After upgrade to version ```3.9.1``` app crashes on launch.

Logs: 
```
2019-04-26 15:28:54.163 [fatal][tid:com.facebook.react.ExceptionsManagerQueue] Unhandled JS Exception: TypeError: TypeError: undefined is not an object (evaluating 't.default')
```

I fixed it by adding
```
"resolutions": {
    "@react-navigation/core": "3.4.0",
    "@react-navigation/native": "3.4.0"
  },
```
to ```package.json```

Seems like problem in ```3.4.1``` versions of core & native.

### Current Behavior

App crashes in release build.

### Expected Behavior

App should not crash in release build.

### How to reproduce

Update any app with RN-navigation to ```3.9.1``` and build release.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.9.0
| react-native     | 0.59.5
| node             | v10.15.0
| yarn      | 1.15.2

**Comment by brentvatne** [comment]
can you give more information, perhaps through sentry or something that can include a stacktrace?

**Comment by brentvatne** [comment]
cc @satya164

**Comment by kesha-antonov** [comment]
I think this is related https://github.com/react-navigation/react-navigation-core/commit/c507374a476955dbbda6fa81db943a73c9f45e62

**Comment by brentvatne** [comment]
could be! let us know if you end up being able to provide more context around the error. @satya164 will investigate when he's back from vacation, and it'll help him a lot to have a stacktrace

**Comment by kesha-antonov** [comment]
Sure
I'll try to provide more info but that's all I was getting
Other lines very similarly complaining about ```evaluating 't.default'```

**Comment by satya164** [comment]
Can you provide a repro?

**Comment by yasgreen93** [comment]
I have the same issue on 3.9.0 and 3.9.1. Here is the error I get:
![Screenshot 2019-05-05 at 11 10 53](https://user-images.githubusercontent.com/15678246/57192275-8a39e080-6f26-11e9-8f94-819d864036d5.png)

What I have in `package.json`:
```
    "dependencies": {
        "babel-preset-react-native": "^4.0.1",
        "moment": "^2.24.0",
        "prettier": "^1.16.2",
        "prop-types": "^15.6.2",
        "react": "16.6.3",
        "react-native": "0.58.3",
        "react-native-gesture-handler": "^1.0.15",
        "react-native-iphone-x-helper": "^1.2.0",
        "react-native-keyboard-aware-scroll-view": "^0.8.0",
        "react-native-linear-gradient": "^2.5.3",
        "react-native-snap-carousel": "^3.7.5",
        "react-native-vector-icons": "^6.2.0",
        "react-navigation": "3.9.0"
    },
    "devDependencies": {
        "@babel/core": "^7.4.4",
        "@babel/plugin-proposal-class-properties": "^7.4.4",
        "@babel/plugin-proposal-decorators": "^7.4.4",
        "@babel/plugin-transform-classes": "^7.4.4",
        "@babel/plugin-transform-flow-strip-types": "^7.4.4",
        "babel-eslint": "^10.0.1",
        "babel-jest": "^24.7.1",
        "eslint": "^5.12.1",
        "eslint-config-airbnb": "^17.1.0",
        "eslint-config-prettier": "^4.0.0",
        "eslint-plugin-import": "^2.16.0",
        "eslint-plugin-jsx-a11y": "^6.2.0",
        "eslint-plugin-prettier": "^3.0.1",
        "eslint-plugin-react": "^7.13.0",
        "jest": "24.0.0",
        "metro-react-native-babel-preset": "0.51.1",
        "react-test-renderer": "16.6.3"
    },
```

What I have in `babel.config.js`:
```module.exports = (api) => {
    api.cache(true);

    return {
        presets: ['module:metro-react-native-babel-preset'],
        plugins: [
            ['@babel/plugin-proposal-class-properties', { loose: true }],
            ['@babel/plugin-transform-classes', { loose: true }],
            ['@babel/plugin-proposal-decorators', { legacy: true }],
            '@babel/plugin-transform-flow-strip-types',
        ],
    };
};
```

I've even tried downgrading to `2.13.0` from an answer in this stack post https://stackoverflow.com/questions/54833668/typeerror-undefined-is-not-an-object-evaluating-this-calllisteners-bind, but I just get a different error.

**Comment by satya164** [comment]
@yasgreen93 that looks like something else, see #5350

Metro cache is very flaky. Try running `yarn start --reset-cache` to ensure that there are no issues due to caching.

**Comment by Boatly** [comment]
> I have the same issue on 3.9.0 and 3.9.1. Here is the error I get:
> ![Screenshot 2019-05-05 at 11 10 53](https://user-images.githubusercontent.com/15678246/57192275-8a39e080-6f26-11e9-8f94-819d864036d5.png)
> 
> What I have in `package.json`:
> 
> ```
>     "dependencies": {
>         "babel-preset-react-native": "^4.0.1",
>         "moment": "^2.24.0",
>         "prettier": "^1.16.2",
>         "prop-types": "^15.6.2",
>         "react": "16.6.3",
>         "react-native": "0.58.3",
>         "react-native-gesture-handler": "^1.0.15",
>         "react-native-iphone-x-helper": "^1.2.0",
>         "react-native-keyboard-aware-scroll-view": "^0.8.0",
>         "react-native-linear-gradient": "^2.5.3",
>         "react-native-snap-carousel": "^3.7.5",
>         "react-native-vector-icons": "^6.2.0",
>         "react-navigation": "3.9.0"
>     },
>     "devDependencies": {
>         "@babel/core": "^7.4.4",
>         "@babel/plugin-proposal-class-properties": "^7.4.4",
>         "@babel/plugin-proposal-decorators": "^7.4.4",
>         "@babel/plugin-transform-classes": "^7.4.4",
>         "@babel/plugin-transform-flow-strip-types": "^7.4.4",
>         "babel-eslint": "^10.0.1",
>         "babel-jest": "^24.7.1",
>         "eslint": "^5.12.1",
>         "eslint-config-airbnb": "^17.1.0",
>         "eslint-config-prettier": "^4.0.0",
>         "eslint-plugin-import": "^2.16.0",
>         "eslint-plugin-jsx-a11y": "^6.2.0",
>         "eslint-plugin-prettier": "^3.0.1",
>         "eslint-plugin-react": "^7.13.0",
>         "jest": "24.0.0",
>         "metro-react-native-babel-preset": "0.51.1",
>         "react-test-renderer": "16.6.3"
>     },
> ```
> 
> What I have in `babel.config.js`:
> 
> ```
>     api.cache(true);
> 
>     return {
>         presets: ['module:metro-react-native-babel-preset'],
>         plugins: [
>             ['@babel/plugin-proposal-class-properties', { loose: true }],
>             ['@babel/plugin-transform-classes', { loose: true }],
>             ['@babel/plugin-proposal-decorators', { legacy: true }],
>             '@babel/plugin-transform-flow-strip-types',
>         ],
>     };
> };
> ```
> 
> I've even tried downgrading to `2.13.0` from an answer in this stack post https://stackoverflow.com/questions/54833668/typeerror-undefined-is-not-an-object-evaluating-this-calllisteners-bind, but I just get a different error.

Hi Yasmin,

I have the same issue and haven't been able to resolve it.  Did you find a resolution for this error?

Thanks,
Peter

**Comment by satya164** [comment]
The error with `callListeners.bind` happens because of one of these plugins:

```js
['@babel/plugin-proposal-class-properties', { loose: true }],
['@babel/plugin-transform-classes', { loose: true }],
```

Here you're specifying `loose: true` which will produce non spec-compliant code. You need to remove them and run `react-native start --reset-cache`

**Comment by satya164** [comment]
Regarding this issue, I'm closing it since no repro was provided. If you have a repro for the issue, please comment here or open a new issue.

**Comment by kesha-antonov** [comment]
Found problem

Here's my `babel.config.js`
```
module.exports = function (api) {
  api.cache(true)

  return ({
    "presets": [
      "module:metro-react-native-babel-preset",
    ],
    "plugins": [
      "@babel/plugin-transform-flow-strip-types",
      ["@babel/plugin-proposal-decorators", { "legacy": true }],
      ["@babel/plugin-proposal-class-properties", { "loose" : true }],
      [
        "@babel/plugin-transform-runtime",
        {
          "helpers": true,
          "regenerator": false
        }
      ]
    ],
    "env": {
      "production": {
        "plugins": [
          "transform-remove-console",
          [
            "transform-react-remove-prop-types", {
              "mode": "remove",
              "ignoreFilenames": ["node_modules"],
              "removeImport": true
            }
          ]
        ]
      }
    }
  })
}
```

If I remove `transform-react-remove-prop-types` build works fine

**Comment by VictorYuan666** [comment]
> Found problem
> 
> Here's my `babel.config.js`
> 
> ```
> module.exports = function (api) {
>   api.cache(true)
> 
>   return ({
>     "presets": [
>       "module:metro-react-native-babel-preset",
>     ],
>     "plugins": [
>       "@babel/plugin-transform-flow-strip-types",
>       ["@babel/plugin-proposal-decorators", { "legacy": true }],
>       ["@babel/plugin-proposal-class-properties", { "loose" : true }],
>       [
>         "@babel/plugin-transform-runtime",
>         {
>           "helpers": true,
>           "regenerator": false
>         }
>       ]
>     ],
>     "env": {
>       "production": {
>         "plugins": [
>           "transform-remove-console",
>           [
>             "transform-react-remove-prop-types", {
>               "mode": "remove",
>               "ignoreFilenames": ["node_modules"],
>               "removeImport": true
>             }
>           ]
>         ]
>       }
>     }
>   })
> }
> ```
> 
> If I remove `transform-react-remove-prop-types` build works fine

it is work for me!
