### ISSUE TITLE
official docs demo can't run correctly, why

### ISSUE THREAD

**Issue by xgqfrms** [react-navigation/react-navigation#5855]
## The issue tracker is reserved for bug reports only.

If you have a question, feature request, or an idea for improving the library or its related tools, please try one of the following resources:

- [Read the documentation](https://reactnavigation.org/)
- [Post an issue to the website repository if you'd like to see a documentation change](http://github.com/react-navigation/website)
- [Post a feature request to Canny](https://react-navigation.canny.io/feature-requests)
- [Write a RFC if you have ideas for how to implement a feature request](https://github.com/react-navigation/rfcs)
- [Get help on Discord chat (#react-navigation on Reactiflux)](https://discord.gg/4xEK3nD) or [on StackOverflow](https://stackoverflow.com/questions/tagged/react-navigation)
- Search for your issue - it may have already been answered or even fixed in the development branch. However, if you find that an old, closed issue still persists in the latest version, you should open a new issue.

Bugs with react-navigation must be reproducible *without any external libraries that operate on it*. This means that if you are attempting to use Redux or MobX with it and you think you have found a bug, you must be able to reproduce it without Redux or MobX in this report. Redux related issues belong in [react-navigation-redux-helpers](https://github.com/react-navigation/react-navigation-redux-helpers), and we do not have any first-class integration with MobX at the moment.

---

### Current Behavior

- What code are you running and what is happening?
- Include a screenshot if it makes sense.

### Expected Behavior

- What do you expect should be happening?
- Include a screenshot if it makes sense.

### How to reproduce

- You must provide a way to reproduce the problem. If you are having an issue with your machine or build tools, the issue belongs on another repository as that is outside of the scope of React Navigation.
- Either re-create the bug on [Snack](https://snack.expo.io) or link to a GitHub repository with code that reproduces the bug.
- Explain how to run the example app and any steps that we need to take to reproduce the issue from the example app.

***

https://reactnavigation.org/docs/en/getting-started.html

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^3.9.1
| react-native     | 0.59.5
| node             | v10.15.3
| npm or yarn      | 6.4.1 / 1.15.2

***

```json

{
    "name": "demo_android_app",
    "version": "0.0.1",
    "private": true,
    "scripts": {
        "start": "node node_modules/react-native/local-cli/cli.js start",
        "test": "jest"
    },
    "bin": {
        "app_cmd": "app.cmd",
        "app_bash": "app.sh"
    },
    "dependencies": {
        "react": "16.8.3",
        "react-native": "0.59.5",
        "react-native-gesture-handler": "^1.1.0",
        "react-navigation": "^3.9.1"
    },
    "devDependencies": {
        "@babel/core": "^7.4.3",
        "@babel/runtime": "^7.4.3",
        "babel-jest": "^24.7.1",
        "jest": "^24.7.1",
        "metro-react-native-babel-preset": "^0.53.1",
        "react-test-renderer": "16.8.3"
    },
    "jest": {
        "preset": "react-native"
    }
}


```

**Comment by xgqfrms** [comment]
# after change `MainActivity.java`, it can't render again

![image](https://user-images.githubusercontent.com/7291672/56860309-dbe2e800-69c7-11e9-9eb9-d5f0f4b38edc.png)

**Comment by xgqfrms** [comment]
# full demo codes can be find in this repo

https://github.com/xgqfrms/WNAAIO/tree/master/React-Native/demo_android_app

**Comment by xgqfrms** [comment]
# but the default is OK, why

```js

package com.demo_android_app;

import com.facebook.react.ReactActivity;
// react-native-gesture-handler for Android
import com.facebook.react.ReactActivityDelegate;
import com.facebook.react.ReactRootView;
import com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView;

public class MainActivity extends ReactActivity {

    /**
     * Returns the name of the main component registered from JavaScript.
     * This is used to schedule rendering of the component.
     */
    @Override
    protected String getMainComponentName() {
        return "demo_android_app";
    }
    // @Override
    // protected ReactActivityDelegate createReactActivityDelegate() {
    //     return new ReactActivityDelegate(this, getMainComponentName()) {
    //         @Override
    //         protected ReactRootView createRootView() {
    //             return new RNGestureHandlerEnabledRootView(MainActivity.this);
    //         }
    //     };
    // }
}


```

![image](https://user-images.githubusercontent.com/7291672/56860493-b1922a00-69c9-11e9-9008-bf0e9a375276.png)

**Comment by brentvatne** [comment]
sorry i don't really understand what's going on here. make sure you follow the instructions properly for installing react-native-gesture-handler.

**Comment by xgqfrms** [comment]
@brentvatne Could you try this demo

https://github.com/xgqfrms/React-Native-Tutorials/tree/master/demo_android_app
