### ISSUE TITLE
navigation.getChildNavigation is not a function

### ISSUE THREAD

**Issue by o-legvynenko** [react-navigation/react-navigation#5857]
Hello, I am integrating with Redux in react navigation project.

### Current Behavior

- What code are you running and what is happening?

```
// tabbar/index.js

import React, { Component } from 'react';
import { connect } from 'react-redux';
import { TabBar } from './config';

class TabBarNavigation extends Component {
  render() {
    const { dispatch, navigationState } = this.props;
    return (
      <TabBar
        navigation={{
          dispatch: dispatch,
          state: navigationState
        }}
      />
    );
  }
}

const mapStateToProps = (state) => {
  return {
    navigationState: state.tabBar
  }
}

export default connect(mapStateToProps)(TabBarNavigation);
```

```
// tabbar/config.js

import { createBottomTabNavigator } from 'react-navigation';

import FirstTabNavigation from './library';
import SecondTabNavigation from './create';
import ThirdTabNavigation from './get-inspired';
import ForthTabNavigation from './notification';
import FifthTabNavigation from './profile';

const routeConfiguration = {
  first: { screen: FirstTabNavigation },
  second: { screen: SecondTabNavigation },
  third: { screen: ThirdTabNavigation },
  forth: { screen: ForthTabNavigation },
  fifth: { screen: FifthTabNavigation }
}

const tabBarConfiguration = {
  tabBarOptions: {
    activeTintColor: 'red',
    inactiveTintColor: 'grey',
    labelStyle: {
      textTransform: 'uppercase',
      fontSize: 10
    },
    style: {
      backgroundColor: 'white',
      borderTopWidth: 0,
      shadowOffset: { width: 5, height: 3 },
      shadowOpacity: 0.5,
      elevation: 5
    },
    lazy: true
  }
}

export const TabBar = createBottomTabNavigator(routeConfiguration,tabBarConfiguration);

export const tabBarReducer = (state,action) => {
  if (action.type === 'JUMP_TO_TAB') {
    return { ...state, index: 0 }
  } else {
    return TabBar.router.getStateForAction(action,state)
  }
}
```

- Include a screenshot if it makes sense.

![Simulator Screen Shot - iPhone 6 - 2019-04-28 at 06 13 54](https://user-images.githubusercontent.com/48455672/56915883-7a288980-6a6c-11e9-973c-32c5cc1a9d5e.png)

### Expected Behavior

I use blank screen as I've just started project so I expect blank screen with 5 tabs.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.9.0
| react-native     | 0.59.5
| node             | 11.10.1
| npm or yarn      | 6.9.0

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!

**Comment by hpelitebook745G2** [comment]
@brentvatne I got this error too when upgrading `react-navigation: ^1.0.0-beta.15` to `react-navigation: ^3.11.0`.

The error points to:
`navigation={{
          dispatch: dispatch,
          state: navigationState
        }}`

This used to work in `1.0.0-beta.15` but now it doesn't. Would you enlighten use how to rewrite the said line for later versions like `3.11.0`?

**Comment by glocore** [comment]
@hpelitebook745G2 I'm doing the exact same upgrade. Were you able to solve the issue? We're using [react-navigation/redux-helpers](https://github.com/react-navigation/redux-helpers), and I believe it's the cause for the issue.

**Comment by PratikG9** [comment]
Facing same issue on `3.0.2`

**Comment by bwoodlt** [comment]
Still having this issue - anyone made progress on this?
