### ISSUE TITLE
How to navigate the same page which is currently open and start it from constructor again in react-native? 

### ISSUE THREAD

**Issue by Ektasahusahu** [react-navigation/react-navigation#5858]
Suppose, A user create form is currently open and value are set in the text Input and Then when i again navigate from side drawer to the same page(user create) so i want fresh form like i just want to call constructor again to set all the state into initial state.

**Comment by brentvatne** [comment]
hi there! this is a question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.
