### ISSUE TITLE
navigation.getChildNavigation is not a function

### ISSUE THREAD

**Issue by o-legvynenko** [react-navigation/react-navigation#5859]
### Current Behavior

- What code are you running and what is happening?

```
// src/navigation/tabbar/index.js

import React, { Component } from 'react';
import { connect } from 'react-redux';
import { TabBar } from './config';

class TabBarNavigation extends Component {
  render() {
    const { dispatch, navigationState } = this.props;
    return (
      <TabBar
        navigation={{
          dispatch: dispatch,
          state: navigationState
        }}
      />
    );
  }
}

const mapStateToProps = (state) => {
  return {
    navigationState: state.tabBar
  }
}

export default connect(mapStateToProps)(TabBarNavigation);
```

- Include a screenshot if it makes sense.

![Simulator Screen Shot - iPhone 6 - 2019-04-28 at 06 13 54](https://user-images.githubusercontent.com/48455672/56935175-45d0bf80-6aa4-11e9-9af1-c690aeab71eb.png)

### Expected Behavior

I use blank screen as I've just started project so I expect blank screen with 5 tabs.

### How to reproduce

Here is a repository.
https://github.com/o-legvynenko/therapy

Run this code and there is only a TouchableOpacity. Tap it and occurs error.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.9.0
| react-native     | 0.59.5
| node             | 11.10.1
| npm or yarn      | 6.9.0

**Comment by brentvatne** [comment]
hello! there is a lot going on in this example, could you possible condense it into one js file and remove any code that's unnecessary to reproduce the problem?

**Comment by o-legvynenko** [comment]
I've attached js code occurring error and I think you can see the screenshot saying. For other files, it's all related to stack navigator and tab navigator. You can track issue from src/navigation/tabbar/index.js file.

**Comment by hpelitebook745G2** [comment]
@brentvatne I got this error too when upgrading `react-navigation: ^1.0.0-beta.15` to `react-navigation: ^3.11.0`.

The error points to:
`navigation={{
          dispatch: dispatch,
          state: navigationState
        }}`

This used to work in `1.0.0-beta.15` but now it doesn't. Would you enlighten use how to rewrite the said line for later versions like `3.11.0`?

**Comment by cmorent** [comment]
Hello there, any update on this? I have the same problem:

react-navigation: 3.11.0
react-native: 0.59.9
node: 12.4.0
yarn: 1.16.0

**Comment by andrewhartwig** [comment]
Any successes?

**Comment by kamlesh1000** [comment]
I have same issue . Any updates on this ?

**Comment by andrewhartwig** [comment]
@kamlesh1000 after many hours, and many issues I've gotten it working.

I'm using 
```javascript
    "react-navigation": "^3.11.1",
    "react-navigation-redux-helpers": "^3.0.2",
```

I'm sure my solution only applies to 3.x so if you're on a different version, not sure if this will help.

Give me a minute to type up my solution as clean as I can.

**Comment by andrewhartwig** [comment]
I finally got it working this morning, I'm rather disappointed with the lack of documentation on the redux-helpers. (Oops, I'm just now realizing I'm in the wrong repo here, I hope you're trying redux integration.)

# `src/TabNavigator.js`
```javascript

export const TabNavigation = createMaterialTopTabNavigator({
  Discover: {
    screen: DiscoverScreen
  },
  Products: {
    screen: ProductsScreen
  },
  MyCoupons: {
    screen: MyCouponsScreen
  },
  Profile: {
    screen: ProfileScreen
  },
  Settings: {
    screen: SettingsScreen
  }
}, {
  tabBarComponent: () => null,
  animationEnabled: true,
  swipeEnabled: true
});

const WrappedTabNavigation = connect(state => ({ state: state.tabNav }))(createReduxContainer(TabNavigation, 'tabNav'));
```

# `src/index.js`
```javascript

const tabNavigatorMiddleware = createReactNavigationReduxMiddleware(state => state.tabNav, 'tabNav');

let composed = composer(applyMiddleware(ReduxThunk, stackNavigatorMiddleware, tabNavigatorMiddleware));
```

# `src/reducer.js`
```javascript

const firstTabAction = TabNavigation.router.getActionForPathAndParams('Discover');
const initialTabNavState = TabNavigation.router.getStateForAction(firstTabAction);

function tabNav(state = initialTabNavState, action) {
  let nextState;

  switch(action.type) {
    case 'Navigation/BACK':
      return nextState || state;
    default:
      nextState = TabNavigation.router.getStateForAction(action, state);
      break;
  }

  return nextState || state;
}

export default () => combineReducers({
  ...
  tabNav,
  ...
});
```

This provided the proper object/config to my navigator.

Please ask any questions / let me know if you're not using redux helpers, as I've spent a lot of time trying to get this to work, I may be able to offer some help.

**Comment by kamlesh1000** [comment]
Thanks for your effort. Appreciated it. I am gona try this. I will let you
know, if this help me.

**Comment by kamlesh1000** [comment]
I use the same versions of the packages, Please have a look on this
question, I asked yesterday on Stackoverflow. I am completely puzzled. I
have described my problem in detail. I am waiting for your response.  As I
am new to react native, I seek your help for this.  Thank You.

**Comment by kamlesh1000** [comment]
I just realized, i didn't gave you a link for a question.
https://stackoverflow.com/questions/57459685/typeerror-navigation-getchildnavigation-is-not-a-function-in-navigation-getc

**Comment by andrewhartwig** [comment]
Hey @kamlesh1000 looks like you're pretty close. You're just missing two things.

In your `InitialAuthRoute.js` file:

You have:
```javascript
import React, { Component } from "react";
import { connect } from "react-redux";
import { addNavigationHelpers } from "react-navigation";
import InitialAuthRoute from "./InitialAuthRoute";
import NavigationReducer from "../reducers/navigationReducer";

class AppNavigation extends Component {
  render() {
    return (
      <InitialAuthRoute navigation={({
        dispatch: this.props.dispatch,
        state: this.props.navigationState,
      })} />
    );
  }
}

const mapStateToProps = state => {
  return {
    navigationState: state.nav
  };
};

export default connect(mapStateToProps)(AppNavigation);
```

What you need to do is **not** pass the navigation object to `<InitialAuthRoute` and instead use:

```javascript
...
import { createReduxContainer } from 'react-navigation-redux-helpers';

const WrappedInitialAuthRoute = connect(state => ({ state: state.nav }))(createReduxContainer(InitialAuthRoute));

class AppNavigation extends Component {
  render() {
    return (
      <WrappedInitialAuthRoute />
    );
  }
}
...
```

Then you're missing one last step in `index.js`:

```javascript
  import { createReactNavigationReduxMiddleware } from 'react-navigation-redux-helpers';

  const navigationMiddleware = createNavigationReduxMiddleware(state => state.nav);

  const createStoreWithMiddleware = applyMiddleware(thunk, navigationMiddleware)(createStore);
```

Let me know how that goes.

**Comment by kamlesh1000** [comment]
@andrewhartwig damn bro!! I can't express my happiness in words. You are a savior. I asked god to help me , and I found you. :D Thank you.

**Comment by kamlesh1000** [comment]
@andrewhartwig Thank You so much. You are a savior. I solved this issue. But, I finally landed to the start of problem, I am not able to navigate from the actions after the success of fetching of api. Say 'loginactions.js' , all this started with making the screen making able to navigate to another screen after the fetch success in action. :(
Round-and-round

**Comment by deehuey** [comment]
@kamlesh1000 Isn't it `NavigationActions.navigate({ routeName: 'MyCompanies', params: {...} })` ?
