### ISSUE TITLE
How to make tab inside tab

### ISSUE THREAD

**Issue by craigcosmo** [react-navigation/react-navigation#5861]
I got a basic bottom nav. Then I need to do tabs within the bottom nav. Some thing like this

<img width="317" alt="Screen Shot 2019-04-28 at 4 09 58 PM" src="https://user-images.githubusercontent.com/538657/56940745-6a777680-6b3a-11e9-9543-729368f69af2.png">

I checked out the tab nagivation guides document, doesn't seem to solve the case. 

Can react navigation tab within tabs or I need to resort to something else?

**Comment by brentvatne** [comment]
we don't provide a navigator with a ui similar to what you want here. the closest is createMaterialTopTabNavigator. you could also make a custom tab navigator for this - some info in this here: https://reactnavigation.org/docs/en/custom-navigator-overview.html although i'd recommend just reading https://github.com/react-navigation/material-bottom-tabs/tree/master/src

**Comment by brentvatne** [comment]
(created a followup issue to have some better docs on creating a custom tab navigator as i believe this is reasonably common)

**Comment by craigcosmo** [comment]
Thanks. Any time frame with the follow up?

**Comment by brentvatne** [comment]
not really. the above documentation and source links should be sufficient though

**Comment by brentvatne** [comment]
you could also check out the 'creating a navigator' section in this talk https://youtu.be/wJJZ9Od8MjM?t=1215

**Comment by craigcosmo** [comment]
thanks good vid, didnt know it was you in the first view.
