### ISSUE TITLE
Async Storage has been extracted from react-native core and will be removed in a future release

### ISSUE THREAD

**Issue by surmon-china** [react-navigation/react-navigation#5864]
I have this warning with react-navigation:
```
Warning: Async Storage has been extracted from react-native core and will be removed in a future release. 
It can now be installed and imported from '@react-native-community/async-storage' instead of 'react-native'.
See https://github.com/react-native-community/react-native-async-storage
```

### The warn code
https://github.com/react-navigation/react-navigation-native/blob/master/src/createAppContainer.js#L2

```js
import { AsyncStorage, Linking, Platform, BackHandler } from 'react-native';
// should be replace to
import AsyncStorage from '@react-native-community/async-storage'
```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.9.1
| react-native     | 0.59.5

**Comment by brentvatne** [comment]
this will be resolved shortly by https://github.com/react-navigation/native/pull/21

**Comment by brentvatne** [comment]
>= 3.10.0 removes dependency on AsyncStorage
