### ISSUE TITLE
how to hide the header the tabs

### ISSUE THREAD

**Issue by craigcosmo** [react-navigation/react-navigation#5866]
<img width="424" alt="Screen_Shot_2019-05-01_at_3_22_05_PM" src="https://user-images.githubusercontent.com/538657/57010104-1ac1a980-6c25-11e9-9a9e-2133b4c7f3e9.png">
How do you hide/remove the header?

**Comment by eriveltonelias** [comment]
Hi @craigcosmo,

you can use `header:null`

https://reactnavigation.org/docs/en/stack-navigator.html#header

**Comment by craigcosmo** [comment]
Thanks, how do you hide the border of tab? 

```js
style: {
	borderTop:0,
	border:0
},
```
That code wont do

<img width="437" alt="Screen_Shot_2019-05-05_at_12_39_44_AM" src="https://user-images.githubusercontent.com/538657/57182831-81b5bb80-6ece-11e9-9663-0eb14b7a2225.png">
