### ISSUE TITLE
Pass params on swipe/gestures

### ISSUE THREAD

**Issue by MartinMasek** [react-navigation/react-navigation#5867]
I've tried to look into documentation and google this problem but I wasn't successful.

I have a screen (say A) and I pass parameter {refresh: false} when I don't want the screen to refresh. I have a screen B and when navigation from B->A I don't want the refresh.

I'm able to pass the parameter when a user clicks back button or Android hardware back button. However, when it comes to swiping, I'm not able to do that (when a user swipes back on iOS, no {refresh: false} is passed, thus the screen is refreshed).

I checked Custom routes documentation and the idea was to look at the state manually insert the parameter when navigation from B->A. However, I checked 'action' and 'state' parameters and even though the 'routes' property contains the destination screen (A), I can't access the source screen (thus not being able to distinguish if user navigated from B or from C).

Is my use case achievable with react-navigation? I don't want to turn off gestures just because of this.

**Comment by eriveltonelias** [comment]
hi there! this is a question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.
