### ISSUE TITLE
Swipe to goback function crash in IOS platform.

### ISSUE THREAD

**Issue by tlweiii6465** [react-navigation/react-navigation#5870]
Hi, i just used this gesturesEnabled:true in my project for use the swipe to goback function, android is work fine but it just crash in my ios app, this is what error it show to me.

***Terminating app due to uncaught exception 'RCTFatalException: Unhandled JS Exception: 
  Unsupported top level event type "onGestureHandlerStateChange" dispatched', reason: 
  'Unhandled JS Exception: Unsupported top level event type "onGestureHandlerS..., stack:

is any solution to solve this?

"react-native": "^0.55.4",
"react-navigation": "^3.0.8"
"react-native-gesture-handler": "1.0.16"

**Comment by tlweiii6465** [comment]
Hi, i just fix this issue by 
1. downgrading "react-native-gesture-handler": "1.0.16"-> "react-native-gesture-handler": "^1.0.9"
2. react-native link
3. pod update

**Comment by paul-hart** [comment]
The current version of react-native-gesture-handler is 1.2.1. I am really frustrated by all advise on this crash being to down grade. 1.0.16 and 1.0.9 are too far in the past. Lets get some feedback that actually fixes the up-to-date version of this. I keep having this problem myself.

**Comment by camilo5972** [comment]
This works for me

```
require('react-native-gesture-handler'); // Add this to the beginning of App.js
import React, { Component, Fragment } from 'react';
import { StyleSheet, StatusBar } from 'react-native
```

Versions:
"react": "16.8.3",
"react-native": "0.59.8",
"react-native-gesture-handler": "^1.2.1",
"react-navigation": "^3.11.0"

**Comment by shairamiri** [comment]
> This works for me
> 
> ```
> require('react-native-gesture-handler'); // Add this to the beginning of App.js
> import React, { Component, Fragment } from 'react';
> import { StyleSheet, StatusBar } from 'react-native
> ```
> 
> Versions:
> "react": "16.8.3",
> "react-native": "0.59.8",
> "react-native-gesture-handler": "^1.2.1",
> "react-navigation": "^3.11.0"

--

Did you use this for all the js files u made? Because im not using my App.js anywhere.
