### ISSUE TITLE
Bottom tab color doesn't change dynamically

### ISSUE THREAD

**Issue by HenriqueMata** [react-navigation/react-navigation#5873]
I'm trying to change color dynamically from params, but when I change the color the bottom tab color returns white not the color that i want.
![captura](https://user-images.githubusercontent.com/35509741/57102422-d5bb7700-6cf9-11e9-8fff-6ed1f7134f63.PNG)
![set](https://user-images.githubusercontent.com/35509741/57102393-c63c2e00-6cf9-11e9-8356-0654aac1003a.PNG)
(value coming from navigation)
![style](https://user-images.githubusercontent.com/35509741/57102392-c63c2e00-6cf9-11e9-90d9-cceb7e0232fb.PNG)
(background  color)

| software         | version
| ---------------- | -------
| react-navigation | 3.3.2
| react-native     | 0.58.5

**Comment by brentvatne** [comment]
if you enable `shifting` then you can use `tabBarColor` in `navigationOptions` - https://reactnavigation.org/docs/en/material-bottom-tab-navigator.html#tabbarcolor

`barStyle` is not supported as a dynamic option currently - it is only available through navigation configuration. you can propose this on https://github.com/react-navigation/react-navigation-material-bottom-tabs if you would like

in the future please follow the issue template correctly and provide a reproducible example.

**Comment by HenriqueMata** [comment]
So if I want to disable `shifting ` and change my bottom tab color dynamic, can't i?
