### ISSUE TITLE
Convert NavigationPlayground to Expo managed project and publish

### ISSUE THREAD

**Issue by brunohkbx** [react-navigation/react-navigation#5875]
It crashes when I try to open the `Tabs Example` with the following error:

![error](https://user-images.githubusercontent.com/6487206/57153723-6901b480-6dad-11e9-8498-0010ed0f21b8.jpeg)

**Comment by brentvatne** [comment]
the published example is a bit out of date at the moment, we need to convert NavigationPlayground back to being an expo project (for convenience it was converted to a bare react-native project when adding typescript to it) and publish it again. if you'd like to work on this it'd be cool! it shouldn't take much work

**Comment by brunohkbx** [comment]
@brentvatne could you take a look :smiley: ? #5898

**Comment by brunohkbx** [comment]
@brentvatne feel free to republish it now

**Comment by eriveltonelias** [comment]
thanks @brunohkbx
