### ISSUE TITLE
Picker component as headerRight is reverting to previous value in expo

### ISSUE THREAD

**Issue by eladmotola** [react-navigation/react-navigation#5876]
### Current Behavior

the picker showing for a half of a second "switch" and then it showing "hello"

### Expected Behavior

picker to show "switch"

### How to reproduce

```
static navigationOptions = ({ navigation }) => {
    const { params } = navigation.state;
    return {
      title:'title',
      headerRight: (
       <View>
                    {params && params.groups ?
                        <Picker
                            selectedValue={params.groupName}
                            style={{ height: 50, width: 200 }}
                            onValueChange={params.switch}>
                            {params.groups.map(group => {
                                return <Picker.Item key={group.id} label={group.name} value={group.id} />
                            })}
                        </Picker> : <Fragment></Fragment>}
                </View>
      ),
    };
  };

  componentWillMount() {
    const groups = [{id:1,name:"hello"},{id:2,name:"switch"}]
    this.props.navigation.setParams({ switch: this.switch , groups,groupName:groups[0].name });
  }

  switch = () => {
    const groups = [{id:1,name:"hello"},{id:2,name:"switch"}]
    this.props.navigation.setParams({ groupName:groups[1].name });
  };
```
### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.6.1/3.9.1
| react-native     | 32
| node             | 10.4.1
| npm or yarn      | npm

when i use a different component like `Text` and tapping on a text its not reverting back to the previos value, maybe a problem with the integration with picker?

**Comment by vonovak** [comment]
Hi! Please take a look at your onValueChange callback - it's always resetting the picker to the same value ("hello"). Take a look at the example at https://facebook.github.io/react-native/docs/picker

Thanks.

**Comment by eladmotola** [comment]
How it's resetting to "hello" every time if group[1].name is "switch"
