### ISSUE TITLE
Use Different Tab View for each Role

### ISSUE THREAD

**Issue by QaziAbeelQureshi** [react-navigation/react-navigation#5877]
I need to Render Different Tab view on the base of role of user how would i do that as much as i know the tab view and complete navigation renders on the starting time so how would i change tab view according to my role on run time ??

**Comment by eriveltonelias** [comment]
hi there! this issue tracker is reserved for bugs only. your post seems to be a usage question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help. thanks!
