### ISSUE TITLE
react-navigation-tabs version

### ISSUE THREAD

**Issue by alamothe** [react-navigation/react-navigation#5878]
Hello,
I am wondering why this package uses `react-navigation-tabs` `1.1.2` instead of `2.1.2`. This is causing `react-native-tab-view` `1.3.5` to be transitively included, but I would like to use its latest version.

Thanks!

**Comment by eriveltonelias** [comment]
hey @alamothe, 

check this https://github.com/react-navigation/react-navigation/issues/5684#issuecomment-473489146
