### ISSUE TITLE
iOS createBottomTabNavigator with react-native-screens UI is stuck (touch events not working?) in React Navigation 3.0.9

### ISSUE THREAD

**Issue by oriharel** [react-navigation/react-navigation#5879]
---

### Current Behavior

- What code are you running and what is happening?

This is my tab navigator:

```
const TabNavigator = createBottomTabNavigator(
	{
		Diagnosis: {
			screen: DiagnosisScreen
		},
		MyPatient: {
			screen: MyPatientScreen
		}
	},
	{
		initialRouteName: 'Diagnosis
	}
);
```

App starts at "Diagnosis". I navigate to "MyPatientScreen", then back to "Diagnosis", then back to "MyPatientScreen" (for the 2nd time) - the button inside "MyPatientScreen" is unresponsive. On initial navigation it is responsive. If I use `createMaterialBottomTabNavigator` it works. Reproduces only for `createBottomTabNavigator`

### Expected Behavior

- What do you expect should be happening?

Touch events should work.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.0.9
| react-native     | expo SDK 32
| node             | v10.15.1
| npm or yarn      | 1.13.0

Here's the snack repro:
https://snack.expo.io/@oriharel/Y3JlYX

**Comment by eriveltonelias** [comment]
hi @oriharel, please make your code runnable either on https://snack.expo.io without any extraneous code

maybe is related with https://github.com/react-navigation/react-navigation/issues/5684

**Comment by oriharel** [comment]
@ericvicenti ok - I've narrowed down the causes of this bug - it seems that it has something to do with react-native-screen. I've added a repro in snack.

**Comment by oriharel** [comment]
Looks like it's already reported:
https://github.com/kmagiera/react-native-screens/issues/53

**Comment by devagul93** [comment]
Even I am facing this Issue
