### ISSUE TITLE
Not restoring state on Android when backgrounding and foregrounding and Activity is destroyed.

### ISSUE THREAD

**Issue by joshuapinter** [react-navigation/react-navigation#5880]
### Current Behavior

On Android, an Activity can be destroyed by the operating system in the background to recover memory, etc. Android handles this by saving and restoring the state. Works great, actually. However, with React Navigation, the entire stack is wiped out when this happens.

![react navigation](https://user-images.githubusercontent.com/180819/57197003-4c858980-6f1f-11e9-9381-c69c6440a1fa.gif)

### Expected Behavior

It should restore the state, similar to what happens when you have "Don't keep activities" set to false. (See above GIF for comparison.)

### How to reproduce

To easily test this: 

1. Ensure "Don't keep activities" is set to true in Developer Settings. 

2. Navigate a couple screens deep. 

3. Background app.

4. Foreground app. 

5. You're back at the root screen.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.18.4
| react-native     | 0.59.5
| node             | v10.15.3
| npm or yarn      | 6.4.1

**Comment by vonovak** [comment]
hi, thanks for reporting!

> Android handles this by saving and restoring the state

actually, I believe android does not do this out of the box for all state. It might retain state of individual widgets - eg textinput state (which should work for react-navigation too) but if you, as a developer, want to do something more clever you'll have to implement this yourself (by overriding onSaveInstanceState())

in react-navigation, the behavior you want is opt-in: see https://reactnavigation.org/docs/en/state-persistence.html

hope this answers the question

**Comment by joshuapinter** [comment]
Android handles it relatively automagically for native Activities that get backgrounded and destroyed without having to override `onSaveInstanceState` or `onRestoreInstanceState`, unless you need to do something special, like save a file path or something. You might have to adjust the `launchMode` in `AndroidManifest.xml` slightly to use `singleTask` or `singleTop` to get the desired result, but it works more or less out of the box.

On Android 21+, you can even persist your instance to the disk to handle reboots as well with `onSaveInstanceState(Bundle outState, PersistableBundle outPersistentState)`.

However, with React Native, there's no way to save or restore from that bundle cleanly, that I can see.

The only way is the State Persistence in `react-navigation` by using `persistenceKey` that you mentioned.

When implementing that we ran into issues, likely with the params we have setup in the NavigationStack, but if that's the only way to do it, I guess we'll just have to keep playing with it.

Thanks for the reply and let me know if there's anything else we should be looking at here.

**Comment by vonovak** [comment]
> Android handles it relatively automagically for native Activities that get backgrounded and destroyed without having to override onSaveInstanceState or onRestoreInstanceState, unless you need to do something special

yes, that's essentially what I was trying to say.

> The only way is the State Persistence in react-navigation by using persistenceKey that you mentioned.

yes, and it's cross-platform so you don't need to handle ios / android differences. Also note that there will be a small change in the persistence mechanism: https://github.com/react-navigation/native/pull/21

I'll leave this open in case some other maintainer wants to add something, but this is it from me :)

**Comment by joshuapinter** [comment]
Perfect, thanks @vonovak! Looks like you've been working on this recently. Lots of big changes coming down the pipe for this.

Is your branch more or less good to be used? May as well use the latest instead of using `persistenceKey` before this is merged in.

**Comment by vonovak** [comment]
@joshuapinter I think it's safe to say the functionality, as implemented in the branch now, will make it into a future version of react-navigation

**Comment by joshuapinter** [comment]
@vonovak Great, thanks!

**Comment by eriveltonelias** [comment]
thanks @vonovak, can we close this issue ? :)

**Comment by joshuapinter** [comment]
The only thing I’ll mention is, would be worth a PR to showcase this functionality in the demo app? Happy to add that so let me know.

**Comment by nguyenhose** [comment]
hi @joshuapinter, I got this problem recently in some real androids. If I set `Login Screen` as first screen of stack, it will always resets to `Login Screen` after go foreground even I was in Home Screen.

**Comment by colaskirschoff** [comment]
@nguyenhose I have the exact same issue. Any update ?
@joshuapinter Do you still use state persistence ?

**Comment by vonovak** [comment]
@colaskirschoff if you believe you hit a bug in react-navigation, please open a new issue with a runnable repro, thank you.
