### ISSUE TITLE
BackHandler within nested navigators

### ISSUE THREAD

**Issue by Jacky9425** [react-navigation/react-navigation#5882]
I have a stack navigator containing 3-4 screens and one of them is contains a tab navigator. The Tab Navigator is my main HOME PAGE. I want to make the app to respond in a way that when hardware back button is pressed on the MAIN tab navigator , it prompts an alert message. Whereas on the other screens within the main stack or other stacks within the tab navigator, i want the back button act as normal that is return to previous screen.

My current progress is i can add the listener to proc an alert but on the other screens the back press does not return to previous screen but instead proc the alert i declared in the main tab navigator (Main.js for instance). Its it necessary to declare a BackHandler listener across each screens or is there better approach to do so?

**Comment by eriveltonelias** [comment]
hi there! this issue tracker is reserved for bugs only. your post seems to be a usage question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help. thanks!
