### ISSUE TITLE
Conditional in bottomtab

### ISSUE THREAD

**Issue by mrodrigs** [react-navigation/react-navigation#5884]
Hello guys, I'm starting with React Native and I have this little issue right here. I have a bottomTabNavigator, if the user has permission, he navigates to ImageScreen, else, it navigates to the HomeScreen.

My function global.hasPermission() checks the permission and return true or false, so I want to be capable of changing the {screen: ImageScreen} depending on what the function returns. How can I do it? Where do I call my function hasPermission()?

Here's my tabNavigator:
```
const BottomTab = createBottomTabNavigator({
	Image: {
		screen: ImageScreen,
		navigationOptions: {
			tabBarLabel: 'Image Screen',
			tabBarIcon: ({ tintColor, focused }) => (
				<Ionicons
					name={'ios-camera'}
					size={focused ? 30 : 26}
					style={{ color: tintColor }}
				/>
			),
		},
	},
});
```

**Comment by eriveltonelias** [comment]
hi there! this issue tracker is reserved for bugs only. your post seems to be a usage question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help. thanks!
