### ISSUE TITLE
Can't subscribe to swipe event

### ISSUE THREAD

**Issue by IlinIgor** [react-navigation/react-navigation#5886]
How can I subscribe to the swipe event and stop it? I have to open popup when user swiping back the screen. I can't do it with getStateForAction, cuz it works at the end of the swipe event. I see that there is onHandlerStateChange event in react-native-gesture-handler but I can't subscribe to it. How can I do it?

react-native: 0.59.1
react-navigation: 3.8.1
react-native-gesture-handler: 1.1.0

**Comment by brentvatne** [comment]
please follow the issue template!
