### ISSUE TITLE
On swipe, Navigation menu is not getting updated.

### ISSUE THREAD

**Issue by YajanaRao** [react-navigation/react-navigation#5888]
### Current Behavior
`swipeEnabled` is true and swiping is changing the screen not the active tab of tab bar component. While clicking on the icons in tab bar is changing the page as well as active tab in the tab bar as well.

#### Note: 
I have created a custom tabBarComponent

### Expected Behavior
It should update the active screen in tab bar.

### How to reproduce

 [Snack Demo](https://snack.expo.io/@yajana/thoughtful-cookies)

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.0.0-rc.5
| react-native     | 32
| node             | v8.11.4
| npm or yarn      | 6.4.0

**Comment by brentvatne** [comment]
you need to use the latest version of the library

**Comment by YajanaRao** [comment]
Updating to latest version is giving an issue with drawer. I will update you regarding the issue once I am able to update to the latest version
https://github.com/react-navigation/drawer/issues/47
