### ISSUE TITLE
Question about state persistence

### ISSUE THREAD

**Issue by alamothe** [react-navigation/react-navigation#5889]
Docs state:

> Each param, route, and navigation state must be fully JSON-serializable for this feature to work. This means that your routes and params must contain no functions, class instances, or recursive data structures.

What happens if this is not the case, for example a function? Is it simply ignored, or...?

Having a function in params is the usual pattern for interaction with header buttons, described here: https://reactnavigation.org/docs/en/header-buttons.html

Thanks!

**Comment by vonovak** [comment]
@alamothe the state persistence functionality has been updated in the last release, please take a look at https://reactnavigation.org/docs/en/state-persistence.html

> What happens if this is not the case, for example a function? Is it simply ignored, or...?

you can now freely choose what to persist and what not, and you can modify the state from which react-navigation will bootstrap the navigation. 

hope this answers the question

**Comment by IanVS** [comment]
I'm also trying to figure out how to square the instructions to only use serializable params with the other instructions of how to use header buttons by creating function params.  I've read reactnavigation.org/docs/en/state-persistence.html, but the warning is still there.  I'm using version 4.x.  If I'm not using state persistence, is using functions in params safe?

**Comment by vonovak** [comment]
@IanVS 

> If I'm not using state persistence, is using functions in params safe?

yes, if you're not using the state persistence. So you can pass functions around but once you'll want to take advantage of state persistence, it won't be possible.

you can work around the limitation of using the provided state persistence mechanism if you want, see eg. https://reactnavigation.org/docs/en/MST-integration.html
