### ISSUE TITLE
Handle header button in current screen with Functional Component (not Class Component)

### ISSUE THREAD

**Issue by Steffi3rd** [react-navigation/react-navigation#5890]
Hello, 

I would like to use button in my header to interact with my screen component

I tried some things but it doesn't work.
Maybe It seems because I don't have Class Component but Functionnal component, so` static navigation` doesn't work....

```
const ScreenComponent = ({ navigation }) => {
  
 navigationOptions = {
    headerRight: (
      <Button
        onPress={() => state.params.doSomething()}
        title="Info"
        color="#fff"
      />
    )
  };

   const doSomething = () => {
      ... 
   }

  useEffect({
      navigation.setParams({ doSomething: () => doSomething() })
  }, [])

}
```

I follow this : https://dev.to/acro5piano/handle-stack-navigators-event-in-current-screen-with-react-navigation-2en3 and https://github.com/react-navigation/react-navigation/issues/145

Does anyone have a solution please?

**Comment by brentvatne** [comment]
```
const ScreenComponent = ({ navigation }) => {
  // your stuff
};
ScreenComponent.navigationOptions = {
  // other stuff
}
```

**Comment by Steffi3rd** [comment]
Thank you @brentvatne!

**Comment by Steffi3rd** [comment]
@brentvatne Is there a solution for screen using `createBottomTabNavigator()` ?

I mean, with your solution I can update navigationsOptions for a screen. 

Now I would like to do that with a screenNavigator (which contains 3 screens accessible by bottom tab navigator)

**Comment by Steffi3rd** [comment]
@brentvatne The thing is I would like to have conditional rendering in that header. If user has rights, he can see the headerRight button in the header, else no button is invisible.
