### ISSUE TITLE
navigating to screen in Stack navigator renders second component in addition to desired one

### ISSUE THREAD

**Issue by twelve17** [react-navigation/react-navigation#5895]
### Current Behavior

When navigating to screen A of a stack navigator, screen B is also rendered. Screen B is not visible in the UI, but it is present in the document (confirmed by searching in the react dev tools explorer).  I can additionally confirm that it is rendered by adding a `console.log` in the errant component's `render()` method.

- What code are you running and what is happening?

In a component outside of the target component's stackNavigator, I am calling:

```
navigation.navigate('Inner3');
```

`Inner3` is a screen in a stackNavigator:

```
import { createStackNavigator } from "react-navigation";
import { Inner1 } from "./Inner1";
import { Inner2 } from "./Inner2";
import { Inner3 } from "./Inner3";

export const InnerNavigator = createStackNavigator(
  {
    Inner1: { 
      screen: Inner1,
      navigationOptions: () => ({
        headerTitle: 'Inner 1 Screen',
        headerLeft: null
      })
    },
    Inner2: { 
      screen: Inner2,
      navigationOptions: () => ({
        headerTitle: 'Inner 2 Screen',
        headerLeft: null
      })
    },
    Inner3: {
      screen: Inner3,
      navigationOptions: () => ({
        headerTitle: 'Inner 3 Screen',
        headerLeft: null
      })
    }
  },
  {
    headerMode: "screen",
    navigationOptions: {
      header: null
    }
  }
);
```

When the `navigate` code is ran, which should navigate to `Inner3`, I observe that Inner1's `render()` method is called in addition to `Inner3`'s.

### Expected Behavior

I expect that only the screen name that is passed into the `navigate` call would be rendered, and not other screens in the `stackNavigator`.

### How to reproduce

Here's a snack:

https://snack.expo.io/@alexwb/4f7450

When ran, click on the "Go To Inner2" link.  Then observe the console to see which `InnerN`'s `render()` method is called (each one logs to the console when its `render()` method is called).

I see this in the console:

```
Inner1 screen render() called.
Inner2 screen render() called.
```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.9.1
| react-native     | 0.57.8
| node             | 10.15.1
| npm or yarn      | 6.8.0

**Comment by brentvatne** [comment]
you're rendering the contents twice here:

```
const AppContainer = createAppContainer(OuterStackNavigator);

export default class App extends React.Component {
  render() {
    return (
      <AppContainer
        ref={nav => {
          this.navigator = nav;
        }}>
        <View style={styles.container}>
          <Text style={styles.paragraph}>
            Change code in the editor and watch it change on your phone! Save to
            get a shareable url.
          </Text>
          <Card>
            <OuterStackNavigator />
          </Card>
        </View>
      </AppContainer>
    );
  }
}
```

that just should be

```
const AppContainer = createAppContainer(OuterStackNavigator);

export default class App extends React.Component {
  render() {
    return (
      <AppContainer
        ref={nav => {
          this.navigator = nav;
        }}
      />
    );
  }
}
```

**Comment by twelve17** [comment]
@brentvatne Nice catch! I need to see if this was a result of contriving the sample code.  I will report back. Thank you.

**Comment by brentvatne** [comment]
oh i see what this issue is about. what you're seeing is that when you go to a navigator that currently isn't mounted, it first presents its initial route and then adds the other route on top. you should put the route on the outer navigator if you don't want that to happen.

if you can explain the context of this in your app and also if possible compare it to an interaction from existing app that i can find on the app store it'd be helpful

**Comment by twelve17** [comment]
@brentvatne I'm waiting to hear back for the motivation behind this design, but let me see if I can describe it:

The "main" stackNavigator has things like:
```
{ 
   MyPosts
   EditPost
   MyProfile
   Survey
}
```

`Survey` is another`stackNavigator`, akin to a wizard flow:

```
{ 
  SectionA,
  SectionB,
  SectionC
}
```

You could go to the Survey screen from several screens in the main stackNavigator.  The twist, I suppose, is that for some use cases, you start in section B instead of section A.  So the "initial" component might vary.  

So I could see that the behavior you mentioned, showing the initial route if it's not mounted yet, would happen (even if no initialRouteName is defined, it seems that the navigator is picking one of the items in the object).

**Comment by twelve17** [comment]
I got a little more context.  The Survey wizard has a "cancel" button on every screen.  I believe cancelling from a wizard just "reset"s the stackNavigator, so you'd end up back at whatever screen you were at when you started the wizard, keeping the stack history the same as from when you went to start the wizard.  Does that make sense?

**Comment by jlala** [comment]
Have you solved this problem?

**Comment by twelve17** [comment]
@jlala we were not able to.

**Comment by fctmolina1135** [comment]
It also happens to me
I have two screens: ScreenA and ScreenB

I navigate to screenB from ScreenA, every time ScreenB is update componentDidUpdate of ScreenA is triggered. It's like ScreenA is still running on the background and is just covered by UI of ScreenB

**Comment by mlazari** [comment]
@twelve17 I found a way to navigate to any screen in the inner stack navigator without triggering a navigation to the initial route:
Replace this:
```
navigation.navigate('Inner2');
```
with this:
```
import { StackActions } from 'react-navigation';
// ...
navigation.dispatch(StackActions.push({
  routeName: 'InnerNavigator',
  action: StackActions.push({ routeName: 'Inner2' }),
}));
```
Here is an updated snack: https://snack.expo.io/vmRvhb2Mw

**Comment by mlazari** [comment]
For people using `react-navigation` v5, I think the solution above does not work since the `StackActions.push` API changed and does not seem to accept an `action` parameter anymore for navigating to a specific screen in the inner navigator.

In v5 I think it can be implemented by passing an `initialRouteName` (or whatever you want to name it) parameter when navigating to the inner navigator and using that parameter for `initialRouteName` prop of the navigator. Something like this: https://snack.expo.io/OvbyoXxZh

Pasting the code here in case the snack will not be available in future:
```
import * as React from 'react';
import { View, Button, Text } from 'react-native';
import { NavigationContainer, StackActions } from '@react-navigation/native';
import { createStackNavigator } from '@react-navigation/stack';

function HomeScreen({ navigation }) {
  console.log('Rendering HomeScreen');
  return (
    <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
      <Button
        title="Push Inner1"
        onPress={() =>
          navigation.dispatch(StackActions.push('InnerNavigator', { initialRouteName: 'Inner1' }))
        }
      />
      <Button
        title="Push Inner2"
        onPress={() =>
          navigation.dispatch(StackActions.push('InnerNavigator', { initialRouteName: 'Inner2' }))
        }
      />
    </View>
  );
}

function InnerScreenButtons({ navigation }) {
  return (
    <>
      <Button
        title="Push Inner1"
        onPress={() =>
          navigation.dispatch(StackActions.push('Inner1'))
        }
      />
      <Button
        title="Push Inner2"
        onPress={() =>
          navigation.dispatch(StackActions.push('Inner2'))
        }
      />
      <Button
        title="Dismiss InnerNavigator"
        onPress={() =>
          navigation.dangerouslyGetParent().pop()
        }
      />
    </>
  );
}

function InnerScreen1({ navigation }) {
  console.log('Rendering InnerScreen1');
  return (
    <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
      <Text>Inner 1!</Text>
      <InnerScreenButtons navigation={navigation} />
    </View>
  )
}

function InnerScreen2({ navigation }) {
  console.log('Rendering InnerScreen2');
  return (
    <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
      <Text>Inner 2!</Text>
      <InnerScreenButtons navigation={navigation} />
    </View>
  )
}

const Stack = createStackNavigator();
const InnerStack = createStackNavigator();

const InnerNavigator = ({ route }) => (
  <InnerStack.Navigator
    initialRouteName={route?.params?.initialRouteName}
  >
    <InnerStack.Screen name="Inner1" component={InnerScreen1} />
    <InnerStack.Screen name="Inner2" component={InnerScreen2} />
  </InnerStack.Navigator>
);

export default function App() {
  return (
    <NavigationContainer>
      <Stack.Navigator>
        <Stack.Screen name="Home" component={HomeScreen} />
        <Stack.Screen
          options={{ headerShown: false }}
          name="InnerNavigator"
          component={InnerNavigator}
        />
      </Stack.Navigator>
    </NavigationContainer>
  );
}

```

**Comment by twelve17** [comment]
Good to know, thanks @mlazari
