### ISSUE TITLE
Navigation state params getting undefined

### ISSUE THREAD

**Issue by birendra-90** [react-navigation/react-navigation#5899]
@brentvatne When I am trying to do setParams with navigation in componentDidMount() and try to access in static navigationOptions = {} but it's not setting the params in navigation state object and getting undefined.

 Can you look into this -> https://snack.expo.io/@chanchal02/demo-app

| software         | version
| ---------------- | -------
| react-navigation | 3.9.1
| react-native     | EXPO SDK 32.0
| node             | 8.14.0
| npm or yarn      | 6.4.1

**Comment by vonovak** [comment]
hi! Please follow the issue template - while you added a repro, it is not clear where the problem is. Please make sure to create a **minimal** reproduction, otherwise this is not actionable. Thanks.

**Comment by birendra-90** [comment]
@vonovak Can you check once more I have given to you minimal reproduction code.

https://snack.expo.io/@chanchal02/demo-app

**Comment by satya164** [comment]
That's not a minimal repro. Please post a minimal runnable repro with only navigation related code if you think this is still an issue.
