### ISSUE TITLE
How can I remove animate of the header when I move the next screen?

### ISSUE THREAD

**Issue by ChenJunhan** [react-navigation/react-navigation#5900]
I set headerBackground because I want to achieve gradient of the header.But it will appear white of flicker when I move the next screen, I guess this is the reason for the animation. I am trying to configuration transitionConfig but it not work. This is my navigationOptions:
```
headerBackground: (
      <Image
        style={{height: setHeight(58), width: setWidth(375), resizeMode: 'stretch'}}
        source={require('./assets/images/top-bg.jpg')}
      />
),
transitionConfig: () => ({
    screenInterpolator: StackViewStyleInterpolator.forHorizontal,
    transitionSpec: {
      duration: 0,
      timing: Animated.timing,
      easing: Easing.step0
    }
})
```
![Screenshot](https://user-images.githubusercontent.com/29296597/57428495-3cd9ae00-725b-11e9-90be-ae1d8bc9d914.gif)

Version: 
`"react-navigation": "^3.6.1"`

**Comment by eriveltonelias** [comment]
hi there! this issue tracker is reserved for bugs only. your post seems to be a usage question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help. thanks!
