### ISSUE TITLE
I created a react native app using create-react-native-app. Chose expo-template-tabs. Then I following error came up

### ISSUE THREAD

**Issue by ganeshpprasad** [react-navigation/react-navigation#5911]
---

### Current Behavior

- What code are you running and what is happening?
create-react-native-app appName
- Include a screenshot if it makes sense.
<img width="1304" alt="Screenshot 2019-05-14 at 2 02 53 AM" src="https://user-images.githubusercontent.com/16379606/57652132-896f1180-75ec-11e9-9d80-90176087cd54.png">

### Expected Behavior

- What do you expect should be happening?
react native app should be created

| software         | version
| ---------------- | -------
| react-navigation | 3.0.9
| react-native     | https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz
| node             | 10.14.2
| yarn      |  1.15.2

**Comment by eriveltonelias** [comment]
Hi @ganeshpprasad, 

create-react-native-app has been merged with Expo CLI, so try to use `expo init` here is the docs https://docs.expo.io/versions/v32.0.0/workflow/up-and-running/ and also, make sure to use the latest version of react-navigation ( 3.9.1 )
