### ISSUE TITLE
MaterialTopTabNavigator warning on 'bounces' prop of AndroidPager

### ISSUE THREAD

**Issue by ElChurros** [react-navigation/react-navigation#5914]
### Current Behavior

I am running a very simple mobile application in which i am using a MaterialTopTabNavigator to navigate between 3 different screens.
When testing on iOS, the application runs without any warning. On Android, a warning is displayed in the emulator indicating :
``Warning: Failed prop type: The prop 'bounces' is marked as required in 'PagerAndroid', but it's value is 'undefined'.``

Here is a screenshot of the complete warning message :
![image](https://user-images.githubusercontent.com/25263559/57871826-83567c00-780a-11e9-9b5b-716f3590f0f3.png)

### Expected Behavior
Of course I would expect it to run without any warnings.

### How to reproduce

Here is an example app that generates this warning :

https://github.com/ElChurros/TabNavigatorIssue.git

To reproduce the warning : 
 - clone the repository
 - navigate to the cloned repo
 - run ``npm install``
 - launch an Android emulator
 - run ``react-native run-android``

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  "^3.9.2"
| react-native     | "0.59.8"
| node             | v12.2.0 
| npm or yarn      | 6.9.0

**Comment by chohonest** [comment]
I am having this exact warning.

**Comment by amed** [comment]
I had to disable it manually, it happened after upgrading to latest. ( 3.0.9 => 3.9.2 )

```javascript
import { YellowBox } from 'react-native'

YellowBox.ignoreWarnings(['Warning: Failed prop type: The prop'])
```

**Comment by brentvatne** [comment]
cc @satya164

**Comment by spyshower** [comment]
I see this got closed, but for me the error is not fixed. I get this error for `PagerPan` instead of `PagerAndroid` though.

**Comment by vizfiz** [comment]
Found the root of this under
 
react-native-tab-view  --> src folder --> PropTypes line 43, bounces: PropTypes.bool.isRequired

I removed the .isRequired. Doesn't seem like it should be a required prop

Yet to uncover what impact this has upstream in react navigation...

**Comment by Abdalmajid** [comment]
> Found the root of this under
> 
> react-native-tab-view --> src folder --> PropTypes line 43, bounces: PropTypes.bool.isRequired
> 
> I removed the .isRequired. Doesn't seem like it should be a required prop
> 
> Yet to uncover what impact this has upstream in react navigation...

this fix the issue, Thanks

**Comment by satya164** [comment]
Please upgrade your `react-navigation` version. The line isn't there.

**Comment by ElChurros** [comment]
> Please upgrade your `react-navigation` version. The line isn't there.

Hi, I did, but the warning remains with react-navigation 3.11.0. Tried in both my app and my minimal example.

**Comment by satya164** [comment]
try deleting your `node_modules` and install again and clear metro cache with `react-native start --reset-cache`. the latest version doesn't even have this line in `PagerPan` or `PagerAndroid`, so it's not possible for it to show a warning.

**Comment by ElChurros** [comment]
@satya164 Perfect the reset-cache was the trick. Thank you for the quick fix on this issue.

**Comment by hadpro24** [comment]
@satya164  thank you, it's work.
