### ISSUE TITLE
Warning: Failed prop type: The prop `bounces` is marked as required in `PagerPan`, but its value is `undefined`.

### ISSUE THREAD

**Issue by spyshower** [react-navigation/react-navigation#5915]
### Current Behavior

At the first `navigation.navigate` that happens inside the app this error is thrown. Example from a Stack Navigator to another:

`this.props.navigation.navigate('App')`

This likely happened at 3.9.2 update, but I tried 3.9.1 and it happens again.

Full stack trace:

```
Warning: Failed prop type: The prop `bounces` is marked as required in `PagerPan`, but its value is `undefined`.
- node_modules/prop-types/checkPropTypes.js:20:20 in printWarning
- node_modules/prop-types/checkPropTypes.js:83:12 in checkPropTypes
- node_modules/react/cjs/react.development.js:1501:19 in validatePropTypes
- node_modules/react/cjs/react.development.js:1590:22 in createElementWithValidation
- node_modules/react-navigation-tabs/src/navigators/createMaterialTopTabNavigator.js:118:30 in _renderPanPager
- node_modules/react-native-tab-view/src/TabView.js:193:22 in render
- node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:10563:21 in finishClassComponent
- node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:14091:21 in performUnitOfWork
- node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:14129:41 in workLoop
- node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:14226:15 in renderRoot
- node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:15193:17 in performWorkOnRoot
- node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:15090:24 in performWork
- node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:15047:14 in performSyncWork
- node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:14925:19 in requestWork
- node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:14711:16 in scheduleWork
- node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:7700:17 in enqueueSetState
- node_modules/react/cjs/react.development.js:364:31 in setState
- node_modules/@react-navigation/native/src/createAppContainer.js:351:22 in dispatch
- node_modules/@react-navigation/core/lib/module/getChildNavigation.js:1:1529 in <unknown>
* src/components/Screens/AuthHome.js:489:43 in _callee5$
- node_modules/regenerator-runtime/runtime.js:62:44 in tryCatch
- node_modules/regenerator-runtime/runtime.js:288:30 in invoke
- ... 13 more stack frames from framework internals
```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.9.1
| react-native     | Expo 32
| node             | 10.15.3
| npm or yarn      | 6.8.0

**Comment by jstansbe** [comment]
Also getting this error.

"react": "16.4.1",
"react-native": "0.55.4",
"react-native-gesture-handler": "1.0.14",
"react-navigation": "^3.0.2",

**Comment by Ananlabs** [comment]
i have this problem too :(

##########################################

React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (4) x64 Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
      Memory: 1.19 GB / 5.92 GB
    Binaries:
      Yarn: 1.16.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.4.1 - C:\Users\Ahmed\AppData\Roaming\npm\npm.CMD
    IDEs:
      Android Studio: Version  3.0.0.0 AI-171.4443003

##########################################

  "dependencies": {
    "axios": "^0.18.0",
    "native-base": "^2.12.1",
    "react": "16.6.3",
    "react-native": "0.57.8",
    "react-native-gesture-handler": "^1.2.1",
    "react-navigation": "^3.9.2",
    "react-redux": "6.0.1",
    "redux": "^4.0.1",
    "redux-thunk": "^2.3.0"
  },

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!

**Comment by spyshower** [comment]
@brentvatne Thank you.

**Comment by brentvatne** [comment]
noticed another thread about this so let's discuss there https://github.com/react-navigation/react-navigation/issues/5914
