### ISSUE TITLE
SwitchActions is not exported, even thou it's documented

### ISSUE THREAD

**Issue by lucasmotta** [react-navigation/react-navigation#5916]
### Current Behavior

Documentation mentions about SwitchActions and how to use it:
https://reactnavigation.org/docs/en/switch-actions.html

But it does not really exist on the latest version.

### Expected Behavior

`SwitchActions` should be exported by `react-navigation`. 

### Your Environment

```
Node: 11.14.0
Yarn: 1.15.2
react: 16.8.6
react-native: 0.59.5
react-navigation: 3.9.2
```

**Comment by brentvatne** [comment]
hello! I've added it now and published 3.10.1. I did not, however, add the typescript definition for it. feel free to!

**Comment by aIacoella** [comment]
I'm sorry. I did update react-navigation to 3.10.2 but it looks like SwitchActions is still not exported. Did I get something wrong or is it actually not exported?

**Comment by satya164** [comment]
It's exported in https://github.com/react-navigation/core/blob/bb6b740aa4727ebcfa1852cc20858928b80fcfed/src/index.js#L36

**Comment by aIacoella** [comment]
Oh, I see. I feel like this is a dumb question but do I need to install that separate module then? Otherwise how can I access that?

**Comment by satya164** [comment]
It's exported in `react-navigation` now.
