### ISSUE TITLE
how to go back to different stack

### ISSUE THREAD

**Issue by craigcosmo** [react-navigation/react-navigation#5920]
my stack is like this
```js
const HomeStack = createStackNavigator({
    Home: HomeScreen,
});

const CarStack = createStackNavigator({
    Booking: BookingScreen,
    Confirm: ConfirmScreen

});

export default createBottomTabNavigator({
    HomeStack,
    CarStack,
});
```

```js
export default class HomeScreen extends React.Component {
	goTo(){
	        this.props.navigation.navigate('Confirm')
	}
	render() {
		return (
			<View style={css.container}>
				<button onPress={this.goTo.bind(this)}>go to</button>
			</View>
		);
	}	
}



export default class ConfirmScreen extends React.Component {
	goBack(){
	        this.props.navigation.goBack()
	}
	render() {
		return (
			<View style={css.container}>
				<button onPress={this.goBack.bind(this)}>goback</button>
			</View>
		);
	}	
}
```

In home screen, when I click goto, it take me to confirmscreen, which is good.
But when I press go back, it takes me to booking screen instead of home screen. Which is bad.
It suppose to take me to home screen. What am i missing here?

**Comment by brentvatne** [comment]
history is specific to a stack. if you know where you want to go specifically, then just use `navigate` and it'll figure out if you need to move back/forward. if you want to go back in the parent navigator you can use `navigation.dismiss()` which is basically a shortcut for `navigation.goBack(navigation.dangerouslyGetParent().state.key)`

would be good to have better docs about using back  when there are multiple navigators.

**Comment by netgfx** [comment]
On the same note, is there a way to have a transition when using `.dismiss()`? To emulate the back transition?
