### ISSUE TITLE
State persistence and auth workflow: design flaws

### ISSUE THREAD

**Issue by alamothe** [react-navigation/react-navigation#5924]
The official recipe for authentication workflow: https://reactnavigation.org/docs/en/auth-flow.html creates a switch navigator, and loading screen as part of the navigator. Then, after auth state is loaded from storage, it decides where to navigate. 

This recipe is not compatible with state persistence: https://reactnavigation.org/docs/en/state-persistence.html. 

There, a function to load the state must be passed immediately when the root navigator is rendered. Additionally, it has separate means to render loading screen through `renderLoadingExperimental`.

**Out of the box, it is not possible to combine both the official auth recipe and state persistence.**

By the way, and may be considered a rant, I find that this library imposes a lot of restrictions on how certain problems can be solved, and makes it hard to think and code in the natural React way.

Possibly one way how to solve this is if the library allowed me to pass navigation state itself instead of the loading function. Then, I could load both auth and navigation states first, and decide what to pass. However, that means loading screen is no longer a part of the navigator, and I don't know if the library will play well with that (and the persistence feature would have to be changed again, obviously).

Another possible approach is to set complete navigation state through some other mean besides `loadNavigationState`. Is that possible?

Any other ideas? Thanks!

**Comment by brentvatne** [comment]
that's a good point, they don't play too nicely together. I think we need to have a different pattern for auth because it's also tricky to handle deep links with auth too, and the problems are related. i think the auth flow needs executed prior to handling deep links and loading persisted state. i'm away for a few weeks but if you want to open a rfc for how this can be nicely solved, please do.

as for the "rant", please keep feedback actionable. if you'd like to propose something concrete you're welcome to in rfcs. not sure what you expect to get from us by providing such feedback.

**Comment by alamothe** [comment]
> i think the auth flow needs executed prior to handling deep links and loading persisted state.

Thanks for the reply! That's what I actually ended up doing. This approach is:

- Rely on `renderLoadingExperimental` to render loading screen (loading screen is no more a part of navigators).
- Rely on `loadNavigationState` to load **everything** for the app (auth, fonts, images, persisted state).

Then, `loadNavigationState` can either return persisted state, but it's also free to send the user to some other route, say if the token expired. I achieve this by:

```js
if (/*... token expired ...*/) {
  return RootNavigator.router.getStateForAction(
    NavigationActions.navigate({ routeName: 'auth' })
  )
} else {
  return persistedState
}
```

So far it works nicely, and the code ends up simpler than the auth recipe in the docs.

(I don't use deep linking yet, so not sure how it'll fit in)

**Comment by alamothe** [comment]
...If this pattern sounds good, then these features (`renderLoadingExperimental` & `loadNavigationState`) only need to be marked non-experimental. 🙂

**Comment by mtsap** [comment]
Hey @alamothe, I have the same issue currently. Could you maybe provide a full example of how to use state persistence and managing auth navigation?

**Comment by brentvatne** [comment]
thank you for the follow up @alamothe! if you have time to provide a simple minimal example app of implementing this pattern it'd be really helpful. perhaps we could update our documentation for it accordingly!

**Comment by ManasN** [comment]
I'm facing the same problem too, in my case, I'm propping the main navigator component with said props in official docs for "State Persistence". My main navigator consists of switch navs which again contains many stacknavs and drawer navs. There is also an auth flow which occurs every time app is opened. However, I found that the key never gets created in the first place. Local storage stays empty.

**Comment by NawazKhanMd** [comment]
Please provide a sample code for our reference
