### ISSUE TITLE
Full screen modal inside tab navigator

### ISSUE THREAD

**Issue by alamothe** [react-navigation/react-navigation#5927]
My application is using "a stack navigator for each tab" recipe as described here: https://reactnavigation.org/docs/en/tab-based-navigation.html#a-stack-navigator-for-each-tab

I would like to open a full screen modal, with a back button and proper animations, and have tab bar not visible on this modal.

I have found two options in the doc:

### 1. Hide tab on specific screens in the inner stack navigator

https://reactnavigation.org/docs/en/navigation-options-resolution.html#a-tab-navigator-contains-a-stack-and-you-want-to-hide-the-tab-bar-on-specific-screens

This approach has issues with animation. When the modal is about to show, **first** tab is hidden, then modal starts sliding from the right. When back is pressed (or swiped from the left) the opposite will happen, **first** tab will appear then modal with slide to the right. 

This is really awkward. The tab bar should actually be a part of the sliding animation.

### 2. Put modal in the tab's parent stack navigator

https://reactnavigation.org/docs/en/modal.html. 

The problems with this approach are:
- Swiping from the left no longer works as back.
- There is no header. This is obviously due to:

```
		{
			mode: 'modal',
			headerMode: 'none',
		}
```

But if this is removed, double (or triple) header will appear.

**Is there any solution which does not suffer from described issues?**

Thanks!

**Comment by drewhamlett** [comment]
Hey @alamothe I'm in the same situation also.  I'm guessing a lot of the questions about hiding tabs over the years are actually related to this.  Right now to solve this issue I'm wrapping each modal or card that needs to be full screen in another stack navigator.  I'm not sure about performance but it should be ok.  Now this means you still don't get the right animations, but at least the header is there and you can put in back button yourself. We don't currently use text on the back button so I don't have to deal with having to know where the user came from.

I still have the situation where I need a full screen modal transition and full screen card transition(with header).  So not sure about that

```js
const CardStack = createStackNavigator(
  {
    CheckinShow: {
      screen: CheckinShowScreen
    },
  },
)

const RootStack = createStackNavigator(
  {
    Main: {
      screen: BottomTabNavigator,
    },

    CardStack: {
      screen: CardStack,
    },

    GroupStack: {
      screen: GroupStack,
     },
  },
  {
    headerMode: 'none',
  },
)

export default RootStack
```

**Comment by alamothe** [comment]
Hey @drewhamlett, thanks for your reply!

We ended up with a similar approach. I found a small shortcut:

```typescript
function createMainNavigator() {
	return createStackNavigator(
		{
			Tab: {
				screen: createTabNavigator(),
				navigationOptions: {
					// No header on tab (prevent double header)
					header: null,
				}
			},
			[SomeModal.name]: {
				screen: SomeModal,
			},
		},
		{
			// Make modal appear from bottom, disables swiping from the left
			mode: 'modal',
			// headerMode: 'none',
			defaultNavigationOptions: ...,
		}
	);
}
```

Instead of setting `headerMode` to `none` which has a "global" effect, I specifically only disable the header on tab screen. This way, a nested stack navigator is not necessary.

Note that I changed the modal to appear from the bottom, and instead of "Back" button I decided to render a "Cancel" button instead.

I considered for a long time whether to go with rendering the header myself approach. It's not just for reasons mentioned in this issue. Another big pain with `react-navigation`'s header is that it's separate from the contents and it makes it tricky to communicate between the header and contents. I'm sure you encountered this problem too.

However, looking at the code, it looks very difficult to separate just header from `react-navigation`, it's just too entangled. There are some libraries out there which have a header component, but either it does not meet the high standard of `react-navigation` header or I didn't want to mix the stylings.

**Comment by drewhamlett** [comment]
Hey @alamothe, thats a good idea.  I didn't know you could do that.  We currently just punted having a card stack slide over tab bar for now.  But I think I'll play some more with your idea.   As far as the header you can actually take the Header component from react-navigation and render it.

https://github.com/react-navigation/stack/blob/d1d0cfb53f26090c83c95dda0e2053205823f68b/src/views/StackView/StackViewLayout.tsx#L220

```tsx
GroupSelectFriendsScreen.navigationOptions = ({ navigation }) => {
  return {
    header: props => (
      <View>
        <Header {...props} />
        <View style={{ backgroundColor: color('yellow'), padding: space(2) }}>
          <TextInput
            onChangeText={text => {
              selectFriendsStore.search(text)
            }}
            placeholderTextColor={color('grays.3')}
            placeholder={t('search_your_friends')}
            style={{
              backgroundColor: color('white'),
              paddingVertical: space(1),
              paddingHorizontal: space(2),
              borderRadius: 3,
            }}
          />
        </View>
      </View>
    ),
    ...headerStyleNoBorder,
  }
}

You want to render the stuff that's suppose to be in header in the actual header as opposed below it in the view, because it makes the transitions less weird.

And talking about communicating, we are currently using mobx-state-tree, but context api and redux can also solve it.  I think it's mentioned in docs somewhere.  You end up having to reach for some external state system in native apps anyway honestly because the setting navigation params gets old very fast.  We started with context API for communication but switched to mobx and mobx-state tree because it's just too much of a mind fuck to optimize.

Good luck

```

**Comment by 3rdp** [comment]
>https://reactnavigation.org/docs/en/navigation-options-resolution.html#a-tab-navigator-contains-a-stack-and-you-want-to-hide-the-tab-bar-on-specific-screens
This approach has issues with animation.

True. I decided to just navigate from tab screen to stack. StackNavigator is parent of TabNavigator and has `transitionConfig` implemented as below to make some screens slide in from the bottom:
```
const IOS_MODAL_ROUTES = ['/modal1', '/modal2'];
const dynamicModalTransition = (transitionProps, prevTransitionProps) => {
  const isModal = IOS_MODAL_ROUTES.some(
    screenName =>
      screenName === transitionProps.scene.route.routeName ||
      (prevTransitionProps && screenName === prevTransitionProps.scene.route.routeName)
  );
  return StackViewTransitionConfigs.defaultTransitionConfig(
    transitionProps,
    prevTransitionProps,
    isModal
  );
};
```
This is from the docs: https://reactnavigation.org/docs/en/stack-navigator.html#specifying-the-transition-mode-for-a-stacks-screens-explicitly

> Swiping from the left no longer works as back.
    There is no header.

You need to also set `gesturesEnabled: false` on the stack navigator and implement your own custom header. Then animations will work with rock solid reliability.

**Comment by ZaidAbo** [comment]
same issue here
