### ISSUE TITLE
createBottomTabNavigator backgroundColor is not changing 

### ISSUE THREAD

**Issue by MaheshNandam** [react-navigation/react-navigation#5928]
I had given the borderTopLeftRadius and borderTopRightRadius with the below the code, but still, createBottomTabNavigator couldn't able to change backgroundColor, Did I missed anything to make it proper?

```
tabBarOptions: {
      activeTintColor: "rgb(245,87,108)",
      inactiveTintColor: "rgba(0,0,0,0.41)",
      style: {
        borderTopLeftRadius: 30,
        borderTopRightRadius: 30,
        borderTopColor: "#fff",
        borderTopWidth: 0.5,
        width: width,
        backgroundColor: "#fff",
        shadowColor: "rgba(0, 0, 0, 0.19)",
        shadowOffset: {
          width: 0,
          height: 6
        },
        shadowRadius: 30,
        elevation: 5,
        shadowOpacity: 1,
        height: 55
      },
      tabStyle: {
        alignItems: "center",
        justifyContent: "center",
        paddingVertical: 4,
        backgroundColor: "#fff",
        borderTopLeftRadius: 30,
        borderTopRightRadius: 30,
      }
    },
```

My task is to make a createBottomTabNavigator tab with transparent backgroundColor even with border-radius.

Thanks to the savior.

![Image from iOS](https://user-images.githubusercontent.com/13198616/58021006-6fbb5600-7b27-11e9-9700-d9335ed7e79e.jpg)

**Comment by satya164** [comment]
`position: 'absolute'`

**Comment by webuijorgeGL** [comment]
> `position: 'absolute'`

Perfect. Thanks, man.

**Comment by enzzoperez** [comment]
With custom tabBar its also worked, thanks!
