### ISSUE TITLE
CreateBottomStackNavigator listeners doesn't fire

### ISSUE THREAD

**Issue by MinaFSedrak** [react-navigation/react-navigation#5933]
### Current Behavior
CreateBottomTabNavigator listeners doesn't work correctly within a stack navigator on iOS & android production release.

### Expected Behavior
CreateBottomTabNavigator listeners works inside a stack navigator.

### Description
My problem is when i archive a **PRODUCTION** release, tabBarComponent **LISTENER** doesn't works correctly & the custom component **LIFECYCLE** doesn't fire. 

My project structure starting with root StackNavigator which looks like
```
const MainStackNavigator = createStackNavigator( 
    {
        launchScreen: {
            screen: LaunchScreen
        },
        authStackNavigator: {
            screen: AuthStackNavigator
        },
        tabNavigator: {
            screen: myTabNavigator
        }
    },
    {
        initialRouteName: 'launchScreen',
        headerMode: 'none'
    }
);
```

Then with second tabNavigator layer using custom tabBarComponent looks like
```
const MyTabNavigator = createBottomTabNavigator(
    {
        Dashboard: {
            screen: DashboardStackNavigator
        },
        Kalender: {
            screen: EventStackNavigator
        },
        Information: {
            screen: NewsStackNavigator
        },
        Services: {
            screen: ServicesStackNavigator
        },
        Betriebsrat: {
            screen: BRStackNavigator
        }
    },
    {
        navigationOptions: ({ navigation }) => ({
            gesturesEnabled: false,
        }),
        tabBarOptions: {
            activeTintColor: COLORS.BABY_BLUE,
            inactiveTintColor: COLORS.GRAY16,
            activeBackgroundColor: COLORS.WHITE,
            inactiveBackgroundColor: COLORS.WHITE,
            tabBarHideShadow: false
        },
        tabBarComponent: (props)=> { return <TabBar {...props} /> },
        tabBarPosition: 'bottom',
        animationEnabled: false,
        swipeEnabled: false,
        lazy: false
    }
);
```  

### Environment
    Binaries:
      Node: 10.14.1
      Yarn: 1.15.2
      npm: 6.9.0 
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.1 => 0.59.1
      react-navigation: 3.5.1
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

**Comment by nicholasc** [comment]
Did you find a solution to this?
