### ISSUE TITLE
DRAWER NAVIGATOR DONT WORK

### ISSUE THREAD

**Issue by wxkz** [react-navigation/react-navigation#5934]
MY CODE :::::::::::::::::

`
import React from "react";
import Icon from 'react-native-vector-icons/FontAwesome5'
import Icon2 from 'react-native-vector-icons/MaterialIcons'

import {
  createBottomTabNavigator,
  createStackNavigator,
  createAppContainer,
  createSwitchNavigator,
  createDrawerNavigator,
} from 'react-navigation';

import HomeScreen from './homeTab/homeScreen'
import BuyScreen from "./buyTab/buyScreen"
import PsalmsScreen from './psalmsTab/psalmsScreen'
import LoginScreen from './authTab/loginScreen'
import RegisterScreen from './authTab/registerScreen'
import GroupScreen from './groupsTab/groupScreen'
import AddUserToGroupScreen from './groupsTab/addUserToGroup'
import userGroupsScreen from './groupsTab/userGroups'
import SettingsScreen from './settingsTab/settingsScreen'

const DrawerNavigator = createDrawerNavigator({
  Settings: {
    screen: SettingsScreen,
  },
})

const HomeStack = createStackNavigator({
  Home: { screen: HomeScreen },
})

const GroupStack = createStackNavigator({
  Groups: userGroupsScreen,
  Group: { screen: GroupScreen },
  AddUserToGroup: AddUserToGroupScreen,
})

const BuyStack = createStackNavigator({
  Buy: { screen: BuyScreen },
})

const PsalmsStack = createStackNavigator({
  Psalms: { screen: PsalmsScreen },
})

const TabNavigator = createBottomTabNavigator(
  {
    Progamação: HomeStack,
    Grupos: GroupStack,
    Lojinha: BuyStack,
    Salmos: PsalmsStack,
  },
  {
    defaultNavigationOptions: ({ navigation }) => ({
      tabBarIcon: ({ focused, horizontal, tintColor }) => {
        const { routeName } = navigation.state
        if (routeName === 'Progamação'){
          iconName = 'home'
        } else if (routeName === 'Lojinha') {
          iconName = 'shopping-basket'
        }
        else if (routeName === 'Salmos') {
          iconName = 'book-open'
        }
        else if (routeName === 'Grupos') {
          iconName = 'group'
          return <Icon2 name={iconName} size={25} color={tintColor}/>
        }
        return <Icon name={iconName} size={25} color={tintColor}/>
      }
    }),
    tabBarOptions:{
      activeTintColor: '#3480f9',
      inactiveTintColor: 'white',
      tabStyle:{
        backgroundColor: '#4a4b4c'
      }
    }
  },
)

const AuthScreen = createStackNavigator({
  Login: LoginScreen,
  Register: RegisterScreen,
})

export default createAppContainer(createSwitchNavigator({
  Auth: AuthScreen,
  Drawer: DrawerNavigator,
  TabNavigator: TabNavigator,
})
)
`

**Comment by brentvatne** [comment]
please follow the issue template
