### ISSUE TITLE
How to write a custom navigator in Typescript with type-checking

### ISSUE THREAD

**Issue by nartc** [react-navigation/react-navigation#5937]
Hi React-Navigation team and community,

I'm new to React Native but for the little time that I've had with RN, I found that React Navigation provides a very clean API for RN's Navigations. I'm using TypeScript for my React projects.

Lately, I've been looking into Custom Navigators and how to build them with type-checking. Would anyone be able to point me in the right direction for building custom navigator with type-checking? 

I've looked at this repo: https://github.com/brentvatne/animated-bottom-navigation-example but I haven't been able to succeed.

Thanks

**Comment by brentvatne** [comment]
we don't have any documentation on this right now, you may be best off referring to https://github.com/react-navigation/drawer which is written entirely in typescript.

**Comment by brentvatne** [comment]
tried to transfer this to the docs repo but "Transfer issue" appears to be broken on Github atm, can't find any repos in the list when I search :\

**Comment by nartc** [comment]
@brentvatne Thanks for pointing me to the drawer repo. I'll give that a closer look. I'll go back to this issue and update with any findings :)

**Comment by nartc** [comment]
@brentvatne Hi again, I've been trying to get this going but unfortunately, I've hit another blocker. 

![image](https://user-images.githubusercontent.com/25516557/58733759-0525d800-83bb-11e9-8f37-979415d31c2a.png)
Where are all those Props come from for TabBar? When I try to implement my custom NavigationView, I only have 4 props which were specified here: 
![image](https://user-images.githubusercontent.com/25516557/58733790-1ec71f80-83bb-11e9-88cb-152c4d683220.png)

Any pointers? And also, what would be the strategy to renderScene with nested navigators?
