### ISSUE TITLE
Push quickly will jump twice

### ISSUE THREAD

**Issue by CocoaZX** [react-navigation/react-navigation#5938]
## The issue tracker is reserved for bug reports only.

Push quickly will jump twice.
We want like A push B , B push C , C push A. Then every page can pop to the page tho push them.

If use navigate() to replace push() , will make a bug, A push B , B push C , C pop A. A can't pop B

---

### Current Behavior

 A push B , B push C , C push A. But will push more than one time if you click it quick.

### How to reproduce
Use method push and click  quick every page

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |newest
| react-native     |newest
| node             |newest
| npm or yarn      |newest

**Comment by matthamil** [comment]
This is the [expected behavior](https://reactnavigation.org/docs/en/stack-actions.html#push). If you do not want this behavior, stick to using `navigation.navigate('RouteName')`.

**Comment by CocoaZX** [comment]
I want push behavior ,but when tap quick ,it will push more than onetime ,I want push only once ,even tap 100times at 1 sec

**Comment by matthamil** [comment]
You should look into a throttle or debounce wrapper around whatever is calling `navigation.push`

**Comment by matthamil** [comment]
otherwise, use `navigation.navigate` since it does add history to the stack (w/o being 100% like push)

**Comment by CocoaZX** [comment]
I want to change push method ,but I cant find where to change it. Not found the where code implementation push method

**Comment by CocoaZX** [comment]
I will fix this with change source code.
Make the push method will response once in 0.5 seconds.
Will this is the right way to resolve this? If so, please merge my commit ,or can u tell me how to resolve

**Comment by matthamil** [comment]
You should use a throttle or debounce that wraps the call to navigation.push in your code if you want to limit the push to once every 0.5 seconds.

**Comment by CocoaZX** [comment]
But every page navigation is a new one, set in their props, right? How can I fix all of them？

change withMappedNavigationProps() with a other HOC compent?

**Comment by matthamil** [comment]
I am not sure I understand your question @CocoaZX . I recommend posting on Stackoverflow or joining the [Reactiflux](https://www.reactiflux.com/) community and asking your question there.

**Comment by CocoaZX** [comment]
Thank you , I fix this with wraps Component. But I have to import to every page code.My question is not sure this is the good way to solve it.

`export default function midPush() {
  return function mid(Component) {
    return class _ extends BaseComponent {
      render() {
        const { navigation } = this.props;
        const { push } = navigation;
        let time = Date.now();
        navigation.push = (...arg) => {
          const timeNow = Date.now();
          if (timeNow - time > 500) {
            push(...arg);
            time = timeNow;
          }
        };
        return <Component {...this.props} />;
      }
    };
  };
}
`

**Comment by CocoaZX** [comment]
Why my code does't auto insert newline?

**Comment by byk04712** [comment]
@CocoaZX 


\`\`\` 
	code
	write here
\`\`\`



```
export default function midPush() {

	return function mid(Component) {

		return class _ extends BaseComponent {

			render() {
				const { navigation } = this.props;
				const { push } = navigation;
				let time = Date.now();
				
				navigation.push = (...arg) => {
					const timeNow = Date.now();
					if (timeNow - time > 500) {
						push(...arg);
						time = timeNow;
					}
				};

				return <Component {...this.props} />;
			}
		};
	};
}
```
