### ISSUE TITLE
Dumb component in StackNavigator

### ISSUE THREAD

**Issue by higor-correa** [react-navigation/react-navigation#5945]
I'm trying to use the createStackNavigator and one of my screen is a dumb component.
So I'm getting this error: 
> Functions are not valid as a React child. This may happen if you return a Component instead of <Component /> from render. Or maybe you meant to call this function rather than return it.

Does anyone know if I can not use a dumb component as a screen of StackNavigator?

As dumb component I mean something like:
`export default Foo = () => (<View>:D</View>)`

**Comment by eriveltonelias** [comment]
Hi @higor-correa, 

this error means that your screen component is not valid.

check this https://facebook.github.io/react-native/docs/text#docsNav

I just created a example for this https://snack.expo.io/@eriveltonelias/functional-screen

**Comment by higor-correa** [comment]
Thanks @eriveltonelias i was forgetting to use the `createAppContainer` and use it "as a tag".
It's working now!!!
😗
