### ISSUE TITLE
funky defaultNavigationOptions behavior

### ISSUE THREAD

**Issue by pvinis** [react-navigation/react-navigation#5946]
I have made this following snack to demonstrate.
https://snack.expo.io/@pvinis/intrigued-milkshake

### Current Behavior
The main thing to notice here are these:
- `HomeScreen` and `SettingsScreen` have `tabBarOnLongPress: () => Alert.alert('from screen')` in their `navigationOptions`
- `SettingsStack` has `tabBarOnLongPress: () => Alert.alert('from stack')` in its `navigationOptions`
- `createBottomTabNavigator` has `tabBarOnLongPress: () => Alert.alert('from tab default')` in its `defaultNavigationOptions`
- The tabs are: Home **Stack** with just the home screen, Settings **Screen**, and Settings **Stack** with just the settings screen

When long-pressing the first tab, we get an alert from the `tab default`.
When long-pressing the second tab, we get an alert from the `screen`.
When long-pressing the third tab, we get an alert from the `stack`.

### Expected Behavior
When long-pressing the first tab, we should get an alert from the `screen`, specifically the home screen. But we dont, because the tab nav and the home screen have the stack nav in between, which causes it to "lose" the `defaultNavigationOptions`.

When long-pressing the second tab, all is well, we should get an alert from the `screen`. That case is correct.

When long-pressing the third tab, we should again get an alert from the `screen`, specifically the settings screen. The tab nav has the `defaultNavigationOptions`, which then the stack nav overrides and merges (I guess) with its `navigationOptions`, and we get the alert from there. On top of that, the screen should be again overriding with its own `navigationOptions`, so we should be getting the alert from the screen.

### How to reproduce

Here is a snack for repro.
https://snack.expo.io/@pvinis/intrigued-milkshake

### Your Environment
Snack

**Comment by brentvatne** [comment]
this is the expected behavior. we only look one level deep for navigation options, in this case on the home tab we look at the home stack itself, we don't look at HomeScreen. if you'd like to drill deeper than the immediate child route then you need to use `getActiveChildNavigationOptions` to be explicit about it: https://reactnavigation.org/docs/en/navigation-options-resolution.html#getactivechildnavigationoptions
