### ISSUE TITLE
Modal dismissal in stack navigators with dynamic transitions behave incorrectly

### ISSUE THREAD

**Issue by alexpyoung** [react-navigation/react-navigation#5947]
### Current Behavior

- For screens specified as a modal in stack navigators with dynamic transition configurations, the gesture recognizer uses a push style (swipe left/right) as opposed as a modal style (swipe down) for dismissal. The screen itself still presents and dismisses from the bottom of the screen as expected. 

### Expected Behavior

- I should not be able to swipe right to dismiss a modal
- I should be able to swipe down to dismiss a modal

### How to reproduce

This behavior can be reproduced by applying the [example dynamic config](https://reactnavigation.org/docs/en/stack-navigator.html#specifying-the-transition-mode-for-a-stack-s-screens-explicitly) to the [playground app](https://github.com/react-navigation/react-navigation/tree/master/examples/NavigationPlayground):

https://github.com/react-navigation/react-navigation/compare/master...alexpyoung:master

### Your Environment

```
React Native Environment Info:
  System:
    OS: macOS High Sierra 10.13.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 166.48 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 8.15.1 - ~/.nvm/versions/node/v8.15.1/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v8.15.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
  IDEs:
    Android Studio: 3.4 AI-183.5429.30.34.5452501
    Xcode: 10.1/10B61 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.5.0 => 16.5.0
    react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1
```

**Comment by brentvatne** [comment]
indeed this is the case and we won't fix it in this version of react-navigation. you should nest stacks for modals instead of using a dynamic config if you need this behavior.
