### ISSUE TITLE
TypeError: _ReanimatedModule.default.animateNextTransition is not a function

### ISSUE THREAD

**Issue by StudyTae** [react-navigation/react-navigation#5951]
## The issue tracker is reserved for bug reports only.

If you have a question, feature request, or an idea for improving the library or its related tools, please try one of the following resources:

- [Read the documentation](https://reactnavigation.org/)
- [Post an issue to the website repository if you'd like to see a documentation change](http://github.com/react-navigation/website)
- [Post a feature request to Canny](https://react-navigation.canny.io/feature-requests)
- [Write a RFC if you have ideas for how to implement a feature request](https://github.com/react-navigation/rfcs)
- [Get help on Discord chat (#react-navigation on Reactiflux)](https://discord.gg/4xEK3nD) or [on StackOverflow](https://stackoverflow.com/questions/tagged/react-navigation)
- Search for your issue - it may have already been answered or even fixed in the development branch. However, if you find that an old, closed issue still persists in the latest version, you should open a new issue.

Bugs with react-navigation must be reproducible *without any external libraries that operate on it*. This means that if you are attempting to use Redux or MobX with it and you think you have found a bug, you must be able to reproduce it without Redux or MobX in this report. Redux related issues belong in [react-navigation-redux-helpers](https://github.com/react-navigation/react-navigation-redux-helpers), and we do not have any first-class integration with MobX at the moment.

---

### Current Behavior

![스크린샷 2019-05-30 오후 5 06 46](https://user-images.githubusercontent.com/45538347/58618345-64251780-82fd-11e9-8b5f-596fe45ced37.png)

> **When you click on the text, you get an error with the title.**

### Expected Behavior

- What do you expect should be happening?
- Include a screenshot if it makes sense.

### How to reproduce

App.js
~~~js
import React from "react";
import createAnimatedSwitchNavigator from "react-navigation-animated-switch";
import { Transition } from "react-native-reanimated";
import {
  createDrawerNavigator,
  createAppContainer,
  createStackNavigator
} from "react-navigation";
import A from "./A";
import B from "./B";

const MySwitch = createAnimatedSwitchNavigator(
  {
    Home: A,
    Other: B
  },
  {
    initialRouteName: "Home",
    headerMode: "none"
  },
  {
    // The previous screen will slide to the bottom while the next screen will fade in
    transition: (
      <Transition.Together>
        <Transition.Out
          type="slide-bottom"
          durationMs={400}
          interpolation="easeIn"
        />
        <Transition.In type="fade" durationMs={500} />
      </Transition.Together>
    )
  }
);
const HomeScreenRouter = createAppContainer(MySwitch);

export default HomeScreenRouter;
~~~

A.js
~~~js
import React from "react";
import { StyleSheet, Text, View, TouchableHighlight } from "react-native";

export default class A extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      loading: false
    };
  }

  render() {
    return (
      <View style={styles.container}>
        <Text onPress={() => this.props.navigation.navigate("Other")}>
          Open up App.js to start working on your app!
        </Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center"
  }
});
~~~

B.js
~~~js
import React from "react";
import { StyleSheet, Text, View } from "react-native";

export default class B extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      loading: false
    };
  }

  render() {
    return (
      <View style={styles.container}>
        <Text>B screen</Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center"
  }
});
~~~

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  "^3.11.0"
| react-native     | "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz"
| node             |  v10.16.0
| react-native-reanimated | "^1.0.1"
| react-navigation-animated-switch | "^0.2.0"
| npm or yarn      | 6.9.0

**Comment by brentvatne** [comment]
you'll need to wait for expo sdk 33 to use this, as it's not currently available in sdk 32. sdk 33 is coming very soon! note that this is documented in the readme :) https://github.com/react-navigation/animated-switch#installation

thanks for the good issue report though!

**Comment by gstcarv** [comment]
I have the same error, but i'm not using expo, my RN version is 0.58.0
