### ISSUE TITLE
Cannot send param hen navigating from Drawer to Stack

### ISSUE THREAD

**Issue by mharrisweb** [react-navigation/react-navigation#5952]
### Current Behavior

I get undefined params when using:

```
     <Text
              onPress={() => {
                this.props.navigation.navigate("VideoPlayer", { video: video });
              }}
              style={styles.text}
            >
```
I get undefined in my component when I try and get param:

`this.props.navigation.state.params.video`

### How to reproduce

https://snack.expo.io/@mharrisweb/insane-cake

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.0.9
| react-native     | 0.57.1
| node             | 10.15.3
| npm or yarn      | 6.9.0

**Comment by SourceCipher** [comment]
I am having an issue trying to pass param from the store to the auth screen. It always returns undefined..

**Comment by mptorz** [comment]
I have the same issue. `getParams` always returns `undefined` when navigating from drawer content component to any stack.

**Comment by brentvatne** [comment]
you can pass params to the screen you're actually going to, not the navigator that contains that screen. 

related:
- https://github.com/react-navigation/react-navigation.github.io/issues/374
- https://github.com/react-navigation/rfcs/issues/68
