### ISSUE TITLE
Performance issue on StackNavigator

### ISSUE THREAD

**Issue by vatex** [react-navigation/react-navigation#5953]
Hi!

I have the latest version of everything.
I use react-navigation.

I have Stack Navigator. Inside stack navigator, there is drawer navigator. Inside drawer navigator, there is stack navigator. That means I have nested navigation. It is slow when I am on the third level of navigation: Stack Navigator > Drawer Navigator > Stack Navigator.

I found old issues about this issue, but it seems they are not fixed.
https://github.com/react-navigation/react-navigation/issues/31
https://github.com/react-navigation/react-navigation/issues/672
https://github.com/react-navigation/react-navigation/issues/706
https://github.com/react-navigation/react-navigation/issues/608

Don't ask me to reproduce the issue, I am working on a big project and it's impossible to start working on a reproduction. Deadline is coming :3

**Comment by matthamil** [comment]
Bug reports like this simply aren't actionable without a reproducible example. If you can reproduce the problem you are experiencing, please open a new issue.
