### ISSUE TITLE
Tapping on status button on top screen of stack triggers scrollsToTop on other screens

### ISSUE THREAD

**Issue by donysukardi** [react-navigation/react-navigation#5954]
### Current Behavior

- What code are you running and what is happening?
- Include a screenshot if it makes sense.

I have a StackNavigator with a Scrollable (SectionList) on one screen and then an empty screen.

Upon navigating from the SectionList to the second screen, tapping on the status bar on second screen actually scrolls the list in the first screen to the top

![scroll-to-top](https://user-images.githubusercontent.com/410792/58743227-43290780-8460-11e9-9064-6c2bb093dc85.gif)

### Expected Behavior

Tapping on the status bar on screen on the top of the stack shouldn't trigger scrollsToTop for rest of the screens in the stack.

Currently I could get around this by assigning navigation focus state `isFocused` to `scrollsToTop`.

### How to reproduce

https://snack.expo.io/@donysukardi/sponaneous-marshmallows

* Scrolls down the list, tap on any of the item down the list.
* Tap on the status bar
* Tap on < Back
* List scroll position is now reset to top 

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.11.0

**Comment by donysukardi** [comment]
I can submit a pull request to `react-navigation/native` to force `scrollsToTop={false}` when the screen is not focused, if that's the desired approach

**Comment by brentvatne** [comment]
if you use react-native-screens then this should not happen

```
import { useScreens } from 'react-native-screens';
useScreens();
```

**Comment by matthamil** [comment]
Hello! I am closing this issue since there hasn't been a response since a maintainer has responded with a solution. If you are still experiencing issues, do not hesitate to open a new issue. Thank you!
