### ISSUE TITLE
useScreens not working correctly with nested navigators

### ISSUE THREAD

**Issue by dominicstop** [react-navigation/react-navigation#5955]
Recently Expo upgraded the Expo Client in preparation for supporting SDK 33 - ([Updated Expo client available on App Store and Play Store](https://blog.expo.io/updated-expo-client-available-on-app-store-and-play-store-8747bd3a1364))

As noted in the [CHANGELOG](https://github.com/expo/expo/blob/master/CHANGELOG.md), one of the changes is bumping the version of react-native-screens from *1.0.0-alpha.15* to *1.0.0-alpha.22*.

### Current Behavior

I followed this guide: [Common mistakes · React Navigation](https://reactnavigation.org/docs/en/common-mistakes.html) for Explicitly rendering more than one navigator. I had this problem when using `useScreens()` where, `screenX` inside `navigatorB` nested inside `navigatorA` is not being rendered (all i get is a blank screen, but all of the logic inside of it is being executed normally, but it’s just not visible.) This used to work before the update.

I made an expo [snack](https://snack.expo.io/@dominicstop/react-native-screens) to show the issue using the code example from react-navigation.

Here's a screenshot of the snack running on the iPhone 6+ simulator without `useScreens()` (iOS 12.1 - expo client: 2.11.0.106093 i.e the newest update - with the current version of react-native-screens: 1.0.0-alpha.22):
![Simulator Screen Shot - iPhone 6 Plus - 2019-06-01 at 11 03 10](https://user-images.githubusercontent.com/18517029/58743493-29d68a00-8465-11e9-896a-c270da45c434.png)

Here it is again but with `useScreens()`:
![Simulator Screen Shot - iPhone 6 Plus - 2019-06-01 at 11 03 28](https://user-images.githubusercontent.com/18517029/58743498-496db280-8465-11e9-91ee-b3a30a218437.png)

I encountered it first on react-navigation v2 after updating the expo app, so I tried upgrading to v3 but it doesn’t seem to have fixed it yet.

### Expected Behavior

It used to work before in the previous update.
Here's a screenshot of the same snack running on an older version of the expo client with or without `useScreens()` (iPhone 6 iOS 12.1 simulator - expo client: 2.10.0.105125 i.e before the update - with react-native-screens 1.0.0-alpha.15 ):
![Simulator Screen Shot - iPhone 6 - 2019-06-01 at 11 18 33](https://user-images.githubusercontent.com/18517029/58743454-fc3d1100-8463-11e9-91c6-8aa182eea7c0.png)

### How to reproduce

* Snack: https://snack.expo.io/@dominicstop/react-native-screens
* Comment/Uncomment `useScreens()` on line 9

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^3.11.0
| react-native     | 0.57
| node             |  v10.4.0
| npm or yarn      | npm

I’m not sure if this is a problem with react-navigation or react-native-screens. Hoping for a solution soon! 😊

(sorry for the grammatical errors, english isn’t really my native language + this is also my first time posting an issue on github 😅)

**Comment by dominicstop** [comment]
For now, since useScreens works in the older version of expo, i added this as a temporary "fix" 😂

```
import { Constants } from 'expo';
const expoVersion = Constants.expoVersion;
const version = parseFloat(expoVersion.slice(0,4));

if(version <= 2.1){
  //use native navigation
  useScreens();
};
```

**Comment by nottmey** [comment]
Some Expo users are experiencing this issue with their default build and using expo app 2.11.0.
 #[https://github.com/expo/expo/issues/4371](https://github.com/expo/expo/issues/4371)

**Comment by heysailor** [comment]
Should be fixed now in a new Expo app release mentioned in link above.
