### ISSUE TITLE
Invariant Violation: Invariant Violation: Text strings must be rendered within a <Text> component.

### ISSUE THREAD

**Issue by fradrick** [react-navigation/react-navigation#5956]
Navigation:
import {
    createStackNavigator,
    createAppContainer
} from 'react-navigation'
import Home from '../Home'
import Friends from "../Friends";

const RootStack = createStackNavigator({
    Home: {
        screen: Home
    },
    Friends: {
        screen: Friends
    }
});

const AppNavigator = createAppContainer(RootStack);

export default AppNavigator;

Home:
import React from "react"
import { StyleSheet, Text, View, Button } from "react-native"

export default class Home extends React.Component{
    render() {
        return (
            <View>
                We have no friends!
            </View>
        );
    }
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#fff",
        alignItems: "center",
        justifyContent: "center",
    },
});

Friends:
import React from "react"
import {StyleSheet, Text, View, Button} from "react-native"

export default class Friends extends React.Component{
    render() {
        return (
            <View>
                Add friends here!
            </View>
        );
    }
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#fff",
        alignItems: "center",
        justifyContent: "center",
    },
});

This error is located at:
    in RCTView (at View.js:44)
    in Home (at SceneView.js:9)
    in SceneView (at StackViewLayout.tsx:888)
    in RCTView (at View.js:44)
    in RCTView (at View.js:44)
    in RCTView (at View.js:44)
    in AnimatedComponent (at StackViewCard.tsx:93)
    in RCTView (at View.js:44)
    in AnimatedComponent (at screens.native.js:59)
    in Screen (at StackViewCard.tsx:80)
    in Card (at createPointerEventsContainer.tsx:95)
    in Container (at StackViewLayout.tsx:971)
    in RCTView (at View.js:44)
    in ScreenContainer (at StackViewLayout.tsx:383)
    in RCTView (at View.js:44)
    in AnimatedComponent (at StackViewLayout.tsx:379)
    in Handler (at StackViewLayout.tsx:372)
    in StackViewLayout (at withOrientation.js:30)
    in withOrientation (at StackView.tsx:103)
    in RCTView (at View.js:44)
    in Transitioner (at StackView.tsx:40)
    in StackView (at createNavigator.js:61)
    in Navigator (at createKeyboardAwareNavigator.js:12)
    in KeyboardAwareNavigator (at createAppContainer.js:429)
    in NavigationContainer (at App.js:7)
    in App (at withExpoRoot.js:22)
    in RootErrorBoundary (at withExpoRoot.js:21)
    in ExpoRootComponent (at renderApplication.js:34)
    in RCTView (at View.js:44)
    in RCTView (at View.js:44)
    in AppContainer (at renderApplication.js:33)

This error is located at:
    in NavigationContainer (at App.js:7)
    in App (at withExpoRoot.js:22)
    in RootErrorBoundary (at withExpoRoot.js:21)
    in ExpoRootComponent (at renderApplication.js:34)
    in RCTView (at View.js:44)
    in RCTView (at View.js:44)
    in AppContainer (at renderApplication.js:33)

**Comment by vonovak** [comment]
hi! this is not a bug with react-navigation. As the error message explains, you need to make sure that every text you render is wrapped in `<Text>` tags.

```
export default class Home extends React.Component{
render() {
return (

We have no friends!

);
}
```

change the return to `<Text>We have no friends!</Text>`
