### ISSUE TITLE
Tab navigator slow in nested Stack Navigator

### ISSUE THREAD

**Issue by andrewchristt** [react-navigation/react-navigation#5957]
Im quite new to this react environtment, and found slowness in tab navigator if its nested, JS fps down to 10-20 fps when i switch between tabs ( the lag only occur on the indicator tab, but the screen behave as expected ). if the tab navigator is the main nav, its become fast and no lagging or delay. So i suspect its because of nested stack? thanks before

### Current Behavior
Tab navigator so slow in transition between tabs (swipe or click) if its nested in stacknavigator ( fps around 10-20) but become normal (50-60) if its the main nav

### Expected Behavior
Behave the same when the tab navigator is main nav

### How to reproduce
please use this to reproduce, its show fps around 10-20 (i use drawer and tab icon in the actual code and it become worse to 0-15fps)

````
class A extends Component {
    render() {
        return (
            <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
                <Text>this is A tab</Text>
            </View>
        );
    }
}

class B extends Component {
    render() {
        return (
            <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
                <Text>this is B tab</Text>
            </View>
        );
    }
}

class C extends Component {
    render() {
        return (
            <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
                <Text>this is C tab</Text>
            </View>
        );
    }
}

class Login extends Component {
    render() {
        return (
            <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
                <Text>this is login screen</Text>
                <Button
                    title='Login'
                    onPress={() => this.props.navigation.navigate('Dashboard')}
                />
            </View>
        );
    }
}

class Home extends Component {
    render() {
        return (
            <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
                <Text>this is Home tab</Text>
                <Button
                    title='School'
                    onPress={() => this.props.navigation.navigate('SD')}
                />
            </View>
        );
    }
}

class Setting extends Component {
    render() {
        return (
            <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
                <Text>this is setting screen</Text>
                <Button
                    title='School'
                    onPress={() => this.props.navigation.navigate('SD')}
                />
            </View>
        );
    }
}

class Profile extends Component {
    render() {
        return (
            <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
                <Text>this is profile tab</Text>
                <Button
                    title='School'
                    onPress={() => this.props.navigation.navigate('SD')}
                />
            </View>
        );
    }
}

class SD extends Component {
    render() {
        return (
            <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
                <Text>this is SD screen</Text>
                <Button
                    title='Go to class top tab'
                    onPress={() => this.props.navigation.navigate('ClassroomTab')}
                />
            </View>
        );
    }
}

const ClassTopTabNavigator = createMaterialTopTabNavigator(
    {
        A: A,
        B: B,
        C: C,
    },
)
const AppNavigator = createStackNavigator(
    {
        Login: Login,
    },
    {
        initialRouteName: "Login",
    },
);

// @desc  Profile route stack
const ProfileNavigator = createStackNavigator(
    {
        Profile: {
            screen: Profile,
        },
    },
);

// @desc  Setting route stack
const SettingNavigator = createStackNavigator(
    {
        Setting: Setting,
    },
);

const HomeNavigator = createStackNavigator(
    {
        Home: Home,
        SD: ClassTopTabNavigator,
    },
);

const App = createStackNavigator(
    {
        Home: {
            screen: HomeNavigator,
        },
        Profile: {
            screen: ProfileNavigator,
        },
        Setting: {
            screen: SettingNavigator,
        }
    },
);

const AppSwitchNavigator = createSwitchNavigator({
    Welcome: { screen: AppNavigator },
    Dashboard: { screen: App },
}, {
        initialRouteName: "Dashboard",
        defaultNavigationOptions: () => {
            return {
                header: null
            };
        }
    });
````
### Your Environment

| software         | version
| Android------- | 8-------
| react-navigation | 3.11.0
| react-native     | 0.58.3
| react-native-gesture-handler | 1.2.2

**Comment by ramon90** [comment]
I am facing the same issue using nested stack navigator. It is really slow and unusable. I have tested on physical devices iOS and android and simulators as well, both in debug mode and without it. This needs to be fixed ASAP.

**Comment by brentvatne** [comment]
i tried to get this example running but i could not within a couple of minutes so i gave up: https://snack.expo.io/@notbrent/forlorn-waffle

@ramon90 or @ndrewchristt - please create a new issue and follow the issue template, we would be happy to look if we can reproduce the issue you are encountering

**Comment by andrewchristt** [comment]
hi @brentvatne thank you for replying, i create a new issue here [#5990](https://github.com/react-navigation/react-navigation/issues/5990) i attach some gif for comparison and snack that reproduce the code, hope it helps. Thanks you

@ramon90 yes its unusable, for now i use workaround that put tab navigator in switch navigator, even there is no transition animation when switching from current nav to tab nav in switch navigator but at least the tab navigator not laggy. I think i will use this until its fixed, please tell me if you have other workaround :)

**Comment by smbt** [comment]
I could prevent this from happening by removing the `initialRouteName` attribute from my nested navigator.

**Comment by satya164** [comment]
does your issue happen with latest `react-navigation-tabs`?

**Comment by smbt** [comment]
Sorry for commenting prematurely but my "bug-fix" was a false positive. The issue was somewhere in my own code and removing `initialRouteName` just seemed to have fixed it for a moment but was probably completely unrelated.

**Comment by andrewchristt** [comment]
@satya164 i use react navigation tabs as you suggested in my other thread, the lag on the swipe is gone but there is delay like 2s when i switch between tabs with clicking the tabs. i was using version 2.1.3 before, now i try updating to the latest which is 2.2.0 and the delay still there. 

this is my dependencies
"dependencies": {
    "@react-native-community/async-storage": "^1.3.4",
    "axios": "^0.18.0",
    "moment": "^2.24.0",
    "react": "16.8.3",
    "react-native": "0.59.9",
    "react-native-btr": "^1.1.4",
    "react-native-device-info": "^2.0.1",
    "react-native-firebase": "^5.3.1",
    "react-native-gesture-handler": "^1.0.16",
    "react-native-image-picker": "^0.28.0",
    "react-native-linear-gradient": "^2.5.4",
    "react-native-looped-carousel": "^0.1.13",
    "react-native-modal-datetime-picker": "^6.0.0",
    "react-native-reanimated": "^1.0.1",
    "react-native-vector-icons": "^6.3.0",
    "react-navigation": "^3.11.0",
    "react-navigation-tabs": "^2.2.0",
    "react-navigation-transitions": "^1.0.8",
    "rn-fetch-blob": "^0.10.15"
  },

you have any idea why the delay happen only when clicking the tabs?

**Comment by satya164** [comment]
please provide a repro

**Comment by andrewchristt** [comment]
@satya164 here is the snack https://snack.expo.io/BJ_GqqQxB , i try with physical device just now and the lag still there

**Comment by ramon90** [comment]
The issue i am facing is not with Stack Navigator, not Tab navigator. When I am navigating from one screen to another in a Stack navigator (whether is it nested or not) it is very laggy.

**Comment by ramon90** [comment]
The issue i am facing is with Stack Navigator, not Tab navigator. When i am navigating from one screen to another in a stack navigator (whether it is nested or not) it is laggy. I noticed this has to do with the the amount of content rendered on the screen, but even with optimiztaions such as initialNumToRender it is still laggy and not as smooth as it should be. Also, i noticed that adding params when navigating in Stack navigator makes the navigation much slower.

**Comment by andrewchristt** [comment]
@ramon90 if you have a lot of to render, have you try runAfterInteractions() on your component? it will force to render the navigation animation first before load your component, i write some little example. First set navigationRender to false so it only render a loading text or whatever you want, when navigation successfully rendered, then it will update the state and start to loading your component
import {InteractionManager, Text} from 'react-native';
state = {navigationRender: false};

  componentDidMount() {
    InteractionManager.runAfterInteractions(() => {
      this.setState({navigationRender: true});
    });
  }

  render() {
    if (!this.state.navigationRender) {
      return <Text>loading...</Text>;
    }

    return (
      <your component or render list/>
    );
  }

**Comment by ramon90** [comment]
I even tried that and unfortunately it did not make any difference

**Comment by ramon90** [comment]
I have tried again with runAfterInteractions, the navigation feels better, but the component never renders. Actually the callback function from runAfterInteractions never gets executed. Any clue on this?

**Comment by satya164** [comment]
@andrewchristt I tried your snack, but I don't see any kind of delay on tab press

**Comment by andrewchristt** [comment]
@satya164 I attach the gif for the delay, is this normal?
[https://media.giphy.com/media/dWZhCFJ4FjVIMSBrCT/giphy.gif](url)

**Comment by andrewchristt** [comment]
> I have tried again with runAfterInteractions, the navigation feels better, but the component never renders. Actually the callback function from runAfterInteractions never gets executed. Any clue on this?

can you try to console warn / log in component did mount and render, see if the component entered didmount and updating the complete render state?

**Comment by satya164** [comment]
Looks like you're pressing the tab for a while before lifting your finger, which is normal. Also 2s seems a way higher number than what you're showing in the gif.

**Comment by andrewchristt** [comment]
> Looks like you're pressing the tab for a while before lifting your finger, which is normal. Also 2s seems a way higher number than what you're showing in the gif.

sorry my bad for the 2s comment, I press B first and click C right away so I didnt press it for a while.. if its normal that the switching look like that when clicking then okay

**Comment by ramon90** [comment]
@andrewchristt yes, componeneDidMount is called, @satya164 any suggestions on my issue?
