### ISSUE TITLE
implementing drawer-sidebar on both side for LTR languages

### ISSUE THREAD

**Issue by Ashkan-Oliaie** [react-navigation/react-navigation#5958]
### Current Behavior

I needed to have two drawer Sidebar for when you change language to RTL,
in order to do that I've tried to implement two exactly same drawer on the both side to navigate to the corresponding route
but the contents and screens seems to get rendered twice as the screens on each drawer components are the same

is there anyway to implement these drawer sidebars or anyway to prevent the screens to get rendered twice?

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation  | 3.11.0
| react-native     |  0.59
| node             |    
| npm or yarn      |

**Comment by eriveltonelias** [comment]
hi there! this issue tracker is reserved for bugs only. your post seems to be a usage question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help. thanks!
