### ISSUE TITLE
Dynamic navigation options work wrong in v3 (in v2 it worked well)

### ISSUE THREAD

**Issue by whitetown** [react-navigation/react-navigation#5960]
Hello, 

### Current Behavior

I have used react-navigation v2.
A user can switch themes in the application and I set navigation options dynamically in 

```
componentDidMount() {
this.props.navigation.setParams({navigationOptions: this.props.theme.navigationOptions})
}
```

then I read them 
```
ChildScreen.navigationOptions = ({ navigation }) => {
    const navigationOptions = navigation.getParam('navigationOptions')||{}
    return {
        ...navigationOptions,
// other setup
    }
}
```
there is a video with v2:
https://www.dropbox.com/s/h2xuu78864o8b4n/v2-cool.mp4?dl=0 

### Expected Behavior

I would like to see the same behavior in v3 :-)
but here you can see a bug.
in v3 you can see some default navigation bar for a short moment
https://www.dropbox.com/s/ihbe2os6gh15r2i/v3-bug.mp4?dl=0

### How to reproduce

```
  componentDidMount() {
    this.props.navigation.setParams({ myBackground:'green', myTint:'yellow' })
  }
```

```
DetailsScreen.navigationOptions = ({ navigation }) => {

  return {
      title: 'Dymanic title',
      headerStyle: {
        backgroundColor: navigation.getParam('myBackground'),
      },
      headerTintColor:  navigation.getParam('myTint'),
    };
}
```

this is an original react-navigation demo with the code above:

https://snack.expo.io/@whitetown/overriding-shared-header-styles-v3

### Your Environment

    "react": "16.8.6",
    "react-native": "^0.59.8",
    "react-navigation": "^3.11.0",

**Comment by brentvatne** [comment]
this is the recommended approach for theming: https://reactnavigation.org/docs/en/themes.html
