### ISSUE TITLE
Cannot read property 'Direction' of undefined , it was appeared when i update version ^2.2.0 to ^3.11.0; i have checked other solutions but  not use

### ISSUE THREAD

**Issue by Ruanyang2015** [react-navigation/react-navigation#5963]
## The issue tracker is reserved for bug reports only.
**Cannot read property 'Direction' of undefined , it was appeared when i update version ^2.2.0 to ^3.11.0; i have checked other solutions but  not use**
---
### Current Behavior

- What code are you running and what is happening?
- Include a screenshot if it makes sense.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |"react-navigation": "^3.11.0",
| react-native     |  "@types/react-native": "^0.52.8",
| node             |
| npm or yarn      |yarn

**Comment by eriveltonelias** [comment]
Hi there,
this happens if you haven't installed RNGH properly. be sure to follow the steps from here: https://reactnavigation.org/docs/en/getting-started.html#installation


https://github.com/react-navigation/react-navigation/issues?utf8=%E2%9C%93&q=Cannot+read+property+%27Direction%27+of+undefined+

https://github.com/react-navigation/react-navigation/issues/5724#issuecomment-480506198

**Comment by Ruanyang2015** [comment]
You should say this: version 3x requires a react-naiive of at least 0.57.2, because you reference the react-native-gesture-handler

**Comment by Ruanyang2015** [comment]
> Hi there,
> this happens if you haven't installed RNGH properly. be sure to follow the steps from here: https://reactnavigation.org/docs/en/getting-started.html#installation
> 
> https://github.com/react-navigation/react-navigation/issues?utf8=%E2%9C%93&q=Cannot+read+property+%27Direction%27+of+undefined+
> 
> [#5724 (comment)](https://github.com/react-navigation/react-navigation/issues/5724#issuecomment-480506198)

You should say this: version 3x requires a react-naiive of at least 0.57.2, because you reference the react-native-gesture-handler

**Comment by eriveltonelias** [comment]
https://reactnavigation.org/docs/en/getting-started.html
