### ISSUE TITLE
How can I hide the tabBar in react-navigation (tabBarVisible not working for me)

### ISSUE THREAD

**Issue by nihp** [react-navigation/react-navigation#5965]
I am using react-navigation. Here I have many screens (I have subscreens under the createBottomTabNavigator)

```
const AppNavigator = createBottomTabNavigator({
Home: {
    screen: createStackNavigator({
      Users: {
        screen: Users
      },
      Location: {
        screen: Location
      },
      navigationOptions: {
      headerStyle: {
          backgroundColor: 'white',
          borderWidth:0,
          borderBottomWidth:0
      }
  navigationOptions: {
      headerStyle: {
          backgroundColor: 'white',
          borderWidth:0,
          borderBottomWidth:0
      },
      tabBarIcon: ({focused}) =>  (<Image   source={{uri: IMAGE}} />)
    },
  }Screen1: {
    screen: createStackNavigator({
      UserDetail: {
        screen: UserDetail
      },
      LocalisedPlace: {
        screen: LocalisedPlace
      },
      navigationOptions: {
      headerStyle: {
          backgroundColor: 'white',
          borderWidth:0,
          borderBottomWidth:0
      }
  navigationOptions: {
      headerStyle: {
          backgroundColor: 'white',
          borderWidth:0,
          borderBottomWidth:0
      },
      tabBarIcon: ({focused}) =>  (<Image   source={{uri: IMAGE}} />)
    },
const App = createAppContainer(AppNavigator);

export default class Routes extends Component {
  render() {
    return (
  
        <App onNavigationStateChange={(prevState, currentState) => {
        const currentScreen = getActiveRouteName(currentState);

        if (SCREENS_TO_HIDE_STATUS_BAR.includes(currentScreen))
          StatusBar.setHidden(true);
        else
          StatusBar.setHidden(false);
        }}/>
     );
  }
}
........
```

Here I have many subscreens under the Tabbar navigator(stack navigator is inside the tabNavigator)

I need to hide the bottom bars in the subscreens of the AppNavigator.

I have tried your answer https://github.com/react-navigation/tabs/issues/19. But it not worked for me. Kindly anyone gives a correct solution to achieve this

![Screenshot 2019-06-03 at 11 44 43 AM](https://user-images.githubusercontent.com/36992338/58788859-6c859700-860a-11e9-8efe-b144d056f7da.png)

**Comment by eriveltonelias** [comment]
Hi @nihp, 

you can do this https://reactnavigation.org/docs/en/navigation-options-resolution.html#a-tab-navigator-contains-a-stack-and-you-want-to-hide-the-tab-bar-on-specific-screens 

or 


https://snack.expo.io/@eriveltonelias/hide-tabbar-dynamic-react-navigation-v3

**Comment by nihp** [comment]
But it not worked for me. My use case is this refer below

https://github.com/react-navigation/react-navigation/issues/6006

**Comment by nihp** [comment]
@eriveltonelias I am getting an error as tabBarVisible is **readOnly** option.

My code is 

```
UserProfileNavigator.navigationOptions = ({ navigation }) => {

  const { state } = navigation;
  const routes = state.routes[state.index];

  const routeNames = routes.routeName;
  const tabBarVisible = state.routes[state.index].params ? state.routes[state.index].params.tabBarVisible : false;
 if(routeNames == 'Users'){
   return(
     tabBarVisible == false
   )
 }else{
   return (
     tabBarVisible
   )
 }
}

```

**Comment by eriveltonelias** [comment]
> @eriveltonelias I am getting an error as tabBarVisible is **readOnly** option.
> 
> My code is
> 
> ```
> UserProfileNavigator.navigationOptions = ({ navigation }) => {
> 
>   const { state } = navigation;
>   const routes = state.routes[state.index];
> 
>   const routeNames = routes.routeName;
>   const tabBarVisible = state.routes[state.index].params ? state.routes[state.index].params.tabBarVisible : true;
>  if(routeNames == 'Users'){
>    return(
>      tabBarVisible == false
>    )
>  }else{
>    return (
>      tabBarVisible
>    )
>  }
> }
> ```
> 


you're getting this error because the `tabBarVisible` you defined as constant, so you cannot change the value. 

so use `let tabBarVisible = ...`

and make sure to return an object
```js
return {
    tabBarVisible // make sure that this value was defined to true or false 
  }
```

**Comment by nihp** [comment]
In my case it not worked for me. Failed to hide the tab bars in react-navigation. 

Note: I have a clarification. I there any option to hide a tabbar item in react-navigation

I need to hide home tab in other screens. Any suggestion?

![Screenshot 2019-06-24 at 2 30 14 PM](https://user-images.githubusercontent.com/36992338/60012471-a55cdd00-9699-11e9-8a89-015e9d2fbc21.png)

**Comment by CVRamana** [comment]
> I am using react-navigation. Here I have many screens (I have subscreens under the createBottomTabNavigator)
> 
> ```
> const AppNavigator = createBottomTabNavigator({
> Home: {
>     screen: createStackNavigator({
>       Users: {
>         screen: Users
>       },
>       Location: {
>         screen: Location
>       },
>       navigationOptions: {
>       headerStyle: {
>           backgroundColor: 'white',
>           borderWidth:0,
>           borderBottomWidth:0
>       }
>   navigationOptions: {
>       headerStyle: {
>           backgroundColor: 'white',
>           borderWidth:0,
>           borderBottomWidth:0
>       },
>       tabBarIcon: ({focused}) =>  (<Image   source={{uri: IMAGE}} />)
>     },
>   }Screen1: {
>     screen: createStackNavigator({
>       UserDetail: {
>         screen: UserDetail
>       },
>       LocalisedPlace: {
>         screen: LocalisedPlace
>       },
>       navigationOptions: {
>       headerStyle: {
>           backgroundColor: 'white',
>           borderWidth:0,
>           borderBottomWidth:0
>       }
>   navigationOptions: {
>       headerStyle: {
>           backgroundColor: 'white',
>           borderWidth:0,
>           borderBottomWidth:0
>       },
>       tabBarIcon: ({focused}) =>  (<Image   source={{uri: IMAGE}} />)
>     },
> const App = createAppContainer(AppNavigator);
> 
> export default class Routes extends Component {
>   render() {
>     return (
>   
>         <App onNavigationStateChange={(prevState, currentState) => {
>         const currentScreen = getActiveRouteName(currentState);
> 
>         if (SCREENS_TO_HIDE_STATUS_BAR.includes(currentScreen))
>           StatusBar.setHidden(true);
>         else
>           StatusBar.setHidden(false);
>         }}/>
>      );
>   }
> }
> ........
> ```
> 
> Here I have many subscreens under the Tabbar navigator(stack navigator is inside the tabNavigator)
> 
> I need to hide the bottom bars in the subscreens of the AppNavigator.
> 
> I have tried your answer [react-navigation/tabs#19](https://github.com/react-navigation/tabs/issues/19). But it not worked for me. Kindly anyone gives a correct solution to achieve this
> 
> ![Screenshot 2019-06-03 at 11 44 43 AM](https://user-images.githubusercontent.com/36992338/58788859-6c859700-860a-11e9-8efe-b144d056f7da.png)

Hey I have solved this..
 the code is as follows..


import * as React from 'react';
import 'react-native-gesture-handler';
import { NavigationContainer, DefaultTheme, DarkTheme } from '@react-navigation/native';
import Details from './src/Tab_1/Details'
import Home from './src/Tab_1/Home'
import CreatePost from './src/Tab_1/CreatePost'
import Setting from "./src/Tab_1/Setting";
import { createStackNavigator } from '@react-navigation/stack';
import { createBottomTabNavigator } from '@react-navigation/bottom-tabs';
import Login from './src/Tab2/Login';
import Signin from './src/Tab2/Signin';
import Profile from "./src/Tab_3/Profile";

const Stack = createStackNavigator();

const Tab = createBottomTabNavigator();

//home Stack
function HomeStack({ navigation, route }) {
  navigation.setOptions({ tabBarVisible: route.state ? route.state.index > 0 ? false : true : null });
  return (
    <Stack.Navigator
      initialRouteName="Home"
    >
      <Stack.Screen name="Home" component={Home}
      />
      <Stack.Screen name="Details" component={Details}
      />
      <Stack.Screen name="CreatePost" component={CreatePost} />
    </Stack.Navigator>
  )

}


//Auth stack
function AuthStack({ route, navigation }) {
  navigation.setOptions({ tabBarVisible: route.state ? route.state.index > 0 ? false : true : null });
  return (
    <Stack.Navigator initialRouteName="Signin">
      <Stack.Screen name="Setting" component={Setting} />
      <Stack.Screen name="Login" component={Login} />
      <Stack.Screen name="Signin" component={Signin} />
    </Stack.Navigator>
  );
}

function ProfileStack() {
  return (
    <Stack.Navigator>
      <Stack.Screen name="Profile" component={Profile} />
    </Stack.Navigator>
  )
}

const MyTheme = {
  ...DefaultTheme,
  colors: {
    ...DefaultTheme.colors,
    primary: 'rgb(255, 45, 85)',
  },
};

export default function App() {
  return (

    <NavigationContainer theme={MyTheme}>
      <Tab.Navigator
        tabBarOptions={{
          activeTintColor: 'red',
          inactiveTintColor: "green",
          labelStyle: { fontSize: 20 },
          tabStyle: {
            backgroundColor: "pink",
            height: 90,
            //  marginTop:20,
            // alignItems:"center",
            justifyContent: "center"
          }

        }}
      >
        <Tab.Screen name="Home" component={HomeStack}
          options={{
            tabBarLabel: 'Home',
            tabBarVisible: true

          }}
        />
        <Tab.Screen name="Auth" component={AuthStack}

        />
        <Tab.Screen name="Profile" component={ProfileStack}

        />
      </Tab.Navigator>
    </NavigationContainer>
  );
}

**Comment by CVRamana** [comment]
SEE the HomeStack function.....

**Comment by andrey010** [comment]
> navigation.setOptions({ tabBarVisible: route.state ? route.state.index > 0 ? false : true : null });

very good . I am using this

**Comment by wesbelonci** [comment]
> > navigation.setOptions({ tabBarVisible: route.state ? route.state.index > 0 ? false : true : null });
> 
> very good . I am using this

thanks!

**Comment by lylest** [comment]
SuperNavigator: {
      screen: SuperNavigator,
      navigationOptions: {
        tabBarVisible:false,
        
      },
  
    },
