### ISSUE TITLE
[bug? navigationOptions and Context]

### ISSUE THREAD

**Issue by tdimnet** [react-navigation/react-navigation#5966]
### Current Behavior

Hello there, here are some info :).

- I am using React Native with the Expo SDK (I write you the dump of my expo diagnostic below). I am working on the user authentication and I created a small store with the React Context API (I created a HOC which helps me manipulate my store) and it seems that the navigationOptions is read once my component is wrapped.

- With the HOC:
 
![Screenshot 2019-06-03 at 12 01 55](https://user-images.githubusercontent.com/9935925/58793918-676b1c80-85f7-11e9-9965-3a28de01ceba.png)

- Here is part of the code I am using:

```
class SignInScreen extends React.PureComponent {
  static navigationOptions = {
    header: null
  }

  state = {
    username: '',
    password: ''
  }

  render() {
    const { statusBarHeight } = Constants
    const { username, password } = this.state
    const { navigation } = this.props
    const { goBack, navigate } = navigation

    return (
      <Wrapper withMarginTop={statusBarHeight}>
        <BackButton onPress={() => goBack()} />
      </Wrapper>
    )
  }
}

export default WithMeContext(SignInScreen)
```

### Expected Behavior

- Without using the HOC (I pasted the code below), the static navigationOptions works as expected.

- The design I am looking for:

![Screenshot 2019-06-03 at 12 06 32](https://user-images.githubusercontent.com/9935925/58794328-3b03d000-85f8-11e9-8341-f362f8b45aea.png)

- The code I run:

```
export default class SignInScreen extends React.PureComponent {
  static navigationOptions = {
    header: null
  }

  state = {
    username: '',
    password: ''
  }

  render() {
    const { statusBarHeight } = Constants
    const { username, password } = this.state
    const { navigation } = this.props
    const { goBack, navigate } = navigation

    return (
      <Wrapper withMarginTop={statusBarHeight}>
        <BackButton onPress={() => goBack()} />
      </Wrapper>
    )
  }
}
```

### Your Environment

 Expo CLI 2.17.3 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      @storybook/react-native: ^4.1.18 => 4.1.18 
      @types/expo: ^32.0.13 => 32.0.13 
      @types/react: ^16.8.18 => 16.8.18 
      @types/react-native: ^0.57.60 => 0.57.60 
      expo: ^32.0.0 => 32.0.6 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
      react-navigation: ^3.0.9 => 3.11.0 
    npmGlobalPackages:
      expo-cli: 2.17.3

**Comment by satya164** [comment]
The static property needs to be on the screen component. Here your HOC is wrapping the component in another where the wrapper component doesn't have the static property. You need to use something like https://github.com/mridgway/hoist-non-react-statics

**Comment by tdimnet** [comment]
@satya164 : I was thinking at something like it.
Thank you for your reactivity 👍
