### ISSUE TITLE
Text component in drawerlabel has huge spacing

### ISSUE THREAD

**Issue by nirjack** [react-navigation/react-navigation#5970]
Please check the expo snack
https://snack.expo.io/B1ZWF9M0V

Image below: 
![image](https://user-images.githubusercontent.com/12936751/58803841-04e14300-862e-11e9-9110-715fcb5d60aa.png)
This has spacing between home and description... how do I remove it?

Thanks in advance.

please create a new issue with this and i'd be happy to review it!

_Originally posted by @eriveltonelias in https://github.com/react-navigation/react-navigation/issues/5967#issuecomment-498236002_

**Comment by vonovak** [comment]
> This has spacing between home and description

can you please clarify what kind of spacing you have in mind? It's not quite clear to me what you're talking about.

**Comment by nirjack** [comment]
Fixed it.
