### ISSUE TITLE
TS definition for tabBarOptions in StackNavigatorConfig.navigationOptions

### ISSUE THREAD

**Issue by deeuu** [react-navigation/react-navigation#5971]
Potentially related to #3855, but Typescript defs are now provided by this repo, so I assume these issues are now relevant.

Tested on 3.11.0
```
const ExampleStack = createStackNavigator(
  { Example: ExampleScreen },
  {
    navigationOptions: {
      tabBarLabel: 'Example',
      tabBarOptions: {                    // type error 2345
        activeBackgroundColor: 'red'
      }
    }
  }
)
```
yields

```
error 2345| Argument of type '{ navigationOptions: { tabBarLabel: string; tabBarOptions: { activeBackgroundColor: string; }; }; }' is not assignable to parameter of type 'StackNavigatorConfig'
```

**Comment by nartc** [comment]
`navigationOptions.tabBarOptions` is not available. `tabBarOptions` outside of `navigationOptions` is available for `createBottomTabNavigator` or `createMaterialTopTabNavigator`. What is it that you want to achieve?

**Comment by deeuu** [comment]
Hey,

I should have added the `ExampleStack` is rendered by `createBottomTabNavigator`, so `activeBackgroundColor` in parent Navigator is indeed modified. Unless I'm mistaken, this makes sense following the guide on [Navigation options resolution](https://reactnavigation.org/docs/en/navigation-options-resolution.html).

If it's possible to configure the parent `navigationOptions` via child screen/stack, shouldn't it be available?

I got here by exploring different approaches to configuring the tab bar differently for each screen.

Cheers

**Comment by nartc** [comment]
@deeuu You're correct. I've tried this Snack out: https://snack.expo.io/@react-navigation/nested-navigationoptions-title-v3 and it does allow `navigationOptions` to have `tabBarOptions`. I think it's time to open a PR if you want to take ownership of the PR 👍

**Comment by satya164** [comment]
It shouldn't give error in 4.x. You should be able to import `NavigationBottomTabOptions` and annotate it manually.
