### ISSUE TITLE
textTransform property in headerTitleStyle doesn't work on Android

### ISSUE THREAD

**Issue by joeyyang** [react-navigation/react-navigation#5973]
### Current Behavior

Applying the `textTransform` style to `headerTitleStyle` works on iOS but not on Android. In the repro link below, it does not honor the `textTransform` property on Android. In my app, it does not render the header title at all on Android. 

This code works on iOS but not on Android:
```js
const headerBarOptions = {
  headerBackTitleVisible: false,
  defaultNavigationOptions: {
    headerTitleStyle: {
      // TOGGLE THIS LINE — observe that it works on iOS but not Android
      textTransform: 'uppercase'
    },
  }
};
```

From the repro link:
<img width="1440" alt="Screenshot 2019-06-03 13 42 25" src="https://user-images.githubusercontent.com/2928395/58833251-78228f00-8605-11e9-8286-bf1fe559d1b3.png">
<img width="1440" alt="Screenshot 2019-06-03 13 42 40" src="https://user-images.githubusercontent.com/2928395/58833252-78228f00-8605-11e9-8733-2f52df1041c3.png">

From my app — without `textTransform`:
<img width="973" alt="Screenshot 2019-06-03 13 45 16" src="https://user-images.githubusercontent.com/2928395/58833420-d7809f00-8605-11e9-8874-7cf9779e7a35.png">

with `textTransform` — header title does not render on Android:
<img width="961" alt="Screenshot 2019-06-03 13 45 02" src="https://user-images.githubusercontent.com/2928395/58833419-d7809f00-8605-11e9-9451-195b51cb1f75.png">

### Expected Behavior

I expect `textTransform` to be honored on iOS and Android.

### How to reproduce

Reproduced here: https://snack.expo.io/BJ8Phy7R4

### Your Environment

My app:

| software         | version
| ---------------- | -------
| react-navigation | `yarn list --depth 0` ->  `@react-navigation/core@3.1.1`, `@react-navigation/native@3.1.5`
| react-native     | `yarn list --depth 0` -> `react-native@0.57.8`
| node             | `node -v` -> `v8.11.3`
| npm or yarn      | `yarn --version` -> `1.15.2`

**Comment by vonovak** [comment]
hi @joeyyang, thanks for reporting. This is an issue present in your version of react native: https://github.com/facebook/react-native/issues/21966
it was fixed in 0.59.0. I'll therefore close this.
