### ISSUE TITLE
Nested Drawer inside BottomTab prohibits changing tabs sometimes

### ISSUE THREAD

**Issue by kpaulus1997** [react-navigation/react-navigation#5977]
### Current Behavior

Tab switches back to previous tab when using gestures with the drawer on IOS and Android.

![](https://media.giphy.com/media/kDqTNFGi7OBEptGopU/giphy.gif)

you can test this here: 
https://snack.expo.io/Hy299PSRN

I have used two drawers in this example but this can also be replicated with only on drawer

Is there a workaround?

### Expected Behavior

- Change tabs without jumping back

### How to reproduce

- This only occurs when using the gestures

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | latest
| react-native     | latest
| node             | latest
| yarn      | latest

**Comment by brentvatne** [comment]
i would suggest using the 2.0.0-alpha.2 release of react-navigation-drawer, it is more performant and solves this problem: https://snack.expo.io/@notbrent/rude-croissant

**Comment by kpaulus1997** [comment]
Thanks for the help, works great now!
