### ISSUE TITLE
Opening a view that is not in the navigation menu

### ISSUE THREAD

**Issue by pixsolution** [react-navigation/react-navigation#5978]
Hi everyone,

I'm doing an app with react native and it has a drawer menu that I did with react navigation. And I'm presenting the next issue. I have a view that is the "News list" and I want that when you click on the "Read more" button open the "Detail" view of the news. But I do not want the detail view of the news to be among the options in the drawer menu. How can I do?

Attachment of code news list and drawer navigator:
[Code.zip](https://github.com/react-navigation/react-navigation/files/3258485/Code.zip)

I'll appreciate your help
Regards

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.10.1
| react-native     | expo 32
| node             | 10.15.3
| npm      | 4.6.1

**Comment by brentvatne** [comment]
hi there! this is a question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.
