### ISSUE TITLE
Deep Linking not working in nested navigators expo 

### ISSUE THREAD

**Issue by okeybond** [react-navigation/react-navigation#5979]
` render() {

        const HomeStack = createStackNavigator({
            home: createStackNavigator({
                home: {screen: HomePage},
                ytSearch: {
                    screen: YTSearch
                },
                composePost: {
                    screen: ComposePost
                }
            }, {
                mode: 'modal',
                headerMode: 'none',
                navigationOptions: {
                    header: null,
                    tabBarVisible: false
                }
            }),
            postDetails: {screen: PostDetails, path: '/postDetails/:id'},
            composeReply: ComposeReply,
            groupProfile: GroupProfilePage,
            profile: ProfilePage
        });

        HomeStack.navigationOptions = ({navigation}) => {

            let tabBarVisible = true;
            if (navigation.state.index > 0) {
                tabBarVisible = false;
            }
            return {
                tabBarIcon: ({tintColor}) => <HomeIcon tintColor={tintColor}/>,
                tabBarVisible
            }
        };

        const
            SubscriptionStack = createStackNavigator({
                screen: SubscriptionPage,
                postDetails: {screen: PostDetails, path: '/postDetails/:id'},
                composeReply: ComposeReply
            });

        SubscriptionStack
            .navigationOptions = ({navigation}) => {
            let tabBarVisible = true;
            if (navigation.state.index > 0) {
                tabBarVisible = false;
            }
            return {
                tabBarIcon: ({tintColor}) => <Icon name="subscriptions" size={26} color={tintColor} type="material"/>,
                tabBarVisible
            }
        };

        const
            HomeNavigator = createBottomTabNavigator({
                home: {screen: HomeStack, path: ''},
                subscription: SubscriptionStack,
                search: {screen: SearchPage},
                notifications: {screen: NotificationsPage}
            }, {});

        const
            RootNavigator = createSwitchNavigator({
                welcome: {screen: WelcomePage},
                login: createStackNavigator({
                    auth: {screen: AuthPage},
                    signUp: {screen: SignUpPage},
                    resetPassword: {screen: ResetPasswordPage}
                }),
                main: createDrawerNavigator({
                        home: {
                            screen: HomeNavigator,
                            path: ''
                        },
                        profile: createStackNavigator({
                            profile: ProfilePage,
                            postDetails: {screen: PostDetails, path: '/postDetails/:id'},
                            composeReply: ComposeReply
                        }),
                        following: createStackNavigator({
                            following: FollowingPage,
                            createGroup: CreateGroupPage,
                            groupProfile: {
                                screen: GroupProfilePage
                            },
                            postDetails: {screen: PostDetails, path: '/postDetails/:id'},
                            composeReply: ComposeReply
                        }, {
                            navigationOptions: {
                                headerMode: 'none'
                            }
                        }),
                        bookmarks: createStackNavigator({
                            screen: BookmarksPage,
                            postDetails: {screen: PostDetails, path: '/postDetails/:id'},
                            composeReply: ComposeReply
                        }),
                        contact: {
                            screen: ContactPage,
                        },
                        info: {
                            screen: InfoPage,
                        },
                        conduct: {
                            screen: ConductPage,
                        }
                    },
                    {
                        contentComponent: SideMenuPage,
                        drawerWidth: 250,
                        defaultNavigationOptions: ({navigation}) => {
                            return {
                                headerLeft: (
                                    <Icon
                                        style={{paddingLeft: 10}}
                                        onPress={() => navigation.openDrawer()}
                                        name="menu"
                                        size={30}
                                    />
                                )
                            };
                        }
                    }
                )
            }, {
                lazy: true
            });

        const
            WrapperNavigator = createAppContainer(RootNavigator);

        const prefix = Linking.makeUrl("/");

        if (this.state.isReady) {
            return (
                <Provider store={store}>
                    <StyleProvider style={getTheme(variables)}>
                        <Root>
                            <WrapperNavigator uriPrefix={prefix}/>
                        </Root>
                    </StyleProvider>
                </Provider>
            );
        } else {
            return <AppLoading/>
        }
    }
`
---

### Current Behavior

- What code are you running and what is happening? 
`xcrun simctl openurl booted exp://127.0.0.1:19000/--/postDetails/uT5EgK9DIF5HWIk9yUAn
`
It doesnt navigate to the detailed page, it remains in the HomePage

### Expected Behavior

I expected it to navigate to the detailed page

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.8.1
| react-native     |31.0.1
| node             | 11.13.0
| npm or yarn      |6.9.0

**Comment by brentvatne** [comment]
hi there! this is a question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.

**Comment by okeybond** [comment]
@brentvatne Hi, it's a bug though, used the documentation but not getting the desired result
