### ISSUE TITLE
Avoid initalRoute to always mount before the actual navigated route?

### ISSUE THREAD

**Issue by Humbl-e** [react-navigation/react-navigation#5980]
### Current Behavior
On switching stacks, it mounts or at least calls the default route everytime there is a change in stack.

I have a Switch Navigator, that handles my Auth and once logged in navigates to the main App. The problem is that both of the screens are stack navigators and on navigating from one stack to another, it always navigates to the initial route and not to the specified route within the stack.
This leads to crashing my app as the default route would get a navigation.state.param.xxx if coming from another screen, but i would like to send from login to the second screen.
```
const AppStack = createStackNavigator({
  User: {
    screen: UserPage
  },
AddOrEditUser: {
    screen: AddOrEditUserPage
  },
 UserDetail: {
    screen: UserDetailPage
  },
});

const AuthStack = createStackNavigator({
Login: {
    screen: LoginPage
  },
  Registration: {
    screen: RegisterPage
  },
...
const AppNavigator = createAppContainer(createSwitchNavigator(
    {
        App: AppStack,
        Auth: AuthStack,
    },
    {
        initialRouteName: 'App',
    }
));
```
Also it doesn't make sense to have a fallback prop for the screen as user is not created to begin with, so it shouldn't be able to read anything related to user id from redux.

### Expected Behavior
I should be able to navigate to the desired screen without having to mount unnecessary screens or passing params which do not exist.

### How to reproduce
1) on APP.js I do a check if user logged in and if not I send to auth:
``` this.props.navigation.navigate('Auth')``` which leads to login page as expected to the default route.
2) From login i have two use cases: If  a user/client exists navigate to App with the userId prop.
``` this.props.navigation.navigate('App',{userId: nextProps.userIds[0]})``` 
which leads to User page and works fine. 
If there is no user created i would expect it to follow the navigate action to AddEditUser.
```
this.props.navigation.navigate('App',
{},
NavigationActions.navigate({'AddOrEditUser',{editing: false}})
``` 
Or
```
this.props.navigation.navigate('AddOrEditUser',{editing : false})
```
both seem to work on navigating to App stack, but crash as userId is undefined.
 ```ComponentWillMount() {console.log('hello from userPage' ) ``` 
will produce "hello from userPage" twice, as soon as i navigate to the 'App' stack.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | V3
| react-native     | 59.3

**Comment by Humbl-e** [comment]
This is also a problem even when user is logged in. As in from App.js I would do the same check for user, if it exists jusst go to main app(default),  otherwise go to main app(addUser)

**Comment by brentvatne** [comment]
https://reactnavigation.org/docs/en/auth-flow.html
