### ISSUE TITLE
How to work the toggleDrawer () within the createStackNavigator

### ISSUE THREAD

**Issue by pixsolution** [react-navigation/react-navigation#5981]
Hello! I need to know how to work the toggleDrawer () within the createStackNavigator? because I need to use the onpress for the MenuDrawer icon directly from the navigator when I created the StackNavigator. I attach my code. Hope you can help me, regards!
`
const HomeNavigator = createStackNavigator(
  	{
				
		 Inicio: {
				
		 screen: HomeScreen,
		 navigationOptions: (navigation) => ({
			title: ``,
			headerBackTitle: null,
			headerLeft:(
			
				<Ionicons style={{ marginLeft: 20 }} 
					name="md-menu" 
					size={32}
					margin={50} 
					onPress={
						
							
						
					  }

				   
				/>  
			),
		  }),
		
		 },`

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.10.1
| expo | 32.0
| node | 10.15.3
| npm | 4.6.1

**Comment by brentvatne** [comment]
hi there! this is a question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.
