### ISSUE TITLE
All screens in createDrawerNavigator having blue statusbar color in android devices

### ISSUE THREAD

**Issue by akhilsanker** [react-navigation/react-navigation#5983]
### Current Behavior

I have a drawernavigator as my root navigator and the initialroute of this is a stacknavigator. And all the pages in the root navigator is having a blue colour as the statusbar in Android devices.

Android

![Screenshot_1559907969](https://user-images.githubusercontent.com/32122016/59101947-3d439280-8948-11e9-8b25-d8190e098939.png)

iOS

![Simulator Screen Shot - iPhone 6 - 2019-06-07 at 17 11 13](https://user-images.githubusercontent.com/32122016/59101664-4f710100-8947-11e9-9fcd-13d7bddba58b.png)

### Expected Behavior

To have transluent statusbar color in android devices

### How to reproduce

My code is as follows:

    export const HomeNavigation = createStackNavigator({
	  Home: {screen: HomeScreen},
	  TimeTableScreen: {screen: TimeTableScreen},
	  ELibraryScreen: {screen: ELibraryScreen},
	  LearningScreen: {screen: LearningScreen},
	  WebViewSupportScreen: {screen: WebViewSupportScreen}
    })

    export const DrawerNavigation = createDrawerNavigator ({
     Dashboard: {screen: HomeNavigation},
     Profile: {screen: ProfileScreen},
     'Student Support': {screen: SupportWebViewNavigation},
      Settings: {screen: SettingsScreen}
    })   

    	render() {
		return(
			<DrawerNavigation/>
		)
	}

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.18.3
| react-native     | 0.59.8
| node             | 12.1.0
| npm or yarn      | 6.9.0

**Comment by brentvatne** [comment]
this is unrelated to react-navigation, you need to configure your android app to do this

**Comment by akhilsanker** [comment]
Hi @brentvatne ,
Please check the screenshots,

1. My app login screen. It is defined as a stack navigation.

       export const LoginNavigation = createStackNavigator({
	      LoginScreen: {screen: LoginScreen},
	      LoginCredentialsScreen: {screen: LoginCredentialsScreen},
	      ForgotPasswordScreen: {screen: ForgotPasswordScreen} 
       },
       {
	    headerMode: 'none',
       })

![Screenshot_1560844900](https://user-images.githubusercontent.com/32122016/59664183-2d407400-91ce-11e9-8efd-13355bd3994f.png)

and it is having a dark colour as statusbar color.

2. My dashboard. It is defined as a drawer navigation.

       export const HomeNavigation = createStackNavigator({
         	Home: {screen: HomeScreen},
	        TimeTableScreen: {screen: TimeTableScreen},
	        ELibraryScreen: {screen: ELibraryScreen},
	        LearningScreen: {screen: LearningScreen},
	        WebViewSupportScreen: {screen: WebViewSupportScreen}
       },
       {
	       headerMode: 'none', 
       })

       export const SupportWebViewNavigation = createStackNavigator({ 
	        Support: {screen: StudentSupportScreen},
	        WebViewSupportScreen: {screen: WebViewSupportScreen}
       },
       {
	       headerMode: 'none',
       })

       export const DrawerNavigation = createDrawerNavigator ({
	        Dashboard: {screen: HomeNavigation},
	        Profile: {screen: ProfileScreen},
	       'Student Support': {screen: SupportWebViewNavigation},
	       Settings: {screen: SettingsScreen}
       },
       {
	       contentComponent: MenuDrawerComponent
       },
       {
	       initialRouteName: 'Dashboard',
       })

![Screenshot_1560844954](https://user-images.githubusercontent.com/32122016/59664619-059ddb80-91cf-11e9-820c-ead6fac4446c.png)


and it is having a blue colour in statusbar


3. Internet handling page. It is just a screen/view to handle network condition

![Screenshot_1560845910](https://user-images.githubusercontent.com/32122016/59665135-f53a3080-91cf-11e9-87f9-1385d34d5047.png)

and is having the same colour in status bar as of the login screen.

If its not regarding react-navigation, it is appreciable if you can suggest how can I overcome this.

Thanks

**Comment by akhilsanker** [comment]
@brentvatne ,

Found out the solution. Its due to `native-base` default status bar colour for android. 

Thanks
