### ISSUE TITLE
web, stack navigator: Previous screen doesn't disappear completely

### ISSUE THREAD

**Issue by zamponotiropita** [react-navigation/react-navigation#5984]
After 3 months off keyboard and a new laptop I stumbled across the following bugs in both chrome and safari (the second one is major) while running react-native for web:
* I have to set `cardStyle: { flex: 1 }` in the options of `createStackNavigator`, otherwise the cards (individual screens of the stack navigator) will have height `0`.
* When pushing a new screen into the navigation stack, the previous screen will become blank and occupy half of the top of the screen instead of disappearing completely. The bottom half of the screen will contain the pushed screen.

Testing on android I don't have those issues.

I don't know whether these issues are related to react-native-gesture-handler, react-navigation or react-native-web. I would appreciate any hints.

I used the most recent versions for all packages (react-native v0.59.9, react-navigation v3.0.9 and react-native-web v0.11.4, react-native-gesture-handler v1.3.0)

### Current Behaviour

web version:
<img src="https://user-images.githubusercontent.com/23146389/59103601-e0ed6c80-8961-11e9-9a18-8f819836ba67.png" width="300"/>

### Expected Behaviour
mobile version:
<img src="https://user-images.githubusercontent.com/23146389/59103796-65d88600-8962-11e9-9f08-d2439adadeec.png" width="300"/>

### How to reproduce

The problem arises only on the web version, not on the mobile versions. Vanilla StackNavigator:

```
const StackNavigatorContainer = createAppContainer(createStackNavigator(
  {
    FirstScreen: FirstScreen,
    SecondScreen: SecondScreen,
  },
  {
    initialRouteName: "FirstScreen",
    cardStyle: {
      flex: 1,
    }
  }
));
```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.0.9 
| react-native     | 0.59.9
|react-native-web | 0.11.4
| react-native-gesture-handler     | 1.3.0
| node             | 12.3.1
| yarn      | 1.16.0

**Comment by pleportz** [comment]
Hi!

I have the same problem using react-native-web 0.8.8 + react-navigation 3.11.0. Here is a gif: 

![gif](https://user-images.githubusercontent.com/20668374/59117044-3408f480-894d-11e9-9129-02c1aa205282.gif)

I haven't found the cause of this behaviour. This may be a hint: there is this a warning in the console when I load the first page, `PanGestureHandler is not yet supported on web.`

@EvanBacon do you have insights about this?

**Comment by zamponotiropita** [comment]
@pleportz do you also need to set `cardStyle: { flex: 1 }`?

**Comment by pleportz** [comment]
@zamponotiropita I do not use `cardStyle: { flex: 1 }` but I use `flexGrow: 1,` on my `Page` component, which I use as a container for every page of the stack

**Comment by brentvatne** [comment]
ymmv on web right now, we need to do a lot of work to get this running well on web. i'd just stick to switch navigator as much as possible

**Comment by EvanBacon** [comment]
Web support is still very much in beta. using `headerMode: "float"` (default) will cause this problem as `react-native-screens` works differently across web and native. Please either use `headerMode: "screen"` or more preferable, a `SwitchNavigator`.

**Comment by zamponotiropita** [comment]
`headerMode: "screen"` solved my problem.
However, some other things are broken. For example `numberOfLines` doesn't work to a newly pushed screen. Any suggestions?

```jsx
```

**Comment by zamponotiropita** [comment]
possibly related to this: https://github.com/necolas/react-native-web/issues/1386
