### ISSUE TITLE
Top padding issue in StackNavigator on Android

### ISSUE THREAD

**Issue by JeremyBradshaw7** [react-navigation/react-navigation#5985]
Currently on Android if you navigate to a StackNavigator whose first/default screen has navigationOptions: {header: null}, but then other screens in that Stack have standard headers, the header on those screens is pushed up under the Android status bar so it is half-obscured.

| software         | version
| ---------------- | -------
| react-navigation | 1.5.11
| react-native     | 0.55.2

**Comment by JeremyBradshaw7** [comment]
Workaround:

```
  static navigationOptions = ({ navigation }) => {
    const params = navigation.state.params || {};
    return {
      headerStyle: { marginTop: Platform.OS === 'android' ? 20 : 0 }, // fix for half obscured header on android
    };
  }
```

**Comment by brentvatne** [comment]
hello! we don't support `react-navigation@1` anymore, the latest version is 3.11
