### ISSUE TITLE
Help Needed: Re-render when bottom tab switch

### ISSUE THREAD

**Issue by ManishSharmaApporio** [react-navigation/react-navigation#5988]
Hi ,
I have used  react-navigation 2.6.2 but i m getting some  problem with *createBottomTabNavigator*  when i switch tab first time component lifecycle method will fired  but i m going to switch tab next time there will be  no lifecycle method fired even react native listener not fired also. please help me out  for the same .Thanks

**Comment by brentvatne** [comment]
https://reactnavigation.org/docs/en/function-after-focusing-screen.html

**Comment by ManishSharmaApporio** [comment]
Hi @brentvatne  its didn't work

**Comment by power-f-GOD** [comment]
As per the docs brent posted above, the `useFocusEffect` hook should work. That's what you need in this case not a `useEffect`.
