### ISSUE TITLE
react navigation tabnavigator just wroks for 1 time in android

### ISSUE THREAD

**Issue by musakhani** [react-navigation/react-navigation#5989]
Hi, i'm using tab navigator in react navigation but bottom menu just works for 1 time in android. 
i mean when i click on 1 of menu i cannot change it or back to the home menu

i test it in real android devices and didn't work as well 

![Video20190610210714](https://user-images.githubusercontent.com/10217938/59210963-fc57b200-8bc3-11e9-9dcc-3c8f4e279fdd.gif)

here is my router.js

`import {
    StackNavigator,
    TabNavigator,
    createStackNavigator,

} from "react-navigation";

import React from "react";
import {Text, View, Image, Platform} from "react-native";
import Home from "./Screens/Home/Home";
import LogoTitle from "./component/LogoTitle/LogoTitle";
import Icon from "react-native-vector-icons/Ionicons";
import Splash from "./Screens/Splash/Splash";
import Phone from "./Screens/Splash/Phone";
import ValidPhone from "./Screens/Splash/ValidPhone";
import Information from "./Screens/Splash/Information";
import SuperCategory from "./Screens/SuperCategory/SuperCategory";
import First from "./Screens/Test/First";
import Second from "./Screens/Test/Second";
import Category from "./Screens/Category/Category";
import Cheap from "./Screens/Category/Cheap";
import Expensive from "./Screens/Category/Expensive";
import Product from "./Screens/Product/Product";
import Seller from "./Screens/Seller/Seller";
import Filter from "./Screens/Filter/Filter";
import Search from "./Screens/Search/Search";
import Profile from "./Screens/Profile/Profile";
import EditProfile from "./Screens/Profile/EditProfile";
import SellerContactInfo from "./Screens/SellerContactInfo/SellercontactInfo";
import Tab from "./component/Tab/Tab";
import {SettingIcon, ProfileIcon, SearchIcon, HomeIcon, BotickIcons} from "./component/svg-icon/svg";

console.disableYellowBox = true;

const RootStack = StackNavigator(
    {
        _ValidPhone: ValidPhone,
        _Second: Second,
        _Splash: Splash,
        _Second: Second,
        _Search: Search,
        _Product : Product,
        _Phone: Phone,
        _Profile : Profile,
        _Seller : Seller,
        _EditProfile : EditProfile,
        _Filter: Filter,
        _Category: Category,
        _Information: Information,
        _Tabs: TabNavigator(
            {
                Home: {
                    screen: StackNavigator(
                        {
                            _Home: Home,
                            _SuperCategory: SuperCategory,
                            _Seller: Seller,
                            _SellerContactInfo: SellerContactInfo,
                            _Filter: Filter,
                            _Product: Product,
                            _Category: Category
                        },
                        {
                            initialRouteName: "_Home",
                            navigationOptions: {
                                headerTitle: <LogoTitle/>,
                            },
                        }
                    ),
                    navigationOptions: {
                        tabBarIcon: ({focused}) => (
                            <BotickIcons
                                icon={'home'}
                                style={Platform.OS == 'ios' ? { width:'100%' , height : '100%'} : { width:'200%' , height : '200%'} }
                                fill={focused ? "black" : "gray"}
                            />
                        )
                    }
                },

                Search: {
                    screen: createStackNavigator(
                        {
                            Search: Search,
                            _ProductSearch: Product,
                            _CategorySearch: Category,
                            _SellerSearch : Seller,
                            _SellerContactInfoSearch: SellerContactInfo,
                        },
                        {
                            navigationOptions: {
                                headerTitle: <LogoTitle/>,

                            }
                        }
                    ),
                    navigationOptions: {
                        tabBarIcon: ({focused}) => (
                            <Icon
                                size={30}
                                name="ios-search"
                                color={focused ? "black" : "gray"}
                            />
                        )
                    }
                },

                Profile: {
                    screen: createStackNavigator(
                        {
                            _Profile: Profile ,
                            _EditProfile : EditProfile ,
                            _SellerProfile : Seller,
                            _ProductProfile : Product,
                            _SellerContactInfoProfile : SellerContactInfo
                        },
                        {
                            navigationOptions: {
                                headerTitle: <LogoTitle/>,

                            }
                        }
                    ),
                    navigationOptions: {

                        tabBarIcon: ({focused}) => (
                           <BotickIcons
                                icon={'profile'}
                                style={Platform.OS == 'ios' ? { width:'100%' , height : '100%'} : { width:'200%' , height : '200%'} }
                                fill={focused ? "black" : "gray"}
                            />
                        )

                    }
                }
            },
            {
                initialRouteName: "Home",
                tabBarPosition: "bottom",
                tabBarOptions: {
                    showLabel: false,
                    showIcon: true,
                    activeTintColor: "#000000",
                    inactiveTintColor: "#000000",
                    indicatorStyle: {
                        backgroundColor: "#FF546A"
                    },
                    style: {
                        backgroundColor: "#FFFFFF"
                    },
                    labelStyle: {
                        fontSize: 14
                    },
                    upperCaseLabel: false
                },
                animationEnabled: true,
                swipeEnabled: false,
                lazy: false
            }
        )
    },
    {
        initialRouteName: "_Splash",
        navigationOptions: {
            header: null
        }
    }
);

export default RootStack;
`

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
