### ISSUE TITLE
Tab navigator slow in nested Stack Navigator

### ISSUE THREAD

**Issue by andrewchristt** [react-navigation/react-navigation#5990]
Im quite new to this react environtment, and found slowness in tab navigator if its nested, JS fps down to 10-20 fps when i switch between tabs ( the lag only occur on the indicator tab, but the screen behave as expected ). if the tab navigator is the main nav, its become fast and no lagging or delay. So i suspect its because of nested stack? thanks before

### Current Behavior

Tab navigator so slow in transition between tabs (swipe or click) if its nested in stacknavigator ( fps around 10-20) but become normal (50-60) if its the main nav
here i attach the example in gif. so much laggy on swipe and getting worse on clicking the tabs ( this tab navigator is on nested stack ). JS thread drops 
![Image of Current](https://media.giphy.com/media/JUkYpOqZwi9FTXYeim/giphy.gif)

### Expected Behavior

Behave the same when the tab navigator is main nav
here i attach the example in gif. JS thread drops a little but its fine, no lagging when do swipe and clicking the tabs ( this tab navigator is on main nav, not in nested stack )
![Image of Expected](https://media.giphy.com/media/URkCv3SrymHJp9h8Es/giphy.gif)

### How to reproduce

@brentvatne hi brent, i reproduce the code here as your instructed. In the snack emulator i found there is no lag but delay (1sec), and i tried to test it on my phone again via expo app and the lag is there again. for additional information I create my rn app via create react native app not the expo one. I attached some gif to show the comparison in current & expected behavior section
 
https://snack.expo.io/BkbPkDn0N

### Your Environment

| software | version
| Android------- | 8-------
| react-navigation | 3.11.0
| react-native | 0.58.3
| react-native-gesture-handler | 1.2.2

**Comment by satya164** [comment]
Please use `react-navigation-tabs` which address a lot of performance concerns.

https://github.com/react-navigation/tabs

**Comment by andrewchristt** [comment]
@satya164 its works for the swipe, but the delay is still there when i switch tab with clicking the tab. the delay is 2s

**Comment by darknblack** [comment]
> @satya164 its works for the swipe, but the delay is still there when i switch tab with clicking the tab. the delay is 2s. i tried both creatematerialtop and bottom, its only happen on top

Happened to me as well :( hoping for a solution soon

**Comment by Pilaba** [comment]
Any update? 
this "slowness" is frustrating

**Comment by cargallo** [comment]
Happened to me as well!! I think the problem is in Stack Navigation

**Comment by paschaldev** [comment]
Same here +1

**Comment by SaeedZhiany** [comment]
> Please use `react-navigation-tabs` which address a lot of performance concerns.
> 
> https://github.com/react-navigation/tabs

@satya164 what is the difference between that repository and react-navigation tabs? I thought to react navigation automatically import the tabs from the repository you mentioned.

**Comment by SaeedZhiany** [comment]
> @satya164 its works for the swipe, but the delay is still there when i switch tab with clicking the tab. the delay is 2s. i tried both creatematerialtop and bottom, its only happen on top

@satya164 and @andrewchristt 
I tested both, the result is the same with considerable delay in response, even with two empty screens.
obviously, there is something wrong with react-navigation Tab

**Comment by firofame** [comment]
> Please use `react-navigation-tabs` which address a lot of performance concerns.
> 
> https://github.com/react-navigation/tabs

why is the newer version of `react-navigation-tabs` not used in the `react-navigation` package?

**Comment by paschaldev** [comment]
Anybody still experiencing this issue, I had to use `react-native-tab-view` package. Much more faster and I didn't experience the slow tab change anymore.

**Comment by SaeedZhiany** [comment]
@paschaldev 
I still struggling with it, unfortunately, there is no active response from maintainers. I want to manage all navigation stuff using `react-navigation`. I take a look at `react-native-tab-view`, its structure is more different from react-navigation, so using it adds more complexity to my application naviagtion logic

**Comment by paschaldev** [comment]
@SaeedZhiany I use both `react-navigation` and `react-native-tab-view`. `react-navigation` still manages my navigation, however on the screen where I need tabs, I render a screen and in that screen, I use `react-native-tab-view` for the tabs. It's simple

**Comment by SaeedZhiany** [comment]
@paschaldev 
Yeah I could guess how you use it right now, but in my case, I have a little bit complex parameter passing between screens and my app bar changes dynamically according to the current tab, I manage all of the logic using react-navigation and I can not migrate part of it to another library.

I hope to react--navigation maintainers do something for the problem any soon.

**Comment by Mattimus333** [comment]
I just noticed this today.  Funny enough I had just upgraded to react-native .60 and enabled the Hermes JS engine.  Disabling Hermes cut at least a second off the delay.  I guess Hermes integration is still a work in progress.

**Comment by Ashkan-Oliaie** [comment]
Guys 
I'm just a newbie but 
have you tried disabling dev-mode ? or disabling debugger ?
I'm using it on 0.60.5 and it works fine.
and another thing is the lazy option for bottom-tabs

**Comment by SaeedZhiany** [comment]
@Ashkan-Oliaie 

Yeah, I tried everything but result is the same. I even tried creating two empty tabs to test if my content causes the issue but I saw no difference between them.

**Comment by SaeedZhiany** [comment]
@Ashkan-Oliaie 

Yeah, I tried everything but the result is the same. I even tried creating two empty tabs to test if my content causes the issue but I saw no difference between them.

**Comment by Ashkan-Oliaie** [comment]
@SaeedZhiany I've just nested a materialTabNavigator within a stackNavigator and it worked well.
If I'm reproducing the case you've mentioned,
The animation is smooth  and had like 0.2 sec delay and that's because I had js Dev-mode ON.
 something must be wrong though since you'll getting it.
Though I was on 0.60.5.

**Comment by SaeedZhiany** [comment]
Which navigator did you use exactly? materialTopTabNavigator or materialBottomTabNavigator?
However, I'm still on RN 0.59.10 and can't migrate this soon.

**Comment by Ashkan-Oliaie** [comment]
createMaterialTopTabNavigator
createStackNavigator

for upgrading check this out :
https://github.com/react-native-community/upgrade-helper

I haven't used it yet , but lemme know the outcome if it helped 😋

**Comment by SaeedZhiany** [comment]
yeah I know how I should upgrade my project's RN version but I have some other technical problem for migrating, thank you anyway.

it seems react-navigation V4.0.0 has been released, so we can use the latest version of each navigator separately and according to [this comment](https://github.com/react-navigation/react-navigation/issues/5990#issuecomment-500634291), the latency might be resolved. I haven't access to my laptop for a few days, can someone (that has the issue previously) test the new version and tell us the result, please?

**Comment by SaeedZhiany** [comment]
> Try changing your testing device or emulator

I have tested on both of them, the result is the same.

**Comment by SaeedZhiany** [comment]
A related issue on [react-navigation-tabs](https://github.com/react-navigation/tabs/issues/150)
it seems the problem still there.

**Comment by cargallo** [comment]
In [react-native-tab-view](https://github.com/react-native-community/react-native-tab-view) says that _React Navigation integration can be achieved by the react-navigation-tabs package. Note that while it's easier to use, it is not as flexible as using the library directly._
So, WTF is this mamushka hell??? I started using react-navigation, then installed react-navigation-tabs, but seems like it's using react-native-tab-view behind!!! this is crazy as hell!!!

**Comment by SaeedZhiany** [comment]
@cargallo 
Are you sure? I couldn't find `react-native-tab-view` as a dependency in [react-navigation's package.json](https://github.com/react-navigation/react-navigation/blob/master/package.json) file? where did you see the dependency? can you give the file's link?

**Comment by SaeedZhiany** [comment]
Just for clarification, there are two tab navigation library with an almost similar name,

- react-native-tab-view: it belongs to react-native-community and not related to react-navigation. it can be used as a standalone library.

- react-navigation-tabs: it belongs to react-navigation library that recently extracted from its core and maintained separately. it must be used with react-navigation library together.

**Comment by firofame** [comment]
react-native-tab-view is a dependency of react-navigation-tabs https://github.com/react-navigation/tabs/blob/master/package.json

**Comment by SaeedZhiany** [comment]
@firofame 
yeah, you're right, I didn't notice that.

**Comment by paschaldev** [comment]
@cargallo Exactly, `react-native-tab-view` was good to go for me... The performance gain was incredible, I no longer experience the slow tab navigation. Everything is smooth now

**Comment by cargallo** [comment]
> @cargallo
> Are you sure? I couldn't find `react-native-tab-view` as a dependency in [react-navigation's package.json](https://github.com/react-navigation/react-navigation/blob/master/package.json) file? where did you see the dependency? can you give the file's link?

Yes, but you must see in [react-navigation-tabs](https://github.com/react-navigation/tabs/blob/master/package.json) that's why I talked about mamushka hell!!!

**Comment by Mattimus333** [comment]
After a little more investigation it seems disabling dev mode does seem to speed things up and I have yet to test things on production.  However I did notice this issue did not come up on react-native .59.8, only once I upgraded to .60.5 did I notice this lag.

**Comment by SaeedZhiany** [comment]
@Mattimus333 
It's not true in my case. I saw the lag in both dev (either debug is enabled or disabled) and production mode.

**Comment by axelraymundo** [comment]
I'm having the same problem so I used [react-native-tab-view](https://github.com/react-native-community/react-native-tab-view) like what was suggested here and it fixed the performance issue, but my views are dependent on the navigation prop passed by the navigator, so following the docs of in react-native-tab-view, it says that I should use a custom **renderScene function**

"If you need to pass additional props, use a custom renderScene function:"

`renderScene = ({ route }) => {
  switch (route.key) {
    case 'first':
      return <FirstRoute navigation={this.props.navigation} />;
    case 'second':
      return <SecondRoute />;
    default:
      return null;
  }
};`

So naturally I passed the navigation prop and now it behaves similar to the slowness of react-navigation-tabs. 

If I use the SceneMap, it's fast, if I use a custom renderScene function, it's slow.

**Comment by jiangbophd** [comment]
react-navigation-tabs still not fixed, very slow, why why.....

**Comment by cargallo** [comment]
@jiangbophd you could try something like this inside each tab screen...

  public state: State = {
    screenReady: false,
  };

  componentDidMount() {
    InteractionManager.runAfterInteractions(() => {
      this.setState({
        screenReady: true
      });
    });
  }

  public render(): React.ReactNode {
    if (!this.state.screenReady) {
      return (
        <View style={styles.container}>
          <ActivityIndicator size="large" color="#fff" />
        </View>
      );
    }
    return (
        {/* ...your current render code... */}
    );
  }
}

**Comment by yelkamel** [comment]
same issue here on Android release version
```
   "react-navigation": "^4.0.10",
   "react-navigation-redux-helpers": "^4.0.0",
   "react-navigation-stack": "^1.9.3",
   "react-navigation-tabs": "^2.5.5",
```

**Comment by syedsaadqamar** [comment]
I was facing the slow tab navigate issue, The slow issues occur when having nesting things like in my case

- I have Drawer from `react-navigation/drawer` **FIRST LEVEL**
- Second I have Tabs from `'@react-navigation/bottom-tabs'` under the drawer **SECOND LEVEL**
- The third thing I have a stack (it has multiple screens)  from `@react-navigation/stack` under the Tabs **THIRD LEVEL**

```
<Drawer.Navigator>
   <Tab.Navigator>
       <Stack.Navigator>
           <Stack.Screen name="Home"></Stack.Screen>
           <Stack.Screen name="Details"></Stack.Screen>
       </Stack.Navigator>
      <Stack.Navigator>
           <Stack.Screen name="Task"></Stack.Screen>
           <Stack.Screen name="Details"></Stack.Screen>
       </Stack.Navigator>
       .....
   </Tab.Navigator>
</Drawer.Navigator>
```

So if I remove any one thing from above the slow issue was gone for example if I remove Drawer.Navigator so I have only two nested things Tab.Navigator and Stack.Navigator so issue was gone.

So what I did I remove Drawer and use a drawer from `native base`(you can use another drawer package).
I know how pain is that I suffering it for a long time and didn't find any solution from the official team, Hope Team will fix nesting issue soon, for now, you can use that solution.

**Comment by gostavee** [comment]
Still an issue, nested navigators caused the the top bar scrolls to be very slowly. 
"expo": "^38.0.0",
"@react-navigation/drawer": "^5.8.2",
"@react-navigation/material-top-tabs": "^5.2.12",
"@react-navigation/native": "^5.2.1",
"@react-navigation/stack": "^5.2.16"

**Comment by NikolaRaevski** [comment]
What helped me was setting _**initialLayout**_ to a style with only _**Dimensions.get('window').width**_ .
Another improvement may come by setting **_removeClippedSubviews_** to **_true_**.
Hope this helps you too!

**Comment by ehdwns980416** [comment]
Any Update?

**Comment by hotaryuzaki** [comment]
in docs it suggest to use react-native-screens to improve performance of stack navigator.
is it works for this issue????
