### ISSUE TITLE
App freezes on setParams if used in useEffect

### ISSUE THREAD

**Issue by dominictwlee** [react-navigation/react-navigation#5996]
### Current Behavior
```javascript
import React, {useEffect} from "react";
import { View, Text, Button } from "react-native";
import { createStackNavigator, createAppContainer } from "react-navigation";

const HomeScreen = ({navigation}) => {
  useEffect(() => {
    navigation.setParams({hello: 'world'})
  }, [navigation])
  return (
    <View>
      <Button title="Something" />
    </View>
  )
}

HomeScreen.navigationOptions = ({navigation}) => ({
  title: navigation.getParam('hello')
})

const AppNavigator = createStackNavigator({
  Home: {
    screen: HomeScreen
  }
});

export default createAppContainer(AppNavigator);
```

App will freeze up when using setParams in useEffect with navigation props included in the deps array.

### Expected Behavior

- App should not freeze.

### How to reproduce

- Please see code above.
- Remove navigation props from useEffect to unfreeze the app.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^3.11.0
| react-native     |  0.59.9
| node             | 10.15.3
| yarn      | 1.16.0

**Comment by satya164** [comment]
This is the expected behaviour. `setParams` triggers a re-render and updates the `navigation` prop. Since you're updating params every time `navigation` prop changes, it causes an infinite loop. it's same as calling `setState` in `render`. You need to add some checks to avoid updating params when you don't need to.

**Comment by mhuggins** [comment]
@satya164 As someone who is new to both hooks and react-native, what kind of checks are options here?  Is there some documentation you could point to?

**Comment by ameernormie** [comment]
Having the same issue. Any solution?

**Comment by mhuggins** [comment]
I posted an approach that ended up working for me, which can be found [here](https://github.com/react-navigation/react-navigation/issues/2473#issuecomment-522704708).  Hope it helps!

**Comment by ameernormie** [comment]
If we want to only run useEffect `once`. we should pass in an empty array in place of dependencies.
Like
```
useEffect(() => {
    navigation.setParams({hello: 'world'})
  }, [])
```

**Comment by draperunner** [comment]
Using an empty array breaks the `react-hooks/exhaustive-deps` ESLint rule. I'd rather check if the param has already been set or is changed:

```
useEffect(() => {
  if (navigation.getParam('hello') !== 'world') {
    navigation.setParams({ hello: 'world' })
  }
}, [])
```

**Comment by chen1zee** [comment]
my solution is using a useRef to prevent inifinitly re-render

### case inifinitly re-render
```
const cb = useCallback(() => {
	console.log(state)
	// ...something
}, [state])

useEffect(() => {
	navigation.setParams({
	  cb: cb
	})
}, [navigation, cb])

```

### useRef to handle, because ref doesn't change in the lifecycle,  navigation.getParams("cbRef").current always get the newest cb
```
const cb = useCallback(() => {
    console.log(state)
    // ...something
  }, [state])
  const cbRef = useRef(cb)
  useEffect(() => {
    cbRef.current = cb
  }, [cb])
  useEffect(() => {
    navigation.setParams({cbRef: cbRef})
  }, [])
```
### you can wrap your own hook, too

### btw,,, I don't think this the best solution, hope react-navigation can impove the code
