### ISSUE TITLE
`navigationOptions` with header back button settings doesn't have any effect

### ISSUE THREAD

**Issue by Hatko** [react-navigation/react-navigation#5998]
### Current Behavior

I've created [a snack](https://snack.expo.io/@vladhatko/amused-almond) to demonstrate the issue.

After passing 

```
navigationOptions: {
        headerBackImage: <Image src='./assets/snack-icon.png'/>,
        headerBackTitle: 'Test',
        headerLeft: <Text>'Test'</Text>
    }
```

to `createStackNavigator` I expect header back button to be changed. However, whatever settings I provide, I keep getting the default one. So far I couldn't find what I'm doing wrong. 

### Expected Behavior

Back button changed

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.11

**Comment by satya164** [comment]
Please provide correct link

**Comment by Hatko** [comment]
@satya164 updated the link

**Comment by Hatko** [comment]
During the farther investigation, I found out that it works with overriding `defaultNavigationOptions` instead. The issue can be closed, if it's intended behavior.

**Comment by MikaelConecto** [comment]
Ty @Hatko ! This should be in the Docs, that's sure.

**Comment by wamry** [comment]
Please reopen this issue, as this is not the intended behavior
@Hatko @MikaelConecto 
 
from the docs
> You can set buttons in the header through the headerLeft and headerRight properties in navigationOptions.
> The back button is fully customizable with headerLeft
