### ISSUE TITLE
Cannot read property 'Direction' of undefined despite proper installation

### ISSUE THREAD

**Issue by jjd314** [react-navigation/react-navigation#5999]
### Current Behavior
First, I realize that this exact problem has been reported a dozen times.  Most of those end with a response of "you did not install correctly, try again".  I am certain that I installed react-navigation correctly, and into a newly created app, and I still get the error.

In a brand new react-native project, `yarn test` runs the default test successfully. After following the installation directions at https://reactnavigation.org/docs/en/getting-started.html, and changing App.js to wrap the default App in AppContainer/StackNavigator, the test fails with "Cannot read property 'Direction' of undefined"

### Expected Behavior

Test should run.

### How to reproduce
```
react-native init Foo
cd Foo
yarn add react-navigation
yarn add react-native-gesture-handler
react-native link react-native-gesture-handler
```

Edit android/app/src/main/java/com/foo/MainActivity.java to look like this (per installation instructions):
```
package com.foo;

import com.facebook.react.ReactActivity;
import com.facebook.react.ReactActivityDelegate;
import com.facebook.react.ReactRootView;
import com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView;

public class MainActivity extends ReactActivity {

    /**
     * Returns the name of the main component registered from JavaScript.
     * This is used to schedule rendering of the component.
     */
    @Override
    protected String getMainComponentName() {
        return "Foo";
    }

    @Override
    protected ReactActivityDelegate createReactActivityDelegate() {
        return new ReactActivityDelegate(this, getMainComponentName()) {
            @Override
            protected ReactRootView createRootView() {
                return new RNGestureHandlerEnabledRootView(MainActivity.this);
            }
        };
    }
}
```

Run `yarn test`, verify that test runs.

Edit App.js to look like this (wrapping App in AppContainer/StackNavigator):
```
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 *
 * @format
 * @flow
 */

import React, {Component} from 'react';
import {Platform, StyleSheet, Text, View} from 'react-native';
import { createAppContainer, createStackNavigator } from 'react-navigation'

const instructions = Platform.select({
  ios: 'Press Cmd+R to reload,\n' + 'Cmd+D or shake for dev menu',
  android:
    'Double tap R on your keyboard to reload,\n' +
    'Shake or press menu button for dev menu',
});

type Props = {};
class App extends Component<Props> {
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>Welcome to React Native!</Text>
        <Text style={styles.instructions}>To get started, edit App.js</Text>
        <Text style={styles.instructions}>{instructions}</Text>
      </View>
    );
  }
}

export default createAppContainer(createStackNavigator({
  App: App
}))

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
```

And edit package.json to look like this (adding transformIgnorePatterns):
```
{
  "name": "Foo",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.8.3",
    "react-native": "0.59.9",
    "react-native-gesture-handler": "^1.3.0",
    "react-navigation": "^3.11.0"
  },
  "devDependencies": {
    "@babel/core": "^7.4.5",
    "@babel/runtime": "^7.4.5",
    "babel-jest": "^24.8.0",
    "jest": "^24.8.0",
    "metro-react-native-babel-preset": "^0.54.1",
    "react-test-renderer": "16.8.3"
  },
  "jest": {
      "preset": "react-native",
      "transformIgnorePatterns": [
          "node_modules/(?!(react-native|@react-navigation|react-native-screens|react-native-gesture-handler)/)"
      ]
  }
}
```

Run `yarn test`, get error message.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.11.0
| react-native     | 0.59.9
| node             | 8.11.3
| npm or yarn      | 1.12.3

**Comment by brentvatne** [comment]
this means react-native-gesture-handler isn't properly linked. try removing react-navigation and just using react-native-gesture-handler directly and you will find the same issue. it's beyond the scope of this repo to help people with linking native libraries, I hope you can figure it out though!

**Comment by spasecadet** [comment]
@jjd314 were you able to figure this out?  I'm having the same issue, though using RN 0.60.0-rc.1.  I've done the installation correctly, cleared and reinstall node_modules several times, cleared cache, etc with no luck.  I thought it must have been related to RN 60 since I had this working on RN 59.9.

**Comment by jjd314** [comment]
Sorry, @spasecadet, I have not.  Good luck.

**Comment by dawidrogowicz** [comment]
In case someone will look for solution. I got it working by running react-navigation-gesture-handler's `jestSetup.js` inside of `react-navigation` mock

__mocks__/react-navigation.tsx:
```
import 'react-native-gesture-handler/jestSetup.js';
export * from 'react-navigation';
```

**Comment by nada-elhakim** [comment]
I got it fixed by adding the following setup file. Check the [ react-native-gesture-handler doc for testing](https://kmagiera.github.io/react-native-gesture-handler/docs/getting-started.html#testing)

```
 "jest": {
  "preset": "react-native",
  "setupFiles": ["./node_modules/react-native-gesture-handler/jestSetup.js"]
}
```
