### ISSUE TITLE
how can support RTL with top Tabs using createMaterialTopTabNavigator or stop animation

### ISSUE THREAD

**Issue by Abdo-zayed** [react-navigation/react-navigation#6000]
how can stop this animation or change direction 
in last version i edited node_modules\react-native-tab-view\src\TabBar.js
and commented two functions to solve this problem _adjustScroll , _resetScroll
but after upgrading i couldn't find this functions

**Comment by brentvatne** [comment]
hi there! this is a question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.
