### ISSUE TITLE
TextInput will lose focus immediately on Android

### ISSUE THREAD

**Issue by arniu** [react-navigation/react-navigation#6001]
### Current Behavior

Render string list with `FlatList` and the `ListFooterComponent` is a `TextInput`.

It works well on iOS and with Expo. While on Android, when the `TextInput` is focused, it will lose focus immediately, no matter in a tab navigator or a stack navigator.

<img src="https://raw.githubusercontent.com/arniu/react-navigation-demo/master/snapshot/tabview-react-native.gif" alt="Lose focus on Android" width="50%"/>

### How to reproduce

I put a simple [demo](https://github.com/arniu/react-navigation-demo) on Github.

The react-native folder is the entry for react-native and the expo for expo.

As it works well with Expo, I do not put it on [snack](https://snack.expo.io/).

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.11.0
| react-native     | 0.59.9
| node             | 10.15.0
| npm or yarn      | yarn 1.16.0

**Comment by arniu** [comment]
There is a similar issue #1023

**Comment by arniu** [comment]
And more, the bottom tabbar was still there when keyboard displayed.

Related issues:

- [Bottom tab bars and keyboard on Android #16](https://github.com/react-navigation/tabs/issues/16)
- [TabBarBottom should hide when Keyboard is activated #618](https://github.com/react-navigation/react-navigation/issues/618)

**Comment by satya164** [comment]
Thanks for the repro. I removed all navigation related code and just rendered a `FlatList` with a `TextInput` as footer and the issue with keyboard disappearing still happens. So it's not something related to React Navigation and rather a bug in React Native.

I'm closing the issue. Please open a new issue in the React Native repo.

**Comment by YesSkyscrapers** [comment]
removeClippedSubviews={false}
its work for me :)

**Comment by Noitidart** [comment]
> removeClippedSubviews

@YesSkyscrapers  Can you please elaborate on this. Where did you put this?

I'm also having the issue of immediate loss of focus. Did anyone find any solutions?
