### ISSUE TITLE
getActiveChildNavigationOptions && flow

### ISSUE THREAD

**Issue by Preeternal** [react-navigation/react-navigation#6002]
I got the flow error:
"Cannot import `getActiveChildNavigationOptions` because there is no `getActiveChildNavigationOptions` export in `react-navigation`.Flow(InferError)"

**Comment by Ashoat** [comment]
The [libdef](https://github.com/react-navigation/react-navigation/blob/master/flow/react-navigation.js) doesn't currently cover `getActiveChildNavigationOptions`. Could you make a PR adding it? Here are the [docs](https://reactnavigation.org/docs/en/navigation-options-resolution.html#getactivechildnavigationoptions) and [an example use](https://github.com/react-navigation/react-navigation/blob/eac5feb64e2170f370a815f10af77b471e146648/examples/NavigationPlayground/app/StacksOverTabs.tsx#L123-L134).

**Comment by Preeternal** [comment]
> cover `getActiveChildNavigationOptions`

I tried to do it. But the issue is still present. Could you please review the PR?
