### ISSUE TITLE
[iOS] Quick white screen (flash) after LaunchImage

### ISSUE THREAD

**Issue by xoapit** [react-navigation/react-navigation#6003]
### Current Behavior

- Between the LaunchImage and display of the first RN screen, there is a screen that is white. In Debug mode it takes longer; this is where you see the green "Downloading JavaScript bundle" bar up top. 
- Include a screenshot if it makes sense.

### Expected Behavior

- No white flash after LaunchImage.

### How to reproduce

- Setup LaunchImage in Xcode.
- Run App

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.11
| react-native     | 0.59.3
| node             | 10.15.11
| npm or yarn      | yarn 1.13.0

**Comment by satya164** [comment]
The white screen is because it takes time to start the JS VM. You need to tweak the native root view to improve it. This is unrelated to react navigation.
