### ISSUE TITLE
react-native-gesture-handler is (currently) incompatible with Gradle v6.x

### ISSUE THREAD

**Issue by AyushG3112** [react-navigation/react-navigation#6004]
Considering the fact that `react-navigation` asks us to install `react-native-gesture-handler`, I thought i should post this here too.

I am using react-native v0.59.9 which uses gradle v5.4.1.

While building using `./gradlew assembleRelease`, I get the warning

```
Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
```

On running `./gradlew assembleRelease --warning-mode all`, the warning changed to:

```
> Task :react-native-gesture-handler:generateReleaseRFile UP-TO-DATE
Changing the value for a property with a final value has been deprecated. This will fail with an error in Gradle 6.0.
```

**Comment by satya164** [comment]
Please open gesture handler related issues in it's repo.

**Comment by AyushG3112** [comment]
@satya164 I did. But to be clear, does this mean that `react-navigation` is incompatible with Gradle v6.x till this issue is resolved on `react-native-gesture-handler` end?

**Comment by Nykollas** [comment]
I'm with the same issue.
