### ISSUE TITLE
navigation options with functional component using hooks

### ISSUE THREAD

**Issue by achrafKara** [react-navigation/react-navigation#6005]
I switched my project from class component to functional component, but i faced a probelm figuring out how to access the header title inside the component coz i want to translat it.
In class componenet i was doing it like so:
static navigationOptions = {
    title: 'Home',
  };

**Comment by vonovak** [comment]
hi!
given a function component you should be able to assign nav options like this:
```
function YourComponent(props) {
  return ...
}

YourComponent.navigationOptions = {
title: 'Home',
};
```

**Comment by elioncho** [comment]
Hi, what about using params in the title?

**Comment by richeterre** [comment]
@elioncho You can assign a function that returns the nav options object:

```javascript
YourComponent.navigationOptions = screenProps => ({
  title: screenProps.navigation.getParam("yourParam")
});
```
