### ISSUE TITLE
How to hide tabbars in some screens under createStacknavigation and the same screen are present under createTabnavigation

### ISSUE THREAD

**Issue by nihp** [react-navigation/react-navigation#6006]
I need to hide the tab bar in some screens under createStackNavigator. (Home (**Show tab bars**), detailed screen ( hide tab bars), UserDetails ( hide tab bars) and I have mentioned this as UserNavigator const and this constant is in createBottomTabNavigator and also have additional screens in the createBottomTabNavigator method.

Here I need to hide the detailed screens tabbar. But it present in the createTabBarBottom method too. I have tried your answer in the react-navigation(https://github.com/react-navigation/tabs/issues/19) but it not worked for me)

Kindly clarify

```
const UserNavigator = createStackNavigator({
Home: {
screen: Home
}, 
DetailedScreen:{
screen: DetailedScreen
},
UserDetails: {
UserDetails
}
})

```
```
const BoottomTab = createBottomTabNavigator ({
UserScreens: {
screen: createStackNavigator({
User:{
screen: UserNavigator,
},
OtherProfile:{
screen:OtherProfile
},... 
}),
DetailedProfile:{
screen: createStackNavigator({
Details:{
screen: Details
}.......
})
```

**Comment by brentvatne** [comment]
https://reactnavigation.org/docs/en/navigation-options-resolution.html#a-tab-navigator-contains-a-stack-and-you-want-to-hide-the-tab-bar-on-specific-screens

**Comment by nihp** [comment]
@brentvatne  It not worked for me

**Comment by iraniamir** [comment]
@nihp I have this problem too
