### ISSUE TITLE
iOS Transparent header blocks UI Touchables

### ISSUE THREAD

**Issue by summerkiflain** [react-navigation/react-navigation#6009]
### Current Behavior

Touchables under iOS transparent header are not working, it seems like transparent header is overlapping them making them unusable. I have scrollable-tabview whose tab header sticks to the top of the screen, tabs are clickable on android but not in iOS.

### Expected Behavior

Touchable under transparent header should work as expected like they work in android.

### How to reproduce

The bug is pretty straight forward, still I will provide a working expo snack soon.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.11.0
| react-native     | https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz
| node             | v8.15.0
| npm or yarn      | yarn 1.15.2

**Comment by brentvatne** [comment]
this is expected behavior, the rect still remains a touchable area as you have buttons and so on inside of it. if you'd like to do something different then you should do `header: null` and just render exactly what you need

**Comment by summerkiflain** [comment]
@brentvatne why is this expected behavior?, it works fine on android, it should work in the same way for iOS too, I can see that there is a flex wrapper on container, it should be removed, at least in the case when there is no `headerTitle` provided, so the user can click something visible in place of transparent header.

**Comment by rzinnatullin** [comment]
I use `headerTransparent: true` mode, and put whatever I want into the header. However, the invisible area in the header is stealing the touchable area from the components I put there. That's annoying, and it's definitely a bug.
I don't want to fully draw the header on my own (for example, I like having the default behavior of the `back` button).

**Comment by fondue-tech** [comment]
@brentvatne This answer is as invalid as in was back in 2019.
