### ISSUE TITLE
'lazy: false' for createStackNavigator?

### ISSUE THREAD

**Issue by trevorwhealy** [react-navigation/react-navigation#6010]
Hello, it seems that the `lazy` flag is not enabled for stack navigation. It would be great if all the screens in the stack could be rendered so that they do not have to load during navigation. It seems that all the other createXyzNavigators have it available - so why not stack as well? I can imagine there are performance implications, but in small apps, this would be great. Thanks!

**Comment by satya164** [comment]
In drawer/tabs, there are a fixed number of all screens, so all of them can be rendered and you just navigate to an existing screen. The order in which the screens are rendered is also fixed.

It doesn't make sense for stack. There's no limit to how many screens that can be rendered and there's no guarantee about order of screens or what is the next screen. There can also be multiple instances of the same screen.

The navigation state for stack is populated you push a new screen as opposed to drawer it tabs where there state already includes all screens.

**Comment by trevorwhealy** [comment]
@satya164 thank you for taking the time to write a thoughtful response!

I understand that you're saying this "doesn't make sense for stack" but it makes sense for my use-case. I don't necessarily need "lazy" to be implemented for the `createStackNavigator` so much as I need to achieve the effect of all screens being mounted at app load time. 

The reason that I need this is that each new Screen in our app is a WebView and the mounting process causes considerable lag because the WebView needs to load the page in question. Do you have any suggestions or ideas for how to achieve the effect of all the Screens being rendered at app load time?
