### ISSUE TITLE
Can you use transitionConfig with createSwitchNavigator? if not how do you add transitions to the Switch?

### ISSUE THREAD

**Issue by ThomasLarge** [react-navigation/react-navigation#6012]
I have been trying to add a transtion animation when I change stack / switch but i'm unable to do this, can anyone help? here is my switch

```js
export default createAppContainer(
  createSwitchNavigator(
    {
      Splash: SplashScreen,
      App: AppStack,
      Auth: AuthStack,
      Video: VideoStack
    },
    {
      initialRouteName: "Splash"
    }
  )
);
```

All I want to do is get the splash screen to fade out when I change to the auth screen

**Comment by eriveltonelias** [comment]
hey @ThomasLarge, 

try to this https://github.com/react-navigation/animated-switch
