### ISSUE TITLE
how to disable Gesture of DrawerNavigator in StackNavigator inside DrawerNavigator

### ISSUE THREAD

**Issue by aksmfosef11** [react-navigation/react-navigation#6013]
On a specific page of StackNavigator inside DrawerNavigator I want to disable the Gesture of DrawerNavigator. Calling static navigationOptions sets the options for StackNavigator.

How do I set the DrawerNavigator options?

```
const ListNavigator = type => createStackNavigator({
  List: {
    screen: PostListContainer,
    path: 'list',
    params: { type },
  },
  viewPost: ViewPostContainer,
}, {
  mode: 'card',
  headerMode: 'none',

});

const leftMenuWidth = Dimensions.get('screen').width / 2;

const DrawerNavigator = createDrawerNavigator({
  Home: AppNavigator,
  Post1: {
    screen: ListNavigator(true),
  },
  Post2: {
    screen: ListNavigator(false),
  },
}, {
  drawerWidth: leftMenuWidth,
  contentComponent: SlideMenuContainer,
  drawerOpenRoute: 'DrawerOpen',
  drawerCloseRoute: 'DrawerClose',
  drawerToggleRoute: 'DrawerToggle',
});
```
In this code, opening the viewPost in the PostList I want to disable Gesture of DrawerNavigator. What should I do?

Gesture should work in List Must be disabled only in viewPost.

| software         | version
| ---------------- | -------
| react-navigation |3.9.1
| react-native     |0.59.8
| node             | 8.11.0
| npm or yarn      |1.15.2

**Comment by Rodrigo816** [comment]
I have the same question...anyone solved this?

**Comment by brentvatne** [comment]
similar to hiding tabs example on https://reactnavigation.org/docs/en/navigation-options-resolution.html
