### ISSUE TITLE
refs or measure not working on SafeAreaView

### ISSUE THREAD

**Issue by davidalvarezr** [react-navigation/react-navigation#6014]
#### Code that I tried to run

```js
import { SafeAreaView } from 'react-navigation';
...
componentDidUpdate() {
    this.safeAreaRef.measure((x, y) => { console.log(`${x}, ${y}`); }); // error here
}
...
render() {
    return (
        <SafeAreaView ref={(c) => { this.safeAreaRef = c; }} >
        ...
        </SafeAreaView>
    )
}
```
#### The error

```
TypeError: TypeError: this.safeAreaRef.measure is not a function. (In 'this.safeAreaRef.measure(function (x, y) {
          console.log(x + ", " + y);
        })', 'this.safeAreaRef.measure' is undefined)
```

### Expected Behavior

- Getting the mensurations of the `SafeAreaView`

**note:** it works when a replace `SafeAreaView` with `View` (from `react-native`)

### How to reproduce

- Put a `SafeAreaView` as root component with a ref and try to gets it's dimensions

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.11.0
| react-native     | 33.0.0
| node             | 8.16.0
| npm or yarn      | 6.4.1

**Comment by vonovak** [comment]
hi! Thanks for reporting; please take a look at how measurement is done in the `SafeAreaView`

https://github.com/react-native-community/react-native-safe-area-view/blob/bf7405b8fb3a42df204255e1fbc05f9cc9c83628/index.js#L187

you'll probably need to do `this.safeAreaRef.view.getNode().measure(...)`
