### ISSUE TITLE
How to add view dynamically on header part 

### ISSUE THREAD

**Issue by sharifashraful** [react-navigation/react-navigation#6016]
I have a screen where header and flatlist is there. when i click on item, i want to add view( or another topbar  ) on header part. i like to add message like "x item selected" and "delete icon" on that view. something like this screenshot

![image](https://user-images.githubusercontent.com/7131239/59747563-ebc9ca80-929a-11e9-9eab-8a2d10d00a87.png)

how will do that in react native

**Comment by matthamil** [comment]
Hello! The issues are meant for bug reports. I will be closing this issue.

You should check out [this page in the docs](https://reactnavigation.org/docs/en/headers.html).
