### ISSUE TITLE
drawer lockmode not working social media 

### ISSUE THREAD

**Issue by MITDD6338** [react-navigation/react-navigation#6024]
The issue tracker is reserved for bug reports only.
so, whenever I click the social media button then default play services model open but background drawer are open 

![Drawer Error](https://user-images.githubusercontent.com/31823903/59911911-91637200-9432-11e9-8ec8-9d9cb8784521.jpeg)

**Current Behavior**
opens the app in Running-Devices

**Expected Behavior**
Close the background drawer 

software | version
-- | --
react-navigation | ^3.3.0
react-native-google-signin | ^1.2.0
react-native | 0.58.5
node | 12.3.1
npm or yarn

**so I recently I face this issues so can you please help us**
**resolve the bug** 
Thank You in Advance?

**Comment by dominictwlee** [comment]
I've been noticing this too. It happens whenever a native android dialog pops up.

**Comment by MITDD6338** [comment]
@dominictwlee  
so any Solution ....

**Comment by dominictwlee** [comment]
@MITDD6338 nope, but i opened an issue with a minimal reproducible example for them to take a  look at.

Maintainers, please check out #6029 for a related issue.

**Comment by eriveltonelias** [comment]
closing in favor of https://github.com/react-navigation/react-navigation/issues/6029#issuecomment-505453705 and https://github.com/react-navigation/react-navigation/issues/6029#issuecomment-506701507
