### ISSUE TITLE
animation speed for MaterialTopTabNavigator

### ISSUE THREAD

**Issue by miladrasooli** [react-navigation/react-navigation#6025]
### Current Behavior
Switching between tabs in material top tab navigator is relatively slow!

### Expected Behavior

I want to make transition/animation speed of switching tabs faster. I know that react-native-tab-view has timingConfig to do so but I can't pass it to my navigator

### How to reproduce

Just use default createMaterialTabTopNavigator!

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3
| react-native     | 0.59.8

**Comment by satya164** [comment]
Please migrate to https://github.com/react-navigation/tabs which uses the latest version of `react-native-tab-view` and has faster tab switching speeds by default.

**Comment by miladrasooli** [comment]
Thanks, migrated to tabs but it's still slow , I was wondering if I could manually set the sliding speed? I tried to pass timingConfig and springConfig bu no luck

**Comment by miladrasooli** [comment]
finally fixed! upgraded `react-navigation-tabs` and `react-native-tab-view` to latest version and passed `timingConfig `to `createMaterialTopTabNavigator` .

**Comment by d-warfield** [comment]
@miladrasooli Can you share the code please?

**Comment by shovel-kun** [comment]
The solution the commenter above suggested is no longer valid for react-navigation v6+. 

See https://stackoverflow.com/a/77659267
