### ISSUE TITLE
Drawer locks up and stays open when navigating to a page with dialog prompt

### ISSUE THREAD

**Issue by dominictwlee** [react-navigation/react-navigation#6029]
### Current Behavior
When navigating to a screen in drawer navigator with an android dialog prompt, the drawer freezes and stays open in the background until the dialog prompt is  dismissed.

![Screenshot_20190622-231738](https://user-images.githubusercontent.com/34794189/59969398-489bde00-9544-11e9-9413-8935800db48a.jpg)

### Expected Behavior
- The drawer should not be open when navigating between screens unless specifically specified with drawerLockMode.

### How to reproduce
```javascript
import React from "react";
import { View, Text, PermissionsAndroid } from "react-native";
import { createAppContainer, createDrawerNavigator } from "react-navigation";


class HomeScreen extends React.Component {
  render() {
    return (
      <View style={{ flex: 1, alignItems: "center", justifyContent: "center" }}>
        <Text>Home Screen</Text>
      </View>
    );
  }
}

class PageTwo extends React.Component {
  componentDidMount() {
    this.requestLocation()
  }
   requestLocation = async () => {
    try {
       await PermissionsAndroid.request(
        PermissionsAndroid.PERMISSIONS.ACCESS_COARSE_LOCATION
      );
    } catch (err) {
      console.warn(err);
    }
  }

  render() {
    return (
      <View style={{ flex: 1, alignItems: "center", justifyContent: "center" }}>
        <Text>Page Two</Text>
      </View>
    );
  }
}

const AppNavigator = createDrawerNavigator({
  Home: HomeScreen,
  PageTwo: PageTwo, 
});

export default createAppContainer(AppNavigator);
```

-  Setup two screens in drawer navigator as shown above.
- Navigate to screen with permissions prompt, and the drawer should be locked open in the background until dismissed.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^3.11.0
| react-native     | 0.59.9
| node             | 10.15.3
| yarn      |  1.16.0

**Comment by dvhchuot** [comment]
useNativeAnimations: false, working for me !

**Comment by jqn** [comment]
I have seen this issue also but I believe it's only related to android.

**Comment by eriveltonelias** [comment]
have you tried to use https://github.com/react-navigation/drawer   v2 ?

`react-navigation-drawer@2.0.0-alpha.3`

**Comment by dominictwlee** [comment]
Cool so just tried react-navigation-drawer @2.0.0 and the result is this:

![image](https://user-images.githubusercontent.com/34794189/60249141-0e239f80-98bc-11e9-99bc-dfa95f899ad2.png)

While that is already much better than before, wouldn't it make more  sense for the drawer to fully close before letting the modal open on the next page?

**Comment by satya164** [comment]
> wouldn't it make more sense for the drawer to fully close before letting the modal open on the next page

Your app's code is responsible for opening the dialog, so it's upto you. The drawer navigator cannot control it.

Closing the issue since the original issue seems to be resolved in the new version of drawer navigator.
