### ISSUE TITLE
How can I hide a tab bar item in react navigation

### ISSUE THREAD

**Issue by nihp** [react-navigation/react-navigation#6031]
I need to hide the tab item(home) from the react-navigation. How can I hide this? Refer this attached image
![Screenshot 2019-06-24 at 2 30 14 PM](https://user-images.githubusercontent.com/36992338/60005750-c0752000-968c-11e9-916c-5b972d1c5dd7.png)

**Comment by drewhamlett** [comment]
The best option is to have a custom Tab bar, but there are some other solutions explained here: https://github.com/react-navigation/react-navigation/issues/4069 .  There are links to a canny discussion also.

**Comment by vikrantnegi** [comment]
@nihp Can you share your react-navigation routes code where you have defined the tab navigator?

**Comment by eriveltonelias** [comment]
thanks @drewhamlett 

https://react-navigation.canny.io/feature-requests/p/hiding-tab-from-the-tabbar

**Comment by nihp** [comment]
How can I change the tabBarIcon color? I have used images in tabBarIcon

**Comment by abrahamAlonzo** [comment]
You just need to add `tabBarButton: () => (null)` in your tab screen like:
`<Tab.Screen 
          options={{
            tabBarButton: () => (null)
          }}
          navigation={navigation} name={'Home'} component={HomeScreen} />`
