### ISSUE TITLE
Setting props to state when switching between stacks in drawer

### ISSUE THREAD

**Issue by connercms** [react-navigation/react-navigation#6032]
### Current Behavior
Snack demo:
https://snack.expo.io/ry3DaSAyr

I have an application that allows users to manage orders placed through the app. My application is a drawer navigator that contains several stack navigators. On the "home" screen (the initial stack in my drawer), I have a dashboard that shows the user metrics about the orders (count of orders, count of *their* orders, count of open orders, etc.). I am trying to make it so when a user presses a metric it will redirect them to a different stack in the drawer that displays the list of orders, filtered to the metric they selected.

In my list component, I set the state in the constructor based on what filter is sent in navigation params. This works fine for the first time the user selects a metric. However, the component is never unmounted, so no following selections are applied. 

1. Press Filter: Open Orders to navigate to the list. It will accurately show that the Open filter is applied.
2. Open drawer, navigate back to home. Press Filter: My Open Orders to navigate back to the list. Filters are not accurately applied because component is not unmounted when navigating between stacks.

### Expected Behavior

I believe this worked in a previous version of the library (component unmounted when switching stacks) but may have been changed. At any rate, I tried to adapt by using getDerivedStateFromProps to update the filters in state if navigation props changed instead of only on initial mount. This works except for the following scenario:

1. User selects a metric, is navigated to list filtered to that metric
2. User navigates back to home screen (or any other stack)
3. User opens drawer and navigates back to the list (without having selected a metric)
4. Last metric pressed is still applied when user expects none to be applied

I believe this worked in a previous version because on componentWillUnmount I did `this.props.navigation.setParams({ filters: {} })` to clear my filters before navigating away to fix the above scenario.

I am not sure if this is a bug, but I cannot find how to properly do this.

**Comment by drewhamlett** [comment]
Have you checked NavigationEvents?  https://reactnavigation.org/docs/en/navigation-events.html .  There's also a hook version https://github.com/react-navigation/hooks

**Comment by eriveltonelias** [comment]
thanks @drewhamlett
