### ISSUE TITLE
Navigation with custom transition and disabled lazy loading ? 

### ISSUE THREAD

**Issue by Letitbe93** [react-navigation/react-navigation#6033]
### Trouble
I need tool for implementation navigation whith custom transition and disabled lazy loading for screens. For custom transition I have createStackNavigator (but it does not have option lazy), for lazy I have createMaterialTopTabNavigator (but it does not have options for custom transition).

I try combine createMaterialTopTabNavigator and createStackNavigator, but this did not work.

Any ideas on how to impelemnt this thing.Thanks beforehands.

### Your Environment
| react-navigation 3 |
| react-native 0.59.9 |

Thanks!

**Comment by eriveltonelias** [comment]
hi there! this issue tracker is reserved for bugs only. your post seems to be a usage question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help. thanks!
