### ISSUE TITLE
SafeAreaView.setStatusBarHeight does not exist on type

### ISSUE THREAD

**Issue by ardyfeb** [react-navigation/react-navigation#6035]
### Current Behavior

- SafeAreaView.setStatusBarHeight does not exist on type ComponentClass<SafeAreaViewProps, any> but no error when compile
- Screenshot: 
![Screenshot from 2019-06-25 15-24-43](https://user-images.githubusercontent.com/30074366/60082161-6beda580-975d-11e9-8aad-4fe19b6d7bb3.png)

### Expected Behavior

- SafeAreaView.setStatusBarHeight exist on type.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.11.0
| react-native     | https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz
| node             | latest
| npm or yarn      | latest

**Comment by eriveltonelias** [comment]
hi @ardyfeb, 

thanks for your report, this issue is related with `react-native-safe-area-view`
this PR will fix this https://github.com/react-native-community/react-native-safe-area-view/pull/81
