### ISSUE TITLE
App freezes on IOS when navigate to another screen

### ISSUE THREAD

**Issue by hakkikonu** [react-navigation/react-navigation#6036]
### Current Behavior

Ios app freezing when I want to navigate from Page1 to Page2

### Expected Behavior

I have two simple pages and I want to go to from Page1 to Page2 like 

`<Button title = "Go to Page2" onPress={() => this.props.navigation.navigate("Page2")} />`

But on IOS simulator when I press to Button or TouchableOpacity, app is freezing and can not go to another screen. Actually page 2 is loading background but screen can not update itself.

**Page1.js**

```
import React, {Component} from 'react';
import {View, Text, Button} from 'react-native';

export default class Page1 extends Component{
    render() {
        return(
            <View>
                <Text>Page 1</Text>
                <Button title = "Go to page 2" onPress={() => this.props.navigation.navigate("Page2")} />
            </View>
        )
    }
}
```

**Page2.js**

```
import React, {Component} from 'react';
import {View, Text} from 'react-native';

export default class Page2 extends Component{
    componentDidMount() {
        console.log("This is page 2 and, I can see this from console.");
    }
    render() {
        return(
            <View>
                <Text>I'm in Page 2</Text>
            </View>
        )
    }
}
```

**Router.js**

```
import Page1 from "./Page1";
import Page2 from "./Page1";

const AppNavigator = createStackNavigator({
        Page1: {
            screen: Page1
        },
        Page2: {
            screen: Page2
        }
    }, {
        initialRouteName: "Page1",
    }
);
export default createAppContainer(AppNavigator);
```

**package.json**

```
  "dependencies": {
    "@react-native-community/async-storage": "^1.5.0",
    "react": "16.8.3",
    "react-native": "0.59.8",
    "react-native-elements": "^1.1.0",
    "react-native-facebook-account-kit": "^1.1.0",
    "react-native-fbsdk": "^0.8.0",
    "react-native-gesture-handler": "^1.3.0",
    "react-native-iap": "^2.5.5",
    "react-native-vector-icons": "^6.5.0",
    "react-navigation": "^3.11.0"
  }
```

**Podfile**

```
pod 'React', :path => '../node_modules/react-native', subspecs: [
       'Core',
       'CxxBridge',
       'DevSupport',
       'RCTText',
       'RCTNetwork',
       'RCTWebSocket',
       'RCTAnimation',
       'RCTActionSheet',
       'RCTBlob',
       'RCTCameraRoll',
       'RCTGeolocation',
       'RCTImage',
       'RCTPushNotification',
       'RCTSettings',
       'RCTTest',
       'RCTVibration',
       'RCTLinkingIOS'
     ]
     pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
     pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
     pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
     pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
     pod 'RNAccountKit', :path => '../node_modules/react-native-facebook-account-kit/ios'
     pod 'RNIap', :path => '../node_modules/react-native-iap'
     pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'
     pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
     pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'
```

### Environment

React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
      Memory: 209.52 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.1 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 24, 26, 27, 28, 29
        Build Tools: 19.1.0, 20.0.0, 21.1.2, 22.0.1, 23.0.2, 25.0.0, 26.0.2, 27.0.0, 28.0.3, 29.0.0, 29.0.0
        System Images: android-26 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom_64
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.8 => 0.59.8 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-rename: 2.4.1

**Comment by eriveltonelias** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.
you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.
please create a new issue with this and i'd be happy to review it!

**Comment by HananeAlSamrout** [comment]
same here!

**Comment by MykhailoKaduk** [comment]
Same. And it's not very cool of you guys to close tickets without Sample code. What if I am working under NDA?

**Comment by satya164** [comment]
> Same. And it's not very cool of you guys to close tickets without Sample code. What if I am working under NDA

So how do you expect someone to fix your issue if you can't even show the code which reproduces the issue? We're asking for minimal reproducible code, not full code of your app, you being under NDA doesn't prevent you from sharing a minimal repro without any of your client code.

**Comment by MykhailoKaduk** [comment]
> > Same. And it's not very cool of you guys to close tickets without Sample code. What if I am working under NDA
> 
> So how do you expect someone to fix your issue if you can't even show the code which reproduces the issue? We're asking for minimal reproducible code, not full code of your app, you being under NDA doesn't prevent you from sharing a minimal repro without any of your client code.

So issue is gone? Just because you don't have code sample issue is fixed somehow? I don't think so. I don't blame you for doing magic and resolving issues just by guessing, but why closing those? Until it's not done, It should not be closed

**Comment by eriveltonelias** [comment]
@MykhailoKaduk don't be rude, every day we can see 10 new issues but a lot of isn't a bug. I'm sure that will take less time to share the minimal reproducible example ( as required on issue template ) than maintainers trying to find the bug and solution for that. So all the help are welcome, will be awesome if you can send PR ( btw looks like this code works well on https://snack.expo.io )

**Comment by hakkikonu** [comment]
Your pod file is the issue.

in subspecs

'Core', 'RCTLinkingIOS'

you only need these two. Change your pod file, and do pod install. If you get any error, add the missing subspec and do pod install. The culprit is one of the item in subspecs.

**Comment by satya164** [comment]
> @MykhailoKaduk So issue is gone

If there's no way to repro an issue we can't even know if it's an actual issue and not a mistake in your code. The issue is not confirmed until you provide a repro. In this case, according to @hakkikonu it's indeed a mistake in your code rather than a bug.

As @eriveltonelias said, there are like 10 new issues everyday, which may not even be an actual issues. We need to know what's a bug and what's not. Keeping everything open distracts us from focusing us on actual bugs. Also fixing a bug requires a way to repro the issue first. If there's no repro, it can't be fixed.

If you don't provide a repro and someone else has the same issue, they can always open a new issue with repro.

**Comment by JulioOrellana** [comment]
This happens to me on iPhone 6 and older

**Comment by AlenToma** [comment]
same here nut it happen on android
