### ISSUE TITLE
Tapping back button on Android causes a crash if persisted state is currently being loaded

### ISSUE THREAD

**Issue by ddenisen** [react-navigation/react-navigation#6039]
Hello,

I've encountered an issue related to the [new state persistence API](https://reactnavigation.org/docs/en/state-persistence.html). I'm reporting it as a bug because it seems like the framework should be handling this scenario gracefully.

### Current Behavior

If I tap a hardware back button on Android while React Nav is waiting for the `loadNavigationState` promise to resolve, the app crashes with the following error message:
```
should be set in constructor if stateful
```
Which originates from [here](https://github.com/react-navigation/native/blob/d54c3590825a3567f63fdea940a784699c653742/src/createAppContainer.js#L365).

This happens because the React Navigation nav state is not fully initialized until the `loadNavigationState` promise resolves. If any navigation events are triggered prior to that point, the framework is unable to determine the current state and therefore triggers an assertion failure. Pressing the HW back button on Android triggers a navigation back event in the framework and leads to such a crash.

### Expected Behavior

I expect the back button press to simply propagate to the parent handler (e.g. native activity) if React Nav is not ready to handle it. For example, the app activity could simply dismiss instead of crashing.

### How to reproduce

1. Create a new empty React Native app with `<AppNavigator ..>` as the main component, with `persistNavigationState` prop defined.
2. Inside the `persistNavigationState` function implementation, add a 2-3 second timeout before returning null (or a valid state, doesn't matter).
3. Open the app and tap the back button immediately.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  3.11.0
| react-native     |  0.57.3
| node             | 8.12.0
| npm or yarn      |  1.6.0

### Related issues

* https://github.com/react-navigation/react-navigation/pull/5203

**Comment by mmmoussa** [comment]
Has anyone come across a fix for this? I'm still seeing this issue in my app.

**Comment by joeljerushan** [comment]
I have the same issue still !

**Comment by RameshTigeen** [comment]
I also have, no fixes ?
