### ISSUE TITLE
React native navigation parameter not working with Switch navigator

### ISSUE THREAD

**Issue by perazzo** [react-navigation/react-navigation#6042]
I'm using react native navigation and redux in my code. Below is my navigation structure

```
const MainTabNavigator = createBottomTabNavigator({
    Home,
    Tenants,
    WorkOrders: {
      screen: WorkOrders,
      navigationOptions: {
        title: 'Work Orders',
        headerTitle: 'Work Orders'
      }
    }
}, {
  navigationOptions: ({ navigation }) => {
      const { routeName } = navigation.state.routes[navigation.state.index];
      return {
        headerTitle: routeName
      };
  }
});

const MainStackNavigator = createStackNavigator({
    MainTabNavigator
}, {
  defaultNavigationOptions: ({ navigation }) => {
      return {
        headerLeft: (
          <Icon
            style={{ paddingLeft: 10 }}
            onPress={() => navigation.openDrawer()}
            name="md-menu"
            size={30}
          />
        )
      };
    }
});

const AppDrawerNavigator = createDrawerNavigator({
  Menu: {
    screen: MainStackNavigator
  }
});

const AppSwitchNavigator = createSwitchNavigator({
  Login: { screen: Login },
  Main: { screen: AppDrawerNavigator }
});
```

Then, I have an action file where I navigate from the Login to the Main pages.
```
async
...
console.debug(response.data);  // Here the console shows value 10
NavigationService.navigate('Main', { userID: response.data });
```

In the HomeScreen page I tried to get the parameter value:
```
const { navigation } = this.props;
const userID = navigation.getParam('userID', '0');
console.debug(userID); // HERE THE VALUE IS 0, BUT SHOULD BE 10
```

What I am doing wrong? Thanks

**Comment by halbano** [comment]
What happen if you log: `this.props.navigation.state.params` on the component? Params are undefined? 

I am having kind of the same issue. 

export const navigateToOwner = (nextRoute: string) => {
  return NavigationActions.navigate({
    params: {
      nextRoute,
    },
    routeName: Route.GameSummaryOwner,
  })
}

I am navigating like this and nextRoute param is undefined later. 

Any help is appreciated.

**Comment by DgRosa** [comment]
Same problem here...

**Comment by eriveltonelias** [comment]
hi @perazzo, 

see https://github.com/react-navigation/react-navigation/issues/5646#issuecomment-469823386

the route that you trying to navigate that will receive the params.

**Comment by shawnmitchell** [comment]
> What happen if you log: `this.props.navigation.state.params` on the component? Params are undefined?
> 
> I am having kind of the same issue.
> 
> ```
> export const navigateToOwner = (nextRoute: string) => {
>   return NavigationActions.navigate({
>     params: {
>       nextRoute,
>     },
>     routeName: Route.GameSummaryOwner,
>   })
> }
> ```
> 
> I am navigating like this and nextRoute param is undefined later.
> 
> Any help is appreciated.

In the documentation for NavigationActions (https://reactnavigation.org/docs/4.x/navigation-actions#navigate) it says that params will be merged into the destination route. 

How is one meant to navigate from a stack or drawer to a non-index-0 tab of a tab navigator with params?
