### ISSUE TITLE
Reset stack navigator from drawer

### ISSUE THREAD

**Issue by pedrobrost** [react-navigation/react-navigation#6044]
Hi, this is an example of my structure 
```
  Main ( DrawerNavigator )
    --> Home ( StackNavigator )
       --> Page 1
       --> Page 2
    --> Settings
       --> ...
```
This is the secuence: I press the drawer, go to Home ( Default page 1)  and then to page 2 pressing a button in page 1. I can't find any way to go back to page 1 when I press the Home button from the drawer. Instead when I do that nothing happens.

Thanks!

**Comment by eriveltonelias** [comment]
hi there! this issue tracker is reserved for bugs only. your post seems to be a usage question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help. thanks!
