### ISSUE TITLE
How can we set navigationOptions for functional components?

### ISSUE THREAD

**Issue by a-c-sreedhar-reddy** [react-navigation/react-navigation#6045]
How can we declare navigationOptions in functional component?

**Comment by apswak** [comment]
I've just working through issues regarding this.

For hardcoded things it's fairly straightforward:

```
function YourComponent() {
  return <Text>Hi</Text>
}

YourComponent.navigationOptions = {
  tabBarLabel: 'Your custom label...',
}
```

However I'm unaware on how to use props from parent.

**Comment by a-c-sreedhar-reddy** [comment]
@satya164  How can we set the header name from props for a functional component?

**Comment by yarapolana** [comment]
plus one on the header title

**Comment by a-c-sreedhar-reddy** [comment]
> plus one on the header title

you can react to the comment

**Comment by nickmccomb** [comment]
@apswak you can use props from the parent like this:

`
<YourComponent title={'LOGIN'} />

export default YourComponent = ({ title, navigation }) => {

  YourComponent.navigationOptions = () => ({
    title
  });

  useEffect(() => {
    navigation.setParams({ title });
  }, []);

}
`

**Comment by nickmccomb** [comment]
@a-c-sreedhar-readdy you can set the header name like this:

    export default Login = ({ navigation }) => {

        const [ title, setTitle ] = useState('LOGIN')

        Login.navigationOptions = () => ({
             title
        });

        useEffect(() => {
             navigation.setParams({ title });
        }, []);

    }

**Comment by CharidimosTzedakis** [comment]
> @a-c-sreedhar-readdy you can set the header name like this:
> 
> ```
> export default Login = ({ navigation }) => {
> 
>     const [ title, setTitle ] = useState('LOGIN')
> 
>     Login.navigationOptions = () => ({
>          title
>     });
> 
>     useEffect(() => {
>          navigation.setParams({ title });
>     }, []);
> 
> }
> ```
@nickmccomb , you need to add the property navigationOptions outside the function body

**Comment by Arwiz** [comment]
This doesnt work in Lazy loaded component. Is there any workaround for lazy component ?

**Comment by jwoertink** [comment]
I just tried this, but it doesn't seem to work for me:

```javascript
const HomeScreen = props => {
    return <Text>Hello World</Text>
}
HomeScreen.navigationOptions = screenProps => ({
    headerTitle: (props) => <Text>Start</Text>,
})

<NavigationContainer>
  <Stack.Navigator>
    <Stack.Screen name="Home" component={HomeScreen} />
  </Stack.Navigator>
</NavigationContainer>
```

Instead of rendering "Start", it renders "Home". I'm using version `5.10.0`

**Comment by raajnadar** [comment]
@jwoertink , This is the proper way read the version 5 docs you are using v4 code.

``
<Stack.Screen 
  name="Home"
  component={HomeScreen}
  options={{
    headerTitle: (props) => <Text>Start</Text>
  }}
/>
```

**Comment by jwoertink** [comment]
Oh, I see. I didn't notice the "1.x" tag on this page when I came across it https://reactnavigation.org/docs/1.x/navigation-options/ Maybe since those docs are really old at this point, they can just 301 or something?

**Comment by MoneyPool-xu** [comment]
> This doesnt work in Lazy loaded component. Is there any workaround for lazy component ?

do you resolve it, i have this question

**Comment by minhth-1529** [comment]
> I've just working through issues regarding this.
> 
> For hardcoded things it's fairly straightforward:
> 
> ```
> function YourComponent() {
>   return <Text>Hi</Text>
> }
> 
> YourComponent.navigationOptions = {
>   tabBarLabel: 'Your custom label...',
> }
> ```
> 
> However I'm unaware on how to use props from parent.

How can I setState in main function?

**Comment by a-c-sreedhar-reddy** [comment]
You can pass the handler as a prop as mentioned here
https://reactnavigation.org/docs/hello-react-navigation/#passing-additional-props
