### ISSUE TITLE
Missing headerBackTitle between stacks

### ISSUE THREAD

**Issue by lkspc** [react-navigation/react-navigation#6046]
Hi, I found that `headerBackTitle` is missing when navigating to another stack navigator. The codes are below: 
```js
import React from 'react';
import { View, Button } from 'react-native';
import { createStackNavigator, createAppContainer } from 'react-navigation';

function Navigation(name, to) {
  function NavComp({ navigation }) {
    return (
      <View>
        <Button title={'go ' + to} onPress={() => navigation.navigate(to)} />
      </View>
    );
  }

  NavComp.navigationOptions = {
    title: name,
    headerBackTitle: name,
  };

  return NavComp;
}

const HomeStack = createStackNavigator({
  Home: Navigation('Home', 'Inside'),
  Inside: Navigation('Inside', 'AnotherInside'),
});

const AnotherStack = createStackNavigator({
  AnotherInside: Navigation('AnotherInside', 'Home'),
});

export default createAppContainer(
  createStackNavigator({
    Home: HomeStack,
    Other: AnotherStack,
  })
);
```
Navigation from "Home" to "Inside" will have correct `headerBackTitle`, but when navigating from "Inside" to "AnotherInside", `headerBackTitle` would missing

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |^3.11.0
| react-native     |
| node             |
| npm or yarn      |

**Comment by jforaker** [comment]
see this issue: https://github.com/react-navigation/react-navigation/issues/5802 
you probably need `backTitleVisible={true}`
