### ISSUE TITLE
Missing navigationOptions in SwitchNavigatorConfig typing

### ISSUE THREAD

**Issue by sinxwal** [react-navigation/react-navigation#6047]
### Current Behavior
SwitchNavigatorConfig interface is missing navigationOptions and defaultNavigationOptions options, however [docs](https://reactnavigation.org/docs/en/switch-navigator.html#switchnavigatorconfig) page says they are allowed here.

So when I use them, I get typings error:
Argument of type '{ navigationOptions: { tabBarLabel: any; }; }' is not assignable to parameter of type 'SwitchNavigatorConfig'.
  Object literal may only specify known properties, and 'navigationOptions' does not exist in type 'SwitchNavigatorConfig'.ts(2345)

### Expected Behavior
No typings error.

### How to reproduce
Code example:
`const AppStack = createSwitchNavigator(
  {},
  {
    navigationOptions: {
      title: 'My awesome title'
    }
  }
);`
### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.11.0
| react-native     | 0.59.9
| node             | 8.11.2
| yarn      | 1.10.1

**Comment by alexmcode** [comment]
Hi. I would like to help with this issue. Is anyone working on it?

**Comment by sinxwal** [comment]
@alexmcode The issue is really simple, so you can create pr if you have time.

**Comment by alexmcode** [comment]
Sure. I'll do that

**Comment by alexmcode** [comment]
@sinxwal the solution I found is to just add the two properties to the SwitchNavigatorConfig interface. Is this the right approach?

**Comment by satya164** [comment]
Should be fixed now.
