### ISSUE TITLE
tabBarButtonComponent can not get focused prop

### ISSUE THREAD

**Issue by Symous** [react-navigation/react-navigation#6049]
### Current Behavior
When we use `tabBarButtonComponent` to custom a tab button, there is not a simple way to get the tab focus status, with tarBarIcon, we can easily get focused & tintColor to achieve this. And I just found another way to check the focused status of a tab by check the accessibilityStates: 
```js
tabBarButtonComponent: ({ accessibilityStates }: any) => {
     const isFocused = accessibilityStates.length > 0 && accessibilityStates[0] === 'selected';
}
```
But I can not confirm whether it is reliable, is there any other way to do this?

### Expected Behavior

There is supposed to enable us to get the focused & tintColor just as tabBarIcon.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.11.0
| react-native     | 0.59.8
| node             | 11.2.0
| npm or yarn      | npm 6.4.1

**Comment by satya164** [comment]
PR welcome to add it. You need to change this line: https://github.com/react-navigation/tabs/blob/e4b976dc293446819b58e9bf4b35ff8c4aa7262c/src/views/BottomTabBar.js#L374

**Comment by Symous** [comment]
@satya164 Thanks for the guidance, I have make a PR, see it [here](https://github.com/react-navigation/tabs/pull/144).

**Comment by matthamil** [comment]
Closing this for now since it's related to the tabs repo

**Comment by SamiChab** [comment]
Hey! You can use `isFocused` from the navigationOptions params, like this:
```
static navigationOptions = ({navigation}) => {
	return {
		tabBarButtonComponent: ({onPress}) => {
			source = navigation.isFocused ? require('../icons/focused.png') : require('../icons/unfocused.png')
			return ...
		},
	}
}
```
