### ISSUE TITLE
Inconsistent headerLeft and headerRight navigation options in createStackNavigator 

### ISSUE THREAD

**Issue by hrastnik** [react-navigation/react-navigation#6050]
### Current Behavior
The behaviour of the headerLeft and headerRight props passed to navigationProps is different.

headerLeft can accept both a pre-rendered component and a component function/class
headerRight on the other hand can only accept a pre-rendered component

### Expected Behavior
It would make more sense for both props to behave the same - accepting both a component class/function and a pre-rendered component

### How to reproduce
Link to snack showing the behavior
https://snack.expo.io/B1BY4xcgS

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.11.0
| react-native     | 0.59.10
| node             | 12.4.0
| npm or yarn      | 6.9.2

**Comment by satya164** [comment]
You must pass a function for both in latest alpha of `react-navigation-stack`: https://github.com/react-navigation/stack
