### ISSUE TITLE
 Only one default export allowed per module.

### ISSUE THREAD

**Issue by Kiransonne123** [react-navigation/react-navigation#6051]
Failed to load bundle(http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false) with error:(SyntaxError: /Users/mac/Documents/navigation/App.js: Only one default export allowed per module. (45:0)

[0m [90m 43 | [39m  }[33m,[39m[0m
[0m [90m 44 | [39m})[33m;[39m[0m
[0m[31m[1m>[22m[39m[90m 45 | [39m[36mexport[39m [36mdefault[39m createStackNavigator({[0m
[0m [90m    | [39m[31m[1m^[22m[39m[0m
[0m [90m 46 | [39m  home[33m:[39m [33mHome[39m[33m,[39m[0m
[0m [90m 47 | [39m  test[33m:[39m [33mTest[39m[0m
[0m [90m 48 | [39m})[0m (null))

__38-[RCTCxxBridge loadSource:onProgress:]_block_invoke.228
    RCTCxxBridge.mm:414
___ZL36attemptAsynchronousLoadOfBundleAtURLP5NSURLU13block_pointerFvP18RCTLoadingProgressEU13block_pointerFvP7NSErrorP9RCTSourceE_block_invoke.118
__80-[RCTMultipartDataTask URLSession:streamTask:didBecomeInputStream:outputStream:]_block_invoke
-[RCTMultipartStreamReader emitChunk:headers:callback:done:]
-[RCTMultipartStreamReader readAllPartsWithCompletionCallback:progressCallback:]
-[RCTMultipartDataTask URLSession:streamTask:didBecomeInputStream:outputStream:]
__88-[NSURLSession delegate_streamTask:didBecomeInputStream:outputStream:completionHandler:]_block_invoke
__NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__
-[NSBlockOperation main]
-[__NSOperationInternal _start:]
__NSOQSchedule_f
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_continuation_pop
_dispatch_async_redirect_invoke
_dispatch_root_queue_drain
_dispatch_worker_thread2
_pthread_wqthread
start_wqthread

**Comment by satya164** [comment]
The error message says what's wrong.
