### ISSUE TITLE
[ISSUE] header on StackNavigator (nesting TabNavigator) breaks layout 

### ISSUE THREAD

**Issue by LouisJS** [react-navigation/react-navigation#6052]
### Current Behavior

This issue is related **only** to an app context using Expo For Web.
I've started to play around with this [template](https://github.com/EvanBacon/react-navigation-web-responsive-tabs-demo), and i've noticed this issue when you try to nest a MaterialTopTabNavigator inside a StackNavigator

Quick demo: https://streamable.com/mq8g4

### Expected Behavior

That should not shrink the content and breaks the layout.
Expect a default header on the SearchScreen

### How to reproduce

```
const TabNav = createMaterialTopTabNavigator(
  {
    HomeStack,
    LinksStack,
    SettingsStack
  }
);
TabNav.path = "";

export default createStackNavigator(
  {
    TabNav,
    Search: SearchScreen
  },
  { headerMode: "none" }
);
```

If you set this configuration, it will works correctly and displays nicely as expected 👍
However, if you remove the headerMode none for the StackNavigator, then your layout breaks

Quick demo: https://streamable.com/mq8g4

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  ^3.11.0
| expo     |    SDK 33
| node             |      v8.15.1
| npm    | .  6.4.1

**Comment by satya164** [comment]
@EvanBacon

**Comment by LouisJS** [comment]
Temporary fix:

I've created a customNavigator adding a 'Header' component with navigation props by hand.

```
export default class CustomNavigator extends React.Component {
    static router = TabNav.router;
    render() {
        const { navigation } = this.props;

        return (
            <View style={{ flex: 1 }}>
                <Header navigation={navigation} />
                <TabNav navigation={navigation} />
            </View>
        );
    }
}
```
