### ISSUE TITLE
reactnavigation is not working with react-native 0.60.0

### ISSUE THREAD

**Issue by viveknaragude** [react-navigation/react-navigation#6053]
React-native 0.60.0 is release, they added Autolinking of package feature and manual linking not suuport(like react-native link react-native-gesture-handler)

Ref : https://github.com/react-native-community/releases/blob/master/CHANGELOG.md

**Comment by satya164** [comment]
Manual linking is still supported. Also please open issues about linking gesture handler in gesture handler repo.

**Comment by viveknaragude** [comment]
Sorry, Thank you to correct me .

**Comment by SeaMoonTime** [comment]
> Manual linking is still supported. Also please open issues about linking gesture handler in gesture handler repo.

How can I manual link? The React Navigation is just dead with this problem.

**Comment by satya164** [comment]
https://github.com/kmagiera/react-native-gesture-handler/issues/671#issuecomment-508903588
