### ISSUE TITLE
Overriding native go back action

### ISSUE THREAD

**Issue by TfADrama** [react-navigation/react-navigation#6056]
In my app i am using the native back button but i used headerBackImage property while creating the stack navigator. In one particular screen i need to customize the back action because im using a webview there. 

The following code represents the only way to do it, but in the props from the HeaderBackButton component there's no background image. So I need to create a whole new component exactly the same as used in react-navigation but with a different image to use as headerLeft. 

I think this should be a thing to to change in future releases of react-navigation.

```
import { HeaderBackButton } from 'react-navigation';

static navigationOptions = ({ navigation }) => {
    let goBack = navigation.goBack;
    if (navigation.state.params.onGoBack) {
      goBack = navigation.state.params.onGoBack;
    }
return {
      headerLeft: <HeaderBackButton onPress={() => goBack()} tintColor={'red'} />,
    };
}
```

_Originally posted by @feong in https://github.com/react-navigation/react-navigation/issues/2714#issuecomment-361206934_

**Comment by matthamil** [comment]
I encourage you to open a PR with this change. If you need any help along the way, don't hesitate to tag myself or any of the other project volunteers in the PR directly!
