### ISSUE TITLE
cannot read property 'bind' of undefined 

### ISSUE THREAD

**Issue by cliek** [react-navigation/react-navigation#6058]
Hello, I have a problem using react-native navigator. It works well in the Android simulator, but it does not work in the IOS simulator.
I've looked at a lot of documents, but none of them works.
### The picture of the problem is as follows.
![image](https://user-images.githubusercontent.com/29326163/60758839-6a21bd00-a04e-11e9-9e5f-003f6a465d10.png)
### babel.config.js
![image](https://user-images.githubusercontent.com/29326163/60758881-077cf100-a04f-11e9-9c9c-15017b885595.png)

### package.json
![image](https://user-images.githubusercontent.com/29326163/60758873-f207c700-a04e-11e9-8161-3f836f5e08ef.png)
### Description
I.ve seen this link [https://github.com/facebook/react-native/issues/22157](url),Modifier configured
` plugins: [
        ["@babel/plugin-transform-flow-strip-types"],`
But it didn't work.
Other configurations：
`system：mac os 
simulator：iphone 8 12.2 
reactnative version 0.59.9`

**Comment by satya164** [comment]
Remove the class properties Babel plugin.

**Comment by cliek** [comment]
> Remove the class properties Babel plugin.
![image](https://user-images.githubusercontent.com/29326163/60759296-6b0a1d00-a055-11e9-8179-8099e306d0a1.png)
I commented on other class Babel components, which is still the problem.
Because I installed mbox, I needed to rely on the ES7 modifier to use the class Babel plug-in.

**Comment by oradkovsky** [comment]
I've removed `["@babel/plugin-proposal-class-properties", { "loose": true}]` and it did not have any positive impact. I don't understand why this issue is closed.

**Comment by oradkovsky** [comment]
What actually helped in my case was adding this plugin (and resetting cache of course):
`["@babel/plugin-transform-flow-strip-types"],`

**Comment by IdkMan2** [comment]
For anyone having the same problem:
1. Remove `@babel/plugin-proposal-class-properties` from package.json & babel.config.js
2. Add `@babel/plugin-transform-flow-strip-types` to package.json & babel.config.js
3. Run `expo r -c` to clear cache and start expo

If this does not help also try to remove node_modules/package-lock.json & install again.
