### ISSUE TITLE
Remove header from TabStack

### ISSUE THREAD

**Issue by ithustle** [react-navigation/react-navigation#6059]
info 
  React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
      Memory: 469.70 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.4.0 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 23, 24, 25, 26, 27, 28
        Build Tools: 23.0.1, 23.0.3, 25.0.0, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.2, 28.0.3
        System Images: android-26 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.6 => 16.8.6 
      react-native: 0.59.10 => 0.59.10 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
react-navigation: 3.11.0

<img width="350" alt="Captura de ecrã 2019-07-07, às 19 11 48" src="https://user-images.githubusercontent.com/5114680/60772235-62642600-a0eb-11e9-9ad3-69c805d43dd0.png">

How can I remove header from TabScreen?

I tried to use `headerMode: "none"` but removed header's screens too.

**Comment by satya164** [comment]
Please read the docs https://reactnavigation.org/docs/en/navigation-options-resolution.html

**Comment by ithustle** [comment]
@satya164 , is there a way to remove only on TabScreen?
