### ISSUE TITLE
The React Navigation doesn't work in React Native 0.60 for react-native-gesture-handler linking bug

### ISSUE THREAD

**Issue by SeaMoonTime** [react-navigation/react-navigation#6064]
![Simulator Screen Shot - iPhone X - 2019-07-09 at 16 27 33](https://user-images.githubusercontent.com/32903875/60872002-7ed89d80-a266-11e9-8282-e1c70d2829d4.png)

I try all solutions but still have this problem.

**Comment by SeaMoonTime** [comment]
**No matter how I try with all methods. This bug is still there. I think React Navigation is Dead with this serious BUG.**

**Comment by satya164** [comment]
> No matter how I try with all methods

What methods did you try?

https://github.com/kmagiera/react-native-gesture-handler/issues/671#issuecomment-508903588

**Comment by SeaMoonTime** [comment]
I have try it and in iOS it works well, but the bug is still there in Android.

**Comment by SeaMoonTime** [comment]
@satya164 , I finally find the method. 

[Fix react-native-gesture-handler Tutorial](https://youtu.be/NcQhDlC7hT8)

**Comment by SeaMoonTime** [comment]
[Please see the tutorial](https://youtu.be/NcQhDlC7hT8)
