### ISSUE TITLE
How to add transitionConfig for createBottomTabNavigator

### ISSUE THREAD

**Issue by tuantvk** [react-navigation/react-navigation#6065]
i want add transition for createBottomTabnavigator
my code:

```
const Stack = createStackNavigator({
  stack1: { screen: stack1 },
  stack2: { screen: stack2 },
},
{
  headerMode: 'none',
  navigationOptions: {
    headerVisible: false,
  },
  transitionConfig: () => fromRight(),
}
)

const TabBottom = createBottomTabNavigator({
  screen1: { screen: Stack },
  screen2: { screen: screen2 },
  screen3: { screen: screen3 },
})
```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^3.5.0
| react-native     | 0.57.4
| node             | v8.10.0
| npm or yarn      | 6.9.0

**Comment by satya164** [comment]
`createBottomTabNavigator` doesn't support animations. You can use `createMaterialTopTabNavigator` for animations with a `tabBarPosition` of `bottom`

**Comment by jpmasud** [comment]
If we use createMaterialTopTabNavigator, we still can't provide a transitionConfig, can we?

**Comment by niksudan** [comment]
@satya164 Are you able to provide an example of using animations with `createMaterialTopTabNavigator`? There does not appear to be [any appropriate properties](https://reactnavigation.org/docs/en/material-top-tab-navigator.html) for this.
