### ISSUE TITLE
HeaderTitle component is not exported in typescript definition

### ISSUE THREAD

**Issue by Aure77** [react-navigation/react-navigation#6069]
### Current Behavior

Importing `HeaderTitle` component cause a typescript warning :
`Module '"react-navigation"' has no exported member 'HeaderTitle'.ts(2305)`

### Expected Behavior

as this component is exported from react-navigation.js https://github.com/react-navigation/react-navigation/blob/a3092ab17df454793382bf6123121b5f20fe9f12/src/react-navigation.js#L166-L168
it should have TS definition in _react-navigation.d.ts_

### How to reproduce

`import { HeaderTitle } from "react-navigation";` into a tsx file
See warning in your IDE.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.11.0
| react-native     | 0.59.8
| node             | 10.15.3
| npm or yarn      | yarn 1.16.0

**Comment by satya164** [comment]
Should be fixed in https://github.com/react-navigation/stack
