### ISSUE TITLE
The items of BottomTabNavigator are not centered vertically when using a 12.9-inch's iPad

### ISSUE THREAD

**Issue by iwashi1t** [react-navigation/react-navigation#6070]
### Current Behavior

The items of BottomTabNavigator are not centered vertically when using a 12.9-inch's iPad. There is unnecessary padding at the bottom as shown in the screenshot below. It works fine when using a 9.7-inch iPad or iPhone.

![IMG_7E7BA3B6D765-1](https://user-images.githubusercontent.com/25096711/61037706-89ca3400-a406-11e9-8fa1-b705a5fcf688.jpeg)

### Expected Behavior

The items of BottomTabNavigator are centered vertically.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  3.11.0
| react-native     | 0.59.9
| node             | 11.0.0
| npm or yarn      | npm 6.9.0

**Comment by satya164** [comment]
Please provide a minimal runnable repro

**Comment by iwashi1t** [comment]
Thank you for replying.
I prepared the following. Please confirm.

https://github.com/iwashi1t/ReactNavigation6070

![Simulator Screen Shot - iPad Pro (12 9-inch) - 2019-07-16 at 17 58 07](https://user-images.githubusercontent.com/25096711/61281231-44d24300-a7f4-11e9-8dd7-d0a9b0604b6f.png)

**Comment by satya164** [comment]
I believe this is the safe area. Closing since this is expected.
