### ISSUE TITLE
React-Navigation "createBottomTabNavigator" header overwriting already existed header of each class.

### ISSUE THREAD

**Issue by aunabbas007** [react-navigation/react-navigation#6072]
All classes of my "React Native" code have their own header implemented using "navigationOptions" and I've created the "bottomTabNavigator" that has its own header overwriting the existing header and their functionality. How to hide the "bottomTabNavigator" header while own headers of classes work properly and accordingly?

I've used "header: null" and "navigationOptions: { header: null, }" in the stack of "bottomTabNavigator" and also "header: { visible: false, }" but it didn't work, as header is still visible.

I expect that header of 'bottomTabNavigator" should be hidden and it should not overwrite the already existing headers of every class.
![11](https://user-images.githubusercontent.com/48434011/61045708-d1e05b00-a3f4-11e9-8db7-6924b3697a16.JPG)
![22](https://user-images.githubusercontent.com/48434011/61045712-d278f180-a3f4-11e9-9b6b-3af25de52329.JPG)

**Comment by satya164** [comment]
https://reactnavigation.org/docs/en/navigation-options-resolution.html

**Comment by NischayaSharma** [comment]
> 
> 
> https://reactnavigation.org/docs/en/navigation-options-resolution.html

Page not found, what should we do ??
