### ISSUE TITLE
RN: 0.60.0 compile error : RNGestureHandlerEnabledRootView(MainActivity.this) && "can't find symbol"

### ISSUE THREAD

**Issue by ezranbayantemur** [react-navigation/react-navigation#6073]
I'm trying to install react-navigation package to my project. I did all instructions on [here](https://reactnavigation.org/docs/en/getting-started.html#installation) and I search on GitHub, StackOverflow but can't find any solution, still getting error while compiling

My package.json:
-     "react": "16.8.6",
-     "react-native": "0.60.0",
-     "react-native-gesture-handler": "^1.3.0",
-     "react-native-safe-area-view": "^0.14.6",
-     "react-navigation": "^3.11.0",
-     "react-redux": "^7.1.0",
-     "redux": "^4.0.3"

Error output:

> > Task :app:compileDebugJavaWithJavac FAILED
> 
> Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
> Use '--warning-mode all' to show the individual deprecation warnings.
> See https://docs.gradle.org/5.4.1/userguide/command_line_interface.html#sec:command_line_warnings
> 13 actionable tasks: 2 executed, 11 up-to-date
> C:\Users\ezran\Desktop\SADELABS\reduxTest\android\app\src\main\java\com\reduxtest\MainActivity.java:6: error: package com.swmansion.gesturehandler.react does
> not exist
> import com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView;
>                                          ^
> C:\Users\ezran\Desktop\SADELABS\reduxTest\android\app\src\main\java\com\reduxtest\MainActivity.java:24: error: cannot find symbol
>                 return new RNGestureHandlerEnabledRootView(MainActivity.this);
>                            ^
>   symbol: class RNGestureHandlerEnabledRootView
> 2 errors
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':app:compileDebugJavaWithJavac'.
> > Compilation failed; see the compiler error output for details.
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 7s
> 
> error Failed to install the app. Make sure you have the Android development environment set up: https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.
> Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
> C:\Users\ezran\Desktop\SADELABS\reduxTest\android\app\src\main\java\com\reduxtest\MainActivity.java:6: error: package com.swmansion.gesturehandler.react does
> not exist
> import com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView;
>                                          ^
> C:\Users\ezran\Desktop\SADELABS\reduxTest\android\app\src\main\java\com\reduxtest\MainActivity.java:24: error: cannot find symbol
>                 return new RNGestureHandlerEnabledRootView(MainActivity.this);
>                            ^
>   symbol: class RNGestureHandlerEnabledRootView
> 2 errors
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':app:compileDebugJavaWithJavac'.
> > Compilation failed; see the compiler error output for details.
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 7s
> 
>     at checkExecSyncError (child_process.js:616:11)
>     at execFileSync (child_process.js:634:13)
>     at runOnAllDevices (C:\Users\ezran\Desktop\SADELABS\reduxTest\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:75:39)
>     at buildAndRun (C:\Users\ezran\Desktop\SADELABS\reduxTest\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\index.js:137:41)
>     at then.result (C:\Users\ezran\Desktop\SADELABS\reduxTest\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\index.js:103:12)
>     at process._tickCallback (internal/process/next_tick.js:68:7)

Any help?

**Comment by davidst2017** [comment]
Same problem

**Comment by sinodko** [comment]
Same here...

**Comment by davidst2017** [comment]
Two things: 
1. npm install jetifier
    npx jetify

2. 
`module.exports = {
  dependencies: {
    'react-native-gesture-handler': {
      platforms: {
        android: null, <--- delete this line! in native.config.js
        ios: null,
      },
    },
  },
};`

**Comment by sinodko** [comment]
If it is not working you can also try a hack from [react-native-gesture-handler Issue - 684](https://github.com/kmagiera/react-native-gesture-handler/issues/684)

**Comment by satya164** [comment]
Closing due to missing repro.

I have tested the steps in the getting started guide and they work. If you're having issues, please provide a proper repro so we can actually see what's wrong and if you figure out a fix, please send a PR to fix the documentation.

**Comment by wqzwh** [comment]
look this https://github.com/kmagiera/react-native-gesture-handler/issues/691
