### ISSUE TITLE
For RN 0.60 autolinking, Android  Error: null is not an object (evaluating 'RNGestureHandlerModule.State'.

### ISSUE THREAD

**Issue by kqzh** [react-navigation/react-navigation#6075]
### Current Behavior

I updated RN to 0.60

Create a new project

I follow the steps of navigation website strictly.

Now I execute run-android without reporting errors

But whenever you use navigation components, my virtual machine prompts for errors

Null is not an object (evaluating'RNGestureHandlerModule. State')

### Expected Behavior

I can use navigation components like RN0.59,no bugs

### How to reproduce

Just follow the steps of navigation website strictly.
no superfluous operation
I dont know how to solve this problem

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.11.0
| react-native     | 0.60
| node             | 10.15.0
|  yarn      | yarn -1.16.0

**Comment by satya164** [comment]
Please provide a proper repro according to the issue template.

**Comment by ricbermo** [comment]
@kqzh can u try this? https://github.com/react-navigation/react-navigation/issues/6074#issuecomment-510691037 may be related.

**Comment by satya164** [comment]
Closing due to no repro
