### ISSUE TITLE
Bottom tabs icon not visible

### ISSUE THREAD

**Issue by vtechguys** [react-navigation/react-navigation#6076]
My Navigator is like Switch->Drawer->Stack->Tabs->Stack:Screens. The problem is I don't get any icon. To Replicate Here is a repo.[GitHub-App-RN](https://github.com/vtechguys/app-rn). 
Hope to get help soon...

**Comment by satya164** [comment]
Please provide a minimal repro containing as few files as possible

**Comment by vtechguys** [comment]
I have provided the link above.
Here:
https://github.com/vtechguys/app-rn

**Comment by satya164** [comment]
It has too many files. We don't have the bandwidth to debug it. Please provide a minimal repro.

**Comment by vtechguys** [comment]
https://github.com/vtechguys/react-navigation-v3-issue
This is minimal repo.

**Comment by vtechguys** [comment]
@satya164 Any update on this?

**Comment by satya164** [comment]
There are no icons specified for the tab bar in your example. Please read the docs https://reactnavigation.org/docs/en/material-bottom-tab-navigator.html#tabbaricon

**Comment by vtechguys** [comment]
@satya164  I know tabBarIcon property is a function that must return React node. While producing the minimal repo I forgot to check tabBarIcon property. I have experimented a lot with it earlier.
To respect your point I have updated the repo.
So kindly check the updated repo. 
Thanks.

**Comment by satya164** [comment]
`tabBarIcon` is a property in the static `navigationOptions` of the component you have as the screen, you're specifying it in a completely unrelated screen.

```js
SettingsStack.navigationOptions = {
  tabBarIcon: () => <Icon name="md-menu" size={20} />,
};
```

This is already documented https://reactnavigation.org/docs/en/navigation-options-resolution.html
