### ISSUE TITLE
PROPOSAL: Update tab bar example - passing props

### ISSUE THREAD

**Issue by usrbowe** [react-navigation/react-navigation#6077]
### Current Behavior
This whole issues is referring to example code here: 
**DOCS**: https://reactnavigation.org/docs/en/tab-based-navigation.html
**SNACK**: https://snack.expo.io/@react-navigation/stacks-in-tabs-v3

When I want to pass params from Home screen to Settings screen it would fail.

### Expected Behavior

My personal view is, that passing params between tabs/stacks should work. Maybe the current bahavior is intentional for some other reasons.
I also found other issues, having similar problem: #3787, #143

### How to reproduce

I copy&paste the snack from documentation (link above).
I made two tiny changes.
1. Home: Pass params to Settings screen `{ name: 'Lukas'}`
2. Settings: Render `name` from navigation params.

🐛 Example of problem: https://snack.expo.io/@usrbowe2/stacks-in-tabs-v3---fixed-params

✅ Example of fix: https://snack.expo.io/@usrbowe2/stacks-in-tabs-v3---fixed-params

### Proposed solution

To be honest, I don't know what is correct way to fix this. The only thing I changed in code is renaming each tab stack. So the screenName doesn't collide with name of nested screen.
From `Home: { screen: HomeStack }` -> `HomeStack: { screen: HomeStack }`. This will allow passing params to `Home` screen directly.

**Comment by matthamil** [comment]
The purpose of route params is to pass data while navigating. If you aren't navigating to another screen and want to pass data to the other screen, the navigation library's job isn't to manage that transaction. There are other patterns that are more suitable for this--global state management like redux, having a component in screen B "observe" something that screen A is managing, letting both screens be consumers of the same context, etc. 

If you _do_ think this should be something that react-navigation should include as a feature, I encourage you to move your RFC into the [RFCs](https://github.com/react-navigation/rfcs) repo.

**Comment by usrbowe** [comment]
@matthamil 
The usecase I'm describing is "passing params while navigating". It's not to replace Context/Redux. Let's say I wanna pass just simple `id` to another route, while navigating, this would fail.
