### ISSUE TITLE
How do I update navigation params, without navigating to screen again?

### ISSUE THREAD

**Issue by shubhamdeol** [react-navigation/react-navigation#6082]
I have a screen component ```Order``` and I am passing data from ```order``` screen to ```OrderDetails``` screen.

```javascript
showOrderDetails = () => {
    const { orderData } = this.props;
    NavigationService.navigate('OrderDetails', {
      orderDetails: orderData,
    });
  }

```

Inside order details I am updating the order data (let's say payment info), using redux. 
So, my ```Orders``` screen is updated now I want to pass updated **OrderDetails**, parameters to ```OrderDetails``` screen. I don't know how to update **params** without renavigating to screen.

Right now, I fixed my problem, but this might result in bugs in the future. 
for Now, I am doing this

```javascript
  componentDidUpdate(prevProps) {
    const { orderData } = this.props;
    if (orderData.payment_mode.id !== prevProps.orderData.payment_mode.id) {
      this.showOrderDetails();
    }
  }
```

Is there any solution without re-navigating ?

**Comment by matthamil** [comment]
Check out https://reactnavigation.org/docs/en/headers.html#updating-navigationoptions-with-setparams
