### ISSUE TITLE
enable/disable header and tabBar on specific screen is not working sometime! acting randomly on any screen

### ISSUE THREAD

**Issue by dipakparmar** [react-navigation/react-navigation#6086]
I have two stack navigatior which has two screens and I want to set header: null for the second screen and for first screen tabBarvisible: false but it applying one stack, not for other one. 

```
export default (HomeStack = createStackNavigator({
  Home: {
    screen: HomeScreen,
    navigationOptions: {
      header: null,
      tabBarVisible: true ,
    }
  },
  Details: {
    screen: DetailsScreen,
    navigationOptions: {
      header:null,
      tabBarVisible: fasle,
    }
  }
}));


  HomeStack.navigationOptions = {
  tabBarLabel: '',
  header: null,
  tabBarIcon: ({ focused }) => (
    <TabBarIcon type='AntDesign' name='home' />
  )
};
```

```
export default CategoriesStack = createStackNavigator({
  Category: {
    screen: CategoryScreen,
    header:null,
    tabBarVisible: false,
  },

});


CategoriesStack.navigationOptions = {
  tabBarLabel: '',
  header: null,
  tabBarIcon: ({ focused }) => (
    <TabBarIcon type='Foundation' name='thumbnails' />
  )
};
```

If anyone knows please help out!

| Software | Version |
| ---------| --------|
| react-native |https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz  |
| react | 16.8.3  |
| expo | 2.21.2 |
| yarn | 1.16.0 |

_Originally posted by @dipakparmar in https://github.com/react-navigation/react-navigation/issues/3958#issuecomment-511164995_

**Comment by matthamil** [comment]
Hello! Can you create a reproducible example in a public GitHub repo or as a [Snack](https://snack.expo.io)? Code snippets are great, but a cloneable repo that has only the parts necessary to reproduce your issue is even better. Thanks!

**Comment by satya164** [comment]
You're setting `tabBarVisible` in a stack navigator. This is expected behaviour https://reactnavigation.org/docs/en/navigation-options-resolution.html
