### ISSUE TITLE
createSwitchNavigator with gesture

### ISSUE THREAD

**Issue by Piero87** [react-navigation/react-navigation#6088]
Hi,
I read the documentation for this page: https://reactnavigation.org/docs/en/switch-navigator.html

but, I can't understand if the gesture are available for this type of navigation to go back like in stacknavigation.

I have tried to do this:

```
    navigationOptions: {
      gesturesEnabled: true
    }
```

but the gesture doesn't work.

thanks

**Comment by matthamil** [comment]
The Switch Navigator does not handle back actions and does not have a `gesturesEnabled` option because of that. If you want to "go back" from a switch navigator, you will need a stack navigator to render the switch navigator.
