### ISSUE TITLE
scroll, scrollview, flatlist doesn't scrolling with react navigation

### ISSUE THREAD

**Issue by aznoisib** [react-navigation/react-navigation#6089]
This bug only occurs on certain devices, the case is on my Android. I think this is scrolling freezes

### How to reproduce

- Tested on react native app

1. expo
2. react native paper
3. codepad (my experiment app)

Scrolling freezes: yes

- tested on native mobile app
1. android example

Scrolling freezes: no

video sample 1
https://www.dropbox.com/s/5mh8aje1cv0e7q6/mobizen_20190720_125215.mp4?dl=0

sample videos 2
https://www.dropbox.com/s/z5eupip3s9ozmqa/mobizen_20190720_125825.mp4?dl=0

### Solution
try to detect a device that has a bug

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | latest
| react-native     | latest

Android Device info
https://www.dropbox.com/s/4mn6tswvlums1hm/Screenshot_Setelan_20190720-124232.png?dl=0

**Comment by aznoisib** [comment]
i mean freeze scroll

**Comment by anastely** [comment]
@aznoisib  Any updates?

**Comment by matthamil** [comment]
I'm not sure I understand what your issue is @aznoisib. Can you provide more details?

**Comment by Modest4** [comment]
I have the same issue. At the moment I use react navigation (here a stack navigator) I can't scroll nor trigger (onTouch with <TouchableOpacity>) anything.

**Comment by aznoisib** [comment]
This bug only occurs on certain devices, the case is on my Android. I think this is scrolling freezes


Tested on react native app

1. expo
2. reqct native paper
3. codepad (my experiment app)

issues: yes



tested on native mobile app
1. android example

issues: no

video sample 1
https://www.dropbox.com/s/5mh8aje1cv0e7q6/mobizen_20190720_125215.mp4?dl=0

sample videos 2
https://www.dropbox.com/s/z5eupip3s9ozmqa/mobizen_20190720_125825.mp4?dl=0

Device info
https://www.dropbox.com/s/4mn6tswvlums1hm/Screenshot_Setelan_20190720-124232.png?dl=0

**Comment by matthamil** [comment]
I can scroll on my Samsung Galaxy S9+ in the Android React Navigation examples project. Does this only happen with React Navigation or does this not work for any scrollable view from React Native on your Android device?

**Comment by aznoisib** [comment]
yes only on certain Android devices that will find this bug, yes this bug is in the scroll section

**Comment by aznoisib** [comment]
I tried to compare with native mobile android but there are no scroll bugs

**Comment by matthamil** [comment]
Can you `react-native init` a new project and use a `<ScrollView/>` or `<FlatList/>` and see if those can scroll on your Android devices? I want to see if you can isolate the problem to `react-navigation` in particular. If it causes an issue only after introducing `react-navigation`, it could be a compatibility issue `react-native-screens` and the flavor of Android you are using.

**Comment by aznoisib** [comment]
This bug may occur on certain Androids, not just the Android I use, I've also tried without react navigation and bug still appear

**Comment by aznoisib** [comment]
on the flatlist and scrollview components

**Comment by aznoisib** [comment]
Without react navigation 

Videos here
https://www.dropbox.com/s/78aa5g7ypnpkrna/mobizen_20190727_054008.mp4?dl=0

Snipet here
https://snack.expo.io/@aznoisib/remounted-scrolling-component-with-key

**Comment by matthamil** [comment]
If you are experiencing this problem without react-navigation installed, you will need to open an issue in the react-native repo. There's nothing actionable for us here.
