### ISSUE TITLE
How can i make two drawers?

### ISSUE THREAD

**Issue by frndmr** [react-navigation/react-navigation#6090]
Hello, i want to make specific two drawers on the left and right. I could not find a solution for this. I can make only one drawer.

**Comment by Hatvan** [comment]
+1

**Comment by Hatvan** [comment]
solved by lowering the version of drwer.
I do not know why getCustomActionCreators is missing in the latest version

https://github.com/react-navigation/drawer/issues/8

**Comment by frndmr** [comment]
I used another package. https://www.npmjs.com/package/react-native-drawer-layout
