### ISSUE TITLE
Circular Reference between topBarNavigator and StackNavigator ?

### ISSUE THREAD

**Issue by Seeyko** [react-navigation/react-navigation#6104]
StackNavigator use to display a screen with a list of similars movie and when you click on one of them you go the details 
```
const FilmDetailSimilarsNavigator = createStackNavigator(
  {
    FilmDetailSimilar: {
      screen: FilmDetailSimilars,
  },
    FilmDetail: {
      screen: FilmDetailsNavigator, //First reference
  }
    },
    {
        headerMode: "none",
        headerBackTitleVisible: true
    }
);
```
Top bar navigator with 'movies details', 'crew' and 'similar movies' tabs
```
const FilmDetailsNavigator = createMaterialTopTabNavigator(
    {
        Details: {
            screen: FilmDetail,
            navigationOptions: {
                tabBarLabel: 'Details'
            }
        },
        Similar: {
            screen:  FilmDetailSimilarsNavigator, // Second ref
            navigationOptions: {
                tabBarLabel: "Similaire"
            }
        }, 
        Equipes: {
            screen: FilmDetailActorsNavigator,
            navigationOptions: {
                tabBarLabel: "L'équipe"
            }
        },
    },
    {
        swipeEnabled: true,
        tabBarOptions: {
            activeTintColor: '#000',
            inactiveTintColor: 'gray',
            style: {
                backgroundColor: '#DDDDDD',
            },
            indicatorStyle: {
                backgroundColor: '#000',
            },
        }
    }
);

```
### Behaviour
My main screen is a list of movies, when you click on a movie it goes to the Details screen wich is the `FilmDetailsNavigator` screen wich included an other list of 'similars' movies and you can click on one of them you go again at the Details screen but with this new movie as parameters. \
You can circle through as many movies as you want. But right now, when i click on a similar movie i get an error because my `FilmDetailSimilarsNavigator` screen is declared before my  `FilmDetailsNavigator`

![Error](http://projects.tomandrieu.com/Documents/Film_Selector/66852949_469741643576356_259133076527906816_n.jpg)

Youtube video of the behaviour (no design on the app) : [Circular Reference between topBarNavigator and StackNavigator ?](https://youtu.be/jKZ6hapRyVY)

Environnments : 
- react-navigation v3.11.0
- react-native v0.59.8
- node v12.4.0
- npm v6.9.0

Edit: I have seen the closed issue #1396 but without any response on it and without finding any other solutions i have made this one.

**Comment by matthamil** [comment]
Hello! Can you create a reproducible example in a public GitHub repo or as a [Snack](https://snack.expo.io)? Code snippets are great, but a cloneable repo lets us see everything necessary to reproduce the issue as you are seeing it.

**Comment by Seeyko** [comment]
> Hello! Can you create a reproducible example in a public GitHub repo or as a [Snack](https://snack.expo.io)? Code snippets are great, but a cloneable repo lets us see everything necessary to reproduce the issue as you are seeing it.

Hello matt, here the snack, i have adapt the code from my projects so it may have some unused styles or librairies but the main idea is there.
You will find the problem in 'components/Navigation.js'

Snack : https://snack.expo.io/@seeyko/seeyko-circular-references-in-react-navigation

**Comment by satya164** [comment]
It's not possible to have circular references. Code like this won't work:

```js
const a = { foo: b };

const b = { foo: a };
```

**Comment by Seeyko** [comment]
Yeah thanks satya i know that the code wont work like that. But a lot of app have the behaviour i ask so i'm pretty sure there is another solution that i dont see.

**Comment by satya164** [comment]
Due to the way current version of React Navigation works, you can't do it.

**Comment by Seeyko** [comment]
You doesn't seems so pessimist on the issue #1396, did you think other librairies of navigation can do it or i have to create my own navigation ?

**Comment by satya164** [comment]
Well, I was wrong on that issue. `getScreen` will work for screens, but not navigators.

> did you think other librairies of navigation can do it or i have to create my own navigation ?

I'm not sure why you need circular reference since it should be possible to navigate between the tabs and stack.

I'm working on a different API where you could have things like this https://github.com/react-navigation/navigation-ex

**Comment by Seeyko** [comment]
> Well, I was wrong on that issue. `getScreen` will work for screens, but not navigators.
Ok, no problem :)
I don't 'want' to do a circular references. For the moment this is what i have and it doesn't work so i just search for maybe an alternavite or a correct way to do it.

> I'm working on a different API where you could have things like this https://github.com/react-navigation/navigation-ex
Ok i will try with this one thanks
