### ISSUE TITLE
Customize the sliding distance that can be returned. I'm not referring to the “horizontal“ attribute.

### ISSUE THREAD

**Issue by ngxu** [react-navigation/react-navigation#6111]
Hello!

By default, it's about half of the screen before returning. I think it's possible to return by sliding to one third of the screen width (or customized distance). How do I do it?

Who can help me? Thank you very much.

**Comment by ngxu** [comment]
I just want to think that sliding to one third of the screen or customizing the distance can execute the return method, and the default distance is a little bit large, about half of the screen, which is a little inconvenient. Often want to slide back, not sliding to half of the screen to release the hand, resulting in the page rebound, did not return to the previous page.


![image](https://user-images.githubusercontent.com/43433064/61602098-e7624a00-ac6a-11e9-93e0-e9422ba19cd0.png)
This document does not contain what I want, and I think this attribute can be added. Make it more flexible to slide back to the previous page

**Comment by matthamil** [comment]
I'm not sure I understand your question. Can you provide more details?

**Comment by satya164** [comment]
Closing due to no response.
