### ISSUE TITLE
Blank screen for iOS release builds

### ISSUE THREAD

**Issue by jeremyfrancis** [react-navigation/react-navigation#6112]
#6103 
## Current Behavior

I've simplified my code down to the most basic form. I just want it to show this green background. When I run in debug it works great but when I run for release I get a white screen. I changed the rootView backgroundColor in my AppDelegate.m to black and now I get a black screen. So that proves it's just showing the rootView and nothing else. When I put just a <View /> component in and don't use the createAppContainer or anything it shows that View in release mode no problem.

We are using redux but I've taken it out of the way by removing it from the render method and just put in a View and AppContainer to try to get it working. However, I've had no luck.

`class TestHome extends Component {
  componentDidMount() {
    alert('TestHome mounted')
  }
  render() {
    return <View style={{
      backgroundColor: 'green',
      width: Dimensions.get('window').width,
      height: Dimensions.get('window').height,
    }} />
  }
}

export const MyStackNavigator = createStackNavigator({
  Home: TestHome
},{
  initialRouteName: 'Home'
})
export const AppContainer = createAppContainer(MyStackNavigator)

render() {
return <View style={{ flex: 1, backgroundColor: 'red' }}>
      <AppContainer />
    </View>
}`

### Expected Behavior

A green background should be showing up. And then eventually our entire app.

### How to reproduce

From what I can tell this should be reproducible by simply making a new project with the same versions I have and putting in a app container, stack navigator, and a view, then compiling for release with this. When I compile for release I do Product > Scheme > Edit Scheme > Release. I set my AppDelegate jsCodeLocation to main2 jsbundle. I run my bundle command:

`react-native bundle --entry-file index.js --platform ios --dev false --bundle-output ios/main2.jsbundle --assets-dest ./app/assets`

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^3.11.1
| react-native     | 0.59.10
| node             |  v10.16.0
| npm or yarn      | npm

**Comment by satya164** [comment]
The code you provided is invalid syntax. Please provide a proper runnable repro.

**Comment by matthamil** [comment]
Are you still experiencing this issue @jeremyfrancis after correcting any syntax problems? If not, I will be closing this issue within the next couple of days since a maintainer has provided a solution to your problem.
