### ISSUE TITLE
createBottomTabNavigator adding tabBarIcon gives 'Unexpected token' error

### ISSUE THREAD

**Issue by edrichhans** [react-navigation/react-navigation#6114]
### Current Behavior

- Unexpected token, expected "</>/<=/>="
<img width="358" alt="Screen Shot 2019-07-22 at 3 19 10 PM" src="https://user-images.githubusercontent.com/13763624/61613553-37093b80-ac94-11e9-9fc1-55770b337dc3.png">

### Expected Behavior

- Icons will render at bottom tab navigator

### How to reproduce

```
import Ionicons from 'react-native-vector-icons/Ionicons';

export const BottomTabNavigator = createBottomTabNavigator({
  services: { screen: ServicesNavigator },
  create: { screen: CreateServiceScreen },
  messages: { screen: MessageNavigator },
  account: { screen: AccountNavigator },
}, {
  defaultNavigationOptions: ({navigation}) => ({
    tabBarIcon: ({ focused, horizontal, tintColor }) => {
      return <Ionicons name="ios-build" size={20} />;
    }
  })
})
```

- The error is produced at the line with `<Ionicons>`

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.0.0
| react-native     | 0.59.3
| node             | 8.10
| npm or yarn      | 1.12.3

**Comment by satya164** [comment]
This is a syntax error, so definitely something not related to React Navigation. Please double check your code and try clearing metro cache.

**Comment by edrichhans** [comment]
I just figured out my problem. All this time my file's extension was `.ts`, which does not support jsx, instead of `.tsx`.

**Comment by connoremma** [comment]
Had the same issue, @edrichhans solution worked for me

**Comment by cuongw** [comment]
I use react-navigation with TypeScript and I had the same issue. Have a solution @edrichhans , @connoremma . Thanks 🙏!
![Screenshot from 2019-11-17 23 37 39](https://user-images.githubusercontent.com/34389409/69010531-53dc2400-0993-11ea-93de-5e8dedb5ddd4.png)

**Comment by bygirish** [comment]
> I just figured out my problem. All this time my file's extension was `.ts`, which does not support jsx, instead of `.tsx`.

Same happened with me. I ended up wasting almost 2 hours. Thanks for saving my more time.
