### ISSUE TITLE
change focused on header createBottomTabNavigator / createStackNavigator 

### ISSUE THREAD

**Issue by devster19** [react-navigation/react-navigation#6118]
I use createBottomTabNavigator with createStackNavigator and use focused parameter to change effect on bottom button pressed  but I dont know how to remove focused effect at bottom button when i pressed button at header

**Comment by matthamil** [comment]
Hello! It looks like you didn't follow the issue template. Can you please open a new issue and follow the prompts provided in the template? Thank you!
