### ISSUE TITLE
Problems with goBack and didFocus/didBlur

### ISSUE THREAD

**Issue by nicoceledon** [react-navigation/react-navigation#6123]
### Current Behavior
With a stackNavigator, i tried too change between screens using `navigate` and `goBack()` using a Button. When i change to the second screen through `navigate` it goes without problem and the seconds screends loads fine. When i try to go back it seems weird because it takes too long(more than 30 seconds) to actually go Back. 

When inspecting the didFocus/didBlur and willFocus/willBlur events, it seems that the first ones (did) takes too long. I think it might be related.

### Expected Behavior
I expect to happend inmediatly the change between the screens.

### How to reproduce
https://github.com/nicoceledon/react_navigation_test

run the example and press the buttons to flow between the screens.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 0.3.11
| react-native     | 0.60.3
| node             | 0.10.51
| npm or yarn      | yarn

**Comment by nicoceledon** [comment]
I just notice that it has to do with debugging. When i have "remote debugging" enabled, it has this behavior. I'll check if there is some other issue related to this.

**Comment by satya164** [comment]
The behaviour with remote debugging might be buggy with interactions/gestures in React Native. This is unrelated to React Navigation.
