### ISSUE TITLE
didBlur、didFocus event not triggered when app turn into background and come foreground

### ISSUE THREAD

**Issue by KingAmo** [react-navigation/react-navigation#6125]
### Current Behavior

- What code are you running and what is happening?
`didBlur`、`didFocus`  event not triggered when app turn into background and then come foreground

### Expected Behavior

trigger `didBlur` event when app turn into background, trigger `didFocus` event when app turn into foreground,

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.7.1
| react-native     | 0.59.10

**Comment by matthamil** [comment]
You can use https://facebook.github.io/react-native/docs/appstate for this.
