### ISSUE TITLE
Unable to add custom header with semi-opaque background

### ISSUE THREAD

**Issue by louy** [react-navigation/react-navigation#6130]
Not 100% whether this is a bug or by design, but in short, using a custom semi-transparent header (e.g. VibrancyView from RNBlur) with a scrollview in the screen doesn't work as I'd expect to work, and I can't seem to be able to achieve the desired effect I'm looking for (which is very common in iOS apps 

### Current Behavior

- What code are you running and what is happening?
[Here's a snack.](https://snack.expo.io/@louay/react-navigation-w-blur-header)

```jsx
const Header = () => <SafeAreaView style={{backgroundColor: '#00000033'>
  <View style={{height: 40}} />
</SafeAreaView>

const Screen = () => <ScrollView
  automaticallyAdjustContentInsets={true}
  contentInsetAdjustmentBehavior="always"
  style={{flex: 1, backgroundColor: "#F00"}}
/>

const App = createAppContainer(createStackNavigator({
  Screen,
}, { headerMode: 'screen' }))
```

When I run this code, I see an semi-opaque header with white background (or the previous screen) behind it, and the scroll view starts where the header ends

### Expected Behavior

- What do you expect should be happening?
The scroll view goes under the header, so I'm able to see the scrollview background colour through the semi-opaque header

I also expect the `contentInsetAdjustmentBehavior` to take care of setting `contentInset` for me

### How to reproduce

Check the snack or example code above

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.11.1
| react-native     | 0.60.4
| node             | N/A
| npm or yarn      | N/A

**Comment by louy** [comment]
Sorry I meant to say semi-opaque

**Comment by matthamil** [comment]
This is expected behavior. The default Header doesn't overlay the screen like an absolute positioned element. You can create a custom header component as a workaround.
