### ISSUE TITLE
FlatList does not maintain scroll position

### ISSUE THREAD

**Issue by hotdev405** [react-navigation/react-navigation#6132]
Hi,
I have a StackNavigator with two screens A and B
screen A has a FlatList with around 1000 items which are loaded based on scrolling of the user with onEndReached method,
Now when user clicks on any item in the flatlist, he goes to screen B which detail screen of that clicked item.
Now if user goes back to screen A, then the flat list again starts showing from first item so the scroll position is not maintained.

How can we maintain the scroll position when going back in this case?

**Comment by matthamil** [comment]
Hello! It looks like you didn't follow the issue template. Can you reopen a new issue answering the prompts provided when you author a new issue? Thank you!

**Comment by AbdelkhalekESI** [comment]
same issue, any possible fix for that?

**Comment by DISKONEKTeD** [comment]
This also happens to me but only on Samsung devices, kinda weird

**Comment by DISKONEKTeD** [comment]
what fixed this for me was removing the use of Modal component, somehow it was affecting it

**Comment by sreuter** [comment]
@zeabdelkhalek @hotdev405 See https://github.com/react-navigation/react-navigation/issues/9733#issuecomment-1047712550 for a possible answer to your issue.
