### ISSUE TITLE
I want to navigate to another screen in Action Creator through react navigation but its not working can any body help

### ISSUE THREAD

**Issue by Hassam34** [react-navigation/react-navigation#6133]
export const employeeCreate=({name,phone,shift})=>{
      return(dispatch)=>{
            const{currentUser} =firebase.auth();
            firebase.database().ref(`users/${currentUser.uid}/employees`)
            .push({name,phone,shift})
            .then(()=>{
                  dispatch({
                        type:EMPLOYEE_CREATE
                  })
                  this.props.navigation.navigate('EmployeLists')
            });}
}

**Comment by vonovak** [comment]
hi there! this issue tracker is reserved for bugs only. your post seems to be a usage question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help. thanks!
