### ISSUE TITLE
StackNavigator in Expo Web doesn't hide previous pages

### ISSUE THREAD

**Issue by louislatreille** [react-navigation/react-navigation#6135]
I have an issue with the StackNavigator where the previously visited pages are still taking space on the currently visible page. The content of the previous page is not visible, but all the space is still taken. The currently visible page appears to be correctly constructed, and is visible. The issue only happen on **Expo/React-Native web**. Everything is working as expected on mobile.

### Current Behavior

- What code are you running and what is happening?

I found the issue on one of my personal projects, but was able to reproduce it on the NavigationPlayground Stack Example. All I had to do was to upgrade the expo version to SDK 33 and compile the web platform. After navigating to any page in the Stack Example, the Home page is hidden (0 opacity), but still takes all its space.

- Include a screenshot if it makes sense.

After navigating to a 2nd page in the Stack Example. We can see the big blank space taken by the previous page elements.
![2ndPage_0opa](https://user-images.githubusercontent.com/8052355/62010337-87bae180-b137-11e9-8ea1-a6d2653aaed0.png)

Same thing, but I changed the opacity to 1 to show that's it's really the elements from the previous page.
![2ndPage_1opa](https://user-images.githubusercontent.com/8052355/62010348-b6d15300-b137-11e9-9342-38f837f77d69.png)

### Expected Behavior

- What do you expect should be happening?

The elements from the previous page should be hidden, and take 0 space from the currently visible page.

### How to reproduce

All I had to do was clone the react-navigation repo, and update the NavigationPlayground project to expo SDK 33, and add the necessary dependencies to run a web project. 

Here is the diff:
![package json](https://user-images.githubusercontent.com/8052355/62010420-7e7e4480-b138-11e9-8d0d-ad5e3495a1c1.png)
![app json](https://user-images.githubusercontent.com/8052355/62010421-80480800-b138-11e9-9f58-bf86b2de6689.png)

After that, running `yarn install` to download everything, and then `expo start -w` to start the WebApp. In the Stack Example, any navigation will cause the issue.

**Comment by satya164** [comment]
cc @EvanBacon

**Comment by johanhenriksson** [comment]
We're also having this problem. Manually finding the view in the DOM and changing the `opacity: 0` property to something like `display: none` gives the expected result.

**Comment by coffenbacher** [comment]
I'm also having this issue, did anyone figure out a workaround for now?

**Comment by louislatreille** [comment]
Closing as this is fixed by using the `headerMode: 'screen'` configuration, like mentioned in #5984.

```
const MainFlow = createStackNavigator({
  A: {
    screen: AScreen
  },
  B: {
    screen: BScreen
  },
  ...
},
{
  headerMode: 'screen'
});
```
