### ISSUE TITLE
How to use restActions twice?

### ISSUE THREAD

**Issue by alirezadarvishi** [react-navigation/react-navigation#6136]
I need to twice rest action for go to my cart screen.

---Home
------TabsShow
---------Men
-------------Product
---------Women
---Cart

I want to go to cart screen when I'm in product screen. So I need to two restActions. How Can I do that?

**Comment by satya164** [comment]
hi there! this issue tracker is reserved for bugs only. your post seems to be a usage question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help. thanks!
