### ISSUE TITLE
Error Flatlist scrolling

### ISSUE THREAD

**Issue by JoynerPerez1987** [react-navigation/react-navigation#6138]
## The issue tracker is reserved for bug reports only.

If you have a question, feature request, or an idea for improving the library or its related tools, please try one of the following resources:

- [Read the documentation](https://reactnavigation.org/)
- [Post an issue to the website repository if you'd like to see a documentation change](http://github.com/react-navigation/website)
- [Post a feature request to Canny](https://react-navigation.canny.io/feature-requests)
- [Write a RFC if you have ideas for how to implement a feature request](https://github.com/react-navigation/rfcs)
- [Get help on Discord chat (#react-navigation on Reactiflux)](https://discord.gg/4xEK3nD) or [on StackOverflow](https://stackoverflow.com/questions/tagged/react-navigation)
- Search for your issue - it may have already been answered or even fixed in the development branch. However, if you find that an old, closed issue still persists in the latest version, you should open a new issue.

Bugs with react-navigation must be reproducible *without any external libraries that operate on it*. This means that if you are attempting to use Redux or MobX with it and you think you have found a bug, you must be able to reproduce it without Redux or MobX in this report. Redux related issues belong in [react-navigation-redux-helpers](https://github.com/react-navigation/react-navigation-redux-helpers), and we do not have any first-class integration with MobX at the moment.

---

### Current Behavior

- I have a horizontal screen with a FlatList inside but after updating in development mode it looks correct when creating the apk it is not seen correctly, as I show in the images.
My code is verey simple, is Expo SDK 33.

`import React, { Component } from 'react';
import { connect } from 'react-redux';
import {
  AsyncStorage, Image, View, FlatList, StyleSheet, Text, TouchableOpacity, Platform,
} from 'react-native';
import { ScreenOrientation } from 'expo';
import {
  actionLoading, actionGetSaldos, actionVerSaldos,
} from '../../Store/ACCIONES';
import Loading from '../Loading';
import Columnas from '../Tabla/Columnas';
import FilasSaldos from '../Tabla/FilasSaldos';

class Saldo extends Component {
  static navigationOptions = ({ navigation }) => ({
    headerRight: (
      <TouchableOpacity
        style={{
          width: 220, borderRadius: 15, backgroundColor: '#FF6A00', alignSelf: 'center',
        }}
        onPress={
            navigation.getParam('navegarEnviarInforme')
          }
      >
        <View style={{
          flex: 0,
          flexDirection: 'row',
          justifyContent: 'space-between',
          alignItems: 'center',
          paddingHorizontal: 16,
        }}
        >
          <Text style={{
            fontSize: 18, color: 'white', padding: 8, textAlign: 'center',
          }}
          >
  ENVIAR INFORME
          </Text>

          <Image
            style={{ width: 34, height: 24 }}
            source={require('../../assets/enviar-informe.png')}
          />

        </View>
      </TouchableOpacity>
    ),
  });

  async componentWillMount() {
    await ScreenOrientation.lockAsync(ScreenOrientation.OrientationLock.LANDSCAPE);
  }

  componentDidMount() {
    this.props.navigation.setParams({ navegarEnviarInforme: this.enviarInforme });
    AsyncStorage.getItem('@Unide:JWT')
      .then((value) => {
        this.props.dispatchLoading(true);
        this.props.dispatchGetSaldos(this.props.tienda, value);
      });
  }

  async componentWillUnmount() {
    this.props.dispatchLimpiarInformes([], [], []);
    if (Platform.OS === 'android') {
      await ScreenOrientation.lockAsync(ScreenOrientation.OrientationLock.PORTRAIT);
    } else {
      await ScreenOrientation.lockAsync(ScreenOrientation.OrientationLock.PORTRAIT_UP);
    }
  }

  enviarInforme = () => {
    this.props.navigation.navigate('EnviarInforme', {
      datos: this.props.informes.datos,
      titulo_datos: 'SALDO',
      parametros_busqueda: `Saldos para la tienda ${this.props.tienda.nombre}`,
    });
  }

  render() {
    return (
      <View style={styles.container}>

        <Loading
          loading={this.props.loading}
        />

        <Columnas
          valores={this.props.informes.columnas === undefined ? [] : this.props.informes.columnas}
        />
        <View
          style={styles.containerIosLista}
        >
          <FlatList
            nestedScrollEnabled
            data={this.props.informes.filas}
            keyExtractor={(item, index) => index.toString()}
            renderItem={({ item }) => (
              <FilasSaldos
                valores={item}
              />
            )
}
          />
        </View>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'flex-start',
    backgroundColor: 'white',
  },
  textoTitulo: {
    fontSize: 14,
    color: '#004964',
  },
  textoOtros: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#FF6A00',
  },
  containerAndroidLista: {
    backgroundColor: 'white',
    height: 200,
  },
  containerIosLista: {
    flex: 1,
    backgroundColor: 'white',
  },
  head: {
    flex: 1, flexDirection: 'row', height: 40, backgroundColor: '#e0e0e0',
  },
  row: { flexDirection: 'row' },
  textHead: {
    color: '#004964', textAlign: 'center', padding: 2, fontSize: 12,
  },
  textRow: { color: '#9c9b9b', textAlign: 'center', padding: 2 },
  textRowVerde: {
    color: '#61A94D', textAlign: 'center', padding: 2, fontWeight: 'bold',
  },
  textRowRojo: {
    color: '#D13C36', textAlign: 'center', padding: 2, fontWeight: 'bold',
  },
  dataWrapper: { flex: 0, marginTop: -1 },
});

const mapStateToProps = state => ({
  loading: state.reducerLoading,
  tienda: state.reducerEditarTienda,
  informes: state.reducerVerSaldos,
});

const mapDispatchToProps = dispatch => ({
  dispatchLoading: (valor) => {
    dispatch(actionLoading(valor));
  },
  dispatchGetSaldos: (tienda, jwt) => {
    dispatch(actionGetSaldos(tienda, jwt));
  },
  dispatchLimpiarInformes: (datosUsuario, columnas, filas) => {
    dispatch(actionVerSaldos(datosUsuario, columnas, filas));
  },
});

export default connect(mapStateToProps, mapDispatchToProps)(Saldo);`

![photo_2019-07-14 10 46 22 p  m](https://user-images.githubusercontent.com/10671527/62103312-b3d28180-b261-11e9-8fb2-acc48840499d.jpeg)

### Expected Behavior

- In dev mode is correct but with compile apk not.
-
![Screenshot_1563162157](https://user-images.githubusercontent.com/10671527/62103454-22afda80-b262-11e9-8522-d46a77c929b4.png)

### How to reproduce

- You must provide a way to reproduce the problem. If you are having an issue with your machine or build tools, the issue belongs on another repository as that is outside of the scope of React Navigation.
- Either re-create the bug on [Snack](https://snack.expo.io) or link to a GitHub repository with code that reproduces the bug.
- Explain how to run the example app and any steps that we need to take to reproduce the issue from the example app.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.11.1
| react-native     |0.59.8
| node             |10.16.0
| npm or yarn      |yarn

**Comment by matthamil** [comment]
Hello! Can you create a reproducible example in a public GitHub repo or as a [Snack](https://snack.expo.io)? Code snippets are great, but a cloneable repo that has only the parts necessary to reproduce your issue is even better. Thanks!

**Comment by JoynerPerez1987** [comment]
I can't create it in snack. But what I am doing is very simple. Simply by navigating from a vertical screen to a horizontal screen that only has a View component, bottomNavigation it disappears. I do not know if I explained well. Look at the images attached above.
And this problem only happens to me when creating the apk with Expo, in development mode everything is going well

**Comment by matthamil** [comment]
Can you create it as a public repo?

**Comment by JoynerPerez1987** [comment]
No, it is a private project.

**Comment by matthamil** [comment]
If there is no way you can create a minimal, reproducible example of the problem you are experiencing, then we don't have any way to help you.

**Comment by vonovak** [comment]
hello, without a minimal repro, we cannot help :(
