### ISSUE TITLE
Deep linking in iOS with Universal Links

### ISSUE THREAD

**Issue by giangyger** [react-navigation/react-navigation#6139]
## Universal Linking only works if app is closed in iOS

Hello, I added Deep linking to my app and everything works perfectly except that when the app on iOS is running in the background and I open a Universal Link I am not forwarded to the path I set, instead I am stuck on the root screen and nothing happens.
I followed your guide [https://reactnavigation.org/docs/en/deep-linking.html](url) and added the prefix to my root navigation component like this
`<Navigation uriPrefix={prefix} />`
and the path parameter to my screen like this.
`MyScreen: { screen: Import, path: "import/:key" }`

The weird part is that this works on Android regardless of whether the app is running in the background or not, and on iOS it works only when the app is closed.

Please let me know if I did something wrong or if this is a bug or if there's extra configuration I have to do.
Thanks!

**Comment by orcunorcun** [comment]
How did you solve that problem? @giangyger

**Comment by acollazomayer** [comment]
@giangyger @orcunorcun I have the same problem! How did you solve it.

**Comment by papucho** [comment]
@giangyger Any updates on this?

**Comment by giangyger** [comment]
I think I had to change some of the ios configuration, it _**wasn't**_ a react-navigation issue. This was quite some time ago and I think I didn't really understand it at the time. Sorry about that.
