### ISSUE TITLE
Can't use this. Props. Navigation. State. key  The key to obtain the key

### ISSUE THREAD

**Issue by zjchxl** [react-navigation/react-navigation#6140]
I don't know why, I suddenly can't get the page key, now I can only get the page name.
Use this. Props. Navigation. State. The key to get the key

The use of the I
`const BottomTabNavigator = createBottomTabNavigator({
    Home: {
        screen: Home,
        navigationOptions: () => ({
            header: null, 
            headerBackTitle: null, 
            gesturesEnabled: true 
        })
    },
    Work: {
        screen: Work,
        navigationOptions: () => ({
            header: null, 
            headerBackTitle: null,
            gesturesEnabled: true 
        })
    },
}, {//BottomTavNavtigtorConfig
        defaultNavigationOptions: ({ navigation }) => ({
            tabBarIcon: ({ focused, tintColor }) => 
                getTabBarIcon(navigation, focused, tintColor),
            tabBarLabel: navigation.state.routeName === 'Home' ? 'Home' : 'Work', 
        }),
        
    });

const AppDrawer = createDrawerNavigator({
    Set: {
        screen: BottomTabNavigator,
    },
}, {
        order: ['Set'],
        initialRouteName: 'Set',
        drawerLockMode: 'unlocked',
       
        contentComponent: props => {
            return <DrawerView {...props} />;
        },
        
        contentOptions: {
         
            activeTintColor: 'white', 
            activeBackgroundColor: 'blue',
            inactiveTintColor: 'black', 
            inactiveBackgroundColor: 'red', 

            
        }

    })

const PageView = createStackNavigator({
    AppDrawer: {
        screen: AppDrawer,
        navigationOptions: () => ({
            header: null, 
            headerBackTitle: null, 
            gesturesEnabled: true  
        })
    },
    
}, {
        initialRouteName: 'AppDrawer',
        initialRouteParams: { 
            key: 'aaaaa',
            key1: 'bbbbb'
        },
    });

const RootStack = createStackNavigator({
    Login: {
        screen: Login,
        navigationOptions: () => ({
            header: null,
            headerBackTitle: null
        }),
    },

    PageView: {
        screen: PageView,
        navigationOptions: () => ({
            header: null,
            headerBackTitle: null
        }),
    }

}, {
        initialRouteName: 'Login',

    });

const AppNavigator = createAppContainer(RootStack);`

When I use this method

`let keys =  this.props.navigation.state.key;
        let routeName =  this.props.navigation.state.routeName;

        console.log('this.props.navigation.state.key = '+keys+' this.props.navigation.state.routeName = '+routeName);
`
Get the log
`this.props.navigation.state.key = Home this.props.navigation.state.routeName = Home`

**Comment by matthamil** [comment]
Hello! Can you create a reproducible example in a public GitHub repo or as a [Snack](https://snack.expo.io)? Code snippets are great, but a cloneable repo that has only the parts necessary to reproduce your issue is even better. Thanks!

**Comment by zjchxl** [comment]
Sure, I re-created a project and re-created the problem. I will give you the project link, thank you!
[https://github.com/zjchxl/TemporaryDemo](url)

**Comment by satya164** [comment]
@zjchxl The repro provided has a lot of code unrelated to navigation. Please post a minimal runnable repro if you think this is still an issue.
