### ISSUE TITLE
Does not quite navigate when on debug mode on iOS

### ISSUE THREAD

**Issue by kusalshrestha** [react-navigation/react-navigation#6141]
I'm having trouble while navigating to a new screen on debug mode specifically on iOS. In release mode it works almost fine like 99.9%.

### Current Behavior

On debug mode, the navigation acts very weird. Like the drawer does not open/close on clicking the button but takes the gesture (swipe gesture). On List view, every cell returns touch feedback but does not navigate to any screen. When the same code is run on release mode, it works almost perfectly except I recently got the same problem on my iphone SE model.

### Expected Behavior

Sorry I can neither share my code nor screenshots or a video.

### How to reproduce

This usually happens when you run in debug mode.

### Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.11.0
| react-native     | 0.60.0
| node             | 10.15.3
| npm or yarn      | 1.15.2

**Comment by matthamil** [comment]
> Sorry I can neither share my code nor screenshots or a video.

Can you create a minimal reproduction of the problem you are experiencing? We can't help you unless we can see what's happening. You don't have to publish your entire code base (and please, don't :) ), but just enough to recreate the issue. Thanks

**Comment by kusalshrestha** [comment]
Thanks @matthamil . It didn't occur in the new project. May be something blunder going with my codebase.
