### ISSUE TITLE
Getting warning: “componentWillUpdate is deprecated and will be removed in the next major version” when using the react navigation's createDrawerNavigator, it work fine with createStackNavigator and createBottomTabNavigator.

### ISSUE THREAD

**Issue by vjazz** [react-navigation/react-navigation#6143]
## The issue tracker is reserved for bug reports only.

I am facing a  issue while developing a react native app. I am using navigation for which i added "react-navigation" library.

Get the below warning and it seems to be like with react native 0.60 +:

componentWillUpdate is deprecated and will be removed in the next major version.

const App = () => {
  return (
    <AppContainer />
  );
};

const AppTabNavigator = createBottomTabNavigator(
  {
    FindPlace: {
      screen: FindPlace,
    },
    SharePlace: {
      screen: SharePlace,
    },
  },
  {
    defaultNavigationOptions: ({ navigation }) => ({
      tabBarIcon: ({ focused, horizontal, tintColor }) => {
        const { routeName } = navigation.state;
        let IconComponent = Icon;
        let iconName;
        if (routeName === 'FindPlace') {
          iconName = `ios-information-circle${focused ? '' : '-outline'}`;
        } else if (routeName === 'SharePlace') {
          iconName = `ios-options`;
        }

        return <IconComponent name={iconName} size={25} color={tintColor} />;
      },
    }),
    tabBarOptions: {
      activeTintColor: 'tomato',
      inactiveTintColor: 'gray',
      activeBackgroundColor: 'yellow',
    },
    })

const AppDrawerNavigation = createDrawerNavigator({
  FindPlace: {
    screen: AppTabNavigator
![Screenshot_1564742776](https://user-images.githubusercontent.com/25026100/62365180-09987980-b541-11e9-81f1-807e968194fb.png)
![Screenshot_1564742776](https://user-images.githubusercontent.com/25026100/62365194-1c12b300-b541-11e9-92ed-cc7db087438e.png)

,
  }
},
  {
    drawerPosition: 'right',
  })
const AppNavigator = createStackNavigator({
  Home: {
    screen: AuthScreen,
    navigationOptions: ({ navigation }) => {
      return {
        header: null
      }
    }
  },
  FindPlace: {
    screen: AppDrawerNavigation,
    navigationOptions: ({ navigation }) => {
      return {
        headerTitle: 'Profile',
        headerRight: (<Icon style={{ paddingRight: 10 }}
          onPress={() => navigation.openDrawer()}
          name="md-menu" size={30} />),
      }
    }
  },
},
 );

### Your Environment

"react": "16.8.6",
"react-native": "0.60.3",
"react-native-gesture-handler": "^1.3.0",
"react-native-vector-icons": "^6.6.0",
 "react-navigation": "^3.11.1",

**Comment by vkts** [comment]
I'm getting a "componentWillUpdate is deprecated" warning along with the suggestion to update DrawerLayout when using `createDrawerNavigator()`.
software 	version
react-navigation 	3.11.1
react-native 	0.60.4
node 	10.16.0
npm or yarn 	npm

I tried to update the drawer component with `npm install react-navigation-drawer` which installed v2.0.0 however react-native-navigation@3.11.1 seems to supply its own dependency react-navigation-drawer@1.2.1

Would forking react-navigation and replacing the dependency remove the warnings or just break more things?

**Comment by ielhag** [comment]
+1

**Comment by 2n2n** [comment]
having the same issue.. how to fix?

**Comment by vjazz** [comment]
still looking for solution and don't want to downgrade RN to lower version. I think solution right now is downgrade RN, but I did't check for this case.

**Comment by vonovak** [comment]
this comes from react-native-gesture-handler: see https://github.com/kmagiera/react-native-gesture-handler/issues/683

This is just a warning, you can safely ignore it, see https://facebook.github.io/react-native/docs/debugging#warnings
