### ISSUE TITLE
the navigation prop is missing for this navigator when nested navigator is not a direct child of parent navigator

### ISSUE THREAD

**Issue by michaelknoch** [react-navigation/react-navigation#6144]
### Current Behavior
we am running a react native project using react-navigation@2.x. I upgraded the project and initialized an app container. When running the project i receive `The navigation prop is missing for this navigator. In react-navigation 3 you must set up your app container directly..` for all nested StackNavigators. At first i thought maybe nested Navigators are not supported anymore, but the issue turned out to be more complex. I have a Navigator that is not directly referenced in the parent Navigator, which means there is a simple wrapping component that renders some ui on top of the navigation stack.

It's hard to explain, but i think it's easy to understand when opening the demo snack
https://snack.expo.io/SkDXQ2bQS

So what happens is that the nested navigator is lacking knowledge of the container. Even passing the navigation prop manually or wrapping with `withNavigation` breaks, but with a different error `Routes is undefined..`

Any ideas how to fix or workaround this issue? Thanks in advance!
 

### Expected Behavior
It (hopefully) should be possible to render navigators anywhere in the app, not only as direct child of parent navigators. If not, it would be great to workaround because this worked in version 2.

### How to reproduce
https://snack.expo.io/SkDXQ2bQS

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.11.1 (latest)
| react-native   |  0.59
| node             | 10
| npm or yarn      | both

**Comment by vonovak** [comment]
hi! I have edited your snack and made it work: https://snack.expo.io/@vonovak/createnavigator-with-nested-stacknavigator

the thing is that navigator uses some static fields and when you wrapped the navigator, the static information was not copied over to the new components. see also https://reactnavigation.org/docs/en/custom-navigators.html

hope this helps

**Comment by truongtv** [comment]
Hi @michaelknoch 
Here is another solution: https://snack.expo.io/@tranvinhtruong/createnavigator-with-nested-stacknavigator
