### ISSUE TITLE
Navigating back from multiple screen Error 

### ISSUE THREAD

**Issue by akash4320** [react-navigation/react-navigation#6145]
Suppose i have four screens A -> B -> C -> D -> E , i want navigate back from E to C i use different routes itself for this purpose like ,
 firstRoute => A -> B -> C is one route ,
secondRoute => D-> E is one  more route. 
i first switch the route to "firstRoute" then i take upon stack "C" 
I do this as a reason because ,
**i want to come to C from E using IOS back slide, after that when i use IOS back slide again, i should go back to B and followed by A rather than going back to E itself and making Infinite loop.**
**I am unable to do this task Can someone help me out in writing a example stack navigation and routes how to differentiate them.**

**Comment by brentvatne** [comment]
hi there! this is a question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.

**Comment by akash4320** [comment]
You must answer to my problems in this package right?? This is related to the problem i got in your package. Why i should post this in stackoverflow or discord
