### ISSUE TITLE
Tabnavigator initialRouteName not working with react-native 0.59.5 on iOS

### ISSUE THREAD

**Issue by manuTro** [react-navigation/react-navigation#6148]
Hi, I'm using the `1.0.0-beta.11` version of this library and everything worked fine until I upgraded my react-native version (from `0.55.4` to `0.59.5`). 
Now `initialRouteName` TabNavigator property is not working anymore just on iOS. 
Is it normal? I would like to avoid to upgrade this library just for this.. 

Thx

**Comment by brentvatne** [comment]
hi there! this is a question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.

**Comment by manuTro** [comment]
@brentvatne I upgraded to `react-navigation@2.0.0-rc.1` and by using `createMaterialTopTabBarNavigator` `initialRouteName` sets right just the tabNavigator label but not the screen. As you can see on the image attached the navigator says that it's on the fourth screen but the app shows the third screen 

![Simulator Screen Shot - iPhone SE - 2019-08-23 at 15 29 13](https://user-images.githubusercontent.com/25326470/63596327-48a77100-c5bb-11e9-802b-b80f47841238.png)

**Comment by manuTro** [comment]
Instead if I use `createMaterialBottomTabNavigator` it renders the right screen but the swipe animation doesn't work. 
![Simulator Screen Shot - iPhone SE - 2019-08-23 at 15 48 11](https://user-images.githubusercontent.com/25326470/63597392-a341cc80-c5bd-11e9-977e-a29abd3d586b.png)
