### ISSUE TITLE
Header not showing with createBottomTabNavigator

### ISSUE THREAD

**Issue by harrygill123** [react-navigation/react-navigation#6149]
#6103 # Current Behavior

```
import React, {Component} from 'react';
import { View, Text } from 'react-native';
import {  createAppContainer, createBottomTabNavigator } from 'react-navigation';

class MusicScreen extends Component {
  static navigationOptions = {
    title: 'Musiiic',
  };
  render() {
    return (
        <View >
            <Text>Music Screen</Text>
        </View>
    );
  }
}

class MoviesScreen extends Component {
  static navigationOptions = {
    headerTitle: 'Movies',
  };
  render() {
    return (
    <View>
        <Text>Movies Screen</Text>
    </View>
    );
  }
}

const MainNavigation = createBottomTabNavigator({
    Music : {
      screen: MusicScreen,
      navigationOptions: ({navigation}) => ({
        title: 'Music',
        headerTitle: <Text>MUSIICCCC</Text>,
      })
    },
    Movies : {
      screen: MoviesScreen,
      navigationOptions: {
        title: 'Movies',
      },
    },
  },
  {
    headerMode: 'screen',
    headerVisible: true,
    navigationOptions: {
      headerMode: 'screen',
      headerVisible: true,
    },
  }
);

export default createAppContainer(MainNavigation);
```

### Expected Behavior

A header should appear on top of the screen, along with the bottom tab bar.

### How to reproduce

Just create a new native react project and add the above code to App.js

```
react-native init someAndroidApp
cd someAndroidApp
npm install --save react-navigation
npm i --save react-native-gesture-handler
react-native link react-native-gesture-handler
npm i jetifier
npx jetify
react-native run
```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.11.1
| react-native     | 0.60.4
| node             | v10.16.0
| npm       | 6.9.0
![Screenshot_1565007008](https://user-images.githubusercontent.com/53768753/62464222-9fced880-b7a9-11e9-9d30-1ee2feb72a5a.png)

**Comment by vonovak** [comment]
hi! Thanks for reporting. This is the expected behavior. If you want to show header, you need to wrap your screens in a stack navigator. see https://reactnavigation.org/docs/en/tab-based-navigation.html#a-stack-navigator-for-each-tab

**Comment by tim92109** [comment]
Basically you lose the ability to have authentication flow.  Someone HAS to come up with a better solution for navigation in React.

**Comment by guptanisha** [comment]
> hi! Thanks for reporting. This is the expected behavior. If you want to show header, you need to wrap your screens in a stack navigator. see https://reactnavigation.org/docs/en/tab-based-navigation.html#a-stack-navigator-for-each-tab

@vonovak I am trying to render the header of 'View' using. Pls, help me out where I m doing wrong.

AppointmentTabs.navigationOptions = ({ navigation }) => {
   const varr = navigation.state.routeName.navigationOptions;

 return {
      varr,
  };
};

**Comment by 2016CS112** [comment]
navigationOpions can we use in bottomtabnavigator Screen.?
@vonovak
