### ISSUE TITLE
Dependency react-native-safe-area-view uses deprecated global.Expo.Constants

### ISSUE THREAD

**Issue by brettdh** [react-navigation/react-navigation#6150]
React Navigation depends on a library ([react-native-safe-area-view](https://github.com/react-native-community/react-native-safe-area-view)) with a [known issue](https://github.com/react-native-community/react-native-safe-area-view/issues/78) related to Expo SDK 33 and 34. When running on Android, this issue results in a deprecation warning on SDK 33, and will result in either a crash or a silently incorrect `statusBarHeight` calculation in SDK 34.

The upstream issue isn't fixed yet, but when it is, react-navigation will need to use the version with the fix.

### Current Behavior

Warning log message (Expo SDK 33):

```
The following APIs have moved to separate packages and importing them from the "expo" package is deprecated: Constants.

1. Add correct versions of these packages to your project using:

   expo install expo-constants

   If "install" is not recognized as an expo command, update your expo-cli installation.

2. Change your imports so they use specific packages instead of the "expo" package:

 - import { Constants } from 'expo' -> import Constants from 'expo-constants'
```

### Expected Behavior

No warning, no crash, no incorrect height calculation.

### How to reproduce

Demo forthcoming. In the meantime: any navigator screen that uses `SafeAreaView` should reproduce the issue on Android, using Expo SDK 33.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.11.0
| react-native     | 0.59.8
| node             | 8.11.4
| yarn      | 1.13.0

**Comment by brentvatne** [comment]
update to the latest expo sdk 33 patch version or sdk 34 and this will not be a problem. we have resumed re-exporting the constants on the expo global (https://github.com/expo/expo/blob/ee351e7516f7042486ca558b5ac5b7e071ca1281/packages/expo/src/globals.ts#L19-L24) until metro supports optional imports

**Comment by brettdh** [comment]
@brentvatne Thanks; from the file you linked, I found https://github.com/expo/expo/pull/4470, which helped me understand the situation better.

However, I'm not quite connecting the dots here with respect to "optional imports." What is that feature, and what would that change for Expo or the modues that haven't yet moved to named exports?

**Comment by brentvatne** [comment]
https://github.com/react-native-community/discussions-and-proposals/issues/120

**Comment by wcandillon** [comment]
@brettdh I'm affected by this issue after upgrading a project to expo 35. How did you solve it on your side?
