### ISSUE TITLE
Navigator created with createNavigator does not respect defaultNavigationOptions

### ISSUE THREAD

**Issue by joebernard** [react-navigation/react-navigation#6151]
### Current Behavior

- What code are you running and what is happening?
https://snack.expo.io/@joebernard/custom-header-in-custom-navigator

When using a custom navigator created with `createNavigator`, it does not seem possible to update the header with a `defaultNavigationOptions`. I've put together the demo above to illustrate. Switch between using `createCustomNavigator` and `createStackNavigator`. 

I am passing in `defaultNavigationOptions` in the `navigationConfig` but it is ignored in the custom navigator.

### Expected Behavior

It should be possible to manipulate the header of a cusom navigator using `defaultNavigationOptions`.

### How to reproduce
Snack provided.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.11.1
| react-native     | 0.59.10
| node             | v10.15.3
| yarn      | 1.17.3

**Comment by joebernard** [comment]
Is there anything else I can provide to help debug this?

**Comment by AndreiCalazans** [comment]
You are not implementing any logic for it in your View layer. The Header stuff is implemented in the View layer. Take a look at the code implementation for the Navigation views: https://reactnavigation.org/docs/en/navigation-views.html

**Comment by joebernard** [comment]
I don't see any code referencing the header. Here is the Switch view:
https://github.com/react-navigation/core/blob/master/src/views/SwitchView/SwitchView.js

**Comment by joebernard** [comment]
Here is my working custom navigator. I built it to be keyboard avoiding.

```javascript
import * as React from "react";
import { KeyboardAvoidingView, StyleSheet, Platform } from "react-native";
import { StackRouter, createNavigator } from "react-navigation";
import { StackView } from "react-navigation-stack";

const createKeyboardAvoidingStackNavigator = (
  routeConfigMap,
  stackConfig = {}
) => {
  const router = StackRouter(routeConfigMap, stackConfig);

  if (stackConfig.disableKeyboardHandling || Platform.OS === "web") {
    return createNavigator(StackView, router, stackConfig);
  }

  return createNavigator(
    navigatorProps => (
      <KeyboardAvoidingView
        style={styles.keyboardAvoidingView}
        behavior="padding"
      >
        <StackView {...this.props} {...navigatorProps} />
      </KeyboardAvoidingView>
    ),
    router,
    stackConfig
  );
};

export default createKeyboardAvoidingStackNavigator;

const styles = StyleSheet.create({
  keyboardAvoidingView: {
    flex: 1
  }
});
```
