### ISSUE TITLE
Missing Flow types

### ISSUE THREAD

**Issue by levibuzolic** [react-navigation/react-navigation#6153]
After creating #6152 I decided to go check if there's other publicly exported interfaces in the `react-navigation` package that were missing from the Flow type definition, turns out there's quite a lot.

I'm happy to go through and fix all of these, and will work on them over the coming week or two, however I'm posting it here to keep track of what's missing and should anybody want to chip in as good first issues. Many of them are quite easy to tackle.

 - [x] `ScrollView` - #6152
 - [x] `NavigationContext` - #6152
 - [x] `FlatList` - #6170
 - [x] `SectionList` - #6170
 - [x] `ResourceSavingSceneView` - #6170
 - [x] `withOrientation` - #6170
 - [ ] `createKeyboardAwareNavigator`
 - [ ] `createNavigationAwareScrollable`
 - [ ] `NavigationProvider`
 - [ ] `NavigationConsumer`
 - [ ] `SwitchRouter`
 - [ ] `createConfigGetter`
 - [x] `getScreenForRouteName` - #6170
 - [ ] `validateRouteConfigMap`
 - [ ] `pathUtils`
 - [x] `SceneView` - #6170
 - [ ] `SwitchView`
 - [ ] `StackGestureContext`
 - [ ] `DrawerGestureContext`
 - [ ] `DrawerRouter`
 - [x] `StackView` - #6170
 - [x] `StackViewCard` - #6170
 - [ ] `StackViewTransitionConfigs`
 - [ ] `HeaderStyleInterpolator`
 - [ ] `DrawerSidebar`

**Comment by rumax** [comment]
Thees types are also missing?

- [ ] `NavigationAction`
- [ ] `NavigationScreenProp`
- [ ] `NavigationState`

**Comment by levibuzolic** [comment]
@rumax those types are already exported as far as I can tell.

* [`NavigationAction`](https://github.com/react-navigation/react-navigation/blob/master/flow/react-navigation.js#L213)
* [`NavigationScreenProp`](https://github.com/react-navigation/react-navigation/blob/master/flow/react-navigation.js#L588)
* [`NavigationState`](https://github.com/react-navigation/react-navigation/blob/master/flow/react-navigation.js#L244)

**Comment by thymikee** [comment]
cc @Ashoat who's working on upgrading the Flow typings for flow-typed: https://github.com/flow-typed/flow-typed/pull/3569. It would be good to consolidate the efforts and have a single source of truth

**Comment by Ashoat** [comment]
Not sure how I missed this issue!

https://github.com/flow-typed/flow-typed/pull/3569 adds a bunch of missing types, but not all of them. The only ones missing now are also missing on the TypeScript side.

I also put up #6327 yesterday, which removes the Flow libdef from this repo in favor of maintaining the `flow-typed` ones as canonical.
