### ISSUE TITLE
Unexpected token (33:11) in ResourceSavingSceneView.js

### ISSUE THREAD

**Issue by AbhishekNairOfficial** [react-navigation/react-navigation#6155]
I'm trying to use React-Navigation (v3.11.1) with react-native and react-native-web.
On native, it runs as expected, but when I try to run the same code on native-web, I get the following error:
./node_modules/@react-navigation/native/dist/ResourceSavingSceneView.js
SyntaxError: /path/to/folder/node_modules/@react-navigation/native/dist/ResourceSavingSceneView.js: Unexpected token (33:11)

Anyone else faced this issue?

**Comment by jkdc** [comment]
I've the same problem...

**Comment by brentvatne** [comment]
don't use `@react-navigation/native` on web, use `@react-navigation/web` instead

**Comment by AbhishekNairOfficial** [comment]
@brentvatne I used these two to create my navigation:

`import { createSwitchNavigator } from "@react-navigation/core";`
`import { createBrowserApp } from "@react-navigation/web";`

I still get the error 

> SyntaxError: /Users/abhisheknairofficial/Projects/NorthStar-2.0/packages/common/node_modules/@react-navigation/native/dist/ResourceSavingSceneView.js: Unexpected token (33:11)

Any replacement for createSwitchNavigator that i'm missing?

**Comment by lauvrenn** [comment]
I get the same error when I try to import `createStackNavigator` and `createAppContainer`. Any ideas?

**Comment by taersious** [comment]
We need a fix for this issue. Navigation was working.

**Comment by AbhishekNairOfficial** [comment]
Yes please. Any replacement for either CreateAwitchNavigator or CreateStackNavigator

**Comment by sinasadeghi83** [comment]
I have the same problem do you have any solutions?

**Comment by sinasadeghi83** [comment]
I found it! You should delete this line 
`import { createStackNavigator, createAppContainer } from 'react-navigation';`
and use `@react-navigation/web`

**Comment by roxxid** [comment]
You need to handle all the dependencies correctly. Just run the following command and it works,
 
npm i react-navigation react-navigation-stack react-native-gesture-handler react-native-screens
or
yarn add npm i react-navigation react-navigation-stack react-native-gesture-handler react-native-screens

**Comment by vitalyiegorov** [comment]
Followed the [docs](https://reactnavigation.org/docs/en/stack-navigator.html) provided by @roxxid, @sinasadeghi83 could you please describe your solution?

**Comment by vitalyiegorov** [comment]
I have managed to make it work: 

```
// @ts-ignore
import {createBrowserApp} from '@react-navigation/web';
// @ts-ignore
import { createSwitchNavigator } from "@react-navigation/core";
import {Main} from './main';
import {Second} from './second';

export const InitialStackNavigator = createBrowserApp(createSwitchNavigator({
    root: Main,
    second: Second,
}));
```

Unfortunately, only switchNavigator is working for now.

**Comment by dherault** [comment]
I think this issue should be reopened.

**Comment by lovetofail** [comment]
I'm using this as a seed project https://github.com/brunolemos/react-native-web-monorepo.
I had the same error. Adding "resolveApp("node_modules/@react-navigation"), " to "config-overrides.js" file fixes the issue for me.

```const fs = require("fs");
const path = require("path");
const webpack = require("webpack");

const appDirectory = fs.realpathSync(process.cwd());
const resolveApp = relativePath => path.resolve(appDirectory, relativePath);

// our packages that will now be included in the CRA build step
const appIncludes = [
  resolveApp("src"),
  resolveApp("../components/src"),

//YOUR PATH PROBABLY WILL BE LIKE THIS
  resolveApp("node_modules/@react-navigation"), 

//MY PATH IS THIS
  resolveApp("../../node_modules/@react-navigation"), 

  resolveApp("../../node_modules/react-native-gesture-handler"),
  resolveApp("../../node_modules/react-native-screens"),
  resolveApp("../../node_modules/react-native-swipe-list-view"),
  resolveApp("../../node_modules/react-navigation-drawer"),
  resolveApp("../../node_modules/react-native-reanimated"),
  resolveApp("../../node_modules/react-native-paper"),
  resolveApp("../../node_modules/react-native-vector-icons"),
  resolveApp("../../node_modules/react-native-web"),
];

const addWebpackAlias = alias => config => {
  if (!config.resolve) {
    config.resolve = {};
  }
  if (!config.resolve.alias) {
    config.resolve.alias = {};
  }
  Object.assign(config.resolve.alias, alias);
  return config;
};

//export const alias = (options?: any) => (config: any) => {
//  return addWebpackAlias(options || {})(config)
//}

module.exports = function override(config, env) {
  //addWebpackAlias({
  //      "react-native-firebase":"firebase"
  //    }),

  // allow importing from outside of src folder
  config.resolve.plugins = config.resolve.plugins.filter(
    plugin => plugin.constructor.name !== "ModuleScopePlugin",
  );
  config.module.rules[0].include = appIncludes;
  config.module.rules[1] = null;
  config.module.rules[2].oneOf[1].include = appIncludes;
  config.module.rules[2].oneOf[1].options.plugins = [
    require.resolve("babel-plugin-react-native-web"),
    require.resolve("@babel/plugin-proposal-optional-chaining")
//@babel/plugin-proposal-optional-chaining
  ].concat(config.module.rules[2].oneOf[1].options.plugins);
  config.module.rules = config.module.rules.filter(Boolean);
  config.plugins.push(
    new webpack.DefinePlugin({ __DEV__: env !== "production" }),
  );
  return config;
};
```

**Comment by possiblytyler** [comment]
This is another project that is an example of React Native App with reactJS and Navigation Stack Support https://github.com/possiblytyler/rnNavWebAppExample

**Comment by LaurelOlson** [comment]
I got this to work by adding the following rule to `webpack.config.js` (based on this [SO post]( https://stackoverflow.com/questions/54089116/cannot-integrate-react-native-web-with-react-navigation)):

```
{
        test: /\.(js|jsx)$/,
        include: [
          ...
          // add these two lines
          path.resolve('node_modules/@react-navigation'),
          path.resolve('node_modules/react-navigation'),
          ...
        ],
        loader: 'babel-loader',
        options: {
          plugins: [],
        },
      }
```

**Comment by vinothsoft-work** [comment]
/node_modules/@react-navigation/native/dist/ResourceSavingSceneView.js
SyntaxError: /home/vinoth/Documents/ReactJs/ReactMobile/toprankers/node_modules/@react-navigation/native/dist/ResourceSavingSceneView.js: Unexpected token (33:11)

  31 |     } = this.props;
  32 | 
> 33 |     return <View style={styles.container} collapsable={false} removeClippedSubviews={Platform.OS === 'android' ? removeClippedSubviews : !isFocused && removeClippedSubviews}>
     |            ^
  34 |         <View style={this._mustAlwaysBeVisible() || isFocused ? styles.innerAttached : styles.innerDetached}>
  35 |           {awake ? <SceneView {...rest} navigation={childNavigation} /> : null}
  36 |         </View> 


Me also facing the same issues any one can help me please...

**Comment by sinasadeghi83** [comment]
I think @lovetofail solution is better. I don't test it. but I use the same seed project.
@vitalyiegorov StackNavigator doesn't work in web.

**Comment by renanmav** [comment]
What solved for me was @lovetofail solution with this little tweak:
```js
config.module.rules[2].oneOf[1].options.sourceType = 'unambiguous';
```

**Comment by vikulin** [comment]
What release contains fix for the issue?
