### ISSUE TITLE
willFocus not trigger

### ISSUE THREAD

**Issue by sophister** [react-navigation/react-navigation#6156]
### Current Behavior

- What code are you running and what is happening?
I use both `navigation.addListener("willFocus")` and `<NavigationEvents onWillFocus={callback} />` to bind the `willFocus` event. 
But sometimes only one of these two callbacks is invoked, and sometimes both of them are invoked. 

I've tested it with `Android`, not sure about `iOS`.

### Expected Behavior

- What do you expect should be happening?
Both of these two callbacks are invoked, or only the exact one is invoked. At least, the behavior should be consistent.

### How to reproduce

expo link: [https://snack.expo.io/@sophister/addlistener-vs-navigationevents](https://snack.expo.io/@sophister/addlistener-vs-navigationevents) 

you can enter and exit the `Detail` screen multiple times to reproduce.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.0.0-rc.5
| react-native     |

**Comment by brentvatne** [comment]
hi! please use the latest version of react-navigation rather than a pre-release version. the latest version is 3.11.1 at the time of writing. if your issue is not resolved by updating (i suspect it will be) then create a new issue and just copy and paste your information here but with the updated react-navigation version info

**Comment by sophister** [comment]
@brentvatne  I've updated `react-navigation` to `3.11.1`, but same problem. A new issue here [https://github.com/react-navigation/react-navigation/issues/6184](https://github.com/react-navigation/react-navigation/issues/6184)
