### ISSUE TITLE
How can one navigate straight to the bottom screen of a StackNavigator whilst also providing params for the intermediate screens skipped over?

### ISSUE THREAD

**Issue by shirakaba** [react-navigation/react-navigation#6158]
### Current Behavior

I have an app with two StackNavigators: the LoginStack, and the MainStack. Upon the user completing login in the LoginStack, I navigate them to the next stack: MainStack.

If it's their first time using the app, the screen I navigate them to is MenuScreen (where they can navigate onward to VideoScreen by selecting a video); but if they've selected a video from the MenuScreen before, I skip past MenuScreen and navigate them directly to VideoScreen.

When skipping directly to VideoScreen, however, I find that upon calling `navigation.goBack()` from VideoScreen, MenuScreen is navigated back to without any navigation params. How can I ensure that these params are provided?

#### Screenshot upon navigating from LoginStack's LoginScreen to MainStack's VideoScreen

![VideoScreen](https://user-images.githubusercontent.com/14055146/62617205-47165180-b909-11e9-82bb-113f68da5840.png)

#### Screenshot upon navigating back from MainStack's VideoScreen (to MainStack's MenuScreen)

![MenuScreen](https://user-images.githubusercontent.com/14055146/62617217-4b426f00-b909-11e9-83b7-69f7920d8bd9.png)

### Expected Behavior

I would expect there to be an API for passing params to intermediate routes in a StackNavigator if any screens in the stack can be skipped past. Instead, `navigation.goBack()` is possible yet (to my knowledge) there is no API to ensure that params are passed to the route that we're navigating back to.

### How to reproduce

**Run [my Snack](https://snack.expo.io/@bottledlogic/react-navigation-going-back-to-intermediate-screen)**, which will automatically navigate from LoginStack's LoginScreen to MainStack's VideoScreen. Press either of the two back buttons to trigger `navigation.goBack()`, and you'll find that it will navigate back to the MainStack's MenuScreen without any navigation params having been provided to that screen.

I shall also attach the relevant code from the Snack below, for reference.

##### AppNavigator

```js
const LoginStack = createStackNavigator({ LoginScreen });
const MainStack = createStackNavigator({
    MenuScreen,
    VideoScreen,
});

const AppNavigator = createSwitchNavigator(
    {
        LoginStack,
        MainStack,
    },
    {
        initialRouteName: "LoginStack",
    }
);
```

##### Routing from LoginStack's LoginScreen to MainStack's VideoScreen

```js
const videoScreenParams = {
    originStack: "LoginStack",
    originScreen: "LoginScreen"
};

/* Called from the InitStack.
 * First we navigate to the MainStack, then we perform a sub-action
 * to navigate to the VideoScreen within that stack. */
this.props.navigation.navigate({
    routeName: "MainStack",
    params: {},
    action: {
        type: "Navigation/NAVIGATE",
        routeName: "VideoScreen",
        params: {
            videoScreenParams
        },
    },
});
```

##### Going back in MainStack from VideoScreen to MenuScreen

```js
/* Called from VideoScreen. */
this.props.navigation.goBack();
```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.11.1
| react-native     | Tested on 0.59.5 and whatever version Expo Snack is running
| node             | Tested on 12.5.0 and whatever version Expo Snack is running
| npm or yarn      | yarn (not sure about Expo Snack)

**Comment by brentvatne** [comment]
you would have to customize the router for this: https://reactnavigation.org/docs/en/custom-routers.html

an example of how to do this kind of customization (implementing the actual behavior is up to you though): https://github.com/brentvatne/react-europe-2019-react-navigation/blob/5ccb336f994c42038f6ba4e99ff223e0aaf54790/sections/PreventingActions.js#L125-L141
