### ISSUE TITLE
Sometime tab doesn't open the corresponding view. Nothing happened.

### ISSUE THREAD

**Issue by anagar23** [react-navigation/react-navigation#6161]
I have updated my react native version to 0.59 from 0.51 and also updated React-Navigation to v3 from v1. I have 5 tabs in my app configured via createBottomTabNavigator, when I switch to other tab, sometime it works, however, sometime not. Mostly it happened with third tab. I have some my own code on `tabBarOnPress` but also tried without it.

It worked correctly for me in v1.

**I have tried to debug it. What happened is, in `createTabNavigator.js`, `_makeDefaultHandler`, method calls and `navigation.isFocused()` returns `true` while it's not in the focus.** 
### Current Behavior

- Nothing happends

### Expected Behavior

- It should open the tab and it's view

### How to reproduce

This is my configuration code :

```
const bottomTabs = {
  Home: {
    screen: HomeView,
    navigationOptions: {
      header:null,
      tabBarIcon: ({ tintColor, focused }) => (
        <Image
          source={require('../assets/icons/tab_home.png')}
          style={[styles.icon, { tintColor: tintColor }]} />
      )
    },
  },
  'My Health': {
    screen: MyHealthTab,
    navigationOptions: {
      header:null,
      tabBarIcon: ({ tintColor, focused }) => (
        <Image
          source={require('../assets/icons/tab_health_records.png')}
          style={[styles.icon, { tintColor: tintColor }]} />
      ),
    },
  },
  Search: {
    screen: SearchStackView,
    navigationOptions: ({ navigation }) => ({
      header:null,
      tabBarIcon: ({ tintColor, focused }) => (
        <Image
          source={require('../assets/icons/tab_search.png')}
          style={[styles.icon, { tintColor: tintColor }]} />
      ),
      tabBarOnPress: ({ navigation, defaultHandler }) => {      
        if (navigation.state.index > 0) {
          const currentScreen = NavigationService.currentScreen();
          if (currentScreen !== 'SearchForCareType') {
            Promise.all([
              navigation.dispatch(
                NavigationActions.navigate({ routeName: 'SearchForCareType' })
              )
            ])
          }
        } else {
          defaultHandler();
        }
      },
    })
  },
  Coverage: {
    screen: Coverage,
    navigationOptions: {
      header:null,
      tabBarIcon: ({ tintColor, focused }) => (
        <Image
          source={require('../assets/icons/tab_coverage.png')}
          style={[styles.icon, { tintColor: tintColor }]} />
      ),
    },
  },
  Share: {
    screen: ShareTab,
    navigationOptions: ({ navigation }) => ({
      header:null,
      tabBarIcon: ({ tintColor, focused }) => (
        <Image
          source={require('../assets/icons/share.png')}
          style={[styles.icon, { tintColor: tintColor }]} />
      ),
      tabBarOnPress: ({ navigation, defaultHandler }) => {        
        if (navigation.state.index > 0) {
            const tabRoute = route.routeName;
            Promise.all([
              navigation.dispatch(
                NavigationActions.navigate({ routeName: tabRoute })
              )
            ]).then(() => navigation.navigate('ShareHomeScreen'))
          } else {
            defaultHandler();
          }
        }
    })
  },
}
```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.11.0
| react-native     | 0.59.0
| node             | 8.11.3
| npm or yarn      | 5.6.0

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
