### ISSUE TITLE
TouchableOpacity doest work

### ISSUE THREAD

**Issue by maxakak1998** [react-navigation/react-navigation#6168]
Hello, i am using RN version 0.59.9 and React Navigaton 3.11.1.
I want to add onPress on my view so i wrap it in TouchableOpacity but it doest work for me.
I try to use it outside React Navigation and it is still working, so maybe it is a bug in this lib.
Here is some snapshot from my code:

It works here without using React Navigation:
![image](https://user-images.githubusercontent.com/50696626/62731511-8e592b00-ba4c-11e9-85a6-fc2e2f6db630.png)

But not here, it is my component inside the stacknavigator
 
![image](https://user-images.githubusercontent.com/50696626/62731270-f8bd9b80-ba4b-11e9-9f24-3ab5c9e26321.png)

Here is my stack:

![image](https://user-images.githubusercontent.com/50696626/62731548-a03ace00-ba4c-11e9-8c7a-88bbf3966ce6.png)

Also i have tried to set the height for my view, nothing happens

Thanks for reading my issue !

**Comment by brentvatne** [comment]
hi there! this is a question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.
