### ISSUE TITLE
Lazy loading a navigator with suspense

### ISSUE THREAD

**Issue by denissb** [react-navigation/react-navigation#6174]
I am building a cross-platform app with `react-native-web` and `react-navigation`.
The problem I have is that when I try to lazy-load a whole navigator with `react.lazy` + `React.Suspense` the application fails because the navigation state is not being passed to the mounted navigator although I am passing all the props down to it from the lazy wrapper.

I can get the application to run and lazy-load if I wrap the `MoreNavigator` with `createAppContainer`, but that creates problems with the navigation state such as route names not being updated accordingly. (e.g creates 2 independent navigation states)

### Current Behavior
`TypeError: No "routes" found in navigation state. Did you try to pass the navigation prop of a React component to a Navigator child? See https://reactnavigation.org/docs/en/custom-navigators.html#navigator-navigation-prop`

Code:

Main router
```
import { createStackNavigator } from 'react-navigation';

import MoreNavigatorLazyWrapper from './areas/more';
import Main from './areas/main';

export default routes => createStackNavigator(
{
  'More': { screen: MoreNavigatorLazyWrapper },
  'Main': { screen: Main },
}
,{
  headerMode: 'none',
 ),
});
```
MoreNavigatorLazyWrapper loading wrapper
```
import React from 'react';
import Loader from '../misc/Loader';

const MoreNavigator = React.lazy(() => import('./MoreNavigator'));

const MoreNavigatorLazyWrapper = props => (
  // Displays <Loader> until MoreNavigator loads
  <React.Suspense fallback={<Loader />}>
    <MoreNavigator {...props} />
  </React.Suspense>
);

export default MoreNavigatorLazyWrapper;
```

MoreNavigator
```
import { createStackNavigator } from 'react-navigation';
import Profile from './Profile';
import Feedback from './Feedback';
import Settings from './Settings';

import More from './More';

export default createStackNavigator({
  'Overview': { screen: More },
  'Profile': {
    screen: Profile,
  },
 'Feedback': {
    screen: Feedback,
  },
  'Settings': {
    screen: Settings,
  },
});
```
### Expected Behavior

I expect the navigation to work correctly except for deeplinks to lazy-loadable routes until they are loaded.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.11.0
| react-native     | 0.59.8
| node             |  11.7.0
| npm or yarn      |  1.13.0

**Comment by eriveltonelias** [comment]
hi @denissb 

lazy import are suported only on react-navigation v5, because is component based.

https://github.com/react-navigation/navigation-ex

let me know if is that what are you looking for.

**Comment by mMarcos208** [comment]
The are any example?

**Comment by alejomendoza** [comment]
Doesn't work with react-navigation v5, paths won't work.

**Comment by anhnch** [comment]
Do we need to use React.lazy to dynamically import the screen components or React Navigation does it under the hood?

**Comment by gaoxianglyx** [comment]
same question

**Comment by whalemare** [comment]
> Do we need to use React.lazy to dynamically import the screen components or React Navigation does it under the hood?

React Navigation unable to do that, because of nature of `async imports`. With `import` you don't do any sync job like you do this with `require`.

So you should to do this manually

**Comment by lockykeaney** [comment]
Was there ever any update for this? Would love an example how to code split the routes for web.

**Comment by bzozoo** [comment]
It is not working again in Expo SDK 48.0.20 React Navigation 6X
