### ISSUE TITLE
Swipe back on Android not working

### ISSUE THREAD

**Issue by durdevic** [react-navigation/react-navigation#6175]
I am trying to add a swipe back on Android, unfortunately it doesn't work. I used the suggested example from this page https://reactnavigation.org/docs/en/stack-navigator.html#gesturesenabled, but still no luck. 

Is it even possible to do it on Android? I mean there is the [gesturesEnabled](https://reactnavigation.org/docs/en/stack-navigator.html#gesturesenabled) property.

---

### Current Behavior

- Not working on Android
```javascript
const ModalNavigator = createStackNavigator(
  {
    Main: { screen: Main },
    Login: { screen: Login },
  },
  {
    // headerMode: 'none',
    // mode: 'modal',
    defaultNavigationOptions: {
      gesturesEnabled: true,
    },
    transitionConfig: () => ({
      transitionSpec: {
        duration: 300,
        easing: Easing.out(Easing.poly(4)),
        timing: Animated.timing,
      },
      screenInterpolator: sceneProps => {
        const { layout, position, scene } = sceneProps;
        const { index } = scene;

        const height = layout.initHeight;
        const translateY = position.interpolate({
          inputRange: [index - 1, index, index + 1],
          outputRange: [height, 0, 0],
        });

        const opacity = position.interpolate({
          inputRange: [index - 1, index - 0.99, index],
          outputRange: [0, 1, 1],
        });

        return { opacity, transform: [{ translateY }] };
      },
    }),
  }
);
```

### Expected Behavior

- Swipe to go back on Android device

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.11.1
| react-native     | 0.60.4
| node             | 10.15.1
| npm or yarn      | 6.4.1

**Comment by jerameel** [comment]
This also happens to me on latest react native and react navigation.

Based on redux logger, navigation action is being fired properly, but the screen does not actually go back.

Turning the remote js debugger will make it work, but what if you need to test something then this becomes a major blocker

**Comment by durdevic** [comment]
@jerameel Cool! 💪Would you be kind and provide me an example app of working navigation, I just can't get it to work? 

Thanks!

**Comment by yangfanyu** [comment]
<img width="1296" alt="WeChat45305058c172d3c393103d2c718d1af8" src="https://user-images.githubusercontent.com/17940584/66057130-c3748c00-e56a-11e9-89a4-756bb7e643ab.png">

i forget it, by this step, it woks

**Comment by yangfanyu** [comment]
package com.reactnavigation.example;

import com.facebook.react.ReactActivity;
+ import com.facebook.react.ReactActivityDelegate;
+ import com.facebook.react.ReactRootView;
+ import com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView;

public class MainActivity extends ReactActivity {

  @Override
  protected String getMainComponentName() {
    return "Example";
  }

+  @Override
+  protected ReactActivityDelegate createReactActivityDelegate() {
+    return new ReactActivityDelegate(this, getMainComponentName()) {
+      @Override
+      protected ReactRootView createRootView() {
+       return new RNGestureHandlerEnabledRootView(MainActivity.this);
+      }
+    };
+  }
}

[https://reactnavigation.org/docs/en/getting-started.html](url)

**Comment by CrazyMan2** [comment]
> 包com.reactnavigation.example;
> 
> 导入com.facebook.react.ReactActivity;
> 
> * 导入com.facebook.react.ReactActivityDelegate;
> * 导入com.facebook.react.ReactRootView;
> * 导入com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView;
> 
> 公共类MainActivity扩展了ReactActivity {
> 
> @override
> 受保护的字符串getMainComponentName（）{
> 返回“示例”；
> }
> 
> * @override
> * 受保护的ReactActivityDelegate createReactActivityDelegate（）{
> * 返回新的ReactActivityDelegate（this，getMainComponentName（））{
> * ```
>    @Override
>   ```
> * ```
>    protected ReactRootView createRootView() {
>   ```
> * ```
>     return new RNGestureHandlerEnabledRootView(MainActivity.this);
>   ```
> * ```
>    }
>   ```
> * };
> * } 
>   }
> 
> [https://reactnavigation.org/docs/en/getting-started.html](url)

After the configuration doesn't work on android
