### ISSUE TITLE
Swiping the drawer is not working on RN v0.60.4

### ISSUE THREAD

**Issue by Albert0405** [react-navigation/react-navigation#6176]
Never had a problem installing gesture handler and reanimated but when i tried to swipe on the left side of my device, the drawer wont open, however you can open it through the use of `this.props.navigation.openDrawer`

**Comment by RZsam** [comment]
same here 
 
```
"react-native": "0.60.4",
"react-native-gesture-handler": "^1.3.0",
"react-native-reanimated": "^1.2.0",
"react-navigation": "^3.11.1",
```

**Comment by mbrehme** [comment]
+1

**Comment by voxspox** [comment]
+1

**Comment by Albert0405** [comment]
https://github.com/kmagiera/react-native-gesture-handler/issues/725

**Comment by Abhishekkumarshakya** [comment]
modifications to MainActivity.java

Step:1 -->
import com.facebook.react.ReactActivityDelegate;
import com.facebook.react.ReactRootView;
import com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView;

Step:2 --> Inside class
@override
protected ReactActivityDelegate createReactActivityDelegate() {
return new ReactActivityDelegate(this, getMainComponentName()) {
@override
protected ReactRootView createRootView() {
return new RNGestureHandlerEnabledRootView(MainActivity.this);
}
};
}

**Comment by voxspox** [comment]
ok, the manual [setup](https://kmagiera.github.io/react-native-gesture-handler/docs/getting-started.html#android) has still to be done. `react-native link` is not necessary with 0.60 new auto-linking feature

**Comment by satya164** [comment]
https://github.com/react-navigation/drawer/issues/91

**Comment by Moji0098** [comment]
**i have error for your solution** 

error: cannot find symbol
  @override
   ^
  symbol:   class override
  location: class MainApplication
/media/x/2406AE1206ADE4D0/Projects/MY/payab/android/app/src/main/java/com/payab/MainApplication.java:57: error: cannot find symbol
  return new ReactActivityDelegate(this, getMainComponentName()) {
                                         ^
  symbol:   method getMainComponentName()
  location: class MainApplication
/media/x/2406AE1206ADE4D0/Projects/MY/payab/android/app/src/main/java/com/payab/MainApplication.java:58: error: cannot find symbol
    @override
     ^
  symbol: class override
/media/x/2406AE1206ADE4D0/Projects/MY/payab/android/app/src/main/java/com/payab/MainApplication.java:60: error: not an enclosing class: MainActivity
    return new RNGestureHandlerEnabledRootView(MainActivity.this);
                                                           ^
4 errors


"dependencies": {
    "@react-native-community/async-storage": "^1.6.1",
    "react": "16.8.6",
    "react-native": "0.60.5",
    "react-native-gesture-handler": "^1.4.1",
    "react-native-jalaali-date-picker": "^1.0.0",
    "react-native-reanimated": "^1.2.0",
    "react-native-vector-icons": "^6.6.0",
    "react-navigation": "^3.12.1",
    "react-navigation-drawer": "^2.0.0"
  },

**Comment by voxspox** [comment]
@Moji0098 please follow the setup for react-native-gesture-handler

**Comment by Moji0098** [comment]
My gesture project have not any problem because i import DrawerLayoutAndroid from react-native and i slide this and its working good but when i use react navigation drawer it doesnt work . Thanks to help me

**Comment by netgfx** [comment]
Similar issue here as well, local code not using Expo swipe doesn't work, but here it does https://snack.expo.io/@netgfx/auth-flow-v3 any ideas?

**Comment by ShahidAli786** [comment]
check your [react-native-gesture-handler setup](https://kmagiera.github.io/react-native-gesture-handler/docs/getting-started.html) in MainActivity file. example here


```
package com.swmansion.gesturehandler.react.example;

import com.facebook.react.ReactActivity;
+ import com.facebook.react.ReactActivityDelegate;
+ import com.facebook.react.ReactRootView;
+ import com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView;

public class MainActivity extends ReactActivity {

  @Override
  protected String getMainComponentName() {
    return "Example";
  }

+  @Override
+  protected ReactActivityDelegate createReactActivityDelegate() {
+    return new ReactActivityDelegate(this, getMainComponentName()) {
+      @Override
+      protected ReactRootView createRootView() {
+       return new RNGestureHandlerEnabledRootView(MainActivity.this);
+      }
+    };
+  }
}
```
