### ISSUE TITLE
Upgrade all navigator sub-modules version

### ISSUE THREAD

**Issue by SaeedZhiany** [react-navigation/react-navigation#6177]
### Current Behavior
I just look at the versions of sub-module libraries and I saw that current react-navigation uses very old versions. it seems there are some performance improvements in that sub-modules such as TabNavigators as @satya164 [said here](https://github.com/react-navigation/react-navigation/issues/5990#issuecomment-500634291) 

### Expected Behavior
Upgrade all sub-modules version

### How to reproduce
nothing to reproduce. just you can read the conversation in [this issue](https://github.com/react-navigation/react-navigation/issues/5990)

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.11.0
| react-native     | 0.59.10
| node             | 12.3.1
| npm or yarn      | 6.10.2

**Comment by eriveltonelias** [comment]
hi @SaeedZhiany 

on react navigation v4, `react-navigation-stack react-navigation-tabs react-navigation-drawer` was extracted from the core, now you need to install and import independent

https://github.com/react-navigation/react-navigation/releases/tag/v4.0.0
