### ISSUE TITLE
undefined is not an object (evaluating '_this2.props.navigation.navigate') on a recursive component

### ISSUE THREAD

**Issue by dcalixto** [react-navigation/react-navigation#6178]
After setup the router with:

PostShow > Comments > Comment > Reply
The postShow belong to the stackNavigator!

when click on the comment component to go to reply

show this error:

> undefined is not an object (evaluating
> '_this2.props.navigation.navigate')

And after search on the docs and the react-navigation issues page and here on SO

the solution seems to place navigation={this.props.navigation} on the child component because is not inside the stack. But still showing the same error after some attempt!

then other solution is to use  withNavigation  on the parent component, still not redirecting to the reply screen!

So, someone please can clarify how to properly use the navigation when the components are recursive or not under the stack or any Navigation component?

<router>    

    export const HomeStack = createStackNavigator({
      Home: {
        screen: Home
      },
    
      PostShow: {
        screen: PostShow,
    
        navigationOptions: ({ navigation }) => ({
          title: `${navigation.state.params.post.title}`,
          headerTitleStyle,
          headerStyle
        })
      }
    });
    
    The postSHow component with:
    
    <postShow>
    
      render() {
        const { title, body } = this.state;
    
        return (
          <View style={{ flex: 1 }}>
           
              <Text>{title}</Text>
              <Comments
                comments={this.state.comments}
              
                //navigation={this.props.navigation}
                //navigate={this.props.navigation.navigate}
              />               
         
          </View>
        );
      }
    }

  The comments/comment 
  <comments/comment>

    import Comment from "./Comment";
    
    class Comments extends Component {
    
      render() {
        var comments =
          this.props.comments &&
          this.props.comments.map(comment => {
            return (
              <View key={comment.id} style={styles.commentContainer}>
                <Comment
                  // navigate={this.props.navigation.navigate}
                  navigation={this.props.navigation}
                  comment={comment}
              
                />
              </View>
            );
          });
    
        return <View>{comments}</View>;
      }
    }
    
    export default Comments;

 

I'd like to on comment component be able to click on reply and redirect to the screen Reply

        import React, { Component } from "react";
    
    import { View, Text } from "react-native";
    
    import Comments from "./Comments";
    import Reply from "./Reply";
    
    import { withNavigation } from "react-navigation";
    class Comment extends Component {
    
    
      render() {
        const comment = this.props.comment;
        const { navigation } = this.props;
        return (
          <View>
            <Text style={styles.body}>{comment.comment} </Text>
            <Text
              style={{ color: "blue" }}
              onPress={() => this.props.navigation.navigate("Reply")}
            
            >
              Reply
            </Text>
    
            <Comments
              // navigation={this.props.navigation}
              // navigate={this.props.navigation.navigate}
              comments={comment.replies}
         
            />
          </View>
        );
      }
    }
    
    export default Comment;

**Comment by armagedan** [comment]
I think `Reply` should be an actual screen in your stack navigator. Or did you not include that part?

Also wouldn't this cause an issue? where the line `const { navigation } = this.props;` and then you are doing `onPress={() => this.props.navigation.navigate("Reply")}`.

**Comment by satya164** [comment]
hi there! this is a question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.

**Comment by AkashRajpoot** [comment]
![Screenshot from 2020-02-20 10-48-24](https://user-images.githubusercontent.com/61053913/74903314-96682f00-53ce-11ea-96e3-e08becd196e0.png)
How can i fix this error i did not get any proper solution for this.

**Comment by awais-sf** [comment]
componentDidMount() {
    setTimeout((props) => {
      this.props.navigation.navigate('log');
    }, 200);
  }

i write this and get the same issue
