### ISSUE TITLE
NavigationEvents are slow in tab switching when swiping

### ISSUE THREAD

**Issue by SourceCipher** [react-navigation/react-navigation#6181]
### Current Behavior

When swiping from tab 1 to tab 2, navigation events are delayed/slow, but if you press on the tab 1 button instead of swiping from 1 screen to the other, the even is instant (usually triggers before the screens starts to change)

### Expected Behavior

Event should trigger while swiping as fast as it does when you clicking on the tabs

### How to reproduce

Open console log and see the difference when you swipe from the tab 1 to tab 2 and when you switch the views by clicking on the tab 1 and tab 2 buttons

https://snack.expo.io/@gwidaz/a40cb3 

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  ^3.10.2
| react-native     | ^0.59.8
| node             |  10.15.3
| npm or yarn      | 6.4.1

**Comment by satya164** [comment]
It's expected behavior. Use https://github.com/react-navigation/tabs directly which uses a new implementation if you want it to trigger sooner.

**Comment by SourceCipher** [comment]
@satya164 Thanks for your quick response! Let me give this a go

**Comment by SourceCipher** [comment]
@satya164 Your solution did not worked tho. In fact its twice slower than just using the one in OP. The animation seems glitchy as well. The tab highlighting isnt working properly.

When moving through the screens the update is still much slower than just tapping on the tabs.
