### ISSUE TITLE
didfocus event fired on initial mount  with class component but it didn't with hook

### ISSUE THREAD

**Issue by chitsutote** [react-navigation/react-navigation#6183]
### Current Behavior
When I navigate between screens in the same navigation stack or from other navigation stack, it will trigger the didFocus event and fire api calls with class component.
But it only trigger the didFocus event, when navigating between screens in the same navigation stack with hook version.

### Expected Behavior
When I navigate between screens in the same navigation stack or from other navigation stack, it should have same behavior with either class component or hook version.

### Class component version
```
class someScreen extends Component {
    componentDidMount() {
       const {
           navigation,
       } = this.props;

       this.navFocusListener = navigation.addListener('didFocus', () => {
         // do some API calls here
         console.log("class version");
         API_CALL();
       });
    }

    componentWillUnmount() {
        this.navFocusListener.remove();
    }
}
```
**console output**
transition from other navigation stack to this screen: class version

transition between screens in same stack: class version

#### Hook version
```
const someScreen = ({
 navigation,
}) => {
    useEffect(() => {
        const navFocusListener = navigation.addListener('didFocus', () => {
        // do some API calls here
        API_CALL();
        console.log('hooooks');
    });

    return () => {
        navFocusListener.remove();
    };
  }, []);
}
```
**console output**
transition from other navigation stack to this screen: nothing is shown in console

transition between screens in same stack: hooooks

-----
BTW, here is the workaround solution I found.
You can see there is little difference in console between class version and hook version with workaround solution 
```
const someScreen = ({
 navigation,
}) => {
      useEffect(() => {
          const isFocused = navigation.isFocused();

          // manually judge if the screen is focused
          // if did, fire api call
          if (isFocused) {
             // do the same API calls here
             API_CALL();
             console.log('focused section');
          }

          const navFocusListener = navigation.addListener('didFocus', () => {
              // do some API calls here
              API_CALL();
              console.log('listener section');
          });

          return () => {
              navFocusListener.remove();
          };
      }, []);
}
```
**console output**

transition from other navigation stack to this screen: focused section

transition between screens in same stack: listener section

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.17.0
| react-native     | 59.8
| expo             | SDK 33
| yarn        | 1.10.1

**Comment by sophister** [comment]
I've experienced a similar problem. I guess, `navigation.addListener` in `useEffect` is al little late, when code in `useEffect` run, the `didFocus` event has fired (the focus state of our screen has transitioned to `didFocus`), so our callback is not invoked.

BTW, I'm using the same hack with yours 😅

**Comment by chitsutote** [comment]
@sophister I guess I found the root cause of the inconsistent behavior.
There is another hook called `useLayoutEffect`
> useLayoutEffect
The signature is identical to useEffect, but it fires synchronously after all DOM mutations. Use this to read layout from the DOM and synchronously re-render. Updates scheduled inside useLayoutEffect will be flushed synchronously, before the browser has a chance to paint.

the useLayoutEffect will block the painting while the useEffect will not.
That confirm and explains our guess that the `didFocus` event had fired, but it didn't trigger the listener since it miss the timing

so in my case, I have to use `useLayoutEffect` instead of `useEffect`

reference: https://kentcdodds.com/blog/useeffect-vs-uselayouteffect

**Comment by diogopalhais** [comment]
Hey, this way i think it wil do what you need. I just tested and it seems to work fine in every cenario. In refetch you can do the api call.

```javascript
useEffect(() => {
        const listener = navigation.addListener('didFocus',() => refetch())
        return function cleanup() {
            listener.remove();
          };
    },[]);
```

**Comment by chitsutote** [comment]
@diegocstn Thanks for replying. I've tried your solution. It still outputs the same result as hook version.
api call didn't execute when transitioning from other navigation stack but it is triggered when transitioning between screens in the same stack.

**Comment by diogopalhais** [comment]
@chitsutote in my nav structure i have one tabnavigator with one stack for each child, and im transitioning from one stack to another and it works. but maybe is because they all inside of the same tabnavigation. Maybe its not a hooks problem but with your nav structure. Hope it helps

**Comment by chitsutote** [comment]
@diogopalhais Could it be? I guess it miss the timing since the screen did focused.
my structure is that I have a drawer navigator with one stackNavigator for each child.

**Comment by dstoppelman** [comment]
Similar workarounds that worked for me:
```javascript
const SomeScreen = ({ navigation }) => {
  const isFocused = navigation.isFocused();

  React.useEffect(() => {
    if (isFocused) {
      runSomeEffect();
    }
  }, [isFocused]);

  return <SomeElement />;
};
```
```javascript
import { withNavigationFocus } from 'react-navigation';

const SomeView = withNavigationFocus(({ isFocused }) => {
  React.useEffect(() => {
    if (isFocused) {
      runSomeEffect();
    }
  }, [isFocused]);

  return <SomeElement />;
});
```

**Comment by chrisparton1991** [comment]
`useLayoutEffect` is working nicely for me so far.

Just to add a data point, Having a `didFocus` listener inside a `useEffect` worked on some devices during testing (Galaxy S7, iPhone X simulator) but not on others (iPad Air 2, iPad Air 3 simulator).

Possibly a race condition, but I haven't bothered to check since `useLayoutEffect` is the safer option anyway.

**Comment by kartiikeyabaleneni** [comment]
Kudos to your work around.
