### ISSUE TITLE
willFocus not trigger with 3.11.1

### ISSUE THREAD

**Issue by sophister** [react-navigation/react-navigation#6184]
### Current Behavior

- What code are you running and what is happening?
I use both `navigation.addListener("willFocus")` and `<NavigationEvents onWillFocus={callback} />` to bind the `willFocus` event. 
But sometimes only one of these two callbacks is invoked, and sometimes both of them are invoked. 

I've tested it with `Android`, not sure about `iOS`.

### Expected Behavior

- What do you expect should be happening?
Both of these two callbacks are invoked, or only the exact one is invoked. At least, the behavior should be consistent.

### How to reproduce

expo link: [https://snack.expo.io/@sophister/addlistener-vs-navigationevents](https://snack.expo.io/@sophister/addlistener-vs-navigationevents) 

you can enter and exit the `Detail` screen multiple times to reproduce.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.11.1
| react-native     |
| expo                 |  SDK 34

**Comment by vonovak** [comment]
you added `navigation.addListener("willFocus")` in componentDidMount. Does moving it to constructor help?

**Comment by sophister** [comment]
@vonovak actually the code `navigation.addListener("willFocus")`always works, but `< NavigationEvents 
onWillFocus={calback} />` does not work as expected, it is fired sometimes, not always.

**Comment by AEPKILL** [comment]
same issue

**Comment by lihp2014** [comment]
same issue

**Comment by BravenxX** [comment]
Same problem with react-navigation 3.12.1
