### ISSUE TITLE
TypeError: navigation.getChildNavigation is not a function. (In 'navigation.getChildNavigation(route.key)'

### ISSUE THREAD

**Issue by kamlesh1000** [react-navigation/react-navigation#6185]
I wanted to integrate Redux with React-navigation. Created all the structure for the implementation. But, I am getting the above error and I am getting no any proper solution. I found some similar error raised by others , but non helped me. The structure of my project is:

	index.js
	src=>
	   actions=>
	   reducers=>
		 index.js
		 loginReducers.js
		 navigationReducer.js
	   route=>
		 InitialAuthRoute.js
		 ReduxNavigation.js
	   screens=>
		 Login.js

index.js

	  import {AppRegistry} from 'react-native';
	  import ReduxNavigation from './src/route/ReduxNavigation';
	  import {name as appName} from './app.json';
	  import React from 'react';
	  import {Provider} from 'react-redux';
	  import {createStore, applyMiddleware} from 'redux';
	  import reducers from './src/reducers';
	  import thunk from 'redux-thunk';

	  const createStoreWithMiddleware = applyMiddleware(thunk)(createStore);

	  const store = createStoreWithMiddleware(reducers);

	  const AppContainer = () =>
		<Provider store={store}>
		  <ReduxNavigation/>
		</Provider>

	  AppRegistry.registerComponent(appName, () => AppContainer);
ReduxNavigation.js

	  import React, { Component } from "react";
	  import { connect } from "react-redux";
	  import { addNavigationHelpers } from "react-navigation";
	  import InitialAuthRoute from "./InitialAuthRoute";
	  import NavigationReducer from "../reducers/navigationReducer";

	  class AppNavigation extends Component {
		render() {
		  return (
			<InitialAuthRoute navigation={({
			  dispatch: this.props.dispatch,
			  state: this.props.navigationState,
			})} />
		  );
		}
	  }

	  const mapStateToProps = state => {
		return {
		  navigationState: state.nav
		};
	  };

	  export default connect(mapStateToProps)(AppNavigation);
initialAuthRoute.js

	  import {createStackNavigator} from 'react-navigation';
	  import LoginScreen from '../screens/Login'

	  const PrimaryNav = createStackNavigator({
		LoginScreen: { screen: LoginScreen }
	  }, {
		headerMode: 'none',
		initialRouteName: 'LoginScreen'
	  })

	  export default PrimaryNav
reducers/index.js

	  import {combineReducers} from 'redux';
	  import LoginReducers from './loginReducers';
	  import NavigationReducer from "./navigationReducer";

	  export default combineReducers({
		login: LoginReducers,
		nav: NavigationReducer,
	  })
navigationReducer:

	  import AppNavigator from "../route/InitialAuthRoute";

	  const navigationReducer = (state, action) => {

		const newState = AppNavigator.router.getStateForAction(action, state);
		return newState || state;
	  };

	  export default navigationReducer; 
Environment:

System:
	   OS: Windows 10
		CPU: (4) x64 Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
		Memory: 3.27 GB / 7.92 GB
	  Binaries:
		Node: 12.3.1 - C:\Program Files\nodejs\node.EXE
		Yarn: 1.16.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
		npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
	  IDEs:
		Android Studio: Version  3.4.0.0 AI-183.6156.11.34.5522156

Packages:
		"react": "16.8.6",
		"react-native": "0.60.4",
		"react-redux": "^7.1.0",
		"redux": "^4.0.4",
		"redux-thunk": "^2.3.0",
		"react-navigation": "^3.11.1",
		"react-navigation-redux-helpers": "^3.0.2",

**Comment by satya164** [comment]
We don't recommend putting navigation state to Redux and don't support it in core. Please open an issue in https://github.com/react-navigation/redux-helpers if you have issues with redux.

**Comment by bwoodlt** [comment]
@kamlesh1000 Did you fix this, having similar error

**Comment by kirankbee** [comment]
<img width="280" alt="Screen Shot 2020-03-29 at 7 39 30 PM" src="https://user-images.githubusercontent.com/13452228/77869954-056a4c00-71f5-11ea-8369-b94f39c24590.png">
 any guidance please?
