### ISSUE TITLE
didFocus listener doesn't trigger when navigating to a previously unmounted screen with key in nested stack navigator 

### ISSUE THREAD

**Issue by EdgarHSM** [react-navigation/react-navigation#6187]
### Current Behavior

I have a navigator setup similar to this: 

```
Drawer
|
|
 — Stack
  |
   — Screen_one
  |
   — Screen_two

```

A stack navigator with 2 screens, inside a drawer navigator. 
In Screen_two I'm adding a listener in the componenDidMount function like so: 

`  componentDidMount() {
    this.focusListener = this.props.navigation.addListener('didFocus', () => {
      console.log('Screen 2 didFocus');
    });
  }`

In Screen_one I'm navigating to Screen_two like so: 

`this.props.navigation.navigate({
              routeName: 'Screen_two',
              key: 'Screen_two_key',
            });`

When I navigate to Screen_two for the first time the listener triggers as expected, but when I navigate back to Screen_one and then navigate to Screen_two again the listener doesn't trigger.

### Expected Behavior

Listener should trigger every time I navigate to Screen_two

### How to reproduce
https://snack.expo.io/@eddyserrano/listeners

Navigate between screens and check the console for logs.

### Your Environment

| software              | version
| ---------------- | -------
| react-navigation | ^3.11.0
| react-native        | ^0.59.9
| node                    |  10.0.0
| npm                     |  5.6.0

**Comment by davidskaarup** [comment]
I have the same problem. Any solution?

**Comment by IronTony** [comment]
Ye same here also on the 4.0.10 version. On old one seems working

**Comment by EdgarHSM** [comment]
Sorry never found a solution :( Realized I didn't need the keys in my use case so I just stopped using them and the focus listener went back to normal

**Comment by linzera** [comment]
Same problem here with 4.0.10.

**Comment by whereiscode** [comment]
@EdgarHSM This is a bug that can't be fixed. You can use it in some older versions, but you have to try it out one by one

**Comment by whereiscode** [comment]
@linzera 4.x ，It is possible to back up without using the gesture. The gesture only supports listening once. If you click the back button, it will always work

Note that gestures only support one listen, which is a super bug

**Comment by whereiscode** [comment]
NavigationEvents is more buggy, so this is not recommended

**Comment by whereiscode** [comment]
If you change the second interface to modal mode, you can always listen

**Comment by whereiscode** [comment]
I upgraded the cocopods, pod clear and pod install, and NPM node modules were removed and reinstalled, which solved my problem

**Comment by V1sk** [comment]
Same problem here with 4.2.2 .

**Comment by satya164** [comment]
I've reworked the event system which should fix the issue. Please upgrade `react-navigation` to `4.3.4` and `react-navigation-stack` to `2.3.8` and give it a try.
