### ISSUE TITLE
how to full screen?

### ISSUE THREAD

**Issue by Sing1** [react-navigation/react-navigation#6188]
![image](https://user-images.githubusercontent.com/15246585/63166770-ee119080-c061-11e9-9102-96f326000d35.png)

v2.18.3

android中AndroidManifest.xml已设置 <meta-data android:name="android.max_aspect"  android:value="2.4" />

**Comment by Sing1** [comment]
<meta-data
            android:name="android.max_aspect"
            android:value="2.4" />

**Comment by Sing1** [comment]
<meta-data
            android:name="android.max_aspect"
            android:value="2.4" />

**Comment by Sing1** [comment]
<meta-data
            android:name="android.max_aspect"
            android:value="2.4" />

**Comment by Sing1** [comment]
1

**Comment by Sing1** [comment]
<meta-data android:name="android.max_aspect"  android:value="2.4" />

**Comment by eriveltonelias** [comment]
hey there! 

https://reactnavigation.org/docs/en/handling-iphonex.html#docsNav
