### ISSUE TITLE
 'overlayColor' does not work 

### ISSUE THREAD

**Issue by ruanshanshan** [react-navigation/react-navigation#6190]
---

### Current Behavior
my code is below: 
`const HomeStack = createDrawerNavigator(
  {
    ownedCoe: {
      screen: CoeList
    },
    FollewedCoe: {
      screen: FollowedList
    },
    AllCoe: {
      screen: AllList
    }

  },
  {
    initialRouteName: 'ownedCoe',
    contentComponent: DrawerContent,
    drawerBackgroundColor: '#ffffff',
    drawerWidth: width * 0.7,
    overlayColor: 'rgba(0,0,0,0.24)',
    contentOptions: {
      activeTintColor: '#1C6CDC',
      activeBackgroundColor: '#EEF6FF',
      labelStyle: {
        fontWeight: '300',
        color: 'rgba(0,0,0,.6)',
        marginLeft: 0
      }
    }
  }

)`
I get error : 
'overlayColor' does not work

### Expected Behavior

 overlayColor work

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.11.1
| react-native     |
| node             |
| npm or yarn      |

**Comment by wilhelmeek** [comment]
`overlayColor` will default to `rgba(0, 0, 0, 0.5)` which may appear similar to your provided color. Could you try a red color `rgba(255,0,0, 1)` to rule out that case?

**Comment by SandarbhS** [comment]
@wilhelmeek Are you sure that it defaults to `rgba(0, 0, 0, 0.5)`? It used to, but after I upgraded my react-native version to `0.60.4` it defaults to `rgba(0, 0, 0, 1)`.
