### ISSUE TITLE
MaskedViewIOS has been extracted from react-native core

### ISSUE THREAD

**Issue by mi5ha** [react-navigation/react-navigation#6191]
### How to reproduce

I created a clean react native 0.60.5 project, and installed react navigation 3.11.1

When app runs in iOS simulator I get this warning: "MaskedViewIOS has been extracted from react-native core and will be removed in a future release"

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.11.1
| react-native     | 0.60.5
| node             | 10.16.1
| npm or yarn      | 6.9.0

**Comment by eriveltonelias** [comment]
Hi @mi5ha, 

could you try to use `react-navigation-stack` v2 ? and use 

```js
import { createStackNavigator } from react-navigation-stack 
```

**Comment by mi5ha** [comment]
You mean this: https://github.com/react-navigation/stack ?

How is that related to createStackNavigator defined in "react-navigation"?

**Comment by mi5ha** [comment]
I confirm that this issue is gone in react-navigation v3.12.1
