### ISSUE TITLE
undefined is not an object (evaluating 'this.props.navigation.dispatch') on some devices in google play store crash report

### ISSUE THREAD

**Issue by rakibhasan48** [react-navigation/react-navigation#6194]
App crashes due to React navigation error thrown on some devices in release build. 
After releasing our app on play store, we have received crash reports in google play console with the following exception : 

```com.facebook.react.common.JavascriptException:` undefined is not an object (evaluating 'this.props.navigation.dispatch'), stack:```
value@1167:1467
value@-1
value@1167:1837
value@-1
onPress@1167:2825
<unknown>@131:1358
value@23:3807
<unknown>@23:1144
value@23:2772
value@23:1114
`value@-1

Our react-navigation version : 3.11.1

We have faced this type of crash after we migrated our app to React Native 0.60.4. We are unable to reproduce this error with any of our devices. Is this a known problem with React Navigation? Or could this be triggered by something else?

### My Environment
| react-navigation 3.11.1
| react-native 0.60.4

**Comment by matthamil** [comment]
This sounds like you are calling `navigation.dispatch` before `navigation` exists as a prop. You should check to see if your component has received a `navigation` prop before calling methods on it if this error is being thrown. Without a reproducible example, there is nothing actionable for us so I am closing this issue for now.

**Comment by rakibhasan48** [comment]
If it was a matter of trying to access a prop before it exists, the app should have crashed on all devices, right? The issue is that we have only found out about the crash through the reports sent out from a handful of devices.
All I'm asking is, how can this be a device dependent issue if it is a javascript error? We have only encountered this issue after upgrading out project to RN 0.60.4 and react-navigation to 3.11.1. Our code hasn't changed at allbetween the versions.

**Comment by aujisti-ador** [comment]
> If it was a matter of trying to access a prop before it exists, the app should have crashed on all devices, right? The issue is that we have only found out about the crash through the reports sent out from a handful of devices.
> All I'm asking is, how can this be a device dependent issue if it is a javascript error? We have only encountered this issue after upgrading out project to RN 0.60.4 and react-navigation to 3.11.1. Our code hasn't changed at allbetween the versions.

i am facing the same issue.

**Comment by matthamil** [comment]
Can you create a reproducible example for us? @rakibhasan48
