### ISSUE TITLE
Transparent header bottom border visible on transition

### ISSUE THREAD

**Issue by dquessenberry** [react-navigation/react-navigation#6200]
### Current Behavior
I have a screen that displays a transparent header with only a custom back button. The header should not display a bottom border or shadow. I am successfully able to do this by configuring the header styles in the navigationOptions. HOWEVER, upon transitioning, the bottom border becomes visible again.

#### What code are you running and what is happening?

I am configuring the navigationOptions (with everything I can think of) in my screen like so: 

`
static navigationOptions = () => {
    return {
      headerLeft: <HeaderBackButton/>,
      headerTransparent: true,
      headerStyle: {
        borderBottomColor: 'transparent',
        borderBottomWidth: 0,
        shadowColor: 'transparent',
        shadowOpacity: 0,
        shadowOffset: {
          height: 0,
        },
        shadowRadius: 0,
        elevation: 0,
      },
    };
  }
` 

***NOTE: the issue occurs even without the custom headerLeft component.

#### Include a screenshot if it makes sense.

 I made a gif of the transition animation in slow mode on the iOS simulator, which can be seen here: 

![rnav-header-border](https://user-images.githubusercontent.com/10273674/63371639-55b52d80-c339-11e9-8965-1c6d010707f1.gif)

#### What do you expect should be happening?
No bottom border/shadow should be visible on the header when displayed on screen or while transitioning on/off screen. 

### How to reproduce

Create a couple basic screens and navigate from one to the other. On the second screen, include the navigationOptions I have posted above. As mentioned before, the headerLeft component is not necessary and can be removed from my code above - the default Back button also has the same issue.

*** NOTE: The issue has only been verified on iOS. I have not yet tested on Android.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.11.1
| react-native     | 0.60.5
| node             | 12.7.0
| yarn      | 1.17.3

**Comment by dquessenberry** [comment]
Figured out the issue. The borderBottomWidth also has to be set on the previous screen too. In my case, the previous screen (initial screen) had the header set to null in the navigationOptions, but the bottomBorderWidth also has to be set 0 as well. However, I do believe there is a potential bug here because the screen that is transitioning out should maintain the same header, not depend on what the next screen has configured. I suspect there are cases where an undesired effect could occur, particularly if one screen has border and the other is transparent without a border.

**Comment by jjfrutos** [comment]
It still happens not only with the borderBottomWidth. It seems the back button overrides the navigationOptions with the defaultNavigationOptions.

![ezgif-1-3c1df2195f1c](https://user-images.githubusercontent.com/2398936/63909652-b6bcbf80-ca23-11e9-9225-d82fe0f3feee.gif)

**Comment by dquessenberry** [comment]
@jjfrutos, try adding `headerLeft: null` to the navigationOptions for the initial screen (the screen that displays after clicking the back button - the "Pending" screen in your example) or the stack it is in if that makes more sense in your case.
