### ISSUE TITLE
unable to resolve module ../foldername/file.js from app.js

### ISSUE THREAD

**Issue by devika7** [react-navigation/react-navigation#6202]
## The issue tracker is reserved for bug reports only.

If you have a question, feature request, or an idea for improving the library or its related tools, please try one of the following resources:

- [Read the documentation](https://reactnavigation.org/)
- [Post an issue to the website repository if you'd like to see a documentation change](http://github.com/react-navigation/website)
- [Post a feature request to Canny](https://react-navigation.canny.io/feature-requests)
- [Write a RFC if you have ideas for how to implement a feature request](https://github.com/react-navigation/rfcs)
- [Get help on Discord chat (#react-navigation on Reactiflux)](https://discord.gg/4xEK3nD) or [on StackOverflow](https://stackoverflow.com/questions/tagged/react-navigation)
- Search for your issue - it may have already been answered or even fixed in the development branch. However, if you find that an old, closed issue still persists in the latest version, you should open a new issue.

Bugs with react-navigation must be reproducible *without any external libraries that operate on it*. This means that if you are attempting to use Redux or MobX with it and you think you have found a bug, you must be able to reproduce it without Redux or MobX in this report. Redux related issues belong in [react-navigation-redux-helpers](https://github.com/react-navigation/react-navigation-redux-helpers), and we do not have any first-class integration with MobX at the moment.

---

### Current Behavior

I am running the app in expo. The app should perform basic navigator operation, but it says failed to resolve the module. and the files don't exist

### Expected Behavior

- What do you expect should be happening?
- Include a screenshot if it makes sense.

### How to reproduce

link to a dummy snack project - https://snack.expo.io/@naikdevika7/myexpapp
### Your Environment

react": "16.8.3",
<img width="340" alt="Screen Shot 2019-08-21 at 12 41 08 AM" src="https://user-images.githubusercontent.com/5160152/63403234-65218e80-c3ac-11e9-90c9-6965a9a32ffe.png">
 "react-dom": "^16.8.6"
expo": "^34.0.1
"react-navigation": "^3.11.1"

**Comment by satya164** [comment]
Please check your code for incorrect paths. This is unrelated to React Navigation.
