### ISSUE TITLE
 Activetab is not in center when scrollEnabled is true and tabStyle width is set to 'auto'.

### ISSUE THREAD

**Issue by earlyCloud** [react-navigation/react-navigation#6205]
Active tab is not in center when scrollEnabled is true and tabStyle width is set to 'auto'.
For some reason the version of the dependence 'react-native-tab-view' is still 1.4.1. I'm not so sure if the newest 'react-native-tab-view' has fixed this issue but I noticed some PR on it.
### Expected Behavior
Active tab scrolls to center of the view.
### Environment
| software         | version
| ---------------- | -------
| react-navigation | 3.11.1
| react-native     | 0.57.8
| node             | 8.11.4
| npm      | 5.6.0

**Comment by satya164** [comment]
Please use https://github.com/react-navigation/tabs directly
