### ISSUE TITLE
how to using Navigation Service in App.js

### ISSUE THREAD

**Issue by hotaryuzaki** [react-navigation/react-navigation#6206]
I tried using NavigationService in docs and tried this.navigator (in below post), but i cannot use in App.js itself.
Because if i call it in componentDidMount or in function it would call first before ref props in AppNavigator.
How to use it in App.js?

Or the main question is how to using react navigation in App.js for OneSignal onOpened function callback??
especially when the Apps is not yet run.

FYI : im using AppLoading from Expo

--------------------------------------------------------------

The following should work. If it doesn't then it is probably a bug. If it does work, can you find a good place to add this to the documentation?

```
const AppNavigator = StackNavigator(SomeAppRouteConfigs);

class App extends React.Component {
  someEvent() {
    // call navigate for AppNavigator here:
    this.navigator && this.navigator.dispatch({ type: 'Navigate', routeName, params });
  }
  render() {
    return (
      <AppNavigator ref={nav => { this.navigator = nav; }} />
    );
  }
}
```

_Originally posted by @ericvicenti in https://github.com/react-navigation/react-navigation/issues/71#issuecomment-275893178_

**Comment by eriveltonelias** [comment]
hey @hotaryuzaki, 

isn't necessary to be in App.js, because you can do this following on the file who you create the AppContainer from react-navigation.

check this code, will help you.
https://snack.expo.io/@eriveltonelias/navigation-service


more info on docs: https://reactnavigation.org/docs/en/navigating-without-navigation-prop.html#docsNav

**Comment by hotaryuzaki** [comment]
Thanks, I already followed from react navigation page.
But my main problem, I'm using One Signal push notifications in app.js, and I create a deep links for push notifications.

So I declare one signal listener in app.js and deep links function.
When I get one signal params I redirect to intended screen.
If I already open the (app in background), react navigation successful redirected.
But if I'm not open yet, apps will load and open home screen.

How to achieve same result????

**Comment by eriveltonelias** [comment]
Have you tried to use `Linking.getInitialURL()` ?

this will allow you to know the initial url/route of the app.

https://facebook.github.io/react-native/docs/linking

**Comment by diamont1001** [comment]
Have you solved it?

**Comment by epileftro85** [comment]
Did you solve it? I need to redirect to a screen when notification opened

**Comment by hotaryuzaki** [comment]
> Have you solved it?

> Did you solve it? I need to redirect to a screen when notification opened

No.
But I found in other post that it was a bug if we make a nested stack.
Maybe you can try update to latest version, or search a solution for nested stack navigation.
right now I'm on project to update to latest expo version.

**Comment by thegreatzeus** [comment]
> hey @hotaryuzaki,
> 
> isn't necessary to be in App.js, because you can do this following on the file who you create the AppContainer from react-navigation.
> 
> check this code, will help you. https://snack.expo.io/@eriveltonelias/navigation-service
> 
> more info on docs: https://reactnavigation.org/docs/en/navigating-without-navigation-prop.html#docsNav

Thank you so much for the [`navigation-service`](https://snack.expo.io/@eriveltonelias/navigation-service) demo. You are a life-saver!
