### ISSUE TITLE
Navigation drawer (front) - overlayColor opacity goes to 100% when open

### ISSUE THREAD

**Issue by AGIsmail** [react-navigation/react-navigation#6208]
### Current Behavior

Sliding open the drawer or using toggleDrawer to open the drawer causes the overlay to go from 0% to 100% opacity instead of the default maximum of 70%.

<img src="https://user-images.githubusercontent.com/11680600/63547087-57c5ea80-c4f9-11e9-827e-260f8a302cf6.gif" width=248/>

(click image for full resolution)

### Expected Behavior

The open drawer should have the solid overlayColor behind it only reach 70% opacity.

### How to reproduce

[Github repository (master branch)](https://github.com/AGIsmail/rn-nav-issue) to reproduce the issue on Android. The issue persists between the emulator and device, dev and production builds.

Run `npm i` and `react-native run-android` then press the "Toggle Drawer" button or slide the drawer out from the left to the right. 

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.11.1
| react-native     | 0.60.5
| node             | v11.15.0 & v12.9.0
| npm or yarn      |npm v6.10.2

**Comment by AGIsmail** [comment]
I traced it to react-native-gesture-handler/DrawerLayout.js in `_renderOverlay`
```
const overlayOpacity = this._openValue.interpolate({
      inputRange: [0, 1],
      outputRange: [0, 1],
      extrapolate: 'clamp',
});
```

Changing the outputRange from `[0, 1]` to [0, 0.7]` achieves the desired behaviour.

**Comment by AGIsmail** [comment]
Traced outputRange change from 0.7 to 1 in git commit 0f31a2f79f0e96158ad133476a34431d12a5eddf of react-native-gesture-handler.

```
    Remove overlay 70% opacity to allow more flexibility (#629)

    ## Purpose

    Remove the forced 70% opacity overlay to allow more flexibility - for instance if you want 90% instead.

    ## Use

    When declaring overlay background, you could feed it `rgba(255, 255, 255, 0.9)` to achieve a white overlay that is only slightly transparent.
```

Thus, setting `overlayColor: 'rgba(0, 0, 0, 0.7)'` in the createDrawerNavigator configs object restores the old default behaviour.

Can we update the docs [here](https://reactnavigation.org/docs/en/drawer-navigator.html) to reflect this change in the gesture-handler?

**Comment by mukeshsharma1201** [comment]
I am facing the same issue after installing react-native-gesture-handler today.
It was working fine in a project created about a week ago.

**Comment by jsaraiva** [comment]
https://github.com/react-navigation/react-navigation/issues/6208#issuecomment-524091241 

The solution presented by @AGIsmail works like a charm.

**Comment by brentvatne** [comment]
i recommend using the latest version of react-navigation-drawer: https://github.com/react-navigation/drawer - drawer has been re-implemented here to use react-native-reanimated and is more performant

**Comment by dhrupalG** [comment]
kh

**Comment by musadiq-jinbade** [comment]
not able open by swiping in /out drawer only able to open by onpress

**Comment by mukeshsharma1201** [comment]
@musadiq-jinbade Can  you check if you have latest version of `react-native-reanimated` and you have **linked** the library using `react-native link react-native-gesture-handler`?

**Comment by musadiq-jinbade** [comment]
@mukeshsharma1201 Thanks for update 
I have already link all the packages
solution in index.js file:
AppRegistry.registerComponent(appName, () => gestureHandlerRootHOC(App));

**Comment by musadiq-jinbade** [comment]
import {AppRegistry} from 'react-native';
import App from './src/Rightsidebar/Drawer';
import {name as appName} from './app.json';
import { gestureHandlerRootHOC } from 'react-native-gesture-handler'


AppRegistry.registerComponent(appName, () => gestureHandlerRootHOC(App));
