### ISSUE TITLE
Using CustomHeader in navigationOptions.headerBackground also stack the screen component

### ISSUE THREAD

**Issue by zxccvvv** [react-navigation/react-navigation#6209]
### Current Behavior
creating `customHeader` with stacking view also effect the `screen` props,

![image](https://user-images.githubusercontent.com/19633881/63574274-9919d100-c5b1-11e9-98aa-089e6bce3ed5.png)

i need to add `marginTop:75` in root View of every screen component to make it showing below `customHeader`

```const Home = () => <CustomText style={{marginTop:75}}>Sample</CustomText>;```

![image](https://user-images.githubusercontent.com/19633881/63574757-b9965b00-c5b2-11e9-9440-369d7e9a7dba.png)

### Expected Behavior

Should be at the bottom of `header` vice-versa even thought i need to styling the `header` height if the custom `headerBackground` height is different from default `header` height, 

> I used `headerBackground` instead of `header` because i want to keep all props of navigationOptions such as `title, styling, etc`

### How to reproduce

```
import { createAppContainer, createStackNavigator } from "react-navigation";
const Home = () => <CustomText>Sample</CustomText>; // using regular <Text></Text>
const StackHome = createStackNavigator({
  InputNIK:{
    screen:Home,
    navigationOptions: ({ navigation }) => ({
      headerTransparent:true,
      headerStyle:{height:75, textAlign:'center'},
      headerTintColor:'white',
      title:'Custom Header',
      headerBackground:<View>
        <View style={{height:75, backgroundColor:ListColor.goldenrod, position:'absolute', top:0, left:0, right:-12.5, borderBottomRightRadius:50}}/>
        <View style={{height:70, backgroundColor:ListColor.red_800, position:'absolute', top:0, left:0, right:-10, borderBottomRightRadius:50}}/>
      </View>,
    }),
  },
})
```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^3.11.1
| react-native     | 0.60.5
| node             | v10.16.0
| npm              | 6.4.1
| Yarn | 1.17.3

_Have tried create custom `headerBackground` without `absolute` position also stack the main screen so i think it's not related of `absolute`_

**Comment by n76i** [comment]
I have removed `headerTransparent:true` and it work, I don't known why they use this code on document :(
