### ISSUE TITLE
When I click on an active bottomNavigatorTab it should jump to the top of the content, I already built the core of it, and now I just need to call the function that jumps to the FlatList top.

### ISSUE THREAD

**Issue by mrkkrly** [react-navigation/react-navigation#6211]
Navigator:

const tabBarOnPress = ({ navigation, defaultHandler }) => {
    const { isFocused, state, goBack } = navigation;
    if (isFocused()) {
        console.log("IT IS FOCUSED")
        if (state.routes.length > 1) {
            for (let i = 0; i < state.routes.length - 1; i += 1) {
                goBack();
            }
        } else {
            // I SHOULD CALL THE FUNCTION HERE
        }
    } else {
        console.log("THIS IS JUST DEFAULT")
        defaultHandler();
    }
};

  const BottomNav = createBottomTabNavigator({
    ....

  }, {
    tabBarOptions:{
      activeTintColor:"#69E191",
      inactiveTintColor:"grey",
      style:{
        borderTopColor: '#fff',
        backgroundColor:"#fff",
      },
    },
    defaultNavigationOptions: {
      header: null,
      tabBarOnPress,
    }
  });
Screen with FlatList:

jumpToTop = () => {
    this.flatListRef.scrollToOffset({ animated: true, offset: 0 })
  }

<FlatList
              ref={(ref) => { this.flatListRef = ref; }}
              showsVerticalScrollIndicator={false}
              data={this.state.dataSource}
              refreshing={this.state.refreshing}
              onRefresh={this.handleRefresh}
              extraData={this.state}
              onEndReached={this.handleLoadMore}
              ItemSeparatorComponent={RenderSeparator}
              onEndReachedThreshold={0.05}
              renderItem={({item}) => ( ... ) ...

**Comment by mgarabedian** [comment]
I came across this need as well. You need to use tabBarOnPress via navigationOptions, along with navigation state params. Here's what the code in one of my tab components looks like:

```
  static navigationOptions = ({ navigation }) => {
    return {
      tabBarLabel: 'Label Name',
      tabBarOnPress: ({navigation, defaultHandler} ) => {
        if (navigation.isFocused()) {
          navigation.state.params.scrollToTop()
        }
        defaultHandler()
      }
    }
  }

  componentWillMount() {
    this.props.navigation.setParams({
      scrollToTop: this.scrollToTop,
    });
  }

  scrollToTop = () => {
    console.log("Use the FlatList ref and scroll to top.")
  }

```

**Comment by brentvatne** [comment]
see https://reactnavigation.org/docs/en/scrollables.html
