### ISSUE TITLE
getParam() is not a function error for custom header

### ISSUE THREAD

**Issue by mifozski** [react-navigation/react-navigation#6212]
### Current Behavior

When calling `navigation.getParam()` from `HeaderProps` object passed to a custom header component with any argument, js crashes with the error that says that getParam is not a function. I understand that if I don't have any params set, it should return either undefined or default value, but `getParam` function itself is marked as non-optional in react-navigation.d.ts, so it's clearly an error.

### Expected Behavior

Calling `getParam()` shouldn't crash js.

### How to reproduce

https://snack.expo.io/@mifoz/e15f6c

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.11.1
| react-native     | 0.60.3
| node             | 10.15.3
| yarn      | 1.17.3

**Comment by eriveltonelias** [comment]
Hi @mifozski 

`header` prop are avaliable only on `navigationOptions`
you can do something like this https://snack.expo.io/@eriveltonelias/getparam-is-not-a-function-for-custom-header


or you can use all props avaliable for header https://reactnavigation.org/docs/en/stack-navigator.html#stacknavigatorconfig

**Comment by aldrinjenson** [comment]
Hey, just use route.params.property_name_you_want_to_access_from_the_object_passed  instead for react navigation v5.
Note that, you need to accept route as an additional parameter in the function along with navigation.
[Use this for extra reference](https://reactnavigation.org/docs/params/)

**Comment by udayarajurs** [comment]
> route.params

tanks so much it works for me
