### ISSUE TITLE
Error occur after install and link @react-version 0.59.9

### ISSUE THREAD

**Issue by IamMHC** [react-navigation/react-navigation#6213]
node_modules\react-native-gesture-handler\android\src\main\java\com\swmansion\gesturehandler\react\RNGestureHandlerEnabledRootView.java:10: error: cannot find symbol
import androidx.annotation.Nullable;

**Comment by mushinz** [comment]
@IamMHC this should be related to the new version of react-native-gesture-handler which have introduced some bug

**Comment by AfrazHussain** [comment]
Make sure you use the https://github.com/mikehardy/jetifier package and migrate your non-AndroidX support packages to AndroidX. Download it as `yarn add --dev jetifier` and then use `npx jetify` before running `react-native run-android/ios`.

**Comment by SamiChab** [comment]
Same as [this issue](https://github.com/kmagiera/react-native-gesture-handler/issues/749)

**Comment by SamiChab** [comment]
I finally made it work...
What I did:
- unlinked react-native-gesture-handler
- uninstalled and reinstalled react-native-gesture-handler
- linked react-native-gesture-handler

Then I just followed some of the installation steps of the [react navigation docs](https://reactnavigation.org/docs/en/getting-started.html)
- `yarn add --dev jetifier`
- in package.json->scripts, add `"postinstall": "jetifier -r"`
- `yarn postinstall`
