### ISSUE TITLE
goBack() call try to re-render and trigger error on parent screen.

### ISSUE THREAD

**Issue by thomaslc66** [react-navigation/react-navigation#6214]
## The issue tracker is reserved for bug reports only.

If you have a question, feature request, or an idea for improving the library or its related tools, please try one of the following resources:

- [Read the documentation](https://reactnavigation.org/)
- [Post an issue to the website repository if you'd like to see a documentation change](http://github.com/react-navigation/website)
- [Post a feature request to Canny](https://react-navigation.canny.io/feature-requests)
- [Write a RFC if you have ideas for how to implement a feature request](https://github.com/react-navigation/rfcs)
- [Get help on Discord chat (#react-navigation on Reactiflux)](https://discord.gg/4xEK3nD) or [on StackOverflow](https://stackoverflow.com/questions/tagged/react-navigation)
- Search for your issue - it may have already been answered or even fixed in the development branch. However, if you find that an old, closed issue still persists in the latest version, you should open a new issue.

Bugs with react-navigation must be reproducible *without any external libraries that operate on it*. This means that if you are attempting to use Redux or MobX with it and you think you have found a bug, you must be able to reproduce it without Redux or MobX in this report. Redux related issues belong in [react-navigation-redux-helpers](https://github.com/react-navigation/react-navigation-redux-helpers), and we do not have any first-class integration with MobX at the moment.

---

### Current Behavior

- What code are you running and what is happening?
I have 2 screens, parent and child. child display a react-native-map with a ref.

- Include a screenshot if it makes sense.
![image](https://user-images.githubusercontent.com/9827392/63649015-7665f480-c738-11e9-8674-7614920fc043.png)

I'm getting this warningwhen going back using the left arrow in the header.
![image](https://user-images.githubusercontent.com/9827392/63649130-12443000-c73a-11e9-9887-63920d3b8c57.png)

When i go back, the method onMapReady or any other method should not be triggered. I'm leaving the map screen to go back to parent, but it seems that something is triggered again as the warning say it cannot update an unmounted component.

This method is called when the map is rendered, normaly not when i'm changing screen.

### Expected Behavior
- What do you expect should be happening?
I expect my child component not to enter in a re-rendering phase as i'm leaving it.
So it should not enter my onReady function from my MapView component, because the MapView component shouldn't be rendering.

- Include a screenshot if it makes sense.

### How to reproduce

- You must provide a way to reproduce the problem. If you are having an issue with your machine or build tools, the issue belongs on another repository as that is outside of the scope of React Navigation.
To reproduce. 
Create to screen, use react-navigation, and react-native-maps.
first screen a button to a second. second screen a map with a ref and a goBack() call.
onMapReady needs to call an action like in the first picture.

- Either re-create the bug on [Snack](https://snack.expo.io) or link to a GitHub repository with code that reproduces the bug.
- Explain how to run the example app and any steps that we need to take to reproduce the issue from the example app.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |
3.11
| react-native     |
0.59.9
| node             |
12.9.0
| npm or yarn      |
yarn 1.17.3

**Comment by eriveltonelias** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.
you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.
please create a new issue with this and i'd be happy to review it!
