### ISSUE TITLE
headerTransparent to true should contain a space instead of hiding the header

### ISSUE THREAD

**Issue by swingywc** [react-navigation/react-navigation#6218]
### Current Behavior
I wish to make a transparent header that imageBackground can show behind it.

My coding is here:

    import React, { PureComponent } from 'react';
    import { ImageBackground, TouchableOpacity, View, Text } from 'react-native';
 
    class LoginScreen extends PureComponent {
      static navigationOptions = {
        headerTransparent: true,
        headerRight: (<TouchableOpacity onPress={() => {}}><Text>O</Text></TouchableOpacity>)
      };

      render() {
        return (
          <ImageBackground style={{flex: 1}} source={require('@assets/images/login-bg.jpg')} resizeMode="cover">
            <View>
              <Text style={{fontSize: 30}}>This is login</Text>
            </View>
          </ImageBackground>
        );
      }
    }

    export default LoginScreen;

What it show in emulator is like this:
<img width="436" alt="螢幕快照 2019-08-27 下午6 02 20" src="https://user-images.githubusercontent.com/9659080/63762188-fb960880-c8f4-11e9-9982-cd7f661817b6.png">

### Expected Behavior

I expect the header should contain a space. `headerTransparent` should make the header background transparent instead of a behavior like this.(It's like removing the header now)
 
What I expected it is like this:
![image](https://user-images.githubusercontent.com/9659080/63762562-9d1d5a00-c8f5-11e9-9811-14faa10fd42d.png)

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^3.12.0
| react-native     | 0.60.5
| node             | 12.3.1
| npm or yarn      | 6.9.0

Thanks for any helping hands.

**Comment by satya164** [comment]
This is expected behavior. React Navigation cannot know where you want to add a spacer and cannot insert a spacer in a view you're rendering.

**Comment by swingywc** [comment]
Sorry that I don't understand your meaning. I am not adding a spacer, I just want the header to be here while its background is transparent. Do you mean `headerTransparent` will remove the header ? If yes, what is the difference between setting `header: null` and `headerTransparent: true` ?

**Comment by sallar** [comment]
@satya164 Im sorry but how is this expected? `headerTransparent` clearly says that header should be `transparent` and not change height completely

**Comment by satya164** [comment]
it doesn't change its height, it's positioned absolutely over your content. if it's not positioned above your content, you can't see content below it whether or not it's transparent.

your content includes the image background as well as your text. react navigation cannot distinguish between them and cannot predict which content you want below the header and which content you don't. you want only the image background below and text above, so you need to take care of that yourself.
