### ISSUE TITLE
Install 3.12.1, Build Error Unable to resolve react-lifecycles-compat

### ISSUE THREAD

**Issue by dl-husky73** [react-navigation/react-navigation#6222]
### Current Behavior

- Build of a project which has been stable with previous versions
![snippet1](https://user-images.githubusercontent.com/47721681/63785229-fa95b480-c8bd-11e9-97ba-fdeebe04fabf.PNG)

### Expected Behavior

Should compile fine, always has

### How to reproduce

- It is on build.  
Error: bundling failed: Error: unable to resolve module react-lifecycles-compat.
Comes from createBottomTabNavigator

I understand react-lifecycles-compat but don't understand why this specific upgrade in React-Navigation triggered this build error.   Is there something else going on?   Do I have to install react-lifecycles-compat?  I thought that compatibility goes away soon?  

### Your Environment

| software         | version
| ---------------- | -------
react-navigation: 3.12.1
react-native: 60.5
node: 11.6
npm: 6.10.2

**Comment by subbotinb** [comment]
Try this:
1. Clear watchman watches: `watchman watch-del-all`.
2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.
4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.
Or simply `expo start -c` if you're using Expo.

**Comment by izhan25** [comment]
@subbotinb answer resolved my issue. I am not using expo but it just resolved the issue. Thanks @subbotinb

**Comment by stevematdavies** [comment]
Same issue on react-navigation 3.13.0, all solutions above fail, now we can no longer release the product on time. 

This is a fairly critical issue isn't it?

**Comment by ohhyunjin** [comment]
@subbotinb answer actually solved my issue as well.
