### ISSUE TITLE
Why createBottomTabNavigator inside a nested modal stack doesn't work?

### ISSUE THREAD

**Issue by scerelli** [react-navigation/react-navigation#6224]
### Current Behavior
given

```
const screens = navigationRegistry.getScreens();
const modals = navigationRegistry.getModals();
```

where screens and modals are objects like:
```
{
  screenName: {
    screen: 'name'
  }
}
```

I expect this code to work:
```
const Root = createStackNavigator({
 screenStack:  createStackNavigator({
  ...screens,
  main: {
    screen: createBottomTabNavigator(
       {
         tab1: Component,
         tab2: Component,
         tab3: Component,
         tab4: Component,
         tab5: Component,
       },
       {
         tabBarComponent: HomeBottomBar,
       },
     ),
   }
  }
}),
 ...modals,
}, {
  mode: 'modal',
  initialRouteName: 'aScreenInsideTheScreensConst',
});
```
instead i get that `main` key is not defined.

I also tried to put tabs at the same level of modals, the app runs but the result is that
everything acts like a modal, also when you navigate somewhere it automatically pops after 1 second:
```
const Root = createStackNavigator({
  screenStack:  createStackNavigator({
    ...screens
  }),
  main: {
   screen: createBottomTabNavigator(
      {
        tab1: Component,
        tab2: Component,
        tab3: Component,
        tab4: Component,
        tab5: Component,
      },
      {
        tabBarComponent: HomeBottomBar,
      },
    ),
  }
 }
 ...modals,
}, {
  mode: 'modal',
  initialRouteName: 'aScreenInsideTheScreensConst',
});
```
to navigate i'm using the `dispatcher` plus `navigationActions + stackActions` not normal props injection.

### Expected Behavior
I expect the first block of code to actually works instead it reports an error regarding the `main` key not being found but it's there!!

### How to reproduce
Use the code block I posted above.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.11.1
| react-native     | 0.59.10
| node             | v11.12.0
| npm or yarn      | 1.15.2

**Comment by scerelli** [comment]
Ok here is the repo:
https://github.com/scerelli/testReactNavigation

what i noticed is that the problem is not in `createBottomTabNavigator` but in resetting to a subRoute.

it happens here:
https://github.com/scerelli/testReactNavigation/blob/master/core/navigation/ReactNavigationManager.ts#L67

triggered from here:
https://github.com/scerelli/testReactNavigation/blob/master/Navigator.tsx#L16

**Comment by brentvatne** [comment]
https://reactnavigation.org/docs/en/stack-actions.html#reset

`key - string or null - optional - If set, the navigator with the given key will reset. If null, the root navigator will reset.`

reset is a bit difficult to use but the important thing to pay attention to here is the key

**Comment by scerelli** [comment]
thanks @brentvatne i think that the problem here is that to reset to a key that is under a parent route we have to specify the parent in the reset action. I suppose it may be worth to add it to the stack-actions documentation page, what do you think?
