### ISSUE TITLE
Error: This navigator has both navigation and container props, so it is unclear if it should own its own state. Remove props: "theme" if the navigator should get its state from the navigation prop. If the navigator should maintain its own state, do not pass a navigation prop.

### ISSUE THREAD

**Issue by kevin871223** [react-navigation/react-navigation#6225]
## The issue tracker is reserved for bug reports only.
This error is located at:
    in NavigationContainer (at SceneView.js:9)
    in SceneView (at StackViewLayout.tsx:899)
    in RCTView (at View.js:35)
    in View (at StackViewLayout.tsx:898)
    in RCTView (at View.js:35)
    in View (at StackViewLayout.tsx:897)
    in RCTView (at View.js:35)
    in View (at createAnimatedComponent.js:151)
    in AnimatedComponent (at StackViewCard.tsx:106)
    in RCTView (at View.js:35)
    in View (at createAnimatedComponent.js:151)
    in AnimatedComponent (at screens.native.js:71)
    in Screen (at StackViewCard.tsx:93)
    in Card (at createPointerEventsContainer.tsx:95)
    in Container (at StackViewLayout.tsx:982)
    in RCTView (at View.js:35)
    in View (at screens.native.js:101)
    in ScreenContainer (at StackViewLayout.tsx:394)
    in RCTView (at View.js:35)
    in View (at createAnimatedComponent.js:151)
    in AnimatedComponent (at StackViewLayout.tsx:384)
    in PanGestureHandler (at StackViewLayout.tsx:377)
    in StackViewLayout (at withOrientation.js:30)
    in withOrientation (at StackView.tsx:103)
    in RCTView (at View.js:35)
    in View (at Transitioner.tsx:267)
    in Transitioner (at StackView.tsx:40)
    in StackView (at createNavigator.js:81)
    in Navigator (at createKeyboardAwareNavigator.js:12)
    in KeyboardAwareNavigator (at createAppContainer.js:451)
    in NavigationContainer (at App.js:36)
    in Provider (at App.js:35)
    in App (at renderApplication.js:40)
    in RCTView (at View.js:35)
    in View (at AppContainer.js:98)
    in RCTView (at View.js:35)
    in View (at react-native-root-siblings/index.js:34)
    in RootSiblingsWrapper (at AppContainer.js:112)
    in RCTView (at View.js:35)
    in View (at AppContainer.js:115)
    in AppContainer (at renderApplication.js:39)

This error is located at:
    in NavigationContainer (at App.js:36)
    in Provider (at App.js:35)
    in App (at renderApplication.js:40)
    in RCTView (at View.js:35)
    in View (at AppContainer.js:98)
    in RCTView (at View.js:35)
    in View (at react-native-root-siblings/index.js:34)
    in RootSiblingsWrapper (at AppContainer.js:112)
    in RCTView (at View.js:35)
    in View (at AppContainer.js:115)
    in AppContainer (at renderApplication.js:39)

| software         | version
| ---------------- | -------
| react-navigation |3.12.1
| react-native     |0.60.5
| node             |10.16.3
| npm or yarn      |npm

**Comment by usmansbk** [comment]
multiple components are probably using `createAppContainer`. Make sure there's only a single component using it.

**Comment by Mustafa-eksi** [comment]
I have same problem

**Comment by JorgeosorioDev** [comment]
Mi solucion fue la siguiente:


1. Cree la funcion.

    register(){
        this.props.navigation.navigate('Register');
    }

2.  Llamado a la funcion
onPress={this.register}


3. Dentro del constructor

	constructor(props) {
        super(props);         

        this.register = this.register.bind(this);             

    }

**Comment by brentvatne** [comment]
update to the latest version of react-navigation@3

**Comment by lylest** [comment]
import * as React from 'react';
import { NavigationContainer } from '@react-navigation/native';
import { createDrawerNavigator } from '@react-navigation/drawer';
import Profile from '../screen/Profile'
import StackNavigator from './StackNavigator'


const Drawer = createDrawerNavigator()



export default function App() {
    return (
      <NavigationContainer>
        <Drawer.Navigator initialRouteName="StackNavigator">
          <Drawer.Screen name="StackNavigator" component={()=><StackNavigator />} />
          <Drawer.Screen name="Profile" component={Profile} />
         
        </Drawer.Navigator>
      </NavigationContainer>
    );
  }
