### ISSUE TITLE
Back button overrides navigationOptions with defaultNavigationOptions

### ISSUE THREAD

**Issue by jjfrutos** [react-navigation/react-navigation#6228]
### Current Behavior

When back() is fired, the current navigationOptions of the component are overrided by the defaultNavigationOptions.

![ezgif-1-3c1df2195f1c](https://user-images.githubusercontent.com/2398936/63910100-ab6a9380-ca25-11e9-8ee2-42d879557e77.gif)

### Expected Behavior

The navigationOptions set in the component have to persist till the end.

### How to reproduce

Just define a backgroundColor in the defaultNavigationOptions. Then change it using the static navigationOptions pattern in a pushed component. 

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.11.1
| react-native     | 0.60.5
| node             | 8.15.1
| npm or yarn      | npm

**Comment by matthamil** [comment]
Hello! Can you create a reproducible example in a public GitHub repo or as a [Snack](https://snack.expo.io)?

**Comment by brentvatne** [comment]
use `headerBackground` and `headerBackgroundTransitionPreset` if you want different behavior for this. see https://reactnavigation.org/docs/en/stack-navigator.html#headerbackgroundtransitionpreset

see examples in https://github.com/react-navigation/stack/blob/1.0/example/src/HeaderBackgrounds.js
