### ISSUE TITLE
Using this.props.navigation.push  method not trigger componentWillUnmount

### ISSUE THREAD

**Issue by sasaluo** [react-navigation/react-navigation#6230]
my react-navigation verision is 3.8.1,and the problem i have encountered is here:
when i use  this.props.navigation.navigate('FilterIndex',{from:'series',categoryId:typeList[this.state.rowIndex].intent,rowIndex:rowIndex}), from A to B, it will trigger componentWillUnmount method in A,but when i am in B,i can not use DeviceEventEmitter.addListener which used to listen remote control event.
 When i switch to this.props.navigation.push('FilterIndex',{from:'series',categoryId:typeList[this.state.rowIndex].intent,rowIndex:rowIndex})  , it will not trigger componentWillUnmount method in A , so where is the problem, i need both
 componentWillUnmount  in Aand  DeviceEventEmitter.addListener  in B

**Comment by matthamil** [comment]
Hello! Can you create a reproducible example in a public GitHub repo or as a [Snack](https://snack.expo.io)? Code snippets are great, but a cloneable repo that has only the parts necessary to reproduce your issue is even better. Thanks!

**Comment by matthamil** [comment]
If you are adding routes to a stack, the previous route does not unmount. I believe all screens in the stack are still in memory until the stack is reset or re-instantiated. Going back however should trigger an unmount.
