### ISSUE TITLE
stack -> tabs -> stacks: how do I possibly go back to the previous screen?

### ISSUE THREAD

**Issue by rwest88** [react-navigation/react-navigation#6233]
I've been at this for several days, through the docs and many of these threads...I know the answer must be out there! I think this is a very simple question so I'm trying to phrase it as such--at a high level--and maybe get a general insight into this pattern.  My current setup:

- MainStackNav
----- MainTabNav
---------- TabStack1
----------------- screen: Bob
----------------- screen: Alice
---------- TabStack2
----------------- screen: Jeremy
----------------- screen: Grace
----- LoginStackNav

The beauty of this setup so far is that screens `Bob` and `Alice` are aware of `Jeremy` and `Grace`.  That is if I'm in `Bob`, I can use `props.navigation.navigate('Grace')`, and `TabStack2` will get highlighted in the bottom tab bar, telling me what general realm I'm in.  I also like (and want to keep) the default behavior of pressing `TabStack2`, which takes me to the initial route of that stack, `Jeremy`.

My problem is that if I navigate to `Grace` from `Bob` and hit the back button, I'm taken to `Jeremy`, but I want `Bob`--the previous screen in history. (That was my other hope when nesting `MainTabNav` inside `MainStackNav`.)

So, how might I go about fixing this? Do I need to completely replace the back button and keep a separate stack history in a global store? ...If those things are even possible? I'm keeping in mind I need the tab bar to highlight the screen's respective tab. I know this is possibly a big task but I can only imagine someone's done it, so I didn't want to overwhelm with a code example right away.

**Comment by brentvatne** [comment]
hi there! this is a question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.
