### ISSUE TITLE
Dark Mode - White background on Android Keyboard

### ISSUE THREAD

**Issue by smeekmeister** [react-navigation/react-navigation#6235]
Using react-navigation in dark mode by providing the theme prop in app container, which is picked up from redux state theme.
Everything works very nicely with all dark backgrounds.
Added bonus is that also the Android keyboard is now showing up dark, previously not possible to configure (TextInput keyboard appearance only works for iOS). However, the android keyboard seems to be contained in a view (I'll call it keyboard container view) and that view is still white. The resulting behaviour on Focus is a brief white flash because the keyboard container view is already rendered upfront with keyboard height/width, before the actual keyboard slides up. Same behaviour when the keyboard is closed on blur.

```js
const container = (
            <AppContainer
                theme={theme.mode}
                onNavigationStateChange={(prevState, currentState) => {
                    const currentScreen = this.getActiveRouteName(currentState)
                    const prevScreen = this.getActiveRouteName(prevState)
                    if (prevScreen !== currentScreen) {  firebase.analytics().setCurrentScreen(currentScreen) }
                }}
                ref={(ref) => { this.navigator = ref }}
                screenProps={{
                    theme,
                    tabLabelToday: translate(Texts.TabLabelToday),
                    tabLabelSearch: translate(Texts.TabLabelSearch),
                    tabLabelShop: translate(Texts.TabLabelShop),
                    tabLabelDelivery: translate(Texts.TabLabelDelivery),
                    tabLabelProfile: translate(Texts.TabLabelProfile),
                }}
            />
        )
```js

**Comment by brentvatne** [comment]
themes in react-navigation are only meant to theme navigation that it controls. the rest is dependent on the user
