### ISSUE TITLE
Can't use createMaterialTopTabNavigator with react-native@0.61.0-rc.0 (ViewPagerAndroid + old dependencies)

### ISSUE THREAD

**Issue by pedrolopes10** [react-navigation/react-navigation#6236]
Hi there,

As already was reported here, react-navigation dependencies (react-navigation-tabs and react-navigation-stack) needs to be upgraded. ViewPagerAndroid has now been extracted (not a warning now).

I've already tried the TEMP solution of yarn resolutions and no success.

Thanks

**Comment by pedrolopes10** [comment]
v4

**Comment by pallavikhtri25** [comment]
@pedrolopes10 i have upgraded dependency Below mentioned is package.json still issue persist
![image](https://user-images.githubusercontent.com/72016802/95843960-f8aedf00-0d65-11eb-9bda-871d09617350.png)

i have upgraded react-native-tab-view manually as well 
rm -rf /tmp/metro-*
npx react-native start -- --reset-cache

still same error 
![image](https://user-images.githubusercontent.com/72016802/95844508-9dc9b780-0d66-11eb-82ce-8c07e4df35dd.png)

**Comment by pallavikhtri25** [comment]
@pedrolopes10 i have upgraded dependency Below mentioned is package.json still issue persist
![image](https://user-images.githubusercontent.com/72016802/95843960-f8aedf00-0d65-11eb-9bda-871d09617350.png)

i have upgraded react-native-tab-view manually as well 
rm -rf /tmp/metro-*
npx react-native start -- --reset-cache

still same error 
![image](https://user-images.githubusercontent.com/72016802/95844508-9dc9b780-0d66-11eb-82ce-8c07e4df35dd.png)
