### ISSUE TITLE
I controll the tabbar hide or show with 'tabBarVisible', but the tabbar show or hide flashed and  no animation

### ISSUE THREAD

**Issue by AroZhou** [react-navigation/react-navigation#6239]
When I open or close the drawer, tabbar will be hide or show. Here are my thoughts and it works, but tabbar is flashed show or hide.

In drawer component, I set params 'tabBarVisible' in callback
```
export default (self) => (
  <DrawerLayout
    ref={drawer => this.drawer = drawer}
    drawerPosition={DrawerLayout.positions.Left}
    drawerType='back'
    renderNavigationView={() => SideContentView(self)}
    drawerLockMode='locked-closed'
    drawerWidth={width * 0.75}
    onDrawerOpen={() => self.props.navigation.setParams({tabBarVisible: false})}
    onDrawerClose={() => self.props.navigation.setParams({tabBarVisible: true})}
  >
    {MainContentView(self)}
  </DrawerLayout>
);
```

In main, I change navigationOptions with params
```
class Trade extends Component {

  static navigationOptions = ({navigation}) => {
    return {
      tabBarVisible: navigation.state.params ? navigation.state.params.tabBarVisible : true
    }
  };

  render() {
    return view(this);
  }

}
```

Is there any params can be set in navigationOptions which can make tabbar show or hide animated?

**Comment by matthamil** [comment]
I don't believe the show/hide API for the tab bar is meant to include an animation out-of-the-box. The intent behind showing/hiding the tab bar might be to navigate into a stack from a tab route. This lets you hide the tab bar when you might not want the user to switch between tabs from some nested route.

You could use your own tab bar component and provide a means to animate it into/out of view.
