### ISSUE TITLE
Missing changelog for v4.0.0

### ISSUE THREAD

**Issue by rumax** [react-navigation/react-navigation#6241]
### Current Behavior

- Open [reactnavigation versions](https://reactnavigation.org/en/versions.html)
- No changelog for [v4.0.0](https://www.npmjs.com/package/react-navigation), which is the latest released version today

<img width="315" alt="Screenshot 2019-09-01 at 14 00 09" src="https://user-images.githubusercontent.com/2707180/64076124-dcb2c000-ccc0-11e9-915a-35bd219aed5c.png">

### Expected Behavior

- Changelog for v4.0.0 is available same as for `3.11.1`, 3.11.0, etc.
- [CHANGELOG](https://github.com/react-navigation/react-navigation/blob/master/CHANGELOG.md) is updated according to changes in new releases, because V4 is a major change and should be documented according to:

> All notable changes to this project will be documented in this file.

statement in changelog

<img width="997" alt="Screenshot 2019-09-01 at 13 59 11" src="https://user-images.githubusercontent.com/2707180/64076117-bbea6a80-ccc0-11e9-9cfd-cac79893ba0d.png">

**Comment by spyshower** [comment]
Unprofessional? Yep

**Comment by Ashkan-Oliaie** [comment]
you could just check the docs , so straight forward,took me 10 mins to realize what has changed 😃 
just give them some time 😄

**Comment by tapz** [comment]
The change logs says that you still need to import react-navigation. Is that really necessary as it basically contains nothing? All imports work from react-navigation-stack.

**Comment by satya164** [comment]
The release notes are available at https://github.com/react-navigation/react-navigation/releases

@spyshower no need to be rude. It's an open source project you're using for free. If there's a mistake, you can send a pull request to fix it.

@tapz You still need to import `createAppContainer` from `react-navigation` (or `@react-navigation/native`). It's not exported from `react-navigation-stack`. If there's a mistake, can you point me there so I can take a look?

**Comment by tapz** [comment]
@satya164 Eslint in VS Code gives an error when trying to import createAppContainer from react-navigation, but no error when importing from react-navigation-stack.

**Comment by satya164** [comment]
There is something wrong with the ESLint config? Have you run the code?

**Comment by antgel** [comment]
No blog post either. If GitHub Releases is now the destination for release information, at least a blog post stating that would be welcome.
