### ISSUE TITLE
Error with contentComponent with react-navigation-drawer on version 4.x

### ISSUE THREAD

**Issue by outaTiME** [react-navigation/react-navigation#6244]
Hi,
today i update to the new version of react-navigation and im unable to get work the custom content component for the drawer navigator (its working on last 3.x version), propably something update but not documented, here the snippet:

```js
import { createDrawerNavigator, DrawerItems } from 'react-navigation-drawer';
// ...
const MainDrawer = createDrawerNavigator(allowed_routes, {
  contentComponent: props => (
    <ScrollView>
      <DrawerItems {...props} />
      <Text>Your Own Footer Area After</Text>
    </ScrollView>
  ),
  unmountInactiveRoutes: true
});
// ...
```

here the error:

![IMG_3703](https://user-images.githubusercontent.com/140472/64082222-fd3f4200-cce1-11e9-9186-174827c58182.PNG)

Note: if i remove the contentComponent everything works as expected

Thanks !!!

**Comment by satya164** [comment]
Sorry for the trouble. I think it should be `DrawerNavigatorItems` instead of `DrawerItems`. I have updated the docs. If there's still an error, please open a new issue.

**Comment by outaTiME** [comment]
Yup, using `DrawerNavigatorItems` works as expected, thanks for your time !!!

**Comment by ali-hellani** [comment]
You saved my day. I was struggling with this for hours.
