### ISSUE TITLE
Unhandled JS Exception: `HeaderStyleInterpolator` has been removed

### ISSUE THREAD

**Issue by johanquiroga** [react-navigation/react-navigation#6246]
The App never starts and this error appears:

![image](https://user-images.githubusercontent.com/22845267/64083913-4f389580-cceb-11e9-958a-24ed71cba2b3.png)

I'm creating the AppContainer like this:

```js
import { createAppContainer, createSwitchNavigator } from 'react-navigation';

import { AuthLoading as AuthLoadingScreen, AuthStack } from './screens/Auth';

const AppNavigator = createSwitchNavigator(
  {
    AuthLoading: AuthLoadingScreen,
    Auth: AuthStack,
    // App: AppDrawer,
  },
  {
    initialRouteName: 'AuthLoading',
  },
);

export default createAppContainer(AppNavigator);
```

The AuthLoading is a ReactNative component that renders a Loading indicator while it checks for the user auth state.

The AuthStack is created like this:

```js
import { createStackNavigator } from 'react-navigation-stack';

// Auth Screens
import PhoneNumber from './PhoneNumber';
// import SmsCode from './SmsCode';
// import UserInfo from './UserInfo';

// Theme
import { Colors } from '../../theme';

const AuthStack = createStackNavigator(
  {
    Phonenumber: {
      screen: PhoneNumber,
    },
    // SmsCode: {
    //   screen: SmsCode,
    // },
    // UserInfo: {
    //   screen: UserInfo,
    // },
  },
  {
    initialRouteName: 'Phonenumber',
    cardStyle: {
      backgroundColor: Colors.whitePrimary,
    },
    defaultNavigationOptions: {
      header: null,
    },
  },
);
```

### Environment

| software         | version
| ---------------- | -------
| react-navigation | ^4.0.0
| react-native     |0.60.5
| node             |10.16.0
| yarn      |1.17.3

**Comment by satya164** [comment]
Can you provide a reproducible demo? Are you importing `HeaderStyleInterpolator` somewhere?

**Comment by johanquiroga** [comment]
So, I tried installing it in a clean project and it worked, I was hoping that you maybe could point me in some direction as for what that error means or where it could be happening.

I'm not importing `HeaderStyleInterpolator` anywhere.

If I use the 3.x version everything works perfectly.

**Comment by johanquiroga** [comment]
I found that I was indeed importing `HeaderStyleInterpolator` in a component that wasn't being used so that's why I couldn't find it. Sorry to bother.
