### ISSUE TITLE
Issue with DrawerLayoutAndroid

### ISSUE THREAD

**Issue by Ta-Boy** [react-navigation/react-navigation#6247]
I used the DrawerLayoutAndroid component in a StackNavigator, and the openDrawer method did not open drawer properly.  In addition when i push to another page and then go back, the drawer works well.

### Current Behavior

The specific phenomenon is that only black masks are displayed, drawer menu won't show, but the drawer menu can be opened by gesture.

### Code
`class YCHomeExaminePlanViewController extends Component {

    constructor(props) {
        super(props);

        // 构建列表数据
        this.state = {
            drawerVisible: false,
        };
    }

    componentWillUnmount() {
        this._navListener.remove();

        BackHandler.removeEventListener('hardwareBackPress', this.handleBack.bind(this));
    }

    handleBack() {
        if (this.state.firstClick && this.state.firstClick + 2000 >= Date.now()) {
            //最近2秒内按过back键，可以退出应用。
            BackHandler.exitApp();
        } else {
            this.state.firstClick = Date.now();
            ToastAndroid.show('再按一次退出应用', ToastAndroid.SHORT);
            return true;
        }
    }

    render() {
        return (
            <DrawerLayoutAndroid
                ref='drawer'
                drawerWidth={310}
                drawerPosition={DrawerLayoutAndroid.positions.Right}
                renderNavigationView={this.renderDrawerFilterView.bind(this)}
                onDrawerOpen={() => {
                    this.state.drawerVisible = true;
                }}
                onDrawerClose={() => {
                    this.state.drawerVisible = false;
                }}>
                <View style={styles.container}>
                </View>
            </DrawerLayoutAndroid>
        );
    }

    renderDrawerFilterView() {
        return (
            <FilterMenu />
        );
    }

    // 开关抽屉
    handleDrawerPanelDisplay(open) {
        if (open) {
            this.refs.drawer.openDrawer();
        } else {
            this.refs.drawer.closeDrawer();
        }
    }
}
`

`const AppNavigator = createStackNavigator({
    Home: {
        screen: YCHomeExaminePlanViewController,
    },
    Detail: {
        screen: YCExaminePlanDetailViewController,
    },
    Scan: {
        screen: YCScanViewController,
    },
    NewException: {
        screen: YCAddNewExceptionViewController,
    },
    UnusualAppearance: {
        screen: YCSelectUnusualAppearanceViewController,
    },
    UnusualReason: {
        screen: YCSelectUnusualReasonViewController,
    },
});

export default AppNavigator;`

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |3.12.1
| react-native     |0.60.0
| node             |11.10.1
| npm or yarn      |6.7.0

**Comment by matthamil** [comment]
Hello! Can you create a reproducible example in a public GitHub repo or as a [Snack](https://snack.expo.io)? Code snippets are great, but a cloneable repo that has only the parts necessary to reproduce your issue is even better. Thanks!

**Comment by Ta-Boy** [comment]
I create a new react-native project in https://github.com/Ta-Boy/DrawerIssueReproduce, and i reproduced this issue, when only a StackNavigator as AppContainer, all goes well. But when multi StackNavigators in a BottomTabNavigator which is a AppContainer, the issue comes out.

**Comment by brentvatne** [comment]
i don't recommend using `DrawerLayoutAndroid` with react-navigation, you should use react-navigation-drawer instead

**Comment by Ta-Boy** [comment]
Thanks, i use react-navigation-drawer now and  it's works very well.
