### ISSUE TITLE
react-naviagation-drawer are needed even though not used in v4

### ISSUE THREAD

**Issue by ParAnton** [react-navigation/react-navigation#6248]
Just upgraded to version 4
and get this error message
`Unable to resolve "react-navigation-drawer" from "node_modules/react-navigation/src/react-navigation.js"
Failed building JavaScript bundle.`

Even though I'm not using react-navigation-drawer so I should not need to install it or have I missed something?

**Comment by satya164** [comment]
Try deleting your node_modules and reinstall? and/or clear metro cache with `react-native start --reset-cache`
