### ISSUE TITLE
When navigating from one stacknavigator to another stacknavigator, initial route flickers.

### ISSUE THREAD

**Issue by TriinK** [react-navigation/react-navigation#6250]
### Current Behavior

React navigator flickers unwanted screen before navigating to desired route. When wanting to navigate from one stacknavigator named **Timeline** to **ViewArticle** (see below), the LearningHome screen flickers for 0,5 seconds before navigator navigates automatically to ViewArticle. 

```
export default createStackNavigator({
    LearningHome: {
        screen: LearningHome,
        navigationOptions: {
            header: <Header title={i18n.t('navigation.learningCenter')} />,
        },
    },
    ViewArticle: {
        screen: ViewArticle,
        backgroundImage: backgroundImages.big,
        navigationOptions: ({ navigation }) => ({
            header: <Header navigation={navigation} />,
        }),
    },
},
{
    headerMode: 'screen',
});
```

### Expected Behavior

The flicker shouldn't happen.

### How to reproduce

Build 2 StackNavigators. Add 2 screens to one StackNavigator (LearningCenter) and 1 screen to second StackNavigator (named Timeline). Navigate from  Timeline to LearningCenter subroute named ViewArticle.

### Your Environment

| software        | version
| react-navigation | 3.x
| react-native     | 0.59.8
| node             | 12.7.0
| npm or yarn      | 6.10.2

**Comment by matthamil** [comment]
Hello! Can you create a reproducible example in a public GitHub repo or as a [Snack](https://snack.expo.io)? Code snippets are great, but a cloneable repo that has only the parts necessary to reproduce your issue is even better. Thanks!

**Comment by brentvatne** [comment]
closing, please re-create with reproducible example if you have time

**Comment by GulinSS** [comment]
I approve it is present but have no minimal reproducible sample
