### ISSUE TITLE
iOS devices skip initialRoute and skips directly into app

### ISSUE THREAD

**Issue by bytewiz** [react-navigation/react-navigation#6251]
### Current Behavior

What happens is that on all iOS devices the initial route seems to be skipped which means my entire AuthLoading flow is skipped and the app isn't working.

### Expected Behavior

Expecting at least the route to be loaded so it is possible to evaluate the auth state before getting thrown into the app head first

### How to reproduce

```
// App navigator
export default createAppContainer(
  createSwitchNavigator(
    {
      // You could add another route here for authentication.
      // Read more at https://reactnavigation.org/docs/en/auth-flow.html
      AuthLoading,
      Setup: SetupStack,
      Main: MainTabNavigator,
      Auth: AuthStack,
    },
    { initialRouteName: 'AuthLoading' },
  ),
)
```
```
// AuthLoading (which seems to be skipped)
componentDidMount() {
    const self = this
    auth.onAuthStateChanged(async (user) => {
      if (user) {
        self.props.navigation.navigate(Routes.MAIN)
      } else {
        // User is signed out.
        self.props.navigation.navigate(Routes.AUTH)
  }
```
### Your Environment

Expo, 
react-native, 
react-navigation 4.x
iOS 6, 7, 10 (tested)

**Comment by matthamil** [comment]
Hello! Can you create a reproducible example in a public GitHub repo or as a [Snack](https://snack.expo.io)? Code snippets are great, but a cloneable repo that has only the parts necessary to reproduce your issue is even better. Thanks!

**Comment by bytewiz** [comment]
@matthamil I can do that 👍 so I guess out of the blue no idea why this happens? 🤔

**Comment by bytewiz** [comment]
@matthamil Just a note this problem only persists on actual real devices and not the emulator of iOS, so a snack probably won't work and you will have to have an iPhone to production version with for this to be reproducible

**Comment by bytewiz** [comment]
@matthamil This was an issue with `react-navigation` not really sure how/why it happens but stripped out half of the parts and wrote some custom code and now it seems to work as expected! 👍
