### ISSUE TITLE
NavigationEvents not working from unit tests (Jest)

### ISSUE THREAD

**Issue by jdnichollsc** [react-navigation/react-navigation#6252]
Guys, I have errors running unit tests with Jest and this component of React Navigation, do you have any example mocking this? Because it's missing from the documentation

Thanks in advance

**Comment by matthamil** [comment]
What are the errors? Can you create a reproducible example? Thanks

**Comment by Johan-dutoit** [comment]
Not sure if it's relevant, but my tests started failing after updating to 4.0.  Below is the log

```
Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /path/to/node_modules/react-navigation/src/react-navigation.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){export * from '@react-navigation/core';
                                                                                             ^^^^^^

    SyntaxError: Unexpected token export

      1 | /** @format */
      2 | 
    > 3 | import { NavigationActions, NavigationContainerComponent } from 'react-navigation';
        | ^
      4 | 
      5 | let navigator: NavigationContainerComponent;

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:537:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:579:25)
      at Object.<anonymous> (src/services/navigation.ts:3:1)
```

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!

**Comment by medmo7** [comment]
@jdnichollsc  have you resolved this issue? I have the same problem when trying to test a component which uses NavigationEvents.
this is the error i get:

`    Invariant Violation: withNavigation can only be used on a view hierarchy of a navigator. The wrapped component is unable to get access to navigation from props or context.

      at React (node_modules/@react-navigation/core/lib/commonjs/utils/invariant.js:45:11)
      at node_modules/@react-navigation/core/lib/commonjs/views/withNavigation.js:10:41
      at updateContextConsumer (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7275:19)
      at beginWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7441:14)
      at performUnitOfWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10138:12)
      at workLoop (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10170:24)
      at renderRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10256:7)
      at performWorkOnRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11121:7)
      at performWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11033:7)
      at performSyncWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11007:3)

Test Suites: 1 failed, 1 passed, 2 total
Tests:       1 failed, 3 passed, 4 total
Snapshots:   3 passed, 3 total
Time:        1.942s, estimated 2s
Ran all test suites.
  console.error node_modules/react-test-renderer/cjs/react-test-renderer.development.js:8060
    The above error occurred in the <Context.Consumer> component:
        in withNavigation(NavigationEvents) (at Settings.js:116)
        in View (created by View)
        in View (at ScrollViewMock.js:29)
        in RCTScrollView (created by _class)
        in _class (at ScrollViewMock.js:27)
        in ScrollViewMock (at Settings.js:112)
        in Settings (at setting.test.js:22)
    
    Consider adding an error boundary to your tree to customize error handling behavior.
    Visit https://fb.me/react-error-boundaries to learn more about error boundaries.`

**Comment by nicmalegre** [comment]
Hi! You need to add this on your test:
`jest.mock('react-navigation', () => ({
  NavigationEvents: 'mockNavigationEvents',
}))`
