### ISSUE TITLE
How to add border to  Navigation Icon 

### ISSUE THREAD

**Issue by vaibhavgadekar** [react-navigation/react-navigation#6253]
How to add Border radius to Navigation Icon 
![Screenshot_2019-09-03-12-21-51-532](https://user-images.githubusercontent.com/39763708/64150244-786d3900-ce45-11e9-9cdb-342fe7a61cdf.jpeg)
 Like this. 
I am Using React Navigation 3+

**Comment by brentvatne** [comment]
hi there! this is a question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help.
