### ISSUE TITLE
Opening the payment console triggers open the nav drawer

### ISSUE THREAD

**Issue by AGIsmail** [react-navigation/react-navigation#6255]
### Current Behavior

Opening a payment console to purchase an in-app subscription/product causes the navigation drawer to toggle open

<img src="https://i.stack.imgur.com/3wW8I.gif" width=248/>

(click image for full resolution)

### Expected Behavior
Opening a payment console should not trigger the drawer to open

### How to reproduce
[Github repository (iapDrawerBug branch)](https://github.com/AGIsmail/rn-nav-issue/tree/iapDrawerBug). This issue presents itself on both an emulator and device and in dev and production builds.

Run `npm i` and `react-native start` & `react-native run-android` then press/click on the "Purchase test item" text.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.11.1
| react-native     | 0.60.5
| react-native-iap | 3.4.0
| node             | v11.15.0 & v12.9.0
| npm or yarn      |npm v6.10.2

**Comment by brentvatne** [comment]
use react-navigation-drawer as directed in https://reactnavigation.org/docs/en/drawer-navigator.html and it will solve your problem

**Comment by jeffersontpadua** [comment]
@brentvatne can you elaborate a little bit more on what could be wrong? My implementation of react-navigation-drawer seems to be "as directed" in the documentation, but I'm still getting this issue
