### ISSUE TITLE
Conditional display custom navigator component

### ISSUE THREAD

**Issue by ScreamZ** [react-navigation/react-navigation#6257]
Hello, I'm back in React Navigation since version 1 :D.

Great evolves, good job !

I got the following custom navigator extended : 

```tsx
import React from "react";
import { useTranslation } from "react-i18next";
import { NavigationComponent, NavigationParams } from "react-navigation";
import { createBottomTabNavigator } from "react-navigation-tabs";
import Menu from "../../screens/main/Menu";
import News from "../../screens/main/News";
import Teams from "../../screens/main/Teams";
import Tournament from "../../screens/main/Tournament";
import Venue from "../../screens/main/Venue";
import LiveScoreAppHeader from "../livescore/components/LiveScoreAppHeader";
import { AppScreens } from "./types";

const MainBottomNav = createBottomTabNavigator({
  [AppScreens.Teams]: Teams,
  [AppScreens.News]: News,
  [AppScreens.Tournament]: Tournament,
  [AppScreens.Venue]: Venue,
});

const MainBottomNavContainer: NavigationComponent = (props: NavigationParams) => {
  // Inject translations into nav
  const { t } = useTranslation();

  return (
    <>
      <LiveScoreAppHeader />
      <MainBottomNav navigation={props.navigation} screenProps={{ t }} />
    </>
  );
};

MainBottomNavContainer.router = MainBottomNav.router;

export default MainBottomNavContainer;
```

I would like to display `LiveScoreAppHeader` only on some of children screens, so I would like to be able to disable it on some (like on Venue).

**I can't render it on each screen separately, because livescore will be a carousel and I want to keep the same component to keep its state**.

Any idea how can I achieve this ?
Thanks

Best regards

**Comment by brentvatne** [comment]
you might be interested in this alpha rewrite of the react-navigation api to make it more dynamic: https://github.com/react-navigation/navigation-ex

dynamic behavior like this is possible right now but not without tradoffs. you can see an example in https://github.com/brentvatne/react-europe-2019-react-navigation/blob/master/sections/DynamicTabs.js

you can also fork whatever navigator you're using and at this behavior to it
