### ISSUE TITLE
is there a ChangeLog of 4.0.0 ?

### ISSUE THREAD

**Issue by KingAmo** [react-navigation/react-navigation#6265]
### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 4.0.0
| react-native     | 0.60.5

----

or the only change is extracted out the navigators to separate repos  ?

**Comment by brentvatne** [comment]
it uses the same version of @react-navigation/core and @react-navigation/native, so no changes there. the navigators just live in separate repos now, and the navigators themselves were updated (except stack). see the changelogs for the navigators at:
- https://github.com/react-navigation/tabs/releases
- https://github.com/react-navigation/drawer/releases

**Comment by satya164** [comment]
https://github.com/react-navigation/react-navigation/releases/tag/v4.0.0

**Comment by SnehalAgrawal** [comment]
Here I have mentioned the updates in React Navigation 4.0
https://aboutreact.com/react-navigation-version-4/
