### ISSUE TITLE
navigation bug

### ISSUE THREAD

**Issue by xgqfrms** [react-navigation/react-navigation#6266]
# navigation bug

> different version codes

![image](https://user-images.githubusercontent.com/7291672/64415314-a1046580-d0c7-11e9-9023-0eee101d7d4b.png)

https://snack.expo.io/@react-navigation/hello-world-v3

![image](https://user-images.githubusercontent.com/7291672/64415425-d610b800-d0c7-11e9-93ee-23db761c6e39.png)

https://reactnavigation.org/docs/en/hello-react-navigation.html

![image](https://user-images.githubusercontent.com/7291672/64415438-e1fc7a00-d0c7-11e9-89d0-602ea8cdddfa.png)

**Comment by xgqfrms** [comment]
# why not tell install `react-navigation-stack`, but use it in the project, cause unnecessary bugs when running the app?

```sh
$ yarn add react-navigation-stack
```

https://reactnavigation.org/docs/en/getting-started.html#install-into-an-existing-project

**Comment by xgqfrms** [comment]
# put it there will very easy missing it

![image](https://user-images.githubusercontent.com/7291672/64416712-4c161e80-d0ca-11e9-9d78-13a3830c61cb.png)

**Comment by xgqfrms** [comment]
# can not open the app, after add `react-navigation-stack`, what's wrong with this?

> no exist error infos

```js

/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 *
 * @format
 * @flow
 */

import React from 'react';


import { HomePage } from "./src/Home";
import { Nav } from "./src/Navigation";

// import {
//     createAppContainer,
//     createStackNavigator,
//     // StackActions,
//     // NavigationActions,
// } from 'react-navigation';

import { createAppContainer } from 'react-navigation';
import { createStackNavigator } from 'react-navigation-stack';

const App = createStackNavigator(
    {
        Home: {
            screen: HomeScreen,
        },
        Details: {
            screen: Nav,
        }
    },
    {
        initialRouteName: 'Home',
    }
);

export default createAppContainer(App);
// export default App;


```

**Comment by suretarget** [comment]
Maybe related to this issue https://github.com/react-navigation/react-navigation/issues/6267#issuecomment-528883756

**Comment by xgqfrms** [comment]
# I will try it out

https://github.com/react-navigation/react-navigation/issues/6267#issuecomment-528883756

https://github.com/kmagiera/react-native-screens#usage-with-react-navigation-without-expo

**Comment by mehdiyaq** [comment]
I have same problem, so I use V3 instead in native Cli

**Comment by sitompul** [comment]
It's just broken. I don't think the current release version of react-navigation supports 0.60

**Comment by satya164** [comment]
Please follow the issue template when opening issues and read the release notes when upgrading https://github.com/react-navigation/react-navigation/releases/tag/v4.0.0
