### ISSUE TITLE
[TS][v4] Cannot find name 'NavigationStackScreenOptions'

### ISSUE THREAD

**Issue by retyui** [react-navigation/react-navigation#6276]
This commit [chore: prepare for 4.x](https://github.com/react-navigation/react-navigation/commit/9bdf5fa78483fa8906ed89b025a93e63b06df4f2#diff-4c9ef844fb7fba25c52a2ad6cb776b75) removed too a lot types

### Current Behavior
When I run a command `tsc --noEmit` I get next errors: 

```sh
node_modules/react-navigation/typescript/react-navigation.d.ts:197:41 - error TS2304: Cannot find name 'NavigationStackScreenOptions'.

197   export type NavigationScreenOptions = NavigationStackScreenOptions &
                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/react-navigation/typescript/react-navigation.d.ts:198:5 - error TS2304: Cannot find name 'NavigationTabScreenOptions'.

198     NavigationTabScreenOptions &
        ~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/react-navigation/typescript/react-navigation.d.ts:199:5 - error TS2304: Cannot find name 'NavigationDrawerScreenOptions'.

199     NavigationDrawerScreenOptions;
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/react-navigation/typescript/react-navigation.d.ts:477:7 - error TS2304: Cannot find name 'NavigationBottomTabScreenOptions'.

477       NavigationBottomTabScreenOptions
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 4 errors.
```

### Expected Behavior
Typings in node_modules don't have errors

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 4.0.0
| react-native     | 0.60.0
| node             | 12
| yarn      | 1.17.3

**Comment by abdullah-sr** [comment]
they've shifted things around with v4. The type you're looking for should be in `react-navigation-stack` now
