### ISSUE TITLE
when i install React-navigation@4.0.2 App start crashing

### ISSUE THREAD

**Issue by MajidAziz3** [react-navigation/react-navigation#6286]
{
  "name": "HijamaTherapy",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "react": "16.8.6",
    "react-native": "0.60.5",
    "react-native-gesture-handler": "^1.4.1",
    "react-native-reanimated": "^1.2.0",
    "react-native-screens": "^2.0.0-alpha.3",
    "react-native-webview": "^7.0.5",
    "react-navigation": "^4.0.2"
  },
  "devDependencies": {
    "@babel/core": "^7.6.0",
    "@babel/runtime": "^7.6.0",
    "@react-native-community/eslint-config": "^0.0.5",
    "babel-jest": "^24.9.0",
    "eslint": "^6.3.0",
    "jest": "^24.9.0",
    "metro-react-native-babel-preset": "^0.56.0",
    "react-test-renderer": "16.8.6"
  },
  "jest": {
    "preset": "react-native"
  }
}

app.js
import React, {Component} from 'react';
import {View} from 'react-native';
import {  createStackNavigator,createAppContainer } from 'react-navigation';
import Splash from './Components/Splash';
import MainScreen from './Components/MainScreen';

const BasedNavigator=createStackNavigator({
    Splash:Splash,
    MainScreen:MainScreen,
},
{
  initialRouteName: 'Splash',
}
)

const Container=createAppContainer(BasedNavigator);

class App extends Component {
  render() {
    return (
      <View style={styles.container}>
        <Container />
      </View>
    );
  }
}
export default App;
 even i use react-navigation-stack app crashing doesn't stop

**Comment by arifo** [comment]
+same

**Comment by satya164** [comment]
Please follow the release notes https://github.com/react-navigation/react-navigation/releases/tag/v4.0.0

**Comment by datvp09** [comment]
my app crash too but only when install apk. It remains crashing even after adding that 2 lines to dependencies @arifo

**Comment by trananh2001** [comment]
> Adding the following two lines to dependencies section in android/app/build.gradle resolves the crash issue
> 
> implementation 'androidx.appcompat:appcompat:1.1.0-rc01'
> implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0-alpha02'

very thank! this save my day ❤️

**Comment by PronayMallick** [comment]
> Adding the following two lines to dependencies section in android/app/build.gradle resolves the crash issue
> 
> implementation 'androidx.appcompat:appcompat:1.1.0-rc01'
> implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0-alpha02'

Thanks!

**Comment by MohitPrakashSharma** [comment]
Try this working form me 

$ react-native link react-navigation

**Comment by hamza-ameer** [comment]
@arifo You just saved me <3
