### ISSUE TITLE
cannot find the reference variable: Navigator  github repo : https://github.com/javeriazubair/login-sign-up

### ISSUE THREAD

**Issue by javeriazubair** [react-navigation/react-navigation#6288]
![github1](https://user-images.githubusercontent.com/50515469/64717169-31cead00-d4dd-11e9-88eb-f9483a924663.PNG)
![github2](https://user-images.githubusercontent.com/50515469/64717284-72c6c180-d4dd-11e9-8260-d95f4fb6abf9.PNG)
![github3](https://user-images.githubusercontent.com/50515469/64717367-9db11580-d4dd-11e9-9098-5e45a6e1d676.PNG)
![github4](https://user-images.githubusercontent.com/50515469/64717576-fc768f00-d4dd-11e9-9d07-ab7c2661d4f6.PNG)
![github5](https://user-images.githubusercontent.com/50515469/64717634-17490380-d4de-11e9-8f46-cdbc2f3de103.PNG)

**Comment by javeriazubair** [comment]
this is my code and i've been getting the error undefined this.props.navigation.navigate('login screen') first then i get this error after upgrading to version 4 react-navigation

**Comment by satya164** [comment]
Please provide runnable code

**Comment by satya164** [comment]
@javeriazubair how can I repro the issue if you don't add the code related to navigation? also please provide a very simple minimal repro so I can debug it. It's not possible for me to go through the code if it has unrelated code.
