### ISSUE TITLE
Setting headerTransparent to TRUE with CustomHeader JSX in navigationOptions cause screen component stack with Header.

### ISSUE THREAD

**Issue by ivanjiang5628** [react-navigation/react-navigation#6296]
## The issue tracker is reserved for bug reports only.

my navigationOptions setting is like this as below:
### static navigationOptions = {
        headerTransparent: true,
        header: (
            <View style={{
                alignItems: 'center',
                flex:1
            }}>
                <TouchableHighlight
                    style={{
                        flexDirection: 'row',
                        alignItems: 'flex-end',
                        justifyContent: 'space-between',
                        padding: 10,
                        borderRadius: 20,
                        height: 100,
                        width: '100%',
                        backgroundColor: 'white',
                        shadowColor: '#000',
                        shadowOffset: {
                            width: 0,
                            height: 2
                        },
                        shadowOpacity: 0.25,
                        shadowRadius: 3.84,
                        elevation: 5
                    }}
                    // onPress={this.onPress}
                >
                    <Text style={{
                        color: 'black',
                        fontSize: 40,
                        // marginBottom:5,
                        marginStart: 5
                        
                    }}>Chat</Text>
                </TouchableHighlight>
            </View>
        )
    };

### Current Behavior
![屏幕快照 2019-09-13 上午10 32 15](https://user-images.githubusercontent.com/24568041/64882404-dbaf5600-d611-11e9-8622-f735d9679fbc.png)

### Expected Behavior
headerTransparent should not effect the height of the whole header placement.

![屏幕快照 2019-09-13 上午10 34 05](https://user-images.githubusercontent.com/24568041/64882473-09949a80-d612-11e9-9c52-609e535f90f9.png)

### Your Environment

| software         | version
| ---------------- | -------
"react-navigation"|"^3.11.0",
"react-native"| "0.60.5",
| node             |  10.15.1

**Comment by gytisgreitai** [comment]
Duplicate https://github.com/react-navigation/react-navigation/issues/6218  ?
