### ISSUE TITLE
createAppContainer background cannot be transparent

### ISSUE THREAD

**Issue by seaver-choy** [react-navigation/react-navigation#6297]
### Current Behavior

1. When createAppContainer is coupled with <ImageBackground> or has a background, the backgroundImage won't show up, and it refuses to be transparent even if style={{ backgroundColor: 'transparent'}} has been passed.

````
import React, { Component } from 'react' // eslint-disable-line no-unused-vars
import { connect } from 'react-redux'
import tempNavigator from '../navigators/tempNavigator' // eslint-disable-line no-unused-vars
import { View, Platform, Linking, ImageBackground } from 'react-native' // eslint-disable-line no-unused-vars
import { createAppContainer } from 'react-navigation'

class ApplicationNavigatorContainer extends Component {
    constructor (props) {
        super(props)
    }

  render () {
      const Navigator = createAppContainer(tempNavigator) // eslint-disable-line no-unused-vars
      return (
          <ImageBackground source={require('../../assets/images/banner.png')} style={{ width: '100%', height: '100%' }}>
              <Navigator style={{backgroundColor: 'transparent'}}/>
          </ImageBackground>
      )
  }
}

export default connect(null, null)(
    ApplicationNavigatorContainer)
````
<img width="382" alt="Screen Shot 2019-09-14 at 9 36 35 PM" src="https://user-images.githubusercontent.com/10723083/64908871-c3d1f200-d737-11e9-9bd2-5ec5c2a06f18.png">

### Expected Behavior

The ImageBackground shows the image.

### How to reproduce

tempNavigator.js
````
import React from 'react'
import { createStackNavigator } from 'react-navigation-stack'
import Settings from '../../features/settings/components'
import * as screenNames from '../screenNames'

export default createStackNavigator(
    {
        [screenNames.SETTINGS]: {
        screen: Settings,
    },
        headerMode: 'none'
    }
)
````

Settings.js
````
import React, { Component } from 'react'
import { View, Text } from 'react-native'

import styles from './styles'

export default class Settings extends Component {
    render() {
        return (
            <View style={styles.background}>
                <Text>Hi</Text>
            </View>
        )
    }
}
````

### Your Environment

| software         | version
| Visual Code | 1.38.1
| react-navigation | 4.0.0
| react-native     | 0.60.5
| node             | 12.6.0
| npm or yarn      | 6.9.0

**Comment by dmitov** [comment]
Noticed that during a package update on my app. I'm using **react-navigation@3.11.1**, but I guess it could be applied to 4.0.0 as-well.

`{
    transparentCard: true,

    transitionConfig: () => ({
      containerStyle: {
        backgroundColor: 'transparent',
      },
      containerStyleLight: {
        backgroundColor: 'transparent',
      },
      containerStyleDark: {
        backgroundColor: 'transparent',
      },
  })
}`

I believe it's related to 12.4 update on the simulators, which include some of the new iOS 13 dark/light modes. Anyways, this should be further addressed and the `containerStyle` prop should overwrite the Dark/Light styles in my opinion.

Hope this helps!

**Comment by rt2zz** [comment]
@dmitov great find thank you. Works for me (after seeing the same issue upon updating react-navigation)

**Comment by dmitov** [comment]
Finer explanation for the issue and workaround is here:
https://github.com/react-navigation/stack/issues/232

**Comment by alubeck** [comment]
@dmitov indeed the holy grail, thank you :) ... although types are not aware of this solution 🤔 

```typescript
export const RootStackNavigator = createStackNavigator(
  {
    Home: HomeScreen,
    Modal: ModalDialogScreen,
  },
  {
    mode: 'modal',
    headerMode: 'none',
    transparentCard: true,
    transitionConfig: () => ({
      containerStyle: {
        backgroundColor: 'transparent',
      },
      containerStyleLight: {
        backgroundColor: 'transparent',
      },
      containerStyleDark: {
        backgroundColor: 'transparent',
      },
    }),
    defaultNavigationOptions: {
      gesturesEnabled: false,
    },
  } as any,  // needs to be any to prevent type issues
);
```
