### ISSUE TITLE
Conditional Render Inside createStackNavigator

### ISSUE THREAD

**Issue by MuhammadAhmed1994** [react-navigation/react-navigation#6298]
I have a navigation setup as following:

- Parent Component
   - Switch Navigator
     - Stack Navigator 1
        - Stack Navigator 2

I have wrapped navigation in a **parent component** and  I am passing the props from the parent component. Is there any way to pass the component down the tree to stack navigators hierarchy  and conditionally render from **stack navigator 1** and  **stack navigator 2**

Switch Navigator
==============

`export const createRootNavigator = (appState) => {
  return createSwitchNavigator(
    {
      AppStack: {
        screen: AppStack
      },
      AuthStack: {
        screen: AuthStack
      }
    },
    {
      initialRouteName: appState.isLoggedIn? "AppStack": "AuthStack"
    }
  );
}`

**Stack Navigator 1**
================

`const AppStack = createStackNavigator(
    {
        Home: { screen: Home },
        Stack2: { screen: stack2 }
    },
    {
        initialRouteName: 'Stack2', //here i want to render conditionall
        headerMode: 'none'
    }
)`

 
**Stack Navigator 2**
================

`const AppStack = createStackNavigator(
    {
        Home: { screen: Home },
        Stack2: { screen: stack2 }
    },
    {
        initialRouteName: 'Stack2', //here i want to render conditionally same as Stack Navigator 1
        headerMode: 'none'
    }
)`

Is it possible to use redux store in stack navigator?

**Comment by satya164** [comment]
Dynamic configuration of navigators will be possible in React Navigation 5: https://reactnavigation.org/next
