### ISSUE TITLE
hardwareBackPress not getting called after app enters the foreground from background

### ISSUE THREAD

**Issue by suneelkumargavara** [react-navigation/react-navigation#6299]
Hey there!!! It's been one week but i was unable to find the solution for this issue. The problem is with the hardwareBackPress after resetting react navigation. I am only using one stack navigator in this application like below.
const PrimaryNav = createStackNavigator {
    SplashScreen: { screen: SplashScreen },
    SelectField: { screen: SelectLanguage },
    WelcomeScreen: { screen: WelcomeScreen },
    TutorialScreen: { screen: TutorialScreen }
} 
The Welcome screen has the following implementation of BackHandler.

  componentDidMount() {
    this.backHandler = BackHandler.addEventListener('hardwareBackPress', () => {
      BackHandler.exitApp()
      return true
    })
  }
  componentWillUnmount() {
    this.backHandler.remove()
  }
Now i have navigated from welcomescreen to tutorialsceen by navigation.push('TutorialScreen'). The TutorialScreen contains a done button and on clicking that i am resetting the stack with the welcome screen as initial screen with the backhandler implementation as above. Below mentioned code is being used for resetting.

function resetTheStack() {
 const { navigation } = this.props
  const navigateAction = StackActions.reset({
    index: 0,
    key: null,
    actions: [NavigationActions.navigate({ routeName })],
  })
  navigation.dispatch(navigateAction)
}

Till now everything is goes well and the welcome screen is now the home screen with its index as 0. If i click the android backbutton now, it is working fine and app is going to background. Now the real problem comes. Once i open the app now, it is coming from background to foreground with the initial screen as welcome screen. But handler function us not getting called. In my application i am doing the resetting stack with welcome screen as initial screen, all is going well for the first time back press, but the real problem is occurring after the app got transitioned from background to foreground. Please help me as i have been struggling to get rid of this issue from one week.

Thanks in advance

**Comment by matthamil** [comment]
Hello! Can you create a reproducible example in a public GitHub repo or as a [Snack](https://snack.expo.io)? Code snippets are great, but a cloneable repo that has only the parts necessary to reproduce your issue is even better. Thanks!
