### ISSUE TITLE
React Native tabBarOptions - can't remove inactive background colour

### ISSUE THREAD

**Issue by patouxp** [react-navigation/react-navigation#6304]
I created a themed tab-bar using MaterialTopTabNavigator and tabBarOptions.

What I would like is to remove the background colour of the inactive tabs but it seems React is adding some default inactive background colour.

Does anyone know the trick to remove the background of the inactive tabs?

This is my code:    

> tabBarOptions: {
>         style: {
>           backgroundColor: 'transparent',
>         },
>         indicatorStyle: {
>           backgroundColor: 'transparent',
>         },
>         labelStyle: {
>           fontSize: 13,
>         },
>         tabStyle: {
>           backgroundColor: "tomato",
>           borderRadius: 10,
>           paddingLeft: 5,
>           paddingRight: 5,
>           paddingTop: 0,
>           paddingBottom: 0,
>           marginRight: 10,
>           marginBottom: 10,
>           width: "auto", 
>         },
>         activeTabStyle: {},
>         activeTintColor: "white",
>         inactiveTintColor: '#fcfcfc',
>         upperCaseLabel: false,
>       }
>

**Comment by matthamil** [comment]
Hello! Can you create a reproducible example in a public GitHub repo or as a [Snack](https://snack.expo.io)? Code snippets are great, but a cloneable repo that has only the parts necessary to reproduce your issue is even better. Thanks!
