### ISSUE TITLE
Build crashes when using react-native-screens 2.0

### ISSUE THREAD

**Issue by mariodot** [react-navigation/react-navigation#6305]
### Current Behavior
Build crashes when using React Navigation with react-native-screens@^2.0
There's probably a breaking change with react-native-screens, but yarn and npm install the latest 2.0 

Documentation should note that you should install version 1.0 to avoid any issues
### How to reproduce
Install react-native-screens@^2.0 
### Environment
| software         | version
| ---------------- | -------
| react-navigation | ^4.0.5
| react-native     | 0.60.5
| node             | 10.16.3
| npm  |  6.9.0

**Comment by burhanyilmaz** [comment]
Hey @mariodot 
Did you see it?
https://github.com/react-navigation/react-navigation/issues/6267

**Comment by satya164** [comment]
We've updated the docs to mention 1.0
