### ISSUE TITLE
[v4] unable to run on rn 0.59.10

### ISSUE THREAD

**Issue by yasir-netlinks** [react-navigation/react-navigation#6306]
### Current Behavior
I have followed the instructions for installation on docs, but I get the following error

```
> Task :app:processDebugManifest FAILED
/Users/netlinks/Projects/jobsaf/android/app/src/debug/AndroidManifest.xml:22:18-91 Error:
        Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
        is also present at [androidx.core:core:1.1.0-rc01] AndroidManifest.xml:24:18-86 value=(androidx.core.app.CoreComponentFactory).
        Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:7:5-117 to override.
```
I also followed what the error is suggesting to add `tools:replace="android.appComponentFactory"` but no use and got this error

```
/Users/netlinks/Projects/jobsaf/android/app/src/main/AndroidManifest.xml:15:5-69:19 Error:
        tools:replace specified at line:15 for attribute android:appComponentFactory, but no new value specified
/Users/netlinks/Projects/jobsaf/android/app/src/main/AndroidManifest.xml Error:
        Validation failed, exiting
```

Is `v4` compatible with `rn 0.59` ?

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^4.0.5
| react-native     | 0.59.10
| node             | v12.4.0
| npm    | 6.9.0

**Comment by satya164** [comment]
Doesn't seem related to React Navigation.

**Comment by yasir-netlinks** [comment]
I updated the lib and this error appeared, how is it not related ?

**Comment by satya164** [comment]
The error is in your native code. React Navigation doesn't include any native code. The error message doesn't say anything about React Navigation.

**Comment by yasir-netlinks** [comment]
I am just wondering if it isn't related to the installation of `react-native-screens` where I have to add this
```
implementation 'androidx.appcompat:appcompat:1.1.0-rc01'
implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0-alpha02'
```

**Comment by yasir-netlinks** [comment]
I am just wondering if it isn't related to the installation of `react-native-screens` where I have to add this
```
implementation 'androidx.appcompat:appcompat:1.1.0-rc01'
implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0-alpha02'
```

**Comment by satya164** [comment]
If you're on React Native 0.59, use reverse jetifier to convert dependencies that use android x: https://github.com/mikehardy/jetifier#to-reverse-jetify--convert-node_modules-dependencies-to-support-libraries
