### ISSUE TITLE
undefined is not an object (evaluating 'reactNavigation.ThemeColors.Light')

### ISSUE THREAD

**Issue by 16isaac89** [react-navigation/react-navigation#6311]
Package.json:
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "axios": "^0.19.0",
    "expo": "^34.0.1",
    "react": "16.8.3",
    "react-dom": "^16.8.6",
    "react-native": "https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz",
    "react-native-gesture-handler": "^1.3.0",
    "react-native-reanimated": "^1.1.0",
    "react-native-web": "^0.11.4",
    "react-navigation": "^3.0.0"
  },
  "devDependencies": {
    "babel-preset-expo": "^6.0.0"
  },
  "private": true
}

App.js
import React from 'react';
import {createAppContainer,createSwitchNavigator,createStackNavigator,createBottomTabNavigator} from 'react-navigation';
import AccountScreen from './src/screens/AccountScreen';
import SignupScreen from './src/screens/SignupScreen';
import SigninScreen from './src/screens/SigninScreen';
import TrackCreateScreen from './src/screens/TrackCreateScreen';
import TrackDetailsScreen from './src/screens/TrackDetailsScreen';
import TrackListScreen from './src/screens/TrackListScreen';

const SwitchNavigator = createSwitchNavigator({
      loginFlow:createStackNavigator({
        Signin:SigninScreen,
        Signup:SignupScreen
      }),
      mainFlow: createBottomTabNavigator({
        trackListFlow: createStackNavigator({
          TrackList:TrackListScreen,
          TrackDetails:TrackDetailsScreen
        }),
        TrackCreate: TrackCreateScreen,
        Account: AccountScreen
      })

});
export default createAppContainer(SwitchNavigator);

![Capture](https://user-images.githubusercontent.com/23630466/65222673-39d3b180-dac8-11e9-84b9-90436818c573.PNG)

**Comment by cx5168** [comment]
Install the following version:
"react-native-gesture-handler": "^1.4.1",
"react-native-reanimated": "^1.2.0",
"react-navigation": "^4.0.5",
"react-navigation-drawer": "^2.2.1",
"react-navigation-stack": "^1.8.0",
"react-navigation-tabs": "^2.5.3"

**Comment by 16isaac89** [comment]
import React from 'react';
import {createAppContainer,createSwitchNavigator} from 'react-navigation';
import { createBottomTabNavigator } from 'react-navigation-tabs';
import {createStackNavigator} from 'react-navigation-stack';
import AccountScreen from './src/screens/AccountScreen';
import SignupScreen from './src/screens/SignupScreen';
import SigninScreen from './src/screens/SigninScreen';
import TrackCreateScreen from './src/screens/TrackCreateScreen';
import TrackDetailsScreen from './src/screens/TrackDetailsScreen';
import TrackListScreen from './src/screens/TrackListScreen';

const SwitchNavigator = createSwitchNavigator({
      loginFlow:createStackNavigator({
        Signin:SigninScreen,
        Signup:SignupScreen
      }),
      mainFlow: createBottomTabNavigator({
        trackListFlow: createStackNavigator({
          TrackList:TrackListScreen,
          TrackDetails:TrackDetailsScreen
        }),
        TrackCreate: TrackCreateScreen,
        Account: AccountScreen
      })

});
export default createAppContainer(SwitchNavigator);

I STILL GET THE SAME ERROR

**Comment by matthamil** [comment]
Hello! Can you create a reproducible example in a public GitHub repo or as a [Snack](https://snack.expo.io)? Code snippets are great, but a cloneable repo that has only the parts necessary to reproduce your issue is even better. Thanks!

**Comment by GideonWolfe** [comment]
Bump, I am also experiencing this issue

**Comment by 16isaac89** [comment]
@matthamil  i have created a public repo  https://github.com/16isaac89/Tracker

**Comment by satya164** [comment]
@16isaac89 in your `package.json`, I see `"react-navigation": "^3.0.0"`. Please upgrade to latest version of 3.x (3.11.2) or 4.x

**Comment by 16isaac89** [comment]
@satya164  I upgraded to react navigation 4.0.5 as indicated in the following project https://github.com/16isaac89/Tracker  but still got the same issue

**Comment by sloppie** [comment]
@16isaac89  have you tried re-linking after installing the updated version?

**Comment by satya164** [comment]
@16isaac89 I ran your demo and it runs fine without any error. Make sure you reset metro cache and try again: `expo start -c` if using expo, `react-native start --reset-cache` on vanilla RN projects.

**Comment by Saad-Bashar** [comment]
just upgraded react-native to 0.59.10, did all steps like yarn cache clean, rm -rf node_modules, yarn install but still getting the same error. Using react navigation 3.0.0

**Comment by brentvatne** [comment]
hi there! sorry you're having an issue. as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.

you might wonder, why are we strict about this? the reason is that there are only a small number of maintainers on this project and there are hundreds of people who report issues. if it takes us 20 minutes on average to reproduce each issue and we go through 10 issues each day, that's about half of our day just trying to reproduce bugs, without even beginning to investigate solutions. compare that to 20 minutes for each person who reports an issue.

please create a new issue with this and i'd be happy to review it!
