### ISSUE TITLE
React Navigation Crash on Release mode/IPA on ios 

### ISSUE THREAD

**Issue by vishwajeet01** [react-navigation/react-navigation#6314]
## The issue tracker is reserved for bug reports only.

If you have a question, feature request, or an idea for improving the library or its related tools, please try one of the following resources:

- [Read the documentation](https://reactnavigation.org/)
- [Post an issue to the website repository if you'd like to see a documentation change](http://github.com/react-navigation/website)
- [Post a feature request to Canny](https://react-navigation.canny.io/feature-requests)
- [Write a RFC if you have ideas for how to implement a feature request](https://github.com/react-navigation/rfcs)
- [Get help on Discord chat (#react-navigation on Reactiflux)](https://discord.gg/4xEK3nD) or [on StackOverflow](https://stackoverflow.com/questions/tagged/react-navigation)
- Search for your issue - it may have already been answered or even fixed in the development branch. However, if you find that an old, closed issue still persists in the latest version, you should open a new issue.

Bugs with react-navigation must be reproducible *without any external libraries that operate on it*. This means that if you are attempting to use Redux or MobX with it and you think you have found a bug, you must be able to reproduce it without Redux or MobX in this report. Redux related issues belong in [react-navigation-redux-helpers](https://github.com/react-navigation/react-navigation-redux-helpers), and we do not have any first-class integration with MobX at the moment.

---

### Current Behavior

- What code are you running and what is happening?
- Include a screenshot if it makes sense.

### Expected Behavior

- What do you expect should be happening?
- Include a screenshot if it makes sense.

### How to reproduce

- You must provide a way to reproduce the problem. If you are having an issue with your machine or build tools, the issue belongs on another repository as that is outside of the scope of React Navigation.
- Either re-create the bug on [Snack](https://snack.expo.io) or link to a GitHub repository with code that reproduces the bug.
- Explain how to run the example app and any steps that we need to take to reproduce the issue from the example app.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |
| react-native     |
| node             |
| npm or yarn      |

**Comment by satya164** [comment]
Please open a new issue by filling the issue template and posting a stack trace of the crash.

**Comment by vishwajeet01** [comment]
I have updated the issue

**Comment by satya164** [comment]
Please provide a stack trace of the crash

**Comment by vishwajeet01** [comment]
2019-09-17 18:48:36.339 [error][tid:com.facebook.react.JavaScript] TypeError: undefined is not an object (evaluating 'e.default')

This error is located at:
    in r
    in t
    in RCTView
    in RCTView
    in n
    in n
    in t
    in t
    in RCTView
    in e
    in n
    in n
    in r
    in r
    in t
    in n
    in n
    in RCTView
    in e
    in a
    in RCTView
    in RCTView
    in t
2019-09-17 18:48:36.344 [error][tid:com.facebook.react.JavaScript] TypeError: TypeError: undefined is not an object (evaluating 'e.default')

This error is located at:
    in r
    in t
    in RCTView
    in RCTView
    in n
    in n
    in t
    in t
    in RCTView
    in e
    in n
    in n
    in r
    in r
    in t
    in n
    in n
    in RCTView
    in e
    in a
    in RCTView
    in RCTView
    in t

This error is located at:
    in n
    in RCTView
    in e
    in a
    in RCTView
    in RCTView
    in t
2019-09-17 18:48:36.346 [error][tid:com.facebook.react.JavaScript] TypeError: TypeError: undefined is not an object (evaluating 'e.default')

This error is located at:
    in r
    in t
    in RCTView
    in RCTView
    in n
    in n
    in t
    in t
    in RCTView
    in e
    in n
    in n
    in r
    in r
    in t
    in n
    in n
    in RCTView
    in e
    in a
    in RCTView
    in RCTView
    in t

This error is located at:
    in n
    in RCTView
    in e
    in a
    in RCTView
    in RCTView
    in t
2019-09-17 18:48:36.363 [fatal][tid:com.facebook.react.ExceptionsManagerQueue] Unhandled JS Exception: TypeError: TypeError: undefined is not an object (evaluating 'e.default')

This error is located at:
    in r
    in t
    in RCTView
    in RCTView
    in n
    in n
    in t
    in t
    in RCTView
    in e
    in n
    in n
    in r
    in r
    in t
    in n
    in n
    in RCTView
    in e
    in a
    in RCTView
    in RCTView
    in t

This error is located at:
    in n
    in RCTView
    in e
    in a
    in RCTView
    in RCTView
    in t
libc++abi.dylib: terminating with uncaught exception of type NSException
