### ISSUE TITLE
React Native app crashes on ios in release mode after adding React Navigation , works fine in Debug mode

### ISSUE THREAD

**Issue by vishwajeet01** [react-navigation/react-navigation#6315]
##App crashes on ios simulator and devices in release mode using Xcode but runs fine on debug mode and also works fine in android:

---

### Current Behavior

- App crashes in when build is release type in product scheme in Xcode.
- Works fine in when build type is debug .
- Works fine in android 

### Expected Behavior

- To run in release mode also and via ipa also

### How to reproduce

- npm install  ( to install node modules )
- uncomment release line for NSURL in AppDelegate.m 
- Product > Scheme > Edit Scheme > Build > change to release 

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.12.1
| react-native     | 0.56.0
| node             |
| npm or yarn      | npm

Github repo Link :  https://www.google.com/url?q=https://github.com/vikassahutech/ReactNavigationProject.git&sa=D&source=hangouts&ust=1568994195895000&usg=AFQjCNHChBAkhb6hqpDXGkFsR2sv9GXNmg

**Comment by nguyenanhthai** [comment]
I got same issue. 

software | version
-- | --
react-navigation | 4.0.10
react-native | 0.61.01

**Comment by satya164** [comment]
Please don't open multiple issues in multiple repos.

https://github.com/kmagiera/react-native-gesture-handler/issues/320

**Comment by AliRehman7141** [comment]
@satya164 will it be fixed by jsut adding ```import 'react-native-gesture-handler'``` in index.js?
