### ISSUE TITLE
React Navigation app crashes on release mode or via ipa on ios but works fine in debug mode

### ISSUE THREAD

**Issue by vishwajeet01** [react-navigation/react-navigation#6317]
##App crashes on ios simulator and devices in release mode using Xcode but runs fine on debug mode and also works fine in android:
---

### Current Behavior

- App crashes in when build is release type in product scheme in Xcode.
- Works fine in when build type is debug .
- Works fine in android 

### Expected Behavior

- To run in release mode also and via ipa also

### How to reproduce

- npm install  ( to install node modules )
- uncomment release line for NSURL in AppDelegate.m 
- Product > Scheme > Edit Scheme > Build > change to release 

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.12.1
| react-native     | 0.56.0
| node             |
| npm or yarn      | npm

Github repo Link for cloning of project :  https://www.google.com/url?q=https://github.com/vikassahutech/ReactNavigationProject.git&sa=D&source=hangouts&ust=1568994195895000&usg=AFQjCNHChBAkhb6hqpDXGkFsR2sv9GXNmg

Package.json :  

{
  "name": "SampleProject",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest",
    "android": "cd ./android && ./gradlew app:assembleDebug && ./gradlew installDebug"
  },
  "dependencies": {
    "@babel/runtime": "^7.5.5",
    "react": "^16.9.0",
    "react-native": "0.56.0",
    "react-native-gesture-handler": "1.0.15",
    "react-native-reanimated": "^1.2.0",
    "react-navigation": "^3.12.1"
  },
  "devDependencies": {
    "babel-jest": "24.9.0",
    "babel-polyfill": "^6.26.0",
    "babel-preset-react-native": "5.0.2",
    "jest": "24.9.0",
    "react-test-renderer": "16.4.1"
  },
  "jest": {
    "preset": "react-native"
  }
}

Error :

2019-09-17 18:48:36.339 [error][tid:com.facebook.react.JavaScript] TypeError: undefined is not an object (evaluating 'e.default')

This error is located at:
in r
in t
in RCTView
in RCTView
in n
in n
in t
in t
in RCTView
in e
in n
in n
in r
in r
in t
in n
in n
in RCTView
in e
in a
in RCTView
in RCTView
in t
2019-09-17 18:48:36.344 [error][tid:com.facebook.react.JavaScript] TypeError: TypeError: undefined is not an object (evaluating 'e.default')

This error is located at:
in r
in t
in RCTView
in RCTView
in n
in n
in t
in t
in RCTView
in e
in n
in n
in r
in r
in t
in n
in n
in RCTView
in e
in a
in RCTView
in RCTView
in t

This error is located at:
in n
in RCTView
in e
in a
in RCTView
in RCTView
in t
2019-09-17 18:48:36.346 [error][tid:com.facebook.react.JavaScript] TypeError: TypeError: undefined is not an object (evaluating 'e.default')

This error is located at:
in r
in t
in RCTView
in RCTView
in n
in n
in t
in t
in RCTView
in e
in n
in n
in r
in r
in t
in n
in n
in RCTView
in e
in a
in RCTView
in RCTView
in t

This error is located at:
in n
in RCTView
in e
in a
in RCTView
in RCTView
in t
2019-09-17 18:48:36.363 [fatal][tid:com.facebook.react.ExceptionsManagerQueue] Unhandled JS Exception: TypeError: TypeError: undefined is not an object (evaluating 'e.default')

This error is located at:
in r
in t
in RCTView
in RCTView
in n
in n
in t
in t
in RCTView
in e
in n
in n
in r
in r
in t
in n
in n
in RCTView
in e
in a
in RCTView
in RCTView
in t

This error is located at:
in n
in RCTView
in e
in a
in RCTView
in RCTView
in t
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by Johan-dutoit** [comment]
I get this issue when tapping back, only in release mode.

> Terminating app due to uncaught exception 'RCTFatalException: Unhandled JS Exception: Invariant Violation: Unsupported top level event type "onGestureHandlerStateChange" dispatched', reason: 'Unhandled JS Exception: Invariant Violation: Unsupported top level event type "onGestureHandlerStateChange" dispatched

**Comment by satya164** [comment]
https://github.com/react-navigation/react-navigation/issues/6330
