### ISSUE TITLE
Whats up, Versions?

### ISSUE THREAD

**Issue by dmitov** [react-navigation/react-navigation#6318]
Hi there!

Huge fan! Great job!

I've been working with React Navigation for quite some time now and everything has been flawless... Or close to :) 

### Issue
My question here is - what's up with the versions? At some point the repo was split to core and different navigators and I get that, it's awesome to split and conquer! 

Anyways, I got an app that's running on **3.12.1** version, but I'm confused with the numbers here. There, a snippet from yarn.lock

```
react-navigation@^3.12.1:
  version "3.12.1"
  dependencies:
    "@react-navigation/core" "~3.5.0"
    "@react-navigation/native" "~3.6.1"
    react-navigation-drawer "~1.4.0"
    react-navigation-stack "~1.5.0"
    react-navigation-tabs "~1.2.0"
```

I believe version 3 will be supported for some time after the release of 4.0, but I'm not sure how you guys handle the versions. What I suggest is to switch to more semantic versioning and make all the packages 3.x.x and 4.x.x, so there is easier-to-see connection between the different packages. 

This came by to me when trying to figure out which version of the Stack Navigator is actually linked to my packages and here is what I see:

### Stack Navigator
Version 1.5.1 of Stack, requires Core@3.5.0:
https://github.com/react-navigation/stack/blob/v1.5.1/package.json#L73

Version 1.5.4 of Stack, requires RN@4:
https://github.com/react-navigation/stack/blob/v1.5.4/package.json#L73

And somehow I got version 1.5.3, which is missing from Github.

### Drawer Navigator
Then, Drawer navigator has the following:
2.0.0 Drawer -> 3.0.0 Core: https://github.com/react-navigation/drawer/blob/v2.0.0/package.json#L75

2.1.1 Drawer -> 4.0.1 RN: https://github.com/react-navigation/drawer/blob/v2.1.1/package.json#L83

### Tab Navigator
And the Tab navigator is similar, but even more confusing.

## Suggestion

It's hard to undo what has been done, but my suggestion is to upgrade to a more specific versioning for the future. React Navigation 4 should use Core@^4.0.0, Stack@^4.0.0, etc.

This way, all the different packages can benefit from Minor and Patch versions, but keep their Major versions aligned with the others.

**Comment by brentvatne** [comment]
in the future the following will be true of versioning:

- react-navigation will include stable matching versions of @react-navigation/core and @react-navigation/native. it will not include any other navigator packages
- navigator packages will follow their own versioning so we don't have to force updates on people in order to update packages that they may not use
- dependencies from navigator packages on react-navigation will be expressed as peerDependencies

hope that is useful for you!

**Comment by brentvatne** [comment]
also thanks for the kind words and i'm glad the library is working well for you!
