### ISSUE TITLE
Problems installing yarn add react-navigation-tabs ^ 1.2.0

### ISSUE THREAD

**Issue by JorgeMoralesLopez** [react-navigation/react-navigation#6322]
I am having problems installing yarn add react-navigation-tabs ^ 1.2.0 This is the error that the console throws me error An unexpected error occurred: "https://registry.yarnpkg.com/react-navigation-tabs%5E1. 2.0: Not found "
yarn add react-navigation react-navigation-stack@^1.7.3 has been installed without problems.
I just did the expo SDK 34 to SDK 35

**Comment by iamharky** [comment]
Hi @JorgeMoralesLopez ,
Just add two '@' signs before version numbers like this:
`yarn add react-navigation react-navigation-stack@^1.7.3 react-navigation-tabs**@**^1.2.0 react-navigation-drawer**@**^1.4.0`
