### ISSUE TITLE
Potential TypeScript bug regarding screenProps

### ISSUE THREAD

**Issue by darrylyoung** [react-navigation/react-navigation#6323]
As discussed with @satya164 on Discord, I noticed an issue with in my app with regard to types and `screenProps`. Here's an example:

```tsx
import React from "react"
import { Text, View } from "react-native"
import { NavigationStackScreenComponent } from "react-navigation-stack"

interface ScreenProps {
  translate: (str: string, quantity?: { count: number }) => string
}

const ExampleScreen: NavigationStackScreenComponent<{}, ScreenProps> = ({
  screenProps: { translate }
}) => {
  return (
    <View>
      <Text>{translate("someTranslationKey")}</Text>
    </View>
  )
}

ExampleScreen.navigationOptions = ({ screenProps: { translate } }) => ({
  title: translate("someTranslationKey")
})

export default ExampleScreen
```

The issue is that in the `navigationOptions`, I'm seeing `translate` underlined with the following:

```
Property 'translate' does not exist on type '{}'
```

Note that `translate` is a function I set in my `App.tsx` like this:

```tsx
<AppNavigator
  screenProps={{
    locale,
    translate
  }}
/>
```

### Current Behavior

- I'm seeing a TypeScript warning about something passed via `screenProps`

### Expected Behavior

- After adding the correct type and using it in `NavigationStackScreenComponent`, I expect no warnings

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 4.0.6
| react-native     | Expo SDK 35
| node             | 10.16.3
| npm or yarn      | Yarn 1.17.3
| react-navigation-stack    | 2.0.0-alpha.14
| react-navigation-tabs    | 2.5.4

**Comment by satya164** [comment]
Upgrading react-navigation and react-navigation-stack to their latest versions should fix it.

**Comment by darrylyoung** [comment]
Thanks for the quick fix, @satya164.
