### ISSUE TITLE
React Navigation without navigation prop does not work in release mode

### ISSUE THREAD

**Issue by EtainLove** [react-navigation/react-navigation#6325]
I am implementing a react-native app that receives firebase push notification. When a notification arrives the app navigate to a screen to show the notification. I followed this approach using reference: "Navigating without the navigation prop" https://reactnavigation.org/docs/en/navigating-without-navigation-prop.html

When I tested this with debug mode, it works perfectly. But when I tested in release mode (android signed app) it does not work.

Especially, when the notification arrives when the app is open, it does not work. There is no error message and the app become freezing and in a 30 seconds or so, the app crashes.

Here are package info:
```
    "react": "16.8.3",
    "react-i18next": "10.12.2",
    "react-native": "0.59.10",
    "react-native-firebase": "5.5.6",
    "react-native-gesture-handler": "1.3.0",
    "react-navigation": "3.11.1",

    node: 10.16.3
```
Basically, I tried this "Navigating without the navigation prop" https://reactnavigation.org/docs/en/navigating-without-navigation-prop.html

Similarly, this one too: https://github.com/react-navigation/react-navigation/issues/742

I am using not class component but functional component.

// Navigator.js
```
const switchNavigator = createSwitchNavigator({
  ResolveAuth: ResolveAuthScreen,
  loginFlow: createStackNavigator({
    Signin: SigninScreen,
    Signup: SignupScreen
  }),
  helpFlow: createStackNavigator({
    Help: HelpScreen,
  }, {headerLayoutPreset: 'center'}),
  mainFlow: createBottomTabNavigator({
    Ask: createStackNavigator({
      AskMain: AskScreen,
      AskWait: AskWaitScreen,
    }, {headerLayoutPreset: 'center'}),
    Chat: createStackNavigator({
      ChatList: ChatListScreen,
      Chatting: ChatScreen,
    }, {headerLayoutPreset: 'center'}),
    Profile: createStackNavigator({
      Account: AccountScreen,
      AccountEdit: AccountEditScreen,
      ProfileContract: ProfileScreen
    }
    , {headerLayoutPreset: 'center'})
  },
...
export default createAppContainer(switchNavigator);
```

// App.js
```
import Navigator from './Navigator';
import { useTranslation } from 'react-i18next';
import { navigate, setNavigator } from './src/navigationRef';

const App = Navigator;

export default () => {

  // setup language
  const { t } = useTranslation();

  // use effect
  useEffect(() => {

    // notification listener (triggered when a particular notification has been received)
    // if the app is foreground, we need to navigate the screen
    const listenerFG = firebase.notifications().onNotification((notification: Notification) => {
      console.log('onNotification', notification);
      Alert.alert(
        t('AppScreen.title'),
        t('AppScreen.message'),
        [
          {text: t('yes'), onPress: () => navigate('Help', { notificationBody: notification })},
        ],
        {cancelable: true},
      );
    });

   listenerForAppClosed();

   return () => {
      listenerFG();
    }
  }, []);

  return (
    <App ref={(navigator) => { setNavigator(navigator) }} /> 
  );
```

// navigationRef.js
```
import { NavigationActions } from 'react-navigation';

let navigator;

// nav is coming from react navigation
export const setNavigator = navRef => {
  console.log('navigation ref', navRef);
  // set navigator
  navigator = navRef;
};

export const navigate = (routeName, params) => {
  console.log('[navigate dispatch] navigator', navigator);
  navigator.dispatch(
    NavigationActions.navigate({
      routeName,
      params
    })
  );
};
```
In debug mode, using `navigate('any screen') works like a charm, but in release mode, it does not work.

But one strange thing is that the following navigation works. A user opens a push notification when the app is not foreground state.

// part of App.js
```
// listen the notification being opened or clicked when the app is closed
  const listenerForAppClosed = async() => {
    // app closed
    const notificationOpen: NotificationOpen = await firebase.notifications().getInitialNotification();
    if (notificationOpen) {
      // app was opened by a notification
      console.log('getInitialNotification', notificationOpen);
      // get information about the notification that was opened
      const notification: Notification = notificationOpen.notification;
      //// ignore the same notification id since the same notification is received again, don't know why.
      // get noti id from storage
      const notiId = await AsyncStorage.getItem('notiId');
      // set noti id to storage
      await AsyncStorage.setItem('notiId', notification.notificationId);     
      if (notification.notificationId === notiId) {
        console.log('notification id is the same');       
      } else { 
        console.log('navigating to helpscreen...');   
        // navigate to Help screen
        navigate('Help', { notificationBody: notification });
      }
    }
  }
```
The problem happens both on Android emulator and a device (Android9).

Why the navigate('Help') does not work in release mode? I searched many documents and I feel that it should work in release mode too.

Is there any other way to navigate to a screen from top-level (like App.js)?

**Comment by Dhirajbhujbal** [comment]
Sorry to interrupt, 
I am using the same approach. but now able to get params that has been passed
May I know How to get Params which has been passed while navigating the screens?

**Comment by EtainLove** [comment]
Here are how I got navigation params:

1. set navigation params example
 ```
// navigate to chat screen with param of user as client
navigation.navigate('Chatting', {chatUserId: 1, caseId, helperId: docSnapshot.data().helperId});
```

2. get navigation params
```
  // get params
  const chatUserId = navigation.getParam('chatUserId');
  const caseId = navigation.getParam('caseId');
```

does this answer your question? if not, let me know.

**Comment by EtainLove** [comment]
I found the source of the problem. I tested several things. I wanted to know that whether very simple app in release mode navigates properly. So, I just followed this posting: https://medium.com/@katharinep/firebase-notification-integration-in-react-native-0-60-3a8d6c8d56ff

Here are what I did: - created two screens: Home and Notification. - Re-created the app with latest react-native@0.60.6 and react-navigation@4.0.9 - sent cloud message not from the app but from the firebase cloud messaging

It worked! When a notificaiton arrives the app navigated to the notification screen.

So I tried to track down the source of the problem. - tried to add more screens - added more providers and context - sent message from the app

Finally, I found the source. It was how I used 'navigateRef.js' Originally I used it like this:
```
// App.js
import { navigate, setNavigator } from './src/navigationRef';
<App ref={(navigator) => { setNavigator(navigator) }} /> 
// navigationRef.js
import { NavigationActions } from 'react-navigation';

let navigator;

// nav is coming from react navigation
export const setNavigator = navRef => {
  console.log('navigation ref', navRef);
  // set navigator
  navigator = navRef;
};

export const navigate = (routeName, params) => {
  console.log('[navigate dispatch] navigator', navigator);
  navigator.dispatch(
    NavigationActions.navigate({
      routeName,
      params
    })
  );
};
```
I simply used the exact the code from react-navigation: https://reactnavigation.org/docs/en/navigating-without-navigation-prop.html

```
// App.js
import NavigationService from './src/NavigationService';
<App
    ref={navigationRef => 
      {NavigationService.setTopLevelNavigator(navigationRef);}}
/>
// NavigationService.js
import { NavigationActions } from 'react-navigation';

let _navigator;

function setTopLevelNavigator(navigatorRef) {
  _navigator = navigatorRef;
}

function navigate(routeName, params) {
  _navigator.dispatch(
    NavigationActions.navigate({
      routeName,
      params,
    })
  );
}

// add other navigation functions that you need and export them

export default {
  navigate,
  setTopLevelNavigator,
}
```
Then I worked! I do not know the difference of these two codes. The first one worked perfectly in debug mode but not in release mode, especially the app is in foreground.

Could anyone tell me the difference? Why the first code does not work?
