### ISSUE TITLE
Can not get params which navigate passed

### ISSUE THREAD

**Issue by liudonghua123** [react-navigation/react-navigation#6335]
### Current Behavior

I have two navigator, one `Auth` which is a `StackNavigator` contains `SignInScreen`, one `App` which is a `BottomTabNavigator` contains `HomeScreen`, I want to navigate from `HomeScreen` to `SignInScreen` and pass some params to indicate the source.

I tried a lot of code like the following.

```
navigation.navigate('Auth', { source: 'App' })
```
or
```
navigation.navigate(
  'Auth',
  {},
  {
    type: 'Navigate',
    routeName: 'Auth',
    params: { source: 'App' }
  }
)
```
or
```
navigation.navigate(
  'Auth',
  {},
  {
    type: 'Navigate',
    routeName: 'Auth',
    action: {
      type: 'Navigate',
      routeName: 'SignInScreen',
      params: { source: 'App' }
    }
  }
)
```
...
But none of them works. `navigation.getParam('source', null)` always return null.

see more on 
https://github.com/liudonghua123/expo-multi-screen-starter/blob/navigation_params_null/src/screens/HomeScreen.js#L22
https://github.com/liudonghua123/expo-multi-screen-starter/blob/navigation_params_null/src/screens/SignInScreen.js#L26

I have also read the https://github.com/react-navigation/react-navigation/issues/143 and https://github.com/react-navigation/react-navigation/issues/1237.

### Expected Behavior

- I expected the code `navigation.getParam('source', null)` return the actural params.

### How to reproduce

- https://github.com/liudonghua123/expo-multi-screen-starter/tree/navigation_params_null
- https://snack.expo.io/@git/github.com/liudonghua123/expo-multi-screen-starter@navigation_params_null

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^4.0.6
| react-native     | https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz
| node             | 12.11.0
| npm or yarn      | 1.12.1

**Comment by eriveltonelias** [comment]
hey @liudonghua123, 

when you navigate between navigators, you can use `dangerouslygetparent` https://reactnavigation.org/docs/en/navigation-prop.html#dangerouslygetparent-get-parent-navigator

**Comment by liudonghua123** [comment]
Thanks, I need to revert the code to `navigation.navigate('Auth', { source: 'App' })` in HomeScreen, and then I can get the params like the following code.
```
    const parent = navigation.dangerouslyGetParent();
    let source = null;
    if (parent && parent.state && parent.state.params) {
      ({ source } = parent.state.params);
    }
```

**Comment by eriveltonelias** [comment]
great!

**Comment by vinitgundeti** [comment]
Hi, i am facing the same issue in "@react-navigation/native": "^5.7.3" but the above mentioned method is not working. can anyone help please
