### ISSUE TITLE
I had found headerBackImage it's no longer working in react-navigation@4.0.1

### ISSUE THREAD

**Issue by txfyteen** [react-navigation/react-navigation#6339]
```
  defaultNavigationOptions:{
            headerStyle:{
                backgroundColor:'#f4511e'
            },
            headerTintColor:'#fff',
            headerBackImage: ()=>(<Image source={require('./assets/back.png')} />),
            headerBackTitle:null,
        }
```

### the headerBackImage  attribute is abandoned in 4.0.1？？

**Comment by brentvatne** [comment]
it works as expected here: https://github.com/react-navigation/react-navigation/blob/2e34cb1e389cf648848de1823ab02b9830e4e2eb/example/src/StackWithCustomHeaderBackImage.tsx#L129-L140

might want to double check that
