### ISSUE TITLE
split view

### ISSUE THREAD

**Issue by kefyru** [react-navigation/react-navigation#6344]
is it possible to make split-view like in mail.app?

i have hierarchical list in left side (where i can route into each item and got included list etc...)
and in right side i have any content, that contains any links to another content.
So i make two navigators (left and right) and they work independently. Thats ok.

I want that in landscape view it will be split-screen of too navigators, but in portrait view it will be good to have one navigator.

i can make it by using any swipable components. But may be react-navigation can do it?

sorry for my english)

**Comment by MaxInMoon** [comment]
@kefyru could you share your router code please? I need to understand better the ` two navigators (left and right) and they work independently` part. Thank you

**Comment by retyui** [comment]
@MaxInMoon @kefyru 
I created an article "how to implement Split View" [https://dev.to/retyui/how-to-implement-split-view-on-a-tablet-with-react-native](https://bit.ly/2TSCAiU)

**Comment by MaxInMoon** [comment]
@retyui thanks you, it seems amazing :)
