### ISSUE TITLE
Unable to resolve "react-navigation" from "App.js"

### ISSUE THREAD

**Issue by Ugurercin** [react-navigation/react-navigation#6345]
I tried everything,

npx expo-cli install react-native-gesture-handler react-native-reanimated react-navigation-stack

yarn add react-navigation react-navigation-stack@^1.7.3 react-navigation-tabs@^1.2.0 react-navigation-drawer@^1.4.0

and as in new version trying to import these

+ import { createAppContainer } from 'react-navigation';
+ import { createStackNavigator } from 'react-navigation-stack';

instead of - import { createAppContainer, createStackNavigator } from 'react-navigation';

But still cant figure out what the problem is. 

I am also a beginner for these stuff, kinda stucked at this point.

**Comment by AlaminPu1007** [comment]
did you try it with npm ?install ,its worked for me.

**Comment by bismarkstoney** [comment]
import { createAppContainer } from '@react-navigation/native';

**Comment by ayushman-sinha** [comment]
You should install it with:

npm install @react-navigation/stack

“@“ should be in the beginning
It worked for me

**Comment by LIGHT-LLC** [comment]
1. Install React Navigation

npm install react-navigation --legacy-peer-deps

or

yarn add react-navigation


2. Install Dependencies

npx expo install react-native-gesture-handler react-native-reanimated react-native-screens react-native-safe-area-context @react-native-community/masked-view -- --legacy-peer-deps


3. Install React Navigation Stack

npm install react-navigation-stack @react-native-community/masked-view --legacy-peer-deps

or

yarn add react-navigation-stack @react-native-community/masked-view



4. Find the babel.config.js file and add the following line to the return:

    plugins: ["react-native-reanimated/plugin"],

Updated babel.config.js:

```
module.exports = function (api) {
  api.cache(true);
  return {
    presets: ["babel-preset-expo"],
    plugins: ["react-native-reanimated/plugin"],
  };
};


Then retry npm start
