### ISSUE TITLE
Wrong type definition for `transitionConfig` in StackNavigator

### ISSUE THREAD

**Issue by emeraldsanto** [react-navigation/react-navigation#6346]
### Current Behavior

TypeScript complains about a custom transition config passed to a `StackNavigator` is of the wrong type, is `TransitionConfig` but should be `HeaderTransitionConfig`. The transition code is as follows:
```javascript
const screenWidth = Dimensions.get('window').width;
const swipeTransition = () => {
    return {
        transitionSpec : {
            useNativeDriver : true,
            duration : 225,
	   timing : Animated.timing,
        }, 
	screenInterpolator : (sceneProps : any) => {
            const currentIndex = sceneProps.scene.index;

            const translateX = sceneProps.position.interpolate({
	        inputRange : [currentIndex - 1, currentIndex, currentIndex + 1],
		outputRange : [screenWidth, 0, -screenWidth]
	    });

	    return { transform : [{ translateX : translateX }] }
	}
    }
}
```

### Expected Behavior

No TypeScript error.

### How to reproduce

Pass a custom transition of type `TransitionConfig` to a `StackNavigator` such as the one above.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |    4.0.0   
| react-native     |    0.61.1
| node             |    12.10.0
| npm or yarn      |    6.11.3

**Comment by satya164** [comment]
https://github.com/react-navigation/stack/issues/211
