### ISSUE TITLE
Tab Navigation with Stacks - cannot deep link to child screen when parent tab is active

### ISSUE THREAD

**Issue by hkellaway** [react-navigation/react-navigation#6350]
### Current Behavior

I have an app with a root `Tab` bar and a `Stack` at the root of each tab. The issue is, I cannot deep link to the child in a stack when that tab is actively selected. However, deep linking to the child works as expected if a different tab is selected.

I've created a basic demonstration of this here: https://github.com/hkellaway/React-Native-Navigation-DeepLink-Demo

The demo has 2 tabs: **Home** Tab and **Settings** Tab. At the root of each tab is a Stack.  The **Home** tab has one child in its Stack, the **Details** screen. Represented in code:

``` javascript
const HomeStack = createStackNavigator({
  Home: {
    screen: HomeScreen,
    path: "home"
  },
  Details: {
    screen: DetailsScreen,
    path: "details"
  }
});
  
const SettingsStack = createStackNavigator({
  Settings: {
    screen: SettingsScreen,
    path: "settings"
  }
});
  
const RootTabNavigator = createBottomTabNavigator({
  Home: HomeStack,
  Settings: SettingsStack,
});

const AppContainer = createAppContainer(RootTabNavigator);

class App extends Component {
  render() {
    return <AppContainer uriPrefix="deeplinkdemo://" />
  }
}

export default App;
```

### Expected Behavior

The following deep links are expected to work, no matter which tab is active:
`deeplinkdemo://home`
`deeplinkdemo://home/details`
`deeplinkdemo://settings`

The issue is that, if the **Home** tab is active, the deep link to **Details** does not work. However, it does work if the **Settings** tab is active.

### How to reproduce

See the demo README for steps to reproduce: https://github.com/hkellaway/React-Native-Navigation-DeepLink-Demo

### Your Environment

Demo dependencies: https://github.com/hkellaway/React-Native-Navigation-DeepLink-Demo/blob/master/package.json#L12

| software         | version
| ---------------- | -------
| react-navigation | `^4.0.10`
| react-navigation-stack | `^1.9.3`
| react-navigation-tabs | `^2.5.5`
| react-native     | `0.61.1`
| node             | `v12.10.0`
| yarn      | `1.17.3`

**Comment by fabcall** [comment]
I'm facing exactly the same issue with react-navigation 2.17.0. It seems to be a long-living bug, since you're already at 4.0.10 and it seems to persist.

**Comment by hkellaway** [comment]
that's unfortunate to hear. have other folks who are on `4.x` experienced this? what is your workaround?

**Comment by fabcall** [comment]
@hkellaway , I could solve this issue by overriding the handleOpenUrl method from react-navigation. Basically, you can follow [this](https://github.com/react-navigation/react-navigation/issues/1527#issuecomment-318327889). I would also suggest to recursively get last action object instead of cascading "ifs".

**Comment by hkellaway** [comment]
i was able to address my particular example by shirting which screen i provided the `path` to. credit to this post for the idea of what to try: https://github.com/react-navigation/react-navigation/issues/1527#issuecomment-323540179

whereas this did not work:

```
const HomeStack = createStackNavigator({
  Home: {
    screen: HomeScreen,
    path: "home"
  },
  Details: {
    screen: DetailsScreen,
    path: "details"
  }
});
  
const SettingsStack = createStackNavigator({
  Settings: {
    screen: SettingsScreen,
    path: "settings"
  }
});
  
const RootTabNavigator = createBottomTabNavigator({
  Home: HomeStack,
  Settings: SettingsStack,
});

const AppContainer = createAppContainer(RootTabNavigator);

class App extends Component {
  render() {
    return <AppContainer uriPrefix="deeplinkdemo://" />
  }
}
```

this did work:

```
const HomeStack = createStackNavigator({
  Home: { screen: HomeScreen },
  Details: {
    screen: DetailsScreen,
    path: "details"
  }
});
  
const SettingsStack = createStackNavigator({
  Settings: { screen: SettingsScreen }
});

const RootTabNavigator = createBottomTabNavigator({
  HomeStack: { screen: HomeStack, path: 'home' },
  SettingsStack: { screen: SettingsStack, path: 'settings' },
});

const AppContainer = createAppContainer(RootTabNavigator);

class App extends Component {
  render() {
    return <AppContainer uriPrefix="deeplinkdemo://" />
  }
}
```

notice where the `path` is defined is changed.

hope that helps someone!
