### ISSUE TITLE
Custom Stack Navigator header does not animate

### ISSUE THREAD

**Issue by scottmas** [react-navigation/react-navigation#6352]
### Current Behavior
Specifying a [custom header component](https://reactnavigation.org/docs/en/stack-navigator.html#header) causes the header to not animate when transitioning between screens.

![header](https://user-images.githubusercontent.com/2257337/66007023-fbe27000-e46d-11e9-99ba-04fab9521b17.gif)

### Expected Behavior

- React Navigation knows what header is animating out and which one is animating in. It should be able to have a sane opacity animation on the entire header component. 

### How to reproduce

- Navigate between two sibling Stack Navigator screens, each with custom header components. Note that no animation is performed. 

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 4.0.7
| react-native     | 59
| node             | 10
| npm or yarn      | yarn

**Comment by satya164** [comment]
When specifying a custom header, you need to manage the animation yourself. Always applying a fade animation means you won't be able to add custom animations, so we don't do it. You can check the existing code to see how animation is done.

Or set `headerMode` to `'screen'` and header will slide with the screen.

**Comment by scottmas** [comment]
Hey thanks for the info Satyajit. Can you provide a starting point though? There's no information on animating a custom header anywhere online. I've investigated the header props that get passed to the custom `header` method and while the props have a `scene` field, the scene field does not seem to be the same one that is referenced `HeaderSegment`, since it is lacking the `progress` property that gets passed to the style interpolator. If you can provide a starting point that I can take and make work then I could paste my solution here so future people would know how it's done.

**Comment by Artem29383** [comment]
anyone found solution?
