### ISSUE TITLE
How to get params? I am using the 'Navigating without the navigation prop' approach

### ISSUE THREAD

**Issue by Dhirajbhujbal** [react-navigation/react-navigation#6354]
How to get params? I am using the 'Navigating without the navigation prop' approach

**Comment by r1ckyrockz** [comment]
If you redirect to Page A to Page B like this:
`NavigationService.navigate('PageB', { firstParam: 'xyz' });`

You have access over the `props.navigation` in your `PageB` component.

Example: 

```
class PageB extends React.PureComponent {
  componentDidMount() {
    const { navigation } = this.props;
    const myNavigationParam = navigation.getParam('firstParam', 'yourCustomdefaultValue');
  }
}

```

Maybe this will help you out ;-)

**Comment by Dhirajbhujbal** [comment]
returns undefined

**Comment by Dhirajbhujbal** [comment]
Please note that Page B is the **StackNavigator**
