### ISSUE TITLE
[iOS] Bug on Release Version by navigation over header

### ISSUE THREAD

**Issue by r1ckyrockz** [react-navigation/react-navigation#6355]
### Current Behavior

I've got a real strange problem with the navigation with the package `react-navigation`.
Hopefully someone can help me.

The Problem is, that on debug mode via metro bundler the app work as aspected. But, if i archive the build for the app store (create archive build over xcode) and install it first over `Ad Hoc` or `TestFlight` (also xcode) the header back navigation is not going back!? 

i am using  basic `react-navigation`... 

Short example:

```
// App.tsx
import ScreenA from 'xxx/screens/ScreenA';
import ScreenB from 'xxx/screens/ScreenB';

const AppStack = createStackNavigator({
  ScreenA: ScreenA,
  ScreenB: ScreenB
}, {
  initialRouteName: 'ScreenA',
});

const AppNavigation = createAppContainer(AppStack);
export default AppNavigation;
```

```
// ScreenA
class ScreenA extends React.PureComponent {
  render() {
     return (
      <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
        <Text>Screen A</Text>
        <Button
          title="Go to Screen B"
          onPress={() => this.props.navigation.navigate('ScreenB')}
        />
      </View>
    );
  }
}
```

```
// Screen B
class ScreenB extends React.PureComponent {
  render() {
     return (
      <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
        <Text>Screen B</Text>
        <Button
          title="Go to Screen A"
          onPress={() => this.props.navigation.navigate('ScreenA')}
        />
      </View>
    );
  }
}
```

Navigate from `Screen A` to `Screen B`, the Header will show the back button. Now, nothing happen by clicking on the button.

### Expected Behavior

On release build (over xcode for ios) the back navigation should go to the previous screen.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | `^4.0.10`
| react-native     | `0.61.2`
| node             | `12.4.0`
| yarn      | `1.19.0`

**Comment by Radiergummi** [comment]
Same here

**Comment by JonasGrunau** [comment]
The back button is not working for me as well.

**Comment by r1ckyrockz** [comment]
UPDATE: i found out, that the `react-native-gesture-handler@1.4.1` is broken on release.

**Comment by satya164** [comment]
Is this your issue? https://github.com/kmagiera/react-native-gesture-handler/issues/320

**Comment by r1ckyrockz** [comment]
No, this is not my issue. but i will have a look into this.

**Comment by r1ckyrockz** [comment]
Thank you @satya164 for your help! This issue solved my problem.

For the others (https://github.com/kmagiera/react-native-gesture-handler/issues/320):
```
// index.js
import 'react-native-gesture-handler'; // <- FIRST LINE
```
