### ISSUE TITLE
null is not an object (evaluating 'rngesturehandlermodule.direction') android

### ISSUE THREAD

**Issue by joker1951998** [react-navigation/react-navigation#6356]
Hi, I have the issue in Android app. Could you please help me to fix it?

"react-native": "0.61.2",

"react-native-gesture-handler": "^1.4.1",

"react-native-reanimated": "^1.3.0",

"react-navigation": "^4.0.10",

"react-navigation-stack": "^1.9.3".

![image](https://user-images.githubusercontent.com/48432206/66216552-e1b7c480-e6ef-11e9-878c-58b69cc1331d.png)

**Comment by joker1951998** [comment]
please help me

**Comment by calendee** [comment]
I had the same problem initially.  However, I remembered that the whole installation process adds tons of native code.  Reloading the app will not load native code.  Please try:

1. Kill your metro bundler
2. `yarn start --reset-cache`
3. `react-native run-android`

That did the trick for me.

**Comment by afshawnlotfi** [comment]
Still having this problem with ```"react-native-gesture-handler": "^1.5.2"```

**Comment by hengsoheak** [comment]
I got the same issue
<img width="396" alt="Screen Shot 2019-12-18 at 4 52 02 PM" src="https://user-images.githubusercontent.com/812528/71075512-c7519b00-21b6-11ea-8ae0-774580645593.png">

**Comment by pdaniloais** [comment]
For IOS:
-- cd ios
-- pod install

**Comment by afshawnlotfi** [comment]
@pdaniloais Yip that's exactly how I solved it

**Comment by adiRandom** [comment]
Any fix for Android? Followed all the steps from the getting started page but I am still getting this error

**Comment by OmarKhattab** [comment]
i made sure to pod install in ios folder and then restart my dev enviornment
