### ISSUE TITLE
When I Press Back Button(from the stack header) or swipe left to right, ios app crashes

### ISSUE THREAD

**Issue by mashfiqcse13** [react-navigation/react-navigation#6361]
## Bug description

When I Press Back Button(In the stack header) or swipe left to right in a physical iPhone device running from the "apple test flight", my react native app crashes. It is happening for react-native-gesture-handler, I guess.

When I run my code directly to my iPhone. The gesture handler works fine. But when I upload a build in the "app store connect" and download it using testflight app on my iphone. It do not work. I don't have any crash log. No way to find out why crashing it. In my app there is a drawer nav also. when I swipe left to right the app crashes. When I press back button in the stack nav header, then the app crashes.

So, how can I fix this issue?

Here is the code for my main navigator
https://gist.github.com/mashfiqcse13/e90812cf1c042850cd64654a8ae87bf9
---

### Current Behavior

- What code are you running and what is happening?
If I run app from Apple Testflight, The app crashes on pressing back button (from the stack header) or swipe left to right.

### Expected Behavior

- What do you expect should be happening?
The gesture should work fine.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^4.0.5
| react-native     | 0.61.2
| react-native-gesture-handler | ^1.4.1
| node             | 12.6.0
| npm      | 6.11.3
| yarn      | 1.17.3

**Comment by r1ckyrockz** [comment]
My App is not crashing, but the back button is also not working. 
see my Issue:
https://github.com/react-navigation/react-navigation/issues/6355

**Comment by satya164** [comment]
https://github.com/kmagiera/react-native-gesture-handler/issues/320

**Comment by mnemanja** [comment]
The app that I'm working on also crashes on ios for the same behavior.
Android works correctly.

software | version
-- | --
react-navigation | ^4.0.4
react-native | 0.61.1
react-native-gesture-handler | ^1.4.1
node | 10.16.3
npm | 6.11.2
yarn

**Comment by mashfiqcse13** [comment]
Yes, this solution is work for me fine : 
https://github.com/kmagiera/react-native-gesture-handler/issues/320#issuecomment-447534290

**Comment by MeisterTea** [comment]
> Yes, this solution is work for me fine :
> [kmagiera/react-native-gesture-handler#320 (comment)](https://github.com/kmagiera/react-native-gesture-handler/issues/320#issuecomment-447534290)

Thank you, it did the trick !

**Comment by apostolou** [comment]
I'm using RN 64 and had to combine both adding the `import 'react-native-gesture-handler'` in the beginning of my index.js file (as mentioned in react-native-gesture-handler [installation instructions](https://docs.swmansion.com/react-native-gesture-handler/docs/#installation
)) and setting the `inlineRequires` attribute to `false` in the metro.config.js file (as explained [here](https://github.com/software-mansion/react-native-gesture-handler/issues/320#issuecomment-829434134)).
