### ISSUE TITLE
Please update the following components: SafeView

### ISSUE THREAD

**Issue by Didosior** [react-navigation/react-navigation#6362]
```
 WARN  Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: SafeView

```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |
| react-native     | 0.61.2
| node             | v8.9.0
| npm or yarn      | 1.19.0

Screen Shout; http://prntscr.com/pfuo1m

**Comment by 0xClpz** [comment]
I'd like to take this one up!

**Comment by satya164** [comment]
You should update your react navigation version. 3.x or 4.x shouldn't have any warnings.

**Comment by Didosior** [comment]
The problem continues.

**Comment by satya164** [comment]
Then open an issue by following the issue template and a runnable repro.

**Comment by dagi3d** [comment]
It keeps happening even after using 4.x with latest React version because react-navigation depends on `"@react-navigation/native": "^3.6.2"`, which uses`"react-native-safe-area-view":"0.11"` where `SafeAreaView` uses deprecated methods.
`4.0.x` version of `@react-navigation/native` uses `0.14` which has been updated

**Comment by tanoabeleyra** [comment]
Can confirm, I'm using React Native 0.61 (React 16.9) with react-navigation 4.0.5 and it's complaining about this.

**Comment by fernandoAvargas** [comment]
Hi everyone!
This warn, componentWillReceiveProps, will don´t appear in production, but is very important the solution because we need to show for clients the best results of apps and this warn is very bad for presentations.

**Comment by achourihaithem** [comment]
HI everyone!
just Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode.
for more details
https://github.com/oliviertassinari/react-swipeable-views/search?q=componentwillreceiveprops&unscoped_q=componentwillreceiveprops

**Comment by ZeerakHameem32** [comment]
Its still happening in 4.x. Any solution guys?

**Comment by allankwok** [comment]
Modify node_modules/react-native-safe-area-view/index.js
Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps

**Comment by juanlet** [comment]
you can use the modification @allankwok suggests and use the https://www.npmjs.com/package/patch-package package to apply the changes until the real fix comes in the future
