### ISSUE TITLE
React Navigation in Hacktoberfest + Software Mansion

### ISSUE THREAD

**Issue by osdnk** [react-navigation/react-navigation#6363]
https://medium.com/p/40e230715c23

Here's a list of issues:

### Good first tasks

- [stack](https://github.com/react-navigation/stack/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22good+first+issue%22)
- [tabs](https://github.com/react-navigation/tabs/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen+label%3A%22good+first+issue%22)
- [drawer](https://github.com/react-navigation/drawer/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen+label%3A%22good+first+issue%22)

### Advanced tasks

- [stack](https://github.com/react-navigation/stack/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22level%3A+advanced%22)
- [tabs](https://github.com/react-navigation/tabs/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen+label%3A%22level%3A+advanced%22)
- [drawer](https://github.com/react-navigation/drawer/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen+label%3A%22level%3A+advanced%22)
- [tab-view](https://github.com/react-native-community/react-native-tab-view/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22level%3A+advanced%22)

**Comment by Transfusion** [comment]
Hi, I'd love to contribute to fixing some of the TS types of the DrawerNavigator, but I'm confused about what is the general workflow to build from source; I have tried to install from master
![https://i.imgur.com/EVsuKRt.png](https://i.imgur.com/EVsuKRt.png) but TSC throws errors on the example app within

**Comment by satya164** [comment]
@Transfusion run `yarn bootstrap` in the root

**Comment by Transfusion** [comment]
Thanks! Now going into the `example` folder and doing `yarn start` works, trying to figure out how to get `.tsx` or `.ts` edits to be automatically transpiled to JS....

**Comment by satya164** [comment]
@Transfusion you don't need to compile to notice changes.

To test the build process that's run before publishing, you can run `yarn prepare`

**Comment by adrianha** [comment]
Do i get the prize for https://github.com/react-navigation/tabs/issues/149? 😆
