### ISSUE TITLE
react-navigation-stack doesnot exist

### ISSUE THREAD

**Issue by Fahad-Mahmood** [react-navigation/react-navigation#6364]
### Current Behavior

- What code are you running and what is happening?
``
import { createAppContainer, createSwitchNavigator } from 'react-navigation';
import { createStackNavigator } from 'react-navigation-stack';

import MainScreen from '../screens/Main';

const MainStack = createStackNavigator({
  Main: {
    screen: MainScreen,
  },
});
``
const SwitchNavigator = createSwitchNavigator({
  Main: MainScreen,
  Stack: MainStack
}, {
  initialRouteName: 'Main',
});
const AppContainer = createAppContainer(SwitchNavigator);
export default AppContainer; 
`
- Unable to resolve module 'react-navigation-stack', could not be found within project
### Expected Behavior

- Screen Without Error

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  4.0.10
| react-native     | 0.61.2
| node             | 10.14.1
| npm or yarn      | yarn 1.15.2

**Comment by satya164** [comment]
Install the package in your project.

**Comment by Fahad-Mahmood** [comment]
react-navigation-stack?

**Comment by ramanasak** [comment]
I am facing this issue 

error: bundling failed: Error: Unable to resolve module `@react-native-community/masked-view` from `node_modules\react-navigation-stack\lib\module\vendor\views\MaskedView.js`: @react-native-community/masked-view could not be found within the project.

how to solve this ?
