### ISSUE TITLE
How to add header height which is applicable for all devices

### ISSUE THREAD

**Issue by nihp** [react-navigation/react-navigation#6365]
I am using react-navigation stack and tab navigator for header and footer section.

I have used height value to design the header section. But how can I achieve the height will be vary for all devices.

For eg) I need height:140 in iPhone XS Max and in the lower modals it will be 120, 100 etc.

Any suggestion for this

**Comment by pzatorski** [comment]
Hey @nihp I think this question is more to https://stackoverflow.com
You can create a helper function which checks for the screen width and then manipulate the height value.
Here you can find how to get the device dimensions: https://facebook.github.io/react-native/docs/dimensions

I hope this will help.

**Comment by nihp** [comment]
I also have a question. In my headerTitle some screens have sub-text for the title in the header section. (i.e) header title **LIST OF NAMES** and below this, I have sub-title as **30 Students**. Both the text comes in the Header section. How to design this is same for all the screens. 


Here I have added the 30 student as a text in the screen which the LIST OF NAMES screen is implemented.

What is the best way to acheive same legnth and height I have many screens with or without sub-title.

**Comment by pzatorski** [comment]
> What is the best way to acheive same legnth and height I have many screens with or without sub-title.

I personally think that you don't need to have same height on all the screen, but if you want to you can use custom height for your Header Component. You can style each of the screen separately using `navigationOptions` or you can style the whole stack with `defaultNavigationOptions`.

Please look one more time to the docs: https://reactnavigation.org/docs/en/headers.html
