### ISSUE TITLE
Any way to add right bottom component in react-navigation

### ISSUE THREAD

**Issue by nihp** [react-navigation/react-navigation#6366]
I need to add a rightBottomIcon. I have rightIcons. Any suggestion to add the rightBottomComponent.

**Comment by pzatorski** [comment]
Hey @nihp, I don't really get this question...

**Comment by nihp** [comment]
I mean in the header section (createStackNavigator) already have **headerRight**. My question is there any way to add headerBottomRinght like a component in react-navigation.

Because I need to set an icon at right bottom of the header

**Comment by pzatorski** [comment]
Ok, great. You can find more information about the issue you are facing here:
https://reactnavigation.org/docs/en/header-buttons.html

The best practice is to check the docs of the repository first.

Thanks a lot!
