### ISSUE TITLE
Deprecation warning "[RTCRootView cancleTouches] is deprecated"

### ISSUE THREAD

**Issue by janbuerling** [react-navigation/react-navigation#6368]
### Current Behavior

- Deprecation warning "[RTCRootView cancleTouches] is deprecated" if I open the drawer menu on iPhone 11. 

<img width="243" alt="Bildschirmfoto 2019-10-10 um 11 39 55" src="https://user-images.githubusercontent.com/18394509/66557785-c109c780-eb52-11e9-84ce-ff0e36015afc.png">

### Expected Behavior

- No usage of deprecated functions

### How to reproduce

- Implement a drawer menu to an app

- My Code:

```
const DashboardStack = createStackNavigator({
  [routeNames.Dashboard]: {
    screen: DashboardScreen,
  },
});

const AppDrawer = createDrawerNavigator({
    DashboardStack,
});

const AppSwitchNavigator = createSwitchNavigator({
  AppDrawer,
});

const AppContainer = createAppContainer(AppSwitchNavigator);

const AppRouting = () => <AppContainer />;
```

### Your Environment

"react": "16.9.0",
"react-native": "0.61.2",
"react-native-gesture-handler": "^1.4.1",
"react-native-reanimated": "^1.3.0",
"react-native-screens": "^2.0.0-alpha.3",
"react-navigation": "^4.0.10",
"react-navigation-drawer": "^2.2.2",
"react-navigation-stack": "^1.9.4",

**Comment by satya164** [comment]
https://github.com/kmagiera/react-native-gesture-handler/issues/746
