### ISSUE TITLE
Header title overlaps custom component

### ISSUE THREAD

**Issue by tankpower1** [react-navigation/react-navigation#6370]
When headerLayoutPreset is set to 'left', adding a custom headerRight component gets overlapped by the title (if it's too long).

**Comment by YajanaRao** [comment]
I am facing the similar issue here 
Header title is not getting truncated
![image](https://user-images.githubusercontent.com/38914337/70245492-274e4780-179c-11ea-98e7-fb85465795a2.png)

**Comment by tankpower1** [comment]
Is there a way to bypass this?

**Comment by chpill** [comment]
I have the exact same problem shown in the screenshot above (combination of a long title and `headerRight` component) with @react-navigation/stack 5.2.9.

Is there a workaround for this? I'd rather avoid providing a custom component for the whole header...

**Comment by satya164** [comment]
Closing since you haven't provided a repro. Please open a new issue with a minimal repro if you're still having problems.
