### ISSUE TITLE
defaultNavigationOptions on a stack navigator screen config causes iOS crash on physical device

### ISSUE THREAD

**Issue by kanehara** [react-navigation/react-navigation#6371]
When using `createStackNavigator` and a screen mistakenly uses `defaultNavigationOptions` with a `headerLeft` config with a back button, it works fine on simulator but causes a crash on iOS.

### Current Behavior
Using `defaultNavigationOptions` on a screen config in a stack navigator with a `headerLeft` back button renders and works in iOS simulator but crashes on a physical device.  Changing to `navigationOptions` fixes it.

### Expected Behavior
`defaultNavigationOptions` should not work on screen configurations so this can be caught during development.

### How to reproduce
1. Create a stack navigator w/ `createStackNavigator`
2. Add a screen w/ `defaultNavigationOptions` configuration with a back button configured for `headerLeft` option
3. Simulator renders `headerLeft` back button on screen and can go navigate back pressing it
4. Same screen on a physical device causes a crash
5. Change `defaultNavigationOptions` to `navigationOptions`
6. Crash no longer occurs

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 4.0.9
| react-native     | 0.61.1
| node             | 10.15.2
| npm or yarn      | yarn 1.17.3

**Comment by chasemac** [comment]
I ran into this issue as well

**Comment by thehellmaker** [comment]
I am runnign into this issues as well. Backbutton just crashes

**Comment by Hyuchiha** [comment]
I have the same issue using HeaderBackButton on physical device

**Comment by satya164** [comment]
Keep open

**Comment by chr33s** [comment]
@satya164 this was fixed upstream and is no longer an issue, at least for me.
