### ISSUE TITLE
BUG: Full screen content on React Navigation for web

### ISSUE THREAD

**Issue by elie222** [react-navigation/react-navigation#6372]
I'd like to get the View fill the screen when using React Navigation on web. 

Is there an easy way to do this? I can change the CSS to `height: 100%` for a certain inner component, but I haven't found a way to easily access it through the react-navigation API.

Reproduction:

```
expo init
# select TS blank
yarn web
# add View style backgroundColor: "red", 
```

Sample code:

```ts
import React from "react";
import { View, Text } from "react-native";
import { createAppContainer } from "react-navigation";
import { createStackNavigator } from "react-navigation-stack";

class HomeScreen extends React.Component {
  render() {
    return (
      <View
        style={{
          flex: 1,
          alignItems: "center",
          justifyContent: "center",
          backgroundColor: "red",
        }}
      >
        <Text>Home Screen</Text>
      </View>
    );
  }
}

const AppNavigator = createStackNavigator({
  Home: {
    screen: HomeScreen
  }
});

export default createAppContainer(AppNavigator);
```

I want to do something like this:

![image](https://user-images.githubusercontent.com/3090527/66612576-e33f2c00-ebca-11e9-9213-700b2e4d03fc.png)

In practice I get something like this:

![image](https://user-images.githubusercontent.com/3090527/66612635-141f6100-ebcb-11e9-84b5-b191e18585dd.png)

**Comment by nickjanssen** [comment]
As a workaround, you can use `react-navigation@3.9`. Note that you'll have to change imports `react-navigation-stack` and `react-navigation-tabs` to import from the main package `react-navigation`.
Demo: https://snack.expo.io/@laska/react-navigation-web-with-3_9

**Comment by elie222** [comment]
That did it, thanks!
Definitely a bug in the latest version of the package.

**Comment by zachschultz** [comment]
Any updates on this bug? I've run into this issue as well

**Comment by mitschabaude** [comment]
I was able to solve this in version 1.10.3 by passing a cardStyle to the StackNavigator. In the example above, use

```javascript
const AppNavigator = createStackNavigator({
  Home: {
    screen: HomeScreen
  }
}, {
  cardStyle: { flex: 1 }
});
```

**Comment by nandorojo** [comment]
> I was able to solve this in version 1.10.3 by passing a cardStyle to the StackNavigator. In the example above, use
> 
> ```js
> const AppNavigator = createStackNavigator({
>   Home: {
>     screen: HomeScreen
>   }
> }, {
>   cardStyle: { flex: 1 }
> });
> ```

For me, it looks like this:

```es6
const AppNavigator = createStackNavigator({
  Home: {
    screen: HomeScreen
  }
 }, {
  defaultNavigationOptions: { 
    cardStyle: { flex: 1 } 
  }
});
```

**Comment by KEMBL** [comment]
for those who came here with the same problem in react-navigation v5.
It is not possible to pass params to createStackNavigator anymore, what you can do is to wrap NavigationContainer into View like that 

`<View style={{height: Dimensions.get('window').height}}>
<NavigationContainer> ...
`
and screen height will fit the window.

**Comment by isaachkwu** [comment]
> 
> 
> for those who came here with the same problem in react-navigation v5.
> It is not possible to pass params to createStackNavigator anymore, what you can do is to wrap NavigationContainer into View like that
> 
> `<View style={{height: Dimensions.get('window').height}}> <NavigationContainer> ... `
> and screen height will fit the window.

Nice workaround! I used the dimensions lib for the height value, but the height didn't change if my browser change its size. I used 100vh instead and it works perfectly.

`<View style={styles.navContainer}>
  <NavigationContainer>.......`
 and the styles are...
`const styles = StyleSheet.create({
  navContainer: {
    ...Platform.select({
      native: {
        flex: 1,
      },
      web: {
        height: '100vh',
      },
    }),
  },`
Hope this could help some of you guys!

**Comment by Adushar** [comment]
Just remove the outer <View> or <SafeAreaView> of the <NavigationContainer>. It works for me
