### ISSUE TITLE
[Typescript] NavigationScreenProp is miss some property

### ISSUE THREAD

**Issue by EternalChildren** [react-navigation/react-navigation#6373]
### Current Behavior
![image](https://user-images.githubusercontent.com/27210994/66626078-7a3ad100-ec29-11e9-8a20-8048aa0fba28.png)
![image](https://user-images.githubusercontent.com/27210994/66626086-8030b200-ec29-11e9-857f-4dbe0ec98ea5.png)
![image](https://user-images.githubusercontent.com/27210994/66626120-a5252500-ec29-11e9-84cb-10f4b0c78e5c.png)

in fact, the navigation has pop, push, etc. and the document also has a description.
but the type description file think that these methods are missing.

### Expected Behavior

fix the wrong NavigationScreenProp Type.

### How to reproduce
Using the typescript compiler, it will give an error when using the tsc command.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 4.0.10
| react-native     | 0.61.1
| node             | 
| npm or yarn      |

**Comment by satya164** [comment]
Please read the docs https://reactnavigation.org/docs/en/typescript.html

**Comment by macfanatic** [comment]
I really struggled with this as well, but here's a simple example:

```typescript
import { WithTranslation, withTranslation } from "react-i18next";
import { withNavigation } from "react-navigation";
import { NavigationStackProp } from "react-navigation-stack";

export interface TravelExpenseProps {}; // interesting project stuff

export type AllTravelExpenseProps =
  TravelExpenseProps &
  WithTranslation & {
    navigation: NavigationStackProp
  }

export class TravelExpense extends React.PureComponent<AllTravelExpenseProps> {
  // stuff...
}

const withNav = withNavigation<AllTravelExpenseProps>(TravelExpense)
export default withTranslation()(withNav);
```
