### ISSUE TITLE
Back button not working on iOS release build (rn 0.61)

### ISSUE THREAD

**Issue by SpertsyanKM** [react-navigation/react-navigation#6374]
After updating from react-native 0.59.5 to react-native 0.61.1 back button in navigation bar stopped working. It's displayed, but not clickable. On debug builds works fine, on any android build also works fine. The problem is only in iOS release build.

### Current Behavior

Pressing back button on any screen doesn't navigate back and react in any way. The same is with left-to-right swipe action.

### Expected Behavior

Back button press navigates to the previous screen in stack as in debug or android builds .

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 4.0.10
| react-navigation-stack | 1.9.4, 2.0.0
| react-native     | 0.61.1
| node             | 10.16.1
| yarn      | 1.16.0

**Comment by suriksarkisyan** [comment]
ebat' ti loh))))

**Comment by krstffr** [comment]
Are you sure the app is not crashing behind the scenes? That was the case for me, and it was due to the fact that i was not importing 'react-native-gesture-handler' in  the very first line of the index.js file which was described here: https://github.com/kmagiera/react-native-gesture-handler/issues/320#issuecomment-540849079

**Comment by SpertsyanKM** [comment]
@krstffr^ it should be crashing anytime so, regardless to build type or platform

**Comment by SpertsyanKM** [comment]
@krstffr it's interesting, but it works. Thanks a lot.

**Comment by Frosty92** [comment]
Thanks @krstffr , I had the same issue and your reply solved the problem!

**Comment by hautran96** [comment]
help, i use add import 'react-native-gesture-handler' but it not working 
 "react": "16.9.0",
"react-native": "0.61.5",
"react-native-gesture-handler": "^1.6.1",
