### ISSUE TITLE
TypeError: propListener.apply is not a function

### ISSUE THREAD

**Issue by Cleiglo** [react-navigation/react-navigation#6376]
Hi all,
It's my first time reporting an issue so be polite to me xD.
I' am facing this issue on my application, that makes my application crash, as you can see in the image below:
![image](https://user-images.githubusercontent.com/43414385/66706302-2c10f500-ed31-11e9-85bf-0bdf82997383.png)

Somehow i found the problem to be: 
![image](https://user-images.githubusercontent.com/43414385/66706346-8ca03200-ed31-11e9-99d5-f93c514a83c5.png)

I really don't know why but sometimes propListener seems to be a pending promise, so .apply result to not be a function, and this problem semms to be totally random, cause sometimes it happens and sometimes it dont and the code is always the same.

I found a way to solve this problem, adding a this line of code to check if apply is a function or not:
`
return propListener&&typeof propListener.apply==="function" &&propListener.apply`

I applied that line of code to:
 Project\node_modules\@react-navigation\core\lib\module\views\NavigationEvents.js

So now my NavigationEvent.js look like:

```
import _classCallCheck from "@babel/runtime/helpers/classCallCheck";
import _createClass from "@babel/runtime/helpers/createClass";
import _possibleConstructorReturn from "@babel/runtime/helpers/possibleConstructorReturn";
import _getPrototypeOf from "@babel/runtime/helpers/getPrototypeOf";
import _inherits from "@babel/runtime/helpers/inherits";
import React from 'react';
import withNavigation from './withNavigation';
var EventNameToPropName = {
    willFocus: 'onWillFocus',
    didFocus: 'onDidFocus',
    willBlur: 'onWillBlur',
    didBlur: 'onDidBlur'
};
var EventNames = Object.keys(EventNameToPropName);
var NavigationEvents = function (_React$Component) {
    _inherits(NavigationEvents, _React$Component);

    function NavigationEvents() {
        var _getPrototypeOf2;
        var _this;
        _classCallCheck(this, NavigationEvents);
        for (var _len = arguments.length, args = new Array(_len), _key = 0; _key < _len; _key++) {
            args[_key] = arguments[_key];
        }
        _this = _possibleConstructorReturn(this, (_getPrototypeOf2 = _getPrototypeOf(NavigationEvents)).call.apply(_getPrototypeOf2, [this].concat(args)));
        _this.getPropListener = function (eventName) {
            return _this.props[EventNameToPropName[eventName]];
        };
        return _this;
    }
    _createClass(NavigationEvents, [{
        key: "componentDidMount",
        value: function componentDidMount() {
            var _this2 = this;
            this.subscriptions = {};
            EventNames.forEach(function (eventName) {
                _this2.subscriptions[eventName] = _this2.props.navigation.addListener(eventName, function () {
                    var propListener = _this2.getPropListener(eventName);
                    return propListener && typeof propListener.apply === "function" && propListener.apply(void 0, arguments);
                });
            });
        }
    }, {
        key: "componentWillUnmount",
        value: function componentWillUnmount() {
            var _this3 = this;
            EventNames.forEach(function (eventName) {
                _this3.subscriptions[eventName].remove();
            });
        }
    }, {
        key: "render",
        value: function render() {
            return null;
        }
    }]);
    return NavigationEvents;
}(React.Component);
export default withNavigation(NavigationEvents);
//# sourceMappingURL=NavigationEvents.js.map
```

Anyway this solution seems a bit nasty to me, and can probably cause other issues even if for now i am not facing any for now, so i was wondering I am doing something wrong so i am facing this issue? Cause what's my application is basically doing is Navigating to new screen where it has to load some images.

Did someone ever face this issue and know another way to solve it?

**Comment by eriveltonelias** [comment]
Hi @Cleiglo 

Have you tried to use the latest version of react-navigation ?

**Comment by Cleiglo** [comment]
Hi @eriveltonelias 

Yeah i tried to change my package.json to use the latest version of react-navigation, the problem persist.
Here is my package.json: 
`{
  "name": "FindYourType",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "native-base": "^2.13.8",
    "react": "16.8.6",
    "react-native": "0.60.5",
    "react-native-action-button": "^2.8.5",
    "react-native-date-picker": "^2.7.0",
    "react-native-datepicker": "^1.7.2",
    "react-native-drawer": "^2.5.1",
    "react-native-elements": "^1.1.0",
    "react-native-firebase": "^5.5.6",
    "react-native-fs": "^2.14.1",
    "react-native-geolocation-service": "^3.1.0",
    "react-native-gesture-handler": "^1.4.1",
    "react-native-google-signin": "^2.0.0",
    "react-native-image-crop-picker": "^0.25.0",
    "react-native-image-picker": "^1.1.0",
    "react-native-image-resizer": "^1.0.1",
    "react-native-image-slider-box": "^1.0.5",
    "react-native-image-zoom-viewer": "^2.2.26",
    "react-native-maps": "0.25.0",
    "react-native-modals": "^0.19.6",
    "react-native-orientation": "^3.1.3",
    "react-native-popup-dialog": "^0.18.3",
    "react-native-pull-to-refresh": "^2.1.3",
    "react-native-reanimated": "^1.2.0",
    "react-native-slideshow": "^1.0.1",
    "react-native-snap-carousel": "^3.8.0",
    "react-native-swipe-gestures": "^1.0.3",
    "react-native-vector-icons": "^6.6.0",
    "react-navigation": "latest",
    "react-navigation-stack": "latest"
  },
  "devDependencies": {
    "@babel/core": "^7.5.5",
    "@babel/runtime": "^7.5.5",
    "@react-native-community/eslint-config": "^0.0.5",
    "babel-jest": "^24.9.0",
    "eslint": "^6.2.2",
    "jest": "^24.9.0",
    "jetifier": "^1.6.4",
    "metro-react-native-babel-preset": "^0.56.0",
    "react-test-renderer": "16.8.6"
  },
  "jest": {
    "preset": "react-native"
  }
}
`

here is also a screenshot for the problem using my phone, anyway its not just related to my phone also the emulator seems to have that problem: 
![image](https://user-images.githubusercontent.com/43414385/68022122-acc57000-fca3-11e9-9921-796ed66815ec.png)

If you need any further information let me know

**Comment by satya164** [comment]
Can you show your babel config?

**Comment by Cleiglo** [comment]
Hi @satya164,
Here is my `babel.config.js`:

`module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
};`
