### ISSUE TITLE
Sub Screen Navigation

### ISSUE THREAD

**Issue by danwhite-ad** [react-navigation/react-navigation#6377]
Can you do this style of navigation to a child screen?

![image](https://user-images.githubusercontent.com/40389335/66759207-ba06f000-ee97-11e9-9889-9ebfdaf11103.png)

**Comment by k3ithl1m** [comment]
Yes.

`const app = createStackNavigator(
{Main,
Email,
},
{
mode: 'modal'
});
`

**Comment by satya164** [comment]
https://blog.expo.io/re-writing-react-navigation-stack-db6a376522b1
