### ISSUE TITLE
tab icon not changing 

### ISSUE THREAD

**Issue by paddy57** [react-navigation/react-navigation#6378]
![IMG_8781](https://user-images.githubusercontent.com/22058036/66809450-ffd0c080-ef4a-11e9-8745-eaef100610de.JPG)

![IMG_9403](https://user-images.githubusercontent.com/22058036/66809107-54c00700-ef4a-11e9-95c5-4e567ac27902.JPG)

---

### Current Behavior

- If i switch to second tab, it is showing me two icon first is when search tab is inactive i.e user icon, and when it is active search icon 

### Expected Behavior

- after switching to second tab, it should show search icon.

my code

    Search: {
      screen: Search,
      showLabel: false,
      navigationOptions: {
        barStyle: styles.barStyleForRemainingTab,
        showLabel: false,
        tabBarIcon: ({ tintColor, focused }) => (
          focused ?
            <Icon
              name="magnify"
              size={25}
              color='#000000'
            /> :
            <Icon
              name="account"
              size={25}
              color='#CCCCCC' 
            />
        ),
      },
    },

### Your Environment

| react-navigation: ^2.11.2", |
| react-native  :"0.60.5"   |

**Comment by satya164** [comment]
Please fill the issue template when opening an issue.
