### ISSUE TITLE
[RN 0.61] fast refresh  reset route to initialRoute

### ISSUE THREAD

**Issue by KingAmo** [react-navigation/react-navigation#6379]
### Current Behavior
`React Native 0.61.2`, enable `fast refresh` , in a deep stack route, when  change and save your code, app refreshing and reset route to initialRoute

### Expected Behavior
when `fast refresh` refreshing,  the route does not reset, app stay in the deep route

### How to reproduce
stack navigation , in `home screen`, navigate to `detail screen`, change and save your code, then `fast refresh` refreshing and the route reset to `home screen`
### Your Environment
```
System:
    OS: macOS 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 54.42 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.3.1 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.1, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 21, 23, 26, 27, 28
      Build Tools: 23.0.1, 26.0.1, 28.0.3, 29.0.2
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5900203
    Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.2 => 0.61.2
```

| software         | version
| ---------------- | -------
| react-navigation | ^4.0.0
| react-native     | 0.61.2
| node             |
| npm or yarn      |

**Comment by JonnyBurger** [comment]
You are most likely calling create*TabNavigator inside the render function. Move it outside the render function and only use it's return value inside the the render function and then Fast Reload works for me.

**Comment by Manishalexin** [comment]
@JonnyBurger Can you explain on what do you mean by calling createNavigator's outside the render function. Below vanilla code doesn't let the fast refresh stay on second page.

`const App = props => {
  return (
    <View>
      <Text>Home Screen</Text>
      <Button
            title="Go to Detail"
            onPress={() => props.navigation.navigate('Detail')}
          />
    </View>
  );
};

const Detail = () => {
  return (
    <View>
      <Text>Detail Page</Text>
    </View>
  );
};

const AppNavigator = createStackNavigator({
  App,
  Detail,
});

export default createAppContainer(AppNavigator);`

**Comment by guilhermegonzaga** [comment]
Same problem :(
Fast refresh reset route to initialRoute

**Comment by kkirby** [comment]
I ended up using persistence functions for development. It's not ideal but it works.

```javascript
const persistenceFunctions = (() => {
  return __DEV__
    ? {
        async persistNavigationState(value: any) {
          GLOBAL.__nav__state = value;
        },
        async loadNavigationState() {
          if (GLOBAL.__nav__state == null) {
            await Promise.reject('no data');
          }
          return GLOBAL.__nav__state;
        },
      }
    : {};
})();

cont App = () => {
  return <AppContainer
    {...persistenceFunctions}
  />;
};
```
