### ISSUE TITLE
WebView on page of a tabNavigator set to 'lazy: false' does not load until page gains focus when using react-native-webview

### ISSUE THREAD

**Issue by connor-odoherty** [react-navigation/react-navigation#6380]
### Current Behavior

When rendering tabs in a tabNavigator configured with `lazy: false`, the WebView does not launch until the page it is rendered on is "active".

This was not an issue when using Expo v34 and their WebView product, which makes me think this is more a react-native-webview issue than a react-navigation issue.

For example:

I use react-navigation to create a `bottomTabNavigator`. When I set `lazy` to false, it renders all tabs, both the one currently focused, and all the other tabs in the background.

On some of these pages, I render a WebView. However, despite the components still loading and rendering the background, the WebView does not launch (onLoadStart doesn't even start) until I navigate to the page it is contained on.

### Expected Behavior

The WebView should have already been loaded in the background, before I navigated to the page.

### How to reproduce

From a StackOverflow with the same issue:

```
Tab

const Tab = () => { 
    console.log('render') // this is being called right away

    return (<WebView 
             onLoadStart={() => console.log('on load start') // this is being called only when tab becomes active (clicking on it) }
             source={{uri:'linkgoes.here'}} />) 
}
```

```
  const TabNavigator = createBottomTabNavigator(
  {
    TabOne: {
      screen: Tab
    },
    TabTwo: {
      screen: Tab
    }
  },
  {
    initialRouteName: 'TabOne',
    lazy: false,
  }
)
```

You will see that the WebView does not start until the page gains focus.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.11.1
| react-native     |    https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz
| node             |        12.10.0
| npm or yarn      |   1.17.3

### Some extra info:

Looks like it's a bug where it returns early if no window is present

This SO user had a similar experience: https://stackoverflow.com/questions/56923273/react-native-webview-only-starts-loading-when-on-active-tab-in-react-navigation

There is PR out to solve the issue, but it looks like it comes with a bunch of bad side effects: https://github.com/react-native-community/react-native-webview/pull/813

Again, I know this isn't a react-navigation issue, but suggestions for a workaround would be greatly appreciated!

**Comment by satya164** [comment]
I don't think there's anything we can do about it. Closing since this isn't an issue we can address.

**Comment by connor-odoherty** [comment]
@satya164 Is there not a way to iterate through each of the tabs while under a splash screen or something on startup? Or a way to spoof the window on each of the pages?

**Comment by satya164** [comment]
You can implement your own tab navigator however you like https://reactnavigation.org/docs/en/custom-navigators.html
