### ISSUE TITLE
Show tabBarlabel  for createMaterialBottomTabNavigator even inactive

### ISSUE THREAD

**Issue by jackhts4** [react-navigation/react-navigation#6381]
Now label will be hidden if the it is not active
How can I show the label even it is inactive

Example:
https://timomeh.gitbook.io/material-bottom-navigation/
Demo - Full Tab

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 4.0.10
| react-native     | 35.0.0
| node             | 
| npm or yarn      |

**Comment by satya164** [comment]
Please read the docs https://reactnavigation.org/docs/en/next/material-bottom-tab-navigator.html#shifting
