### ISSUE TITLE
How can I push react native view from UIViewController?

### ISSUE THREAD

**Issue by devyu** [react-navigation/react-navigation#6382]
Hi Guys, I have a react native project and nest some native code using Objective-C. I already push a UIViewController from the PageA.js. In this UIViewController, I want to push PageB.js but cannot work. when I see the view hierarchy, the PageB behind the UIViewController, How can I push the react-native page from UIViewController? the PageB above on UIViewController, Just like UINavigationController Stack in ios.

---

| software         | version
| ---------------- | -------
| react-navigation | ^3.3.2
| react-native     | ^0.58.6

**Comment by satya164** [comment]
https://github.com/callstack/react-native-brownfield
