### ISSUE TITLE
createMaterialBottomTabNavigator

### ISSUE THREAD

**Issue by DavidJas** [react-navigation/react-navigation#6383]
## Header in createMaterialBottomTabNavigator

After update react-navigation to version next I cannot hide the header. Maybe I created the wrong stack with tabs. 

Home is stack with tabs.
   <Stack.Screen
            key="home"
            component={TabNavigator}
            name="home"
            options={{
              ...defaultHeaderOptions,
            }}
          /> 

const TabNavigator = () => (
  <Tab.Navigator
    activeColor={Colors.white}
    barStyle={{ backgroundColor: Colors.grey }}
    inactiveColor={Colors.white}
    initialRouteName="tracking"
    shifting={false}
  >
    <Tab.Screen component={TrackingContainer} name="tracking" navigationOptions={{ header: null }} />
    <Tab.Screen component={DevicesContainer} name="devices" navigationOptions={{ header: null }} />
    <Tab.Screen component={PreferencesContainer} name="preferences" navigationOptions={{ header: null }} />
  </Tab.Navigator>
)
---

### Expected Behavior
I need to hide the header in different cases.

### Environment

| software         | version
| ---------------- | -------
| react-navigation | next
| react-native     | 60.6

**Comment by satya164** [comment]
https://reactnavigation.org/docs/en/next/stack-navigator.html#headershown
https://reactnavigation.org/docs/en/next/screen-options-resolution.html
