### ISSUE TITLE
react-navigation-drawer [RCTRootView CancelTouches] is deprecated.

### ISSUE THREAD

**Issue by Leminur** [react-navigation/react-navigation#6386]
### Current Behavior
I am simply using `createDrawerNavigator` and React Native CLI. This error only happens in iOS systems, Android systems are excluded. The system allows drawer navigation as it should, but once the drawer is open, and the user clicks outside the drawer to close, [this warning message](https://user-images.githubusercontent.com/9650859/67040242-74496200-f0f9-11e9-83cc-801bc50f2e2f.png) shows up. 
It does not prevent me from navigating, yet this warning message shows up every time I try to close the drawer by using this method. And according to the warning, such function might be deleted in the future.

### Expected Behavior

The drawer should be closed without a warning message.

### How to reproduce
(Unfortunately, I could not reproduce this using Expo CLI, as it works without giving a warning. It only shows using React Native CLI.)

- Import createDrawerNavigator.
- Create some options for navigation.
`const MainNavigator = createDrawerNavigator(
  {
    Main: MainTabNavigator,
    Register: RegisterNavigator,
    Login: LoginNavigator,
  },
  {
    contentOptions: {
      activeTintColor: 'red',
    },
  },
);`

- Click outside the drawer window, as the red square shows [in this image](https://user-images.githubusercontent.com/9650859/67040241-73b0cb80-f0f9-11e9-9a23-02bd5e5c6cf1.png).
### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 4.0.10
| react-navigation-drawer | 2.2.2
| react-native     | 0.61.2
| node             | 12.12.0
| npm       | 6.12.0

**Comment by cipriancaba** [comment]
I think this is related to https://github.com/kmagiera/react-native-gesture-handler/issues/746

**Comment by Leminur** [comment]
@cipriancaba You are right! Other users are experiencing it in other dependencies. Using YellowBox stops triggering the warning, but this might get deleted soon and the gesture to close the drawer might not work. Thanks for finding a temporary solution though!

**Comment by cipriancaba** [comment]
@Leminur the problem is that this still crashes in production builds.. I guess the best bet is to disable the gestures for now?

**Comment by Leminur** [comment]
Wait, really? I did not know that production builds are having trouble. I guess you are right, disabling the gestures would be for the best until it's fixed.

**Comment by satya164** [comment]
See https://github.com/kmagiera/react-native-gesture-handler/pull/796
