### ISSUE TITLE
How to change navigationOptions tabBarLabel language based on conditions

### ISSUE THREAD

**Issue by HemanthSurimani** [react-navigation/react-navigation#6389]
How to change navigationOptions tabBarLabel language based on condition
i want to change tabBarLabel language 

Trending: { screen: TrendingComponent,
        navigationOptions: {
           tabBarLabel: {this.language == "English" ? 'Trending:'తీరు'}
       },
"react-native": "0.59.8",
"react-navigation": "^3.11.0",
please help me,
thanks.

**Comment by satya164** [comment]
https://reactnavigation.org/docs/en/localization.html
