### ISSUE TITLE
undefined is not a function 'navigation.navigate'

### ISSUE THREAD

**Issue by fabioplaka** [react-navigation/react-navigation#6391]
I am testing something in React-Native and I have an error with **React-Navigation** library that said: **TypeError:undefined is not a function(evaluating 'navigation.navigate')**. Based to official documentation of react-navigation library I have done the code:

**Navigation.js**
`import 'React' from 'react;'`
`import {createAppContainer} from 'react-navigation';`
`import {createStackNavigator} from 'react-navigation-stack';`
`import MainScreen from './History';`
`import AirmineScreen from './AirmineApp';`

`const MainNavigator = createStackNavigator({`
    `MainScreen: {screen:MainScreen},`
   `HistoryScreen: {screen: HistoryScreen}`
});`

`const Navigation = createAppContainer(MainNavigator);`
`export default Navigation;`

**Main.js**
`import { StackNavigator } from 'react-navigation';`
`render(){`
    `const navigation = this.props.navigation;`
   ` return (`
        `<TouchableOpacity onPress={() => navigation.navigate('HistoryScreen')}>`
               ` <Text>history</Text>`
        ` </TouchableOpacity>`
   ` )`
`}`

**Comment by pzatorski** [comment]
Hey @fabioplaka it will be great if you can provide runnable. I suggest to use https://snack.expo.io/

**Comment by fabioplaka** [comment]
I just solve it, it was an idiot error

**Comment by sameersankalp** [comment]
> I just solve it, it was an idiot error

how did you solve it

**Comment by vyaskartik20** [comment]
How did you solve it?

**Comment by rgarimella0124** [comment]
How did you solve it ? @fabioplaka

**Comment by carsanbravo** [comment]
la verdad es una  {} de llaves en la declaracion

ejemplo :

el error da en mi caso por que colocaba navigation sin {}
const Meals = (  navigation  ) => {

solucion  colocar { navigation }
const Meals = ( { navigation } ) => {


const Meals = ( { navigation } ) => {
    return (
      <View style={styles.container}>
       <FlatList
          style={styles.list}
          data={data}
          keyExtractor={ x => x._id}
          renderItem={({ item }) =>
            <ListItem
            onPress={() => navigation.navigate('Modal', { _id: item.id })}
            name={item.name}
             />} 
    />
      </View>  
    )
}

**Comment by shivamjjha** [comment]
This can be solved either by
1. [undefined is not a function (evaluating '_reactNativr.default.createElement')](https://stackoverflow.com/a/54551682/11667949), or
2. [React Native Navigation Undefined is not a function](https://stackoverflow.com/a/45196212/11667949)

**Comment by theneto16** [comment]
What the fuck, first you ask and you leave with the answers without saying anything, selfish

**Comment by fabioplaka** [comment]
> What the fuck, first you ask and you leave with the answers without saying anything, selfish

What the fuck, it's been 4 years and you still expect an answer??

**Comment by zaclapaille** [comment]
I found the solution: when he imported the prop navigation he did not put the {} around it so it was not read as an object 👍 

function HomeScreen(navigation) { <---------  replace by HomeScreen({navigation})
return (
<View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
Home Screen
<Button
title="Go to Dtails"
onPress={() => navigation.navigate('Details')}
/>

);
}
