### ISSUE TITLE
React navigation drawer issue (gestures are not working properly)

### ISSUE THREAD

**Issue by 1sujith** [react-navigation/react-navigation#6392]
## The issue tracker is reserved for bug reports only.
---

### Current Behavior

- What code are you running and what is happening?
-running basic react native drawer app and 
--new version - gestures not working properly (click outside the container and drawer does not close except that everything working fine)
--old version- gestures are working properly (react-navigation ^3.11.1)

### Expected Behavior

- What do you expect should be happening?
--gestures should work properly

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |4.0.5|
|react-navigation-drawer|2.2.1|
| react-native     |0.61.1|
| node             |10.16.0|
| npm or yarn      |6.11.3|

**Comment by pzatorski** [comment]
Please fill the issue template when opening an issue and provide a runnable repro.
