### ISSUE TITLE
Custom Navigator example does not have navigation prop

### ISSUE THREAD

**Issue by NicWickman** [react-navigation/react-navigation#6395]
---

### Current Behavior
I am trying to follow the custom navigator example in the documentation to check for changes to my navigation prop, and navigate to a new screen when a condition is met. But, the custom navigation component does not have access to the navigation prop like the documentation states it would.

```
const AppStackBase = createStackNavigator({...})

class AppStack extends React.Component {
  constructor(props) {
    super(props);
  }
  static router = {
    ...AppStackBase.router,
    getStateForAction: (action, lastState) => {
      return MyStack.router.getStateForAction(action, lastState);
    }
  };

  componentDidUpdate(prevProps) {
    if (condition){
      this.props.navigation.navigate("Screen")
    }
  }

  render() {
    const { navigation } = this.props;

    return (
      <AppStackBase
        navigation={navigation}
        screenProps={this.props.screenProps}
        {...this.props}
      />
    );
  }
}


const Navigation = () => {
  return (
    <AppStack
      ref={navigatorRef => {
        NavigationService.setTopLevelNavigator(navigatorRef);
      }}
    />
  );
};
```

"navigation" is undefined.

### Expected Behavior
I would expect to have access to the navigation prop.

### How to reproduce

Code provided

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | "2.18.3"
| react-native     | "0.57.7"

**Comment by satya164** [comment]
You need to render the navigator with `createAppContainer` or another navigator, and forward the props in your `Navigation` component. You're only adding a ref and ignoring all props in your `Navigation` component.
