### ISSUE TITLE
Unmount inactive screens in bottom tab navigator

### ISSUE THREAD

**Issue by BravenxX** [react-navigation/react-navigation#6396]
Im using react-navigation v3, is there an option to make that inactive tab screens get unmounted like   unmountInactiveRoutes: true in DrawerNavigator?? I cant find something like unmountInactiveRoutes for BottomTabNavigator.

I have two stacknavigators inside a BottomTabNavigator and I want to unmount them automatically.

**Comment by Mikoz93** [comment]
I an older version of React Navigation you used to be able to set `animationEnabled: false` in the TabNavigator config, this unmounted any stack that's not in the currently active tab but also removed the tab switching animation. Not sure if this is still available.

**Comment by satya164** [comment]
> set animationEnabled: false in the TabNavigator config, this unmounted any stack that's not in the currently active tab

It's not true

**Comment by BravenxX** [comment]
Well I couldn't find anything so if someone have a similar problema I recommend work with Redux. If u need to refresh a screen if another get changed just try to listen the changed in a boolean redux param. 

```
useEffect (() => { 
<what you want to do here> 
},[props.reduxVar]) 
```

**Comment by joshualimpj** [comment]
Do this 
`
const resetAction = StackActions.reset({
      index: 0,
      actions: [NavigationActions.navigate({ routeName: <ROUTE_NAME> })],
    });
    this.props.navigation.dispatch(resetAction);
`
Replace ROUTE_NAME with which ever screen you want to navigate to. It should unmount all screens associated with the previous screen.
