### ISSUE TITLE
[v5.0] Missing Example using Nested/Multiple Stacks inside NavigationNativeContainer

### ISSUE THREAD

**Issue by luancurti** [react-navigation/react-navigation#6397]
### Current Behavior

- Multiple Stacks Code
<img width="554" alt="Screen Shot 2019-10-18 at 16 16 19" src="https://user-images.githubusercontent.com/7242605/67121775-b7bbd300-f1c2-11e9-8240-0ce44d3c3774.png">

- Multiple Stacks Error
![Screen Shot 2019-10-18 at 16 16 39](https://user-images.githubusercontent.com/7242605/67121794-c0aca480-f1c2-11e9-9a85-beb3dd6b4792.png)

- Nested Stacks Code
<img width="581" alt="Screen Shot 2019-10-18 at 16 18 16" src="https://user-images.githubusercontent.com/7242605/67121869-e9349e80-f1c2-11e9-9321-72e6777743e2.png">

- Nested Stacks Error
![Screen Shot 2019-10-18 at 16 18 41](https://user-images.githubusercontent.com/7242605/67122104-6eb84e80-f1c3-11e9-8620-1e7acc1086b0.png)

### Expected Behavior

- Need Example Like this https://reactnavigation.org/docs/en/next/hello-react-navigation.html but showing Nested Stacks example and Multiple Stacks

### Your Environment

| software         | version
| ---------------- | -------
|@react-navigation/core | 5.0.0-alpha.15
|@react-navigation/native | 5.0.0-alpha.12
|@react-navigation/native-stack | 5.0.0-alpha.1
|@react-navigation/stack | 5.0.0-alpha.26
| react-native     | 0.61.2
| node             | 10.16.2
| yarn      | 1.19.0

**Comment by satya164** [comment]
There are 2 rules:
- The container can have only a single navigator
- Navigators can only contain `Screen` as children.

So any component you want to have under a navigator (whether a component renders a navigator or not doesn't matter) needs to be inside a screen.

**Comment by nicolas-amabile** [comment]
Hey, I know it's an old issue and might not be 100% related to my question, but is it possible to wrap the nested navigator in a custom provider?
Something like:
```
function HomeTabs() {
  return (
    <CustomContextProvider>
      <Tab.Navigator>
        <Tab.Screen name="Home" component={Home} />
        <Tab.Screen name="Feed" component={Feed} />
        <Tab.Screen name="Notifications" component={Notifications} />
      </Tab.Navigator>
    </CustomContextProvider>
  );
}

function App() {
  return (
    <Stack.Navigator>
      <Stack.Screen name="Home" component={HomeTabs} />
      <Stack.Screen name="Profile" component={Profile} />
      <Stack.Screen name="Settings" component={Settings} />
    </Stack.Navigator>
  );
}
```

If I try something like that, I get `Error: Got an invalid name (undefined) for the screen. It must be a non-empty string`.

I posted a question on StackOverflow [here](https://stackoverflow.com/questions/63795195/nested-stack-navigator-with-context-provider)
