### ISSUE TITLE
react-navigation4x  Use  createBottomTabNavigator

### ISSUE THREAD

**Issue by hainanzhang** [react-navigation/react-navigation#6400]
![Screenshot_2019-10-21-13-44-31-177_com awesomepro](https://user-images.githubusercontent.com/45220026/67179644-841eba00-f409-11e9-8b70-1e04bf104288.png)

![image](https://user-images.githubusercontent.com/45220026/67179650-8a149b00-f409-11e9-8093-6ccd5d558489.png)
![image](https://user-images.githubusercontent.com/45220026/67179654-926cd600-f409-11e9-9591-2f2ba0ce7f89.png)

**Comment by satya164** [comment]
https://github.com/react-navigation/react-navigation/releases/tag/v4.0.0
