### ISSUE TITLE
Header is unmounted when navigating 3 levels down in a stack

### ISSUE THREAD

**Issue by Macksen** [react-navigation/react-navigation#6402]
### Current Behavior

I have a search screen that has a `TextInput` in the react-navigation `headerTitle` and while navigating 3 levels down into the search screen results, the header is unmounted.

E.g. each letter represents a screen where screen **A** represents the search screen and **D** a nested screen 3 levels down.

**A** -> B -> C -> **D**

From screen **A** I am searching on something and getting some results, then I am navigating down **3 levels** to screen **D** which unmounts the header of screen **A**. 
However, when I go back to screen **C** it is mounted again. 

This causes the `TextInput` on screen **A** to be empty when navigating back.

This always and only happens 3 levels down.
This does not apply to the actual screen component, only the header.

### Expected Behavior

The header in react-navigation should not unmount when navigating deeper into a stack.

### How to reproduce

Create a root screen that has a `TextInput` in the header and fill in some text, then create a few nested screens and navigate **3 levels** down and then back to the root screen again and the `TextInput` should be cleared.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | v4.0.10
| react-native     | v0.60.0
| node             | v12.4.0
| npm or yarn      | yarn

**Comment by vonovak** [comment]
hello, the unmounting is expected behavior; You'll have to keep the textinput state somewhere outside of the component, like mobx or redux.

**Comment by 2ducanhpham** [comment]
same issue. How to disabled 3 level
