### ISSUE TITLE
tabBarOnPress is not fired

### ISSUE THREAD

**Issue by SmirnovM91** [react-navigation/react-navigation#6406]
![image](https://user-images.githubusercontent.com/32675072/67308298-b02a6000-f51b-11e9-9eac-2c5ac3526820.png)

"react-navigation": "^4.0.10",
"react-navigation-stack": "^1.10.2",
"react-navigation-tabs": "^2.5.6",
"react-native": "0.61.2",
npm: 6.11.3

console.log("object") is not printing.

Help please.

**Comment by ralph-dev** [comment]
You have placed this in the wrong section of the code, please review the document. This is SCREEN specfic.

**Comment by eriveltonelias** [comment]
thanks @ralph-dev 


@SmirnovM91 https://reactnavigation.org/docs/en/bottom-tab-navigator.html
