### ISSUE TITLE
Invariant violation: TurboModuleRegistry.get(...): 'LinkingManager'

### ISSUE THREAD

**Issue by antunesgabriel** [react-navigation/react-navigation#6409]
Hi, i am trying to add react-navigation to my project, but I am getting this error:

```
Running "Elon" with {"rootTag":11}
 WARN  Possible Unhandled Promise Rejection (id: 0):
TypeError: undefined is not an object (evaluating '_reactNative.Linking.addEventListener')
componentDidMount$@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:107555:39
tryCatch@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:25669:23
invoke@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:25844:32
tryCatch@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:25669:23
invoke@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:25745:30
http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:25775:19
tryCallTwo@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:27033:9
doResolve@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:27197:25
Promise@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:27056:14
callInvokeWithMethodAndArg@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:25774:29
enqueue@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:25779:157
async@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:25795:69
componentDidMount@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:107531:44
commitLifeCycles@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:20555:45
commitLayoutEffects@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:22899:29
invokeGuardedCallbackImpl@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:9039:21
invokeGuardedCallback@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:9135:42
commitRootImpl@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false:22706:36
commitRootImpl@[native code]
```

### Current Behavior
<img src="https://imgur.com/tqbhSYK.png" width="200" height="400" alt="erro print 1"/>
<img src="https://i.imgur.com/SLYjyAR.png" width="200" height="400" alt="erro print 2"/>
<img src="https://imgur.com/8UzdTue.png" width="200" height="400" alt="erro print 3"/>

### Expected Behavior

- I hope the component will be assembled without this error, before deploying the screens, was not giving error.

### How to reproduce

>  git clone https://github.com/antunesgabriel/elon
- cd elon
- yarn or npm i
- in react-native 0.60 >,  the links are automatic.
- in ios you need : 
> cd ios 
> pod install
> cd ..
- up you device emulator
- react-native run-android or react-native run ios

### Environment

| software         | version
| ---------------- | -------
| react-navigation | ^4.0.10
| react-native     | 0.61.2
| node             | 10.16.3
| npm or yarn      | 1.19.1

System:
    OS: Linux 5.0 Ubuntu 19.04 (Disco Dingo)
    CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
    Memory: 1.69 GB / 7.66 GB
    Shell: 5.5.1 - /usr/bin/zsh
  Binaries:
    Node: 10.16.3 - /usr/bin/node
    Yarn: 1.19.1 - /usr/bin/yarn
    npm: 6.9.0 - /usr/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    Android SDK:
      API Levels: 27, 28
      Build Tools: 28.0.3, 29.0.2
      System Images: android-28 | Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.2 => 0.61.2

**Comment by brentvatne** [comment]
you should link the Linking library in your app: https://facebook.github.io/react-native/docs/linking

**Comment by Jalson1982** [comment]
Hello. Have the same issue all worked then just stopped? IOS works fine android makes me issue. How did you solve it?

**Comment by girvX** [comment]
Same error here, i don't have idea for this problem: 'LinkingManager', could not be found...

**Comment by Jalson1982** [comment]
Actually I fixed this issue and this is not a react-navigation problem. I had in my code stupid error: Platform.OS = 'ios' and it should be Platform.OS === 'ios'. So I apologize it was my mistake and probably you have something in code same.

**Comment by girvX** [comment]
> Actually I fixed this issue and this is not a react-navigation problem. I had in my code stupid error: Platform.OS = 'ios' and it should be Platform.OS === 'ios'. So I apologize it was my mistake and probably you have something in code same.

Nooo way Jalson1982! Thank you, i'm using KeyboardAvoidingView and inside i had the prop enabled={Platform.OS = 'ios'}, and I fix it! Thank you so much!

**Comment by surajsawant786** [comment]
Bless you! , even I had the same issue, where I was using Platform.OS = 'android' && Platform.Version >= 21 to use the TouchableNativeFeedback. Thank You!

**Comment by GFBorelli** [comment]
Thank you!!!!! @Jalson1982

**Comment by bachbonglong** [comment]
> Actually I fixed this issue and this is not a react-navigation problem. I had in my code stupid error: Platform.OS = 'ios' and it should be Platform.OS === 'ios'. So I apologize it was my mistake and probably you have something in code same.

Thanks you so much !!!!!
