### ISSUE TITLE
How to move app to background on back button andoid

### ISSUE THREAD

**Issue by acollazomayer** [react-navigation/react-navigation#6411]
Is there a way to put the app on the background when pressing back button on android. Thanks

**Comment by ralph-dev** [comment]
https://facebook.github.io/react-native/docs/backhandler

You are looking for this: 
https://facebook.github.io/react-native/docs/backhandler#exitapp

React Navigation also has a back handler function override control here: 
https://reactnavigation.org/docs/en/custom-android-back-button-handling.html#docsNav

**Comment by acollazomayer** [comment]
I solve this by adding this on the MainActivity.java file:
```
@Override
    public void invokeDefaultOnBackPressed() {
        moveTaskToBack(true);
    }
```

**Comment by ralph-dev** [comment]
Great, can you close the issue then!
