### ISSUE TITLE
Back Button not working on Release Mode

### ISSUE THREAD

**Issue by jjpatel1996** [react-navigation/react-navigation#6412]
### Current Behavior
 - In Debug mode Back Button working as expected but in release build it's not working even back gesture not working. Please find attached screenshot of Navigation Stack.
`export const HomeTabStack = createStackNavigator(
         {
           HomeView: {
             screen: HomeScreen
           },
           TalentProfileView: {
             screen: TalentProfileScreen,
             navigationOptions: () => ({
               headerBackTitle: null,
               headerTintColor: "black"
             })
           },
           TalentListScreen: {
             screen: TalentListScreen,
             navigationOptions: () => ({
               headerBackTitle: null,
             })
           }
         },
         {
           headerLayoutPreset: "left"
         }
       );
`

### Expected Behavior?

-Back button should work on release mode too as there are no code changes in release build.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | "^4.0.10"
| react-native     | "0.61.2"
| node             | . v10.16.0
| npm or yarn      | 6.9.0

**Comment by satya164** [comment]
See https://github.com/kmagiera/react-native-gesture-handler/issues/320

**Comment by mikehardy** [comment]
and maybe https://github.com/kmagiera/react-native-gesture-handler/issues/792 - a possible fix
