### ISSUE TITLE
resetting stack from nested navigators

### ISSUE THREAD

**Issue by magna25** [react-navigation/react-navigation#6414]
### Current Behavior
I'm working on an app that allows users to login and access full features or use other features without logging in.
when user requests server resources, the token stored on the app is checked and if it has expired, the user should logged out.
I'm trying to sign the user out by navigating to `Account` screen.
I'm getting Error: `There is no route defined for key Account`

- What code are you running and what is happening?
basically I don't want to return to the last page after navigating the user to Account screen and I'm using the reset method but it's throwing an error.
  
    `const resetAction = StackActions.reset({
                        index: 0,
                        key:null,
                        actions: [
                          NavigationActions.navigate({ routeName: 'Account'})
                        ] })
                    this.props.navigation.dispatch(resetAction);`

- Include a screenshot if it makes sense.

### Expected Behavior

- What do you expect should be happening?
the current stackNavigator should be reset and I should be able to navigate to Account screen

### How to reproduce
press the button on this snack
https://snack.expo.io/BJ3gJy-qB

**Comment by DovletAmanov** [comment]
I have same issue and even issue includes required rules for posting issue, it didn't get attention :/
