### ISSUE TITLE
react-navigation-drawer won't close When pressed outside #112

### ISSUE THREAD

**Issue by iamsapankumar** [react-navigation/react-navigation#6415]
import React, {Component} from 'react'
import { View, Text, TouchableOpacity } from 'react-native'
import { createAppContainer } from 'react-navigation'
import { createStackNavigator } from 'react-navigation-stack'
import { createDrawerNavigator, DrawerActions } from 'react-navigation-drawer'
import Icon from 'react-native-vector-icons/Ionicons'

class Home extends Component{
    render(){
        return(
            <View>
                <Text> Home</Text>
            </View>
        )
    }
}
class Setting extends Component{
    render(){
        return(
            <View>
                <Text> Setting</Text>
            </View>
        )
    }
}

const MenuIcon =({navigation})=>{
    return(
        // <TouchableOpacity onPress={()=> navigation.dispatch(DrawerActions.toggleDrawer())}>
        <TouchableOpacity onPress={()=> navigation.openDrawer()}>
            <Icon name='md-menu' size={25}/>
        </TouchableOpacity>
    )
}

const HomeStack = createStackNavigator({
    Home: { screen: Home}
},{
    defaultNavigationOptions:({navigation})=>({
        headerLeft:<MenuIcon navigation ={navigation}/>
    })
})
const SettingStack = createStackNavigator({
    Setting:{ screen: Setting}
},{
    defaultNavigationOptions:({navigation})=>({
        headerLeft:<MenuIcon navigation={navigation}/>
    })
})

const DrawerStack = createDrawerNavigator({
    HomeStack,
    SettingStack
},{
    drawerType:'front'
})
const AppContainer = createAppContainer(DrawerStack)
class App extends Component{
    render(){
        return(
            <AppContainer/>
        )
    }
}
export default App

**Comment by du-hernandez** [comment]
Hello @iamsapankumar, yesterday I had the same problem. I solved it following the installation instructions on the official site (https://reactnavigation.org/docs/en/getting-started.html).
On the other hand, I had a problem using the createDrawerNavigator and createMaterialTopTabNavigator component, but it was evident only when I generated the .apk release; the application quits unexpectedly when you slide your finger to show the createDrawerNavigator component or when you try to change the screen in the createMaterialTopTabNavigator component. I am not sure if it is a problem of react-navigation or it was my configuration (although I did it as indicated by the official documentation)

**Comment by whallysson** [comment]
I have the same problem, when switching the screen or sliding the screen with a createDrawerNavigator, the app closes unexpectedly. How do I solve this? I already followed the documentation and it didn't work out.

**Comment by daheeahn** [comment]
I had too, how can I solve this?

**Comment by du-hernandez** [comment]
Hi @whallysson, I resolved it not in the best way, for my requirement it did not affect. What I did was disable such a function with `swipeEnabled: false`. I haven't found a real solution yet

**Comment by satya164** [comment]
https://github.com/react-navigation/drawer/commit/22202522d5cb8b553a68a5b69167ccce07a66993

**Comment by whallysson** [comment]
For me I decided by upgrading "`react-navigation-drawer`" to version "`^2.3.2`", and then adding the line `import 'react-native-gesture-handler';` in my `index.js`. 

`import 'react-native-gesture-handler';

import {AppRegistry} from 'react-native';
import App from './App';
import {name as appName} from './app.json';

AppRegistry.registerComponent(appName, () => App);`

I hope it serves someone else this solution.

**Comment by edritech93** [comment]
same for me
