### ISSUE TITLE
hidden Bottom Tab Navigator is shown for less than a sec when keyboard comes up 

### ISSUE THREAD

**Issue by reza-ss** [react-navigation/react-navigation#6418]
### Current Behavior

- hidden Bottom Tab Navigator is shown for less than a sec when keyboard comes up 
![untitled](https://user-images.githubusercontent.com/47644333/67727395-8501ae00-f9fe-11e9-9328-efcca79e9d9e.gif)

### Expected Behavior

- it has to be hidden because i hid it in this page!

### my code
<h3>user.js</h3>
<pre>
function Users(props) {
    return (
      <>
        <View style={{flex: 1, paddingHorizontal: 15}}>
          <Text
            onPress={() => {
              console.log('pressed');
              props.navigation.navigate('AddUser');
            }}
            style={style.addBTN}>
            افزودن کاربر
          </Text>
          <UsersList></UsersList>
        </View>
      </>
    );
  }
  const navigation = createStackNavigator(
    {
      Users: {
        screen: Users,
        navigationOptions: {headerShown: false},
      },
      AddUser: {
        screen: AddUser,
      },
    },
    {},
  );
  navigation.navigationOptions = ({navigation}) => {
    let {routeName} = navigation.state.routes[navigation.state.index];
    let navigationOptions = {};
    if (routeName === 'AddUser') {
      navigationOptions.tabBarVisible = false;
    }

    return navigationOptions;
  };
  export default navigation;
</pre>
</br>
<h3>app.js</h3>
<pre>
const MainStack = createMaterialBottomTabNavigator(
  {
    Users: {screen: Users},
    Costs: {screen: Library},
    Trips: {screen: B},
  },
  {
    initialRouteName: 'Costs',
    activeColor: '#f0edf6',
    shifting: true,
    defaultNavigationOptions: SetNavigationMenuConfig,
  },
);
export default createAppContainer(MainStack);
</pre>
### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^4.0.10
| react-native     | 0.61.2
| node             |10.16.3
| npm or yarn      | 6.9.0
react-navigation-material-bottom-tabs | ^2.1.3

**Comment by satya164** [comment]
it's fixed in 2.1.5
