### ISSUE TITLE
Focus events not triggered When switch  pages quickly 

### ISSUE THREAD

**Issue by windandsonw** [react-navigation/react-navigation#6420]
in"react-navigation": "^3.6.1",
When I Quickly switch pages，I can't set the status bar，this is code，
 componentDidMount() {
        console.log('executed')
        this._didFocusSubscription =  this.props.navigation.addListener(
            'willFocus',
            () => {
        console.log('setting')
                setStatusBar('dark-content', '#fff');
            }
        );
    }

 componentWillUnmount() {
        this._didFocusSubscription && this._didFocusSubscription.remove();
    }
When I Quickly Exit and enter the same Page ，the status bar cannot be setting ，reason is  code setStatusBar('dark-content', '#fff')  is not execute

**Comment by hanwenbo** [comment]
me too

**Comment by tr3v3r** [comment]
The same here!
