### ISSUE TITLE
The component for route 'SecondPage' must be react component

### ISSUE THREAD

**Issue by arunreenamohan-creator** [react-navigation/react-navigation#6421]
**App.js**

//This is an example code for Navigator//
import React, { Component } from "react";

import { createAppContainer } from "react-navigation";
import { createStackNavigator } from "react-navigation-stack";
import { AsyncStorage } from "react-native";
import { isSignedIn } from "./pages/auth";
import FirstPage from "./pages/FirstPage";
import SecondPage from "./pages/SecondPage";

//import {SecondPage1} from './pages/Router'
import Router from "./pages/Router";
import Router_1 from "./pages/Router_1";

export default class App extends Component {
  constructor(props) {
    super(props);
    AsyncStorage.clear();
    this.state = {
      signedIn: false,
      checkedSignIn: false
    };
  }

  render() {
    const { checkedSignIn, signedIn } = this.state;
    <Router />;
    // If we haven't checked AsyncStorage yet, don't render anything (better ways to do this)
    if (!checkedSignIn) {
      return null;
    }

    if (signedIn) {
      return <Router_1 />;
    } else {
      return <Router />;
    }
  }
  componentDidMount() {
    //alert("hi");
    isSignedIn()
      .then(res => this.setState({ signedIn: res, checkedSignIn: true }))
      .catch(err => alert("An error occurred"));
  }
}

/*const Router = createStackNavigator({

 FirstPage: {
    screen: FirstPage,
    navigationOptions: {
      title: "Sign Up"
    }
  },
  SecondPage: {
    screen: SecondPage,
    navigationOptions: {
      title: "Sign In"
    }
    }
  },
  {
        initialRouteName: 'FirstPage'
      }

);

 export default createAppContainer(Router);*/

**Router.js**

import React, { Component } from 'react';
import FirstPage from './FirstPage';
import SecondPage from './SecondPage';
import ForgotPage from './ForgotPage';
import ResetPage from  './ResetPage';
import ProfilePage from './ProfilePage'

import { createAppContainer,SwitchNavigator } from 'react-navigation';
import { createStackNavigator } from 'react-navigation-stack';
import { AsyncStorage} from 'react-native';
//import App from '.App';
const Router = createStackNavigator({
//alert(this.props.signedIn)
FirstPage: {
    screen: FirstPage,
   // screen: () => <FirstPage/>,
    navigationOptions: {
      title: "Sign Up"
    }
  },
  SecondPage: {
    screen: SecondPage,
 //screen: () => <SecondPage/>,
    navigationOptions: {
      title: "Sign In"
    }
    },
/*    ForgotPage: {
        screen:ForgotPage,
        navigationOptions:{
         title: "Forgot"
        }

      },
      ResetPage:{
        screen:ResetPage,
        navigationOptions:{
        title:"ResetPage"}
      },
      ProfilePage:{
      screen:ProfilePage,
      navigationOptions:{
      title:"ProfilePage"}
      }*/
  },

  {
        initialRouteName: 'FirstPage'
      }

);

/*
export const CreateRootNavigator = (signedIn = false) => {
  return SwitchNavigator(
    {
      FirstPage: {
        screen: FirstPage
      },
      SecondPage: {
        screen: SecondPage
      }
    },
    {
      initialRouteName: signedIn ? "FirstPage" : "SecondPage"
    }
  );
};
*/

// export default createAppContainer(Router);

 const App = createAppContainer(Router);

 export default App;

**Router_1.js**

import React, { Component } from 'react';
import FirstPage from './FirstPage';
import SecondPage from './SecondPage';
import ForgotPage from './ForgotPage';
import ResetPage from  './ResetPage';
import ProfilePage from './ProfilePage'

import { createAppContainer,SwitchNavigator } from 'react-navigation';
import { createStackNavigator } from 'react-navigation-stack';
import { AsyncStorage} from 'react-native';
//import App from '.App';

const Router_1 = createStackNavigator({

//alert(this.props.signedIn)

 /*FirstPage: {
    screen: FirstPage,
    navigationOptions: {
      title: "Sign Up"
    }
  },
 */
    /*ForgotPage: {
        screen:ForgotPage,
        navigationOptions:{
         title: "Forgot"
        }
        },*/

         SecondPage: {
           // screen: SecondPage,
            screen: () => <SecondPage/>,
            navigationOptions: {
              title: "Sign In"
            }
            },
        ProfilePage:{
              //screen:ProfilePage,
              screen: () => <SecondPage/>,
              navigationOptions:{
              title:"ProfilePage"}
              },
 ResetPage:{
        /*screen:ResetPage,*/
        screen: () => <ResetPage/>,
        navigationOptions:{
        title:"ResetPage"}
      },

      },

  /*{
        initialRouteName: 'FirstPage'
      }*/

);

/*
export const CreateRootNavigator = (signedIn = false) => {
  return SwitchNavigator(
    {
      FirstPage: {
        screen: FirstPage
      },
      SecondPage: {
        screen: SecondPage
      }
    },
    {
      initialRouteName: signedIn ? "FirstPage" : "SecondPage"
    }
  );
};
*/

 //export default createAppContainer(Router_1);

 const AppContainer  = createAppContainer(Router_1);

 export default AppContainer ;

**FirstPage.js**

import React, { Component } from 'react';
import {
  StyleSheet,
  Text,
  View,
  TextInput,
  Button,
  TouchableHighlight,
  Image,
  Alert,
  AsyncStorage,ScrollView
} from 'react-native';
import { createAppContainer } from 'react-navigation';
import { createStackNavigator } from 'react-navigation-stack';

//import all the components we are going to use.

export default class FirstPage extends Component {

   static navigationOptions = {
     title: 'First Page',
     //Sets Header text of Status Bar
   };;

   constructor(props) {
    super(props);

    this.state = {
      username: '',
      password: '',
    };
  }

  onLogin() {

    const {username,password}=this.state;

let obj = {
          username:username,
          password:password
        }

    AsyncStorage.setItem('obj',JSON.stringify(obj))
this.props.navigation.navigate('SecondPage');

  }

  displayData=async () =>{
    try{
      let obj1 = await AsyncStorage.getItem('obj1')
      let parsed = JSON.parse(obj1);
      alert("The username is "+parsed.username+" and  "+"the password is "+parsed.password);

    }
    catch(error){
      alert(error);

    }
  }

postData()	{
 const {username,password}=this.state;
fetch('http://test.lutsjoin.com/api/v1/user/login', {
  method: 'POST',
  headers: { 'Accept': 'application/json', 'Content-Type': 'application/json' },
  body: JSON.stringify({'username' : username,
                        'password' : password,
                        'rememberMe':false})
}).then((response) => response.json())
.then((responseData) => { console.log("response: " + JSON.stringify(responseData));

if(responseData.token!=null){
    let obj1 = {

              username: username,
              password: password,
              token: responseData.token

            }
AsyncStorage.setItem('obj1',JSON.stringify(obj1))
this.props.navigation.navigate('SecondPage');
}
console.log(responseData.token);

  //  console.log(obj1);

// console.log(responseData);

})
.catch((err) => { console.log(err); });
}
render() {
    const { navigate } = this.props.navigation;
    return (
<ScrollView style={styles.scrollView}>
    <View style={styles.container}>
            <View style={styles.inputContainer}>
              <Image
                style={styles.inputIcon}
                source={{
                  uri: 'https://png.icons8.com/message/ultraviolet/50/3498db',
                }}
              />
              <TextInput
                style={styles.inputs}
                placeholder="Email"
                keyboardType="email-address"
                underlineColorAndroid="transparent"
                onChangeText={username => this.setState({ username })}
              />
            </View>

            <View style={styles.inputContainer}>
              <Image
                style={styles.inputIcon}
                source={{
                  uri: 'https://png.icons8.com/key-2/ultraviolet/50/3498db',
                }}
              />
              <TextInput
                style={styles.inputs}
                placeholder="Password"
                secureTextEntry={true}
                underlineColorAndroid="transparent"
                onChangeText={password => this.setState({ password })}
              />
            </View>
<View>
           <TouchableHighlight
                         style={[styles.buttonContainer, styles.loginButton]}
                         onPress={this.postData.bind(this)}>
                         <Text style={styles.loginText}>Login</Text>
                       </TouchableHighlight>

              <Button title='Forgot Password'
                    onPress={() =>navigate('ForgotPage')}
                    />

</View>
          </View>
</ScrollView>
    );
  }
}
const styles = StyleSheet.create({
  container: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
     backgroundColor: '#DCDCDC',
    },
    inputContainer: {
        borderBottomColor: '#F5FCFF',
        backgroundColor: '#FFFFFF',
        borderRadius:30,
        borderBottomWidth: 1,
        width:250,
        height:45,
        marginBottom:20,
        flexDirection: 'row',
        alignItems:'center'
    },
    inputs:{
        height:45,
        marginLeft:16,
        borderBottomColor: '#FFFFFF',
        flex:1,
    },
    inputIcon:{
      width:30,
      height:30,
      marginLeft:15,
      justifyContent: 'center'
    },
    buttonContainer: {
      height:45,
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom:20,
      width:250,
      borderRadius:30,
    },
    loginButton: {
      backgroundColor: "#00b5ec",
    },
    loginText: {
      color: 'white',
    },
    scrollView: {
      backgroundColor: '#DCDCDC',
        marginHorizontal: 20,
      },
});

**SecondPage,js**

import React, { Component } from 'react';
//import react in our code.
import {
  StyleSheet,
  View,
  Text,
  Button,
  Alert,
  Linking,
  TouchableOpacity,
  ScrollView
} from 'react-native';
import { createAppContainer } from 'react-navigation';
import { createStackNavigator } from 'react-navigation-stack';
import Router from './Router';
import Router_1 from './Router_1';
import { AsyncStorage} from 'react-native';
import {isSignedIn} from './auth';
import FirstPage from './FirstPage';

class SecondPage  extends Component {
  static navigationOptions = {
    title: 'Second Page',
    //Sets Header text of Status Bar
  };

    state = {
    todos:[
            {
              "completed": false,
              "id": 1,
              "title": "delectus aut autem",
              "userId": 1
            },
            {
              "completed": false,
              "id": 2,
              "title": "quis ut nam facilis et officia qui",
              "userId": 1
            },
            {
              "completed": false,
              "id": 3,
              "title": "fugiat veniam minus",
              "userId": 1
            }
          ]
  }

componentDidMount() {
  /*  fetch('http://jsonplaceholder.typicode.com/todos')
    .then(res => res.json())
    .then((data) => {
      this.setState({ todos: data })
      console.log(this.state.todos)
    })
    .catch(console.log)*/
  }
  render() {
<Router_1/>
/*const {navigation} = this.props;*/
const {navigate} = this.props.navigation;
 //const { navigate } = this.props;
//const {navigate} = this.props.navigation;
//<SecondPage navigation={this.props.navigation}/>
/* var {navigate} = this.props.navigation;*/
    //const { navigate } = this.props.navigation;
/*  const { navigate } = this.props.navigation;*/
    return (
      <ScrollView style={styles.scrollView}>
      <View style={styles.container}>
        <Text>You are on SecondPage</Text>
         <View>
          {this.state.todos.map((todo, index) => (
            <TouchableOpacity
              key={todo.id}
              style={styles.container1}
              onPress={() => Linking.openURL('https://google.com')}>
              <Text style={styles.text}>{todo.id}</Text>
            </TouchableOpacity>
          ))}

        </View>
        <View style={{ flexDirection: 'row', justifyContent: 'space-between'}}>
          <Button
            style={styles.button}
            title="Manage By Members"
           // onPress={() =>navigate('ProfilePage')}

            onPress={() => navigate('ProfilePage')}
          />

          <Button
            title="My PD Profile"
            onPress={() => Linking.openURL('https://google.com')}
          />

        </View>

      </View>
      </ScrollView>
    );
  }
}
const styles = StyleSheet.create({
  container: {
  flex: 2,
    backgroundColor: '#fff',
  //  margin: 50,
    alignItems: 'center',
   justifyContent: 'center',
  },
  button: {
    backgroundColor: 'green',
    width: '40%',
    height: 40,
  },
  container1: {
    padding: 20,
    marginTop: 3,
    backgroundColor: '#d9f9b1',
    alignItems: 'center',
  },
  text: {
    color: '#4f603c',
  },
  scrollView: {
      backgroundColor: '#DCDCDC',
      marginHorizontal: 20,
      },
});
 export default SecondPage;

**Comment by satya164** [comment]
The error message tells you what the issue is. This is not a bug.
