### ISSUE TITLE
Could not create an instance of type org.gradle.internal.locking.DefaultDependencyLockingProvider.

### ISSUE THREAD

**Issue by slivens** [react-navigation/react-navigation#6423]
"dependencies": {
    "react": "16.9.0",
    "react-native": "0.61.3",
    "react-native-gesture-handler": "^1.5.0",
    "react-native-reanimated": "^1.3.1",
    "react-native-screens": "1.0.0-alpha.23",
    "react-navigation": "^4.0.10",
    "react-navigation-stack": "^1.10.3"
  },
The following error occurred following the steps on the  official website
![1572445247(1)](https://user-images.githubusercontent.com/32921512/67866366-ce1f4280-fb63-11e9-83ef-c425625c5f1e.jpg)

**Comment by vonovak** [comment]
hello, sorry for the issue, but it seems like it's coming from `react-native-gesture-handler` so I'll close it.
