### ISSUE TITLE
BlankScreen After using useScreens

### ISSUE THREAD

**Issue by Yieron** [react-navigation/react-navigation#6427]
BlankScreen After using useScreens

![image](https://user-images.githubusercontent.com/16173466/67930378-9fa07680-fbfa-11e9-9f02-bd5f24089d89.png)

Method `useScreens` is deprecated, please use `enableScreens` 
I use enableScreens , BlankScreen

![image](https://user-images.githubusercontent.com/16173466/67930686-42f18b80-fbfb-11e9-9fd7-54a8707befa1.png)

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 4.0.10
| react-native     |0.61.2
| node             | 
| npm or yarn      |

**Comment by Yieron** [comment]
![image](https://user-images.githubusercontent.com/16173466/67930654-340ad900-fbfb-11e9-991c-ff45e654d3e4.png)

**Comment by njacob1001** [comment]
yes! and when I make a transition to other screen, the next screen becames crazy with position of elements, please help!

**Comment by satya164** [comment]
Please use react-native-screens@^1.0.0-alpha.23 as mentioned in the getting started guide https://reactnavigation.org/docs/en/getting-started.html
