### ISSUE TITLE
InteractionManager.runAfterInteractions() not working properly in react navigation

### ISSUE THREAD

**Issue by DovletAmanov** [react-navigation/react-navigation#6428]
### Current Behavior
Callback function is being called alongside with long-running async tasks.

### Expected Behavior
Callback function should be called after long-running async tasks are completed.

### How to reproduce

```
import { View, Text, TouchableOpacity, InteractionManager } from 'react-native';
import { createAppContainer } from 'react-navigation';
import { createStackNavigator } from 'react-navigation-stack';

class HomeScreen extends React.Component {
    render() {
        return (
            <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
          <TouchableOpacity
                    style={{
                        height: 20,
                        width: 20,
                        backgroundColor: 'red'
                    }}
                    onPress={() => {
                        this.props.navigation.navigate("Home2")
                    }}
                />
            </View>
        );
    }
}

class Home2Screen extends React.Component {
    state = { loaded: false }
    componentDidMount(){
        InteractionManager.runAfterInteractions(() => {
            this.setState({ loaded: true })
        })
    }

    renderExpensiveComponent = () => {
        let ar = []
        for(let i = 0; i < 1000; i++) {
            ar.push(
                <View style={{ alignSelf: 'stretch', padding: 4}}>
                    <Text style={{ color: 'red', fontSize: 15}}>ITEM {i}</Text>
                </View>
            )
        }
        return ar;
    }

    render() {
        if(this.state.loaded){
            return this.renderExpensiveComponent()
        } else {
            return null;
        }
    }
}

const AppNavigator = createStackNavigator({
    Home: {
        screen: HomeScreen,
    },
    Home2: {
        screen: Home2Screen,
    },
});

```

### Your Environment

| software              | version
| ----------------  | -------
| react-navigation | 4.0.10
| react-native        | 0.61.2
| node                    |  10.15.3 
| npm or yarn        |  6.4.1

**Comment by taygundonma** [comment]
Same issue here,
It works when i used react native modal insight componentDidMount, but it doest work on StackNavigator, If i use single screen with setTimeout(() => {}, 0) wrapper it triggers interactionManager.runAfterInteractions.

**Comment by egeakyurek** [comment]
same issue

**Comment by vonovak** [comment]
hi, please read the docs at https://facebook.github.io/react-native/docs/interactionmanager

> InteractionManager allows long-running work to be scheduled after any interactions/animations have completed. In particular, this allows JavaScript animations to run smoothly.

as opposed to 

> Expected Behavior
Callback function should be called after long-running async tasks are completed.

your expectation does not fit the job of `runAfterInteractions`. If you want to run something after long-running async tasks are done, you need to do this yourself.
