### ISSUE TITLE
React Navigator doesn't work on real Android device

### ISSUE THREAD

**Issue by derrickpersson** [react-navigation/react-navigation#6431]
Hello,

I was following along on the example project; however when I tried to load the app on a real Android device I found that the react-navigation doesn't work beyond one screen. (i.e. going to the 'details' screen in the example works, but going back and/or to additional 'details' screens doesn't)

Here's the minimum code to reproduce the issue - https://github.com/derrickpersson/react-navigation-example

I'm not sure if it doesn't work completely, or if it's just excessively slow. It seems to be unresponsive for 20+ seconds, then refreshes to the home screen.

**Comment by brentvatne** [comment]
do you have chrome debugging enabled by any chance? it can be problematic on real devices depending on the network. otherwise i have no idea how to reproduce the issue you describe.

**Comment by derrickpersson** [comment]
I do - 

Turning it off made it work! Thanks!
