### ISSUE TITLE
Why my global style does not take effect after upgrade to 'react-navigation": "^4.0.10'

### ISSUE THREAD

**Issue by Ruanyang2015** [react-navigation/react-navigation#6437]
### this is my code

`render() {
        // const prefix = 'startcteacher://';
        return (
            <View style={{flex:1,backgroundColor: 'red'}}>
                <Provider style={{backgroundColor: 'red'}} store={store}>
                    <Layout>
                        <ReactNavigationCommetn/>
                    </Layout>
                </Provider>
            </View>
        );
    }`

---

### Current Behavior

- What code are you running and what is happening?
- Include a screenshot if it makes sense.

### Expected Behavior
can show backgroundColor 'red'

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |"^4.0.10"
| react-native     |0.59.9
| node             |
| npm or yarn      |

**Comment by vonovak** [comment]
hi there! this issue tracker is reserved for bugs only. your post seems to be a usage question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help. thanks!

If you think this is a bug, as the issue template explains, we require that you provide a runnable example that reproduces the bug on https://snack.expo.io or in a github repository. please try to minimize the superfluous code and focus only on reproducing the bug.
