### ISSUE TITLE
v5 Deep Linking doesn't open correct screen

### ISSUE THREAD

**Issue by rnnyrk** [react-navigation/react-navigation#6438]
Hi there,

I'm currently trying v5 which is really nice imo. Also the documentation is super clear. But unfortunately the Deep Linking doesn't seem to work?! I've copied the same code as stated on https://reactnavigation.org/docs/en/next/deep-linking.html. Although the linking does open the my app it doesn't the correct screen. Also the state returned from `getInitialState` stays `undefined`. There is no error returned either.

```javascript
import React, { useEffect, useState, useRef } from 'react';
import { NavigationNativeContainer, useLinking } from '@react-navigation/native';

import RootNavigator from 'navigators/RootNavigator';
import { setContainer } from 'services/navigationService';

const App: React.FC = () => {
  const navigationRef = useRef();

  const { getInitialState } = useLinking(navigationRef, {
    prefixes: ['https://powerbreak.nl', 'powerbreak://'],
    config: {
      Detail: {
        path: 'page/:id',
        parse: {
          id: Number,
        },
      },
    },
  });

  const [isReady, setIsReady] = useState(false);
  const [initialState, setInitialState] = useState();

  useEffect(() => {
    getInitialState()
      .catch((error) => {
        console.error('error getInitialState', error);
      })
      .then((state) => {
        console.log('state', state);

        if (state !== undefined) {
          setInitialState(state);
        }

        setIsReady(true);
      });
  }, [getInitialState]);

  useEffect(() => {
    setContainer(navigationRef);
  }, []);

  if (!isReady) return null;

  return (
    <NavigationNativeContainer
      initialState={initialState}
      ref={navigationRef}
    >
      <RootNavigator />
    </NavigationNativeContainer>
  );
};

export default App;
```

The full repo can be found here: https://github.com/rnnyrk/powerbreak/blob/develop/src/app/App.tsx
The Screen I want to link to is nested `RootNavigator (Stack) > MainNavigator (Tab) > PagesNavigator (Stack) > Detail (Screen)`.

Tried linking to the screen with `powerbreak://page/4` and `powerbreak://page?id=4`, but both give the same result.

If there is anyone in how I can help solving this bug, let me know! Would love to help. 

### Your Environment

| software         | version
| ---------------- | -------
| @react-navigation/core | ^5.0.0-alpha.20
| @react-navigation/native | ^5.0.0-alpha.14
| @react-navigation/routers | ^5.0.0-alpha.0
| @react-navigation/stack | ^5.0.0-alpha.20
| react-native |  0.61.3

**Comment by satya164** [comment]
What does `Linking.getInitialURL()` return?

**Comment by rnnyrk** [comment]
@satya164 Unfortunately this stays `null`

**Comment by satya164** [comment]
If `Linking.getInitialURL()` returns `null` then it's not a bug with React Navigation. I'd suggest you to check React Native issues to see if you're mising some configuration. Refer to Linking docs for configuration https://facebook.github.io/react-native/docs/linking

**Comment by rnnyrk** [comment]
@satya164 Thanks for pointing this out. Maybe this seems to be a bug after all. I've found out that the logging of `Linking.getInitialState` is somehow broken when debug mode is on (see: https://github.com/facebook/react-native/issues/24429). So I changed to code to run Alert's without debug mode on;

```javascript
  useEffect(() => {
    getInitialState()
      .catch((error) => console.error('error getInitialState', error))
      .then((state) => {
        if(state){
          const names = state.routes.map((route) => {
            return `${route.name}, ${JSON.stringify(route.params)}`
          });

          Alert.alert(names.join(','));
        } else {
          Alert.alert(state === undefined ? 'No state' : 'test');
        }

        if (state !== undefined) {
          setInitialState(state);
        }

        setIsReady(true);
      });
  }, [getInitialState]);

  useEffect(() => {
    Linking.getInitialURL()
      .then((url) => {
        if (url) {
          Alert.alert(`Initial url is: ${url}`);
        } else {
          Alert.alert('No initial url');
        }
      })
      .catch((err) => console.error('An error occurred', err));
  }, []);

```

Now as expected `Linking.getInitialState` shows the incoming link, in this case: `powerbreak://page/4`. The alert maps it to: 
<img width="373" alt="Screenshot 2019-11-07 at 13 36 54" src="https://user-images.githubusercontent.com/4519142/68389741-f4487200-0163-11ea-8c22-895f557912a6.png">

Which, I think, should map to the config I added in my first post;
```javascript
    config: {
      Detail: {
        path: 'page/:id',
        parse: {
          id: Number,
        },
      },
    },
```

Unfortunately the behaviour didn't change, and it's still opening the wrong (main) screen.

**Comment by pragneshpj** [comment]
Deep linking is not working when app is not in background / kill the app. (Android, iOS)
if app is in background then working perfectly
can anyone help me

**Comment by iocodbanid6** [comment]
> Deep linking is not working when app is not in background / kill the app. (Android, iOS)
> if app is in background then working perfectly
> can anyone help me

@pragneshpj I am also experiencing same issue. Did you find anything?

**Comment by manojeeva** [comment]
Same here. Background mode working. When the app is killed or closed and trying to open it does not navigate. Simply goes to default route.

**Comment by nazrdogan** [comment]
@pragneshpj  same issue.

**Comment by blankey1337** [comment]
I also have this issue, please advise, thanks.

**Comment by pragneshpj** [comment]
```
  // 1. If the app is not already open, it is opened and the url is passed in as the initialURL
  // You can handle these events with Linking.getInitialURL(url) -- it returns a Promise that
  // resolves to the url, if there is one.
  useEffect(() => {
    getUrlAsync()
  }, [])

  const getUrlAsync = async () => {
    // Get the deep link used to open the app
    const initialUrl = await Linking.getInitialURL()
    if (initialUrl) {
      // Register linkingUrl in EventRegister.emit
      EventRegister.emit(LINKING_URL, initialUrl)
    }
    // if this setLinkedURL is not work then with setTimeout
    setLinkedURL(decodeURI(initialUrl))
    // The setTimeout is just for testing purpose
    // setTimeout(() => {
      // setLinkedURL(decodeURI(initialUrl))
    // }, 1000)
  }
```

and get your **EventRegister.emit** in your screen navigation. 
It works for me. @nazrdogan

**Comment by nitish173** [comment]
> ```
>   // 1. If the app is not already open, it is opened and the url is passed in as the initialURL
>   // You can handle these events with Linking.getInitialURL(url) -- it returns a Promise that
>   // resolves to the url, if there is one.
>   useEffect(() => {
>     getUrlAsync()
>   }, [])
> 
>   const getUrlAsync = async () => {
>     // Get the deep link used to open the app
>     const initialUrl = await Linking.getInitialURL()
>     if (initialUrl) {
>       // Register linkingUrl in EventRegister.emit
>       EventRegister.emit(LINKING_URL, initialUrl)
>     }
>     // if this setLinkedURL is not work then with setTimeout
>     setLinkedURL(decodeURI(initialUrl))
>     // The setTimeout is just for testing purpose
>     // setTimeout(() => {
>       // setLinkedURL(decodeURI(initialUrl))
>     // }, 1000)
>   }
> ```
> 
> and get your **EventRegister.emit** in your screen navigation.
> It works for me. @nazrdogan

can you explain this a bit more @pragneshpj

**Comment by Sheleya** [comment]
Any updates regarding the problem with opening on iOS when app is closed?

**Comment by jsonreeder** [comment]
I ran into a similar problem and was able to get past it with help from this comment https://github.com/react-navigation/react-navigation/issues/8710#issuecomment-672877764. TL;DR update your linking config for nested routes.

I was trying to open the app to screen `Shopping List`. With the link `example://shopping-list` and following config:
```ts
const linking = {
  prefixes: ['example://'],
  config: {
    screens: {
      'Shopping List': 'shopping-list',
    },
  },
};
```

When the app was open (focused or in the background), that link took me to the desired screen. When the app was closed, that link took me to the home screen not the desired screen.

That screen is actually a nested route. It is declared in a navigator called `Tabs`. When I changed my config object to match the [nested navigator docs](https://reactnavigation.org/docs/configuring-links/#handling-nested-navigators), I got the desired behavior: regardless of whether the app is open or closed, the link always opens the app to the desired screen.

```ts
const linking = {
  prefixes: ['example://'],
  config: {
    screens: {
      Tabs: {
        screens: {
          'Shopping List': 'shopping-list',
        },
      },
    },
  },
};
```

What's misleading here is that the non-nested config happens to work if the app is open (and the route under which the desired page is nested is active).

@rnnyrk It looks like you might be having the same problem. The component you're linking to, `Detail` appears to be nested under the screen [Pages](https://github.com/rnnyrk/powerbreak/blob/develop/src/app/components/navigators/MainNavigator.tsx) but your linking config does not mention `Pages`.

**Comment by arunkarnati** [comment]
Deep linking isn't loading the right screen when the app is not running in the background. Based on Ronny's comment above https://github.com/react-navigation/react-navigation/issues/6438#issuecomment-551063822, I turned off the debug mode, and it is working normally in all cases. 

An issue exists for the same on React Native repo, https://github.com/facebook/react-native/issues/24429

**Comment by rnnyrk** [comment]
@jsonreeder Thanks for pointing it out. Although it's not one of my active projects anymore (it was a RN try-out), I will check out if you suggestion will work out.

**Comment by HungNhOnPV** [comment]
> Deep linking is not working when app is not in background / kill the app. (Android, iOS) if app is in background then working perfectly can anyone help me

You stop debug then it run
