### ISSUE TITLE
react-native createMaterialTopTabNavigator with I18n based arabic Titles are not working

### ISSUE THREAD

**Issue by SopoB** [react-navigation/react-navigation#6439]
I have an Arabic app, I am using forceRTL to update the views and translations.

All the things are working, except tabs Arabic titles are not getting updated.

I am using "createMaterialTopTabNavigator, createAppContainer" of react navigation.

If you have any suggestions or references for the same, please let me know.

Following is my tabs code.

import React, { Component } from 'react';
import { Text, View, Image, Linking, ScrollView, TouchableOpacity, SafeAreaView, StyleSheet, Dimensions, StatusBar, AsyncStorage, FlatList } from 'react-native';
import I18n from '../Helpers/i18n';
import { createMaterialTopTabNavigator, createAppContainer } from 'react-navigation';
import Upcoming from "./Upcoming.js";
import History from "./History.js";

const { width, height } = Dimensions.get('window');

const MyBookingTabs = createAppContainer(
  createMaterialTopTabNavigator({
    Upcoming: { 
      screen: Upcoming,
      navigationOptions: {
        title:I18n.t('bookingTableUpcomingText'),
      }
    },
    History: { 
      screen: History,
      navigationOptions: {
        title:I18n.t('bookingTableHistoryText'),
      }

    },
  },
    {
      tabBarPosition: 'top',
      swipeEnabled: true,
      animationEnabled: true,
      tabBarOptions: {
        activeTintColor: '#FFFFFF',
        inactiveTintColor: '#F8F8F8',
        style: {
          backgroundColor: '#f01616',
          //backgroundColor:'#000',
          shadowColor: "#fc301c",
          shadowOffset: {
            width: 0,
            height: 2,
          },
          shadowOpacity: 0.80,
          shadowRadius: 3.84,
          elevation: 5,
        },
        labelStyle: {
          textAlign: 'center',
        },
        indicatorStyle: {
          borderBottomColor: '#fff',
          borderBottomWidth: 1,
        },
      },
    }));

export default class MyBookingTabsComponent extends React.Component {
  constructor(props) {
    super(props);
  }
  render() {
    return (
      <View style={{height:(height-150),}}>
      <MyBookingTabs screenProps={{navigationObj: this.props.screenProps.navigationObj }}/>        
      </View>
    )
  }
}

Tabs are getting updated on hot reloading to that page

**Comment by SopoB** [comment]
title:I18nManager.isRTL ? "ملف" : "Profile"

Resolved using this way

**Comment by satya164** [comment]
Please fill the issue template when opening issues.
