### ISSUE TITLE
Import ScrollView from React Navigation

### ISSUE THREAD

**Issue by ruben-kasaz** [react-navigation/react-navigation#6440]
# Current Behavior

As said in the documentation of React Navigation [here](https://reactnavigation.org/docs/en/scrollables.html)

React Navigation export its own ScrollView component.
But when I try to import it, it fails and shows me an error.

The import is :

![Capture d’écran 2019-11-07 à 13 03 35](https://user-images.githubusercontent.com/56114419/68396743-55774200-0172-11ea-9ffc-d520d133a721.png)

The error is : 

![Capture d’écran 2019-11-07 à 15 23 18](https://user-images.githubusercontent.com/56114419/68396876-8eafb200-0172-11ea-8aab-a933ad40ff21.png)

### How to reproduce

I created a repo in github that shows the problem.
You can clone it [here]( https://github.com/ruben-kasaz/navigation-test)

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^4.0.10
| expo     | ^35.0.0
| react-native-web             | ^0.11.7
| yarn      | 1.9.4

**Comment by pzatorski** [comment]
Hey @ruben-kasaz I used your repo to reproduce the issue that you are facing. To be honest with you after installing all needed dependencies I managed to run the project and I also used `ScrollView` from `'react-navigation'`. I can not see the same issue as you are.. Please double check your dependencies in `package.json`.
