### ISSUE TITLE
Route changing when   minimizer and open app

### ISSUE THREAD

**Issue by stefanosandes** [react-navigation/react-navigation#6443]
### Current Behavior

In Android with react-native, when I navigate between screens in the fist launch after installation and minimize the app, when I bring it back the displayed screen  is the root screen. So if I navigate from root screen A to B, when I minimize and open app again, the displayed screen is screen A, not B. But, if I kill the app and repeat de process minimizing and opening app, it respect the last screen and show this.

#### After kill and reopen
![android_1](https://user-images.githubusercontent.com/6722075/68448659-fbeb3380-01c2-11ea-8058-45c780ad11d4.gif)

#### Before kill and reopen

![android_3](https://user-images.githubusercontent.com/6722075/68448686-09a0b900-01c3-11ea-83d5-5c67e422cc9c.gif)

### Expected Behavior

It needs to respect the last screen showed until app keep in memory.

### How to reproduce

```js
import React from 'react';
import {View, Text, Button} from 'react-native';
import {createAppContainer} from 'react-navigation';
import {createStackNavigator} from 'react-navigation-stack';

const componentStyle = {
  flex: 1,
  alignItems: 'center',
  justifyContent: 'center',
};

const HomeScreen = props => {
  const navigate = () => {
    props.navigation.navigate('Second');
  };
  return (
    <View style={componentStyle}>
      <Text style={{color: 'blue'}}>First Screen</Text>
      <Button title="Second screen" onPress={navigate} />
    </View>
  );
};

const SecondScreen = () => {
  return (
    <View style={componentStyle}>
      <Text style={{color: 'red'}}>Second Screen</Text>
    </View>
  );
};

const AppNavigator = createStackNavigator({
  Home: {
    screen: HomeScreen,
  },
  Second: {
    screen: SecondScreen,
  },
});

export default createAppContainer(AppNavigator);

```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 4.0.10
| react-native     | 0.61.4
| node             | 13.0.1
| npm or yarn      | 1.19.1

**Comment by stefanosandes** [comment]
Ok guys, I was able to reproduce this problem without react-navigation. It seems to be a react-native problem.

**Comment by valeriashpiner** [comment]
@stefanosandes Hi! Sorry, I see that it is closed already, but seems that I have the same project. Did you resolve it? Thank you!

**Comment by stefanosandes** [comment]
@valeriashpiner Hi! You can find the solution here: https://github.com/facebook/react-native/issues/27170#issuecomment-551879994
