### ISSUE TITLE
Unable to use function/class based navigator in v4

### ISSUE THREAD

**Issue by panda0603** [react-navigation/react-navigation#6445]
### Current Behavior

I recently updated to version 4 from version 2 of react-navigation. 
In version 2(without createAppContainer), I was able to use class or function based navigator, as follows: 

```
let DrawerConfig = ({ initScreen, initData }) => {
  const Tabs = createBottomTabNavigator(
    {
      About: {
        screen: () => <Weather initData={initData} />,
        navigationOptions: {
          title: "Chat",
          tabBarIcon: ({ tintColor }) => (
            <Feather name="message-square" size={27} color={tintColor} />
          )
        }
      },
      ...,
   },
    {
      initialRouteName: initScreen,
      backBehavior: "none",
      tabBarOptions: {
        activeTintColor: "black",
        inactiveTintColor: "gray",
        showLabel: false,
        style: {
          backgroundColor: "#fff"
        },
        indicatorStyle: {
          backgroundColor: "#000"
        },
        tabStyle: {
          justifyContent: "center",
          alignCenter: "center"
        }
      }
    }
  );
  return <Tabs  />;
};

export default DrawerConfig;
// for version 4, i did change to export default createAppContainer(DrawerConfig);

```

I'm using class/function based navigator because I need to pass a global variable(mobx store variable), or prop(initData, initScreen) from its parent component. 

It worked fine in version 2, but not anymore. It gives following error: 

TypeError: Cannot read property 'getStateForAction' of undefined. 

### Expected Behavior

Should work as before in version 2. 
Or is there any other way to pass in global store variable to stack, tab, drawer navigators directly?

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |4.0.10
| react-native     |0.61.4
| node             |10.16.0
| npm or yarn      |6.12

**Comment by satya164** [comment]
This usage has never been supported. You were creating a component inside render, every time anything changes, it would've unmounted and remounted, losing all state.

If you need dynamic navigator, see React Navigation 5 https://reactnavigation.org/next
