### ISSUE TITLE
Navigate from one tab to stack having another tab is working but coming back to first tab is not working

### ISSUE THREAD

**Issue by t009s** [react-navigation/react-navigation#6446]
Navigate from one tab to stack having another tab is working but coming back to first tab is not working..... Please help.
I am attaching a screenshot of the functionality...
![IMG_20191111_185553](https://user-images.githubusercontent.com/35057726/68590698-2f74d900-04b5-11ea-93e7-c756e4b7bd50.jpg)

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.1.2
| react-native     |
| node             |
| npm or yarn      |

**Comment by gilsonviana** [comment]
Could you provide the source code?

**Comment by t009s** [comment]
Actually I have figured it out by passing goBack() of one component in props to other.
Thanks.....
