### ISSUE TITLE
APP CRASH: Invariant Violation: Unsupported top level event type "onGestureHandlerStateChange" dispatched #286

### ISSUE THREAD

**Issue by JeremyBradshaw7** [react-navigation/react-navigation#6447]
Getting this error on migrating to the latest v4 react-navigation packages. It's happening only in a production build, not a simulator or even a device on a dev build, which makes testing workarounds extremely time-consuming. I'm picking up the error in a Sentry crash report, the app just crashes. It's thrown when the user picks an option from a DrawerNavigator and an attempt is made to navigate to a screen, on Android.

Versions of packages below:

		"react-navigation": "^4.0.10",
		"react-navigation-drawer": "^2.3.3",
		"react-navigation-slide-from-right-transition": "^1.0.4",
		"react-navigation-stack": "^1.10.3",
		"react-navigation-tabs": "^2.5.6",
		"react-native-gesture-handler": "^1.5.0",
		"react-native-reanimated": "^1.4.0",
		"react-native-screens": "^1.0.0-alpha.23",

**Comment by JeremyBradshaw7** [comment]
Have tried the fixes suggested here, other than rolling back react-native-gesture-handler to the suggested versions as those are old now:
https://github.com/react-navigation/react-navigation/issues/5208

But nothing works.

**Comment by JeremyBradshaw7** [comment]
Actually the bug started occurring even before the upgrade to react-navigation 4, it happens on upgrading to react native 0.61.4 from 0.60, but still its related to gesture-handler, which is a dependency of this package.

**Comment by eldina07** [comment]
I have the same problem with android SDK 28 and react-navigation v3.

My app works well with SDK 27 (but play store need 28). I try everything but nothings works :(

**Comment by TrueTiem** [comment]
Did you guys found any solution?
im also getting the same error on production build with

```
react-native: 0.61.3
react-navigation: 4.0.10
react-native-gesture-handler: 1.5.0
```

We've just upgraded our project from 0.59.9 to 0.61.3 and we are getting this error. Tried all fixes i can found but no luck.
Crash log:

```
Invariant Violation: Unsupported top level event type "onGestureHandlerStateChange" dispatched
Invariant Violation: Unsupported top level event type "onGestureHandlerStateChange" dispatched
ATAL EXCEPTION: mqt_native_modules
rocess: com.test, PID: 16023
om.facebook.react.common.d: Invariant Violation: Unsupported top level event type "onGestureHandlerStateChange" dispatched, js engine: hermes, stack:
xtractEvents (address at@1:138061
nonymous (address at@1:93494
e (address at@1:143710
e (address at@1:93071
e (address at@1:93404
eceiveEvent (address at@1:138175
pply@-1
alue (address at@1:49100
nonymous (address at@1:47524
alue (address at@1:48698
alue (address at@1:47482
      at com.facebook.react.modules.core.ExceptionsManagerModule.reportException()
      at java.lang.reflect.Method.invoke(Native Method)
      at com.facebook.react.bridge.JavaMethodWrapper.invoke()
      at com.facebook.react.bridge.JavaModuleWrapper.invoke()
      at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
      at android.os.Handler.handleCallback(Handler.java:751)
      at android.os.Handler.dispatchMessage(Handler.java:95)
      at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage()
      at android.os.Looper.loop(Looper.java:154)
      at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run()
      at java.lang.Thread.run(Thread.java:761)
   Force finishing activity com.test/.MainActivity
 eglMakeCurrent: 0xe7b057e0: ver 2 0 (tinfo 0xe7b03b50)
 gralloc_alloc: Creating ashmem region of size 2691072
 tid 1319: eglCreateSyncKHR(2050): error 0x3004 (EGL_BAD_ATTRIBUTE)
 : Long monitor contention with owner Binder:1708_8 (2211) at android.graphics.Bitmap com.android.server.wm.WindowManagerService.screenshotApplicationsInner(android.os.IBinder, int, int, int, boolean, float, android.graphics.Bitmap$Config, boolean)(WindowManagerService.java:6469) waiters=0 in void com.android.server.wm.WindowAnimator$1.doFrame(long) for 143ms
Invariant Violation: Unsupported top level event type "onGestureHandlerStateChange" dispatched
```

**Comment by DaiYz** [comment]
same issue , add  "import 'react-native-gesture-handler'" not work for me

**Comment by DaiYz** [comment]
any update?

**Comment by JeremyBradshaw7** [comment]
What worked for me in the end was to put this import as the first line in the root index file AND in any file that calls react-navigation's `createAppContainer` method :

`import 'react-native-gesture-handler';`

And then this immediately after all the imports in your root index file:

```
// fix for https://github.com/kmagiera/react-native-gesture-handler/issues/320
if (Platform.OS === 'android') {
  const { UIManager } = NativeModules;
  if (UIManager) {
    // Add gesture specific events to genericDirectEventTypes object exported from UIManager native module.
    // Once new event types are registered with react it is possible to dispatch these events to all kind of native views.
    UIManager.genericDirectEventTypes = {
      ...UIManager.genericDirectEventTypes,
      onGestureHandlerEvent: { registrationName: 'onGestureHandlerEvent' },
      onGestureHandlerStateChange: {
        registrationName: 'onGestureHandlerStateChange',
      },
    };
  }
}
``` 

It would still be better to have it properly fixed in the repo so that these workarounds aren't necessary, so will keep this open.

**Comment by satya164** [comment]
Closing in favor of https://github.com/kmagiera/react-native-gesture-handler/issues/320

Please track the issue there and comment there.
