### ISSUE TITLE
Screen and Header section is flickering while navigating from a stack navigator to headerRight

### ISSUE THREAD

**Issue by nihp** [react-navigation/react-navigation#6448]
I am using react-navigation to navigate the screens. Here I have used TabBarBotoom and stack navigator.

The headerRight (header right there is 3 icons) is inside the stacknavigator so while navigating it gets flickering. Any solution for this. In header right there?

```
renderMyHomeHeader = (navigation) => {
  let navigationOptions = {
    headerStyle: {
      backgroundColor: 'black',
      borderWidth: 0,
      borderBottomWidth: 0,
      width: deviceWidth,
      height:  headerHeight
    },
    headerLeft: headerTitleNavigationOptions('Home'),
    //headerLeft: headerLeftNavigatorOptions(navigation),
    headerRight: headerRightNavigatorOptions(navigation) // Here I have many screens
  };

  navigationOptions: ({ navigation }) => ({
  headerStyle: {
      backgroundColor: 'black',
      borderWidth:0,
      borderBottomWidth:0
  },
})

  if (navigation.state.routeName != 'Home') {
    navigationOptions = {
      header: null
    };
  }
  return navigationOptions;
}

const BottomTabNavigator = createBottomTabNavigator({
  Home: {
    screen: createStackNavigator({
     HomeScreen: {
        screen: HomeScreen
      },
      User: {
        screen: User
      },
    },
    {
      defaultNavigationOptions: ({ navigation }) => (
        renderMyHomeHeader(navigation)
      ),
      navigationOptions: ({ navigation }) => ({
        tabBarVisible: showTabBar(navigation),
        tabBarIcon: ({focused}) =>  (<Image style={{tintColor: focused ? '#C7A985': '#FFFFFF', width: 45, borderColor:'white', height:45, paddingTop:0, resizeMode:'contain'}} source={{uri: 'image'}} />),
        //tabBarIconColor: 'white',
        tabBarOnPress: ({}) => (navigation.navigate('Home')),
        inactiveTintColor:'white'
      }),
      transitionConfig: () => ({
          transitionSpec: {
            duration: 0,
            timing: Animated.timing,
            opacity: 0
          },
        }),
      },
    ),
  },
```

```
Version:

"react-navigation": "^3.2.3"
"react": "16.8.1",
react-native-cli: 2.0.1
react-native: 0.58.4
```

**Comment by JarnoNijhof** [comment]
You can try something like this mayby;

```
export const LoadingPage = () =>  {
    componentDidMount(){
         // When the page is loaded it starts counting
         this.timeoutHandle = setTimeout(()=>{
         }, 1000);
    }
};

```

**Comment by nihp** [comment]
So in each screen I need to add this loading. Does it makes any performance issue?

**Comment by JarnoNijhof** [comment]
Not that much... when u just add this and it works you can decrease the loading time.

**Comment by nihp** [comment]
After upgrade also still I am facing same issue

**Comment by carlos21** [comment]
@nihp did you find the solution, I;'m facing the same

**Comment by nihp** [comment]
No I don't found any solution

**Comment by nihp** [comment]
It is an answer from a github

have you tried putting the waitForRender: true whenever you are about to push to a new screen? It worked for me that way, it was the only way i could make it work. Whenever I do a Navigation.push() i set the waitForRender within the options. Works like a charm. Good luck

**Comment by AdarshJais** [comment]
> It is an answer from a[ github](https://github.com/wix/react-native-navigation/issues/358#issuecomment-579524906)
> 
> have you tried putting the waitForRender: true whenever you are about to push to a new screen? It worked for me that way, it was the only way i could make it work. Whenever I do a Navigation.push() i set the waitForRender within the options. Works like a charm. Good luck

Can you please share the code How to do so.

**Comment by timothyerwin** [comment]
> It is an answer from a[ github](https://github.com/wix/react-native-navigation/issues/358#issuecomment-579524906)
> 
> have you tried putting the waitForRender: true whenever you are about to push to a new screen? It worked for me that way, it was the only way i could make it work. Whenever I do a Navigation.push() i set the waitForRender within the options. Works like a charm. Good luck

isn't that a different repo though? I don't think that's the same component

**Comment by saeidtkh** [comment]
it is still there, do you have any updates ?
