### ISSUE TITLE
cardTransparent, cardStyle not recognized as known property of NavigationScreenConfig type

### ISSUE THREAD

**Issue by gilsonviana** [react-navigation/react-navigation#6452]
### Current Behavior

Possibly related to issue #6047 

I'm using the ```react-navigation-stack 1.10.3``` to create a stack navigator. But there are properties missing in NavigationScreenConfig type. I need to make the _Help_ screen with a transparent background. I've tried the cardTransparent and cardStyle but no effect and TypeScript is displaying the following error message: 
```
Type '{ headerShown: false; cardTransparent: boolean; }' is not assignable to type 'NavigationScreenConfig<NavigationStackOptions, NavigationStackProp<NavigationRoute<NavigationParams>, any>, unknown>'.
  Object literal may only specify known properties, and 'cardTransparent' does not exist in type 'NavigationScreenConfig<NavigationStackOptions, NavigationStackProp<NavigationRoute<NavigationParams>, any>, unknown>'.
```

```
export default createStackNavigator({
    [...]
    Help: {
        screen: Help,
        navigationOptions: {
            headerShown: false,
            cardTransparent: true,
            cardStyle: { 
                [...] 
            }
        },
    }
}, {
    initialRouteName: 'Profile',
    mode: 'modal',
})
```

### Expected Behavior

I'm wanting to make the _Help_ screen to have a transparent background

### How to reproduce

Here's the simplest reproduction code I came up with.

```
import { createAppContainer } from 'react-navigation'
import { createBottomTabNavigator } from 'react-navigation-tabs'
import { createStackNavigator } from 'react-navigation-stack'

const Stack = createStackNavigator({
    Help: {
        screen: Help,
        navigationOptions: {
            headerShown: false,
            cardTransparent: true,
            cardStyle: {
                backgroundColor: 'transparent'
            }
        }
    }
})

const BottomTabs = createBottomTabNavigator({
    Home: Stack
})

export default createAppContainer({
    App: BottomTabs
})
```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 4.0.10
| react-native     | 35
| node             | 10.16.3
| npm or yarn      | 6.9.0

**Comment by satya164** [comment]
`cardStyle` and `cardTransparent` are not inside `navigationOptions` in v1 and `cardTransparent` is called `transparentCard`. You're looking at v2/v5 docs.

**Comment by gilsonviana** [comment]
Could you at least elaborate?
I am looking for a way to add transparency in just one screen of a stack so code below don't solve my problem since it make all the screen on the stack to have a transparent background.
```
[...]
transparentCard: true,
transitionConfig: () => ({ 
     [..] 
})
[...]
```
I looked at the documentation for the stable version and wasn't able to find anything related.

Could you please, re-open this issue?

**Comment by satya164** [comment]
> Could you at least elaborate?
> I looked at the documentation for the stable version and wasn't able to find anything related.

Like you saw in the stable version documentation, what you wrote isn't correct code. It's only possible for [stack 2.0](https://reactnavigation.org/docs/en/stack-navigator-2.0.html) or [react-navigation 5.0](https://reactnavigation.org/docs/en/next/stack-navigator.html)

> Could you please, re-open this issue?

You're using unsupported options and getting type errors. The issue in invalid.
