### ISSUE TITLE
React Navigation Upgrade failed from 3.x to 4.x

### ISSUE THREAD

**Issue by manish-jain-1** [react-navigation/react-navigation#6454]
So, I followed instructions from https://github.com/react-navigation/react-navigation/releases/tag/v4.0.0 to migrate from "react-navigation": "3.1.0" to "react-navigation": "4.0.10"

In this process I added below libraries:

```
        "react-native-reanimated": "1.2.0",
        "react-native-screens": "2.0.0-alpha.10",
        "react-navigation-stack": "2.0.0-alpha.37",
        "@react-native-community/masked-view": "0.1.5",
        "react-native-safe-area-view": "1.0.0",
        "react-native-safe-area-context": "0.3.3",
        "react-navigation-tabs": "2.5.6",
        "react-navigation-drawer": "2.3.3"
```

Each above version was carefully reviewed and selected to support 0.59.10

This was done on a stable branch that was tested with 
```
  "react": "16.8.3",
  "react-native": "0.59.10"
  "@babel/core": "^7.4.5",
  "@babel/runtime": "^7.4.5",
  "metro-react-native-babel-preset": "0.54.1",
```

`npm i` ran fine. `react-native run ios `or `react-native run android` is throwing below errors:

Android Error:
<img width="367" alt="image" src="https://user-images.githubusercontent.com/1090670/68913154-3b5bd780-070f-11ea-9a6e-7a07093a2be7.png">

iOS Error:
<img width="367" alt="image" src="https://user-images.githubusercontent.com/1090670/68913199-5f1f1d80-070f-11ea-9960-f04f8fd34d2e.png">

Debugger is clean, no errors.

Environment:

| software         | version
| ---------------- | -------
| react-navigation | 4.0.10
| react-native     | 0.59.10
| node             |      v10.16.0
| npm       |   6.9.0

I don't have a sample repo yet. Any ideas what could be the problem or how to troubleshoot further based on this info?

Thanks in advance!

**Comment by bramski** [comment]
iOS problem looks like you haven't done a `pod install`

**Comment by satya164** [comment]
Try deleting `node_modules` and `yarn.lock`/`package-json.lock` and install deps again. Looks like your deps have an old version of `@react-navigation/core`

**Comment by manish-jain-1** [comment]
```
"@react-navigation/core": {
            "version": "3.5.1",
```

I think this migration needs project to be on AndroidX. Package `react-navigation-stack` uses `react-native-safe-area-context` that is not available without AndroidX. 

https://github.com/th3rdwave/react-native-safe-area-context/blob/v0.2.0/android/gradle.properties

**Comment by satya164** [comment]
> I think this migration needs project to be on AndroidX. Package react-navigation-stack uses react-native-safe-area-context that is not available without AndroidX.

As mentioned in the release notes, upgrading navigators is optional. You can upgrade stack in future.

**Comment by bramski** [comment]
Don't use the alpha versions of `react-navigation-stack`. `1.10.3` does not use that library.
