### ISSUE TITLE
Deep linking, params don't work

### ISSUE THREAD

**Issue by AstroCorp** [react-navigation/react-navigation#6455]
By using deep linking I can navigate to the screen, but not get the url parameter. (undefined)

`class Navigation extends PureComponent
{
    configNavigation()
    {
        enableScreens();

        const AppStack = createDrawerNavigator({
            Home: {
                screen: Home
            },
            Settings: {
                screen: Settings
            }
        },
        {
            initialRouteName: 'Home'
        });

        const LoginStack = createStackNavigator(
        { 
            Login: {
                screen: Login,
                path: 'login/:token',
            },
            Register: Register,
        },
        {
            headerMode: 'none'
        });

        const MySwitchNavigator = createSwitchNavigator(
            {
                Login: {
                    screen: LoginStack,
                    path: 'auth',
                },
                App: AppStack,
            },
            {
                initialRouteName: 'Login',
            }
        );
        
        return createAppContainer(MySwitchNavigator);
    }

    render() 
    {
        const AppContainer = this.configNavigation();
        const prefix = 'myapp://';

        return (
            <AppContainer uriPrefix={prefix} />
        );
    }
}`

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 4.0.10
| react-native     | 0.61.4
| node             | v12.1.0
| npm or yarn      | yarn 1.15.2

**Comment by rnnyrk** [comment]
Might be related? https://github.com/react-navigation/react-navigation/issues/6438

**Comment by AstroCorp** [comment]
This works for me...

https://github.com/Starotitorov/react-native-deep-link

**Comment by rnnyrk** [comment]
@AstroCorp Did you use this in combination with (the latest) `react-navigation`?

**Comment by AstroCorp** [comment]
Yes, but only in the main route of the application, I haven't tried using deep link navigation (react navigation) with this library

**Comment by rnnyrk** [comment]
🤔 Can you share an example?

**Comment by AstroCorp** [comment]
@rnnyrk I'm sorry, the link was incorrect, I edited the comment, there are examples
