### ISSUE TITLE
V5 createNavigator is not a function

### ISSUE THREAD

**Issue by rnnyrk** [react-navigation/react-navigation#6456]
Hi there, with v5 I'm facing a strange error which I can find nothing about. I followed the docs creating navigators. Got some really simple navigators. `Screen1` just renders a text.

**App.js**
```javascript
import { NavigationNativeContainer } from '@react-navigation/native';
import RootNavigator from 'navigators/RootNavigator';
import { enableScreens } from 'react-native-screens';

const App: = () => {
  enableScreens();

  return (
    <NavigationNativeContainer>
      <RootNavigator />
    </NavigationNativeContainer>
  )
}
```

**RootNavigator.js**
```javascript
import { createStackNavigator } from '@react-navigation/stack'

const RootNavigator = () => (
  <Stack.Navigator initialRouteName="Main">
    <Stack.Screen name="Main" component={Screen1} />
  </Stack.Navigator>
);
```

Which gives the error: `TypeError: core_1.createNavigator is not a function`

My packages:
```
"@react-navigation/core": "^5.0.0-alpha.22",
"@react-navigation/native": "^5.0.0-alpha.15",
"@react-navigation/routers": "^5.0.0-alpha.0",
"@react-navigation/stack": "^5.0.0-alpha.20",
"react-native-screens": "2.0.0-alpha.11",
"react": "16.12.0",
"react-native": "0.61.4",
```

Any idea what this might be?

<img width="420" alt="Screenshot 2019-11-16 at 15 07 20" src="https://user-images.githubusercontent.com/4519142/68994433-2d2ec800-0883-11ea-86da-76264921db33.png">

**Comment by satya164** [comment]
Update your stack (5.0.0-alpha.36): `yarn add @react-navigation/stack@next`
