### ISSUE TITLE
Going back leaves user with a stuck, half-animated screen if screen height is being animated

### ISSUE THREAD

**Issue by hbarylskyi** [react-navigation/react-navigation#6458]
### Current Behavior

I'm wrapping a Stack of multiple screens with a custom component. That way I am able to add a bottom bar (music player) which is rendered once (heavy component) for all those screens. And not rendered for others. The problem is that the player needs to be hidden if track data is not yet loaded (that's its initial state on app load). After first track is loaded, player slides from the bottom. 

The problem is that if user navigates to a different screen inside above mentioned stack while player is hidden and player is shown there, after user goes back, they see a half-animated screen. I've simplified my case and here's a reproducible demo. removing `enableScreens();` 'fixes' the problem. 

Here's an example of two screens. They are wrapped into an AppStack. AppStack is wrapped into a custom component which has the bottom bar in it. Final component is exported. Bottom bar is shown after 5 seconds. 
If user goes to second screen before 5 seconds have passed, the bottom bar will be shown when user is on second screen. When user goes back in that state, they see a half-animated screen that's stuck.

Initial view:
<img width="372" alt="image" src="https://user-images.githubusercontent.com/12055535/69078396-cdd8df80-0a5d-11ea-9017-01d9736a84f2.png">

On the second screen:
<img width="371" alt="image" src="https://user-images.githubusercontent.com/12055535/69078401-d4675700-0a5d-11ea-98db-8932f3b23f5a.png">

Bottom bar showed up:
<img width="373" alt="image" src="https://user-images.githubusercontent.com/12055535/69078428-e943ea80-0a5d-11ea-9400-153d80d9ae7d.png">

Going back:
<img width="360" alt="image" src="https://user-images.githubusercontent.com/12055535/69078446-f2cd5280-0a5d-11ea-9c6e-5fc5b9486970.png">

```
import React from 'react';
// @ts-ignore
import {
  Animated,
  Text,
  TouchableOpacity,
  View,
} from 'react-native';
import { enableScreens } from 'react-native-screens';

import './utils/NetworkLogFix';
import './utils/PushNotifications';
import { createStackNavigator } from 'react-navigation-stack';
import { createAppContainer } from 'react-navigation';

// commenting this line prevents bug from happening
enableScreens();

// create first screen with a button to navigate to second screen
const Stack1 = createStackNavigator({
  Screen1: ({ navigation }) => (
    <View style={{ flex: 1, backgroundColor: 'red' }}>
      <TouchableOpacity onPress={() => navigation.navigate('Stack2')}>
        <Text>go to Stack2</Text>
      </TouchableOpacity>
    </View>
  ),
});

// create a simple second screen
const Stack2 = createStackNavigator(
  {
    Screen2: () => <View style={{ flex: 1, backgroundColor: 'green' }} />,
  },
);

// wrap those screens in one stack
const AppStack = createStackNavigator({
  Stack1,
  Stack2,
});

// now, configure the animated bottom bar. after the launch, it will be shown after 5 seconds.
// initial height of bottom bar is 0
const animatedHeight = new Animated.Value(0);

// increase height to 100 after 5 seconds
setTimeout(() => {
  Animated.spring(animatedHeight, { toValue: 100 }).start();
}, 5000);


// wrap the App Stack into a custom component, add a bottom bar so that it will be shown on top of AppStack. 
// on top of Stack1 and Stack2.
function WrappedApp({ navigation }) {
  return (
    <View style={{ flex: 1 }}>
      <AppStack navigation={navigation} />

      <Animated.View style={{ height: animatedHeight }}>
        <Text>BOTTOM BAR</Text>
      </Animated.View>
    </View>
  );
}

WrappedApp.router = AppStack.router;

export default createAppContainer(WrappedApp);
```

### Expected Behavior

Here's the look I'm expecting after going back:
<img width="372" alt="image" src="https://user-images.githubusercontent.com/12055535/69078504-0973a980-0a5e-11ea-8c05-d84580e4ba73.png">

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 4.0.10
| react-native     | 0.61.4
| node             | 10.15.1
| yarn      | 1.13.0

**Comment by hbarylskyi** [comment]
Or should I post that in react-native-screens instead?

**Comment by peterkuiper** [comment]
@hbarylskyi what version of `react-native-screens` are you using? We are experiencing something similar.

```
"react-native": "0.61.4",
"react-navigation": "4.0.10",
"react-navigation-drawer": "2.3.3",
"react-navigation-stack": "1.10.3",
"react-navigation-tabs": "2.5.5",
"react-native-screens": "2.0.0-alpha.11",
```
For us, it only occurs on iOS. Android works fine. Might be related with: https://github.com/kmagiera/react-native-screens/pull/221.

**Comment by hbarylskyi** [comment]
Hey @peterkuiper. I'm using `^2.0.0-alpha.11` too.

**Comment by jamieallen59** [comment]
If you need a workaround for now, this worked for me: https://github.com/kmagiera/react-native-screens/issues/220#issuecomment-556034708

**Comment by yawnr** [comment]
Disabling screens fixes it -- but not a real solution as far as I'm concerned

**Comment by ymanjuy** [comment]
Agree @yawnr . #6451 is working but that may not be the exact solution. Even in their [latest docs](https://reactnavigation.org/docs/en/next/native-stack-navigator.html#docsNav), they are saying we have to enable it manually!

**Comment by Fulanko** [comment]
I had the same issue. It was fixed after updating the dependencies to the versions found here:

https://github.com/kmagiera/react-native-screens/issues/220#issuecomment-575059635
