### ISSUE TITLE
Importing e.g. createAppContainer or createSwitchNavigator causes flow error

### ISSUE THREAD

**Issue by schumannd** [react-navigation/react-navigation#6459]
flow doesn't seem to find the corresponding exports.

importing them like

    import { createSwitchNavigator } from 'react-navigation'; 

causes 

    error  createSwitchNavigator not found in 'react-navigation'

**Comment by satya164** [comment]
Closing since we don't support flow in this repo anymore. For flow related issues, open issues in flow-typed.
