### ISSUE TITLE
navigator has more padding

### ISSUE THREAD

**Issue by zhoubo91** [react-navigation/react-navigation#6461]
## Navigatior has more padding
hello , In my  project,I has used react-navigation.but when I put my app to a new router ,the header has  more  padding .How I can  fix it?

here is my code 

<img width="514" alt="image" src="https://user-images.githubusercontent.com/13418395/69134940-48077380-0af3-11ea-88f5-c2bb45bb076e.png">

this is the compoent 
<img width="527" alt="image" src="https://user-images.githubusercontent.com/13418395/69134966-4dfd5480-0af3-11ea-9ab1-6cebff6fc578.png">

---

### Current Behavior
here is the behavior 

<img width="359" alt="image" src="https://user-images.githubusercontent.com/13418395/69198983-8ba0c280-0b71-11ea-92b0-069ecb56f04f.png">

### Expected Behavior
how can I  remove the  position 1 

### How to reproduce

- You must provide a way to reproduce the problem. If you are having an issue with your machine or build tools, the issue belongs on another repository as that is outside of the scope of React Navigation.
- Either re-create the bug on [Snack](https://snack.expo.io) or link to a GitHub repository with code that reproduces the bug.
- Explain how to run the example app and any steps that we need to take to reproduce the issue from the example app.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 4.0.10
| react-native     | 0.61.4
| node             |10.15.3
| npm or yarn      |1.10.1

**Comment by davidsamacoits** [comment]
It is very much likely because of `SafeAreaView`. Try using `headerforceinset` in your `navigationOptions`
```js
navigationOptions: () => ({
    headerForceInset: { top: 'never', bottom: 'never' },
})
```
https://reactnavigation.org/docs/en/stack-navigator.html#headerforceinset

**Comment by zhoubo91** [comment]
> It is very much likely because of `SafeAreaView`. Try using `headerforceinset` in your `navigationOptions`
> 
> ```js
> navigationOptions: () => ({
>     headerForceInset: { top: 'never', bottom: 'never' },
> })
> ```
> 
> https://reactnavigation.org/docs/en/stack-navigator.html#headerforceinset

yeah,is the  SafeAreaView, It has resolve my problem。Thanks
