### ISSUE TITLE
`overlayColor` is missing in  `_DrawerNavigatorConfig` [1] but exists in  object literal [2].Flow(InferError)

### ISSUE THREAD

**Issue by Preeternal** [react-navigation/react-navigation#6465]
### Current Behavior

I got the flow error:
Cannot call `createDrawerNavigator` with object literal bound to `config` because property `overlayColor` is missing in  `_DrawerNavigatorConfig` [1] but exists in  object literal [2].Flow(InferError)

### Expected Behavior

Expected no flow errors

### How to reproduce

Just set 'overlayColor' in  createDrawerNavigator

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |3.11.1
| react-native     |0.61.2
| node             |10.16.3
| npm or yarn      |1.19.1

**Comment by Ashoat** [comment]
Thanks for catching this @Preeternal! We don't track Flow issues in this repo anymore, so let's go ahead and follow-up on your [PR](https://github.com/flow-typed/flow-typed/pull/3651) over in flow-typed.
