### ISSUE TITLE
Is there any way i can navigate to another screen from SceneMap

### ISSUE THREAD

**Issue by hamzamugabo** [react-navigation/react-navigation#6466]
import * as React from 'react';
import { View, StyleSheet, Dimensions, ScrollView, Button } from 'react-native';
import { TabView, SceneMap, TabBar } from 'react-native-tab-view';
 
const FirstRoute = ({navigation}) => (
  <View style={styles.scene} >
      <ScrollView style={styles.scrollView}>
      <View>
          <Button title="Crop" onPress={()=> navigation.navigate("Home")}/>
      </View>
          </ScrollView>
      </View>
);
 
const SecondRoute = () => (
  <View style={styles.scene} >
      <ScrollView style={styles.scrollView}>
          <View>
          <Text>
              Hi there
          </Text>
          </View>
        
          </ScrollView>
      </View>
);
 
export default class AddCrop extends React.Component {
    static navigationOptions = {
        title: "Crop Information Management"
      };
  state = {
    index: 0,
    routes: [
      { key: 'first', title: 'Add Crop' },
      { key: 'second', title: 'View crops' },
    ],
  };
  renderTabBar(props) {
    return (<TabBar
    style={{backgroundColor: 'green'}}
    labelStyle={{color: 'white', fontSize: 18, fontWeight: 'bold', paddingBottom:10 }}
    {...props}
    indicatorStyle={{backgroundColor: 'black', height: 1.5}}
    />
    );
    }
 
  render() {
    return (
      <TabView
        navigationState={this.state}
        renderScene={SceneMap({
          first: FirstRoute,
          second: SecondRoute,
        })}
        onIndexChange={index => this.setState({ index })}
        initialLayout={{ width: Dimensions.get('window').width }}
        TabView renderTabBar={this.renderTabBar}
      />
    );
  }
}
 
const styles = StyleSheet.create({
  scene: {
    flex: 1,
  },
scrollView: {
    backgroundColor: 'pink',
    marginHorizontal: 20,
    flex:1,
  },
  
});

**Comment by vonovak** [comment]
hi there! this issue tracker is reserved for bugs only. your post seems to be a usage question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help. thanks!
