### ISSUE TITLE
goBack make screen error in IOS

### ISSUE THREAD

**Issue by viralS-tuanlv** [react-navigation/react-navigation#6468]
React navigation tried: 4.x, 3.x
The first, i opened app like this:

![DetectTextFromImage Android](https://i.imgur.com/uKWMkmB.png)

and then i click to forgot pass, and press home button to make this app to background, and open it again, and click goback and result:

![DetectTextFromImage Android](https://i.imgur.com/7YFtsl1.png)

I dont know how to fix it, can anyone help?

**Comment by jamieallen59** [comment]
Related to this: https://github.com/react-navigation/react-navigation/issues/6458

**Comment by vonovak** [comment]
closing in favor of https://github.com/react-navigation/react-navigation/issues/6458 (duplicate)
