### ISSUE TITLE
Add "unmountInactiveRoutes" option for StackNavigator?

### ISSUE THREAD

**Issue by servocoder** [react-navigation/react-navigation#6469]
I wondering is that possible to add  an option "unmountInactiveRoutes" to StackNavigator, as it is implemented at the DrawerNavigator?

The problem behind this has been discussing a while, and seems still no solution:

Possibility to prevent unmount of component B when navigate back from B to A, which however contradicts to the Lifecycle [Example Scenario](https://reactnavigation.org/docs/en/navigation-lifecycle.html#example-scenario). Keep component B being mounted assume that all components in stack should be managed/unmounted manually, of course, to prevent memory leaks.

I am aware that such a behavior may not sound well for StackNavigator.

Perhaps it should implemented as a new kind of Navigator.

What do you think?

**Comment by inpendio** [comment]
This would be nice, since its impossible to prevent rerender of inactive scenes.
