### ISSUE TITLE
Header is rendered after screen transition when updated through setParams

### ISSUE THREAD

**Issue by henrikland** [react-navigation/react-navigation#6471]
I'm working on an app where we use a custom header component for a lot of our screens, and set properties on that header in the screen components using `navigation.setParams`, usually from the `constructor` or `componentDidMount`. This has worked fine before but after updating react native from 0.59.2 to 0.61.4 and react-navigation from 2.17.0 to 4.0.10, we have the issue that the header doesn't render until after the screen transition completes.
If we use `static navigationOptions = { ... }` instead, the header renders before the transition and everything looks good, but this makes it harder for us to modify the shared header component based on other interactions.

If this is intended behavior we will probably just downgrade to 2.17.0 again.

### Current Behavior

Header is rendered after screen transition completes.

### Expected Behavior

Header should render before screen transition completes.

### How to reproduce

This is a simplified version of the problem. Please note that I know that it should not be done in this way, it is only for illustration.
Snack: https://snack.expo.io/@henrikland/header-renders-after-transition

Here is a snack using react-navigation 2.17.0 where the header is shown correctly during the transition: https://snack.expo.io/@henrikland/header-is-rendered-during-transition

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 4.0.10
| react-native     | 0.61.4
| node             | 10.15.0
| npm or yarn      | 6.4.1

**Comment by armaneker** [comment]
same problem...
