### ISSUE TITLE
useNavigation in tabBar component throws 'Hooks can only be used inside a functional component error'

### ISSUE THREAD

**Issue by DaveClissold** [react-navigation/react-navigation#6472]
This concerns react-navigation@next so if this is the wrong place to report this please let me know where I should post this bug.

### Current Behavior

React-Native is throwing the below error when trying to to use the useNavigation() hook within a tabBar component

```
Invariant Violation: Hooks can only be called inside the body of a function component. (https://fb.me/react-invalid-hook-call)
Object.throwInvalidHookError
    cbf86c2f-71ac-49d0-8b07-8b1bdd8e78e8:18286:9
Object.useContext
    cbf86c2f-71ac-49d0-8b07-8b1bdd8e78e8:8760:27
useNavigation
    cbf86c2f-71ac-49d0-8b07-8b1bdd8e78e8:132309:28
BottomNav
```

### Expected Behavior

Should be able to use the useNavigaton hook anywhere within the application, not just within screens.

### How to reproduce

have created the following snack which recreates the error

https://snack.expo.io/H1eNQgcnB

### Your Environment
react: 16.9.0,
react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz,
    expo: 35.0.0,
    @react-navigation/bottom-tabs: ^5.0.0-alpha.22,
    @react-navigation/core: ^5.0.0-alpha.24,
    @react-navigation/native: ^5.0.0-alpha.16,
    @react-navigation/stack: ^5.0.0-alpha.37,
node:  v10.13.0
yarn: 1.17.3

**Comment by satya164** [comment]
https://reactnavigation.org/docs/en/next/bottom-tab-navigator.html#tabbar

It's a function that returns a React element, not a component.

```js
tabBar={props => <CustomTabBar {...props} />}
```

**Comment by DaveClissold** [comment]
Ahh sorry, I misread the docs!! Thanks for clearing this up!!

**Comment by rpedroni** [comment]
This works for me
`<Tab.Navigator tabBar={({ navigation }) => <BottomNavBarContainer navigation={navigation} />}>`

**Comment by eikonomega** [comment]
@satya164 It might be good to incorporate something like @rpedroni's example in the docs as I can imagine many people getting tripped up with this.

**Comment by satya164** [comment]
the docs already show you to pass the props and how to get the `navigation` object from props in custom tab bar.

**Comment by DaveClissold** [comment]
Ok so I rolled back to v4, to continue development because this was causing me a headache. I've just tried to upgrade to v5 again and I'm still getting the same error "Couldn't find a navigation object. Is your component inside a screen in a navigator?" and I'm using the following 

```
<NavigationContainer>
            <Tab.Navigator initialRouteName="home" tabBar={(props) => <BottomNavigation {...props} />}>
                <Tab.Screen name="home" component={HomeScreens} />
                <Tab.Screen name="search" component={SearchScreens} initialParams={{ listType: 'search' }} />
                <Tab.Screen name="user" component={UserScreens} />
                <Tab.Screen name="newEvent" component={NewEventScreens} />
            </Tab.Navigator>
        </NavigationContainer>
```

@satya164 Am I just going mad or is there something glaringly obvious that I am missing?
