### ISSUE TITLE
Drawer is not closing when clicking outside of drawer

### ISSUE THREAD

**Issue by kranthijulakantiwork** [react-navigation/react-navigation#6475]
I have a navigation drawer which can be opened by clicking a button and closed by swiping. But I can't close the drawer by clicking outside of it. I am opening drawer navigator using this.props.navigation.openDrawer().

Here's my navigator: 

```
const navigationOptions = {
  defaultNavigationOptions: {
    gesturesEnabled: false,
    header: null
  },
  transitionConfig
};

const DrawerNavigator = createDrawerNavigator(
  {
    Home: { screen: Tabs }
  },
  {
    initialRouteName: 'Home',
    contentComponent: DrawerScreen,
    drawerWidth: (2 * width) / 3
  }
);

const AppNavigator = createStackNavigator(
  {
    Splash: { screen: Splash },
    DrawerNavigator: { screen: DrawerNavigator },
  },
  navigationOptions
);
```

### **MainActivity.js**

```
import android.content.Intent;
import android.os.Bundle;
import com.facebook.react.ReactActivity;
import org.devio.rn.splashscreen.SplashScreen;
import com.facebook.react.ReactActivityDelegate;
import com.facebook.react.ReactRootView;
import com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView;

public class MainActivity extends ReactActivity {

    /**
     * Returns the name of the main component registered from JavaScript.
     * This is used to schedule rendering of the component.
     */
    @Override
    protected String getMainComponentName() {
        return "mobile_app";
    }

    @Override
    protected ReactActivityDelegate createReactActivityDelegate() {
        return new ReactActivityDelegate(this, getMainComponentName()) {
            @Override
            protected ReactRootView createRootView() {
                return new RNGestureHandlerEnabledRootView(MainActivity.this);
            }
        };
    }

    @Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        MainApplication.getCallbackManager().onActivityResult(requestCode, resultCode, data);
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        SplashScreen.show(this);
        super.onCreate(savedInstanceState);
    }

}
```

### **Expected Behavior**

    What do you expect should be happening?

In the previous version we used (3.0.9) before upgrading to react-navigation 4.0.10, the drawer was closing fine if clicking outside the drawer container area on android.
We expect the drawer to close automatically when clicking outside the drawer container area.

###  **Environment:**

"npm":  6.4.1
"node":  v8.16.2
"react": "16.9.0",
"react-native": "0.61.0",
"react-navigation": "^4.0.10",
"react-navigation-drawer": "2.3.2",
"react-navigation-redux-helpers": "4.0.1",
"react-navigation-stack": "^1.10.3",
"react-navigation-tabs": "^2.6.0",
"react-native-gesture-handler": "1.5.0",

**Comment by DrMisQ** [comment]
I'm facing same problem with expo for web, it was working fine before upgrading to react navigation 4

**Comment by fastmanu** [comment]
Faced same issue. [@kikeztw comment actually solved it -> ](https://github.com/react-navigation/react-navigation/issues/6405#issuecomment-548618986)

**Comment by raajnadar** [comment]
@fastmanu what if I want to disable the gestures and tap outside the drawer should close it.
