### ISSUE TITLE
disabled drawer (sideMenu) for specific view

### ISSUE THREAD

**Issue by YeisonVelez11** [react-navigation/react-navigation#6483]
in the "Detail" view by default I can open the drawer, but I want to prevent this behavior so that with a swipe left the drawer can be shown, but only for this view. How can I do it?    I am using the last versión

    
![mar](https://user-images.githubusercontent.com/1949889/69965530-72d5cc80-14e2-11ea-9cdb-1d8e788a103b.gif)

`   
      import React from "react";
      import { createAppContainer, createSwitchNavigator } from "react-navigation";
      import { createStackNavigator } from "react-navigation-stack";
      import { createDrawerNavigator } from "react-navigation-drawer";
      import SideBar from "../components/SideBar/SideBar";
      import { STYLES } from "../styles/Styles";
      import LoginScreen from "../screens/Login/Login";
      import HomeScreen from "../screens/Home/Home";
      import DetailScreen from "../screens/DetailScreen/DetailScreen ";
      const LoginStack = createStackNavigator(
     {
        Login: {
        screen: LoginScreen,
        navigationOptions: {
            title: "Login",
            headerLeft: null,
            header: null
        }
        }
        
    },
    {
        initialRouteName: "Login"
    }
    );

    const HomeStack = createStackNavigator(
    {
        Home: {
        screen: HomeScreen,
        navigationOptions: {
            title: "Cita",
            headerLeft: null,
            header: null
        }
        },
        Detail: {
        screen: DetailScreen,
        navigationOptions: {
            title: "Detail cita",
            headerStyle: STYLES.bgHeaderBack,
            headerTintColor: "#fff",
            headerMode: "none"
        }

    },
    {
        initialRouteName: "Home",
        headerMode: "none"
    }
    );

    const DrawerStack = createDrawerNavigator(
    {
        Home: {
        screen: HomeStack
        }
    },
    {
        contentComponent: SideBar
    }
    );

    const switchNavigator = createSwitchNavigator(
    {
        LoginStack: LoginStack,
        HomeStack: DrawerStack
    },
    {
        headerMode: "none",
        initialRouteName: "LoginStack"
    }
    );

    const AppContainer = createAppContainer(switchNavigator);
    export default AppContainer;
`

**Comment by gcoro** [comment]
add this to your HomeStack config to disable the drawer on all the stack screens except the initial one

 ```javascript
	navigationOptions: ({ navigation }) => ({
		drawerLockMode: navigation.state.index > 0 ? 'locked-closed' : 'unlocked',
	})
```
