### ISSUE TITLE
Theme prop is not set

### ISSUE THREAD

**Issue by acerbetti** [react-navigation/react-navigation#6484]
### Current Behavior

I'm trying to build an app with support of light and dark theme.

I'm following the guide here https://reactnavigation.org/docs/en/themes.html, but I'm always getting _undefined_ when reading the prop.theme inside a class build withNavigation

### Expected Behavior

Get the current theme from the prop

### How to reproduce

My app file
```
import { AppearanceProvider, useColorScheme } from 'react-native-appearance';

// Other navigation code goes here...
let Navigation = createAppContainer(RootStack);

export default () => {
  const theme = useColorScheme();

  return (
    <AppearanceProvider>
      <ContainerApp
        theme={theme}
      />
    </AppearanceProvider>
  );
};
```

And this is my first component of the navigation stack
```
type Params = {};

type ScreenProps = {};

interface State {
  isConnecting: boolean;
}

class ProgrammerScreen extends React.Component<
  NavigationStackScreenProps<Params, ScreenProps>,
  State
> {
  render() {
    console.log('Theme: ' + this.props.theme);
    return null;
  }
}

export default withNavigation(ProgrammerScreen);
```

The theme is applied in the navigation bar and navigation items, but I'm always getting _undefined_ in the console log. What am I missing?

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 4.0.10
| react-native     | 0.61
| node             | 8.11.1
| npm or yarn      | yarn 1.19.1

**Comment by iamsuneeth** [comment]
As per the docs, the selected theme can be accessed using ThemeContext inside a class component. It will not be passed as a prop to screen components.
