### ISSUE TITLE
createBottomTabNavigator - higher height.

### ISSUE THREAD

**Issue by WebMobi59** [react-navigation/react-navigation#6487]
I am using BottomTabNavigator with stackNavigator. But bottomTabNavigator become higher sometimes.
https://screencast.com/t/KQhkwpSQaih

```
export const MainTabsNavigator = createBottomTabNavigator(MainTabs, {
    initialRouteName: NavKeys.Main.MainTabs.Home,
    tabBarOptions: {
        activeTintColor: Colors.blue,
        inactiveTintColor: Colors.light_gray,
        labelStyle: { fontSize: 12 },
        // docs indicate that this should be ok... plus it works
        // https://reactnavigation.org/docs/en/bottom-tab-navigator.html
        // @ts-ignore
        safeAreaInset: { bottom: 'never' },
        showIcon: true,
        showLabel: true,
        style: {
            backgroundColor: Colors.white,
            borderTopColor: Colors.blue,
            borderTopWidth: 1,
            height: 60,
        },
    },
});
```

Thank you.

**Comment by tamangsuresh** [comment]
I'm using 
<img width="330" alt="Screen Shot 2020-04-23 at 5 05 17 PM" src="https://user-images.githubusercontent.com/21368268/80093660-9d551e80-8584-11ea-8423-b9c1ddc33bc6.png">
<img width="391" alt="Screen Shot 2020-04-23 at 5 06 18 PM" src="https://user-images.githubusercontent.com/21368268/80093727-c1186480-8584-11ea-9389-943288249e1a.png">
https://drive.google.com/file/d/1YmGWvXacoqwOavx9yn2GgO4shpbyJyca/view?usp=sharing


Is there any way to display height inside createMaterialTopTabNavigator screens??
