### ISSUE TITLE
createStackNavigator Header Flicker

### ISSUE THREAD

**Issue by dunklesToast** [react-navigation/react-navigation#6488]
### Current Behavior
The header flickers a little bit if you are moving to a new screen with the same header component.

![demo](https://user-images.githubusercontent.com/17279485/70195635-895c6d80-1706-11ea-9905-7019ca973ae8.gif)

### Expected Behavior
If the header does not change, it should not fade or there should be a way to disable the header fading. On other threads I read that
```js
transitionConfig: () => ({
            transitionSpec: {
                duration: 0,
            },
        })
```
will fix this, but it disables the complete animation and not just the header fading.

### How to reproduce
Create a basic app with a StackNavigator and set the same header for all screens. It will fade to the same header which causes a weird flicker effect.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |4.0.10
| react-native     |0.60.5
| node             |v10.17.0
| npm or yarn      |1.19.1

**Comment by nicolashemonic** [comment]
I'm facing same issue, the header's text of my app doesn't change between screens.
It would be very great if the animation could be disabled when the text stay the same.
Thanks!

**Comment by stephanos7** [comment]
Yes facing the same issue myself. I'm using the same backgroundColor for all screens, but experiencing the same flicker effect (quick opacity fading effect) upon navigating between them. Any way to disable the animation?

**Comment by tarpey** [comment]
+1

**Comment by lyair1** [comment]
In react navigation 5.x you can try this:

`<Stack.Screen
  name="Profile"
  component={Profile}
  options={{
    title: 'Profile',
    headerStyleInterpolator: HeaderStyleInterpolators.forNoAnimation,
  }}
/>;`

[https://reactnavigation.org/docs/stack-navigator/#headerstyleinterpolators](url)

hope that helps.

**Comment by tarpey** [comment]
Thanks for pointing me in the right direction. For anyone else, this keeps the title animation and removes the background flicker.
`headerStyleInterpolator: HeaderStyleInterpolators.forUIKit`

**Comment by satya164** [comment]
As @lyair1 said, you can disable animations for the header if you don't want it.

**Comment by nateblog** [comment]
The `headerStyleInterpolator: HeaderStyleInterpolators.forUIKit` is a lot better

**Comment by andreasanta** [comment]
Can someone please post an example with full code? I am trying both `headerStyleInterpolator` values to no avail. I always see the background flicker and the title fade. Thanks!

**Comment by blueprintChris** [comment]
This works, however the back button still flickers - any suggestions?

**Comment by spencer741** [comment]
For those experiencing a flicker and are using a custom header with React Native Paper, I recommend reading [this comment](https://github.com/callstack/react-native-paper/issues/975#issuecomment-653647600). Whether you're using a custom header you built or loading a ton of data (i.e., where you might be using react-native ScrollView instead of FlatList and/or impacting app performance with synchronous data fetching), the problem is likely on your end. Although it's not easy, troubleshoot from the top down. Most of the tickets about flickering can be attributed to a not-well-implemented drop in or misuse of an upstream library / data retrieval.

**Comment by Hirbod** [comment]
Is there no way to detect, if there was a change in background color for example and only pass interpolator (for example forFade) when the background color from screen 1 does differ from screen 2?

Currently, some screens of mine have a transparent header and some are black. the animation between them works but when I animate from black to black, it looks like flickering.
