### ISSUE TITLE
headerTitle is not getting truncated with headerRight button

### ISSUE THREAD

**Issue by YajanaRao** [react-navigation/react-navigation#6489]
### Current Behavior
headerTitle is not truncating with headerRight button

### react navigation 5

```
<Stack.Screen
        name="ArtistSongs"
        component={ArtistSongs}
        options={({ route }) => {
          const { artist } = route.params;
          const { addToQueue } = route.params;
          return {
            headerTitle: artist.artist || artist.name,
            headerRight: () => (
              <View style={{ flexDirection: 'row' }}>
                <FavContainer item={artist} type="artist" />
                <IconButton icon="play-circle-outline" onPress={addToQueue} />
              </View>
            ),
          };
        }}
      />
```
![image](https://user-images.githubusercontent.com/38914337/70245806-b6f3f600-179c-11ea-9345-c70a7e006acc.png)

### Expected Behavior
headerTitle should get truncated.

### react navigation 4
![photo6289816190532561122](https://user-images.githubusercontent.com/38914337/70246224-64670980-179d-11ea-8c13-5328d1de652a.jpg)

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 5
| react-native     | 0.60
| node             | 10
| npm or yarn      |

**Comment by YajanaRao** [comment]
Issue is still present in the latest version as well.

**Comment by terrysahaidak** [comment]
Hi @YajanaRao, how did you solve the issue?

**Comment by mcatmos** [comment]
Same issue over here.

**Comment by tacomanator** [comment]
I'm having a similar issue, except that the truncation math doesn't seem to account for either the right button or the back chevron and name. Is your issue only with right buttons?

<img width="577" alt="Screen Shot 2020-03-21 at 18 20 28" src="https://user-images.githubusercontent.com/63794/77223551-f6561f00-6ba0-11ea-97ad-116a7e1367e8.png">

    "@react-native-community/masked-view": "0.1.5",
    "@react-navigation/bottom-tabs": "^5.2.2",
    "@react-navigation/native": "^5.1.1",
    "@react-navigation/stack": "^5.2.3",

for comparison in react-navigation 4:

<img width="577" alt="oldscreenshot" src="https://user-images.githubusercontent.com/63794/77223633-bf343d80-6ba1-11ea-981b-8a8b54d5b2a8.png">

**Comment by osdnk** [comment]
Hi,
it can be fixed with `rightButtonStyle: { position: 'relative' }`

**Comment by terrysahaidak** [comment]
Hi @osdnk, I think such a thing should be at least in docs

**Comment by dansiemens** [comment]
See https://github.com/react-navigation/react-navigation/issues/7057#issuecomment-593086348 for a fix
