### ISSUE TITLE
How to add information at the top of tabBar

### ISSUE THREAD

**Issue by tiwus** [react-navigation/react-navigation#6493]
<img width="364" alt="Screen Shot 2019-12-06 at 4 27 19 pm" src="https://user-images.githubusercontent.com/44537472/70312598-87012d00-1846-11ea-901c-e68802888a6b.png">

How to add information at the top of tabBar like on image above?i'm using createBottomTabNavigator.

Thank you

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.11.0
| react-native     | 0.59.9
| node             | v10.16.3
| npm or yarn      | 1.19.1

**Comment by pzatorski** [comment]
Here is my simple example:
```
MessagesStack.navigationOptions = ({
  screenProps
}) => ({
  tabBarLabel: "Messages",
  tabBarIcon: ({ focused }) => (
    <TabBarIcon
      focused={focused}
      name={messagesIcon}
      unreadMessagesCount={screenProps.unreadMessagesCount}
    />
  )
});
```
`MessagesStack` in above example is one of the navigators while using `createBottomTabNavigator`.
You can use `screenProps` to pass the information from top level Component [(Read More)](url) and then create your custom Component like I did in above example.
I hope this will help you 😉
