### ISSUE TITLE
ESLint errors 'NavigationActions not found in 'react-navigation''

### ISSUE THREAD

**Issue by maribies** [react-navigation/react-navigation#6506]
Hi there,

I am trying to bump the React Navigation version in my project but I am facing some errors in ESLint.

```
  1:10  error  NavigationActions not found in 'react-navigation'  import/named
  1:29  error  StackActions not found in 'react-navigation'       import/named
  80:10  error  createAppContainer not found in 'react-navigation'  import/named
``` 

Any tips on how to fix it?

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 4.0.10
| react-native     | 0.61.4
| node             |  v11.15.0
| npm or yarn      | 1.16.0

**Comment by tn12787** [comment]
Having this issue too.

**Comment by satya164** [comment]
It's issue with the ESLint plugin that it doesn't recognize TypeScript definitions. Not a bug in React Navigation. You should open an issue in eslint-plugin-import repo.

**Comment by joaovieira** [comment]
Does the module need to be wrapped in that `declare module "react-navigation" {}` though? Instead of exporting a "normal" ES module? The name of the module is already given by the package name. I believe it would work without it (haven't tried).

**Comment by PatricSachse** [comment]
Hi,
I'm facing the very same issue since the upgrade to react-navigation 4.
Strangely, importing from react-navigation-stack or one of the other new extracted modules does NOT result in this issue.
Only imports from 'react-navigation' seem to lead to this. 
One difference I could see is that the new modules are serving an index.d.ts while the react-navigation module uses react-navigation.d.ts as module definition. 
Are you sure that this is not related to react-navigation, @satya164?
Does anyone of y'all have a hint how to solve this issue?

Hope to now annoy you!
Thanks for your support,
Best,
Patric

**Comment by maribies** [comment]
@PatricSachse - a temporary work around my team and i opted for, which is obviously not ideal, is to ignore this lib in the linter config and on our jest testing config to all us to update and keep moving.

**Comment by PatricSachse** [comment]
Thanks for this hint. Not ideal but I guess we'll do the same for now. :+1:

**Comment by PatricSachse** [comment]
Awww, how do I configure the eslintrc to ignore react-navigation imports? Thanks for the support @maribies :)

**Comment by maribies** [comment]
@PatricSachse - find your .eslintrc.yml file and add
`settings:
  import/ignore:
    - react-navigation`
https://eslint.org/docs/user-guide/configuring

**Comment by ilyakam** [comment]
Same issue here. I also had to resort to ignoring this package, which is a shame. Here's how:

```json5
// .eslintrc.json
{
  // ...
  "plugins": [
    "import",
    // ...
  ],
  // ...
  "settings": {
    "import/ignore": ["react-navigation"],
    // ...
  }
}
```
[More details here](https://www.npmjs.com/package/eslint-plugin-import#importignore).

---

@satya164, please consider re-opening this issue and following @joaovieira's advice above.

**Comment by satya164** [comment]
If @joaovieira's solution fixes the issue, feel free to send a pull request and I'll merge it.

**Comment by joaovieira** [comment]
@satya164 thank you for your flexibility 🙏 

I don't use this library but seems to be working ok for me. Hope others can confirm.

**Comment by maribies** [comment]
hi all, with the release of version 5, my team and i clued into the solution for this version. import the following as such and there are no longer errors: `import { createAppContainer } from '@react-navigation/native';
Import { navigationActions, stackActions } from ‘@react-navigation/core’;` an update to the docs for this version 4 might be helpful for others. thanks.

**Comment by jesikaprabhu** [comment]
> @satya164 thank you for your flexibility 🙏
> 
> I don't use this library but a quick check seems to be working ok for me. Hope others can confirm.
