### ISSUE TITLE
Unable to hide bottom tab bar in a stack navigator that is in another top tab navigator

### ISSUE THREAD

**Issue by henoktsegaye** [react-navigation/react-navigation#6507]
### Current Behavior
I have  a bottom tab bar > top tab > stack navigation 
when I am trying to hide the navigator using the code below
if(navigation.state.routeName == 'conversation') {
    return false;
  }
  let tabBarVisible = true;
  if (navigation.state.index > 0) {
    tabBarVisible = false;
  }

  return {
    tabBarVisible,
  };

**it hides the immediate upper tab navigator, which is the top navigator. so the bottom navigator is not hidden. its visible.
how do I achieve this ?**

- What code are you running and what is happening?
if(navigation.state.routeName == 'conversation') {
    return false;
  }
  let tabBarVisible = true;
  if (navigation.state.index > 0) {
    tabBarVisible = false;
  }

  return {
    tabBarVisible,
  };
- Include a screenshot if it makes sense.

### Expected Behavior

- What do you expect should be happening?
Both tabs should be hidden
- Include a screenshot if it makes sense.

### Your Environment
linux ubuntu 18.04 bionic beaver
| software         | version
| ---------------- | -------
| react-navigation |4.0.10
| react-native     |0.61
| node             |8.10
| npm or yarn      |6.13

**Comment by vonovak** [comment]
hi there! this issue tracker is reserved for bugs only. your post seems to be a usage question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help. thanks!
