### ISSUE TITLE
No proper navigation in StackNavigator

### ISSUE THREAD

**Issue by coorum** [react-navigation/react-navigation#6508]
## Current Behavior

On running `this.props.navigate(...)` to another screen it navigate to another one (visible from navigation prop), but renders the previous
![react-navigation](https://user-images.githubusercontent.com/32096016/70658347-7ac20900-1c66-11ea-9069-989714a51204.gif)

### Expected Behavior

Navigating to another screen

### Your Environment

```
System:
    OS: macOS Mojave 10.14.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 78.51 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.13.0 - ~/.nvm/versions/node/v12.13.0/bin/node
    Yarn: 1.21.1 - ~/.yvm/shim/yarn
    npm: 6.12.0 - ~/.nvm/versions/node/v12.13.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 27, 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-28 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5900203
    Xcode: 11.3/11C29 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.4 => 0.61.4
```
And 
```
    "react-navigation": "^4.0.10",
    "react-navigation-stack": "^2.0.0-alpha.36",
    "react-navigation-tabs": "^2.5.6",
```

### Intro
(Both state values are `true`)
```
componentDidUpdate() {
    const { genresLoaded, animationFinished } = this.state;
    console.log(this.props.navigation);

    if (genresLoaded && animationFinished) {
      const navigateAction = NavigationActions.navigate({
        routeName: 'Login',
        params: {},
      });

      this.navigate(navigateAction);
    }
  }

  navigate = action => this.props.navigation.dispatch(action);
```
### Login
```
const Login = props => {
  useEffect(() => {
    console.log(props.navigation);
  }, []);

  return (
    <SafeAreaConsumer>
      {insets => (
        <View style={{ paddingTop: insets.top }}>
          <Text>Login Screen</Text>
        </View>
      )}
    </SafeAreaConsumer>
  );
};
```

**Comment by vonovak** [comment]
hi! Can you please create a runnable repro of this issue? Otherwise it's hard to help. Thanks.

**Comment by coorum** [comment]
@vonovak, sorry for long absence, here is the link to repo with existing problem 
https://github.com/coorum/react-navigation-issue

**Comment by satya164** [comment]
what exactly is the issue?

**Comment by coorum** [comment]
By the logic navigator should move me to Login Screen on button click, but it navigates me to the same page. If you'll check the navigation params you will see that after button click we are on `Login` page, but it renders `Intro` page

**Comment by satya164** [comment]
You're already on login screen. `navigate` navigates you to the same screen if it already existed. If you want a new screen, use `push`

**Comment by coorum** [comment]
@satya164, with your suggested method I'm receiving the same result
