### ISSUE TITLE
Navigation.replace animation issue in await

### ISSUE THREAD

**Issue by AlexDemzz** [react-navigation/react-navigation#6509]
Hello guys, i use `navigation.replace()` for open a tutorial screen if the query request return something (without any animation).

If I use the replace outside the await, the replace work well, it render no animation and the user dont see we change the screen.

But if i put it in the `then()`, the replace is animated
Someone know how to fix ?

```
testFunction()
  .then(response => {
     if (response.data) {
        navigation.replace('Tutorial');
     }
 });
```

**Comment by satya164** [comment]
Closing due to no response.
