### ISSUE TITLE
tabBarOnPress is not fired

### ISSUE THREAD

**Issue by Danik711** [react-navigation/react-navigation#6511]
### Current Behavior

- What code are you running and what is happening?
I created a MaterialTopTabNavigator. It works fine, it moves between the pages. However, I need to catch tab bar events. I followed the documentation and I hope I did everything correctly. The presses are not caught for some reason.  

- Include a screenshot if it makes sense.
![index](https://user-images.githubusercontent.com/42851878/70742590-e5695800-1ceb-11ea-9e25-8cf3d0f3c77b.png)

### Expected Behavior
- What do you expect should be happening?
I expect the console.log() to leg the message on the debugger, but it does not do it. 
- Include a screenshot if it makes sense.

### How to reproduce

- You must provide a way to reproduce the problem. If you are having an issue with your machine or build tools, the issue belongs on another repository as that is outside of the scope of React Navigation.
To reproduce create a callback for onTabBarPress. I just did what I have provided in the screenshot. 

- Explain how to run the example app and any steps that we need to take to reproduce the issue from the example app.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 4.0.10
| react-native     | 0.60.5
| node             | 12.13.0
| npm or yarn      | 6.13.2

**Comment by vonovak** [comment]
hello, please see https://reactnavigation.org/docs/en/bottom-tab-navigator.html#bottomtabnavigatorconfig and https://stackoverflow.com/questions/48031729/how-to-use-tabbaronpress-in-tabnavigator-react-native/53634195

the object with `navigationOptions` is passed to `create*TabNavigator` as the **second** argument
