### ISSUE TITLE
Can't open drawer in actual page (not registered in drawernavigator)

### ISSUE THREAD

**Issue by schmem55** [react-navigation/react-navigation#6517]
Hi,
I want to toggle drawer in a screen(Map) that is not defined in my drawer navigator ,using NavigationActions
the problem is that i want to open the drawer in my ACTUAL screen(Map) that i write in 'routeName' but nothing happens
It's working when i write in 'routeName' the screen defined in the drawerNavigator(Main) , and unfortunately it takes me to this screen(Main) in background ...instead of staying in Map Screen

`
import { createAppContainer,NavigationActions  } from 'react-navigation';
import {createStackNavigator} from 'react-navigation-stack';
import { createDrawerNavigator,DrawerActions} from 'react-navigation-drawer';
import { createMaterialTopTabNavigator } from 'react-navigation-tabs';

const AppDrawerNavigator = createDrawerNavigator({
  Main:{
    screen:MainStackNavigator,navigationOptions:({navigation})=>({
      title:translate('dashboard'),
      drawerIcon: (
        <HomeIcon name='home' size={16} color='#3ACCE1'/>
      ),
    })
  },//somescreens
})

const AppStackNavigator = createStackNavigator({
  Main:{screen:AppDrawerNavigator,navigationOptions: {
    header: null,
  }},
  Login:{screen:LoginScreen,navigationOptions:{
    header:null
  }},

  Map:{screen:MapScreen,navigationOptions:({navigation})=>({
    headerLeft:null,
    headerTransparent:true,
    headerRight:()=>{
      const navigateAction = NavigationActions.navigate({
        routeName: 'Main',// if Map instead of Main, nothing happens
        action: DrawerActions.toggleDrawer()
      });
    
        return(
          <TouchableOpacity
          onPress={()=>navigation.dispatch(navigateAction)}>
            <IconMenu name='menu' size={25} style={{marginRight:20}} />
        </TouchableOpacity>
        )},
        })
      },`

"react-native": "0.59.10",
"react-navigation": "^4.0.10",

**Comment by satya164** [comment]
Closing due to no response.
