### ISSUE TITLE
Nested Stack Navigator resetting to initialRoute after app is closed and reopened in Android (without swipe)

### ISSUE THREAD

**Issue by JoeNatan30** [react-navigation/react-navigation#6522]
### Current Behavior

I have a nested Stack Navigators like this (names are changed). If I go from the InitialStack to the HomeStack and from then to any of the screens in HomeStack or the other stacks, when I close the app (without swipe)  it automatically resets to the first screen of the InitialStack

```
const RootStack = createStackNavigator(
        {
                InitialStack: InitialStack,
                HomeStack: HomeStack,
                StackC: StackC,
                StackD: StackD,
        },
        {
                initialRouteName: 'InitialStack',
                defaultNavigationOptions: {
                        header: null
                },
        }
)

const AppContainer = createAppContainer(RootStack);
```

### Expected Behavior

I want to keep the current screen being rendered instead of the initial one from the initialStack after the apps has been reopened.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 4.0.10
| react-native     | 0.61.2

**Comment by dantasfiles** [comment]
Is it related to this? https://github.com/facebook/react-native/issues/27170#issuecomment-551879994

**Comment by dantasfiles** [comment]
https://github.com/facebook/react-native/issues/27170#issuecomment-551879994

**Comment by neil-gebbie-smarterley** [comment]
I had this problem - it was driving me crazy and the comment and fix above from @dantasfiles fixed my problem.
