### ISSUE TITLE
initialRouteName not works in nested stack

### ISSUE THREAD

**Issue by brambang** [react-navigation/react-navigation#6523]
### Current Behavior

i make nested navigator, example
```
StackNavigator {
Auth: AuthLoadingScreen,
Login: {
    screen: AuthLoginScreen,
    path: 'login'
},
LupaPassword: {
    screen: AuthLupaPasswordScreen,
    path: 'lupaPassword'
  },
Main: {
    screen: MainTabNavigator,
    path: '' // ====> **if i set value here it solve**
  }
}
```

and in the MainTabNavigator:
```
createBottomTabNavigator {
  ProdukStack: {
    screen: ProdukStack,
    path: ''
  },
  BelanjaCepatStack: {
    screen: BelanjaCepatStack,
    path: ''
  }
}
```

i dont understand why the initialRoute is always redirect to Produk Stack in Main Bottom Tab Navigator
even if i set `initialRouteName` in root StackNavigator to other screen.
example if i set to login screen, in a quick miliseconds it will redirect to Produk stack.

**UPDATE**:
_i found that the problem is `path`, currently my Main `path` is '' (empty value).
if i set the `path` with some value it will solves the problem
but i set it with empty value for good deeplink URI._

### Expected Behavior

how the correct way to set initial route?????
is it necessary to adding path value? or is it bug??

### Your Environment

| software         | version
| ---------------- | -------
| expo | sdk 34 (eject to expokit)
| react-navigation | 3.11.1
| react-native     | 0.59.8
| node             | 12.7.0
| npm     | 6.10.0

**Comment by everweij** [comment]
I ran into the same issue as well. Your solution fixed the problem of not loading the `initialRouteName` for me by adding a value to `path`.

Before:
```js
const Switch = createSwitchNavigator(
  {
    Loading,
    RootStack,
    Login
  },
  {
    initialRouteName: "Loading"
  }
);
```

After:
```js
const Switch = createSwitchNavigator(
  {
    Loading: {
      screen: Loading,
      path: "loading"
    },
    RootStack: {
      screen: RootStack,
      path: "root"
    },
    Login: {
      screen: Login,
      path: "login"
    }
  },
  {
    initialRouteName: "Loading"
  }
);
```

**Comment by brambang** [comment]
> I ran into the same issue as well. Your solution fixed the problem of not loading the `initialRouteName` for me by adding a value to `path`.
> 
> Before:
> 
> ```js
> const Switch = createSwitchNavigator(
>   {
>     Loading,
>     RootStack,
>     Login
>   },
>   {
>     initialRouteName: "Loading"
>   }
> );
> ```
> 
> After:
> 
> ```js
> const Switch = createSwitchNavigator(
>   {
>     Loading: {
>       screen: Loading,
>       path: "loading"
>     },
>     RootStack: {
>       screen: RootStack,
>       path: "root"
>     },
>     Login: {
>       screen: Login,
>       path: "login"
>     }
>   },
>   {
>     initialRouteName: "Loading"
>   }
> );
> ```

yes that solved the problem.
But if i add value 'main' to `path`, it will make a problem with deeplink inside my MainTabNavigator.

Currently i have deeplink with `myapp://produk` would open Produk Screen in Produk Stack inside MainTabNavigator.
After adding path value the link will broken, instead it used `myapp://main/produk`.
So, painfully i have to update all my code to new deeplink URI.

I hope they fix this bug.

**Comment by eriveltonelias** [comment]
Hey @brambang, can you test with the latest version of react-navigation ?

**Comment by satya164** [comment]
Closing due to no response.

**Comment by sangampokharel** [comment]
i did wrong import and got that issue like 
**import SplashScreen from './LoginScreen** may be it helps!!
