### ISSUE TITLE
Fire `componentWillUnmount` every time on Fast Refresh

### ISSUE THREAD

**Issue by VictorKolb** [react-navigation/react-navigation#6527]
Hi! Thanks for great plugin!
I face with problem: `react-navigation` calling `componentWillUnmount` every time on Fast Refresh for all routes and redux clear store function and lost all data :(

---

### Current Behavior

`react-navigation` calling `componentWillUnmount` every time on Fast Refresh for all routes

### Expected Behavior

`react-navigation` **not** calling `componentWillUnmount` every time on Fast Refresh for all routes

### How to reproduce

My app looks like:

`Navigator.ts`
```
import { createAppContainer } from "react-navigation";
import { createStackNavigator } from "react-navigation-stack";
import Chat from "app/screens/Chat";
import Home from "app/screens/Home";

const Navigator = createStackNavigator(
  {
    Home: Home,
    Chat: Chat,
  },
  {
    initialRouteName: "Home",
  },
);

export default createAppContainer(Navigator);

```

`App.tsx`

```
...
import Navigator from "app/screens/Navigator";

class App extends React.PureComponent<Props> {
  ...
  render() {
    return (
      <Wrapper>
        <StatusBar barStyle="light-content" />
        <ErrorBoundary>
          <Navigator />
        </ErrorBoundary>
      </Wrapper>
    );
  }
}
```

`Home.tsx`

```
class Home extends React.PureComponent<Props> {
  ...
 //REDUX WILL CLEAR DATA IN THIS PLACE 
 componentWillUnmount() {
    this.props.clearReduxStore()
  }

  render() {
    return (
      <View>
        <Text>Some content<Text>
      </View>
    );
  }
}
```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 4.0.10
| react-native     | 0.61.2

**Comment by VictorKolb** [comment]
https://github.com/react-navigation/react-navigation/issues/6379#issuecomment-568012809 used this method. Looks like it works.

**Comment by VictorKolb** [comment]
but it didn't help. :(

**Comment by satya164** [comment]
You need to use function components if you want fast refresh to work. Looks like you're using class components.

Anyway, Fast Refresh doesn't gurrantee that your state will be preserved. It can trigger full reload when it can't preserve state, so don't rely on not to clear your redux state.

**Comment by VictorKolb** [comment]
@satya164 thanks!
