### ISSUE TITLE
how to change iOS navigation back button size?  Header Default Style Change?

### ISSUE THREAD

**Issue by LoganRaja** [react-navigation/react-navigation#6529]
I was changed header tilte, headerbacktitle but i cant change the back button icon size.
current result:
<img width="311" alt="Screenshot 2019-12-24 at 1 11 01 PM" src="https://user-images.githubusercontent.com/23418521/71401157-049ea880-264f-11ea-812f-42008cffabc0.png">
expected result:
<img width="290" alt="Screenshot 2019-12-24 at 1 12 52 PM" src="https://user-images.githubusercontent.com/23418521/71401192-2009b380-264f-11ea-8526-4d9cee71c841.png">

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |4.X
| react-native     |0.61
| node             | 10.X
| npm or yarn      | npm

**Comment by eriveltonelias** [comment]
Hi @LoganRaja 


you can do this following: https://reactnavigation.org/docs/en/stack-navigator.html#headerleft
