### ISSUE TITLE
Navigate to first screen in a stack with material-bottom-tabs component

### ISSUE THREAD

**Issue by ilibilibom** [react-navigation/react-navigation#6531]
Hi - I'm using react-native and I'm using the material-bottom-tabs component
Currently, the behavior is that when clicking on the bottom navigator, it always goes back to the previous screen in the tab navigator stack.
I want this behavior to change so when clicking on the bottom navigator you always go to the first screen in the stack.
Is this possible ?
It sounds to me very strange that possibility is missing
seems like a trivial need for any app

**Comment by ilibilibom** [comment]
Can anyone assist please?

**Comment by satya164** [comment]
hi there! this issue tracker is reserved for bugs only. your post seems to be a usage question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help. thanks!
