### ISSUE TITLE
screen turn blank after navigate from drawer to nested stack tabbar

### ISSUE THREAD

**Issue by peyman-hakemi** [react-navigation/react-navigation#6533]
i have a tab bar inside my drawer stack, each tab have a stack
 when i want to navigate from tab2 to one of the screens inside of tab1 screen goes blank
 but everything behind the scene is working and i can see my logs inside of debugger
this is not a problem when i try open that screen from drawer inside of tab1

[this a video i record from my app](http://8upload.ir/uploads/f66515872.mp4)

`const AuthStack = createStackNavigator(
  {
    Auth: Auth,
  },
);`

`const ShopStack = createStackNavigator(
  {
    FirstPage,
    MoneyInBank,
    MarketMenu,
  },
);`

`const SugestStack = createStackNavigator(
  {
    Sugest,
    Discount,
  },
);`

`const MainTabs = createBottomTabNavigator({
  Home: {
    screen: ShopStack,
    navigationOptions: {
      tabBarLabel: 'Shop',
    },
  },
  Home2: {
    screen: SugestStack ,
    navigationOptions: {
      tabBarLabel: 'Sugest',
    },
  },
});`

`const DrawerNavStack = createDrawerNavigator(
  {
    MainTabs,
  },
  {
    contentComponent: ContentComponent,
    drawerType: 'slide',
    drawerPosition: 'right',
    drawerBackgroundColor: 'transparent',
  },
);`

`const AppNavigator = createSwitchNavigator(
  {
    Auth: AuthStack,
    Home: DrawerNavStack,
  },
);`

`const AppContainer = createAppContainer(AppNavigator);`
`export default AppContainer;`

**and this is my custom drawer**

`const ContentComponent = (props) => {`
 ` return (`
  `  <ScrollView>`
    `  <SafeAreaView`
      `  style={styles.container}`
       ` forceInset={{top: 'always', horizontal: 'never'}}>`
      `  <View>`
        `  <MenuItem`
         `   title="Market"`
         `   navigateTo="MarketMenu"`
         `   navigation={props.navigation}`
        `  />`
         ` <MenuItem`
          `  title="Auth"`
            `navigateTo="Auth"`
           ` navigation={props.navigation}`
         ` />`
       ` </View>`
     ` </SafeAreaView>`
   ` </ScrollView>`
 ` );`
`};`

and inside of menuItem i just navigate to navigateTo props

### Your Environment
i use custom drawer.
| software         | version
| ---------------- | -------
| react-navigation | v4.0.10
| react-native     | 0.61.4

**Comment by jedi2209** [comment]
@peyman-hakemi, did u found any solution for your problem?

**Comment by peyman-hakemi** [comment]
> 
> 
> @peyman-hakemi, did u found any solution for your problem?

yes
i installed the react-native-screens version 2 this was the reason behind all my problems
then i downgrade  it to 1.0.0-alpha.23
now every thing working fine
