### ISSUE TITLE
documentation problem!!

### ISSUE THREAD

**Issue by kasaiee** [react-navigation/react-navigation#6535]
## update document
please look at [https://reactnavigation.org/docs/en/auth-flow.html#set-up-our-navigators](https://reactnavigation.org/docs/en/auth-flow.html#set-up-our-navigators)
the import in the document is correct but run code is incorrect

## doc

```
import { createAppContainer, createSwitchNavigator } from 'react-navigation';
import { createStackNavigator } from 'react-navigation-stack';
```

## run code
```
import { createAppContainer, createSwitchNavigator , createStackNavigator } from 'react-navigation';
```

**Comment by spyshower** [comment]
It's outdated

**Comment by pzatorski** [comment]
Thanks for reporting the issue. As far as I know the snack is already updated.
