### ISSUE TITLE
TypeError: (0 , _native.useFocusEffect) is not a function

### ISSUE THREAD

**Issue by shivaping** [react-navigation/react-navigation#6536]
Created a sample react native application and seeing the below error after adding the package _npm install react-navigation@4.1.0-alpha.1_

TypeError: (0 , _native.useFocusEffect) is not a function

This error is located at:
    in App (at renderApplication.js:40)
    in RCTView (at AppContainer.js:101)
    in RCTView (at AppContainer.js:119)
    in AppContainer (at renderApplication.js:39)

**Comment by satya164** [comment]
`useFocusEffect` is available in v5 as per the docs.
