### ISSUE TITLE
TypeError: subs is not a function. (In 'subs(payloadWithType)', 'subs' is undefined)

### ISSUE THREAD

**Issue by sefatamak** [react-navigation/react-navigation#6537]
TypeError: subs is not a function. (In 'subs(payloadWithType)', 'subs' is undefined)

My navigation structure is something like this.

Menu->Tables->Products->ProductInformation

They are in same stack navigator. When I went from Products to ProductInformation I want to go back again to Products screen.  When I run this.props.navigation.goBack() function in ProductInformation, I take error 'TypeError: subs is not a function. (In 'subs(payloadWithType)', 'subs' is undefined)'

| software         | version
| ---------------- | -------
| react-navigation | 4.0.10
| react-native     | 0.59.2
| node             | 13.1.0
| npm or yarn      |

**Comment by eriveltonelias** [comment]
hi! please make your code runnable either on https://snack.expo.io without any extraneous code

**Comment by eriveltonelias** [comment]
I'll close the issue for now, but you can add the repro to the original post and then ping me and I'll reopen to investigate. Thanks for understanding.

**Comment by developert1990** [comment]
> hard to say without your code, but I've seen this error when you call a function rather than passing a function as a second parameter to navigation.addListener.
> 
> problem code:
> 
> `this.didFocusListener = navigation.addListener('didFocus', this.setState({foo: bar}) `
> 
> fix:
> 
> `this.didFocusListener = navigation.addListener('didFocus', () => {this.setState({foo: bar}) })`
> 
> Hope this helps.

Thank you so much
