### ISSUE TITLE
react-navigation V4,  createBottomTabNavigator Icon not shown

### ISSUE THREAD

**Issue by carl0804** [react-navigation/react-navigation#6539]
I use react-navigation V4,  createBottomTabNavigator Icon not shown both on Anroid and IOS.
I use Image as Icon, both two images can show on two pages, but not shown on bottomTabBar.
My code:
```
/* eslint-disable react-native/no-inline-styles */
import React, {Component} from 'react';
import {Image} from 'react-native';
import {createAppContainer} from 'react-navigation';
import {createBottomTabNavigator} from 'react-navigation-tabs';

import Person from './pages/Person';
import News from './pages/News';

const tabNavigator = createBottomTabNavigator(
  {
    person: {
      screen: Person,
      navigationOptions: {
        tabBarIcon: () => {
          <Image
            source={{uri: 'http://127.0.0.1/images/0.jpg'}}
            style={{width: 30, height: 30, borderRadius: 15}}
            resizeMode="cover"
          />;
        },
      },
    },
    News: {
      screen: News,
      navigationOptions: {
        tabBarIcon: () => {
          <Image
            source={{uri: 'http://127.0.0.1/images/1.jpg'}}
            style={{width: 30, height: 30, borderRadius: 15}}
            resizeMode="cover"
          />;
        },
      },
    },
  },
  {
    tabBarOptions: {
      showIcon: true,
    },
  },
);

const AppContainer = createAppContainer(tabNavigator);
class App extends Component {
  render() {
    return <AppContainer />;
  }
}

export default App;

```

### My Environment

| software         | version
| ---------------- | -------
| react-navigation | ^4.0.10
| react-native     | 0.61.5
| node             | v12.13.0
| npm or yarn      | npm: 6.13.4

![image](https://user-images.githubusercontent.com/25131086/71569772-6ad27200-2b0c-11ea-8f0e-4f7cb560d93b.png)

**Comment by carl0804** [comment]
I found this: [https://stackoverflow.com/questions/54064554/icons-not-displaying-for-react-navigation-bottom-tab-bar-in-v3/54065050](url) . It seems that I should use defaultNavigationOptions instead of navigationOptions. Now it works!

**Comment by minhajul-islam** [comment]
> I found this: [https://stackoverflow.com/questions/54064554/icons-not-displaying-for-react-navigation-bottom-tab-bar-in-v3/54065050](url) . It seems that I should use defaultNavigationOptions instead of navigationOptions. Now it works!
thanks
