### ISSUE TITLE
listen EADDRINUSE: address already in use :::8081

### ISSUE THREAD

**Issue by detroit007** [react-navigation/react-navigation#6541]
### Current Behavior

I install react navigation by using this command "npm install react-navigation" 

then i install library by this command "npm install --save react-native-gesture-handler" and link it by this command "react-native link react-native-gesture-handler",
then i install react-naigation-stack by this command ''npm install react-navigation-stack @react-native-community/masked-view''

after installing these i run 'react--native run-android' and then npm start and it starts showing this error:

Error: listen EADDRINUSE: address already in use :::8081
    at Server.setupListenHandle [as _listen2] (net.js:1298:14)
    at listenInCluster (net.js:1346:12)
    at Server.listen (net.js:1434:7)
    at /home/hami/Foodies/node_modules/metro/src/index.js:257:20
    at new Promise (<anonymous>)
    at Object.<anonymous> (/home/hami/Foodies/node_modules/metro/src/index.js:256:14)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/home/hami/Foodies/node_modules/metro/src/index.js:46:24)
    at _next (/home/hami/Foodies/node_modules/metro/src/index.js:66:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Foodies@0.0.1 start: `react-native start "--port=8081"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Foodies@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hami/.npm/_logs/2020-01-02T10_14_13_081Z-debug.log

#############################################################################################

package.json

{
  "name": "Foodies",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@react-native-community/masked-view": "^0.1.5",
    "react": "16.9.0",
    "react-native": "0.61.5",
    "react-native-gesture-handler": "^1.5.3",
    "react-navigation": "^4.0.10",
    "react-navigation-stack": "^2.0.1"
  },
  "devDependencies": {
    "@babel/core": "^7.7.7",
    "@babel/runtime": "^7.7.7",
    "@react-native-community/eslint-config": "^0.0.5",
    "babel-jest": "^24.9.0",
    "eslint": "^6.8.0",
    "jest": "^24.9.0",
    "metro-react-native-babel-preset": "^0.57.0",
    "react-test-renderer": "16.9.0"
  },
  "jest": {
    "preset": "react-native"
  }
}

**Comment by AbiltonDias** [comment]
Hi guy, so I'm with problem, and found this solution:

https://medium.com/@rismandev/react-native-error-listen-eaddrinuse-address-already-in-use-8081-8512831d4194

I hope that help you!
