### ISSUE TITLE
[iOS] When keyboard is focused and back is pressed, previous screen moves off the screen partially

### ISSUE THREAD

**Issue by rogerkerse** [react-navigation/react-navigation#6543]
Code is here and tested on iOS: https://snack.expo.io/@bolts/react-navigation-back-offset-bug
### Current Behavior

- What code are you running and what is happening?
I am running this expo snack -> https://snack.expo.io/@bolts/react-navigation-back-offset-bug
When textinput if focused and back is pressed, then the whole previous screen shifts right.

- Include a screenshot if it makes sense.

![ezgif-2-eeaeb0b51a45](https://user-images.githubusercontent.com/571171/71682435-628e6700-2d98-11ea-930c-f1fb75e18976.gif)

Screen should be centered but this happens
<img width="290" alt="Screenshot 2020-01-02 at 19 37 42" src="https://user-images.githubusercontent.com/571171/71682121-62da3280-2d97-11ea-976c-fa9c5abf0e95.png">

### Expected Behavior

- What do you expect should be happening?
Previous screen was centered so I expect when back is pressed, it still would be.

- Include a screenshot if it makes sense.

### How to reproduce

I added snack above. Also gif that shows.
1. Press Search button
2. Focus search field
3. Press back button

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^4.0.10
| react-native     | https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz
| node             | 13.1.0
| npm or yarn      | yarn latest

**Comment by rogerkerse** [comment]
It even happens when the textinput is inside the scene and not on the navbar

**Comment by simonelp** [comment]
Hi, I solved this problem by updating react-navigation-stack. The operation led me to make some changes to the application, but it worked for me.

**Comment by satya164** [comment]
Please upgrade to latest version

**Comment by GleidsonDaniel** [comment]
> Hi, I solved this problem by updating react-navigation-stack. The operation led me to make some changes to the application, but it worked for me.
Same here.
For those who came here, this up here resolved.

> Please upgrade to latest version
Useless.
Which version? Which lib? :thumbsdown:

**Comment by JulioRosil** [comment]
Still having this issue, don't know how to solve it. 
It moves off the screen to the bottom and hide some bottom buttons.

My environment:
  "react-native": "0.68.1",    
  "@react-navigation/native": "^6.0.8",
  "@react-navigation/native-stack": "^6.5.0",
