### ISSUE TITLE
v4.0.10 example does not work with expo start --web

### ISSUE THREAD

**Issue by kopax** [react-navigation/react-navigation#6547]
I am a user of `react-router` and discovered `react-navigation` while doing my first expo (SDK36) application.

I want to support web and native, after testing your demo, I wonder why there is a `web` compatibility while the example does not support the web.

Also, expo documentation [suggested](https://docs.expo.io/versions/latest/guides/routing-and-navigation/) that we use the `react-router` library directly

### Current Behavior

When I run on the `example` `expo start-web`,

I have compiling issue due to typescript:

```bash
 web  Failed to compile.
/home/dka/workspace/github.com/react-navigation/react-navigation/example/App.tsx
SyntaxError: /home/dka/workspace/github.com/react-navigation/react-navigation/example/App.tsx: Unexpected token (42:17)

  40 | import TabsInDrawer from './src/TabsInDrawer';
  41 | 
> 42 | const ExampleInfo: any = {
     |                  ^
  43 |   CustomTabUI: {
  44 |     description: 'Render additional views around a Tab navigator',
  45 |     name: 'Custom Tabs UI',
```

And the web showing:

![image](https://user-images.githubusercontent.com/1866564/71749796-be2f2200-2e76-11ea-97cb-59481979251d.png)

### Expected Behavior

I expect it to run on the web

### How to reproduce

```
git clone git@github.com:react-navigation/react-navigation.git
cd react-navigation
git checkout v4.0.10
yarn bootstrap
cd example
npx expo start --web
```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | v4.0.10
| react-native     |  0.59.8
| node             | 13.5.0
| yarn      | 1.21.1

Is react-navigation ready for web development or should I got with react-router-dom for the web?

**Comment by satya164** [comment]
Closing since we don't plan to add running web example to v4's example app. v4 is in maintenance mode and will only receive bug fixes.
