### ISSUE TITLE
Intermittent padding issue with custom header

### ISSUE THREAD

**Issue by alizahid** [react-navigation/react-navigation#6549]
### Current Behavior

I have a custom header (and tab bar) in my navigators. Every now and then, this happens;

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-01-05 at 16 06 00](https://user-images.githubusercontent.com/941775/71779992-234d5980-2fd6-11ea-9066-c10970dc5379.png)

My header is taller than the default header. The issue doesn't happen when using the default header.

### Expected Behavior

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-01-05 at 16 13 11](https://user-images.githubusercontent.com/941775/71779999-4d9f1700-2fd6-11ea-86a5-012ac8917259.png)

### How to reproduce

Here's my app: https://github.com/willa/app

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^4.0.10
| react-native     | 0.61.5
| node             | v13.4.0
| npm or yarn      | yarn 1.21.1

**Comment by alizahid** [comment]
On the device, it got even worse somehow;

![IMG_A2A888314FE3-1](https://user-images.githubusercontent.com/941775/71780139-5264ca80-2fd8-11ea-9274-b04ce43e7fc9.jpeg)

**Comment by satya164** [comment]
Please try with the latest version (2.0.8). You can also specify a height in `headerStyle: { height: YOUR_HEADER_HEIGHT }`

**Comment by pzatorski** [comment]
@alizahid Are you still facing the same issue, after **satya164** suggestion ?

**Comment by alizahid** [comment]
Unfortunately, upgrading to `2.0.14` didn't help. Neither does setting my own height.

I feel this is due to the safe area view. I'm still using the one from `react-navigation`. Could that be the case?

**Comment by alizahid** [comment]
Okay, tried a few things;
- using `SafeAreaView` from `react-native-safe-area-context`; still the same behavior.
- using a global `SafeAreaView` from `react-native-safe-area-context`; results in the following.
<img width="820" alt="Screen Shot 2020-01-13 at 2 15 09 PM" src="https://user-images.githubusercontent.com/941775/72247787-1ef4f200-360f-11ea-85dd-7f500e778d24.png">

**Comment by Silon** [comment]
@alizahid any solution for this issue? Did you solved it?

**Comment by alizahid** [comment]
I’m gonna close this issue since I’m upgrading all my apps to v5. Will open again if the issue persists.

**Comment by alizahid** [comment]
The issue still persists with;

```
"@react-navigation/bottom-tabs": "^5.1.1",
"@react-navigation/native": "^5.0.9",
"@react-navigation/stack": "^5.1.1",
```

I will add a snack soon.

**Comment by alizahid** [comment]
Unfortunately, I couldn't create a Snack.

But here's the GitHub repo: https://github.com/alizahid/ReactNavigationHeaderBug

And here's a video: https://imgur.com/a/Dcs4EUr

**Comment by satya164** [comment]
I don't see a `headerStyle` in your repro.

https://reactnavigation.org/docs/stack-navigator#specify-a-height-in-headerstyle

**Comment by alizahid** [comment]
I tried that with v4 but it didn't work. I'll try with v5 and report back.

**Comment by alizahid** [comment]
@satya164 `headerStyle` only works intermittently. Also, if I have a dynamic header (`top` from `useSafeArea` + my header height depending on what's in it), how would I account for that?

**Comment by satya164** [comment]
> headerStyle only works intermittently.

We need a repro to debug it. Can you share a repro with `headerStyle` that's not working for you?

> Also, if I have a dynamic header (top from useSafeArea + my header height depending on what's in it), how would I account for that?

Include safe area value in your header height.

**Comment by alizahid** [comment]
I've found a solution following @satya164's suggestion. Closing this issue.
