### ISSUE TITLE
Bug, when use mobx decorator

### ISSUE THREAD

**Issue by GMati13** [react-navigation/react-navigation#6551]
When I use mobx decorator, I has an error:
![image](https://user-images.githubusercontent.com/31896990/71787423-3a189e00-3020-11ea-97a1-0f08e279a010.png)

It's happening if Scene class is decorated through mobx inject decorator.
To resolve this I should wrap the Scene to "clean component", then it works perfectly.
Also I think that it can happen in case with others decorators.

how to reproduce:
```js
@inject('smthStore')
class Scene extends React.Component {
  render() {
    return (
      <View>
        <Text>{this.props.smthStore.smthValue}</Text>
      <View>
    );
  }
}

const Navigator = createStackNavigator({
  smthScene: Scene
});
```

how to fix:

```js
const Navigator = createStackNavigator({
  smthScene: () => <Scene />
});
```

**Comment by satya164** [comment]
Doesn't look like related to React Navigation. You need to ask for help in MobX related channels.
