### ISSUE TITLE
StackNavigator leftComponent display issue

### ISSUE THREAD

**Issue by lukecurtis93** [react-navigation/react-navigation#6552]
### Current Behavior

Currently, I am overriding the navigation options of a Stack Navigator with a custom left component.
```js
MealScreen.navigationOptions = () => {
  return {
    header: (
      <Header
        containerStyle={{ backgroundColor: "#fff" }}
        leftComponent={<MealScreenBackNavigation />}
        centerComponent={{
          text: "PLANS",
          style: {
            color: "rgba(42,172,229,1)",
            fontSize: 20,
            fontWeight: "bold"
          }
        }}
      />
    )
  };
};
const MealScreenBackNavigation = () => {
  return (
    <TouchableOpacity
      onPress={() => {
        back();
      }}
    >
      <Ionicons name="ios-arrow-back" size={20} color="rgba(42,172,229,1)" />
    </TouchableOpacity>
  );
};

```

It displays great. However when navigating back with a custom left component, the component is removed and the native "Back" icon is displayed on iOS.

### Expected Behavior

The overridden input should display.

### How to reproduce

![example](https://user-images.githubusercontent.com/26925537/71798199-e5ffcf00-309c-11ea-8e20-2c3f3d15f07f.gif)

https://snack.expo.io/B1kCy8eeL

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 4.0.10
| react-native     | 0.61.4
| node             | 10.15.3
| npm or yarn      | yarn 1.17.3

**Comment by satya164** [comment]
Set `headerMode` to `screen` as mentioned in docs https://reactnavigation.org/docs/en/stack-navigator.html#header
