### ISSUE TITLE
Navigating to specific key does not work

### ISSUE THREAD

**Issue by panda0603** [react-navigation/react-navigation#6554]
I am trying to making a web browser app with react native. I'm implementing tab feature in which user can add many tabs(screens) and navigate to each screen if they click on them in TabList Screen where all the tabs opened are listed up. 

The logic here is to push same screen or route (internally would have different key) using navigation.push('browseScreen') every time user clicks on add tab, and use navigation.navigate('browseScreen', {key: keyOfTheScreen}) to navigate to the specific screen in the stack. 

### Current Behavior
What I did is get the key of the screen pushed using 'this.props.navigation.state.key' and save it to an array to be rendered in the TabList screen where all the tabs are listed for users to click.
so every time screen is pushed, following code is executed. 
```
 const tabInfo = {
      key: this.props.navigation.state.key,
      webImage: ...,
      title: ...
    };
     
tabListArray.push(tabInfo);

```
using the array, I then render all the screens pushed in TabList Screen. Now in order to navigate to some particular screen already pushed, I do

```
tabListArray.map(item=>{
return(
      <TouchableOpacity
        style={styles.tabLook}
        onPress={() => {
          this.props.navigation.navigate('FavScreen', {key: item.key});
        }}>
        <Text>{item.key}</Text>
      </TouchableOpacity>
)
}
```

But this does not return to the specified key. At the moment, it just straightely navigates to the first screen pushed, regardless of which tab I click on in the TabList Screen, and pops all other screens pushed.  Am I wrong on how I use it? 

From what I understand, when we use navigation.navigate, it keeps all other screens(not pop) mounted so that users can jump between the opened tabs right?

### Expected Behavior

jump to the screen with specified key. How would I achieve the desired behavior?

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 4.0.10
| react-native     |0.61.5
| node             |10.16.0
| npm or yarn      | npm

**Comment by OscarYuen** [comment]
Hello, How do you resolve this?
