### ISSUE TITLE
tab navigator, A has title, B doesn't, B will have an white space

### ISSUE THREAD

**Issue by L-x-C** [react-navigation/react-navigation#6556]
I have a tab navigator with 2 tabs
I want tab A has a title 'home', tab B has no header,
So here is my code
```
tabNavigator.navigationOptions = ({ navigation }: { navigation: { state: object } }) => {
  const { routeName } = navigation.state.routes[navigation.state.index]
  if (routeName  === 'home') {
    return {
      headerTitle: 'home',
    }
  } else {
    return {
      header: null,
    }
  }
}
```
Here is the result
![bug](https://user-images.githubusercontent.com/4329120/72034179-42e2cb80-32cf-11ea-9dde-cb885a924134.gif)

As you can see home is showed OK, but tab B has a white space in the header

If both of the tabs are header: null, it will be OK
```
tabNavigator.navigationOptions = ({ navigation }: { navigation: { state: object } }) => {
  return {
    header: null,
  }
}
```
![bb2](https://user-images.githubusercontent.com/4329120/72034418-e2a05980-32cf-11ea-9dbd-29d596b85782.gif)

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 4.0.10
| react-native     | 0.61.5

**Comment by satya164** [comment]
Upgrade to latest stack and use `headerShown: false`
