### ISSUE TITLE
Interactive Transition

### ISSUE THREAD

**Issue by Ufosek** [react-navigation/react-navigation#6559]
Hi,

Is it possible to create interactive transition in Stack Navigator with this great library? Back gesture is already automatically supported - e.g. if I create FromBottom transition (using `navigationOptions/cardStyleInterpolator -> transform`) and enable gesture then user can swipe to close the screen.
The solution I am looking for is similar to iOS-Native `UIPercentDrivenInteractiveTransition`. It allows to trigger navigation (`navigate('details')`) but also to send current progress. So I can create GestureListener on some object and during this gesture I can update transition progress. Then it could use `cardStyleInterpolator -> transform` as with back to calculate proper position etc.

Youtube app may be the good example - we can swipe video to small player bar and then swipe it to fullscreen. I was able to achieve it using iOS native (`UIPercentDrivenInteractiveTransition`) but unfortunately I could not do it on Native Android (Fragment Transitions does not allow interactive animation). 

Of course I could just create a gesture animation on "non-screen" object and just place it above current screen (as here: [https://codedaily.io/tutorials/10/Create-a-Youtube-Video-Page-with-Animated-Video-Drag-to-Corner-in-React-Native](https://codedaily.io/tutorials/10/Create-a-Youtube-Video-Page-with-Animated-Video-Drag-to-Corner-in-React-Native)) but I think it would be great to create it with navigation as normal screen transition.

Thanks in advance!

**Comment by satya164** [comment]
Stack v2 exports `useCardAnimation()` which has the progress value
