### ISSUE TITLE
Document version confusion.

### ISSUE THREAD

**Issue by yisar** [react-navigation/react-navigation#6560]
In documents, sometimes is 
`import { createBottomTabNavigator } from 'react-navigation-tabs'`
and sometimes is
`import { createBottomTabNavigator } from '@react-navigation/bottom-tabs'`

Can you unify the document? It's old

I don't know which is the latest

**Comment by eriveltonelias** [comment]
Hi @yisar, 

```js
// this import is from react-navigation v4
import { createBottomTabNavigator } from 'react-navigation-tabs'
```

```js
// this import is from react-navigation v5
import { createBottomTabNavigator } from '@react-navigation/bottom-tabs'
```

**Comment by yisar** [comment]
Thank you!
