### ISSUE TITLE
Back button display wrong on Ipad

### ISSUE THREAD

**Issue by maitrungduc1410** [react-navigation/react-navigation#6561]
When I test my app on iPad, the back button displays wrongly. It takes my Screen's name.

<img width="309" alt="Screenshot 2020-01-11 at 23 02 51" src="https://user-images.githubusercontent.com/16630193/72206289-c1558e00-34c6-11ea-83be-cfa300ef4088.png">

In the screenshot, it displays my screen's name, but it should display `Back`

On iPhone it works fine

Does anyone have this issue?

### My Environment

| software         | version
| ---------------- | -------
| Device | Simulator iPad Pro (9.7 inch, iOS 13)
| react-navigation | 4.0.10
| react-native     | 0.61.5
| node             | 10.15
| npm or yarn      | 6.13

**Comment by satya164** [comment]
The back button shows the screen title as long as there's enough space. If you don't want it, you need to set `headerBackTitle`: https://reactnavigation.org/docs/en/stack-navigator.html#headerbacktitle
