### ISSUE TITLE
Right method to execute navigation code (navigate to other screen) after completion of redux cycle.  

### ISSUE THREAD

**Issue by dev-pacific22** [react-navigation/react-navigation#6564]
**Current Behavior**
I am using Redux and React Navigation in my app where I am making some API calls, 
I have a question that after successful completion of my redux cycle which lifecycle method of react component I should have to use for navigation to the next screen and why? 

Example: 

1. The user has clicked on the login after putting his credentials on Login Screen.
2. Executed the login redux action and returned a success
3. After success, my Login screen props get changed and I want to redirect to the next screen. 
4. In which method I should have to put the navigation code like `this.props.navigation.navigate("DashoardScreen');`

**Expected Behavior**

We should have to navigate to the next screen component using redux and react-navigation.

**Your Environment**

| software         | version |
| ---------------- | ------- |
| react-navigation |4.0.10
| react-native     |0.61.5
|redux             |4.0.5
| npm or yarn      |

**Comment by vonovak** [comment]
hi there! this issue tracker is reserved for bugs only. your post seems to be a usage question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help. thanks!
