### ISSUE TITLE
Default back button - how to make this go back to the home page and not prev page

### ISSUE THREAD

**Issue by rajBar** [react-navigation/react-navigation#6565]
**Current Behavior**

- From my homepage I go through some pages: e.g.
Homepage -> page1 -> page2 -> page3

When on page3, the default back button in the top left hand corner will take you back to page2. However, this doesn't make sense in my application, and I would like to have this button take me back to 'Homepage'

Any idea how to do this? Thanks :)

**Comment by eriveltonelias** [comment]
you can customize your back action on page3, you can use 

```js
navigation.popToTop()
```

**Comment by rajBar** [comment]
Hey Thanks....

I've got this working for the back button, but on Android when the native back button is pressed, it still goes back to  page2 (same thing happens when you swipe 'back' on iOS)

Here is the code I currently have:
```
const MainNavigator = createStackNavigator({
  Home: {screen: StartPage},
  NewGame: {screen: NewGame},
  LoadGame: {screen: LoadGame},
  NewLeague: {screen: NewLeague},
  League: {
    screen: League,
    navigationOptions: ({navigation}) => {
      return {
        title: 'League',
        headerLeft: (
          <HeaderBackButton
            onPress={() => {
              navigation.popToTop();
              // navigation.navigate('Home');
            }}
          />
        ),
      };
    },
  },
});
```

**Comment by eriveltonelias** [comment]
on Android you can customize the BackButton https://reactnavigation.org/docs/en/custom-android-back-button-handling.html#docsNav

or you can reset your stack after navigate to page3 

Homepage -> page1 -> page2 ->( reset your stack routes in here ) page3

https://reactnavigation.org/docs/en/stack-actions.html#reset

**Comment by rajBar** [comment]
Unfortunately I am unable to do what I require using the documentation. Could you please review my desired functionality to see if it's possible:

                  <--> createGame  -->  game  <--> editGame
homepage                               ↙
                  <--> loadGame     <-->  game  <--> editGame


in the top route, I want to reset the stack to be [homepage, loadgame, game], but it's staying as [homepage, createGame, game]. I've added the functionality for the back button to just default to 'homepage' from 'game' - but it doesn't provide a nice user experience.

Would it be possible to have this functionality? If so, how can I utilize the stack actions to do so? There are no concrete examples of this anywhere online :/

Thank you
