### ISSUE TITLE
add a plus button in the createBottomTabNavigator

### ISSUE THREAD

**Issue by ouba421** [react-navigation/react-navigation#6567]
How do I implement add a plus button in the createBottomTabNavigator so that when I click on it it comes up with a modal？

![image](https://user-images.githubusercontent.com/31402685/72319281-bd4d8a00-36d9-11ea-94aa-e8b095924e83.png)

**Comment by eriveltonelias** [comment]
Hi @ouba421 
you can create your own custom tabBarComponent, check this https://reactnavigation.org/docs/en/bottom-tab-navigator.html#docsNav
