### ISSUE TITLE
How to implement routing nesting using v4

### ISSUE THREAD

**Issue by NextChampion** [react-navigation/react-navigation#6570]
Before, I used v2 to achieve this effect by routing nesting: horizontally switched routes can pop up modal, and pages inside modal can be switched horizontally.

It is found that the routing nesting of the v4 version is not the same as before。

Can anyone help me achieve the previous effect using v4

"react-native": "0.61.5",
"react-navigation": "4.0.10",

**Comment by vonovak** [comment]
hi there! this issue tracker is reserved for bugs only. your post seems to be a usage question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help. thanks!

Also, when asking, please be more detailed. It's really hard to understand what you mean by "horizontally" in the context of the question. As always, runnable code would help. Thank you.
