### ISSUE TITLE
Are transitions without dropped frames possible?

### ISSUE THREAD

**Issue by djendacott** [react-navigation/react-navigation#6571]
Even with an empty demo project, I find that I can't navigate to a new view without dropping at least one or two frames during the transition animation. This is a real bummer because it's the only thing separating the feel of my react native app from a genuine native app.

Here's a video recorded at 60fps on an iPhone XS. You'll notice a frame drop toward the end that makes the animation feel choppy.

[dropped-frame.mp4.zip](https://github.com/react-navigation/react-navigation/files/4075042/dropped-frame.mp4.zip)

I believe react navigation uses the native driver so what is causing this dropped frame? And can anything be done to prevent it and create smoother transitions?

**Comment by satya164** [comment]
> And can anything be done to prevent it and create smoother transitions

Do all expensive tasks in `InterationManager.runAfterInteractions`
