### ISSUE TITLE
backBehavior: 'initialRoute' and backBehaviour: 'history' not working

### ISSUE THREAD

**Issue by ismailkhan89** [react-navigation/react-navigation#6573]
**Current Behavior**
I have 5 tabs on bottom with  createBottomTabNavigator functionality.
Then i have sub screens for each tab Like home screen also have screen for chat 
for suppose a user in home tab visited chat screen and then change the tab to Cart when user click on home tab again so user should see the inital screen instead of chat screen which was recently opened in this tab.
So when user revisit the tab it has last visited screen instead of initial screen.
- What code are you running and what is happening?
const Tabs = createBottomTabNavigator({
  HOME: {
      screen: HomeStack,
      initialRouteName: NAVIGATION_HOME_SCREEN,
      backBehavior: 'initialRoute'
  },
[NAVIGATION_TRIP_TREE_PATH]: {
    screen: TripStack,
      initialRouteName: NAVIGATION_PRODUCT_LIST
      backBehavior: 'initialRoute'

  }
})

**Comment by satya164** [comment]
#7317
