### ISSUE TITLE
How can i cover the BottomTabNavigator in nested StackNavigator

### ISSUE THREAD

**Issue by qiaoyixuan** [react-navigation/react-navigation#6574]
- BottomTabNavigator
    - StackNavigator
        - Drawer(react-native-drawer)

Drawer's mask is under BottomTabNavigator,How can i cover the BottomTabNavigator in nested StackNavigator

**Comment by qiaoyixuan** [comment]
![image](https://user-images.githubusercontent.com/13936160/72798341-d926d200-3c7d-11ea-9685-470953013ebf.png)

**Comment by abduraufsherkulov** [comment]
I have the same issue. I nested **StackNavigator** into **BotomTabNavigator** and when user is inside of **StackNavigator**, **BottomTabNavigator** is still visible. Is there any possible way to hide it on certain screens of **StackNavigator**? Is it overall the most optimal way of doing it? Or one should nest **BottomTabNavigator** into **StackNavigator** to achieve best performance?

**Comment by vonovak** [comment]
hello and thanks for asking. Please take a look at https://reactnavigation.org/docs/en/tab-based-navigation.html#a-stack-navigator-for-each-tab and https://reactnavigation.org/docs/en/navigation-options-resolution.html#a-tab-navigator-contains-a-stack-and-you-want-to-hide-the-tab-bar-on-specific-screens

hope this helps, thanks
