### ISSUE TITLE
How can I have <ScrollView /> within my HomePage in react-navigation v5.x?

### ISSUE THREAD

**Issue by kopax** [react-navigation/react-navigation#6577]
I am working on a react-native application that use `@react-navigation/stack@^5.0.0-alpha.53`.

In react-navigation 4, we use to have a custom `ScrollView` exported : https://reactnavigation.org/docs/en/scrollables.html#docsNav

This does not exist in version 5, my `HomeView` is a ScrollView, and it is not scrollable when used with react-navigation.

How can I use a ScrollView with react-navigation 5?

**Comment by 5paun** [comment]
Hi. If I understand correctly, scrolling to react-navigation v5 does not work for you. I have the following problem. When updating react-navigation with v4 to v5, when the keyboard opens in the input form, my form does not fit on the screen completely. And scrolling does not work. Have you solved this problem somehow? Еhank you in advance for your help!

**Comment by kopax** [comment]
No I did not solved that problem. 

I took so much time trying to understand why the scrolling does not work on orientation change on certain page, I decided to lock the orientation (todo) on android and I will investigate later.

If you find any solution or explanation, please share, I'll keep you updated also.

**Comment by yalcinozer** [comment]
Scrollview usage on a clean App.js project fike works flawlessly.

`<ScrollView style={{flex:1}}></ScrollView>`

All you need is to give it flex:1 and add some components in it including TextInput. It will work. But using wrapped by navigations causes some problems.(It can't be scrolled or it need a specific height property etc) I dont know how to solve this.
