### ISSUE TITLE
Memory increases when I navigate between screens

### ISSUE THREAD

**Issue by billypap1** [react-navigation/react-navigation#6581]
**Current Behavior**

- What code are you running and what is happening?

I use React-Navigation v4 (Stack Navigator) with react-native-screens v2.0.0-alpha.6 and I have noticed a memory increase when I navigate between screens.
For example, if I populate a list with Items and navigate to an Item Page memory adds up 5mb. Even If I go back, memory is not released.It's like adding the same page in stack, even I have visited before. Is this a bug? Can I remove same screen names from stack?

- Include a screenshot or video if it makes sense.

Memory Results Here -> [Memory Results](https://i.stack.imgur.com/nHTSS.png)

**Expected Behavior**

- What do you expect should be happening?

Navigate to Item's Page and when I go back to Remove the page from stack or replace it with an other page with same name.

- Include a screenshot or video if it makes sense.
-

**Environment**

| software         | version |
| ---------------- | ------- |
| iOS   | 13.3
| react-navigation | v4.0.10
| react-native     | 0.61
| expo             | -

**Comment by sbycrosz** [comment]
Hey, did you manage to fix this? 

We run into this bug when we're trying to upgrade react-navigation :(

**Comment by satya164** [comment]
Closing in favor of #7078
