### ISSUE TITLE
The action buttons are not coming in iOS notification due to react-navigation

### ISSUE THREAD

**Issue by dhruvil1514** [react-navigation/react-navigation#6582]
I am using react native(0.52) for building my iOS app.I am using react navigation library(1.0.0) for navigating around different screens.I am trying to get action buttons for my iOS notifications.I have successfully registered the categories for iOS notification in my native method of appdelegate.m .But when I get my first notification with  action buttons I am using react navigation to redirect to other screens according to the action buttons user has clicked.After successfully redirecting to the other screen when I again get the notification the action buttons are not coming.Is this the problem of react navigation library?.Does anyone know workaround?

Here is my code for registering categories in appdelegate.m
```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
 
  
  UNNotificationAction* Calendar = [UNNotificationAction
        actionWithIdentifier:@"Calendar"
        title:@"Calendar"
        options:UNNotificationActionOptionNone];
  
  UNNotificationAction* Harisha = [UNNotificationAction
         actionWithIdentifier:@"Harisha"
         title:@"Harisha"
         options:UNNotificationActionOptionNone];
   
  UNNotificationCategory* expiredCategory = [UNNotificationCategory
  categoryWithIdentifier:@"SOME_CATEGORY"
  actions:@[Calendar,Harisha]
  intentIdentifiers:@[]
  options:UNNotificationCategoryOptionNone];
  UNUserNotificationCenter* center = [UNUserNotificationCenter currentNotificationCenter];
  [center setNotificationCategories:[NSSet setWithObjects:expiredCategory,
        nil]];

**Comment by yashvanthkg** [comment]
+1

**Comment by vonovak** [comment]
hi there! this issue tracker is reserved for bugs only. your post seems to be a usage question which is better suited for stackoverflow or discord. see https://reactnavigation.org/help.html for more information on how to get help. thanks!
