### ISSUE TITLE
Where is the `tabBarComponent` option in version 5?

### ISSUE THREAD

**Issue by janoist1** [react-navigation/react-navigation#6583]
I can't find the option `tabBarComponent` in the documentation of the new version: https://reactnavigation.org/docs/en/next/bottom-tab-navigator.html

How am I supposed to use my own TabBarComponent?

**Comment by satya164** [comment]
https://reactnavigation.org/docs/en/next/bottom-tab-navigator.html#tabbar

**Comment by mrcMesen** [comment]
Sorry! I cant find it, can you help me?

**Comment by raajnadar** [comment]
https://reactnavigation.org/docs/bottom-tab-navigator/#tabbar

**Comment by angelxmoreno** [comment]
So, for clarity: in v5 the `tabBarComponent` from previous versions has been replaced with the `tabBar` function. An example is in the link @raajnadar [posted](https://reactnavigation.org/docs/bottom-tab-navigator/#tabbar).
