### ISSUE TITLE
React-Navigation navigtion file not imported properly

### ISSUE THREAD

**Issue by Thirumalaisamy-paulraj** [react-navigation/react-navigation#6585]
**Current Error**
Invariant Violation: The navigation prop is missing for this navigator. In react-navigation 3 you must set up your app container directly
Pls help me for find the solution

**Current Output**

![WhatsApp Image 2020-01-29 at 2 35 15 PM](https://user-images.githubusercontent.com/52504374/73343219-32a68680-42a6-11ea-8f1a-2bf34179d975.jpeg
![WhatsApp Image 2020-01-29 at 2 35 15 PM](https://user-images.githubusercontent.com/52504374/73343294-59fd5380-42a6-11ea-8269-22d8dc693988.jpeg)

**Comment by eriveltonelias** [comment]
Hi @Thirumalaisamy-paulraj 

check this https://reactnavigation.org/docs/en/3.x/app-containers.html
