### ISSUE TITLE
Blank screen iOS

### ISSUE THREAD

**Issue by georgeMorales** [react-navigation/react-navigation#6586]
Problem iOS
react navigation 4.0.10
expo sdk 36
node v10.16.0
npm 6.13.4

My navigation consists of a createStackNavigator RootNoAuth that only has the screen login, it also has a createMaterialTopTabNavigator RootTopTab that has several tabs and another createStackNavigator RootAuth that brings together different screens and the createMaterialTopTabNavigator.
RootAuth has this structure:
```js
const RootAuth = createStackNavigator (
    {
        Welcome: {
            screen: Welcome,
            navigationOptions: ({navigation}) => ({
              header: null
            }),
        },
        RootTopTab: {
          screen: AppRootTopTapContainer,
          navigationOptions: ({navigation}) => ({
            header: null
          }),
        },
        ProfileEdit,
        ProfileSettings,
        ...
);
```

then there is a createSwitchNavigator
```js
const RootNav = createSwitchNavigator (
  {
      Loading: LoadingScreen,
      RootNoAuth: {
        screen: AppRootNoAuth,
      },
      RootAuth: {
        screen: AppRootAuth
      }
  },
  {
    initialRouteName: 'Loading',
  }
);
```

The problem is that after Welcome I get a blank screen, but it reaches the next screen because it loads the data.
In Welcome navigation.push ('RootTopTab') or navigation.navigate ('RootTopTab')
In expo sdk 35 it works well for iOS and Android, now with sdk 36 of expo it works perfect in Android but in iOS I get a blank screen and no error appears.
If in RootAuth I remove Welcome screen and the first one is RootToTab, then if the following screen appears, but I need Welcome screen to check and make calculations for the next screen.

**Comment by satya164** [comment]
Can you provide a repro on https://snack.expo.io?

**Comment by georgeMorales** [comment]
It's a huge project, I don't know if I could recreate it at https://snack.expo.io.
I will try to create an example

**Comment by satya164** [comment]
You need to provide a minimal example to repro the issue.

**Comment by georgeMorales** [comment]
I have already been able to fix the problem, when making a test application to upload to github and that you could verify it, I have realized that "react-navigation-stack": "^ 1.10.3", "react-navigation- tabs ":" ^ 2.5.6 "which are the versions I have in my app, there are newer versions" react-navigation-stack ":" ^ 2.1.0 "," react-navigation-tabs ":" ^ 2.7. 0 ", I have updated and it worked ...
Thank you

**Comment by alejomendoza** [comment]
Still happening for us as well, works on the Expo client app but then when creating the standalone build breaks.
