### ISSUE TITLE
Used `yarn upgrade-interactive` and upgraded react-navigation from 4.0.10 to 4.1.0 -- now missing react-native-screens

### ISSUE THREAD

**Issue by bobber205** [react-navigation/react-navigation#6587]
Seems to be a new dependency? 

Got

`Error: Unable to resolve module `react-native-screens``

when trying to load my local bundle after upgrading.  Adding react-native-screens manually did the trick.

**Comment by satya164** [comment]
It was mistakenly in dependencies and due to flattening of node_modules by yarn, it used to work for you.

You need to manually install it.

**Comment by mjmasn** [comment]
@satya164 so will this be fixed in the next version or is it a permanent change that we need to have react-native-screens installed? :thinking:

**Comment by satya164** [comment]
@mjmasn you'll need to install screens in your project manually. it means that you can stay on latest version of screens without needing us to update (which is important in case of screens) and also it's the only reliable way of making sure that autolinking works properly for all packagae managers.

**Comment by mjmasn** [comment]
@satya164 makes sense, thanks :+1:
