### ISSUE TITLE
addListener via ref

### ISSUE THREAD

**Issue by Aidoboy** [react-navigation/react-navigation#6590]
**Current Behavior**

           <App
                ref={nav => {
                    this.navigator = nav;
                    let self = this;
                    if(nav) {
                        console.log("print nav");
                        console.log(Object.getOwnPropertyNames(nav.state.nav));
                        console.log("print nav");
                        nav.addEventListener('didBlur',
                            payload => {
                                //console.debug('didBlur', payload);
                                self.setState({
                                    canBack: navigator.state.routes[navigator.state.index].index === 0
                                });
                            })
                    }
                }}
            />

`undefined is not a function (near '...nav.addEventListener...')`

**Expected Behavior**

I expect the function to exist

**How to reproduce**

https://snack.expo.io/@aidanedwardsbu/refeventlistener

**Your Environment**

| software         | version |
| ---------------- | ------- |
| iOS or Android   |  Android
| react-navigation |  4.0.10
| react-native     | Provided be expo, I think?
| expo             | 36.0.2
| node             | v10.15.2
| npm or yarn      | 6.13.6

**Comment by satya164** [comment]
Events are for screens. Screens get focused and blurred. What's exactly are you expecting from adding a listener on navigator?

Closing since this is not supported.

**Comment by Aidoboy** [comment]
@satya164 I'm trying to make the back button appear and disappear on a `react-native-paper` `AppBar.Header` and I need some kind of event to trigger on. Is this not the right thing to use? What should I use? Going back using that navigation ref works fine, I just want to know when I can use it and when I can't.

**Comment by satya164** [comment]
If you are using `header` option in stack to render your appbar, you'll receive a prop called `previous`. If it exists, there's a previous screen and you can show back button there. You don't need to listen to events. You also get `navigation` prop there which you should use for going back.

**Comment by satya164** [comment]
https://reactnavigation.org/docs/en/stack-navigator.html#header

**Comment by Aidoboy** [comment]
@satya164 Is there any way to stop the App Bar from flashing when I use it with the Material Bottom Bar that way? Maybe I should've posted that issue instead that was the root of the problem.

**Comment by satya164** [comment]
`sceneAnimationEnabled: false` in your material bottom navigation config.

**Comment by Aidoboy** [comment]
@satya164 Is there a way to disable in on just the AppBar?

**Comment by ljubomirsinadinovski** [comment]
I think this issue has to be re-opened, because I am saving the ref from the <NavigationContainer>  in mobx store for further use in child components. When I want to detect an event of loading the screen (in the child component of the screen e.g. focus of the screen event) if I use the navigationRef from MobX (which contains addListener) I cannot fire up my focus methods. On the other hand if i pass downs this.props.navigation as a property to my child component and call addListener, the event is added to the listener and everything works fine. What do you think @satya164 ??
