### ISSUE TITLE
Missing drawer methods from navigation prop

### ISSUE THREAD

**Issue by slavikdenis** [react-navigation/react-navigation#6592]
Using version: 4.1.0

What was the reason of removing drawer methods in this commit https://github.com/react-navigation/react-navigation/commit/683892e ?

Using `react-navigation-hooks` now breaks TS with:

```
Property 'closeDrawer' does not exist on type 'NavigationScreenProp<NavigationRoute<NavigationParams>, NavigationParams>'.     

28  const { navigate, closeDrawer } = useNavigation();
                      ~~~~~~~~~~~
```

```
Property 'toggleDrawer' does not exist on type 'NavigationScreenProp<NavigationRoute<NavigationParams>, NavigationParams>'.       

14  const { toggleDrawer } = useNavigation();
            ~~~~~~~~~~~~
```

Thanks

**Comment by satya164** [comment]
https://reactnavigation.org/docs/en/typescript.html

https://github.com/react-navigation/hooks/issues/42

**Comment by slavikdenis** [comment]
@satya164 oh, missed that. Thanks :)
