### ISSUE TITLE
lazy load still loads intermediate screens

### ISSUE THREAD

**Issue by conleymon** [react-navigation/react-navigation#6593]
When navigating to the 'last' screen in a  navigator definition, react-navigation still seems to 'fill' the intermediate screens in the stack. This is a problem because these screens may require certain paramters that are not provided without direct navigation.

export const ExampleRouter = createStackNavigator({
    A: { screen: A },
    B: { screen: B },
    C: { screen: C },
    D: { screen: D },
}, {
    lazy: true,
})

Once the navigator is loaded, if I navigate directly to screen, D screens B and C are mounted automatically. There should be a way to mount only the screen being navigated to.

**Comment by satya164** [comment]
Screens are rendered when they come into the viewport. This is expected.

> Boolean indicating whether to lazily render the scenes. When this is set to true, screens will be rendered as they come into the viewport.
