### ISSUE TITLE
bundling failed: Error: Unable to resolve module ` react-native-screens` from `node_modules/react-navigation-tabs/src/navigators/createBottomTabNavigator.js`

### ISSUE THREAD

**Issue by aujisti-ador** [react-navigation/react-navigation#6594]
**Current Behavior**

- After executing app is not installing reporting
```
bundling failed: Error: Unable to resolve module `
react-native-screens` from `node_modules/react-navigation-tabs/src/navigators/createBottomTabNavigator.js`: react-native-screens could not be found within the project.
```

**Your Environment**

| software         | version |
| ---------------- | ------- |
| react-navigation | 3.11.1
| react-native     | 0.61.2
| node             | 12.13.0

**Comment by aujisti-ador** [comment]
well i have solved this by reinstalling / updating these packages.
`npm install --save react-native-gesture-handler react-native-reanimated react-native-screens`

**Comment by DEV-Ahmedbakr** [comment]
Performing npm start -- --reset-cache on its own did not do the trick for me.

But performing the following did succeed:

Delete node_modules & package-lock.json
Delete app from phone
run npm start -- --reset-cache
run app

**Comment by frknbltci** [comment]
npm add react-navigation-material-bottom-tabs react-native-paper

**Comment by Rusulan** [comment]
Mr. Rabbi.
thanks

**Comment by aravi365** [comment]
all these ended up in **Nativemodule cannot be null** error for me !

**Comment by Pagebakers** [comment]
Make sure to link the packages, in case auto linking doesnt work with your project

**Comment by aujisti-ador** [comment]
> Mr. Rabbi.
> My project and others is well working according your solution.
> thanks

Thank you, Pleasure.

**Comment by Snooze-Button** [comment]
> run npm start -- --reset-cache

my terminal says it doesnt recogise --reset-cache

**Comment by Jedi0098** [comment]
expo install react-native-gesture-handler react-native-reanimated react-native-screens react-native-safe-area-context @react-native-community/masked-view
if you use Expo

**Comment by arslan121472** [comment]
error: Error: Unable to resolve module ../..screens from H:\react native\online-learning-app\screens\Dashboard\MainLayout.js:

None of these files exist:
  * screens\..screens(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  * screens\..screens\index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)

**Comment by arslan121472** [comment]
i got the following error please resolve it
