### ISSUE TITLE
White background on iOS13 modal style in Native Stack, when it should be black?

### ISSUE THREAD

**Issue by stevelizcano** [react-navigation/react-navigation#6735]
**Current Behavior**

- What code are you running and what is happening?
I'm running latest V5 Native Stack Navigator with a switch statement. After login, I have a modal that appears. The background of the modal is white, and all subsequent modals have a white background.

On another app I've used with V5, it's always a black background, and within iOS13, it's always black.

I also tried a suggestion for a similar issue here, to no avail: https://github.com/react-navigation/react-navigation/issues/325#issuecomment-583128362

- Include a screenshot or video if it makes sense.:

![Simulator Screen Shot - iPhone 11 - 2020-02-07 at 12 54 12](https://user-images.githubusercontent.com/25097587/74027849-4a1df780-49a9-11ea-85a5-2c0d61ce7f8a.png)

**Expected Behavior**

- What do you expect should be happening?
Background should be black, as seen here: 

![Simulator Screen Shot - iPhone 11 - 2020-02-07 at 12 57 32](https://user-images.githubusercontent.com/25097587/74027902-69b52000-49a9-11ea-9ab2-fb2c1ecf157c.png)

- Include a screenshot or video if it makes sense.

Included above

**How to reproduce**

`    <Stack.Navigator
      screenOptions={{
        headerShown: false,
        gestureEnabled: true,
        ...TransitionPresets.ModalPresentationIOS,
      }}
      // mode="modal"
    >
      {isAuthenticated ? (
        <Stack.Screen
          name="AppDrawer"
          options={{
            headerShown: false,

            contentStyle: { backgroundColor: "blue" },
          }}
          component={AppDrawer}

        />
      ) : (
        <Stack.Screen
          name="LandingScreen"
          component={AuthScreen}
          options={{
            title: "HIV Antiretrovirals",
            headerTranslucent: true,
            headerShown: false,

          }}
        />
      )}
    </Stack.Navigator>`

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | 13.3
| @react-navigation/native       | 5.0
| @react-navigation/native-stack | 5.0
| react-native-screens           | 2.0.0-beta.2
| react-native                   |  0.61
| expo                           | SDK36
| node                           |  v12.13.1
| npm or yarn                    | yarn

**Comment by stevelizcano** [comment]
To add, I checked with the expo team to make sure that the RootView of an ejected ExpoKit app is set to Black, or can be set to black. They're checked it on their end that it is working correctly for an ExpoKit app.

**Comment by dsolimando** [comment]
It's not related to react-navigation. It's because Expo is setting window.background to UIColor.white ([see here)](https://github.com/expo/expo/blob/bd7bc03ee10d89487eac25351a455bd9db155b8c/ios/Exponent/ExpoKit/EXStandaloneAppDelegate.m).
Setting that value is the way to control background color of modals in ios13 ([see](https://stackoverflow.com/questions/58119078/how-to-change-background-color-of-modal-presentation-ios13)).

**Comment by stevelizcano** [comment]
Correct, that worked. Thanks, and closing issue. 

I'll let the Expo team know.

**Comment by garrytaulu** [comment]
Any news from the expo team on how we can set this without ejecting? Thanks.
