### ISSUE TITLE
Drawer navigator opens in android with swipe gesture with default values.

### ISSUE THREAD

**Issue by raajnadar** [react-navigation/react-navigation#6736]
**Current Behavior**

Docs states that

> gestureEnabled
> 
> Whether you can use gestures to open or close the drawer. Defaults to true on iOS, false on Android.

https://reactnavigation.org/docs/en/drawer-navigator.html#gestureenabled

But the default behavior in android is enabled i.e. `gestureEnabled: true`

**Expected Behavior**

The drawer should not open with gesture in android if `gestureEnabled` is not set to true.

**How to reproduce**

https://snack.expo.io/@raajnadar/drawer-gesture-enabled-by-default-in-android

Open the snack and try to open the drawer with swipe gesture the drawer will open in android with default config.

**Your Environment**

Versions from the snack, I am using latest in my project.

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | N/A - 10
| @react-navigation/native       | 5.0.0
| @react-navigation/drawer       | 5.0.0
| react-native-reanimated        | 1.0.0
| react-native-gesture-handler   | 1.0.0
| react-native-safe-area-context | 0.6.0
| react-native-screens           | 2.0.0-alpha.33
| react-native                   | 0.61
| expo                           | 36
| node                           | 10
| npm or yarn                    | 1.21

**Comment by osdnk** [comment]
Sorry, it was bug in docs! Fixed
