### ISSUE TITLE
Ensure that paths are not included in bundles

### ISSUE THREAD

**Issue by brentvatne** [react-navigation/react-navigation#6737]
Unsure what is causing paths like `/Users/satya/Workspace/Callstack/react-navigation-core/src/views/withNavigation.js` to appear in bundles but we should investigate and fix it :) Possibly `tsc`?

**Comment by empyrical** [comment]
The babel plugin [babel-plugin-transform-react-jsx-source](https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-react-jsx-source) is doing this. 

This plugin looks to be enabled by the babel react preset when you enable compiling builds in `development`:

https://babeljs.io/docs/en/babel-preset-react

You can see the `__jsxFilename` variable containing paths in the `lib/commonjs` folder in the builds sent to NPM:

https://registry.npmjs.org/react-native-tab-view-viewpager-adapter/-/react-native-tab-view-viewpager-adapter-1.0.7.tgz

**Comment by satya164** [comment]
Should be fixed with latest version of bob.
