### ISSUE TITLE
[V5] Header disappears when switching to createDrawerNavigator

### ISSUE THREAD

**Issue by tsvetann** [react-navigation/react-navigation#6739]
The default header missing (both IOS and Android) when i switch to createDrawerNavigator

```javascript
const App: () => React$Node = () => {
  return (
    <NavigationContainer>
      <Drawer.Navigator
        initialRouteName="Home"
        screenOptions={{
          headerTintColor: 'red',
          headerStyle: {backgroundColor: 'tomato'},
        }}>
        <Drawer.Screen name="Home" component={HomeScreen} />
        <Drawer.Screen name="Details" component={DetailsScreen} />
      </Drawer.Navigator>
    </NavigationContainer>
  );
};
```

Is this expected or am I missing something.

Context:
```javascript
"dependencies": {
    "@react-native-community/masked-view": "^0.1.6",
    "@react-navigation/drawer": "^5.0.0",
    "@react-navigation/native": "^5.0.0",
    "@react-navigation/stack": "^5.0.0",
    "react": "16.9.0",
    "react-native": "0.61.5",
    "react-native-gesture-handler": "^1.5.6",
    "react-native-reanimated": "^1.7.0",
    "react-native-safe-area-context": "^0.6.4",
    "react-native-screens": "^2.0.0-beta.2"
  },
```

**Comment by satya164** [comment]
Drawer navigator doesn't provide a header. You need to use a custom header not stack navigator nested in drawer to provide a header.

**Comment by martinjohnlopez8** [comment]
I can't find a custom header in the API Reference for drawer. https://reactnavigation.org/docs/en/drawer-navigator.html.

**Comment by chj-damon** [comment]
> Drawer navigator doesn't provide a header. You need to use a custom header not stack navigator nested in drawer to provide a header.

how?

**Comment by martinjohnlopez8** [comment]
> > Drawer navigator doesn't provide a header. You need to use a custom header not stack navigator nested in drawer to provide a header.
> 
> how?

You need to have the Stack as the child of your Drawer.

`
      <Drawer.Navigator >
        <Drawer.Screen 
          name="Dashboard" 
          component={StackComponent} 
        /> 
      </Drawer.Navigator>
`

**Comment by chj-damon** [comment]
@martinjohnlopez8 thanks, I'll try this.
