### ISSUE TITLE
[iOS] BottomTabNavigator keyboardHidesTabBar bug

### ISSUE THREAD

**Issue by palmtrae** [react-navigation/react-navigation#6740]
**Current Behavior**

- When setting `tabBarOptions.keyboardHidesTabBar` to `true` it sometimes causes the TabBar to drop down ~50pts. This isn't always the case when running in the simulator, but if you toggle it between false and true while hot-reloading it will show up. Also when compiling the application in `release`-mode, it will show up every time until you display and dismiss the keyboard.

**How to reproduce**

- Toggle `keyboardHidesTabBar` from `false` to `true` while running in the simulator.

![BottomTabNavigatorBug](https://user-images.githubusercontent.com/461914/73928778-f7bed700-48d3-11ea-9fb5-ee556c5c38a0.gif)

**Example code**  

This bug is also reproducible on the iOS simulator on snack: https://snack.expo.io/ByKcuDYMI

```javascript
import React from 'react';
import { View, Text } from 'react-native';
import { NavigationContainer } from '@react-navigation/native';
import { createBottomTabNavigator } from '@react-navigation/bottom-tabs';

const Tab = createBottomTabNavigator();

const HomeScreen = () => {
  return (
    <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
      <Text>Home!</Text>
    </View>
  );
};

const SettingsScreen = () => {
  return (
    <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
      <Text>Settings!</Text>
    </View>
  );
};

const Tabs = () => {
  return (
    <Tab.Navigator
      tabBarOptions={{
        activeTintColor: '#FFF',
        inactiveTintColor: '#AAA',
        keyboardHidesTabBar: true,
        style: {
          backgroundColor: '#00220a',
        },
      }}>
      <Tab.Screen name="Home" component={HomeScreen} />
      <Tab.Screen name="Settings" component={SettingsScreen} />
    </Tab.Navigator>
  );
};

const App: () => React$Node = () => {
  return (
    <NavigationContainer>
      <Tabs />
    </NavigationContainer>
  );
};

export default App;
```
**Your Environment**

| software                      | version |
| ----------------------------- | ------- |
| iOS                           | 13.0    |
| @react-navigation/native      | ^5.0.0  |
| @react-navigation/bottom-tabs | ^5.0.0  |
| react-native-screens          | ^2.0.0-beta.2  |
| react-native                  | ^0.61.5 |

**Comment by davidgovea** [comment]
@palmtrae try upgrading to ``5.0.2`. The snack is fixed after upgrading https://snack.expo.io/@runtrizapps/createbottomtabnavigator-·-react-navigation
