### ISSUE TITLE
How to use useNavigation() within @react-navigation drawer?

### ISSUE THREAD

**Issue by kopax** [react-navigation/react-navigation#6741]
**Current Behavior**

I have a react-native application that use [`react-navigation`](https://reactnavigation.org/) v5 for the routing.

1. I have a drawer (offeset menu left) in all my views
1. I use the stackNavigation for page transition.

Because of *(1)*, my structure is `drawerNavigator (a) > stackNavigator (b) > views (c)`.

When I try to call the `useNavigation()` hook, I have the following error: 

```
Error: We couldn't find a navigation object. Is your component inside a navigator?
    at useNavigation (bundle.js:8766)
```

Yes, I am not inside the `stackNavigator` so the hook cannot be called

**Expected Behavior**

I expect to have navigation available in my drawer.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | iOS, Android and web
| @react-navigation/native       | 5.0.0-alpha.41
| @react-navigation/stack         | 5.0.0-alpha.63
| @react-navigation/drawer       | 5.0.0-alpha.41
| react-native-reanimated        | 1.4.0
| react-native-gesture-handler   | 1.5.3
| react-native-safe-area-context | 0.6.2
| react-native-screens           | 2.0.0-alpha.32
| react-native                   | https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz
| expo                           | SDK36
| node                           | v13.5.0
| npm or yarn                    | 6.13.7

How can I use [`@react-navigation/stack`](https://github.com/react-navigation/react-navigation/tree/master/packages/stack) inside [`@react-navigation/drawer`](https://github.com/react-navigation/react-navigation/tree/master/packages/drawer) or how should I build my drawer and app with them?

**Comment by Epick362** [comment]
I am encountering the same issue. It seems the drawerContent calls `useNavigation` hook even though it shouldn't have to and fails.

Commenting out 
```
if (navigation === undefined) {
    throw new Error(
      "Couldn't find a navigation object. Is your component inside a screen in a navigator?"
    );
  }
``` 
in `@react-navigation/core/src/useNavigation.tsx` fixes the crash and navigation prop in the drawer is still defined and working.

**Comment by kopax** [comment]
This still cause me a lot of trouble and a degraded navigation api accross my application. Is there any plan for this please ?..

**Comment by satya164** [comment]
The `navigation` prop received by screen and drawer content are very different. `useNavigation` gives you `navigation` prop of the screen and is only supported inside screens. 

Please use the `navigation` prop inside the drawer content.

**Comment by kopax** [comment]
@satya164 this was impossible to me because of the web requirements.

My target are web/ios/native , as every website which respect it-self, we needed to have location history. 

My application is not using `react-navigation` api directly, instead I wrapped it, and depending on the environment (single page app/progressive web app/native app), I use `react-router` for the first and  `react-navigation` for the last two.

This required me to have a global and standard way to access `navigation` in any components to fits all use cases by knowing the constraints of both.

I finally ended up having hard issue just with `react-navigation` and the `navigation` props I am using is the one I got from the `ref` strategy.


Since I started ith RN4/RN5, I got contacted quite a few times directly regarding my issue and prefered solution and I can say now @satya164 that my use case is not that uncommon, and toughs should be open to discussion until it got resolved (if it can)

**Comment by chaiiplss** [comment]
Anyone found any permanent solution to this?

**Comment by kopax** [comment]
No

**Comment by amanjareck** [comment]
So I guess we need to create a navigation reference, similar to the doc here

https://reactnavigation.org/docs/navigating-without-navigation-prop/

**Comment by kopax** [comment]
That's what I did and its far from ideal. You won't have access to many features, you won't be able to access the current navigation stack and current route.

**Comment by amanjareck** [comment]
I just needed to navigate to a screen so it worked for me. Took me some time to figure out, Hope it was easier for components not part of Screen components
