### ISSUE TITLE
Trying to make a scrollable nested navigator with a custom header

### ISSUE THREAD

**Issue by rolivegab** [react-navigation/react-navigation#6742]
**Current Behavior**

- What code are you running and what is happening?
```tsx
const { Navigator, Screen } = CadastroStackNavigator;

const CadastroRoutes = () => (
  <ScrollView
    contentContainerStyle={{
      minHeight: '100%',
    }}
  >
    <Text>A *NOT* FIXED CUSTOM HEADER. WHEN USER SCROLLS TO BOTTOM, THIS NEEDS TO DISAPPEAR AT TOP OF SCREEN</Text>
    <View
      style={{
        flexGrow: 1,
      }}
    >
      <Navigator {...{ screenOptions }}>
        <Screen
          name="Test"
        >
          {() => (
            <View>
              {[...new Array(50)].map((i, index) => (
                <Text key={index}>
                  {`hi ${index}`}
                </Text>
              ))}
            </View>
          )}
        </Screen>
      </Navigator>
    </View>
  </ScrollView>
);
```

- Include a screenshot or video if it makes sense.
![image](https://user-images.githubusercontent.com/7359906/73885815-33f82600-4847-11ea-990f-306f0c6d7eeb.png)

**Expected Behavior**

- What do you expect should be happening?
I want the previous code to scroll, and behave like when i remove Navigator and Screen in the end of this video: https://www.youtube.com/watch?v=Cvge4lTdkG0
Without removing then, the content doesn't scroll.

I think that the problem is to have a screen with a height equal to its content height. But I couldn't make it to happen.

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Android
| @react-navigation/native       | 5.0.0
| @react-navigation/stack        | 5.0.0
| react-native-gesture-handler   | latest stable
| react-native-safe-area-context | latest stable
| react-native-screens           | 1.5.6
| react-native                   | 0.61.5
| expo                           | not using expo
| node                           | 12-stable
| npm or yarn                    | npm 6.13.4

**Comment by satya164** [comment]
Navigators are not supposed to be inside a ScrollView. Your content needs to be in scroll view inside your screens, not the whole navigator.

Closing since this is not a valid use case.
