### ISSUE TITLE
Replacing Screen from nested Screen  of another stack.

### ISSUE THREAD

**Issue by AlexSmirnov9107** [react-navigation/react-navigation#6743]
**Current Behavior**
Following with "auth flow", if i replace screen from nested screen in stack, screen is getting pop instead of push

1. Welcome
    1.1 LoginScreen
2. PolicyScreen

Full routing path is 
Welcome screen -> Login Screen -> PolicyScreen

- What code are you running and what is happening?
- Include a screenshot or video if it makes sense.

**Expected Behavior**

- What do you expect should be happening?
This should be a push action
- Include a screenshot or video if it makes sense.

**Comment by satya164** [comment]
https://reactnavigation.org/docs/en/stack-navigator.html#animationtypeforreplace
