### ISSUE TITLE
Stack Navigator navigates to the previous screen on 'fast-swipe'

### ISSUE THREAD

**Issue by enheit** [react-navigation/react-navigation#6747]
**Current Behavior**

1. Create Login page (Stack)
2. Create Home page (Stack)
3. Navigate to the Home page using Button (everything is okay)
4. Navigate back to the previous screen by using swipe (do it fast)

[react-navigation-stack-issue (video).zip](https://github.com/react-navigation/navigation-ex/files/4150855/react-navigation-stack-issue.video.zip)

Router navigates back to the Home screen after showing Login screen.

**Expected Behavior**

Router should navigate to the Login screen and do not navigate back to the Home screen.

**How to reproduce**

Do fast swipes between Stack Navigation screens

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | iOS
| @react-navigation/native       | ^5.0.0-alpha.33
| @react-navigation/stack        | next
| react-native-gesture-handler   | ^1.5.6
| react-native-safe-area-context | ^0.6.4
| react-native-screens           | ^2.0.0-alpha.12
| react-native                   | ~0.61.4
| expo                           | ~36.0.0
| node                           | v12.14.1
| npm or yarn                    | 6.13.4

**Comment by satya164** [comment]
You're on a very old version. Please upgrade and open a new issue if it's still a problem

**Comment by llauderesv** [comment]
Hi,

I'm experiencing the issue in react-navigation 4.0. Is there any way to resolve this problem without updating to the latest version?

Thanks!
