### ISSUE TITLE
focus listener called twice when navigating to screens in different navigators 

### ISSUE THREAD

**Issue by ravirajn22** [react-navigation/react-navigation#6749]
When trying to navigate using navigation.navigate('MainScreen', {screen: 'SubScreen'})}, the 'SubScreen' focus listener is called twice. This happens in the below navigation structure. The first time it will be called only ones but the next time you navigate using the above method it will be called twice.

- BottomTabNavigator
     - TabScreen1 (Issue happens while Navigate to TopTabScreen1 and TopTabScreen2 from this screen)
     - TopTabNavigator
                 - TopTabScreen1 (focus listener called twice)
                  - TopTabScreen2 (focus listener called twice)

Project to reproduce the bug,
https://github.com/ravirajn22/reactnavigationexFocusBug

Below is the sample code to reproduce,

```
function Dashboard(props) {
  return(
    <View>
      <Text>Dashboard Screen</Text>
      <Button 
        title='go to my events' 
        onPress={() => props.navigation.navigate('Events', {screen: 'Myevent'})} 
      />
      <Button 
        title='go to all events' 
        onPress={() => props.navigation.navigate('Events', {screen: 'Allevent'} )}
      />
    </View>
  )
}

class Myevent extends React.Component {

  componentDidMount() {
    this.unsubscribe = this.props.navigation.addListener('focus', () => {
      // Will be called twice when navigated from dashboard buttons
      console.warn('Myevent focus');
    });
  }

  componentWillUnmount() {
    this.unsubscribe();
  }

  render() {
    return (
      <View>
        <Text>Myevent</Text>
      </View>
    );
  }
}

class Allevent extends React.Component {

  componentDidMount() {
    this.unsubscribe = this.props.navigation.addListener('focus', () => {
      // Will be called twice when navigated from dashboard buttons
      console.warn('Allevent focus');
    });
  }

  componentWillUnmount() {
    this.unsubscribe();
  }

  render() {
    return(
      <View>
        <Text>Allevent</Text>
      </View>
    );
  }
}

function EventsTab() {
  return(
    <TopTab.Navigator>
      <TopTab.Screen name='Myevent' component={Myevent} />
      <TopTab.Screen name='Allevent' component={Allevent} />
    </TopTab.Navigator>
  );
}


const App = () => {
  return (
    <View style={{paddingTop: 80, flex: 1}} >
      <StatusBar barStyle="dark-content" />
      <NavigationNativeContainer>
        <BottomTab.Navigator>
          <BottomTab.Screen name='Dashboard' component={Dashboard} />
          <BottomTab.Screen name='Events' component={EventsTab} />
        </BottomTab.Navigator>
      </NavigationNativeContainer>
    </View>
  );
};


export default App;
```

Pls comment if you are unable to reproduce.

Thanks.

**Comment by ravirajn22** [comment]
I looked at the src code but couldn't find the origin of the issue. There are so many wrapper components in addition to usage of context, so I was not able to understand the structure. What is the best way to understand this library and understand its code flow. What is your suggestion? @satya164

**Comment by satya164** [comment]
This is the only relevant file for focus/blur events https://github.com/react-navigation/react-navigation/tree/master/packages/core/src/useFocusEvents.tsx

**Comment by ravirajn22** [comment]
The issue happens in nested tab navigator, for example using the below structure 

BottomTabNavigator
 -BottomTabScreen1 (Issue happens while Navigate to TopTabScreen1 and TopTabScreen2 from this screen)
 -BottomTabScreen2 (TopTabNavigator)
  - ChildTabScreen1 (focus listener called twice)
  - ChildTabScreen2 (focus listener called twice)

Say I have already visited all the screens and navigate to `BottomTabScreen1` from `ChildTabScreen1`.

Now from `BottomTabScreen1` call `navigation.navigate('BottomTabScreen2', {screen: 'ChildTabScreen2'})}.` The `focus` listener inside `ChildTabScreen2` will be called twice.

This happens due to,

https://github.com/react-navigation/react-navigation/blob/86c39d2e0ec5b864419b3850d1ac0e1a55ec3007/packages/core/src/useFocusEvents.tsx#L20

Here we are subscribing to parent screens `focus` event and emit `focus` event to the child screen when it happens.

Also we emit `focus` event when child screen changes in this useEffect,
https://github.com/react-navigation/react-navigation/blob/86c39d2e0ec5b864419b3850d1ac0e1a55ec3007/packages/core/src/useFocusEvents.tsx#L63

By calling `navigation.navigate('BottomTabScreen2', {screen: 'ChildTabScreen2'})}` we change both the parent screen as well as the child screen, i.e 
BottomTabScreen1 to BottomTabScreen2
ChildTabScreen1 to ChildTabScreen2

Hence `focus` event for parent screen change is called which in turn fires the `focus` event for child screen `focus`. And since the child screen are themselves changing `focus` event will again be fired.

Though I was able to find the bug, but I still can't figure out the correct fix and where to apply. I think the maintainers will have better idea of solving the problem in more natural way.

**Comment by AdamPanag** [comment]
@ravirajn22 Any updates on this issue? I have the same problem when I navigate from a `TabScreen` to a `StackScreen` and then go back. When i return to the `TabScreen`, it renders 2 times.

**Comment by dewey4iv** [comment]
I'm also have the same issue @AdamPanag . It's a shame because we are trying to use this to power some metrics/analytics and it's all over the place.

**Comment by MUHAMMAD-ATEEK** [comment]
same issue here

**Comment by thexdd** [comment]
Any solution yet?

**Comment by kg-currenxie** [comment]
Same issue here
