### ISSUE TITLE
`headerLargeTitleStyle` isn't accepting any Expo fonts

### ISSUE THREAD

**Issue by iDuuck** [react-navigation/react-navigation#6750]
**Current Behavior**

When I am trying to include a custom font into Expo, I am not able to use it using the native stack navigators `fontFamily` attributes. It keeps the SF Font.

**Expected Behavior**

I want the font to be the right one actually.

**How to reproduce**

Implement a custom font into an Expo project and try to use the font for any of the title styles.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | iOS
| @react-navigation/native       | next
| @react-navigation/native-stack | ^5.0.0-alpha.29
| react-native-screens           | ^5.0.0-alpha.29
| react-native                   | https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz
| expo                           | 36
| node                           | v12.8.0
| npm or yarn                    | 1.19.2

**Comment by Derewith** [comment]
Any news?

**Comment by iDuuck** [comment]
This is working for me on a *non-expo* app.

**Comment by louischeminant** [comment]
Same issue for me, not loading any Expo font on `headerLargeTitleStyle` or `headerTitleStyle`

**Comment by satya164** [comment]
Hey, native-stack has been moved to [software-mansion/react-native-screens](https://github.com/software-mansion/react-native-screens). Please track the issue here: https://github.com/software-mansion/react-native-screens/issues/371
