### ISSUE TITLE
headerLargeTitle exposes white background on navigation.

### ISSUE THREAD

**Issue by evanheckert** [react-navigation/react-navigation#6751]
**Current Behavior**

![demo-gif](https://user-images.githubusercontent.com/5625859/73494562-55a26a80-437a-11ea-904d-38376df88771.gif)

Gif was recorded with slow animations enabled in the iOS simulator (ios 13.3). Symptoms are the same when running on iPhone 11 Pro Max through expo client.

**Expected Behavior**
I would expect either the headerStyle or contentStyle backgroundColor to be the background color throughout the transition.  

**How to reproduce**
Repro: https://github.com/evanheckert/header-example

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | iOS 13.3 and 13.3.1
| @react-navigation/native       | 5.0.0-alpha.29
| @react-navigation/native-stack | 5.0.0-alpha.29
| react-native-screens           | 2.0.0-alpha.12
| react-native                   | latest expo fork, sdk-36.0.1
| expo                           | 36.0.2
| node                           | 10.17.0
| npm or yarn                    | yarn v1.21.1

**Comment by satya164** [comment]
Hey, native-stack has been moved to [software-mansion/react-native-screens](https://github.com/software-mansion/react-native-screens). Please track the issue here: https://github.com/software-mansion/react-native-screens/issues/370
