### ISSUE TITLE
App is crashing while Tab having more than 6 menu item

### ISSUE THREAD

**Issue by desis123** [react-navigation/react-navigation#6752]
**Current Behavior**

I have a @react-navigation/material-top-tabs nested with @react-navigation/native-stack  Code is following 

 ```
const Tab = createMaterialTopTabNavigator();

const Tabnav = ()=> {

return(
  <Tab.Navigator
      initialRouteName="Home"
      tabBarOptions={{
        activeTintColor: '#e91e63',
        scrollEnabled:true,  
      }}
      lazy={true}
      lazyPreloadDistance = {1}
 
    > 
        
               <Tab.Screen name="Home" component={Home} />
        
                {c.CATEGORIES_BN_NAME.map((item, key) => {
         return (
          <Tab.Screen name={c.CATEGORIES_NAME[key]} key={key} component={Categories} />
         );
      })} 

            

            
        
 </Tab.Navigator>
  )
```

```
 const Stack = createNativeStackNavigator();

function Stacknav() {

  

    return (
      <Stack.Navigator>
        <Stack.Screen name="HomeStack" component={Tabnav} />
        <Stack.Screen name="Articles" 
        component={Articles}
       
        />
     
      </Stack.Navigator>
    );


  <NavigationNativeContainer initialState={initialState} ref={ref}>
    <Stacknav />
   </NavigationNativeContainer>

```
**Expected Behavior**

Everything is working fine. until CATEGORIES_BN_NAME array having less than 5 items, but while it's more than 5-7 items , app  is crashing randomly ... and if app does not crash, it loads extremely slow.

**How to reproduce**

- You must provide a way to reproduce the problem. If you are having an issue with your machine or build tools, the issue belongs on another repository as that is outside of the scope of React Navigation.
- Either re-create the bug on [Snack](https://snack.expo.io) or link to a GitHub repository with code that reproduces the bug.
- Explain how to run the example app and any steps that we need to take to reproduce the issue from the example app.
- Keep the repro code as simple as possible, with the minimum amount of code required to repro the issue.
- Before reporting an issue, make sure you are on latest version of the package.

**Your Environment**

| software                            | version |
| ----------------------------------- | ------- |
| iOS or Android                      |
| @react-navigation/native            |
| @react-navigation/material-top-tabs |
| react-native-tab-view               |
| react-native                        |
| node                                |
| npm or yarn                         |

**Comment by satya164** [comment]
Closing due to no response.
