### ISSUE TITLE
Unable to "hide" item from drawer

### ISSUE THREAD

**Issue by Elias-Graf** [react-navigation/react-navigation#6753]
Previously you were able to remove an item from the drawer by setting the label to: `() => null` now there is some wrapper that causes space to show up, which is also clickable.

**Current Behavior**
`DrawerItem` still shows
**Expected Behavior**
`DrawerItem` should not show **OR** provide an option to disable a certain item. E.g.:
```
navigation.setOptions({
    label: () => null, // Old method
    showInDrawer: false // potential new method
});
```

if you want to keep the old method you could simply add the line
```
  if (typeof label === 'function' && (label as () => React.ReactElement)() === null) return null;
```

in https://github.com/react-navigation/navigation-ex/blob/fa4a959549ccd9dc2f9bd2ea495e99abdedc9f94/packages/drawer/src/views/DrawerItem.tsx#L96

@react-navigation/drawer: ^5.0.0-alpha.41

Cheers!

**Comment by nizarl** [comment]
Please add this easy declarative way to hide label.

**Comment by pendalph** [comment]
Does anyone have a solution to this problem?

**Comment by franciscailleAstus** [comment]
Same issue here !

**Comment by franciscailleAstus** [comment]
In the meantime, I found this ugly workaroud
![image](https://user-images.githubusercontent.com/44379473/74865007-74af6f00-531e-11ea-97ca-31904a7eb341.png)

**Comment by savio777** [comment]
> In the meantime, I found this ugly workaroud
> ![image](https://user-images.githubusercontent.com/44379473/74865047-86911200-531e-11ea-9499-12c5dc9f2561.png)

Work, thank you.

**Comment by Elias-Graf** [comment]
@satya164 Is this really a `feature-request` if it used to work?

**Comment by Fallup** [comment]
I couldn't find the feature request in the Canny, so I created one https://react-navigation.canny.io/feature-requests/p/add-option-to-hide-item-from-a-drawer

**Comment by spalmer** [comment]
FWIW, another solution that finally worked for me is to just create your own DrawerItemList component and use that instead. Basically just copy/paste the React Navigation component and add some conditional logic to not render the DrawerItem at all unless there's a label.

(I also stripped out the TS stuff since my project is just JS)

```
/* Overrides React Navigation's DrawerItemList to completely hide items with no label
=============================== */

import * as React from 'react';
import { View } from 'react-native'
import { CommonActions } from '@react-navigation/native';
import { DrawerActions } from '@react-navigation/routers';
import { DrawerItem } from '@react-navigation/drawer';

/**
 * Component that renders the navigation list in the drawer.
 */
export default function AppDrawerItemList({
  state,
  navigation,
  descriptors,
  activeTintColor,
  inactiveTintColor,
  activeBackgroundColor,
  inactiveBackgroundColor,
  itemStyle,
  labelStyle,
}) {
  return (state.routes.map((route, i) => {
    const focused = i === state.index;
    const { title, drawerLabel, drawerIcon } = descriptors[route.key].options;

    return (
      <View key={route.key}>
        { typeof drawerLabel === 'string' && <DrawerItem
          label={
            drawerLabel !== undefined
              ? drawerLabel
              : title !== undefined
              ? title
              : route.name
          }
          icon={drawerIcon}
          focused={focused}
          activeTintColor={activeTintColor}
          inactiveTintColor={inactiveTintColor}
          activeBackgroundColor={activeBackgroundColor}
          inactiveBackgroundColor={inactiveBackgroundColor}
          labelStyle={labelStyle}
          style={itemStyle}
          onPress={() => {
            navigation.dispatch({
              ...(focused
                ? DrawerActions.closeDrawer()
                : CommonActions.navigate(route.name)),
              target: state.key,
            });
          }}
        />}
      </View>
    );
  }));
}
```
