### ISSUE TITLE
Native animation (Large title) isn't scrolling properly

### ISSUE THREAD

**Issue by iDuuck** [react-navigation/react-navigation#6754]
**Current Behavior**

When scrolling through the screens in my example (see "How to reproduce"), the large title bar is bouncing. I am not sure on how to **properly** recreate the issue, because it sometimes happens with `ScrollView`, and sometimes it is happening with `FlatList`, but you can check out the example.

For me personally, the `ScrollView` on the `Home` component, isn't scrolling properly, since the title bar scrolls away faster, than the actual scroll momentum.

**Additionally:** Don't know, if I should create a new issue for this one, but I am sure, that there is a scrolling behavior, if the large title is scrolled to the half, that it bounces back to the nearest position (small title, or full large title – not cutted large title).

**Expected Behavior**

I expect it to function (scroll) properly.

**How to reproduce**

https://snack.expo.io/r1UIKryGI

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | iOS | 
| @react-navigation/native       | ^5.0.0-alpha.29 | 
| @react-navigation/native-stack | ^5.0.0-alpha.29 |
| react-native-screens           | 2.0.0-alpha.12 |
| react-native                   | https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz |
| expo                           | 36.0.0 |
| node                           | v12.8.0 |
| npm or yarn                    | 1.19.2 |

**Comment by satya164** [comment]
Hey, native-stack has been moved to [software-mansion/react-native-screens](https://github.com/software-mansion/react-native-screens). Please track the issue here: https://github.com/software-mansion/react-native-screens/issues/369
