### ISSUE TITLE
No way to listen to `tabPress` event outside of Tab.Navigator.

### ISSUE THREAD

**Issue by Trancever** [react-navigation/react-navigation#6756]
**Current Behavior**

There is no way to set `tabPress` listener in a component that is not a Tab.Screen or its child.

**Expected Behavior**

There should be a way to listen to `tabPress` event globally and not only in TabNavigator's child components.

**Use case**

I want to render a FAB button that is visible in all Tab.Navigator Tabs and I want to change its appearance depending on currently active tab.

To make FAB component visible in all tabs I render it as a Tab.Navigator sibling. Since I can only set `tabPress` listener inside Tab.Navigator screen currently, I have to pass a callback to each Tab.Navigator screen to know if it was pressed. It would be handy to be able to set a `tabPress` listener outside of Tab.Navigator that would tell me which tab was just pressed.

**Your Environment**

| software                      | version |
| ----------------------------- | ------- |
| @react-navigation/native      | 5.0.0-alpha.27
| @react-navigation/bottom-tabs |5.0.0-alpha.34

**Comment by markmssd** [comment]
100% agree! We can wrap it with a 

```
<NavigationContainer onStateChange={console.log}>
    <Tab.Navigator>
        ...Tabs
    </Tab.Navigator>
</NavigationContainer>
```

But then we can't nest <NavigationContainer> as it errs out.

**Comment by markmssd** [comment]
Another way to do it would be to have your own custom `tabBar` (https://reactnavigation.org/docs/en/bottom-tab-navigator.html#tabbar) , but it's pretty overkill solution for something that should be exposed. I'd be glad to open a PR if needed.
