### ISSUE TITLE
Web: Drawer snaps open when swiping on a tab navigator

### ISSUE THREAD

**Issue by EvanBacon** [react-navigation/react-navigation#6758]
**Current Behavior**

- What code are you running and what is happening?
  - `expo start:web` in `/example` open the "Material Top Tabs" demo
  - click to a page that isn't the first page
  - swiping right will cause the drawer to snap open and scroll the tab navigator

**Your Environment**

- commit 179e807 (Latest on master)

**Comment by jpaas** [comment]
Same problem occurs if your screen has a list of swipeable rows. You try to swipe a row but the drawer opens.

**Comment by satya164** [comment]
Shouldn't be an issue anymore since swipe gesture is disabled in drawer on web.
