### ISSUE TITLE
Web: Tapping the drawer overlay doesn't toggle it closed

### ISSUE THREAD

**Issue by EvanBacon** [react-navigation/react-navigation#6759]
**Current Behavior**

- What code are you running and what is happening?
  - `expo start:web` in `/example`
  - open drawer by pressing menu button
  - tap content overlay component (darkened view).
  - drawer should toggle closed like it does on native but nothing happens

**Solution**

- Updating RNGH when this comes out:
  - https://github.com/software-mansion/react-native-gesture-handler/pull/921
- Updating Reanimated when this comes out (as long as nothing new breaks web):
  - https://github.com/software-mansion/react-native-reanimated/pull/547

**Your Environment**

- commit 179e807 (Latest on master)

**Comment by BernardRadman** [comment]
I am experiencing this issue on mobile also. But the funny thing is that clicking overlay toggles drawer every second time, and those second times in between it does not. I will try to reproduce this bug in snack.

My current environment:
@react-navigation/bottom-tabs: ^5.0.6,
@react-navigation/drawer: ^5.0.6,
@react-navigation/native: ^5.0.6,
@react-navigation/stack: ^5.0.6,
react-native-gesture-handler: ^1.6.0,
react-native-reanimated: ^1.7.0,
react-native-screens: ^2.0.0-beta.8

**Comment by jpaas** [comment]
Clicking the overlay closes the drawer now in v5.5.0 but swiping to open or close the drawer no longer works
