### ISSUE TITLE
Web: Drawer doesn't animate closed/opened on swipe

### ISSUE THREAD

**Issue by EvanBacon** [react-navigation/react-navigation#6760]
**Current Behavior**

- What code are you running and what is happening?
  - `expo start:web` in `/example`
  - open drawer by pressing menu button
  - drag drawer closed
  - regardless of when/where the drawer is released it'll stay where it is and not animate to a open/closed position.

**Your Environment**

- commit 179e807 (Latest on master)

**Comment by satya164** [comment]
Closing since we've removed gestures from drawer on web.
