### ISSUE TITLE
Can't navigate to nested native stack navigator from native stack navigator

### ISSUE THREAD

**Issue by foonx** [react-navigation/react-navigation#6761]
**Current Behavior**

I Currently have

- Main native stack navigator
  - Main menu screen (this is the initial route)
  - Nested native stack navigator
    - List Screen

**Expected Behavior**

I want to navigate from the main menu screen to the nested stack navigator. It works when using normal stack navigators.

**How to reproduce**

I created a [snack](https://snack.expo.io/@metec_roger/nested-navigator-problem) to reproduce the problem.
Currently it doesn't work, trying to navigate from the homescreen to the profile screen doesn't work. But if you change initial route from 'Home' to 'SubStack' on line 52, then it is possible to navigate from the sub stack to home screen and back.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |  Android 9
| @react-navigation/native       |  next
| @react-navigation/native-stack |  next
| react-native-screens           |  2.0.0-alpha.12
| react-native                   |  
| expo                           |  36
| node                           |  v10.16.2
| npm or yarn                    |  npm 6.13.6

**Comment by satya164** [comment]
Hey, native-stack has been moved to [software-mansion/react-native-screens](https://github.com/software-mansion/react-native-screens). Please track the issue here: https://github.com/software-mansion/react-native-screens/issues/368
