### ISSUE TITLE
Navigator Overdraw

### ISSUE THREAD

**Issue by jack828** [react-navigation/react-navigation#6762]
**Current Behavior**

I currently have a navigator setup like so:

```javascript
const Nav = () => (
    <Stack.Navigator
      initialRouteName="Home"
    >
      <Stack.Screen name="Home" component={HomeScreen} />
      <Stack.Screen name="Other" component={OtherScreen} />
    </Stack.Navigator>
)

const Screen = () => (<View><Text>You will see my glyph outlines</Text></View>)
```

**Expected Behavior**

I expect the screen, once navigated away, to no longer be rendered at all.
However, using the Android Layout tools and GPU Overdraw feature I can see elements are still being drawn, causing serious performance issues on lower end devices.

See below image, high levels of overdraw on any screen except home, and text outlines are visible.

![image](https://user-images.githubusercontent.com/6363719/72670549-4a744400-3a36-11ea-9ffd-c7e63d217361.png)

**How to reproduce**

This is a tricky one but you should be able to copy the above code, some basic screens (easiest to see with text), and enable the GPU overdraw feature to see what I mean.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Android
| @react-navigation/native       | 5.0.0-alpha.27
| @react-navigation/stack        | 5.0.0-alpha.61
| react-native-gesture-handler   | 1.5.3
| react-native-safe-area-context | 0.6.2
| react-native-screens           | n/a (see below)
| react-native                   | 0.61.4
| expo                           | n/a
| node                           | 10.16.3
| npm or yarn                    | ~1

I've had to remove react-native-screens from my project because of a separate issue - it was ignoring the first touch, requiring double-taps for actions to occur. I'm going to give it a go adding it back in and see if it fixes this.

**Comment by idanlevi1** [comment]
> I think the screens are kept for animations.
> [react-navigation/navigation-ex@7f963a7](https://github.com/react-navigation/navigation-ex/commit/7f963a74bb4d4b04134e917fe47e38e4d982afed)
> 
> And iirc, it only keeps adjacents screens rendered (and not the whole stack down). But I might be wrong.

That makes sense, but how can we over it?
@jack828 Maybe you solved it?

**Comment by jack828** [comment]
Hey @idanlevi1, I believe this issue is pretty much resolved with v5 of react-navigation and the latest react-native-screens. I _think_ I still experience a touch delay after transitions, but if so it is small enough for me not to worry about.

I think this issue can be closed if all are happy with the usage of react-native-screens as a fix for this issue.

**Comment by idanlevi1** [comment]
> Hey @idanlevi1, I believe this issue is pretty much resolved with v5 of react-navigation and the latest react-native-screens. I _think_ I still experience a touch delay after transitions, but if so it is small enough for me not to worry about.
> 
> I think this issue can be closed if all are happy with the usage of react-native-screens as a fix for this issue.

I work with 4.4.0 version and it's too many changes to upgrade version to 5
my `react-native-screens` version in my project is 2.9.0 and is still slow and too much overdraw
do you have any advice?

**Comment by jack828** [comment]
Sure, as eluded to me by another user that emailed me directly (if you're watching Hasan, please comment!) a possible fix for this is to identify where background colours are being unecessarily drawn - for example, if you have a tab navigator within a stack navigator, it will be drawing two backgrounds - one per navigator.

You'll need to test this by setting the styles to `{ backgroundColor: 'transparent' }` or `{ backgroundColor: null }`.

I'm still in the process of trying to find an Android/iOS way of setting a global app background colour, to entirely remove the overdraw.

**Comment by henrikra** [comment]
Is this problem fixed?

**Comment by idanlevi1** [comment]
> Is this problem fixed?

It removes only one layer

**Comment by jack828** [comment]
> I'm still in the process of trying to find an Android/iOS way of setting a global app background colour, to entirely remove the overdraw.

I fixed this by setting the theme on react-navigation to my app theme (handled by react-native-paper)
```jsx
const theme = {
  background: secondary,
  card: secondary,
  text: '#000000',
  border: secondary
}

<NavigationContainer theme={theme} >
  {children}
</NavigationContainer>
```

With this change, you should be ale to remove all backgrounds for navigators/screens to significantly reduce overdraw.

As my original issue is fixed by upgrading to v5 and latest react-native-screens, I am going to close this issue. If you need to, please open a **new** issue with a reproducible scenario.
