### ISSUE TITLE
White flash on the app header with dark colored backgrounds (iOS)

### ISSUE THREAD

**Issue by samparhizkar** [react-navigation/react-navigation#6765]
### Current Behavior

- I noticed a quick white flash on the app header whenever the app is transitioning to another page of the same stack. I think it's more visible on headers with darker colors.

### Expected Behavior

- There should not be a white flash between transitions

### How to reproduce

- Please refer to this snack.. I just added a dark color. 
[https://snack.expo.io/ryeWoVWl8](url)
### Environment

| software         | version
| ---------------- | -------
| react-navigation | 5.0.0-alpha.22
| react-native     | 0.61.5| node             |
| @react-navigation/stack     | 5.0.0-alpha.55
| Platform | iOS

**Comment by satya164** [comment]
That's a different issue. Please open another issue for that.

**Comment by Bardiamist** [comment]
Why `headerStyleInterpolator: HeaderStyleInterpolators.forUIKit` not by default...

**Comment by Bardiamist** [comment]
HeaderStyleInterpolators.forUIKit leads to another issues when I use TransitionPresets.ModalTransition in inner stack in tabs

**Comment by Bardiamist** [comment]
In `TransitionPresets.forFade`:
```
backgroundStyle: {
      opacity: progress.interpolate({
        inputRange: [0, 1, 1.9, 2],
        outputRange: [0, 1, 1, 0],
      }),
    },
```

can be improved:
```
const forFade = ({
  current,
  next,
}: StackHeaderInterpolationProps): StackHeaderInterpolatedStyle => {
  const progress = Animated.add(
    current.progress.interpolate({
      inputRange: [0, 1],
      outputRange: [0, 1],
      extrapolate: 'clamp',
    }),
    next
      ? next.progress.interpolate({
        inputRange: [0, 1],
        outputRange: [0, 1],
        extrapolate: 'clamp',
      })
      : 0,
  );

  const opacity = progress.interpolate({
    inputRange: [0, 1, 2],
    outputRange: [0, 1, 0],
  });

  return {
    leftButtonStyle: { opacity },
    rightButtonStyle: { opacity },
    titleStyle: { opacity },
    backgroundStyle: {
      opacity: progress.interpolate({
        inputRange: [0, 1, 1.99999999, 2],
        outputRange: [0, 1, 1, 0],
      }),
    },
  };
};
```
@satya164 
Then white flash will not visible for user.

Or I want to try:
```
const forFade = ({ current }: StackHeaderInterpolationProps): StackHeaderInterpolatedStyle => {
  const opacity = current.progress;

  return {
    leftButtonStyle: { opacity },
    rightButtonStyle: { opacity },
    titleStyle: { opacity },
    backgroundStyle: { opacity },
  };
};
```
Any underwater rocks? As I understand then background screens will wisible on navigate to nest screens. But seems that not problem for me.
