### ISSUE TITLE
Can't toggle element inspector on modal window 

### ISSUE THREAD

**Issue by Hirbod** [react-navigation/react-navigation#6766]
When opening rn element inspector while a modal is open, the element inspector gets attached to the window behind. So it's not possible to inspect the modal screen.

No issues with the performance monitor though. This might be even an upstream issue with react-native itself. Or do you think it can be handled by react-native-screens? Not sure where this belongs to.

![Simulator Screen Shot - iPhone 11 - 2020-01-06 at 20 45 38](https://user-images.githubusercontent.com/504909/71844175-e52f6300-30c5-11ea-9bd6-6861a90ca3eb.png)

**Comment by satya164** [comment]
Hey, native-stack has been moved to [software-mansion/react-native-screens](https://github.com/software-mansion/react-native-screens). Please track the issue here: https://github.com/software-mansion/react-native-screens/issues/367

**Comment by Hirbod** [comment]
What you mean by it moved? Do we need to require it from native screens now?

**Comment by satya164** [comment]
Yes

**Comment by Hirbod** [comment]
Is there any documentation for the transition?

**Comment by satya164** [comment]
You'll just need to change the import from '@react-navigation/native-stack' to 'react-native-screens/native-stack' after they publish new version. Everything else should stay the same.

https://github.com/software-mansion/react-native-screens/pull/345

**Comment by Hirbod** [comment]
Ok. Looks like Expo 37 is around the corner, I hope they don’t miss that one here.
