### ISSUE TITLE
react-navigation@next does not show header with transparentModal

### ISSUE THREAD

**Issue by Aryk** [react-navigation/react-navigation#6768]
I was using createNativeStackNavigator to create a new stack. For one of the screens when setting presentation to "transparentModal" or "modal" in my iOS simulator, the overlay comes up but the header is completely gone. Removing {presentation: "transparentModal"} defaults to the push method and it shows the header like its supposed to.

However, with"transparentModal" or "modal" if the screen is another stack, it will show the header in that stack correctly. Is this normal functionality for modals?

**Comment by satya164** [comment]
Hey, native-stack has been moved to [software-mansion/react-native-screens](https://github.com/software-mansion/react-native-screens). Please track the issue here: https://github.com/software-mansion/react-native-screens/issues/365
