### ISSUE TITLE
Collapsible header / modal swipe gesture on inverted ScrollView

### ISSUE THREAD

**Issue by Hirbod** [react-navigation/react-navigation#6769]
Cross-Posting, since I don't know where this should take place. If you consider this as a duplicate, feel free to close.  https://github.com/kmagiera/react-native-screens/issues/263

If you have a ScrollView with inverted property, the LargeTitleHeader behaves accordingly.

If the ScrollView is set to inverted (often the case with chats where messages appear at the bottom) and the whole thing takes place in a modal, you have to swipe backwards to close the modal. This is not an error in itself, but there should be the possibility or a prop for these cases to explicitly reverse the behavior.

**Comment by satya164** [comment]
Seems this is related to native stack. Closing since its in screens repo now.
