### ISSUE TITLE
[@react-navigation/drawer] drawerType="back"

### ISSUE THREAD

**Issue by alz10** [react-navigation/react-navigation#6770]
I'm using `createDrawerNavigator` in a `createNativeStackNavigator`. I set the `drawerType` to `back` and when i tried to tap on the `back button` of my device, the drawer seems to open suddenly. I doesn't look smooth, looks like a flicker bug or something.

![gif](https://user-images.githubusercontent.com/38030623/71622202-18c64500-2c0f-11ea-9045-196fca92b63c.gif)

### Code
navigation.js
```
import Drawer from './Drawer ';

      <NavigationNativeContainer>
        <Stack.Navigator headerMode="none" screenOptions={screenOptions}>
          <Stack.Screen name="Home" component={Home} />
          <Stack.Screen name="Drawer" component={Drawer} />
        </Stack.Navigator>
      </NavigationNativeContainer>
```

Drawer.js
```
     <Drawer.Navigator drawerType="back">
        <Drawer.Screen name="Hello" component={Hello}/>
     </Drawer.Navigator>
```

**Comment by satya164** [comment]
Closing due to no response.
