### ISSUE TITLE
Issue when pressing back with KeyboardAvoidingView v5

### ISSUE THREAD

**Issue by quinnvaughn** [react-navigation/react-navigation#6771]
On React Navigation Next (v5), I have a stack > tabs & chat screen, and one of the tabs is the "chats" screen. The chat is the same level as the tabs so it's not behind them. The chat screen renders a View: flex 1 that contains a FlatList of messages inverted. When a message is added to the FlatList and it updates and then I press back, the screen comes down to go back, but about the bottom third of the screen is still visible for about another second until it finally goes away. This issue is not present if the user does not add a message. Has anyone experienced a situation similar to this? And is it a React Navigation issue, or an issue with my FlatList render, or possibly an issue with my update function on my Apollo hook being too slow?

Here is the useMutation that seems to be causing the issue. 

```
const [sendMessage] = useMutation(SEND_MESSAGE, {
    update: (proxy, { data: { writeMessage } }) => {
      const data = proxy.readQuery({
        query: GET_MESSAGES,
        variables: {
          chatId: route.params.id,
        },
      })
      const newMessages = [
        writeMessage.message,
        ...data.getChatMessages,
      ]
      proxy.writeQuery({
        query: GET_MESSAGES,
        variables: {
          chatId: route.params.id,
        },
        data: {
          ...data,
          getChatMessages: newMessages,
        },
      })
    },
  })
```

**Comment by raajnadar** [comment]
@quinnvaughn can you please test it with the latest version (latest minor version)? or add a snack or GitHub repo. I will reopen the issue if you can reproduce it in the latest version.
