### ISSUE TITLE
Cannot use useNavigation() above the first navigator.

### ISSUE THREAD

**Issue by Titozzz** [react-navigation/react-navigation#6773]
### Current Behavior

Trying to use "useNavigation()" below NavigationContainer but above your first navigator results in: `We couldn't find a navigation object. Is your component inside a navigator?`. We might have some logic that wants to navigate from here. Since this is achievable in the meantime by using the NavigationContainer ref, we could probably allow users to use useNavigation() directly.

### Expected Behavior

useNavigation would allow you to use .navigate() while being below the NavigationContainer.

**Comment by saur2729** [comment]
hi
just checking out - till when this feature will be available for testing

moreover, do we have a workaround - I'm kind of stuck

**Comment by devstarman** [comment]
Hey, I'm having similar problem with using useFocusEffect() inside a screen component that is inside nested StackNavigator (navigator inside navigator). There is an error "Couldn't find a navigation object. Is your component inside a screen in a navigator?

Any workaround? Or way to pass down navigation object?

**Comment by tafelito** [comment]
I had the same issue. As a workaround I put everything on a Stack Navigator and just make the initial route conditional based on props sent to the navigator

Something like this

instead of 

```js
{condition ? 
(
  <ComponentWithoutNavigator/> 
) : (
  <NavigationContainer>
    <BottomTabNavigator  />
  </NavigationContainer>
)}
```

use
```js
<NavigationContainer>
  <MainNavigator condition={condition}/>
</NavigationContainer>

....

<Stack.Navigator
  initialRouteName={condition ? 'RouteA' : 'RouteB'}
>
  <Stack.Screen name="RouteA" component={BottomTabNavigator} />
  <Stack.Screen name="RouteB" component={ComponentWithoutNavigator} />
</Stack.Navigator>
```

**Comment by vavdoshka** [comment]
Heres is what helped me - a how-to on using ref to work with navigation API https://reactnavigation.org/docs/navigating-without-navigation-prop/

**Comment by tringsalil** [comment]
Can anyone help me use useFocusEffect within a functional component that has access to navigation as a prop its not clear to me how can we use the same . Thanks .

**Comment by Nop0x** [comment]
@devstarman Did you ever figure out a way for this in your app? I'm facing the exact same thing to override the hardware back button in android.

**Comment by satya164** [comment]
fixed in https://github.com/react-navigation/react-navigation/commit/1d40279db18ab2aed12517ed3ca6af6d509477d2

**Comment by Peretz30** [comment]
For me, on React Native, the problem was that I imported hook from core, insted of native:
```
import { useFocusEffect } from '@react-navigation/core'; // We couldn't find a navigation object.
import { useFocusEffect } from '@react-navigation/native'; // works
```
