### ISSUE TITLE
Issue with native-stack nested within a bottom-tabs navigator

### ISSUE THREAD

**Issue by Mitch528** [react-navigation/react-navigation#6774]
I'm not sure if this is an issue with react-native-screens or with how react-navigation interacts with it, but I thought I'd start here.

---

### Current Behavior

When pushing a second screen using the native stack navigator nested within a bottom tabs navigator, the bottom tabs continue to take up space as if it were still there (with tabBarVisible being false).

![Simulator Screen Shot - iPhone 11 Pro Max - 2019-11-24 at 10 00 48](https://user-images.githubusercontent.com/932976/69499099-a04bc600-0ea3-11ea-834f-3d8f908e0f00.png)

### Expected Behavior

I expect the new screen not to be covered by the no longer visible bottom tabs.

![Simulator Screen Shot - iPhone 11 Pro Max - 2019-11-24 at 10 14 04](https://user-images.githubusercontent.com/932976/69499103-a477e380-0ea3-11ea-808c-afb3e44c7f64.png)

### How to reproduce

[Mitch528/react-navigation-repro](https://github.com/Mitch528/react-navigation-repro)

### Your Environment

| software         | version
| ---------------- | -------
| @react-navigation/core | 5.0.0-alpha.24
| @react-navigation/native-stack | 5.0.0-alpha.14
| @react-navigation/bottom-tabs | 5.0.0-alpha.22
| react-native-screens | 2.0.0-alpha.12 
| react-native     | 0.61.5

**Comment by satya164** [comment]
Hey, native-stack has been moved to [software-mansion/react-native-screens](https://github.com/software-mansion/react-native-screens). Please track the issue here: https://github.com/software-mansion/react-native-screens/issues/363
