### ISSUE TITLE
Transition performance heavy screen

### ISSUE THREAD

**Issue by AlexandreM59** [react-navigation/react-navigation#6775]
This is not an issue, but this is a question for this new version of react-navigation.

Are the performance of transitions improved with this new version of react-navigation?

I am referring to this issue https://github.com/react-navigation/rfcs/issues/51#issue-335977402. 
I have encountered the same problem, when I am loading a heavy screen or fetching data when a screen mounts in `ComponentDidMount`, the transition to the screen had most of the time a noticeable delay and I have to use `InteractionManager` to fetch the data after the screen has mount.
From what I understood, this delay was encountered since the animation was still calling the main thread and it was blocked since the screen rendering or the data fetching was using it.

I love react-navigation, it is super easy to implement and all, but my app feels slow because all this loading screen since I had to put `InteractionManager` a lot. It seams wix's react-native-navigation manage to handle this issue (see https://github.com/wix/react-native-navigation/issues/3432) and I don't clearly see if it was resolved in the react-navigation V5. I have high hopes since the blog post on the website says "React Navigation meets native" 😄, so it should not use the Main thread for the transition and leave it for the data fetching or the rendering.

**Comment by satya164** [comment]
Closing since there's an RFC for this issue.
