### ISSUE TITLE
autoFocus inputs with native stack causes double navigation glitch

### ISSUE THREAD

**Issue by owinter86** [react-navigation/react-navigation#6778]
### Current Behavior

- Navigating to a screen using createNativeStackNavigator will cause screen to have a double navigation glitch, the animation will reset when the keyboard is activated.
- I can confirm this does not happen with the JS stack navigator.

<img src="https://user-images.githubusercontent.com/2920419/68596338-56beac80-049b-11ea-9349-531d9f9019df.gif" height="400">

### Expected Behavior

- autofocus inputs should not re-trigger the navigation animation, when showing the keyboard.

### How to reproduce

- Navigate to a route with autoFocus TextInput in a native stack navigator.

### Your Environment
    "@react-navigation/core": "^5.0.0-alpha.20",
    "@react-navigation/native": "^5.0.0-alpha.14",
    "@react-navigation/native-stack": "^5.0.0-alpha.9",
    "react-native": "^0.61.4",
    "react-native-screens": "^2.0.0-alpha.8",

**Comment by wong2** [comment]
Same issue here, and it happens on the device so I think it's not related to simulator

**Comment by wong2** [comment]
ref the same issue in another repo: https://github.com/software-mansion/react-native-screens/issues/236

**Comment by wong2** [comment]
ref the same issue in another repo: https://github.com/software-mansion/react-native-screens/issues/236

**Comment by satya164** [comment]
Hey, native-stack has been moved to [software-mansion/react-native-screens](https://github.com/software-mansion/react-native-screens). Please track the issue here: https://github.com/software-mansion/react-native-screens/issues/362
