### ISSUE TITLE
[ANDROID] Tab Bar - tabBarVisible = false displays grey bar

### ISSUE THREAD

**Issue by brandtnewww** [react-navigation/react-navigation#6779]
### Current Behavior

On Android, when I set tabBarVisible to false, I still get a grey bar at the bottom of the screen.

Implemented like this:

```
<Tab.Screen name={AppNavigatorKeys.profileTab.routeName} component={ProfileScreen} options={{ tabBarVisible: false }} />
```

![tabBar-visible-false](https://user-images.githubusercontent.com/44766428/68523925-e3147800-02bf-11ea-8f70-96077bb94b39.png)

### Expected Behavior

I except the tab bar to be hidden, like in iOS.

### How to reproduce

Set options={{ tabBarVisible: false }} of a Tab.Screen.

### Your Environment

```
     "react-native": "0.61.2",
    "@react-navigation/bottom-tabs": "5.0.0-alpha.20",
    "@react-navigation/core": "5.0.0-alpha.21",
    "@react-navigation/native": "^5.0.0-alpha.15",
    "@react-navigation/stack": "5.0.0-alpha.35",
```

**Comment by satya164** [comment]
AFAIK this is fixed in latest version of screens. If not, please comment and I'll re-open.

**Comment by rrsalian16** [comment]
I'm also having the same issue, Any fix?

**Comment by Atheane** [comment]
Same here, on ios, versions:
"react-native-screens": "^3.25.0",
"@react-navigation/bottom-tabs": "^6.5.9",
"@react-navigation/native": "^6.1.7",
"@react-navigation/native-stack": "^6.9.13",
