### ISSUE TITLE
expo only cant not install react-native-gesture-handler

### ISSUE THREAD

**Issue by DevilMayDead** [react-navigation/react-navigation#6787]
yarn add react-native-gesture-handler@~1.5.0
yarn add v1.21.1
[1/4] Resolving packages...
error Command failed.
Exit code: 128
Command: git
Arguments: fetch --tags
Directory: D:\programfiles\nodejs\yarn_cache\v6\.tmp\9ee0a27027db93fad58e8dddb6592fbc
Output:
fatal: not a git repository (or any of the parent directories): .git
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
yarnpkg exited with non-zero code: 128

**Comment by kantorm** [comment]
I strongly recommend reading docs before opening an issue. Here are installation steps for gesture handler on expo.
https://docs.expo.io/versions/v35.0.0/sdk/gesture-handler/#installation

**Comment by brentvatne** [comment]
react-native-gesture-handler currently depends on a package that is installed through git, and git is a pre-requisite for using expo tools: https://docs.expo.io/versions/latest/get-started/installation/#pre-requisities

you'll have this problem if you use expo or react-native-cli, fwiw
