### ISSUE TITLE
inputRange invariant violation expo web nextjs

### ISSUE THREAD

**Issue by emac3** [react-navigation/react-navigation#6789]
**Current Behavior**

Trying Next.js with Expo for Web and React Navigation 5 throws an error on load.

When I run `yarn next dev`:

```
Invariant Violation: inputRange must be monotonically increasing NaN,0
    at invariant (<my_monorepo>/node_modules/fbjs/lib/invariant.js:40:15)
    at checkValidInputRange (<my_monorepo>/packages/<my_package>/.next/server/static/development/pages/_document.js:24098:62)
    at createInterpolation (<my_monorepo>/packages/<my_package>/.next/server/static/development/pages/_document.js:23946:3)
    at new AnimatedInterpolation (<my_monorepo>/packages/<my_package>/.next/server/static/development/pages/_document.js:24116:28)
    at AnimatedValue.interpolate (<my_monorepo>/packages/<my_package>/.next/server/static/development/pages/_document.js:25388:12)
    at getProgressFromGesture (<my_monorepo>/packages/<my_package>/.next/server/static/development/pages/index.js:14820:18)
    at <my_monorepo>/packages/<my_package>/.next/server/static/development/pages/index.js:15154:24
    at Array.map (<anonymous>)
    at getDerivedStateFromProps (<my_monorepo>/packages/<my_package>/.next/server/static/development/pages/index.js:15140:30)
    at processChild (<my_monorepo>/node_modules/react-dom/cjs/react-dom-server.node.development.js:3061:63)
    at resolve (<my_monorepo>/node_modules/react-dom/cjs/react-dom-server.node.development.js:3013:5)
    at ReactDOMServerRenderer.render (<my_monorepo>/node_modules/react-dom/cjs/react-dom-server.node.development.js:3436:22)
    at ReactDOMServerRenderer.read (<my_monorepo>/node_modules/react-dom/cjs/react-dom-server.node.development.js:3395:29)
    at renderToString (<my_monorepo>/node_modules/react-dom/cjs/react-dom-server.node.development.js:3954:27)
    at render (<my_monorepo>/node_modules/next/dist/next-server/server/render.js:80:16)
    at renderPage (<my_monorepo>/node_modules/next/dist/next-server/server/render.js:291:16) {
  name: 'Invariant Violation',
  framesToPop: 1
```

**Expected Behavior**

I load the app in the browser at `http://localhost:3000/` and I'd expect to see the first page.

**How to reproduce**

```
import { NavigationContainer } from "@react-navigation/native";
import { createStackNavigator } from "@react-navigation/stack";
import React from "react";
import { Button, Text, View } from "react-native";

function HomeScreen({ navigation }) {
  return (
    <View style={{ flex: 1, alignItems: "center", justifyContent: "center" }}>
      <Text>Home Screen</Text>
      <Button
        title="Go to Details"
        onPress={() => navigation.navigate("Details")}
      />
    </View>
  );
}

function DetailsScreen({ navigation }) {
  return (
    <View style={{ flex: 1, alignItems: "center", justifyContent: "center" }}>
      <Text>Details Screen</Text>
      <Button title="Go back" onPress={() => navigation.navigate("Home")} />
    </View>
  );
}

const Stack = createStackNavigator();

export default function App() {
  return (
    <NavigationContainer>
      <Stack.Navigator screenOptions={{ animationEnabled: false }}>
        <Stack.Screen name="Home" component={HomeScreen} />
        <Stack.Screen name="Details" component={DetailsScreen} />
      </Stack.Navigator>
    </NavigationContainer>
  );
}

```

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| Web                 | Chrome (latest) |
| @react-navigation/native       | 5.0.0 |
| @react-navigation/stack        | 5.0.0 |
| react-native-gesture-handler   | i1.5.6 |
| react-native-safe-area-context | 0.6.0 |
| react-native-screens           | 2.0.0-alpha.12 |
| react-native                   | 0.61.5 |
| expo                           | 36.0.2 |
| node                           | 12.14.1 |
| yarn                    | 1.21.1 |

**Comment by ankeetmaini** [comment]
Can confirm this is happening on 4.1.1 also. I too was trying to use this with NextJS, though without expo.

Repro repo: https://github.com/ankeetmaini/Dogstagram

```
yarn
yarn web
```

Error:

```
inputRange must be monotonically non-decreasing NaN,0
▶ 5 stack frames were collapsed.
getProgressFromGesture
./CardStack.tsx:1
> 1 | import * as React from 'react';
  2 | import {
  3 |   Animated,
  4 |   View,
View compiled
(anonymous function)
/Users/ankeet.maini/Code/Dogstagram/.next/server/static/development/pages/index.js:5654:17373
getDerivedStateFromProps
./CardStack.tsx:1
> 1 | import * as React from 'react';
  2 | import {
  3 |   Animated,
  4 |   View,
View compiled
▶ 7 stack frames were collapsed.
```

Open http://localhost:3000/ to see the error

**Comment by emac3** [comment]
I found the issue is [here](https://github.com/react-navigation/react-navigation/blob/master/packages/stack/src/views/Stack/CardStack.tsx#L173), when `distance` is `NaN`, 'cause `layout` is `undefined` since there are no window dimensions on server side.
So the problem is related to Next.js SSR. If I disable it with something like [this](https://nextjs.org/docs/advanced-features/dynamic-import#with-no-ssr),  the page loads correctly on the client.
Also you need this [workaround](https://github.com/react-navigation/react-navigation/issues/6757#issuecomment-591732411) and to install [next-images](https://docs.expo.io/versions/latest/guides/using-nextjs/#image-support) to make react-navigation work with Next.js.

**Comment by emac3** [comment]
> Hey! Thanks for opening the issue. Can you provide a minimal repro which demonstrates the issue? Posting a snippet of your code in the issue is useful, but it's not usually straightforward to run. A repro will help us debug the issue faster. Please try to keep the repro as small as possible. The easiest way to provide a repro is on [snack.expo.io](https://snack.expo.io). If it's not possible to repro it on [snack.expo.io](https://snack.expo.io), then you can also provide the repro in a GitHub repository.

To repro you only need create a new project with Expo bare workflow, add [Next.js support ](https://docs.expo.io/versions/latest/guides/using-nextjs/)and then[ add React Navigation](https://reactnavigation.org/docs/getting-started).

**Comment by RWOverdijk** [comment]
What's the solution here? I've had this same issue with react-navigation-collapsible and react-navigation-collapsible on web.
