### ISSUE TITLE
DrawerContentComponentProps Type Definition Omissions 

### ISSUE THREAD

**Issue by jangerhofer** [react-navigation/react-navigation#6790]
**Current Behavior**

When the user defines a custom DrawerContent component and provides it to the `Drawer.Navigator` component, the props provided to `DrawerContent` include a `navigation` object that includes several drawer-related functions (namely `openDrawer`, `closeDrawer`, and `toggleDrawer`).  

These functions are not present in the type definition of the `navigation` object.  Consequently, it is not straightforward to imperatively change the state of the drawer from within the drawer without the TypeScript compiler shouting at you! :)

I define my own custom drawer component as such:
```ts
const DrawerContent: FC<DrawerContentComponentProps> = props => {
    console.log(props); // --> I can see `openDrawer`, `closeDrawer`, and `toggleDrawer` properties inside the logged object, even though they are absent in the type def.
    ...
}
```

and pass it to the navigator via:

```ts
<Drawer.Navigator
    drawerContent={props => <DrawerContent {...props} />}
    ...
/>
```

Tracing the types down the tree I see...

```ts
export declare type DrawerNavigationConfig<T = DrawerContentOptions> = {
    ...
    drawerContent?: (props: DrawerContentComponentProps<T>) => React.ReactNode;
    ...
}
```
...then...
```ts
export declare type DrawerContentComponentProps<T = DrawerContentOptions> = T & {
    ...
    navigation: DrawerNavigationHelpers;
    ....
};
```
...and, finally...
```ts
export declare type DrawerNavigationHelpers = NavigationHelpers<ParamListBase, DrawerNavigationEventMap>;
```

I believe that final definition is the root (or close to the root!) of the mismatch.  Adding the drawer-specific `navigation` fields here may well resolve the type definition omission.

**Expected Behavior**

The `navigation` prop should be typed to include the `openDrawer`, `closeDrawer`, and `toggleDrawer` actions, as they are present at run-time!

**Comment by WoLewicki** [comment]
Can you use `navigation.dispatch(DrawerActions.closeDrawer())` etc there?

**Comment by jangerhofer** [comment]
> Can you use `navigation.dispatch(DrawerActions.closeDrawer())` etc there?

Yep!  That works perfectly well.  

Just to be explicit & clear: `navigation.closeDrawer()` also works in this spot.  The issue is simply that the TS type isn't aware of `.closeDrawer()`.

**Comment by ryanjwessel** [comment]
`navigation.dispatch(DrawerActions.closeDrawer())` was a nice workaround for this issue! Looks like the PR was almost there, but closed due to some remaining type issues.

**Comment by tonycoco** [comment]
```
screenOptions={{
  header: (props) => {
    return <DrawerScreenHeader {...props} />;
  },
  headerShown: true,
}}
```

When using a custom component for a screen's header in a drawer navigator.

`props.scene.descriptor.navigation.dispatch(DrawerActions.toggleDrawer());` does not work.

Nor do I see a type that would accurately describe this component.

**Comment by satya164** [comment]
Closing since these methods are present in latest version.
