### ISSUE TITLE
iOS 13 Style Modal Has White Background instead of Black

### ISSUE THREAD

**Issue by hammadj** [react-navigation/react-navigation#6791]
**Current Behavior**

- What code are you running and what is happening?
Using a NativeStackNavigator and presenting a screen with `stackPresentation: 'modal'` results in the app having a white BG.
![Screen Recording 2020-02-06 at 12 15 20 AM](https://user-images.githubusercontent.com/7143583/73914511-a9c7b600-4876-11ea-909f-7b6f75d83269.gif)

**Expected Behavior**

- What do you expect should be happening?
The status bar text should turn white and the background should be black:
![RPReplay_Final1580973117](https://user-images.githubusercontent.com/7143583/73914680-ff9c5e00-4876-11ea-8d74-58859142e2ff.gif)

**How to reproduce**

Using Expo SDK 36, with `backgroundColor` in app.json set to `#000000` it still doesn't work.

Here's the code snippet:
```tsx
const Stack = createNativeStackNavigator<NavScreenParams>();

export const HomeNavigator: React.FC = () => (
  <Stack.Navigator initialRouteName={Screen.HOME}>
    <Stack.Screen
      name={Screen.HOME}
      component={Home}
      options={{ title: 'Home', headerShown: false }}
    />
    <Stack.Screen
      name={Screen.PROFILE}
      component={ProfileNavigator}
      options={{ stackPresentation: 'modal' }}
    />
  </Stack.Navigator>
);
``` 

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | iOS
| @react-navigation/native       | 5.0.0
| @react-navigation/native-stack | 5.0.0
| react-native-screens           | 2.0.0-beta.2
| react-native                   | https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz
| expo                           | 36.0.2
| node                           | 10.16.0
| npm or yarn                    | 1.16.0

**Comment by philipheinser** [comment]
@hammadj I have the same problem with an expo app. But in my app that does not use expo the background is black. So maybe is an issue that only exists in expo?

**Comment by artalat** [comment]
Came here to post the same issue:


<img src="https://user-images.githubusercontent.com/295630/74082693-46a87000-4a7e-11ea-9000-82b015fe0c38.gif " data-canonical-src="https://user-images.githubusercontent.com/295630/74082693-46a87000-4a7e-11ea-9000-82b015fe0c38.gif " width="300" />

**Comment by hammadj** [comment]
@philipheinser I tried setting the app background color in my expo app as well, no luck. Since react-navigation is an Expo funded / supported project, should be working well together. Dont think its been a problem in past versions, but there is an issue here on the Expo repo as well: https://github.com/expo/expo/issues/6585

They plan to fix it with Expo 37

**Comment by philipheinser** [comment]
@hammadj That would be great looking forward to the 37 release.

**Comment by losh11** [comment]
I'm not using expo (ejected a long time ago), and the background colour is still white. Any idea what I could do?

**Comment by luizfonseca** [comment]
I am having the same issue, for the time being I am using `transparentModal` instead

**Comment by Anish-Agnihotri** [comment]
Ditto, facing the same issue. Does not seem to be limited to Expo either.

**Comment by satya164** [comment]
Hey, native-stack has been moved to [software-mansion/react-native-screens](https://github.com/software-mansion/react-native-screens). Please track the issue here: https://github.com/software-mansion/react-native-screens/issues/361

**Comment by jefelewis** [comment]
You can do this with the [React Native Modal](https://reactnative.dev/docs/modal) with the `presentationStyle="formSheet"` prop.
