### ISSUE TITLE
navigation.replace does not merge the screen initialParams when using a Stack Navigator

### ISSUE THREAD

**Issue by davidkashtan-github** [react-navigation/react-navigation#6792]
**Current Behavior**

When using navigation.replace to completely replace the navigation stack with a new top-level screen, the instantiated screen component only gets the params supplied to the navigation.replace call.

**Expected Behavior**

The screen-defined initialParams should be merged with the navigation.replace params and supplied to the instantiated screen component.

**Your Environment**

React Navigation 5.0.0

**The Fix**

In the "master" branch at react-navigation/packages/routers/src/StackRouter.tsx line 203 (in the 'REPLACE' action case) only the action.payload params is returned in the new state, while at lines 223-229 in the 'PUSH' action case) the routeParamList params are properly merged with the action.payload params.  The 'REPLACE' action code at line 203 should be replaced with code similar to the 'PUSH' action code at lines 223-229.

**Comment by satya164** [comment]
https://github.com/react-navigation/react-navigation/commit/80629bf30baf8f17620e6d3127e00376182af074
