### ISSUE TITLE
Upgrade from alpha to v5 break unit test :     TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by kopax** [react-navigation/react-navigation#6793]
**Current Behavior**

I have tried to upgrade from :

```
| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | iOS, Android and web
| @react-navigation/native       | 5.0.0-alpha.22
| @react-navigation/stack         | 5.0.0-alpha.63
| @react-navigation/drawer       | 5.0.0-alpha.41
| react-native-reanimated        | 1.4.0
| react-native-gesture-handler   | 1.5.3
| react-native-safe-area-context | 0.6.2
| react-native-screens           | 2.0.0-alpha.32
| react-native                   | https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz
| expo                           | SDK36
| node                           | v13.5.0
| npm or yarn                    | 6.13
```

To

```
| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | iOS, Android and web
| @react-navigation/native       | 5.0.0
| @react-navigation/stack         | 5.0.0
| @react-navigation/drawer       | 5.0.0
| react-native-reanimated        | 1.4.0
| react-native-gesture-handler   | 1.5.3
| react-native-safe-area-context | 0.6.2
| react-native-screens           | 2.0.0-beta.1
| react-native                   | https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz
| expo                           | SDK36
| node                           | v13.5.0
| npm or yarn                    | 6.13
```

I have checked the example and thanks. I have upgrade safely all my dependencies to latest except:
- `react-native-web` is 0.11.7 due to https://github.com/react-native-community/async-storage/issues/52
- `react-native-screens` is `2.0.0.beta.1` due to https://github.com/kmagiera/react-native-screens/issues/311 
- `react-native-safe-area-context` is `0.6.2` due to https://github.com/th3rdwave/react-native-safe-area-context/issues/49

I am now trying to upgrade the following:

```jsx
 @react-navigation/drawer  ^5.0.0-alpha.41  →        ^5.0.0 
 @react-navigation/native  ^5.0.0-alpha.22  →        ^5.0.0 
 @react-navigation/stack   ^5.0.0-alpha.63  →        ^5.0.0 
```

I have followed all of your recommendations and to be precise:

- Open the source that used to create `NavigationNativeContainer` and replace `NavigationNativeContainer` for `NavigationContainer` in all the file.
- Verify that the import line is equal to `import { NavigationContainer } from '@react-navigation/native';`
- run `expo start -c` to clear expo cache and notice that both app start on android and ios.
- check at my test and they are all failing:

```
    TypeError: Cannot read property 'split' of undefined

      at Object.<anonymous> (node_modules/@react-navigation/stack/lib/commonjs/views/Stack/CardStack.tsx:42:26)
      at Object.<anonymous> (node_modules/@react-navigation/stack/lib/commonjs/views/Stack/StackView.tsx:8:1)
```
- I have also tried to downgrade dependencies to be as in the demo (ex: `react-native-safe-area-context`  to 0.6.2 instead of 0.6.4) and that didn't help, error is in there: 

https://github.com/react-navigation/react-navigation/blob/abb595830ec19cf43e13f2ecd58ec65460365103/packages/stack/src/views/Stack/CardStack.tsx#L42

I've decided to stick to alpha version until I get some more info. 

Just to confirm the version used:

```
├─┬ @react-navigation/drawer@5.0.0
│ └─┬ @react-navigation/routers@5.0.0
│   └── @react-navigation/core@5.0.0  deduped
└─┬ @react-navigation/native@5.0.0
  └── @react-navigation/core@5.0.0 
```

**Expected Behavior**

I expect the upgrade to go smoothly

**Comment by brooksbecton** [comment]
jest-expo mocks out some of the Expo object for tests, but it doesn't mock out anything for the sdkVersion 
https://github.com/expo/expo/blob/master/packages/jest-expo/src/preset/createMockConstants.js

I don't think jest-expo should mock out the SDK version, but I'm not aware of a way for a user to do that. 

Can we add another `?` after `sdkVersion`?

I can start working on a repro too.

**Comment by kopax** [comment]
Thanks for the hint, I have created a PR to earn some attention https://github.com/expo/expo/pull/6999

> Can we add another `?` after sdkVersion?

No clue, I have never seen that in javascript before reading that file to be honest.


In the meantime, can we make this more permissive here or should we wait for the next expo sdk (not soon).

**Comment by satya164** [comment]
Closing since fixed in `jest-expo`

**Comment by kopax** [comment]
I am using 

└── jest-expo@36.0.1 

It seems that it was released 2 month ago:

![image](https://user-images.githubusercontent.com/1866564/74593335-b0b3ad00-505c-11ea-9903-aae4382b8d2d.png)

@satya164 may I know how I can get the fix? Thanks!
