### ISSUE TITLE
v5 broke typing nested tab `navigation.navigate` usage

### ISSUE THREAD

**Issue by CPatchane** [react-navigation/react-navigation#6795]
Hello here 👋 

I am encountering a typing issue with my app navigation. I didn't have this issue with a previous alpha version usage, it was only when upgrading to stable v5 versions. In my case, I have a `TabNavigator` containing all my views nested into a `DrawerNavigator`, in order to make my drawer available in all my app views. Then I pass a `routeName` parameter to navigate through my views. Here is my (simplified) expo app code:

`App.tsx`
```typescript
export type DrawerScreensParamsTypes = {
  Main: { routeName?: string }
}

const MenuDrawer = createDrawerNavigator<DrawerScreensParamsTypes>()

const App = () => (
  <NavigationContainer>
    <MenuDrawer.Navigator
      drawerPosition="right"
      drawerType="front"
      drawerContent={DrawerContent}
    >
      <MenuDrawer.Screen
        name="Main"
        component={TabNavigator}
        initialParams={{ routeName: "Home" }}
      />
    </MenuDrawer.Navigator>
  </NavigationContainer>
)

export default App
```

`DrawerContent.tsx`
```typescript
const DrawerContent = (props: DrawerContentComponentProps) => {
  const { navigation } = props

  const goTo = (routeName: DrawerScreensParamsTypes["Main"]["routeName"]) => {
    navigation.navigate({ name: "Main", params: { routeName } })
  }

  return (
    <DrawerContentScrollView {...props}>
      <Title light>Menu</Title>
      <View>
        <DrawerItem label="Home" onPress={() => {goTo("Home")}} />
        <DrawerItem label="Second" onPress={() => {goTo("Second")}} />
        <DrawerItem label="Third" onPress={() => {goTo("Third")}} />
        <DrawerItem label="Fourth" onPress={() => {goTo("Fourth")}} />
      </View>
    </DrawerContentScrollView>
  )
}

export default DrawerContent
```

`TabNavigator.tsx`
```typescript
type NavigationPropType = CompositeNavigationProp<
  BottomTabNavigationProp<{}>,
  DrawerNavigationProp<DrawerScreensParamsTypes>
>

const Noop = () => null
const Home = () => <View><Text>Home</Text></View>
const Second = () => <View><Text>Second</Text></View>
const Third = () => <View><Text>Third</Text></View>
const Fourth = () => <View><Text>Fourth</Text></View>

const Tab = createBottomTabNavigator()

const TabNavigator = () => {
  const navigation = useNavigation<NavigationPropType>()
  const route = useRoute<RouteProp<DrawerScreensParamsTypes, "Main">>()

  /* Listen for routeName params change, which leads to view change */
  useEffect(() => {
    if (route.params.routeName) {
      /* HERE IS MY ISSUE */
      navigation.navigate(route.params.routeName)
    }
  }, [route.params.routeName])

  return (
    <Tab.Navigator tabBarOptions={{ showLabel: false }}>
      <Tab.Screen
        name="Home"
        component={Home}
        options={{ tabBarAccessibilityLabel: "Home" }}
      />
      <Tab.Screen
        name="Second"
        component={Second}
        options={{ tabBarAccessibilityLabel: "Second" }}
      />
      <Tab.Screen
        name="Menu"
        component={Noop}
        options={{
          tabBarAccessibilityLabel: "Menu",
          tabBarButton: props => (
            <TouchableOpacity
              {...props}
              onPress={() => navigation.toggleDrawer()}
            />
          ),
        }}
      />
      {/* Below are internal views, not navigated directly
      from the bottom tabBar */}
      {([
        ["Third", Third],
        ["Fourth", Fourth],
      ] as [string, () => JSX.Element][]).map(screenData => (
        <Tab.Screen
          key={screenData[0]}
          name={screenData[0]}
          component={screenData[1]}
          options={{ tabBarButton: Noop }}
        />
      ))}
    </Tab.Navigator>
  )
}

export default TabNavigator
```

**Current Behavior**

When using `navigation.navigate(route.params.routeName)` I got the typing error (from VSC intelissense): 

```
No overload matches this call.
  Argument of type '[string]' is not assignable to parameter of type '["Main"] | ["Main", { routeName?: string; }]'.
    Type '[string]' is not assignable to type '["Main"]'.
      Type 'string' is not assignable to type '"Main"'.
  Overload 2 of 2, '(route: { key: string; params?: { routeName?: string; }; } | { name: "Main"; key?: string; params: { routeName?: string; }; }): void', gave the following error.
    Argument of type 'string' is not assignable to parameter of type '{ key: string; params?: { routeName?: string; }; } | { name: "Main"; key?: string; params: { routeName?: string; }; }'.ts(2769)
```

It's not expecting a string anymore, but when I use `navigation.navigate("Main", route.params)` or just `navigation.navigate(route)`, the error is fixed but the navigation just doesn't work.

This is an issue because when I force the type here using `navigation.navigate(route.params.routeName as any)` my navigation is working correctly.

**Expected Behavior**

Either the expecting argument type from `navigation.navigate` here should handle `string` or passing the expected format of `route` to `navigation.navigate` should navigate to the matching view correctly.
Maybe I am just using things in a wrong way so feel free to tell me if it's the case :)

**How to reproduce**

I tried to provide a snack: https://snack.expo.io/SyNdFw3GL
But I think that there are some issues about type checking, `navigation.navigate` is inferred as `any` type.

BTW, In that snack, I also have an issue. When I first click on `Second` tab then open the drower and click on `Home` item, the navigation doesn't work, is that normal?

**Your Environment**

| software                      | version |
| ----------------------------- | ------- |
| iOS or Android                | iOS simulator
| @react-navigation/native      | 5.0.0
| @react-navigation/bottom-tabs | 5.0.0
| @react-navigation/drawer| 5.0.0
| react-native-screens          | 2.0.0-alpha.12
| react-native                  | https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz
| expo                          | 36.0.2
| node                          | 12.14.0
| npm or yarn                   | 1.21.1

**Comment by satya164** [comment]
The type-checking is working as expected. You have defined one screen `Main` for the drawer and no screens for tab (empty record of screens in `BottomTabNavigationProp<{}>`). So we can only find one screen (`Main`). If you want `navigate` to accept additional screens, then specify the name of screens instead of empty record or if you want it to accept any string, then specify `{ [key: string]: undefined }`.

If it didn't complain in a previous version that means the type-checking was broken.

Also you don't need to navigate manually in `useEffect`. This should work already https://reactnavigation.org/docs/en/nesting-navigators.html#navigating-to-a-screen-in-a-nested-navigator

For type-check to work, you'll need to specify the `screen` type in drawer's params.

**Comment by CPatchane** [comment]
Thanks for the quick reply and the explanation about typing here 👍 

> Also you don't need to navigate manually in useEffect. This should work already https://reactnavigation.org/docs/en/nesting-navigators.html#navigating-to-a-screen-in-a-nested-navigator
> For type-check to work, you'll need to specify the screen type in drawer's params.

Indeed, it's perfect for my use case and it's better to use `screen` instead. But using this way, I have to click twice on a `DrawerItem` to make the drawer closing. How do you do to "`navigate` + close drawer" when you click on a DrawerItem then?

**Comment by satya164** [comment]
Can you open an issue about that?

**Comment by CPatchane** [comment]
@satya164 Yep, it's here #6800 :)
