### ISSUE TITLE
Header is out of the safe area on Android (react-navigation/native-stack)

### ISSUE THREAD

**Issue by enheit** [react-navigation/react-navigation#6797]
**Current Behavior**

The header navigation is rendered beyond safe area on Android devices.

![image](https://user-images.githubusercontent.com/8645216/74091933-4f249900-4ac6-11ea-9ce6-bded773c13a7.png)

**Expected Behavior**

The header should be rendered in 'safe area'.

![image](https://user-images.githubusercontent.com/8645216/74091967-b2aec680-4ac6-11ea-97a8-6d03cc8be951.png)

(this is how `@react-navigation/stack` works)

**How to reproduce**

Create a screen by using `Screen.Stack` from `@react-navigation/native-stack`

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Android (v9)
| @react-navigation/native       | ^5.0.0-alpha.33
| @react-navigation/native-stack | ^5.0.0
| react-native-screens           | ^2.0.0-beta.2
| react-native                   | ~0.61.4
| expo                           | ~36.0.0
| node                           | v12.14.1
| npm or yarn                    | 6.13.4

**Comment by cokealmonacid** [comment]
If you are using expo, check this link https://docs.expo.io/versions/v36.0.0/guides/configuring-statusbar/

**Comment by babylone-star** [comment]
This can be worked around by adding some padding corresponding to the `StatusBar` height, but if you're like me and have some views with custom backgrounds that _need_ to go under (for a particular page), applying a global padding does not work.

**Comment by satya164** [comment]
Hey, native-stack has been moved to [software-mansion/react-native-screens](https://github.com/software-mansion/react-native-screens). Please track the issue here: https://github.com/software-mansion/react-native-screens/issues/380
