### ISSUE TITLE
set header for drawer navigation

### ISSUE THREAD

**Issue by zeitamin** [react-navigation/react-navigation#6798]
I tried to set header in react navigation v5 by setting options without any change

    <Drawer.Navigator
      initialRouteName='...'
    >
      <Drawer.Screen
        name='...'
        component={Component}
        options={{ title: 'My home' }}
      />
    </Drawer.Navigator>

is there a way I could have my react navigation header in drawer?

**Comment by WoLewicki** [comment]
Drawer navigator doesn't provide a header. You can e.g. nest a stack navigator with only one screen inside the drawer to make the header visible or provide a custom component that will imitate the header. Does it solve your problem?
