### ISSUE TITLE
v5 How to close automatically the drawer on navigate?

### ISSUE THREAD

**Issue by CPatchane** [react-navigation/react-navigation#6800]
**Current Behavior**

I have an application with a tab navigator nested in a drawer navigator, so I use the [`screen` parameter](https://reactnavigation.org/docs/en/nesting-navigators.html#navigating-to-a-screen-in-a-nested-navigator) to navigate through my nested views.
Using this way, on iOS/Android (seems to work on the Web), when you click on a drawer item to navigate to a new view, the view is changed but it doesn't close the drawer automatically. I have to click twice on the item to get the correct behaviour here, I didn't see any API props to change that behaviour, I guess this is a bug.

**Expected Behavior**

When clicking on a drawer item, it navigates to the matching view and closes the drawer automatically.

**How to reproduce**

Here is the snack https://snack.expo.io/SJgMFOpGU

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | ios 11
| @react-navigation/native       | 5.0.0
| @react-navigation/drawer       | 5.0.0
| react-native-reanimated        | 1.4.0
| react-native-gesture-handler   | 1.5.6
| react-native-safe-area-context | 0.6.0
| react-native-screens           | 2.0.0-alpha.12
| react-native                   | https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz
| expo                           | 36.0.2
| node                           | 12.14.0
| npm or yarn                    | 1.21.1

**Comment by eriveltonelias** [comment]
Hey @CPatchane, 

you can do the following: https://snack.expo.io/@eriveltonelias/drawer-tab-stack

**Comment by CPatchane** [comment]
I fixed this issue by just replacing in my `DrawerContent`

```typescript
  const goTo = (screen: string) => {
    navigation.navigate("Main", { screen })
  }
```

by 
```typescript
  const goTo = (screen: string) => {
    navigation.navigate(screen)
  }
```

I still doesn't understand the difference here and why it behaves differently, but at least it works.
Thanks @eriveltonelias 👍
