### ISSUE TITLE
Clicking on drawer items create large ripple on whole container

### ISSUE THREAD

**Issue by ShivamJoker** [react-navigation/react-navigation#6801]
**Current Behavior**
When I click on the drawer list it shows a big hover ripple instead of just on button
![image](https://user-images.githubusercontent.com/23727670/74103141-a0d52e00-4b6f-11ea-83aa-2122aebf39a1.png)

I am on my actual physical device using MIUI 11 and Android 9

It works fine on my emulator like it should. (Android 10 Pixel 2)

I am using the latest and update version of React Navigation `^5`

**Comment by akrava** [comment]
Same problem on Android 9 with React Navigation v5

**Comment by ShivamJoker** [comment]
@satya164 the `overflow hidden` doesn't seems to be fixing the issue.

**Comment by satya164** [comment]
PR welcome if you figure it out.

**Comment by thiagoferolla** [comment]
I'm havi g the same issue with the back button on the stack navigator
