### ISSUE TITLE
React-navigation 4.x - navigation.state.routes is undefined

### ISSUE THREAD

**Issue by yarapolana** [react-navigation/react-navigation#6802]
Hey dev.
 
A couple of days ago react-navigation started breaking the navigation UI of my job's app, so I decided to updated to `4.1.1` since I use it for my personal projects and works great.

After upgrading it, the UI started working fine but I am having an error with `navigation.state.routes[navigation.state.index].routeName` and `navigation.state.routes.length` coming out as undefined.

Now I know navigation.state used to have: `index, isTransitioning, key, params, routeName, routes.key, routes.routeName` now its only `key, params and routeName`.

I figured out how to solve the routeName but the app custom nav components are heavily dependent on the `navigation.state.routes.length` does anyone know the equivalent of this?

I am using:

 - expo: sdk36 (jobs app)
 - react-native: 0.61 (side projects)
 - react-navigation: 4.1.1
 - react-navigation-stack: 2.1.1
 - react-navigation-tabs: 2.7.0

The documentation of 4.x also shows `navigation.state.index` which is undefined... here is an example of what I tried so far:

```
{
  defaultNavigationOptions: {
    header: ({ navigation, navigationState }) => {
      console.log(navigation.state) <-- key, param and routeName
      console.log(navigation.state.index) <-- undefined
      console.log(navigation.state.routes) <-- undefined
      console.log(navigationState) <-- undefined
    }
}
```

I wish react-navigation 4.x docs were better organized like the 5.x (great job here <3 all the way).

Please this is sort of an emergency any insight is helpful.
Thanks.

**Comment by satya164** [comment]
Try `navigation.dangerouslyGetParent().state`

**Comment by yarapolana** [comment]
Hey @satya164 this works, thank you, although the UI breaks (flickering screen, and some weird behaviours).
Since you closed this one, I will open another issue with more details in relation to the UI breaking bug.

**Comment by mkhib** [comment]
Hey @yarapolana . I have the same problem after upgrading my react navigation version and since I use type Script it said that navigation.dangerouslyGetParent().state is possibly undefined ! so did you find any other workarounds to this ?

**Comment by mkhib** [comment]
Changed my TSX file to JS for now. I don't know why they break something like this :|
