### ISSUE TITLE
CommonActions.reset is not a function

### ISSUE THREAD

**Issue by hakkikonu** [react-navigation/react-navigation#6803]
`import { CommonActions } from '@react-navigation/native';
`

Then

simple function that triggers CommonActions.reset()

```
goToMenu = () => {
    this.props.navigation.dispatch(
      CommonActions.reset({
        index: 0,
        routes: [{name: 'Menu'}],
      }),
    );
  };
```

When i call this it gives;

Result:  `CommonActions.reset `is not a function. I'm using v5.0.0

Also` CommonActions.replace()` gives same error.

Also React Navigation's [expo example](https://snack.expo.io/?platform=android&name=CommonActions%20reference%20%C2%B7%20React%20Navigation&dependencies=%40react-native-community%2Fmasked-view%40%5E0.1.1%2C%40react-navigation%2Fnative%40%5E5.0.0%2C%40react-navigation%2Fbottom-tabs%40%5E5.0.0%2C%40react-navigation%2Fdrawer%40%5E5.0.0%2C%40react-navigation%2Fmaterial-bottom-tabs%40%5E5.0.0%2C%40react-navigation%2Fmaterial-top-tabs%40%5E5.0.0%2C%40react-navigation%2Fnative-stack%40%5E5.0.0%2C%40react-navigation%2Fstack%40%5E5.0.0%2Creact-native-gesture-handler%401.5.2%2Creact-native-reanimated%401.4.0%2Creact-native-safe-area-context%400.6.0%2Creact-native-screens%402.0.0-alpha.12&sourceUrl=https%3A%2F%2Freactnavigation.org%2Fexamples%2F5.x%2Fcommon-actions.js) has this issue:

**Comment by satya164** [comment]
I can't repro your issue with `reset`. `replace` is available in `StackActions`. The example is outdated.

https://reactnavigation.org/docs/en/stack-actions.html#replace

**Comment by kircod** [comment]
`StackActions` is undefined when imported from `@react-navigation/routers`. I had to import it from `@react-navigation/routers`.
