### ISSUE TITLE
Cannot navigate more than 1 screen back in a NativeStack with stackPresentation transparentModal or modal

### ISSUE THREAD

**Issue by jkingworking** [react-navigation/react-navigation#6804]
I have a demo app with one native stack navigator and 3 screens setup up with `stackPresentation:transparentModal`. Each screen navigates to the next except the final screen which attempts to navigate back to the first.

Attempting to navigate from the last screen back to the first causes the second screen to flash into view then be replaced by the third screen again. The app is left in an unusable state as none of the content on the screen in view is interactable.

![Bug](https://user-images.githubusercontent.com/4926948/74111084-78413a00-4b57-11ea-8e5a-774bafefe435.gif)

**Expected Behavior**
I would expect this to behave like the StackNavigator and transition smoothly to the correct screen.

**How to reproduce**
This is the smallest working example. It doesn't happen in the Appetize.io demo but does on the iOS simulator and actual devices.
https://snack.expo.io/@jkingworking/bug:-native-stack-modal-navigation

To reproduce take a look at the demo app and click through the screens in order.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | iOS |
| @react-navigation/native       | 5.0.0|
| @react-navigation/native-stack |5.0.0|
| react-native-screens           | 2.0.0-alpha.34|
| react-native                   | https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz |
| expo                           |  36.0.0|
| node                           | 12.13.0|
| npm or yarn                    | yarn 1.19.1 |

**Comment by satya164** [comment]
Hey, native-stack has been moved to [software-mansion/react-native-screens](https://github.com/software-mansion/react-native-screens). Please track the issue here: https://github.com/software-mansion/react-native-screens/issues/359
