### ISSUE TITLE
 Headerless screen to screen with header jerks.

### ISSUE THREAD

**Issue by beingArkReal** [react-navigation/react-navigation#6807]
**Current Behavior**

Please refer this issue for detailed info:  https://github.com/react-navigation/react-navigation/issues/2732

![ezgif-6-a5fec0930dba](https://user-images.githubusercontent.com/49546685/74142413-d6852000-4c1e-11ea-9346-5b34e2b67e5f.gif)

**How to reproduce**
Switch stack navigator from headerless one to header one.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |
| @react-navigation/native  5.0     |
| @react-navigation/native-stack 5.0 |
| react-native-screens   2.0.0-alpha.29        |
| react-native            0.61.5       |

**Comment by beingArkReal** [comment]
giving a fixed height for the header can fix this glitch, but I'm not sure whether this is the best practice.

**Comment by MoSattler** [comment]
same issue here on iOS - this looks like a bug to me.
