### ISSUE TITLE
Transform with key of "translateY" must be a number: {"translateY":"-100%"}

### ISSUE THREAD

**Issue by leethree** [react-navigation/react-navigation#6808]
**Current Behavior**

- Open a screen with `gestureDirection: 'vertical'`
- Crash with the following error:

```
Invariant Violation: Transform with key of "translateY" must be a number: {"translateY":"-100%"}

This error is located at:
    in RCTView (at View.js:45)
    in View (at createAnimatedComponent.js:151)
    in AnimatedComponent (at HeaderSegment.tsx:304)
    in HeaderSegment (at Header.tsx:44)
    in Header (at HeaderContainer.tsx:147)
    in RCTView (at View.js:45)
    in View (at HeaderContainer.tsx:122)
    in RCTView (at View.js:45)
    in View (at HeaderContainer.tsx:58)
    in HeaderContainer (at StackView.tsx:294)
    in CardStack (at StackView.tsx:381)
...
```

**Expected Behavior**

- It should not crash.

It's pretty obvious that this line of code doesn't work with React Native `Animated`:
https://github.com/react-navigation/react-navigation/blob/cff2d06adc0cdb215608d2ca56897f5b65cfd53d/packages/stack/src/TransitionConfigs/HeaderStyleInterpolators.tsx#L251

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | iOS
| @react-navigation/native       |  5.0.0
| @react-navigation/stack        |  5.0.0
| react-native-gesture-handler   |  1.4.1
| react-native-safe-area-context | 0.6.2
| react-native-screens           | 1.0.0-alpha.23
| react-native                   | 0.59.10
| expo                           | N/A
| node                           | 10.15.0
| yarn                    | 1.21.1

**Comment by satya164** [comment]
React Navigation 5 doesn't support React Native 0.59. You need to be on the latest version.
