### ISSUE TITLE
Swipe back is not working

### ISSUE THREAD

**Issue by berkaey** [react-navigation/react-navigation#6809]
**Current Behavior**

with 

```
"@react-navigation/native-stack": "^5.0.0",
"react-native-screens": "^2.0.0-beta.2",
```
swipe back is not work on iOS 13.

**Expected Behavior**

It should work line in stack navigator.

**How to reproduce**

just create a simple 2 view app and swipe back.

https://snack.expo.io/@berkaey/routing-test << some how working in this demo

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | 13.3
| @react-navigation/native       |
| @react-navigation/native-stack | 5
| react-native-screens           | 2.0.0-beta.2
| react-native                   | 0.61.5
| expo                           |
| node                           |
| npm or yarn                    |

**Comment by berkaey** [comment]
updated the snack.

**Comment by franciscofsales** [comment]
Same issue here:

` "@react-navigation/native": "^5.0.3",`

`"@react-navigation/native-stack": "^5.0.3",`

**Comment by satya164** [comment]
Hey, native-stack has been moved to [software-mansion/react-native-screens](https://github.com/software-mansion/react-native-screens). Please track the issue here: https://github.com/software-mansion/react-native-screens/issues/358
