### ISSUE TITLE
Problematic combination of "switch", stack, and stack with modal

### ISSUE THREAD

**Issue by pvinis** [react-navigation/react-navigation#6811]
**Current Behavior**

There is a problem with stacks when we involve a "switch", a stack and a stack with modal.

The typical "switch" navigator for v5 is to just have a conditional return. I used here the typical "auth" flow. Then we have the stack with a `Home` and a `Something` screen, just to test this. All good so far.

Now we add a stack with modal that goes before the `MainStack`, as the documentation suggests. Now we have a problem!

When we log in, the next screen comes as a modal! This is not what we want.

**Expected Behavior**

 The `Home` screen should appear as a normal stack screen, and only the `Modal` should appear as a modal screen. Is this a bug with the library, a restriction of the library, or just a case that is not considered?

**How to reproduce**

repro repo: https://github.com/pvinis/modal-react-navigation-repro

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | iOS |
| @react-navigation/native       | 5.0.1 |
| react-native                   | 0.61.5 |
| expo                           | no |
| node                           | 13.1.0 |
| npm or yarn                    | yarn |

**Comment by satya164** [comment]
This should be fixed in latest version.

There won't be animation since you're using 2 different navigators. If you want animation, then you'll need to use one navigator and conditionally define the screens.

**Comment by pvinis** [comment]
I'll try the latest. I don't mind about the animation, as long as it's not the **wrong** animation, here, the modal :D 
Thanks.
