### ISSUE TITLE
createMaterialTopTabNavigator allows a second tier in a stack to navigate to another stack

### ISSUE THREAD

**Issue by igibliss00** [react-navigation/react-navigation#6812]
**Current Behavior**
`createMaterialTopTabNavigator` allows navigating from a second layer of a stack direct to the first layer of another screen by swiping in iOS.

**Expected Behavior**
I expect the screens to be able to only navigate to screens within the same stack by swiping.

**How to reproduce**
https://snack.expo.io/SkdtZ7yXU

I currently have a nested navigation stack using React Navigation in iOS:
```js
const HomeStack = createStackNavigator({
    Home: {
        screen: HomeScreen,
        navigationOptions: {
            header: null,
        },
    },
    Detail: {
        screen: DetailScreen,
    }
})

const MainStack = createMaterialTopTabNavigator({
    Home: {
        screen: HomeStack ,
    },
    Profile: {
        screen: ProfileScreen,
    },
}, {
        tabBarPosition: null,
    }
)
```

The first layer is the MainStack using createMaterialTopTabNavigator as shown above. On the second layer, when I navigate from the HomeScreen to the DetailScreen, I expect the only way to navigate from this screen is to go back to the HomeScreen by swiping right.

However, I'm currrently able to swipe left from the DetailScreen and navigate directly to the ProfileScreen on the first layer, as if I'm going from the HomeScreen. I'm guessing this is either a feature or a bug of createMaterialTopTabNavigator, but I need to use createMaterialTopTabNavigator so that I can navigate from one screen to another by swiping and not having to press on the navigation tab, sort of like react-native-viewpager, but between non-stacked screens.

To be more specific, I expect the behavior to be following:

HomeScreen -> DetailScreen - (swipe right) -> HomeScreen -> ProfileScreen

However, following is currently possible:

HomeScreen -> DetailScreen - (swipe left ) -> ProfileScreen

Is there either a way to block the navigation from DetailScreen on the second layer of the navigation stack directly to ProfileScreen which is on the first layer of the navigation stack? Otherwise, is there a way to navigate to different non-stacked screens on the same level using a different navigator than createMaterialTopTabNavigator?

**My Environment**
    "expo": "~36.0.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz",
    "react-native-gesture-handler": "~1.5.0",
    "react-native-reanimated": "~1.4.0",
    "react-native-screens": "2.0.0-alpha.12",
    "react-native-web": "~0.11.7",
    "react-navigation": "^4.0.6",
    "react-navigation-stack": "^1.8.0",
    "react-navigation-tabs": "^2.5.4",

**Comment by igibliss00** [comment]
Is the aforementioned behavior of `createMaterialTopTabNavigator` an intended behavior or a bug?

**Comment by satya164** [comment]
It's not a bug. Tab navigator doesn't care what's nested inside and won't disable its gestures.
