### ISSUE TITLE
[v5] TypeError: undefined is not a function (near ...createRouter...)

### ISSUE THREAD

**Issue by flexsurfer** [react-navigation/react-navigation#6813]
**Current Behavior**

- Trying to run a minimal example from here https://reactnavigation.org/docs/en/tab-based-navigation.html
- Get this  on ios simulator

![image](https://user-images.githubusercontent.com/11790366/74179617-20313300-4c3e-11ea-9d47-1f2510e40bc9.png)

**Expected Behavior**

No errors

**How to reproduce**

Just try to run minimal example

**Your Environment**

| software                      | version |
| ----------------------------- | ------- |
| iOS or Android                | iOS
| @react-navigation/native      | ^5.0.0
| @react-navigation/bottom-tabs | ^5.0.1
| react-native-screens          | ^2.0.0-beta.2
| react-native                  | 0.61.4
| expo                          |
| node                          | v12.5.0
| npm or yarn                   | yarn 1.13.0

**Comment by sercanov** [comment]
I'm also having the same issue with `@react-navigation/stack v5.0.1`

**Comment by satya164** [comment]
Upgrade `@react-navigation/native` to `5.0.1`

**Comment by amduffy19** [comment]
I'm getting the same error with DrawerNavigator. I'm already on `@react-navigation/native v5.0.1` and still seeing it.

**Comment by Aniie11** [comment]
how to solve this problem??

**Comment by flexsurfer** [comment]
`yarn upgrade @react-navigation/native`

**Comment by docteur-charles** [comment]
yarn upgrade

**Comment by docteur-charles** [comment]
`yarn upgrade`

**Comment by pulidlc** [comment]
Thanks!  "yarn upgrade" works!
