### ISSUE TITLE
Fix React Native 'resolution' to less than 0.61.5

### ISSUE THREAD

**Issue by bigorangemachine** [react-navigation/react-navigation#6817]
**Current Behavior**

- What code are you running and what is happening?
- Include a screenshot or video if it makes sense.

Using React Native 0.61.5 Navigation Reset or Back Action:
```
this.props
               .navigation
               .dispatch(NavigationActions.reset(
                 {
                    index: 0,
                    actions: [
                      NavigationActions.navigate({ routeName: 'Menu'})
                    ]
                  }));
```
OR
```
this.props.navigation.goBack()
```
Navigation either partially navigates or not at all (some components don't update)

**Expected Behavior**

> - What do you expect should be happening?
> - Include a screenshot or video if it makes sense.

npm install should upgrade to 5.x when using 0.61.5 react native

**How to reproduce**

> - You must provide a way to reproduce the problem. If you are having an issue with your machine or build tools, the issue belongs on another repository as that is outside of the scope of React Navigation.
> - Either re-create the bug on [Snack](https://snack.expo.io) or link to a GitHub repository with code that reproduces the bug.
> - Explain how to run the example app and any steps that we need to take to reproduce the issue from the example app.
> - Keep the repro code as simple as possible, with the minimum amount of code required to repro the issue.
> - Before reporting an issue, make sure you are on latest version of the package.

Setup a React Native App with some nested navigation. Attempt to go back. 

No action happens or actions where some components update and others don't

Same goes for reset

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| react-navigation               | 4.x |
| react-navigation-stack         | 4.x
| react-navigation-tabs          | 4.x
| react-navigation-drawer        | 4.x
| react-native                   | 0.61.5 |
| node                           | 12.15.0 |
| npm or yarn                    | 6.13.7 |

Should Branch 4.x set 'resolution' to 0.60?

https://github.com/react-navigation/react-navigation/blob/4.x-monorepo/package.json#L47

**Comment by satya164** [comment]
Closing due to no response.
