### ISSUE TITLE
Default Screen Background Color not white anymore after ugprading

### ISSUE THREAD

**Issue by felix-voicehub** [react-navigation/react-navigation#6819]
**Current Behavior**

I have upgraded from 4.0.10 to to 4.1.1 and my screens used to have a white default background color if not specified otherwise. No, it is this light gray. How can I specify a default screen background color?

**Expected Behavior**

It should be white.

**How to reproduce**

I am on 4.1.1.

**Comment by satya164** [comment]
```js
cardStyle: { backgroundColor: 'white' }
```

https://reactnavigation.org/docs/en/4.x/stack-navigator.html#cardstyle

**Comment by serhiipalash** [comment]
Hi @satya164 ! Is there a way to update `cardStyle` after `createStackNavigator` is called in v4? For example, if we want to change background color across the app on theme switch.

**Comment by satya164** [comment]
@serhiipalash `cardStyle` is in `navigationOptions` in stack v2 so you can update it with params or screenProps

**Comment by serhiipalash** [comment]
Great! Thank you @satya164 !

**Comment by EhsanSarshar** [comment]
card style not exist in tabNavigator

**Comment by chargingsleipnir** [comment]
> in material top tab navigator its
> 
> ```
> sceneContainerStyle={{
>         backgroundColor: '#fff',
>  }}
> ```
> 
> and in bottom tab navigator there is no field for background color.

Glad I found this. I had to specifically switch to the top tabs just for "sceneContainerStyle", though it's screens can't seem to use the "unmountOnBlur" property that the bottom tabs can, which I also need. So frustrating that they don't all have these same features.

**Comment by NishargShah** [comment]
I think none of the above answers worked for me in `react-navigation 5` so, I made it mine own solution and share it with you

Just changed background of your `theme` in `react-navigation 5` and you are good to go.

```
import React from 'react';
import { NavigationContainer, DefaultTheme } from '@react-navigation/native';

const MainNavigator = () => {
  const MyTheme = {
    ...DefaultTheme,
    colors: {
      ...DefaultTheme.colors,
      background: '#FFF',
    },
  };

  return (
    <NavigationContainer theme={MyTheme}>
      ...
    </NavigationContainer>
  );
};

export default MainNavigator;

```

https://reactnavigation.org/docs/themes/

**Comment by therealemjy** [comment]
@NishargShah That fixed it for me: thank you!

**Comment by NishargShah** [comment]
> @NishargShah That fixed it for me: thank you!

Welcome

**Comment by Josefpa** [comment]
> I think none of the above answers worked for me in `react-navigation 5` so, I made it mine own solution and share it with you
> 
> Just changed background of your `theme` in `react-navigation 5` and you are good to go.
> 
> ```
> import React from 'react';
> import { NavigationContainer, DefaultTheme } from '@react-navigation/native';
> 
> const MainNavigator = () => {
>   const MyTheme = {
>     ...DefaultTheme,
>     colors: {
>       ...DefaultTheme.colors,
>       background: '#FFF',
>     },
>   };
> 
>   return (
>     <NavigationContainer theme={MyTheme}>
>       ...
>     </NavigationContainer>
>   );
> };
> 
> export default MainNavigator;
> ```
> 
> https://reactnavigation.org/docs/themes/

Thank you Took Me a week to find
