### ISSUE TITLE
Question about withNavigation in v5

### ISSUE THREAD

**Issue by tankpower1** [react-navigation/react-navigation#6821]
Is it still supported since i need to use it in a class based component?

Same goes for withNavigationFocus?

**Comment by cristianoccazinsp** [comment]
I'm wondering the same. Just found out v5 is 100% hooks based. This is a big bummer to anyone using v4 and class based components.

Can we document and have back some of the class based components? Or are they totally gone with v5?

**Comment by satya164** [comment]
HOCs are available in the compat package https://reactnavigation.org/docs/en/compatibility.html

Also there are usage docs for class components for the hooks https://reactnavigation.org/docs/en/use-navigation.html#using-with-class-component

**Comment by cristianoccazinsp** [comment]
That's awesome! What are the plans to remove that layer? Might want to consider class based components to be part of the core library at least since React won't be getting rid of them in a good time.

**Comment by satya164** [comment]
It's not going to be removed. You can use it for as long as you need. It's an official package and will be improved in future.

**Comment by cristianoccazinsp** [comment]
Hey @satya164 , I do not see `NavigationEvents` in the compat lib. Which component would replace it?
