### ISSUE TITLE
Undefined is not an object while nesting Stacknavigator inside Drawer 

### ISSUE THREAD

**Issue by Merrick17** [react-navigation/react-navigation#6822]
**Current Behavior**

`function HomeNav() {
  const Stack = createStackNavigator();

  return (
    <Stack.Navigator initialRouteName="Main">
      <Stack.Screen name="Main" component={MainScreen} />
      <Stack.Screen name="MainW" component={MainWallet} />
    </Stack.Navigator>
  );
}

export default function NavDrawer(props) {
  const Drawer = createDrawerNavigator();

  const icnProps = {
    color: "white",
    size: 20,
    focused: false
  };
  const iconProprty = {
    color: "white",
    size: 20,
    focused: false
  };
  const DashboardLbl = {
    color: "white",
    focused: false
  };
  ///Labels
  const DashboardLabel = DashboardLbl => (
    <Text style={{ color: "white" }}>Dashboard</Text>
  );
  const WalletLabel = DashboardLbl => (
    <Text style={{ color: "white" }}>Cryptocurrency Wallet</Text>
  );
  const PayLabel = DashboardLbl => (
    <Text style={{ color: "white" }}>Mobile Payment</Text>
  );
  const BuyLabel = DashboardLbl => (
    <Text style={{ color: "white" }}>Buy Cryptocurrncy</Text>
  );

  const ATMLabel = DashboardLbl => (
    <Text style={{ color: "white" }}>Find Bitcoin ATM</Text>
  );

  const NewsLabel = DashboardLbl => (
    <Text style={{ color: "white" }}>Latests News</Text>
  );
  const ExitLabel = DashboardLbl => (
    <Text style={{ color: "white" }}>Exit Wallet</Text>
  );
  const backupLabel = DashboardLbl => (
    <Text style={{ color: "white" }}>Backup Wallet</Text>
  );
  const SettingLabel = DashboardLbl => (
    <Text style={{ color: "white" }}>User Settings</Text>
  );
  const DashboardIcon = icnProps => (
    <Icon name="home" color="white" size={20} />
  );
  const walletIcon = iconProprty => (
    <Icon name="bitcoin" color="white" size={20} />
  );
  const buyIcon = icnProps => (
    <Icon name="shopping-bag" color="white" size={20} />
  );
  const atmIcon = icnProps => (
    <Icon name="location-arrow" color="white" size={20} />
  );
  const payIcon = icnProps => (
    <Icon name="credit-card" color="white" size={20} />
  );
  const newsIcon = icnProps => (
    <Icon name="newspaper-o" color="white" size={20} />
  );
  const refreshIcon = icnProps => (
    <Icon name="refresh" color="white" size={20} />
  );
  const VGWLogo = icnProps => (
    <View>
      <Image source={require("../assets/images/VegaWallet.png")} />
      <Text>User Name</Text>
    </View>
  );
  return (
    <NavigationContainer>
      <Drawer.Navigator
        initialRouteName="Home"
        drawerStyle={{
          backgroundColor: "#292732"
        }}
      >
        <Drawer.Screen
          name="Home"
          component={HomeNav}
          options={{
            drawerLabel: DashboardLabel,
            drawerIcon: DashboardIcon
          }}
        />
        <Drawer.Screen
          name="Wallet"
          component={MainWallet}
          options={{
            drawerLabel: WalletLabel,
            drawerIcon: walletIcon
          }}
        />
        <Drawer.Screen
          name="Payment"
          component={PayCrypto}
          options={{ drawerLabel: PayLabel, drawerIcon: payIcon }}
        />
        <Drawer.Screen
          name="BuyCrypto"
          component={BuyCrypto}
          options={{ drawerLabel: BuyLabel, drawerIcon: buyIcon }}
        />
        <Drawer.Screen
          name="ATM"
          component={LocateATM}
          options={{ drawerLabel: ATMLabel, drawerIcon: atmIcon }}
        />
        <Drawer.Screen
          name="News"
          component={LatestNews}
          options={{ drawerLabel: NewsLabel, drawerIcon: newsIcon }}
        />
        <Drawer.Screen
          name="Backup"
          component={BackupWallet}
          options={{ drawerLabel: backupLabel, drawerIcon: refreshIcon }}
        />
        <Drawer.Screen
          name="Settings"
          component={UserSettings}
          options={{ drawerLabel: SettingLabel, drawerIcon: settingIcon }}
        />
        <Drawer.Screen
          name="Exit"
          component={LatestNews}
          options={{ drawerLabel: ExitLabel, drawerIcon: exitIcon }}
        />
      </Drawer.Navigator>
    </NavigationContainer>
  );
}`

![Screenshot_1581433737](https://user-images.githubusercontent.com/25400839/74252770-6645cf80-4cee-11ea-9c86-dcaf592d13cd.png)

**Comment by satya164** [comment]
Closing due to no response.
