### ISSUE TITLE
Issue with react-native KeyboardAvoidView

### ISSUE THREAD

**Issue by asurare** [react-navigation/react-navigation#6823]
**Current Behavior**

I'm having some issues using the react-native keyboardAvoidView on the tabBar prop of the `createMaterialTopTabNavigator` :

This is working on the version `5.0.0-alpha.18` of `@react-navigation/material-top-tabs`.

On the latest version (5.0.0), it produced the following error :

![Simulator Screen Shot - iPhone 11 - 2020-02-11 at 10 32 22](https://user-images.githubusercontent.com/9867398/74254534-dce3cc80-4cf0-11ea-9042-e4cf5b5ebf3d.png)

Does anyone have any idea of how to fix this ?

**Expected Behavior**

The keyboard is correctly handled.

**How to reproduce**

```
import { KeyboardAvoidingView as RNKeyboardAvoidingView } from "react-native"

const KeyboardAvoidingView: FC<IProps> = ({ children }: IProps) => (
  <RNKeyboardAvoidingView
    {...props}
    behavior={(Platform.OS === "ios" && "padding") || undefined}
    keyboardVerticalOffset={
      (hasOffset && Platform.OS === "ios" && getHeaderSafeAreaHeight() + (hasNavBar ? 56 : 0)) ||
      undefined
    }
  />
)

<Tab.Navigator
        tabBarPosition="bottom"
        // tslint:disable-next-line:jsx-no-lambda
        tabBar={props => (
          <KeyboardAvoidView hasOffset={true}>
            // Functional component
          </KeyboardAvoidView>
        )}
        swipeEnabled={false}
      >
   // Tab screens definitons
</Tab.Navigator>
```

**Your Environment**

| software                            | version |
| ----------------------------------- | ------- |
| iOS or Android                      | 13.0
| @react-navigation/native            | 5.0.0
| @react-navigation/material-top-tabs | 5.0.0
| react-native-tab-view               | 2.12.0
| react-native                        | 0.61.5

**Comment by satya164** [comment]
Closing due to no response.
