### ISSUE TITLE
Tab Bar Navigator inside a Stack Navigator

### ISSUE THREAD

**Issue by dotfelixb** [react-navigation/react-navigation#6824]
**Current Behavior**
When a bottom tab is place inside a stack navigator, you get the error
"TypeError: undefined is not a function (near '...createRouter...')"

![Simulator Screen Shot - iPhone 8 - 2020-02-11 at 16 34 31](https://user-images.githubusercontent.com/6296750/74257979-7d37f200-4ced-11ea-8669-15d8da55c60a.png)

**How to reproduce**
const Stack = createStackNavigator();
const Tab = createBottomTabNavigator();

const AppTabs = () => {
  return (
    <Tab.Navigator>
      <Tab.Screen name="Home" component={HomeTab} />
      <Tab.Screen name="Profile" component={ProfileTab} />
    </Tab.Navigator>
  );
};

export default AppTabs;

 <NavigationContainer>
      <Stack.Navigator headerMode="none" initialRouteName="OnBoard"> 
        <Stack.Screen name="AppBottomTab" component={AppTabs} />
      </Stack.Navigator>
 </NavigationContainer>

**Environment**

| software                                          | version |
| -------------------------------- | ------- |
| @react-navigation/bottom-tabs | 5.0.1
| @react-navigation/native             | 5.0.0

**Comment by JogiPrasadPakki** [comment]
I have same issue

**Comment by dotfelixb** [comment]
Solved

**Comment by Aniie11** [comment]
How to solve this problem??
