### ISSUE TITLE
Missing horizontal prop on tabBarIcon v5

### ISSUE THREAD

**Issue by nartc** [react-navigation/react-navigation#6826]
**Current Behavior**
`tabBarIcon` on v5 doesn't have `horizontal` prop anymore.
https://reactnavigation.org/docs/en/bottom-tab-navigator.html#tabbaricon

**Expected Behavior**
Should have `horizontal` prop OR a note in Migration guide that `horizontal` prop has been removed. Any alternative?

| software                      | version |
| ----------------------------- | ------- |
| @react-navigation/native      | 5.0.1
| @react-navigation/bottom-tabs | 5.0.2

**Comment by satya164** [comment]
Can you describe your use case? Why do you need it?

**Comment by nartc** [comment]
@satya164 back in v4, I used `horizontal` prop to remove the `icon` from the `BottomTab`. Is there a different way to handle that in v5 now since the API is component based? Just want to make sure which approach I should take here.

**Comment by satya164** [comment]
Removing the icon was not an officially supported feature (even though it worked for your use case), so you might want to open a new feature request for that https://react-navigation.canny.io/feature-requests

For a work around, you can check the size of the icon which is different in horizontal mode.

**Comment by nartc** [comment]
Thanks. Do you think I can leverage `Dimensions` object from `react-native` instead of working with the `size` of the icon?

**Comment by satya164** [comment]
Sure, why not

**Comment by nartc** [comment]
Thanks for quick answer. Feature request submitted. Workaround is working. Closed :)
