### ISSUE TITLE
Warning for non-serializable values in navigation state when passing nested objects separately

### ISSUE THREAD

**Issue by aibtcare** [react-navigation/react-navigation#6827]
**Current Behavior**
When passing two objects (one of which is nested in the other) as route parameters in a navigate() call, I get this warning. If I pass only one of the objects at a time, I won't get this warning.

Full warning: "We found non-serializable values in the navigation state, which can break usage such as persisting and restoring state. This might happen if you passed non-serializable values such as function, class instances etc. in params. If you need to use functions in your options, you can use 'navigation.setOptions' instead."

- What code are you running and what is happening?

Simplified code that reproduces the error:
`const userObject = {
  id: "2sdif020a",
  name: "my name"
}`
`const familyObject = {
  userObjectArray: [userObject]
}`
And then pass the userObject and familyObject as parameters to the route:
`navigation.navigate('MyFamily', {userObject, familyObject})`

If I set `familyObject.userObjectArray = []`, I no longer receive the error. When nesting the `userObject` within `userObjectArray`, and then passing the `userObject` as it's own parameter seems to cause the error.

- Include a screenshot or video if it makes sense.

**Expected Behavior**
I shouldn't be getting this warning since I think the parameter object should be serializable

- What do you expect should be happening?
- Include a screenshot or video if it makes sense.

**How to reproduce**
Nesting an object within a parameter and then passing it as a second parameter seems to reproduce this issue consistently

- You must provide a way to reproduce the problem. If you are having an issue with your machine or build tools, the issue belongs on another repository as that is outside of the scope of React Navigation.
- Either re-create the bug on [Snack](https://snack.expo.io) or link to a GitHub repository with code that reproduces the bug.
- Explain how to run the example app and any steps that we need to take to reproduce the issue from the example app.
- Keep the repro code as simple as possible, with the minimum amount of code required to repro the issue.
- Before reporting an issue, make sure you are on latest version of the package.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or [Android]                 |9
| @react-navigation/native       |5.0.0
| @react-navigation/stack        |5.0.0
| react-native-gesture-handler   |1.5.6
| react-native-safe-area-context |0.7.0
| react-native-screens           |2.0.0-beta.2
| react-native                   |0.61.5
| expo                           |
| node                           |13.8.0
| [npm] or yarn                    |6.13.7

**Comment by aibtcare** [comment]
My bad, submitted the post before I was done writing it.

**Comment by anam-hossain** [comment]
It is happening with me with the header component:

```js
function HomeStack() {
  return (
    <Stack.Navigator
      initialRouteName="Home"
    >
      <Stack.Screen
        name="Home"
        component={HomeSreen}
        options={{ header: ({ navigation }) => <HomeHeader navigation={navigation} /> }}
      />
      <Stack.Screen
        name="List"
        component={ListScreen}
        options={{ header: ({ navigation }) => <ListHeader navigation={navigation} /> }}
      />
    </Stack.Navigator>
  );
}
```

**Comment by elfstyle** [comment]
> const userObject = { id: "2sdif020a", name: "my name" }
> const familyObject = { userObjectArray: [userObject] }
> navigation.navigate('MyFamily', {userObject, familyObject})

This error is happening because the function `isSerializableWithoutCircularReference` from react-`navigation/packages/core/src/isSerializable.tsx` adds all the objects of the navigation state into `seen = new Set<any>()` and then cheks 
`  if (seen.has(o)) {
    return false;
  }`

Every duplicated object in the navigation state will cause a non-serializable warning.

**Comment by anam-hossain** [comment]
@satya164 Still not fix for me. I am getting the following warning but not finding the source.

```
We found non-serializable values in the navigation state, which can break usage such as persisting and restoring state. This might happen if you passed non-serializable values such as function, class instances etc. in params. If you need to use components with callbacks in your options, you can use 'navigation.setOptions' instead. See https://reactnavigation.org/docs/en/header-buttons.html#header-interaction-with-its-screen-component for docs.
```

Here is my navigation code:

```
function HomeStack() {
  return (
    <Stack.Navigator
      initialRouteName="Home"
      headerMode="none"
    >
      <Stack.Screen
        name="Home"
        component={HomeSreenContainer}
      />
      <Stack.Screen
        name="List"
        component={ListScreen}
      />
    </Stack.Navigator>
  );
}

function FavouriteStack() {
  return (
    <Stack.Navigator
      initialRouteName="Favourite"
      headerMode="none"
    >
      <Stack.Screen
        name="Favourite"
        component={FavouriteScreen}
      />
    </Stack.Navigator>
  );
}

function NewsStack() {
  return (
    <Stack.Navigator
      initialRouteName="News"
      headerMode="none"
    >
      <Stack.Screen
        name="News"
        component={NewsScreen}
      />
    </Stack.Navigator>
  );
}

function MiscellaneousStack() {
  return (
    <Stack.Navigator
      initialRouteName="Miscellaneous"
      headerMode="none"
    >
      <Stack.Screen
        name="Miscellaneous"
        component={MiscellaneousScreen}
      />
      <Stack.Screen
        name="Settings"
        component={SettingsScreen}
      />
      <Stack.Screen
        name="About"
        component={AboutScreen}
      />
    </Stack.Navigator>
  );
}

const Tab = createBottomTabNavigator();

function TabNavigator() {
  return (
    <Tab.Navigator
      screenOptions={({ route }) => ({
        tabBarIcon: ({ focused, color }) => {
          const routeName = route.name;

          let iconName;

          if (routeName === "HomeTab") {
            iconName = `home`;
          } else if (routeName === "NewsTab") {
            iconName = `th-list`;
          } else if (routeName === "FavouriteTab") {
            iconName = `bookmark`;
          } else if (routeName === "SettingsTab") {
            iconName = `bars`;
          }

          return <Icon name={iconName} size={30} color={color} solid={focused} light={!focused} />;
        }

      })}
      tabBarOptions={{
        activeTintColor: colors.brand,
        inactiveTintColor: "gray",
        showLabel: false,
        style: {
          backgroundColor: colors.brandLightest,
        }
      }}
    >
      <Tab.Screen name="HomeTab" component={HomeStack} />
      <Tab.Screen name="NewsTab" component={NewsStack} />
      <Tab.Screen name="FavouriteTab" component={FavouriteStack} />
      <Tab.Screen name="SettingsTab" component={MiscellaneousStack} />
    </Tab.Navigator>
  );
}

function AppNavigator() {
  return (
    <Stack.Navigator
      initialRouteName="Main"
      mode="modal"
      headerMode="none"
      screenOptions={{
        cardStyle: { backgroundColor: 'transparent' }
      }}
    >
      <Stack.Screen
        name="Main"
        component={TabNavigator}
      />
      <Stack.Screen
        name="PickLanguageModal"
        component={PickLanguageScreen}
        options={{
          headerTransparent: true,
        }}
      />
    </Stack.Navigator>
  );
}

export default AppNavigator;
```

**Comment by muhammadwafa** [comment]
This actually happens when you pass a function to the screen you navigate

**Comment by muhammadwafa** [comment]
Why is closed still happens in v 5.03

**Comment by tapz** [comment]
I can confirm that this still happens in v 5.0.3.

**Comment by muhammadwafa** [comment]
I used other way.

When I come back I dont call .goBack() function instead I used .navigate() and with params needed.

**Comment by aibtcare** [comment]
> This actually happens when you pass a function to the screen you navigate


> I can confirm that this still happens in v 5.0.3 when passing a function in the navigation state params.

I don’t think that’s recommended because I don’t think sending functions or instances of a class is considered serializable.

**Comment by vincicat** [comment]
> This actually happens when you pass a function to the screen you navigate

A duplicate object reference will cause this warning too (as it is considered as circular reference).

To developer: it is good to see a warning when something may break the navigation state, but it needs to include more clue (object's JSON string etc) for us to pinpoint the source

**Comment by jbromberg** [comment]
How are we expected to access necessary functions across different navigation screens such as state setting functions?

**Comment by satya164** [comment]
https://reactnavigation.org/docs/en/troubleshooting.html#i-get-the-warning-we-found-non-serializable-values-in-the-navigation-state

**Comment by GuleriaAshish** [comment]
I want to navigate from a screen with a function in params and on coming back i want that function to called. So how can i do this because in the newer versions i am unable to send a function in the parameters .

**Comment by celucode** [comment]
I am having this problem too. I am passing a function, so I can return an object on goBack(); Is any solution for this?

**Comment by tapz** [comment]
I understand the idea or this warning, but a single screen cannot be restored without restoring the whole path with the callback function. If React Navigaton is not able to do that, then no restore should be used by default and this kind of warnings displayed.

**Comment by perrosnk** [comment]
Has anyone found a solution? Why is this issue closed?

**Comment by lludovic** [comment]
I have the same problem.
I was previously use react-navigation 4x, everything worked fine. But now with 5x, I have this ugly warning message and documentation is not clear about the way to handle it.I have the same problem.
I was previously use react-navigation 4x, everything work fine. But now with 5x I have this ugly warning message and doc is not clear about the way to handle it

**Comment by AhmadLpsn** [comment]
i had the same problem 
in my case happens when i set fun as parameter 
solution : i use global var and update i from inside the component by using   useEffect
`
let onSave=()=>{}
const myCom=props=>{
    const save=useCallback( ()=>{
        //.... some logic 
    })
    useEffect(()=>{
        onSave=save;
    },[save]);
}
myCom.screenOptions=props=>{
return ({
    headerRight:()=>
    <HeaderButtons  HeaderButtonComponent={(props)=>
            <HeaderButton {...props} 
            />} >
        <Item title="save"   iconName="ios-save" onPress={onSave}/>
    </HeaderButtons>,
})
}

`

**Comment by YahiaBadr** [comment]
any updates? i am tried to send my function using setOptions instead of setParams but i can not access it in the other component, anyone has a solution?

**Comment by rptoma** [comment]
The solution from the documentation seems like such a bad idea for callbacks.
This basically means that you need to store all the callback functions and all the things you want to pass to a child screen in a global store based on some uuids.
This seems such an overkill and changes the way you structure your app entirely.

**Comment by rptoma** [comment]
Here's what the documnetation says: https://reactnavigation.org/docs/troubleshooting/

> To pass a callback to use in a header button. This can be achieved using navigation.setOptions instead. See the guide for header buttons for examples.
To pass a callback to the next screen which it can call to pass some data back. You can usually achieve it using navigate instead. See the guide for params for examples.
To pass complex data to another screen. Instead of passing the data params, you can store that complex data somewhere else (like a global store), and pass an id instead. Then the screen can get the data from the global store using the id.

**Comment by satya164** [comment]
The documentation also says:

> If you don't use state persistence or deep link to the screen which accepts functions in params, then the warning doesn't affect you and you can safely ignore it.

You're free to pass anything in params, but then it's impossible to support use cases like state persistence or deep linking if those things cannot be serialized, and the warning exists to make sure that you are aware of it. It's also why it's a warning that you can ignore and not an error.

> storing all the callback functions based on some uuid in a global store is pure overkill 

Also like the documentation says:

> To pass a callback to the next screen which it can call to pass some data back. You can usually achieve it using navigate instead. See the guide for params for examples.

It doesn't suggests to store callbacks in a global store. "complex data" doesn't mean callbacks, it means complex data that cannot be serialized. Use `navigate` instead to pass data back to previous screen like it suggests.

Or like just ignore the warning following the steps that's mentioned in the documentation if you don't care about the use cases.

> I can already see how they'll make another update that will make us refactor our apps again, just like every update they roll out.

You're free not to use React Navigation if you're going to always assume bad faith in everything we do. I literally spent months working on it because people wanted features that wasn't possible with previous architecture, but thanks.

I'm sorry that the documentation isn't perfect, but it's an Open Source project, you can send pull requests to improve the documentation.

**Comment by rptoma** [comment]
How should one use navigate if the child screen can be presented from multiple other screens? Thank you. goBack doesn't allow sending parameters.

**Comment by satya164** [comment]
Pass the name of the screen as a param so the new screen knows where to navigate back.

**Comment by alexpchin** [comment]
I have recently upgraded from react-navigation v4 to v5. I had a global modal which I used to pass a function to. This now shows a warning. Is there any way to pass a function in params?

```js
import PropTypes from 'prop-types';

import NavigationService from 'src/stacks/NavigationService';
import i18n from 'i18next';
import * as R from 'src/constants/routes';
const t = i18n.t.bind(i18n);

const AlertCustom = ({
  cancelAction,
  cancelLabel,
  confirmAction,
  confirmLabel,
  contentComponent,
  error,
  hideCancel,
  hideConfirm,
  isBottom,
  swipeDirection,
  text,
  title,
}) => {
  const _cancelAction = async () => {
    if (typeof cancelAction === 'function') {
      return await cancelAction();
    } else {
      return () => {};
    }
  };

  const _confirmAction = async () => {
    if (typeof confirmAction === 'function') {
      return await confirmAction();
    } else {
      return () => {};
    }
  };

  const _parseErrorMessage = (error) => {
    return error
      ? error.message === 'string'
        ? error.message
        : t('alerts.tryAgain.text')
      : null;
  };

  return NavigationService.navigate(R.CUSTOM_MODAL, {
    cancelAction: _cancelAction, // Causes an issue in v5
    cancelLabel: cancelLabel ?? t('ui.buttons.dismiss'),
    confirmAction: _confirmAction, // Causes an issue in v5
    confirmLabel: confirmLabel ?? t('ui.buttons.confirm'),
    contentComponent: contentComponent,
    hideCancel: hideCancel,
    hideConfirm: hideConfirm,
    isBottom: isBottom,
    swipeDirection: swipeDirection,
    text: text || _parseErrorMessage(error),
    title: title,
  });
};

AlertCustom.defaultProps = {
  hideCancel: false,
  hideConfirm: false,
  isBottom: false,
};

AlertCustom.propTypes = {
  cancelAction: PropTypes.func,
  cancelLabel: PropTypes.string,
  confirmAction: PropTypes.func,
  confirmLabel: PropTypes.string,
  contentComponent: PropTypes.object,
  error: PropTypes.object,
  hideCancel: PropTypes.bool.isRequired,
  isBottom: PropTypes.bool.isRequired,
  swipeDirection: PropTypes.string,
  text: PropTypes.string,
  title: PropTypes.string.isRequired,
};

export { AlertCustom };
```

**Comment by ganzp87** [comment]
ChatList.js
navigation.navigate("ChatDetail", {setSkip}) // setSkip is function

and When I go back to ChatList from ChatDetail, I want to trigger setSkip function.

but, When I pass the function to ChatDetail, the yellow warning appear. I think that it's irritating thing.

**Comment by AbhiShrek** [comment]
Why this issue is CLOSED ? 
It's still happening on passing function as a param to other screen. 
Is there any solution yet ?

**Comment by satya164** [comment]
The reasons are already documented on the website along with instructions on how to to suppress it, which should gives you an idea **if you actually read the warning**.

I'm locking this issue to prevent unnecessary spam from people not reading warnings when it's already explained. Of course the documentation can always be improved to make it more clear and add more examples for different use cases. Feel free to send pull requests for that to https://github.com/react-navigation/react-navigation.github.io
