### ISSUE TITLE
Android does not respect any styles given to custom header

### ISSUE THREAD

**Issue by akshit5230** [react-navigation/react-navigation#6830]
**Current Behavior**

In iPad the styles are working and i got the proper UI but when I ran it on an android Tablet, all the components are over each other on the left.

**Expected Behavior**

Styles should be respected by android tablet

**How to reproduce**

```
function MainHeader() {
return (
    <View style={{
      height: 80, flex: 1, flexDirection: 'row', marginTop: 20
    }}>
...many components
</View>
)}

function MainStack() {
  return (
    <Stack.Navigator screenOptions={{
      header: MainHeader
    }}>
      <Stack.Screen name="Home" component={HomeScreen} />
    </Stack.Navigator>
  )
}

export default AppContainer = () => {
  return (
    <NavigationContainer>
      {MainStack()}
    </NavigationContainer>
  )
}
```
**Your Environment**

| software        Android               | version | 10
| ------------------------------ | ------- |
| Android  Pixel C emulator with Android Q          |
| @react-navigation/native       |"^5.0.0",
| @react-navigation/stack        | "^5.0.0"
| react-native-gesture-handler   |"^1.5.6"
| react-native-safe-area-context |"^0.7.2"
| react-native-screens           |"^2.0.0-beta.2"
| react-native                   |"0.61.5"
| node                           |11.2.0
| npm or yarn                    | 6.13.6

**Comment by satya164** [comment]
Closing due to no response.
