### ISSUE TITLE
Not able to access Inner Drawer Navigator from Outer Stack Navigator

### ISSUE THREAD

**Issue by akshit5230** [react-navigation/react-navigation#6831]
**Current Behavior**

undefined is not an object (evaluating '_native.DrawerActions.toggleDrawer')
when dispatched action from parent stack navigator 

**Expected Behavior**

child drawer should receive toggle action when dispatched toggle action from parent stack navigator

**How to reproduce**

```
function MainDrawer() {
  return (
    <Drawer.Navigator
      initialRouteName="Overview"
      drawerType="slide"
      overlayColor="transparent"
      drawerStyle={{
        
      }}
      drawerContent={props => <CustomDrawerContent {...props} />}
    >
      <Drawer.Screen name="SomeScreen" component={SomeScreen} />
    </Drawer.Navigator>
  )
}

function CustomDrawerContent(props) {
  return (
      <DrawerContentScrollView {...props}>
        <DrawerItem
          label={strings.some}
          onPress={() => Linking.openUrl('https://mywebsite.com/help')}
        />
      </DrawerContentScrollView>
  );
}

function MainHeader() {
  return (
    <View style={{
      height: 80, flex: 1, flexDirection: 'row', marginTop: 20
    }}>
..........................................
    </View>
  )
}

function MainStack() {
  return (
    <Stack.Navigator screenOptions={{
      header: MainHeader
    }}>
      <Stack.Screen name="Home" component={SomeStack} />
    </Stack.Navigator>
  )
}

function SomeStack({ navigation }) {
  return (
    <Stack.Navigator screenOptions={{
      headerLeft: () => <TouchableOpacity activeOpacity={0.9} onPress={() => navigation.dispatch(DrawerActions.toggleDrawer())} style={{
        padding: 10, marginTop: -20
      }}>
        <Image source={images.hamburger} />
      </TouchableOpacity>
    }}>
      <Stack.Screen name="Some" component={MainDrawer} />
    </Stack.Navigator>
  )
}

export default AppContainer = () => {
  return (
    <NavigationContainer>
      {MainStack()}
    </NavigationContainer>
  )
}
```

**Your Environment**

| software iOS | version | 13
| iPad |
| @react-navigation/native |"^5.0.0",
| @react-navigation/stack | "^5.0.0"
| react-native-gesture-handler |"^1.5.6"
| react-native-safe-area-context |"^0.7.2"
| react-native-screens |"^2.0.0-beta.2"
| react-native |"0.61.5"
| node |11.2.0
| npm or yarn | 6.13.6

**Comment by satya164** [comment]
https://reactnavigation.org/docs/en/nesting-navigators.html#navigator-specific-methods-are-available-in-the-navigators-nested-inside

**Comment by smanzini** [comment]
Hey @akshit5230  do you have any update on this?
It happens also to me!
Many thanks!

**Comment by akshit5230** [comment]
@smanzini you can try using dangerouslyGetParent to listen to the parent's events.
check this:
https://reactnavigation.org/docs/nesting-navigators/#nested-navigators-dont-receive-parents-events
