### ISSUE TITLE
Mixing custom header and build-in header won't render properly on iOS

### ISSUE THREAD

**Issue by dkulagin** [react-navigation/react-navigation#6832]
**Current Behavior**

There is a mix of two types of headers within a Stack.Navigator:

1. Custom header set to a component:

```
<Stack.Screen
  options={({route}) => ({
                   header: () => (<View
                            style={{backgroundColor: "#DD4124", width: "100%", paddingTop: getStatusBarHeight()}}>
                            <SearchBox />
                        </View>)
                    })}
                    name="Content"
                    component={ContentScreen}                  
                />
```
2. Built-in header:
```
<Stack.Screen
                    options={({route}) => ({
                        headerTitle: route.params?.query ?? '',
                        headerBackTitle: '',
                        headerTruncatedBackTitle: ''
                    })}
                    name="Switch"
                    component={SwitchScreen}/>
```

When running on iOS and the app navigates to the Switch screen, the rendering doesn't go right keeping part of the Content screen header visible.

**Content screen**

![photo_2020-02-12_10-41-20 resized](https://user-images.githubusercontent.com/2980869/74314510-9771de80-4d86-11ea-9c24-b824005c3606.jpg)

**Switch screen (bugged) -- see: the bottom part of the SearchBox is still visible**

![photo_2020-02-12_10-41-21 resized](https://user-images.githubusercontent.com/2980869/74314517-9c369280-4d86-11ea-9608-d999dd2a8d9b.jpg)

**Expected behavior**

The previous screen' header is completely erased and replaced with a new one (works that way on Android).

**Your Environment**

```
  "dependencies": {
    "@react-native-community/masked-view": "0.1.5",
    "@react-navigation/core": "^5.0.0",
    "@react-navigation/native": "^5.0.0",
    "@react-navigation/stack": "^5.0.0",
    "expo": "^36.0.2",
    "npm": "^6.13.7",
    "react": "^16.12.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz",
    "react-native-gesture-handler": "~1.5.0",
    "react-native-reanimated": "~1.4.0",
    "react-native-safe-area-context": "0.6.0",
    "react-native-safe-area-view": "^1.0.0",
    "react-native-screens": "2.0.0-alpha.12",
    "react-native-status-bar-height": "^2.4.0",
    "yarn": "^1.22.0"
  }
```

**Comment by satya164** [comment]
> When using a custom header, it's recommended set the `headerMode` prop on the navigator to `screen` so that you don't have to implement animations.

https://reactnavigation.org/docs/en/stack-navigator.html#header

**Comment by mstaniewski** [comment]
Seems like there's another issue with custom header in one of many stack screens.

Before setting `headerMode="screen"`
![Screenshot 2020-02-14 at 16 46 30](https://user-images.githubusercontent.com/11744682/74545748-b8cef800-4f49-11ea-860d-0ca55cba8e32.png)

After setting `headerMode="screen"`
![Screenshot 2020-02-14 at 16 46 42](https://user-images.githubusercontent.com/11744682/74545792-c84e4100-4f49-11ea-8687-c4e599bb3bf4.png)

Docs states that it's a good practice to set height for header, so I did:
```
<NavigationContainer>
        <Stack.Navigator
          screenOptions={{
            headerStyle: {
              height: 100,
            },
          }}
          headerMode="screen">
          <Stack.Screen
            options={{
              header: Header,
              headerStyle: {
                height: 100,
              },
            }}
            name="App"
            component={AppFlow}
          />
          <Stack.Screen
            options={{header: Header, headerShown: false}}
            name="Auth"
            component={AuthNavigator}
          />
          <Stack.Screen
            options={{header: Header, headerShown: false}}
            name="Attraction"
            component={AttractionNavigator}
          />
        </Stack.Navigator>
```

Neither `screenOptions.headerStyle` nor `options.headerStyle` is being applied to `HeaderContainer`. No style displayed in inspector.

It's a top most navigator in my app

**Comment by dkulagin** [comment]
> Docs states that it's a good practice to set height for the header

I found it not working out that great due to different pixel ratio across different devices. E.g. setting height equal to 80px seems to work fine for iPhone 8, but it renders badly on the iPhone 11 Pro Max. What I actually need is for RN to set the header height consistently across different screens in the stack applying the "max-height" strategy.

For now, I will try to set my secondary screen header's height programmatically to match the primary screen header's height as a workaround.

**Comment by bikowalczyk** [comment]
> Seems like there's another issue with custom header in one of many stack screens.
> 
> Before setting `headerMode="screen"`
> ![Screenshot 2020-02-14 at 16 46 30](https://user-images.githubusercontent.com/11744682/74545748-b8cef800-4f49-11ea-860d-0ca55cba8e32.png)
> 
> After setting `headerMode="screen"`
> ![Screenshot 2020-02-14 at 16 46 42](https://user-images.githubusercontent.com/11744682/74545792-c84e4100-4f49-11ea-8687-c4e599bb3bf4.png)
> 
> Docs states that it's a good practice to set height for header, so I did:
> 
> ```
> <NavigationContainer>
>         <Stack.Navigator
>           screenOptions={{
>             headerStyle: {
>               height: 100,
>             },
>           }}
>           headerMode="screen">
>           <Stack.Screen
>             options={{
>               header: Header,
>               headerStyle: {
>                 height: 100,
>               },
>             }}
>             name="App"
>             component={AppFlow}
>           />
>           <Stack.Screen
>             options={{ headerShown: false}}
>             name="Auth"
>             component={AuthNavigator}
>           />
>           <Stack.Screen
>             options={{ headerShown: false}}
>             name="Attraction"
>             component={AttractionNavigator}
>           />
>         </Stack.Navigator>
> ```
> 
> Neither `screenOptions.headerStyle` nor `options.headerStyle` is being applied to `HeaderContainer`. No style displayed in inspector.
> 
> It's a top most navigator in my app

Hi, Have you found out a solution to this problem by any chance? I'm facing the same issue. Setting headerMode="screen" is cutting of the Title of my custom header
