### ISSUE TITLE
CommonActions not found/available in latest version '@react-navigation/native'

### ISSUE THREAD

**Issue by singheshadev** [react-navigation/react-navigation#6833]
**Current Behavior**

- I am try to implement react-navigation 5

**Expected Behavior**
In Library @react-navigation/native' not found **CommonActions** property.

**How to reproduce**

- Simple install latest version of /native library
- And import { CommonActions } from '@react-navigation/native';
- CommonActions not found in library
- I have follow this documentation - https://reactnavigation.org/docs/en/upgrading-from-4.x.html

**Your Environment**

| react-native                   |

**Comment by Kroniac** [comment]
I think it's cache issue. Try, **npm start -- --reset-cache**
If not then try deleting node_modules folder and **npm install** again.

**Comment by Oscar3000** [comment]
I am experiencing this issue as well right now. I have been using react-navigation v5 for two weeks now and I haven't had this issue but today I decided to delete node_modules/ (regretting this decision) and install my packages again and boom, this happened.
![image](https://user-images.githubusercontent.com/17434695/74335611-3c031900-4da5-11ea-98ae-d29fb55ac59a.png). 

Tried **rm -rf node_modules/** then **npm start --reset-cache**. still the same.

**Comment by Oscar3000** [comment]
The solution that worked was restating my system!

**Comment by Kroniac** [comment]
It was definitely the cache issue. Here it happened when your **@react-navigation/native** package got upgraded to version **5.0.2** from 5.0.0 or 5.0.1 when you did npm install. Most of the time -- reset cache should work but something must have went wrong with it in your case. I think restarting the system always work when nothing works.

**Comment by nobledm** [comment]
I was experiencing the same issue after updating my node_modules this morning. Cleaning npm cache didn't work and just broke the expo metro builder, restarting my system didn't work, removing node_modules and reinstalling didn't change anything either.

What did work was specifically cleaning out Expo's cache: **expo r -c**

**Comment by singheshadev** [comment]
Issue resolve with
Remove old install package then install new package for react-navigation-5
"react-navigation": "^4.0.5",
"react-navigation-stack": "^2.1.0",
"react-navigation-tabs": "^2.5.2",
