### ISSUE TITLE
Get navigation ref before initial route renders

### ISSUE THREAD

**Issue by HasanAlyazidi** [react-navigation/react-navigation#6834]
**Current Behavior**

`NavigationContainer`'s ref is fully available after rendering the initial route name (exactly after componentDidMount).

**Expected Behavior**

1. Get `NavigationContainer`'s ref ready
2. Render initial route

Then do something with navigation ref immediately

**How to reproduce**

[Snack](https://snack.expo.io/@hasan/app-containers-·-react-navigation)

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Android
| @react-navigation/native       | ^5.0.1
| react-native                   | 0.61.5
| expo                           | N/A
| node                           | v10.18.0
| npm or yarn                    | yarn

**Comment by satya164** [comment]
That's not how a ref works. You can't get a reference until there's something which adds the reference.
