### ISSUE TITLE
Swap icon and label order in DrawerItem

### ISSUE THREAD

**Issue by andergtk** [react-navigation/react-navigation#6836]
**Current Behavior**

Before v5 of react-navigation we could use `flexDirection: 'row-reverse'` to invert the items order inside `<DrawerItem />`. Now this isn't possible because the components are wrapped by a `<ToutchableItem />` that has no way to customize his styles.

Example of how it was done before v5:

```javascript
createDrawerNavigator({
  // ...
}, {
  contentOptions: {
    itemStyle: {
      flexDirection: 'row-reverse',
    }
  }
})
```

**Expected Behavior**

A way to position the icon node after the label like using `flexDirection: 'row-reverse';` on his wrapper element or any alternative.

**Comment by WoLewicki** [comment]
Sorry, but we don't support this use case. You should create your own component like there: https://reactnavigation.org/docs/en/drawer-navigator.html#drawercontent 
If you have a compelling use case then please create a feature request in canny: https://react-navigation.canny.io/

**Comment by RickameCua** [comment]
![Capture20](https://user-images.githubusercontent.com/28285289/118954421-535d8880-b990-11eb-9c52-d048d9187b4a.PNG)

instead of adding `icon` property. I added the icon inside the `label`.
Maybe this wasn't possible on the versions before but now you can.
