### ISSUE TITLE
V5 : header does not receives navigation props

### ISSUE THREAD

**Issue by ali-sardari** [react-navigation/react-navigation#6837]
V5 : My headerLeft does not receives navigation props. here is my code:
<Stack.Navigator>
            <Stack.Screen
                options={{
                    headerLeft: props => <Button
                        onPress={() => {
                            console.log('props', props)
                        }}
                    />
                }}
                name="Home"
                component={Home}/>
        </Stack.Navigator>

**MyEnvironment**

Android
@react-navigation/native": "^5.0.2
@react-navigation/stack": "^5.0.2
react-native-screens": "^2.0.0-beta.2
react-native": "0.61.5

**Comment by WoLewicki** [comment]
Is it native-stack or stack? Please provide a snack if you can repro it.

**Comment by giautm** [comment]
hey @ali-sardari , `options` props can be a function. You can receive the `navigation` & `route` via it.
