### ISSUE TITLE
V5: Cleanup is not a function

### ISSUE THREAD

**Issue by rnnyrk** [react-navigation/react-navigation#6839]
**Current Behavior**

I'm using a `createMaterialTopTabNavigator` and a `createBottomTabNavigator`, when navigating between them I get the following error:
![IMG_91C78F18D48D-1](https://user-images.githubusercontent.com/4519142/74350654-4e398300-4db6-11ea-89c0-a7bccce13144.jpeg)

I have a nested navigators as following;`createStackNavigator` > `createStackNavigator` > `createBottomTabNavigator` > `createStackNavigator` > `createMaterialTopTabNavigator`

Any idea what I can do about this? 

**Your Environment**
| software                      | version |
| ----------------------------- | ------- |
| iOS or Android                | Both
| @react-navigation/native      | 5.0.2
| @react-navigation/bottom-tabs | 5.0.2
| react-native-screens          | 2.0.0-beta.2
| react-native                  | 0.61.5
| node                          | v12.13.0
| npm or yarn                   | 6.12.0

**Comment by gaishimo** [comment]
I experienced a similar error. (@react-navigation/core: 5.1.4)

```js
TypeError: cleanup is not a function. (In 'cleanup()', 'cleanup' is null)
```

 
The cause of my error is the code returns `null` in `useCallback`.


```js
useFocusEffect(
  useCallback(() => {
    // some code
    return null
  }, [field1]),
)
```


Does your code return a `promise` object in it?

**Comment by rnnyrk** [comment]
Sorry about the delayed response. Indeed I accidentally returned a promise to the `useFocusEffect`. Fixed the issue. Thanks for getting back to me.
