### ISSUE TITLE
[BUG] Doc asserts invalid🐞

### ISSUE THREAD

**Issue by DonaldDai** [react-navigation/react-navigation#6840]
Hi~I'am walking through your doc at [Opening a full-screen modal](https://reactnavigation.org/docs/en/1.x/modal.html)，and there is an image being invalid(as showing bellow)

![doc](https://cdn-std.droplr.net/files/acc_513938/jv9fYf)

![error page](https://cdn-std.droplr.net/files/acc_513938/FAjaPD)

I know that the version of 1.x is no longer supported, but, for some reason, the App of my company is still using it. I will so thankful, if someone can fix it.

**Comment by WoLewicki** [comment]
Thanks for submitting an issue! It should be mentioned in react-navigation.github.io repo because it concerns docs. It should be fixed now.
