### ISSUE TITLE
[RN 4] Transition of closing nested stack is not smooth while nested stack is hiding Bottom Tab 

### ISSUE THREAD

**Issue by zxccvvv** [react-navigation/react-navigation#6841]
**Current Behavior**

In attachment below, the close transition is not smooth, seems like last animation waiting for original tab height before gone

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/19633881/74354010-4f39d700-4ded-11ea-832a-809eae0ca271.gif)

**Expected Behavior**

Should just run without waiting

**How to reproduce**

```
import React from 'react';
import { createAppContainer } from "react-navigation";
import { createStackNavigator } from 'react-navigation-stack';
import { createBottomTabNavigator } from 'react-navigation-tabs';
import RN from 'react-native';

class SimpleScreen extends React.Component{
  render(){
    return(
      <RN.View style={{flex:1, justifyContent:'center', alignItems:'center', backgroundColor:this.props.navigation.getParam('color', 'white')}}>
        <RN.Button title={'Go To Nested Stack'} onPress={()=>this.props.navigation.push('SimpleScreen', {color:'red'})}/>
      </RN.View>
    )
  }
}

const StackBuggy = createStackNavigator({
  SimpleScreen:SimpleScreen
},{
  headerMode:'none',
  navigationOptions:({navigation})=>({
    tabBarVisible:navigation.state.index<1
  })
})

const TabBuggy = createBottomTabNavigator({
  Tab1:StackBuggy,
  Tab2:StackBuggy
})

export default createAppContainer(TabBuggy);
```

**Your Environment**

| software                      | version |
| ----------------------------- | ------- |
| iOS or Android                | Android
| @react-navigation/native      | "react-navigation": "^4.1.1",
| @react-navigation/bottom-tabs | "react-navigation-tabs": "^2.7.0"
| react-native-screens          | "react-native-screens": "^2.0.0-beta.2"
| react-native                  | 0.61.5

**Comment by satya164** [comment]
Reorganize your navigators to have stack at root instead of hiding the tab bar.

**Comment by zxccvvv** [comment]
@satya164 i don't get it what you mean, did you mean i should wrap the tabbar to stack and put this stack to appContainer?

**Comment by satya164** [comment]
https://reactnavigation.org/docs/en/nesting-navigators.html#parent-navigators-ui-is-rendered-on-top-of-child-navigator

https://reactnavigation.org/docs/en/screen-options-resolution.html

**Comment by zxccvvv** [comment]
Hi @satya164 ,
I've updated my navigation as below:
```
const HomeTab= createStackNavigator({
  SimpleScreen:SimpleScreen
},{
  headerMode:'none'
})

const NestedHome= createStackNavigator({
  Home1:SimpleScreen,
  Home2:SimpleScreen
},{
  headerMode:'none'
})

const TabBuggy = createBottomTabNavigator({
  Tab1:HomeTab,
  Tab2:HomeTab,
  HomeStack:NestedHome
})
```

but i've a problem with these pattern,

How do i navigate from `Tab1`, to `Home2`?
usually i used:
```
this.props.navigation.navigate('NestedHome');
this.props.navigation.navigate('Home2');
```

but in this case `Home1` would show and calling an API

what is the best method about this case?
