### ISSUE TITLE
Modal shifts the background screen up on Android. [gif attached]

### ISSUE THREAD

**Issue by GollyJer** [react-navigation/react-navigation#6842]
This is with the most up to date versions of `react-navigation 5` and it's sub components as of 02-12-2020.

I have a simple stack.
```javascript
import { NavigationContainer } from '@react-navigation/native';
import { createStackNavigator } from '@react-navigation/stack';
import React from 'react';

import * as screens from '../screens/unauthenticated-screens';

const Stack = createStackNavigator();
const NavUnauthenticated = () => (
  // console.log('TRIGGERED NavUnauthenticated');

  <NavigationContainer>
    <Stack.Navigator mode="modal" headerMode="none">
      <Stack.Screen name="landing" component={screens.LandingScreen} />
      <Stack.Screen
        name="auth"
        component={screens.AuthScreen}
        options={{ cardStyle: { backgroundColor: 'transparent' } }}
      />
    </Stack.Navigator>
  </NavigationContainer>
);
```
It works as expected on iOS. The modal rises from the bottom and the background screen doesn't move.
However, on Android the entire background screen shifts up and an equivalently sized white section comes into view at the bottom.
<img src="https://user-images.githubusercontent.com/689204/74408826-3d0a6980-4dea-11ea-8f77-32681045bf2b.gif" width="350">

**Comment by satya164** [comment]
https://reactnavigation.org/docs/en/stack-navigator.html#transparent-modals

**Comment by GollyJer** [comment]
@satya164 That is the exact code I used... I just took out the animation for simplicity of this example. 
Have you tried it? For me the example in the docs has the exact same problem.

**Comment by satya164** [comment]
> I just took out the animation for simplicity of this example. 

That's the most important part that you took out. Of course it's gonna shift up, that's the default animation. That's why you need to override it.

**Comment by GollyJer** [comment]
Gotcha... that makes sense. Thanks @satya164.
I was looking to make a "rise up from bottom" modal in the native style. Where I got confused is doing it in Snack. **The Android emulator doesn't shift background screen**, but if you open it on a real Android device (at least my Pixel 3), it does shift the background.
[React Navigation v5 - JS Modal (snack)](https://snack.expo.io/@gollyjer/react-navigation-v5---js-modal)

For future searchers... at the end of the day I was able to get the exact behavior I wanted by switching to the `@react-navigation/native-stack`.
```javascript
import { NavigationContainer } from '@react-navigation/native';
import { createNativeStackNavigator } from '@react-navigation/native-stack';
import React from 'react';

import * as screens from '../screens/unauthenticated-screens';

const Stack = createNativeStackNavigator();
const NavUnauthenticated = () => (
  // console.log('TRIGGERED NavUnauthenticated');

  <NavigationContainer>
    <Stack.Navigator screenOptions={{ headerShown: false }}>
      <Stack.Screen name="landing" component={screens.LandingScreen} />
      <Stack.Screen
        name="auth"
        component={screens.AuthScreen}
        options={{
          stackPresentation: 'transparentModal',
          contentStyle: { backgroundColor: 'transparent' },
        }}
      />
    </Stack.Navigator>
  </NavigationContainer>
);

export default NavUnauthenticated;

```
