### ISSUE TITLE
Question about v5 double tap bug

### ISSUE THREAD

**Issue by tankpower1** [react-navigation/react-navigation#6843]
Hello,
In v4 there is a bug when you double tap a .push() it pushes the desired screen 2 times. Is this bug in v5 too?

**Comment by AnOptimistSeePessimist** [comment]
it is not a bug. Please refer to [this](https://reactnavigation.org/docs/en/4.x/navigation-prop.html#push)

**Comment by shirohana** [comment]
I made a helper hook for that, hope it helps:

##### ~hooks/use-navigate-lock.js
```js
// @flow
import { useCallback, useState } from 'react'
import { useFocusEffect } from '@react-navigation/native'

export default function useNavigateLock () {
  const [isLocked, setIsLocked] = useState(false)

  useFocusEffect(useCallback(() => {
    setIsLocked(false)
  }, []))

  const locker = () => {
    if (isLocked) {
      return false
    } else {
      setIsLocked(true)
      return true
    }
  }

  return locker
}
```

And use it:

##### ~scenes/home.js
```js
import React from 'react'
import { Button, View } from 'react-native'

import useNavigateLock from '~hooks/use-navigate-lock'

const Home = ({ navigation }) => {
  const lock = useNavigateLock()

  const goSettings = () => lock() && navigation.push('Settings')
  const goProfile = () => lock() && navigation.push('Profile')

  return (
    <View>
      <Button title="pushSettings" onPress={goSettings} />
      <Button title="pushProfile" onPress={goProfile} />
    </View>
  )
}

export default Home
```

**Comment by loodsite** [comment]
This bug is still present in v5. Occurs when you quickly double-tap a button calling a function `navigation.goBack()`, `navigation.pop()` or header back arrow.

**Comment by enaluz** [comment]
> I made a helper hook for that, hope it helps:
> 
> ##### ~hooks/use-navigate-lock.js
> ```js
> // @flow
> import { useCallback, useState } from 'react'
> import { useFocusEffect } from '@react-navigation/native'
> 
> export default function useNavigateLock () {
>   const [isLocked, setIsLocked] = useState(false)
> 
>   useFocusEffect(useCallback(() => {
>     setIsLocked(false)
>   }, []))
> 
>   const locker = () => {
>     if (isLocked) {
>       return false
>     } else {
>       setIsLocked(true)
>       return true
>     }
>   }
> 
>   return locker
> }
> ```
> 
> And use it:
> 
> ##### ~scenes/home.js
> ```js
> import React from 'react'
> import { Button, View } from 'react-native'
> 
> import useNavigateLock from '~hooks/use-navigate-lock'
> 
> const Home = ({ navigation }) => {
>   const lock = useNavigateLock()
> 
>   const goSettings = () => lock() && navigation.push('Settings')
>   const goProfile = () => {
>     if (lock()) {
>       const params = { name: 'Hana' }
>       navigation.push('Profile', params)
>     }
>   }
> 
>   return (
>     <View>
>       <Button title="pushSettings" onPress={goSettings} />
>       <Button title="pushProfile" onPress={goProfile} />
>     </View>
>   )
> }
> 
> export default Home
> ```

Awesome solution! This is the only one that has worked for me.

**Comment by efstathiosntonas** [comment]
Since this solution can raise [Accessing the 'state' property of the 'route' object is not supported](https://github.com/react-navigation/react-navigation/issues/9056) warning, here's an alternate solution: 

```

import { useRef } from "react";

export default (callback: any, timeBlocked = 2000) => {
  const isBlockedRef = useRef(false);
  const unblockTimeout = useRef(false);

  return (...callbackArgs: any) => {
    if (!isBlockedRef.current) {
      callback(...callbackArgs);
    }
    // @ts-ignore
    clearTimeout(unblockTimeout.current);
    // @ts-ignore
    unblockTimeout.current = setTimeout(
      () => (isBlockedRef.current = false),
      timeBlocked
    );
    isBlockedRef.current = true;
  };
};

```

and usage: 

```
 const onGoToFeed = useTimeBlockedCallback((feed: Doc<Feed>) => {
    navigation.push("FeedDetailPage", { ...feed, tabType: "comment", blockedUsers });
  }, 1000);

```

**Comment by raajnadar** [comment]
Hey,

`navigation.push('')` is used to add same page multiple times on the navigation tree. If you know you need a specific screen only once use `navigation.navigate('')`. This is not a bug it is a feature 🤣 🤣

**Comment by anhquan291** [comment]
> ```js
>   const lock = useNavigateLock()
> ```

Hi, I got a problem using your custom hook "Hooks can't be called outside functional component". Thanks
