### ISSUE TITLE
Is ready the Native Stack Navigator for production ?

### ISSUE THREAD

**Issue by muhammadwafa** [react-navigation/react-navigation#6844]
This warning still exist in `@react-navigation/native-stack`:

We found non-serializable values in the navigation state, which can break usage such as persisting and restoring state. This might happen if you passed non-serializable values such as function, class instances etc. in params. If you need to use components with callbacks in your options, you can use 'navigation.setOptions' instead. See https://reactnavigation.org/docs/en/header-buttons.html#header-interaction-with-its-screen-component for docs.

This actually happens when I navigate with function params, I mean I am passing function as params because I need to call parent function from screen I navigated.

**Comment by satya164** [comment]
https://reactnavigation.org/docs/en/troubleshooting.html#i-get-the-warning-we-found-non-serializable-values-in-the-navigation-state

**Comment by muhammadwafa** [comment]
Thank you and the other part is **`Is native stack navigator ready for production ?`**
