### ISSUE TITLE
v5 - Giving a custom openDrawer openClose route?

### ISSUE THREAD

**Issue by M1zuke** [react-navigation/react-navigation#6846]
I have a specific case where i have 2 Drawers. One left and one on the right at the same time.

I resolved this by stacking both Drawers into each other and routing via costum Component.

The only thing which I can't read out of the docs is, if it's possible to actually give the drawers a costum route to open up. I want the headerLeft to open the Left Drawer and the HeaderRight to open the right one.

Did I overread something which makes this possible or does someone have an idea how I can achive that?

My Code looks like this:
- here I navigate after logging in to the loggedIn Route, which then uses the DrawerNavigator MyLeftDrawer. 
![image](https://user-images.githubusercontent.com/59958391/74438272-0aa05100-4e6a-11ea-89bc-9a88a454d2a9.png)
- The LeftDrawer then has the screen MyRightDrawer which resolves in 2 Drawers. Left and Right at the same time.
![image](https://user-images.githubusercontent.com/59958391/74438258-0116e900-4e6a-11ea-9450-b594ba346a93.png)

Many thanks in advance.

**Comment by WoLewicki** [comment]
You can use navigation.dangerouslyGetParent() to get the navigation of your parent Drawer. Something like that: https://snack.expo.io/@wolewicki/two-drawers. Does this fix your issue?
