### ISSUE TITLE
`onLayout` is being called every time keyboard shows

### ISSUE THREAD

**Issue by Hatko** [react-navigation/react-navigation#6847]
**Current Behavior**

Whenever keyboard is shown, `onLayout` is called for a view inside of TabNavigator, if the view has `flex: 1`. It wasn't the case before upgrading to 4.* (3.11.0 the behavior is different)

**Expected Behavior**

I'm not sure if it's an intended behavior, but we have some things broken. Before fixing them, it would be nice to know if it's a bug or not.

**How to reproduce**

You can see the issue in this snack. Show and hide keyboard, and `onLayout` message will be shown every time

https://snack.expo.io/@vladhatko/react-navigation-is-weird

**Your Environment**

| software                                  | version |
| ----------------------------- | ------- |
| iOS                                           |  13.3    |
| @react-navigation/native     |4.1.0  |
| @react-navigation/bottom-tabs |  2.7.0  |
| react-native-screens  | ^2.0.0-alpha.20  |
| react-native              | 0.61.2   |
| expo                   | N/A     |
| node                   |    12.1.0   |
| yarn              | 1.22.0    |

**Comment by satya164** [comment]
You need to set `keyboardHidesTabBar` to `false` for old behaviour https://reactnavigation.org/docs/en/4.x/bottom-tab-navigator.html#bottomtabnavigatorconfig
