### ISSUE TITLE
If present native alert for iOS that time not navigate new screen in react-navigation 5 using createNativeStackNavigator.

### ISSUE THREAD

**Issue by singheshadev** [react-navigation/react-navigation#6852]
**Current Behavior**

- Not redirect new screen.

**Expected Behavior**

- Navigate new screen

**How to reproduce**

- Open A screen
- Present native alert view 
- Execute to navigate second screen code (Using createNativeStackNavigator)

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS                |
| @react-navigation/native       |
| react-native                   |

**Comment by satya164** [comment]
Hey, native-stack has been moved to [software-mansion/react-native-screens](https://github.com/software-mansion/react-native-screens). Please track the issue here: https://github.com/software-mansion/react-native-screens/issues/357
