### ISSUE TITLE
Drawer Navigator is not working with latest version of react 0.61

### ISSUE THREAD

**Issue by Bayramito** [react-navigation/react-navigation#6855]
Im getting

**TypeError: null is not an object (evaluating '_RNGestureHandlerMoodule.default.Direction)**

I was getting same error on my project that im working on, so i wanted to test it from scratch with a new project.

> I've created a new project 
>Installed  React Navigation v5 from its own website as well as the Drawer Navigation.
>I went to App.js file, deleted everything and copy pasted their own simple example from Snack!

And still getting same error.
Is there any bug or something ???

**Comment by satya164** [comment]
https://reactnavigation.org/docs/en/troubleshooting.html#im-getting-an-error-null-is-not-an-object-evaluating-rngesturehandlermoduledefaultdirection

**Comment by Bayramito** [comment]
> https://reactnavigation.org/docs/en/troubleshooting.html#im-getting-an-error-null-is-not-an-object-evaluating-rngesturehandlermoduledefaultdirection

Thank you very much mate. I fixed my errors. That helped me a lot. Thank you
