### ISSUE TITLE
v5: overflow visible only for expo web.

### ISSUE THREAD

**Issue by ningacoding** [react-navigation/react-navigation#6856]
**Current Behavior**

- What code are you running and what is happening?
Very similar to example/documentation.

- Include a screenshot or video if it makes sense.
![image](https://user-images.githubusercontent.com/17342546/74544255-73400a00-4f0c-11ea-9f2c-2747d268bf08.png)

**Expected Behavior**
Same look but without scrollbars or with overflow hidden.

- What do you expect should be happening?
overflow hidden
- Include a screenshot or video if it makes sense.
![image](https://user-images.githubusercontent.com/17342546/74544406-b1d5c480-4f0c-11ea-8ab3-fc0e3ee73457.png)

**How to reproduce**

- You must provide a way to reproduce the problem. If you are having an issue with your machine or build tools, the issue belongs on another repository as that is outside of the scope of React Navigation.
- Either re-create the bug on [Snack](https://snack.expo.io) or link to a GitHub repository with code that reproduces the bug.
- Explain how to run the example app and any steps that we need to take to reproduce the issue from the example app.
- Keep the repro code as simple as possible, with the minimum amount of code required to repro the issue.
- Before reporting an issue, make sure you are on latest version of the package.

OK, looks like happens only for web.

**Your Environment**

| software                            | version |
| ----------------------------------- | ------- |
| iOS or Android                      |  Expo Web Chrome and Edge Chrome
| @react-navigation/native            |  5.0.3
| @react-navigation/material-top-tabs | 5.0.3
| react-native-tab-view               | 2.13.0
| react-native                        | https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz
| expo                                | 36.0.0
| node                                |  12.9.1
| npm or yarn                         | yarn 1.19.1

**Comment by ningacoding** [comment]
Adding snippet code:

App root file:

```
render = () => {
        return this.state.isReady ? <SafeAreaProvider>
                    <KeyboardAvoidingView style={styles.container} 
                               behavior={"padding"} 
                               enabled={Platform.OS === 'ios'}>
                        <SafeAreaView style={[styles.container, {backgroundColor: Colors.$primaryColor}]}>
                            <StatusBar barStyle="light-content" backgroundColor={Colors.$primaryColor}/>
                            <Routes/>
                        </SafeAreaView>
                    </KeyboardAvoidingView>
                </SafeAreaProvider>  : <AppLoading/>
    };
```

Routes file
```

// other imports
import {createMaterialTopTabNavigator} from '@react-navigation/material-top-tabs';
import {createStackNavigator} from '@react-navigation/stack';

const TabTop = createMaterialTopTabNavigator();
const Stack = createStackNavigator();

function ProductCreate() {
    return <TabTop.Navigator tabBarOptions={{
        activeTintColor: Colors.$accentColor,
        indicatorStyle: {backgroundColor: Colors.$accentColor},
        inactiveTintColor: Colors.$textColorPrimary
    }}>
        <TabTop.Screen name="productFormBasic"
                       component={ProductCreateBasicScreen}
                       options={{title: i18n.t("products.labels.titleFormBasic")}}/>
        <TabTop.Screen name="productFormImages"
                       component={ProductCreateImagesScreen}
                       options={{title: i18n.t("products.labels.titleFormImages")}}/>
        <TabTop.Screen name="productFormAdvanced"
                       component={ProductCreateAdvancedScreen}
                       options={{title: i18n.t("products.labels.titleFormAdvanced")}}/>
    </TabTop.Navigator>;
}

function Home() {
    return <Stack.Navigator
        initialRouteName="home"
        screenOptions={{
            headerStyle: {
                backgroundColor: Colors.$primaryColor,
            },
            headerTintColor: Colors.$white,
            headerTitleStyle: {
                fontWeight: 'bold',
            },
        }}>
      // other Stack.Screens
        <Stack.Screen name={'productCreate'} component={ProductCreate}
                      options={{title: i18n.t("products.labels.titleForm")}}/>
    </Stack.Navigator>;
}

export default class Routes extends Component {
    render = () => <Stack.Navigator
        initialRouteName="appLoader"
        headerMode={'none'}>
        // other Stack.Screens
        <Stack.Screen name={'home'} component={Home}/>
    </Stack.Navigator>;
}
```

**Comment by ningacoding** [comment]
Also edited the main issue adding right versions of packages and Browsers. I hope this help.

**Comment by coalini** [comment]
@ningacoding Hey, did you find a solution for this by any chance?

**Comment by ningacoding** [comment]
@coalini not yet, i'm waiting for bugfix.

**Comment by satya164** [comment]
Should be fixed in latest version of react-native-tab-view.
