### ISSUE TITLE
headerStyle doesn't take any effect with custom header and headerMode set to screen

### ISSUE THREAD

**Issue by mstaniewski** [react-navigation/react-navigation#6857]
**Current Behavior**
Despite setting headerStyle to height: 100, it's not being applied to HeaderContainer

Before headerMode: screen:
![Screenshot 2020-02-14 at 16 46 30](https://user-images.githubusercontent.com/11744682/74549482-ffbfec00-4f4f-11ea-833a-de1276bebcee.png)

After headerMode: screen:
![Screenshot 2020-02-14 at 16 46 42](https://user-images.githubusercontent.com/11744682/74549497-08b0bd80-4f50-11ea-8c84-92114dd651c8.png)

As of documentation, it's a good practice to set header height, so did I:
```js
      <NavigationContainer>
        <Stack.Navigator headerMode="screen">
          <Stack.Screen
            options={{
              header: Header,
              headerStyle: {
                height: 100,
              },
            }}
            name="App"
            component={AppFlow}
          />
          <Stack.Screen
            options={{headerShown: false}}
            name="Auth"
            component={AuthNavigator}
          />
        </Stack.Navigator>
      </NavigationContainer>
```

height style isn't being passed to HeaderContainer:
![Screenshot 2020-02-14 at 17 34 47](https://user-images.githubusercontent.com/11744682/74549688-57f6ee00-4f50-11ea-9cdb-631d47712b78.png)

**Expected Behavior**
headerStyle should be passed to headerContainer

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | iOS 13.2.2
| @react-navigation/native       | 5.0.3
| @react-navigation/stack        | 5.0.3
| react-native-gesture-handler   | 1.5.6
| react-native-safe-area-context | 0.7.3
| react-native-screens           | 2.0.0-beta.2
| react-native                   | 0.61.5
| node                           | 10.16.3
|  yarn                    | 1.19.1

**Comment by WoLewicki** [comment]
Could you provide a repro via snack? Because in the photos it looks like you have a top-tabs navigator.

**Comment by mstaniewski** [comment]
> Could you provide a repro via snack? Because in the photos it looks like you have a top-tabs navigator.

It's a top-tabs navigator nested in stack navigator. It's AppFlow from the code. 
I'll prepare a repro in a spare moment.

**Comment by satya164** [comment]
You must apply the style to your custom component for it to take effect https://reactnavigation.org/docs/stack-navigator#specify-a-height-in-headerstyle

**Comment by bikowalczyk** [comment]
> You must apply the style to your custom component for it to take effect https://reactnavigation.org/docs/stack-navigator#specify-a-height-in-headerstyle

Hello,

I'm facing the same issue. When I change the headerMode to "screen" my custom header collapses.

Maybe I've set the height style wrong. Could you maybe take a look?

<img width="581" alt="Zrzut ekranu 2020-04-4 o 17 48 38" src="https://user-images.githubusercontent.com/34490652/78455182-0c81d600-769d-11ea-95f2-281879ae1a68.png">

Above is my custom header component and below how I render it:

<img width="521" alt="Zrzut ekranu 2020-04-4 o 17 53 47" src="https://user-images.githubusercontent.com/34490652/78455212-3dfaa180-769d-11ea-816f-ada49d3d302b.png">


When I change set headerMode="screen" the header collapses and I'm no longer able to see the <Text> component. 

I'd be glad if you could help.
