### ISSUE TITLE
What's wrong with this Drawer Navigator

### ISSUE THREAD

**Issue by Bayramito** [react-navigation/react-navigation#6860]
Iam %100 sure there's a problem with drawer navigator. 
I can create and manage the other navigators with closed eyes but drawer navigator always having problem from it ....

i followed step by step the instructions, did everything. but getting this error, 

::ffff:127.0.0.1 - - [14/Feb/2020:20:44:00 +0000] "GET /index.bundle?platform=android&dev=true&minify=false HTTP/1.1" 500 - "-" "okhttp/3.12.1"
error: bundling failed: Error: Unable to resolve module `./CommonActions` from `node_modules\@react-navigation\core\src\index.tsx`:

tryd everything to fix it but no ... nothing changes ... 
Any ideas ?

**Comment by filozof6** [comment]
I am having the same issue updating the React Navigation to 5.0.5 is this fixed?

**Comment by Bayramito** [comment]
Run  npm --reset-cache react-native run-android

**Comment by kopax** [comment]
I have the same issue after upgrading from alpha to latest, how can this be resolved, `expo start -c` deos not work.
