### ISSUE TITLE
Navigating to any screen in a navigator cause all the intermediate screens to be instantiated

### ISSUE THREAD

**Issue by conleymon** [react-navigation/react-navigation#6861]
**Current Behavior**
If you define a navigator with 4 screens and navigate from the first to the fourth, 2 and 3 are instantiated, No value of lazyPreloadDistance  will allow one screen to be loaded in total isolation.

**Expected Behavior**
Only the target screen should be instantiated

snack https://snack.expo.io/@datconley/intermediate-screen-instantiation

| software                            | version |
| ----------------------------------- | ------- |
| both iOS  and  Android                      |
| @react-navigation/native            | 4.1.1
| @react-navigation/material-top-tabs |
| react-native-tab-view               |
| react-native                        | .61
| expo                                |36
| node                                |12.14.1
| yarn                         |

**Comment by satya164** [comment]
This is expected behavior. Lazily loaded screens load when they become visible, not focused. When you go to 1-4, all screens in between become visible.

**Comment by conleymon** [comment]
What then may I ask does the lazyPreloadDistance property do? Unless I do not understand it's function, there should be a value for that property that would allow me to load a screen in total isolation from the others.
