### ISSUE TITLE
Stack option not work (override) in tab option

### ISSUE THREAD

**Issue by foadabdollahi** [react-navigation/react-navigation#6862]
Stack option not work (override) in tab option 

when use stack in tab, tabBarLabel or tabBarVisible props not set from option property in stack options.

- https://snack.expo.io/?platform=android&name=Screen%20options%20resolution%20%C2%B7%20React%20Navigation&dependencies=%40react-native-community%2Fmasked-view%40%5E0.1.1%2C%40react-navigation%2Fnative%40%5E5.0.1%2C%40react-navigation%2Fbottom-tabs%40%5E5.0.1%2C%40react-navigation%2Fdrawer%40%5E5.0.1%2C%40react-navigation%2Fmaterial-bottom-tabs%40%5E5.0.1%2C%40react-navigation%2Fmaterial-top-tabs%40%5E5.0.1%2C%40react-navigation%2Fnative-stack%40%5E5.0.1%2C%40react-navigation%2Fstack%40%5E5.0.1%2Creact-native-gesture-handler%401.5.2%2Creact-native-reanimated%401.4.0%2Creact-native-safe-area-context%400.6.0%2Creact-native-screens%402.0.0-alpha.12&sourceUrl=https%3A%2F%2Freactnavigation.org%2Fexamples%2F5.x%2Fstack-in-tab-nav-options.js 

this snack must be show "Home!" not "Home"

Android

| software                      | version |
| ----------------------------- | ------- |
| iOS or Android                |  Android
| @react-navigation/native      | 5.0.2
| @react-navigation/bottom-tabs | 5.0.2
| react-native-screens          | 5.0.2
| react-native                  | 5.0.2

**Comment by Stringsaeed** [comment]
+1

**Comment by satya164** [comment]
Stack options are for stack, not for tabs https://reactnavigation.org/docs/en/screen-options-resolution.html
