### ISSUE TITLE
Passing params in React Navigation 5. Bug?

### ISSUE THREAD

**Issue by AliShehzad18** [react-navigation/react-navigation#6863]
I'm trying to pass a few params between a Tab Navigator. I’ve spent days debugging and am starting to believe this could be a bug. But then again, I could easily have missed something. Below is the structure of my program. In **bold** are the routes

**App**(Tab Navigator): { **Main**(stack) & **Filter**(screen) }

**Main**(Stack Navigator): { **Home**(screen) & **MediaDetails**(screen) }

I have a *button* on the screen associated with **Filter** which has an **onPress()** function. I'm passing a few params(but let's only consider the param ***to*** for the sake of this question).

    this.props.navigation.navigate('Home', {
        to: this.state.to,
    }

Now in the screen associated with **Home**, I'm reading the param inside the state like this: 

    state = {
        to: this.props.route.params.to
    }

Inside ***App.js***, I've set the initial value of ***to*** to be '2020' like this:

    <Stack.Screen 
        name="Home" 
        component={HomeScreen}                 
        initialParams={{
           to: '2020'
        }}
    />

The initial value is indeed set to *2020*. I press the button. Let's say I'm setting ***to*** to *1900*. Just before ***this.props.navigation.navigate*** executes, I **console.log(this.state.to)** the value and it is indeed updated to *1900*. However, as the screen changes to **Home**, the value reverts back to *2020*(observed via console.log) 

Could someone point out the cause for this spooky behavior? I've been trying to debug this for many hours with no luck. React Navigation 5 is pretty new as well so couldn't find anything similar online. Any help will be greatly appreciated. Thank you for reading all the way.
 
**Edit:** Full Code Below

**App.js**

    import React from 'react'
    import { NavigationContainer } from '@react-navigation/native'
    import { createStackNavigator } from '@react-navigation/stack'
    import { createBottomTabNavigator } from '@react-navigation/bottom-tabs'
    import Icon from "react-native-vector-icons/MaterialCommunityIcons"
    
    import HomeScreen from './screens/Home/HomeScreen'
    import MediaDetailsScreen from './screens/Details/MediaDetailsScreen'
    import FilterResultsScreen from './screens/Filter/FilterResultsScreen'
    
    const Stack = createStackNavigator()
    
    const Tab = createBottomTabNavigator()
    
    
    function MediaBrowserStack() {
        return (
            <Stack.Navigator 
                screenOptions={{ 
                    headerTitleAlign: 'center' 
                }}>
                <Stack.Screen 
                    name="Home" 
                    component={HomeScreen}                 
                    initialParams={{ 
                        validTypes: ['movie', 'series', 'game'],
                        from: '1800',
                        to: '2020'
                    }}
                    options={{ 
                        title: 'Media Browser',
                        headerTitleStyle: {
                            fontSize: 25
                        }
                    }}
                />
                <Stack.Screen 
                    name="MediaDetails" 
                    component={MediaDetailsScreen} 
                    options={({ route }) => {
                        title = route.params.title
                        if (title.length <= 36) {
                            return {
                                title: title,
                                headerTitleStyle: {
                                    fontSize: 20
                                }
                            }
                        } 
                        else if (title.length <= 45) {
                            return {
                                title: title,
                                headerTitleStyle: {
                                  fontSize: 15
                                }
                            }
                        }
                        else if (title.length <= 60) {
                            return {
                                title: title,
                                headerTitleStyle: {
                                    fontSize: 12                                
                                }
                            }
                        }
                        else {
                            return {
                                title: title,
                                headerTitleStyle: {
                                    fontSize: 10
                                }
                            }
                        }
                    }}
                />
            </Stack.Navigator>
        )
    }
    
    
    function App() {
        return (
            <NavigationContainer>
                <Tab.Navigator>
                    <Tab.Screen 
                        name="Main" 
                        component={MediaBrowserStack} 
                        options={{ 
                            title: 'Media Browser',
                            tabBarIcon: ({ focused }) => (
                                <Icon
                                    name={`alpha-m-circle${focused ? "" : "-outline"}`}
                                    size={25}
                                    color="blue"
                                />
                            )
                        }}
                    />
                    <Tab.Screen 
                        name="Filter" 
                        component={FilterResultsScreen} 
                        options={{
                            title: 'Filter Results',
                            tabBarIcon: ({ focused }) => (
                                <Icon
                                    name={`filter${focused ? "" : "-outline"}`}
                                    size={25}
                                    color="blue"
                                />
                            )
                        }}  
                    />
                </Tab.Navigator>
            </NavigationContainer>
        )
    }
    
    
    export default App

**HomeScreen.js**(this is the **Home** Route)

    import React, { Component } from 'react'
    import { StyleSheet, Text, View, TextInput } from 'react-native';
    
    import ResultsView from './ResultsView'
    import { fetchResponse } from '../../API/api'
    
    
    export default class HomeScreen extends Component {
    
        state = {
            search: '',
            error: 'Nothing searched yet.',
            ready: false,
            validTypes: this.props.route.params.validTypes,
            from: this.props.route.params.from,
            to: this.props.route.params.to
        }
    
        // Handle search then get response
        handleSearchChange = (search) => {
            if (search.trimEnd() === this.state.search.trimEnd()) {
                this.setState({ search })
            }
            else {
            this.setState({ search, ready: false }, this.getResponse)
            }
        }
    
        // Async function that checks if Response is valid
        // Returns number of pages if response is valid, error if invalid
        // Ready indicates we are 'ready' to go to ResultsView
        getResponse = async () => {
            const error = await fetchResponse(this.state.search)
            this.setState({ error, ready: true })
        }
        
        render() {
            console.log(this.state.to)
            return(
                <View style={styles.container}>
                    <TextInput 
                        style={styles.input}
                        placeholder='Search...'
                        value={this.state.search}
                        onChangeText={this.handleSearchChange}
                    />
                    {
                        (isNaN(this.state.error) &&  <Text>{this.state.error}</Text>)
                        ||
                        this.state.ready && <ResultsView 
                                                search={this.state.search} 
                                                totalPages={this.state.error} 
                                                navigation={this.props.navigation}
                                            />
                    }
                </View>
            )
        }
    }
    
    
    const styles = StyleSheet.create({
        container: {
            flex: 1,
            paddingTop: 30,
            paddingRight: 10,
            paddingLeft: 10
        },
        input: {
            borderWidth: 1,
            borderRadius: 5,
            paddingRight: 5,
            paddingLeft: 5
        }
    })

**FilterResultsScreen.js**(this is the **Filter** Route)

    import React, { Component } from 'react'
    import { StyleSheet, Keyboard, KeyboardAvoidingView, View, Text, Switch, TextInput, Button } from 'react-native'
    
    
    export default class FilterResults extends Component {
    
        state = {
            moviesSwitch: true,
            seriesSwitch: true,
            gamesSwitch: true,
            from: '1800',
            to: '2020',
            validTypes: []
        }
    
        prepareValidTypes() {
            if (this.state.moviesSwitch) {
                this.state.validTypes.push('movie')
            }
            if (this.state.seriesSwitch) {
                this.state.validTypes.push('series')
            }
            if (this.state.gamesSwitch) {
                this.state.validTypes.push('game')
            }
        }
    
        render() {
            return (
                <KeyboardAvoidingView style={styles.container} behavior="padding">
                    <Text style={styles.header}>Filter Results</Text>
                    <Text></Text>
                    <Text></Text>
                    <Text style={styles.header2}>What type(s) of media do you wish to search?</Text>
                    <Text></Text>
                    <View style={styles.row}>
                        <Text style={styles.header3}>Movies: </Text>
                        <Switch
                            value={this.state.moviesSwitch}
                            onValueChange={value => this.setState({ moviesSwitch: value })}
                        />
                        <Text style={styles.header3}>   Series: </Text>
                        <Switch
                            value={this.state.seriesSwitch}
                            onValueChange={value => this.setState({ seriesSwitch: value })}
                        />
                        <Text style={styles.header3}>   Games: </Text>
                        <Switch
                            value={this.state.gamesSwitch}
                            onValueChange={value => this.setState({ gamesSwitch: value })}
                        />
                    </View>
                    <Text></Text>
                    <Text></Text>
                    <Text style={styles.header2}>What year(s) do you wish to search?</Text>
                    <Text></Text>
                    <View style={styles.row}>
                        <TextInput
                            style={styles.inputBox}
                            keyboardType="numeric"
                            maxLength={4}
                            value={this.state.from}
                            onChangeText={from => this.setState({ from })}
                        />
                        <Text style={styles.header3}>    -    </Text>
                        <TextInput
                            style={styles.inputBox}
                            keyboardType="numeric"
                            maxLength={4}
                            value={this.state.to}
                            onChangeText={to => this.setState({ to })}
                        />
                    </View>
                    <Text></Text>
                    <Text></Text>
                    <Button
                        title="SET"
                        onPress={() => {
                            if (Number(this.state.from) > Number(this.state.to)) {
                                alert("You are trying to go back in time!")
                            }
                            else {
                                Keyboard.dismiss()
                                this.prepareValidTypes()
                                console.log(this.state.to)
                                this.props.navigation.navigate('Home', {
                                    validTypes: this.state.validTypes,
                                    from: this.state.from,
                                    to: this.state.to,
                                })
                            }
                        }}
                    />
                    <Text></Text>
                    <Button
                        title="RESET TO ALL"
                        onPress={() => this.setState({ 
                            moviesSwitch: true,
                            seriesSwitch: true,
                            gamesSwitch: true,
                            from: '1800',
                            to: '2020',
                            validTypes: []
                        }, Keyboard.dismiss())}
                    />
                </KeyboardAvoidingView>
            )
        }
    } 
    
    
    const styles = StyleSheet.create({
        container: {
            flex: 1,
            alignItems: 'center',
            justifyContent: 'center',
            fontSize: 15,
        },
        header: {
            fontSize: 30,
            fontWeight: 'bold'
        },
        header2: {
            fontSize: 20,
            fontWeight: 'bold',
            textAlign: 'center'
        },
        header3: {
            paddingTop: 2,
            fontSize: 15,
            fontWeight: 'bold'
        },
        row: {
            flexDirection: 'row'
        },
        inputBox: {
            width: 60,
            height: 30,
            borderWidth: 2,
            textAlign: 'right',
            paddingRight: 5
        }
    })

**Comment by ravirajn22** [comment]
To navigate from `Filter` screen in ParentTab to `Home` screen in  StackNav nested inside `Main` screen in ParentTab , 

First you need to navigate to the `Main` screen and then send name of the child screen in `Main` as params like below,
`navigation.navigate('Main', { screen: 'Home', params: { to: 1900 } });`

check out this doc, https://reactnavigation.org/docs/en/nesting-navigators.html#navigating-to-a-screen-in-a-nested-navigator

It should work.

**Comment by AliShehzad18** [comment]
Thanks for taking the time to read and respond.

However, the same issue occurs when I replace my line of code with 
`this.props.navigation.navigate('Main', { screen: 'Home', params: { to: 1900 } })`

I wasn't defining screen and params explicitly as **Home** is the Initial Screen on the **Main** Stack.

**Comment by ravirajn22** [comment]
Ok use this way to navigate,
https://github.com/react-navigation/react-navigation/issues/6863#issuecomment-586971849

Now can u just log the following in HomeScreen render,
`console.log(this.props.route.params.to)`

If this works correctly then ur not updating ur state from the latest route props. Avoid setting to and from from props to state instead just use them directly in render like route.params.to. If this is the case then you need to read more on this topic from react docs.

**Comment by WoLewicki** [comment]
@AliShehzad18 could you provide a snack with the minimal configuration and the bug appearing? This code snippet has too much code that is not needed and makes it hard to read.

**Comment by AliShehzad18** [comment]
> @AliShehzad18 could you provide a snack with the minimal configuration and the bug appearing? This code snippet has too much code that is not needed and makes it hard to read.



> Ok use this way to navigate,
> [#6863 (comment)](https://github.com/react-navigation/react-navigation/issues/6863#issuecomment-586971849)
> 
> Now can u just log the following in HomeScreen render,
> `console.log(this.props.route.params.to)`
> 
> If this works correctly then ur not updating ur state from the latest route props. Avoid setting to and from from props to state instead just use them directly in render like route.params.to. If this is the case then you need to read more on this topic from react docs.
> 
> In ur case since Main stack is nested inside a tab, the screens will not get unmounted when u navigate away from them.

**Comment by AliShehzad18** [comment]
> Ok use this way to navigate,
> [#6863 (comment)](https://github.com/react-navigation/react-navigation/issues/6863#issuecomment-586971849)
> 
> Now can u just log the following in HomeScreen render,
> `console.log(this.props.route.params.to)`
> 
> If this works correctly then ur not updating ur state from the latest route props. Avoid setting to and from from props to state instead just use them directly in render like route.params.to. If this is the case then you need to read more on this topic from react docs.
> 
> In ur case since Main stack is nested inside a tab, the screens will not get unmounted when u navigate away from them.

Thank you so much brother. The problem was exactly as you said. The **state wasn't updating** as the screen was still mounted. Thanks for explaining the reasoning behind this as well. It makes sense now. I've solved it by updating the state in **shouldComponentUpdate()**. Works like a charm!

I've just closed this issue as it wasn't a bug. Have a nice day!

**Comment by pke** [comment]
I ran into a similar problem I guess. 
What if `HomeScreen` is actually another StackNavigator the initial params are not forwarded to this stacks first screen.

```tsx
const RootStack = () => (
  <Stack.Navigator>
    <Stack.Screen name="HomeScreeen" component={HomeStack} initialParams={{ mode: "basket" }}/>
  </Stack.Navigator>
)

const HomeStack = () => (
  <Stack.Navigator>
    <Stack.Screen name="FooScreen" component={FooScreen}/>
  </Stack.Navigator>
)

const FooScreen = ({ route }) => {
  assert.equal(route.params?.mode, "basket")
}
```

Somehow FooScreen does not get the default param from the `Root` navigator passed down.
This is especially difficult if one is using deep linking with this config:

```ts
config = {
  HomeScreen: {
    screens: {
      FooScreen: "/foo/:mode?"
    }
  }
}

// Should show FooScreen with "mode" set to "basked"
linkTo("/foo")
```
