### ISSUE TITLE
Double tap header back arrow or button calling a function goBack(), pop()

### ISSUE THREAD

**Issue by loodsite** [react-navigation/react-navigation#6864]
**Current Behavior**

- If you double-tap header back arrow or the button that calls the function `navigation.goBack()` or `navigation.pop()` two screen were popped from the navigation stack.

**Expected Behavior**

- Only one screen should be popped, instead of two. 

**How to reproduce**

`
<Stack.Navigator>
  
<Stack.Screen name="ScreenA" component={ScreenA} />
<Stack.Screen name="ScreenB" component={ScreenB} />
<Stack.Screen name="ScreenC" component={ScreenC} />

</Stack.Navigator>
`
- ScreenA -> ScreenB -> ScreenC
- When trying to go back from ScreenC to ScreenB double-tap on header back arrow or 
- double-tap `<Button onPress={() => { this.props.navigation.goBack(); }}/>`
- same for `<Button onPress={() => { this.props.navigation.pop(); }}/>`

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| Android                 | 9.0 |
| @react-navigation/native       | 5.0.0 |
| @react-navigation/stack        | 5.0.0 |
| react-native-gesture-handler   | 1.5.0 |
| react-native-safe-area-context | 0.6.0 |
| react-native-screens           | 2.0.0-alpha.12 |
| react-native                   | 0.61 |
| expo                           | 36.0.0 |
| node                           | 12.15.0 |
| yarn                    | 1.21.1 |

**Comment by satya164** [comment]
If you call pop 2 times then 2 screens will be popped. This is not a bug.

If you want to prevent it, then you need to debounce your handlers in your code.

**Comment by loodsite** [comment]
@satya164 this makes sense for pop() function, but for goBack() function and double tap on header back icon debounce should be added by default. Especially for double tapping header back arrow icon.

**Comment by loodsite** [comment]
@satya164 worst case scenario if you navigate from ScreenA to ScreenB (only two screens in stack), on ScreenB double tapping header back arrow will cause app crash with console error
> The action 'POP' with payload '{"count":1}' was not handled by any navigator

**Comment by satya164** [comment]
It's not a crash. It's a development time only console error that can be dismissed.

**Comment by kevinvangelder** [comment]
Also experiencing this issue on react-navigation 4.0.10, but when pressing the back button twice in quick succession on Android it goes back a screen (B to A) and then forward again (A to B), and locks up the ability to go back (can't get back to A anymore), unless the user navigates deeper (C) and then back twice (C to B to A).

**Comment by Ashoat** [comment]
If you're encountering this issue, and want to make it so a `goBack` action only pops off the screen from which it was called, try this:

```js
navigation.dispatch(state => ({ ...CommonActions.goBack(), target: state.key }));
```

**Comment by betoharres** [comment]
@Ashoat thanks a lot, looks like your solution works :D
