### ISSUE TITLE
headerTitle going out of screen/overlapping

### ISSUE THREAD

**Issue by selvin007** [react-navigation/react-navigation#6865]
any content added in "headerTitle" is going out of screen

eg: headerTitle: "TERMS AND CONDITIONS and PRIVACY POLICY",

![Screenshot 2](https://user-images.githubusercontent.com/7314081/74608679-460c7b00-5109-11ea-86c1-3ff9baef45a6.jpg)

even with headerTitle: () => <Text style={{ width: '100%', fontSize: 18, color: '#fff' }}>"TERMS AND CONDITIONS and PRIVACY POLICY"</Text>,

![Screenshot 3](https://user-images.githubusercontent.com/7314081/74608683-4d338900-5109-11ea-9d45-85b176c7f23c.jpg)

also if headerRight is set it is getting overlapped

![Screenshot 1](https://user-images.githubusercontent.com/7314081/74608686-515fa680-5109-11ea-8b7e-5f00b596390e.jpg)

**Comment by WoLewicki** [comment]
What is the behavior expected by you?

**Comment by selvin007** [comment]
No, 

Need "TERMS AND CONDITIONS ..." instead of full text if it is exceeding the screen

    "react-native": "0.61.5",
    "@react-navigation/drawer": "^5.0.5",
    "@react-navigation/native": "^5.0.5",
    "@react-navigation/stack": "^5.0.5",

**Comment by WoLewicki** [comment]
You can try to use `numberOfLines` prop to achieve it https://facebook.github.io/react-native/docs/text.html#numberoflines. It seems like it is not the concern of react-navigation itself.

**Comment by selvin007** [comment]
Thanks, got it working

> headerTitle: () => <Text style={{ fontSize: 18, color: MyTheme.headerFontColor, fontWeight: "bold", width: screenWidth - (headerLeftWidth + headerRightWidth) }} numberOfLines={1}>TERMS AND CONDITIONS and PRIVACY POLICY</Text>,
            headerStyle: {
                backgroundColor: MyTheme.primaryColor,
            },
            headerTintColor: MyTheme.headerFontColor,
            headerRight: () => (<TouchableOpacity activeOpacity={0.1} style={{ marginRight: 10, borderColor: "#fff", borderWidth: 0.5, borderRadius: 5, paddingTop: 6, paddingHorizontal: 8, paddingBottom: 2 }}>
                <Image source={{ uri: 'asset:/icons/fa-map.png' }} style={{ width: 20, height: 20 }} />
                <Text style={{ color: '#fff', fontSize: 8, textAlign: "center" }}>Map</Text>
            </TouchableOpacity>
            ),

![Screenshot 1](https://user-images.githubusercontent.com/7314081/74726682-e4adee80-5265-11ea-83af-6f6bf5dcd717.jpg)

But how i do i effectively determine the width of headerLeft

**Comment by WoLewicki** [comment]
It varies on different platforms. You can check the style with the inspector or in the code (e.g. here): https://github.com/react-navigation/react-navigation/blob/master/packages/stack/src/views/Header/HeaderBackButton.tsx
