### ISSUE TITLE
Disable Drawer on specific screens

### ISSUE THREAD

**Issue by martinjohnlopez8** [react-navigation/react-navigation#6866]
I cannot find the option to lock drawer on specific screens. 

I was looking for this snippet

`navigationOptions: {
  drawerLockMode: 'locked-closed'
}`

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | 0.61.5
| @react-navigation/native       |5.0.1
| @react-navigation/drawer       |5.0.1
| react-native-reanimated        |1.7.0
| react-native-gesture-handler   |1.5.6
| react-native-safe-area-context |0.7.2
| react-native-screens           |
| react-native                   |0.61.5
| expo                           |
| node                           |
| npm or yarn                    |npm

**Comment by WoLewicki** [comment]
Are you looking for `gestureEnabled` prop? https://reactnavigation.org/docs/en/drawer-navigator.html#gestureenabled

**Comment by martinjohnlopez8** [comment]
> Are you looking for `gestureEnabled` prop? https://reactnavigation.org/docs/en/drawer-navigator.html#gestureenabled

Yes, thank you.

**Comment by infinitbility** [comment]
Looking for an example?

https://infinitbility.com/how-to-disable-drawer-on-the-drawer-navigation-screen

**Comment by haipv01** [comment]
> Looking for an example?
> 
> https://infinitbility.com/how-to-disable-drawer-on-the-drawer-navigation-screen

fuck you, don't comment to embedded back link any more
