### ISSUE TITLE
Bottom Tab Navigator icons not showing in React Navigation 5.0.5

### ISSUE THREAD

**Issue by mauriciosoares01** [react-navigation/react-navigation#6867]
### Problem:
I'm trying to use icons, from React Native Vector Icons, in the bottom tab navigator. But the icons are not being rendered in the tab.

![image](https://user-images.githubusercontent.com/17464462/74613013-590f5300-50e9-11ea-82ee-599a70f68644.png)

### My BottomTab code:

```import React from 'react';
import {createBottomTabNavigator} from '@react-navigation/bottom-tabs';
import Icon from 'react-native-vector-icons/MaterialIcons';

import {Home, Playlists, Adjusts} from '../pages';

const BottomTab = createBottomTabNavigator();

function Dashboard() {
  return (
    <BottomTab.Navigator initialRouteName="home">
      <BottomTab.Screen
        name="home"
        component={Home}
        options={{
          tabBarLabel: 'Home',
          tabBarIcon: () => <Icon name="home" color="#333" size={24} />,
        }}
      />
      <BottomTab.Screen
        name="playlists"
        component={Playlists}
        options={{
          tabBarLabel: 'Playlists',
          tabBarIcon: () => (
            <Icon name="playlist-play" color="#333" size={24} />
          ),
        }}
      />
      <BottomTab.Screen
        name="adjusts"
        component={Adjusts}
        options={{
          tabBarLabel: 'Ajustes',
          tabBarIcon: () => <Icon name="settings" color="#333" size={24} />,
        }}
      />
    </BottomTab.Navigator>
  );
}

export default Dashboard;
```

### Environment:

software | version
-- | --
iOS or Android | Only verified on Android
@react-navigation/native | 5.0.5
@react-navigation/bottom-tabs | 5.0.5
react-native-screens | 2.0.0-beta.4
react-native | 0.61.5
react-native-vector-icons/MaterialIcons | 6.6.0

**Comment by ctopher7** [comment]
im experiencing the same, and it is not the fault of react navigation. You need to do this: 
Copy the contents in the Fonts (from node modules) folder to android/app/src/main/assets/fonts (note lowercase fonts folder).

**Comment by mauriciosoares01** [comment]
> im experiencing the same, and it is not the fault of react navigation. You need to do this:
> Copy the contents in the Fonts (from node modules) folder to android/app/src/main/assets/fonts (note lowercase fonts folder).

Thank you, this solved my problem

**Comment by umair-dpl** [comment]
I am having this issue and I have done as told but nothing changes

**Comment by lylest** [comment]
copy what contents friend and put them where can you please explain

**Comment by raajnadar** [comment]
@lylest @umair-dpl follow this steps https://github.com/oblador/react-native-vector-icons/issues/1117#issuecomment-589958315

**Comment by eee9** [comment]
> im experiencing the same, and it is not the fault of react navigation. You need to do this:
> Copy the contents in the Fonts (from node modules) folder to android/app/src/main/assets/fonts (note lowercase fonts folder).

Thanx, this helped for me too.

**Comment by saurabhkanswal** [comment]
https://www.npmjs.com/package/react-native-vector-icons#android

check this one for android
