### ISSUE TITLE
Hardware / Gesture back not working if stack depth is more than 1

### ISSUE THREAD

**Issue by deepankarsandy** [react-navigation/react-navigation#6868]
**[ANDROID]**
**When I enter into any stack screen and depth is more than 1, hardware/gesture back is not working. Header back button is working as usual. Also I disabled enableScreens() since it was causing a blank screen on back when depth is 1**

***Probable cause***
This happened after react native and other package upgrade. Older versions are mentioned in right to current

**Reproduce with this code**
[https://github.com/react-navigation/react-navigation/issues/url](url)

***package description and versions***
`"react": "16.12.0"`
`"react-dom": "16.12.0"`
`"react-native": "0.61.5"` (previous 0.60.4)
`"react-native-screens": "^2.0.0-beta.4"` (2.0.0-alpha.20)
`"react-native-gesture-handler": "^1.6.0"` (1.3.0)
`"react-navigation": "^4.1.1",` (4.0.10)
`"react-navigation-drawer": "^2.3.4"` (2.3.3)
`"react-navigation-stack": "^2.1.1"` (1.10.3)
`"react-navigation-tabs": "^2.7.0"` (2.6.2)

I've imported `react-native-gesture-handler` in my root js file, and properly set up gesture handler in android gradle file (certain of it)

**Expected Behavior**
I should be able to back to stacked screens with hardware button / gesture / header button and see no blank screens

**Your Environment**

| software                                       | version |
| ------------------------------ | ------- |
| react-navigation                        | 4.1.1
| react-navigation-stack            | 2.1.1
| react-navigation-tabs              | 2.7.0
| react-navigation-drawer         | 2.3.4
| react-native-reanimated         | 1.7.0
| react-native-gesture-handler   | 1.6
| react-native-safe-area-context | 0.7.3
| react-native-screens               | 2.0.0-beta.4
| react-native                               | .61.5
| node                                           | 10.18
| yarn                                            | 1.17.3

**Comment by deepankarsandy** [comment]
**Patch for the time being**

down graded following packages
`"react-native-screens": "^2.0.0-alpha.20"`
`"react-navigation-stack": "^1.10.3"`

removed following 
`"react-native-safe-area-context": "^0.6.2"`

so now it's working but I'd appreciate a fix the issue.

**Comment by deepankarsandy** [comment]
**Repro**
[https://snack.expo.io/ByZkH1FmU](url)

**Comment by satya164** [comment]
Closing due to no response.

**Comment by deepankarsandy** [comment]
@satya164 if there's no response that doesn't mean it's resolved and ready to close, either merge with similar issue or keep it open until resolved.

**Comment by satya164** [comment]
If you want to keep it open then follow the issue template and provide a repro.
