### ISSUE TITLE
All previous screens are mounted again while navigating to next ones react-navigation 5x

### ISSUE THREAD

**Issue by deserthurricane** [react-navigation/react-navigation#6870]
**Current Behavior**

We have a react-native project with such structure:

```
<NavigationContainer>
    <BottomTabNavigator {...props}>
            <BottomTab.Screen 
                component={StackNavigator1} 
            />
            <BottomTab.Screen 
                component={StackNavigator2} 
            />
            <BottomTab.Screen 
                component={StackNavigator3} 
            />
            <BottomTab.Screen 
                component={StackNavigator4} 
            />
    </BottomTabNavigator>
</NavigationContainer>
```

For example, we are on screen A of StackNavigator1, which has screens: A, B, C. When navigating to screen B, the A screen is mounted again! When you go from B to C, A and B are mounted again and so on.

As said in documentation ([https://reactnavigation.org/docs/en/navigation-lifecycle.html](https://reactnavigation.org/docs/en/navigation-lifecycle.html)), 

> Consider a stack navigator with screens A and B. After navigating to A, its componentDidMount is called. When pushing B, its componentDidMount is also called, but A remains mounted on the stack and its componentWillUnmount is therefore not called.

But is doesn't work like this! All screens in the stack keep on mounting while navigating to the next one. And, besides performance concern,  if you have an API call in componentDidMount() or in useEffect(() => APIcall(), []) hook, it is being called every time you navigate to a new screen and causes various bugs!

**But:** if we wrap each StackNavigator with `<NavigationContainer independent={true}>`, all screens mount only once as it should be. But in such case we loose access to other nested stack navigators, which becomes another big trouble.

**Expected Behavior**
In react-navigation 4x, each screen in the stack was mounted only once. Can it work the same in 5x?

**How to reproduce**
https://snack.expo.io/@deserthurricane/stacknavigator

Create a project with the same structure and call console.log('screen mounted') in componentDidMount() or useEffect(() => , []). You will see how often it is called while navigating.

If it is important - each StackNavigator is wrapped with react-redux <Provider store={store} /> component, because each navigator has it's own separate store.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | iOS
| @react-navigation/native       | 5.0.3
| @react-navigation/stack        | 5.0.3
| react-native-gesture-handler   | 1.5.6
| react-native-safe-area-context | 0.6.4
| react-native-screens           | 2.0.0-beta.2
| react-native                   | 0.61.5

**Comment by deserthurricane** [comment]
Probably this issue: https://github.com/react-navigation/react-navigation/issues/6861 is caused by the same problem as mine. Or the same bunch of problems.

**Comment by deserthurricane** [comment]
By the way, @react-navigation/native-stack also has this behaviour.

**Comment by satya164** [comment]
Please provide a runnable repro.

**Comment by deserthurricane** [comment]
> Please provide a runnable repro.

I've finally found what caused the bug. Link to reproduce: https://snack.expo.io/@deserthurricane/stacknavigator

When you wrap your Navigator in a HOC (withTheme) right inside another navigator, it causes "re-mounting" error.

Previously, in 4x version, when it looked like this:

```
const Navigator = createStackNavigator({
	Search: {
		screen: withTheme(SearchScreen),
	},
	SearchResults: {
		screen: withTheme(SearchResultsScreen),
	},
	SelectedItem: {
		screen: withTheme(SelectedItemScreen),
	},
}, {
	initialRouteName: 'Search',
	headerBackTitleVisible: false,
	defaultNavigationOptions : { header: null },
})
```
it didn't have "re-mounting" behaviour.

**Comment by satya164** [comment]
`withTheme(...)` creates a new component. If you create a new component every re-render then it'll be remounted. You need to move it outside of render phase.

**Comment by voold** [comment]
I have the same problem. Can someone be more specific or show me how to solve this problem?

**Comment by tmaly1980** [comment]
I'm noticing this same issue with redux and connect() for a nested TabNavigator. I'll try moving the props outside of the TabNav to see if that helps...

**Comment by satya164** [comment]
Don't put them inside your component. Wrap it in the top level of the file and assign it to a variable, then use that variable inside your component.

Calling HOC like `connect` or whatever creates a new React Component. You shouldn't create React Components inside React Components.

**Comment by tmaly1980** [comment]
> Don't put them inside your component. Wrap it in the top level of the file and assign it to a variable, then use that variable inside your component.
> 
> Calling HOC like `connect` or whatever creates a new React Component. You shouldn't create React Components inside React Components.

@satya164 I'm unclear what you're suggesting, can you provide a quick example, assuming my navigation is one file and a screen component that needs access to redux is in another file? Am I supposed to use connect() and define mapStateToProps/mapDispatchToProps for my whole app in my navigation component?

**Comment by satya164** [comment]
```js
const ConnectedThing = connect(Thing); // outside

function NavigationStuff() {
 // <Stack.Screen component={ConnectedThing} /> inside
}

```

**Comment by tmaly1980** [comment]
@satya164 Actually my problem is with nested navigators. This first example works fine, but the second one causes each tab to be unmounted/remounted every time I navigate to a new tab. What am I missing?

OK:
```
return (
<NavigationContainer>
   <Tab.Navigator>
      <Tab.Screen name="One" component={ScreenOne} />
      <Tab.Screen name="Two" component={ScreenTwo} />
      <Tab.Screen name="Three" component={ScreenThree} />
      <Tab.Screen name="Four" component={ScreenFour} />
  </Tab.Navigator>
</NavigationContainer>
)
```

This causes remounting every tab click (for all the other tabs, not just the previous one):
```
const TabNav = (
   <Tab.Navigator>
      <Tab.Screen name="One" component={ScreenOne} />
      <Tab.Screen name="Two" component={ScreenTwo} />
      <Tab.Screen name="Three" component={ScreenThree} />
      <Tab.Screen name="Four" component={ScreenFour} />
  </Tab.Navigator>
)

return (
<NavigationContainer>
  <Stack.Navigator>
    <Stack.Screen name="Tabs" component={TabNav} />
  </Stack.Navigator>
</NavigationContainer>
)
```

**Comment by satya164** [comment]
I'm 99% sure that you're creating components inside other components, so check for that. I can't tell from the code you posted, but looks like you're creating `TabNav` component inside another component.

**Comment by tmaly1980** [comment]
OK I think I figured it out. I was actually passing each tab component as a function within the same larger component, and had something like: this.ScreenOne.bind(this), rather than this.ScreenOne . Mainly because I wanted to have access to redux and shared functions, but I'll have to work around that somehow.

**Comment by JulianKingman** [comment]
Tip for people using redux in their navigators: use the `useSelector` hook instead of `connect`, like so:
```javascript
const TabNav = {
  const propertyThatYouWant = ({stateThatYouWant: { propertyThatYouWant: p}) => p;
  return (
     <Tab.Navigator>
        <Tab.Screen name="One" component={ScreenOne} />
        <Tab.Screen name="Two" component={ScreenTwo} />
        <Tab.Screen name="Three" component={ScreenThree} />
        <Tab.Screen name="Four" component={ScreenFour} />
    </Tab.Navigator>
  )
}
```

**Comment by Sebi55** [comment]
I had the same problem when updating to React Navigation 3 to 5. I am also using Redux.
For me the solution was to nest the navigators as child of the screen component and not inserting the navigator into the component property.

**Comment by merigold** [comment]
In my app, problem is in authentication flow, when I use conditional rendering from docs:
https://reactnavigation.org/docs/auth-flow
All my screens in current condition render together

**Comment by Jarrettgohh** [comment]
I may have found a simple reason why the remounting keeps happening when a  new stack screen is navigated too. Under the section `Screens are unmounting/remounting during navigation` from this link https://reactnavigation.org/docs/troubleshooting/.

It could happen

**Comment by AndonMitev** [comment]
> I'm 99% sure that you're creating components inside other components, so check for that. I can't tell from the code you posted, but looks like you're creating `TabNav` component inside another component.

Hey i have exact same structure as comment above:

```
const TabNav = (
   <Tab.Navigator>
      <Tab.Screen name="One" component={ScreenOne} />
      <Tab.Screen name="Two" component={ScreenTwo} />
      <Tab.Screen name="Three" component={ScreenThree} />
      <Tab.Screen name="Four" component={ScreenFour} />
  </Tab.Navigator>
)

return (
<NavigationContainer>
  <Stack.Navigator>
    <Stack.Screen name="Tabs" component={TabNav} />
    <Stack.Screen name="OtherScreen" component={OtherScreen} />
  </Stack.Navigator>
</NavigationContainer>
)
```

At some point in `OtherScreen` i do redirect to `TabNav Screen#1` is this possible for such behaviour?

I can see how previous screen is displayed for 1 sec before opening a new one and sometimes new one is not able to navigate correctly

**Comment by amiresobh** [comment]
hi
my solution was to use useNavigationState(state=> state.index) to get the index of active screen and in useEffect hook(which renders from previous screens) I used a condition.
hope it helps

**Comment by chetanbhadarka** [comment]
> @satya164 Actually my problem is with nested navigators. This first example works fine, but the second one causes each tab to be unmounted/remounted every time I navigate to a new tab. What am I missing?
> 
> OK:
> 
> ```
> return (
> <NavigationContainer>
>    <Tab.Navigator>
>       <Tab.Screen name="One" component={ScreenOne} />
>       <Tab.Screen name="Two" component={ScreenTwo} />
>       <Tab.Screen name="Three" component={ScreenThree} />
>       <Tab.Screen name="Four" component={ScreenFour} />
>   </Tab.Navigator>
> </NavigationContainer>
> )
> ```
> 
> This causes remounting every tab click (for all the other tabs, not just the previous one):
> 
> ```
> const TabNav = (
>    <Tab.Navigator>
>       <Tab.Screen name="One" component={ScreenOne} />
>       <Tab.Screen name="Two" component={ScreenTwo} />
>       <Tab.Screen name="Three" component={ScreenThree} />
>       <Tab.Screen name="Four" component={ScreenFour} />
>   </Tab.Navigator>
> )
> 
> return (
> <NavigationContainer>
>   <Stack.Navigator>
>     <Stack.Screen name="Tabs" component={TabNav} />
>   </Stack.Navigator>
> </NavigationContainer>
> )
> ```



@satya164 , I do testing for same configuration with react-navigation v6 It's working fine as expected for Example First but If i configured as Example second, then whenever I called redux dispatch action, screen are re-render.

@tmaly1980 , can you please suggest me solution, how you solve this issue. It might be help-full. I also attached my configuration for your insight.

```
const TabScreens = () => (
  <Tab.Navigator
    screenOptions={{ headerShown: false, tabBarShowLabel: false }}>
    <Tab.Screen name="homeScreen" component={HomeScreen} />
    <Tab.Screen name="myGalaxyScreen" component={MyGalaxyScreen} />
    <Tab.Screen name="createGalaxyScreen" component={CreateGalaxyScreen} />
    <Tab.Screen name="activityScreen" component={ActivityScreen} />
    <Tab.Screen name="profileScreen" component={ProfileScreen} />
  </Tab.Navigator>
);
```
```
<NavigationContainer>
  <Stack.Navigator screenOptions={{headerShown: false}}>
    <Stack.Screen name="bottomTab" component={TabScreens} />
    <Stack.Screen name="updateProfileScreen" component={UpdateProfileScreen} />
    <Stack.Screen hotosCreateGalaxyScreen" component={ManagePhotosCreateGalaxyScreen} />
  </Stack.Navigator>
</NavigationContainer>
```
