### ISSUE TITLE
Why do you people constantly change import locations and other stuff?

### ISSUE THREAD

**Issue by gezginrocker** [react-navigation/react-navigation#6874]
I've been trying to learn RN for the last few months and it has been like hell thanks to react-navigation team. Every tutorial I try to follow has became obsolete, because you people are constantly breaking and changing stuff. Every project I start or try to update, I'm wasting time trying to fix problems caused by react-navigation. I'm very close to quitting RN and switching to Flutter, and it is thanks to you people.

**Comment by satya164** [comment]
Thanks for being so nice to us for providing you a library for free.

**Comment by gezginrocker** [comment]
Many communities are providing a library for free, but not torturing their users by constantly breaking stuff. This is the first time I'm writing an angry message at Github, because I really had it with this library. If you don't know how to maintain it properly, then hand it to people capable of please.

**Comment by satya164** [comment]
Your refund will be on the way.
