### ISSUE TITLE
TypeError : undefined is not an object (evaluating 'this.props.navigation.navigate')

### ISSUE THREAD

**Issue by ktk38** [react-navigation/react-navigation#6876]
### TypeError : undefined is not an object (evaluating 'this.props.navigation.navigate')

**What causes I get an error when I click login or sign up**

**How Can I fix That?**

![login](https://user-images.githubusercontent.com/45520860/74692710-7cc1be80-51f9-11ea-9a33-3d9134fdb1e8.jpg)

![library](https://user-images.githubusercontent.com/45520860/74692714-8519f980-51f9-11ea-853e-f6fadf733937.jpg)

import React from 'react';
import { View,Text,StyleSheet,TouchableOpacity } from 'react-native';

export default class Welcome extends React.Component{
    render(){
        return(
            <View style={styles.container}>
                <TouchableOpacity style={styles.touchable}
                onPress={() => this.props.navigation.navigate('Login')} >
                    <Text style={styles.text}>Logins</Text>
                </TouchableOpacity>
                <TouchableOpacity style={styles.touchable}
                onPress={() => this.props.navigation.navigate('Signin')}>
                    <Text style={styles.text}>Signins</Text>
                </TouchableOpacity>
                </View>
        )
    }
};

const styles = StyleSheet.create({
container:{
    flex:1,
    backgroundColor:"#fff",
    justifyContent:'center',
    alignItems:'center'
},
touchable:{
    width:100,
    height:50,
    backgroundColor:'blue',
    marginTop:20,
    justifyContent:'center',
    alignItems:'center',
    backgroundColor:'red',
    borderRadius:0.8
},
text :{
    color:'white'
}

});

![WELCOME](https://user-images.githubusercontent.com/45520860/74692530-a0383980-51f8-11ea-8d7c-ed7c53973cd9.jpg)
import React from 'react';
import {createSwitchNavigator, createAppContainer} from 'react-navigation';
import Welcome from "../pages/Welcome";
import Login from '../pages/Login';
import Signin from '../pages/Signin';

const AppSwitchNavigator = createSwitchNavigator(
  {
    Welcome: {
      screen: Welcome
    },
    Signin: {
      screen: Signin
    },
    Login: {
      screen: Login
    }
  },
  {
    initialRouteName: 'Welcome'
  }
);
export default createAppContainer(AppSwitchNavigator);

![router](https://user-images.githubusercontent.com/45520860/74692532-a29a9380-51f8-11ea-9227-df6b6bdd6a93.jpg)

import React from 'react';
import {
  View,
  Text,
  StatusBar,
  Dimensions,
  TouchableOpacity
} from 'react-native';

import Router from './src/lib/Router'

export default class App extends React.Component{
  render() {
    return (
      <Router/>
    )
  }
};

![app](https://user-images.githubusercontent.com/45520860/74692539-b0e8af80-51f8-11ea-8ad6-2b2ca8fa8d36.jpg)

**Comment by satya164** [comment]
Closing due to no response.
