### ISSUE TITLE
Modals can't be transparent without changing ThemeContext

### ISSUE THREAD

**Issue by Jarred-Sumner** [react-navigation/react-navigation#6877]
**Current Behavior**
Say you're on iOS and you want to show a modal with a transparent background.
 
All views have a background color set by default, so instead of the modal being transparent, it shows the system background color.

https://github.com/react-navigation/react-navigation/blob/1a28c299b5e3f0805eb6e9ea3cf5e9cc90c7a280/packages/native-stack/src/views/NativeStackView.tsx#L73-L79

Currently, to make it transparent, you'd need to set a custom `ThemeProvider` above the stack, which would override `colors.background`.

Example:

```jsx
const TransparentThemeProvider = ({ children }) => {
  const currentTheme = useTheme();
  const newTheme = React.useMemo(() => {
    const theme = cloneDeep(currentTheme);
    theme.colors.background = "transparent";
    return theme;
  }, [currentTheme]);
  return <ThemeProvider value={newTheme}>{children}</ThemeProvider>;
};
```

**Expected Behavior**

It'd be great if there was a way to ensure it is transparent when it should be without overriding the ThemeContext. For example, if `stackPresentation` is `transparentModal`, then the background should be null or `transparent`.

This functionality works on `@react-navigation/stack` via the following props:
- `cardStyle`
- `cardOverlayEnabled`
- `cardShadowEnabled`

**Your Environment**
```
├─ @react-navigation/core@5.1.2
│  ├─ @react-navigation/routers@^5.0.1
├─ @react-navigation/native-stack@5.0.3
├─ @react-navigation/native@5.0.3
│  └─ @react-navigation/core@^5.1.2
├─ @react-navigation/routers@5.0.1
├─ @react-navigation/stack@5.0.3
├─ react-navigation-animated-switch@0.4.1
├─ react-navigation-shared-element@0.5.0
```

**Comment by satya164** [comment]
We can remove the background if `stackPresentation` is `transparentModal`. Do you want to send a PR?

**Comment by Joaojuby** [comment]
Was having an issue with a modal stack in a partial migration from v4 to v5 and I would never find out to fix it wasn't it for this.

Also, we don't even use the ThemeContext in our app (well we do now) so a clarification in the docs or migration guide would also be useful aside from a PR with the proposed change

**Comment by satya164** [comment]
Hey, native-stack has been moved to [software-mansion/react-native-screens](https://github.com/software-mansion/react-native-screens). Please track the issue here: https://github.com/software-mansion/react-native-screens/issues/356
