### ISSUE TITLE
In createBottomTabNavigator not call Listener first time click.

### ISSUE THREAD

**Issue by singheshadev** [react-navigation/react-navigation#6880]
**Current Behavior**

- Not call Event tab change listener 

**Expected Behavior**

const unsubscribe = navigation.addListener('tabPress', e => {
    // Prevent default behavior
    e.preventDefault();

    // Do something manually
    // ...
  });
-> NOt call this Listener first when tab change for second time it's work
-> Please check live https://snack.expo.io/?platform=android&name=createBottomTabNavigator%20%C2%B7%20React%20Navigation&dependencies=%40react-native-community%2Fmasked-view%40%5E0.1.1%2C%40react-navigation%2Fnative%40%5E5.0.5%2C%40react-navigation%2Fbottom-tabs%40%5E5.0.5%2C%40react-navigation%2Fdrawer%40%5E5.0.5%2C%40react-navigation%2Fmaterial-bottom-tabs%40%5E5.0.5%2C%40react-navigation%2Fmaterial-top-tabs%40%5E5.0.5%2C%40react-navigation%2Fnative-stack%40%5E5.0.5%2C%40react-navigation%2Fstack%40%5E5.0.5%2Creact-native-gesture-handler%401.5.2%2Creact-native-reanimated%401.4.0%2Creact-native-safe-area-context%400.6.0%2Creact-native-screens%402.0.0-alpha.12&sourceUrl=https%3A%2F%2Freactnavigation.org%2Fexamples%2F5.x%2Fbottom-tab-prevent-default.js

**How to reproduce**

- Click on change tab and check Listener execute or not.

**Your Environment**

| software                      | version |
| ----------------------------- | ------- |
| iOS or Android                |
| @react-navigation/native      |
| @react-navigation/bottom-tabs |
| react-native                  |

**Comment by WoLewicki** [comment]
When I first click the `Home` tab, while beeing in `Home` or `Settings`, the event fires. Can you be more specific about what you consider a bug there?

**Comment by singheshadev** [comment]
Hi WoLewicki,
Thanks for replay but issue when click on first time tab event not execute.

i have 4 tab in app.
This code for second tab in app.
constructor(props){
        super(props);
        this.state={
            isShow: false
        };

        props.navigation.addListener('tabPress', e => {
            EventRegister.emit('tabChangeListner', "statistic"); //Issu for this block Method
        });
    }

Start to load 1st tab when open app after click on second tab(as code about screen). Block not execute click on 1st time.
Block call when click second time in tab.

**Comment by WoLewicki** [comment]
I think it doesn't emit because the tab isn't rendered before you navigate to it for the first time, so there is no event listener till that time. Does it solve your issue?

**Comment by evancloutier** [comment]
@WoLewicki 👋 I'm experiencing the same issue trying to upgrade from v3 -> v5. I agree with the event not registering because it isn't rendered prior to navigating to it, but is there a way to pre-render tabs/work around this? Documentation isn't clear about that part.

I'm trying to have haptic feedback when my tabs are pressed, for context.

**Comment by WoLewicki** [comment]
@evancloutier  https://reactnavigation.org/docs/bottom-tab-navigator#lazy is it the thing you need?

**Comment by evancloutier** [comment]
@WoLewicki looks like it-- thanks. I can make a PR to amend the docs around events if needed.

**Comment by iiagodias** [comment]
Solution?

**Comment by iiagodias** [comment]
> @WoLewicki looks like it-- thanks. I can make a PR to amend the docs around events if needed.

In createBottomTabNavigator not call Listener first time click, solution for first time click?
