### ISSUE TITLE
How to hide tab bar component when leaving the tab screens

### ISSUE THREAD

**Issue by onuroo** [react-navigation/react-navigation#6884]
**Problem**

I have one tab.navigator which have tab.screen inside.

When I routed a nested screen, the bottom tab bar is not hidden.

**Note:**
Used custom tab bar component.

Thanks for your answers..

**Comment by crcass** [comment]
I had a similar issue and solved it using https://reactnavigation.org/docs/en/screen-options-resolution.html#setting-parent-screen-options-based-on-child-navigators-state as a starting place. Here's my solution:

Helper function
```
const getIsTabBarVisible = (route) => {
  const routeName = route.state
    ? route.state.routes[route.state.index].name
    : route.params?.screen || 'Tab1';

  switch (routeName) {
    case 'Tab1':
    case 'Tab2':
    case 'Tab3':
    case 'Tab4':
      return true;
    default:
      return false;
  }
};
```
Then, in my TabNavigator
```
    <Tab.Navigator
      initialRouteName="Tab1"
      screenOptions={({route}) => ({
        tabBarVisible: getIsTabBarVisible(route),
      })}
      tabBar={renderTabBar}
      tabBarOptions={{
        activeTintColor: brand.light,
        inactiveTintColor: grays.medium,
      }}
    >
     <Tab.Screen
       component={Tab1}
       screen="Tab1"
     />
     <Tab.Screen
       component={Tab2}
       screen="Tab2"
     />
     <Tab.Screen
       component={Tab3}
       screen="Tab3"
     />
     <Tab.Screen
       component={Tab4}
       screen="Tab4"
     />
</Tab.Navigator>
```

I have a bunch of other options set but this is basic of example of how I solved it. Hope this helps!

**Comment by satya164** [comment]
You should nest the tab navigator inside the first screen of stack navigator instead

```
- Stack
  - FirstScreen
    - Tab
      - Home
      - Settings
  - SecondScreen
  - ThirdScreen
```

https://reactnavigation.org/docs/en/nesting-navigators.html#parent-navigators-ui-is-rendered-on-top-of-child-navigator
