### ISSUE TITLE
v5 undefined is not an object (evaluating 'Object.keys(_routers.CommonActions)')

### ISSUE THREAD

**Issue by abhishek1305** [react-navigation/react-navigation#6885]
I get this error when I add bottomTabNavigator in my app. I was getting different error with react-navigation/native: 5.0.0 then I upgraded the react-navigation/native version from 5.0.0 to 5.0.5. And now I am getting this error. 

Package versions i am using
"@react-navigation/bottom-tabs": "^5.0.5",
"@react-navigation/native": "^5.0.5",
"@react-navigation/stack": "^5.0.5",

Here is my code snippet

```const HomeTabNavigator = () => (
  <Tab.Navigator > 
    <Tab.Screen name='Home' component={HomeScreen}/>
    <Tab.Screen name='Monitor' component={MonitorScreen}/>
  </Tab.Navigator>
) 
export default function AppNavigator() {
  return (<NavigationContainer ><HomeStack.Navigator initialRouteName="Home">
      <HomeStack.Screen
          name="Home"
          component={HomeTabNavigator}
          options = {{
            headerShown:false
          }}
        />

        <HomeStack.Screen
          name="RescheduleConfirmation"
          component={RescheduleConfirmationScreen}
        />
        <HomeStack.Screen name="Calendar" component={CalendarViewScreen} />
        <HomeStack.Screen
          name="AppointmentBooking"
          component={AppointmentBookingScreen}
        />
        <HomeStack.Screen
          name="BPClassification"
          component={BPClassificationScreen}
        />
        <HomeStack.Screen name="ReferAFriend" component={ReferAFriendScreen} />
        <HomeStack.Screen
          name="ArticleDetail"
          component={ArticleDetailScreen}
        />
      </HomeStack.Navigator> 
    </NavigationContainer>
  );
```

Error screenshot: 

![WhatsApp Image 2020-02-18 at 19 45 13](https://user-images.githubusercontent.com/20300934/74743959-5c404580-5287-11ea-8b55-d41805c439be.jpeg)

**Comment by abhishek1305** [comment]
I changed versions of packages to : 
@react-navigation/drawer": "^5.0.5",
@react-navigation/native": "^5.0.5",
@react-navigation/stack": "^5.0.0",

and ran expo start -c 

It solved my issue.

**Comment by coutureJ** [comment]
I had the same issue yesterday, "expo start -c" also fixed the problem. I wonder why it happen.
