### ISSUE TITLE
Material Top Tab Navigator - Native module cannot be null.

### ISSUE THREAD

**Issue by chrissnape** [react-navigation/react-navigation#6886]
I am currently updating to V5 react navigation, and having trouble with the basic part of material top tab navigator.

When I do `const Tab = createMaterialTopTabNavigator();` I get 'Native module cannot be null' in the simulator, createStackNavigator() works fine, and when I remove this line it works fine too.
It's the simplest of things, I just don't know what's causing it.

This is on iPhone 11 simulator running iOS 13.3, all my navigation packages are the latest as I just started this yesterday.

**Comment by satya164** [comment]
Make sure you have linked Reanimated and gesture handler. The should be automatically linked as of latest version of React Babe and you just need to run `pod install` in `ios` folder.

**Comment by chrissnape** [comment]
It worked, thanks very much!
