### ISSUE TITLE
Replace from a nested navigator to another doesn't work

### ISSUE THREAD

**Issue by sofianegargouri** [react-navigation/react-navigation#6889]
**Current Behavior**

Here are my navigators:

```
import React from 'react'
import { NavigationContainer } from '@react-navigation/native'
import { createStackNavigator } from '@react-navigation/stack'
import { createBottomTabNavigator } from '@react-navigation/bottom-tabs'

import { MatchesContainer } from '../matches'
import { LeaderboardContainer } from '../leaderboard'
import { NewsContainer } from '../news'
import { ProfileContainer } from '../profile'
import { SignInContainer } from '../user/signin'
import { SignUpContainer } from '../user/signup'
import { InitialLoading } from '../initial-loading'
import { NavigationIcon } from '../components'

const AuthStack = createStackNavigator()

const AuthNavigator = () => (
  <AuthStack.Navigator headerMode="none">
    <AuthStack.Screen name="SignIn" component={SignInContainer} />
    <AuthStack.Screen name="SignUp" component={SignUpContainer} />
  </AuthStack.Navigator>
)

const Tab = createBottomTabNavigator()

const MainNavigator = (theme) => () => (
  <Tab.Navigator
    initialRouteName="Matches"
    tabBarOptions={{
      showLabel: false,
      style: {
        backgroundColor: theme.colors.backgroundColor,
      },
    }}
  >
    <Tab.Screen
      component={MatchesContainer}
      name="Matches"
      options={{
        tabBarIcon: (props) => <NavigationIcon {...props} name="md-calendar" color={theme.colors.textColor} />,
      }}
    />
    <Tab.Screen
      component={LeaderboardContainer}
      name="Leaderboard"
      options={{
        tabBarIcon: (props) => <NavigationIcon {...props} name="md-trophy" color={theme.colors.textColor} />,
      }}
    />
    <Tab.Screen
      component={NewsContainer}
      name="News"
      options={{
        tabBarIcon: (props) => <NavigationIcon {...props} name="md-paper" color={theme.colors.textColor} />,
      }}
    />
    <Tab.Screen
      component={ProfileContainer}
      name="Profile"
      options={{
        tabBarIcon: (props) => <NavigationIcon {...props} name="md-person" color={theme.colors.textColor} />,
      }}
    />
  </Tab.Navigator>
)

const RootStack = createStackNavigator()
const switchNavigator = (theme) => (
  <RootStack.Navigator initialRouteName="Init" headerMode="none">
    <RootStack.Screen name="Init" component={InitialLoading} />
    <RootStack.Screen name="App" component={MainNavigator(theme)} />
    <RootStack.Screen name="Auth" component={AuthNavigator} />
  </RootStack.Navigator>
)

export default (theme) => () => (
  <NavigationContainer>
    {switchNavigator(theme)}
  </NavigationContainer>
)
```

When I run the following code from `Initial
```
const navigation = useNavigation()
navigation.replace('Auth')
```
I get redirected to my Auth stack, as expected.

However, if I run
```
const navigation = useNavigation()
navigation.replace('SignIn')
```

I get the following error:

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-02-19 at 00 07 15](https://user-images.githubusercontent.com/4323986/74785940-d682c100-52ab-11ea-818a-57c0cced4d61.png)

While I understand it might be logical to prevent navigation from a nested screen to another, I think we should be able to navigate from a nested screen to a parent sibling.

When I try to navigate from `SignIn` to  `App`, I'm getting the same error

This issue is only available for `replace`, because `navigate` works as expected

**Expected Behavior**

- `replace` should  be working with nested screens, since `replace` does

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | both
| @react-navigation/native       | 5.0.5
| react-native                   | 0.61.3
| expo                           | /
| node                           | v12.13.1
| yarn                    | 1.19.1

**Comment by satya164** [comment]
```js
navigation.replace('Auth', { screen: 'SignIn' })
```

**Comment by sofianegargouri** [comment]
Not working

![image](https://user-images.githubusercontent.com/4323986/74914793-5485bb80-53c3-11ea-9e66-da2be195de8d.png)

**Comment by james-mallory** [comment]
+1
@sofianegargouri Did you end up finding a solution? I'm having the same problem.

**Comment by sofianegargouri** [comment]
Nop, didn't find a workaround either.

@satya164 please re-open this issue.

**Comment by james-mallory** [comment]
@sofianegargouri 
Our use case is to replace this screen with one in a different stack. Since `replace` is a stack action, maybe what it is trying to do is replace the current screen with another screen in that same stack. If that's so, I think it's not intuitive and the documentation should be improved to indicate that better. Perhaps also different error, and maybe a new feature that navigates + removes previous screen.

In any case, my almost good solution is to have a boolean in global store that's something like `goHereAfterGoingBack`. Then in the component where I would have called `replace`, I instead do the following:
```
dispatchAction(setGoHereAfterGoingBack('targetScreen'));
navigation.goBack();
```
Then on every screen, I check for that state. If it exists, I navigate to that page. If it exists and is the same as the current screen, I reset `goHereAfterGoingBack` to null. 

It's convoluted and it would be awesome if there were a built in solution, but it doesn't seem like there is 🤷‍♂ . I hope this helps you.

**Comment by EugeneDraitsev** [comment]
@satya164 Why this issue is closed? Your solution is not working for this this case. Moreover, `react-navigation`  doesn't seem to hav any possible workaround to reset nested stacks.  I pretty sure that you need to reopen it

**Comment by tayloraleach** [comment]
Please re-open. I am facing this issue as well

**Comment by raajnadar** [comment]
Give a snack example to reproduce this issue.

**Comment by jtomaszewski** [comment]
FYI, I tried making a workaround by keeping a reference to the root's `navigation` prop in the nested screens and calling `navigation.replace` on that, but it doesn't work. It redirects me to URL like this `http://localhost:19007/?params=%5Bobject%20Object%5D&screen=Chat` instead .

So indeed, seems like a workaround is not possible.

**Comment by chr4ss12** [comment]
bump
