### ISSUE TITLE
After installing react navigation app is getting crashed all the time. 

### ISSUE THREAD

**Issue by SupriyaGo** [react-navigation/react-navigation#6892]
**Current Behavior**
I have installed "npm install @react-navigation/native" and all the dependencies with it "npm install react-native-reanimated react-native-gesture-handler react-native-screens react-native-safe-area-context @react-native-community/masked-view". After installation when I build the app and , its building successfully but getting crashed after installing on my phone.

- What code are you running and what is happening?
I have installed the library on basic react-native app, not additional code is there.

**Expected Behavior**
App should open and run successfully.

- What do you expect should be happening?
when I uninstall the dependency  react-native-safe-area-context, app is running but it suppose to be needed to use react navigation. 

**Your Environment**

I am using windows machine, testing on my android phone.

package.json

{
"name": "Money",
"version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@react-native-community/masked-view": "^0.1.6",
    "@react-navigation/bottom-tabs": "^5.0.5",
    "@react-navigation/drawer": "^5.0.5",
    "@react-navigation/native": "^5.0.5",
    "@react-navigation/stack": "^5.0.5",
    "react": "16.9.0",
    "react-native": "0.61.5",
    "react-native-gesture-handler": "^1.6.0",
    "react-native-reanimated": "^1.7.0",
    "react-native-screens": "^2.0.0-beta.7",
    "react-native-vector-icons": "^6.6.0"
  },
  "devDependencies": {
    "@babel/core": "^7.6.2",
    "@babel/runtime": "^7.6.2",
    "@react-native-community/eslint-config": "^0.0.5",
    "babel-jest": "^24.9.0",
    "eslint": "^6.5.1",
    "jest": "^24.9.0",
    "metro-react-native-babel-preset": "^0.56.0",
    "react-test-renderer": "16.9.0"
  },
  "jest": {
    "preset": "react-native"
  }
}

**Comment by goepoet** [comment]
i have same problem

**Comment by wolfhawk163** [comment]
I have the same problem ,but it runs smoothly before today.And i have found  when i don't install react-native-screens the app works correctly,

**Comment by thijs-qv** [comment]
Can confirm, crashing immediately after launch on Android, no problems on iOS.
It seems there is a Java class missing.
```
java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/swiperefreshlayout/widget/SwipeRefreshLayout;
```

**Comment by SupriyaGo** [comment]
@thijs-qv Thanks buddy, it worked. Now my app is running. 
Can you please explain a little about the issue , I am not familiar with Android that  much. Thanks in advance.

**Comment by thijs-qv** [comment]
Not much to explain really; a missing dependency caused a missing class error which caused a crash. These dependencies are mentioned in the react-native-screens documentation:
https://github.com/software-mansion/react-native-screens#usage-with-react-navigation-without-expo

**Comment by dantasfiles** [comment]
> Add the following dependencies to app/build.gradle to avoid this error

This used to be in the React Navigation installation instructions.
https://github.com/react-navigation/react-navigation.github.io/blob/5f9027e3d67110be3562d21c685d5363c7f17083/website/versioned_docs/version-5.x/getting-started.md
It was removed 7 days ago.

**Comment by jimkhan** [comment]
i have same problem. i have tried every solution given here. Still not working. i'm using (windows)

**Comment by gregoryfm** [comment]
@jimkhan Did you find a solution?

**Comment by jimkhan** [comment]
> @jimkhan Did you find a solution?

I don’t get any perfect solution.  But it may occur for graphics memory capacity. My graphic memory is below 2gb and it is Shared memory.

**Comment by nicolasopt** [comment]
I have same problem and figure out "@react-native-community/masked-view": "^0.1.6" module effect this issue but still not solved it.
