### ISSUE TITLE
gestureEnabled does not enable swipe to go back on Android

### ISSUE THREAD

**Issue by thijs-qv** [react-navigation/react-navigation#6893]
**Current Behavior**

StackNavigator option gestureEnabled does not enable gesture navigation on Android: swiping to go back does not work. On iOS it is working without issue.

**Expected Behavior**

Swipe to go back enabled on Android as well.

**How to reproduce**

```
import 'react-native-gesture-handler';

import React from 'react';
import { View, Text } from 'react-native';

import { NavigationContainer } from '@react-navigation/native';
import { createStackNavigator } from '@react-navigation/stack';

const Stack = createStackNavigator();

const App = () => {

  return (
    <NavigationContainer>
    <Stack.Navigator initialRouteName="Screen 1" screenOptions={{gestureEnabled: true}}>
      <Stack.Screen name="Screen 1" component={Screen1} />
      <Stack.Screen name="Screen 2" component={Screen2} />
    </Stack.Navigator>
  </NavigationContainer>
  );
};

function Screen1(props) {
  return (
    <View style={{flex: 1, justifyContent: 'center', alignItems: 'center'}}>
      <Text onPress={() => props.navigation.navigate('Screen 2')}>Press to navigate to screen 2</Text>
    </View>
  )
}

function Screen2() {
  return (
    <View style={{flex: 1, justifyContent: 'center', alignItems: 'center'}}>
      <Text>This is screen 2</Text>
    </View>
  )
}

export default App;
```

Run app on Android, press text to navigate to screen2, try to navigate back via gesture.

**Your Environment**

Android 
    "@react-native-community/masked-view": "^0.1.6",
    "@react-navigation/native": "^5.0.5",
    "@react-navigation/stack": "^5.0.5",
    "react": "16.8.6",
    "react-native": "0.60.5",
    "react-native-gesture-handler": "^1.6.0",
    "react-native-reanimated": "^1.7.0",
    "react-native-safe-area-context": "^0.7.3",
    "react-native-screens": "^2.0.0-beta.7"

**Comment by WoLewicki** [comment]
Did you try to swipe the screen from up to down on Android?

**Comment by thijs-qv** [comment]
My bad, I wasn't aware that the Android gesture was from up to down.
Thank you.
