### ISSUE TITLE
No height in headerStyle

### ISSUE THREAD

**Issue by franciscailleAstus** [react-navigation/react-navigation#6896]
**Current Behavior**
There is no possibility to set a header height.

![image](https://user-images.githubusercontent.com/44379473/74848100-28a40080-5305-11ea-8bfe-b665a32970b0.png)

**Expected Behavior**
There should be a "height" property.

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |
| @react-navigation/native       | 5.0.5
| @react-navigation/stack        | 5.0.5
| react-native-gesture-handler   |
| react-native-safe-area-context |
| react-native-screens           |
| react-native                   |
| expo                           | 36
| node                           |
| npm or yarn                    |

**Comment by WoLewicki** [comment]
Is it a native-stack or stack navigator?

**Comment by franciscailleAstus** [comment]
> Is it a native-stack or stack navigator?

Hi @WoLewicki ,
It's a native-stack. Thanks for your support.

**Comment by franciscailleAstus** [comment]
Oh, height is not available into native-stack. My bad.
