### ISSUE TITLE
Android app crashes after react-native-screens step of Getting Started

### ISSUE THREAD

**Issue by dantasfiles** [react-navigation/react-navigation#6897]
**Current Behavior**
After the [_Getting Started_](https://reactnavigation.org/docs/en/getting-started.html) procedure, the resulting Android app crashes. I narrowed it down to the `npm install react-native-screens` step.

**Expected Behavior**
Android app should not crash after following _Getting Started_ instructions.

**How to reproduce**
- Create a bare React Native 0.61.5 app
`npx react-native init RNTest`
- Install `react-native-screens` 2.0.0-beta.10 as part of [_Getting Started_](https://reactnavigation.org/docs/en/getting-started.html)
`npm install react-native-screens`
- Run Android app
`npx react-native run-android`
- App crashes (not a RedBox error, a full crash to Android home screen)

The [original _Getting Started_ instructions](https://github.com/react-navigation/react-navigation.github.io/blob/5f9027e3d67110be3562d21c685d5363c7f17083/website/versioned_docs/version-5.x/getting-started.md#installing-dependencies-into-a-bare-react-native-project) up until about [a week ago](https://github.com/react-navigation/react-navigation.github.io/commit/bfbad4557fe785dac6317ff76a26c70ea776df2b#diff-1d3693c4ce7677d9de451d5d469ba4b1) had the section:
> To finalize installation of `react-native-screens` for Android, add the following two lines to dependencies section in `android/app/build.gradle`:
```gradle
implementation 'androidx.appcompat:appcompat:1.1.0-rc01'
implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0-alpha02'
```

If you follow those original instructions and add the two lines to `android/app/build.gradle`, the app works.

**Edited to add:** You can alternately follow the lead of the [RN 0.62.0-rc2 template](https://github.com/facebook/react-native/blob/d4d8887b5018782eeb3f26efa85125e6bbff73e4/template/android/app/build.gradle#L188) and add:
```
implementation "androidx.swiperefreshlayout:swiperefreshlayout:1.0.0"
```
which seems to work so far.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| Android                 | 10
| @react-navigation/native       | 5.0.5
| react-native                   | 0.61.5
| expo                           | N/A
| node                           | 13.9.0
| npm or yarn                    | 6.13.7

**Comment by ctopher7** [comment]
update your react-native-screens to the latest version (2.0.0 beta 8) everybody is encountering error before this version

**Comment by dantasfiles** [comment]
> the latest version (2.0.0 beta 8)

I updated my original post to indicate that I am running beta 8.

**Comment by dantasfiles** [comment]
I upgraded to `react-native-screens@2.0.0-beta.9`, released today. It still doesn't work in a vanilla React Native installation.

I did notice this message during `npx react-native run android`. I don't know if it's important.
```
> Task :react-native-screens:compileDebugJavaWithJavac
C:\Users\Daniel\.gradle\caches\transforms-2\files-2.1\b4b3f50028f4886635a10951a0445687\jars\classes.jar: D8: Type `androidx.swiperefreshlayout.widget.SwipeRefreshLayout` was not found, it is required for default or static interface methods desugaring of `void com.facebook.react.views.swiperefresh.ReactSwipeRefreshLayout.setRefreshing(boolean) 
C:\Users\Daniel\.gradle\caches\transforms-2\files-2.1\b4b3f50028f4886635a10951a0445687\jars\classes.jar: D8: Interface `androidx.swiperefreshlayout.widget.SwipeRefreshLayout$OnRefreshListener` not found. It's needed to make sure desugaring of `com.facebook.react.views.swiperefresh.SwipeRefreshLayoutManager$1` is correct. Desugaring will assume that this interface has no default method.
```

**Comment by dantasfiles** [comment]
The [documentation change](https://reactnavigation.org/docs/en/getting-started.html) was rolled back, so I'm going to close this
