### ISSUE TITLE
React Navigation's docs include very convoluted examples

### ISSUE THREAD

**Issue by CostachescuCristinel** [react-navigation/react-navigation#6898]
I am posting here because I could find no other way to post about issues with the Docs.
Feel free to delete the post after reading it, but please, spread the word internally between React Navigation's Docs maintainers and developers as this is not something to be left unhandled.

To anyone that is starting up with React Native, and just barely discovered this thing called React Navigation - but also to some experienced developers, like me - the examples in the latest React Navigation docs are very convoluted. The worst example actually comes from a guide, which is ridiculous:

https://reactnavigation.org/docs/en/auth-flow.html

This guide already introduces the reader to the (most likely) unknown concepts of:
* React Hooks
* reducers
* state management libraries
* React Context
* AsyncStorage

It happened to find myself needing guidance for an authentication flow with React Navigation 5, and after some time reading the guide, and asking for help on StackOverflow, and re-reading the guide a few times, it just snapped: the answer to that guide was as simple as `You can conditionally render routes using JSX's conditional rendering`. Please have a look at the post on SO that I made prior to posting this, where I have also posted a minimal example:
https://stackoverflow.com/questions/60301963/react-navigation-5-block-back-navigation-after-login

This is not an isolate case. Most of React Native's docs only include examples using React Hooks, while giving no explanation to what they are (they shouldn't, it's not part of React Navigation after all), or any hint to where to read more (they should do this, just a link like `Read more about React Hooks here`).

Please, revise the docs to include minimal, working examples without extras. The examples should include mainly the traditional class and SFC based components, and React Hooks based examples if that would be of any help.
In places where the explanation is actually about things related to React Hooks it's fine to only include hooks based examples, but traditional class/SFC examples would be appreciated if possible.

**Comment by satya164** [comment]
Feel free to send pull requests to update and simplify docs.
