### ISSUE TITLE
How remove bottom border of header

### ISSUE THREAD

**Issue by Piero87** [react-navigation/react-navigation#6899]
**Current Behavior**

In react navigation 4 I could remove the bottom border of the header, in version 5 I can't, this is a screen of the border:

<img width="438" alt="Schermata 2020-02-19 alle 22 05 19" src="https://user-images.githubusercontent.com/768952/74876692-6ab05f00-5364-11ea-96a0-26bdd19c9305.png">

And this is the code I use:

```
    <Stack.Navigator
      initialRouteName="Page1"
      screenOptions={{
  headerStyle: {
    backgroundColor: commonStyles.mainBGColor,
    borderBottomWidth: 0,
  },
  headerTintColor: '#fff',
  headerTitleStyle: commonStyles.headerText,
}}
    >
```

**Expected Behavior**

I want remove the bottom border i add some arrow to indicate the border to make my self more clear:
<img width="438" alt="Schermata 2020-02-19 alle 22 05 19" src="https://user-images.githubusercontent.com/768952/74876866-c844ab80-5364-11ea-89f3-52ed9e872117.png">

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS                  |
| @react-navigation/stack        |
| react-native-gesture-handler   |
| react-native-safe-area-context |
| react-native-screens           |
| react-native                   |
| yarn                    |

**Comment by WoLewicki** [comment]
It looks like the prop connected with it is shadowOffset here (for iOS): https://github.com/react-navigation/react-navigation/blob/4578849ebf48e39855b2dcbb84b5419e60846390/packages/stack/src/views/Header/HeaderBackground.tsx#L38 so you can change it by providing something like `          shadowOffset: { height: 0, width: 0 }`

**Comment by pmadruga** [comment]
This is what worked for me:

``` 
screenOptions={{
        headerHideShadow: true
      }}
```

**Comment by WoLewicki** [comment]
@pmadruga I am afraid it worked for you in `native-stack`, not in `stack`. Am I right?

**Comment by hkadyanji** [comment]
@Piero87 adding `shadowColor: 'transparent'` in `headerStyle` worked for me

**Comment by Mangor1no** [comment]
> @Piero87 adding `shadowColor: 'transparent'` in `headerStyle` worked for me

This solution works for me! Thank you a lot!

**Comment by pmadruga** [comment]
> @pmadruga I am afraid it worked for you in `native-stack`, not in `stack`. Am I right?

You're right - thanks for pointing it out.

**Comment by NishargShah** [comment]
```
screenOptions={{
    headerStyle: { elevation: 0 }
}}
```

works fine in android :smile:

**Comment by goodryanboy** [comment]
borderBottomColor: 'transparent' works for me ios

**Comment by dereknahman** [comment]
Here's what I did, because my header had a backgroundColor that I didn't want to override.

```
 options={{
          title: false,
          headerTransparent: true,
        }}
```

**Comment by yasir128** [comment]
<NavigationContainer independent={true}>
      <Stack.Navigator
        screenOptions={{
          headerStyle: {elevation: 0},
        }}>
        <Stack.Screen
          name="Login"
          component={Login}
          options={{headerShown: false}}
        />
        <Stack.Screen
          name="NewAccount"
          component={NewAccount}
          options={{
            title: '',
          }}
        />
      </Stack.Navigator>
    </NavigationContainer>


HELP FOR ME

**Comment by yasir128** [comment]
<NavigationContainer independent={true}>
      <Stack.Navigator
        screenOptions={{
          headerStyle: {elevation: 0},
        }}>
        <Stack.Screen
          name="Login"
          component={Login}
          options={{headerShown: false}}
        />
        <Stack.Screen
          name="NewAccount"
          component={NewAccount}
          options={{
            title: '',
          }}
        />
      </Stack.Navigator>
    </NavigationContainer>

**Comment by Mrjavaci** [comment]
Help me

**Comment by darrylyoung** [comment]
The following worked for me:

```css
headerStyle: {
  ... // your other styles
  shadowColor: 'transparent',
}
```

**Comment by rn04techmelo** [comment]
bc sare chawln mar rahe han kse ka nhi chl rha

**Comment by gtallen13** [comment]
`headerTransparent:true,` worked for me

**Comment by hungdev** [comment]
> The following worked for me:
> 
> ```css
> headerStyle: {
>   ... // your other styles
>   shadowColor: 'transparent', // ios
>   elevation: 0  // android
> }
> ```

thank you. it worked for me

**Comment by russiann** [comment]
`headerShadowVisible` works for me:

https://reactnavigation.org/docs/native-stack-navigator/#headershadowvisible

```js
<Stack.Navigator
  initialRouteName="home"
  screenOptions={{
    headerShadowVisible: false
  }}
>
```

**Comment by fmacedoo** [comment]
> `headerShadowVisible` works for me:
> 
> https://reactnavigation.org/docs/native-stack-navigator/#headershadowvisible
> 
> ```js
> <Stack.Navigator
>   initialRouteName="home"
>   screenOptions={{
>     headerShadowVisible: false
>   }}
> >
> ```

Worked pretty well at `"@react-navigation/native-stack": "^6.2.5"`.
No other option replied here worked.

**Comment by fmacedoo** [comment]
> `headerShadowVisible` works for me:
> 
> https://reactnavigation.org/docs/native-stack-navigator/#headershadowvisible
> 
> ```js
> <Stack.Navigator
>   initialRouteName="home"
>   screenOptions={{
>     headerShadowVisible: false
>   }}
> >
> ```

Worked pretty well at `"@react-navigation/native-stack": "^6.2.5"`.
No other option replied here worked.

**Comment by ashkan-esz** [comment]
> 



> `headerShadowVisible` works for me:
> 
> https://reactnavigation.org/docs/native-stack-navigator/#headershadowvisible
> 
> ```js
> <Stack.Navigator
>   initialRouteName="home"
>   screenOptions={{
>     headerShadowVisible: false
>   }}
> >
> ```

tnx , this one woked for me.

**Comment by varda-altusnova** [comment]
@alamothe have u managed to resolve that?

**Comment by uthpalax** [comment]
> headerShadowVisible: false

This is the answer for me.
