### ISSUE TITLE
Tab Sort Bug

### ISSUE THREAD

**Issue by gitcow** [react-navigation/react-navigation#6900]
**Current Behavior**

Tabs render in numerical order when tab names are fully numerical strings like "12345" or "779001". Bug is showing up in at least versions 5.0.0 through 5.0.5.

**Expected Behavior**

Tabs should render in the order in which they are defined as child screens of the parent tab navigator; no re-sorting should occur.

**How to reproduce**

Here's a simple [snack](https://snack.expo.io/@expocow/tab-sort-bug).
If it helps, I did a bit of sleuthing and was able to pinpoint where the unwanted reordering is happening: Line 190 of @react-navigation/core/src/useNavigationBuilder.tsx. `Object.keys` apparently does not respect the order in which the keys where created when they are numerical strings, go figure. Replacing this line with an explicit mapping from `children` to `routeNames` should do the trick based on my tinkering in the debugger. Something like `routeNames = children.map(child => child.props.name)`. Hope that helps!

In the meantime, I was able to work around this bug by mixing in non-numeric text into the tab names.

**Comment by satya164** [comment]
Woah what a weird issue.
