### ISSUE TITLE
Only custom content

### ISSUE THREAD

**Issue by mathritter** [react-navigation/react-navigation#6901]
Drawer navigator won't support only custom content, it will ask for at least one screen

Code:
```
function CustomDrawerContent(props) {
  return (
    <DrawerContentScrollView {...props}>
      <DrawerItemList {...props} />
      <DrawerItem label={() => <View style={styles.listItem}><Text style={styles.listItemText}>Login </Text></View>} onPress={() => props.navigation.navigate("Home")}/>
      <DrawerItem label={() => <View style={styles.listItem}><Text style={styles.listItemText}>LOGIN </Text></View>} onPress={() => props.navigation.navigate("Login")}/>
    </DrawerContentScrollView>
  );
}

function MyNavigation() {
  return (
    <Drawer.Navigator initialRouteName={"Home"} drawerContent={props => CustomDrawerContent(props)}
    drawerStyle={{
      backgroundColor: '#121e40',
      width: 240,
    }}>
    </Drawer.Navigator>
  );
}

```
**Expected Behavior**

- What do you expect should be happening?
I wanted to fully customize the drawer, but it seems I HAVE to put at least one screen as **child**

**How to reproduce**
the code below won't work, if I change "My navigation" to the code below it will work fine:

```
function MyNavigation() {
  return (
    <Drawer.Navigator initialRouteName={"Home"} drawerContent={props => CustomDrawerContent(props)}
    drawerStyle={{
      backgroundColor: '#121e40',
      width: 240,
    }}>
      <Drawer.Screen name="Home" component={Home} /> 
    </Drawer.Navigator>
  );
}

```

I just downloaded the react native and its bibs, been 2 days.

**Comment by WoLewicki** [comment]
Navigators must have at least one screen, it is one of the fundamentals of the library. You can always create a custom component that will imitate a drawer but it cannot be a navigator if there are no screens present there.

**Comment by mathritter** [comment]
I'm sorry, I skipped part of the documentation where you can use components as labels. Thanks!
