### ISSUE TITLE
Previous screen state mutation in push same screen multiple times with different data

### ISSUE THREAD

**Issue by nitesh3539** [react-navigation/react-navigation#6902]
Let's suppose I have a screen A and I have to push the same screen A multiple times with different data by using React Navigation Push API. If I go back to the previous screen I have seen the top screen data. on each of the previous screen. I want to handle this such that the state of the previous screen does not change after pushing same screen. Please let me know if anyone have handled this type of situations.

Thanks

**Comment by WoLewicki** [comment]
The state shouldn't change for the previous screens. Look at the first snack here: https://reactnavigation.org/docs/en/params.html, it shows that the screens keep their params. Is this what you mean?

**Comment by satya164** [comment]
Closing due to no response.
