### ISSUE TITLE
Authentication flows and nesting navigators

### ISSUE THREAD

**Issue by hooorvat** [react-navigation/react-navigation#6903]
**Current Behavior**

Now the navigation structure is as follows:

- RootStack:
    - AuthStack
        - CityScreen
        - LoginScreen
        - SignupScreen
    - HomeStack
        - MapScreen
        - Other Screens...
    - EngineWorksScreen

**Expected Behavior**

In my case, the user selects a city, after which he logs in, then goes to the Map screen. After that, he can change the city (in this case, the token is deleted, as with logout) or just logout with saving the city. In the first case, the city selection screen should appear (there are no problems with this). But in the second case, it should get on the screen with authorization, while it should be able to return to the city selection screen by swiping to the left or using goBack. I studied https://reactnavigation.org/docs/en/auth-flow.html, but my case is not covered there. I used to use Switch Navigator, and called reset (), where I indicated the navigation state I needed and the screen that should be displayed. Now, when calling reset, for some reason, the swipe to the left is unavailable ...
I can’t think of how declarative it is for me, how you advise changing the history of nested navigators.

**How to reproduce**

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | 
| @react-navigation/native       | 5.0.1
| @react-navigation/stack        | 5.0.1
| react-native-gesture-handler   | 1.5.6
| react-native-safe-area-context | 0.7.2
| react-native-screens           | 2.0.0-beta.2
| react-native                   | 0.61.5
| expo                           | -
| node                           | 10.15.0
| npm or yarn                    | 6.11.3

**Comment by WoLewicki** [comment]
How does your reset function look like? Can you provide a snack with minimal configuration to show this setup?
