### ISSUE TITLE
Double tap on header back arrow

### ISSUE THREAD

**Issue by loodsite** [react-navigation/react-navigation#6905]
**Current Behavior**

- If you double tap on header back arrow two screen were popped from the navigation stack.

**Expected Behavior**

- Only one screen should be popped, instead of two. 

**How to reproduce**
`
<Stack.Navigator>
  
<Stack.Screen name="ScreenA" component={ScreenA} options={{headerShown: false}} />
<Stack.Screen name="ScreenB" component={ScreenB} options={{headerShown: false}} />
<Stack.Screen name="ScreenC" component={ScreenC} />

</Stack.Navigator>
`
- Navigate: ScreenA -> ScreenB -> ScreenC
- When trying to go back from ScreenC to ScreenB double tap on header back arrow

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| Android                 | 9.0 |
| @react-navigation/native       | 5.0.6 |
| @react-navigation/stack        | 5.0.6 |
| react-native-gesture-handler   | 1.6.0 |
| react-native-safe-area-context | 0.7.3 |
| react-native-screens           | 2.0.0-beta.8 |
| react-native                   | 0.61.5 |
| node                           | 12.11.0 |
| npm                 | 6.13.7 |

**Comment by WoLewicki** [comment]
Shortest snack repro: https://snack.expo.io/@wolewicki/double-tap-back-button-bug

**Comment by osdnk** [comment]
Taking a look at this

**Comment by osdnk** [comment]
This issues should be gone with 040f5db

**Comment by loodsite** [comment]
@osdnk thanks. I will test it in new release.

**Comment by loodsite** [comment]
@WoLewicki and @osdnk this double tap back arrow bug is still present although I have updated on the latest versions currently available.

`"dependencies": {
    "@react-native-community/masked-view": "^0.1.7",
    "@react-navigation/bottom-tabs": "^5.1.0",
    "@react-navigation/native": "^5.0.8",
    "@react-navigation/stack": "^5.1.0",
    "react": "16.9.0",
    "react-native": "0.61.5",
    "react-native-gesture-handler": "^1.6.0",
    "react-native-reanimated": "^1.7.0",
    "react-native-safe-area-context": "^0.7.3",
    "react-native-screens": "^2.2.0",
  },`

Same thing when double tapping on button calling function `navigation.goBack()`.

This need to be reopen.
