### ISSUE TITLE
Adding a Drawer Screen with an empty path

### ISSUE THREAD

**Issue by LinusU** [react-navigation/react-navigation#6906]
**Current Behavior**

I'm adding a drawer to my existing app which is using URL routing. I'm trying to add the drawer without affecting the existing URLs, but I cannot seem to have one of the drawer paths be empty. I'm trying to use the following config to `useLinking`:

```javascript
config: {
  Main: { path: '' },
  Landing: { path: '' },
  ShoppingCart: { path: 'restaurants/:restaurantId/cart' },
  Restaurant: { path: 'restaurants/:restaurantId' },
  RestaurantList: { path: 'restaurants' },
  VerifyPayment: { path: 'verify' },
  Settings: { path: 'settings' }
}
```

With the following view hierarchy:

```javascript
<NavigationContainer initialState={initialState} ref={navigationRef}>
  <Drawer.Navigator>
    <Drawer.Screen name='Main'>
      {() => (
        <Stack.Navigator initialRouteName='Landing'>
          <Stack.Screen name='Landing' component={Landing} options={{ header: () => null }} />
          <Stack.Screen name='Restaurant' component={Restaurant} options={{ header: () => null }} />
          <Stack.Screen name='RestaurantList' component={RestaurantList} />
          <Stack.Screen name='ShoppingCart' component={ShoppingCart} options={{ header: () => null }} />
          <Stack.Screen name='VerifyPayment' component={VerifyPayment} />
        </Stack.Navigator>
      )}
    </Drawer.Screen>

    <Drawer.Screen name='Settings' component={Settings} />
  </Drawer.Navigator>
</NavigationContainer>
```

This breaks the routing so that every time I reload I get to the start page.

**Expected Behavior**

I want to have the routing like this:

- `/` = `Main` -> `Landing`
- `/restaurants` = `Main` -> `RestaurantList`
- `/restaurants/:id` = `Main` -> `Restaurant`
- `/settings` = `Settings`

**How to reproduce**

https://snack.expo.io/SkiA6G37I

For some reason the Snack can't import `@react-navigation/stack`, but you can copy the `index.js` into an empty React Native or Expo project to test it out.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Web |
| @react-navigation/native       | 5.0.6
| @react-navigation/drawer       | 5.0.6
| react-native-reanimated        | 1.4.0
| react-native-gesture-handler   | 1.5.6
| react-native-safe-area-context | 0.6.0
| react-native-screens           | 2.0.0-alpha.12
| react-native                   | 0.61.4
| expo                           | 36.0.2
| node                           | Node v12.12.0
| npm or yarn                    | npm 6.13.6

**Comment by WoLewicki** [comment]
What you can do is make all the config a nested config inside the drawer. Also, you shouldn't pass empty strings as paths, because they are ignored and the state is not correctly resolved then. All considered it would look like this: 
```
config = {
    Main: {
      path: 'Main',
      screens: {
        Landing: 'landing',
        ShoppingCart: 'restaurants/:restaurantId/cart',
        Restaurant: 'restaurants/:restaurantId',
        RestaurantList: 'restaurants',
        VerifyPayment: 'verify',
        Settings: 'settings',
      },
    },
  };
```
You can try passing an empty string as a URL and check if it resolves to Main->Landing. The rest should good then. Let me know if it worked for you.

**Comment by LinusU** [comment]
Amazing 😍 that works!

Did I miss it in the documentation, or is this something that should be added to the documentation?

> Also, you shouldn't pass empty strings as paths, because they are ignored and the state is not correctly resolved then.

Hmm, how would I have my landing page on just `https://my-website.com/` instead of `/landing` then?

If I add `path: 'landing'` as in your example, when navigating to the restaurant list and then back to the landing screen, my web-browser now shows `/landing` which is undesirable 🤔 

----- 

Actually I spoke too soon 🙈 

When adding another page to the drawer I cannot navigate back to "Main" after visiting something else.

Example:

```javascript
config: {
  Main: {
    path: 'main',
    screens: {
      Landing: { path: 'landing' },
      ShoppingCart: { path: 'restaurants/:restaurantId/cart' },
      Restaurant: { path: 'restaurants/:restaurantId' },
      RestaurantList: { path: 'restaurants' }
    }
  },
  Settings: {
    path: 'settings'
  }
}
```

```javascript
<NavigationContainer initialState={initialState} ref={navigationRef}>
  <Drawer.Navigator initialRouteName='Main'>
    <Drawer.Screen name='Main'>
      {() => (
        <Stack.Navigator initialRouteName='Landing'>
          <Stack.Screen name='Landing' component={Landing} options={{ header: () => null }} />
          <Stack.Screen name='Restaurant' component={Restaurant} options={{ header: () => null }} />
          <Stack.Screen name='RestaurantList' component={RestaurantList} />
          <Stack.Screen name='ShoppingCart' component={ShoppingCart} options={{ header: () => null }} />
        </Stack.Navigator>
      )}
    </Drawer.Screen>

    <Drawer.Screen name='Settings' component={Settings} />
  </Drawer.Navigator>
</NavigationContainer>
```

With this setup I can load the site and navigate around inside "Main" and everything works.

I can also open the drawer and press "Settings" and get to the settings page. At this point the url correctly shows `/settings`.

But when I then open the drawer and press "Main" the url correctly changes back to the page I were at, but it just renders a gray screen. Reloading the page at that point works (since the url is correct) and brings up the correct page.

**Comment by WoLewicki** [comment]
> Did I miss it in the documentation, or is this something that should be added to the documentation?
Nested config is mentioned in the `deepLinking` guide.
> Hmm, how would I have my landing page on just https://my-website.com/ instead of /landing then?
Doesn't the landing page open up when you just open the app because it is the initial state of the app (initial route in the drawer and stack navigators)? So if you don't provide the path, the state will resolve to the initial one and open the `landing` page. Am I right?

About the last paragraph, I think it is the problem with the drawer navigator: https://github.com/react-navigation/drawer/issues/162

**Comment by LinusU** [comment]
> Nested config is mentioned in the `deepLinking` guide.

Great 👍 
 
> > Hmm, how would I have my landing page on just https://my-website.com/ instead of /landing then?
> 
> Doesn't the landing page open up when you just open the app because it is the initial state of the app (initial route in the drawer and stack navigators)? So if you don't provide the path, the state will resolve to the initial one and open the `landing` page. Am I right?

It does show the correct page when first navigating to the website, but navigating to any other page and then back again will show `/landing` in the adress bar. Also, navigating to `/landing` will also work so it will be like having two pages with the same content 🤔 
 
> About the last paragraph, I think it is the problem with the drawer navigator: https://github.com/react-navigation/drawer/issues/162

Thanks, will follow that issue as well!

**Comment by WoLewicki** [comment]
Try making the path an empty string instead of 'landing'. It should then cut that part, but I am not sure that it integrates perfectly with the browser history API. Hope it works well.

**Comment by LinusU** [comment]
Sorry for the late reply, making the path an empty string seems to work indeed, thanks!

> Also, you shouldn't pass empty strings as paths, because they are ignored and the state is not correctly resolved then.

You did write this though, is that no longer a concern? 🤔

**Comment by WoLewicki** [comment]
Passing an empty string as a path gives back `undefined` as a state, which resolves to the initial navigation state, so it works in this case.

**Comment by LinusU** [comment]
Ah, I see, thank you for your help!
