### ISSUE TITLE
Header Title left aligned with react-native-web

### ISSUE THREAD

**Issue by hjpsievert** [react-navigation/react-navigation#6910]
**Current Behavior**
Header for Stack Navigator page is left-aligned when using react-native-web, on iOS it is centered

- What code are you running and what is happening?
React Navigation 5.0.2 on Expo with react-native-web 0.11.7

- Include a screenshot or video if it makes sense.

**Expected Behavior**
I did read in the documentation that the header is configured to display left for Android, but would think it makes more sense to center it for web as it is for iOS

- What do you expect should be happening?
Would prefer for header on web pages to be centered

- Include a screenshot or video if it makes sense.

**How to reproduce**
[Snack Repro](https://snack.expo.io/@hjpsievert/header-alignment-issue-with-web)
It works as expected on iOS and Android, on web the title is left-aligned, not sure why the headerRight is not shown, it is visible and functional when I run my project in Expo. 

**Your Environment**

| software                      | version |
| ----------------------------- | ------- |
| iOS or Android                |iOS13.3.1
| @react-navigation/native      |5.02
| @react-navigation/bottom-tabs |5.02
| react-native-screens          |2.0.0-alpha.12
| react-native                  |0.61.5
| expo                          |36.0.0
| node                          |2.15.0
| npm or yarn                   |yarn 1.22.0

**Comment by satya164** [comment]
https://reactnavigation.org/docs/en/stack-navigator.html#headertitlealign

**Comment by hjpsievert** [comment]
Hi Satyajit:

Thanks for the fast response, I must have overlooked this option or maybe it is a more recent addition. I added it to my code and it works as expected.

 

Best regards,

Hans-Jürgen (HJ) Sievert
:: 3770 Vancouver Drive, Reno, NV 89511
:: Cell (775) 742-7425 Home (775) 853-4599

::  <mailto:hj.sievert@gmail.com> hj.sievert@gmail.com

::  <http://www.linkedin.com/in/hjsievert> http://www.linkedin.com/in/hjsievert
