### ISSUE TITLE
navigationRef does not provide many from navigation like setOptions 

### ISSUE THREAD

**Issue by kopax** [react-navigation/react-navigation#6913]
I am using `@react-navigation/native` with 

1. `@react-navigation/drawer`
2. `@react-navigation/stack`

Within (1), I want to get the navigation object of (2), the only way that was possible was to use:

```jsx
import { createRef } from 'react';

export const navigationRef = createRef();

export function navigate(name, params) {
  return navigationRef.current?.navigate(name, params);
}

export function goBack() {
  return navigationRef.current?.goBack();
}

export function setOptions(options) {
  console.log(navigationRef.current);
  return navigationRef.current?.setOptions(options);
}
```

Unfortunately, it seems that `navigationRef` provide less than it should

## Expected

I expect to be able to access any of the `navigation` method

## Result

`navigationRef.current` is degraded and miss most of the helpers

## Possible fix

Add more helper to the ref.

## Versions

```
    "@react-navigation/drawer": "^5.0.0-alpha.41",
    "@react-navigation/native": "^5.0.0-alpha.22",
    "@react-navigation/stack": "^5.0.0-alpha.63",
```

**Comment by WoLewicki** [comment]
You can use `navigation.dangerouslyGetParent()` to get the parent navigation props: https://reactnavigation.org/docs/en/navigation-prop.html#dangerouslygetparent---get-parent-navigators-navigation-prop. Does this fix your issue?

**Comment by satya164** [comment]
The `ref` isn't a replacement for the `navigation` prop. 

Any screen specific operations such as updating options must be done from the screen. A middleware somewhere else doesn't know which screen is focused so it doesn't make sense for it to update options which may not be valid for the currently focused screen.
