### ISSUE TITLE
How can I declare a not found route for my page 404 using react-navigation 5?

### ISSUE THREAD

**Issue by kopax** [react-navigation/react-navigation#6914]
**Current Behavior**

I am working on a react-native application build with expo SDK.

When I am calling `useNavigation().navigate('${Math.random().toString}')`, I get:

```
The action 'NAVIGATE' with payload '{"name":"0.1978411114028611"}' was not handled by any navigator.
console.<computed> @ index.js:1
error @ muteWarnings.fx.ts:34
r @ backend.js:6
(anonymous) @ useNavigationHelpers.tsx:53
(anonymous) @ NavigationContainer.tsx:127
basicStateReducer @ react-dom.development.js:16445
dispatchAction @ react-dom.development.js:17044
(anonymous) @ NavigationContainer.tsx:122
dispatch @ useNavigationHelpers.tsx:46
dispatch @ useNavigationCache.tsx:83
acc.<computed> @ useNavigationCache.tsx:93
onPress @ 3.chunk.js:751
touchableHandlePress @ index.js:122
_performSideEffectsForTransition @ index.js:730
_receiveSignal @ index.js:642
touchableHandleResponderRelease @ index.js:428
domProps.<computed> @ index.js:65
callCallback @ react-dom.development.js:336
invokeGuardedCallbackDev @ react-dom.development.js:385
invokeGuardedCallback @ react-dom.development.js:440
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:454
executeDispatch @ react-dom.development.js:584
executeDispatchesInOrder @ react-dom.development.js:609
executeDispatchesAndRelease @ react-dom.development.js:713
executeDispatchesAndReleaseTopLevel @ react-dom.development.js:722
forEachAccumulated @ react-dom.development.js:692
runEventsInBatch @ react-dom.development.js:739
runExtractedPluginEventsInBatch @ react-dom.development.js:880
handleTopLevel @ react-dom.development.js:5803
batchedEventUpdates$1 @ react-dom.development.js:24401
batchedEventUpdates @ react-dom.development.js:1415
dispatchEventForPluginEventSystem @ react-dom.development.js:5894
attemptToDispatchEvent @ react-dom.development.js:6010
dispatchEvent @ react-dom.development.js:5914
unstable_runWithPriority @ scheduler.development.js:697
runWithPriority$2 @ react-dom.development.js:12149
discreteUpdates$1 @ react-dom.development.js:24417
discreteUpdates @ react-dom.development.js:1438
dispatchDiscreteEvent @ react-dom.development.js:5881
Show 9 more frames
```

Can I catch this and create a 404 ? How can I declare a not found route for my Page 404 using react-navigation 5? 

**Expected Behavior**

I expect to catch all unknown routes like in this explanation

https://stackoverflow.com/questions/52763749/react-navigation-error-boundary-that-can-navigate

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | all
| @react-navigation/native       | 5
| @react-navigation/stack        | 5
| react-native-gesture-handler   | 1.6.0
| react-native-safe-area-context | 0.7.3
| react-native-screens           | 2.0.0-beta.7
| expo                           | sdk 36
| node                           | 13
| npm or yarn                    |  6

**Comment by Rangoons** [comment]
I've been trying to solve this same thing. I took a dive into [getStateFromPath](https://github.com/react-navigation/react-navigation/blob/master/packages/core/src/getStateFromPath.tsx) which is where the initial url (assuming your use case is for handling malformed deep links too) gets parsed and passed into the navigation container. You have the ability to write and pass your own `getStateFromPath` but the default one does so much else for us already, it doesn't make sense to have to write our own just to be able to handle a link that doesn't exist. It doesn't seem possible to pass a catch all into the route config object for  `useLinking` either.  Hopefully we get a resolution soon

**Comment by satya164** [comment]
https://reactnavigation.org/docs/configuring-links#handling-unmatched-routes-or-404

**Comment by AngelTrinidad** [comment]
Any solution for this? In the latest version of react-navigation doesn't work the handle for unmatched routes.

**Comment by pke** [comment]
> [reactnavigation.org/docs/configuring-links#handling-unmatched-routes-or-404](https://reactnavigation.org/docs/configuring-links#handling-unmatched-routes-or-404)

This does not work as described there. The handler is ignored and the error message from the OP still shows up.
