### ISSUE TITLE
unmountOnBlur is not working

### ISSUE THREAD

**Issue by jaimedeverall** [react-navigation/react-navigation#6915]
**Current Behavior**

Currently, my setup is:

Tab1
  --s1 (initial route)
  --s12
Tab2
  --s2 (initial route)
  --s21
Tab3
  --s3 (initial route)
Tab4
  --s4 (initial route)

I set `unmountOnBlur={true}` as a prop on Tab2. 

When I navigate to `s21` from `s1` and then switch to `Tab1` through the bottom tab, I am taken back to `s1` as expected. However now when I click `Tab2` through the bottom tab, `s21` is still showing meaning that `Tab2` was not unmounted. If `Tab2` had actually unmounted then I would see `s2` because it is the initial route of `Tab2`.

- What code are you running and what is happening?
- Include a screenshot or video if it makes sense.

**Expected Behavior**

I expect to see `s2` when switching to `Tab2` through the bottom tab navigator.

- What do you expect should be happening?
- Include a screenshot or video if it makes sense.

**How to reproduce**

Here is the link to the snack:
https://snack.expo.io/HyaiF_6Q8 (kudos to @ShaneFairweather for the snack)

- You must provide a way to reproduce the problem. If you are having an issue with your machine or build tools, the issue belongs on another repository as that is outside of the scope of React Navigation.
- Either re-create the bug on [Snack](https://snack.expo.io) or link to a GitHub repository with code that reproduces the bug.
- Explain how to run the example app and any steps that we need to take to reproduce the issue from the example app.
- Keep the repro code as simple as possible, with the minimum amount of code required to repro the issue.
- Before reporting an issue, make sure you are on latest version of the package.

**Your Environment**

| software                      | version |
| ----------------------------- | ------- |
| iOS or Android                |
| @react-navigation/native      | 5.0.1
| @react-navigation/bottom-tabs |5.0.5
| react-native-screens          |2.0.0-beta.8
| react-native                  |0.61.5
| expo                          |
| node                          |
| npm or yarn                   |

**Comment by WoLewicki** [comment]
The prop is called `unmountOnBlur`, maybe you misspelled it. Also, your snack doesn't provide the screens, so I created a similar one with all the needed screens: https://snack.expo.io/@wolewicki/3fade7. It looks like the Tab2 is properly unmounted on blur. Does this fix your issue?

**Comment by ShaneFairweather** [comment]
It works correctly initially when navigating with the bottom tab navigator, but in your example snack if you were to try to navigate from "s1" to "s21" with the Button component, then future Tab2 from bottom redirect straight to "s21" instead of "s2".

**Comment by ShaneFairweather** [comment]
You can see the issue in this snack: https://snack.expo.io/@shanefairweather/unmountonblur

**Comment by jaimedeverall** [comment]
Yes apologies for not providing screens in my initial snack and thank you for attending to this issue. I did spell it correctly, my bad for mispelling it in the issue description.

I still have the same problem that @ShaneFairweather is having. If you navigate to "s21" from "s1" and then switch tabs back to "s1" (by switching bottom tabs), it seems that tab2 is not unmounted.

**Comment by satya164** [comment]
The screen is unmounted. The reason you see the same screen when you press the tab again is when you do `navigate('Tab2', { screen: 's12' })`, you're passing `{ screen: 's12' }` as `params` to `Tab2`. The `params` for the route don't get reset on navigating away. So when you go back to the tab, the screen from params gets rendered.

If you want to reset params, you can do something like this in your tab:

```js
React.useEffect(() =>
  navigation.addListener("blur", () =>
    navigation.setParams({ screen: undefined })
  )
);
```

**Comment by crobinson42** [comment]
Is there a way to dispatch to a specific stack? This would solve the problem mentioned possibly.

Example:

```
const Stack = createStackNavigator()

....

Stack.dispatch( CommonActions.reset([]) )
```

**Comment by satya164** [comment]
`reset([])` is not going to fix it, also passing an empty array isn't valid. please see my comment https://github.com/react-navigation/react-navigation/issues/6915#issuecomment-591533068 which both mentions the reason and how to prevent it.

**Comment by Rodrigo816** [comment]
> The screen is unmounted. The reason you see the same screen when you press the tab again is when you do `navigate('Tab2', { screen: 's12' })`, you're passing `{ screen: 's12' }` as `params` to `Tab2`. The `params` for the route don't get reset on navigating away. So when you go back to the tab, the screen from params gets rendered.
> 
> If you want to reset params, you can do something like this in your tab:
> 
> ```js
> function useResetScreenOnBlur() {
>   useFocusEffect(
>     React.useCallback(() => {
>       return () => navigation.setParams({ screen: undefined });
>     }, [navigation])
>   );
> };
> 
> // Then use it
> function Tab2() {
>   useResetScreenOnBlur();
> }
> ```

Do I still have to use ` unmountOnBlur: true ` for this to work right?

**Comment by felippepuhle** [comment]
@satya164 thanks!

As I'm still using `unmountOnBlur` I've made some changes:

```
function useResetScreenOnBlur() {
  const navigation = useNavigation()

  useEffect(() => {
    return () => {
      navigation.setParams({ screen: undefined })
    }
  }, [navigation])
}
```

**Comment by chismadalina** [comment]
> The screen is unmounted. The reason you see the same screen when you press the tab again is when you do `navigate('Tab2', { screen: 's12' })`, you're passing `{ screen: 's12' }` as `params` to `Tab2`. The `params` for the route don't get reset on navigating away. So when you go back to the tab, the screen from params gets rendered.
> 
> If you want to reset params, you can do something like this in your tab:
> 
> ```js
> function useResetScreenOnBlur() {
>   useFocusEffect(
>     React.useCallback(() => {
>       return () => navigation.setParams({ screen: undefined, params: undefined });
>     }, [navigation])
>   );
> };
> 
> // Then use it
> function Tab2() {
>   useResetScreenOnBlur();
> }
> ```

This doesn't fix the issue for me :(

**Comment by SpectreWulf** [comment]
> 
> 
> > The screen is unmounted. The reason you see the same screen when you press the tab again is when you do `navigate('Tab2', { screen: 's12' })`, you're passing `{ screen: 's12' }` as `params` to `Tab2`. The `params` for the route don't get reset on navigating away. So when you go back to the tab, the screen from params gets rendered.
> > If you want to reset params, you can do something like this in your tab:
> > ```js
> > function useResetScreenOnBlur() {
> >   useFocusEffect(
> >     React.useCallback(() => {
> >       return () => navigation.setParams({ screen: undefined, params: undefined });
> >     }, [navigation])
> >   );
> > };
> > 
> > // Then use it
> > function Tab2() {
> >   useResetScreenOnBlur();
> > }
> > ```
> 
> This doesn't fix the issue for me :(

Yes tried this fix, didn't work for me too. 

The params are not getting reset on unmount, to first screen of the stack in tab2.
Is there any fix for this issue in future / any workarounds?

**Comment by parichay101** [comment]
const goBack = ({
  currentRoute, currentNavigation, toRouteName, params
}) => {
  if(toRouteName) {
    currentNavigation.navigate(toRouteName, params)

    // The dispatch action below is used to clear the current screen from route state and replace it with
    // The initialRoute of that stack (if we are not using `inital: false` prop while navigating)
    
    // NOTE: This dispatch action below can be avoided if we use `initial: false` prop while navigating.
    currentNavigation.dispatch((state) => {
      let routes = state.routes.filter(r => r.name !== currentRoute.name)

       
      if(routes.length === 0) {
        routes = [{ name: state.routeNames[0] }]
      }
      return CommonActions.reset({
        ...state,
        routes,
        index: routes.length - 1,
      })
    })
  } else if(currentNavigation.canGoBack()) {
    currentNavigation.goBack()
  } else{
    console.warn('cannot go back')
  }
}

// Screen s1 (Tab1)
 navigateToS21 = () => {
   const { navigation, route } = props
   navigation.navigate('Tab2', {
     screen: 's21',
     params: {
       // your params here,
       fromRouteName: route.name,
     }
   })
 }

 // Screen s21 (Tab2)

 backHandler = () => {
  const { navigation, route } = props
  goBack({
    currentNavigation: navigation,
    currentRoute: route,
    toRouteName: route.params.fromRouteName
  })
}

// How this all works

/* Taking @jaimedeverall's example, suppose I want to jump from s1(Tab1) to s21(Tab2).

Then from s1 we pass a fromRouteName so our goBack handler can navigate to this passed route.

NOTE: It's important that we pass navigation object of s21 to goBack(). So that it can clear the proper routes.
*/

/*
 WARNING: I've just made this as a quickfix to solve my use-case.
 It may have some conceptual flaws that I might not be aware of.
 Do let me know about this approach and it's downfall.
 Thanks :)
*/

**Comment by SpectreWulf** [comment]
Thanks @parichay101 

@chismadalina 
I also found a much more simpler workaround / little less hacky method for this:

On a particular screen/ screens inside a Tab Configuration where you want the behavior of the app to go back to the first screen for that Tab when the user taps on it as follow:

```
   <HomeTab.Screen 
              name="ScreenStackA" 
              component={A_separate_screen_stack} 
              listeners={
               ({navigation}) => ({
                 tabPress: (event) => {
                    event.preventDefault();
                    navigation.navigate('ScreenStackA', {
                       screen: NAME_OF_THE_SCREEN_INSIDE_THE_STACK
                    });
               }
            })
         }
    />
```

**Comment by chiefchief** [comment]
> @satya164 thanks!
> 
> As I'm still using `unmountOnBlur` I've made some changes:
> 
> ```
> function useResetScreenOnBlur() {
>   const navigation = useNavigation()
> 
>   useEffect(() => {
>     return () => {
>       navigation.setParams({ screen: undefined })
>     }
>   }, [navigation])
> }
> ```

Thanks, i've used your solution, and did it in tab navigator,
```
    <Tab.Navigator>
      <Tab.Screen name="FirstScreen" component={FirstScreen} />
      <Tab.Screen
        name="SecondScreen"
        component={SecondScreenStack}
        listeners={({navigation}) => ({blur: () => navigation.setParams({screen: undefined})})}
      />
      <Tab.Screen name="ThirdScreen" component={ThirdScreen} />
    </Tab.Navigator>
```

**Comment by ecemac** [comment]
> > @satya164 thanks!
> > As I'm still using `unmountOnBlur` I've made some changes:
> > ```
> > function useResetScreenOnBlur() {
> >   const navigation = useNavigation()
> > 
> >   useEffect(() => {
> >     return () => {
> >       navigation.setParams({ screen: undefined })
> >     }
> >   }, [navigation])
> > }
> > ```
> 
> Thanks, i've used your solution, and did it in tab navigator,
> 
> ```
>     <Tab.Navigator>
>       <Tab.Screen name="FirstScreen" component={FirstScreen} />
>       <Tab.Screen
>         name="SecondScreen"
>         component={SecondScreenStack}
>         options={{unmountOnBlur: true}}
>         listeners={({navigation}) => ({blur: () => navigation.setParams({screen: undefined})})}
>       />
>       <Tab.Screen name="ThirdScreen" component={ThirdScreen} />
>     </Tab.Navigator>
> ```

Works like a charm, thank you so much!

**Comment by ycdaskin** [comment]
> > @satya164 thanks!
> > As I'm still using `unmountOnBlur` I've made some changes:
> > ```
> > function useResetScreenOnBlur() {
> >   const navigation = useNavigation()
> > 
> >   useEffect(() => {
> >     return () => {
> >       navigation.setParams({ screen: undefined })
> >     }
> >   }, [navigation])
> > }
> > ```
> 
> Thanks, i've used your solution, and did it in tab navigator,
> 
> ```
>     <Tab.Navigator>
>       <Tab.Screen name="FirstScreen" component={FirstScreen} />
>       <Tab.Screen
>         name="SecondScreen"
>         component={SecondScreenStack}
>         options={{unmountOnBlur: true}}
>         listeners={({navigation}) => ({blur: () => navigation.setParams({screen: undefined})})}
>       />
>       <Tab.Screen name="ThirdScreen" component={ThirdScreen} />
>     </Tab.Navigator>
> ```

Even this didn't work me. I don't know what am i doing different from other guys. But this worked:

`<Tab.Navigator>
      <Tab.Screen name="FirstScreen" component={FirstScreen} />
      <Tab.Screen
        name="SecondScreen"
        component={SecondScreenStack}
        options={{unmountOnBlur: true}}
        listeners={({navigation}) => ({focus: () => navigation.setParams({screen: "FirstScreenOfSecondScreenStack"})})}
      />
      <Tab.Screen name="ThirdScreen" component={ThirdScreen} />
    </Tab.Navigator>`

**Comment by fahad39** [comment]
> > @satya164 thanks!
> > As I'm still using `unmountOnBlur` I've made some changes:
> > ```
> > function useResetScreenOnBlur() {
> >   const navigation = useNavigation()
> > 
> >   useEffect(() => {
> >     return () => {
> >       navigation.setParams({ screen: undefined })
> >     }
> >   }, [navigation])
> > }
> > ```
> 
> Thanks, i've used your solution, and did it in tab navigator,
> 
> ```
>     <Tab.Navigator>
>       <Tab.Screen name="FirstScreen" component={FirstScreen} />
>       <Tab.Screen
>         name="SecondScreen"
>         component={SecondScreenStack}
>         options={{unmountOnBlur: true}}
>         listeners={({navigation}) => ({blur: () => navigation.setParams({screen: undefined})})}
>       />
>       <Tab.Screen name="ThirdScreen" component={ThirdScreen} />
>     </Tab.Navigator>
> ```

Works For me . Thank you so much.

**Comment by MorenoMdz** [comment]
I just spent the whole morning trying to have our params reset on navigation or programmatically, in our case is because we may receive a list of params from a deep linked query that affect our data fetching in the App, this solved the problem for me:

```js
      <BottomTab.Screen
        name="Explore"
        component={ExploreNavigator}
        options={({ route }) =>
          getBottomTabOptions({
            title: i18n.t('exploreBottomNavText'),
            iconName: 'search',
            route,
          })
        }
        listeners={({ navigation }) => ({
          blur: () => navigation.setParams({ params: undefined }),
        })}
      />

**Comment by CPeluti** [comment]
> > > @satya164 thanks!
> > > As I'm still using `unmountOnBlur` I've made some changes:
> > > ```
> > > function useResetScreenOnBlur() {
> > >   const navigation = useNavigation()
> > > 
> > >   useEffect(() => {
> > >     return () => {
> > >       navigation.setParams({ screen: undefined })
> > >     }
> > >   }, [navigation])
> > > }
> > > ```
> > 
> > 
> > Thanks, i've used your solution, and did it in tab navigator,
> > ```
> >     <Tab.Navigator>
> >       <Tab.Screen name="FirstScreen" component={FirstScreen} />
> >       <Tab.Screen
> >         name="SecondScreen"
> >         component={SecondScreenStack}
> >         options={{unmountOnBlur: true}}
> >         listeners={({navigation}) => ({blur: () => navigation.setParams({screen: undefined})})}
> >       />
> >       <Tab.Screen name="ThirdScreen" component={ThirdScreen} />
> >     </Tab.Navigator>
> > ```
> 
> Works For me . Thank you so much.

This also worked for me.
Shouldn't this behavior be documented as a warning on the [onBlur page](https://reactnavigation.org/docs/drawer-navigator/#unmountonblur) in the docs?

**Comment by DeepakSharma04** [comment]
unmountOnBlur not available in `@react-navigation/bottom-tabs v7.1.3`
```
 <Tab.Screen
                name="Profile"
                component={SettingScreen}
                options={{ tabBarLabel: stringsoflanguages.TABPROFILE, unmountOnBlur: true }}
                listeners={({ navigation }) => ({ blur: () => navigation.setParams({ screen: undefined }) })}
            />
```
Not working

**Comment by eeeman1** [comment]
> > [@satya164](https://github.com/satya164) Спасибо!
> > Как я все еще использую  `unmountOnBlur`Я внес некоторые изменения:
> > ```
> > function useResetScreenOnBlur() {
> >   const navigation = useNavigation()
> > 
> >   useEffect(() => {
> >     return () => {
> >       navigation.setParams({ screen: undefined })
> >     }
> >   }, [navigation])
> > }
> > ```
> 
> Спасибо, я использовал ваше решение, и сделал это в навигаторе вкладки,
> 
> ```
>     <Tab.Navigator>
>       <Tab.Screen name="FirstScreen" component={FirstScreen} />
>       <Tab.Screen
>         name="SecondScreen"
>         component={SecondScreenStack}
>         options={{unmountOnBlur: true}}
>         listeners={({navigation}) => ({blur: () => navigation.setParams({screen: undefined})})}
>       />
>       <Tab.Screen name="ThirdScreen" component={ThirdScreen} />
>     </Tab.Navigator>
> ```

not working

**Comment by eeeman1** [comment]
this doesn't work either

**Comment by eeeman1** [comment]
> Код ниже работает нормально:
> `listeners={({ navigation }) => ({ blur: () => navigation.setParams({ screen: undefined }) })}`

this doesn't work either

**Comment by eeeman1** [comment]
listeners={({ navigation }) => ({blur: () => navigation.goBack()})} 
working

**Comment by AyoParadis** [comment]
> > Код ниже работает нормально:
> > `listeners={({ navigation }) => ({ blur: () => navigation.setParams({ screen: undefined }) })}`
> 
> this doesn't work either

this does not work, did you find a solution?

**Comment by hailie-rei** [comment]
Hey, maybe my answer will be helpful.

Packages versions:
```js
    "@react-navigation/bottom-tabs": "7.15.9",
    "@react-navigation/native": "7.2.2",
    "@react-navigation/native-stack": "7.14.11",
```

My tabs:
```js
            <Tab.Navigator
                backBehavior={"history"}
                screenOptions={({route}) => ({...})}
            >
                <Tab.Screen name={'Home'}
                            component={ScreenHome}
                />
                ...
                <Tab.Screen name={'More'}
                            component={ScreenMore}
                            listeners={({navigation}) => ({
                                blur: () => {
                                    navigation.setParams({screen: 'MoreMenu'}); // THIS !!!!
                                },
                            })}
                />
            </Tab.Navigator>
```

ScreenMore:
```js
        <MoreStack.Navigator screenOptions={{headerShown: false}}>
            <MoreStack.Screen name={'MoreMenu'} component={ScreenMoreMenu}/>
            <MoreStack.Screen name={'MoreSettings'} component={ScreenMoreSettings}
            .......
            />
        </MoreStack.Navigator>
```

So I used `listeners`, but instead of setting screen parameter as undefined, I set the exact name of the screen that should be loaded.
