### ISSUE TITLE
Screens with transparent overlays don't behave when screens transition out

### ISSUE THREAD

**Issue by stevehollaar** [react-navigation/react-navigation#6916]
**Current Behavior**
I'm having some issues with the use of transparent overlays, after following the documentation at https://reactnavigation.org/docs/en/stack-navigator.html#transparent-modals
 - when pushing a screen above the overlay screen, the overlay flashes white, and stays white until the top-most screen is unmounted
 - when closing a screen that has an overlay, that transitions to 0 opacity, nothing on the screen can be tapped until the screen with the overlay is unmounted

**Expected Behavior**
 - The overlay should remain mounted and visible behind any screens that might open above it
 - The screen with the overlay should allow any touches to pass through to the lower screen as soon as it is transitioned out

**How to reproduce**
Follow the prompts here: https://snack.expo.io/B1H_SZi4U

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |iOS
| @react-navigation/native       |5.0.8
| @react-navigation/stack        |5.1.0
| react-native-gesture-handler   |
| react-native-safe-area-context |0.7.3
| react-native-screens           |
| react-native                   |
| expo                           |
| node                           |
| npm or yarn                    |

**Comment by satya164** [comment]
Instead of using the default overlay, you can render your own custom view inside the screen to achieve the behaviour you want.
