### ISSUE TITLE
base component without the functionality

### ISSUE THREAD

**Issue by zeitamin** [react-navigation/react-navigation#6917]
I need a bottom tab navigation under one of my screens to have two tabs that each one open up a modal to another screen which doesn't show the tab navigations in those modals, unfortunately, this isn't the case with the default tab navigation.  Is there any practice to make this happen without pain? or should I invent the wheel again?

**Comment by WoLewicki** [comment]
Sorry, but I can't understand what you mean. Can you provide a snack or some conceptual image of what you need?

**Comment by zeitamin** [comment]
@WoLewicki basically, I need to change the whole functionality without losing tab navigation looks.

**Comment by WoLewicki** [comment]
You cannot change the navigation functionality of the tab bars in the material bottom tabs. If you need to preserve the look, you can look at the source code and find how the views are defined.
