### ISSUE TITLE
[ios] TextInput immediately gets unfocused after navigating back

### ISSUE THREAD

**Issue by MaxBolotnyi** [react-navigation/react-navigation#6918]
**Current Behavior**
After going back from any screen, if you click on the text input, it will focus and unfocus immediately 

I am attaching 2 snack's playgrounds. It's present both on react-navigation 4 and 5 versions.

**Expected Behavior**
After going back from any screen, if you click on the text input, it should focus and stay focused

**How to reproduce**
1. Go to the second screen.
2. Go back.
3. Right after transition ends click on the textInput component.

**SNACK** 
React-navigation 4 - https://snack.expo.io/@shonsy/navigationandfocus
React-navigation 5 - https://snack.expo.io/@shonsy/newnav

**Your Environment**
    "react-navigation": "^4.0.10",
    "react-native-screens": "^2.0.0-alpha.20",
    "react-navigation-stack": "2.1.1",
    "react-native-gesture-handler": "^1.5.0",
    "react-native-safe-area-context": "^0.6.0",
    "@react-native-community/masked-view": "^0.1.1"

**OR**
   "react-native-screens": "^2.0.0-alpha.20",
    "@react-navigation/stack": "^5.0.0",
    "@react-navigation/native": "^5.0.0",
    "react-native-gesture-handler": "^1.5.0",
    "react-native-safe-area-context": "^0.6.0",
    "@react-native-community/masked-view": "^0.1.5"

**Comment by Rafal-JAR** [comment]
Having the same issue. On first screen load input focuses normally after navigating to another screen and back, for a short time the input will blur after focus.
```
"react-navigation": "^4.0.10",
"react-navigation-animated-switch": "^0.1.2",
"react-navigation-hooks": "^1.1.0",
"react-navigation-stack": "2.1.1",
"react-navigation-tabs": "^2.5.3",
"react-navigation-transitions": "^1.0.12",
```

Btw @MaxBolotnyi it looks like your snacks are incomplete 
`React-navigation 4` - example does not have navigation action on button
`React-navigation 5` - has only one screen

**Comment by MaxBolotnyi** [comment]
@Rafal-JAR 
Thanks for pointing that out, I replaced the links so they are now complete.

**Comment by thetminko** [comment]
+1

**Comment by yuriybarnovich** [comment]
Reproducing as well.

**Comment by declanelcocks** [comment]
Happening for me too. I noticed on `react-navigation@4.0.10` that I couldn't touch my `TextInput` until the previous page had completely transitioned away, which then made the `TextInput` behave as expected. On `react-navigation@4.2.2`, I'm able to press the `TextInput` whilst the previous page is still transitioning which results in it focusing and unfocusing instantly.

**Comment by declanelcocks** [comment]
@satya164 sorry, but why was this issue closed?

**Comment by aitorct** [comment]
It's happening to us as well on the latest version of `react-navigation`.

We just disabled the keyboard handling for the whole stack setting the `keyboardHandlingEnabled` prop to `false`. More info here: https://reactnavigation.org/docs/stack-navigator/#keyboardhandlingenabled

So now it works just fine. :)
Hopefully, this gets fixed soon.

**Comment by aitorct** [comment]
It's happening to us as well on the latest version of `react-navigation`.

As a workaround, we disabled the keyboard handling for the whole stack setting the `keyboardHandlingEnabled` prop to `false`. More info here: https://reactnavigation.org/docs/stack-navigator/#keyboardhandlingenabled

So now it works just fine. :)
Hopefully, this gets fixed soon.

**Comment by thekingrenz23** [comment]
> It's happening to us as well on the latest version of `react-navigation`.
> 
> As a workaround, we disabled the keyboard handling for the whole stack setting the `keyboardHandlingEnabled` prop to `false`. More info here: https://reactnavigation.org/docs/stack-navigator/#keyboardhandlingenabled
> 
> So now it works just fine. :)
> Hopefully, this gets fixed soon.

this does not work for me did anyone have a solution for this its sucks

**Comment by phil-kearney** [comment]
I had this problem as well, the home screen `autofocus` and single tap focus worked as expected, anything after navigation would focus then hide immediately afterwards without any other functions (renders etc) firing between. `keyboardHandlingEnabled` prop to `false` didn't help, but changing `createStackNavigator` to `createNativeStackNavigator` did the trick for me.

**Comment by topherPedersen** [comment]
> It's happening to us as well on the latest version of `react-navigation`.
> 
> As a workaround, we disabled the keyboard handling for the whole stack setting the `keyboardHandlingEnabled` prop to `false`. More info here: https://reactnavigation.org/docs/stack-navigator/#keyboardhandlingenabled
> 
> So now it works just fine. :)
> Hopefully, this gets fixed soon.

Thank you so much for posting this aitorct! I spent hours trying to fix this.

**Comment by acro5piano** [comment]
I solved the problem by showing `TextInput` only in focused screen. In other words, re-show `TextInput` fire auto focus.

```jsx
  const [isFocused, setIsFocued] = React.useState(true)

  const setFocus = React.useCallback(() => {
    setIsFocued(true)
  }, [])

  const setBlur = React.useCallback(() => {
    setIsFocued(false)
  }, [])

  const navi = useNavigation()

  React.useEffect(() => {
    navi.addListener('focus', setFocus)
    navi.addListener('blur', setBlur)
    return () => {
      navi.removeListener('focus', setFocus)
      navi.removeListener('blur', setBlur)
    }
  }, [])

  return (
    <View>
        {focused && <TextInput autoFocus />}
    </View>
  )
```

**Comment by joe-a-bizzycar** [comment]
Having this issue on iOS, has anyone arrived at a better solution? Tried out the above method without luck

**Comment by AbdelrahmanTealab** [comment]
> Having this issue on iOS, has anyone arrived at a better solution? Tried out the above method without luck

I'm in the same boat, whenever i try using TextInput inside a component from within TabView the keyboard keeps dismissing itself automatically, until i spam the TextInput the keyboard remains up after a quick taps, can't seem to find any solution.
