### ISSUE TITLE
RESET from nested navigator not works

### ISSUE THREAD

**Issue by AlexeyVlasenko** [react-navigation/react-navigation#6920]
**Current Behavior**

I have arch of navigators: 
```
MainNav: 
     -FirstNav:
        -ScreenA
        -ScreenB
     -SecondNav:
        -ScreenC
        -ScreenD
```
I've tried to use NavigationService with ref on NavigationContainer.
Also, I've tried call RESET and use logic according to an article about nested navigators.

In cases i've mentioned above, result is replace to ScreenC, not ScreenA

**Expected Behavior**

I need to be able to reset from ScreenD to ScreenA.

**How to reproduce**

Snack with repro: https://snack.expo.io/rJRBlwamU

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Both
| @react-navigation/native       | 5.0.6
| react-native                   |  0.61.5

**Comment by WoLewicki** [comment]
The actions are by default dispatched by the deepest nested navigator, so in your case by FirstStack, and it can't reset its state to `ScreenD`. You have to use something like this to achieve what you want: 
```
navigation.dangerouslyGetParent().reset({
          routes: [
          {
            name: 'SecondStack',
            state: {
              routes: [
                {
                  name: 'ScreenD'
                }
              ]
            }
          },
         ],
        }) 
```
It will trigger the reset action on the parent navigator. Does it solve your issue?

**Comment by AlexeyVlasenko** [comment]
@WoLewicki Hi! Thanks for the quick reply!
This is what I search for, the solution works great!

(btw. maybe it's can be added to docs?)
