### ISSUE TITLE
Unable to identify touchable with testID when set as header item on screen in a stack

### ISSUE THREAD

**Issue by andybee** [react-navigation/react-navigation#6921]
**Current Behaviour**

This behaviour is specific to iOS only. When running an Xcode UI Test against an app where a Touchable with a defined `testID` has been placed as a header item on a screen in a stack, the UI Test is unable to locate the element using its `testID` value.

I have explored the known issue with parent elements declaring `accessible="true"` preventing child elements being discoverable, but there doesn't appear to be anyway of manipulating this behaviour when setting header items.

**Expected Behaviour**

When setting a `testID` on the touchable item that is added as a header item on a screen in a stack, I expect to be able to find the element in an Xcode UI Test.

**How to reproduce**

I have created an [example project on GitHub](https://github.com/aiir/react-native-nav-access-test) which demonstrates this issue. Just to reiterate, this project will only work on iOS as I have skipped the setup steps for Android.

You should attempt to execute the `testExample()` function on `NavAccessTestUITest`. This attempts to locate an element with `testID="DrawerMenuButton.Touchable"`, but in my attempts will fail saying the element cannot be found. The debug output after listing possible elements confirms this as it's not listed.

**Your Environment**

| software                       | version       |
| ------------------------------ | ------------- |
| iOS or Android                 | iOS 13.1      |
| @react-navigation/native       | 5.0.6         |
| @react-navigation/stack        | 5.0.6         |
| react-native-gesture-handler   | 1.6.0         |
| react-native-safe-area-context | 0.7.3         |
| react-native-screens           | 2.0.0-beta.10 |
| react-native                   | 0.61.5        |
| expo                           | -             |
| node                           | 12.16.1       |
| npm or yarn                    | npm           |

**Comment by satya164** [comment]
Can you check if it's still an issue with the latest version? (5.0.7)?

**Comment by andybee** [comment]
Thanks for the update @satya164, I can confirm using `5.0.8` of `stacks` fixes the issue.
