### ISSUE TITLE
headerTitle does not accept component anymore (only string)

### ISSUE THREAD

**Issue by franciscailleAstus** [react-navigation/react-navigation#6922]
**Current Behavior**
headerTitle can only take a string. In v4, it used to take also component.

**Expected Behavior**
headerTitle should also take component.

![image](https://user-images.githubusercontent.com/44379473/75050639-59696e80-549a-11ea-9ef4-22fd5d464c6b.png)

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |
| @react-navigation/native       | 5.0.6
| @react-navigation/stack        | 5.0.6
| react-native-gesture-handler   |
| react-native-safe-area-context |
| react-native-screens           |
| react-native                   |
| expo                           | 36
| node                           |
| npm or yarn                    |

**Comment by satya164** [comment]
```js
headerTitle: props => <VehicleListHeaderTitle {...props} />
```

**Comment by franciscailleAstus** [comment]
@satya164 Thanks for the answer, but it doesn't seems to work.

**Comment by satya164** [comment]
Seems you're using `createNativeStackNavigator`. This is only supported in `createStackNavigator`

**Comment by franciscailleAstus** [comment]
Thanks !

**Comment by KhimGurung** [comment]
@satya164  headerTitle: props => <VehicleListHeaderTitle {...props} />
Can you explain what does it mean. I know you are using component in headerTitle but I dont understand the syntax.

**Comment by franciscailleAstus** [comment]
> @satya164 headerTitle: props => <VehicleListHeaderTitle {...props} />
> Can you explain what does it mean. I know you are using component in headerTitle but I dont understand the syntax.

Same thing as: 
(props) =><VehicleListHeaderTitle {...props} />

**Comment by gunn-fd** [comment]
> Seems you're using `createNativeStackNavigator`. This is only supported in `createStackNavigator`

Is there a way to do this in native?

**Comment by CharlyPoppins** [comment]
> > Seems you're using `createNativeStackNavigator`. This is only supported in `createStackNavigator`
> 
> Is there a way to do this in native?
According to the doc no : https://reactnavigation.org/docs/native-stack-navigator/

But it works fine with this code :
````
import { createStackNavigator } from '@react-navigation/stack'
const Stack = createStackNavigator()
````
