### ISSUE TITLE
Bottom Bar keyboardHidesTabBar: true doesn't work well

### ISSUE THREAD

**Issue by alexbchr** [react-navigation/react-navigation#6928]
**Current Behavior**
When using a Bottom Bar and having a `TextInput` in one of the screen, when the keyboard appears (when focusing the text field), there is 3 issues when `keyboardHidesTabBar: true` is used.

1. The Bottom bar is hidden with an animation, but this animation is visible while the keyboard is showing up, as the Bottom Bar follows the top of the keyboard.
2. When the Bottom Bar is hidden (and keyboard visible), the current tab height is increased as much as the Bottom Bar height.
3. The animation hiding the Bottom Bar ignores changes made to the style of Bottom Bar (which could affect its height) when animating. It seems like the Bottom Bar animation animates the Bottom Bar using a hardcoded translation value.

**When keyboard is hidden**
![device-2020-02-21-153126](https://user-images.githubusercontent.com/3542313/75070057-787af700-54c0-11ea-9fb5-c331daf98e86.png)

**When keyboard is visible**
![device-2020-02-21-153136](https://user-images.githubusercontent.com/3542313/75070055-787af700-54c0-11ea-828b-9215f848a9bd.png)

We can see that the screen's content at the bottom (blue block) is lower when the keyboard is visible (issue 2). We can also see in second screenshot that part of the Bottom Bar is still visible because I made it a bit higher (issue 3). 

**Expected Behavior**
Is it necessary to animate then bottom bar when it is hidden? Shouldn't it just remain in place while the keyboard? The keyboard will go on top of it anyway and it would prevent too many things from moving on the screen when the keyboard  is shown. This would even fix all 3 issues without too much trouble I think.

**How to reproduce**
Here is the Snack to the issue: https://snack.expo.io/@alexbchr/react-navigation-bug

Simply click the red `TextInput` on the first screen and see the issues.

**Your Environment**

| software                      | version |
| ----------------------------- | ------- |
| iOS or Android                | 10
| @react-navigation/native      | 5.0.7
| @react-navigation/bottom-tabs | 5.0.7
| react-native-screens          |  2.0.0-alpha.12
| expo                          | 36

**Comment by alexbchr** [comment]
Related issue: #6947

**Comment by satya164** [comment]
https://github.com/react-navigation/react-navigation/issues/6700#issuecomment-547084964

**Comment by alexbchr** [comment]
> [#6700 (comment)](https://github.com/react-navigation/react-navigation/issues/6700#issuecomment-547084964)

Then not animating the BottomBar on Android would fix the issue, as I suggested. The keyboard would simply appear on top of the BottomBar, which would be perfect and much better than hiding it after the keyboard is shown. It would also better follow what the behavior described on the [Material Design Website](https://material.io/components/bottom-navigation/#placement)

> Bottom navigation can be temporarily covered by dialogs, bottom sheets, navigation drawers, the on-screen keyboard, or other elements needed to complete a flow.

**Comment by ReallyLiri** [comment]
It also doesn't work well with padding or margin set in `tabBarOptions.style`, sometimes tab bar might be partly shown over the keyboard.

**Comment by SoorajChoudhary** [comment]
Nice! Working fine 

Thanks
