### ISSUE TITLE
this.props.navigation.state.params is undefined

### ISSUE THREAD

**Issue by noellaby** [react-navigation/react-navigation#6929]
Hello
My code worked without problem with react navigation V3, but following an update to version 5.
I had a piece of code to get the name of the route of the active screen, but following an update to version V5, this.props.navigation.state.params is undefined.

this piece of code is no longer functional react navigation V5

`const activeScreen = this.props.navigation.state.routes [
       this.props.navigation.state.index
     ] .RouteName;
`

Thank you for your answers

**Comment by wildseansy** [comment]
@noellaby - I had the same issue upgrading.  Params now seem to be stored on the `route` object in v5 also passed in props.

```typescript
    const { navigation, route } = props;
    const params = route.params;
```

For reference a lot of stuff won't work on v5 if you upgrade from v3. You'll need to rewrite most of your navigation. See the [upgrade guide](https://reactnavigation.org/docs/en/upgrading-from-4.x.html) for reference

**Comment by osdnk** [comment]
I agree with @wildseansy 
Thanks!

**Comment by adarshkhatri** [comment]
> @noellaby - I had the same issue upgrading. Params now seem to be stored on the `route` object in v5 also passed in props.
> 
> ```ts
>     const { navigation, route } = props;
>     const params = route.params;
> ```
> 
> For reference a lot of stuff won't work on v5 if you upgrade from v3. You'll need to rewrite most of your navigation. See the [upgrade guide](https://reactnavigation.org/docs/en/upgrading-from-4.x.html) for reference

Thank you

**Comment by raajnadar** [comment]
@adarshkhatri you can use the emoji button for +1

**Comment by noumanahmadstack** [comment]
function AddNotes({ navigation }){
    const[notetitle,setnotetitle] = useState('')
    const[noteDescription,setnoteDescription] = useState('')

    function onSaveNote(){
        navigation.state.params.AddNotes({notetitle, noteDescription})
        navigation.goBack()
    }


 <FAB
            style={styles.fab}
             small 
             icon='plus'
             label='Add a new Note'
             onPress={()=>navigation.navigate('AddNotes',{AddNotes})}
            />
