### ISSUE TITLE
Custom navigator dispatch undefined

### ISSUE THREAD

**Issue by mnatanbrito** [react-navigation/react-navigation#6930]
**Current Behavior**

In my react-native application, I'm trying to implement an [Error Boundary](https://reactjs.org/docs/error-boundaries.html) component which has a button to trigger navigation back to the app home screen. So I extended a navigator following [Custom navigators](https://reactnavigation.org/docs/en/4.x/custom-navigators.html):

**AppNavigator**
```
import React from 'react';
import {
  createSwitchNavigator,
  createAppContainer,
  SwitchActions,
} from 'react-navigation';

import AuthLoadingScreen from './screens/AuthLoadingScreen';
import AppStack from './AppStack';
import HelpStack from './HelpStack';
import ErrorBoundary from './ErrorBoundary';

const SwitchNavigator = createSwitchNavigator({
  AuthLoading: AuthLoadingScreen,
  App: AppStack,
  Help: HelpStack,
});

class AppContainer extends React.Component {
  static router = {
    ...SwitchNavigator.router,
  };

  render() {
    const { navigation } = this.props;

    return (
      <ErrorBoundary
        onNavigate={to => {
          console.log(
            `navigation property = ${JSON.stringify(navigation.navigate)}`,
          );

          navigation.dispatch(
            SwitchActions.jumpTo({
              routeName: 'AuthLoading',
            }),
          );
        }}>
        <SwitchNavigator navigation={navigation} />
      </ErrorBoundary>
    );
  }
}

const AppNavigator = createAppContainer(AppContainer);

export default AppNavigator;
```

**ErrorBoundary**
```
import React, { Component } from 'react';
import { View, Text, Button, SafeAreaView } from 'react-native';

const logCrash = (errorName, attributes) => {
  console.error(errorName, JSON.stringify(attributes));
};

class ErrorBoundary extends Component {
  constructor(props) {
    super(props);
    this.state = { hasError: false };
  }

  static getDerivedStateFromError(error) {
    // update state so the next render will show the fallback UI.
    return { hasError: true };
  }

  componentDidCatch(error, errorInfo) {
    // you can also log the error to an error reporting service
    logCrash('jsError', { error, errorInfo });
  }

  render() {
    const { onNavigate } = this.props;

    if (this.state.hasError) {
      // You can render any custom fallback UI
      return (
        <SafeAreaView
          style={{
            flex: 1,
            flexDirection: 'column',
            justifyContent: 'center',
            alignItems: 'stretch',
          }}>
          <Button
            title="Back to main"
            onPress={() => {
              if (onNavigate) {
                onNavigate('App');
              }
            }}
          />
        </SafeAreaView>
      );
    }

    return this.props.children;
  }
}

export default ErrorBoundary;

```

According to [Navigator-navigation-prop](https://reactnavigation.org/docs/en/4.x/custom-navigators.html#navigator-navigation-prop), there should be _dispatch_ function on the _navigation_ prop. However, I'm getting undefined.

**Expected Behavior**

_dispatch_ function is defined on the _navigation_ property. 

**How to reproduce**

I set up a project to reproduce the bug at https://github.com/mnatanbrito/react-navigation-error-boundary.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | iOS 13.3
| react-navigation               | ^4.1.1
| react-navigation-stack         | ^2.1.1
| react-navigation-tabs          | 
| react-navigation-drawer        | 
| react-native-reanimated        | 
| react-native-gesture-handler   | ^1.6.0
| react-native-safe-area-context | ^0.7.3
| react-native-screens           | ^2.0.0-beta.10
| react-native                   | 0.61.5
| expo                           |
| node                           | v13.7.0
| npm or yarn                    | 6.13.6

**Comment by satya164** [comment]
I ran your repro and there's `dispatch` on `navigation`
<img width="1099" alt="Screen Shot 2020-03-20 at 13 03 53" src="https://user-images.githubusercontent.com/1174278/77162034-55d20300-6aab-11ea-9bf5-e13e5b78e4bf.png">
