### ISSUE TITLE
Type error when going to nested navigator

### ISSUE THREAD

**Issue by Aryk** [react-navigation/react-navigation#6931]
In React-Navigation v5, the following works fine for type checking:

```js
navigation.navigate('RouteName', {paramName: 'value'})
```

but when using the forms:

```js
navigation.navigate('Root', { screen: 'Settings' });
navigation.navigate('Root', {
  screen: 'Settings',
  params: {
    screen: 'Sound',
    params: {
      screen: 'Media',
    },
  },
});
```

The TS checking does not work. It is expecting screen to be a param when really I'm going to a screen in the nested navigator.

**Expected Behavior**

- TS should take the screen param and check that the params match against those in the sub navigator.
 

| software                       | version |
| ------------------------------ | ------- |
| react-navigation | 5.0.6
| react | 16.9.0
| node | 13.5

**Comment by Aryk** [comment]
The best I can come up with:

```ts
interface ISubNavigator<T extends ParamListBase, K extends keyof T> {
  screen: K;
  params?: T[K];
}
```

and then:

```ts
type NavigatorBParamList = {
  Mar: { userId: string };
  Lard: undefined;
};
type NavigatorAParamList = {
  Foo: undefined;
  Bar: ISubNavigator<NavigatorBParamList, "Mar"> | ISubNavigator<NavigatorBParamList, "Lard">;
  Car: { activityId: string };
};
```

**Comment by frankyjuang** [comment]
@Aryk maybe this is better? Then we don't have to manually iterate all.

```typescript
type SubNavigator<T extends ParamListBase> = {
  [K in keyof T]: { screen: K; params?: T[K] };
}[keyof T];
```

**Comment by hainguyentien** [comment]
@frankyjuang Do you think about when you get params on the screen you passed, it'll be like: 
```ts
this.props.params.params?.userId
```
Any idea to make it shorter?

**Comment by Aryk** [comment]
@frankyjuang thanks it works perfectly...they really should add this into the type definitions in the library!

**Comment by mi5ha** [comment]
@Aryk Did you report somewhere so this can be added into lreact-navigation? It's really important.

**Comment by Aryk** [comment]
No i did no, but not sure where to report

**Comment by rclai** [comment]
Why did this get closed?

**Comment by karrettgelley** [comment]
This is a big issue for me and for anyone using react navigation and typescript in a prod environment. I have been unable to strongly type the navigation prop for screens in a nested navigator. Please fix this asap

**Comment by JesperLekland** [comment]
> This is a big issue for me and for anyone using react navigation and typescript in a prod environment. I have been unable to strongly type the navigation prop for screens in a nested navigator. Please fix this asap


Using the solution by @frankyjuang works perfectly for us and we have a very big and complex app. 

```ts
type SubNavigator<T extends ParamListBase> = {
  [K in keyof T]: { screen: K; params?: T[K] };
}[keyof T];
```

Also remember that this is open source (i.e people volunteering their time and work) and moderate your tone accordingly.

**Comment by thabemmz** [comment]
I ran into an issue where I'm able to omit `params` while they are required for a specific route. This means my routes are defined as follows:

```
type SubNavigator<T extends ParamListBase> = {
  [K in keyof T]: { screen: K; params?: T[K] }
}[keyof T]

export type TStackNavigatorParamList = {
  [ROUTE_NAMES.PEOPLE_INDEX]: undefined
  [ROUTE_NAMES.PEOPLE_DETAIL]: {
    personId: string
  }
}

export type TTabNavigatorParamList = {
  [ROUTE_NAMES.HOME]: undefined
  [ROUTE_NAMES.PEOPLE]: SubNavigator<TStackNavigatorParamList>
}
```

With the current `SubNavigator`, I'm able to call navigate as follows from code without typing issues.

```
navigation.navigate(ROUTE_NAMES.PEOPLE, { screen: ROUTE_NAMES.PEOPLE_DETAIL }
```

You'd like Typescript to give you an error in this case, since you need the `personId` when calling the `PEOPLE_DETAIL` route in the example.

Hence I optimized the `SubNavigator` generic as follows, which implements the proper Typescript behaviour (error when params are missing while they were defined).

```
type SubNavigator<T extends ParamListBase> = {
  [K in keyof T]: T[K] extends undefined
    ? { screen: K }
    : { screen: K; params: T[K] }
}[keyof T]
```

**Comment by jeanregisser** [comment]
Building up on @thabemmz solution,
here's more robust version that handles the case where the params are `X | undefined`.

```tsx
type NestedNavigatorParams<ParamList> = {
  [K in keyof ParamList]: undefined extends ParamList[K]
    ? { screen: K; params?: ParamList[K] }
    : { screen: K; params: ParamList[K] }
}[keyof ParamList]
```

**Comment by Jonathan0wh** [comment]
any chance for a PR about this change to the param typing?

**Comment by zloi-patrick** [comment]
`@react-navigation` please, fix this bug.
Where is no sense to use `TypeScript` with `@react-navigation` package if it doesn't fully supported :(

**Comment by jonasgroendahl** [comment]
also experiencing this

**Comment by andkom** [comment]
me also

**Comment by satya164** [comment]
https://reactnavigation.org/docs/typescript/#type-checking-screens-and-params-in-nested-navigator

**Comment by omniteq** [comment]
Either there is a bug in the docs or I'am doing something wrong. It looks like `NavigatorScreenParams` is located in `@react-native/core`, not `@react-native/native`. I can't import that type from `/native`.

**Comment by semcelik** [comment]
To use `NavigatorScreenParams` type, you need to update your  **@react-navigation/core** package at least **5.14.0** ([here](https://github.com/react-navigation/react-navigation/blob/main/packages/core/CHANGELOG.md#5140-2020-11-04)). 

@omniteq all of the **@react-native/core** modules are imported and exported in **@react-native/native**.  This means, you can import from both ([here](https://github.com/react-navigation/react-navigation/blob/main/packages/native/src/index.tsx))

**Comment by t-ricci-enhancers** [comment]
@satya164 the typings of the other navigations should be updated as well.

for example:
```typescript
export type StackScreenProps<
  ParamList extends ParamListBase,
  RouteName extends keyof ParamList = string
> = {
  navigation: StackNavigationProp<ParamList, RouteName>;
  route: RouteProp<ParamList, RouteName>;
};
```

using StackScreenProps still gives me a type error when navigating to a nested screen (screen: "routename", params: myParams)

Object literal may only specify known properties, and 'screen' does not exist in type

**Comment by adbl** [comment]
I'm confused, how can `NavigatorScreenParams` be combined with `RouteProp` / `StackNavigationProp`?

With navigators nested in multiple levels, I need a `Child` route (which is also a navigator) to get its route/navigation params from the `Parent` (e.g. `RouteProp<ParentParamList, 'Child'>` and `StackNavigationProp<ParentParamList, 'Child'>`). I also need `Child` to expose that its child routes (grandchildren of `Parent`) can be navigated to directly from within the `Parent` navigator (e.g. `navigation.navigate('Child', {screen: 'GrandChild'})`).

**Comment by jonasgroendahl** [comment]
> I'm confused, how can `NavigatorScreenParams` be combined with `RouteProp` / `StackNavigationProp`?
> 
> 
> 
> With navigators nested in multiple levels, I need a `Child` route (which is also a navigator) to get its route/navigation params from the `Parent` (e.g. `RouteProp<ParentParamList, 'Child'>` and `StackNavigationProp<ParentParamList, 'Child'>`). I also need `Child` to expose that its child routes (grandchildren of `Parent`) can be navigated to directly from within the `Parent` navigator (e.g. `navigation.navigate('Child', {screen: 'GrandChild'})`).

This might be be helpful to you:


https://github.com/jonasgroendahl/react-native-starter

Shows some examples of types needed for nesting and usage of the Navigator prop

**Comment by adbl** [comment]
To clarify, my problem is that in `ParentParamList` I need to specify something like:
```
// to be consumed by `Child` for `route` / `navigation` props
export type ParentParamList = {
  Child: ChildRouteParams 
}
```

But also:
```
// to support `navigation.navigate('Child', {screen: ...})` within `Parent`
type ParentParamList = {
  Child: NavigatorScreenParams<ChildParamList>
}
```

**Comment by adbl** [comment]
> 
> This might be be helpful to you:
> 
> https://github.com/jonasgroendahl/react-native-starter
> 
> Shows some examples of types needed for nesting and usage of the Navigator prop

Thanks but I couldn't find any examples where route params are consumed like in the scenario I described.

**Comment by adbl** [comment]
Ok this seems to work:

`parent`:
```
import type {ChildStackParamsList} from './child'

export type ParentStackParamsList = {
  Child: {foo: string}
  Sibling: {bar: string}
}

type ParentStackScreenParams = {
  Child: NavigatorScreenParams<ChildStackParamsList>
}

type ParentStackParams = ParentStackParamsList | ParentStackScreenParams

const ParentStack = createStackNavigator<ParentStackParams>()

type Props = {
  navigation: StackNavigationProp<ParentStackParams>
}

export const Parent: React.VFC<Props> = ({ navigation }) => {
  // type checks, as well as the `<MotherStack.Navigator>` / `<MotherStack.Screen>` with `initialRouteName` / `initialParams`
  navigation.navigate('Child', {params: {foo: "1"}})
  navigation.navigate('Child', {screen: 'GrandChild'})

  /// ...
}
```

`child`:
```
import type {ParentStackParamsList} from './parent'

export type ChildStackParamsList = {
  GrandChild: {foo: string}
}

type ChildNavigationProp = CompositeNavigationProp<
  StackNavigationProp<ChildStackParamsList>,
  StackNavigationProp<ParentStackParamsList, 'Child'>
>

type Props = {
  navigation: ChildNavigationProps
  route: RouteProp<RootStackParamsList, 'Child'>
}

export const Child: React.VFC<Props> = ({navigation, route}) => {
  //  => string
  route.params.foo

  // type checks
  navigation.navigate('Sibling', {bar: '2'})
}
```

**Comment by raulcontrerasrubio** [comment]
> The best I can come up with:
> 
> ```ts
> interface ISubNavigator<T extends ParamListBase, K extends keyof T> {
>   screen: K;
>   params?: T[K];
> }
> ```
> 
> and then:
> 
> ```ts
> type NavigatorBParamList = {
>   Mar: { userId: string };
>   Lard: undefined;
> };
> type NavigatorAParamList = {
>   Foo: undefined;
>   Bar: ISubNavigator<NavigatorBParamList, "Mar"> | ISubNavigator<NavigatorBParamList, "Lard">;
>   Car: { activityId: string };
> };
> ```
> 
> But then you need to iterate through and write out manually A | B | C | D etc...

To avoid the repetition this works for me:

 ```ts
 type NavigatorBParamList = {
   Mar: { userId: string };
   Lard: undefined;
 };
 type NavigatorAParamList = {
   Foo: undefined;
   Bar: ISubNavigator<NavigatorBParamList, keyof NavigatorBParamList>;
   Car: { activityId: string };
 };
 ```

**Comment by ChamaraWP** [comment]
In a Scenario like  below type suggestion still does not working 
```
export type RootStackParamList = {
  Root: NavigatorScreenParams<UsersParamList>;
};

type UsersParamList = {
  Home: NavigatorScreenParams<HomeStackParamList>;
  Profile: NavigatorScreenParams<ProfileStackParamList>;
};

type HomeStackParamList = {
  Home: undefined;
  Subjects: { id: string };
};

type ProfileStackParamList = {
  Profile: { id: string };
  Marks: undefined;
};
```
let's say we want to navigate to the subject screen by doing this

```
navigation.navigate('Root', {
  screen: ' // it suppose to display the Home and Profile Stacks ',
  params: {
    screen: 'Subjects',
    params: {
      screen: 'GHM2345',
    },
  },
});
```

but it's not showing even if added this to the global type as mentioned in the official docs
```
declare global {
  // eslint-disable-next-line @typescript-eslint/no-namespace
  namespace ReactNavigation {
    interface RootParamList extends RootStackParamList {}
  }
}
```
