### ISSUE TITLE
unmountOnBlur does not close drawer when navigating from a nested stack navigator

### ISSUE THREAD

**Issue by dhruvdewangupta** [react-navigation/react-navigation#6933]
**Current Behavior**

Here I have two items in drawer navigator, both of which contain nested stack navigators. When using `{ unmountOnBlur = true }` in options, the drawer does not close on selecting an item.

**Expected Behavior**

The drawer should close when tapping on an item.

**How to reproduce**

Please find the snack: 
https://snack.expo.io/@gupta_dd/3fade7

1. Open Tab2 from drawer.
2. Click on button.
3. Open Tab1 from drawer.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Android
| @react-navigation/native       | 5.0.5
| @react-navigation/drawer       | 5.0.5
| react-native-reanimated        | 1.4.0
| react-native-gesture-handler   | 1.5.6
| react-native-safe-area-context | 0.6.0
| react-native-screens           | -
| react-native                   | 0.61.4
| expo                           | 36
| node                           | 12.11.1
| npm or yarn                    | yarn 1.22.0

**Comment by dhruvdewangupta** [comment]
It's working fine today without any changes. Don't know why

**Comment by Thegrep01** [comment]
I goy the same issue
