### ISSUE TITLE
Stack Navigator Logic Fails

### ISSUE THREAD

**Issue by engineertdog** [react-navigation/react-navigation#6935]
**Current Behavior**

I have a pretty small app (the screens you see are the only ones that'll be available) that I'm trying to use v5 stack navigation on. Users are provided via AD authentication. The settings screen has an input for the socket based backend connection, which is why they're forced to check their settings when the connection cannot be made (and they're connected to the internet). The logic below works under all circumstances *except* for when `canConnect` changes from `false` to `true. When this happens, the user should be transferred to the Login & Settings screens. But, they stay on the single Settings screen. If the function that changes `canConnect` from `false` to `true` is triggered a second time, then the user will be directed appropriately. However, it would be a bad UX to have the user press the form submit button twice to make this happen. When going from `true` to `false`, the user is directed as expected.

I've logged the logic variables below, including determining where the user should be directed. And based on the values of the variables, the user should be shown the `Login` screen when `canConnect` changes from `false` to `true`, but they are not. When on the `Settings` screen and I log the `routeNames`, only `Settings` is shown on the first form submit while `Login` and `Settings` are shown on the second click (which then directs user with `navigation.goBack()`).

Code:
```js
<NavigationContainer>
        <Stack.Navigator
          screenOptions={{
            headerShown: false
          }}
        >
          { !canConnect
            ? <Stack.Screen name="Settings" component={ Settings } />
            : isAuthorized && user
              ? <>
                  <Stack.Screen name="BarcodeScan" component={ BarcodeScan } />
                  <Stack.Screen name="DataEntry" component={ DataEntry } />
                  <Stack.Screen name="Settings" component={ Settings } />
                </>
              : <>
                  <Stack.Screen name="Login" component={ Login } />
                  <Stack.Screen name="Settings" component={ Settings } />
                </>
          }
        </Stack.Navigator>
</NavigationContainer>
```

**Expected Behavior**
The user should be redirected from `Settings` to `Login` when `canConnect` changes from `false` to `true`.

**How to reproduce**
Use the code above and set `canConnect` to false, `isAuthorized` to false, and `user` to null or false, and try to change `canConnect` to true. Should be redirected from `Settings` to `Login`, but you stay on settings. At this point, `navigation.navigate("Login")` would not work because `canConnect` is update to true after the navigation attempt.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | iOS
| @react-navigation/native       | 5.05
| @react-navigation/stack        | 5.05
| react-native-gesture-handler   | 1.5.0
| react-native-safe-area-context | 0.7.3
| react-native-screens           | 2.0.0-alpha.12
| react-native                   | https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz
| expo                           | 36.0.0
| node                           | 12.11.0
| npm or yarn                    | npm

**Comment by satya164** [comment]
You have the `Settings` screen defined regardless of value of `canConnect`. It'll only be removed if you actually remove it from the configuration. This is expected behaviour. If you expect it to be removed, give it a different name when `canConnect` is `false`.
