### ISSUE TITLE
Increase transition duration and add bezier to cardStyleInterpolator

### ISSUE THREAD

**Issue by shrikantr-iprogrammer** [react-navigation/react-navigation#6936]
**Current Behavior**

- I'm using `cardStyleInterpolator` to make my pages look like cards placed side by side (edges glued to each other) mean no overlapping no fading while navigating. Code below

`
cardStyleInterpolator: ({ current, next, layouts }) => {
    return {
      cardStyle: {
        transform: [
          {
            translateX: current.progress.interpolate({
              inputRange: [0, 1],
              outputRange: [layouts.screen.width, 0],
            }),
          },
          {
            translateX: next
              ? next.progress.interpolate({
                  inputRange: [0, 1],
                  outputRange: [0, -layouts.screen.width],
                })
              : 1,
          },
        ],
      },
    };
  },
`

**Expected Behavior**

- This code works fine but it's really fast. I want it to slow it down a bit (increase transition duration). Also like to add Bezier curv to it.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |
| react-navigation               |
| react-native-reanimated        |
| react-native-gesture-handler   |
| react-native-screens           |
| react-native                   |

**Comment by satya164** [comment]
Use `transitionSpec`: https://reactnavigation.org/docs/en/stack-navigator.html#animation-related-options
