### ISSUE TITLE
In the status bar sinking and floating mode, createnativestacknavigator cannot set the style of the head, which results in the sinking and floating status bar blocking the back and cannot set paddingtop

### ISSUE THREAD

**Issue by livelyPeng** [react-navigation/react-navigation#6937]
In the status bar sinking and floating mode, createnativestacknavigator cannot set the style of the head, which results in the sinking and floating status bar blocking the back and cannot set paddingtop

**Comment by satya164** [comment]
Please open an issue in https://github.com/kmagiera/react-native-screens
