### ISSUE TITLE
Prevent to running common events in React Navigation stack screens

### ISSUE THREAD

**Issue by bashirpour** [react-navigation/react-navigation#6938]
```ecmascript
<Stack.Navigator>
    <Stack.Screen name="Home" component={Screens.Home} />
    <Stack.Screen name="Blog" component={Screens.Blog} />
</Stack.Navigator>
```

When I Navigate to `Blog stack` some of the events(such as `BackHandler` ,`open keyboard when focus on Textinput` ,...) in this screen affect the `Home screen`.

How can a new Screen work as a stand-alone Screen in Stack Navigation?

**Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Android |
| @react-navigation/native       |  ^5.0.5  |
| @react-navigation/stack        | ^5.0.0 |
| react-native-gesture-handler   | ^1.5.6 |
| react-native-safe-area-context | ^0.7.0 |
| react-native-screens           | ^2.0.0-beta.2 |
| react-native                   | 0.61.4 |
| expo                           | |
| node                           | |
| npm or yarn                    | |

**Comment by delavago** [comment]
I have this very issue. more over with keyboard. 

first screen (keyboard works) -> navigate to second screen (textinput un focus immediatly)
