### ISSUE TITLE
how to hide bottomNavigation in a specific nested stack screen?(v5)

### ISSUE THREAD

**Issue by happyChappy13g** [react-navigation/react-navigation#6940]
I have nested stack screens in my tab navigator like so:

```
const Tab = createBottomTabNavigator();
const Stack = createStackNavigator();    

const HomeStackNavigator = () => (
  <Stack.Navigator>
    <Stack.Screen name="FirstNestedScreen" component={FirstNestedScreen} />
    <Stack.Screen name="SecondNestedScreen" component={SecondNestedScreen} />
    <Stack.Screen name="ThirdNestedScreen" component={ThirdNestedScreen} /> // on this screen
    //I don't want the user to see the bottom navigation tab
  </Stack.Navigator>
);

export default () => (
   <NavigationContainer>
     <Tab.Navigator>
       <Tab.Screen
         name="Home"
         options={({route}) => {
           let tabBarVisible = true;           
           if(route.name === "ThirdNestedScreen"){
             tabBarVisible = false;
           }
           return {tabBarVisible};
         }}
       >
         {HomeStackNavigator}
       </Tab.Screen>
     </Tab.Navigator>
   </NavigationContainer>
);
```
My Intention is obvious, I want to hide the bottom tab navigator when the user is in the third nested stack screen. but the problem is that I don't have access to `tabBarVisible` option on a `Stack.Screen` as mentioned in this doc: [link](https://reactnavigation.org/docs/en/screen-options-resolution.html#a-tab-navigator-contains-a-stack-and-you-want-to-hide-the-tab-bar-on-specific-screens)

so what I did was trying to set the visibility dynamically on the `Tab.Screen` by route.name but it doesn't show the name of the nested route, instead it always shows Home(the name of the Tab navigator). so I'm stuck. any workaround would be appreciated, thanks.

note that this solution doesn't apply to v5: [link](https://reactnavigation.org/docs/en/navigation-options-resolution.html#a-tab-navigator-contains-a-stack-and-you-want-to-hide-the-tab-bar-on-specific-screens)

**Comment by rmkpatchaa** [comment]
In a stack screen you can have access to the parent navigator (which is the tab navigator in this case) and set the option.
Here is a code snippet that can help : 

```
import React, {useCallback} from 'react';
import {useFocusEffect} from '@react-navigation/native';
...
export default function MyScreen({navigation: {dangerouslyGetParent}}) {
...
  useFocusEffect(
    useCallback(() => {
      // Do something when the screen is focused
      const parent = dangerouslyGetParent();
      if (parent) {
        parent.setOptions({
          tabBarVisible: false,
        });
      }

      return () => {
        // Do something when the screen is unfocused
        // Useful for cleanup functions
        if (parent) {
          parent.setOptions({
            tabBarVisible: true,
          });
        }
      };
    }, [dangerouslyGetParent]),
  );
...
}
```

**Comment by rmkpatchaa** [comment]
You can also use the solution here : 
https://github.com/react-navigation/react-navigation/issues/6884#issuecomment-589991405

**Comment by satya164** [comment]
You should nest the tab navigator inside the first screen of stack navigator instead

```
- Stack
   - FirstScreen
      - Tab
         - Home
         - Settings
   - SecondScreen
   - ThirdScreen
```

https://reactnavigation.org/docs/en/nesting-navigators.html#parent-navigators-ui-is-rendered-on-top-of-child-navigator
