### ISSUE TITLE
navigation.emit？？？What do you mean?

### ISSUE THREAD

**Issue by livelyPeng** [react-navigation/react-navigation#6941]
**Current Behavior**

- What code are you running and what is happening?
- Include a screenshot or video if it makes sense.

**Expected Behavior**

- What do you expect should be happening?
- Include a screenshot or video if it makes sense.

**How to reproduce**

- You must provide a way to reproduce the problem. If you are having an issue with your machine or build tools, the issue belongs on another repository as that is outside of the scope of React Navigation.
- Either re-create the bug on [Snack](https://snack.expo.io) or link to a GitHub repository with code that reproduces the bug.
- Explain how to run the example app and any steps that we need to take to reproduce the issue from the example app.
- Keep the repro code as simple as possible, with the minimum amount of code required to repro the issue.
- Before reporting an issue, make sure you are on latest version of the package.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |
| @react-navigation/native       |
| react-native                   |
| expo                           |
| node                           |
| npm or yarn                    |

**Comment by Kennytian** [comment]
@livelyPeng 老哥，你要懂得提问的礼貌，你这语句完全是在质问别人。

**Comment by lucianomlima** [comment]
@satya164 You can reopen this issue please?
I'm getting this error after update my react-navigation packages.

<img width="190" alt="iPhone 11 (13 4 1)_g1dk3" src="https://user-images.githubusercontent.com/1580205/82608445-14d09a80-9b91-11ea-99b7-c29a86353750.png">

<img width="202" alt="Android Emulator - Android95554_74fgn" src="https://user-images.githubusercontent.com/1580205/82608816-bf48bd80-9b91-11ea-8b33-2cb306089802.png">

software | version
-- | --
iOS or Android |  both
@react-navigation/native |  v4.3.9
react-native |  0.61.5
expo |  no
node |  v12
npm or yarn | yarn

From `yarn.lock`:
```yaml
react-navigation-drawer@^2.4.0:
  version "2.4.13"
  resolved "https://registry.yarnpkg.com/react-navigation-drawer/-/react-navigation-drawer-2.4.13.tgz#9a5240664c1022a58a598fb326124185a6f8f0f0"
  integrity sha512-C9YI8iks0EoTpfDtE7Ys/QJy42jFfTJZqHNULzIu9doqbc5z6cc4Uutz9nUvAae3hJguUrv61FssC+caR6XuFg==

react-navigation-stack@^2.5.0:
  version "2.5.1"
  resolved "https://registry.yarnpkg.com/react-navigation-stack/-/react-navigation-stack-2.5.1.tgz#4ae3511654fb7f5c1e28305366aa8d3d973dec9e"
  integrity sha512-LNMIIt1B22IohL7Nbyk7Jk4y8lSvFrA6nna1pqx8wwEDlylT9U1NZ719HZibegr3CPJBZKjqpdGCGUd8sE6b8A==
  dependencies:
    color "^3.1.2"
    react-native-iphone-x-helper "^1.2.1"

react-navigation-tabs@^2.8.0:
  version "2.8.13"
  resolved "https://registry.yarnpkg.com/react-navigation-tabs/-/react-navigation-tabs-2.8.13.tgz#a7ec2a6b298e522370f03172bf2778f422ad4d6f"
  integrity sha512-3CpGzHd/mWAv/vOvP/mYxLMKAOVOxu9uYj6i4DZB2KkGphbwrZTGckaxkGj1L9SyxNSBnB4nAz2a1I4Bdk8vTg==
  dependencies:
    hoist-non-react-statics "^3.3.2"
    react-lifecycles-compat "^3.0.4"
    react-native-safe-area-view "^0.14.9"
    react-native-tab-view "^2.11.0"
```

My old versions:
```yaml
react-navigation-drawer@^2.3.3:
  version "2.3.4"
  resolved "https://registry.yarnpkg.com/react-navigation-drawer/-/react-navigation-drawer-2.3.4.tgz#c1faa96f2d810158c81fdf1e4829bd7f8291181d"
  integrity sha512-jPGFVsYB+Q51bMFoeXLO2sYXMQISu2b9fQWZ9QMTvRsA/9pqeBfW7AXM97qW+HdciiQJBdJ6DcttoybWjBSpWQ==

react-navigation-stack@^2.0.16:
  version "2.1.1"
  resolved "https://registry.yarnpkg.com/react-navigation-stack/-/react-navigation-stack-2.1.1.tgz#0e674f9eb1441fdcd67a792ecc9fb0f9349ed22a"
  integrity sha512-ei2JWgAWrsUgyhIR47bnm9Y2gQMQOpnCIy3JMNeGjW82iqdqvq71SaUksb8rZmjt9J3thCyaH2/ClvHJbMMV2w==
  dependencies:
    color "^3.1.2"
    react-native-iphone-x-helper "^1.2.1"

react-navigation-tabs@^2.7.0:
  version "2.7.0"
  resolved "https://registry.yarnpkg.com/react-navigation-tabs/-/react-navigation-tabs-2.7.0.tgz#68505910164a51c44710f835def8fe29360f346a"
  integrity sha512-fQEHjFrIBi+89loLL521HjGS0Z9tl4Y89SSamRkDl8Of6bPS1Ep++an3ctl2j7c3veqBZBrj3H1qa7qjd3apBQ==
  dependencies:
    hoist-non-react-statics "^3.3.0"
    react-lifecycles-compat "^3.0.4"
    react-native-safe-area-view "^0.14.6"
    react-native-tab-view "^2.11.0"

react-navigation@*, react-navigation@^4.1.0:
  version "4.1.1"
  resolved "https://registry.yarnpkg.com/react-navigation/-/react-navigation-4.1.1.tgz#670a1712e945e454fe9cafa424e685c2f1f30832"
  integrity sha512-HEzPOsndrKnxTf0+gsi1N/0GKbwu8KSTOveL7ptJLG7XNXHBXVvp4lbaS3PVPe2IaiXbXCC+y3VJ8dH50wHR4g==
  dependencies:
    "@react-navigation/core" "^3.5.2"
    "@react-navigation/native" "^3.6.5"
```

**Comment by raajnadar** [comment]
try clearing the cache

**Comment by lucianomlima** [comment]
I try it. Also delete node_modules, run yarn start with --reset-cache, try another version combinations. Any works for me.
From react-navigation v4.2.0 shows me this error on startup.

**Comment by raajnadar** [comment]
Try upgrading to react navigation v5

**Comment by JetCyC** [comment]
> I try it. Also delete node_modules, run yarn start with --reset-cache, try another version combinations. Any works for me.
> From react-navigation v4.2.0 shows me this error on startup.

same for me

**Comment by lucianomlima** [comment]
> Try upgrading to react navigation v5

I can't update right now. It's been planned to be in future

**Comment by satya164** [comment]
> You can reopen this issue please

This issue doesn't have any info. I don't think "navigation.emit？？？What do you mean?" is your issue. If you think there's a bug, you need to open a new issue with some info.

Anyway, looks like you have older version of `react-navigation` package. You have mentioned that you use `4.3.9` of `@react-navigation/native` (I assume `react-navigation` coz there's no such version of `@react-navigation/native`), but your `yarn.lock` pasted below says you have `4.1.1`

**Comment by JetCyC** [comment]
> > Try upgrading to react navigation v5
> 
> I can't update right now. It's been planned to be in future

Hello，Have you solved the problem？Could you please share it. Thank you

**Comment by lucianomlima** [comment]
> Hello，Have you solved the problem？Could you please share it. Thank you

I try it in a new clean app and works... but in my project no. I will try step-by-step recreation and later, upgrade.

**Comment by thijs-qv** [comment]
I ran into the same issue after updating from 3.x to 4.x. Deleting node_modules and ~/Library/Developer/Xcode/DerivedData, reinstalling the node_modules and pods and rebuilding the app has solved the problem for me. It looks like a caching thing.
