### ISSUE TITLE
Better typing for `route`

### ISSUE THREAD

**Issue by karszawa** [react-navigation/react-navigation#6943]
**Current Behavior**

When I try to make `tabBarVisible` configurable by route props, TypeScript causes an error like:

```
TypeScript error like `Property 'state' does not exist on type 'RouteProp<Record<string, object>, string>'.ts(2339)`
```

This is because I tried to use `state` for `route`. However, there is no definition of `state` for `route`.

https://github.com/react-navigation/react-navigation/blob/86c39d2e0ec5b864419b3850d1ac0e1a55ec3007/packages/core/src/types.tsx#L285-L295

I checked the value and found there should be other fields other than `params`.

```
Object {
  "route": Object {
    "key": "Home-ejiMzBnYL",
    "name": "Home",
    "params": undefined,
    "state": Object {
      "index": 0,
      "key": "stack-m9Rdg4hu1",
      "routeNames": Array [
        "Home",
        "Camera",
        "ConfirmFood",
        "EditFood",
        "SearchFoodByBarcode",
        "SearchFood",
        "Comment",
      ],
      "routes": Array [
        Object {
          "key": "Home-MKFwBvLDm",
          "name": "Home",
          "params": undefined,
        },
      ],
      "stale": false,
      "type": "stack",
    },
  },
}
```

**Expected Behavior**

More accurate typing for `route`.

**How to reproduce**

This is the code I tried.

```typescript
import { createBottomTabNavigator } from "@react-navigation/bottom-tabs";

const Tab = createBottomTabNavigator();

export const MainTab = () => (
  <Tab.Navigator lazy={false}>
    <Tab.Screen
      name="Home"
      component={HomeStack}
      options={({ route }) => ({
        // TypeScript error like `Property 'state' does not exist on type 'RouteProp<Record<string, object>, string>'.ts(2339)`
        tabBarVisible: route?.state?.routes?.length === 1,
      })}
    />
  </Tab.Navigator>
);
```

**Your Environment**

| software                      | version |
| ----------------------------- | ------- |
| iOS or Android                | iOS and Android |
| @react-navigation/native      | 5.0.7 |
| @react-navigation/bottom-tabs | 5.0.7 |
| react-native-screens          | 2.0.0-beta.10 |
| react-native                  | expo's 36.0.1 |
| expo                          | 36.0.2 |
| node                          | v10.16.3 |
| npm or yarn                   | 6.13.0 |

**Comment by brunon80** [comment]
I have the same issue on the same environment with `Drawer.Navigator`, code:

```tsx
<Drawer.Navigator
    drawerContent={(props: DrawerContentComponentProps): ReactElement => CustomDrawerContent(props)}
      drawerContentOptions={{
            activeTintColor: colors.orange,
            itemStyle: {
                marginLeft: 0,
             },
        }}
        screenOptions={({ route }) => {
            return {
                //Property 'state' does not exist on type 'RouteProp<Record<string, object>, string>'.ts(2339)
                swipeEnabled: route?.state?.index > 0 ? false : true,
            }
        }}
        initialRouteName="Home"
    >
```

**Comment by satya164** [comment]
Accessing `route.state` property isn't safe. It isn't guaranteed to exist and relying on it means that your code may not work as expected. So you shouldn't be accessing it. See https://reactnavigation.org/docs/screen-options-resolution/#setting-parent-screen-options-based-on-child-navigators-state for various approaches to handle such use cases.
