### ISSUE TITLE
Unable to access setOptions in useRoute

### ISSUE THREAD

**Issue by nateblog** [react-navigation/react-navigation#6944]
**Current Behavior**

Unable to access setOptions values in useRoute, I can only see the values I set using setParams. I am passing a function which gives a warning if I use setParams so I need the setOption to be accessible in useRoute.

**Expected Behavior**

Be able to access setOptions in useRoute

**VERSION**

    "@react-navigation/native": "5.0.3",
    "@react-navigation/stack": "5.0.3",

**Comment by osdnk** [comment]
Why do you need this? Can't you use `setParams` and then do mapping by passing a function to `screenOptions`?
