### ISSUE TITLE
BottomTabNavigator keyboardHidesTabBar: true - tabBar is hidden with an animation

### ISSUE THREAD

**Issue by timbicker** [react-navigation/react-navigation#6947]
**Current Behavior**

The BottomTabNavigator moves up with the keyboard and then immediately moves down again.

**Expected Behavior**

The BottomTabNavigator should stay hidden when the keyboard moves up.

**How to reproduce**

[Example on Snack](https://snack.expo.io/@tonks/createbottomtabnavigator---animation-bug)

**Your Environment**

| software                      | version |
| ----------------------------- | ------- |
| iOS or Android                |  9
| @react-navigation/native      |    5.0.4
| @react-navigation/bottom-tabs | 5.0.4
| react-native-screens          | 2.0.0-alpha.12

**Comment by hadnet** [comment]
When keyboardHidesTabBar is set to true this ugly animation occurs on Android only. On iOS is very smooth.

**Comment by satya164** [comment]
https://github.com/react-navigation/react-navigation/issues/6700#issuecomment-547084964
