### ISSUE TITLE
i create a header button and didn't open the drawer for me

### ISSUE THREAD

**Issue by kimitchii** [react-navigation/react-navigation#6949]
when i swipe right my drawer open but i want to open it using a button in the header i did a code but i have this error navigator.openDrawer is not a function.(In 'navigation.openDrawer')','navigation.openDrawer' is undefined)

that's my code:

```
const Navigator = createStackNavigator({
  Home:{screen: Home},
  Profil:{screen: Inscription},
  signup:{screen: signup, navigationOptions: { header: null }},
  mp:{screen: mp},
  ch:{screen: ch},
  mn:{screen: mn},
  drawer:{screen: drawer,
  navigationOptions: ({navigation}) => ({ 
    title:"votre travail",
    headerStyle:{backgroundColor:'#8B0000'},
    headerTitleStyle: {
      fontWeight: 'bold',
      color:'white',         
    },
    headerLeft: () => (
      <TouchableOpacity onPress={() => navigation.openDrawer()} >
        <Icon name={'menu'} size={28} color={'white'} style={{marginRight:10}}/>
      </TouchableOpacity> 
     ),
    }),
  },
});
```

**Comment by Rangoons** [comment]
`    headerLeft: (props) => (
      <TouchableOpacity onPress={() => props.navigation.openDrawer()} >
        <Icon name={'menu'} size={28} color={'white'} style={{marginRight:10}}/>
      </TouchableOpacity> 
     ),`

getting the props in the `headerLeft` function and using that in the `onPress` function should fix it for you

**Comment by kimitchii** [comment]
thank you for reponding but its give me an other error
undefined is not an object(evaluating 'props.navigation.openDrawer')

**Comment by Rangoons** [comment]
post a snippet of the code with the changes you made

**Comment by kimitchii** [comment]
ok her is the code now:


```
const Navigator = createStackNavigator({
  Home:{screen: Home},
  Profil:{screen: Inscription},
  signup:{screen: signup, navigationOptions: { header: null }},
  mp:{screen: mp},
  ch:{screen: ch},
  mn:{screen: mn},
  drawer:{screen: drawer,
  navigationOptions: ({navigation}) => ({ 
    title:"votre travail",
    headerStyle:{backgroundColor:'#8B0000'},
    headerTitleStyle: {
      fontWeight: 'bold',
      color:'white',         
    },
    headerLeft: (props) => (
      <TouchableOpacity onPress={() => props.navigation.openDrawer()} >
        <Icon name={'menu'} size={28} color={'white'} style={{marginRight:10}}/>
      </TouchableOpacity> 
     ),
     
    }),
  },
});


const App = createAppContainer(Navigator);
export default App;
```

**Comment by diaraujo13** [comment]
I'm facing same issue

> ok her is the code now:
> 
> ```
> const Navigator = createStackNavigator({
>   Home:{screen: Home},
>   Profil:{screen: Inscription},
>   signup:{screen: signup, navigationOptions: { header: null }},
>   mp:{screen: mp},
>   ch:{screen: ch},
>   mn:{screen: mn},
>   drawer:{screen: drawer,
>   navigationOptions: ({navigation}) => ({ 
>     title:"votre travail",
>     headerStyle:{backgroundColor:'#8B0000'},
>     headerTitleStyle: {
>       fontWeight: 'bold',
>       color:'white',         
>     },
>     headerLeft: (props) => (
>       <TouchableOpacity onPress={() => props.navigation.openDrawer()} >
>         <Icon name={'menu'} size={28} color={'white'} style={{marginRight:10}}/>
>       </TouchableOpacity> 
>      ),
>      
>     }),
>   },
> });
> 
> 
> const App = createAppContainer(Navigator);
> export default App;
> ```

Did you find a solution? 

` <NavigationContainer ref={containerRef}>
                <Stack.Navigator>
                    <Stack.Screen
                        options={{
                        headerMode: "none",
                        header: null,
                        headerShown: false
                    }}
                        name="Login"
                        component={LoginScreen}/>
                    <Stack.Screen
                        name="Root"
                        headerMode="top"
                        options={{
                        headerStyle: {
                            backgroundColor: '#00a5f0'
                        },
                        headerTintColor: '#ffffff',
                        headerTitleStyle: {
                            fontWeight: 'bold'
                        },
                        headerLeftContainerStyle: {},
                        headerLeft: (props) => <TouchableOpacity
                                onPress={(props) => props.navigation.openDrawer()}
                                style={{
                                flex: 1,
                                width: 49,
                                height: 20,
                                alignItems: 'center',
                                justifyContent: 'center',
                                backgroundColor: 'transparent'
                            }}
                                title="X"
                                color="#fff">
                                <Icon name='ios-menu'/>
                            </TouchableOpacity>
                    }}
                        component={DrawerNavigator}/>
                </Stack.Navigator>
            </NavigationContainer>`

**Comment by RoderickJDunn** [comment]
@diaraujo13 In order to access `navigation` from an option, you can make the entire options prop a function instead of an object. This function is passed various props, one of which is `navigation`. See modifications of your code below. 
```
<NavigationContainer ref={containerRef}>
    <Stack.Navigator>
        <Stack.Screen
            options={{
                headerMode: 'none',
                header: null,
                headerShown: false,
            }}
            name="Login"
            component={LoginScreen}
        />
        <Stack.Screen
            name="Root"
            headerMode="top"
            options={props => {
                return {
                    headerStyle: {
                        backgroundColor: '#00a5f0',
                    },
                    headerTintColor: '#ffffff',
                    headerTitleStyle: {
                        fontWeight: 'bold',
                    },
                    headerLeftContainerStyle: {},
                    headerLeft: (
                        <TouchableOpacity
                            onPress={() =>
                                props.navigation.openDrawer()
                            }
                            style={{
                                flex: 1,
                                width: 49,
                                height: 20,
                                alignItems: 'center',
                                justifyContent: 'center',
                                backgroundColor: 'transparent',
                            }}
                            title="X"
                            color="#fff">
                            <Icon name="ios-menu" />
                        </TouchableOpacity>
                    ),
                };
            }}
            component={DrawerNavigator}
        />
    </Stack.Navigator>
</NavigationContainer>
```
