### ISSUE TITLE
Some props not working from @react-navigation/stack in react-navigation-stack

### ISSUE THREAD

**Issue by jadhavsaurabh** [react-navigation/react-navigation#6950]
Well, I am new to this repo I just needed to know is there any difference between createStackNavigator() imported from `@react-navigation/stack` and one imported from `react-navigation-stack`,
Because Props like `screenOptions` are not working if we use imported `createStackNavigator()` from `react-navigation-stack`

**Comment by satya164** [comment]
https://reactnavigation.org/docs/upgrading-from-4.x/
