### ISSUE TITLE
TypeError: Cannot read property 'ThemeContext' of undefined, when testing with jest and @testing-library/react-native

### ISSUE THREAD

**Issue by elraphty** [react-navigation/react-navigation#6951]
When trying to test my react-native application, i get this error "TypeError: Cannot read property 'ThemeContext' of undefined" caused by react-navigation-stack

<img width="1440" alt="Screen Shot 2020-02-15 at 7 04 03 PM" src="https://user-images.githubusercontent.com/27078045/74593288-1175c200-502a-11ea-86a9-d9ff0fb7bab6.png">
<img width="1440" alt="Screen Shot 2020-02-15 at 7 04 30 PM" src="https://user-images.githubusercontent.com/27078045/74593295-18043980-502a-11ea-855c-ed6e69f7a1d6.png">
<img width="1440" alt="Screen Shot 2020-02-15 at 7 04 41 PM" src="https://user-images.githubusercontent.com/27078045/74593296-189cd000-502a-11ea-8bab-2c97c0bdad78.png">
<img width="1440" alt="Screen Shot 2020-02-15 at 7 04 54 PM" src="https://user-images.githubusercontent.com/27078045/74593297-19cdfd00-502a-11ea-856e-f6dbe297c5d3.png">

**Comment by satya164** [comment]
Closing due to no response.
