### ISSUE TITLE
ModalPresentationIOS jump when closed with tabbar

### ISSUE THREAD

**Issue by MorgadoKnivet** [react-navigation/react-navigation#6952]
Hello people. I am using ModalPresetationIOS in my app. It's working with a bug in android and ios when the modal closed over a tab bar. More or less a "jumping"

Return of modal
`
    return = ()=>{

        if ( this.idioma  == "pt_BR") {
            this.props.SAVE_PT_BR ()
        }

        if ( this.idioma  == "es") {
            this.props.SAVE_ES()
        }

        this.props.navigation.goBack()
    } 
`
Stack of tab bar
`       ConfiguracoesStack:{
            screen:RootConfiguracoes,
            navigationOptions: ({navigation}) => 
            {
              let tabVisible = false
              var route = navigation.state.routes[navigation.state.index]
              
              let routeName = navigation.state.routes[navigation.state.index].routeName

              try {
                if(route.routes[1].routeName == "EscolherIdioma" || route.routes[1].routeName == "TrocarEmail" || route.routes[1].routeName == 'EditarPerfil')
                  tabVisible = false

              } catch (error) {
                tabVisible = true
              }

              if( route.routeName  == "EscolherIdioma" || route.routeName  == "TrocarEmail" || route.routeName  ==  'EditarPerfil' || route.routeName == "TrocarSenha" || route.routeName == "Local")
                tabVisible = false
    
              return{
                tabBarIcon: ({ focused }) => <IconComponent name={"Configuracoes"} focused={focused} />,
                tabBarVisible: tabVisible
              }
            }
        },
    },{ 
        initialRouteName: 'MutiroesStack',
        tabBarOptions: { 
          showLabel: false,
          style: {
            backgroundColor: colors.sunflower_yellow,
          },
        },
    }`

Stack of Page and Modal (EscolherIdioma)

`
const StackConfiguracoes = createStackNavigator(
    { 
      ConfiguracoesHome,
      EditarPerfil,
      TrocarEmail,
      TrocarSenha,
      EscolherIdioma :  {
        screen: EscolherIdioma,
        navigationOptions:{
          ...TransitionPresets.ModalPresentationIOS,
          gestureEnabled: true,
          cardOverlayEnabled: true,
        },
      },
    },
    {
      initialRouteName:"ConfiguracoesHome",
      headerMode: 'none',
      defaultNavigationOptions: {
        ...TransitionPresets.SlideFromRightIOS,
        gestureEnabled: true,
        cardOverlayEnabled: true,

      },
    }
  )

const RootConfiguracoes = createStackNavigator(
    {
      StackConfiguracoes:{
        screen:StackConfiguracoes
      },
    },
    {
    mode: 'modal',
    headerMode: 'none',
    defaultNavigationOptions: {
      ...TransitionPresets.ModalPresentationIOS,
      gestureEnabled: true,
      cardOverlayEnabled: true,

    }},
) 
`

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/34779500/74374290-e0448a00-4dbc-11ea-9bc3-a2efd9cdad36.gif)

**Your Environment**

| software     mac osX                   | version : 10.15.12|
| ------------------------------ | ------- |
| iOS or Android   - both  
iPhone 6 11.4 / iPhone 11 13.2.2
Android 9            
| react-navigation : "^4.0.10"       
| react-navigation-stack: "^2.1.1" 
 "react-navigation-tabs": "^2.7.0",      
 "react-native-gesture-handler":  "^1.4.1"
 "react-native-safe-area-context": "^0.6.4",
 "react-native-screens": "^1.0.0-alpha.23",
 "react-native": "0.60.5",
  npm: '6.13.7',
  node: '10.16.0',

**Comment by satya164** [comment]
It jumps because you're changing the height of the screen during the transition by hiding the tab bar. You should nest the tab navigator inside a stack navigator instead to avoid this.

**Comment by Steffi3rd** [comment]
> It jumps because you're changing the height of the screen during the transition by hiding the tab bar. You should nest the tab navigator inside a stack navigator instead to avoid this.

Hello @satya164,
I don't understand your solution. I don't see in his code where he's changing the height of screen. 

I have actually the same bug. The card below "is flickering/jumping". I don't understand why. 
I followed the tutorial.

```
import { TransitionPresets } from 'react-navigation-stack';

// ...

const Stack = createStackNavigator(
  {
    Home,
    Profile,
    Settings,
  },
  {
    mode: 'modal',
    headerMode: 'none',
    defaultNavigationOptions: {
      gestureEnabled: true,
      cardOverlayEnabled: true,
      ...TransitionPresets.ModalPresentationIOS,
    },
  }
);
```

My Screen Settings is open as Modal (without tabs). 
My HomeScreen is the initial screen and became "card below" and this screen has tabs.

Do you know how to fix the bug on my case?

**Comment by MorgadoKnivet** [comment]
@satya164 you are my hero <3
