### ISSUE TITLE
bottom border below header

### ISSUE THREAD

**Issue by michaelknoch** [react-navigation/react-navigation#6953]
**Current Behavior**
After updating from version `1.9.4` to one of the lastest versions i see a 1px border bottom below all my stack headers. This is how my `headerStyle` looks, any advices or workarounds for this behaviour?

```js
headerStyle: {
   backgroundColor: "blue"
   borderBottomWidth: 0,
   elevation: 0, // hide shadow on android
},
```
Even setting the border color explicitly has no effect

<img width="487" alt="Screenshot 2020-02-12 at 13 34 34" src="https://user-images.githubusercontent.com/5617793/74335487-a82d4f00-4d9c-11ea-9ffd-acbeae769bcf.png">

**How to reproduce**
I am assuming that my usage of the library might be incorrect. If the random border is a bug, i am happy to create a demo for reproduction

**Your Environment**
seen with react-navigation-stack 2.0.1, 2.0.16 and 2.1.0

**Comment by Remigar2012** [comment]
@satya164 
             
<img width="379" alt="Снимок экрана 2020-03-12 в 16 24 06" src="https://user-images.githubusercontent.com/38878586/76525987-e68e5a80-647d-11ea-8823-adaeee4dcf6d.png">

**Comment by UADACID** [comment]
> @satya164
> 
> <img alt="Снимок экрана 2020-03-12 в 16 24 06" width="379" src="https://user-images.githubusercontent.com/38878586/76525987-e68e5a80-647d-11ea-8823-adaeee4dcf6d.png">

i try this solution but not work, shadow and border bottom on my header stil show up
