### ISSUE TITLE
How to use ModalPresentationIOS with nested stacks

### ISSUE THREAD

**Issue by aymanosman** [react-navigation/react-navigation#6955]
# Problem
I am trying to use the newer `ModalPresentationIOS` transition with an app that uses nested stacks. I've produced a minimal example [here](https://gist.github.com/aymanosman/404b446bc3650381b48de2cf3728b272).

The bad effect that I'm seeing is shown in the gif below. The overlay effect is happening twice, when I would like it to happen once.

![out](https://user-images.githubusercontent.com/3605049/74146948-1d145380-4bfa-11ea-9a96-574c495700ec.gif)

**Comment by seunghyun-woo** [comment]
This is because wrong navigator structure. 
Change your navigator structure will help.
