### ISSUE TITLE
CardStyleInterpolators.forScaleFromCenterAndroid  background white flash when app in dark theme

### ISSUE THREAD

**Issue by gaodeng** [react-navigation/react-navigation#6957]
**Current Behavior**
https://youtu.be/qeUpiPesgj4

**Expected Behavior**

no white background flash

**How to reproduce**
1. turn dark mode on
2. cardStyleInterpolator: CardStyleInterpolators.forScaleFromCenterAndroid,

**Your Environment**
latest

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | ANDROID
| react-navigation               |
| react-navigation-stack         |
| react-native-gesture-handler   |
| react-native-safe-area-context |
| react-native-screens           |
| react-native                   |
| expo                           |
| node                           |
| npm or yarn                    |

**Comment by satya164** [comment]
Closing due to no response.

**Comment by gcottrell1** [comment]
I have also experienced this issue, it happens on android when "dark theme" in the OS is switched on while the app is open. On all screen animations there is a flicker of a white background as seen in @gaodeng's linked video. The same happens in reverse if the app is opened when in dark theme and then switched to light, a dark background will flicker during the screen transitions. Did you find a fix @gaodeng
