### ISSUE TITLE
Strange behaviour when more than 2 screens are pushed and RNCamera is used

### ISSUE THREAD

**Issue by cristianoccazinsp** [react-navigation/react-navigation#6958]
**Current Behavior**
When using RNCamera in one screen, and then pushing 2 additional screens, RNCamera receives a surface destroy event (and results in the camera stopping). This seems to be a new change from stack navigation 2.x since it didn't seem to happen before. This updated behaviour is causing issues with the camera component (it is stopped and never resumed). Still trying to figure out what's going on, but perhaps someone could shed some light.

**Expected Behavior**
Screens in the stack should not receive any surface destroy event.

**How to reproduce**
Mount a RNCamera component, then push two screens, then pop them. The moment the second screen is pushed, RNCamera receives a surface destroy event and stops (even if told not to). This does NOT happen if only 1 screen is pushed. And this also never happened before until 2.x

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Android any version
| react-navigation               | 4.1.1
| react-navigation-stack         | 2.1.1
| react-native-gesture-handler   | 1.5.6
| react-native-safe-area-context | 0.7.2
| react-native-screens           | 2.0.0-beta.2
| react-native                   | 0.61.5
| expo                           | - 
| node                           | - 
| npm or yarn                    | -

**Comment by satya164** [comment]
Closing since `removeClippedSubviews` isn't used anymore.

**Comment by cristianoccazinsp** [comment]
Interesting change. So this basically brings back the previous behaviour.  Either way, the issue with screens and react-native-camera was resolved so it wasn't that bad.  

Do you know if there is any noticeable performance impact due to this?

**Comment by satya164** [comment]
I haven't measured, it depends on what kind of screens you have.
