### ISSUE TITLE
react navigation stack + react native screens + react native webview will crash (null pointer dereference) when the pop stack

### ISSUE THREAD

**Issue by gaodeng** [react-navigation/react-navigation#6960]
**Current Behavior**

react navigation stack + react native screens + react native webview will crash (null pointer dereference) when the pop stack

**Expected Behavior**

working fine

**How to reproduce**

react navigation stack + react native screens + react native webview will crash (null pointer dereference) after the pop webview's stack screen

**Your Environment**
latest

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | ANDROID
| react-navigation               |
| react-navigation-stack         |
| react-native-gesture-handler   |
| react-native-safe-area-context |
| react-native-screens           |
| react-native                   |
| expo                           |
| node                           |
| npm or yarn                    |

**Comment by satya164** [comment]
This seems like something which needs to be fixed in react-native-webview. Closing since it's not actionable for us and workaround is mentioned.

**Comment by andreialecu** [comment]
Leaving this here for future readers:

`androidLayerType="software"` has been making certain web content render as transparent/invisible for us. I would be able to long press to select text, and things like links would be clickable (and trigger navigation) but still everything would basically be invisible (as if rendered with `opacity: 0`).

Some HTML would render properly, but other wouldn't. Be careful with `androidLayerType="software"`.

**Comment by Aszurar** [comment]
With me the androidLayerType="software" property avoided the crash of react native render html/react native webview with videos, but when using it, it made the videos not work anymore and as mentioned above, sometimes it visually affected some HTML.
So, taking a look at the possible values it could receive, I used it as: androidLayerType="hardware" and it worked perfectly, whether on the emulator or physical Android device.

any problems using with the value as hardware?

```js
import RenderHtml from 'react-native-render-html';
...
    <RenderHtml
      renderers={{ iframe: IframeRenderer }}
      WebView={WebView}
      **defaultWebViewProps={{
        androidLayerType: 'hardware',
      }}**
      contentWidth={width * 0.9}
      source={{ html: html.replace(/src="\/\//g, 'src="https://') }}
      customHTMLElementModels={{ iframe: iframeModel }}
      renderersProps={{ iframe: { scalesPageToFit: true } }}
    />
```

**Comment by criszz77** [comment]
`androidHardwareAccelerationDisabled` did not work for me,  but the following solution did:

https://github.com/react-native-webview/react-native-webview/issues/811#issuecomment-570813204

```javascript
    <WebView
      style={{ opacity: 0.99 }}
    />
```
