### ISSUE TITLE
^2.1.1 stack casue  RecyclerListView report ' RecyclerListView needs to have a bounded size error '

### ISSUE THREAD

**Issue by gaodeng** [react-navigation/react-navigation#6962]
**Current Behavior**
![IMAGE 2020-02-05 23:44:29](https://user-images.githubusercontent.com/1118249/73857138-73d40300-4871-11ea-95f1-ed6f4131248a.jpg)

**Expected Behavior**
should working fine

**How to reproduce**
put RecyclerListView in first screen,push a few screen,it will report 
https://github.com/Flipkart/recyclerlistview/issues/144  issue.
It's is working  version 1.x without react native screens.

**Your Environment**
all latest

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |  ANDROID
| react-navigation               |
| react-navigation-stack         |
| react-native-gesture-handler   |
| react-native-safe-area-context |
| react-native-screens           |
| react-native                   |
| expo                           |
| node                           |
| npm or yarn                    |

**Comment by satya164** [comment]
Closing since `removeClippedSubviews` isn't used anymore.
