### ISSUE TITLE
Two or more screens could be opened at the same time using back swipe

### ISSUE THREAD

**Issue by VladTabaka** [react-navigation/react-navigation#6963]
**Current Behavior**

Here is an reproducible example https://snack.expo.io/ryjmtfwM8

- Include a screenshot or video if it makes sense.
![RPReplay_Final1580906837](https://user-images.githubusercontent.com/50845996/73843231-e966b180-4826-11ea-81fe-e65f2ef404ab.gif)

**Expected Behavior**

Screen is expected not to stuck after opening. (react-navigation-stack: "^1.10.3")
![RPReplay_Final1580908007](https://user-images.githubusercontent.com/50845996/73844694-bb36a100-4829-11ea-834c-f62147782f77.gif)

**How to reproduce**

1) Install the app
2) Tap 'Go to Details'
3) Start the swipe right from the left edge of the screen and spot at the center
4) Minimize the app
5) Open app

**Your Environment**

| software                              | version |
| --------------------------| ------- |
| iOS or Android                   | any
| react-navigation                | ^4.0.10"
| react-navigation-stack      | "^2.1.1"
| react-native-gesture-handler   | "^1.5.1"
| react-native-safe-area-context | "^0.6.0"
| react-native-screens           | "^2.0.0-beta.1"
| react-native                   | "0.61.5"
| expo                           | 36.0.0

**Comment by yuriybarnovich** [comment]
Have the same issue.

**Comment by satya164** [comment]
Fixed in #7898
