### ISSUE TITLE
Header Padding problem during startup.

### ISSUE THREAD

**Issue by lewatt23** [react-navigation/react-navigation#6966]
**Current Behavior**
 Hello everyone,  I have been having this problem on every new problem i created using react-navigation-stack,  when the stack initialized there is a Padding Top that is added then removed,so far i have created 3 projects and am having the some problem even after i build, can someone please help me? 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/21952062/73754502-c7a4f600-4764-11ea-897a-3d0db673f840.gif)

here is my code 

```
`//root navigator

import React from "react";
import { View } from "react-native";
import { createAppContainer } from "react-navigation";
import { createStackNavigator } from "react-navigation-stack";

import { DetailBilan, ListBilan } from "../screens";
import { SearchStack } from "./reservationNavigation";


//contains all  Bilan stack
const BilanStackTab = createStackNavigator(
  {
    ListBilanScreen: {
      screen: ListBilan
    },
    DetailBilanScreen: {
      screen: DetailBilan
    }
  },
  {
    initialRouteName: "ListBilanScreen"
  }
);



//route container
const AppContainer = createAppContainer(BilanStackTab);

export default AppContainer;
`

```

**Expected Behavior**

- What do you expect should be happening?
- Include a screenshot or video if it makes sense.

**How to reproduce**

- start a new react-native project
**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | 8.1
| react-navigation               |4.1.0
| react-navigation-stack         | 2.1.0
| react-native-gesture-handler   | 1.5.6
| react-native-safe-area-context | 0.6.4
| react-native-screens           | 2.0.0-alpha.34
| react-native                   | 61.5
| node                           | 10.7
| npm or yarn                    | 17.3

**Comment by satya164** [comment]
Closing since this shouldn't happen with latest version of `react-native-safe-area-context`.

**Comment by badbod99** [comment]
This issue is not resolved in current released version of react-navigation 4.

**Comment by TPXP** [comment]
I'm also still having this issue on Android with the current version of React-Navigation 5

**Comment by ShivamJoker** [comment]
<img width="401" alt="image" src="https://user-images.githubusercontent.com/23727670/145089168-bace6994-0d35-45d0-a31b-133a5fa79e93.png">
 
@satya164 same here
