### ISSUE TITLE
Dismissing modal in some screens crashes app

### ISSUE THREAD

**Issue by klaaz0r** [react-navigation/react-navigation#6970]
**Current Behavior**

I have a modal that works perfect on most screens but for some reason it completely breaks when used in one specific stack. I tried changing all the components to empty placeholders (remove all the complexity) but it keep breaking on the main/default stack. 

[![RPReplay-Final1580743187.gif](https://i.postimg.cc/SRK9XLXk/RPReplay-Final1580743187.gif)](https://postimg.cc/N9WFSH7z)

**Expected Behavior**
Do modal should dismiss regardless of the underlying content. 

**How to reproduce**
Production App

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | iOS
| react-navigation               | 4.0.10
| react-navigation-stack         | 2.1.0
| react-native-gesture-handler   | 1.4.1
| react-native-safe-area-context | 0.6.2
| react-native-screens           | -
| react-native                   | 0.64.1
| expo                           | -
| node                           | 12
| npm or yarn                    | yarn

**Comment by satya164** [comment]
Closing due to no response.
