### ISSUE TITLE
Header flick to white on fade out screen 

### ISSUE THREAD

**Issue by YogiHa** [react-navigation/react-navigation#6974]
**Current Behavior**

Header background set to white on the faded-out screen (until pressing back button al works normally), new screen loaded with right bg color

**Expected Behavior**

white flicker disappear

**How to reproduce**

this happens only when navigating back to the main screen. while navigating back in all other screens header bg stays as is and as expected.

my code below: 

{

const ListNavigation = createStackNavigator({ List });

const DrawerNavigation = createDrawerNavigator(
  {
    Home: ListNavigation
  },
  {
    defaultNavigationOptions: {
      header: null
    },
    contentComponent: Drawer,
    drawerWidth: Dimensions.get("window").width - 60
  }
);

export const RootStack = createStackNavigator(
  {
    DrawerNavigation,
   ...other screens
  },
  {
    defaultNavigationOptions: {
      header: null
    },
    headerMode: "screen"
  }
);

const MainRoutes = createStackNavigator(
  {
    ...other screens
    Main: RootStack
  },
  {
    defaultNavigationOptions: {
      header: null
    }
  }
);

export const AppRoutes = createAppContainer(MainRoutes);

class ThemeWrappedAppRoutes extends React.PureComponent {
  static router = AppRoutes.router;

  render() {
    let { themeType, themeColor, orangeIcons, onRef } = this.props;
    ThemeUtil.getThemeInstance().setThemeColor(
      themeType,
      themeColor,
      orangeIcons
    );
    const theme = getModifiedTheme(themeType, themeColor, orangeIcons);
    return (
      <View style={{ flex: 1 }} testID="main">
        <ThemeContext.Provider value={getTheme(theme)}>
          <AppRoutes
            ref={navigatorRef => {
              NavigationService.setTopLevelNavigator(navigatorRef);
              NotificationManager.onNavigatorReady();
              onRef(navigatorRef);
            }}
            {...this.props}
          />
        </ThemeContext.Provider>
       </View>
    );
  }
}

const mapStateToProps = ({ settingsReducer }) => {
  const { globalSettings = {} } = settingsReducer;
  const {
    theme_color = 0,
    global_theme_color = "",
    global_display_icons_in_orange
  } = globalSettings;
  return {
    themeType: theme_color,
    themeColor: global_theme_color,
    orangeIcons: global_display_icons_in_orange
  };
};

const mapDispatchToProps = dispatch => bindActionCreators({}, dispatch);

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(ThemeWrappedAppRoutes);

}

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | both
| react-navigation               | v3.11.0
| react-native-gesture-handler   | v1.3.0
| react-native                   | v0.59.5
| node                           | v12.13.0
| npm or yarn                    | npm v6.13.4 || yarn v1.21.1

thanks in advance

**Comment by satya164** [comment]
Closing due to no repro.
