### ISSUE TITLE
How to get header height in class based component ?

### ISSUE THREAD

**Issue by rahulnainwal107** [react-navigation/react-navigation#6975]
I am facing issue in getting header height in class based component. Although there is a solution for functional component but according to my project need, I need it in class based component.
Project details are:
"react": "16.9.0"
"react-native": "0.61.5"
"react-navigation": "^4.0.10"
"react-navigation-stack": "^2.0.15"

**Comment by bimix** [comment]
> ```js
> import { HeaderHeightContext } from 'react-navigation-stack';
> 
> // ...
> 
> <HeaderHeightContext.Consumer>
>   {headerHeight => (
>     /* render something */
>   )}
> </HeaderHeightContext.Consumer>
> ```

What about @react-navigation/stack package?
