### ISSUE TITLE
Can't use headerHideShadow prop in react-navigation 5.x

### ISSUE THREAD

**Issue by morteify** [react-navigation/react-navigation#6981]
**Current Behavior**

I can't use the _headerHideShow_ prop on Stack Navigator. It doesn't have any effect on actual UI element. What's more, even though it's mentioned in the documentation with description:

> Boolean indicating whether to hide the elevation shadow on the header.

 Typescript throws the error: 

> Type '{ headerHideShadow: boolean; }' is not assignable to type 'StackNavigationOptions | ((props: { route: RouteProp<Record<string, object>, string>; navigation: any; }) => StackNavigationOptions)'.  
> 
> Object literal may only specify known properties, and 'headerHideShadow' does not exist in type 'StackNavigationOptions | ((props: { route: RouteProp<Record<string, object>, string>; navigation: any; }) => StackNavigationOptions)'.
> 

Other props e.g. _headerShown_, which is included in the same section of docs, work properly.
My code (its relevant part):
```
import { createStackNavigator } from '@react-navigation/stack';
const Stack = createStackNavigator();

export function StatisticsStackNavigator() {
  return (
    <Stack.Navigator
      screenOptions={{
        headerShown: false, // works correctly
        headerHideShadow: true, // doesn't work
      }}>
      <Stack.Screen
        name="Statistics"
        component={StatisticsTopTabNavigator}
        options={{
          headerStyle: {
            backgroundColor: '#207193',
          },
          headerTintColor: '#fff',
          headerTitleStyle: {
            fontFamily: 'OpenSans-Regular',
            fontWeight: '700',
          },
        }}
      />
    </Stack.Navigator>
  );
}
```
 
**Expected Behavior**

According to the documentation, I'd expect to get rid of the header's elevation on one specific screen.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Android 9
| react-navigation               | 5.0.0-alpha.27
| react-navigation-stack         | 5.0.0-alpha.61
| react-native-gesture-handler   | 1.5.3
| react-native-safe-area-context | 0.6.2
| react-native-screens           | 2.0.0-alpha.25
| react-native                   | 0.61.5

**Comment by kockok** [comment]
With `6.6.2`, they changed to this `headerShadowVisible`
