### ISSUE TITLE
How to set the `transitionConfig` method in the API?

### ISSUE THREAD

**Issue by khat33b** [react-navigation/react-navigation#6982]
**Current Behavior**

In the previous API, we could set a `transitionConfig` method to the `navigationOptions` of any stack. In the current API, this option does not work. We need this to set a custom transition animation based on the RN Animation API. The new animations given [here](https://reactnavigation.org/docs/en/next/stack-navigator.html#animations) are not robust enough for this.

```
transitionConfig: () => ({
  screenInterpolator: sceneProps => {
    const {position, scene} = sceneProps;

    const thisSceneIndex = scene.index;
    const opacity = position.interpolate({
      inputRange: [thisSceneIndex - 1, thisSceneIndex - 0.5, thisSceneIndex],
      outputRange: [0, 1, 1],
    });
    const scale = position.interpolate({
      inputRange: [thisSceneIndex - 1, thisSceneIndex, thisSceneIndex + 1],
      outputRange: [4, 1, 1],
    });
    const scaleWithOpacity = {
      opacity,
      transform: [{scaleX: scale}, {scaleY: scale}],
    };

    return scaleWithOpacity;
  }
})
```

**Expected Behavior**

There has to be a option to set a custom transition animation based on the RN Animation API.

**How to reproduce**

Try to set a variable named `transitionConfig` method to the `navigationOptions` of a stack. We get a warning that this variable has beeen removed.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Android Q
| react-navigation               | 4.0.10
| react-navigation-stack         | 2.0.16
| react-native-gesture-handler   | 1.5.3
| react-native-safe-area-context | 0.6.2
| react-native-screens           | 2.0.0-alpha.22
| react-native                   | 0.62.0-rc.1
| expo                           | NA
| node                           | 13.7.0
| npm or yarn                    | 6.13.6

**Comment by Liqiankun** [comment]
@khat33b It seems like we have a same kinda issue. What did you do?

**Comment by shrynshJn** [comment]
Hey @khat33b were you able to figure out the right values for the delay when closing?
