### ISSUE TITLE
FlatList slow and start flicking (memory leak) when many screens in their previous routeStack.?

### ISSUE THREAD

**Issue by xpertystanalyst** [react-navigation/react-navigation#6987]
**Current Behavior**

FlatList start flicking and slow when we navigate from one list to another (screen1-list ---->screen-normal ----> screen3-list).

The list on first screen works fine but when i go to the 3rd screen its will start flicking and crash sometime and lots of frame drops (memory leak) in system trace. But while navigating to 3rd screen if i clear the previous route then its behave normal.

**Expected Behavior**

If i navigate to the multiple screens (1st screen to 3rd screen) the performance of the 3rd screen should same as 1st.

**How to reproduce**
 You can reproduce this issue by pushing the 2 or 3 screens with large FlatList data. You can see the performance difference of the list on 1st screen and the last screen on which you navigate.

**Your Environment**

"react": "16.9.0",
"react-native": "0.61.5",
"react-navigation": "^4.0.10",
"react-navigation-stack": "^2.0.16",

**Comment by satya164** [comment]
https://reactnavigation.org/docs/react-native-screens
