### ISSUE TITLE
Switching to v2 only return white blank screen

### ISSUE THREAD

**Issue by appify-waheed** [react-navigation/react-navigation#6990]
**Current Behavior**
I switch from v1.10.3 to v2.x.x and i also tried with the latest version and other 2.x.x versions , before update my code was working fine but after update got blank screen with only header showing route name on top of it.
<img width="353" alt="Screenshot 2020-01-23 at 5 41 07 PM" src="https://user-images.githubusercontent.com/45425486/72995716-32783800-3e1b-11ea-8920-66c613d2dd54.png">

**Expected Behavior**
Update to latest version and works normally.
**How to reproduce**
switch from v1.10.3 to v 2.xx 

**Your Environment**
Mac OS IOS 
| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |IOS
| react-navigation               |4.0.10
| react-navigation-stack         |2.x.x
| react-native-gesture-handler   |1.5.2
| react-native-safe-area-context |0.6.2
| react-native-screens           |2.0.0-alpha.12  but same with or without useScreens()
| react-native                   |0.61.2
| expo                           |
| node                           |10.16.2
| npm or yarn                    |6.11.3

**Comment by satya164** [comment]
Closing due to no repro.

**Comment by appify-waheed** [comment]
@satya164 could you please re-open this here is repo 
https://github.com/waheed25/IssueFixture

**Comment by satya164** [comment]
@appify-waheed i can't run your app. it crashes with some error related to pusher config. also we need a minimal repro, your repro contains a lot of unrelated code and it's not possible for us to debug it easily.

**Comment by appify-waheed** [comment]
@satya164 Okay, I will make a separate branch for it but can you please tell me the exact error you were facing?

**Comment by umang-simform** [comment]
Same issue here
