### ISSUE TITLE
Params not getting set in action generated by nested navigators with an initialRoute

### ISSUE THREAD

**Issue by TikiTDO** [react-navigation/react-navigation#6991]
Consider the following navigation layout

* TabNavigator
    * SomePath => StackNavigator
        * initialRouteName => SomeComponent

### Current Behavior

When I call `tabNavigator.getActionForPathAndParams("SomePath", {some: params})` I get an action with the following nav params:

```
{
  routeName: "SomePath",
  action: {
    routeName: "initialRouteName"
  }
}
```

without any params, because the code [here](https://github.com/react-navigation/react-navigation/blob/master/src/routers/StackRouter.js#L342) generates an initial action without consideration for `inputParam`.

### Expected Behavior

I expect to receive something like this:

```
{
  routeName: "SomePath",
  action: {
    routeName: "initialRouteName",
    params: {some: params}
  }
}
```
OR 

```
{
  routeName: "SomePath",
  params: {some: params},
  action: {
    routeName: "initialRouteName",
  }
}
```

One way or another, I would expect the params I specified to appear somewhere.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.23
| react-native     | 0.51.0
| node             | 8.0.0
| yarn      | 1.3.2

**Comment by satya164** [comment]
Closing since the code has changed a lot since opening the issue and I couldn't find the code linked in https://github.com/react-navigation/react-navigation/issues/6991#issuecomment-397477930

If you're still facing issues in the latest version, please open a new issue.
