### ISSUE TITLE
Not reducing header height in landscape on iOS 'Plus' devices

### ISSUE THREAD

**Issue by bodumotableau** [react-navigation/react-navigation#6992]
I see that on iOS devices, when the device is in landscape mode, we [check if the device is an iPad](https://github.com/react-navigation/react-navigation/blob/1764b21f3461b831b8135de36484bd9cfbd3032a/src/views/Header/Header.js#L27).

However, from observing the behavior of the navigation bar on Plus devices running iOS 10 and iOS 11, I noticed that the navigation bar maintains the same height in portrait and landscape modes just like the iPad.

Here are some screenshots from iBooks on an iPhone 6 Plus running iOS 10.0.2. 

**Portrait**
![portrait](https://user-images.githubusercontent.com/38145141/38513070-f478c6ba-3be1-11e8-91b6-93167cf5601e.PNG)
**Landscape**
![landscape](https://user-images.githubusercontent.com/38145141/38513073-f7a22a66-3be1-11e8-9084-0a11478fc3cf.PNG)
**Navigation bar cut from Landscape mode on the right. Lines up perfectly.**
![portraitlandscape](https://user-images.githubusercontent.com/38145141/38513080-fbd6ab5c-3be1-11e8-9da1-ca41ab928ece.png)

**Comment by satya164** [comment]
This shouldn't be an issue in react-navigation-stack 2.x. Please open a new issue for it if you're still encountering it with latest version.
