### ISSUE TITLE
Reset not working in nested routers with exposed router static

### ISSUE THREAD

**Issue by xanderberkein** [react-navigation/react-navigation#6994]
### Current Behavior & how to reproduce

`StackActions.reset` attaches itself to the wrong route in nested routes connected by an exposed router static. I prepared a snack where I combined some code snippets from the docs: 

https://snack.expo.io/@x11n/react-navigation-stack-reset

The snack exist of a very simple nested StackNavigator, with a React.Component in between. The two navigators are connected by the exposed `static router` in `HomeScreen` (as per [documentation](https://reactnavigation.org/docs/en/common-mistakes.html)) . 

When I try to reset the stack in the component located between the two navigators, the `reset` action gets confused (I think) and tries to reset on the InnerNavigator instead of the Top Level one. Since I'm not defining a key, the top level navigator should get reset ([docs](https://reactnavigation.org/docs/en/stack-actions.html#reset)).

I tested the same snippet with a `push` action, and that worked perfectly. Replacing the reset's `action` (line 25) with `StackActions.push` didn't make a difference.

Of course, without the exposed router static, everything works fine (since reset has nothing to be confused about anymore)

### Expected Behavior

I expect the top level navigator the one to be reset.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.0.0 (see snack)

**Comment by satya164** [comment]
Closing since this doesn't seem to be an issue with React Navigation 4.
