### ISSUE TITLE
Do not use forSlide hardcoded if header is hidden

### ISSUE THREAD

**Issue by mo22** [react-navigation/react-navigation#6998]
Hi,

the code in `react-navigation-stack@^2.0.15` `src/vendor/views/Header/HeaderContainer.tsx` sets `isHeaderStatic` if the next scene does not have a header.

Later it uses that to override the `styleInterpolator` with `forSlide` if `isHeaderStatic` is set.

However it would be nice if the `navigationOptions`'s `headerStyleInterpolator` property would be used if set, so that for non slide interpolations (in my case I use a slide from bottom) could use `forFade` or other interpolations.

Right now the new scene slides in from the bottom, still the previous's scene floating header slides to the left which does not look good.

```
        const previousScene = self[i - 1];
        const nextScene = self[i + 1];
        const isHeaderStatic =
          (previousScene &&
            previousScene.descriptor.options.headerShown === false &&
            // We still need to animate when coming back from next scene
            // A hacky way to check this is if the next scene exists
            !nextScene) ||
          (nextScene && nextScene.descriptor.options.headerShown === false);

        const props = {
          mode,
          layout,
          insets,
          scene,
          previous,
          navigation:  scene.descriptor.navigation as StackNavigationProp,
          styleInterpolator:
            mode === 'float'
              ? isHeaderStatic
                ? forSlide
                : styleInterpolator
              : forNoAnimation,
        };
```

**Comment by kbrandwijk** [comment]
Is this still an issue in v5 as well, that headerStyleInterpolator is completely ignored if the header is hidden in the source screen?
