### ISSUE TITLE
TextInput cursor is placed in the right corner when deleting the text

### ISSUE THREAD

**Issue by AntonBorovoi** [react-navigation/react-navigation#7000]
**Current Behavior**
TextInput caret moves to the end when trying to clear it.
![Screenshot_1579531455](https://user-images.githubusercontent.com/23105330/72735281-8c26fb00-3bac-11ea-98ca-d86892325921.png)

**Expected Behavior**
The caret should be centered.
**How to reproduce**
This issue only reproducible with the `textAlign=center` and defined `value` props for TextInput on android simulator and Huawei devices.

App.js
```import React from 'react';
import { Navigator } from './routing.js';

class App extends React.Component {
  render() {
    return (
      <Navigator />
    );
  }
}

export default App;
```

routing.js
```
import { createAppContainer, createSwitchNavigator } from 'react-navigation';
import { createStackNavigator } from 'react-navigation-stack';
import { SignIn } from 'signIn.js';

const routes = createStackNavigator({
  SignIn: SignIn,
});

const MainNavigator = createSwitchNavigator(
  {
    Anonymous: routes,
  },
);
export const Navigator = createAppContainer(MainNavigator);
```

SignIn.js
```
import React from 'react';
import { TextInput } from 'react-native';

export class SignInContainer extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      inputText: ''
    };
  }

  onChangeText = (text) => {
    this.setState({ inputText: text });
  };

  render() {
    return (
      <TextInput
        value={this.state.inputText}
        placeholder="placeholder"
        textAlign="center"
        onChangeText={this.onChangeText}
       />
    );
  }
}
```

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | API 21+
| react-navigation               | 4.0.9
| react-navigation-stack         | 1.7.3
| react-native-gesture-handler   | 1.3.0
| react-native-safe-area-context | -
| react-native-screens           | 2.0.0-alpha.1
| react-native                   | 0.60.5
| expo                           | -
| node                           | 11.10.1
| npm or yarn                    | 1.17.3

**Comment by rxliuli** [comment]
> @satya164 I am not sure how it may affect, but on an empty react-native project, it doesn't persist. Only if I include react-navigation package to empty project the issue will occur.

Still having this problem, how did you solve it?
