### ISSUE TITLE
Why Header.HEIGHT is deprecated

### ISSUE THREAD

**Issue by lorenc-tomasz** [react-navigation/react-navigation#7001]
Hi,
earlier in v1 there used to be Header.HEIGHT to get the height of the header. Now it seems to be deprecated in favour of useHeaderHeight hook in v2. It's awesome that there will be hook for that but why those that use class components have to create HOC to use it instrad of normal constant?

**Comment by cyphire** [comment]
I have spent 5 hours trying to stop the invariant violation call "Invalid hook call".  Tried every possible way.  Anyone else have problem calling useHeaderHeight from /stack?
