### ISSUE TITLE
error: bundling failed: Error: While trying to resolve module `react-native-safe-area-context` from file

### ISSUE THREAD

**Issue by bhirmbani** [react-navigation/react-navigation#7003]
I have installed `react-native-safe-area-context` but it give me this error

```
error: bundling failed: Error: While trying to resolve module `react-native-safe-area-context` from file `/Users/itmi/Documents/itmi-rn/node_modules/react-navigation-stack/lib/module/vendor/views/Stack/StackView.js`, the package `/node_modules/react-native-safe-area-context/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/node_modules/react-native-safe-area-context/src/index.tsx`. Indeed, none of these files exist:
```

**Current Behavior**

running `react-native start`
<img width="564" alt="Screen Shot 2020-01-20 at 14 18 49" src="https://user-images.githubusercontent.com/12825389/72706159-e82f5680-3b8f-11ea-8142-9bf2b4300133.png">

**Expected Behavior**

It should success build

**How to reproduce**

running `react-native start`

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | android
| react-navigation               | 4.0.10
| react-navigation-stack         | 2.0.15
| react-native-gesture-handler   | 1.5.3
| react-native-safe-area-context | ^0.6.2
| react-native-screens           | 2.0.0-alpha.25
| react-native                   | 0.61.5

**Comment by MohitR1999** [comment]
> for anyone have same problem like me, check following error on above: `However, this package itself specifies a `main` module field that could not be resolved (`/node_modules/react-native-safe-area-context/src/index.tsx`. Indeed, none of these files exist:`
> 
> if you have same error, add this on your `metro.config.js` file:
> 
> ```
> resolver: {
>     /* resolver options */
>    sourceExts: ['jsx','js', 'ts', 'tsx'] // add tsx if its not yet defined
>   },
> ```
> 
> then run `npm start -- --reset-cache`

thanks a lot @bhirmbani , it was a life saver :smile:

**Comment by kirhim** [comment]
@bhirmbani  where can I find the metro.config.js ? I see multiple files in my project.

**Comment by bhirmbani** [comment]
@kirhim at the root path should available, if not maybe you can create it manually.
this is mine
```
/**
 * Metro configuration for React Native
 * https://github.com/facebook/react-native
 *
 * @format
 */

module.exports = {
  resolver: {
    /* resolver options */
    sourceExts: ['jsx', 'js', 'ts', 'tsx'],
  },
  maxWorkers: 2,
  transformer: {
    getTransformOptions: async () => ({
      transform: {
        experimentalImportSupport: false,
        inlineRequires: false,
      },
    }),
  },
};

```

**Comment by kirhim** [comment]
@bhirmbani thanks! I found it in my root path :)

**Comment by KaumadieKariyawasam** [comment]
installing following two,

```
npm install --save @react-native-community/masked-view
npm install react-native-safe-area-context
```

it is work for me

**Comment by SourceCipher** [comment]
If anyone still have errors in metro, make sure you have metro config as stated by @bhirmbani and check what files are throwing the error as I had a library which had `.map` extensions so I had to add `map` to sourceExts to make `sourceExts: ['jsx', 'js', 'ts', 'tsx', 'map']`

Once I added map, the app finally built and I have all the libraries up to date to the latest versions
