### ISSUE TITLE
Custom header does not take all available space

### ISSUE THREAD

**Issue by bibipkins** [react-navigation/react-navigation#7010]
**Current Behavior**

Hi!
I am new to react-native and I have been following some beginner tutorials on youtube.
My main issue is setting width and height to 100% on my custom header. Instead of taking all the header space it just stays the same, it takes only as much space as its content needs. That is what works in the tutorial but does not work for me. The main difference is versions of our dependencies (will list them below). I searched through the docs and looked for this issue on the github, stackoverflow and all around the web but could not find any working solutions. I have also tried running web version of this app and found something interesting by looking at the generated DOM.

Here is my app, wrapper around the header does not take all the space, as a result setting width to 100% has no effect:
![myapp](https://user-images.githubusercontent.com/16402446/72222197-dbe14300-356a-11ea-9645-52ac1772cfeb.PNG)

Here is app from the tutorial, wrapper takes all the space:
![tutorialapp](https://user-images.githubusercontent.com/16402446/72222212-06330080-356b-11ea-80b6-6117167e2c9c.PNG)

**Expected Behavior**

Setting width and height style properties to 100% on custom header should make custom header take all available space. If it is not the way of forcing a custom header to fill the space please provide one

**How to reproduce**

Create a new expo app with a simple screen and stack navigation. Define a custom header and try setting width and/or height of it to 100%. Here is some example code:

my home stack:
```
import { createStackNavigator } from 'react-navigation-stack';
import React from 'react';
import Header from '../shared/header';
import Home from '../screens/home';

const screens = {
  Home: {
    screen: Home,
    navigationOptions: ({ navigation }) => {
      return {
        headerTitle: () => <Header navigation={navigation} />
      }
    }
  }
};

export default HomeStack = createStackNavigator(screens);
```
my custom header:
```
import React from 'react';
import { StyleSheet, Text, View } from 'react-native';

export default function Header ({ navigation }) {
  return (
    <View style={styles.header}>
      <View>
        <Text style={styles.headerText}>Foo</Text>
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  header: {
    width: '100%',
    flexDirection: 'row',
    alignContent: 'center',
    justifyContent: 'center',
    backgroundColor: 'red'
  },
  headerText: {
    fontWeight: 'bold',
    fontSize: 20,
    color: '#333',
    letterSpacing: 1,
    paddingLeft: 20
  }
});
```

**Your Environment**
my env:
```
"dependencies": {
    "@react-native-community/masked-view": "^0.1.5",
    "expo": "~36.0.0",
    "react": "~16.9.0",
    "react-dom": "~16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz",
    "react-native-gesture-handler": "^1.5.3",
    "react-native-reanimated": "^1.4.0",
    "react-native-safe-area-context": "^0.6.2",
    "react-native-web": "~0.11.7",
    "react-navigation": "^4.0.10",
    "react-navigation-drawer": "^2.3.3",
    "react-navigation-stack": "^2.0.13"
  }
```

env used in the tutorial:
```
"dependencies": {
    "expo": "^35.0.0",
    "react": "16.8.3",
    "react-dom": "16.8.3",
    "react-native": "https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz",
    "react-native-gesture-handler": "~1.3.0",
    "react-native-reanimated": "~1.2.0",
    "react-native-web": "^0.11.7",
    "react-navigation": "^4.0.10",
    "react-navigation-drawer": "^2.3.1",
    "react-navigation-stack": "^1.10.3"
  }
```

**Comment by vctr90** [comment]
Thanks @satya164 for your response here. To add to you solution a bit more, there is a disclaimer to it. From using your header as custom as specifying `header` component, be aware that the height should be completely controlled from our code from now on. No react navigation header helper anymore.
