### ISSUE TITLE
[v2.1.x] Peer dependency warning

### ISSUE THREAD

**Issue by ahce** [react-navigation/react-navigation#7026]
This version is compatible with react-native-safe-area-context >= 0.7.x (latest 0.6.2) ?

I am receiving these warnings:
```
npm WARN react-navigation-stack@2.1.1 requires a peer of react-native-safe-area-context@^0.6.0 but none is installed. You must install peer dependencies yourself.
```

#### Enviroment
- react-navigation-stack 2.1.1
- @react-native-community/masked-view 0.1.6
- react-native 0.61.5
- react-native-safe-area-context 0.7.2

**Comment by satya164** [comment]
@SPineapple for expo, you must install the correct versions.
