### ISSUE TITLE
navigation.replace animation with 2.0.x

### ISSUE THREAD

**Issue by cristianoccazinsp** [react-navigation/react-navigation#7031]
With version 2, `navigation.replace` will also animate. I wonder how can I disable the transition animation just for `.replace` calls? I want to keep the animation when doing `.navigate`, but no when replacing. 

Ideally, however, I want the `.replace` call to just animate "backwards". I'm using replace to go to a previous screen which I unmount since it's too heavy. How can I achieve that?

**Comment by iiAtlas** [comment]
For anyone looking at this in React Navigation v5, the `animationTypeForReplace` property should be used under a screens `options` [https://reactnavigation.org/docs/stack-navigator/#animationtypeforreplace](url)

```
<Stack.Navigator initialRouteName='main' screenOptions={{ headerShown: false }}>
        <Stack.Screen
            name='login' component={LoginScreen}
            options={{animationTypeForReplace: 'pop'}}>
        </Stack.Screen>
        <Stack.Screen name='done' component={DoneScreen}></Stack.Screen>
 </Stack.Navigator>
```
