### ISSUE TITLE
Unable to resolve module 'react-native-safe-area-context'

### ISSUE THREAD

**Issue by eae-christian** [react-navigation/react-navigation#7033]
Hi, I did the upgrade of react-navigation-tabs from 1.10.3 to 2.0.1 and immediately after restarting the application I found that the following error (attached photo)

![Screenshot 2020-01-02 at 09 22 37](https://user-images.githubusercontent.com/49148186/71660063-c6d20c00-2d41-11ea-89e9-c38a36d0156d.png)

Description of my environment

"react": "16.11.0",
"react-native": "0.61.5",
"react-native-gesture-handler": "^1.5.3",
"react-native-screens": "^2.0.0-alpha.22",
"react-navigation": "^4.0.10",
"react-navigation-drawer": "^2.3.3",
"react-navigation-stack": "^2.0.1",
"react-navigation-tabs": "^2.6.2",

I'm just developing for iOS

Do you have any solution?
Thank you

**Comment by EhsanSarshar** [comment]
install 
```
"@react-native-community/masked-view"
"react-native-safe-area-context"
```
and then 
```
cd ios
pod install
```

**Comment by EstebanCoder2054** [comment]
If you are having some issues with react navigation, you can try installing this dependencies:
 1- @react-native-community/masked-view
 2- react-native-safe-area-context
 3- react-native-screens
It worked for me!!

**Comment by osman144** [comment]
^ Following the steps above, do 
1. react-native link
2. Pod install

**Comment by Chinnapetchi** [comment]
https://github.com/react-navigation/react-navigation/issues/7033#issuecomment-627468560

tq

**Comment by Chinnapetchi** [comment]
> ^ Following the steps above, do
> 
> 1. react-native link
> 2. Pod install

tq
