### ISSUE TITLE
Question: how to navigate smoothly

### ISSUE THREAD

**Issue by KisaneNeko** [react-navigation/react-navigation#7038]
Hi, I'm having a problem with stack navigation but I can't share the production code, so I created a fork to represent the issue:
https://github.com/KisaneNeko/stack/tree/laggy-navigation-question

When you put some expensive code inside component lifecycle methods (or hooks), the navigation animation will only happen when this code is finished. We used to deal with that by wrapping any expensive code, that was required on init, inside `InteractionsManager.runAfterInteractions` and it worked fine until we updated react-navigation (from `2.18.3` to `4.0.10`).

Now in our production code, navigation seems to happen instantly, but the code inside `runAfterInteractions` is not triggered right after, it takes a random amount of time to start therefore content loading is dramatically longer.

So there are three cases:
1. Expensive code directly inside i.e. `componentDidMount` - there's a significant lag after the click and before the navigation animation:
![laggy nav](https://user-images.githubusercontent.com/5794356/71411631-77f1eb80-264a-11ea-9697-cf537d459e65.gif)

2. Expensive code inside `componentDidMount` wrapped inside the `runAfterInteractions` - navigation happens instantly, but the processing doesn't start right away but after a random delay, adding up to 3 seconds to screen loading time. I wasn't able to reproduce it with the example code unfortunately, but in the example it worked like the above, so `runAfterInteractions` is not a valid solution either way.

3. Expensive code inside `componentDidMount` wrapped inside the `setTimeout` - setTimeout without any delay value will simply push the expensive action to the end of the callstack, and it will result in instant and smooth transition (exactly what I want) but it feels like a hack.
![smooth nav](https://user-images.githubusercontent.com/5794356/71411749-e5058100-264a-11ea-86ac-784e3699ca93.gif)

Is there a better way to achieve this smooth transition in a proper way? Or is the `setTimeout` the only way to do it?

**Comment by KisaneNeko** [comment]
I can see this issue has been transferred, anyone willing to check it out?

**Comment by satya164** [comment]
Like you mentioned in your issue, `setTimeout` works and is a reasonable solution. `runAfterInteractions` will only run after the animation finishes, which can take longer due to spring animation settling.

**Comment by batuhansahan** [comment]
@KisaneNeko have you solve it

**Comment by KisaneNeko** [comment]
@batuhansahan 
> Expensive code inside componentDidMount wrapped inside the setTimeout - setTimeout without any delay value will simply push the expensive action to the end of the callstack, and it will result in instant and smooth transition (exactly what I want) but it feels like a hack.

I haven't found any better way than `setTimeout` at the time, but that was 3 years ago so I'm not sure if this issue is still relevant with current state of react, react-native and react-navigation. Also there might be a better solution out there now.

**Comment by darion6** [comment]
I'm have this problem currently
