### ISSUE TITLE
RN 0.60 - Android - HeaderTitle isn't bold anymore

### ISSUE THREAD

**Issue by brunohkbx** [react-navigation/react-navigation#7043]
It seems like the `fontWeight` prop behavior changed since RN 0.60.
Related issue: 
https://github.com/facebook/react-native/issues/25696

Expo SDK 35 using RN 0.59
![sdk-35](https://user-images.githubusercontent.com/6487206/70581097-cefcb880-1b94-11ea-9dc7-1ace23f912e6.png)

Expo SDK 36 using RN 0.60
![sdk-36](https://user-images.githubusercontent.com/6487206/70581107-d4f29980-1b94-11ea-84b3-dec39d4bbe1d.png)

Should the [default value](https://github.com/react-navigation/stack/blob/master/src/views/Header/HeaderTitle.tsx#L22) of fontWeight in the `HeaderTitle` component be 'bold' on android platform ?

**Comment by ARDcode** [comment]
@brunohkbx u can use this temporary solution before 0.62 release for Expo and RN: [react-native-text-weight](https://www.npmjs.com/package/react-native-text-weight)

**Comment by satya164** [comment]
Closing since this is now fixed in latest stack.
