### ISSUE TITLE
[Web] Working on dev, not working on prod

### ISSUE THREAD

**Issue by billygl** [react-navigation/react-navigation#7046]
**What happened:**

There is an issue with StackView.js
![image](https://user-images.githubusercontent.com/442925/70289296-549df400-17a2-11ea-8f65-12d5a77f6fe2.png)
when It is built with `react-app-rewired build` and serve as static with `serve -s src/web/build -d`
But it is working fine when it is run with `react-app-rewired start`
It is a monorepo project with Lerna, an Creat React App (customize-cra, and react-app-rewired)
```
The config for rewired is:
module.exports = override(
    babelInclude([
        path.resolve('src'), 
        path.resolve(__dirname, '../app'),
        path.resolve(__dirname, '../../node_modules'),
    ]),
    addBabelPresets(
        "module:metro-react-native-babel-preset"
    ),
    addWebpackAlias({
        "react-native/Libraries/Renderer/shims/ReactNativePropRegistry": "react-native-web/dist/modules/ReactNativePropRegistry",
        "react-native": "react-native-web"
    })
);
```
I tried the configuration with webpack explained in http://necolas.github.io/react-native-web/docs/?path=/docs/guides-multi-platform--page  
But not running at all.

It works ok with SwitchNavigator in dev and prod (https://github.com/react-navigation/web-server-example) but not for react-navigation-stack.
I tried https://www.npmjs.com/package/react-navigation-stack-web but not working. It has another issue:
![image](https://user-images.githubusercontent.com/442925/70289787-e9edb800-17a3-11ea-86b7-08f8fe4e88bd.png)

**Environment:**
Windows 10

**Comment by satya164** [comment]
Closing since latest versions of React Navigation don't require code on web to be compiled with Babel.
