### ISSUE TITLE
Allow HeaderBackButton accessibility label to be customized

### ISSUE THREAD

**Issue by ludovic-gonthier** [react-navigation/react-navigation#7050]
I am doing some work on the accessibility of my application and have the need to change the `accessibilityLabel` put by default in the current version of the code of **HeaderBackButton**:

```js
label && label !== 'Back' ? `${label}, back` : 'Go back'
```

I would like to be able to change it because the customers of the application will be French, and having mixed languages in a screen reader doesn't feel good.

**Comment by satya164** [comment]
Closing since `HeaderBackButton` now accepts an `accessibilityLabel` prop.

**Comment by dprevost-LMI** [comment]
And what about accessibilityHint?
