### ISSUE TITLE
Title does not truncate

### ISSUE THREAD

**Issue by miguelneves** [react-navigation/react-navigation#7057]
The long titles should truncate and fill a single line. It works on the previous version of react navigation stack

![Screenshot 2019-11-14 at 12 12 36](https://user-images.githubusercontent.com/736753/68856423-5d863300-06d8-11ea-91a5-fd75d77d8334.png)

"react-native": "0.61.4"
"react-navigation": "^4.0.10"
"react-navigation-stack": "^2.0.0-alpha.37"

**Comment by evrimfeyyaz** [comment]
This issue still persists on `react-navigation-stack@2.2.2`.

**Comment by tinchev** [comment]
This issue is also present with:
```
    "react-native": "^0.62.0",
    "@react-navigation/native": "5.1.5",
    "@react-navigation/stack": "5.2.10",
```

**Comment by omgo** [comment]
this issue still present

> "react-native": "0.63.4",
> "@react-navigation/core": "^5.15.2",
> "@react-navigation/drawer": "^5.12.4",
> "@react-navigation/native": "^5.9.3",
> "@react-navigation/stack": "^5.14.3"

```
<Stack.Screen
  name="PasswordChange"
  options={{
    title: 'Very long title very long title very long title',
    headerLeft: ButtonBack,
    headerRight: () => <ButtonLogout onPress={onLogout} />
  }}
>
```

![image](https://user-images.githubusercontent.com/13779291/116428489-a179e300-a84d-11eb-9243-b00527d73d4d.png)

**Comment by ozgurbayram** [comment]
Current solution. In the option 
`                headerTitleAlign:'left',
`


versions:
- `"@react-navigation/native": "^6.0.10",`
- `"@react-navigation/native-stack": "^6.6.2",`

**Comment by fukemy** [comment]
headerTitleContainerStyle seem not working anymore with v6, any solutions now?

**Comment by SethCram** [comment]
The only thing that worked for me was creating a custom header component and playing around with that
```
options={{
          headerTitle: (props) => <ReplacementHeader title={props.children} />,
        }}
```
```
interface IReplacementHeaderProps {
  title: string
}

const ReplacementHeader = ({ title }: IReplacementHeaderProps) => {
  return (
      <View style={styles.headerContainer}>
        <Text style={styles.headerTitle} numberOfLines={1} ellipsizeMode="tail">
          {title}
        </Text>
      </View>
  );
};

const styles = StyleSheet.create({
  headerContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%', //play around with this value
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: "bold",
  },
});

export default ReplacementHeader;
```
