### ISSUE TITLE
Need example for Moving back to screen on different stack navigator?

### ISSUE THREAD

**Issue by mukeshsharma1201** [react-navigation/react-navigation#7064]
### Current Behavior

I have 2 Stack navigators inside Tab navigator.
```
Bottom Tab Navigator
- Dashboard Stack Navigator
   - Dashboard Landing screen
   - Dashboard details

- Accounts Stack Navigator
   - Accounts Landing Screen
   - Accounts Details
```

### PROBLEM:
from `Dashboard Landing` screen, if I do `navigation.navigate('AccountDetails');` it takes me to  `AccountDetails` , 

**but while going BACK** , `navigation.goBack()` **or** `navigation.pop()` **takes me to** `Account Landing` **screen, instead of** `Dashboard Landing` **screen!**

### Expected Behavior

- `navigation.goBack()` should take me to the screen I navigated from!

### No Solution available? 
I searched StackOverflow and closed issues and I am surprised that there is absolutely no clear answer anywhere!! 
**Can someone please provide an example of going back to screen in another stack?**
 
Few similar questions and issues: 
- https://github.com/react-navigation/react-navigation/issues/6434
- https://github.com/react-navigation/react-navigation/issues/4403
- [how-to-navigate-between-different-nested-stacks-in-react-navigation](https://stackoverflow.com/questions/49826920/how-to-navigate-between-different-nested-stacks-in-react-navigation) 
- [react-navigation-goback-between-stack-navigators](https://stackoverflow.com/questions/57350138/react-navigation-goback-between-stack-navigators)
- [react-navigation-how-to-go-back-to-a-screen-in-another-stack-from-a-stack](https://stackoverflow.com/questions/51946507/react-navigation-how-to-go-back-to-a-screen-in-another-stack-from-a-stack)
- https://github.com/react-navigation/react-navigation/issues/697 

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^4.0.10
| react-native     | ^0.60.5
| node             | v12.9.1
| npm or yarn      | npm

**Comment by zach-luman** [comment]
Any solution here?
