### ISSUE TITLE
Unable to resolve module './views/Header/HeaderStyleInterpolator

### ISSUE THREAD

**Issue by MorgadoKnivet** [react-navigation/react-navigation#7074]
Hello People. I did update react-navigation-stack to  "react-navigation-stack": "^2.0.0-alpha.26" to implement ios 13 modal. Can help me with issue? Thanks.

![Screen Shot 2019-10-13 at 12 05 01](https://user-images.githubusercontent.com/34779500/66717650-b305b200-edb1-11e9-99de-236027d64165.png)

React-Native - 60.5
React-navigation-stack - 2.0.0-alpha.26

**Comment by antstu** [comment]
Hi I have been trying to resolve the same issue for about three days now. I am using expo and upgraded to react-navigation-stack version "^2.3.4". I have tried all of the recommended troubleshooting, however to no avail. I uninstalled everything, removed node_modules, ran expo start -c. Nothing works.

This is my package.json and the error I'm getting. Can someone please help?


`  "dependencies": {
    "@expo/vector-icons": "^10.0.0",
    "@firebase/firestore": "^1.12.2",
    "@react-native-community/art": "^1.2.0",
    "@react-native-community/masked-view": "0.1.5",
    "@react-native-community/segmented-control": "^1.2.1",
    "algoliasearch": "^3.35.1",
    "base-64": "^0.1.0",
    "buffer": "^5.4.3",
    "color": "^3.1.2",
    "core-js": "^3.6.4",
    "crypto-js": "^3.1.9-1",
    "d3-scale": "^3.2.1",
    "expo": "^36.0.0",
    "expo-asset": "~8.0.0",
    "expo-av": "~8.0.0",
    "expo-battery": "~2.0.0",
    "expo-blur": "~8.0.0",
    "expo-camera": "~8.0.0",
    "expo-contacts": "~8.0.0",
    "expo-file-system": "~8.0.0",
    "expo-font": "~8.0.0",
    "expo-gl": "~8.0.0",
    "expo-haptics": "~8.0.0",
    "expo-image-manipulator": "~8.0.0",
    "expo-image-picker": "~8.0.1",
    "expo-linear-gradient": "~8.0.0",
    "expo-mail-composer": "~8.0.0",
    "expo-sqlite": "~8.0.0",
    "expo-web-browser": "~8.0.0",
    "firebase": "^7.12.0",
    "firebase-admin": "^8.10.0",
    "firebase-functions": "^3.5.0",
    "flatted": "^2.0.1",
    "formik": "^2.1.4",
    "gl-react": "4.0.1",
    "gl-react-expo": "4.0.1",
    "lottie-react-native": "~2.6.1",
    "moment": "^2.24.0",
    "patch-package": "^6.2.0",
    "react": "16.9.0",
    "react-content-loader": "^4.3.4",
    "react-dom": "16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz",
    "react-native-animatable": "^1.3.3",
    "react-native-collapsible": "^1.5.1",
    "react-native-dropdownalert": "^4.2.1",
    "react-native-elements": "^1.2.7",
    "react-native-gesture-handler": "~1.5.0",
    "react-native-gifted-chat": "^0.12.0",
    "react-native-progress": "^4.0.3",
    "react-native-push-notification-popup": "^1.4.0",
    "react-native-reanimated": "~1.4.0",
    "react-native-redash": "^10.0.1",
    "react-native-safe-area-context": "0.6.0",
    "react-native-screens": "2.0.0-alpha.12",
    "react-native-shared-element": "~0.5.1",
    "react-native-svg": "9.13.3",
    "react-native-touchable-scale": "^2.1.0",
    "react-native-vector-icons": "^6.6.0",
    "react-native-web": "^0.11.7",
    "react-native-webview": "7.4.3",
    "react-navigation": "^4.3.2",
    "react-navigation-drawer": "^2.4.6",
    "react-navigation-hooks": "^1.0.3",
    "react-navigation-shared-element": "^2.2.0",
    "react-navigation-stack": "^2.3.4",
    "react-navigation-tabs": "^2.8.6",
    "react-redux": "^7.2.0",
    "redux": "^4.0.5",
    "redux-persist": "^6.0.0",
    "redux-thunk": "^2.3.0",
    "shorthash": "0.0.2",
    "styled-components": "^5.0.1",
    "use-memo-one": "^1.1.1",
    "yup": "^0.28.3"
  },`

![Simulator Screen Shot - iPhone 11 Pro - 2020-03-21 at 19 18 32](https://user-images.githubusercontent.com/45006351/77238675-e17d8980-6ba8-11ea-8292-5a235e0c0039.png)

**Comment by zigcccc** [comment]
Even after deleting node_modules, reinstalling and starting the project with `expo start -c`, the problem persists... Any other ideas?

React Native: https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz
React: "16.9.0"
React Navigation: "^4.3.7"

**Comment by xiCO2k** [comment]
having the exact same issue @zigcccc

**Comment by tuthanhnguyen** [comment]
have same issue. I'm starting hate react.

**Comment by zigcccc** [comment]
@xiCO2k I was able to solve the issue by running `rm -rf $TMPDIR/react-native-packager-cache-* && rm -rf $TMPDIR/metro-bundler-cache-*` and than `expo start -c`. Apparently it was a cache issue after all. I hope this solves your problem as well.

@tuthanhnguyen no need to start hating React. This is not even a React issue (nor React Navigation for that matter). Managing and updating packages is, at least in my opinion, the weakest link in the Node environment and it can be a pain I agree, but it is solvable especially with the help of the community.

**Comment by tuthanhnguyen** [comment]
> @xiCO2k I was able to solve the issue by running `rm -rf $TMPDIR/react-native-packager-cache-* && rm -rf $TMPDIR/metro-bundler-cache-*` and than `rm -rf node_modules && npm install && expo start -c`. Apparently it was a cache issue after all. I hope this solves your problem as well.
> 
> @tuthanhnguyen no need to start hating React. This is not even a React issue (nor React Navigation for that matter). Managing and updating packages is, at least in my opinion, the weakest link in the Node environment and it can be a pain I agree, but it is solvable especially with the help of the community.

Thank you so much @zigcccc . It's quite pain when I have to solve sudden issue even I didn't modify code yet. Anyway, thanks for your support. It helps me.

**Comment by xiCO2k** [comment]
Solved it Upgrading to v5 ;)

**Comment by churromorales20** [comment]
> Solved it Upgrading to v5 ;)

Hi how did you managed to upgrade to V5 i have same issue

**Comment by xiCO2k** [comment]
I did the "expo start -c" and did all the reactor for the v5

**Comment by twero** [comment]
I have the same issue, still can work it out,
im using, react-native-cli

**Comment by raajnadar** [comment]
@twero For react native use this cmd `npx react-native run-android --reset-cache`
