### ISSUE TITLE
Stack header elevation shadow blinks during transition

### ISSUE THREAD

**Issue by Grohden** [react-navigation/react-navigation#7089]
I'm having a problem with the current navigation stack **header** transition using material tabs.

It's better to show it instead of explaining, so here's a gif:
![20190925_131000](https://user-images.githubusercontent.com/7496871/65619307-4c515d80-df96-11e9-87bf-9258457d88ab.gif)

Also, here's a expo example (I could only reproduce it on a **physical** device):
https://snack.expo.io/@grohden/a3ad19

Expo is faster than on my app, so it's just a blink on the expo app from playstore, but you can still see it (I hope)

Note: The `elevation: 20` is just to make it easier to see the problem, omitting it still causes the problem.

Not sure how this could be solved, the only thing that fixed it was to set the elevation to 0... but that's no solution :/

**Comment by MasterRedStorm** [comment]
This stil happens
