### ISSUE TITLE
Excuse me, {gesturesEnabled: true} doesn't work on android

### ISSUE THREAD

**Issue by graviation** [react-navigation/react-navigation#7104]
react-navigation/react-navigation#6103 
# Current Behavior

```
let HomeStack = createStackNavigator({
    Home: HomeScreen,
    Details: DetailsScreen,
    Register: {
      screen: RegisterScreen,
      navigationOptions: {
        gesturesEnabled: true,
      },
    },
  });
```

If set `gesturesEnabled: false` is correct on iOS,  but set `gesturesEnabled: true`  doesn't work on android. Can you give us an example？ thanks

| software              | version
| ---------------- | -------
| react-navigation |  4.0.0
| react-native        |  0.60.5
| node                    |  v12.9.1
| yarn                     |  1.17.3

**Comment by appli-intramuros** [comment]
Any update ?

**Comment by TQCasey** [comment]
met the same issue with rn 0.61... 
any solutions ?

**Comment by raajnadar** [comment]
Try upgrading to latest version i.e. ver 5
