### ISSUE TITLE
Adding a full-screen background image to a StackNavigator

### ISSUE THREAD

**Issue by jb-** [react-navigation/react-navigation#7114]
### Current Behavior

StackNavigator itself has whity background color and it is not changed through style attribute.
Thus ImageBackground is not visible.

```js
const PresetNavigatorInner = createStackNavigator({
  InterestScreen, /* each screen has transparent background */
  PurposeScreen,
  NicknameScreen,
}, {
  cardStyle: {
    backgroundColor: 'transparent',
  },
  transparentCard: true,
  transitionConfig: () => ({
    containerStyle: {
      backgroundColor: 'transparent',
    },
  }),
  initialRouteName: 'InterestScreen',
});

class PresetNavigator extends React.Component {
  static router = PresetNavigatorInner.router;

  render() {
    const { navigation } = this.props;
    return (
      <ImageBackground
        source={require('../assets/ScreenBackground.png')}
        style={{ width: '100%', height: '100%' }}
      >
        <PresetNavigatorInner style={{ backgroundColor: 'transparent' }} navigation={navigation} />
        {/* <InterestScreen /> */}
      </ImageBackground>
    );
  }
}
```

### Expected Behavior

I want a transparent StackNavigator (and its screens to be navigated) wrapped with ImageBackground so that the background image stays fixed while navigate forward or back.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.12.0
| react-native     | 0.59.0
| node             | 8.15.0
| yarn      | 1.15.2

**Comment by fazal26** [comment]
I cant find anything relating background image in `React Navigation 5`. Things I've tried so far:
1- adding a parent ImageBackground and setting `Stack Navigator` with transparent background as
`<Stack.Navigator screenOptions={{ cardStyle: { backgroundColor: "transparent" } }}>`
with this the screen being navigated collapse on each other, the source screen seems to be transitioned half way the screen.
2- If I use background color for screens the source screen is hidden by the destination screen's background color.
3- another thing I can do is to move ImageBackground to a baseScreen for every screen, which I don't like personally.

If there is a way to set background Image once for all the screens under a navigator, please do share.

**Comment by ultimateshoppingapp** [comment]
this code below will solve the problem, i have the background set to my image,
just change the image location and see 


import * as React from 'react';
import { Button, View, Text, Image, StyleSheet, ImageBackground, TouchableOpacity, BackgroundColor } from 'react-native';
import Constants from 'expo-constants';
import { NavigationContainer } from '@react-navigation/native';
import { createStackNavigator } from '@react-navigation/stack';
import { Card } from 'react-native-paper';

const Stack = createStackNavigator();



 function MyCustomHeaderBackImage() {
  return (
    <Image 
      style={{ width: 30, height: 30,}}      
      source={require('./assets/backicon.png')}
     />
    ); }             
          


function HomeScreen({ navigation }) {
  return (
    <View style={{ flex: 1, 
                   alignItems: 'left', 
                   justifyContent: "flex-end",
                   flexDirection: "column",
                   padding: 1,
                   height: "10%",
                   width: "100%",
                   transparentCard: true,
                   backgroundColor: 'transparent',                        
                   }}>
                  
               <ImageBackground
                style={{width: '100%', height: '100%'}}
                source={require('./assets/backgroundimage.png')} >
               
               <Button title="Go to Details"
                onPress={() => navigation.navigate('Details')} />        
              
              </ImageBackground>
     </View>  );  }

function DetailsScreen({ navigation }) {
  return (
    <View style={{ flex: 1, 
                   alignItems: 'left', 
                   justifyContent: "flex-end",
                   flexDirection: "column",
                   padding: 1,
                   height: "10%",
                   width: "100%",
                   transparentCard: true,
                   backgroundColor: 'transparent',                        
                   }}>
                  
               <ImageBackground
                style={{width: '100%', height: '100%'}}
                source={require('./assets/backgroundimage.png')} >
               
      <Text>Details Screen</Text>
      <Button title="Go to Details... again"
        onPress={() => navigation.push('Details')} />
      <Button title="Go to Home" 
        onPress={() => navigation.navigate('Home')} />
      <Button title="Go back" 
        onPress={() => navigation.goBack()} />
      <Button
        title="Go back to first screen in stack"
        onPress={() => navigation.popToTop()}  />
               
               </ImageBackground>
    </View>  ); }

function LogoTitle() {
  return (
    <Image
     style={{ width: 245, height: 55 }}
      source={require('./assets/ultimateimage3new.png')}
     />
    ); }    


function App() {
  return (   
    <NavigationContainer>
      
      <Stack.Navigator initialRouteName="Home" 
      screenOptions={{headerStyle: { backgroundColor: '#000000', },
                      headerBackImage: MyCustomHeaderBackImage   ,                              
                      headerTintColor: '#ffffff', 
                      headerTitleStyle: { fontWeight: 'bold', },
                      headerTitleAlign: 'center',
                      headerTitle: props => <LogoTitle {...props} />
                      }}>
 
             
         <Stack.Screen name="Home" component={HomeScreen}
                       
                       options={{ title: 'Main Page', 
                       cardStyle: {backgroundColor: 'transparent',                                                                            shadowColor:'transparent'},
                       transparentCard: true,
                       transitionConfig: () => ({ containerStyle: {
                       backgroundColor: 'transparent', }, 
                       }),                       
                        }} 
                       />
                        
         <Stack.Screen name="Details" component={DetailsScreen}
                       options={{ title: '2nd Page', 
                       cardStyle: {backgroundColor: 'transparent',                                                                            shadowColor:'transparent'},
                       transparentCard: true,
                       transitionConfig: () => ({ containerStyle: {
                       backgroundColor: 'transparent', }, 
                       }),        
                        }} />
                       
      </Stack.Navigator>

   
   
    </NavigationContainer>  
  );
}



export default App;

**Comment by DanielFredriksson** [comment]
Any smarter solution on the horizon?

**Comment by GregoryWullimann** [comment]
Maybe I have a solution using themes, it works well for me.

By default the theme has background set to `rgb(242,242,242)`, so the whole navigator has that background.

What I did is create a custom theme with transparent background color and set the theme to my `NavigatorContainer`

```
import { NavigationContainer, DefaultTheme } from '@react-navigation/native';
const MyTheme = {
  ...DefaultTheme,
  colors: {
    ...DefaultTheme.colors,
    background: 'transparent',
  },
};
```
Then depending on where I want the background image I can use a `ImageBackground`, so in my case I used it on a StackNavigator. In this way all the navigator in that stack will have the same background


```
const MyStackNavigator = createStackNavigator();

<NavigationContainer theme={MyTheme}>
     <ImageBackground source={require("../assets/my_background_image.png")} resizeMode="cover" style={{ width: "100%", flex: 1, justifyContent: "center" }}>
    <MyStackNavigator.Navigator screenOptions={defaultNavOptions}>
        <MyStackNavigator.Screen name="MyScreenName" component={MyScreen} options={screenOptions} />
    </MyStackNavigator.Navigator>
  </ImageBackground>
</NavigationContainer>
```

**Comment by RomanSuvorov** [comment]
> Maybe I have a solution using themes, it works well for me, this is **react-navigation 6** tho
> 
> By default the theme has background set to `rgb(242,242,242)`, so the whole navigator has that background.
> 
> What I did is create a custom theme with transparent background color and set the theme to my `NavigatorContainer`
> 
> ```
> import { NavigationContainer, DefaultTheme } from '@react-navigation/native';
> const MyTheme = {
>   ...DefaultTheme,
>   colors: {
>     ...DefaultTheme.colors,
>     background: 'transparent',
>   },
> };
> ```
> 
> Then depending on where I want the background image I can use a `ImageBackground`, so in my case I used it on a StackNavigator. In this way all the navigator in that stack will have the same background
> 
> ```
> const MyStackNavigator = createStackNavigator();
> 
> <NavigationContainer theme={MyTheme}>
>      <ImageBackground source={require("../assets/my_background_image.png")} resizeMode="cover" style={{ width: "100%", flex: 1, justifyContent: "center" }}>
>     <MyStackNavigator.Navigator screenOptions={defaultNavOptions}>
>         <MyStackNavigator.Screen name="MyScreenName" component={MyScreen} options={screenOptions} />
>     </MyStackNavigator.Navigator>
>   </ImageBackground>
> </NavigationContainer>
> ```

If MyTheme.colors.background set "tranparent", you will blink during screens animation

**Comment by tylerku** [comment]
This still seems to be the issue ^. Does anyone have a solution to this?

**Comment by Saralhossain** [comment]
how about if user wants to upload image which will be store in redux, so It will be render in background screen, otherwise it will shows backgroundcolor, else background color will be transparent and image will be none? is there any screenOption component for background Image? like headerImage?
