### ISSUE TITLE
(0, _reactNavigationStack.createAppContainer) is not a function

### ISSUE THREAD

**Issue by domene96** [react-navigation/react-navigation#7119]
New to react. Received a year (stagnated) project and am currently attempting to make it run. Updated expo from 25 to 34 and implemented createStackNavigator, createAppContainer over deprecated StackNavigator.

Complete error:
(0, _reactNavigationStack.createAppContainer) is not a function. (In '(0, _reactNavigationStack.createAppContainer) (MenuNav)', '(0, _reactNavigationStack.createAppContainer)' is undefined)

package.json:`
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "expo": "^34.0.1",
    "firebase": "^6.4.0",
    "react": "16.8.3",
    "react-dom": "^16.8.6",
    "react-native": "https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz",
    "react-native-communications": "^2.2.1",
    "react-native-datepicker": "^1.6.0",
    "react-native-easy-grid": "^0.2.0",
    "react-native-fast-image": "^4.0.12",
    "react-native-fcm": "^14.1.3",
    "react-native-gesture-handler": "^1.3.0",
    "react-native-image-zoom-viewer": "^2.0.20",
    "react-native-lightbox": "^0.8.0",
    "react-native-reanimated": "^1.1.0",
    "react-navigation": "^3.11.1",
    "react-navigation-stack": "^1.4.0",
    "react-native-web": "^0.11.4",
    "uuid": "^3.2.1"
  },
  "devDependencies": {
    "babel-preset-expo": "^6.0.0"
  },
  "private": true
}
`

App.js:
`
import React from 'react';
import { StyleSheet, Text, View, Modal, Dimensions, Animated, Image, Button, Easing, Platform} from 'react-native';
import Menu from './tabs/Menu';
import Cpi from './tabs/Cpi';
import Galery from './tabs/Galery';
import Contact from './tabs/Contact';
import CpiSales from './tabs/CpiSales';
import Newsfeed from './tabs/Newsfeed';
import NewsfeedInt from './tabs/NewsfeedInt';
import { StackNavigator } from "react-navigation";
import { createStackNavigator, createAppContainer } from "react-navigation-stack";
import allStyles from './css/allStylesCSS.js';

// const MenuNav = StackNavigator(
const MenuNav = createStackNavigator(
  {
    Cpi: { screen: Cpi },
    Galery: { screen: Galery },
    Contact: { screen: Contact },
    CpiSales: { screen: CpiSales },
    Newsfeed: { screen: Newsfeed },
    NewsfeedInt: { screen: NewsfeedInt },
  },
  {
    initialRouteName: 'Cpi',
    headerMode: 'none',
  }
);

// export default MenuNav;
export default createAppContainer(MenuNav);
`

Warnings being displayed:
Error Actual

Require cycle: tabs/Menu.js -> tabs/Galery.js -> tabs/Menu.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
- node_modules/expo/build/environment/muteWarnings.fx.js:17:23 in warn
- node_modules/metro/src/lib/polyfills/require.js:115:8 in metroRequire
* tabs/Galery.js:8:0 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:331:6 in loadModuleImplementation
* tabs/Menu.js:7:0 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:331:6 in loadModuleImplementation
* App.js:3:0 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:331:6 in loadModuleImplementation
- node_modules/expo/AppEntry.js:4:0 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:331:6 in loadModuleImplementation
- node_modules/metro/src/lib/polyfills/require.js:197:45 in guardedLoadModule
* null:null in global code

Accessing view manager configs directly off UIManager via UIManager['getConstants'] is no longer supported. Use UIManager.getViewManagerConfig('getConstants') instead.
- node_modules/expo/build/environment/muteWarnings.fx.js:17:23 in warn
- node_modules/react-native/Libraries/ReactNative/UIManager.js:164:12 in get
- node_modules/react-native/Libraries/Utilities/defineLazyObjectProperty.js:42:18 in getValue
- node_modules/react-native-gesture-handler/createHandler.js:39:2 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:331:6 in loadModuleImplementation
- node_modules/react-native-gesture-handler/NativeViewGestureHandler.js:3:0 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:331:6 in loadModuleImplementation
- node_modules/react-native-gesture-handler/createNativeWrapper.js:3:0 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:331:6 in loadModuleImplementation
- node_modules/react-native-gesture-handler/GestureHandler.js:1:0 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:331:6 in loadModuleImplementation
- node_modules/react-native-gesture-handler/Swipeable.js:10:0 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:331:6 in loadModuleImplementation
- node_modules/react-native-gesture-handler/index.js:1:0 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:331:6 in loadModuleImplementation
- node_modules/react-navigation-stack/lib/module/views/StackView/StackViewLayout.js:1:1762 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:331:6 in loadModuleImplementation
- node_modules/react-navigation-stack/lib/module/views/StackView/StackView.js:1:1417 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:331:6 in loadModuleImplementation
- node_modules/react-navigation-stack/lib/module/navigators/createStackNavigator.js:1:166 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:331:6 in loadModuleImplementation
- node_modules/react-navigation-stack/lib/module/index.js:1:35 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:331:6 in loadModuleImplementation
* App.js:11:0 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:331:6 in loadModuleImplementation
- node_modules/expo/AppEntry.js:4:0 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:331:6 in loadModuleImplementation
- node_modules/metro/src/lib/polyfills/require.js:197:45 in guardedLoadModule
* null:null in global codeRequire cycle: tabs/Menu.js -> tabs/Galery.js -> tabs/Menu.js

**Comment by elzasimoes** [comment]
> @sheixt You probably figured this out but just in case, I just had to
> `import { createAppContainer } from 'react-navigation';`
> `import { createStackNavigator} from 'react-navigation-stack';`

Resolving this in 2020.. Thanks

**Comment by BestSilverTiger** [comment]
@cassiern 
Thank you so much., 👍 💯 🥇
