### ISSUE TITLE
Expose transition state to be able to run custom animations

### ISSUE THREAD

**Issue by chrfalch** [react-navigation/react-navigation#7122]
## Background 

When building custom transitions like shared element transitions and appear/disappear animations for individual components we want to be able to change the current transition animations implemented in `react-navigation-stack`. 

## Requirements

What we want is:

1. A way to configure the stack to animate using a simple fade transition between screens
2. Get access to the state driving the animation

I think that it should be possible to accomplish configuring the stack, so this is probably already in place.

If we get access to the Animated.Values driving the transition (position, index, gestures etc) we should be able to build our own node trees describing our own animations.

## Suggested implementation

It looks like the `Card` component already has the transition state declared as private class members. Transitions/animations are built using these values and it should be possible to encapsulate this and expose it to the outside. This way we should be able to meet our requirements.

**Comment by Zurdge** [comment]
@chrfalch 
This topic mirrors what I'm trying to achieve slightly in my project.
I'm running v5 and am want to access the transition.progress to animate components in my screens.
I'm digging around to find a solution but was wondering if you had any pointers?

**Comment by chrfalch** [comment]
Nope, it was easy to get access to this. Here is a short snippet showing what I did in my screen wrapper:

```js
const stackCardAnimationContext = useContext(StackCardAnimationContext);
const progressValue = stackCardAnimationContext.next
      ? stackCardAnimationContext.next.progress
      : stackCardAnimationContext.current.progress;
```

You should be able to interpolate on the progressValue which will be available when you are in a navigation transition.

**Comment by Zurdge** [comment]
@chrfalch You're a superstar! ⭐ 
Thank you it's working perfectly.
