### ISSUE TITLE
ScrollViews conflict with the swipe back gesture on iOS 

### ISSUE THREAD

**Issue by aarondail** [react-navigation/react-navigation#7132]
This is pretty similar to https://github.com/react-navigation/stack/issues/127 but its not related to a Modal so I thought it might deserve its own issue.

Basically put a ScrollView on a screen, and try to swipe back on iOS diagonally (which is very common).  Very frequently the ScrollView "takes" the gesture instead of the stack navigator and so instead of swiping back you end up scrolling.

Compared to a native app, the swipe back gesture takes precedence and is much easier to trigger.

I can fix this by wrapping my ScrollView like this:
```
import { NativeViewGestureHandler } from 'react-native-gesture-handler';
import { StackGestureContext } from 'react-navigation-stack';
...
 <StackGestureContext.Consumer>
          {(ref: any) => (
            <NativeViewGestureHandler waitFor={ref}>
                <ScrollView>...</ScrollView>
            </NativeViewGestureHandler>
          )}
 </StackGestureContext.Consumer>    
```

But I feel like this should be handled in the library itself.

https://github.com/react-navigation/stack/issues/137 is also probably caused by this.

**Comment by vi07** [comment]
> NativeViewGestureHandler

Thank you so much for this solution!! I was looking for this from 4 days!
