### ISSUE TITLE
Full web support on v2+

### ISSUE THREAD

**Issue by brunolemos** [react-navigation/react-navigation#7142]
I'd love to use this new version by @satya164 on my projects but they are mostly universal projects that use react-native-web. Is that planned?

I see v2 is using `react-native-gesture-handler` and `react-native-reanimated`, they don't have web support yet (https://github.com/kmagiera/react-native-gesture-handler/issues/581, https://github.com/kmagiera/react-native-reanimated/issues/169).

@EvanBacon [made gesture handler work in the web](https://twitter.com/Baconbrix/status/1141240199407517696?s=20), so maybe we could use that? (pinged him [here](https://github.com/kmagiera/react-native-gesture-handler/issues/581#issuecomment-504773788)).

**Comment by nandorojo** [comment]
If it helps, I made [`expo-next-react-navigation`](https://github.com/nandorojo/expo-next-react-navigation) to support expo's `next` integration with `react-navigation` with the help of @EvanBacon.

You use the same API as `react-navigation`, but while on web, it uses next router.
