### ISSUE TITLE
Customize Header Background Image

### ISSUE THREAD

**Issue by rickardinho** [react-navigation/react-navigation#716]
I am using React-Navigation for routing in a React Native app and was wondering how I can show a background image in the header as opposed to a background color.   For a colour I can use the header object on NavigationOptions, but how can I nest an image in here?

**Comment by RobertSheaO** [comment]
React-Navigation doesn't support this, as you have to wrap your content in an `<Image>` tag to accomplish this, thus, you'll probably need a complete custom header component to accomplish this.

**Comment by rickardinho** [comment]
Do you have an example of how to do this? I'm finding the docs difficult to follow.

Thanks

**Comment by cstoddart** [comment]
I also would like to know how to add a header background image.

**Comment by DjangoGG** [comment]
+1

**Comment by 23tux** [comment]
I'd also like to see an example of a custom header +1

**Comment by koenpunt** [comment]
Creating a custom header with an image is actually really simple.

By wrapping the Header with a view and placing an absolute positioned image in that view, the image will scale to its parent size.

Important is to set the `backgroundColor` of the default header to `transparent`.

```jsx
const ImageHeader = props => (
  <View style={{ backgroundColor: '#eee' }}>
    <Image
      style={StyleSheet.absoluteFill}
      source={{ url: 'https://upload.wikimedia.org/wikipedia/commons/3/36/Hopetoun_falls.jpg' }}
    />
    <Header {...props} style={{ backgroundColor: 'transparent' }}/>
  </View>
);
```

And then use that component as header:

```jsx
const SimpleStack = StackNavigator({
  Home: {
    screen: MyHomeScreen,
  },
}, {
  navigationOptions: {
    headerTitleStyle: { color: '#fff' },
    header: (props) => <ImageHeader {...props} />,
  }
});
```

Which would result in:

<img src="https://cloud.githubusercontent.com/assets/351038/26284024/68d8e8cc-3e32-11e7-85c6-48c27a806f00.png" width="300" />

**Comment by bondanherumurti** [comment]
i tried it, it works however if i integrate with drawer, whenever the drawer opened, it seems the original header showed up

**Comment by bondanherumurti** [comment]
`const Header = props => (
  <View style={{justifyContent: 'flex-end'}}>
    <Text style={{fontFamily: 'dosis-bold', color: 'white', fontSize: 25}}>TAXPEDIA</Text>
  </View>
);

const ImageHeader = props => {
  console.log('ImageHeader props', props);
  return(
    <View style={{height: 10*vh, justifyContent: 'flex-end', padding: 5, backgroundColor: 'transparent'}}>
      <Image
        style={{width, height: 10*vh, position: 'absolute', top: 0, left: 0}}
        source={require('./assets/images/bg-header.png')}
        resizeMode="cover"
      />
      <Header {...props} style={{ backgroundColor: 'transparent' }}/>
    </View>
  );
}`

` Home: {
      screen: Home,
      navigationOptions: {
        header: props => <ImageHeader {...props} />,
        title: 'Welcome',
        headerRight: <View><Text>Test</Text></View>
      }`

This is my header it seems the tittle and headerRight is not working when i put custom header

**Comment by koenpunt** [comment]
Try removing the styles from the container view in the ImageHeader and see if it works then.

**Comment by petersuwara** [comment]
Can anyone advise on how to simple replace the headerTitle text with an Image. For us there is no need to fully replace the entire header, we just want to add an image instead of a title text for the header.

Thanks.

**Comment by koenpunt** [comment]
You can supply a React component as `headerTitle` which should do the trick.

See this issue for a bit more info; https://github.com/react-community/react-navigation/issues/1302

**Comment by florinpop17** [comment]
@koenpunt How does your Header component look like? Do we need to create a custom Header component ourself or we could somehow get the header component react-navigation uses?

**Comment by nasmuris** [comment]
Is there a way to have image in header and header to be partly transparent?

**Comment by angryBearLX** [comment]
@koenpunt  thanks for your solution. But it is not work at V1.0.0-beta.19. Then I add a headerStyle to resolve it.
Like this:
`const SimpleStack = StackNavigator({
    Home: {
        screen: MyHomeScreen,
    },
}, {
    navigationOptions: {
        headerTitleStyle: { color: '#fff' },
        header: (props) => <ImageHeader {...props} />,
        headerStyle: {
            backgroundColor: 'transparent'
        }
    }
});`

**Comment by angryBearLX** [comment]
@koenpunt Thank your for your solution. But it's not work well at V1.0.0-beta.19. 
I add a headerStyle to resolve it.
like this:
![1510127668251](https://user-images.githubusercontent.com/5259446/32537325-29d4ee90-c49d-11e7-99d1-960e038aace2.jpg)

**Comment by lfdantoni** [comment]
Hi @angryBearLX , I have the same problem, do you find a solution for that? 
Thanks

**Comment by fahadhaq** [comment]
cant seem to get header working. Getting an error. React is not defined. header.  @angryBearLX did you solve your issue?

**Comment by fahadhaq** [comment]
I have added a component named ImageHeader.Js

here is the code 

```
import React, { Component } from 'react'
import PropTypes from 'prop-types'
import {
  AppRegistry,
  StyleSheet,
  Text,
  Image,
  Button,
  Alert,
  TouchableHighlight,
  View,
  ScrollView,
  Header
} from 'react-native'

const ImageHeader = props => (
  <View style={{ backgroundColor: '#eee' }}>
    <Image
      style={StyleSheet.absoluteFill}
      source={{ uri: 'https://upload.wikimedia.org/wikipedia/commons/3/36/Hopetoun_falls.jpg' }}
    />
    <Header {...props} style={{ backgroundColor: 'transparent' }}/>
  </View>
);

export default class ImageTestHeader extends Component {
  constructor(props) {
    super(props)
  }
  
  render () {
    return (<ImageHeader />);
  }
}

```

But I am getting an error

<img width="376" alt="screen shot 2017-11-12 at 2 02 52 am" src="https://user-images.githubusercontent.com/2104888/32696952-f2315744-c7e9-11e7-91cd-f5082a8cac85.png">

Can some one please help. Not sure what I am doing wrong
Can some please help

**Comment by psyanite** [comment]
@angryBearLX You saved my life.

**Comment by fahadhaq** [comment]
I have the code working but it seems to only show me a black background. I cant see my left and right button. Also transparent doesnt seem to do anything. Here is my code

```
const Header = props => (
    <View style={{justifyContent: 'flex-end', backgroundColor: 'transparent'}}>
    </View>
  );

const ImageHeader = props => {
  return (
    <View style={{ height: 65 }}>
      <Image
        style={StyleSheet.absoluteFill}
        source={{ uri: 'https://upload.wikimedia.org/wikipedia/commons/3/36/Hopetoun_falls.jpg' }}
      />
      <Header {...props} style={{ backgroundColor: 'transparent' }}/>
    </View>
  )




const MyCardStack = StackNavigator({
  MyCardScreen: {
    screen: MyCardScreen,
    navigationOptions: ({ navigation }) => ({
      title: '',
      gesturesEnabled: false,
      header: (props) => <ImageHeader {...props} />,
      headerLeft: drawerButton(navigation),
      headerRight: myCardRightButton(navigation, 'MyCardScreen'),
      headerStyle: { backgroundColor: 'transparent' },
      transitionConfig: () => ({
        containerStyle: {
        },
      }),

    })
  }
}, {
    // Default config for all screens
    headerMode: 'float',
    navigationOptions: {
      headerTitleStyle: { color: '#fff' },
      // header: (props) => <ImageHeader {...props} />,
    }
  })
```

What am I doing wrong? I can see the image on the nav header but nothing else. please help

**Comment by brentvatne** [comment]
moved to website repo as this belongs in documentation: https://github.com/react-navigation/website/issues/8

**Comment by gwl002** [comment]
There is a prop named headerBackground can do the work.
`	LoginWithPincode:{
		screen: LoginWithPincodeScreen
	},
	Test:{
		screen: TestScreen
	},
  	Onboarding:{
    	screen: OnboardingScreen,
  	},
  	ActivationStack:{
  		screen: ActivationStack,
  		navigationOptions:{
  			header:null
  		}
  	}
},{	
	initialRouteName: "Onboarding",
	//initialRouteName: "VeryCode",
	mode:"card",
	navigationOptions:{
		headerStyle: {
			elevation: 0,
			backgroundColor: 'rgb(86,215,198)',
			...Platform.OS === "android"?{ paddingTop: StatusBar_HEIGHT+10,height: HEADER_HEIGHT}:{},
		},
		headerTintColor: '#fff',
		headerTitleStyle:{
			textAlign: 'center',
			flex:1,
			alignItems:'center',
			fontSize:18,
			fontWeight:'100'
		},
		headerBackground:<Image source={require("../../images/btn_header.png")} style={{resizeMode:"cover",height:HEADER_HEIGHT}} />
	}
	
})`
