### ISSUE TITLE
transparentCard: true doesn't work on Android

### ISSUE THREAD

**Issue by todorone** [react-navigation/react-navigation#7170]
It works perfectly on iOS, but on Android the screen under modal is just being hidden.
Reproduce: https://snack.expo.io/S1ZKx1VvV

**Comment by ospfranco** [comment]
Hi, I'm running into this issue on v4, is this fixed on v5?

**Comment by todorone** [comment]
@ospfranco Yes, it's fixed, it just being set up in another way...
