### ISSUE TITLE
set header default height on Android

### ISSUE THREAD

**Issue by sophister** [react-navigation/react-navigation#7178]
hi, according to [source code](https://github.com/react-navigation/react-navigation-stack/blob/master/src/views/StackView/StackViewLayout.js#L130), default header height is `56`, how can we change that default value? I've set `headerStyle` in `defaultNavigationOptions` to `72`, but When my page get rendered, `ReactNavigation` will use the default `56` as `paddingTop` of the `Card`, see [this line](https://github.com/react-navigation/react-navigation-stack/blob/master/src/views/StackView/StackViewLayout.js#L854). And then, header's `onLayout` callback [is called](https://github.com/react-navigation/react-navigation-stack/blob/master/src/views/StackView/StackViewLayout.js#L255). After this, another `render` executed and updating the `Card` `paddingTop` to `72`, which cause page content to move down `72 - 56` dp.

so, how can we change the default header height, it is hard coded as `56` on `Android`, according to [source code](https://github.com/react-navigation/react-navigation-stack/blob/master/src/views/StackView/StackViewLayout.js#L130)  :

```javascript
const getDefaultHeaderHeight = isLandscape => {
  if (Platform.OS === 'ios') {
    if (isLandscape && !Platform.isPad) {
      return 32;
    } else if (IS_IPHONE_X) {
      return 88;
    } else {
      return 64;
    }
  } else {
    return 56;
  }
};

this.state = {
      // Used when card's header is null and mode is float to make transition
      // between screens with headers and those without headers smooth.
      // This is not a great heuristic here. We don't know synchronously
      // on mount what the header height is so we have just used the most
      // common cases here.
      floatingHeaderHeight: getDefaultHeaderHeight(props.isLandscape),
 };
```

**Comment by snicro** [comment]
This should not be closed. It is very much still an issue in v5 as well.

**Comment by VolneiTonato** [comment]
https://github.com/react-navigation/react-navigation/issues/5936

screenOptions ={{safeAreaInsets: {top: 0},}}

**Comment by VolneiTonato** [comment]
@kamalpandey 

does it help you?

I put the Platform test on safeAreaInsets

```
const AppStackNavigation: React.FC = () => {
  const {signOut} = useAuth();

  const options = {
    headerShown: true,
    cardStyle: {backgroundColor: '#fff'},
    headerRight: () => (
      <ButtonLogout onPress={signOut}>
        <ButtonLogoutText>Sair</ButtonLogoutText>
      </ButtonLogout>
    ),
    headerStyle: {
      backgroundColor: '#696fDF',
      //height: 50,
    },
    safeAreaInsets: Platform.OS === 'android' ? {top: 0} : {},
    headerTintColor: '#fff',
    headerTitleStyle: {
      fontWeight: 'bold',
    },
    headerTransparent: false,
  };

  return (
    <Stack.Navigator screenOptions={options} initialRouteName="Home">
      <Stack.Screen
        options={{
          headerTitle: 'BusinessApp',
        }}
        name="Home"
        component={HomePage}
      />
      <Stack.Screen name="Pedidos" component={PedidosPage} />
      <Stack.Screen
        options={{title: 'Conferência de Pedidos'}}
        name="ConferenciaPedidos"
        component={ConferenciaPage}
      />
    </Stack.Navigator>
  );
};

export default AppStackNavigation;
