### ISSUE TITLE
React Native test with Jest - TypeError: Cannot read property 'BaseButton' of undefined

### ISSUE THREAD

**Issue by sidhijakpat** [react-navigation/react-navigation#7180]
I'm using react native with react navigation, and react navigation stack,

when trying to test using `npm test` with `jest`, I got this error message

```
Test suite failed to run

    TypeError: Cannot read property 'BaseButton' of undefined

      at Object.BaseButton (node_modules/react-navigation-stack/dist/views/BorderlessButton.js:6:61)
      at Object.<anonymous> (node_modules/react-navigation-stack/dist/views/TouchableItem.js:13:1)
      at Object.<anonymous> (node_modules/react-navigation-stack/dist/views/Header/HeaderBackButton.js:4:1)
```

here is my package.json dependencies:
```
"dependencies": {
    ...
    "native-base": "^2.8.1",
    "react": "^16.6.3",
    "react-native": "^0.57.5",
    "react-navigation": "^3.0.1",
    "react-navigation-stack": "^1.0.2",
    "react-redux": "^5.1.1",
    "redux": "^4.0.1",
    ...
  },
  "devDependencies": {
    ...
    "@babel/core": "^7.1.6",
    "babel-jest": "^23.6.0",
    "babel-preset-react-native": "^4.0.1",
    "jest": "^23.6.0",
    "metro-react-native-babel-preset": "^0.49.2",
    "react-test-renderer": "^16.6.3",
    ...
  },
  "jest": {
    "preset": "react-native",
    "transformIgnorePatterns": [
      "/node_modules/(?!native-base)/"
    ]
  }
```

what did I do wrong?

Any help will be appreciate

Thank you

**Comment by EgorenkoRusKS** [comment]
> You have to mock it. The above doesn't work as it's missing a return statement.
> This is a working version:
> `jest.mock('react-navigation-stack', () => { return {Header: ()=>'whatever'} });`
> 
> This is ES6 syntax, as `()=>'something'` is shorthand for `()=>{ return 'something' } `.

It`s really working

**Comment by kopax-polyconseil** [comment]
How about with version 5 ? I still got this error, I don't want to mock the whole navigation.
```
 FAIL   @pass-culture/id-check  src/components/pages/Confirmation/tests/AccountCreated.test.tsx
  ● Test suite failed to run

    TypeError: Cannot read property 'BaseButton' of undefined

      at Object.<anonymous> (../../node_modules/@react-navigation/stack/lib/commonjs/views/TouchableItem.ios.tsx:5:1)
      at Object.<anonymous> (../../node_modules/@react-navigation/stack/lib/commonjs/views/Header/HeaderBackButton.tsx:13:1)
```

Any clue? And thanks!

**Comment by gabrielgrover** [comment]
> How about with version 5 ? I still got this error, I don't want to mock the whole navigation.
> 
> ```
>  FAIL   @pass-culture/id-check  src/components/pages/Confirmation/tests/AccountCreated.test.tsx
>   ● Test suite failed to run
> 
>     TypeError: Cannot read property 'BaseButton' of undefined
> 
>       at Object.<anonymous> (../../node_modules/@react-navigation/stack/lib/commonjs/views/TouchableItem.ios.tsx:5:1)
>       at Object.<anonymous> (../../node_modules/@react-navigation/stack/lib/commonjs/views/Header/HeaderBackButton.tsx:13:1)
> ```
> 
> Any clue? And thanks!

I am getting the same exact error.  Not sure if the mocks provided by  [https://docs.swmansion.com/react-native-gesture-handler/docs/#testing](react-native-gesture-handler) are broken or what
