### ISSUE TITLE
Swipe back gesture iOS seems to lose its momentum, causing 'stuttery' effect

### ISSUE THREAD

**Issue by SasjaVDD** [react-navigation/react-navigation#7184]
Compared to a native swipe back gesture in native applications, the gesture in react-navigation seems to 'stutter'.

The 'goBack()' navigation, when triggered onPress, works like a charm. The stutter is not visible when using slower and longer swipe gesture. It is however quite noticeable when swiping back fast. 

After digging in the code, I'm not entirely sure if this is a bug or expected behaviour. See the code I attached. It seems that by setting the position value the momentum is bound to be lost thus rendering giving Spring a 'velocity' value useless.

https://github.com/react-navigation/react-navigation-stack/blob/680dc515ada3636294ea208d080f59d0c6552ca9/src/views/StackView/StackViewLayout.js#L561-L562

https://github.com/react-navigation/react-navigation-stack/blob/680dc515ada3636294ea208d080f59d0c6552ca9/src/views/StackView/StackViewLayout.js#L221-L240

(In my case) only reproducible on physical devices, tested on Iphone 8 and 5s. Snack: [https://snack.expo.io/@sasjav/react-navigation-swipe-lag](url)

| software         | version
| ---------------- | -------
| react-navigation | v3.0.0
| react             | 16.5.0
| Expo     | 31.0.4
| react-native-gesture-handler | 1.0.9

Not to be confused with issue react-navigation/stack#19

If the comment about implementing reanimated anticipated or implied this, then please close this issue.

https://github.com/react-navigation/react-navigation-stack/blob/680dc515ada3636294ea208d080f59d0c6552ca9/src/views/StackView/StackViewLayout.js#L360-L361

**Comment by vi07** [comment]
This issue still persists in version 5.

**Comment by vi07** [comment]
This issue still persists in version 5.
