### ISSUE TITLE
White flickering when switching screens

### ISSUE THREAD

**Issue by rodperottoni** [react-navigation/react-navigation#7221]
**Current Behavior**

Whenever I switch between different navigators in a **AnimatedSwitchNavigator** I can see a white flicker on the left of my screen.

Video: [flickering.mov.zip](https://github.com/react-navigation/animated-switch/files/4059255/flickering.mov.zip)

**Expected Behavior**

No white flickering.

**How to reproduce**

Will update this issue soon with a reproducible project.

**Your Environment**

| software                         | version |
| ----------------------- | ------- |
| iOS or Android               | iOS      |
| react-navigation            | 4.0.10
| react-navigation-animated-switch | 0.4.1
| react-native-reanimated          | 1.4.0
| react-native                     | 0.61.2

**Comment by jpshelley** [comment]
I commented out the shadow in the return statement here and the white vertical line issue is "fixed" for me now, so assuming its something with the shadows for sure https://github.com/react-navigation/react-navigation/blob/de5d985f3b1272d44175f1148c1b6cffc9a2650c/packages/stack/src/TransitionConfigs/CardStyleInterpolators.tsx#L62

**Comment by jpshelley** [comment]
xposting - think they are related
https://github.com/react-navigation/react-navigation/issues/7690#issuecomment-610492091

**Comment by satya164** [comment]
Closing since you didn't provide a repro. If you have a minimal repro, feel free to open an issue.
