### ISSUE TITLE
@react-navigation/core absolute file import path references .ts file

### ISSUE THREAD

**Issue by jwandrews** [react-navigation/react-navigation#7246]
**Current Behavior**

<img width="501" alt="image" src="https://user-images.githubusercontent.com/7916874/75181424-2a5a3380-570c-11ea-82e1-7bfa334cf211.png">

File link: [@react-navigation/core@3.6.0](https://github.com/react-navigation/react-navigation/blob/41e12725078e5a4adfc6fdf9623fb50660fa9045/packages/core/src/getNavigation.js#L1)

**Expected Behavior**

- should load app experience

**How to reproduce**

- update to latest react-navigation@4.2.0 (@react-navigation/core@3.6.0)

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | iOS |
| react-navigation               | 4.2.0 |
| react-navigation-stack         | 2.2.0 |
| react-navigation-tabs          | 2.8.0 |
| react-navigation-drawer        | 2.4.0 |
| react-native-reanimated        | 1.4.0 |
| react-native-gesture-handler   | 1.5.2 |
| react-native-safe-area-context | 0.6.0 |
| react-native-screens           | 2.0.0-alpha.12 |
| react-native                   | 0.61.4 |
| expo                           | 36.0.2 |
| node                           | 12.16.1 |
| npm or yarn                    | yarn |

**Comment by jwandrews** [comment]
https://github.com/react-navigation/react-navigation/blob/41e12725078e5a4adfc6fdf9623fb50660fa9045/packages/core/src/getNavigation.js#L1

**Comment by jasonbodily** [comment]
Same problem here. This came hot on the heels of fixing https://github.com/react-navigation/react-navigation/issues/7124

**Comment by jwandrews** [comment]
found another: https://github.com/react-navigation/react-navigation/blob/41e12725078e5a4adfc6fdf9623fb50660fa9045/packages/core/src/StateUtils.js#L1

**Comment by jasonbodily** [comment]
Encountered same ^, pardon the +1

**Comment by jwandrews** [comment]
more: https://github.com/react-navigation/react-navigation/blob/41e12725078e5a4adfc6fdf9623fb50660fa9045/packages/core/src/navigators/createNavigator.js#L2-L3

**Comment by jwandrews** [comment]
@satya164 i see the commit to fix the file extensions. thanks!!!

**Comment by kubilaytural** [comment]
Thanksssss
