### ISSUE TITLE
Custom headers are hanging on iOS when transitioning between screens

### ISSUE THREAD

**Issue by Rangoons** [react-navigation/react-navigation#7247]
https://snack.expo.io/@rangoons/237c5e
  its all in the snack, it only happens on iOS

In the snack, click 'Go to Details'
click the 'back' button that appears
it will hang on the home screen for a second, this does not happen on android and does not happen on iOS when using the built in headers

**Comment by satya164** [comment]
Please read the docs https://reactnavigation.org/docs/en/stack-navigator.html#header
