### ISSUE TITLE
Question: How can I change the title for each screen inside TabNavigator?

### ISSUE THREAD

**Issue by hakkikonu** [react-navigation/react-navigation#7248]
My stack navigator

```
<NavigationContainer>
    <Stack.Navigator>
       <Stack.Screen name="PageA" component={PageA} options={{title:'Page=A'}} />
       <Stack.Screen name="PageB" component={PageB} options={{title:'Page=B'}} />
       <Stack.Screen name="Menu" component={MenuTabNavigator} options={{title:'Menu'}} />
    </Stack.Navigator>
</NavigationContainer>
```
and my tab navigator

```
const MenuTabNavigator = () => {
  return (
    <Tab.Navigator>
      <Tab.Screen name="PageA" component={PageA} />
      <Tab.Screen name="PageB" component={PageB} />
      <Tab.Screen name="Menu" component={Menu} />
    </Tab.Navigator>
);};
```
I'm using Tab Navigator with Stack Navigator.

ScreenA, Screen B and Menu screen in my Tabs.

I pass MenuTabNavigator to StackNavigator's Menu Component as you can see.

Problem:

When I use tabs, header title stays 'Menu'.

For example when I touch to PageB on tab, i expect header title should be 'PageB' but it stays 'Menu'.

How can I change header title for screens when i use bottom tabs?

**Comment by RealDyllon** [comment]
Sorry if I'm missing the point, but why are you putting PageA and PageB in both navigators? Wouldn't you only want them in one?

**Comment by WoLewicki** [comment]
https://reactnavigation.org/docs/screen-options-resolution#setting-parent-screen-options-based-on-child-navigators-state. Is this what you need?

**Comment by DnEgorWeb** [comment]
@hakkikonu I think @WoLewicki gave exactly the right answer, so you can try it and close the issue.

**Comment by Andrei-Sager** [comment]
> https://reactnavigation.org/docs/screen-options-resolution#setting-parent-screen-options-based-on-child-navigators-state. Is this what you need?

Thanks a lot!!! 

This solved my problem. I am using a Tab navigation inside a Stack navigation in expo router.
