### ISSUE TITLE
tabBarOnpress not working

### ISSUE THREAD

**Issue by hudiohizari** [react-navigation/react-navigation#7249]
Sorry if this obvious mistake, i've searched anywhere but can't find a way to run my function on tab changed, i tried to add tabBarOnPress on Tab.Screen tag, but its not working too

```
import React, { useState, useEffect } from 'react'
import { createBottomTabNavigator } from '@react-navigation/bottom-tabs'
import { Ionicons } from '@expo/vector-icons'

import DashboardScreen from '../screens/DashboardScreen'
import ScanScreen from '../screens/ScanScreen'
import ProfileScreen from '../screens/ProfileScreen'

import Colors from '../utils/Colors'

const Tab = createBottomTabNavigator();

const TabNavigator = props => {
    const [focusedTab, setFocusedTab] = useState("Dashboard")

    useEffect(() => { 
        props.statusBarHanlder(focusedTab == "Dashboard" ? Colors.kolegaBlue2 : "white")
    })

    return (
        <Tab.Navigator
            lazy={true}
            screenOptions={({ route }) => ({
                tabBarIcon: ({ focused, color, size }) => {
                    let iconName;

                    if (route.name === "Dashboard") iconName = "ios-home"
                    else if (route.name === "Scan") iconName = "ios-qr-scanner"
                    else if (route.name === "Profile") iconName = "ios-person"

                    return ( <Ionicons name={iconName} size={size} color={color} />)
                },
                tabBarOnPress: ({ navigation }) => {
                    console.log("pressed")
                }
            })}
            tabBarOptions={{
                activeTintColor: Colors.kolegaBlue2,
                inactiveTintColor: Colors.darkGrey
            }}>
            
            <Tab.Screen name="Dashboard" component={DashboardScreen}/>
            <Tab.Screen name="Scan" component={ScanScreen} />
            <Tab.Screen name="Profile" component={ProfileScreen} />
        </Tab.Navigator>
    )
}

export default TabNavigator
```

**Comment by stephtea** [comment]
I experienced a similar issue. 

tabBarOnPress does not work on navigator screenOptions or on a screen's options. It looks like it's missing it in the type as well, even though according to https://reactnavigation.org/docs/2.x/bottom-tab-navigator/#tabbaronpress it should be there.

**Comment by stephtea** [comment]
looks like they moved it to hooks.

https://reactnavigation.org/docs/navigation-events

**Comment by hudiohizari** [comment]
> looks like they moved it to hooks.
> 
> https://reactnavigation.org/docs/navigation-events

i tried https://reactnavigation.org/docs/navigation-events/#navigationaddlistener and https://reactnavigation.org/docs/navigation-events/#listeners-prop-on-screen, still not working

**Comment by hudiohizari** [comment]
> > looks like they moved it to hooks.
> > https://reactnavigation.org/docs/navigation-events
> 
> i tried https://reactnavigation.org/docs/navigation-events/#navigationaddlistener and https://reactnavigation.org/docs/navigation-events/#listeners-prop-on-screen, still not working

Sorry i tried using "focus" instead "tabPress" on
```
const unsubscribe = navigation.addListener('tabPress', e => {
  // Prevent default action
  e.preventDefault();
});
```
It's working now, thanks

**Comment by hudiohizari** [comment]
> > looks like they moved it to hooks.
> > https://reactnavigation.org/docs/navigation-events
> 
> i tried https://reactnavigation.org/docs/navigation-events/#navigationaddlistener and https://reactnavigation.org/docs/navigation-events/#listeners-prop-on-screen, still not working

Sorry i tried adding this into screen js using "focus" instead "tabPress" on
```
const unsubscribe = navigation.addListener('tabPress', e => {
  // Prevent default action
  e.preventDefault();
});
```
It's working now but i need it to be listened by Tab.Navigation not on Tab.Screen, how can I do that?

**Comment by Aung-Myint-Thein** [comment]
Yes, I tried listener in the screen and it is working but I also want to have it on the tab navigator and tried 

```
listeners={{
                    tabPress: e => {
                        console.log("pressed")
                        e.preventDefault();
                    },
                }}
```
but not working.. :D Please let us know if you found a solution!

**Comment by hudiohizari** [comment]
> Yes, I tried listener in the screen and it is working but I also want to have it on the tab navigator and tried
> 
> ```
> listeners={{
>                     tabPress: e => {
>                         console.log("pressed")
>                         e.preventDefault();
>                     },
>                 }}
> ```
> 
> but not working.. :D Please let us know if you found a solution!

I still don't have any solution for this :(

**Comment by satya164** [comment]
Please upgrade your dependencies. If it's a bug, please fill the issue template when opening issues.

**Comment by dblazeski** [comment]
@hudiohizari you're looking for the tabPress event?
Try adding the listener in your screen with dangerouslyGetParent:

```
if (navigation.dangerouslyGetParent()) {
	navigation.dangerouslyGetParent().addListener('tabPress', this.tapOnTabNavigator)
}
```

**Comment by winseyli** [comment]
> Yes, I tried listener in the screen and it is working but I also want to have it on the tab navigator and tried
> 
> ```
> listeners={{
>                     tabPress: e => {
>                         console.log("pressed")
>                         e.preventDefault();
>                     },
>                 }}
> ```
> 
> but not working.. :D Please let us know if you found a solution!

same, `listeners` doesn't work

**Comment by sunil-bhagat** [comment]
> > Yes, I tried listener in the screen and it is working but I also want to have it on the tab navigator and tried
> > ```
> > listeners={{
> >                     tabPress: e => {
> >                         console.log("pressed")
> >                         e.preventDefault();
> >                     },
> >                 }}
> > ```
> > 
> > 
> > but not working.. :D Please let us know if you found a solution!
> 
> same, `listeners` doesn't work
> 
> UPDATE: it works after I upgraded to latest dependences.

which dependency you updated?

**Comment by sunil-bhagat** [comment]
`<Tabs.Screen
  name="Chat"
  component={Chat}
  listeners={({ navigation, route }) => ({
    tabPress: e => {
      // Prevent default action
      e.preventDefault();

      // Do something with the `navigation` object
      navigation.navigate('AnotherPlace');
    },
  })}
/>`
 while using callback its not working

**Comment by hackrx** [comment]
> @Osamasomy you're looking for the tabPress event?
> Try adding the listener in your screen with dangerouslyGetParent:
> 
> ```
> if (navigation.dangerouslyGetParent()) {
> 	navigation.dangerouslyGetParent().addListener('tabPress', this.tapOnTabNavigator)
> }
> ```

Man, you saved my day, thanks.
