### ISSUE TITLE
Missing renderIndicator typing in MaterialTabbarOptions

### ISSUE THREAD

**Issue by philippeauriach** [react-navigation/react-navigation#7250]
**Current Behavior**

`renderIndicator` tabbar options works and is documented but no typings are available.

**Expected Behavior**

Neing able to use renderIndicator with typescript

**How to reproduce**

Following won't be validated by typescript : 
```
import { createMaterialTopTabNavigator } from 'react-navigation-tabs'
export const exploreTopTabNavigator = createMaterialTopTabNavigator(
  {
    TAB_A: {
      screen: ScreenA
    },
    TAB_B: {
      screen: ScreenB
    },
    },
  },
  {
    tabBarOptions: {
      // just a typing problem here
      renderIndicator: props => {
        return <View />
      },
    },
  },
)
```
**Your Environment**

| software                     | version |
| ---------------------------- | ------- |
| iOS or Android               | both
| react-navigation             | 4.1.1
| react-navigation-tabs        | 2.7.0
| react-native-reanimated      | 1.7.0
| react-native-gesture-handler | 1.5.3
| react-native-screens         | 2.0.0-alpha.32
| react-native                 | 0.61.5
| expo                         | 
| node                         | 12.14.0
| npm or yarn                  | 1.12.1

I tried a PR but could not find the correct typings that should probably come from `react-native-tab-view`

**Comment by pawsaw** [comment]
This one still exists. What's the status of this issue?

**Comment by kyawthura-gg** [comment]
Closing this as it seems to be resolved in latest version.
