### ISSUE TITLE
tabPress listener not working when wrapped in Stack.Navigator

### ISSUE THREAD

**Issue by dblazeski** [react-navigation/react-navigation#7252]
**Current Behavior**

The listener for `tabPress` event is not working when the screen component is an instance of Stack.Navigator. Works fine when the screen component is an instance of Stack.Screen.

**Expected Behavior**

The 'tabPress' listener to fire.

**How to reproduce**

Expo - https://snack.expo.io/@slusatel/react-navigation-tabpress
1st tab works fine with direct Stack.Screen component.
2nd tab fails - with Stack.Navigator component.

**Your Environment**

| software                     | version |
| ---------------------------- | ------- |
| Platform               | iOS
| react-navigation             | 5.0.3
| react-navigation-tabs        | 5.0.3
| react-native-reanimated      | 5.0.3
| react-native-gesture-handler | 5.0.3
| react-native-screens         | master
| react-native                 | latest
| expo                         |
| node                         | latest
| npm or yarn                  | latest

**Comment by dblazeski** [comment]
@satya164 just fixed this in https://github.com/react-navigation/react-navigation/commit/162410843c4f175ae107756de1c3af04d1d47aa7 🎉

On the Tab.Navigator -> Tab.Screens, listeners can be attached now with:
`listeners={{
    tabPress: e => console.log('Tab press', e.target),
}}`

Thank you!

**Comment by Osamasomy** [comment]
> @satya164 just fixed this in [1624108](https://github.com/react-navigation/react-navigation/commit/162410843c4f175ae107756de1c3af04d1d47aa7) 🎉
> 
> On the Tab.Navigator -> Tab.Screens, listeners can be attached now with:
> `listeners={{ tabPress: e => console.log('Tab press', e.target), }}`
> 
> Thank you!

can you please check issu in below link i have same issu right know and i am unable to solve it.
https://github.com/react-navigation/react-navigation/issues/7249

**Comment by Rooban19** [comment]
> @satya164 just fixed this in [1624108](https://github.com/react-navigation/react-navigation/commit/162410843c4f175ae107756de1c3af04d1d47aa7) 🎉
> 
> On the Tab.Navigator -> Tab.Screens, listeners can be attached now with:
> `listeners={{ tabPress: e => console.log('Tab press', e.target), }}`
> 
> Thank you!

Can u tell me, How to implement 'tabPress'event in the screen which is in stack navigator wrapped by tab navigator

**Comment by dotku** [comment]
> > @satya164 just fixed this in [1624108](https://github.com/react-navigation/react-navigation/commit/162410843c4f175ae107756de1c3af04d1d47aa7) 🎉
> > On the Tab.Navigator -> Tab.Screens, listeners can be attached now with:
> > `listeners={{ tabPress: e => console.log('Tab press', e.target), }}`
> > Thank you!
> 
> Can u tell me, How to implement 'tabPress'event in the screen which is in stack navigator wrapped by tab navigator
> @satya164 @ddedic

Here is the code you can refer to, but I don't see the listener is triggered. @satya164  
```
function PublishNavigator() {
  const navigation = useNavigation();
  return (
    <PublishStack.Navigator>
      <PublishStack.Screen
        name="PublishScreen"
        component={SpaceScreen}
        options={{ headerTitle: "Publish" }}
        listeners={{
          tabPress: (e) => {
            e.preventDefault();
            console.log("pressed");
          },
        }}
      />
    </PublishStack.Navigator>
  );
}```

**Comment by satya164** [comment]
> but I don't see the listener is triggered. @satya164

https://reactnavigation.org/docs/nesting-navigators/#nested-navigators-dont-receive-parents-events

**Comment by dotku** [comment]
> > but I don't see the listener is triggered. @satya164
> 
> https://reactnavigation.org/docs/nesting-navigators/#nested-navigators-dont-receive-parents-events

Cool, it works now. I realized that there is parent/child relationship on the tabNavigation, so I just add the event directly on the root of bottomTabNavigation and it works.

sample code as below

```
export default function BottomTabNavigator() {
  const colorScheme = useColorScheme();

  return (
    <BottomTab.Navigator
      initialRouteName="TabOne"
      tabBarOptions={{ activeTintColor: Colors[colorScheme].tint }}
    >
      <BottomTab.Screen
        name="TabOne"
        component={TabOneNavigator}
        options={{
          tabBarIcon: ({ color }) => (
            <TabBarIcon name="ios-code" color={color} />
          ),
        }}
      />
      <BottomTab.Screen
        name="TabTwo"
        component={() => null}
        listeners={{
          tabPress: (e) => {
            e.preventDefault();
            console.log("tabPress tabTwo");
          },
        }}
        options={{
          tabBarIcon: ({ color }) => (
            <TabBarIcon name="ios-code" color={color} />
          ),
        }}
      />
    </BottomTab.Navigator>
  );
}
```

**Comment by ckswopnera** [comment]
I cant find tab press in screenlistners and not even in listeners too 
![image](https://user-images.githubusercontent.com/73164259/190670153-2e7c375a-62ad-4ef1-96db-bab5ce6d3260.png)
Please help in this
