### ISSUE TITLE
Impossible to change page overflow to visible (hidden by default)

### ISSUE THREAD

**Issue by Gentlee** [react-navigation/react-navigation#7258]
**Current Behavior**

Page container overflow is hidden, and there is no way to change it.

**Expected Behavior**

I should decide if I need to hide it or not.

**How to reproduce**

Try ty set overflow to visible of your page, it won't work.

**Your Environment**

| software                     | version |
| ---------------------------- | ------- |
| react-navigation-tabs        | latest |

Problem is in style `container:{flex:1,overflow:'hidden'}` in `createBottomTabNavigator.js` file.

`overflow:'hidden'` should be removed.

**Comment by satya164** [comment]
I don't think `overflow: visible` is a solution. We need to expose tab bar height instead #7268
