### ISSUE TITLE
performance of MaterialTopTabNavigator is slow

### ISSUE THREAD

**Issue by kkorezelidis** [react-navigation/react-navigation#7259]
I have two tabs on my page and sometimes when you change the tabs quickly the selected state of the tab is not changing although you can see the correct content of the tab. For example let's say we have tab1 and tab2. If you click quickly between the two tabs many times and the last tab you clicked was tab2, you see the selected tab to be tab1 and you see the content of tab2. This is only happening on Android S7 edge, the same behaviour happens also if i have the accessibility mode enabled on the device. I think it's related with the following issues.

https://github.com/react-navigation/tabs/issues/210
https://github.com/react-navigation/tabs/issues/207

i can reproduce it even with the latest version

"react-native": "0.61.4",
"react-navigation-tabs": "2.7.0",
"react-navigation": "4.0.10",
"react-navigation-stack": "1.10.3",
"react-navigation-tabs": "2.7.0",

**Comment by satya164** [comment]
Closing since you didn't provide a repro. Feel free to open a new issue if you have a repro.
