### ISSUE TITLE
Android: Nested Stack Navigator's Screen(s) Not Rendered

### ISSUE THREAD

**Issue by 509dave16** [react-navigation/react-navigation#7260]
## Current Behavior
- What code are you running and what is happening?
  - Screen header and content are not rendered.
  - As a simplified example of the problem, here is a link to a Snack that has a Tab Navigator containing routes to nested Stack Navigators using React Navigation v4: https://snack.expo.io/@foodbarrio/react-navigation-test-bed
  - Here's also the snack referenced from the docs using v3 that does work: https://snack.expo.io/@react-navigation/stacks-in-tabs-v3
  - Here's a high level code snippet from my snack referenced above:
   ```javascript
  import * as React from 'react';
  import { Text, View } from 'react-native';
  import Constants from 'expo-constants';
  import { createStackNavigator } from 'react-navigation-stack'
  import { createBottomTabNavigator } from 'react-navigation-tabs'
  import { createAppContainer } from 'react-navigation'
  import { useScreens } from 'react-native-screens'
  useScreens()

  import ScreenA from './components/ScreenA'
  import ScreenB from './components/ScreenB'
  import ScreenC from './components/ScreenC'
  import ScreenD from './components/ScreenD'

  const Stack1 = createStackNavigator({ ScreenA, ScreenB}, { initialRouteName: 'ScreenA'})
  const Stack2 = createStackNavigator({ ScreenC, ScreenD}, { initialRouteName: 'ScreenC'})
  const App = createBottomTabNavigator({ Stack1, Stack2 }, { initialRouteName: 'Stack1' })
  export default createAppContainer(App)
   ```
- Include a screenshot or video if it makes sense.
  - **Android**: Not working as expected
    <img src="https://user-images.githubusercontent.com/2925882/72869564-8f98b000-3c9a-11ea-9f24-88b9513d98c8.png" height="450" width="225"  />

## Expected Behavior
- What do you expect should be happening?
  - Screen header and content should be rendered.
- Include a screenshot or video if it makes sense.
  - **iOS**: Working as expected
    <img src="https://user-images.githubusercontent.com/2925882/72869543-80196700-3c9a-11ea-876b-b98998eab41a.png" height="450" width="225" />

## How to reproduce
Nest a Stack Navigator instead of a Screen in a Tab Navigator. Notice on Android how nested Screens work fine. But not nested Navigators. The snack mentioned above reproduces the problem: https://snack.expo.io/@foodbarrio/react-navigation-test-bed

## Your Environment

| software                     | version |
| ---------------------------- | ------- |
| Android               | Oreo
| react-navigation             |  4.0.10
| react-navigation-tabs        | 2.7.0
| react-native-reanimated      | 1.2.0
| react-native-gesture-handler | 1.3.0
| react-native-screens         | 1.0.0-alpha.23
| react-native                 | 0.59.8
| expo                         | 35
| node                         | 12.3.1
| npm                  | 6.13.6

**Comment by Runtime-Err** [comment]
Same problem here with same versions as listed above

**Comment by satya164** [comment]
Closing since this shouldn't be an issue with latest version of screens.

**Comment by rubina-shakhkyan** [comment]
This issue is still present with the latest version of screens (`3.4.0`) and react-navigation 5.
Nested stack is rendered, but not the screens&screen headers.
