### ISSUE TITLE
iOS: Focus events not being called when navigating into tab stack then into another tab quickly

### ISSUE THREAD

**Issue by java-james** [react-navigation/react-navigation#7265]
**Current Behavior**

Using a stack navigator with a tabs screen and some other full screen - When navigating back from the full screen onto the tabs screen and pressing a tab QUICKLY navigation listeners are not executed.

For example a screen which is contained as a tab with the following:

```  
useEffect(() => {
    const didFocusListener = navigation.addListener("didFocus", handleFocusChanged(true));
    const didBlurListener = navigation.addListener("didBlur", handleFocusChanged(false));
    return () => {
      didFocusListener.remove();
      didBlurListener.remove();
    };
  }, [navigation]);
```

The didFocusListener is not called if the user pressed the tab fast enough after navigating back to the tabs screen and into the tab.

**Expected Behavior**

The listener is called

**How to reproduce**

**I apologise I don't have time to make the application for reproduction I will try make time as soon as I have time**

A stack navigator containing 1 bottom tab navigator (using createBottomTabNavigator) and one other screen as a react component.

Eg 
```
export const StackNavigator = createStackNavigator(
  {
    [Routes.MainTabs.routeName]: MainTabNavigator,
    [Routes.CameraPermission.routeName]: SomeOtherScreen,
  },
  {
    initialRouteName: Routes.MainTabs.routeName,
  }
);
```

MainTabNavigator:

```
export const MainTabNavigator = createBottomTabNavigator(
  {
    [Routes.ScreenOne.routeName]: ScreenOne,
    [Routes.ScreenTwo.routeName]: ScreenTwo,
    [Routes.ScreenThree.routeName]: ScreenThree,
  },
  {
    initialRouteName: Routes.ScreenOne.routeName,
  }
);
```

In ScreenOne add the following effects:

```  
useEffect(() => {
    const didFocusListener = navigation.addListener("didFocus", handleFocusChanged(true));
    const didBlurListener = navigation.addListener("didBlur", handleFocusChanged(false));
    return () => {
      didFocusListener.remove();
      didBlurListener.remove();
    };
  }, [navigation]);

  useEffect(() => {
    console.log("Running effect:" + Math.random());
  }, [isFocused, navigation]);
```

Navigate from SomeOtherScreen to ScreenTwo, as quickly as possible tap the tab for ScreenOne.

Observe no console log. 

**Your Environment**

| software                     | version |
| ---------------------------- | ------- |
| iOS           | 13.3
| react-navigation             | 4.0.10
| react-navigation-tabs        | 2.5.6
| react-native                 | 0.61.4
| node                         | 10.16.3
| yarn                  | 1.17.3

**Comment by satya164** [comment]
#4867
