### ISSUE TITLE
[createMaterialTopTabNavigator] Has crashed the app on a real device Android with swipe enabled option is true

### ISSUE THREAD

**Issue by vothanhhungit** [react-navigation/react-navigation#7278]
Environment
OS: macOS High Sierra v10.13

Packages: (installed)
"react-navigation": "^4.0.4",
"react-navigation-tabs": "^2.5.6"
"react-native": 0.61.3

Actual Behavior
I build apk release and running app crash when using createMaterialTopTabNavigator (was just crashed on a real device Android)
Note: when I was using createMaterialBottomTabNavigator (from 'react-navigation-material-bottom-tabs') to instead of or **setting swipeEnabled is false** then it works fine.
Here is the content of my component :

> import React from 'react';
> import {
>   Text,
>   SafeAreaView
> } from 'react-native';
> import { createMaterialTopTabNavigator, MaterialTopTabBar } from 'react-navigation-tabs';
> // import { createMaterialBottomTabNavigator } from 'react-navigation-material-bottom-tabs';
> 

> /* Components */
> ....
> 
> const RootTabNavigator = createMaterialTopTabNavigator(
>   {
>     Pending: PendingJobsComponent,
>     ...
>   },
>   {
>     
>     lazy: true,
>     
>     tabBarOptions: {
>       activeTintColor: "#000000",
>       inactiveTintColor: "#000000",
>       // scrollEnabled: true,
>       tabStyle: {
>         // width: 95,
>       },
>       style: {
>         backgroundColor: '#ffffff',
>         fontSize: 12,
>         shadowColor: 'transparent',
>       },
>       labelStyle: {
>         fontSize: 12,
>       },
>       indicatorStyle: {
>         borderBottomColor: '#000000',
>         borderBottomWidth: 2,
>         backgroundColor: 'transparent'
>       },
>       upperCaseLabel: false
>     },
>     
>   }
> 
> export default RootTabNavigator;

Plz! help me find out the solution to fix this issue! Many Thanks!

**Comment by RatebSeirawan** [comment]
Same here also when debugging getting an error related to react-native-reanimated when I swipe on tabs.
Value of node com.swmansion.reanimated.nodes.valueNode@e442dba cannot be cast to a number
