### ISSUE TITLE
the performance of MaterialTopTabNavigator is slow

### ISSUE THREAD

**Issue by LeeMoonki** [react-navigation/react-navigation#7280]
### Current Behavior

(I only test all in adroid.)

![sample_video](https://user-images.githubusercontent.com/20311378/66249308-2b45f500-e76c-11e9-9d88-42614c92596f.gif)

I faced the performance issue of MaterialTopTabNavigator. And I found that the performance issue is came from itself not from its screen rendering performance or others.

When I just replace the `MaterialTopTabNavigator` with `BottomTabNavigator`, there is no performance issue anymore. i.e, the `BottomTabNavigator` has same screen as `MaterialTopTabNavigator` but much faster than it.

Additionally, when I use `MaterialTopTabNavigator` the screen is rendered very slowly. Also, when I use `BottomTabNavigator` the speed of rendering of screen is very fast.

Lastly, the speed is also differed between virtual device and real device. In virtual device the rendering speed is slower than real device but the navigator is work better in the virtual device. (In virtual device, if I press the tab, the animation and rendering screen is slow but act right after. But in real device, if I press the tab, after few seconds the animation and rendering screen is triggered)

Why the difference is occurred ?

The following is my code. 

```
import React from 'react';
import {View, Text, StyleSheet} from 'react-native';
import {createMaterialTopTabNavigator} from 'react-navigation-tabs';

import {GROUPS} from '../../../config';
import navStyle, {labelStyle} from '../../../styles/memberNavigator';

import MainScreen from '../../../screens/feed/MainScr';

const group = GROUPS.groupA;
const styles = StyleSheet.create(navStyle);
const lstyles = StyleSheet.create(labelStyle);

class TabBarLabel extends React.Component {
  static lastFocused = null;
  constructor(props) {
    super(props);
  }
  render() {
    return this.props.focused ? (
      <View style={lstyles.container_focused}>
        <Text style={lstyles.label_focused}>{this.props.name}</Text>
      </View>
    ) : (
      <View style={lstyles.container_blur}>
        <Text style={lstyles.label_blur}>{this.props.name}</Text>
      </View>
    );
  }
}

const memberNavigationConfig = (function() {
  const result = {};

  for (const member of group.members) {
    result[member.id] = {
      screen: MainScreen,
      navigationOptions: function({navigation}) {
        return {
          title: member.name,
          tabBarLabel({focused, horizontal, tintColor}) {
            return <TabBarLabel focused={focused} name={member.name} />;
          },
          tabBarOnPress(payload) {
            console.log('tabBarOnPress : ', member.name);
            payload.navigation.setParams({group: group, member: member});
            payload.defaultHandler();
          },
        };
      },
    };
  }

  return result;
})();

const FeedAGroupMemberNavigator = createMaterialTopTabNavigator(
  {
    ...memberNavigationConfig,
  },
  {
    initialRouteName: group.members[0].id,
    swipeEnabled: false,
    tabBarOptions: {
      scrollEnabled: true,
      ...styles,
    },
  },
);

export default FeedAGroupMemberNavigator;

```

And I already update all related packages.

### Expected Behavior

- rendering screens and animation of tab is fast like other navigators.

### How to reproduce

- I run above code under environment written below.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.12.1
| react-navigation-tabs      | 2.5.5
| react-native-tab-view      | 2.10.0
| react-native     | 0.60.5
| node             | 10.13.0
| npm or yarn      | 6.4.1

**Comment by uxdw** [comment]
Still an issue for me  but only on TabNavigator, it's selectively non-responsive or incredibly slow.

@react-navigation/bottom-tabs": "^5.2.6

**Comment by johnrayguerracoinpass** [comment]
Having the same issue with @uxdw. do you see any solutions for the issue?

**Comment by ErkinKurt** [comment]
I have the same issue...

**Comment by nassim99** [comment]
same here very bad performance it even freezes my entire operating system (win10) not just emulator.

    "@react-navigation/bottom-tabs": "^5.7.3",
    "@react-navigation/material-top-tabs": "^5.2.16",
    "@react-navigation/native": "^5.7.2",
    "@react-navigation/stack": "^5.8.0",

**Comment by andrconstruction** [comment]
The problem still here

**Comment by topheroes** [comment]
having the same issue.
@andrconstruction , @nassim99 did you solve the problem?

**Comment by topheroes** [comment]
@LeeMoonki , @sgr-fr What did you do to solve the problem?

**Comment by sgr-fr** [comment]
I can't, we just decided to use another component... Sorry 
PS but it's in 2019, I haven't retry recently

**Comment by karamsetty09** [comment]
Issue still exists, Taking too long to display the tabScreen.

**Comment by jafar-jabr** [comment]
same here v6.5.2

**Comment by martinrombach88** [comment]
Issue happening still.

**Comment by kitolog** [comment]
Do you know if there is any workaround there? 
The swipe works pretty well, pressing on the tab freezes for a few seconds on iOS and Android

**Comment by MarkHeijnekamp-Atermes** [comment]
I am experiencing the same issue on the latest version 7.3.2, has anyone figured out a method to resolve this issue?
