### ISSUE TITLE
After hidden bottom tab bar by open keyboard remains white block

### ISSUE THREAD

**Issue by fri0z** [react-navigation/react-navigation#7284]
### Current behaviour
After hidden bottom tab bar by open keyboard remains white block. I use mode `android:windowSoftInputMode="adjustResize"` and `adjustResize` fits most to me. I tried other modes and not fits me.

### Expected behaviour

I expect to hide the white bar in adjustResize mode

### Code sample

```
import React from 'react';
import { Input } from "react-native-elements";
import { View, ScrollView } from 'react-native';

class Example extends React.Component {
    render() {
        return (
            <View style={ { backgroundColor: '#ccc', flex: 1 } }>
                <ScrollView>
                    <Input
                        label={ 'Серия бланка' }
                        placeholder='Серия бланка'
                    />
                </ScrollView>
            </View>
        );
    }
}
```

### Screenshots (if applicable)

![photo_2019-10-24_20-37-34](https://user-images.githubusercontent.com/1527987/67505173-34a7ea80-f6a4-11e9-9f61-e619828d6596.jpg)

### What have you tried
I watched react-navigation/tabs#16 / react-navigation/tabs#64 

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | android
| react-native          | 0.60.5
| react-navigation-tabs | 4.0.10
| react-navigation-stack | 1.10.2
| react-navigation-tabs | 2.5.6
| node                  | v10.17.0
| npm or yarn           | 6.11.3

**Comment by barak109** [comment]
I upgrade and it's still happen to me..

**Comment by yarin177** [comment]
same here still looking for a fix...
