### ISSUE TITLE
Navigation Tab partly covered (Android, Oreo)

### ISSUE THREAD

**Issue by WillVill** [react-navigation/react-navigation#7288]
On devices using Android Oreo part of the Navigation Tab is being covered. Happening on Google Pixel, Nexus and Samsung devices.

I have these styles for the labels and icons:
const styles = StyleSheet.create({
  tabBarIconActive: {
    width: 22,
    height: 22,
    resizeMode: 'contain',
    marginTop: 5
  },
  tabBarIconInactive: {
    width: 22,
    height: 22,
    resizeMode: 'contain',
    marginTop: 5
  },
  textActive: {
    fontSize: 10,
    fontFamily: fonts.AVENIR.HEAVY,
    textAlign: 'center',
    marginBottom: 12
  },
  textInactive: {
    fontSize: 10,
    fontFamily: fonts.AVENIR.DEFAULT,
    textAlign: 'center',
    marginBottom: 12
  }
})

and this as tab bar options:

  
tabBarOptions: {
   activeTintColor: 'black',
   inactiveTintColor: 'black',
   showLabel: true,
   showIcon: true,
   style: {
      height: 65
   }
}
    
How it looks on newer Android versions + IOS:

![Screenshot 2019-10-21 at 16 50 35](https://user-images.githubusercontent.com/9032463/67216132-f6e85f00-f422-11e9-9d63-dde8dac6619f.png)

How it shouldn't look, but does, on Android Oreo. I'm not 100% sure if it is only because of the Android version or if it generally happens in older devices. Or if it's my styling. I have attempted to remove the styles but there was no success.

![Screenshot 2019-10-21 at 16 50 19](https://user-images.githubusercontent.com/9032463/67216137-f94ab900-f422-11e9-9057-15486b60b7db.png)

Thanks in advance!

| software              | version
| --------------------- | -------
| android                       | Oreo
| react-native               | 0.60.4
| react-navigation-tabs | 1.2.0
| node                          | 12.0.0
| npm                          | 6.10.2

**Comment by satya164** [comment]
#7253
