### ISSUE TITLE
Getting Invariant Violation: Native Module cannot be null after installing dependencies

### ISSUE THREAD

**Issue by parthpatel20010** [react-navigation/react-navigation#7291]
### Current behaviour

After installing react-native-reanimated, I get an "Invariant violation: Native module cannot be null" error. 

### Code sample

I followed the advice of others with the same error and added the following to package.json:
  "jest": {
    "preset": "react-native",
    "SetupFiles": [
      "test/setup.js"
    ]
  }

and my setup.js file looks like this:

jest.mock('react-native-reanimated', () => {
  return {
    addEventListener: jest.fn(),
    removeEventListener: jest.fn(),
    openURL: jest.fn(),
    canOpenURL: jest.fn(),
    getInitialURL: jest.fn(),
  }
})

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        |
| react-native          |
| react-navigation-tabs |
| node                  |
| npm or yarn           |

**Comment by tanmay-patil** [comment]
I am still facing this issue, any help?

![Screenshot 2021-04-21 at 12 04 17 PM](https://user-images.githubusercontent.com/36257670/115507422-baa4f180-a299-11eb-99e5-392c82e6a3d8.png)
