### ISSUE TITLE
Display bottomtabnavigator on non included screens

### ISSUE THREAD

**Issue by max21** [react-navigation/react-navigation#7292]
### Current behaviour
When createBottomTabNavigator all screens with the bottom tab bar are in the bottom stack 

### Expected behaviour

I want to create a screen with the bottom stack but not include in the bottom stack. So the bottom stack can have no tab selected.
Like this example https://snack.expo.io/SyZElPlSm when you click on "Go to setting tab", the bottom tab is display but no tabs are selected.

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        |
| react-native          |
| react-navigation-tabs |
| node                  |
| npm or yarn           |

**Comment by talaikis** [comment]
For latest version:

```
const screenOptions = ({ route }) => ({
  tabBarButton: (props) => {
      const MAP = {
        A: null, // screen where we include tab bar, but won't display
        B: <TouchableOpacity {...props} />,
        ...   
      }

      return MAP[route.name]
})
```

**Comment by imoempire** [comment]
I have been trying to achieve this in Top Bar navigator but I am getting "navigator can only contain screen, group or react.fragment

const WorkOrderApp = () => {
  return (
    <WorkStack.Navigator screenOptions={{ headerShown: false }}>
      <WorkStack.Screen name={'workorder'} component={WorkScreen} />;
    </WorkStack.Navigator>
  );
};

const MyTabs = () => {
return (
<Tab.Navigator>
 <Tab.Screen
        name={HOME}
        options={{
          tabBarLabel: "Dashboard",
        }}
        component={Home}
      />
       <Tab.Screen
        name={HOME}
        options={{
          tabBarLabel: "WorkOrder",
        }}
        component={WorkOrderApp}
      />
</Tab.Navigator>
)
}

Anyone with how I can resolve this ?

**Comment by eugeek** [comment]
> I've found a workaround :
> 
> ` defaultNavigationOptions: ({navigation}) => ({ tabBarButtonComponent: props => { return (navigation.state.routeName === 'Connect') ? null : <TouchableOpacity {...props} />; } }),`
> 
> When 'Connect' is the screen you don't want to see in bottom tab bar

This works fine 👍
