### ISSUE TITLE
expose BottomTabBarProps

### ISSUE THREAD

**Issue by damathryx** [react-navigation/react-navigation#7297]
### Current behaviour

You can't import BottomTabBarProps from
```
import {BottomTabBarProps} from 'react-navigation-tabs'
``` 
### Expected behaviour
You can import the type to be used on custom tab bar component

### Code sample
```
import {BottomTabBarProps} from 'react-navigation-tabs'
const CustomBottomTabBar = (props: BottomTabBarProps) => {
 ...
}
```
`tabBarComponent: CustomBottomTabBar,`

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | both
| react-native          | 0.60.4
| react-navigation-tabs | 2.5.5

**Comment by changmen1** [comment]
+1
