### ISSUE TITLE
createMaterialTopTabNavigator initial route not working with tabBarComponent

### ISSUE THREAD

**Issue by pierregoutheraud** [react-navigation/react-navigation#7298]
### Current behaviour

When using "createMaterialTopTabNavigator" and "tabBarComponent", the TabNavigator does not stay on its initial route. Instead it quickly switches to the first route.

This only seem to reproduce in a react-native project (not using Expo) on Android only.
This works fine on Expo (Tested on snack.expo.io).
This works fine without "tabBarComponent" property.
This used to work fine on my other project on react-native 0.57.x

### Expected behaviour

TabNavigator should stay on initial route.

### Code sample

```javascript
// App.js
import React from "react";
import { Text } from "react-native";
import { createAppContainer } from "react-navigation";
import { createMaterialTopTabNavigator } from "react-navigation-tabs";

const TabNavigator = createMaterialTopTabNavigator(
  {
    test1: () => <Text>test1</Text>,
    test2: () => <Text>test2</Text>,
  },
  {
    tabBarComponent: () => null,
    initialRouteName: "test2",
  }
);

const AppContainer = createAppContainer(TabNavigator);

export default () => {
  return <AppContainer />;
};

```

This displays "test2" for a very short time (few frames) then switches to "test1" without any action.

![v](https://i.imgur.com/RNIRGrZ.gif)

### Your Environment

"react": "16.9.0",
"react-native": "0.61.1",
 "react-native-gesture-handler": "^1.4.1",
 "react-native-reanimated": "^1.3.0",
 "react-native-screens": "^1.0.0-alpha.23",
 "react-navigation": "^4.0.10",
 "react-navigation-tabs": "^2.5.5"

**Comment by satya164** [comment]
Closing since no one provided a repro. If you have a minimal repro, feel free to open an issue.
