### ISSUE TITLE
transparent color of BottomTabNavigator not working.

### ISSUE THREAD

**Issue by mukeshsharma1201** [react-navigation/react-navigation#7299]
### Current behaviour
Setting tabBarOptions.style.backgroundColor to transparent sets the background color to White.

### Expected behaviour
Setting tabBarOptions.style.backgroundColor to transparent should make the color invisible, i.e make the color transparent.

### Code sample
```javascript
createBottomTabNavigator(
    {
      DashboardStack: DashboardStack,
      EditStack: EditStack,
    },
    {
      tabBarOptions: {
        style: {
          backgroundColor: 'transparent',
        },
      },
    },
  ),
```

### What have you tried
I have tried the solution mentioned in a similar issue react-navigation/tabs#46 but the problem with it is that other scrollView don't consider the tab bar as bottom anymore. That is, if I scroll my vertical scroll view to the very end, goes behind the tab bar.
<br>Scroll View looks like this after scrolling to the bottom: 
![Scroll View looks like this](https://i.imgur.com/0zIzko0.png)
<br>and on **Android** I am not able to change tabs using this method.

 

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        |both
| react-native          |0.60.5
| react-navigation-tabs |2.5.3
| node                  |v12.9.1
| npm or yarn           |6.10.2

**Comment by dhavalpanchani** [comment]
position: 'absolute' is a solution for this, but you may notice it'll not look perfectly with the android side, however working perfectly for the android side.

Finally, I found the solution to this after long hard work.

elevation: 0

Set this on tab bar style will fix this issue.

Example -

tabBarOptions={{
        showIcon: true,
        showLabel: true,
        activeTintColor: COLORS.tabSelected,
        inactiveTintColor: COLORS.tabNormal, 
        style: {
          backgroundColor:'transparent',
          borderTopWidth: 0,
          position: 'absolute',
          elevation: 0  // <-- this is the solution
        },
        labelStyle: {
          fontSize: 12,
        },
      }}>

Here is the output screenshot.
[Before set "elevation: 0", it was looking like this][1]

[After set "elevation: 0", it's looking perfect][2]

  [1]: https://i.stack.imgur.com/o4eCJ.png
  [2]: https://i.stack.imgur.com/I0pFa.png

**Comment by dhavalpanchani** [comment]
position: 'absolute' is a solution for this, but you may notice it'll not look perfectly with the android side, however working perfectly for the android side.

Finally, I found the solution to this after long hard work.

elevation: 0

Set this on tab bar style will fix this issue.

Example -

tabBarOptions={{
        showIcon: true,
        showLabel: true,
        activeTintColor: COLORS.tabSelected,
        inactiveTintColor: COLORS.tabNormal, 
        style: {
          backgroundColor:'transparent',
          borderTopWidth: 0,
          position: 'absolute',
          elevation: 0  // <-- this is the solution
        },
        labelStyle: {
          fontSize: 12,
        },
      }}>

Here is the output screenshot.
[Before set "elevation: 0", it was looking like this][1]

[After set "elevation: 0", it's looking perfect][2]

  [1]: https://i.stack.imgur.com/o4eCJ.png
  [2]: https://i.stack.imgur.com/I0pFa.png
![Screenshot_1595331674](https://user-images.githubusercontent.com/25957550/88051784-d4809f00-cb76-11ea-9bd7-91531652d711.png)

**Comment by dhavalpanchani** [comment]
position: 'absolute' is a solution for this, but you may notice it'll not look perfectly with the android side, however working perfectly for the android side.

Finally, I found the solution to this after long hard work.

elevation: 0

Set this on tab bar style will fix this issue.

Example -

tabBarOptions={{
        showIcon: true,
        showLabel: true,
        activeTintColor: COLORS.tabSelected,
        inactiveTintColor: COLORS.tabNormal, 
        style: {
          backgroundColor:'transparent',
          borderTopWidth: 0,
          position: 'absolute',
          elevation: 0  // <-- this is the solution
        },
        labelStyle: {
          fontSize: 12,
        },
      }}>

Here is the output screenshots.

![Before set "elevation: 0", it was looking like this](https://user-images.githubusercontent.com/25957550/88051825-ec582300-cb76-11ea-8f46-ba6411df6c1d.png)

![After set "elevation: 0", it's looking perfect](https://user-images.githubusercontent.com/25957550/88051872-009c2000-cb77-11ea-9481-6d1f9a65c318.png)

**Comment by cgdstnc** [comment]
hi are you using v4 or v5 of this library. i cannot make it work like this

**Comment by dhavalpanchani** [comment]
v5

**Comment by dhavalpanchani** [comment]
> hi are you using v4 or v5 of this library. i cannot make it work like this

v5
