### ISSUE TITLE
focused prop tabBarIcon strange behaviour 

### ISSUE THREAD

**Issue by rossjohnsonMP** [react-navigation/react-navigation#7308]
### Current behaviour

When navigating to a tab the focused prop is passed through as true and then again as false wether the tab is being focused on or not

### Expected behaviour

TabBarIcon only re-rendered once with true if focused or false if not focused

### Code sample

https://github.com/rossjohnsonMP/Recipe

As can be seen in the code sample - any behaviour toggled by focused (text color) seems to work fine but console logging the prop shows it doesn't have the correct value which is stopping me from being able to add a side effect to the tab being focused or unfocused 

### What have you tried

console logging the prop - switching behaviour within the component on the prop

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | ios
| react-native          | 0.59.8 and 0.60.5
| react-navigation-tabs | 2.4.1
| node                  | 12.10
| npm or yarn           | yarn - 1.15.2

**Comment by louis9089** [comment]
i am trying to make my bottom tab navigator to paper in every page on my app
but the tab should only have 3 navigator (home,profile,setting)
so for example if I want to open list page I must go through the list button
it will show the list page while having the bottom tab navigator too
how do you make that?
