### ISSUE TITLE
undefined is not an object (evaluating '_reactNavigation.ThemeColors.light')

### ISSUE THREAD

**Issue by WrathChaos** [react-navigation/react-navigation#7314]
### Current behaviour

After upgraded react-navigation from v3 to v4, it just explodes. 

### Expected behaviour

Just navigate to screens

### Code sample

```
import { createBottomTabNavigator } from "react-navigation";
// Screens
import HomeScreen from "../../scenes/home/Home";
import TaskDetailsScreen from "../../scenes/task-details";

const defaultNavigationOptions = {
  tabBarVisible: false,
  header: null
};

export const Navigator = createBottomTabNavigator(
  {
    home: HomeScreen,
    taskDetails: TaskDetailsScreen
  },
  {
    defaultNavigationOptions
  }
);

```

### Screenshots (if applicable)

![Simulator Screen Shot - iPhone X - 2019-09-11 at 14 45 45](https://user-images.githubusercontent.com/6813862/64696750-e6e67280-d4a7-11e9-83a9-6949a6f62025.png)

### What have you tried

Tried to remove every cache, node_modules, package-lock.json etc but the problem still exists. 

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | iOS 12.3
| react-native          | 0.60.5
| react-navigation-tabs | 2.4.1
| react-navigation | 4.0.2
| node                  | v10.15.3
| npm or yarn           | npm 6.10.3

**Comment by satya164** [comment]
Closing since no repro was provided and I cannot repro this issue.

**Comment by BettyJJ** [comment]
You are my hero! 

> **experimentalImportBundleSupport: true** _//here//_ **metro-config/src/defaults/index.js**

This line saved me.

**Comment by febelectron** [comment]
I had 5x versions for native and core. Fixed the issue when replaced them with
```
    "@react-navigation/native": "3.8.4",
    "@react-navigation/core": "3.7.9",
```

**Comment by AahilShahzad** [comment]
I have tried a lot but no luck
I have same issue

"react": "17.0.2",
"react-native": "0.66.0",
"react-navigation": "^4.4.3",
 "react-navigation-drawer": "^1.4.0",
 "react-navigation-stack": "^1.10.3",
 "react-navigation-tabs": "^2.10.1",

anyOne can help please?
<img width="718" alt="Screenshot 2022-02-11 at 6 21 06 PM" src="https://user-images.githubusercontent.com/13553516/153598745-c1db5bac-0b64-464c-8b08-33227ec50316.png">
