### ISSUE TITLE
Typescript definition is wrong

### ISSUE THREAD

**Issue by EternalChildren** [react-navigation/react-navigation#7315]
### Current behaviour
![image](https://user-images.githubusercontent.com/27210994/64690804-dc39d680-d4c3-11e9-827a-dbfe18befe7a.png)
'initialRouteName' does not exist in type 'NavigationBottomTabOptions'

### Expected behaviour
no error

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | ios
| react-native          | 0.61.0
| react-navigation-tabs | 2.4.1
| node                  | 10.16.0
| npm or yarn           | 1.17.0

**Comment by Jarodshow** [comment]
Still having this issue with v5...

**Comment by damon02** [comment]
Somehow also an issue still with V6
