### ISSUE TITLE
ViewPagerAndroid has been extracted from react-native core and will be removed in a future release.

### ISSUE THREAD

**Issue by avrcoelho** [react-navigation/react-navigation#7328]
I am using the createMaterialTopTabNavigator, but getting the error:

"ViewPagerAndroid has been extracted from react-native core and will be removed in a future release."

How to solve?

**Comment by stevanka988** [comment]
I am using the createMaterialTopTabNavigator, but getting the error:

![Screenshot_1624743833](https://user-images.githubusercontent.com/41450109/123526474-76d6ca00-d6d8-11eb-885c-6406dcc1dbcb.png)

I don't use ViewPager, this is happening every time when i navigate to the screen with createMaterialTopTabNavigator.
I have this problem just on Android.

React Navigation 4

Do you have any idea?

**Comment by shubhext** [comment]
This issue stilll persists it is not working with  react-native 0.0.64
react-navigation :-    "react-navigation": "^2.1.0",
