### ISSUE TITLE
TypeError: Cannot read property 'out' of undefined

### ISSUE THREAD

**Issue by nwaughachukwuma** [react-navigation/react-navigation#7342]
Hey guys, am having following error message:  `TypeError: Cannot read property 'out' of undefined` when using and testing components that use react-navigation-tabs. Basically, how can I mock this module?

@brentvatne @satya164

| software              | version
| --------------------- | -------
| ios or android        | android
| react-native          | 0.59.8
| react-navigation-tabs | 2.1.2
| node                  | 8.11.3
| npm or yarn           | yarn (1.15.2)

**Comment by yangfreezy** [comment]
Thank you so much @nwaughachukwuma!
