### ISSUE TITLE
Knowing wether or not the user is swiping the material top bar navigator

### ISSUE THREAD

**Issue by jordy-wijman** [react-navigation/react-navigation#7343]
### Current behaviour

I'm trying to hook onto the isSwiping property of the material top bar navigator, so I can transition my shared component (that is shared over all the tabs) whenever the animation is starting and ending. Currently there is no way to do this.

### Expected behaviour

It would be awesome if a prop would be sent back that would indicate wether the animation is happening yes or no. I know that you can hook onto react navigations' didBlur and willFocus events, but these happen too late. They happen whenever the transition is done.

### Code sample

      <View style={styles.container}>
        <FavoritesNavigator navigation={navigation} />
        /** I want to transition this floating action button when the navigator changes OR starts
        swiping, however we currently can't hook onto 'isAnimating' or anything like that. */
        <FAB
          icon="add"
          color="white"
          style={styles.fab}
          onPress={() =>
            navigation.navigate(
              navigation.state.index === 0
                ? NavigationScreens.TRIP_DETAIL_SCREEN
                : NavigationScreens.LABEL_DETAIL_SCREEN,
            )
          }
        />
      </View>

### What have you tried
Looked at the implementation of the createMaterialTopBarNavigator and couldn't find an API available here that I could use.

**Comment by alieslam** [comment]
@satya164 Do you have any updates on exposing `swipeStart` and `swipeEnd` callbacks to TopTabNavigator?
