### ISSUE TITLE
tabBarVisible not working 

### ISSUE THREAD

**Issue by CosmicSage** [react-navigation/react-navigation#7346]
### Current behaviour

tabBarVisible is not hiding the TabBar at the bottom

### Expected behaviour

TabBar should be hidden

### Code sample
  /** navigation.state.index is undefined
      Therefore used routeName
  **/
  static navigationOptions = ({ navigation }) => {
  navigationOptions = {
    title: navigation.getParam('Title', 'Info Unavialable'),
  };
  if (navigation.state.routeName === "Details") {
    navigationOptions.tabBarVisible = false;
  }
  return navigationOptions;
};
The Snack : https://snack.expo.io/@coldlinux/trembling-candies
The issue most probably lies in the DetailsScreen.js file inside screens directory

### What have you tried

I've read issue react-navigation/tabs#19 and react-navigation/tabs#20 and also read 
https://reactnavigation.org/docs/en/navigation-options-resolution.html#a-tab-navigator-contains-a-stack-and-you-want-to-hide-the-tab-bar-on-specific-screens
Tried the solutions mentioned in all of them

The code snippet is taken from DetailsScreen.js file and the entire projects is present on My profile under the name "Project2"
### Your Environment

| software              | version
| --------------------- | -------
| react-native          |0.59
| react-navigation-tabs |3.0.9
| node                  |11.7.0
| npm or yarn           |6.9.0

**Comment by ghasemikasra39** [comment]
same here:
```
    "@react-navigation/bottom-tabs": "^5.3.1",
    "@react-navigation/native": "^5.2.1",
    "@react-navigation/stack": "^5.2.16",
```
