### ISSUE TITLE
ScrollView is not working with createMaterialTopTabNavigator in Android

### ISSUE THREAD

**Issue by billouboq** [react-navigation/react-navigation#7361]
@listingzhao explained the problem pretty well in his post.

See :

https://github.com/react-navigation/react-navigation/issues/4987#issue-359859427

**Comment by ThallyssonKlein** [comment]
Same issue here, and not fix by using ScrollView from react-native-gesture-handler

**Comment by 3KINGZ** [comment]
anybody solved this issue?

**Comment by gui-grana** [comment]
I'm still having this problem, when trying to use createMaterialTopTabNavigator inside ScrollView on React Navigation 6.
