### ISSUE TITLE
TabBarIcon: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.

### ISSUE THREAD

**Issue by hammadxoho** [react-navigation/react-navigation#7368]
Getting this error 
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of "TabBarIcon".

Following is the code i have:- issue in the build for ios 

import React from 'react';
import {createStackNavigator, createBottomTabNavigator, createSwitchNavigator} from 'react-navigation';
import {Alert} from 'react-native';
import { FontAwesome } from "react-native-vector-icons";

I was using Expo.io before and it worked all fine, but after ejecting and removing expo completely (not using expokit), i am starting to get these issues

**Comment by AkihikoITOH** [comment]
@hammadxoho I've encountered a similar issue with `MaterialCommunityIcons`, and [this](https://github.com/oblador/react-native-vector-icons/issues/937) fixed the issue for me.

I might be completely wrong here as I started doing anything with react-native and react-navigation just yesterday, but perhaps the examples in the documentation such as https://reactnavigation.org/docs/bottom-tab-navigator#example need to be updated accordingly.

**Comment by vishalseshagiri** [comment]
For newbies like me trying this on android seeing an error for import  { Icon } from 'react-native-vector-icons/dist/FontAwesome';
this should be a default import like this import Icon from ...
see this really helpful post on stackoverflow https://stackoverflow.com/a/56419701/6254414

**Comment by Daniel730** [comment]
I had the same problem. The issue was that I was doing wrong the import.
Should be like this: import Ionicons from 'react-native-vector-icons/Ionicons'
Instead of this: import Ionicons from 'react-native-vector-icons'

**Comment by J6ey** [comment]
@AkihikoITOH 
How is `import {MaterialCommunityIcons} from 'react-native-vector-icons/MaterialCommunityIcons';` any different? And how exactly did you fix the 'Element type is invalid' error?
