### ISSUE TITLE
Labels overlapping icon on IPAD when using createBottomTabNavigator

### ISSUE THREAD

**Issue by proutek** [react-navigation/react-navigation#7383]
### Current behaviour

Labels are overlapping icons on IPAD if tabBarLabel is function returning **\<Text\>Label\</Text\>** and not just string in navigationOptions
According to documentation it should be supported

[https://reactnavigation.org/docs/en/bottom-tab-navigator.html](https://reactnavigation.org/docs/en/bottom-tab-navigator.html)
**tabBarLabel**
Title string of a tab displayed in the tab bar or React Element or a function that given { focused: boolean, tintColor: string } returns a React.Node, to display in tab bar. When undefined, scene title is used. To hide, see tabBarOptions.showLabel in the previous section.

### Expected behaviour

Labels do not overlap icons.
### Code sample

Expo snack (Run it on **IPAD**)
[https://snack.expo.io/@chilly/vigorous-kiwi](https://snack.expo.io/@chilly/vigorous-kiwi)

It can be reproduced also on android tablet or phone when I modify this function in 
**node_modules\react-navigation-tabs\src\views\BottomTabBar.js**

```
  _shouldUseHorizontalLabels = () => {
    return true; 
}
```

### Screenshots (if applicable)

Android tablet (with modified BottomTabBar.js)
![screenshot_2018-11-07-10-14-44](https://user-images.githubusercontent.com/21219132/48129031-994a1980-e288-11e8-92f6-995677a2877f.png)

IPAD
![ipad](https://user-images.githubusercontent.com/21219132/48129216-15446180-e289-11e8-8b1e-f21c7a97818f.jpg)

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        |
| react-native          |
| react-navigation-tabs | 0.8.4
| node                  |
| npm or yarn           |

**Comment by gaurav0044** [comment]
labelPosition
Whether the label is rendered below the icon or beside the icon. Possible values are:

below-icon
beside-icon

[https://reactnavigation.org/docs/bottom-tab-navigator#labelposition](url)

**Comment by CptFabulouso** [comment]
These two styles are used by the lib
```
labelBeneath: {
    fontSize: 10,
},
labelBeside: {
    fontSize: 13,
    marginLeft: 20,
    marginTop: 3,
},
```
so if anyone wants to use their on Text component with horizontal support, you can achieve that by:
```
export const TabLabel = ({ focused, title, position }) => {
  return (
    <Text
      style={{
        marginLeft: position === 'beside-icon' ? 20 : 0,
        marginTop: position === 'beside-icon' ? 3 : 0,
      }}
    >
      {title}
    </Text>
  );
};
```

The reason I do not use `title` prop with `labelStyle` is because I need different styling for active / inactive state besides just color. Maybe the `labelStyle` prop could accept function with `focused` prop?
