### ISSUE TITLE
I want to hide bottom tab bar when keyboard appear

### ISSUE THREAD

**Issue by tndyd5390** [react-navigation/react-navigation#7386]
i have some problem with bottomtabnavigator,
bottomtab dosen't disappear when keyboard is activated
how can i hide my bottom tab bar when keyboard is activated???

and this is my code
`import React, {Component} from 'react';
import {Platform, StyleSheet, Text, View, Image} from 'react-native';
import {createBottomTabNavigator, withNavigation} from 'react-navigation';
import Icon from 'react-native-vector-icons/Ionicons';
import IconFontAwesome from 'react-native-vector-icons/FontAwesome';
import Explore from './screens/Explore';
import Reservation from './screens/Reservation';
import Saved from './screens/Saved';
import Chat from './screens/Chat';
import Profile from './screens/Profile';
import Colors from './utils/Colors';

export default createBottomTabNavigator({
  Explore : {
    screen : Explore,
    navigationOptions : {
      tabBarLabel : '검색하기',
      tabBarIcon : ({tintColor}) => (
        //<Image source={require('./img/img.png')} style={{height : 24, width : 24, tintColor : tintColor}}/>
        <Icon name='ios-search' color={tintColor} size={24}/>
      )
    }
  },
  Saved : {
    screen : Reservation,
    navigationOptions : {
      tabBarLabel : '예약보기',
      tabBarIcon : ({tintColor}) => (
        <IconFontAwesome name='calendar' color={tintColor} size={24}/>
      )
    }
  },
  Trips : {
    screen : Chat,
    navigationOptions : {
      tabBarLabel : '대화하기',
      tabBarIcon : ({tintColor}) => (
        <IconFontAwesome name='comments' color={tintColor} size={24}/>
      )
    }
  },
  Profile : {
    screen : withNavigation(Profile),
    navigationOptions : {
      tabBarLabel : '프로필',
      tabBarIcon : ({tintColor}) => (
        <IconFontAwesome name='user' color={tintColor} size={24}/>
      )
    }
  },
},
{
  tabBarPosition : 'bottom',
  swipeEnabled : false,
  tabBarOptions : {
    activeTintColor : 'red',
    inactiveTintColor : 'grey',
    style : {
      //backgroundColor : 'white',
      backgroundColor : Colors.bottomNavigatorGrey,
      borderTopWidth : 0,
      shadowOffset : {width : 5, height : 3},
      shadowColor : 'black',
      shadowOpacity : 0.5,
      elevation : 5
    }
  }
})

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fff',
  }
});
`

`import React, {Component} from 'react';
import {
  Platform, 
  StyleSheet, 
  Text, 
  View,
  Dimensions,
  Image,
  TextInput,
  Keyboard,
  TouchableOpacity
} from 'react-native';
import Colors from '../utils/Colors';
import Icon from 'react-native-vector-icons/FontAwesome';
import PropTypes from 'prop-types';
const{height, width} = Dimensions.get('window');

class Profile extends Component {
  render() {
    return (
      <View style={styles.container}>
        <View>
          <Image source={require('../../img/user.png')} style={{width : 200, height : 200, marginTop : 30}}/>
        </View>
        <View style={{width : width-60}}>
          <Text style={styles.idText}>아이디</Text>
          <TextInput style={{borderBottomWidth : 1, paddingTop : 5, paddingBottom : 5}}/>
        </View>
      </View>
    );
  }
}

export default Profile;

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    backgroundColor: Colors.white,
  }, 
  idText : {
    fontSize : 20,
    marginTop : 10
  }
});`

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | android
| react-native          | react-native-cli 2.0.1
| react-navigation-tabs | 2.0.4
| node                  | 10.6.0
| npm or yarn           | npm 6.1.0

**Comment by ManuViola77** [comment]
> ./gradlew clean

Thank you!!! I've been trying for hours and I was missing the cleaning part! I thought it just didn't work!

**Comment by NishargShah** [comment]
Sometime setting `android:windowSoftInputMode` to `adjustPan` or `adjustResize` is not ideal idea because it effects whole application.

so that is my idea to solve that error.

###  React Navigation 5

```
import React, { useEffect, useState } from 'react';
import { Platform, Keyboard } from 'react-native';
import { BottomTabBar } from '@react-navigation/bottom-tabs';

const CustomBottomTabBar = props => {
  const [visible, setVisible] = useState(true);

  useEffect(() => {
    let keyboardEventListeners;
    if (Platform.OS === 'android') {
      keyboardEventListeners = [
        Keyboard.addListener('keyboardDidShow', () => setVisible(false)),
        Keyboard.addListener('keyboardDidHide', () => setVisible(true)),
      ];
    }
    return () => {
      if (Platform.OS === 'android') {
        keyboardEventListeners &&
          keyboardEventListeners.forEach(eventListener => eventListener.remove());
      }
    };
  }, []);

  const render = () => {
    if (Platform.OS === 'ios') {
      return <BottomTabBar {...props} />;
    }
    if (!visible) return null;
    return <BottomTabBar {...props} />;
  };

  return render();
};

export default CustomBottomTabBar;

```

**Comment by zoobibackups** [comment]
check this for react-navigation 5 
[https://reactnavigation.org/docs/bottom-tab-navigator/#keyboardhidestabbar](url)

**Comment by MedElba** [comment]
> Sometime setting `android:windowSoftInputMode` to `adjustPan` or `adjustResize` is not ideal idea because it effects whole application.
> 
> so that is my idea to solve that error.
> 
> ### React Navigation 5
> **BottomTabBar.js**
> 
> ```
> import React, { useEffect, useState } from 'react';
> import { Platform, Keyboard } from 'react-native';
> import { BottomTabBar } from '@react-navigation/bottom-tabs';
> 
> const CustomBottomTabBar = props => {
>   const [visible, setVisible] = useState(true);
> 
>   useEffect(() => {
>     let keyboardEventListeners;
>     if (Platform.OS === 'android') {
>       keyboardEventListeners = [
>         Keyboard.addListener('keyboardDidShow', () => setVisible(false)),
>         Keyboard.addListener('keyboardDidHide', () => setVisible(true)),
>       ];
>     }
>     return () => {
>       if (Platform.OS === 'android') {
>         keyboardEventListeners &&
>           keyboardEventListeners.forEach(eventListener => eventListener.remove());
>       }
>     };
>   }, []);
> 
>   const render = () => {
>     if (Platform.OS === 'ios') {
>       return <BottomTabBar {...props} />;
>     }
>     if (!visible) return null;
>     return <BottomTabBar {...props} />;
>   };
> 
>   return render();
> };
> 
> export default CustomBottomTabBar;
> ```
> 
> **AppNavigator.js**
> 
> ```
> import { createBottomTabNavigator } from '@react-navigation/bottom-tabs';
> 
> const bottomTabNavigator = createBottomTabNavigator();
> 
> <BottomNavigator
>     screenOptions={bottomTabScreenOptions}
>     tabBarOptions={bottomTabBarOptions}
>     tabBar={props => <CustomBottomTabBar {...props} />}
> >
>     ......
> </BottomNavigator>
> ```

Hi! 
This workaround works, but is a bit laggy and sometimes shows the flash of the disappearing tab bar over the keyboard

**Comment by NishargShah** [comment]
> > Sometime setting `android:windowSoftInputMode` to `adjustPan` or `adjustResize` is not ideal idea because it effects whole application.
> > so that is my idea to solve that error.
> > ### React Navigation 5
> > **BottomTabBar.js**
> > ```
> > import React, { useEffect, useState } from 'react';
> > import { Platform, Keyboard } from 'react-native';
> > import { BottomTabBar } from '@react-navigation/bottom-tabs';
> > 
> > const CustomBottomTabBar = props => {
> >   const [visible, setVisible] = useState(true);
> > 
> >   useEffect(() => {
> >     let keyboardEventListeners;
> >     if (Platform.OS === 'android') {
> >       keyboardEventListeners = [
> >         Keyboard.addListener('keyboardDidShow', () => setVisible(false)),
> >         Keyboard.addListener('keyboardDidHide', () => setVisible(true)),
> >       ];
> >     }
> >     return () => {
> >       if (Platform.OS === 'android') {
> >         keyboardEventListeners &&
> >           keyboardEventListeners.forEach(eventListener => eventListener.remove());
> >       }
> >     };
> >   }, []);
> > 
> >   const render = () => {
> >     if (Platform.OS === 'ios') {
> >       return <BottomTabBar {...props} />;
> >     }
> >     if (!visible) return null;
> >     return <BottomTabBar {...props} />;
> >   };
> > 
> >   return render();
> > };
> > 
> > export default CustomBottomTabBar;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **AppNavigator.js**
> > ```
> > import { createBottomTabNavigator } from '@react-navigation/bottom-tabs';
> > 
> > const bottomTabNavigator = createBottomTabNavigator();
> > 
> > <BottomNavigator
> >     screenOptions={bottomTabScreenOptions}
> >     tabBarOptions={bottomTabBarOptions}
> >     tabBar={props => <CustomBottomTabBar {...props} />}
> > >
> >     ......
> > </BottomNavigator>
> > ```
> 
> Hi!
> This workaround works, but is a bit laggy and sometimes shows the flash of the disappearing tab bar over the keyboard

Yes sometimes possible but that hack is perfect for this type of problem.

**Comment by medmo7** [comment]
```javascript
  <BottomTab.Navigator
    tabBarOptions={{
      keyboardHidesTabBar: true,
    }}
  >
```

**Comment by Nivethan-Ar** [comment]
> ```js
>   <BottomTab.Navigator
>     tabBarOptions={{
>       keyboardHidesTabBar: true,
>     }}
>   >
> ```

not working for a custom tab bar

**Comment by GeorgiIvanovPXL** [comment]
So, still no solution for this?

**Comment by alistairholt** [comment]
If you delve into the docs and source code, you will find a solutuion for using a custom tab bar 👀  - @Nivethan-Ar @GeorgiIvanovPXL.

This example is for React Navigation 6.x:

```jsx
<BottomTab.Navigator
  tabBar={(props) => <CustomTabBar {...props} />}
  screenOptions={{
    tabBarHideOnKeyboard: true,
  }}
>
  ...
</BottomTab.Navigator>
```

```jsx
function CustomTabBar({ state, descriptors }) {
  // Based on code from https://github.com/react-navigation/react-navigation/blob/main/packages/bottom-tabs/src/views/BottomTabBar.tsx
  const focusedRoute = state.routes[state.index]
  const focusedDescriptor = descriptors[focusedRoute.key]
  const focusedOptions = focusedDescriptor.options

  const { tabBarHideOnKeyboard = false } = focusedOptions

  // Custom hook borrowed from https://github.com/react-navigation/react-navigation/blob/main/packages/bottom-tabs/src/utils/useIsKeyboardShown.tsx
  const isKeyboardShown = useIsKeyboardShown() 
  const shouldShowTabBar = !(tabBarHideOnKeyboard && isKeyboardShown)

  return (
    // Do whatever you want here and hide it however you want using `shouldShowTabBar`
    // I'm using `react-native-reanimated` to animate it in and out but they use `Animated` from `react-native`
  )
}
```

**Comment by sivakrishnacode** [comment]
> Hello, if you don't want the input box to start the bottom navigation bar, please do this. Replace one line of code in `android\app\src\main\AndroidManifest.xml` inside the project I did this, I don't know if it is feasible for you.
> 
> ```
> <application
>       
>       <activity
>         android:name=".MainActivity"
>         android:label="@string/app_name"
>         android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
>                 
>         android:windowSoftInputMode="stateAlwaysHidden|adjustPan">
>         <intent-filter>
>             <action android:name="android.intent.action.MAIN" />
>             <category android:name="android.intent.category.LAUNCHER" />
>         </intent-filter>
>       </activity>
>       <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
>     </application>
> ```

its working thanks
