### ISSUE TITLE
withDimensions reporting incorrect when Split-screen on Tablet

### ISSUE THREAD

**Issue by SteffeyDev** [react-navigation/react-navigation#7387]
### Current behaviour

The `dimensions.width on an iPad` (and any tablet or phone that supports split-screen capabilities) is incorrect, because the React Native `Dimensions.get('window')` reports the full width of the device.

### Expected behaviour

The `dimensions.width` passed in from the `withDimensions` HOC should return the actual dimensions of the app instead of the dimensions of the device, as those are the only dimensions any navigation components should be concerned with.  It doesn't matter if the device is 1300 points wide if we can only use 400 points because the app is run in split-screen mode.

### Code

A simple glance at the [withDimensions.js](https://github.com/react-navigation/react-navigation-tabs/blob/master/src/utils/withDimensions.js) code makes the issue evident.

### Use Case and History

I am the original author of https://github.com/react-navigation/react-navigation/pull/3041, which allowed for better tab navigation rendering on tablets in split screen mode.  As you can see in that pull request (specifically https://github.com/react-navigation/react-navigation/pull/3041/files#diff-cf9accb5a3555e3383f8175c7e7c6fd9R213) I used the `layout.width` prop that was passed in to `TabBarBottom` to determine the width of the device, and then using that width enable the adaptive tabs on iOS 11+ devices.  Somewhere when this was broken off as it's own repo, that code was lost, and `layout.width` was replaced with `dimensions.width`, which, as described above, is not equivalent.  This breaks adaptive tabs.

### Potential fix

I believe that updating withDimensions to pull the dimensions from the `onLayout` callback would be preferable to the `Dimensions.get('window')`, though the 
RN dimensions could be used for the initial state.

### Your Environment

| software              | version
| --------------------- | -------
| ios        | 12.0.1
| react-native          | 0.57.3
| react-navigation-tabs | 0.8.4
| node                  | v9.2.0
| yarn           | 1.3.2

**Comment by satya164** [comment]
In latest version (v6), we don't use `Dimensions` API anymore in favor of `useSafeAreaFrame` from `react-native-safe-area-context` which should return the correct size. So I'm closing this.
