### ISSUE TITLE
Tab bar visibility in nested createStackNavigator screens.

### ISSUE THREAD

**Issue by shoaibehmed** [react-navigation/react-navigation#7411]
### Current behaviour

tabBarVisible: false;
does not hide the tab bar.

### Expected behaviour

tabBarVisible: false;
should hide the tab bar.

### Code sample

https://snack.expo.io/@shoaibahmed/stacks-in-tabs

### What have you tried

I have a nested createStackNavigator within a createBottomTabNavigator. On one of the stack navigator screens I'd like the tab bar to be invisible. Previously in version 1 all I had to do was set tabBarVisible: false in navigationOptions of the screen. Updated to version 2 and the tab bar is still visible.

tabBarVisible: false;
only works while setting it in the routeconfig of createBottomTabNavigator for a specific screen, but that hides the tab bar for the whole stack.
like this

```
export default createBottomTabNavigator(
  {
    Home: { screen: HomeStack, navigationOptions:{tabBarVisible: false} },
    Settings: { screen: SettingsStack },
  },
);
```

This is expected according to react-navigation/tabs#19 .
react-navigation/tabs#19 doesn't really apply to my scenario.

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | android
| react-native          | 0.55.3
| react-navigation |  2.0.0
| node                  | 8.9.4
| npm or yarn           | 5.6.0

**Comment by mkamranhamid** [comment]
thanks @brentvatne your [solution](https://github.com/react-navigation/react-navigation/issues/7412#issuecomment-387885810) worked like a charm
