### ISSUE TITLE
Bottom tab bars and keyboard on Android

### ISSUE THREAD

**Issue by brentvatne** [react-navigation/react-navigation#7415]
### Current behaviour

Keyboard pushes tab bar up on Android when open.

### Expected behaviour

By default, the tab bar should be hidden when the keyboard is open. It should be controllable with tab bar options.

### Code sample & screenshots

Examples and screenshots in original issue: https://github.com/react-navigation/react-navigation/issues/618

### What have you tried

Many examples listed in original issue

**Comment by shubhankar30** [comment]
https://reactnavigation.org/docs/bottom-tab-navigator/

As mentioned by @brentvatne and the documentation given above,

```
Set keyboardHidesTabBar : true 
```

**Comment by NathanBeesley** [comment]
The solution { keyboardHidesTabBar: true } does in fact work. The only problem I personally have with it is that it initially slides up with the keyboard and then hides. Is this normal expected behavior? If so I assume its caused by Android lacking keyboardWillShow listener?

**Comment by brentvatne** [comment]
@NathanBeesley - correct

**Comment by MarianAlexandruAlecu** [comment]
For anyone using the default `createBottomTabNavigator()`, I did the following:

```

const BottomTab = createBottomTabNavigator<BottomTabParamList>();

const useTabBarVisibility = () => {
	const [visible, setVisible] = useState(true);
	const keyboardEventListeners = useRef<EmitterSubscription[]>([]);

	useEffect(() => {
		const listeners = keyboardEventListeners.current;

		if (Platform.OS === 'android') {
			listeners?.push(
				Keyboard.addListener('keyboardDidShow', () =>
					setVisible(false),
				),
			);
			listeners?.push(
				Keyboard.addListener('keyboardDidHide', () => setVisible(true)),
			);
		}

		return () => listeners && listeners.forEach((event) => event.remove());
	}, []);

	return visible;
};

export default function BottomTabNavigator() {
	const { theme } = useTheme();
	const visible = useTabBarVisibility();

	return (
		<BottomTab.Navigator
			initialRouteName="Home"
			tabBarOptions={{
				activeTintColor: theme.colors?.primary,
				showLabel: false,
				style: {
					display: visible ? 'flex' : 'none',
				},
			}}
		>
			<BottomTab.Screen
				name="Home"
				component={HomeNavigator}
				options={{
					tabBarIcon: ({ color }) => (
						<TabBarIcon name="home-sharp" color={color} />
					),
				}}
			/>
			....
		</BottomTab.Navigator>
	);
}
``` 

Returning `null` was breaking my navigation, so I just used `display: none` instead

**Comment by zain-khalid** [comment]
You just need to change 
android:windowSoftInputMode="stateUnspecified|adjustPan"
from the android manifest file. It worked for me.


As mentioned in https://www.codegrepper.com/code-examples/javascript/bottom+navigation+bar+react+native+hide+on+keyboard

**Comment by piyushyadav0191** [comment]
I found a Fix for android and IOS
```
import {  Dimensions, View } from "react-native";
const { width, height } = Dimensions.get("window")


.....
return (
  <View
     style={{
      width,
      height,
  }}
  >
    <Tabs>
..... 
</Tabs>
</View>
)


```
