### ISSUE TITLE
iPhoneX SafeAreaView support on createMaterialTopNavigator

### ISSUE THREAD

**Issue by fabriziogiordano** [react-navigation/react-navigation#7425]
### Current behaviour

`createMaterialTopTabNavigator` nor `createBottomTabNavigator` handle iPhoneX.

### Expected behaviour

`createMaterialTopTabNavigator` or `createBottomTabNavigator` handle iPhoneX.

### Code sample

Here the Snack:
https://snack.expo.io/@fabrygio/react-navigator-2.x-beta-3---top-bottom-nav

### Screenshots (if applicable)
<img width="420" alt="screen shot 2018-03-20 at 7 29 06 pm" src="https://user-images.githubusercontent.com/109390/37688153-faa5f3f4-2c74-11e8-912c-f7c1158ea423.png">

<img width="420" alt="screen shot 2018-03-20 at 7 29 04 pm" src="https://user-images.githubusercontent.com/109390/37688154-fab13b92-2c74-11e8-820f-4516990054f7.png">

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        |
| react-native          |
| react-navigation-tabs |
| node                  |
| npm or yarn           |

**Comment by Jordan-Morrison** [comment]
Anyway to get this working in React Navigation v5? Been trying to use the SafeAreaView with no luck
