### ISSUE TITLE
Active Tab Route Name

### ISSUE THREAD

**Issue by devonwesley** [react-navigation/react-navigation#7429]
Abtract:
- Is there a way to inform the other tabs about the name of the current tab?

Description:
- I want to change the color of the tab bars color and the icons colors based upon the name of the current route.

Example: 
- If a tab is named "Airplane", I need the tab bar to be blue and all of the icons to be white.
- If it's any other tab then I want the tab bar color to be white with all of the icons to be blue.
- So knowing that an icons name is Airplane is important and why the properties "active" or "focused" won't work in this case.

**Comment by frankenthumbs** [comment]
check out navigation's state object.. it should let you traverse the active routes.
