### ISSUE TITLE
Icons not changing color in inactive state

### ISSUE THREAD

**Issue by ilibilibom** [react-navigation/react-navigation#7432]
Hi
I'm using createMaterialBottomTabNavigator v5 with react navigation v5. 
```
    "@react-navigation/material-bottom-tabs": "^5.0.0-alpha.15",
    "@react-navigation/native": "^5.0.0-alpha.7",
    "@react-navigation/stack": "^5.0.0-alpha.15",
```
The icons are not changing their color when not active. 
here is how it looks like: 
![Screen Shot 2019-11-05 at 10 07 41](https://user-images.githubusercontent.com/12745414/68189518-231fe600-ffb4-11e9-869f-1e4c80ad4d8b.png)
I would like the icons to be blue, same as the text. 

Here is my code: 

```
const Tab = createMaterialBottomTabNavigator();

export default function StackTabs() {
  return (
    <NavigationNativeContainer>
      <Tab.Navigator
        initialRouteName="Home"
        activeColor="#000"
        inactiveColor="blue"
        shifting={false}
        barStyle={{backgroundColor: '#fff'}}>
        <Tab.Screen
          name="Home"
          component={Home}
          options={{
            tabBarLabel: 'Home',
            tabBarIcon: ({tintColor}) => (
              <Icon name="home" color={tintColor} size={25} />
            ),
          }}
        />
        <Tab.Screen
          name="My Items"
          component={MyItems}
          options={{
            tabBarLabel: 'My Items',
            tabBarIcon: ({tintColor, focused}) => (
              <Icon size={25} name="dashboard" color={tintColor} />
            ),
          }}
        />
        <Tab.Screen
          name="My Groups"
          component={MyGroups}
          options={{
            tabBarLabel: 'My Groups',
            tabBarIcon: ({tintColor, focused}) => (
              <Icon size={25} name="people" color={tintColor} />
            ),
          }}
        />
        <Tab.Screen
          name="Chat"
          component={Home}
          options={{
            tabBarLabel: 'Chat',
            tabBarIcon: ({tintColor, focused}) => (
              <Icon size={25} name="chat" color={tintColor} />
            ),
          }}
        />
      </Tab.Navigator>
    </NavigationNativeContainer>
  );
}
```

**Comment by marcosriani** [comment]
Thank you that worked for me.

`import { createMaterialBottomTabNavigator } from '@react-navigation/material-bottom-tabs';
import MaterialCommunityIcons from 'react-native-vector-icons/MaterialCommunityIcons';

const Tab = createMaterialBottomTabNavigator();

function MyTabs() {
  return (
    <Tab.Navigator
      initialRouteName="Feed"
      activeColor="#e91e63"
      style={{ backgroundColor: 'tomato' }}
    >
      <Tab.Screen
        name="Feed"
        component={Feed}
        options={{
          tabBarLabel: 'Home',
          tabBarIcon: ({ color }) => (
            <MaterialCommunityIcons name="home" color={color} size={26} />
          ),
        }}
      />
      <Tab.Screen
        name="Notifications"
        component={Notifications}
        options={{
          tabBarLabel: 'Updates',
          tabBarIcon: ({ color }) => (
            <MaterialCommunityIcons name="bell" color={color} size={26} />
          ),
        }}
      />
      <Tab.Screen
        name="Profile"
        component={Profile}
        options={{
          tabBarLabel: 'Profile',
          tabBarIcon: ({ color }) => (
            <MaterialCommunityIcons name="account" color={color} size={26} />
          ),
        }}
      />
    </Tab.Navigator>
  );
}`

**Comment by marcosriani** [comment]
Thank you, that worked for me.

`<Tab.Screen
        name="Profile"
        component={Profile}
        options={{
          tabBarLabel: 'Profile',
          tabBarIcon: ({ color }) => (
            <MaterialCommunityIcons name="account" color={color} size={26} />
          ),
        }}
      />`
