### ISSUE TITLE
Can't import {MaterialCommunityIcons} from 'react-native-vector-icons';

### ISSUE THREAD

**Issue by ilibilibom** [react-navigation/react-navigation#7434]
I'm trying to import  {MaterialCommunityIcons} from 'react-native-vector-icons' 
and vscode is telling me:
```
Module '"../../../../../../../../../Users/ilandiamond/Developer/Code/me/bla/app/node_modules/@types/react-native-vector-icons"' has no exported member 'MaterialCommunityIcons'
```

**Comment by shlokamin** [comment]
Same issue using TS. Contrary to the docs, if you import as a default like this:

```
import MaterialCommunityIcons from 'react-native-vector-icons/MaterialCommunityIcons'
```
and consume like this:

```
const App = () =>  <MaterialCommunityIcons name="home" color={color} size={26} />
```

You sould be groovy

**Comment by manjeetKaurSaini** [comment]
Use following command and  it will work
yarn add --dev @types/react-native-vector-icons

**Comment by manjeetKaurSaini** [comment]
I faced this issue and just resolved it .
