### ISSUE TITLE
Hide tabbar in specific screen

### ISSUE THREAD

**Issue by alikazemkhanloo** [react-navigation/react-navigation#7464]
I want to hide tabbar when I reached a screen deep in the stackNavigator.
my routes are something like this:

materialTabNavigator:{
    Homestack:{
         Homescreen, 
         Detailscreen
    },
    Librarystack: {        
          Libraryscreen,
          Detailscreen
     }
}
and I want to hide the tabbar when I reach the Detailscreen.
when I use tabBarVisible in Homestack it works fine, But using it in Detailscreen, doesn't.
In react-navigation/material-bottom-tabs#20, we can only hide tabbar, if we are in the direct child of tab navigator. But if you go deeper, you can't. I think this option must be passed all the way to top in the navigation tree 🤔

**Comment by umerhayat54** [comment]
example like this :

const AppStack = createStackNavigator({
  SplashScreen: {
    screen: SplashScreen,
    navigationOptions: {
      header: null,
    },
  },
  Home: Home,
  CarouselMap: CarouselMap,
  HeatMapComponent: HeatMapComponent,
});

**Comment by pyxploiter** [comment]
> Hi
> This is not working for me.
> I'm using react-navigation v5
> It's not even getting into the function since I don't see any console.log()
> here is my code:
> 
> ```
> function homeStack() {
>   return (
>     <Stack.Navigator>
>       <Stack.Screen
>         name="Home"
>         component={Home}
>         options={{
>           header: null,
>         }}
>       />
> 
>       <Stack.Screen
>         name="Item"
>         component={Item}
>         options={{
>           title: '',
>         }}
>       />
>     </Stack.Navigator>
>   );
> }
> 
> homeStack.navigationOptions = ({navigation}) => {
>   let tabBarVisible = true;
>   console.log('navigation.state.routes[1].routeName', navigation);
>   if (
>     navigation.state.index > 0 &&
>     navigation.state.routes[1].routeName === 'Item'
>   ) {
>     tabBarVisible = false;
>   }
> 
>   return {
>     tabBarVisible,
>   };
> };
> ```

```
function homeStack({route, navigation}) {
  let tabBarVisible = true
  if (route.state.index > 0 && route.state.routes[1].name === "Item"){
    tabBarVisible = false
  }
  navigation.setOptions({
    tabBarVisible: tabBarVisible
  })

  return (
    <Stack.Navigator>
      <Stack.Screen
        name="Home"
        component={Home}
        options={{
          header: null,
        }}
      />

      <Stack.Screen
        name="Item"
        component={Item}
        options={{
          title: '',
        }}
      />
    </Stack.Navigator>
  );
}
```

This works for react-navigation v5

**Comment by FaysalBsata** [comment]
The flow goes like this
`import {
  getFocusedRouteNameFromRoute,
} from "@react-navigation/native";
<BottomTab.Navigator
      screenOptions={(props) => {
        console.log(getFocusedRouteNameFromRoute(props.route));
        return {
          tabBarActiveTintColor: Colors.Red,
          tabBarInactiveTintColor: Colors.Blue,
          headerShown: false,
          tabBarStyle: {
            display:
              getFocusedRouteNameFromRoute(props.route) === "ProdDetails"
                ? "none"
                : "flex",
          },
        };
      }}
    >
{...children}
</BottomTab.Navigator>
`
Cheers

**Comment by Aszurar** [comment]
> The recommended way is the following one:
> 
> > Another option here would be to add another stack navigator as a parent of the tab navigator, and put the details screen there. This is recommended.
> > ```js
> > const FeedStack = createStackNavigator({
> >   FeedHome: FeedScreen,
> >   /* any other route you want to render under the tab bar */
> > });
> > 
> > const TabNavigator = createBottomTabNavigator({
> >   Feed: FeedStack,
> >   Profile: ProfileScreen,
> > });
> > 
> > const HomeStack = createStackNavigator({
> >   Tabs: TabNavigator,
> >   Details: DetailsScreen,
> >   /* any other route you want to render above the tab bar */
> > });
> > 
> > const AppNavigator = createSwitchNavigator({
> >   Auth: AuthScreen,
> >   Home: HomeStack,
> > });
> > ```
> 
> Source: https://reactnavigation.org/docs/en/navigation-options-resolution.html#a-tab-navigator-contains-a-stack-and-you-want-to-hide-the-tab-bar-on-specific-screens

Thaaaaannnnnnkss!!! solved for meeee!!!
