### ISSUE TITLE
Screen Blinking/Flashing on tab change

### ISSUE THREAD

**Issue by magworkss** [react-navigation/react-navigation#7468]
Hello 

After replace
`import { createBottomTabNavigator } from 'react-navigation';` to 
`import { createMaterialBottomTabNavigator } from 'react-navigation-material-bottom-tabs';`
every time when on tab change event works my screen is flashing/blinking

[**Snack**](https://snack.expo.io/@avo/reactnavigation-issue)
https://snack.expo.io/@avo/reactnavigation-issue
@brentvatne 
Is there any solution ?

**Comment by FrancoMuniz** [comment]
> You can pass `sceneAnimationEnabled: false` to disable animation when switching tabs with latest react-native-paper.

Hello! Sorry to reopen this issue after almost a year.
I'm wondering what's the fix if I want the animation to be enabled. Been looking for a solution but can't seem to find any.

Any idea? My screen does the same thing, flashes and shows weird stuff (like only-shadows) from the previous screen when switching to a new one.

**Comment by eldirb21** [comment]
the reason " sceneAnimationEnabled={true}  "

**Comment by mandeep115** [comment]
Nesting tab navigator inside a drawer navigator solves the issue.

Also try setting `sceneAnimationEnabled={true}` or `false` in tab navigator (no nesting required)
