### ISSUE TITLE
change label size 

### ISSUE THREAD

**Issue by rodgomesc** [react-navigation/react-navigation#7475]
So, i needed to change a lebel size of the font, and I did not see anything about it on the docs,  `tabBarOptions `and `titleStyle `do not seem to work, i tried change te size in` barStyle`, too, but not work.

my code...

```
import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { Profile } from '../screens/'
import Icon from 'react-native-vector-icons/Ionicons'

import { createMaterialBottomTabNavigator } from 'react-navigation-material-bottom-tabs';

import { Financeiro,
          Historico,
          Boletim
      } from '../views'

const HomeNav = createMaterialBottomTabNavigator (
  {
  HistoricoScreen:{
    screen: Historico,
    navigationOptions:{
      title: 'Historico',
      
      tabBarIcon: ({ tintColor }) => (
        <Icon name='ios-settings' color={ tintColor } size={28} />
      )
    }
    
  },
    Financeiro,
    Boletim,
    
  },
  {
    labeled: true,
    initialRouteName: 'Boletim',
    activeTintColor: '#1b5dcb',
    inactiveTintColor: 'grey',
    barStyle: { 
      backgroundColor: '#fff',
 
     }, 
  }, 
)
export default HomeNav
```

**Comment by donni106** [comment]
@Kleinhummel 

it should work exactly as it does for `tabBarIcon`:

```
tabBarLabel: ({ focused }) => (<Text style={{ fontSize: 10, color: focused ? activeTintLabelColor : inactiveTintLabelColor }}> My Tickets </Text>),
```

**Comment by ajoykarmakar** [comment]
> That's more easy than you imagine.
> 
> Here some example:
> 
> ```
> const activeTintLabelColor = '#FF0000';
> const inactiveTintLabelColor = '#808080';
> 
> const TabPages = createMaterialBottomTabNavigator(
>   {
>     TabHome: {
>       screen: HomeStack,
>       navigationOptions: {
>         tabBarLabel: <Text style={{ fontSize: 10, color: activeTintLabelColor }}> My Tickets </Text>,
>         tabBarIcon: ({ focused }) => (
>           <MaterialCommunityIcons name='format-list-bulleted' color={focused ? activeTintLabelColor : inactiveTintLabelColor} size={24} />
>         )
>       }
>     },
>     TabFavorite: {
>       screen: FavoriteStack,
>       navigationOptions: {
>         tabBarLabel: <Text style={{ fontSize: 10, color: activeTintLabelColor }}> My Tickets </Text>,
>         tabBarIcon: ({ focused }) => (
>           <MaterialCommunityIcons name='format-list-bulleted-type' color={focused ? activeTintLabelColor : inactiveTintLabelColor} size={24} />
>         )
>       }
>     }
>   }, {
>     activeTintColor: activeTintLabelColor,
>     inactiveTintColor: inactiveTintLabelColor,
>     barStyle: {
>       backgroundColor: '#fff',
>     },
>     shifting: true
>   }
> );
> ```

It's works like a charm but If I want to apply  numberOfLines={1} props in text tag then it doesn't working, It's always shows in 2 lines. can anyone help me to figure out what I made mistake?
