### ISSUE TITLE
Material bottom tab doesn't render correctly on Android 8

### ISSUE THREAD

**Issue by ricogallo** [react-navigation/react-navigation#7482]
Hi, I tried to upload the code to reproduce the bug on Snack, but unfortunately, it won't resolve this repo as a dependency (yet). I will leave here the code and a screenshot of my device to show how it is rendered, the tab buttons seem shown only in half. It works perfectly fine on my iOs simulator. Thanks!

![2018-05-04 21 05 04](https://user-images.githubusercontent.com/1225753/39647355-e391005e-4fde-11e8-9803-7d78bc69ccbe.jpg)

---

```jsx
import React from 'react';
import { Text, View } from 'react-native';
import { createMaterialBottomTabNavigator } from 'react-navigation-material-bottom-tabs';

class HomeScreen extends React.Component {
  render() {
    return (
      <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
        <Text>Home!</Text>
      </View>
    );
  }
}

class SettingsScreen extends React.Component {
  render() {
    return (
      <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
        <Text>Settings!</Text>
      </View>
    );
  }
}

export default createMaterialBottomTabNavigator({
  Home: { screen: HomeScreen },
  Settings: { screen: SettingsScreen }
});
```

**Comment by hananfci** [comment]
> tabBarOptions is not working. i am unable to style

me too, how you solve this issue, please
