### ISSUE TITLE
Custom header component not working correctly

### ISSUE THREAD

**Issue by guistrutzki** [react-navigation/react-navigation#7483]
**Current Behavior**

I'm using trying to use custom header component, and my custom component has `position: absolute` and `color: transparent` in its style. Unfortunately sometimes the stack header get automatically height, and a white header stay stucked at the top of screen.

![Captura de Tela 2020-02-24 às 17 47 50](https://user-images.githubusercontent.com/41959250/75189837-d2ccbf80-572d-11ea-9d8e-495c0aca0341.png)

**Expected Behavior**

When I refresh state, or sometimes randomly my header has the expected behavior, so I dont know if it's a bug or something I am doing wrong.

![Captura de Tela 2020-02-24 às 17 49 10](https://user-images.githubusercontent.com/41959250/75189914-fd1e7d00-572d-11ea-9e89-966b58e14b07.png)

- What do you expect should be happening?

I'm using some navigators nested, like Drawer and BottomTab, maybe this be conflicting.

My code of TabContainer
![Captura de Tela 2020-02-24 às 17 54 03](https://user-images.githubusercontent.com/41959250/75190322-d14fc700-572e-11ea-915c-958f5ed24f45.png)

My helper to create stacks in each Tab
![Captura de Tela 2020-02-24 às 17 54 57](https://user-images.githubusercontent.com/41959250/75190326-d3198a80-572e-11ea-9cb2-75493f3c9da3.png)

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | iOS
| @react-navigation/native       | 5.0.3
| @react-navigation/stack        | ^5.0.3
| react-native-gesture-handler   | ^1.5.3
| react-native-safe-area-context | ^0.6.2
| react-native-screens           | ^2.0.0-alpha.27
| react-native                   | ^0.61.5
| node                           | v10.16.0
| npm or yarn                    | yarn

**Comment by satya164** [comment]
https://reactnavigation.org/docs/en/stack-navigator.html#headertransparent
https://reactnavigation.org/docs/en/stack-navigator.html#specify-a-height-in-headerstyle
