### ISSUE TITLE
switch navigator renders solid background on 'View"

### ISSUE THREAD

**Issue by ulisinn** [react-navigation/react-navigation#7484]
**Current Behavior**
        backgroundColor: colors.withAlpha(colors.black, 0.4),
renders as solid grey

**Expected Behavior**
style:
    overlayContainer: {
        position: 'absolute',
        backgroundColor: colors.withAlpha(colors.black, 0.4),
        minHeight: metrics.screenHeight * 3,
        minWidth: metrics.screenWidth,
        opacity: 0.4
    },

should render with alpha channel

this was after upgrade from v3.1 to v4.2.1
<img width="426" alt="Screen Shot 2020-02-24 at 14 09 29" src="https://user-images.githubusercontent.com/156169/75195719-51fecb00-570f-11ea-85f5-4bd76e005986.png">

**Comment by satya164** [comment]
Pass `cardStyle: { backgroundColor: 'transparent' }` in `defaultNavigationOptions` of your stack navigator.

**Comment by ulisinn** [comment]
does the switch navigator also have that option?

**Comment by dmitryshelomanov** [comment]
> does the switch navigator also have that option?

no, i could not to replace bg color in switch
