### ISSUE TITLE
[WEB] White screen after switching screens

### ISSUE THREAD

**Issue by coats707** [react-navigation/react-navigation#7485]
I'd just like to reopen issue [#127](https://github.com/react-navigation/drawer/issues/127#issue-509230623), since it was auto-closed. The original issue has a repo to reproduce it.

The issue can also be seen on [this snack](https://snack.expo.io/?platform=android&name=createDrawerNavigator%20%C2%B7%20React%20Navigation&dependencies=%40react-native-community%2Fmasked-view%40%5E0.1.1%2C%40react-navigation%2Fnative%40%5E5.0.1%2C%40react-navigation%2Fbottom-tabs%40%5E5.0.1%2C%40react-navigation%2Fdrawer%40%5E5.0.1%2C%40react-navigation%2Fmaterial-bottom-tabs%40%5E5.0.1%2C%40react-navigation%2Fmaterial-top-tabs%40%5E5.0.1%2C%40react-navigation%2Fnative-stack%40%5E5.0.1%2C%40react-navigation%2Fstack%40%5E5.0.1%2Creact-native-gesture-handler%401.5.2%2Creact-native-reanimated%401.4.0%2Creact-native-safe-area-context%400.6.0%2Creact-native-screens%402.0.0-alpha.12&sourceUrl=https%3A%2F%2Freactnavigation.org%2Fexamples%2F5.x%2Fsimple-drawer.js), from the createDrawerNavigator API Documentation.

**Comment by efichot** [comment]
Same with my drawer, blank screen when I comeback on a page already in the navigator. When I resize the screen turn back to normal. Work well on mobile

**Comment by hjpsievert** [comment]
I have the same problem where after opening drawer from entry screen and navigating to a screen, then returning to entry screen, it shows blank page in web, but works fine in mobile. Tried to build a snack, but it will not run, gives error, [snack here](https://snack.expo.io/@hjpsievert/drawer-navigation-web-issue)

```
Device: (856:881) Request failed with status 403: undefined
  Evaluating module://react-native-screens.js
```

This also happens with the snack provided by @coats707

**Comment by ngustavo** [comment]
Can confirm this on web. Works fine on Android (Expo).
I've got something like `stack(drawer(stack, tabs))`. When I move from first drawer screen (stack) to another drawer screen (tabs), it works fine. Though when I go back to the first drawer screen, it shows a blank screen. The thing is you can inspect the items on it as it was fully loaded, which is weird.

Using these versions:
```json
"@react-navigation/drawer": "^5.1.1",
"@react-navigation/material-top-tabs": "^5.1.2",
"@react-navigation/native": "^5.0.9",
"@react-navigation/stack": "^5.1.1",
"react-navigation": "^4.2.2",
```

**Comment by lovetofail** [comment]
I ended up rendering drawer items via drawerContent. And then manually doing "navigate" when drawer item clicked.
Inspired by https://github.com/callstack/react-native-paper/blob/master/example/src/index.tsx

My code
https://gist.github.com/lovetofail/fbc3827eb474199d9fbf7876c72eeb2d
https://gist.github.com/lovetofail/76f43a339786488bb3431723c8c446c8

**Comment by efichot** [comment]
That's work but that's not really the fix I want to use. :/

**Comment by efichot** [comment]
It's about the opacity who didn't comeback at 1 when you return on the same page.
Here's my fix: (I didn't try but maybe you can remove it entirely because the display change to flex to none already so I didn't understand why the opacity need to change also)
Anyway that works fine like this
```diff --git a/node_modules/@react-navigation/drawer/lib/module/views/DrawerView.js b/node_modules/@react-navigation/drawer/lib/module/views/DrawerView.js
index b24cbb4..03fc14e 100644
--- a/node_modules/@react-navigation/drawer/lib/module/views/DrawerView.js
+++ b/node_modules/@react-navigation/drawer/lib/module/views/DrawerView.js
@@ -160,7 +160,7 @@ export default function DrawerView(_ref2) {
       return React.createElement(ResourceSavingScene, {
         key: route.key,
         style: [StyleSheet.absoluteFill, {
-          opacity: isFocused ? 1 : 0
+          opacity: 1
         }],
         isVisible: isFocused
       }, descriptor.render());```
