### ISSUE TITLE
How can I dock the @react-navigation/drawer for large screens on the web ?

### ISSUE THREAD

**Issue by kopax** [react-navigation/react-navigation#7488]
How can I dock the menu on the left side when the **viewport width is greater than `800px`** such as in this [example](http://balloob.github.io/react-sidebar/example/) ?

![image](https://user-images.githubusercontent.com/1866564/75221920-83da6500-57d5-11ea-9a06-c33830de350a.png)

**Your Environment**

| software                     | version |
| ---------------------------- | ------- |
| iOS or Android               | web
| react-navigation             | 5
| react-navigation-drawer      | 5
| react-native-gesture-handler | 1.6.0
| react-native-reanimated      | 1.4.0
| react-native-screens         | 2.0.0-beta.7
| expo                         | sdk36
| node                         | 13
| npm or yarn                  | 6

**Comment by hosseinmd** [comment]
Solved to this pull Request https://github.com/react-navigation/react-navigation/pull/6871

**Comment by kopax** [comment]
This is awesome, unfortunately I am still using the alpha because of `jest-expo` not being fixed yet. But this is still just awesome.
