### ISSUE TITLE
Drawer sometimes doesn't close on stack navigator first mount

### ISSUE THREAD

**Issue by outaTiME** [react-navigation/react-navigation#7490]
Hi guys, 
I update the `react-navigation` and their dependencies to the latest versions and start with some wired problems (im using Expo 36 on managed workflow).

Sometimes the drawer not closed on initial mount of the stack navigator (if it is already mounted it closes correctly).

I leave you a video so you can see the behavior:

![Screen Recording 2020-02-04 at 20 24 57](https://user-images.githubusercontent.com/140472/73797040-b1f7f680-478d-11ea-9ed8-dfe0225b6b1d.gif)

Im creating the drawer in the following way (im using custom drawer also i tried to use the default drawer and the same effect):

```js
const MainDrawer = createDrawerNavigator(allowed_routes, {
  contentComponent: props => {
    return <Drawer {...props} />;
  },
  unmountInactiveRoutes: true,
});
```

My code is really complex to share entirety, but each `allowed_route` is created with the following code:

```js
createRoute(id, screens, params = {}) {
  const title = I18n.t(`${id}_module`);
  return {
    [id]: {
      screen: this.createModuleNavigator(title, screens, params),
      navigationOptions: ({ navigation }) => {
        // lock only when home
        let drawerLockMode = 'unlocked';
        if (navigation.state.index > 0) {
          drawerLockMode = 'locked-closed';
        }
        return {
          title,
          drawerIcon: ({ tintColor }) => {
            return this.getModuleIcon(id, {
              color: tintColor,
            });
          },
          drawerLockMode,
        };
      },
    },
  };
},
```

Any advice or feedback will be welcome, thanks !!!

**Comment by rafamrs** [comment]
This also happens to me. Any luck?

**Comment by rafmst** [comment]
@brentvatne @satya164 sorry for mentioning you guys, but this is really important for me. If you guys could spare a moment of your day, I would appreciate. Thank you

**Comment by abhip10** [comment]
having the same issue on expo 36, react navigation version 4

**Comment by cvvspb** [comment]
I have the same issue, and I'm not using expo

**Comment by cvvspb** [comment]
Well, I've been able to hunt it down further.

I've divided the screens into several stacks. My drawer config looks like this now:

> const DrawerNavigation = createDrawerNavigator(
	{
		TabNavigation: {
			screen: MainTabNavigationStack,
		},
		SettingsStack: {
			screen: SettingsStack,
		},
		AboutStack: {
			screen: AboutStack,
		},
		ProfileStack: {
			screen: ProfileStack,
		},
		DebugStack: {
			screen: DebugStack,
		},
	},
	{
		drawerWidth: styles.drawer.width,
		contentComponent: DrawerMenu,
		initialRouteName: 'TabNavigation',
	},
);

Navigation works OK for all the stacks except the ProfileStack
On the ProfileStack the first screen is Profile
In the Profile component I do this:

> componentDidMount() {
		this.props.navigation.setParams({ resetHandler: this.reset, backHandler: this.onBackAction });
		BackHandler.addEventListener('hardwareBackPress', this.onBackAction);
		this.props.dispatch(resetConnection());
		this.props.dispatch(resetErrorPerson());
	}

If I comment the line 
>this.props.navigation.setParams({ resetHandler: this.reset, backHandler: this.onBackAction });

the Drawer works OK
But I need to pass the component handlers to the header back button

**Comment by rafmst** [comment]
I think I have the solution for you @cvvspb, just try this in your constructor() function

```js
InteractionManager.runAfterInteractions(() => {
    this.props.navigation.setParams({ resetHandler: this.reset, backHandler: this.onBackAction });
})
```

If you're not familiar with InteractionManager you can check the [docs](https://reactnative.dev/docs/interactionmanager). I think this was what really solved it for me.

**Comment by cvvspb** [comment]
Thank you, @rafmst! That workaround actually does the trick.

**Comment by satya164** [comment]
Closing since a workaround is mentioned.

**Comment by outaTiME** [comment]
thanks @rafmst is works as expected, but still a workaround 😢 
@satya164 any real fix for that issue in your schedule? what is the real issue here? thanks !!!
