### ISSUE TITLE
Drawer navigation is visible when stack navigation is transitioning

### ISSUE THREAD

**Issue by deenMuhammad** [react-navigation/react-navigation#7495]
I am trying to build an app which has Drawer, Tab, and Stack navigation at the same time. 

`Drawer` navigation is the parent of both tab and stack navigation. 

while transitioning between stacks the drawer is slightly visible on header of the stack

I am posting the behavior image

![](https://res.cloudinary.com/ddjg5k4ul/image/upload/v1579660831/ezgif.com-video-to-gif__.gif)

**Comment by satya164** [comment]
Closing since you didn't fill the issue template. If you still have an issue, please fill all fields in the issue template and provide a minimal repro when opening an issue.
