### ISSUE TITLE
Is it possible to turn off the drawerBackground screen overlap

### ISSUE THREAD

**Issue by chervyakovru** [react-navigation/react-navigation#7497]
When open app on mobile i need to have a fully functional drawerNavigator (drawerType: front, and hide on swipe and on press on outside of screen close the drawer). But in tablet version i need to have always opened drawerNavigation with drawerType: slide and the same time have opportunity to press on current screen. How can i make it? 

mobile open
<img width="360" alt="New deal - Select supplier" src="https://user-images.githubusercontent.com/14909082/72505176-39260e80-3861-11ea-992b-aee849b52522.png">
<img width="360" alt="New deal - Select supplier (1)" src="https://user-images.githubusercontent.com/14909082/72506644-23661880-3864-11ea-9d03-b57321902a09.png">

**Expected Behavior**

- I expect that there is a solution that will make it possible to disable the substrate as an background view

**Your Environment**

"react-navigation": "4.0.10",
 "react-navigation-drawer": "2.3.2",
 "react-navigation-stack": "1.10.3",

**Comment by satya164** [comment]
`@react-navigation/drawer` in v5 has an option `drawerType: 'permanent'` to achieve this behaviour.
