### ISSUE TITLE
Mocking createDrawerNavigator with Jest

### ISSUE THREAD

**Issue by sentry0** [react-navigation/react-navigation#7503]
Does anyone have any idea how I would go about doing this?

Here is my react-navigation-drawer.js file under __mocks__:
```
jest.mock("react-navigation-drawer", () => {
  return {
    createDrawerNavigator: jest.fn().mockImplementation(nav => {
      return {};
    })
  }
});
```

Here is my transformIgnorePatters from package.json:
```
    "transformIgnorePatterns": [
      "node_modules/(?!(jest-)?react-native|react-navigation|@react-navigation/.*|react-navigation-drawer)"
    ]
```

When executing my tests I get this error:
```
Test suite failed to run

    TypeError: (0 , _reactNavigationDrawer.createDrawerNavigator) is not a function

      28 | // limitations under the License.
      29 | 
    > 30 | const AppNavigator = createDrawerNavigator({
```

**Comment by lucianomlima** [comment]
@sentry0 you resolved this?!

**Comment by sentry0** [comment]
No, I was unable to figure this one out.

**Comment by sammysium** [comment]
@sentry0 any feedback on that one?

**Comment by satya164** [comment]
You're mocking the full package, it's not any different than mocking any other package (you could call it `my-own-package` instead of `react-navigation-drawer` and it's the same) and not specific to React Navigation. Please ask the question on StackOverflow.
