### ISSUE TITLE
Navigation drawer not closing

### ISSUE THREAD

**Issue by RukshanWithanage** [react-navigation/react-navigation#7505]
Navigation drawer not closing properly. sometimes it closes and sometimes it is not. 

```
import { DrawerActions } from "react-navigation-drawer";

this.props.navigation.dispatch(DrawerActions.closeDrawer());
NavigationService.navigate('Home');
```

   
```
initialRouteName: 'Home',
    contentComponent: DrawerScreen,
    drawerWidth: deviceHeight * 0.35,
    drawerLockMode: 'locked-closed',
```

"react-native": "0.61.5",
"react-navigation": "^4.0.10",
"react-navigation-drawer": "^2.3.3",

**Comment by satya164** [comment]
Closing since you didn't provide a repro. If you have a minimal repro, feel free to open an issue.
