### ISSUE TITLE
Unable to programmatically open Drawer after setting drawerLockMode to locked-closed

### ISSUE THREAD

**Issue by DaniAkash** [react-navigation/react-navigation#7507]
## Issue

When the `drawerLockMode` of the navigator is set to `locked-closed` the drawer will stay closed and not respond to gestures and it'll only be opened programmatically as per this [documentation](https://facebook.github.io/react-native/docs/drawerlayoutandroid.html#drawerlockmode).

It worked properly on React navigation v3. However, on V4, I'm unable to open the drawer programmatically. The drawer is permanently closed.

---

### Current Behavior

The drawer is not opening programmatically.

### Expected Behavior

The drawer should open programmatically and should not respond to gestures.

### How to reproduce

Can be reproduced by running the app in this repository - https://github.com/DaniAkash/react-navigation-drawer-issue and clicking the "Open Drawer" button in the home screen.

Drawer lock mode is set in [App.js](https://github.com/DaniAkash/react-navigation-drawer-issue/blob/master/App.js#L20)

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 4.0.10
| react-native     | 0.61
| node             | 12.13.0
| npm or yarn      | 1.19.0

**Comment by punisher97** [comment]
> screenOptions={{ gestureEnabled: loginState }}

its ok, but to swipeClose not working

**Comment by satya164** [comment]
I believe this is fixed in latest version. Please open a new issue if you are having problems.
