### ISSUE TITLE
scale down the scene when drawer is opening

### ISSUE THREAD

**Issue by peyman-hakemi** [react-navigation/react-navigation#7513]
i want achieve this custom animation when drawer is opening. i wonder is there any way that i can do this with react-navigation-drawer?

[image of drawer animation](https://cloud.githubusercontent.com/assets/3721734/22906232/4c98dd34-f24c-11e6-931e-66a8c020e35d.gif)

i don't want to use any package for this because they all don't support the react navigation v4 but if you know there are a package that can do this and support react navigation  v4 please let me know.

thanks in advance.

**Comment by nishantWM** [comment]
I require the same animation. I think I can use the `progress` prop passed to the component in `drawerContent`. But I can't find a way to style the background for the whole navigator.

**Comment by nishantWM** [comment]
`export default navigator = () => {

    const [progress, setProgress] = useState(null);

    return (
        <Drawer.Navigator initialRouteName={Routes.Home}
                          sceneContainerStyle={progress ? {
                              transform: [
                                  {
                                      scale: Animated.interpolate(progress, {
                                          inputRange: [0, 1],
                                          outputRange: [1, 0.7],
                                      })
                                  },
                                  {
                                      translateX: Animated.interpolate(progress, {
                                          inputRange: [0, 1],
                                          outputRange: [0, ThemeUtils.relativeWidth(50)],
                                      })
                                  }

                              ]
                          } : null}
                          drawerStyle={{
                              backgroundColor: Color.PRIMARY,
                              width: 240,
                          }}
                          drawerContent={(props) =>
                              <AnimatedDrawer onChangeProgress={e => setProgress(e)}
                                              {...props}/>}
                          drawerType={'back'}>
            <Drawer.Screen name={Routes.Home}
                           component={Home}/>
            <Drawer.Screen name={Routes.Start}
                           component={Start}
            />
        </Drawer.Navigator>
    )
}`

**Comment by getumangon** [comment]
@nishantWM Did you got the result? if yes can you please guide me I am looking for the same kind of functionality. Thanks

**Comment by peyman-hakemi** [comment]
@getumangon @nishantWM  i found i solution with react navigation v5 this is the video that helped me.
[link to the video](https://www.youtube.com/watch?v=iD8N6cxyffw)

**Comment by getumangon** [comment]
@peyman-hakemi Thanks a lot! Saved my day.
