### ISSUE TITLE
drawer First load blink

### ISSUE THREAD

**Issue by max-end** [react-navigation/react-navigation#7515]
drawer content Priority display，cause First load blink
I recorded a video, [click on me to check](https://dwz.cn/Hn5zB1l5)

demo:
my package.json
`{
  "name": "example",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "react": "16.9.0",
    "react-native": "0.61.3",
    "react-native-gesture-handler": "^1.5.0",
    "react-native-reanimated": "^1.3.2",
    "react-native-screens": "^1.0.0-alpha.23",
    "react-navigation": "^4.0.10",
    "react-navigation-drawer": "^2.3.3"
  },
  "devDependencies": {
    "@babel/core": "^7.6.4",
    "@babel/runtime": "^7.6.3",
    "@react-native-community/eslint-config": "^0.0.5",
    "babel-jest": "^24.9.0",
    "eslint": "^6.6.0",
    "jest": "^24.9.0",
    "metro-react-native-babel-preset": "^0.56.3",
    "react-test-renderer": "16.9.0"
  },
  "jest": {
    "preset": "react-native"
  }
}`

App.js

`/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 *
 * @format
 * @flow
 */

import React from 'react';
import {Text, View} from 'react-native';
import {createAppContainer} from 'react-navigation';
import {createDrawerNavigator} from 'react-navigation-drawer';

class Hello extends React.Component {
  render() {
    return (
      <View>
        <Text>hello</Text>
      </View>
    );
  }
}

const App = createAppContainer(
  createDrawerNavigator(
    {
      Hello,
    },
    {
      drawerBackgroundColor: 'blue',
    },
  ),
);
export default App;`

**Comment by theristes** [comment]
I'm not proud of my solution but what I did was set a state for drawerType as a back, and before calls openDrawer I change it for what I want and works fine. I'm using hooks btw

**Comment by amit13091992** [comment]
I have added code like this:
const Drawer = createDrawerNavigator(
    {
        Main: MainNavigator
    },
    {
        drawerPosition: 'right',
        drawerWidth: 290,
        contentComponent: DrawerContainer,
        **drawerType: 'slide'**   //this line I have added
    }
);

I have added drawerType and this issue gets resolved.
App configuration:
    "react": "16.11.0",
    "react-native": "0.62.1"

**Comment by Fernando922** [comment]
> I have added code like this: added drawerType and this _issue gets resolved_.
> 
> ```
> const Drawer = createDrawerNavigator(
>     {
>         Main: MainNavigator
>     },
>     {
>         drawerPosition: 'right',
>         drawerWidth: 290,
>         contentComponent: DrawerContainer,
>         drawerType: 'slide'   //this line I have added
>     }
> );
> ```
> 
> App configuration:
> 
> ```
>     "react": "16.11.0",
>     "react-native": "0.62.1"
> ```

in my case drawerType='back' solved

**Comment by naxir** [comment]
<Drawer.Navigator
      minSwipeDistance={100}
      drawerType={'front'}
      drawerStyle={{width: Dimension(250)}}
      drawerContent={(props) => <DrawerScreen {...props} />}
      drawerPosition="right"
      initialRouteName="profile">
      <Drawer.Screen name={'profile'} component={Profile} />
      <Stack.Screen
        options={{gestureEnabled: false}}
        name={'PrivacyPolicy'}
        component={PrivacyPolicy}
      />
    </Drawer.Navigator>

on First load it's blink 
"react-native": "0.63.1",
React Navigation V5
When i change from front to back then it's not blink 
I want back behaviour with no Blink any work around on this?

**Comment by Megha060199** [comment]
Any solutions on this ?
