### ISSUE TITLE
App crashes in Release apk

### ISSUE THREAD

**Issue by kumaresan-cgvak** [react-navigation/react-navigation#7518]
The app crashes whenever I try to open the side menu in release APK after updating to the version 2.3.1. But it's working fine on debug mode.

**Comment by ketanvault** [comment]
Experiencing the same issue on latest library

"dependencies": {
"@react-native-community/async-storage": "^1.9.0",
"@react-native-community/geolocation": "^2.0.2",
"@react-native-community/masked-view": "^0.1.10",
"@react-navigation/bottom-tabs": "^5.3.4",
"@react-navigation/drawer": "^5.6.4",
"@react-navigation/native": "^5.2.4",
"@react-navigation/stack": "^5.2.19",
"formik": "^2.1.4",
"moment": "^2.24.0",
"react": "16.11.0",
"react-native": "0.62.0",
"react-native-android-location-enabler": "^1.2.1",
"react-native-background-fetch": "^3.0.4",
"react-native-button": "^3.0.1",
"react-native-camera": "^3.22.0",
"react-native-fast-image": "^8.1.5",
"react-native-gesture-handler": "^1.6.1",
"react-native-permissions": "^2.0.10",
"react-native-qrcode-scanner": "^1.4.0",
"react-native-reanimated": "^1.8.0",
"react-native-safe-area-context": "^0.7.3",
"react-native-screens": "^2.7.0",
"react-native-sqlite-storage": "^5.0.0",
"react-native-vector-icons": "^6.6.0",
"react-navigation-redux-helpers": "^4.0.1",
"react-redux": "^7.2.0",
"redux": "^4.0.5",
"yup": "^0.28.3"
},
"devDependencies": {
"@babel/core": "^7.9.0",
"@babel/runtime": "^7.9.2",
"@react-native-community/eslint-config": "^1.0.0",
"babel-jest": "^25.2.4",
"eslint": "^6.8.0",
"jest": "^25.2.4",
"metro-react-native-babel-preset": "^0.59.0",
"react-test-renderer": "16.11.0"
},
"jest": {
"preset": "react-native"
}

I followed each instruction set by react-navigation in it's docs. Added 'react-native-gesture-handler' library at the top. Still getting the same issue.

Please help me on this.

**Comment by raajnadar** [comment]
But you forgot to clear the cache `npx react-native run-android`

**Comment by muganwas** [comment]
> 2\. import 'react-native-gesture-handler'

This worked for me, thanks!!
