### ISSUE TITLE
Crash prod app after click outside drawer

### ISSUE THREAD

**Issue by TchernyavskyDaniil** [react-navigation/react-navigation#7525]
Hi. 
After clicking this area, the prod app crashed and I don't know why, because in the dev is ok.
Some ideas? 
![image](https://user-images.githubusercontent.com/29048318/66434035-52314f00-ea2a-11e9-8f78-3b1e2164b757.png)

IOS 13 (btw same crash with Android)

**Comment by ggdegreat** [comment]
Just update `react-native-gesture-handler` to version `1.5.2`
