### ISSUE TITLE
App crashed in release mode in react-native 0.61.2

### ISSUE THREAD

**Issue by ajaykumar97** [react-navigation/react-navigation#7529]
I am using react-navigation-drawer in my application. App works fine in debug mode. But the app crashes in release mode as soon as I try to open the drawer with swipe gesture in Android.

Also tried by downgrading the drawer to the ``version 1.4.0`` but with no success.

Below is the link for the code repo

[Drawer Test](https://github.com/ajaykumar97/drawerTest)

```
"react-native": 0.61.2
"react-native-gesture-handler": "^1.4.1",
"react-native-reanimated": "^1.3.0",
"react-native-screens": "^2.0.0-alpha.3",
"react-navigation": "^4.0.10",
"react-navigation-drawer": "2.2.2",
"react-navigation-stack": "^1.9.3"
```

**Comment by mohamadnabikhani** [comment]
I had no problem on thiese version
`
"react-native": "0.62.2",
"react-native-gesture-handler": "^1.6.1",
`
but when upgraded to these

`
"react-native": "0.63.2",
"react-native-gesture-handler": "1.7.0",
`
I encounter this error, and have no idea why? 
the app worked in debug mode well, but in non-debug mode, when I logged in and so when I want to go in MainNavigator screen, the app will be crashed
```
function App(props) {
  return (
    <NavigationContainer>
      <AppStack.Navigator 
      initialRouteName="Splash"
      headerMode="none"
      >
      { props.isSplash &&

      	<AppStack.Screen 
    		name="Splash"
    		component={SplashScreen}
    	/>
      }

      { (
      	props.isAuthenticated) &&
      	<AppStack.Screen
   			name="Main"
   			component={MainNavigator}
   		/>

      }

      { (
      	!props.isAuthenticated) &&
      	<AppStack.Screen 
    		name="Auth"
    		component={AuthNavigator}
    	/>

      }
      </AppStack.Navigator>
    </NavigationContainer>
  );
}
```
