### ISSUE TITLE
Annoying Drawer Border on Android

### ISSUE THREAD

**Issue by binodnp** [react-navigation/react-navigation#7532]
It appears that react navigation drawer was not tested for dark theme(s) as you can see weird border blinks in the the video below.

![react-navigation-drawer](https://user-images.githubusercontent.com/5472889/65834459-f1ec3000-e2fa-11e9-9263-77030df10c1c.gif)

Here's a code snippet to reproduce this issue:

```js
import React from 'react';
import {Text, View, StatusBar, StyleSheet, Button} from 'react-native';
import {createDrawerNavigator} from 'react-navigation-drawer';
import {createStackNavigator} from 'react-navigation-stack';
import {createAppContainer} from 'react-navigation';

const Sidebar = ({navigation}) => (
  <View style={styles.container}>
    <Text style={styles.text}>Sidebar</Text>
    <Button title="Close Sidebar" onPress={() => navigation.closeDrawer()} />
  </View>
);

const Home = ({navigation}) => {
  return (
    <View style={styles.container}>
      <Button title="Open Sidebar" onPress={() => navigation.openDrawer()} />
    </View>
  );
};

const Routes = createStackNavigator({Home: {screen: Home}}, {mode: 'card', headerMode: 'none'});

const Drawer = createDrawerNavigator(
  {DefaultRoutes: Routes},
  {
    contentComponent: Sidebar,
    drawerType: 'slide',
    drawerWidth: 300,
  },
);

const AppContainer = createAppContainer(Drawer);

const App = () => {
  return (
    <>
      <StatusBar backgroundColor="#121212" barStyle="light-content" />
      <AppContainer />
    </>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#121212',
  },
  text: {
    fontSize: 18,
    color: '#eeeeee',
    marginBottom: 14,
  },
});

export default App;
```

and a gist:

https://gist.github.com/binodnp/1f28059e6013ab17f5cb7d3867ceed8a

Is there any workaround for this?

**Comment by Nantris** [comment]
Is there no way to resolve this without using `drawerType="back"`? We'd like a traditional drawer, but we'd also like not to have this hairline white border over a black background.

**Comment by Nantris** [comment]
Good find @Ali72. Unfortunately we need it to not show over a black screen shown in our light mode, so that leaves us having to try to imperatively change the background of the navigator on the fly, which is sort of insane. 

It would be so much better if this border simply didn't appear, and this issue really shouldn't be closed.

@satya164, sorry for the ping but the bot says no-one will see this issue otherwise - is there any way to achieve this or any interest in resolving this issue?

**Comment by Nantris** [comment]
Friendly bump. This little thing makes for a big UI headache and really reduces the apparent quality of the app.
