### ISSUE TITLE
Can not open / close drawer with swipe gesture

### ISSUE THREAD

**Issue by muraterd** [react-navigation/react-navigation#7536]
I can open drawer with _**this.props.navigation.openDrawer()**_ but can not open or close with swipe gesture. What am i doing wrong here?

App.js
```
import React from 'react';
import {Button} from 'react-native';

import {createDrawerNavigator} from 'react-navigation-drawer';
import {createAppContainer} from 'react-navigation';

class MyHomeScreen extends React.Component {
  render() {
    return (
      <>
        <Button
          onPress={() => this.props.navigation.navigate('Notifications')}
          title="Go to notifications"
        />

        <Button
          onPress={() => this.props.navigation.openDrawer()}
          title="Drawer"
        />
      </>
    );
  }
}

class MyNotificationsScreen extends React.Component {
  render() {
    return (
      <Button
        onPress={() => this.props.navigation.goBack()}
        title="Go back home"
      />
    );
  }
}

const MyDrawerNavigator = createDrawerNavigator(
  {
    Home: {
      screen: MyHomeScreen,
    },
    Notifications: {
      screen: MyNotificationsScreen,
    },
  },
  {
    drawerLockMode: 'unlocked',
  },
);

export default createAppContainer(MyDrawerNavigator);

```

dependencies
```
"dependencies": {
    "react": "16.8.1",
    "react-native": "0.61.0-rc.3",
    "react-native-gesture-handler": "^1.4.1",
    "react-native-reanimated": "^1.2.0",
    "react-native-screens": "^2.0.0-alpha.3",
    "react-navigation": "^4.0.5",
    "react-navigation-drawer": "^2.2.1",
    "react-navigation-stack": "^1.7.3"
  },
```

And i did the MainActivity setup
```
import com.facebook.react.ReactActivityDelegate;
import com.facebook.react.ReactRootView;
import com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView;
...
...
...
@Override
  protected ReactActivityDelegate createReactActivityDelegate() {
    return new ReactActivityDelegate(this, getMainComponentName()) {
      @Override
      protected ReactRootView createRootView() {
      return new RNGestureHandlerEnabledRootView(MainActivity.this);
      }
    };
  }
```

**Comment by Maskedman99** [comment]
react native: 0.62.2
react-native-gesture-handler: 1.6.1
This Issue is still present. https://github.com/react-navigation/react-navigation/issues/7536#issuecomment-540667009 workaround works. 
This should be mentioned in the docs of RNGesturehandler's Drawer Layout https://docs.swmansion.com/react-native-gesture-handler/docs/component-drawer-layout.html

**Comment by sleez007** [comment]
I am also having this issue on rn 0.63.3. Gesture doesn't work on Android

**Comment by sandipbiswasbehala** [comment]
I am also having this issue on react-native: 0.63.4. Gesture doesn't work on Android.

**Comment by sandipbiswasbehala** [comment]
Solution Found and Working in Android (by following https://docs.swmansion.com/react-native-gesture-handler/docs/#with-wixreact-native-navigation)

Update your MainActivity.java file

import com.facebook.react.ReactActivity;
+ import com.facebook.react.ReactActivityDelegate;
+ import com.facebook.react.ReactRootView;
+ import com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView;
public class MainActivity extends ReactActivity {

  @Override
  protected String getMainComponentName() {
    return "Example";
  }
+  @Override
+  protected ReactActivityDelegate createReactActivityDelegate() {
+    return new ReactActivityDelegate(this, getMainComponentName()) {
+      @Override
+      protected ReactRootView createRootView() {
+       return new RNGestureHandlerEnabledRootView(MainActivity.this);
+      }
+    };
+  }
}

+ ---> need to add

For React Native 0.61 or greater, add the library as the first import in your index.js file:

import 'react-native-gesture-handler';


Before running apps--- clean using gradlew clean command .

then npx react-native run-android.

Just tested.

**Comment by parnekov** [comment]
> I had the same problem and solved it by importing **react-native-gesture-handler** in the root of the project:
> 
> `import 'react-native-gesture-handler';`

Worked fine on iOS and Android. Thank you.

**Comment by SvrMihir** [comment]
> I resolved !!!
> 
> in the index.js of your project:
> 
> ```
> import {AppRegistry} from 'react-native';
> import App from './App';
> import {name as appName} from './app.json';
> import { gestureHandlerRootHOC } from 'react-native-gesture-handler'
> 
> AppRegistry.registerComponent(appName, () => gestureHandlerRootHOC(App));
> ```
> 
> Works in debug, not testing in release mode.

not worked for me 🙃.
