### ISSUE TITLE
swipe to back inside drawer

### ISSUE THREAD

**Issue by diego-lipinski-de-castro** [react-navigation/react-navigation#7578]
Is there anyway to enable swipe to go back inside a drawer navigation? I wrapped my app around a drawer navigation and in just one screen I want that when i swipe from left to right it goes back, thats how most apps work on iOS, but i couldnt figure out how to do that, btw i know i can change drawerLockMode to lock the drawer from opening, but I wasnt able to go back on swipe yet

**Comment by AndriyBroda** [comment]
> Hi @diego-lipinski-de-castro,
> 
> you can do this https://reactnavigation.org/docs/en/navigation-options-resolution.html#a-drawer-has-a-stack-inside-of-it-and-you-want-to-lock-the-drawer-on-certain-screens

How can it be done with a version of react-navigation 5+?
Back button on Android goes back in drawer navigation. 
But on IOS swipe back gesture doesn't go back, just stays on the current screen. Is there any solution to this problem?

**Comment by ShuminY** [comment]
> > Hi [@diego-lipinski-de-castro](https://github.com/diego-lipinski-de-castro),
> > you can do this https://reactnavigation.org/docs/en/navigation-options-resolution.html#a-drawer-has-a-stack-inside-of-it-and-you-want-to-lock-the-drawer-on-certain-screens
> 
> How can it be done with a version of react-navigation 5+? Back button on Android goes back in drawer navigation. But on IOS swipe back gesture doesn't go back, just stays on the current screen. Is there any solution to this problem?

Hi @AndriyBroda, I am trying to figure out this same issue. Did you get any ideas/solutions?

**Comment by ShuminY** [comment]
> Hi [@diego-lipinski-de-castro](https://github.com/diego-lipinski-de-castro),
> 
> you can do this https://reactnavigation.org/docs/en/navigation-options-resolution.html#a-drawer-has-a-stack-inside-of-it-and-you-want-to-lock-the-drawer-on-certain-screens

Hi @eriveltonelias,  this link won't opens a "Page Not Found" page. Anywhere else could I find it?

**Comment by ShuminY** [comment]
Hi @diego-lipinski-de-castro , have you got the answer for this question? I have this same scenario to resolve. Really appreciate it if you could share the solution.
