### ISSUE TITLE
drawerLockMode not supported

### ISSUE THREAD

**Issue by tonyxiao** [react-navigation/react-navigation#7582]
According to the latest 3.0 documentation, drawerLockMode is still [documented as supported](https://reactnavigation.org/docs/en/drawer-navigator.html#drawerlockmode) when in fact [it is not](https://github.com/react-navigation/react-navigation-drawer/blob/master/src/views/DrawerLayout.js#L57). We should either update the docs or update the source code to actually support it. And this should also be documented as a breaking change in the release notes (actually happened as of `react-navigation-drawer` version 0.5.0 which was part of react-navigation 2.x)

**Comment by slolkunchik** [comment]
> ({ navigation }: { navigation: any }) => ({
>       drawerLockMode: navigation.state.index > 0 ? 'locked-closed' : 'unlocked',
>     })

you can use NavigationDrawerProp instead of any

**Comment by anwar-kt** [comment]
this is working for me, add 'drawerLockMode' inside  'createDrawerNavigator' 
 
![image](https://user-images.githubusercontent.com/71360450/102683262-8ccd7480-41f5-11eb-930a-0bc45026174f.png)
