### ISSUE TITLE
A way to navigate to the last dynamically created tab. 

### ISSUE THREAD

**Issue by panda0603** [react-navigation/react-navigation#7611]
Using react navigation v5, I am currently using dynamic bottom tab navigator, to add and remove tabs on a button press. Tab navigator and stack navigator is nested as follows: 

```

function RootStack({id}) {
  return (
    <Stack.Navigator headerMode="none">
      <Stack.Screen name={`Fav-${id}`}>
        {props => <Favourites {...props} id={id} />}
      </Stack.Screen>
      ...
    </Stack.Navigator>
  );
}

<Tab.Navigator tabBar={() => null}>
        {tabArray.map(data => {
          return (
            <Tab.Screen name={data.id} key={data.id}>
              {props => <RootStack {...props} id={data.id} />}
            </Tab.Screen>
          );
        })}
</Tab.Navigator>
```

upon pushing an item in tabArray, a tab is successfully dynamically created. However, the focus automatically goes to the first item in the array every time I push a new item. 

**What I would like to do is to automatically focus to the last tab added to the array.** 

I have tried following: 

```
      tabArray.push({       // on button click to create new tab
        id: UID,
      });
    this.props.navigation.navigate(UID); // after pushing, navigate to the created item. 
```

However, above doesn't work as it says it cannot handle navigate function. I guess navigation.navigate is executed too fast before new tab is rendered. 

Any way to automatically focus to the last pushed tab? 

Thanks

**Comment by satya164** [comment]
You can do the navigation in `useEffect`/`componentDidUpdate`. If your `tabArray` contains the list of tabs:

```js
React.useEffect(() => {
  navigation.navigate(tabArray[tabArray.length - 1].id);
}, [navigation, tabArray]);
```

Also note that you shouldn't mutate the `tabArray` by calling `tabArray.push`. Instead, create a new array by spreading it `[...tabArray, { id: UID }]` and call `setState` to update it.

**Comment by panda0603** [comment]
@satya164 thanks. Above code works, though sometimes it shows first item for very short time then navigates to the last item. It seems like navigation happens after the re-render of the new array. Any way to prevent the behavior? Thanks

**Comment by satya164** [comment]
Try using `useLayoutEffect` instead of `useEffect`
