### ISSUE TITLE
StatusBar - TabNavigator Improvements

### ISSUE THREAD

**Issue by export-mike** [react-navigation/react-navigation#7618]
Hey,

so I've just noticed the limitation with StatusBar on TabNavigation where props such as barStyle etc do not change due to routes being mounted previously.

noticed this doc: https://reactnavigation.org/docs/en/status-bar.html#tabnavigator to help with this scenario, which helped me fix the issue,

I've since wrapped this up into a component, we're now using this on a small app, and works well. We could export it as a StatusBar wrapper for react-navigation.

it would look something like this.

```js
import React from 'react'
import {NavigationEvents} from '@react-navigation/core'
import {StatusBar as RNStatusBar} from 'react-native'

export default function StatusBar(props) {
  return <>
    <NavigationEvents onDidFocus={() => {
      if (props.barStyle) {
        RNStatusBar.setBarStyle(props.barStyle);
      }
      if (props.backgroundColor) {
        RNStatusBar.setBackgroundColor(props.backgroundColor);
      }
      if (props.hidden) {
        RNStatusBar.setHidden(props.hidden);
      }
      if (props.networkActivityIndicatorVisible) {
        RNStatusBar.setNetworkActivityIndicatorVisible(props.networkActivityIndicatorVisible);
      }
      if (props.translucent) {
        RNStatusBar.setTranslucent(props.translucent);
      }
    }} />
  </>
}
```

thoughts, feedback, worth a PR?

**Comment by satya164** [comment]
I think the following works well:

```js
const isFocused = useIsFocused()

isFocused & <StatusBar .... />
```

The hook is available in core in v5 and in https://github.com/react-navigation/hooks in v4. There's also `withNavigationFocus` in v4.
