### ISSUE TITLE
Async Storage has been extracted from react-native core

### ISSUE THREAD

**Issue by sulaysumaria** [react-navigation/react-navigation#7622]
Warning: Async Storage has been extracted from react-native core and will be removed in a future release. It can now be installed and imported from '@react-native-community/async-storage' instead of 'react-native'. See https://github.com/react-native-community/react-native-async-storage

**Comment by rishisingh-dev** [comment]
I'm importing AsyncStorage correctly, but still getting it.

```
import AsyncStorage from '@react-native-community/async-storage';
```

![Screen Shot 2020-07-11 at 7 38 54 AM](https://user-images.githubusercontent.com/56976320/87226582-98189c00-c349-11ea-9832-5400c1e78c2b.png)
```
"@react-native-community/async-storage": "^1.11.0",
"react": "^16.13.1",
"react-native": "^0.63.0",
```

How can I fix this problem?

**Comment by hpelitebook745G2** [comment]
> I'm importing AsyncStorage correctly, but still getting it.
> 
> ```
> import AsyncStorage from '@react-native-community/async-storage';
> ```
> 
> ![Screen Shot 2020-07-11 at 7 38 54 AM](https://user-images.githubusercontent.com/56976320/87226582-98189c00-c349-11ea-9832-5400c1e78c2b.png)
> 
> ```
> "@react-native-community/async-storage": "^1.11.0",
> "react": "^16.13.1",
> "react-native": "^0.63.0",
> ```
> 
> How can I fix this problem?

Any updates @rishisingh-dev ?

**Comment by haveamission** [comment]
@rishisingh-dev Did you find a solution?
