### ISSUE TITLE
[Bug] Unexpected behavior of focus events

### ISSUE THREAD

**Issue by isnifer** [react-navigation/react-navigation#7628]
Hey! I found several issues in different repos about focus events. Tried to find a root problem.
I didn't find it, but I have logged one line for the file https://github.com/react-navigation/core/blob/master/src/getChildEventSubscriber.js#L51
```js
console.log(`${key}:${type}`) // This is my log handler
```
Also, I've recorded my pet-app with this log to show you a problem.
![react-navigation_focus_error](https://user-images.githubusercontent.com/1788245/73615475-1e051e00-4619-11ea-9081-b84171c70014.gif)

For me, it looks like navigator at some moment loose children navigators or something else.
I don't know. Hope, it'll help anyway.

I have configured my routes following documentation — https://github.com/isnifer/food/blob/master/src/screens/index.js

**Comment by OscarYuen** [comment]
meet this issue in navigation 4 

"react-navigation": "^4.1.1",
"react-navigation-stack": "^2.1.1",
"react-navigation-tabs": "^2.7.0",

**Comment by satya164** [comment]
I've reworked the event system which should fix the issue. Please upgrade `react-navigation` to `4.3.4` and `react-navigation-stack` to `2.3.8` and give it a try.
