### ISSUE TITLE
Memoize navigation action functions

### ISSUE THREAD

**Issue by slorber** [react-navigation/react-navigation#7631]
Related to this hooks issue: https://github.com/react-navigation/hooks/issues/3#issuecomment-524176110

People are trying to use the navigate() function in useEffect, and try to comply to eslint dependency rules, unfortunately the navigation function provided by the NavigationContext changes often, and lead to unwanted effect re-executions on each screen change.

```
function ReactComponent() {
  const {navigate} = useNavigation();

  useEffect(() => {
      if (user) {
          navigate(...)
      }
  }, [user, navigate])

 return null
}
```

Not sure exactly how to fix this, but it would be nice if the navigation actions would be memoized to avoid being recreated.

Could it make sense to cache per route key the result of `getNavigationActionCreators` / `router.getActionCreators` ?

https://github.com/react-navigation/core/blob/e514a61f9314e8d771231de9d3a4ebf64f661003/src/getNavigation.js#L46
https://github.com/react-navigation/core/blob/e514a61f9314e8d771231de9d3a4ebf64f661003/src/routers/getNavigationActionCreators.js

**Comment by manulera** [comment]
For those stumbling with this in future versions, I resorted to adding a custom hook.

```jsx
import React from 'react';
import { useNavigate } from 'react-router-dom';

/**
 * This hook is used to create a stable navigate function that is not affected by re-renders.
 * It is used to avoid issues with the navigation function being updated and causing the app to navigate to the wrong page.
 * @returns {function} A stable navigate function.
 */
export default function useStableNavigate() {
  const navigate = useNavigate();
  const navigateRef = React.useRef(navigate);

  React.useLayoutEffect(() => {
    navigateRef.current = navigate;
  }, [navigate]);

  return React.useCallback((...args) => {
    navigateRef.current(...args);
  }, []);
}

```
