### ISSUE TITLE
[Umbrella] TypeScript migration

### ISSUE THREAD

**Issue by satya164** [react-navigation/react-navigation#7634]
- [ ] Remove `invariant` - TS doesn't play well with it, and this FB-specific pattern makes code less straightforward for OSS
- [ ] Migrate `utils`
- [ ] Migrate `routers`
- [ ] Migrate top-level files
- [ ] Migrate `views`
- [ ] Migrate `navigators`
- [ ] Migrate `__tests__`

**Comment by eriveltonelias** [comment]
Hey @satya164, 

should we close this?
