### ISSUE TITLE
activekey doesn't work for nested routers

### ISSUE THREAD

**Issue by sirpy** [react-navigation/react-navigation#7641]
i'm using core+web.
I have nested routes, when I try to go to a 3rd level route
such as AppNavigation/Dashboard/Claim the navigation state is only set until Dashboard

![image](https://user-images.githubusercontent.com/671095/53020614-f5176780-345f-11e9-8904-c7062378c507.png)

you can see that first route has index set to 4 (AppNavigation) then it has index set to 2 (Dashboard) but the Dashboard route index is set to =0 (Dashboard again)

It also causes navigating to 'Dashboard' show the url as AppNavigation/Dashboard/Dashboard

**Comment by satya164** [comment]
Closing due to no response.
