### ISSUE TITLE
SwitchRouter returns null if navigating twice to same route?

### ISSUE THREAD

**Issue by slorber** [react-navigation/react-navigation#7644]
There is a thing I did not really understand when rewriting some tests. It looks like when we try to navigate again to the same route as before, the router does return "null". Is it the way to tell the user the state is unchanged?

I would rather recommend to just return the user-provided state in such case. User would still be able to detect a change by using identity comparison if needed, and I think it's be safer and less error-prone.

I'd like the following test to pass. Currently it does not because `getState()` returns null the 2nd time, because I did not handle null returns in `getRouterTestHelper`, which I could support there)

```js
  test('can navigate twice to same route', () => {
    const { navigateTo, getState } = getRouterTestHelper(getExampleRouter());

    navigateTo('B');
    expect(getState().index).toEqual(1);

    navigateTo('B');
    expect(getState().index).toEqual(1);
  });
```

Whatever the choice, I think this specific case should be covered in tests (currently it seems it's not) because this can be a breaking change if modified for users of router.getStateForAction

**Comment by satya164** [comment]
AFAIK `null` is returned to signal that the router didn't handle the action. I think closing this behaviour now would be a breaking change and probably break other stuff. Closing since v4 is only supposed to receive bug fixes for now.
