### ISSUE TITLE
Reconsider state.isTransitioning and completeTransition action

### ISSUE THREAD

**Issue by ericvicenti** [react-navigation/react-navigation#7655]
I think the "complete transition" action may have been a bad move. Storing isTransitioning in navigation state means extra unnecessary state changes, and the event system is very confusing because of it. Also it encourages people to use the action to configure the transition (eg, the "immediate" flag), rather than declaratively configuring the transition on the screen itself.

Instead, a navigator could fire a callback inside the navigation prop while a state change is happening, to register that a longer transition is in progress, and the event system can fire didFocus/blur actions when the transition completes. If the navigator doesn't call this hook, then the transition completes immediately.

Opening this here to start a discussion and to see if others agree

**Comment by satya164** [comment]
I'm closing this since we've rewritten this in v5 and probably better to avoid breaking changes in v4.
