### ISSUE TITLE
Error with basic Stack Navigator example

### ISSUE THREAD

**Issue by MislavPeric** [react-navigation/react-navigation#7658]
**Current Behavior**
Upon running the program with Expo on my phone (Samsung S9, Android 10) the program errors out with `'TypeError: (0, _native.createNavigatorFactory) is not a function. (In'(0,_native.createNavigatorFactory)(StackNavigator)','(0,_native.createNavigatorFactory)' is undefined)`
![87951395_196350688246658_5497378845470228480_n](https://user-images.githubusercontent.com/23200555/75244057-52f53280-57cb-11ea-9fcf-c295f2a75975.jpg)
Using web view a different error pops up:
`TypeError: Object(...) is not a function
Module.D:\Projects\again\node_modules\@react-navigation\stack\lib\module\navigators\createStackNavigator.js`

**Expected Behavior**

The application compiles properly and the navigation works

**How to reproduce**
Run the program using Expo

**Code**
The entire program can be found in this https://github.com/MislavPeric/react-native-mob repo

**Info about the env**
Windows 10 Education x64
Samsung S9 Android 10

Visual Code Studio 1.42.1.
Node Version v12.14.1

**Dependencies**

"@react-native-community/masked-view": "0.1.5",
    "@react-navigation/bottom-tabs": "^5.0.0-alpha.32",
    "@react-navigation/compat": "^5.0.0-alpha.21",
    "@react-navigation/core": "github:react-navigation/core",
    "@react-navigation/drawer": "^5.0.0-alpha.34",
    "@react-navigation/material-bottom-tabs": "^5.0.0-alpha.29",
    "@react-navigation/material-top-tabs": "^5.0.0-alpha.27",
    "@react-navigation/native": "^3.7.3",
    "@react-navigation/native-stack": "^5.0.0-alpha.22",
    "@react-navigation/routers": "^5.0.0-alpha.20",
    "@react-navigation/stack": "^5.0.0-alpha.51",
    "expo": "~36.0.0",
    "react": "~16.9.0",
    "react-dom": "~16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz",
    "react-native-gesture-handler": "~1.5.0",
    "react-native-navigation": "^6.0.1",
    "react-native-reanimated": "~1.4.0",
    "react-native-safe-area-context": "0.6.0",
    "react-native-screens": "2.0.0-alpha.12",
    "react-native-web": "~0.11.7",
    "react-navigation": "^4.2.1"

**Comment by satya164** [comment]
Closing due to no response.

**Comment by vance-liu** [comment]
same problem

**Comment by vance-liu** [comment]
Too weird, when I run `yarn add @ react-navigation / native`, it uses 3.7.6 instead of 5.x. It took me half a day to check it. I fixed it by running `@ react-navigation / native @ 5.1.1` because of the documentation error and the latest version error in npm.
@satya164 @MislavPeric

**Comment by vance-liu** [comment]
I think the document should be fixed, such as
`
yarn add @react-navigation/native@5.1.1
yarn add @react-navigation/stack@5.2.3
yarn add @react-navigation/core@5.2.3
......
`

**Comment by fightingljm** [comment]
react-navigation 4x 与 react-navigation 5x混用造成的报错
安装5.x之前要确保 4.x 版本的都 remove 掉

**Comment by shqawe1** [comment]
> I think the document should be fixed, such as
> `yarn add @react-navigation/native@5.1.1 @react-navigation/stack@5.2.3 @react-navigation/core@5.2.3 ......`

Thank you so much man you save my day i was looking for solution for this issue two days ago they should update docs or at lest they should mentioned that.
Thanks again

**Comment by bonifacemwanza** [comment]
wonderful solution, still fixed my error

**Comment by amranwebdeveloper** [comment]
Face same the same error. Got it resolved. Try with this:

npm install @react-navigation/native

or

yarn add @react-navigation/native@next

or

yarn add @react-navigation/native

Doc : https://reactnavigation.org/docs/getting-started/

**Comment by mountainash** [comment]
This is an issue again. With Expo v51.0.38 and the suggested versions in https://github.com/react-navigation/react-navigation/issues/7658#issuecomment-602173818 don't work, nor does using the latest v7.0.0 @react-navigation dependencies.

🤔  It's also interesting that the Expo/Example at https://github.com/expo/examples/blob/master/with-drawer-navigation/App.js doesn't use the Expo Drawer libraries as documented at https://docs.expo.dev/router/advanced/drawer/

After hours of trial-and-error, as of today the following versions are working for me:

```
"expo": "^51.0.38",
"@react-navigation/core": "6.4.17",
"@react-navigation/drawer": "6.5.8",
"@react-navigation/native": "6.1.18",
"@react-navigation/stack": "6.4.1",
```

⚠  Also note that, [as per the migration note](https://github.com/expo/router/blob/b6a1ed0973cb529579fc5baf73c6943a88e1b6b1/docs/docs/migration/react-navigation/drawer.md), you'll need to add `'react-native-reanimated/plugin'` as a babel plugin.

```js title=babel.config.js
module.exports = {
    presets: [
        ...
    ],
    plugins: [
        ...
        'react-native-reanimated/plugin',
    ],
};
