### ISSUE TITLE
how to hide TabNavigation in a specific nested stack screen?(v5)

### ISSUE THREAD

**Issue by blueturtle13g** [react-navigation/react-navigation#7662]
I have nested stack screens in my tab navigator like so:
```
const Tab = createBottomTabNavigator();
const Stack = createStackNavigator();    

const HomeStackNavigator = () => (
  <Stack.Navigator>
    <Stack.Screen name="FirstNestedScreen" component={FirstNestedScreen} />
    <Stack.Screen name="SecondNestedScreen" component={SecondNestedScreen} />
    <Stack.Screen name="ThirdNestedScreen" component={ThirdNestedScreen} /> // on this screen
    //I don't want the user to see the bottom navigation tab
  </Stack.Navigator>
);

export default () => (
   <NavigationContainer>
     <Tab.Navigator>
       <Tab.Screen
         name="Home"
         options={({route}) => {
           let tabBarVisible = true;           
           if(route.name === "ThirdNestedScreen"){ // but it does not help,
// because route.name is always equal to the name of the Tab navigator, in this case "Home"
             tabBarVisible = false;
           }
           return {tabBarVisible};
         }}
       >
         {HomeStackNavigator}
       </Tab.Screen>
     </Tab.Navigator>
   </NavigationContainer>
);
```
My Intention is obvious, I want to hide the bottom tab navigator when the user is in the third nested stack screen. but the problem is that I don't have access to `tabBarVisible` option on a `Stack.Screen` as mentioned in this [doc:](https://reactnavigation.org/docs/en/screen-options-resolution.html#a-tab-navigator-contains-a-stack-and-you-want-to-hide-the-tab-bar-on-specific-screens)

so what I did was trying to set the visibility dynamically on the `Tab.Screen` by `route.name` but it doesn't show the name of the nested route, instead it always shows "Home"(the name of the Tab navigator). so I'm stuck. any workaround would be appreciated, thanks.

**Comment by satya164** [comment]
https://github.com/react-navigation/react-navigation/issues/6940#issuecomment-590087169
