### ISSUE TITLE
How can I define useRoute()'s params type?

### ISSUE THREAD

**Issue by KoreanThinker** [react-navigation/react-navigation#7663]
![image](https://user-images.githubusercontent.com/48207131/75248566-befd8800-5817-11ea-9056-c8b43ca9a117.png)
This code working but
![image](https://user-images.githubusercontent.com/48207131/75248664-e81e1880-5817-11ea-8288-9e22a8e84368.png)
I want use like this. I think something put on check...

**Comment by satya164** [comment]
https://reactnavigation.org/docs/en/typescript.html

**Comment by paulcmd** [comment]
Do this:

`
interface CommentScreenProps extends ParamListBase {
postid : string
}

const CommentScreen = () => {
  const { params : { id } } = useRoute<RouteProp<CommentScreenProps, 'Comment'>>()
}

//I am assuming Comment is the screen name you are using
`
