### ISSUE TITLE
Include Screens but don't show them on the Bottom Navigation Bar

### ISSUE THREAD

**Issue by hz1165** [react-navigation/react-navigation#7664]
I have a login and a signup screen and I want them to show at the beginning the of app
Right now i have them included in the MyTabs() function, it works but I can see those two tabs even if I am on other screens.
Is there a way to include Login and SignUp and also hide them when I am on 'Home', 'Search' and 'Diet'?

function MyTabs() {
  return (
    <Tab.Navigator
      initialRouteName="Login"
      tabBarOptions={{
        activeTintColor: '#e91e63',
      }}
    >
      <Tab.Screen
        name="Home"
        component={HomeScreen}
        options={{
          tabBarLabel: 'Home',
          tabBarIcon: ({ color, size }) => (
            <MaterialCommunityIcons name="home" color={color} size={size} />
          ),
        }}
      />
      <Tab.Screen
        name="Search"
        component={SearchScreen}
        options={{
          tabBarLabel: 'Search',
          tabBarIcon: ({ color, size }) => (
            <MaterialCommunityIcons name="magnify" color={color} size={size} />
          ),
        }}
      />
      <Tab.Screen
        name="Diet"
        component={ListScreen}
        options={{
          tabBarLabel: 'Diet',
          tabBarIcon: ({ color, size }) => (
            <MaterialCommunityIcons name="food-apple" color={color} size={size} />
          ),
        }}
      />
      <Tab.Screen
        name="Profile"
        component={Profile}
        options={{
          tabBarLabel: 'Profile',
          tabBarIcon: ({ color, size }) => (
            <MaterialCommunityIcons name="account-circle" color={color} size={size} />
          ),
        }}
      />
      <Tab.Screen
        name="Login"
        component={LoginScreen}
        options={{
          tabBarVisible: false,
          tabBarLabel: 'Login',
          tabBarIcon: ({ color, size }) => (
            <MaterialCommunityIcons name="home" color={color} size={size} />
          ),
        }}
      />
      <Tab.Screen
        name="SignUp"
        component={SignUpScreen}
        options={{
          tabBarVisible: false,
          tabBarLabel: 'SignUp',
          tabBarIcon: ({ color, size }) => (
            <MaterialCommunityIcons name="home" color={color} size={size} />
          ),
        }}
      />
    </Tab.Navigator>
  );
}

**Comment by WoLewicki** [comment]
You can make them render conditionally like in auth flow: https://reactnavigation.org/docs/auth-flow. Does it solve your issue?

**Comment by hz1165** [comment]
@WoLewicki  I rolled back to React Navigation 4 and put the bottom tab navigator under another navigator and it's working now
