### ISSUE TITLE
Routes with route parameters in stack navigators are ignored

### ISSUE THREAD

**Issue by 3rdp** [react-navigation/react-navigation#7667]
**Current Behavior**

StackNavigator. I have a route defined like `/survey/:surveyId`. I push `/survey/aaaaa`. No navigation happens.

**Expected Behavior**

The app does navigate, and survey id is accessible via navigation params.

**How to reproduce**

I don't have a reproducible demo, but I debugged what's happening and I see that on [this](https://github.com/react-navigation/react-navigation/blob/4.x/packages/core/src/routers/StackRouter.js#L354) line of code happens what I don't exactly want.
```
} else if (
    action.type === StackActions.PUSH &&
    childRouters[action.routeName] === undefined
    ) {
  // Return the state identity to bubble the action up
  return state;
}
```
The program doesn't even try to get the route. `childRouters` is an object like `{ '/survey/:surveyId': {...}, '/home': {...} }` and `action.routeName` is exactly the route I pushed.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | iOS
| react-navigation               | ^4.0.10
| @react-navigation/core   | 3.5.1
| react-navigation-stack         | 1.10.3
| react-navigation-tabs          | 2.5.6
| react-navigation-drawer        | none
| react-native-reanimated        | 1.4.0
| react-native-gesture-handler   | 1.5.0
| react-native-safe-area-context | none
| react-native-screens           | 1.0.0-alpha.23
| react-native                   | 0.61.3
| expo                           | none 
| node                           | 8.15.0
| npm or yarn                    | npm@6.7.0

**Comment by satya164** [comment]
This is not how the API is. Please read the documentation to see how to pass params https://reactnavigation.org/docs/4.x/params

**Comment by 3rdp** [comment]
@satya164 I want to deep link to this route. So, the API you mentioned is not relevant in my case.

**Comment by 3rdp** [comment]
I feel like docs can be improved here. Cause this had been working before, and the docs were not clear at how this works and how you can implement it. And that's very counterintuitive when you want to debug this via navigating in the app and you can't cause "this is not how the API is".

**Comment by satya164** [comment]
There's nowhere in the docs where we show such an API as per my knowledge. The logic of router also hasn't changed at all between version 3 and 4 so I'm pretty sure that this didn't work before if it isn't working now.

If you're going to use some API that's not mentioned in docs, then I'm not sure what to do you expect to happen.
