### ISSUE TITLE
error Can't add "react-navigation": invalid package version undefined.

### ISSUE THREAD

**Issue by Kiranyellu** [react-navigation/react-navigation#7668]
I am trying to install the project packages with the command "yarn " in MacBook Pro

OS : macOS Mojave version 10.14.5
 "react-native": "0.60.5",
 "react": "16.8.6",
"react-navigation": "3.11.0",

yarn version 1.22.0

Please find the attached images for the reference.

<img width="567" alt="Screenshot 2020-02-26 at 4 10 40 PM" src="https://user-images.githubusercontent.com/31812511/75337245-a0989a80-58b2-11ea-8005-35aa8bee0a7e.png">

and I have another **dell laptop** (Windows) there I could install the dependencies with the command "yarn" 

Please help me out I need to install packages with the command **"yarn" or "yarn install"**

Thanks

**Comment by RealDyllon** [comment]
@Kiranyellu are you running: `yarn add react-navigation@^3.0.0` ?

**Comment by Kiranyellu** [comment]
No the package is already there in my package.json file

**Comment by RealDyllon** [comment]
Hmmm. 

@Kiranyellu Try deleting the /node_modules folder then `yarn install`

**Comment by Kiranyellu** [comment]
I did same

**Comment by RealDyllon** [comment]
That’s odd, because v3 is still hosted on npm. 

I doubt you’ll get much help on this issue, as v3 is depreciated. 

You may want to upgrade to v4

**Comment by satya164** [comment]
This seems like a bug in `yarn`. Try deleting `yarn.lock` and run `yarn` again, or use `npm`.
