### ISSUE TITLE
Incorrect description of parameter 'route'

### ISSUE THREAD

**Issue by AwesomeAndrewMK** [react-navigation/react-navigation#7669]
**Current Behavior**

When we use Stack.Screen's options and pass parameter 'route' in callback we received wrong description:
<img width="834" alt="Screenshot 2020-02-26 at 14 50 04" src="https://user-images.githubusercontent.com/42909164/75346519-8ad1a800-58a7-11ea-9638-14a88ba66011.png">
`<Stack.Screen
          name="MainMenuScreen"
          component={MainMenuScreen}
          options={({route}) => ({
            title: 'Title',
            headerStyle: {
              backgroundColor: colors.white,
            },
            headerTintColor: colors.mainTextColor,
          })}
        />`

**Expected Behavior**

- Show correct description

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |
| @react-navigation/native       |
| react-native                   |0.61
| expo                           |
| node                           |
| npm or yarn                    |

**Comment by AwesomeAndrewMK** [comment]
@satya164 It's simple to reproduce: first of all, I had installed latest version of RN:
` "dependencies": {
    "@react-native-community/masked-view": "^0.1.6",
    "@react-navigation/native": "^5.0.7",
    "@react-navigation/stack": "^5.0.9",
    "react": "16.9.0",
    "react-native": "0.61.5",
    "react-native-gesture-handler": "^1.6.0",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-reanimated": "^1.7.0",
    "react-native-safe-area-context": "^0.7.3",
    "react-native-screens": "^2.0.0-beta.13"
  },`

And here is my code from root component:
`import 'react-native-gesture-handler';
import React from 'react';
import HomeScreen from '../HomeScreen';
import MainMenuScreen from '../MainMenuScreen';
import {NavigationContainer} from '@react-navigation/native';
import {createStackNavigator} from '@react-navigation/stack';
import colors from '../../../assets/colors/colors';

const Stack = createStackNavigator();

export default function App() {
  return (
    <NavigationContainer>
      <Stack.Navigator>
        <Stack.Screen
          name="HomeScreen"
          component={HomeScreen}
          options={{headerShown: false}}
        />
        <Stack.Screen
          name="MainMenuScreen"
          component={MainMenuScreen}
          options={({route}) => ({
            title: 'Title',
            headerStyle: {
              backgroundColor: colors.white,
            },
            headerTintColor: colors.mainTextColor,
            headerTitleStyle: {
              // fontFamily: 'OdibeeSans-Regular',
              fontSize: 20,
            },
          })}
        />
      </Stack.Navigator>
    </NavigationContainer>
  );
}
`

I studied the new version of navigation and found incorrect description of parameter in Stack.screen's options.
<img width="834" alt="Screenshot 2020-02-26 at 14 50 04" src="https://user-images.githubusercontent.com/42909164/75348234-17319a00-58ab-11ea-95b6-c132f7f44f11.png">

That's all what I can provide. It's a minor bug, but it isn't comfortable to work with it and in official documentation you can find example which can also help to reproduce it: 
[https://reactnavigation.org/docs/headers#using-params-in-the-title](url)
<img width="724" alt="Screenshot 2020-02-26 at 15 16 04" src="https://user-images.githubusercontent.com/42909164/75348153-ee110980-58aa-11ea-852d-25d8eab93460.png">
Hope, that will help : )

**Comment by satya164** [comment]
What exactly is the issue? What description are you talking about?

**Comment by AwesomeAndrewMK** [comment]
@satya164 underlined:
<img width="834" alt="Screenshot 2020-02-26 at 14 50 04" src="https://user-images.githubusercontent.com/42909164/75348578-d1c19c80-58ab-11ea-94b2-64e3cd3245bd.png">

**Comment by satya164** [comment]
That's not a description. That's the type hint shown by TypeScript showing the type of the object. To configure types in your project, refer to https://reactnavigation.org/docs/typescript
