### ISSUE TITLE
Bug navigation.replace() and navigation.reset()

### ISSUE THREAD

**Issue by hudiohizari** [react-navigation/react-navigation#7670]
One second or so after changing screen I still can go to previous screen by swiping back on iOS

https://share.icloud.com/photos/0coZCPIxEIOJ337ThqnTO2V_g
this when the error occurred. After I clicked logout button, I tried to go back to previous screen as fast as i can.  (At this point I'm not supposed to on this screen, because navigation.replace() already triggered) Then I clicked any tab on bottomTab but nothing happens, and i tried to click logout button which triggered navigation.replace() then error screen appeared

https://share.icloud.com/photos/0_owUS_eEF_zJk01ozxnc186g
This when I wait a second or so to swipe back to previous screen

I tried to try catch those function but try catch did not catch the error

here's my attempt to try catch navigation.replace()
```
        try {
            if(!isLoggedIn) navigation.replace("Login")   
        } catch (error) {
            alert("Oops, some error occurred, please restart application")            
        }
```

Main Stack
```
      <NavigationContainer>
        <Stack.Navigator 
          screenOptions={{ headerShown: false }}>
          <Stack.Screen 
            name="Route" 
            component={RouteScreen}/>
          <Stack.Screen 
            name="Login" 
            component={LoginScreen}/>
          <Stack.Screen 
            name="Navigation" 
            component={NavigationScreen}/>
        </Stack.Navigator>
      </NavigationContainer>
```

Inside NavigationScreen
```
        <Tab.Navigator>
            <Tab.Screen name="Dashboard" component={DashboardScreen}/>
            <Tab.Screen name="Scan" component={ScanScreen} />
            <Tab.Screen name="Profile" component={ProfileScreen} />
        </Tab.Navigator>
```

I tried to go from ProfileScreen to LoginScreen when error occurred

**Comment by albarkahdev** [comment]
> One second or so after changing screen I still can go to previous screen by swiping back on iOS
> 
> https://share.icloud.com/photos/0coZCPIxEIOJ337ThqnTO2V_g
> this when the error occurred. After I clicked logout button, I tried to go back to previous screen as fast as i can. (At this point I'm not supposed to on this screen, because navigation.replace() already triggered) Then I clicked any tab on bottomTab but nothing happens, and i tried to click logout button which triggered navigation.replace() then error screen appeared
> 
> https://share.icloud.com/photos/0_owUS_eEF_zJk01ozxnc186g
> This when I wait a second or so to swipe back to previous screen
> 
> I tried to try catch those function but try catch did not catch the error
> 
> here's my attempt to try catch navigation.replace()
> 
> ```
>         try {
>             if(!isLoggedIn) navigation.replace("Login")   
>         } catch (error) {
>             alert("Oops, some error occurred, please restart application")            
>         }
> ```
> 
> Main Stack
> 
> ```
>       <NavigationContainer>
>         <Stack.Navigator 
>           screenOptions={{ headerShown: false }}>
>           <Stack.Screen 
>             name="Route" 
>             component={RouteScreen}/>
>           <Stack.Screen 
>             name="Login" 
>             component={LoginScreen}/>
>           <Stack.Screen 
>             name="Navigation" 
>             component={NavigationScreen}/>
>         </Stack.Navigator>
>       </NavigationContainer>
> ```
> 
> Inside NavigationScreen
> 
> ```
>         <Tab.Navigator>
>             <Tab.Screen name="Dashboard" component={DashboardScreen}/>
>             <Tab.Screen name="Scan" component={ScanScreen} />
>             <Tab.Screen name="Profile" component={ProfileScreen} />
>         </Tab.Navigator>
> ```
> 
> I tried to go from ProfileScreen to LoginScreen when error occurred
Did you find any solusution for this problem?

**Comment by albarkahdev** [comment]
> One second or so after changing screen I still can go to previous screen by swiping back on iOS
> 
> https://share.icloud.com/photos/0coZCPIxEIOJ337ThqnTO2V_g
> this when the error occurred. After I clicked logout button, I tried to go back to previous screen as fast as i can. (At this point I'm not supposed to on this screen, because navigation.replace() already triggered) Then I clicked any tab on bottomTab but nothing happens, and i tried to click logout button which triggered navigation.replace() then error screen appeared
> 
> https://share.icloud.com/photos/0_owUS_eEF_zJk01ozxnc186g
> This when I wait a second or so to swipe back to previous screen
> 
> I tried to try catch those function but try catch did not catch the error
> 
> here's my attempt to try catch navigation.replace()
> 
> ```
>         try {
>             if(!isLoggedIn) navigation.replace("Login")   
>         } catch (error) {
>             alert("Oops, some error occurred, please restart application")            
>         }
> ```
> 
> Main Stack
> 
> ```
>       <NavigationContainer>
>         <Stack.Navigator 
>           screenOptions={{ headerShown: false }}>
>           <Stack.Screen 
>             name="Route" 
>             component={RouteScreen}/>
>           <Stack.Screen 
>             name="Login" 
>             component={LoginScreen}/>
>           <Stack.Screen 
>             name="Navigation" 
>             component={NavigationScreen}/>
>         </Stack.Navigator>
>       </NavigationContainer>
> ```
> 
> Inside NavigationScreen
> 
> ```
>         <Tab.Navigator>
>             <Tab.Screen name="Dashboard" component={DashboardScreen}/>
>             <Tab.Screen name="Scan" component={ScanScreen} />
>             <Tab.Screen name="Profile" component={ProfileScreen} />
>         </Tab.Navigator>
> ```
> 
> I tried to go from ProfileScreen to LoginScreen when error occurred

Did you find any solution for this problem?

**Comment by hudiohizari** [comment]
> > One second or so after changing screen I still can go to previous screen by swiping back on iOS
> > https://share.icloud.com/photos/0coZCPIxEIOJ337ThqnTO2V_g
> > this when the error occurred. After I clicked logout button, I tried to go back to previous screen as fast as i can. (At this point I'm not supposed to on this screen, because navigation.replace() already triggered) Then I clicked any tab on bottomTab but nothing happens, and i tried to click logout button which triggered navigation.replace() then error screen appeared
> > https://share.icloud.com/photos/0_owUS_eEF_zJk01ozxnc186g
> > This when I wait a second or so to swipe back to previous screen
> > I tried to try catch those function but try catch did not catch the error
> > here's my attempt to try catch navigation.replace()
> > ```
> >         try {
> >             if(!isLoggedIn) navigation.replace("Login")   
> >         } catch (error) {
> >             alert("Oops, some error occurred, please restart application")            
> >         }
> > ```
> > 
> > 
> > Main Stack
> > ```
> >       <NavigationContainer>
> >         <Stack.Navigator 
> >           screenOptions={{ headerShown: false }}>
> >           <Stack.Screen 
> >             name="Route" 
> >             component={RouteScreen}/>
> >           <Stack.Screen 
> >             name="Login" 
> >             component={LoginScreen}/>
> >           <Stack.Screen 
> >             name="Navigation" 
> >             component={NavigationScreen}/>
> >         </Stack.Navigator>
> >       </NavigationContainer>
> > ```
> > 
> > 
> > Inside NavigationScreen
> > ```
> >         <Tab.Navigator>
> >             <Tab.Screen name="Dashboard" component={DashboardScreen}/>
> >             <Tab.Screen name="Scan" component={ScanScreen} />
> >             <Tab.Screen name="Profile" component={ProfileScreen} />
> >         </Tab.Navigator>
> > ```
> > 
> > 
> > I tried to go from ProfileScreen to LoginScreen when error occurred
> 
> Did you find any solution for this problem?

Nope, still having this bug

**Comment by prashen** [comment]
I have created a example here https://snack.expo.io/@prashen/navigation-reset
But I can see in expo it's working but in ios Simulator don't know why it's not working. After clicking nothing happens.

```
const logout = () => {
    props.navigation.reset({
      index: 0,
      routes: [
        {
          name: 'Login'
        }
      ]
    });
  };
```

```
import React, { useSelector, useDispatch } from 'react';
import {
  View,
  Text,
  TouchableOpacity,
  Platform,
  Dimensions
} from 'react-native';
import { Icon } from 'react-native-paper';
import FaIcon from 'react-native-vector-icons/FontAwesome5';
import AuthLoadingScreen from '../Containers/AuthLoadingScreen';
import LoginScreen from '../Containers/LoginScreen';
import HomeScreen from '../Containers/HomeScreen';
import ChatScreen from '../Containers/ChatScreen';
import { NavigationContainer } from '@react-navigation/native';
import { createStackNavigator } from '@react-navigation/stack';
import { createBottomTabNavigator } from '@react-navigation/bottom-tabs';

const Stack = createStackNavigator();
const Tab = createBottomTabNavigator();

function HomeTabScreen(props) {
  console.log(props);
  return (
    <Tab.Navigator>
      <Tab.Screen name="Home" component={HomeScreen} />
      <Tab.Screen name="ChatScreen" component={ChatScreen} />
    </Tab.Navigator>
  );
}

function AppNavigator() {
  return (
    <NavigationContainer>
      <Stack.Navigator initialRouteName="AuthLoadingScreen">
        <Stack.Screen
          name="AuthLoadingScreen"
          options={{
            headerShown: false
          }}
          component={AuthLoadingScreen}
        />

        <Stack.Screen name="Home" component={HomeTabScreen} />
        
        <Stack.Screen
          name="Login"
          options={{
            headerShown: false
          }}
          component={LoginScreen}
        />
      </Stack.Navigator>
    </NavigationContainer>
  );
}

export default AppNavigator;
```



AuthLoading screen just has a button which routes to Home screen which has tab. and in one of the tab screen I have a button which has code like:

```
props.navigation.reset({
      index: 0,
      routes: [
        {
          name: 'Login'
        }
      ]
    });
```

navigate is working but reset methods is not working.

my package json
```
{
  "name": "test",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint .",
    "flow": "flow",
    "flow-typed": "flow-typed",
    "releaseApk": "cd android && gradlew assembleRelease",
    "debugApk": "cd android && gradlew assembleDebug",
    "bundle": "./gradlew bundleRelease"
  },
  "dependencies": {
    "@react-native-community/async-storage": "^1.7.1",
    "@react-native-community/google-signin": "^3.0.4",
    "@react-native-community/masked-view": "^0.1.6",
    "@react-native-firebase/app": "^6.3.0",
    "@react-native-firebase/auth": "^6.3.0",
    "@react-navigation/bottom-tabs": "^5.1.1",
    "@react-navigation/native": "^5.0.9",
    "@react-navigation/stack": "^5.0.9",
    "axios": "^0.19.2",
    "esdoc-ecmascript-proposal-plugin": "^1.0.0",
    "esdoc-flow-type-plugin": "^1.1.0",
    "esdoc-jsx-plugin": "^1.0.0",
    "jest-enzyme": "^7.1.2",
    "react": "16.9.0",
    "react-dom": "^16.12.0",
    "react-native": "0.61.5",
    "react-native-fbsdk": "^1.1.2",
    "react-native-gesture-handler": "^1.5.3",
    "react-native-paper": "^3.4.0",
    "react-native-reanimated": "^1.4.0",
    "react-native-safe-area-context": "^0.6.2",
    "react-native-screens": "^2.0.0-alpha.23",
    "react-native-splash-screen": "^3.2.0",
    "react-native-vector-icons": "^6.6.0",
    "react-redux": "^7.1.3",
    "redux": "^4.0.5"
  },
  "devDependencies": {
    "@babel/cli": "^7.8.4",
    "@babel/core": "^7.8.4",
    "@babel/preset-flow": "^7.8.3",
    "@babel/runtime": "^7.6.2",
    "@react-native-community/eslint-config": "^0.0.5",
    "babel-jest": "^24.9.0",
    "enzyme": "^3.11.0",
    "enzyme-adapter-react-16": "^1.15.2",
    "esdoc": "^1.1.0",
    "esdoc-standard-plugin": "^1.0.0",
    "eslint": "^6.8.0",
    "eslint-config-prettier": "^6.10.0",
    "eslint-plugin-prettier": "^3.1.2",
    "eslint-plugin-react": "^7.18.3",
    "eslint-plugin-react-native": "^3.8.1",
    "flow-bin": "^0.118.0",
    "flow-typed": "^2.6.2",
    "jest": "^24.9.0",
    "metro-react-native-babel-preset": "^0.56.0",
    "prettier": "^1.19.1",
    "react-test-renderer": "16.9.0"
  },
  "rnpm": {
    "assets": [
      "./assets/fonts/"
    ]
  }
}

```

**Comment by chakrihacker** [comment]
I have made another [Snack](https://snack.expo.io/@chakrihacker/passing-parameters-to-routes-|-react-navigation) in which replace doesn't work.

My question is does replace and reset doesn't bubble up??

**Comment by prashen** [comment]
@chakrihacker Change this line ` onPress={() => navigation.replace('AuthScreen')` to `onPress={() => navigation.navigate('Auth')}`

https://snack.expo.io/@prashen/passing-parameters-to-routes-%7C-react-navigation

**Comment by chakrihacker** [comment]
@prashen I have route *Auth* in the snack which holds auth stack and I want to replace auth stack and it's routes to home

**Comment by chakrihacker** [comment]
@prashen I have route *Auth* in the snack which holds auth stack and I want to replace auth stack and it's routes to home

**Comment by WoLewicki** [comment]
@chakrihacker in your snack `onPress={() => navigation.replace('AuthScreen')}` tries to replace your screen with a one with the name `AuthScreen`, which does not occur in your navigator, since it has screens: "Splash", "Auth", "Home", "Details".

```js
 <Stack.Screen name="Splash" component={SplashScreen} />
        <Stack.Screen name="Auth" component={AuthScreen} />
        <Stack.Screen name="Home" component={HomeScreen} />
        <Stack.Screen name="Details" component={DetailsScreen} />
```

**Comment by WoLewicki** [comment]
@hudiohizari could you provide a snack with a minimal repro of this bug?

**Comment by raajnadar** [comment]
Closing this because if you want to make an authentication flow with react navigation v5 you should follow this docs. https://reactnavigation.org/docs/auth-flow/

No need to use `replace` or `reset`

**Comment by LucasHimelfarb** [comment]
if you have the following code:

```
    navigation.addListener('beforeRemove', (evt) => {
      evt.preventDefault();
    });
```

maybe .replace() and .reset() shouldn't work correctly
