### ISSUE TITLE
Nested stack navigator is not reseted from drawer navigator

### ISSUE THREAD

**Issue by kenodek** [react-navigation/react-navigation#7671]
**Current Behavior**
Nested stack navigator in drawer navigator is not reseted after clicking it in drawer.

**Expected Behavior**

Nested stack navigator is reseted.

**How to reproduce**

Navigation structure looks like this:

- DrawerNavigator
    - MainStack
        - FirstScreen (initialScreen)
        - SecondScreen
    - ThirdScreen

If I go to Second Screen and then I click Main Stack in drawer I expect to go back to First Screen as it is initial screen. If I'm in Second Screen and go to Third Screen and then moving back to Main Stack it shows the Second Screen. I would expect to see the intitial screen

Here is the snack https://snack.expo.io/@kenodek/3d0eb5

**Comment by WoLewicki** [comment]
> If I go to Second Screen and then I click Main Stack in drawer I expect to go back to First Screen as it is initial screen

It is not the default behavior in the drawer navigator.

>  If I'm in Second Screen and go to Third Screen and then moving back to Main Stack it shows the Second Screen. I would expect to see the intitial screen

Is https://reactnavigation.org/docs/drawer-navigator#unmountonblur what you need?

**Comment by kenodek** [comment]
@WoLewicki  thanks for quick reply . For me it's strange behavior it's not reseted. It would be great to have option to reset the nested stack navigator

**Comment by WoLewicki** [comment]
@satya164 wdyt?

**Comment by satya164** [comment]
That's how it is for all core navigators. Navigators don't unmount screens when you navigate to a new screen. It's the expected behaviour and if you want a different behaviour, you need to configure it explicitly.

**Comment by crobinson42** [comment]
Here is an example snack: https://snack.expo.io/@coryrobinson42/1cd250

I think this behavior should be supported according to how the docs explain it:

```
**unmountOnBlur**

Whether this screen should be unmounted when navigating away from it. Unmounting a screen resets any local state in the screen as well as state of nested navigators in the screen. Defaults to false.
```
https://reactnavigation.org/docs/drawer-navigator#unmountonblur

In the example snack I provided, **currently**, the screens for the DrawerNavigator do unmount but the StackNavigators state is persisted in the `NavigationContainer` so when the nested StackNavigators mount again later they have the same state as they did before unmounting. 

Is this a bug or some missing configuration in that snack example @satya164 @WoLewicki ?

**Comment by crobinson42** [comment]
I opened #7783 regarding this issue with reproducible demo.

**Comment by glassdevops** [comment]
Hi, we are also facing a similar issue whereby if navigate from stack screen to drawer screen and then when pushToTop the last screen navigated to in the stack screen is shown even though unmountonblur= true was set.

From our analysis the unmountonblur isn't working from stack to drawer navigation, only within the navigators. Is this an expected behavior, and if it is, is there a workaround to reset the previous stack screens?

**Comment by edwardchen** [comment]
I'm having the same issue. Nested navigators aren't reset, but they should be if unmountOnBlur is set.

Isn't that what the docs are saying?
> Whether this screen should be unmounted when navigating away from it. Unmounting a screen resets any local state in the screen as well as state of nested navigators in the screen. Defaults to false.

**Comment by pedromcunha** [comment]
Same issue with a DrawerNavigator and a BottomTabNavigator. Any updates on this?
