### ISSUE TITLE
Dynamic changes to the stack would briefly set the Screen at index 0 as the focused screen

### ISSUE THREAD

**Issue by kidroca** [react-navigation/react-navigation#7672]
**Current Behavior**

- What code are you running and what is happening?

Having a code similar to the following would trigger the `useFocusEffect` hook when the `Stack.Screen` at index 0 is active and the condition changes:

*The use case is this: We're having a Screen that destroys itself from the navigation and navigates to another screen, something like a redirect component. A concrete case would be determining the authentication state of an app as it gets loaded*

```javascript
const Navigation = () => {
  const { auth } = React.useContext(AppStateConenxt);

  return (
    <NavigationContainer>
      <Stack.Navigator initialRouteName="Auth Loading">
        { /* When this Stack.Screen gets removed the Menu is briefly added as the current screen,
         and it's useFocusEffect runs (see the console), while actually the Login screen is set as active */ }
        { !auth.isInitialized && <Stack.Screen name="Auth Loading" component={AuthLoading} /> }

        {/* In the actual app we're conditionally rendering one or the other... */}
        {/* The first of these screens is briefly focused when `auth.isInitialized` is true */}
        { AuthStack }
        { AnonymousStack }
      </Stack.Navigator>
    </NavigationContainer>
  );
};

// I would much like to use this as a component `const AuthStack = () => (...)` but currently that's not allowed (A navigator can only contain screens...)
// Having a separate component with some screens that might be deferred and not loaded (parsed) initially could be beneficial 
const AuthStack = (
  <>
    <Stack.Screen name="Menu" component={MenuScreen} />
    { /* other screens */ }
  </>
)

const AnonymousStack = (
  <>
    <Stack.Screen name="Login" component={LoginScreen} />
    <Stack.Screen name="Create Account" component={CreateAccount} />
  </>
)
```

**Expected Behavior**

- What do you expect should be happening?

The active screen should not automatically get to be the wherever Screen happens to be at index 0, even briefly. But the one we're setting by with `navigation.navigate()` by the immediate execution
At least some warning should be logged informing the developer that the active screen might have changed unintentionally due to control flow. 

**How to reproduce**

A snack recreating the issue: https://snack.expo.io/@kidroca/usefocuseffect

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Both
| @react-navigation/native       |  5.0.8
| @react-navigation/stack        | 5.0.5
| react-native-gesture-handler   |  1.5.0
| react-native-safe-area-context | 0.6.0
| react-native-screens           | 2.0.0-alpha.12
| expo                           | 36.0.2
| node                           | 10.16.2
| yarn                    | 1.19.1

**Comment by satya164** [comment]
This is expected behaviour. When you remove the auth screen, the first screen defined takes focus. You're not supposed to manually navigate to the screen after you login, but define the screens conditionally so the correct screen gets focused.
