### ISSUE TITLE
Stack.Navigator nested doesnt accept/work headerMode="none" on sub Stack.Navigator

### ISSUE THREAD

**Issue by bracketized** [react-navigation/react-navigation#7674]
**Current Behavior**
Currently i have this navigation ( trying to upgrade from V4 where everything was totally fine ).

This is all wrapped with Stack.Navigator.

- Loading ( main loading for the app, requets or awaits ).
- Authentication ( this is nested screen with Stack navigation again and it's Stack screens )
--- HomeScreen
--- LoginScreen
--- SignupScreen
--- ForgotScreen
--- RecoverScreen
- Authenticated  ( this is nested screen with drawer navigation )
--- UserHomeScreen
--- UserMapScreen
[...] etc

When i try to hide the header for HomeScreen in authentification, because there
i do not what it to be shown, it's impossible, it doesn't work, i must hide or show for all
the nested Stacks.

If i try to set it to the nested Stack, lets supose i hide it for the Top stack, and put
headerMode = "screen" on the subStack, it doesn't show up.

**Expected Behavior**

I expect like with static props on the old V4, to be hable to hide/show nested stacks header
independently, and not forced to use on all Stacks, independently of the nesting.

**How to reproduce**

Nesting Two Stack.Navigators and setting headerMode="screen" to first and headerMode="none" to second, doesn't hide the nested stack header.

**Your Environment**

I'm running the following versions.
"@react-navigation/bottom-tabs": "^5.0.7",
"@react-navigation/drawer": "^5.0.7",
"@react-navigation/material-bottom-tabs": "^5.0.7",
"@react-navigation/material-top-tabs": "^5.0.7",
"@react-navigation/native": "^5.0.7",
"@react-navigation/stack": "^5.0.9",

Thank you all by any means.

**Comment by solace** [comment]
The new modules aren't able to be loaded into snack and don't have a chance to create a repro demo atm.

For reference, I'm experiencing a similar issue, starting hidden and changing to a visible header. I was previously using a SwitchNavigator with a nested StackNavigator and from the recommendation of the docs, I changed the outer Switch to a Stack but now the header needs to be visible for all or hidden for all.

**Comment by satya164** [comment]
Closing due to no response.

**Comment by 1awaleed** [comment]
Giving the outer stack navigator `headerMode="none"` solves the issue as @solace said. This is not mentioned anywhere else.
