### ISSUE TITLE
Little Question V5. How to redirect to sub-routers in another component children like in V4.

### ISSUE THREAD

**Issue by ruyjfs** [react-navigation/react-navigation#7675]
I upgrade to from v4 to v5.

In my component Loading, i redirect to anothers components. But in V5 the component Loading, not see routers from App like in V4.

How I can redirect to sub-routers into my component App?

Thanks...
```
export default () => (
  <NavigationContainer>
    <Stack.Navigator headerMode="none" mode="modal">
      <Stack.Screen name="Loading" component={Loading} />
      <Stack.Screen name="App" component={App} />
      <Stack.Screen name="AuthChat" component={AuthChat} />
    </Stack.Navigator>
  </NavigationContainer>
);
```

**Comment by satya164** [comment]
Please read the docs https://reactnavigation.org/docs/nesting-navigators#navigating-to-a-screen-in-a-nested-navigator

**Comment by ruyjfs** [comment]
> Please read the docs https://reactnavigation.org/docs/nesting-navigators#navigating-to-a-screen-in-a-nested-navigator

Thank you very much Man! Work very fine now!

```
navigation.navigate('Root', {
  screen: 'Settings',
  params: {
    screen: 'Sound',
    params: {
      screen: 'Media',
    },
  },
});

```
