### ISSUE TITLE
[Android] Crash when using animated switch navigator

### ISSUE THREAD

**Issue by MohamadKh75** [react-navigation/react-navigation#7680]
**Current Behavior**
Whenever I use `createAnimatedSwitchNavigator`, app crashes!

**Expected Behavior**
The app should works as expected!

**How to reproduce**
Just try this:
```js
import { createSwitchNavigator, createAppContainer } from 'react-navigation';
import createAnimatedSwitchNavigator from 'react-navigation-animated-switch';
import { createStackNavigator } from 'react-navigation-stack';
import { A, B } from './screens';

const firstStack = createStackNavigator({
  _One: A
});

const secondStack = createStackNavigator({
  _Two: B
});

const rootStack = createAnimatedSwitchNavigator(
  {
    _firstStack: firstStack,
    _secondStack: secondStack
  },
  {
    initialRouteName: '_firstStack'
  }
);

export default createAppContainer(rootStack);

```

Then try to navigate to stack B via `navigation.navigate('_secondStack')`.
If you change to `createSwitchNavigator`, everything will be fine!

**Your Environment**
```json
"dependencies": {
  "@react-native-community/masked-view": "^0.1.6",
  "react": "16.9.0",
  "react-native": "0.61.5",
  "react-native-gesture-handler": "^1.6.0",
  "react-native-reanimated": "^1.7.0",
  "react-native-safe-area-context": "^0.7.3",
  "react-native-screens": "^2.1.0",
  "react-navigation": "^4.2.2",
  "react-navigation-animated-switch": "^0.5.2",
  "react-navigation-stack": "^2.2.2"
}
```

```bash
System:
    OS: Windows 8.1 6.3.9600
    CPU: (8) x64 Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz
    Memory: 9.38 GB / 15.92 GB
  Binaries:
    Node: 10.19.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
  SDKs:
    Android SDK:
      API Levels: 23, 25, 26, 27, 28
      Build Tools: 23.0.1, 25.0.0, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.3, 28.0.3
      System Images: android-22 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom_64, android-25 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: Version  3.4.0.0 AI-183.6156.11.34.5692245
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
```

**Comment by WoLewicki** [comment]
I made a quick snack with this and it seems to work just fine: https://snack.expo.io/@wolewicki/02afc4. Can you be more specific about why it crashes?

**Comment by MohamadKh75** [comment]
> I made a quick snack with this and it seems to work just fine: https://snack.expo.io/@wolewicki/02afc4. Can you be more specific about why it crashes?

Hey

I copied your snack and ut crashes on a real device (galaxy s7).
I created the project via `react-native init ...`
maybe that's the difference 🤔

**Comment by WoLewicki** [comment]
Can you show the logs from the crash? Are they anyhow descriptive?

**Comment by MohamadKh75** [comment]
here's the output of `react-native log-android`:

<details><summary>Log</summary>
<p>

```bash
info Starting logkitty
[2m[22:36:42][22m D | [1mReactNative[22m ▶︎ ReactInstanceManager.ctor()

[2m[22:36:42][22m D | [1mReactNative[22m ▶︎ ReactInstanceManager.createReactContextInBackground()
                           [2m└ [22mReactInstanceManager.recreateReactContextInBackgroundInner()

[2m[22:36:43][22m D | [1mReactNative[22m ▶︎ ReactInstanceManager.onJSBundleLoadedFromServer()
                           [2m└ [22mReactInstanceManager.recreateReactContextInBackground()

[2m[22:36:43][22m D | [1mReactNative[22m ▶︎ ReactInstanceManager.runCreateReactContextOnNewThread()

[2m[22:36:43][22m D | [1mReactNative[22m ▶︎ ReactInstanceManager.createReactContext()

[2m[22:36:43][22m D | [1mReactNative[22m ▶︎ Initializing React Xplat Bridge.

[2m[22:36:43][22m D | [1mReactNative[22m ▶︎ Initializing React Xplat Bridge before initializeBridge

[2m[22:36:45][22m D | [1mReactNative[22m ▶︎ Initializing React Xplat Bridge after initializeBridge
                           [2m└ [22mCatalystInstanceImpl.runJSBundle()

[2m[22:36:45][22m D | [1mReactNative[22m ▶︎ ReactInstanceManager.setupReactContext()

[2m[22:36:45][22m D | [1mReactNative[22m ▶︎ CatalystInstanceImpl.initialize()

[2m[22:36:45][22m D | [1mReactNative[22m ▶︎ ReactInstanceManager.attachRootViewToInstance()

[2m[22:36:46][22m I | [1mReactNativeJS[22m ▶︎ Running "TestFresh61" with {"rootTag":1}

[2m[22:36:46][22m I | [1mReactNative[22m ▶︎ [GESTURE HANDLER] Gesture handler is already enabled for a parent view

[2m[22:36:46][22m I | [1mReactNative[22m ▶︎ [GESTURE HANDLER] Initialize gesture handler for root view com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView{1f1c37 V.E...... ......ID 0,0-720,1238 #1}

[2m[22:36:56][22m I | [1mReactNative[22m ▶︎ [GESTURE HANDLER] Gesture handler is already enabled for a parent view

```
</p>
</details>

After this, app crashes!

**Comment by mpraksti-alchemy** [comment]
Experiencing the same issue, anyone figure out a solution?

**Comment by satya164** [comment]
Closing since you didn't provide a repro. If you have a minimal repro, feel free to open an issue.

**Comment by ketanvault** [comment]
Experiencing the same issue on latest library

"dependencies": {
    "@react-native-community/async-storage": "^1.9.0",
    "@react-native-community/geolocation": "^2.0.2",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-navigation/bottom-tabs": "^5.3.4",
    "@react-navigation/drawer": "^5.6.4",
    "@react-navigation/native": "^5.2.4",
    "@react-navigation/stack": "^5.2.19",
    "formik": "^2.1.4",
    "moment": "^2.24.0",
    "react": "16.11.0",
    "react-native": "0.62.0",
    "react-native-android-location-enabler": "^1.2.1",
    "react-native-background-fetch": "^3.0.4",
    "react-native-button": "^3.0.1",
    "react-native-camera": "^3.22.0",
    "react-native-fast-image": "^8.1.5",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-permissions": "^2.0.10",
    "react-native-qrcode-scanner": "^1.4.0",
    "react-native-reanimated": "^1.8.0",
    "react-native-safe-area-context": "^0.7.3",
    "react-native-screens": "^2.7.0",
    "react-native-sqlite-storage": "^5.0.0",
    "react-native-vector-icons": "^6.6.0",
    "react-navigation-redux-helpers": "^4.0.1",
    "react-redux": "^7.2.0",
    "redux": "^4.0.5",
    "yup": "^0.28.3"
  },
  "devDependencies": {
    "@babel/core": "^7.9.0",
    "@babel/runtime": "^7.9.2",
    "@react-native-community/eslint-config": "^1.0.0",
    "babel-jest": "^25.2.4",
    "eslint": "^6.8.0",
    "jest": "^25.2.4",
    "metro-react-native-babel-preset": "^0.59.0",
    "react-test-renderer": "16.11.0"
  },
  "jest": {
    "preset": "react-native"
  }

I followed each instruction set by react-navigation in it's docs. Added 'react-native-gesture-handler' library at the top. Still getting the same issue.

Please help me on this.
