### ISSUE TITLE
Dates should be serializable in params

### ISSUE THREAD

**Issue by lukewlms** [react-navigation/react-navigation#7681]
**Current Behavior**

When trying to pass a date in `navigate()` params, the warning appears:

> We found non-serializable values in the navigation state

**Expected Behavior**

Dates have standard serialization/deserialization protocol (e.g. formatISO and parseISO in date-fns or similar).  Is there a reason not to allow them to be serialized?  Passing around date strings instead is in many cases more cumbersome.

**How to reproduce**

Example:

```ts
    navigation.navigate("EditWorkoutScreen", {
      workoutDate,
    });
```

| @react-navigation/native       | 5
| react-native                   | 61

**Comment by satya164** [comment]
JSON.stringify and JSON.parse won't handle it automatically. Also when parsing a ISO string, there's no way to know if it should be parsed or not, it's specific to the use case.

You can pass the ISO string instead of a Date object instead for it to be serializable.

**Comment by lukewlms** [comment]
I see - JSON doesn't have a canonical representation for Dates.  We are already serializing via ISO as you suggest.  Thank you for the thoughtful response!

**Comment by kopax-polyconseil** [comment]
Hello, I have in my URL : 

`/search?aroundRadius=null&beginningDatetime=null&date=null&endingDatetime=null&geolocation=%5Bobject%20Object%5D&hitsPerPage=10&locationType=EVERYWHERE&offerCategories=CINEMA%2CMUSIQUE%2CLECON%2CLIVRE%2CFILM%2CJEUX_VIDEO%2CCONFERENCE%2CINSTRUMENT%2CMATERIEL_ART_CREA&offerIsDuo=false&offerIsFree=false&offerIsNew=false&offerTypes=%5Bobject%20Object%5D&priceRange=0%2C300&tags=&timeRange=null&venueId=null`.

It seems object aren't serialized, I am quite surprise of the discussion as it seems it should be serialized.

**Comment by kseverinsen** [comment]
Could not react-navigation use something like [EJSON](https://docs.meteor.com/api/EJSON.html) for serializing navigation params?
