### ISSUE TITLE
Background active/inative tabs

### ISSUE THREAD

**Issue by mathritter** [react-navigation/react-navigation#7682]
I want something very simple and I couldn't find how to do that reading the docs top to bottom. I need the tabs to have specific background color when they are either active or inactive;

**Comment by eriveltonelias** [comment]
Hey @mathritter, 

you can do the following https://reactnavigation.org/docs/bottom-tab-navigator/#tabbaroptions

**Comment by mathritter** [comment]
it's in the section for bottom tabs, can I apply that for top tabs?

**Comment by mathritter** [comment]
Please, remove the closed label, it doesn't work for top tabs

**Comment by vankhoa01** [comment]
Hello, Is there any update for this ?
