### ISSUE TITLE
No 'headerLeft' option in NativeStackNavigation

### ISSUE THREAD

**Issue by hammadj** [react-navigation/react-navigation#7684]
**Current Behavior**

When navigating to a modal screen, I want to be able to set a "Cancel" button on the left, like so: 
![image](https://user-images.githubusercontent.com/7143583/75503104-f6903f80-5991-11ea-9c2c-8c3c9b4b439e.png)
However, the only available option in `navigator.setOptions` is `headerRight`. headerLeft does not work: 
![image](https://user-images.githubusercontent.com/7143583/75503165-23dced80-5992-11ea-8a08-ad4898fd949e.png)

**Expected Behavior**

I should be able to specify a headerLeft for the nav bar, especially for modals.

**How to reproduce**

Just try to set headerLeft on any modal or nav. The option isn't there.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | 13
| @react-navigation/native       |  5.0.7
| @react-navigation/stack        | 5.0.5
| react-native-gesture-handler   | 1.5.3
| react-native-safe-area-context | 0.6.0
| react-native-screens           | 2.1.0
| react-native                   | https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz
| expo                           | 36
| node                           | 10.16
| npm or yarn                    | yarn 1

**Comment by satya164** [comment]
Please open native stack related issues in screens repo https://github.com/software-mansion/react-native-screens/pull/345
