### ISSUE TITLE
Navigate to same screen name with different key just replaces the existing screen

### ISSUE THREAD

**Issue by OscarYuen** [react-navigation/react-navigation#7685]
**Current Behavior**

I have a component(with specific objectId in its props) which have a onPress callback as the following
` this.props.navigation.navigate("StackA", {
            screen: 'Screen1',
            key: 'Screen1' + this.props.objectId,
            params: {
                id: this.props.objectId
            },
})`
It would redirect to Screen1 with id = this.props.objectId
Inside Screen1, It also show the same component with other objectId which also have the same callback.
When I press one of other components, It just replaces the existing screen with pressed objectId

**Expected Behavior**

It should push a new screen with pressed objectId like what navigation v4 behaves.

**How to reproduce**

Described in Current Behavior

Demo: https://snack.expo.io/@oscaryuen/0581b7

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | both
| @react-navigation/native       |^5.0.7
| @react-navigation/stack        |^5.0.9
| react-native-gesture-handler   |~1.5.0
| react-native-safe-area-context |0.6.0
| react-native                   |0.60
| expo                           |SDK 36

**Comment by OscarYuen** [comment]
> Hey! Thanks for opening the issue. Can you provide a minimal repro which demonstrates the issue? Posting a snippet of your code in the issue is useful, but it's not usually straightforward to run. A repro will help us debug the issue faster. Please try to keep the repro as small as possible. The easiest way to provide a repro is on [snack.expo.io](https://snack.expo.io). If it's not possible to repro it on [snack.expo.io](https://snack.expo.io), then you can also provide the repro in a GitHub repository.

https://snack.expo.io/@oscaryuen/0581b7

**Comment by mbretter** [comment]
I encountered the same problem, when opening a screen twice with different routing params, then a new screen should be opened, but react navigation just focuses the old screen. This only occurs when using the web renderer, running the app on an android device, then it works as expected.

**Comment by satya164** [comment]
It's not supported to specify `key` in params.

**Comment by OscarYuen** [comment]
> It's not supported to specify `key` in params.

thanks, I thought it would be similar to navigation v4 which supports key in params. 
Look forward to this new feature :D

**Comment by Aryk** [comment]
I'm getting the same issue, basically forces me to have to push a new stack everytime when I got just reload to a previous page.... :/

**Comment by Hamidrezana** [comment]
I have same problem. any update?

**Comment by Aryk** [comment]
@OscarYuen - are you still having this issue?

I'm curious if anyone out there can actually navigate to a new screen using the "key", or is it just completely broken?

**Comment by OscarYuen** [comment]
> @OscarYuen - are you still having this issue?
> 
> I'm curious if anyone out there can actually navigate to the same screen (but different params) by using a unique "key", or is it just completely broken?
Instead of `navigation.navigate with key`,
I found `navigation.push` could also navigate to the same screen component with correct navigation.
e.g.
```
navigation.push("AStack", {
            screen: 'ADetailScreen',
            params: {
                id: itemId,
            },
        });
```

Hope this could help you guys

**Comment by Aryk** [comment]
Thanks @OscarYuen , I'm aware of the `push` method but the problem is that if I'm currently on that screen, I will want to stay there and not move to a new one...so I have to create a checking method to parse the navigation state, check if I'm on that screen (but with different params) and then push...it's really annoying and everyone has to basically write this parsing function for the navigation state if they want this functionality.

**Comment by imns1ght** [comment]
@dmoree

Thank you very much, this solved my problem! :)

**Comment by michaelroevievictoria** [comment]
@dmoree what is I go back how can i get the prev id ?

**Comment by ankit-gl** [comment]
> > @Aryk I'm not sure on the status of this as its over a year old, but the same behavior can be had by using the [`getId`](https://reactnavigation.org/docs/screen#getid) attribute on a `Stack.Screen`. In this case you would pass:
> > ```
> > <Stack.Screen
> >   ...
> >   getId={({ params: { id } }) => id}
> > />
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > (From the link above)
> > > This is useful for preventing multiple instances of the same screen in the navigator, e.g. - when params.userId is used as an ID, subsequent navigation to the screen with the same userId will navigate to the existing screen instead of adding a new one to the stack. If the navigation was with a different userId, then it'll add a new screen.
> > 
> > 
> > I am currently using `v6`, but it should be available for `v5`
> 
> Hey, I'm confused how this works. I'm using getId and navigate with {id} param. What I'm trying to do is actually use dynamic routes based on the id param, and I want repeated navigations to that route to stay cached...but when I actually call navigate, it always rebuilds the screen from scratch.
> 
> Any tips?

Were you able to find a solution for this. Even we have similar scenario where we want to render new component but re render the whole tree.
