### ISSUE TITLE
Adding material icons in drawer screens(react-navigation v5)

### ISSUE THREAD

**Issue by drb1** [react-navigation/react-navigation#7687]
how can we add material icons in header bar and drawer bar in react-navigation v5.

**Comment by PeterNewtonBR** [comment]
Hi, I installed this [https://www.npmjs.com/package/react-native-vector-icons](url)

1. Run: $ npm install --save react-native-vector-icons

1. For each platform (iOS/Android/Windows) you plan to use, follow one of the options for the corresponding platform.

In my case for android.

`import Icon from 'react-native-vector-icons/MaterialIcons';`
`<Drawer.Screen name="Home" component={Home}`
`          options={{ drawerLabel: 'Casa',`
`            drawerIcon: (({focused}) => <Icon name="home" size={30} color="#900" />)`
`size={30} name='rocket' />)`
`        }}`

![image](https://user-images.githubusercontent.com/61658443/75628429-ac88a300-5bb7-11ea-9ed1-477294def2bf.png)

**Comment by drb1** [comment]
can you explain for header bar icon too, by the way thank you for your response it worked for drawer bar

**Comment by PeterNewtonBR** [comment]
Which header? I don't understood.

**Comment by PeterNewtonBR** [comment]
Now I'm learn this video [https://www.youtube.com/watch?v=z7wZSA176kE](url)
I'm starting with react.

**Comment by drb1** [comment]
Top Header bar of app where we place notification and menu icon

**Comment by PeterNewtonBR** [comment]
About the icons, you can see in this link, it's very simple.

`https://github.com/react-navigation/react-navigation/issues/url`
