### ISSUE TITLE
How to complely disable @react-navigation/drawer

### ISSUE THREAD

**Issue by kopax** [react-navigation/react-navigation#7691]
Within `redux`, I have a selector that return `isLogged` bool, I want my drawer to render and have gesture **only** if the value is `true`.

I have tried to do as follow: 

```jsx
      <Navigator drawerContent={isLogged ? DrawerContent : () => null}>
        <Screen
          name="inner-drawer"
          component={AppNavigatorRuntime}
          {...rest}
        />
      </Navigator>
```

It still gives me a drawer with an empty content and with gesture, I have tried to disable the gesture as well with : 

    <Navigator drawerContent={DrawerContent} gestureEnabled={isLogged}>

But this doesn't disable the gesture.

How would you recommend users to completely disable the `drawer`?

Thanks a lot for your time, 

Dimitri

**Comment by satya164** [comment]
`gestureEnabled` is an `option`, not a prop. Pass it in `screenOptions`.

**Comment by kopax** [comment]
I have tried to do so: 

```jsx
export default function createAppContainer(AppNavigator, drawerNavigator) {
  const { Navigator, Screen } = drawerNavigator();
  // eslint-disable-next-line react/prop-types
  return ({ AppBar, DrawerContent, ...rest }) => {
    const AppNavigatorRuntime = (props) => (
      <AppNavigator
        headerMode="screen"
        screenOptions={AppBar ? {
          header: AppBar,
          gestureEnabled: false,
        } : undefined}
        {...props}
      />
    );
    return (
      <Navigator drawerContent={DrawerContent}>
        <Screen
          name="inner-drawer"
          component={AppNavigatorRuntime}
          screenOptions={{
            gestureEnabled: false,
          }}
          {...rest}
        />
      </Navigator>
    );
  };
}
```

And even if this work, this will only disable the gesture, while I need hidden and disabled like if it was not existing.

But thanks still. By the way your new documentation is awesome. There is just the `light` icon in the dark mode switch that doesn't render properly.

**Comment by kopax** [comment]
What I need shouldn't be hard, I want to not render the drawer at all.  I still look for a simple way, I am not able to do that simply.

It would be an awesome feature and not so hard to implement, don't you think too @satya164 ?

Thanks again!

**Comment by kopax** [comment]
Awesome this disabled it : 

```
      <Navigator
        drawerContent={DrawerContent}
        screenOptions={{
          gestureEnabled: false,
        }}
      >
```

Thanks a lot!
