### ISSUE TITLE
How to get rid of blinking when pressing tab

### ISSUE THREAD

**Issue by jinsunee** [react-navigation/react-navigation#7693]
I don't know why this happening and what should i do :(

![화면 기록 2020-02-29 오전 12 29 35](https://user-images.githubusercontent.com/31176502/75561666-be205c80-5a8a-11ea-9923-00283e4a689e.gif)

**Environment**

| software                               | version |
| -------------------------------------- | ------- |
| iOS or Android                         |  iOS |
| @react-navigation/native               |   ^5.0.3 |
| @react-navigation/material-bottom-tabs | ^5.0.7 |
| react-native-paper                     | ^3.6.0 |
| react-native                           | 36.0.0 |
| expo                                   |  ^36.0.2 |
| node                                   | v13.5.0 |
| npm or yarn                            | 6.13.4 |

**Comment by fvsch** [comment]
It looks like there's some kind of default animation with a fade effect, probably using opacity and/or a transform.

The lighter background color might be coming from the parent screen's color. So one solution would be to use the same background color on the tab screens and on the parent screen.

**Comment by jinsunee** [comment]
@fvsch Thanks to you! I fixed this issue 😊

**Comment by Cronusl** [comment]
How to fix it?  I am also facing same issue
