### ISSUE TITLE
[Web] Two major Issues with createMaterialTopTabNavigator on Web

### ISSUE THREAD

**Issue by resdevd** [react-navigation/react-navigation#7695]
**Current Behavior**
- What code are you running and what is happening?
```
import * as React from 'react';
import { Text, View, StyleSheet } from 'react-native';
import {NavigationContainer, DarkTheme} from '@react-navigation/native'
import {createMaterialTopTabNavigator} from '@react-navigation/material-top-tabs'

const Home = () => {
  return(
    <View>
    <Text>home</Text>
    </View>
  )
}

const About = () => {
  return(
    <View>
    <Text>about</Text>
    </View>
  )
}

const Tab = createMaterialTopTabNavigator()

const RootNavigator = () => {
return(
  <View
  style={styles.container}
  >
         <Tab.Navigator
            initialRouteName='home'
        >
            <Tab.Screen name='home' component={Home}/>
            <Tab.Screen name='about' component={About}/>
         </Tab.Navigator>
         </View>
)
}

 const App = () => {
    return (
      
                    <NavigationContainer
                        // theme={DarkTheme}
                     >
                        <RootNavigator/>
                    </NavigationContainer>
    );
}

export default App

const styles = StyleSheet.create({
  container: {
    flex: 1,
    width: '100vw', //  Removing this cause Tabbar expand into uncontrollable width
  }
});

```
Currently On web, createMaterialTopTabNavigator has two major issues:
1) When used with default settings , the tab bar expands way beyond available browser's width that goes out of control.

2) TabBar always has empty whitespace at the bottom and right of Tab Bar. This empty white space doesn't seem to get removed with any style changes.

- Include a screenshot or video if it makes sense.

Regarding first issue out of control TabBar expansion on the web. Refer to following expo snack -
[https://snack.expo.io/@resdevd/forlorn-pretzels](https://snack.expo.io/@resdevd/forlorn-pretzels)
![Screen Shot 2020-02-28 at 12 55 55 PM](https://user-images.githubusercontent.com/29984943/75586666-ca280200-5a29-11ea-9577-9949ee576f50.png)
In the above screen hot, tabBars went beyond browsers view
As a temporary workaround, one can add **width: '100vw',** setting to stop width expansion.

Regarding empty whitespace, in the same snack expo after applying **width: '100vw',** style, you can notice empty white space at the bottom and right of tabbar.
![Screen Shot 2020-02-28 at 12 56 29 PM](https://user-images.githubusercontent.com/29984943/75586778-ecba1b00-5a29-11ea-87db-8cab34cd0c09.png)

This can also be observed in the example by @emanuelmd the TopTabNavigator always has sticky empty white space at the bottom and right. 
https://deploy-preview-7689--react-navigation-example.netlify.com/material-top-tabs/Chat
Screenshot:
![Screen Shot 2020-02-28 at 12 14 37 PM](https://user-images.githubusercontent.com/29984943/75584482-af9f5a00-5a24-11ea-8fa4-78decd62f8a0.png)

**Expected Behavior**

- What do you expect should be happening?
TopTabBar should not expand uncontrollably and TopTabNavigator should not produce empty white space around it.
- Include a screenshot or video if it makes sense.
None
**How to reproduce**

- You must provide a way to reproduce the problem. If you are having an issue with your machine or build tools, the issue belongs on another repository as that is outside of the scope of React Navigation.
- Either re-create the bug on [Snack](https://snack.expo.io) or link to a GitHub repository with code that reproduces the bug.
https://snack.expo.io/@resdevd/forlorn-pretzels

- Explain how to run the example app and any steps that we need to take to reproduce the issue from the example app.
Run the snack specified above, removing the style property width: '100vw', expands tabBar uncontrollably.
In the same snack, white space around tabBar can be noticed.

- Keep the repro code as simple as possible, with the minimum amount of code required to repro the issue.
- Before reporting an issue, make sure you are on latest version of the package.

**Your Environment**

| software                            | version |
| ----------------------------------- | ------- |
| iOS or Android                      | None (Web)
| @react-navigation/native            | 5.0.7
| @react-navigation/material-top-tabs | 5.1.0
| react-native-tab-view               | 2.13.0
| react-native                        | expo-default
| expo                                | 36.0.1
| node                                | 13.7.0
| npm or yarn                         | yarn

**Comment by mikaboz** [comment]
Same issue !

**Comment by satya164** [comment]
I checked the snack with latest versions of everything and cannot repro the issues mentioned, so I'm assuming they are fixed. If they are still present, please open a new issue or comment here.
