### ISSUE TITLE
Navigating to Nested Stack Navigator Doesn't Show Go Back Button

### ISSUE THREAD

**Issue by brycedeneen** [react-navigation/react-navigation#7698]
**Current Behavior**

I have a Bottom Tab Navigator that controls the main bottom navigation. Each "tab" is a stack navigation component. When I navigate from a screen in a different tab to a nested page in a stack navigator, the goback button does not show (but if i manually use "navigation.goBack()" it takes me where I want to go.

From my Home Component I'm navigating to a nested appointment details page using below:

return navigation.navigate('Appointments', {
                        screen: 'Appointment Details',
                        params: {
                            appointmentId: activity.id ?? ''
                        }
                    })

**Expected Behavior**

I expect the Go Back button to show and when pressed goBack to the source page (which actually works if I manually trigger goback);

  const goBack = () => {
    navigation.goBack();
}

**How to reproduce**
see code snippets above

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |
    "@react-navigation/bottom-tabs": "^5.1.0",
    "@react-navigation/native": "^5.0.8",
    "@react-navigation/stack": "^5.1.0",
    "react-native": "0.61.5",
    "react-navigation": "^4.2.2"

**Comment by brycedeneen** [comment]
Wanted to add one more sort of interesting thing. This ONLY happens the first time the app is loaded. if I navigate to the other stack navigator via the tab navigator, the back button shows correctly going forward. If I reload the app then it starts again, but once I navigate to the other stack at least once, the back button appears correctly.

**Comment by WoLewicki** [comment]
Could you provide a snack with a minimal repro of the issue?

**Comment by adamck** [comment]
FWIW, and I just have nested stacks rather than a Tab Nav involved, but I solved this issue by calling navigate and then push instead of navigating directly to the nested screen.

```
navigate(parentStack)
push(nestedStackScreen)
```

**Comment by brycedeneen** [comment]
@adamck I meant to post that I also had the same solution that worked for me. Thanks for confirming!

**Comment by WoLewicki** [comment]
Looks like you solved the issue, I'm closing it.

**Comment by alizahid** [comment]
```
navigate(parentStack)
push(nestedStackScreen)
```

@adamck Is this the right way to do this? I'm navigating to the nested route from a component where I'm accessing `navigation` from the `useNavigation` hook which apparently doesn't have `push`. So I've got the second `navigate` in a `setTimeout` because it doesn't work in the same cycle. But the timeout feels a bit iffy. Ideas?

**Comment by JustynaKK** [comment]
I have the same situation, bottom tab navigator, where every tab is the stack navigator.  
tabs: A - A1 - A2
        B - B1 - B2
When I go for the first time A -> B -> B1, then B1 is working as it should, has back button and it is on top of B screen. However if I am in A and do navigation.navigate(B1) without previously going to B, then B1 screen is open, and does not have back button, and it seems as it is rendered as the first in this stack. (Normally If I am in nested screen and I will click on the tab button, it is bringing me back to base of the stack, here is staying in B1, as this is base). As above, setTimeout does not feel as the proper way.

**Comment by WoLewicki** [comment]
@JustynaKK It is the correct behavior since it is not implied anywhere that the `B` screen should always be rendered before `B1`.  If you want the `B` screen to always be rendered, you can set `lazy` prop to `false` in the tabs navigator and then it will render the initial route for `B` navigator at the beginning.

**Comment by alizahid** [comment]
I feel like this is a bug.

There are two approaches to solve this:

```typescript
navigate('Navigator', {
  screen: 'Screen'
}```

**Comment by alizahid** [comment]
I feel like this is a bug.

There are two approaches to solve this:

First;
```typescript
navigate('Navigator', {
  screen: 'Screen'
})
```

Second;
```typescript
navigate('Navigator')
push('Screen')
```

However, the first one then doesn't allow back.
And the second one doesn't work because there's no navigator available immediately to handle the `push` call.

I've tried wrapping it in a `setTimeout`, but that feels like a dirty hack and doesn't work all the time either. Eg, if there's a slight delay because of device performance or any other reason.

I think if we had a callback on `navigate`, that would be ideal. Something like;

```typescript
navigate('Navigator', () => push('Screen'))
```

But I'm open to whatever is the best available solution right now so I can ship the code.

@adamck @brycedeneen Can you please share what worked for you?

**Comment by compojoom** [comment]
I created an issue over at the docs repo: https://github.com/react-navigation/react-navigation.github.io/issues/731

I was thinking about the same problem and wonder what the recommended approach is. SetTimeout really feels strange.

**Comment by brycedeneen** [comment]
What has worked for me is setting lazy to false. I didn't see anything in the documentation as to downsides of this, so any thoughts?

ex:

`    <BottomTabNav.Navigator
      tabBarOptions={{
        // showIcon: true,
      }}
      lazy={false}
    >
`

**Comment by daxilshah** [comment]
I'm not sure how or why! but navigation.push actually worked for me!
All i had to do was providing full route path in navigation.push method and it worked!

`navigation.push('RootApp', {
       screen: 'SomeList',
       params: {
            screen: 'SomeDetail',
            params: data,
        },
    });`

Here I have RootApp as Stack Screen which is of type DrawerNavigator component. SomeList is Drawer.Screen inside RootApp, which again has Stack Navigator and contains multiple screens out of which SomeDetail is one of those screens.

**Comment by alizahid** [comment]
I will try `push` instead of `navigate` and see what happens.

**Comment by rusyurchenko** [comment]
@daxilshah I suppose it worked for you because of another type of navigator. `push` didn't work with `TabNavigator`. 

Plain `navigate` with a corresponding nested routes scheme works with `lazy: false` for me, but I still think this is kind of trick and could lead to some other bugs as described here: #7908

**Comment by Awfulnaut** [comment]
@WoLewicki solved it for me. I added `lazy={false}` to my `<Tab.Navigator>` and now it works perfectly. No need to mess with navigating to the stack, then pushing a screen. Just disable lazy.

**Comment by compojoom** [comment]
@Awfulnaut `lazy={false}`is not a real solution for a lot of people. Imagine the following situation. You have 3 tabs. Every tab has a redux selector that grab few hundred items, sorts them, manipulates them and then renders something. Depending on how intensive the things that you do on those tabs are you might be adding a lot of seconds to the startup time of your app. And for what? For the user just to see something on your first tab and to close the app without interacting without the other tabs...

**Comment by rusyurchenko** [comment]
After some tries, the following worked for me without defining `lazy: false`: https://reactnavigation.org/docs/nesting-navigators#rendering-initial-route-defined-in-the-navigator

**Comment by WoLewicki** [comment]
Yes, as @rusyurchenko said, you can now use this new option to achieve the behavior.

**Comment by Awfulnaut** [comment]
@rusyurchenko what exactly does your navigation event look like? When I pass in the option `initial: false`, the behavior does not change (ie. there is still no back button). Here's mine:
```
navigator.navigate('AppointmentStack', {
    screen: 'Login',
    initial: false,
  })
```

**Comment by lukechinworth** [comment]
`initial: false` wasn't working for me either on 5.1, but it did work when I update to the latest.

**Comment by tayloraleach** [comment]
`initial: false` worked for me. Thank you!

**Comment by MatthewMarkgraaff** [comment]
If like me, you were wondering why you weren't getting a native 'back' control when navigation to a screen in a nested route definition, ensure you have a `initialRouteName` set on the root node of your navigator definition. It should point to the 'root screen' of that collection of routes.

**Comment by vostvesh** [comment]
I faced the same issue. And it helped me to install headerMode="none" in the parent Navigator

**Comment by chrispaynter** [comment]
I'm wondering if there a way to specify initial when defining the configuration for deep links, such as here - https://reactnavigation.org/docs/configuring-links/#advanced-cases

It's possible to specify `initial` via the navigate API when using the navigation prop, but we have a need to have the back button history available when linking to a page from a deep link.

The only way we've identified this is possible is to manually handle the back button in the screen that is being linked to.

Any one been able to achieve this using initial or some similar approach?

**Comment by iainheng** [comment]
I'm having the same issue as  @JustynaKK 

> I have the same situation, bottom tab navigator, where every tab is the stack navigator.
> tabs: A - A1 - A2
> B - B1 - B2
> When I go for the first time A -> B -> B1, then B1 is working as it should, has back button and it is on top of B screen. However if I am in A and do navigation.navigate(B1) without previously going to B, then B1 screen is open, and does not have back button, and it seems as it is rendered as the first in this stack. (Normally If I am in nested screen and I will click on the tab button, it is bringing me back to base of the stack, here is staying in B1, as this is base). As above, setTimeout does not feel as the proper way.

Setting `lazy={false}` on my `Tab.Navigator` solved this issue for me.

**Comment by JDMathew** [comment]
@satya164 would you be able to weigh in on best practice / a solution for this navigation issue. My understanding is that while `lazy={false}` solves the issue it may cause performance issues for bigger apps. It also doesn't seem like the right solution but rather a work around. 

React Navigation now uses dynamic configuration which is the reason for `lazy={false}` solving the above issue as it forces the stack navigators in all tabs to render on initial load.
> with dynamic configuration, React Navigation doesn't know which screens are available and where until the navigator containing the screen renders. Normally, a screen doesn't render its contents until you navigate to it, so the configuration of navigators which haven't rendered is not yet available. This makes it necessary to specify the hierarchy you're navigating to.

It seems like another possible solution is to navigate to an alternative tab is with `navigation.push()`and specifying the full hierarchy you wish to navigate too. This allows us to still use `lazy={true}`. I am fairly new to react navigation and am not sure if this is the intended use of `push` as it seems from documentation that one should navigate into nested navigators using 'navigation.navigate()'. If push is the correct solution for dealing with bottom tab navigation into alternative tabs it may be worth adding documentation about navigating into nested navigators on different tabs when lazy loading is true. ([Bottom tab navigator](https://reactnavigation.org/docs/bottom-tab-navigator/) docs).

I don't know the inner workings of the library but on the surface this looks like a bug.

**Comment by aphostrophy** [comment]
I don't like lazy={false} because it's bad for performance and also the option doesn't exist if you use materialBottomTabNavigator instead of the normal bottomTabNavigator

By default, when you navigate a screen in the nested navigator, the specified screen is used as the initial screen and the initial route prop on the navigator is ignored. The documentation said you can fix this by giving initial: false
navigation.navigate('Root', {
  screen: 'Settings',
  initial: false,
});

https://reactnavigation.org/docs/nesting-navigators/

**Comment by asolomonbf** [comment]
`initial: false` fixed it for me. Thanks folks.

**Comment by irothenbaum** [comment]
So `initial: false` is working in that it's now showing the back button and properly returns me to the initial screen in that stack when I execute a goBack, but after leaving and returning to that stack it's still showing the second page first (with a back button) and not the preferred initial screen.

My structure is:

Main (tab navigator)
  - Home (stack navigator)
    - H1
    - H2
  - Settings (stack navigator)
    - S1
    - S2

If I navigate from H1 to S2 with the following action (generated using `CommonActions.navigate` and dispatched):
```
{"type":"NAVIGATE","payload":{"name":"Settings","params":{"screen":"S2","initial":false}}}
```
S2 properly appears with a back button that returns to S1, but if I return to H1 and then click on the Settings button in the bottom nav bar, it takes me again to S2 with a back button that returns to S1. 

Ideally, if after returning to H1 and clicking the Settings button, it would take me to S1.


Any thoughts?

**Comment by thibaultcapelli** [comment]
Sorry about reopening this issue but is there a way to navigate back to the previous screen instaed of the initialRouteName of the targetted stack ?

**Comment by Lalmi-Issam** [comment]
Same issue here i tieed to use `backBehavior="history"` not working for me

**Comment by mattlewer** [comment]
> So `initial: false` is working in that it's now showing the back button and properly returns me to the initial screen in that stack when I execute a goBack, but after leaving and returning to that stack it's still showing the second page first (with a back button) and not the preferred initial screen.
> 
> My structure is:
> 
> Main (tab navigator)
> 
> * Home (stack navigator)
>   
>   * H1
>   * H2
> * Settings (stack navigator)
>   
>   * S1
>   * S2
> 
> If I navigate from H1 to S2 with the following action (generated using `CommonActions.navigate` and dispatched):
> 
> ```
> {"type":"NAVIGATE","payload":{"name":"Settings","params":{"screen":"S2","initial":false}}}
> ```
> 
> S2 properly appears with a back button that returns to S1, but if I return to H1 and then click on the Settings button in the bottom nav bar, it takes me again to S2 with a back button that returns to S1.
> 
> Ideally, if after returning to H1 and clicking the Settings button, it would take me to S1.
> 
> Any thoughts?

I was all excited that `initial: false` had fixed the problem and then ran into the exact same issue. Did you manage to solve?

**Comment by irothenbaum** [comment]
> I was all excited that `initial: false` had fixed the problem and then ran into the exact same issue. Did you manage to solve?

No. We ended up restructuring our app so that all pages are in one monolithic stack and the hirearchy of sub pages is enforced purely through the UI - very hacky. 

At this point we're only using react-navigation out of momentum (would be a pain to pull it out) and its convenience for rendering headers on different devices.
