### ISSUE TITLE
How I hide bottom tab in V5?  

### ISSUE THREAD

**Issue by ruyjfs** [react-navigation/react-navigation#7699]
Hi guis!!! ✋🏼

In the documentation show this:

> A tab navigator contains a stack and you want to hide the tab bar on specific screens

> See the documentation here

When i clicked on link of documentation, I will redirect to: https://reactnavigation.org/docs/tab-based-navigation/screen-options-resolution.html#a-tab-navigator-contains-a-stack-and-you-want-to-hide-the-tab-bar-on-specific-screens

But I got 404, page not found.

Thanks!

**Comment by choychris** [comment]
The correct documentation link should be this:
https://reactnavigation.org/docs/screen-options-resolution#setting-parent-screen-options-based-on-child-navigators-state

**Comment by WoLewicki** [comment]
This issue refers to https://github.com/react-navigation/react-navigation.github.io, so I will close it here. Thanks for the feedback, I will change it in docs!

**Comment by nomi9995** [comment]
here is a solution https://stackoverflow.com/a/62134625/8079868

**Comment by mudassir-iqbal** [comment]
Just add this code in useEffect of that screen where you wants to hide the bottom-bar.

useEffect(() => {
    const parent = props.navigation.dangerouslyGetParent();
    // Hide tab-bar
    parent.setOptions({
      tabBarVisible: false,
    });

    // Set visible true while exiting the screen.
    return () =>
      parent.setOptions({
        tabBarVisible: true,
      });
  }, []);
