### ISSUE TITLE
Why is there no createSwitchNavigator in 5.x version

### ISSUE THREAD

**Issue by CooLNuanfeng** [react-navigation/react-navigation#7702]
Why is there no createSwitchNavigator in 5.x version, so how to implement the welcome page when the app is first launched

**Comment by OscarYuen** [comment]
You could use conditional rendering(like checking if the user has login yet) in your stack/tab navigator to render what screens should be seen.

**Comment by WoLewicki** [comment]
You can use https://reactnavigation.org/docs/auth-flow examples. Does this fix your issue?

**Comment by Abhishek9634** [comment]
I feel That's a really bad practice conditional rendering
**createSwitchNavigator** is much better option rather than adding conditions :|

**Comment by natearmagost** [comment]
@WoLewicki 
An Auth flow is a minimal example. `isLoggedIn`... I understand that case. Just set isLoggedIn `false` and it boots the user out.

But in my app I have 4 stacks on the top level switch and could navigate with navigation.navigate('Stack1Screen1') from a nested view within 'Stack2Details'.

Now we have to set up our own state management (setState, Context, Redux, etc.) just to switch screens. We can't navigate from switch case to switch case. I'm trying to update to v5, my code is v3, so I might be a bit out of the loop, but it seems like we lost some of the benefits of react-navigation... the routing and the navigation from view to view.

**Comment by taranpalsingh** [comment]
> But in my app I have 4 stacks on the top level switch and could navigate with navigation.navigate('Stack1Screen1') from a nested view within 'Stack2Details'.

Facing the same issue, I am upgrading an app from v4 to v5+, in which we had 5 stacks on the top level using createSwitchNavigator. Have been trying to solve it for the past 5 days, but no luck yet.
Can anybody please help?
