### ISSUE TITLE
Navigation state is undesirably getting reset on App.js screen re-render

### ISSUE THREAD

**Issue by rgavinc** [react-navigation/react-navigation#7703]
**Current Behavior**

I am using a theme with my app which I allow to change dynamically. I am using the react hook `useContext` for my theme so that I can access it from anywhere in the app. When the theme is updated it will be changed at the very top level of the app in App.js. Everytime the theme is changed from insde the app react navigation seems to forget its state and gets reset to the default. Note: This issue seems to only appear when using nested navigators

**Expected Behavior**

The react navigation state should remain the same.

**How to reproduce**

I've created a simplified example of my issue using the react hook `useState`. This example can be found [here](https://snack.expo.io/@gavinrob92/b2e5ad). To reproduce the issue of the navigation state being reset go to the Details screen and click on the button `Update Count`. You should see that by clicking the button the app navigates back to the Home screen.

**Comment by WoLewicki** [comment]
Have you tried to use theme handling provided by react-navigation:  https://reactnavigation.org/docs/themes In your example, you are updating the state of the App component, in which there is the navigation container, I think this is the problem.

**Comment by rgavinc** [comment]
> Have you tried to use theme handling provided by react-navigation: https://reactnavigation.org/docs/themes In your example, you are updating the state of the App component, in which there is the navigation container, I think this is the problem.

Sure I could use teact-navigation's themes but I would still run into the same issue by allowing the theme to be updated dynamically. I want the bottom and top navigation bars colors to be controlled by the theme so I must update the state of the App component, in which there is a navigation controller.

**Comment by satya164** [comment]
Your state gets lost on re-render because you're creating components during render, which causes new components to be created every render and causes a remount. This is unrelated to React Navigation.

**Comment by rgavinc** [comment]
> Your state gets lost on re-render because you're creating components during render, which causes new components to be created every render and causes a remount. This is unrelated to React Navigation.

How would I go about updating the theme without kicking off a re-render then @satya164 ? How does React Navigation want me to update the themes dynamically? Would you be able to provide an example? If not, I feel like this should be reopened.

**Comment by satya164** [comment]
> Would you be able to provide an example? If not, I feel like this should be reopened

The issue tracker is reserved for bug reports regarding React Navigation. Your question is unrelated to React Navigation and you need post it on StackOverflow.

**Comment by rgavinc** [comment]
@satya164 this is my question regarding React Navigation - `How does React Navigation want me to update the themes dynamically?` Is changing the theme dynamically with React Navigation simply not a feature?

**Comment by satya164** [comment]
React Navigation doesn't care about how you manage your themes. Your state is lost not because re-render, but because you are **creating components in render** which causes a **remount** on re-render. If you do the same without React Navigation, you'll have the same issue.

**Comment by NicWickman** [comment]
Could you elaborate on what to do differently in the provided Snack? It's not clear to me what about this code should be different, it looks just like any other normal React code I've seen. Is there some serious error here?
