### ISSUE TITLE
nested Stack Navigator in Drawer cannot jump to each other

### ISSUE THREAD

**Issue by chj-damon** [react-navigation/react-navigation#7704]
**Current Behavior**
currently, I have a navigator structure like below:

```js
DrawerNavigator
|- HomeStack
    |- HomeScreen
    |- DetailScreen
|- MineStack
	|- MineScreen
	|- ProfileScreen
```

when the app starts, I want to jump from HomeScreen to MineScreen, but it will fail and report an error like: `The action 'NAVIGATE' with payload {"name":"Mine"} was not handled by any navigator`.
![image](https://user-images.githubusercontent.com/4902684/75666710-408a6580-5cb1-11ea-853c-d021083dee85.png)

But, if I activate MineStack then jump from HomeScreen to MineScreen, it works.

**Expected Behavior**

navigate should work even though I didn't activate MineStack

**How to reproduce**

- You must provide a way to reproduce the problem. If you are having an issue with your machine or build tools, the issue belongs on another repository as that is outside of the scope of React Navigation.
- Either re-create the bug on [Snack](https://snack.expo.io) or link to a GitHub repository with code that reproduces the bug.
- Explain how to run the example app and any steps that we need to take to reproduce the issue from the example app.
- Keep the repro code as simple as possible, with the minimum amount of code required to repro the issue.
- Before reporting an issue, make sure you are on latest version of the package.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |IOS12
| @react-navigation/native       |5.0.8
| @react-navigation/drawer       |5.1.0
| react-native-reanimated        |1.7.0
| react-native-gesture-handler   |1.6.0
| react-native-safe-area-context |0.7.3
| react-native-screens           |2.0.0-beta.2
| react-native                   |0.61.5
| expo                           |
| node                           |v10.16.0
| npm or yarn                    |6.13.7

**Comment by WoLewicki** [comment]
It is like this due to a fact that the screens are lazy-rendered by default, so as long as you don't navigate to the second drawer screen, the second stack navigator doesn't exist, so the `MineScreen` as well. Check https://reactnavigation.org/docs/drawer-navigator#lazy and set it to `true` to render all drawer screens at the beginning. Does this fix your issue?

**Comment by chj-damon** [comment]
@WoLewicki Thank you. It works now.
