### ISSUE TITLE
what is the best way to organize navigator？

### ISSUE THREAD

**Issue by chj-damon** [react-navigation/react-navigation#7705]
I read the document https://reactnavigation.org/docs/tab-based-navigation#a-stack-navigator-for-each-tab, it says `Usually tabs don't just display one screen — for example, on your Twitter feed, you can tap on a tweet and it brings you to a new screen within that tab with all of the replies. You can think of this as there being separate navigation stacks within each tab, and that's exactly how we will model it in React Navigation.`
the navigator structure looks like this:
```js
RootTabNavigator
|- Stack1
	|- Screen1
|- Stack2
	|- Screen2
|- Stack3
	|- Screen3
```
or
```js
RootDrawerNavigator
|- Stack1
	|- Screen1
|- Stack2
	|- Screen2
|- Stack3
	|- Screen3
```

why is it the best way to organize like this? in my opinion, I can put all the screen and tab navigator and drawer navigator in one stack navigator, like this:
```js
RootStackNavigator
|- Screen1
|- TabNavigator
	|- Screen4
	|- Screen5
|- DrawerNavigator
	|- Screen6
	|- Screen7
|- Screen2
|- Screen3
```

**Comment by WoLewicki** [comment]
It just seems intuitive to do it like this. Why did you put "bug" label in the issue?

**Comment by chj-damon** [comment]
I don't know. I cannot remove the label.

**Comment by WoLewicki** [comment]
It doesn't seem like an issue, I'm closing it. Feel free to ask questions here if you have any other.
