### ISSUE TITLE
navigation.getParam('key', 'default') don't work

### ISSUE THREAD

**Issue by HVHMobileDeveloper** [react-navigation/react-navigation#7706]
**Current Behavior**

first screen: 
 this.props.navigation.navigate('TargetScreen', {
        key: 'data',
      });

seconds screen:

const { navigation } = this.props;
    const itemId = navigation.getParam('key', 'NO-ID');

**Comment by WoLewicki** [comment]
Params are now accessed through route.params. Check https://reactnavigation.org/docs/params

**Comment by HVHMobileDeveloper** [comment]
Thanks.

Vào Th 3, 3 thg 3, 2020 vào lúc 01:04 Wojciech Lewicki <
notifications@github.com> đã viết:
