### ISSUE TITLE
nativeStackNavigator = page not found in docs 404

### ISSUE THREAD

**Issue by rusakovic** [react-navigation/react-navigation#7707]
Hello.

Please, check the link
https://reactnavigation.org/docs/en/native-stack-navigator.html

I found the link from search bar into your documentation.

**Comment by WoLewicki** [comment]
Native stack navigator is no longer maintained by React Navigation and is not available in docs, so this is the search engine bug. This issue refers to https://github.com/react-navigation/react-navigation.github.io, can you post the issue there? I am closing it here.
