### ISSUE TITLE
Example Code in Docs has a size bug

### ISSUE THREAD

**Issue by Kaschman** [react-navigation/react-navigation#7708]
**Current Behavior**

- Following the example code at https://reactnavigation.org/docs/material-bottom-tab-navigator I get a bug where the size of the `tabBarIcon` is undefined, resulting in the icon showing up smaller than it should be.

**Expected Behavior**

- The `tabBarIcon` should have a size of 24

**How to reproduce**

- Follow the example code

**Suggested Fix**

- Digging into the [source code](https://github.com/react-navigation/react-navigation/blob/master/packages/material-bottom-tabs/src/views/MaterialBottomTabView.tsx) it appears the `MaterialBottomTabNavigator` has a `tabBarIcon` function signature of `{ focused, color }` whereas the `BottomTabNavigator` has a function signature of `{ focused, color, size }`

- Error was probably introduced by a copy/paste from the BottomTabNavigator example code.

- Quick fix is to update the docs to show 
```
tabBarIcon: ({ color }) => (
     <MaterialCommunityIcons name="home" color={color} size={24} />
),
```

- Another option considering `MaterialCommunityIcons` are supported natively:
```
tabBarIcon: 'home'
```

- Better fix is to have `BottomTabNavigator` and `MaterialBottomTabNavigator` have the same API for `tabBarIcon`

**Comment by WoLewicki** [comment]
Thanks! Could you make a PR in https://github.com/react-navigation/react-navigation.github.io ? It belongs to that repo, so I am closing this this issue.
