### ISSUE TITLE
Is there a way to make enableSwipe={false} on a custom tabNavigator

### ISSUE THREAD

**Issue by shawnFallon** [react-navigation/react-navigation#7710]
I have created a TopTabNavigator using a set of custom tabs. 

```
const authNav= createMaterialTopTabNavigator();
    <authNav.Navigator
      tabBar={props => <SignupTabs {...props} />}
     ......
    </authNav.Navigator>
```
However, I want to turn off the swipe functionality in the custom tab component (SignupTabs).

Is there a way to turn off the Swipe functionality on a custom Tab component?  

Cheers in Advance.

-------------------------------------------------
packages:
"react-native": "0.61.5",
    "@react-navigation/bottom-tabs": "^5.0.1",
    "@react-navigation/drawer": "^5.0.1",
    "@react-navigation/material-top-tabs": "^5.0.2",
    "@react-navigation/native": "^5.0.1",
    "@react-navigation/stack": "^5.0.1",

**Comment by WoLewicki** [comment]
https://reactnavigation.org/docs/material-top-tab-navigator#swipeenabled can be what you are looking for. Please look at the documentation and/or ask on the channels instead of reporting it as a bug.
