### ISSUE TITLE
Back function goBack() crash on Android Pie (9)

### ISSUE THREAD

**Issue by nateblog** [react-navigation/react-navigation#7711]
**Current Behavior**

When you trigger the goBack() function twice in android pie the app crashed, while in lower android versions it works just fine.

**Expected Behavior**

It should not crash when going back to the previous screens.

**How to reproduce**

1. Create an app with 4 to 5 screens.

2. Create a button that will route from first to the last screen.

3. Trigger the back button from the last screen down to the first screen.

Crash happens during the second time you tap the back button.

"@react-navigation/bottom-tabs": "5.1.0",
"@react-navigation/native": "5.0.8",
"@react-navigation/stack": "5.1.0",

**Comment by nateblog** [comment]
I think the problem has something to do with my app structure, the weird thing is that on lower android version everything works fine but on android pie it crashes... anyway I will investigate further and update this if I find something... I will close this for now.

**Comment by chj-damon** [comment]
have you resolved it? I'm facing the same problem now.

**Comment by chj-damon** [comment]
what does your app structure look like? Mine looks like below:
```js
NavigationContainer
	|- StackNavigator
	|- Drawer
		|- Screen01
		|- Screen02
	|- Screen1
	|- Screen2
	|- Screen3
	|- ...
```
