### ISSUE TITLE
undefined is not object _core.NavigationActions.init

### ISSUE THREAD

**Issue by JherysVargas** [react-navigation/react-navigation#7712]
Could someone help me solve this error?
![errorNavigation](https://user-images.githubusercontent.com/39938693/75747202-4ea8a800-5cea-11ea-9b54-79d48c68b862.jpeg)

**Comment by satya164** [comment]
Closing due to no response.

**Comment by sallarahmed** [comment]
I solved issue by deleting node_modules and install dependencies using yarn instead of npm
