### ISSUE TITLE
Navigation didn't work, when appstate is background.

### ISSUE THREAD

**Issue by bhavik66** [react-navigation/react-navigation#7713]
When we start native Android activity in picture in picture mode and try to navigate another screen from main screen (react native screen) at that time navigation didn't work.

I check appstate and I think when appstate is background at that time navigation did not work.

check this video for more detail

https://drive.google.com/file/d/1PAhzp6VKNoqzN7txUDCCPDE_NPNrIYi6/view?usp=sharing

**Comment by satya164** [comment]
Closing due to no response.

**Comment by Symous** [comment]
I met the same issue, is there any solution here now? @bhavik66

**Comment by hengkx** [comment]
ios same issue
