### ISSUE TITLE
[RN5] Can't change tab content container background color

### ISSUE THREAD

**Issue by mgambati** [react-navigation/react-navigation#7716]
**Current Behavior**
![ezgif-6-e5ae3269dd43](https://user-images.githubusercontent.com/813131/75780219-53447f00-5d31-11ea-92e2-e6c2e8e806d4.gif)

On dark mode, with shifting enabled, the screen flashes white on screen transition.

**Expected Behavior**

Allow to change the tabs content container style or just set RN4 transparentCard prop.

**How to reproduce**

Minimal repro: https://snack.expo.io/@mgambati/eee2b6

**Comment by eriveltonelias** [comment]
Hey @mgambati,

you should use `tabStyle` from `tabBarOptions`  https://reactnavigation.org/docs/bottom-tab-navigator/#tabbaroptions

**Comment by mgambati** [comment]
The problem is that material bottom tabs doesn't have that prop.

**Comment by satya164** [comment]
Set React Navigation's theme to dark https://reactnavigation.org/docs/themes#built-in-themes

**Comment by jambu43** [comment]
`<Navigator
      screenOptions={{
        tabBarActiveTintColor: theme.colors.main,
        tabBarInactiveTintColor: theme.colors.text_detail,
        tabBarShowLabel: false,
        tabBarStyle: {
          paddingVertical: Platform.OS === 'ios' ? 20 : 0,
          height: 78,
          backgroundColor: theme.colors.background_primary
        }
      }}
    >`
