### ISSUE TITLE
Screen "shaking" when I navigate back

### ISSUE THREAD

**Issue by georgiosd** [react-navigation/react-navigation#7718]
With react-navigation 4, on expo, on some screens, when I press "Back" after a screen, the top "shakes".

I know this is hard to comprehend without seeing but I wonder if anyone else has seen this and found what causes it?

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Expo
| react-navigation       | 4.0.10
| react-navigation-stack        | 1.10.3
| react-native-gesture-handler   | ~1.5.2
| react-native-screens           | 2.0.0-alpha.12
| react-native                   | https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz
| expo                           | ~36.0.2
| node                           | 12.9.1
| yarn                    | 1.22.0

**Comment by rafamrs** [comment]
This also happened to me, not only on back, but on navigate also. For some reason, changing the components name, worked for me... 🤔

**Comment by georgiosd** [comment]
@rafamrs do you remember the specifics?? Was it long and you made it short or something?

**Comment by rafamrs** [comment]
I dont have a clue why it worked, but I changed screen name from Today.js to TodayDetails.js and it worked. I replaced class name, and imports everything to TodayDetails and worked.

It's very strange, it was flickering/jumping when I navigated from WeekOverview.js to Today.js and when I click back button it also flickered.

**Comment by Kyonru** [comment]
I have a similar issue:
https://github.com/Kyonru/just-a-review-app
![ezgif-2-80c0dc040682](https://user-images.githubusercontent.com/17935828/76047742-14cde080-5f3a-11ea-9b4b-944e4dad7d5b.gif)

**Comment by satya164** [comment]
@Kyonru Use https://github.com/th3rdwave/react-native-safe-area-context instead of SafeAreaView from React Native.

**Comment by Kyonru** [comment]
@satya164 It kinda worked, it doesn't shake as much as it did. But now I facing this [issue](https://github.com/th3rdwave/react-native-safe-area-context/issues/60)... I guess I'm using it wrong.

**Comment by Guuz** [comment]
I've seen this shaking issue too. Can't reproduce it anymore though...

**Comment by rafmst** [comment]
I noticed this bug again and I found what is causing it. Basically I have a stack within a tabs navigator, and when I navigate inside I hide the bottom tabs and that is causing the flicker, navigating while hiding the bottom tabs

**Comment by yasirtrimulabs** [comment]
> I noticed this bug again and I found what is causing it. Basically I have a stack within a tabs navigator, and when I navigate inside I hide the bottom tabs and that is causing the flicker, navigating while hiding the bottom tabs

I have also a stack inside the tabs navigator but I am not hiding bottom tabs. I am also facing the same flickering and also sometime the internal stack inside the stack in tabs navigator goes behind the bottom tab if I switch between the tabs. Any fixes??

**Comment by rafmst** [comment]
I didn't found any fixes for it, what I ended up doing was reworking my stacks :/ which is an ugly fix

**Comment by georgiosd** [comment]
Everyone, it turns out that the problem was for me was that I was mixing components from react native paper (mui). If this is the case for any of you I'm happy to dig in my notes and tell you exactly what the problem was.

**Comment by luckytiger1** [comment]
Hello everyone, I'm facing the similar problem of shaking screen on refresh, does anyone know how to fix it?

**Comment by luckytiger1** [comment]
> Hello everyone, I'm facing the similar problem of shaking screen on refresh, does anyone know how to fix it?

Problem was incorrectly placed components, fixed it by moving Header component outside of conditional rendering.

**Comment by beterfysiek** [comment]
For me it was placing a SafeAreaView inside an scrollview

**Comment by avinash-synapsesai** [comment]
I am also getting same problem when I am hiding custom header in one of my screen with `headerShown: false` , removing it worked. However I had to use `header: ()=>null` in order to hide my header.

**Comment by gazedash** [comment]
+1111111111111 +1

**Comment by csr15** [comment]
> I am also getting same problem when I am hiding custom header in one of my screen with `headerShown: false` , removing it worked. However I had to use `header: ()=>null` in order to hide my header.

yes by using `header:  null` in navigationOptions the screen is shaking

**Comment by hariskhalid366** [comment]
I got the same error and while I was trying to fix it my components also started jumping when the screen renders

**Comment by kamaladdi34** [comment]
Try this
```
headerShown: false,
tabBarShowLabel: false,
```
