### ISSUE TITLE
Error : Animated events must have event data 

### ISSUE THREAD

**Issue by anastely** [react-navigation/react-navigation#7722]
**Current Behavior**

My App crashed when I swipe to tabs on **Android** And got this error

>  **Animated events must have event data** 

[screenshot](https://i.imgur.com/sDA00Ld.png)

Code snippet 
```

import {createAppContainer} from 'react-navigation';
import {createMaterialTopTabNavigator} from 'react-navigation-tabs';
import MyFavorite from '../MyFavorite/MyFavorite';
import YourPlaylist from '../YourPlaylist/YourPlaylist';

const TabNavigator = createMaterialTopTabNavigator(
  {
    Playlist: {
      screen: YourPlaylist,
    },
    Favorite: {
      screen: MyFavorite,
    },
  },
  {
    lazy: false,
    navigatorStyle: {
      statusBarTextColorScheme: 'light',
      statusBarColor: '#222325',
    },
    navigationOptions: ({navigation}) => ({
      headerTitleStyle: {
        color: '#fff',
      },
    }),
    tabBarOptions: {
      style: {
        backgroundColor: '#ff4865',
      },
      activeTintColor: '#fff',
      indicatorStyle: {
        backgroundColor: '#fff',
      },
    },
    animationEnabled: true,
  },
);

export default TabNavigator;

```

**Expected Behavior**

Android doesn't have a crash when I swipe.

**Your Environment**

| software                            | version |
| ----------------------------------- | ------- |
| iOS or Android                      | Android
| react-navigation      | 4.1.0
| react-navigation-tabs| 2.7.0
| react-native-gesture-handler | 1.5.3
| react-native                        | 0.61.5
| node                                | v10.16.3
| npm or yarn                         | yarn

**Comment by DGatere** [comment]
I am also affected by this behavior, it crashes constantly when using MaterialTopTabNavigator, I have a stack navigator with a nested top tab navigator for a chat area and swipe gestures just don't work as they should. Most of the time expo crashes with zero warning when I test on a device, and 100% of the time on an emulator, only managed to get the Animated events error once

**Comment by lander854** [comment]
same issue

**Comment by jakub-gonet** [comment]
Hi @anastely, @DGatere, @lander854,

could you guys please add a repro on [snack](https://snack.expo.io/)?

We can't really debug this issue without reproducing it locally.

**Comment by max-kim** [comment]
It happened with me when I wrapped one MaterialTopTabNavigator to other MaterialTopTabNavigator. I added dynamic count of screens in nested top tabs. The error occured with my nested MaterialTopTabNavigator when i passed single <Tab.Screen /> to <Tab.Container> and tried to swipe it. When I passed more then one screen it all was ok. Solution in my case was in adding 'swipeEnabled={screensArray.length > 1 ? true : false}' option to nested navigator, when I had single screen.

package.json:
{
  ...
  "@react-navigation/native": "^5.2.3",
  "@react-navigation/material-top-tabs": "^5.1.15",
  "react-native-reanimated": "^1.7.0",
  "react-native-gesture-handler": "^1.6.0",
  "react-native-tab-view": "^2.14.0",
  ...
}

**Comment by tuantu196** [comment]
i got same issue. Can anyone find solution to fix it?

**Comment by OsamaMukhtar** [comment]
Same issue here. Needs to be fixed

**Comment by kamalpandey** [comment]
Any update on this one?
