### ISSUE TITLE
Nested StackNavigator in modal has too much vertical padding

### ISSUE THREAD

**Issue by hammadj** [react-navigation/react-navigation#7723]
**Current Behavior**
When opening a modal using the StackNavigator + ModalPresentationIOS preset on devices with a notch, the Header has excess top padding (presumably as a safe area for the notch). The modal style doesn't require that padding since the whole header is below the notch.

![image](https://user-images.githubusercontent.com/7143583/75828545-565b6180-5d69-11ea-8d09-cb51203a8040.png)

Code:
```tsx
export const HomeNavigator: React.FC = () => (
  <Stack.Navigator
    initialRouteName={Screen.HOME}
    mode="modal"
    headerMode="none"
    screenOptions={{
      gestureEnabled: true,
      cardOverlayEnabled: true,
      ...TransitionPresets.ModalPresentationIOS,
    }}
  >
    <Stack.Screen name={Screen.HOME} component={Home} />
    <Stack.Screen name={Screen.SETTINGS} component={SettingsNavigator} />
  </Stack.Navigator>
);

```

**Expected Behavior**

The header should not have extra top padding. Here I manually had to set these options to replicate how the header should look:
```ts
    screenOptions={{
      headerStyle: { height: 56 },
      headerStatusBarHeight: 0,
    }}
```
![image](https://user-images.githubusercontent.com/7143583/75828808-ebf6f100-5d69-11ea-835c-15f5bf60101a.png)

**How to reproduce**

https://snack.expo.io/@hammadj/header-top-padding-repro

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | iOS
| @react-navigation/native       | 5.0.7
| @react-navigation/stack        | 5.0.9
| react-native-gesture-handler   | 1.5.3
| react-native-safe-area-context | 0.6.0
| react-native-screens           | 2.1.0
| react-native                   | Expo 36
| expo                           | 36
| node                           | 10.16
| npm or yarn                    | yarn 1

**Comment by WoLewicki** [comment]
For now, the workaround should be setting `headerStatusBarHeight` to 0 in `screenOptions` on deeper screens of the stack. It would be something like this: 

```
headerStatusBarHeight:
            props.navigation
              .dangerouslyGetState()
              .routes.indexOf(props.route) === 0
              ? undefined
              : 0,
```

**Comment by Guuz** [comment]
@satya164 / @WoLewicki This is a workaround. but the bug is still there. Shouldn't this issue be open? This prevents user from React Navigation to use the iOS 13 modals.
