### ISSUE TITLE
Redux devtools with "autoselect instance" -> will autoselect @react-navigation

### ISSUE THREAD

**Issue by jambon-beurre-vodka** [react-navigation/react-navigation#7726]
I use React Native Debugger to inspect the redux state of my react native app.

React navigation automatically creates an instance called "@react-navigation" in the redux devtools each time I live reload (see screenshot). 

With auto select instances turned on, @react-navigation takes precedence over the new redux store instance. It's very annoying because I must manually select the new redux store instance each time I live reload. 

<img width="916" alt="Screenshot 2020-03-04 at 12 53 29" src="https://user-images.githubusercontent.com/59906660/75877084-2d91a580-5e17-11ea-9dfc-9418b317238e.png">

**Comment by aymkin** [comment]
The same issue

* every load @react-navigation appears in the autoselected instances
* every time redux store has a different name
![download](https://user-images.githubusercontent.com/10321850/76186361-c55a0f80-61da-11ea-8091-999f395af562.png)

**Comment by TamerlanG** [comment]
The same issue, but whenever redux-dev-tools is open my navigation just becomes super slow. I'm talking like 30-40 seconds delay, but outside of debugging mode, it's working well.
