### ISSUE TITLE
bottom-tab-navigator gets hidden when I navigate to another screen using drawer

### ISSUE THREAD

**Issue by saur2729** [react-navigation/react-navigation#7728]
**Current Behavior**
I'm using the bottom tab and drawer navigator in my react-native project using expo. I'm using react-navigation v5 in my project.
I have nested Bottom Tab Navigator inside one of the drawer screens. I'm not sure why but when I navigate to another screen using drawer, I tend to lose bottom tab bar on that page. 
Even if I nest the drawer inside one of the screens of  bottom tab navigator, I won't be able to use the drawer when I  navigate to another screen using bottom tab navigator

**Expected Behavior**
Bottom tab navigator shouldn't disappear, it should be available on each drawer screen

I have tried cloning it here - https://snack.expo.io/rkC_VVFE8

**Comment by WoLewicki** [comment]
> I have nested Bottom Tab Navigator inside one of the drawer screens. I'm not sure why but when I navigate to another screen using drawer, I tend to lose bottom tab bar on that page.

You lose it because the bottom-tabs navigator is nested in the drawer's screen, not in the whole navigator, so it can't be available on any other drawer screen. I don't quite understand why would you like something like this to be available from the navigation's point of view. Could you provide a conceptual diagram of the navigator's structure you need?

**Comment by WoLewicki** [comment]
It is not possible and should not be possible. The other way you could do it is to add a bottom-tabs navigator for every drawer navigator's screen or drawer navigator for every bottom-tabs screen. Does this fix your issue?

**Comment by rhmedias** [comment]
> **Current Behavior**
> I'm using the bottom tab and drawer navigator in my react-native project using expo. I'm using react-navigation v5 in my project.
> I have nested Bottom Tab Navigator inside one of the drawer screens. I'm not sure why but when I navigate to another screen using drawer, I tend to lose bottom tab bar on that page.
> Even if I nest the drawer inside one of the screens of bottom tab navigator, I won't be able to use the drawer when I navigate to another screen using bottom tab navigator
> 
> **Expected Behavior**
> Bottom tab navigator shouldn't disappear, it should be available on each drawer screen
> 
> I have tried cloning it here - https://snack.expo.io/rkC_VVFE8

I am having this same issue with my project. Were you able to solve it? How?
