### ISSUE TITLE
Drawer not working

### ISSUE THREAD

**Issue by bkmed** [react-navigation/react-navigation#7730]
**Current Behavior**

drawertype="front" show black screen and drawertype="back" or slide show white screen
![Screenshot_20200305-112023](https://user-images.githubusercontent.com/15847412/75973050-d9e59180-5ed4-11ea-88cf-b7f88c021216.png)
![Screenshot_20200305-112654](https://user-images.githubusercontent.com/15847412/75973054-db16be80-5ed4-11ea-864c-0469eaa95259.png)

**Expected Behavior**

th emenu to be shown

**How to reproduce**

// drawer
const Drawer = createDrawerNavigator();
function AppDrawerNavigator () {
  return (
    <Drawer.Navigator 
      initialRouteName="Dashboard"
      drawerContent={ (props) => (
        <Menubar { ...props }/>
      ) }
      drawerPosition="left"
      lazy
      drawerType="slide"
      edgeWidth={ (DEVICE_WIDTH/2) }
      screenOptions={ {
        headerTintColor: WelcolColor.White,
        headerStyle: {backgroundColor: WelcolColor.Primary},
      } }
      drawerStyle={ {
        width: DEVICE_WIDTH,
        height: DEVICE_HEIGHT
      } }
    >
      <Drawer.Screen name="Dashboard" component={ DashboardStackNavigator }/>
    </Drawer.Navigator>
  );
}
*Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |
| @react-navigation/native    ^5.0.6   |
| @react-navigation/drawer   ^5.0.6    |
| react-native-reanimated      ^1.7.0  |
| react-native-gesture-handler ^1.6.0  |
| react-native-safe-area-context  ^0.7.3|
| react-native-screens       ^2.0.0-beta.8    |
| react-native         ^0.61.5            |
| node                           |
| npm or yarn                    |

**Comment by vimcat** [comment]
I had similar issues when implementing a custom Drawer component. Wrapping it with DrawerContentScrollView solved it for me.

`import { DrawerContentScrollView } from '@react-navigation/drawer'`

**Comment by bkmed** [comment]
its not working i have tried the exemple put in https://snack.expo.io/@professorxii/79f754?session_id=snack-session-M3G36gqdl&preview=true&platform=web&iframeId=iwsj5dpw1g&theme=dark

doesn't not work either

**Comment by WoLewicki** [comment]
Can you provide a minimal repro through a snack? I cannot repro your bug.

**Comment by bkmed** [comment]
i tiried the exepmle repo   https://snack.expo.io/@professorxii/79f754?session_id=snack-session-M3G36gqdl&preview=true&platform=web&iframeId=iwsj5dpw1g&theme=dark
but didn't work for me

**Comment by WoLewicki** [comment]
> but didn't work for me
What do you mean by that? The content of the `DrawerContent` didn't render?

**Comment by bkmed** [comment]
it show like the photo i put it in the first comment

**Comment by satya164** [comment]
Closing since issue template is incomplete and there's no repro to test. If you manage to repro it or fill the issue template, then comment here to reopen.

**Comment by akilisosa** [comment]
Actually I had this issue come up I was wondering what the problem was, and it actually happened when i wrapped one of the navigational components in a function.

**Comment by akilisosa** [comment]
so i had a stack navigator that had an Auth option, then an app that was the drawer component. If a user was authenticated It would show the drawer component, and it was wrapped with connect. I had written similar apps so i was wondering why it wasn't working this time. If you change your logic and presentation of the application this will work.

**Comment by dilshod1d** [comment]
So many people had same issue but no one is responding , or suggesting anything

**Comment by dilshod1d** [comment]
I don't understand Why you closed without solving it

**Comment by draperunner** [comment]
I also had a blank drawer like this after upgrading. I solved it by removing some width properties in `drawerStyle` of my `Drawer.Navigator`. I don't remember specifically why I had this there in the first place, but I think it was some hack I made a while ago to make the contents show. I am _not_ using `drawerContent`.

```diff
-drawerStyle: {
-  width: width * 0.8,
-  left: width,
-},
```
