### ISSUE TITLE
Reset nested stack on tab blur v5

### ISSUE THREAD

**Issue by stephtea** [react-navigation/react-navigation#7734]
I am using react-navigation v5. There seems to be no option like "unmountInactiveScreens" or "resetOnBlur" like in past versions, or atleast one that does anything. I'm not getting type errors using unmountInactiveScreens, but it does not reset the stack.

Is there a way to reset a nested navigation stack when navigating to a new tab with a new nested stack in v5?

**Comment by stephtea** [comment]
@satya164 Is it an oversight that this is missing from v5 or intentional? That's why I posted here, there does not seem to be documentation explaining what functionality replaces the potentially deprecated one.

**Comment by JBaczuk** [comment]
@stephtea Did you find a solution?

**Comment by stephtea** [comment]
the **screenOptions** property **unmountOnBlur**

**Comment by nathanbedford** [comment]
@JBaczuk  and @stephtea if you'd like to avoid the unmount penalty (takes a few extra milliseconds for me) you can subscribe to the 'blur' event and pop the nav stack to the top:

```
<BottomTab.Screen
  name={Screens.Home}
  component={HomeNavigator}
  options={{
    tabBarIcon: ({ color }) => <TabBarIcon name="ios-home" color={color} />,
  }}
  listeners={({ navigation, route }) => ({
    blur: () => {
      if (route.state && route.state.index > 0) {
        navigation.dispatch(StackActions.popToTop());
      }
    },
  })}
/>
```

This is the closest solution I've found to v3's `resetOnBlur`. Hope it helps!

**Comment by SampsonCrowley** [comment]
@nathanbedford what about when the root screen wasn't the first screen to be navigated to for the stack?

**Comment by SampsonCrowley** [comment]
That fact that something so very basic and needed is so unnecessarily difficult is shocking...
