### ISSUE TITLE
useIsDrawerOpen drawer is undefined

### ISSUE THREAD

**Issue by flyingcircle** [react-navigation/react-navigation#7736]
**Current Behavior**
While upgrading from v4 to v5:
Unable to use `useIsDrawerOpen` since it is throwing an error whenever I use it.

> TypeError: Cannot read property 'addListener' of undefined
> 
> This error is located at:
>     in HamburgerMenu
>     in RCTView (at createAnimatedComponent.js:222)
>     in AnimatedComponent (at Drawer.tsx:623)
>     in RCTView (at createAnimatedComponent.js:222)
>     in AnimatedComponent (at Drawer.tsx:586)
>     in PanGestureHandler (at Drawer.tsx:576)
>     in DrawerView (at DrawerView.tsx:206)
>     in SafeAreaProviderCompat (at DrawerView.tsx:204)
>     in RCTView (at DrawerView.tsx:203)
>     in DrawerView (at createDrawerNavigator.tsx:42)
>     in DrawerNavigator (at createCompatNavigatorFactory.tsx:156)
>     in Navigator (at CompatScreen.tsx:22)
>     in ScreenComponent (at createCompatNavigatorFactory.tsx:142)
>     in StaticContainer
>     in StaticContainer (at SceneView.tsx:89)
>     in EnsureSingleNavigator (at SceneView.tsx:88)
>     in SceneView (at useDescriptors.tsx:125)
>     in RCTView (at CardContainer.tsx:187)
>     in RCTView (at CardContainer.tsx:186)
>     in RCTView (at Card.tsx:508)
>     in RCTView (at createAnimatedComponent.js:151)
>     in AnimatedComponent (at Card.tsx:491)
>     in PanGestureHandler (at Card.tsx:484)
>     in RCTView (at createAnimatedComponent.js:151)
>     in AnimatedComponent (at Card.tsx:480)
>     in RCTView (at Card.tsx:473)
>     in Card (at CardContainer.tsx:154)
>     in CardContainer (at CardStack.tsx:518)
>     in RCTView (at CardStack.tsx:109)
>     in MaybeScreen (at CardStack.tsx:511)
>     in RCTView (at CardStack.tsx:92)
>     in MaybeScreenContainer (at CardStack.tsx:410)
>     in CardStack (at StackView.tsx:384)
>     in KeyboardManager (at StackView.tsx:382)
>     in SafeAreaProviderCompat (at StackView.tsx:379)
>     in RCTView (at StackView.tsx:378)
>     in StackView (at createStackNavigator.tsx:67)
>     in StackNavigator (at createCompatNavigatorFactory.tsx:156)
>     in Navigator (at CompatScreen.tsx:22)
>     in ScreenComponent (at createCompatNavigatorFactory.tsx:142)
>     in StaticContainer
>     in StaticContainer (at SceneView.tsx:89)
>     in EnsureSingleNavigator (at SceneView.tsx:88)
>     in SceneView (at useDescriptors.tsx:125)
>     in RCTView (at CardContainer.tsx:187)
>     in RCTView (at CardContainer.tsx:186)
>     in RCTView (at Card.tsx:508)
>     in RCTView (at createAnimatedComponent.js:151)
>     in AnimatedComponent (at Card.tsx:491)
>     in PanGestureHandler (at Card.tsx:484)
>     in RCTView (at createAnimatedComponent.js:151)
>     in AnimatedComponent (at Card.tsx:480)
>     in RCTView (at Card.tsx:473)
>     in Card (at CardContainer.tsx:154)
>     in CardContainer (at CardStack.tsx:518)
>     in RCTView (at CardStack.tsx:109)
>     in MaybeScreen (at CardStack.tsx:511)
>     in RCTView (at CardStack.tsx:92)
>     in MaybeScreenContainer (at CardStack.tsx:410)
>     in CardStack (at StackView.tsx:384)
>     in KeyboardManager (at StackView.tsx:382)
>     in RNCSafeAreaView (at src/index.tsx:28)
>     in SafeAreaProvider (at SafeAreaProviderCompat.tsx:42)
>     in SafeAreaProviderCompat (at StackView.tsx:379)
>     in RCTView (at StackView.tsx:378)
>     in StackView (at createStackNavigator.tsx:67)
>     in StackNavigator (at createCompatNavigatorFactory.tsx:156)
>     in Navigator (at App.js:91)
>     in EnsureSingleNavigator (at BaseNavigationContainer.tsx:267)
>     in ForwardRef(BaseNavigationContainer) (at NavigationContainer.tsx:39)
>     in ThemeProvider (at NavigationContainer.tsx:38)
>     in ForwardRef(NavigationContainer) (at App.js:90)
>     in RxrApp (at renderApplication.js:40)
>     in RCTView (at AppContainer.js:101)
>     in RCTView (at AppContainer.js:119)
>     in AppContainer (at renderApplication.js:39)
> 
> React.useEffect$argument_0
>     useIsDrawerOpen.tsx:28:31
> unstable_runWithPriority
>     scheduler.development.js:643:11

The relevant code in my own repo is:
App.js
```
...
const HomeDrawer = createCompatNavigatorFactory(createDrawerNavigator)(
  {
    Main: Home,
  },
  {
    drawerPosition: 'right',
    drawerContent: props => <HamburgerMenu {...props} />,
    initialRouteName: 'Main',
    defaultNavigationOptions: {
      headerShown: false,
    },
  },
);
...
```

SideMenu.js
```
function HamburgerMenu(props) {

  let viewRef = null;
  const isDrawerOpen = useIsDrawerOpen();

  useFocusEffect(
    React.useCallback(() => {
      console.log("focused on side menu.");
      focusOnView(viewRef);
    })
  );

    return (
      <Fragment>
        <View style={styles.container}>
          <View style={styles.topDrawer}>
            <Text
              ref={x => {
                viewRef = x;
              }}
...
```
**Expected Behavior**
I expect to be able to use the current drawer state. I need the drawer to know when it is open so that I can set the Accessibility Focus whenever the drawer opens/closes. 

**How to reproduce**
I was not able to recreate the exact bug in Expo, but something similar:

[Expo Snack](https://snack.expo.io/@flyingcircle/useisdraweropen-%7C-react-navigation?platform=android&name=Compatibility%20layer%20%7C%20React%20Navigation&dependencies=%40react-native-community%2Fmasked-view%40%5E0.1.1%2C%40react-navigation%2Fnative%40%5E5.0.5%2C%40react-navigation%2Fbottom-tabs%40%5E5.0.5%2C%40react-navigation%2Fdrawer%40%5E5.0.5%2C%40react-navigation%2Fmaterial-bottom-tabs%40%5E5.0.5%2C%40react-navigation%2Fmaterial-top-tabs%40%5E5.0.5%2C%40react-navigation%2Fstack%40%5E5.0.5%2Creact-native-gesture-handler%401.5.2%2Creact-native-reanimated%401.4.0%2Creact-native-safe-area-context%400.6.0%2Creact-native-screens%402.0.0-alpha.12&sourceUrl=https%3A%2F%2Freactnavigation.org%2Fexamples%2F5.x%2Fdrawer-dispatch.js)
**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | both
| @react-navigation/native       | 5.0.9
| @react-navigation/drawer       | 5.1.1
| react-native-reanimated        | 1.3.0
| react-native-gesture-handler   | 1.5.6
| react-native-safe-area-context | 0.7.3
| react-native-screens           | 2.0.0-alpha.6
| react-native                   | 0.61.4
| expo                           | NA
| node                           | 10.16.3
| npm or yarn                    | 1.19.1

**Comment by WoLewicki** [comment]
Isn't this the same issue as #7725 since you are trying to use hook in drawerContent?

**Comment by osdnk** [comment]
@WoLewicki it's not related

**Comment by osdnk** [comment]
`useIsDrawerOpen` check for navigator context and content of drawer is rendered outside of screens, my PR fixes that

**Comment by osdnk** [comment]
fixed with #7746

**Comment by jeffreyabarrios** [comment]
Hello! I'm facing the same problem with the hook. You said its fixed in #7746 but is it already in the last release?

**Comment by flyingcircle** [comment]
@osdnk I tried upgrading to 5.2.0, but I'm still hitting the same error.

**Comment by flyingcircle** [comment]
@osdnk I did a little bit more research into this on my fork: https://github.com/flyingcircle/react-navigation I added some customDrawerContent to the example, and it is currently throwing an error that I'm not sure I understand. Here is the error that it is producing for me:
```
Invariant Violation: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.

This error is located at:
    in DrawerView (at DrawerView.tsx:206)
    in RNCSafeAreaView (at src/index.tsx:28)
    in SafeAreaProvider (at SafeAreaProviderCompat.tsx:42)
    in SafeAreaProviderCompat (at DrawerView.tsx:204)
    in RCTView (at DrawerView.tsx:203)
    in DrawerView (at createDrawerNavigator.tsx:42)
    in DrawerNavigator (at src/index.tsx:220)
    in EnsureSingleNavigator (at BaseNavigationContainer.tsx:267)
    in ForwardRef(BaseNavigationContainer) (at NavigationContainer.tsx:39)
    in ThemeProvider (at NavigationContainer.tsx:38)
    in ForwardRef(NavigationContainer) (at src/index.tsx:209)
    in ThemeProvider (at Provider.tsx:21)
    in RCTView (at PortalHost.tsx:128)
    in Portal.Host (at Provider.tsx:17)
    in Provider (at src/index.tsx:205)
    in App (at withExpoRoot.js:26)
    in RootErrorBoundary (at withExpoRoot.js:25)
    in ExpoRoot (at renderApplication.js:40)
    in RCTView (at AppContainer.js:101)
    in DevAppContainer (at AppContainer.js:115)
    in RCTView (at AppContainer.js:119)
    in AppContainer (at renderApplication.js:39)

useNavigation
    App.tsx.bundle?platform=ios&dev=true&minify=false&hot=false:132660:38
useIsDrawerOpen
    App.tsx.bundle?platform=ios&dev=true&minify=false&hot=false:169663:99
CustomDrawerContent
    App.tsx.bundle?platform=ios&dev=true&minify=false&hot=false:168085:103
Drawer.Navigator.props.drawerContent
    index.tsx:221:54
renderNavigationView
    DrawerView.tsx:156:6
DrawerView#render
    Drawer.tsx:639:12
renderRoot
    [native code]:0
runRootCallback
    [native code]:0
unstable_runWithPriority
    scheduler.development.js:643:23
dispatchAction
    [native code]:0
restoreState
    index.tsx:179:19
tryCatch
    runtime.js:45:44
invoke
    runtime.js:274:30
tryCatch
    runtime.js:45:44
invoke
    runtime.js:135:28
PromiseImpl.resolve.then$argument_0
    runtime.js:145:19
tryCallOne
    core.js:37:14
setImmediate$argument_0
    core.js:123:25
_callTimer
    JSTimers.js:146:14
_callImmediatesPass
    JSTimers.js:194:17
callImmediates
    JSTimers.js:458:30
callImmediates
    [native code]:0
flushedQueue
    [native code]:0
invokeCallbackAndReturnFlushedQueue
    [native code]:0
```

**Comment by satya164** [comment]
Use `<CustomDrawerContent {...props} />` [as shown in the example](https://reactnavigation.org/docs/drawer-navigator#drawercontent), not `CustomDrawerContent(props)`

**Comment by flyingcircle** [comment]
@satya164 Thanks for the tip. I was going off of the snack example that is linked just above that example.
I changed the code and found this error that is still related to this bug:
```
Error: Couldn't find a navigation object. Is your component inside a screen in a navigator?

This error is located at:
    in CustomDrawerContent (at src/index.tsx:220)
    in RCTView (at createAnimatedComponent.js:233)
    in AnimatedComponent(Component) (at Drawer.tsx:624)
    in RCTView (at createAnimatedComponent.js:233)
    in AnimatedComponent(Component) (at Drawer.tsx:587)
    in PanGestureHandler (at Drawer.tsx:577)
    in DrawerView (at DrawerView.tsx:206)
    in RNCSafeAreaView (at src/index.tsx:28)
    in SafeAreaProvider (at SafeAreaProviderCompat.tsx:42)
    in SafeAreaProviderCompat (at DrawerView.tsx:204)
    in RCTView (at DrawerView.tsx:203)
    in DrawerView (at createDrawerNavigator.tsx:42)
    in DrawerNavigator (at src/index.tsx:220)
    in EnsureSingleNavigator (at BaseNavigationContainer.tsx:267)
    in ForwardRef(BaseNavigationContainer) (at NavigationContainer.tsx:39)
    in ThemeProvider (at NavigationContainer.tsx:38)
    in ForwardRef(NavigationContainer) (at src/index.tsx:209)
    in ThemeProvider (at Provider.tsx:21)
    in RCTView (at PortalHost.tsx:128)
    in Portal.Host (at Provider.tsx:17)
    in Provider (at src/index.tsx:205)
    in App (at withExpoRoot.js:26)
    in RootErrorBoundary (at withExpoRoot.js:25)
    in ExpoRoot (at renderApplication.js:40)
    in RCTView (at AppContainer.js:101)
    in DevAppContainer (at AppContainer.js:115)
    in RCTView (at AppContainer.js:119)
    in AppContainer (at renderApplication.js:39)

useNavigation
    useNavigation.tsx:16:16
useIsDrawerOpen
    App.tsx.bundle?platform=ios&dev=true&minify=false&hot=false:169656:99
CustomDrawerContent
    App.tsx.bundle?platform=ios&dev=true&minify=false&hot=false:168092:103
renderRoot
    [native code]:0
runRootCallback
    [native code]:0
unstable_runWithPriority
    scheduler.development.js:643:23
dispatchAction
    [native code]:0
restoreState
    index.tsx:179:19
tryCatch
    runtime.js:45:44
invoke
    runtime.js:274:30
tryCatch
    runtime.js:45:44
invoke
    runtime.js:135:28
PromiseImpl.resolve.then$argument_0
    runtime.js:145:19
tryCallOne
    core.js:37:14
setImmediate$argument_0
    core.js:123:25
_callTimer
    JSTimers.js:146:14
_callImmediatesPass
    JSTimers.js:194:17
callImmediates
    JSTimers.js:458:30
callImmediates
    [native code]:0
flushedQueue
    [native code]:0
invokeCallbackAndReturnFlushedQueue
    [native code]:0
```

**Comment by satya164** [comment]
`useNavigation` can only be used inside screens. Use the `navigation` from `props` in drawer content.

**Comment by flyingcircle** [comment]
This is from trying to use `useIsDrawerOpen` from inside the custom drawer content. Not trying to use the navigation object directly.

**Comment by WoLewicki** [comment]
@flyingcircle can you provide a minimal repro where the bug occurs?

**Comment by WoLewicki** [comment]
@flyingcircle your problem comes from the fact that `useIsDrawerOpen` uses `useNavigation()` inside it, and your custom drawer content does not have access to this hook, which throws the error.

**Comment by flyingcircle** [comment]
@WoLewicki yes, I understand the issue. That's why I opened the bug. I personally need to know when the drawer opens so that I can move the VoiceOver Focus to the top of the drawer content. This was possible in v4, through the navigation state in my custom drawer content. You can see a minimal example from my fork https://github.com/flyingcircle/react-navigation I've updated the base example there to include drawerContent.

In v4 I was able to do something like this:
```
componentDidUpdate(prevProps) {
    if (
      this.viewRef &&
      this.props.navigation.state.isDrawerOpen &&
      this.props.isFocused
    ) {
      focusOnView(this.viewRef);
    }
  }
```

But due to a different bug in v4, I was forced to move to v5 which has this issue preventing me from migrating completely.

**Comment by satya164** [comment]
```js
const isDrawerOpen = state.history.some(it => it.type === 'drawer');
```

**Comment by flyingcircle** [comment]
@satya164 you'll have to give me more than that. I don't know what context this line is, or what kind of object `state` is supposed to be.

**Comment by flyingcircle** [comment]
I tried implementing your line of code several ways. I'm not having any luck coming up with where you're getting certain variables:
```
componentDidUpdate(prevProps) {
      const isDrawerOpen = this.state.history.some(it => it.type === 'drawer');
      console.log("Drawer State: " + isDrawerOpen);
      this.setState({drawerState: isDrawerOpen});
  }
```

**Comment by flyingcircle** [comment]
I would suggest that this ticket be reopened, but I found a work around for my purpose with v4 and making a custom event with react-native-event-listener.

**Comment by WoLewicki** [comment]
@flyingcircle it should work just right due to https://github.com/react-navigation/react-navigation/commit/193c344ba5124f2246dde310a14449e295b4aa19.

**Comment by blackstalk** [comment]
This worked for me

`import {
  useDrawerStatus,
} from "@react-navigation/drawer";

export const DrawerContent = (props) => {

onst isDrawerOpen = useDrawerStatus() === "open";

  useEffect(() => {
    if (isDrawerOpen) {
      // Drawer was focused
      console.log("drawer focused", isDrawerOpen);
    }
    return () => {
      if (isDrawerOpen) {
        // Drawer was unfocused
        console.log("drawer was unfocused", isDrawerOpen);
      }
    };
  }, [isDrawerOpen]);

return (
    <DrawerContentScrollView {...props}>
    </DrawerContentScrollView>
);

}`
