### ISSUE TITLE
How to handle the SafeArea's background color with Bottom Tab?

### ISSUE THREAD

**Issue by danhnguyeen** [react-navigation/react-navigation#7739]
**Current Behavior**

I want to set the background color for the Bottom Tab. So I did as below.
```
<Tab.Navigator
      tabBarOptions={{
        activeTintColor: '#FF0000',
        activeBackgroundColor: '#FFFFFF',
        inactiveBackgroundColor: '#FF0000',
        inactiveTintColor:  '#FFFFFF'
      }}>
      <Tab.Screen
        name="Home"
        component={HomeScreen}
      />
      <Tab.Screen
        name="Account"
        component={AccountScreen}
      />
    </Tab.Navigator>
```

![Simulator Screen Shot - iPhone 11 Pro - 2020-03-06 at 14 27 50](https://user-images.githubusercontent.com/6939811/76062160-b6dfde00-5fb7-11ea-8808-3f2562e90c24.png)

The problem is the SafeArea has a white background

**Expected Behavior**
What I expect is
![Simulator Screen Shot - iPhone 11 Pro - 2020-03-06 at 14](https://user-images.githubusercontent.com/6939811/76062716-cca1d300-5fb8-11ea-926a-acbd42d412dd.png)

So could you tell me how to solve this issue in React Navigation version 5 please?

**Your Environment**

| software                      | version |
| ----------------------------- | ------- |
| iOS
| @react-navigation/native:       |^5.0.5
| @react-navigation/bottom-tabs: | ^5.0.5

**Comment by Norfeldt** [comment]
@danhnguyeen did you find a solution for this? I have the same problem

**Comment by manakuro** [comment]
Use `tabBarStyle` like so.

```.tsx
    <Tab.Navigator
      screenOptions={{
        tabBarStyle: {
          backgroundColor: 'black',
        },
      }}
    >

```
