### ISSUE TITLE
createNativeStackNavigator not longer available in react-navigation site

### ISSUE THREAD

**Issue by singheshadev** [react-navigation/react-navigation#7740]
complete remove native stack navigation link in react-navigation site

https://reactnavigation.org/docs/getting-started

Previously i am using - https://reactnavigation.org/docs/en/next/native-stack-navigator.html.

Any one know why react-navigation remove native stack navigation?

**Comment by eriveltonelias** [comment]
Hey @singheshadev 

it was moved to react-native-screens package https://github.com/software-mansion/react-native-screens#using-native-stack-navigator

**Comment by singheshadev** [comment]
Thanks for replay.
Not provide any documentation link in site. Can you share document link for implementation.

**Comment by Guuz** [comment]
@eriveltonelias The documentation that you link to tells us to use:
`import createNativeStackNavigator from 'react-native-screens/createNativeStackNavigator';`
But that import is invalid. I am using the latest versions of React Navigation and React Native Screens.

**Comment by satya164** [comment]
https://github.com/software-mansion/react-native-screens/blob/master/native-stack/README.md
