### ISSUE TITLE
Header title shows for sometime after pop

### ISSUE THREAD

**Issue by rayWille** [react-navigation/react-navigation#7741]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/43776890/76072252-a5013980-5fbd-11ea-9020-a8227c62fd98.gif)

Facing above issue when tapping on back button.
This issue only occurs in iOS device

**Comment by rayWille** [comment]
@WoLewicki 
I can't share code but i can explain how it is setup
There is SwitchNavigator which contains Drawer Navigator having  StackNavigator with above mentioned issue

**Comment by rayWille** [comment]
@WoLewicki 
Also i found if set **headerMode: 'screen'** , it works fine but when it is set to **float** then above issue occurs

**Comment by WoLewicki** [comment]
Can't you make a snack with the simplest configuration where it occurs? You won't have to share any specific code then.

**Comment by satya164** [comment]
Closing due to no response.
