### ISSUE TITLE
Layout inconsistency of modal screen during animation (forModalPresentationIOS)

### ISSUE THREAD

**Issue by taeingyu** [react-navigation/react-navigation#7742]
**Current Behavior**

![1](https://user-images.githubusercontent.com/24571455/76080927-5b2f4800-5feb-11ea-8b25-8b1afe751d8b.gif) ![2](https://user-images.githubusercontent.com/24571455/76080335-03dca800-5fea-11ea-8948-78dcb918dbd4.gif)

When swiping down a modal screen, bottom components  move first upper components later. Is this on purpose? How can I control this behavior?

**Expected Behavior**

Every component in the screen moves down synchronously.

**How to reproduce**

https://github.com/taeingyu/react-navigation-example

```javascript
import * as React from 'react';
import { SafeAreaView, Text, TouchableOpacity } from 'react-native';
import { NavigationContainer } from '@react-navigation/native';
import { createStackNavigator } from '@react-navigation/stack';

function HomeScreen({ navigation }) {
  return (
    <SafeAreaView style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
      <TouchableOpacity onPress={() => navigation.navigate('Modal')}>
        <Text>Modal Screen</Text>
      </TouchableOpacity>
    </SafeAreaView>
  );
}

function ModalScreen() {
  return (
    <SafeAreaView style={{ flex: 1, alignItems: 'center', justifyContent: 'space-around' }}>
      <Text>----- 4 -----</Text>
      <Text>----- 3 -----</Text>
      <Text>----- 2 -----</Text>
      <Text>----- 1 -----</Text>
    </SafeAreaView>
  );
}

const Stack = createStackNavigator();

function App() {
  return (
    <NavigationContainer>
      <Stack.Navigator initialRouteName="Home" headerMode="none" mode="modal">
        <Stack.Screen name="Home" component={HomeScreen} />
        <Stack.Screen name="Modal" component={ModalScreen} />
      </Stack.Navigator>
    </NavigationContainer>
  );
}

export default App;
```

**Your Environment**

"@react-native-community/masked-view": "^0.1.7",
"@react-navigation/native": "^5.0.9",
"@react-navigation/stack": "^5.1.1",
"react": "16.9.0",
"react-native": "0.61.5",
"react-native-gesture-handler": "^1.6.0",
"react-native-reanimated": "^1.7.0",
"react-native-safe-area-context": "^0.7.3",
"react-native-screens": "^2.2.0"

**Comment by WoLewicki** [comment]
What device are you running it on?

**Comment by taeingyu** [comment]
> What device are you running it on?

I tested on the simulator and my iPhoneX real device.

**Comment by WoLewicki** [comment]
I cannot repro this behavior on iPhone X and other phones. All the components are moving down synchronously. Can you provide a snack with an exact configuration?

**Comment by satya164** [comment]
Use https://github.com/th3rdwave/react-native-safe-area-context instead of `SafeAreaView` from React Native.
