### ISSUE TITLE
How to disable the Ripple circle when pressing a DrawerItem ?

### ISSUE THREAD

**Issue by MustaphaGhlissi** [react-navigation/react-navigation#7747]
Hi every body ! 

Actually I have a problem within the drawer item default styling 

When press a DrawerItem, the ripple appears over the DrawerItems

How to fix that ?

Regards

**Comment by MustaphaGhlissi** [comment]
There is no solution for that !

**Comment by MustaphaGhlissi** [comment]
Solved !

**Comment by pietroanello** [comment]
> Solved !

Can you tell me how you did tha? I'm trying to achieve the same result with the materialTopBar, but I can't find anything.

**Comment by jrhager84** [comment]
> Solved !

Can you at least elaborate on _how_ you solved it?
