### ISSUE TITLE
openDrawer() will trigger onStateChange with previousRouteName = null 

### ISSUE THREAD

**Issue by mydesweb** [react-navigation/react-navigation#7748]
I just noticed that when I use navigation.openDrawer() the onStateChange from NavigationContainer is called immediately with previousRouteName = null even if I provide a initialRouteName for Drawer.Navigator which is rendered fine.

This is wrong for Analytics and  **onStateChange should not be called because there is no route change**.. I only open the Drawer (nothing more)

I use the latest version.

**Comment by satya164** [comment]
> onStateChange should not be called because there is no route change

It's called on every state change as implied by the name *onStateChange* implies. If you only care about route change, then add a check to see if the route actually changed before logging.
