### ISSUE TITLE
Focus events not working properly on react-navigation-stack 2.x.x

### ISSUE THREAD

**Issue by ferrannp** [react-navigation/react-navigation#7749]
**Current Behavior**

![ezgif-7-7c0f859c3e1e](https://user-images.githubusercontent.com/774577/76103370-e3085880-5fd1-11ea-95be-e495662a50aa.gif)

As you can see in the video it does not always happen but when it happens, no matter what you do, the focus state never comes back to true.

**Expected Behavior**

Focus state to work.

**How to reproduce**

**Repro here: https://github.com/ferrannp/react-navigation-4-focus-bug**

Steps to reproduce (iOS):

- Go to Tab 3
- Click "Go to details"
- Click Go Back button (not swipe)
- Click to Tab 1 and Tab 2 quickly
- You should see: Tab X is focused: true

Repeat the steps above.

It is easy to reproduce that sometimes we are on a tab but is does not update and it shows `false`.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | iOS
| react-navigation       | 4.2.2
|react-navigation-hooks | 1.1.0
| react-navigation-stack        | 2.2.3
| react-navigation-stack        | 2.2.3
| react-native-gesture-handler   | 1.6.0
| react-native-safe-area-context | 0.7.3
| react-native-screens           | 2.2.0
| react-native                   | 0.61.5
| node                           | v10.16.3
| yarn                    | 1.19.1

**Comment by satya164** [comment]
I've reworked the event system which should fix the issue. Please upgrade `react-navigation` to `4.3.4` and `react-navigation-stack` to `2.3.8` and give it a try.
