### ISSUE TITLE
jest-expo - Unit tests failing after upgrade to react navigation 5

### ISSUE THREAD

**Issue by KiratiBhuva** [react-navigation/react-navigation#7750]
Hi, I recently upgraded the navigation version in my project to react-navigation 5. All the unit-test case were failing. So, I upgraded jest-expo to 36.0.1

Now, some of the tests are working, but it still fails in the file which import from '@react-navigation/stack'.

> import { HeaderBackButton } from '@react-navigation/stack'

 I get the below error

```
Test suite failed to run

 TypeError: Cannot read property 'split' of undefined
      at Object.global (../node_modules/@react-navigation/stack/lib/commonjs/views/Stack/CardStack.tsx:41:26)

      at Object.<anonymous> (../node_modules/@react-navigation/stack/lib/commonjs/views/Stack/StackView.tsx:11:1)
```

Instead of CardStack.tsx I have CardStack.js. Any idea why that might be?
There is a CardStack.tsx in the following location, though:

> node_modules/@react-navigation/stack/src/views/Stack/CardStack.tsx

(i.e. src instead of lib/commonjs)

**Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |
| @react-navigation/native       |5.0.2
| @react-navigation/stack        |5.0.2
| react-native-gesture-handler   |1.3.0
| react-native-safe-area-context |0.3.6
| react-native-screens           |1.0.0-alpha.23
| react-native                   |https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz
| expo                           |35.0.0
| npm or yarn                    |^1.22.0

**Comment by WoLewicki** [comment]
The line that is throwing the TypeError is 

```
const maybeExpoVersion = global.Expo?.Constants.manifest.sdkVersion.split(
  '.'
)[0];
```

Try upgrading your Expo to the newest version.

**Comment by satya164** [comment]
The line isn't there in new versions. Please upgrade.
