### ISSUE TITLE
enableScreens breaks copy/paste for TextInputs on Android 

### ISSUE THREAD

**Issue by benawad** [react-navigation/react-navigation#7751]
If I remove:
```
import { enableScreens } from "react-native-screens";
enableScreens()
```
copy/paste/select text from a TextInput works fine.

**How to reproduce**

https://github.com/benawad/copy-paste-android-broken

- clone project
- npm install
- npm start
- try to copy/paste/select text from the TextInput

I tested this on a physical LG G6

**Comment by eriveltonelias** [comment]
Hey @benawad, 

which version of react-native-screens are you using? seems fixed on latest version, could you check it?

**Comment by benawad** [comment]
Tried upgrading, but the issue seems to persist. 

I'm not sure if Expo is related to the problem, I get this warning:
![image](https://user-images.githubusercontent.com/7872329/77078641-dec23f00-69c4-11ea-9a80-0e8c314d0def.png)

**Comment by satya164** [comment]
Expo needs to upgrade their SDK to include the new version of screens. It should be fixed in SDK 37.

Related issue in screens https://github.com/software-mansion/react-native-screens/issues/205
