### ISSUE TITLE
safeAreaInset option doesn't work on Bottom Tab Navigator

### ISSUE THREAD

**Issue by danhnguyeen** [react-navigation/react-navigation#7758]
**Current Behavior**
I followed the [document](https://reactnavigation.org/docs/bottom-tab-navigator/#tabbaroptions), but it seems `safeAreaInset` option didn't work. 
I have tried to view the options in `node_modules` source code, and I didn't see this option.
Could you give me an advice for this issue please?
```
<Tab.Navigator
      tabBarOptions={{
        activeTintColor: themes.brandPrimary,
        activeBackgroundColor: themes.backgroundColor,
        inactiveBackgroundColor: themes.brandPrimary,
        inactiveTintColor: themes.backgroundColor,
        keyboardHidesTabBar: true,
        safeAreaInset: { bottom: 'never', top: 'never' },
        style: {
          backgroundColor: themes.brandPrimary,
        },
      }}
    >
     <Tab.Screen
        name="Account"
        component={AccountNavigator}
      />
</Tab.Navigator>
```
| software                      | version |
| ----------------------------- | ------- |
| iOS                |
| @react-navigation/native      |^5.0.5
| @react-navigation/bottom-tabs |^5.0.5
| react-native                  |0.61.5

**Comment by WoLewicki** [comment]
It is not available for now, the prop wasn't deleted from the documentation while upgrading to v5, though it might be added in the future for v5.

**Comment by cyveros** [comment]
@WoLewicki 
There is a commit on master branch for this fix. https://github.com/react-navigation/react-navigation/commit/82af7bed7135e42e24693b48cf7f1c6f9f5a6981

The dependent lib react-native-safe-area-context has a bug to compute bottom inset for android 5 or below. This bug affects bottom-tabs as well. So we can make a workaround with this `safeAreaInset` option if it were available.
