### ISSUE TITLE
Same RouteName with different parameter is working fine. but i goto back last coming details only coming all same routeName 

### ISSUE THREAD

**Issue by jameerTSS** [react-navigation/react-navigation#7759]
**Current Behavior**

      this.props.navigation.navigate({
            routeName: 'GymClass',
            params: {
              id: id,
            },
            key: `GymClasses_${id}`,
          })

Same RouteName with different parameter is working fine. but i goto back last coming details only coming all same routeName 

| software                       | version |
| ------------------------------ | ------- |
| react-navigation               | 4.0.10

**Comment by satya164** [comment]
Closing due to incomplete issue template.
