### ISSUE TITLE
useHeaderHeight returns different value for no reason

### ISSUE THREAD

**Issue by mi-mazouz** [react-navigation/react-navigation#7761]
I'm trying to set a height to my header component according to the headerHeight value from the child function of HeaderHeightContext.

I'm getting different values for the same screen, same component on the same device! Sometime I get 88 sometime 0 and sometime 44 just by going to a screen and coming back

my header component:

```
import * as React from 'react';
import {
    Header as HeaderRNE, HeaderProps,
} from 'react-native-elements';
import { HeaderHeightContext } from 'react-navigation-stack';

import { normalize } from '../../../../tools/responsive';

const Header = ({ containerStyle, ...props }: HeaderProps): React.ReactElement => (
    <HeaderHeightContext.Consumer>
        {(headerHeight): React.ReactElement => (
            <HeaderRNE
                containerStyle={[
                    containerStyle,
                    { ...(headerHeight && { height: headerHeight + normalize(10) }) },
                ]}
                {...props} />
        )}
    </HeaderHeightContext.Consumer>

);

export default Header;
```

**Environment**

| @react-navigation/stack 2.2.3 |
| expo sdk 36 |

**Comment by satya164** [comment]
`useHeaderHeight` is for getting the measured height of the header inside a screen, not for setting the height of your custom header. This isn't how it's supposed to be used.

**Comment by mi-mazouz** [comment]
So why did you remove Header.HEIGHT constant that does not make sense. How can we get a height that corresponding to the size of a header? As I don't have header in my screen (I create my own) I want to keep the size consistently!

**Comment by satya164** [comment]
If you have a custom header, then you should know how big your header should be to look right. If you want to use platform size, on Android it's 56, on iOS, it's 44 + status bar size.

Using height of the built-in header that React Navigation uses doesn't make much sense.

**Comment by mi-mazouz** [comment]
thank you for your response! For me it make sense to have header consistent everywhere...

What i'm gonna do is to create my own constant, it don't change anything

**Comment by neclamis1285** [comment]
If I am understanding your question correctly, you could pass the header height from your function/class component to your utility function. 

### Class Component

```    
import {HeaderHeightContext} from '@react-navigation/stack';

export default class MyClassComponent extends Component<Props, State> {

static contextType = HeaderHeightContext;

const {headerHeight} = this.context;
console.log('HEADER HEIGHT: ' + Utils.doSomethingWithHeaderHeight(headerHeight));

render = () => {
  <View style="{{height: headerHeight}}">
  </View>
};

}
```

### Utility Function

```
export const Utils = {
   doSomethingWithHeaderHeight: (headerHeight) => {
        return headerHeight + 10;
    }
};
```
