### ISSUE TITLE
Standard card transition inherits TransitionPresets.ModalPresentationIOS top margin

### ISSUE THREAD

**Issue by gabts** [react-navigation/react-navigation#7762]
**Current Behavior**

I want to wrap a stack navigation (standard card transition) with a navigator using `TransitionPreset.ModalPresentationIOS` to be able to open a modal above it no matter where in the card stack the user is. 

However, if the user navigates back from the modal stack and then again navigates a screen in the card stack before the modal transition was 100% completed the card transition will add a top margin.

See gif below:

![gif](https://user-images.githubusercontent.com/31779292/76262786-8faa3a80-625d-11ea-8fb6-d22d8e97ecd6.gif)

**Expected Behavior**

Smooth card transition when using TransitionPresets.ModalPresentationIOS.

**How to reproduce**

[Repo with steps to reproduce](https://github.com/gabts/react-navigation-modal-bug-example)

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | iOS
| @react-navigation/native       | 5.0.9
| @react-navigation/stack        | 5.1.1
| react-native-gesture-handler   | 1.6.0
| react-native-safe-area-context | 0.7.3
| react-native-screens           | 2.2.0
| react-native                   | 0.61.5
| expo                           | -
| node                           | 13.10.1
| npm or yarn                    | yarn

**Comment by WoLewicki** [comment]
Try upgrading to the newest version of the stack navigator. Is it still the case there?

**Comment by gabts** [comment]
Hello,

After upgrading to latest @react-navigation/stack I am no longer able to navigate at all until the modal transition is completely finished. 

Doesn't feel like a perfect solution but works fine in my case. Thank you!

However I noticed that the header border flashes once the transition has been completed (see gif).

![gif-2](https://user-images.githubusercontent.com/31779292/77159265-4d76c980-6aa5-11ea-86d0-18ab59e589e6.gif)

But that isn't really related to the title of this issue so I'm gonna go ahead and close this one. Thanks again.
