### ISSUE TITLE
Pass props from Parent to bottomTabNavigation view

### ISSUE THREAD

**Issue by moficodes** [react-navigation/react-navigation#7764]
**Current Behavior**

- What code are you running and what is happening?
Code Below
- Include a screenshot or video if it makes sense.

**Expected Behavior**

- What do you expect should be happening?
I am trying to pass props and functions to bottobNavigationBar pages.
- Include a screenshot or video if it makes sense.

**How to reproduce**
This is the base example for the Bottom Navigator.

```
import React, {useState} from 'react';
import {Text, View, Button} from 'react-native';
import {NavigationContainer} from '@react-navigation/native';
import {createBottomTabNavigator} from '@react-navigation/bottom-tabs';

function HomeScreen(props) {
  console.log(props);
  return (
    <View style={{flex: 1, justifyContent: 'center', alignItems: 'center'}}>
      <Text>{props.route.name}!</Text>
      <Button title="Click me" />
    </View>
  );
}

function SettingsScreen(props) {
  console.log(props);
  return (
    <View style={{flex: 1, justifyContent: 'center', alignItems: 'center'}}>
      <Text>{props.route.name}!</Text>
      <Button title="Click me" />
    </View>
  );
}

const Tab = createBottomTabNavigator();

export default function App() {
  const [homeText, setHomeText] = useState('home');
  const [settingText, setSettingsText] = useState('settings');

  // pass these states down to the tab bar pages.
  // also pass a function to the individual naviagtion pages that i can call on button click in SettingsScreen
  // or HomeScreen
  return (
    <NavigationContainer>
      <Tab.Navigator>
        <Tab.Screen name="Home" component={HomeScreen} />
        <Tab.Screen name="Settings" component={SettingsScreen} />
      </Tab.Navigator>
    </NavigationContainer>
  );
}

```

https://reactnavigation.org/docs/upgrading-from-4.x/#global-props-with-screenprops

There is some docs with react contexts. But I am not sure how that would work with React Navigations. 

If there is some example or docs you can point me to, that would be really helpful.

- You must provide a way to reproduce the problem. If you are having an issue with your machine or build tools, the issue belongs on another repository as that is outside of the scope of React Navigation.
- Either re-create the bug on [Snack](https://snack.expo.io) or link to a GitHub repository with code that reproduces the bug.
https://snack.expo.io/@moficodes/d88513
- Explain how to run the example app and any steps that we need to take to reproduce the issue from the example app.
- Keep the repro code as simple as possible, with the minimum amount of code required to repro the issue.
- Before reporting an issue, make sure you are on latest version of the package.

**Your Environment**

| software                      | version |
| ----------------------------- | ------- |
| iOS or Android                | iOS 13.3
| @react-navigation/native      | 5.0.9
| @react-navigation/bottom-tabs | 5.1.1
| react-native-screens          | 2.2.0
| react-native                  | 61.5
| expo                          | x
| node                          | 12.16.1
| npm or yarn                   | 6.13.4

**Comment by Nikosmonaut** [comment]
Hi. You can do it like this : 

```
return (
    <NavigationContainer>
      <Tab.Navigator>
            <Tab.Screen name="Home">
                {(props) => <HomeScreen  {...props} text={homeText} />}
            </Tab.Screen>
           <Tab.Screen name="Settings" component={SettingsScreen} />
      </Tab.Navigator>
    </NavigationContainer>
  );
```
