### ISSUE TITLE
The Previous Screen not Closing Perfectly (The Green One on Bottom)

### ISSUE THREAD

**Issue by risardi123** [react-navigation/react-navigation#7766]
**Current Behavior**
The prev screen not closing perfectly if the first screen have BottomTabNavigator see more detail on .gif file. Thank You

![glitch](https://user-images.githubusercontent.com/29408156/76293373-806dd000-62e3-11ea-8416-9d4a1055e8ca.gif)

**Expected Behavior**
When go back the green one or all screen is closing perfectly without interpolating BottomTabNavigator from first screen

**How to reproduce**
https://gist.github.com/risardi123/98e3df3595864fea5f34de1ad21a8f32

**Your Environment**
| software                      | version |
| ----------------------------- | ------- |
| iOS or Android                | Android X (Samsung Note 10)
| @react-navigation/native      | 5.0.9
| @react-navigation/bottom-tabs | 5.1.1
| react-native-screens          | 2.2.0
| react-native                  | 0.61.5
| node                          | 10.15.3
| npm or yarn                   | 1.22.0

**Comment by satya164** [comment]
Please nest tab navigator in the first screen of stack instead of hiding the tab bar https://reactnavigation.org/docs/nesting-navigators#parent-navigators-ui-is-rendered-on-top-of-child-navigator

**Comment by risardi123** [comment]
Thank You, it's working
