### ISSUE TITLE
Header Shaking error (The first time I approach the screen,)

### ISSUE THREAD

**Issue by smboy86** [react-navigation/react-navigation#7767]
**Current Behavior**

hi, 

i have a probleam 

It's very unusual. I can't reproduce it

I had no choice but to use other Version(V5) to solve it.

![K-003](https://user-images.githubusercontent.com/10238367/76304735-3a2a6800-6307-11ea-92e4-8cad69a2d482.jpg)

also, 

I tried but failed. >>>  (https://reactnavigation.org/docs/4.x/handling-iphonex/)

my code.

```
// 1. navigation
const TabNavigation = createBottomTabNavigator(
  {
    Shows: {
      screen: TodayReportScreen,
      navigationOptions: {
        tabBarIcon: ({ tintColor }) => (
          <View>
            <Icon style={[{ color: tintColor }]} size={28} name={'md-menu'} />
          </View>
        ),
      },
    },
    Search: {
      screen: SettingScreen,
      navigationOptions: {
        tabBarIcon: ({ tintColor }) => (
          <View>
            <Icon style={[{ color: tintColor }]} size={28} name={'md-menu'} />
          </View>
        ),
      },
    },
  },
  {
    initialRouteName: 'Shows',
    headerStyle: {
      height: 100,
    },
    headerForceInset: { top: 'never', bottom: 'never' },
  },
);

const MainNavigation = createStackNavigator(
  {
    Tabs: {
      screen: TabNavigation,
      navigationOptions: {
        // header: null,
        headerTitle: 'ss',
        headerTitleStyle: {
          color: '#e2e2e2',
          lineHeight: 22,
        },
        headerStyle: {
          height: 50,
        },
      },
    },
  },
);

// 2. screen
import SafeAreaView from 'react-native-safe-area-view';
...
render() {
    return (
      <SafeAreaView style={{ flex: 1, backgroundColor: '#fff' }}>
        <Container>
          <ContainerScrollView>
            <SettingBox>
...
  )
}

```

why happen??

thank you

**How to reproduce**

- You must provide a way to reproduce the problem. If you are having an issue with your machine or build tools, the issue belongs on another repository as that is outside of the scope of React Navigation.
- Either re-create the bug on [Snack](https://snack.expo.io) or link to a GitHub repository with code that reproduces the bug.
- Explain how to run the example app and any steps that we need to take to reproduce the issue from the example app.
- Keep the repro code as simple as possible, with the minimum amount of code required to repro the issue.
- Before reporting an issue, make sure you are on latest version of the package.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | android
| react-navigation               | 4.0.10
| react-navigation-stack         | 2.0.8
| react-navigation-tabs          | 2.7.0
| react-navigation-drawer        | x
| react-native-reanimated        | 1.4.0
| react-native-gesture-handler   | 1.5.3
| react-native-safe-area-context | 0.7.3
| react-native-screens           | 2.0.0-alpah.22
| react-native                   | 0.61.5
| expo                           | x
| node                           |
| npm or yarn                    | yarn

**Comment by satya164** [comment]
Closing since there's no repro and hence this issue not actionable for us.

**Comment by ajoykarmakar459** [comment]
Same issue +1
