### ISSUE TITLE
Bring back `activeLabelStyle` prop

### ISSUE THREAD

**Issue by thabemmz** [react-navigation/react-navigation#7768]
**Current Behavior**
I'm in the process of upgrading from `react-navigation@v3` to `v5`. One of the things we're using is a `DrawerNavigator` with a custom `DrawerContent` component. In that component, we highlight the currently active item with a prop `activeLabelStyle` that we pass onto `DrawerItemList`. The `activeLabelStyle`, in our case, only adds `font-weight` to the item in the `DrawerContent`.

However, this prop has been removed in https://github.com/react-navigation/react-navigation/commit/0a5fb3e268160586febed7fce14aecb294dd25aa#diff-b7fe367c22106e97eb0a61777e28348c, without providing any context why this change took place.

This means we currently cannot control this. The only solution I see for this is by cloning the whole `DrawerItemList` implementation in order to render our own `DrawerItem` components, which we can pass conditional styling based on the currently focussed item. This is of course very undesirable.

**Expected Behavior**
I'd expect the `DrawerItemList` to have a `activeLabelStyle` property or make it easier to control how the appearance of the `DrawerItem` would look. I'm at least curious why this property has been removed.

**Your Environment**

- **@react-navigation/drawer**: "^5.1.1"
- **@react-navigation/native**: "^5.0.9"
- **react**: "16.12.0"
- **react-native**: "0.61.5"

**Comment by WoLewicki** [comment]
It was removed because the design changed, it's more complicated now since the old design just changed the color and now there is also a background for an active item. The easiest way now would be the thing you wrote with cloning the `DrawerItemList`, you can also try to work with `activeTintColor` and `inactiveTintColor`. You can open a feature request in canny too: https://react-navigation.canny.io/feature-requests

**Comment by thabemmz** [comment]
Thanks for the clarification! I don't really grasp the full impact of the design change, so it seems to me that it still is a pretty straightforward thing to add, but I might be unaware of some nested component implications. I'll open a feature request at the page you linked.

**Comment by nathan815** [comment]
Agreed, this change made `DrawerItemList` inflexible, especially for anyone trying to customize the styles of drawer labels.
