### ISSUE TITLE
undefined is not an object ( evauating '_core.NavigationAction.init')

### ISSUE THREAD

**Issue by uendar** [react-navigation/react-navigation#7769]
I get an issue with react navigation 

> undefined is not an object ( evauating '_core.NavigationAction.init')

I am using :

> 
>     "@react-navigation/native": "^5.0.9",
>     "@react-navigation/stack": "^5.1.1",
>     "@react-native-community/masked-view": "^0.1.7",
>     "@react-native-community/art": "^1.1.2",
>     "react-native-safe-area-context": "^0.7.3",
>     "react": "16.9.0",
>     "react-native": "0.61.5",

Any idea what is it ?

**Comment by uendar** [comment]
Well i am using react without expo.  I have been using old versions of react-native, react, react-navgiation and others.

I had 
>   "react-navigation": "^3.8.1",
>     "react-navigation-redux-helpers": "^3.0.0",
>     "react-redux": "^5.0.7",
>     "realm": "^2.29.2",
>     "redux": "^4.0.0",
>     "redux-thunk": "^2.3.0",
>      "react": "16.8.3",
>     "react-native": "^0.59.10",



NOW after update
> "react": "16.9.0",
>      "react-native": "0.61.5",
>     "react-redux": "^7.2.0",
>     "realm": "^4.0.0-beta.0",
>     "redux": "^4.0.5",
>     "redux-thunk": "^2.3.0"


Also other modules but they have not changed. Also i did the updates in the code based on new updates of modules. And when i run project in debug mode i get that error. Nothings else.

**Comment by WoLewicki** [comment]
Can you provide a repo with the minimal needed configuration to show the error?

**Comment by satya164** [comment]
`react-navigation-redux-helpers` is not compatible with React Navigation 5. Either use React Navigation 4, or don't use `react-navigation-redux-helper`. We don't officially support or recommend storing navigation state in Redux .

**Comment by uendar** [comment]
I tried to use lower version but still same.

>  "dependencies": {
>     "@react-native-community/art": "^1.2.0",
>     "@react-native-community/datetimepicker": "^2.2.3",
>     "@react-native-community/google-signin": "^3.0.4",
>     "@react-native-community/masked-view": "^0.1.7",
>     "@react-native-community/netinfo": "^5.5.1",
>     "@react-native-firebase/app": "^6.3.4",
>     "@react-native-firebase/messaging": "^6.3.4",
>     "@react-navigation/core": "^5.2.1",
>     "base64-js": "^1.3.1",
>     "create-react-native-module": "^0.16.0",
>     "dateformat": "^3.0.3",
>     "formik": "^2.1.4",
>     "global": "^4.4.0",
>     "install": "^0.13.0",
>     "json2csv": "^4.5.4",
>     "mime": "^2.4.4",
>     "moment": "^2.24.0",
>     "native-base": "^2.13.8",
>     "prop-types": "^15.7.2",
>     "react": "16.9.0",
>     "react-native": "0.61.5",
>     "react-native-charts-wrapper": "^0.5.7",
>     "react-native-document-picker": "^3.2.4",
>     "react-native-elements": "^1.2.7",
>     "react-native-exit-app": "^1.1.0",
>     "react-native-file-picker": "0.0.19",
>     "react-native-file-viewer": "^2.0.2",
>     "react-native-fs": "^2.16.6",
>     "react-native-gesture-handler": "^1.6.0",
>     "react-native-google-drive-api-wrapper": "^1.2.0",
>     "react-native-html-to-text": "0.0.5",
>     "react-native-image-crop-picker": "^0.28.0",
>     "react-native-image-picker": "^2.3.1",
>     "react-native-keyboard-aware-scroll-view": "^0.9.1",
>     "react-native-loading-spinner-overlay": "^1.1.0",
>     "react-native-modal": "^11.5.4",
>     "react-native-modal-filter-picker": "^2.0.0",
>     "react-native-onesignal": "^3.6.5",
>     "react-native-pdf": "^6.0.1",
>     "react-native-pie": "^1.1.2",
>     "react-native-reanimated": "^1.7.0",
>     "react-native-screens": "^2.3.0",
>     "react-native-simple-radio-button": "^2.7.4",
>     "react-native-simple-toast": "^1.0.0",
>     "react-native-spinkit": "^1.5.0",
>     "react-native-step-indicator": "0.0.11",
>     "react-native-svg": "^12.0.3",
>     "react-native-timeago": "^0.5.0",
>     "react-native-typography": "^1.4.1",
>     "react-navigation": "^3.8.1",
>     "react-navigation-redux-helpers": "^3.0.0",
>     "react-redux": "^5.0.7",
>     "realm": "^4.0.0-beta.0",
>     "redux": "^4.0.0",
>     "redux-thunk": "^2.3.0",
>     "rn-fetch-blob": "^0.12.0",
>     "rn-smart-barcode": "^1.0.6",
>     "shortid": "^2.2.15",
>     "util": "^0.12.2",
>     "uuid": "^7.0.2",
>     "validate-model": "0.0.2",
>     "yup": "^0.28.3"
>   },
>   "devDependencies": {
>     "@babel/core": "7.8.7",
>     "@babel/runtime": "7.8.7",
>     "@react-native-community/eslint-config": "0.0.5",
>     "babel-jest": "24.9.0",
>     "eslint": "6.8.0",
>     "jest": "24.9.0",
>     "metro-react-native-babel-preset": "0.56.4",
>     "react-test-renderer": "16.9.0"
>   },

**Comment by satya164** [comment]
If redux helpers doesn't work with lower version, you need to open issue in redux helpers repo. As I said, we don't officially recommend using it or support it, so you shouldn't report issues about it in this repo.

**Comment by sallarahmed** [comment]
I solved issue by deleting node_modules and install dependencies using yarn instead of npm

**Comment by super-potion** [comment]
@uendar any guidance on how you solved this? facing the same issue.

**Comment by kumailahmedk** [comment]
any guidence on how you can solve this issue ?facing the same issue 
![Screenshot from 2022-04-14 13-19-34](https://user-images.githubusercontent.com/101647079/163344199-c9fa397f-9291-42cf-b098-11ab12152c1b.png)

**Comment by kumailahmedk** [comment]
as i am using react navigaton 4
