### ISSUE TITLE
Sample Snack from 5.0 Documentation fails

### ISSUE THREAD

**Issue by hjpsievert** [react-navigation/react-navigation#7771]
**Current Behavior**
Snack fails with error 

```
Device: (0:0) Request failed with status 403: 
  Evaluating module://react-native-screens.js
  Evaluating module://@react-navigation/drawer.js
  Evaluating module://App.js.js
  Loading module://App.js
```

Using the [snack ](https://snack.expo.io/?platform=android&name=Drawer%20navigation%20%7C%20React%20Navigation&dependencies=%40react-native-community%2Fmasked-view%40%5E0.1.1%2C%40react-navigation%2Fnative%40%5E5.0.5%2C%40react-navigation%2Fbottom-tabs%40%5E5.0.5%2C%40react-navigation%2Fdrawer%40%5E5.0.5%2C%40react-navigation%2Fmaterial-bottom-tabs%40%5E5.0.5%2C%40react-navigation%2Fmaterial-top-tabs%40%5E5.0.5%2C%40react-navigation%2Fstack%40%5E5.0.5%2Creact-native-gesture-handler%401.5.2%2Creact-native-reanimated%401.4.0%2Creact-native-safe-area-context%400.6.0%2Creact-native-screens%402.0.0-alpha.12&sourceUrl=https%3A%2F%2Freactnavigation.org%2Fexamples%2F5.x%2Fdrawer-based-navigation.js) from the [documentation ](https://reactnavigation.org/docs/drawer-based-navigation/) for version 5. Have the same issue with a [snack](https://snack.expo.io/@hjpsievert/59d468) I created to report a drawer issue.

**Expected Behavior**

Expected the drawer to render

**How to reproduce**

Run the [referenced](https://snack.expo.io/?platform=android&name=Drawer%20navigation%20%7C%20React%20Navigation&dependencies=%40react-native-community%2Fmasked-view%40%5E0.1.1%2C%40react-navigation%2Fnative%40%5E5.0.5%2C%40react-navigation%2Fbottom-tabs%40%5E5.0.5%2C%40react-navigation%2Fdrawer%40%5E5.0.5%2C%40react-navigation%2Fmaterial-bottom-tabs%40%5E5.0.5%2C%40react-navigation%2Fmaterial-top-tabs%40%5E5.0.5%2C%40react-navigation%2Fstack%40%5E5.0.5%2Creact-native-gesture-handler%401.5.2%2Creact-native-reanimated%401.4.0%2Creact-native-safe-area-context%400.6.0%2Creact-native-screens%402.0.0-alpha.12&sourceUrl=https%3A%2F%2Freactnavigation.org%2Fexamples%2F5.x%2Fdrawer-based-navigation.js) snack for web, but same error for iOS and Android

**Your Environment**

Not applicable, this is on Snack

**Comment by WoLewicki** [comment]
This error should be fixed now.

**Comment by hjpsievert** [comment]
Looks like there is  a different error now:

 

Device: (0:0) Unable to resolve module 'module://fbjs/lib/invariant.js'

package.json: (1:1) Unexpected end of input

 

 

Best regards,

Hans-Jürgen (HJ) Sievert
:: 3770 Vancouver Drive, Reno, NV 89511
:: Cell (775) 742-7425 Home (775) 853-4599

::  <mailto:hj.sievert@gmail.com> hj.sievert@gmail.com

:: http://www.linkedin.com/in/hjsievert

**Comment by singamnv** [comment]
I have the same error too with any code I run with snack.

**Comment by hjpsievert** [comment]
I did try the example on the useFocusEffect from the React Navigation documentation and that [snack](https://snack.expo.io/?platform=android&name=useFocusEffect%20%7C%20React%20Navigation&dependencies=%40react-native-community%2Fmasked-view%40%5E0.1.1%2C%40react-navigation%2Fnative%40%5E5.0.5%2C%40react-navigation%2Fbottom-tabs%40%5E5.0.5%2C%40react-navigation%2Fdrawer%40%5E5.0.5%2C%40react-navigation%2Fmaterial-bottom-tabs%40%5E5.0.5%2C%40react-navigation%2Fmaterial-top-tabs%40%5E5.0.5%2C%40react-navigation%2Fstack%40%5E5.0.5%2Creact-native-gesture-handler%401.5.2%2Creact-native-reanimated%401.4.0%2Creact-native-safe-area-context%400.6.0%2Creact-native-screens%402.0.0-alpha.12&sourceUrl=https%3A%2F%2Freactnavigation.org%2Fexamples%2F5.x%2Fsimple-focus-effect.js) worked, but it uses a tab navigator.
