### ISSUE TITLE
Can't use wrapper components that use navigation

### ISSUE THREAD

**Issue by WouterFlorijn** [react-navigation/react-navigation#7772]
**Current Behavior**

- Error: "Couldn't find a navigation object. Is your component inside a screen in a navigator?"

**Expected Behavior**

- Wrapper components can use navigation.

**How to reproduce**

index.js

```jsx
// @flow
import React, { Component } from 'react'
import { NavigationContainer } from '@react-navigation/native'
import RootNavigator from './RootNavigator'
import { SomeWrapper } from './SomeWrapper'

type Props = {}

class Root extends Component<Props> {

  static router = RootNavigator.router

  render() {
    return (
      <NavigationContainer>
        <SomeWrapper>
          <RootNavigator />
        </SomeWrapper>
      </NavigationContainer>
    )
  }

}

export default Root
```

`SomeWrapper` uses `useNavigation`.

In my case, I'm using a wrapper component to listen to app opens through deep links, and then navigate to a screen corresponding to the deep link url. This worked fine in 4.x, using `withNavigation`, but now doesn't work anymore. How can I use navigation in wrapper components for this or similar purposes?

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| @react-navigation/native       | 5.0.9
| react-native                   | 0.61.5
| expo                           | 36.0.0

**Comment by satya164** [comment]
https://reactnavigation.org/docs/navigating-without-navigation-prop
