### ISSUE TITLE
TypeError: left is not a function

### ISSUE THREAD

**Issue by WouterFlorijn** [react-navigation/react-navigation#7773]
**Current Behavior**

```
TypeError: left is not a function

This error is located at:
    in HeaderSegment (at Header.tsx:57)
    in Header (at HeaderContainer.tsx:151)
    in RCTView (at HeaderContainer.tsx:124)
    in RCTView (at HeaderContainer.tsx:59)
    in HeaderContainer (at StackView.tsx:297)
    in RCTView (at CardContainer.tsx:186)
    in RCTView (at Card.tsx:508)
    in RCTView (at createAnimatedComponent.js:151)
    in AnimatedComponent (at Card.tsx:491)
    in PanGestureHandler (at Card.tsx:484)
    in RCTView (at createAnimatedComponent.js:151)
    in AnimatedComponent (at Card.tsx:480)
    in RCTView (at Card.tsx:473)
    in Card (at CardContainer.tsx:154)
    in CardContainer (at CardStack.tsx:518)
    in RCTView (at CardStack.tsx:109)
    in MaybeScreen (at CardStack.tsx:511)
    in RCTView (at CardStack.tsx:92)
    in MaybeScreenContainer (at CardStack.tsx:410)
    in CardStack (at StackView.tsx:384)
    in KeyboardManager (at StackView.tsx:382)
    in SafeAreaProviderCompat (at StackView.tsx:379)
    in RCTView (at StackView.tsx:378)
    in StackView (at createStackNavigator.tsx:67)
```

**Expected Behavior**

- No error should occur.

**How to reproduce**

- Use any function that leads to a `HeaderSegment` somehow. E.g. `createStackNavigator`.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| @react-navigation/native       | 5.0.9
| react-native                   | 0.61.5
| expo                           | 36.0.0

**Comment by HollyPony** [comment]
Solved here. It waas due to my migration. `screenOptions` like `headerTitle`, `headerLeft`, `headerRight` now taking a function which return the Component. Switching `header*: <MyHeader />` to `header*: () => <Header />` save me.

https://reactnavigation.org/docs/stack-navigator#headertitle

> String or a function that returns a React Element to be used by the header.

I didn't notice from a migration from 3.x, maybe missing on doc ?

Anyway, hope it help ;)

**Comment by WouterFlorijn** [comment]
@HollyPony yes, same for me. I was passing a function, but the function `() => <SomeComponent />` is also considered a component, so it didn't work. Therefore `() => () => <SomeComponent />` is also a component, and `() => () => () => <SomeComponent />` and so on. Not sure if it's related to my React, React Native or Expo versions, but it was impossible for me to fix, so I would consider this a bug.

I'm sticking to 4.x for now. 5.x has too many breaking changes and issues without solutions at the moment (googling some of the errors I ran into literally yielded zero results).

**Comment by satya164** [comment]
All of these are mentioned in the v4 upgrading guide and print warnings after you upgrade https://reactnavigation.org/docs/4.x/upgrading-from-3.x#react-navigation-stack

> but the function () => <SomeComponent /> is also considered a component (not a function)

That's both a component and a function, and is valid usage.
