### ISSUE TITLE
Android back button in stack header not shown in a yarn workspace monorepo

### ISSUE THREAD

**Issue by wscotten** [react-navigation/react-navigation#7774]
**Current Behavior**
In a Yarn workspace monorepo, the back button on Android does not show up.  However running the example in a normal repository works just fine.  On iOS there is no issue.

<img width="543" alt="Screen Shot 2020-03-10 at 3 16 52 PM" src="https://user-images.githubusercontent.com/24510642/76364365-359f8880-62e2-11ea-8f9e-c3093f4fbdfa.png">

**Expected Behavior**
The back button would show up to the left of the "Profile" title in the header.

**How to reproduce**
clone: https://github.com/wscotten/react-navigation-android-back-bug
run: `yarn`
run: `cd packages/app`
run: `yarn start`
Click the "Go To Profile" button and see there is no back button.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Android
| @react-navigation/native       | ^5.0.0
| @react-navigation/stack        | ^5.0.0
| react-native-gesture-handler   | ~1.5.0
| react-native-safe-area-context | 0.6.0
| react-native-screens           | 2.0.0-alpha.12
| react-native                   | 0.61.4
| expo                           | ~36.0.0
| node                           | 12.13.1
| npm or yarn                    | yarn

**Comment by satya164** [comment]
It's a bug in metro, not react navigation https://github.com/react-navigation/react-navigation/blob/82af7bed7135e42e24693b48cf7f1c6f9f5a6981/example/metro.config.js#L75

**Comment by wscotten** [comment]
Oh thank you for the quick response!  So how should I modify my `metro.config.js` to make it work?

**Comment by satya164** [comment]
You'll have to check the request URL and modify it so that it's right

**Comment by wscotten** [comment]
For anyone else that has a similar project structure to mine, this got it working: 


```
const { createMetroConfiguration } = require('expo-yarn-workspaces');

const server = {
  enhanceMiddleware: middleware => {
    return (req, res, next) => {
      // When an asset is imported outside the project root, it has wrong path on Android
      // This happens for the back button in stack, so we fix the path to correct one
      const assets = '/node_modules/@react-navigation/stack/src/views/assets';

      if (req.url.startsWith(assets)) {
        req.url = req.url.replace(
          assets,
          '/assets/../../node_modules/@react-navigation/stack/src/views/assets',
        );
      }

      return middleware(req, res, next);
    };
  },
};

module.exports = { ...createMetroConfiguration(__dirname), server };
```
