### ISSUE TITLE
Android weird screen transitions

### ISSUE THREAD

**Issue by thiagoferolla** [react-navigation/react-navigation#7775]
**Current Behavior**

After upgrading from v3 to v5, every Stack navigator in my app seems to have a strange animation and I'm not able to change. Tried following the docs but it always shows the same animation - video below.

[https://imgur.com/Btv1dPh](url)

An example is:
```
import { createStackNavigator } from '@react-navigation/stack';

const Stack = createStackNavigator<AssistenteNavigatorParams>();

function Navigator() {
    return (
        <Stack.Navigator>
            <Stack.Navigator name="Screen A" component={ScreenA}/>
            <Stack.Navigator name="Screen B" component={ScreenB}/>
            <Stack.Navigator name="Screen C" component={ScreenC}/>
        </Stack.Navigator>
    )
}
```

**Expected Behavior**

Stack Navigator should reproduce the native screen transitions

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | android
| @react-navigation/native       | 5.0.9
| @react-navigation/stack        | 5.1.1
| react-native-gesture-handler   | 1.6.0
| react-native-safe-area-context | 0.7.3
| react-native-screens           | 2.3.0
| react-native                   | 0.61.5
| expo                           | -
| node                           | 12.10
| npm or yarn                    | yarn

**Comment by satya164** [comment]
Please read the docs before opening issues https://reactnavigation.org/docs/stack-navigator#transitionpresets

**Comment by thiagoferolla** [comment]
@satya164 I've read the docs and tried changing the animation preset but almost every preset gave the behavior of the video I posted - DefaultTransition, FadeFromBottomAndroid, RevealFromBottomAndroid and ModalPresentation. Also I've never seem an android app with this transition so I don't know if this behaviour is correct.

https://imgur.com/Btv1dPh

**Comment by satya164** [comment]
> Also I've never seem an android app with this transition so I don't know if this behaviour is correct

All of those are default OS animations like mentioned in the docs, which you can see in simulators or devices with unmodified Android OS.

**Comment by thiagoferolla** [comment]
> > Also I've never seem an android app with this transition so I don't know if this behaviour is correct
> 
> All of those are default OS animations like mentioned in the docs, which you can see in simulators or devices with unmodified Android OS.

So you're saying that it can be an issue with a specific device that I'm testing?

**Comment by miinos** [comment]
having the same issue.. the transition are weired and not the default of Android OS,
the V4 was doing it well. looks like a bug in v5

**Comment by miinos** [comment]
a workaround is to define the Android transition manually.. Since iOS transition are OK.
`screenOptions={{
        headerShown: false,
        gestureEnabled: false,
        ...(Platform.OS === "android" &&
          TransitionPresets.FadeFromBottomAndroid),
   }}`

**Comment by Liqiankun** [comment]
I got the same issue. Im using v4, the transition animation is not like the one on v2. Just kinda weird. I don't know how to put it. Just weird.

**Comment by benvp** [comment]
Indeed it looks like somewhat like a "slide from bottom" navigation. A bit like the default modal transision on iOS. Definitely changed from v4 to v5 and looks odd.

**Comment by EhsanSarshar** [comment]
this weird transition only happen in android 8+

**Comment by PierreBresson** [comment]
> a workaround is to define the Android transition manually.. Since iOS transition are OK.
> `screenOptions={{ headerShown: false, gestureEnabled: false, ...(Platform.OS === "android" && TransitionPresets.FadeFromBottomAndroid), }}`
Have you find a way to do this globally?

**Comment by EhsanSarshar** [comment]
@PierreBresson TransitionPresets.FadeFromBottomAndroid have also a weird behaviour. it first shows like shadow transitions. like something that have shadow fade first and then fade it's actual content. I have tested on samsung galaxy m30s android 9

**Comment by EhsanSarshar** [comment]
@satya164 
This is really a big weird issue in android. hope you fix it soon. I must switch to react-native-screen for now 

here is the [video](https://imgur.com/Btv1dPh)

**Comment by jamesdunay** [comment]
Yeah, I'm getting this too. iOS works just fine but it seems odd to me that it defaults to this on android? A few of our users pinged us with it.

**Comment by zoom2009** [comment]
just use this 
```javascript
import { TransitionPresets } from '@react-navigation/stack';

// ...

<Stack.Screen
  name="Profile"
  component={Profile}
  options={{
    title: 'Profile',
    ...TransitionPresets.SlideFromRightIOS,
  }}
/>;
```

**Comment by EhsanSarshar** [comment]
is there any progress on this ?

**Comment by humphriest** [comment]
@satya164 Any update on this issue? It's a fairly big problem for us
