### ISSUE TITLE
How to navigate to another conditionally defined screen?

### ISSUE THREAD

**Issue by wong2** [react-navigation/react-navigation#7776]
let's say I have these screens: 

* HomePage
* CreateBlogPage
* BlogPage

If a user doesn't have a blog yet, they'll see `CreateBlogPage` where they can create a blog, and then they will be redirected to `BlogPage` to manage their newly created blog. 
If a user already has a blog, they'll see `HomePage` when opening the app.

Here is how I'm defining my navigators:

```
user.blog ? (
  <>
    <Stack.Screen name="Home" component={HomePage} />
    <Stack.Screen name="Blog" component={BlogPage} />
  </>
) : (
  <Stack.Screen name="CreateBlog" component={CreateBlogPage} />
)
```

in CreateBlogPage:

```
const createStore = useCallback(async () => {
  const blog = await api.createBlog(blogName)
  dispatch(userCreatedBlog(blog))
  navigation.navigate('Blog', { id: blog.id })
}, [navigation, blogName])
```

this doesn't work, I think the problem is when navigating to BlogPage in `createStore`, the screen is not yet in the navigation tree

**Comment by WoLewicki** [comment]
You cannot navigate from `CreateBlog` to `Blog`, it should be controlled by the state of `user.blog`. Read https://reactnavigation.org/docs/auth-flow. Does this solve your issue?

**Comment by wong2** [comment]
@WoLewicki I wrote my code after reading the auth-flow doc
