### ISSUE TITLE
labelStyle not working

### ISSUE THREAD

**Issue by kohleen** [react-navigation/react-navigation#7777]
The [document and sample code](https://reactnavigation.org/docs/material-bottom-tab-navigator/) for material bottom tab navigator shows `labelStyle` as a valid property however it is not recognised as a property in mine. Here's a snippet of my code:
```
const HomeTabs = createMaterialBottomTabNavigator();

const HomeTabsScreen = () => (
    <HomeTabs.Navigator
        initialRouteName="Screen1"
        labeled={true}
        labelStyle={{fontSize: 14}}
        activeColor="#673AB7"
        inactiveColor="#7E7E7E"
        barStyle={styles.tabBar}> 
            <HomeTabs.Screen name="Screen1" component={Screen`} options={{tabBarLabel:'Screen1', tabBarIcon: ({color}) => <Icon name="screen1" color={color}  /> }} />
    </HomeTabs.Navigator>
);
```
This error appears:
```
Property 'labelStyle' does not exist on type 'IntrinsicAttributes & Pick<Props, "style" | "children" | "shifting" | "labeled" | "activeColor" | "inactiveColor" | "sceneAnimationEnabled" | "keyboardHidesNavigationBar" | "barStyle" | "theme" | "backBehavior"> & { ...; } & { ...; }
```

  
**Environment**

| software                               | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 5.0.9
| @react-navigation/material-bottom-tabs | 5.1.1
| react-native-paper                     | 3.6.0
| react-native                           | 0.61.5
| node                                   | 12.12.0
| npm or yarn                            | yarn

Is there something wrong with my versions? I tried ignoring the type error but the font styling still does not apply on my Android device.

**Comment by WoLewicki** [comment]
`labelStyle` is not available in this package, it is a typo in the documentation that it is mentioned in the example. I will fix it in a minute.

**Comment by kohleen** [comment]
@WoLewicki Thank you! Is there no way to customise the font styling for material bottom tab labels then? The workaround I applied was creating my own bottom tab bar component.

**Comment by WoLewicki** [comment]
> Is there no way to customise the font styling for material bottom tab labels then?

It is not possible.

> The workaround I applied was creating my own bottom tab bar component.

Your workaround seems like the easiest one.

**Comment by deathemperor** [comment]
@WoLewicki can you confirm this applies to https://reactnavigation.org/docs/bottom-tab-navigator/#options too? I can't seem to change the font of label either. Maybe this needs another issue?

**Comment by WoLewicki** [comment]
You should be able to use https://reactnavigation.org/docs/bottom-tab-navigator/#labelstyle and it should apply to the label's item here: https://github.com/react-navigation/react-navigation/blob/main/packages/bottom-tabs/src/views/BottomTabItem.tsx#L209

**Comment by deathemperor** [comment]
> You should be able to use https://reactnavigation.org/docs/bottom-tab-navigator/#labelstyle and it should apply to the label's item here: https://github.com/react-navigation/react-navigation/blob/main/packages/bottom-tabs/src/views/BottomTabItem.tsx#L209

I trying applying it but it won't take effect. Code:

```javascript
<BottomTab.Navigator initialRouteName={INITIAL_ROUTE_NAME}>
      <BottomTab.Screen
        name='Home'
        component={HomeScreen}
        options={{
          title: t('home_screen'),
          labelStyle: {color: 'red'},
          tabBarIcon: ({ focused }) => (
            <Home color={focused ? '#B3D4FF' : '#B3BAC5'} />
          ),
        }}
      />
```

**Comment by WoLewicki** [comment]
Can you provide a snack with the simplest configuration needed to reproduce it so I could see what is the problem?

**Comment by AhmedAbdulrahman** [comment]
@deathemperor I had the same issue, I just moved `labelSyle` from `Tab.Screen` to `Tab.Navigation`'s `tabBarOptions` and it worked :) 

```js
<Tab.Navigator
    tabBarOptions={{
    activeTintColor: theme.palette.success.main.string(),
    labelStyle: {
     fontSize: 12
    },
  }}
>
.....
...
..
</Tab.Navigation>
```

**Comment by AnLuubk** [comment]
https://stackoverflow.com/a/60936345 this answer is solve everything!
