### ISSUE TITLE
StackActions.push is not idempotent (unlike CommonActions.navigate)

### ISSUE THREAD

**Issue by linda167** [react-navigation/react-navigation#7779]
**Current Behavior**

- What code are you running and what is happening?

We wanted to switch our navigation in version 5 from using navigate to push, because we always want a push screen animation. The problem we encountered was that it seems StackActions.push does not have the idempotent protection that CommonActions.navigate already has. As a result, if you quickly tap on a button that triggers navigation, the new screen would get pushed twice in rapid succession.

It looks like the original idempotent behavior for navigate was added here:
https://github.com/react-navigation/react-navigation/pull/3393

Please consider adding the same support for StackActions.push, as the current push API cannot be used in production for us because of the lack of idempotent protection.

- Include a screenshot or video if it makes sense.

**Expected Behavior**

- What do you expect should be happening?
- Include a screenshot or video if it makes sense.

**How to reproduce**

- You must provide a way to reproduce the problem. If you are having an issue with your machine or build tools, the issue belongs on another repository as that is outside of the scope of React Navigation.

Repro is simply to tap on a button twice rapidly which triggers StackActions.push, and observe that the push animation will play twice overlapping each other.

- Either re-create the bug on [Snack](https://snack.expo.io) or link to a GitHub repository with code that reproduces the bug.
- Explain how to run the example app and any steps that we need to take to reproduce the issue from the example app.
- Keep the repro code as simple as possible, with the minimum amount of code required to repro the issue.
- Before reporting an issue, make sure you are on latest version of the package.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |
| @react-navigation/native       |
| @react-navigation/stack        |
| react-native-gesture-handler   |
| react-native-safe-area-context |
| react-native-screens           |
| react-native                   |
| expo                           |
| node                           |
| npm or yarn                    |

**Comment by satya164** [comment]
> from using navigate to push, because we always want a push screen animation

navigate also does push animation. not sure what you mean. you can achieve idempotent navigate actions the same way and get the behaviour that you want.

**Comment by linda167** [comment]
@satya164 The problem is that if we use navigate, and try to push a screen that was already previously pushed onto the current stack, then it will not do a push animation, whereas StackActions.push will always do a push animation. If there is a way to always do push navigation using navigate, it would be great if you could point us to it, as I have not been able to find a way to achieve this. Thanks!

**Comment by satya164** [comment]
If you're using a key to make `navigate` idempotent, there's not going to be a screen that was already pushed to the stack unless you're quickly tapping a button. What am I missing?

**Comment by linda167** [comment]
@satya164 Yes, if I use the key prop, it always will do the push animation, but it seems to lose the idempotency protection. As soon as I start using a key, then when I double tap a button, the navigate will happen twice. This seems like a bug with the implementation?

**Comment by satya164** [comment]
if you generate a new key on each tap, then it'll navigate multiple times. just avoid generating a new key each tap, or debounce your taps.

**Comment by linda167** [comment]
@satya164, Thanks, that actually makes a lot of sense. I think we can generate a key for our scenario that is different from the previous pushed screen, but is the same key for pushing a specific new screen to avoid the multiple navigation. Will give this a try, thanks! :)
