### ISSUE TITLE
componentDidMount called twice on stack switching.

### ISSUE THREAD

**Issue by beingArkReal** [react-navigation/react-navigation#7781]
**Current Behavior**

-ComponentDidMount called twice when switching stack using redux.
-This happens isNewUser redux state change from true to false from EnrollmentStack_.

`  return (
    <NavigationContainer>
      {isUserLoggedIn ? (
        isNewUser ? (
          <EnrollmentStack_ />
        ) : (
          <RootStackScreen />
        )
      ) : (
        <Stack.Navigator>
          <Stack.Screen name="AuthenticationScreenId" component={AuthenticationScreen} options={{headerShown: false}} />
        </Stack.Navigator>
      )}
    </NavigationContainer>)`

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |both
| @react-navigation/native       |5.0
| @react-navigation/stack        |5.0

**Comment by satya164** [comment]
Closing due to incomplete issue template.
