### ISSUE TITLE
react navigation part of screen not render ios swipe back

### ISSUE THREAD

**Issue by EhsanSarshar** [react-navigation/react-navigation#7784]
I have a main page and I push a page on top of it and then another page on top of that. so when I swipe back or pop the screens one after another. the last screen which is root just shows part of screen. 

![partOfScreenHide](https://user-images.githubusercontent.com/46188784/76448720-6cf85d00-63e8-11ea-8f29-d607cfad658f.png)

![ezgif com-optimize](https://user-images.githubusercontent.com/46188784/76451995-fe1e0280-63ed-11ea-8ea4-ed5e7dd6c003.gif)

A _push_ B _push_ C

C _popTo_ B _popTo_ A

when I pop to screen A it shows part of the screen.
this bug is only in ios 

I test it in iPhone x
**_this problem specially occur when app go in background and then come in foreground_**

"react-navigation": "^4.0.10",
"react-navigation-stack": "^1.10.3",
"react-navigation-tabs": "^2.5.6"
"react-native-gesture-handler": "^1.6.0"

System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz
    Memory: 39.90 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.13.0 - /usr/local/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.13.7 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 25, 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.3.1/11C505 - /usr/bin/xcodebuild

**Comment by EhsanSarshar** [comment]
the actual problem is when app go in background. 
and if I again put app to background and then come back the screen suddenly fix

**Comment by EhsanSarshar** [comment]
@WoLewicki it's so much overhead to reproduce it
so explain my router structure to you. sorry if it's not really helpfull.

TopNavigator = { ScreenD, ScreenF}

BottomTab = {  TopNavigator, ScreenB, ScreenC}

StackNavigator = {BottomTab,  DetailsScreen}

when I open the app it by default navigate  to BottomTab > TopNavigator > ScreenD

inside ScreenD I push DetailsScreen and then inside DetailsScreen I push another DetailsScreen on stack. so if I swipe the screen back, it will pop the screens and finally navigate to screenD which is root. it's working as expected
but if I push the screens and suddenly go to home screen of my phone then come back to app. the swipe button not work as expected. it seems that it swipe the screen that is in stack with it self to the left.


sorry if it's not really helpful. I will try my best to reproduce it in a snack

**Comment by WoLewicki** [comment]
Try to create the minimal configuration that would cause the bug to appear

**Comment by idan666** [comment]
@EhsanSarshar were you able to fix this? i have this issue as well... happens when coming back from background

**Comment by EhsanSarshar** [comment]
@idan666 no not yet.
I think I should rewrite my app with react navigation@5

**Comment by satya164** [comment]
You're using an old version of `react-navigation-stack`. Please upgrade to the latest version.

**Comment by EhsanSarshar** [comment]
@satya164 let me check

**Comment by EhsanSarshar** [comment]
@satya164 thanks alot that solved the problem.

**Comment by EhsanSarshar** [comment]
by updating, this problem solved but it generate another [issue](https://github.com/react-navigation/react-navigation/issues/7841).
