### ISSUE TITLE
V5 Fast Refresh it was to work?

### ISSUE THREAD

**Issue by ruyjfs** [react-navigation/react-navigation#7785]
In my app with v5, the fast refresh not working, every time is reloaded everything and I have to navigate every time to where i was, when i save the code file. Is working with fast refresh? 

My version is: ^5.0.6

Thanks for help!

**Comment by WoLewicki** [comment]
It should work just right. Can you provide a snack that shows the problem?

**Comment by arberK** [comment]
I am also having this issue in majority of my screens. My navigation has become very complex, and it is very hard to find the root of the problem right now. I'll respond if I find something.

**Comment by kamui545** [comment]
I had the same issue and noticed it was coming from my screens and UI Package, not react-navigation.
After refactoring and migrating to `react-native-paper` for the UI, everything worked fine.

Could you share a simple screen where you have this issue?

**Comment by ruyjfs** [comment]
It's my fault.

The problem was mine, for some reason I had removed the "React$Node" from index.tsx, I created a project from scratch and I was comparing, my mistake, sorry guys, you are great. Congratulations on the excellent work, I'm enjoying it very much. Big hug! 🤜🏼🤛🏼
