### ISSUE TITLE
RNCSafeAreaView was not found in the UIManager

### ISSUE THREAD

**Issue by vuggg** [react-navigation/react-navigation#7787]
**System:**
    OS: Linux 5.3 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i5-4300U CPU @ 1.90GHz
    Memory: 378.16 MB / 7.66 GB
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 12.16.1 - /usr/bin/node
    Yarn: 1.21.1 - /usr/bin/yarn
    npm: 6.13.4 - /usr/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  **SDKs:**
    Android SDK:
      API Levels: 23, 25, 27, 28
      Build Tools: 23.0.1, 23.0.3, 27.0.3, 28.0.3
      System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-git-upgrade: 0.2.7

```
"dependencies": {
    "@react-native-community/masked-view": "^0.1.7",
    "@react-navigation/bottom-tabs": "^5.1.1",
    "@react-navigation/native": "^5.0.9",
    "@react-navigation/stack": "^5.1.1",
    "prop-types": "^15.7.2",
    "react": "16.9.0",
    "react-native": "0.61.5",
    "react-native-deprecated-custom-components": "^0.1.2",
    "react-native-gesture-handler": "^1.6.0",
    "react-native-reanimated": "^1.7.0",
    "react-native-safe-area-context": "^0.7.3",
    "react-native-screens": "^2.3.0",
    "react-native-scrollable-tab-view": "^1.0.0",
    "react-native-swiper": "^1.6.0-rc.3",
    "react-native-tab-navigator": "^0.3.4"
  }
```

code:

```
function HomeScreen() {
  return (
    <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
      <Text>Home!</Text>
    </View>
  );
}

function SettingsScreen() {
  return (
    <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
      <Text>Settings!</Text>
    </View>
  );
}
return (
      <NavigationContainer>
        <Tab.Navigator>
          <Tab.Screen name="Home" component={HomeScreen} />
          <Tab.Screen name="Settings" component={SettingsScreen} />
        </Tab.Navigator>
      </NavigationContainer>
    )

```

**Comment by kubilaytural** [comment]
I have this problem. What's the solution?

**Comment by uloco** [comment]
Upgrading to v0.62.2 worked for me, but not what I wanted to do.
Is there any way to use react-navigation v5 with v61.5?
Also this problem only appears on Android, not in iOS.

**Comment by suwu150** [comment]
I have this problem. What's the solution?
      Android SDK:
        API Levels: 24, 26, 27, 28, 29
        Build Tools: 26.0.2, 26.0.3, 27.0.3, 28.0.2, 28.0.3, 29.0.2
        System Images: android-28 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6241897
      Xcode: 11.3/11C29 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.10 => 0.59.10 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-update-cli: 1.1.3
