### ISSUE TITLE
How to structure deep link in nested navigator

### ISSUE THREAD

**Issue by krissnawat** [react-navigation/react-navigation#7790]
**Current Behavior**

Hi guy got stuck on structure deep link in nested navigator first here my navigation code it's just stack inside the tab

```
function HomeStack() {
return (
    <Stack.Navigator>
        <Stack.Screen
            name="Home"
            component={HomeScreen}
        />
        <Stack.Screen
            name="SinglePost"
            component={SinglePost}
        />
    </Stack.Navigator>
  );
} 
```

and bottom tabs

  <Tab.Screen name="Home" component={HomeStack} />

so this is config part of react navigation that for organize deeplink first i put a stack parent
```
const config = {
Home: {
    path: "stack",
    initialRouteName: "SinglePost",
    screens: {
        Home: "home",
        SinglePost: {
            path: "post/:post_id",
            parse: {
                post_id: Number,
            }
        }
    }
  }
};
```
 
then when navigating to this screen with

xcrun simctl openurl booted Kriss://post/3232

got error

![](https://i.stack.imgur.com/Q1M2G.png)

**Expected Behavior**

- should navigate to SinglePost screen and pass parameter 

**How to reproduce**

I paste Navigation code part on snack
https://snack.expo.io/@krissnawat/d731df
**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |
| @react-navigation/native       |
| @react-navigation/stack        |
| react-native-gesture-handler   |
| react-native-safe-area-context |
| react-native-screens           |
| react-native                   |\
| node                           |
| npm or yarn                    |

**Comment by WoLewicki** [comment]
Can you use deep-linking to get to any of the screens or does it always throw an error? Also, can you print the state created from passing the link?

**Comment by margaridaDinis** [comment]
I think your config should be:
```
const config = {
  Home: "home",
  SinglePost: {
    path: "post/:post_id",
    parse: {
      post_id: Number,
    }
  }
};
```
