### ISSUE TITLE
 Unable to resolve module `@react-navigation/core`

### ISSUE THREAD

**Issue by uendar** [react-navigation/react-navigation#7791]
Hi everyone,

I get this error :

_error Unable to resolve module `@react-navigation/core` from `node_modules\react-navigation-redux-helpers\src\reducer.js`: @react-navigation/core could not be found within the project or in these directories:
  ..\..\..\node_modules\@react-navigation_

When i try to build project.  This are the modules i use.

Should i install apart `@react-navigation/core` ??

>  "dependencies": {
>     "@react-native-community/art": "^1.2.0",
>     "@react-native-community/datetimepicker": "^2.2.3",
>     "@react-native-community/google-signin": "^3.0.4",
>     "@react-native-community/masked-view": "^0.1.7",
>     "@react-native-community/netinfo": "^5.5.1",
>     "@react-native-firebase/app": "^6.3.4",
>     "@react-native-firebase/messaging": "^6.3.4",
>     "base64-js": "^1.3.1",
>     "create-react-native-module": "^0.16.0",
>     "dateformat": "^3.0.3",
>     "formik": "^2.1.4",
>     "global": "^4.4.0",
>     "install": "^0.13.0",
>     "json2csv": "^4.5.4",
>     "mime": "^2.4.4",
>     "moment": "^2.24.0",
>     "native-base": "^2.13.8",
>     "prop-types": "^15.7.2",
>     "react": "16.9.0",
>     "react-native": "0.61.5",
>     "react-native-charts-wrapper": "^0.5.7",
>     "react-native-document-picker": "^3.2.4",
>     "react-native-elements": "^1.2.7",
>     "react-native-exit-app": "^1.1.0",
>     "react-native-file-picker": "0.0.19",
>     "react-native-file-viewer": "^2.0.2",
>     "react-native-fs": "^2.16.6",
>     "react-native-gesture-handler": "^1.6.0",
>     "react-native-google-drive-api-wrapper": "^1.2.0",
>     "react-native-html-to-text": "0.0.5",
>     "react-native-image-crop-picker": "^0.28.0",
>     "react-native-image-picker": "^2.3.1",
>     "react-native-keyboard-aware-scroll-view": "^0.9.1",
>     "react-native-loading-spinner-overlay": "^1.1.0",
>     "react-native-modal": "^11.5.4",
>     "react-native-modal-filter-picker": "^2.0.0",
>     "react-native-onesignal": "^3.6.5",
>     "react-native-pdf": "^6.0.1",
>     "react-native-pie": "^1.1.2",
>     "react-native-reanimated": "^1.7.0",
>     "react-native-safe-area-context": "^0.7.3",
>     "react-native-screens": "^2.3.0",
>     "react-native-sensor-manager": "^0.1.10",
>     "react-native-simple-radio-button": "^2.7.4",
>     "react-native-simple-toast": "^1.0.0",
>     "react-native-smart-barcode": "^1.0.6",
>     "react-native-spinkit": "^1.5.0",
>     "react-native-step-indicator": "0.0.11",
>     "react-native-svg": "^12.0.3",
>     "react-native-timeago": "^0.5.0",
>     "react-native-typography": "^1.4.1",
>     "react-navigation": "^4.2.2",
>     "react-navigation-redux-helpers": "^4.0.1",
>     "react-redux": "^5.0.7",
>     "realm": "^4.0.0-beta.0",
>     "redux": "^4.0.0",
>     "redux-thunk": "^2.3.0",
>     "rn-fetch-blob": "^0.12.0",
>     "shortid": "^2.2.15",
>     "util": "^0.12.2",
>     "uuid": "^7.0.2",
>     "validate-model": "0.0.2",
>     "yup": "^0.28.3"
>   },

**Comment by WoLewicki** [comment]
Did you try to remove your `node_modules` and install them again? Looking at `react-navigation-redux-helpers` package.json, the `@react-navigation/core` is in its peerDependencies.

**Comment by WoLewicki** [comment]
We don't support `redux-helpers`. Please submit the issue in `redux-helpers` repo.
