### ISSUE TITLE
Can not run in a project without Typescript

### ISSUE THREAD

**Issue by brandons** [react-navigation/react-navigation#7796]
When attempting to run in a project without typescript metro bundler errors out because it can not recognize typescript. 

```
error: bundling failed: SyntaxError: /Users/brandon/Development/frontend1/src/rn/node_modules/@react-navigation/stack/src/utils/memoize.tsx: Unexpected token, expected "," (1:62)

> 1 | export default function memoize<Result, Deps extends readonly any[]>(
    |                                                               ^
  2 |   callback: (...deps: Deps) => Result
  3 | ) {
  4 |   let previous: Deps | undefined;
```

Reproduction steps:

- Add react navigation and react navigation stack to a project without typescript set up.
- Start the bundler and load the app.
- Observe an error similar to the one above 

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | 13.3
| @react-navigation/native       | 3.4.0
| @react-navigation/stack        | 5.1.1
| react-native-gesture-handler   | 1.6.0
| react-native-safe-area-context | 0.7.3
| react-native-screens           | 2.3.0
| react-native                   | 0.61.2
| expo                           | N/A
| node                           | 8.11
| npm or yarn                    |

**Comment by satya164** [comment]
Use the default preset that metro uses or add the typescript preset to your babel config to build TypeScript files.
