### ISSUE TITLE
Simple Stack not working

### ISSUE THREAD

**Issue by Derewith** [react-navigation/react-navigation#7797]
**Current Behavior**
[This example](https://reactnavigation.org/examples/5.x/simple-stack.js) is not working in [snack.expo.io](snack.expo.io). 
Also all the others examples from the website of react-navigation v5 are not working on a real iOS device.

**Expected Behavior**
To render the navigator

**Comment by Kielan** [comment]
please fix the hyperlinks so that this thread does not get archives

**Comment by WoLewicki** [comment]
I think it is a duplicate of #7807, so I am closing it. Tell me please if I am wrong.

**Comment by Derewith** [comment]
Mine was started before.. btw ok

**Comment by WoLewicki** [comment]
True, it's my mistake, sorry. Also, #7807 seems to better describe the exact bug.
