### ISSUE TITLE
Nested stack navigator inside drawer navigator have weird interaction behavior

### ISSUE THREAD

**Issue by Darkystel** [react-navigation/react-navigation#7798]
**Current Behavior**
Screens that are inside of a stack navigator seem to have a weird behavior where events fire but for some reason in the case of RN's Switch component resets after changing its value by tapping it.
The `onValueChange `event of the Switch is fired but it switched back to its initial value.

[A GIF with the described behavior](https://tenor.com/view/gif-16566322)

**Expected Behavior**
The Switch should remain on the changed position/value upon tapping it.

**How to reproduce**

[Here](https://github.com/Darkystel/navigation-issue) is a reproduction of the issue without any distractions, the code was tested and the issue was present.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |The issue was present in Android, was not tested on iOS|
| @react-navigation/native       |5.0.9|
| @react-navigation/stack        |5.1.1|
| @react-navigation/drawer        |5.1.1|
| react-native-gesture-handler   |1.5.0|
| react-native-safe-area-context |0.6.0|
| react-native-screens           |2.0.0-alpha.12|
| react-native                   |[sdk-36.0.0](https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz) |
| expo                           |36.0.0|
| node                           |v12.16.0|
| npm or yarn                    |npm: 6.14.2, yarn: 1.21.1|

**Comment by WoLewicki** [comment]
Can you provide a snack that will show the bug? In the repo, it looks like you use `<Switch />` without keeping its value in a state, or am I not seeing something? Shouldn't it be something like: 

```
const [value, setValue] = React.useState(false);

 <Switch onValueChange={value => setValue(value)} value={value} />
```

**Comment by Darkystel** [comment]
Oh, I didn't use switches enough and I forgot that I must do that 😅.
The thing that threw me off was that when I used a TextInput component in the screen it was losing focus immediately as I tap on it, and I read in one of the issue posts that react-native-screens' `enableScreens()` used to have a bug where it makes screens nested inside navigators unresponsive to events.
Thanks @WoLewicki !
