### ISSUE TITLE
RN5 and expo-dark-mode-switch make the app exit on Android

### ISSUE THREAD

**Issue by kopax** [react-navigation/react-navigation#7799]
**Current Behavior**

Using `expo-dark-mode-switch` v0.0.1 and RN5 5.1.1, my app crash when I press the switch.

This error happen only on Android

**Expected Behavior**

I expect no error

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Android
| @react-navigation/native       |  5.0.9
| @react-navigation/stack        | 5.1.1
| @react-navigation/drawer        | 5.1.1
| react-native-gesture-handler   | 1.6.0
| react-native-safe-area-context | 0.7.3
| react-native-screens           | 2.3.0
| react-native                   |
| expo                           | sdk 36.0.1
| node                           | v13.5.0
| npm or yarn                    | 6.14.0

**Comment by kopax** [comment]
Hi @WoLewicki , thanks for tagging this.

 This is a private project, I am pretty sure I can prepare a minimal reproduction after the first delivery. 

We fixed the alpha since it worked enough for our current needs. 

I am pretty sure we want this upgrade in this end. Can this remain open till june 2020? By now, I can probably shot a video showing the difference, but it look exactly the same except the application crash. 

It's maybe worth to say, but that's probably not related to the `expo-dark-switch-theme`, but to any page change.

**Comment by satya164** [comment]
Closing since you haven't provided a repro. Please open a new issue with a minimal repro if you're still having problems.
