### ISSUE TITLE
React native material top navigator swipe enabled doesn't work

### ISSUE THREAD

**Issue by BSThisarasinghe** [react-navigation/react-navigation#7803]
In my app, I am using react-navigation-tabs version 2.6.2. This is my code.

`const TopTabNavigator = createMaterialTopTabNavigator({

  slideshow: {

    screen: Welcome,

    navigationOptions: ({ navigation }) => ({

        title: '',

        swipeEnabled: true

    })
  },
  businessReg: {

    screen: BusinessReg,

    navigationOptions: ({ navigation }) => ({

        title: '',

        swipeEnabled: true

    })

  }

}, {

  swipeEnabled: true

});`

Navigation works fine but swipe doesn't work although I have made it true. Am I missing something in my code or is this a bug?

I have done installation correctly according to my knowledge.

**Comment by satya164** [comment]
Closing due to no repro.
