### ISSUE TITLE
Reopening: Sample Snack from 5.0 Documentation fails

### ISSUE THREAD

**Issue by hjpsievert** [react-navigation/react-navigation#7807]
**Current Behavior**

I am reopening the previous issue [7771](https://github.com/react-navigation/react-navigation/issues/7771#issue-578769996) which was closed by @WoLewicki. The original error is not occurring anymore, instead there is a similar error about being unable to resolve a module.

Running the Sample snack from the 5.0 Drawer documentation for web or tap to play android/iOS fails with the following error:

```
Device: (0:0) Unable to resolve module 'module://fbjs/lib/invariant.js'
  Evaluating module://fbjs/lib/invariant.js
  Evaluating module://react-native-reanimated.js
  Evaluating module://@react-navigation/drawer.js
  Evaluating module://App.js.js
  Loading module://App.js
```

**Expected Behavior**

Expected navigation example to render

**How to reproduce**

Run the referenced [snack](https://snack.expo.io/?platform=android&name=Drawer%20navigation%20%7C%20React%20Navigation&dependencies=%40react-native-community%2Fmasked-view%40%5E0.1.1%2C%40react-navigation%2Fnative%40%5E5.0.5%2C%40react-navigation%2Fbottom-tabs%40%5E5.0.5%2C%40react-navigation%2Fdrawer%40%5E5.0.5%2C%40react-navigation%2Fmaterial-bottom-tabs%40%5E5.0.5%2C%40react-navigation%2Fmaterial-top-tabs%40%5E5.0.5%2C%40react-navigation%2Fstack%40%5E5.0.5%2Creact-native-gesture-handler%401.5.2%2Creact-native-reanimated%401.4.0%2Creact-native-safe-area-context%400.6.0%2Creact-native-screens%402.0.0-alpha.12&sourceUrl=https%3A%2F%2Freactnavigation.org%2Fexamples%2F5.x%2Fdrawer-based-navigation.js) for web, but same error occurs for iOS and Android

I am trying to submit a rendering issue with Drawer Navigator, but my [snack repro](https://snack.expo.io/@hjpsievert/59d468) dies with the same error.

**Your Environment**

Not applicable, this happens on Snack

**Comment by hjpsievert** [comment]
I did try the example on the useFocusEffect from the React Navigation documentation and that [snack](https://snack.expo.io/?platform=android&name=useFocusEffect%20%7C%20React%20Navigation&dependencies=%40react-native-community%2Fmasked-view%40%5E0.1.1%2C%40react-navigation%2Fnative%40%5E5.0.5%2C%40react-navigation%2Fbottom-tabs%40%5E5.0.5%2C%40react-navigation%2Fdrawer%40%5E5.0.5%2C%40react-navigation%2Fmaterial-bottom-tabs%40%5E5.0.5%2C%40react-navigation%2Fmaterial-top-tabs%40%5E5.0.5%2C%40react-navigation%2Fstack%40%5E5.0.5%2Creact-native-gesture-handler%401.5.2%2Creact-native-reanimated%401.4.0%2Creact-native-safe-area-context%400.6.0%2Creact-native-screens%402.0.0-alpha.12&sourceUrl=https%3A%2F%2Freactnavigation.org%2Fexamples%2F5.x%2Fsimple-focus-effect.js) worked, but it uses a tab navigator.

**Comment by raajnadar** [comment]
in package.json of snack add `"fbjs": "1.0.0"`  or `"fbjs": " latest"`this should fix the issue.

**Comment by hjpsievert** [comment]
Unfortunately that does not work, get a new error now:

Device: (0:0) Cannot assign to read only property 'exports' of object '#<Object>'
  Evaluating module://@react-navigation/native.js
  Evaluating module://@react-navigation/drawer.js
  Evaluating module://App.js.js
  Loading module://App.js

**Comment by hjpsievert** [comment]
Just to add one more bit of information, the above error occurs when I run on web, if I use tap to play for iOS or Android, I get this:

Device: (900:881) Attempted to assign to readonly property.
  Evaluating module://@react-navigation/native.js
  Evaluating module://@react-navigation/drawer.js
  Evaluating module://App.js.js
  Loading module://App.js

**Comment by raajnadar** [comment]
After adding `fbjs` in package.json use Expo sdk 36 it will fix the issue.

**Comment by hjpsievert** [comment]
@raajnadar, thanks for the update. Is there any way to run the snack with SDK 37, I already upgraded a while ago and really don't want to introduce new issues by downgrading?

**Comment by satya164** [comment]
Try opening the snacks from the documentation again and they should work now without any changes.

**Comment by hjpsievert** [comment]
@satya164, I was able to confirm that the newest documentation sample for drawer navigator works. I was not able to get my own repro sample to work, but with all the updates to react navigation, I first have to redo my repro anyhow, so it may work as well. Closing this issue...

**Comment by mustafa5555** [comment]
same issue i cant solve it .

**Comment by mustafa5555** [comment]
> Just to add one more bit of information, the above error occurs when I run on web, if I use tap to play for iOS or Android, I get this:
> 
> Device: (900:881) Attempted to assign to readonly property.
> Evaluating module://@react-navigation/native.js
> Evaluating module://@react-navigation/drawer.js
> Evaluating module://App.js.js
> Loading module://App.js

same issue. i cant fix it. help please.

**Comment by hjpsievert** [comment]
Did you try this [snack ](https://snack.expo.io/?platform=android&name=Drawer%20navigation%20%7C%20React%20Navigation&dependencies=%40react-native-community%2Fmasked-view%40%5E0.1.7%2C%40react-navigation%2Fbottom-tabs%40%5E5.4.2%2C%40react-navigation%2Fdrawer%40%5E5.7.2%2C%40react-navigation%2Fmaterial-bottom-tabs%40%5E5.2.2%2C%40react-navigation%2Fmaterial-top-tabs%40%5E5.2.2%2C%40react-navigation%2Fnative%40%5E5.3.0%2C%40react-navigation%2Fstack%40%5E5.3.2%2Creact-native-paper%40%5E3.10.1%2Creact-native-reanimated%40%5E1.7.0%2Creact-native-safe-area-context%40%5E0.7.3%2Creact-native-screens%40%5E2.4.0%2Creact-native-tab-view%40%5E2.14.0&sourceUrl=https%3A%2F%2Freactnavigation.org%2Fexamples%2F5.x%2Fdrawer-open-close-toggle.js)link from the most recent react navigation docs?

I tried it for web, Android, and iOS, all three work for me, SDK is 37.

**Comment by mustafa5555** [comment]
> Did you try this [snack ](https://snack.expo.io/?platform=android&name=Drawer%20navigation%20%7C%20React%20Navigation&dependencies=%40react-native-community%2Fmasked-view%40%5E0.1.7%2C%40react-navigation%2Fbottom-tabs%40%5E5.4.2%2C%40react-navigation%2Fdrawer%40%5E5.7.2%2C%40react-navigation%2Fmaterial-bottom-tabs%40%5E5.2.2%2C%40react-navigation%2Fmaterial-top-tabs%40%5E5.2.2%2C%40react-navigation%2Fnative%40%5E5.3.0%2C%40react-navigation%2Fstack%40%5E5.3.2%2Creact-native-paper%40%5E3.10.1%2Creact-native-reanimated%40%5E1.7.0%2Creact-native-safe-area-context%40%5E0.7.3%2Creact-native-screens%40%5E2.4.0%2Creact-native-tab-view%40%5E2.14.0&sourceUrl=https%3A%2F%2Freactnavigation.org%2Fexamples%2F5.x%2Fdrawer-open-close-toggle.js)link from the most recent react navigation docs?
> 
> I tried it for web, Android, and iOS, all three work for me, SDK is 37.

yes this snack works fine but when i run my project it says:

Device: (856:881) Attempted to assign to readonly property.
  Evaluating module://react-native-screens.js
  Evaluating module://react-navigation-tabs.js
  Evaluating module://App.js.js
  Loading module://App.js
