### ISSUE TITLE
New route remove itself

### ISSUE THREAD

**Issue by wojtekhorembala** [react-navigation/react-navigation#7808]
Hello,

I have problem with navigation, when I try swipe back view and fast click button which open new view this but this is view have same route name what have this previous I have bug - new screen closes (Look at video)

This only happens if you create a new view very quickly, and only when i swipe

youtube link - https://www.youtube.com/watch?v=smakcDs9gC4&feature=youtu.be (showing bug)

**My code**
My code which have task to open new route with the same name

```
export const changeRoute = (routeName, params, key = undefined): void => {
   const route = NavigationActions.navigate({
            routeName,
            params,
            key: key ? `${ routeName }${ key }` : undefined,
    });
    navigator.dispatch(route);
};
```

**Your Environment**

"react-navigation-stack": "^2.0.8",
"react-navigation": "^4.0.10",

**Comment by satya164** [comment]
Please upgrade to latest version before opening issues.
