### ISSUE TITLE
Detect goBack on previous screen

### ISSUE THREAD

**Issue by ShrikantRao** [react-navigation/react-navigation#7810]
This is a very good use-case where I want 2 different events or 2 different animation to perform on screen focus (on screen-2). First animation will run on navigating from screen-1 to screen-2 and second on navigating from screen-3 to screen-2 (goBack).

In V4 and V5 I don't find any function or hook which help me identify this (goBack) on screen-2. Please correct me if I'm wrong. There should be a hook which help identify (on Screen-2) that user is coming from Screen-3.

Instead of just 'focus' can there be 3 versions of 'focus'.

focus - standard one
focusOnPush or focusForward
focusOnPop or focusBackward

Same for Blur.

**Comment by satya164** [comment]
`focusOnPush` -> `componentDidMount`
`blurOnPop` -> `componentWillUnmount`

**Comment by ShrikantRao** [comment]
@satya164 Thanks for your reply. Sorry If I didn't make myself clear. `componentDidMount` and `componentWillUnmount` will not fire, because I'm not navigating back from screen-2.

Let me put it again. I got 3 screens (screen-1, screen-2 & screen-3). And similarly I have navigated from screen-1 to screen-2 and then to screen-3. On Screen-3 I click back (goBack) I'll land on screen-2. On screen-2 I'm looking for an event/hook so that I can handle my animation. 

So when I land on screen-2 the focus event will fire but at this point I couldn't identify that user is coming from screen-1 or screen-3. ComponentDidMount will only fire if user is coming from Screen-1 not from Screen-3 

Similarly when I navigate to screen-1 from screen-2 or screen3 from screen-2, on screen-2 Blur event will fire but I couldn't identify that user is going back or forward. ComponentWillUnmount will only run if user is going back not in case of forward.

I hope this time I made it clear.

**Comment by satya164** [comment]
Then `focus` and `blur` events will fire. you can detect all of the scenarios you mentioned using `componentDidMount`, `componentWillUnmount`, `focus` and `blur`.

For animations, you also get a `closing` argument that tells you whether the animation is because of a screen closing (going back) or not which sounds more like what you want. https://github.com/react-navigation/react-navigation/blob/0dcaea32428484cdc9b4d56f7bf38f9f1bdf1dee/packages/stack/src/TransitionConfigs/CardStyleInterpolators.tsx#L180

**Comment by ShrikantRao** [comment]
@satya164  How will I get access of this `closing` argument in my screens file (Dashboard.js, Myaccount.js, Setting.js)? All my routes and CardStyleInterpolators has been declared on my Navigation.js file.

**Comment by satya164** [comment]
use the `useCardAnimation()` hook

**Comment by grifotv** [comment]
out of curiosity, `useCardAnimation` provides properties with Animated or Reanimated nodes?

**Comment by grifotv** [comment]
Saw now that the `stack-navigator` uses *Animated* but `drawer-navigator` uses *Reanimated*.
