### ISSUE TITLE
Animation related options

### ISSUE THREAD

**Issue by BlackJohnny** [react-navigation/react-navigation#7811]
**Current Behavior**

No matter what I set with the Stack.Screen options, nothing applies. I must do something wrong but I have no clue what.

If I hook it with a callback (as bellow), it is called but doesn't matter what I return, it does not get applied.
```
const Stack = createStackNavigator();

export default GlobalStack = () => {
  return (
    <Stack.Navigator headerMode="none">
    <Stack.Screen name="Name" component={Page}
        options={({ navigation, route }) => {
          console.log("route", route);
          return {
            animationEnabled: false,
          };
        }}
   />
   </Stack.Navigator>
   ...
```

Actually I just want to disable the animation. Can anyone give me a hint on what could cause such behavior?

Versions:

    "@react-navigation/drawer": "^5.2.0",
    "@react-navigation/native": "^5.0.10",
    "@react-navigation/stack": "^5.2.0",

**Comment by WoLewicki** [comment]
Can't you just do 
`<Stack.Screen name="Name" component={Page} options={{ animationEnabled: false }} />`

**Comment by BlackJohnny** [comment]
Thank you for your answers, unfortunately I've tried all the above.

Does anyone have a working version of such code? I tried everything according to the documentation. There must be something else that I am doing (or not doing) that makes the navigation to ignore these options.

**Comment by satya164** [comment]
Closing due to no repro.
