### ISSUE TITLE
Deep Linking in a conditional Stack Navigator throws error

### ISSUE THREAD

**Issue by OctaBruzzesi** [react-navigation/react-navigation#7812]
**Current Behavior**

- What code are you running and what is happening?
- Include a screenshot or video if it makes sense.

I have a structure like mentioned in https://reactnavigation.org/docs/auth-flow/.

This is my Navigation right now:

```
<NavigationContainer initalState={initialState} ref={ref}>
  {state.userToken ?
    <Tab.Navigator>
      <Tab.Screen name="Main" component={Main} />
      <Tab.Screen name="Settings" component={Settings} />
    </Tab.Navigator>
  :
    <Stack.Navigator>
      <Stack.Screen name="Login" component={Login} />
      <Stack.Screen name="InvitePart1" component={InvitePart1}/>
      </Stack.Navigator>
    }
</NavigationContainer>
```

And the configuration
```
const { getInitialState } = useLinking(ref, {
  prefixes: [prefix],
  config: {
    InvitePart1: 'invites/accept/:value',
  }
});
```

When you open a deep link with 'invites/accept/eydsflkhjkdshflhsdj' and you're logged in, meaning that the Tabs are being rendered, the app shows an error, which mentions that there is no screen InvitePart1.

The error is: 'The action NAVIGATE with... was not handled by any navigator'

**Expected Behavior**

It should navigate to a default screen, that could be Home, when the InvitePart1 is not being rendered, and not throw an error.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Both
| @react-navigation/native       | 5.0.9
| react-native                   | Expo
| expo                           | 36.0.0
| node                           | 10.16.0
| npm or yarn                    | 6.9.0

**Comment by neiker** [comment]
This error is a warning in fact. Which is confusion. 

On the bottom of the message you can see "This is a development-only warning and won't be shown in production."

**Comment by OctaBruzzesi** [comment]
> This error is a warning in fact. Which is confusion.
> 
> On the bottom of the message you can see "This is a development-only warning and won't be shown in production."

Sure, but where will it navigate in production? To the initial route?
It's useful to know that this path doesn't exist, and warn the developer. But it's shown as an error and I don't know how to handle this.

The question is, how can I arrange my code to allow these non-existing routes when I'm developing?

**Comment by neiker** [comment]
Seems like is not doing anything at all if route not exist.


https://github.com/react-navigation/react-navigation/blob/5bb0f405ceb5755d39a0b5b1f2e4ecee0da051bc/packages/core/src/useNavigationHelpers.tsx#L44-L78
I agree, that console.error maybe should be a console.warn

**Comment by fjcadenas** [comment]
Hello, I'm experiencing a similar problem:

`
  return (
    <NavigationContainer>
      <Stack.Navigator
        headerMode={isAuthenticated ? "float" : "none"}
      >
        {!isAuthenticated ? (
          <>
            <Stack.Screen name="Splash" component={SplashScreen} />
            <Stack.Screen name="Login" component={LoginScreen} />
          </>
        ) : (
          <Stack.Screen name="Home" component={HomeScreen} />
        )}
      </Stack.Navigator>
    </NavigationContainer>
  );
`
When my user tries to logout the isAuthenticated value changes to false and the SplashScreen gets rendered, but when I try to navigate to Login from Splash the  following error appears:

<img width="362" alt="Captura de pantalla 2020-03-16 a las 22 53 40" src="https://user-images.githubusercontent.com/17270991/76802928-fdfc7900-67d8-11ea-9955-fd7b7347b887.png">
Thank you all!

**Comment by WoLewicki** [comment]
@OctaBruzzesi could you try to wrap all the navigation in a stack navigator, which only screen would be all the navigation you have now? It would slightly change the config for deepLinking, but may work. @fjcadenas do you use deepLinking or just try to navigate from Login to splash?

**Comment by OctaBruzzesi** [comment]
> @OctaBruzzesi could you try to wrap all the navigation in a stack navigator, which only screen would be all the navigation you have now? It would slightly change the config for deepLinking, but may work. @fjcadenas do you use deepLinking or just try to navigate from Login to splash?

Hey @WoLewicki, I tried to wrap the navigation and it still fails. I think, as I said before that it shouldn't show an error in case the path doesn't exist. It should navigate to a default screen.

**Comment by WoLewicki** [comment]
> And as an update, it only occurs when the app is already open. Otherwise it doesn't show an error.

Do you land in the correct screen when the app is not already open?

**Comment by OctaBruzzesi** [comment]
> Do you land in the correct screen when the app is not already open?

Yes, it shows the default screen.

**Comment by WoLewicki** [comment]
I think the state resolved by the deep link says that there should be a screen named `InvitePart1` in your navigator, but since the navigator you are in is Tab, there is not, so it throws an error. When opening an app, it is different since the navigator that has that screen (Stack) is rendered and the action is handled properly. Am I right @OctaBruzzesi ?

**Comment by ethanyuwang** [comment]
having the same problem here. is there a way to delay the link resolve until the conditional navigator is set?

**Comment by patlux** [comment]
For everyone who needs to handle the initial deep link with conditional rendering of screens/navigators without blocking/unmounting the root navigator:

```typescript
class Deferred {
  promise: Promise<unknown>;
  resolve: ((v: unknown) => void) | undefined;
  reject: ((reason?: any) => void) | undefined;
  constructor() {
    this.promise = new Promise((resolve, reject) => {
      this.reject = reject;
      this.resolve = resolve;
    });
  }
}

function YourRootNavigatior()
  const waitFor = React.useRef(new Deferred());

  React.useEffect(() => {
    // something like `isAuthenticated `
    if (yourCondition) {
      waitFor.current.resolve?.(null);
    }
  }, [yourCondition]);
  
  return (
    <NavigationContainer
      /* React Element to use as a fallback while we resolve deep links */
      fallback={
        <YourLoadingSpinnerScreen />
      }
      linking={{
        async getInitialURL() {
          const url = await Linking.getInitialURL();
          if (url == null) {
            return null;
          }
          // Ensures that "fallback" is rendered until the promise has been resolved
          await waitForLoadDone.current.promise;
          // react-navigation will handle the deep link now, after your own condition resolved
          // which ensures that the corresponding navigation screens/navigators exists and are rendered below
          return url;
        },
        prefixes: [ ... ],
        config: { ... }
      }}
    >
      <RootStack.Navigator>
          {yourCondition ? (
            <Stack.Screen name="Home" component={HomeScreen} />
          ) : (
           <>
              <Stack.Screen name="Splash" component={SplashScreen} />
              <Stack.Screen name="Login" component={LoginScreen} />
            </>
          )}
      </RootStack.Navigator>
    </NavigationContainer>
  );
}
``
