### ISSUE TITLE
Error with popToTop() when on root screen

### ISSUE THREAD

**Issue by scarlac** [react-navigation/react-navigation#7814]
**Current Behavior**

Running `navigation.popToTop()` at the top/initial screen causes error that cannot be try-catch'ed:
```
console.error: "The action 'POP_TO_TOP' with payload 'undefined' was not handled by any navigator. If you are trying to navigate to a screen, check if the screen exists in your navigator. If you're trying to navigate to a screen in a nested navigator, see https://reactnavigation.org/docs/en/nesting-navigators.html#navigating-to-a-screen-in-a-nested-navigator."

_construct
    construct.js:30:26
Wrapper
    wrapNativeSuper.js:26:23
SyntheticError
    index.bundle?platform=ios&dev=true&minify=false:29187:111
reactConsoleErrorHandler
    ExceptionsManager.js:135:52
console.error
    YellowBox.js:63:8
performTransaction$argument_0
    useNavigationHelpers.tsx:49:10
setNavigationState$argument_0
    BaseNavigationContainer.tsx:148:18
dispatchAction
    [native code]:0
setNavigationState$argument_0
    BaseNavigationContainer.tsx:143:25
performTransaction$argument_0
    useNavigationHelpers.tsx:42:25
dispatch
    useNavigationCache.tsx:83:12
acc.name
    useNavigationCache.tsx:92:51
HeaderLogo.props.onPress
    index.js:21:29
createReactClass$argument_0.touchableHandlePress
    TouchableOpacity.js:264:45
touchableHandlePress
    [native code]:0
TouchableMixin._performSideEffectsForTransition
    Touchable.js:880:34
_performSideEffectsForTransition
    [native code]:0
TouchableMixin._receiveSignal
    Touchable.js:779:44
_receiveSignal
    [native code]:0
TouchableMixin.touchableHandleResponderRelease
    Touchable.js:490:24
touchableHandleResponderRelease
    [native code]:0
forEach
    [native code]:0
callFunctionReturnFlushedQueue
    [native code]:0
```

**Expected Behavior**

- What do you expect should be happening?
Nothing

**How to reproduce**

1. Add a button to a header that pops to top
2. Press the button
3. Press the button again

Crash/console.error() happens.

None of the Expo snacks in the documentation are currently working so I cannot provide an example.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | 13.3
| @react-navigation/native       | 5.0.5
| @react-navigation/stack        | 5.0.5
| react-native-gesture-handler   | 1.6.0
| react-native-safe-area-context | 0.7.3
| react-native-screens           | 2.0.0-beta.8
| react-native                   | 0.61.2
| expo                           | Not using expo
| node                           | Node not used (jsc is used)
| npm or yarn                    | yarn

**Comment by satya164** [comment]
It's a `console.error`, not error thrown that you should catch.

Regardless, you aren't supposed `try/catch` the navigation, but don't dispatch an action if it won't do anything. From UX perspective, it doesn't make sense to show a interactable button that won't do anything.

For `goBack`/`popToTop` you can use `navigation.canGoBack()` check or `useNavigationState(state => state.routes.length)` to determine if you can go back.

**Comment by scarlac** [comment]
This is undocumented behavior that one needs to use `canGoBack()`. I did my due diligence to check the documentation and source code and _I found no solution_. This used to work in previous versions (I am migrating to v5). I recommend one of:

1. Document behavior in the online docs
2. Document potential solution in the console.error message / a more helpful with reference to `canGoBack()`
3. Remove console.error statement

Either of the 3 options seem fine to do, and either of them would have caused me to not raise this ticket. I don't think ignoring the ticket entirely is the right course.

**Comment by mousikosk** [comment]
I'm handling the event of a Drawer menu item being pressed. `popToTop()` works just fine to reset the nested navigators (which is the requested behaviour when pressing the menu item of the nested stack you are currently on). The console.error makes this very annoying to use in development however.

**Comment by godlikeAlex** [comment]
### V5
You can get state from BotomTabBar. And when currentRoute state index not equal 0 call navigation.popToTop();


```ts
const currentRoute = state.routes.find(route => route.name === state.routeNames[index]);
  if (currentRoute?.state) 
    if (currentRoute.state.index !== 0) navigation.popToTop();
```

Full botomBar code

```ts
const BottomTabBar = ({ state, navigation, counterMessages}: {counterMessages: number, state: NavigationState, navigation: any}) => {
  const onSelect = (index: number) => {
    if(state.index !== index) {
      navigation.navigate(state.routeNames[index]);
    } else {
      const currentRoute = state.routes.find(route => route.name === state.routeNames[index]);
      if (currentRoute?.state) 
        if (currentRoute.state.index !== 0) navigation.popToTop();
    }
  };

  return (
    <BottomNavigation selectedIndex={state.index} onSelect={onSelect}>
      <BottomNavigationTab icon={HomeIcon}  />
      <BottomNavigationTab icon={SearchIcon} />
      <BottomNavigationTab icon={(props) => <EmailIcon {...props} counterMessages={counterMessages} />} />
      <BottomNavigationTab icon={UserIcon} />
    </BottomNavigation>
  );
};

const BottomBar = ({ counterMessages }) => {
  return (
    <Navigator tabBar={(props) => <BottomTabBar {...props} counterMessages={counterMessages} />}>
      <Screen name="HomeStack" component={MainStack}  />
      <Screen name="Search" component={SearchStack}  />
      <Screen name="Direct" component={DirectNavigator} />
      <Screen name="Profile" component={ProfileStack} />
    </Navigator>
  );
};
```

**Comment by zachdixon** [comment]
I know this is old but wanted to leave my solution to this issue since I just ran into it and found this. The above solution didn't work for me, but my case is similar. I have a nested stackNavigator in a bottomTabNavigator that I want to reset to the first screen when navigated to. `popToTop` in a `tabPress` listener "worked" but gave me this error/notice when on the first screen already. But the following worked no matter what:

```
React.useEffect(() => {
    const unsubscribe = navigation?.addListener?.('tabPress', (e) => {
      navigation.navigate('Home', { screen: 'Stores' })
    })

    return unsubscribe
  }, [navigation])
```
