### ISSUE TITLE
The replace event does not bubble up

### ISSUE THREAD

**Issue by musmanfaisal** [react-navigation/react-navigation#7815]
My Stack Navigator is like this

`const Stack = createStackNavigator();
const AuthStack = createStackNavigator();
const AppStack = createStackNavigator();

const _AuthStack = () => (
    <AuthStack.Navigator headerMode='none'>
        <AuthStack.Screen name='Welcome' component={WelcomeScreen} />
        <AuthStack.Screen name='Selection' component={SelectionScreen} />
        <AuthStack.Screen name='SignUpForm' component={SignUpFormScreen} />
        <AuthStack.Screen name='Login' component={LoginScreen} />
    </AuthStack.Navigator>
)

const _AppStack = () => (
    <AppStack.Navigator headerMode='none'>
        <AppStack.Screen name='AppHome' component={AppHome} />
        <AppStack.Screen name='Courses' component={Courses} />
    </AppStack.Navigator>
)

const Screens = () => {
    Axios.defaults.baseURL = constants.baseURL;
    return (
        <NavigationContainer>
            <StatusBar backgroundColor={constants.themeColor} barStyle='light-content' />
            <Stack.Navigator headerMode='none'>
                <Stack.Screen name='AuthStack' component={_AuthStack} />
                <Stack.Screen name='AppStack' component={_AppStack} />
            </Stack.Navigator>
        </NavigationContainer>
    );
};`

In the AuthStack->Login screen, upon login, I am calling this function

`navigation.replace('AppStack')`

And it doesn't work. However if I call the navigate function like this

`navigation.navigate('AppStack')`

The it works. So my best guess is that the replace function does not bubble up. If it could be fixed, that would be awesome.

**Comment by satya164** [comment]
You can make it bubble up by setting `source` to `undefined`.

```js
navigation.dispatch({
  ...StackActions.replace('AppStack'),
  source: undefined,
});
```
