### ISSUE TITLE
tabBarOnPress in RN v5

### ISSUE THREAD

**Issue by felix-voicehub** [react-navigation/react-navigation#7816]
I just upgraded from v4 to v5 and am still busy with the migration. I was wondering how I now implement `tabBarOnPress` in version 5. In v4, it looked like this:

```js
NotificationsStack.navigationOptions = {
	tabBarLabel: 'Notifications',
	tabBarOnPress: ({ defaultHandler }) => {
		// some custom stuff ....
		defaultHandler();
	},
	tabBarIcon: ({ tintColor }) => (
		<SomeIcon
			tintColor={tintColor} />
	),
};
```

Now it does seem like `tabBarOnPress` does not exist anymore in v5. I can't seem to figure out how I can now implement a function that gets called on pressing that icon.

**Comment by satya164** [comment]
https://reactnavigation.org/docs/bottom-tab-navigator#tabpress

**Comment by felix-voicehub** [comment]
Thanks, however I have 2 question regarding this snippet from the docs:

```js
React.useEffect(() => {
  const unsubscribe = navigation.addListener('tabPress', e => {
    // Prevent default behavior
    e.preventDefault();

    // Do something manually
    // ...
  });

  return unsubscribe;
}, [navigation]);
```
1. Where does this go? In the router/some root component?
2. Doesn't this then listen for ALL tabpresses? So I need to check which one it was if I just want to target one? Feels like a step backwards.
3. What is the `navigation` variable here?

**Comment by drager** [comment]
@felix-voicehub If you have a nested navigator for each tab you can do this:

```js

const YourStack = createStackNavigator();

const Navigator = ({navigation}) => {
    React.useEffect(() => {
        const unsubscribe = navigation.addListener("tabPress", e => {
            // Prevent default behavior
            e.preventDefault();

            alert("Default behavior prevented");
            // Do something manually
            // ...
        });

        return unsubscribe;
    }, [navigation]);

    return (
        <YourStack.Navigator>
            <YourStack.Screen name='start' component={Start} />
            <YourStack.Screen name='detail' component={Detail} />
        </YourStack.Navigator>
    );
};
```

**Comment by felix-voicehub** [comment]
thanks!
