### ISSUE TITLE
Add hook to get bottom tab height

### ISSUE THREAD

**Issue by abdallaemadeldin** [react-navigation/react-navigation#7817]

**Comment by WoLewicki** [comment]
If I understand correctly, you want such a feature to be added to the package?

**Comment by abdallaemadeldin** [comment]
@WoLewicki yes i wanna something like useHeaderHeight but for the material bottom tabs

**Comment by eriveltonelias** [comment]
Hey @abdallaemadeldin, 

can you open a rfc (https://github.com/react-navigation/rfcs), please?

**Comment by abdallaemadeldin** [comment]
done
