### ISSUE TITLE
NavigationProp should default ParamList to ParamListBase 

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [react-navigation/react-navigation#7819]
**Current Behavior**

Going off the recommended [`useNavigation`](https://reactnavigation.org/docs/use-navigation/#using-with-class-component) shim docs in a TypeScript project, this is how you'd type `MyBackButtonProps`:

```ts
export type MyBackButtonProps = {
    navigation: NavigationProp<{}>;
};

class MyBackButton extends React.Component<MyBackButtonProps> {
```

**Expected Behavior**

I'd like to be able to:

```ts
    navigation: NavigationProp;
```

...but because `NavigationProp` doesn't allow an `= ParamListBase` in its declaration, you have to provide at least the `{}`.

Basically I'm asking for this 😄:

```diff
- export declare type NavigationProp<ParamList extends ParamListBase, RouteName extends keyof ParamList = string, State extends NavigationState = NavigationState, ScreenOptions extends object = {}, EventMap extends EventMapBase = {}> = NavigationHelpersCommon<ParamList, State> & {
+ export declare type NavigationProp<ParamList extends ParamListBase = ParamListBase, RouteName extends keyof ParamList = string, State extends NavigationState = NavigationState, ScreenOptions extends object = {}, EventMap extends EventMapBase = {}> = NavigationHelpersCommon<ParamList, State> & {
```

> TypeScript feature request for a shorthand version of ☝️: https://github.com/microsoft/TypeScript/issues/30919

The same issue is on `RouteProp`/`useRoute`.

**How to reproduce**

<details>
<summary>The TypeScript playground is down, so here's a code snippet in the meantime.</summary>

```ts
import { withNavigation } from '@react-navigation/compat';
import { NavigationProp } from '@react-navigation/native';
import * as React from 'react';
import { Button } from 'react-native';

export type MyBackButtonProps = {
  navigation: NavigationProp<{}>;
}

class MyBackButton extends React.Component<MyBackButtonProps> {
  render() {
    // Get it from props
    const { navigation } = this.props;
  }
}

// Wrap and export
export default function(props) {
  const navigation = useNavigation<NavigationProp<{}>>();

  return <MyBackButton {...props} navigation={navigation} />;
}
```
</details>

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | N/A
| @react-navigation/native       | 5.0.9
| react-native                   | `https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz`
| expo                           | 36.0.2
| node                           | 12.4.0
| npm or yarn                    | yarn 1.21.1

**Comment by satya164** [comment]
You're not supposed to use it directly. Please refer to the docs on how to use the types https://reactnavigation.org/docs/typescript/

**Comment by JoshuaKGoldberg** [comment]
@satya164 I have read that doc, but the use case here is for lower-level components that don't care about the specifics of their parent navigators. I'd like to be able to mark the types in a generic way so that they don't need to know that they're in, say, a `BottomTabNavigationProp` or `CompositeNavigationProp`.

I understand this is meant to be a bug reporting forum so I can move to a feature request / StackOverflow post if this is becoming a feature request. Thanks for the prompt reply either way!

**Comment by satya164** [comment]
Even for lower-level components, a lot of times it's important to care about the parent navigator. e.g. button which opens drawer needs to use drawer specific navigation prop to get `navigation.openDrawer`. To know if the drawer is open, you need to use correct type so that the state object you get from `dangerouslyGetState()` returns correct type. A back button probably needs to access `navigation.pop` etc. It depends most of the time.

The generic is not optional so that when building types using it, it's not possible to forget to specify a proper type for params. That's how we have made most of our low-level types and it reduces mistakes for us. Internally we need specify the params everywhere too when using this prop.

If you don't want to specify it everywhere, you could also make an alias by specifying it in a separate file.
