### ISSUE TITLE
Property 'replace' does not exist

### ISSUE THREAD

**Issue by b3coded** [react-navigation/react-navigation#7820]
**Current Behavior**

```js
const navigation = useNavigation();
const handleSubmit = () => {
   navigation.replace('LoadingData');
};
```

VSCode ESLint message:
`Property 'replace' does not exist on type 'NavigationProp<Record<string, object | undefined>, string, NavigationState, {}, {}>'.ts(2339)`

But it still works.

**Expected Behavior**

No Type error.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
|  Android                 | 9.0
| @react-navigation/native       | 5.1.0
| react-native                   | 0.61.5
| expo                           | -
| node                           | 10.16.0
| yarn                    | 1.22.4

**Comment by satya164** [comment]
Please read the docs https://reactnavigation.org/docs/typescript/

**Comment by alexmccabe** [comment]
The easiest way to deal with this, if you don't need any strict typing is: 

```js
const navigation = useNavigation<StackNavigationProp<ParamListBase>>();
```
