### ISSUE TITLE
undefined is not a function in some Android 6.0 devices

### ISSUE THREAD

**Issue by willing8310** [react-navigation/react-navigation#7822]
**Current Behavior**

the code:

```
import ProfileEditScreen from "./ProfileEditScreen";
import { createAppContainer } from 'react-navigation';
import { createStackNavigator } from 'react-navigation-stack';
const AppNavigator = createStackNavigator({
    ProfileEdit: {
        screen: ProfileEditScreen
    }
}, {
        initialRouteName: 'ProfileEdit'
    })
export default createAppContainer(AppNavigator)
```

It works in most devices. But in 金立M6、GN8003（Android 6.0, level 23) and 三星SM-A5000 (Android 6.0.1, level 23), it doesnot work. The error is "TypeError: undefined is not a function(evaluating '['undefined','string','function','boolean','number'].includes(typeof config)')".

It occurs every time. Pls give me some help, thank you.

The screenshot has been attached.

I tried to upgrade react-navigation to 5.x, but the error still occurs.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| Android                 |  6.0
| react-navigation               |  3.6.1
| react-navigation-stack         | 1.10.3
| react-native-reanimated        | 1.7.0
| react-native                   | 0.61.5

![](http://tbfiles.testbird.com/upload//1584514568918_45d977ae7cbb4dbd8e9087ad16bd2f59.jpg)

**Comment by willing8310** [comment]
The parameter "config" value  is " { type: 'value', value: NaN }".

**Comment by satya164** [comment]
Closing since you didn't provide any repro. We need a minimal repro to be able to debug issues. Feel free to open a new issue if you have a repro.
