### ISSUE TITLE
Wrong spelling in inactiveBackgroundColor's description

### ISSUE THREAD

**Issue by vinifraga** [react-navigation/react-navigation#7827]
**Current Behavior**

The description says **olor** instead of **color**.
```tsx
  /**
   * Background olor for the active tab.
   */
  activeBackgroundColor?: string;
```

**Expected Behavior**

```tsx
  /**
   * Background color for the active tab.
   */
  activeBackgroundColor?: string;
```

**How to reproduce**

https://github.com/react-navigation/react-navigation/blob/master/packages/bottom-tabs/src/types.tsx#L141

Can/Should I open a PR with the fix?

**Comment by eriveltonelias** [comment]
Hey @vinifraga,

yes, please! I'll close this one and ping me when you're ready.
