### ISSUE TITLE
navigate to black screen

### ISSUE THREAD

**Issue by happystudy666** [react-navigation/react-navigation#7829]
hello,I used createSwitchNavigator  nested two createStackNavigator, navigate from the first to the second, and got a black screen. I replaced it with a createStackNavigator. I mean that the createStackNavigator nested two  createStackNavigator got what I want.please help me.

const Main = createStackNavigator(RouteConfigs, StackNavigatorConfig);

const LoginRoute = createStackNavigator(
    {
        Login: LoginStack.Login
    },
   
)
const App = createSwitchNavigator(
    {
        Login: Login,
        Main: Main
    },
   {
    initialRouteName: 'Login',
   }
)
 Android  
react-navigation  4.0.10
react-navigation-stack   2.0.1
react-navigation-tabs       2.6.2
react-native-reanimated      1.4.0
react-native-gesture-handler   1.5.2
react-native-safe-area-context 0.3.6
react-native-screens       2.3.0
react-native              0.61.4
node                          10.16.0
npm

**Comment by teivienn** [comment]
I have a similar problem, only when switching from createSwitchNavigator to createStackNavigator in which createBottomTabNavigator to ios

**Comment by satya164** [comment]
Closing due to no repro.
