### ISSUE TITLE
State persist and Deep linking togethers not work

### ISSUE THREAD

**Issue by tastafur** [react-navigation/react-navigation#7831]
**Current Behavior**

When i try to enter the app through deep linking, the app opens in the last persisted state

This code break deep linking
`
export function useStateNavigator() {
  const ref = useRef();

  const {getInitialState} = useLinking(ref, {
    prefixes: ['dgp-apps://'],
    config,
  });

  const [isReady, setIsReady] = useState(false);
  const [initialState, setInitialState] = useState();

  useEffect(() => {
    const restoreState = async () => {
      try {
        const savedStateString = await AsyncStorage.getItem(PERSISTENCE_KEY);
        if (!savedStateString) {
          throw new Error();
        }
        const state = JSON.parse(savedStateString);

        setInitialState(state);
        setIsReady(true);
      } catch {
        Promise.race([
          getInitialState(),
          new Promise(resolve =>
            // Timeout in 150ms if `getInitialState` doesn't resolve
            // Workaround for https://github.com/facebook/react-native/issues/25675
            setTimeout(resolve, 150),
          ),
        ])
          .catch(e => {
            console.error(e);
          })
          .then(state => {
            if (state !== undefined) {
              setInitialState(state);
            }

            setIsReady(true);
          });
      }
    };

    if (!isReady) {
      restoreState();
    }
  }, [getInitialState, isReady]);

  return {
    isReady,
    initialState,
  };
}
`
If i comment this line const savedStateString = await AsyncStorage.getItem(PERSISTENCE_KEY);
 return work but i deactivate the state persist

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| Android                | 29 
| @react-navigation/native       | 5.0.3
| react-native                   | 0.61.5
| node                           | 12.16.0
| npm                     | 6.13.4
| yarn                     | 1.22.0

**Comment by tastafur** [comment]
Hello!

I just resolve how to make the state persist work together with deep linking.

`
export function useStateNavigator() {
  const ref = useRef();

  const {getInitialState} = useLinking(ref, {
    prefixes: ['dgp-apps://'],
    config,
  });

  const [isReady, setIsReady] = useState(false);
  const [initialState, setInitialState] = useState();

  useEffect(() => {
    const restoreState = async () => {
      try {
        const savedStateString = await AsyncStorage.getItem(PERSISTENCE_KEY);
        const state = JSON.parse(savedStateString);

        setInitialState(state);
      } finally {
        setIsReady(true);
      }
    };

    Promise.race([
      getInitialState(),
      new Promise(resolve =>
        // Timeout in 150ms if `getInitialState` doesn't resolve
        // Workaround for https://github.com/facebook/react-native/issues/25675
        setTimeout(resolve, 150),
      ),
    ])
      .catch(e => {
        console.error(e);
      })
      .then(state => {
        if (state !== undefined) {
          setInitialState(state);
          setIsReady(true);
        } else {
          restoreState();
        }
      });
  }, [getInitialState, isReady]);

  return {
    isReady,
    initialState,
  };
}
`

In case it helps someone

**Comment by ibnukipa** [comment]
Hi @tastafur , seems I have the same problem with you but we have different implementation on restoring the state. do you mind if you tell about where and how do you put the useStateNavigator function on your navigator?
