### ISSUE TITLE
Navigating to a nested stack within a tab causes `navigation.goBack()` to go back to the wrong screen

### ISSUE THREAD

**Issue by drager** [react-navigation/react-navigation#7832]
**Current Behavior**

Navigating to a nested stack within a tab causes `navigation.goBack()` to go back to the wrong screen.

**Expected Behavior**

I expect it to go back to the "Settings" screen. (See Snack below).

**How to reproduce**

See Snack: https://snack.expo.io/S1c_rCeLI

Click on the "To details" in the top. You will see that it navigates to the "Settings" "Details". This is correct, however when I press "Back" it navigates back to the "Home" screen and then if you click on "Settings" it's in the "Details" state. It shouldn't be in this state. You can press "Back" several times and the state of the "Settings" screen will always be the same. This is weird behavior...

However, if you start by navigating to "Settings" and then back to "Home" and then click on "To Details" at the top it works as expected. So it seems that it must first be mounted in order to work correctly?

**Comment by satya164** [comment]
This is expected behavior. If you've never navigate to "Settings", then it's not in the back stack.

**Comment by drager** [comment]
@satya164 Okey, so how would you make it work like this? I.e adding it to the back stack?

**Comment by drager** [comment]
If I recall this wasn't the same behavior in version 4. Is this because of this? https://reactnavigation.org/docs/upgrading-from-4.x#navigating-to-nested-screens

**Comment by satya164** [comment]
It was not the behaviour in v4 but a lot of complained about that behaviour.

> so how would you make it work like this? I.e adding it to the back stack?

Navigate to the screen first if you want it in the history.

**Comment by drager** [comment]
> It was not the behaviour in v4 but a lot of people complained about that behaviour.
> 
> > so how would you make it work like this? I.e adding it to the back stack?
> 
> Navigate to the screen first if you want it in the history.

Yeah, that's what I ended up doing. Thanks!
