### ISSUE TITLE
Safe area paddings are not taken into account when use a customer header height

### ISSUE THREAD

**Issue by pybuche** [react-navigation/react-navigation#7833]
**Current Behavior**

- What code are you running and what is happening?
Hi, I noticed that when you are precising `height` in `headerStyle` options, safe area paddings for devices with a notch are not taken into account.
That's a shame because if forces me to add manually the safe insets and it's not that convenient.

- Include a screenshot or video if it makes sense.
*With default height*:
```typescript
const AccountStackNavigator = () => {
    return (
        <AccountStack.Navigator>
            <AccountStack.Screen
                name="Profile"
                component={Profile}
                options={{ title: 'Profile' }}
            />
        </AccountStack.Navigator>
    );
};
```
![image](https://user-images.githubusercontent.com/7555711/77065251-3cfd1b00-69e1-11ea-9baa-21b5f2e44d23.png)

*With custom height*:
```typescript
const AccountStackNavigator = () => {
    return (
        <AccountStack.Navigator>
            <AccountStack.Screen
                name="Profile"
                component={Profile}
                options={{ title: 'Profile', headerStyle: { height: 64 } }}
            />
        </AccountStack.Navigator>
    );
};
```
![image](https://user-images.githubusercontent.com/7555711/77065409-89e0f180-69e1-11ea-8c99-7ff6590e303b.png)
The header is smaller than the standard one, although the standard header is 44px high...

*With custom height and insets*:
```typescript
const AccountStackNavigator = () => {
    return (
        <AccountStack.Navigator>
            <AccountStack.Screen
                name="Profile"
                component={Profile}
                options={{ title: 'Profile', headerStyle: { height: 64 + insets.top } }}
            />
        </AccountStack.Navigator>
    );
};
```
![image](https://user-images.githubusercontent.com/7555711/77065443-9b29fe00-69e1-11ea-9191-169037b52a69.png)

**Expected Behavior**

- What do you expect should be happening?
I understand why insets are not taken into account, since you override the default param. But I'd like at least to be able to set a custom height and not having to deal with the safe areas. 
Would it be possible?

- Include a screenshot or video if it makes sense.
I'd like have this result:
![image](https://user-images.githubusercontent.com/7555711/77065443-9b29fe00-69e1-11ea-9191-169037b52a69.png)
with this piece of code:
```typescript
const AccountStackNavigator = () => {
    return (
        <AccountStack.Navigator>
            <AccountStack.Screen
                name="Profile"
                component={Profile}
                options={{ title: 'Profile', headerStyle: { height: 64 } }}
            />
        </AccountStack.Navigator>
    );
};
```

**How to reproduce**

You should be able to reproduce everything with the code snippets above. 
Thanks !

- You must provide a way to reproduce the problem. If you are having an issue with your machine or build tools, the issue belongs on another repository as that is outside of the scope of React Navigation.
- Either re-create the bug on [Snack](https://snack.expo.io) or link to a GitHub repository with code that reproduces the bug.
- Explain how to run the example app and any steps that we need to take to reproduce the issue from the example app.
- Keep the repro code as simple as possible, with the minimum amount of code required to repro the issue.
- Before reporting an issue, make sure you are on latest version of the package.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |  iOS 12+
| @react-navigation/native       |  5.0.10
| @react-navigation/stack        | 5.2.0
| react-native-gesture-handler   | 1.5.0 (do I need it with the RN nav v5?)
| react-native-safe-area-context | 0.6.0
| react-native-screens           | 2.0.0-alpha.12 (do I need it with the RN nav v5?)
| react-native                   | I guess it's expo 36's v0.60
| expo                           | 36.0.0
| node                           | 12
| npm or yarn                    | 1.19.1

**Comment by WoLewicki** [comment]
> I understand why insets are not taken into account, since you override the default param. But I'd like at least to be able to set a custom height and not having to deal with the safe areas.
Would it be possible?

It is understandable that overriding the header's height will not take safe area insets into account by default, because it would destroy the customizability.  The best way I can think of is to just always add the top inset plus the value you would like to be changed, it would look somehow like this: `headerStyle: { height: useSafeArea().top + yourValue }`.

**Comment by pybuche** [comment]
That's what I did, I just wanted to know if there is another way, since it's now pretty standard to take safe areas into account !

**Comment by WoLewicki** [comment]
Do you have anything specific in mind? I can't think of any other sensible solution.

**Comment by pybuche** [comment]
Well, if `react-navigation` already has the safe insets values, maybe just a param like `headerHeight` instead of `headerStyle.height` would do the trick. 

It's already done for other params that could be handled with style, why not this one ? 
Moreover, it's recommanded to set `headerStyle.height` when using a custom header component with a non-standard height according to the docs, so there may be some thoughts to give to this height problem :)

**Comment by maersk96** [comment]
> **Current Behavior**
> 
> * What code are you running and what is happening?
>   Hi, I noticed that when you are precising `height` in `headerStyle` options, safe area paddings for devices with a notch are not taken into account.
>   That's a shame because if forces me to add manually the safe insets and it's not that convenient.
> * Include a screenshot or video if it makes sense.
>   _With default height_:
> 
> ```ts
> const AccountStackNavigator = () => {
>     return (
>         <AccountStack.Navigator>
>             <AccountStack.Screen
>                 name="Profile"
>                 component={Profile}
>                 options={{ title: 'Profile' }}
>             />
>         </AccountStack.Navigator>
>     );
> };
> ```
> 
> ![image](https://user-images.githubusercontent.com/7555711/77065251-3cfd1b00-69e1-11ea-9baa-21b5f2e44d23.png)
> 
> _With custom height_:
> 
> ```ts
> const AccountStackNavigator = () => {
>     return (
>         <AccountStack.Navigator>
>             <AccountStack.Screen
>                 name="Profile"
>                 component={Profile}
>                 options={{ title: 'Profile', headerStyle: { height: 64 } }}
>             />
>         </AccountStack.Navigator>
>     );
> };
> ```
> 
> ![image](https://user-images.githubusercontent.com/7555711/77065409-89e0f180-69e1-11ea-8c99-7ff6590e303b.png) The header is smaller than the standard one, although the standard header is 44px high...
> 
> _With custom height and insets_:
> 
> ```ts
> const AccountStackNavigator = () => {
>     return (
>         <AccountStack.Navigator>
>             <AccountStack.Screen
>                 name="Profile"
>                 component={Profile}
>                 options={{ title: 'Profile', headerStyle: { height: 64 + insets.top } }}
>             />
>         </AccountStack.Navigator>
>     );
> };
> ```
> 
> ![image](https://user-images.githubusercontent.com/7555711/77065443-9b29fe00-69e1-11ea-9191-169037b52a69.png)
> 
> **Expected Behavior**
> 
> * What do you expect should be happening?
>   I understand why insets are not taken into account, since you override the default param. But I'd like at least to be able to set a custom height and not having to deal with the safe areas.
>   Would it be possible?
> * Include a screenshot or video if it makes sense.
>   I'd like have this result:
>   ![image](https://user-images.githubusercontent.com/7555711/77065443-9b29fe00-69e1-11ea-9191-169037b52a69.png)
>   with this piece of code:
> 
> ```ts
> const AccountStackNavigator = () => {
>     return (
>         <AccountStack.Navigator>
>             <AccountStack.Screen
>                 name="Profile"
>                 component={Profile}
>                 options={{ title: 'Profile', headerStyle: { height: 64 } }}
>             />
>         </AccountStack.Navigator>
>     );
> };
> ```
> 
> **How to reproduce**
> 
> You should be able to reproduce everything with the code snippets above. Thanks !
> 
> * You must provide a way to reproduce the problem. If you are having an issue with your machine or build tools, the issue belongs on another repository as that is outside of the scope of React Navigation.
> * Either re-create the bug on [Snack](https://snack.expo.io) or link to a GitHub repository with code that reproduces the bug.
> * Explain how to run the example app and any steps that we need to take to reproduce the issue from the example app.
> * Keep the repro code as simple as possible, with the minimum amount of code required to repro the issue.
> * Before reporting an issue, make sure you are on latest version of the package.
> 
> **Your Environment**
> 
> software	version
> iOS or Android	iOS 12+
> @react-navigation/native	5.0.10
> @react-navigation/stack	5.2.0
> react-native-gesture-handler	1.5.0 (do I need it with the RN nav v5?)
> react-native-safe-area-context	0.6.0
> react-native-screens	2.0.0-alpha.12 (do I need it with the RN nav v5?)
> react-native	I guess it's expo 36's v0.60
> expo	36.0.0
> node	12
> npm or yarn	1.19.1

Just wondering. What font is this?
