### ISSUE TITLE
Update from v4 to v5

### ISSUE THREAD

**Issue by wojtekhorembala** [react-navigation/react-navigation#7835]
Hello,

I working at update my navigation from v4 to v5.
I reading this docs https://reactnavigation.org/docs/compatibility/ and i have this code now

```
import { createStackNavigator } from '@react-navigation/stack';
import { createCompatNavigatorFactory, createSwitchNavigator } from '@react-navigation/compat';
import { NavigationActions } from '@react-navigation/compat';
import { NavigationContainer } from '@react-navigation/native';
import { createBottomTabNavigator } from 'react-navigation-tabs';
```

My stacks navigators
```
const AsynchronousLogin = () => {
    return createCompatNavigatorFactory(createStackNavigator)({
            LoginAsync: { screen: AsyncLogin },
        },
    );
}

const NavForNotLogin = () => {
    return createCompatNavigatorFactory(createStackNavigator)({
        Login: { screen: Login },
    });
}

const NavForLogin = () => {
    return createCompatNavigatorFactory(createStackNavigator)({
        Home: { screen: Home },
    });
}

const TabForLogin = createBottomTabNavigator({
    Home: { screen: NavForLogin() },
}, {
    tabBarComponent: ({ navigation }) => { ... }, 
});
```

And now i want create switch navigator in old version i have this

v4 code ->
```

const switchNavigator = (ForNotLogin, AsyncLogin) => {
    return createSwitchNavigator({
        AsyncLogin,
        ForNotLogin,
        ForLogin: { screen: TabForLogin },
    }, {
        initialRouteName: 'AsyncLogin',
    });
};

export const AppNavigator = () => {
    const swichNavigator = switchNavigator(
        NavForNotLogin(),
        AsynchronousLogin(),
    );
    return createAppContainer(swichNavigator);
};
```

My approach v5 version - this is broken bcs i dont know how i can do this correct ->
```
export const AppNavigator = () => {
    const switchNav = createSwitchNavigator({
        AsynchronousLogin: { screen: AsynchronousLogin() },
        NavForNotLogin: { screen: NavForNotLogin() },
        NavForLogin: { screen: TabForLogin },
    }, {
        initialRouteName: 'AsyncLogin',
    });
    return (
        <NavigationContainer 
            ref={ ref => setTopLevelNavigator(ref) }
        >
        ....
        </NavigationContainer>
    );
};
```

**Comment by xgenem** [comment]
Hey man, any solution on this? I'm used to createSwitchNavigator as well.

**Comment by nuflowx** [comment]
I've been struggling with this as well :/

I was able to replace most navigation with the updated API from v5, but in the last instance I couldn't find a way around NOT having to use createSwitchNavigator using `@react-navigation/compat`.

This works:
```
import { createSwitchNavigator } from 'react-navigation'; // @react-navigation/core 4.x works [3.7.1]

import MainNavigator from './MainNavigator';

const switchNavigator = createSwitchNavigator(
  {
    Main: {
      screen: MainNavigator,
    },
  },
  {
    initialRouteName: 'Main',
  }
);
switchNavigator.path = '';

export default createBrowserApp(switchNavigator, { history: 'hash' });
```

Importing from `@react-navigation/compat` it breaks:
```
// import { createSwitchNavigator } from '@react-navigation/compat'; // breaks/does not work
```
> TypeError: Cannot read property 'getActionForPathAndParams' of undefined
> createBrowserApp

Wouldn't be surprised if it's the combination of the two not playing ball. (`createBrowserApp` with `createSwitchNavigator` from `compat`).

Either way, v5 doesn't have any documentation for browser builds, so for now I'll just end up using the `createSwitchNavigator` from 4.x-core to get round this and be able to use `createBrowserApp` with it. If there's a better way I'd be happy to hear about it ;)

**Comment by nuflowx** [comment]
@xgenem I found this answer somewhat helpful:
https://stackoverflow.com/questions/60402632/switchnavigator-with-react-navigation-5

And a useful resource from the documentation how the removed `createSwitchNavigator` and that you're supposed to make your own `Stacks` directly:
https://reactnavigation.org/docs/upgrading-from-4.x/
