### ISSUE TITLE
Adding / updating peer dependencies should be a semver breaking change

### ISSUE THREAD

**Issue by plaa** [react-navigation/react-navigation#7840]
**Current Behavior**

When I upgraded react-navigation-tabs from 2.7.0 to 2.8.5 and react-navigation-stack from 2.0.15 to 2.3.2, both added a peer dependency for react-native-screens.  This caused the app to crash immediately on startup with `Unable to resolve module 'react-native-screens'`.

**Expected Behavior**

According to semver, minor and patch updates should not break your application.  Thus if you add a new peer dependency or upgrade the required version of a peer dependency, this should be considered a breaking change and increase the major version of the library.

In practical terms, people should be able to use `"react-navigation-tabs": "^2.7.0"` and run `npm update` without fear of their application breaking.

This is also the [consensus with the maintainers of semver](https://github.com/semver/semver/issues/502).

There is nothing that needs / can be done for existing versions, but please bear this in mind when releasing future versions.

Thanks for your hard work on react-navigation!

**Comment by satya164** [comment]
They always had peer dep on `react-native-screens`.
