### ISSUE TITLE
react navigation ios on swipe to left not dismiss the screen

### ISSUE THREAD

**Issue by EhsanSarshar** [react-navigation/react-navigation#7841]
I just updated react-navigation-stack, react-navigation-tabs and react-native-screens to it's latest version. but as I notice the swipe left not dismiss the screen on ios. when I swipe it to left it should pop the current screen. but it just swipe and when I hold it off it just turn back to its location and nothing happen.

"react-navigation": "^4.0.10",
 "react-navigation-stack": "^2.3.1",
 "react-navigation-tabs": "^2.8.5",
"react-native-screens": "^2.3.0"
"react-native":"0.61.5"

![swipe-problem](https://user-images.githubusercontent.com/46188784/77151518-b9602e80-6ab3-11ea-876f-bb11c7f3aaec.gif)

**Comment by EhsanSarshar** [comment]
here is the createStackNavigator configs

   ```
 mode: "card",
    defaultNavigationOptions: {
        headerTintColor: color_primary,
        headerBackTitle: 'برگشت',
        cardStyle: { backgroundColor: "#fff" },
        headerTitle: '',
        ...TransitionPresets.SlideFromRightIOS,
    },
    headerMode: "screen"
```

**Comment by satya164** [comment]
can you test the latest version? 2.3.4

**Comment by EhsanSarshar** [comment]
@satya164 I update all of them to latest version but still not working.
"react-navigation-stack": "^2.3.4",
"react-navigation-tabs": "^2.8.6",
"react-native-screens": "^2.4.0",
