### ISSUE TITLE
Navigation does not navigate anything

### ISSUE THREAD

**Issue by ekofi** [react-navigation/react-navigation#7842]
**Current Behavior**
Navigation is not working. 
```
import React from "react";
import { StyleSheet, View, Alert } from "react-native";

import { NavigationContainer } from "@react-navigation/native";
import { createStackNavigator } from "@react-navigation/stack";

const Stack = createStackNavigator();

export default function App() {
  function HomeScreen() {
    return (
      <View style={{ flex: 1, alignItems: "center", justifyContent: "center" }}>
        <Text>Home Screen</Text>
      </View>
    );
  }

  function DetailsScreen() {
    return (
      <View style={{ flex: 1, alignItems: "center", justifyContent: "center" }}>
        <Text>Details Screen</Text>
      </View>
    );
  }

  return (
    <View style={styles.container}>
      <NavigationContainer>
        <Stack.Navigator initialRouteName="Home">
          <Stack.Screen name="Home" component={HomeScreen} />
          <Stack.Screen name="Details" component={DetailsScreen} />
        </Stack.Navigator>
      </NavigationContainer>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 25
  },
});
```

**Expected Behavior**

No text appears on the screen. "Home Screen" or "Details Screen"

**How to reproduce**
https://snack.expo.io/@zicxor/mature-coffee
You can run it with blank expo app.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Expo client
| @react-navigation/native       | ^5.1.0
| @react-navigation/stack        | ^5.2.1
| react-native-gesture-handler   | ~1.5.0
| react-native-safe-area-context | 0.6.0
| react-native-screens           | 2.0.0-alpha.12
| react-native                   | 0.61.4
| expo                           | ~36.0.0
| node                           | 10.15.3
| npm or yarn                    | 6.14.2

**Comment by satya164** [comment]
Remove `alignItems: "center"` and `justifyContent: "center"`

**Comment by androidIsForVivek** [comment]
i am facing this issue.
