### ISSUE TITLE
isFocused broken when dynamically adding items to navigator

### ISSUE THREAD

**Issue by thabemmz** [react-navigation/react-navigation#7843]
## Current Behavior
This issue probably has the same underlying issue as https://github.com/react-navigation/react-navigation/issues/6738, but I create a different ticket for it in order for people to find it more easily.

In my app, I use a nested Stack navigator as 3rd item inside a Drawer navigator with 3 items. The second item of the Drawer navigator is added conditionally, based on an (async) API call. Navigating from the Drawer navigator to the first screen works fine and as expected. From the Drawer navigator to the conditional, second, screen also works fine. However, when navigating inside the Stack navigator of the 3rd screen, the back button in that stack navigator does not work.

## Probable cause
After some digging in the code, I found out that the back button does not work because `isFocused()` is always `false` for this screen, due to the following check inside `isFocused`:

```
            if (index !== state.index) {
              return false;
            }
```

Due to some routes in my drawer navigator being dynamically added, the indices of routes don't match with the initial generated state anymore, making `isFocused()` always returning `false`.

## Probable solution
The solution would probably be to refresh the `state` of the `navigator` when routes are being added or removed to or from the navigator.

## How to reproduce
This is a simplified example:

```
export const RootNavigator = () => {
  const navigationRef = useRef()
  const [permissions, setPermissions] = useState([])
  useEffect(() => {
    checkPermissions().then(permissions => {
      if (permissions) setPermissions(permissions)
    })
  }, [checkPermissions])

  return (
    <NavigationContainer ref={navigationRef}>
      <Drawer.Navigator
        initialRouteName="home"
      >
        <Drawer.Screen
          name="home"
          component={Home}
        />
        {permissions.includes('authorized') && (
          <Drawer.Screen
            name="authorized"
            component={AuthorizedScreen}
          />
        )
        <Drawer.Screen
          name="help"
          component={() => (
            <Stack.Navigator initialRouteName="help-screen1">
              <Stack.Screen name="help-screen1" component={HelpScreen1} />
              <Stack.Screen name="help-screen2" component={HelpScreen2} />
            </Stack.Navigator>
          )}
        />
      </Drawer.Navigator>
    </NavigationContainer>
  )
}
```

The drawer shows the "Authorized" option when you have permissions to see it. When you click the help item, you automatically navigate to the initial route of the stackNavigator in it (`help-screen1`), but when you click through to `help-screen2`, the back button does not work anymore due to the issue described.

## Workaround
In order to make this work properly, I adjusted the `useEffect` hook above and added a `navReady` state:

```
export const RootNavigator = () => {
  const navigationRef = useRef()
  const [permissions, setPermissions] = useState([])
  const [navReady, setNavReady] = useState(false)
  useEffect(() => {
    checkPermissions().then(permissions => {
      setNavReady(true)
      if (permissions) setPermissions(permissions)
    })

    return () => setNavReady(false)
  }, [checkPermissions])

  if (!navReady) return null

  return (
    <NavigationContainer ref={navigationRef}>
      <Drawer.Navigator
        initialRouteName="home"
      >
        <Drawer.Screen
          name="home"
          component={Home}
        />
        {permissions.includes('authorized') && (
          <Drawer.Screen
            name="authorized"
            component={AuthorizedScreen}
          />
        )
        <Drawer.Screen
          name="help"
          component={() => (
            <Stack.Navigator initialRouteName="help-screen1">
              <Stack.Screen name="help-screen1" component={HelpScreen1} />
              <Stack.Screen name="help-screen2" component={HelpScreen2} />
            </Stack.Navigator>
          )}
        />
      </Drawer.Navigator>
    </NavigationContainer>
  )
}
```

(Be aware of the use of the `return` function inside the `useEffect`, in my case this was necessary to make absolutely sure the `Drawer.Navigator` items are not adjusted dynamically, but there was a render of `null` in between to make the `NavigationContainer` / `Drawer.Navigator` unmount from the "DOM").

## Expected behavior
You should be able to dynamically add or remove pages from the navigator without having to do manual bookkeeping on your side. Either with a React hook, or some kind of `refresh` action on the navigation object.

## Your Environment
React 16.9.0
React Native 0.61.5
@react-navigation/drawer: 5.1.1,
@react-navigation/native: 5.0.9,
@react-navigation/stack: 5.1.1

**Comment by thabemmz** [comment]
Will look into that this weekend.

**Comment by satya164** [comment]
Also don't pass component like that inline. Component should be created outside render, not during render.

**Comment by thabemmz** [comment]
I know, I know, this was just for the sake of creating an example...

**Comment by thabemmz** [comment]
@satya164 it turned out to be good that I created an example repository for this, because I over-simplified my example in the issue above. I updated the issue with the correct description of the problem.

You can find the example repository with the root cause of the issue here: https://github.com/thabemmz/reactNavigationIsFocusedIssueExample.

Hope the issue is clear for you, if I can help you in any way, please let me know!

**Comment by RWOverdijk** [comment]
@satya164 I had this issue and can confirm that this fix fixes it (thanks for that) but could it be it broke something else?

- First, I could swipe to dismiss after a reset and it worked fine, but the back button in the nav bar didn't work.
- After your fix, the button in the nav bar works but swipe to dismiss no longer works. (It does fade, but then pops back up).

I could create a new issue for this if you prefer, but I feel like this is somehow related.

**Comment by satya164** [comment]
@RWOverdijk can you try updating to the latest version of @react-navigation/stack  regarding the swipe issue?

**Comment by thabemmz** [comment]
Wow, thanks for the quick reply and action @satya164. Much appreciated 👏
