### ISSUE TITLE
Transparent Background overlaps previous screen

### ISSUE THREAD

**Issue by niallel** [react-navigation/react-navigation#7844]
**Current Behavior**

I want to use a background image outside the navigation, so that it doesn't change when I move between screens.
When I navigate from one screen to another using the background set to transparent, half of the previous screen is shown.
Any ideas on what I'm doing wrong.

`  <Background>
      <NavigationContainer>
          <Stack.Navigator initialRouteName="ScreenA" 
              screenOptions={{
                cardStyle: {backgroundColor: 'transparent'},
              }}>
              <Stack.Screen name="ScreenA" component={ScreenA} />
              <Stack.Screen name="ScreenB" component={ScreenB} />
          </Stack.Navigator>
      </NavigationContainer>
  </Background>`

ScreenA
<img width="416" alt="image" src="https://user-images.githubusercontent.com/6152664/77165748-d3494380-6aaa-11ea-8142-1194dc5ac605.png">

ScreenB
<img width="420" alt="image" src="https://user-images.githubusercontent.com/6152664/77165769-df350580-6aaa-11ea-9640-4f61b4d74d26.png">

**Comment by satya164** [comment]
You need to change the animation https://reactnavigation.org/docs/stack-navigator#transparent-modals

**Comment by niallel** [comment]
Thanks, any pointers to the animation I should change would be appreciated.

The link you sent seems to indicate if you want the behaviour I've seen. I want the previous card to disappear completely.

**Comment by satya164** [comment]
@niallel it's upto you how to make previous card disappear completely. animate its opacity to `0`, translate it completely offscreen etc., depending on how you want the animation to look.

**Comment by niallel** [comment]
Thanks for that. I've been trying with no success, but likely I need to spend some time learning.

**Comment by timvanwolfswinkel** [comment]
@niallel maybe something like this will help you?

```
const TransitionScreen = {
    gestureDirection: 'horizontal',
    transitionSpec: {
        open: TransitionSpecs.TransitionIOSSpec,
        close: TransitionSpecs.TransitionIOSSpec
    },
    cardStyleInterpolator: ({ current, next, layouts }) => {
        return {
            cardStyle: {
                transform: [
                    {
                        translateX: current.progress.interpolate({
                            inputRange: [0, 1],
                            outputRange: [layouts.screen.width, 0]
                        })
                    },
                    {
                        translateX: next
                            ? next.progress.interpolate({
                                  inputRange: [0, 1],
                                  outputRange: [0, -layouts.screen.width]
                              })
                            : 1
                    }
                ]
            },
            overlayStyle: {
                opacity: current.progress.interpolate({
                    inputRange: [0, 1],
                    outputRange: [0, 0.5]
                })
            }
        };
    }
};

const CardOptions = {
    cardStyle: { backgroundColor: 'transparent' },
    ...TransitionScreen
};
```
Then I use it like this:

```
const Screens = () => {
    return (
        <MainStack.Navigator screenOptions={ScreenOptionsWithHeader}>
            <MainStack.Screen name="Home" component={Home} options={CardOptions} />
            <MainStack.Screen name="CreateProject" component={CreateProject} />
            <MainStack.Screen name="MyGallery" component={MyGallery} options={CardOptions} />
        </MainStack.Navigator>
    );
};
```

**Comment by niallel** [comment]
@timvanwolfswinkel 

Thats brilliant, worked perfectly. Thanks so much.

**Comment by 787941287** [comment]
> @timvanwolfswinkel
> 
> Thats brilliant, worked perfectly. Thanks so much.

Can you tell me How did you solve the problem in the end ?

**Comment by niallel** [comment]
> > @timvanwolfswinkel
> > Thats brilliant, worked perfectly. Thanks so much.
> 
> Can you tell me How did you solve the problem in the end ?

I just followed [https://github.com/react-navigation/react-navigation/issues/7844#issuecomment-603184937]

**Comment by davoam** [comment]
If you don't have necessary properties, make sure you use `createStackNavigator` instead `createNativeStackNavigator`. 
Thanks, @wolfie90 for the animation!

**Comment by coreybyrum7** [comment]
> 

anyone get this working in TS?

**Comment by coreybyrum7** [comment]
> @niallel maybe something like this will help you?
> 
> ```
> const TransitionScreen = {
>     gestureDirection: 'horizontal',
>     transitionSpec: {
>         open: TransitionSpecs.TransitionIOSSpec,
>         close: TransitionSpecs.TransitionIOSSpec
>     },
>     cardStyleInterpolator: ({ current, next, layouts }) => {
>         return {
>             cardStyle: {
>                 transform: [
>                     {
>                         translateX: current.progress.interpolate({
>                             inputRange: [0, 1],
>                             outputRange: [layouts.screen.width, 0]
>                         })
>                     },
>                     {
>                         translateX: next
>                             ? next.progress.interpolate({
>                                   inputRange: [0, 1],
>                                   outputRange: [0, -layouts.screen.width]
>                               })
>                             : 1
>                     }
>                 ]
>             },
>             overlayStyle: {
>                 opacity: current.progress.interpolate({
>                     inputRange: [0, 1],
>                     outputRange: [0, 0.5]
>                 })
>             }
>         };
>     }
> };
> 
> const CardOptions = {
>     cardStyle: { backgroundColor: 'transparent' },
>     ...TransitionScreen
> };
> ```
> 
> Then I use it like this:
> 
> ```
> const Screens = () => {
>     return (
>         <MainStack.Navigator screenOptions={ScreenOptionsWithHeader}>
>             <MainStack.Screen name="Home" component={Home} options={CardOptions} />
>             <MainStack.Screen name="CreateProject" component={CreateProject} />
>             <MainStack.Screen name="MyGallery" component={MyGallery} options={CardOptions} />
>         </MainStack.Navigator>
>     );
> };
> ```

anyone get this working in TS?
