### ISSUE TITLE
Snack Demos don't work at all

### ISSUE THREAD

**Issue by micnguyen** [react-navigation/react-navigation#7845]
**Current Behavior**
Running a simple Snack example either on local device, or on Appetize (iOS + Android), it hast his error:

<img width="325" alt="Screen Shot 2020-03-21 at 2 14 59 pm" src="https://user-images.githubusercontent.com/919166/77218358-a4040680-6b7e-11ea-83fb-a5218618e2b3.png">

This does not happen when selecting "Web"

**Expected Behavior**

It should work

**How to reproduce**

Go to this Snack and try running iOS 

https://snack.expo.io/?platform=android&name=Getting%20started%20%7C%20React%20Navigation&dependencies=%40react-native-community%2Fmasked-view%40%5E0.1.1%2C%40react-navigation%2Fnative%40%5E5.0.5%2C%40react-navigation%2Fbottom-tabs%40%5E5.0.5%2C%40react-navigation%2Fdrawer%40%5E5.0.5%2C%40react-navigation%2Fmaterial-bottom-tabs%40%5E5.0.5%2C%40react-navigation%2Fmaterial-top-tabs%40%5E5.0.5%2C%40react-navigation%2Fstack%40%5E5.0.5%2Creact-native-gesture-handler%401.5.2%2Creact-native-reanimated%401.4.0%2Creact-native-safe-area-context%400.6.0%2Creact-native-screens%402.0.0-alpha.12&sourceUrl=https%3A%2F%2Freactnavigation.org%2Fexamples%2F5.x%2Fhello-react-navigation.js

**Comment by qwe123wsx** [comment]
Same bug here, Any snacks on https://reactnavigation.org/ didn't work.

**Comment by duongkhoangiam** [comment]
Same problem here . but work in local emulator, does not working in build and or on Appetize (iOS + Android)

**Comment by soullivaneuh** [comment]
Some works, some doesn't.

Here is another buggy Snack: https://snack.expo.io/?platform=android&name=Header%20buttons%20%7C%20React%20Navigation&dependencies=%40react-native-community%2Fmasked-view%40%5E0.1.1%2C%40react-navigation%2Fnative%40%5E5.0.5%2C%40react-navigation%2Fbottom-tabs%40%5E5.0.5%2C%40react-navigation%2Fdrawer%40%5E5.0.5%2C%40react-navigation%2Fmaterial-bottom-tabs%40%5E5.0.5%2C%40react-navigation%2Fmaterial-top-tabs%40%5E5.0.5%2C%40react-navigation%2Fstack%40%5E5.0.5%2Creact-native-gesture-handler%401.5.2%2Creact-native-reanimated%401.4.0%2Creact-native-safe-area-context%400.6.0%2Creact-native-screens%402.0.0-alpha.12&sourceUrl=https%3A%2F%2Freactnavigation.org%2Fexamples%2F5.x%2Fnest-navigators.js

Come from: https://reactnavigation.org/docs/nesting-navigators#navigating-to-a-screen-in-a-nested-navigator

**Comment by satya164** [comment]
Closing since snacks should work fine now.

**Comment by micnguyen** [comment]
This is still problematic @satya164.
See: https://snack.expo.io/?platform=android&name=Header%20buttons%20%7C%20React%20Navigation&dependencies=%40react-native-community%2Fmasked-view%40%5E0.1.1%2C%40react-navigation%2Fnative%40%5E5.0.5%2C%40react-navigation%2Fbottom-tabs%40%5E5.0.5%2C%40react-navigation%2Fdrawer%40%5E5.0.5%2C%40react-navigation%2Fmaterial-bottom-tabs%40%5E5.0.5%2C%40react-navigation%2Fmaterial-top-tabs%40%5E5.0.5%2C%40react-navigation%2Fstack%40%5E5.0.5%2Creact-native-gesture-handler%401.5.2%2Creact-native-reanimated%401.4.0%2Creact-native-safe-area-context%400.6.0%2Creact-native-screens%402.0.0-alpha.12&sourceUrl=https%3A%2F%2Freactnavigation.org%2Fexamples%2F5.x%2Fnest-navigators.js


<img width="326" alt="Screen Shot 2020-05-11 at 1 27 14 pm" src="https://user-images.githubusercontent.com/919166/81521664-38beff80-938b-11ea-9d83-ddd69e51cd65.png">

**Comment by raajnadar** [comment]
Add `"fbjs": "latest"` or `"fbjs": "1.0.0"` in the package.json
