### ISSUE TITLE
when gestureEnabled in android back() not working

### ISSUE THREAD

**Issue by mynameisguy** [react-navigation/react-navigation#7848]
**Current Behavior**

running:
`_navigator.dispatch(NavigationActions.back({key: null}));`
works perfectly in iOS and android.

Once I added:
```
        defaultNavigationOptions: {
            gestureEnabled: true,
        },
```
to `createStackNavigator` or:
```
navigationOptions: {
                gestureEnabled: true
            }
```

to the specific screen it stopped working.
tried to add the key didn't help. it continues to work well on iOS

the stack navigator is nested (inside and outside)

**Expected Behavior**
Expect it to continue to work

**How to reproduce**
add gestureEnabled: true

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | android
| @react-navigation/native       |3.6.5
| @react-navigation/stack        |
| react-native-gesture-handler   |^1.6.0
| react-native-safe-area-context |^0.7.3
| react-native-screens           |2.0.0-beta.6
| react-native                   |0.61.5
| expo                           |
| node                           |13.1.0
| npm or yarn                    | npm

**Comment by harisb2012** [comment]
Same issue

**Comment by harisb2012** [comment]
Getting error 'The action 'GO_BACK' was not handled by any navigator''

**Comment by saigyouyou** [comment]
same issue，on any page setted "gestureEnabled: true", navigation.goBack() will act very slow。

"react-native": "0.61.5",
"react-native-gesture-handler": "^1.6.0"
"react-navigation": "^4.3.1"
"react-navigation-stack": "^2.3.1"
"react-navigation-tabs": "^2.8.4"

**Comment by mynameisguy** [comment]
more details:
If I change go back to:
```
_navigator.dispatch(StackActions.pop({n:1}));
```
it works only when I click twice, even if I change n to 2 or 3.

**Comment by R-D-P** [comment]
Same issue
The action 'GO_BACK' was not handled by any navigator, works fine when I change gestureEnabled to false

`"@react-native-community/masked-view": "^0.1.7",
    "@react-navigation/drawer": "^5.1.1",
    "@react-navigation/native": "^5.0.9",
    "@react-navigation/stack": "^5.1.1",
"react": "16.9.0",
    "react-native": "0.61.5",`

**Comment by christianjuth** [comment]
This is what I was using. It worked until I updated Expo to SDK 37 about an hour ago

```
function goBack() {
    navigation.navigate('App');
    // THIS IS A HACK!!!!!!!
    // UPDATE RN NAVIGATION AND DELETE THIS
    if(Platform.OS === 'android') {
      setTimeout(() => {
        navigation.navigate('App');
      }, 100);
    }
  }
```

**Comment by sshapoval** [comment]
same issue

**Comment by margabit** [comment]
Same issue for me too.

**Comment by jefersonjuliani** [comment]
> This is what I was using. It worked until about an hour ago when I updated to Expo SDK 37
> 
> ```ts
> function goBack() {
>     navigation.navigate('App');
>     // THIS IS A HACK!!!!!!!
>     // UPDATE RN NAVIGATION AND DELETE THIS
>     if(Platform.OS === 'android') {
>       setTimeout(() => {
>         navigation.navigate('App');
>       }, 100);
>     }
>   }
> ```

works

**Comment by sshapoval** [comment]
> This is what I was using. It worked until about an hour ago when I updated to Expo SDK 37
> 
> ```ts
> function goBack() {
>     navigation.navigate('App');
>     // THIS IS A HACK!!!!!!!
>     // UPDATE RN NAVIGATION AND DELETE THIS
>     if(Platform.OS === 'android') {
>       setTimeout(() => {
>         navigation.navigate('App');
>       }, 100);
>     }
>   }
> ```

Yes, it works, but there is no transition animation.

**Comment by satya164** [comment]
Closing since you didn't provide a repro. If you have a minimal repro, feel free to open an issue.

**Comment by durdevic** [comment]
Hi @satya164, 

On expo it works, but if you put the same code on clean npx project and run it on device, it creates the same error. Here is the zip you can test it and a video with behaviour I get on my device

You can clone this one to test it
https://github.com/durdevic/navitest

Video: 
![navitest](https://user-images.githubusercontent.com/2753836/79642160-34446400-819c-11ea-987b-a3fe4c52d899.gif)

Expo with the case here: 
https://snack.expo.io/@ukiand1/react-navigation-5---android-goback()-bug
