### ISSUE TITLE
App crashes when using @react-navigation/drawer

### ISSUE THREAD

**Issue by duongkhoangiam** [react-navigation/react-navigation#7849]
**Current Behavior**
- Using Expo
- When running in my computer emulator both android and ios is good working but when expo build android or apk file app is crash, when i remove all @react-navigation/drawer in my project, expo build working. i do not know what happen.

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Expo apk build
| @react-navigation/native       | ^5.1.1
| @react-navigation/drawer       | 5.3.2
| react-native-reanimated        | 1.4.0
| react-native-gesture-handler   | 1.5.0
| react-native-safe-area-context | 0.6.0
| react-native-screens           | 2.0.0-alpha.12
| react-native                   | https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz
| expo                           | 36.0.0
| node                           | v12.16.1
| npm or yarn                    | npm 6.14.3

**Comment by duongkhoangiam** [comment]
Also i have add top of App.js 
```
import 'react-native-gesture-handler';
```

**Comment by eriveltonelias** [comment]
do you have a log/report of your crash?

**Comment by duongkhoangiam** [comment]
After i check , the problem not from drawer , problem is stack navigation. i am remove all stack it's working.

**Comment by satya164** [comment]
Closing due to no response.

**Comment by Holzmichel41** [comment]
I have the same issue, is anybody still working on this? 
The expo app crashes with no error message when calling `const Drawer = createDrawerNavigator();`.
When trying to run the app without the statement everything is working as expected without any error or crash.

**Comment by Holzmichel41** [comment]
> When trying to run the app without the statement everything is working as expected without any error or crash.

Solved: I've updated the expo SDK, so it automatically updated all modules to compatible versions and everything is working fine again.

**Comment by kasaiee** [comment]
I have the same issue with react native 0.67.3

**Comment by vikaskamboj321** [comment]
in my case application is closing without any errors in console.
check this video
[screen-capture.webm](https://user-images.githubusercontent.com/56072561/181915639-49844148-901e-4b48-927e-80f6b8071202.webm)
let me  know if anyone has a solution for this issue

**Comment by raajnadar** [comment]
Check the android log cat for the native app crash

**Comment by ggchicote** [comment]
Could someone find out what is going on? I have the same situation as vikaskamboj321

**Comment by RodolfoSilva** [comment]
I've the same issue!

**Comment by RodolfoSilva** [comment]
I've used the @raajnadar answer https://github.com/react-navigation/react-navigation/issues/10836#issuecomment-1246523415 . This now working for me.

```bash
$ npm run android -- -c
```
