### ISSUE TITLE
Hi, How to. get tab bottom height?

### ISSUE THREAD

**Issue by XOneto9** [react-navigation/react-navigation#7850]
Hi, I want to know how to get Height?

I was using `useHeaderHeight` this hook function to get Navigation header Height
Like above function of hook, should I get tab bottom Height?

no matter using function which of Material-bottom-tab or Bottom-tab(common)
should I get it?

**Comment by sorinsinz** [comment]
Hi, @XOneto9 !

I don't think there is a hook for getting the bottom tab height. But if you check the code you can see that: 

`const DEFAULT_TABBAR_HEIGHT = 50;`

Another solution is to give the bottom tab your own style with your own height and save that const for reuse.

Have a nice day!

**Comment by XOneto9** [comment]
@sorinsinz 
Hi.
Thanks to reply.
hum...
how about iPhone X? is it also 50?
