### ISSUE TITLE
undefined is not an object (evaluating 'navigation.navigate')

### ISSUE THREAD

**Issue by erdoganmithat** [react-navigation/react-navigation#7851]
**Current Behavior**

- I am running:
```
import * as React from 'react';
import { Button, View, Text } from 'react-native';
import { NavigationContainer } from '@react-navigation/native';
import { createStackNavigator } from '@react-navigation/stack';

export default function App({ navigation }) {
  firebase.auth().onAuthStateChanged(user => {
    if (user != null) {
      {
        console.log("auth successful");
        navigation.navigate("HomeScreen");
      }
    }
  });


  const LoginScreen = props => (
    <View style={styles.container}>
      <Text h1>Coronova</Text>
    </View>
  );

  const HomeScreen = props => (
    <View style={styles.container}>
      <Text h1>Coronova</Text>
    </View>
  );

  return (
    <NavigationContainer>
      <Stack.Navigator initialRouteName="Login">
        <Stack.Screen name="Login" component={LoginScreen} />
        <Stack.Screen name="Home" component={HomeScreen} />
      </Stack.Navigator>
    </NavigationContainer>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    /* alignItems: "center",
    justifyContent: "center", */
    marginBottom: 25
  },
  fbbutton: { backgroundColor: "#3b5998" },
  flex: 1,
  marginTop: 25
});
```

 It says undefined is not an object (evaluating 'navigation.navigate')

**Expected Behavior**

I expected to navigate ("Home")

**How to reproduce**

https://snack.expo.io/@zicxor/09d84c

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |  Expo client
| @react-navigation/native       | ^5.1.0
| @react-navigation/stack        | ^5.2.1
| react-native-gesture-handler   | ~1.5.0
| react-native-safe-area-context | 0.6.0
| react-native-screens           | 2.0.0-alpha.12
| react-native                   | 0.61.4
| expo                           | ~36.0.0
| node                           | 10.15.3
| npm or yarn                    | 6.14.2

**Comment by eriveltonelias** [comment]
Hey @erdoganmithat 

instead of using `navigation.navigate("HomeScreen");` 
you can do the following https://reactnavigation.org/docs/app-containers/#calling-dispatch-or-navigate-on-app-container  because the function App does not receive the navigation prop.

**Comment by CallMeProteus** [comment]
> Hey @erdoganmithat
> 
> instead of using `navigation.navigate("HomeScreen");`
> you can do the following https://reactnavigation.org/docs/app-containers/#calling-dispatch-or-navigate-on-app-container because the function App does not receive the navigation prop.


Your link is broken, please look into it

**Comment by Troy-Harder** [comment]
Hey, could u please tell me how u solved that problem?  Thanks in advance.

**Comment by AAwaisYaseen** [comment]
> Hey @erdoganmithat
> 
> instead of using `navigation.navigate("HomeScreen");`
> you can do the following https://reactnavigation.org/docs/app-containers/#calling-dispatch-or-navigate-on-app-container because the function App does not receive the navigation prop.

the Link is not working

**Comment by cbandara** [comment]
https://reactnavigation.org/docs/navigation-prop/#dispatch

**Comment by rzkypebrian** [comment]
> Hey @erdoganmithat
> 
> instead of using `navigation.navigate("HomeScreen");`
> you can do the following https://reactnavigation.org/docs/app-containers/#calling-dispatch-or-navigate-on-app-container because the function App does not receive the navigation prop.

the link is broken, can u tell me the new link?

**Comment by raajnadar** [comment]
@rzkypebrian you should read all the comments, the comment which was made before you're comment has got the working link.

**Comment by lylest** [comment]
link is still broken

**Comment by HieuMinh1907** [comment]
I have a problem like this
<img width="847" alt="Screen Shot 2021-08-17 at 14 11 11" src="https://user-images.githubusercontent.com/81904379/129682450-253efedb-0cbe-4960-afa5-9ca4063a4b39.png">

**Comment by raajnadar** [comment]
https://reactnavigation.org/docs/navigation-prop/#dispatch the link is working but the scroll spy is not working for some reason.

For all the people having this issue make sure you have access to the navigation object or else you can use `useNavigation` hook to get assess anywhere inside the navigation container.
