### ISSUE TITLE
web: direct link to nested route, back button leaves app

### ISSUE THREAD

**Issue by RWOverdijk** [react-navigation/react-navigation#7852]
**Current Behavior**

Using react navigation on the web I have an issue with browser behaviour.

When I go directly to a nested url and press the back button in the header the browser goes back to the previous page (so my "new tab" page). I can see it animate to the correct page really briefly before it redirects back, but it doesn't seem to stop the browser navigating back.

I made a short video that showcases the issue: https://youtu.be/7J_wtgxzqrI

**Expected Behavior**

- What do you expect should be happening?
- Include a screenshot or video if it makes sense.

**How to reproduce**

Go directly to a nested page (make sure linking is set up properly) and press the back button in the react navigation nav bar.

I made a project that shows the issue: https://github.com/RWOverdijk/nav-issue 

Upon starting the app and opening it in the browser there's a button that says **Go to nested view.**.  Clicking this will work. Navigating back (click back arrow in the react-navigation bar) will also work.

What will not work however is taking that nested url (http://localhost:19006/venue/test-slug), opening it in a new tab and then pressing back in the nav bar. It'll go back to the previous page (which is the "new tab" page of your browser).

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Web
| @react-navigation/native       |  5.1.1
| @react-navigation/stack        | 5.2.3
| react-native-gesture-handler   | 1.5.6
| react-native-safe-area-context | 0.6.
| react-native-screens           |  2.0.0-alpha.12
| react-native                   | 0.61.4, expo sdk-36.0.0
| expo                           | 36.0.2
| node                           | 12.13.0
| npm or yarn                    | 1.17.3

I realise web support is experimental but I'd like to help. Is there a branch this is being worked on? A backlog or todo list maybe?

**Comment by RWOverdijk** [comment]
🎉

**Comment by alexmccabe** [comment]
It goes deeper than that, you can't reset to the top of the stack, and you can't call `navigation.goBack()` as there's nothing in history. I've spent many hours today trying to reset to the top when navigating directly to a url.
