### ISSUE TITLE
TransitionPresets.ModalPresentationIOS cause card to overflow the device screen

### ISSUE THREAD

**Issue by lsps9150414** [react-navigation/react-navigation#7856]
**Current Behavior**

Please look at the orange border which is set on the `cardStyle` of a screen.

Standard Modal Transition:
![Simulator Screen Shot - iPhone 8 - 2020-03-24 at 15 57 13](https://user-images.githubusercontent.com/5022617/77402367-871f3b80-6de9-11ea-98d1-97536136c41f.png)

When using `TransitionPresets.ModalPresentationIOS`, note the bottom of the orange border is not inside the device's screen:

![Simulator Screen Shot - iPhone 8 - 2020-03-24 at 15 57 07](https://user-images.githubusercontent.com/5022617/77402373-88e8ff00-6de9-11ea-8199-c1b32f72fc1c.png)

Note: The `borderWidth` I set is 11, it looks like the exceeding height is 10.

**Expected Behavior**

The screen should shrink in height to be fully displayed when `TransitionPresets.ModalPresentationIOS` is used.

**How to reproduce**

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | ios |
|    "@react-navigation/bottom-tabs" | "^5.2.2", |
|    "@react-navigation/native" | "^5.1.0",
|   "@react-navigation/stack" | "^5.2.1",
| react-native                   | 0.61.4 |
| expo                           | ^36.0.0 | 
| node                           | v12.0.0 | 
| npm or yarn                    | yarn |

**Comment by dv-jm** [comment]
I have this issue with the iPhone 8 simulator but not the iPhone 11.
So maybe it occurs only when there are no safe areas?

**Comment by nicholaskim94** [comment]
+1. 
Same behaviour is found on Android devices with `TransitionPresets.ModalPresentationIOS`
