### ISSUE TITLE
No screen is focused when using custom bottomTabBar component

### ISSUE THREAD

**Issue by SocialBrothersDEV** [react-navigation/react-navigation#7861]
**Current Behavior**
I am setting up a bottomTabNavigator with a custom tabBar component. In my stack i enter the correct icons based on whether the screen is focused or not. When i am using the default tabBar component i receive a prop `focused` which is true or false. Whenever i'm using a custom tabBar, i dont get passed this prop. I have followed the documentation on 'Creating custom navigators', but no success. i would think that by emitting tabPress (which i am emitting), the correct screen would get the focused prop, but not.

Stack: 
```
const Tabs = createBottomTabNavigator();

export default () => (
  <Tabs.Navigator tabBar={TabBarComponent} initialRouteName="Home">
    <Tabs.Screen
      name="Home"
      component={HomeScreen}
      options={{
        tabBarIcon: props => {
          console.log(props); // {}

          const icon = props.focused
            ? require('images/iconOverviewRed.png')
            : require('images/iconOverviewGrey.png');

          return <Image source={icon} />;
        },
      }}
    />
    <Tabs.Screen
      name="Overview"
      component={OverviewScreen}
      options={{
        tabBarIcon: props => {
          return <Image source={require('images/logoRed.png')} />;
        },
      }}
    />
    <Tabs.Screen
      name="Account"
      component={AccountScreen}
      options={{
        tabBarIcon: props => {
          console.log(props); // {}

          const icon = props.focused
            ? require('images/iconAccountRed.png')
            : require('images/iconAccountGrey.png');
          return <Image source={icon} resizeMethod="resize" />;
        },
      }}
    />
  </Tabs.Navigator>
);
```

tabBar component: 
```
const TabBar = ({ navigation, state, descriptors }: any) => {
  return (
    <LinearGradient
      style={styles.backgroundGradient}
      colors={['#ffffff', '#eeeeee']}>
      <View style={styles.container}>
        {state.routes.map((route: any, index: number) => {
          const onPress = () => {
            const event = navigation.emit({
              type: 'tabPress',
              target: route.key,
              canPreventDefault: true,
            });

            if (!event.defaultPrevented) {
              navigation.dispatch({
                ...TabActions.jumpTo(route.name),
                target: state.key,
              });
            }
          };

          return (
            <TabIcon
              key={route.key}
              Icon={descriptors[route.key].options.tabBarIcon}
              onPress={onPress}
              isBig={route.name === 'Overview'}
            />
          );
        })}
      </View>
    </LinearGradient>
  );
};
```

**Expected Behavior**

- I would expect the tabBarIcon to have the `focused` prop.
- Or i would expect more documentation on how to pass the focused prop in my custom tabBar

**How to reproduce**
Make up the above navigator and try to retreive the focused prop.

**Your Environment**

| software                      | version |
| ----------------------------- | ------- |
| iOS or Android                | Both
| @react-navigation/native      | ^5.1.2
| @react-navigation/bottom-tabs | ^5.2.4
| react-native-screens          | ^2.0.0-alpha.26
| react-native                  | 0.61.5
| expo                          | No
| node                          | 13.8.0
| npm or yarn                   | yarn 1.22.0

**Comment by SocialBrothersDEV** [comment]
For anyone else looking for this solution, it is not a bug.  `descriptors[route.key].options.tabBarIcon` gives you access to the function you have specified in your stack, thus you have to supply the arguments yourself. Using `descriptors[route.key]options.tabBarIcon({focused: route.index === index})` gives you the parameter the same as the default tabBar will.

**Comment by arundevkv** [comment]
@SocialBrothersDEV This works for me.
