### ISSUE TITLE
tabPress event not fired, when listeners requires navigation 

### ISSUE THREAD

**Issue by JsonGuy** [react-navigation/react-navigation#7862]
As stated in this documentation 
https://reactnavigation.org/docs/navigation-events/

**Current Behavior**

```
<Tab.Navigator labeled={false} barStyle={{backgroundColor: '#ffffff', height: 55}}>
            <Tab.Screen name={`DeviceNavigatorTab`} component={DeviceNavigator} options={{
                tabBarIcon: ({tintColor}) => <Image source={require('../../images/feather_home-menu.png')} style={{width: 26, height: 26, tintColor}}/>,
            }} listeners={{
                tabPress: e => {
                    console.log('tabPress') //Works
                }
            }}/>
            <Tab.Screen name={`AlarmNavigatorTab`} component={AlarmNavigator} options={{
                tabBarIcon: ({tintColor}) => <Image source={require('../../images/feather_alert-circle.png')} style={{width: 26, height: 26, tintColor}}/>,
            }} listeners={({ navigation, route }) => ({
                tabPress: e => {
                    console.log('tabPress 1') // Dont work
                    // Prevent default action
                    e.preventDefault();

                    // Do something with the `navigation` object
                    navigation.navigate('AnotherPlace');
                },
            })}/>
            <Tab.Screen name={`ProfileNavigatorTab`} component={ProfileNavigator} options={{
                tabBarIcon: ({tintColor}) => <Image source={require('../../images/feather_user.png')} style={{width: 26, height: 26, tintColor}}/>,
            }} />
        </Tab.Navigator>
```

**Expected Behavior**

It should console log tabPress 1, but it is not working

**Your Environment**

| software                               | version |
| -------------------------------------- | ------- |
| iOS or Android                         | 13.4
| @react-navigation/native               | 5.1.2
| @react-navigation/material-bottom-tabs | 5.1.5
| react-native-paper                     | 3.6.0
| react-native                           | 36.0.0
| expo                                   | 36.0.2
| node                                   | 12.14.0
| npm or yarn                            | yarn 1.21.1

**Comment by satya164** [comment]
Please upgrade your packages

**Comment by Osamasomy** [comment]
I have the same issu as describe in this Question and I also update all liabraries but notworking with callback.
i am also try useNavigation hook but its genrate error hooks only availabe inside function.
Any other solution ?

**Comment by Osamasomy** [comment]
> Please upgrade your packages

I have the same issu as describe in this Question and I also update all liabraries but notworking with callback.
i am also try useNavigation hook but its genrate error hooks only availabe inside function.
Any other solution ?

**Comment by Liqiankun** [comment]
@Osamasomy Yes, I have the same issue. How can we fix it?

**Comment by iiagodias** [comment]
Solution?

**Comment by OkancanCosar** [comment]
"@react-navigation/bottom-tabs": "^6.3.2",
    "@react-navigation/drawer": "^6.4.3",
    "@react-navigation/native": "^6.0.11",
    "@react-navigation/stack": "^6.2.2",

with this configurations bug still continue. 




```js
useEffect(() => {
        const unsubscribe = props.navigation.addListener('tabPress', (e: any) => {
            console.log("⚡️ e", e);
            props.navigation.navigate('Home');
        });
        return unsubscribe;
    }, [props.navigation]);
```

or

```js
 <BottomTab.Screen
                name={ScreenNames.UploadFile}
                component={UploadFile}
                listeners={{ tabPress: e => e.preventDefault(), }}
```
anyone has a solution?

**Comment by rkstar** [comment]
why was this closed? it's still an issue!
