### ISSUE TITLE
No transition animation when navigate back to nested tab screen

### ISSUE THREAD

**Issue by frankyjuang** [react-navigation/react-navigation#7864]
**Current Behavior**

No transition animation when navigation.navigate()

**Expected Behavior**

Has transition animation just like navigation.goBack()

**How to reproduce**

https://snack.expo.io/@milkjobs/nested-tab-navigate-transition
1. click Edit
2. click Go Back
3. no transition took place

Note that i'm not using navigation.goBack here because i'm trying to replace callback functions in params with navigate using new params. Recommended here https://reactnavigation.org/docs/params

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | both
| @react-navigation/native       | latest
| react-native                   | 
| expo                           |
| node                           |
| npm or yarn                    |

**Comment by BenGeva** [comment]
+1
I'm experiencing the same behavior.
I also came across this issue - #6827, (which is closed for some reason) and the latest comments refer to the problem of the newly recommended way of sending data in navigate. If callbacks aren't allowed anymore, what is the right way for updating state at the parent screen?

**Comment by frankyjuang** [comment]
@BenGeva navigate from child screen to parent screen with new params will do. However, the issue here is with `navigate` (instead of previous `goBack`) the close transition animation is gone

**Comment by satya164** [comment]
Closing since this seems to be fixed in latest version of stack.

**Comment by kennethbrent** [comment]
Did anyone find a solution? There is still no animation when navigating to a nested screen on my end
