### ISSUE TITLE
StackNavigator Over BottomTabNavigator having display issue (not fast enough)

### ISSUE THREAD

**Issue by guanhuay** [react-navigation/react-navigation#7866]
Hi developers,

Please have a look at this video link that demonstrate the problem: [Look at just above bottom tab when navigating back](https://streamable.com/n0du5)

I just found out this issue happen on react navigation 5.

I am using the kittentricks repo as a example, if you want you can have a look at their navigator file here: [Home Navigator](https://github.com/akveo/kittenTricks/blob/master/src/navigation/home.navigator.tsx)

Any ideas why this is happening and how can we potentially fix it?

**Comment by satya164** [comment]
Nest tab navigator in the first screen of a stack Navigator instead of hiding the tab bar.

**Comment by guanhuay** [comment]
@satya164 

For my current setup, i have the following:


AppNavigator (render either AuthNavigator or MainNavigator based on user authentication)

 ```
   <Stack.Navigator headerMode="none">
      {isAuthenticated ? (
        <Stack.Screen name={RouteName.Main} component={MainNavigator} />
      ) : (
        <Stack.Screen name={RouteName.Auth} component={AuthNavigator} />
      )}
    </Stack.Navigator>
```

MainNavigator (bottom tab navigator, where I insert multiple StackNavigator on each tab, and where I place logic to show or hide tab bar based on the suggestion here [Reference, search for route.state](https://reactnavigation.org/docs/screen-options-resolution/#setting-parent-screen-options-based-on-child-navigators-state) ):

See point 2
![Screen Shot 2020-03-25 at 09 22 38](https://user-images.githubusercontent.com/16933391/77560264-779c0300-6e7a-11ea-8550-14dc01ef209f.png)


```
  const TabBarVisibleOnRootScreenOptions = ({ route }) => {
    return {tabBarVisible: route.state && route.state.index === 0}
  };


    <BottomTab.Navigator
      initialRouteName={RouteName.Home}
      lazy={false}
      screenOptions={TabBarVisibleOnRootScreenOptions}
      tabBar={(props) => <BottomTabBar {...props} />}
    >
      <BottomTab.Screen
        name={RouteName.Home}
        component={HomeTopTabNavigator}
      />
      <BottomTab.Screen
        name={RouteName.Member}
        component={MemberStackNavigator}
      />
      <BottomTab.Screen
        name={RouteName.Order}
        component={OrderStackNavigator}
      />
       .............
      />
    </BottomTab.Navigator>

```


So I think I am following the recommended way of implement it, isn't it?
