### ISSUE TITLE
Typescript: Only literal values are allowed in constant context

### ISSUE THREAD

**Issue by JensDebergh** [react-navigation/react-navigation#7870]
**Current Behavior**

- What code are you running and what is happening?

I'm running following version of `react-navigation`:

```
   "@react-native-community/masked-view": "0.1.5",
    "@react-navigation/bottom-tabs": "^5.2.4",
    "@react-navigation/native": "^5.1.3",
    "@react-navigation/stack": "^5.2.6",
```
Typescript version: `3.7.2`

Tsconfig:

```
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "jsx": "react-native",
    "lib": ["dom", "esnext"],
    "moduleResolution": "node",
    "noEmit": true,
    "skipLibCheck": true,
    "resolveJsonModule": true
  }
}
```

- Include a screenshot or video if it makes sense.

<img width="1137" alt="screenshot" src="https://user-images.githubusercontent.com/6651506/77624522-3c650700-6f42-11ea-90ab-f64285f2e1bc.png">

**Expected Behavior**

- What do you expect should be happening?

No literal values are allowed in constant contexts.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |both
| @react-navigation/native       |^5.1.3
| react-native                   |https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz
| expo                           |^36.0.0
| node                           |12.10
| npm or yarn                    |yarn

```
SyntaxError: /Users/null/app/@react-navigation/core/src/useSyncState.tsx: Only literal values are allowed in constant contexts (27:10)

  25 |   }, []);
  26 |
> 27 |   return [state, getState, setState] as const;
     |           ^
  28 | }
  29 |
Failed building JavaScript bundle.
```

Am I doing something wrong here? I just upgraded my packages to all the latest versions and got hit with this error. Might be a bug with typing.

The constant context has been added in typescript for quite some time. But as said I'm running the latest stable version on all my packages.

Kind regards
Jens

**Comment by satya164** [comment]
Can you tell me the version of `@babel/plugin-syntax-typescript` and `@babel/plugin-transform-typescript` in your project?

Run:

```sh
yarn why @babel/plugin-syntax-typescript
yarn why @babel/plugin-transform-typescript
```

**Comment by JensDebergh** [comment]
Hey there!

Just checked:

Found "@babel/plugin-syntax-typescript@7.3.3"
Found "@babel/plugin-transform-typescript@7.4.0"

I don't directly reference these plugins in my package.json. But my guess is they are packaged along with. 

`babel-preset-expo`

Which one should I upgrade?

**Comment by satya164** [comment]
Try deleting your `yarn.lock` or updating them in your `yarn.lock` file to latest versions.
