### ISSUE TITLE
navigation.replace removed from types in 5.2.2

### ISSUE THREAD

**Issue by LinusU** [react-navigation/react-navigation#7872]
**Current Behavior**

Today I bumped some dependencies, and got the following error in my app:

<img width="775" alt="Screenshot 2020-03-26 at 12 30 59" src="https://user-images.githubusercontent.com/189580/77647054-a8089d80-6f5d-11ea-9a86-8fc6c21c9219.png">

`navigation` comes from `const navigation = useNavigation()`

After some investigation I noticed that:

1. They were removed in this commit:
    https://github.com/react-navigation/react-navigation/commit/646cbfb28e319d8db2387962195c1d06f07ebad6#diff-c02dbd883a9765a06e96cfaf5d4ae40e
2. They were present in the published files of 5.2.1:
    https://cdn.jsdelivr.net/npm/@react-navigation/core@5.2.1/lib/typescript/src/types.d.ts
3. They are not present in the published files of 5.2.2:
    https://cdn.jsdelivr.net/npm/@react-navigation/core@5.2.2/lib/typescript/src/types.d.ts

**Expected Behavior**

I expected the types for `replace` to still be present.

**How to reproduce**

n/a

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | n/a
| @react-navigation/native       | n/a
| react-native                   | n/a
| expo                           | n/a
| node                           | n/a
| npm or yarn                    | n/a

-----

Potentially I've been using the API wrong somehow, or typed it wrong. In that case I would be very happy to change my code, I still think that it would be nice to add it back with a `@deprected` notation tough since this breaks code in a patch version...

**Comment by satya164** [comment]
Please follow the typescript guide and annotate it https://reactnavigation.org/docs/typescript#annotating-usenavigation

**Comment by LinusU** [comment]
Thanks for pointing me in the right direction...
