### ISSUE TITLE
[android] Keyboard does not hide on screen change.

### ISSUE THREAD

**Issue by MaxBolotnyi** [react-navigation/react-navigation#7875]
**Current Behavior**
Demo project to test (Expo):
https://github.com/MaxBolotnyi/android-keyboard-issue

When you open the keyboard and then switch the screen - the keyboard remains to be open.

**Expected Behavior**

The keyboard should hide when the screen changes.

**How to reproduce**

https://github.com/MaxBolotnyi/android-keyboard-issue

1. Clone the project.
2. Run `expo install`
3. Run `react-native run-android`
4. Click on the input field.
5. Click on the 'goSecond' button.

**Your Environment**

  "@react-native-community/masked-view": "^0.1.7",
    "expo": "~36.0.0",
    "react": "~16.9.0",
    "react-dom": "~16.9.0",
    "react-native": "~0.61.4",
    "react-native-gesture-handler": "^1.5.6",
    "react-native-reanimated": "^1.4.0",
    "react-native-safe-area-context": "^0.7.3",
    "react-native-screens": "^2.0.0-alpha.12",
    "react-native-unimodules": "~0.7.0",
    "react-native-web": "~0.11.7",
    "react-navigation": "^4.3.3",
    "react-navigation-stack": "^2.3.6"

**Comment by MaxBolotnyi** [comment]
Opened a pull request to fix the issue

**Comment by frankyjuang** [comment]
having the same issue. another repro https://snack.expo.io/@milkjobs/android-keyboard-not-dismiss

**Comment by MaxBolotnyi** [comment]
@frankyjuang the pull request has been merged today :)

**Comment by cristianoccazinsp** [comment]
PR didn't solve the issue.  Android keyboard still stays opened after a screen change.

"@react-navigation/compat": "5.1.7",
"@react-navigation/native": "5.1.4",
"@react-navigation/stack": "5.2.9",

**Comment by Trancever** [comment]
@MaxBolotnyi Can you confirm if it works fine for you on the latest version of react-navigation -> @react-navigation/stack v5.2.10?

I am unable to reproduce the issue on that version.

**Comment by MaxBolotnyi** [comment]
@Trancever, Hi, particularly this issue is gone, however it brought back another one - #6918

Here I have the pull request that is supposed to handle both cases, you can review it [here](https://github.com/react-navigation/react-navigation/pull/7931) and share your opinion.

**Comment by Trancever** [comment]
@MaxBolotnyi I tried to reproduce it on both - the latest v4 and latest v5 and it work fine.

**Comment by KristineTrona** [comment]
I can verify I am having the same issue on `@react-navigation/native v5.5.1`, but on ios.

This is the structure of my navigator:
```
const AuthStack = createStackNavigator();
const AuthStackScreen = () => {
  return (
    <AuthStack.Navigator>
      <AuthStack.Screen name="WelcomeScreen" component={WelcomeScreen} />
      <AuthStack.Screen name="LoginScreen" component={LoginScreen} />
      <AuthStack.Screen name="OnboardingScreen" component={OnboardingScreen} />
      <AuthStack.Screen name="AnotherScreenWithTextInput" component={AnotherScreenWithTextInput} />
    </AuthStack.Navigator>
  );
};

const TabNavigator = createBottomTabNavigator();
const TabNavigatorScreen = () => (
  <TabNavigator.Screen name="Home" component={HomeScreen} />
  <TabNavigator.Screen name="Settings" component={SettingsScreen} />
);

const RootStackScreen = () => {
  return (
    <RootStack.Navigator screenOptions={{ headerShown: false, animationEnabled: false }}>
      <RootStack.Screen name="Auth" component={AuthStackScreen} />
      <RootStack.Screen name="App" component={TabNavigatorScreen} />
    </RootStack.Navigator>
  );
};

export default function Navigator() {
  return (
    <NavigationContainer>
      <RootStackScreen />
    </NavigationContainer>
  );
}

```
I notice that Keyboard is not automatically being dismissed as I navigate from `LoginScreen` to `OnboardingScreen` and also as I navigate from `AnotherScreenWithTextInput`to `App`.
