### ISSUE TITLE
Horizontal ScrollView swipe gesture clashes with Stack Navigator swipe gesture

### ISSUE THREAD

**Issue by nicolaspavlotsky** [react-navigation/react-navigation#7878]
I'm using React Navigation 4, and I have a stack navigator with a Swipe Gesture (to be able to swipe back between screens). This is the code:

```
const myStack = createStackNavigator(
  {
    screen1: Screen1,
    screen2: Screen2,
  },
  {
    defaultNavigationOptions: {
      gesturesEnabled: true,
      gestureResponseDistance: { horizontal: 1000 }
    },
    mode: 'card',
    transitionConfig: () => StackViewTransitionConfigs.SlideFromRightIOS
  }
);
```

Inside one of the screens I have a Scrollview with "horizontal" set to true. I want this scrollview to take precedence over the swipe back gesture (obviously, cause otherwise the scrollview becomes unusable).

Happens in all versions of Android and iOS.

**Package versions:**
react-navigation: 4.0.10
react-navigation-stack: 1.10.3
react-native-reanimated: 1.2.0
react-native-gesture-handler: 1.3.0
react-native: sdk-35.0.0
expo: 35.0.0

**Comment by satya164** [comment]
Import `ScrollView` from `react-native-gesture-handler` and it shouldn't happen.

**Comment by nicolaspavlotsky** [comment]
> Import `ScrollView` from `react-native-gesture-handler` and it shouldn't happen.

It didn't work, still happens

**Comment by ithebk** [comment]
> Import `ScrollView` from `react-native-gesture-handler` and it shouldn't happen.

Still, the issue is there.

**Comment by ManAnRuck** [comment]
how does it work with React Navigation 5?

**Comment by MountBaqer** [comment]
I'm having the same problem right now.

**Comment by Aryk** [comment]
Me too...any updates on this?

**Comment by ofgowtham** [comment]
Still happening. Anyone find any solution?

**Comment by PeterVuyk** [comment]
I also have the same problem

**Comment by PeterVuyk** [comment]
I solved it by adding hitSlop={{ left: -50 }}

**Comment by ofgowtham** [comment]
> 

Where do I add the hitSlop? in navigator options?
