### ISSUE TITLE
Nested navigation not working with react-native 0.62.0

### ISSUE THREAD

**Issue by tankpower1** [react-navigation/react-navigation#7880]
**Current Behavior**

- What code are you running and what is happening?
- Include a screenshot or video if it makes sense.

**Expected Behavior**

- What do you expect should be happening?
- Include a screenshot or video if it makes sense.

Currently i have a tab navigator with 3 tabs that are stack navigators. Trying to navigate from one tab to another doesn't seem to work with version 0.62.0 of react-native.

This is the error:

<pre>
The action 'NAVIGATE' with payload {"name":"Chats"} was not handled by any navigator.

Do you have a screen named 'Chats'?

If you're trying to navigate to a screen in a nested navigator, see https://reactnavigation.org/docs/nesting-navigators#navigating-to-a-screen-in-a-nested-navigator.

This is a development-only warning and won't be shown in production.
</pre>

**How to reproduce**

1. Create a bottom navigator with 3 tabs.
2. Create a stack navigator for each tab.
3. Try to navigation.navigate('Tab1', {screen: 'ScreenInTab1'});

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | both
| @react-navigation/native       |  5.1.3
| @react-navigation/stack        | 5.2.6
| react-native-gesture-handler   | 1.6.1
| react-native-safe-area-context | 0.7.3
| react-native                   | 0.62.0
| npm or yarn                    | yarn

**Comment by compojoom** [comment]
Doesn't sound like a 0.62 problem. 

You haven't shared your Navigation config, but it sounds more that you are trying to navigate from stack1 to a screen in stackB. Due to the fact that navigators are lazy loaded in a tab the navigator that has your screen is most probably not rendered and you end up with the above error.

**Comment by tankpower1** [comment]
Oh yea, my bad i put unmountOnBlur to true because i wanted the tabs to refresh but it seems that it breaks the lazy loading.
