### ISSUE TITLE
Problem with internal ref usage when using scrollToTop hook method

### ISSUE THREAD

**Issue by tankpower1** [react-navigation/react-navigation#7881]
**Current Behavior**

Hello,
currently i created a tab screen which wraps my class component with the provided method for scrolling to the top when pressing the screen tab. Everything works fine but i can't seem to use the ref inside the class itself. I'm trying to implement a scrollToOffset({y: 0}) logic for my flatlist when the screen updates but the ref doesn't work.

<pre>
class Screen extends Component {

    state = {
        data: []
    };

    componentDidMount() {

        this.focusListener = this.props.navigation.addListener('focus', () => this.fetchData());

    }

    componentWillUnmount() {

        this.focusListener();

    }

    fetchData = () => {

        axios.get(DATA_PATH)
            .then(res => {

                this.setState({
                    data: res.data || []
                }, () => {
                
                    this.props.listRef.current.scrollToOffset({y: 0});

                });

            });
    };

    handleOnRefreshData = () => this.fetchData()));

    render() {

        return (
            <View>               
                    <FlatList
                        listRef={listRef}
                        data={this.state.data}
                        keyExtractor={item => item.id.toString()}
                        refreshControl={
                            <RefreshControl
                                onRefresh={this.handleOnRefreshData}
                            />
                        }
                        renderItem={({item}) => (
                            null
                        )}
                    />
                }
            </View>
        )
    }
}

export default props => {

    const ref = React.useRef(null);

    useScrollToTop(ref);

    return <Screen {...props} listRef={ref}/>;

}
</pre>

**Expected Behavior**

It should allow me to use the ref from inside the class?

**Comment by satya164** [comment]
https://reactnavigation.org/docs/use-scroll-to-top#using-with-class-component
