### ISSUE TITLE
Missing package with yarn install @react-navigation 5

### ISSUE THREAD

**Issue by PaulB2Code** [react-navigation/react-navigation#7885]
**Current Behavior**

When we install 

    "@react-navigation/native": "^5.1.3",
    "@react-navigation/stack": "^5.2.7",

It missed 3 package 
1/ 
Module not found: Can't resolve 'react-native-gesture-handler' in '/***h/AwesomeProjectTypeScript/node_modules/@react-navigation/stack/lib/module/views'
2/
    "react-native-safe-area-context": 
3/ 
@react-native-community/masked-view

**Expected Behavior**

{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "@react-navigation/native": "^5.1.3",
    "@react-navigation/stack": "^5.2.7",
    "expo": "~36.0.0",
    "react": "~16.9.0",
    "react-dom": "~16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz",
    "react-native-screens": "2.0.0-alpha.12",
    "react-native-web": "~0.11.7"
  },
  "devDependencies": {
    "@types/react": "~16.9.0",
    "@types/react-native": "~0.60.23",
    "@babel/core": "^7.0.0",
    "babel-preset-expo": "~8.0.0",
    "typescript": "~3.6.3"
  },
  "private": true
}

**Your Environment**

Expo CLI 3.15.5 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.8.1 - /usr/local/bin/node
      Yarn: 1.3.2 - /usr/local/bin/yarn
      npm: 6.13.6 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6241897
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ~36.0.0 => 36.0.2 
      react: ~16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4 
    npmGlobalPackages:
      expo-cli: 3.15.5

**Comment by satya164** [comment]
Please read the docs https://reactnavigation.org/docs/getting-started
