### ISSUE TITLE
[V5]headerMode='none' Not working

### ISSUE THREAD

**Issue by kkusanagi** [react-navigation/react-navigation#7888]
- What code are you running and what is happening?
using code as below.  
```
<SafeAreaProvider>
      <NavigationContainer>
        <Stack.Navigator>
          <Stack.Screen name="Login" component={LoginScreen} headerMode='none' />
        </Stack.Navigator>
      </NavigationContainer>
    </SafeAreaProvider>
```
The stack still render the header. Should be no render.

**Your Environment**

IOS
    "react": "16.9.0",
    "react-native": "^0.60.5",
    "@react-native-community/async-storage": "^1.8.1",
    "@react-native-community/geolocation": "^2.0.2",
    "@react-native-community/masked-view": "^0.1.7",
    "@react-navigation/bottom-tabs": "^5.2.4",
    "@react-navigation/native": "^5.1.3",
    "@react-navigation/stack": "^5.2.8"

using Npm and NO Expo.

**Comment by satya164** [comment]
https://reactnavigation.org/docs/stack-navigator#headershown

**Comment by kkusanagi** [comment]
Please open the issue back. Not working at all. Added but not working at all. Still showing the header. 
`
<Stack.Screen name="Login" component={LoginScreen} headerShown={false} headerMode='none' />
`

**Comment by Nagai-S** [comment]
<Stack.Screen options={{ headerShown: false }} />
you can hide header.
