### ISSUE TITLE
Setting gestureResponseDistance does not work. It has no effect.

### ISSUE THREAD

**Issue by jpcahoon** [react-navigation/react-navigation#7890]
**Current Behavior**

- What code are you running and what is happening?
I cloned the github repository [master v.5](I had the same issues in my own project running react-navigation/drawer 5.3.4 and react-navigation/native 5.1.3) and ran the example on an iOS simulator. I had the same issues with the Android simulator in my own project.

The bare example works fine but setting gestureResponseDistance has no effect.

iPhone 8, iOS 13.2, Simulator: Version 11.2.1 (SimulatorApp-912.4 SimulatorKit-570.3 CoreSimulator-681.15)

I edited: react-navigation/example/src/index.tsx at line 239 to look as follows:

```
        <Drawer.Navigator drawerType={isLargeScreen ? 'permanent' : undefined}>
          <Drawer.Screen
            name="Root"
            options={{
gestureResponseDistance: {horizontal: 0},
              title: 'Examples',
              drawerIcon: ({ size, color }) => (
                <MaterialIcons size={size} color={color} name="folder" />
              ),
            }}
          >
```

Setting the gestureResponsDistance had no effect on the example in the simulator. I was still able to swipe open the drawer. It does not seem to matter what number I set, I could effect no change. I tried many other mechanisms for setting gestureResponseDistance, but nothing I did had any effect. I showed this technique because it worked for "gestureEnabled". If there is a way to get "gestureResponseDistance" to work in react-navigation v5, then I would like to know what it is.

However, I can effect the drawer if I use the following code instead:
```
        <Drawer.Navigator drawerType={isLargeScreen ? 'permanent' : undefined}>
          <Drawer.Screen
            name="Root"
            options={{
gestureEnabled: false,
              title: 'Examples',
              drawerIcon: ({ size, color }) => (
                <MaterialIcons size={size} color={color} name="folder" />
              ),
            }}
          >
```
As expected, the example no longer allows me to swipe the drawer open. However, also as expected, tapping outside the drawer no longer closes the drawer. I was expecting that setting gestureResponseDistance to a horizontal distance of 0 would disable swiping open, but still allow clicking outside of the drawer to close the drawer.

- Include a screenshot or video if it makes sense.
N/A

**Expected Behavior**

- What do you expect should be happening?
I expected setting the gestureResponseDistance would effect the drawer in the example. Setting horizontal to 0 should have disabled swiping the drawer open.

- Include a screenshot or video if it makes sense.
N/A

**How to reproduce**
Clone react-navigation (4.3.4 is the latest release, but this is a clone of master), add one line to index.tsx of the example as described above, and run the example. The drawer can still swipe open, even with gestureResponseDistance: {horizontal: 0}.

- You must provide a way to reproduce the problem. If you are having an issue with your machine or build tools, the issue belongs on another repository as that is outside of the scope of React Navigation.
- Either re-create the bug on [Snack](https://snack.expo.io) or link to a GitHub repository with code that reproduces the bug.
- Explain how to run the example app and any steps that we need to take to reproduce the issue from the example app.
- Keep the repro code as simple as possible, with the minimum amount of code required to repro the issue.
- Before reporting an issue, make sure you are on latest version of the package.

**Your Environment**

| software                       | version |     MacBook Pro running Version 10.15.2
| ------------------------------ | ------- |
| iOS or Android                 | iOS simulator iPhone 8 [Software version 13.2.2] ((I experienced exactly the same problem on android emulator)
| @react-navigation/native       |  Clone of repository - master (same problem on 5.1.3)
| @react-navigation/drawer       | Clone of repository - master (same problem on 5.3.4)
| react-native-reanimated        | 1.7.0
| react-native-gesture-handler   | 1.6.0
| react-native-safe-area-context | 0.7.3
| react-native-screens           | 2.3.0
| react-native                   | 0.61.5
| expo                           | 36.0.2
| node                           | v13.11.0
| npm or yarn                    | yarn 1.18.0

**Comment by satya164** [comment]
`gestureResponseDistance` is an option of stack navigator, not drawer.

https://reactnavigation.org/docs/drawer-navigator#minswipedistance
