### ISSUE TITLE
Setting shadow to custom tab bar does not work

### ISSUE THREAD

**Issue by rptoma** [react-navigation/react-navigation#7891]
**Current Behavior**

I am rendering a custom tab bar in my Tab.Navigator.
I want the tab bar to have a bottom shadow.
I tried setting the style of the main view in the `tabBar` rendering function to:
```
      {
        backgroundColor: 'white',
        flexDirection: 'row',
        shadowColor: 'black',
        shadowRadius: 3,
        overflow: 'visible',
        shadowOpacity: 0.5,
        shadowOffset: {
          width: 2,
          height: 2
        }
      }
```
It doesn't work. Nothing visible happens.

The closest I've come to the desired result was when also setting zIndex to a high value, but this doesn't seem like a common practice.

How should one add shadows to custom tab bars properly? Thank you.

**Expected Behavior**
![Observe the shadown under the tab bar](https://i.imgur.com/eYfQqQF.png)

**Comment by satya164** [comment]
Add a `z-index` to your component.

**Comment by noktigula** [comment]
I'm facing the same issue, tried to copy code from the snippet and it doesn't work. Adding a `z-index` doesn't solve the issue.

**Comment by k1nnx** [comment]
Same here.

**Comment by xenvi** [comment]
Still would like to know the answer to this. I am using the `react-native-tab-view` alone and found a workaround when using the TabBar and TabView components. The only thing is it requires a high z-index and a background color to work. Inside of the renderTabBar function, I wrapped the <TabBar> component in a View with zIndex, shadow properties, and a background color. Not the prettiest solution but it suffices. Maybe something similar can be translated to `Tab.Navigator`?

<img width="419" alt="image" src="https://github.com/react-navigation/react-navigation/assets/49381727/28e4437f-6d0a-47c6-a16d-7ef8c04a2f42">


`
import {
  NavigationState,
  SceneRendererProps,
  TabBar,
  TabView,
} from 'react-native-tab-view';

const renderTabBar = useCallback(
    (
      props: SceneRendererProps & {
        navigationState: NavigationState<{
          key: string;
          title: string;
        }>;
      },
    ) => {
      return (
        <View
          style={{
            zIndex: 9999,
            backgroundColor: BG_COLOR,
            elevation: 7,
            shadowOpacity: 0.15,
            shadowColor: '#000000',
            shadowOffset: {
              width: 0,
              height: 3,
            },
          }}>
          <TabBar {...props} />
        </View>
      );
    },
    [BG_COLOR],
  );

<TabView
      renderTabBar={renderTabBar}
     {...otherTabViewProps}
/>
`
