### ISSUE TITLE
Type checking issue with CompositeNavigationProp

### ISSUE THREAD

**Issue by tspike** [react-navigation/react-navigation#7892]
**Current Behavior**

- What code are you running and what is happening?

Code: https://github.com/tspike/rn-nav-issue

When passing a `CompositeNavigationProp` along to child screens, VS Code highlights `.navigation` with the following error:

> Property 'navigation' does not exist on type 'CompositeNavigationProp<BottomTabNavigationProp<TabParamList, "A">, StackNavigationProp<AParamList, string>>'. Did you mean 'navigate'?

However, running the code as-is, it works fine.

Taking the suggestion and replacing it with `navigate` causes a runtime crash. Debugging inspection reveals that `.navigation` actually does exist on the object.

- Include a screenshot or video if it makes sense.

![](https://github.com/tspike/rn-nav-issue/blob/master/img/Screen%20Shot%202020-03-28%20at%2010.51.24%20AM.png?raw=true)
![](https://github.com/tspike/rn-nav-issue/blob/master/img/Screen%20Shot%202020-03-28%20at%2010.51.33%20AM.png?raw=true)
![](https://github.com/tspike/rn-nav-issue/blob/master/img/Screen%20Shot%202020-03-28%20at%2010.56.45%20AM.png?raw=true)

**Expected Behavior**

- What do you expect should be happening?

Type checking should not indicate an error

**How to reproduce**

- You must provide a way to reproduce the problem. If you are having an issue with your machine or build tools, the issue belongs on another repository as that is outside of the scope of React Navigation.

1. Clone repo: https://github.com/tspike/rn-nav-issue
1. Open in VS Code
1. Observe type error on line 77 in App.js
1. `react-native run-ios`
1. Observe tapping 'Go to details screen' works, despite error
1. Fix type error
1. Run again
1. Observe app crashes

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS Simulator                 | 13.3
| react-navigation               | 5.3.1
| react-navigation-stack         | 5.2.7
| react-navigation-bottom-tabs          |  5.2.4
| react-native-reanimated        | 1.7.1
| react-native-gesture-handler   | 1.6.1
| react-native-safe-area-context | 0.7.3
| react-native-screens           | 2.4.0
| react-native                   | 0.61.3
| node                           | 11.4.0
| npm or yarn                    | 6.4.1

**Comment by satya164** [comment]
It's `(props: { navigation: ANavigationProp })`, not `(navigationProps: ANavigationProp)`

https://reactnavigation.org/docs/typescript/#type-checking-screens

**Comment by tspike** [comment]
Thanks, had tried that and got another type error that looks like it was caused by https://github.com/react-navigation/react-navigation/issues/7882#issuecomment-605021180. Updated to the version you published yesterday and it's working as expected now.
