### ISSUE TITLE
Swipe (with swipeEnabled) doesn't have an event method like onTabBarPress

### ISSUE THREAD

**Issue by kylanhurt** [react-navigation/react-navigation#7895]
`onTabBarPress` is not that helpful if the swiping of the tabs doesn't also trigger it. Since I cannot change the "current index" of the tabs during swipe that means I cannot manually style the "active" tab differently.

Someone should add that hook. I would do it but I'm not sure which swipe library we're using and / or how it works.

**Comment by satya164** [comment]
I'm not sure why you need this as you haven't provided any details, but in screens, you need to use `useNavigationState` to get currently focused route https://reactnavigation.org/docs/use-navigation-state and for tab bar, you receive all required props.

Please follow issue template when opening issues.
