### ISSUE TITLE
Access to react-native-screens HeaderStyleInterpolators and native Screen stacks 

### ISSUE THREAD

**Issue by kyle-ssg** [react-navigation/react-navigation#7899]
**Current Behavior**

As far as I can see currently, the navbar consistst of RCTView's/RCTTextViews and uses JavaScript based navbar transitions. react-native-screens however has the ability to use the standard native UINavigationBar and standard UILabels (and Android equivalent) when rendering and seems to equally use a proper native transition.

**Expected Behavior**
Ideally, I'd like to use this navigation library whilst accessing lower level react-native-screens functionality so that I can step away from using react-native-navigation. 

Perhaps this is already totally possible and I'm missing something, apologies if so.

**Comment by satya164** [comment]
Please open react-native-screens related feature requests in react-natove-screens repo git@github.com:MaxBolotnyi/android-keyboard-issue.git

**Comment by kyle-ssg** [comment]
@satya164 hmm but this isn't a feature for react-native-screens? I think react-native-screens is great! This feature is to expose react-native-screens in this library, so putting the feature request there would be a bit strange.
