### ISSUE TITLE
peerDependencies to dependencies

### ISSUE THREAD

**Issue by nainardev** [react-navigation/react-navigation#7900]
**Current Behavior**

`@react-navigation/native` requires many peer dependencies and it is error prone for a user to install and increases onboarding friction

in docs,https://reactnavigation.org/docs/getting-started#installing-dependencies-into-a-bare-react-native-project

`npm i react-native-reanimated react-native-gesture-handler react-native-screens react-native-safe-area-context @react-native-community/masked-view`

**Expected Behavior**

One should `npm i @react-navigation/native` and he's good to go

**Comment by satya164** [comment]
They are peer dependencies because they need to be. There can only be one version of those dependencies installed at the root level for linking to work properly and it's impossible to ensure that with dependencies,

**Comment by zanona** [comment]
Hi, @satya164. Perhaps it's a good idea to state why on the documentation as for most people used to consume NPM packages, it may feel a bit extraordinary having to manually install dependencies of dependencies.

I think it's good to educate users on this aspect as I was having a problem understanding this myself, and to be honest, it still not very clear to me :) Specially after digging through the package.json file on core and native sub packages and not finding those dependencies listed under `peerDependencies`? 

I case you would like to expand under a reply to this issue I would be happy to open an PR mentioning your explanation.
