### ISSUE TITLE
drawerLockMode is not working for the app

### ISSUE THREAD

**Issue by neemssoni** [react-navigation/react-navigation#7901]
**Current Behaviour**
For the nested Stack Navigator Screens, throughout the app, I am able to open the drawer with swipe. 'drawerLockMode' prop is not working for this version.

`const DrawerNavigator = () => {
return (
<Drawer.Navigator
      drawer
      drawerContent={props => <DrawerScreen {...props} />}
      drawerPosition={'right'}>
      <Drawer.Screen
        name="HomeScreen"
        component={AppStackNavigator}
        options={{
          drawerLockMode: 'locked-closed',
        }}
      />
    </Drawer.Navigator>
  );
};`

**Expected Behaviour**
- I want to disable swipe for Drawer, so that throughout the in any nested stack navigator user should not be able to open the drawer.

**Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS                | 13.x |
| Android | "10" |
| @react-navigation/native       | "^5.0.9" |
| @react-navigation/drawer       | "^5.1.1" |
| react-native-reanimated        | "^1.7.0" | 
| react-native-gesture-handler   | "^1.6.0" | 
| react-native-safe-area-context | "^0.7.3" | 
| react-native-screens           | "^2.3.0" |
| react-native                   | "0.61.2" |

**Comment by satya164** [comment]
https://reactnavigation.org/docs/drawer-navigator#swipeenabled

**Comment by alexakasanjeev** [comment]
Hi @satya164 `swipeEnabled` is not working for me, I'm able to open drawer, by using gesture.

I have a StackNavigator nested inside Drawer navigator, and I want to hide drawer on certain screens, but when I'm setting `swipeEnabled` on individual Stack screen, nothing is happening

```
<Stack.Screen
        name="detail"
        component={DetailScreen}
        options={{
          swipeEnabled: false,
        }}
      />
```
