### ISSUE TITLE
Can not center item label correctly

### ISSUE THREAD

**Issue by soullivaneuh** [react-navigation/react-navigation#7905]
**Current Behavior**

Items are not correctly centered when using `justifyContent` and `alignItems` property. A right padding is always present

**Expected Behavior**

The items should be centered correctly.

**How to reproduce**

Style:

```
listItem: {
  justifyContent: 'center',
  alignItems: 'center',
},
listItemLabel: {
  fontSize: 26,
  fontWeight: 'bold',
},
```

Appliance:

```typescript
<Drawer.Navigator
  initialRouteName="Home"
  drawerContent={DrawerContent}
  drawerType="front"
  drawerStyle={{
    backgroundColor: Colors.pink,
    width: '100%'
  }}
  drawerContentOptions={{
    activeBackgroundColor: 'transparent',
    activeTintColor: 'white',
    itemStyle: styles.listItem,
    labelStyle: styles.listItemLabel,
  }}
>
```

The only hack I found is to set a negative margin:

```
    marginRight: -32,
```

Look related to this: https://github.com/react-navigation/react-navigation/blob/master/packages/drawer/src/views/DrawerItem.tsx#L149

But I didn't find a way to override this style properly.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |
| @react-navigation/native       | 5.1.1
| @react-navigation/drawer       | 5.3.4
| react-native-reanimated        | 1.4.0
| react-native-gesture-handler   | 1.5.0
| react-native-safe-area-context | 0.6.0
| react-native-screens           | 2.0.0-alpha.12
| react-native                   | https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz
| expo                           | 36.0.0
| node                           | v12.11.1
| npm or yarn                    | 6.13.7

**Comment by Rodrigo816** [comment]
I have the same problem, I can't center items properly cus of that
` marginRight: 32`

**Comment by soullivaneuh** [comment]
@satya164 I'm sorry but how this can be considered as a feature-request? :thinking:

**Comment by alittletf** [comment]
I also have this issue. I am sorta new to React Navigation so I keep thinking this must be something I am not figuring out.  

When looking at the DrawerItem.tsx code, I see this: 

```
          <View
            style={[
              styles.label,
              { marginLeft: iconNode ? 32 : 0, marginVertical: 5 },
            ]}
          >
```

`iconNode` is the variable representing whatever I pass in the `icon` prop from <DrawerItem/>. 

So there is no way for me to pass an icon to <DrawerItem/> and change that 32 marginLeft?

**Comment by anisbouzahar** [comment]
> I also have this issue. I am sorta new to React Navigation so I keep thinking this must be something I am not figuring out.
> 
> When looking at the DrawerItem.tsx code, I see this:
> 
> ```
>           <View
>             style={[
>               styles.label,
>               { marginLeft: iconNode ? 32 : 0, marginVertical: 5 },
>             ]}
>           >
> ```
> 
> `iconNode` is the variable representing whatever I pass in the `icon` prop into DrawerItem.
> 
> So there is no way for me to pass an icon to and change that 32 marginLeft?

The order should be reversed for the style array, any progress on this?

**Comment by sclavijo93** [comment]
Hi, is a negative margin the only solution here? :(
