### ISSUE TITLE
Issue with snapshot testing with Navigator

### ISSUE THREAD

**Issue by jonniebigodes** [react-navigation/react-navigation#7906]
**Current Behavior**

While working on a [pr for expo](https://github.com/expo/expo/pull/7302)  and the [issue](https://github.com/expo/expo/issues/7155) that kickstarted the endeavour in order to update their tabbed template i'm currently experiencing some issues with implementing a suitable test for a user that will consume said template and get it running without having problems. 

As the user will have issues with the snapshots each time he runs the tests as the key prop is constantly being regenerated and i've checked your documentation/examples for a suitable solution to overcome this and also did some research and came up dry. I know for a fact in version 4 there was a helping tool, more specifically `NavigationTestUtils` and that's now deprecated. 

So with this a viable solution would be to steer clear of snapshot testing alltogether or could you show me a viable solution to mock the Navigation so that when the user initializes the an app with the said template he/she could use snapshot testing without issues. And also keep the testing implementation simple/clean and effecient without having to introduce unecessary logic by introducing for instance pattern matching.

A side note. I still have to commit a small change to `package.json` in the mentioned pr with the following:
```json
"jest": {
    "preset": "jest-expo",
    "transformIgnorePatterns": [
      "node_modules/(?!(jest-)?react-native|react-clone-referenced-element|@react-native-community|expo(nent)?|@expo(nent)?/.*|react-navigation|@react-navigation/.*|@unimodules/.*|unimodules|sentry-expo|native-base)"
    ]
  },
```
But the same applies locally.

**Expected Behavior**

Me or another user should be able to use snapshot testing without having to introduce the `-u` flag in the scripts or having to use pattern matching.

**How to reproduce**

Not applicable 

**Your Environment**

This is not applicable as it's related to any app initialization of the expo template which is updated with the latest package versions.

| software                      | version |
| ----------------------------- | ------- |
| iOS or Android                |
| @react-navigation/native      |
| @react-navigation/bottom-tabs |
| react-native-screens          |
| react-native                  |
| expo                          |
| node                          |
| npm or yarn                   |

Feel free to provide feedback.

**Comment by satya164** [comment]
You can mock the `shortid` module to generate stable keys. However I don't think it provides any advantage in snapshot testing built-in navigation components like tab bar except adding noise. You should probably mock bottom tabs.

**Comment by jonniebigodes** [comment]
@satya164 thank you for your answer. But a couple more follow up questions:

- Regarding this
  > You can mock the shortid module to generate stable keys.
  
   Care to point where it's located? Or what is the exact react navigation package that needs to be mocked?
 - Regarding this:
   >  You should probably mock bottom tabs.

   If you take a closer look that the pr in question and the code itself you'll see that the bottom tabs are being mocked.
