### ISSUE TITLE
Removing a parameter with setParams

### ISSUE THREAD

**Issue by LinusU** [react-navigation/react-navigation#7909]
**Current Behavior**

I'm trying to remove a parameter passed to a route, since it acts like a flag. But my attempt resulted in the parameter showing up in the url as `undefined`:

```js
navigation.setParams({ checkout: undefined })
```

becomes:

`?checkout=undefined&menuType=EatIn`

**Expected Behavior**

I expected the param to be removed, instead of set to `"undefined"`, like so:

`?menuType=EatIn`

**How to reproduce**

- Snack incoming

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Web
| @react-navigation/native       | 5.1.3 
| @react-navigation/stack        | 5.2.6
| react-native-gesture-handler   | 1.5.6
| react-native-safe-area-context | 0.6.0
| react-native-screens           | 2.0.0-alpha.12 
| react-native                   | 0.61.4
| expo                           | 37
| node                           | 12.12.0
| npm or yarn                    | 6.13.6

**Comment by WoLewicki** [comment]
It should be fixed in #7911. Does it solve your issue?

**Comment by LinusU** [comment]
Looks great! Thanks ❤️

**Comment by wmonecke** [comment]
I am seeing this bug again. Anyone else?
