### ISSUE TITLE
Different keyboardHandlingEnabled behavior on ios and android

### ISSUE THREAD

**Issue by frankyjuang** [react-navigation/react-navigation#7912]
**Current Behavior**

On android, the keyboard is not dismiss until the transition end.
On ios, the keyboard is dismiss when the transition start.

**Expected Behavior**

On android, the keyboard should be dismiss when the transition start.

**How to reproduce**

https://snack.expo.io/@milkjobs/android-keyboard-dismiss
1. press edit button. go to edit page
2. focus text input. see keyboard open
3. press back button. go back to home page. see keyboard didn't start dismiss until edit screen is closed

might be related to https://github.com/react-navigation/react-navigation/issues/7875 and https://github.com/react-navigation/react-navigation/pull/7907

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | android
| @react-navigation/native       | latest
| @react-navigation/stack        |
| react-native-gesture-handler   |
| react-native-safe-area-context |
| react-native-screens           |
| react-native                   |
| expo                           |
| node                           |
| npm or yarn                    |

**Comment by frankyjuang** [comment]
having the same issue. another repro https://snack.expo.io/@milkjobs/android-keyboard-not-dismiss

**Comment by durdevic** [comment]
@frankyjuang Have you solved it?

**Comment by frankyjuang** [comment]
can't reproduce anymore
