### ISSUE TITLE
React Navigation v5 does not support the tabbarvisible prop for material top tab navigator

### ISSUE THREAD

**Issue by NishidaRyu416** [react-navigation/react-navigation#7914]
**Current Behavior**
```
screenOptions={({navigation, route}) => ({
      tabBarVisible:
        route.name !== 'Following' && route.name !== 'Recommendation'
          ? false
          : true,
    })}
```
I tried the code below too.
```
tabBarOptions={{
      tabBarVisible: false
    }}
```

Both do not hide the tab.

As I have read the codes of react navigation, this particular prop is not even written in the toptab navigator while it is in bottomtab.
**Expected Behavior**
TopBar should support the prop as previous versions had supported.

**How to reproduce**
You can reproduce this by just following the codes above.
**Your Environment**

| software                            | version |
| ----------------------------------- | ------- |
| iOS or Android                      | ios
| @react-navigation/native            |5.1.3
| @react-navigation/material-top-tabs | v5.1.6
| react-native-tab-view               |
| react-native                        | latest
| expo                                |
| node                                |
| npm or yarn                         | yarn

**Comment by RinorDreshaj** [comment]
I also have the same issue with the material top tab navigator, on version 4 was working quite good

**Comment by azhararmar** [comment]
Same here, how do we hide tab bar for specific screens(s) inside the nested stack navigator.

**Comment by satya164** [comment]
https://reactnavigation.org/docs/hiding-tabbar-in-screens

**Comment by azhararmar** [comment]
Following worked for me.

```
const isTabBarVisible = (route) => {
    const routeName = route.state
        ? route.state.routes[route.state.index].name
        : (route.params ? route.params.screen : 'HomeScreen');
    return !['HideScreen'].includes(routeName);
};

<Tab.Navigator screenOptions={({route}) => ({tabBarVisible: isTabBarVisible(route)})}>
```

**Comment by nrlnv** [comment]
> Following worked for me.
> 
> ```
> const isTabBarVisible = (route) => {
>     const routeName = route.state
>         ? route.state.routes[route.state.index].name
>         : (route.params ? route.params.screen : 'HomeScreen');
>     return !['HideScreen1', 'HideScreen2'].includes(routeName);
> };
> 
> <Tab.Navigator screenOptions={({route}) => ({tabBarVisible: isTabBarVisible(route)})}>
> ```

Hi Friend, could you please provide full example?

**Comment by nrlnv** [comment]
i have same problem, @NishidaRyu416 did you find solution? if yes, please share

**Comment by lil12t** [comment]
> i have same problem, @NishidaRyu416 did you find solution? if yes, please share

https://reactnavigation.org/docs/hiding-tabbar-in-screens/

Separate navigation into stacks:

index.navigation.ts

```tsx
  <Stack.Navigator>
    <Stack.Screen name="Tab" component={TabNavigation} />
    <Stack.Screen name="Home" component={HomeNavigation} />
  </Stack.Navigator>
```
  tab.navigation.ts
  ```tsx
  export const TabNavigation: React.FC = () => {
  return (
    <Tab.Navigator>
      <Tab.Screen
        name="UserTab"
        component={TabScreen}
        options={{
          tabBarLabel:'User'
        }}
      />

    </Tab.Navigator>
  );
};
```

In order to navigate between Stack Navigator and Tab Navigator you should pass nested screen between them

```tsx
 navigate('Tab', { screen: 'UserTab' })
 ```

**Comment by skkshoaib** [comment]
>https://reactnavigation.org/docs/hiding-tabbar-in-screens

This is the worst solution one can come up. How can you put Tab Navigator inside Stack navigator when visually it doesn't make sense.

**Comment by aadelgrossi** [comment]
I switched to materialTopBar yesterday as I wanted the swipe and indicator animations by default, but I need tabBarVisible to hide specific screens of a nested Stack navigator in certain routes. Switching back to BottomTab -_-


> > https://reactnavigation.org/docs/hiding-tabbar-in-screens
> 
> This is the worst solution one can come up. How can you put Tab Navigator inside Stack navigator when visually it doesn't make sense. If I use the above solution then within 1 day, I would have to scratch my head on WHY did I write it like this.

@skkshoaib i agree this is just plain useless for certain cases. I attempted it and had to revert immediately.

**Comment by ZeeshanAhmadKhalil** [comment]
> Following worked for me.
> 
> ```
> const isTabBarVisible = (route) => {
>     const routeName = route.state
>         ? route.state.routes[route.state.index].name
>         : (route.params ? route.params.screen : 'HomeScreen');
>     return !['HideScreen1', 'HideScreen2'].includes(routeName);
> };
> 
> <Tab.Navigator screenOptions={({route}) => ({tabBarVisible: isTabBarVisible(route)})}>
> ```

Its not working for me, from where we are getting `tabBarVisible` prop?

**Comment by laymand-exceed** [comment]
> > Following worked for me.
> > ```
> > const isTabBarVisible = (route) => {
> >     const routeName = route.state
> >         ? route.state.routes[route.state.index].name
> >         : (route.params ? route.params.screen : 'HomeScreen');
> >     return !['HideScreen1', 'HideScreen2'].includes(routeName);
> > };
> > 
> > <Tab.Navigator screenOptions={({route}) => ({tabBarVisible: isTabBarVisible(route)})}>
> > ```
> 
> Its not working for me, from where we are getting `tabBarVisible` prop?

https://reactnavigation.org/docs/4.x/bottom-tab-navigator/#tabbarvisible

**Comment by mazharEteam** [comment]
Simple and working solution if you want to hide tab bar on every screen
Just pass an empty component as a value of tabBar prop to your material top tab navigator

`<Tab.Navigator 
            tabBar={props => {}}
        >`

**Comment by wishfulthinkerme** [comment]
@mazharEteam That's the only hack that worked for me.
