### ISSUE TITLE
useNavigation Hook

### ISSUE THREAD

**Issue by luizandrends** [react-navigation/react-navigation#7915]
Hello guys i'm having a problem with the useNavigation hook.

Error: Couldn't find a navigation object. Is your component inside a screen in a navigator?

`import React from 'react'
import { TouchableOpacity } from 'react-native-gesture-handler'
import { createStackNavigator } from '@react-navigation/stack'
import { useNavigation } from '@react-navigation/native' 

const Stack = createStackNavigator()

import TimeInterval from '../../pages/TimeInterval'

function AppRoutes() {
  const navigation = useNavigation()

    <Stack.Navigator
      screenOptions={{
        headerStyle: { backgroundColor: '#5F27CD' },
        headerTintColor: '#fff',
        headerBackTitleVisible: false,
        headerLeftContainerStyle: { marginLeft: 17 },
      }}
      initialRouteName='Home'
    >
      <Stack.Screen
        name='TimeInterval'
        component={TimeInterval}
        options={{
          title: 'sometitle',
          headerLeft: () => (
            <TouchableOpacity onPress={() => {navigation.navigate('somepage')}}>
              <Icon name='chevron-left' size={25} color='#fff' />
            </TouchableOpacity>
          ),
        }}
      />
  </StackNavigator>
}`

**Comment by compojoom** [comment]
You are trying to use useNavigation already before it has even rendered any navigation. That's why you get this. You can try something like this:
https://reactnavigation.org/docs/navigating-without-navigation-prop#handling-initialization

**Comment by satya164** [comment]
Like the error says, `useNavigation` can only be used inside screens. Use a callback for your options:

```js
options={({ navigation }) => ({ /* whatever */ })}
```
