### ISSUE TITLE
When using ModalPresentationIOS, status bar color does not invert.

### ISSUE THREAD

**Issue by rkrueger11** [react-navigation/react-navigation#7916]
**Current Behavior**

When navigating to a full screen model using the `ModalPresentationIOS` settings.. the status bar becomes illegible since the background becomes black.

![ReactRouterStack](https://user-images.githubusercontent.com/8338328/77971187-0f0ab700-72bc-11ea-9d8a-7eba2aec0117.gif)

**Expected Behavior**

This should invert the status bar to be `light-content` or background should be light. Not sure which is expected on iOS tbh.

**How to reproduce**

On iOS, in light mode, using the example app, select Model Presentation Stack. Click on Push Album. Note the status bar is illegible.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS                 | 13.4
| @react-navigation/native       | 5.1.3
| @react-navigation/stack        | 5.2.8
| react-native-gesture-handler   | ^1.6.1
| react-native-safe-area-context | ^0.7.3
| react-native-screens           | ^2.4.0
| react-native                   |  0.61.5
| expo                           | N/A
| node                           |  v10.15.3
|  yarn                    | 1.18.0

**Comment by denisgoryaynov** [comment]
I have the same issue. Setting `<StatusBar barStyle={'light-content'} />` inside the modal "fixes" it but the status bar doesn't animate between screens if the user swipes down the modal.

This is how it looks like in health app:

![Registrazione-schermo-2020-04-07-alle-21 22 31](https://user-images.githubusercontent.com/16140813/78711114-c33cbb00-7916-11ea-9c0c-6be4d8b3af85.gif)

This is how it looks like when using `ModalPresentationIOS`:

![Registrazione-schermo-2020-04-07-alle-21 25 25](https://user-images.githubusercontent.com/16140813/78711271-fed78500-7916-11ea-9669-3a7815f036dd.gif)

I'm using this code inside 'Home' screen tho change barStyle back to normal but it doesn't get triggered until the user stops dragging and closes the modal:
```
useFocusEffect(
  useCallback(() => {
    StatusBar.setBarStyle(theme.dark ? 'light-content' : 'dark-content');
  }, [theme]),
);
```

**Comment by QQizi** [comment]
@rkrueger11 How do you change the background color when a modal is opened ? 
My background is white somehow.

**Comment by rkrueger11** [comment]
I’m using the example repo as is.

**Comment by simongoot** [comment]
> @rkrueger11 How do you change the background color when a modal is opened ?
> My background is white somehow.

@QQizi In AppDelegate.m you need to define   rootView.backgroundColor.

I did this:
`rootView.backgroundColor = [[UIColor alloc] initWithRed:0.00f green:0.00f blue:0.00f alpha:1]; // Black Root view background for ModalPresentation transition`

**Comment by shrynshjn** [comment]
> > @rkrueger11 How do you change the background color when a modal is opened ?
> > My background is white somehow.
> 
> @QQizi In AppDelegate.m you need to define rootView.backgroundColor.
> 
> I did this:
> `rootView.backgroundColor = [[UIColor alloc] initWithRed:0.00f green:0.00f blue:0.00f alpha:1]; // Black Root view background for ModalPresentation transition`

Thank you, this worked for me.

**Comment by amerllica** [comment]
I really love _**iOS Developers**_ ❤️

**Comment by amerllica** [comment]
I really love _**iOS Developers**_ ❤️ 


@simongoot

**Comment by charles-goode** [comment]
@simongoot Any idea if changing that rootView background color is possible within JS? I'm working on an expo managed project and would love for this to look so native.

**Comment by satya164** [comment]
https://github.com/react-navigation/react-navigation/commit/a204edd012060f0816eddee7a093183aa379d049


https://user-images.githubusercontent.com/1174278/111003866-3d2bbe80-8388-11eb-8a33-edc2dad4ea9b.mp4

**Comment by 1111mp** [comment]
@satya164 Has it been resolved in the latest version?
```
    "@react-native-community/masked-view": "^0.1.10",
    "@react-navigation/native": "^5.9.3",
    "@react-navigation/stack": "^5.14.3",
    "react": "17.0.1",
    "react-native": "0.64.0",
    "react-native-gesture-handler": "^1.10.3",
    "react-native-reanimated": "^2.0.1",
    "react-native-screens": "^2.18.1"
```
This is the version information I use, this kind of problem still exists.
![image](https://user-images.githubusercontent.com/31227919/112754916-f210dd00-9010-11eb-8a00-02c729c4dca6.png)

**Comment by 1111mp** [comment]
@satya164 I followed the patch code you provided to make changes, but I found a problem in dark mode：

https://user-images.githubusercontent.com/31227919/116900439-50ae2400-ac6b-11eb-93d8-6ae160a6e24c.mov

Then I traced the code of this file (stack/src/views/ModalStatusBarManager.tsx):
```
  // ......
  
  // if (dark) {
  //   return null;
  // }

  if(isDark) {
    return null
  }

  return (
    <StatusBar animated barStyle={isDark ? 'dark-content' : 'light-content'} />
  );
}
```
Because the value of dark is always false.

**Comment by Milker90** [comment]
"react-native": "0.64.1"
"@react-navigation/native": "^5.9.4",
"@react-navigation/stack": "^5.14.5",

I solved this problem by referring to the official website. [https://reactnavigation.org/docs/status-bar/#tabs-and-drawer](url)

we can custom a statusbar component like this
```
import * as React from 'react';
import { StatusBar } from 'react-native';
import { useIsFocused } from '@react-navigation/native';

function FocusAwareStatusBar(props) {
  const isFocused = useIsFocused();

  return isFocused ? <StatusBar {...props} /> : null;
}
```
use it in the modal screen or where you like
```
<SafeAreaView style={[styles.container, { backgroundColor: '#ecf0f1' }]}>
    <FocusAwareStatusBar barStyle="dark-content" backgroundColor="#ecf0f1" />
    <Text>Dark Screen</Text>
    <Button
        title="Next screen"
        onPress={() => navigation.navigate('Screen1')}
    />
</SafeAreaView>
```

**Comment by andrewdang17** [comment]
I'm on the latest versions and I still have this problem
```
    "@react-navigation/native": "^6.0.10",
    "@react-navigation/native-stack": "^6.6.2",
    "@react-navigation/stack": "^6.2.1",
