### ISSUE TITLE
Unable to resolve "./getChildEventSubscriber" after update to v4.3.5

### ISSUE THREAD

**Issue by antoniro** [react-navigation/react-navigation#7917]
I am getting the following error when trying to run my app on the Android Simulator (from Android studio).

`Unable to resolve "./getChildEventSubscriber" from "node_modules\@react-navigation\core\lib\module\getChildNavigation.js"`

I started getting this error just after updating to v4.3.5 (from 4.2.2)

Note that I am using the Expo Framework.

I tried re-installing everything, even the expo framework but I am still having the same issue.

I took a look at the diff between v4.3.5 and v.4.2.2 and noticed that `getChildEventSubscriber` in the file `getChildNavigation` was renamed to something else. I don't know if that change is relevant or not.

**Comment by shlaing** [comment]
SOS !!! same issue with you @antoniro

**Comment by ahilles107** [comment]
same HERE!

**Comment by satya164** [comment]
https://reactnavigation.org/docs/troubleshooting#im-getting-an-error-unable-to-resolve-module-after-updating-to-the-latest-version

**Comment by AakashPat** [comment]
Facing the same issue.
Unable to resolve "./getChildEventSubscriber" from "node_modules/@react-navigation/core/lib/module/getChildNavigation.js"

![image](https://user-images.githubusercontent.com/10728448/78457818-a318bc00-76ca-11ea-973d-1bcfc304048f.png)


    "expo": "^37.0.0"
    "react": "16.9.0"
    "react-navigation": "^4.3.7"

**Comment by AakashPat** [comment]
> https://reactnavigation.org/docs/troubleshooting#im-getting-an-error-unable-to-resolve-module-after-updating-to-the-latest-version

This does not seem to fix it. I usually start my expo server with -c anyway. And this does not seem to fix the issue.

**Comment by Vanns35** [comment]
Same here? Tried all solutions.. restart.. reinstall.. cache clean.. any solution?

**Comment by fangcaiwen** [comment]
SOS !!! same issue

**Comment by jeremyfrancis** [comment]
SAAAAME! dwiuhdiwuhduihiuhdihusa X_X
