### ISSUE TITLE
Safearea is not respected if the header/tab bar is hidden

### ISSUE THREAD

**Issue by tankpower1** [react-navigation/react-navigation#7918]
**Current Behavior**

Hello,
currently i have a stack screen which has his header hidden but then the screen doesn't respect the top notch. Same goes for screens without a bottom tab bar they don't seem to respect the bottom button. Adding SafeAreaView where needed seems to just add extra padding and breaks layout...

Also forceInset on SafeAreaView doesn't work.

**Expected Behavior**

- What do you expect should be happening?
- Include a screenshot or video if it makes sense.

**How to reproduce**

- You must provide a way to reproduce the problem. If you are having an issue with your machine or build tools, the issue belongs on another repository as that is outside of the scope of React Navigation.
- Either re-create the bug on [Snack](https://snack.expo.io) or link to a GitHub repository with code that reproduces the bug.
- Explain how to run the example app and any steps that we need to take to reproduce the issue from the example app.
- Keep the repro code as simple as possible, with the minimum amount of code required to repro the issue.
- Before reporting an issue, make sure you are on latest version of the package.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | IOS
| @react-navigation/native       | 5.1.3
| react-native                   | 0.62.0
| npm or yarn                    | yarn

**Comment by sjungwirth** [comment]
@tankpower1  did you find a solution for this? I'm having the same issue. I wanted to import the HeaderShownContext but it doesn't seem to work.
