### ISSUE TITLE
Keyboard does not dismiss on opening modal after submitting TextInput with blurOnSubmit={false}

### ISSUE THREAD

**Issue by tacomanator** [react-navigation/react-navigation#7919]
**Current Behavior**

On a screen with a `TextInput` with `blurOnSubmit={false}`, after submitting the `TextInput`, subsequently opening a modal does not dismiss the keyboard.

![ezgif-2-b320059e6698](https://user-images.githubusercontent.com/63794/77997787-f3121e80-736a-11ea-83da-80dd3c939857.gif)

(in this example, the `window.alert` message is called in the TextInput's `onSubmitEditing` method.. also, it as can be seen, it doesn't dismiss even after visiting the child and coming back).

**Expected Behavior**

They keyboard should be dismissed (as it is if the modal is opened *prior* to submitting the field).

**How to reproduce**

https://github.com/tacomanator/modalkeyboardtest

run the example in the iOS simulator
type some text in the field
submit (by pressing enter)
dismiss the subsequent alert
the input should still have focus (due to `blurOnSubmit={false}`)
press the Open Modal button

The keyboard does not dismiss.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | iOS |
| @react-navigation/native       | 5.0.0 |
| @react-navigation/stack        | 5.0.0 |
| react-native-gesture-handler   | 1.6.1 |
| react-native-safe-area-context | 0.6.4 |
| react-native-screens           | 2.4.0 |
| react-native                   | 36.0.0 |
| expo                           | 36.0.0 |
| node                           | 13.6.0 |
| npm or yarn                    | 6.14.4 |

The example repo uses a slightly different version of gesture handler and safe area context than what is listed here but the issue is reproducible with both.

**Comment by kaioduarte** [comment]
Hi @tacomanator, I guess this error is related to RN itself, if you take a look in [Keyboard Snack example from docs](https://reactnative.dev/docs/keyboard) there is this bug in iOS. I'm not able to test iOS, could you downgrade RN to detect when this bug was introduced?

**Comment by tacomanator** [comment]
Tested on latest RN 0.62.1 and was not reproducible. I will wait for expo to upgrade to newer RN and try again. Thank you!

**Comment by HodgertA** [comment]
I am still seeing this issue. When typing a textinput in a modal and I press a button inside the modal to open a new modal, the to open a new modal the keyboard disappears, but after I close the modal they keyboard reappears on the initial modal


https://github.com/react-navigation/react-navigation/assets/71614738/c52252c6-802f-4391-9a1f-d5a5c35ca718
