### ISSUE TITLE
TypeError: func.apply is not a function.(In 'func.apply(context, funcArgs)', 'func.apply is undefined)

### ISSUE THREAD

**Issue by gvsakhil** [react-navigation/react-navigation#7920]
**Current Behavior**

<img width="350" alt="Screenshot 2020-03-31 at 5 34 16 PM" src="https://user-images.githubusercontent.com/40195211/78024559-33c36500-7376-11ea-92d5-d8c171d7bfa5.png">

```
async function logout() {
    try {
      setSpinner(true);
      setSpinner(false);
      props.navigation.navigate('LoginStack');
    } catch (e) {
      console.log(e);
    }
  }
```

**Expected Behavior**

### **It should go to login screen**

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
"react" | "16.9.0"
"react-native" | "0.61.5"
"react-navigation" | "^4.3.5"
"react-navigation-drawer" | "^2.3.3"
"react-navigation-material-bottom-tabs" | "^2.1.5"
"react-navigation-stack" | "^1.10.3"

**Comment by satya164** [comment]
Closing due to no response.

**Comment by maxconnectAbhi** [comment]
same error
any solution ?

**Comment by pratik007kumar** [comment]
same error
any solution ?
