### ISSUE TITLE
 Unable to resolve module `shortid` from `node_modules/@react-navigation/routers/src/BaseRouter.tsx`

### ISSUE THREAD

**Issue by cristianoccazinsp** [react-navigation/react-navigation#7921]
Sorry for not following the template, but this is quite trivial and I don't think the template info is needed.

After doing the following upgrade, something broke with the dependencies:

-    "@react-navigation/compat": "5.1.6",
-    "@react-navigation/native": "5.1.3",
-    "@react-navigation/stack": "5.2.8",
+    "@react-navigation/compat": "5.1.7",
+    "@react-navigation/native": "5.1.4",
+    "@react-navigation/stack": "5.2.9",

error: bundling failed: Error: Unable to resolve module `shortid` from `node_modules/@react-navigation/routers/src/BaseRouter.tsx`: shortid could not be found within the project.

Tracing this back, looks like "@react-navigation/core" removed the `shortid` dependency, but it is still used.  What happened?

Work around: install the dependency manually.

**Comment by satya164** [comment]
It's not used. Please clear your cache https://reactnavigation.org/docs/troubleshooting#stale-cache-of-metro-bundler

**Comment by cristianoccazinsp** [comment]
Will try again, but I have already deleted the whole node_modules folder and it is still happening.  

Any chance someone forgot to remove it from a file? Perhaps a missing version bump to any of those packages?

**Comment by cristianoccazinsp** [comment]
No luck, tried with --reset-cache and wiping out the node_modules folder and I'm still getting the above error.

**Comment by satya164** [comment]
You can check the code in the repo that `shortid` isn't used anywhere. So it's likely some kind of cache.

**Comment by cristianoccazinsp** [comment]
You are right, not even the file reported with the error has the actual import. I have no idea where it is coming from.

**Comment by satya164** [comment]
Try restarting your computer too

**Comment by cristianoccazinsp** [comment]
Looks like `npm start -- --reset-cache` was the solution (note the extra --). Either that, or manually re-saving each of the files with conflicts ( I guess the last modified date didn't change so npm didn't pick it up?)

**Comment by adasinio97** [comment]
same here after updating packages with npm install

**Comment by konieczka** [comment]
You can also try shift+r in CLI if `npm start -- --reset-cache` didn't do the trick.

**Comment by OscarYuen** [comment]
still no luck after trying expo start -c

**Comment by NaNtrack** [comment]
npm i --save-dev shortid@2.2.15

**Comment by coolvasanth** [comment]
@NaNtrack Did it worked for you ?

**Comment by NaNtrack** [comment]
> @NaNtrack Did it worked for you ?

yes, it fixed my issue

**Comment by andrey010** [comment]
> npm i --save-dev shortid@2.2.15

It helped me

**Comment by rashtell** [comment]
npm start -- --reset-cache 
worked for me

**Comment by raajnadar** [comment]
I will lock this thread because we already have many solution to resolve this issue.
