### ISSUE TITLE
Question: How to get the actual stack of a StackNavigator?

### ISSUE THREAD

**Issue by IgorBelyayev** [react-navigation/react-navigation#7924]
How can I get the actual stack of a `StackNavigator`? Specifically, I want to inspect the current screens on the stack in order to decide which route my application needs to navigate to. 

For example, if my stack contains screens [A, B, C] and I want to Navigate to screen B, I would like to simply pop the stack in order to get to screen B (and have a resulting stack of [A, B]). However if my stack contains screens [A, C] and I want to navigate to screen B, I would decide to push screen B (and end up with stack [A, C, B]).

I'm not seeing anything useful in the `navigation` prop.

**Comment by compojoom** [comment]
Well, your example is simple enough that you could just use navigation.navigate. It will pop the screen if it needs to go back and it will push the new one if it is not in the stack.

**Comment by satya164** [comment]
Yes and there is `navigation.dangerouslyGetState()` when you actually need it.
