### ISSUE TITLE
Passing function thought route params shows warning about not doing it

### ISSUE THREAD

**Issue by rkostrab** [react-navigation/react-navigation#7925]
**Current Behavior**

When I try to pass a function in route params, it's working fine but I'm getting a warning message that I cannot pass a function or other non-serializable objects.

Full warning text:
```
Non-serializable values were found in the navigation state, which can break usage such as persisting and restoring state. This might happen if you passed non-serializable values such as function, class instances etc. in params. If you need to use components with callbacks in your options, you can use 'navigation.setOptions' instead. See https://reactnavigation.org/docs/troubleshooting#i-get-the-warning-non-serializable-values-were-found-in-the-navigation-state for more details.

```
**Why I need to pass function?** I have TabNavigator nested in StackNavigator. I need to control parent StackNavigators's navbar (headers and title) e.g. change icon and press handler directly from button situated in specific tab. 

I also posted this to StackOverflow:
https://stackoverflow.com/questions/60954742/how-to-pass-parent-function-to-child-screen-in-react-navigation-5

**Expected Behavior**

Warning should not show.

**How to reproduce**

Here in example code I want to change from XXXXXXXX to YYYYYYYYY:
``` js
const TabA = ({ route }) => (
    <View>
        <Text>Tab A</Text>
        <Button title="Change header" onPress={() => route.params.setHeaderRightName("YYYYYYYYY")}/>
    </View>
)

const TabB = () => <><Text>Tab B</Text></>

const Tabs = createBottomTabNavigator();
const TabsNavigator = ({ navigation }) => {
    const [headerRightName, setHeaderRightName] = useState("XXXXXXXX");
    
    useLayoutEffect(() => navigation.setOptions({
        headerRight: () => <MyNavIcon name={headerRightName}/>
    }), [headerRightName]);
    
    return (
        <Tabs.Navigator>
            <Tabs.Screen name="tab-a" component={TabA} initialParams={{ setHeaderRightName }} />
            <Tabs.Screen name="tab-b" component={TabB} />
        </Tabs.Navigator>
    );
}

const Stack = createStackNavigator();
export default App = () => (
    <NavigationContainer>
        <Stack.Navigator>
            <Stack.Screen name="tabs" component={TabsNavigator} />
            <Stack.Screen name="another-screen" component={AnotherScreen} />
        </Stack.Navigator>
    </NavigationContainer>
)
```

**Your Environment**

| software                      | version |
| ----------------------------- | ------- |
| Android                | 10
| @react-navigation/native      | 5.1.3
| @react-navigation/bottom-tabs | 5.2.4
| react-native-screens          | 2.4.0
| react-native                  | 0.61.5
| expo                          | ejected
| node                          | v13.11.0
| npm or yarn                   | 1.22.4

**Comment by satya164** [comment]
At least read the warning and the link in the warning.

**Comment by rkostrab** [comment]
@satya164  Yes or No:  **It is okay to pass functions thought route params?** 
I don't use state persistence or deep link.

**Comment by Wangzihao5325** [comment]
how to comprehend "If you don't use state persistence or deep link to the screen which accepts functions in params, then the warning doesn't affect you and you can safely ignore it." in the link?
 what's meaning of 'state persistence or deep link to the screen'?

**Comment by Joshandrews43** [comment]
+1 here

**Comment by achuraevreal** [comment]
class MainScreen extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      title: null
    };

    this.updateTitle = this.updateTitle.bind(this);
  }

  updateTitle(title) {
    this.setState({title: title});
  }

  render() {
    return (
      <NavigationContainer>
        <Stack.Navigator>
          <Stack.Screen 
          name="NewScreen"
          options={{
            headerShown: true,
            headerTitle: this.state.title
          }}>
            {(props) => <NewScreen  {...props} updateTitle={this.updateTitle}/>}
          </Stack.Screen>
        </Stack.Navigator>
      </NavigationContainer>
    );
  }
}
