### ISSUE TITLE
Error while testing due to stackNavigator

### ISSUE THREAD

**Issue by CamilleLeRoux** [react-navigation/react-navigation#7927]
**Current Behavior**

 `FAIL  src/App.spec.js`
  `● Console`

    console.error node_modules/react/cjs/react.development.js:167
      Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

      Check the render method of `Card`.
          in Card (created by CardContainer)
          in CardContainer (created by CardStack)
          in View (created by View)
          in View (created by MaybeScreen)
          in MaybeScreen (created by CardStack)
          in View (created by View)
          in View (created by MaybeScreenContainer)
          in MaybeScreenContainer (created by CardStack)
          in CardStack (created by KeyboardManager)
          in KeyboardManager (created by Context.Consumer)
          in RNCSafeAreaView (created by RNCSafeAreaView)
          in RNCSafeAreaView (at src/index.tsx:28)
          in SafeAreaProvider (created by Context.Consumer)
          in SafeAreaProviderCompat (created by StackView)
          in View (created by View)
          in View (created by StackView)
          in StackView (created by StackNavigator)
          in StackNavigator (created by App)
          in EnsureSingleNavigator (created by ForwardRef(BaseNavigationContainer))
          in ForwardRef(BaseNavigationContainer) (created by ForwardRef(NavigationContainer))
          in ThemeProvider (created by ForwardRef(NavigationContainer))
          in ForwardRef(NavigationContainer) (created by App)
          in App
    console.error node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11944
      The above error occurred in the <View> component:
          in View (created by View)
          in View (created by AnimatedComponent)
          in AnimatedComponent (created by ForwardRef(AnimatedComponentWrapper))
          in ForwardRef(AnimatedComponentWrapper) (created by Card)
          in View (created by View)
          in View (created by Card)
          in Card (created by CardContainer)
          in CardContainer (created by CardStack)
          in View (created by View)
          in View (created by MaybeScreen)
          in MaybeScreen (created by CardStack)
          in View (created by View)
          in View (created by MaybeScreenContainer)
          in MaybeScreenContainer (created by CardStack)
          in CardStack (created by KeyboardManager)
          in KeyboardManager (created by Context.Consumer)
          in RNCSafeAreaView (created by RNCSafeAreaView)
          in RNCSafeAreaView (at src/index.tsx:28)
          in SafeAreaProvider (created by Context.Consumer)
          in SafeAreaProviderCompat (created by StackView)
          in View (created by View)
          in View (created by StackView)
          in StackView (created by StackNavigator)
          in StackNavigator (created by App)
          in EnsureSingleNavigator (created by ForwardRef(BaseNavigationContainer))
          in ForwardRef(BaseNavigationContainer) (created by ForwardRef(NavigationContainer))
          in ThemeProvider (created by ForwardRef(NavigationContainer))
          in ForwardRef(NavigationContainer) (created by App)
          in App

      Consider adding an error boundary to your tree to customize error handling behavior.
      Visit https://fb.me/react-error-boundaries to learn more about error boundaries.

  ● renders correctly

    Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

    Check the render method of `Card`.

      at createFiberFromTypeAndProps (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:16616:21)
      at createFiberFromElement (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:16639:15)
      at reconcileSingleElement (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:5425:23)
      at reconcileChildFibers (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:5485:35)
      at reconcileChildren (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7985:28)
      at updateHostComponent (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:8507:3)
      at beginWork$1 (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10083:14)
      at performUnitOfWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14694:12)
      at workLoopSync (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14667:22)
      at performSyncWorkOnRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14366:11)`

When testing with 'npm run test' I have this error but I can't figure why, except the fact that it may be caused by the package StackNavigator

**Expected Behavior**

Being able to pass the tests

**How to reproduce**

Just clone the repo : https://github.com/CamilleLeRoux/navigationTest
And execute npm run test

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Android
| @react-navigation/native       | 5.1.4
| @react-navigation/stack        | 5.2.9
| react-native-gesture-handler   | 1.6.1
| react-native-safe-area-context | 0.7.3
| react-native-screens           | 2.4.0
| react-native                   | 0.62.0
| expo                           |
| node                           | 12.10.0
| npm or yarn                    | npm 6.12.0

**Comment by ralph-dev** [comment]
https://github.com/CamilleLeRoux/navigationTest/blob/master/src/App.js#L15
First of all I don't believe you need to do props => component because that will cause continuous re-renders.

Second to answer your question:
You should just be passing in component={page2} your not allowed to pass JSX as component value.

**Comment by raajnadar** [comment]
@ralph-dev is right, closing this issue.

Also check this @CamilleLeRoux  https://twitter.com/satya164/status/1255277058181251074?s=20

**Comment by hamy-acg** [comment]
Hi @CamilleLeRoux , have you got the solution to fix this issue? I have the same problem here https://github.com/react-navigation/react-navigation/issues/8859
