### ISSUE TITLE
Gesture Disable in V5

### ISSUE THREAD

**Issue by Marzdor** [react-navigation/react-navigation#7928]
**Current Behavior**
```javascript
    <Stack.Navigator
      options={{
        gestureEnabled: false,
        headerShown: false,
        gestureDirection: 'horizontal-inverted',
      }}>
      <Stack.Screen
        name="Videos"
        component={Videos}
        options={{
          headerShown: false,
        }}
      />
      <Stack.Screen
        name="VideoPage"
        component={VideoPage}
        options={{
          headerTitle: '',
          headerBackTitle: ' ',
          headerStyle: {
            backgroundColor: theme.getColor('black', 1),
            shadowColor: 'transparent',
          },
          headerTintColor: theme.getColor('white', 1),
        }}
      />
    </Stack.Navigator>
```

I can't disable the gesture no matter where or what I seem to do

**Expected Behavior**

`options={{gestureEnabled: false}} `should disable the gesture

**How to reproduce**

Create a stack nav like above nested in a tab nav

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | iOS
| @react-navigation/native       |5.1.3
| @react-navigation/stack        |5.2.6
| react-native-gesture-handler   |1.6.1
| react-native-safe-area-context |0.7.3
| react-native-screens           |1.4.0
| react-native                   |.62
| expo                           |n/a
| node                           |13.5
| npm or yarn                    |yarn

**Comment by satya164** [comment]
It's `screenOptions` on `Stack.Navigator`, not `options`

**Comment by aibrahim3546** [comment]
@satya164 but that will disable the entire stack gesture. What if I only want for one particular screen?

**Comment by raajnadar** [comment]
Set the option on `Stack.Screen` and not in the `Stack.Navigator`

**Comment by Dlessi** [comment]
Try this
`
      <Stack.Screen
        name="RootScreen"
        component={RootScreen}
        options={{
           gestureEnabled: false
       }}
      />
`

**Comment by sam1463** [comment]
I'm running into this issue as well. `gesturesEnabled: false` works when it's in `screenOptions` for the navigator, but that disables the gestures for all child screens. If I omit that from `screenOptions` and only set it in `options` for one route, it doesn't work on that route. Tried using `navigation.setOptions` in the component for that screen as well, but still didn't work. Is `gesturesEnabled` only configurable for the entire navigator, and not customizable by route/screen?

**Comment by eakeyson1** [comment]
I am currently facing the same issue and feel like I have tried putting the "gestureEnabled" everywhere but nothing seems to work.

const SellerOrdersStack = createStackNavigator();
const SellerOrdersStackScreen = () => (
  <SellerOrdersStack.Navigator
    screenOptions={{
      headerShown: false,
    gestureEnabled: false,
  }}>
    
    <SellerOrdersStack.Screen name="SellerOrders" component={SellerOrders}
      options={({ navigation }) => ({ 
        headerShown: false,
        gestureEnabled: false,
        })
      }
    />
....

I have tried options in screen and screen options in stack navigator. Weird thing is that "headerShown" works correctly in both. Also, the "gestureEnabled" props doesn't show up like the other props (e.g. headerShown, gestureDirection) in my IDE. Was this prop removed? I am using a tab navigator so this might have something to do with it. Also, in the docs, it does specifically say that gestures aren't supported on web. Could someone clarify this for me?

**Comment by eakeyson1** [comment]
I am facing the same issue. I get the "gestureEnabled" props to show up, so I believe it is in the correct place but it doesn't work. It says this feature isn't supported on web, could someone elaborate more on this? It is supported in the react native environment?

    <SellerOrdersStack.Screen name="SellerOrders" component={SellerOrders} options={{gestureEnabled}}/>

**Comment by Joshandrews43** [comment]
This still does not work in my simulator running V5.

**Comment by PritishSawant** [comment]
This does not work
