### ISSUE TITLE
Nested Navigator with bottom-tab is slow when first time touch and load

### ISSUE THREAD

**Issue by XOneto9** [react-navigation/react-navigation#7929]
Problem:
When I  select Tab Bottom icon button, the reaction to transition view is slow during about 2sec..
just first time.
and then second time touch, it will fast as I feel.
I'm using to real iPhone device to test

the structure of navigation is nested to...

Stack 
  |
TabBottom
  |
Stack(With ModalView)

**Your Environment**

| software                               | version |
| -------------------------------------- | ------- |
| iOS or Android                         | iOS
| @react-navigation/native               | 5.1.1
| @react-navigation/material-bottom-tabs |5.1.4
| react-native-paper                     |3.6.0
| react-native                           |sdk-36.0.1
| expo                                   |36.0.0
| node                                   |13.10.1
| npm or yarn                            |6.13.7

**Comment by prancky** [comment]
@XOneto9 how did you fix it ?

**Comment by XOneto9** [comment]
@prancky 
Hi
Well, that is so long time.
Maybe I remember that i can not solve it. To work smoothly, I think I changed module of navigation to material bottom navigation.

Sorry, I cannot clearly remember..

**Comment by Badopisa** [comment]
Material bottom navigation is really slow on my Android as well.. takes like 2 seconds to load each tab, how can I fix this


import React from 'react';
import {createMaterialBottomTabNavigator} from '@react-navigation/material-bottom-tabs';
import MaterialCommunityIcons from 'react-native-vector-icons/MaterialCommunityIcons';
import Home from './Home';
import Settings from './Settings';
import Store from './Store';
import Cart from './Cart';
const Tab = createMaterialBottomTabNavigator();
export default function BottomTab() {
  return (
    <Tab.Navigator
      initialRouteName="Feed"
      activeColor="white"
      barStyle={{backgroundColor: 'green'}}>
      <Tab.Screen
        name="Home"
        component={Home}
        options={{
          tabBarLabel: 'Home',
          tabBarIcon: ({color}) => (
            <MaterialCommunityIcons name="home-heart" color={color} size={22} />
          ),
        }}
      />
      <Tab.Screen
        name="Notifications"
        component={Store}
        initialRouteName="Home"
        options={{
          tabBarLabel: 'store',
          tabBarIcon: ({color}) => (
            <MaterialCommunityIcons name="basket" color={color} size={22} />
          ),
        }}
      />
      <Tab.Screen
        name="Cart"
        component={Cart}
        options={{
          tabBarLabel: 'Cart',
          tabBarIcon: ({color}) => (
            <MaterialCommunityIcons name="shopping" color={color} size={22} />
          ),
        }}
      />
      <Tab.Screen
        name="Settings"
        component={Settings}
        options={{
          tabBarLabel: 'Settings',
          tabBarIcon: ({color}) => (
            <MaterialCommunityIcons name="cog" color={color} size={22} />
          ),
        }}
      />
    </Tab.Navigator>
  );
}
