### ISSUE TITLE
Removing Top shadow and how top shadow was achieved

### ISSUE THREAD

**Issue by NikhilShisode** [react-navigation/react-navigation#7930]
**Current Behavior**

- Top side of tabBar has shadow.
 ![WhatsApp Image 2020-04-02 at 12 20 17 AM](https://user-images.githubusercontent.com/30415953/78177800-4de76b00-747c-11ea-8cc7-4b3930af55e9.jpeg)

**Expected Behavior**

- how to remove top shadow of top tabBar? 
- tried elevation: 0 but it also removes bottom shadow.
- **Side note** - How top shadow was achieved for Tabs.Navigator (react navigation)? as box-shadow properties does not work for android and elevation only shows shadow to bottom.

**How to reproduce**

```
<>
<Header /> //App name custom component
<Tabs.Navigator
        ...
        tabBarOptions={{
          ....
          style: {
            // elevation: 0, 
          },
        }}>
```

**Your Environment**

| software                            | version |
| ----------------------------------- | ------- |
| iOS or Android                      | android
| @react-navigation/native            |5.1.2
| @react-navigation/material-top-tabs | 5.1.6
| react-native-tab-view               | 2.13.0
| react-native                        |5.1.2
| expo                                |N/A
| node                                |12.16.1
| npm or yarn                         |6.14.3

**Comment by pke** [comment]
@seyedmostafahasani doesn't work in v6.0.9
