### ISSUE TITLE
A warning maybe coming from react navigation 4 on RN 0.62.0

### ISSUE THREAD

**Issue by tankpower1** [react-navigation/react-navigation#7933]
**Current Behavior**

- What code are you running and what is happening?
- Include a screenshot or video if it makes sense.

Hello i'm currently using react-navigation 4 and ever since i updated to react-native 0.62.0 this warning pops up every time i navigate to a screen.

`ReactNativeFiberHostComponent: Calling `getNode()` on the ref of an Animated component is no longer necessary. You can now directly use the ref instead. This method will be removed in a future release.`

**Expected Behavior**

- What do you expect should be happening?
- Include a screenshot or video if it makes sense.

Maybe not get the error if it's from the react-navigation package?

**How to reproduce**

- You must provide a way to reproduce the problem. If you are having an issue with your machine or build tools, the issue belongs on another repository as that is outside of the scope of React Navigation.
- Either re-create the bug on [Snack](https://snack.expo.io) or link to a GitHub repository with code that reproduces the bug.
- Explain how to run the example app and any steps that we need to take to reproduce the issue from the example app.
- Keep the repro code as simple as possible, with the minimum amount of code required to repro the issue.
- Before reporting an issue, make sure you are on latest version of the package.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | both
| react-navigation               | 4.0.10
| react-navigation-stack         | 1.10.3
| react-navigation-tabs          | 2.5.6
| react-navigation-drawer        |
| react-native-reanimated        |
| react-native-gesture-handler   | 1.5.3
| react-native-safe-area-context |
| react-native-screens           |
| react-native                   | 0.62.0
| expo                           |
| node                           |
| npm or yarn                    | yarn

**Comment by malaganator3000** [comment]
I have the same problem. For now it is not a problem, but I would like to know how to request the problem

**Comment by sayem314** [comment]
Yes same for v5 as well.

**Comment by tankpower1** [comment]
Every time i transition to a screen this warning pops up and floods the console.. I can't seem to track where it's coming from, my guess is from react-navigation for now.. could be any other package.

**Comment by sayem314** [comment]
Temporary workaround:

`YellowBox.ignoreWarnings([
  'Calling `getNode()` on the ref of an Animated component is no longer necessary. You can now directly use the ref instead.',
]);`

**Comment by hossein-zare** [comment]
@sayem314 Ignoring warnings is not even a bad idea, but a terrible one.

**Comment by sayem314** [comment]
> @sayem314 Ignoring warnings is not even a bad idea but a terrible one.

Yes, but I was replying on @tankpower1 since he said that his console is being flooded (makes development harder). And it's a TEMPORARY fix for end-users until react-navigation pushes new version with the fix. Ignoring a warning for a short period of time is okay but you should not do this as a patch.

**Comment by luiz-couto** [comment]
I agree with @sayem314  here. The problem cant be fixed right now, so why you need the yellow box showing every time for the same warning? We need to wait for react navigation updates. That's a good temporary workaround.

**Comment by Julian-quintero** [comment]
Having this in rn4 too, will wait for a fix.

**Comment by chamaloriz** [comment]
#To quick fix this go to node_modules/react-native-safe-area-view

at line 192 change

`this.view.getNode().measureInWindow((winX, winY, winWidth, winHeight)`

to

`this.view.measureInWindow((winX, winY, winWidth, winHeight)`

**Comment by betoharres** [comment]
> #To quick fix this go to node_modules/react-native-safe-area-view => index.js
> 
> at line 192 change
> 
> `this.view.getNode().measureInWindow((winX, winY, winWidth, winHeight)`
> 
> to
> 
> `this.view.measureInWindow((winX, winY, winWidth, winHeight)`

for anyone trying this, you can use this to gracefully upgrade it later: https://github.com/ds300/patch-package

**Comment by tankpower1** [comment]
Re-installing the react-navigation (4.0.10) package seemed to fix the problem. Closing the issue.

**Comment by linelson** [comment]
I'm still seeing this with @react-navigation/native v5.1.4. Seems to be caused by https://github.com/react-native-community/react-native-safe-area-view/issues/111.

**Comment by malikimran34** [comment]
me too

Calling `getNode()` on the ref of an Animated component is no longer necessary. You can now directly use the ref instead. This method will be removed in a future release. ReactNativeFiberHostComponent 
    in SafeView (at withOrientation.js:54)
    in withOrientation (created by TabBarBottom)
    in TabBarBottom (created by withDimensions(undefined))
    in withDimensions(undefined) (created by TabNavigationView)
    in TabNavigationView (created by NavigationView)
    in NavigationView (created by Navigator)
    in Navigator (created by SceneView)
    in SceneView (created by CardContainer)
    in CardContainer (created by CardStack)
    in CardStack (created by KeyboardManager)
    in KeyboardManager (created by Context.Consumer)
    in Context.Consumer (created by StackView)
    in StackView (created by StackView)
    in StackView (created by Anonymous)
    in Anonymous (created by Navigator)
    in Navigator (created by SceneView)
    in SceneView (created by Drawer)
    in Drawer (created by DrawerView)
    in DrawerView (created by Navigator)
    in Navigator (created by SceneView)
    in SceneView (created by SwitchView)
    in SwitchView (created by Navigator)
    in Navigator (created by NavigationContainer)
    in NavigationContainer (at App.js:9)
    in App (at renderApplication.js:45)

**Comment by brentvatne** [comment]
a fix for react-native@0.62 is available in react-native-safe-area-view@1.1.0! thanks for the report!

**Comment by schumannd** [comment]
@brentvatne I can see a commit by you with message "Release 1.0.0" but I can't find 1.1.0. Neither are officially released. What is the preferred course of action here?

**Comment by kisakyegordon** [comment]
Upgrade to the latest version of react-navigation - at the time of writing that's 4.3.9. - here.

I had the error popping up on almost every screen - because id last updated the version 9months back - this issue has since been attended to in the latest versions.
