### ISSUE TITLE
Weird behaviour when no header is render and using SafeAreaView from react-native-safe-area-context

### ISSUE THREAD

**Issue by kkusanagi** [react-navigation/react-navigation#7934]
Different behaviour using SafeAreaView from react-native and react-native-safe-area-context

Following the document React Navigation [Supporting safe areas](https://reactnavigation.org/docs/handling-safe-area), we should use SafeAreaView from react-native-safe-area-context. but result is not what i want.
Below is the coding.

```
function HomeNav(){
  return (
    <Tab.Navigator initialRouteName="MultiTab"
      screenOptions={({ route }) => ({
        tabBarIcon: ({ focused, color, size }) => {
          let iconSource;
          let opacity;

          if (route.name === 'ChatTab') {
            iconSource = imgChat;
            opacity = focused ? 1:0.5;
 
          }else if (route.name === 'MultiTab') {
            iconSource = imgGame;
            opacity = focused ? 1:0.5;
            
          }else if (route.name === 'Setting') {
            iconSource = imgSetting;
            opacity = focused ? 1:0.5;          
          }          
          return <Image
            source={iconSource}
            style={[styles.icon,{opacity}]}
          />;

        },
      })}
      tabBarOptions={{
        showLabel:false,
      }}
    >
      <Tab.Screen name="ChatTab" component={ChatTabScreen} />
      <Tab.Screen name="MultiTab" component={MultiTabScreen} />
      <Tab.Screen name="Setting" component={SettingTabScreen} />
    </Tab.Navigator>
  );
}
```

And

```
<SafeAreaProvider>
      <global.AuthContext.Provider value={authContext}>
        <NavigationContainer>
            <Stack.Navigator headerMode="none">
              <Stack.Screen name="Home" component={HomeNav} options={{headerShown:false}} />
            </Stack.Navigator>
        </NavigationContainer>
      </global.AuthContext.Provider>
    </SafeAreaProvider>
```

Result for using SafeAreaView from react-native-safe-area-context

![Simulator Screen Shot - iPhone 11 - 2020-04-02 at 18 07 05](https://user-images.githubusercontent.com/1698343/78238378-183f9200-750f-11ea-8623-0ba03b2b7c7c.png)

You can see the bottom got slightly padding. 
Using SafeAreaView from react-native have no issue for this.

| software                      | version |
| ----------------------------- | ------- |
iOS
    "@react-navigation/bottom-tabs": "^5.2.4",
    "@react-navigation/native": "^5.1.3",
    "@react-navigation/stack": "^5.2.8",
    "react-native-screens": "^2.4.0",
    "react-native-safe-area-context": "^0.7.3",
    "react": "16.9.0",
    "react-native": "^0.60.5",
npm

**Comment by satya164** [comment]
https://reactnavigation.org/docs/handling-safe-area/#tweak-paddings-for-more-control
