### ISSUE TITLE
Android navigation transition is like a modal and cannot be changed

### ISSUE THREAD

**Issue by blazk0** [react-navigation/react-navigation#7935]
**Current Behavior**

When navigating to a new screen, all screen open from bottom to top exactly like a modal.

**Expected Behavior**
In android the default behavior is the transition fades in from the bottom to top but this comes from bottom like a modal and when i add mode="card" nothing changes as well.

![Screen-Recording-1441-08-09-at-1 52 30-PM](https://user-images.githubusercontent.com/36491230/78241675-748fbb00-74e9-11ea-89d0-90722e515368.gif)

**How to reproduce**
*This is Auth Stack *
```javascript
const AuthStack = () => {
  const Stack = createStackNavigator();

  return (
    <Stack.Navigator
      screenOptions={{
        headerTitle: () => <HeaderLogo />,
        headerStyle: styles.header,
        headerTitleAlign: 'center',
      }}>
      <Stack.Screen name="Auth" component={Tab} />

      <Stack.Screen
        name="ForgotPass"
        component={ForgotPass}
        options={{
          headerBackTitle: 'Back',
          headerStyle: globalStyles.header,
        }}
      />

      <Stack.Screen
        name="ForgotPassStep2"
        component={ForgotPassword_Step2}
        options={{
          headerBackTitle: 'Back',
          headerStyle: globalStyles.header,
        }}
      />

      <Stack.Screen
        name="Otp"
        component={Otp}
        options={{
          headerStyle: globalStyles.header,
          headerBackTitle: 'Back',
        }}
      />
    </Stack.Navigator>
  );
};

const Tab = () => {
  const TopTab = createMaterialTopTabNavigator();

  return (
    <TopTab.Navigator
      tabBarOptions={{
        activeTintColor: '#EE05F2',
        inactiveTintColor: 'grey',
        indicatorStyle: styles.indicator,
        style: styles.view,
        pressColor: 'transparent',
      }}>
      <TopTab.Screen name="Login" component={Login} />
      <TopTab.Screen name="Sign Up" component={SignUp} />
    </TopTab.Navigator>
  );
};
```
*and this is the App Container *
```javascript
const index = ({ auth }: Props) => {
  const Stack = createStackNavigator();
  const { loading, userType } = auth;

  return (
    <NavigationContainer ref={navigationRef}>
      <Stack.Navigator screenOptions={{ headerShown: false }}>
        {loading ? (
          <Stack.Screen
            name="Splash"
            component={Splash}
          />
        ) : userType === null ? (
          <Stack.Screen
            name="Auth"
            component={AuthStack}
          />
        ) : (
          <Stack.Screen
            name="BottomTab"
            component={BottomTabs}
            options={{
              headerStyle: styles.header,
              headerTitle: () => <HeaderLogo />,
              headerRight: () => <Notification />,
              headerRightContainerStyle: styles.headerRight,
            }}
          />
        )}
      </Stack.Navigator>
    </NavigationContainer>
  );
};
```

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| Android                 | All versions
| @react-navigation/native       | 5.1.3
| @react-navigation/stack        |  5.2.6
| react-native-gesture-handler   |1.6.1
| react-native-safe-area-context |0.7.3
| react-native-screens           |2.4.0
| react-native                   |0.61.5
| expo                           | ---
| node                           | 10.15.3
| yarn                    |1.22.0

**Comment by satya164** [comment]
Read the docs before opening issues, please.

https://reactnavigation.org/docs/stack-navigator#animations

**Comment by blazk0** [comment]
> Read the docs before opening issues, please.
> 
> https://reactnavigation.org/docs/stack-navigator#animations

I have already tried that, it doesnot work..

**Comment by blazk0** [comment]
straight from the docs 
By default the stack navigator is configured to have the familiar iOS and Android look & feel: new screens slide in from the right on iOS, fade in from the bottom on Android. On iOS the stack navigator can also be configured to a modal style where screens slide in from the bottom.

**Comment by satya164** [comment]
Did you even read the section I linked to? Please spend some time reading docs before opening issues. We don't have a lot of capacity to answer every question.

**Comment by blazk0** [comment]
> Did you even read the section I linked to? Please spend some time reading docs before opening issues. We don't have a lot of capacity to answer every question.

Have you seen the gif ??, is this the default behavior ??

**Comment by rphlmr** [comment]
> > Did you even read the section I linked to? Please spend some time reading docs before opening issues. We don't have a lot of capacity to answer every question.
> 
> Have you seen the gif ??, is this the default behavior ??

For me, yes it's the expected behaviour ;) 

> Tab navigator nested inside the initial screen of stack navigator - New screens cover the tab bar when you push them.

https://reactnavigation.org/docs/nesting-navigators#parent-navigators-ui-is-rendered-on-top-of-child-navigator

**Comment by ljuborados** [comment]
@rphlmr @satya164  um, this definitely isn't the Android default transition, and it never was.
Cmon, there's no fade going on here, and it's pretty visible in the gif.
I know you guys are trying to close issues but this isn't the best way..

**Comment by satya164** [comment]
I use Android on Pixel (have been using Android devices with as Stock OS as possible for years) as my primary device and copied the transitions as close as I could. Every version of Android has different transitions and this is the default Animation from Android 9. If you think it's definitely not, then feel free to open an issue/PR with the default transition.

Regardless, fade transitions are pretty buggy with elevations in React Native so that's not something usable to make a default.
