### ISSUE TITLE
header not appearing on Any of the screens created using Drawer.Screen

### ISSUE THREAD

**Issue by jatin28** [react-navigation/react-navigation#7937]
**Current Behavior**
no header appearing even after setting props like options={{title: 'Home'}} inside drawer navigator.
- What code are you running and what is happening?
export function AppDrawer() {
  return (
    <NavigationContainer>
      <Drawer.Navigator
        drawerContent={props => <CustomDrawerContent {...props} />}
        contentComponent={DrawerContent}
        initialRouteName="Home"
        drawerContentOptions={{
          activeTintColor: '#e91e63',
          itemStyle: {marginVertical: 30},
          style: {backgroundColor: '#8a8a8a'},
          labelStyle: {color: 'white'},
        }}>
        <Drawer.Screen
          name="Home"
          component={Root}
          options={{title: 'Homeeee'}}
          screenOptions={{headerMode: 'screen'}}
        />
        <Drawer.Screen
          name="Info"
          component={HomeScreen}
          // options={{drawerLabel: 'Plant Information', headerTitle: 'test'}}
          // navigationOptions={{drawerLabel: 'Home', headerTitle: 'test'}}
        />
        <Drawer.Screen
          name="Report"
          component={SignInScreen}
          options={{drawerLabel: 'Report a Problem', headerTitle: 'test'}}
          navigationOptions={{drawerLabel: 'Home', headerTitle: 'test'}}
        />
        <Drawer.Screen
          name="Settings"
          component={SignInScreen}
          options={{drawerLabel: 'Settings', headerTitle: 'test'}}
          navigationOptions={{drawerLabel: 'Home', headerTitle: 'test'}}
        />
      </Drawer.Navigator>
    </NavigationContainer>
  );
}

- Include a screenshot or video if it makes sense.

![Screenshot_1585832219](https://user-images.githubusercontent.com/2936483/78251904-a74caa00-750f-11ea-91e8-4813593be519.png)

**Expected Behavior**

header should appear with the assigned title props.

- What do you expect should be happening?
- Include a screenshot or video if it makes sense.

**How to reproduce**

- You must provide a way to reproduce the problem. If you are having an issue with your machine or build tools, the issue belongs on another repository as that is outside of the scope of React Navigation.
- Either re-create the bug on [Snack](https://snack.expo.io) or link to a GitHub repository with code that reproduces the bug.
- Explain how to run the example app and any steps that we need to take to reproduce the issue from the example app.
- Keep the repro code as simple as possible, with the minimum amount of code required to repro the issue.
- Before reporting an issue, make sure you are on latest version of the package.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | both (Android apiv29, iOS 13)
| @react-navigation/native       |     "@react-navigation/native": "^5.0.8"
| @react-navigation/drawer       |     "@react-navigation/drawer": "^5.1.0"
| react-native-reanimated        |     "react-native-reanimated": "^1.7.0"
| react-native-gesture-handler   |      "react-native-gesture-handler": "^1.6.0"
| react-native-safe-area-context |     "react-native-safe-area-context": "^0.7.3",
| react-native-screens           |     "react-native-screens": "^2.4.0"
| react-native                   |     "react-native": "0.61.5"
| expo                           | N/A
| node                           | v13.12.0
| npm or yarn                    | v1.22.4

**Comment by jatin28** [comment]
@satya164 / @osdnk any idea about the above issue?

**Comment by kienlv58** [comment]
I have same issue. My solution is wrapper each screen with each stack navigator or custom header. But I think the author needs to fix

**Comment by diegolaciar** [comment]
+1  the same bug. screen header not appear on drawer.

**Comment by satya164** [comment]
Drawer doesn't have header. Use a custom header component or nest stack navigator inside the screens.

**Comment by JulianKingman** [comment]
This has always been confusing to me, is there a reason the drawer and tab navigators don't have headers? Shouldn't they have headers? Wrapping each route in a stack navigator adds many uncessary components to the tree.
