### ISSUE TITLE
Problems when nesting Stack Navigator in Drawer Navigator

### ISSUE THREAD

**Issue by PlinioMayer** [react-navigation/react-navigation#7940]
I am trying to update the react navigation from 3.x to 5.x.

**Current Behavior**

I have an authentication flow in a stack navigator as follows

![Routes](https://user-images.githubusercontent.com/55549580/78322291-ae41df80-7544-11ea-83ea-d863368a0f4d.png)

The problem appears when I'm in the "HomeNavigation":

![HomeNavigation](https://user-images.githubusercontent.com/55549580/78322500-48098c80-7545-11ea-87d0-cb046bd63743.png)

Which opens normally in the HomeStack and navigates through all the stacks, excpet one, the UserSignatureStack: 

![UserSignatureStack](https://user-images.githubusercontent.com/55549580/78322627-adf61400-7545-11ea-86e4-1c870d1d99ce.PNG)

Here it opens as it should, but I can't go anywhere from here, it just crashes. If I try to move to any screen in the same stack with "navigation.navigate" it accuses a problem in the Stack Navigator (UserSignatureStack) and gives me:

```
cb is not a function. (In 'cb(event)', 'cb' is undefined)
- node_modules\@react-navigation\core\src\useEventEmitter.tsx:120:15 in React.useCallback$argument_0
* [native code]:null in forEach
- node_modules\@react-navigation\core\src\useEventEmitter.tsx:118:16 in React.useCallback$argument_0
- node_modules\@react-navigation\core\src\useFocusEvents.tsx:65:4 in React.useEffect$argument_0
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:16921:31 in commitHookEffectList
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:16970:29 in commitPassiveHookEffects
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:307:15 in invokeGuardedCallbackImpl
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:531:36 in invokeGuardedCallback
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:20061:28 in flushPassiveEffectsImpl
* [native code]:null in flushPassiveEffectsImpl
- node_modules\scheduler\cjs\scheduler.development.js:643:23 in unstable_runWithPriority
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:19597:25 in scheduleCallback$argument_1
- node_modules\scheduler\cjs\scheduler.development.js:482:68 in flushTask
- node_modules\scheduler\cjs\scheduler.development.js:607:20 in flushWork
- node_modules\scheduler\cjs\scheduler.development.js:58:18 in _flushCallback
- node_modules\react-native\Libraries\Core\Timers\JSTimers.js:146:14 in _callTimer
- node_modules\react-native\Libraries\Core\Timers\JSTimers.js:399:17 in callTimers
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:436:47 in __callFunction
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:111:26 in __guard$argument_0
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:384:10 in __guard
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:110:17 in __guard$argument_0
* [native code]:null in callFunctionReturnFlushedQueue
```

And when I try to go back a get the same, but with a problem in the Drawer Navigator (HomeNavigation).

**Expected Behavior**

I just wanted to go from one screen to another. 

**Your Environment**

| Android                 | SDK 28|
| @react-navigation/native       | 5.1.4 |
| @react-navigation/stack        | 5.2.9 |
| @react-navigation/drawer        | 5.4.0 |
| react-native-gesture-handler   | 1.6.0 |
| react-native-safe-area-context | 0.7.3 |
| react-native-screens           | 2.2.0 |
| react-native                   | 61.4 |
| expo                           | 37 |
| node                           | 12.9.0 |
| npm or yarn                    | yarn |

**Comment by PlinioMayer** [comment]
Forget it, I was passing a non existing function to "addListener()".

**Comment by goransiriev** [comment]
How you solve the problem? 
What you mean (I was passing a non existing function to "addListener()".)
