### ISSUE TITLE
Screen content flickers/resets positioning when calling goBack

### ISSUE THREAD

**Issue by declanelcocks** [react-navigation/react-navigation#7941]
I have a simple `Stack.Screen` which has the code below which will produce something similar to a bottom sheet. It essentially behaves like a bottom sheet too, so when you drag the content down, it will translate it as you drag and clamp to the bottom of the screen when reaching the `closeLimit`. At that point it will call `navigation.goBack`. This is all handled by the `translateY` value.

**Current Behavior**

When `navigation.goBack` is called, there's something which is resetting this `translateY` value somehow. Even when debugging, the value of `translateY` never seems to be reset to `0`, but the content of the page resets to its initial state for a split second before the `goBack` animation kicks in.

I even removed the actual line in `@react-navigation/stack/src/views/Stack/Card.tsx` which triggers this animation (`componentDidUpdate => animate(...)`) and I can see that the content resets to its initial position when `.goBack` is called.

Could anyone help to see why this would happen? What would cause the entire page to reset to its initial positioning/state before carrying out the `goBack` process and animation?

**Expected Behavior**

I expect that the content will STAY clamped to the bottom and the animation will simply slide it off the screen from that clamped position, or wherever it may be as a result of `translateY`'s value. I do not expect to see it reset to its original position/state and then animate.

**How to reproduce**

```
const ModalCard = ({
  children,
  ...props
}) => {
  const navigation = useNavigation();
  const {
    translationY,
    velocityY,
    state,
    gestureHandler,
  } = panGestureHandler();
  const snapBottom = new Value<number>(0);
  const snapTop = 0;
  const closeLimit = sub(snapBottom, 20);

  const translateY = withSpring({
    value: clamp(translationY, snapTop, snapBottom),
    state,
    velocity: velocityY,
    snapPoints: [snapBottom, snapTop],
    config: springConfig,
  });

  const stop = new Value<number>(0);

  useCode(
    () =>
      block([
        cond(
          and(
            greaterThan(translateY, 0),
            greaterThan(translateY, closeLimit),
            eq(stop, 0),
          ),
          block([
            set(stop, 1),
            call([], () => {
              navigation.goBack();
            }),
          ]),
        ),
      ]),
    [],
  );

  return (
    <PanGestureHandler {...gestureHandler}>
      <Animated.View style={{ transform: [{ translateY } as any] }}>
        <View
          onLayout={(e) => {
            if (snapBottom.isNativelyInitialized) {
              snapBottom.setValue(e.nativeEvent.layout.height);
            }
          }}
          {...props}
          >
          {children}
        </View>
      </Animated.View>
    </PanGestureHandler>
  );
};
```

**Your Environment**

Latest version of all deps.

**Comment by satya164** [comment]
Closing since you didn't provide any repro. We need a minimal repro to be able to debug issues. Feel free to open a new issue if you have a repro.
