### ISSUE TITLE
Drawer not opening on swipe after once tapped outside to close.

### ISSUE THREAD

**Issue by adiwon9555** [react-navigation/react-navigation#7944]
**Current Behavior**

In React navigation 5

Drawer properly opens and closes on event openDrawer() and closeDrawer() events, but when facing issues while swipping to open drawer.

Steps to Reproduce:-
1)Open Drawer once
2)Tap outside Drawer and close.
3)Swipe to open drawer. ( Facing problem here, not able to open)

**Comment by bijayalaxmi19** [comment]
dreawer is not close after Touching outside of drawer.

**Comment by raajnadar** [comment]
Give the versions! A repro! Read the docs.

https://reactnavigation.org/docs/drawer-navigator#swipeenabled

https://reactnavigation.org/docs/drawer-navigator#gestureenabled

**Comment by Nehal-29** [comment]
I'm also facing the same issue
I open the drawer then close it by tapping outside but DrawerActions.closeDrawer() is not dispatched automatically
since the state isDrawerOpen is not updated hence on tapping the icon again to open the drawer doesn't work
@brentvatne @ericvicenti

**Comment by raajnadar** [comment]
**@Nehal-29 please don't tag the maintainers.**

> I'm also facing the same issue

We don't have a repro to test the issue so how can we help to solve this issue? If you can create a snack or repo with the issue we can find what is going wrong.

**Comment by Nehal-29** [comment]
Hey @adiwon9555 
were you able to resolve this ?

**Comment by adiwon9555** [comment]
I guess, there is some gesture issue with RN5 drawer. In my project i just removed the functionality of opening drawer via gesture.

**Comment by satya164** [comment]
Closing since you didn't provide any repro. We need a minimal repro to be able to debug issues. Feel free to open a new issue if you have a repro.

**Comment by rgoldiez** [comment]
@adiwon9555 @satya164 - I just submitted https://github.com/react-navigation/react-navigation/pull/8369 to fix this issue. Hopefully it gets reviewed soon!
