### ISSUE TITLE
On first mount of app, Drawer buttons are clickable even when its closed for some time.

### ISSUE THREAD

**Issue by adiwon9555** [react-navigation/react-navigation#7945]
**Current Behavior**

React Navigation 5

If user Taps on screen just after he opens app, buttons of Drawer screens are clicked even when drawer is closed.

This is for atleat 2 -  3 seconds after app is first mounted.

**Comment by satya164** [comment]
Closing since you didn't follow the issue template.

**Comment by kkirby** [comment]
Also having this issue. There's not much more information that I personally can provide. It's happening on Android, and possibly iOS too.

**Comment by raajnadar** [comment]
@kkirby but you should at least provide a runnable repro to check the issue.

**Comment by kkirby** [comment]
> @kkirby but you should at least provide a runnable repro to check the issue.

I actually haven’t been able to reproduce this one myself yet. Our QA team and PM brought it to my attention. When I find the cause or find a minimal reproducible app I’ll update you.
