### ISSUE TITLE
On navigating using Top level navigation ref to a nested screen, the screen gets set to first index for the nested stack.

### ISSUE THREAD

**Issue by adiwon9555** [react-navigation/react-navigation#7946]
During nested navigation, I want the screen to be rendered in the same order as is kept in the stack, and when goBack() fired, follows the hierarchy upwards.

**Comment by rusyurchenko** [comment]
Same thing... If a nested screen has not rendered yet, navigation sets the nested screen as first in the stack and completely breaks my navigation. I know this behavior intended by design with dynamic routing, but it should somehow prerender routes in the stack to safe routes order.

**Comment by satya164** [comment]
https://reactnavigation.org/docs/nesting-navigators#rendering-initial-route-defined-in-the-navigator
