### ISSUE TITLE
Swipe back gesture not working on Android

### ISSUE THREAD

**Issue by durdevic** [react-navigation/react-navigation#7947]
**Current Behavior**

I created a ```gestureResponseDistance: {horizontal: 300}``` in Stack.Navigator. The goal is to swipe back on the whole screen. Currently it works on iOS but not on Android. It worked for me on version 4 of react navigation.

Video example:
[Android bug.mov.zip](https://github.com/react-navigation/react-navigation/files/4432213/Android.bug.mov.zip)

**Expected Behavior**

To have same behaviour on Android.

**How to reproduce**

Create a simple app and apply the screen options to the Stack.Navigator. 

Here is the snack you can check out:
https://snack.expo.io/@ukiand1/react-navigation-5---android-swipe-back-bug

I've also tried to put ```import 'react-native-gesture-handler';``` to different locations in my project (index.js and App.js) and even added the imports to MainActivity.java by following these instructions https://software-mansion.github.io/react-native-gesture-handler/docs/getting-started.html.

No luck.

Thanks for checking this out!

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |Android
| @react-navigation/native       |^5.1.4
| @react-navigation/stack        |^5.2.9
| react-native-gesture-handler   | ^1.6.1
| react-native-safe-area-context |^0.7.3
| react-native-screens           |^2.4.0
| react-native                   |0.62.1
| expo                           | -
| node                           |v12.13.0
| npm or yarn                    |6.12.0

**Comment by satya164** [comment]
`gestureEnabled: true`, not `gesturesEnabled: true`

**Comment by durdevic** [comment]
OMG! Thanks! And thanks for the amazingly fast reply ❤️

**Comment by TQCasey** [comment]
still not working in android react native 0.61 with {gesturesEnabled : true} included ...

**Comment by durdevic** [comment]
Just read the previous comments 👌

**Comment by TQCasey** [comment]
thanks @durdevic  ,But still not work , event navigation 4.x still not working ,the same with  {gestureEnabled : true}  (not 
 gesturesEnabled)  @durdevic 
did navigation 4.x swipe back work on android ? 
need I upgrade to navigation 5.x ?

**Comment by TQCasey** [comment]
After upgrading to navigation 5.x ,It works ...... thanks @durdevic

**Comment by durdevic** [comment]
@TQCasey Here are both swipe-enabled codes for 
https://snack.expo.io/@ukiand1/navigation-4---swipe-back,-no-touch-bug
