### ISSUE TITLE
Unable to resolve module `./views/assets/back-icon.png` from `node_modules/@react-navigation/stack/src/index.tsx`: 

### ISSUE THREAD

**Issue by Estebank94** [react-navigation/react-navigation#7950]
**Current Behavior**

After installing Stack navigator I get the following error:
`Unable to resolve module `./views/assets/back-icon.png` from `node_modules/@react-navigation/stack/src/index.tsx`: `

But I can see in the node modules folder that it's installed and the asset is there.

I have tried deleting node modules folder an installing again, reseting cache and restarting my computer.

**Expected Behavior**

The app should work properly

**How to reproduce**

npm install @react-navigation/native --save
npm install react-native-reanimated react-native-gesture-handler react-native-screens react-native-safe-area-context @react-native-community/masked-view --save
npm install @react-navigation/stack --save
cd ios; pod install; cd ..

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | iOS
| @react-navigation/native       | 5.1.4
| @react-navigation/stack        | 5.2.9
| react-native-gesture-handler   | 1.6.1
| react-native-safe-area-context | 0.7.3
| react-native-screens           | 2.4.0
| react-native                   | 0.61.5
| expo                           | ---> using "react-native-unimodules": "^0.8.1"
| node                           | 12.16.1
| npm or yarn                    | npm

**Comment by QuevedoIB** [comment]
Problem shows when you install together react-native-unimodules and react-navigation

**Comment by du5rte** [comment]
Also having this issue, using a bare react-native project

```
error: bundling failed: node_modules/@react-navigation/stack/src/views/assets/back-icon-mask.png: Cannot find module 'expo/tools/hashAssetFiles'
Require stack:
- /Users/du5rte/Work/haystack/node_modules/metro/src/Assets.js
- /Users/du5rte/Work/haystack/node_modules/metro/src/assetTransformer.js
- /Users/du5rte/Work/haystack/node_modules/metro/src/JSTransformer/worker.js
- /Users/du5rte/Work/haystack/node_modules/metro/src/DeltaBundler/Worker.js
- /Users/du5rte/Work/haystack/node_modules/jest-worker/build/workers/processChild.js
```

```

**Comment by sboh1214** [comment]
same as me on jest test. my error is as below. Any updates?

` FAIL  __tests__/App-test.tsx
  ● Test suite failed to run

    /Users/sboh1214/Repos/News-App/node_modules/@react-navigation/stack/lib/commonjs/views/assets/back-icon.png:1
    �PNG


    SyntaxError: Invalid or unexpected token
        at compileFunction (<anonymous>)

      at Runtime._execModule (node_modules/jest-runtime/build/index.js:1010:58)
      at Object.<anonymous> (node_modules/@react-navigation/stack/lib/commonjs/index.tsx:13:3)`

**Comment by du5rte** [comment]
@sboh1214 I came across the same bug today, basically, jest doesn't know how to handle static assets:

You can read more on here:
- https://jestjs.io/docs/en/webpack#handling-static-assets
- https://github.com/facebook/jest/issues/2663#issuecomment-274270387
- https://github.com/eddyerburgh/jest-transform-stub

Here's my solution, add this your `jest.config.js`
```js
module.exports = {
 moduleNameMapper: {
    '.+\\.(css|styl|less|sass|scss|png|jpg|ttf|woff|woff2)$':
      'jest-transform-stub',
    '\\.(css|less)$': 'identity-obj-proxy',
  },
}

```

**Comment by QuevedoIB** [comment]
Can you check babel versions in package.json :
1. npm install @babel/core@^7.9.0
2. npm install @babel/runtime@^7.9.2

If that doesn't work I got it gone using this versions:
"@react-navigation/native": "^5.1.5",
"@react-navigation/stack": "^5.2.10",
"react-native-unimodules": "^0.7.0",

 "@babel/core": "^7.9.0",
 "@babel/runtime": "^7.9.2",
 "jest": "^24.9.0",

Hope it helps

**Comment by sboh1214** [comment]
@du5rte Thanks! It works. I'm newbie on jest. you helped me a lot.

**Comment by alexstanbury** [comment]
I ran into this issue, solved by adding .png extension to the assetExts array in my metro.config.js.

**Comment by satya164** [comment]
Closing since you didn't provide a repro. Regardless, this is most likely an issue with your bundler configuration rather than React Navigation. The files exists and is resolved in fresh React Native projects.

**Comment by fomin-max** [comment]
> I ran into this issue, solved by adding .png extension to the assetExts array in my metro.config.js.

thanks, it works for me!

**Comment by camel113** [comment]
@du5rte code is working. Do not forget to run `npm i --save-dev jest-transform-stub`

**Comment by rayonnunes** [comment]
> I ran into this issue, solved by adding .png extension to the assetExts array in my metro.config.js.

thanks @sboh1214. If I can complement your answer, here is a snippet from `metro.config.js`:
```javascript
module.exports = {
  resolver: {
    assetExts: [ 'png', ...additional_extensions ],
    ...
  }
}
```

**Comment by esilvestre31** [comment]
Android Bundling failed 6856ms
Unable to resolve module ./logo.android.png from C:\Users\hp\Desktop\expo\TccApp2\screens\HomeScreen.js: 

None of these files exist:
  * logo.android.png
  * screens\logo.android.png\index(.native|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.js|.native.js|.js|.android.jsx|.native.jsxjsx|.native.jsx|.jsx|.android.json|.native.json|.json)
  14 |         }}
  15 |           source={
> 16 |              require('./logo.android.png')
     |                       ^
  17 |
  18 |             }

**Comment by esilvestre31** [comment]
Android Bundling failed 6856ms
Unable to resolve module ./logo.android.png from C:\Users\hp\Desktop\expo\TccApp2\screens\HomeScreen.js: 

None of these files exist:
  * logo.android.png
  * screens\logo.android.png\index(.native|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.js|.native.js|.js|.android.jsx|.native.jsxjsx|.native.jsx|.jsx|.android.json|.native.json|.json)
  14 |         }}
  15 |           source={
> 16 |              require('./logo.android.png')
     |                       ^
  17 |
  18 |             }

**Comment by alidplus** [comment]
possible solutions:
check the .yarnclean file if you use "yarn autoclean" (in project root). remove "assets" and "image" lines
