### ISSUE TITLE
Cannot blur the entire screen with header

### ISSUE THREAD

**Issue by salamancajr** [react-navigation/react-navigation#7951]
I am trying to use a blur view on the entire screen including the header when I display a pop up. I am able to blur the screen portion, but the header floats over the blur and is completely unblurred. The header is declared in the screenOptions of the Stack.Navigator and headerTransparent is set to true, although I have set it to false and it doesn't make any difference for the blur.

My environment:

| software                       | version |
| ------------------------------ | ------- |
| Android                 |
| @react-navigation/native       | 5.1.3
| @react-navigation/stack        |    5.2.8
| react-native-gesture-handler   |   1.6.0
| react-native-safe-area-context |  0.7.3
| react-native-screens           |   2.4.0
| react-native                   |  0.59.10
| @react-native-community/blur       | 3.4.1
 npm or yarn                    | yarn

**Comment by raajnadar** [comment]
You need a portal provider and consumer it will be at the root level of your application.

If you use react native paper you already have a built-in component https://callstack.github.io/react-native-paper/portal.html
