### ISSUE TITLE
MaterialTopTabNavigator tabBarLabel always show uppercase letter in reactnavigation 5

### ISSUE THREAD

**Issue by TechAsif** [react-navigation/react-navigation#7952]
**Current Behavior**

- What code are you running and what is happening?
- Include a screenshot or video if it makes sense.

**Expected Behavior**

- What do you expect should be happening?
- Include a screenshot or video if it makes sense.

**How to reproduce**

- You must provide a way to reproduce the problem. If you are having an issue with your machine or build tools, the issue belongs on another repository as that is outside of the scope of React Navigation.
- Either re-create the bug on [Snack](https://snack.expo.io) or link to a GitHub repository with code that reproduces the bug.
- Explain how to run the example app and any steps that we need to take to reproduce the issue from the example app.
- Keep the repro code as simple as possible, with the minimum amount of code required to repro the issue.
- Before reporting an issue, make sure you are on latest version of the package.

**Your Environment**

| software                      | version |
| ----------------------------- | ------- |
| iOS or Android                |
| @react-navigation/native      |
| @react-navigation/bottom-tabs |
| react-native-screens          |
| react-native                  |
| expo                          |
| node                          |
| npm or yarn                   |

**Comment by ralph-dev** [comment]
Can we see the code where your tab navigator is initialized? (Pref the file with the TabBarLabel string)

**Comment by edwardchen** [comment]
I'm seeing this too. What happened to upperCaseLabel? I'll post code in a bit if I can't figure it out.

**Comment by edwardchen** [comment]
Uhh I dunno. Here's the code.
`    

    const Tab = createMaterialTopTabNavigator();
    return (
      <Tab.Navigator>
        <Tab.Screen name="chart" component={ChartScreen}
          options = {{ title: 'i show up uppercase' }}/>
      </Tab.Navigator>`

**Comment by ralph-dev** [comment]
@edwardchen 
@TechAsif 
This is why: 
https://github.com/react-native-community/react-native-tab-view/blob/master/src/TabBar.tsx#L73

**Comment by edwardchen** [comment]
Makes sense. In react navigation 4 you could control it using
`upperCaseLabel=false`

I guess it was just taken out? I want to have my title not in all uppercase.

**Comment by ralph-dev** [comment]
https://reactnavigation.org/docs/material-top-tab-navigator#tabbaroptions
Yep it was removed, but it's a simple thing to add if you want to open a PR?

**Comment by satya164** [comment]
https://reactnative.dev/docs/text-style-props#texttransform

```js
tabBarOptions={{
  labelStyle: { textTransform: 'none' }
}}
```

**Comment by ralph-dev** [comment]
textTransform: 'lowercase'
Yes I was about to comment you can just apply the style lol

**Comment by sirilmp** [comment]
<Tab.Navigator
             screenOptions={{
                tabBarLabelStyle: { textTransform:'lowercase' },
}}
            >
              ......
            </Tab.Navigator>

Now its will show in lowercase.

**Comment by hipages-ligang** [comment]
For the new version (mine is "@react-navigation/material-top-tabs": "^6.2.1")
We should set it in Tab.Navigator-> tabBarLabelStyle->textTransform

`
<Tab.Navigator
                screenOptions={{
                    tabBarActiveTintColor: Colors.white,
                    tabBarLabelStyle: { fontSize: 12, textTransform: 'none' },
                    tabBarStyle: { backgroundColor: Colors.primary }
                }}
            >
                <Tab.Screen name="Invite" component={InviteTab} />
                <Tab.Screen name="Accepted" component={AcceptedTab} />
                <Tab.Screen name="Message" component={MessageTab} />
                <Tab.Screen name="Help" component={HelpTab} />
            </Tab.Navigator>
`

**Comment by burakodabas** [comment]
> https://reactnative.dev/docs/text-style-props#texttransform
> 
> ```js
> tabBarOptions={{
>   labelStyle: { textTransform: 'none' }
> }}
> ```
Thank you for solution work for me.

Version 6.x should be; 

```javascript
screenOptions={{
          tabBarLabelStyle: {
            textTransform: 'none',
          },
}}
```

**Comment by faerylay** [comment]
```
- 'capitalize',
- 'lowercase',
 - 'none',
- 'uppercase',
<TopTab.Navigator
           screenOptions={{
                    tabBarLabelStyle: {
                        fontStyle: 'normal',
                        textTransform: 'lowercase',
                    },
                }}
            >
</TopTab.Navigator>
```
