### ISSUE TITLE
Unable to resolve "./getChildEventSubscriber" from "node_modules/@react-navigation/core/lib/module/getChildNavigation.js"

### ISSUE THREAD

**Issue by AakashPat** [react-navigation/react-navigation#7953]
Unable to resolve "./getChildEventSubscriber" from "node_modules/@react-navigation/core/lib/module/getChildNavigation.js"

![image](https://user-images.githubusercontent.com/10728448/78457818-a318bc00-76ca-11ea-973d-1bcfc304048f.png)

    "expo": "^37.0.0"
    "react": "16.9.0"
    "react-navigation": "^4.3.7"

Also, I am facing this problem only with Android (Emulator as well as a physical device). I do not face this error on an iOS Simulator.

**Comment by louishinohara** [comment]
I was having the same issue but my first issue started here
https://github.com/expo/expo/issues/7552
I followed the guide and ended up with your issue but after I restarted my computer, I got it to work on physical device.

**Comment by samgrat** [comment]
Had the same error, fixed it by running `expo start -c` to solve the "stale cache" problem.

Solution found here (https://reactnavigation.org/docs/troubleshooting/#im-getting-an-error-unable-to-resolve-module-after-updating-to-the-latest-version)

`"expo": "^36.0.0"
"react": "16.9.0"
"react-navigation": "^4.0.10"`

Cheers

**Comment by AakashPat** [comment]
Finally got it working! It took a combination of both the above mentioned things.
I had to restart my Mac and also start the expo app by 'expo start -c', the later is something I always do any which way.

**Comment by CHARITH1995** [comment]
delete the node modules , package-lock.json 
reinstall the node modules.
 
if getting this error reinstall the react-native-router-flux if you using this. or reinstall the npm package that is using @react-navigation

**Comment by jantsch** [comment]
I am still having this issue. I have already tried all the things above. I am using react-native-router-flux and already reinstalled all the dependencies. How should you tackle the issue if you were in my shoes?

**Comment by Karen-1999** [comment]
> I am still having this issue. I have already tried all the things above. I am using react-native-router-flux and already reinstalled all the dependencies. How should you tackle the issue if you were in my shoes?

I cleaned cache `npm cache clean` and then fixed the react-native version in package.json, it works for me!

**Comment by jeremyfrancis** [comment]
@Karen-1999 Thank you this fixed the issue for me!
