### ISSUE TITLE
Got an invalid value for 'component' prop for the screen 'Feeds'. It must be a valid React Component.]

### ISSUE THREAD

**Issue by Hansol-git** [react-navigation/react-navigation#7954]
**Current Behavior**

I used functional component as a component in stack.screen.
But I got the error : **Got an invalid value for 'component' prop for the screen 'Feeds'. It must be a valid React Component.**

I just made stack navigation on tab navigation (each tab has stack navigation).
Each stack navigation has the same screens except one stack screen, so that I made and reuse the stack navigation as a functional component.
Here is my code. 

```
import React from 'react';
import {createMaterialTopTabNavigator} from '@react-navigation/material-top-tabs';
import StackFactory from '../components/StackFactory';

export default () => {
  const Tab = createMaterialTopTabNavigator();

  return (
    <Tab.Navigator
      initialRouteName="Feeds">
      <Tab.Screen
        name="Feeds"
        component={StackFactory(Feeds)}
      />
      <Tab.Screen
        name="Search"
        component={StackFactory(Search)}
      />
    </Tab.Navigator>
  );
};
```

The StackFactory is:
```
import React from 'react';
import {createStackNavigator} from '@react-navigation/stack';
import PostDetail from '../screens/PostDetail';
import UserProfile from '../screens/UserProfile';

const Stack = createStackNavigator();

export default initialRoute => {
  return (
    <Stack.Navigator>
      <Stack.Screen
        name="InitialRoute"
        component={initialRoute}
      />
      <Stack.Screen
        name="PostDetail"
        component={PostDetail}
      />
      <Stack.Screen
        name="UserProfile"
        component={UserProfile}
      />
    </Stack.Navigator>
  );
};
```

And Feeds, Search, PostDetail, UserProfile is like this.
```
import React from 'react';
import styled from 'styled-components';

const View = styled.View`
  justify-content: center;
  align-items: center;
  flex: 1;
`;

const Text = styled.Text``;

export default () => (
  <View>
    <Text>Feeds</Text>
  </View>
);

```

**Expected Behavior**

I think stack navigation with each component should work well depending on the input I gave.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Android
| @react-navigation/native       | 5.0.8
| react-native                   | 0.61.5
| expo                           | not used
| node                           |
| npm or yarn                    |

**Comment by ralph-dev** [comment]
Make sure StackFactory is returning the correct Type.

**Comment by Hansol-git** [comment]
Thank you for your reply @ralph-dev . 
How can I return navigator as react component?
Sorry for annoying you since I'm beginner of react native.

**Comment by ralph-dev** [comment]
@Hansol-git you don't need StackFactory. Because you are just creating a screen from a component. Please re-read the docs which explain this in detail. 

https://reactnavigation.org/docs/stack-navigator

Just import the component you want to appear and show that directly. Good luck!

**Comment by Hansol-git** [comment]
@ralph-dev Thank you for your kind response first at all.
I understood to create a screen from component. But I want to make a stack navigation as a componet of tab navigation.

By modifying above code (removing argument of StackFactory), it works!

```
import React from 'react';
import {createMaterialTopTabNavigator} from '@react-navigation/material-top-tabs';
import StackFactory1 from '../components/StackFactory1';
import StackFactory2 from '../components/StackFactory2';

export default () => {
  const Tab = createMaterialTopTabNavigator();

  return (
    <Tab.Navigator
      initialRouteName="Feeds">
      <Tab.Screen
        name="Feeds"
        component={StackFactory1}
      />
      <Tab.Screen
        name="Search"
        component={StackFactory2}
      />
    </Tab.Navigator>
  );
};
```
where StackFactory1 is (or StackFactory2):
```
import React from 'react';
import {createStackNavigator} from '@react-navigation/stack';
import Feeds from '../screens/Feeds';
import PostDetail from '../screens/PostDetail';
import UserProfile from '../screens/UserProfile';

const Stack = createStackNavigator();

export default () => {
  return (
    <Stack.Navigator>
      <Stack.Screen
        name="Feeds"
        component={Feeds}
      />
      <Stack.Screen
        name="PostDetail"
        component={PostDetail}
      />
      <Stack.Screen
        name="UserProfile"
        component={UserProfile}
      />
    </Stack.Navigator>
  );
};
```

I checked that it does work using stack navigation as a component of tab navigation **without any argument**.
However, with argument (initialRoute in the first StackFactory.js), the error shows up, so I thought it could be bug. Am I wrong?

**Comment by ralph-dev** [comment]
Yes if you reference the document initial route should be a name in the existing navigation level.

Meaning initial route for tab navigator can be the stack mavigator and the initial route for the stack navigator can be Tab A.

**Comment by singha55162326** [comment]
Got an invalid value for 'component' prop for the screen 'Profile'. It must be a valid React Component.]

**Comment by singha55162326** [comment]
can you help me

**Comment by dinhtrumdieu** [comment]
@singha55162326

**Comment by stephenmclin** [comment]
did you export your function
or try it like this

export default function initialRoute ( ){
}

**Comment by pm-sharma** [comment]
Getting still this 

Home.js
export default function Home(props) {
  return (
    <SafeAreaView style={styles.home}>
        <Header />
        <HomeContent />
        <Footer style={styles.footer} />
    </SafeAreaView>
  );
}

app.js
import { NavigationContainer } from '@react-navigation/native';
import { createStackNavigator } from '@react-navigation/stack';
const Stack = createStackNavigator();
export default function App() {
    return (
        <NavigationContainer>
            <Stack.Navigator initialRouteName="Profile">
                <Stack.Screen name="Home" component={<Home />} />
                <Stack.Screen name="Profile" component={<Profile />} />
            </Stack.Navigator>
        </NavigationContainer>
    );
}


It's working fine when I am tried to define the home and profile components in app.js. But in the case of importing gives an error

**Comment by fukemy** [comment]
> did you export your function or try it like this
> 
> export default function initialRoute ( ){ }

i can not access to prop when using function, i need props to replace navigaton

**Comment by eqlipse18** [comment]
> did you export your function or try it like this
> 
> export default function initialRoute ( ){ }



it worked thanks mate after 3 days finally thanks alot 

import React from 'react';
import { StyleSheet, Text, View } from 'react-native';

export default function ProfileScreen() {
  return (
    <View>
      <Text>ProfileScreen</Text>
    </View>
  );
}

const styles = StyleSheet.create({});
