### ISSUE TITLE
Swipe Gesture Not Disabling

### ISSUE THREAD

**Issue by anwersolangi** [react-navigation/react-navigation#7955]
I have created an app where i need to just only disable the swipe gesture for opening and closing the drawer.
I have found several articles, but didn't help with react navigation v5.

**Comment by raajnadar** [comment]
Use `gestureEnabled: false` to disable all the gestute. Use `swipeEnabled: false` to disable wipe gesture only tab gesture will work.

**Comment by alexakasanjeev** [comment]
Example

```
<Drawer.Navigator>
        <Drawer.Screen
            name="Drawer
            component={StackNavigator}
            options={{
               gestureEnabled: false,
               swipeEnabled: false,
           }}
        />
```
