### ISSUE TITLE
What is unmountInactiveRoutes prop equivalent in react-navigation V5

### ISSUE THREAD

**Issue by shubhamdeol** [react-navigation/react-navigation#7959]
**Current Behavior**

In V4 I was using **unmountInactiveRoutes** to unmiunt the enactive routes in drawer navigatior
Is there any such prop in new api. I couldn't find this in React-Navigation doc.

**Comment by shubhamdeol** [comment]
@allandiego  this is for the individual screen, and this does not work exactly the same way *unmountInactiveRoutes* used to work

**Comment by satya164** [comment]
Specify it in `screenOptions`

**Comment by shubhamdeol** [comment]
@satya164  there is no property as ```unmountInactiveRoutes``` under screenProps as per documentation. I want screens to be unmounted on tab change in drawer navigation.
currently drawer keeps all screens mounted in all tabs. I want to unmount all screens from tab when navigating to another tab

**Comment by xiCO2k** [comment]
@shubhamdeol add screenOptions={{ unmountOnBlur: true }} on the nav it does work
