### ISSUE TITLE
undefined is not an object (evaluating 'navigation.navigate') - openDrawer

### ISSUE THREAD

**Issue by saur2729** [react-navigation/react-navigation#7961]
I'm getting myself familiar with the new react-navigation version. I'm seeing an issue while using the navigation.navigate method. 

**Current Behavior**

- When we click the menu button, it throws an error - 
**Device: (65:24) undefined is not an object (evaluating 'navigation.navigate')**

**Expected Behavior**

- On clicking the menu button, it should open the drawer

**How to reproduce**

https://snack.expo.io/W0dye1bLt

**Comment by saur2729** [comment]
> try to use hooks:
> 
> ```js
> import { useNavigation } from '@react-navigation/native';
> 
> function NotificationsScreen() {
> const navigation = useNavigation(); 
> return(
> <Button
>         onPress={() => navigation.navigate('Notifications')}
>         title="Go to notifications"
>       />
> );
> }
> ```

Sorry but this doesn't work.
Error I see is - couldn't find a navigation object. Is your component inside a scree in a navigator?

**Comment by louzada01** [comment]
> > try to use hooks:
> > ```js
> > import { useNavigation } from '@react-navigation/native';
> > 
> > function NotificationsScreen() {
> > const navigation = useNavigation(); 
> > return(
> > <Button
> >         onPress={() => navigation.navigate('Notifications')}
> >         title="Go to notifications"
> >       />
> > );
> > }
> > ```
> 
> Sorry but this doesn't work.
> Error I see is - couldn't find a navigation object. Is your component inside a scree in a navigator?


If your component is inside another component try to pass the navigation on a props. Example:

```js
import React from 'react';
import {createDrawerNavigator} from '@react-navigation/drawer';
const Drawer = createDrawerNavigator();

function App() {
  return (
    <Drawer.Navigator
      sceneContainerStyle={{
        backgroundColor: '#7121FF',
      }}
      drawerContent={({navigation}) => (
        <DrawerComponent navigation={navigation} />
      )}>
      <Drawer.Screen name="Main" component={Main} />
    </Drawer.Navigator>
  );
}
```

```js

export default function Drawer({navigation}) {
  return (
     <Container>
            <DrawerItem
              name="Close"
              icon="subdirectory-arrow-left"
              action={() => navigation.closeDrawer()}
            />
     </Container>
  )
}
```

So it solved my problem that was similar to yours.

**Comment by dhaveed** [comment]
> ```js
> navigation
> ```

This worked to resolve the issue for me. Thanks.

**Comment by zoro1378** [comment]
> try to use hooks:
> 
> ```js
> import { useNavigation } from '@react-navigation/native';
> 
> function NotificationsScreen() {
> const navigation = useNavigation(); 
> return(
> <Button
>         onPress={() => navigation.navigate('Notifications')}
>         title="Go to notifications"
>       />
> );
> }
> ```

nice ♥

**Comment by harsh-kumar-saaniya** [comment]
import { useNavigation } from '@react-navigation/native';

function NotificationsScreen() {
const navigation = useNavigation(); 
return(
<Button
        onPress={() => navigation.navigate('Notifications')}
        title="Go to notifications"
      />
);
}

This doesn't worked still having the same issue

**Comment by mitia-anah** [comment]
Thank you all, These saved my day.

**Comment by mauricejulesm** [comment]
> > Sorry but this doesn't work.
> > Error I see is - couldn't find a navigation object. Is your component inside a scree in a navigator?
> 
> If your component is inside another component try to pass the navigation on a props. Example:
> 
> ```js
> import React from 'react';
> import {createDrawerNavigator} from '@react-navigation/drawer';
> const Drawer = createDrawerNavigator();
> 
> function App() {
>   return (
>     <Drawer.Navigator
>       sceneContainerStyle={{
>         backgroundColor: '#7121FF',
>       }}
>       drawerContent={({navigation}) => (
>         <DrawerComponent navigation={navigation} />
>       )}>
>       <Drawer.Screen name="Main" component={Main} />
>     </Drawer.Navigator>
>   );
> }
> ```
> 
> ```js
> export default function Drawer({navigation}) {
>   return (
>      <Container>
>             <DrawerItem
>               name="Close"
>               icon="subdirectory-arrow-left"
>               action={() => navigation.closeDrawer()}
>             />
>      </Container>
>   )
> }
> ```
> 
> So it solved my problem that was similar to yours.

Thank you @louzada01, this is what I was looking for!

**Comment by HieuMinh1907** [comment]
I have a problem like this
<img width="847" alt="Screen Shot 2021-08-17 at 14 11 11" src="https://user-images.githubusercontent.com/81904379/129682292-eb94e0d6-b524-4602-919c-7d0e55e85c6a.png">

**Comment by raajnadar** [comment]
@HieuMinh1907 you are using props & not hooks. There is a change you are not passing the navigation props to the component.

**Comment by sagar17-create** [comment]
you have to pass a navigation props  from parent to child componenet.

**Comment by Mohsin-Nawaz** [comment]
> @HieuMinh1907 you are using props & not hooks. There is a change you are not passing the navigation props to the component.

but still not work

**Comment by comontes** [comment]
I had the same issue using Typescript but I made it work,


I first created an object type with mappings for each route name, I did that on App.tsx

```TSX
export type RootStackParamList = {
  Challenges: undefined
  AudioLesson: undefined
}
```
Then used that type when using createNativeStackNavigator

```TSX
const Stack = createNativeStackNavigator<RootStackParamList>()
```

On a screen, 'Challenges' in my example, I created an object type for it
```TSX
export type ChallengesType = NativeStackScreenProps<RootStackParamList, 'Challenges'>
```

I used that type in the screen like so
```TSX
export default function Challenges({ navigation }: ChallengesType) {
```

Then I passed the navigation object to the final component that will be using it like this:
```TSX
        <SomeComponent button_title="Tap me" navigation={navigation} />
```
And the part I somehow managed to get right was this:
In the component, create an object type and include navigation, as the type for it put the object type of the Screen you are coming from ( navigation: ChallengesType['navigation'] for example).

You can also use multiple screen types here to use the component in more screens. (  navigation: AudioLessonType['navigation'] | ChallengesType['navigation']
)

```TSX
import React from 'react'
import { Button } from 'react-native'
import { ChallengesType } from 'src/Challenges'

interface SomeComponentType {
  button_title: string
  navigation: ChallengesType['navigation']
}

export default function SomeComponent(params: SomeComponentType) {
  const { button_title, navigation } = params

  return <Button title={button_title} onPress={() => navigation.navigate('AudioLesson')} />
}
```

**Comment by nippysky** [comment]
Thank you very much, guys. passing navigation function as a prop, solved it

**Comment by janusqa** [comment]
Hi all, my understanding is that useNavigation hook can be used in non-screen components, so that it was not necessary to pass the navigation via props.
I though ti could do something like this
```
// SomeComponent.tsx
import { useNavigation } from '@react-navigation/native';
import { Props as NavigateToScreenProps } from '../pages/NavigateToScreen'; //this is page i want to navigate too

const SomeComponent:React.FC = ()=> {
  const {navigation} = useNavigation<NaviGateToScreenProps>()
  console.log(navigigatoin) // <--- undefined
}
export default SomeComponent
```
and then I have a screen call NavigateFrom that loads SomeComponent with a pressable that when pressed i want to navigate to NavigateToScreen

I expected this to work. Am I doing it wrong.

**Comment by janusqa** [comment]
> Hi all, my understanding is that useNavigation hook can be used in non-screen components, so that it was not necessary to pass the navigation via props. I though ti could do something like this
> 
> ```
> // SomeComponent.tsx
> import { useNavigation } from '@react-navigation/native';
> import { Props as NavigateToScreenProps } from '../pages/NavigateToScreen'; //this is page i want to navigate too
> 
> const SomeComponent:React.FC = ()=> {
>   const {navigation} = useNavigation<NaviGateToScreenProps>()
>   console.log(navigigatoin) // <--- undefined
> }
> export default SomeComponent
> ```
> 
> and then I have a screen call NavigateFrom that loads SomeComponent with a pressable that when pressed i want to navigate to NavigateToScreen
> 
> I expected this to work. Am I doing it wrong.

Hmmm it seems to work if I do this
 const navigation = useNavigation<NaviGateToScreenProps>()
 navigation.navigate('NavigateToScreen')  
 
 But navigate has the red squiggles from typescript which is why i thought it did not work at first.

**Comment by janusqa** [comment]
I used // @ts-ignore above line to get rid of the squiggle.

**Comment by janusqa** [comment]
After re-reading the docs i Put this in SomeComponent which was loaded from NavigateFromScreen

```
// SomeComponent.tsx
import { useNavigation } from '@react-navigation/native';
import type { NativeStackNavigationProp } from '@react-navigation/native-stack';
import type { RouteProp } from '@react-navigation/native';
import { RootStackParamList } from '../App';

type NavigateFromNavigationProps = NativeStackNavigationProp<
    RootStackParamList,
    'NavigateFrom'
>;

type NavigateFromRouteProps = RouteProp<RootStackParamList, 'NavigateFrom'>;

const SomeComponent:React.FC = ()=> {
  const navigation = useNavigation<NaviGateToScreenProps>()
  console.log(navigation) // <--- works now with no red squiggles.
}
export default SomeComponent

**Comment by Misha010199** [comment]
> > try to use hooks:
> > ```js
> > import { useNavigation } from '@react-navigation/native';
> > 
> > function NotificationsScreen() {
> > const navigation = useNavigation(); 
> > return(
> > <Button
> >         onPress={() => navigation.navigate('Notifications')}
> >         title="Go to notifications"
> >       />
> > );
> > }
> > ```
> 
> nice ♥

it worked thanks!

**Comment by aerrazki** [comment]
> import { useNavigation } from '@react-navigation/native';
> 
> function NotificationsScreen() { const navigation = useNavigation(); return( <Button onPress={() => navigation.navigate('Notifications')} title="Go to notifications" /> ); }
> 
> This doesn't worked still having the same issue

did you try to install @react-navigation/native with npm?

**Comment by pollyolly** [comment]
Make sure the Component of the navigation is running First in the Program. 
In example in App.js the component for navigation <AuthStack /> is inside the App.js.
Then <AuthStack /> is executed with the App.js first.
