### ISSUE TITLE
How to filter DrawerItems

### ISSUE THREAD

**Issue by ROODAY** [react-navigation/react-navigation#7962]
**Current Behavior**
Our app has a Home screen, Login Screen, and Article Screen. Article is a reusable screen that changes depending on the required params passed to it, so we don't want a user clicking the Article screen in the Drawer and navigating to it (instead we navigate using the API when an article button is clicked). I want to hide the DrawerItem for Article, and I did so by filtering the routes (I did extensive googling and all the results were a couple years old so this is the best I could find).
```
const Drawer = createDrawerNavigator();
const visibleRoutes = ['Home', 'Login'];
const Sidebar = props => {
    const clonedProps = {...props};
    clonedProps.state.routes = props.state.routes.filter(route => visibleRoutes.includes(route.name));
    return (
        <DrawerContentScrollView {...clonedProps}>
            <DrawerItemList {...clonedProps} />
        </DrawerContentScrollView>
    );
}

...
<Drawer.Navigator
initialRouteName="Home"
drawerContent={Sidebar} >
...
```

**Expected Behavior**
This works and removes the unwanted DrawerItems from the Sidebar. However, when clicking an Article button, I get this error:
```
The action 'NAVIGATE' with payload {"name":"Article","params":{"id":1,"title":"Democratic Debate","subtitle":"Bernie dominates debate, but democrats seem to rally behind Biden still.","dateString":"April 06, 2020"}} was not handled by any navigator.

Do you have a screen named 'Article'?

If you're trying to navigate to a screen in a nested navigator, see https://reactnavigation.org/docs/nesting-navigators#navigating-to-a-screen-in-a-nested-navigator.
```

I do have a screen named article, defined like so:
```
<Drawer.Screen
    name="Article"
    component={ArticleScreen}
    listeners={{
        focus: e => StatusBar.setHidden(true),
        blur: e => StatusBar.setHidden(false)
    }}
/>
```
Yet I get this error whenever I click on the button. It would seem that the filtered routes I send to the DrawerItems are the same ones that the entire navigation uses. What's the point of a custom component then?

**How to reproduce**
[Full Code](https://github.com/Veri-News/Veri-Mobile/blob/master/components/AppNavigator.js)

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Android
| @react-navigation/native       |  5.1.4
| @react-navigation/drawer       | 5.4.0
| react-native-reanimated        | 1.4.0
| react-native-gesture-handler   | 1.5.6
| react-native-safe-area-context | 0.6.0
| react-native-screens           | 2.0.0-alpha.12
| react-native                   | [version](https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz)
| expo                           | 36.0.2
| node                           | v12.16.1
| npm or yarn                    | npm

**Comment by satya164** [comment]
The error probably happens because you're mutating the state object and changing the available routes in the original state. Shallow copy the state object before changing any properties on it.

**Comment by ROODAY** [comment]
Do you mean a deep copy, as a shallow copy would contain references to the original? I did use lodash cloneDeep earlier and still ran into issues, so I ended up solving it by making my own version of DrawerItemList that filters in the render method.
