### ISSUE TITLE
Event order: focus from Screen2 execute before blur from Screen1

### ISSUE THREAD

**Issue by allandiego** [react-navigation/react-navigation#7963]
**Current Behavior**
Two <Drawer.Screen> that add a ScreenOrientation listener on focus event and remove it on blur. The problem is when Screen1 execute the blur event to remove the orientation listener its after Screen2 addListerner on focus, so is removes Screen2 listener too.

Time line for better understanding:
- Screen1 - focus > register orientation listener
- user navigate to Screen2 -  focus > register orientation listener
- Screen1 execute blur event > remove orientation Listeners including the newly registered by focus from Screen2

Screen1
```js
 useEffect(() => {
    navigation.addListener('focus', () => {
      function handleOrientationChange(orientation) {
        const isLandscape = orientation.orientationInfo.orientation > 2;
        setIsLandscapeLayout(isLandscape);
      }

      ScreenOrientation.addOrientationChangeListener(handleOrientationChange);
    });

     navigation.addListener('blur', () => {
       ScreenOrientation.removeOrientationChangeListeners();
       navigationListenerBlur();
       navigationListenerFocus();
     });
  }, [navigation]);
```

Screen2 have the same code with different handleOrientationChange function body

**Expected Behavior**

- Screen1 focus > register orientation listener
- user navigate to Screen2
- Screen1 blur > remove orientation listener
- Screen2 focus > register orientation listener

I have achieved that behavior using the useEffect return (component unmount) to remove the listener and adding the unmountOnBlur option, but that way i lose the component state and i need preserve it, 
Is there any way to execure blur before next screen focus?

```js
<Drawer.Screen options={{ unmountOnBlur: true }} />
```

```js
 useEffect(() => {
      function handleOrientationChange(orientation) {
        const isLandscape = orientation.orientationInfo.orientation > 2;
        setIsLandscapeLayout(isLandscape);
      }
      ScreenOrientation.addOrientationChangeListener(handleOrientationChange);

    return () => ScreenOrientation.removeOrientationChangeListeners();
  }, [navigation]);
```

i have tried useIsFocused too and its the same behavior as the focus / blur event its set to false after new screen focus is set to true

**Comment by BooDzioo** [comment]
Did you managed to resolve this problem?

**Comment by allandiego** [comment]
yes, they fixed the blur and focus order, now blur from screen1 execute before focus from screen2

**Comment by SeveHo** [comment]
@allandiego how did you fix this?

**Comment by allandiego** [comment]
@SeveHo it was fixed:
https://github.com/react-navigation/react-navigation/commit/ce3994c82c28669d5742017eb7627e9adf996933

the order of blur and focus events was swapped so the problem got fixed
