### ISSUE TITLE
How to get a "current route" from the "navigation" object

### ISSUE THREAD

**Issue by JosipSylo** [react-navigation/react-navigation#7965]
Is it possible to get the current route from the "navigation" object. Docks https://reactnavigation.org/docs/navigation-prop/#common-api-reference don't mention it.

The only way I found is to use the "dangerouslyGetState". It also says to avoid using it:
`
If there is some functionality you cannot achieve without relying on the structure of the state object, please open an issue.
`

Thank you

**Comment by zmefz** [comment]
@JosipSylo
1. If you want to get current route **being inside of this page** you may use `useRoute()` or `route` prop provided by navigator to the screen component. 
2. If you want to use `route` **at navigation parts** (e.g. navigation bar right/title/left) you may use `route` property provided by navigation (at Navigator.screenOptions/Screen.options)
3. If you want to find current route **from other parts of the application** (e.g. currently inactive/unfocused screen) you need to use `dangerouslyGetState` and find current route inside of this state.

Here is an **example** on how receiving current route state from dangerouslyGetState might look:
```javascript
function getActiveRouteState(state) {
    if (!state) return null;
    if (state.state) return getActiveRouteState(state.state);
    return 'index' in state ? getActiveRouteState(state.routes[state.index]) : state;
}

getActiveRouteState(navigation.dangerouslyGetState())
```

**Comment by JosipSylo** [comment]
Awesome. Thank you so much for the quick and concise response.
