### ISSUE TITLE
White screen when use TransitionPresets.ScaleFromCenterAndroid on Android 5.0

### ISSUE THREAD

**Issue by Bardiamist** [react-navigation/react-navigation#7966]
**Current Behavior**

[You can see how that looks on this video](https://drive.google.com/file/d/1kXlfz2T7ca1wN9hLoD8CHWe1ePJo6JtS/view?usp=sharing)

Note: This white overlay not touchable. I can touch on invisible "NAVIGATE TO PROFILE" button.

**Expected Behavior**

I don't expect white overlay on screen.

**How to reproduce**

Repro steps:
1. Reset to screen with `TransitionPresets.ScaleFromCenterAndroid`
2. Navigate to another screen
3. Go back

[I reproduced minimal example in this repository](https://github.com/Bardiamist/ScaleFromCenterAndroid)

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |Android 5.0
| @react-navigation/native       |5.1.4
| @react-navigation/stack        |5.2.9
| react-native-gesture-handler   |1.6.1
| react-native-safe-area-context |0.7.3
| react-native-screens           |2.4.0
| react-native                   |0.62.1
| expo                           |Bare React native project
| node                           |13.12.0
| npm or yarn                    |yarn

**Comment by Bardiamist** [comment]
Seems problem in `cardStyleInterpolator`. `current.progress` has value 0 when navigate back on Android (value is 1 on iOS)

**Comment by satya164** [comment]
I just cloned your repo and can't repro this issue. Can you verify that this issue still exists in latest versions?

**Comment by Bardiamist** [comment]
@satya164 I updated dependencies in [repo](https://github.com/Bardiamist/ScaleFromCenterAndroid). Issue still exist. What problem with reproduction, can you show the video? [Here is my fresh video](https://drive.google.com/open?id=1PIVER8YXxmBf10cWFlWy6QDkSvPkHevt)

**Comment by Bardiamist** [comment]
I found next:
Issue not reproduced on API 29.
Issue exist on API 21. (Android 5.0)

<details>
  <summary>Android Studio Emulator details</summary>


Name: Galaxy_Nexus_API_21

CPU/ABI: Google APIs Intel Atom (x86)

Path: /Users/bardiamist/.android/avd/Galaxy_Nexus_API_21.avd

Target: google_apis [Google APIs] (API level 21)

Skin: galaxy_nexus

SD Card: 512 MB

fastboot.chosenSnapshotFile: 

runtime.network.speed: full

hw.accelerometer: yes

hw.device.name: Galaxy Nexus

hw.lcd.width: 720

hw.initialOrientation: Portrait

image.androidVersion.api: 21

tag.id: google_apis

hw.mainKeys: no

hw.camera.front: emulated

avd.ini.displayname: Galaxy Nexus API 21

hw.gpu.mode: auto

hw.ramSize: 1024

PlayStore.enabled: false

fastboot.forceColdBoot: no

hw.cpu.ncore: 4

hw.keyboard: yes

hw.sensors.proximity: yes

hw.dPad: no

hw.lcd.height: 1280

vm.heapSize: 80

skin.dynamic: yes

hw.device.manufacturer: Google

hw.gps: yes

hw.audioInput: yes

image.sysdir.1: system-images/android-21/google_apis/x86/

showDeviceFrame: yes

hw.camera.back: virtualscene

AvdId: Galaxy_Nexus_API_21

hw.lcd.density: 320

hw.arc: false

hw.device.hash2: MD5:d37b758e1a2b070e348378c2efde849a

fastboot.forceChosenSnapshotBoot: no

fastboot.forceFastBoot: yes

hw.trackBall: no

hw.battery: yes

hw.sdCard: yes

tag.display: Google APIs

runtime.network.latency: none

disk.dataPartition.size: 1G

hw.sensors.orientation: yes

avd.ini.encoding: UTF-8

hw.gpu.enabled: yes
</details>

**Comment by Bardiamist** [comment]
Fixed, should be in 9c06a92d092af150d653c3a2f7fdccd28090bb14
