### ISSUE TITLE
Conditional / dynamic screens in a StackNavigator break if inside a nested navigator (includes minimal repro)

### ISSUE THREAD

**Issue by jamesisaac** [react-navigation/react-navigation#7968]
### Current Behavior

I've created a minimal repro here: https://github.com/jamesisaac/react-navigation-nesting-bug which combines the following 2 techniques discussed in the docs:

- **Authentication flows**: https://reactnavigation.org/docs/auth-flow/ - all screens are conditionally included in the `MainStacknavigator` based on whether the user is logged in or not.
- **Transparent modals**: https://reactnavigation.org/docs/stack-navigator/#transparent-modals - The `MainStackNavigator` is nested inside a `RootModalStackNavigator`, allowing for modal screens to be set up with a different `cardStyle`/`cardStyleInterpolator` etc.

My navigation heirarchy looks like this:

- RootModalStackNavigator
  - MainStackNavigator
    - [if not logged in]
      - WelcomeScreen
      - LoginScreen
    - [if logged in]
      - AccountMainScreen
      - AccountSubScreen
  - ModalScreen

The issue is, whenever the routes in `MainStackNavigator` get conditionally reloaded, it seems like the screen which gets landed on gets passed the wrong `navigation` prop (from the parent `RootModalStackNavigator`), as all the buttons not longer work, because it can't navigate to any of its sibling screens:

```
console.error: "The action 'NAVIGATE' with payload {"name":"AccountSub"} was not handled by any navigator.

Do you have a screen named 'AccountSub'

If you're trying to navigate to a screen in a nested navigator, see https://reactnavigation.org/docs/nesting-navigators/#navigating-to-a-screen-in-a-nested-navigator
```

This error can be removed by taking away the parent `RootModalStackNavigator`

### Expected Behavior

It shouldn't matter to the `MainStackNavigator` that it happened to be nested inside a parent navigator; it's just trying to navigate between its own sibling screens.

There should be no new error introduced by combining these two techniques from the docs (both quite normal patterns when creating large apps).

### How to reproduce

https://github.com/jamesisaac/react-navigation-nesting-bug

```
$ yarn install
$ expo start
```

Then click the buttons through the screens.  As soon as the state has switched to logged in, the next button press will break.

### Your Environment

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Android
| @react-navigation/native       | 5.1.4
| @react-navigation/stack        | 5.2.9
| react-native-gesture-handler   | 1.6.1
| react-native-safe-area-context | 0.7.3
| react-native-screens           | 2.2.0
| react-native                   | 0.61
| expo                           | 37.0.1
| node                           | 12.10.0
| npm or yarn                    | yarn

**Comment by JuniorBoaventura** [comment]
I have the same issue. If the condition passes at the first launch it works, but if I pass by the Authentication Stack first it breaks the navigation and I get this error.

<img width="414" alt="Capture d’écran 2020-04-07 à 12 06 33" src="https://user-images.githubusercontent.com/9675292/78657011-74683480-78c8-11ea-8b8f-5ad1ebc3f663.png">

```javascript
 <NavigationContainer>
      <Stack.Navigator
        mode="modal"
        screenOptions={{
          headerShown: false,
        }}>
        {userState.token ? (
          <>
            <Stack.Screen name="App" component={App} />
            <Stack.Screen name="Onboarding" component={Onboarding} />
          </>
        ) : (
          <>
            <Stack.Screen name="Authentication" component={Authentication} />
          </>
        )}
      </Stack.Navigator>
    </NavigationContainer>
```

**Comment by 92sajid110** [comment]
Yes i also getting this error any fix yet

**Comment by satya164** [comment]
Thanks for providing a repro. I can no longer repro the issue after updating the `@react-navigation/native` and `@react-navigation/stack` packages to the latest versions, so I'm closing this.

**Comment by samipshah100** [comment]
I am having the same issue even after upgrading to the latest version.  This is very weird

`"@react-navigation/drawer": "^5.7.2",
    "@react-navigation/native": "^5.3.0",
    "@react-navigation/stack": "^5.3.3",
    `

**Comment by JuniorBoaventura** [comment]
@samipshah100 I'm using these versions and it works fine for me now.

"@react-navigation/native": "^5.1.7",
"@react-navigation/stack": "^5.2.14",

Have you tried to delete the node_modules et package-lock.json and run npm install again?

**Comment by samipshah100** [comment]
worked thanks. apologies for incorrect report.

**Comment by jobindcruz** [comment]
This issue is not solved yet. I am using latest versions
"@react-navigation/native": "^6.0.0-next.7",
"@react-navigation/stack": "^5.14.5",

**Comment by thorep** [comment]
Im also having this issue..any fix?

**Comment by iamadityaaz** [comment]
+1

**Comment by Delvio** [comment]
no updates on this?

**Comment by AbsoluteZero823** [comment]
> ome to discuss the issue with others

did you fixed this error?

**Comment by AbsoluteZero823** [comment]
> I have the same issue. If the condition passes at the first launch it works, but if I pass by the Authentication Stack first it breaks the navigation and I get this error.
> 
> <img alt="Capture d’écran 2020-04-07 à 12 06 33" width="414" src="https://user-images.githubusercontent.com/9675292/78657011-74683480-78c8-11ea-8b8f-5ad1ebc3f663.png">
> 
> ```js
>  <NavigationContainer>
>       <Stack.Navigator
>         mode="modal"
>         screenOptions={{
>           headerShown: false,
>         }}>
>         {userState.token ? (
>           <>
>             <Stack.Screen name="App" component={App} />
>             <Stack.Screen name="Onboarding" component={Onboarding} />
>           </>
>         ) : (
>           <>
>             <Stack.Screen name="Authentication" component={Authentication} />
>           </>
>         )}
>       </Stack.Navigator>
>     </NavigationContainer>
> ```

I have the same issue. did you fixed it?
