### ISSUE TITLE
Send navigation from stack to screen. But lost data. navigation.openDrawer is not function

### ISSUE THREAD

**Issue by khoailangdo** [react-navigation/react-navigation#7969]
I have an Stack in this below function. I had send navigation to HomeScreen

`
function HomeStack({ navigation }) {
  return (
    <StackHome.Navigator initialRouteName='Home'>
      <StackHome.Screen name='Home' options={navOptionHandle}>
        {() => <HomeScreen navigation={navigation} />}
      </StackHome.Screen>
      <StackHome.Screen name='HomeDetail' component={HomeScreenDetail} options={navOptionHandle} />
    </StackHome.Navigator>
  );
}
`

 

But in HomeScreen.  I cannot navigating to other screen. navigation.navigate("HomeDetail") is not a function:
`          <TouchableOpacity style={{ marginTop: 20 }} onPress={() => this.props.navigation.navigate('HomeDetail')}>
            <Text>Go to Home Details</Text>
          </TouchableOpacity>
`
 
What is matter here. Help me pls. 
Thanks

**Comment by zmefz** [comment]
You don't need to pass navigation prop manually. Just use 
```javascript
<StackHome.Screen name='Home' options={navOptionHandle} component={HomeScreen} />
```
`navigation.openDrawer` should be still available at `HomeScreen`. I just checked it and may assure you that it works. if not - the issue is somewhere else.

**Comment by khoailangdo** [comment]
Because of i using this:
`{() => <HomeScreen navigation={navigation} />} `
to send navigator from other screen to homescreen. But it don't effect and HomeScreen cannot using navigation.openDrawer

**Comment by zmefz** [comment]
@khoailangdo you never (as I know) need to pass `navigation` property manually to your screen. `openDrawer` should present for all nested navigators so you can just take `navigation` automatically passed by navigator and call `openDrawer` method which should work.
