### ISSUE TITLE
[Feature] Allow Routers to be passed into Navigators

### ISSUE THREAD

**Issue by RubenSandwich** [react-navigation/react-navigation#797]
Currently both StackNavigator and TabNavigator both create a StackRouter and TabRouter for you during their init. This is a solid default. However, this closely ties the the Routers with their navigators making it difficult to separate our the Routers which are usable in a Web Environment with the Navigators which are not. Leading to a project that is aimed at supporting both Native and Web to duplicate the Routers if they wish to share the share redux state.

Therefore, there should be an option to pass in the Routers for the Navigators.

**Comment by brentvatne** [comment]
we are going to be making routers and views more modular so that you can build this on your own in the near future.
