### ISSUE TITLE
Is there any short hand for navigation props?

### ISSUE THREAD

**Issue by suhailibnnisar** [react-navigation/react-navigation#7971]
**Current Behavior**

I have to define navigation & route on every route:

```javascript
interface Props {
  navigation: StackNavigationProp<RootScreens, "CurrentRoute">
  route: RouteProp<RootScreens, "CurrentRoute">
  otherProp: SomeType
}
```

**Expected Behavior**

I am looking for short-hand for eg.

```javascript
interface Props extends SomeAwesomeInterface<RootScreens, "CurrentRoute"> {
  otherProp: SomeType
}
```

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Android
| @react-navigation/native       | 5.1.4
| @react-navigation/stack        | 5.2.9

I would have loved to make pull request I tried but since I am just 27 days old to typescript I feel sad for myself =D 

I have seen this in @reach/router (web)

**Comment by zanona** [comment]
Request for supporting `CompositeScreenProps`: https://github.com/react-navigation/react-navigation/commit/bea14aa26fd5cbfebc7973733c5cf1f44fd323aa

**Comment by arafatzahan** [comment]
CompositeScreenProps will be super handy to have!

**Comment by semcelik** [comment]
is there any update for this?
