### ISSUE TITLE
Unable to resolve "./getChildEventSubscriber" from "node_modules/@react-navigation/core/lib/module/getChildNavigation.js"

### ISSUE THREAD

**Issue by confrodog** [react-navigation/react-navigation#7972]
**Current Behavior**

Hello, I am running a expo app on the ios simulator and with a real device

I expect the main screen to appear on app load through the Expo client app on the simulated phone. It isnt even popping up

<img width="327" alt="Screen Shot 2020-04-07 at 10 53 35 AM" src="https://user-images.githubusercontent.com/35404848/78702470-7bd61080-78bd-11ea-8e43-cab324f427ed.png">

**How to reproduce**

start an expo app with the following packages and their versions and the first thing that occurs is:

Unable to resolve "./getChildEventSubscriber" from "node_modules/@react-navigation/core/lib/module/getChildNavigation.js"
Failed building JavaScript bundle.

| software                       | version |
| ------------------------------ | ------- |
| iOS: 13.4 |
| react-navigation  | 4.3.7
| react-navigation-stack | 2.3.11
| react-navigation-drawer | 2.4.11
| react-native-reanimated | 1.4.0
| react-native-gesture-handler | 1.6.1
| react-native-safe-area-context | 0.6.0
| react-native-screens | 2.0.0-alpha.12
| react-native | https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz 
| expo | 36.0.0
| node | 12.14.1
| npm | 6.14.1

All of these versions are directly from the package.json.

**Comment by confrodog** [comment]
closed because im dumb and didnt restart my computer like
https://github.com/react-navigation/react-navigation/issues/7953
suggested. oops

**Comment by romicaiarca** [comment]
You don't need to restart your computer. You can run these commands instead:
> rm -rf /tmp/metro-*
> npx react-native start -- --reset-cache
