### ISSUE TITLE
Header size invalid

### ISSUE THREAD

**Issue by Xoce51** [react-navigation/react-navigation#7974]
**Current Behavior**

I'm using `createStackNavigator` to handle my page and show title in every screen and every thing were alright, but since I've added a new plugin `react-native-swipeout` with Yarn I'm facing the issue, I have an extra "padding ?" between the header title and to top of the device.
I tried to rollback on older version which wasn't buggy but when I launch the app on expo I still have the issue. It seems that the action to show a dropdown message (with librarie `react-native-dropdownalert`) fix the view, but when I reload the app the issue come back.
Here is a screenshot of the actual issue
![with_extra_height](https://user-images.githubusercontent.com/5357297/78732138-8a8bf880-798d-11ea-9aa1-6b9d47d17608.jpg)

**Expected Behavior**

The height of the header should be like the image below
![after_dropdown_alert](https://user-images.githubusercontent.com/5357297/78732160-937cca00-798d-11ea-8ce5-7d5911d6fd07.jpg)

**How to reproduce**
I juste simply run `yarn start` which runs `expo start --no-minify -c`.
I will try to give you a Snack

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Android
| react-navigation               | 4.0.10
| react-navigation-stack         |1.10.3
| react-navigation-tabs          |2.5.3
| react-navigation-drawer        | not used
| react-native-reanimated        |1.4.0
| react-native-gesture-handler   |1.5.3
| react-native-safe-area-view |0.14.8
| react-native-screens           |1.0.0-alpha.23
| react-native                   |0.61.4
| expo                           |36.0.2
| node                           |10.13.0
| npm or yarn                    |1.21.1

**Comment by Xoce51** [comment]
This issue is not relative to react navigation. I finally found the bug, it came from the expo client version, I had to rollback the apk (links [here](https://d1ahtucjixef4r.cloudfront.net/Exponent-2.14.0.apk)) and everything is back to normal

**Comment by ishrek** [comment]
i have a problem like you on devices android redmi 6. How to you fix it ???

**Comment by Xoce51** [comment]
Hi @ishrek like I said in the previous message I just rolled back my expo client version (with this one https://d1ahtucjixef4r.cloudfront.net/Exponent-2.14.0.apk) on my phone and it solved the problem.
