### ISSUE TITLE
BottomTab cannot run project with latest release (5.2.6)

### ISSUE THREAD

**Issue by sebinq** [react-navigation/react-navigation#7978]
I'm not able to run latest production release. After compilation I keep getting following error:

```ts
error: SyntaxError: /Users/user/Dev/eks/node_modules/@react-navigation/bottom-tabs/src/index.tsx: Unexpected token (15:12)

  13 |  * Types
  14 |  */
> 15 | export type {
     |             ^
  16 |   BottomTabNavigationOptions,
  17 |   BottomTabNavigationProp,
  18 |   BottomTabBarProps,
```

Also after I downgraded just bottom-tabs package, now I'm getting:

```ts
error: SyntaxError: /Users/user/Dev/eks/node_modules/@react-navigation/stack/src/index.tsx: Unexpected token (51:12)

  49 |  * Types
  50 |  */
> 51 | export type {
     |             ^
  52 |   StackNavigationOptions,
  53 |   StackNavigationProp,
  54 |   StackHeaderProps,
```

**Comment by sebinq** [comment]
Now it is not working even if I downgrade packages.... I dont know what happened but it is weird :D

**Comment by satya164** [comment]
Delete your `yarn.lock`/`package-json.lock` file and run `yarn`

**Comment by KULTI1995** [comment]
@satya164 U mnie nic to nie dało. Korzystam z łysego react native.

**Comment by gothraven** [comment]
@KULTI1995 delete `node_modules` folder and do what he said, it will work.

**Comment by adamivancza** [comment]
Not sure what's causing this but if I install via npm it works just fine, but if I install via yarn then it throws the error above.

**Comment by PaxLyj** [comment]
Solve with
1. `rm -rf node_modules yarn.lock`
2. `yarn cache clean`
3. `yarn`

just quick reinstall, didn't tested with npm, but it seems just simple error with cached file or version.

**Comment by gregoryfm** [comment]
Same issue here.

I already removed `node_modules`,` yarn.lock`, cleared yarn cache and installed using npm and yarn, but still the same error.

**Comment by Georginfanger** [comment]
@satya164  why is this closed .. It does not work. 
Im on npm and nothing helps

**Comment by pixelsaurus** [comment]
Yeah...not working for yarn either. Removed yarn.lock, reset cache, ran yarn install. No dice.

**Comment by twelve17** [comment]
In my case, I also had a direct dependency on `metro-react-native-babel-preset` in my `package.json`, and [per these docs|https://reactnavigation.org/docs/troubleshooting/#im-getting-syntaxerror-in-react-navigationxxxxxxtsx-or-syntaxerror-xxxreact-navigationxxxxxxtsx-unexpected-token], it needed to be updated.

**Comment by SpectorHacked** [comment]
Deleted node_models and reinstall them,
Still doesn't work, I am using @react-navigation/stack 5.2.10 
Any solution??

**Comment by mayconmesquita** [comment]
If you are using NPM try:

1. `rm -rf node_modules package-lock.lock`
2. `npm cache clean --force`
3. `npm install`

**Comment by zhumanasyrov** [comment]
@mayconmesquita your solution is working for me. Thanks dude

**Comment by dommangetnicolas** [comment]
> Delete your `yarn.lock`/`package-json.lock` file and run `yarn`/`npm install`.
> 
> Then try clearing cache with `npx react-native start --reset-cache`/`expo start -c`
> 
> 1. [Upgrade deps](https://reactnavigation.org/docs/troubleshooting#im-getting-syntaxerror-in-react-navigationxxxxxxtsx-or-syntaxerror-xxxreact-navigationxxxxxxtsx-unexpected-token)
> 2. [Clear cache](https://reactnavigation.org/docs/troubleshooting#stale-cache-of-metro-bundler)

It worked for me !

**Comment by FortisFortuna** [comment]
Did all of these, still got
node_modules/@react-navigation/drawer/lib/typescript/src/index.d.ts:21:13 - error TS1005: ';' expected.
export type { DrawerNavigationOptions, DrawerNavigationProp, DrawerContentOptions, DrawerContentComponentProps, } from './types';

and

node_modules/@react-navigation/routers/lib/typescript/src/index.d.ts:7:86 - error TS1109: Expression expected.

export type { TabActionHelpers, TabActionType, TabRouterOptions, TabNavigationState, } from './TabRouter';

plus 18 other similar ones

**Comment by ospaarmann** [comment]
> Delete your `yarn.lock`/`package-json.lock` file and run `yarn`/`npm install`.
> 
> Then try clearing cache with `npx react-native start --reset-cache`/`expo start -c`
> 
> 1. [Upgrade deps](https://reactnavigation.org/docs/troubleshooting#im-getting-syntaxerror-in-react-navigationxxxxxxtsx-or-syntaxerror-xxxreact-navigationxxxxxxtsx-unexpected-token)
> 2. [Clear cache](https://reactnavigation.org/docs/troubleshooting#stale-cache-of-metro-bundler)

Worked for me. Thanks!

**Comment by FortisFortuna** [comment]
Turns out my console `tsc` was not the same `tsc` installed by `npm install -g typescript`. You can check this via `tsc --version`. Make sure it is at least 3.8.3. Once I upgraded that, the errors went away.
Thank you guys for the help!

**Comment by aviemore** [comment]
https://reactnavigation.org/docs/troubleshooting/#im-getting-syntaxerror-in-react-navigationxxxxxxtsx-or-syntaxerror-xxxreact-navigationxxxxxxtsx-unexpected-token 

Yep, solved

**Comment by abhisheq6u** [comment]
It is a typescript compilation error.
You need to upgrade your `@babel/core` & `@babel/runtime` dev dependencies version to 7.9.0+ or simply the latest version.

Thanks to nicky for pointing [**this**](https://github.com/react-navigation/react-navigation/issues/7981#issuecomment-611419607) out!

**Comment by piazz** [comment]
Ugh this one cost me hours. @abhisheq6u has the fix - needs `babel core 7.9.0`, which requires blasting `package-lock`. This really needs to go in the docs/quick start guide or something. Too painful.

**Comment by zoontek** [comment]
I solved a similar issue on `react-native-permissions` with https://github.com/react-native-community/react-native-permissions/compare/2.0.6...2.0.7#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

I don't get the point of setting a TS file as entry point, it's just causing issues if your version of the babel TS preset does not support the new syntax. Serving the js file + the types solves it.

**Comment by willf80** [comment]
> Delete your `yarn.lock`/`package-json.lock` file and run `yarn`/`npm install`.
> 
> Then try clearing cache with `npx react-native start --reset-cache`/`expo start -c`
> 
> 1. [Upgrade deps](https://reactnavigation.org/docs/troubleshooting#im-getting-syntaxerror-in-react-navigationxxxxxxtsx-or-syntaxerror-xxxreact-navigationxxxxxxtsx-unexpected-token)
> 2. [Clear cache](https://reactnavigation.org/docs/troubleshooting#stale-cache-of-metro-bundler)

Worked for me. Thanks !

**Comment by jasurkurbanovinit** [comment]
> Delete your `yarn.lock`/`package-json.lock` file and run `yarn`/`npm install`.
> 
> Then try clearing cache with `npx react-native start --reset-cache`/`expo start -c`
> 
> 1. [Upgrade deps](https://reactnavigation.org/docs/troubleshooting#im-getting-syntaxerror-in-react-navigationxxxxxxtsx-or-syntaxerror-xxxreact-navigationxxxxxxtsx-unexpected-token)
> 2. [Clear cache](https://reactnavigation.org/docs/troubleshooting#stale-cache-of-metro-bundler)

worked for me. with npm install

**Comment by dani-mp** [comment]
You should never remove the `yarn.lock` file. Just upgrading `@babel/core` fixed it for me.

**Comment by nikopolidi** [comment]
I tried all things described at troubleshooting page. 
It's not working at all.
I tried with clean `expo init` project with typescript and tab navigation.

```
yarn add --dev metro-react-native-babel-preset
yarn add --dev @babel/core
watchman watch-del-all
rm -rf node_modules
rm yarn.lock
yarn cache clean
yarn
expo start -c
```

Nothing works. This is bizzare!
ENV:
```
node v12.20.0
yarn 1.22.5
expo 4.0.13
```
package.json
```
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject",
    "test": "jest --watchAll"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@expo/vector-icons": "^12.0.0",
    "@react-native-community/masked-view": "0.1.10",
    "@react-navigation/bottom-tabs": "^5.11.1",
    "@react-navigation/native": "^5.8.9",
    "@react-navigation/stack": "^5.12.6",
    "expo": "~40.0.0",
    "expo-asset": "~8.2.1",
    "expo-constants": "~9.3.0",
    "expo-font": "~8.4.0",
    "expo-linking": "~2.0.0",
    "expo-splash-screen": "~0.8.0",
    "expo-status-bar": "~1.0.3",
    "expo-web-browser": "~8.6.0",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz",
    "react-native-gesture-handler": "~1.8.0",
    "react-native-safe-area-context": "3.1.9",
    "react-native-screens": "~2.15.0",
    "react-native-web": "~0.13.12"
  },
  "devDependencies": {
    "@babel/core": "^7.12.10",
    "@babel/runtime": "^7.9.6",
    "@types/react": "~16.9.35",
    "@types/react-native": "~0.63.2",
    "jest-expo": "~40.0.0",
    "metro-react-native-babel-preset": "^0.64.0",
    "typescript": "~4.0.0"
  },
  "private": true
}

```

**Comment by daveGregorian** [comment]
I still got the same issue. Tried everything that was described here & on the websites trouble shooting section :/

**Comment by daveGregorian** [comment]
@nikopolidi I solved it finally. I use exact versions for these plugins now:
```
    "metro-react-native-babel-preset": "0.61.0",
    "metro-react-native-babel-transformer": "0.61.0",
    "@babel/core": "7.9.0",
    "@babel/runtime": "7.9.0", 
```

Additionally I had to delete my metro cache in this way: `watchman watch-del-all && rm -rf $TMPDIR/react-*`

**Comment by EAT-CODE-KITE-REPEAT** [comment]
I got stuck with this issue for 6 hours or so in total... I tried everything above but nothing helped. Apparently, however, it seemed that the problem was that there was a wrong version of typescript somewhere globally installed that was being used. Once I removed all yarn global packages and reinstalled expo-cli, it worked again.

**Comment by jsbls** [comment]
@EAT-CODE-KITE-REPEAT You might be onto something. I've tried everything to no avail but hadn't thought of global packages. Would explain why @satya164 and others were unable to replicate the error. Will give it a go later tonight.

**Comment by jsbls** [comment]
Ok, so I think I found something that helps. Kudos to @EAT-CODE-KITE-REPEAT :

1. Remove all of your global packages except for expo-cli (`yarn global list`)
2. Add @babel/core as a **global** dependency (`yarn global add @babel/core`), since `expo-cli` apparently doesn't recognize project-specific deps.

Also, for clarity, I think most people with the error are building on MacOS for iOS. If I ejected the Expo project, `react-navigation` loaded with no errors, but I really didn't wanna eject at this stage. BUT if it's not a problem for you, you can also try that. (Be sure to run npx pod-install ios` as per the docs)

**Comment by white-room** [comment]
@jsbls Thank you for ending hours of monkeying with this...! Just adding `@babel/core` (v7.13.10 at time of writing) as a yarn global dep followed by `rm -rf node_modules && yarn install && expo start -c` sorted it out for me, did not have to remove any global packages.

**Comment by archae0pteryx** [comment]
@jsbls I am sad it took me so long trying every one of these suggestions all the way down this thread. It was in fact the global @babel/core that needed upgrading... you get the party emoji!

**Comment by jsbls** [comment]
> @jsbls I am sad it took me so long trying every one of these suggestions all the way down this thread. It was in fact the global @babel/core that needed upgrading... you get the party emoji!

😂😂😂 Same energy, my friend. Glad to have helped!

**Comment by xlcrr** [comment]
Got it working after installing typescript and setting babel/core and babel/runtime to 7.9.0

**Comment by roots-ai** [comment]
Tried the above methods, still not working.

Here is my package.json
{
  "name": "Odo",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "pretest": "./node_modules/.bin/eslint -c .eslintrc --ext .js src",
    "test": "jest",
    "postinstall": "npx jetify"
  },
  "jest": {
    "preset": "react-native",
    "setupFiles": [
      "<rootDir>/jest.setup.js"
    ],
    "transformIgnorePatterns": [
      "node_modules/(?!react-native|tcomb-form-native|apsl-react-native-button,react-native-device-info|react-clone-referenced-element)"
    ],
    "collectCoverage": true,
    "verbose": true
  },
  "rnpm": {
    "assets": [
      "./src/fonts"
    ]
  },
  "dependencies": {
    "@babel/plugin-syntax-dynamic-import": "^7.0.0",
    "@babel/runtime": "^7.14.0",
    "@react-native-community/async-storage": "^1.6.1",
    "@react-native-community/blur": "^3.6.0",
    "@react-native-community/netinfo": "^4.2.1",
    "@react-native-community/push-notification-ios": "^1.0.5",
    "@react-native-firebase/analytics": "^7.3.1",
    "@react-native-firebase/app": "^8.2.0",
    "@react-native-firebase/in-app-messaging": "^7.2.2",
    "@react-native-firebase/messaging": "^7.5.0",
    "@stream-io/flat-list-mvcp": "^0.10.1",
    "aws-sdk": "^2.560.0",
    "axios": "^0.18.0",
    "crypto-js": "^3.1.9-1",
    "es6-symbol": "^3.1.1",
    "firebase": "^7.2.3",
    "grpc": "^1.23.3",
    "hermes-engine": "^0.1.1",
    "highlight.js": "^9.12.0",
    "install": "^0.12.1",
    "jsc-android": "^241213.1.0",
    "lottie-ios": "^3.1.3",
    "lottie-react-native": "^3.2.1",
    "md5": "^2.3.0",
    "node-pre-gyp": "^0.11.0",
    "npm": "^6.13.6",
    "nt-transmit-transparently": "^1.0.7",
    "object-hash": "^1.3.0",
    "patch-package": "^6.2.0",
    "prop-types": "^15.5.10",
    "react": "^16.9.0",
    "react-addons-perf": "^15.4.2",
    "react-native": "^0.61.4",
    "react-native-circles": "^1.0.1",
    "react-native-cookies": "^3.3.0",
    "react-native-device-info": "^5.6.1",
    "react-native-exception-handler": "^2.10.8",
    "react-native-extra-dimensions-android": "^1.2.5",
    "react-native-fast-image": "^8.1.5",
    "react-native-fbsdk": "^2.0.0",
    "react-native-fs": "^2.16.1",
    "react-native-gesture-handler": "^1.10.3",
    "react-native-iap": "^4.3.0",
    "react-native-image-header-scroll-view": "^0.10.3",
    "react-native-keyboard-accessory": "^0.1.15",
    "react-native-keyboard-aware-scroll-view": "^0.4.1",
    "react-native-lightbox": "^0.8.0",
    "react-native-linear-gradient": "^2.3.0",
    "react-native-permissions": "^2.1.5",
    "react-native-push-notification": "^7.3.1",
    "react-native-rate": "^1.1.6",
    "react-native-reanimated": "^2.2.0",
    "react-native-root-toast": "^3.2.0",
    "react-native-router-flux": "^4.2.0",
    "react-native-screens": "^3.3.0",
    "react-native-segmented-round-display": "^1.0.0",
    "react-native-share": "^1.0.24",
    "react-native-shimmer-placeholder": "^1.0.35",
    "react-native-size-matters": "^0.3.1",
    "react-native-snap-carousel": "^3.9.1",
    "react-native-sound": "^0.11.0",
    "react-native-splash-screen": "3.0.6",
    "react-native-svg": "^12.1.0",
    "react-native-swipe-list-view": "^3.2.6",
    "react-native-tts": "^3.2.0",
    "react-native-vector-icons": "^4.2.0",
    "react-native-wheel-picker": "^1.2.0",
    "react-redux": "^7.1.3",
    "recyclerlistview": "^1.3.4",
    "redux": "^4.0.4",
    "redux-logger": "^3.0.6",
    "redux-persist-filesystem-storage": "^2.1.0",
    "redux-thunk": "^2.1.0",
    "regenerator": "^0.13.2",
    "rn-fetch-blob": "^0.11.2",
    "scheduler": "^0.11.2",
    "url-parse": "^1.4.3"
  },
  "devDependencies": {
    "@babel/core": "^7.6.0",
    "@babel/plugin-proposal-decorators": "^7.6.0",
    "babel-eslint": "^7.1.1",
    "babel-plugin-transform-remove-console": "^6.9.4",
    "babel-preset-react-native": "5.0.0",
    "eslint": "^3.9.1",
    "eslint-config-airbnb": "^15.0.2",
    "eslint-plugin-import": "^2.2.0",
    "eslint-plugin-jsx-a11y": "^5.1.1",
    "eslint-plugin-react": "^7.0.1",
    "jest": "^25.0.0",
    "jetifier": "^1.6.4",
    "metro-react-native-babel-preset": "0.51.0",
    "schedule": "^0.5.0"
  }
}

**Comment by roots-ai** [comment]
Tried the above methods, its still not working.

Here is my package.json
{
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "pretest": "./node_modules/.bin/eslint -c .eslintrc --ext .js src",
    "test": "jest",
    "postinstall": "npx jetify"
  },
  "jest": {
    "preset": "react-native",
    "setupFiles": [
      "<rootDir>/jest.setup.js"
    ],
    "transformIgnorePatterns": [
      "node_modules/(?!react-native|tcomb-form-native|apsl-react-native-button,react-native-device-info|react-clone-referenced-element)"
    ],
    "collectCoverage": true,
    "verbose": true
  },
  "rnpm": {
    "assets": [
      "./src/fonts"
    ]
  },
  "dependencies": {
    "@babel/plugin-syntax-dynamic-import": "^7.0.0",
    "@babel/runtime": "^7.14.0",
    "@react-native-community/async-storage": "^1.6.1",
    "@react-native-community/blur": "^3.6.0",
    "@react-native-community/netinfo": "^4.2.1",
    "@react-native-community/push-notification-ios": "^1.0.5",
    "@react-native-firebase/analytics": "^7.3.1",
    "@react-native-firebase/app": "^8.2.0",
    "@react-native-firebase/in-app-messaging": "^7.2.2",
    "@react-native-firebase/messaging": "^7.5.0",
    "@stream-io/flat-list-mvcp": "^0.10.1",
    "aws-sdk": "^2.560.0",
    "axios": "^0.18.0",
    "crypto-js": "^3.1.9-1",
    "es6-symbol": "^3.1.1",
    "firebase": "^7.2.3",
    "grpc": "^1.23.3",
    "hermes-engine": "^0.1.1",
    "highlight.js": "^9.12.0",
    "install": "^0.12.1",
    "jsc-android": "^241213.1.0",
    "lottie-ios": "^3.1.3",
    "lottie-react-native": "^3.2.1",
    "md5": "^2.3.0",
    "node-pre-gyp": "^0.11.0",
    "npm": "^6.13.6",
    "nt-transmit-transparently": "^1.0.7",
    "object-hash": "^1.3.0",
    "patch-package": "^6.2.0",
    "prop-types": "^15.5.10",
    "react": "^16.9.0",
    "react-addons-perf": "^15.4.2",
    "react-native": "^0.61.4",
    "react-native-circles": "^1.0.1",
    "react-native-cookies": "^3.3.0",
    "react-native-device-info": "^5.6.1",
    "react-native-exception-handler": "^2.10.8",
    "react-native-extra-dimensions-android": "^1.2.5",
    "react-native-fast-image": "^8.1.5",
    "react-native-fbsdk": "^2.0.0",
    "react-native-fs": "^2.16.1",
    "react-native-gesture-handler": "^1.10.3",
    "react-native-iap": "^4.3.0",
    "react-native-image-header-scroll-view": "^0.10.3",
    "react-native-keyboard-accessory": "^0.1.15",
    "react-native-keyboard-aware-scroll-view": "^0.4.1",
    "react-native-lightbox": "^0.8.0",
    "react-native-linear-gradient": "^2.3.0",
    "react-native-permissions": "^2.1.5",
    "react-native-push-notification": "^7.3.1",
    "react-native-rate": "^1.1.6",
    "react-native-reanimated": "^2.2.0",
    "react-native-root-toast": "^3.2.0",
    "react-native-router-flux": "^4.2.0",
    "react-native-screens": "^3.3.0",
    "react-native-segmented-round-display": "^1.0.0",
    "react-native-share": "^1.0.24",
    "react-native-shimmer-placeholder": "^1.0.35",
    "react-native-size-matters": "^0.3.1",
    "react-native-snap-carousel": "^3.9.1",
    "react-native-sound": "^0.11.0",
    "react-native-splash-screen": "3.0.6",
    "react-native-svg": "^12.1.0",
    "react-native-swipe-list-view": "^3.2.6",
    "react-native-tts": "^3.2.0",
    "react-native-vector-icons": "^4.2.0",
    "react-native-wheel-picker": "^1.2.0",
    "react-redux": "^7.1.3",
    "recyclerlistview": "^1.3.4",
    "redux": "^4.0.4",
    "redux-logger": "^3.0.6",
    "redux-persist-filesystem-storage": "^2.1.0",
    "redux-thunk": "^2.1.0",
    "regenerator": "^0.13.2",
    "rn-fetch-blob": "^0.11.2",
    "scheduler": "^0.11.2",
    "url-parse": "^1.4.3"
  },
  "devDependencies": {
    "@babel/core": "^7.6.0",
    "@babel/plugin-proposal-decorators": "^7.6.0",
    "babel-eslint": "^7.1.1",
    "babel-plugin-transform-remove-console": "^6.9.4",
    "babel-preset-react-native": "5.0.0",
    "eslint": "^3.9.1",
    "eslint-config-airbnb": "^15.0.2",
    "eslint-plugin-import": "^2.2.0",
    "eslint-plugin-jsx-a11y": "^5.1.1",
    "eslint-plugin-react": "^7.0.1",
    "jest": "^25.0.0",
    "jetifier": "^1.6.4",
    "metro-react-native-babel-preset": "0.51.0",
    "schedule": "^0.5.0"
  }
}
