### ISSUE TITLE
moving between tabs(lazy render)

### ISSUE THREAD

**Issue by Liqiankun** [react-navigation/react-navigation#7982]
**Current Behavior**
##### structure
I set  ***`Settings1`*** to `initialRouteName`.  I wanna navigate to `Settings2` from `Home1`
```
-MyTabs (TabNavigator)
   -Tab1 (StackNavigator)
     -Home1
   - Tab2 (StackNavigator)
     -Settings1(initialRoute)
     -Settings2
```
It has two situations
##### 1）set `lazy` to true
![屏幕快照 2020-04-17 15 00 30](https://user-images.githubusercontent.com/11532418/79541346-3d5e0400-80bc-11ea-8d4b-4b08e182ea2a.png)
It seems like `Settings2` is the `initialRoute`
##### 2）set `lazy` false
![屏幕快照 2020-04-17 15 01 58](https://user-images.githubusercontent.com/11532418/79541450-6aaab200-80bc-11ea-9bae-20c12f12caa6.png)
This behavior is what I want. But all tabs are rendered immediately.

**Expected Behavior**
My Expected Behavior is like [navigate_cross_tab_v4](https://github.com/Liqiankun/navigation_cross_tab_v4)

Following with v5
```
<Tab.Navigator lazy={false}>
  <Tab.Screen name="Tab1" component={Tab1} />
  <Tab.Screen name="Tab2" component={Tab2} />
</Tab.Navigator>
```
It did solve my issue! But it has a performance issue. All tabs are rendered immediately. Is there any way can solve my issue along with a better performance(tabs are rendered only when they are made active for the first time)?

**How to reproduce**
* [Snack navigate_cross_tab](https://snack.expo.io/@qiankunli/833fbb)
* [Github navigate_cross_tab](https://github.com/Liqiankun/navigate_cross_tab)

If you had problem with downloading dependencies on snack, you could use the github repository.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | iOS
| @react-navigation/native       | ^5.1.4
| @react-navigation/stack        | ^5.2.9
| react-native-gesture-handler   | ^1.6.1
| react-native-safe-area-context | ^0.7.3
| react-native-safe-area-context | ^0.7.3
| react-native-screens           | ^2.4.0
| node                           | v10.15.3
| npm or yarn                    | yarn

**Comment by Liqiankun** [comment]
[react-navigation bottom-tab-navigator props lazy](https://reactnavigation.org/docs/bottom-tab-navigator/#lazy)
```
<Tab.Navigator lazy={false}>
      <Tab.Screen name="Tab1" component={Tab1} />
      <Tab.Screen name="Tab2" component={Tab2} />
</Tab.Navigator>
```

**Comment by Liqiankun** [comment]
@satya164 Would you like to take a look at this issue?

**Comment by satya164** [comment]
https://reactnavigation.org/docs/nesting-navigators#rendering-initial-route-defined-in-the-navigator

**Comment by Liqiankun** [comment]
I replaced
```js
this.props.navigation.navigate('Tab2', { screen: 'Settings2' });
```
with 
```
this.props.navigation.navigate('Tab2', { screen: 'Settings2', initial: false });
```
It didn't solve my issue! @satya164

**Comment by Bardiamist** [comment]
@Liqiankun Thanks!:)
