### ISSUE TITLE
Crash when on press go back twice quickly android

### ISSUE THREAD

**Issue by dinhduongson** [react-navigation/react-navigation#7983]
App crash when press go back twice quickly android

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |Android
| @react-navigation/native       |^5.0.1
| @react-navigation/stack        |^5.0.1
| react-native-gesture-handler   |^1.6.1
| react-native-safe-area-context |^0.7.3
| react-native-screens           |^2.4.0
| react-native                   |^0.61.5
| expo                           | no
| node                           |v10.16.3
| npm or yarn                    |both npm and yarn

**Comment by satya164** [comment]
Closing since issue template was not followed
