### ISSUE TITLE
[initialRouteName] is not work when change value by async method  in Stack.Navigator V5

### ISSUE THREAD

**Issue by lyicelee** [react-navigation/react-navigation#7984]
**Current Behavior**

Show the [Screen1] after changed  initialRouteName of state by setState.

Source:
```
export default class App extends Component {
  constructor(props) {
    super(props)
    this.state = {
      initialRouteName: "Screen1",
    }
  }
  
  Screen1() {
    return (<View>
        <Text>{"Screen1"}</Text>
      </View>)
  }
  
  Screen2() {
    return (<View>
      <Text>{"Screen2"}</Text>
      </View>)
  }

  render() {
    console.log(this.state.initialRouteName);
    return (
      <NavigationContainer>
        <Stack.Navigator initialRouteName={this.state.initialRouteName}>
          <Stack.Screen name="Screen1" component={this.Screen1} />
          <Stack.Screen name="Screen2" component={this.Screen2} />
        </Stack.Navigator>
      </NavigationContainer>
    );
  }

  async componentDidMount() {
    console.log("componentDidMount");
    const value = await AsyncStorage.getItem("key");
    if (value === null) { // ->> true
      this.setState({
        initialRouteName: "Screen2",
      });
    }
  }
}
```

log:
```
Running “App” with {"rootTag":21,"initialProps":{}}
Screen1
componentDidMount
Screen2
```

**Expected Behavior**

Show the [Screen2] after changed  initialRouteName of state by setState.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | IOS 13.3 Simulator
| @react-navigation/native       |5.1.4
| @react-navigation/stack        |5.2.9
| react-native                   |0.62.1
| @react-native-community/async-storage  |1.9.0

**Comment by mlisik** [comment]
This is actually expected - as the name suggests, `initialRouteName` has impact only on the [initial render](https://reactnavigation.org/docs/stack-navigator/#initialroutename).

However, if you want to switch between routes based on your `App` component state, you can render navigator children conditionally, like so:

```jsx
  render() {
    const { someBooleanValue } = this.state;

    return (
      <NavigationContainer>
        <Stack.Navigator>
          {someBooleanValue ? (
            <Stack.Screen name="Screen1" component={this.Screen1} />
          ) : (
            <Stack.Screen name="Screen2" component={this.Screen2} />
          )}
        </Stack.Navigator>
      </NavigationContainer>
    );
  }
```

This pattern is explained in the docs with regard to authentication flows: https://reactnavigation.org/docs/auth-flow#define-our-screens

**Comment by mlisik** [comment]
This is actually expected - as the name suggests, `initialRouteName` has impact only on the initial render. If you want to switch between routes based on your `App` component state, you can render navigator children conditionally, like so:

```jsx
  render() {
    const { someBooleanValue } = this.state;

    return (
      <NavigationContainer>
        <Stack.Navigator>
          {someBooleanValue ? (
            <Stack.Screen name="Screen1" component={this.Screen1} />
          ) : (
            <Stack.Screen name="Screen2" component={this.Screen2} />
          )}
        </Stack.Navigator>
      </NavigationContainer>
    );
  }
```

This pattern is explained in the docs with regard to authentication flows: https://reactnavigation.org/docs/auth-flow#define-our-screens

**Comment by lyicelee** [comment]
> This is actually expected - as the name suggests, `initialRouteName` has impact only on the [initial render](https://reactnavigation.org/docs/stack-navigator/#initialroutename).
> 
> However, if you want to switch between routes based on your `App` component state, you can render navigator children conditionally, like so:
> 
> ```js-jsx
>   render() {
>     const { someBooleanValue } = this.state;
> 
>     return (
>       <NavigationContainer>
>         <Stack.Navigator>
>           {someBooleanValue ? (
>             <Stack.Screen name="Screen1" component={this.Screen1} />
>           ) : (
>             <Stack.Screen name="Screen2" component={this.Screen2} />
>           )}
>         </Stack.Navigator>
>       </NavigationContainer>
>     );
>   }
> ```
> 
> This pattern is explained in the docs with regard to authentication flows: https://reactnavigation.org/docs/auth-flow#define-our-screens

OK, i find another way to resolve what i want. Thanks.

**Comment by Yab-kami** [comment]
@lyicelee How did you achieve this... im facing the same issue

**Comment by lyicelee** [comment]
> @lyicelee How did you achieve this... im facing the same issue

By my case:
```
  constructor(props) {
    super(props)
    this.state = {
      initialRouteName: null,
    }
  }

  render() {
    const layout = this.Layout(this.state.initialRouteName);
    return (layout);
  }

  /** Layout */
  Layout =(initialRouteName)=> {
    if (initialRouteName !== null) {
      return (
        <NavigationContainer>
        <MainStack.Navigator initialRouteName={initialRouteName} screenOptions={this.mainStackScreenOptions} >
          {ScreenList.map((screen) => this.StarkScreens(screen))}
        </MainStack.Navigator>
        </NavigationContainer>
      );
    } else {
      return (<View></View>);
    }
  }

  componentDidMount() {
    this.setState({initialRouteName: condition ? "screen1" : "screen2"});
  }

```

**Comment by lyicelee** [comment]
@Yab-kami 
By my case:
```
  constructor(props) {
    super(props)
    this.state = {
      initialRouteName: null,
    }
  }

  render() {
    const layout = this.Layout(this.state.initialRouteName);
    return (layout);
  }

  /** Layout */
  Layout =(initialRouteName)=> {
    if (initialRouteName !== null) {
      return (
        <NavigationContainer>
        <MainStack.Navigator initialRouteName={initialRouteName} screenOptions={this.mainStackScreenOptions} >
          {ScreenList.map((screen) => this.StarkScreens(screen))}
        </MainStack.Navigator>
        </NavigationContainer>
      );
    } else {
      return (<View></View>);
    }
  }

  componentDidMount() {
    this.setState({initialRouteName: condition ? "screen1" : "screen2"});
  }

```

**Comment by haciSeydaoglu** [comment]
@lyicelee's solution worked for me.

**Comment by thangtx86** [comment]
anyone here help me propblem:

`const TabNavigator = createMaterialTopTabNavigator(
    {
        A: {

            screen: (props) => (
                <A />
            )
        },
        B: {
            screen: (props) => (
                <B  />
            )
        },
        C: {
            screen: (props) => (
                <C  />
            )
        }
    },
    {
    
        initialRouteName: props.initRouter
    }
);

const TopTab = createAppContainer(TabNavigator);`
