### ISSUE TITLE
BottomTabNavigator animations are jumpy on Android

### ISSUE THREAD

**Issue by sebinq** [react-navigation/react-navigation#7985]
**Current Behavior**

Some of my screens use header, some of them have header set to null. The same for BottomTabs: some screens in nested StackNavigator have bottom tab visible property set to false.

Screen transition animations are really nice and fluid on IOS. There is no jumping or whatever, but on Android the animation is jumpy and transition from screen with bottom tabs to screen without bottom tabs looks terrible. The same goes for header/non header screen transitions.

**Expected Behavior**

Animation on Android should look a little bit cleaner?

**How to reproduce**

Do I need to provide a reproduction repro? If so, I will create one.

**Your Environment**

| software                      | version |
| ----------------------------- | ------- |
| @react-navigation/native      | 5.1.5 |
| @react-navigation/bottom-tabs | 5.2.6 |
| react-native-screens          | 2.4.0 |
| react-native                  | 0.62.2 |

Thanks!

**Comment by sebinq** [comment]
I've just found that jumpy transition is cause by `<StatusBar translucent />` on Android... Is there any way to make Android StatusBar translucent without that prop, please?

**Comment by sebinq** [comment]
So for anyone encountering same issue...

If you have multiple screens with `<StatusBar translucent />` on Android, then setting:

```ts
useEffect(() => {
  if (Platform.OS === 'android'){
    StatusBar.setTranslucent(true);
  }
}, [])
```

in `App.tsx` can help you to prevent jumpy transitions between screens. You just need to take care of top offsets across the app when its needed.

**Comment by gotexis** [comment]
in my app BottomTabNavigator has no transition at all, and i am struggling to get it there...

how do you enabled it in the first place?

**Comment by chinieer** [comment]
> So for anyone encountering same issue...
> 
> If you have multiple screens with `<StatusBar translucent />` on Android, then setting:
> 
> ```ts
> useEffect(() => {
>   if (Platform.OS === 'android'){
>     StatusBar.setTranslucent(true);
>   }
> }, [])
> ```
> 
> in `App.tsx` can help you to prevent jumpy transitions between screens. You just need to take care of top offsets across the app when its needed.

it did

**Comment by jzxchiang1** [comment]
> So for anyone encountering same issue...
> 
> If you have multiple screens with `<StatusBar translucent />` on Android, then setting:
> 
> ```ts
> useEffect(() => {
>   if (Platform.OS === 'android'){
>     StatusBar.setTranslucent(true);
>   }
> }, [])
> ```
> 
> in `App.tsx` can help you to prevent jumpy transitions between screens. You just need to take care of top offsets across the app when its needed.

This works for me too.
