### ISSUE TITLE
shifting={false} blocks tabBarColor in createMaterialBottomTabNavigator

### ISSUE THREAD

**Issue by ggunti** [react-navigation/react-navigation#7987]
**Current Behavior**

- What code are you running and what is happening?

I created a TabNav using `createMaterialBottomTabNavigator`:
`const TabNav = createMaterialBottomTabNavigator();`

Then, I added my screens to the `TabNav`. (`TabNav.Navigator` is the root component of the app):
```javascript
  <TabNav.Navigator activeColor={WHITE}>
    <TabNav.Screen
      name='articles'
      component={ArticlesPage}
      options={{
        title: 'Articles',
        tabBarColor: BLUE,
        tabBarIcon: ({ color }) => <Icon size={24} color={color} type='feather' name='file-text' />,
      }}
    />
    <TabNav.Screen
      name='forum'
      component={ForumPage}
      options={{
        title: 'Forum',
        tabBarColor: GREEN,
        tabBarIcon: ({ color }) => <Icon size={24} color={color} type='material-community' name='forum-outline' />,
      }}
    />
    <TabNav.Screen
      name='definitions-and-theorems'
      component={ArticlesPage}
      options={{
        title: 'Def & Theorems',
        tabBarColor: BLUE,
        tabBarIcon: ({ color }) => <Icon size={24} color={color} type='feather' name='book-open' />,
      }}
    />
    <TabNav.Screen
      name='stars'
      component={ArticlesPage}
      options={{
        title: 'Stars',
        tabBarColor: BLUE,
        tabBarIcon: ({ color }) => <Icon size={24} color={color} type='feather' name='star' />,
      }}
    />
  </TabNav.Navigator>
```

This is what I get:
<img width="315" alt="Captură de ecran din 2020-04-09 la 16 06 23" src="https://user-images.githubusercontent.com/26307699/78898665-d6699b00-7a7c-11ea-96fe-23f40719f440.png">

If I press the second icon (Forum) in the Tabbar, this is what I get:
<img width="315" alt="Captură de ecran din 2020-04-09 la 16 06 36" src="https://user-images.githubusercontent.com/26307699/78898783-07e26680-7a7d-11ea-9aee-ba6765a7a869.png">

Everything is okay until now, but what I want to achieve is to show the labels of all tabs (not only when a tab is active), so I just added `shifting={false}` to the `TabNav.Navigator`. It looks that it works, but actually now if I press the second tab (Forum), the tab bar color is not changed to green (as you saw above), it keeps remaining blue:
<img width="315" alt="Captură de ecran din 2020-04-09 la 16 17 39" src="https://user-images.githubusercontent.com/26307699/78899268-cf8f5800-7a7d-11ea-8a7d-4c6f114f49f0.png">

Note that I tried also `labeled={true}`, but it did not work.

**Expected Behavior**

It should show labels as it does, but also change tab bar colors.

**How to reproduce**

- You must provide a way to reproduce the problem. If you are having an issue with your machine or build tools, the issue belongs on another repository as that is outside of the scope of React Navigation.
- Either re-create the bug on [Snack](https://snack.expo.io) or link to a GitHub repository with code that reproduces the bug.
- Explain how to run the example app and any steps that we need to take to reproduce the issue from the example app.
- Keep the repro code as simple as possible, with the minimum amount of code required to repro the issue.
- Before reporting an issue, make sure you are on latest version of the package.

**Your Environment**

| software                      | version |
| ----------------------------- | ------- |
| iOS or Android                | iOS & Android
| @react-navigation/native      | "^5.1.5"
| @react-navigation/material-bottom-tabs | "^5.1.8"
| react-native-screens         | "^2.4.0"
| react-native                  | "0.62.0"
| expo                         | I don't use expo
| node                          | "v10.15.3"
| npm                   | "6.13.7"

**Comment by raajnadar** [comment]
Why are you using color names in upper case? Add a snack demo to understand your problem.

**Comment by ggunti** [comment]
It's just a variable, `BLUE = '#2089dc'` and `GREEN = '#008000'`

**Comment by raajnadar** [comment]
It is clearly stated in docs it won't work if shifting is false. https://reactnavigation.org/docs/material-bottom-tab-navigator/#tabbarcolor

**Comment by ggunti** [comment]
@raajnadar Thank you! You are right, I did not observe this. Then my question is: how can I show labels also for inactive tabs and also keeping tabbarcolor? `labeled={true}` don't work.

**Comment by raajnadar** [comment]
if `shifting={true}` and `labeled={true}` it will only show the active label and if you use `labeled={false}` all label will be hidden.

if `shifting={false}` and `labeled={true}` it will show all the label and if you use `labeled={false}` all the label will be hidden.

**Comment by ggunti** [comment]
@raajnadar Thanks for clarifying, but unfortunately none of this cases help me in what I want to achieve.
- If I set `shifting={false}`, tabbarcolor cannot be changed.
- If I set `shifting={false}` and `labeled={true}`, only the label for the active tab is visible (inactive tabs have no label).

What I want to achieve is to show always all the labels, but also to be able to change tabbarcolor when I switch from a tab to another.

**Comment by raajnadar** [comment]
I know none of the case will work I just wanted to clarify. No there is no possibility at this moment. You can send a PR to add this feature.

Maybe the feature you want is not possible to implement due to the ripple effect (I am assuming but you can give a try to fix this issue)

**Comment by satya164** [comment]
Material Bottom Tabs is just a wrapper around BottomNavigation from React Native Paper. Please open issues and feature requests regarding it in React Native Paper's repo: https://github.com/callstack/react-native-paper

**Comment by alkeshattal** [comment]
> @raajnadar Thanks for clarifying, but unfortunately none of this cases help me in what I want to achieve.
> 
> * If I set `shifting={false}`, all labels are visible, but tabbarcolor cannot be changed.
> * If I set `shifting={true}` and `labeled={true}`, only the label of the active tab is visible (inactive tabs label are not visible).
> 
> What I want to achieve is to show always all the labels, but also to be able to change tabbarcolor when I switch from a tab to another. Is it possible to achive this somehow?

@ggunti  were you able to achieve this feature/design, I'm also looking for same - show labels for all tabs with shifting true.

**Comment by ggunti** [comment]
@alkeshattal 
I was unable to achieve this feature (labels for all tabs + shifting) with this library.
Although, it is possible with [react-native-material-navigation](https://github.com/timomeh/react-native-material-bottom-navigation#readme), but I was unable to integrate with react-navigation.

**Comment by udhungana** [comment]
How about integrating icons with label. Meaning icon already have label in the picture.

**Comment by MAgungHKM** [comment]
in case someone need an answer to this, you need to use barStyle on <Tab.Navigator> like so:

```
<Tab.Navigator barStyle={{backgroundColor: 'steelblue'}} shifting={false} />
```

**Comment by elmcapp** [comment]
To use tabBarColor you have to set shifting to true. In the doc
By default, this is true when you have more than 3 tabs. Pass shifting={false} to explicitly disable this animation, or shifting={true} to always use this animation.

so if you have less than 3 or less tabs set shifting to true and it will work
