### ISSUE TITLE
navigation.reset() not working as expected

### ISSUE THREAD

**Issue by sebastianknopp** [react-navigation/react-navigation#7988]
**Current Behavior**

I have three screens: Home, First and Second. 

When user reaches Second, I want to remove Frist from navigation stack, so if the user presses the back-button on Second, it brings him to Home not to First. 

I try to achieve this by using the following code:
```
    props.navigation.reset({
      index: 1,
      routes: [
        { name: 'Home' },
        { name: 'Second' }
      ]
    });
```
Calling the above code removes Frist from the stack, but on call it cycles through the whole stack. Meaning it first loads Home and then Second. You can see how Home is loaded before Second.

**Expected Behavior**
Calling reset should update the stack but not cycling and loading all the screens in the stack after each other. 

I expect I can point navigation.goBack() to an item further down in the stack. 

**How to reproduce**
You can find an [example snack here](https://snack.expo.io/@sebastianknopp/481d06).

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | tested on iOS 13.3.1 in expo app
| @react-navigation/native       | ^5.1.5
| @react-navigation/stack        | ^5.2.10
| react-native-gesture-handler   | ~1.6.0
| react-native-safe-area-context | ^0.7.3
| react-native-screens           | ~2.2.0
| react-native                   | ~0.61.5
| expo                           | ~37.0.3
| npm or yarn                    | yarn

**Comment by raajnadar** [comment]
What about using `props.navigation.replace('Second')`

Add this code in First stack and after first will be replaced by Second stack.

**Comment by sebastianknopp** [comment]
`props.navigation.replace('Second')` works like a charm!

@raajnadar thanks a lot!

This solves my current problem!

Nevertheless, I think navigation.reset() should be either fixed or the documentation needs an update. If I remember correctly, in 4.x it used to work like I expected.

**Comment by raajnadar** [comment]
If you want you can see docs for reset also https://reactnavigation.org/docs/navigation-actions#reset

**Comment by sebastianknopp** [comment]
The documentation was updated. Now it makes perfect sense! Great, thanks a lot!
