### ISSUE TITLE
redux-devtools intregation not work

### ISSUE THREAD

**Issue by tastafur** [react-navigation/react-navigation#7991]
**Current Behavior**

- I upgrade version *@react-navigation/native to 5.1.5*, *@react-navigation/stack to 5.2.10* and *@react-navigation/bottom-tabs 5.2.6* and I saw that that *react-native-debugger* did not show now in the *Redux Devtool* the navigation status

![demostration-not-work-redux-devtools](https://user-images.githubusercontent.com/11853181/78934685-a685bc00-7aab-11ea-8bf9-7c9ab7f3b0b7.gif)

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| Android                 | Api 29 simulator |
| Ios                 | Iphone 11 13.4 v |
| @react-navigation/native       | 5.1.5 |
| react-native                   | 0.61.5 |
| node                           | 12.0.1 |
|  yarn                    | 1.22.0

**Comment by e1ferapontov** [comment]
same here

**Comment by andrey010** [comment]
I have the same problem. and besides, closeDrawer () broke when exiting the application. and now when you re-enter the driver opens which I can not close

**Comment by andrey010** [comment]
> **Current Behavior**
> 
> * I upgrade version _@react-navigation/native to 5.1.5_, _@react-navigation/stack to 5.2.10_ and _@react-navigation/bottom-tabs 5.2.6_ and I saw that that _react-native-debugger_ did not show now in the _Redux Devtool_ the navigation status
> 
> ![demostration-not-work-redux-devtools](https://user-images.githubusercontent.com/11853181/78934685-a685bc00-7aab-11ea-8bf9-7c9ab7f3b0b7.gif)
> 
> **Your Environment**
> 
> software	version
> Android	Api 29 simulator
> Ios	Iphone 11 13.4 v
> @react-navigation/native	5.1.5
> react-native	0.61.5
> node	12.0.1
> yarn	1.22.0

hi, did you solve this problem?

**Comment by andrey010** [comment]
In rn v61 you have to use debugger v 10

**Comment by flimble** [comment]
Same here @tastafur was this working for you in a previous version of @react-navigation/native?

**Comment by sefam-vbastien** [comment]
I'm using react-native 0.62.2
It was not working for me until I add this line into my code:
`global.REACT_NAVIGATION_REDUX_DEVTOOLS_EXTENSION_INTEGRATION_ENABLED = true`
Hope this help.

**Comment by khaledBou** [comment]
global.REACT_NAVIGATION_REDUX_DEVTOOLS_EXTENSION_INTEGRATION_ENABLED = true
where we should add this line ?

**Comment by sefam-vbastien** [comment]
We added it into the `index.js` right before registering the component, wrapped into a `if (__DEV__)` check

**Comment by raajnadar** [comment]
Closing since a solution is provided to fix the issue.

**Comment by tastafur** [comment]
Good afternoon
I have version 0.62.2 of react-native, @react-navigation/native 5.1.5, react-native-debugger 0.1.13 and i added this line in index.js 
`if (__DEV__) {
  global.REACT_NAVIGATION_REDUX_DEVTOOLS_EXTENSION_INTEGRATION_ENABLED = true;
}`

and it still doesn't work

**Comment by tastafur** [comment]
before in preview version if it work me without this line
`if (__DEV__) { global.REACT_NAVIGATION_REDUX_DEVTOOLS_EXTENSION_INTEGRATION_ENABLED = true; }`
