### ISSUE TITLE
Custom header glitches with react navigation 5

### ISSUE THREAD

**Issue by anam-hossain** [react-navigation/react-navigation#7997]
Hi guys, the Custom header (i.e. Nativebase header) is glitching with the latest version of react-navigation (v5.3.1). I have attached a gif file to demonstrate the glitch.

![react_navigation_5_header_glitch](https://user-images.githubusercontent.com/5017268/78954894-e1760700-7b20-11ea-9449-971abbd4496f.gif)

I am using a native base header with a custom component. 

The code looks like the following:

```js
class HomeHeader extends React.PureComponent {
  render() {
    return (
      <StyleProvider style={getTheme(platform)}>
        <Header>
          <Left />
          <Body>
            <Title>DuaCollection</Title>
          </Body>
        </Header>
      </StyleProvider>
    );
  }
}
```
```js
function HomeStack() {
  return (
    <Stack.Navigator
      initialRouteName="Home"
      headerMode="screen"
    >
      <Stack.Screen
        name="Home"
        component={HomeSreenContainer}
        options={{ 
          header: ({ navigation }) => <HomeHeader navigation={navigation}/>
        }}
      />
      <Stack.Screen
        name="List"
        component={ListScreen}
        options={{ 
          header: ({ navigation }) => <ListHeader navigation={navigation}/>
        }}
      />
    </Stack.Navigator>
  );
}
```
```js
function TabNavigator() {
  return (
    <Tab.Navigator>
      <Tab.Screen name="HomeTab" component={HomeStack} />
    </Tab.Navigator>
  );
}
```

```js
function AppNavigator() {
  return (
    <Stack.Navigator
      initialRouteName="Main"
      mode="modal"
      headerMode="none"
      screenOptions={{
        cardStyle: { backgroundColor: 'transparent' }
      }}
    >
      <Stack.Screen
        name="Main"
        component={TabNavigator}
      />
    </Stack.Navigator>
  );
}
```

#### My setup
node: v10.18.0
react-native: 0.61.5
react 16.9.0
native-base: 2.13.12
xcode 11.3

**Comment by sergchernata** [comment]
Same issue here, on IOS only.

**Comment by anam-hossain** [comment]
@sergchernata I have tried the `headerShown: true`. It is not working on my side.

```js
      <Stack.Screen
        name="Home"
        component={HomeSreenContainer}
        options={{
          headerShown: true,
          header: ({ navigation }) => <HomeHeader navigation={navigation}/>
        }}
      />
```

**Comment by satya164** [comment]
If you have a glitch in native base header, open issue with native base.

**Comment by anam-hossain** [comment]
@satya164 Any example with a custom header height? So that I can try in my code.

I have also opened the issue on Nativebase repo.

**Comment by sergchernata** [comment]
> If you have a glitch in native base header, open issue with native base.

This issue sounds exactly like what your documentation covers:

> If your header's height differs from the default header height, then you might notice glitches due to measurement being async. Explicitly specifying the height will avoid such glitches.

However, none of the settings I've tried fix it. That's why I too think it belongs here, not in NativeBase.

**Comment by satya164** [comment]
If you can repro issues without any third party libraries like native base, then open an issue about it.

**Comment by amilaDulanjana** [comment]
did you able to solve this ? I am having same issue

**Comment by svmszcck** [comment]
Same issue here, React Native Elements custom header is jumping on page load for 1 sec.

**Comment by LorenzoInvernizzi** [comment]
same issue here, not able to find a workaround.

**Comment by svmszcck** [comment]
I used this workaround until this bug is solved:

- Add "loaded" state variable by using "useState" hook.
- Set the opacity of the header wrapper to 0 initially
- Add timeout on component load by using useEffect hook and make the opacity 1 after 1 ms.

`const [loaded, setLoaded] = useState(false);

 useEffect(() => {
    setTimeout(() => {
      setLoaded(true);
    }, 1);
  }, []);

 return (
    <View style={{ opacity: loaded ? 1 : 0 }}>
     ...
    </View>
`

**Comment by kaivamannam** [comment]
I wrapped my <Navigator> in <SafeAreaProvider> and it fixed the problem.
