### ISSUE TITLE
Handle `react-native-dropdownalert` properly

### ISSUE THREAD

**Issue by rdewolff** [react-navigation/react-navigation#7999]
**Current Behavior**

- What code are you running and what is happening?

With nested stack navigation, the dropdown alert is not displayed properly. It's hidden behind the modal.

- Include a screenshot or video if it makes sense.

![dropdown-issue](https://user-images.githubusercontent.com/130704/78972077-3e67c200-7b0d-11ea-81c9-d450a7234661.gif)

**Expected Behavior**

- What do you expect should be happening?

We should be able to display the dropdown alert on top of all the navigation.

- Include a screenshot or video if it makes sense.

**How to reproduce**

- create any nested stack
- add the package `react-native-dropdownalert`
- display a dropdown alert

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | iOS
| @react-navigation/native       | 5.1.4
| @react-navigation/stack        | 5.0.5
| react-native-gesture-handler   | 1.6.1
| react-native-safe-area-context | 0.7.3
| react-native-screens           | 2.4.0
| react-native                   | 0.61.5
| expo                           | n/a
| node                           | 10.16.0
| npm or yarn                    | yarn 1.22.4

**Comment by rdewolff** [comment]
Dang, just missed the issue #8000 🙈

**Comment by satya164** [comment]
Please open issue in react-native-dropdownalert
