### ISSUE TITLE
navigation prop of type `any` and unresolved `StackNavigationProp` import

### ISSUE THREAD

**Issue by kromsik** [react-navigation/react-navigation#8004]
**Current Behavior**

navigation has `any` type
![image](https://user-images.githubusercontent.com/33729094/78998793-05057580-7b52-11ea-870c-408ea98433ca.png)

**Expected Behavior**

navigation is typed correctly

**How to reproduce**
Clone this repo
https://github.com/kromsik/fa-test
![image](https://user-images.githubusercontent.com/33729094/78998710-d7b8c780-7b51-11ea-9336-841ae04fee2f.png)

**Your Environment**

All the latest package versions

> {
  "name": "users",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios --simulator='iPhone Xs'",
    "start": "react-native start",
    "start:rc": "npm start -- --reset-cache",
    "test": "jest",
    "lint": "eslint . --ext .js,.jsx,.ts,.tsx"
  },
  "dependencies": {
    "@eva-design/eva": "^2.0.0-alpha.1",
    "@react-native-community/masked-view": "^0.1.7",
    "@react-native-community/netinfo": "^5.7.0",
    "@react-navigation/native": "^5.1.5",
    "@react-navigation/stack": "^5.2.10",
    "@types/react-redux": "^7.1.7",
    "@ui-kitten/components": "^5.0.0-alpha.1",
    "@ui-kitten/eva-icons": "^5.0.0-alpha.1",
    "axios": "^0.19.2",
    "react": "16.11.0",
    "react-native": "0.62.2",
    "react-native-appearance": "^0.3.3",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-reanimated": "^1.8.0",
    "react-native-safe-area-context": "^0.7.3",
    "react-native-screens": "^2.4.0",
    "react-native-svg": "^12.1.0",
    "react-redux": "^7.2.0",
    "redux": "^4.0.5",
    "redux-saga": "^1.1.3",
    "reselect": "^4.0.0"
  },
  "devDependencies": {
    "@babel/core": "^7.6.2",
    "@babel/runtime": "^7.6.2",
    "@react-native-community/eslint-config": "^1.0.0",
    "@types/jest": "^24.0.24",
    "@types/react-native": "^0.62.0",
    "@types/react-test-renderer": "16.9.2",
    "@typescript-eslint/eslint-plugin": "^2.27.0",
    "@typescript-eslint/parser": "^2.27.0",
    "babel-jest": "^24.9.0",
    "eslint": "^6.5.1",
    "eslint-config-react-native-wcandillon": "^2.7.0",
    "eslint-plugin-import": "^2.20.2",
    "jest": "^24.9.0",
    "metro-react-native-babel-preset": "^0.58.0",
    "prettier": "^2.0.4",
    "react-test-renderer": "16.11.0",
    "typescript": "^3.8.3"
  },
  "jest": {
    "preset": "react-native",
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "jsx",
      "json",
      "node"
    ]
  }
}

 software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | iOS and Android
| @react-navigation/native       | "^5.1.4"
| @react-navigation/stack        | ^5.2.9"
| react-native-gesture-handler   | "^1.6.1"
| react-native-safe-area-context | "^0.7.3"
| react-native-screens           | "^2.4.0"
| react-native                   | 0.62.2
| expo                           | none
| node                           | v12.13.1
| npm or yarn                    | npm

**Comment by satya164** [comment]
Closing since the GitHub repro provided in the issue doesn't exist. Please open a new issue with repro if you still have problems.
