### ISSUE TITLE
Preload HeaderBackButton for offline app support

### ISSUE THREAD

**Issue by summerkiflain** [react-navigation/react-navigation#8007]
**Current Behavior**

- HeaderBackButton imported from react-navigation-stack doesn't load for offline app

**Expected Behavior**

- Their should be a way to bundle headerBackButton in assets easily for offline first apps

**How to reproduce**

- Just add `import { HeaderBackButton } from 'react-navigation-stack'` to any template use it in the view and try to start the app without internet on first load, header back arrow will not be visible.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | both
| react-navigation               | 4.1.1
| react-navigation-stack         | 1.10.3
| react-navigation-tabs          | 2.7.0
| react-navigation-drawer        | 2.3.3
| react-native-reanimated        | 1.4.0
| react-native-gesture-handler   | 1.5.0
| react-native-safe-area-context | 
| react-native-screens           | 2.0.0-alpha.12
| react-native                   | https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz
| expo                           | 36.0.0
| node                           | 12.16.1
| npm or yarn                    | yarn 1.22.0

**Comment by satya164** [comment]
If you need to preload it, then preload it. Don't see why that's a bug in the package.

**Comment by summerkiflain** [comment]
@satya164 I have tried but there are many different png files for different views and platforms, i m using expo platform for developing an app for multiple platforms, is there a way we can use custom component in it probably which uses preloaded fonts already used in apps. FontAwesome or any other from vector-icons.

**Comment by garrottkai** [comment]
Why should a navigation package depend on internet access for core functionality? This doesn't quite make sense to me

**Comment by satya164** [comment]
Well, it doesn't depend on internet. But if you are caching JavaScript files on user's browser to load them offline, it's your responsibility to cache assets as well, I don't see how React Navigation can handle it.
