### ISSUE TITLE
How to increase space between one icon and another icon in material-bottom-tabs

### ISSUE THREAD

**Issue by ppv94** [react-navigation/react-navigation#8011]
**Current Behavior**

More space is left on Right and Left of the bottom tab bar, I am not able to align space equally between icons.
![sample](https://user-images.githubusercontent.com/28724702/79052920-4d5a8b80-7c57-11ea-91ea-f1ccc6f48f96.png)

**Expected Behavior**

I am using material-bottom-tabs and I want to increase space between one icon and another icon in material-bottom-tabs ( or ) align icons space equally.

**Your Environment**

| software                               | version |
| -------------------------------------- | ------- |
| iOS or Android                         | android
| @react-navigation/native               |^5.1.5
| @react-navigation/material-bottom-tabs |^5.1.8
| react-native-paper                     |
| react-native                           |0.62.1
| expo                                   |
| node                                   |12.16.1
| npm or yarn                            |6.14.3

**Comment by satya164** [comment]
Material Bottom Tabs is just a wrapper around BottomNavigation from React Native Paper. Please open issues and feature requests regarding it in React Native Paper's repo: https://github.com/callstack/react-native-paper
