### ISSUE TITLE
add backgroundColor in tabStyle override indicatorStyle backgroundColor

### ISSUE THREAD

**Issue by zxccvvv** [react-navigation/react-navigation#8012]
**Current Behavior**

```
<Tab.Navigator
  screenOptions={({route})=>({
    tabBarIcon:({color})=>{
      return <Icon name={iconName[route.name]} size={28} color={color}/>
    },
  })}
  tabBarOptions={{
    activeTintColor:'white',
    inactiveTintColor:'lightgrey',
    showIcon:true,
    tabStyle:{height:50, backgroundColor:'#311b92ee'},
    indicatorStyle:{backgroundColor:'red',},
    iconStyle:{width:'100%'},
    style:{justifyContent:'center'},
  }}
  lazy={true}
>
  <MainStack.Screen name="Home" component={Home}/>
  <MainStack.Screen name="Kasus" component={Kasus}/>
  <MainStack.Screen name="Pencegahan" component={Pencegahan}/>
</Tab.Navigator>
```

![image](https://user-images.githubusercontent.com/19633881/79066615-922c0400-7ce3-11ea-8f9b-3405c4b9755c.png)

without `backgroundColor` in `tabStyle`:

```
tabBarOptions={{
  activeTintColor:'white',
  inactiveTintColor:'lightgrey',
  showIcon:true,
  tabStyle:{height:50},
  indicatorStyle:{backgroundColor:'red',},
  iconStyle:{width:'100%'},
  style:{justifyContent:'center'},
}}
```
![image](https://user-images.githubusercontent.com/19633881/79066659-d3241880-7ce3-11ea-897f-cadacefef5c9.png)

**Expected Behavior**

should not override the backgroundColor of indicatorStyle

**Your Environment**

| software                            | version |
| ----------------------------------- | ------- |
| iOS or Android                      | Android (doesn't env to build in iOS)
| @react-navigation/native            | ^5.1.5
| @react-navigation/material-top-tabs | 5.1.8
| react-native-tab-view               | 2.14.0
| react-native                        | 0.62.2
| expo                                | using RN Init

**Comment by raajnadar** [comment]
You should do like this 

```
style: {
  backgroundColor: '#000' // Style the tab bar
},
indicatorStyle: {
  backgroundColor: '#FFF' // Style the indicator
}
```

**Comment by anupamcyber** [comment]
Why backgroundcolor will not work
