### ISSUE TITLE
Sending props from bottom navigator to screen

### ISSUE THREAD

**Issue by Sapkotaanish** [react-navigation/react-navigation#8013]
**Current Behavior**

I am trying to send props to screen. I have defined: 

`const Tab = createBottomTabNavigator();`

When I use the following code, it works fine.

` <Tab.Navigator> <Tab.Screen  name="HomeScreen" >{props => <HomeScreen locationUpdated={this.locationUpdate} /> }</Tab.Screen> </Tab.Navigator>`

But when a space is used before '{' or after '}' , react naive throws an error.

` <Tab.Navigator> <Tab.Screen  name="HomeScreen" > {props => <HomeScreen locationUpdated={this.locationUpdate} /> }</Tab.Screen> </Tab.Navigator>`

![Screenshot_20200412-173218](https://user-images.githubusercontent.com/38289476/79070216-01115900-7cf4-11ea-95ca-e0786b64a584.png)

**Expected Behavior**

I think it must work fine with both the codes. Is it the bug or my misunderstanding?

**Your Environment**

| software                      | version |
| ----------------------------- | ------- |
| Android                |  9
| @react-navigation/native      |  5.1.5
| react-native                  | 0.62.1
| node                          | 12.16.1
| npm                  | 6.14.4

**Comment by satya164** [comment]
A space in JSX is a string which is not allowed as children of screen.
