### ISSUE TITLE
Styles not applying to custom drawer background even with drawer styles

### ISSUE THREAD

**Issue by rebirthtobi** [react-navigation/react-navigation#8014]
**Current Behavior**
- What code are you running and what is happening?
I am trying to achieve border-radius on the custom drawer content but I still get an underlying white background (see the white background on the custom drawer in the pic)
```
const Drawer = createDrawerNavigator<DrawerParamList>();

const styles = StyleSheet.create({
    drawerStyle: {
        backgroundColor:         "red",
        borderBottomRightRadius: 35,
        borderTopRightRadius:    35,
        width:                   90,
    },
});

export default function Navigation() {
    return (
        <NavigationContainer>
            <Drawer.Navigator
                initialRouteName="Feed"
                backBehavior="history"
                drawerType="slide"
                drawerContent={SideBar}
                drawerStyle={styles.drawerStyle}
            >
                <Drawer.Screen name="Home" component={Home} />
                <Drawer.Screen name="Feed" component={Feed} />
                <Drawer.Screen name="Twitter" component={Twitter} />
            </Drawer.Navigator>
        </NavigationContainer>
    );
}

```
<img width="382" alt="Screenshot 2020-04-12 at 16 03 55" src="https://user-images.githubusercontent.com/20771062/79072239-de714700-7cd7-11ea-98ee-14ef66bc326d.png">

**Expected Behavior**
I will expect that there should be no white background after applying the border-radius which

**How to reproduce**
To reproduce, apply border-radius and color to drawer styles, you should see the white background underneath

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | both |
| @react-navigation/native       |  ^5.1.5 |
| @react-navigation/drawer       | ^5.4.1 |
| react-native-reanimated        | ^1.8.0 |
| react-native-gesture-handler   | ^1.6.1 |
| react-native-safe-area-context | ^0.7.3 |
| react-native-screens           | ^2.4.0 |
| react-native                   | 0.62.2 |
| expo                           | Using RN init |
| node                           | v10 |
| npm or yarn                    | yarn |

**Comment by raajnadar** [comment]
Can you add the SideBar code that you passed to drawerContent prop.

**Comment by rebirthtobi** [comment]
@raajnadar this is code hosted on snack.expo.io

https://snack.expo.io/@rebirthtobi/9cb6b1

**Comment by satya164** [comment]
You have `drawerType` set to `slide` so the drawer appears side by side with the screen. There's **nothing below the drawer**, so this is expected behaviour that you don't see the screen below the drawer, since you positioned it on side of the drawer.

**Comment by SLAYER-CODE** [comment]
`
        <Drawer.Navigator screenOptions={{drawerStyle:{backgroundColor:'transparent'}}}  initialRouteName={'Auth'}  drawerContent={(props:DrawerContentComponentProps) => <Menu propiedades={props}/> } >
            <Drawer.Screen name="Auth" component={Auth} />
            <Drawer.Screen name="Main" component={Main} />
        </Drawer.Navigator>
`

**Comment by MiteshKalal7** [comment]
> `<Drawer.Navigator screenOptions={{drawerStyle:{backgroundColor:'transparent'}}} initialRouteName={'Auth'} drawerContent={(props:DrawerContentComponentProps) => <Menu propiedades={props}/> } > <Drawer.Screen name="Auth" component={Auth} /> <Drawer.Screen name="Main" component={Main} /> </Drawer.Navigator>`

`screenOptions={{drawerStyle:{backgroundColor:'transparent'}}}`
working

**Comment by rameshmarandi** [comment]
> screenOptions={{drawerStyle:{backgroundColor:'transparent'}}}

It's work for me , Thank YOu

**Comment by codeYard17** [comment]
@MiteshKalal7 @rameshmarandi Have you tried the code for ios as backgroundColor: 'transparent' working fine with android but not with ios.

**Comment by evgenyshenets91** [comment]
it doesn’t work for v6 drawer, someone know how to deal with it? Thanks

**Comment by evgenyshenets** [comment]
Found solution, we have to add `drawerType: 'front'` in screenOptions Drawer.Navigator and then in `drawerStyle:{borderRadius: 20 }`

**Comment by codeYard17** [comment]
Thanks @evgenyshenets your solution worked for v6
