### ISSUE TITLE
ModalPresentationIOS background color

### ISSUE THREAD

**Issue by QQizi** [react-navigation/react-navigation#8015]
**Current Behavior**

- When open a modal with `CardStyleInterpolators.forModalPresentationIOS` the background is white instead of black.

<img width="403" alt="Capture d’écran 2020-04-12 à 17 37 11" src="https://user-images.githubusercontent.com/2890748/79072990-475ebc00-7ce4-11ea-9cac-80761c3e7fe0.png">

**Expected Behavior**

- The background of the app should be black when a IOS 13 modal is opened 

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | 13.4
| @react-navigation/native       |5.1.4
| @react-navigation/stack        |5.2.10
| react-native-gesture-handler   |1.6.1
| react-native-safe-area-context |0.7.3
| react-native-screens           |2.4.0
| react-native                   |0.61.5
| expo                           |
| node                           |13.0
| npm or yarn                    |1.22.4

**Comment by satya164** [comment]
Set `cardOverlayEnabled: true` as mentioned in docs

**Comment by QQizi** [comment]
@satya164 This is not `cardOverlayEnabled`, the color i referred is the color behind the Scene that scale. You can see it when you use the Calendar app on iPhone and press the add button.
The color at the very top of the app, behind the bottom scene is black (no matter if in dark or light mode

**Comment by bkbooth** [comment]
@QQizi it looks like `backgroundColor` at the top-level of _app.json_ controls this. Setting it to `#000000` there fixed it for me. (https://docs.expo.io/versions/latest/workflow/configuration/#backgroundcolor)

**Comment by bkbooth** [comment]
Apologies, my answer is Expo-specific. I assume it'd be similar in any case, I think the color you're seeing is the app's background color, not the background color of any specific screen or component.

**Comment by QQizi** [comment]
@bkbooth Apparently `backgroundColor` in app.json of Expo is refering to the color of the root view which can be changed in `AppDelegate.m` which I did.
Still no change. 

`  rootView.backgroundColor = [[UIColor alloc] initWithRed:0.00f green:0.00f blue:0.00f alpha:1];`

Background of root view is black, means that the code above worked, but the background behind the modal is still white

**Comment by QQizi** [comment]
@bkbooth Got it to work with the code above and `cardStyle: { backgroundColor: 'transparent' }` on the `stackNavigator`

**Comment by tongao** [comment]
The default theme has a background color, so the background is not black.
https://reactnavigation.org/docs/themes/

**Comment by Navipro70** [comment]
In my case I have provider: `SafeAreaProvider` from `react-native-safe-area-context` on top of the App. And It set background color based on app theme (for dark theme: 'black', for light theme: 'white'). Just give it style props like that: 
```
<SafeAreaProvider style={{backgroundColor: 'black'}}>
    ...
</SafeAreaProvider>
```
