### ISSUE TITLE
Navigating into a screen deep in not mounted stack

### ISSUE THREAD

**Issue by radko93** [react-navigation/react-navigation#8022]
**Current Behavior**

I have a stack inside a drawer item. I'm navigating to a screen that is not the initial screen of the stack after opening a notification (either in background or foreground). This works but how to build the navigation actions so I can go back from the screen that's deep? Even if I change the item in the drawer the next time I come back the "deep" screen is mounted.

**Expected Behavior**

I can navigate to a route deep in a stack and set up a hierarchy so it's possible to come back the usual way. Or be able to leave the stack (switch to another one in the drawer) and next time open stack with initial screen open.

**How to reproduce**
I'm trying something like this
```
containerRef.current.dispatch(
            CommonActions.navigate({
              name: "Root", // Drawer navigator name
              params: {
                screen: "First", // Name of the first item in drawer navigator
                params: {
                  screen: "screen2" // screen deep in the stack
                }
              },
              source: 'screen1'
            })
          )
```
Expo app: https://expo.io/@radko93/nav-repro
Repro code: https://github.com/radko93/nav-repro/blob/master/App.js

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                both |
| @react-navigation/native      latest |
| @react-navigation/stack      latest  |
| react-native-gesture-handler   |
| react-native-safe-area-context |
| react-native-screens          2.2.0 |
| react-native                   |
| expo                         37  |
| node                       13    |
| npm or yarn                  yarn  |

**Comment by okwast** [comment]
Hey, I'm facing a similar issue at the moment.
The documentation says you can set the param `initial` to `false`.
See: https://reactnavigation.org/docs/nesting-navigators/#rendering-initial-route-defined-in-the-navigator

However I was not able to make this work yet.

I tried:
```ts
navigation.navigate("Navigator", {
  screen: "SecondScreen",
  initial: false,
});
```
But this ignores the initial value and just sets the second screen as initial one.
In the navigator I set "FirstScreen" as initialRoute.

---

I was able to workaround this with navigating to the first screen and then after 1ms to the second one. But this doesn't feel the same and doesn't feel nice to code 😕 

```
navigation.navigate("Navigator", {
  screen: "FirstScreen",
});
setTimeout(() => {
  navigation.navigate("Navigator", {
    screen: "SecondScreen",
  });
}, 1);
```

**Comment by flexsurfer** [comment]
initial parameter was added here https://github.com/react-navigation/react-navigation/releases/tag/%40react-navigation%2Fcore%405.3.4, so just bump react-navigation deps to latest and it will work

**Comment by okwast** [comment]
I updated everything yesterday anyhow and now it works perfectly fine 🎉 

Thanks a lot for the hint, should have checked that myself though.

**Comment by codecog** [comment]
Experiencing this issue with the latest version. Setting `initial: false` when navigating to a nested stack in a different tab. The screen being navigated to then becomes the initial screen of that stack.

**Comment by raajnadar** [comment]
I seems like the issue is resolved! If not let me know I will reopen the issue.

**Comment by codecog** [comment]
Oh, must have misunderstood. I'm having the issue stated here.

`navigation.navigate('Foo', { screen: 'my-screen', initial: false })`

This will set 'my-screen' as the initial screen of the stack which is incorrect according to the docs? If i use this, whenever i go back to the stack then 'my-screen' is what will be shown, even when unmounting.

**Comment by codecog** [comment]
Please keep the issue open as there is a problem with how it currently works

**Comment by SohelIslamImran** [comment]
Is there any update?

**Comment by SohelIslamImran** [comment]
When I navigate to a deeper stack screen with navigation.navigate() before mount, I get error `The action 'NAVIGATE' with payload  was not handled by any navigator.`

**Comment by satya164** [comment]
Please open a new issue with repro
