### ISSUE TITLE
cardStyleInterpolator visual glitches on Android (header)

### ISSUE THREAD

**Issue by Guuz** [react-navigation/react-navigation#8023]
**Current Behavior**
The cardStyleInterpolator `forFadeFromBottomAndroid` and `forScaleFromCenterAndroid` show visual glitches on Android. Look at the shadow of the header in the videos below:

Had some trouble converting and uploading as gif, so:

- https://streamable.com/6kid2v
- https://streamable.com/dxruzx

![Screen-Recording-2020-04-13-at-1](https://user-images.githubusercontent.com/810327/79119394-8a766900-7d90-11ea-8915-0670dd13283b.gif)

**Expected Behavior**

Not to have glitches, like the other cardStyleInterpolator's

**How to reproduce**

```tsx
<Stack.Navigator
      screenOptions={{
        cardStyleInterpolator: CardStyleInterpolators.forFadeFromBottomAndroid,
      }}>
...
</Stack.Navigator>
```

**Your Environment**

Updated everything to the latest version.

**Comment by satya164** [comment]
It's a bug in React Native https://github.com/facebook/react-native/issues/23090
