### ISSUE TITLE
SafeArea color in dark mode cannot be changed

### ISSUE THREAD

**Issue by mkhaledche** [react-navigation/react-navigation#8025]
**Current Behavior**
I have been trying to adjust the color of safeArea in iPhone X, it's working well on the top, and in the bottom as well for screens with no tab, however, in screens with tab navigator, the bottom safeArea is always white as shown in the screenshot. 

Also, I want to ask if it would be better to use normal SafeAreaView component and remove the SafeAreaProvider and remove react-native-safe-area-context package, I just added it as a trial to solve this problem but I was first working with the react native normal SafeAreaView component; 

- What code are you running and what is happening?

In App component:
```
import { SafeAreaProvider } from "react-native-safe-area-context";
          <SafeAreaProvider>
            <NavigationContainer>
              <CatNavigator />
            </NavigationContainer>
          </SafeAreaProvider>

```
In the CatNavigator component:
```
const CatNavigator = () => {
  return (
    <Drawer.Navigator
      initialRouteName="Home"    >
      <Drawer.Screen
        name="Home"
        component={SettingsNavigator}
        options={{ title: "Inicio" }}
      />
    </Drawer.Navigator>

```
In the settings tab navigator:
```
const SettingsNavigator = () => {
  return (
    <Tab.Navigator
      screenOptions={({ route }) => ({
        tabBarIcon: ({ focused, color, size }) => {
          let iconName;
          const iconType = Platform.OS === "ios" ? "ios" : "md";
          if (route.name === "Home") {
            iconName = iconType + "-home";
          } else if (route.name === "Settings") {
            iconName = iconType + "-settings";
          }
          const tabColor = focused ? Colors.buttonBackColor : Colors.titleColor;
          return <Ionicons name={iconName} size={size} color={color} />;
        },
      })}
      tabBarOptions={{
        activeTintColor: Colors.activeTabColor,
        inactiveTintColor: Colors.inactiveTabColor,
        activeBackgroundColor: Colors.tabBackgroundColor,
        inactiveBackgroundColor: Colors.tabBackgroundColor,
        safeAreaInset: { bottom: "never", top: "never" },
      }}
    >
      <Tab.Screen
        name="Home"
        component={HomeNavigator}
        options={{ title: "Inicio" }}
      />
      <Tab.Screen
        name="Settings"
        component={SettingStackNavigator}
        options={{ title: "Ajustes" }}
      />
    </Tab.Navigator>

```
In SettingsNavigator:
```
const SettingStackNavigator = (props) => {
  return (
    <SettingStack.Navigator screenOptions={defaultNavOptions}>
      <SettingStack.Screen
        name="Settings"
        component={SettingScreen}
        options={settingsOptions}
      />
    </SettingStack.Navigator>
  );
};

```
And finally in SettingScreen:
```
import { SafeAreaView } from "react-native-safe-area-context";
    return (
      <SafeAreaView
        style={{
             flex: 1,
    backgroundColor: Colors.backgroundColor,
          justifyContent: "center",
          alignItems: "center",
        }}
      >
        {colorScheme === "dark" && <StatusBar barStyle="light-content" />}
       // Other components
      </SafeAreaView>

```

- Include a screenshot or video if it makes sense.
![93257830_634558760434219_882196620584681472_n](https://user-images.githubusercontent.com/33604455/79123024-797e2580-7d99-11ea-9510-2aa259972bc7.jpg)

**Expected Behavior**

The bottom tab safeArea to have the same background color

**Your Environment**

| software                      | version |
| ----------------------------- | ------- |
| iOS or Android                | iOS
| @react-navigation/native      | 5.1.4
| @react-navigation/bottom-tabs | 5.2.5
| react-native-screens          | ~2.2.0
| react-native                  | "https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz"
| expo                          |  ~37.0.3
| node                          | 12.6.1
| npm or yarn                   | npm

**Comment by satya164** [comment]
Use `style: { backgroundColor }` instead of `inactiveBackgroundColor`
