### ISSUE TITLE
Deeplinks config object optional path params 

### ISSUE THREAD

**Issue by gothraven** [react-navigation/react-navigation#8027]
**Current Behavior**

```js
const { getInitialState } = useLinking(ref, {
  prefixes: ['https://mychat.com', 'mychat://'],
  config: {
    Chat: 'feed/:sort',
  },
});
```
this will work fine
```
mychat://feed/desc
mychat://feed/asc
```
but what if we want to call that page without any parms ?
```
mychat://feed/
```
this one does no work because there is no params

**Expected Behavior**

I expect it to work and let the page handle the fact that there is no parms

if this is not a bug, then what about this idea ?
```js
const { getInitialState } = useLinking(ref, {
  prefixes: ['https://mychat.com', 'mychat://'],
  config: {
    Chat: 'feed/:sort?', // ? to say that this param is optional
  },
});
```

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |
| @react-navigation/native       | ^5.1.5
| react-native                   | 0.61.5
| expo                           | 
| node                           | 8.16.2
| npm                    | 6.4.1

**Comment by satya164** [comment]
It should work as expected after updating https://reactnavigation.org/docs/configuring-links#updating-config

You can also test your config here https://reactnavigation.org/docs/configuring-links#playground
