### ISSUE TITLE
safeAreaInsets being ignored for header options

### ISSUE THREAD

**Issue by da1z** [react-navigation/react-navigation#8029]
I have this stack inside Tab navigator:
```
return (
    <DiscoverStack.Navigator>
      <DiscoverStack.Screen
        name="Discover"
        component={HomeScreen}
        options={{ headerShown: false, safeAreaInsets: { top: 50 } }}
      />
    </DiscoverStack.Navigator>
  );
```

and safeAreaInsets is being ignored:
<img width="389" alt="Screen Shot 2020-04-13 at 2 35 52 PM" src="https://user-images.githubusercontent.com/4012422/79163573-3077a280-7d94-11ea-926c-d6dd6ce0c28d.png">

**Comment by satya164** [comment]
https://reactnavigation.org/docs/handling-safe-area/
