### ISSUE TITLE
Example code in the BottomTabNavigator doc raises an error

### ISSUE THREAD

**Issue by AkihikoITOH** [react-navigation/react-navigation#8030]
This probably isn't a bug, but rather a mere documentation issue.

Related to https://github.com/react-navigation/react-navigation/issues/7368

**Current Behavior**

Example shown on https://reactnavigation.org/docs/bottom-tab-navigator#example would generate the following error.
![Screenshot_1586819015](https://user-images.githubusercontent.com/4457682/79169183-0a7dec80-7dec-11ea-8066-5627a4baa27e.png)

**Expected Behavior**

Example code works as expected.
![Screenshot_1586819316](https://user-images.githubusercontent.com/4457682/79169345-7e1ff980-7dec-11ea-8466-f4df032ae75c.png)

**How to reproduce**

This is the `App.js` that reproduces the issue ([the example](https://reactnavigation.org/docs/bottom-tab-navigator#example) in the doc + import, `NavigationContainer`, etc).

```js
// App.js

import React, {Component} from 'react';
import {Text} from 'react-native';
import {NavigationContainer} from '@react-navigation/native';
import {createBottomTabNavigator} from '@react-navigation/bottom-tabs';
import {MaterialCommunityIcons} from 'react-native-vector-icons';

const Tab = createBottomTabNavigator();

const Feed = () => <Text>Feed</Text>;
const Notifications = () => <Text>Notifications</Text>;
const Profile = () => <Text>Profile</Text>;

function MyTabs() {
  return (
    <Tab.Navigator
      initialRouteName="Feed"
      tabBarOptions={{
        activeTintColor: '#e91e63',
      }}>
      <Tab.Screen
        name="Feed"
        component={Feed}
        options={{
          tabBarLabel: 'Home',
          tabBarIcon: ({color, size}) => (
            <MaterialCommunityIcons name="home" color={color} size={size} />
          ),
        }}
      />
      <Tab.Screen
        name="Notifications"
        component={Notifications}
        options={{
          tabBarLabel: 'Updates',
          tabBarIcon: ({color, size}) => (
            <MaterialCommunityIcons name="bell" color={color} size={size} />
          ),
        }}
      />
      <Tab.Screen
        name="Profile"
        component={Profile}
        options={{
          tabBarLabel: 'Profile',
          tabBarIcon: ({color, size}) => (
            <MaterialCommunityIcons name="account" color={color} size={size} />
          ),
        }}
      />
    </Tab.Navigator>
  );
}

export default class App extends Component {
  render() {
    return (
      <NavigationContainer>
        <MyTabs />
      </NavigationContainer>
    );
  }
}
```

Simply replacing the line importing `MaterialCommunityIcons` with

```js
import MaterialCommunityIcons from 'react-native-vector-icons/MaterialCommunityIcons';
```

as suggested on https://github.com/oblador/react-native-vector-icons/issues/937 fixes the problem.
Therefore I suspect this is merely the example being outdated.
If someone from the team can confirm this needs to be fixed, I'll happily create a pull request.

**Your Environment**

| software                      | version |
| ----------------------------- | ------- |
| Android                | 9 (emulator)
| @react-navigation/native      | 5.1.5
| @react-navigation/bottom-tabs | 5.2.6
| react-native-screens          | 2.4.0
| react-native                  | 0.62.2
| node                          | 13.8.0
| npm or yarn                   | 6.13.6
| react-native-vector-icons | 6.6.0

**Comment by satya164** [comment]
fixed
