### ISSUE TITLE
Stack Navigator not working on production

### ISSUE THREAD

**Issue by RavisaraDev** [react-navigation/react-navigation#8031]
**Current Behavior**
I'm using stack navigator inside the tab navigator. I'ts working perfectly on development mode. But when it comes to production the only stack navigator not working. No errors, no crashes, It just not navigating through screens.

This is how i navigate through pages
`onPress={() => navigation.navigate(CreateProfile)}`

**My Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android  | "Android" 
| @react-navigation/native        |"^5.1.4"
| @react-navigation/stack       |"^5.2.9"  
| react-native-gesture-handler   | "^1.6.1"
| react-native-safe-area-context  |"^0.7.3"
| react-native-screens            |"^2.4.0"
| react-native                  |"0.62.1  
| expo                         |"false" 
| node                      |"v12.14.0"    
| yarn                 |"1.21.1"

**Comment by satya164** [comment]
Closing since you didn't provide a repro.

**Comment by HoWWWWWhy** [comment]
I I also have same problem....

**Comment by HoWWWWWhy** [comment]
I remember I solved the problem like below.

onPress={() => navigation.navigate(CreateProfile)}

should be

onPress={() => navigation.navigate('CreateProfile')}
