### ISSUE TITLE
setParams will trigger tabBarIcon focused false to true

### ISSUE THREAD

**Issue by L-x-C** [react-navigation/react-navigation#8039]
**Current Behavior**
When i in a tab view, I setParams in my onScroll Event, and every time  i setParams, it will trigger tabBarIcon's **focused** property **false** first ,then **true**

**Expected Behavior**
it should not change tabBarIcon's **focused** property 

**Your Environment**

| software                      | version |
| ----------------------------- | ------- |
    "@react-navigation/bottom-tabs": "^5.1.1",
    "@react-navigation/compat": ">=5.1.1",
    "@react-navigation/core": ">=5.2.1",
    "@react-navigation/drawer": ">=5.1.1",
    "@react-navigation/material-bottom-tabs": ">=5.1.1",
    "@react-navigation/material-top-tabs": ">=5.1.1",
    "@react-navigation/native": ">=5.0.9",
    "@react-navigation/routers": ">=5.1.0",
    "@react-navigation/stack": ">=5.1.1",

**Comment by satya164** [comment]
Please open a new issue if you have a bug. A function being called with some arguments is not a bug unless it's causing any unexpected behaviour.
