### ISSUE TITLE
React Navigation Hook for the setOptions

### ISSUE THREAD

**Issue by nateblog** [react-navigation/react-navigation#8042]
Is there a react navigation hook that allows me to get the setOptions info?

[![enter image description here][1]][1]

Right now I can only get the information above via header props:

    <Stack.Screen name="tab_menu" options={{ headerShown: true, header: (props) => console.log(props) }}></Stack.Screen>

And currently there is an issue using a custom header in iOS...so I am changing my approach... Below is the UI issue when using custom header in iOS.

[![enter image description here][2]][2]

it overlaps, the previous screen header still shows on the focused screen

[![enter image description here][3]][3]

Is there a way to fix this overlapping issue or is there a way to get the setOptions info?

**Environment**

"react-native": "0.61.5",
"@react-navigation/native": "^5.1.5",
"@react-navigation/stack": "^5.2.10",

**Platform**

iOS only

  [1]: https://i.stack.imgur.com/Rgjm2.png
  [2]: https://i.stack.imgur.com/lx6tF.png
  [3]: https://i.stack.imgur.com/onAHB.png

**Comment by nateblog** [comment]
It appears the previous screen header overlaps the current screen

**Comment by nateblog** [comment]
Just to get things released, I am just using `setParams` for now instead of `setOptions`... I just hope there is a hook called `useDescriptor` so we can get those payload inside descriptor object... Hope the custom header issue will be fixed.

**Comment by satya164** [comment]
https://reactnavigation.org/docs/stack-navigator#set-headermode-to-screen

**Comment by nateblog** [comment]
> https://reactnavigation.org/docs/stack-navigator#set-headermode-to-screen

I think you can see in the screenshot above that the `headerMode` is already set to `screen`.

**Comment by satya164** [comment]
I can't see your code in your screenshot. If you think there's a bug, please open an issue with a runnable repro that I can debug.
