### ISSUE TITLE
Not assignable type mismatch for component param

### ISSUE THREAD

**Issue by crystalneth** [react-navigation/react-navigation#8044]
**Current Behavior**
The following gives an error:
```
            <Tab.Navigator>
              <Tab.Screen name="Schedule" component={<View/>}></Tab.Screen>
            </Tab.Navigator>
```

```
Type 'Element' is not assignable to type 'ComponentType<any>'.
  Type 'Element' is not assignable to type 'FunctionComponent<any>'.
    Type 'Element' provides no match for the signature '(props: any, context?: any): ReactElement<any, any> | null'.ts(2322)
```

Also nesting the View :

```
            <Tab.Navigator>
              <Tab.Screen name="Schedule"><View/></Tab.Screen>
            </Tab.Navigator>
```
```
Type 'Element' is not assignable to type '(props: { route: RouteProp<Record<string, object | undefined>, "Schedule">; navigation: any; }) => ReactNode'.
  Type 'Element' provides no match for the signature '(props: { route: RouteProp<Record<string, object | undefined>, "Schedule">; navigation: any; }): ReactNode'.ts(2322)
```

**Expected Behavior**

View
**How to reproduce**

- You must provide a way to reproduce the problem. If you are having an issue with your machine or build tools, the issue belongs on another repository as that is outside of the scope of React Navigation.
- Either re-create the bug on [Snack](https://snack.expo.io) or link to a GitHub repository with code that reproduces the bug.
- Explain how to run the example app and any steps that we need to take to reproduce the issue from the example app.
- Keep the repro code as simple as possible, with the minimum amount of code required to repro the issue.
- Before reporting an issue, make sure you are on latest version of the package.

**Your Environment**

| software                            | version |
| ----------------------------------- | ------- |
| iOS or Android                      |
| @react-navigation/native            |. 5.1.4
| @react-navigation/material-top-tabs | 5.1.8
| react-native-tab-view               | 2.14.0
| react-native                        | 0.62.1
| expo                                |
| node                                |.                                                                                                                                                             
| npm or yarn                         |

**Comment by satya164** [comment]
Well it gives error because your code is not correct.

**Comment by crystalneth** [comment]
It's not clear to me why this would not work, even if I can see that the type is not accepted.

I worked around this with a simple wrapper that conforms the types. I'm not sure if this has any unintended side effects, and if not why react-navigation would not just support arbitrary JSX components.

`  const TabWrapper = (wrapped:any) => () => wrapped
`

which can be used:

`
          <Tab.Navigator>
            <Tab.Screen name="Schedule" component={TabWrapper(<View style={{flex: 1, backgroundColor: 'red'}}></View>)}></Tab.Screen>
          </Tab.Navigator>
`

**Comment by satya164** [comment]
`() => <View style={...}></View>` is not the same as `<View style={...}></View>`

> react-navigation would not just support arbitrary JSX components

`<View />` is an JSX element, not a component. also see https://reactnavigation.org/docs/hello-react-navigation#passing-additional-props

**Comment by crystalneth** [comment]
Is `() => <View style={...}></View>` incorrect or going to cause problems in any way?
