### ISSUE TITLE
Header Flickering & Modal Header doesn't completely disappear behind Bottom Tab until a second later when using TabBarVisible after upgrading react-navigation-stack

### ISSUE THREAD

**Issue by AndresTIY** [react-navigation/react-navigation#8045]
**Current Behavior**

So I needed more control over transition animations and noticed I needed `TransitionPresets` from `react-navigation-stack`. I was using version `1.9.4` before but transition presets didn't exist, so I updated the version to `2.3.11` in which it did exist. I had to change a few other items around to fix deprecation warnings. I noticed that with screens that require `tabBarVisible: false` , and with `mode: 'modal'`, the screen header would flicker and when dismissed, the screen moves from top to bottom as expected but that screen's header doesn't disappear behind the bottom tab bar. It sort of persists just above the tab bar for a second then fades out a second later. 

Here's a snippet of the code I'm using:

```js
import React from 'react';
import { createBottomTabNavigator } from 'react-navigation-tabs';
import { createStackNavigator } from 'react-navigation-stack';

const BOTTOM_TAB_SHADOW = {
  shadowColor: 'black',
  shadowOffset: { width: 0, height: 2 },
  shadowOpacity: 0.3,
  shadowRadius: 3,
  elevation: 5,
};

const TabNavConfig = {
  initialRouteName: 'Screen1',
  header: null,
  headerMode: 'none',
  tabBarOptions: {
    activeTintColor: 'blue',
    inactiveTintColor: 'grey',
    style: {
      backgroundColor: 'white',
      borderTopColor: 'grey',
      height: 56,
      BOTTOM_TAB_SHADOW,
    },

    labelStyle: {
      fontSize: 26,
    },
  },
};

const RouteConfigs = {
  Stack1: {
    screen: Stack1,
    navigationOptions: ({ navigation }) => {
      const currentRoute = navigation.state.routes[navigation.state.index];
      let tabBarVisible = true;
      let routeName;
      if (currentRoute && currentRoute.routeName) {
        routeName = currentRoute.routeName;
      }

      if (routeName === 'Modal1') {
        tabBarVisible = false;
      }
      return {
        tabBarLabel: 'Stack 1',
        tabBarVisible,

        tabBarIcon: ({ tintColor }) => (
          <Icon name="home" tintColor={tintColor} />
        ),
      };
    },
  },

  Stack2: {
    screen: Stack2,
    navigationOptions: {
      tabBarLabel: 'Stack 2',
      tabBarIcon: ({ tintColor }) => <Icon name="user" tintColor={tintColor} />,
    },
  },
  Stack3: {
    screen: Stack3,
    navigationOptions: {
      tabBarLabel: 'Stack 3',
      tabBarIcon: ({ tintColor }) => <Icon name="bat" tintColor={tintColor} />,
    },
  },
};

const AppNavigator = createBottomTabNavigator(RouteConfigs, TabNavConfig);

export default AppNavigator;

// / Stack 1

const Stack1NavConfig = {
  initialRouteName: 'Screen1',
  mode: 'modal',
  defaultNavigationOptions: {
    headerTitleAlign: 'center',
    headerBackTitleVisible: false,
  },
};
const Stack1RouteConfigs = {
  Screen1: {
    screen: Screen1,
    navigationOptions: () => ({
      headerTitle: () => <HeaderLogo />,
      headerStyle: {
        backgroundColor: 'white',
        shadowColor: 'transparent',
        borderBottomColor: 'transparent',
        elevation: 0,
      },
      headerBackTitle: null,
      headerRight: () => (
        <TouchableHeaderIconRight
          badgeNumber={2}
          onPress={() => console.log('NOTIFICATIONS!')}
        />
      ),
    }),
  },
  Modal1: {
    screen: Modal1,
    navigationOptions: ({ navigation }) => ({
      title: 'Modal 1',
      headerLeft: () => <Icon name="arrow-back" />,
    }),
  },
};
const Stack1 = createStackNavigator(Stack1RouteConfigs, Stack1NavConfig);

export default Stack1;

```

Video:

This one doesn't show the header flicker as much

![modalbug](https://user-images.githubusercontent.com/25064365/79361237-a6057f00-7f0a-11ea-8132-d832cd6f6e37.gif)

This one shows the header flicker

![modalbug2](https://user-images.githubusercontent.com/25064365/79361961-98042e00-7f0b-11ea-9bab-50a29bf59e1b.gif)

 
**How to reproduce**

- Tried to create a Snack but kept on getting an error 
`Device: (0:0) Unable to resolve module 'module://react-navigation-tabs.js'
  Evaluating module://react-navigation-tabs.js`

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android: iOS so far      |  iOS 13.2.2, XCode : 11.2.1
| react-navigation               | 4.0.10
|react-navigation-stack    |  2.3.11
| react-navigation-tabs          | 2.8.11
| react-navigation-drawer        | not being used
| react-native-reanimated        | 1.7.1
| react-native-gesture-handler   | 1.6.1
| react-native-safe-area-context | 0.7.3
| react-native-screens           | 2.4.0
| react-native                   | 0.61.2
| expo                           | nope 
| node                           | 13.11.0
| npm or yarn                    | Yarn 1.22.4

**Comment by satya164** [comment]
This guide is for v5, but the same applies for v4. You should avoid using `tabBarVisible` and restructure your navigators instead.

**Comment by theasc** [comment]
@satya164 I also have the same issue.  I removed `tabBarVisible` and restructured as recommended in your [link](https://reactnavigation.org/docs/hiding-tabbar-in-screens), It only happens in Android on my side.
