### ISSUE TITLE
Redux's dispatch action slows or prevents navigation

### ISSUE THREAD

**Issue by 1awaleed** [react-navigation/react-navigation#8047]
**Current Behavior**
I have screen A, which has "logout Button". 
Logout button's onPress fires 2 redux actions then should navigates to the login screen.
After upgrading to react-navigation 5. The redux actions are fired. but the navigation never happens. I need to press again to actually navigate.
I have another component which fires only 1 action before navigation action, It works but the navigation animation stutters.
Any redux action described here just empties a reducer. 
Logging out clears the user data & token.

- What code are you running and what is happening?
Here is my onPress handler function
`const handleLogout = () => {
    props.dispatch(actionA());
    props.dispatch(actionB());
    props.navigation.navigate("Login");
 };`

**Expected Behavior**
Expected behavior to have the redux actions fired then navigate to the login screen.

**How to reproduce**
Fire more than one redux action immediately before the navigation.
I am using 
"react-redux": "^7.1.0",
"redux-persist": "^5.10.0"

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | iOS
| @react-navigation/native       | 5.1.5
| @react-navigation/stack        | 5.2.10
| react-native-gesture-handler   | 1.6.1
| react-native-safe-area-context | 0.7.3
| react-native-screens           | 2.4.0
| react-native                   | 0.62.1
| expo                           |-
| node                           |-
| npm or yarn                    |-

**Comment by cepem** [comment]
This is happening to me too. I fire two redux actions on a button press and then redirect the user to another screen. Sometimes I have to press the button twice for the redirect to take effect. 
We're downgrading back to React Navigation 4.

**Comment by 1awaleed** [comment]
@cepem After careful inspection, I found out that the problem is not related to react navigation and we upgraded successfully to react navigation 5, so I am closing this issue.
