### ISSUE TITLE
Possible bad context of 'route' in options of a stack screen.

### ISSUE THREAD

**Issue by neolitec** [react-navigation/react-navigation#8048]
**Current Behavior**

`options` in Stack.Screen seems to have access to 2 different contexts: the current and the parent navigation, relatively to the screen where this option is used. 

```javascript
function MyStackNavigator() {
  return (
    <MyStack.Navigator>
      <MyStack.Screen
        name="Screen"
        component={MyComponent}
        options={({route, navigation}) => { // 'route' here is in the context of the parent navigation
          return {
            header: (
              props, // props: StackHeaderProps (contains scene.route that is in the context of the screen 'Screen')
            ) => (
              <Text>{route.params.title}</Text>
            ),
          };
        }}
      />
    </MyStack.Navigator>
  );
}
```

I was trying to pass data from the screen to the header through the navigation params like it was done before in my application. And I figured out that I actually set params in the parent navigation! If I'm not mistaken, React-Navigation 4 works differently.

**Expected Behavior**

I wonder if this is a wanted behavior to get a reference to the current navigation only when using `header` and not when using a simple function. It's nice to be able to get both current and parent navigation params but why not expose current navigation directly in `options` params?

How can I dynamically set the title of the header (through the navigation) without redefining a whole custom header with `header`?

**How to reproduce**

You can test with my example just above or if needed I will create a repo to reproduce that :)

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Both (I guess!)
| @react-navigation/native       | 5.1.5
| @react-navigation/stack        | 5.1.1
| react-native-gesture-handler   | 1.6.1
| react-native-safe-area-context | 0.7.3
| react-native-screens           | 2.4.0
| react-native                   | 0.62.2
| expo                           | -
| node                           | 13.12
| npm or yarn                    | npm 6.14.4

**Comment by neolitec** [comment]
I think the issue is in `core`. Can anyone change the label `package:stack` to `package:core`?

**Comment by satya164** [comment]
> How can I dynamically set the title of the header

Use `navigation.setOptions` then `scene.descriptor.options.title` or use params.
