### ISSUE TITLE
_RNGestureHandlerModule.default.Direction is not an object

### ISSUE THREAD

**Issue by kravtsovnet** [react-navigation/react-navigation#8050]
**Current Behavior**

- Minimalist code implementing react navigation - recommended solutions do not work
Attempted to resolve by:
1. Removing and adding react-native-gesture-handler.
2. pod install + restart.
3. Unlinking and reinstalling react-native-gesture-handler.
4. Clearing cache npx react-native start --reset-cache.

**Expected Behavior**
- No error

**How to reproduce**

- Create AwesomeProject per instructions and install all dependencies
- npm start
- error TypeError: null is not an object (evaluating '_RNGestureHandlerModule.default.Direction')
code: 
import 'react-native-gesture-handler';
import * as React from 'react';
import { NavigationContainer } from '@react-navigation/native';

export default function App() {
  return (
    <NavigationContainer>{/* Rest of your app code */}</NavigationContainer>
  );
}

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |
| @react-navigation/native       | latest stable
| react-native                   | latest stable
| expo                           | latest stable
| node                           | latest stable
| npm or yarn                    | latest stable

**Comment by satya164** [comment]
https://reactnavigation.org/docs/troubleshooting
