### ISSUE TITLE
Drawer not opening-closing properly

### ISSUE THREAD

**Issue by aesthytik** [react-navigation/react-navigation#8051]
**Current behaviour: >>>**

Drawer is behaving weirdly

It opens twice and closes. 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/26917061/79452451-cf570580-8005-11ea-81c6-5ebd093adbb7.gif)
. 

**Epected behavior**

Should open normally

**System environment**

System:
    OS: macOS High Sierra 10.13.6
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
    Memory: 522.49 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.2 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    Android SDK:
      API Levels: 23, 25, 26, 27, 28
      Build Tools: 27.0.3, 28.0.2, 28.0.3
      System Images: android-26 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 10.1/10B61 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7

Below is my code for route:-

import React, { useEffect } from 'react';
import { View, Text, Platform, Alert } from 'react-native';
import { NavigationContainer } from '@react-navigation/native';
import { createStackNavigator } from '@react-navigation/stack';
import { createDrawerNavigator } from '@react-navigation/drawer';
import { applyMiddleware, createStore } from 'redux';
import { useDispatch, Provider } from 'react-redux';
import Geolocation from '@react-native-community/geolocation';
import thunkMiddleware from 'redux-thunk';
import promise from 'redux-promise';

import { ThemeProvider } from 'styled-components';
import FlashMessage from 'react-native-flash-message';
import AsyncStorage from '@react-native-community/async-storage';

import {
  Login,
  Signup,
  ForgotPassword,
  Home,
  Payment,
  Welcome,
  NoZone,
  Settings,
} from './src/containers';
import AuthLoading from './src/components/AuthLoading';

import reducers from './src/store/reducers';
import theme from './src/utils/theme';
import CustomDrawerContent from './src/components/CustomDrawerContent';
import { geoCode } from './src/utils/helpers';

import { getOrigin } from './src/store/actions/globalActions';

function Main() {
  const dispatch = useDispatch();

  useEffect(() => {
    getLocationAccess();
  }, []);

 

  return (
    <Stack.Navigator headerMode="none" initialRouteName="AuthLoading">
      <Stack.Screen name="AuthLoading" component={AuthLoading} />
      <Stack.Screen name="Login" component={Login} />
      <Stack.Screen name="ForgotPassword" component={ForgotPassword} />
      <Stack.Screen name="NoZone" component={NoZone} />
      <Stack.Screen name="Signup" component={Signup} />
      <Stack.Screen name="Welcome" component={Welcome} />
      <Stack.Screen name="Home" component={Home} />
      <Stack.Screen name="Settings" component={Settings} />

      <Stack.Screen name="PaymentMethod" component={Payment} />

      {/* <Stack.Screen name="WelcomePage" component={WelcomePage} /> */}
    </Stack.Navigator>
  );
}

const Stack = createStackNavigator();

const Drawer = createDrawerNavigator();

const createStoreWithMiddleware = applyMiddleware(
  promise,
  thunkMiddleware,
)(createStore);

function App() {
  console.disableYellowBox = true;

  return (
    <Provider store={createStoreWithMiddleware(reducers)}>
      <ThemeProvider theme={theme}>
        <NavigationContainer>
          <Drawer.Navigator
            initialRouteName="Main"
            drawerStyle={{
              backgroundColor: '#3B414B',
            }}
            drawerContent={props => <CustomDrawerContent {...props} />}>
            <Drawer.Screen name="Past Rides" component={Home} />
            <Drawer.Screen name="Payment" component={Payment} />
            <Drawer.Screen name="How it Works" component={Main} />
            <Drawer.Screen name="Main" component={Main} />
          </Drawer.Navigator>
          <FlashMessage position="top" />
        </NavigationContainer>
      </ThemeProvider>
    </Provider>
  );
}

export default App;

**Comment by aesthytik** [comment]
@satya164 i updated the info. please help

**Comment by aesthytik** [comment]
@raajnadar please help here

**Comment by aesthytik** [comment]
@satya164 any help?

**Comment by raajnadar** [comment]
Create a snack or a repo to check the issue.
