### ISSUE TITLE
BottomTabNavigationProp type is resolving to "any"

### ISSUE THREAD

**Issue by jhbertra** [react-navigation/react-navigation#8054]
**Current Behavior**

- What code are you running and what is happening?

Typing a bottom tab navigation prop with `BottomTabNavigationProp`, the type is being calculated as `any`.
The same does not happen with the plain `NavigationProp` type.

- Include a screenshot or video if it makes sense.

![Screen Shot 2020-04-16 at 3 04 07 PM](https://user-images.githubusercontent.com/1339296/79496111-aa599700-7ff3-11ea-8764-c1ab2f116a94.png)

Does not happen with plain `NavigationProp`
![Screen Shot 2020-04-16 at 3 04 44 PM](https://user-images.githubusercontent.com/1339296/79496172-be9d9400-7ff3-11ea-8d20-7207765d13a6.png)

**Expected Behavior**

- What do you expect should be happening?
  The type of the navigation prop should be calculated as
  ```ts
   NavigationProp<ParamList, RouteName, TabNavigationState, BottomTabNavigationOptions, BottomTabNavigationEventMap> & TabActionHelpers<ParamList>;
   ```

- Include a screenshot or video if it makes sense.

**How to reproduce**

- You must provide a way to reproduce the problem. If you are having an issue with your machine or build tools, the issue belongs on another repository as that is outside of the scope of React Navigation.

  This issue reproduces with the following example code:

  ```ts
  type Example = {
    RouteA: undefined,
    RouteB: undefined,
  };
  
  // type is calculated as any
  declare const example: BottomTabNavigationProp<Example, "RouteA">;
  ```

- Either re-create the bug on [Snack](https://snack.expo.io) or link to a GitHub repository with code that reproduces the bug.

  Bug does not appear at runtime - cannot demonstrate on Snack

- Explain how to run the example app and any steps that we need to take to reproduce the issue from the example app.
- Keep the repro code as simple as possible, with the minimum amount of code required to repro the issue.
- Before reporting an issue, make sure you are on latest version of the package.

**Your Environment**

| software                      | version |
| ----------------------------- | ------- |
| iOS or Android                | N/A
| @react-navigation/native      | 5.1.5
| @react-navigation/bottom-tabs | 5.2.6
| react-native-screens          | N/A
| react-native                  | 0.61.5
| expo                          | N/A
| node                          | 10.16.3
| npm or yarn                   | 1.22.0

**Comment by satya164** [comment]
Closing since you didn't provide a repro.
