### ISSUE TITLE
Navigation between nested navigators doesn't work

### ISSUE THREAD

**Issue by vlad1chek** [react-navigation/react-navigation#8056]
Hi! 

Currently, I have auth navigator and bottom tab bar navigator. And I can't navigate from the screen from the auth navigator to the bottom tab bar navigator.

**Current behavior**
When I tried to implement the auth flow, but I can't navigate from the login screen to the bottom tab bar. 

**Expected Behavior**
Should navigate from auth navigator to the bottom tab bar navigator

Here is my switch navigator:
```
export default function AppSwitchNavigator() {
    return(
        <MainStack.Navigator>
            {isLoggedIn ? (
                <MainStack.Screen name={'MainApp'} component={AppTabNavigator} />
            ) : (
                <MainStack.Screen name={'Auth'} component={AuthNavigator} />
            )}
        </MainStack.Navigator>
    );
}
```
Bottom tab bar navigator:
```
export default function AppTabNavigator() {
    return(
        <Tab.Navigator lazy={false}>
            <Tab.Screen name={'HomeTab'} component={HomeScreen}/>
            <Tab.Screen name={'CartTab'} component={CartScreen}/>
            <Tab.Screen name={'QRCodeTab'} component={QRCodeScreen}/>
            <Tab.Screen name={ChatTab'} component={ChatScreen}/>
            <Tab.Screen name={'ProfileTab'} component={ProfileScreen}/>
        </Tab.Navigator>
    );
}
```
Auth navigator: 
```
export default function AuthNavigator() {
    return(
        <AuthStack.Navigator headerMode='none'>
            <AuthStack.Screen name={'InitialScreen'} component={InitialScreen} />
            <AuthStack.Screen name={'LoginByPhone'} component={LoginByPhoneScreen} />
            <AuthStack.Screen name={'LoginVerification'} component={LoginVerificationScreen} />
            <AuthStack.Screen name={'LoginByEmail'} component={LoginByEmailScreen} />
            <AuthStack.Screen name={'RegistrationByPhone'} component={RegisterByPhoneScreen} />
            <AuthStack.Screen name={'RegistrationVerification'} component={RegisterVerificationScreen} />
            <AuthStack.Screen name={'RegistrationByEmail'} component={RegisterByEmailScreen} />
        </AuthStack.Navigator>
    );
}
```
And when I try navigate from Auth navigator  to the bottom tab bar navigator via `navigation.navigate('MainApp')` I get the error that I sent above. 
Also I tried `navigation.navigate('MainApp', {screen: 'HomeTab'})` but I have the same error.
I thought that `<Tab.Navigator lazy={false}>` should help me, but unfortunately no

Error
![image](https://user-images.githubusercontent.com/38522988/79519754-69966800-805d-11ea-9221-e2028797f84f.png)

**Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |IOS 12.4
| @react-navigation/native       | 5.1.5
| @react-navigation/stack        | 5.2.10
| react-native-gesture-handler   | 1.6.1
| react-native-safe-area-context | 0.7.3
| react-native-screens           | 2.5.0
| react-native                   | 0.62.2
| npm or yarn                    | yarn

**Comment by vlad1chek** [comment]
**Current behavior**
When I tried to implement the auth flow, but I can't navigate from the login screen to the bottom tab bar. 

**Expected Behavior**
I can navigate from auth navigator to the bottom tab bar navigator

Currently, I have auth navigator and bottom tab bar navigator. And I can't navigate from the screen from the auth navigator to the bottom tab bar navigator.

Here is my switch navigator:
```
export default function AppSwitchNavigator() {
    return(
        <MainStack.Navigator>
            {isLoggedIn ? (
                <MainStack.Screen name={'MainApp'} component={AppTabNavigator} />
            ) : (
                <MainStack.Screen name={'Auth'} component={AuthNavigator} />
            )}
        </MainStack.Navigator>
    );
}
```
Bottom tab bar navigator:
```
export default function AppTabNavigator() {
    return(
        <Tab.Navigator lazy={false}>
            <Tab.Screen name={'HomeTab'} component={HomeScreen}/>
            <Tab.Screen name={'CartTab'} component={CartScreen}/>
            <Tab.Screen name={'QRCodeTab'} component={QRCodeScreen}/>
            <Tab.Screen name={ChatTab'} component={ChatScreen}/>
            <Tab.Screen name={'ProfileTab'} component={ProfileScreen}/>
        </Tab.Navigator>
    );
}
```
Auth navigator: 
```
export default function AuthNavigator() {
    return(
        <AuthStack.Navigator headerMode='none'>
            <AuthStack.Screen name={'InitialScreen'} component={InitialScreen} />
            <AuthStack.Screen name={'LoginByPhone'} component={LoginByPhoneScreen} />
            <AuthStack.Screen name={'LoginVerification'} component={LoginVerificationScreen} />
            <AuthStack.Screen name={'LoginByEmail'} component={LoginByEmailScreen} />
            <AuthStack.Screen name={'RegistrationByPhone'} component={RegisterByPhoneScreen} />
            <AuthStack.Screen name={'RegistrationVerification'} component={RegisterVerificationScreen} />
            <AuthStack.Screen name={'RegistrationByEmail'} component={RegisterByEmailScreen} />
        </AuthStack.Navigator>
    );
}
```
And when I try navigate from Auth navigator  to the bottom tab bar navigator via `navigation.navigate('MainApp')` I get the error that I sent above. 
Also I tried `navigation.navigate('MainApp', {screen: 'HomeTab'})` but I have the same error.
I thought that `<Tab.Navigator lazy={false}>` should help me, but unfortunately no

**Comment by vlad1chek** [comment]
@raajnadar I updated comment and provide a code sample. Please help.

**Comment by Trancever** [comment]
You should update `isLoggedIn ` state that will cause `MainApp` screen to render instead of calling `navigate` manually.
