### ISSUE TITLE
Back navigation on android makes dismiss the keyboard

### ISSUE THREAD

**Issue by hamzaouhssain1993** [react-navigation/react-navigation#8058]
**Current Behavior**
When I have two screen in the navigation and i go back to the first one and I click right away on the text input, the keyboard opens and dismiss right away. This does not happen if you go back and wait for the screen to load properly.
So to reproduce you need to click on the text input quick.

- What code are you running and what is happening?
    "@react-navigation/bottom-tabs": "^5.2.6",
    "@react-navigation/material-top-tabs": "^5.1.8",
    "@react-navigation/native": "^5.1.5",
    "@react-navigation/stack": "^5.2.10",

    "react-native": "0.61.5",

**Expected Behavior**
if you click on the text input, the keyboard should stay open and not dismiss

**How to reproduce**

Have a text input in the first screen.
Move to the next screen
Go back to the previous screen where there was the text input.
click right away on the text input and the keyboard will open and dismiss.
(to reproduce it, you have to be quick enough and click on the text input, if not the page will be loaded completely and you won't get the problem)

**Your Environment**
| ------------------------------ | ------- |
| Android      9           |
Huawei P20
|     
"@react-navigation/bottom-tabs": "^5.2.6",
    "@react-navigation/material-top-tabs": "^5.1.8",
    "@react-navigation/native": "^5.1.5",
    "@react-navigation/stack": "^5.2.10",       
|
| react-native   0.61.5                |

Possible solution:
I have tried the solution provided in this pr #7931 and it seels fixing it, tried also in ios device to be sure and it worked

Sorry if i am missing something, this is my first error post in my life

**Comment by Max706** [comment]
same issue

**Comment by satya164** [comment]
Closing since you didn't provide any repro. We need a minimal repro to be able to debug issues. Feel free to open a new issue if you have a repro.
