### ISSUE TITLE
How can i create submenus in Drawer (with icons before the text) in v5?

### ISSUE THREAD

**Issue by anisharya16** [react-navigation/react-navigation#8059]
**Expected Behavior**

How can i create Submenus in Drawer and also each menu should have an icon before the text in v5 of react navigation?

[https://cdn-media-1.freecodecamp.org/images/1*YYYyBYo_SjxfgVnIsZyKUQ.gif](url)
| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |Android|
| @react-navigation/native       |^5.1.5|
| @react-navigation/drawer       |^5.4.1|
| react-native-reanimated        |^1.8.0|
| react-native-gesture-handler   |^1.6.1|
| react-native-safe-area-context |^0.7.3|
| react-native-screens           |^2.4.0|
| react-native                   |0.62.2|
| npm or yarn                    |npm|

**Comment by khacvu0505** [comment]
:(((
