### ISSUE TITLE
@react-navigation/routers/src/index.tsx: Unexpected token (9:12)

### ISSUE THREAD

**Issue by Yab-kami** [react-navigation/react-navigation#8060]
[<a href="https://ibb.co/3kXKy0k"><img src="https://i.ibb.co/3kXKy0k/Simulator-Screen-Shot-i-Phone-11-2020-04-17-at-16-50-00.png" alt="Simulator-Screen-Shot-i-Phone-11-2020-04-17-at-16-50-00" border="0"></a>](url)
| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |
| @react-navigation/native       |5
| react-native                   |
| expo                           | 
| node                           |
| npm or yarn                    |

**Comment by Neck1T** [comment]
https://github.com/react-navigation/react-navigation/issues/7981#issuecomment-611377210

this should help (it works for me)

**Comment by sultan-ul-arefin** [comment]
how to ignore that error ?
