### ISSUE TITLE
Reset Not working nor removed screen from stack

### ISSUE THREAD

**Issue by anwersolangi** [react-navigation/react-navigation#8061]
Greetings To All..!!!
I am building an app where i want an screen to work as a modal. What i am doing is just holding a screen for some seconds and then navigating back to the Parent Screen. But what i encounter is the screen still working in the background stack. and is not removed and also when i use the reset. i got error the action 'RESET' with payload {"routes":[{}]} was not handled by any navigator. I found some stackoverflow answers but that didn't work.  Like [this](https://stackoverflow.com/questions/60466399/react-navigation-v5-wont-reset-and-remove-previous-routes) article

**Hierarchy Of My Screen**
I have three Tab Bar nested inside Drawer Stack and a Stack with mode="modal"

I am using React Navigation v5. 
**I have attached screenshot of error where, you can also see that the screen logs are still updating in the background**
![Error](https://user-images.githubusercontent.com/37410529/79585085-bbd09b00-80e8-11ea-935a-12123d47b95e.png)

**Comment by raajnadar** [comment]
Try using `navigation.goBack()` in you child screen.

**Comment by anwersolangi** [comment]
> Try using `navigation.goBack()` in you child screen.

Already tried this solution but still getting the screen state in console. when i console.log the state of the child screen,

**Comment by anwersolangi** [comment]
> Hey! Thanks for opening the issue. Can you provide a [minimal repro](https://stackoverflow.com/help/minimal-reproducible-example) which demonstrates the issue? Posting a snippet of your code in the issue is useful, but it's not usually straightforward to run. A repro will help us debug the issue faster. Please try to keep the repro as small as possible. The easiest way to provide a repro is on [snack.expo.io](https://snack.expo.io). If it's not possible to repro it on [snack.expo.io](https://snack.expo.io), then you can also provide the repro in a GitHub repository.

https://snack.expo.io/@anwersolangi/e5630b

I rewrite the problem above, however i am getting the error when the snack is installing @react-navigation library. please checkout the codes, i have write minimal code as i can. Thanks

**Comment by anwersolangi** [comment]
Somehow i manage that error and used the goBack() function and it works fine, it stop that child stack screen. and when i again open that stack i didn't get the states update.
