### ISSUE TITLE
Publish pre-styled Header-family components without additional prop requirements

### ISSUE THREAD

**Issue by finom** [react-navigation/react-navigation#8062]
**Current Behavior**

- What code are you running and what is happening?

I'm trying to customise `options.header` but all styles are gone because the entire component is overridden. My goal is not to replace the header but add some extra features. More precise, I'm trying to reproduce behaviour of Viber search (no problem if you don't know what is that). There is a search icon at the header which can be added with https://github.com/vonovak/react-navigation-header-buttons, but if I want to add the search function (see screenshots below) I'd either need to
- Completely customise the component which may cause unpredictable difference to other non-custom headers 
- Put the input into headerTitle which is tricky because its parent is a Text component but also I'd need to create a context to also update state of the custom headerLeft (for back button) and headerRight (for clear input button)
- Put the entire functionality into headerTitle, loose the definite position of headerLeft and headerRight icons and set them manually by reverse-engineering.

All 3 cases are too complicated to implement and to make them as smooth as the library itself.

Here is what I'm trying to re-produce:

![image](https://user-images.githubusercontent.com/1082083/79584190-bd916300-80d6-11ea-8b9b-6015b65e67e2.png)

By clicking 🔍 icon the header needs to render an input, where back button isn't about routing but it sets the header to be in its default state, ✖️icon needs to render at the same place as custom icons defined with the help of react-navigation-header-buttons.

![image](https://user-images.githubusercontent.com/1082083/79584231-cb46e880-80d6-11ea-987c-67d24b762250.png)

I've noticed that the library exports some components like Header and HeaderTitle, so here what I've got trying to re-use them.

```js
<Stack.Screen
          name="Home"
          component={HomeScreen}
          options={{
            header: () => <Header><HeaderTitle>Hello world</HeaderTitle></Header>,
...
```

![image](https://user-images.githubusercontent.com/1082083/79586933-7a38f380-80da-11ea-8e06-b371fdb763e6.png)

I guess they're exported for debugging and experimental (?) purposes but not for that kind of use.

**Expected Behavior**

- What do you expect should be happening?

I'd like to have a possibility to re-use `<Header>` component as well as `<HeaderLeft>`, `<HeaderRight>` and `<HeaderTitle>` to completely customise header behaviour. As far as I understand that's not so complicated but requires some effort because component structure is a bit trickier than I expected.

That's what I'd ideally got to have:
```
<Header>
  <HeaderLeft>Left</HeaderLeft>
  <HeaderTitle>Title</HeaderTitle>
  <HeaderRight>Right</HeaderRight>
</Header>
```

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | No matter
| @react-navigation/native       | https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz
| @react-navigation/stack        | 5.2.10

**Comment by satya164** [comment]
You need to pass the props

```js
header: props => <Header {...props} />
```

https://reactnavigation.org/docs/stack-navigator#header

**Comment by finom** [comment]
@satya164 thank you, but that not exactly I meant. I would like to use the Header component and its styling (+ its children of course) at any place I want (not only as `header` option). Can you reopen that please?

**Comment by satya164** [comment]
Then you need to use a custom header or a component library. React Navigation isn't a component library for generic components.

**Comment by finom** [comment]
It isn't, but it does include pre-styled components which may be helpful when somebody builds a react-navigation-like header at screens where react navigation isn't able to cover developer needs.
