### ISSUE TITLE
Navigate back on android 7 and older

### ISSUE THREAD

**Issue by esi32** [react-navigation/react-navigation#8065]
This is just an issue with android 7 and older but in newer versions everything is working correctly,
consider i'm navigating like below 
A  -> B -> C
now i'm in C screen when i press the back button it shows the A and all actions are locked till when i press back again and it work  , so B is never shown in between , and there is an weird thing that when for first pushing back I'm in A it seem on pressing it something touched in B while A is shown :(
help

**Comment by satya164** [comment]
Closing since you didn't follow the issue template.
