### ISSUE TITLE
Navigation 5 - Swipe back overflowing the screen

### ISSUE THREAD

**Issue by durdevic** [react-navigation/react-navigation#8069]
**Current Behavior**
When swiping back (right) and then swiping left (like to put it back in place), there is no border for the screen to stop to. The same effect doesn't happen on v4

Video:
![n5 (1)](https://user-images.githubusercontent.com/2753836/79645090-70cc8b80-81ad-11ea-9de6-7892b060bfb9.gif)

Expo:
https://snack.expo.io/@ukiand1/navigation-5---swipe-back,-touch-bug

**Expected Behavior**
To have border stop when swiping left.

Video:
![n4](https://user-images.githubusercontent.com/2753836/79645034-04518c80-81ad-11ea-8a65-507505b858ed.gif)

Expo: 
https://snack.expo.io/@ukiand1/navigation-4---swipe-back,-no-touch-bug

**How to reproduce**
Projects like in expo

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | iOS and Android
| @react-navigation/native       |^5.1.4
| @react-navigation/stack        |latest
| react-native-gesture-handler   |
| react-native-safe-area-context |^0.6.0
| react-native-screens           |^2.0.0
| react-native                   |
| expo                           |v37.0.0
| node                           |
| npm or yarn                    |

**Comment by satya164** [comment]
If you don't want the card to animate more than the screen width, you need to configure it in your animation with `extrapolate: 'clamp'.

https://github.com/react-navigation/react-navigation/blob/master/packages/stack/src/TransitionConfigs/CardStyleInterpolators.tsx

**Comment by durdevic** [comment]
Thanks! Pretty nifty solution!
