### ISSUE TITLE
How can I type my stack screen component to use toggleDrawer?

### ISSUE THREAD

**Issue by kuhelbeher** [react-navigation/react-navigation#8070]
Hi, I'm using StackNavigator inside DrawerNavigator with Typescript:

```javascript
const FiltersNavigator = createStackNavigator({
  Filters: FiltersScreen,
});

const MainNavigator = createDrawerNavigator({
  Filters: FiltersNavigator,
});

export default createAppContainer(MainNavigator);
```

And I want to add button in the header and toggle drawer when user taps on it:

```javascript
const FiltersScreen: NavigationStackScreenComponent = ({ navigation }) => {
  return (
    <View>
      <Text>The FiltersScreen</Text>
    </View>
  );
};

FiltersScreen.navigationOptions = ({ navigation }) => {
  return {
    headerTitle: 'Filter Meals',
    headerLeft() {
      return (
        <HeaderButtons HeaderButtonComponent={HeaderButtonComponent}>
          <Item
            title="Menu"
            iconName="ios-menu"
            onPress={() => {
              navigation.toggleDrawer();
            }}
          />
        </HeaderButtons>
      );
    },
  };
};
```

But TS shows error when I'm trying to run navigation.toggleDrawer():

> Property 'toggleDrawer' does not exist on type StackNavigationProp<NavigationRoute<NavigationParams>, NavigationParams>'

How can I use types to make it work?

**Comment by kuhelbeher** [comment]
Repo with repro: https://github.com/kuhelbeher/drawer-stack-navigation

**Comment by raajnadar** [comment]
I tested the code in the repo and found no issues. Maybe you can try upgrading to latest version where ts support is much better than old version.

**Comment by kuhelbeher** [comment]
@raajnadar this error appears only in VSCode but console is clear
![image](https://user-images.githubusercontent.com/37115006/79685585-83dd6b00-8242-11ea-8330-75bb0eef4296.png)
What IDE do you use, maybe it is problem with VSCode?

**Comment by raajnadar** [comment]
Try running `yarn --dev @types/react-navigation`

**Comment by xgenem** [comment]
I am surprised that there's no solution to this. Even the documentations didn't include this :(
