### ISSUE TITLE
how to set header for Tab navigators in v5.x?

### ISSUE THREAD

**Issue by kulikalov** [react-navigation/react-navigation#8071]
Hi!
In the `react-navigation@4.x` we were using nested StackNavigator to set headers for TabNavigators. Is this different now? I can't find any changes regarding that neither in migration notes nor in docs.
Thanks, awesome library :)

**Comment by Liqiankun** [comment]
```js
<Stack.Screen name="PageName" component={Page} options={{ headerShown: false }} />
```

**Comment by kulikalov** [comment]
For now, I'm using this:

```
<Stack.Screen
  component={HomeTabs}
  name='Home tabs'
  options={navigator => {
    const { index, routeNames } = navigator.route?.state || {}
    if (!routeNames?.length) {
      return {
        headerTitle: 'First Tab'
      }
    }
    return {
      headerTitle: routeNames[index]
    }
  }}
/>
```
Pls, correct me, if there is a more elegant solution.

**Comment by firevitality** [comment]
https://reactnavigation.org/docs/4.x/navigation-options-resolution/#a-stack-contains-a-tab-navigator-and-you-want-to-set-the-title-on-the-stack-header

**Comment by satya164** [comment]
There's no difference
