### ISSUE TITLE
Android: StackCardMode not working for 'card' only shows 'modal' (V5)

### ISSUE THREAD

**Issue by FrederickEngelhardt** [react-navigation/react-navigation#8072]
**Current Behavior**

- Currently android only allowing the modal mode for stack navigator
- iOS retains the ability to use both 'card' and 'modal'

Example app stack I have setup
```
const AppStackNav = () => (
  <AppStack.Navigator mode='card' headerMode='none' initialRouteName='drawer'>
    <AppStack.Screen name='drawer' component={DrawerNav} />
    <AppStack.Screen name='topic' component={TopicNavigator} />
    <AppStack.Screen name='tutorial' component={AppTutorial} />
  </AppStack.Navigator>
)
```

**Expected Behavior**

- `mode` should allow android to use 'card' mode
- `mode` should automatically be set to 'card' for android

**How to reproduce**
Option 1:
```bash
git clone https://github.com/FrederickEngelhardt/androidStackNavigationIssueV5.git &&
cd ./androidStackNavigationIssueV5 &&
yarn &&
npx react-native run-android
```

Option 2: Manual way
- go with a barebones react-native app
- `npx react-native init testApp`
- cd `./testApp`
- `yarn add @react-navigation/native @react-navigation/stack react-native-reanimated react-native-gesture-handler react-native-screens react-native-safe-area-context @react-native-community/masked-view 
- Replace App.js with this code and boot android emulator or on device and notice that only modal is applied. Notice that iOS does not have this issue.

```javascript
import React from 'react';
import { View, Button } from 'react-native';
import { NavigationContainer } from '@react-navigation/native';
import { createStackNavigator } from '@react-navigation/stack';

const AppStack = createStackNavigator();

const Screen = modifier => ({ navigation: { navigate } }) => (
  <View style={{ flex: 1, backgroundColor: 'orange' }}>
    <Button
      title={`Go to Screen ${modifier}`}
      onPress={() => navigate(`Screen ${modifier}`)}
    />
  </View>
);

const Navigation = () => (
  <NavigationContainer>
    <AppStack.Navigator mode="card">
      <AppStack.Screen name="Screen A" component={Screen('B')} />
      <AppStack.Screen name="Screen B" component={Screen('A')} />
    </AppStack.Navigator>
  </NavigationContainer>
);

export default Navigation;
```

**Your Environment**
| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |Android
| @react-navigation/native       |5.1.6
| @react-navigation/stack        |5.5.0
| react-native-gesture-handler   |1.6.1
| react-native-safe-area-context |0.7.3
| react-native-screens           |2.5.0
| react-native                   |0.62.1
| node                           |12.16.1
| yarn                    |1.22.0

**Comment by satya164** [comment]
Vertical transition doesn't mean it's a modal https://reactnavigation.org/docs/stack-navigator#mode

Stack uses default platform animations. If you want to change the animation, you can change it following the docs https://reactnavigation.org/docs/stack-navigator#pre-made-configs

**Comment by zalash333** [comment]
I have the same problem

**Comment by KingAmo** [comment]
in my case, the animation is default to 'modal'  on android,  which means new page slide up ,  while on iOS it's default animation is horizontal ,  and config the animation via https://reactnavigation.org/docs/stack-navigator#pre-made-configs does not work on android

**Comment by mowshe** [comment]
Still having this issue. The docs say that "Card" is the default on both IOS and Android, which is true for IOS but not Android. Setting mode="card" doesn't help either.
