### ISSUE TITLE
The action 'SET_PARAMS' with the payload ... was not handled by any navigator

### ISSUE THREAD

**Issue by Angusalex** [react-navigation/react-navigation#8073]
**Current Behavior**

- What code are you running and what is happening?
//App.js
`import * as React from "react"
import { View, Text, ActivityIndicator, StyleSheet } from 'react-native'
import { NavigationContainer } from '@react-navigation/native'
import { createStackNavigator } from '@react-navigation/stack'
import { createDrawerNavigator } from '@react-navigation/drawer'
import EtiquettesPictureContext from './Components/Contexts/EtiquettesPictureContext'

import RootStack from './Navigation/Navigation'
import Home from './Components/Layouts/Home'
import Etiquettes from './Components/Layouts/Etiquettes'
import TemperaturesFridges from './Components/Layouts/TemperaturesFridges'
import BonsLivraisons from './Components/Layouts/BonsLivraisons'
import EtiquettesTakePicture from "./Components/EtiquettesTakePicture"
import BonsLivraisonsTakePicture from "./Components/BonsLivraisonsTakePicture"
import DlcAlertTakePicture from "./Components/DlcAlertTakePicture"
import Notifications from "./Components/Layouts/Notifications"
import Settings from "./Components/Layouts/Settings"
import Welcome from "./Components/Layouts/Welcome"
import Login from "./Components/Layouts/Login"
import Signup from "./Components/Layouts/Signup"
import Logout from "./Components/Layouts/Logout"
import InitLogin from "./Components/Layouts/InitLogin"
import MesEtiquettes from "./Components/Layouts/MesEtiquettes"
import MyEtiquette from "./Components/Layouts/MyEtiquette"
import MesBl from "./Components/Layouts/MesBl"
import MyBl from "./Components/Layouts/MyBl"
import MesReleves from "./Components/Layouts/MesReleves"
import DownloadableDocuments from "./Components/Layouts/DownloadableDocuments"
import Equipe from "./Components/Layouts/Equipe"
import RenewMembership from "./Components/Layouts/RenewMembership"
import DlcAlertNotifications from "./Components/Layouts/DlcAlertNotifications"
import WhatRole from "./Components/WhatRole"

const AuthContext = React.createContext()

const Stack = createStackNavigator()
const Drawer = createDrawerNavigator()

export default function App({ navigation }) {
  const [etiquettesPictureData, blPictureData, setEtiquettesPictureData, setBlPictureData] = React.useState("")

  updateInitialData = (data) => {
    setEtiquettesPictureData(data)
  }

  updateBlData = (data) => {
    blPictureData(data)
  }

  const [state, dispatch] = React.useReducer(
    (prevState, action) => {
      switch (action.type) {
        case 'RESTORE_TOKEN':
          return {
            ...prevState,
            userToken: action.isLogged,
            isLoading: false,
          };
        case 'SIGN_IN':
          return {
            ...prevState,
            isSignout: false,
            userToken: action.isLogged,
          };
        case 'SIGN_OUT':
          return {
            ...prevState,
            isSignout: true,
            userToken: null,
          };
      }
    },
    {
      isLoading: true,
      isSignout: false,
      userToken: null,
    }
  );

  React.useEffect(() => {
    // Fetch the token from storage then navigate to our appropriate place
    const bootstrapAsync = async () => {
      let isLogged;

      try {
        isLogged = await InitLogin.initLogin()
      } catch (e) {
        // Restoring token failed
      }

      // After restoring token, we may need to validate it in production apps

      // This will switch to the App screen or Auth screen and this loading
      // screen will be unmounted and thrown away.
      dispatch({ type: 'RESTORE_TOKEN', isLogged: isLogged.logged });
    };

    bootstrapAsync();
  }, []);

  const authContext = React.useMemo(
    () => ({
      signIn: async data => {
        // In a production app, we need to send some data (usually username, password) to server and get a token
        // We will also need to handle errors if sign in failed
        // After getting token, we need to persist the token using `AsyncStorage`
        // In the example, we'll use a dummy token

        dispatch({ type: 'SIGN_IN', isLogged: 'dummy-auth-token' });
      },
      signOut: () => dispatch({ type: 'SIGN_OUT' }),
      signUp: async data => {
        // In a production app, we need to send user data to server and get a token
        // We will also need to handle errors if sign up failed
        // After getting token, we need to persist the token using `AsyncStorage`
        // In the example, we'll use a dummy token

        dispatch({ type: 'SIGN_IN', isLogged: 'dummy-auth-token' });
      },
    }),
    []
  )

  if (state.isLoading) {
    // We haven't finished checking for the token yet
    return (
      <View style={[styles.container, styles.horizontal]}>
        <ActivityIndicator size="large" color="#0000ff" />
      </View>
    )
  }

  function RootStackScreen() {
    return (
      <Stack.Navigator>
        {state.userToken == false ? (
          <>
            <Stack.Screen name="Welcome" component={Welcome} />
            <Stack.Screen name="Login" component={Login} />
            <Stack.Screen name="Signup" component={Signup} />
          </>

        ) : (
            <>
              <Stack.Screen name="Home" component={Home} options={({ route }) => ({ title: route.params ? route.params.company : "" })} />
              <Stack.Screen name="Etiquettes" component={Etiquettes} />
              <Stack.Screen name="TemperaturesFridges" component={TemperaturesFridges} />
            </>
          )}
      </Stack.Navigator>
    )
  }

  function DrawerScreen() {
    return (
      <Drawer.Navigator>

        <Drawer.Screen name="TemperaturesFridges" component={TemperaturesFridges} />
      </Drawer.Navigator>
    )
  }

  return (
    <EtiquettesPictureContext.Provider
      value={{
        etiquette: etiquettesPictureData,
        Bl: blPictureData,
        updateInitialData: updateInitialData,
        updateBlData: updateBlData
      }}>
      <AuthContext.Provider value={authContext}>
        <NavigationContainer>
          <Drawer.Navigator>
            <Drawer.Screen name="Home" component={RootStackScreen} />
          </Drawer.Navigator>
        </NavigationContainer>
      </AuthContext.Provider>
    </EtiquettesPictureContext.Provider>
  )
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center'
  },
  horizontal: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    padding: 10
  }
})
`
//Home.js
`import * as React from 'react';
import mainStyleSheet from "../../Themes/main.js"
import { MaterialHeaderButtons, Item } from '../HeaderButtons';
import Ionicons from 'react-native-vector-icons/FontAwesome5';
import Company from '../Entities/Company';
import Notification from '../Entities/Notification'

import {
  SafeAreaView,
  ScrollView,
  View,
  Text,
  TouchableHighlight
} from 'react-native';

export default function Home({ navigation }) {

  React.useEffect(() => {
    Company.getCompany().then(company => {
      navigation.setParams({ company })
    })
    this.didBlurSubscription = navigation.addListener(
      'didFocus',
      () => {
        Notification.countNotifications()
          .then(resp => {
            navigation.setParams({ notificationsCount: resp.length })
          })
      }
    )

    // returned function will be called on component unmount 
    return () => {
      this.didBlurSubscription()
    }
  }, [])

  const { navigate } = navigation;
  return (
    <SafeAreaView>
      <ScrollView>
        <View style={mainStyleSheet.mainContainer}>
          <TouchableHighlight style={[mainStyleSheet.buttonHomeContainer, { marginTop: 0 }]} onPress={() => navigate('Etiquettes')} >
            <View style={mainStyleSheet.buttonHome}>
              <Ionicons name="tag" style={{ marginLeft: 20 }} color="white" size={30} />
              <Text style={mainStyleSheet.buttonText}>Etiquettes produits</Text>
            </View>
          </TouchableHighlight>
          <TouchableHighlight style={mainStyleSheet.buttonHomeContainer} onPress={() => navigate('TemperaturesFridges')}>
            <View style={mainStyleSheet.buttonHome}>
              <Ionicons name="thermometer-quarter" style={{ marginLeft: 20 }} color="white" size={30} />
              <Text style={mainStyleSheet.buttonText}>Relevés de température</Text>
            </View>
          </TouchableHighlight>
          <TouchableHighlight style={mainStyleSheet.buttonHomeContainer} onPress={() => navigate('BonsLivraisons')}>
            <View style={mainStyleSheet.buttonHome}>
              <Ionicons name="file-invoice" style={{ marginLeft: 20 }} color="white" size={30} />
              <Text style={mainStyleSheet.buttonText}>Bons de livraisons</Text>
            </View>
          </TouchableHighlight>
          <TouchableHighlight style={mainStyleSheet.buttonHomeContainer} onPress={() => navigate('DownloadableDocuments')}>
            <View style={mainStyleSheet.buttonHome}>
              <Ionicons name="file-image" style={{ marginLeft: 20 }} color="white" size={30} />
              <Text style={mainStyleSheet.buttonText}>Documents à télécharger</Text>
            </View>
          </TouchableHighlight>
        </View>
      </ScrollView>
    </SafeAreaView>
  )
}`

**Expected Behavior**

- What do you expect should be happening?
No error

**How to reproduce**
On home i get that error: The action 'SET_PARAMS' with the payload {"params":{"company":"Marciello Resto 2"}} was not handled by any navigator.

**Your Environment**

MacOs (Latest)
Android
@react-navigation/native
react-native
node
npm

**Comment by osdnk** [comment]
Can you show us some snack with repro steps?

**Comment by satya164** [comment]
Closing since you didn't follow the issue template.
