### ISSUE TITLE
Swipe back event with react-navigation v5.0

### ISSUE THREAD

**Issue by tusharpandey** [react-navigation/react-navigation#8074]
**Current Behavior**

With React native 5.0, I am not able to find a way to get swipe-back event in ios.

```
const Funnel = () => {
  return (
    <Stack.Navigator
      options={({ route }) => ({

      })}
      screenOptions={{
        headerShown: true,
        ...TransitionPresets.SlideFromRightIOS,
        header: props => <Header {...props} />,
      }}
    >
      <Stack.Screen name="page1" component={ContactContainer} />
      <Stack.Screen name="page2" component={WorkExpContainer} />
      <Stack.Screen name="page3" component={Education} />
      <Stack.Screen name="page4" component={Skill} />
      <Stack.Screen name="page5" component={Summary} />
      <Stack.Screen name="page6" component={Finalize} />
    </Stack.Navigator>
  )
}
```

**Expected Behavior**

with react native < 5.0 I was able to get callback on swipe-back by this code section.
```
const Funnel = createStackNavigator({
  page1: ContactContainer,
  page2: WorkExpContainer,
  page3: Education,
  page4: Skill,
  page5: Summary,
  page6: Finalize,
}, {
  defaultNavigationOptions: ({ navigation }) => ({
    ...TransitionPresets.SlideFromRightIOS,
    header:
      (<SafeAreaView style={{ flex: 1 }} forceInset={{ bottom: 'never' }}>
        <AppHeader pageData={navigation.state.params == undefined ? data : navigation.state.params} />
      </SafeAreaView>),
  }),
  mode: "card"
})

const defaultGetStateForAction = Funnel.router.getStateForAction;
Funnel.router.getStateForAction = (action, state) => {
  if (action.type == 'Navigation/POP') {
    back()
  }
  return defaultGetStateForAction(action, state);
};
```

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                | ios 
| @react-navigation/native       | yes
| react-native                   |yes
| expo                           | no
| node                           |
| npm or yarn                    |

**Comment by hao1234567** [comment]
Hello!I got the same problem.I want to custom router with **getStateForAction** ,but can not read the router and getStateForAction properties now.Have you solved the problem?

**Comment by tusharpandey** [comment]
> Hello!I got the same problem.I want to custom router with **getStateForAction** ,but can not read the router and getStateForAction properties now.Have you solved the problem?

I have posted this issue yesterday, looking for response from community.

**Comment by hao1234567** [comment]
Uh.If they are slow to respond to this question,i will change this code directly temporarily.(the getStateForAction code in /node_modules/@react-navigation/routers/src/StackRouter.tsx)

**Comment by hao1234567** [comment]
> > Hello!I got the same problem.I want to custom router with **getStateForAction** ,but can not read the router and getStateForAction properties now.Have you solved the problem?
> 
> I have posted this issue yesterday, looking for response from community.

Uh.If they are slow to respond to this question,i will change this code directly temporarily.(the getStateForAction code in /node_modules/@react-navigation/routers/src/StackRouter.tsx)

**Comment by hao1234567** [comment]
> > Hello!I got the same problem.I want to custom router with **getStateForAction** ,but can not read the router and getStateForAction properties now.Have you solved the problem?
> 
> I have posted this issue yesterday, looking for response from community.

Thank you for reply!You can try this too.

**Comment by tusharpandey** [comment]
> > > Hello!I got the same problem.I want to custom router with **getStateForAction** ,but can not read the router and getStateForAction properties now.Have you solved the problem?
> > 
> > 
> > I have posted this issue yesterday, looking for response from community.
> 
> Uh.If they are slow to respond to this question,i will change this code directly temporarily.(the getStateForAction code in /node_modules/@react-navigation/routers/src/StackRouter.tsx)

that's not a good approach, to play with library packages ..

**Comment by tusharpandey** [comment]
@satya164 , can you please suggest a way to handle this ?

**Comment by tusharpandey** [comment]
> > > Hello!I got the same problem.I want to custom router with **getStateForAction** ,but can not read the router and getStateForAction properties now.Have you solved the problem?
> > 
> > 
> > I have posted this issue yesterday, looking for response from community.
> 
> Thank you for reply!You can try this too.

hi @hao1234567 , how you have handled that ?

**Comment by hao1234567** [comment]
> > > > Hello!I got the same problem.I want to custom router with **getStateForAction** ,but can not read the router and getStateForAction properties now.Have you solved the problem?
> > > 
> > > 
> > > I have posted this issue yesterday, looking for response from community.
> > 
> > 
> > Thank you for reply!You can try this too.
> 
> hi @hao1234567 , how you have handled that ?

Uh,i had found no good way to handle this,so i changed the code for this v5.0 directly. I do not know what you did with this code,but I think you can try this way to solve the problem for the moment( if you are in a hurry to solve the problem).Or,you can roll this navigation back to the old version.I will always focus on and try to solve this problem in a better way(means no changes to these library packages)

**Comment by hao1234567** [comment]
> > > > Hello!I got the same problem.I want to custom router with **getStateForAction** ,but can not read the router and getStateForAction properties now.Have you solved the problem?
> > > 
> > > 
> > > I have posted this issue yesterday, looking for response from community.
> > 
> > 
> > Thank you for reply!You can try this too.
> 
> hi @hao1234567 , how you have handled that ?

Uh,i had found no good way to handle this,so i changed the code for this v5.0 directly.I do not know what you did with your code,but I think you can try this way to solve the problem for the moment( if you are in a hurry to solve this problem).Or,you can roll this navigation back to the old version.I will always focus on and try to solve this problem in a better way(means no changes to these library packages)

**Comment by osdnk** [comment]
Hi,
This https://reactnavigation.org/docs/custom-routers#blocking-navigation-actions might be interesting if you'd like to build your own router.  

Also, https://reactnavigation.org/docs/stack-navigator/#transitionstart events can be your ally

**Comment by hao1234567** [comment]
> Hi,
> This https://reactnavigation.org/docs/custom-routers#blocking-navigation-actions might be interesting if you'd like to build your own router.
> 
> Also, https://reactnavigation.org/docs/stack-navigator/#transitionstart events can be your ally

Yes,i know this chapter,but the docs doesn't show how to use custom routers.The docs just show how to make a custom router,but doesn't show how to use.

**Comment by tusharpandey** [comment]
I am using panResponder for that ....
`export let panResponder = (callback) => PanResponder.create({
  onMoveShouldSetResponderCapture: () => true,
  onMoveShouldSetPanResponderCapture: (evt, gestureState) => {
    const isFarLeft = evt.nativeEvent.pageX < Math.floor(width * 0.25);
    if (isFarLeft) {
      return true;
    }
    return false;
  },
  onPanResponderRelease: (evt, gestureState) => {
    if (Platform.OS != 'ios') return
    if (Math.floor(gestureState.moveX) <= width / 4) {
      if (callback != undefined) callback()
      NavigationService.goBack()
    }
  },
});`

and using it my parent view like 

return (
      <KeyboardAwareScrollView style={GlobalStyle.notchMargin}>
        <View
          {...panResponder(back).panHandlers}
          style={styles.parent}>
              </View>
      </KeyboardAwareScrollView>
);

**Comment by jwhitty1** [comment]
> so first disable left gesture.
> gestureEnabled: false,
> 
> I am using panResponder for providing that left swipe functionality ....
> 
> `export let panResponder = (callback) => PanResponder.create({ onMoveShouldSetResponderCapture: () => true, onMoveShouldSetPanResponderCapture: (evt, gestureState) => { const isFarLeft = evt.nativeEvent.pageX < Math.floor(width * 0.25); if (isFarLeft) { return true; } return false; }, onPanResponderRelease: (evt, gestureState) => { if (Platform.OS != 'ios') return if (Math.floor(gestureState.moveX) <= width / 4) { if (callback != undefined) callback() NavigationService.goBack() } }, });`
> 
> and using it my parent view like
> `return ( <KeyboardAwareScrollView> <View {...panResponder(back).panHandlers} style={styles.parent}> </View> </KeyboardAwareScrollView> );`
> 
> and 1 catch is that always use padding in place of margin to give default margin in the screen for layout.
> 
> ![Screenshot 2020-05-03 at 2 41 22 PM](https://user-images.githubusercontent.com/4696846/80910320-47cefd80-8d4c-11ea-85bf-ab74bedd5ce3.png)

Where are you supposed to write "gestureEnabled: false" ?? It's annoying to have to just copy/paste it everywhere until it works when you could've said where to write it and saved me/everyone else that time..

**Comment by spacebnd** [comment]
> Where are you supposed to write "gestureEnabled: false" ?? It's annoying to have to just copy/paste it everywhere until it works when you could've said where to write it and saved me/everyone else that time..

try this:
`
import React from "react";
import { NavigationContainer } from "@react-navigation/native";
import { createStackNavigator } from "@react-navigation/stack";

const Stack = createStackNavigator();

const AppNavigation = () => {
  return (
    <NavigationContainer>
      <Stack.Navigator
        screenOptions={{
          gestureEnabled: false,
        }}
      >
        <Stack.Screen name="Dashboard" component={Dashboard} />
        <Stack.Screen name="MainMenu" component={MainMenu} />
         // other screens
      </Stack.Navigator>
    </NavigationContainer>
  );
};

export default AppNavigation;
`

**Comment by spacebnd** [comment]
> Where are you supposed to write "gestureEnabled: false" ?? It's annoying to have to just copy/paste it everywhere until it works when you could've said where to write it and saved me/everyone else that time..

try this:

```import React from "react";
import { NavigationContainer } from "@react-navigation/native";
import { createStackNavigator } from "@react-navigation/stack";

const Stack = createStackNavigator();

const AppNavigation = () => {
  return (
    <NavigationContainer>
      <Stack.Navigator
        screenOptions={{
          gestureEnabled: false,
        }}
      >
        <Stack.Screen name="Dashboard" component={Dashboard} />
        <Stack.Screen name="MainMenu" component={MainMenu} />
      </Stack.Navigator>
    </NavigationContainer>
  );
};

export default AppNavigation;
