### ISSUE TITLE
@react-navigation/drawer@5.5.0 - 'openByDefault' throws type does not exist error.

### ISSUE THREAD

**Issue by astron97** [react-navigation/react-navigation#8075]
**Current Behavior**

<Drawer.Navigator
      drawerPosition="right"
      drawerStyle={styles.drawer}
      drawerContent={props => <CustomDrawerContent {...props} />}
      screenOptions={{gestureEnabled: false}}
      openByDefault={true}>
The prop 'openByDefault' passed to Drawer.Navigator component throws the error property does not exist.

**Expected Behavior**
The prop should be made available.

**How to reproduce**
import {createDrawerNavigator} from '@react-navigation/drawer';
const Drawer = createDrawerNavigator();
<Drawer.Navigator
      drawerPosition="right"
      drawerStyle={styles.drawer}
      drawerContent={props => <CustomDrawerContent {...props} />}
      screenOptions={{gestureEnabled: false}}
      openByDefault={true}>
      </Drawer.Navigator>
**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Android
| @react-navigation/native       | @react-navigation/native@5.1.6
| @react-navigation/drawer       | @react-navigation/drawer@5.5.0
| react-native-reanimated        | "react-native-reanimated": "^1.7.1",
| react-native-gesture-handler   |     "react-native-gesture-handler": "^1.6.1",
| react-native-safe-area-context | "react-native-safe-area-context": "^0.7.3"
| react-native-screens           | "react-native-screens": "^2.4.0"
| react-native                   | "react-native": "0.61.5"
| expo                           | none
| node                           | 12.13.0
| npm or yarn                    | 1.22.4

**Comment by satya164** [comment]
Closing since you didn't provide a repro.

**Comment by hsavit1** [comment]
I am also having this problem on my react-native-web project
