### ISSUE TITLE
Unable to set transparent BG of Tab Navigator Screen

### ISSUE THREAD

**Issue by chasepoirier** [react-navigation/react-navigation#8076]
**Current Behavior**
I'm not able to set the background color of the Tab Navigator screen to transparent, it instead shows the default gray background. I can set the tabbar component to transparent as seen in the screenshot (the color behind the tab navigator is black), but the screen does not do the same.

<img width="455" alt="Screen Shot 2020-04-19 at 7 48 23 PM" src="https://user-images.githubusercontent.com/23040747/79703031-139d0c80-8277-11ea-8fad-58e874179e66.png">

- current code

```
import React from "react";
import { createBottomTabNavigator } from "@react-navigation/bottom-tabs";
import { View, Text } from "react-native";
import { NavigationContainer } from "@react-navigation/native";

const Tab = createBottomTabNavigator();

const Component = () => {
  return (
    <View
      style={{
        flex: 1,
        backgroundColor: "transparent",
        justifyContent: "center",
        alignItems: "center"
      }}>
      <Text>Component</Text>
    </View>
  );
};

export default function MockTabStack() {
  return (
    <NavigationContainer>
      <Tab.Navigator
        tabBarOptions={{
          style: {
            backgroundColor: "transparent"
          }
        }}>
        <Tab.Screen component={Component} name="Initial" />
      </Tab.Navigator>
    </NavigationContainer>
  );
}
```

**Expected Behavior**

When setting the background to transparent for the tab navigator screen, it should show the color below the navigator (black in this case).

**How to reproduce**

- Set the background style to "transparent" for the screen

**Your Environment**

| software                      | version |
| ----------------------------- | ------- |
| @react-navigation/native      | 5.1.6
| @react-navigation/bottom-tabs | 5.2.7
| react-native-screens          | 2.5.0
| react-native                  | 0.61.2
| node                          | 10.16.3

**Comment by rdjuric** [comment]
Hi,

Have you tried adding position: "absolute" on your style? That's what made it work for me.
```
style: {
	position: "absolute",
	backgroundColor: "transparent",
	borderTopWidth: 0,
	marginBottom: 0,
	borderRadius: 10,
}
```

**Comment by ozerty** [comment]
Hi, any news about this one ?

Thanks

**Comment by ShivamJoker** [comment]
I am screwed too 
![image](https://user-images.githubusercontent.com/23727670/83622745-05e4e180-a5ae-11ea-8b90-02aee14a6fde.png)
Can someone please help ?

**Comment by bartekkaminski** [comment]
@ShivamJoker 

Add `elevation: 0`

The code below will make a transparent bottom bar

`    <NavigationContainer>
      <Tab.Navigator tabBarOptions={{
        style: {
          backgroundColor: 'transparent',
          position: 'absolute',
          borderTopWidth: 0,
          elevation: 0,
        }
      }}>
        <Tab.Screen name="Home" component={Home} />
        <Tab.Screen name="Second" component={Second} />
      </Tab.Navigator>
    </NavigationContainer>`

**Comment by ShivamJoker** [comment]
> @ShivamJoker
> 
> Add `elevation: 0`
> 
> The code below will make a transparent **Bottom Bar**
> 
> ```
> <NavigationContainer>
>   <Tab.Navigator tabBarOptions={{
>     style: {
>       backgroundColor: 'transparent',
>       position: 'absolute',
>       borderTopWidth: 0,
>       elevation: 0,
>     }
>   }}>
>     <Tab.Screen name="Home" component={Home} />
>     <Tab.Screen name="Second" component={Second} />
>   </Tab.Navigator>
> </NavigationContainer>
> ```

Thanks this works we should close the issue now :)

**Comment by steventeague** [comment]
Hi,

This issue remains, as the OP stated the BG colour can't not be set on the screen ( not the bar ) it is always the default grey. Having a requirement to make the background transparent to overlay over native screens means this is broken.

**Comment by crrobinson14** [comment]
Not sure if this is the same issue holding this ticket open, but I was able to address this with `sceneContainerStyle={{backgroundColor: 'transparent'}}` in my `<Tab.Navigator` element.

**Comment by lukehamilton** [comment]
@chasepoirier @crrobinson14 This took me hours to figure out. I had to go into the actual package to see how the styles were being applied.

But the only way to change the background color of the actual tab views that are for each scene in the bottom tab navigator is to pass a theme into the top level `NavigationContainer` component where you specify `transparent` for `colors.background`

```
import { NavigationContainer } from "@react-navigation/native";
import { createBottomTabNavigator } from "@react-navigation/bottom-tabs";

const Tab = createBottomTabNavigator();

const theme = {
    colors: {
      background: "transparent",
    },
  };

<NavigationContainer theme={theme}>
     <Tab.Navigator>
          <Tab.Screen component={ComponentA} name="A" />
          <Tab.Screen component={ComponentB} name="B" />
     </Tab.Navigator>
</NavigationContainer>
```

In the above example `ComponentA` and `ComponentB` the screens for each of the tabs will have transparent backgrounds.

Hope this helps! 😄

**Comment by mvrdrew** [comment]
@lukehamilton Thanks for that suggestion, I've tried out it and it works but it breaks other components in the hierarchy so it's still not a 100% solution.

@crrobinson14 I've had a look for that setting, but it doesn't exist in bottom-tabs, only on drawerNavigator and materialTopTabNavigator.

It seems like that's the ideal prop for this situation though, has it been left off bottom-tabs for a reason or has it just been overlooked in the v5 rewrite? It does seem very odd that there's no way to change the background colour of tab screens like you can in other navigators.

**Comment by mvrdrew** [comment]
I thought I'd have a go at implementing sceneContainerStyle into the bottom-tabs navigator. It's partially based on the drawer implementation, so you can still use a theme but also override using this prop's styles.

Before I submit a PR, I thought I'd put it up here first to see if there's any glaring errors I've made. 

https://github.com/mvrdrew/react-navigation/commit/b490141842b60e23d335e525a16612f4d17b2fc6

If any maintainers see this, I'd be really keen to hear their feedback and if it's worth continuing with.

**Comment by mvrdrew** [comment]
This ticket can be closed now this PR has been merged.

**Comment by bondansebastian** [comment]
> @ShivamJoker
> 
> Add `elevation: 0`
> 
> The code below will make a transparent **Bottom Bar**
> 
> ```
> <NavigationContainer>
>   <Tab.Navigator tabBarOptions={{
>     style: {
>       backgroundColor: 'transparent',
>       position: 'absolute',
>       borderTopWidth: 0,
>       elevation: 0,
>     }
>   }}>
>     <Tab.Screen name="Home" component={Home} />
>     <Tab.Screen name="Second" component={Second} />
>   </Tab.Navigator>
> </NavigationContainer>
> ```

You saved my life buddy.

**Comment by predbjorn** [comment]
> > @ShivamJoker
> > Add `elevation: 0`
> > The code below will make a transparent **Bottom Bar**
> > ```
> > <NavigationContainer>
> >   <Tab.Navigator tabBarOptions={{
> >     style: {
> >       backgroundColor: 'transparent',
> >       position: 'absolute',
> >       borderTopWidth: 0,
> >       elevation: 0,
> >     }
> >   }}>
> >     <Tab.Screen name="Home" component={Home} />
> >     <Tab.Screen name="Second" component={Second} />
> >   </Tab.Navigator>
> > </NavigationContainer>
> > ```
> 
> Thanks this works we should close the issue now :)

Works on v6.x too: 
`screenOptions={() => {
       tabBarStyle: {
            backgroundColor: 'transparent',
            position: 'absolute',
            borderTopWidth: 0,
            elevation: 0,
        },
    }}      
`

**Comment by Lakshya-Katarmal** [comment]
> @ShivamJoker
> 
> Add `elevation: 0`
> 
> The code below will make a transparent **Bottom Bar**
> 
> ```
> <NavigationContainer>
>   <Tab.Navigator tabBarOptions={{
>     style: {
>       backgroundColor: 'transparent',
>       position: 'absolute',
>       borderTopWidth: 0,
>       elevation: 0,
>     }
>   }}>
>     <Tab.Screen name="Home" component={Home} />
>     <Tab.Screen name="Second" component={Second} />
>   </Tab.Navigator>
> </NavigationContainer>
> ```

this worked for me.
 Thanks @ShivamJoker

**Comment by aliciabarczak** [comment]
For anyone who is struggling and none of the above worked, this is what worked for me:
  ```
<Tab.Navigator
    screenOptions={({ route }) => ({
      ...
      tabBarStyle: [{
        backgroundColor: 'transparent',
        position: 'absolute',
        borderTopWidth: 0,
        elevation: 0,
      }],
    })}>
```

**Comment by ToxicoFR** [comment]
> For anyone who is struggling and none of the above worked, this is what worked for me:
> 
> ```
> <Tab.Navigator
>   screenOptions={({ route }) => ({
>     ...
>     tabBarStyle: [{
>       backgroundColor: 'transparent',
>       position: 'absolute',
>       borderTopWidth: 0,
>       elevation: 0,
>     }],
>   })}>
> ```

Thanks!!

**Comment by abuayaan-01** [comment]
> Not sure if this is the same issue holding this ticket open, but I was able to address this with `sceneContainerStyle={{backgroundColor: 'transparent'}}` in my `<Tab.Navigator` element.

Thanks a lot I have been putting this inside ScreenOptions

**Comment by ngdbao** [comment]
> @ShivamJoker
> 
> Add `elevation: 0`
> 
> The code below will make a transparent **Bottom Bar**
> 
> ```
> <NavigationContainer>
>   <Tab.Navigator tabBarOptions={{
>     style: {
>       backgroundColor: 'transparent',
>       position: 'absolute',
>       borderTopWidth: 0,
>       elevation: 0,
>     }
>   }}>
>     <Tab.Screen name="Home" component={Home} />
>     <Tab.Screen name="Second" component={Second} />
>   </Tab.Navigator>
> </NavigationContainer>
> ```

In my test, this position absolute causing Screen Content stop avoiding Tab bar, then I have to manually insert safe-area in every single screen's footer
