### ISSUE TITLE
Is it possible to do snapshot testing with react navigation (RN/Typescript)?

### ISSUE THREAD

**Issue by joongyoon95** [react-navigation/react-navigation#8077]
**Current Behavior**

- I am having some difficulties creating snapshot unit tests for my React Native (Typescript) project.

- My project requires react navigation to navigate between screens. Therefore, it needs NavigationInjectedProps as the required prop [1].

**Expected Behavior**

- It should allow me to do snapshot testing without any error or warning

**How to reproduce**

- When I try to pass jest mocks [2] as the required props of the component for unit testing, it will just give me the warnings [3]

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |
| @react-navigation/native       |
| react-native                   |
| expo                           |
| node                           |
| npm or yarn                    | 

[1]
<img width="517" alt="Screen Shot 2020-04-20 at 10 25 10 AM" src="https://user-images.githubusercontent.com/56858879/79705619-4b489a80-82f1-11ea-8534-993d8f0b3ce9.png">

[2]
<img width="382" alt="Screen Shot 2020-04-20 at 10 17 23 AM" src="https://user-images.githubusercontent.com/56858879/79705615-471c7d00-82f1-11ea-9c81-fa3a0a0714fe.png">

[3]
<img width="624" alt="Screen Shot 2020-04-20 at 10 17 46 AM" src="https://user-images.githubusercontent.com/56858879/79705618-4a176d80-82f1-11ea-9131-44a7dbd00e59.png">

**Comment by hamzahayat** [comment]
Any luck with this @joongyoon95?

**Comment by satya164** [comment]
https://reactnavigation.org/docs/testing#mocking-native-modules

**Comment by NorfeldtAbtion** [comment]
@satya164 the docs you link to is quite sparse on details and good examples...
