### ISSUE TITLE
React Navigation 5: useScrollToTop Bug

### ISSUE THREAD

**Issue by jjg77** [react-navigation/react-navigation#8078]
```
    "@react-native-community/masked-view": "0.1.6",
    "@react-navigation/bottom-tabs": "^5.0.0",
    "@react-navigation/drawer": "^5.4.1",
    "@react-navigation/native": "^5.0.0",
    "@react-navigation/stack": "^5.0.0",
    "@react-navigation/web": "~1.0.0-alpha.9",
    "expo": "~37.0.3",
```

Nav structure looks like this:

DrawerNavigator
--StackNavigator
----BottomTabNavigator
-------StackNavigator (Tab 1)
---------Screen A (has a flatlist)
---------Screen B (has a flatlist)
---------Screen C (has a flatlist)
---------Screen D (has a flatlist)
-------StackNavigator (Tab 2)
-------StackNavigator (Tab 3)

The bug is that whenever I click on Tab 1, to trigger the scroll to top, it scrolls to the top of Screen A.  Even if I'm on Screen B, C, or D.  I would expect it to scroll to the top of the current screen.

Bug is seen on both web and android.

All of the screens are setup similar, but have different flatlists.  Here's how the useScrollToTop is implemented on each screen:

```
const listRef  = React.useRef();
useScrollToTop(listRef);
<FlatList ref={listRef} ... >
```

**Comment by satya164** [comment]
Closing since you didn't provide a repro.
