### ISSUE TITLE
White flickering in the edge when poping the screen

### ISSUE THREAD

**Issue by sa8ab** [react-navigation/react-navigation#8083]
**Current Behavior**
I get this white flickering when poping the stack screen
![ezgif-7-e3e764591441](https://user-images.githubusercontent.com/59901734/79758434-43c5c900-82d2-11ea-8250-f9c28311ea25.gif)

On Android
    "react-navigation": "^4.3.7",
    "react-navigation-stack": "^2.3.11",

**Comment by sa8ab** [comment]
Just upgraded to the 2.3.12 and still the same

**Comment by N1ghtly** [comment]
I'm running into this issue as well. Also on latest version.

**Comment by sa8ab** [comment]
@N1ghtly I solved it by removing enableScreens from react-native-screens, are you using it as well?
