### ISSUE TITLE
Navigator header has not been hidden by using properly screenOptions in a Stacknavigator

### ISSUE THREAD

**Issue by renatobenks** [react-navigation/react-navigation#8084]
**Current Behavior**

- What code are you running and what is happening?

The header has not been hide as expected when using the `screenOptions` at the stack navigator to do it, as the following examples:

1. Firstly, I've tried to use the `headerMode` as `none`, because I already did it successfully in previous versions of react-navigation, like such:

```js
/**
 * @flow
 */

import * as React from 'react';
import {createStackNavigator} from '@react-navigation/stack';

import Welcome from '../../screens/Welcome/Welcome';
import LookSteps from '../../screens/LookSteps/LookSteps';

import {ONBOARDING_HOME, ONBOARDING_LOOK_STEPS} from '../routes';

const OnboardingStack = createStackNavigator();

const options = {
  headerMode: 'none',
};

const OnboardingRouter = () => {
  return (
    <OnboardingStack.Navigator
      initialRouteName={ONBOARDING_HOME}
      screenOptions={options}>
      <OnboardingStack.Screen name={ONBOARDING_HOME} component={Welcome} />
      <OnboardingStack.Screen
        name={ONBOARDING_LOOK_STEPS}
        component={LookSteps}
      />
    </OnboardingStack.Navigator>
  );
};

export default OnboardingRouter;
```

2. Then, I've tried to use the `header` option as a function that retrieves `null`, like such:

```js
/**
 * @flow
 */

import * as React from 'react';
import {createStackNavigator} from '@react-navigation/stack';

import Welcome from '../../screens/Welcome/Welcome';
import LookSteps from '../../screens/LookSteps/LookSteps';

import {ONBOARDING_HOME, ONBOARDING_LOOK_STEPS} from '../routes';

const OnboardingStack = createStackNavigator();

const options = {
  header: () => null,
};

const OnboardingRouter = () => {
  return (
    <OnboardingStack.Navigator
      initialRouteName={ONBOARDING_HOME}
      screenOptions={options}>
      <OnboardingStack.Screen name={ONBOARDING_HOME} component={Welcome} />
      <OnboardingStack.Screen
        name={ONBOARDING_LOOK_STEPS}
        component={LookSteps}
      />
    </OnboardingStack.Navigator>
  );
};

export default OnboardingRouter;
```

- Include a screenshot or video if it makes sense.

The first try with the `headerMode` as `'none'` should hide the header completely but it doesn't:

> it happens in both iOS and Android

![Simulator Screen Shot - iPhone 7 - 2020-04-20 at 10 16 01](https://user-images.githubusercontent.com/51369951/79756159-94e4b580-82f0-11ea-9a48-a01f5b9eb8c1.png)

The second try with `header: () => null` shouldn't have a margin between the screen component and screen top as displayed below, so it hides the header but keeps a margin in the screen:

> it happens just in iOS. Android works well.

![Simulator Screen Shot - iPhone 7 - 2020-04-20 at 10 36 41](https://user-images.githubusercontent.com/51369951/79757715-d6766000-82f2-11ea-8625-5019009cb4d4.png)

**Expected Behavior**

- What do you expect should be happening?

I was expecting the header to be completely hidden by using these such options described here.

**How to reproduce**

It's too easy as possible! You just need to have a stack navigator and try to hide the header by using these such options explained here as I did.

**How to solve it**

I could get it fixed by using the `headerShown` option as `false`. However, following the react-navigation docs, it should be fixed by using both ways described here as well, such as using respectively the both `header` and `headerMode` options.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | iOS and Android
| @react-navigation/native       | ^5.1.4
| @react-navigation/stack        | ^5.2.9
| react-native-gesture-handler   | ^1.6.1
| react-native-safe-area-context | ^0.7.3
| react-native-screens           | ^2.4.0
| react-native                   | 0.61.5
| expo                           |
| node                           | 12.16.1
| npm or yarn                    | 1.17.3

**Comment by renatobenks** [comment]
I've upgraded the both `@react-navigation/native` and `@react-navigation/stack` packages, and the problem it's still happening in both scenarios as described above.

**Comment by raajnadar** [comment]
Try `headerShown: false`  https://reactnavigation.org/docs/stack-navigator/#headershown

If that did not work add a repro.

**Comment by renatobenks** [comment]
@raajnadar take a look in the issue description, I've described how I fixed it by using the `headerShow` option as you suggested:

> **How to solve it:**

> I could get it fixed by using the headerShown option as false. However, following the react-navigation docs, it should be fixed by using both ways described here as well, such as using respectively the both header and headerMode options.

However, also the other both options described should be working as `headerShown` works, right?

**Comment by raajnadar** [comment]
`headerMode: 'none'` is a prop and not a `screenOptions` option.

This is the right way

```
<MainStackNav.Navigator headerMode="none">
    ...
</MainStackNav.Navigator>
```

**Comment by renatobenks** [comment]
@raajnadar great, you're right, and it's properly updated in the docs BTW! 

but what about the `header` option as component rendering `null`?
