### ISSUE TITLE
Error while placing a GoToButton that navigates from one child component to another

### ISSUE THREAD

**Issue by AntoniSkup** [react-navigation/react-navigation#8085]
Hello, I created a go to button in react navigation 5 to go from my login screen to TabNavigation
`//SwitchNavigator.js file
 function GoToButton({ screenName }) {
    const navigation = useNavigation();

    return (
        <TouchableOpacity
            title={${screenName}}
            onPress={() => navigation.navigate(screenName)}  style={styles.buttonLogin}> 
            <Text style={{color: '#ffcc00', fontWeight: 'bold'}}>Start!</Text>
        </TouchableOpacity>
    );
} 
 `
and I want to call it in my Login.js file which is then refrenced 
`//SwitchNavigator.js file
function LoginScreen({navigation}) {
    return (
        <View>
            <Login />
        </View>
        
    );
}`
But when i import the button to Login.js I get the error saying that I have nested NavigationContainer inside another. 
 `class Login extends React.Component  {
  login = () => {
    this.props.login(this.props.email)
  }
  render() {
    return (
      <View style={{ position: 'absolute', justifyContent: 'center', alignItems: 'center', flex: 1,  justifyContents: "flex-end", width: screenWidth, height: screenHeight, backgroundColor: 'white', }}>
        <View style={styles.box}>
          
          <TextInput value={this.props.user} style={styles.textarea} onChangeText={input => this.props.updateEmail(input)}
          placeholder='Email'/>
          <TextInput value={this.props.user} style={styles.textarea} onChangeText={input => this.props.updatePassword(input)}
            placeholder='Password' />  
          
          <GoToButton screenName="TabNavigator" onPress={() => this.login()}/>
        </View>
              
      </View>
    );
  }
}`
My navigation:
`const Stack = createStackNavigator();

export default function App() {
    let [fontsLoaded] = useFonts({
        'Pacifico-Regular': require('../assets/fonts/Pacifico-Regular.ttf'),
    });

    if (!fontsLoaded) {
        return <AppLoading />;
    } else {
        return (
            <NavigationContainer>
                <Stack.Navigator>
                    
                    <Stack.Screen name="Welcome" component={WelcomeScren} />
                    <Stack.Screen name="Login" component={LoginScreen}  />
                    <Stack.Screen name="Signup" component={SignupScreen}/>
                    <Stack.Screen name="TabNavigator" component={TabNavigatorScreen} />
                    
                </Stack.Navigator>
            </NavigationContainer>
        
        );
    }
}`
TabNavigator.js 
`//TabMavigator file
function UploadScreen() {
    return (
        <Upload/>
    );
}
function FriendsScreen() {
    return (
        <Friends/>
    );
}
function HomeScreen() {
    return (
        <Home/>
    );
}
function SpecialScreen() {
    return (
        <Special/>
    );
}
function ProfileScreen() {
    return (
        <Profile/>
    );
}
const Tab = createBottomTabNavigator();
export default function App() {
    return (
            <Tab.Navigator initialRouteName="Home" >
                <Tab.Screen name="Upload" options={{
                    tabBarLabel: 'Upload',
                    justifyContent: 'center',
                    tabBarIcon: ({ color, size}) => (<MaterialCommunityIcons name="pen" color={color} size={32} />),
                }} component={UploadScreen}/>
                <Tab.Screen name="Friends" options={{
                    tabBarLabel: 'Friends',
                    tabBarIcon: ({ color, size }) => (<MaterialCommunityIcons name="heart" color={color} size={32}/>),
                }} component={FriendsScreen}/>
                <Tab.Screen name="Home" options={{
                    tabBarLabel: 'Home',
                    
                    tabBarIcon: ({ color, size }) => (<MaterialCommunityIcons name="web" color={color} size={32}/>),
                }}component={HomeScreen}/>
                <Tab.Screen name="Special" options={{
                    tabBarLabel: 'Special',
                    tabBarIcon: ({ color, size }) => (<MaterialCommunityIcons name="special" color={color} size={32}/>),
                }}component={SpecialScreen}/>
                <Tab.Screen name="Profile" options={{
                    tabBarLabel: 'Profile',
                    
                    tabBarIcon: ({ color, size }) => (<MaterialCommunityIcons name="account" color={color} size={32}/>),
                }}component={ProfileScreen} />
            </Tab.Navigator>
       
    );
}
`
the Upload, FriendsScreen, etc components are normal components that don't include react-navigation

![](https://cdn.discordapp.com/attachments/288388742929055765/701795182919680070/unknown.png)
 I double checked and there is no other NavigationContainer in my whole program. 
Regards

**Comment by satya164** [comment]
Closing since you didn't follow the issue template.
