### ISSUE TITLE
Text not selectable on web

### ISSUE THREAD

**Issue by RWOverdijk** [react-navigation/react-navigation#8086]
**Current Behavior**

This is one of those "hard to classify" issues. I have no idea where this is coming from, but I know it has something to do with react navigation.

I'm in the beautiful world of React navigation + React-native-web and when using react-navigation the text on the page can no longer be selected.

This issue includes mouse dragging, double click and cmd+a (ctrl+a if you're into that) to select text.

**Expected Behavior**

Text selectable

**How to reproduce**

Very simple this time.  call `npx expo init` and pick the managed workflow "tabs" _(several example screens and tabs using react-navigation)_.

When that's done navigate into the new project created and just run `yarn web`. After some time the webpage will open and none of the text on it is selectable.

**Your Environment**

    "react-native": "https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz",
    "@react-navigation/bottom-tabs": "^5.0.0",
    "@react-navigation/native": "^5.0.0",
    "@react-navigation/stack": "^5.0.0",
    "@react-navigation/web": "~1.0.0-alpha.9",
    "expo": "~37.0.3",

**Comment by RWOverdijk** [comment]
I can't because it's expo managed. Out of my control, but the issue is specific enough to ring bells (or not) so I'm taking my chances 😄

**Comment by satya164** [comment]
> I can't because it's expo managed

React Navigation can be updated independently from Expo. They are not tied to Expo SDK versions.

Disabling text selection is coming from react-native-gesture-handler. cc @EvanBacon 

It'll better if you open an issue in gesture handler repo.

**Comment by RWOverdijk** [comment]
@satya164 That's fair. I tried updating it afterwards anyway (because I had another issue with react-native-web) but now that you pointed me in the right direction I found this: https://github.com/software-mansion/react-native-gesture-handler/pull/1037

So I'll give that a go first! Thanks a lot.
