### ISSUE TITLE
openByDefault doesn't work in React Native Web

### ISSUE THREAD

**Issue by sohcah** [react-navigation/react-navigation#8087]
**Current Behavior**
Settings the openByDefault prop on a Drawer Navigator doesn't open the drawer by default on React Native Web.

**Expected Behavior**
Settings the openByDefault prop on a Drawer Navigator should open the drawer by default on React Native Web.

**How to reproduce**
Can't make a Snack as it fails to resolve React Navigation packages.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |Web
| @react-navigation/native       |5.1.6
| @react-navigation/drawer       |5.5.0
| react-native-reanimated        |1.7.1
| react-native-gesture-handler   |1.6.1
| react-native-safe-area-context |0.7.3
| react-native-screens           |2.2.0
| react-native                   |0.61.4
| expo                           |37.0.7
| node                           |12.4.0
| npm or yarn                    |yarn 1.19.0

**Comment by satya164** [comment]
Closing since you didn't provide a repro.
