### ISSUE TITLE
Screen layering transparancy bug

### ISSUE THREAD

**Issue by reimertz** [react-navigation/react-navigation#8089]
**Current Behavior**
![image](https://user-images.githubusercontent.com/625287/79807748-22192000-836c-11ea-8ae2-69d5769d7c61.png)

**Expected Behavior**
![image](https://user-images.githubusercontent.com/625287/79807837-5db3ea00-836c-11ea-9f36-d3c569e6e8f3.png)

**How to reproduce**

We cannot reproduce but get multiple reports by users running android on `Android 10 (API 29)`.

We do set the background but  wonder if there could be a race-condition since we do something like this 

```
const Screen = ({ level, children }) =>
<View style={styles.container(level)}>
  {children}
</View>

//styles.js
export const styles = {
  container: (level) => ({
    flex: 1,
    backgroundColor: level === 1 ? COLORS.PLUM400 : COLORS.PLUM500,
  })
}

```
**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |
| react-navigation               | 4.0.10
| react-navigation-stack         |  2.0.5
| react-navigation-tabs          | 2.6.2
| react-native                   | 0.61.5

**Comment by reimertz** [comment]
Hey @satya164 and thanks for responding!

The issue is not with the current animation but so more with the lack of a background color as seen in the first provided image. 

We set this issue but only on a a subset of devices; Android running OS Version 29, api level 10.
So I don't know if it should be closed since it is not related to animations.

**Comment by satya164** [comment]
There's a background color set by default. However you're using an outdated version of stack. So please open an issue with a repro if there's an issue in lastest version.
