### ISSUE TITLE
material-bottom-tabs does not support `lazy` option

### ISSUE THREAD

**Issue by kamui545** [react-navigation/react-navigation#8092]
**Current Behavior**

`material-bottom-tabs` does not have a `lazy` option to disable the lazy loading of screens: 
https://reactnavigation.org/docs/material-bottom-tab-navigator/#props

**Expected Behavior**

I think this option should be also available, as it is already available for the bottom-tab-navigator: https://reactnavigation.org/docs/bottom-tab-navigator/#lazy

I assumed `material-bottom-tabs` was based on top of `bottom-tab-navigator`, is there any reason this option was not added?

**How to reproduce**

Simply check the doc: https://reactnavigation.org/docs/material-bottom-tab-navigator/#props
Or install the package `npm install @react-navigation/material-bottom-tabs`:

```js
import { createMaterialBottomTabNavigator } from '@react-navigation/material-bottom-tabs';

const BottomTab = createMaterialBottomTabNavigator();

export default () => (
  <BottomTab.Navigator
     lazy={false} // <-- does not work / exist
  >
    <BottomTab.Screen />
  </BottomTab.Navigator>
)
```

**Your Environment**

| software                               | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 5.1.6
| @react-navigation/material-bottom-tabs | 5.1.9
| react-native-paper                     | 3.8.0

**Comment by kamui545** [comment]
@github-actions My bad, I put the version of the `@react-navigation/bottom-tabs` instead of  `@react-navigation/material-bottom-tabs`, I fixed it.

**Comment by raajnadar** [comment]
Bottom TabBar is based on this component https://callstack.github.io/react-native-paper/bottom-navigation.html

**Comment by satya164** [comment]
Please open feature requests regarding material bottom tabs in https://github.com/callstack/react-native-paper repo.

**Comment by tudiantuan** [comment]
how to remove lazy react-navigation-material-bottom-tabs version 2.1.5? I want to set lazy for tab needed.
