### ISSUE TITLE
useLinking prefix with `https://` doesnt work

### ISSUE THREAD

**Issue by AregShahbazian** [react-navigation/react-navigation#8093]
**Current Behavior**

I'm have an app called `testapp`. When I click on a link (in a browser, email, or in the app itself) that starts with `https://testapp.com`, I want the app to handle it instead of the browser.
Links starting with `testapp://` work as expected, but the `https://testapp.com` links open in a browser.

**Expected Behavior**

I would expect the app to open, instead of the browser.

**How to reproduce**

example app in [this](https://github.com/AregShahbazian/TestApp) repo

The first link in the Home screen works properly (using `testapp://`). The second one (using `https://testapp.com` opens a browser)

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | android
| @react-navigation/native       | 5.1.6
| react-native                   | 0.61.5
| expo                           | n/a
| node                           | v10.16.0
| npm or yarn                    | yarn v1.21.1

**Comment by zRelux** [comment]
This is not a bug I believe, but you have to tell ios and android how to handle the regular urls see https://docs.expo.io/versions/latest/workflow/linking/#universaldeep-links-without-a-custom-scheme

**Comment by satya164** [comment]
https://developer.android.com/training/app-links/deep-linking

**Comment by AregShahbazian** [comment]
> https://developer.android.com/training/app-links/deep-linking

Adding the extra `<intent-filter>` solved it. Thank you
