### ISSUE TITLE
Deep linking return null via notification when i kill the app

### ISSUE THREAD

**Issue by darbaoui** [react-navigation/react-navigation#8095]
**Current Behavior**

```javascript

// App.js

componentDidMount() {
  Linking.getInitialURL().then(url => {
      this.navigate(url);
  });
  Linking.addEventListener('url', this.handleOpenURL);
}

handleOpenURL = event => {
    this.navigate(event.url);
};

navigate = url => {
    const route = url.replace(/.*?:\/\//g, '');
    const route_id = route.match(/\/([^\/]+)\/?$/)[1];
    const routeName = route.split('/')[0];

    this.navigator &&
          this.navigator.dispatch(
            NavigationActions.navigate({
               routeName
               params: {
                 route_id,
               },
             }),
          );
}

```

i have 2 scenarios in **IOS**:

- if the app is already opened and it is in the background, send push notification from intercom with deep link, i receive it then i click on it the app opened and redirect me to the screen that i want.
- if i kill the app by swipping it, i send the same notifcation, if i click on it, that only open the app no redirection, **in this case if i use safari with my app url schema like `appname://....`, i can  open the app and navigate to the disired screen.**, only from push notification that not work.

**Expected Behavior**

- if i kill the app and receive notification with deep link action i can navigate to the desired screen.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS                  | 13.3.1
| react-navigation               | ^4.0.10
| react-navigation-stack         | ^1.10.3
| react-navigation-tabs          | ^2.5.6
| react-native-reanimated        | ^1.4.0
| react-native-gesture-handler   |  ^1.5.0
| react-native-screens           | ^2.0.0-alpha.11
| react-native                   | 0.61.4"
| node                           | v13.6.0
| yarn                    | 1.21.1

**Comment by darbaoui** [comment]
After upgrading to the latest versions of these packages the issue still exists .

**Comment by satya164** [comment]
If `Linking.addEventListener` gives you `null`, then it's a bug in `Linking` in React Native, not React Navigation.

**Comment by toanpv-2417** [comment]
i get same issue as you , did you solve it , please confirm with me in here , thank you <3
