### ISSUE TITLE
Custom headerLeft can not goBack on Android after pressed

### ISSUE THREAD

**Issue by JackClown** [react-navigation/react-navigation#8096]
**Current Behavior**
I customize the `headerLeft` with screenOptions on StackNavigator. It works well on IOS but not well on Android. The Navigator can not go back after the button pressed.

![screencast-Genymotion-2020-04-21_21 46 17 616](https://user-images.githubusercontent.com/9284369/79875610-77ad0580-841c-11ea-9db8-473ffa4bd5c8.gif)

**Expected Behavior**
The Navigator can go back.

**How to reproduce**

use the component with `headerLeft`:
```typescript
import React from 'react';
import { TouchableOpacity, Text } from 'react-native';

export default function HeaderBack(props: { onPress?: () => void }) {
  return (
    <TouchableOpacity onPress={props.onPress}>
      <Text>Back</Text>
    </TouchableOpacity>
  );
}

```

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |iOS
| @react-navigation/native       |5.1.6
| @react-navigation/stack        |5.2.11
| react-native-gesture-handler   |1.6.1
| react-native-safe-area-context |0.7.3
| react-native-screens           |2.4.0
| react-native                   |0.62.2
| expo                           |
| node                           |
| npm or yarn                    |

I notice that if I use HeaderLeftButton of @react-navigation/stack with headerLeft. It works well on Android.
And I find that if I change the callback of onPress like HeaderLeftButton. The problem can be solved.
```typescript
import React from 'react';
import { TouchableOpacity, Text } from 'react-native';

export default function HeaderBack(props: { onPress?: () => void }) {
  const { onPress } = props;

  const handlePress = () => {
    if (onPress) {
      requestAnimationFrame(onPress);
    }
  }

  return (
    <TouchableOpacity onPress={handlePress}>
      <Text>Back</Text>
    </TouchableOpacity>
  );
}
```

**Comment by satya164** [comment]
Closing since you didn't provide a repro.
