### ISSUE TITLE
Keyboard bug when going back a screen while text input is focused on Android.

### ISSUE THREAD

**Issue by chriscodes21** [react-navigation/react-navigation#8098]
I have a two screen project. One welcome screen, that navigates to a second screen that has two text inputs that are within a KeyboardAvoidingView. When I am on the second screen and focused on a text input (keyboard is open) and I press the react navigation header navigate back button, on initial tap the keyboard dismisses then it reopens then dismisses again and THEN navigates back to the first screen. This all happens very quickly, but it creates a very unpleasing keyboard jerk thats quite odd and not fluid.

On iOS it works as expected. When your press the headers navigate back button, the keyboard closes once and the transition to the previous screen happens seamlessly.

Here is a quick video showing the issue. May be hard to catch, it happens quickly.
[bugkeyboard.mov.zip](https://github.com/react-navigation/react-navigation/files/4512316/bugkeyboard.mov.zip)

**Comment by satya164** [comment]
Closing since you didn't provide any repro or didn't fill the issue template. We need a minimal repro to be able to debug issues. Feel free to open a new issue if you have a repro.

**Comment by mitsest** [comment]
Also experiencing this

**Comment by felire** [comment]
We should reopen this, I'm having the same issue and I don't know why. It's just happening if you interact with the app very faster

**Comment by Lester016** [comment]
I am having the same problem, Tried updating all the packages and still showing the same problem.
