### ISSUE TITLE
Android crash：use goBack from a screen with Webview

### ISSUE THREAD

**Issue by ceressteven** [react-navigation/react-navigation#8099]
When I return to the normal page from a page with Webview, got crash!
Environmental：
 "react-native": "0.62.2",
 "@react-navigation/stack": "^5.0.0",
    "react-native-webview": "^8.1.2",

code:
 <View style={{ flex: 1, backgroundColor: config.theme.backgroundColor }}>
      {/* header */}
      <components.Angle />

      <View style={{ flex: 1, backgroundColor: config.theme.backgroundColor }}>
        <components.CustomWebView
          handleMessage={handleMessage}
          uri={url}
        />
      </View>
    </View>

**Comment by ceressteven** [comment]
> 下列软件包的问题中提到的版本与npm上的最新版本不同：
> 
> * `@react-navigation/stack`（发现：`5.0.0`，最新的：`5.2.11`）
> 
> 升级到这些软件包的最新版本后，您可以验证问题是否仍然存在吗？
in yarn.lock
  "@react-navigation/stack@^5.0.0":
  version "5.2.11"
  resolved "https://registry.npm.taobao.org/@react-navigation/stack/download/@react-navigation/stack-5.2.11.tgz#3e8d5e64a7a46c9fdb672eed74c973c3073e8ca5"
  integrity sha1-Po1eZKekbJ/bZy7tdMlzwwc+jKU=
  dependencies:
    color "^3.1.2"
    react-native-iphone-x-helper "^1.2.1"

so My  react-navigation/stack version is 5.2.11

**Comment by ceressteven** [comment]
when i use reset or navigate,it's work well, but use popToTo app got crash too

**Comment by ceressteven** [comment]
supplement： 
use navigation.navigate({ key: last.key }) ,got crash too

**Comment by satya164** [comment]
Closing since you didn't follow the issue template.

**Comment by imimali** [comment]
Also encountered the same issue. In case you are using [react-native-screens](https://github.com/software-mansion/react-native-screens), (according to https://github.com/software-mansion/react-native-screens/issues/214 you can set ```androidHardwareAccelerationDisabled``` on the WebView.

**Comment by buffge** [comment]
the same problem

**Comment by franjorub** [comment]
> Also encountered the same issue. In case you are using [react-native-screens](https://github.com/software-mansion/react-native-screens), (according to [software-mansion/react-native-screens#214](https://github.com/software-mansion/react-native-screens/issues/214) you can set `androidHardwareAccelerationDisabled` on the WebView.

this solved my issue! also I have experiencing this with react-native-youtube-iframe maybe they could allow this prop too

**Comment by jacobarvidsson** [comment]
Warning for people using the web view for YouTube. The YouTube video won't show with androidHardwareAccelerationDisabled set to true, only play the sound. I solved the original problem by just showing / hiding the web view when the screen was in focus.

```javascript
import React from "react";
import { WebView } from "react-native-webview";
import { useIsFocused } from "@react-navigation/native";

const Screen = () => {
  const isFocused = useIsFocused();

  if (!isFocused) {
    return null;
  }
  return <WebView />
}

```

**Comment by hfalk** [comment]
Can we reopen this issue? Though both proposed solution(hacks) above works, I feel this is a bug that should be investigated further

**Comment by msmtr14** [comment]
> Also encountered the same issue. In case you are using [react-native-screens](https://github.com/software-mansion/react-native-screens), (according to [software-mansion/react-native-screens#214](https://github.com/software-mansion/react-native-screens/issues/214) you can set `androidHardwareAccelerationDisabled` on the WebView.

Thanks @imimali , this solved my issue.

**Comment by JANGFREEMAN** [comment]
> androidHardwareAccelerationDisabled

it is work !

**Comment by buffaloDeveloper** [comment]
I am seeing the same issue when using "react-native-web-webview".  The app will crash on goBack (100% of the time) as well as navigation.navigate (most of the time) to a page using a webview.

**Comment by jgudo** [comment]
> 

Have you found a solution? I've found a workaround like setting ```{ animationEnabled: false }``` on my ```Stack.Screen``` options where my WebView is present. However, upon navigating to to > 2-level navigation then going back to the screen where  WebView exist, the app crashes.

**Comment by jgudo** [comment]
> I am seeing the same issue when using "react-native-web-webview". The app will crash on goBack (100% of the time) as well as navigation.navigate (most of the time) to a page using a webview.

Same issue. Have you found a solution? I've found a workaround like setting { animationEnabled: false } on my Stack.Screen options where my WebView is present. However, upon navigating to to > 2-level navigation then going back to the screen where WebView exist, the app crashes.

**Comment by jgudo** [comment]
Finally solved it with the opacity hack 
Try setting the ```opacity``` style of the ```WebView``` below 1 
```<WebView style={{ opacity: 0.99 }} ... />```

**Comment by Harikrishnan-AV** [comment]
> Finally solved it with the opacity hack Try setting the `opacity` style of the `WebView` below 1 `<WebView style={{ opacity: 0.99 }} ... />`

yes its workig now , but how !!
