### ISSUE TITLE
Using Redux & Firebase Authentication 

### ISSUE THREAD

**Issue by Bilal-Abdeen** [react-navigation/react-navigation#8100]
I am trying to use **React-Navigation Version 5** (not Ver 4) to switch from the authentication screens/stack to the non-authentication screens/stack when the user logs in. A simple example is well demonstrated in the documentation. 

However, the documentation does not provide details for using **Redux** and **Google Firebase authentication.** After a successful login to Firebase, I am getting the following warning message. 

```Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.```

I think that the cause of this warning message is that the call to Redux action (action creator) causes re-rendering of the authentication screen, while the navigation code has already unmounted this screen! **How can I update the Redux's store after the authentication screen has been unmounted?** 

Navigation Code: 
```javascript
...
// If user is logged in -> display the app/main stack
if (props.loggedIn) 
{
	const MyTabs = createBottomTabNavigator();
	return (
		<NavigationContainer>
			<MyTabs.Navigator initialRouteName="UserTypeScreen">
			   <MyTabs.Screen name="UserTypeScreen" component={UserTypeScreen}  />
			   <MyTabs.Screen name="PermissionsScreen" component={PermissionsScreen} />
			</MyTabs.Navigator>
		</NavigationContainer>
	); 
}
// If user is NOT logged in -> display the auth stack
else {
	const AuthStack = createStackNavigator();
	return (
		<NavigationContainer>
			<AuthStack.Navigator>
			   <AuthStack.Screen name="AuthScreen" component={AuthScreen} />
			   <AuthStack.Screen name="AuthLinkScreen" component={AuthLinkScreen} />
			</AuthStack.Navigator>
		</NavigationContainer>
	); 
}
...
```

Authentication screen: 
```javascript
...
useEffect( () => {
	const unSubscribe = firebase.auth().onAuthStateChanged( (user) => {
		if (user) {
			const idToken = firebase.auth().currentUser.getIdToken(); 
			const credential = firebase.auth.PhoneAuthProvider.credential(idToken); 

			// The following statement causes a warning message, 
			//      because it causes re-rendering of an unmounted screen
			props.acLoginUserSuccess(user, credential);	
		} 
	}); 

	return () => {
		unSubscribe();
	};
}, []); 
...
```

Redux Action Creator: 
```javascript
...
export const acLoginUserSuccess = (user, credential) => {
	return {
    		type: LOGIN_USER_SUCCESS,
		payload: { user: user, credential: credential }
	};
};
...
```
**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Android
| @react-navigation/native       | 5.1.6
| react-native                   | 0.62.2
| expo                           | N/A 
| node                           | 6.13.6
| npm or yarn                    | npm

**Comment by Bilal-Abdeen** [comment]
I have updated the library to the latest version and tested the app again. The problem is still there.

**Comment by abhikulshrestha22** [comment]
@Bilal-Abdeen Did you find any solution for the above scenerio?

**Comment by Bilal-Abdeen** [comment]
No, mate. I did not find a solution. In addition to asking here, I asked on Stackoverflow. Check the following. 
https://stackoverflow.com/questions/61316213/using-react-navigation-v5-with-redux-firebase-authentication

**Comment by abhikulshrestha22** [comment]
@Bilal-Abdeen , okay, I upvoted that and added a bounty. Let's see what we get there

**Comment by Bilal-Abdeen** [comment]
If no one has an answer to this issue, I think it should be re-categorised as a "bug" and NOT simply a "Question".  I suppose this increases the urgency of the issue. 

I think a lack of support for Redux and Firebase authentication is a major issue. I wonder if the old "switching" between Auth & non-Auth stacks, which was used in v4, is a more robust approach than mounting/unmounting the stacks, which is used in v5!

**Comment by raajnadar** [comment]
IDK why you need redux when you can easily work with context API and you will find may examples.

> How can I update the Redux's store after the authentication screen has been unmounted?

How can you categorize it as bug when you asked a how to question.

**Comment by Bilal-Abdeen** [comment]
@raajnadar Thanks for your reply. 

I don't think this is the right forum to compare Context API with Redux. Redux has become widely used and proven effective for quite some time now. Moreover, there are many applications, which have been using it (mine included). It is a lot of work to replace Redux with Context. 

React-Navigation is widely used too. It is highly appreciated if integration with Redux continues with every version of React-Navigation. 

If it has been decided to stop integration with Redux, I think this has to be made very clear in the documentation. 

Thanks and Regards.

**Comment by raajnadar** [comment]
Redux maybe the industry standard but react navigation has nothing to do with it.

> It is a lot of work to replace Redux with Context

Context is easier to setup you need a provider & consumer you can use it with useReducer to completely replace it with Redux or Mobx. Context API is a copy of Redux.

Context API is made to replace other Global state management libraries.

You can read this blog post https://dev.to/ayushmanbthakur/redux-vs-context-api-3182

_Rest is your choice_

**Comment by abhikulshrestha22** [comment]
@raajnadar Context is a way to do it. But doesn't mean it should not work with Redux
