### ISSUE TITLE
Open modal on deeplink

### ISSUE THREAD

**Issue by Yallan** [react-navigation/react-navigation#8103]
I would like to open a modal when a deeplink is fired and keep initial stack behind.

**Current Behavior**

It's works when app is in foreground or background.
But when app is inactive and deeplink fired, only modal is present. I can't close modal and show main stack.

**Expected Behavior**

Keep the main stack behind the modal

**How to reproduce**

My deeplink is app_scheme://purchases/purchase/new/:purchaseId

```
function App() {
  const ref = useRef();
  const logged = useSelector((state) => state.user.logged);

  const { getInitialState } = useLinking(ref, {
    prefixes: ['app_scheme://'],
    config: {
      AddStack: {
        screens: {
          TakePicture: {
            path: 'purchases/purchase/new/:purchaseId',
            parse: {
              purchaseId: Number,
            },
          },
        },
      },
    },
  });
  const [isReady, setIsReady] = useState(false);
  const [initialState, setInitialState] = useState();

  React.useEffect(() => {
    Promise.race([
      getInitialState(),
      new Promise((resolve) =>
        // Timeout in 150ms if `getInitialState` doesn't resolve
        // Workaround for https://github.com/facebook/react-native/issues/25675
        setTimeout(resolve, 150),
      ),
    ])
      .catch((e) => {
        console.error(e);
      })
      .then((state) => {
        if (state !== undefined) {
          setInitialState(state);
        }

        setIsReady(true);
      });
  }, [getInitialState]);

  if (!isReady) {
    return null;
  }

  return (
      <NavigationContainer initialState={initialState} ref={ref}>
        {logged ? <RootStack /> : <AuthStack />}
      </NavigationContainer>
  );
}
```

```
function RootStack() {
  return (
    <Stack.Navigator mode="modal" initialRouteName="MainStack">
      <Stack.Screen
        name="MainStack"
        component={MainStack}
        options={{ headerShown: false }}
      />
      <Stack.Screen
        name="AddStack"
        component={AddStack}
        options={{
          headerShown: false,
        }}
      />
      ...
    </Stack.Navigator>
  );
}
```

```
function MainStack() {
  return (
    <Stack.Navigator initialRouteName="Purchases">
      <Stack.Screen
        name="Purchases"
        component={Purchases}
      />
      <Stack.Screen
        name="PurchaseDetail"
        component={PurchaseDetail}
      />
      ...
    </Stack.Navigator>
  );
}
```

```
export default function AddStack() {
  return (
    <Stack.Navigator initialRouteName="TakePicture">
      <Stack.Screen
        name="TakePicture"
        component={TakePicture}
      />
      ...
    </Stack.Navigator>
  );
}
```

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS                 | 13.4.1|
| @react-navigation/native       |5.1.6|
| @react-navigation/stack        |5.2.11|
| react-native-gesture-handler   |1.6.1|
| react-native-safe-area-context |0.7.3|
| react-native-screens           |2.5.0|
| react-native                   |0.62.2|

**Comment by Yallan** [comment]
Upgraded to 5.2.12 but i had the same issue

**Comment by benjipott** [comment]
same for me @Yallan, someone have a solution ?

**Comment by satya164** [comment]
https://reactnavigation.org/docs/configuring-links#rendering-an-initial-route

**Comment by benjipott** [comment]
Sorry @satya164 but your solution is not related to this bug 🐜.

Deeplink doesn’t open a modal but render modal on root

**Comment by emroot** [comment]
@benjipott can you share your code? I just fixed mine, @satya164 is right you can use `initialRouteName`, just gotta set up your linking object properly.

**Comment by benjipott** [comment]
Hi, I simply return all navigation instead of waiting state from the
exemple and all work fine for me.

Le sam. 23 mai 2020 à 20:12, Emre Ozdemir <notifications@github.com> a
écrit :

**Comment by Yallan** [comment]
@benjipott Remove this code not open modal on app start. What is your config ?

@emroot & @satya164 I try to add **initialRouteName: 'MainStack',** in my config but it's not working. **AddStack** render first and **MainStack** become the modal.

**Comment by Yallan** [comment]
I have create a Snack : https://snack.expo.io/@allanmry/ca293e

**Comment by OscarYuen** [comment]
I meet the same problem as yours. Did you fix that?

**Comment by berkaey** [comment]
Same Here!

**Comment by CptFabulouso** [comment]
I had similar issue and the `initialRouteName` prop in config fixed it, following my code, yours should end up like this:
```
config: {
   initialRouteName: 'MainStack', // <-- added
   screens: { // <-- wrapped in screens
      AddStack: {
        screens: {
          TakePicture: {
            path: 'purchases/purchase/new/:purchaseId',
            parse: {
              purchaseId: Number,
            },
          },
        },
      },
    },
 },
```
Maybe you've tried it this way, it's hard to know from the comments here, please post entire configs..

**Comment by yasemincidem** [comment]
Is there any solution for that issue ? I faced the similar issue. When the app is in background, the modal is rendered. When the app is terminated, screen is shown instead of a modal.

**Comment by tylercote** [comment]
@yasemincidem @OscarYuen @berkaey Did any of you ever get this working? I am seeing the same problem, and none of the above fixes have worked for me.

**Comment by MehediH** [comment]
@tylercote This worked for me:

```
const config = {
  initialRouteName: "Tabs",
  screens: {
    initialRouteName: "Tabs", // <--- main stack
    Tabs: {
      screens: {
        Home: "*", // <--- first/primary screen in the stack
      },
    },
    Comment: "comment/:commentId", // <-- modal screen
  },
};
```

**Comment by jforaker** [comment]
> @tylercote This worked for me:
> 
> ```
> const config = {
>   initialRouteName: "Tabs",
>   screens: {
>     initialRouteName: "Tabs", // <--- main stack
>     Tabs: {
>       screens: {
>         Home: "*", // <--- first/primary screen in the stack
>       },
>     },
>     Comment: "comment/:commentId", // <-- modal screen
>   },
> };
> ```

Saved me, thanks @MehediH!

Here's my config in case anyone finds it useful:

```
  config: {
    initialRouteName: 'TabScreens',
    screens: {
      initialRouteName: 'TabScreens',  // <-- main tabnavigation stack
      TabScreens: {
        screens: {
          Dashboard: 'dashboard',  // <-- default screen on the tabs
        },
      },
      Study: {  // <-- modal stack that sits at the same level as the tab screens
        screens: {
          StudyScreen: {.  // <-- single modal screen inside the Study stack -- this is where the deep link opens 
            path: 'study/:Id?,
          },
        },
      },
      AuthStack: {   // <-- fallback if not logged in 
        screens: {
          Splash: 'splash',
        },
      },
      NoMatch: '*',
    },
  },
```
