### ISSUE TITLE
bundling failed: SyntaxError

### ISSUE THREAD

**Issue by longhuynhthanh** [react-navigation/react-navigation#8104]
bundling failed: SyntaxError: \node_modules\@react-navigation\routers\src\index.tsx: Unexpected token (9:12)

   7 | export { default as StackRouter, StackActions } from './StackRouter';
   8 |
>  9 | export type {
     |             ^
  10 |   StackActionHelpers,
  11 |   StackActionType,
  12 |   StackRouterOptions,

**Comment by raajnadar** [comment]
Solution is here https://github.com/react-navigation/react-navigation/issues/7981#issuecomment-611377210
