### ISSUE TITLE
navigationOptions only apply from 2nd render of the screen.

### ISSUE THREAD

**Issue by simonholzapfel** [react-navigation/react-navigation#8105]
**Current Behavior**
`const MainMenu = props => {

    MainMenu.navigationOptions = {
      headerRight: () => <HeaderButtons HeaderButtonComponent={HeaderButton}>
        <Item 
          title="Search"
          iconName="md-search"
          onPress={() => {
            props.navigation.navigate('Search');
          }}
          />
          <Item
          title="Profile"
          iconName="md-person"
          onPress={() => {
            props.navigation.push('UserProfile')
          }}
          />
    </HeaderButtons>}

    return (
        <View>
          <Text>Example</Text>
        </View>
      );
}`

These navigation options only apply after the 2nd render of the containing component.

**Expected Behavior**
They should be applied on 1st render.

**How to reproduce**

Use the same code as I did

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| Android               10  |
| @react-navigation/native   4.3.3    |
| @react-navigation/stack     2.3.7   |
| react-native-gesture-handler 1.6.0  |
| react-native-safe-area-context 0.7.3 |
| react-native-screens         2.2.0  |
| react-native                 https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz  |
| expo                     37.0.0      |
| node                     12.14.0      |
| yarn        1.22.0            |

**Comment by satya164** [comment]
You cannot change `navigationOptions` during render.
