### ISSUE TITLE
Error after installing @react-navigation/bottom-tabs

### ISSUE THREAD

**Issue by GodwinEbikwo** [react-navigation/react-navigation#8106]
**Current Behavior**
SyntaxError: /Users/godwin/Desktop/another_blog/node_modules/@react-navigation/bottom-tabs/src/index.ts
13 |  * Types
  14 |  */
> 15 | export type {
     |             ^
  16 |   BottomTabNavigationOptions,
  17 |   BottomTabNavigationProp,
  18 |   BottomTabBarProps,

**Expected Behavior**

just render the bottom-navigator without errors

**How to reproduce**

yarn install @react-native/bottom-tabs
- Before reporting an issue, make sure you are on latest version of the package.

**Your Environment**

| software                      | version |
| ----------------------------- | ------- |
| iOS or Android                |
| @react-navigation/native      |
| @react-navigation/bottom-tabs |
| react-native-screens          |
| react-native                  |
| expo                          |
| node                          |
| npm or yarn                   |

**Comment by raajnadar** [comment]
Solution is here https://github.com/react-navigation/react-navigation/issues/7981#issuecomment-611377210
