### ISSUE TITLE
Goback to specific screen，4.x and 5.x behave differently。

### ISSUE THREAD

**Issue by funyaliga** [react-navigation/react-navigation#8108]
**Current Behavior**

in 4.x
SCREENA:  navigation.navigate({ routeName:'SCREENB', key:'SCREEN_KEY_A' });
SCREENB:  navigation.navigate({ routeName:'SCREENC', key:'SCREEN_KEY_A' });
SCREENC:  navigation.navigate({ routeName:'SCREEND', key:'SCREEN_KEY_A' });
SCREEND:  navigation.goBack('SCREEN_KEY_A')

It will go back to SCREENA

----

but in 5.x
SCREENA:  navigation.navigate({ name:'SCREENB', key:'SCREEN_KEY_A' });
SCREENB:  navigation.navigate({ name:'SCREENC', key:'SCREEN_KEY_A' });
SCREENC:  navigation.navigate({ name:'SCREEND', key:'SCREEN_KEY_A' });
SCREEND:  navigation.navigate('SCREEN_KEY_A');

It will go to SCREENB, not SCREENA

**Expected Behavior**

I want 5.x to behave the same as 4.x

**How to reproduce**

4.x:  https://snack.expo.io/@funreading/test-in-4

5.x: https://snack.expo.io/@funreading/test-in-5

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS                  |
| @react-navigation/native       | ^5.1.6 |
| @react-navigation/stack        | ^5.2.11 |
| react-native-gesture-handler   | ^1.6.1 |
| react-native-safe-area-context | ^0.7.3 |
| react-native-screens           | ^2.5.0 |
| react-native                   | "0.61.5" |
| expo                           |
| node                           | v10.15.0 |
| yarn                    | 1.3.2 |

**Comment by satya164** [comment]
In your code snippet, you have specified the same key for all screens, which isn't valid. In your snack for v4, you're using `goBack`, in your snack for v5, you're using `navigate`. They are obviously not the same.

You have specified the key `SCREEN_KEY_A` for `screenB`, and then you're navigating to the key `SCREEN_KEY_A` which refers to `screenB`, seems like it's working as expected.

If you want to got to `screenA`, just navigate to `screenA`? Not sure why are you even using keys here.

**Comment by funyaliga** [comment]
> In your code snippet, you have specified the same key for all screens, which isn't valid. In your snack for v4, you're using `goBack`, in your snack for v5, you're using `navigate`. They are obviously not the same.
> 
> You have specified the key `SCREEN_KEY_A` for `screenB`, and then you're navigating to the key `SCREEN_KEY_A` which refers to `screenB`, seems like it's working as expected.
> 
> If you want to got to `screenA`, just navigate to `screenA`? Not sure why are you even using keys here.

Because in the 4.x documentation, you are using goBack
https://reactnavigation.org/docs/4.x/navigation-prop/#going-back-from-a-specific-screen-with-goback

But in the 5.x document, you are using navigate
https://reactnavigation.org/docs/navigation-prop/#going-back-from-a-specific-screen

In 5.x, I tried to use goBack (key) or goBack ({key: key}). To no avail.

My scenario is that there is a long process A-> B-> C-> D. After D finishes processing the job and returns to A, but page A is uncertain, because there are multiple pages and entrances into B, so I You cannot use navigate to the specified page.

In 4.x, I used goBack (key) to complete this scene.
