### ISSUE TITLE
Drawer position "right" by code break drawer

### ISSUE THREAD

**Issue by sagivStekolshik** [react-navigation/react-navigation#8114]
**Current Behaviour**

changing by code the direction of the drawer from left to right(other way is fine), breaks the drawer and only display overlay, restarting the app will resolve issue, providing drawer position was persisted.

IOS and Android

**Expected Behaviour**

Changing drawer position will not break drawer 

**How to reproduce**

Re-create bug in [this repo](https://github.com/sagivStekolshik/react-navigation-drawer-ltr-bug)

just press the button and only an overlay will appear

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Both|
| @react-navigation/native       |5.1.6|
| @react-navigation/drawer       |5.5.0|
| react-native-reanimated        |1.8.0|
| react-native-gesture-handler   | 1.6.1|
| react-native-safe-area-context |0.7.3|
| react-native-screens           |2.6.0|
| react-native                   |0.62.2|
| node                           | 13.13.0|
| npm or yarn                    | yarn|

**Comment by raajnadar** [comment]
Fixed in this PR https://github.com/react-navigation/react-navigation/pull/8357

Upgrade to latest version to get the issue fixed.
