### ISSUE TITLE
Unable to resolve module `shortid` from `node_modules/@react-navigation/routers/src/StackRouter.tsx`: shortid could not be found within the project

### ISSUE THREAD

**Issue by AdityaKotamraju** [react-navigation/react-navigation#8121]
**Current Behavior**
![Simulator Screen Shot - iPhone 11 - 2020-04-25 at 19 43 49](https://user-images.githubusercontent.com/4414368/80282121-4f2f4f00-872d-11ea-9ec6-48e733189a9e.png)

I see something post this commit made a difference [react-navigation/react-navigation@9bb5cfd](https://github.com/react-navigation/react-navigation/commit/9bb5cfded3f805797cf759386bb3bfe34d2e01e7)

**Expected Behavior**
Application should run installing all the modules and its dependencies.

**How to reproduce**
Just create a new project and install react-navigation and its dependencies. Later try installing @react-navigation/stack and you can see the error.

**Your Environment**
"@react-native-community/art": "^1.2.0",
    "@react-native-community/async-storage": "^1.8.1",
    "@react-native-community/masked-view": "^0.1.7",
    "@react-native-community/netinfo": "^5.5.1",
    "@react-native-community/slider": "^2.0.9",
    "@react-navigation/drawer": "^5.1.1",
    "@react-navigation/material-bottom-tabs": "^5.1.7",
    "@react-navigation/material-top-tabs": "^5.1.9",
    "@react-navigation/native": "^5.0.9",
    "@react-navigation/stack": "^5.1.1",
    "axios": "^0.19.2",
    "eslint-import-resolver-babel-module": "^5.1.2",
    "jwt-decode": "^2.2.0",
    "moment": "^2.24.0",
    "prop-types": "^15.7.2",
    "react": "16.9.0",
    "react-native": "0.61.5",
    "react-native-gesture-handler": "^1.6.0",
    "react-native-modalbox": "^2.0.0",
    "react-native-paper": "^3.6.0",
    "react-native-pie": "^1.1.2",
    "react-native-reanimated": "^1.7.0",
    "react-native-safe-area-context": "^0.7.3",
    "react-native-screens": "^2.2.0",
    "react-native-tab-view": "^2.14.0",
    "react-native-vector-icons": "^6.6.0",
    "react-native-webview": "9.1.0",
    "react-redux": "^7.2.0",
    "redux": "^4.0.5",
    "redux-thunk": "^2.3.0"

Can we quickly look in to this as StackNavigator is the default used by most of them and I am already in a tight schedule for a demo.

**Comment by AdityaKotamraju** [comment]
Yes its the issue still exists in @react-navigation/stack@5.2.13 as well. :(

**Comment by raajnadar** [comment]
Did you try `expo start -c` or `npx react-native run-android --reset-cache`?

**Comment by AdityaKotamraju** [comment]
Yes I did, but unfortunately no use.!

**Comment by AdityaKotamraju** [comment]
Looks silly but worked after cleaning the cache many times and restarting my MacBook. All is well now.
