### ISSUE TITLE
Beginner - React-Navigation V3, V4. grammar error (createStackNavigator)

### ISSUE THREAD

**Issue by jaemanhailey** [react-navigation/react-navigation#8122]
I'm an extremely beginner of react-native.
I have been learning this following a book and this chapter is learning how to use 'navigation' and 'App resource' based on react-navigation V3.

But I installed react-navigation V4 and found the library "createStackNavigator" is separated from "react-navigation".
and it has an error as below sentences. 
 
const MovieNavigator = createStackNavigator ({
     MovieHome, 
     MovieDetail,
});

at here.   no code actions are available.
import MovieHome from '~/Screens/MovieHome';

I really really want to know how to solve it.
Thank you for instance.

====================================
below is my "Navigator.ts".

import {
    createSwitchNavigator,
    createAppContainer,
     }
    from 'react-navigation';

import {
         createStackNavigator,
       }
       from 'react-navigation-stack';

import CheckLogin from '~/Screens/CheckLogin';
import Login from '~/Screens/Login';
import MovieHome from '~/Screens/MovieHome';
import MovieDetail from '~/Screens/MovieDetail';

const LoginNavigator = createStackNavigator ({
    Login,
});

const MovieNavigator = createStackNavigator ({
        MovieHome
        MovieDetail,
});

....

===============
here is my MovieHome. index.tsx

import React, { useEffect } from 'react';
import AsyncStorage from '@react-native-community/async-storage';
import { NavigationScreenProp, NavigationState} from 'react-navigation';
import Styled from 'styled-components/native';

......

interface Props {
    navigation: NavigationScreenProp<NavigationState>;
}

const MovieHome = ({ navigation }: Props ) => {
    const _logout = () => {
        AsyncStorage.removeItem('key');
        navigation.navigate('LoginNavigator');
    };

......

**Comment by raajnadar** [comment]
Follow the issue temple and don't paste the full code instead add a repo or snack demo.
