### ISSUE TITLE
iPhone notch breaks view

### ISSUE THREAD

**Issue by Emetrop** [react-navigation/react-navigation#8128]
On iPhones with notch in the bottom of screen is space between content and tabs because `SafeAreaView` has additional `paddingBottom`. It's broken for `material-bottom-tabs` and `bottom-tabs` too.

I created this repo with testing example https://github.com/Emetrop/tabs-test

And here is demonstrating code which breaks it
```
function Screen() {
  return (
    // setting up paddingBottom = 0 fix this problem
    // <SafeAreaView style={{ flex: 1, backgroundColor: 'blue', paddingBottom: 0 }}>
    <SafeAreaView style={{ flex: 1, backgroundColor: 'blue' }}>
      <View style={{ flex: 1, backgroundColor: 'lightgreen' }}>
        <Text>Some content</Text>
      </View>
    </SafeAreaView>
  );
}

const Tab = createBottomTabNavigator();
// broken too
// const Tab = createMaterialBottomTabNavigator();

export default function App() {
  return (
    <SafeAreaProvider>
      <NavigationContainer>
        <Tab.Navigator barStyle={{ backgroundColor: 'gold' }}>
          <Tab.Screen name="Swipe" component={Screen} />
        </Tab.Navigator>
      </NavigationContainer>
    </SafeAreaProvider>
  );
}
```

![iphone11](https://user-images.githubusercontent.com/7429956/80294248-d389ce00-873d-11ea-9acb-048ed0b4a669.png)

**Comment by phungdaihiep79** [comment]
i have same problem :((

**Comment by phungdaihiep79** [comment]
I was facing the same problem in v5. Fixed by negating bottomInset with bottomPadding for screens with BottomBar.
https://github.com/react-navigation/react-navigation/issues/5714#issuecomment-630607484

**Comment by satya164** [comment]
You can customize the `edges` prop to not include bottom inset https://github.com/th3rdwave/react-native-safe-area-context#edges
