### ISSUE TITLE
Feature request: headerContent option

### ISSUE THREAD

**Issue by finom** [react-navigation/react-navigation#8129]
The goal I'm trying to achieve is to completely override logic of one of my stack navigation header which is on a home screen. Since my [previous proposal](https://github.com/react-navigation/react-navigation/issues/8062) wasn't a successful attempt to get this as part of the official API, I hope this feature request is going to be much easier to implement and more convenient for the goals which react-navigation is achieving.

Currently if I want to completely customise a header I need to use a third-party library or reverse-engineer react-navigation to get the same look (sizing, safe area views, colours, shadows etc). That's not a straightforward way to add some custom features like a search text input. So I propose (but actually ask for!) an option called `headerContent` which is going to be rendered as the only child of the header overriding `headerTitle`, `headerLeft` and `headerRight`.

**Comment by borgogelli** [comment]
Why in previous versions it's possible to completely customize the header (using a custom component) and in the latest version not ?

**Comment by satya164** [comment]
If you want header's wrapper styles then import the `HeaderBackground` component and wrap your custom header with it. No need for a separate prop.
