### ISSUE TITLE
Navigation.navigator() typing should also allow string variable for screen name in addition to the defined literals

### ISSUE THREAD

**Issue by artsra** [react-navigation/react-navigation#8130]
- What code are you running and what is happening?

`navigation.navigate(route.params.returnScreen, { name: value })`

Getting: `Type 'string' is not assignable to type '"PickOpcode" | "HomeStack" | "Root"`. I'm a ts beginner but I think the type declaration should add `| string` somewhere.

**Expected Behavior**

Specifying a variable should be allowed.

**How to reproduce**

I think the code above is obvious

**Your Environment**

Latest version 5

**Comment by satya164** [comment]
You need to make type of your `returnScreen` more specific instead of using `string`. `"PickOpcode" | "HomeStack" | "Root" | string` basically means `string` and will lose all the type-checking.
