### ISSUE TITLE
Drawer Navigator back button returns to parent Stack Navigator to UnAuthenticated views

### ISSUE THREAD

**Issue by ablankenship10** [react-navigation/react-navigation#8132]
**Current Behavior**

When using a Stack Navigator leading to a nested Drawer Navigator after authentication, pressing the back button will attempt to return the user back to the Login views in the Stack Navigator, rather than remaining in the Drawer Navigator or closing the app.

**Expected Behavior**

After Logging in and being directed to the Authenticated section of the app, pressing the back button should no longer return to the Login views located in a parent Navigator, it should stay on the initialRoute or close the app. Reading around seems to suggest using `navigation.reset()` in various ways but this has not worked for me and also feels very messy screwing around with internal state of things to me. Is there a way I can simply define "Do not go further back than this point/exit app on back button"?

**How to reproduce**

``` javascript
export default function Router() {
  const { Navigator, Screen } = createStackNavigator();

  const screenOptions = { headerShown: false, cardStyle: styles.container };

  return (
    <SafeAreaProvider>
      <NavigationContainer>
        <Navigator initialRouteName='LoginSignup'>
          <Screen name='LoginSignup' component={LoginSignup} options={screenOptions} />
          <Screen name='Authenticated' component={Authenticated} options={screenOptions} />
        </Navigator>
      </NavigationContainer>
    </SafeAreaProvider>
  );
}

function Authenticated() {
  const { Navigator, Screen } = createDrawerNavigator();

  const screenOptions = { cardStyle: styles.container };

  return (
    <Navigator
      backBehavior='initialRoute'
      initialRouteName='Dashboard'
      drawerContent={(props) => <DrawerContent {...props} />}
    >
      <Screen name='Dashboard' component={Dashboard} options={screenOptions} />
      <Screen name='LastMonth' component={LastMonth} options={screenOptions} />
      <Screen name='Contact' component={Contact} options={screenOptions} />
      <Screen name='Accounts' component={Accounts} options={screenOptions} />
      <Screen name='ConnectPlaid' component={ConnectPlaid} options={screenOptions} />
    </Navigator>
  );
}
```

From LoginSignup, user logs in and calls navigation.navigate('Authenticated') which directs user to the `initialRoute` Dashboard. Once there, the user should not be able to press the back button to return the `LoginSignup` route.

**Your Environment**

"@react-navigation/drawer": "^5.5.0"
"@react-navigation/native": "^5.1.6"
"@react-navigation/stack": "^5.2.13"
"react-native-gesture-handler": "~1.6.0"
"react-native-safe-area-context": "0.7.3"
"react": "~16.9.0"
"react-native": "https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz"
"expo": "~37.0.3"
"node": 12.16.1
"npm": 6.13.4

**Comment by ablankenship10** [comment]
Confirmed that updating to the latest packages does not resolve the issue

**Comment by ablankenship10** [comment]
Found a solution thats to discord user Samip, used the BackHandler functionality to prevent unwanted redirecting:

```javascript
BackHandler.addEventListener('hardwareBackPress', () => {
  if(navigation.isFocused()){
    BackHandler.exitApp();
    return true;
  }
  return false;
});

```

**Comment by raajnadar** [comment]
It seems like you solved the issue so I am closing it!
