### ISSUE TITLE
useIsFocused in Stack Screen options

### ISSUE THREAD

**Issue by KaitoCode** [react-navigation/react-navigation#8134]
**Current Behavior**

Hey guys,
i try to toogle my StatusBar based on the selected Screen. So i had the Idea to use the hook "useIsFocused" in every Header. It works for my first Layer of Stack's but when i try to click through i get these error: 

![Screenshot_20200427-114221](https://user-images.githubusercontent.com/14308618/80358550-e3f49280-887c-11ea-8a7b-42885f1930eb.png)

**Expected Behavior**

The only thing should happen is a toggle or 'style' change for my StatusBar.

**How to reproduce**

It is easy to reproduce, just hit the "Favorites"-Button in my Snack example.
Then the Error should be displayed. 

When you just switch the Tab's you will see that is working for this Screens like a charm.

https://snack.expo.io/@collinsaddo/react-navigation-useisfocused

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                |both|
| @react-navigation/native       |5.1.6|
| @react-navigation/stack        |5.2.13|
| @react-navigation/bottom-tabs        |5.2.7|
| react-native                   |0.61.5|

Maybe it is also the wrong way to use this hook but for my "Bottom-Tabs" it works perfectly.

**Comment by KaitoCode** [comment]
Yes!

**Comment by satya164** [comment]
Hooks can only be used in components https://reactjs.org/docs/hooks-rules.html#only-call-hooks-from-react-functions
