### ISSUE TITLE
Already rendered components remounting on navigation from side drawer when we use CommonAction.reset.

### ISSUE THREAD

**Issue by getumangon** [react-navigation/react-navigation#8136]
**Current Behavior**

- I have the following structure in project: 

    - Drawer Navigator
          - Screen 1
          - Screen 2
          - Screen 3

With following method I am navigating to screens: 

` this.props.navigation.dispatch(
                CommonActions.reset({
                    routes: [
                        { name: key }
                    ]
                })
            )
`

- Using CommonActions.reset() I am navigating to screen 2 and it is re-rendering the screen 1 in background.

**Expected Behavior**

- When we do reset in drawer navigator it should not re-render the previously rendered screens.

**How to reproduce**

- Create navigation drawer with 3 screens. 
- Use CommonActions.reset() for navigation.
- For example if we are navigating screen-1 to screen-2 then screen-1 componentDidMount() is calling along with screen-2 componentDidMount().

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Both |
| @react-navigation/native       | 5.1.7 |
| @react-navigation/drawer       | 5.5.1 |
| react-native-reanimated        | 1.8.0 |
| react-native-gesture-handler   | 1.6.1 |
| react-native-safe-area-context | 0.7.3 |
| react-native-screens           | 2.7.0 |
| react-native                   | 0.62.2 |
| node                           | 12.11.1 |
| npm or yarn                    | npm |

**Comment by satya164** [comment]
Please read the docs https://reactnavigation.org/docs/navigation-actions#reset

**Comment by Bardiamist** [comment]
@satya164 I have Stack navigator. That have Tab navigator. Every tab have self stack navigator.

If I want to preserve only first screen of second navigator and reset to first.

```
(secondNavigationState) => ({
          routes: [{
            name: RouteName.MainTabNavigator,
            state: {
              routes: [{
                name: RouteName.First,
                state: {
                  routes: [
                    { name: RouteName.A },
                    { name: RouteName.B },
                  ],
                  index: 1,
                },
              }, {
                name: RouteName.Second,
                state: {
                  ...secondNavigationState,
                  routes: [secondNavigationState.routes[0]],
                  index: 0,
                },
              }],
              index: 0,
            },
          }],
          index: 0,
        })
```

That code will not preserve first screen of second Navigator.
