### ISSUE TITLE
Question: Is it possible to attach the same screen to multiple, different (kinds of) Navigators?

### ISSUE THREAD

**Issue by artsra** [react-navigation/react-navigation#8139]
When nesting navigators for writing an app for both web/native, I want to be able to reuse screens, depending on the platform.

I could not find this in the documentation. Also the [Type checking with TypeScript
](https://reactnavigation.org/docs/typescript/#type-checking-screens) page states:

> To annotate the navigation prop, we need to import the corresponding type from the navigator. For example, StackNavigationProp for @react-navigation/stack:

which suggests that a screen is at least bound to a specific *kind* of Navigator.

So this is probably a request to make this more clear in the documentation.

**Comment by raajnadar** [comment]
Yes, You can use same screen in multiple navigators, if navigator refers to (stack, drawer, bottom tabs, etc).

**Comment by harterc3** [comment]
> Yes, You can use same screen in multiple navigators, if navigator refers to (stack, drawer, bottom tabs, etc).

I don't think this completely solves @artsra's issue. When using TypeScript, a screen/page's properties are defined as something like this:
```
StackScreenProps<MyStackParamList, "MyScreen">
```
`MyStackParamList` defines the usable params for each screen within `MyStack`. Now if we had another stack called `MySecondStack` with params defined in `MySecondStackParamList` and we wanted this new stack to also have `MyScreen` in it, how would that work? In the MyScreen file, we've already defined the props using `MyStackParamList`. Can we also have it reference `MySecondStackParamList`?

**Comment by jzxchiang1** [comment]
Bump, this is an important issue IMO

**Comment by pke** [comment]
@harterc3 asked an important question. You can't currently specify screen props via typescript when the screen is to be used in different stacks

**Comment by jzxchiang1** [comment]
I guess you would just have to hope the screen accepts the same params from all of the stack navigators it's used in... Then, you can just type the prop with the ParamList for one of the stack navigators...

**Comment by JDMathew** [comment]
How do we notify the core team to add support for this? 

It's not only a problem with the params type but also with the navigation prop type as the navigation prop can be a combination of multiple navigation props. We might need to create a condition type that accepts a generic which determines which screen is being referenced.

**Comment by jzxchiang1** [comment]
> How do we notify the core team to add support for this?
> 
> It's not only a problem with the params type but also with the navigation prop type as the navigation prop can be a combination of multiple navigation props. We might need to create a condition type that accepts a generic which determines which screen is being referenced.

Exactly!

**Comment by JDMathew** [comment]
@satya164, would you be able to weigh in on this issue. Would it be possible to annotate route and navigation screen props when it is used in multiple navigators. The same can be said for useNavigation and useRoute hooks used in components.

**Comment by JDMathew** [comment]
I was looking into this again and came up with a solution where I would conditionally create a type based off the route params key but ran into an issue where nested types are not narrowed and so TS couldn't determine the correct type. This would work if the screen name was passed in as a prop at the top level. See https://github.com/Microsoft/TypeScript/issues/18758

**Comment by Alpha0YZ** [comment]
Hey there, has someone found a workaround for this issue?

**Comment by Noitham** [comment]
Ever consider reopening the issue @raajnadar?
When using Typescript, it is not possible to use the same screen in multiple navigators as you mentioned.

**Comment by raajnadar** [comment]
Instead of opening a 2 years old issue, you can submit a new issue with a runnable code so that someone from the team will check & guide you if that is not a bug

**Comment by tibbe** [comment]
@raajnadar what's not clear about the bug report that runnable code will help clarify? A genuine question, the problem seems pretty clear to me. It's not possible to give a type to a screen used in two different navigator since the screen props are tied to one navigator.

**Comment by possible-evan** [comment]
I've run into this as well have had to jump through hoops to make it work due to how screen navigation is typed. Any solutions would be appreciated!

**Comment by aemre** [comment]
is there any workaround?
