### ISSUE TITLE
How to hide entire top tab bar?

### ISSUE THREAD

**Issue by Bayramito** [react-navigation/react-navigation#8143]
Hello,

I need this solution ASAP!!!

How can i hide or remove entire top tab bar, from the screen? 

I need only functionality of the createMaterialTopTabNavigator, so i dont need the labels or buttons etc...
TY

**Comment by raajnadar** [comment]
Read the docs

**Comment by Maskedman99** [comment]
This removes the tab and shows only indicator
```
    <Tab.Navigator
      tabBarComponent={() => null}
      tabBarOptions={{
        tabStyle: {height: 0},
        style: {backgroundColor: 'transparent'}
      }}>
      <Tab.Screen component={A} name="A" />
      <Tab.Screen component={B} name="B" />
    </Tab.Navigator>
```  
This removes the tab bar completely including the indicator
```
    <Tab.Navigator
      tabBarComponent={() => null}
      tabBarOptions={{
        style: {height: 0}
      }}>
      <Tab.Screen component={A} name="A" />
      <Tab.Screen component={B} name="B" />
    </Tab.Navigator>
```

**Comment by Kulothungan16** [comment]
Is there is a way to get it back after hiding it?

**Comment by johnjoshuadablo** [comment]
@Kulothungan16 I added a dynamic tabBarOptions that is dependent on a state. Something like this.

`  const tabBarOptions: MaterialTopTabBarOptions = useMemo(() => {
    if (isFetchingVideo) {
      return {
        tabStyle: {height: 0},
        style: {backgroundColor: 'transparent'},
        indicatorStyle: {backgroundColor: 'transparent'},
      };
    }
    return {
      indicatorStyle: ViewStyles.bgBackdrop,
      labelStyle: TypographyStyles.fontSizeDefault,
    };
  }, [isFetchingVideo]);

  return (
    <Navigator tabBarOptions={tabBarOptions}>
       {..screens}
    </Navigator>`

**Comment by Kulothungan16** [comment]
@johnjoshuadablo Thanks you very much

Another question, Is it possible to get the route name in MaterialTopBar like
```jsx
const TabNavigator = () => {
    const [routeName, setRouteName] = useState('');
    return (
    <Tab.Navigator onTabChange={(route) => setRouteName(route.name)}>
        ....screens
    </Tab.Navigator>
);
}
```
