### ISSUE TITLE
HeaderShown option not working as expected

### ISSUE THREAD

**Issue by ryanoillataguerre** [react-navigation/react-navigation#8144]
## Current Behavior

I have the following Stack Navigator (RepresentativesStack) that contains both the index screen (Representatives) and a screen that's navigated to (Representative) by clicking a card on the Representatives screen.

**Stack Navigator**

![Screen Shot 2020-04-27 at 8 59 10 PM](https://user-images.githubusercontent.com/28904005/80445910-3dcf7980-88ca-11ea-9b6b-71080e594f68.png)

**Index Screen**

The content of the header on the index page is a custom `SearchBar` component.

![Screen Shot 2020-04-27 at 8 59 41 PM](https://user-images.githubusercontent.com/28904005/80445981-6b1c2780-88ca-11ea-9b55-689795b74552.png)

**Representative Screen**

The header should not be showing at all on the Representative Screen, **BUT IT IS**

![Screen Shot 2020-04-27 at 9 00 10 PM](https://user-images.githubusercontent.com/28904005/80446052-a3236a80-88ca-11ea-9b5a-88d5745a4e46.png)

## Expected Behavior

- Expect the header on the Representatives index screen to contain the `SearchBar` component, which it does 👍 

- Expect the header to not show at all on the Representative screen ❌

The exact same header component (`SearchBar`) shows on the Representative screen, **even though** I'm explicitly setting the following:
```
headerMode="none"
options={({ navigation }) => ({
    headerShown: false,
    header: null,
})}
```
from the StackNavigator definition
AND
```
navigation.setOptions({
      header: () => null,
});
```
within the component

## How to Reproduce

- Create Stack Navigator
- Set `header` option inside first Stack Screen component
- Set `header` option to null inside another Stack Screen component within the same Navigator

[Snack here](https://snack.expo.io/@ryanoillataguerre/grounded-bacon)

If anyone has any ideas as to how to fix it, please let me know. I would be surprised if it was a bug with the core lib because it's a fairly common use case, but you never know. Figured I'd post it here just in case that's what's going on.

## Your Environment

**Notes** 

- This project was started with `react-native-init`
- Have not tested this on Android as my project is not built for it, but this is definitely a problem on iOS both in the simulator and on an actual device.

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | 13.4.1
| @react-navigation/native       | 5.1.7
| @react-navigation/stack        | 5.2.14
| react-native-gesture-handler   | 1.5.6
| react-native-safe-area-context | 0.6.2
| react-native-screens           | 1.0.0-alpha.23
| react-native                   | 0.62.0 and 0.62.2
| expo                           | n/a
| node                           | 12.16.2
| npm or yarn                    | 6.14.4

**Comment by ryanoillataguerre** [comment]
@raajnadar just added a Snack repro

**Comment by ryanoillataguerre** [comment]
## Update

Just managed a workaround for this issue, though it may still be a problem with the lib as the options above still aren't working. For anyone else experiencing this bug, I had to change `headerMode` to `screen` (`headerMode="screen"` prop on the Navigator) and just render the search bar in the `Representatives` screen itself. Not ideal, but it works for now.

**Comment by mojtabast** [comment]
Faced with exactly same issue. @ryanoillataguerre's solution worked for me as well.

I guess this is happening because `headerMode` is `float` by default, and for those custom `header`s that doesn't implement the `float` animation, you will face with this issue. (ref: https://reactnavigation.org/docs/stack-navigator#set-headermode-to-screen)
