### ISSUE TITLE
Delay switching between screens with different Header component

### ISSUE THREAD

**Issue by aliceathens** [react-navigation/react-navigation#8145]
**Current Behavior**

Nested createDrawerNavigator inside createStackNavigator.
Custom Nav bar header component for createDrawerNavigator with Hamburger menu toggle...
then createStackNavigator with modal views that have custom header Component.

eg
`<DrawerNavigationNavigator.Navigator
      initialRouteName="DrawerStack"
      screenOptions={{
        header: props => <Navbar {...props} />,
        gestureEnabled: false
      }}>
      <DrawerNavigationNavigator.Screen
        name="DrawerStack"
        component={DrawerStack}
      />
      <DrawerNavigationNavigator.Screen
        name="Insights"
        component={Insights}
        options={({navigation}) => ({
          header: props => <Header navigation={navigation} title=".... Blog" />,
          mode: 'modal',
        })}
      />
 </DrawerNavigationNavigator.Navigator>`

When I navigate to a createStackNavigator modal screen the header component shows instantly. When I click the close button which does goBack() the header component for the createStackNavigator shows over the top of the createDrawerNavigator for at least 2-3 seconds (the screen has already disappears instantly from the goBack()) but the header lags behind.

![9dK6Z3h2yb](https://user-images.githubusercontent.com/9316491/80448414-162fdf80-88d1-11ea-9b11-906d795872e8.gif)

**Expected Behavior**

- What do you expect should be happening?
When I click the 'X' to navigate back to Draw Menu the header goes away at the same time as the modal screen its attached too.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | iOS
| @react-navigation/native       | 5.1.4
| @react-navigation/stack        | 5.2.9
| react-native-gesture-handler   | 1.6.1
| react-native-safe-area-context | 0.7.3
| react-native-screens           | 2.4.0
| react-native                   | 0.62.0
| npm or yarn                    | yarn

**Comment by aliceathens** [comment]
@github-actions yes it does.

**Comment by satya164** [comment]
https://reactnavigation.org/docs/stack-navigator#set-headermode-to-screen

**Comment by sarazeaiter1** [comment]
This issue is still happening. Any solution?

**Comment by dylanjeffers** [comment]
Also experiencing this issue

**Comment by ignaciosantise** [comment]
this is the right solution, you have to provide an animation using the `progress` prop received in the header params

Check the example:
https://reactnavigation.org/docs/stack-navigator/#set-headermode-to-float-for-custom-header-animations
