### ISSUE TITLE
_this.toggleStatusBar is not a function error when using createDrawerNavigator in tests

### ISSUE THREAD

**Issue by callumbooth** [react-navigation/react-navigation#8151]
**Current Behavior**

When running tests with @testing-library/react-native and a screen that uses drawer navigation, it causes the following error.

```
TypeError: _this.toggleStatusBar is not a function

      at b (node_modules/@react-navigation/drawer/lib/commonjs/views/Drawer.tsx:418:11)
      at call (node_modules/react-native-reanimated/mock.js:141:19)
      at new DrawerView (node_modules/@react-navigation/drawer/lib/commonjs/views/Drawer.tsx:408:7)
      at constructClassInstance (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:3932:18)
      at updateClassComponent (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7639:5)
      at beginWork$1 (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9159:16)
      at performUnitOfWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12981:12)
      at workLoopSync (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12955:22)
      at renderRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12648:11)
      at runRootCallback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12420:20)

  console.error node_modules/react-native/Libraries/YellowBox/YellowBox.js:63
    Warning: Can't call forceUpdate on a component that is not yet mounted. This is a no-op, but it might indicate a bug in your application. Instead, assign to `this.state` directly or define a `state = {};` class property with the desired state in the DrawerView component.

  console.error node_modules/react-native/Libraries/YellowBox/YellowBox.js:63
    The above error occurred in the <DrawerView> component:
        in DrawerView (created by DrawerView)
        in RNCSafeAreaView (created by RNCSafeAreaView)
        in RNCSafeAreaView (at src/index.tsx:28)
        in SafeAreaProvider (created by Context.Consumer)
        in SafeAreaProviderCompat (created by DrawerView)
        in View (created by View)
        in View (created by DrawerView)
        in DrawerView (created by DrawerNavigator)
        in DrawerNavigator
        in EnsureSingleNavigator (created by ForwardRef(BaseNavigationContainer))
        in ForwardRef(BaseNavigationContainer) (created by ForwardRef(NavigationContainer))
        in ThemeProvider (created by ForwardRef(NavigationContainer))
        in ForwardRef(NavigationContainer)
        in View (created by View)
        in View (created by AppContainer)
        in View (created by View)
        in View (created by AppContainer)
        in AppContainer (at src/index.js:26)
    
    Consider adding an error boundary to your tree to customize error handling behavior.
    Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
```

**Expected Behavior**

It should render correctly in the test. This doesn't happen when changing the drawer navigator to a stack navigator in the test

**How to reproduce**

Repo to reproduce --> https://github.com/callumbooth/drawer-error-example

run `yarn test`

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | N/A
| @react-navigation/native       |  5.1.7
| @react-navigation/drawer       | 5.5.1
| react-native-reanimated        | 1.8.0
| react-native-gesture-handler   | 1.6.0
| react-native-safe-area-context |0.7.3
| react-native-screens           |2.2.0
| react-native                   |https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz
| expo                           |37.0.3
| node                           |12.16.2
| npm or yarn                    | yarn

**Comment by nemonweb** [comment]
I have same bug when test with `react-native-testing-library`

**Comment by GoMino** [comment]
Here is my workaround at the moment: 
```
jest.mock('@react-navigation/drawer', () => ({
  createDrawerNavigator: jest.fn().mockReturnValue({
    Navigator: ({children}) => <>{children}</>,
    Screen: ({children}) => <>{children}</>,
  }),
}));
```

**Comment by satya164** [comment]
there are no tests in your repo. please provide a repro with tests

**Comment by GoMino** [comment]
@satya164 if you use the basic test created by the cli you will see the issue:

```
describe('APP', () => {
  it('renders correctly', async () => {
    renderer.create(<App />);
  });
});
```

App.tsx code:
```
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 *
 * Generated with the TypeScript template
 * https://github.com/react-native-community/react-native-template-typescript
 *
 * @format
 */

import React from 'react';
import {createDrawerNavigator} from '@react-navigation/drawer';
import {View, Text} from 'react-native';
import {NavigationContainer} from '@react-navigation/native';

const Drawer = createDrawerNavigator();

function DrawerContent() {
  return (
    <View style={{flex: 1, alignItems: 'center', justifyContent: 'center'}}>
      <Text>Drawer content</Text>
    </View>
  );
}

function HomeScreen() {
  return (
    <View style={{flex: 1, alignItems: 'center', justifyContent: 'center'}}>
      <Text>Home Screen</Text>
    </View>
  );
}

export const RootNavigator = () => {
  return (
    <Drawer.Navigator
      drawerType="slide"
      drawerStyle={{width: 350}}
      drawerContent={() => <DrawerContent />}>
      <Drawer.Screen name="Home" component={HomeScreen} />
    </Drawer.Navigator>
  );
};

const App = () => {
  return (
    <>
        <NavigationContainer>
          <RootNavigator />
        </NavigationContainer>
    </>
  );
};

export default App;

```

**Comment by satya164** [comment]
You need to provide a runnable repro

**Comment by GoMino** [comment]
Why is that needed? you have all the required informations...

**Comment by satya164** [comment]
I don't have time to recreate every issue by reading through all the info. If there's no repo I can just clone and check to see the issue, then it's going to be deprioritized over the issues which have a repro.

It doesn't take you much time to provide a repro, it takes a lot of time for me to go through each issue and recreate repros by reading every info.

**Comment by GoMino** [comment]
Ok got, I will try to create a sample project when I have time.
I'm not the creator of the issue here, and because I found a working mock, this is not a priority for me.

**Comment by callumbooth** [comment]
> **How to reproduce**
> 
> Repo to reproduce --> https://github.com/callumbooth/drawer-error-example
> 
> run `yarn test`
>

I included a repo when opening the ticket, let me know if you "dont" have issues with the repo above

**Comment by GoMino** [comment]
yes I havn't seen but the test file exist here => `https://github.com/callumbooth/drawer-error-example/blob/master/screens/home.test.js`

**Comment by satya164** [comment]
Sorry it wasn't obvious where the test file is. This is why we ask for minimal repro with as little code, it's easy to get lost when you have multiple files and folders.

Anyway, the bug is because of reanimated's incorrect mock. Specifically this line https://github.com/software-mansion/react-native-reanimated/blob/d4d6455206ff78b3650cb087123d89e44de70182/mock.js#L141

It should not call the callback synchronously on defining. It probably should be a no-op.

Please open an issue in Reanimated repo or send a PR to fix the mock.

**Comment by tomonsoejang** [comment]
I had to do a lot of searching before finding this page. So, if someone is still stuck, going through [react-navigation testing documentation](https://reactnavigation.org/docs/testing/) might help
Reference from **react-navigation documentation** for setting up 


****** the following is  short extract from react-navigation documentation *****
### Testing with Jest
Testing code using React Navigation takes some setup since we need to mock some native dependencies used in the navigators. We recommend using Jest to write unit tests.

https://reactnavigation.org/docs/testing/
