### ISSUE TITLE
Shows blank white scree everytime

### ISSUE THREAD

**Issue by Bayramito** [react-navigation/react-navigation#8156]
Hello,

I'm using React navigation 5 on my project, and somewhere i used material top tab navigator.
i have 3 screens there 3 tabs actually, but once i load this screen, always showing a blank white screen on the right side of the entire screen. 

is there any solution for this?

**Comment by raajnadar** [comment]
Are you serious this is your 2nd issue that I saw without and useful info.

Issue template not followed
No proper info
No repro
No code

https://youtu.be/53zkBvL4ZB4

**Comment by raajnadar** [comment]
Closing this issue because no info was updated.
