### ISSUE TITLE
null is not an object (evaluating 'navigationRef.current.getRootState')

### ISSUE THREAD

**Issue by outaTiME** [react-navigation/react-navigation#8161]
Hi guys, 
im getting the following error after update to `@react-navigation/native@5.2.0` but if i rollback to  `@react-navigation/native@5.1.7` everything goes fine.

im using the screen tracking for analytics example:

https://reactnavigation.org/docs/screen-tracking

if you run the snack from this page and point to `@react-navigation/native@5.2.0` it breaks

![IMG_7E7B3936A91F-1](https://user-images.githubusercontent.com/140472/80764398-04d81480-8b17-11ea-8cba-df5952b87cc9.jpeg)

thanks !!!

**Comment by outaTiME** [comment]
🤟

**Comment by lc3t35** [comment]
@outaTiME did you check if it works under last commit 
```
"@react-navigation/compat": "5.1.14",
"@react-navigation/native": "5.2.3",
"@react-navigation/stack": "5.2.18",
```
I have the same error with these version.

**Comment by outaTiME** [comment]
@lc3t35 fixed for me after upadate currently im using these dependencies:

@react-navigation/core@5.4.0
@react-navigation/native@5.2.3
@react-navigation/routers@5.4.2
@react-navigation/stack@5.2.18

im not using the compat dependency, i hope it helps

**Comment by lc3t35** [comment]
My bad. works fine with this deps too 
```
"@react-navigation/compat": "5.1.14",
"@react-navigation/core": "5.4.0",
"@react-navigation/native": "5.2.3",
"@react-navigation/stack": "5.2.18",
```

The code given at https://reactnavigation.org/docs/screen-tracking must be implemented in App.js not in a SwitchNavigator.

**Comment by sachin-blinkdigital** [comment]
Workaround here is to use optional chaining as calling route name before its initialised results in error.

navigationRef.current?.getCurrentRoute()?.name;
