### ISSUE TITLE
Add documentation for web SPA redirects

### ISSUE THREAD

**Issue by EvanBacon** [react-navigation/react-navigation#8162]
Related: https://github.com/react-navigation/react-navigation/pull/8160

We have a similar guide for React Router + Netlify https://github.com/expo/examples/tree/master/with-react-router#deploying-to-netlify

We should also have one for Now:

- Create `now.json`:
```json
{
  "version": 2,
  "routes": [{ "handle": "filesystem" }, { "src": "/.*", "dest": "/index.html" }]
}
```

**Comment by axaysushir** [comment]
How can I help you to create documentation for SPA Redirects?
I want to more detail on this.

**Comment by Dev2927** [comment]
How can I help you to create documentation for SPA Redirects? Is this available RN?
