### ISSUE TITLE
How can i pass badge count from component and show the count in bottom-tabs

### ISSUE THREAD

**Issue by ppv94** [react-navigation/react-navigation#8164]
**Expected Behavior**

- I want to show the badge count in bottom tabs, how can I pass count from API to Tab.Navigator and display the count in the bottom tabs.

**Sample Code**

      <Tab.Navigator
        initialRouteName={this.state.selectedTab}
        tabBarOptions={{
          activeTintColor: '#248E42',
          labelStyle:{fontSize:width/35,fontFamily:'SFProText-Medium'}
        }}
      >
        <Tab.Screen
         name="Channels"
         component={Channels}
         options={{
          tabBarLabel: 'Channels',
          tabBarIcon: ({ focused,badgeCount }) => (
            <View>
            <Image source={Images.iconChannel} style={{ height: 24, width: 24, marginVertical:3, opacity:focused?1:0.4 }} />
            {badgeCount < 0 &&
              (
              <View style={styles.badge}>
                <Text style={{ color: 'white', fontSize: 10, fontWeight: 'bold' }}>{badgeCount}</Text>
              </View>
              )
            }
            </View>
          )
        }}
        />
        <Tab.Screen
         name="Documents"
         component={Documents}
         options={{
          tabBarLabel: 'Documents',
          tabBarIcon: ({ focused }) => (
            <Image source={Images.iconDocuments} style={{ height: 24, width: 24, marginVertical:3, opacity:focused?1:0.4 }} />
          ),
        }}
        />
      </Tab.Navigator>
    
`

**Your Environment**

| software                      | version |
| ----------------------------- | ------- |
| iOS or Android                |Both
| @react-navigation/native      |^5.1.7
| @react-navigation/bottom-tabs |^5.2.8
| react-native-screens          |^2.7.0
| react-native                  |0.62.2

**Comment by waneed00** [comment]
I wonder if this will solve your problem. 

https://stackoverflow.com/questions/61537218/how-can-i-update-or-pass-badge-count-from-component-to-tab-navigator-react-nati/61813127#61813127

if you found a better solution please do share.
