### ISSUE TITLE
@react-navigation/bottom-tabs createBottomTabNavigator.Navigator  undefined is not an object (evaluating '_native.NavigationHelpersContext.Provider')

### ISSUE THREAD

**Issue by huaiguoguo** [react-navigation/react-navigation#8169]
**Current Behavior**

undefined is not an object (evaluating '_native.NavigationHelpersContext.Provider') 
![image](https://user-images.githubusercontent.com/1888094/80800728-c7d65580-8bdc-11ea-9727-ab7ea142419d.png)

**Expected Behavior**

undefined is not an object (evaluating '_native.NavigationHelpersContext.Provider') 

**How to reproduce**

It's written entirely according to the example of official documents

```
app\ximalaya\src\navigator\BottomTabs.tsx

import React, {Component} from 'react';
import {Text, View, Button} from 'react-native';
import {NavigationContainer} from '@react-navigation/native';
import {createBottomTabNavigator} from '@react-navigation/bottom-tabs';

// export type BottomTabParamList = {
//   Home: undefined;
//   Listen: undefined;
//   Found: undefined;
//   Account: undefined;
//   HomeScreen: undefined;
// };

const Tab = createBottomTabNavigator();

class HomeScreen extends Component {
  render() {
    return (
      <View>
        <Text>HomeScreen</Text>
      </View>
    );
  }
}

class BottomTabs extends Component {
  render() {
    return (
      <NavigationContainer>
        <Tab.Navigator>
          <Tab.Screen name="HomeScreen" component={HomeScreen} />
        </Tab.Navigator>
      </NavigationContainer>
    );
  }
}

export default BottomTabs;

```

**Your Environment**

| software                      | version |
| ----------------------------- | ------- |
| iOS or Android                | android
| @react-navigation/native      | ^5.1.7
| @react-navigation/bottom-tabs | ^5.3.1
| react-native-screens          | ^2.7.0
| react-native                  | 0.62.2
| expo                          |
| node                          |  v12.13.1
| npm or yarn                   | yarn

```
{
  "name": "ximalaya",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint . --ext .js,.jsx,.ts,.tsx"
  },
  "dependencies": {
    "@react-native-community/masked-view": "^0.1.10",
    "@react-navigation/bottom-tabs": "^5.3.1",
    "@react-navigation/native": "^5.1.7",
    "@react-navigation/stack": "^5.2.14",
    "react": "16.11.0",
    "react-native": "0.62.2",
    "react-native-config": "^1.0.0",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-reanimated": "^1.8.0",
    "react-native-safe-area-context": "^0.7.3",
    "react-native-screens": "^2.7.0"
  },
  "devDependencies": {
    "@babel/core": "^7.6.2",
    "@babel/runtime": "^7.6.2",
    "@react-native-community/eslint-config": "^1.0.0",
    "@types/jest": "^24.0.24",
    "@types/react-native": "^0.62.0",
    "@types/react-test-renderer": "16.9.2",
    "@typescript-eslint/eslint-plugin": "^2.27.0",
    "@typescript-eslint/parser": "^2.27.0",
    "babel-jest": "^24.9.0",
    "babel-plugin-module-resolver": "^4.0.0",
    "eslint": "^6.5.1",
    "jest": "^24.9.0",
    "metro-react-native-babel-preset": "^0.58.0",
    "prettier": "^2.0.4",
    "react-test-renderer": "16.11.0",
    "typescript": "^3.8.3"
  },
  "jest": {
    "preset": "react-native",
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "jsx",
      "json",
      "node"
    ]
  }
}
```

**Comment by huaiguoguo** [comment]
it's ok after yarn upgrade

**Comment by anil-sidhu** [comment]
Not working even after upgrade package

**Comment by sergioengineer** [comment]
All good after yarn upgrade

**Comment by yurakruhlyk** [comment]
@anil-sidhu check maybe you forgot to upgrade @react-navigation/native package.

**Comment by raajnadar** [comment]
Try clearing the cache

**Comment by chooch620** [comment]
pod install worked for me

**Comment by daskinnyman** [comment]
problem solved after update the package to latest version

**Comment by kychesu** [comment]
Please share your package.json

**Comment by raajnadar** [comment]
@kychesu upgrade to latest version of react navigation v5

**Comment by isidore18** [comment]
Upgraded to latest version for react-navigation/stack and react-navigation/native made the trick

**Comment by arjun-ravi** [comment]
Working fine after yarn upgrade

**Comment by JordanBarthes** [comment]
undefined is not an object (evaluating '_native.NavigationHelpersContext.Provider')

i have the same problem.. it's working after and after install new dependancie i have this error..
When i use the Drawer.Scene .. i don't know why because this afternoon it's working and now impossible.. Can you help me ?

**Comment by ignacioaraya1995** [comment]
Working fine after a "yarn upgrade" or a "yarn install"

**Comment by AlvSovereign** [comment]
I can confirm the same - `yarn upgrade` resolves this error

**Comment by LucasSouza0** [comment]
component update resolves perfectly

**Comment by lmrarturo** [comment]
`npm update` works
