### ISSUE TITLE
useLinking error on web: Error: Looks like you are using 'useLinking' in multiple components

### ISSUE THREAD

**Issue by RWOverdijk** [react-navigation/react-navigation#8171]
**Current Behavior**

> Error: Looks like you are using 'useLinking' in multiple components. This is likely an error since URL integration should only be handled in one place to avoid conflicts. Also ensure that you set your android activity launchMode to single task in your AndroiManifest.xml file.

This is with a regular useLinking, just once, in App.js in a newly created expo project with the versions I've specified below.

Before the upgrade I was on these versions and had no issues:

```
    "@react-navigation/bottom-tabs": "^5.2.7",
    "@react-navigation/native": "^5.1.6",
    "@react-navigation/stack": "^5.2.13",
```

**Expected Behavior**

No error.

**How to reproduce**

Just use useLinking in a new expo project (rn-web) with the updated versions below.

**Your Environment**

```
    "@react-navigation/bottom-tabs": "^5.3.1",
    "@react-navigation/native": "^5.2.1",
    "@react-navigation/stack": "^5.2.16",
    "react-native": "~0.61.4",
    "expo": "^37.0.0",
```

Not sure which dep is responsible exactly, but because it's quite recent I'm assuming someone might know what this is all about.

**Comment by satya164** [comment]
Can you check if you're still facing the issue in the latest version?

**Comment by RWOverdijk** [comment]
Ah you just pushed an update again? Lemme check

**Comment by RWOverdijk** [comment]
@satya164 Whups, it does work but none of the URLs are correct anymore.

**Comment by RWOverdijk** [comment]
@satya164 As discussed on discord:

- I have disabled useLinking because the URLs aren't working anymore.
- I have moved to the linking prop on the <NavigationContainer />
- 👆works for regular use, but doesn't work on reload (doesn't load the correct page)
- `getPathFromState()` is not working properly and gives me the route names in the path instead of the actual nice path. I made sure to pass in the linking config.

Example:

```
{path: "/Root/Home/Venues?locale=en"}
```

**Comment by satya164** [comment]
Make sure that you're passing the same object to `getPathFromState` that you pass to `useLinking` in the "config" property.

Reloading works in the example app so if it's not working for you then maybe there's something wrong with the config. Check the example app to make sure that your config is correct https://github.com/react-navigation/react-navigation/blob/6bec620a3fd5fbce03f0d890230dc1652ba0ef72/example/src/index.tsx#L224

**Comment by RWOverdijk** [comment]
@satya164 Regarding the config you were right, I wasn't using the correct config, my bad.

But regarding the reloading, it doesn't work with a complex linking config. There's another issue out there for that: https://github.com/react-navigation/react-navigation/issues/7854

Any more complex linking config with nested routers fails in the weirdest ways currently.

Here's my config to show you what I mean:

```js
export const linkingConfig = {
  ItemConfiguration: {
    path: ':locale/venue/:slug/item-configuration',
    parse: { slug: String }
  },
  Filters: ':locale/filters',
  Payment: {
    path: ':locale/venue/:slug/payment',
    parse: { slug: String }
  },
  SelectAddress: ':locale/select-address',
  OrderDetails: {
    path: ':locale/venue/:slug/order-overview',
    parse: { slug: String }
  },
  VenueInfo: {
    path: ':locale/venue/:slug/info',
    parse: { slug: String }
  },
  Root: {
    path: '',
    initialRouteName: isWeb ? 'Landing' : 'Home',
    screens: {
      NotFound: {
        path: ':locale/not-found'
      },
      Home: {
        initialRouteName: 'Venues',
        screens: {
          Venues: ':locale/venues',
          Search: ':locale/search',
          PastOrders: ':locale/past-orders',
          ProfileStack: {
            screens: {
              Profile: ':locale/profile',
              Faq: ':locale/faq'
            }
          }
        }
      },
      VenueDetails: {
        path: ':locale/venue/:slug',
        parse: { slug: String }
      },
      Landing: {
        path: ':locale'
      }
    }
  }
}
```

**Comment by satya164** [comment]
Do you have correct config here? Are your `ItemConfiguration`, `Filters`, `Payment` page etc. in the root navigator or nested inside another screen? Make sure that you nest your config is nested like your navigation structure https://reactnavigation.org/docs/configuring-links/#handling-nested-navigators

**Comment by satya164** [comment]
Also not entirely sure if param in the beginning of the path is supposed to work. I'd suggest stripping the `locale` out before parsing.

cc @WoLewicki

**Comment by RWOverdijk** [comment]
@satya164 I did that. They are identical to the way the nav is set up (in terms of nesting and such). Those are modals, and I want them to always be accessible so I made them part of the Root nav.

Re stripping the locale: I can do that, but it was broken even before I added locales (see the other issue). I feel like you think I'm lying 😅

I know web isn't stable yet, just trying to be helpful :)

**Comment by WoLewicki** [comment]
Params should be at the end of the path segment or it won't work correctly. I will look at this closer on Monday.

**Comment by RWOverdijk** [comment]
It works fine with or without params at the beginning. But that's also besides the point and not the real issue I'm facing right now.

Still good to know! I'll work on a route parser soon, perhaps that can help with the flexibility here.

**Comment by RWOverdijk** [comment]
@satya164 Repro for the issues https://github.com/Rawphs/navigation-bug

1. Going straight to a nested screen in a new browser tab (http://localhost:19006/item/one for example) and press the browser's back button you'll end up in the "new tab" screen of the browser again.
2. http://localhost:19006/faq goes to search when refreshing the page, and not faq.

There's also no way to define the path taken to a linked screen. Because every nested navigator needs a path it quickly becomes difficult to solve this with more and more navigators. FAQ is a good example of this, in that it has a path to get there from the root of the app that is not being rebuilt when using linking.

I'll also put this comment in https://github.com/react-navigation/react-navigation/issues/7854 which is the real issue for this I think.

**Comment by vaibhav50596** [comment]
Hey, I am also getting the same issue with expo cli - on web and android!

Looks like you are using 'useLinking' in multiple components. This is likely an error since deep links should only be handled in one place to avoid conflicts.

Any workaround for this?

**Comment by RWOverdijk** [comment]
@vaibhav50596 Update. If it's the same issue, it should be resolved. If not, it's probably a different issue.

**Comment by RWOverdijk** [comment]
@WoLewicki Wait I just reread your comment... You mean they can't be in the middle of the path either? Because that would explain why things aren't working.

**Comment by satya164** [comment]
I believe this is now supported https://github.com/react-navigation/react-navigation/commit/3999fc28365c3a06a17d963c7be7fb7e897f99e0
