### ISSUE TITLE
Can't hide tabbar when on specific screen. I mean there is not tabBarVisible property

### ISSUE THREAD

**Issue by nesibeyyubov** [react-navigation/react-navigation#8172]
"@react-navigation/material-top-tabs": "^5.1.12",
 "@react-navigation/native": "^5.1.7",
 "@react-navigation/stack": "^5.2.14",

I am able to hide tabbar on bottomTabBar but not in top tab Bar.

![image](https://user-images.githubusercontent.com/55137572/80814497-0e2bb480-8bdd-11ea-855c-f0541ba58242.png)

**Comment by nesibeyyubov** [comment]
> The versions mentioned in the issue for the following packages differ from the latest versions on npm:
> 
> * `@react-navigation/material-top-tabs` (found: `5.1.12`, latest: `5.1.13`)
> * `@react-navigation/native` (found: `5.1.7`, latest: `5.2.2`)
> * `@react-navigation/stack` (found: `5.2.14`, latest: `5.2.17`)
> 
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?

i run the command "yarn upgrade" but it didn't solve my problem

**Comment by asherccohen** [comment]
See https://github.com/react-navigation/react-navigation/issues/8363

**Comment by satya164** [comment]
Add this in your tab bar:

```js
function MyTabBar({ state, descriptors, navigation }) {
  const focusedOptions = descriptors[state.routes[state.index].key];

  if (focusedOptions.tabBarVisible === false) {
    return null;
  }

  // rest
}
```

**Comment by satya164** [comment]
https://reactnavigation.org/docs/hiding-tabbar-in-screens/
