### ISSUE TITLE
Nested navigator inside screen isn't shown

### ISSUE THREAD

**Issue by Kleinhummel** [react-navigation/react-navigation#8173]
My initial situation is this:
In my App.js I have a BottomTabNavigation as the Root Navigation. Now inside one screen of the BottomTabNavigation I want to include a MaterialTopTabNavigation. But I don't want the MaterialTopTabNavigation to be the single element shown in the screen. But as soon as I wrap the MaterialTopTabNavigation inside a View, it isn't shown on the screen anymore. It is only shown if it is the only element rendered by the screen.
How to display some content AND the MaterialTopTabNavigator on one screen?

**Comment by raajnadar** [comment]
Closing because the issue template is not followed.

**Comment by clementbmn** [comment]
Hi, have you found a solution to this, I'm facing the same situation
