### ISSUE TITLE
react navigation 5 passing props in nested routes has a bug

### ISSUE THREAD

**Issue by chetanabc** [react-navigation/react-navigation#8176]
const Stack = createStackNavigator();
const Drawer = createDrawerNavigator();

class Root extends React.Component {
    render() {
        return (
            <Stack.Navigator initialRouteName="Dashboard" >
                <Stack.Screen name="Dashboard" component={Dashboard}  />
                <Stack.Screen name="Seller" component={SellerGroup}  />
            </Stack.Navigator>
        )
    }
}

class SellerRoutes extends React.Component {
    render() {
        return (
            <Stack.Navigator initialRouteName="SellerLogin" >
                <Stack.Screen name="SellerLogin" component={SellerLogin} />
            </Stack.Navigator>
        )
    }
}

class SellerGroup extends React.Component {
    render() {
        return (
            <Drawer.Navigator initialRouteName="SellerRoutes" >
                <Stack.Screen name="SellerRoutes" component={SellerRoutes}  />
            </Drawer.Navigator>
        )
    }
}

class Routes extends React.Component {
    state = { isLoading: true, }
    async componentDidMount() {
        setTimeout(async () => { this.state({ isLoading: false }) }, 500);
    }

    render() {
        if (this.d.isLoading) {
            return <SplashScreen />;
        } else {
            return (
                <NavigationContainer  >
                    <Drawer.Navigator initialRouteName="Root"  >
                        <Stack.Screen name="Root" component={Root}  />
                    </Drawer.Navigator>
                </NavigationContainer>
            )
        }
    };
}

export default Routes

<TouchableOpacity
      onPress={() => {
        this.props.navigation.navigate('Seller', { screen: 'SellerLogin', params:{to:'text here'} })
   }}>
    <Text>Seller Login</Text>
 </TouchableOpacity>

// using above Routing while I tried pass props to my nested routes, I find that this.props.routes.params is undefined this this is surely a confirm bug in React Navigation 5

**Comment by chetanabc** [comment]
Hi @raajnadar, Thanks for your reply, as you have suggested I have created a repo on snack.expo.io 

https://snack.expo.io/@chetanabc/reactnavigationbug

In above expo app the parameters are not received in nested route for sure.. Please have look and let me know if I am wrong somewhere??
Thanks

**Comment by raajnadar** [comment]
Fixed the issue here https://snack.expo.io/@raajnadar/96cedc

**Comment by chetanabc** [comment]
Hi @raajnadar , I noticed that you have made changes in Routes.js to fix this issue, but I don't want to make changes in Routes.js  as it will stop my componentDidMount function to work every time, could please the issue in same expo repo and help me solve this issue, I have explain issue in same link
https://snack.expo.io/@chetanabc/reactnavigationbug
thanks
