### ISSUE TITLE
TabBar Item's content overlap on each other.

### ISSUE THREAD

**Issue by Hareramrai** [react-navigation/react-navigation#8177]
**Current Behavior**

<img width="408" alt="Screenshot 2020-05-03 at 2 14 57 PM" src="https://user-images.githubusercontent.com/1335876/80909779-8367c880-8d48-11ea-84cc-89bb4ed9b4bd.png">

<img width="407" alt="Screenshot 2020-05-03 at 2 15 08 PM" src="https://user-images.githubusercontent.com/1335876/80909781-85318c00-8d48-11ea-8c36-bf8daeb70f42.png">

- What code are you running and what is happening?

I am using `createMaterialTopTabNavigator` for creating tab navigation in my application. 

Below the sample code for the above screenshots.

````
export const DiscussionNavigation = createMaterialTopTabNavigator(
    {
        Discussion: {
            screen: DiscussionList,
            navigationOptions: {
                tabBarIcon: ({ focused }) => {
                    if (focused) {
                        return (
                            <View
                                style={{
                                    flexDirection: 'row',
                                    flex: 1,
                                    width: 200
                                }}>
                                <DashboardIcon color={'#6EAF52'} />
                                <Text
                                    style={{
                                        fontSize: 16,
                                        flexDirection: 'row',
                                        color: '#6EAF52'
                                    }}>
                                    Discussion
                                </Text>
                            </View>
                        );
                    } else {
                        return (
                            <View style={{ width: 30 }}>
                                <DashboardIcon color={'#CCCCCC'} />
                            </View>
                        );
                    }
                }
            }
        },
        Members: { 
        },
       ....,
      {
        lazy: true,
        tabBarOptions: {
            activeTintColor: 'green',
            inactiveTintColor: '#323232',
            showIcon: true,
            showLabel: false,
            style: {
                backgroundColor: '#fff',
                zIndex: 0
            },
            indicatorStyle: {
                backgroundColor: indicatorColor
            }
        }
    }
}



 <SafeAreaView style={{ flex: 1 }}>
       <View style={{ flex: 1 }}>
          <DiscussionNavigation navigation={this.props.navigation} />
       </View>
 </SafeAreaView>
````

- Include a screenshot or video if it makes sense.

**Expected Behavior**

- What do you expect should be happening?

Each of the individual items should not overlap. 

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS                |  13.1 
| @react-navigation/native       | "^5.1.4"
| react-native                   | 0.61.5
| expo                           |
| node                           | v12.16.1
| npm or yarn                    |  yarn

**Comment by satya164** [comment]
Well, there's not enough space to render it so it'll overlap. You can use a custom tab bar to have your custom layout instead.
