### ISSUE TITLE
Private Route in react native not working on page changes.

### ISSUE THREAD

**Issue by raazatul7** [react-navigation/react-navigation#8179]
**Current Behavior**
Getting Error :
### Private Route in react native not working on page changes. The action 'NAVIGATE' with payload {"name":"Home"} was not handled by any navigator.

Do you have a screen named 'Home'?

If you're trying to navigate to a screen in a nested navigator, see https://reactnavigation.org/docs/nesting-navigators#navigating-to-a-screen-in-a-nested-navigator.

This is a development-only warning and won't be shown in production.

![IMG_4C18B4CB1A7B-1](https://user-images.githubusercontent.com/29301407/80912566-625ca300-8d5b-11ea-8757-7071f3ae2476.jpeg)

**Expected Behavior**
Not able to navigate using Auth flow.

**How to reproduce**
User code from : https://reactnavigation.org/docs/auth-flow
```
<NavigationContainer>
        <Stack.Navigator
          screenOptions={{
            headerShown: false,
          }}>
           {isSignedIn === "true"? ( 
            <> 
            <Stack.Screen name="Home" component={Home} />
            <Stack.Screen name="Bookorder" component={Bookorder} />
             </> 
           ) : (
            <>
            <Stack.Screen name="Login" component={Login} />
            </>
          )}
        </Stack.Navigator>
  </NavigationContainer>
```
**Your Environment**
System:
    OS: macOS 10.15.4
    CPU: (4) x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
    Memory: 46.17 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 13.12.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 25, 28, 29
      Build Tools: 28.0.3, 29.0.2
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6392135
    Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
  Languages:
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.0 => 0.62.0 
| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |
| @react-navigation/native       |
| @react-navigation/stack        |
| react-native-gesture-handler   |
| react-native-safe-area-context |
| react-native-screens           |
| react-native                   |
| expo                           |
| node                           |
| npm or yarn                    |

**Comment by daybreaker** [comment]
Where are you calling your "navigate" action? 

If youre following the auth flow example, you dont need to navigate to Home after a Login, you just set isLoggedIn to true, and the Navigator will switch the routes out automatically and send you to Home. When you're in the Login path, there technically is no "Home" route to navigate to, because isLoggedIn is false

**Comment by raazatul7** [comment]
> Where are you calling your "navigate" action?
> 
> If youre following the auth flow example, you dont need to navigate to Home after a Login, you just set isLoggedIn to true, and the Navigator will switch the routes out automatically and send you to Home. When you're in the Login path, there technically is no "Home" route to navigate to, 
because isLoggedIn is false

In Login class 
I set isLoggedIn : true and then
`this.props.navigation.navigate('Home')`
and it throws error.

**Comment by samipshah100** [comment]
I am having the same error when i try to use navigationRef as per this guide ( https://reactnavigation.org/docs/navigating-without-navigation-prop ) 

is the app.js not mounted or something?

**Comment by raazatul7** [comment]
> I am having the same error when i try to use navigationRef as per this guide ( https://reactnavigation.org/docs/navigating-without-navigation-prop )
> 
> is the app.js not mounted or something?

yes, it works when I'm navigating in same stack
and shows error when navigating to different stack
i.e I'm able to navigate from Home to bookmark but it throws error if I navigating to home from Login.
