### ISSUE TITLE
Supply navigation object to headerLeft and related component customization points

### ISSUE THREAD

**Issue by mschipperheyn** [react-navigation/react-navigation#8185]
**Current Behavior**

I have a stack navigator and a modal navigator. The stack navigator navigates to the modal navigator for modals. When it does, there is no concept of "back", because you switch navigator and back is relative to the current navigator. 

In order to navigate "back" to the stack navigator, you actually have to execute a `navigate`. 
Currently, the `navigation` object is not supplied to e.g. the `headerLeft` function. You can work around this by implementing a custom component and using `useNavigation`, but if you want to stay vanilla, and use the out of the box components you're stuck. They encapsulate this functionality and it's not accessible.

**Expected Behavior**

The navigation object is supplied to `headerLeft` and similar functions.

**How to reproduce**

Create a stacknavigator and a modal navigator. navigate from the stack to the modal navigator and create a `headerLeft` function
 
**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | both
| @react-navigation/native       | 5.1.5
| react-native                   | 61.4
| expo                           | 37
| node                           | 12.16
| npm or yarn                    | yarn

**Comment by mschipperheyn** [comment]
I will, thanks

**Comment by mschipperheyn** [comment]
Ok, robot, I upgraded everything to the latest and greatest and the navigation object is not available in the `headerLeft` options and the onPress handler. Wrapping the whole thing it is for now.

**Comment by satya164** [comment]
Both `options` and `screenOptions` props receive the `navigation` object when used as a function. You don't need `useNavigation` for that.

**Comment by mschipperheyn** [comment]
@satya164 yes, well, I might be missing something, but

```
import { Header, HeaderBackButton } from '@react-navigation/stack';
[...]
    options: {
        header: props => {
            const { scene, previous, navigation } = props;
            return (
                <Header
                    {...props}
                    headerLeft={props => ( // can't do this bc header properties are stored in the scene. Should I manipulate that directly? Prob not.
                        <HeaderBackNavigationButton {...props} previous={previous} />
                    )}
                />
            );
        },
        headerBackImage: () => <BackButton htmlColor="#616C8A" />,
        headerLeft: props => {
            // don't have navigation here
            return <HeaderBackNavigationButton {...props} />
        },
    },
```

**Comment by satya164** [comment]
```js
options={({ navigation }) => ({ ...whatever })}`

**Comment by mschipperheyn** [comment]
Yeah, I get that the navigation object is available there. But my point is that it's not possible to use the out of the box header components with it because they encapsulate this functionality in such a way that customization requires wrapping the component. It should be easier than that. I guess I'm not getting my point across. I'll just go ahead with a wrapper.

**Comment by satya164** [comment]
I don't see how it's not available here. You literally have it in the closure:

```js
options={({ navigation }) => ({
  headerLeft: () => ^there is `navigation`
})}
```

**Comment by mschipperheyn** [comment]
Ah I see now, I should use options as a function rather than a key value. Ok, thanks.
