### ISSUE TITLE
[v5] headerLeft/Right theme without headerTintColor

### ISSUE THREAD

**Issue by AzzouDuGhetto** [react-navigation/react-navigation#8189]
I'm trying to get a custom headerLeft/Right component to get my app color from NavigationContainer's theme. Actually it can be done using headerTintColor but it kinda break the purpose of the NavigationContainer's theme if I have then to set my custom color in all my headerTintColor (screenOptions make it less painful but still).

**Current Behavior**
 
headerLeft/Right only give tintColor props depending on headerTintColor

**Expected Behavior**

headerLeft/Right to give tintColor props depending on `<NavigationContainer theme{}>`

React Navigation use this method to theme the color using useTheme() hook

`color: tintColor === undefined ? colors.text : tintColor`

But props color is send by this method (headerRight example, in HeaderSegment.tsx)

`{right({ tintColor: headerTintColor })}`

Wouldn't be possible to use the same method for both, like this we may be able to get themed color in headerLeft/Right props ?

**How to reproduce**

`headerRight: (props) => <Icon name="settings" {...props} />`

**Comment by AzzouDuGhetto** [comment]
After further investigation, it doesn't seem possible to use useTheme in HeaderSegment...

**Comment by satya164** [comment]
You can specify custom color for the title using `headerTitleStyle` while using theme tint color for your left/right items.
