### ISSUE TITLE
The 'navigation' object hasn't been initialized yet

### ISSUE THREAD

**Issue by kulkarnisaumitra98** [react-navigation/react-navigation#8191]
**Current Behavior**

```
import React from 'react';

export const isMountedRef = React.createRef();

export const navigationRef = React.createRef();

export function navigate(routeName, params) {
  if (isMountedRef.current && navigationRef.current) {
    console.log('Mounted', navigationRef.current);
    navigationRef.current.navigate(routeName);
  } else {
    console.log('Not mounted');
  }
}

```
I am getting console log as Mounted and getting the correct Navigation object.

**Expected Behavior**

Since it is mounted I should we able to call navigate but the following error occurs,

Error: The 'navigation' object hasn't been initialized yet. This might happen if you don't have a navigator mounted, or if the navigator hasn't finished mounting.

```
const Routes = () => {
  const { user } = useContext(UserContext);

  React.useEffect(() => {
    isMountedRef.current = true;

    navigate('Chunks'); // Works here, but doesnt work in NavbarOptions  component

    return () => (isMountedRef.current = false);
  }, []);

  return (
    <>
      {user.username ? <NavbarOptions /> : null}
      <NavigationContainer ref={navigationRef}>
        {user.username ? <TabRoutes /> : <StackRoutes />}
      </NavigationContainer>
    </>
  );
};

```
Routes.js

```
import { navigate } from '../../../reusables/functions/NavigatorService';

const NavbarOptions = ({
  selected,
  renderComponents,
}) => {
  useEffect(() => {
    switch (selected) {
      case 0:
        navigate('Chunks'); // Error occurs here
        break;
      case 1:
        navigate('Completed');
        break;
      case 2:
        navigate('Leaderboard');
        break;
      default:
        navigate('Auth');
        break;
    }
  }, [selected]);
```
Sibling component to Routes.js -> NavbarOptions.js

**Environment**

| software                           | version |
| expo-web|
| @react-navigation/native | 5.2.3|
| react-native                      | sdk-37.0.1.tar.gz|
| expo                                 | 37.0.3|
| node                                 | 10.2|
| npm or yarn                      | npm|

**Comment by ralph-dev** [comment]
@kulkarnisaumitra98 
UseRefs should be used in UseLayoutEffects. Let me know if this helps :)

**Comment by satya164** [comment]
Dunno how your `isMountedRef` is true, but parent `useEffect` runs after children's and you're doing navigation ins `useEffect` of child, when the app hasn't finished rendering.

Also doing navigation on mount doesn't seem right, you should probably set `initialRouteName` conditionally instead of navigating.

**Comment by thqueiroz** [comment]
And I think that three functions can be refactored 

![Captura de Tela 2020-10-08 às 18 13 03](https://user-images.githubusercontent.com/42079047/95514234-faf1f180-0991-11eb-80f3-6ee56ea93360.png)

**Comment by lopesboa** [comment]
hi @thqueiroz can u tell what extension is this pls.
Thanks.
