### ISSUE TITLE
error: Error: Unable to resolve module `./NavigationNativeContainer` from `node_modules\@react-navigation\native\src\index.tsx`:

### ISSUE THREAD

**Issue by asaadxheikh** [react-navigation/react-navigation#8197]
I'm using react-native CLI for my project and using react-navigation v5. I updated all react-navigation to the latest, but still getting error.

My package.json 

  
> "dependencies": {

    "@react-native-community/masked-view": "^0.1.10",
    "@react-navigation/bottom-tabs": "^5.2.8",
    "@react-navigation/native": "^5.2.4",
    "@react-navigation/stack": "^5.2.19",
    "firebase": "^7.14.2",
    "native-base": "^2.13.12",
    "react": "16.11.0",
    "react-native": "0.62.2",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-ionicons": "^5.0.0-rc",
    "react-native-reanimated": "^1.8.0",
    "react-native-safe-area-context": "^0.7.3",
    "react-native-safe-area-view": "^1.1.1",
    "react-native-screens": "^2.7.0",
    "react-native-vector-icons": "^6.6.0"
  }

**Comment by asaadxheikh** [comment]
I upgraded packages but error still there.

**Comment by benbeltzer** [comment]
Also having the same issue. I'm on @react-navigation/bottom-tabs 5.3.4 and 
@react-navigation/native 5.2.4

**Comment by 7934345** [comment]
> Running `npx react-native start --reset-cache` fixed the issue for me.
> Source: https://reactnavigation.org/docs/troubleshooting/

What about not using Expo???

**Comment by raajnadar** [comment]
For expo use this `expo start -c`

**Comment by asaadxheikh** [comment]
> Running `npx react-native start --reset-cache` fixed the issue for me.
> Source: https://reactnavigation.org/docs/troubleshootin

It worked for me.

**Comment by nirmaldalmia** [comment]
> Running `npx react-native start --reset-cache` fixed the issue for me.
> Source: https://reactnavigation.org/docs/troubleshooting/

I tried everything from deleting and reinstalling node_modules to cloning the entire project all over again but nothing worked. After spending over an hour on this, I finally came across this comment. Worked like a charm! Thanks @benbeltzer

**Comment by hackrx** [comment]
> > Running `npx react-native start --reset-cache` fixed the issue for me.
> > Source: https://reactnavigation.org/docs/troubleshooting/
> 
> I tried everything from deleting and reinstalling node_modules to cloning the entire project all over again but nothing worked. After spending over an hour on this, I finally came across this comment. Worked like a charm! Thanks @benbeltzer

Same here, thanks @benbeltzer

**Comment by vaibsshukla** [comment]
For those who don't use npx can  try this `react-native start --reset-cache`

**Comment by amiour-billel** [comment]
It worked for me thks

**Comment by mertmetin** [comment]
> For those who don't use npx can try this `react-native start --reset-cache`

Tried many things. Only this one worked!!!

**Comment by devang-p-eq** [comment]
> For those who don't use npx can try this `react-native start --reset-cache`

yes its worked thanks

**Comment by REVATHI-CMOON** [comment]
> For those who don't use npx can try this `react-native start --reset-cache`

thank you ,its working

**Comment by HiddenThroll** [comment]
> Running `npx react-native start --reset-cache` fixed the issue for me.
> Source: https://reactnavigation.org/docs/troubleshooting/

Yes，it works，thank you
