### ISSUE TITLE
tabPress listener not invoked for un-rendered tabs, thus doesn't run with lazy=true

### ISSUE THREAD

**Issue by JulianKingman** [react-navigation/react-navigation#8198]
**Current Behavior**

1. Create a tab navigator with tabs Home and Settings (per the [snack](https://snack.expo.io/?platform=android&name=createBottomTabNavigator%20%7C%20React%20Navigation&dependencies=%40react-native-community%2Fmasked-view%400.1.7%2C%40react-navigation%2Fbottom-tabs%405.2.4%2C%40react-navigation%2Fdrawer%405.3.4%2C%40react-navigation%2Fmaterial-bottom-tabs%405.1.6%2C%40react-navigation%2Fmaterial-top-tabs%405.1.6%2C%40react-navigation%2Fnative%405.1.3%2C%40react-navigation%2Fstack%405.2.6%2Creact-native-reanimated%401.7.0%2Creact-native-safe-area-context%400.7.3%2Creact-native-screens%402.4.0&sourceUrl=https%3A%2F%2Freactnavigation.org%2Fexamples%2F5.x%2Fbottom-tab-prevent-default.js) in [the docs](https://reactnavigation.org/docs/bottom-tab-navigator/#tabpress))
2. Move tabPress listener to Settings screen ([example](https://snack.expo.io/@buishi/createbottomtabnavigator-|-react-navigation?platform=android&name=createBottomTabNavigator%20%7C%20React%20Navigation&dependencies=%40react-native-community%2Fmasked-view%400.1.7%2C%40react-navigation%2Fbottom-tabs%405.2.4%2C%40react-navigation%2Fdrawer%405.3.4%2C%40react-navigation%2Fmaterial-bottom-tabs%405.1.6%2C%40react-navigation%2Fmaterial-top-tabs%405.1.6%2C%40react-navigation%2Fnative%405.1.3%2C%40react-navigation%2Fstack%405.2.6%2Creact-native-reanimated%401.7.0%2Creact-native-safe-area-context%400.7.3%2Creact-native-screens%402.4.0&sourceUrl=https%3A%2F%2Freactnavigation.org%2Fexamples%2F5.x%2Fbottom-tab-prevent-default.js))
3. Click Settings tab, it will navigate and not preventDefault (because it hasn't rendered yet, thus the listener is not instantiated)

**Expected Behavior**

Press Settings and default is prevented

**How to reproduce**

[Snack](https://snack.expo.io/@buishi/createbottomtabnavigator-|-react-navigation?platform=android&name=createBottomTabNavigator%20%7C%20React%20Navigation&dependencies=%40react-native-community%2Fmasked-view%400.1.7%2C%40react-navigation%2Fbottom-tabs%405.2.4%2C%40react-navigation%2Fdrawer%405.3.4%2C%40react-navigation%2Fmaterial-bottom-tabs%405.1.6%2C%40react-navigation%2Fmaterial-top-tabs%405.1.6%2C%40react-navigation%2Fnative%405.1.3%2C%40react-navigation%2Fstack%405.2.6%2Creact-native-reanimated%401.7.0%2Creact-native-safe-area-context%400.7.3%2Creact-native-screens%402.4.0&sourceUrl=https%3A%2F%2Freactnavigation.org%2Fexamples%2F5.x%2Fbottom-tab-prevent-default.js) (same referenced above)

**Thoughts**

Obviously this is because the tab is not rendered, as `lazy={false}` by default. However, I don't believe settings lazy to true is the solution, as this needlessly renders all the tabs, triggering lifecycle hooks and slowing things down.

Some potential solutions (ranked in order of intuitiveness):
 - Allow hooking into tabPress from the `<Tab.Navigator>` or better yet the`<Tab.Screen>` component. With the movement of all the navigationOptions into the Screens (a choice I love, btw), this move makes a lot of sense. For example 
```javascript
<Tab.Screen onTabPress={e => {e.preventDefault(); Alert('No pressy!!')}} {...props} />
```
 - Add some kind of "renderOnTabBarLoad" option that can be passed to tab screens, e.g.
```javascript
<Tab.Screen renderOnTabBarLoad={true | false} />
```
 - Some hacky workaround where you set `lazy` to false and render `null` on each tab that shouldn't be rendered, unless the tab is focused, then render the content.
```javascript
// TabNavigator.js
<Tab.Navigator lazy={false}>
  <Tab.Screen screen={Settings} name="Settings />
</Tab.Navigator>

// Settings.js
const focused = useIsFocused();
React.useEffect(() => {
    const unsubscribe = navigation.addListener('tabPress', e => {e.preventDefault(); Alert('No Pressy!')});
return unsubscribe;
  }, [navigation]);
if (!focused) return null;
const thing = runSomeExpensiveFunction();
return (
  <View> { /* etc... */ } </View> 
)
```

**Comment by satya164** [comment]
https://reactnavigation.org/docs/navigation-events#listeners-prop-on-screen

**Comment by iiagodias** [comment]
Solution?
I'm trying to behave differently from v4, when I click on the tab it first goes to the screen and if I click again it runs tabPress, formerly on the first click it ran tabPress.
