### ISSUE TITLE
[v5] library not working at all - NavigationContainer.tsx renders only fallback in iOS release with RN 62.2

### ISSUE THREAD

**Issue by majirosstefan** [react-navigation/react-navigation#8203]
**Current Behavior**
It is working in debug mode only, not working on IOS release (renders only fallback prop).

- What code are you running and what is happening?

**From tutorial**:

import 'react-native-gesture-handler';
import * as React from 'react';
import { View, Text } from 'react-native';
import { NavigationContainer } from '@react-navigation/native';
import { createStackNavigator } from '@react-navigation/stack';

function HomeScreen() {
  return (
    <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
      <Text>Home Screen</Text>
    </View>
  );
}

const Stack = createStackNavigator();

function App() {
  return (
    <NavigationContainer fallback={<Text>Loading...</Text>}>
      <Stack.Navigator>
        <Stack.Screen name="Home" component={HomeScreen} />
      </Stack.Navigator>
    </NavigationContainer>
  );
}

**In iOS release, it renders only "Loading" (fallback component).**

**Expected Behavior**
It should render NavigationContainer ( and whole nav tree) instead of fallback component.

**How to reproduce**
Just create a release build and run it on the iOS device.

I am using 
 react-navigation: "^4.3.8",
 react-native: "0.62.2",
 react: "16.11.0",

**Your Environment**

System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 519.82 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v10.16.0/bin/yarn
    npm: 6.12.1 - ~/.nvm/versions/node/v10.16.0/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.8.4 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29
      Build Tools: 27.0.3, 28.0.3, 29.0.1, 29.0.2
      System Images: android-24 | Google Play Intel x86 Atom, android-26 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom
      Android NDK: 20.1.5948944
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.3/11C29 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_222 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found

**It seems that issue is in NavigationContainer.tsx.**

if I comment following code (lines 57 to 61): 

  // if (!isReady) {
  //   // This is temporary until we have Suspense for data-fetching
  //   // Then the fallback will be handled by a parent `Suspense` component
  //   return fallback as React.ReactElement;
  // }

**it is just working as I would expect (also in release mode).**

**Comment by satya164** [comment]
Closing since you didn't provide any repro. We need a minimal repro to be able to debug issues. Feel free to open a new issue if you have a repro.
