### ISSUE TITLE
Nested navigator inside screen isn't shown

### ISSUE THREAD

**Issue by Kleinhummel** [react-navigation/react-navigation#8204]
**Current Behavior**

In my App.js I have a BottomTabNavigation as the Root Navigation. Now inside one screen of the BottomTabNavigation I want to include a MaterialTopTabNavigation. But I don't want the MaterialTopTabNavigation to be the single element shown in the screen. But as soon as I wrap the MaterialTopTabNavigation inside a View, it isn't shown on the screen anymore. It is only shown if it is the only element rendered by the screen.

**Expected Behavior**

The MaterialTopTabNavigation should be displayed on the screen even if it is wrapped inside a view.

**How to reproduce**

[Snack](https://snack.expo.io/@christophhummler/reactnavigationscreenbug)
The weird thing is: On the web emulator the MaterialTopTabNavigation is displayed but on Android and iOS it isn't.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| Android                 | 9
| iOS                 | 12.4.5
| @react-navigation/native       | 5.2.4
| react-native                   | 0.62 (latest I think)
| expo                           | 37.0.3
| node                           | 12.9.1
| yarn                    | 1.17.3

**Comment by satya164** [comment]
Add `flex: 1` to your view wrapping the navigator.

**Comment by Kleinhummel** [comment]
> Add `flex: 1` to your view wrapping the navigator.

Wow, too easy. I recognized: In my own local project the view wrapping the navigator had `alignItems: 'center'`, which caused the Navigator to not show up. Now everything is working. Thank you very much!
