### ISSUE TITLE
props empty stacknavigator  

### ISSUE THREAD

**Issue by maximguer2** [react-navigation/react-navigation#8211]
Hi everyone, 
When I try to go to the Component Copyright in my component headermenu, I have an mistake this.props.navigate.navigation is not an object, After Read this.props with consol.log I saw my props was empty. 

I make a Header compnenent :headermenu I call it in my stack navigator in my screen menu 

Menu: { 
    screen: Menu,
    navigationOptions: {
      headerTitle:()=><HeaderMenu  />
    }
  },

How could I solve it please I spend few days on this problems

**Comment by raajnadar** [comment]
Please follow the issue template. We can't help you until you provide proper information.
