### ISSUE TITLE
NavigationContainer Linking with open iOS app

### ISSUE THREAD

**Issue by ericvicenti** [react-navigation/react-navigation#8213]
**Current Behavior**
NavigationContainer linking works great when the iOS app is starting from cold boot, and on Android.

When the URI is opened on a running iOS app, nothing seems to happen, the URL is not opened.

**Expected Behavior**

The screen specified by the path should open 

**How to reproduce**

Check out the example repo, run yarn.

Edit `App.js` and select the example app in `Chapter5.tsx`

`yarn ios`

On cold boot of the app, this works fine:

```
npx uri-scheme open taskreact://task/1 --ios
```

Once the app is open, the url open does not work. Again, this is not a bug on Android.

**Your Environment**

iOS
"react-native": "~0.61.5",
"@react-navigation/native": "^5.2.4",
"expo": "~37.0.3",

**Comment by satya164** [comment]
Could you check what `Linking.addEventListener` prints in this case?

**Comment by ericvicenti** [comment]
Ah I should have checked.. it actually doesn't print anything.. so probably something wrong with this version of expo/RN?

Example repo is here (uncomment chapter 5 in App.js) https://github.com/ericvicenti/TaskReactor_Workshop

**Comment by Cookizza** [comment]
I am also having this issue on current versions - ios in background opens but does not navigate - Linking listener never seems to fire. Perhaps this is an issue between react-navigation and expo-linking packages?

**Comment by satya164** [comment]
Please open post it in expo forums.

**Comment by n0izn0iz** [comment]
We're having this exact problem on
- "@react-navigation/native": "^5.7.1"
- "react-native": "^0.61.5"
- iOS 13.1

We do NOT use expo, please reopen
