### ISSUE TITLE
createMaterialBottomTabNavigator not have tabBarVisible like createBottomTabNavigator

### ISSUE THREAD

**Issue by NguyenPhatBG** [react-navigation/react-navigation#8215]

**Comment by exneval** [comment]
@satya164 can you look at this one? It's sad that MaterialBottomTabNavigator (Top/Bottom) doesn't have the tabBarVisible!

**Comment by satya164** [comment]
https://reactnavigation.org/docs/hiding-tabbar-in-screens

**Comment by exneval** [comment]
Well.. the docs only recommended for people that want to show/hide the tab bar in mid navigation..

but In my case, I want to show/hide the tab bar when showing modal, click button, show sliding up panel, and that's not possible with MaterialTabs. Instead I'd been forced to use bottom tab.

how will you solve the case with Material if it doesn't have options tabBarVisible? @satya164

**Comment by shubich** [comment]
agree with @exneval 
@satya164 any updates?

**Comment by tr3v3r** [comment]
@shubich @exneval You can use 
```
 tabBar={() => null}
```
to hide tab bar

**Comment by ahmadtech199** [comment]
I tried to use
`tabBar={() => null} 
`
with 
`createBottomTabNavigator  
`
from library 
`@react-navigation/material-bottom-tabs 
`
but not working 
this is solution with only
` @react-navigation/bottom-tabs
`


can you help me?

**Comment by MHaris404** [comment]
> I tried to use `tabBar={() => null} ` with `createBottomTabNavigator ` from library `@react-navigation/material-bottom-tabs ` but not working this is solution with only `@react-navigation/bottom-tabs`
> 
> can you help me?

did you find any solution for materials bottom tabs?

**Comment by MHaris404** [comment]
> I tried to use `tabBar={() => null} ` with `createBottomTabNavigator ` from library `@react-navigation/material-bottom-tabs ` but not working this is solution with only `@react-navigation/bottom-tabs`
> 
> can you help me?

any update? did you find any solution?
