### ISSUE TITLE
@react-navigation/core is missing the `typescript` build folder

### ISSUE THREAD

**Issue by danilowoz** [react-navigation/react-navigation#8216]
**Current Behavior**
I'm trying to use the `useNavigation` from `@react-navigation/native'`, but typescript is not able to get the type from react-navigation/core, because the folder `lib/typescript` is missing there.

Path to types:
<img width="315" alt="Screenshot 2020-05-08 at 17 39 25" src="https://user-images.githubusercontent.com/4838076/81427586-e4c9d600-9152-11ea-85d4-d50a09e9bc02.png">

Lib folder missing `typescript` done:
<img width="172" alt="Screenshot 2020-05-08 at 17 39 15" src="https://user-images.githubusercontent.com/4838076/81427582-e4313f80-9152-11ea-88df-3c19e2609b90.png">

**Expected Behavior**
It has the proper folder on build

**How to reproduce**
Just set up the latest version of `core` and `native`

**Comment by AlphaJuliettOmega** [comment]
Indeed, none of these files exist:
/core/lib/module/index.js
/core/lib/module/index.js/index

etc

Why was this ticket closed but I just installed this and am seeing the error?

@satya164 that push you used to close this was just minor version bumps, how are those changes related to Typescript definition files not being generated at all?

Any help or advice would be appreciated.

**Comment by raajnadar** [comment]
Try to use the latest version of react navigation. [Bob](https://www.npmjs.com/package/@react-native-community/bob) creates the typescript folder inside the lib folder for the npm package.
