### ISSUE TITLE
Avoid unmount view when move between screen

### ISSUE THREAD

**Issue by Piero87** [react-navigation/react-navigation#8219]
How can avoid unmont view when return in a closed page? I'm explain better:

I go from:
A > B
B > A
A > B - here i want that B maintain the same state when I left, because is a search view and I want the user found again what he was searching for.

I read that a solution would be to use a SwitchNavigator, but it seems that with react-navigation v5 will be a little tricky, anyone can give me a solution?

thanks

**Comment by raajnadar** [comment]
You can use context api, keep some data and access it again when you need it. The data will be preserved between mount and unmount.

You can check React Js docs for Context API.

**Comment by ekatanata** [comment]
Really need this feature. It's not only about fetch data, but also about rendering some heavy components like Grid. I wrote the whole app with StackNavigator and now it seems like I need to refactor routing with logical incompatible TabNavigator with a custom top header. Just because I can't prevent unmount of it. Monkeys code.

**Comment by timnlupo** [comment]
@ekatanata Did you ever figure out a workaround?

**Comment by gurkerl83** [comment]
I would also be very interested in a solution. 
Looking at possibly relevant code places in the library, specifically the StackRouter, it is noticeable that Route B is taken from the stack array if navigating from View B towards View A. This is done at least on the Navigate actions.

A little experiment shows that the desired effect cannot be achieved so easily despite a modification of the routing logic. In the StackRouter the routes are allocated with predefined React keys, if these do not change, no corresponding render is executed in the React part of the library, the StackView and possibly other subcomponents.

So the effect is basically not achievable without adapting the source code, as far as my estimation goes.

Switches like detachInactiveScreens, and detachPreviousScreen, for example, have no effect on what happens, in my opinion.

**Comment by uladkasach** [comment]
@raajnadar is there a technical limitation in react-navigation that prevents this valid usecase? 

Your response gave an out-of-band solution that we'd have to hack on top of react-navigation. As mentioned by folks above, there are valid usecases that aren't solved by that recommendation either.

Can you please elaborate on why it is not possible to control stack screen mounting in a StackNavigator with react-navigation?
