### ISSUE TITLE
Nested doesn't navigate to screen in params

### ISSUE THREAD

**Issue by lLenn** [react-navigation/react-navigation#8220]
**Current Behavior**

Nested stack navigator doesn't navigate to screen but goes to initial route.
This seems to happen after navigating to a screen in a navigator nested 1 higher from a screen nested on the same level.

**Expected Behavior**

It should navigate to the screen that's provided with the params

**How to reproduce**

https://snack.expo.io/puXicKSIN
Press the button to do the navigation.

**Your Environment**

| software                               | version |
| ------------------------------ | ------- |
| Android |
| @react-navigation/native | 5.2.4
| @react-navigation/stack | 5.2.19
| react-native-gesture-handler | 1.6.0
| react-native-safe-area-context | 0.7.3
| react-native-screens | 2.7.0
| expo | 36.0.1

**Comment by lLenn** [comment]
New snack with updated packages: https://snack.expo.io/iL6bxrGB0

**Comment by raajnadar** [comment]
You gave wrong name in you navigation

```
function HomeScreen({ navigation }) {
  return (
    <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
      <Text>Home Screen</Text>
      <Button
        title="Go to Settings"
        onPress={() => {
          navigation.navigate('Root1', {
            screen: 'Settings1'                      <--- wrong name here
          });
        }}
      />
    </View>
  );
}
```

This is the corrected config.

**Comment by lLenn** [comment]
Yes, classic case of confirmation bias, my apologies.
I've since refactored the code and was able to make it work.
I can't seem to make a replication, so I must have done something wrong and it's not a bug.
Thanks for looking anyways and sorry for the inconvenience.
