### ISSUE TITLE
Old screen under custom header on iOS

### ISSUE THREAD

**Issue by guillaumeLamanda** [react-navigation/react-navigation#8223]
**Current Behavior**

On iOS, when I navigate to a screen with a custom header, I see the previous screen under my header.

I created a Snack for the example 
https://snack.expo.io/@glamanda/react-navigation-custom-header

![Simulator Screen Shot - iPhone 11 - 2020-05-09 at 13 39 13](https://user-images.githubusercontent.com/10440081/81472807-86583280-91fa-11ea-9564-a7ad5aa6bdda.png)

**Expected Behavior**

We should have a blank background under a custom header.

**How to reproduce**

https://snack.expo.io/@glamanda/react-navigation-custom-header

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | iPhone 11 (13.4.1)
| @react-navigation/native       | 5.2.6
| @react-navigation/stack        | 5.3.1
| react-native-gesture-handler   | 1.6
| react-native-safe-area-context | 0.7.3
| react-native-screens           | 2.2.0
| expo                           | 37.0.3

**Comment by guillaumeLamanda** [comment]
Verified on the snack with the latest packages

**Comment by angimenez** [comment]
Has there been progress? I have a similar problem with headerShown: false on a specific screen and the header from the previous screen is displayed.
    "@react-navigation/native": "^5.2.3",
    "@react-navigation/stack": "^5.2.18",

**Comment by satya164** [comment]
https://reactnavigation.org/docs/stack-navigator#set-headermode-to-screen
