### ISSUE TITLE
Can't perform a React state update on an unmounted component after app is sent to background

### ISSUE THREAD

**Issue by AronSoppe** [react-navigation/react-navigation#8226]
**Current Behavior**
- What code are you running and what is happening?
React Native init project with only React Navigation as the dependency. Code is quite similar as described in the [docs](https://reactnavigation.org/docs/hello-react-navigation). 

A well known React warning pops up after 'exiting' the app and after navigation has taken place. The warning below pops up after the app is pushed to the background in Android (and not fully exited). I've also tried navigating without the navigation prop. It made no difference.

`
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    in ForwardRef(BaseNavigationContainer) (at NavigationContainer.tsx:66)
`

No (huge) memory peak after the app is sent to background or when you reopen the app. The warning pops up in the developer console while the app is in background state and also shows when you open the app (see picture below). I guess a weird garbage collection issue? Something with a state in `BaseNavigationContainer`?

The warning:
<a target="_blank" href="https://imgur.com/Mg6GbNJ"><img src="https://i.imgur.com/Mg6GbNJ.png" title="source: imgur.com" /></a>

**Expected Behavior**

- What do you expect should be happening?
No '**`Can't perform a React state update on an unmounted component`**' warning when you reopen the app after it has been sent to the background.

**How to reproduce**
Code is on [Snack](https://snack.expo.io/@sickwubs/59db44). Does not happen in Snack because the code runs inside the Expo app. Try running the code on an Android phone or emulator. See GIF below on how you could reproduce this warning. I wonder if it's only on my end.

<a target="_blank" href="https://imgur.com/E6pxGAb"><img src="https://i.imgur.com/E6pxGAb.gif" title="source: imgur.com" /></a>

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Android 9 (emulator) and 10 (physical device)
| @react-navigation/native       | 5.3.0
| @react-navigation/stack | 5.3.2
| react-native-gesture-handler | 1.6.1
| react-native-reanimated | 1.8.0
| react-native-safe-area-context | 1.0.0
| react-native-screens | 2.7.0
| react-native                   | 0.62.2
| expo                           | no expo
| node                           | 12.16.3
| npm or yarn                    | yarn

**Comment by AronSoppe** [comment]
@raajnadar 
Here you go: https://github.com/AronSoppe/react-navigation-warning

Command used in /android subfolder:
`./gradlew clean`

Commands used in root folder:
`npx react-native run-android`
`npx react-native start --reset-cache`

**Comment by iamyellow** [comment]
hi! i also found with this warning just starting coding a new app, so in a very simple simple app. 
following the warning links, it seems is related to:
https://github.com/react-navigation/react-navigation/blob/master/packages/core/src/useNavigationBuilder.tsx#L370
https://github.com/react-navigation/react-navigation/blob/master/packages/core/src/useSyncState.tsx#L30

in `useNavigationBuilder` you're setting the state in an `useEffect` cleanup returned callback and i'm pretty sure that's the problem. 

hope this helps.

**Comment by AronSoppe** [comment]
@iamyellow You're right, that is indeed the reason why it is throwing that warning. Seems like it is related to issue [#8195](https://github.com/react-navigation/react-navigation/issues/8195).

**Comment by iamyellow** [comment]
happy to help, then. since i'm using hooks at some point i decided to make a simple `useSafeState` in order to avoid this kind of stuff. it just checks if the component is unmounted before setting the state. it became a life-saver because as the code grows and the warning messages are no obvious...

**Comment by AronSoppe** [comment]
> happy to help, then. since i'm using hooks at some point i decided to make a simple `useSafeState` in order to avoid this kind of stuff. it just checks if the component is unmounted before setting the state. it became a life-saver because as the code grows and the warning messages are no obvious...

Thanks! Though, this is in the core library of React Navigation. An async task is executed after unmount. Anyone of the React Navigation team who can comment on this?

**Comment by iamyellow** [comment]
sorry, @AronSoppe i thouht you was part of the team. hope they look at this soon, it's just a warning, but who knows the side effects.

**Comment by iamyellow** [comment]
searching about transparent background stuff, i came across this issue:
https://github.com/react-navigation/react-navigation/issues/7958
as soon as i remove the `background: 'transparent'` from `cardStyle` the warning went out.

**Comment by AronSoppe** [comment]
> sorry, @AronSoppe i thouht you was part of the team. hope they look at this soon, it's just a warning, but who knows the side effects.

No problem! 

> searching about transparent background stuff, i came across this issue:
> #7958
> as soon as i remove the `background: 'transparent'` from `cardStyle` the warning went out.

I haven't set that style option. You were right at first. I commented out setState in [useNavigationBuilder](https://github.com/react-navigation/react-navigation/blob/master/packages/core/src/useNavigationBuilder.tsx#L370) and the warning didn't show anymore. I'm pretty sure it has something to do with the timeout being executed after a navigator component is unmounted. The stacktrace mentions line 370, which is where setState is.
