### ISSUE TITLE
Unable to resolve module 'react-native-vector-icons/Ionicons' from App.js

### ISSUE THREAD

**Issue by GustavoMSevero** [react-navigation/react-navigation#8228]
Tab navigation doc do not show how to install react-native-vector-icons for who don't use expo. and every time i try to run my app, this error appers on the simulator 

> Unable to resolve module 'react-native-vector-icons/Ionicons'

So how to solve it?

**Comment by GustavoMSevero** [comment]
Hi @raajnadar!
See my codes on github...
[https://github.com/GustavoMSevero/ReactNative-TabNavigation](github)

This is my package.json
`{
  "name": "TabNavigation",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@react-native-community/masked-view": "^0.1.10",
    "@react-navigation/bottom-tabs": "^5.4.1",
    "@react-navigation/native": "^5.2.6",
    "react": "16.11.0",
    "react-native": "0.62.2",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-reanimated": "^1.8.0",
    "react-native-safe-area-context": "^0.7.3",
    "react-native-screens": "^2.7.0",
    "react-native-vector-icons": "^6.6.0"
  },
  "devDependencies": {
    "@babel/core": "^7.9.6",
    "@babel/runtime": "^7.9.6",
    "@react-native-community/eslint-config": "^1.1.0",
    "babel-jest": "^26.0.1",
    "eslint": "^7.0.0",
    "jest": "^26.0.1",
    "metro-react-native-babel-preset": "^0.59.0",
    "react-test-renderer": "16.11.0"
  },
  "jest": {
    "preset": "react-native"
  }
}`

**Comment by raajnadar** [comment]
You didn't add the fonts (ttf files) dynamically or manually.

Follow this steps https://github.com/oblador/react-native-vector-icons/issues/1117#issuecomment-589958315 add the code that I have in Automatic way at the very end, this place looks perfect https://github.com/GustavoMSevero/ReactNative-TabNavigation/blob/d2d03b70cedef827571d8c613cc198d0331f1dd0/android/app/build.gradle#L225.

After that `./gradlew clean` in `android` directory and run the app.

**Comment by GustavoMSevero** [comment]
@raajnadar, the problem is on iOS. On android runs perfect.
Add the fonts where? Because i did it on Xcode, manually.

**Comment by raajnadar** [comment]
Try this https://github.com/oblador/react-native-vector-icons#red-screen-with-unrecognized-font-family-error-on-ios

If that did not work open an issue in https://github.com/oblador/react-native-vector-icons

**Comment by GustavoMSevero** [comment]
Hi @raajnadar 
I tried to follow all the steps. But have some doubts.
How to do that "Check that the font you are trying to use appears in Info.plist, if you've added the whole folder and it's blue in color, then you need to add it to the path." I have to add one-by-one the fonts?
Then i run "rm -rf ios/build" and recompile the project but i get error
![Captura de Tela 2020-05-11 às 11 22 27 AM](https://user-images.githubusercontent.com/2678092/81573189-84b57880-937a-11ea-93eb-2aab46e9114d.png)

**Comment by alecpo** [comment]
It's not React Navigation's responsability teach you how to use react-native-vector-icons library. I suggest you to try looking for this in the react-native-vector-icons documentation properly, try to uninstall the lib (vector icons) and reinstall following all the steps. Read the document and probably you gonna find your solution. (I know that is a pain in the ass to install this library prop)
