### ISSUE TITLE
Upgrade react-native-safe-area-context to version 1.0.0

### ISSUE THREAD

**Issue by SaeedZhiany** [react-navigation/react-navigation#8229]
**Current Behavior**

- What code are you running and what is happening?

[th3rdwave/react-native-safe-area-context](https://github.com/th3rdwave/react-native-safe-area-context), one of peer dependencies of react-navigation has released the new major version 1.0.0 and has some break changes. so we can't upgrade it until the break changes resolved in this library

```
error: Error: Unable to resolve module `./InitialWindowSafeAreaInsets` from `node_modules\react-native-safe-area-context\src\index.tsx`:

None of these files exist:
  * node_modules\react-native-safe-area-context\src\InitialWindowSafeAreaInsets(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  * node_modules\react-native-safe-area-context\src\InitialWindowSafeAreaInsets\index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
    at ModuleResolver.resolveDependency (C:\Users\SAEED\workspace\MoeinMobile\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:163:15)
    at ResolutionRequest.resolveDependency (C:\Users\SAEED\workspace\MoeinMobile\node_modules\metro\src\node-haste\DependencyGraph\ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (C:\Users\SAEED\workspace\MoeinMobile\node_modules\metro\src\node-haste\DependencyGraph.js:287:16)
    at Object.resolve (C:\Users\SAEED\workspace\MoeinMobile\node_modules\metro\src\lib\transformHelpers.js:267:42)
    at C:\Users\SAEED\workspace\MoeinMobile\node_modules\metro\src\DeltaBundler\traverseDependencies.js:434:31
    at Array.map (<anonymous>)
    at resolveDependencies (C:\Users\SAEED\workspace\MoeinMobile\node_modules\metro\src\DeltaBundler\traverseDependencies.js:431:18)
    at C:\Users\SAEED\workspace\MoeinMobile\node_modules\metro\src\DeltaBundler\traverseDependencies.js:275:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (C:\Users\SAEED\workspace\MoeinMobile\node_modules\metro\src\DeltaBundler\traverseDependencies.js:87:24)

```

- Include a screenshot or video if it makes sense.

![Screenshot_1589171177](https://user-images.githubusercontent.com/13766432/81524135-4bbed900-9365-11ea-909a-014fecebc068.png)

**Expected Behavior**

- What do you expect should be happening?
 Applications should works like before after resolving the break changes.

- Include a screenshot or video if it makes sense.
-

**How to reproduce**
I tried to reproduce the problem on a new small project, but I didn't succeed so far. because I don't know what the exact usage of react-native-safe-area-context is in react-navigation. (although I used stack and drawer navigation in the project.) 
if anyone can reproduce the problem please share the link of the snack or repository.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | both
| @react-navigation/native       | 5.3.0
| react-native                   | 0.62.2
| expo                           | -
| node                           | 12.3.1
| npm or yarn                    | 6.12.0

**Comment by raajnadar** [comment]
Did you try clearing the cache. `npx react-native run-android --reset-cache`

**Comment by SaeedZhiany** [comment]
@raajnadar 

```bash
> npx react-native run-android --reset-cache
error: unknown option `--reset-cache'
```

**Comment by SaeedZhiany** [comment]
Also, I tried below steps,

1. `npm cache clean -f`
2. remove `node_modules` folder
3. `npm install`
4. `react-native start --reset-cache`
5. `react-native run-android`

it seems to work fine now, Thanks @raajnadar 

I close this issue.
