### ISSUE TITLE
URL not being updated correctly when navigating through

### ISSUE THREAD

**Issue by raduungurean** [react-navigation/react-navigation#8230]
**Current Behavior**

I am using a drawer navigator. Each drawer item uses its own stack navigator.
```
const Drawer = createDrawerNavigator(); 
const Stack1 = createStackNavigator(); 
const Stack2 = createStackNavigator(); 
const Stack3 = createStackNavigator(); 
```

This is the navigation container:

```
<NavigationContainer linking={LinkingConfiguration}>
  <Drawer.Navigator initialRouteName="Home">
    <Drawer.Screen name="Home" component={
      () => <Stack1.Navigator>
        <Stack1.Screen name="Home" component={HomeScreen}/>
      </Stack1.Navigator>
    }/>
    <Drawer.Screen name="Links" component={
      () => <Stack2.Navigator>
        <Stack2.Screen name="Links" component={LinksScreen}/>
      </Stack2.Navigator>
    }/>
    <Drawer.Screen name="New" component={
      () => <Stack3.Navigator>
        <Stack3.Screen name="New" component={NewScreen}/>
      </Stack3.Navigator>
    }/>
  </Drawer.Navigator>
</NavigationContainer>
```

Each of the 3 screens is looking like this:
```
export default function HomeScreen({navigation}) {
  return (
    <ScrollView style={styles.container} contentContainerStyle={styles.contentContainer}>
      <Text>HOME SCREEN</Text>
      <Button onPress={() => navigation.openDrawer()} title="open drawer" />
    </ScrollView>
  );
}
```

```
export default function LinksScreen({navigation}) {
  return (
    <ScrollView style={styles.container} contentContainerStyle={styles.contentContainer}>
      <Text>LINKS SCREEN</Text>
      <Button onPress={() => navigation.openDrawer()} title="open drawer" />
    </ScrollView>
  );
}
```

LinkConfiguration.js
```
import * as Linking from 'expo-linking';

export default {
  prefixes: [Linking.makeUrl('/')],
};
```

I am opening the drawer, and the URL is updating correctly.
When I am navigating to a screen that I already visited, the URL is not getting updated correctly.

**Expected Behavior**

When navigating to a DrawerItem, the URL should update accordingly.

**How to reproduce**

1. open app (home screen). The URL should be /Home/Home
2. programmatically open drawer (navigation.openDrawer())
3. click another drawer item. (Links)The URL is now /Links/Links
4. programmatically open drawer (navigation.openDrawer())
5. click Home drawer item. **The URL is now /Links/Links** instead of /Home/Home

![1-nav](https://user-images.githubusercontent.com/5908732/81552965-1201c880-938d-11ea-8894-e1fbda3778fe.PNG)
![2-nav](https://user-images.githubusercontent.com/5908732/81552973-162de600-938d-11ea-84a3-862c5e2c3fb9.PNG)

Note that when I open the drawer, the URL gets updated correctly and the Home item is selected inside the drawer. However if I toggle out the drawer, the URL is wrong again.

![3-nav](https://user-images.githubusercontent.com/5908732/81552981-1928d680-938d-11ea-9a8a-3e6014e2eeac.PNG)

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | web
| @react-navigation/native       |^5.2.1
| @react-navigation/drawer       |^5.7.2
| react-native-reanimated        |^1.8.0
| react-native-gesture-handler   |~1.6.0
| react-native-safe-area-context |0.7.3
| react-native-screens           |~2.2.0
| react-native                   |https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz
| expo                           |~37.0.9
| node                           |12.0.6
| npm or yarn                    |npm

**Comment by bruunoromero** [comment]
I'm having the exact same issue! The url is only updated when opening the drawer but not when navigating through the app. 

Also, this seems to happen only on drawer stuff... seems fine when navigating through nested stack routes

**Comment by raduungurean** [comment]
It has nothing to do with the tracker. It is related to the drawer. I removed the stacks flows from my test and it was still happening. Also If the drawer is permanent, it is working fine.

**Comment by raduungurean** [comment]
I've created a small repo on expo:

https://snack.expo.io/@raduungurean/react-navigation-drawer-bug

1. Open Drawer (the url is /Home)
2. Select another drawer item (the url changes correctly /Links)

**Comment by SleeplessByte** [comment]
I don't think it's necessarily the drawer. This also happens if you unmount a screen "programmatically" in a stack.

**Comment by raduungurean** [comment]
I ended up using a permanent drawer for the web version of the app only.

**Comment by mafortier-nexapp** [comment]
I got the same problem with these nested navigators:

Drawer -> Stack ---(in one of the screen)---> Tabs (3 screens)

If I navigate to another screen of the Stack navigator from the initial screen of the Tabs navigator, no problem. But if I navigate to another screen of the Stack navigator from a screen of the Tabs navigator that is not the initial screen, the URL stays the one of the Tabs' screen instead of becoming the one of the Stack's screen.

**Comment by buffaloDeveloper** [comment]
This issue is still not fixed.
