### ISSUE TITLE
Half screen white space when loading...

### ISSUE THREAD

**Issue by Bayramito** [react-navigation/react-navigation#8234]
Hi,

I have routing system like below,

`Stack Navigator > Material Top Tab Navigator > Material Bottom Navigator`

So when i load the screen its loading a specific screen in the Material Bottom Navigator.
I also added 2 screens to the both sides of the bottom navigator with Top tab navigator, so it can be swiped to these.

And finally i put all these into a stack navigator so in stack navigator i have some others screen where i dont want to have left or right functionality, and where i dont want to see bottom navigator. 

But in loading its rendering half of the screen empty white then. I dont know what to do in this case.

[Here is the video of the problem](https://www.youtube.com/watch?v=H9GituvSmuo)

**Comment by Bayramito** [comment]
Hello,

I hope this is enogh,

Becouse this is the navigation system that im loading ...
```

const B_Post = createMaterialBottomTabNavigator();
const T_Post = createMaterialTopTabNavigator();
const S_Post = createStackNavigator();
const ModalPlaceHolder = () => (
	<View style={{ flex: 1, backgroundColor: "blue" }} />
);
const NewPost = () => <View style={{ flex: 1, backgroundColor: "red" }} />;

const PostStackNavigator = ({ navigation, route }) => {
	return (
		<S_Post.Navigator mode="modal" screenOptions={{ headerShown: false }}>
			<S_Post.Screen name="Posts" component={PostTopNavigator} />
			<S_Post.Screen name="Notify" component={Notify} />
			<S_Post.Screen name="Search" component={Search} />
			<S_Post.Screen
				name="NewPost"
				options={{
					animationEnabled: true,
					gestureEnabled: true,
				}}
				component={NewPost}
			/>
		</S_Post.Navigator>
	);
};

const PostTopNavigator = ({ navigation, route }) => {
	return (
		<T_Post.Navigator
			initialRouteName="Posts"
			headerMode="float"
			tabBarOptions={{
				style: {
					height: 0, // hide the top tab bar
				},
			}}
		>
			<T_Post.Screen
				name="Camera"
				options={{ headerStyle: { height: 0 } }}
				component={Camera}
			/>
			<T_Post.Screen
				name="Posts"
				component={PostBottomNavigator}
			/>
			<T_Post.Screen
				name="Chat"
				component={ChatNavigator}
			/>
		</T_Post.Navigator>
	);
};

const PostBottomNavigator = ({ navigation, route }) => {
	return (
		<B_Post.Navigator
			initialRouteName="Posts"
			labeled={false}
			headerMode="float"
			shifting={true}
			style={{ backgroundColor: "#fff" }}
		>
			<B_Post.Screen name="Posts" component={Timeline} />
			<B_Post.Screen name="Discover" component={Profile} />
	
			<B_Post.Screen name="HomeTown" component={Profile} />
			<B_Post.Screen name="Profile" component={Profile} />
		</B_Post.Navigator>
	);
};
```

**Comment by Bayramito** [comment]
To help you out:

I may fixed the issue by adding 
`			initialLayout={{ width: Dimensions.get("window").width }}
`
into the material top tab navigator props.

**Comment by iomier** [comment]
> To help you out:
> 
> I may fixed the issue by adding
> ` initialLayout={{ width: Dimensions.get("window").width }} `
> into the material top tab navigator props.

it worked for me 
thanks

**Comment by satya164** [comment]
Closing since you didn't provide a runnable repro. Please open a new issue if you have a runnable repro.
