### ISSUE TITLE
Possible to Pass Redux Values to Navigation file? 

### ISSUE THREAD

**Issue by AndresTIY** [react-navigation/react-navigation#8239]
**Current Behavior**

So as a user, when I first log in, I'm taken to the HomeScreen. On this screen, there are these prompt values that come back from our API and thrown into Redux. These values determine whether or not I want to show these screens over the Home Screen.

I created a function to create a stack dynamically based on dummy data. It's working fine on my end, but I realized an issue when I tried to use the actual data. I need to pass these redux values over to my prompt-stack.js (which is a non react component so I can't use useSelector here... as far as I know?)

So here's an example of my code on the Home Screen, what causes the navigation to display this stack, the function that creates the stack, and the dummy data.

```js
import React, { useEffect } from 'react';

import { useSelector } from 'react-redux';

const Home = ({ navigation }) => {
  const { show_prompt1, show_prompt2, show_prompt3 } = useSelector(
    state => state.reducer,
  );
  useEffect(() => {
    if (show_prompt1 || show_prompt2 || show_prompt3) {
      navigation.navigate('PromptStack');
    }
  }, [show_prompt1, show_prompt2, show_prompt3]);

  return <View />;
};

// PROMPT STACK

import { Prompt1, Prompt2, Prompt3} from './screen-prompts'
import { createStackNavigator } from 'react-navigation-stack';

const dummyData = {
  show_prompt1: true,
  show_prompt2: true,
  show_prompt3: false,
};

const promptConfigs = [
  {
    id: 0,
    screenKey: 'Prompt1',
    screenName: Prompt1,
    valueToMatch: 'show_prompt1',
  },
  {
    id: 1,
    screenKey: 'Prompt2',
    screenName: Prompt2,
    valueToMatch: 'show_prompt2',
  },

  {
    id: 2,
    screenKey: 'Prompt3',
    screenName: Prompt3,
    valueToMatch: 'show_prompt3',
  },
];

const createRoutes = () => {
  let RouteConfigsObject = {};
  promptConfigs.forEach(item => {
    if (dummyData[item.valueToMatch]) {
      RouteConfigsObject = {
        ...RouteConfigsObject,
        [item.screenKey]: {
          screen: item.screenName,
        },
      };
    }
  });

  return RouteConfigsObject;
};

const RouteConfigs = createRoutes();
const initialRouteName = Object.keys(RouteConfigs)[0];

const NavigatorConfig = { initialRouteName };

const PromptStack = createStackNavigator(RouteConfigs, NavigatorConfig);

export default PromptStack;
How would I swap out the dummy data with the redux data instead in this situation or what else can I do to figure this out?
Thanks!
```
**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | both
| react-navigation               | 4.0.10 
| react-navigation-stack         | 2.3.11
| react-navigation-tabs          |  2.8.11
| react-navigation-drawer        | 
| react-native-reanimated        | 1.7.1
| react-native-gesture-handler   | 1.6.1
| react-native-safe-area-context | 0.7.3
| react-native-screens           | 2.4.0
| react-native                   | 0.61.2
| expo                           | na
| node                           | 13.11.0
| npm or yarn                    | yarn

**Comment by satya164** [comment]
Dynamic configuration is not possible with React Navigation 4. Use React Navigation 5.

**Comment by AndresTIY** [comment]
thought so. will eventually upgrade but that's going to be some work. thanks again satya! i came up with a different solution to handle this anyways
