### ISSUE TITLE
enableScreens(true) with react navigation make component flash

### ISSUE THREAD

**Issue by AnOptimistSeePessimist** [react-navigation/react-navigation#8242]
## Current Behavior

**enableScreens(true)**

![11](https://user-images.githubusercontent.com/27407218/80302376-421d6900-87dc-11ea-8092-db0a2fe3e8c2.gif)

**enableScreens(false)**
![12](https://user-images.githubusercontent.com/27407218/80302456-c07a0b00-87dc-11ea-8002-49516beb3a8e.gif)

## How to reproduce

https://snack.expo.io/@chengxiaodong1/reactnativescreens

**Comment by AnOptimistSeePessimist** [comment]
first issue: https://github.com/software-mansion/react-native-screens/issues/480

**Comment by Jalson1982** [comment]
I have notice glitch in bare react native project when I have stack navigator on Android when going back it has glitch like half second stops. So @osdnk is it possible somehow to prioritize this as it affects android devices a lot.

**Comment by brunohkbx** [comment]
Any updates on this?

**Comment by Jalson1982** [comment]
No still nothing. Simply react-native-screens do not work fine with react-navigation.

**Comment by jdlk07** [comment]
I've had the same issue as well and didn't realize that the cause was enableScreens.  Thanks!

Seems to occur whenever going back or popping a screen using the Stack Navigator.

**Comment by ovy9086** [comment]
This happens to me as well. Really degrades the experience after migrating to v5

**Comment by Jalson1982** [comment]
@osdnk @satya164 any idea or maybe to point us where to look for solution as it is not possible to use react native screens with navigation 5. Thanks in advance guys :)

**Comment by brunohkbx** [comment]
@AnOptimistSeePessimist did you found a solution?

**Comment by SageWu** [comment]
Maybe you can try this

**Comment by SageWu** [comment]
maybe you can try this

```
<Navigator
  screenOptions={({ navigation }) => {
    return {
      detachPreviousScreen: !navigation.isFocused(),
    }
  }}
>
  <Screen component={...} />
  <Screen component={...} />
</Navigator>
```

**Comment by kuasha420** [comment]
Why's this closed? It's definitely not fixed.

**Comment by siarheipashkevich** [comment]
Hi all. What the solution for this issue?

**Comment by joebernard** [comment]
In my case navigating back (tapping the < in the upper left of a stack) will pop the top screen then quickly flash that top (popped) screen for a split second. It is very reproducible on all my stacks.

I found two ways to resolve this:

Rolling back to `react-native-screens@2.15.2` seems to fix the issue. The problem first occurs in 2.17.0.

Also if I disable `react-native-screens` the problem goes away.

```javascript
enableScreens(false);
```

Relevant packages:
```
"react-native": "0.64.1",
"react-native-screens": "3.3.0",
"react-navigation": "4.4.4",
"react-navigation-props-mapper": "1.0.4",
"react-navigation-stack": "2.10.4",
"react-navigation-tabs": "2.11.1",
```

**Comment by kangfenmao** [comment]
Why's this closed? It's definitely not fixed.
