### ISSUE TITLE
Got null of undefined when logout 

### ISSUE THREAD

**Issue by ashkanghaderi** [react-navigation/react-navigation#8244]
**Current Behavior**

When i logout in my app after call api for logout in .then i navigate to login page like this:

dispatch(logout())
.then(() => {
navigation.reset({
index: 0,
routes: [{ name: 'AuthNavigator' }],
})
})
.catch((err) => {
console.log('err', err)
}
but it seems some pages are still mounted and i have got null of undefined issue because i'm clear redux store on logout succes.

![Simulator Screen Shot - iPhone 11 - 2020-05-12 at 15 25 27](https://user-images.githubusercontent.com/16876080/81770415-7344ab80-94f5-11ea-8dec-c954f459c13d.png)

**Expected Behavior**

I expect that after logout api call complete , could run this code without crash: 
  navigation.reset({
              index: 0,
              routes: [{ name: 'AuthNavigator' }],
            })

dispatch({ type: actionTypesAuth.LOGOUT.SUCCESS })

**How to reproduce**

**Your Environment**

"@react-navigation/bottom-tabs": "^5.4.2",
    "@react-navigation/compat": "^5.1.18",
    "@react-navigation/drawer": "^5.7.2",
    "@react-navigation/material-top-tabs": "^5.2.2",
    "@react-navigation/native": "^5.3.0",
    "@react-navigation/stack": "^5.3.3",

**Comment by raajnadar** [comment]
This has nothing to do with react navigation, this issue usually arise when you clear the logged in user's state and you did not perform checks for the variable if it exists or not.

**Comment by ashkanghaderi** [comment]
thnx dear raajnadar
but it seems after navigate still some pages remains live and has reference to redux store. why?

**Comment by raajnadar** [comment]
This happened to me also I didn't perform check for var called users which was in the logout page as soon as I cleared the users (context var) the var had null value. same thing is happening to you.

If you have a tab navigation see this option

https://reactnavigation.org/docs/bottom-tab-navigator/#lazy

https://reactnavigation.org/docs/material-top-tab-navigator/#lazy
