### ISSUE TITLE
Change height of header when keyboard appears on ios

### ISSUE THREAD

**Issue by ashkanghaderi** [react-navigation/react-navigation#8245]
**Current Behavior**

When taped on input and keyboard appears a white space between header and main layout showed and after keyboard disappeared the white space remain

![WhatsApp-Video-2020-05-13-at-8 58 39-AM](https://user-images.githubusercontent.com/16876080/81773829-7b551900-94fe-11ea-9530-92cbc13584c6.gif)

**Expected Behavior**

I expect that when keyboard appears navigation header update himself as reset of layout do

**How to reproduce**

**Your Environment**
using yarn

my navigation libs:

    "react": "16.9.0",
    "react-native": "0.61.5",
    .
    .
    .
    "react-native-safe-area-context": "^0.7.3",
    "react-native-safe-area-view": "^1.1.0",
    "react-native-screens": "^2.4.0",
.
.
.

"@react-navigation/bottom-tabs": "^5.4.2",
"@react-navigation/compat": "^5.1.18",
"@react-navigation/drawer": "^5.7.2",
"@react-navigation/material-top-tabs": "^5.2.2",
"@react-navigation/native": "^5.3.0",
"@react-navigation/stack": "^5.3.3",

**Comment by satya164** [comment]
Stop opening duplicate issues.
