### ISSUE TITLE
How do i use my current custom theme in class components?

### ISSUE THREAD

**Issue by rahulkasana** [react-navigation/react-navigation#8246]
I couldn't find any documentation for v5. I know this is no place to ask this question. But will the documentation be updated for this? Also can anyone tell me how to use it without hooks?

**Comment by satya164** [comment]
https://reactnavigation.org/docs/use-theme#using-with-class-component

**Comment by lylest** [comment]
facing the same problem

**Comment by rahulkasana** [comment]
What worked for me was maintaining a theme variable in redux persist storage. And create 2 sets of constants like.

`const DARK = {
  primary: '#000',
  secondary: "#fff",
  success: '#52c41a',
  ...
};

const LIGHT = {
  primary: '#fff',
  secondary: "#000",
  success: '#52c41a',
  ...
}
`
And using them like - 
`
const mapStateToProps = state => {
  const {theme} = state;
  return {theme};
};
`
`
<Text style={{fontSize: 16, color: theme.primary}}>Continue</Text>
`
This seemed like a better approach to me for class Components.

Otherwise wrapping each class component function with a wrapper seemed quite tedious when presentation components are already wrapped by redux logic. 
And if you try to wrap the top level Navigator you still have to use the hook
`  const { colors } = useTheme();`
