### ISSUE TITLE
[V5] @react-navigation/native. Can't refresh in web version after build

### ISSUE THREAD

**Issue by jackychanfox** [react-navigation/react-navigation#8247]
In dev mode, I can refresh or go any links without issue.

But after build and run it using http-server, can't refresh or link to any other links.

I added .htaccess file in the same folder which includes index.html 

```
Options -MultiViews
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^ index.html [QSA,L]
```

**Comment by satya164** [comment]
Your server setup is unrelated to React Navigation.

**Comment by markholland** [comment]
@jackychanfox Did you solve this?

**Comment by akshgods** [comment]
@jackychanfox how you solved it?

@satya164  why you close it if cant have answer?
