### ISSUE TITLE
Non-centred tab icons and text on React Native Web

### ISSUE THREAD

**Issue by sohcah** [react-navigation/react-navigation#8248]
**Current Behavior**
When using a Material Bottom Tab Navigator on React Native Web, the icons and text in the tabs are no longer centred. This was broken in a recent commit where the navigator started using Links.
This is not very noticeable in the example due to the amount of tabs, however when limiting to 2 or 3 tabs it is more noticable. 
![2020-05-13 14 52 16 react-navigation-example netlify app 5b839212f045](https://user-images.githubusercontent.com/51970078/81821271-95f0b780-9529-11ea-839c-a08bc6c93d82.png)

**Expected Behavior**
The icons and text in the tabs should be centered on Web.
![2020-05-13 14 52 47 react-navigation-example netlify app bc9410be43d6](https://user-images.githubusercontent.com/51970078/81821279-97ba7b00-9529-11ea-9ddb-e33444fac8f8.png)

**How to reproduce**
Go to https://react-navigation-example.netlify.app/material-bottom-tabs/Article/Article?author=Gandalf and look. The icons and text in the tab sections are not centred.

**Your Environment**
| software                               | version |
| -------------------------------------- | ------- |
| iOS or Android                         | React Native Web
| @react-navigation/native               | 5.3.0
| @react-navigation/material-bottom-tabs | 5.2.2
| react-native-paper                     | 3.10.1
| react-native                           | https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz
| expo                                   | 37.0.3
| node                                   | 12.4.0
| npm or yarn                            | yarn 1.19.0

**Comment by sohcah** [comment]
After experimenting a bit, a simple fix is to add {display:"flex",justifyContent:"center"} to the styles of the Link component.

**Comment by sohcah** [comment]
Why was this closed?

**Comment by raajnadar** [comment]
Here you can check they are properly aligned https://react-navigation-example.netlify.com/material-bottom-tabs/Article/Article?author=Gandalf

Without the workaround you gave, this means the issue is in you code if you can provide a repro I will reopen it.

**Comment by sohcah** [comment]
It looks proper, but it isn't. Here is a screenshot from that page... not perfectly centered. 
![image](https://user-images.githubusercontent.com/51970078/81823069-cfc2bd80-952b-11ea-8926-6483dd4d9036.png)
