### ISSUE TITLE
Header not shown for Drawer Navigator inside stack navigator

### ISSUE THREAD

**Issue by rahulkasana** [react-navigation/react-navigation#8249]
**Current Behavior**
I'm using a drawer navigator nested inside a stack navigator. In drawer navigator the header is remaining constant as the name of Parent stack screen name.

**Expected Behavior**
In drawer navigator the header title should change for each screen.

**How to reproduce**
    <NavigationContainer>
      <AppStack.Navigator>
        {!authenticated ? (
          <AppStack.Screen name={NAVIGATE.HOME} component={DrawerNavigator} />
        ) : (
          <AppStack.Screen name={NAVIGATE.SIGN_IN} component={SignIn} />
        )}
      </AppStack.Navigator>
    </NavigationContainer>

Also this is my drawer navigator------------
export default function DrawerNavigator() {
  return (
    <>
      <Drawer.Navigator initialRouteName="Home">
        <Drawer.Screen
          name="Home"
          options={{title: 'My home'}}
          component={HomeScreen}
        />
        <Drawer.Screen
          name="Notifications"
          options={{title: 'Notification'}}
          component={NotificationsScreen}
        />
      </Drawer.Navigator>
    </>
  );
}

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | iOS
| @react-navigation/native       | 5.3.0
| @react-navigation/drawer       | 5.7.2
| react-native-reanimated        | 1.8.0
| react-native-gesture-handler   | 1.6.1
| react-native-safe-area-context |
| react-native-screens           | 2.7.0
| react-native                   | 0.62.2
| expo                           |
| node                           | 12.12.0
| npm or yarn                    | 6.11.3

**Comment by satya164** [comment]
Drawer navigator doesn't show header. You need to nest a stack navigator if you want header.
