### ISSUE TITLE
[iOS] Top of Flatlist is hidden when don't use mode='modal'

### ISSUE THREAD

**Issue by ggunti** [react-navigation/react-navigation#8250]
**Current Behavior**
It happens only on iOS.

When I press the "Comment" button, I navigate to a new screen named "Comments":
<img width="317" alt="Captură de ecran din 2020-05-13 la 17 17 21" src="https://user-images.githubusercontent.com/26307699/81824313-03a6de80-953e-11ea-9aa2-d69c1bb59787.png">

The problem is that inside "Comments" screen, the first element of the Flatlist is hidden (not visible), like below:
<img width="317" alt="Captură de ecran din 2020-05-13 la 17 18 45" src="https://user-images.githubusercontent.com/26307699/81824332-0acdec80-953e-11ea-8644-df276e9d43fb.png">

If I set `mode='modal'` to the stack navigator, it works as expected. But why?:
<img width="317" alt="Captură de ecran din 2020-05-13 la 17 32 47" src="https://user-images.githubusercontent.com/26307699/81826037-01458400-9540-11ea-9de1-e0b8270a5929.png">

**Expected Behavior**
I expect to not cut the first element of the Flatlist also when I do not set `mode='modal'`.

**How to reproduce**

- You must provide a way to reproduce the problem. If you are having an issue with your machine or build tools, the issue belongs on another repository as that is outside of the scope of React Navigation.
- Either re-create the bug on [Snack](https://snack.expo.io) or link to a GitHub repository with code that reproduces the bug.
- Explain how to run the example app and any steps that we need to take to reproduce the issue from the example app.
- Keep the repro code as simple as possible, with the minimum amount of code required to repro the issue.
- Before reporting an issue, make sure you are on latest version of the package.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | iOS 13.3
| @react-navigation/native       | ^5.3.0
| @react-navigation/stack        | ^5.3.3
| react-native-gesture-handler   | ^1.6.1
| react-native-safe-area-context | ^0.7.3
| react-native-screens           | ^2.4.0
| react-native                   | 0.62.0
| expo                           | -
| node                           | v10.15.3
| npm or yarn                    | npm 6.13.7

**Comment by ggunti** [comment]
Still exists after upgrading to latest versions (I edited my initial post).

**Comment by satya164** [comment]
Closing since you didn't provide a runnable repro. Please open a new issue if you have a runnable repro.
