### ISSUE TITLE
Property 'replace' does not exist on type 'NavigationProp<Record<string, object>, string, NavigationState, {}, {}>'

### ISSUE THREAD

**Issue by BrandonMA** [react-navigation/react-navigation#8256]
**Current Behavior**

If you try to use replace on the navigation object it will complain that the function does not exist, if you use // @ts-ignore it will work.

**Expected Behavior**

As it is a feature of the library itself, it should be available on default types the same way navigate is.

I know it is possible to solve it with the types guide on the docs, but that is a workaround and not a fix.

**How to reproduce**
```
const navigation = useNavigation();
navigation.replace('route');
```

**Environment**
@react-navigation/native: 5.3.0

**Comment by BrandonMA** [comment]
Still a bug even on the latests 5.3.0 version

**Comment by terrierscript** [comment]
FYI: I can solve this with `StackNavigationProp`

```ts
const navigation =  useNavigation<StackNavigationProp<{route: {} }>>()
navigation.replace('route');
```

**Comment by satya164** [comment]
> I know it is possible to solve it with the types guide on the docs, but that is a workaround and not a fix

It's how you do it is as per the docs. It's not an workaround.

**Comment by bryantobing12** [comment]
> I know it is possible to solve it with the types guide on the docs, but that is a workaround and not a fix.

can you link the possible solve in the docs?
