### ISSUE TITLE
Extra navigation after reset to screen with `animationEnabled: false` on app start on Android

### ISSUE THREAD

**Issue by Bardiamist** [react-navigation/react-navigation#8257]
**Current Behavior**

I call `navigationContainerRef.current?.reset` on app start for navigate to screen with `animationEnabled: false` on Android. After reset that navigate forward to initial screen.

**Notes**

`onStateChange` fires twice
No problems on iOS.
I tested on Android 5.0 and on Android 10.0.

**Expected Behavior**

Shouldn't extra navigation.

**How to reproduce**

I created [minimal repro repository](https://github.com/Bardiamist/NavigationReset)

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |iOS
| @react-navigation/native       |5.3.0
| @react-navigation/stack        |5.3.3
| react-native-gesture-handler   |1.6.1
| react-native-safe-area-context |1.0.0
| react-native-screens           |2.7.0
| react-native                   |0.62.2
| expo                           |-
| node                           |14.2.0
| npm or yarn                    |yarn 1.22.4

**Comment by pix2D** [comment]
Not sure if related but this causes an infinite loop on Android for me (the 2nd screen automatically goes back to the 1st screen, which decides it should again go to the 2nd screen etc). Removing `animationEnabled: false` from the initial screen fixes it.

**Comment by lvanhala** [comment]
we have the same problem

**Comment by Bardiamist** [comment]
@satya164 reason?

**Comment by satya164** [comment]
Fixed in https://github.com/react-navigation/react-navigation/commit/1f27e4b1f659e59ad15ecbf44b4fb0a80cae302f

<img width="408" alt="Screen Shot 2020-06-08 at 10 54 59" src="https://user-images.githubusercontent.com/1174278/84011520-89b81880-a976-11ea-8a36-d73e7fc7eded.png">
