### ISSUE TITLE
Cannot inject custom props via React.cloneElement on a descriptors[route.key].render()

### ISSUE THREAD

**Issue by rclai** [react-navigation/react-navigation#8258]
**Current Behavior**

- What code are you running and what is happening?
I have a custom navigator, and I'd like to inject some custom props into the scene, but for some reason those props are not being sent through when doing `React.cloneElement`. This was possible in v4.

**Expected Behavior**

- What do you expect should be happening?
I expect my custom props to be accessible in my route component.

**How to reproduce**

https://snack.expo.io/@rclai/custom-navigator-no-custom-prop-injection
App.js line 52
components/AssetExample.js line 11

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |  iOS 13.3
| @react-navigation/native       | ~5.1.7~ 5.3.0
| react-native                   | 0.61.0
| expo                           | N/A
| node                           | v10.15.3
| npm or yarn                    | yarn

**Comment by rclai** [comment]
The issue is still there even after upgrading to `5.3.0`.

**Comment by satya164** [comment]
It's not supported. You have 2 approaches:

- Before passing the `children` prop to `useNavigationBuilder`, wrap the components in some kind of HOC to pass additional props
- Use the context API to pass additional data

**Comment by Slapbox** [comment]
It's majorly surprising that you can't even pass props to a navigator. It seems completely at odds with constructing the navigators as React components. I'm sure there's a good reason but it's very counterintuitive.

**Comment by Slapbox** [comment]
It's majorly surprising that you can't pass props to a navigator without obliterating React-Navigation's props. It seems completely at odds with constructing the navigators as React components. I'm sure there's a good reason but it's very counterintuitive.
