### ISSUE TITLE
screen is not defined

### ISSUE THREAD

**Issue by Lyd1223** [react-navigation/react-navigation#8259]
**Current Behavior**
I want to navigate to a nesting navigator. I try to navigate from scanPage to equimentInfo or from warnData to workOrderDetail, it will show screen is not defined.
But if I press the bottom tabs, and then I can navigate to that screen, which I want to go.

 bottomNavigator
   home(Stack.Navigator)
      overView(screen)
      scanPage (screen)
   data(Stack.Navigator)
     assets(screen)
     equimetInfo(Tab.Navigator)
     warnData(screen)
  workOrder(Stack.Navigator)
     workOrderDetail(screen)
     workOrderLog(screen)

**Expected Behavior**

 navigate to the screen

**How to reproduce**

 `this.props.navigation.navigate('WorkOrder', {screen: 'WorkOrderPage', params: {type:typeInfo, operatorType: 'add', warnInfo}})`

**Your Environment**

| software                      | version |
| ----------------------------- | ------- |
| iOS or Android                | 13.4.1
| @react-navigation/native      | 5.1.4
| @react-navigation/bottom-tabs | 5.2.5
| react-native-screens          |  2.4.0
| react-native                  |  0.62.0
| expo                          | N/A
| node                          | 10.16.3
| npm or yarn                   |  npm

**Comment by Lyd1223** [comment]
![WechatIMG18](https://user-images.githubusercontent.com/49749583/82020746-41ca0c80-96bc-11ea-9893-3aad5fae758e.jpg)
This occur error， please help me, how can I fix this problem?

**Comment by satya164** [comment]
Closing since you didn't provide a runnable repro. Please open a new issue if you have a runnable repro.
