### ISSUE TITLE
Should Tab.Screen inherit params from Tab.Navigator? (v5)

### ISSUE THREAD

**Issue by JulianKingman** [react-navigation/react-navigation#8262]
**Current Behavior**

Given:
```javascript
const TabScreen1 = ({route}) => {
  console.log(route.params);
  return null;
}

const TabNavigator = () => (
  <Tab.Navigator initialRoute="TabScreen1">
    <Tab.Screen component={TabScreen1} name="TabScreen1" />
  </Tab.Navigator>
)
```

1. Navigate to TabNavigator, with params {params: 'example'}
2. Log params on TabScreen1, they are undefined

Sidenote: this probably applies to other navigator types

**Expected Behavior**

1. Navigate to TabNavigator, with params {params: 'example'}
2. Params are inherited, logs {params: 'example'}

**How to reproduce**

Snack: https://snack.expo.io/@buishi/tabnavigatorparams

**Unwieldy solution**
I can get around this by using this:
```javascript
const parentState = navigation.dangerouslyGetParent().dangerouslyGetState();
console.log('parent params', parentState.routes[parentState.index].params);
```
But for some reason this seems dangerous 🤔 

**Your Environment**

| software                      | version |
| ----------------------------- | ------- |
| iOS or Android                |
| @react-navigation/native      | 5.3.2
| @react-navigation/bottom-tabs | 5.4.4
| react-native-screens          | 2.2.0
| react-native                  |
| expo                          | 37.0.0
| node                          | v12.4.0
| npm or yarn                   | 6.14.3

**Comment by JulianKingman** [comment]
Yes, still exists

**Comment by hongsa** [comment]
still exist too

**Comment by raajnadar** [comment]
While navigating you should also specify the name of the screen, something like this

```
navigation.navigate('TabNavigator', {
  screen: 'TabScreen1', // The screen inside the nested navigation
  params: {
    example: 'example', // And pass params like this
  },
})
```

Reference https://reactnavigation.org/docs/params/#passing-params-to-nested-navigators

**Comment by satya164** [comment]
You should expose such stuff using React Context. Params shouldn't be automatically passed to children.

Imagine changing params somewhere in a parent forced all of the children to re-render regardless if they use it. It'd be pretty expensive.

**Comment by rgoldiez** [comment]
As @satya164 said, we had this same need and easily solved it with context.
