### ISSUE TITLE
Params persist across multiple navigation even if not re-specified

### ISSUE THREAD

**Issue by rams23** [react-navigation/react-navigation#8263]
**Current Behavior**

I set up the standard tab navigator with nested stack navigator as the example [here](https://reactnavigation.org/docs/tab-based-navigation). When I navigate to a page of another stack with params and press go back the params are persisted at tab level so the second time I repeat the operation the params are still there even if the navigation action does not contains any params.
Same if i use deep link to a specific page in the stack, and then renavigate to the deep link target screen.

Here the resulting navigation state, with the params at tab level persisted obviously even if the stack index changes.

![image](https://user-images.githubusercontent.com/11600164/81996662-de08fa80-964d-11ea-8f5f-602b15863a1c.png)

**Expected Behavior**

- I would expect to not have the params persisted across navigation especially if the page has been destroyed and then re-navigating to that page

Here a [expo snack](https://snack.expo.io/@rams23/d74f7b) and a [repo ](https://github.com/rams23/react-navigation-params-error) with the repro example 
you can use this deep link to test the behaviour 
`adb shell am start -a android.intent.action.VIEW -d "myapp://profile?a=b&c=d"
`
Just go to the settings page press "Go to home Details with params", then back to the homePage, settings tabs and "Go to home Details", you can see that params are still there.

![video_2020-05-15_01-40-25](https://user-images.githubusercontent.com/11600164/81996467-6509a300-964d-11ea-8da5-0b00f973f8ac.gif)

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |
| @react-navigation/native       | ^5.3.2
| @react-navigation/bottom-tabs | ^5.4.4
| @react-navigation/stack | ^5.3.5
| react-native                   |  0.62.2
| expo                           |
| node                           | v10.15.0
| npm or yarn                    | 6.12.1

**Comment by mauroerta** [comment]
I'm facing the same issue of @rams23 in my project.
I have a screen that accepts two params, articleId and commentId, the deep link configuration of this screen looks like this:
```
[ARTICLE_SCREEN]: {
  /**
   * Accept query params:
   * @example
   * example://article/11111/22222
   */
  path: 'article',
  path: 'article/:articleId/:commentId'
  params: {
    articleId: (articleId: string) => articleId,
    commentId: (commentId: string) => commentId,
  },
},
```
I tried to set the deep link configuration in this way, but the same issue appear, and the navigation params persist even if I navigate in another screen and the come back in the same screen without override the params.
i tried to change the settings in different ways:
```
path: 'article',
```
And the make a test passing the params as a query params like this:
`example://article?articleId=11111&commentId=22222`
but the result is always the same.
According the documentation [here](https://reactnavigation.org/docs/configuring-links) the configuration seems correct, so i think there is a bug.

**Comment by lorenzoangelini** [comment]
I follow this discussion, i also have encountered the same issue

**Comment by BrianCerasuolo** [comment]
I'm seeing a similiar problem when i push the same screen to a stack and go back. For example if i call navigate.push('Detail', { leg: 1}), and then do navigate.push('Detail', {leg: 2}) and then go back, it remains and leg 2 instead of giving me leg 1

**Comment by thomasarogers** [comment]
same issue

**Comment by swizes** [comment]
I hate to write this down but same issue

**Comment by alexlpdj** [comment]
Same with me, passing param only in one point of the app, but this param remains the same even if i call navigate with the param setted to null, can't find any solution

**Comment by rainst** [comment]
same issue, I've tried also using `setParams` to clear the params after using them but on the next navigation without specifying any the old params are delivered.. :(

**Comment by AM-77** [comment]
Same issue.

**Comment by tkyr-hh** [comment]
I'm facing the same issue over and over again, but I found a solution "not very clever", but it fixed the issue for.
For instance, if you are navigating from ScreenOne to ScreenTwo, you need to pass some params like so: 
`navigation.navigate('ScreenTwo', { paramOne: 'foo', paramTwo: 'foo2'  })`.

Then, if you would like to navigate from ScreenThree to ScreenTwo, you can override these params by: 
`navigation.navigate('ScreenTwo', { paramOne: undefined, paramTwo: undefined, paramsThree: 'foo3'  })`.
I hope that answer helps.

**Comment by raajnadar** [comment]
This issue is solved in the react-navigation v6, the v6 does not merge params instead it overrides the params. You can read the docs linked below to get more info.

https://reactnavigation.org/docs/upgrading-from-5.x#params-are-now-overwritten-on-navigation-instead-of-merging

**Comment by GuidoGagliardini** [comment]
same issue here

**Comment by cph2117** [comment]
i'm using v6 (@react-navigation/native 6.1.7, and @react-navigation/stack 6.2.5) and have the same issue specifically when deep-linking for push notifications

**Comment by syllasrangel** [comment]
I had a similar issue and solved it using [navigation.reset()](https://reactnavigation.org/docs/navigation-prop/#reset).

**Comment by MnariMohamed** [comment]
really ? still not fixed

**Comment by pinge** [comment]
I'm not sure if this is a generic solution for all use cases, but the following works for me, give it a shot.

The idea is to clear (on mount) the sticky `navigate()` `params` for nested navigators in the screen that is reappearing.

This also works with deep linking (e.g. `Linking.getInitialUrl()`). When dismissing the screen (in my case a modal), both `navigation.pop()` and `navigation.goBack()` work correctly.

```tsx
export function SomeScreen({ navigation }: SomeScreenProps) {
  // ...

  useEffect(
    () => {
      const clear = { screen: undefined, params: undefined, state: undefined, path: undefined }
      navigation.getParent('root')?.setParams(clear)
      navigation.getParent('tabs')?.setParams(clear)
    },
    [navigation]
  )

  // ...
}
```

This works with the following nested navigators (simplified example):

```tsx
<NavigationContainer>
  <RootStack.Navigator id="root">
    <Tab.Navigator id="tabs">
       <NestedStack.Navigator>
         <NestedStack.Screen name="SomeScreen" component={ SomeScreen } />
       </NestedStack.Navigator>
    </Tab.Navigator>
  </RootStack.Navigator>
</NavigationContainer>
```
