### ISSUE TITLE
Does Drawer.Screen have listeners? If not, should it?

### ISSUE THREAD

**Issue by JulianKingman** [react-navigation/react-navigation#8264]
**Current Behavior**

```javascript
<Drawer.Screen
        name="HelpCenter"
        component={HelpCenter}
        listeners={{
          onItemPress(e) {
            console.log('item pressed'); // doesn't run
            e.preventDefault();
        }}
/>
```

**Expected Behavior**

Allow overriding Drawer.Screen onPress without completely customizing the component
The issue with the [supported way](https://reactnavigation.org/docs/drawer-navigator#drawercontent), adding DrawerItem's, is that any custom DrawerItem has to go either at the beginning or end of the list, can't go in the middle.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |
| @react-navigation/native       |5.3.2
| @react-navigation/drawer       |5.7.4
| react-native-reanimated        |1.7.0
| react-native-gesture-handler   |1.6.0
| react-native-safe-area-context |1.0.0
| react-native-screens           |2.0.0
| react-native                   |
| expo                           |37.0.11
| node                           |v12.4.0
| npm or yarn                    |6.14.3

**Comment by himrocks33** [comment]
Has anyone found a work around for this yet?  Besides creating a custom drawer?

**Comment by richlewis14** [comment]
Would be interested in hearing about peoples solutions to this issue, I would like to be able to run this for example when a user clicks on a particular item in a drawer

      navigation.dispatch(
        CommonActions.reset({
          index: 0,
          routes: [{name: 'Home'}],
      }),
              );

**Comment by satya164** [comment]
https://reactnavigation.org/docs/drawer-navigator/#draweritempress
