### ISSUE TITLE
How to prevent swipe function when using draggable component?

### ISSUE THREAD

**Issue by Bayramito** [react-navigation/react-navigation#8266]
Hello,

I have a quick question. Is there any method or way to prevent tab swiping functionality if we use draggable/swipeable component in one of our screens? 

For example instagram feeds. If there is multiple images you can swipe to right without swipe the entire screen. As you know when you swipe to the right it goes to Direct Messages. 

I think you got the idea, how to disable swiping option when we use a nested draggable or swipeable component in the screen?

**Comment by binhnt12** [comment]
Have you tried flatlist or scrollview from react-native-gesture-handler yet?

**Comment by Bayramito** [comment]
> Have you tried flatlist or scrollview from react-native-gesture-handler yet?

yes  i did
