### ISSUE TITLE
swipe back action in stack navigation white screen and drawer menu opening problem

### ISSUE THREAD

**Issue by bugraonucyildiz** [react-navigation/react-navigation#8270]
**Current Behavior**

     `<NavigationContainer >
        <Drawer.Navigator drawerContent={props => <DrawerContent instagramUrl={this.state.instagramUrl} youtubeUrl={this.state.youtubeUrl}  {...props} />}>
          <Drawer.Screen name="HomeDrawer" component={MainTabScreen} />
        </Drawer.Navigator>
      </NavigationContainer>`

When scrolling from top to bottom on the bottom screens, it comes back, and scrolling from top to bottom on the main screen becomes a white screen.
 
In addition, the side menu opens by dragging horizontally on any screen.

**Expected Behavior**

 The horizontal menu should be opened from the icon in the top bar.
no need to drag the screen from top to bottom to come back on any screen

 
**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Android 9
| @react-navigation/native       | ^5.3.2
| @react-navigation/stack        | ^5.3.6
| react-native-gesture-handler   | ^1.6.0
| react-native-safe-area-context | ^0.7.3
| react-native-screens           | ^2.0.0-beta.8
| react-native                   | 0.62.0
| expo                           |
| node                           | v12.16.1
| npm or yarn                    | 6.13.4

**Comment by bugraonucyildiz** [comment]
> The versions mentioned in the issue for the following packages differ from the latest versions on npm:
> 
> * `@react-navigation/native` (found: `5.0.0`, latest: `5.3.2`)
> * `@react-navigation/stack` (found: `5.0.0`, latest: `5.3.6`)
> 
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?

I added the latest versions, the problem still exists

**Comment by raajnadar** [comment]
To stop opening the drawer with swipe use this api

https://reactnavigation.org/docs/drawer-navigator/#swipeenabled

For white screen issue add a repro.

**Comment by BooYeu** [comment]
I have same problem . I can't set "swipeEnabled" props to a Stack.Screen

**Comment by raajnadar** [comment]
`swipeEnabled` is for drawer read the docs carefully @BooYeu

**Comment by satya164** [comment]
Closing since you didn't provide a runnable repro. Please open a new issue if you have a runnable repro.
