### ISSUE TITLE
Drawer Object.fromEntries is not a function

### ISSUE THREAD

**Issue by claudiofus** [react-navigation/react-navigation#8272]
**Current Behavior**
- What code are you running and what is happening?
I'm new to React Native and I'm using Expo to build and test my app on multiple devices. I'm using a react-navigation drawer, stack and native but for iOS I have the error attached.

- Include a screenshot or video if it makes sense.
![error](https://user-images.githubusercontent.com/18471299/82140264-f97f2b80-982e-11ea-8bd0-1bb056472a2c.png)

**Expected Behavior**

- What do you expect should be happening?
The error appears only for iOS while in Android there's no problem of this kind.
I've inspected the error with Sentry and I found `TypeError Object.fromEntries is not a function. \node_modules\@react-navigation\core\src\getPathFromState.tsx in createNormalizedConfigs at line 232:17`

**How to reproduce**
```
const AppDrawer = createDrawerNavigator();
const AppDrawerScreen = () => (
  <AppDrawer.Navigator>
    <AppDrawer.Screen name="Home" component={Nav.HomeStackScreen} />
    <AppDrawer.Screen name="Categorie" component={Nav.CategoryStackScreen} />
    <AppDrawer.Screen name="Impostazioni" component={Nav.SettingsStackScreen} />
  </AppDrawer.Navigator>
);

export default () => (
  <NavigationContainer initialRouteName="Home">
    <AppDrawerScreen />
  </NavigationContainer>
);
```
Then in another file:
```
const HomeStack = createStackNavigator();
const HomeStackScreen = ({ navigation }) => (
  <HomeStack.Navigator>
    <HomeStack.Screen
      name="Home"
      component={Homepage}
      options={{
                headerTitle: 'Home',
                headerLeft: () => <NavigationDrawerStructure navigationProps={navigation} />
            }}
    />
  </HomeStack.Navigator>
);

const CategoryStack = createStackNavigator();
const CategoryStackScreen = ({ navigation }) => (
  <CategoryStack.Navigator>
    <CategoryStack.Screen
      name="Category"
      component={QuizIndex}
      options={{
                headerTitle: 'Categorie',
                headerLeft: () => <NavigationDrawerStructure navigationProps={navigation} />
            }}
    />
    <CategoryStack.Screen
      name="Quiz"
      component={Quiz}
    />
  </CategoryStack.Navigator>
);

const SettingsStack = createStackNavigator();
const SettingsStackScreen = ({ navigation }) => (
  <SettingsStack.Navigator>
    <SettingsStack.Screen
      name="Settings"
      component={Settings}
      options={{
                headerTitle: 'Impostazioni',
                headerLeft: () => <NavigationDrawerStructure navigationProps={navigation} />,
            }}
    />
    <SettingsStack.Screen name="ActionDetails" component={Settings} />
  </SettingsStack.Navigator>
);
```

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS                 | 10.3.3
| @react-navigation/native       | 5.3.2
| @react-navigation/drawer       |5.7.4
| react-native-reanimated        |1.8.0
| react-native-gesture-handler   |1.6.1
| react-native-safe-area-context |0.7.3
| react-native-screens           |2.7.0
| react-native                   |https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz
| expo                           |37.0.11
| node                           |10.16.0
| npm or yarn                    |6.14.5

**Comment by claudiofus** [comment]
I've tried to update to the latest version but same error occurs.

**Comment by vijay86-git** [comment]
I'm getting the same issue, after updated the latest versions. @claudiofus did you find the solution ?

**Comment by claudiofus** [comment]
Not yet, I've tried to:
-  revert to old version

- deleted `node_modules` and `package-lock.json` 

- uninstall the app from the iPhone

but nothing changed. 

 The last chance is to create a new project, copy and paste my code. In package core https://github.com/react-navigation/react-navigation/blob/master/packages/core/CHANGELOG.md#570-2020-05-16 seems they have fixed the issue but I'm not sure.

**Comment by vijay86-git** [comment]
code is working properly on android but getting the issue on ios.

**Comment by claudiofus** [comment]
The same happens for me!

**Comment by majorhayes** [comment]
I'm seeing the same error but in the Android simulator after upgrading from 5.3 to 5.4.

**Comment by raajnadar** [comment]
Try updating to the latest version and clear the cache for expo `yarn start -c` for react native `npx react-native run-android --reset-cache`

**Comment by claudiofus** [comment]
I've cleared cache as suggested from @raajnadar  with `expo start --clear` and it worked.

**Comment by vijay86-git** [comment]
cleared cache and its working.. thanks a lot..
