### ISSUE TITLE
Remove MaterialCommunityIcons from source

### ISSUE THREAD

**Issue by mschipperheyn** [react-navigation/react-navigation#8274]
**Current Behavior**

The library imports MaterialCommunityIcons by default.
This forces both an additional weight and style of icon use (font based icons) that is imho undesirable.

**Expected Behavior**

Icons are generally custom. Offering an out of the box preloading of icons may offer convenience but at the expense of loading (a prob relatively large) functionality that is likely not used. Material design is great, but many libraries that use it don't consider it the way it should be: a great default and scaffolding for further customization but not an out of the box "have-to-use-and-look-like" structure.

**How to reproduce**

Not applicable

**Your Environment**

| software                               | version |
| -------------------------------------- | ------- |
| iOS or Android                         | both
| @react-navigation/native               | 5.3.2
| @react-navigation/material-bottom-tabs | 5.2.4
| react-native-paper                     | 2.16.0
| react-native                           | 61.x
| expo                                   | 37
| node                                   | 16.4
| npm or yarn                            | yarn

**Comment by satya164** [comment]
Material Bottom Tabs uses React Native Paper which uses the `MaterialCommunityIcons` by default. Removing it from here doesn't change anything.

If you want it to be optional, you should open an issue in paper's repo.
