### ISSUE TITLE
navigate does not work from headerRight

### ISSUE THREAD

**Issue by rostgoat** [react-navigation/react-navigation#8275]
I am showing a button on a certain Tab in my Stack Navigator. When I click on the button, I want to navigate to that screen. Instead I get an error locally, but no error or output in my [snack](https://snack.expo.io/FRNMPQaNQ)

Has anyone had this issue?

Local Error:

```
console.error: The action 'NAVIGATE' with payload {"name":"ProfileEditScreen"} was not handled by any navigator.

Do you have a screen named 'ProfileEditScreen'?

```

**Current Behavior**

above error

**Expected Behavior**

Should navigate to specified screen

**How to reproduce**

[snack](https://snack.expo.io/FRNMPQaNQ)

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | ios
| @react-navigation/native       | ^5.2.3
| @react-navigation/stack        | ^5.2.14
| react-native-gesture-handler   | ^1.6.1
| react-native-safe-area-context | ^0.7.3
| react-native-screens           | ^2.7.0
| react-native                   | 0.62.2
| expo                           |
| node                           | v12.3.1
| npm or yarn                    | 6.14.4

**Comment by rostgoat** [comment]
issue persists after update to latest versions

**Comment by rostgoat** [comment]
I have included a minimal repro above

**Comment by satya164** [comment]
You don't have a screen named 'ProfileEditScreen' like the error says.

**Comment by rostgoat** [comment]
What do you mean, it's right there..

![Screenshot from 2020-05-18 13-40-31](https://user-images.githubusercontent.com/22672124/82257602-2efa4680-990d-11ea-8fe3-5fa320c4cf74.png)

**Comment by satya164** [comment]
You just made a file named `ProfileEditScreen` without specifying such a screen in the navigator.

**Comment by rostgoat** [comment]
Oh I forgot to add a Screen for it! Derp..thanks
