### ISSUE TITLE
 shifting="true" not working 

### ISSUE THREAD

**Issue by c-obsesie** [react-navigation/react-navigation#8280]
**Current Behavior**

Hi I ve got the code attached and I am trying to make my bottom navigator to change its background color in accordance with the tab selected. Reading the documentation I've seen that in order to do that i need to change shifting status to true. I change it but no luck. 

If I add another tab to bottom navigation is working, the colors are changing in accordance with the tab selected.

Thank you
```
`
const TabsScreen = () => (
  <Tabs.Navigator
    shifting="true"
    //barStyle={{backgroundColor: '#694fad'}}
    initialRouteName="Home"
    activeColor="#fff">
    <Tabs.Screen
      name="Home"
      component={Browser}
      options={{
        tabBarLabel: 'Home',
        tabBarColor: '#009387',
        tabBarIcon: ({color}) => (
          <MaterialCommunityIcons name="home" color={color} size={26} />
        ),
      }}
    />
    <Tabs.Screen
      name="Sleep"
      component={Sleep}
      options={{
        tabBarLabel: 'Updates',
        tabBarColor: '#1f65ff',
        tabBarIcon: ({color}) => (
          <MaterialCommunityIcons name="sleep" color={color} size={26} />
        ),
      }}
    />
    <Tabs.Screen
      name="Settings"
      component={SettingWithContext}
      options={{
        tabBarLabel: 'Profile',
        tabBarColor: '#694fad',
        tabBarIcon: ({color}) => (
          <MaterialCommunityIcons name="settings" color={color} size={26} />
        ),
      }}
    />
  </Tabs.Navigator>
);`

```

 "@fortawesome/fontawesome-svg-core": "^1.2.28",
    "@fortawesome/free-solid-svg-icons": "^5.13.0",
    "@fortawesome/react-native-fontawesome": "^0.2.3",
    "@react-native-community/masked-view": "^0.1.9",
    "@react-native-community/slider": "^2.0.9",
    "@react-navigation/bottom-tabs": "^5.2.7",
    "@react-navigation/drawer": "^5.5.0",
    "@react-navigation/material-bottom-tabs": "^5.2.5",
    "@react-navigation/native": "^5.4.0",
    "@react-navigation/stack": "^5.2.11",
    "react-native": "0.62.2",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-paper": "^3.10.1",
    "react-native-vector-icons": "^6.6.0",
    "react-navigation-material-bottom-tabs": "^2.2.12",
    "react-slider": "^1.0.4"

**Comment by satya164** [comment]
It's boolean, not a string.
