### ISSUE TITLE
Release note commit hash links aren't valid

### ISSUE THREAD

**Issue by EmpireJones** [react-navigation/react-navigation#8282]
The release notes commit links don't have valid URLs.

For example, the release notes for @react-navigation/core@5.7.0:
https://github.com/react-navigation/react-navigation/releases/tag/%40react-navigation%2Fcore%405.7.0

Has a link for the commit 51f4d11 as:
https://github.com/react-navigation/react-navigation/tree/master/packages/core/commit/51f4d11fdf4bd2bb06f8cd4094f051816590e62c

**Comment by raajnadar** [comment]
Fixed here https://github.com/react-navigation/react-navigation/issues/8423
