### ISSUE TITLE
ModalPresentationIOS Double Header

### ISSUE THREAD

**Issue by bfraiman** [react-navigation/react-navigation#8283]
TransitionPresets.ModalPresentationIOS Gives me double header on nested stacks. How to fix it?

This is the [example](https://snack.expo.io/CZRUQ5jvm?platform=android&name=createStackNavigator+%7C+React+Navigation&dependencies=%40react-native-community%2Fmasked-view%40%5E0.1.7%2C%40react-navigation%2Fbottom-tabs%40%5E5.4.5%2C%40react-navigation%2Fdrawer%40%5E5.7.5%2C%40react-navigation%2Fmaterial-bottom-tabs%40%5E5.2.5%2C%40react-navigation%2Fmaterial-top-tabs%40%5E5.2.5%2C%40react-navigation%2Fnative%40%5E5.4.0%2C%40react-navigation%2Fstack%40%5E5.3.7%2Creact-native-paper%40%5E3.10.1%2Creact-native-reanimated%40%5E1.7.0%2Creact-native-safe-area-context%40%5E0.7.3%2Creact-native-screens%40%5E2.4.0%2Creact-native-tab-view%40%5E2.14.0&sourceUrl=https%3A%2F%2Freactnavigation.org%2Fexamples%2F5.x%2Fstack-modal-presentation.js&fbclid=IwAR29vWrrcHPGczs1WB4x7a-w9N7pk2_Nc3T8Z7Ec4_aA56WIQs18E-wyQo8)

![98119656_10221930258421904_432357091919790080_n](https://user-images.githubusercontent.com/31390603/82272959-8373e500-9952-11ea-9029-076191666f3c.jpg)

**Comment by zainbinfurqan** [comment]
double header means please show pic of what kind of header you getting

**Comment by davidlruizc** [comment]
Hey, I faced the same issue, found the solution in this [issue](https://github.com/react-navigation/react-navigation/issues/7723#issuecomment-601754805). 

Just add on Screen Options `headerStatusBarHeight: 0`.

Hope it helps you.

**Comment by Dallas62** [comment]
> This is already documented https://reactnavigation.org/docs/stack-navigator#transitionpresets

Hi @satya164 
In the v6 documentation, with the link provided, `headerStatusBarHeight` is no more documented.
This "issue" is still present in v6.
Regards

**Comment by satya164** [comment]
> This "issue" is still present in v6.
Regards

It's set automatically in v6. Please open a new issue with repro of it's still present.

**Comment by marshal-truman** [comment]
> This is already documented https://reactnavigation.org/docs/stack-navigator#transitionpresets

This helped. Thanks.
