### ISSUE TITLE
web url update wrong when navigate between tab and stack

### ISSUE THREAD

**Issue by bestv2** [react-navigation/react-navigation#8284]
**Current Behavior**

- when navigate between tab.screen and statck.screen with linking, the web url goes wrong
-  ![image](https://user-images.githubusercontent.com/443689/82276173-18102e80-99b7-11ea-9f53-f47bbbf3779d.png)

**Expected Behavior**

- Detail page's url should be 'detail' not to be cart
- I make a repo at [https://snack.expo.io/@bestv2/linking-web](https://snack.expo.io/@bestv2/linking-web)

**How to reproduce**
1. click the bottom Cart, url update to 'cart'
2. click the bottom Me, url update to 'me'
3. click the bottom Home, url update to 'home'
4. click the 'navigate to stack detail page' btn, url update to 'cart', it should be 'detail'

**Your Environment**

| software                      | version |
| ----------------------------- | ------- |
| iOS or Android                |web
| @react-navigation/native      |5.4.0
| @react-navigation/bottom-tabs |5.4.5
| @react-navigation/stack |5.3.7
| react-native-screens          |2.7.0
| react-native                  |0.62

**Comment by bestv2** [comment]
> The versions mentioned in the issue for the following packages differ from the latest versions on npm:
> 
> * `@react-navigation/stack` (found: `5.3.6`, latest: `5.3.7`)
> 
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?

update to 5.3.7, same problem

**Comment by bestv2** [comment]
In my situation, tab in stack navigator, this will fix my problem.
`@react-navigation/core/useLinking` file
```js
const getStateLength = state => {

  let length = 0;
  if (state.history) {
    length = state.history.length;
  } else {
    length = state.index + 1;
  }
  const focusedState = state.routes && state.routes[state.index] ? state.routes[state.index].state : null;

  if (focusedState && !focusedState.stale) {
    // If the focused route has history entries, we need to count them as well
    length += getStateLength(focusedState) - 1;
  } else if (state.index > 0 && state.type === 'stack') {
    // add to fix this bug
    // sum tab and stack history length
    for (let i = 0; i < state.index; i++) {
      state.routes[i] && state.routes[i].state && (length += getStateLength(state.routes[i].state) - 1)
    }
  }
  return length;
};
```

**Comment by code-artisan** [comment]
> In my situation, tab in stack navigator, this will fix my problem.
> `@react-navigation/core/useLinking` file
> 
> ```js
> const getStateLength = state => {
> 
>   let length = 0;
>   if (state.history) {
>     length = state.history.length;
>   } else {
>     length = state.index + 1;
>   }
>   const focusedState = state.routes && state.routes[state.index] ? state.routes[state.index].state : null;
> 
>   if (focusedState && !focusedState.stale) {
>     // If the focused route has history entries, we need to count them as well
>     length += getStateLength(focusedState) - 1;
>   } else if (state.index > 0 && state.type === 'stack') {
>     // add to fix this bug
>     // sum tab and stack history length
>     for (let i = 0; i < state.index; i++) {
>       state.routes[i] && state.routes[i].state && state.routes[i].state.type === 'tab'  && (length += getStateLength(state.routes[i].state) - 1)
>     }
>   }
>   return length;
> };
> ```

The file path should be `@react-navigation/native/useLinking`, not `@react-navigation/core/useLinking`

**Comment by bestv2** [comment]
> > In my situation, tab in stack navigator, this will fix my problem.
> > `@react-navigation/core/useLinking` file
> > ```js
> > const getStateLength = state => {
> > 
> >   let length = 0;
> >   if (state.history) {
> >     length = state.history.length;
> >   } else {
> >     length = state.index + 1;
> >   }
> >   const focusedState = state.routes && state.routes[state.index] ? state.routes[state.index].state : null;
> > 
> >   if (focusedState && !focusedState.stale) {
> >     // If the focused route has history entries, we need to count them as well
> >     length += getStateLength(focusedState) - 1;
> >   } else if (state.index > 0 && state.type === 'stack') {
> >     // add to fix this bug
> >     // sum tab and stack history length
> >     for (let i = 0; i < state.index; i++) {
> >       state.routes[i] && state.routes[i].state && state.routes[i].state.type === 'tab'  && (length += getStateLength(state.routes[i].state) - 1)
> >     }
> >   }
> >   return length;
> > };
> > ```
> 
> The file path should be `@react-navigation/native/useLinking`, not `@react-navigation/core/useLinking`

Thanks, you are right. It's my fault.
