### ISSUE TITLE
Nested Material Top Tab causes container to re-render on click

### ISSUE THREAD

**Issue by andrewcharnley** [react-navigation/react-navigation#8287]
**Current Behavior**

When a top tab is nested clicking any of it's tabs with a dummy view container causes the container for the nested tabs to re-render. This causes a large stutter of about 1s. Possibly the click event is bubbling to the parent or something similar.

**Expected Behavior**

The container shouldn't reload.

**How to reproduce**

Stick a nested material-top-tab inside of another. Stick a console.log to see the render fire when you click any second level tab.

  "dependencies": {
    "@react-native-community/masked-view": "^0.1.7",
    "@react-navigation/material-top-tabs": "^5.2.5",
    "@react-navigation/native": "^5.1.4",
    "@react-navigation/stack": "^5.2.9",
    "buffer": "^5.6.0",
    "react": "16.11.0",
    "react-native": "0.62.0",
    "react-native-ble-plx": "^2.0.0",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-picker-select": "^7.0.0",
    "react-native-reanimated": "^1.7.1",
    "react-native-safe-area-context": "^0.7.3",
    "react-native-screens": "^2.4.0",
    "react-native-tab-view": "^2.13.0"
  },

**Comment by andrewcharnley** [comment]
To comply with the bot... 

 "dependencies": {
    "@react-native-community/masked-view": "^0.1.10",
    "@react-navigation/material-top-tabs": "^5.2.5",
    "@react-navigation/native": "^5.4.0",
    "@react-navigation/stack": "^5.3.7",
    "buffer": "^5.6.0",
    "react": "16.11.0",
    "react-native": "^0.62.2",
    "react-native-ble-plx": "^2.0.0",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-picker-select": "^7.0.0",
    "react-native-reanimated": "^1.8.0",
    "react-native-safe-area-context": "^1.0.2",
    "react-native-screens": "^2.7.0",
    "react-native-tab-view": "^2.13.0"
  },

**Comment by satya164** [comment]
Closing since you didn't provide a runnable repro. Please open a new issue if you have a runnable repro.
