### ISSUE TITLE
blur listener not calling when setting animationEnabled to false to the stack navigator

### ISSUE THREAD

**Issue by Vali06** [react-navigation/react-navigation#8289]
**Current Behavior**

I'm trying to clear the state when the screen it's no longer focused, so I'm listening to blur events like this. 

  `React.useEffect(() => {
        const unsubscribe = props.navigation.addListener('blur', () => {
            clearState();
        });
        return unsubscribe;
    }, []);`

I've disabled animations in my app by setting animationEnabled to false in the screenOptions for my Stack Navigator and because of that this listener won't get called when the screen unmounts, it only gets called if you navigate to another screen so the screen stays mounted.

Here is the snack: https://snack.expo.io/ZArtIyGjm

**Expected Behavior**

The clearState function doesn't get called if the screen unmounts. It only gets called if the screen looses focus by navigating to another screen

**Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Android, haven't tested on iOS
| @react-navigation/native       | 5.4.0
| @react-navigation/stack        | 5.3.7
| react-native-gesture-handler   | 1.6.0
| react-native-safe-area-context | 0.7.3
| react-native-screens           | 2.4.0
| react-native                   | 0.61.5
| npm or yarn                    | yarn

**Comment by Vali06** [comment]
I've created a snack as you requested. I've realized that the issue it's actually that the blur listener, doesn't get called when the screen gets unmounted, but it gets called if you navigate to another screen, having animationEnabled set to false. If you have it, set to true, the listener gets called when the screen gets unmounted too.

Here is the snack: https://snack.expo.io/ZArtIyGjm

**Comment by satya164** [comment]
It's expected. You should use `useFocusEffect`'s cleanup function instead of listening to `focus` and `blur` events directly https://reactnavigation.org/docs/use-focus-effect

**Comment by Vali06** [comment]
How can it be expected? Why does animationEnabled have an impact on such logic?

**Comment by satya164** [comment]
If you disable animations, you screen unmounts immediately and there's no listener by the time the events fire.

Regardless, it's a bug in your code that you aren't handling cleanup when the component unmounts. What happens if the whole navigator gets unmounted if you don't handle cleanup properly?

There's already `useFocusEffect` which is supposed to handle all of these cases transparently. Just use it instead of listening to focus/blur manually.

> It doesn't work with useFocusEffect either.

```js
useFocuseEffect(
  React.useCallback(() => {
    return () => {
     // Run cleanup
    }
  }, [])
);
```

Also, maybe stop downvoting replies if you're looking for helpful answers. It's unnecessarily rude.

**Comment by Vali06** [comment]
Got it, my bad. Didn't know that the useFocusEffect cleanup function gets called when screen blurs, somehow I've missed that.

It was just weird how you've stated that it's expected without any explanation cause it didn't make sense why animationEnabled would have an impact on that. Have a good day! :)
