### ISSUE TITLE
Android: stackNavigator nested in tabNavigator makes keyboardAvoidingView not working properly

### ISSUE THREAD

**Issue by GGrassiant** [react-navigation/react-navigation#8290]
**Current Behavior**
My app has a MaterialBottomTabNavigator that has a nested StackNavigator. In this StackNavigator, I have 3 screens.

- The first one has no header and is just plain content + links to the 2 other screens
- SignIn page
- SignUp page

```
// AuthNavigator
const AuthStackNavigator = createStackNavigator();

export const AuthNavigator = () => {
  return (
    <AuthStackNavigator.Navigator
      initialRouteName={WELCOME_PAGE.id}
      screenOptions={{
        headerShown: false,
        headerTintColor: colors.primary,
      }}
      lazy>
      <AuthStackNavigator.Screen
        name={WELCOME_PAGE.id}
        component={WELCOME_PAGE.component}
      />
      <AuthStackNavigator.Screen
        name={LOGIN_PAGE.id}
        component={LOGIN_PAGE.component}
        options={LOGIN_PAGE.options}
      />
      <AuthStackNavigator.Screen
        name={SIGN_UP_PAGE.id}
        component={SIGN_UP_PAGE.component}
        options={LOGIN_PAGE.options}
      />
    </AuthStackNavigator.Navigator>
  );
};
```

```
// AuthTabNavigator
const AuthTabNavigator =
  Platform.OS === 'android'
    ? createMaterialBottomTabNavigator()
    : createBottomTabNavigator();

const RootNavigator = () => {
  return (
    <AuthTabNavigator.Navigator
      activeColor={colors.primary}
      inactiveColor="grey"
      barStyle={materialBottomNavBackgroundColor}
      tabBarOptions={defaultTabNavOptions}>
      <AuthTabNavigator.Screen
        name={WELCOME_PAGE.id}
        component={AuthNavigator}
        options={WELCOME_PAGE.options}
      />
    </AuthTabNavigator.Navigator>
  );
};

export default RootNavigator;
```

- What code are you running and what is happening?

In both SignIn and Signup, I wrap the fields in a keyboardAvoidingView. On iOS, there are no issues but on Android, the behaviour onPress is very clunky and onDimiss the keyboardAvoidingView seems to be 'jumping'. It appears as if when dismissing the keyboard, a first calculation for the height is made and then re-computed causing the view to translate twice.

I tried 3 different implementations using the keyBoardAvoidView boilerplate from the [React Native CLI documentation](https://reactnative.dev/docs/keyboardavoidingview) and figured it must be an issue with react-navigation and not the keyboardAvoidingView component.

- Include a screenshot or video if it makes sense.

I documented the issue [here](https://stackoverflow.com/questions/61856752/react-native-android-keyboardavoidingview-in-stacknavigator-within-a-tabnavi) and you can find 3 videos here:

- [base version](https://recordit.co/tcEwDbo1oT)

- [no header version](https://recordit.co/O4lZ9G83vg)

- [not nested in a tab navigator](https://recordit.co/uh7mOGlKdk)

I get the proper behaviour when I am not nesting the stack in a tabNavigator (i.e. when I get rid of the tabNavigator all together for Android).

**Expected Behavior**

- What do you expect should be happening?

I should see similar behaviour on ios and Android, not see the 'jump' when dismissing the keyboard on Android

- Temporary solution

As a workaround, I took inspiration from [react-native-spacer](https://github.com/ambistudio/react-native-spacer) by creating a custom KeyboardSpacer that I can better control, I also edited the AndroidManifest.xml
```android:windowSoftInputMode="adjustUnspecified"``` and added a background colour to the view because I still get a double computation causing the view not to reposition smoothly.

I created a [Gist with the temporary solution for my app](https://gist.github.com/GGrassiant/eac2c84b02359341aaae632e23883ee9).

**How to reproduce**
I created a bare bone Gist with:

- tabNavigator (main entry point)
- stackNavigator (nested element)
- Screen with the input fields and the keyBoardAvoidingView (from the React Native CLI)

https://gist.github.com/GGrassiant/393a31c2f8c1f81da366b77834dddfe5

It's very similar to what I used for the quick videos above.

**Your Environment**

My package.json is as follows:
```
"@react-navigation/bottom-tabs": "^5.2.8",
"@react-navigation/drawer": "^5.7.2",
"@react-navigation/material-bottom-tabs": "^5.1.10",
"@react-navigation/native": "^5.1.7",
"@react-navigation/stack": "^5.2.17",
"react": "16.11.0",
"react-native": "0.62.2",
"react-native-gesture-handler": "^1.6.1",
"react-native-paper": "^3.9.0",
"react-native-reanimated": "^1.8.0",
"react-native-safe-area-context": "^0.7.3",
"react-native-screens": "^2.7.0",
```

Thanks in advance :)

**Comment by GGrassiant** [comment]
I upgraded to the above message's deps and tried again but still the same issue.

**Comment by satya164** [comment]
This issue has been opened several times. If you search previous issues in the repo, you can learn why it works like that.

**Comment by GGrassiant** [comment]
Thanks!
