### ISSUE TITLE
custom header area affect to after 2 depth origin header

### ISSUE THREAD

**Issue by makearts** [react-navigation/react-navigation#8292]
**Current Behavior**
![AnyConv com__화면 기록 2020-05-20 오후 2 27 25](https://user-images.githubusercontent.com/22754824/82408951-a49a1a00-9aa7-11ea-8f86-fc2971566fee.gif)

**Expected Behavior**

i use custom header at the first screen so i expect other original header will work normally except custom header. But when i use custom header it affect to after 2 depth screen. custom header makes margin (or padding) to original header. and when i go back from 3 dept > 2dept that problem margin just appear after 2sec??

**How to reproduce**

![스크린샷 2020-05-20 오후 2 36 26](https://user-images.githubusercontent.com/22754824/82408784-508f3580-9aa7-11ea-8951-f82f70e6aa24.png)
hear is my code that routes 

![스크린샷 2020-05-20 오후 2 39 30](https://user-images.githubusercontent.com/22754824/82409001-c2677f00-9aa7-11ea-8aa3-e2ec414f5f5b.png)
and this is my custom header code

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |  13.4.1 / Android 10
| @react-navigation/native       | 5.1.6
| @react-navigation/stack        | 5.2.11
| react-native-gesture-handler   | 1.6.1
| react-native-safe-area-context | 0.7.3
| react-native-screens           | 2.5.0
| react-native                   | 0.62.2
| expo                           |
| node                           |  14.2.0
| npm or yarn                    | 6.14.4

**Comment by makearts** [comment]
> The versions mentioned in the issue for the following packages differ from the latest versions on npm:
> 
> * `@react-navigation/native` (found: `5.1.6`, latest: `5.4.0`)
> * `@react-navigation/stack` (found: `5.2.11`, latest: `5.3.7`)
> 
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?

yes i update , but bug is still alive

**Comment by satya164** [comment]
https://reactnavigation.org/docs/stack-navigator#header
