### ISSUE TITLE
Back arrow hidden on Android

### ISSUE THREAD

**Issue by mtnptrsn** [react-navigation/react-navigation#8293]
**Current Behavior**
In a nested stack navigator, the back arrow on Android is not visible. I tried both on a physical device and in an emulator. I'm using Expo and followed the official documentation to install (https://reactnavigation.org/docs/getting-started/#installing-dependencies-into-an-expo-managed-project)

![Screenshot_1589956220](https://user-images.githubusercontent.com/684179/82412646-32710780-9a9e-11ea-8f16-969c69189cff.png)

**Expected Behavior**

The back arrow on Android is visible.

**How to reproduce**

1. Initiate a new expo project
2. Install react-navigation following this guide: https://reactnavigation.org/docs/getting-started/#installing-dependencies-into-an-expo-managed-project
3. Set up a stack navigator
4. Navigate within the stack navigator

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Android 9
| @react-navigation/native       | 5.4.0
| @react-navigation/stack        | 5.3.7
| react-native-gesture-handler   | 1.6.1
| react-native-safe-area-context | 0.7.3
| react-native-screens           | 2.2.0
| react-native                   | 0.61.4
| expo                           | 37.0.8
| node                           | 10.20.1
| npm or yarn                    | yarn 1.13.0

**Comment by mtnptrsn** [comment]
Updated native and stack to the latest versions and the problem still persist.

**Comment by gavrichards** [comment]
I can confirm I see this too. Although it doesn't happen in the emulator, only on a real device.
The issue is not occurring in the iOS simulator.

**Comment by satya164** [comment]
React Navigation doesn't do anything special for back button image. If you're facing issue, open a bug report in expo forums.

**Comment by craftzdog** [comment]
Had the same issue on iOS without expo, but this worked for me:
https://github.com/facebook/react-native/issues/29279#issuecomment-658244428
