### ISSUE TITLE
Header title not changing 

### ISSUE THREAD

**Issue by c-obsesie** [react-navigation/react-navigation#8294]
**Current Behavior**
Hi, so I 've got nested navigation, as the code shows. Now I am trying to make the header bar. however, when I change the screens from bottom navigation the header remains the same, no matter on what screen I am(always shoes that I am on Browser screen).  Also is the React navigation header the best to create a header bar or is better to create a fully custom one. Thank you

**Expected Behavior**
I am expecting that the header title will change in accordance with the page.

**How to reproduce**

`
const Stack = createStackNavigator();
const Tabs = createMaterialBottomTabNavigator();
const AuthStack = createStackNavigator();

const TabsScreen = () => (
  <Tabs.Navigator shifting={true} initialRouteName="Home" activeColor="#fff">
    <Tabs.Screen
      name="Home"
      component={Browser}
      options={{
        tabBarLabel: 'Home',
        tabBarColor: '#009387',
        tabBarIcon: ({color}) => (
          <MaterialCommunityIcons name="home" color={color} size={26} />
        ),
      }}
    />
    <Tabs.Screen
      name="Sleep"
      component={Sleep}
      options={{
        tabBarLabel: 'Sleep',
        tabBarColor: '#694fad',
        tabBarIcon: ({color}) => (
          <MaterialCommunityIcons name="sleep" color={color} size={26} />
        ),
      }}
    />
    <Tabs.Screen
      name="Settings"
      component={SettingWithContext}
      options={{
        tabBarLabel: 'Settings',
        tabBarColor: '#694fad',
        tabBarIcon: ({color}) => (
          <MaterialCommunityIcons name="settings" color={color} size={26} />
        ),
      }}
    />
  </Tabs.Navigator>
);

export default CreateStack = () => {
  const [isLoading, setIsLoading] = React.useState(true);
  const [userToken, setUserToken] = React.useState(null);

  const authContext = React.useMemo(() => {
    return {
      signIn: () => {
        setIsLoading(false);
        setUserToken('asdf');
      },
      signUp: () => {
        setIsLoading(false);
        setUserToken('asdf');
      },
      signOut: () => {
        setIsLoading(false);
        setUserToken(null);
      },
    };
  }, []);

  React.useEffect(() => {
    setTimeout(() => {
      setIsLoading(false);
    }, 1000);
  }, []);

  if (isLoading) {
    return <LoadingScreen />;
  }
  return (
    <AuthContext.Provider value={authContext}>
      <NavigationContainer>
        {userToken ? (
          <Stack.Navigator initialRouteName={Browser}>
            <Stack.Screen name="Browser" component={TabsScreen} />
            <Stack.Screen name="PreScreen" component={PreScreen} />
            <Stack.Screen name="Player" component={Player} />
          </Stack.Navigator>
        ) : (
          <AuthStack.Navigator
            screenOptions={{headerShown: false}}
            initialRouteName={RegisterLogin}>
            <AuthStack.Screen name="RegisterLogin" component={RegisterLogin} />
            <AuthStack.Screen name="Login" component={LoginWithContext} />
            <AuthStack.Screen name="Register" component={RegisterWithContext} />
          </AuthStack.Navigator>
        )}
      </NavigationContainer>
    </AuthContext.Provider>
  );
};
`

**Your Environment**

"react-native-community/masked-view": "^0.1.9",
    "@react-navigation/bottom-tabs": "^5.4.5"
    "@react-navigation/material-bottom-tabs": "^5.2.5",
    "@react-navigation/native": "^5.4.0",
    "@react-navigation/stack": "^5.3.7",
    "react": "16.11.0",
    "react-native": "0.62.2",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-paper": "^3.10.1",
    "react-native-reanimated": "^1.8.0",
    "react-native-safe-area-context": "^0.7.3",
    "react-native-screens": "^2.5.0",
    "react-slider": "^1.0.4"

**Comment by c-obsesie** [comment]
https://drive.google.com/open?id=1vRWKvgmnAAcDs4sBB9oaXOc1SRPBoOv8
https://drive.google.com/open?id=1nvGcepJnz2sW2VQri-9DqgOFGglqnKre
https://drive.google.com/open?id=19lL4NF4HN_csVGk3JSnl2VkqEjDWM44B

**Comment by satya164** [comment]
https://reactnavigation.org/docs/screen-options-resolution#setting-parent-screen-options-based-on-child-navigators-state
