### ISSUE TITLE
MainStack to a new top position when opening FullSscreen-Modal

### ISSUE THREAD

**Issue by LucasParra** [react-navigation/react-navigation#8295]
Hello there!

I have found a strange behavior when we are using a modal.

**Current Behavior**

- What code are you running and what is happening?

```javascript
import React from 'react';

import {
  Button,
  Text,
  View,
} from 'react-native';

import { NavigationContainer } from '@react-navigation/native';
import { createStackNavigator } from '@react-navigation/stack';

function HomeScreen({ navigation }) {
  return (
    <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
      <Text style={{ fontSize: 30 }}>This is the home screen!</Text>
      <Button
        onPress={() => navigation.navigate('MyModal')}
        title="Open Modal"
      />
    </View>
  );
}

function DetailsScreen() {
  return (
    <View>
      <Text>Details</Text>
    </View>
  );
}

function ModalScreen({ navigation }) {
  return (
    <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: "transparent" }}>
      <View style={{ top: -100 }}><Button onPress={() => navigation.goBack()} title="Dismiss" /></View>
    </View>
  );
}

const MainStack = createStackNavigator();
const RootStack = createStackNavigator();

function MainStackScreen() {
  return (
    <MainStack.Navigator>
      <MainStack.Screen name="Home" component={HomeScreen} />
      <MainStack.Screen name="Details" component={DetailsScreen} />
    </MainStack.Navigator>
  );
}

export default function RootStackScreen() {
  return (
    <NavigationContainer>
      <RootStack.Navigator mode="modal">
        <RootStack.Screen
          name="Main"
          component={MainStackScreen}
          options={{ headerShown: false }}
        />
        <RootStack.Screen name="MyModal" options={{
          cardStyle: {
            backgroundColor: 'transparent',
          },
          header: () => null,
          headerStyle: {
            height: 0,
          },
        }} component={ModalScreen} />
      </RootStack.Navigator>
    </NavigationContainer>
  );
}

```

Basically what is happening is that the position of the MainStack is moving to a new top position, and the problem is that in transparent modals is weird to see that happening and doesn't keep the logic ui for users.

When using custom bottom navigation is even worst, because the bottom navigation goes up in position with all the navigation and there is a blank space between the new position of the bottom navigation component (upper) and the end of the screen.

- Video : https://streamable.com/wxd1r6

**Expected Behavior**

- What do you expect should be happening?

Keep the same position for MainStack when I open a modal

**How to reproduce**

I will not push any code because I'm running 
```expo init ```
```expo install @react-navigation/native``` 
```expo install react-native-gesture-handler react-native-reanimated react-native-screens react-native-safe-area-context @react-native-community/masked-view```
```expo install @react-navigation/stack```

and putting the code that u can see at the beginning of this comment

**Your Environment**

iOS or Android : Android, I tested in many androids and is happening in each one of them
@react-navigation/native : 5.4.1
@react-navigation/stack : 5.3.8
react-native-gesture-handler : 1.6.0
react-native-safe-area-context : 0.7.3
react-native-screens : 2.2.0
react-native : sdk-37.0.1
expo : 37.0.3
node : v13.7.0
npm or yarn: npm (expo handled honestly)

**Comment by satya164** [comment]
https://reactnavigation.org/docs/stack-navigator#transparent-modals
