### ISSUE TITLE
TS Binding element 'color' implicitly has an 'any' type

### ISSUE THREAD

**Issue by mtt87** [react-navigation/react-navigation#8296]
**Current Behavior**

Since the last version I think this TS type error was introduced

`Binding element 'color' implicitly has an 'any' type`

```ts
<Tabs.Screen
  options={{
    tabBarIcon: ({ color }) => (...),
    tabBarLabel: ({ color }) => (...),
  }}
/>
```

If I CMD+click to get to the definition of `createBottomTabNavigator` I get to this which feels weird
![Screen Shot 2020-05-20 at 11 12 25 AM](https://user-images.githubusercontent.com/2150927/82434558-ea94b500-9a8a-11ea-9c07-2d409ef76467.png)

`tsconfig.json`
```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "jsx": "react-native",
    "esModuleInterop": true
  },
  "include": ["src/**/*", "__tests__/**/*"],
  "exclude": ["node_modules"]
}
```
**How to reproduce**

I can create a repo later, I wanted to create a snack on Expo but can't see an option to use Typescript so wouldn't be able to reproduce the problem without TS

**Your Environment**

```
    "@react-navigation/bottom-tabs": "^5.4.6",
    "@react-navigation/native": "^5.4.1",
    "@react-navigation/stack": "^5.3.8",
    "typescript": "3.8.3"
    "react-native": "0.62.2",
    "react-native-screens": "2.7.0",

$ yarn -v
1.22.4

$ node -v
v14.2.0
```

**Comment by satya164** [comment]
Should be fixed in the latest version.
