### ISSUE TITLE
Rendering initial route defined in the navigator doesn't seem to work

### ISSUE THREAD

**Issue by roshangm1** [react-navigation/react-navigation#8301]
**Current Behavior**

- I am trying to navigate to nested screen inside a Tab Navigator with Stack Navigator. It's navigating properly but when I come back to other tab and again go back to the particular tab. It doesn't show the initial route from stack navigator, instead it shows the last screen inside Stack Navigator that I navigated to. Here is the sample code I am using.

**Tab Navigator**
```
<Tab.Navigator
      initialRouteName="Scan">
      <Tab.Screen
        name="Scan"
        component={screens.Scan}
        options={{
          tabBarIcon: ({color}) => {
            return <Icon name="crop-free" color={color} size={18} />;
          },
        }}
      />
      <Tab.Screen
        name="RegisterTag"
        component={RegisterTagScreen}
        options={{
          title: 'Register',
          unmountOnBlur: true,
          tabBarIcon: ({color}) => {
            return <Icon name="plus-box" color={color} size={18} />;
          },
        }}
      />
</Tab.Navigator>
```
**Stack Navigator** - RegisterStack
```
<TagsStack.Navigator
      screenOptions={{headerShown: false}}
      initialRouteName="Tags">
      <TagsStack.Screen name="Tags" component={screens.Tags} />
      <TagsStack.Screen name="Scan" component={screens.Scan} />
      <TagsStack.Screen name="AddTag" component={screens.AddTag} />
 </TagsStack.Navigator>
```

I am navigating to `AddTag` from first tab "Scan" as:
 
```
navigation.navigate('RegisterTag', {
      screen: 'AddTag',
      initial: false,
      params: {location},
    });
```

**Expected Behavior**

After navigating to `AddTag` screen and coming back to first Tab `Scan` and again going to second tab `RegisterTag`. I should be able to see initial route name mentioned in navigator i.e. `Tags` not `AddTag` screen.

**How to reproduce**
https://snack.expo.io/@roshangm1/nested-tab

**Comment by raajnadar** [comment]
`initialRouteName` will only work on initial render.

**Comment by roshangm1** [comment]
@raajnadar Oh cool!! Maybe, I wasn't clear but I don't have any issues with back button handling, I am actually talking about tab switching. Although, I feel like, I can add event listener for tab switch and handle accordingly, but I wanted to know if there was any other ways to do it. 

I actually did read the docs before creating this issue. I created this because I didn't find the proper solution. Anyway, Thanks for replying.

**Comment by raajnadar** [comment]
Again you didn't read the docs properly that prop is related to the history!

**Comment by hamidbin** [comment]
import { useFocusEffect } from '@react-navigation/native';

const A62ReciveScreen = ({route,navigation}) => { 

let renderState=0;

  useFocusEffect(
    React.useCallback(() => {
  if(renderState==0){
   renderState++;
  }else{
    renderState=0;
    navigation.popToTop();
  }
    }, [])
  );

  return(
<Screen style={styles.screen}>
</Screen>
)};

If you don't want to see even a glimpse of the previous stack screen, use "useIsFocused".
Check out the docs: https://reactnavigation.org/docs/function-after-focusing-screen/

**Comment by thusharamitrai** [comment]
I seem to have found the issue, it happens only when unmountOnBlur is set to true. seems to be a bug with library.

**Comment by laurens-lamberts** [comment]
I face this issue as well, specifically with. the `material top tab navigator`.
I tackled the issue by using react-native-tab-view immediately instead of the tab navigator.
Of course this is not ideal. initialRouteName not working with nested tab navigators still appears to be an issue.
