### ISSUE TITLE
navigation.reset() with given index does not set the active screen

### ISSUE THREAD

**Issue by riffryder** [react-navigation/react-navigation#8306]
**Current Behavior**

From my Home stack, I am trying to reset the navigation state so that I can push several screens into the routes so that they are available in the stack. I would also like to set the active screen as 'ScreenOne'. However, when I run this I land on 'ScreenThree'. I am trying to achieve the following by running:

```
navigation.reset({
  index: 1,
  routes: [{name: 'Home'}, {name: 'ScreenOne'}, {name: 'ScreenTwo'}, {name: 'ScreenThree'}]
});
```

**Expected Behavior**

I expect that setting `index: 1` would set the active screen as 'ScreenOne'. 

**How to reproduce**

This same bug can be reproduced within the same example in your docs for CommonActions.reset. If you change the index to 0 within the reset function, it still takes you to 'Home'.
[Here is the example](https://snack.expo.io/?platform=android&name=CommonActions%20reference%20%7C%20React%20Navigation&dependencies=%40react-native-community%2Fmasked-view%40%5E0.1.7%2C%40react-navigation%2Fbottom-tabs%40%5E5.4.5%2C%40react-navigation%2Fdrawer%40%5E5.7.5%2C%40react-navigation%2Fmaterial-bottom-tabs%40%5E5.2.5%2C%40react-navigation%2Fmaterial-top-tabs%40%5E5.2.5%2C%40react-navigation%2Fnative%40%5E5.4.0%2C%40react-navigation%2Fstack%40%5E5.3.7%2Creact-native-paper%40%5E3.10.1%2Creact-native-reanimated%40%5E1.7.0%2Creact-native-safe-area-context%40%5E0.7.3%2Creact-native-screens%40%5E2.4.0%2Creact-native-tab-view%40%5E2.14.0&sourceUrl=https%3A%2F%2Freactnavigation.org%2Fexamples%2F5.x%2Fcommon-actions.js)

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | iOS 13.5.0
| @react-navigation/native       |^5.4.0
| @react-navigation/stack        |^5.3.7
| react-native-gesture-handler   |^1.6.1
| react-native-safe-area-context |^1.0.2
| react-native-screens           |^2.7.0
| react-native                   |0.60.6
| npm or yarn                    | npm

**Comment by satya164** [comment]
You can't have more screens than the index in stack. This is expected.

**Comment by riffryder** [comment]
@satya164 Thanks for clarifying! Is this anywhere in the documentation? I was not aware of that until now. Also, is there any way to achieve this behavior currently?

**Comment by satya164** [comment]
What do you expect to happen if there are more screens than the index?

Stack Navigator works like a stack of cards. The item in the top of the stack is the focused card.

**Comment by riffryder** [comment]
There should be a facepalm emoji on here lol. Thanks @satya164!
