### ISSUE TITLE
Back button does not appear when trying deeplinking

### ISSUE THREAD

**Issue by yogendradanwar** [react-navigation/react-navigation#8308]
Hi, I am using this code to achieve deep linking it works great when the app is in the background back button appears and I can go back to the initial route. But as soon as I clear the app from the background process and try to access from the browser again the back button doesn't show up. Any idea ??

`
const Tab = createBottomTabNavigator();
const Stack = createStackNavigator();

export default RootStack = () => {

  const ref = React.useRef();

  const { getInitialState } = useLinking(ref, {
    prefixes: ['https://myapp.com', 'myapp://'],
    enabled: true,
    config: {
      more: {
        screens: {
          series: 'series',
          seriesdetail: {
            path: 'series/:id/:teamname/:tab',
            exact: true
          }
        }
      }
    },
    getPathFromState(state, config) {
      console.log(state, config);
    },
    getStateFromPath(path, config) {
      console.log(path, config);
    }
  });

  const [isReady, setIsReady] = React.useState(false);
  const [initialState, setInitialState] = React.useState();

  React.useEffect(() => {
    getInitialState()
      .catch(() => { })
      .then(state => {
        if (state !== undefined) {
          setInitialState(state);
        }
        setIsReady(true);
      });
  }, [getInitialState]);

  if (!isReady) {
    return null;
  }

  const MoreStack = () => (
    <Stack.Navigator initialRouteName="series">
      <Stack.Screen name="series" component={HomeScreen} />
      <Stack.Screen name="seriesdetail" component={DetailScreen} />
    </Stack.Navigator>
  )

  const MainNavigator = () => (
    <Tab.Navigator>
      <Tab.Screen name="more" component={MoreStack} />
      <Tab.Screen name="home" component={HomeStack} />
    </Tab.Navigator>
  )

  return (
    <NavigationContainer initialState={initialState} fallback={<Text>Loading...</Text>} ref={ref}><MainNavigator /></NavigationContainer>
  )

}

AppRegistry.registerComponent(appName, () => RootStack);`

Using these following version to achieve deep linking 

"@react-navigation/bottom-tabs": "^5.4.5",
"@react-navigation/native": "^5.4.0",
"@react-navigation/stack": "^5.3.7",
"react": "16.11.0",
"react-native": "0.62.2",

**Comment by bestv2** [comment]
Maybe this will help you
```tsx
 const linking = {
    prefixes: ['http://xxx.xxx',  'xxx://'],
    config: xxxConfig,
    getStateFromPath(path, config) {
      const defaultState = getStateFromPathDefault(path, config)
      // add first page to routes, then you will have a back btn
      const { routes } = defaultState
      const firstRouteName= 'YourFirstRouteYouWantBackTo'
      if (routes && routes.length === 1 && routes[0].name !== firstRouteName) {
        defaultState.routes.unshift({ name: firstRouteName})
      }
      return defaultState
    },
  }
```

**Comment by satya164** [comment]
https://reactnavigation.org/docs/configuring-links#rendering-an-initial-route

**Comment by yogendradanwar** [comment]
@satya164 can you reopen this ticket the above solution works when the app is closed. 
But when the app is not closed and is in the background state clicking on the back button gets me to the intialRouteName but when I switch tabs again and I go the same tab the state of that tab remains which was at the time of deeplink

**Comment by anthlasserre** [comment]
> @satya164 can you reopen this ticket the above solution works when the app is closed. But when the app is not closed and is in the background state clicking on the back button gets me to the intialRouteName but when I switch tabs again and I go the same tab the state of that tab remains which was at the time of deeplink

Hey @satya164 I finally get a rid of it by
1. Ensure my config linking has the right **initialRouteName**
2. Setting home screen navigation parameter in the home stack
```typescript
<Tab.Screen
  name={AppRoute.HomeStack}
  component={HomeStackScreen}
  options={options}
  listeners={({navigation}) => ({
    blur: () =>
      navigation.setParams({
        screen: undefined, // <-- This is fixing the initialRouteName issue when switching tabs
        title: 'Home',
      }),
    focus: () => navigation.setParams({title: 'Home'}),
  })}
/>
```
