### ISSUE TITLE
react-native-screen ( needed for bottom tab) shows node_modules/react-native-screens/src/screens.web.js: Support for the experimental syntax 'classProperties' isn't currently enabled (15:23):

### ISSUE THREAD

**Issue by kaiyes** [react-navigation/react-navigation#8310]
Hi,

While trying to add bottom tabs in a CRA app with react-native-web, This error pops up

![Screenshot 2020-05-21 at 4 50 52 PM](https://user-images.githubusercontent.com/5293742/82553638-3e37f900-9b86-11ea-9217-b7f336e272b1.png)

Which stems from react-native-screens. 

reproduction repo is here 
https://github.com/kaiyes/react-native-screens-babel-transform-error

'@react-navigation/native', '@react-navigation/stack'  , @react-native-community/masked-view and react-native-safe-area-context works.

**Comment by kaiyes** [comment]
I guess it has to do with webpack build set up as bottom tab works perfectly in vanilla react native or expo ios-android and even in expo web. But react navigation should work out of the box in create-react-app situations too. Hence this bug report.

**Comment by nonameb3** [comment]
Same issue here.

**Comment by satya164** [comment]
There's already an open PR in screens repo for that https://github.com/software-mansion/react-native-screens/pull/517
