### ISSUE TITLE
typescript: how to type props of `Stack.Navigator`

### ISSUE THREAD

**Issue by zanona** [react-navigation/react-navigation#8311]
I am looking into wrapping `Stack.Navigator` around another component `RootNavigator`, while keeping the prop types available, so I can pass those through the wrapper component as below.

The problem is that I cannot really find how to type `Props` of `createStackNavigator<RootNavigatorParams>();` so they are correctly checked?

### ./navigators/RootNavigator.tsx
```tsx
const Stack = createStackNavigator<RootNavigatorParams>();

type Props = {} /* NEED PROPS TYPE FOM STACK  ^^^^  */

const RootNavigator = ( props:Props ):JSX.Element => (
  <Stack.Navigator screenOptions={{headerTitleAlign:'center'}} {...props} />
);

export {RootNavigator};
```

### ./App.tsx
```tsx
import {RootNavigator} from './navigators/RootNavigator';

const App = ():JSX.Element => (
  ...
  <RootNavigator mode='modal' /> /* <--- props passed to Stack.Navigator */
  ... 
)

export default App;
```

**Comment by zanona** [comment]
Sorry about the labels, not sure how they got there, but I don't seem to be able to remove them :confused:

**Comment by zanona** [comment]
Hey, @raajnadar, after checking the source code, I'm almost sure those props are not being exposed, which would make this impossible to achieve? Shall I re-submit this as feature request? 

I count on your judgement over this, but if in fact, there are no public types allowing extension, I think there's little reason to submitting this as a question on SO?

**Comment by raajnadar** [comment]
Actually if I am not wrong you want this feature, right? https://github.com/react-navigation/rfcs/issues/85

**Comment by satya164** [comment]
```ts
React.ComponentProps<typeof Stack.Navigator>
```

**Comment by zanona** [comment]
Thanks for following up, @raajnadar. @satya164 that was it! This means the SO question would indeed make sense. Sorry about the hassle.
