### ISSUE TITLE
Issue with the replace action

### ISSUE THREAD

**Issue by vineetshetty** [react-navigation/react-navigation#8313]
**Current Behavior**
```
navigation.replace({
  name: 'Home',
  params: { fromScreen: 'screenName' },
  key: 'somekey'
});
```
The above command does not work and throws the following error:

The action 'REPLACE' with payload {"name":{"name":"Home","params":{"fromScreen":"screenName"},"key":"somekey"}} was not handled by any navigator.

Do you have a screen named '[object Object]'?

My assumption is it is taking the first object in the function as the screen name.

The following works:
```
navigation.replace('Home', { fromScreen: 'screenName' });
```
But how do I set the key parameter here?

Tried this as well and it works too:
```
navigation.dispatch({
  StackActions.replace(
    'Home',
    { fromScreen: 'screenName' }
  )
})
```
Not sure of how to set the key using this format as well

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |iOS
| @react-navigation/native       |5.4.0
| @react-navigation/stack        |5.3.7
| react-native-gesture-handler   |1.6.1
| react-native-safe-area-context |1.0.2
| react-native-screens           |2.7.0
| react-native                   |0.62.2
| expo                           |--
| node                           |10.20.1
| npm or yarn                    |yarn 1.22.4

**Comment by vineetshetty** [comment]
Upgraded to the latest versions

@react-navigation/native (found: 5.4.0, latest: 5.4.2)
@react-navigation/stack (found: 5.3.7, latest: 5.3.9)

The issues still persist

**Comment by vineetshetty** [comment]
The navigation works properly using the following code snippets:

`navigation.replace('Home', { fromScreen: 'screenName' });`

OR

```
navigation.dispatch({
  StackActions.replace(
    'Home',
    { fromScreen: 'screenName' }
  )
})
```

However, I am just not able to set the key parameter. The documentation does not mention how to set the key parameter for the replace command.

**Comment by raajnadar** [comment]
I am asking repro for the part where error is thrown. Why would I ask repro for a working code?

> navigation.replace({
>   name: 'Home',
>   params: { fromScreen: 'screenName' },
>   key: 'somekey'
> });
> 
> The above command does not work and throws the following error:
> 
> The action 'REPLACE' with payload {"name":{"name":"Home","params":{"fromScreen":"screenName"},"key":"somekey"}} was not handled by any navigator.
> 
> Do you have a screen named '[object Object]'?

You can see in the last line it says `[object Object]` this means you are doing something wrong in your code.

**Comment by vineetshetty** [comment]
Thank you for your curt reply. Please refer to my original query where I have mentioned that I have an idea of why I am encountering the issue.

Let me try to rephrase my query. I just need to know how to set the key parameter in the Stack action. The key parameter in react-navigation has been a widely used parameter at least from version 3 as far as I can remember. Please refer to another part of the documentation where the definition of key should be clear:

https://reactnavigation.org/docs/upgrading-from-4.x#replace

I am not able to set the key or the source parameter as mentioned in the above link.

**Comment by raajnadar** [comment]
Read the migration docs https://reactnavigation.org/docs/upgrading-from-4.x

https://reactnavigation.org/docs/upgrading-from-4.x#navigate

**Comment by vineetshetty** [comment]
How is this resolved? I am not talking about navigate at all!!! I am referring to the replace action. Can you be a little more specific rather than just pointing to the same document that I am referring to? If the key parameter is something that cannot be set, can you at least acknowledge it and change the documentation accordingly?

**Comment by raajnadar** [comment]
Can you please open the migration docs & search for the thing that you want..!

**Comment by vineetshetty** [comment]
From the document

> Previously, it was possible to pass an object { routeName, key, newKey, params }. Now, routeName is called just name, and newKey is called key, so it'll be { name, key, params }. The previous key can be specified using the source property.

Please help me understand how does this mean that the key is deprecated? According to what I understand, this means the value that we used to pass into newKey until version 4 can now be passed into the key parameter

**Comment by vineetshetty** [comment]
In fact I went through the entire document again and there is no mention of key being deprecated at any point in the document.

**Comment by klinzo** [comment]
Any update on this? Did you find a way to specify the key of the new route for replace @vineetshetty by any chance? Thanks!
