### ISSUE TITLE
Require cycle: node_modules/@react-navigation/core/src/BaseNavigationContainer.tsx -> node_modules/@react-navigation/core/src/useOptionsGetters.tsx -> node_modules/@react-navigation/core/src/BaseNavigationContainer.tsx

### ISSUE THREAD

**Issue by vikasg603** [react-navigation/react-navigation#8315]
**Current Behavior**

- Adding Bottom Tab navigation
- Screenshot of warning https://ibb.co/kK1R6DJ

**Expected Behavior**

- There should be no cycle in a code base

**How to reproduce**

- Opening bottom tab navigation screen

**Your Environment**
"@react-navigation/bottom-tabs": "^5.4.7",
"@react-navigation/material-top-tabs": "^5.2.7",
"@react-navigation/native": "^5.1.7",
"@react-navigation/stack": "^5.2.13",

**Comment by raajnadar** [comment]
Upgrade to latest version and clear cache. The issue will get fixed.

**Comment by Uttu316** [comment]
No, it is not fixed it yet. I am still getting the same warning now.

**Comment by vikasg603** [comment]
> No, it is not fixed it yet. I am still getting the same warning now.

fixing cache and then rebuilding the app will fix the issue
(Update all the navigation library)

**Comment by raajnadar** [comment]
@Uttu316 upgrade to very latest version of v5. Clear the cache with `expo start -c` or `npx react-native run-android --reset-cache`

Make sure you uninstall the app from from device.

Also try `cd android` and `gradlew clean` or `./gradlew clean`

**Comment by Uttu316** [comment]
I did everything but still getting the warning

**Comment by stephanoparaskeva** [comment]
Am also getting issue, have cleared cache multiple times

**Comment by raajnadar** [comment]
@Uttu316 & @stephanoparaskeva if the issue is not fixed give a repro.

As I said upgrading to latest version of react navigation v5 & clearing the cache of metro should fix the issue.

Read this comment also https://github.com/react-navigation/react-navigation/issues/8315#issuecomment-635737879
