### ISSUE TITLE
Bottom Tab navigating to incorrect stack

### ISSUE THREAD

**Issue by boxedcode** [react-navigation/react-navigation#8318]
**Current Behavior**

Below is the structure of the navigation for an app that I am working on. I am having some issues when navigating using a bottom tab between stacks which I will explain below.

```
SwitchNavigator
 - Landing Flow
     Switch Navigator
     - Landing 	
     - Main Flow
         Bottom Tab Navigator
         - Home Flow 
	         Stack Navigator
	         - Home
                 - Equipment
		 - Why Us
		 - About
		 - Select System Flow
		     Switch Navigator
		     - Select System Menu
		           Stack Navigator
			    - Select System
			    - Domestic Systems
			    - Commercial Systems
		     - Resolve Auth		
	 - View System
	 - My Appliance
	 - Finance Options
 - Login Flow
     Stack Navigator
     - Sign Up
     - Login
```

When I navigate using the following path:

Landing > Home > Select System > Domestic Systems > View System

When I then hit the bottom tab **Home Flow**, I am shown the **Domestic Systems** screen instead of the **Home** screen. When I hit the bottom tab **Home Flow** a second time, I am then taken to the **Home** screen.

**Note:** I have the `initialRouteName` set to `Home` for the `Home Flow` stack navigator options.

Effectively, it appears that the bottom tab is behaving like a **Back** button, before it behaves like it should. Another way to look at it is that, it is navigating me back to the **last known** screen in a Stack Navigator, before it takes me to where it needs to go.

I have tried using `unmountOnBlur: true` on the **Select System Menu** stack navigator, but that did not do the trick.

Can anyone provide some insight into possible reasons why I am having this issue, and how I can resolve it?

Thanks!

**Your Environment**

| software                      | version |
| ----------------------------- | ------- |
| iOS or Android                | Android
| @react-navigation/native      | 3.7.11
| react-navigation      | 4.3.7
| react-navigation-stack      | 2.3.11
| react-navigation-tabs | 2.8.12
| react-native-screens          | 2.2.0
| react-native                  | 0.61.4
| expo                          | 37.0.7
| node                          | v10.14.2
| npm or yarn                   | npm

**Comment by boxedcode** [comment]
I have upgraded to the following package versions below. For the app that I am building, for compatibility reasons, I need to stick to all other versions that I currently have:

| software                      | version |
| ----------------------------- | ------- |
| @react-navigation/native      | 3.7.13
| react-navigation      | 4.3.9
| react-navigation-stack      | 2.5.1
| react-navigation-tabs | 2.8.13
| expo                          | 37.0.12

After the upgrades, the problem still persists. Thanks.

**Comment by boxedcode** [comment]
Here is a simplified version of my app that demonstrates the navigation issue that I am having;

https://snack.expo.io/@onetimeengineer/bottom-tab-issue

**Comment by raajnadar** [comment]
Your navigation system is very complicated I would suggest you to upgrade to v5 of react navigation. Try to use less nesting the cause of problem seems like the swith navigator.

**Comment by boxedcode** [comment]
@raajnadar Thanks for getting back to me, much appreciated.

Are there known issues with the switch navigator and / or react navigation when it comes to nesting, which have been resolved in v5 of react navigation?

Can you suggest a simpler way of organising my navigation based on what I am trying to achieve with the structure I posted above?

Thanks..

**Comment by raajnadar** [comment]
In v5 we don't have switch navigation, switch navigation is used for authentication that's why I told you to upgrade.

**Comment by satya164** [comment]
https://reactnavigation.org/docs/4.x/bottom-tab-navigator/#bottomtabnavigatorconfig
