### ISSUE TITLE
Disabled android back button behavior between top tabs when coming from stack navigation

### ISSUE THREAD

**Issue by meerita** [react-navigation/react-navigation#8322]
**Current Behavior**

I am developing an app that has a hierarchy of navigation systems using React Navigation 5 and it reacts in a bizarre way when using the hardware button return from android.

My current hierarchy is:

- Main Stack Navigation
-- BottomTabNavigation

or 
- Main Stack Navigation
-- Top Tab Navigator.

Once you start browing the Tab Navigator, and you press the Android Hardware Back Button this one starts browsing back between all the tabs I've visited. This behaviour is not good at all, instead of that I should return to the previous stack navigation screen.

I will attach a video of this behaviour.

[Video of the behavior](https://drive.google.com/open?id=1_-g9fjWtDHMoAvZhW4r4FVTotCYQadYb)

**Expected Behavior**

I want to disable the android back button between tabs and allowing only to respect the stack navigation or disable it at all in the rest of the tabs but not on the main one.

**Your Environment**

| software                            | version |
| ----------------------------------- | ------- |
| iOS or Android                      | +11 / +5.0
| @react-navigation/native            | ^5.3.0
| @react-navigation/material-top-tabs | ^5.2.8
| react-native-tab-view               |
| react-native                        | sdk-37.0.1 | sdk-37.0.1| 
| expo                                | ^37.0.0
| node                                |
| npm or yarn                         |

**Comment by satya164** [comment]
https://reactnavigation.org/docs/bottom-tab-navigator#backbehavior
