### ISSUE TITLE
inactiveColor issue with 4 bottom Tabs 

### ISSUE THREAD

**Issue by deepgosalia1** [react-navigation/react-navigation#8323]
I currently want to implement a bottom tab navigator with 4 tabs.
When only three tabs were present the inactiveColor would work perfectly for all the tabs. When i added the 4th new tab, the inactiveColor prop is suddenly failing to give the color to the inactive tabs. the active tab's label and icon would get correctly colored. And the label isnt showing up as well.

As you see, the inactive color is not getting applied to label text. 

**Expected Behavior**
Expected Behaviour would be that all the 3 inactive tabs and the 4th active tabs would properly get their respective colors for the icons and labels both.

**Your Environment**
Issue is persisting for my android and IOS app both. Also the @expo/vector-icons are not getting displayed on my ios app for some reason. I tried recreating the app from scratch for that but still wont show up. 

![image](https://user-images.githubusercontent.com/32708932/82755775-7bed8980-9df3-11ea-87f7-bf4d51632722.png)

```
export default function MyTabs() {
  const Tab = createMaterialBottomTabNavigator();

  return (
    <Tab.Navigator
      initialRouteName="Home"
      activeColor="blue"
      inactiveColor='grey'
      labelStyle={{ fontSize: 12 }}
      barStyle={{ backgroundColor: 'white' }}
    // 3b3c36
    >
      <Tab.Screen
        name="Home"
        component={Home}
        options={{
          tabBarLabel: 'Home',
          tabBarIcon: ({ color }) => (
            <Entypo name="home" color={color} size={26} />
          ),
        }}
      />

      <Tab.Screen
        name="Search"
        component={Search}
        options={{
          tabBarLabel: 'Search',
          tabBarIcon: ({ color }) => (
            <Feather name="search" color={color} size={26} />
          ),
        }}
      />

      <Tab.Screen
        name="Library"
        component={Library}
        options={{
          tabBarLabel: 'My Music',
          tabBarIcon: ({ color }) => (
            <MaterialCommunityIcons name="library-music" color={color} size={26} />
          ),

        }}
      />


      <Tab.Screen
        name="Profile"
        component={profileStack}
        options={{
          tabBarLabel: 'Profile',
          tabBarIcon: ({ color }) => (
            <MaterialCommunityIcons name="account" color={color} size={26} />
          ),
        }}
      />


    </Tab.Navigator>
  );
}
```

**Comment by satya164** [comment]
Closing since you haven't provided a repro. Please open a new issue with a minimal repro if you're still having problems.

**Comment by dheeraj539** [comment]
https://snack.expo.dev/@dheeraj539/react-navigation

Here's a minimal repo demonstrating the issue. Its working as expected with 3 bottom tabs, but stops working after adding the 4th.
