### ISSUE TITLE
Push animation working sideways with authentication navigator

### ISSUE THREAD

**Issue by cipriancaba** [react-navigation/react-navigation#8324]
**Current Behavior**

- When running an authentication flow (old SwitchNavigator) I have an issue where the main app screen appears from the left side and the login screen goes to the right, rather than being the other way around
- It's probably a silly mistake but I've tried playing around with the order of components but it's basically the same behaviour

**Expected Behavior**

- Navigation to main flow should happen naturally (ios push style)

**How to reproduce**

- Here is my `NavigationContainer`:
```
<Stack.Navigator>
        {authState === AuthState.Initial && (
          <Stack.Screen
            name={"LoadingFlow"}
            component={LoadingFlow}
            options={{ headerShown: false }}
          />
        )}
        {authState === AuthState.SignedOut && (
          <Stack.Screen
            name={"AuthenticationFlow"}
            component={AuthenticationFlow}
            options={{ headerShown: false }}
          />
        )}
        {authState === AuthState.SignedIn && (
          <Stack.Screen
            name={"ApplicationFlow"}
            component={ApplicationFlow}
            options={{
              headerShown: false,
              animationTypeForReplace: 'push',
            }}
          />
        )}
      </Stack.Navigator>
```

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | iOS
| @react-navigation/native       | 5.0.5
| @react-navigation/stack        | 5.0.5
| react-native-gesture-handler   | 1.6.0
| react-native-safe-area-context | 0.7.3
| react-native-screens           | 2.2.0
| react-native                   | 0.61.5
| expo                           | 37.0.11
| node                           | 13.12.0
| npm or yarn                    | yarn ftw

**Comment by cipriancaba** [comment]
I've replicated the behaviour on the latest package versions

**Comment by satya164** [comment]
Closing since you haven't provided a repro. Please open a new issue with a minimal repro if you're still having problems.
