### ISSUE TITLE
Possible to persist navigation state based on screen?

### ISSUE THREAD

**Issue by AndresTIY** [react-navigation/react-navigation#8328]
**Current Behavior**

https://reactnavigation.org/docs/4.x/state-persistence/

Using the experimental state persistence feature. Currently when the user leaves the app and then returns, the last seen screen is displayed as expected. This happens with every screen. 

It would be beneficial if I could control which screens should be persisted. 

**Expected Behavior**
Screen A should be persisted
Screen B should NOT
- User leaves the app on Screen A. Comes back a day later, Screen A is displayed. 
- User leaves the app on Screen B. Comes back a day later, Screen A is displayed instead. 

```js
 const persistenceKey = 'persisKey';
  const persistNavigationState = async navState => {
    try {
      await AsyncStorage.setItem(persistenceKey, JSON.stringify(navState));
    } catch (err) {
      console.log('persist navigation error', err);
    }
  };
  const loadNavigationState = async () => {
    const jsonString = await AsyncStorage.getItem(persistenceKey);

    return JSON.parse(jsonString);
  };
```

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |
| react-navigation               | 4
| react-navigation-stack         |
| react-navigation-tabs          |
| react-navigation-drawer        |
| react-native-reanimated        |
| react-native-gesture-handler   |
| react-native-safe-area-context |
| react-native-screens           |
| react-native                   |0.61.0
| expo                           | no
| node                           |
| npm or yarn                    |

**Comment by satya164** [comment]
You are getting the state object to persist, it's upto you to make whatever changes you want to the object if you need to.
