### ISSUE TITLE
Using <Link /> with getStateFromPath has broken Back behavior

### ISSUE THREAD

**Issue by virgil9306** [react-navigation/react-navigation#8330]
**Current Behavior**

I am trying to get URL back-forward behavior to work in web. Here is how:

1. I am using `linking` in `NavigationContainer` to `getStateFromPath`. 
2. I am using`<Link />` to navigate from Page A to Page B. But actually, Page A and Page B is the same Route, just with different contents loaded based on the URL (see `getStateFromPath`).

**_Behavior on @react-navigation/native @ 5.4.3 & @react-navigation/stack @ 5.4.0 and versions originally posted in this issue:_**

On web, going "back" doesn't go back to "Page A." It just goes to whatever URL I was at before Page A (in this case, my browser home page).

(BTW this works fine on iOS using `navigation.dispatch` with params, but then I cannot use back button on Web)

----

Following this documentation:

https://reactnavigation.org/docs/web-support/

**Expected Behavior**

- Back button behavior should be the same for "same route with different parameters," not just "different route with different parameters."

Expected behavior is `<Link />` to push to the navigation stack of the `StackNavigator` I created since it is a stack navigator. But even though the URL changes, the Back button does not work.

I need to use the same Route. There are quite a few apps that require an architecture like mine.

**How to reproduce**

1. Create an app with only one route
2. Create an app that uses `getStateFromPath` to create different states based on URL/web path.
3. Create a `<Link />` that links to another path. This should create different states according to step # 2.

The navigation happens.

Then try to click Back, and you will see it doesn't work.

**Steps taken**

1. First I used `<Link>` without `options` property.
2. That produced the bug. So then I used the `StackActions.push` as outlined here: https://reactnavigation.org/docs/use-link-props#options 

Both produced the same bug.

Also, both allowed me to go back _once_. But this pattern broke the Back behavior:

Route 1, Props A -> Route 1, Props B -> Back to Route 1, Props A -> Forward to Route 1, Props B -> **Back to Route 1, Props A (this breaks: it shows Route 1, but with Props B instead -- it didn't successfully pop/push the stack?)**

Note: These are the same route, rendering different contents based on which props are received (using `getStateFromPath`).

**Workaround**

Until this issue gets fixed I am using a-tags as a workaround like this:

```
if (Platform.OS === 'web') {
    return <a href={path}>...</a>;
}
return <Link path={path} ... />;
...
```

**Repro**

https://snack.expo.io/mX5NiCNP5

How to reproduce the issue in Repro:

1) Open the app
2) Click the Link to change the URL (which changes the URL parameters)
3) Click Back, and it will go back to the page before loading the app, rather than changing the URL to the last URL and loading the page. **(This is the buggy behavior)**

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | web
| @react-navigation/native       | 5.3.0
| @react-navigation/stack        | 5.2.14
| react-native-gesture-handler   | 1.6.1
| react-native-safe-area-context | 0.7.3
| react-native-screens           | 2.2.0
| react-native                   | 0.61.4
| expo                           | 37.0.12
| node                           | Node 12.11.1
| npm or yarn                    | npm 6.13.6

**Comment by virgil9306** [comment]
> Hey! Thanks for opening the issue. Can you provide a [minimal repro](https://stackoverflow.com/help/minimal-reproducible-example) which demonstrates the issue? Posting a snippet of your code in the issue is useful, but it's not usually straightforward to run. A repro will help us debug the issue faster. Please try to keep the repro as small as possible. The easiest way to provide a repro is on [snack.expo.io](https://snack.expo.io). If it's not possible to repro it on [snack.expo.io](https://snack.expo.io), then you can also provide the repro in a GitHub repository.

@satya164 

I am trying to create a `repro` right now.

If you can reach me privately I can share a GitHub repo but it has proprietary code so I cannot share it here publicly. Is that possible too?

**Comment by virgil9306** [comment]
Hi @satya164 
Thanks for the reply and advice. 

As I mentioned above

> First I used <Link> without options property.
> That produced the bug. So then I used the StackActions.push as outlined here: https://reactnavigation.org/docs/use-link-props#options
> Both produced the same bug.

So I already your suggestion but it actually didn’t work in this case. Could there be some strange unexpected behavior in this scenario? 

Thanks.

**Comment by satya164** [comment]
I can't repro the issue with `StackActions.push` in your repro
