### ISSUE TITLE
How can I use both Drawer and Screen on slide type?

### ISSUE THREAD

**Issue by devethan** [react-navigation/react-navigation#8331]
Thanks to your support 😄 

**Current Behavior**

- What code are you running and what is happening?
I'm using `expo-web` to develop simple demo app. For this, I'm using `DrawerNavigator` on `DrawerType` set to `slide`. But I couldn't use both of `Drawer` and `screens` at same time. Because there are overlay on the screen. When I touched on the screen, the `Drawer` is closed.

![May-26-2020 10-33-50](https://user-images.githubusercontent.com/55861805/82851973-764f8b00-9f3c-11ea-829a-832ad9523c7b.gif)

**Expected Behavior**

- What do you expect should be happening?
I wanna keep my `Drawer` open when using screen. I know that there is `permanent` type, but it doesn't support `DrawerActions` , like `open` and `close` actions. How could I make it?

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | 13
| @react-navigation/native       | ^5.3.0
| @react-navigation/drawer       | ^5.8.0
| react-native-reanimated        | ~1.7.0
| react-native-gesture-handler   | ~1.6.0
| react-native-safe-area-context | 0.7.3
| react-native-screens           | ~2.2.0
| react-native                   | https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz
| expo                           | 37.0.9
| node                           | 12.16.3
| npm or yarn                    | 1.22.4

**Comment by raajnadar** [comment]
Github issues is only for tracking bugs & issues. This is not the right place for how to questions.
