### ISSUE TITLE
tabStyle height doesn't work as expected

### ISSUE THREAD

**Issue by mtt87** [react-navigation/react-navigation#8337]
**Current Behavior**

Changing the height of the bottom tab bar doesn't make it grow upwards but it grows downwards (off the screen)

Example with `height: 64`
![Simulator Screen Shot - iPhone 11 - 2020-05-27 at 11 36 44](https://user-images.githubusercontent.com/2150927/83009565-d9115700-a00e-11ea-8670-aac35b4a424b.png)
![Screenshot_1590575802](https://user-images.githubusercontent.com/2150927/83009571-db73b100-a00e-11ea-90d2-b129df9d1389.png)

Example with `height: 128`
![Simulator Screen Shot - iPhone 11 - 2020-05-27 at 11 41 05](https://user-images.githubusercontent.com/2150927/83009677-0231e780-a00f-11ea-90ea-25a5d10fa5cf.png)
![Screenshot_1590576064](https://user-images.githubusercontent.com/2150927/83009679-03fbab00-a00f-11ea-8ed4-a4e3a7bf1cc4.png)

**Expected Behavior**

I would expect the bottom tab bar to grow upwards in order to not go off the screen.
Example, if your screen is 1000 height and you set the bottom tab bar to be 100 I would expect the Tab.Screen available space to become 900.
At the moment no matter what you set apparently somewhere in a parent there is a fixed height value of 50.

**How to reproduce**

```js
    <Tabs.Navigator
      tabBarOptions={{
        tabStyle: {
          height: 128,
          backgroundColor: 'green',
        },
      }}
    >
```

**Your Environment**

```
    "@react-navigation/bottom-tabs": "^5.5.0",
    "@react-navigation/native": "^5.4.3",
    "@react-navigation/stack": "^5.4.0",
    "react-native": "0.62.2",
    "react-native-screens": "2.8.0"
```

**Comment by mtt87** [comment]
Ok it's a bit confusing the usage of `style` and `tabStyle` but I was able to fix it by doing this:
```js
  <SafeAreaView style={{ flex: 1 }}>
      <Tabs.Navigator
        tabBarOptions={{
          style: {
            height: 64,
          },
          tabStyle: {
            height: 64,
            backgroundColor: '#fff',
          },
        }}
      >
        <Tabs.Screen ...
```

Note that just using `style` without the `<SafeAreaView>` doesn't work as iOS will show go outside the safe area. I thought the bottom tab bar was automatically wrapped in a safe area view.

![Simulator Screen Shot - iPhone 11 - 2020-05-27 at 11 56 57](https://user-images.githubusercontent.com/2150927/83011077-38706680-a011-11ea-8a6f-152ddd6749d7.png)
![Screenshot_1590577016](https://user-images.githubusercontent.com/2150927/83011079-3908fd00-a011-11ea-929a-325a7220c621.png)

**Comment by k4Shinigami** [comment]
I had the same issue where I needed a different height for the tabbar. Your solution almost worked for me @mtt87 but I had more white space at the top and bottom where virtual home bar is present instead of the color specified in the style. 

Instead of using the safeAreaView around the tabnavigator, insets worked for me.

```
import { useSafeArea } from 'react-native-safe-area-context'
...
const TabScreen = () => {
	const insets = useSafeArea()
	
	<Tabs.Navigator
        tabBarOptions={{
		 style: {
			height: TAB_HEIGHT + insets.bottom,
			backgroundColor: theme.colors.black,
          },
          tabStyle: {
            height: TAB_HEIGHT,
          },
		height: TAB_HEIGHT + insets.bottom, 
		...
	}}>
	...

```

**Comment by mtt87** [comment]
@k4Shinigami I was facing the exact same problem yesterday what a coincidence! Thanks for sharing your approach!

**Comment by mortocks** [comment]
@k4Shinigami 's solution worked perfectly for me

**Comment by Simranjit1080** [comment]
@k4Shinigami Was facing same problem.Tried implementing our method. But I am getting error (No safe area insets available)

**Comment by acomito** [comment]
my text editor is saying useSafeArea is deprecated?

**Comment by manumaticx** [comment]
you can update it to `useSafeAreaInsets`

**Comment by suhaillilac** [comment]
as with react native navigation V6 , tabstyle props changed. 

<Tab.Navigator
  screenOptions={{
    tabBarInactiveTintColor: 'rgba(255, 255, 255, 0.5)',
    tabBarActiveTintColor: '#fff',
    tabBarStyle: {
      position: 'absolute',
      borderTopColor: 'rgba(0, 0, 0, .2)',
      height: 70 
    },
  }}
>

**Comment by Aiosa** [comment]
Use `withSafeAreaInsets` with  navigation v6:

    import {withSafeAreaInsets} from "react-native-safe-area-context";

    const Tab = createBottomTabNavigator();
    function BottomBarNavigator(props) {
        return (
            <Tab.Navigator
    ...
                screenOptions={{
                    tabBarStyle: {
                        height: MY_HEIGHT + props.insets.bottom,  

    ...

    export default withSafeAreaInsets(BottomBarNavigator);
