### ISSUE TITLE
How to avoid drawer methods existence error without using hooks

### ISSUE THREAD

**Issue by take** [react-navigation/react-navigation#8341]
Hi Thanks for the awesome library :)

I came across to the error below when I was using drawer navigator

```
let HomeScreen = createStackNavigator({
  Tabs: {
    screen: Tabs,
    navigationOptions: ({ navigation }) => ({
      headerLeft: () =>
        <Icon.Button
          onPress={() => navigation.openDrawer()} ❯ TS2339: Property 'openDrawer' does not exist on type 'StackNavigationProp<NavigationRoute<NavigationParams>, NavigationParams>'.
        />,
    }),
  }
})
```

and looks like the method was removed in https://github.com/react-navigation/react-navigation/commit/683892e
I did some search in the Issues and found out https://github.com/react-navigation/react-navigation/issues/6592, but looks like that is using hooks.

Is there a way to avoid this error without using hooks? Or do I need to ignore it with `// @ts-ignore` just like in the [example](https://github.com/react-navigation/react-navigation/commit/683892e#diff-104762acb2d384bf28f2294a49a3c2d0R33-R34) ? :eyes: 

Thanks,

**Comment by raajnadar** [comment]
```
onPress={(): void =>
  ((navigation as any) as DrawerNavigationProp<{}>).openDrawer()
}
```

Try this took this code from the example application.

**Comment by take** [comment]
ahaaaa thanks it worked ! 🙌 

@raajnadar btw where was the example code? 🤔 tried to find it but I could only find https://github.com/react-navigation/react-navigation/blob/52d5cb41792e4bd9119e30b738e0b22c399323f6/example/src/index.tsx#L270

**Comment by raajnadar** [comment]
Actually I gave you a workaround if you upgrade to latest version the below code will be valid.

`onPress={() => navigation.toggleDrawer()}`

**Comment by take** [comment]
damn nice thanks! 🙌

**Comment by Symyon** [comment]
Instead of:
`navigation.openDrawer()`
do:
'navigation.dispatch(DrawerActions.openDrawer())'

taken from docs for react-navigation v4:
https://reactnavigation.org/docs/4.x/drawer-based-navigation
