### ISSUE TITLE
No null screen in version 5

### ISSUE THREAD

**Issue by Kunalpaul12** [react-navigation/react-navigation#8343]
import { createBottomTabNavigator } from '@react-navigation/bottom-tabs';

const Tab = createBottomTabNavigator();

const Add = () => {
  return null;
};

function MyTabs() {
  return (
    <Tab.Navigator>
      <Tab.Screen name="Home" component={HomeScreen} />
      <Tab.Screen name="Settings" component={Add} />
    </Tab.Navigator>
  );
}

**Comment by Kunalpaul12** [comment]
@raajnadar  This issues has not been answered if you need anything let me know or point me in right direction

**Comment by raajnadar** [comment]
Follow the issue template, and add a repro I will reopen the issue.
