### ISSUE TITLE
Web, URL differs from what we expect

### ISSUE THREAD

**Issue by M4gie** [react-navigation/react-navigation#8344]
Hey :wave:

**Current Behavior**

We are using react navigation on the web with the Link component and sometimes our URL differs from what we expect.
We have a bottom bar with three screens ("Home, Profile, Contact") and a stack navigator who contains our bottom bar and a screen call "QRScreen".
We made some tests by navigating on each screen:
 - Home -> QRScreen => my URL is correct (/qr-screen)
 - Home -> Profile -> QRScreen => my URL is correct (/qr-screen)
 - Home -> Profile -> Contact -> QRScreen => my URL isn't correct (/profile)

**Expected Behavior**

- Home -> Profile -> Contact -> QRScreen
By navigating on these screens our url should be /qr-screen

**How to reproduce**

I create an example in this [repository](https://github.com/M4gie/nestedNavigators)

1. Navigate on these screens: Home -> Profile -> Contact -> QRScreen
2. Check the URL 

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |
| @react-navigation/native       |5.4.1
| @react-navigation/bottom-tabs       |5.4.6
| @react-navigation/stack       |5.3.8
| react-native                   |
| expo                           |37.0.3
| node                           |
| npm or yarn                    |

**Not sure if it's a bug or if we missed something in your documentation**

**Comment by M4gie** [comment]
The issue still exists after upgrading

**Comment by code-artisan** [comment]
Same problem.
