### ISSUE TITLE
When you press tab icon no not respond

### ISSUE THREAD

**Issue by meksiabdou** [react-navigation/react-navigation#8346]
The problem of the top position but in the bottom position works well

![screen1](https://user-images.githubusercontent.com/16627410/83072276-c29ae800-a06e-11ea-8dd2-a05fbc24fc44.gif)
![screen2](https://user-images.githubusercontent.com/16627410/83072369-f0802c80-a06e-11ea-9636-2971010c3173.gif)

**Your Environment**

| software                            | version |
| ----------------------------------- | ------- |
|Android                      |10
| @react-navigation/native            |5.4.3
| @react-navigation/material-top-tabs |5.2.8
| react-native-tab-view               |2.14.2
| react-native                        |0.62.2
| node                                |12.14.1
| npm or yarn                         |6.13.4

**Comment by satya164** [comment]
Closing since you haven't provided a repro. Please open a new issue with a minimal repro if you're still having problems.
