### ISSUE TITLE
warning: Accessing child navigation state for a route is not safe and won't work correctly

### ISSUE THREAD

**Issue by fuersite** [react-navigation/react-navigation#8348]
**Current Behavior**

- Has a warning with navigation when I custom the navigationOptions

**Expected Behavior**

- I want it work correctly

**How to reproduce**

```
export const BottomNav = createCompatNavigatorFactory(createBottomTabNavigator)(
    {
      'takeout': { screen: ProfileScreen, navigationOptions:{
        title: '外卖',
      }},
      'home':{screen: HomeScreen,navigationOptions:{
        title: '我的',
      }},
    },
    {
      initialRouteName: 'takeout',
    }
)

export const MainScreen = createCompatNavigatorFactory(createStackNavigator)(
    {
      'home': { screen: BottomNav, navigationOptions:({navigation})=> {
          console.log('state',navigation.state)
          let activeIndex = navigation.state.index
          let routeName = activeIndex!=undefined? navigation.state.routes[activeIndex].name:'takeout'
          return {
            headerTitle: routeName,
          }},
    },
      '我的':{ screen: HomeScreen}
    },
    {
      initialRouteName: 'home',
    }
)
```

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |ios&android
| @react-navigation/native       |5.4.2
| @react-navigation/stack        |5.3.9
| react-native-gesture-handler   |1.6.1
| react-native-safe-area-context |
| react-native-screens           |
| react-native                   |0.62.2
| expo                           |no
| node                           |10.10.0
| npm or yarn                    |yarn

**Comment by Aung-Myint-Thein** [comment]
Have you fixed this issue?

By the way, how do you access the stack's index in the screen?

**Comment by satya164** [comment]
The warning is there because it won't work.

**Comment by cristianoccazinsp** [comment]
I'm getting this warning even without using `dangerouslyGetState`. I got this after a recent upgrade to native/stack 5.7.x. Thoughts?

How do we replace `dangerouslyGetState` anyways?

**Comment by cristianoccazinsp** [comment]
Even after removing `dangerouslyGetState` and `<NavigationContainer onStateChange` (which I also suspected was causing the warnings), the warnings are coming after pretty much every navigation event.

@satya164  can you re-open this or shine some light about where this warning is coming from? We use warn messages to log to a central server and it's impossible to release this version with the spam coming from these warnings.
