### ISSUE TITLE
undefined is not an object (evaluating '_native.NavigationHelpersContext.Provider') 

### ISSUE THREAD

**Issue by keshav100** [react-navigation/react-navigation#8351]
https://github.com/wix/react-native-navigation/issues/6247#issue-625728535

**Comment by keshav100** [comment]
why you closed the issue without explanation

**Comment by raajnadar** [comment]
Did you explain your problem here? pasting a link is no good..! And you did not follow the issue template.

**Comment by keshav100** [comment]
you must click that link . there is full explanation about issue

**Comment by keshav100** [comment]
by mistake i posted my problem there.

**Comment by raajnadar** [comment]
No one has that much time to click a link and help you. Issue template is important for us to debug.

**Comment by keshav100** [comment]
you keep away your self when you cant help me

**Comment by keshav100** [comment]
@raajnadar sorry bro! now my project running well
