### ISSUE TITLE
undefined is not an object (evaluating '_native.NavigationHelpersContext.Provider')

### ISSUE THREAD

**Issue by keshav100** [react-navigation/react-navigation#8352]
**Current Behavior**
I got error for header button then i just did update for all packages. then i stuck on this error

![photo_2020-05-27_19-35-27](https://user-images.githubusercontent.com/11971739/83120239-65df1200-a0ee-11ea-9ae6-be58137757a2.jpg)
**Expected Behavior**

- it should not show the bug

**Your Environment**
{
"main": "node_modules/expo/AppEntry.js",
"scripts": {
"start": "expo start",
"android": "expo start --android",
"ios": "expo start --ios",
"web": "expo start --web",
"eject": "expo eject"
},
"dependencies": {
"@expo/react-native-action-sheet": "^3.8.0",
"@react-native-community/async-storage": "^1.11.0",
"@react-native-community/datetimepicker": "^2.4.0",
"@react-native-community/masked-view": "^0.1.10",
"@react-navigation/bottom-tabs": "^5.5.0",
"@react-navigation/drawer": "^5.8.0",
"@react-navigation/material-bottom-tabs": "^5.2.8",
"@react-navigation/native": "^5.1.7",
"@react-navigation/native-stack": "^5.0.4",
"@react-navigation/stack": "^5.3.7",
"axios": "^0.19.2",
"base-64": "^0.1.0",
"expo": "~36.0.0",
"expo-camera": "^8.2.0",
"expo-image-picker": "^8.1.0",
"expo-linear-gradient": "~8.0.0",
"expo-location": "^8.1.0",
"expo-media-library": "^8.1.0",
"expo-permissions": "~8.0.0",
"expo-sqlite": "^8.1.0",
"firebase": "^7.14.5",
"galio-framework": "^0.6.3",
"moment": "^2.26.0",
"native-base": "2.13.8",
"react": "~16.9.0",
"react-dom": "~16.9.0",
"react-native": "https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz",
"react-native-circular-progress": "^1.3.6",
"react-native-elements": "^1.2.7",
"react-native-fetch-blob": "^0.10.8",
"react-native-gesture-handler": "^1.6.0",
"react-native-paper": "^3.9.0",
"react-native-safe-area-context": "^0.7.3",
"react-native-screens": "^2.8.0",
"react-native-simple-toast": "^1.1.2",
"react-native-storage": "^1.0.1",
"react-native-svg": "^12.1.0",
"react-native-web": "~0.11.7",
"react-navigation": "^4.3.9",
"react-navigation-stack": "^2.5.1",
"react-navigation-tabs": "^2.8.13",
"shortid": "^2.2.15",
"sqlite3": "^4.2.0",
"styled-components": "^5.1.1"
},

"devDependencies": {
"babel-preset-expo": "~8.1.0",
"@babel/core": "^7.8.6"
},
"private": true
}

**Comment by raajnadar** [comment]
Update to latest version `expo start -c`

**Comment by keshav100** [comment]
mother fucker why are you closing issue again and again

**Comment by keshav100** [comment]
dont close until i confirm it solved.

**Comment by satya164** [comment]
@keshav100 please be civil or you'll be blocked from this repo

**Comment by keshav100** [comment]
i have no time to post again and  again

**Comment by keshav100** [comment]
when he has no answer why he closing the issue

**Comment by keshav100** [comment]
please re open the issue is is not solved for me

**Comment by raajnadar** [comment]
https://github.com/react-navigation/react-navigation/issues/8225

https://github.com/react-navigation/react-navigation/issues/8169

Similar issue where upgrading to latest version & `expo start -c` worked. I already gave you the solution.

**Comment by satya164** [comment]
don't post again and again then. you need to search existing issues first before opening issues. maintainers don't have a lot of time to answer every question. and especially not when you use swear words. you're using the library for free, don't act entitled.

there's an issue template you need to follow when opening issues and provide repro if it's a bug. regardless, it's not a bug and you have outdated versions like he answered you.

**Comment by keshav100** [comment]
this small bug ruin my whole project. and this cant be so irresponsible.  I am not force anyone to this library opensource.  and i am asking to community not him. if he has not answer he must keep him self away. just closing the project. and do you this i have not any previous search?? i have search a lot yesterday . 5 time project re installed . do you think it is easy.    and this man just closing the issue without proper explanation.

**Comment by raajnadar** [comment]
**I gave you the solution & then I closed the issue**.

I closed it because this is a common issue of cache. And it is not a bug.

**Comment by ehsanagh** [comment]
I use these packages and I have the same issue here.

my code sample is
```
import React from 'react'
import { createBottomTabNavigator } from '@react-navigation/bottom-tabs'
import MainScreen from '../screens/main'

const BottomTab = createBottomTabNavigator()

export default (): React.ReactElement => {
    return (
        <BottomTab.Navigator
        initialRouteName='Home'
        >
            <BottomTab.Screen name="Home" component={MainScreen} />
        </BottomTab.Navigator>
    )
}
```

Any solution. I don't have expo at all.

**Comment by raajnadar** [comment]
@ehsanagh Try `npx react-native run-android --reset-cache` for android & `npx react-native run-ios --reset-cache` for ios.

**Comment by ehsanagh** [comment]
Weird but cleaning the cache manually and then restarting the simulator fixed the problem.
I confirm it's fine now. @raajnadar

**Comment by keshav100** [comment]
@raajnadar sorry for all bro! now my project running well. thank you for help
