### ISSUE TITLE
Swipe bug in Android 

### ISSUE THREAD

**Issue by Ashvinsolanki123** [react-navigation/react-navigation#8353]
**Current Behavior**

There is two case happen on my App while using Tab for first time after restart.
 
1) If the first action after restart is swiping, only the indicator moves - not the screen. Works in iOS.
2) First time moving tab transition is extremely slow.
 
So it's only when the app is started. If the app is on the background and brought back, it works.
If you click one of the navigation buttons, the swiping works again.

Here is my code for Tab navigation

> export default createMaterialTopTabNavigator({
> 	Home: {
> 		screen: DashboardStack,
> 		navigationOptions: () => ({
> 			tabBarIcon: getIcon.bind(null, "goals"),	
> 			tabBarLabel: i18n.t("t_goals"),
> 		})
> 	},
> 	ChatConversations: {
> 		screen: ConversationsScene,
> 		navigationOptions: () => ({
> 			tabBarIcon: getIcon.bind(null, "community"),	
> 			tabBarLabel: i18n.t("t_community"),
> 		})
> 	},
> 	Emergency: {
> 		screen: EmergencyStack,
> 		navigationOptions: () => ({
> 			tabBarIcon: getIcon.bind(null, "help"),					
> 			tabBarLabel: i18n.t("t_help"),
> 		})
> 	},
> 	Me: {
> 		screen: MeScene,
> 		navigationOptions: () => ({
> 			tabBarIcon: getIcon.bind(null, "face"),		
> 			tabBarLabel: i18n.t("t_me"),
> 		})
> 	},
> }, {
> 	initialRouteName: "Home",
> 	tabBarPosition: "bottom",
> 	swipeEnabled: true,
> 	animationEnabled: true,
> 	lazy: true,
> 	tabBarOptions: {
> 		showLabel: true,
> 		showIcon: true,
> 		pressColor: colors.robinEggBlue,
> 		pressOpacity: .8,
> 		scrollEnabled: false,
> 		inactiveTintColor: colors.lightslateGrey,
> 		activeTintColor: colors.robinEggBlue,
> 		activeBackgroundColor: colors.robinEggBlue,
> 		labelStyle: {
> 			textTransform: "capitalize",
> 			marginTop: 0,
> 			fontSize: fontSize.s12,
> 			fontWeight: "bold",
> 		},
> 		tabStyle: {
> 			height: 60,
> 			paddingTop: 6,
> 			paddingLeft: 2,
> 			paddingRight: 2,
> 			justifyContent: "flex-start",
> 		},
> 		iconStyle: {
> 			width: iconSize,
> 			height: iconSize,
> 		},
> 		renderIndicator: () => null,
> 		style: {
> 			backgroundColor: colors.white,
> 			paddingBottom: bottomUnsafeHeight
> 		},
> 		allowFontScaling: false,
> 	}
> })
> 

![navigation](https://user-images.githubusercontent.com/66064991/83131720-e9ecc600-a0fd-11ea-8d82-22f2fcbed2af.png)

**Expected Behavior**

- What do you expect should be happening?
- Tab navigation should first time as normally work on APP.

**Your Environment**
- "react-native": "^0.61.2",
- "react-navigation": "^4.0.10",
- "react-navigation-tabs": "^2.5.5",
- Android & Android 9

**Comment by Ashvinsolanki123** [comment]
Hello Guys 

As per your suggestion I have updated react-navigation-tabs lib to 2.8.13 as latest version from 2.5.5 but Still swipe issue exist in my app.

Issue: If the first action after restart is swiping, only the indicator moves - not the screen. Works in iOS.

Can you please help me?

Thanks

**Comment by satya164** [comment]
Closing since you haven't provided a repro. Please open a new issue with a minimal repro if you're still having problems.
