### ISSUE TITLE
How to use stack inside drawerContent?

### ISSUE THREAD

**Issue by diegolmello** [react-navigation/react-navigation#8355]
**Current Behavior**

https://snack.expo.io/@diegolmello/ba7e3c

It raises

> Another navigator is already registered for this container. You likely have multiple navigators under a single "NavigationContainer" or "Screen". Make sure each navigator is under a separate "Screen" container. See https://reactnavigation.org/docs/nesting-navigators for a guide on nesting.

**Expected Behavior**

To show a normal stack as a drawer.

**How to reproduce**

https://snack.expo.io/@diegolmello/ba7e3c

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |iOS 13.4.1
| @react-navigation/native       | 5.4.2
| @react-navigation/drawer       |5.7.7
| react-native-reanimated        |1.8.0
| react-native-gesture-handler   |1.6.1
| react-native-safe-area-context |1.0.2
| react-native-screens           |2.7.0
| react-native                   |0.62.2
| expo                           |
| node                           |10.20.1
| npm or yarn                    |yarn 1.16.0

**Comment by diegolmello** [comment]
Just tested and the problem persists.
I'm trying to achieve a master/detail layout like this:
![image](https://user-images.githubusercontent.com/804994/83195571-ce3eeb00-a110-11ea-9194-1718e3ea4a17.png)

This was made using react-navigation v4 and now we're upgrading to v5.
How can that be done?

I've tried drawer with `drawerType='permanent'`, two side-by-side stacks (which raises the same error) and a side view (which lacks the stack header).
Can you help?
Thanks! :)

**Comment by lucasfeijo** [comment]
@diegolmello Please tell me if you figure this out, or if you know how to embed a stack inside any other component in the navigation. I'm trying to embed a stack inside a formSheet style modal and I can't figure it out.

**Comment by satya164** [comment]
It's not possible to add navigators inside drawer content. You can achieve custom layouts using a custom router and custom navigator:

https://reactnavigation.org/docs/custom-routers
https://reactnavigation.org/docs/custom-navigators

For such a navigator, you can use the `TabRouter` and build your custom layout in the navigator.

**Comment by lucasfeijo** [comment]
@satya164 what about a navigator inside a formsheet style modal?

**Comment by satya164** [comment]
You need to build a custom navigator for that with 2 screens, one screen for content, other screen for the modal.

**Comment by diegolmello** [comment]
@lucasfeijo You can try something like this: https://github.com/react-navigation/react-navigation/blob/master/example/src/Screens/MasterDetail.tsx

It's far from ideal, but it works.

**Comment by lucasfeijo** [comment]
@diegolmello @satya164 I think I'm not expressing myself well enough. My goal is I wanna be able to, from react-navigation, display and control the children of this component:

```js
      <Modal
        visible={props.visible}
        animationType={'slide'}
        supportedOrientations={['portrait', 'landscape']}
        presentationStyle={'formSheet'}
      >
```

So that I can have a formSheet modal that has navigation inside it.

I can display a modal with the code above, but it can only have one static view, and it's not linked to the react-navigation routes either.

**Comment by diegolmello** [comment]
I'm not sure I got it, but it seems you want a navigation inside a modal.
You can create a stack inside another with `mode='modal'`.
It's not related to this issue though.

**Comment by Czarczynski** [comment]
@lucasfeijo Any progress here? I'm facing the same problem.

**Comment by lucasfeijo** [comment]
> @lucasfeijo Any progress here? I'm facing the same problem.

I thankfully don't work with react anymore, I'm free!
