### ISSUE TITLE
Customizing Header Tittle error: Cannot add a child that doesn't have a Yoganode

### ISSUE THREAD

**Issue by deathemperor** [react-navigation/react-navigation#8356]
**Current Behavior**

Couldn't add title as `<View><Text>My Title</Text></View>`. This works on web (and iOS?) but not on Android.

[Snack Link](https://snack.expo.io/@deathemperor/42c1f0)

**Expected Behavior**

Title <Text> can be wrap under <View> so I can style the header

**How to reproduce**

[Snack Link](https://snack.expo.io/@deathemperor/42c1f0) 

Run it on android and the uncaught error will appear.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| Android                 | 
| @react-navigation/native       | 5.4
| @react-navigation/stack        | 5.0
| react-native-gesture-handler   | 1.6
| react-native-safe-area-context | 0.7.3
| react-native-screens           | 2.2
| react-native                   | 0.61
| expo                           | 37.0.1
| node                           | 12.10.0
| yarn                    | 1.9.4

**Comment by raajnadar** [comment]
https://reactnavigation.org/docs/stack-navigator/#title

Only accepts string you can't pass react element.

Use https://reactnavigation.org/docs/stack-navigator/#headertitlestyle to style the title.

Views nested inside text component don't work in android https://github.com/facebook/react-native/issues/18491
