### ISSUE TITLE
Avoid Navigation to the same screen which is visible 

### ISSUE THREAD

**Issue by BobFactory** [react-navigation/react-navigation#8362]
**Current Behavior**
I have a screen which shows multiple lists being populated from different API's. Each API has a common error handler function which handles the errors. In case of a 401 error , the controller adds a navigation to the login screen , using this code mentioned below. 

```
navigation.dispatch(CommonActions.reset({
    index: 0, routes: [{ name: "Auth" }]
}));
```

Since multiple API's are being called in at the same time, they have a slight difference in their response and eventually end up calling the above mentioned code. This leads to the screen being navigated the AUTH screen, not ones but multiple times. 

**Expected Behavior**
In case the route is the current route, the present route should get the callback or a re-render since it is already present rather than pushing a new route with the same name. 

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| @react-navigation/native       | 5.1.6
| @react-navigation/stack        | 5.2.13
| react-native-gesture-handler   | 1.6.1
| react-native-safe-area-context | 0.7.3
| react-native-screens           | 2.7.0
| react-native                   | 0.62.2
| node                           | 12.16.3
| npm or yarn                    | 1.19.1

**Comment by BobFactory** [comment]
Updated to the latest versions and checked. Still the same issue. 

```
"@react-navigation/native": "^5.5.0",
"@react-navigation/stack": "^5.4.1",
```

**Comment by raajnadar** [comment]
If you don't to same page to stack one on another (or add up to the history again & again) use `navigation.navigate` because it go back to the screen if it is already present in the history & it won't be added in the history multiple times.

Eg: -

A -> B -> C  // is your history
`navigation.navigate('A')` // A
`navigation.navigate('B')` // A -> B
`navigation.navigate('D')` // A -> B -> C -> D if D exists

Try this out and let me know if that worked.

**Comment by BobFactory** [comment]
@raajnadar I know that navigate function does not push another route the stack , but the main problem is I need to reset the stack in this particular action. 

Basically this is a 401 action from the server and I need to clear all the existing routes and push the user to the starting route .

**Comment by satya164** [comment]
It's upto you to check current state and see if you wanna preserve it or not https://reactnavigation.org/docs/navigation-prop#dispatch

Also you should conditionally define screens rather than using reset https://reactnavigation.org/docs/auth-flow
