### ISSUE TITLE
Flash,Related to the bottom physical navigation button of the mobile phone

### ISSUE THREAD

**Issue by ngxu** [react-navigation/react-navigation#8368]
"react-navigation": "^4.3.9",

When I don't use the bottom navigation button, there's a problem.

When I use the bottom navigation button, it's normal.

I tested two phones, one with a problem (Android 10) and one without a problem (Android 7).

![8F0496D987206A9D8212E121D6023C44](https://user-images.githubusercontent.com/43433064/83494221-880ad280-a4e8-11ea-9029-c88437e694ad.gif)

**Comment by satya164** [comment]
Closing since you didn't fill the issue template or provide any repro.

**Comment by sivarajng** [comment]
@ngxu I also had exact issue in Android 10 and spent around 3-4 days. Finally found that In case a (Screen's/Page's) View don't have a backgroundColor then that screen flashes like in the above screenshot.

Can you try the below Solution it worked:
in case you have as below:
`render() { return <View style={{ flex:1 }} > .............`

then change it to :
`render() { return <View style={{ flex:1, backgroundColor: 'white' }} > .............`

**Comment by ngxu** [comment]
@sivarajng @satya164 

As you said, it is also related to the style "elevation". When I set the elevation of the next navigation to be greater than the elevation of the previous page, and then add the background color to the outermost view, it will not Flashes.
Of course, this blinking only appears on Android phones, maybe Android 10 and above, and it is also related to the mobile phone's own navigation buttons at the bottom.

**Comment by ngxu** [comment]
I found the cause of the problem, which is the problem of react-native-swiper.
After I annotate it, there is no problem

**Comment by ngxu** [comment]
In the end I used `react-native-swiper`, and I added `"style={{elevation:1}}"` to the outermost view of the flashing page to solve the problem

**Comment by A-ANing** [comment]
"react-native-swiper": "^1.6.0-nightly.3",
"react-navigation":"^5.6.1";

At present, I still have the same problem with the above version. Only when the bottom button of the mobile phone is hidden and the 'swiper' is satisfied, it is normal when the bottom button of the phone is displayed.

**Comment by wutiange** [comment]
我的也是这样，也是华为的，我虽然解决了，但是一直不知道原因。请问提问者找到原因了嘛，我试了试 react-native-swiper 发现这个的确会出现闪烁，但跟显示上一个页面的内容有点不一样。

So is mine. It's Huawei's too. Although I've solved the problem, I still don't know why. Did the questioner find out the reason? I tried react native swiper and found that it did flicker, but it was a little different from the content displayed on the previous page.

**Comment by marlti7** [comment]
> 我的也是这样，也是华为的，我虽然解决了，但是一直不知道原因。请问提问者找到原因了嘛，我试了试 react-native-swiper 发现这个的确会出现闪烁，但跟显示上一个页面的内容有点不一样。
> 
> So is mine. It's Huawei's too. Although I've solved the problem, I still don't know why. Did the questioner find out the reason? I tried react native swiper and found that it did flicker, but it was a little different from the content displayed on the previous page.

怎么解决的？

**Comment by A-ANing** [comment]
> 我的也是这样，也是华为的，我虽然解决了，但是一直不知道原因。请问提问者找到原因了嘛，我试了试 react-native-swiper 发现这个的确会出现闪烁，但跟显示上一个页面的内容有点不一样。
> 
> So is mine. It's Huawei's too. Although I've solved the problem, I still don't know why. Did the questioner find out the reason? I tried react native swiper and found that it did flicker, but it was a little different from the content displayed on the previous page.

你是不是也是将手机系统导航方式选择为手势导航就闪烁  用按键导航方式就不闪烁

Did you also choose gesture navigation as the navigation method of the mobile phone system, and then flash? Use the button navigation method to not flash

**Comment by A-ANing** [comment]
> 怎么解决的？
我当初是每个页面最外层的view用`"style={{elevation:1}}"`  配上`backgroundColor`来解决的

**Comment by marlti7** [comment]
> > 我的也是这样，也是华为的，我虽然解决了，但是一直不知道原因。请问提问者找到原因了嘛，我试了试 react-native-swiper 发现这个的确会出现闪烁，但跟显示上一个页面的内容有点不一样。
> > So is mine. It's Huawei's too. Although I've solved the problem, I still don't know why. Did the questioner find out the reason? I tried react native swiper and found that it did flicker, but it was a little different from the content displayed on the previous page.
> 
> 你是不是也是将手机系统导航方式选择为手势导航就闪烁 用按键导航方式就不闪烁
> 
> Did you also choose gesture navigation as the navigation method of the mobile phone system, and then flash? Use the button navigation method to not flash

就是切换时候 会闪烁黄色 感觉是不是默认切换动画的问题？

**Comment by A-ANing** [comment]
> 就是切换时候会闪烁黄色感觉是不是替代切换动画的问题？

目前我也不太清楚，只知道可能是react-native-swiper引起的，可以换一个轮播组件试试

**Comment by marlti7** [comment]
我用5.x 安卓默认切换动画的问题 设置下screenOptions={{
                    cardStyleInterpolator: CardStyleInterpolators.forHorizontalIOS,
                    // cardOverlayEnabled: true,
                    // ...MyTransition,
                }} 
                就正常了
