### ISSUE TITLE
Flashing white when switching to a new page (Android)

### ISSUE THREAD

**Issue by iamtortue001101** [react-navigation/react-navigation#8371]
**Current Behavior**

https://www.youtube.com/watch?v=l_u1xJ7JgTs

**Expected Behavior**

- Don't let the white light burn when switching to a new page

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Android
| @react-navigation/native       | 5.5.0
| @react-navigation/stack        | 5.4.1
| react-native-gesture-handler   | 1.6.1
| react-native-safe-area-context | 2.0.0
| react-native-screens           | 2.8.0
| react-native                   | 0.62.2
| expo                           |  -
| node                           | v12.16.2
| npm or yarn                    | yarn 1.22.4

**Comment by iamtortue001101** [comment]
> Found the following packages mentioned in the issue, but couldn't find version numbers for them:
> 
> * `@react-navigation/native`
> 
> Can you update the issue to include version numbers for those packages? The version numbers must match the format 1.2.3.
> 
> The versions mentioned in the issue for the following packages differ from the latest versions on npm:
> 
> * `@react-navigation/stack` (found: `5.4.0`, latest: `5.4.1`)
> 
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?

yes, the problem persists.

**Comment by iamtortue001101** [comment]
`import * as React from 'react';
import { createAppContainer } from 'react-navigation';
import { createStackNavigator } from 'react-navigation-stack';
import { createMaterialBottomTabNavigator } from "react-navigation-material-bottom-tabs";
import Icons from 'react-native-vector-icons/Feather';

import Home from './Home/Home';
import Search from './Search/Search';
import Login from './Auth/Login';
import Register from './Auth/Register';
import Account from './Auth/Account';
import Movements from './Movements/Movements';
import PrivateMessage from './PrivateMessage/PrivateMessage';

const tabBarIcon = name => ({ tintColor }) => (
  <Icons style={{ backgroundColor: 'transparent' }} name={name} color={tintColor} size={25} />
);

const AccountStack = createStackNavigator({
  Account: {
    screen: Account
  },
}, {
  defaultNavigationOptions: {
    headerShown: false
  },
  cardStyle: {
	  backgroundColor: 'transparent'
  }
});

const BottomNavigator = createMaterialBottomTabNavigator({
  Home: {
    screen: Home,
    navigationOptions: ({ navigation }) => ({
      tabBarIcon: tabBarIcon('home'),
      title: "Anasayfa"
    })
  },
  Search: {
    screen: Search,
    navigationOptions: ({ navigation }) => ({
      tabBarIcon: tabBarIcon('search'),
      title: "Arama"
    })
  },
  Post: {
    screen: Home,
    navigationOptions: ({ navigation }) => ({
      tabBarIcon: tabBarIcon('plus-square'),
      title: "Post"
    })
  },
  Movements: {
    screen: Movements,
    path: 'Hareketler',
    navigationOptions: ({ navigation }) => ({
      tabBarIcon: tabBarIcon('heart'),
      title: "Hareketler"
    })
  },
  Account: {
    screen: AccountStack,
    path: 'account',
    navigationOptions: ({ navigation }) => ({
      tabBarIcon: tabBarIcon('user'),
      title: "Hesabım"
    })
  },
}, {
  backBehavior: 'history',
  initialRouteName: 'Home',
  shifting: true,
});


const MainNavigator = createStackNavigator({
  BottomNavigator: {
    screen: BottomNavigator,
    path: 'home'
  },
  PrivateMessage: {
    screen: PrivateMessage,
    path: 'PrivateMessage/:userId'
  },
  Login: {
    screen: Login,
    path: 'Login'
  },
  Register: {
    screen: Register,
    path: 'Register'
  },
}, {
  backBehavior: 'history',
  initialRouteName: 'BottomNavigator',
  defaultNavigationOptions: {
    headerShown: false
  },
  cardStyle: {
	  backgroundColor: 'transparent'
  }
});

export default createAppContainer(MainNavigator);
`

**Comment by satya164** [comment]
Your repro doesn't run. Besides, you need to use proper themes for dark theme https://reactnavigation.org/docs/4.x/themes

**Comment by iamtortue001101** [comment]
> Your repro doesn't run. Besides, you need to use proper themes for dark theme https://reactnavigation.org/docs/4.x/themes

Thank you.

`let Navigation = createAppContainer(MainNavigator);`
`export default () => <Navigation theme="dark" />;`
