### ISSUE TITLE
How do I embed a navigator inside a RN Modal with presentationStyle={"formSheet"}

### ISSUE THREAD

**Issue by lucasfeijo** [react-navigation/react-navigation#8372]
**Current Behavior**

- What code are you running and what is happening?
  - I'm unable to render a sub-navigator, I mean, a navigator that's embedded in another. This is commonplace in iOS development, you simply instantiate a UINavigationController and place its view wherever you want.
  - When I do so, the warning that only a single navigator container can exist within the app keeps popping up, which is fine if it worked 100%, but there are slight issues that I'm gonna describe further.
  - The header bar is rendered with too much height, it feels like it's taking the space to avoid the notch even though it's not even close, because it's in a formSheet in the middle of the screen.
- Include a screenshot or video if it makes sense.
<img width="360" alt="Screen Shot 2020-06-02 at 6 41 58 PM" src="https://user-images.githubusercontent.com/4157166/83572885-beece280-a500-11ea-8054-90a558544434.png">

**Expected Behavior**

- What do you expect should be happening?
  - When I started down this path, I wanted to make the modal itself using react-navigation, but the great library limitations made me go the route I went, rendering the modal using RN, and placing the navigation container inside it.
- Include a screenshot or video if it makes sense.
  - n/a

**How to reproduce**

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | both
| react-navigation               | 4.2.2
| react-navigation-stack         | 1.7.3
| react-native                   | 0.59.10
| node                           | 8.10.0

**My Solution**

On the screen from where I launch the modal:

```js
const [showingRoomInfoPopover, setShowingRoomInfoPopover] = useState(false)
// then render:
{showingRoomInfoPopover && (<NavigableModalRoomInfo
        roomInfo={info as Room}
        visible={showingRoomInfoPopover}
        onClose={() => setShowingRoomInfoPopover(false)}
      />)}
```
_By the way, if I don't wrap the NavigableModalRoomInfo with that condition, it never shows up._

Then that component is the following:

```js
export class NavigableModalRoomInfo extends React.Component<RoomInfoProps & DismissableModal> {
  shouldComponentUpdate() {
    return false
  }

  injectParams = (params: any, navigation) => {
    navigation.state.params = params
    return navigation
  }

  render() {
    const Children = createAppContainer(
      createStackNavigator({
        index: {
          screen: ({ navigation }) => (
            <NavigableRoomInfo {...this.props} navigation={this.injectParams(this.props, navigation)} />
          ),
          navigationOptions: ({ navigation }) => {
            navigation = this.injectParams(this.props, navigation)
            const roomInfo = navigation!.state!.params!.roomInfo
            return {
              ...defaultNav,
              headerLeft: () => <BackButton useX onPress={this.props.onClose} />,
              title: `${roomInfo.name} Options`
            }
          }
        },
        [NC.SCREEN_ROOM_ROSTER]: { screen: NavigableRoomRoster },
        [NC.SCREEN_ROOM_NOTIFICATION_PREFERENCES]: { screen: NavigableRoomNotificationPreferences },
        [NC.SCREEN_ROOM_EDIT]: { screen: NavigableRoomEdit }
      })
    )

    return (
      <Modal
        visible={this.props.visible}
        animationType={'slide'}
        supportedOrientations={['portrait', 'landscape']}
        presentationStyle={'formSheet'}
        onRequestClose={this.props.onClose}
        onDismiss={this.props.onClose}
      >
        <Children />
      </Modal>
    )
  }
}
```

The `shouldComponentUpdate` method is there because otherwise the component keeps re-rendering and the navigation context is lost, taking the user back to the initial route. I would love to know how to do this properly though.

Notice how I'm having to implement `navigationOptions` on the initial view even though I do implement it in the component itself, but when I moved the component into this navigation, it stopped showing the correct navigationOptions, but only the initial route! Other routes work fine and can have the header set up in their own file.

Also notice in the screenshot how the header is taller than it should be. Check out what happens when I try to set a headerStyle with an appropriate maxHeight:

<img width="361" alt="Screen Shot 2020-06-02 at 6 54 39 PM" src="https://user-images.githubusercontent.com/4157166/83573852-9bc33280-a502-11ea-9e1e-a29db5d551d8.png">

As you can see, I'm not doing things properly, but if I can make it work with minor adjustments, that's how I'm gonna go. But if you can help me understand how to do this the right way, I could go with that too.

Thanks!

PS: Before anyone tells me to use `mode: 'modal'`, that does not have the same visual effect as RN's Modal with presentationStyle formSheet.

**Comment by lucasfeijo** [comment]
**Not a bug, it got tagged automatically.**

**Comment by satya164** [comment]
https://reactnavigation.org/docs/4.x/custom-navigators#extending-navigators

**Comment by lucasfeijo** [comment]
@satya164 I followed the guide you linked but it's not clear at all how to implement what I need, if I could make that background screen invisible and its animation with duration=0 that would be perfect:

![Simulator Screen Shot - iPad Pro (9 7-inch) - 2020-06-06 at 17 48 16](https://user-images.githubusercontent.com/4157166/83954253-0daabd00-a81e-11ea-8aa4-b927cf1c7737.png)

**Comment by lucasfeijo** [comment]
Nevermind, I figured it out and wrote a guide: https://stackoverflow.com/q/62257644/1346618
