### ISSUE TITLE
example can't run

### ISSUE THREAD

**Issue by dfqin** [react-navigation/react-navigation#8373]
run as the document
int root pro:  yarn
then:   yarn example start
it show error and log as bellow:
`
yarn example start
$ yarn --cwd example start
error An unexpected error occurred: "Cannot create property '-registry-npmjs-org' on string '{\"-registry-npmjs-org\":\"\"}'".
info If you think this is a bug, please open a bug report with the information provided in "/Users/user/Desktop/temp/react-navigation/example/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
`

[yarn-error.log](https://github.com/react-navigation/react-navigation/files/4720766/yarn-error.log)

**Comment by raajnadar** [comment]
This is not related to react navigation try creating an issue in yarn repo https://github.com/yarnpkg/yarn/issues
