### ISSUE TITLE
Drawer not changing position from left to right

### ISSUE THREAD

**Issue by geekrepos** [react-navigation/react-navigation#8374]
I am trying to shift drawer from left to right, but it isn't working. However when I am trying to shift from right to left, its working fine. I have already tried in physical device and running in emulator, but nothing worked.

**Current Behavior**

- Drawer is shifted from right to left, but is not shifting from left to right.

![ezgif-4-a4c858d91297](https://user-images.githubusercontent.com/53126714/83626104-99b8ac80-a5b2-11ea-85c3-edcd523fa11e.gif)

**Expected Behavior**

- Drawer should shift whichever side shifted

**How to reproduce**

- Create a new project with following configurations (React Navigation 5).
- Use this code:
```
import React,{Component} from 'react';
import {View, TouchableOpacity, Text} from "react-native";
import {createDrawerNavigator} from "@react-navigation/drawer";
import {NavigationContainer} from '@react-navigation/native';
const initialPosition = 'left';

function DrawerContent({pos, moveDrawer}) {
    const position = pos=='right'?'left':'right';
    return (
        <View style={{flex:1, alignItems:'center', justifyContent:'center'}}>
            <TouchableOpacity onPress={()=>moveDrawer(position)} >
                <Text style={{color:'#1d7bc2'}}>Move me {position}</Text>
            </TouchableOpacity>
        </View>
    )
}

class App extends Component {
    state = {pos: initialPosition}
    render(){
        const Drawer = createDrawerNavigator();
        return(
            <NavigationContainer>
                <Drawer.Navigator drawerPosition={this.state.pos}
                                  drawerStyle={{width: '40%'}}
                                  drawerContent={props =>
                                      <DrawerContent pos={this.state.pos}
                                                     moveDrawer={(pos)=>this.setState({pos})} {...props} />
                                  }>
                    <Drawer.Screen name={'d'}
                                   component={({navigation: {openDrawer}})=>(
                                       <TouchableOpacity style={{backgroundColor:'black', padding:10, alignSelf:'center'}}
                                                         onPress={openDrawer} >
                                           <Text style={{color:'white'}}>Open Drawer</Text>
                                       </TouchableOpacity>
                                   )} />
                </Drawer.Navigator>
            </NavigationContainer>
        )
    }
}

export default App;

```

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |Android
| @react-navigation/native       |^5.3.0
| @react-navigation/drawer       |^5.7.5
| react-native-reanimated        |^1.8.0
| react-native-gesture-handler   |^1.6.1
| react-native-safe-area-context |^0.7.3
| react-native-screens           |^2.5.0
| react-native                   |0.62.2
| node                           |v8.16.2
| npm or yarn                    |npm

**Comment by geekrepos** [comment]
Yes issue still persists even after updating both dependencies mentioned.
"@react-navigation/drawer": "^5.8.1",
"@react-navigation/native": "^5.5.0",

**Comment by raajnadar** [comment]
Duplicate https://github.com/react-navigation/react-navigation/issues/8358

**Comment by geekrepos** [comment]
> Duplicate #8358

I tried updating all dependencies even though its not working. Please fix this issue asap. 

"@react-navigation/core": "^5.10.0",
"@react-navigation/drawer": "^5.8.2",
"@react-navigation/native": "^5.5.1",

![my](https://user-images.githubusercontent.com/53126714/85153078-609b6000-b273-11ea-8767-257cdd670616.gif)

**Comment by raajnadar** [comment]
It's already fixed.

**Comment by geekrepos** [comment]
I saw you have merged the pull request regarding to this issue. But I have created this fresh project yesterday. 
Here is my package.json:
```
{
  "name": "Practice",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@react-native-community/masked-view": "^0.1.10",
    "@react-navigation/core": "^5.10.0",
    "@react-navigation/drawer": "^5.8.2",
    "@react-navigation/native": "^5.5.1",
    "react": "16.11.0",
    "react-native": "0.62.2",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-reanimated": "^1.9.0",
    "react-native-safe-area-context": "^3.0.5",
    "react-native-screens": "^2.8.0"
  },
  "devDependencies": {
    "@babel/core": "^7.10.2",
    "@babel/runtime": "^7.10.2",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-jest": "^26.0.1",
    "eslint": "^7.2.0",
    "jest": "^26.0.1",
    "metro-react-native-babel-preset": "^0.59.0",
    "react-test-renderer": "16.11.0"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

Node Version: v10.19.0
NPM Version: 6.14.5

**Comment by raajnadar** [comment]
You need to use React Context Api. You are passing your function through initialParams prop it will only fire once may be that is the issue in you case.

**Comment by geekrepos** [comment]
Can you please provide me a working example. I have modified your snippet. 
Please see this: https://snack.expo.io/3Mswy0K1Z

**Comment by ZainAliSyed24** [comment]
> I saw you have merged the pull request regarding to this issue. But I have created this fresh project yesterday.
> Here is my package.json:
> 
> ```
> {
>   "name": "Practice",
>   "version": "0.0.1",
>   "private": true,
>   "scripts": {
>     "android": "react-native run-android",
>     "ios": "react-native run-ios",
>     "start": "react-native start",
>     "test": "jest",
>     "lint": "eslint ."
>   },
>   "dependencies": {
>     "@react-native-community/masked-view": "^0.1.10",
>     "@react-navigation/core": "^5.10.0",
>     "@react-navigation/drawer": "^5.8.2",
>     "@react-navigation/native": "^5.5.1",
>     "react": "16.11.0",
>     "react-native": "0.62.2",
>     "react-native-gesture-handler": "^1.6.1",
>     "react-native-reanimated": "^1.9.0",
>     "react-native-safe-area-context": "^3.0.5",
>     "react-native-screens": "^2.8.0"
>   },
>   "devDependencies": {
>     "@babel/core": "^7.10.2",
>     "@babel/runtime": "^7.10.2",
>     "@react-native-community/eslint-config": "^2.0.0",
>     "babel-jest": "^26.0.1",
>     "eslint": "^7.2.0",
>     "jest": "^26.0.1",
>     "metro-react-native-babel-preset": "^0.59.0",
>     "react-test-renderer": "16.11.0"
>   },
>   "jest": {
>     "preset": "react-native"
>   }
> }
> ```
> 
> Node Version: v10.19.0
> NPM Version: 6.14.5
> 
> Code:
> 
> ```
> import React, {Component} from 'react';
> import { Button, View, Text } from 'react-native';
> import {createDrawerNavigator, DrawerItem} from '@react-navigation/drawer';
> import { NavigationContainer } from '@react-navigation/native';
> 
> function HomeScreen({ navigation, route:{params: {changePosition}} }) {
>     return (
>         <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
>             <Button
>                 onPress={() => navigation.toggleDrawer()}
>                 title="Open Drawer"
>             />
>             <View style={{marginTop:20}}/>
>             <Button
>                 onPress={changePosition}
>                 title={'Change Drawer Position'}
>             />
>         </View>
>     );
> }
> 
> const Drawer = createDrawerNavigator();
> 
> export default class App extends Component {
>     state = {
>         position: 'left'
>     }
>     changePosition(){
>         this.setState({position: this.state.position==='right'?'left':'right'}, ()=>{
>             alert("Drawer Position: " + this.state.position);
>         });
>     }
>     render(){
>         return (
>             <NavigationContainer>
>                 <Drawer.Navigator drawerPosition={this.state.position} initialRouteName="Home">
>                     <Drawer.Screen name="Home" component={HomeScreen}
>                                    initialParams={{changePosition:this.changePosition.bind(this)}} />
>                 </Drawer.Navigator>
>             </NavigationContainer>
>         );
>     }
> }
> ```

I have reinstalled all new library with new versions 

"@react-native-community/masked-view": "^0.1.10”,
"react-native-reanimated": "^1.13.0",
"react-native-safe-area-context": "^3.1.6",
"react-native-screens": "^2.10.1”,
"@react-navigation/drawer": "^5.9.0",
"@react-navigation/native": "^5.7.3",
"@react-navigation/stack": "^5.9.0",

Still facing same issue , When i change **drawerPosition left to right drawer not opening at right position** 

It's works only when i kill my application and come back again so it start working .

**Comment by geekrepos** [comment]
@raajnadar  Please reopen this issue

**Comment by geekrepos** [comment]
> You need to use React Context Api. You are passing your function through initialParams prop it will only fire once may be that is the issue in you case.

If it is, how am I able to change position from right to left again using same function.

**Comment by vocuzi** [comment]
Facing the same issue!

**Comment by Pandit2903** [comment]
facing same issue ........

**Comment by ZainaliSyed** [comment]
> again

can you please your all versions details so i can have same dependency installed

**Comment by mas1515** [comment]
facing same issue @geekrepos

**Comment by mas1515** [comment]
"dependencies": {
    "@react-native-community/masked-view": "^0.1.10",
    "@react-navigation/drawer": "^5.9.0",
    "@react-navigation/native": "^5.7.3",
    "@react-navigation/stack": "^5.9.0",
    "react": "16.13.1",
    "react-native": "0.63.2",
    "react-native-gesture-handler": "^1.8.0",
    "react-native-reanimated": "^1.13.0",
    "react-native-safe-area-context": "^3.1.7",
    "react-native-screens": "^2.10.1"

**Comment by ravipanchal-in** [comment]
I am also facing same issue, please reopen this.

**Comment by Unknown051** [comment]
Same Here .... 
no drawer on right ..

**Comment by drfbwilliams** [comment]
"@react-navigation/drawer": "^5.11.4",

Still nothing on the right..... How is this remaining closed?

**Comment by akramyounes** [comment]
hi there
i do it like this
import  React,{useState} from 'react';
import { Button, View, Dimensions } from 'react-native';
import { createDrawerNavigator } from '@react-navigation/drawer';
import { NavigationContainer } from '@react-navigation/native';

const {width,height} = Dimensions.get('window');
const DrawerWidth = width * 0.75;


function HomeScreen({ navigation }) {
  return (
    <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
      <Button
        onPress={() => navigation.navigate('Notifications')}
        title="Go to notifications"
      />
    </View>
  );
}

function NotificationsScreen({ navigation }) {
  return (
    <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
      <Button onPress={() => navigation.goBack()} title="Go back homeee" />
    </View>
  );
}

const Drawer = createDrawerNavigator();

export default function App() {
  const [dir,setDir] = useState('right');
  return (
    <NavigationContainer>
      <Drawer.Navigator initialRouteName="Home" drawerPosition={dir} 
                        drawerStyle={{width:DrawerWidth, 
                                      left : dir ==="left" ? -DrawerWidth : width ,
                                      }} >

        <Drawer.Screen name="Home" component={HomeScreen} />
        <Drawer.Screen name="Notifications" component={NotificationsScreen} />
      </Drawer.Navigator>
    </NavigationContainer>
  );
}

**Comment by zhGio** [comment]
Guys this still isn't fixed..

**Comment by raajnadar** [comment]
keep in mind we cannot dynamically change the position of drawer. If you still have any issue create a new issue or discussion with more info.

If you say you are not able to use position right, a PR was made to fix that issue. Use the latest version to get that issue fixed.

**Comment by avinash-synapsesai** [comment]
> keep in mind we cannot dynamically change the position of drawer. If you still have any issue create a new issue or discussion with more info.
> 
> If you say you are not able to use position right, a PR was made to fix that issue. Use the latest version to get that issue fixed.
> 
> To answer the OPs question,
> 
> You can use two drawers and create a function to find which drawer to open left or right this is the only possible answer I believe you can use.

First of all very much thanks for replying. You could have told this earlier, since I created this issue. So much conversation was going in this thread but no one was replying, and that's sad.

**Comment by raajnadar** [comment]
@avinash-synapsesai one of the user in this thread already confirmed that he had to kill the app and restart the application to change the drawer position.

**Comment by zhGio** [comment]
@raajnadar thanks, that does indeed help.

**Comment by hjchoudry** [comment]
to open the drawer from the right side just add:    drawerType="front"

**Comment by juan-alternova** [comment]
Exactly. Add drawerType = 'right' and close the app and when we open it again we would have our drawer on the right

**Comment by azzozhsn** [comment]
OK, but 

`drawerStyle={{backgroundColor: 'transparent'}}`

doesn't work with

`drawerType='right'`

**Comment by Ruturaj2728** [comment]
> to open the drawer from the right side just add: drawerType="front" and drawerPosition="right"

You should have to use 'back' not 'front' then it will work perfectly

**Comment by ankitpmi** [comment]
> > to open the drawer from the right side just add: drawerType="front" and drawerPosition="right"
> 
> You should have to use 'back' not 'front' then it will work perfectly

it's work for me

**Comment by HamzaAitOumghar** [comment]
```
 "@paraboly/react-native-card": "github:Paraboly/react-native-card#expo",
    "@react-navigation/native": "^5.1.3",
    "@react-navigation/stack": "^5.2.9",
    "@react-navigation/drawer": "^5.4.0",
    "axios": "^0.21.1",
    "expo": "~42.0.1",
    "expo-status-bar": "~1.0.4",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz",
    "react-native-gesture-handler": "~1.10.2",
    "react-native-loading-spinner-overlay": "^2.0.0",
    "react-native-paper": "^4.9.2",
    "react-native-screens": "~3.4.0",
    "react-native-web": "~0.13.12",
    "react-redux": "^7.2.4",
    "redux": "^4.1.1",
    "redux-thunk": "^2.3.0",
    "react-navigation-drawer": "^2.4.9",
    "react-native-reanimated": "^2.1.0"
```

```
<Drawer.Navigator
      drawerContent={(props) => <DrawerContainer {...props} />}
      screenOptions={{
        drawerPosition: "right",
        drawerType: "back",
        drawerStatusBarAnimation: "fade",
      }}
    >
```

still not working for me

**Comment by alishmoldakhmet** [comment]
<Drawer.Navigator
        initialRouteName="MainPage"
        drawerContentOptions={{
          drawerType:"back",
          drawerPosition: "right",
        }}
      >

**Comment by Abdurrahman-Alizada** [comment]
@alishmodakhmet Thanks... It did not work as drawerContentOptions but worked in screenOption as drawerContentOptions is deprecated in latest versions.

**Comment by kotsh23** [comment]
in 2024 fixs

<Drawer.Navigator
      screenOptions={{
        drawerType: "front",
        drawerPosition: "right",
      }}
      drawerContent={(props) => <DrawerContent {...props} />}
    >
