### ISSUE TITLE
[V4] Error with SafeView and RN 62.2 undefined evaluating measureInWindow

### ISSUE THREAD

**Issue by tjlondon-npauctions** [react-navigation/react-navigation#8376]
**Current Behavior**
After upgrading from RN 0.60.5 to 0.62.2 I'm getting the following error when trying to render material bottom tabs. I've upgraded both react-native-safe-area-view and react-native-safe-area-context to the latest release.

- What code are you running and what is happening?

My TabNavigator
```
const AppNavigator = createMaterialBottomTabNavigator({
  History: {
    screen: HistoryStack,
    navigationOptions: {
      tabBarIcon: ({ ...props }) => <TabBarIcon name="list" {...props} />,
      tabBarColor: '#222222',
    },
  },
  Account: {
    screen: AccountStack,
    navigationOptions: {
      tabBarIcon: ({ ...props }) => <TabBarIcon name="user" {...props} />,
      tabBarColor: '#222222',
    },
  },
}, {
  initialRouteName: 'History',
  activeTintColor: constants.colors.primary,
  inactiveTintColor: '#ffffff',
  barStyle: { backgroundColor: 'black' },
  tabBarIcon: true,
  shifting: true,
  labeled: true,

  inactiveBackgroundColor: constants.colors.secondary,
  tabBarOptions: {
    inactiveTintColor: '#ffffff',
    activeBackgroundColor: '#e32b24',
  },
});
```

- Include a screenshot or video if it makes sense.
![Screenshot_1591206513](https://user-images.githubusercontent.com/6552733/83670695-69f4af00-a588-11ea-8089-a9be9cfc75e5.png)

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Android 
| react-navigation               | 4.3.9
| react-navigation-stack         | 2.5.1
| react-navigation-material-bottom-tabs          | 2.2.12
| react-native-reanimated        | 1.9.0
| react-native-gesture-handler   | 1.4.1
| react-native-safe-area-context | 3.0.2
| react-native-screens           | 2.8.0
| react-native                   | 0.62.2
| node                           | 10
| npm or yarn                    | npm

**Comment by satya164** [comment]
Material Bottom Tabs comes from react native paper. Upgrade react native paper or open an issue in react native paper repo.

**Comment by t407289575** [comment]
same problem +1
