### ISSUE TITLE
There is no actual support for going back to specific screen in v5.x.x

### ISSUE THREAD

**Issue by lukebars** [react-navigation/react-navigation#8382]
**Current Behavior**

- There is no actual method for going back to specific screen. This is a revised issue, similar to #8108

`v4.x` supported this
![image](https://user-images.githubusercontent.com/46403446/83744186-6df5ff00-a664-11ea-818d-df2b70c12f4f.png)

While in `v5.x` there seems to be some kind of mistake, because documentation suggests that we use `navigate` to go back to specific screen.
![image](https://user-images.githubusercontent.com/46403446/83744271-88c87380-a664-11ea-9746-61270ff4423d.png)

This seems not right and doesn't work in a way it should work.

**Expected Behavior**

- Going back to a specific screen by passing a key to `goBack`

**Comment by raajnadar** [comment]
`navigation.navigate` will go back to the route if it is already present in the history

A -> B -> C -> D

`navigation.navigate('B')` // Now the history will be A -> B 
`navigation.navigate('A')` // Now the history will be A

IDK why are you using key when it is very straightforwad with name.

Try this snack https://snack.expo.io/@raajnadar/875aa7

**Comment by lukebars** [comment]
> `navigation.navigate` will go back to the route if it is already present in the history
> 
> A -> B -> C -> D
> 
> `navigation.navigate('B')` // Now the history will be A -> B
> `navigation.navigate('A')` // Now the history will be A
> 
> IDK why are you using key when it is very straightforwad with name.
> 
> Try this snack https://snack.expo.io/@raajnadar/875aa7

I'm using screen names too. That's just screenshots from docs. 

Thanks, looks like it's working.

**Comment by congshengwu** [comment]
Using screen names to go to a specific screen is also working for me. Thanks for saving my time.

I am using `react-navigation 6.x`. The document for version 6.x is still the same as your posted screenshot, maybe the [document](https://reactnavigation.org/docs/navigation-prop#going-back-from-a-specific-screen) is wrong.

**Comment by lukebars** [comment]
> I am using react-navigation 6.x. The document for version 6.x is still the same as the screenshot, maybe the document is wrong.

@congshengwu could you raise a PR to the docs?

**Comment by congshengwu** [comment]
Hi @lukebars, it's a good idea, I will do it.
