### ISSUE TITLE
Tabs can make screens within nested stacks impossible to navigate to

### ISSUE THREAD

**Issue by Delph** [react-navigation/react-navigation#8383]
**Current Behavior**

https://snack.expo.io/gi8wTu!px

Using the above Snack, we have HomeScreen on a Home tab, and ItemListScreen and ItemScreen in ItemStack, on the Items tab. ItemScreen has a "go back" button using `goBack()`.

Navigation to ItemScreen is possible from HomeScreen or ItemListScreen.

Two different behaviours from here can be observed:
1. Navigating from HomeScreen to ItemScreen via the button without navigating to ItemListScreen first makes ItemListScreen impossible to get to. Using `goBack` takes you to HomeScreen (which I expected), but clicking on the Items tab, from ItemScreen does nothing, from HomeScreen it takes you back to ItemScreen, not to ItemListScreen.

2. Navigating from HomeScreen to ItemListScreen (via the tab) first and then to ItemScreen works as expected and `goBack` takes you back to ItemListScreen. However, when you then navigate from HomeScreen to ItemScreen, `goBack` takes you from ItemScreen to ItemListScreen, not HomeScreen. 

Setting `lazy` to true in the `Tab.Navigator` props 'fixes' the issue and makes the second case always happen, regardless of whether you visit ItemListScreen before ItemScreen or not.

**Expected Behavior**

Navigating from HomeScreen to ItemScreen works. From ItemScreen, clicking the Items tab takes you to ItemListScreen and `goBack` takes you to HomeScreen.
Navigating from HomeScreen to ItemListScreen to ItemScreen works. From ItemScreen, clicking the Items tab takes you to ItemListScreen and `goBack` takes you to ItemListScreen.

**How to reproduce**

https://snack.expo.io/uxIoMAtCS
a. Navigating from HomeScreen to ItemScreen via the button without navigating to ItemListScreen first makes ItemListScreen impossible to get to. Using `goBack` takes you to HomeScreen (which I expected), but clicking on the Items tab, from ItemScreen does nothing, from HomeScreen it takes you back to ItemScreen, not to ItemListScreen.

b. Navigating from HomeScreen to ItemListScreen (via the tab) first and then to ItemScreen works as expected and `goBack` takes you back to ItemListScreen. However, when you then navigate from HomeScreen to ItemScreen, `goBack` takes you from ItemScreen to ItemListScreen, not HomeScreen. 

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Android 10
| @react-navigation/native               | 5.2.3
| @react-navigation/stack         | 5.3.7
| @react-navigation/tabs          | 5.3.3
| react-native                   | 37.0.1
| expo                           | 37.0.3
| node                           | 12.16.3
| npm or yarn                    | npm 6.14.4

**Comment by raajnadar** [comment]
Instead of using screen names like `OtherScreen` & `OtherChild` can you use different terms like profil settings, etc. It will be easier to understand the issue.

**Comment by Delph** [comment]
Updated, using ItemScreen (OtherChild) and  ItemListScreen (OtherScreen).

**Comment by Hirbod** [comment]
@raajnadar let's help you on this.

Suppose we have two tabs and the TabNavigator options are set to lazy as the defaults.

If you now jump from home tab to a child screen of Profile [which is also a Tab] (.navigate('Profile', { screen: 'child' }) and call goBack() from the child window brings you back to Home - fine. When you select the Profile-Tab now, you will always end up on "child" and can't ever open Profile's root screen again without restarting the app. It's like wiped out. If you set lazy to false, the tabs are already rendered and the problem does not occur when directly jumping to a subscreen of an different tab. I have tested this and can confirm it - that error also happens on my app.

**Comment by raajnadar** [comment]
In the snack I saw there is no header maybe the issue can be solved by adding a header backbutton or re structure your design.

**Comment by Hirbod** [comment]
It's still a bug @raajnadar. 2 presses on a Tab-button should always pop to the root of that Tab. And that's not working when lazy is set to true and you jump on a child-screen of a tab from another tab

**Comment by Delph** [comment]
> In the snack I saw there is no header maybe the issue can be solved by adding a header backbutton or re structure your design.

If this is a structure issue, can you point me to the correct structure to have it work as designed? I have a similarly designed app using v4 which didn't have this problem.

I don't see why the lack of a header should make a difference, and if it does then this should be counted as a bug separately, although Hirbod's comments shows it makes no difference.

**Comment by raajnadar** [comment]
Can you show your v4 example @Delph

**Comment by Delph** [comment]
Reviewing the old app, it's actually structured in a slightly different way so there's no such navigation flow. Apologies.

**Comment by satya164** [comment]
@Delph are you looking for https://reactnavigation.org/docs/nesting-navigators#rendering-initial-route-defined-in-the-navigator?

@Hirbod not sure how that relates to this issue. seems like https://github.com/react-navigation/react-navigation/issues/6915#issuecomment-591533068

**Comment by Hirbod** [comment]
Its related cause its the same issue (I have a app which receives notifications and when I open my app and Navigate to .navigate('Messages', { screen: "chat" }) on boot I am stuck on "chat" and can't escape. My workaround was to navigate to "Messages", wait for 300ms and then to "chat" to fix it.

**Comment by satya164** [comment]
Please read the linked docs.

**Comment by Delph** [comment]
Is there some way I can obtain the previous screen from the navigation store or context? Otherwise I need to prop-drill through four layers or store it in my Redux store, which I don't think is appropriate. From reading documentation and testing, `useNavigationState` gives me a history of navigating from `ItemList` and not `HomeScreen`.

**Comment by FlashLim** [comment]
> In the snack I saw there is no header maybe the issue can be solved by adding a header backbutton or re structure your design.

I removed my custom back button and use the original back button provided by the navigator instead. (My custom back button execute by using navigation.goBack() bring back to Tab1 instead)
Wow, it works. But why? 

My structure:
<BottomTab>
  <Tab1/>
  <Tab2/>
<BottomTab/>

<Tab1>
  <Screen 1/>
  <Screen 2/>   <-- I press back from here, should back to Screen 1
<Tab1 />
