### ISSUE TITLE
SafeAreaView in MaterialTopTabNavigator produces strange results on iOS and Android

### ISSUE THREAD

**Issue by tss101** [react-navigation/react-navigation#8385]
**Current Behavior**

I have a MaterialTopTabNavigator with the tabs positioned at the bottom. I've put each of the 4 screens in a SafeAreaView from react-native-safe-area-context as per the docs here: https://reactnavigation.org/docs/handling-safe-area

But I'm getting strange behaviour on Android and iOS

On Android the first two tab screens look fine, but the third tab screen, just under the SafeAreaView, is squashed

Pics, first tab screen Android fine:
![Screenshot_20200604-170646](https://user-images.githubusercontent.com/8374794/83785997-05217d80-a68a-11ea-8988-9d7eda2b3a84.png)

Third tab screen Android:
![Screenshot_20200604-170631](https://user-images.githubusercontent.com/8374794/83786019-0baff500-a68a-11ea-97ca-4cfc2511306a.png)

On iOS, portrait looks ok but Landscape seems to be broken with the SafeAreaView. The first sceen of the tabbar is shifted to the right, and the last screen might be shifted to the left (after rotating the phone)

First tab screen iOS, shifted right, notch on right
![Screenshot 2020-06-04 at 17 47 23](https://user-images.githubusercontent.com/8374794/83787294-7ca3dc80-a68b-11ea-9745-3d9a8784cd57.png)

Last tab screen iOS shifted left, notch on left
![Screenshot 2020-06-04 at 17 46 50](https://user-images.githubusercontent.com/8374794/83787301-7f063680-a68b-11ea-938c-396d1dd171d8.png)
 

**Expected Behavior**

SafeAreaView should be adding the correct padding when used in the MaterialTopTabNavigator 

**Your Environment**

| software                            | version |
| ----------------------------------- | ------- |
| iOS or Android                      |   both
| @react-navigation/native            | 5.4.3
| @react-navigation/material-top-tabs |  5.2.8
| react-native-tab-view               | 2.14.2
| react-native-safe-area-context | 2.0.2
| react-native                        | 0.62.2
| expo                                | NA
| node                                | 14.3.0
| npm or yarn                         | npm

**Comment by tss101** [comment]
Issue still exists

**Comment by satya164** [comment]
Please open issue in react-native-safe-area-context repo
