### ISSUE TITLE
navigation.goBack() results in blank screen instead of previous one

### ISSUE THREAD

**Issue by todorone** [react-navigation/react-navigation#8391]
**Current Behavior**

![blank-page](https://user-images.githubusercontent.com/423701/83950687-5b7eef80-a835-11ea-8d51-9339b8d9943b.gif)

`navigation.goBack()` results in blank screen under 2 conditions:
- previously `navigator.dispatch(StackActions.replace('SCREEN'))` has been called
- screen from which `goBack()` is being called has `{ animationEnabled: false }` property

Bug occurs only under 2 these conditions.

After `goBack()` is called, previous screen ends with { x: deviceWidth } position, that's why it's invisible.

**Expected Behavior**

After `goBack()` is called user should see previous screen

**How to reproduce**

Snack - https://snack.expo.io/@wmonkchain/great-hummus

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | iOS
| @react-navigation/native       | 5.5.1
| @react-navigation/stack        | 5.4.2
| react-native-gesture-handler   |
| react-native-safe-area-context |
| react-native-screens           |
| react-native                   |
| expo                           | 37
| node                           | 10
| npm or yarn                    | yarn

**Comment by todorone** [comment]
Dear bot, yes the versions are the latest ones.

**Comment by raajnadar** [comment]
Upgrading and clearing cache should fix the issue.

Maybe this is related https://github.com/react-navigation/react-navigation/issues/7938

**Comment by todorone** [comment]
@raajnadar Thanks for reply.

> Upgrading and clearing cache should fix the issue.

Upgrading to the latest version and full rebuild didn't help unfortunately.

> Maybe this is related #7938

I've seen this issue, but it's not the case - that one was reproduced on Android and with animation, my is reproduced on iOS and without animation only.

**Comment by trackmystories** [comment]
> Upgrading and clearing cache should fix the issue.
> 
> Maybe this is related #7938

No it doesnt.

**Comment by mzminhaz5683** [comment]
I find the same issue for android and fix it by setting `presentation` as `transparentModal` for the android platform as below
```
<RouteStack.Navigator initialRouteName={"SplashScreen"} screenOptions={{
	headerShown: false,
	presentation: Platform.OS === "ios" ? "card" : "transparentModal"
}}>
```
For,
```
  "@react-navigation/bottom-tabs": "^6.4.0",
  "@react-navigation/native": "^6.0.13",
  "@react-navigation/stack": "^6.3.4",
```
