### ISSUE TITLE
issue #8126

### ISSUE THREAD

**Issue by Razorholt** [react-navigation/react-navigation#8392]
Solution for the issue is already given.

_Originally posted by @raajnadar in https://github.com/react-navigation/react-navigation/issues/8126#issuecomment-640080802_

What's the solution?

**Comment by satya164** [comment]
https://github.com/react-navigation/react-navigation/issues/8126#issuecomment-623122783
https://github.com/react-navigation/react-navigation/issues/8126#issuecomment-623247729
