### ISSUE TITLE
ScenView does not fill the available view height. It matches childeren content's height

### ISSUE THREAD

**Issue by arash-a2k** [react-navigation/react-navigation#8393]
**Current Behavior**
SceneView from StackViewLayout doesnt contain the max height although flex is set to 1. It only matches the full contents of its childeren. (only on web)

**Expected Behavior**
I expect the view to grow and fill the screen.

![Screenshot from 2020-06-07 18-47-49](https://user-images.githubusercontent.com/10008988/83974699-8463bb00-a8ef-11ea-939d-31760db63564.png)

**How to reproduce**
https://snack.expo.io/krPILFQBE

If you check this code sample. I expect the parent which has red background to fill the screen.

**Your Environment**

| software                       | version |
web    
"react-native": "https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz",        
"react-native": "https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz",
    "react-native-paper": "3.6.0",
    "react-navigation": "^3.13.0",
    "react-native-screens": "^2.2.0"

**Comment by satya164** [comment]
```js
screenOptions={{ cardStyle: { flex: 1 } }}
```

**Comment by arash-a2k** [comment]
@satya164 thanks for your answer, but this seems to be more like a work around. Why it doesnt work as react native official documentations specify for flex: 1: https://reactnative.dev/docs/height-and-width#flex-dimensions

**Comment by arash-a2k** [comment]
Ok I found the right config:
One should pass this 
`{cardStyle: { flex: 1}}`
as the second argument to `createStackNavigator() `
You have a nice project and lib but documentation has a lot of space for improvement.
