### ISSUE TITLE
App crashes randomly

### ISSUE THREAD

**Issue by heroic** [react-navigation/react-navigation#8395]
**Current Behavior**

We are seeing random reports of a crash with this stacktrace. Trying to replicate the issue, but have not been able to.

```
com.facebook.react.bridge.JSApplicationIllegalArgumentException Animated node with tag 2028 does not exists 
    NativeAnimatedNodesManager.java:308 com.facebook.react.animated.NativeAnimatedNodesManager.disconnectAnimatedNodeFromView
    NativeAnimatedModule.java:390 com.facebook.react.animated.NativeAnimatedModule$18.execute
    NativeAnimatedModule.java:168 com.facebook.react.animated.NativeAnimatedModule$3.execute
    UIViewOperationQueue.java:499 com.facebook.react.uimanager.UIViewOperationQueue$UIBlockOperation.execute
    UIViewOperationQueue.java:792 com.facebook.react.uimanager.UIViewOperationQueue$1.run
    UIViewOperationQueue.java:903 com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches
    UIViewOperationQueue.java:43 com.facebook.react.uimanager.UIViewOperationQueue.access$2400
    UIViewOperationQueue.java:963 com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded
    GuardedFrameCallback.java:29 com.facebook.react.uimanager.GuardedFrameCallback.doFrame
    ReactChoreographer.java:175 com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame
    ChoreographerCompat.java:85 com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame
    Choreographer.java:871 android.view.Choreographer$CallbackRecord.run
    Choreographer.java:685 android.view.Choreographer.doCallbacks
    Choreographer.java:618 android.view.Choreographer.doFrame
    Choreographer.java:859 android.view.Choreographer$FrameDisplayEventReceiver.run
    Handler.java:754 android.os.Handler.handleCallback
    Handler.java:95 android.os.Handler.dispatchMessage
    Looper.java:165 android.os.Looper.loop
    ActivityThread.java:6375 android.app.ActivityThread.main
    Method.java:-2 java.lang.reflect.Method.invoke
    ZygoteInit.java:912 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run
    ZygoteInit.java:802 com.android.internal.os.ZygoteInit.main
```

**Expected Behavior**

No such crash should happen.

**How to reproduce**

Have not been able to find a concrete way to re-create the issue. The only thing in common in almost all cases is that the host activity onStop had been triggered. In some cases this is followed by onResume, but not in all.

From this it appears as if some state change might have happened after the activity had been destroyed, causing navigation to redirect.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |  android
| @react-navigation/native       |  5.5.0
| react-native                   | 0.62.2
| expo                           |
| node                           |   12
| npm or yarn                    |   yarn

**Comment by heroic** [comment]
Still happening on 5.5.1

**Comment by ohjeyong** [comment]
@heroic Same here. Did you solve this issue?

**Comment by heroic** [comment]
@ohjeyong this turned out to be an issue with our Animation in other component. It was a class component, changing it to a functional component fixed something that was causing the animation to run even after the component was unmounted.

**Comment by LiuIos** [comment]
Still happening on 5.14.5
