### ISSUE TITLE
Typescript: NavigationStackScreenComponent and NavigationStackScreenProps not available in @react-navigation/stack

### ISSUE THREAD

**Issue by timbicker** [react-navigation/react-navigation#8396]
In order to have typescript support for functional components and `navigationOptions` it is necessary to import `NavigationStackScreenComponen` and `NavigationStackScreenProps` as types. However, they seem to not be available from `@react-navigation/stack`.

For `react-navigation-stack` it seems to work fine ([see this StackOverflow post](https://stackoverflow.com/a/58472536/2925113)):

```
import {
  NavigationStackScreenComponent,
  NavigationStackScreenProps
} from 'react-navigation-stack'

interface Props extends NavigationStackScreenProps {
  // your props...
}

export const HomeScreen: NavigationStackScreenComponent<Props> = ({ navigation }) => {
  return (
    <View>
      <Text>Home</Text>
    </View>
  )
}

HomeScreen.navigationOptions = {
  // your options...
}
```

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| @react-navigation/stack        | 5.5.1

**Comment by timbicker** [comment]
> The versions mentioned in the issue for the following packages differ from the latest versions on npm:
> 
> * `@react-navigation/stack` (found: `5.2.11`, latest: `5.5.1`)
> 
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?

This problem also persists with `5.5.1`.

**Comment by satya164** [comment]
https://reactnavigation.org/docs/upgrading-from-4.x#configuring-the-navigator
https://reactnavigation.org/docs/typescript
