### ISSUE TITLE
Stack Navigator slows down after moving from react-navigation-stack to @react-navigation/stack

### ISSUE THREAD

**Issue by sergearts** [react-navigation/react-navigation#8397]
**Current Behavior**

I updated my Existing project from react-navigation-stack to @react-navigation/stack, then I changed the implementation to what's currently in the documentation, but then the navigation between screens started lagging
A. Before updating the package
![fast](https://user-images.githubusercontent.com/26005293/84033550-53d85b80-a999-11ea-8c55-38a97ce9bfb4.gif)

B. After updating the package
![slow](https://user-images.githubusercontent.com/26005293/84033610-6ce10c80-a999-11ea-9618-8e6febf1f917.gif)

**Expected Behavior**

I expect the performance to remain stable on improve as i upgrade to new versions of navigator
And the app to remain as smooth as it was as the first gif shows it

**How to reproduce**
What Produces Lag
Create a Stack Navigator nested with Bottom Tab Navigator

```
import { createStackNavigator } from '@react-navigation/stack';
import { NavigationContainer } from '@react-navigation/native';
import { createBottomTabNavigator } from '@react-navigation/bottom-tabs';

function MainApp() {
const Tab = createBottomTabNavigator();
  return (
    <Tab.Navigator>
      <Tab.Screen name="Home" component={Home} />
      <Tab.Screen name="Search" component={Search} />
      <Tab.Screen name="Saved" component={Saved} />
    </Tab.Navigator>
  );
}

function App() {
const AppNav = createStackNavigator();
  return (
    <NavigationContainer>
      <AppNav.Navigator>
        <AppNav.Screen name="MainApp" component={MainApp} />
        <AppNav.Screen name="Login" component={Login} />
        <AppNav.Screen name="Signup" component={Signup} />
      </AppNav.Navigator>
    </NavigationContainer>
  );
}
```

The code I had before updating

```
import { createAppContainer } from 'react-navigation';
import { createStackNavigator } from 'react-navigation-stack';
import { createBottomTabNavigator } from '@react-navigation/bottom-tabs';

function MainApp() {
  const Tab = createBottomTabNavigator();
  return (
    <Tab.Navigator>
      <Tab.Screen name="Home" component={Home} />
      <Tab.Screen name="Search" component={Search} />
      <Tab.Screen name="Saved" component={Saved} />
    </Tab.Navigator>
  );
}

function App() {
const MainAppStack = createStackNavigator(
  {
    SignUp: {
      screen: SignUp,
      navigationOptions: {
        headerShown: false,
      },
      path: 'SignUp',
    },
    Login: {
      screen: Login,
      navigationOptions: {
        headerShown: false,
      },
      path: 'Login',
    },
    MainApp: {
      screen: MainApp,
      navigationOptions: {
        headerShown: false,
      },
      path: 'MainApp',
    },
  },
  {
    initialRouteName: 'MainApp',
  }
);
const AppContainer = createAppContainer(MainAppStack);
  return (
    <NavigationContainer>
     <AppContainer />
    </NavigationContainer>
  );
}
```

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |Android 7|
| @react-navigation/native       |5.5.1|
| @react-navigation/stack        |5.5.1|
| react-native-gesture-handler   |1.6.1|
| react-native-safe-area-context |0.7.3|
| react-native-screens           |2.8.0|
| react-native                   |0.62.2|
| node                           |12.15.0|
| npm or yarn                    |6.13.4|

**Comment by satya164** [comment]
Closing since you haven't provided a repro. Please open a new issue with a minimal repro if you're still having problems.
