### ISSUE TITLE
createMaterialTopTabNavigator with position bottom pushes tab-bar above keyboard

### ISSUE THREAD

**Issue by Vibhu-Agarwal** [react-navigation/react-navigation#8400]
Wanted to _switch between different routes by tapping the tab or swiping horizontally_ but, with bottom-tabs

**Current Behavior**

- Used `createMaterialTopTabNavigator` with `tabBarPosition` value as `bottom` to achieve this
- Using `TextInput` in a screen, the keyboard pushes the tab-bar component above keyboard

**Expected Behavior**

- The keyboard shouldn't push the tab-bar above the keyboard, or there should be a way to hide it (like `keyboardHidesTabBar` field in `tabBarOptions` prop in `createBottomTabNavigator`).

**Your Environment**

| software                            | version |
| ----------------------------------- | ------- |
| iOS or Android                      | Android
| @react-navigation/native            |5.5.1
| @react-navigation/material-top-tabs |5.2.10
| react-native-tab-view               |2.14.2
| react-native                        |0.61.4 
| expo                                |37.0.8
| node                                |13.4.0
| npm                         |6.14.4

**Comment by Vibhu-Agarwal** [comment]
> The versions mentioned in the issue for the following packages differ from the latest versions on npm:
> 
>     * `@react-navigation/native` (found: `5.2.4`, latest: `5.5.1`)
>     * `@react-navigation/material-top-tabs` (found: `5.2.9`, latest: `5.2.10`)
> 
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?

Yes. Upgraded to the latest versions, and behaviour perists.

**Comment by mkdesilva** [comment]
I am getting this same issue on Android. For iOS it works fine.

**Comment by satya164** [comment]
You can implement it yourself using Keyboard listeners in the `TabBar` component https://reactnative.dev/docs/keyboard

**Comment by proSingularity** [comment]
Besides that I think this should be a default of the library as probably many people will run into the same issue, the keyboard does not work 100% perfect. 
On Android, there is a short flicker when the keyboard gets shown. Probably because `keyboardWillShow` is not available on Android. 

`material-bottom-tabs` seems to be able to work around this (see [here](https://github.com/react-navigation/material-bottom-tabs/blob/71a9836697606a96d8d5b7c46c155b554b1b32bd/src/views/MaterialBottomTabView.tsx#L114)) but for me it was not working with the top tabs.
Scrolling via gestures is a must-have, so using bottom tabs is not an option, unfortunately. Any ideas how to get rid of the flicker? Thank you in advance!

```typescript
const NavigationApp = () => {
    const [keyboardShown, setKeyboardShown] = useState(false);

    useEffect(() => {
        Keyboard.addListener("keyboardDidShow", handleKeyboardShown);
        Keyboard.addListener("keyboardDidHide", handleKeyboardHidden);
        return () => {
            Keyboard.removeListener("keyboardDidShow", handleKeyboardShown);
            Keyboard.removeListener("keyboardDidHide", handleKeyboardHidden);
        };
    }, []);

    const handleKeyboardShown = () => setKeyboardShown(true);
    const handleKeyboardHidden = () => setKeyboardShown(false);

    const theme = useTheme() as FullTheme;
    const { t } = useTranslation();
    return (
        <NavigationContainer theme={theme}>
            <Tab.Navigator
                initialRouteName={START_SCREEN}
                tabBarPosition="bottom"
                tabBarOptions={{
                    showIcon: true,
                    style: keyboardShown
                        ? styles.hidden
                        : {
                              ...styles.tabBar,
                              backgroundColor: theme.dark
                                  ? theme.colors.accentedCard
                                  : theme.colors.primary,
                          },
                    iconStyle: styles.icon,
                    renderIndicator: () => null,
                    labelStyle: styles.label,
                    activeTintColor: "white",
                }}
            >
...
```
