### ISSUE TITLE
Touchable of parent screen listen event child screen after navigate

### ISSUE THREAD

**Issue by kliker02** [react-navigation/react-navigation#8403]
**Current Behavior**
I have a start screen; and when I navigate to the next screen and if i click on the place where the touchablehighlight was present, named as "Some act" then i will navigate to another screen.

**Expected Behavior**
So that touchablehighlights in the parent screen are not processed in next screen

**How to reproduce**
1. Download project from [repo](https://github.com/kliker02/ErrorReactNavStack)
2. Start project
3. Navigate to support(next) screen
4. Сlick on the place where the touchable was previously located

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |  Android
| @react-navigation/native       | 5.5.1
| @react-navigation/stack        | 5.5.1
| react-native-gesture-handler   | 1.6.1
| react-native-safe-area-context | 3.0.2
| react-native-screens           | 2.8.0
| react-native                   | 0.62.2
| node                           | 6.14.4
| npm or yarn                    | npm

**Comment by kliker02** [comment]
I found that the problem disappears if I set the style backgroundColor inside the screen. But in case I want to use a react native themes еhis leads to a dead end.

**Comment by billxie1988** [comment]
+1, same problem .try this
```
const isFocused = useIsFocused();
<View style={flex:1} pointerEvents={isFocused ? 'auto' : 'none'}>
```

**Comment by satya164** [comment]
Same as #8515
