### ISSUE TITLE
Passing custom props to drawer screens in React Navigation 5?

### ISSUE THREAD

**Issue by sorxrob** [react-navigation/react-navigation#8405]
Here's my Drawer Navigation config:

```react
  return (
    <NavigationContainer theme={navigationTheme}>
      <Drawer.Navigator
        drawerContent={(props) => (
          <DrawerContent {...props} />
        )}
      >
        <Drawer.Screen name="Home" component={HomeScreen} />
        <Drawer.Screen name="About" component={AboutScreen} />
      </Drawer.Navigator>
    </NavigationContainer>
  );
```

and in my `DrawerContent` component:

```react
export default function DrawerContent({ state, navigation, ...props }) {
  return (
    <DrawerContentScrollView {...props}>
        <Drawer.Section>
          {state.routes.map((route) => (
            <DrawerItem
              key={route.key}
              label={route.name}
              onPress={() => navigation.navigate(route.name)}
            />
          ))}
        </Drawer.Section>
      </View>
    </DrawerContentScrollView>
  );
}
```

I want to add an `icon` prop to my `DrawerItem` component inside the `DrawerContent` component. I tried doing this:

```react
<Drawer.Screen name="Home" icon="home" component={HomeScreen} />
```

and in my `DrawerContent`

```react
{state.routes.map((route) => (
    <DrawerItem
        key={route.key}
        icon={({ color, size }) => (
        <MaterialCommunityIcons name="home" icon={route.icon} color={color} size={size} />
        )}
        label={route.name}
        onPress={() => navigation.navigate(route.name)}
    />
))}
```

But the `route.icon` property is `undefined`. Any idea on this?

**Comment by sorxrob** [comment]
Fixed it using [options prop on Screen](https://reactnavigation.org/docs/screen-options).

In my Drawer Navigator:

```react
<Drawer.Navigator>
  <Drawer.Screen
    name="Home"
    component={HomeScreen}
    options={{ icon: 'home' }}
  />
</Drawer.Navigator>
```

and to access it in the custom `DrawerContent` component:

```react
export default function DrawerContent({ state, navigation, ...props }) {

    const getIcon = (key) => props.descriptors[key].options.icon;

    return (
        <DrawerContentScrollView {...props}>
            <Drawer.Section>
            {state.routes.map((route) => (
                <DrawerItem
                key={route.key}
                label={route.name}
                icon={({ color, size }) => (
                    <MaterialCommunityIcons
                        name={getIcon(route.key)}
                        color={color}
                        size={size}
                    />
                )}
                onPress={() => navigation.navigate(route.name)}
                />
            ))}
            </Drawer.Section>
        </View>
        </DrawerContentScrollView>
    );
}
```

If there's a better way of doing this, please let me know.

**Comment by shehrazjazib** [comment]
I have similar issues with little changes. I have integrated Redux into my project and its working fine. 

here is my Drawer Navigation Cofig

`return (
    <NavigationContainer theme={navigationTheme}>
      <Drawer.Navigator
        drawerContent={(props) => (
          <DrawerContent {...props} />
        )}
      >
        <Drawer.Screen name="Home" component={HomeScreen} />
        <Drawer.Screen name="About" component={AboutScreen} />
      </Drawer.Navigator>
    </NavigationContainer>`

Here is my DrawerContent code.

`import { save_user } from './action
export default function DrawerContent({ state, navigation, ...props }) {
  return (
    <DrawerContentScrollView {...props}>
        <Drawer.Section>
          {state.routes.map((route) => (
            <DrawerItem
              key={route.key}
              label={route.name}
              onPress={() => props.save_user() }
            />
          ))}
        </Drawer.Section>
      </View>
    </DrawerContentScrollView>
  );
}`

But i am unable to acces the save_user() action method. I tried to make DrawerContent as a component and want to connect with redux also like this.
`export default connect(null, { save_user })(DrawerContent)`.

Now i am stuck and need your help to update redux state from custom drawer (Drawer Content).


Thanks

**Comment by Habtamu-Asefa** [comment]
You can use this function:

```

const Drawer = props => {
  const { navigation } = props;
  const routes = props.state.routes;

  const drawerIcons = Object.entries(props.descriptors).map(
    ([key, descriptor]) => {
      return {
        key,
        descriptor,
      };
    },
  );

  const getIcon = key => {
    return drawerIcons
      .find(icon => icon.key === key)
      .descriptor.options.drawerIcon();
  };
...
 {routes.map((route, index) => {
        const key = route['key'];
        const Icon = getIcon(key);
        console.log('Icon: ', Icon);
        return (
          <DrawerItem
            key={index}
            label={route.name}
            icon={() => Icon}
            onPress={() => navigation.navigate(route.name)}
          />
        );
      })}

...
```
