### ISSUE TITLE
NavigationContainer root state (getting via ref) is not available!

### ISSUE THREAD

**Issue by mrousavy** [react-navigation/react-navigation#8407]
**Current Behavior**

My `App.tsx` looks like this:

```ts
export default class App extends React.PureComponent<unknown, AppState> {
  navigationContainerRef = React.createRef<NavigationContainerRef>();
  // ...
  componentDidMount(): void {
    const rootState = this.navigationContainerRef.current?.getRootState();
    this.currentRouteName = this.getActiveRouteName(rootState);
  }
  // ...
  getActiveRouteName(state?: NavigationState | PartialState<NavigationState>): string | undefined {
    if (state == null || state.index == null) return;
    const route = state.routes[state.index];

    console.log(`___-----FOUND ROUTE: ${JSON.stringify(route)}`);
    if (route.state) {
      // Dive into nested navigators
      return this.getActiveRouteName(route.state);
    }

    return route.name;
  }
  // ...
  render(): React.ReactNode {
    Logger.debug('RE-RENDERING APP.tsx!');
    console.log(` @ ${JSON.stringify(this.navigationContainerRef.current)}`);
    return (
      <NavigationContainer ref={this.navigationContainerRef} onStateChange={this.navigationStateChanged.bind(this)}>
        <StatusBar animated={true} showHideTransition="fade" translucent={true} />
        {this.state.isSignedIn && <HomeStackNavigator />}
        {!this.state.isSignedIn && <Login />}
      </NavigationContainer>
    );
  }
}
```

But the `rootState` is `undefined` (because the `this.navigationContainerRef.current` is also undefined) in `componentDidMount`.

**Expected Behavior**

Root state becoming the `NavigationContainer`'s root state and route name becoming the Name of my initial route.

**How to reproduce**

[Snack](https://snack.expo.io/oiY178xMK)

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | iOS 13.4.1
| @react-navigation/native       | ^5.5.1
| react-native                   | 0.62.2
| expo                           | /
| node                           | v14.3.0
| npm or yarn                    | 6.14.5

**Comment by satya164** [comment]
`componentDidMount` fires too early. You need to use a function component for your root component and use `useEffect` to get the state.

**Comment by TrejoCode** [comment]
I have the same error

**Comment by mrousavy** [comment]
@satya164 makes sense, worked. thanks 👍
