### ISSUE TITLE
Browser forward button navigates to wrong pages 

### ISSUE THREAD

**Issue by davemollen** [react-navigation/react-navigation#8409]
**Current Behavior**

When you hit the browser forward button the browser history gets scrambled. You end up on unexpected pages.

**Expected Behavior**

Whenever the browser forward button is available I would expect to be able to go forward to the previously visited pages.

**How to reproduce**

Here’s a repository to reproduce the problem: [https://github.com/davemollen/browser-history-bug](url)
- Run yarn to install
- Launch expo for web
- Navigate to different pages by pushing the buttons. Then play around with the browser back and forward buttons to see what page and url you land on. 

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Web
| @react-navigation/native       | 5.5.1
| react-native                   | https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz
| expo                           | 37.0.3
| node                           | 13.10.1
| yarn                    | 1.19.1

**Comment by satya164** [comment]
> Navigate to different pages by pushing the buttons. Then play around with the browser back and forward buttons to see what page and url you land on.

Please describe what behaviour you expect and current behaviour.

**Comment by davemollen** [comment]
If you first navigate from page 1 to page 2 to page 3 through the buttons, and then follow up by hitting the browser back button to go back to page 2 and then to page 1. 
I would expect the browser forward button to be able to take you back to page 2 first and after that to page 3.

**Comment by SleeplessByte** [comment]
In short: it stops working after the first `back`. By stops working I mean either doesn't refresh the app at all (and load the correct screen), or loads the incorrect screen. This behaviour was present before, but got easier to reproduce.

I don't now if https://github.com/react-navigation/react-navigation/pull/8367 is released yet, but that might have introduced the reproducible behaviour (or fixed it, if it's not yet released).

**Comment by SleeplessByte** [comment]
Here is a snack to reproduce:

https://snack.expo.io/@derk-jan/react-navigation-5:-broken-web-linking

1. press login ✅ (expected remount on landing, works)
2. press single ✅ (expected single, works)
3. press back BROWSER BUTTON ✅ (expected landing, works)
4. can't press forward ❌ (it doesn't do anything, but it does change the url)

Here is another way to reproduce

1. press login ✅ (expected remount on landing, works)
2. press single ✅ (expected single, works)
3. press double ✅ (expected double, works)
4. press back BROWSER BUTTON ✅ (expected single, works)
5. press forward ❌ (expected double, got landing)

-------

Everything works fine if you only use the _header back button_. 

Problem used to be reproducible to inject (navigate) route on non-last-index, now it happens on every back -> forward combination.
