### ISSUE TITLE
Stack >= 5.5.0 causes TextInput to lose focus

### ISSUE THREAD

**Issue by hsjoberg** [react-navigation/react-navigation#8414]
**Current Behavior**

When tapping a `TextInput` to make the on-screen keyboard appear, the `TextInput` immediately loses focus which makes the keyboard disappear.

It only happens on the first tap and my testing suggests that `animationEnabled` has to be set to `true` in `screenOptions` of the navigator for the issue to appear.  
You also have to navigate once to make it appear, the issue doesn't show up if it is the first screen in the stack.

![textinput-focus-issue2](https://user-images.githubusercontent.com/3824379/84285523-dbf76600-ab3d-11ea-8836-9fd2e7ee9821.gif)

The issue first appears in stack@5.5.0 (stack@5.5.1 does not work either).  
It works fine in stack@5.4.2

**Expected Behavior**

Tapping on the TextInput makes it maintain focus which makes the on-screen keyboard appear.

**How to reproduce**

Here's an example code on how to make the issue appear:

```JSX
import React from 'react';
import {Button, TextInput} from 'react-native';
import {NavigationContainer} from '@react-navigation/native';
import {createStackNavigator} from '@react-navigation/stack';

const RootStack = createStackNavigator();

function Next({navigation}) {
  return (
    <Button title="Next" onPress={() => navigation.navigate('FocusTest')} />
  );
}

function FocusTest() {
  return <TextInput style={{backgroundColor: 'blue'}} />;
}

export default function Main() {
  const screenOptions = {
    animationEnabled: false,
  };

  return (
    <NavigationContainer>
      <RootStack.Navigator
        initialRouteName="Next"
        screenOptions={screenOptions}>
        <RootStack.Screen name="Next" component={Next} />
        <RootStack.Screen name="FocusTest" component={FocusTest} />
      </RootStack.Navigator>
    </NavigationContainer>
  );
}
```

I also uploaded a clean CRNA app with the issue here: https://github.com/hsjoberg/react-navigation-focus-problem

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Android
| @react-navigation/native       | 5.5.1
| @react-navigation/stack        | 5.5.0 / 5.5.1
| react-native-gesture-handler   | 1.6.1
| react-native-safe-area-context | 3.0.3
| react-native-screens           | 2.8.0
| react-native                   | 0.62.2
| expo                           | N/A
| node                           | v12.12.0
| npm or yarn                    | yarn

**Comment by pedrobneto** [comment]
Same happening to me as well, couldn't find a solution or workaround yet. Even setting keyboardHandlingEnabled to false did nothing

**Comment by hsjoberg** [comment]
@raajnadar I have provided a GIF, relevant code and a RCNA repo that demonstrates the issue.

**Comment by raajnadar** [comment]
This PR is the root cause of issue https://github.com/react-navigation/react-navigation/commit/9c06a92d092af150d653c3a2f7fdccd28090bb14

**Comment by ramoas86** [comment]
My app is having the same problem. I tested with Drawer and everything is OK, but with Stack...

**Comment by karandwivedi42** [comment]
+1

Workaround for me was to rollback to @react-navigation/stack@5.4.2

```npm i @react-navigation/stack@5.4.2```

**Comment by hsjoberg** [comment]
@karandwivedi42 Yes this is already explained n the OP

**Comment by oguzhanali** [comment]
+1

**Comment by nakulBageja** [comment]
The issue still persists in version  `"@react-navigation/stack": "^5.14.2" `. Then why is the issue closed?

**Comment by CaanDoll** [comment]
The issue still persists in version ``"@react-navigation/stack": "^5.14.3"`` . Then why is the issue closed?

**Comment by CaanDoll** [comment]
Set ``gestureEnabled`` to false or set ``animationEnabled`` to false can be solved.

**Comment by huang-ju** [comment]
@CaanDoll thank you very much

```
screenOptions={{
            gestureEnabled: true,
            animationEnabled: false,
          }}
```

**Comment by Ideopunk** [comment]
I'm having the same issue, but with material-top-tabs@^5.3.13. Tab doesn't have `gestureEnabled` or `animationEnabled` unfortunately.

**Comment by Ideopunk** [comment]
This is only an issue on iOS.

**Comment by mlecoq** [comment]
Reproduced on android with version 5.14.5 when my modal has only one `TextInput` (with several text inputs in a scroll view, everything works fine) - passing `false` in `gestureEnabled` helps to avoid the issue in this particular case.  I have noticed that if I put my text input at the top of the modal but not lower

**Comment by sarmad321** [comment]
I'm facing this issue .. my screen B has a Textinput which works perfectly fine when i call it from outside of the navigation but if enable the navigation i cant see the textinput div even i have given width and height,

**Comment by iqbalhusen** [comment]
> I'm having the same issue, but with material-top-tabs@^5.3.13. Tab doesn't have `gestureEnabled` or `animationEnabled` unfortunately.
> 
> Update: Had react-native-tab-view@3.0.0 somehow, reverted to 2.16.0, issue resolved

It was not possible for me to downgrade react-native-tab-view as I use react-native@0.64.2 which supports only 3.x.x version. The only workaround I could come up with a dirty patch which causes UI flickering.

```
let t;

const Component = () => {
  const textInputRef = useRef();

  return (
    <TextInput
      value={'test'}
      ref={textInputRef}
      onFocus={() => {
        t = +new Date(); // get unix-timestamp in milliseconds
      }}
      onBlur={() => {
        if (+new Date() - t < 500) {
          textInputRef.current.focus();
        }
      }}
    />
  );
};
```javascript

**Comment by MuhammadMattiullah** [comment]
This issue is due to the latest version of react native screens and i was facing the same issue on Android and i tried to solve this issue using screen options but nothing worked so the only thing that can fix this issue is downgrading the `react native screens` version.
Before this issues: "react-native-screens": "^3.11",
and i simply replaced IT with below version and it worked 🎉 
"react-native-screens": "3.4.0",

**Comment by ali-thowfeek** [comment]
> This issue is due to the latest version of react native screens and i was facing the same issue on Android and i tried to solve this issue using screen options but nothing worked so the only thing that can fix this issue is downgrading the `react native screens` version. Before this issues: "react-native-screens": "^3.11", and i simply replaced IT with below version and it worked 🎉 "react-native-screens": "3.4.0",

`3.10.0` did the trick for me. Thanks @MuhammadMattiullah

**Comment by DragonQi** [comment]
> This issue is due to the latest version of react native screens and i was facing the same issue on Android and i tried to solve this issue using screen options but nothing worked so the only thing that can fix this issue is downgrading the `react native screens` version. Before this issues: "react-native-screens": "^3.11", and i simply replaced IT with below version and it worked 🎉 "react-native-screens": "3.4.0",

Thanks, works for me, but im upgrade from 3.1.0 to 3.4.0

**Comment by miloscopic** [comment]
I have same issue, on react-native-screens@3.10.0 , tried 3.4.0 also, using material top tabs as bottom tab navigator. 
Interesting thing that when i totally delete react-native-screens i have same issue, maybe problem is not in that package. When switch back to material bottom tab instead of top tab , everything is fine. But i am required to use top tabs.

**Comment by AngeelVallem** [comment]
The issue still persists in version "@react-navigation/stack": "6.3.16" . Then why is the issue closed?


Any solutions?

**Comment by atakanbayil** [comment]
"@react-navigation/native-stack": "^6.9.13",    "@react-navigation/material-top-tabs": "^6.6.3", stil persists. I have 5 screens text input at the middle If I change one left or one right then I move middle screen and focus text input keyboard comes up and closes immediately as in milliseconds. I tried so many things but couldn't come up with any solutions. Interesting side of problem if I move to leftmost or rightmost screen then move to the middle screen it focuses the text input and keyboard does not close. please help !!
