### ISSUE TITLE
headerTitle is rendering screen name before it get new params from component

### ISSUE THREAD

**Issue by procarrera** [react-navigation/react-navigation#8418]
**Current Behavior**
I am passing a new headerTitle through my functional component, but there is a gap about 400ms to get it updated on the screen. the result is that a default title is rendered for a awhile before it get updated. to be more clear, this is the flow:
button on parent component (screen Feed) clicked -> child component (screen UserPage) rendered with default headerTitle (UserPage that is the screen name in my Routes.js) -> gap of 400ms -> headerTitle get updated with my params.

- What code are you running and what is happening?
**ROUTES:**
```
const Routes = createAppContainer(
  createStackNavigator(
    {
      Feed: {
        screen: Feed,
        navigationOptions: {
          headerTitle: () => <Image source={header} />,
        },
      },
      UserPage: {
        screen: UserPage,
        navigationOptions: {
          headerTitleStyle: {
            color: "red",
          },
        },
      },
    },
    {
      initialRouteName: "Feed",
      defaultNavigationOptions: () => ({
        headerTitleAlign: "center",
        headerStyle: {
          backgroundColor: "#fafafa",
          height: 80,
        },
      }),
    }
  )
);
```
**PARENT COMPONENT BUTTON:**
```
 <TouchableOpacity
              onPress={() =>
                navigate("UserPage", {
                  userDetails: item.author,
                  title: item.author.user_name,
                })
              }
  />
```
**CHILD COMPONENT (how i am dynamically updating the headerTitle):**
```
export default function UserPage({ navigation }) {
  const { user_name } = navigation.getParam("userDetails");

  UserPage.navigationOptions = ({ navigation }) => {
    return {
      title: `@${user_name}`,
      headerTitleStyle: {
        color: "#e0e0e0e0",
      },
    };
  };
```
**Expected Behavior**
some default headerTitle should not appear and my own headerTitle should replace it much faster.

**How to reproduce**
You can experiment the same behavior in this Snack Example, take a look in the headerTitle, it blinks "Details" and then my custom message.
[Snack](https://snack.expo.io/fMQKAEETu)

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Android
| @react-navigation/native       | ^4.3.9
| @react-navigation/stack        | ^2.5.1
| react-native-gesture-handler   | ~1.6.0
| react-native-safe-area-context | 0.7.3
| react-native-screens           | ~2.2.0
| react-native                   | https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz
| expo                           | ~37.0.3
| node                           | v12.13.0
| npm or yarn                    | yarn 1.21.1

**Comment by satya164** [comment]
You need to specify `navigationOptions` property outside the function, not inside.

**Comment by procarrera** [comment]
Hi @satya164 , but how if i am receiving it through my props? would you mind to code how it would be? thanks
