### ISSUE TITLE
Reanimated 2 alpha, TypeError: undefined is not a function

### ISSUE THREAD

**Issue by mym0404** [react-navigation/react-navigation#8419]
**Current Behavior**

```json
    "@react-navigation/core": "^5.10.0",
    "@react-navigation/drawer": "^5.8.2",
    "@react-navigation/native": "^5.5.1",
    "@react-navigation/stack": "^5.5.1",
```

I upgraded `reanimated` to `2.0.0-alpha.1` and am using drawer navigator. At the initialization time, the something related to `DrawerView` throw an error like that.
 
![image](https://user-images.githubusercontent.com/33388801/84334871-68516980-abce-11ea-85fa-439af29356dc.png)

**Expected Behavior**

App is working well.

**Your Environment**

```
System:
    OS: macOS 10.15.3
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 757.05 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.7.0 - /usr/local/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.14.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /Users/mj/.rvm/gems/ruby-2.7.0/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 28, 29
      Build Tools: 24.0.1, 25.0.0, 25.0.2, 26.0.2, 27.0.2, 27.0.3, 28.0.0, 28.0.2, 28.0.3, 29.0.1, 29.0.2, 29.0.3
      System Images: android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom_64
      Android NDK: 21.0.6113669
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6392135
    Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_192 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Android
| @react-navigation/native       | 5.5.1
| @react-navigation/drawer       | 5.8.2
| react-native-reanimated        | 2.0.0-alpha.1
| react-native-gesture-handler   | 1.6.1
| react-native-safe-area-context | 3.0.3
| react-native-screens           | 2.8.0
| react-native                   | 0.62.2
| expo                           | 
| node                           | 13.7.0
| npm or yarn                    | yarn 1.22.0

**Comment by raajnadar** [comment]
Don't you think you should use stable version instead of an alpha version?

Try clearing the cache!

**Comment by mym0404** [comment]
I know but I just opened an issue about upgrade `reanimated`. In `react-navigation` the used `reanimated` version is `1.2.x`. It is so outdated.

**Comment by raajnadar** [comment]
The used reanimated version is for dev mode for this repo only. It won't affect your project.

**Comment by mym0404** [comment]
Well then I will try with your advise. Thanks

**Comment by Johan-dutoit** [comment]
There are obviously breaking changes in V2 of reanimated, the one that got me was `interpolate` being renamed to `interpolateNode`.  See more [here](https://docs.swmansion.com/react-native-reanimated/docs/migration).

We can't expect react-navigation to update to an alpha, so my best piece of advise is to make the changes in each package that you use and use `npx patch-package @react-navigation/[package]`.

**Comment by raajnadar** [comment]
Closing since we need to wait for stable version of react native reanimated.

**Comment by chaudev** [comment]
> Rõ ràng là có những thay đổi đột phá trong V2 của reanimated, cái mà tôi đã `interpolate`được đổi tên thành `interpolateNode`. Xem thêm [tại đây](https://docs.swmansion.com/react-native-reanimated/docs/migration) .
> 
> Chúng tôi không thể mong đợi điều hướng phản ứng cập nhật lên alpha, vì vậy lời khuyên tốt nhất của tôi là thực hiện các thay đổi trong từng gói mà bạn sử dụng và sử dụng `npx patch-package @react-navigation/[package]`.

I think you so beautiful. tkanks

**Comment by usamadesigner** [comment]
I got this Error while using Animated. **interpolate** and I changed it to Animated.**interpolateNode**
An error was removed successfully by changing it!

**Comment by techman4tech** [comment]
> I got this Error while using Animated. **interpolate** and I changed it to Animated.**interpolateNode**
> An error was removed successfully by changing it!

Yeah, you saved my day - changed it to Animated.**interpolateNode**. It worked like charm.

**Comment by Mansi-Bigstep** [comment]
If i change this to interpolateNode in development it works fine. But will it work fine in production as well where node modules are being installed again.
