### ISSUE TITLE
cardStyle padding impact header [android]

### ISSUE THREAD

**Issue by xmanemran** [react-navigation/react-navigation#8420]
**Current Behavior**

In **android** when implementing padding `cardStyle` for every screen, that padding impact the header. In the ios its work as expected. 

```
cardStyle: {
    backgroundColor: 'red',
    paddingHorizontal: 16,
},
```

![Drag Racing](https://i.ibb.co/DQzwHw6/rsz-screenshot-1591848666.png)

**Expected Behavior**
Padding will impact screen only. I want to add padding for every screen by default. 

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| @react-navigation/native       |^5.4.0
| @react-navigation/stack        |^5.3.7
| react-native-gesture-handler   |^1.6.1
| react-native-safe-area-context |^1.0.0
| react-native-screens           |^2.7.0
| react-native                   |0.62.2

**Comment by xmanemran** [comment]
Yes, the issue still exists after upgrading to the latest versions of both.

**Comment by satya164** [comment]
You're not supposed to add padding in `cardStyle`. Add it inside your screen.

**Comment by xmanemran** [comment]
Just for my understanding, if the `cardStyle` use to set background color only, why we are using a variable called `cardStyle `. It's a bit confusing. Or we can use another kind of style, except padding. I checked in the doc, I didn't find any or I just miss it.
