### ISSUE TITLE
Weird logs, when navigating to a different screen

### ISSUE THREAD

**Issue by swizes** [react-navigation/react-navigation#8424]
I am using console.log while developing an application and whenever I change a screen, I am seeing bunch of texts, which are related to the react-navigation. I would like to know, how can I disable them, because this makes my job harder to keep track of logs, which I want to see immediately.

![image](https://user-images.githubusercontent.com/8876645/84382395-d4da6180-abea-11ea-84f5-f7c254b8df93.png)

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | iOS 13
| @react-navigation/native       | 5.5.0
| react-native                   | 0.62.2
| expo                           |
| node                           | 10.16.0
| npm or yarn                    | yarn - 1.22.4

**Comment by swizes** [comment]
It was caused by using console.warn, instead of console.log

**Comment by tranquan** [comment]
I have the same problem & found this.
In case you really want to use `console.warn`, wrap it under and timeout solve the problem

Set this on index.js
```js
console.warn2 = function (...args) {
  setTimeout(() => {
    console.warn(...args);
  }, 0);
};
```

Then you can use it in useEffect without trigger a lot of warning
```js
  useEffect(() => {
    console.warn2(`no more spam logs`);
    return () => {};
  }, []);
  ```
