### ISSUE TITLE
isDrawerOpen returns false when drawer is permanent

### ISSUE THREAD

**Issue by deggertsen** [react-navigation/react-navigation#8429]
**Current Behavior**

When calling isDrawerOpen() on a screen where the drawerType is set to permanent it returns false.

**Expected Behavior**

I would expect that whenever the drawer is showing isDrawerOpen should return true.

**How to reproduce**

Just console.log isDrawerOpen on a screen where you have the drawerType set to permanent.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | both
| @react-navigation/native       |5.5.0
| @react-navigation/drawer       |5.8.2
| react-native-reanimated        |1.7.1
| react-native-gesture-handler   |1.6.1
| react-native-safe-area-context |3.0.2
| react-native-screens           |2.8.0
| react-native                   |0.61.5
| expo                           | N/A
| node                           |13.10.1
| npm                    | 6.13.7

**Comment by satya164** [comment]
This is expected behavior. There's no concept of opened or closed drawer when drawer is permanent. The internal drawer state is "closed" and that's what `useIsDrawerOpen` returns.

**Comment by deggertsen** [comment]
Well that's a bummer. Is there any ways to detect a permanent drawer?

**Comment by satya164** [comment]
You can use React context and pass drawer type.
