### ISSUE TITLE
How to force drawer to come over header and statusbar like in gmail android app

### ISSUE THREAD

**Issue by manjeets12** [react-navigation/react-navigation#843]
Right now I am adding a drawer in one of my screen(it is wrapped in stackNavigator), right now drawer is starting below the header, I somehow wanted it to come over statusbar and header in android

**Comment by andrerfneves** [comment]
This isn't necessarily related to `react-navigation`, but here a good explanation:
https://blog.callstack.io/android-drawer-statusbar-done-right-for-react-native-7e85f01fc099

**Comment by manjeets12** [comment]
@andrerfneves , thanks for the response that link may solve the problem somehow, but it must be related to react-navigation as right now a header is added by default to the drawer in the open case,I will check what props are needed to hide that

**Comment by martnu** [comment]
@manjeets12 I think https://github.com/react-community/react-navigation/issues/856#issuecomment-290433676 will work for you.

**Comment by manjeets12** [comment]
@martnu that will simply remove header from my view

**Comment by martnu** [comment]
@manjeets12 it will make the drawer go full height up til the statusbar. Was that not what you wanted?

**Comment by manjeets12** [comment]
@martnu I described my my case in[ this SO post](https://stackoverflow.com/questions/43079339/drawer-not-covering-header-in-react-navigation)  and my issue is something similar to [this](https://github.com/react-community/react-navigation/issues/469) but it is also not resolved till now

**Comment by spencercarli** [comment]
Hi! Since this issue has been quiet for a while I'm going to go ahead and close it. If the issue persists in the latest version of React Navigation please re-open!

**Comment by Stophface** [comment]
@spencercarli Please re-open. I think this is an important feature. The drawer should have some params to set whether it shall overlay or stay behind the statusbar.

**Comment by Stophface** [comment]
One possible solution is this:
https://stackoverflow.com/questions/44574976/status-of-react-navigation-drawer-open-or-closed/45759817#45759817

However, it would be nice if the `DrawerNavigator` had that possibility as a method.

**Comment by hoscarcito** [comment]
+1

**Comment by nisargrthakkar** [comment]
Any update on this?

**Comment by brentvatne** [comment]
you need to re-organize your navigation hierarchy such that the screen with a header is a child of the drawernavigator. if this behavior doesn't work for you, please create a feature request on https://react-navigation.canny.io/feature-requests with more information or a rfc in https://github.com/react-navigation/rfcs with a complete spec

**Comment by vladikoff** [comment]
Hm I'm surprised that we have to do the `StackNavigator inside DrawerNavigation` hack. The drawer overlay is the correct guideline from https://material.io/guidelines/patterns/navigation-drawer.html#navigation-drawer-specs  (Basically the gmail app overlay behaviour)

**Comment by tonmanayo** [comment]
another solution could be to add marginTop: StatusBar.currentHeight, to the drawer component. It's not going over but at least it's not being covered

**Comment by peterchibunna** [comment]
I discovered that if your StatusBar component is not `translucent`, the drawer will not look like in Gmail app. After making the StatusBar `translucent`,  `<StatusBar translucent={true} backgroundColor={'rgba(0,0,0,0.20)'}/>`  you need to restyle the navigation header bar:
```
headerStyle = {
        paddingTop: Platform.OS === "android" ? StatusBar.currentHeight : 0,
	height: 56 + Platform.select({'android': StatusBar.currentHeight, 'ios': 0}),
}
```

**Comment by stevematdavies** [comment]
"you need to re-organize your navigation hierarchy such that the screen with a header is a child of the drawernavigator"

For me it wasn't an option since we have quite an advanced navigator nesting stack, and to add it all inside a drawer (essentially making the Drawer the root stack) breaks the app, and seems entirely counter intuitive. Im still searching for a better solution.

**Comment by ThiagoLovatine** [comment]
const defaultGetStateForAction = DrawerNav.router.getStateForAction;
  
```
DrawerNav.router.getStateForAction = (action, state) => {
 
    if(action){
        if(action.type == 'Navigation/MARK_DRAWER_SETTLING' && action.willShow){   
            StatusBar.setHidden(true);
        } else if(action.type == 'Navigation/MARK_DRAWER_SETTLING' && !action.willShow) {
            StatusBar.setHidden(false);
        }
    }
    
    return defaultGetStateForAction(action, state);
};
```
working with:

"react-navigation": "^3.5.1"
