### ISSUE TITLE
Root navigators re-renders unnecessarily while navigating from one nested screen to it's sibling screen

### ISSUE THREAD

**Issue by sjsakib** [react-navigation/react-navigation#8431]
**Current Behavior**

Let's say we have nested navigators like this:
```jsx
function Screen1({navigation}) {
  return (
    <View style={styles.screen}>
      <Text>Screen 1</Text>
      <Button
        title="go to screen 2"
        onPress={() => {
          navigation.navigate('Screen2');
        }}
      />
    </View>
  );
}

function Screen2() {
  return (
    <View style={styles.screen}>
      <Text>Screen 2</Text>
    </View>
  );
}

const Tab1Stack = createStackNavigator();

function Tab1() {
  return (
    <Tab1Stack.Navigator>
      <Tab1Stack.Screen name="Screen1" component={Screen1} />
      <Tab1Stack.Screen name="Screen2" component={Screen2} />
    </Tab1Stack.Navigator>
  );
}

function Tab2() {
  return (
    <View style={styles.screen}>
      <Text>Tab 2</Text>
    </View>
  );
}

const MainTabs = createBottomTabNavigator();

function MainApp() {
  return (
    <MainTabs.Navigator>
      <MainTabs.Screen name="Tab1" component={Tab1} />
      <MainTabs.Screen name="Tab2" component={Tab2} />
    </MainTabs.Navigator>
  );
}

const RootStack = createStackNavigator();

function Root1({navigation}) {
  return (
    <View style={styles.screen}>
      <Text>Root 1</Text>
      <Button
        title="Go to main app"
        onPress={() => {
          navigation.navigate('MainApp');
        }}
      />
    </View>
  );
}

export default function App() {
  return (
    <NavigationContainer>
      <RootStack.Navigator initialRouteName="Root1" headerMode="none">
        <RootStack.Screen name="Root1" component={Root1} />
        <RootStack.Screen name="MainApp" component={MainApp} />
      </RootStack.Navigator>
    </NavigationContainer>
  );
}
```

Now, if we navigate from `Screen` to `Screen2` the whole tree of navigators re-renders, even the `BottomTabBar`. This slows down page transition when the screens themselves has heavy rendering to do too. Here's a partial screenshot of the profile I recorded:

![Screenshot from 2020-06-12 10-54-29](https://user-images.githubusercontent.com/15678931/84466438-3ce88080-ac9b-11ea-9639-c3b33d6c4112.png)

**Expected Behavior**

Only the `Tab1` and it's children re-renders.

**How to reproduce**

Here's a snack: https://snack.expo.io/@sjsakib/unnecessary-root-navigator-re-render-
A profiling tool can be used to see how the components re-renders.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Android 8.1
| @react-navigation/native       |5.5.1
| react-native                   |0.62.2
| expo                           |
| node                           |
| npm or yarn                    |

**Comment by satya164** [comment]
This is expected behaviour. If your screens have heavy rendering, then you need to extract relevant parts to separate components and apply `React.memo` or other optimizations to those parts.
