### ISSUE TITLE
Screen doesn't focus on Bottom Tab Icon Press.

### ISSUE THREAD

**Issue by Gabrielhvcardoso** [react-navigation/react-navigation#8433]
**Current Behavior**

I have a TabNavigator with five Components, each one of those components is a DrawerNavigator inside a StackNavigator.

When I run it on an android device, it works fine, but when on an iOS device, the `FirstStack` screen is opened but it doesn't change the focused screen when I press another TabBar icon.

This is my actual code:
```
export default function Routes() {
  return(
    <NavigationContainer>
      <Tab.Navigator screenOptions={tabScreenOptions} tabBarOptions={tabBarOptions} >
        <Tab.Screen name="First" component={FirstStack} options={{ unmountOnBlur: true }}/>
        <Tab.Screen name="Second" component={SecondStack} options={{ unmountOnBlur: true }} />
        <Tab.Screen name="Third" component={ThirdStack} options={{ title: '' }} />
        <Tab.Screen name="Fourth" component={FourthStack} options={{ unmountOnBlur: true }} />
        <Tab.Screen name="Fifth" component={FifthStack} options={{ unmountOnBlur: true }} />
      </Tab.Navigator>
    </NavigationContainer>
  )
}
```

![Screenshot_20200612-120859](https://user-images.githubusercontent.com/59807575/84517537-d61c9480-aca5-11ea-8aee-65ed238fa5e6.png)

**Expected Behavior**

It works like how it works on android.

**Your Environment**

| software                      | version |
| ----------------------------- | ------- |
| iOS or Android                | iPhone 6 - iOS 12.4.5
| @react-navigation/native      | ^5.0.9
| @react-navigation/bottom-tabs | ^5.1.1
| react-native-screens          | ~2.2.0
| react-native                  | sdk-36-0-1
| expo                          | ^37.0.0
| node                          | v12.14.1
| npm or yarn                   | npm 6.13.4

**Comment by satya164** [comment]
Closing since you haven't provided a repro. Please open a new issue with a minimal repro if you're still having problems.
