### ISSUE TITLE
Navigation Drawer with {drawerLockMode :'lock-closed'} not closing When pressed outside 

### ISSUE THREAD

**Issue by Shabnam-Veranloo** [react-navigation/react-navigation#8437]
I set  {drawerLockMode :'lock-closed'} becuse i don want swipe work but When pressed outside drawer does'nt close

| software                       | version |
| ------------------------------ | ------- |
|react-navigation |4.3.9
|react-navigation-drawer|  2.4.13
| react-native-gesture-handler   |1.6.1
| react-native                   |0.62.2

**Comment by satya164** [comment]
https://reactnavigation.org/docs/drawer-navigator#swipeenabled

**Comment by Shabnam-Veranloo** [comment]
my version of react navigation is 4 not 5!!!!
anyway i fix it by  EdgeWidth:0 but this is bad bug in version 4
