### ISSUE TITLE
Bottom Tab "tabBarVisible: false" does not work in 5.5.2, I revert back to 5.2.4 and it works again

### ISSUE THREAD

**Issue by matthewkos** [react-navigation/react-navigation#8439]
**Current Behavior**

just setting "tabBarVisible: false"  Does not work in 5.5.2 , revert to 5.2.4 will fix the problem.

**Expected Behavior**

Expecting to hide the tabbar when setting "tabBarVisible: false"

**How to reproduce**

`<TabNav.Navigator
        tabBar={props => (
          <TabBar
            {...props}
            noShow={this.props.store.user ? 2 : null}
            tabBarOptions={{
              activeTintColor: EStyleSheet.value('$primaryInvertColor'),
              inactiveTintColor: EStyleSheet.value('$primaryColor'),
              activeBackgroundColor: EStyleSheet.value('$primaryColor'),
              inactiveBackgroundColor: EStyleSheet.value('$primaryInvertColor'),
            }}
            globalEmitter={this.props.globalEmitter}
          />
        )}
      >
            <TabNav.Screen
              name="Home"
              component={HomeStack}
              options={{
                tabBarIcon: HomeIcon,
              }}
            />
            <TabNav.Screen
              name="Map"
              component={MapStack}
              options={{
                tabBarIcon: MapIcon,
               tabBarVisible: false,
              }}
            />
      </TabNav.Navigator>`

**Your Environment**

| software                      | version |
| ----------------------------- | ------- |
| iOS or Android                | Android
| @react-navigation/native      | 5.1.3
| @react-navigation/bottom-tabs | 5.5.2
| react-native-screens          | no
| react-native                  | 5.1.3
| expo                          | no
| node                          | 12.8.0
| npm or yarn                   | yarn 1.22.4

**Comment by ozerty** [comment]
Same here.

**Comment by satya164** [comment]
https://github.com/react-navigation/react-navigation/issues/8363#issuecomment-639697617
