### ISSUE TITLE
Do not automatically hide the header for nested stacks

### ISSUE THREAD

**Issue by yvbeek** [react-navigation/react-navigation#8442]
### Current Behavior

**What code are you running and what is happening?**

`@react-navigation/stack` 5.5.0 or later breaks our app.
Probably because of the changes in this commit: https://github.com/react-navigation/react-navigation/commit/e0e0f79793be552e5532cd0afe9444000d21341e

In our app we have the following navigation structure:
1. root stack navigator for our "popups" (card layout)
2. then a tab navigator for the main menu items
3. every tab has a traditional stack navigator

### Expected Behavior

**What do you expect should be happening?**

The assumption to automatically hide the header in nested stacks is wrong in my opinion. When you use a stack navigator for card-layout it has nothing to do with a normal stack navigator and should therefor not affect the headers.

Maybe the card-layout should be refactored out into a separate navigator type?

For now it would be great if this change could be reverted.

### Your Environment

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | most recent
| @react-navigation/native       | 5.5.1
| @react-navigation/stack        | 5.5.1
| react-native-gesture-handler   | 1.6.1
| react-native-safe-area-context | 3.0.3
| react-native-screens           | 2.8.0
| react-native                   | 0.62.2
| expo                           | -
| node                           | 14.4.0
| npm or yarn                    | yarn 1.22.4

**Comment by satya164** [comment]
It only hides header in nested stack automatically only if you already have a header. I think it's highly unlikely that people want to have 2 headers, whatever the layout is. And if you really need 2 headers for some reason, you can explicitly enable it:

```js
screenOptions={{ headerShown: true }}
```

**Comment by yvbeek** [comment]
**Side-note**: none of the links on the releases page work. The links seem to be relative to the package instead of the root.

See https://github.com/react-navigation/react-navigation/releases

**Comment by yvbeek** [comment]
@satya164 For card-layout that does make sense, because the cards aren't always visible and they are an overlay on the actual content.

Right now, it is hiding the headers of my normal stack navigator, because I have a root stack navigator that is used to show popups (cards).

**Comment by satya164** [comment]
I'm not sure why card/modal makes a difference here. Even with modal, why would you want to show 2 headers at a time? It only hides the header automatically if the parent screen already has a header. And you can enable header explicitly if you really want 2 headers (though I don't understand why) with `headerShown: true` on the nested navigator.

**Comment by yvbeek** [comment]
> I'm not sure why card/modal makes a difference here.

The card has a header, because we want to show a title. The card itself isn’t visible though until you navigate to it.

The normal stack navigator now detects the stack navigator for the cards, sees that it has a header and now hides the header.

A card-based stack navigator should not affect a normal stack navigator in any way. Cards cover the entire screen.

**Comment by satya164** [comment]
Can you share a screenshot what do you mean by "card" vs normal stack navigator and what's your layout?

**Comment by yvbeek** [comment]
@satya164 I've created a Snack here that demonstrates the issue:
https://snack.expo.io/@yvbeek/react-navigation-stack-header-issue

With @react-navigation/stack 5.4.1, the headers work properly.
With @react-navigation/stack 5.5.1, the headers are gone.

It illustrates that the `RootStack` navigator (mode: modal, used to display cards) should not influence the `PageStack` navigator inside of the tabs. The headers of the `PageStack` navigator should not automatically be set to hidden.

**Comment by yvbeek** [comment]
@satya164 Did you see the Snack?

I can use `headerShown` as a workaround, but I don't think this is the correct default behavior.
StackNavigators with `mode: modal` should not affect normal StackNavigators.

**Comment by satya164** [comment]
> It illustrates that the RootStack navigator (mode: modal, used to display cards) should not influence the PageStack navigator inside of the tabs

I am not sure how it illustrate that.

From what I see, you have set `headerTransparent` to `true`, so headers are positioned over each other now instead of below one another. So if you show both headers, it'll look like this:

<img width="206" alt="Screen Shot 2020-06-19 at 19 21 22" src="https://user-images.githubusercontent.com/1174278/85162706-18277680-b262-11ea-800f-36385f111e2f.png">

Without `headerTransparent`, it'd look like this:

<img width="149" alt="Screen Shot 2020-06-19 at 19 22 00" src="https://user-images.githubusercontent.com/1174278/85162786-33928180-b262-11ea-9514-6d3656931c42.png">

I'm pretty sure none of these are desirable in any case.

In fact, looks like you don't want that behavior either, but you're trying to make header look like hidden by using `headerTitle: ""` instead of `headerShown: false` which would've resulted in expected behavior.

Also I don't get how `mode: 'modal'` and `mode: 'card'` relate to this. Any stacks can be nested, not just modal and card.

**Comment by yvbeek** [comment]
@satya164 I would much rather see the header titles overlapping each other vs automatically hiding the headers of the inner stack navigators (https://github.com/react-navigation/react-navigation/commit/e0e0f79793be552e5532cd0afe9444000d21341e). It is an incorrect assumption that the inner stack navigator's headers should be hidden instead of the parent's header. I would leave this up to the developer. I think in many cases the developer would want to hide the parent's header instead.

When I was implementing the navigation I found it confusing that `mode: 'modal'` is something that you set on the StackNavigator. I'm not sure how big of a change this would be, but what do you think of moving the `mode` argument to the navigation actions? So that you can say that you want to `push` a screen onto the stack with `mode: 'modal'`. That would prevent some of these issues. In the example app it would remove the need for the second stack navigator. Alternatively you could configure a screen to be modal.

**Comment by pke** [comment]
@satya164 Multiple headers can make sense in some app scenarios like mine:
My root navigator displays the users current location.
All subsequent stack navigators show their normal header. That way I don't have to customise each stack header with the location info, which would require me to completely re-implement the default stack `<Header/>` component.

I have a feature-request open to make customisation of the default stack header component easier:
https://react-navigation.canny.io/feature-requests/p/stack-header-default-impl-recognizes-children-and-render-them-abovebelow-itself

However with my approach there is a bug: The nested stack navigators header also renders itself with Safe-Area insets, which it shouldn't when its nested and another header is already rendered before it.

**Comment by vshjxyz** [comment]
I had issues with this too while upgrading, it seems like if I have the parent with `header: ()=> null` set then the inner navigator won't have safe areas (on previous versions it wasn't like that). The current solution for me is to use `headerShown: false` on the parent and keep the header in the children. This preserves safe areas for the inner one.
