### ISSUE TITLE
 how to set someone tabBarLabel of Tab.Screen to hide?

### ISSUE THREAD

**Issue by huaiguoguo** [react-navigation/react-navigation#8444]
this is a question of use for me;
its not a bug,  i need help .

**i expected effect is as follows**
![image](https://user-images.githubusercontent.com/1888094/84758047-86b4cc00-aff7-11ea-8d43-dcf39ab7660b.png)

**Current Behavior**
```

type BottomTabsParamList = {
  Home: {
    screen: any;
  };
  Explore: {
    screen?: any;
  };
  Plus: {
    screen?: any;
    navigationOptions: {
      tabBarLabel: 'asdf';
    };
  };
  Message: {
    screen?: any;
  };
  Mine: {
    screen?: any;
  };
};

const Tab = createBottomTabNavigator<BottomTabsParamList>();

function BottomTabs(props: IProps) {
  const {navigation, route} = props;

  useEffect(() => {
    navigation.setOptions({
      headerTitle: getHeaderTitle(route),
    });
  }, [props]);

  return (
    <Tab.Navigator
      tabBarOptions={{activeTintColor: 'orange'}}
      screenOptions={{}}>
      <Tab.Screen
        name="Home"
        component={Home}
        options={{
          tabBarLabel: '首页',
          tabBarIcon: ({color, size}) => (
            <IconFont name="icon-home" size={size} color={color} />
          ),
        }}
      />
      <Tab.Screen
        name="Plus"
        component={Plus}
        options={({route, navigation}) => {
          return {
            tabBarLabel: 'I want hide this tabBarLabel, just only this tabBarLabel',
            tabBarIcon: ({color, size}) => (
              <IconFont name="icon-Plus" size={size} color={color} />
            ),
          };
        }}
      />
      <Tab.Screen
        name="Mine"
        component={Mine}
        options={{
          tabBarLabel: '我的',
          tabBarIcon: ({color, size}) => (
            <IconFont name="icon-mine" size={size} color={color} />
          ),
        }}
      />
    </Tab.Navigator>
  );
}
```

**Expected Behavior**
i see have a option `showLabel`  in tabBarOptions of Tab.Navigator,
but if set showLabel is false,  all tabBarLabel is hide,

i try set `tabBarLabel` in `options` of  `Tab.Screen` is empty string, 
but its still have a placeholder !!

I want hide someone tabBarLabel, just only hide someone tabBarLabel
but  i dont know  how to set....

**How to reproduce**

**Your Environment**

| software                      | version |
| ----------------------------- | ------- |
| iOS or Android                | Android 28
| @react-navigation/native      | ^5.5.1
| @react-navigation/bottom-tabs | ^5.5.2
| react-native-screens          | ^2.8.0
| react-native                  |  0.62.2
| expo                          |
| node                          |   v12.13.1
| npm or yarn                   | yarn 1.22.4

**Comment by ReactNativ** [comment]
`options={{
tabBarShowLabel: false,
}}`

**Comment by messabih-khalil** [comment]
<Tab.Screen
                options={{
                    tabBarLabelStyle: { display: 'none' }, // add this line to ur options
                }}
            />
