### ISSUE TITLE
NavigationContainer linking + ref props together leads to ref always null

### ISSUE THREAD

**Issue by Speedy1991** [react-navigation/react-navigation#8445]
```
const AppNavigator: React.FC<NavigationContainerProps> = (props) => {
  const routeNameRef = React.useRef<string>(null!)
  const navigationRef = React.useRef<NavigationContainerRef>(null!)

  React.useEffect(() => {
   // navigationRef.current is always null if linking exists
    const state = navigationRef.current.getRootState() 
    routeNameRef.current = getActiveRouteName(state)
  }, [])

return(
  <NavigationContainer
      {...props}
      ref={navigationRef}
      // Remove linking and everything works as expected
      linking={{
        prefixes:...
      }}
      ....
    </NavigationContainer>
  >
```

As soon I add `linking` prop to the NavigationContainer the `navigationRef` stays forever null

**Expected Behavior**
ref should work as expected

**Setup**
```
"react": "16.13.1",
"react-native": "0.62.2",
"@react-navigation/material-top-tabs": "5.2.10",
"@react-navigation/native": "5.5.1",
"@react-navigation/stack": "5.5.1",
```

**Comment by satya164** [comment]
You can use `onReady` callback with latest version https://reactnavigation.org/docs/screen-tracking/#example

**Comment by juliopiubello** [comment]
@satya164 I don't know if you answer solves the issue

If I use linking, the useRef works only sometimes, if I comment the linking the navigation ref is always null and even after the container is ready, still null

**Comment by manoj398** [comment]
I had similar issue.
useLinking for me https://reactnavigation.org/docs/use-linking/

**Comment by jennmueng** [comment]
@satya164 This issue is still present, the ref is `null` with linking set. `onReady` is not related to this issue at all. We use the navigation container ref over at Sentry to integrate with React Navigation for our performance product, and this is breaks it, so please reopen this issue.

**Comment by satya164** [comment]
> `onReady` is not related to this issue at all

Well, it is. The ref isn't ready until deep link is resolved and `onReady` fires when ref becomes usable. If the ref is `null`, it means there is no navigation data for you to track yet.

**Comment by jennmueng** [comment]
@satya164 I see, thank you, and I think it should be explained clearer as it seems others in this thread did not understand either.
