### ISSUE TITLE
Header adjusts/resize when coupled with status bar on initial load and on changing tabs.

### ISSUE THREAD

**Issue by dev7050** [react-navigation/react-navigation#8446]
I am getting strange issue on adding status bar with react navigation. It works fine when I remove status bar from root. I have attached code below and I think it is enough to reproduce the issue. 
![issue](https://user-images.githubusercontent.com/58287483/84763845-75b18e00-afea-11ea-92db-fb0470c419a6.gif)

App.js
```
import React, { Component } from 'react';
import { Text, View } from 'react-native';
import AppStatusBar from './app/components/common/statusBar';
import { createBottomTabNavigator } from 'react-navigation-tabs';
import { createAppContainer } from 'react-navigation';
import { createStackNavigator } from 'react-navigation-stack';

const ScreenOne = () => {
  return (
    <View style={{ flex: 1, justifyContent: 'center' }}>
      <Text>Home</Text>
    </View>
  );
};

const Home = createStackNavigator({
  Initial: { screen: ScreenOne },
});

function ProfileScreen() {
  return (
    <View style={{ flex: 1, justifyContent: 'center' }}>
      <Text>Profile</Text>
    </View>
  );
}

export const App = createAppContainer(
  createBottomTabNavigator({
    Home: { screen: Home },
    Profile: { screen: ProfileScreen },
  }),
);

export default class Root extends React.Component {
  render() {
    return (
      <>
        <AppStatusBar color={'red'} />
        <App />
      </>
    );
  }
}

```
``

AppSatusbar

```
import React from 'react';
import { View, StatusBar } from 'react-native';
import { getStatusBarHeight } from 'react-native-status-bar-height';
const STATUSBAR_HEIGHT = getStatusBarHeight();
const AppStatusBar = ({ color, ...props }) => (
  <View style={[{ backgroundColor: color, height: STATUSBAR_HEIGHT }]}>
    <StatusBar translucent backgroundColor={color} {...props} />
  </View>
);
export default AppStatusBar;

```
 "react-native": "0.62.2",
 "react-navigation": "^4.3.9",
 "react-navigation-tabs": "^2.8.13",

Platform : iOS & Android (Simulator/Device)

**Comment by dev7050** [comment]
Hello @satya164 ,  I am unable to make a snack for the above code but I have updated the code to reproduce. Please check and let me know if this is not sufficient.

**Comment by dev7050** [comment]
Hello @satya164, I am attaching a repo link for reproducing the issue. Please have a look.

https://github.com/dev7050/HeaderIssue.git

**Comment by satya164** [comment]
Can you try updating to latest version of recat-native-safe-area-context?

**Comment by dev7050** [comment]
> Can you try updating to latest version of recat-native-safe-area-context?

Tried but not resolved.

**Comment by dev7050** [comment]
> Can you try updating to latest version of recat-native-safe-area-context?

Tried but issue persists.

**Comment by maystrenkoYurii** [comment]
Also behavior on android

**Comment by dev7050** [comment]
Issue is because of the view height that which we are trying to couple with the navigator. For android this can be fixed by keeping height 0 for app status bar. 

```
const STATUSBAR_HEIGHT = Platform.OS == 'ios' ? getStatusBarHeight() : 0;
const AppStatusBar = ({ color, ...props }) => (
  <View style={[{ backgroundColor: color, height: STATUSBAR_HEIGHT }]}>
    <StatusBar translucent backgroundColor={color} {...props} />
  </View>
);
export default AppStatusBar;
```
But this is not the proper solution and for iOS Issue persists.

**Comment by dev7050** [comment]
> Also behavior on android but i use latest v5 navigation and latest react-native-safe-area-context
> 
> ![Screenrecorder-2020-06-17-00-27-46-860](https://user-images.githubusercontent.com/23016311/84830379-fc3d8e00-b031-11ea-9a41-6f4d969d3e65.gif)
> ![Снимок экрана от 2020-06-17 00-44-21](https://user-images.githubusercontent.com/23016311/84831283-beda0000-b033-11ea-80c2-944af7110b18.png)

Issue is because of the view height that which we are trying to couple with the navigator. For android this can be fixed by keeping height 0 for app status bar.

```
const STATUSBAR_HEIGHT = Platform.OS == 'ios' ? getStatusBarHeight() : 0;
const AppStatusBar = ({ color, ...props }) => (
  <View style={[{ backgroundColor: color, height: STATUSBAR_HEIGHT }]}>
    <StatusBar translucent backgroundColor={color} {...props} />
  </View>
);
export default AppStatusBar;
```
But this is not the proper solution and for iOS Issue persists.

**Comment by satya164** [comment]
It seems expected because using statusbar component changes the statusbar config asynchronously. So it has different config on initial render which updates later and react navigation adjusts to it. You can specify `headerStatusBarHeight: 0` to disable automatic statusbar handling.
