### ISSUE TITLE
com.app.MainActivity cannot be cast to com.reactnativenavigation.NavigationActivity

### ISSUE THREAD

**Issue by khan-zia** [react-navigation/react-navigation#8447]
Recently I merged some changes from a colleague and these changes have React Native Navigation setup in it. After installing all the dependencies and setting up everything, When I run the app, I get this error that says **com.app.MainActivity cannot be cast to com.reactnativenavigation.NavigationActivity** Apparently, the error is coming from the following file
**react-native-navigation\lib\android\app\src\main\java\com\reactnativenavigation\react\NavigationModule.java**

**How to reproduce**

I am not really sure how to reproduce this error because I don't know what's causing it in the first place. However, the only other unexpected behavior was that my Android Studio or **react-native run-android** both were failing gradle build when I first added all the required dependencies. The reason for failure was **kotlin-android** and even though I can confirm that from the build.gradle files of the repository that the required settings exist, still I had to add the relevant required config to my main applications android/gradle.build and android/app/gradle.build
Apparently this solved the issue with now **react-native run-android** running successful gradle build.

The repository has the following dependencies config

```
classpath 'com.android.tools.build:gradle:3.5.3'
classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.61"
```

Despite the presence of above, my gradle builds were failing and complaining about android-kotlin so I added the following dependencies config to my app's android/gradle.build

```
classpath('com.android.tools.build:gradle:3.6.2')
classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.72"
```

Notice the difference in versions of the gradle (This gradle version came by default with RN 0.62) and kotlin-gradle-plugin. I don't know, but could this be the cause of the issue?

![Capture](https://user-images.githubusercontent.com/41148588/84768759-338a4b80-afee-11ea-8728-fb7c6159359f.PNG)
![ssss](https://user-images.githubusercontent.com/41148588/84768782-3be28680-afee-11ea-9a4c-57cd9302512d.PNG)

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| Android                 | API version 28
| @react-navigation/native       |  5.5.0
| react-native                   | 0.62
| expo                           | not using expo.
| node                           | latest
| yarn                    | 1.22.4

**Comment by khan-zia** [comment]
#Update
I updated @react-navigation/native to v 5.5.1 and the issue still persists

**Comment by SKrotkih** [comment]
I have the same issue (the same red message) on Android. MainActivity:
package com.sample;
import com.facebook.react.ReactActivity;

public class MainActivity extends ReactActivity {
    @Override
    protected String getMainComponentName() {
        return "sample";
    }
}
If i press on Esc the message 'com.app.MainActivity cannot be..' disappears and app works but i can't debug it. Could not connect to development server. iOS works.

**Comment by khan-zia** [comment]
Hey @SKrotkih , I figured this out later, in my case, my colleague had also added this other react navigation package from wix (https://github.com/wix/react-native-navigation) and this one apparently needs quite some setup before it could work. So the cause of error is actually this unconfigured package from Wix, not this react-navigation package. Simply remove the wix one if you have, clean all of your build caches by deleting **android/app/build  and android/build if there** folders and running the following command
```
cd android && .\gradlew cleanBuildCache
```

After you have done all those, it's better to do build gradle from android studio when you run into issues. So open the **android** folder of your app in android studio, from top menu, go to **build --> Rebuild Project**

But, if you need to use the package from wix, then here's a comprehensive guide on how to setup that wix package for react native navigation. https://www.sitepoint.com/react-native-navigation-library/

**Comment by abhishekjmd** [comment]
Did anyone got the solution ??

**Comment by ialwayswatching** [comment]
got this issue any info how to fix it?

**Comment by OFD16** [comment]
In my locale, the cause of this problem is due to the `react-native-navigation` package. I already 
`"@react-navigation/bottom-tabs": "^6.5.20",
     "@react-navigation/native": "^6.1.17",
     "@react-navigation/native-stack": "^6.9.26",`
I was using these packages and when I added the `react-native-navigation` package, I got the error `com.app.MainActivity cannot be cast to com.reactnativenavigation.NavigationActivity.` It was fixed when I removed the `react-native-navigation` package.
`yarn remove react-native-navigation`
