### ISSUE TITLE
Header that occupies empty space

### ISSUE THREAD

**Issue by mindaugasnakrosis** [react-navigation/react-navigation#8448]
**Current Behavior**

I am using `React navigation `4 with `Drawer navigator`. and `Stack navigator` and have the following screen:

![image](https://user-images.githubusercontent.com/14983636/84766077-e2bc2800-afd8-11ea-9e14-22f3450bf30d.png)

**Expected Behavior**

No empty space in the top.
**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | iOS and Androiid
| react-navigation               |  4.0.10
| react-navigation-stack         | 1.10.3
| react-navigation-tabs          | 2.5.6
| react-navigation-drawer        | 2.3.3
| react-native-reanimated        |
| react-native-gesture-handler   |
| react-native-safe-area-context | 0.7.3
| react-native-screens           |
| react-native                   | 0.61
| expo                           |  https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz
| node                           | 13.1
| npm or yarn                    | yarn

Code:

**Drawer navigator:**  
```
const PickingStack = createStackNavigator({
  PickingTasks,
  GoToLocationScreen,
});

const routeConfigs = {
  Surinkimas: { screen: PickingStack },
};

const drawerConfig = {
  initialRouteName: 'Surinkimas',
  contentComponent: Sidebar,
};

export default createDrawerNavigator(routeConfigs, drawerConfig);

```

**AppContainer**

```
import DrawerNavigator from './DrawerNavigator';

const AppContainer = createAppContainer(
  createSwitchNavigator(
    {
      App: DrawerNavigator,
    },
    {
      initialRouteName: 'AuthLoading',
    }
  )
);

```

**App**
```
import { Provider as StoreProvider } from 'react-redux';
import AppContainer from './AppContainer';

const App = () => (
      <StoreProvider store={store}>
        <AppContainer
          ref={navigatorRef => {
            NavigationService.setTopLevelNavigator(navigatorRef);
          }}
        />
      </StoreProvider>
    );

```

**Comment by mindaugasnakrosis** [comment]
If I use react-navigation v4 i don't think `react-navigation-stack` 2.7.0 is compatible.

**Comment by satya164** [comment]
https://reactnavigation.org/docs/4.x/upgrading-from-3.x#react-navigation-stack
