### ISSUE TITLE
createBottomTabNavigator() fails silently when wrapped in <View>, works in <Fragment>

### ISSUE THREAD

**Issue by sometimescasey** [react-navigation/react-navigation#8449]
**Current Behavior**

This renders the status bar, but screen is empty and tabs do no appear. No errors show in console.

**App.js**:
```jsx
import React, { Fragment } from 'react';
import { StyleSheet, Text, View } from 'react-native';
import FlashcardStatusBar from './components/FlashcardStatusBar';
import { blue } from './utils/colors';
import Navigator from './navigator/Navigator';

export default function App() {
  return (
      <View>
        <FlashcardStatusBar 
                  backgroundColor={blue} 
                  barStyle='light-content'/>
        <Navigator/>
      </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
```

**./navigator/Navigator.js**:
```jsx
import { createAppContainer } from 'react-navigation';
import { createBottomTabNavigator } from 'react-navigation-tabs';
import DeckScreen from '../screens/DeckScreen';
import NewDeckScreen from '../screens/NewDeckScreen';

const Navigator = createBottomTabNavigator(
    routes = {
        "Main": DeckScreen,
        "New Deck": NewDeckScreen,
    },
    config = {}
);


export default createAppContainer(Navigator);
```

package.json:
```json
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "expo": "~37.0.3",
    "react": "~16.9.0",
    "react-dom": "~16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz",
    "react-native-gesture-handler": "~1.6.0",
    "react-native-reanimated": "~1.7.0",
    "react-native-screens": "~2.2.0",
    "react-native-web": "~0.11.7",
    "react-navigation": "^4.3.9",
    "react-navigation-tabs": "^2.8.13",
    "react-redux": "^7.2.0",
    "redux": "^4.0.5"
  },
  "devDependencies": {
    "@babel/core": "^7.8.6",
    "babel-preset-expo": "~8.1.0"
  },
  "private": true
}
```

**Expected Behavior**

- renders the status bar, bottom tabs appear, screens render. Note this works correctly if the `<View></View>` tags above are switched to `<Fragment></Fragment>` tags.

**How to reproduce**

Can clone and `expo start` from this commit: https://github.com/sometimescasey/reactnd-p3-mobile-flashcards/commit/5afa0b1925c83ff101f1dc12faccd115acfa5e4a

**Your Environment**

See package.json for remainder

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | iOS simulator |
| react-navigation               |
| react-navigation-stack         |
| react-navigation-tabs          |
| react-navigation-drawer        |
| react-native-reanimated        |
| react-native-gesture-handler   |
| react-native-safe-area-context |
| react-native-screens           |
| react-native                   |
| expo                           |
| node                           |
| npm or yarn                    | 1.22.4 |

**Comment by satya164** [comment]
https://reactnavigation.org/docs/troubleshooting#nothing-is-visible-on-the-screen-after-adding-a-view

**Comment by sometimescasey** [comment]
Ah, thank you.

Link above suggests setting `<View style={{ flex: 1 }}>`
