### ISSUE TITLE
In RouteProp Property 'state' does not exist on type typescript

### ISSUE THREAD

**Issue by maystrenkoYurii** [react-navigation/react-navigation#8450]
<img width="780" alt="Снимок экрана 2020-06-16 в 18 43 18" src="https://user-images.githubusercontent.com/23016311/84796659-8d484100-b001-11ea-92f7-bdf00f77830a.png">
<img width="859" alt="Снимок экрана 2020-06-16 в 18 45 51" src="https://user-images.githubusercontent.com/23016311/84796718-9f29e400-b001-11ea-8dc9-fb0fee13351f.png">

**Comment by Hayk-Zohrabyan** [comment]
@maystrenkoYurii I think you need to use their type.

import { useRoute, RouteProp } from '@react-navigation/native';
