### ISSUE TITLE
in Route type is missing 'state' object v5.5.1

### ISSUE THREAD

**Issue by maystrenkoYurii** [react-navigation/react-navigation#8453]
![Снимок экрана от 2020-06-16 23-00-53](https://user-images.githubusercontent.com/23016311/84822661-b8448c00-b025-11ea-8787-c754f92f444d.png)
![Снимок экрана от 2020-06-16 23-03-08](https://user-images.githubusercontent.com/23016311/84822664-b975b900-b025-11ea-9698-806fdb3e4a2b.png)
![Снимок экрана от 2020-06-16 23-01-28](https://user-images.githubusercontent.com/23016311/84822663-b975b900-b025-11ea-8f8c-50ec6253b06e.png)

**Comment by satya164** [comment]
Use `getFocusedRouteNameFromRoute` with latest version https://reactnavigation.org/docs/screen-options-resolution/#setting-parent-screen-options-based-on-child-navigators-state

**Comment by jmparsons** [comment]
@satya164 `getFocusedRouteNameFromRoute` will be `undefined` on first pass if the tab is nested in another tab. The `state` will be empty for the first screen.
