### ISSUE TITLE
Cannot use Hooks inside Header component

### ISSUE THREAD

**Issue by tazsingh** [react-navigation/react-navigation#8463]
**Current Behavior**

- What code are you running and what is happening?

My Stack Navigator is defined as such (please note the `header` option):

```tsx
<StackNavigator.Navigator screenOptions={{ header: NavigationHeader }}>
  <DrawerNavigator.Screen name='Home' component={HomeScreen} />
  <DrawerNavigator.Screen name='Profile' component={ProfileScreen} />
</StackNavigator.Navigator>
```

I would think that `NavigationHeader` can be a React component, but apparently it has the same function signature as a React component while not being a React component. From the docs:

> Function that given `HeaderProps` returns a React Element, to display as a header.

- Include a screenshot or video if it makes sense.

The error that I get if I put a hook inside `NavigationHeader` is (in this case, I tried to `useMemo`):

```
Warrning: React has detected a change in the order of Hooks called by HeaderContainer. This will lead to bugs and errors if not fixed. For more information, read the Rules of Hooks: https://fb.me/rules-of-hooks

   Previous render            Next render
   ------------------------------------------------------
1. useContext                 useContext
2. useMemo                    useMemo
3. undefined                  useMemo
   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    in HeaderContainer (at StackView.tsx:328)
    in CardStack (at StackView.tsx:435)
    in KeyboardManager (at StackView.tsx:433)
    in SafeAreaProviderCompat (at StackView.tsx:430)
    in RCTView (at StackView.tsx:429)
    in StackView (at createStackNavigator.tsx:82)
    in StackNavigator (at App.tsx:96)
    in NavigationStack (at SceneView.tsx:121)
    in StaticContainer
```
_(stack trace continues)_

**Expected Behavior**

- What do you expect should be happening?

I would expect the `header` option can be a React component. I'm specifically trying to `useMemo` on the `styleInterpolator` as it [appears that that result should be memoized](https://github.com/react-navigation/react-navigation/blob/1aadc79fb89177a2fff2dcd791d67a3c880009d0/packages/stack/src/views/Header/HeaderSegment.tsx#L116).

It also appears that the default `Header` component is mounted as a React component while the screen option is not? https://github.com/react-navigation/react-navigation/blob/b14fd9453d5b581966228f9cbb1f89b4fcecf52a/packages/stack/src/views/Header/HeaderContainer.tsx#L165

I would expect the two to be handled in the same way - both mounted as React components.

~~- Include a screenshot or video if it makes sense.~~

**How to reproduce**

https://snack.expo.io/Yvhp7KUKx

I've attempted to recreate the `screenOptions` with a custom Header that has a hook, however, the error is not manifesting in the Snack 🤷 

Looking at the code itself, it seems to verify my suspicion that I describe above - that it's not being rendered as a React component.

I'm unsure if there's some version mismatch between the Snack and my environment. I took the example from the website and added the `screenOptions` onto that.

Kindly let me know if this was helpful or if I can assist with reproducing this in other ways 🙏

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Tested on iOS Simulator
| @react-navigation/native       | 5.5.1
| @react-navigation/stack        | 5.5.1
| react-native-gesture-handler   | 1.6.0
| react-native-safe-area-context | 0.7.3
| react-native-screens           | 2.2.0
| react-native                   | Expo 37.0.1
| react                   | 16.13.1
| expo                           | 37.0.0
| node                           | 12.14.0
| npm or yarn                    | yarn v1.22.4

**Comment by satya164** [comment]
```js
header: props => <NavigationHeader {...props} />
```

**Comment by tazsingh** [comment]
@satya164 Thank you for describing the function signature.

Do you not find this behaviour odd? Why is there a difference? Why introduce a level of indirection where it's unnecessary and where the default code path internally is using a React component?

**Comment by satya164** [comment]
Because it's impossible to detect what's a component and what's an inline function returning an element and they are not interchangeable. Using an inline function as a component will cause other issues like losing local state and perf issues which is harder to catch than not being able to use a hook.

**Comment by iway1** [comment]
this really shouldn't have been closed. This is a massive unnecessary limitation. Surely there is a way to enable using hooks inside of a header component, there's no way that's a technically impossible thing to do

**Comment by sambouchard-newforma** [comment]
The solution provided by @satya164 also breaks this eslint rule : https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/no-unstable-nested-components.md  Shouldnt there exist a solution that both allow to use hooks inside a custom Header component and allow us to pass the header as such : `header: CustomHeader` without getting the Eslint warning?
