### ISSUE TITLE
Header missing in tree

### ISSUE THREAD

**Issue by soroushm** [react-navigation/react-navigation#8464]
**Current Behavior**

in latest navigation custom header is look like changed and my secund header in child stack is missing (check marketNavigation in bellow) but in stack version 5.2.11 working as well

## root navigation
root navigation have main navigation its also have default header for all pages
```
<NavigationContainer
        theme={MyTheme}
      >
        <Stack.Navigator
          initialRouteName="Bootstrap"
          screenOptions={{
            gestureEnabled: false,
            header,
          }}
        >
          <Stack.Screen name="MainNavigator" component={MainNavigator} />
          <Stack.Screen
            name="Bootstrap"
            component={Bootstrap}
            options={{
              header: () => null,
            }}
          />
          <Stack.Screen
            name="AuthNavigator"
            component={AuthNavigator}
            options={{
              header: authHeader,
            }}
          />
//more screen ....
        </Stack.Navigator>
      </NavigationContainer>
```

## main navigation
the main navigator is some tab
```
export default function MainNavigator() {
  return (
    <Tab.Navigator initialRouteName="market" lazy tabBarOptions={{ showLabel: false }} screenOptions={screenOptions}>
      <Tab.Screen name="market" component={MarketNavigation} />
      <Tab.Screen name="portfolio" component={PortfolioNavigator} />
      <Tab.Screen name="search" component={SearchNavigator} />
      <Tab.Screen name="order" component={TransactionNavigation} />
      <Tab.Screen name="settings" component={MenuNavigation} />
    </Tab.Navigator>
  )
}
```

## market navigation 
have a second header (subheader) it's missing on update
```
export default function MarketNavigation(props) {
  return (
    <Stack.Navigator
      initialRouteName="MarketMap"
      headerMode="screen"
      screenOptions={{
        header: subHeader,
        headerStyle: {
          height: 45,
        },
      }}
    >
      <Stack.Screen name="MarketMap" component={MarketMap} />
      <Stack.Screen name="HotList" component={HotList} />
      <Stack.Screen name="HotLists" component={HotLists} />
      <Stack.Screen name="IPOLists" component={IPOLists} />
      <Stack.Screen name="WatchList" component={WatchList} />
      <Stack.Screen name="WatchLists" component={WatchLists} />
      <Stack.Screen name="MarketIndustryList" component={MarketIndustryList} />
    </Stack.Navigator>
  )
}
```

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | |
| @react-navigation/native       | "^5.1.6" ("5.5.1") |
| @react-navigation/stack        |  "^5.2.11" ("5.5.1") |
| react-native-screens           | "^2.4.0" ("2.8.0") |
| react-native                   | 62.2 |

**Comment by soroushm** [comment]
its happened in the latest version

**Comment by satya164** [comment]
Use `headerShown: false` to hide header instead of `header: () => null,`

**Comment by soroushm** [comment]
@satya164 its not under bootstrap still exist with `headerShown: false`

hope this flow helps you better  understanding
<img width="331" alt="Screen Shot 2020-06-17 at 15 28 08" src="https://user-images.githubusercontent.com/1031663/84890537-c8a14900-b0af-11ea-980f-c8f1608ee476.png">
![Screen-Shot-2020-06-17-at-15 28 16](https://user-images.githubusercontent.com/1031663/84890553-cdfe9380-b0af-11ea-9582-81a2b1272633.jpg)

**Comment by satya164** [comment]
If you want nested header, you can pass `headerShown: true` in the `screenOptions` of the nested stack navigator.

**Comment by soroushm** [comment]
@satya164 Nope didn't work 
It look like misunderstanding the header of different flow is hidden.
actually I have two headers on parent and child (main header and subheader)
parent header is on root navigation 
subheader is on market navigation

**Comment by soroushm** [comment]
@satya164 thanks its working now

**Comment by BogdanRad** [comment]
Hey guys, I want to hide the header in the 2 screens and  `headerShown: false` does not working...  On android it's working.. the problem is on ios..

my version is: 
    "@react-navigation/native": "^5.7.3",
    "@react-navigation/stack": "^5.9.0",

can someone help me with this problem?

![image](https://user-images.githubusercontent.com/40359109/92562375-8aff2700-f27e-11ea-9f67-fea1815c081f.png)
