### ISSUE TITLE
Typescript error with `safeAreaInset` in tabBarOptions while migrating from 4.x

### ISSUE THREAD

**Issue by janKir** [react-navigation/react-navigation#8471]
**Current Behavior**

I'm am currently migrating from 4.x to 5.x and while adding the existing `tabBarOptions` to `<Tab.Navigator>` I receive a typescript error, saying that `'safeAreaInset' does not exist in type 'BottomTabBarOptions'` and suggesting to use `safeAreaInsets` (plural) instead, where however the 'never' string does not seem to fit because it requires numbers.

According to the [documentation](https://reactnavigation.org/docs/bottom-tab-navigator/#tabbaroptions) my code should work with `safeAreaInset` (singular) and 'never' values. However, e.g. [the stack navigator documentation](https://reactnavigation.org/docs/stack-navigator/#safeareainsets) describes the syntax aligning with the typescript error. So probably the documentation is just not updated there.

**Expected Behavior**
 The documentation and typescript types are not conflicting. If there are changes in the option types, ideally there should be an explanation how to migrate those. Could I simply use the plural key with 0 values instead of 'never' to have the same behavior?

**How to reproduce**
In a typescript project with the bottom-tabs package, add:
```typescript
import { createBottomTabNavigator } from '@react-navigation/bottom-tabs';
const Tab = createBottomTabNavigator();

....

<Tab.Navigator
  tabBarOptions={{
	safeAreaInset: {
	  bottom: 'never',
	  top: 'never',
	},
  }}
> ... </Tab.Navigator>
```

**Your Environment**

| software                      | version |
| ----------------------------- | ------- |
| iOS or Android                | -
| @react-navigation/native      | 5.5.1
| @react-navigation/bottom-tabs | 5.5.2
| react-native-screens          | 2.2.0
| react-native                  | 0.61
| expo                          | 37
| node                          | 12.10.0
| npm or yarn                   | 6.10.3

This issue seems to be similar to #7007 which however does not target v5 and does not answer the question if `safeAreaInsets` with 0 values behaves the same as `safeAreaInset` with 'never' values.

**Comment by satya164** [comment]
Updated docs https://reactnavigation.org/docs/bottom-tab-navigator/#safeareainsets
