### ISSUE TITLE
Bug with live reload and blur event listener

### ISSUE THREAD

**Issue by alamothe** [react-navigation/react-navigation#8477]
**Current Behavior**

This bug is for live reload and focus/blur event listeners. React Navigation correctly assumes that focus and blur are about subscription/cleanup: https://reactnavigation.org/docs/function-after-focusing-screen/

In our case, we start polling when the component is focused, and stop polling when it's blurred. This is the code:
```tsx
export function usePolling(
	callback: () => void,
	pollInterval: number,
) {
	const navigation = useNavigation()
	const timer = React.useRef<ReturnType<typeof setTimeout> | null>(null)
	const lastRefreshed = React.useRef<number>(Date.now())

	const setRefresh = (delay: number) => {
		timer.current = setTimeout(() => {
			lastRefreshed.current = Date.now()
			setRefresh(pollInterval)
			callback()
		}, delay)
	}

	React.useEffect(() => {
		const focus = () => {
			const elapsed = Date.now() - lastRefreshed.current
			setRefresh(pollInterval - elapsed)
		}

		const blur = () => {
			if (timer.current != null) {
				clearTimeout(timer.current)
				timer.current = null
			}
		}

		if (timer.current != null) {
			clearTimeout(timer.current)
			setRefresh(pollInterval)
		}

		navigation.addListener("blur", blur)
		navigation.addListener("focus", focus)
		return () => {
			navigation.removeListener("focus", focus)
			navigation.removeListener("blur", blur)
		}
	}, [callback])
}
```
So: 
- we start polling once we're focused,
- we stop polling once we're blurred.

This works well, but the problem happens with **live reload**. With live reload, React will unmount the components (which is fine), but **blur is never called**.

This means that the timer will not be cleared. Depending on `callback` this will crash the whole app. 

In essence, focus/blur events are not symmetrical with respect for live reload.

**Expected Behavior**

I expect blur to be called, since the component will be unmounted and mounted again. Otherwise there is no place where to perform the cleanup successfully.

**How to reproduce**

1. Make a simplest component which uses usePolling. Put a `console.log` in focus and blur.
2. Change a file and hit save.
3. Observe that blur was not called, and now two timers will be triggering.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | iOS
| @react-navigation/native       | 5.5.1
| react-native                   | 
| expo                           | 37.0.12
| node                           | 10.19.0
| npm or yarn                    | npm

**Comment by satya164** [comment]
Component unmounting doesn't mean the screen was blurred. You need to handle unmount yourself or use `useFocusEffect` to handle all of this automatically https://reactnavigation.org/docs/use-focus-effect

**Comment by alamothe** [comment]
Do you think it's a bug if there's more focus than blur for the same component? 

If so, then this is a bug... I can repro 10 focus in a row, and no blur with live reload.

**Comment by alamothe** [comment]
I feel a reasonable assumption is that the sequence of calls would be symmetrical: focus, blur, focus, blur... 

not: focus, focus, focus, focus...
