### ISSUE TITLE
"cardStyleInterpolator" causes the "AutoFocus" of "TextInput" to not work properly, and the keyboard will pop up and retract automatically.

### ISSUE THREAD

**Issue by ngxu** [react-navigation/react-navigation#8478]
**Current Behavior**

- "cardStyleInterpolator" causes the "AutoFocus" of "TextInput" to not work properly, and the keyboard will pop up and retract automatically.
- gif
<img src="https://user-images.githubusercontent.com/43433064/85101749-b8b37180-b235-11ea-82dd-b2d40b353a75.gif"  width="300px">

</img>
- my code

```javascript

const forFade = ({ current, closing }) => ({
  cardStyle: {
    opacity: current.progress,
  },
});

SearchPage:{
      screen: SearchPage,
      navigationOptions: () => ({
        title: `Search`,
        header: () => { },
        cardStyleInterpolator: forFade
      }),
      
    }

```

**Expected Behavior**

If I annotate or delete "cardStyleInterpolator: forFade", the keyboard will be no problem, but I want the page to switch to a gradient effect

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Android
| react-navigation               |4.1.1
| react-navigation-stack         |2.3.13
| react-navigation-tabs          | 2.8.12
| react-navigation-drawer        |Not Installed
| react-native-reanimated        |1.8.0
| react-native-gesture-handler   |1.6.1
| react-native-safe-area-context |0.7.3
| react-native-screens           |2.6.0
| react-native                   |0.59.8
| expo                           |
| node                           |
| npm or yarn                    |npm

**Comment by ngxu** [comment]
I did not use `react-navigation-drawer`,the project does not need to be used

**Comment by ngxu** [comment]
如果我注释或删除“ cardStyleInterpolator：forFade”，键盘将没有问题，但是我希望页面切换到渐变效果

-gif 

<img src="https://user-images.githubusercontent.com/43433064/85103126-abe44d00-b238-11ea-8ac7-3bbe5f2a14b5.gif" width="300"/>

**Comment by ngxu** [comment]
```javascript

componentDidMount(){
    if (this.Searching != undefined) {
        
        setTimeout(()=>{
            console.log(this.Searching)
            this.Searching.focus();
        },1000)
        
    }
}
```
I added a timer to the componentDidMount of the TextInput page, although it can be solved, but I don’t know how much time should be taken to get the focus right

**Comment by ngxu** [comment]
@satya164 How to solve in react-navigation 4.x

**Comment by ngxu** [comment]
```js
componentDidMount(){

    this.didFocus = this.props.navigation.addListener('didFocus', () => this.Searchinged.focus());

}
componentWillUnmount(){

    this.didFocus.remove();

}
```
This method works for me. very perfect
Thanks @satya164

**Comment by viet97** [comment]
> ```js
> componentDidMount(){
> 
>     this.didFocus = this.props.navigation.addListener('didFocus', () => this.Searchinged.focus());
> 
> }
> componentWillUnmount(){
> 
>     this.didFocus.remove();
> 
> }
> ```
> 
> This method works for me. very perfect
> Thanks @satya164

this not resolve the issue im still facing the problem. any help ?
