### ISSUE TITLE
Unable to set navigator header title from direct children screen

### ISSUE THREAD

**Issue by jbrodriguez** [react-navigation/react-navigation#8481]
**Current Behavior**

Trying to set header title for a navigator, using the options prop from one its direct children screens, but it doesn't work

```
- RootStack.Navigator
  - RootStack.Screen
    - Tab.Navigator
      - Tab.Screen 
        - ProfileStack.Navigator
          - ProfileStack.Screen options={{headerTitle: 'ProfileHT'}}
```

Check the snack below

**Expected Behavior**

The ProfileStack.Navigator should have ownership of the header, to that its direct children are able to change its properties.

**How to reproduce**

This is a snack reproducing the issue **https://snack.expo.io/VCKjwc4GI**

Click on 'Go to Home', then select the Profile tab.

The title should change to 'ProfileHT'

**Your Environment**

| software                      | version |
| ----------------------------- | ------- |
| iOS or Android                | 10.15.4 |
| @react-navigation/native      | 5.5.1 | 
| @react-navigation/bottom-tabs | 5.5.2 | 
| react-native-screens          | 2.7.0 |
| react-native                  | 0.62.2 | 
| expo                          | n/a |
| node                          | 13.13.0 | 
| yarn                   | 1.22.4 |

**Comment by satya164** [comment]
Either hide the header on `RootStack` or set `screenOptions={{ headerShown: true }}` on `ProfileStack`

**Comment by jbrodriguez** [comment]
Thanks @satya164 for the insight !

I tried `screenOptions={{ headerShown: true }}` and got this

![Screen Shot 2020-06-19 at 15 53 26](https://user-images.githubusercontent.com/1305422/85202698-d8967400-b2cd-11ea-97db-476e8e35566b.png)

so basically two headers, I could hide RootStack header somehow, but I'd lose the go back to settings button.

Also, if I add another screen to the ProfileStack.Navigator, I end up with this 

![Screen Shot 2020-06-20 at 08 12 12](https://user-images.githubusercontent.com/1305422/85202722-10052080-b2ce-11ea-8801-4a1c627acb65.png)

https://snack.expo.io/VCKjwc4GI is updated with these changes.

So, I'm not sure if I want to do is at all possible with V5.

I don't see it as an uncommon use case, I'l gladly take any additional hints on how to get this done.
