### ISSUE TITLE
In first render, icons are showed slowly 

### ISSUE THREAD

**Issue by VictorioMolina** [react-navigation/react-navigation#8485]
Problem:

- I have a Splash Screen (for loading fonts, user auth...) and the Navigator. To choose between one thing or other I am doing a contidional render. My problem is that in the firset render, the tab navigator icons are showed really slow, I mean, after a little delay.

Environment:

Expo SDK 36
@react-navigation/native v.5
Material Botton Tab Navigator
Mode: development

**Comment by SleeplessByte** [comment]
Are you loading the MaterialCommunityIcons font?

**Comment by VictorioMolina** [comment]
Mmmm nope :/ Where I can find it?

**Comment by SleeplessByte** [comment]
So basically when you're using [`@expo/vector-icons`](https://docs.expo.io/guides/icons/#expovector-icons) (which uses [`react-native-vector-icons`](https://github.com/oblador/react-native-vector-icons), also used by `react-navigation`), you can import the font:

```typescript
import { MaterialCommunityIcons } from '@expo/vector-icons
```

You can then follow [this guide](https://docs.expo.io/guides/preloading-and-caching-assets/#pre-loading-and-caching-assets). So something like:

```typescript
Font.loadAsync(MaterialCommunityIcons.font)
```
