### ISSUE TITLE
Deep linking doesn't work properly with StackNavigator inner page

### ISSUE THREAD

**Issue by rajneshbiz** [react-navigation/react-navigation#8489]
**Expected Behavior**
Deep linking works in the same way when app is closed and opened

I have most similar situation  from  https://github.com/react-navigation/react-navigation/issues/7908
But I have only firstpage and firstSubPage
<NavigationContainer ref={ref} initialState={initialState}>
  <FirstStack.Navigator>
      <FirstStack.Screen name="first" component={First} />
      <FirstStack.Screen name="subfirst" component={SubFirst} />
    </FirstStack.Navigator>
</NavigationContainer>

Tried this 

  const { getInitialState } = useLinking(ref, {
    prefixes: ['myapp://'],
    initialRouteName: 'second',
    config: {
      // second: {
      //   screens: {
      subsecond: 'test/:someParam',
      second: 'second',
      //   }
      // },
    },
  });

and many other combinations but did not work .

Issue : When app was closed, then back arrow is not coming and when app is open then working fine.

**Environment**

| software                       | version |
| ------------------------------ | ------- |
| @react-navigation/native       | ^5.1.3

**Comment by rajneshbiz** [comment]
I have updated the @react-navigation/native version that is ^5.1.3

**Comment by satya164** [comment]
https://reactnavigation.org/docs/configuring-links#rendering-an-initial-route

**Comment by rajneshbiz** [comment]
import 'react-native-gesture-handler';
import React, { useRef } from 'react';
import {
  View,
  Text,
  StatusBar,
  Button,
} from 'react-native';
import { NavigationContainer, useLinking } from "@react-navigation/native";
import { createBottomTabNavigator } from "@react-navigation/bottom-tabs";
import { createStackNavigator } from "@react-navigation/stack";

function SubSecond({ route, navigation }) {
  return (
    <View style={{ flex: 1 }}>
      <Text>SubSecond</Text>
      <Text>Item Id: {route.params.someParam}</Text>
    </View>
  )
}

function Second({ navigation }) {
  return (
    <View style={{ flex: 1 }}>
      <Button title='title' onPress={() => navigation.navigate('subsecond', { someParam: "dfds" })} />
      <Text>Second</Text>
    </View>
  )
}


const SecondStack = createStackNavigator();
const Stack = createStackNavigator();

function SecondStackView() {
  return (
    <SecondStack.Navigator initialRouteName="second">
      <SecondStack.Screen name="second" component={Second} />
      <SecondStack.Screen name="subsecond" component={SubSecond} />
    </SecondStack.Navigator>
  )
}

const App = () => {
  const ref = useRef(null);

  const { getInitialState } = useLinking(ref, {
    prefixes: ['myapp://'],
    config: {
      screens: {
        initialRouteName: 'second',
        screens: {
          subsecond: 'test/:someParam',
        },
      }
    },
  });


  const [isReady, setIsReady] = React.useState(false);
  const [initialState, setInitialState] = React.useState();

  React.useEffect(() => {
    Promise.race([
      getInitialState(),
      new Promise(resolve =>
        // Timeout in 150ms if `getInitialState` doesn't resolve
        // Workaround for https://github.com/facebook/react-native/issues/25675
        setTimeout(resolve, 150)
      ),
    ])
      .catch(e => {
        console.error(e);
      })
      .then(state => {
        if (state !== undefined) {
          setInitialState(state);
        }
        setIsReady(true);
      });
  }, [getInitialState]);

  if (!isReady) {
    return null;
  }

  return (
    <>
      <StatusBar barStyle="dark-content" />
      <NavigationContainer ref={ref} initialState={initialState}>
        <SecondStack.Navigator initialRouteName="second">
          <SecondStack.Screen name="second" component={Second} />
          <SecondStack.Screen name="subsecond" component={SubSecond} />
        </SecondStack.Navigator>
      </NavigationContainer>
    </>
  );
};

export default App;


This is not working @satya164 .

Please assist as i done same as your reference even not working.
