### ISSUE TITLE
[Bug Report] Bottom Tab hardly response in Android debugging mode

### ISSUE THREAD

**Issue by seunghyun-woo** [react-navigation/react-navigation#8490]
**Current Behavior**
I made a sample project and copy-paste an example code in official docs. (see [This](https://reactnavigation.org/docs/bottom-tab-navigator/#example))
When I run this on android device and turn on debug mode, bottom tab hardly response to touch.

**Expected Behavior**
It should respond to touch and switch the screen.

**How to reproduce**'
Just copy-paste an example code in official bottom-tab docs and run it.

**Your Environment**

```
System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 19.11 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.16.3 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 28, 29
      Build Tools: 23.0.1, 28.0.3, 29.0.3
      System Images: android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom_64, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  npmPackages:
    react: ~16.9.0 => 16.9.0 
    react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4 
  npmGlobalPackages:
    react-native-cli: 2.0.1

Android                

"@react-navigation/bottom-tabs": "^5.2.7",
"@react-navigation/native": "^5.1.6",
"react-native-screens": "~2.2.0",
```

**Comment by raajnadar** [comment]
https://reactnavigation.org/docs/troubleshooting#app-is-not-working-properly-when-connected-to-chrome-debugger

**Comment by seunghyun-woo** [comment]
> The versions mentioned in the issue for the following packages differ from the latest versions on npm:
> 
> * `@react-navigation/bottom-tabs` (found: `5.2.7`, latest: `5.5.2`)
> * `@react-navigation/native` (found: `5.1.6`, latest: `5.5.1`)
> 
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?

Versions upon is what my sample project has, and this issue is still exist on my project which has version: `
    "@react-navigation/bottom-tabs": "^5.5.1",
    "@react-navigation/native": "^5.5.0",`
