### ISSUE TITLE
Keyboard Behaviour when you navigate faster (Android)

### ISSUE THREAD

**Issue by felire** [react-navigation/react-navigation#8494]
**Current Behavior**

When you navigate to a screen with keyboard and then you goBack faster, the keyboard do this behaviour: 

disappear -> appear -> disappear (very faster)

If you navigate slowly it not happens, but it's not a nice behaviour.

**Expected Behavior**

The keyboard should disappear and never appear again in that screen.

**How to reproduce**

You should have a stack with two screen, in the second screen you should have a TextInput with `autoFocus` and then you will have to navigate and goBack faster

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Android
| @react-navigation/native       | 5.5.1
| @react-navigation/stack        | 5.5.1
| react-native-gesture-handler   | last
| react-native-safe-area-context | last
| react-native-screens           |
| react-native                   | 0.62.2
| expo                           |
| node                           |
| npm or yarn                    |

**Comment by satya164** [comment]
React Navigation cannot predict that you're going to press goBack quickly. If you don't want text input to be focused instantly, don't use `autoFocus` and use `transitionEnd` event to focus it.

**Comment by acro5piano** [comment]
I solved the problem by showing `TextInput` only in focused screen. In other words, re-show `TextInput` fire auto focus.

```jsx
  const [isFocused, setIsFocued] = React.useState(true)

  const setFocus = React.useCallback(() => {
    setIsFocued(true)
  }, [])

  const setBlur = React.useCallback(() => {
    setIsFocued(false)
  }, [])

  const navi = useNavigation()

  React.useEffect(() => {
    navi.addListener('focus', setFocus)
    navi.addListener('blur', setBlur)
    return () => {
      navi.removeListener('focus', setFocus)
      navi.removeListener('blur', setBlur)
    }
  }, [])

  return (
    <View>
        {focused && <TextInput autoFocus />}
    </View>
  )
```
