### ISSUE TITLE
Strange keyboard behaviour when you focus an input after goBack

### ISSUE THREAD

**Issue by felire** [react-navigation/react-navigation#8495]
**Current Behavior**

I have a screen with an input, when you go back to that screen it should execute a function to focus the input. When you go to the next screen and the you go back and the input focus, the input appear and disappear and never show again until you focus it manually.
I Had to execute the focus function with a TIMEOUT of a second to make it works good, but it's not a nice solution.

**Expected Behavior**

The expected behaviour is that if you goBack and you focus your input, it should focus good. like it happens in IOS.

**How to reproduce**

In my case I have three screens but I think you can recreate this with two screens. I go to the second screen where I have an input, and the keyboard is showing. Then I navigate to another Screen and the keyboard hides, and then I go back to the screen with the input and then I detect the focus event and I focus the input. When I do that, the keyboard appears and disappears.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Android
| @react-navigation/native       | 5.5.1
| @react-navigation/stack        | 5.5.1
| react-native-gesture-handler   |
| react-native-safe-area-context |
| react-native-screens           |
| react-native                   | 0.62.2
| expo                           |
| node                           |
| npm or yarn                    | yarn

**Comment by satya164** [comment]
Please read the docs https://reactnavigation.org/docs/typescript

**Comment by satya164** [comment]
https://github.com/react-navigation/react-navigation/pull/7931

**Comment by felire** [comment]
But it's still working bad in the last version, I don't understand why you closed the issue @satya164

**Comment by matthargett** [comment]
@satya164 #7931 isn't merged, so this issue still exists. can we re-open this issue while we work out how to get the fix merged?
