### ISSUE TITLE
Weird types declaration (typescript) V5

### ISSUE THREAD

**Issue by pilotocheg** [react-navigation/react-navigation#8496]
**Current Behavior**

- What code are you running and what is happening?
I was going through the getting started guide (with ReactNative + typescript) and saw wrong typing in few places (maybe there are more);

- Include a screenshot or video if it makes sense.

<img width="483" alt="Screenshot 2020-06-22 at 17 15 50" src="https://user-images.githubusercontent.com/38259170/85299402-e4d92780-b4ad-11ea-9e96-adad56c27edf.png">
<img width="395" alt="Screenshot 2020-06-22 at 17 15 45" src="https://user-images.githubusercontent.com/38259170/85299407-e60a5480-b4ad-11ea-8c96-f6d0115a1084.png">
<img width="1164" alt="Screenshot 2020-06-22 at 17 13 58" src="https://user-images.githubusercontent.com/38259170/85299409-e73b8180-b4ad-11ea-98d2-338a66c77956.png">
<img width="962" alt="Screenshot 2020-06-22 at 17 13 28" src="https://user-images.githubusercontent.com/38259170/85299412-e7d41800-b4ad-11ea-8bbb-d60bd2fec921.png">

**Expected Behavior**

- What do you expect should be happening?
1) `navigation.navigate` and `navigation.push` should accept the `string` type as the first argument, and an optional `object` type as the second argument.
2) `StackScreenProps` type should receive an 'object' like type as the first param.

- Include a screenshot or video if it makes sense.

**How to reproduce**

- You must provide a way to reproduce the problem. If you are having an issue with your machine or build tools, the issue belongs on another repository as that is outside of the scope of React Navigation.
- Either re-create the bug on [Snack](https://snack.expo.io) or link to a GitHub repository with code that reproduces the bug.
- Explain how to run the example app and any steps that we need to take to reproduce the issue from the example app.
- Keep the repro code as simple as possible, with the minimum amount of code required to repro the issue.
- Before reporting an issue, make sure you are on latest version of the package.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS                 | 13.4.1
| @react-navigation/native       | 5.5.1
| @react-navigation/stack        | 5.5.1
| react-native-gesture-handler   | 1.6.1
| react-native-safe-area-context | 3.0.5
| react-native-screens           | 2.9.0
| react-native                   | 0.62.2
| expo                           | - 
| node                           | 12.17.0
| yarn                    | 1.22.4

**Comment by satya164** [comment]
Please read the docs https://github.com/react-navigation/react-navigation/pull/7931
