### ISSUE TITLE
Deeplinking and authentication flow

### ISSUE THREAD

**Issue by ericlifs** [react-navigation/react-navigation#8501]
**Current Behavior**
I have two different navigators "rootStack" and "loginStack" which are shown based upon the user is logged in or not (rootStack is shown for logged in obviously).

![image](https://user-images.githubusercontent.com/7376892/85405060-3c22da80-b536-11ea-9d44-92c1c0e8b83e.png)

When doing the deeplink between webapp and mobile, if the user is not logged in within the app, I'm getting the following error:

![image](https://user-images.githubusercontent.com/7376892/85404818-e4846f00-b535-11ea-80b8-898c2cddba75.png)

As the user is logged in within the web but not on the app, he's trying to navigate to a screen that's not authorized to see since it's not logged in.

**Expected Behavior**
I wanted to know if there is a way of handling this authentication + deeplink cases. I have seen questions like this on stackoverflow but they are related to v4 of react-navigation.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| @react-navigation/native       | 5.5.1
| react-native                   | 0.62.2

**Comment by SleeplessByte** [comment]
You can use a [NotFound](https://reactnavigation.org/docs/configuring-links/#handling-unmatched-routes-or-404) route, store the requested state, and handle it after you login (or just ignore it).

**Comment by ericlifs** [comment]
Thanks for the response @SleeplessByte ! How can I fire a navigation within the NotFound route?

Thanks in advance 🚀 !

**Comment by SleeplessByte** [comment]
I think you can do:

```typescript

function NotFound() {
  const url = useUrl();
  ...
}
```

**Comment by ericlifs** [comment]
Thanks @SleeplessByte !

I was able to get the info from the params being set automatically by react-navigation. If the deeplink gets opened while the app was closed (it will call Linking.getInitialURL()) I provide that url to the NotFound screen and then parse it to get the params structure and then treat them as any deeplink.

**Comment by kamo93** [comment]
> Thanks @SleeplessByte !
> 
> I was able to get the info from the params being set automatically by react-navigation. If the deeplink gets opened while the app was closed (it will call Linking.getInitialURL()) I provide that url to the NotFound screen and then parse it to get the params structure and then treat them as any deeplink.

@ericlifs Sorry im having the same issue but I dont understand what you did. Could be possible to copy the actual code. Thanks in advance.
