### ISSUE TITLE
useHeaderHeight returns 0 in nested Stack.Navigators

### ISSUE THREAD

**Issue by EtherealData** [react-navigation/react-navigation#8505]
**Current Behavior**

- Following the documentation for nesting navigators
- Trying to useHeaderHeight hook inside of a nested Stack.Navigator always returns 0

**Expected Behavior**

- It should return the correct header height regardless of where the hook is used

**How to reproduce**

App.js
```
import React from 'react';
import {useHeaderHeight} from '@react-navigation/stack';
import {createStackNavigator} from '@react-navigation/stack';
import {LoginStackNavigator} from './LoginStackNavigator';

const Stack = createStackNavigator();

export const App = () => <View>
        <Stack.Navigator>
          <Stack.Screen name="Login" component={LoginStackNavigator} />
        </Stack.Navigator>
      )}
</View>
```

LoginStackNavigator.js
```
import React from 'react';
import {useHeaderHeight} from '@react-navigation/stack';
import {createStackNavigator} from '@react-navigation/stack';
import {Login} from './Login';

const Stack = createStackNavigator();

export const LoginStackNavigator = () => {
  const headerHeight = useHeaderHeight();
  console.log({headerHeight});
  // returns appropriate height, 88 on ios
  return (
    <Stack.Navigator>
      <Stack.Screen name="Login with phone" component={Login} />
    </Stack.Navigator>
  );
};
```

Login.js
```
import React from 'react';
import {Text} from 'react-native';
import {useHeaderHeight} from '@react-navigation/stack';

export const Login = () => {
  const headerHeight = useHeaderHeight()
  //returns 0 in nested stack navigator screen
  console.log({headerHeight})
  return <Text>{headerHeight}</Text>
}
```

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | iOS
| @react-navigation/native       | 5.5.1
| @react-navigation/stack        | 5.5.1
| react-native-gesture-handler   | 5.5.1
| react-native-safe-area-context | 3.0.2
| react-native-screens           | 2.8.0
| react-native                   | 0.62.2
| expo                           | n/a (barebones)
| node                           | 12.9.0
| npm or yarn                    | 1.21.0

**Comment by satya164** [comment]
There's no header rendered by default in nested stack, so there's no header height.

**Comment by Daavidaviid** [comment]
Same problem since I upgraded from 5.4.1 to 5.6.2

**Comment by chichke** [comment]
Same here please fix 
Love

**Comment by yoobit** [comment]
@satya164 can you elaborate on how we can expose it in context?

**Comment by jagwingchoy** [comment]
I am having an app structure like this sample:

    <App.StackNavigator headerMode="none">
      {app.user ? (
        <TabNavigator>
          <Tab.FirstTab.StackNavigator>
            <FirstTab.Screen ... />
            {/* Other first tab screens in stack navigator */}
          </Tab.FirstTab.StackNavigator>
          <Tab.SecondTab.StackNavigator />
          <Tab.ThirdTab.StackNavigator />
          <Tab.FourthTab.StackNavigator />
        </TabNavigator>
      ) : (
        <Auth.StackNavigator>
          <Auth.Screen ... />
        </Auth.StackNavigator>)
      }
    </App.StackNavigator>

So it's nearly impossible not to nest the stack as you recommended.
@satya164 Could you help and teach me how to get the `headerHeight` in this case? Thanks.

**Comment by satya164** [comment]
@jagwingchoy the issue is about having parent stack header displayed and child stack header hidden. you're hiding the parent stack header which will work fine with `useHeaderHeight`.

**Comment by Bijiabo** [comment]
My child component just needs to know the height of the navigation rendering, which should not be related to whether the page is rendered or not.

I just need a way to get the navigation bar height. This design looks a bit silly

**Comment by estani** [comment]
Take it from`@react-navigation/elements` from v6 onwards
```js
import { useHeaderHeight } from '@react-navigation/elements';
const headerHeight = useHeaderHeight();
```
see: https://stackoverflow.com/questions/45734664/react-navigation-get-stack-header-height
