### ISSUE TITLE
I think useRoute with having type must have params

### ISSUE THREAD

**Issue by jihokim2** [react-navigation/react-navigation#8507]
**Current Behavior**

type RootStackParamList = {
  Home: undefined;
  HomeTextInput: undefined;
  HomeSearchResult: {searchText: string};
};
 type HomeSearchResultRouteProp = RouteProp<
    RootStackParamList,
    'HomeSearchResult'>;

 const route = useRoute<'HomeSearchResultRouteProp'>();

 const {searchText} = route.params;

Error: TS2339: Property 'params' does not exist on type 'Pick<Route<"HomeSearchResult">, "key" | "name">'.

Note: <> is not visiable. So useRoute<'HomeSearchResultRouteProp'> I insert ''. 
**Expected Behavior**

I think route must have params. But It doesn't.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | android 9.0 +
| @react-navigation/native       | 5.6.0
| @react-navigation/stack        | 5.6.0
| react-native-gesture-handler   | 1.6.1
| react-native-safe-area-context | 3.0.6
| react-native-screens           | 2.9.0
| react-native                   | 0.62.2
| node                           | 12.16.0
| npm or yarn                    | yarn 1.22.4

**Comment by satya164** [comment]
https://reactnavigation.org/docs/typescript/#type-checking-screens

**Comment by jihokim2** [comment]
I did same way like https://reactnavigation.org/docs/typescript/#type-checking-screens. But I met this error. I think useRoute type check have a problem. So I made a issue. If this is not bug, please tell me how can I do avoid this problem Thank you @satya164

**Comment by satya164** [comment]
Use the `HomeSearchResultRouteProp` type instead of a string (`'HomeSearchResultRouteProp'`) to annotate (remove quotes).

**Comment by jihokim2** [comment]
I did this. But It is same. Annotate is not include my code. <HomeSearchResultRouteProp>  is not showing. So I add annotate. 

type RootStackParamList = {
Home: undefined;
HomeTextInput: undefined;
HomeSearchResult: {searchText: string};
};
type HomeSearchResultRouteProp = RouteProp<
RootStackParamList,
'HomeSearchResult'>;

const route = useRoute<HomeSearchResultRouteProp>();

const {searchText} = route.params;

Actually this is mycode. If this is problem, could you tell me the problem? @satya164

**Comment by satya164** [comment]
https://reactnavigation.org/docs/typescript/#annotating-useroute

**Comment by jihokim2** [comment]
My code like this.
type RootStackParamList = {
Home: undefined;
HomeTextInput: undefined;
HomeSearchResult: {searchText: string};
};
type HomeSearchResultRouteProp = RouteProp<
RootStackParamList,
'HomeSearchResult'>;

const route = useRoute<**HomeSearchResultRouteProp**>();

const {searchText} = route.params;

I know your favor. But I tried many times like this. So I think it's bug. If it's not bug I will find a way to solve the problem. Thank you @satya164
