### ISSUE TITLE
[RN5] Apps has stopped constantly around 2 min while navigate to another nested routes

### ISSUE THREAD

**Issue by zxccvvv** [react-navigation/react-navigation#8509]
**Current Behavior**

I have these routes config:
Stack Navigator:
  - Home (Tab Navigator)
    * Home
    * QR
    * Profile
  - NestedHome (Stack)
    - Report

when i'm on Home, and navigate to Report screen, the Apps stopped around 2 min after staying at Report Screen,

Here a piece log from `Monitor` SDK:

First time on Report screen [time 16:07:29.113]:
```
06-25 16:07:29.113: E/unknown:NativeViewHierarchyManager(9465): Unable to update properties for view tag 1055
06-25 16:07:29.113: E/unknown:NativeViewHierarchyManager(9465): com.facebook.react.uimanager.IllegalViewOperationException: ViewManager for tag 1055 could not be found.
```
stopped [16:08:54.063]:
```
>06-25 16:08:54.063: E/AndroidRuntime(9465): FATAL EXCEPTION: FrescoDecodeExecutor-2
06-25 16:08:54.063: E/AndroidRuntime(9465): Process: com.smsfriendship, PID: 9465
06-25 16:08:54.063: E/AndroidRuntime(9465): java.lang.OutOfMemoryError: Failed to allocate a 1876016 byte allocation with 1396736 free bytes and 1364KB until OOM
```

Full Log:
[log.txt](https://github.com/react-navigation/react-navigation/files/4830233/log.txt)

**Expected Behavior**

No more OOM Error :)

**How to reproduce**

- You must provide a way to reproduce the problem. If you are having an issue with your machine or build tools, the issue belongs on another repository as that is outside of the scope of React Navigation.
- Either re-create the bug on [Snack](https://snack.expo.io) or link to a GitHub repository with code that reproduces the bug.
- Explain how to run the example app and any steps that we need to take to reproduce the issue from the example app.
- Keep the repro code as simple as possible, with the minimum amount of code required to repro the issue.
- Before reporting an issue, make sure you are on latest version of the package.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Android [Nox Emulator Android Version 7.1.2]
| @react-navigation/native       | ^5.5.1
| react-native                   | 0.62.2
| expo                           | None
| node                           | v10.19.0
| npm or yarn                    | 6.13.4

**Comment by satya164** [comment]
Closing since you didn't provide a repro. Feel free to open a new issue if you have a repro.
