### ISSUE TITLE
Header stretches when user gets out from TextInput

### ISSUE THREAD

**Issue by lucianoacsilva** [react-navigation/react-navigation#8510]
**Current Behavior**

Hello,

When I enter and exit a TextInput component, the header of the screen stretches.

![image](https://user-images.githubusercontent.com/23501838/85724841-fa776880-b6ca-11ea-98d1-876af2d8255b.png)

![image](https://user-images.githubusercontent.com/23501838/85724893-03683a00-b6cb-11ea-8174-7848408e779d.png)

**Code of the header in navigator:**

```
                  <MainStack.Navigator
			initialRouteName="PrologueScreen"
			screenOptions={{
				headerStyle: {
					backgroundColor: '#02AF10',
				},
				headerTitleAlign: 'center',
				headerTintColor: appColors.BEIGE,
				headerTitleStyle: {
					fontFamily: 'Graphik-Light',
				}
			}}
		>
```

**Code of the TextInput:**

```
                    <TextInput
                        style = {styles.emailInput}
                        value = {email}
                        onChangeText = {setEmail}
                        autoCapitalize = "none"
                        >  
                    </TextInput>
```

**Expected Behavior**

- The header should not stretch

**How to reproduce**

- You must provide a way to reproduce the problem. If you are having an issue with your machine or build tools, the issue belongs on another repository as that is outside of the scope of React Navigation.
- Either re-create the bug on [Snack](https://snack.expo.io) or link to a GitHub repository with code that reproduces the bug.
- Explain how to run the example app and any steps that we need to take to reproduce the issue from the example app.
- Keep the repro code as simple as possible, with the minimum amount of code required to repro the issue.
- Before reporting an issue, make sure you are on latest version of the package.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |
| @react-navigation/native       | ^5.0.9
| @react-navigation/stack        | ^5.0.1
| react-navigation   | ^4.2.2
| react-native-gesture-handler   |
| react-native-safe-area-context |
| react-native-screens           |
| react-native                   | "https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz"
| expo                           | ~36.0.0
| node                           |
| npm or yarn                    |

**Comment by gdamith** [comment]
yeap facing the same issue any is able to find out a workaround ?

**Comment by lucianoacsilva** [comment]
One more detail I've forgotten:

The header only stretches if there is some content that the keyboard overlays when user enter the TextInput component. Don't know if it interfeers somehow.

**Comment by lucianoacsilva** [comment]
@raajnadar , I've made a repro in snack here (please, ignore the dummy styles, did not focused on a beautiful design):

[https://snack.expo.io/@lucsilvacharmander892/header-with-textinput?platform=android&name=header%20title&dependencies=%40react-native-community%2Fmasked-view%40%5E0.1.7%2C%40react-navigation%2Fbottom-tabs%40%5E5.6.0%2C%40react-navigation%2Fdrawer%40%5E5.8.3%2C%40react-navigation%2Fmaterial-bottom-tabs%40%5E5.2.11%2C%40react-navigation%2Fmaterial-top-tabs%40%5E5.2.11%2C%40react-navigation%2Fnative%40%5E5.6.0%2C%40react-navigation%2Fstack%40%5E5.6.1%2Creact-native-paper%40%5E3.10.1%2Creact-native-reanimated%40%5E1.7.0%2Creact-native-safe-area-context%40%5E0.7.3%2Creact-native-screens%40%5E2.4.0%2Creact-native-tab-view%40%5E2.14.0&sourceUrl=https%3A%2F%2Freactnavigation.org%2Fexamples%2F5.x%2Fbasic-header-config.js](url)

Surprisingly, this isolated repro works normaly. However, inside my project, that weird bug appears.

**Comment by lucianoacsilva** [comment]
One more detail, I also use a tab navigator nested inside my stack navigator.

**Comment by lucianoacsilva** [comment]
@github-actions

> The versions mentioned in the issue for the following packages differ from the latest versions on npm:
> 
>     * `@react-navigation/native` (found: `5.0.9`, latest: `5.6.0`)
> 
>     * `@react-navigation/stack` (found: `5.0.1`, latest: `5.6.1`)
> 
> 
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?

Yes, the issue still persists after the packages updates.

**Comment by xXstekkaXx** [comment]
up

**Comment by satya164** [comment]
Please upgrade to latest Expo SDK. You're using a very old version.

**Comment by gdamith** [comment]
@satya164 I don't think related to the Expo SDK. I'm working on the vanilla react native I'm also getting this error.

**Comment by satya164** [comment]
are you on latest version of react-native-safe-area-context?

**Comment by gdamith** [comment]
@satya164 I was updated react-native-safe-area-context V 2.0 to latest version issue has been resolved. thank you for you response.

**Comment by lucianoacsilva** [comment]
@satya164 , updated here to version 2.0.3 of react-native-safe-area-context. However, it now returns the following error: 

`
requireNativeComponent: "RNCSafeAreaProvider" was not found in the UIManager.
`
