### ISSUE TITLE
Scrollview horizontal won't work in Top Tab Navigator

### ISSUE THREAD

**Issue by kimkong88** [react-navigation/react-navigation#8513]
**Current Behavior**

- Swipe horizontal does not work on ScrollView with Top Tab Navigator

**Expected Behavior**

- Swipe horizontal should work on ScrollView with Top Tab Navigator

**How to reproduce**

```
const Tab = createMaterialTopTabNavigator();

export class TopTab extends React.Component {
render() {
    return (
        <Tab.Navigator
            swipeEnabled={false}
            tabBar={(props) => <CustomTabBar {...props} />}
        >
            <Tab.Screen name="First" component={FirstView} />
            <Tab.Screen name="Second" component={SecondView} />
            <Tab.Screen name="Third" component={ThirdView} />
        </Tab.Navigator>
    );
}

export class FirstView extends React.Component {
render() {
    return (
        <ScrollView horizontal>
        .... contents
        </ScrollView>
    );
}
```

then ScrollView horizontal swipe won't work within these Views.

what I've tried:

swipeEnabled=true

nestedScrollViewEnabled=true

Is there any known solution to this?

I've tried pager option to customize ViewPaging with react-native-community/viewpager, still no luck.

Please help!

**Your Environment**

| software                            | version |
| ----------------------------------- | ------- |
| iOS or Android                      | Both
| @react-navigation/native            | ^5.5.1
| @react-navigation/material-top-tabs | ^5.2.10
| react-native-tab-view               | ^2.14.4
| react-native                        | https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz
| expo                                | ^37.0.0
| node                                | v12.7
| npm or yarn                         | npm

**Comment by kimkong88** [comment]
Wow feeling so dumb.
Short after, I found out my problem was having ScrollView inside TouchableWithoutFeedback. closing

**Comment by xAmad** [comment]
No but really horizontal scrollview was working perfectly until I nested it inside a TopBarNavigator. It stopped working. 

Help Please !

**Comment by aleena-adnan1** [comment]
why this issue is closed ?

**Comment by mdriazuddin417** [comment]
I resolve this problem. You should add this line swipeEnabled: false, in child tab
for example 
<Tab.Navigator
        screenOptions={{
          tabBarStyle: {
            backgroundColor: COLORS.white,
            elevation: 0,
            borderBottomWidth: moderateVerticalScale(1),
            borderBottomColor: '#4F4F4F2B',
          },

          tabBarIndicatorStyle: {
            backgroundColor: COLORS.primary,
            height: moderateVerticalScale(2),
            borderRadius: moderateScale(5),
          },
          tabBarLabelStyle: {
            fontSize: scale(16),
            textTransform: 'capitalize',
            fontWeight: 'bold',
          },
          tabBarActiveTintColor: COLORS.primary,
          tabBarInactiveTintColor: COLORS.black,
        }}>
        <Tab.Screen
          name="Storage"
          component={Storage}
          options={{
            title: 'Documents',
            swipeEnabled: false,
          }}
        />
        <Tab.Screen
          name="MyHealthPage"
          component={MyHealthPage}
          options={{
            title: 'My Health',
            swipeEnabled: false,
          }}
        />
      </Tab.Navigator>
