### ISSUE TITLE
Unable to resolve module `./useDevTools`

### ISSUE THREAD

**Issue by AlexSmirnov9107** [react-navigation/react-navigation#8514]
**Current Behavior**

![image](https://user-images.githubusercontent.com/32673518/85830516-8dd59a00-b7ae-11ea-91f3-ca69ea3cd031.png)

```
    "react": "16.11.0",
    "react-native": "0.62.2",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-navigation/drawer": "^5.8.4",
    "@react-navigation/native": "^5.6.1",
    "@react-navigation/stack": "^5.6.2",
    "react-native-screens": "^2.9.0",


```

**Comment by raajnadar** [comment]
Try clearing the metro cache `npx react-native run-android --reset-cache` or `expo start -c`

**Comment by AlexSmirnov9107** [comment]
@raajnadar thanks, its works

**Comment by sushrut-desora** [comment]
When I try running ```npx react-native run-android --reset-cache``` it says "error: unknown option `--reset-cache'". I also tried running "npm start --reset-cache" but that didn't work either.
You need to run ```npx react-native start --reset-cache``` to clear the cache. You will get an output saying "warning: the transform cache was reset." if the cache was reset successfully.
