### ISSUE TITLE
Tab Bar Scroll Performance

### ISSUE THREAD

**Issue by govinda744** [react-navigation/react-navigation#8516]
**Current Behavior**

- What code are you running and what is happening?
```
import { createMaterialTopTabNavigator } from "@react-navigation/material-top-tabs";

const TopTab = createMaterialTopTabNavigator();

const TabScreen = () => {
  return (
    <View style={styles.container}>
      <Text>A</Text>
    </View>
  );
};

const TopBar = () => {
  return (
    <TopTab.Navigator
      lazy={true}
      lazyPreloadDistance={2}
      lazyPlaceholder={() => <Text>Loading</Text>}
      tabBarOptions={{
        scrollEnabled: true,
        indicatorStyle: { backgroundColor: "black" },
        tabStyle: { width: 100 },
      }}
    >
      <TopTab.Screen key="A" name="A" component={TabScreen} />
      <TopTab.Screen key="B" name="B" component={TabScreen} />
      <TopTab.Screen key="C" name="C" component={TabScreen} />
      <TopTab.Screen key="D" name="D" component={TabScreen} />
      <TopTab.Screen key="E" name="E" component={TabScreen} />
      <TopTab.Screen key="F" name="F" component={TabScreen} />
      <TopTab.Screen key="G" name="G" component={TabScreen} />
      <TopTab.Screen key="H" name="H" component={TabScreen} />
      <TopTab.Screen key="I" name="I" component={TabScreen} />
      <TopTab.Screen key="J" name="J" component={TabScreen} />
      <TopTab.Screen key="K" name="K" component={TabScreen} />
      <TopTab.Screen key="L" name="L" component={TabScreen} />
      <TopTab.Screen key="M" name="M" component={TabScreen} />
      <TopTab.Screen key="N" name="N" component={TabScreen} />
      <TopTab.Screen key="O" name="O" component={TabScreen} />
      <TopTab.Screen key="P" name="P" component={TabScreen} />
      <TopTab.Screen key="Q" name="Q" component={TabScreen} />
    </TopTab.Navigator>
  );
};
```
![](https://media.giphy.com/media/IhgKDWQqXjBYt59TnE/giphy.gif)

**Expected Behavior**

- What do you expect should be happening?
![](https://media.giphy.com/media/Ws4l6ApJMtbLR31VFk/giphy.gif)

**How to reproduce**
`expo init`
`yarn add @react-navigation/native @react-navigation/material-top-tabs react-native-tab-view `

**Your Environment**

| software                            | version |
| ----------------------------------- | ------- |
|  Android                      |9
| @react-navigation/native            |^5.6.0
| @react-navigation/material-top-tabs |^5.2.12
| react-native-tab-view               |^2.14.4
| react-native                        |37.0.1
| expo                                |3.21.10
| node                                |12.17.0
| yarn                         |1.22.4

**Comment by govinda744** [comment]
> The versions mentioned in the issue for the following packages differ from the latest versions on npm:
> 
> * `@react-navigation/native` (found: `5.6.0`, latest: `5.6.1`)
> 
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?

It exists even after upgrading to the latest version.

**Comment by diego3799** [comment]
I have the same issue, when having more than 3 tabs and setting the initialRouteName to one of the middle, it renders 1/3 of the View and then it renders it completely. Idk why this is happening,  the views just have a Text

**Comment by Muugen** [comment]
hi did you guys find a solution for this because i'm having the same issues
