### ISSUE TITLE
 WARN Looks like you're passing an inline function for 'component' prop for the screen 'Home' (e.g. component={() => <SomeComponent />}). Passing an inline function will cause the component state to be lost on re-render and cause perf issues since it's re-created every render. You can pass the function as children to 'Screen' instead to achieve the desired behaviour.

### ISSUE THREAD

**Issue by rodolfocassorillo** [react-navigation/react-navigation#8517]
I'm doing a Dynamic Drawer Navigator with React Navigation 5, and this warning appears:

WARN Looks like you're passing an inline function for 'component' prop for the screen 'Home' (e.g. component={() => }). Passing an inline function will cause the component state to be lost on re-render and cause perf issues since it's re-created every render. You can pass the function as children to 'Screen' instead to achieve the desired behaviour.

The problem is when I try to map() my Screens in the Drawer.Screen.

I tried a lot of things, but doesn't work, my Route Stack Itens:

```
`import React from 'react';
import Home from '../screens/home/Index';
import ATR from '../screens/atr/Index';

const stackNavigItens = [
  {
    group: 'Home',
    name: 'Home',
    component: Home,
    icon: 'home',
    iconType: 'FontAwesome',
    label: 'Principal',
    hideMenu: false,
    screenComponent: props => {
      return <Home {...props} />;
    },
  },`

```
Then my Screens:

```
`import React from 'react';
import Icon from 'react-native-vector-icons/Ionicons';
import {DrawerContent} from './DrawerContent';
import {AppStyles, IconStyles} from '../utils/AppStyle';
import {stackNavigItens} from './Routes';
import {createStackNavigator} from '@react-navigation/stack';
import {createDrawerNavigator} from '@react-navigation/drawer';

class DrawerScreens extends React.Component {
  constructor(props) {
    super(props);

    this.state = {
      data: stackNavigItens,
    };
  }

  render() {
    const {data} = this.state;
    const Drawer = createDrawerNavigator();
    const Stack = createStackNavigator();

    const screenOptions = {
      headerStyle: {
        backgroundColor: AppStyles.color.main,
      },
      headerTintColor: AppStyles.color.headerTintColor,
      headerTitleStyle: {
        fontWeight: 'bold',
      },
    };

    return (
      <Drawer.Navigator drawerContent={props => <DrawerContent {...props} />}>
        {data.map(r => {
          return (
            <Drawer.Screen
              key={r.name}
              name={r.name}
              component={({navigation}) => (
                <Stack.Navigator
                  initialRouteName="Home"
                  headerMode="screen"
                  screenOptions={screenOptions}>
                  <Stack.Screen
                    name={r.name}
                    component={r.component}
                    options={{
                      title: r.label,
                      headerLeft: () => (
                        <Icon.Button
                          name="ios-menu"
                          size={IconStyles.size}
                          backgroundColor={AppStyles.color.main}
                          onPress={() => {
                            navigation.openDrawer();
                          }}
                        />
                      ),
                    }}
                    {...this.props}
                  />
                </Stack.Navigator>
              )}
              {...this.props}
            />
          );
        })}
      </Drawer.Navigator>
    );
  }
}

export default DrawerScreens;`
```

Someone can help me ?

System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
    Memory: 8.37 GB / 15.94 GB
  Binaries:
    Node: 10.18.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.19.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
  SDKs:
    Android SDK:
      API Levels: 19, 22, 26, 27, 28, 29
      Build Tools: 28.0.3, 29.0.0, 29.0.2
      System Images: android-19 | Intel x86 Atom, android-19 | Google APIs Intel x86 Atom, android-22 | Google APIs Intel x86 Atom, android-22 | Google APIs Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6514223
  npmPackages:
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2

**Comment by satya164** [comment]
Name the property something other than "component", like "screen" or whatever.

**Comment by satya164** [comment]
Please read the error message.

**Comment by louiechristie** [comment]
This worked for me, from the documentation:

Use a render callback for the screen instead of specifying a component prop:

```
<Stack.Screen name="Home">
  {props => <HomeScreen {...props} extraData={someData} />}
</Stack.Screen>
```

See https://reactnavigation.org/docs/hello-react-navigation/#passing-additional-props

**Comment by SrBrahma** [comment]
> This worked for me, from the documentation:
> 
> Use a render callback for the screen instead of specifying a component prop:
> 
> ```
> <Stack.Screen name="Home">
>   {props => <HomeScreen {...props} extraData={someData} />}
> </Stack.Screen>
> ```
> 
> See https://reactnavigation.org/docs/hello-react-navigation/#passing-additional-props

Sorry for commenting on an old issue, but, would that render callback also cause performance issues?

**Comment by rajan-keypress** [comment]
<Stack.Screen name="Home">
  {props => <HomeScreen {...props} extraData={someData} />}
</Stack.Screen>
 work for me

**Comment by yafta** [comment]
> 

Ty <3

**Comment by fukemy** [comment]
![Screen Shot 2022-05-30 at 15 40 43](https://user-images.githubusercontent.com/8202437/170953332-7f062f87-59a5-4a57-b636-430359d3d6c6.png)
i got error:
***Got an invalid value for 'children' prop for the screen 'Recently'. It must be a function returning a React Element.*** please helppp

**Comment by gavrilikhin-d** [comment]
> ![Screen Shot 2022-05-30 at 15 40 43](https://user-images.githubusercontent.com/8202437/170953332-7f062f87-59a5-4a57-b636-430359d3d6c6.png) i got error: _**Got an invalid value for 'children' prop for the screen 'Recently'. It must be a function returning a React Element.**_ please helppp

Same issue on react-native-web. Everything works perfectly in RN

**Comment by CoolPerson879** [comment]
didn't work for me
