### ISSUE TITLE
Disable swipe back action in Bottom Tab Navigator (react-navigation-v5)

### ISSUE THREAD

**Issue by vish2595** [react-navigation/react-navigation#8520]
I am not unable to disable back swipe on my bottom tab navigator screen.
**Your Environment**

| software                      | version |
| ----------------------------- | ------- |
| iOS or Android                |
| @react-navigation/bottom-tabs | 5.2.6
| react-native-screens          | 2.4.0
| react-native                  | 0.61.4
| node                          |
| npm or yarn                   |

**Comment by vish2595** [comment]
Did you solve it ? @raajnadar

**Comment by raajnadar** [comment]
The back swipe works properly.

**Comment by vish2595** [comment]
No i want to disable back swipe. How can i ? @raajnadar

**Comment by raajnadar** [comment]
You can do this use https://reactnavigation.org/docs/material-top-tab-navigator

Set its position to bottom with this prop https://reactnavigation.org/docs/material-top-tab-navigator#tabbarposition and set awipe enable to false https://reactnavigation.org/docs/material-top-tab-navigator#swipeenabled

**Comment by jonathans199** [comment]
Found this interesting, might help resolve it 
https://reactnavigation.org/docs/preventing-going-back/

Have not able test it on my project yet.

**Comment by sayancitytech** [comment]
you can use backBehavior='none'
