### ISSUE TITLE
 TypeError: undefined is not an object (evaluating '_reactNative.Linking.addEventListener')] Expo android

### ISSUE THREAD

**Issue by ahmedshmokbel** [react-navigation/react-navigation#8521]
I suddenly found this error in Android only and I am using Expo , the error is located NavigationContainer I tried the screens separately without the react navigation they are working fine ,"I am using latest update from React Navigation" ,please help
![Screenshot_20200629-132445_Expo](https://user-images.githubusercontent.com/63881736/86000695-2b7ad480-ba0e-11ea-960a-ff08721b6d0d.jpg)

**Comment by ahmedshmokbel** [comment]
"@react-navigation/native": "^5.6.1",

**Comment by Hypermona** [comment]
when I am using an older version of navigation I got the same error

**Comment by satya164** [comment]
Closing since you didn't provide a repro. Feel free to open a new issue if you have a repro.

**Comment by Shafiulmizbah2** [comment]
Did you solve the issue ? I am facing the same issue!
