### ISSUE TITLE
How to change header title & background colour based on bottom tab bar colour & title?

### ISSUE THREAD

**Issue by Anisha961** [react-navigation/react-navigation#8522]
My each bottomNavigation has different background colour & title. How can I change my header background colour & title name based on bottom tab bar navigation colour ? I am attaching my code with some images.

![Simulator Screen Shot - iPhone 11 - 2020-06-29 at 19 19 11](https://user-images.githubusercontent.com/67403954/86016468-6bf34600-ba40-11ea-8a29-7c695987063b.png)

![Simulator Screen Shot - iPhone 11 - 2020-06-29 at 18 54 26](https://user-images.githubusercontent.com/67403954/86016535-83323380-ba40-11ea-8f31-d47ce9ca65b4.png)

`

    const NavManager = createMaterialBottomTabNavigator({

    
    Home: {
        screen: home,

        navigationOptions: {
            tabBarLabel: 'Home',
            title: "Home",
            tabBarIcon: ({ tintColor }) => (
                <View>
                    <Icon name="ios-home" color={tintColor} size={25} />
                </View>
            ),

            activeColor: '#f0edf6',
            inactiveColor: '#3e2465',
            barStyle: { backgroundColor: '#009999' },

        }
    },

       Covid: {
        screen: India,

        navigationOptions: {
            tabBarLabel: 'Covid',
            tabBarIcon: ({ tintColor }) => (
                <View>
                    <Icon name="ios-stats" color={tintColor} size={25} />
                </View>
            ),

            activeColor: '#f0edf6',
            inactiveColor: '#3e2465',
            barStyle: { backgroundColor: '#66ccff' },

        }
    },

        {
        initialRouteName: 'Home'
        }

    );

    const AppNavigator = createStackNavigator({
    Meals:{
        screen: NavManager,
        navigationOptions:{
            title: 'News',
            
     
        },
       

    },
    
    })

    export default createAppContainer(AppNavigator);`

**Comment by Anisha961** [comment]
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "@react-native-community/masked-view": "^0.1.10",
    "axios": "^0.19.2",
    "expo": "~38.0.1",
    "expo-status-bar": "^1.0.0",
    "react": "~16.11.0",
    "react-dom": "~16.11.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-38.0.0.tar.gz",
    "react-native-elements": "^2.0.4",
    "react-native-flags-kit": "^1.0.1",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-paper": "^3.10.1",
    "react-native-reanimated": "^1.9.0",
    "react-native-screens": "^2.9.0",
    "react-native-vector-icons": "^6.6.0",
    "react-native-web": "~0.11.7",
    "react-navigation": "^4.4.0",
    "react-navigation-material-bottom-tabs": "^2.3.0",
    "react-navigation-stack": "^2.8.2"
  },
  "devDependencies": {
    "@babel/core": "^7.8.6",
    "babel-preset-expo": "~8.1.0"
  },
  "private": true
}

**Comment by rapric2115** [comment]
You can use `headerStyle: { }` to set the  backgroundColor, you can also use the header and pass a function to make the change in the background. `header: ({ navigation, route, options }) => { if(route === 'Home'){ headerStyle: { backgroundColor: '#color you want' }} else {} }` didn't tried it but you can play with it.
