### ISSUE TITLE
[Web] path value with "/" will be escaped in URL

### ISSUE THREAD

**Issue by Albert-Gao** [react-navigation/react-navigation#8523]
packages (with expo v38 managed flow):

```json
{
    "@react-navigation/bottom-tabs": "^5.6.1",
    "@react-navigation/drawer": "^5.8.4",
    "@react-navigation/native": "^5.6.1",
    "@react-navigation/stack": "^5.6.2",
}
```

I have a path config like this:

```javascript
const PATHS = {
    CREATE_TASK = 'task/new'
}

<Screen name={PATHS.CREATE_TASK} path={PATHS.CREATE_TASK}>
```

in the browser, the navigation works fine, but the URL seems odd: `task%2Fnew`

I initially have a `%2Ftask%2Fnew` problem, mitigated it by removing the 1st slash, but the second is always there no matter what, and the [documentation](https://reactnavigation.org/docs/configuring-links) does not have an example for this case.

How to have a clean URL on the web like `task/new`?

Thanks

**Comment by satya164** [comment]
There's no `path` prop on screens. Please follow the documentation and provide a valid `linking` config.

**Comment by Albert-Gao** [comment]
My bad, not path, I am using:

```javascript
import * as Linking from 'expo-linking'
const prefix = Linking.makeUrl('/')

<NavigationContainer linking={{
  prefixes: [prefix],
  config: {
      [PATHS.CREATE_TASK]: PATHS.CREATE_TASK
  }
}}>
    <Screen
        name={PATHS.CREATE_TASK}
        component={Component}
    />
</NavigationContainer
```

**Comment by Albert-Gao** [comment]
I updated the original post with the updated code as well

**Comment by Albert-Gao** [comment]
It is a modal stack navigator, i will try creating a snack example to re-produce it

**Comment by satya164** [comment]
That's not valid code. You need to provide a proper runnable repro to debug the issue.

**Comment by Albert-Gao** [comment]
Sorry for the trouble, false alarm, after creating the minimal example, I found the `PATHS.CREATE_TASK` is not included in the `config.screens`
