### ISSUE TITLE
import getFocusedRouteNameFromRoute from @react-navigation/native not found

### ISSUE THREAD

**Issue by marggi-s** [react-navigation/react-navigation#8527]
**Current Behavior**

- What code are you running and what is happening?

I need to get route name from route, If I refer to the documentation '[Screen options with nested navigators](https://reactnavigation.org/docs/screen-options-resolution)', I must add these lines in any file: 

```import { getFocusedRouteNameFromRoute } from '@react-navigation/native';
function getHeaderTitle(route) {
  // If the focused route is not found, we need to assume it's the initial screen
  // This can happen during if there hasn't been any navigation inside the screen
  // In our case, it's "Feed" as that's the first screen inside the navigator
  const routeName = getFocusedRouteNameFromRoute(route) ?? 'Feed';

  switch (routeName) {
    case 'Feed':
      return 'News feed';
    case 'Profile':
      return 'My profile';
    case 'Account':
      return 'My account';
  }
}
```
Unfortunately the function 'getFocusedRouteNameFromRoute' is not resolved.
To make it work I add to install ```@react-navigation/core``` and replace
```import { getFocusedRouteNameFromRoute } from '@react-navigation/native';```
by
```import { getFocusedRouteNameFromRoute } from '@react-navigation/core';```

Why because the function his in the dependencies of this package and not in the module src.

**Expected Behavior**

- What do you expect should be happening?
```import { getFocusedRouteNameFromRoute } from '@react-navigation/native';``` to work.

*** Personal note***

- Should updated documentation.
OR
- Add 'getFocusedRouteNameFromRoute' in @react-navigation/native and not in his dependencies.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |
| @react-navigation/native       |
| react-native                   |
| expo                           |
| node                           |
| npm or yarn                    |

**Comment by satya164** [comment]
Just update your versions before opening issues, please.

**Comment by marggi-s** [comment]
@satya164 Issue updated.

**Comment by satya164** [comment]
If it doesn't work for you with latest version, you need to clear the cache https://reactnavigation.org/docs/troubleshooting/#stale-cache-of-metro-bundler

**Comment by marggi-s** [comment]
Already clean cache, rm node-modules but still when I add the line 
```import { getFocusedRouteNameFromRoute } from '@react-navigation/native';``` is not found.
To make it work I just changed the line with:
```import { getFocusedRouteNameFromRoute } from '@react-navigation/core';```

**Comment by nonameolsson** [comment]
Happened to me as well. `getFocusedRouteNameFromRoute` doesn't exist in `@react-navigation/native` but in `@react-navigation/core`. 

Maybe the official documentation should be updated?

**Comment by nonameolsson** [comment]
@satya164 What do you think of this? As I understand it, this helper function isn't available.
