### ISSUE TITLE
False notch auto detect on "hideable" android menu. Bottom tab bar has like double size in height.

### ISSUE THREAD

**Issue by Meinl** [react-navigation/react-navigation#8529]
**Current Behavior**

Default example for bottom tab navigator

`<NavigationContainer>
      <Tab.Navigator
        initialRouteName="Feed"
        tabBarOptions={{
          activeTintColor: '#e91e63',
        }}
      >
        <Tab.Screen
          name="Feed"
          component={Feed}
          options={{
            tabBarLabel: 'Home',
            tabBarIcon: ({ color, size }) => (
              <MaterialCommunityIcons name="home" color={color} size={size} />
            ),
          }}
        />
        <Tab.Screen
          name="Notifications"
          component={Feed}
          options={{
            tabBarLabel: 'Updates',
            tabBarIcon: ({ color, size }) => (
              <MaterialCommunityIcons name="bell" color={color} size={size} />
            ),
          }}
        />
        <Tab.Screen
          name="Profile"
          component={Feed}
          options={{
            tabBarLabel: 'Profile',
            tabBarIcon: ({ color, size }) => (
              <MaterialCommunityIcons name="account" color={color} size={size} />
            ),
          }}
        />
      </Tab.Navigator>
    </NavigationContainer>`

This code was for testing purpose, in a blank new Expo project.

It render a navigation tab bar like twice in height, assuming a notch or something. It's render OK on iPhone (with notch, like XS), but the "issue" is in Android.

![Screenshot_20200701-100724465](https://user-images.githubusercontent.com/8104557/86254507-e2e52780-bb83-11ea-8300-cf8e946e1641.jpg)

If I set a safeAreaInset prop, works fine on Android, but break on iOS.

TESTED ON ASUS ZENFONE 5

**Expected Behavior**

Render normally, like previous version I guess. I have no problem with previous compilations.

**How to reproduce**

Just run the example code pusblish in https://reactnavigation.org/docs/bottom-tab-navigator/

**Your Environment**

| software                      | version |
| ----------------------------- | ------- |
| iOS or Android                | Android
| @react-navigation/native      |  "^5.6.1"
| @react-navigation/bottom-tabs | "^5.6.1"
| react-native-screens          | "~2.9.0"
| react-native                  |  https://github.com/expo/react-native/archive/sdk-38.0.1.tar.gz 
| expo                          | "~38.0.8"
| node                          | v12.9.0
| npm or yarn                   |  1.17.3

**Comment by Meinl** [comment]
Hi, thanks for response. I've tried with snack and work fine, but just because the emulator hasn't the option to hide android's native navigation bar. That's why I've said, this is happening, at least on my phone (Asus Zenfone 5), and pretty sure in other that have that choice. In previous versions worked fine, that's mean, the bottom tab navigator goes up and down whit navigation bar, isn't static like now with double height. I'm attaching a gif, the code is exactly the same and was taken of example of react navigation tabs (copy paste) from here: https://reactnavigation.org/docs/bottom-tab-navigator last snack example link.

![20200708_130742](https://user-images.githubusercontent.com/8104557/86949485-b483c100-c11c-11ea-9ccf-08294225a04d.gif)

**Comment by satya164** [comment]
Please open an issue in https://github.com/th3rdwave/react-native-safe-area-context about it
