### ISSUE TITLE
Disable all Gestures on release APP

### ISSUE THREAD

**Issue by SalvatoreAD** [react-navigation/react-navigation#8532]
**Current Behavior**

I can't turn off gestures.

`const defaultScreenOptions = {
  gestureEnabled: false,
  headerShown: false,
  gestureDirection: "horizontal-inverted",
  gestureResponseDistance: 0,
  mode: 'modal',
  ...TransitionPresets.DefaultTransition
};`

**Expected Behavior**

I would like to disable all gestures on the whole stack

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Android
| @react-navigation/native       | "5.6.1"
| @react-navigation/stack        | "5.6.2"
| react-native-gesture-handler   | "~1.6.0"
| react-native-safe-area-context | "^2.0.2"
| react-native-screens           | "~2.2.0"
| react-native                   | "0.62.2"
| expo                           | "~37.0.3"
| node                           | v12.18.0
| npm or yarn                    | yarn 1.19.2

**Comment by SalvatoreAD** [comment]
I have last version of libraries

**Comment by SalvatoreAD** [comment]
It is not possible to create e repro. It occurs when the releaase apk is created

**Comment by satya164** [comment]
> It is not possible to create e repro. It occurs when the release apk is created
And why can't I create the release apk from your repro?

**Comment by SalvatoreAD** [comment]
I know, but I can't give you an apk with this problem. I solved it by 
switching to another system.

In data 8 luglio 2020 13:34:22 Satyajit Sahoo <notifications@github.com> ha 
scritto:
