### ISSUE TITLE
Invalid hook call

### ISSUE THREAD

**Issue by maystrenkoYurii** [react-navigation/react-navigation#8535]
version @react-navigation/native 5.6.1
<img width="789" alt="Снимок экрана 2020-07-02 в 16 07 58" src="https://user-images.githubusercontent.com/23016311/86362665-4d7a8e00-bc7e-11ea-95fe-6c9e6dd5f041.png">
<img width="863" alt="Снимок экрана 2020-07-02 в 16 08 10" src="https://user-images.githubusercontent.com/23016311/86362671-4fdce800-bc7e-11ea-9f47-85219b5396e2.png">

**Comment by satya164** [comment]
`headerLeft: props => <BackButton {...props} />`
