### ISSUE TITLE
get bottom tabs current height

### ISSUE THREAD

**Issue by maystrenkoYurii** [react-navigation/react-navigation#8536]
good solution get bottom tabs current height hook 'useBottomTabHeight' => { height: 50, safeHeight: 30, fullHeight: 80  }

**Comment by marhaupe** [comment]
See #8037

**Comment by akinncar** [comment]
@marhaupe don't you think it's feasible to create a hook? just with this example it was not clear to me how to use it, (i'm using createBottomTabNavigator) and I believe this hook will also be useful for other people
