### ISSUE TITLE
Couldn't find a navigation object. Is your component inside a screen in a navigator?

### ISSUE THREAD

**Issue by dekuvjs** [react-navigation/react-navigation#8538]
**Current Behavior**

- What code are you running and what is happening?
**app.js file**
```
import React from 'react';

import {
  SafeAreaView, StatusBar,
} from 'react-native';
import 'react-native-gesture-handler';
import { NavigationContainer } from '@react-navigation/native';
import LoginNavigator from './src/navigators/LoginNavigator';


const App = () => {
  return (
    <NavigationContainer>
      <StatusBar backgroundColor='#F79F83' />
      <LoginNavigator />
    </NavigationContainer>
  );
};

export default App;

```

**LoginNavigator.js file**
```
import React from 'react';
import { createStackNavigator } from '@react-navigation/stack';


import Login from '../views/Login/Login';
import Verification from '../views/Verification/Verification';

const LoginStack = createStackNavigator();


const LoginNavigator = () => {

    return (
        <LoginStack.Navigator headerMode='none'>
            <LoginStack.Screen name='Login' component={Login} />
            <LoginStack.Screen name='Verification' component={Verification} />
        </LoginStack.Navigator>)
}



export default LoginNavigator;
```

- Include a screenshot or video if it makes sense.

![Screenshot_1593800792](https://user-images.githubusercontent.com/36232710/86491710-79a71500-bd39-11ea-866f-33acb1b065ad.png)

**Expected Behavior**

- What do you expect should be happening?
- Include a screenshot or video if it makes sense.

**How to reproduce**

- You must provide a way to reproduce the problem. If you are having an issue with your machine or build tools, the issue belongs on another repository as that is outside of the scope of React Navigation.
- Either re-create the bug on [Snack](https://snack.expo.io) or link to a GitHub repository with code that reproduces the bug.
- Explain how to run the example app and any steps that we need to take to reproduce the issue from the example app.

just start a fresh react-native app and install all dependencies and follow the instructions guide and  that sit.

 
- Keep the repro code as simple as possible, with the minimum amount of code required to repro the issue.
- Before reporting an issue, make sure you are on latest version of the package.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |
| @react-native-community/masked-view |^0.1.10 
| @react-navigation/core | ^5.11.1
| @react-navigation/native       |^5.6.1
| @react-navigation/stack        |^5.6.2
| react-native-gesture-handler   |^1.6.1
| react-native-safe-area-context |^3.0.7
| react-native-reanimated | ^1.9.0
| react-native-screens           |^2.9.0
| react-native                   |0.62.2
| expo                           |
| node                           | v12.14.1
| npm or yarn                    | 6.13.4

**Comment by satya164** [comment]
Closing since you didn't provide a repro. Feel free to open a new issue if you have a repro.
