### ISSUE TITLE
custom header not working as expected

### ISSUE THREAD

**Issue by timurridjanovic** [react-navigation/react-navigation#8541]
I upgraded from react navigation 4 to react navigation 5. I have a custom header that was working fine with react navigation 4. However, with react navigation 5, it looks like the custom header is being duplicated across the stack, instead of being fixed for all the screens in the same stack.

**Current Behavior**
Here is the code I am running
```
const headerScreenOptions = props => {
  const { navigation } = props
  return {
    header: () => {
      return <NavBar navigation={navigation} />
    },
    headerTransparent: true,
  }
}
const CompagnonStack = createStackNavigator()
function CompagnonStackScreen () {
  return (
    <CompagnonStack.Navigator screenOptions={headerScreenOptions}>
      <CompagnonStack.Screen name="Compagnon" component={Compagnon} />
      <CompagnonStack.Screen name="Refuge" component={Refuge} />
      <CompagnonStack.Screen name="Social" component={Social} />
      <CompagnonStack.Screen name="UserProfile" component={UserProfile} />
    </CompagnonStack.Navigator>
  )
}
```

Video:
https://recordit.co/jwXmplFWJO

**Expected Behavior**
The header should be fixed accross the stack.
https://recordit.co/wVNyHGBPvK

**Your Environment**
iOS 13.2 iPhone 11
@react-navigation/native 5.6.1
@react-navigation/stack 5.6.2
react-native 0.61.4
react-native-screens 2.0.0-alpha.32
react-native-gesture-handler 1.6.1
(not using expo)
node 10.14.0

**Comment by raajnadar** [comment]
Try removing this `headerTransparent: true`

**Comment by timurridjanovic** [comment]
@raajnadar same problem.
https://recordit.co/srx24HSFsy

**Comment by raajnadar** [comment]
Provide a working [snack.expo.io](snack.expo.io) example

**Comment by timurridjanovic** [comment]
Here it is: https://snack.expo.io/trM_Z3PLA
You have to look at the example on ios and not web though. You'll see 2 overlapping Texts in the header if you click on "NAV BAR". If I add a backgroundColor it solves the issue, but I need the transparent background..

**Comment by satya164** [comment]
https://reactnavigation.org/docs/stack-navigator#header

**Comment by timurridjanovic** [comment]
@satya164 why did you close this? Your comment is not helpful at all.. headerMode doesnt solve the issue..

**Comment by timurridjanovic** [comment]
@satya164 @raajnadar It's a bit frustrating to have spent all this time to document the issue when someone can just blindly come here and close it without any justification..

**Comment by voold** [comment]
I have the same problem

**Comment by voold** [comment]
I've put headerMode to 'screen' instead of 'float' and it worked

**Comment by aforty** [comment]
I have the same problem. I had a custom header in v4 that remained static across all pages and I used navigation props to determine how to animate within it. Supposedly headerMode 'float' should allow for this but I cannot use any hooks within my Header because it violates the rules of hooks (more hooks being rendered on the second screen than the first).

**Comment by henrikland** [comment]
Currently using this workaround, i.e. only render the header for the current route:
```
<SomeStack.Navigator
  headerMode="float"
  screenOptions={{
    headerTransparent: true,
    header: ({ navigation, scene }: StackHeaderProps) => {
      const { routes, index } = navigation.dangerouslyGetState();
      const {
        route: { name: routeName },
      } = scene;

      if (routes[index].name !== routeName) {
        return null;
      }

      return <MyHeaderComponent />;
  }
  ...
>
```

**Comment by DjordjePetrovic** [comment]
This is still an issue, anyone found the solution ?

**Comment by satya164** [comment]
There's no problem. The API was changed in `react-navigation-stack` v2 in react navigation 4 to allow for easier usage and improved animations, and consistent API between different `headerMode` - it's working as documented.

You need to update your code to work with the new API. If you need examples then there's an example of custom animation in the docs https://reactnavigation.org/docs/stack-navigator/#set-headermode-to-float-for-custom-header-animations

If you really need a single header you can also achieve it with the [`layout` prop on navigator](https://reactnavigation.org/docs/navigator?config=dynamic#layout) in React Navigation 7.
