### ISSUE TITLE
headerMode='none' The previous page is retained, causing the previous page to appear at the bottom of the current page hierarchy

### ISSUE THREAD

**Issue by zhuSass** [react-navigation/react-navigation#8542]
"@react-native-community/async-storage": "^1.9.0",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-navigation/bottom-tabs": "^5.5.0",
    "@react-navigation/material-top-tabs": "^5.2.12",
    "@react-navigation/native": "5.6.1",
    "@react-navigation/stack": "^5.6.2",
    "react-native-gesture-handler": "^1.6.1",
```
import * as React from 'react';
import { 
    createStackNavigator,
  } from "@react-navigation/stack";
import { createMaterialTopTabNavigator } from '@react-navigation/material-top-tabs';
import { createBottomTabNavigator } from '@react-navigation/bottom-tabs';

import {tabBarIcon,} from '@/components/icon';
//*************************账户************************************//
import LoginScreen from '@/page/account/login'; // 登录
import LoginAuthScreen from '@/page/account/loginAuth'; // 登录状态验证
//*************************主界面************************************//
import HomeScreen from '@/page/main/home'; // 首页
import BibliothecaScreen from '@/page/main/bibliotheca'; // 书库
import FavoritesScreen from '@/page/main/favorites'; // 收藏夹
import MyCenterScreen from '@/page/main/myCenter'; // 个人中心
//*************************书库模块************************************//
import BookDetailsScreen from '@/page/bibliothecas/bookDetails'; // 小说主页
//*************************其它模块************************************//
import ReadingScreen from '@/page/other/reading'; // 阅读
import BookDirectoryScreen from '@/page/other/directory'; // 小说目录
import searchScreen from '@/page/other/search'; // 小说目录
import ShuYuanSdk,{
  AllShuYuanIdsKey,
} from '@/common/shuYuanSdk';

const Stack = createStackNavigator();
const Tab = createBottomTabNavigator();
const TopTab = createMaterialTopTabNavigator();

// 书库模块
function BibliothecaModel() {
  type listItemType = {
    label: string,
    name: string,
  }
  let list:listItemType[] = [];
  Object.keys(ShuYuanSdk.allShuYuanIds).forEach(key => {
    list.push({
        label: ShuYuanSdk.allShuYuanIds[key as AllShuYuanIdsKey].label,
        name: key,
    })
  });
  
  return (
    <TopTab.Navigator
      initialRouteName="快眼看书"
      tabBarOptions={{
        scrollEnabled: true,
        labelStyle: { fontSize: 17,},
        inactiveTintColor: '#7E7E7E',
        activeTintColor: '#484848',
        indicatorStyle: {backgroundColor: '#484848',},
        style: { 
          backgroundColor: '#fff',
          paddingTop: 16,
        },
        tabStyle: {
          width: 'auto',
          display: 'flex',
          flexDirection: 'row',
          justifyContent: 'center',
          alignItems: 'center',
        },
      }}
    >
      {list.map((item: listItemType, i:number) => {
        return <TopTab.Screen
                key={i}
                name={item.name}
                component={BibliothecaScreen}
                options={{ tabBarLabel: item.label,tabBarTestID: item.name, }}
              />
      })}
    </TopTab.Navigator>
  );
}
// 其它模块
function OtherModel() {
  return (
    <Stack.Navigator
      initialRouteName="Search"
      headerMode="none"
      screenOptions={{animationEnabled: false}}
    >
      {/* 文章详情 */}
      <Stack.Screen
        name="Reading"
        component={ReadingScreen}
        options={{
          title: '文章详情',
          gestureEnabled: true,
        }}
      />
      {/* 小说主页 */}
      <Stack.Screen
        name="BookDetails"
        component={BookDetailsScreen}
        options={{
          title: '小说主页',
        }}
      />
      {/* 小说目录 */}
      <Stack.Screen
        name="BookDirectory"
        component={BookDirectoryScreen}
        options={{
          title: '小说目录',
        }}
      />
      {/* 小说搜索 */}
      <Stack.Screen
        name="Search"
        component={searchScreen}
        options={{
          title: '小说搜索',
        }}
      />
    </Stack.Navigator>
  );
}
// 主界面
function AppStack() {
  return (
    <Tab.Navigator
      initialRouteName="Favorites"
      tabBarOptions={{
        activeTintColor: '#3F9CD6',
        inactiveTintColor: '#595959',
      }}
    >
      <Tab.Screen 
        name="Home" 
        component={HomeScreen} 
        options={{
          title: '主页',
          tabBarIcon: ({color}:any) => tabBarIcon('home', 'Entypo', color),
        }}
       />
       <Tab.Screen 
        name="Bibliotheca" 
        component={BibliothecaModel} 
        options={{
          tabBarLabel: '发现',
          tabBarIcon: ({color}:any) => tabBarIcon('library', 'MaterialCommunityIcons', color),
        }}
       />
       <Tab.Screen 
        name="Favorites" 
        component={FavoritesScreen} 
        options={{
          title: '收藏夹',
          tabBarIcon: ({color}:any) => tabBarIcon('collections-bookmark', 'MaterialIcons', color),
        }}
       />
       <Tab.Screen 
        name="MyCenter" 
        component={MyCenterScreen} 
        options={{
          title: '个人中心',
          tabBarIcon: ({color}:any) => tabBarIcon('user', 'Entypo', color),
        }}
       />
    </Tab.Navigator>
  );
}
// 入口路由
export default function MinRouter() {
  return (
    <Stack.Navigator
      initialRouteName="App"
      headerMode="none"
      screenOptions={{animationEnabled: false}}
    >
       {/* 登录验证 */}
      <Stack.Screen
        name="AuthLoading"
        component={LoginAuthScreen}
        options={{
          title: '登录验证',
        }}
      />
      {/* 主界面-tab */}
      <Stack.Screen
        name="App"
        component={AppStack}
        options={{
          title: '主界面-tab',
        }}
      />
      {/* 登录 */}
      <Stack.Screen
        name="Login"
        component={LoginScreen}
        options={{
          title: '登录',
          gestureEnabled: true,
        }}
      />
      {/* 其它 */}
      <Stack.Screen
        name="Other"
        component={OtherModel}
        options={{
          title: '其它',
        }}
      />
    </Stack.Navigator>
  );
};
```
Headers in options must have a DOM to avoid this

**Comment by zhuSass** [comment]
I updated the version (@react-navigation/bottom-tabs@5.6.1) which still had this problem, my code details were the code on the top when I set 'headerMode="none"' to go to the page the previous page was still left at the bottom and not destroyed, which did not happen after I set 'header=>node'

**Comment by zhuSass** [comment]
When the property of 'stack.Navigator' is headerMode='none', adjusting the page color will be abnormal; When a route navigates to a third-level route page, the second-level page behaves at the bottom

**Comment by zhuSass** [comment]
@satya164 This problem will appear in the latest version, it is very easy to reproduce, looking forward to your reply

**Comment by satya164** [comment]
I don't understand what you're describing. Please fill the issue template properly and provide gif/video if applicable.

**Comment by zhuSass** [comment]
[![IMAGE ALT TEXT HERE](https://img.youtube.com/vi/YOUTUBE_VIDEO_ID_HERE/0.jpg)](https://www.youtube.com/watch?v=r5VlzcAo42w)
This is a video I made. Please help me

**Comment by rynvva** [comment]
@satya164 maybe i have the same issue, when navigating to another screen, the previous one is still rendered

![IMAGE 2020-07-23 10:31:56](https://user-images.githubusercontent.com/39117076/88249800-bc706300-cccf-11ea-85fb-6cc11af0786d.jpg)

**Comment by luguoeryi** [comment]
yes, I also have this problem, Have you solved it？

**Comment by rynvva** [comment]
forHorizontal Transition cause the issue, I change to another Transition preset works

**Comment by zhuSass** [comment]
> forHorizontal Transition cause the issue, I change to another Transition preset works

forHorizontal Transition？Can you elaborate? I don't quite understand what you mean

**Comment by rynvva** [comment]
@zhuSass for example

```
const App = StackNavigator({
  AddContact: {
    screen: AddContact,
  },
  EditContact: {
    screen: EditContact,
  },
}, {
 transitionConfig: (() => ({ screenInterpolator: sceneProps => StackViewStyleInterpolator.forHorizontal(sceneProps) }))
})
```

**Comment by zhuSass** [comment]
> @zhuSass for example
> 
> ```
> const App = StackNavigator({
>   AddContact: {
>     screen: AddContact,
>   },
>   EditContact: {
>     screen: EditContact,
>   },
> }, {
>  transitionConfig: (() => ({ screenInterpolator: sceneProps => StackViewStyleInterpolator.forHorizontal(sceneProps) }))
> })
> ```

Does this code cause a problem with the bug description?I didn't customize the transition, using the default, but the problem arose anyway

**Comment by rynvva** [comment]
it cause the problem like what i have screenshot above, on spesific android device only

**Comment by zhuSass** [comment]
That means there are a lot of different situations that can trigger this bug, except in your case and mine

**Comment by chengzhuo5** [comment]
刚刚我也出现了这样的问题，通过修改cardStyleInterpolator.forHorizontalIOS函数中的translateUnfocused变量，解决了问题。
把outputRange: [0, screen.width * -0.3]改成outputRange: [0, screen.width * -1]就可以了

**Comment by zhuSass** [comment]
> 刚刚我也出现了这样的问题，通过修改cardStyleInterpolator.forHorizontalIOS函数中的translateUnfocused变量，解决了问题。
> 把outputRange: [0, screen.width * -0.3]改成outputRange: [0, screen.width * -1]就可以了

`cardStyleInterpolator.forHorizontalIOS`这个函数实在哪个位置，方便说下吗

**Comment by chengzhuo5** [comment]
> > 刚刚我也出现了这样的问题，通过修改cardStyleInterpolator.forHorizontalIOS函数中的translateUnfocused变量，解决了问题。
> > 把outputRange: [0, screen.width * -0.3]改成outputRange: [0, screen.width * -1]就可以了
> 
> `cardStyleInterpolator.forHorizontalIOS`这个函数实在哪个位置，方便说下吗

在node_modules/@react-navigation/stack/src/TransitionConfigs/CardStyleInterpolators.tsx里的forHorizontalIOS函数，把它复制到自己的项目里，同时复制依赖import { Animated } from 'react-native';const { add, multiply } = Animated;

如果图方便，可以直接删除{ translateX: translateUnfocused },这一行，因为Unfocused动画的效果很不明显，反而会有很多bug

**Comment by zhuSass** [comment]
> 在node_modules/@react-navigation/stack/src/TransitionConfigs/CardStyleInterpolators.tsx里的forHorizontalIOS函数，把它复制到自己的项目里，同时复制依赖import { Animated } from 'react-native';const { add, multiply } = Animated;

我并没有弄额外的动画自定义配置，但是也产生了该问题

**Comment by zhugy-yami** [comment]
same issue

**Comment by satya164** [comment]
Please provide a repro. It also might be a device/platform specific issue so make sure to provide information regarding device, platform and versions. It's impossible to help with issues when you don't fill the issue template.

**Comment by satya164** [comment]
Closing since you haven't provided a repro to debug the issue. If you manage to make a repro, please open a new issue with it and someone will take a look at it when possible.

**Comment by kangfenmao** [comment]
Same issue
