### ISSUE TITLE
There no props to hide the specific Top Tab.

### ISSUE THREAD

**Issue by SyedShahbazHussain** [react-navigation/react-navigation#8544]
**Hide Specific Top Tab**

- I want to hide specific top tab?
 
**Your Environment**

| software                            | version |
| ----------------------------------- | ------- |
| iOS or Android                      |Both
| @react-navigation/native            |5.0.8
| @react-navigation/material-top-tabs |5.2.12
| react-native-tab-view               |2.14.4
| react-native                        |0.61.5
| expo                                |
| node                                |
| npm or yarn                         |

**Comment by LEON-WLL** [comment]
I also want to hide the top tab。Have any method ？

**Comment by LEON-WLL** [comment]
just set as below

<Stack.Navigator
    **headerMode="none"**
>
.....
</NavigationContainer>
