### ISSUE TITLE
n.navigation 

### ISSUE THREAD

**Issue by hafeez-ullah-khan** [react-navigation/react-navigation#8545]
my navigation  running fine during debug and on emulator.but once i make bundle its 
in it apk its not working its shows the error

**Your Environment**

| software                       | 0.0.1|
| ------------------------------ | ------- |
| iOS or Android                 |
| "@react-navigation/native": "^5.0.8"      |
|"@react-navigation/stack": "^5.2.0",    |
|  "react-native-gesture-handler": "^1.6.0"  |
|  "react-native-safe-area-context": "^0.7.3",|
|     "react-native-screens": "^2.3.0",          |
| "react-native": "0.61.5",                 
![Screenshot_20200702-124206_ofw](https://user-images.githubusercontent.com/66471936/86569254-c3873980-bf8b-11ea-8ed1-a9a0fc43b48f.jpg)

**Comment by hafeez-ullah-khan** [comment]
> The versions mentioned in the issue for the following packages differ from the latest versions on npm:
> 
> * `@react-navigation/native` (found: `5.0.8`, latest: `5.6.1`)
> * `@react-navigation/stack` (found: `5.2.0`, latest: `5.6.2`)
> 
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?

**Comment by hafeez-ullah-khan** [comment]
no its not resolved

**Comment by satya164** [comment]
Closing since you didn't provide a repro. Feel free to open a new issue if you have a repro.
