### ISSUE TITLE
console.error: "The action 'SET_PARAMS' with payload {"params":{"_title":null}} was not handled by any navigator.

### ISSUE THREAD

**Issue by xiaolu8866** [react-navigation/react-navigation#8547]
react-navigation5

` 
setTimeout(() => {
            this.props.navigation.setParams({});
        }, 0);
this.props.navigation.goBack();
`

console.error: "The action 'SET_PARAMS' with payload {"params":{"_title":null}} was not handled by any navigator.

This is a development-only warning and won't be shown in production."

**Comment by xiaolu8866** [comment]
"@react-navigation/native": "^5.6.0",
"@react-navigation/stack": "^5.6.2",

**Comment by rgoldiez** [comment]
@xiaolu8866 any reason why you want your `goBack` executed before your `setParams`?

**Comment by xiaolu8866** [comment]
@rgoldiez For example, network request or delay operation

**Comment by rgoldiez** [comment]
@xianglinhe and if you change your code as shown below, without delaying the `setParams` until the navigator has been possibly unmounted with the `goBack` ..... do you still get the error?

```
this.props.navigation.setParams({ ... });
this.props.navigation.goBack();
```

**Comment by satya164** [comment]
Setting params after going back doesn't make sense. The screen doesn't exist anymore to update its params.
