### ISSUE TITLE
Documentation error with Deeplinking?

### ISSUE THREAD

**Issue by SRandazzo** [react-navigation/react-navigation#8549]
Hi,

react-navigation version: `5.5.1` and v5 of the docs (link below) 

I have been following the deeplinking documentation here:
https://reactnavigation.org/docs/configuring-links#mapping-path-to-route-names

And have been hitting consistent errors with react-navigation unable to utilize my config properly, for a scheme like `myapp://create` I will get an error "the action NAVIGATE with payload {name: create, params: {}} was not handled by any navigator. Do you have a screen named create?`

After much searching/looking through code It seems the issue is that the docs say to use a config like this:
```
const linking = {
  prefixes: ['https://mychat.com', 'mychat://'],
  config: {
    screens: {
      Chat: 'feed/:sort',
      Profile: 'user',
    },
  },
};
```

Whereas the top key in "config" should not be "screens" but rather your screen names themselves. ie:
```
const linking = {
  prefixes: ['https://mychat.com', 'mychat://'],
  config: {
      Chat: 'feed/:sort',
      Profile: 'user',
    },
  },
};
```

When I remove the top level "screens", deeplinking works as expected.

The source code for the `LinkingOptions` `config` is conflicting however. It's type interface says it should be of shape: `config?: { initialRouteName?: string; screens: PathConfigMap };`
But the documentation on config says it should look like my above example (no screens key`

https://github.com/react-navigation/react-navigation/blob/main/packages/native/src/types.tsx#L30-L43

I'm a bit unsure of this so any help is appreciated,
Thanks!

**Comment by satya164** [comment]
Update

**Comment by gwl002** [comment]
same problem

**Comment by chirag04** [comment]
for anyone else hitting this - updating the react-navigation version fixes the problem.
