### ISSUE TITLE
Drawer layout breaks on web when increasing window width

### ISSUE THREAD

**Issue by stephenkubovic** [react-navigation/react-navigation#8551]
**Current Behavior**

Using a `DrawerNavigator` in React Native Web with a dynamic `drawerType` and `drawerStyle` based on window width, the layout gets stuck in unexpected ways when increasing the window width (going from `drawerStyle='back'` to `drawerStyle='permanent'`). Inspecting the screen container, it looks like it gets stuck with a too-large `transform: translateX` style. This does not happen when reducing the window size (going from `drawerStyle='permanent'` to `drawerStyle='back'`)

Here's a [snack](https://snack.expo.io/@stephenkubovic/ecbfae) - view it on Web in a standalone window to test.

![React Navigation Drawer Bug](https://user-images.githubusercontent.com/5852428/86955697-febd7000-c125-11ea-8c4f-48ac28048803.gif)

**Expected Behavior**

When the `drawerType` changes from `'back'` to `'permanent'`, there should not be excess space between the drawer and the screen content.

**How to reproduce**

See this [snack](https://snack.expo.io/@stephenkubovic/ecbfae), which follows more-or-less the "master-detail layout " example code described in the [documentation](https://reactnavigation.org/docs/drawer-navigator/)

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| react-native-web                 | 0.13.1
| @react-navigation/native       | 5.5.1
| @react-navigation/drawer       | 5.8.4
| react-native-reanimated        | 1.9.0
| react-native-gesture-handler   | 1.6.1
| react-native-safe-area-context | 1.0.2
| react-native-screens           | 2.8.0
| react-native                   | 0.62.2
| expo                           | N/A
| node                           | 10.14.2
| npm or yarn                    | 1.22.4

**Comment by stephenkubovic** [comment]
I have confirmed the same behaviour exists using `@react-navigation/native@5.6.1`

**Comment by sohcah** [comment]
This issue is occurring in my app on Web and iOS (not tested on android yet) when rotating the device or resizing the screen.

**Comment by lanman2000** [comment]
I have the same issue!

**Comment by lanman2000** [comment]
Did you guys also the notice the browser back button is disabled? Is that intentional?

**Comment by nchase** [comment]
I think we're having this issue as well. `@react-navigation/native@5.7.3`

**Comment by corysimmons** [comment]
This makes drawers unusable with React Native Web 😢 

Has anyone figured out a workaround? I'm tracking layout changes and forcing drawers to close (so they'll re-render) with `onLayout` but it's still buggy.

**Comment by localjo** [comment]
This seems to be related to https://github.com/react-navigation/react-navigation/issues/10044

I tried forcing the drawer to unmount-remount on window resize by passing the window width as a key to the `Drawer.Navigator` and `Drawer.Screen` components, but that doesn't seem to force a re-calculation of the drawer's `translateX`, unfortunately.

**Comment by localjo** [comment]
For anyone else struggling with this, since it seems this issue hasn't been addressed for almost three years, downgrading to 6.1.4 seems to work for me, for now.

```bash
npm install --save @react-navigation/drawer@6.1.4
```

**Comment by milesingrams** [comment]
in Reanimated 3 there is no workaround for this since useLegacyImplementation doesn't work. Highly recommend reopening this as this library is getting even more traction with Expo Router and its basically not possible to do a right side drawer on web.
As a temporary workaround just adding a 'className' to the drawer would be helpful to allow people to use "!important" styles and override the broken translateX. using drawerStyle gets overwritten.

**Comment by albertowd** [comment]
> hi same issue

For anyone who has this problem yet, you should use a <SafeAreaProvider> on your app above the navigation hierarchy, the provider calls the updates on every window change and will instantly fix this issue in real time!

**Comment by albertowd** [comment]
Another possible fix is to use a patch-package with this fix:

https://github.com/react-navigation/react-navigation/pull/11398

But again, the `<SafeAreaProvider>` is the correct way to use SafeAreas on your App, just use this patch if you cannot the provider!
