### ISSUE TITLE
Avoid unmounting all screen when pushing a new anonymous screen into a nested stack navigator

### ISSUE THREAD

**Issue by rvera** [react-navigation/react-navigation#8552]
**Current Behavior**

Given an app that is structured like this
```
StackNavigator A
 └─ TabNavigator
    ├─ StackNavigator B1
    └─ StackNavigator B2
```
ie: 
- I have a root stack navigator
- One of the screens on that root stack is a tab navigator
- Each view on the tab has its own stack so they can push screens individually

When I push a screen on StackNavigator B1 or B2 using `navigation.push` the whole stack of nested screens gets unmounted then mounted again. Each screens calls `componentWillUnmount` and `componentDidMount` before pushing the new screen, losing their state in the process.

BUT, this only happens to anonymous components inside nested components. For example when I wrap a component with a function. 
- If I assign this result directly, it fails.
- If I assign this result to a const not in the global scope, it fails.
- This only works if I assign the result to a global const and then assign this to a Screen component.

**Expected Behavior**

- I'd expect elements of the stack to not get unmounted, instead it should just mount the new screen. This is the normal behavior for StackNavigator which are not nested.

**How to reproduce**

Check this snack
https://snack.expo.io/@rodvera/nested-stack-bug
Left tab fails, right tab works since I assign screens to a global const first.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | iOS
| @react-navigation/native       | 5.6.1
| @react-navigation/stack        | 5.6.2
| react-native-gesture-handler   | 1.6.1
| react-native-safe-area-context | 3.0.7
| react-native-screens           | 2.9.0
| react-native                   | 0.62.1
| expo                           | -
| node                           | 13.10.1
| npm or yarn                    | yarn

**Comment by satya164** [comment]
You shouldn't be creating components inside other components during render. If you do, React will remount the component every render, nothing specific to React Navigation.
