### ISSUE TITLE
Property isn't removed when i navigate to the same screen

### ISSUE THREAD

**Issue by dincozdemir** [react-navigation/react-navigation#8554]
**Current Behavior**

I navigate to `ScreenA` with property id = 5. As expected, I get `id` property in my query parameters in `ScreenA`. Then, I try to navigate to the same screen again without the id property. When I look into the query parameters, I still see the id property. When I try to navigate with `{ name: 'Mike' }` for example, I get `{ id: 5, name: 'Mike' }`. I have to enforce `{ id: null }` to remove the value. This only happens if Im trying to navigate to the same screen.

**Expected Behavior**

I should always get the exact same props I send when Im navigating to a screen.

**How to reproduce**

- Navigate to a screen with a property `navigation.navigate('ScreenA', { id: 5 })`
- Navigate to the same screen without that property `navigation.navigate('ScreenA')`
- Observe id parameter in query

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |  
| @react-navigation/native       | 5.6.1
| @react-navigation/stack        | 5.6.2
| react-native-gesture-handler   | 1.6.1
| react-native-safe-area-context |  3.0.2
| react-native-screens           | 2.9.0
| react-native                   | 0.62.2
| expo                           | 38.0.0
| node                           | 12
| npm or yarn                    | yarn

**Comment by dincozdemir** [comment]
Issue persist on latest versions
| software                       | version |
| ------------------------------ | ------- |
| @react-navigation/native       | 5.6.1
| @react-navigation/stack        | 5.6.2

**Comment by satya164** [comment]
https://github.com/react-navigation/react-navigation/pull/8555#pullrequestreview-445462374
