### ISSUE TITLE
How to test Deep Linking on Expo client (physical device)

### ISSUE THREAD

**Issue by proteche** [react-navigation/react-navigation#8556]
i tried to run following command,  but gives error "device not found".
`adb shell am start -W -a android.intent.action.VIEW -d "[ put your URI prefix in here ]" host.exp.exponent
`
**Note: -** here i am running my expo app on my "expo android app" on same network  by scanning QR code address is something like this"exp://192.168.0.2/:port"

**Comment by satya164** [comment]
You phone needs to be connected to your your computer over USB (or have adb wireless configured).
