### ISSUE TITLE
No label bottom tab's height too large

### ISSUE THREAD

**Issue by Andy-ZYA** [react-navigation/react-navigation#8562]
I am developing a bottom tab for my app and I want the tab to have no label. However, the icons are a bit too high up. 

I want to set the safeAreaInsets a few pixels less than the preset value. So I wrote the following code, but the safeAreaInsets doesn't change at all. Why is that?

BTW my package version: "@react-navigation/native": "^5.6.1"

<img width="306" alt="Screen Shot 2020-07-09 at 7 43 39 PM" src="https://user-images.githubusercontent.com/25261744/87101212-7ec60180-c21c-11ea-893a-49b0ca551904.png">

```
 <Tab.Navigator
    tabBarOptions={{
      activeTintColor: "#e91e63",
      showLabel: false,
      safeAreaInsets: (safeAreaInsets) => {
        bottom: safeAreaInsets - 20;
      },
    }}
  >
```

**Comment by satya164** [comment]
Your code doesn't work because `safeAreaInsets` isn't a function.

Regardless, you shouldn't be decreasing the bottom inset value from a usability point of view. It's there because the user should be able to interact with both tab bar and the navigation bar, not tap the other one accidentally.
