### ISSUE TITLE
currentlyFocusedField is deprecated react-native 0.63.0

### ISSUE THREAD

**Issue by maystrenkoYurii** [react-navigation/react-navigation#8566]
"@react-navigation/native": "5.7.0",
<img width="517" alt="Снимок экрана 2020-07-10 в 16 51 41" src="https://user-images.githubusercontent.com/23016311/87161854-c193e200-c2cd-11ea-83ba-2ba514676812.png">

**Comment by sandeshnaroju** [comment]
Facing the same problem in o.63.0. solved it?

**Comment by maystrenkoYurii** [comment]
@sandeshnaroju no solded. This warning from react-native about deprecated method

**Comment by iarmankhan** [comment]
Same error here with "@react-navigation/material-top-tabs"

```
"@react-navigation/material-top-tabs": "^5.2.13",
"@react-navigation/native": "^5.6.1",
"react-native": "0.63.0",
"react-native-gesture-handler": "^1.6.1",
"react-native-tab-view": "^2.14.4",
```

Any solutions yet?

**Comment by LuciferLat** [comment]
Me too facing this isssue. +1

**Comment by satya164** [comment]
You can update to latest version of `react-native-tab-view`.

**Comment by co-de** [comment]
I updated to 2.15.1 but still seeing the error. when I do `yarn list | grep tab-view` I see this:

```
├─ react-native-tab-view@2.15.1
│  ├─ react-native-tab-view@^1.2.0
│  └─ react-native-tab-view@1.4.1
│  ├─ react-native-tab-view@^1.4.1
│  └─ react-native-tab-view@1.4.1


```

Why do I still see the older versions?

**Comment by talhafayyaz12** [comment]
Any success on this??
