### ISSUE TITLE
unmounting first screen on tab switch to second screen

### ISSUE THREAD

**Issue by sohamsingh29** [react-navigation/react-navigation#8569]
**Current Behavior**
whenever i switch to second screen first screen unmounts causing a re render when i come back to the first screen

**Expected Behavior**

i dont want the first screen to re render 

**How to reproduce**

this is the github https://github.com/gauravdh9/healthapp/blob/master/components/NavigationScreens.js
I am using react-native animated-tab-bar which is made from react-navigation

**Your Environment**
I am using latest react-navigation
@react-navigation/native 5.6.1

**Comment by satya164** [comment]
Please open issue in the repo of the library you use instead of React Navigation, unless you can repro it without third party libs.
