### ISSUE TITLE
React Native Navigation Bottom TabBar Overflow Issue

### ISSUE THREAD

**Issue by muhammedesadkaya** [react-navigation/react-navigation#8571]
**Current Behavior**
when i want to take out the icon on Android, half of the icon is not visible.

Expo Link : https://snack.expo.io/NpjmTNusB

thanks.

![image](https://user-images.githubusercontent.com/24611163/87223010-c7e39600-c381-11ea-8a32-3f38315a1dc2.png)

| software                               | version |
| -------------------------------------- | ------- |
| iOS or Android                         | Android
| @react-navigation/native               |5.7.0
| @react-navigation/material-bottom-tabs |5.2.13
| react-native-paper                     |3.10.1
| react-native                           |
| expo                                   |
| node                                   |
| npm or yarn                            |

**Comment by akimabs** [comment]
still waiting for the answer

**Comment by raajnadar** [comment]
Use absolute position for the icon and keep the icon outside the bottom navigator.

**Comment by castalonirenz** [comment]
same issue here. hope there is a fix soon

**Comment by raajnadar** [comment]
You won't find a fix here, this is a navigation library. And the limitation is due to react native for android only. As I said you can use the Icon outside the TabBar.navigator & make it absolution positioned to place it anywhere on the screen.
