### ISSUE TITLE
currentlyFocussedField is deprecated error 

### ISSUE THREAD

**Issue by sandeshnaroju** [react-navigation/react-navigation#8573]
I am using the latest   `@react-navigation/material-top-tabs: "^5.2.13"` for `react-native 0.63.0`  version, facing  `currentlyFocussedField is deprecated` error. How to fix this?

**Comment by sandeshnaroju** [comment]
"@react-navigation/native": "^5.7.0" is the version

**Comment by zxccvvv** [comment]
You can change `<Tab.Screen/>` with Stack Navigator `<Stack.Screen/>

example:
```
function TabBar(){
  const TabStack = createStackNavigator();
  const Tab = createMaterialTopTabNavigator();
  return (
      <Tab.Navigator
        tabBarPosition='bottom'
      >
        <TabStack.Screen name="Home" component={Home} />
        <TabStack.Screen name="Another" component={Home} />
        <TabStack.Screen name="Settings" component={Home} />
      </Tab.Navigator>
  );
}
```

**Comment by ramacatur** [comment]
> You can change `<Tab.Screen/>` with Stack Navigator `<Stack.Screen/>`
> 
> example:
> 
> ```
> function TabBar(){
>   const TabStack = createStackNavigator();
>   const Tab = createMaterialTopTabNavigator();
>   return (
>       <Tab.Navigator
>         tabBarPosition='bottom'
>       >
>         <TabStack.Screen name="Home" component={Home} />
>         <TabStack.Screen name="Another" component={Home} />
>         <TabStack.Screen name="Settings" component={Home} />
>       </Tab.Navigator>
>   );
> }
> ```

I try this solution but didn't work
