### ISSUE TITLE
Going back with gesture not work when keyboard is on

### ISSUE THREAD

**Issue by Hamidrezana** [react-navigation/react-navigation#8574]
When keyboard is appear navigation back using gesture not work in react navigation.
When I hide keyboard it works.

Here is what's happening:

![RN](https://user-images.githubusercontent.com/32125441/87231729-d906c400-c3ce-11ea-8400-847d040dd38f.gif)

```
 "@react-navigation/native": "^5.7.0",
 "@react-navigation/stack": "^5.7.0",
```

**Comment by Hamidrezana** [comment]
@satya164 I wonder why issue closed without any response?

**Comment by satya164** [comment]
Don't open duplicate issues. You have already commented in another issue with the same problem, why open a new issue?
