### ISSUE TITLE
Jumpdown ScrollView with auto insets on BottomTab inside NativeStack

### ISSUE THREAD

**Issue by SDSLeon** [react-navigation/react-navigation#8575]
**Current Behavior**

ScrollView with contentInsetAdjustmentBehavior="automatic" initialy render under translucent header and after stack animation jumps down; 

GIF: [url](https://storage.de.cloud.ovh.net/v1/AUTH_b2cffe8f45324c2bba39e8db1aedb58f/cloudconvert-files/87d0b94d-9da2-417d-837a-5ad54414fe58/Запись%20экрана%202020-07-13%20в%2015.35.56.gif?temp_url_sig=0998bd7d02e92abf5590769b1d8ef8edcac63104&temp_url_expires=1594731587)

**Expected Behavior**

ScrollView with contentInsetAdjustmentBehavior="automatic" initialy render on bottom of header; 

As like material bottom tabs navigator works ;)

**How to reproduce**
Example: https://github.com/SDSLeon/nativeStackPlusTabTranslucentScroll

**Your Environment**

| software                      | version |
| ----------------------------- | ------- |
| iOS                | all versions
| @react-navigation/native      | 5.7.0
| @react-navigation/bottom-tabs | 5.7.0
| react-native-screens          | 2.9.0
| react-native                  | 0.63.0
| expo                          |
| node                          | 13.11
| npm or yarn                   | yarn 1.22.4

**Comment by SDSLeon** [comment]
mistyped version of @react-navigation/native and @react-navigation/bottom-tabs

**Comment by satya164** [comment]
Please open native stack related issues in react-native-screens repo https://github.com/software-mansion/react-native-screens/

**Comment by SDSLeon** [comment]
@satya164 but jumping only appear with bottomTabNavigation with bottomMaterialNavigation its work correctly

**Comment by satya164** [comment]
If you can repro it without native stack then feel free to open a new issue.
