### ISSUE TITLE
getActionFromState not compatible with TabRouter state representation

### ISSUE THREAD

**Issue by cjpete** [react-navigation/react-navigation#8576]
**Background**

When our app is backgrounded, we log the user out and enforce a passcode before returning. This means transitioning between the main authenticated App (tab navigator) and the unauthenticated Auth application. The desire is to take the user back to where they were in the authenticated App - i.e. rehydrate the navigation state.

**Current Behavior**

```
<NavigationContainer
  ref={navigationRef}
  onStateChange={// store state for use later}
>
 {isLoggedIn ? <App /> : <Auth />}
</NavigationContainer>
```

```
const resetNavigationState = (state) => {
  navigator.dispatch(getActionFromState(state))
}
```

Using onStateChange to store the state in memory, and when foregrounding the app, using that state variable to call `resetNavigationState`.

Due to the way the `TabRouter` constructs its state (it pushes all configured tabs into the route state), and how `getActionFromState` uses the last entry in the route state to decide which screen to route to, it means that the constructed action object will always point to the last tab.

I'm not sure that the recipe described in https://reactnavigation.org/docs/state-persistence is suitable here, as I don't want to have to unmount the entire navigator in order to recover the state of an individual stack navigator.

**Your Environment**

```
"@react-navigation/bottom-tabs": "5.7.0",
"@react-navigation/native": "5.7.0",
```

**Comment by satya164** [comment]
You don't have to use `getActionFromState`. If you want to reset the navigation state to desired state, use `navigationRef.current.resetRoot(state)`.
