### ISSUE TITLE
Empty badget on bottom-tabs v5.7.0 when app blur on Android

### ISSUE THREAD

**Issue by outaTiME** [react-navigation/react-navigation#8577]
In Android when my application opens a link using "Linking" and the app blur for some reason and randomly the badge appears in each of the items in the bottom bar.

when I focus on the application again the badges disappear

(I don't even use the badge functionality)

<img width="668" alt="CleanShot 2020-07-13 at 12 06 57@2x" src="https://user-images.githubusercontent.com/140472/87320553-7235f780-c501-11ea-9384-cc7161bddb4f.png">

Thanks !!!

**Your Environment**

| software                      | version |
| ----------------------------- | ------- |
| iOS or Android                | Android
| @react-navigation/native      |  5.7.0
| @react-navigation/bottom-tabs | 5.7.0
| react-native-screens          | 2.2.0
| react-native                  | 0.61
| expo                          | 37
| node                          | 12
| npm or yarn                   | yarn

**Comment by outaTiME** [comment]
BTW, if I go back to the previous versions:

```
@react-navigation/native (v5.6.1) 
@react-navigation/bottom-tabs (v5.6.1) 
```

the issue does not seem to occur

**Comment by satya164** [comment]
Weird bug. Can you try if it's fixed with latest version of bottom-tabs?

**Comment by outaTiME** [comment]
@satya164 i think it works, I try the new version and I couldn't reproduce it anymore, thanks !!!

🙏
