### ISSUE TITLE
useLinkTo broken when using useLinking

### ISSUE THREAD

**Issue by robertherber** [react-navigation/react-navigation#8579]
**Current Behavior**

useLinkTo is broken when using useLinking to handle deep linking.

LinkingContext is only set when linking is specified on the `NavigationContainer` component - and doing so throws an error when using `useLinking`. This means that useLinkTo gets an undefined config from LinkingContext and it's not able to correctly use getStateFromPath.

**Expected Behavior**

I'd expect useLinkTo to use the LinkingOptions I've specified in useLinking. Or if there's another thought out way to configure useLinkTo and useLinking together this should be reflected in the documentation.

Current workarounds:
* Specifiying `linking` directly on NavigationContainer (removing the error). But I suppose there is a reason for this error?
* Setting LinkingContext manually, but since it's not directly exported like this:
```TypeScript
import LinkingContext from '@react-navigation/native/lib/module/LinkingContext';
// ...
<LinkingContext.Provider value={{ options: linkingConfig }}>
  <Routes />
</LinkingContext.Provider>
```

**How to reproduce**

```TypeScript
import React, {
  useRef, useState, useEffect, FunctionComponent,
} from 'react';
import { createBottomTabNavigator } from '@react-navigation/bottom-tabs';
import {
  NavigationContainer,
  useLinking,
  InitialState,
  NavigationContainerRef,
  LinkingOptions,
  useLinkTo,
} from '@react-navigation/native';
import { Text, Button } from 'react-native';

const linkingConfig: LinkingOptions = {
  prefixes: ['https://localhost:19006'],
  config: {
    screens: {
      RouteA: {
        path: 'a',
      },
      RouteB: {
        path: 'b',
      },
    },
  },
};

const Tab = createBottomTabNavigator();

const RouteA: FunctionComponent = () => {
  const linkTo = useLinkTo();
  return (
    <>
      <Text>This is route A</Text>
      <Button onPress={() => linkTo('/b')} title='useLinkTo > B' />
    </>
  );
};
const RouteB: FunctionComponent = () => {
  const linkTo = useLinkTo();
  return (
    <>
      <Text>This is route B</Text>
      <Button onPress={() => linkTo('/a')} title='useLinkTo > A' />
    </>
  );
};

const Routes: FunctionComponent = () => (
  <Tab.Navigator>
    <Tab.Screen key='RouteA' name='RouteA' component={RouteA} />
    <Tab.Screen key='RouteB' name='RouteB' component={RouteB} />
  </Tab.Navigator>
);

type Props = {

}

const App: FunctionComponent<Props> = () => {
  const [initialState, setInitialState] = useState<InitialState | undefined>(undefined),
        [isNavReady, setReady] = useState(false),
        navigationRef = useRef<NavigationContainerRef>(null),
        { getInitialState } = useLinking(navigationRef, linkingConfig);

  useEffect(() => {
    void getInitialState().then((state) => {
      if (state) {
        setInitialState(state);
      }
      setReady(true);
    });
  }, [getInitialState]);

  if (!isNavReady) {
    return null;
  }

  return (
    <NavigationContainer
      initialState={initialState}
      ref={navigationRef}
    >
      <Routes />
    </NavigationContainer>
  );
};

export default App;
```

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| Browser                 | Chrome 83.0.4103.116
| @react-navigation/native       | 5.7.0
| react-native                   | 0.62.2
| expo                           | 38
| node                           | 12.17.0
| yarn                    | 1.22.4

**Comment by satya164** [comment]
Like the `useLinking` documentation says, you should use `linking` prop instead of using the hook directly.

**Comment by robertherber** [comment]
@satya164 Ah, when I implemented it the linking prop wasn't working well on the web - seems to work now. Thanks!
