### ISSUE TITLE
Missing popToTop() on tabPress for nested stack navigator

### ISSUE THREAD

**Issue by HristoEftimov** [react-navigation/react-navigation#8583]
**Current Behavior**

Cannot popToTop() the nested Stack.Navigation on tabPress (it's missing);

**Expected Behavior**

To be able to reset the nested stack navigator on tab press.

**How to reproduce**

With the simplest structure of nested stack navigation on each tab, add a listener for `tabPress` and try to reset the Stack. Currently, it is not possible because of the missing `popToTop()` property (https://reactnavigation.org/docs/bottom-tab-navigator#tabpress)
```
const HomeStack = createStackNavigator();

function HomeStackScreen() {
  return (
    <HomeStack.Navigator>
      <HomeStack.Screen name="Home" component={HomeScreen} />
      <HomeStack.Screen name="Details" component={DetailsScreen} />
    </HomeStack.Navigator>
  );
}

const SettingsStack = createStackNavigator();

function SettingsStackScreen() {
  return (
    <SettingsStack.Navigator>
      <SettingsStack.Screen name="Settings" component={SettingsScreen} />
      <SettingsStack.Screen name="Details" component={DetailsScreen} />
    </SettingsStack.Navigator>
  );
}

const Tab = createBottomTabNavigator();

export default function App() {
  return (
    <NavigationContainer>
      <Tab.Navigator>
        <Tab.Screen name="Home" component={HomeStackScreen} />
        <Tab.Screen
          name="Settings" 
          component={SettingsStackScreen} 
          listeners={({ navigation, route }) => ({
            tabPress: e => {
              // navigation.popToTop();
              navigation.navigate(route.name);
            },
          })}
      />
      </Tab.Navigator>
    </NavigationContainer>
  );
}
```

**Snack**
https://snack.expo.io/@hristoeftimov/cea3db

**Environment**

| software                      | version |
| ----------------------------- | ------- |
| @react-navigation/native      |    5.6.1
| @react-navigation/bottom-tabs |   5.6.1
| react-native-screens          |    2.9.0
| expo                          | SDK 38.0.2

**Comment by satya164** [comment]
1. `popToTop` is already called by default on tab press
2. https://reactnavigation.org/docs/nesting-navigators#navigator-specific-methods-are-available-in-the-navigators-nested-inside

**Comment by HristoEftimov** [comment]
@satya164 Thanks for your answer. But if `popToTop` is called by default, then why the nested Stack is not reset to the initial load when press the tab button?

For example, you go to the Settings tab and then you open the Details page. When you navigate to the Home tab and then go back to the Settings, the current screen will be the Details, no the initial (Settings).

**Comment by satya164** [comment]
https://reactnavigation.org/docs/bottom-tab-navigator#unmountonblur

**Comment by HristoEftimov** [comment]
With `unmountOnBlur` will work, but unfortunately, it always will mount/unmount the components :( 

I am looking for a pragmatic solution, like this: https://github.com/react-navigation/react-navigation/issues/1557#issuecomment-518922107
but it looks not possible on ver.5 :)

**Comment by codoffer** [comment]
@HristoEftimov 

I have tried to figure out this issue and handled it by the below code. I have called the tab navigator and passed the stack screen name. (in my case both are same)

`tabBarButton: props => (
            <TouchableOpacity
              {...props}
              onPress={props => {
                navigation.navigate('Home', {
                  screen: 'Home'
                })
              }}
            />
          ),`

**Comment by carsonus** [comment]
I'm running into this same use case in v5 where I want to reset the history (see the initial tab stack screen) without fully reseting and unmounting the stack. Did you find anything @HristoEftimov ?

**Comment by HristoEftimov** [comment]
@carsonus I found a workaround but the way I want :/ 

I am passing a `listener` event to the screen:
```
<Tab.Screen
     name="homeTab"
     component={HomeStackScreen}
     listeners={tabBarListeners}
/>
```

and then I navigate the user to the initial rout every time when he presses the tab:
```
const tabBarListeners = ({ navigation, route }) => ({
    tabPress: () => navigation.navigate(route.name),
});
```

It works but unfortunately, there is a small visual effect for the user, where he can see this `navigation` from the previous screen to the initial one. Not the best option but this is the only approach that I found :/ Any ideas are welcome :)

**Comment by carsonus** [comment]
@HristoEftimov thanks for sharing that! I'd tried this as well and concur that the slight animation is unfortunate. But it is better than fully unmounting/remounting in my case.

Fwiw I tried internally manipulating the `state` object that can be obtained when dispatching a reset
```ts
navigation.dispatch((state) => {
    // manipulate state and routes here
    return CommonActions.reset({
        ...state,
    });
});
```
And it _still_ resulted in the same quick animation of the prior screen on the stack leaving. 🙃

**Comment by carsonus** [comment]
@HristoEftimov I just found a way to achieve the behavior I wanted using internal state, and it doesn't feel too hacky since I'm not modifying anything (just figuring out where to send the `popToTop` command). This is the function that I then set as `listeners={resetTabStackListener()}` on my tab screens. I'm using typescript btw.

```ts
function resetTabStackListener() {
    // On Android, we want to clear the tab stack history when a user returns to the tab.
    if (Platform.OS === PlatformOs.Android) {
        return function ResetTabStackListener({ navigation }: BottomTabScreenProps<Record<string, undefined>>) {
            // To accomplish the above without delaying the tab switch or incurring loading or animation UX, we
            // clear the history of all tab stacks except for the one being navigated to. This means that the
            // prior stack will be at the desired state if the user returns to it. Since we don't know which
            // tab the user was coming from, we must clear all but the target stack.
            return {
                tabPress: (e: EventArg<"tabPress", true>) => {
                    const state = navigation.dangerouslyGetState();

                    if (state) {
                        const nonTargetTabs = state.routes.filter((r) => r.key !== e.target);

                        nonTargetTabs.forEach((tab) => {
                            const stackKey = (tab.state as NavigationState)?.key;

                            if (stackKey) {
                                navigation.dispatch({
                                    ...StackActions.popToTop(),
                                    target: stackKey,
                                });
                            }
                        });
                    }
                },
            };
        };
    } else {
        // iOS preserves history.
        return undefined;
    }
}
```

**Comment by mightym** [comment]
Just for the interest how is that different from using `unmountOnBlur: true` as `screenOptions` on the Navigator? I just tested  it on my tabs. Screen I left via a tab got reset and there is even no animation.
