### ISSUE TITLE
Warning spam: "Accessing child navigation state for a route is not safe and won't work correctly."

### ISSUE THREAD

**Issue by cristianoccazinsp** [react-navigation/react-navigation#8584]
**Current Behavior**

Typical code with `<Stack.Navigator ...><Stack.Screen>....`.

Variables omitted, but you get the gist.
```
const Stack = createStackNavigator();

const StackNavigator = () => (

  <Stack.Navigator
    initialRouteName="Home"
    headerMode='screen'
    screenOptions={({ navigation, route }) => {
      return {
        header: props => <MainHeader back={true} title={props.scene.descriptor.options.title} navigation={navigation} route={route}/>,
        gestureEnabled: false,
        transitionSpec: {
          open: animationConfig,
          close: animationConfig,
        },
        cardStyleInterpolator: animationInterp
      }
    }}
  >
    <Stack.Screen
      name="Home"
      component={Home}
      options={({ navigation, route }) => {
        return {
          title: "Home",
          header: props => <HomeHeader navigation={navigation} route={route}/>
        }
      }}
    />

    <Stack.Screen
      name="InitialSettings"
      component={InitialSettings}
      options={{ title: 'Settings', headerShown: false }}
    />

    <Stack.Screen
      name="Settings"
      component={Settings}
      options={{ title: 'Settings' }}
    />
   ...other similar screens
  </Stack.Navigator>

)


// the following is to log breadcrumbs
const getActiveRouteName = state => {
  const route = state.routes[state.index];

  if (route.state) {
    // Dive into nested navigators
    return getActiveRouteName(route.state);
  }

  return route.name;
};

onNavigationStateChange = (currentState) => {

    const currentScreen = getActiveRouteName(currentState);

    if (this.prevScreen !== currentScreen) {
      // log breadcrumb
    }
    this.prevScreen = currentScreen;
  }


render(){
 <NavigationContainer onStateChange={this.onNavigationStateChange}>
     <StackNavigator />
 </NavigationContainer>
}
```

The above example, spams "Accessing child navigation state for a route is not safe and won't work correctly." on app start and on every navigation change.  I have removed the `onStateChange` and made sure no calls to `props.navigation.dangerouslyGetState()` are done anywhere, yet I get this warning on every screen navigation.

What's even worse, these warns freeze animations, and there's no way to revert back to the previous version to fix the issue.

**Expected Behavior**
No warnings.

**How to reproduce**
With the above code, just adding/removing screens from the stack will cause the warnings.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | both
| @react-navigation/native       | 5.7.0
| react-native                   | 0.61.5
| expo                           | none
| node                           | 12.16.3
| npm or yarn                    | npm 6.14.4

Related: https://github.com/react-navigation/react-navigation/issues/8348

**Comment by cristianoccazinsp** [comment]
I cannot provide a repro, but the issue happens any time `withNavigation` from `@react-navigation/compat` is used.

**Comment by cristianoccazinsp** [comment]
Any thoughts on this? What could it be?

**Comment by cristianoccazinsp** [comment]
Still an issue with the most recent update:
"@react-navigation/compat": "5.2.1",
"@react-navigation/native": "5.7.1",
"@react-navigation/stack": "5.7.1"

**Comment by Ztarbox** [comment]
Following the documentation HOCs using, `withNavigation` is used in conjunction with `createCompatNavigationFactory(createStackNavigation)` instead of `createStackNavigation()`. 
https://reactnavigation.org/docs/compatibility

Probably this is the problem? Not sure cause I don't use these compatibility features.

**Comment by cristianoccazinsp** [comment]
I will give it a try, but it used to work fine until the most recent update. What if we are using the documented v5 stack navigator (defined as functional components), but some deep children needs access to the navigation prop. It would make sense to still support `withNavigation`, we are otherwise forced to always use the legacy api just because 1 component needs it :(

**Comment by Ztarbox** [comment]
For FCs you there is the  `useNavigation` hook

> useNavigation is a hook which gives access to navigation object. It's useful when you cannot pass the navigation prop into the component directly, or don't want to pass it in case of a deeply nested child.
https://reactnavigation.org/docs/use-navigation

**Comment by satya164** [comment]
> Any thoughts on this? What could it be?

If you can't provide a repro then how do you expect anyone to know why you have the warning? I don't think it has to do with `withNavigation`. You're probably accessing `navigation.state.index` or `navigation.state.routes` somewhere in your app which is what it's warning against. The warnings should have a stack trace which should tell you exactly where the warning comes from in your code.

Also I don't see what it has to do with the linked issue in React Navigation repo, it's a completely different warning.

**Comment by cristianoccazinsp** [comment]
As I said, it definitely comes from using `withNavigation`.  From the above comments, it may be related to using `withNavigation` and not the `createCompatNavigationFactory` (but rather the recommended way of instantiating the navigator).

I'm definitely not using `navigation.state.index` nor `navigation.state.routes`. 

Here's the stack trace.  RN 0.63.1 doesn't really provide a nicely formatted stack trace on the console, reason I didn't post it initially.

**Comment by satya164** [comment]
There are also your components in stack trace you need to investigate. The first line is some `NavigationEvents` component wrapped in `withNavigation`, not `withNavigation`.

Regardless, there's a high chance that it's an issue in your code unless you can repro it to be an issue with React Navigation, and if you can, open a new issue with repro.

**Comment by cristianoccazinsp** [comment]
I will definitely try to get a repro, it just really takes so much time to set it up, and since the issue appeared out of nowhere (no code changes, just some internal update in the react-navigation/core), I thought it would be pretty obvious where the issue was coming from (be it a bug or usage problem). Worst of all, is that I cannot even revert to the previous version that didn't have this issue (because internal requirements are defined with ^ instead of pinned to an exact version)

NavigationEvents is just a component to implement a removed feature from v4, a very simple one:

```
class NavigationEvents extends React.PureComponent{

  componentDidMount(){
    this.blur = this.props.navigation.addListener('blur', this.handleBlur);
    this.focus = this.props.navigation.addListener('focus', this.handleFocus);
  }

  componentWillUnmount(){
    this.blur && this.blur();
    this.focus && this.focus();
  }

  handleFocus = (e) => {
    this.props.focus && this.props.focus(e);
  }

  handleBlur = (e) => {
    this.props.blur && this.props.blur(e);
  }

  render(){
    return null;
  }
}

NavigationEvents = withNavigation(NavigationEvents);
```

However, the above is not the only place the warning happens. Literally, any component that is re-rendered and wraped with `withNavigation` fires the warning. Here's another stack trace:

```
Accessing child navigation state for a route is not safe and won't work correctly. 
withNavigation(QueueStatus)@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:183818:23
ConnectFunction@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:161361:43
RCTView
Right@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:118444:22
Styled(Right)@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:101995:40
RCTView
Header@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:175432:36
Styled(Header)@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:101995:40
MainHeader@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:174972:36
Styled(MainHeader)@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:101995:40
RCTView
RCTView
HeaderContainer@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:159729:20
RCTView
RCTView
CardSheet@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:159423:23
RCTView
AnimatedComponent@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:60687:24
AnimatedComponentWrapper
PanGestureHandler@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:97739:38
PanGestureHandler@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:156417:34
RCTView
AnimatedComponent@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:60687:24
AnimatedComponentWrapper
RCTView
Card@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:158885:36
CardContainer@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:158615:22
RCTView
MaybeScreen@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:157046:24
RCTView
MaybeScreenContainer@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:157021:23
CardStack@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:156602:36
KeyboardManager@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:159601:36
RNCSafeAreaProvider
SafeAreaProvider@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:156212:24
SafeAreaProviderCompat@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:160034:24
RCTView
StackView@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:155729:36
StackNavigator@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:155616:32
StackNavigator
EnsureSingleNavigator@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:150070:24
BaseNavigationContainer@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:149744:28
ThemeProvider@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:154092:21
NavigationContainer@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:154001:26
RCTView
Root@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:141816:22
Styled(Root)@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:101995:40
StyleProvider@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:110009:36
RootApp@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:101153:36
ConnectFunction@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:161361:43
PersistGate@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:164270:22
Provider@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:160949:21
App@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:101389:36
Entry@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:1495:36
RCTView
RCTView
AppContainer@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:67301:22
```

Notice the component now is `QueueStatus`, which is also a simple component:

```
class QueueStatus extends React.PureComponent {

  render() {
    let props = this.props;
    let style = noTextStyle;
    if (props.errors){
      style = Object.assign({}, style, {color: 'red'});
    }
    return (
      <Button
        transparent
        rounded
        noSpacing
        onPress={() => this.props.navigation.navigate('Queue')}
      >
        <Text style={style}>{`${props.total}`}</Text>
      </Button>
    );
  }
}

QueueStatus = withNavigation(QueueStatus);

// redux connect, warning appears even if this is removed.
export default connect(
  (state, ownProps) => {
    return {
      total: state.queue.total,
      errors: state.queue.errors,
      theme: state.settings.theme
    }
  }
)(QueueStatus);
```

I understand I'm not providing enough info without a repro, but doesn't it look strange that all stack traces include withNavigation?

**Comment by satya164** [comment]
I can't repro it with `withNavigation` and I don't see why `withNavigation` would produce such warning, but if you can't provide a repro, then there's nothing I can do. If I don't have the confirmation that this is a bug in React Navigation with a repro then I don't want to spend time on it investigating.

**Comment by cristianoccazinsp** [comment]
Were you using Expo? Do you have any repo with RN 0.63.x I can fork to test (without expo)?

**Comment by cristianoccazinsp** [comment]
Well, I wasn't able to reproduce it with Expo snack (probably because it swallows most warnings), but I was able to reproduce it with a very simple project created from scratch and `withNavigation`. Will provide repo soon.

**Comment by satya164** [comment]
> As I said, all I had to do was to use withNavigation

The only reason you see it when using `withNavigation` is because you're using only this HOC from compat lib. In fact, this seems like a change in the runtime behavior in latest React Native (babel preset) which triggers a warning.

I'll change the code to fix the warning, but I also suggest you to not use `withNavigation` since you're not using compat navigators, and please provide a repro when opening issues in future to avoid back n forth.

> can you re-open if this is indeed a bug

I asked to open a new issue, but doesn't matter.

**Comment by cristianoccazinsp** [comment]
Our current code is still using (mostly) class-based components, instead of hooks.  I was under the impression that the two can be combined, hence I'm using the new API for the root/stack navigator (it's definitely better!), but the HOC on class-based components when required. Do you think this is a bad idea? Was it documented and I overlooked it?

If anything, should I switch back to the compat navigator since most of the code is still class-based?  Truth is, we don't expect to migrate existing code to hooks any time soon, but we like the new API and would like to use it as much as possible.

I appreciate your patience.

**Comment by satya164** [comment]
You should use this approach for class components https://reactnavigation.org/docs/use-navigation#using-with-class-component
