### ISSUE TITLE
Render artifacts when rendered under a full screen blur view

### ISSUE THREAD

**Issue by pke** [react-navigation/react-navigation#8585]
**Current Behavior**

Inside one of my screens I display a transparent RN Modal to blur the entire app when the modal is visible.
The way the [RN Blur](https://github.com/react-native-community/react-native-blur) works on Android, is by compositing the layers of views which leads to a subtle bug in the bottom tab navigator. It seems one of the theme colors (red from the card?) leaks in between the tab elements when the tab-bar is composited under the blur. As if the borders of each tab item is rendered in the theme colour. I later found out (see expected behaviour) that the backgroundColor of the tabBar seems to be the problem.
The inactiveBackgroundColor and activeBackgroundColor override the card color, that is the tabbars background by default, correctly when the blue is not rendered. When the blur is rendered, through its special screen composition, the inactive/activeBackgroundColor do not seem to cover the whole tabbar.

When the blur is not rendered, the tabbar looks correct.

My theme is this:

```ts
const theme: Theme = {
  ...DefaultTheme,
  colors: {
    ...DefaultTheme.colors,
    background: colors.white,
    primary: colors.darkPurpleOnRed,
    card: colors.red,
    text: colors.white,
  },
}
<Tab.Navigator
    initialRouteName="overview"
    tabBarOptions={{
      inactiveBackgroundColor: "#fff",
      activeBackgroundColor: "#fff",
      activeTintColor: colors.red,
      inactiveTintColor: "#000",
      style: {
        elevation: 24,
        shadowColor: "#000",
        shadowOffset: {
        width: 0,
        height: 0,
        },
        shadowOpacity: 0.5,
        shadowRadius: 15,
    },
  }}
>
``` 

| no blur | with blur |
|-|-|
|![without blur](https://user-images.githubusercontent.com/164625/87438208-8bb56d00-c5ef-11ea-986b-a8ec0fd7c034.png)|![Screenshot_1594736684](https://user-images.githubusercontent.com/164625/87438266-9d971000-c5ef-11ea-862d-750ad9f0b748.png)|

- Include a screenshot or video if it makes sense.

**Expected Behavior**

Setting the tabBar `backgroundColor` style manually to white solves the issue:

```diff
<Tab.Navigator
    initialRouteName="overview"
    tabBarOptions={{
      inactiveBackgroundColor: "#fff",
      activeBackgroundColor: "#fff",
      activeTintColor: colors.red,
      inactiveTintColor: "#000",
      style: {
        elevation: 24,
        shadowColor: "#000",
        shadowOffset: {
        width: 0,
        height: 0,
        },
        shadowOpacity: 0.5,
        shadowRadius: 15,
+       backgroundColor: "#fff",
    },
  }}
>
```

![Screenshot_1594737374](https://user-images.githubusercontent.com/164625/87439693-60cc1880-c5f1-11ea-8026-87ad7e6fe035.png)

**How to reproduce**

Repo follows.

**Your Environment**

| software                      | version |
| ----------------------------- | ------- |
| Android                       | 5.1.1
| @react-navigation/native      | 5.7.0
| @react-navigation/bottom-tabs | 5.7.1
| react-native-screens          | 2.7.0
| react-native                  | 0.62.2
| @react-native-community/blur  | 3.6.0
| expo                          | -
| node                          | 14.3.0
| npm or yarn                   | 1.22.4

edit: updated to newest versions, issue still exists.

**Comment by pke** [comment]
Issue still exists with latest versions on npm.

**Comment by satya164** [comment]
I don't think there's anything actionable for React Navigation. If that's how blur view works, we can't do anything about it.

Besides, you're supposed use the `style` prop to set the background color of the tab bar, not `inactiveBackgroundColor`.
