### ISSUE TITLE
useScrollToTop only works with the last 'tab' navigator when nesting top and bottom tab navigators

### ISSUE THREAD

**Issue by iirovi** [react-navigation/react-navigation#8586]
**Current Behavior**

When a top tab navigator is nested in a bottom tab navigator, the `useScrollToTop` hook only scrolls to top when pressing the current top tab, not the bottom tab. 
https://snack.expo.io/ll8bTFpxv

This is because these lines in the code for `useScrollToTop`
<img width="628" alt="Screen Shot 2020-07-14 at 12 21 37" src="https://user-images.githubusercontent.com/1415868/87453679-de336100-c5d0-11ea-95b4-70d6bdc62fee.png">

**Expected Behavior**

I would expect that `useScrollToTop` would work for both tab bars, so that I could tap on either to scroll my current scrollview to top. 

**How to reproduce**

https://snack.expo.io/ll8bTFpxv

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| @react-navigation/native       | ^5.7.0
| @react-navigation/material-top-tabs       | ^5.2.13
| @react-navigation/bottom-tabs       | ^5.7.1
| react-native                   | 0.62
| expo                           | 36.0.0
| node                           | 12.16.1
| npm or yarn                    | 1.22.4

**Comment by iirovi** [comment]
> The versions mentioned in the issue for the following packages differ from the latest versions on npm:
> 
> * `@react-navigation/native` (found: `5.2.4`, latest: `5.7.0`)
> * `@react-navigation/material-top-tabs` (found: `5.1.15`, latest: `5.2.13`)
> * `@react-navigation/bottom-tabs` (found: `5.3.4`, latest: `5.7.1`)
> 
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?

Yes, issue still persist after upgrading (I edited the description and the snack to use the latest versions)

**Comment by anhkieet** [comment]
I faced the same issue as you. The useScrollToTop only work for top tab

**Comment by iirovi** [comment]
In case anyone stumbles into this issue later, I ended up implementing a custom solution, hooking up to the tab press listener of my bottom tab, and firing off an event from there if the tab is focused and in the first element of my stack navigator, and having my view containing the scrollable handle that event. 

```
<BottomTab.Screen
  name="Home"
  component={HomeComponent}
  listeners={({navigation, route}) => ({
    tabPress: () => {
      const isAtFirstScreenOfStack = !route.state || route.state?.index === 0;
      if (navigation.isFocused() && isAtFirstScreenOfStack) {
        // here, fire off an event and listen to that in your relevant component
      }
    },
    })}
/>
```

**Comment by topmaster716** [comment]
> In case anyone stumbles into this issue later, I ended up implementing a custom solution, hooking up to the tab press listener of my bottom tab, and firing off an event from there if the tab is focused and in the first element of my stack navigator, and having my view containing the scrollable handle that event.
> 
> ```
> <BottomTab.Screen
>   name="Home"
>   component={HomeComponent}
>   listeners={({navigation, route}) => ({
>     tabPress: () => {
>       const isAtFirstScreenOfStack = !route.state || route.state?.index === 0;
>       if (navigation.isFocused() && isAtFirstScreenOfStack) {
>         // here, fire off an event and listen to that in your relevant component
>       }
>     },
>     })}
> />
> ```

`route` variable doesn't contain `state` variable.
Can you give me the solution in this case?
Main Bottom Tab Navigator has 5 tabs.
First Tab (`Home`) contains several stack navigators.
Among them, one stack has 3 top tab(`Post`, `News`, `You`)s.
I would expect usescrollToTop effect in `Post` top tabs when user clicks `Home` bottom tab.

**Comment by RMCollins175** [comment]
did you find the solution @topmaster716 ? thanks!!

**Comment by zstuder25** [comment]
I was able to implement the solution above. For context, we have an app with a Bottom nav bar and a top tab nav bar embedded in the first tab of the bottom nav bar. 
`listeners={({navigation, route}) => ({
    tabPress: () => {
      const isAtFirstScreenOfStack = !route.state || route.state?.index === 0;
      if (navigation.isFocused() && isAtFirstScreenOfStack) {
        // here, fire off an event and listen to that in your relevant component
        // I did and EventRegister.emit() here, you can fire off whatever relevant event library you use
      }
    },
    })}`
    
    Then in the corresponding FlatList, if you have one in each top tab like we did, we only want this to work on the one that is currently focused, so I used useFocusEffect
    `useFocusEffect(
    useCallback(() => {
      if (scrollToTop) {
        scrollToTopListener.current = EventRegister.addEventListener("scrollToTop", () => {
          listRef.current.scrollToOffset({ animated: true, offset: 0 });
        });
      }

      return () => {
        if (scrollToTop) {
          EventRegister.removeEventListener(scrollToTopListener.current);
        }
      };
    }, [])
  );`
  
  this ensures that when the event is fired/emitted from the bottom tab option, the event is only caught by the list that is currently in focus. I tried this with useIsFocused(), but it didn't work because and shouldn't according to the docs
  https://reactnavigation.org/docs/use-focus-effect/#how-is-usefocuseffect-different-from-adding-a-listener-for-focus-event

**Comment by angel-discover** [comment]
copy pasting the https://github.com/react-navigation/react-navigation/pull/9434 fix and changing the getState and getParent back into dangerouslyGetState and dangerouslyGetParent worked like a charm for v5.

**Comment by anthonyguay** [comment]
https://github.com/react-navigation/react-navigation/pull/11063

**Comment by pfcodes** [comment]
Is there a clean fix to this?
