### ISSUE TITLE
After updating a few NPM packages, getting "Unable to resolve module './useFocusedListeners' in React Native app

### ISSUE THREAD

**Issue by imsam67** [react-navigation/react-navigation#8588]
In my React Native app, I just updated some outdated npm packages and now I get an error that reads:

> Error: Unable to resolve module `./useFocusedListeners` from `node_modules\@react-navigation\core\src\BaseNavigationContainer.tsx`

Here's a screen shot of the error:
![Annotation 2020-07-14 192133](https://user-images.githubusercontent.com/15844030/87492192-3edd9080-c607-11ea-9e12-70b3b97b0931.png)

Everything was working fine prior to updating npm packages. Here's a screen shot of what's been updated:
![Annotation 2020-07-14 192448](https://user-images.githubusercontent.com/15844030/87492403-bad7d880-c607-11ea-9120-b5c3fec06f16.png)

The version number for `@react-navigation/native": "^5.7.0"`

Any idea what the issue is and how to resolve it?

**Comment by imsam67** [comment]
`@react-navigation/native": "^5.7.0"`

**Comment by satya164** [comment]
https://reactnavigation.org/docs/troubleshooting

**Comment by ashishmmt** [comment]
Put someting like below in your package.json
   "start": "node node_modules/react-native/local-cli/cli.js start --port=8080 --reset-cache",

Run 'npm run start'

This solved my issue.

**Comment by Damidara16** [comment]
> Put someting like below in your package.json
> "start": "node node_modules/react-native/local-cli/cli.js start --port=8080 --reset-cache",
> 
> Run 'npm run start'
> 
> This solved my issue.

this dude is goated, is there a way to figure out how you came about that solution?

**Comment by raajnadar** [comment]
https://reactnavigation.org/docs/troubleshooting/#im-getting-an-error-unable-to-resolve-module-after-updating-to-the-latest-version

Clearing the cache worked here.

**Comment by ivanfeliciano9** [comment]
I had that same problem.
After a reser cache command it worked fine 

npx react-native start --reset-cache

see: 
https://reactnavigation.org/docs/troubleshooting/#im-getting-an-error-unable-to-resolve-module-after-updating-to-the-latest-version

**Comment by lexguy** [comment]
> > Put someting like below in your package.json
> > "start": "node node_modules/react-native/local-cli/cli.js start --port=8080 --reset-cache",
> > Run 'npm run start'
> > This solved my issue.
> 
> this dude is goated, is there a way to figure out how you came about that solution?

same as `npx react-native start --reset-cache`  
just run the cli tool in the react-native package

**Comment by JoelRummel** [comment]
For my Expo-managed project, simply running `expo start -c` fixed it for me.

**Comment by verhovensky** [comment]
For React Native 0.73 the command is
```
npx react-native start --resetCache
```
However it didn't help
