### ISSUE TITLE
@react-navigation/native Reference error in react-native initialization project

### ISSUE THREAD

**Issue by SpiritLing** [react-navigation/react-navigation#8589]
**Current Behavior**

@react-navigation/native is added according to the [official documentation](https://reactnavigation.org/docs/getting-started#installing-dependencies-into-a-bare-react-native-project)

react-native init project

`npm run android` Error

Code:

```
import React from 'react';
import {NavigationContainer} from '@react-navigation/native';
import {createStackNavigator} from '@react-navigation/stack';

import HomePage from './src/home/index';

const Stack = createStackNavigator();
export default function App() {
  return (
    <NavigationContainer>
      <Stack.Navigator initialRouteName="Home">
        <Stack.Screen name="Home" component={HomePage} />
      </Stack.Navigator>
    </NavigationContainer>
  );
}

```

Error:

```
Error: While trying to resolve module `@react-navigation/native` from file `D:\TestProject\rnorigin01\App.jsx`, the package `D:\TestProject\rnorigin01\node_modules\@react-navigation\native\package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`D:\TestProject\rnorigin01\node_modules\@react-navigation\native\src\index.tsx`. Indeed, none of these files exist:
```

**Expected Behavior**

It should work fine

**How to reproduce**

`@react-navigation/native` Error

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | android |
| @react-navigation/native       | 5.7.0 |
| react-native                   | 0.63.1 |
| expo                           |  None |
| node                           | 10.15.3 |
| yarn                    | 1.22.4 |

**Comment by satya164** [comment]
https://reactnavigation.org/docs/troubleshooting/
