### ISSUE TITLE
Bottom tabs jumping on load first time

### ISSUE THREAD

**Issue by bilalqaimkhani** [react-navigation/react-navigation#8590]
**Current Behavior**

- What code are you running and what is happening?
- Include a screenshot or video if it makes sense.

**Expected Behavior**

- What do you expect should be happening?
- Include a screenshot or video if it makes sense.

**How to reproduce**

- You must provide a way to reproduce the problem. If you are having an issue with your machine or build tools, the issue belongs on another repository as that is outside of the scope of React Navigation.
- Either re-create the bug on [Snack](https://snack.expo.io) or link to a GitHub repository with code that reproduces the bug.
- Explain how to run the example app and any steps that we need to take to reproduce the issue from the example app.
- Keep the repro code as simple as possible, with the minimum amount of code required to repro the issue.
- Before reporting an issue, make sure you are on latest version of the package.

**Your Environment**

| software                      | version |
| ----------------------------- | ------- |
| iOS or Android                |10
| @react-navigation/native      |5.5.1
| @react-navigation/bottom-tabs |5.6.1
| react-native-screens          |2.0.0
| react-native                  |0.62.2
| expo                          |
| node                          |12.16.3
| npm or yarn                   |6.14.4

**Comment by bilalqaimkhani** [comment]
> The versions mentioned in the issue for the following packages differ from the latest versions on npm:
> 
> * `@react-navigation/native` (found: `5.5.1`, latest: `5.7.0`)
> * `@react-navigation/bottom-tabs` (found: `5.6.1`, latest: `5.7.1`)
> 
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?

**Comment by bilalqaimkhani** [comment]
> The versions mentioned in the issue for the following packages differ from the latest versions on npm:
> 
> * `@react-navigation/native` (found: `5.5.1`, latest: `5.7.0`)
> * `@react-navigation/bottom-tabs` (found: `5.6.1`, latest: `5.7.1`)
> 
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?

i have tried to upgrade the versions as you mentioned but still i am getting same issue

**Comment by anhquan291** [comment]
Same issue here. I already upgraded all the packages to the latest version. Thanks in advance!
