### ISSUE TITLE
the default back icon is too small on android tablet

### ISSUE THREAD

**Issue by dev-ahmed** [react-navigation/react-navigation#8593]
**Current Behavior**

![image](https://user-images.githubusercontent.com/15056155/87600956-74ac7300-c6f4-11ea-8bc8-91a88521701d.png)

**Expected Behavior**

- icon has same size on all platforms 

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| Android                 |  10
| @react-navigation/native       | 5.1.5
| @react-navigation/stack        | 5.1.1
| react-native-gesture-handler   | 1.6.1
| react-native-safe-area-context | 0.7.3
| react-native-screens           | 2.4.0
| react-native                   | 0.61.5
| expo                           |
| node                           | 14.5.0
| yarn                    | 1.22.4

**Comment by dev-ahmed** [comment]
i upgraded the versions mentioned here to the latest and still the same

**Comment by dev-ahmed** [comment]
any updates about this ?

**Comment by satya164** [comment]
If you have custom header with large title, you can use custom back button. The back button size is fine compared to the default header size.
