### ISSUE TITLE
custom-navigators will render page everytimes when tab changed(lags)

### ISSUE THREAD

**Issue by Wangzihao5325** [react-navigation/react-navigation#8598]
**Current Behavior**

i use custom navigators like: https://reactnavigation.org/docs/custom-navigators/#api-for-building-custom-navigators
but i found that it will render page everytimes when tab changed, and lags.

as navigators create by createBottomTabNavigator() will not render page everytime, and not lags.
how can i decrease render in custom navigators?

sorry for my poor english.

**Your Environment**

| software                      | version |
| ----------------------------- | ------- |
| iOS or Android                | both
| @react-navigation/native      |
| @react-navigation/bottom-tabs | 5.3.1
| react-native-screens          |
| react-native                  | 0.62.2
| expo                          |
| node                          |
| npm or yarn                   |

**Comment by Wangzihao5325** [comment]
use ScreenContainer in react-native-screens like BottomTabView.tsx
```
            <ScreenContainer style={styles.pages}>
              {routes.map((route, index) => {
                const descriptor = descriptors[route.key];
                const { unmountOnBlur } = descriptor.options;
                const isFocused = state.index === index;

                if (unmountOnBlur && !isFocused) {
                  return null;
                }

                if (lazy && !loaded.includes(index) && !isFocused) {
                  // Don't render a screen if we've never navigated to it
                  return null;
                }

                return (
                  <ResourceSavingScene
                    key={route.key}
                    style={StyleSheet.absoluteFill}
                    isVisible={isFocused}
                  >
                    <SceneContent isFocused={isFocused}>
                      {descriptor.render()}
                    </SceneContent>
                  </ResourceSavingScene>
                );
              })}
            </ScreenContainer>
```

**Comment by wzahedi** [comment]
Unfortunately this remains unsolved for me. Did you try anything else to fix this? @Wangzihao5325
