### ISSUE TITLE
React navigation website is down

### ISSUE THREAD

**Issue by VivekNeel** [react-navigation/react-navigation#8605]
**Current Behavior**
when navigating to https://reactnavigation.org/ , website does not load
**Expected Behavior**
website should load on both chrome and safari

**How to reproduce**

- Go to https://reactnavigation.org/ 

![image](https://user-images.githubusercontent.com/5962275/87848806-038ddb00-c901-11ea-8f25-7f1301ec2292.png)

**Comment by wmonecke** [comment]
Why are you opening this as an issue here?

**Comment by raajnadar** [comment]
The webpage is live!
