### ISSUE TITLE
getCurrentRoute() does not work on nested independant navigators

### ISSUE THREAD

**Issue by KristineTrona** [react-navigation/react-navigation#8611]
**Current Behavior**

Following the guide https://reactnavigation.org/docs/screen-tracking/ it should be possible to get current route with ``navigationRef.current.getCurrentRoute()``, while this works on a top level navigator it does not seem to work with a nested navigator with the ``independent`` prop and returns 'undefined'

**Expected Behavior**

``navigationRef.current.getCurrentRoute()`` should return current route.

**Environment**

@react-navigation/native: 5.7.1

**Comment by satya164** [comment]
This is what the error says if you have nested `NavigationContainer`:

> Looks like you have nested a 'NavigationContainer' inside another. Normally you need only one container at the root of the app, so this was probably an error. If this was intentional, pass 'independent={true}' explicitly. Note that this will make the child navigators disconnected from the parent and you won't be able to navigate between them.

So it's expected that if you have independent navigation containers, parent container is disconnected from child container and isn't going to give you nested state from there.

Basically, why are you using nested `NavigationContainer` with `independent`? Have only one container at the root.

**Comment by KristineTrona** [comment]
@satya164 in my use case I have a complex modal structure which makes sense to create a new nested navigator to navigate between the different components within a modal. 

Also I am not trying to get the currentRoute of parent navigator, but of the nested one. I would expect that assigning a reference to the nested navigator and calling ``navigatorRef.current.getCurrentRoute()`` would return the current route of the nested navigator, not undefined.

**Comment by satya164** [comment]
You don't need to use multiple `NavigationContainer` for nested navigators. Like the error and docs say, you should have only one `NavigationContainer` at root of the app, that doesn't mean that you can't have nested navigators.

**Comment by KristineTrona** [comment]
Then why give the option for creating independent ``NavigationContainer``? All normal methods of the nested ``NavigatorContainer``, like navigate, push etc. work as expected, but the recently added ``getCurrentRoute()`` returns undefined. If you don't want to provide the method to independent nested ``NavigationContainer`` it would be better to remove it all together rather than offering it and not returning what is expected, still seems like a buggy behaviour to me.

**Comment by satya164** [comment]
The prop is there for complex use cases such as hybrid apps. The message clearly says what will happen if you use `independent` container. Regardless, you're not supposed to use random props blindly and then complain that it does what it said it'll do.

**Comment by taras-danyliuk** [comment]
@KristineTrona, were you able to find workarounds for this one?

@satya164 `You don't need to use multiple NavigationContainer for nested navigators` is not an answer for a question `Why it returns undefined?`

**Comment by KristineTrona** [comment]
No, I ended up using a different structure for my project, this would have been handy though.
