### ISSUE TITLE
navigationRef.current.getCurrentRoute().name doesn't return the drawer screen name (or how to track drawer analytics)

### ISSUE THREAD

**Issue by MikePendo** [react-navigation/react-navigation#8612]
**Current Behavior**

I am trying to get screen analytics when the drawer gets open according to [Screen tracking](https://reactnavigation.org/docs/screen-tracking/)
_onStatusChange_ get called but then I would like to have `navigationRef.current.getCurrentRoute().name` or the key of but constantly get the screen under it  (I guess I will need to wrap the navigator in the stack - but its not documented and sound a little bit redundant )

**Expected Behavior**
`navigationRef.current.getCurrentRoute().name`
can have the Screen name or the reference to the drawer when it gets opened
**How to reproduce**

```
const Drawer = createDrawerNavigator();

function MyDrawer() {

  return (
    <Drawer.Navigator drawerType="front" drawerPosition="left">
      <Drawer.Screen name="Properties" component={PropertiesTabs} />
      <Drawer.Screen name="Profile" component={Profile} />
    </Drawer.Navigator>
  );
}
```
and then wrap in in NavigationContainer,  try to track the drawer from the state when _onStatusChange_ get called 

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |
| @react-navigation/native       |5.7.1
| react-native                   |0.61.5
| expo                           |NAN
| node                           |13.10.1
| yarn                    |1.22.1

**Comment by satya164** [comment]
What do you mean by "but constantly get the screen under it"? `getCurrentRoute` returns the current route name of the focused screen in the navigation tree. If you want to track screen in a specific navigator, you need to look through the state object you receive in `onStateChange`.

**Comment by MikePendo** [comment]
`onStateChange` doesnt has reference to the drawer,
