### ISSUE TITLE
Invariant Violation: Tried to register two views with the same name RNCSafeAreaProvider

### ISSUE THREAD

**Issue by HoaiHuynh** [react-navigation/react-navigation#8617]
I have an issue when I import this.
import { NavigationContainer } from '@react-navigation/native';
import { createBottomTabNavigator } from '@react-navigation/bottom-tabs';
How can I solve that issue. Thank guy

**Comment by satya164** [comment]
https://github.com/th3rdwave/react-native-safe-area-context/issues/110#issuecomment-662580557

**Comment by ShauryaKharb** [comment]
Found the ULTIMATE SOLUTION
![Screenshot_2021_1019_111215](https://user-images.githubusercontent.com/73641410/137850991-f7daf424-cdc1-48a6-b567-856936a71262.jpg)
Under Call Stack in the second `<global>` tag you can see SafeAreaContext.js
Which means that there is a version mismatch in this dependency
And in the seventh `<global>` tag 
It is written createStackNavigator.txs which indicates that this dependency uses safe area context, whose version does not match to the safe areas context you already have

DIRECT SOLUTION :
just Install the dependency under in the second <global> tag with 
`expo install <dependency-name>`
