### ISSUE TITLE
Video continues to play after navigating to other screens

### ISSUE THREAD

**Issue by mikeRChambers610** [react-navigation/react-navigation#8618]
**Current Behavior**

I am using react navigation version 4 (bug applies to all versions) createStackNavigation and createBottomTabNavigation.
When I have a video on any page and I navigate to another page, the video from the previous pages continues to play. This seems like a very simple use case and I am surprised that there are issues here. 

**Expected Behavior**

When navigating from one screen to another, the video on the previous screen should stop playing.

**How to reproduce**

Create a tab navigator with a stack navigator inside of one of the tab screens. Add video to the tab screens and then navigate through the stack navigator. There seems to be many ways to reproduce this issue. If more detail or the actual code is needed please let me know.

**Your Environment**

| software                       | version |
    "expo": "^38.0.0",
    "react-native": "0.62",
    "react-navigation": "^4.4.0",
    "react-navigation-addons": "0.0.0",
    "react-navigation-drawer": "^2.5.0",
    "react-navigation-stack": "^2.8.2",
    "react-navigation-tabs": "^2.9.0",

**Comment by vukzrito** [comment]
I'm experiencing the opposite, on Android 10 video stops when navigating to another screen. I actually want it to continue playing even when on another screen.
react-native-video : 4.4.5
react-navigation/bottom-tabs: 5.2.6
react-native : 0.62.2

**Comment by satya164** [comment]
https://reactnavigation.org/docs/4.x/navigation-lifecycle
