### ISSUE TITLE
[Android] Header adjust when initial load

### ISSUE THREAD

**Issue by preflower** [react-navigation/react-navigation#8620]
**Current Behavior**

- header adjust when initial load
![Screenrecording_20200722_171538](https://user-images.githubusercontent.com/30513719/88159189-8be0e880-cc3f-11ea-8459-49a3fbe4f9fa.gif)

**How to reproduce**

```
import * as React from 'react';
import {View, Text} from 'react-native';
import {NavigationContainer} from '@react-navigation/native';
import {createStackNavigator} from '@react-navigation/stack';

function HomeScreen() {
  return (
    <View style={{flex: 1, alignItems: 'center', justifyContent: 'center'}}>
      <Text>Home Screen</Text>
    </View>
  );
}

const Stack = createStackNavigator();

function App() {
  return (
    <NavigationContainer>
      <Stack.Navigator>
        <Stack.Screen name="Home" component={HomeScreen} />
      </Stack.Navigator>
    </NavigationContainer>
  );
}

export default App;
```

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
|IOS or Android                 | Android
| @react-navigation/native       | 5.7.1
| @react-navigation/stack        | 5.7.1
| react-native-gesture-handler   |  1.6.1
| react-native-safe-area-context | 3.1.1
| react-native-screens           | 2.9.0
| react-native                   | 0.63.1
| expo                           |
| node                           |
| npm or yarn                    | npm

**Comment by adhax** [comment]
Related to [#8446](https://github.com/react-navigation/react-navigation/issues/8446)

**Comment by satya164** [comment]
Closing since there's no repro.
