### ISSUE TITLE
Warning: Cannot update a component from inside the function body of a different component.

### ISSUE THREAD

**Issue by cristianoccazinsp** [react-navigation/react-navigation#8621]
**Current Behavior**
After the most recent updates, a new warning is now logged each time we try to call `navigation.setParams` on a class-based component constructor.

**Expected Behavior**
No warning should be issued (just like before the update), unless this is actually a usage bug and we are not supposed to update the navigator route params in a constructor? Should such calls get moved to `componentDidMount` instead? 

**How to reproduce**
```
class SomeComponent extends React.Component {

  constructor(props) {
    super(props);
    this.state = {
    }

    this.props.navigation.setParams({
      'test': "test"
    });
  }
}
```

Repro: https://github.com/cristianoccazinsp/react-navigation-bugtest

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | both
| @react-navigation/native       | 5.7.1
| react-native                   | 0.63.2
| expo                           | none
| node                           | 12.16.3
| npm or yarn                    | npm 6.14.4

**Comment by cristianoccazinsp** [comment]
Was a typo, it's indeed 5.7.1

**Comment by xesf** [comment]
I just updated to the new version and start having the same issue.

Since I am using funcional components I am getting the error on a different place, but related.

Issue is identified under useNavigationCache.tsx under
`setOptions: (options: object) =>
            setOptions((o) => ({
              ...o,
              [route.key]: { ...o[route.key], ...options },
            })),`

**Comment by xesf** [comment]
@cristianoccazinsp on your error above, you have to do it on the mount event instead of constructor and that should work.

**Comment by cristianoccazinsp** [comment]
@xesf  I know that.  However, it used to work fine until recently.  I wonder if this is a warning for a previously wrong behaviour, or just a new useless warning.  If it is definitely wrong behaviour, then I should refactor the code, but it used to work fine without warnings until recently.

**Comment by xesf** [comment]
Yeah, it looks like its a warning for a wrong behaviour. I would suggest refactoring the code.
I will do the same on my side :)

**Comment by mxhryvo** [comment]
Same here, this is new behavior of react-navigation since one of the last updates. We did no changes on our side, except upgrading to the latest version (5.7.1). We are using `setOptions` to change the title of the screen on render.

**Comment by satya164** [comment]
React Navigation isn't warning you. The warning comes from React. You are updating params/options in constructor/render which React warns against, since it updates state of parent component.

This means your code is not correct and you need to refactor it. `setParams`/`setOptions` etc. should only be called in `useEffect`/`useLayoutEffect`/`componentDidMount`/`componentDidUpdate` etc. Not during render or in constructor.

**Comment by cristianoccazinsp** [comment]
Hmmm, while I do agree that the constructor shouldn't be doing side effect calls, this was definitely introduced in an update. 

However, after further testing and refactoring to use `componentDidMount`, I still seem to be getting the warning/error from somewhere... Will dig further.

**Comment by cristianoccazinsp** [comment]
Well, looks like react-redux (or at least components that are connected) will also raise this warning, sigh.

**Comment by satya164** [comment]
In your other issue, you had linked to issue about the exact same warning in React Native repo. This is an issue with the React version in React Native that even componentDidMount produces warning. You should post it there instead of on React Navigation repo. There's nothing React Navigation can do about a warning which comes from React.

**Comment by mistersunshine20** [comment]
FWIW I had the same warning, and following satya's advice of moving navigation.setOptions() into useEffect() removed the warning for my program.

**Comment by mostafero** [comment]
Do not change navigation properties in the constructor, and best way is to use componentdidmount:
```
export default class CustomScreen extends Component {
  init() {
    const {route, navigation} = this.props;
    const custom_param = route.params.custom_param; // 
    navigation.setOptions({title: custom_param});
  }

  componentDidMount() {
    this.init(); // here is the right place to change header title for example (title is just an example here you can change other properties ofc)
  }

  render() {
    const {route, navigation} = this.props;
    const type = route.params.type;
    return <View>
    // .....
   </View>;
  }
}
```

**Comment by DexterLawson** [comment]
> React Navigation isn't warning you. The warning comes from React. You are updating params/options in constructor/render which React warns against, since it updates state of parent component.
> 
> This means your code is not correct and you need to refactor it. `setParams`/`setOptions` etc. should only be called in `useEffect`/`useLayoutEffect`/`componentDidMount`/`componentDidUpdate` etc. Not during render or in constructor.

It works . Many thanks

**Comment by DexterLawson** [comment]
> Do not change navigation properties in the constructor, and best way is to use componentdidmount:
> 
> ```js
> export default class CustomScreen extends Component {
>   init() {
>     const {route, navigation} = this.props;
>     const custom_param = route.params.custom_param; // 
>     navigation.setOptions({title: custom_param});
>   }
> 
>   componentDidMount() {
>     this.init(); // here is the right place to change header title for example (title is just an example here you can change other properties ofc)
>   }
> 
>   render() {
>     return <View>
>     // .....
>    </View>;
>   }
> }
> ```

Exact

**Comment by alexkendall** [comment]
Im currently encountering this error while using navigation.setParams() inside of a react-hook. Unsure on how to solve this issue.

**Comment by xesf** [comment]
> Im currently encountering this error while using navigation.setParams() inside of a react-hook. Unsure on how to solve this issue.

It should work fine without a warning if using a useEffect/useLayoutEffect hook. Which one are you using? Are you creating the hook properly?
