### ISSUE TITLE
In createStackNavigator initialRouteName param is not dynamic

### ISSUE THREAD

**Issue by ehijon** [react-navigation/react-navigation#8624]
I have a stack navigator with multiple screens inside.
At the first app loading everything works and the `initialRouteName` brings to 'Auth' screen because is the first that I call.

Clicking the an external link. The deep link opens the app -> the console log prints the new props.dynamicScreen correctly -> BUT the initialRouteName is not updated with the new screen.

Why?
How can I load the screen from inside a StackNavigator (it does't receive the props.navigation)?

Updating the props (the console.log prints the new value correctly!), I aspect to call also the return and have a refresh of the entire navigator.

`const AuthStackNavigator = createStackNavigator();
export const AuthNavigator = props => {
  console.log(props.dynamicScreen); // prints the right value
  return (
    <AuthStackNavigator.Navigator
      initialRouteName={props.dynamicScreen}
      screenOptions={defaultStackNavOptions}>
      <AuthStackNavigator.Screen name="Auth" component={AuthScreen} />
      <AuthStackNavigator.Screen name="Login" component={LoginScreen} />
      <AuthStackNavigator.Screen
        name="InsertEmailToReset"
        component={InsertEmailToResetScreen}
      />
      <AuthStackNavigator.Screen name="Intro" component={IntroScreen} />
      <AuthStackNavigator.Screen
        name="ConfirmEmailVerified"
        component={ConfirmEmailVerifiedScreen}
        initialParams={{oobCode: props.oobCode}}
      />
      <AuthStackNavigator.Screen
        name="InsertEmail"
        component={InsertEmailScreen}
      />
      <AuthStackNavigator.Screen
        name="InsertNewPassword"
        component={InsertNewPasswordScreen}
        initialParams={{oobCode: props.oobCode}}
      />
      <AuthStackNavigator.Screen
        name="RequireEmailVerification"
        component={RequireEmailVerificationScreen}
        initialParams={{email: props.email}}
      />
    </AuthStackNavigator.Navigator>
  );
};
`

React Native 61.5
React Navigation 5

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 both
| @react-navigation/native       5.1.1
| @react-navigation/stack        5.2.3
| react-native-gesture-handler   1.5.3
| react-native-safe-area-context 0.6.2
| react-native-screens           2.4.0
| react-native                   0.61.5
| expo                           no, is a cli app

**Comment by ehijon** [comment]
Updated the versions and nothing changed, still same issue.

**Comment by ehijon** [comment]
Am I using it in the wrong way?

**Comment by markfried96** [comment]
I have the same problem...
