### ISSUE TITLE
Component behind header stack navigation

### ISSUE THREAD

**Issue by nmorales1991** [react-navigation/react-navigation#8627]
**Current Behavior**

I have a stack Navigator with border Radius option in my headerStyle prop. But behind the header a component of a gray color is displayed, this is seen in the corners that were rounded with border radius

![unknown](https://user-images.githubusercontent.com/33029335/88356122-c4aeb980-cd34-11ea-969a-637c1ed2db50.png)

**Expected Behavior**

it shouldn't show that gray background in the corners

**How to reproduce**

- npx react-native init "AwesomeProject"
- npm i all react navigation dependencies
- open genymotion
- npx react-native run-android
- add  a simple stack Navigator
- add this screen options : 
          `screenOptions={{
              headerStyle: {
                backgroundColor: 'red',
                borderBottomLeftRadius:20,
                borderBottomRightRadius:20,
              }}`

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| Emulator  Genymotion             |3.1.0
| @react-navigation/native       |^5.7.0
| @react-navigation/stack        |^5.7.0
| react-native-gesture-handler   |^1.6.1
| react-native-safe-area-context |^3.1.1
| react-native-screens           |^2.9.0
| react-native                   |0.63.1

| node                           |v12.16.2
| npm or yarn                    |6.14.4

**Comment by toantk911** [comment]
Hi @nmorales1991, I'm facing this issue now with the latest versions on iOS. Could you explain how you resolve it?

**Comment by jeremykanso** [comment]
Hi @nmorales1991 I am also facing the same issue. @toantk911 did you find a way?
