### ISSUE TITLE
How to get screen analytics when drawer gets open (in V4 it was in the state )

### ISSUE THREAD

**Issue by MikePendo** [react-navigation/react-navigation#8629]
**Current Behavior**

I am trying to get screen analytics when the drawer gets opened/close according to [Screen tracking](https://reactnavigation.org/docs/screen-tracking/)
_onStatusChange_ get called but there is no drawer state that helps to decide if the drawer was opend or closed (in V4 there was a boolean for that )

**Expected Behavior**
_onStateChange_ should have some hint whether the drawer  is opened or closed
**How to reproduce**<br>
_App.js_
```
const Drawer = createDrawerNavigator();
function MyDrawer(props) {
  return (
    <NavigationContainer onStateChange={props.onStateChange}>
      <Drawer.Navigator drawerType="front" drawerPosition="left">
        <Drawer.Screen name="Properties" component={PropertiesTabs} />
        <Drawer.Screen name="Profile" component={Profile} />
      </Drawer.Navigator>
    </NavigationContainer>
  )
};
export default with(MyDrawer)
```

_With.tsx_
```
export function with(Component: any) {
    class PNDContainer extends React.Component {
        child: any;
        componentDidMount() {
            //debugger;
            console.log('PND Mounted - First Time Screen');
        }
        componentWillUnmount() { }
        render() {
            const myHookValue = this.props.myHookValue;
            debugger;
            return (<Component onStateChange={(state) => {
                debugger;
                console.log('Screen Changed');
            }} />)
        }
    }
    return PNDContainer;
}
```

I know that it's probably possible to implement with functional components (but currently I must use Components)
**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | both
| @react-navigation/native       |5.7.1
| react-native                   |0.61.5
| expo                           |NAN
| node                           |13.10.1
| yarn                    |1.22.1
| software                       | version |
| ------------------------------ | ------- |

**Comment by satya164** [comment]
```js
onStateChange={(state) => {
  const isDrawerOpen = state.history.some((it) => it.type === 'drawer');
}
```

**Comment by night2tl** [comment]
It doesn't work for me on Android with the following dependencies: 
`
    "@react-navigation/drawer": "^5.9.0",
    "@react-navigation/native": "^5.7.3",
    "@react-navigation/stack": "^5.9.0",
    "react-native": "0.63.2"
`
With this configuration I don't have the history object on state.
