### ISSUE TITLE
Can't find variable screensEnabled

### ISSUE THREAD

**Issue by wolodo** [react-navigation/react-navigation#8630]
**Current Behavior**

Application crashes with error "Can't find variable screensEnabled" while trying to use bottom tab navigator

![Simulator Screen Shot - iPhone 8 - 2020-07-24 at 18 08 46](https://user-images.githubusercontent.com/10619680/88412587-1f4e2100-cdda-11ea-92e8-8ad0dfb43b18.png)

**Expected Behavior**

Expected behaviour is page similar to example at https://reactnavigation.org/docs/tab-based-navigation since the code of App.js is the same

**How to reproduce**

- unzip included example project
- yarn install
- expo start

Example Project: [Archive.zip](https://github.com/react-navigation/react-navigation/files/4973162/Archive.zip)

package.json is the only interesting part of the project
`

> {
> 	"main": "node_modules/expo/AppEntry.js",
> 	"scripts": {
> 		"start": "expo start",
> 		"android": "expo start --android",
> 		"ios": "expo start --ios",
> 		"web": "expo start --web",
> 		"eject": "expo eject",
> 		"build-ios-prod": "expo build:ios --release-channel prod",
> 		"build-android-prod": "expo build:android --release-channel prod",
> 		"mock": "node mock-server/server.js"
> 	},
> 	"dependencies": {
> 		"@expo/vector-icons": "^10.0.0",
> 		"@react-native-community/masked-view": "0.1.10",
> 		"@react-navigation/bottom-tabs": "^5.6.1",
> 		"@react-navigation/native": "^5.6.1",
> 		"@react-navigation/stack": "^5.6.2",
> 		"axios": "^0.19.2",
> 		"expo": "~38.0.8",
> 		"expo-camera": "~8.3.1",
> 		"expo-constants": "^9.1.1",
> 		"expo-intent-launcher": "~8.2.1",
> 		"expo-localization": "^8.2.1",
> 		"expo-permissions": "~9.0.1",
> 		"expo-status-bar": "^1.0.2",
> 		"i18n-js": "^3.7.1",
> 		"prop-types": "^15.7.2",
> 		"react": "~16.11.0",
> 		"react-dom": "~16.11.0",
> 		"react-native": "https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz",
> 		"react-native-gesture-handler": "~1.6.0",
> 		"react-native-keyboard-aware-scrollview": "^2.1.0",
> 		"react-native-keyboard-spacer": "^0.4.1",
> 		"react-native-paper": "^3.10.1",
> 		"react-native-reanimated": "~1.9.0",
> 		"react-native-safe-area-context": "~3.0.7",
> 		"react-native-screens": "~2.9.0",
> 		"react-native-table-component": "^1.2.1",
> 		"react-native-view-shot": "3.1.2",
> 		"react-native-web": "~0.11.7",
> 		"react-navigation": "^4.4.0",
> 		"react-redux": "^7.2.0",
> 		"redux": "^4.0.5",
> 		"redux-thunk": "^2.3.0"
> 	},
> 	"devDependencies": {
> 		"@babel/core": "^7.8.6",
> 		"babel-eslint": "^10.1.0",
> 		"babel-preset-expo": "~8.1.0",
> 		"eslint": "^7.4.0",
> 		"eslint-plugin-react": "^7.20.3",
> 		"eslint-plugin-react-native": "^3.8.1"
> 	},
> 	"private": true

}
`

**Your Environment**

| software                      | version |
| ----------------------------- | ------- |
| iOS or Android                |iOS
| @react-navigation/native      |^5.6.1
| @react-navigation/bottom-tabs |^5.6.1
| react-native-screens          |~2.9.0
| react-native                  |https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz
| expo                          |~38.0.8
| node                          |v10.20.1
| npm or yarn                   | yarn

**Comment by wolodo** [comment]
update to newest versions of bottom-tabs, native and stack did not make any difference

**Comment by raajnadar** [comment]
Did you install this dependencies https://reactnavigation.org/docs/getting-started#installing-dependencies-into-a-bare-react-native-project

**Comment by wolodo** [comment]
> Did you install this dependencies https://reactnavigation.org/docs/getting-started#installing-dependencies-into-a-bare-react-native-project

Yes, I did. You can see them in package.json,I included. Interesting fact is, that it worked so far. Problems started just yesterday. 
Maybe something related to expo? Or some incompatible combination with other dependencies?

**Comment by satya164** [comment]
You repro runs without error.

**Comment by wolodo** [comment]
Looks like, the problem is `transform-optional-chaining` plugin. When present in `babel.config.js`, the error occours.

Better example here: https://github.com/wolodo/expo-example

**Comment by sheyooo** [comment]
I had `transform-optional-chaining` also, I have removed it but still getting the error.

**Comment by wolodo** [comment]
> I had `transform-optional-chaining` also, I have removed it but still getting the error.

try to clear cache by calling `expo start -c`

**Comment by satya164** [comment]
The expo babel preset and React Native babel preset already include optional chaining by default, so it's unnecessary to include it again.

Anyway, React Navigation works fine with default babel config, so I'm closing the issue. If you change the config, be aware that it can break other packages and don't change what you don't need to.
