### ISSUE TITLE
headerBackground is transparent when Stack is nested and headerShown set to false

### ISSUE THREAD

**Issue by mafiusu** [react-navigation/react-navigation#8632]
**Current Behavior**

I want to use [headerBackground](https://reactnavigation.org/docs/stack-navigator/#headerbackground) for my Stack Screen. It's working good but at this specific case, a transparent header is shown.

Actually I've a StackNavigator (AuthStack) with headerShown: false. There I render several Stack Screens like SignIn, SignUp and Onboarding. And now in my Onboarding Stack I use the headerBackground style option for a Stack Screen. It doesn't show the backgroundImage, instead it's transparent. If I remove headerBackground, it's renders a normal StackHeader

I'm curious because if the AuthStack has the screenOptions to headerShown: true the backgroundImage is rendered correct BUT the headers are shown 2x times! 

This is the following code 
AuthStack
![carbon-2](https://user-images.githubusercontent.com/33623047/88454099-283c0280-ce6d-11ea-820a-9fbf81d1e653.png)

OnboardingStack
![carbon-3](https://user-images.githubusercontent.com/33623047/88454122-57eb0a80-ce6d-11ea-96c3-22d256150c2f.png)

Here you can the the transparent problem. In the header you see the underlaying screen because it's transparent.
![Simulator Screen Shot - iPhone X - 2020-07-25 at 11 57 07](https://user-images.githubusercontent.com/33623047/88454182-02632d80-ce6e-11ea-86e0-8731dd4516df.png)

**Expected Behavior**

I expect normal behavior from headerBackground when a Stack is nested.

**How to reproduce**

https://snack.expo.io/eEjr!IZUj

**Your Environment**
| iOS or Android                 iOS
| @react-navigation/native       ^5.2.1
| @react-navigation/stack        5.2.16
| react-native-gesture-handler   ~1.6.0
| react-native-safe-area-context ~3.0.7
| react-native-screens           ~2.9.0
| react-native                   sdk-38 (expo)
| expo                           sdk-38
| node                           |
| npm or yarn                    yarn

**Comment by mafiusu** [comment]
The bug still exist after upgrading to the lates version 5.7.1 of native and stack.

**Comment by mafiusu** [comment]
@satya164 I've created a repro with snack.expo

**Comment by satya164** [comment]
It's because you're using `HeaderHeightContext` inside header background which is `0` (height of parent header). Just set the height to `100%` instead.
