### ISSUE TITLE
Recognise the first route name for analytics 

### ISSUE THREAD

**Issue by MikePendo** [react-navigation/react-navigation#8633]
**Current Behavior**

I am trying to get screen analytics when the app launch [Screen tracking](https://reactnavigation.org/docs/screen-tracking/)
_onStatusChange_  doesn't get called when the app launch so my options are to use _componentDidMount_ OR _onReady_
BUT in both cases, I can't get the navigation state that I do receive in _onStatusChange_. Please suggest any other option

**Expected Behavior**
_onStateChange_ should be  called on the first screen/app launch
**How to reproduce**<br>
_App.js_
```
const Drawer = createDrawerNavigator();
function MyDrawer(props) {
  return (
    <NavigationContainer onStateChange={props.onStateChange}>
      <Drawer.Navigator drawerType="front" drawerPosition="left">
        <Drawer.Screen name="Properties" component={PropertiesTabs} />
        <Drawer.Screen name="Profile" component={Profile} />
      </Drawer.Navigator>
    </NavigationContainer>
  )
};
export default with(MyDrawer)
```

_With.tsx_
```
export function with(Component: any) {
    class PNDContainer extends React.Component {
        child: any;
        componentDidMount() {
            //debugger;
            console.log('PND Mounted - First Time Screen no state ');
        }
        componentWillUnmount() { }
        render() {
            const myHookValue = this.props.myHookValue;
            debugger;
            return (<Component onStateChange={(state) => {
                debugger;
                console.log('Screen Changed');
            }} />)
        }
    }
    return PNDContainer;
}
```

I know that it's probably possible to implement with functional components (but currently I must use Components)
**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | both
| @react-navigation/native       |5.7.1
| react-native                   |0.61.5
| expo                           |NAN
| node                           |13.10.1
| yarn                    |1.22.1
| software                       | version |
| ------------------------------ | ------- |

**Comment by night2tl** [comment]
But this is something a developer of this library would answer a lot quicker than stackoverflow. 
In Stackoverflow similiar questions have been posted without any answers.

**Comment by MikePendo** [comment]
More or less the same issues with no proper answer
[Screen tracking instructions don't cover initial route](https://github.com/react-navigation/react-navigation/issues/5643)
[Screen tracking and analytics for the first page](https://github.com/react-navigation/react-navigation/issues/1150l)
