### ISSUE TITLE
Authentication flows   reset   or   clear   cache

### ISSUE THREAD

**Issue by hxzAugustinus** [react-navigation/react-navigation#8639]
**Authentication flows**
```
<NavigationContainer>
{state.userToken == null ? (
 <LoginStack.Navigator headerMode={'none'}>
      <LoginStack.Screen name="Login1" component={LoginTel} />
      <LoginStack.Screen name="Login2" component={LoginPwd} />
    </LoginStack.Navigator>
) : (
 <Tab.Navigator>
       <Tab.Screen name="Home" component={TabHome} />
       <Tab.Screen name="Profile" component={TabProfile} />
 </Tab.Navigator>
)}
</NavigationContainer>
```
navigation  route :   Login1  -> Login2  ->  change  userToken  ->  Home
when  i  change  userToken  to  null  ,  i   go  to   Login2 ,  in  fact  i want   Login1 
so   how  can  i    reset  LoginStack   or   make   it  no  cache  

 enviroment:
@react-navigation/native : "^5.6.1"

**Comment by hxzAugustinus** [comment]
@react-navigation/native : "^5.6.1"

**Comment by hxzAugustinus** [comment]
yes

**Comment by hxzAugustinus** [comment]
already   fixed

**Comment by xhw1993** [comment]
> already fixed

how do you fix it, could you please help me

**Comment by temharay** [comment]
@hxzAugustinus how did you fix it please?

**Comment by pedromcunha** [comment]
Also having this issue if anyone can provide a fix, I can provide a mcve although I believe this repo basically represents the issue. https://github.com/italoiz/react-navigation-reset-bottom-tabs-logout
