### ISSUE TITLE
Preloading HeaderBackButton for offline app support

### ISSUE THREAD

**Issue by summerkiflain** [react-navigation/react-navigation#8640]
**Current Behavior**

- HeaderBackButton imported from `react-navigation-stack` doesn't load for offline app, shows empty space in-place of header back image

**Expected Behavior**

- Their should be a way to bundle headerBackButton image assets easily for offline first apps, a list of image assets with paths for bundleAssets should be provided based on Platform.OS, or a fallBack icon should be provided to load in-place of those images if app starts in offline and navigation couldn't load those default image assets

**How to reproduce**

- Just add `import { HeaderBackButton } from 'react-navigation-stack'` to any template to use it in the view and try to start the app without internet on first load, header back arrow will not be visible.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
iOS or Android | both
react-navigation | 4.1.1
react-navigation-stack | 1.10.3
react-navigation-tabs | 2.7.0
react-navigation-drawer | 2.3.3
react-native-reanimated | 1.4.0
react-native-gesture-handler | 1.5.0
react-native-safe-area-context |  
react-native-screens | 2.0.0-alpha.12
react-native | https://github.com/expo/react-native/archive/sdk-36.0.1.tar.gz
expo | 36.0.0
node | 12.16.1
npm or yarn | yarn 1.22.0

**Why I created this issue again**
Because I think its a bug, react-navigation is suppose to handle all offline cases also, Its not possible that team overlook an important core feature to be just for online, and there is no docs on how to preload navigation assets for offline apps. Previous issue was closed by a contributor without providing a solution to the problem, I hope he doesn't do it this time. I have seen other issues also where this guy is closing others issues without giving a response or a solution.

Regards to everyone reading.

**Comment by raajnadar** [comment]
Are you serious why will a navigation library cache files?? It is your team's responsibility to know how they can cache the file.

> I hope he doesn't do it this time. I have seen other issues also where this guy is closing others issues without giving a response or a solution.

This is GitHub issues, it is used to track issues & bugs and this is not for Q&A so don't expect answers for your question here. You can post your questions in stackoverflow or discord.

**Comment by summerkiflain** [comment]
@raajnadar where are you getting your cache ideas? have you seen the word cache in my description?, read carefully the `Expected Behavior` part, Its a question of bundling assets with the build or providing fallback component for offline apps.
it should be mentioned in the docs also on how to bundle navigation assets with the build for offline apps. it could be major read for users who want to use react-navigation in their offline apps, if its not suppose to be like that or react-navigation is suppose to change the way assets are used or are going to be used in future, that should be mentioned also, we don't want to  bundle assets imported from the third-party library which may change the paths or names of the files in future, that could break the offline functionality of the app or UI of it again.

**Comment by raajnadar** [comment]
> When you want something offline (or it should not be downloaded again & again) we usually call it as caching.

React navigation is a navigation library, how can you expect react navigation to bundle your assets. You need to configure it manually and metro will do the job. And why should we document it when it is not related to navigation.

I didn't use v4 from long time in v5 my assets gets cached properly I use vanilla RN.

**Comment by summerkiflain** [comment]
Dude when the app is starting first time with an internet connection it downloads all assets and cache them so that it doesn't have to download on every launch, but when the app is starting for first time without an Internet connection there is nothing to be cached, thats when only bundled assets show up because those come bundled with the binaries, and offline app are supposed to be used without Internet so there is no question of cache only bundled assets can solve the problem or a fallback component that shows up in place of back arrows if those assets are not loaded through Internet.
If you haven't seen this in action before, delete your expo app from ur fone, install in again from store, turn of ur wifi, data or any other Internet access on device and start the app, see what assets show up on ur app in offline. if not bundled with binary those won't show up.

**Comment by raajnadar** [comment]
If you use expo post it in their forums how to bundle and it pretty straight forward you need to pass some values in app.json.

**Comment by summerkiflain** [comment]
I know how to bundle assets with binaries, Solution would be to expose the navigation assets names / paths from the library to be used for bundling, I just don't it to break if in future if react-navigation decides to changes the names or paths of the assets.

**Comment by brentvatne** [comment]
every expo app template includes an `assetBundlePatterns` config that will bundle all images with the binary, so that will be handled by default. in expo client, you can do something like this: https://github.com/react-navigation/react-navigation/blob/1e813dfb5be34eb0ee1414addf194295aa7b1e96/example/App.tsx#L3-L8
