### ISSUE TITLE
Unrecognised Operator min error

### ISSUE THREAD

**Issue by ashutosh37** [react-navigation/react-navigation#8643]
**Current Behavior**

- What code are you running and what is happening?
- Include a screenshot or video if it makes sense.

**Expected Behavior**

- What do you expect should be happening?
- Include a screenshot or video if it makes sense.

**How to reproduce**

- You must provide a way to reproduce the problem. If you are having an issue with your machine or build tools, the issue belongs on another repository as that is outside of the scope of React Navigation.
- Either re-create the bug on [Snack](https://snack.expo.io) or link to a GitHub repository with code that reproduces the bug.
- Explain how to run the example app and any steps that we need to take to reproduce the issue from the example app.
- Keep the repro code as simple as possible, with the minimum amount of code required to repro the issue.
- Before reporting an issue, make sure you are on latest version of the package.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |
| @react-navigation/native       |
| @react-navigation/drawer       |
| react-native-reanimated        |
| react-native-gesture-handler   |
| react-native-safe-area-context |
| react-native-screens           |
| react-native                   |
| expo                           |
| node                           |
| npm or yarn                    |

**Comment by viniciusfreitasrj17** [comment]
Also have this error, look:

    "@react-native-community/masked-view": "^0.1.10",
    "@react-navigation/bottom-tabs": "^5.7.3",
    "@react-navigation/drawer": "^5.8.7",
    "@react-navigation/native": "^5.7.2",
    "@react-navigation/stack": "^5.8.0",
    "expo": "~38.0.8",
    "expo-status-bar": "^1.0.2",
    "react": "~16.11.0",
    "react-dom": "~16.11.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz",
    "react-native-gesture-handler": "^1.7.0",
    "react-native-reanimated": "^1.10.1",
    "react-native-safe-area-context": "^3.1.1",
    "react-native-screens": "^2.9.0",
    "react-native-web": "~0.11.7"

expo-cli 3.22.3

**Comment by Dao123-hash** [comment]
same error facing

**Comment by Dao123-hash** [comment]
Can anyone solve it?

**Comment by viniciusfreitasrj17** [comment]
I just solved, remove react-native-safe-area-context in version ^3.1.1 and change it to 0.7.3

Also sdk 38 change to 37

**Comment by dipamsen** [comment]
@viniciusfreitasrj17 how to do that in expo-cli?

**Comment by fweakid305** [comment]
I'm also having the same issue

**Comment by viniciusfreitasrj17** [comment]
Also I does this changes:

"@react-native-community/masked-view":    ^0.1.10 chenge to  0.1.6,
"react-native-gesture-handler":     ^1.7.0 chenge to ~1.6.0,
"react-native-reanimated":     ^1.10.1 chenge to ~1.7.0,

Expo in my smartphone version: 2.16.1

**Comment by fweakid305** [comment]
"@react-native-community/masked-view": "^0.1.6",
    "@react-navigation/native": "^5.7.2",
    "@react-navigation/stack": "^5.8.0",
    "expo": "~37.0.0",
    "expo-status-bar": "^1.0.2",
    "react": "~16.11.0",
    "react-dom": "~16.11.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz",
    "react-native-gesture": "^0.2.0",
    "react-native-gesture-handler": "^1.6.0",
    "react-native-reanimated": "^1.7.0",
    "react-native-redash": "^14.2.3",
    "react-native-safe-area-context": "^0.7.3",
    "react-native-screens": "^2.9.0",
    "react-native-web": "^0.11.7"

Ive done this and still got error

**Comment by redvelvet-fan** [comment]
@viniciusfreitasrj17 

can you show your dependencies which in your package.json?

**Comment by adnaan2328** [comment]
still getting error !!!

**Comment by adnaan2328** [comment]
"dependencies": {
    "@expo-google-fonts/raleway": "^0.1.0",
    "@logisticinfotech/react-native-animated-alert": "^1.0.9",
    "@react-native-community/checkbox": "^0.4.2",
    "@react-native-community/masked-view": "^0.1.7",
    "@softmedialab/react-native-material-textfield": "^0.16.18",
    "expo": "~37.0.3",
    "expo-asset": "~8.1.3",
    "expo-av": "^8.3.0",
    "expo-facebook": "~8.1.0",
    "expo-file-system": "^9.0.1",
    "expo-firebase-recaptcha": "^1.1.0",
    "expo-google-app-auth": "^8.1.0",
    "expo-image-picker": "^8.3.0",
    "firebase": "^7.14.0",
    "native-base": "^2.13.8",
    "react": "~16.9.0",
    "react-dom": "~16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz",
    "react-native-animatable": "^1.3.3",
    "react-native-animated-linear-gradient": "^1.2.2",
    "react-native-autocomplete-input": "^4.1.0",
    "react-native-awesome-alerts": "^1.3.3",
    "react-native-calendars": "^1.265.0",
    "react-native-dropdownalert": "^4.3.0",
    "react-native-elements": "^1.2.7",
    "react-native-gesture-handler": "~1.6.0",
    "react-native-gifted-chat": "^0.16.3",
    "react-native-image-slider-box": "^1.0.12",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-loading-spinner-overlay": "^1.1.0",
    "react-native-maps": "^0.27.1",
    "react-native-material-cards": "^1.0.15",
    "react-native-material-textfield": "^0.16.1",
    "react-native-paper": "^3.10.1",
    "react-native-phone-call": "^1.0.9",
    "react-native-popup-dialog": "^0.18.3",
    "react-native-qrcode": "^0.2.7",
    "react-native-qrcode-generator": "^1.2.2",
    "react-native-qrcode-svg": "^6.0.6",
    "react-native-reanimated": "^1.10.1",
    "react-native-safe-area-context": "0.7.3",
    "react-native-screens": "^2.4.0",
    "react-native-snackbar-component": "^1.1.10",
    "react-native-svg": "^12.1.0",
    "react-native-timeago": "^0.5.0",
    "react-native-video-player": "^0.10.1",
    "react-native-web": "~0.11.7",
    "react-native-webview": "^9.4.0",
    "react-navigation": "^4.3.7",
    "react-navigation-drawer": "^2.4.11",
    "react-navigation-material-bottom-tabs": "^2.3.0",
    "react-navigation-stack": "^2.3.11",
    "react-navigation-tabs": "^2.8.11",
    "react-qr-code": "^1.0.2",
    "uuid": "^7.0.3"
  }

**Comment by dipamsen** [comment]
someone help me on this

**Comment by dipamsen** [comment]
@viniciusfreitasrj17  I did what you told and now i am getting this error
```
Unable to resolve "./useValue" from "node_modules\react-native-reanimated\src\Animated.js"
```

**Comment by dipamsen** [comment]
why is this issue closed???

**Comment by VKBobyr** [comment]
Seems like it has something to do with the new Expo update. Possible connected to the `react-native-reanimated`

**Comment by AsterModi** [comment]
I am also have same issue, Any body have any solutions

**Comment by AsterModi** [comment]
Please reply if any body have solutions

**Comment by VKBobyr** [comment]
I was able to get it resolved by creating a new project, copying the files into it without the package.json and installing the dependencies 1 by 1.

**Comment by AsterModi** [comment]
Hey Thanks Man, I solved it

**Comment by ShardulJitkar** [comment]
Getting error as 
![image](https://user-images.githubusercontent.com/62512870/89695269-f9279580-d930-11ea-80e6-e3b540eb5552.png)

**Comment by ndotie** [comment]
just run this man 
`expo install react-native-gesture-handler react-native-reanimated react-native-screens react-native-safe-area-context @react-native-community/masked-view
`

**Comment by ndotie** [comment]
> Getting error as
> ![image](https://user-images.githubusercontent.com/62512870/89695269-f9279580-d930-11ea-80e6-e3b540eb5552.png)

just run this mate
`expo install react-native-gesture-handler react-native-reanimated react-native-screens react-native-safe-area-context @react-native-community/masked-view`

**Comment by ndotie** [comment]
after the above codes installation, just run `expo start -c` to clear cache and run your expo powered application using the QR codes given by the `expo start c` command on your terminal, 
i mean dont go back to `npm run android` right the way... You'll run into the same problems

**Comment by RicardoPalmaSierra** [comment]
Son los mejores, pude resolver eso 🥇

**Comment by CSugarPrince** [comment]
> > Getting error as
> > ![image](https://user-images.githubusercontent.com/62512870/89695269-f9279580-d930-11ea-80e6-e3b540eb5552.png)
> 
> just run this mate
> `expo install react-native-gesture-handler react-native-reanimated react-native-screens react-native-safe-area-context @react-native-community/masked-view`
> 
> after the above codes installation, just run `expo start -c` to clear cache and run your expo powered application using the QR codes given by the expo start c command on your terminal,
> i mean dont go back to `npm run android` right the way... You'll run into the same problems

Additionally after I did the expo install, on my iOS simulator, I went to Device > Erase All Content and Settings. Worked great!

**Comment by Anjani-prog** [comment]
I have deleted expo package-lock json, node modules
then after I did the expo install , expo start -c
