### ISSUE TITLE
createMaterialTopTabNavigator tabs static height issue

### ISSUE THREAD

**Issue by thezenvan** [react-navigation/react-navigation#8644]
**Current Behavior**
I have a MaterialTopTabNavigator with 4 tabs inside of a functional component (which is in a StackNavigator). All the tabbed pages have varying heights that change according to the information displayed in them. The issue is that the height of all the tabs is set to the height of the tallest tab and all the other tab pages have extra padding on the bottom of them. I tried adding {{ padding: 0, margin: 0 }} to the style and sceneContainerStyle props of the tab navigator but that didn't help.

Here's is an example screenshot, the extra padding is in red at the bottom to make it clear.
[example](https://i.imgur.com/12xqCtV.png)

**Expected Behavior**
I expect the height of the page to be determined by the data displayed in it

**How to reproduce**
Create a functional component inside of a StackNavigator that contains a MaterialTopTabNavigator with a few pages with varying heights and swipe between those pages.

**Your Environment**
| software                            | version |
| ----------------------------------- | ------- |
| iOS or Android                      | Both
| @react-navigation/native            | 5.7.2
| @react-navigation/material-top-tabs | 5.2.15
| react-native-tab-view               | 2.15.0
| react-native                        | 0.61.4
| expo                                | 36.0.0
| node                                | 12.16.2
| npm or yarn                         | 6.14.4

**Comment by dario30186** [comment]
I have the same problem, any solution?

**Comment by thezenvan** [comment]
Not yet

**Comment by nadir-karimo** [comment]
Also facing this issue is there a workaround?

**Comment by thezenvan** [comment]
@nadir-karimo Unfortunately I never found a solution

**Comment by jonasgroendahl** [comment]
i also have this issue

**Comment by Htoonlin** [comment]
```js:
    const [show, setShow] = useState(false);
    React.useEffect(() => {
        navigation.addListener('focus', () => {
	    setShow(true);
	});
	navigation.addListener('blur', () => {
	   setShow(false);
	});
    }, [navigation]);
       
    return (<View style={[styles.container, show ? null : { display: 'none' }]}>
        <Text>Scene 1</Text>
    </View>)
```
I am trying like this.

**Comment by medelvann** [comment]
> ```
>     const [show, setShow] = useState(false);
>     React.useEffect(() => {
>         navigation.addListener('focus', () => {
> 	    setShow(true);
> 	});
> 	navigation.addListener('blur', () => {
> 	   setShow(false);
> 	});
>     }, [navigation]);
>        
>     return (<View style={[styles.container, show ? null : { display: 'none' }]}>
>         <Text>Scene 1</Text>
>     </View>)
> ```
> 
> You can use navigation.addListener on Scene Component.

Is there a better solution? Because if I have a large FlatList, so when setSow(true or false) it will be render total data, it makes laggy when click tabbar icon. i searched in other websites many people have this problem but not found for fix this

**Comment by jamesqo** [comment]
:+1: Also having this issue

**Comment by fixurshitreactnative** [comment]
+1

**Comment by yianshih** [comment]
I am also having this issue

**Comment by syntacticsolutions** [comment]
Here is another workaround
```
        <Tab.Screen name="Your Screen Name">
          {function InnerStack({ navigation }: any) {
            return navigation.isFocused() ? (
              <YourComponent />
            ) : (
              <YourComponent style={{maxHeight: 200}} />
            );
          }}
        </Tab.Screen>
```

**Comment by mtahir08** [comment]
facing same issue

**Comment by shubhamkes** [comment]
Anyone found solution?

**Comment by swapzone** [comment]
Same here

**Comment by Apindes** [comment]
> Here is another workaround
> 
> ```
>         <Tab.Screen name="Your Screen Name">
>           {function InnerStack({ navigation }: any) {
>             return navigation.isFocused() ? (
>               <YourComponent />
>             ) : (
>               <YourComponent style={{maxHeight: 200}} />
>             );
>           }}
>         </Tab.Screen>
> ```

Interesting soultion. And in case there are not so many Screens you can do

**Comment by kameshdhana** [comment]
> > Here is another workaround
> > ```
> >         <Tab.Screen name="Your Screen Name">
> >           {function InnerStack({ navigation }: any) {
> >             return navigation.isFocused() ? (
> >               <YourComponent />
> >             ) : (
> >               <YourComponent style={{maxHeight: 200}} />
> >             );
> >           }}
> >         </Tab.Screen>
> > ```
> 
> Interesting soultion. And in case there are not so many Screens you can do
> 
> ```
>     <Tab.Screen name="Yourname">
>       {({ navigation }: any) =>
>         navigation.isFocused() ? <YourComponent /> : <></>
>       }
>     </Tab.Screen>
> ```
> 
> Here if your on the tab which has a lot of content with big height and you tap another tab with small height, the previous content becomes empty and it wont boser current tab height.

This worked for me awesome answer
