### ISSUE TITLE
Events not working when transparent modal is displayed (not full screen) on screen under it

### ISSUE THREAD

**Issue by rdhox** [react-navigation/react-navigation#8645]
**Current Behavior**

```ts
interface Props {};

const AppTabletStack = createStackNavigator<AppTabletStackParamList>();

const AppTabletNav: React.FC<Props> = props => {

  return (
    <AppTabletStack.Navigator
      headerMode="none"
      initialRouteName="Home"
      screenOptions={{
        headerShown: false,
        gestureEnabled: true,
      }}
      mode="modal"
    >
      <AppTabletStack.Screen
        name="Home"
        component={MyScreen}
      />
      <AppTabletStack.Screen
        name="ModalMenu"
        component={ModalScreen}
        options={{
          cardStyle: {
            backgroundColor: 'transparent',
            width:'40%',
          },
          cardStyleInterpolator: CardStyleInterpolators.forNoAnimation,
        }}
      />
  </AppTabletStack.Navigator>
  );
}
```

**Expected Behavior**

Since the modal is only 30% of the width of the window, the screen below that is still visible should be able to receive event like `onPress` with component like `TouchableOpacity.

<img width="1046" alt="Capture d’écran 2020-07-28 à 19 26 03" src="https://user-images.githubusercontent.com/36813150/88699980-4a9d7c80-d108-11ea-9e52-8fe9cd5c8e66.png">

**How to reproduce**

Just follow the example of transparent modal in the doc with the settings above. 

Or see the Snack here: https://snack.expo.io/@rdhox/bug-modal

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| @react-navigation/native       | 5.7.2
| @react-navigation/stack        | 5.8.0
| react-native-gesture-handler   | 1.6.0
| react-native-safe-area-context | 3.0.7
| react-native-screens           | 2.9.0
| react-native                   | 0.62
| expo                           | SDK38

**Comment by aquile** [comment]
@rdhox so did you find a solution?

**Comment by rdhox** [comment]
@aquile No, as nobody answered this thread, no solution apparently...

Which surprise me, because it's a major problem.

**Comment by satya164** [comment]
Stack Navigtor isn't designed to do this. There is only one screen active at a time. It's not something that can be changed since otherwise it's going to mess up accessibility in normal use cases.

I suggest you render your own component over the current screen if you want to the screen to remain accessibile and interactive instead of using a new screen.

**Comment by rdhox** [comment]
> Stack Navigtor isn't designed to do this

Well it is, since I'm able to do it using nothing but the react-navigation settings...

**Comment by satya164** [comment]
> Well it is, since I'm able to do it using nothing but the react-navigation settings...

Just because you can do something doesn't mean it was designed to do it. Regardless, if you were able to do it then there wouldn't be a reason to open an issue.
