### ISSUE TITLE
Re-rendering causes navigation ref.current to become null

### ISSUE THREAD

**Issue by alexanderkho** [react-navigation/react-navigation#8646]
**Current Behavior**

I'm trying to make a reusable SplitView component where the parent navigators are able to perform navigations on their children. To accomplish this I am using ref's to programmatically perform navigations on nested navigators. However, I am running into an issue where when my app re-renders, all my navigation refs become:

```
{current: null}
```

And I am not able to perform any further navigations. 

The docs for ["Navigating without the navigation prop"](https://reactnavigation.org/docs/navigating-without-navigation-prop#handling-initialization) have some notes around initialization issues with this use case but I didn't have any luck with their suggested solutions. I think the issue they are referring to is a race condition before the Navigation container has a chance to mount--I don't think this is what is happening to me because it seems like once my app re-renders I NEVER get access to the correct ref. 

**Expected Behavior**

I should be able to perform programatic navigations on my nested navigators after subsequent re-renders. 

**How to reproduce**

[Link to Snack](https://snack.expo.io/@alexho/splitview-nav-bug).

NOTE: You must uncomment lines 13-17 in ```App.js``` to see the issue. The commented-out useEffect is there to force an initial re-render. Without it the navigation works just fine. 

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | both
| @react-navigation/native       | ^5.7.0
| @react-navigation/stack        | ^5.7.0
|react-native  | 0.63.1

**Comment by satya164** [comment]
Dunno where the error is, but you're passing the same ref to multiple navigators, using `createRef` instead `useRef`, using 3 different `NavigationContainers`. There are a lot of issues in your code. If you can repro an issue with a minimal example, then feel free to open a new issue.

**Comment by alexanderkho** [comment]
@satya164 apologies for the clunky example. Switching to useRef seemed to solve the issue in my case, I guess this wasn't an issue with react-navigation after all. Thanks for taking a look!

**Comment by yairopro** [comment]
Hi @satya164 

Please reopen this issue

The `NavigationContainer.ref` gives a different instance (and of course set to null the previous one) each time the parent render even though the ref function is the same each render (I prefer function rather than ref objects).

Here's a snack about the problem:
https://snack.expo.io/hyOD1hTSR

In the snack i use a state setter because i need the component to re-render (in my real case) and do an some effect.
The setter is always the same function instance.
