### ISSUE TITLE
headerTransparent will affect the previous page

### ISSUE THREAD

**Issue by itenl** [react-navigation/react-navigation#8647]
**Current Behavior**

- When you click Go Detail button, the Header will flash with a white background, unless I set the background color for the Detail page.
- When sliding back on the Detail page to the right, the Header will jitter and drop 56px from the top, this phenomenon does not occur when I click back button, which causes me to have to disable [gesturesEnabled:true] on iOS.

**Expected Behavior**

- Click Go Detail, there will be no white flicker
- And there will be no jitter when sliding back on the Detail page to the right.

**How to reproduce**

![0z2uu-51le3](https://user-images.githubusercontent.com/16585374/88781178-a4f91480-d1be-11ea-9502-5a48eed7c956.gif)

- Home Header
```javascript
  static navigationOptions = ({ navigation, screenProps }) => {
    return {
      headerTitle: 'Home',
      headerStyle: {
        height: 56,
        backgroundColor: '#182233'
      }
    };
  };
```

- Detail Header
```javascript
  static navigationOptions = ({ navigation, screenProps }) => {
    return {
      headerTitle: 'Detail',
      headerStyle: {
        height: 56,
        // backgroundColor: 'pink',
      },
      // headerBackground: (
      //   <View style={{ backgroundColor: 'rgba(255, 255, 255,0)' }}>
      //     <Text>12321</Text>
      //   </View>
      // ),
      headerTransparent: true,
      gesturesEnabled: true
    };
  };
```

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | iOS
| react-navigation         | 3.11.1
| @react-navigation/core  | 3.4.2
| @react-navigation/native       | 3.5.0
| @react-navigation/stack        | 1.4.0
| react-native-gesture-handler   | 1.6.1
| react-native-safe-area-view | 0.14.9
| react-native-safe-area-context | -
| react-native-screens           | 2.8.0
| react-native                   | 0.62.2
| expo                           | -
| node                           | v12.16.3
| npm or yarn                    | npm

**Comment by satya164** [comment]
These versions are deprecated and not supported. Upgrade to at least React Navigation 4 https://reactnavigation.org/docs/4.x/upgrading-from-3.x
