### ISSUE TITLE
using navigation.canGoBack() in only a stack navigator

### ISSUE THREAD

**Issue by abdi4** [react-navigation/react-navigation#8653]
I have a tab navigator which contains a stack navigator. I want to use navigation.canGoBack() for only the stack navigator. So if a user is at the top screen in the stack nav (and there's no going back in that stack) I want it to return false. The way it works now is that canGoBack is always true (unless i’m on the first tab screen when the app starts and goBack() takes me to different tabs). Is there any solution/work-around for this?
Any help is highly appreciated.

**Comment by abdi4** [comment]
I’m using react-navigation v5

**Comment by TMaszko** [comment]
Please provide repo for reproduction. It will be much easier in terms of debugging it and fixing ;)

**Comment by abdi4** [comment]
I found a solution: [https://reactnavigation.org/docs/use-navigation-state/](url)
