### ISSUE TITLE
Typescript : 'state' type does not exit in RouteProp.

### ISSUE THREAD

**Issue by oh3vci** [react-navigation/react-navigation#8661]
I found that the **state** type does not exit in RouteProp when I practiced [Setting parent screen options based on child navigator's state](https://reactnavigation.org/docs/screen-options-resolution/#setting-parent-screen-options-based-on-child-navigators-state).

I also checked this note.

> Note: The route.state property may not exist at all. This will always happen if we have never navigated inside the tab navigator. So it's very important to handle this case, otherwise, your app will crash.

However, I think the **state** type is needed to add optional type to RouteProp for adding dynamic navigation options.

| software                       | version |
| ------------------------------ | ------- |
| @react-navigation/native | 5.7.2 |
| @react-navigation/stack | 5.8.0 |
| react-native | 0.63.0 |

**Comment by satya164** [comment]
As the examples in docs, you should use `getFocusedRouteNameFromRoute` helper instead. The `state` property isn't supposed to be accessed by user code as it can be problematic. I have updated the docs to remove all references to `route.state`.
