### ISSUE TITLE
useScrollToTop not working with Native Stack Navigator's Large Title (iOS)

### ISSUE THREAD

**Issue by Evan-Younan** [react-navigation/react-navigation#8662]
**Current Behavior**

`useScrollToTop` hook does not work properly in a Native Stack Navigator with a translucent header on iOS.

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | iOS
| @react-navigation/native       | 5.7.1
| react-native                   | 0.62.1
| expo                           | 
| node                           | 12.16.1
| npm or yarn                    | 6.14.5

**Comment by WoLewicki** [comment]
For problems with `native-stack`, please submit an issue in [this repo](https://github.com/software-mansion/react-native-screens).
