### ISSUE TITLE
Is push() missing from types file?

### ISSUE THREAD

**Issue by chancesmith** [react-navigation/react-navigation#8664]
I may be reading this wrong, but it looks like push() method isn't apart of the types file.
https://github.com/react-navigation/react-navigation/blob/main/packages/core/src/types.tsx#L137

# question
Does `push()` need to be added to types of `NavigationHelpersCommon`?

Here is the error I get from the `const navigation = useNavigation();`

## screenshot of type error
![Screenshot 2020-07-31 15 05 14](https://user-images.githubusercontent.com/4466585/89073001-3f806180-d33f-11ea-92f7-3804c4faccd2.png)

## using:
```
"@react-navigation/native": "^5.7.1",
"@react-navigation/stack": "^5.7.1",
```

**Comment by theohdv** [comment]
`push()` is a specific action of the StackNavigator. So, if you want to get the right types using `useNavigation` you need to annotate it.
See: https://reactnavigation.org/docs/typescript/#annotating-usenavigation

**Comment by slightlytyler** [comment]
I just ran into this and I'm not understanding your response @theohdv. Are there cases where `push` would not be defined on the return value of `useNavigation`? My understanding is that `push` is always a property of `navigation` and therefore this should be included in the type. Even if was possibly undefined that type should describe that. 

From my view it seems like you're suggesting we go through the ceremony of adding type annotations for no reason.

**Comment by slightlytyler** [comment]
For anyone reading this after me that is pursuing a generic usage of `useNavigation` that includes `push` and `pop`

```ts
const navigation = useNavigation<StackNavigationProp<ParamListBase>>()
```

happy typing 😄

**Comment by satya164** [comment]
> the lack of clear typing here does not shine well on this library

it's literally impossible to automatically type this.

**Comment by simon-abbott** [comment]
> it's literally impossible to automatically type this.

It's actually entirely possible to automatically type this ([source 1](https://www.typescriptlang.org/docs/handbook/declaration-files/templates/module-plugin-d-ts.html), [source 2](https://pqina.nl/blog/typescript-interface-merging-and-extending-modules/)), it just requires some restructuring of the exported types.

**Comment by satya164** [comment]
> It's actually entirely possible to automatically type this 

It's not. Whether `navigation` has `push` or not depends on if it's inside a stack navigator - which needs the knowledge of the React tree that's not knowns statically. Declaration merging will always add `push` to `navigation` which is incorrect.

**Comment by simon-abbott** [comment]
Ah, that's fair. I didn't consider that someone would have a mix of stack and non-stack navigation. I've only ever had no stack or all stack.

**Comment by dgraham-nectivio** [comment]
Similar to [@slightlytyler's answer](https://github.com/react-navigation/react-navigation/issues/8664#issuecomment-701017858) you're using `@react-navigation/native-stack` you can get a navigator with push & pop helpers and strongly typed generic routes with:

```
const navigation = useNavigation<NativeStackNavigationProp<ReactNavigation.RootParamList>>();
```

**Comment by falk-stefan** [comment]
@dgraham-nectivio Thanks - I found it out eventually :)
