### ISSUE TITLE
Cannot listen to drawerOpen event inside DrawerContent

### ISSUE THREAD

**Issue by Mavenic** [react-navigation/react-navigation#8666]
**Current Behavior**
When we are trying to listen to the drawer open event inside the DrawerContent (which is a custom component), the callback is not getting fired. Below is the code I am using.
```
export default CustomDrawerContent extends React.Component {
 ...
 componentDidMount() {
    let {navigation} = this.props;
    this.drawerListener = navigation.addListener('drawerOpen', (e) => {
      console.log('Open');
    });
 }
 ...
}
```
Below is my drawer navigator in app.js
```
<Drawer.Navigator
   screenOptions={{...SCREEN_OPTIONS, gestureEnabled: true}}
   headerMode="none"
   drawerStyle={isTablet ? {width: '60%'} : {width: '75%'}}
   drawerContent={(props) => <CustomDrawerContent {...props} />}>
      <Drawer.Screen name="Home" component={HomeScreen} />
 </Drawer.Navigator>
```

**Expected Behavior**
I should be able to trigger the callback function.

**How to reproduce**
To reproduce add a listener to "drawerOpen" inside DrawerContent.

**Your Environment**

| Software                      | Version |
| ------------------------------ | ------- |
| iOS or Android                 | Both
| @react-navigation/native       | 5.7.1
| @react-navigation/drawer       | 5.8.6
| react-native-reanimated        | 1.10.1
| react-native-gesture-handler   | 1.7.0
| react-native-safe-area-context | 3.1.1
| react-native-screens           | 2.9.0
| react-native                   | 63.2
| expo                           | N/A
| node                           | 10.15.3
| npm or yarn                    | 6.14.3

**Comment by Mavenic** [comment]
Yes it still exists on the latest version as well

**Comment by shrhawk-entertainer** [comment]
facing the same issue

**Comment by jamesholcomb** [comment]
Same result and setup as yours, but in my case it throws exception `navigation.addListener is not a function` in componentDidMount.

```
    "@react-navigation/drawer": "5.9.0",
    "@react-navigation/native": "5.7.3",
    "@react-navigation/stack": "5.9.0",
```

**Comment by at3s** [comment]
@Mavenic have you resolve this issue?

**Comment by satya164** [comment]
Why do you need to listen to `drawerOpen` event?

You can check if drawer is open with `useIsDrawerOpen`:

```js
import { useIsDrawerOpen } from '@react-navigation/drawer';

// ...

const isOpen = useIsDrawerOpen();
```

Or if you have a class component and can't use hooks:

```js
import { getIsDrawerOpenFromState } from '@react-navigation/drawer';

// ...

const isOpen = getIsDrawerOpenFromState(this.props.state);
```

The `drawerOpen` event will be removed in the next major. So I'm closing this.

**Comment by oxyii** [comment]
@satya164 I need to track open progress animation state

**Comment by satya164** [comment]
@oxyii I'm not sure how `drawerOpen` event helps you with that, this event is just fired when the drawer open value changes regardless of animation. You get a `progress` prop in the component which represents animation progress.

**Comment by oxyii** [comment]
@satya164 sorry, I really don't remember exactly how this is related in my case. But I already have a workaround. I will open a new issue if I remember in the future.

**Comment by Mavenic** [comment]
@at3s Not yet, Currently I am listening for a focus event.

**Comment by emmaroland32** [comment]
> @oxyii I'm not sure how `drawerOpen` event helps you with that, this event is just fired when the drawer open value changes regardless of animation. You get a `progress` prop in the component which represents animation progress.

Experiencing the same issue. For me progress prop is not available in the drawe Content props, i only have `state, navigate, descriptors`. Really need a work around on this.

**Comment by guilnorth** [comment]
On version 6:

```js
import { useDrawerStatus } from '@react-navigation/drawer';

// ...

const isDrawerOpen = useDrawerStatus() === 'open';
```

From: https://reactnavigation.org/docs/drawer-based-navigation/
