### ISSUE TITLE
Adding horizotnal padding to scrollable TopTabNavigator

### ISSUE THREAD

**Issue by kimkong88** [react-navigation/react-navigation#8667]
**Current Behavior**

adding horizontal padding/margin to toptabnavigator results in

1. cut off at the end of tabview
2. can't scroll to the end of tabview

**Expected Behavior**

1. I should be able to add padding/margin to either style or contentContainerStyle props to add padding/margin horizontally to tabview

**How to reproduce**

Simple.

```
const Tab = createMaterialTopTabNavigator();
                    <Tab.Navigator
                        tabBarOptions={{
                            scrollEnabled: true,
                            tabStyle: {
                                width: "auto",
                            },
                            style: {
                                paddingHorizontal: 24 <<< Won't work because it will add "white space horizontally
                            },
                            indicatorContainerStyle: {
                                marginHorizontal: 24, <<< This is needed because indicator won't be in sync if I add padding
                            },
                            contentContainerStyle: {
                                marginHorizontal: 24, <<< This partially works, but end is cut off and user cannot scroll to the end
                            },
                        }}
                    > ....
```

Is there something I am missing? seems like pretty basic feature to add paddings/margins to scrollable tabs

**Your Environment**

| software                            | version |
| ----------------------------------- | ------- |
| iOS or Android                      |Both
| @react-navigation/native            |5.5.1
| @react-navigation/material-top-tabs |5.2.10
| react-native-tab-view               |2.14.4
| react-native                        |0.63.2
| expo                                |38.0.0
| node                                |
| npm or yarn                         |

**Comment by Victor-R** [comment]
@kimkong88 Did you solve the issue? I'm facing the same situation but I've figured how to make the scroll work: 
```
contentContainerStyle: {
            width: 'auto', <- with this somehow the scroll goes until the end
            paddingStart: 52,
  },

```
The only problem with this solution is that the animation when you swipe between tabs doesn't go until the end.

**Comment by andreshsingh** [comment]
this worked for me

```
        indicatorStyle: {
          width: (Dimensions.get('window').width / 2) - 100,
          marginHorizontal: 50
        },
```
