### ISSUE TITLE
jest test fail with message: `  <project_path>/node_modules/@react-navigation/stack/lib/commonjs/views/assets/back-icon.png:1

### ISSUE THREAD

**Issue by idhowardgj94** [react-navigation/react-navigation#8669]
**Current Behavior**

I just try to write unit test use jest and "react-test-renderer"

I start up the project by using `npx react-native init my-app`

when project beginning, the automated generate test will pass.

```js
/* eslint-disable no-undef */
/**
 * @format
 */

import 'react-native'
import React from 'react'
import App from '../App'

// Note: test renderer must be required after react-native.
import renderer from 'react-test-renderer'

it('renders correctly', () => {
  renderer.create(<App />)
})

```

but after I add @react-navigation/@stack, i got this error:

```js
 FAIL  __tests__/App-test.js
  ● Test suite failed to run

  /<project>/node_modules/@react-navigation/stack/lib/commonjs/views/assets/back-icon.png:1
    �PNG


    SyntaxError: Invalid or unexpected token

      at Runtime._execModule (node_modules/jest-runtime/build/index.js:1157:58)
      at Object.<anonymous> (node_modules/@react-navigation/stack/lib/commonjs/index.tsx:13:3)
```
I can build the app correctly, just fail to pass the test.

**Expected Behavior**

* pass test

**How to reproduce**

use react-native 0.63.2,

`npx react-native init my-app`

then add react-navigation

`yarn add @react-navigation/native @react-navigation/native react-native-gesture-handler react-native-reanimated`

setup the test environment from official website:

```js
// inside jestSetupFile.js

import 'react-native-gesture-handler/jestSetup'

jest.mock('react-native-reanimated', () => {
  const Reanimated = require('react-native-reanimated/mock')

  // The mock for `call` immediately calls the callback which is incorrect
  // So we override it with a no-op
  Reanimated.default.call = () => {}

  return Reanimated
})

// Silence the warning: Animated: `useNativeDriver` is not supported because the native animated module is missing
jest.mock('react-native/Libraries/Animated/src/NativeAnimatedHelper')
```

and in jest.config.js: 
```js
module.exports = {
  preset: 'react-native',
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json', 'node']
}
```

 
**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | none
| @react-navigation/native       | ^5.7.2
| @react-navigation/stack        | ^5.8.0
| react-native-gesture-handler   | ^1.7.0
| react-native-safe-area-context | ^3.1.1
| react-native-screens           | ^2.9.0
| react-native                   | 0.63.2
| expo                           | none
| node                           | 13.7.0
| npm or yarn                    |

**Comment by burabure** [comment]
Had the same issue; it's a jest transform issue, see here https://github.com/facebook/jest/issues/2663

**Comment by satya164** [comment]
Closing since you didn't provide a repro to debug the issue.

**Comment by rmathias86** [comment]
@idhowardgj94 did you find a solution?

**Comment by idhowardgj94** [comment]
@rmathias86 I just decide not to test view layer, so I get rid of this issue.

but I think https://github.com/facebook/jest/issues/2663#issuecomment-317109798 is one solution for this issue.

I guess it's an issue for jest, because it didn't use ur webpack config, so you need to setup an  transformer to parse the assets.

**Comment by enzzoperez** [comment]
Can you found any solution?

**Comment by albert-dm** [comment]
Hi, for me it was solved adding the library to `transformIgnorePatterns` inside `jest.config.js`.

Mine looks like this

``` javascript
transformIgnorePatterns: [
    'node_modules/(?!(jest-)?react-native|react-clone-referenced-element|@react-native-community|rollbar-react-native|@fortawesome|@react-native|@react-navigation)',
  ],
```

**Comment by moustaouiSalaheddine** [comment]
Reason for the error is Jest failing to interpret the binary code of .png file (or any image file) into .js.

The solution or rather the way around is to mock a default response whenever Jest encounters an image file.

Steps:

Create a file named ImageMock.js (.tsx if you're using TypeScript) in a folder named **__mock__** (or any name).
**YourApp/__mock__/ImageMock.js**

`Write export default ''; ` in ImageMock.js
Add **moduleNameMapper** key with the below value within the **jest** key in **package.json**
```
"jest": {
  "moduleNameMapper": {
  "\\.(png|jpg|ico|jpeg|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$": "<rootDir>/__mock__/ImageMock.js"
  }
}
```
NB: Only the png in the moduleNameMapper key value is required for your particular error.

source : https://stackoverflow.com/a/71618485
