### ISSUE TITLE
IOS keyboard opens and automatically closes

### ISSUE THREAD

**Issue by kamalpandey** [react-navigation/react-navigation#8674]
**Current Behavior**
If I remove the  ``` pagerComponent: ViewPagerAdapter```
It works on IOS but there is crash on Android on scroll on the first and last tab.

If i add it the android works fine but in IOS the  keyboard opens and automatically closes in ScrollView

**Expected Behavior**

The keyboard should remain open when text input is focused

**How to reproduce**

```
import React from "react";
import { Text, View, Platform } from "react-native";
import ViewPagerAdapter from 'react-native-tab-view-viewpager-adapter';
import { createStackNavigator } from "react-navigation-stack";
import { createMaterialTopTabNavigator } from "react-navigation-tabs";

import {
  XYZScreen,
  ABCScreen
} from "../screens";

const settingsTab = createMaterialTopTabNavigator(
  {
    Basic: {
      screen: XYZScreen,
      navigationOptions: ({ navigation }) => ({
        tabBarLabel: ({ focused }) => (
          <View>
            <Text
              numberOfLines={1}
            >
              {navigation.state.routeName}
            </Text>
          </View>
        )
      })
    },
    Notifications: {
      screen: ABCScreen,
      navigationOptions: ({ navigation }) => ({
        tabBarLabel: ({ focused }) => (
          <View>
            <Text
              numberOfLines={1}
            >
              {navigation.state.routeName}
            </Text>
          </View>
        )
      })
    }
  },
  {
    initialRouteName: "Basic",
    swipeEnabled: true,
    animationEnabled: true,
    pagerComponent: ViewPagerAdapter,
    tabBarOptions: {
      scrollEnabled: true,
      upperCaseLabel: false
      style: {
        elevation: 0,
        borderBottomWidth: 0,
        backgroundColor: Colors.white
      }
  }
);
```

**Your Environment**

| software                            | version |
| ----------------------------------- | ------- |
| iOS or Android                      | IOS
| react-navigation  |      4.0.9
| react-navigation-tabs  |  2.9.0
| react-native-tab-view               | 2.15.0
| react-native                        | 0.62
| expo                                | 38
| node                                | 12.16.2
| npm or yarn                         | yarn

**Comment by satya164** [comment]
Please open issue in viewpager adapter repo for issues with it instead of here.
