### ISSUE TITLE
Elevation artifacts when using ScaleFromCenterAndroid

### ISSUE THREAD

**Issue by DomiR** [react-navigation/react-navigation#8676]
**Current Behavior**

- When using TransitionPresets.ScaleFromCenterAndroid for android it has elevation artifacts
- ![Video](https://user-images.githubusercontent.com/1834664/89313977-64dfd900-d679-11ea-8e64-a9b5cdae7ef4.gif)

**Expected Behavior**

- Artifact should not be shown
- Not sure if we need to disable elevation during the animation. When I use a custom header style with elevation set to 0 it works as expected.

Sidenote: DefaultTransition does not check android version > Q yet but should use ScaleFromCenterAndroid for Q by default?!

**How to reproduce**

- See [expo snack](https://snack.expo.io/@domir/getting-started-%7C-react-navigation)

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | android
| @react-navigation/native       |  5.7.3
| @react-navigation/stack        | 5.9.0
| react-native-gesture-handler   |
| react-native-safe-area-context |
| react-native-screens           |
| react-native                   |
| expo                           |
| node                           |
| npm or yarn                    |

**Comment by satya164** [comment]
It's a bug in React Native https://github.com/facebook/react-native/issues/23090

**Comment by DomiR** [comment]
I've investigated this issue. Please see https://github.com/facebook/react-native/issues/23090#issuecomment-669157170.

I guess setting needsOffscreenAlphaCompositing on this view: https://github.com/react-navigation/react-navigation/blob/main/packages/stack/src/views/Header/HeaderSegment.tsx#L313 at least during the animation would fix the problem.
