### ISSUE TITLE
bug mixing react-navigation and react-native-firebase notifications when app is closed

### ISSUE THREAD

**Issue by tastafur** [react-navigation/react-navigation#8685]
**Current Behavior**
What happens, that when I want to navigate using navigate the navigationRef.current is defined but the root state is not, then it fails. What I do is read as firebase says the notification it has made before when the app is closed and then know where to navigate. https://rnfirebase.io/messaging/notifications#handling-interaction What I do is read how firebase says the notifications that it has made before when the app is closed and then know where to navigate but they say to use the initial route and this when you have nested stacks because you have many screens is not feasible
```
export function navigate(name, params) {
  console.log('isReadyRef', isReadyRef);
  console.log('navigationRef state', navigationRef.current.getRootState());
  if (isReadyRef.current && navigationRef.current) {
    // Perform navigation if the app has mounted
    navigationRef.current.navigate(name, params);
  } else {
    console.log('ContainerNavigator is not mounted, action navigate not work');
    // You can decide what to do if the app hasn't mounted
    // You can ignore this, or add these actions to a queue you can call later
  }
}

const handleQuitOpen = useCallback(
    remoteMessage => {
          // This work with TimeOut
          setTimeout(
            () =>
              navigate('NotificationsMyPostCommentsOnly', {
              postId: objectId,
            });,
            800,
          );
           // Without timeout the root state is not defined
            navigate('NotificationsMyPostCommentsOnly', {
              postId: objectId,
            });
    [],
  );

    firebaseMessaging()
      .getInitialNotification()
      .then(handleQuitOpen);

```

**Expected Behavior**

I would like NavigationContainer to have an event that says when the root state has loaded or that the isReady callback waits for it to actually be ready, waiting for the root state to be defined

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | 13.5.1 and 10 |
| @react-navigation/native      | 5.7.3 |
| react-native                   | 0.62.2 |
| node                           | 12.16.0 |
| npm or yarn                    | 6.13.4 and 1.22.0 |

**Comment by tastafur** [comment]
Okey, i am going to create a minimal repro

**Comment by satya164** [comment]
https://reactnavigation.org/docs/navigation-container#onready
