### ISSUE TITLE
modal transparent close from clicking outside

### ISSUE THREAD

**Issue by muriloneo** [react-navigation/react-navigation#8687]
How to detect clicks outside View, or anything from a component Modal with transparent background, that don't have full width/height?

How to close this profile modal (white top right) clicking outside? Is it possible?

![image](https://user-images.githubusercontent.com/16191560/89486160-cb97ec00-d778-11ea-89fb-c26992f5e94f.png)

export default function ProfileScreen({ navigation }) {

  return (
    <View style={{ marginLeft: '60%', marginTop: '20%', flex: 1, flexDirection: 'column', justifyContent: 'flex-start' }}>
      <View style={{ borderRadius: 15, paddingLeft: 30, paddingTop: 60, marginTop: -90, height: "20%", width: '100%', backgroundColor: "#fff", justifyContent: "center" }}>
        <Text>Murilo Freire</Text>
        <TouchableOpacity onPress={() => {
          Alert.alert(
            'Logout?',
            'Você deseja fazer logout?',
            [
              {
                text: "Não", style: 'cancel', onPress: () => { navigation.popToTop() }
              },
              {
                text: 'Sair',
                style: 'destructive',
                onPress: () => navigation.navigate('Login'),
              },
            ]
          );
        }}>
          <Text style={{ textDecorationLine: 'underline' }}>Sair da conta</Text>
        </TouchableOpacity>
      </View>
    </View>
  );
}

function ModalStack() {
  return (
    <Modal.Navigator
      headerMode="none"
      mode="modal"
      screenOptions={{ animationEnabled: false }}
    >
      <Modal.Screen
        name="Root"
        component={RootStack}
      />
      <Modal.Screen
        name="Profile"
        component={Profile}
        options={{
          headerShown: false,
          animationEnabled: false,
          cardStyle: { backgroundColor: "transparent" },
          cardOverlayEnabled: true,
          gestureDirection: 'vertical-inverted',
          // gestureResponseDistance: { vertical: 750 }
        }}
      />
    </Modal.Navigator>
  );
}

    "@react-navigation/native": "^5.7.3",
    "@react-navigation/stack": "^5.9.0",
    "react": "16.13.1",
    "react-native": "0.63.2",
    "react-native-gesture-handler": "^1.7.0",
    "react-native-safe-area-context": "^3.1.1",
    "react-native-screens": "^2.10.0",

**Comment by aquile** [comment]
> How to detect clicks outside View, or anything from a component Modal with transparent background, that don't have full width/height?
> 
> How to close this profile modal (white top right) clicking outside? Is it possible?
> 
> ![image](https://user-images.githubusercontent.com/16191560/89486160-cb97ec00-d778-11ea-89fb-c26992f5e94f.png)
> 
> export default function ProfileScreen({ navigation }) {
> 
> return (
> <View style={{ marginLeft: '60%', marginTop: '20%', flex: 1, flexDirection: 'column', justifyContent: 'flex-start' }}>
> <View style={{ borderRadius: 15, paddingLeft: 30, paddingTop: 60, marginTop: -90, height: "20%", width: '100%', backgroundColor: "#fff", justifyContent: "center" }}>
> Murilo Freire
> <TouchableOpacity onPress={() => {
> Alert.alert(
> 'Logout?',
> 'Você deseja fazer logout?',
> [
> {
> text: "Não", style: 'cancel', onPress: () => { navigation.popToTop() }
> },
> {
> text: 'Sair',
> style: 'destructive',
> onPress: () => navigation.navigate('Login'),
> },
> ]
> );
> }}>
> <Text style={{ textDecorationLine: 'underline' }}>Sair da conta
> 
> 
> 
> );
> }
> 
> function ModalStack() {
> return (
> <Modal.Navigator
> headerMode="none"
> mode="modal"
> screenOptions={{ animationEnabled: false }}
> >
> <Modal.Screen
> name="Root"
> component={RootStack}
> />
> <Modal.Screen
> name="Profile"
> component={Profile}
> options={{
> headerShown: false,
> animationEnabled: false,
> cardStyle: { backgroundColor: "transparent" },
> cardOverlayEnabled: true,
> gestureDirection: 'vertical-inverted',
> // gestureResponseDistance: { vertical: 750 }
> }}
> />
> </Modal.Navigator>
> );
> }
> 
> ```
> "@react-navigation/native": "^5.7.3",
> "@react-navigation/stack": "^5.9.0",
> "react": "16.13.1",
> "react-native": "0.63.2",
> "react-native-gesture-handler": "^1.7.0",
> "react-native-safe-area-context": "^3.1.1",
> "react-native-screens": "^2.10.0",
> ```

Faced the same problem. @muriloneo Did you find a solution?

**Comment by muriloneo** [comment]
> Faced the same problem. @muriloneo Did you find a solution?

No, I did not.
I moved to react-native-modal
