### ISSUE TITLE
Navigate not working when Android app state is background 

### ISSUE THREAD

**Issue by Symous** [react-navigation/react-navigation#8690]
**Current Behavior**

When the Android app is running in background, I use some way(a background timer) to use `navigate(sceneName)` to navigate to another screen, the code is executed but the screen is not change, but when I switch the app from background to foreground, the screen changed. I have test the same step in iOS and all works as expected.  

**Expected Behavior**

The Android app is supposed to jump to the screen I called.

**How to reproduce**

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Android
| @react-navigation/native       | 3.8.0
| @react-navigation/stack        | 1.10.3
| react-native-gesture-handler   | 1.7.0
| react-native-safe-area-context |
| react-native-screens           | 2.10.1
| react-native                   | 0.63.0
| expo                           |
| node                           | 13.12.0 
| npm or yarn                    | npm 6.14.4

**Comment by satya164** [comment]
Closing since there's no repro to debug the issue.

**Comment by aayushm9595** [comment]
Facing the same issue, Whenever app goes in background and other app takes control like camera app or a web window the navigation does not seem to work.
Please help

**Comment by hkar19** [comment]
facing the issue when trying to apply auto logout and moving the screen.

the state was logged out but the screen does not change.

i will try to create minimal repo for that
