### ISSUE TITLE
Flex Direction doesn't work  for tab bar.

### ISSUE THREAD

**Issue by yarbasha** [react-navigation/react-navigation#8691]
I want to change the flex direction of tab bar from row to row-reverse.

<Tab.Navigator
        initialRouteName="Female Users"
        tabBarOptions={{
          activeTintColor: colors.primary,
          tabStyle: styles.tabContainer,
          keyboardHidesTabBar: true,
          labelPosition: "below-icon",
          labelStyle: styles.labelStyle,
          style: { flexDirection: "row-reverse" },
        }}
      >

![Screenshot_1596709sss993](https://user-images.githubusercontent.com/38437018/89522382-cf178b80-d7e9-11ea-931e-78666401af60.png)

after applying flexDirection: "row-reverse" the items should reversed.

I opened the BottomTabBar.tsx in the package and I found the style props I pass applied to Animated.View, I tried to to apply the flexDirection to the content View and it worked.

| software                      | version |
| ----------------------------- | ------- |
|  Android                |
| @react-navigation/native      |^5.6.1
| @react-navigation/bottom-tabs |^5.6.1

**Comment by satya164** [comment]
Just define screens in reverse?

**Comment by yarbasha** [comment]
@satya164 
Of course, but I just want it to work because I want it to change dynamically according to user choice.

**Comment by frknnay** [comment]
I'm also having this issue and I believe the answer should not be defining screens in reverse order.

**Comment by omer73364** [comment]
use transform: [{ scaleX: I18nManager.isRTL ? -1 : 0}]
for the navigator and its children
so the order will be the same in rtl and ltr
