### ISSUE TITLE
Example not working: unrecognized operator min

### ISSUE THREAD

**Issue by sa1dai** [react-navigation/react-navigation#8693]
**Current Behavior**

1. clone react-navigation project
2. yarn
3. yarn example start
4. scan qr code with android
5. react navigation logo occured, project is building
5. When 100% build error occured: 
<img src="https://i.ibb.co/rHPCMBR/photo-2020-08-06-19-42-36.jpg" width="300"/>

**Expected Behavior**

1. clone react-navigation project
2. yarn
3. yarn example start
4. scan qr code with android
5. react navigation logo occured, project is building
5. When 100% no error occur

**How to reproduce**

1. clone react-navigation project
2. yarn
3. yarn example start
4. scan qr code with android
5. react navigation logo occured, project is building
5. When 100% build error occured

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | android 7.1
| @react-navigation/native       | 5.7.3
| react-native                   |0.62.2
| expo                           | 38.0.9
| node                           | 14.4.0
| npm or yarn                    | yarn 1.22.0

**Comment by sa1dai** [comment]
My investigation:
I hard reset main branch to this commit: ` chore: update example to SDK 38 and bump related dependencies (#8654)`
And error gone and all work as expected.

This commit is selected on this screenshot:
<img src='https://i.ibb.co/L006JXX/screenshot-442.png' width='600'/>

**Comment by diego086** [comment]
Having the very same issue. And i can confirm @sa1dai workaround works.

**Comment by satya164** [comment]
should be fixed now
