### ISSUE TITLE
SafeAreaView leaves Extra padding in Bottom Tab Navigator inside Stack Navigator

### ISSUE THREAD

**Issue by prashantchothani** [react-navigation/react-navigation#8694]
**Current Behavior**

While using a screen with SafeAreaView from "react-native-safe-area-context" in a route of the Bottom Tab Navigator which is nested inside a Stack Navigator, there is bottom padding above the tabs which appears.

**Expected Behavior**

If we use SafeAreaView from "react-native" this issue is not there. It should not have the padding above the tabs while using SafeAreaView from "react-native-safe-area-context"

**How to reproduce**

- You must provide a way to reproduce the problem. If you are having an issue with your machine or build tools, the issue belongs on another repository as that is outside of the scope of React Navigation.
- Either re-create the bug on [Snack](https://snack.expo.io) or link to a GitHub repository with code that reproduces the bug.
- Explain how to run the example app and any steps that we need to take to reproduce the issue from the example app.
- Keep the repro code as simple as possible, with the minimum amount of code required to repro the issue.
- Before reporting an issue, make sure you are on latest version of the package.

**Your Environment**

iOS or Android :  iOS
"@react-navigation/native": "^5.5.1",
"@react-navigation/stack": "^5.4.2",
"react-native-screens": "^2.8.0",
react-native : 0.62.2
npm

**Comment by prashantchothani** [comment]
Yes.

**Comment by satya164** [comment]
https://reactnavigation.org/docs/handling-safe-area#summary

**Comment by jamesxabregas** [comment]
I had the same problem. The answer is to use the edges prop on SafeAreaView so that the inset is not applied to the bottom.

```
<SafeAreaView edges={['top', 'left', 'right']}>
   {children}
</SafeAreaView>
```

**Comment by CodeAura-a** [comment]
i found the solution  import {  SafeAreaView } from 'react-native'
instead of this import { SafeAreaView } from 'react-native-safe-area-context'
