### ISSUE TITLE
Elevation artifacts when using ScaleFromCenterAndroid

### ISSUE THREAD

**Issue by DomiR** [react-navigation/react-navigation#8696]
**Current Behavior**

- When using TransitionPresets.ScaleFromCenterAndroid for android it has elevation artifacts

![Video](https://user-images.githubusercontent.com/1834664/89313977-64dfd900-d679-11ea-8e64-a9b5cdae7ef4.gif)

**Expected Behavior**

- I've reopened a new issue, because https://github.com/react-navigation/react-navigation/issues/8676 was closed already
- Artifact should not be shown
- I've investigated this issue. Please see facebook/react-native#23090 (comment).
- ~I guess setting needsOffscreenAlphaCompositing on this view: https://github.com/react-navigation/react-navigation/blob/main/packages/stack/src/views/Header/HeaderSegment.tsx#L313 at least during the animation would fix the problem.~ We need to set needsOffscreenAlphaCompositing on the whole screen, as more elements can have elevation set, so not only on the header view.

Sidenote: DefaultTransition does not check android version > Q yet but should use ScaleFromCenterAndroid for Q by default?!

**How to reproduce**

- See [expo snack](https://snack.expo.io/@domir/getting-started-%7C-react-navigation)

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | android
| @react-navigation/native       |  5.7.3
| @react-navigation/stack        | 5.9.0
| react-native-gesture-handler   |
| react-native-safe-area-context |
| react-native-screens           |
| react-native                   |
| expo                           |
| node                           |
| npm or yarn                    |

**Comment by hienhodeveloper** [comment]
Any fix now???

**Comment by retyui** [comment]
Fortunately, we can set this flag using [needsOffscreenAlphaCompositing](https://reactnative.dev/docs/view#needsoffscreenalphacompositing) as a view prop.

**Comment by dancherb** [comment]
I'm experiencing similar shadow artifacts on a stack screen with forFadeFromBottomAndroid on the latest versions. Manually setting needsOffscreenAlphaCompositing on Views doesn't do the trick..
