### ISSUE TITLE
How to not display tabbar?

### ISSUE THREAD

**Issue by hengkx** [react-navigation/react-navigation#8698]
**Current Behavior**

```
// It's just going to be hidden down, but there's still a pixel out there. Similarly, custom buttons that // exceed the height of the tabbar are completely disabled.
navigation.setOptions({ tabBarVisible: false });
```

**Expected Behavior**

```
not show tabbar
```

**How to reproduce**

- You must provide a way to reproduce the problem. If you are having an issue with your machine or build tools, the issue belongs on another repository as that is outside of the scope of React Navigation.
- Either re-create the bug on [Snack](https://snack.expo.io) or link to a GitHub repository with code that reproduces the bug.
- Explain how to run the example app and any steps that we need to take to reproduce the issue from the example app.
- Keep the repro code as simple as possible, with the minimum amount of code required to repro the issue.
- Before reporting an issue, make sure you are on latest version of the package.

**Your Environment**

| software                      | version |
| ----------------------------- | ------- |
| iOS or Android                |
| @react-navigation/native      |  ^5.7.3 |
| @react-navigation/bottom-tabs | ^5.8.0 |
| react-native-screens          |
| react-native                  |
| expo                          |
| node                          |
| npm or yarn                   |

**Comment by satya164** [comment]
https://reactnavigation.org/docs/hiding-tabbar-in-screens
