### ISSUE TITLE
Tab Navigation In The Middle Of The Screen

### ISSUE THREAD

**Issue by TNBoiBoi** [react-navigation/react-navigation#8702]
**Current Behavior**

- What code are you running and what is happening? 
I'm trying to create a profile page like in twitter for example meaning having a header with stats about the user and his avatar
and then having a tab navigation to navigate between his posts and about page for example and then I wrap them both in a ScrollView both the Header and the Tab Navigato and it causes this issue - > 
Lets say I have the Posts Tab and About Tab and then Posts tab has a height of 800 and About has a height of 400
Then the ScrollView that wraps the Tab Navigator and the Header will have the height of 800 + the Header's height 
and when I switch to the the About tab it will still have a the height of 800 + 400 but it will also reset the tab height for some reason. 
So I will have a huge blank white space below the content in the About Tab. 

Then
I used CreateMaterialTopTabNavigator like so  - 

const TabNavigator = createMaterialTopTabNavigator<RootTabParamList>();

  const [activeTab, setActiveTab] = useState('Posts');
  return (
    <TabNavigator.Navigator
      lazy
      tabBarPosition="top"
    >
      <TabNavigator.Screen
        name="Posts"
        component={Posts}
      />
      <TabNavigator.Screen
        name="About"
        component={About}
      />
    </TabNavigator.Navigator>

And then I added it to the scroll View and it looks something like that 

        
        <Header/>
        <ProfileTabNavigator />

inside a ScrollView

Now whats the best way to implement it or what can I do to fix it? I don't know what to do anymore with it :((

- Include a screenshot or video if it makes sense.

Current Situation - 
The picture is taken from someone who posted this issue on StackExchange but didn't get any good answer as well.

![TheProblemPicture](https://user-images.githubusercontent.com/67235839/89823224-cad8ce80-db59-11ea-9f44-03de743af510.png)

**Expected Behavior**

- What do you expect should be happening?

To be able to switch tabs in the middle of the screen while I have a Header on top of them so the ScrollView Height will dynamically change.

- Include a screenshot or video if it makes sense.

Wanted Result - 

![ixiy60rpqdt21](https://user-images.githubusercontent.com/67235839/89823805-c5c84f00-db5a-11ea-9bd2-3cb324d83100.png)

**How to reproduce**

- You must provide a way to reproduce the problem. If you are having an issue with your machine or build tools, the issue belongs on another repository as that is outside of the scope of React Navigation.
- Either re-create the bug on [Snack](https://snack.expo.io) or link to a GitHub repository with code that reproduces the bug.
- Explain how to run the example app and any steps that we need to take to reproduce the issue from the example app.
- Keep the repro code as simple as possible, with the minimum amount of code required to repro the issue.
- Before reporting an issue, make sure you are on latest version of the package.

You can reproduce this issue by having a MaterialTopBarNavigator inside a scroll view with something on top of it even a Text Component.

**Your Environment**

| software                            | version |
| ----------------------------------- | ------- |
| iOS or Android                      |
| @react-navigation/native           | 5.7.3
| @react-navigation/material-top-tabs  | 5.2.16
| react-native-tab-view               |
| react-native                        | 
| expo                              |    latest 38.0.0
| node                                |
| npm or yarn                         |

**Comment by TomerNAH** [comment]
For Some reason the code wasn't published right so i'm pasting it here

const TabNavigator = createMaterialTopTabNavigator<RootTabParamList>();

  const [activeTab, setActiveTab] = useState('Posts');
  return (
    <TabNavigator.Navigator
      lazy
      tabBarPosition="top"
    >
      <TabNavigator.Screen
        name="Posts"
        component={Posts}
      />
      <TabNavigator.Screen
        name="About"
        component={About}
      />
    </TabNavigator.Navigator>

And then I added it to the scroll View and it looks something like that 

<View style={styles.container}>
      <ScrollView
        style={styles.container}
      >
        
        <Header/>
        <ProfileTabNavigator />
</ScrollView>
 </View>

**Comment by dguzman-ort** [comment]
Hey @TNBoiBoi Did you figurated out how to implememnt a Tab Navigation in the middle of the screen?

**Comment by raman-gnb** [comment]
> **Current Behavior**
> 
> * What code are you running and what is happening?
>   I'm trying to create a profile page like in twitter for example meaning having a header with stats about the user and his avatar
>   and then having a tab navigation to navigate between his posts and about page for example and then I wrap them both in a ScrollView both the Header and the Tab Navigato and it causes this issue - >
>   Lets say I have the Posts Tab and About Tab and then Posts tab has a height of 800 and About has a height of 400
>   Then the ScrollView that wraps the Tab Navigator and the Header will have the height of 800 + the Header's height
>   and when I switch to the the About tab it will still have a the height of 800 + 400 but it will also reset the tab height for some reason.
>   So I will have a huge blank white space below the content in the About Tab.
> 
> Then I used CreateMaterialTopTabNavigator like so -
> 
> const TabNavigator = createMaterialTopTabNavigator();
> 
> const [activeTab, setActiveTab] = useState('Posts'); return ( <TabNavigator.Navigator lazy tabBarPosition="top" > <TabNavigator.Screen name="Posts" component={Posts} /> <TabNavigator.Screen name="About" component={About} /> </TabNavigator.Navigator>
> 
> And then I added it to the scroll View and it looks something like that
> 
> ```
>     <Header/>
>     <ProfileTabNavigator />
> ```
> 
> inside a ScrollView
> 
> Now whats the best way to implement it or what can I do to fix it? I don't know what to do anymore with it :((
> 
> * Include a screenshot or video if it makes sense.
> 
> Current Situation - The picture is taken from someone who posted this issue on StackExchange but didn't get any good answer as well.
> 
> ![TheProblemPicture](https://user-images.githubusercontent.com/67235839/89823224-cad8ce80-db59-11ea-9f44-03de743af510.png)
> 
> **Expected Behavior**
> 
> * What do you expect should be happening?
> 
> To be able to switch tabs in the middle of the screen while I have a Header on top of them so the ScrollView Height will dynamically change.
> 
> * Include a screenshot or video if it makes sense.
> 
> Wanted Result -
> 
> ![ixiy60rpqdt21](https://user-images.githubusercontent.com/67235839/89823805-c5c84f00-db5a-11ea-9bd2-3cb324d83100.png)
> 
> **How to reproduce**
> 
> * You must provide a way to reproduce the problem. If you are having an issue with your machine or build tools, the issue belongs on another repository as that is outside of the scope of React Navigation.
> * Either re-create the bug on [Snack](https://snack.expo.io) or link to a GitHub repository with code that reproduces the bug.
> * Explain how to run the example app and any steps that we need to take to reproduce the issue from the example app.
> * Keep the repro code as simple as possible, with the minimum amount of code required to repro the issue.
> * Before reporting an issue, make sure you are on latest version of the package.
> 
> You can reproduce this issue by having a MaterialTopBarNavigator inside a scroll view with something on top of it even a Text Component.
> 
> **Your Environment**
> 
> software	version
> iOS or Android	
> @react-navigation/native	5.7.3
> @react-navigation/material-top-tabs	5.2.16
> react-native-tab-view	
> react-native	
> expo	latest 38.0.0
> node	
> npm or yarn

I am facing on the same issue, how can will fix the auto height

**Comment by raman-gnb** [comment]
@TNBoiBoi I have checked the material-top-tab-navigator, there are only top and bottom only provide. how can we set the tabs in middle of the page?

**Comment by toppsdown** [comment]
Anyone find a solution to this?

**Comment by HasanMothaffar** [comment]
Same issue. How can we have tab navigation in middle of screen?

**Comment by Dosbodoke** [comment]
No one found a solution yet right?
