### ISSUE TITLE
Bottom Tab Navigator big button problem

### ISSUE THREAD

**Issue by frankie95** [react-navigation/react-navigation#8704]
I am trying to make a big button in the middle of my BottomTabNavigator with below code, however I found that when I click on the red area, it will not response.
Does anyone has any idea to fix it?
(I am using samsung galaxy S8+)
```
  "@react-navigation/bottom-tabs": "^5.8.0",
    "@react-navigation/native": "^5.7.3",
```
```
<Tab.Screen name="Pay" component={AddItemScreen} options={{
                tabBarIcon: (props) => <View style={{
                    borderRadius: 100,
                    borderWidth: 2,
                    borderColor: '#00C289',
                    position: 'absolute',
                    bottom: 5, // space from bottombar
                    backgroundColor: props.focused ? '#8EE4AF' : "#C3D6CD",
                }}>
                    <AntDesign name="plus" color="#05386B" size={85} /></View>
            }} />

```

![117445487_329885271384357_8733857771298383769_n](https://user-images.githubusercontent.com/22611986/89896043-595b5780-dc0f-11ea-9c0f-21f4e7fcc815.jpg)

**Comment by satya164** [comment]
It's a limitation in React Native on Android (or rather due to system behavior) where overflow content outside a view won't be touchable, unrelated to React Navigation.

**Comment by vabvgoyal** [comment]
In android, When an element appears out of the parent component it won’t rise any handler, but only part of the touchable element that renders in the parent component will be responsible, so we can leave that as it is or expands, the TabBar area to extend the touchable area of the big button.
(HACK)
or for a complete solution, 
you need to create a Custom tab bar.
