### ISSUE TITLE
Header animation when navigating back from an iOS style modal

### ISSUE THREAD

**Issue by devinjameson** [react-navigation/react-navigation#8707]
**Current Behavior**

When navigating BACK from the below screen to a screen with a header, the header animates incorrectly.

```
 <Stack.Screen
    name={MoreStackScreens.LanguageSelection}
    component={LanguageSelection}
    options={{
      ...TransitionPresets.ModalPresentationIOS,
      headerShown: false,
      cardOverlayEnabled: true,
      cardShadowEnabled: true,
    }}
/>
```

![incorrect](https://user-images.githubusercontent.com/39350030/89957358-3166f680-dc05-11ea-8742-5573cd17c710.gif)

**Expected Behavior**

- I would expect the header to slide down instead of left

**Comment by devinjameson** [comment]
@react-navigation/native version number is `5.5.1`.

**Comment by satya164** [comment]
It's recommend to have a separate stack for modals. It's not possible to have good interop between normal transition and modal presentation style.

**Comment by bncvnc** [comment]
Can i get to know the transection you are using on modal there and can you tell me how to add swipe down to close this modal like any other native ios app does?
