### ISSUE TITLE
headerTitle can be a component, headerRight has to be a function

### ISSUE THREAD

**Issue by kbrandwijk** [react-navigation/react-navigation#8709]
**Current Behavior**
When specifying the options for a screen, there's a discrepancy between headerTitle accepting a component directly (`headerTitle: <MyTitleComponent />`), but headerRight _has_ to be a function (`headerRight: () => <MyRightComponent />`) or you'll get the `TypeError: right is not a function` error, that isn't really nicely handled (as in: not at all).

**Expected Behavior**
Consistent behavior allowing `headerRight` to accept a component directly as well.

**How to reproduce**

`<Stack.Screen name="MyScreen" component={MyScreen} options={{ headerTitle: <MyTitle />, headerRight: <Right /> }} />`

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | both
| @react-navigation/native       | 5.7.3
| @react-navigation/stack        | 5.9.0
| react-native-gesture-handler   | 1.7.0
| react-native-safe-area-context | 3.1.1
| react-native-screens           | 2.9.0
| react-native                   | 0.63.1
| expo                           | - 
| node                           | 12.18.2
| npm or yarn                    | yarn

**Comment by kbrandwijk** [comment]
Version numbers updated after retesting on latest

**Comment by mcsky** [comment]
Allowing to pass directly the component is a very good thing because otherwise React seems to recreate the DOM of right header at each render. See https://reactjs.org/docs/reconciliation.html#elements-of-different-types

**Comment by migsc** [comment]
I ran into this today and I thankfully had a workaround but I went in and fixed it anyway because it seemed simple enough: https://github.com/react-navigation/react-navigation/pull/11592

**Comment by satya164** [comment]
If you look at the [documentation](https://reactnavigation.org/docs/elements#headertitle) and the [types](https://github.com/react-navigation/react-navigation/blob/e432c32d1e346f7c40cb42772ae5b515c76ef297/packages/stack/src/types.tsx#L139), `headerTitle` only accepts a string. React Element works because you can often render an element where you can render a string, however this is not a documented feature and may break in the future.

**Comment by kbrandwijk** [comment]
So the implementation is inconsistent, but because the documentation isn't, so the issue gets closed after 3 years 👏🏻
