### ISSUE TITLE
Deep linking only gets first query parameter to put on route params

### ISSUE THREAD

**Issue by jrobber** [react-navigation/react-navigation#8713]
**Current Behavior**

- What code are you running and what is happening?
- Include a screenshot or video if it makes sense.

Given this url: `myscheme://user/verification?confirm=1596497089568&email=person@gmail.com`
Only the first query parameter is placed on the route parameters the rest are lost.  In this case `confirm` is found and email is not.  This is also true in `getStateFromPath`.  It passes in a truncated path of `user/verification?confirm=1596497089568`.

**Expected Behavior**

- What do you expect should be happening?
- Include a screenshot or video if it makes sense.

All query parameters are added as route parameters.

**How to reproduce**

Install the sample application on the iOS simulator or a device.

Open it with the following: `xcrun simctl openurl booted rne://127.0.0.1:19000/--/simple-stack/Albums?one=1&two=2`

The log out the route params for Albums (or any other screen of your choice).

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| **iOS** or Android                 | 13.3
| react-navigation/native               |  ^5.7.0
| react-navigation-stack         | ^5.7.0
| react-navigation-bottom-tabs | ^5.7.0 
| react-navigation-drawer        | x
| react-native-reanimated        | x
| react-native-gesture-handler   | x
| react-native-safe-area-context | x
| react-native-screens           | x
| react-native                   | 0.62.2
| expo                           | x
| node                           | 10+
| npm or **yarn**                    | x

**Comment by jrobber** [comment]
Did some further testing to get a work around in, and it looks like this is the URL that react-native Linking.getInitialURL() is providing.  This does not seem to be a react-navigation error.

**Comment by secret0nodes** [comment]
@jrobber I saw your posted issue with react-native. Were you able to find a workaround in the meantime?

**Comment by Taylor123** [comment]
@jrobber Were you able to find a good solution to this? I'm debating on encoding/decoding the query parameters, but this won't solve the problem for deep links created outside of the application

**Comment by LionKing2303** [comment]
You should place a \ in front of the & like this:
xcrun simctl openurl booted rne://127.0.0.1:19000/--/simple-stack/Albums?one=1\&two=2
Then it should work fine.

**Comment by LionKing2303** [comment]
`myscheme://user/verification?confirm=1596497089568\&email=person@gmail.com`
`xcrun simctl openurl booted rne://127.0.0.1:19000/--/simple-stack/Albums?one=1\&two=2
`
