### ISSUE TITLE
@react-navigation/stack could not be found within the project 

### ISSUE THREAD

**Issue by sombizbuzzz** [react-navigation/react-navigation#8714]
"@react-native-community/masked-view": "^0.1.10",
    "@react-navigation/native": "^5.7.3",
    "react": "16.13.1",
    "react-native": "0.63.2",
    "react-native-gesture-handler": "^1.7.0",
    "react-native-reanimated": "^1.11.0",
    "react-native-safe-area-context": "^3.1.4",
    "react-native-screens": "^2.10.1"

@react-navigation/stack could not be found within the project  

here is code 

`import 'react-native-gesture-handler';
import * as React from 'react';
import {NavigationContainer} from '@react-navigation/native';
import {createStackNavigator} from '@react-navigation/stack';

export default function App() {
  return (
    <NavigationContainer>{/* Rest of your app code */}</NavigationContainer>
  );
}`

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-08-12 at 23 57 40](https://user-images.githubusercontent.com/43329978/90053208-c9dda380-dcf7-11ea-8d61-fb740339b1ed.png)

**Comment by raajnadar** [comment]
Reading the docs will help you https://reactnavigation.org/docs/stack-navigator/
