### ISSUE TITLE
gestureEnabled does not work on Android.

### ISSUE THREAD

**Issue by wave2006** [react-navigation/react-navigation#8715]
**Current Behavior**

Below is the source code:

```
import 'react-native-gesture-handler';
import { StatusBar } from 'expo-status-bar';
import React, { Component } from 'react';
import { StyleSheet, Text, View, Button } from 'react-native';
import { NavigationContainer, StackActions } from '@react-navigation/native';
import { createStackNavigator } from '@react-navigation/stack';


export default function App() {
  return (
    <NavigationContainer>
      <Stack.Navigator screenOptions={{gestureEnabled:false}}>
        <Stack.Screen name='Home' component={HomeScreen}/>
        <Stack.Screen name='Detail' component={DetailScreen}/>
      </Stack.Navigator>
    </NavigationContainer>
  );
}

class HomeScreen extends Component{

  render(){
    return(
      <View style={styles.container}>
        <Text>Welcome!</Text>
        <Button title='go to detail' onPress={()=>this.props.navigation.navigate('Detail')}/>
        <StatusBar style="auto" />
      </View>
    )
  }
}

class DetailScreen extends Component{

  render(){
    return(
      <View style={styles.container}>
        <Text>Detail screen.</Text>
      </View>
    )
  }
}

const Stack=createStackNavigator();

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});

```
**I want to close the gestures to dismiss the screen when setting 'screenOptions={{gestureEnabled:false}'.
I ran the code in Expo client with both iOS and Android,and the iOS was working correctly,BUT THE ANDROID WAS NOT!
How can i do to fix this issue?pls help and very thankful!**

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Android
| @react-navigation/native       | ^5.7.3
| @react-navigation/stack        | ^5.9.0
| react-native-gesture-handler   | ~1.6.0
| react-native-safe-area-context | ~3.0.7
| react-native-screens           | ~2.9.0
| react-native                   | https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz
| expo                           | SDK38  expo -Version 3.22.3
| node                           | v12.18.3
| npm or yarn                    | npm v6.14.6

**Comment by wave2006** [comment]
**This problem has been bothering me for a few days. I tried many times and couldn't solve it. It is very urgent. I hope someone can help. Thank you very much!**

**Comment by durdevic** [comment]
I'm managing it on the screens themselves. 

```
function SomeScreen({ route, navigation }) {

   useEffect(() => {
        navigation.setOptions({ gestureEnabled: false });
    }, []);

}
```

**Comment by orzhtml** [comment]
Is the problem solved?

**Comment by flogy** [comment]
Would be interested in a solution too.

**Comment by AoufiAbderahmaneLD** [comment]
Is the problem solved, is there any way to solve it ?
