### ISSUE TITLE
Screen bounces back and forth when closed in mode="modal"

### ISSUE THREAD

**Issue by techoutliers** [react-navigation/react-navigation#8722]
I have placed the stack navigation in bottom tab.
When the the detail page open i am removing the bottom tab bar with: 
```
props.navigation.dangerouslyGetParent().setOptions({
          tabBarVisible: false,
        });
```
and when the screen unmounts i am bringing tab bar back to the screen using this: 
```
props.navigation.dangerouslyGetParent().setOptions({
          tabBarVisible: true,
        });
```

You can see the behavior in the following image: 

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/67784003/90214930-14186f00-de35-11ea-88c1-d887186fd34f.gif)
```
"@react-navigation/bottom-tabs": "^5.8.0",
"@react-navigation/native": "^5.7.3",
"@react-navigation/stack": "^5.9.0",
```

**Comment by techoutliers** [comment]
Issue still exists

**Comment by satya164** [comment]
https://reactnavigation.org/docs/hiding-tabbar-in-screens/

**Comment by AbhiShrek** [comment]
@satya164 , The method mentioned in this document (https://reactnavigation.org/docs/hiding-tabbar-in-screens/) is an incomplete solution of a bigger problem.
It works in a very specific screen hierarchy requirements (that only first screen of stack will show the tab and other screen wont).
What if I want to show the tabs on "Home" & "Settings" screen but not on "Profile" Screen ?
Also, this way of writing code is not intuitive !! Tabs should have stacks, It makes more sense and clear understanding of code.

**Comment by KristineTrona** [comment]
This issue still exists.

**Comment by konstantinmv** [comment]
and still exists
