### ISSUE TITLE
Bottom Tab Navigator hides part of screen when nesting stack navigator  

### ISSUE THREAD

**Issue by Alarees** [react-navigation/react-navigation#8726]
**Current Behavior**

i have stack navigator  nested inside Bottom Tab Navigator, when rendering the screens inside stack navigator the bottom tab hides part of screen, means that the stack navigator calculate the space of full screen and render in it

here is a pic on how it looks :
![1](https://user-images.githubusercontent.com/18484561/90263414-f0165700-de4f-11ea-826a-1ca02227e3c9.png)

here is what it suppose to be:
![2](https://user-images.githubusercontent.com/18484561/90263573-22c04f80-de50-11ea-827b-e77cd370ccba.png)

**My Environment**

| software                      | version |
| ----------------------------- | ------- |
| Android                |6
| @react-navigation/native      |5.7.3
| @react-navigation/bottom-tabs |5.8.0
| @react-navigation/stack          |5.9.0
| react-native                  |0.65.1
| npm                  |6.13.4

**Comment by charleycesar** [comment]
I had the same problem
#8730

**Comment by Alarees** [comment]
after updating to the last version:
```
    "@react-navigation/bottom-tabs": "^5.8.0",
    "@react-navigation/core": "^5.12.3",
    "@react-navigation/native": "^5.7.3",
    "@react-navigation/stack": "^5.9.0",
```

the problem still there.

**Comment by JerakRus** [comment]
I'm facing a similar problem in navigation version 4. The problem does not always appear, but when a video component appears inside the flatlist on the page. Did you find any solution?

**Comment by Alarees** [comment]
@JerakRus , no i haven't find any solution, and i don't have `flatlist` in my component, i have `ScrollView`

**Comment by JerakRus** [comment]
@Alarees  
From the extreme workarounds, you can use tabBarVisible: false on navigationOption. The problem is that we cannot use this on all screens. Also, if you use Flatlist, it does not work correctly for me only with some components, for example, Video from react-native-navigation.

**Comment by Alarees** [comment]
after creating [this repo](https://snack.expo.io/@alarees/createbottomtabnavigator---issue), i find that the lib code is working fine.
the problem was in my code, i have component in my `render`  function making this problem
**my old code :**
```
  render() {
    return (
      <View>
        <MyHeader /> // this component makes the problem
        <ScrollView>
          <View>
            {this.renderOrdersList()}
          </View>
        </ScrollView>
      </View>
    );
  }
```
i just add `flex` to main `View`
**the new code :**
```
  render() {
    return (
      <View style={{flex:1}}>
        <MyHeader />
        <ScrollView>
          <View>
            {this.renderOrdersList()}
          </View>
        </ScrollView>
      </View>
    );
  }
```

**Comment by JerakRus** [comment]
@Alarees Thanks for sharing your solution! Unfortunately, it didn't help me. I tried to make a minimal reproducible repo but it didn't work either. My project is quite large, so it’s difficult to understand what the reason is, but it manifests itself precisely when the video from react-native-video is loaded and everything goes down exactly to the width of the bottom-bar. We'll have to use our workaround to disable it for now.
