### ISSUE TITLE
Before navigating with Drawer, the action 'NAVIGATE' with payload {"name":"screenName"} was not handled by any navigator

### ISSUE THREAD

**Issue by AmirHMousavi** [react-navigation/react-navigation#8727]
**Current Behavior**

The navigation to another screen by pressing buttons throws an error, But after navigating once from the drawer, the navigation from screens becomes possible. 

```ts
import {CommonActions, NavigationContainer, RouteProp} from '@react-navigation/native';
import {createDrawerNavigator} from '@react-navigation/drawer';
import {createStackNavigator, StackNavigationProp} from '@react-navigation/stack';
import React from 'react';
import {Button, StyleSheet, Text, View} from 'react-native';

type paramList = {
  AScreen: undefined;
  BScreen: undefined;
};

type AProps = {
  navigation: StackNavigationProp<paramList, 'AScreen'>;
  route: RouteProp<paramList, 'AScreen'>;
};

type BProps = {
  navigation: StackNavigationProp<paramList, 'BScreen'>;
  route: RouteProp<paramList, 'BScreen'>;
};

const AScreen: React.FC<AProps> = (props) => {
  return (
    <View style={styles.container}>
      <Text>This is A screen</Text>
      <Button
        title="GoTo B"
        onPress={() => {
          props.navigation.navigate('BScreen');
        }}
      />
      <Button
        title="GoTo B"
        onPress={() => {
          props.navigation.dispatch(CommonActions.navigate('BScreen'));
        }}
      />
    </View>
  );
};

const BScreen: React.FC<BProps> = (props) => {
  return (
    <View style={styles.container}>
      <Text>This is B screen</Text>
      <Button
        title="GoTo A"
        onPress={() => {
          props.navigation.navigate('AScreen');
        }}
      />
      <Button
        title="GoTo A"
        onPress={() => {
          props.navigation.dispatch(CommonActions.navigate('AScreen'));
        }}
      />
    </View>
  );
};

const Drawer = createDrawerNavigator();
const Stack = createStackNavigator<paramList>();

const SetAScreens = () => (
  <Stack.Navigator initialRouteName="AScreen">
    <Stack.Screen name="AScreen" component={AScreen} />
  </Stack.Navigator>
);
const SetBScreens = () => (
  <Stack.Navigator initialRouteName="BScreen">
    <Stack.Screen name="BScreen" component={BScreen} />
  </Stack.Navigator>
);

const App = () => {
  return (
    <NavigationContainer>
      <Drawer.Navigator initialRouteName="SetAScreens">
        <Drawer.Screen name="SetAScreens" component={SetAScreens} />
        <Drawer.Screen name="SetBScreens" component={SetBScreens} options={{swipeEnabled: false}} />
      </Drawer.Navigator>
    </NavigationContainer>
  );
};

const styles = StyleSheet.create({
  container: {flex: 1, justifyContent: 'center', alignItems: 'center'},
});

export default App;
```

![Simulator Screen Shot - iPhone 11 - 2020-08-14 at 18 31 36](https://user-images.githubusercontent.com/7797147/90271884-cfa0c980-de5c-11ea-9979-4bc9231f014e.png)

**Expected Behavior**

When the app starts to be able to navigate with the buttons that handle onPress with` navigatioin.navigate`

**How to reproduce**

- create an empty react native project with typescript template (or just javascript then remove the typings)

```sh
npx react-native init MyApp --template react-native-template-typescript
```
- Install react-navigation core, stack, and drawer packages
- Copy-paste the code above into App.tsx(js)
- Run the app in development in either android or iOS simulator or real device

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS                  | iPhone 11 (13.6)
| @react-navigation/native       |  5.7.3
| @react-navigation/stack        |  5.9.0
| @react-navigation/drawer        |  5.9.0
| react-native-gesture-handler   | 1.7.0
| react-native-safe-area-context | 3.1.4
| react-native-screens           | 2.10.1
| react-native                   | 0.63.2
| expo                           | N/A
| node                           | 12.18.0
| yarn                    | 1.22.4

**Comment by raajnadar** [comment]
Actually you need to add a name prop to your stack navigators, to identify the stack in which you need to navigate.

After that use `navigation.navigate('StackNavName', { screen: 'BScreen' })`, Try this and let me know if that worked.

https://reactnavigation.org/docs/nesting-navigators/#navigating-to-a-screen-in-a-nested-navigator

**Comment by AmirHMousavi** [comment]
@raajnadar Thanks, yep it works that way, I got confused cause the [documentation says](https://reactnavigation.org/docs/nesting-navigators#navigation-actions-are-handled-by-current-navigator-and-bubble-up-if-couldnt-be-handled), handling navigation is hierarchical, and if nested navigator cannot find the route, the parent handles it. So when we navigate in Drawer from `SetAScreens ` to `SetBScreens `, the children get registered somewhere that after that we can navigate from `AScreen` to `BScreen`  via the buttons inside the screens. 

Just one more question, how about `reset()`   for instance `props.navigation.reset({index: 0, routes: [{name: 'BScreen'}]});` Where should I define the stack name `SetBScreens`

**Comment by raajnadar** [comment]
Do you want to remove the SetAScreen from navigation history??

**Comment by AmirHMousavi** [comment]
@raajnadar yes in this scenario it can be removing `SetAScreen` .  But imagine that `SetBScreen` has one more screen  (`CScreen` which is not initialRoute), how can we `reset` to this from `AScreen`
