### ISSUE TITLE
Hidden tab is not work expected on IOS still appear tab navigator after hidden.

### ISSUE THREAD

**Issue by charleycesar** [react-navigation/react-navigation#8730]
**Current Behavior**

I use tabs with 4 tab the first root page can be visible the tab navigator but in the children of root page can't.

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-08-14 at 20 00 50](https://user-images.githubusercontent.com/5392290/90298831-0a5d2e80-de6a-11ea-8e5d-7cd639fac428.png)

**Expected Behavior**

Hidden all tab navigation when screen is child of root page.

**How to reproduce**

Try to hidden tab navigator when current page in child of root in Iphone 11 Pro Max siltill appear in bottom of device.

**Your Environment**
Mac OS Catalina 10.15.6
IOS
@react-navigation/native": "^5.7.3",
"@react-navigation/bottom-tabs": "^5.8.0",
"react-native-screens": "2.0.0-alpha.12",
react-native-cli: 2.0.1
react-native: 0.61.5

no use expo
node v13.11.0
yarn

**Comment by charleycesar** [comment]
I think this commit are wrong.
https://github.com/react-navigation/react-navigation/commit/d979dfd634c3969342803f7d988ff3439b4fe9e5

**Comment by satya164** [comment]
Closing since there's no repro.
