### ISSUE TITLE
cant click on header icons when headerTransparent=true and headerMode="float" in react navigation v5 android

### ISSUE THREAD

**Issue by peyman-hakemi** [react-navigation/react-navigation#8731]
when headerTransparent is true or headerMode is float i cant click on header icons but when i set  headerTransparent to false OR 
headerMode to screen everything working fine
`const headerdefaultStyle = {
  headerTransparent: true,
  headerTitleAlign: 'center',
  headerTitleStyle: {
    fontFamily: Fonts.type.iranSans
  },
  headerTintColor: 'white',
  headerBackTitleVisible: false
};`

`const HomeStackScreen = ({navigation}) => (
  <HomeStack.Navigator
    screenOptions={{
      headerRight: () => <DrawerIcon navigation={navigation} />,
      ...headerdefaultStyle,
      ...transitionAnimation
    }}
    headerMode="float">
    <HomeStack.Screen
      name="Home"
      component={HomeScreen}
      options={{
        headerLeft: () => <NotificationBell />,
        title: 'yas'
      }}
    />
    <HomeStack.Screen
      name="TabloGol"
      component={TabloGol}
      options={{
        title: 'tablo'
      }}
    />
  </HomeStack.Navigator>
);`

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| android       | 10
| @react-navigation/native       | ^5.7.3
| @react-navigation/stack        | ^5.9.0
| react-native-gesture-handler   | ^1.6.1
| react-native-safe-area-context | ^0.7.3
| react-native-screens           | ^2.9.0
| react-native                   | 0.62.2
| node                           | 10.16.3

**Comment by peyman-hakemi** [comment]
yes issue still exist on latest version

**Comment by simmotde** [comment]
Hi, I'm still experiencing this issue on latest versions:

```diff
+    "@react-navigation/native": "^5.7.6",
+    "@react-navigation/stack": "^5.9.3",
```

Is there a target date for merging the related PR?
