### ISSUE TITLE
useIsFocused() hook focuses before blurring previous screen

### ISSUE THREAD

**Issue by mike-hamilton** [react-navigation/react-navigation#8732]
**Current Behavior**
When switching between screens, isFocused on the "new screen" is set before !isFocused is set on the "old" screen. In the example below if switching from Screen1 to Screen2, `setShouldTabsBeTransparent(true)` on Screen2 (the one coming into focus) runs first, but then `setShouldTabsBeTransparent(false)` from Screen1 (the one being blurred) runs after, negating Screen2's `setShouldTabsBeTransparent(true)`.

```js
const isFocused = useIsFocused();

useEffect(() => {
  if (isFocused) {
    setShouldTabsBeTransparent(true);
  } else {
    setShouldTabsBeTransparent(false);
  }
}, [isFocused]);
```

**Expected Behavior**

I believe setting `!isFocused` on the "old" screen before setting `isFocused` on the new screen makes sense.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | iOS 11
| @react-navigation/native       | 5.7.3
| @react-navigation/stack        | 5.9.0
| react-native-gesture-handler   | 1.7.0
| react-native-safe-area-context | 3.1.4
| react-native-screens           | 2.10.1
| react-native                   | 0.63.2
| expo                           | n/a
| node                           | v10.22.0
| npm or yarn                    | 1.22.4

**Comment by mike-hamilton** [comment]
> Can you provide a minimal repro which demonstrates the issue? 

[Here's a snack showing the problem.](https://snack.expo.io/6WSg_ahwH).  When going from ScreenOne to ScreenTwo, ScreenTwo is blurred (focused) before ScreenOne is unblurred (unfocused).

**Comment by christophermark** [comment]
I noticed the exact same behavior today.
I got things to work by using a `setTimeout` in the onFocus, but it's more of a workaround to some unexpected behavior

**Comment by satya164** [comment]
I took a look and I don't think it's possible to gurrantee update order. `isFocused` will be `true` for the focused component as soon as it mounts, even before the effect is run and for the unfocused component, it needs to wait for the events.

However, you also shouldn't be use `useIsFocused()` to perform side-effects. You can use the `focus` and `blur` events which gurrantee the order in which they fire: https://reactnavigation.org/docs/navigation-events/
