### ISSUE TITLE
white transition effect on iOS

### ISSUE THREAD

**Issue by taduyde** [react-navigation/react-navigation#8737]
**Current Behavior**
- I have an issue with the transition of navigation, sometimes the transition takes white transition effect. Please see the gif image to more detail

![ezgif-1-2061cf6e192b](https://user-images.githubusercontent.com/8236997/90362618-39061f80-e08b-11ea-9deb-d0beb343ba49.gif)

**Expected Behavior**

**How to reproduce**

- You must provide a way to reproduce the problem. If you are having an issue with your machine or build tools, the issue belongs on another repository as that is outside of the scope of React Navigation.
- Either re-create the bug on [Snack](https://snack.expo.io) or link to a GitHub repository with code that reproduces the bug.
- Explain how to run the example app and any steps that we need to take to reproduce the issue from the example app.
- Keep the repro code as simple as possible, with the minimum amount of code required to repro the issue.
- Before reporting an issue, make sure you are on latest version of the package.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |
| @react-navigation/native       |5.5.1
| @react-navigation/stack        |5.5.1
| react-native-gesture-handler   |1.7.0
| react-native-safe-area-context |
| react-native-screens           |2.4.0
| react-native                   |0.62.2
| expo                           |
| node                           |
| npm or yarn                    |

**Comment by taduyde** [comment]
> The versions mentioned in the issue for the following packages differ from the latest versions on npm:
> 
> * `@react-navigation/native` (found: `5.5.1`, latest: `5.7.3`)
> * `@react-navigation/stack` (found: `5.5.1`, latest: `5.9.0`)
> 
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?
the issue still existing on the latest version

**Comment by satya164** [comment]
Closing since you didn't provide a repro to debug the issue.
