### ISSUE TITLE
Error null is not object (evaluating 'percent.includes') After migrating from rn 0.60 to rn 0.63.2 on ios only

### ISSUE THREAD

**Issue by khalilTN** [react-navigation/react-navigation#8738]
**Current Behavior**

After migrating from rn 0.60 to rn 0.63.2, i got this error on ios, i'm not sure of its location
null is not object (evaluating 'percent.includes')
![Simulator Screen Shot - iPhone 11 - 2020-08-17 at 14 46 58](https://user-images.githubusercontent.com/9549132/90404060-c18bbc80-e099-11ea-9fb2-dd8ed6fdfb58.png)
![Simulator Screen Shot - iPhone 11 - 2020-08-17 at 14 44 00](https://user-images.githubusercontent.com/9549132/90404186-f0a22e00-e099-11ea-97a6-b9858944db03.png)

**Expected Behavior**

No exception

**How to reproduce**

Migrating from react-native@0.60.0 to 0.63.2

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | iOS
| react-navigation | 3.11.0
| react-native                   | 0.63.2
| expo                           | nope
| node                           | 14.7.0
| npm or yarn                    |  npm@6.14.7

**Comment by satya164** [comment]
React Navigation 3.x is not supported. Please upgrade to 4.x
