### ISSUE TITLE
error: node_modules/@react-navigation/stack/src/views/assets/back-icon-mask.png: Cannot find module 'expo-asset/tools/hashAssetFiles

### ISSUE THREAD

**Issue by Xeizzeth** [react-navigation/react-navigation#8742]
**Current Behavior**  
  
I'm running two commands:  
**react-native start --reset-cache** in one console;  
and **react-native run-android** in another console.  
  
And they're failing with _"error: node_modules/@react-navigation/stack/src/views/assets/back-icon-mask.png: Cannot find module 'expo-asset/tools/hashAssetFiles'"_  

And I tried everything. Found these two issues:
https://github.com/react-navigation/react-navigation/issues/7950
https://github.com/microsoft/vscode-react-native/issues/878

And nothing described there helps. Including just plain removing _react-native-unimodules_, since it was suggested in the comments that this issue happens when you use unimodules and react navigation together.  

**Expected Behavior**

An application builds and launches in android emulator.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |Android
| react-navigation               |^4.4.0
| react-navigation-stack         |^2.8.2
| react-navigation-tabs          |^5.8.0 (bottom tabs)
| react-navigation-drawer        |^2.5.0
| react-native-reanimated        |~1.13.0
| react-native-gesture-handler   |~1.7.0
| react-native-safe-area-context |~3.1.4
| react-native-screens           |~2.10.1
| react-native                   |0.63.2
| expo                           |3.24
| node                           |14.7.0
| npm or yarn                    |both

**Comment by Xeizzeth** [comment]
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?

Yes. And it is totally unrelated to react-navi-tabs.

**Comment by Xeizzeth** [comment]
The problem described is resolved, but happened another one - the app is launching but it doesn't show the main screen, so I'm closing this issue, since the new problem is unrelated.

**Comment by alidplus** [comment]
possible solutions:
check the .yarnclean file if you use "yarn autoclean" (in project root). remove "assets" and "image" lines
