### ISSUE TITLE
SafeAreaView hides after navigation

### ISSUE THREAD

**Issue by johnneuland** [react-navigation/react-navigation#8747]
**Current Behavior**

The SafeAreaView (red coloured) works well on all screens except this one, even though I am using the same styling everywhere. It is supposed to be shown at the top and bottom both. Here it is only shown at the bottom and not at the top. In this case, it is being hidden by the View (in pink).

I am afraid this could be because of how I navigate to this screen from the previous one. I fixed it for a second or two (not sure how it happened) but when I went back and navigated to the same screen again, the safeAreaView was hidden again.

<img width="321" alt="Screenshot 2020-08-14 at 10 42 03" src="https://user-images.githubusercontent.com/69582269/90659722-51ba3500-e245-11ea-9f86-b62539409eb0.png">

**Expected Behavior**

SafeAreaView should be visible on top and bottom both.

**How to reproduce**

```
export const JourneyResultScreen: React.FunctionComponent = () => {
  return (
    <SafeAreaView style={styles.safeAreaViewContainer}>
      <View style={styles.container}>
        <Text>HELO</Text>
      </View>
    </SafeAreaView>
  );
};

const styles = StyleSheet.create({
  safeAreaViewContainer: { flex: 1, backgroundColor: 'red'},
  container: {  flex: 1, backgroundColor: 'pink'},
});
```
Navigation:

App.tsx:
```
                <NavigationStack.Screen
                  name="Journey"
                  component={JourneyScreenNavigation}
                  options={{
                    headerShown: false,
                    ...TransitionPresets.FadeFromBottomAndroid,
                  }}
                />
```
```

const NavigationStack = createStackNavigator();
const config = {
  animation: 'spring',
  config: {
    stiffness: 1000,
    damping: 500,
    mass: 3,
    overshootClamping: true,
    restDisplacementThreshold: 0.01,
    restSpeedThreshold: 0.01,
  },
};

export const JourneyScreenNavigation: React.FC = () => {
  return (
    <NavigationStack.Navigator initialRouteName="Journey" mode="modal">
      <NavigationStack.Screen
        name="Journey"
        component={JourneySearchScreen}
        options={{ headerShown: false }}
      />
      <NavigationStack.Screen
        name="JourneyMap"
        component={JourneyResultScreen}
        options={{
          headerShown: false,
          gestureEnabled: false,
          cardStyleInterpolator:
            CardStyleInterpolators.forFadeFromBottomAndroid,
        }}
      />
      <NavigationStack.Screen
        name="TripsNavigation"
        component={AvailableTripsNavigation}
        options={{
          gestureEnabled: false,
          headerShown: false,
          cardStyleInterpolator:
            CardStyleInterpolators.forFadeFromBottomAndroid,
        }}
      />
    </NavigationStack.Navigator>
  );
};
```
The issue is in the second screen from the stack.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| @react-navigation/native       | ^5.7.3
| @react-navigation/native-stack       | ^5.7.0
| @react-navigation/stack        |^5.9.0
| react-native-safe-area-context |^3.1.1
| react-native                   | 3.0.4
| yarn                    | 1.21.1

**Comment by johnneuland** [comment]
> The versions mentioned in the issue for the following packages differ from the latest versions on npm:
> 
> * `@react-navigation/native` (found: `5.7.0`, latest: `5.7.3`)
> * `@react-navigation/stack` (found: `5.7.0`, latest: `5.9.0`)
> 
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?

Yes, they still exsist.

**Comment by ThoughtZer** [comment]
@johnneuland I have the same problem, have you solved it now？
```
Here it is only shown at the bottom and not at the top
```

```
"@react-navigation/bottom-tabs": "^5.11.3",
"@react-navigation/material-top-tabs": "^5.3.11",
"@react-navigation/native": "^5.9.0",
"@react-navigation/stack": "^5.13.0",
"react-native-safe-area-context": "^3.1.9",
  "react-native-safe-area-view": "^1.1.1",
```

**Comment by ThoughtZer** [comment]
import { getStatusBarHeight } from 'react-native-iphone-x-helper';

```js
<Stack.Navigator 
  screenOptions={{ 
      headerStatusBarHeight: getStatusBarHeight(), 
  }}
/>
```
like this

@johnneuland
