### ISSUE TITLE
App Crashing after login or logout

### ISSUE THREAD

**Issue by codertech120386** [react-navigation/react-navigation#8750]
**Current Behavior**

- What code are you running and what is happening?

Routing is handled through 2 files

1) CofficNavigator.tsx

This file has all the routing
 here BottomNavigator is a tab Navigator and AuthNavigator is a stack navigator
Before the app crashing all the correct state is set but it just crashes

`export const FinalStackNavigator = createStackNavigator();
export const FinalNavigator = (props: any) => {
  const authContext = useContext(AuthContext);
  const [signedIn, setSignedIn] = useState<boolean | null>(
    authContext.isLoggedIn
  );
  useEffect(() => {
    if (authContext.isLoggedIn !== signedIn && !authContext.isLoading) {
      setSignedIn(authContext.isLoggedIn);
    }
  }, [authContext]);

  return (
    <FinalStackNavigator.Navigator>
      {signedIn ? (
        <>
          <FinalStackNavigator.Screen
            name="BottomNavigator"
            component={BottomNavigator}
            options={{ headerShown: false }}
          />
        </>
      ) : (
        <>
          <FinalStackNavigator.Screen
            name="AuthNavigator"
            component={AuthNavigator}
          />
        </>
      )}
    </FinalStackNavigator.Navigator>
  );
};`

2) AppNavigator.tsx

`export const AppNavigator = (props: any) => {
  return (
    <NavigationContainer>
      <FinalNavigator />
    </NavigationContainer>
  );
};`

After login I am changing the state in AuthContext and I am trying to use that to decide which Navigator to load

I am not getting any crash logs in the React Native Debug console so I checked IOS Simulator Debug console and the error there was 

`com.apple.CoreSimulator.SimDevice.957FA264-501C-44C3-80F3-9E8D1F600A1E[15500] (UIKitApplication:host.exp.Exponent[e036][rb-legacy][15601]): Service exited due to SIGABRT`

**Please Note :-** 

1. I am using Expo if it matters 
2. AuthContext has the right values set. 
3. Next time I open the app the app redirects correctly i.e :- If I was trying to login it takes me to HomeScreen and if I was trying to logout then it takes me to AuthScreen.

I am attaching a screen recording as I think that is the best way to show what is happening

**Video Link :-** https://fisico-dhaval.s3.ap-south-1.amazonaws.com/Screen+Recording+2020-08-20+at+5.38.06+PM.mov

**Expected Behavior**

- I expect the navigator to redirect me to the correct Navigator and not crash

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Both
| @react-navigation/native       | 5.7.0
| react-native                   | "https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz"
| expo                           | 38.0.8
| node                           | 14.4
| npm or yarn                    | npm

If any other code snippets are needed then do lemme know and I cannot deploy my app because of this issue.

**Comment by satya164** [comment]
Closing since you didn't provide a repro to debug the issue.
