### ISSUE TITLE
React-Navigation 5 - hide header shadow not working?

### ISSUE THREAD

**Issue by Brumor** [react-navigation/react-navigation#8751]
**Current Behavior**

I'm trying to hide the shadow under the header, I've tried everything I could find on the internet and everything I could think of, as can be seen here:

```js
<Stack.Screen
        name="DetailsCard"
        component={DetailsCard}
        options={({}) => ({
          headerStyle: {
            backgroundColor: '#F1F2F5',
            shadowOffset: {
              width: 0,
              height: 0,
            },
            borderBottomWidth: 0,
            elevation: 0,
            shadowOpacity: 0,
          },
          shadowOffset: null,
          headerTopInsetEnabled: false,
          headerHideShadow: false,
          headerLargeTitleHideShadow: false,
          contentStyle: {
            borderBottomWidth: 0,
            elevation: 0,
            shadowOpacity: 0,
            shadowOffset: {
              width: 0,
              height: 0,
            },
          },
        })}
      />
```
And yet there's still a fine line:

<img width="482" alt="Screenshot 2020-08-20 at 16 19 17" src="https://user-images.githubusercontent.com/19175088/90783908-f64d7d00-e300-11ea-844f-aaf3e1f7e13e.png">

I want to get rid of it, is there something I am missing?

Edit: here are the versions I have:

```json
"@react-navigation/bottom-tabs": "^5.6.1",
    "@react-navigation/native": "^5.6.1",
    "@react-navigation/stack": "^5.8.0",
`
``

**Comment by Brumor** [comment]
I have updated the packages and still see the line.

**Comment by Brumor** [comment]
Okay, I set `headerHideShadow` to false, which was a typo! My bad

**Comment by rahulnainwal107** [comment]
options={{headerShadowVisible: false}} can be used in version 6.
