### ISSUE TITLE
@react-navigation/web does not work TypeError: (0, _core.withNavigation) is not a function

### ISSUE THREAD

**Issue by karol-bisztyga** [react-navigation/react-navigation#8754]
**Current Behavior**

following error is thrown:
```
TypeError: (0, _core.withNavigation) is not a function. (In '(0, _core.withNavigation)(LinkWithNavigation)', '(0, _core.withNavigation)' is undefined)
```

**Expected Behavior**

Working app(the rest of the code is just the default generated)

**How to reproduce**

1. Create a react native app like that: `create-react-native-app my-project`
2. Chose 'Default new app'
3. Add following dependencies to `package.json`:
```
"@react-navigation/core": "^5.12.3",
"@react-navigation/native": "^5.6.1",
"@react-navigation/stack": "^5.6.2",
"@react-navigation/web": "^1.0.0-alpha.9",
"react-navigation": "^4.4.0",
"react-navigation-stack": "^2.8.2"
```
4. run `yarn`
5. run `cd ios && pod install && cd -`
6. run metro `yarn start --reset-cache`
7. fire up xcode
8. build & run the app, this works fine
9. Now add this import `import { createBrowserApp } from '@react-navigation/web';` to `App.js`. Here is the result:
<img width="338" alt="Screen Shot 2020-08-21 at 12 56 40 PM" src="https://user-images.githubusercontent.com/59833830/90883312-d9bb4e80-e3ad-11ea-9b05-900f31d9e7dd.png">

snack link: https://snack.expo.io/jDUoOUUoI

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |iOS 10.0
| @react-navigation/native       |5.6.1
| react-native                   |0.62.2
| expo                           |-
| node                           |v14.5.0
| npm or yarn                    |1.22.4

**Comment by karol-bisztyga** [comment]
> The versions mentioned in the issue for the following packages differ from the latest versions on npm:
> 
> * `@react-navigation/native` (found: `5.6.1`, latest: `5.7.3`)
> * `@react-navigation/stack` (found: `5.6.2`, latest: `5.9.0`)
> 
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?

The problem persists after updating those packages

**Comment by satya164** [comment]
https://reactnavigation.org/docs/web-support/
