### ISSUE TITLE
Stack animation sometimes doesn't work with Reanimated 2 (TurboModules)

### ISSUE THREAD

**Issue by AlexeyVlasenko** [react-navigation/react-navigation#8756]
**Current Behavior**

Stack animation doesn't work sometimes.
![Screen Recording 2020-08-21 at 22 45 43](https://user-images.githubusercontent.com/25363536/90929811-26307980-e402-11ea-9aa6-6aaf804a39ef.gif)

**Expected Behavior**

Animations should work all time.

**How to reproduce**

Snack (It's just code, please run it locally with Reanimated 2 set up): https://snack.expo.io/Rq8gJNJIM

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| @react-navigation/native       | ^5.7.3
| @react-navigation/stack        | ^5.9.0
| react-native-gesture-handler   | ^1.7.0
| react-native-safe-area-context | ^3.1.6
| react-native-screens           |^2.10.1
| react-native                   |0.63.2
| react-native-reanimated                   |^2.0.0-alpha.5

**Comment by enesozturk** [comment]
Same issue with exact same packages. With reanimated 2, stack navigation animation sometimes not working. It is navigating other page without transition.

Edit 1: Putting Stack Navigator into the Tab Navigator solving the issue. But if the Stack Navigator in root, problem still exists..

Edit 2: I got the same when the Stack Nav inside Tab Nav...

**Comment by outaTiME** [comment]
something similar here, randomly I know that it is frozen at the beginning of the transition and from that moment it hangs and I have to kill expo

![image](https://user-images.githubusercontent.com/140472/96311945-f6a48480-0fe0-11eb-843e-615dd7ef6774.png)

Im running on Expo and I am using the same packages except for react-native-reanimated that I am using the version react-native-reanimated@2.0.0-alpha.6.1,

**Comment by fierysolid** [comment]
I have this issue as well

**Comment by enesozturk** [comment]
This issue is too old and I did not get this issue again after new releases. If you think you have this issue, please share your version numbers guys.
