### ISSUE TITLE
Expo App is freezing when tap on bottom navigation or stack navigation for routing to other screen

### ISSUE THREAD

**Issue by syedsaadqamar** [react-navigation/react-navigation#8757]
**Current Behavior**
- When clicking on any navigation it will route and freeze the app

**Expected Behavior**

- I have bottom navigation and under the bottom tabs, it has a stack, then tap it should route and work normally.

**How to reproduce**

- It was working before a week but suddenly it stops working when I remove node_module and reinstall the node_module using `yarn install` and the same behavior for `npm install` and I also note that there are lots of changes in yarn.lock files

React Native Environment Info:
System:
OS: macOS 10.15.6
Processor: 3.1 GHz Dual-Core Intel Core i7
Memory: 16 GB 1867 MHz DDR3

Expo global version: 3.24.2

*Package.json file*
```
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject",
    "test": "jest --watchAll"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@expo/vector-icons": "^10.0.0",
    "@iomechs/rn-color-palette": "^0.0.4",
    "@react-native-community/masked-view": "0.1.10",
    "@react-navigation/bottom-tabs": "^5.6.1",
    "@react-navigation/native": "^5.6.1",
    "@react-navigation/stack": "^5.6.2",
    "expo": "~38.0.8",
    "expo-asset": "~8.1.7",
    "expo-constants": "~9.1.1",
    "expo-font": "~8.2.1",
    "expo-splash-screen": "~0.3.1",
    "expo-status-bar": "^1.0.2",
    "native-base": "^2.13.12",
    "react": "~16.11.0",
    "react-dom": "~16.11.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz",
    "react-native-gesture-handler": "~1.6.0",
    "react-native-safe-area-context": "~3.0.7",
    "react-native-screens": "~2.9.0"
  },
  "devDependencies": {
    "@babel/core": "^7.8.6",
    "@types/react": "~16.9.23",
    "@types/react-native": "~0.62.13",
    "babel-preset-expo": "~8.1.0",
    "jest-expo": "~38.0.0",
    "typescript": "~3.9.5"
  },
  "private": true
}
```

**Comment by Stringsaeed** [comment]
@syedsaadqamar try to check the screen itself if there're any crashes or any infinite rerender, it happens with me all the time when the screen contains infinite rerender like setState in componentDidMount or in useEffect this could create freezing issue

**Comment by syedsaadqamar** [comment]
@Stringsaeed your mention issues can be there but when I build a fresh project with tabs it should not have any infinite rerender, it seems it is an internal crash of `react-navigation` when I using Stack under the bottom tabs

**Comment by sunfan1** [comment]
I have the same problem. Is there any way to solve it

**Comment by JerakRus** [comment]
I have the same problem in the cli in debug mode. Instead of a screen component, I just use View. It turns out the following structure:
```
const RootStack = createStackNavigator()
const Tab = createBottomTabNavigator()
const HomeStack = createStackNavigator()
const OrdersStack = createStackNavigator()
const DialogsStack = createStackNavigator()

const Home = () => {
  return (
    <HomeStack.Navigator>
      <HomeStack.Screen name='Home' component={View}/>
    </HomeStack.Navigator>
  )
}

const Orders = () => {
  return (
    <OrdersStack.Navigator>
      <OrdersStack.Screen name='Orders' component={View}/>
    </OrdersStack.Navigator>
  )
}

const Dialogs = () => {
  return (
    <DialogsStack.Navigator>
      <DialogsStack.Screen name='Dialogs' component={View}/>
    </DialogsStack.Navigator>
  )
}

const BottomTabs = () => {
  return (
    <Tab.Navigator initialRouteName='Orders'>
      <Tab.Screen name='Home' component={Home}/>
      <Tab.Screen name='Orders' component={Orders}/>
      <Tab.Screen name='Dialogs' component={Dialogs}/>
    </Tab.Navigator>
  )
}
```
Has anyone found a solution?

**Comment by satya164** [comment]
https://reactnavigation.org/docs/troubleshooting#app-is-not-working-properly-when-connected-to-chrome-debugger

**Comment by JerakRus** [comment]
Thanks for the link, it's good that the documentation says it and it's bad that I haven't seen it. By the way, an interesting and strange moment is that this bug manifests itself in Chrome, everything works fine with React Native Debugger.

**Comment by lemin-ou** [comment]
@syedsaadqamar did you find the solution to that problem , I'm getting it also

**Comment by lemin-ou** [comment]
I figure it out the problem was that react-navigation save the state of the components linked with the tabs but a stack is not a component so its state can't be saved so that the problem 
Solution: 
add : `options={{ unmountOnBlur: true }}` to the tab that contains the nested stack

**Comment by lucasmrl** [comment]
@lemin-ou saved me a few hours of debugging. ;)
