### ISSUE TITLE
Reactnavigation.org is useless because of a bug.

### ISSUE THREAD

**Issue by Cetger** [react-navigation/react-navigation#8761]
Hi guys, it is not bug about this library but i wanted to inform you because it forces me, I wanted to report it because I think there might be people who are experiencing this issue like me.
In your official website, scroll doesnt work as i expected. For example when i want to copy anything on browser, ı start to select and scroll to bottom side, if part of text what i wanted to copy is not fit on one screen page, i have to use scroll. I cant scroll and copy in the same time in your docs.

![Screenshot from 2020-08-23 13-01-27](https://user-images.githubusercontent.com/31896026/90975954-867a0500-e541-11ea-9bfa-82d9986212af.png)

F.e. i want to copy until line where tabbar element finish but scroll doesnt work. Because of this feature i had to copy all code to my editor, then i had to delete other parts which i dont want to use. As i said it is not a bug even so i had problem about it, maybe you wanna fix it. 
By the way I'm using Ubuntu 18.04, 
Chromium Version 84.0.4147.105

**Comment by Belgin-Android** [comment]
@Cetger  I Think This Bug Is Fixed I Am Not Facing Any Issues Like What You Have Mentioned Above I Think You Can Close This Issue
