### ISSUE TITLE
colors are not updating after theme changed

### ISSUE THREAD

**Issue by Bayramito** [react-navigation/react-navigation#8766]
Hello,

I made a dark theme mode in my app. Im getting a observable value from a MobX store, changing the theme in my app by this value and a switch. It's a simple one. All the colors are changing when i trigger the switch, all the components etc... but only bottom tab navigator's background is staying same. But when i take an action on it, like clicking to a different tab, than it's changes too. 

I think the problem is that, it's taking it's color once it is mounted, than, i go and change all the colors in the one of it's child components, its not being notified to re-render itself to show new colors. becouse its still mounted or something... thats my theory.

Is there any way to fix that?

		"@react-navigation/bottom-tabs": "^5.2.7",
		"@react-navigation/compat": "^5.1.9",
		"@react-navigation/material-bottom-tabs": "^5.1.10",
		"@react-navigation/material-top-tabs": "^5.1.9",
		"@react-navigation/native": "^5.1.6",
		"@react-navigation/stack": "^5.2.13",

**Comment by Bayramito** [comment]
"@react-navigation/native": "^5.1.6",

**Comment by Bayramito** [comment]
Of course

25 Ağu 2020 Sal 18:15 tarihinde github-actions[bot] <
notifications@github.com> şunu yazdı:

**Comment by satya164** [comment]
Closing since you didn't provide a repro to debug the issue.
