### ISSUE TITLE
Get parent Header height

### ISSUE THREAD

**Issue by vikjovanov** [react-navigation/react-navigation#8767]
Hi,

Before when I wanted to get the header height, I could just do Header.HEIGHT. 
However, now I have to use a context or hooks to get the header height.

My problem is that I have a stack navigation in which there are 2 views that share the same header. The header is defined and stylized in the navigationOptions of the stackNavigator itself but I didn't define height for it so that it can fit by itself..

I would like to be able to get the size of this header from a child view. But when I use the hooks or the context, I keep getting 0 which makes sense since the child views have headerShown=false. It's pretty important to me because I need to use it for verticalOffset in my KeyboardAvoidingView.

Is it still possible to do that? I'm still on React Navigation 4.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| react-navigation               | 4.1.1
| react-navigation-stack         | 2.8.2
| react-native-safe-area-context | 3.12
| react-native-screens           | 2.10.1
| react-native                   | 0.63.2
| node                           | 10.16.1
| npm or yarn                    | 6.13.4

**Comment by satya164** [comment]
You should hide the header in the parent screen containing the child stack instead, so the child stack will have a header and you can get its height.
