### ISSUE TITLE
The action 'GO_BACK' was not handled by any navigator

### ISSUE THREAD

**Issue by escusado** [react-navigation/react-navigation#8771]
**Current Behavior**

- What code are you running and what is happening?
I have a `BottomTabNavigator` that contains a nested `StackNavigator`, when invoking `navigator.goBack()` I get indeed taken back to the Tab Nav but an error pops up.

- Include a screenshot or video if it makes sense.
![image](https://user-images.githubusercontent.com/93747/91238164-06e76400-e702-11ea-8729-948ab4f443a3.png)

**Expected Behavior**

- I should be taken back to the caller Navigator with no error

**How to reproduce**

- Create a BottomTabNavigator
- At least one tab should contain a `StackNavigator`
- Create a button at the first screen of the nested `StackNavigator` that calls `navigator.goBack()`

**Your Environment**

| software                      | version |
| ----------------------------- | ------- |
| iOS and Android                |
| @react-navigation/native      | 5.7.3
| @react-navigation/bottom-tabs | 5.8.0
| react-native-screens          | 2.10.1
| react-native                  | 0.63.2
| expo                          |8.3.0
| node                          | 
| npm or yarn                   | yarn

**Comment by satya164** [comment]
Closing since you didn't provide a repro to debug the issue.

**Comment by mrvirus9898** [comment]
Double check that none of your bottom tab navigators have independent Navigation Containers

```
<NavigationContainer independent={true}>
```

Independent Navigation Containers attached to Bottom Tab navigators will isolate your tab navigators from each other.

**Comment by rohitninawe** [comment]
**Error Cause**: goBack() or pop() is getting called multiple times. Sometimes onPress event gets called many times. You can check by adding console.log().

**How to Solve**: you need to [throttle](https://lodash.com/docs/#throttle) the onPress function.

**Example**: `export default class Test extends PureComponent {
    constructor(props) {
        super(props)
    
        this.state = {
             
        }
        this.onPress = throttle(this.onPress, 500, {trailing: false})
    }
    

    onPress = () => {
        console.log("going back")
        this.props.navigation.pop();
        //this.props.navigation.goBack();
    }
     
    render() {
        return (
            <View>
                <Text>Hello World!</Text>
            </View>
        )
    }
}`

**Comment by rosnaib11** [comment]
Got same issue, even I use debounce still called twice sometimes

**Comment by asalha** [comment]
I had the same issue and I found the problem:

Don't use navigation.goBack(), just use navigation.navigate("PreviousScreenName").

**Comment by joshuapinter** [comment]
We're on a hybrid Android app that has some nested React Native screens. So, when the stack is only one screen (i.e. you can't go "back") that actually means we need to exit React Native to go back to the native screen. To accomplish this, we're doing something like this: 

```js
if ( navigation.canGoBack() )
  navigation.goBack();
else
  BackHandler.exitApp();
```

This is on Version 5.x of `react-navigation`.

**Comment by sultanularefin** [comment]
`BackHandler.exitApp();`

This worked to programmatically exit the application, on Version 6.x of react-navigation.

**Comment by realjjaveweb** [comment]
This error happened to me when I was going back from a function without exiting the function.
**Basically, I forgot to put `return` there :facepalm:** 

this is wrong:
```
    const handleForm = () => {
        if (someCondition === null) navigation.goBack();
        // this continues into the oblivion
```

this is right:
```
    const handleForm = () => {
        if (someCondition === null) return navigation.goBack();
        // this escapes the sorcery! :-)
```

**Comment by steelegg** [comment]
Function components can be used like this

```
const getThrottle = (() => {
  let lastPress: null | onPressFunctionType = null;
  return (fun: onPressFunctionType) => {
    if(typeof lastPress === 'function' && lastPress === fun) {
      return lastPress;
    } else {
      lastPress = typeof fun === 'function'
        ? throttle(fun, 500, { trailing: false })
        : () => {}
      return lastPress
    }
  };
})();
```
```
const _onPress = getThrottle(onPress);
<Pressable onPress={(e) => { _onPress(e)}}><Pressable/>
```

**Comment by AhmedRazaSiddiqui** [comment]
You can check with can go back that navigation can go back or not.

`    if (canGoBack()) {
      goBack();
    } else {
      navigate("Home");
    }`

**Comment by mr-abdellah** [comment]
Thank you so much dude <3

**Comment by rakeshkumar-23** [comment]
I was facing the same issue. I noticed that I had called the goBack() function two times. And I have removed the duplicate code.

**Comment by anieve01** [comment]
This worked for me:

`
import {
  useNavigation} from "expo-router";
const navigation = useNavigation() 

  const resetAndDismissModal = () => {
    try {
      resetTrackPlayer();
      if (router.canGoBack()) {
        router.back();
      } else {
        navigation.dismiss();
      }
    } catch (e) {}
  };`

**Comment by ShristiC** [comment]
@anieve01 thanks for your code! This helped.

**Comment by fehmisener** [comment]
This might also help 😄 
```js
    const safeGoBack = () => {
        if (navigation.canGoBack()) {
            navigation.goBack();
        } else {
            // If we can't go back, navigate to the main screen
            navigation.navigate('Main');
        }
    };
```

**Comment by Steven-zion** [comment]
for anyone who got this error and they are using expo-router make sure you use router.push() instead of router.replace()

**Comment by struckchure** [comment]
> for anyone who got this error and they are using expo-router make sure you use router.push() instead of router.replace()

Yep, this worked for me!

Although I'm using `react-navigation` directly in an `expo` project
