### ISSUE TITLE
Hide/Show bottom tab bar dinamically generates jumpy animation on Android navigation

### ISSUE THREAD

**Issue by roni-castro** [react-navigation/react-navigation#8774]
**Current Behavior**

- Our app had react-navigation v3 (with react native cli) and had the feature of showing the bottom tabBar in the main screens and hiding it when the user navigates to another one (changing the stack), but after migration from v3 to the v4, the transition of closing the screen in some Android devices are slower, and apparently every time I navigate to a stack it renders all the stack navigation that exists inside the bottom tab navigation. It gets worse on the production app that have 5 tabs and have some animation during the opening (Loading Skeleton).

Here is a sample project that replicates this behavior on the emulator `Galaxy Nexus API 29 - Android 10` 
<img width="896" alt="Captura de Tela 2020-08-26 às 13 55 30" src="https://user-images.githubusercontent.com/24610813/91336959-14a3f480-e7a9-11ea-8ee8-e9e1f5610ed1.png">

![slow react-navigation](https://user-images.githubusercontent.com/24610813/91316441-2ed0d900-e78f-11ea-8b47-4094e90ca426.gif)

Code of the example (https://snack.expo.io/@ronicesarrc/slow-react-navigation-example): 

```
import React from 'react';
import { createStackNavigator } from 'react-navigation-stack';
import { createBottomTabNavigator } from 'react-navigation-tabs';
import {
  createAppContainer,
  createSwitchNavigator
} from "react-navigation";
import { SafeAreaProvider } from 'react-native-safe-area-context';
import Example, { EmptyScreen } from "./screens/Example";
import { StatusBar } from 'react-native';

const SlowStack = createStackNavigator({
  SlowExample: { screen: Example, params: { tabBarVisible: true } },
  Details: {
    screen: EmptyScreen,
    navigationOptions: {
      headerTitle: "Slow on Close"
    },
    params: { tabBarVisible: false }
  }
});

SlowStack.navigationOptions = ({ navigation }: any) => {
  // console.warn('SlowStack')
  const { params = { tabBarVisible: true } } = navigation.state.routes[navigation.state.index];
  return {
    tabBarLabel: 'SlowStack',
    tabBarVisible: params.tabBarVisible // The change on the visibility of tabBar generates the laggy transition
  };
};

const MainTabs = createBottomTabNavigator({
  SlowStack: {
    screen: SlowStack,
    navigationOptions: {
      tabBarLabel: "SlowStack"
    }
  },
});

const AppSwitchNavigator = createSwitchNavigator({
  Auth: {
    screen: MainTabs
  },
});

const AppNavigator = createAppContainer(AppSwitchNavigator);

export const App = () => (
  <SafeAreaProvider>
    <StatusBar barStyle="dark-content" />
    <AppNavigator />
  </SafeAreaProvider>
)

export default App;
```

**Expected Behavior**

- The transition to be faster and to allow hide/show the tabBar as show in here https://snack.expo.io/@ronicesarrc/slow-react-navigation-example to all android devices.

**How to reproduce**

- Add a bottom tab bar navigation and on the stack of one of these tabs, change the visibility of the bottom tab bar dinamically when the user navigates to a new screen, i.e, show the bottom ta bar on the main screen and hide it navigation to a new screen.
This problem happened on emulator `Galaxy Nexus API 29 - Android 10` with the existing code [here](https://snack.expo.io/@ronicesarrc/slow-react-navigation-example), and the device `Moto G7 Play, Android 10`.
Is there a solution to this animation problem?

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |android
| react-navigation       |  ˆ4.4.0
| react-navigation-stack        |  ^2.8.2
| react-native-gesture-handler   | ~1.6.0
| react-native-safe-area-context | ^3.1.7
|  react-navigation-tabs | ^2.9.0
| react-native-reanimated | ^1.13.0
| react-native-screens | ~2.9.0
| react-native                   | 0.63.2
| expo                           | 
| node                           | 13.10.1
| npm or yarn                    | yarn

**Comment by roni-castro** [comment]
Probably this [problem](https://reactnavigation.org/docs/hiding-tabbar-in-screens/) is happening: 
`Some tab navigators such as bottom tab navigator also have a tabBarVisible option which can be used to hide the tab bar based on instructions in the Screen options resolution guide. However, we don't recommend using it since showing/hiding the tab bar mid-navigation can affect the animation of the stack navigator causing glitchy behaviour.` =/

I will try to refactor the navigation to see if it makes better. It would be nice a warning when using `tabBarVisible` of bottom-tabs, to avoid using it.

**Comment by roni-castro** [comment]
Closing as after reading all issues related to this issue there still is no simple solution to this problem but to remove the nested Stack from the TabBar and refactor the whole navigation =/
Duplicate of https://github.com/react-navigation/react-navigation/issues/6841

**Comment by steele-cjf** [comment]
so,there is no solution？

**Comment by roni-castro** [comment]
> so,there is no solution？

The only solution that worked for us is the one described here in the docs https://reactnavigation.org/docs/hiding-tabbar-in-screens/, which is to reorganize the navigations so it hides it automatically, but hiding it dynamically causes this problem and probably is not supported anymore since version 4.

Example of this reorganization https://snack.expo.io/@ronicesarrc/react-navigation-with-bottom-tabs-stack-navigator-switch-navigator
