### ISSUE TITLE
Unable to resolve module `./views/Header/Header`

### ISSUE THREAD

**Issue by Gjoshi3107** [react-navigation/react-navigation#8777]
**Current Behavior**
```
error: bundling failed: Error: Unable to resolve module `./views/Header/Header` from `node_modules/react-navigation-stack/lib/module/index.js`: 

None of these files exist:
  * node_modules/react-navigation-stack/lib/module/views/Header/Header(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  * node_modules/react-navigation-stack/lib/module/views/Header/Header/index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
    at ModuleResolver.resolveDependency (/Users/*/*/*/*/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:163:15)
    at ResolutionRequest.resolveDependency (/Users/*/*/*/*/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (/Users/*/*/*/*/node_modules/metro/src/node-haste/DependencyGraph.js:282:16)
    at Object.resolve (/Users/*/*/*/*/node_modules/metro/src/lib/transformHelpers.js:267:42)
    at /Users/*/*/*/*/node_modules/metro/src/DeltaBundler/traverseDependencies.js:426:31
    at Array.map (<anonymous>)
    at resolveDependencies (/Users/*/*/*/*/node_modules/metro/src/DeltaBundler/traverseDependencies.js:423:18)
    at /Users/*/*/*/*/node_modules/metro/src/DeltaBundler/traverseDependencies.js:275:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/*/*/*/*/node_modules/metro/src/DeltaBundler/traverseDependencies.js:87:24)
```
**Expected Behavior**

There should be files present in node_modules/react-navigation-stack/lib/module/views/

**How to reproduce**

`npm i react-navigation-stack`
then `react-native run-android`

**Your Environment**
"react": "16.9.0",
"react-native": "0.61.2",
"react-navigation": "^4.0.10",
"react-navigation-drawer": "^2.2.2",
"react-navigation-stack": "^2.8.2"

**Comment by satya164** [comment]
https://reactnavigation.org/docs/troubleshooting

**Comment by ShahbazAli206** [comment]
Unable to resolve module ./views/Header/Header from C:\Users\Muhammad Shahbaz Ali\Desktop\pro\node_modules\@react-navigation\stack\src\index.tsx:

**Comment by ShahbazAli206** [comment]
![Capture](https://user-images.githubusercontent.com/88003512/174148810-95a6c5f4-db6b-43cd-8630-8aaef0110a57.PNG)

**Comment by talhakhan119** [comment]
> ![Capture](https://user-images.githubusercontent.com/88003512/174148810-95a6c5f4-db6b-43cd-8630-8aaef0110a57.PNG)

What is the solution of this can you please help us out?

**Comment by ShahbazAli206** [comment]
1) install the pakages properly
npm install react-navigation/stack
npm install react-navigation/native

2) place the files in mentioned path .views/Header/Header

3) in one file, two default expots are not allowed.
export then by list.


4) use expo cli to run this code. not in android studio

**Comment by ShahbazAli206** [comment]
export {SmallButton, BigButton};
