### ISSUE TITLE
How to make Component with Sticky header and Top Tab Navigator?

### ISSUE THREAD

**Issue by huurray** [react-navigation/react-navigation#8791]
**Expected Behavior**

![capture](https://user-images.githubusercontent.com/41982439/91830835-407a1b00-ec7e-11ea-8dbe-3dab9e02313b.gif)

i'd like to make this kind of page with Material Top Tab Navigator.

i tried to move absolute top position of navigator. but it was hard.

I'v got some exampe [github](https://github.com/JanPeter/RN-NavigationHeaderAnimation) but it was too old version code.

could you let me know how to make it or some example code?
thanks for reading this!!

**Your Environment**

| software                            | version |
| ----------------------------------- | ------- |

    "@react-navigation/bottom-tabs": "^5.7.2",
    "@react-navigation/material-top-tabs": "^5.2.14",
    "@react-navigation/native": "^5.7.1",
    "@react-navigation/stack": "^5.7.1",
    "react": "16.13.1",
    "react-native": "0.63.2",
    "react-native-tab-view": "^2.15.0",

**Comment by huurray** [comment]
i made this code. i think it works
https://github.com/huurray/RN-sticky-header-tab-view/blob/master/App.tsx

**Comment by PedroBern** [comment]
Hi @huurray you can use [react-native-collapsible-tab-view](https://github.com/PedroBern/react-native-collapsible-tab-view), it is integrated with `react-navigation`. PS: I'm the maintainer.
