### ISSUE TITLE
setOptions warning spam: "Cannot update a component from inside the function body of a different component" SOLVED

### ISSUE THREAD

**Issue by Acetyld** [react-navigation/react-navigation#8796]
**Current Behavior**
I've used setOptions for a while. But after updating to newest react-native and navigation

` navigation.setOptions({
    headerStyle: {
      backgroundColor: backAni,
      elevation: 0, // remove shadow on Android
      shadowOpacity: 0, // remove shadow on iOS
    },
    headerTintColor: textAni,
    gestureEnabled: false,
    headerShown: false,
  });`

![afbeelding](https://user-images.githubusercontent.com/55088242/91960231-eaeb5000-ed09-11ea-9d02-fed8f0abc696.png)

**Expected Behavior**

No warning spam while using setOptions

**How to reproduce**

Create new react project, use setOptions with all newest verison

**Your Environment**
`@react-native-community/async-storage": "^1.12.0",
    "@react-native-community/cli-platform-android": "^4.11.0",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-navigation/bottom-tabs": "^5.8.0",
    "@react-navigation/native": "^5.7.3",
    "@react-navigation/stack": "^5.9.0",
    "@reduxjs/toolkit": "^1.4.0",
    "axios": "^0.19.2",
    "i18next": "^19.7.0",
    "i18next-react-native-language-detector": "^1.0.2",
    "react": "16.13.1",
    "react-devtools": "^3.6.3",
    "react-hook-form": "^5.7.2",
    "react-i18next": "^11.7.2",
    "react-native": "0.63.2",
    "react-native-appearance": "^0.3.4",
    "react-native-device-info": "^5.6.5",
    "react-native-gesture-handler": "^1.7.0",
    "react-native-keyboard-aware-scroll-view": "^0.9.2",
    "react-native-locale-detector": "^1.0.1",
    "react-native-reanimated": "^1.13.0",
    "react-native-safe-area-context": "^0.7.3",
    "react-native-screens": "^2.10.1",
    "react-native-splash-screen": "^3.2.0",
    "react-native-status-bar-height": "^2.5.0",
    "react-native-svg": "^12.1.0",
    "react-native-swipe-list-view": "^3.2.3",
    "react-native-swipeout": "^2.3.6",
    "react-redux": "^7.2.1",
    "redux": "^4.0.5"`

**Comment by Acetyld** [comment]
```
  React.useLayoutEffect(() => {
    navigation.setOptions({
      title: value === '' ? 'No title' : value,
    });
  }, [navigation, value]);

```

Think i found it! You need to use useLayoutEffect.

**Comment by Enneson** [comment]
> ```
>   React.useLayoutEffect(() => {
>     navigation.setOptions({
>       title: value === '' ? 'No title' : value,
>     });
>   }, [navigation, value]);
> ```
> 
> Think i found it! You need to use useLayoutEffect.

Thanks a lot!

**Comment by festusebin** [comment]
What similar way can I use setoptions navigation prop as it's in react navigation v5 for my react navigation v4?

I have gone through the v4 doc but looking confused 
Please, help
