### ISSUE TITLE
Hide Scrollview indicator

### ISSUE THREAD

**Issue by ndtoan210190** [react-navigation/react-navigation#8799]
Is there any way to hide ScrollView indicator in Material Top Tab Navigator? please help me with this. Thank you

![Screen Shot 2020-09-03 at 17 18 42](https://user-images.githubusercontent.com/40530539/92103742-97acf680-ee0a-11ea-85b0-94356a6774a1.png)

**Comment by raajnadar** [comment]
Check the docs the solution to hide it is given.

**Comment by NishidaRyu416** [comment]
`showsHorizontalScrollIndicator={false}`
Read the docs of react native.
And google!
Super straightforward!!
