### ISSUE TITLE
Integration between different navigators

### ISSUE THREAD

**Issue by satya164** [react-navigation/react-navigation#88]
It'd be nice if nested navigators were aware of each other and then adjust things automatically, for example

- [ ] When a stack navigator is inside another stack navigator, and the parent has it's header visible, the child should automatically hide the header (`header.mode: 'auto'`)
- [ ] When a stack navigator has a tab navigator as it's child with top bar, it should not have a `elevation` or `shadow` by default
- [ ] When a stack navigator has a drawer navigator as it's parent, it can show the drawer menu automatically in the first route
- [ ] When drawer navigation has a stack navigator as it's child and the route isn't the first route, it could lock itself automatically to disable swipe
- [ ] When stack navigator (with header) is inside another stack navigator (without header), show back button in the inner stack if it's not the first route

We need to figure out an API to communicate between navigators (preferable via context).

**Comment by ericvicenti** [comment]
Why is the ideal communication context instead of props? Sounds like we could have navigators pass additional props to each screen, in addition to `screenProps` and the scene's `navigation` prop.

Those props could be very specific like `isContainedInHeader`, and the screen may use that information (like if it wants to render a header in the other header is missing), or it can ignore it.

**Comment by cmrichards** [comment]
Can the elevation be set manually using navigationProps?

**Comment by zoontek** [comment]
> When drawer navigation has a stack navigator as it's child and the route isn't the first route, it could lock itself automatically to disable swipe

THIS.

Does a temporary solution exists actually?

**Comment by nonameolsson** [comment]
How's this coming along?

**Comment by ababba15** [comment]
I have combined drawer navigation with tabs without problem, just removed header from drawer route to don't render two headers.

**Comment by grabbou** [comment]
Are we still okay with implementing these points? @ericvicenti @satya164 I think I could start by implementing features for `drawer` and nested header issues as they seem most severe.

**Comment by ferrannp** [comment]
I still find this issue useful and needed. Specially:

> When drawer navigation has a stack navigator as it's child and the route isn't the first route, it could lock itself automatically to disable swipe

It'd be also nice not having to handle the hamburger button manually (90% of the time we will want the default one).

**Comment by Jacse** [comment]
> When drawer navigation has a stack navigator as it's child and the route isn't the first route, it could lock itself automatically to disable swipe

Needs to happen. Currently when i swipe from the left of the screen it sometimes opens the drawer and sometimes goes back in the StackNavigator. Doesn't seem to follow a pattern, but I haven't tested very thoroughly.

**Comment by NanIsNotANum** [comment]
Hi, thanks for the cool navigation solution!

As I am having complex navigator nest in my app (Stack{Tab{Stack{Tab{Stack}}}})
It is so nice to see that we have "TabBarvisible" feature now. 
Do we expect to have the following awesome feature soon? ;)

"When stack navigator (with header) is inside another stack navigator (without header), show back button in the inner stack if it's not the first route"

Cheers

**Comment by xiemeilong** [comment]
Is there a plan for this issue?

**Comment by Andreyco** [comment]
@satya164 Do you think it would be possible to "reset" navigator of one type to navigator of another type?

E.g: onboarding flow -> StackNavigator, several steps, several screens pushed. Very last screen would reset navigation stack (so that it's not possible to go back after onboarding is done) by pushing let's say DrawerNavigator with "main app", basically.

**Comment by cwagner22** [comment]
> When drawer navigation has a stack navigator as it's child and the route isn't the first route, it could lock itself automatically to disable swipe

So there is currently no way to achieve that? Even some hack?
I don't want to show the drawer on the child screens. (on ios the drawer is opened instead of swiping back)

**Comment by shruti8597** [comment]
I am having a structure as

stack navigator (A)
--tabnavigator (B)
    --tabnavigator (C)
        --stack navigator (D)

Here when navigate to a screen in (D) it shows 4 headers (A)(B)(C)(D) . I want only the header of (D) what to do..???

**Comment by kaiyuanneo** [comment]
FYI in case this helps anyone. I had been scouring Google to find a solution for https://github.com/react-community/react-navigation/issues/1037, and I figured out how to make it work. 

Context:
My navigation stack is Stack1 > Tab1 > Stack2, and I had been getting duplicate headers when navigating to pages in Stack2. Setting Stack2's header to null works in removing duplicate headers, but after that I was not able to edit the text of the back buttons in each of Stack2's screens. I really wanted to remove Stack1's header when displaying screens in Stack2.

Solution:
Adding `navigationOptions: { header: null }` to Tab1's route entry in Stack1's route config causes Stack1's header to disappear in all routes below Tab1 in the navigation tree. Stack1's header is still visible in all screens other than Tab1 in Stack1's route config.

Versions:
    "react": "16.0.0-alpha.12",
    "react-native": "^0.46.4",
    "react-navigation": "^1.0.0-beta.11",
    "react-redux": "^5.0.5",

Hope this helps!

**Comment by aadityapaliwal94** [comment]
> When drawer navigation has a stack navigator as it's child and the route isn't the first route, it could lock itself automatically to disable swipe

@satya164 Do we have any solution for the above.?

**Comment by cyorobert** [comment]
@kaiyuanneo Your solution helped me with a Stack > Stack navigation setup. Thank you!!

**Comment by dashracer** [comment]
```
I have combined drawer navigation with tabs without problem, just removed header from drawer route to don't render two headers, and added custom hamburger button to Tabs' header.
 👍 3  

```

@ababba15 Do you have any gist for your code on combining drawer and tab navigator?

**Comment by ababba15** [comment]
@dashracer sorry, right now don't have it. 
You could try to create tab navigator and provide it into drawer navigator. Let me know if you meet troubles with that.

**Comment by rabrenio** [comment]
@kaiyuanneo it only works for ios. Remember that the order should be header > tab, your solution switches the position, tab > header.

**Comment by brentvatne** [comment]
moved these all out into a several feature requests on canny. this one is an umbrella request to build an api that allows us to build this functionality without needing to couple one to another necessarily

**Comment by kedwin** [comment]
I am sorry but, i think this routing conception from the start has a wrong build,  if you are a hipster to waste days on this react component then this is a nice way to waste your life, if you want to be productive then this is a no go, if you have stack -> switch -> stack navigator, you can blow your head off if you want to goBack ....

**Comment by thisisjaiswal** [comment]
Create a header component suppose <ParentHeader />
make it's visibility driven from redux, then this can be controlled from any component.
