### ISSUE TITLE
non-serializable values were found in the navigation state

### ISSUE THREAD

**Issue by kovkev** [react-navigation/react-navigation#8800]
I get `non-serializable values were found in the navigation state` , when I pass a function to `initialParams` on `Stack.Screen` . I want to do that because the function I pass is `App.sendMessage` . I want all of my logic to be inside `App`, and I want all screens and components to receive functions from `App` . However, it's warning me about passing functions to `initialParams`. How else could I share the function `App.sendMessage` with my `ChatScreen` ?

`@react-navigation/native@5.2.6`

**Comment by kovkev** [comment]
`@react-navigation/native@5.2.6`
Done

**Comment by sebqq** [comment]
It's just a warning. If you want to get rid of it, you can try to put your sendMessage method into a separate context and then access it using `useContext` hook.

**Comment by hyochan** [comment]
I am also having this issue when sending `fbt` string in navigation param. You can see [here in my PR](https://github.com/dooboolab/dooboo-native-ts/pull/161).

**Comment by satya164** [comment]
@hyochan you shouldn't put translation data in params https://reactnavigation.org/docs/params/#what-should-be-in-params

**Comment by hyochan** [comment]
> @hyochan you shouldn't put translation data in params https://reactnavigation.org/docs/params/#what-should-be-in-params

Wow! I have missed that! Thanks for sharing!!
