### ISSUE TITLE
goBack behaviour in nested navigators (stack inside drawer)

### ISSUE THREAD

**Issue by sadikyalcin** [react-navigation/react-navigation#8806]
**Current Behavior**

I'm using a `stack` navigator inside `drawerNavigator` - recently upgraded from v4. Trying to implement custom back button on `headerLeft`. `goBack` function on the stack screen is going back on the `drawer` navigator instead of the stack. I don't know if I'm missing something or if it's a bug.

**Expected Behavior**

`goBack` should go to the previous screen in the `stack` not the `drawer`.

![ezgif-2-657d87fd907e](https://user-images.githubusercontent.com/8109619/92267501-aa8dfc80-eed8-11ea-9099-cf6a82cd35bb.gif)

**How to reproduce**

    export function BlogsStack({navigation}) {
      return (
        <Stack.Navigator
          initialRouteName={'Blogs'}
          screenOptions={{
            gestureEnabled: true,
            gestureDirection: 'horizontal',
            cardStyleInterpolator: CardStyleInterpolators.forHorizontalIOS,
            headerStyle: {
              borderBottomWidth: 0,
              elevation: 0,
              shadowOpacity: 0,
            },
            headerTintColor: themeVars.headerTintColor,
            headerBackground: () => {
              return <HeaderBackground />;
            },
          }}>
          <Stack.Screen
            name="Blogs"
            component={Blogs}
            options={{
              title: 'Blogs',
              headerTitle: () => (
                <View>
                  <HeaderButton title={'Blogs'} />
                </View>
              ),
              headerLeft: () => (
                <TouchableOpacity
                  onPress={() => navigation.toggleDrawer()}
                  style={drawerStyles.menuIconContainer}>
                  <FeatherIcon
                    style={drawerStyles.menuIcon}
                    name="menu"
                    size={themeVars.hamburgerIconSize}
                    color={themeVars.hamburgerIconColor}
                  />
                </TouchableOpacity>
              ),
              headerRight: () => <View />,
            }}
          />
          <Stack.Screen
            name="BlogSingle"
            component={BlogSingle}
            options={{
              headerTitle: () => (
                <View>
                  <HeaderButton title={'Blog'} />
                </View>
              ),
              headerLeft: () => (
                <TouchableOpacity
                  onPress={() => navigation.goBack()}
                  style={drawerStyles.menuIconContainer}>
                  <FeatherIcon
                    style={drawerStyles.menuIcon}
                    name="chevron-left"
                    size={themeVars.hamburgerIconSize}
                    color={themeVars.hamburgerIconColor}
                  />
                </TouchableOpacity>
              ),
              headerRight: () => <View />,
            }}
          />
        </Stack.Navigator>
      );
    }

    export class Navigation extends Component {
      constructor(props, context) {
        super(props, context);
      }

      render() {
        return (
          <NavigationContainer ref={navigationRef}>
            <AppDrawer.Navigator
              initialRouteName={'Home'}
              drawerContent={props => <DrawerContent {...props} />}
              drawerContentOptions={{
                labelStyle: {
                  fontFamily: themeVars.boldFont,
                  color: themeVars.primaryColor,
                },
                activeTintColor: 'black',
                activeBackgroundColor: 'black',
                inactiveTintColor: 'white',
                inactiveBackgroundColor: 'white',
                itemStyle: {
                  marginVertical: 0,
                  borderWidth: 1,
                  borderColor: 'red',
                  margin: 0,
                  padding: 0,
                },
              }}>
              <AppDrawer.Screen
                name="Home"
                component={HomeStack}
                initialRouteName={'Home'}
                options={{
                  drawerLabel: 'Home ',
                  drawerIcon: () => (
                    <FeatherIcon
                      color={themeVars.primaryColor}
                      name="home"
                      size={themeVars.drawerIconSize}
                    />
                  ),
                }}
              />
              <AppDrawer.Screen
                initialRouteName="Blogs"
                backBehavior="order"
                name="Blogs"
                component={BlogsStack}
                options={{
                  drawerLabel: 'Blogs ',
                  drawerIcon: () => (
                    <FontAwesome5
                      color={themeVars.primaryColor}
                      name="wordpress"
                      size={themeVars.drawerIconSize}
                    />
                  ),
                }}
              />
            </AppDrawer.Navigator>
          </NavigationContainer>
        );
      }
    }

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Both
| @react-navigation/native       | 5.7.3
| @react-navigation/stack        | 5.9.0
| react-native-gesture-handler   | 1.7.0
| react-native-safe-area-context | 3.1.7
| react-native-screens           | 2.10.1
| react-native                   | 0.61.5
| expo                           | NA
| node                           | 12.10.0
| npm or yarn                    | yarn 1.13.0

**Comment by NishidaRyu416** [comment]
I’m also facing that issue

**Comment by sandst1** [comment]
Likewise. I've got a stack inside stack. At least on Android, pressing the OS back button navigates back correctly within the nested stack. However, pressing the header back button or calling navigation.goBack() goes back to the parent stack, not the nested stack.

**Comment by sandst1** [comment]
I'm also facing this issue (got a stack navigator inside a stack navigator). Pressing the header arrow goes back to the parent navigator. However, manually calling navigation.goBack() or pressing the OS back button both navigate correctly within the nested stack. 

Did find a workaround where also the header back arrow functions correctly, but it's ugly and at best a very **temporary** solution.

```
    const navigation = useNavigation();

    const removeListener = (e: any) => {
        e.preventDefault();
        navigation.removeListener('beforeRemove', removeListener);
        navigation.goBack();
    };
    navigation.addListener('beforeRemove', removeListener);
```

**Comment by sadikyalcin** [comment]
> I'm also facing this issue (got a stack navigator inside a stack navigator). Pressing the header arrow goes back to the parent navigator. However, manually calling navigation.goBack() or pressing the OS back button both navigate correctly within the nested stack.
> 
> Did find a workaround where also the header back arrow functions correctly, but it's ugly and at best a very **temporary** solution.
> 
> ```
>     const navigation = useNavigation();
>     ...
>     const handleBack = (e: any) => {
>         e.preventDefault();
>         navigation.removeListener('beforeRemove', handleBack);
>         navigation.goBack();
>     };
>     navigation.addListener('beforeRemove', handleBack);
> ```

Ow that is dirty :)...

I found a workaround too just now... If you edit the `headerLeft` and use `navigation.goBack()` via `setOptions` on the screen, it seems to work.

    componentDidMount() {
      this.props.navigation.setOptions({
        headerLeft: () => (
          <TouchableOpacity
            onPress={() => this.props.navigation.goBack()}
            style={drawerStyles.menuIconContainer}>
            <FeatherIcon
              style={drawerStyles.menuIcon}
              name="chevron-left"
              size={themeVars.hamburgerIconSize}
              color={themeVars.black}
            />
          </TouchableOpacity>
        ),
      });
    }

**Comment by sandst1** [comment]
> I found a workaround too just now... If you edit the `headerLeft` and use `navigation.goBack()` via `setOptions` on the screen, it seems to work.
> 
> ```
> componentDidMount() {
>   this.props.navigation.setOptions({
>     headerLeft: () => (
>       <TouchableOpacity
>         onPress={() => this.props.navigation.goBack()}
>         style={drawerStyles.menuIconContainer}>
>         <FeatherIcon
>           style={drawerStyles.menuIcon}
>           name="chevron-left"
>           size={themeVars.hamburgerIconSize}
>           color={themeVars.black}
>         />
>       </TouchableOpacity>
>     ),
>   });
> }
> ```

This is definitely a more proper workaround :)

**Comment by sadikyalcin** [comment]
Another 2 serious issues with `goBack`.

Consider the following (drawerNavigator):

`Home` (homeStack)
`News` (newsStack)
`News > News Single` (newsStack)

Issue 1 - If the app is **not running**:

`xcrun** simctl openurl booted myapp://news/node/{id}` > launches the `News Single` screen in the `News` stack. `goBack` crashes the app: `The action 'GO_BACK' was not handled by any navigator. Is there any screen to go back to?`

Issue 2 - While the app **is running**:

`xcrun** simctl openurl booted myapp://news/node/{id}` > launches the `News Single` screen in the `News` stack. `goBack` goes to the `Home` screen - the initial route on the `drawerNavigator`. I am now stuck in a limbo and cannot access `News` since the route state is stuck at `News Single`.

Not so good workaround;

Instead of using `goBack`, I could use `navigate('News') on the `headerLeft`. But this reverses the animations.

Could someone take a look? @satya164

**Comment by sadikyalcin** [comment]
> The versions mentioned in the issue for the following packages differ from the latest versions on npm:
> 
> * `@react-navigation/native` (found: `5.7.3`, latest: `5.7.4`)
> * `@react-navigation/stack` (found: `5.9.0`, latest: `5.9.1`)
> 
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?

I confirm the issues still exist with the latest versions.

**Comment by satya164** [comment]
You need to use the correct `navigation` prop in your header, i.e. by defining a callback for the `options`: https://reactnavigation.org/docs/screen-options#options-prop-on-screen

You're using `navigation` prop passed from the parent navigator which is a drawer, so the action is performed in the drawer.

**Comment by sadikyalcin** [comment]
> You need to use the correct `navigation` prop in your header, i.e. by defining a callback for the `options`: https://reactnavigation.org/docs/screen-options#options-prop-on-screen
> 
> You're using `navigation` prop passed from the parent navigator which is a drawer, so the action is performed in the drawer.

Thanks. Pointed me in the right direction and I've now solved all my issues; specifically `goBack` after deeplinks. Using the right `navigation` prop alone wasn't enough, had to set an initial route on the deeplink config as well...

    const linking = {
      prefixes: ['communicator://'],
      config: {
        screens: {
          Home: 'home',
          Account: 'account',
          Login: 'login',
          Forms: 'forms',
          Links: 'links',
          Polls: 'polls',
          News: {
            initialRouteName: 'News',
            path: 'news',
            screens: {
              NewsSingle: 'node/:nid',
            },
          },
        },
      },
    };

**Comment by sadikyalcin** [comment]
@satya164 correct me if I'm wrong but I think this is still an issue....

`Home` (stack)
`Account` (stack)
`Account -> MessageSingle`

If I navigate to `MessageSingle` from `Home` and go back I'm taken to `Home` screen even though I'm passing the correct `navigation` prop.

Home:

    this.props.navigation.navigate('Account', {
        screen: 'MessageSingle',
        params: {},
    });


    export function AccountStack() {
      return (
        <Stack.Navigator
          initialRouteName={'Account'}
          }}>
          <Stack.Screen
            name="Account"
            component={Account}
            options={({navigation}) => ({
              title: 'Account',
              headerTitle: () => (
                <View>
                  <HeaderButton title={'Account'} />
                </View>
              ),
              headerLeft: () => (
                <TouchableOpacity
                  onPress={() => navigation.toggleDrawer()}
                  style={drawerStyles.menuIconContainer}>
                  <FeatherIcon
                    style={drawerStyles.menuIcon}
                    name="menu"
                    size={themeVars.hamburgerIconSize}
                    color={themeVars.hamburgerIconColor}
                  />
                </TouchableOpacity>
              ),
              headerRight: () => (
                <TouchableOpacity
                  onPress={() => navigation.navigate('Messages')}
                  style={drawerStyles.menuIconContainer}>
                  <FeatherIcon
                    style={drawerStyles.menuIcon}
                    name="message-circle"
                    size={themeVars.hamburgerIconSize}
                    color={themeVars.hamburgerIconColor}
                  />
                </TouchableOpacity>
              ),
            })}
          />
          <Stack.Screen
            name="EditProfile"
            component={Profile}
            options={({navigation}) => ({
              headerTitle: () => (
                <View>
                  <HeaderButton title={'Profile'} />
                </View>
              ),
              headerLeft: () => (
                <TouchableOpacity
                  onPress={() => navigation.goBack()}
                  style={drawerStyles.menuIconContainer}>
                  <FeatherIcon
                    style={drawerStyles.menuIcon}
                    name="chevron-left"
                    size={themeVars.hamburgerIconSize}
                    color={themeVars.hamburgerIconColor}
                  />
                </TouchableOpacity>
              ),
              headerRight: () => <View />,
            })}
          />
          <Stack.Screen
            name="Messages"
            component={Messages}
            options={({navigation}) => ({
              title: 'Messages',
              headerTitle: () => (
                <View>
                  <HeaderButton title={'Messages'} />
                </View>
              ),
              headerLeft: () => (
                <TouchableOpacity
                  onPress={() => navigation.goBack()}
                  style={drawerStyles.menuIconContainer}>
                  <FeatherIcon
                    style={drawerStyles.menuIcon}
                    name="chevron-left"
                    size={themeVars.hamburgerIconSize}
                    color={themeVars.hamburgerIconColor}
                  />
                </TouchableOpacity>
              ),
              headerRight: () => <View />,
            })}
          />
          <Stack.Screen
            name="MessageSingle"
            component={MessageSingle}
            options={({navigation}) => ({
              headerTitle: () => (
                <View>
                  <HeaderButton title={''} />
                </View>
              ),
              headerLeft: () => (
                <TouchableOpacity
                  onPress={() => navigation.goBack()}
                  style={drawerStyles.menuIconContainer}>
                  <FeatherIcon
                    style={drawerStyles.menuIcon}
                    name="chevron-left"
                    size={themeVars.hamburgerIconSize}
                    color={themeVars.hamburgerIconColor}
                  />
                </TouchableOpacity>
              ),
              headerRight: () => <View />,
            })}
          />
        </Stack.Navigator>
      );
    }

**Comment by sadikyalcin** [comment]
Found the magic at last so solve all issues for future visitors.

All you need to do is, add `initial: false` when navigating from a screen inside a a stack to a detail screen on another stack as mentioned [here](https://reactnavigation.org/docs/nesting-navigators/#rendering-initial-route-defined-in-the-navigator).

    this.props.navigation.navigate('News', {
        screen: 'Detail',
        initial: false,
        params: {},
    });

**Comment by MishaChernov** [comment]
> Found the magic at last so solve all issues for future visitors.
> 
> All you need to do is, add `initial: false` when navigating from a screen inside a a stack to a detail screen on another stack as mentioned [here](https://reactnavigation.org/docs/nesting-navigators/#rendering-initial-route-defined-in-the-navigator).
> 
> ```
> this.props.navigation.navigate('News', {
>     screen: 'Detail',
>     initial: false,
>     params: {},
> });
> ```

How can get the same behavior on the older version <5 ?
