### ISSUE TITLE
DrawerItemList should support an onItemPress callback function

### ISSUE THREAD

**Issue by MarkCSmith** [react-navigation/react-navigation#8809]
**Current Behavior**

- With React Navigation 5.x an `onItemPress` hook is missing.

**Expected Behavior**

- `DrawerItemList` should accept an `onItemPress` prop: a function that can override the default navigation behavior. One use case is to make it easy to implement drawer items that do not navigate to another screen, e.g., to include an item that opens an URL in an external browser.

**How to reproduce**

I have a patch which I will turn into a PR very soon.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| Android or iOS                 | any
| @react-navigation/native       |5.7.3
| @react-navigation/drawer       |5.9.0
| react-native-reanimated        |1.13.0
| react-native-gesture-handler   |1.7.0
| react-native-safe-area-context |3.1.7
| react-native-screens           |2.10.1
| react-native                   |0.62.2
| expo                           |n/a
| node                           |14.5.0
| npm                    |6.14.5

**Comment by sierrakn** [comment]
This is very frustrating, is there any word on this issue?

**Comment by Spark-Cybel** [comment]
Is this resolved?
