### ISSUE TITLE
 93/5000 react-navigation / material-top-tabs || not work in Android when implement scrollEnabled: 'true' in tabBarOptions

### ISSUE THREAD

**Issue by codigorojo** [react-navigation/react-navigation#8811]
**Current Behavior**
I want one createMaterialTopTabNavigator with scrollEnabled: 'true'. 
Work perfect on iOS but on Android not work

- What code are you running and what is happening?
- Include a screenshot or video if it makes sense.
![Captura de Pantalla 2020-09-04 a la(s) 23 25 18](https://user-images.githubusercontent.com/46204965/92295987-46822d00-ef06-11ea-81aa-d4d169223369.png)

**Expected Behavior**
see the video in this link: 
https://ferpm15.myportfolio.com/oleteve

- What do you expect should be happening?
- Include a screenshot or video if it makes sense.
<Tab.Navigator> with  scrollEnabled: 'true',
**How to reproduce**
![Captura de Pantalla 2020-09-04 a la(s) 23 08 05](https://user-images.githubusercontent.com/46204965/92294992-81cf2c80-ef03-11ea-8ff6-910ad7c8fbdb.png)

- You must provide a way to reproduce the problem. If you are having an issue with your machine or build tools, the issue belongs on another repository as that is outside of the scope of React Navigation.
I tried with code very simple with createMaterialTopTabNavigator(). Making debug all time in Android but when write scrollEnabled: 'true', the emulator send this message:
![Captura de Pantalla 2020-09-04 a la(s) 20 49 09](https://user-images.githubusercontent.com/46204965/92296167-0a4fcc00-ef08-11ea-9c23-e148d56a8d85.png)

- Either re-create the bug on [Snack](https://snack.expo.io) or link to a GitHub repository with code that reproduces the bug.
- Explain how to run the example app and any steps that we need to take to reproduce the issue from the example app.
- Keep the repro code as simple as possible, with the minimum amount of code required to repro the issue.
- Before reporting an issue, make sure you are on latest version of the package.

**Your Environment**

| software                            | version |
| ----------------------------------- | ------- |
| iOS or Android                      |I try with Android 6.0 to 10.0
| @react-navigation/native            |"^5.5.1",
| @react-navigation/material-top-tabs |"^5.2.10",
| react-native-tab-view               |"^2.14.4",
| react-native                        |"0.62.2"
| expo                                |
| node                                |v12.15.0
| npm or yarn                         |6.13.7

**Comment by codigorojo** [comment]
ok, I´ll try. Thanks!

**Comment by codigorojo** [comment]
I was tried whit all last versions but not work
I create the bug on this GitHub repository with code that reproduces the bug:
https://github.com/codigorojo/scrollEnabledTrue

**Comment by satya164** [comment]
It's a boolean, not a string.

**Comment by codigorojo** [comment]
Thank you, very much! 
This experience was very important for me! 
I am studying. I am designer => developer.
