### ISSUE TITLE
TextInput maintains focus when tapping on header

### ISSUE THREAD

**Issue by vujevits** [react-navigation/react-navigation#8815]
**Current Behavior**
Tapping on the header does not result in `TextInput` losing focus. Not even if it's a button.

**Expected Behavior**

TextInput should lose focus?

**How to reproduce**
Tried to reproduce the issue in a snack, but the most basic example fails with some unrelated error. In my experience the bug itself happens always when trying to tap on the header.

https://snack.expo.io/@vmark/react-navigation-v5
```Device: TypeError: e is not a function. (In 'e((0,a.default)({},i,(null==r?void 0:r.params)&&"string"==typeof r.params.screen?{initialRouteName:r.params.screen}:null))', 'e' is undefined)

This error is located at:
    in Unknown
    in Unknown
    in ForwardRef
    in App
    in RCTView
    in RCTView
    in n
    in n
    in S
    in RCTView
    in RCTView
    in h
```
**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |iOS
| @react-navigation/native       |5.5.1
| @react-navigation/stack        |5.5.1
| react-native-gesture-handler   |1.6.0
| react-native-safe-area-context |0.7.3
| react-native-screens           |2.2.0
| react-native                   |https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz
| expo                           |37
| node                           |12.16.0
| npm or yarn                    |yarn 1.22.4

**Comment by satya164** [comment]
That's how `TextInput` component in React Native behaves. This is unrelated to React Navigation. If you want to blur input when tapping on Header buttons, then call `Keyboard.dismiss()` manually.
