### ISSUE TITLE
Cannot convert undefined or null to object 

### ISSUE THREAD

**Issue by abbasmoosavi** [react-navigation/react-navigation#8820]
When use @react-navigation/drawer "version": "5.9.0" crash on android and error is

```javascript
const createNormalizedConfigs = (
  legacy: boolean,
  options: PathConfigMap,
  pattern?: string
): Record<string, ConfigItem> =>
  fromEntries(
    Object.entries(options).map(([name, c]) => {
      const result = createConfigItem(legacy, c, pattern);

      return [name, result];
    })
  );
```
Cannot convert undefined or null to object 
"@react-navigation/native": "5.7.3",

**Comment by abbasmoosavi** [comment]
"@react-navigation/native": "5.7.3",

**Comment by purut18** [comment]
same error

"@react-navigation/drawer": "^5.9.2",
"@react-navigation/native": "^5.7.5",

**Comment by satya164** [comment]
Closing due to incomplete info and no repro.
