### ISSUE TITLE
Warning: Can't perform a React state update on an unmounted component.

### ISSUE THREAD

**Issue by Georgge** [react-navigation/react-navigation#8822]
**Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.**

Currently I has this problem when a screen is go Back. This a no important problem for the majority of my app, but it is not with the transitions animations.

`Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.`
`in Card (at CardContainer.tsx:189)`
`in CardContainer (at CardStack.tsx:558)`
 ` in RCTView (at View.js:34)`
`  in View (at Screens.tsx:69)`
`  in MaybeScreen (at CardStack.tsx:551)`

Someone with the same issue and a fix?

**How to reproduce**

"react-native": "^0.63.2"
"@react-navigation/bottom-tabs": "^5.6.1",
"@react-navigation/drawer": "^5.8.4",
"@react-navigation/native": "^5.6.1",
"@react-navigation/stack": "^5.6.2",

**Structure**
```
Stack
  -> Drawer
    -> Tab
      -> Stack
```

Flow: List.tsx (last stack) to Detail.tsx (first stack)

**Comment by aldinoanggawan** [comment]
having the exact same issue here, running latest version

**Comment by satya164** [comment]
Closing since you didn't provide a repro to debug the issue.

**Comment by dfree** [comment]
Ran into the same bump by navigating back on a stack to a screen contains a drawer

**Comment by todorone** [comment]
Experience the same issue with 2 nested StackNavigators...

**Comment by Pretorians** [comment]
I had the same problem about this code:

```
const Drawer = createDrawerNavigator()
const Stack = createStackNavigator()

const Screens = (navigation)=> {
  return (
    <Stack.Navigator
      headerMode="none"
      screenOptions={{
          gestureEnabled: true,
          gestureDirection: "horizontal",
          cardStyleInterpolator: CardStyleInterpolators.forHorizontalIOS
        }}
    >
        <Stack.Screen name="Inicio">{props => <AppMagazine {...props} />}</Stack.Screen>
        <Stack.Screen name="magazine">{props => <Magazine {...props} />}</Stack.Screen>
        <Stack.Screen name="login">{props => <Login {...props} />}</Stack.Screen>
      </Stack.Navigator>
  )
}

function MyDrawer() {
  return (
    <Drawer.Navigator initialRouteName="Home" drawerContent={props => <CustomDrawerContent {...props} />}>
        <Drawer.Screen name="Screens">
          {props => <Screens {...props}  />}
        </Drawer.Screen>
   </Drawer.Navigator>
  );
}
```

I solved it, deleting the following properties (gestureEnabled, gestureDirection).

```
     <Stack.Navigator
       headerMode="none"
       screenOptions={{
-          gestureEnabled: true,
-          gestureDirection: "horizontal",
           cardStyleInterpolator: CardStyleInterpolators.forHorizontalIOS
         }}
     >
```

**Comment by anthonyrfariasmultivende** [comment]
I'm having the same problem. It only happens the first time the goBack Button is pressed, when entering again it does not appear anymore until app is restarted. 
![image](https://user-images.githubusercontent.com/66961286/95932224-46910a80-0d99-11eb-8f7a-386836b3fb3e.png)

**Comment by anthonyrfariasmultivende** [comment]
> I had the same problem about this code:
> 
> ```
> const Drawer = createDrawerNavigator()
> const Stack = createStackNavigator()
> 
> const Screens = (navigation)=> {
>   return (
>     <Stack.Navigator
>       headerMode="none"
>       screenOptions={{
>           gestureEnabled: true,
>           gestureDirection: "horizontal",
>           cardStyleInterpolator: CardStyleInterpolators.forHorizontalIOS
>         }}
>     >
>         <Stack.Screen name="Inicio">{props => <AppMagazine {...props} />}</Stack.Screen>
>         <Stack.Screen name="magazine">{props => <Magazine {...props} />}</Stack.Screen>
>         <Stack.Screen name="login">{props => <Login {...props} />}</Stack.Screen>
>       </Stack.Navigator>
>   )
> }
> 
> function MyDrawer() {
>   return (
>     <Drawer.Navigator initialRouteName="Home" drawerContent={props => <CustomDrawerContent {...props} />}>
>         <Drawer.Screen name="Screens">
>           {props => <Screens {...props}  />}
>         </Drawer.Screen>
>    </Drawer.Navigator>
>   );
> }
> ```
> 
> I solved it, deleting the following properties (gestureEnabled, gestureDirection).
> 
> ```
>      <Stack.Navigator
>        headerMode="none"
>        screenOptions={{
> -          gestureEnabled: true,
> -          gestureDirection: "horizontal",
>            cardStyleInterpolator: CardStyleInterpolators.forHorizontalIOS
>          }}
>      >
> ```

This did not work for me, besides gestures are a requirement in my project!

**Comment by ixez** [comment]
> I had the same problem about this code:
> 
> ```
> const Drawer = createDrawerNavigator()
> const Stack = createStackNavigator()
> 
> const Screens = (navigation)=> {
>   return (
>     <Stack.Navigator
>       headerMode="none"
>       screenOptions={{
>           gestureEnabled: true,
>           gestureDirection: "horizontal",
>           cardStyleInterpolator: CardStyleInterpolators.forHorizontalIOS
>         }}
>     >
>         <Stack.Screen name="Inicio">{props => <AppMagazine {...props} />}</Stack.Screen>
>         <Stack.Screen name="magazine">{props => <Magazine {...props} />}</Stack.Screen>
>         <Stack.Screen name="login">{props => <Login {...props} />}</Stack.Screen>
>       </Stack.Navigator>
>   )
> }
> 
> function MyDrawer() {
>   return (
>     <Drawer.Navigator initialRouteName="Home" drawerContent={props => <CustomDrawerContent {...props} />}>
>         <Drawer.Screen name="Screens">
>           {props => <Screens {...props}  />}
>         </Drawer.Screen>
>    </Drawer.Navigator>
>   );
> }
> ```
> 
> I solved it, deleting the following properties (gestureEnabled, gestureDirection).
> 
> ```
>      <Stack.Navigator
>        headerMode="none"
>        screenOptions={{
> -          gestureEnabled: true,
> -          gestureDirection: "horizontal",
>            cardStyleInterpolator: CardStyleInterpolators.forHorizontalIOS
>          }}
>      >
> ```

This works for me. Thank you so much for saving so much time finding the reason.
It seems the gesture feature has some problems.

**Comment by nfaycel** [comment]
> 
> 
> > I had the same problem about this code:
> > ```
> > const Drawer = createDrawerNavigator()
> > const Stack = createStackNavigator()
> > 
> > const Screens = (navigation)=> {
> >   return (
> >     <Stack.Navigator
> >       headerMode="none"
> >       screenOptions={{
> >           gestureEnabled: true,
> >           gestureDirection: "horizontal",
> >           cardStyleInterpolator: CardStyleInterpolators.forHorizontalIOS
> >         }}
> >     >
> >         <Stack.Screen name="Inicio">{props => <AppMagazine {...props} />}</Stack.Screen>
> >         <Stack.Screen name="magazine">{props => <Magazine {...props} />}</Stack.Screen>
> >         <Stack.Screen name="login">{props => <Login {...props} />}</Stack.Screen>
> >       </Stack.Navigator>
> >   )
> > }
> > 
> > function MyDrawer() {
> >   return (
> >     <Drawer.Navigator initialRouteName="Home" drawerContent={props => <CustomDrawerContent {...props} />}>
> >         <Drawer.Screen name="Screens">
> >           {props => <Screens {...props}  />}
> >         </Drawer.Screen>
> >    </Drawer.Navigator>
> >   );
> > }
> > ```
> > 
> > 
> > I solved it, deleting the following properties (gestureEnabled, gestureDirection).
> > ```
> >      <Stack.Navigator
> >        headerMode="none"
> >        screenOptions={{
> > -          gestureEnabled: true,
> > -          gestureDirection: "horizontal",
> >            cardStyleInterpolator: CardStyleInterpolators.forHorizontalIOS
> >          }}
> >      >
> > ```
> 
> This did not work for me, besides gestures are a requirement in my project!

Thanks a lot you saved my day. (downside i can't use gesture)

**Comment by mostafabrazi** [comment]
Removing `**gestureEnabled: true**` solved the issue for me.

**Comment by diegods-ferreira** [comment]
Removing `gestureEnabled: true` solved the issue for me too.

**Comment by wallyPual** [comment]
Removing gestureEnabled: true solved the issue for me too.

**Comment by ixez** [comment]
But I need `gestureEnabled: true`.

**Comment by AstroCorp** [comment]
I need gestureEnabled: true.
Any solution?

**Comment by aftabaminzoobiapps** [comment]
Here is a simple solution for this. This warning is due to when we do some fetch request while that request is in the background (because some requests take some time.)and we navigate back from that screen then the react cannot update the state. here is the example code for this.  write this line before every state Update. 

` if(!isScreenMounted.current) return;`
```
import React , {useRef} from 'react'
import { Text,StatusBar,SafeAreaView,ScrollView, StyleSheet } from 'react-native'
import BASEURL from '../constants/BaseURL';
const SearchScreen = () => {
    const isScreenMounted = useRef(true)
    useEffect(() => {
        return () =>  isScreenMounted.current = false
    },[])

    const ConvertFileSubmit = () => {
        if(!isScreenMounted.current) return;
         setUpLoading(true)
 
         var formdata = new FormData();
         var file = {
             uri: `file://${route.params.selectedfiles[0].uri}`,
             type:`${route.params.selectedfiles[0].minetype}`,
             name:`${route.params.selectedfiles[0].displayname}`,
         };
         
         formdata.append("file",file);
         
         fetch(`${BASEURL}/UploadFile`, {
             method: 'POST',
             body: formdata,
             redirect: 'manual'
         }).then(response => response.json())
         .then(result => {
             if(!isScreenMounted.current) return;
             setUpLoading(false)    
         }).catch(error => {
             console.log('error', error)
         });
     }

    return(
    <>
        <StatusBar barStyle="dark-content" />
        <SafeAreaView>
            <ScrollView
            contentInsetAdjustmentBehavior="automatic"
            style={styles.scrollView}>
               <Text>Search Screen</Text>
            </ScrollView>
        </SafeAreaView>
    </>
    )
}

export default SearchScreen;


const styles = StyleSheet.create({
    scrollView: {
        backgroundColor:"red",
    },
    container:{
        flex:1,
        justifyContent:"center",
        alignItems:"center"
    }
})
```
