### ISSUE TITLE
Component does not unmount and reset state when navigation.goBack() is called

### ISSUE THREAD

**Issue by MarcoDo99** [react-navigation/react-navigation#8832]
**Current Behavior**
When the back button is pressed, my Screen does not unmount and not reset its state 
**Expected Behavior**
The documentation says
"Consider a stack navigator with screens A and B. After navigating to A, its componentDidMount is called. When pushing B, its componentDidMount is also called, but A remains mounted on the stack and its componentWillUnmount is therefore not called.

When going back from B to A, componentWillUnmount of B is called, but componentDidMount of A is not because A remained mounted the whole time."

Which is exactly the behaviour I need, namely that B will unmount when going back. However, this is not the case.
Component B never unmounts and remains its state.

Versions:

"@react-navigation/native": "^5.7.3",
"@react-navigation/stack": "^5.9.0"

**Comment by afilp** [comment]
I believe this is also happening when I do a `reset` after logout. Some timers I have on mounter components are not cleared, despite their clearance is in the `componentWillUnmount` method. This means that somehow the component is not unmounted?

**Comment by LHDi** [comment]
Same problem here!

**Comment by JayantJoseph** [comment]
why is this happening? is there any work around for this? or am i missing something.

**Comment by deniscreamer** [comment]
Just try use an anonymous function in component prop.

`component={() => <Component />}`

```
<MainStack.Navigator>
   <MainStack.Screen
      name={MAIN_STACK.MONITORING}
      component={(props) => <MonitoringScreen {...props} />}
      options={{headerShown: false}}
   />
</MainStack.Navigator>
```

**Comment by Ahmad652** [comment]
I'm also facing the same issue. Any solution?

**Comment by forster007** [comment]
How this topic are closed without solution?

**Comment by enzzoperez** [comment]
Im facing with this and solved using useFocusEffect

```
//Example from docs

import { useFocusEffect } from '@react-navigation/native';


function Profile() {
  useFocusEffect(
    React.useCallback(() => {
      // Do something when the screen is focused

      return () => {
        // Do something when the screen is unfocused
        // Useful for cleanup functions
      };
    }, [])
  );

  return <ProfileContent />;
}
````

docs: https://reactnavigation.org/docs/navigation-lifecycle/#react-navigation-lifecycle-events

**Comment by DevineDecrypter** [comment]
> Im facing with this and solved using useFocusEffect
> 
> ```
> //Example from docs
> 
> import { useFocusEffect } from '@react-navigation/native';
> 
> 
> function Profile() {
>   useFocusEffect(
>     React.useCallback(() => {
>       // Do something when the screen is focused
> 
>       return () => {
>         // Do something when the screen is unfocused
>         // Useful for cleanup functions
>       };
>     }, [])
>   );
> 
>   return <ProfileContent />;
> }
> ```
> 
> docs: https://reactnavigation.org/docs/navigation-lifecycle/#react-navigation-lifecycle-events

how can i use this for a class component ?

**Comment by DevineDecrypter** [comment]
> Just try use an anonymous function in component prop.
> 
> `component={() => <Component />}`
> 
> ```
> <MainStack.Navigator>
>    <MainStack.Screen
>       name={MAIN_STACK.MONITORING}
>       component={(props) => <MonitoringScreen {...props} />}
>       options={{headerShown: false}}
>    />
> </MainStack.Navigator>
> ```

it throws this warn :
`Looks like you're passing an inline function for 'component' prop for the screen 'VideoPlayer' (e.g. component={() => <SomeComponent />}). Passing an inline function will cause the component state to be lost on re-render and cause perf issues since it's re-created every render. You can pass the function as children to 'Screen' instead to achieve the desired behaviour.`

**Comment by enzzoperez** [comment]
> > Im facing with this and solved using useFocusEffect
> > ```
> > //Example from docs
> > 
> > import { useFocusEffect } from '@react-navigation/native';
> > 
> > 
> > function Profile() {
> >   useFocusEffect(
> >     React.useCallback(() => {
> >       // Do something when the screen is focused
> > 
> >       return () => {
> >         // Do something when the screen is unfocused
> >         // Useful for cleanup functions
> >       };
> >     }, [])
> >   );
> > 
> >   return <ProfileContent />;
> > }
> > ```
> > 
> > 
> > docs: https://reactnavigation.org/docs/navigation-lifecycle/#react-navigation-lifecycle-events
> 
> how can i use this for a class component ?

There are components to be used with class components in 4.x version doc, maybe that will help you https://reactnavigation.org/docs/4.x/navigation-lifecycle

**Comment by azaelvaldo** [comment]
> Just try use an anonymous function in component prop.
> 
> `component={() => <Component />}`
> 
> ```
> <MainStack.Navigator>
>    <MainStack.Screen
>       name={MAIN_STACK.MONITORING}
>       component={(props) => <MonitoringScreen {...props} />}
>       options={{headerShown: false}}
>    />
> </MainStack.Navigator>
> ```

TY so much, this helped me a lot.

**Comment by azaelvaldo** [comment]
> Just try use an anonymous function in component prop.
> 
> `component={() => <Component />}`
> 
> ```
> <MainStack.Navigator>
>    <MainStack.Screen
>       name={MAIN_STACK.MONITORING}
>       component={(props) => <MonitoringScreen {...props} />}
>       options={{headerShown: false}}
>    />
> </MainStack.Navigator>
> ```

Ty so much, you saved me!

**Comment by hussainsherwani** [comment]
> Just try use an anonymous function in component prop.
> 
> `component={() => <Component />}`
> 
> ```
> <MainStack.Navigator>
>    <MainStack.Screen
>       name={MAIN_STACK.MONITORING}
>       component={(props) => <MonitoringScreen {...props} />}
>       options={{headerShown: false}}
>    />
> </MainStack.Navigator>
> ```

not fixed with above solution also with the inline function getting warning  `assing an inline function will cause the component state to be lost on re-render and cause perf issues since it's re-created every render. You can pass the function as children to 'Screen' instead to achieve the desired behaviour.`

**Comment by pke** [comment]
The inline prop is not a solution as @hussainsherwani pointed out.
Would some maintainer please elaborate on this? @satya164

**Comment by hirbod** [comment]
I can confirm this issue. Even running videos will still keep playing.
My guess is that react-native-screens ist doing some interference here.

**Comment by pke** [comment]
No, I couldn't fix it myself. Some deeper knowledge of RN is required to solve this.

**Comment by hirbod** [comment]
@pke https://github.com/software-mansion/react-native-screens/issues/1379
I also did create an Issue here. This one is a big issue, no small thing... it won't break for most use cases, but as soon as camera or video is involved, things get really messy. Already 2 days on it trying to fix it.

**Comment by DominicTobias** [comment]
Well this is surprising, breaks fundamentals of React - the ability to cleanup when navigating around! How can I unsubscribe from a websocket for example when the screen is navigated away from? I found that `useFocusEffect` unmount callback gets called many times when first visiting a screen so it's not useful here.

The solution mentioned here actually caused an infinite unmount/remount loop for me along with this warning getting repeated:

> Looks like you're passing an inline function for 'component' prop for the screen 'Trade' (e.g. component={() => <SomeComponent />}). Passing an inline function will cause the component state to be lost on re-render and cause perf issues since it's re-created every render. You can pass the function as children to 'Screen' instead to achieve the desired behaviour.

But moving it into a function as `children` makes the unmound not work just like before.
