### ISSUE TITLE
Using createMaterialTopTabNavigator (React Navigation v5) with position bottom making Tabs overlapped safe area.

### ISSUE THREAD

**Issue by karanmohanbhola02** [react-navigation/react-navigation#8842]
**Current Behavior**: Using createMaterialTopTabNavigator with position set as bottom making Tabs overlapped safe area. 

**Note**: Doesn't want to add Safe Area Provider to the top container as it will create double header issue in the nested screens/navigators.

**Expected Behavior**: The Tabs should remain inside the safe area.

**How to reproduce**
Using Navigation structure like this

**RootNavigator**
```
<NavigationContainer>
	<Stack.Navigator>
  		<Stack.Screen
	           name={'Drawer'}
	           component={DrawerNavigator}
	           options={{ headerShown: false }} />
	</Stack.Navigator>
</NavigationContainer>
```
**DrawerNavigator**
```
<Drawer.Navigator>
    <Drawer.Screen name={'Tabs'} component={TabNavigator} />
</Drawer.Navigator>
```
**TabNavigator**
```
import React from 'react';
import { createMaterialTopTabNavigator } from '@react-navigation/material-top-tabs';
import HomeNavigator from './HomeNavigator';

const Tab = createMaterialTopTabNavigator();

const TabNavigator = () => {
  return (
    <Tab.Navigator lazy={true} tabBarPosition="bottom">
      <Tab.Screen name={'First Tab'} component={HomeNavigator} />
      <Tab.Screen name={'Second Tab'} component={HomeNavigator} />
      <Tab.Screen name={'Third Tab'} component={HomeNavigator} />
    </Tab.Navigator>
  );
}

export default TabNavigator;
```

Software | Version
-- | --
"react" | "16.13.1"
"react-native" | "0.63.2"
"@react-navigation/native" | "^5.7.3"
"@react-navigation/drawer" | "^5.9.0"
"react-native-reanimated" | "^1.13.0"
"react-native-safe-area-context" | "^3.1.7"
"react-native-screens" | "^2.10.1"
"@react-navigation/material-top-tabs" | "^5.2.16"
"react-native-tab-view" | "^2.15.1"
"@react-navigation/stack" | "^5.9.0"
"@react-native-community/masked-view" | "^0.1.10"
"react-native-gesture-handler" | "^1.7.0"

<img width="346" alt="Screenshot 2020-09-13 at 6 14 20 PM" src="https://user-images.githubusercontent.com/63860912/93018376-f6cdf080-f5ec-11ea-8274-9e5e78dc85b3.png">

**Comment by pragneshpj** [comment]
<img width="274" alt="Screenshot 2020-09-14 at 11 18 35 AM" src="https://user-images.githubusercontent.com/30809418/93048241-0a746800-f67c-11ea-87ba-c9039090262e.png">

Is there any way to open drawer from bottom tab and show back side of bottom tab.?
Anyone know about this?

**Comment by satya164** [comment]
You need to use `react-native-safe-area-context` and handle it. https://reactnavigation.org/docs/handling-safe-area#use-the-hook-for-more-control

**Comment by tribou** [comment]
Hi @satya164 I'm still seeing this issue using `@react-navigation/material-bottom-tabs@5.3.2` and `react-native-safe-area-context@3.1.8`. 

I also tried using the `useSafeAreaInsets()` with `<Tab.Screen style={{ paddingBottom: insets.bottom }} ...` but that raises the entire bottom tab bar instead of inserting the padding underneath the tabBarLabels. Am I missing something?

**Comment by tribou** [comment]
I'm seeing this on an iPhone 12 series/iOS 14, so wondering if this is somehow related to https://github.com/react-navigation/react-navigation/issues/8972

**Comment by mars-lan** [comment]
`material-bottom-tabs` uses `react-native-paper`, which in turns uses an old version of `react-native-safe-area-view` (see https://github.com/callstack/react-native-paper/issues/2323).

**Comment by HughBerriez** [comment]
issued linked to @mars-lan link as well as this https://github.com/react-navigation/react-navigation/issues/9110#issuecomment-742642540

**Comment by HughBerriez** [comment]
https://github.com/callstack/react-native-paper/issues/2419

quick update from my end: updating to v4.5.0 fixed it for me

**Comment by nguyenbathanh** [comment]
Is there any updates on this issue? I have tried solution from the above comments but it doesn't seem to work.
