### ISSUE TITLE
Making sure the route specified in initialRouteName is always added as the first screen in the stack

### ISSUE THREAD

**Issue by remanation** [react-navigation/react-navigation#8843]
**Current Behavior**
Our app have multiple tabs, each tab contains a stack.
We need to be able to navigate from a screen in stack belonging to one tab to a specific screen in a stack belonging to another tab. This can be done like so `navigation.navigate("tab2", {screen:"screen2"})`.

The problem is that if I have not navigated to the initial route for the destination stack(route) before, screen2 is now the only screen in the stack. I need somehow to always make sure that the screen specified in the initialRouteName is added to the stack first. 

**Expected Behavior**
If you specify initialRouteName that route is always added as the first route in the stack, even if you navigate to a specific route defined in the stack.

> Setting lazy=false, would solve the issue, but it's important to not initialise the "initial route screen" before actual navigating to a screen in the stack.

**How to reproduce**
The issue/problem can be reproduced in this [snack](https://snack.expo.io/@remanation/react-navigation-issue)
Click the "Navigate to Screen2 on Tab 2" button on "tab1". Make sure you have not clicked on Tab2 before doing this. 
You are now navigated to Screen2 on Tab2 with no option to navigation to the screen specified in initialRouteName.

**Your Environment**

| software                      | version |
| ----------------------------- | ------- |
| iOS or Android                |
| @react-navigation/native      |5.7.3
| @react-navigation/bottom-tabs |5.8.0
| @react-navigation/stack |5.9.0
| react-native-screens          |
| react-native                  |
| expo                          |
| node                          |
| npm or yarn                   |

**Comment by satya164** [comment]
https://reactnavigation.org/docs/nesting-navigators#rendering-initial-route-defined-in-the-navigator

**Comment by remanation** [comment]
@satya164 Thank you for the quick response, really appreciate it.
