### ISSUE TITLE
How to Disable Swiping Down of Pages on IOS Devices?

### ISSUE THREAD

**Issue by Danik711** [react-navigation/react-navigation#8847]
**Current Behavior**

I had set up a stack navigator with several pages in it. This does not happen on Android, but it happens on IOS. Users are able to dismiss the page by swiping down from the top of the page. This causes the issues as when people sign out from the app they can swipe down the very first page and go back to main experience without authentication.

```javascript
      <Stack.Screen
        name="Settings"
        component={Settings}
        options={{
          gestureEnabled: false,
        }}
      />
```
I saw that example, but it does not work for me. I am still able to swipe the page down on IOS.

**Expected Behavior**

I want to prohibit users from swiping down.

**How to reproduce**

Set up a simple stack navigator with at least two pages. On the second page swipe down from the top of the page on IOS devices and set gestureEnabled to false at the options of the <Stack.Screen />

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS                  | 13.7 |
| @react-navigation/native | 5.0.9      |
| @react-navigation/material-top-tabs | 5.1.1     |
| @react-navigation/stack | 5.1.1       |
| react-native                   | 0.61.5 |

**Comment by ksloan** [comment]
Seeing this as well. `gestureEnabled: false` seems to do nothing.

**Comment by satya164** [comment]
> This causes the issues as when people sign out from the app they can swipe down the very first page and go back to main experience without authentication.

You need to remove screens that require authentication if the user is not logged in. https://reactnavigation.org/docs/auth-flow/

**Comment by satya164** [comment]
Closing since you haven't provided a repro to debug the issue. If you manage to make a repro, please open a new issue with it and someone will take a look at it when possible.
