### ISSUE TITLE
`beforeRemove` event listener doesnt work with TabNavigator

### ISSUE THREAD

**Issue by ortonomy** [react-navigation/react-navigation#8851]
**Current Behavior**

- Added listener to `beforeRemove` on tab navigator `listeners` AND `useEfffect`
- Navigate tabs
- No event fired

```
<MainTab.Screen
        name="Settings"
        component={SettingsScreen}
        listeners={{
          beforeRemove: function (e) {
            console.log('navigating away', e);
          },
        }}
      />



```

**Expected Behaviour**
- should fire event and console log `navigating away` when tapping any of the two other tabs. it doesn't
- ![image](https://user-images.githubusercontent.com/6688676/93305758-8c59c200-f831-11ea-8dbd-88a6a9b0ac41.png)

**How to reproduce**

- reproduction: https://snack.expo.io/@ortonomy/848103

**Your Environment**

| software                      | version |
| ----------------------------- | ------- |
| iOS or Android                | android X , ios 13.7|
| @react-navigation/native      | 5.7.3 | 
| @react-navigation/bottom-tabs | 5.8.0 |
| react-native-screens          | 2.9.0 |
| react-native                  | 0.63.2 |
| expo                          | not using expo |
| node                          | 12 |
| npm or yarn                   | yarn |

**Comment by alfarodarwaynejay** [comment]
It doesn't work also with `@react-navigation/material-bottom-tabs` **5.2.13** with `react-native`  **0.62.2**

**Comment by NishargShah** [comment]
any update?

**Comment by satya164** [comment]
As the name suggests, `beforeRemove` is triggered when a screen is being removed. When you change tabs, the screen is still there, just unfocused. It's not expected to trigger the event just like pushing a new screen on stack doesn't trigger it, since the previous screen is still there.

**Comment by ortonomy** [comment]
@satya164 - that's a deeply unhelpful answer. Before remove of a screen or not, enough people seem to want to a 'beforeNavigate' hook here. No plans to implement?

**Comment by satya164** [comment]
What am I supposed to answer? If you have a feature request then you need to create a feature request on canny why the use case (link is shown before creating a new issue). You opened a bug report and this is not a bug.

**Comment by NishargShah** [comment]
@satya164 please write that in docs, so users will know about that in future

**Comment by satya164** [comment]
Feel free to send a PR here https://github.com/react-navigation/react-navigation.github.io

**Comment by NishargShah** [comment]
@satya164 any way to listen to the changes when users go to other screens and that have the` preventDefault()` feature?

**Comment by LadislavBohm** [comment]
If you need to do some cleanup when use leaves current tab you can use "useFocusEffect" which works even when current tab changes (and component is not unmounted).

**Comment by Bournegit** [comment]
[](https://reactnavigation.org/docs/custom-android-back-button-handling/)

**Comment by Bournegit** [comment]
https://reactnavigation.org/docs/custom-android-back-button-handling/

**Comment by KevinMac19** [comment]
Is there any solutions found for this ?

**Comment by hjdr** [comment]
You _could_ use `tabPress` to detect a change of tabs. It's not ideal, but considering @satya164's stinky attitude, it may have to suffice.
Here is a helpful thread on stackoverflow: https://stackoverflow.com/a/61154477/11345276

```
<Tab.Navigator>
    <Tab.Screen
        component={HomeScreen}
        name="HomeScreen"
        listeners={{
          tabPress: e =>  //  <-- something here 
          },
        }}
      />
      <Tab.Screen
        ../>
</Tab.Navigator>
```

**Comment by nriccar** [comment]
You could accomplish this by
```javascript
  import { useIsFocused } from '@react-navigation/native'
  const isFocused = useIsFocused()
  const canGoBack: boolean = false
  useEffect(() => {
    if (!isFocused) if (!canGoBack) navigation.navigate(route.name)
  }, [route, isFocused])
  ```
