### ISSUE TITLE
useRoute().params content is not consistent on deep link

### ISSUE THREAD

**Issue by mbouxin** [react-navigation/react-navigation#8852]
**Current Behavior**

I am using deep linking. On Android (did not check on iOS), when I use a deep link from Chrome with url parameters, I found that the useRoute().params content if the application was in memory or not.

More precisely when I access {{domain}}/path?code=abc from a Chrome link, 
 - If the application is up, useRoute().params contains
```js
{
  initial: true,
  params: { code: 'abc' }
  ... other stuff but not 'code' value
}
```
 - If the application is down, useRoute().params contains
```js
{
  code: 'abc' 
}
```

This can easily be bypassed by using route.params.params but I do not think this is the expected behavior

**Expected Behavior**

The content of route.params should always be the same. At least route.params.code should be defined in both cases

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| Android                 | 10
| @react-navigation/native       | 5.7.3
| react-native                   | 0.63.2
| node                           | 12.18.3
| yarn                    | 1.22.4

**Comment by satya164** [comment]
https://github.com/react-navigation/react-navigation/commit/e8515f9cd94a912c107a407dea3d953c4172393f
