### ISSUE TITLE
Error: 'This package itself specifies a 'main' module field that could not be resolved'

### ISSUE THREAD

**Issue by codareg** [react-navigation/react-navigation#8855]
**Current Behavior**

When using react navigation, I keep getting the following error:
` Error: While trying to resolve module `@react-navigation/native` from file `/Users/user/Project/index.js`, the package `/Users/user/Project/node_modules/@react-navigation/native/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/user/Project/node_modules/@react-navigation/native/src/index.tsx`. Indeed, none of these files exist:

  * /Users/user/Project/node_modules/@react-navigation/native/src/index.tsx(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)
  * /Users/user/Project/node_modules/@react-navigation/native/src/index.tsx/index(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)
    at ResolutionRequest.resolveDependency (/Users/user/Project/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:65:15)
    at DependencyGraph.resolveDependency (/Users/user/Project/node_modules/metro/src/node-haste/DependencyGraph.js:287:16)
    at Object.resolve (/Users/user/Project/node_modules/metro/src/lib/transformHelpers.js:267:42)
    at /Users/user/Project/node_modules/metro/src/DeltaBundler/traverseDependencies.js:434:31
    at Array.map (<anonymous>)
    at resolveDependencies (/Users/user/Project/node_modules/metro/src/DeltaBundler/traverseDependencies.js:431:18)
    at /Users/user/Project/node_modules/metro/src/DeltaBundler/traverseDependencies.js:275:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/user/project/node_modules/metro/src/DeltaBundler/traverseDependencies.js:87:24)
    at _next (/Users/user/Projectnode_modules/metro/src/DeltaBundler/traverseDependencies.js:107:9)`

**Expected Behavior**
I want it to work properly.

**How to reproduce**
Install React Navigation as seen in the Documentation.
Insert the  following code in your index.js
```
/**
 * @format
 */
import 'react-native-gesture-handler';
import { NavigationContainer, StackActions } from '@react-navigation/native';
import { createStackNavigator } from '@react-navigation/stack';
import React from 'react';
import {AppRegistry} from 'react-native';
import Logsg from './screens/logsg.js';
import {name as appName} from './app.json';

const AuthStack = () => {
return(
 <NavigationContainer>
     <Stack.Navigator>
         <Stack.Screen name="Logsg" component ={Logsg}/>
     </Stack.Navigator>
 </NavigationContainer>
)
}


AppRegistry.registerComponent(appName, () => AuthStack);
```
**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |13.7
| @react-navigation/native    |5
| react-native                   |0.63.2
| expo                           |
| node                           |
| npm or yarn                    |6.14.5

**Comment by re-ali** [comment]
After a long research MetroJS bundler default not compile .ts and .tsx extension files we need tell MetroJS bundler to compiles .ts and .tsx files i solved this error by edit metro.config.js file in root project folder by following.


module.exports = {

  resolver: {
   sourceExts: ['jsx','js','ts','tsx'] //add here 
  },
};

**Comment by re-ali** [comment]
> After a long research MetroJS bundler default not compile .ts and .tsx extension files we need tell MetroJS bundler to compiles .ts and .tsx files i solved this error by edit metro.config.js file in root project folder by following.
> 
> module.exports = {
> 
> resolver: {
> sourceExts: ['jsx','js','ts','tsx'] //add here
> },
> };

The above solution worked for me. Simply adding peace of code in module.expert object.

**Comment by kpyworld1994** [comment]
Error: While trying to resolve module `react-native-elements` from file `C:\Users\DELL\Desktop\Transas-ReactNative\src\screens\registratonAsVendor\team.js`, the package `C:\Users\DELL\Desktop\Transas-ReactNative\node_modules\react-native-elements\package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`C:\Users\DELL\Desktop\Transas-ReactNative\node_modules\react-native-elements\index`. Indeed, none of these files exist:

  * C:\Users\DELL\Desktop\Transas-ReactNative\node_modules\react-native-elements\index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.svg|.native.svg|.svg)
  * C:\Users\DELL\Desktop\Transas-ReactNative\node_modules\react-native-elements\index\index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.svg|.native.svg|.svg)
    at DependencyGraph.resolveDependency (C:\Users\DELL\Desktop\Transas-ReactNative\node_modules\metro\src\node-haste\DependencyGraph.js:376:17)
    at Object.resolve (C:\Users\DELL\Desktop\Transas-ReactNative\node_modules\metro\src\lib\transformHelpers.js:271:42)
    at resolve (C:\Users\DELL\Desktop\Transas-ReactNative\node_modules\metro\src\DeltaBundler\traverseDependencies.js:571:33)
    at C:\Users\DELL\Desktop\Transas-ReactNative\node_modules\metro\src\DeltaBundler\traverseDependencies.js:587:26
    at Array.reduce (<anonymous>)
    at resolveDependencies (C:\Users\DELL\Desktop\Transas-ReactNative\node_modules\metro\src\DeltaBundler\traverseDependencies.js:586:33)
    at C:\Users\DELL\Desktop\Transas-ReactNative\node_modules\metro\src\DeltaBundler\traverseDependencies.js:275:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (C:\Users\DELL\Desktop\Transas-ReactNative\node_modules\metro\src\DeltaBundler\traverseDependencies.js:87:24)
    at _next (C:\Users\DELL\Desktop\Transas-ReactNative\node_modules\metro\src\DeltaBundler\traverseDependencies.js:107:9)
"dependencies": {
    "@react-native-async-storage/async-storage": "^1.15.4",
    "@react-native-community/datetimepicker": "^3.5.2",
    "@react-native-community/geolocation": "^2.0.2",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-native-community/netinfo": "^8.0.0",
    "@react-native-community/push-notification-ios": "^1.0.2",
    "@react-native-firebase/app": "^14.5.0",
    "@react-navigation/bottom-tabs": "^5.11.11",
    "@react-navigation/drawer": "^5.12.5",
    "@react-navigation/native": "^5.9.3",
    "@react-navigation/stack": "^5.14.3",
    "axios": "^0.21.4",
    "moment": "^2.29.1",
    "native-base": "^2.15.2",
    "qs": "^6.10.1",
    "react": "16.13.1",
    "react-native": "0.63.4",
    "react-native-app-intro-slider": "^4.0.4",
    "react-native-countdown-component": "^2.7.1",
    "react-native-document-picker": "^4.1.0",
    "react-native-dropdown-picker": "^5.1.4",
    "react-native-elements": "git+https://github.com/react-native-elements/react-native-elements.git#dist",
    "react-native-gesture-handler": "^1.10.2",
    "react-native-gifted-chat": "^0.16.3",
    "react-native-reanimated": "^2.2.3",
    "react-native-safe-area-context": "^3.1.9",
    "react-native-screens": "^2.17.1",
    "react-native-simple-radio-button": "^2.7.4",
    "react-native-svg": "^12.1.1",
    "react-native-svg-transformer": "^0.14.3",
    "react-native-tooltip": "^5.2.0",
    "react-redux": "^7.2.2",
    "redux": "^4.0.5",
    "redux-devtools-extension": "^2.13.8",
    "redux-thunk": "^2.3.0",
    "rne-modal-tooltip": "gist:b28c003d87c619674def0878473338a0"
  },
anyone can help

**Comment by thomashagstrom** [comment]
Had this issue for firebase on expo and had to add a cjs to resolver in metro.config.js

https://github.com/firebase/firebase-js-sdk/issues/6253#issuecomment-1123923581

```javascript
// metro.config.js
const { getDefaultConfig } = require("@expo/metro-config");

const defaultConfig = getDefaultConfig(__dirname);

defaultConfig.resolver.assetExts.push("cjs");

module.exports = defaultConfig;
```

**Comment by sourabhsainii** [comment]
> Error: While trying to resolve module `react-native-elements` from file `C:\Users\DELL\Desktop\Transas-ReactNative\src\screens\registratonAsVendor\team.js`, the package `C:\Users\DELL\Desktop\Transas-ReactNative\node_modules\react-native-elements\package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`C:\Users\DELL\Desktop\Transas-ReactNative\node_modules\react-native-elements\index`. Indeed, none of these files exist:
> 
> * C:\Users\DELL\Desktop\Transas-ReactNative\node_modules\react-native-elements\index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.svg|.native.svg|.svg)
> * C:\Users\DELL\Desktop\Transas-ReactNative\node_modules\react-native-elements\index\index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.svg|.native.svg|.svg)
>   at DependencyGraph.resolveDependency (C:\Users\DELL\Desktop\Transas-ReactNative\node_modules\metro\src\node-haste\DependencyGraph.js:376:17)
>   at Object.resolve (C:\Users\DELL\Desktop\Transas-ReactNative\node_modules\metro\src\lib\transformHelpers.js:271:42)
>   at resolve (C:\Users\DELL\Desktop\Transas-ReactNative\node_modules\metro\src\DeltaBundler\traverseDependencies.js:571:33)
>   at C:\Users\DELL\Desktop\Transas-ReactNative\node_modules\metro\src\DeltaBundler\traverseDependencies.js:587:26
>   at Array.reduce ()
>   at resolveDependencies (C:\Users\DELL\Desktop\Transas-ReactNative\node_modules\metro\src\DeltaBundler\traverseDependencies.js:586:33)
>   at C:\Users\DELL\Desktop\Transas-ReactNative\node_modules\metro\src\DeltaBundler\traverseDependencies.js:275:33
>   at Generator.next ()
>   at asyncGeneratorStep (C:\Users\DELL\Desktop\Transas-ReactNative\node_modules\metro\src\DeltaBundler\traverseDependencies.js:87:24)
>   at _next (C:\Users\DELL\Desktop\Transas-ReactNative\node_modules\metro\src\DeltaBundler\traverseDependencies.js:107:9)
>   "dependencies": {
>   "@react-native-async-storage/async-storage": "^1.15.4",
>   "@react-native-community/datetimepicker": "^3.5.2",
>   "@react-native-community/geolocation": "^2.0.2",
>   "@react-native-community/masked-view": "^0.1.10",
>   "@react-native-community/netinfo": "^8.0.0",
>   "@react-native-community/push-notification-ios": "^1.0.2",
>   "@react-native-firebase/app": "^14.5.0",
>   "@react-navigation/bottom-tabs": "^5.11.11",
>   "@react-navigation/drawer": "^5.12.5",
>   "@react-navigation/native": "^5.9.3",
>   "@react-navigation/stack": "^5.14.3",
>   "axios": "^0.21.4",
>   "moment": "^2.29.1",
>   "native-base": "^2.15.2",
>   "qs": "^6.10.1",
>   "react": "16.13.1",
>   "react-native": "0.63.4",
>   "react-native-app-intro-slider": "^4.0.4",
>   "react-native-countdown-component": "^2.7.1",
>   "react-native-document-picker": "^4.1.0",
>   "react-native-dropdown-picker": "^5.1.4",
>   "react-native-elements": "git+https://github.com/react-native-elements/react-native-elements.git#dist",
>   "react-native-gesture-handler": "^1.10.2",
>   "react-native-gifted-chat": "^0.16.3",
>   "react-native-reanimated": "^2.2.3",
>   "react-native-safe-area-context": "^3.1.9",
>   "react-native-screens": "^2.17.1",
>   "react-native-simple-radio-button": "^2.7.4",
>   "react-native-svg": "^12.1.1",
>   "react-native-svg-transformer": "^0.14.3",
>   "react-native-tooltip": "^5.2.0",
>   "react-redux": "^7.2.2",
>   "redux": "^4.0.5",
>   "redux-devtools-extension": "^2.13.8",
>   "redux-thunk": "^2.3.0",
>   "rne-modal-tooltip": "gist:b28c003d87c619674def0878473338a0"
>   },
>   anyone can help

I'm also facing similar issue.Were you able to figure it out
