### ISSUE TITLE
DrawerItem focused always false

### ISSUE THREAD

**Issue by IceRD** [react-navigation/react-navigation#8863]
**DrawerItem focused always false**
It is impossible to identify the current screen

I have multiple screens, some of them don't need to be displayed.
tried using DrawerContent, focus works correctly, but no icons display

**Navigation**
```
const DrawerNavigator = createDrawerNavigator();
export default function () {
	return (
		<DrawerNavigator.Navigator
			drawerContent={(props) => <DrawerScreen {...props} />}
			initialRouteName="Catalog">
			<DrawerNavigator.Screen
				name="Catalog"
				component={CatalogScreen}
			/>
			<DrawerNavigator.Screen
				name="IPTV"
				component={IpTvScreen}
			/>
		</DrawerNavigator.Navigator>
	);
}
```

**DrawerScreen**
```
export default class DrawerScreen extends React.Component {
	constructor(props) {
		super(props);
	}

	render() {
		return (
			<SafeAreaView>
				<DrawerContentScrollView {...this.props}>
					<DrawerItem
						{...this.props}
						label={({focused, color}) => (
							<Text style={{color}}>
								{focused ? 'Focused text' : 'Unfocused text'}
							</Text>
						)}
						onPress={() => {
							this.props.navigation.navigate('Catalog');
						}}
					/>
					<DrawerItem
						{...this.props}
						label={({focused, color}) => (
							<Text style={{color}}>
								{focused ? 'Focused text' : 'Unfocused text'}
							</Text>
						)}
						onPress={() => {
							this.props.navigation.navigate('IPTV');
						}}
					/>
				</DrawerContentScrollView>
			</SafeAreaView>
		);
	}
}
```

Catalog / IPTV screen
```
export default function () {
	return (
		<View style={{flex: 1, alignItems: 'center', justifyContent: 'center'}}>
			<Text>Catalog</Text>
		</View>
	);
}
```

icon and title always get false

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |  Android 
| @react-navigation/native       | 5.7.3
| @react-navigation/drawer       | 5.9.0
| react-native-reanimated        |  1.13.0
| react-native-gesture-handler   | 1.8.0
| react-native-safe-area-context |  3.1.7
| react-native-screens           | 2.10.1
| react-native                   | 0.63.2
| expo                           | - 
| node                           | 14.8.0
| npm or yarn                    | npm

**Comment by 000xuandu** [comment]
Are facing the same problem.

**Comment by satya164** [comment]
You need to pass correct props to `DrawerItem`

https://github.com/react-navigation/react-navigation/blob/9e3650831c22b47130d2b388390f7eb7910fe91d/packages/drawer/src/views/DrawerItemList.tsx#L41
