### ISSUE TITLE
Simpler Left-to-right Stack Navigation transitions (#2393) In React Navigation 5 

### ISSUE THREAD

**Issue by ePoromaa** [react-navigation/react-navigation#8867]
We are trying to update to react-navigation v5 but we can't make our header animation work. 

We have an implementation similar to https://github.com/react-navigation/react-navigation/issues/2393#issuecomment-348885307. How do we migrate the `transitionConfig` to React Navigation 5?

**Comment by satya164** [comment]
https://reactnavigation.org/docs/stack-navigator#pre-made-configs
