### ISSUE TITLE
Images disappearing when deeply nested in Views in a screen that is nested in stacks

### ISSUE THREAD

**Issue by kamaal111** [react-navigation/react-navigation#8870]
**Current Behavior**

- There is a limit Views you can use when you have a screen in a nested. You are not able to see Images if you exceed this limit. The limit is 61 Views deep in an image. This only happens on iOS 12.4
- When the app is in the background you can see the image (see example below)

**Expected Behavior**

- Expected to see an Image in a deeply nested Views.

**How to reproduce**

[Sample project](https://github.com/kamaal111/ReactNavigationTooManyViews)
- Run the sample project on a iOS 12.4 simulator.
- Remove 1 View layer and the image should appear.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS                 | 12.4 |
| @react-navigation/native       | 5.7.3 |
| @react-navigation/stack        | 5.9.0 |
| react-native-gesture-handler   | 1.8.0 |
| react-native-safe-area-context | 3.1.8 |
| react-native-screens           | 2.11.0 |
| react-native                   | 0.63.2 |
| node                           | v13.10.1 |
| npm or yarn                    | 1.22.5 |

![screenshot 1](https://github.com/kamaal111/ReactNavigationTooManyViews/blob/master/Simulator%20Screen%20Shot%20-%20iPhone%20X%20-%202020-09-18%20at%2016.18.25.png?raw=true)
![screenshot 2](https://github.com/kamaal111/ReactNavigationTooManyViews/blob/master/Simulator%20Screen%20Shot%20-%20iPhone%20X%20-%202020-09-18%20at%2016.18.32.png?raw=true)

**Comment by Abhishek-Sankey** [comment]
I've also upgraded the react-navigation from 3 to 4 and facing the same issue.

**Comment by satya164** [comment]
Please open the issue in React Native repo.

**Comment by sohail-dragon** [comment]
For us this seems to only be an issue after updating to react navigation 5 and on iOS 12.4.8 only. 
@kamaal111 did you by any chance open and issue on react native you could link.
I tried replicating by deeply nesting components in react navigation 4 and wasn't able to. @satya164 any idea what could lead to something like this?

**Comment by kamaal111** [comment]
Hi @sohail-dragon,

I haven't opened an issue on react native. I have fixed the issue where it really occurred by using Fragments as much as possible.

**Comment by kesha-antonov** [comment]
Related https://github.com/facebook/react-native/issues/33037
