### ISSUE TITLE
When I use ModalPresentationIOS on a screen, it will cause the head to display abnormally. If I want to solve this problem, setting headerMode: screen in the Navigator is normal, but the entire screen will move on the IOS, and the fade-in and fade-out title cannot be used.

### ISSUE THREAD

**Issue by sunleonx** [react-navigation/react-navigation#8872]
When I use ModalPresentationIOS on a screen, it will cause the head to display abnormally. If I want to solve this problem, setting headerMode: screen in the Navigator is normal, but the entire screen will move on the IOS, and the fade-in and fade-out title cannot be used.

Version：
Latest version used

![RPReplay_Final1600513947](https://user-images.githubusercontent.com/38236663/93665904-ace18080-faac-11ea-8bc6-fb112f5d0803.gif)

![RPReplay_Final1600513912](https://user-images.githubusercontent.com/38236663/93665905-ae12ad80-faac-11ea-98b5-88451fcdbf1b.gif)

**Comment by sunleonx** [comment]
> Couldn't find version numbers for the following packages in the issue:
> 
> * `@react-navigation/native`
> 
> Can you update the issue to include version numbers for those packages? The version numbers must match the format 1.2.3.

Version:
```
"@react-native-community/masked-view": "^0.1.10",
    "@react-navigation/bottom-tabs": "^5.8.0",
    "@react-navigation/native": "^5.7.3",
    "@react-navigation/stack": "^5.9.0",
    "mobx": "^5.15.6",
    "mobx-react": "^6.3.0",
    "react": "16.13.1",
    "react-native": "0.63.2",
    "react-native-gesture-handler": "^1.8.0",
    "react-native-reanimated": "^1.13.0",
    "react-native-safe-area-context": "^3.1.7",
    "react-native-screens": "^2.11.0",
    "react-native-vector-icons": "^7.1.0"
```

code1:
```
<NavigationContainer ref={_ref} theme={this.state.dark ? DarkTheme : DefaultTheme}>
    <RootStackNavigator />
</NavigationContainer>
```

RootStack:
![image](https://user-images.githubusercontent.com/38236663/93669072-d8bc3080-fac3-11ea-8d26-9ab6fc0b66aa.png)

BottomTabs:
![image](https://user-images.githubusercontent.com/38236663/93669078-e96ca680-fac3-11ea-9dde-b6d1b5367b19.png)

**Comment by satya164** [comment]
You should render a modal stack at the root for your modal screens: https://reactnavigation.org/docs/modal/

Currently it's not possible to combine modal presentation ios animation with other animations since it has special behaviour.
