### ISSUE TITLE
Universal Link doesn't take user to the inside page in React Navigation V5 Deeplink

### ISSUE THREAD

**Issue by ajitdas123** [react-navigation/react-navigation#8874]
I am trying to work with deep-link in react-navigation v5
Everything is implemented and working fine as long as I use local URL (eg `app://mycoolapp/detail/3`) it opens the app and take the user to the detail page as expected.

But when I try to use the same with a universal URL eg `https://www.exampleapp.com/app/detail/3` it opens the app but it doesn't take the user to the detail page, rather it just shows the home page.

Why this is happening and how can this be resolved.

Here is my android `AndroidManifest.xml` file setting

```
 <intent-filter android:label="@string/app_name" android:autoVerify="true">
              <action android:name="android.intent.action.VIEW" />
              <category android:name="android.intent.category.DEFAULT" />
              <category android:name="android.intent.category.BROWSABLE" />
              <!-- Accepts URIs that begin with "https://www.exampleapp.com/app” -->
              <data android:scheme="https"
                    android:host="www.exampleapp.com"
                    android:pathPrefix="/app" />
              <data android:scheme="http" />
          </intent-filter>
          <intent-filter android:label="@string/app_name">
              <action android:name="android.intent.action.VIEW" />
              <category android:name="android.intent.category.DEFAULT" />
              <category android:name="android.intent.category.BROWSABLE" />
              <!-- Accepts URIs that begin with "app://mycoolapp -->
              <data android:scheme="app"
                    android:host="mycoolapp" />
          </intent-filter>
```

And here my router/navigation page settings

```
    const LINK_PREFIX = ['app://mycoolapp', 'https://www.exampleapp.com/app']
    const config = {
        screens: {
            Detail: {
                path: 'detail/:id',

            },
            Home: '*'
        },
    };
    const linking = {
        prefixes: [...LINK_PREFIX],
        config
    };

    <NavigationContainer ref={navigationRef} linking={linking} fallback={<Text>Loading...</Text>}>
        <Stack.Navigator screenOptions={{headerShown: false}}>
            <Stack.Screen
                name='Home'
                component={Home}
                options={{headerShown: false}}
            />
            <Stack.Screen
                name='Detail'
                component={Detail}
                options={{headerShown: false}}
            />
        </Stack.Navigator>
    </NavigationContainer>
```

I have checked the [documentation][1] of react-navigation also the android documentation nothing additional setup mention on for that. 

I have shared the same question on [stackoverflow](https://stackoverflow.com/questions/63973146/universal-link-doesnt-take-user-to-the-inside-page-in-react-navigation-v5-deepl) as well

  [1]: https://reactnavigation.org/docs/deep-linking/#universal-links

**Current Behavior**

- If a user click on the Universal URL it simply opens the app and pushes to the home page, while the local URL takes to the inside page, for my case detail page

**Expected Behavior**

- Expected it to take the user to the detail page same as local URL

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Android
| @react-navigation/native       | ^5.7.1
| react-native                   | 0:63:2

**Comment by ajitdas123** [comment]
Expo Repo @satya164 https://snack.expo.io/@ajitdas/react-navigation-deep-linking 

Package dependency might not be linked properly, not sure how to add the dependencies, but I hope this repo helps to track down the issue

**Comment by satya164** [comment]
Please provide a repro in a GitHub repo with the dependencies properly setup. It's not possible to test deep links on Snack.

**Comment by babyrusa** [comment]
@ajitdas123  Did you figure this out? I'm facing a similar issue but on IOS. It works fine on Android. I think it has to do with a set up but I haven't yet configured out.
