### ISSUE TITLE
Navigating to non-default screen in nested navigator only works from outside the Stack

### ISSUE THREAD

**Issue by mark-carrington** [react-navigation/react-navigation#8878]
**Current Behavior**

I’m trying to navigate to a non-default screen in a nested navigator via a deep link. I’ve looked at the docs on [how to navigate to screens in a nested navigator](https://reactnavigation.org/docs/nesting-navigators/#navigating-to-a-screen-in-a-nested-navigator), and I’ve used the approach mentioned (sample code below):

navigation.navigate(’StackTwo', { screen: ’NonDefaultPage' })

This works fine as long as we’re not currently in the defined Stack. If we are in StackTwo, and call the above, we end up navigating to the default page in StackTwo, rather than the desired screen. Calling navigate(’NonDefaultPage’) will work, but to know when to call which one requires you to know which stack you’re currently in.

I am able determine if I’m currently in StackTwo based on the current navigation state (by looking at the last item in history). But this seems quite messy, and wondered if there is perhaps a better approach? Or if this is to be considered a bug that will be fixed?

**Expected Behavior**

Calling navigation.navigate(’StackTwo', { screen: ’NonDefaultPage' }) from StackTwo, would navigate to the NonDefaultPage, as it does when you call it from outside that stack.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | 13.7
| @react-navigation/native       | 5.7.3
| @react-navigation/stack        | 5.9.0
| react-native-gesture-handler   | 1.6.1
| react-native-safe-area-context | 3.1.4
| react-native-screens           | 2.10.1
| react-native                   | 0.61.5
| expo                           |
| node                           | 12.2
| npm or yarn                    | 1.17.3

**Comment by satya164** [comment]
Closing since no repro is provided.
