### ISSUE TITLE
Can I hide tab bar dynamically?

### ISSUE THREAD

**Issue by zhaoyi0113** [react-navigation/react-navigation#888]
Below is my code on a tab bar component.

```
static navigationOptions = {
    tabBar: {
      label: '',
      icon: (obj) => {
        const image = obj.focused ? require('1.png') : require('2.png');
        return <Image style={{resizeMode:'contain', width:40, height: 40}}
                      source={image}
        />
      }
    },
  };
```

Can I hide the tab bar dynamically? I know I can add `visible: false` under `tabBar` property but I want to show/hide based on a component state. How can I achieve this?

**Comment by MM-Psiiirus** [comment]
Have you tried to use setParams? 

https://reactnavigation.org/docs/navigators/navigation-prop#setParams-Make-changes-to-route-params

**Comment by zhaoyi0113** [comment]
I tried this code `this.props.navigation.setParams({tabBar:{visible:false}})` but it doesn't make the tab bar invisible? Did I pass a wrong parameter?

**Comment by zhaoyi0113** [comment]
I think `setParams` only works for setting route parameters. But the `visible:false` is not a route parameter. Instead it is a configuration set under `navigationOptions`. Is there a way to update it dynamically?

**Comment by MM-Psiiirus** [comment]
mhh yeah maybe u r right. the tabbar node can be an object or and function maybe this will help you ? 

The acc function parameter is the navigationOptions of the current open screen for example an stackNavigator subpage.


````
export const CustomTabNavigator = TabNavigator({
...
Camera: {
        screen: CameraTab,
        navigationOptions: {
            tabBar: (state,acc) => {
                return {
                    visible: (acc && acc.visible !== 'undefined') ? acc.visible : true,
                    label: 'Camera',
                    icon: ({focused}) => createTabbarIcon('camera', focused)
                }
            },
        }
    },
...
});
`````

**Comment by zhaoyi0113** [comment]
Thanks for your response. I understand the general idea. But I don't know how to update the `acc` parameter in my component? Is the `acc` a state of my component or something else?

**Comment by MM-Psiiirus** [comment]
i think the acc is this:

````
static navigationOptions = {
    tabBar: {
      label: '',
      icon: (obj) => {
        const image = obj.focused ? require('1.png') : require('2.png');
        return <Image style={{resizeMode:'contain', width:40, height: 40}}
                      source={image}
        />
      }
    },
  };
````

**Comment by zhaoyi0113** [comment]
I see. When I update the acc value, the tab bar didn't get rendered. How can I make it re-render when the property value got changed?

**Comment by vitorebatista** [comment]
I have the same problem... 
Is there any example working?

**Comment by richardfickling** [comment]
My solution, to animate the tab bar hiding and showing based on navigatino params.

in your TabNavigator declaration:
```
const MyTabNav = TabNavigator(
  {
    Home: { Screen: HomeScreen },
    Profile: { Screen: ProfileScreen },
  },
  {
    tabBarComponent: TabBar,
  }
);
```

The Tab Bar itself:
```
import React, { Component } from 'react';
import { Animated } from 'react-native';
import { TabBarBottom } from 'react-navigation';

const TAB_BAR_OFFSET = -60;

export default class TabBar extends Component {
  constructor(props) {
    super(props);
    this.state = {
      offset: new Animated.Value(0),
    };
  }

  componentWillReceiveProps(props) {
    const oldState = this.props.navigation.state;
    const oldRoute = oldState.routes[oldState.index];
    const oldParams = oldRoute.params;
    const wasVisible = !oldParams || oldParams.visible;

    const newState = props.navigation.state;
    const newRoute = newState.routes[newState.index];
    const newParams = newRoute.params;
    const isVisible = !newParams || newParams.visible;

    if (wasVisible && !isVisible) {
      Animated.timing(this.state.offset, { toValue: TAB_BAR_OFFSET, duration: 200 }).start();
    } else if (isVisible && !wasVisible) {
      Animated.timing(this.state.offset, { toValue: 0, duration: 200 }).start();
    }
  }

  render() {
    return (
        <TabBarBottom {...this.props} style={[styles.container, { bottom: this.state.offset }]}/>
    );
  }
}

const styles = {
  container: {
    overflow: 'hidden',
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: 'white',
    elevation: 8,
  },
};
```

To use it, just call `this.props.navigation.setParams({ visible: true/false });` in your HomeScreen or ProfileScreen.
You can of course animate however you want - I choose to have it slide off the screen.

**Comment by markjongkind** [comment]
@richardfickling thanks for sharing! I had a problem with animating the <TabBarBottom> component, because it's not a <Animated.View>. Code below fixes that:

`render() {
		return (
			<Animated.View style={[styles.container, { bottom: this.state.offset }]}>
				<TabBarBottom {...this.props} />
			</Animated.View>
		);
	}`

**Comment by richardfickling** [comment]
it's an animated view on master as of 3 days ago :) https://github.com/react-community/react-navigation/commit/d4ce9b08abf7aa725aca8305e841e1adf48d8a44

I had your code exactly until that change was merged.

**Comment by SamMatthewsIsACommonName** [comment]
Thanks guys this was a great guide. I was having trouble with setParams as I had a stack navigator nested inside a tab navigator, so what i ended up doing was making the TabBar component a connected (redux) component and going off of the props:

```
  componentWillReceiveProps(nextProps) {
    const wasVisible = this.props.tabBarOpen;
    const isVisible = nextProps.tabBarOpen;

    if (wasVisible && !isVisible) {
      Animated.timing(this.state.offset, { toValue: TAB_BAR_OFFSET, duration: 200 }).start();
    } else if (isVisible && !wasVisible) {
      Animated.timing(this.state.offset, { toValue: 0, duration: 150 }).start();
    }
```
then:

```
const mapStateToProps = (state) => ({
  tabBarOpen: state.admin.tabBarOpen,
});

export default connect(mapStateToProps)(TabBar);
```

Thanks for the guide!

**Comment by richardfickling** [comment]
@satya164 a recent update change to react-native-tab-view (https://github.com/react-native-community/react-native-tab-view/commit/c80fdff7bdb59b281c324bb6fb0dd1f213c1aae6) broke my workaround using an absolutely positioned tab view. Any chance we can add a way to send a style prop to the container view (or find a cleaner solution to the zIndex bug)? I'll send a PR for the style prop if that works for you

**Comment by satya164** [comment]
Hmm. I might have an idea on how to fix that. Let's see.

**Comment by hama** [comment]
@ satya164 what idea ?

**Comment by chiragpurohit71085** [comment]
Hi All

I have just used simple react-navigation and I have stacked navigation

i.e

StackNavigator
	TabNavigator -- (stack navigor - view1,view2 etc..)

Now how I can show/hide tab bar in view1, after it is rendered?

Note: I have not used tabbarview or no other packages.

Please guide me in this.

**Comment by chiragpurohit71085** [comment]
Please also let me know if there is any alternative for this....

**Comment by chiragpurohit71085** [comment]
Hi @richardfickling

your solution worked. Thanks you saved my life...

**Comment by chiragpurohit71085** [comment]
oops this.props.navigation.setParams({ visible: true/false }); is not working when I call this from inner component for example...

When we have something like

Stacknavigator
--Tabnavigator
----Stacknavigator
------Screen1(somehow works here)-->navigatates to screen-2 (not working here)

Whether I am missing anything here?

**Comment by JayricMok** [comment]
@richardfickling and @markjongkind thanks for your both suggestion and solution. I get one problem is my `indicatorStyle` not apply to the TabBar component, any idea ?

**Comment by joecaraccio** [comment]
Any updates to this?

**Comment by gamingumar** [comment]
I found a **Working Solution** around this:
in the screen you want to hide tab bar update the navigation option. the key is enabling `animationEnabled` to true and hide the tabBar using `tabBarVisible` property.
<pre>
static navigationOptions = ({navigation}) => ({
  tabBarVisible: (navigation.state.params && navigation.state.params.hideTabBar) === true,
  animationEnabled: true
)}
</pre>

make tabBar visible in `componentWillMount`.
<pre>
componentWillMount() {
    const setParamsAction = NavigationActions.setParams({
      params: {hideTabBar: true}
    });
    this.props.navigation.dispatch(setParamsAction);
}
</pre>

and in `componentWillUnmount` hide the tabBar again
<pre>
componentWillUnmount() {
    const setParamsAction = NavigationActions.setParams({
      params: {hideTabBar: false}
    });
    this.props.navigation.dispatch(setParamsAction);
}
</pre>

**Comment by brentvatne** [comment]
please re-post to https://react-navigation.canny.io/feature-requests if this is important for you. re-organizing issues to focus on bug reports here and feature requests on canny. thanks!

**Comment by Donhv** [comment]
same issue when I try show fullscreen modal?
Who can help me?

**Comment by schumannd** [comment]
@gamingumar what is `animationEnabled` for? For me it also worked by simply setting
```
class ScreenWhereTabbarIsHidden extends React.Component {
  static navigationOptions = {
    tabBarVisible: false,
  }
}
```

**Comment by gamingumar** [comment]
@schumannd the problem happens when you have a back button. which doesn't work if `animationEnabled` is not `true`

**Comment by schumannd** [comment]
I am using a custom back button like so:

```
StackNavigator({
...}, {
  navigationOptions: ({ navigation }) => ({
    headerLeft: <BackButton navigation={navigation} />,
}),
});
```

and did not encounter any problems. Can you elaborate why the option would break the back button?

**Comment by vksgautam1** [comment]
unable to find working solution out of above.

**Comment by adamawang** [comment]
I was able to get a working solution using route keys. My setup is a TabNavigator with a nested StackNavigator so YMMV. 

In TabNavigator, use whatever param you want:

    screen: NavigationCamera,
    navigationOptions: ({ navigation }) => {
      const showTabBar = navigation.state && navigation.state.routes && navigation.state.routes[0] && navigation.state.routes[0].params ? navigation.state.routes[0].params.showTabBar : true;
      return {
        tabBarLabel: 'Live',
        path: '/camera',
        tabBarIcon: ({ tintColor }) => (
          <Ionicons
            name={'ios-radio-outline'}
            size={28}
            style={{ color: tintColor, top: 2 }}
          />
        ),
        tabBarVisible: showTabBar,
      };
    },
  
In your component where you want to hide the tab bar, do your boolean check and set showTabBar with the route key: 
    
    const setParamsAction = NavigationActions.setParams({
      params: { showTabBar: false/true },
      key: this.props.navigation.state.key,
    });
    this.props.navigation.dispatch(setParamsAction);

**Comment by vksgautam1** [comment]
@adamawang i tries your solution but it did not worked

**Comment by vksgautam1** [comment]
this is my app.js page 
`import React, { Component } from 'react';
import {
  Platform,
  StyleSheet,navigationOptions,
  Text,
  View
} from 'react-native';
import Tab1 from './src/Tab1';
import Tab2 from './src/Tab2';
import Tab3 from './src/Tab3';
import Navig from './src/Navigation';
import { TabNavigator } from 'react-navigation';
import TabBar from './TabBar';

const Tabs = new TabNavigator({
  Tab1: {
    screen: Navig,
    navigationOptions: ({ navigation }) => {
      const showTabBar = navigation.state && navigation.state.routes && navigation.state.routes[0] && navigation.state.routes[0].params ? navigation.state.routes[0].params.showTabBar : true;
      tabbar=showTabBar
      console.log("showtab bar")
      console.log(tabbar)
      return {
        tabBarVisible: showTabBar,
      };
    },
  },
  
  Tab2: { screen: Tab2 },

  Tab3: { screen: Tab3 },
})
export default class App extends Component {
 

  render() {
  
    return <Tabs />;
  }

}

`

this is my other stack navigator page which is i used for tab1
`import React, { Component } from 'react';
import {
  Platform,
  StyleSheet,
  Text,
  View
} from 'react-native';
import Tab1 from './Tab1';
import Home from './Home';
import {StackNavigator} from 'react-navigation';
 const Stack = new StackNavigator({
  Tab1: { screen: Tab1,navigationOptions: ({ navigation }) => ({
    title: 'Message cool',
    tabBarVisible: false,
  })
  },
Home: { screen: Home,navigationOptions: ({ navigation }) => ({
  title: 'Message cool',
  tabBarVisible: false,
})
}
  })
export default class Navig extends Component {
  render() {
    return  <Stack /> ;
  }
}`

my tab1 page
`import React, {Component} from 'react';
import {View, Text, StyleSheet,Button,NavigationActions } from 'react-native';
export default class Tab1 extends React.Component {
//   componentWillMount() {
//     const setParamsAction = NavigationActions.setParams({
//       params: {hideTabBar: true}
//     });
//     this.props.navigation.dispatch(setParamsAction);
// }

// ComponentWillUnmount() {
//   const setParamsAction = NavigationActions.setParams({
//     params: {hideTabBar: false}
//   });
//   this.props.navigation.dispatch(setParamsAction);
// }
  render() {
    const { navigate } = this.props.navigation;
    return (
      <Button
      title="Go"
      onPress={() =>
       navigate('Home')
      }
    />
    );
  }
}
// const styles = StyleSheet.create({
//   textFirst: {
//   fontSize: 50,
//   marginTop: 300,
//   },
// });`


and final home page where i go
`import React, { Component } from 'react';
import { View, Text, StyleSheet, Image } from 'react-native';
import { TabNavigator, NavigationActions } from 'react-navigation';
export default class Home extends React.Component {
  // static navigationOptions = ({navigation}) => ({
  //   tabBarVisible: (navigation.state.params && navigation.state.params.hideTabBar) === true,
  //   animationEnabled: true
  // })
 
  constructor(props) {
    super(props)
  ///  this.props.navigation.setParams({ visible: true})
  const setParamsAction = this.props.navigation.setParams({
    params: { showTabBar: false },
    key: this.props.navigation.state.key,
    });
    this.props.navigation.dispatch(setParamsAction);
  }
  
  render() {
    const { navigate } = this.props.navigation;
    return (
      <View>
        <Text>page</Text>
        <Image source={{ uri:'https://upload.wikimedia.org/wikipedia/commons/6/6e/Wankhede_ICC_WCF.jpg' }}  style={{width: 100, height: 100}}/>
        <Image
          style={{width: 50, height: 50}}
          source={{uri: 'https://facebook.github.io/react/assets/logo_og.png'}} style={{width: 400, height: 400}}
        />
      </View>
    );
  }
}`

i am new in this one and lost all here
using 1.0.3 react navigation version

**Comment by vksgautam1** [comment]
this is my app.js page 
`import React, { Component } from 'react';
import {
  Platform,
  StyleSheet,navigationOptions,
  Text,
  View
} from 'react-native';
import Tab1 from './src/Tab1';
import Tab2 from './src/Tab2';
import Tab3 from './src/Tab3';
import Navig from './src/Navigation';
import { TabNavigator } from 'react-navigation';
import TabBar from './TabBar';

const Tabs = new TabNavigator({
  Tab1: {
    screen: Navig,
    navigationOptions: ({ navigation }) => {
      const showTabBar = navigation.state && navigation.state.routes && navigation.state.routes[0] && navigation.state.routes[0].params ? navigation.state.routes[0].params.showTabBar : true;
      tabbar=showTabBar
      console.log("showtab bar")
      console.log(tabbar)
      return {
        tabBarVisible: showTabBar,
      };
    },
  },
  
  Tab2: { screen: Tab2 },

  Tab3: { screen: Tab3 },
})
export default class App extends Component {
 

  render() {
  
    return <Tabs />;
  }

}

`

this is my other stack navigator page which is i used for tab1
`import React, { Component } from 'react';
import {
  Platform,
  StyleSheet,
  Text,
  View
} from 'react-native';
import Tab1 from './Tab1';
import Home from './Home';
import {StackNavigator} from 'react-navigation';
 const Stack = new StackNavigator({
  Tab1: { screen: Tab1,navigationOptions: ({ navigation }) => ({
    title: 'Message cool',
    tabBarVisible: false,
  })
  },
Home: { screen: Home,navigationOptions: ({ navigation }) => ({
  title: 'Message cool',
  tabBarVisible: false,
})
}
  })
export default class Navig extends Component {
  render() {
    return  <Stack /> ;
  }
}`

my tab1 page
`import React, {Component} from 'react';
import {View, Text, StyleSheet,Button,NavigationActions } from 'react-native';
export default class Tab1 extends React.Component {

  render() {
    const { navigate } = this.props.navigation;
    return (
      <Button
      title="Go"
      onPress={() =>
       navigate('Home')
      }
    />
    );
  }
}



and final home page where i go
`import React, { Component } from 'react';
import { View, Text, StyleSheet, Image } from 'react-native';
import { TabNavigator, NavigationActions } from 'react-navigation';
export default class Home extends React.Component {
 
 
  constructor(props) {
    super(props)
 
  const setParamsAction = this.props.navigation.setParams({
params: { showTabBar: true },
key: this.props.navigation.state.key,
});
this.props.navigation.dispatch(setParamsAction);
  
  render() {
    const { navigate } = this.props.navigation;
    return (
      <View>
        <Text>page</Text>
        <Image source={{ uri:'https://upload.wikimedia.org/wikipedia/commons/6/6e/Wankhede_ICC_WCF.jpg' }}  style={{width: 100, height: 100}}/>
        <Image
          style={{width: 50, height: 50}}
          source={{uri: 'https://facebook.github.io/react/assets/logo_og.png'}} style={{width: 400, height: 400}}
        />
      </View>
    );
  }
}`

i am new in this one and lost all here
using 1.0.3 react navigation version

**Comment by Aidurber** [comment]
For anyone still figuring out how to hide navigation elements dynamically.

If you're using redux, and custom headers/tab bars/whatever. 

Create a UI ducks module like: 
```typescript
export interface State {
  headerHidden: boolean;
  topTabBarHidden: boolean;
  bottomTabBarHidden: boolean;
}
```

Then in your custom header just return hull if headerHidden is true: 
```typescript
const NavBar: React.SFC<NavBarProps> = props =>
  props.headerHidden ? null : <Header {...props} />;
```

This is what we're using when we want fullscreen video in nested navigators. Hopefully it helps someone.

**Comment by SmiljanicN** [comment]
```
// Dynamically hidding - simple
// In stack navigation add default
screen: yourScreen,
navigationOptions: {
    tabBarVisible: false
}

// On component add
static navigationOptions = ({ navigation }) => ({
	title: 'Wall',
	tabBarVisible: navigation.getParam('tabBarVisible') === false ? false : true
});

// trigger
this.props.navigation.setParams({ tabBarVisible: false/true });
```

**Comment by Ronnyrr** [comment]
@SmiljanicN this doesn't work inside a StackNavigator?

**Comment by anhtukhtn** [comment]
With me, this one works

```
// In Component
navigationOptions = (navigation) => {
  const visible = (navigation.state && navigation.state.routes[0].params) ?
    navigation.state.routes[0].params.showTabBar
    : true; // default is show

  return {
    tabBarVisible: visible,
  };
};

```

Then invoke

`this.props.navigation.setParams({ showTabBar: show });`

**Comment by isaacnass** [comment]
```navigationOptions: ({ navigation }) => ({
  tabBarVisible: !navigation.state || (navigation.state.routes[navigation.state.routes.length - 1] || {}).routeName !== 'whateverroutenameyouwanttohideon'
```

**Comment by vksgautam1** [comment]
@forster-thomas 
`const setParamsAction = this.props.navigation.setParams({
      params: { showTabBar: false },
      key: this.props.navigation.state.key,
    });`

in console.log it shows true  and props shows params undefined

**Comment by toanphan0303** [comment]
@vksgautam1 
You should be careful with "navigation.state.routes[0]". The params may not at position 0 of navigation.state.routes. You can print out value of navigation.state.routes to get exact position.
In my case: navigation.state.routes[1].params.params.showTabBar

**Comment by vksgautam1** [comment]
@toanphan0303
Thanks . i am printing the data but it is not showing routes key

**Comment by michelewang** [comment]
This is a solution that worked for me! Applicable if the Tab Navigator contains Stack Navigators and the screens you want to hide are in the Stack Navigators

in the file of the stack, insert this after you have exported/created the class

```
export default DiscoverStack
const hiddenTabBars = ['AddCompanyReview', 'ApplyNow'] //these are the RouteNames of the screens you want to hide the tab bars on
DiscoverStack.navigationOptions = ({ navigation }) => {
  let tabBarVisible = true
  if (
    hiddenTabBars.includes(
      navigation.state.routes[navigation.state.index].routeName,
    )
  ) {
    tabBarVisible = false
  }
  return {
    tabBarVisible,
  }

```

**Comment by chaoliu** [comment]
@markjongkind  it works . But the tarbar will blink out，especially when you route back with the gesture . Any good ideas about this.

**Comment by tufailra97** [comment]
I have  similar situation with createBottomNavigator;
In my situation the tab bar is invisible as default.

<div data-snack-id="@tufailra97/bottom-tab-bar-always-visible" data-snack-platform="ios" data-snack-preview="true" data-snack-theme="dark" style="overflow:hidden;background:#212733;border:1px solid rgba(0,0,0,.08);border-radius:4px;height:505px;width:100%"></div>
<script async src="https://snack.expo.io/embed.js"></script>

**Comment by johanntony** [comment]
一顿操作猛如虎啊，没有一个能用的啊

**Comment by Changdao** [comment]
The solution worked well. 
You must check your router hierarchy to keep the param corresponding to the right one.
My method is to console.log the navigation in the navigationOptions function to check where is the params object, maybe they are very deep.

**Comment by munafmohammed** [comment]
<img width="296" alt="Screenshot 2020-02-04 at 1 06 37 PM" src="https://user-images.githubusercontent.com/50137781/73723489-2bbcbf80-474f-11ea-9ae3-7497675fada1.png">
@richardfickling Getting this crash on using the code suggested by you.

**Comment by IgorThierry** [comment]
@SmiljanicN thanks man!

**Comment by xilin** [comment]
If you have a navigation struction with nested stack in tab:
- Tab
  - HomeStack
     - Home
     - Detail
  - SecondStack
     - Second

You can pass tab's navigation through `screenProps` as a `rootNavigation` field, and use it later in the `Home` component to update route params.

**Comment by nomi9995** [comment]
here is a solution https://stackoverflow.com/a/62134625/8079868

**Comment by BAE86AEC1946B6AB60CCD7452DC811F0** [comment]
> @richardfickling感谢您的分享！我在为组件设置动画时遇到问题，因为它不是<Animated.View>。以下代码修复了以下问题：
> 
> ```
> render() {
>   return (
>     <Animated.View style={[styles.container, { bottom: this.state.offset }]}>
>       <TabBarBottom {...this.props} />
>     </Animated.View>
>   );
> }
> ```

in v5.0  `<Animated.View>`  Where to put it?

**Comment by nomi9995** [comment]
@BAE86AEC1946B6AB60CCD7452DC811F0  don't use Animated View because bottomtab already using animated view. hide and show like this https://github.com/react-navigation/react-navigation/issues/888#issuecomment-636950420

**Comment by JvdWest** [comment]
Another way is to use the height of the tab bar to hide it. This is required when using createMaterialTopTabNavigator, since it does not have a tabBarVisible property (from what I could find). You can use a global state variable (Redux or UseState) or you can keep track of the currently active screen, similar to the selected answer [here](https://stackoverflow.com/questions/51352081/react-navigation-how-to-hide-tabbar-from-inside-stack-navigation/64204881#64204881)

Assuming 'hideTab' is a boolean.

`const Tab = createMaterialTopTabNavigator();`
...
`<Tab.Navigator
   tabBarOptions={{style: {height: hideTab ? '0%' : null}}>`

**Comment by nguyenanhdong** [comment]
For smooth effect. I use:
In my BottomNavigator declaration:
`
const MyTabNav = createBottomTabNavigator(
  {
    Home: { Screen: HomeScreen },
    Profile: { Screen: ProfileScreen },
  },
  {
    tabBarComponent: (props) => (
            <TabBar {...props} />
          ),
  }
)
`
The Tab Bar itself:
`
import React, { Component } from 'react';
import { Animated,Easing } from 'react-native';
import { BottomTabBar } from 'react-navigation-tabs';

export default class TabBar extends Component {
  constructor(props) {
    super(props);
    this.offset =  new Animated.Value(0);
  }
  
  componentWillReceiveProps(props) {
    const oldState = this.props.navigation.state;
    const oldRoute = oldState.routes[oldState.index];
    const oldParams = oldRoute.params;
    const wasVisible = !oldParams || oldParams.visible;

    const newState = props.navigation.state;
    const newRoute = newState.routes[newState.index];
    const newParams = newRoute.params;
    const isVisible = !newParams || newParams.visible;

    if (wasVisible && !isVisible) {
      Animated.timing(this.offset, { toValue: 1, duration: 300,easing:Easing.linear(),useNativeDriver:true}).start();
    } else if (isVisible && !wasVisible) {
      Animated.timing(this.offset, { toValue: 0, duration: 300,easing:Easing.linear(),useNativeDriver:true}).start();
    }
  }

  render() {
    const bottom = this.offset.interpolate({
      inputRange: [0, 1],
      outputRange: [0,60]
    });
    return (
      <Animated.View style={[styles.container,{ translateY: bottom}]} >
        <BottomTabBar   {...this.props}/>
      </Animated.View>
    );
  }
}

const styles = {
  container: {
    overflow: 'hidden',
    position:'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: 'white',
    elevation: 8,
    zIndex:1000000,
  },
};
`

**Comment by hasanablak** [comment]
<Tab.Navigator
            screenOptions={{
                headerShown: false,
                tabBarHideOnKeyboard: true,
                showLabel: false,
                tabBarStyle: {
                    elevation: 0,
                    backgroundColor: '#F1F1F1',
                    height: 70,
                    /*display: 'none',*/ <-- you can this
                    ...styles.shadow
                },
                tabBarLabelStyle: {
                    display: 'none'
                },

            }}

        >
