### ISSUE TITLE
Button added in Stack.Navigator > screenOptions > headerRight flickers between screen changes on iOS

### ISSUE THREAD

**Issue by rexthefex** [react-navigation/react-navigation#8880]
**Current Behavior**

I'm trying to use a fixed headerRight button on all inner screens of a navigator, so I'm using the screenOptions prop on Stack.Navigator to apply it globally.
This is the barebones code that displays the issue. Making the header red to further highlight the issue:
```
<Stack.Navigator 
  screenOptions={{
    headerStyle: {backgroundColor: 'red'},
    headerRight: () => <Button title={"this button flickers"} onPress={() => {}} />,
  }}>
  <Stack.Screen name="Home" component={HomeScreen} />
  <Stack.Screen name="Home2" component={HomeScreen2} />
</Stack.Navigator>
```
Tried different preset headerStyleInterpolator or changing the mode to 'screen' - nothing solves the issue.

Managed to do a  workaround that relatively works fine using the `header` prop, a container View, add absolutely positioned button to the right and inject the header in between:

```
headerRightContainerStyle: { paddingRight: 40 },
header: (props) => {
    return (
      <>
        <Header {...props} />
        <TouchableNativeFeedback onPress={() => {}}>
          <View style={{ position: 'absolute', right: 10, bottom: 10, width: 20, height: 20, backgroundColor: 'blue' }} />
        </TouchableNativeFeedback>
      </>
    );
  },
```
It still flickers when changing screens and the background changes the hue a bit, but it is very minor.

**Expected Behavior**

The button should be consistent and shouldn't flicker when changing screens.

**How to reproduce**

https://snack.expo.io/udq5VeBt4

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | 13.7
| @react-navigation/native       | 5.7.3
| @react-navigation/stack        | 5.9.0
| react-native-gesture-handler   | 1.8.0
| react-native-safe-area-context | 3.1.8
| react-native-screens           | 2.10.1
| react-native                   | 0.63.2
| expo                           | -
| node                           |
| npm or yarn                    |

**Comment by daviddunnington** [comment]
Looks like it's part of the screen animation effect you could try disabling the animation. 

```
<Stack.Navigator 
  screenOptions={{
    headerStyle: {backgroundColor: 'red'},
    headerRight: () => <Button title={"this button flickers"} onPress={() => {}} />,
    animationEnabled: false,
  }}>
  <Stack.Screen name="Home" component={HomeScreen} />
  <Stack.Screen name="Home2" component={HomeScreen2} />
</Stack.Navigator>
```

**Comment by satya164** [comment]
The headers cross-fade by default. You can set `headerMode` to `screen` or customize the animation (e.g. override `rightButtonStyle`) by specifying a `headerStyleInterpolator` option https://reactnavigation.org/docs/stack-navigator#animation-related-options
