### ISSUE TITLE
Issue with Drawer Navigation ..

### ISSUE THREAD

**Issue by ramkgunturu** [react-navigation/react-navigation#8883]
ERROR   Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'NativeReanimated' could not be found. Verify that a module by this name is registered in the native binary.
ERROR   Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)
ERROR   Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)

Version ---
 "@react-navigation/drawer": "^5.9.0",
    "@react-navigation/native": "^5.7.3",
    "react": "16.13.1",
    "react-native": "0.63.2",
    "react-native-gesture-handler": "^1.8.0",
    "react-native-reanimated": "^1.13.0",

I am facing this issue from today morning..

**Comment by ramkgunturu** [comment]
"@react-navigation/drawer": "^5.9.0",
    "@react-navigation/native": "^5.7.3",
    "react": "16.13.1",
    "react-native": "0.63.2",
    "react-native-gesture-handler": "^1.8.0",
    "react-native-reanimated": "^1.13.0",

**Comment by satya164** [comment]
Closing since you didn't follow the issue template.
