### ISSUE TITLE
navigation.reset does not work when the Login flow is used

### ISSUE THREAD

**Issue by heroic** [react-navigation/react-navigation#8885]
**Current Behavior**

I am following the Login guide. My screens have an access management hook, which decides if that screen can be shown or not.

We `switch` from Login stack to `Member` stack. The first screen in `Member` stack, `Home`, should switch to another screen for a user who is still on the onboarding flow. This is breaking right now. We are doing `navigation.reset` in the `Home` Screen. This does not work. However, if we wrap this in a `setTimeout`, like `setTimeout(() => navigation.reset({index: 0, routes: [name: 'Second']}), 100)` then it works.

**Expected Behavior**

`navigation.reset` should work without `setTimeout`.

**How to reproduce**

Here is a small app that shows the issue: https://github.com/heroic/react-navigation-bug

The issue does not happen if the `Login` stack is removed, that is in `App.js` if we remove the check for `user === undefined`

The issue also does not happen if we change `navigation.reset` in useUserStatus.js to `setTimeout(() => navigation.reset({index: 0, routes: [name: 'Second']}), 100)`

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Android
| @react-navigation/native       | 5.7.3
| react-native                   | 0.63.2
| expo                           |
| node                           |   v12.18.3
| npm or yarn                    | yarn v1.22.5

**Comment by satya164** [comment]
Each navigation/swicthing screen causes a state update. State updates in React are asynchronous, so you can't assume that your previous action was completed synchronously. Instead of timeout, you can use `useNavigationState()` inside a screen or `onStateChange` on the container to observe when the state change happens and then perform the action you want.
