### ISSUE TITLE
Cannot navigate on app startup

### ISSUE THREAD

**Issue by Cerealkillerway** [react-navigation/react-navigation#8891]
**Current Behavior**

    const RootStack = createStackNavigator();

    <RootStack.Navigator>
      <RootStack.Screen name="Main" component={Main} />
      <RootStack.Screen name="B" component={B} />
      <RootStack.Screen name="C" component={C} />
    </RootStack.Navigator>

in `Main` component I am simply doing

    useEffect(() => {
      if (shouldRedirect)
        console.log('here')
        navigation.navigate('C')
      }
    }, [shouldRedirect])

Well at this point I can see the log in the console but the navigation it's not happening;
I guess it's due to the fact that something is not ready yet, because just wrapping the `navigate` in a timeout like the following, makes it work as expected:

    useEffect(() => {
      if (shouldRedirect) {
        setTimeout(() => {
          navigation.navigate('C')
        }, 1)
      }
    }, [shouldRedirect])

**Expected Behavior**

when Main renders it navigates to "C"

**Version**

"@react-navigation/native": "5.7.4",

**Comment by heroic** [comment]
Looks like the issue, I'm facing: https://github.com/react-navigation/react-navigation/issues/8885

**Comment by satya164** [comment]
Like you said, something isn't ready yet. Your app actually needs to finish rendering before you can navigate.

https://reactnavigation.org/docs/navigation-container#onready
