### ISSUE TITLE
TabActions.jumpTo doesn't pass params to destination screen's route.params 

### ISSUE THREAD

**Issue by rarenatoe** [react-navigation/react-navigation#8893]
**Current Behavior**

I have a Tab Navigator which has a stack navigator in each tab. It's jumping to the other tab, but not passing the params specified. I just passes `undefined` for params.

It's possible that it is passing the values to the stack navigator "screen" instead of the `initialRouteName` screen, thus resulting in `undefined` when the actual screen (within the stack) is displayed.

**Expected Behavior**

I need it to to pass the params.

**How to reproduce**

1. Create a tab navigator.
2. Add stack navigators to each tab.
3. Add screens to each stack.
4. Write the following from any screen not in `StackB`:
`navigation.dispatch(TabActions.('StackB', { 'test': 'this won't show up'}));`

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Android
| @react-navigation/native       | 5.7.4
| react-native                   | 0.62.2
| expo                           | Nay
| node                           | 14.3
| npm or yarn                    | 1.22.5

**Comment by satya164** [comment]
https://reactnavigation.org/docs/nesting-navigators
