### ISSUE TITLE
Cannot style tab bar container's parent.

### ISSUE THREAD

**Issue by FrancisLeigh** [react-navigation/react-navigation#8902]
**Current Behavior**
I am building a bottom tab navigator with react-navigation. As you can see in the screen shot i have a `borderTopLeftRadius` & `borderTopRightRadius` being applied to my Tab container via `tabBarOptions.tabStyle` but behind the tab bar itself is a grey background so it's not clear that my tab bar container is in fact curved.

Is there a way to change the background of the container *containing* my tab bar ?

```javascript
function RootNavigator() {
  return (
    <NavigationContainer linking={deeplinkConfig} fallback={<Loading />}>
      <Stack.Navigator initialRouteName={routeConfig.mainApp}>
        <Stack.Screen name={routeConfig.mainApp} component={AppNavigator} />
      </Stack.Navigator>
    </NavigationContainer>
  );
}
```
```javascript
const Tab = createBottomTabNavigator();
export function CustomTabNavigator({tabBarOptions = {}, ...props}) {
  return (
    <Tab.Navigator
      {...props}
      tabBarOptions={{
        activeTintColor: 'tomato',
        inactiveTintColor: 'gray',
        labelStyle: [styles.labelStyle],
        tabStyle: [styles.tabContainer],
        style: [styles.tabBarContainer],
        ...tabBarOptions,
      }}
    />
  );
}
export const CustomTabScreen = Tab.Screen;

const styles = StyleSheet.create({
  tabBarContainer: {
    backgroundColor: '#f4f4f4',
    marginBottom: 15,
    borderWidth: 1,
    borderBottomWidth: 0,
    borderColor: '#D5D5D5',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
  },
  tabContainer: {
    height: 55
  },
  labelStyle: {
    fontSize: 12,
  }
});
```
<img width="394" alt="Screenshot 2020-09-24 at 16 38 36" src="https://user-images.githubusercontent.com/10357801/94242878-92753000-ff0e-11ea-8c27-53e30926851c.png">

**Expected Behavior**
I should be able to clearly see the difference between by tab bar container and it's parent.
The parent of the tab bar container should have `backgroundColor: '#fff'` whilst the tab bar itself should remain `#f4f4f4` 

**How to reproduce**
Use code provided (with mock scenes)

**Your Environment**

| software                      | version |
| ----------------------------- | ------- |
| iOS or Android                | both
| @react-navigation/native      | ^5.7.4
| @react-navigation/bottom-tabs | ^5.9.0
| react-native-screens          | ^2.11.0
| react-native                  | 0.63.2
| expo                          | no
| node                          | yes
| npm or yarn                   | yarn

**Comment by satya164** [comment]
Position your tab bar absolutely.

**Comment by oscar-gallog** [comment]
Position the tab bar absolutely is the stupidest idea I have ever read. If you do that now you need to add padding at the bottom of every view in order to show all the content.
Is that really the only way?

**Comment by FrancisLeigh** [comment]
@oscar-gallog 😂 I agree, that can't be the fix...

**Comment by satya164** [comment]
How do you expect content to appear under the area where the tab bar is if you don't position it absolutely?

**Comment by tchayen** [comment]
> If you do that now you need to add padding at the bottom of every view in order to show all the content.

Yes, that's exactly how it always works with any kind of `position: absolute`. I don't know what problem do you have in adding a padding.

@oscar-gallog your lack of understanding in the topic is not an excuse for offending maintainers. If you think people will gladly help you after you insult them then better not comment at all.

**Comment by FrancisLeigh** [comment]
@satya164 I appreciate your reply. It's only that positioning the tab bar absolute seems like a change that would impact an App that is already released and has multiple screens etc. The impact would be having to change all the screens affected by the absolute positioning by adding padding etc. 

Luckily for me i am starting bare bones on a project but am reluctant to go the position absolute route. 

From what i understand, React navigation (in this scenario) has three containing elements. 
- a top block (for the header)
- a middle block (for the page content)
- a bottom block (for the tab bar)
If i'm completely off please let me know but i'm just thinking if the layout is how i say it might be, it would be *great* if we were able to change the BG Color of the blocks.

**Comment by truongduy997** [comment]
I have done it successfully !!!!!!!!!

<img width="919" alt="Screen Shot 2020-10-22 at 1 27 56 PM" src="https://user-images.githubusercontent.com/43513612/96833304-66e05980-146a-11eb-8387-4dcce799ba33.png">
![simulator_screenshot_69877B3C-210F-49B2-A676-722646033F11](https://user-images.githubusercontent.com/43513612/96833315-6b0c7700-146a-11eb-9a37-ab0fc605095d.png)

**Comment by enzzoperez** [comment]
@truongduy997 do you have the code of that to share? I need to do something like that but in ios i cant show the shadow :/

**Comment by mgefimov** [comment]
I have done it using the `contentStyle` property of the parent `Navigator`

<img width="356" alt="Screen Shot 2023-03-15 at 00 27 43" src="https://user-images.githubusercontent.com/13413154/225102664-ab28723b-019f-4333-bcb4-c2a64c9d7880.png">

Before: 
![IMG_6454](https://user-images.githubusercontent.com/13413154/225103987-00c8fea3-0c91-4c56-930a-870069261e19.jpg)

After:
![IMG_AF2807F2C76D-1](https://user-images.githubusercontent.com/13413154/225104018-11a51867-19cf-4a76-89df-e8b42c1804a8.jpeg)
