### ISSUE TITLE
Issue with navbar back button and android hardware back button (different behavior) in nested navigators

### ISSUE THREAD

**Issue by TntManiak** [react-navigation/react-navigation#8905]
**Current Behavior**

Here is my stack structure:

- StackNavigatorA
  - ScreenA1
  - ScreenA2
  - StackNavigatorB
    - ScreenB1
    - ScreenB2

And the navigation flow:
ScreenA1 -> navigate('ScreenA2") -> navigate('NavigatorB"(="ScreenB1")) -> navigate('ScreenB2") -> Hit navigation bar back button.

Two behaviors observed:

- Hitting navigation bar back button: the app go back to "ScreenA2"
- Hitting android hardware back button: the app go back to "ScreenB1"

**Expected Behavior**

The app should go back to "ScreenB1".

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| @react-navigation/native       | 5.7.4
| @react-navigation/stack        | 5.9.1

**Comment by TntManiak** [comment]
After updating :
- @react-navigation/native (found: 5.7.2, latest: 5.7.4)
- @react-navigation/stack (found: 5.8.0, latest: 5.9.1)

Still the issue.

**Comment by TntManiak** [comment]
I reproduced the issue on a fresh new project containing only basic screen & navigation. Project can be found here:
https://github.com/TntManiak/stacknavigator-issue-8905

**Comment by satya164** [comment]
https://reactnavigation.org/docs/nesting-navigators#nesting-multiple-stack-navigators
https://reactnavigation.org/docs/nesting-navigators#best-practices-when-nesting
