### ISSUE TITLE
headerMode="screen" is not working as expected

### ISSUE THREAD

**Issue by hackrx** [react-navigation/react-navigation#8908]
**Current Behavior**

-As suggested in react-navigation docs [link](https://reactnavigation.org/docs/stack-navigator/#set-headermode-to-screen) by setting header mode to "screen" and with custom header, we don't need to animate the header with scroll.
So the expected outcome is: Header should scroll up with scrolling (with animation) but it is not working.
The header is fixed at the top 

**How to reproduce**
I am using `@react-navigation/material-bottom-tabs`  and stack navigator as a child of each bottom tab.
Now in each stack navigator, I want to scroll up the header when the user scrolls up the screen

## index.js
```
import {createMaterialBottomTabNavigator} from '@react-navigation/material-bottom-tabs';
const Tab = createMaterialBottomTabNavigator();

export default class App extends Component{
render(){

return(
 <Tab.Navigator
      initialRouteName="HomeTab"
      keyboardHidesNavigationBar={true}
      shifting={false}
    >
      <Tab.Screen
        name="HomeTab" 
        component={HomeStackScreen}
        options={{
          tabBarLabel: null,
          tabBarIcon: ({color}) => (
            <View style={{width: 40}}>
              <Octicons
                name="home"
                color={color}  
                size={30}
              />
            </View>
          ),
        }}
      />
)

}
}

const HomeStackScreen =  ({navigation}) => {
  return (
    <HomeStack.Navigator
      initialRouteName="Home"
      headerMode="screen"               //<-----------------------------
      screenOptions={{
        
        header: ({scene, previous, navigation}) => {
        
          const {options} = scene.descriptor;
        
          const title =
            options.headerTitle !== undefined
              ? options.headerTitle
              : options.title !== undefined
              ? options.title
              : scene.route.name;

          return <HeaderHome title={title} style={options.headerStyle} />;
        },
      }}>
      <HomeStack.Screen
        name="Home"
        component={Home}
        options={{
          headerTitleAlign: 'center',
          headerTitle: 'Home',
     
          
        }}
      />

```
## HeaderHome.js
```
import React from 'react';
import {View, Text} from 'react-native';

export default function HeaderHome({title, onPress, style}) {
  return (
    <View
      style={{
        height: 30,
        backgroundColor: 'yellow',
        justifyContent: 'center',
        alignItems: 'center',
      }}>
      <Text style={{textAlign: 'center', fontSize: 20}}>{title}</Text>
    </View>
  );
}

```

 
**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Android
| @react-navigation/native       | 5.7.0
| @react-navigation/stack        | 5.7.0
| react-native-gesture-handler   | 1.6.1
| react-native-safe-area-context | 3.1.1
| react-native-screens           | 2.9.0
| react-native                   | 0.63.0
| expo                           |
| node                           |
| npm or yarn                    |

**Comment by hackrx** [comment]
> The versions mentioned in the issue for the following packages differ from the latest versions on npm:
> 
> * `@react-navigation/native` (found: `5.7.0`, latest: `5.7.4`)
> * `@react-navigation/stack` (found: `5.7.0`, latest: `5.9.1`)
> 
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?

Yes, still I am facing issue after upgrading the packages.
Here is Home.js which I am rendering within the navigator

## Home.js
```
 
import React from 'react';
import {View, Text} from 'react-native';
import {ScrollView} from 'react-native-gesture-handler';

export default function TestScreen() {
  return (
    // <View style={{flex: 1}}>
    <ScrollView>
      <Text>Hii this is a test screen</Text>   //<----------------------------------
      <View style={{width: '100%', height: 250, backgroundColor: 'black'}} />
      <View style={{width: '100%', height: 250, backgroundColor: 'orange'}} />
      <View style={{width: '100%', height: 250, backgroundColor: 'pink'}} />
      <View style={{width: '100%', height: 250, backgroundColor: 'yellow'}} />
      <View style={{width: '100%', height: 250, backgroundColor: 'blue'}} />
      <View style={{width: '100%', height: 250, backgroundColor: '#3428'}} />
    </ScrollView>
    // </View>
  );
}

```
![image](https://user-images.githubusercontent.com/54453778/94363039-08c78d00-00dd-11eb-9620-870aa2f66691.png)
As you can see `"Hii this is a test screen"` is scrolled up but the header still sticks to the top.
Please suggest something if I am doing it wrong.

**Comment by satya164** [comment]
> As suggested in react-navigation docs link by setting header mode to "screen" and with custom header, we don't need to animate the header with scroll

Nowhere it's mentioned that you don't need to animate header on scroll. The docs mention screen animations, not scroll animation.

**Comment by KoolP** [comment]
Does this mean @satya164 that 'hide header on scroll' must be animated with a custom animation such as with Animated from React Native?
