### ISSUE TITLE
Swipe back from middle of screen

### ISSUE THREAD

**Issue by lorensr** [react-navigation/react-navigation#8909]
**Current Behavior**

When I swipe from the middle of the screen to the right, nothing happens. When I swipe from the left side of the screen, I'm taken to the previous page.

**Expected Behavior**

On iOS, I'm used to being able to go back by swiping from the middle of the screen.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | iOS |
| @react-navigation/native       |  5.7.4 |
| @react-navigation/stack        | 5.9.1 |
| expo                           | 39.02 |

**Comment by satya164** [comment]
https://reactnavigation.org/docs/stack-navigator#gestureresponsedistance

**Comment by lorensr** [comment]
That worked, thank you! Perhaps it should have a larger default than 50?
