### ISSUE TITLE
useThenable doesn't always resolve

### ISSUE THREAD

**Issue by b4stien** [react-navigation/react-navigation#8910]
**Current Behavior**

`useThenable` does not always resolve.

**Expected Behavior**

`useThenable` would always "resolve", ie returns with `[true, value]` once the given promise has resolved.

**How to reproduce**

I encountered this problem trying to test an app with jest, with a "simple" test:

```
it("renders the login screen", async () => {
  let testRenderer;
  await act(async () => {
    testRenderer = create(<App />);
    await new Promise((resolve) => {
      setTimeout(resolve, 1000);
    });
  });

  // It does not work for now, because of: https://github.com/react-navigation/react-navigation/pull/8798
  expect(testRenderer.toJSON()).toMatchSnapshot();
}, 15000);
```

With App being:

```
const App = () => (
  <NavigationContainer
    theme={CustomTheme}
    linking={{
      prefixes: [Linking.makeUrl("/")],
      config: {
        screens: {
          Fake: "path",
        },
      },
    }}
  >
    <View>
      <Text>Foo</Text>
    </View>
  </NavigationContainer>
);
```

The detailled cause of this issue and a possible resolution is in https://github.com/react-navigation/react-navigation/pull/8798.

**Env**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | both
| @react-navigation/native       | 5.7.4
| expo                           | 39.0.3

**Comment by satya164** [comment]
> What happens is what @jiwansvmx described, with:
>
> 1. Our `resolved` flag is initialized to `false` and `state.resolved` will be initialized as false as well because `promise` (https://github.com/react-navigation/react-navigation/blob/main/packages/native/src/useThenable.tsx#L10) has not been resolved yet
> 2. Our `promise` resolve, setting our `resolved` flag to `true`
> 3. The effect executes for the first time, bypassing the call to `setState` because our `resolved` flag is already set to `true`

It doesn't matter whether promise resolves setting `resolved` value to `true` later asynchronously. By that time the component has already rendered and the effect has been scheduled. The values captured in `useEffect` reflect the time when the effect was run (e.g. during the component's render, which is synchronous).

Your code doesn't work for the simple reason that after the effect runs and `setState` is called, it triggers a re-render. However, `testRenderer` has the value of when you rendered it initially. So you need to make sure the result also updates by calling `testRenderer.update`:

```js
it("renders the login screen", async () => {
  const App = () => (
    <NavigationContainer
      linking={{
        prefixes: [Linking.makeUrl("/")],
        config: {
          screens: {
            Fake: 'path',
          },
        },
      }}
    >
      <View>
        <Text>Foo</Text>
      </View>
    </NavigationContainer>
  );

  let testRenderer;

  act(() => {
    testRenderer = create(<App />);
  });

  await act(async () => {
    await new Promise((resolve) => {
      setTimeout(resolve, 1000);
    });

    testRenderer.update(<App />);
  });

  expect(testRenderer.toJSON()).toMatchInlineSnapshot(`null`);
});
```

**Comment by b4stien** [comment]
Could you take a look at https://stackblitz.com/edit/react-ts-mpbnry?file=index.tsx ? It never re-renders with `resolved === true` and is a demo of the problem we highlight.

If you play with `TIMEOUT` you'll see it starts render around 20ms (depending on your computer I guess).

**Comment by satya164** [comment]
You're right, there is a bug in the effect. It should check the `resolved` value in state instead of the variable. I'll send a PR to fix it.
