### ISSUE TITLE
issue with app exiting on wrong screen

### ISSUE THREAD

**Issue by aselcuk** [react-navigation/react-navigation#8911]
**Current Behavior**

- The first screen that opens is the home screen, I go to the settings screen through the tabbar and come back to the home screen through the tabbar. Then, while on the home screen, I press the android back button and go to the settings screen. When I press the android back button again, the application quits
- 
![rn](https://user-images.githubusercontent.com/41209531/94375683-29fc9d80-011e-11eb-80af-01785012703b.gif)

**Expected Behavior**

- I am waiting for the application to exit when I press the android back button while on the home screen.

**Code Sample**

    const HomeStack = createStackNavigator();

    function HomeStackScreen() {
        return (
            <HomeStack.Navigator>
                <HomeStack.Screen name="Home" component={Home} />
                <HomeStack.Screen name="Detail" component={Detail} />
            </HomeStack.Navigator>
        );
    }

    const SettingsStack = createStackNavigator();

    function SettingsStackScreen() {
        return (
            <SettingsStack.Navigator>
                <SettingsStack.Screen name="Settings" component={Settings} />
                <SettingsStack.Screen name="Profile" component={Profile} />
            </SettingsStack.Navigator>
        );
    }

    const Tab = createBottomTabNavigator();

    function MainTabs() {
        return (
            <Tab.Navigator>
                <Tab.Screen name="Home" component={HomeStackScreen} />
                <Tab.Screen name="Settings" component={SettingsStackScreen} />
            </Tab.Navigator>
        )
    }

    const RootStack = createStackNavigator();

    return (
        <NavigationContainer>
            <RootStack.Navigator>
                <RootStack.Screen name="Main" component={MainTabs} />
            </RootStack.Navigator>
        </NavigationContainer>
    );

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |Android
| @react-navigation/native       |^5.7.4
| @react-navigation/stack        |^5.9.1
| @react-navigation/bottom-tabs       |^5.9.0
| react-native-gesture-handler   |^1.8.0
| react-native-safe-area-context |^3.1.8
| react-native-screens           |^2.11.0
| react-native                   |0.63.2
| expo                           |
| node                           |v12.18.3
| npm or yarn                    |npm

**Comment by FlawaCLV** [comment]
Hi @aselcuk, I have the same issue. How did you solved it?
