### ISSUE TITLE
In Huawei phones, the style of the last page is carried to the next page to cause style confusion

### ISSUE THREAD

**Issue by caijiami** [react-navigation/react-navigation#8912]
In Huawei phones, the style of the last page is carried to the next page to cause style confusion

version |
| ------------------------------ | ------- |
 Android 
  "react": "16.11.0",
  "react-native": "0.62.0",
  "react-navigation": "^3.3.2",
  "react-navigation-stack": "^1.4.0",
  "react-native-gesture-handler": "^1.6.1",
  "react-native-screens": "^2.9.0",

![1601259950(1)](https://user-images.githubusercontent.com/45455521/94384374-087ad080-0175-11eb-8765-e771534e566f.jpg)

expectation：
![1601260033(1)](https://user-images.githubusercontent.com/45455521/94384459-3233f780-0175-11eb-86fa-bd54664e46ac.jpg)

**Comment by caijiami** [comment]
"@react-navigation/native" "~3.6.2"

**Comment by caijiami** [comment]
> 在问题中找不到以下软件包的版本号：
> 
> * "@react-navigation/native" "3.6.2"
> 
> 您可以更新此问题以包括这些软件包的版本号吗？版本号必须与格式1.2.3匹配。

**Comment by BAE86AEC1946B6AB60CCD7452DC811F0** [comment]
> In Huawei phones, the style of the last page is carried to the next page to cause style confusion
> 
> version |
> | ------------------------------ | ------- |
> Android
> "react": "16.11.0",
> "react-native": "0.62.0",
> "react-navigation": "^3.3.2",
> "react-navigation-stack": "^1.4.0",
> "react-native-gesture-handler": "^1.6.1",
> "react-native-screens": "^2.9.0",
> 
> ![1601259950(1)](https://user-images.githubusercontent.com/45455521/94384374-087ad080-0175-11eb-8765-e771534e566f.jpg)
> 
> expectation：
> ![1601260033(1)](https://user-images.githubusercontent.com/45455521/94384459-3233f780-0175-11eb-86fa-bd54664e46ac.jpg)

请问解决了吗？ 遇到一样的问题。其他手机正常

**Comment by caijiami** [comment]
并没有解决，而且导航栏的文字都带到了下个页面

**Comment by caijiami** [comment]
@jeanregisser @szaboat @ddedic @BAE86AEC1946B6AB60CCD7452DC811F0

**Comment by BAE86AEC1946B6AB60CCD7452DC811F0** [comment]
> 并没有解决，而且导航栏的文字都带到了下个页面

你什么型号的 我华为mate 30 会出现 部分华为不会出现

**Comment by caijiami** [comment]
一样mate30

**Comment by shunzife** [comment]
我也出现过这样的问题，改了下面的设置，问题得到解决
` defaultNavigationOptions: {
      cardStyle: {
        elevation: 1, 
      },
    },`

**Comment by caijiami** [comment]
![image](https://user-images.githubusercontent.com/45455521/96538638-9016b380-12cb-11eb-9e7f-6386d9b2dcf3.png)
是写在这里吗

> 我也出现过这样的问题，改了下面的设置，问题得到解决
> ` defaultNavigationOptions: { cardStyle: { elevation: 1, }, },`

**Comment by lzy110223** [comment]
> ![image](https://user-images.githubusercontent.com/45455521/96538638-9016b380-12cb-11eb-9e7f-6386d9b2dcf3.png)
> 是写在这里吗
> 
> > 我也出现过这样的问题，改了下面的设置，问题得到解决
> > ` defaultNavigationOptions: { cardStyle: { elevation: 1, }, },`

![image](https://user-images.githubusercontent.com/38574031/96544821-decb4a00-12d9-11eb-9fcd-621f39cf0dc1.png)

**Comment by caijiami** [comment]
This certainly cannot copy ah, on the general skip page, a small part of the page will have style problems, in Huawei MATe30 above @satya164

**Comment by A-ANing** [comment]
#8368 
Hi, I have encountered similar problems. It is also a Huawei mobile phone. Moreover, the buttons at the bottom of the mobile phone are related to "swipper". I am not sure about the details.

**Comment by Andriiklymiuk** [comment]
do we have any solution for this one? 
 "@react-navigation/native": "^5.7.6",
