### ISSUE TITLE
tabPress not assignable as Listener on Screen

### ISSUE THREAD

**Issue by Sub-Zero-1** [react-navigation/react-navigation#8918]
Hello,

I need to trigger some functions on tabPress, so I try to add it as a listener to a specific screen within my navigator like documented here: https://reactnavigation.org/docs/navigation-events/#listeners-prop-on-screen

```
<Tabs.Screen
  name="Chat"
  component={Chat}
  listeners={{
    tabPress: e => {
      // Prevent default action
      e.preventDefault();
    },
  }}
/>
```
It does not recognize tabPress and tells me that it is not assignable. What is wrong?

The error: 

`Type '({ navigation, route }: { route: RouteProp<Record<string, object | undefined>, "BlogScreen">; navigation: any; }) => { tabPress: (e: any) => void; }' is not assignable to type 'Partial<{ appear: EventListenerCallback<NativeStackNavigationEventMap, "appear">; dismiss: EventListenerCallback<NativeStackNavigationEventMap, "dismiss">; focus: EventListenerCallback<...>; blur: EventListenerCallback<...>; state: EventListenerCallback<...>; beforeRemove: EventListenerCallback<...>; }> | ((props: {...'.
  Type '({ navigation, route }: { route: RouteProp<Record<string, object | undefined>, "BlogScreen">; navigation: any; }) => { tabPress: (e: any) => void; }' is not assignable to type '(props: { route: RouteProp<Record<string, object | undefined>, "BlogScreen">; navigation: any; }) => Partial<{ appear: EventListenerCallback<NativeStackNavigationEventMap, "appear">; ... 4 more ...; beforeRemove: EventListenerCallback<...>; }>'.
    Type '{ tabPress: (e: any) => void; }' has no properties in common with type 'Partial<{ appear: EventListenerCallback<NativeStackNavigationEventMap, "appear">; dismiss: EventListenerCallback<NativeStackNavigationEventMap, "dismiss">; focus: EventListenerCallback<...>; blur: EventListenerCallback<...>; state: EventListenerCallback<...>; beforeRemove: EventListenerCallback<...>; }>'.ts(2322)`

I want to scrollToTop if it is the current screen and tabPress is triggered. It works while doing the following in my class components.

```
export default function (props: any) {
	const ref = React.useRef(null)
	useScrollToTop(ref)
	return <WelcomeScreen {...props} scrollRef={ref} />
}
```

I need to trigger a specific function within my class component which also changes a state of the class component. I have not found a possiblity to trigger a class function within the `export default function (props: any) {...}` as I can not access it. That is why I tried to add the tabPress listener like above, which is not working.

Version: "react-navigation": "4.4.1"
	     "@react-navigation/native": "5.7.5"

**Comment by Sub-Zero-1** [comment]
> The versions mentioned in the issue for the following packages differ from the latest versions on npm:
> 
> * `@react-navigation/native` (found: `5.7.2`, latest: `5.7.5`)
> 
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?

Changed to 5.75 and it still does not work.

**Comment by satya164** [comment]
From the error, looks like you're adding the listener on native stack screen and not tab screen.
