### ISSUE TITLE
[Question] Why iOS removes 4 from bottom inset?

### ISSUE THREAD

**Issue by sidferreira** [react-navigation/react-navigation#8919]
I'm sorry if the issue title sounds rude, it's not my intention by any means.

I had some hard time because of the bottom tabs and I just want to understand the workaround I had to add to my project.

As you see below, if the device is `iOS`, it will remove `4` "px" from the bottom inset. Now, I just can't understand why exactly this happens. Can someone help me to understand?

https://github.com/react-navigation/react-navigation/blob/e523138321c0a8f530d43e07d8b5119c38113341/packages/bottom-tabs/src/views/BottomTabBar.tsx#L180

**Comment by satya164** [comment]
To match how default tab bar looks on iOS.
