### ISSUE TITLE
Navigation Drawer: background not settable inline

### ISSUE THREAD

**Issue by JaapWeijland** [react-navigation/react-navigation#8924]
https://github.com/react-navigation/react-navigation/blob/9e3650831c22b47130d2b388390f7eb7910fe91d/packages/drawer/src/views/DrawerView.tsx#L199

I needed the background of my `Drawer.Navigator` to be transparent. Unfortunately, this is not possible to do with the `sceneContainerStyle` prop, since the source code overwrites the `backgroundColor: 'transparent'` styling property to the backgroundColor that is supplied by the theme (see reference to the source code). 

Strange, since I think that setting a background through the `sceneContainerStyle` prop is more "specialised" than setting the background with the theme. Special cases should override general cases when it comes to styling, imho. I think this is a little design flaw. Should this be fixed? I am not familiar with pull-requesting, however it seems a very small fix to take into account.

**Comment by satya164** [comment]
Items later in the styles array override previous one so I don't see how `sceneContainerStyle` is overriden when it's the last item.
