### ISSUE TITLE
Dark Theme always enable when default system theme is dark

### ISSUE THREAD

**Issue by joaovbibiano** [react-navigation/react-navigation#8928]
**Current Behavior**

I can't DISABLE dark theme, even passing `dark: false`

- What code are you running and what is happening?
- Include a screenshot or video if it makes sense.

I Defined my own theme like that

```
export const DefaultTheme = {
  ...NavigationTheme,
  colors: {
    ...NavigationTheme.colors,
    ...Colors,
  },
  dark: false,
};
```

Color scheme as 

```
export default {
  primary: '#000000',
  background: '#F2F2F2', 
  card: '#fff', 
  text: '#000', 
  border: '#000',
  secondary: '#278CEA',
  textButton: '#fff',
  grey: '#C4C4C4',
  lightGrey: '#DCDCDC',
  greyDarker: '#5d5d5d',
  lightGreen: '#10CB00',
  scheduleCalendar: '#50cebb50',
  red: '#EA2727',
};
```

And import it on my Navigation container

```
import { DefaultTheme } from 'theme/index';

<NavigationContainer
      theme={DefaultTheme}
    >
// ....
```

On my Xioami MI 9, for example, even forcing background to white, I always got a black theme

<img src="https://user-images.githubusercontent.com/29175815/95065303-c7e10100-06f8-11eb-9666-bd98a3130e5c.jpg" width="30%">

**Expected Behavior**

<img src="https://user-images.githubusercontent.com/29175815/95065258-b4359a80-06f8-11eb-9994-cfc5c8f3fbbd.jpg" width="30%">

- What do you expect should be happening?
- Include a screenshot or video if it makes sense.

In this moment I don't want a dark theme

**How to reproduce**

Just try run React Navigation with `dark:false` in a smartphone with Global Dark Scheme enabled

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |10 - MIUI 12.0.2
| @react-navigation/native       |5.7.5
| @react-navigation/stack        |5.9.2
| react-native-gesture-handler   |1.6.0
| react-native-safe-area-context |3.0.7
| react-native-screens           |2.9.0
| react-native                   |38.0.2
| expo                           |38.0.0
| node                           |14.4.0
| npm or yarn                    |1.22.5

**Comment by joaovbibiano** [comment]
> The versions mentioned in the issue for the following packages differ from the latest versions on npm:
> 
> * `@react-navigation/stack` (found: `5.2.11`, latest: `5.9.2`)
> 
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?

I just update... having the same problem 5.9.2

**Comment by satya164** [comment]
Closing since no repro is provided.

**Comment by luongthanhtung9** [comment]
I also had the same problem

**Comment by duartedanilo** [comment]
I had the same problem. If your dark mode is activated, MIUI 12 forces the app to activate the dark theme too. You have to go to Display > More Dark mode options > Individual apps, look for your app on the list, and switch off the dark theme

**Comment by mcAnastasiou** [comment]
I have the same issue too. I have activated the dark mode in MIUI 12. The strange thing is that this doesn't happen on debug mode. Only in release

**Comment by mcAnastasiou** [comment]
I found the solution on this

Add this on res/values/styles.xml


        <item name="android:forceDarkAllowed">false</item>
