### ISSUE TITLE
useThenable Text strings must be rendered with a <Text> component.

### ISSUE THREAD

**Issue by jvfalco1** [react-navigation/react-navigation#8932]
Current Behavior

useThenable returns "Text strings must be rendered within a <Text> Component in useThenable.tsx".
Only on iOS.

Expected Behavior
 --
How to reproduce

I encountered this problem trying to run on ios "yarn ios".

`
import * as React from 'react';

export default function useThenable<T>(create: () => PromiseLike<T>) {
  const [promise] = React.useState(create);

  // Check if our thenable is synchronous
  let resolved = false;
  let value: T | undefined;

  promise.then((result) => {
    resolved = true;
    value = result;
  });

  const [state, setState] = React.useState<[boolean, T | undefined]>([
    resolved,
    value,
  ]);

  React.useEffect(() => {
    let cancelled = false;

    const resolve = async () => {
      let result;

      try {
        result = await promise;
      } finally {
        if (!cancelled) {
          setState([true, result]);
        }
      }
    }

    if (!resolved) {
      resolve();
    }

    return () => {
      cancelled = true;
    };
  }, [promise, resolved]);

  return state;
}
`
software | version
-- | --
iOS or Android | both
@react-navigation/native | 5.7.4
expo

**Comment by jvfalco1** [comment]
> The versions mentioned in the issue for the following packages differ from the latest versions on npm:
> 
> * `@react-navigation/native` (found: `5.7.4`, latest: `5.7.5`)
> 
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?

Already updated to 5.7.5 still getting the same error.

![Captura de Tela 2020-10-05 às 14 26 45](https://user-images.githubusercontent.com/39075106/95112047-ccb4ad80-0716-11eb-97d6-555aadf272ab.png)

**Comment by jpca999** [comment]
Whats the solution to this bug ?

**Comment by satya164** [comment]
Closing due to lack of repro.

**Comment by kfaria** [comment]
Not sure if anyone is having issues with this, but I traced this down to me trying to use a <form> tag in my render function of code.  Renders fine when I run it in the browser, but get the same error when I try to load it via Expo on my iphone.

**Comment by jvfalco1** [comment]
I Still getting this error in iPhone. (without expo.)

**Comment by ethanyuwang** [comment]
also having the same issue

**Comment by HamedMP** [comment]
I had this issue when I had an innocent `;` mixing JSX/TSX with JS code that I was trying before in my return statement 🤦

**Comment by TomasSestak** [comment]
for me it was not using curly bracket {} around variable when i was returning JSX

**Comment by Hakeemmidan** [comment]
@HamedMP @TomasSestak 
Did you use the logs to find the error? Or did you find it manually?

**Comment by Hakeemmidan** [comment]
I found mine as well. It was that I was using a `<b>` tag for bolding. 

That seems to not be allowed in React Native (although I couldn't find a place in the docs that explicitly states that):
> Instead of rendering HTML elements like div, span, h1, etc., we're rendering components like View and Button. These are native components that work across different platforms.

([source](https://reactnative.dev/blog/2018/05/07/using-typescript-with-react-native#adding-a-component))

**Comment by vanessajbell** [comment]
My issue was that I had a {/* comment */} in my JSX :/

**Comment by guplem** [comment]
For me, it was a component that did some logic (configuration), but only wrapped the children.

It looked like this:

```
export function ConfigurationHandler({ children }) {
  ( ... )
  return <> {children} </>
}
```

We had to change it to:
```
export const ConfigurationHandler = ({children}) => {
  ( ... )
  return <> {children} </>
}
```

**Comment by rogeriorioli** [comment]
NOTHING ?
