### ISSUE TITLE
WEB: Unable to navigate to initialRoute after navigating direct to url

### ISSUE THREAD

**Issue by alexmccabe** [react-navigation/react-navigation#8935]
**Current Behavior**

When navigating direct to screen from a url (copy/pasted, or refresh) the navigation state has been disposed of meaning that it's not possible to navigate to the root of the stack, or reset to any screen, as the only route is the current one. This only happens on web.

- What code are you running and what is happening?

```js
const isFocused = state.index === index;

        const onTabPress = () => {
          const customEvent = navigation.emit({
            type: "tabPress",
            target: route.key,
            canPreventDefault: true,
          });

          if (!isFocused && !customEvent.defaultPrevented) {
            navigation.dispatch({
              ...CommonActions.navigate(route.name),
              target: state.key,
            });
          }
        };
```

- Include a screenshot or video if it makes sense.

**Expected Behavior**

- What do you expect should be happening?
I would expect to be able to navigate to the initialRoute of the tab stack

- Include a screenshot or video if it makes sense.

**How to reproduce**

1. Basic bottom tab navigation installation with nested stack navigators
2. Navigate to a screen inside a nested stack navigator
3. Refresh the screen (the history is now wiped)
4. Press the current tab and try to get back to the root screen (initialRoute)

**Your Environment**

| software                      | version |
| ----------------------------- | ------- |
| iOS or Android                | web
| @react-navigation/native      | 5.7.3
| @react-navigation/bottom-tabs | 5.8.0
| react-native-screens          | 2.11.0
| react-native                  | 0.63.2
| expo                          | n/a
| node                          | 14.4.0
| npm or yarn                   | yarn

**Comment by alexmccabe** [comment]
Issue still exists after upgrading to latest versions of above packages

**Comment by alexmccabe** [comment]
For anyone that winds up here I have a workaround:

```js
{
  state.routes?.map((route, index) => {
    const isFocused = state.index === index;
    const descriptor = descriptors[route.key];
    const options = (descriptor && descriptor.options) || {};

    /**
     * Handle tab press. This is a fairly complex process on the web, due to
     * the fact that if a user comes direct to the screen from a URL there
     * is no previous history to navigate to, so React Navigation can't
     * handle it.
     *
     * Instead we have to have a workaround that clears the entire children
     * state routes and resets it back to as if we had just mounted the
     * navigation.
     */
    const onTabPress = () => {
      const customEvent = navigation.emit({
        type: 'tabPress',
        target: route.key,
        canPreventDefault: true,
      });

      if (!customEvent.defaultPrevented) {
        if (isFocused) {
          navigation.dispatch((navState) => {
            return CommonActions.reset({
              index,
              routes: navState.routes.map((item) => ({ name: item.name })),
            });
          });
        } else {
          navigation.dispatch({
            ...CommonActions.navigate(route.name),
            target: state.key,
          });
        }
      }
    };

    return (
      <NavigationItem
        key={index}
        isFocused={isFocused}
        onPress={onTabPress}
        options={options}
        route={route}
      />
    );
  });
}
```
I have this in a custom component which replaces the default React Navigation one.

**Comment by satya164** [comment]
https://reactnavigation.org/docs/configuring-links/#rendering-an-initial-route

**Comment by alexmccabe** [comment]
I don't want to render an initial route. Given any URL path that goes to a nested screen, this then prevents the ability to go to the top of the stack (I.E the initial route). This should not be closed, it's still an issue.

**Comment by pweisensee** [comment]
@alexmccabe and for others that may find themselves with this issue, I think the solution you're looking for may be resolved with the `initial: false` option. This is a breaking change from React Navigation v4 -> v5. 

https://reactnavigation.org/docs/nesting-navigators/#rendering-initial-route-defined-in-the-navigator

**Comment by LB-Digital** [comment]
> For anyone that winds up here I have a workaround:
> 
> ```js
> {state.routes?.map((route, index) => {
>     const isFocused = state.index === index;
>     const descriptor = descriptors[route.key];
>     const options = (descriptor && descriptor.options) || {};
> 
>     /**
>      * Handle tab press. This is a fairly complex process on the web, due to
>      * the fact that if a user comes direct to the screen from a URL there
>      * is no previous history to navigate to, so React Navigation can't
>      * handle it.
>      *
>      * Instead we have to have a workaround that clears the entire children
>      * state routes and resets it back to as if we had just mounted the
>      * navigation.
>      */
>     const onTabPress = () => {
>     const customEvent = navigation.emit({
>         type: 'tabPress',
>         target: route.key,
>         canPreventDefault: true,
>     });
> 
>     if (!customEvent.defaultPrevented) {
>         if (isFocused) {
>             navigation.dispatch((navState) => {
>                 return CommonActions.reset({
>                 index,
>                 routes: navState.routes.map((item) => ({ name: item.name })),
>                 });
>             });
>         } else {
>             navigation.dispatch({
>                 ...CommonActions.navigate(route.name),
>                 target: state.key,
>             });
>         }
>     }
>     };
> 
>     return (
>         <NavigationItem
>             key={index}
>             isFocused={isFocused}
>             onPress={onTabPress}
>             options={options}
>             route={route}
>         />
>     );
> })}
> ```
> 
> I have this in a custom component which replaces the default React Navigation one.

Can confirm I am still facing this issue today, and this solution is the most reliable/only fix I've found thus far.
