### ISSUE TITLE
gestureResponseDistance has no effect in Screen options

### ISSUE THREAD

**Issue by dan-lee** [react-navigation/react-navigation#8938]
**Current Behavior**

I created a Modal and set a `gestureResponseDistance` to be able to drag it down to close it, which works fine.
On particular screens I want to change this value though, but it has no effect when I set in the `options` prop on the `Stack.Screen` component.

I also tried `navigation.setOptions(…)` in the screen itself but I am only greeted with:

> Warning: Cannot update a component from inside the function body of a different component.

**Expected Behavior**

The `gestureResponseDistance` should change on screens where I pass the option.

**How to reproduce**

See Snack: https://snack.expo.io/@dan-lee/healthy-crackers

I want the second screen (with the Close button) in the modal not to be draggable.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS                            | 14
| @react-navigation/native       | 5.7.6
| @react-navigation/stack        | 5.9.3
| react-native-gesture-handler   | latest from expo snack
| react-native-safe-area-context | ^0.6.0
| react-native-screens           | latest from expo snack
| react-native                   | latest from expo snack
| expo                           | 39.0.0

**Comment by satya164** [comment]
https://reactnavigation.org/docs/screen-options-resolution/
https://reactnavigation.org/docs/nesting-navigators/#best-practices-when-nesting
