### ISSUE TITLE
InputAccessoryView Not Transitioned By Navigation

### ISSUE THREAD

**Issue by nhannah** [react-navigation/react-navigation#8945]
**Current Behavior**

[InputAccessoryView](https://reactnative.dev/docs/inputaccessoryview) Is not transitioned by screen navigation likely due to the portaling of the RN code. Being able to access the reanimated transition values in a component would allow this to be solved by animating the component separately by a user. 

![Simulator Screen Shot - iPhone 11 - 2020-10-09 at 09 30 38](https://user-images.githubusercontent.com/608869/95602425-27e5e900-0a12-11eb-89cb-50e1bddfa47d.png)

**Expected Behavior**

The InputAccessoryView remains in the previous screen and transitions off screen with it. It may be too much to expect React Navigation to handle this but access to the animation values via a provided ref or setRef call would allow a user to handle the issue themselves.

**How to reproduce**

Add an InputAccessoryView to any stack navigation screen and begin to swipe back, it will remain above the screen.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | iOS
| @react-navigation/native       | 5.7.6
| @react-navigation/stack        | 5.9.3
| react-native-gesture-handler   | 1.8.0
| react-native-safe-area-context | 3.1.8
| react-native-screens           | 2.11.0
| react-native                   | 0.63.3
| expo                           | N/A
| node                           | 12.16.1
| yarn                    | 1.22.4

**Comment by ZakSingh** [comment]
This would be a great addition!

**Comment by timothyerwin** [comment]
any update on this? switching screens makes the inputaccessoryview completely disappear when navigating back

**Comment by audn** [comment]
> any update on this? switching screens makes the inputaccessoryview completely disappear when navigating back

did you find a fix for this?

**Comment by timothyerwin** [comment]
> > any update on this? switching screens makes the inputaccessoryview completely disappear when navigating back
> 
> did you find a fix for this?

Just toggle a conditional rerender will make it show up but it's not ideal.

**Comment by Matthew-Allman** [comment]
Has anyone found a fix for this?
