### ISSUE TITLE
Disable animation temporarily when resetting state

### ISSUE THREAD

**Issue by janoist1** [react-navigation/react-navigation#8948]
I'd like to temporarily disable animation when `reset`ting state (https://reactnavigation.org/docs/navigation-prop/#reset).
The bigger picture is that some screens need to reset navigation state once they finish animating. The issue is, when resetting state a transition animation is triggered.
How to `reset` state without doing animation? Thanks.

`"@react-navigation/native": "^5.7.6"`

**Comment by pi0trpietruszewski** [comment]
+1

**Comment by marcinkornek** [comment]
+1

**Comment by xclidongbo** [comment]
+1
