### ISSUE TITLE
Inner content of Screen is not accessible by automation (Appium)

### ISSUE THREAD

**Issue by avient** [react-navigation/react-navigation#8960]
**Current Behavior**

- Any elements within `Screen` component are not accessible by automation and shown as one item

**Expected Behavior**

- Should be able to expose inner content of the `Screen` component

**How to reproduce**

```
function HomeScreen() {
  return (
    <TouchableOpacity accessible={false} testID="opacity">
      <View testID="outer">
        <View testID="inner1">
          <View testID="inner1-1">
            <Text testID="text1">Good morning,1</Text>
          </View>
        </View>
        <View testID="inner2">
          <Text testID="text2">Good morning,2</Text>
        </View>
      </View>
    </TouchableOpacity>
  );
}

export const BottomTabNavigation = ({}) => (
  <BottomTab.Navigator>
    <BottomTab.Screen name="Home" component={HomeScreen} />
  </BottomTab.Navigator>
);
```

![image](https://user-images.githubusercontent.com/25175318/96468831-38c60400-1235-11eb-9b61-71d63f3bd150.png)

**Your Environment**

| software                      | version |
| ----------------------------- | ------- |
| iOS or Android                | iOS
| @react-navigation/native      |5.2.4
| @react-navigation/bottom-tabs |5.3.4
| react-native-screens          |2.7.0
| react-native                  |0.63.3

**Comment by avient** [comment]
> The versions mentioned in the issue for the following packages differ from the latest versions on npm:
> 
> * `@react-navigation/native` (found: `5.2.4`, latest: `5.7.6`)
> * `@react-navigation/bottom-tabs` (found: `5.3.4`, latest: `5.9.2`)
> 
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?

Yes, it still exists

**Comment by demedos** [comment]
@avient did you find a solution to this?

**Comment by Alek5andr** [comment]
Any solution?

**Comment by arled** [comment]
This still happens with the below versions:
        "@react-navigation/bottom-tabs": "^6.5.3",
        "@react-navigation/native": "^6.0.12",
