### ISSUE TITLE
focus event entirely broken

### ISSUE THREAD

**Issue by 11grossmane** [react-navigation/react-navigation#8961]
**Current Behavior**

Ever since upgrading to react navigation 5, focus events simply don't fire properly when using async await.  We were using react navigation 3 with onFocus and onBlur, and everything worked perfectly, but now with react navigation 5 those event must have changed because they do not work the same way.  And, when the focus events run, the setState actions inside them do not consistently run/cause rerendering.

**Expected Behavior**

When the tab focuses, the async focus event should run and MORE IMPORTANTLY any changes to state that occur should cause rerendering 

**How to reproduce**

Snack: https://snack.expo.io/ebTaX9086

In the snack, I am using an IIFC inside the focus event, but it also does not work if the focus event itself is asynchronous.  I've also tested this with useFocusEffect and useCallback with the same result.

**Your Environment**

react-native 0.63.0
iOS
"@react-navigation/bottom-tabs": "^5.9.0",
"@react-navigation/material-top-tabs": "^5.2.17",
"@react-navigation/native": "^5.0.0",
"@react-navigation/stack": "^5.9.1",
"expo": "^39.0.0",
node: 12.19.0
npm

**Comment by 11grossmane** [comment]
This is actually an issue caused by the expo debugger I have found.  The focus events do not work properly when remote debugging is active.

**Comment by satya164** [comment]
https://reactnavigation.org/docs/troubleshooting#app-is-not-working-properly-when-connected-to-chrome-debugger
