### ISSUE TITLE
Invariant Violation: requireNativeComponent: "RNCSafeAreaProvider" was not found in the UIManager.

### ISSUE THREAD

**Issue by PitlaSpandana** [react-navigation/react-navigation#8964]
am facing below error while upgrading from react-navigation 4 to 5:

Invariant Violation: requireNativeComponent: "RNCSafeAreaProvider" was not found in the UIManager.
This error is located at: in RNCSafeAreaProvider (at SafeAreaContext.tsx:74)
 in SafeAreaProvider (at SafeAreaProviderCompat.tsx:42)  in SafeAreaProviderCompat (at StackView.tsx:453)
 in GestureHandlerRootView (at GestureHandlerRootView.android.js:31)
 in GestureHandlerRootView (at StackView.tsx:452)
 in StackView (at createStackNavigator.tsx:84)
 in StackNavigator (at createCompatNavigatorFactory.tsx:154)
 in Navigator (at AppContainer.js:75)
 in EnsureSingleNavigator (at BaseNavigationContainer.tsx:390)
 in ForwardRef(BaseNavigationContainer) (at NavigationContainer.tsx:91)
 in ThemeProvider (at NavigationContainer.tsx:90)
 in ForwardRef(NavigationContainer) (at AppContainer.js:74)
```

`package.json`

`"@react-native-community/masked-view": "^0.1.10",
    "react-native-gesture-handler": "^1.8.0",
    "@react-navigation/compat": "^5.2.8",
    "@react-navigation/native": "^5.7.6",
    "@react-navigation/stack": "^5.9.3",
    "react": "16.9.0",
    "react-native": "0.61.2",
    "react-native-safe-area-context": "^3.1.8",
    "react-native-screens": "^2.0.0-beta.2",
`

```
```
`index.android.js`

`import 'react-native-gesture-handler';`

` render() {
    return (
      <AppContainer ref={container => (this.container = container)}>
        {this.state.showProgressIndicator ? this.renderProgressOverlay() : null}
      </AppContainer>
    );
  }`
```

`appContainer.js`

````
render(){ 
return(
 <View style={{ flex: 1 }}>
       {this.renderAlertModal()}
        <NavigationContainer>
<MainStackNavigator/>
        </NavigationContainer>
      </View>
);
}
````

```
mainstackNavigator.js

`const MainStack = createStackNavigator();
function MainStackNavigator() {
  return (
    <MainStack.Navigator
      headerMode="none"
      screenOptions={{
        header: null,
        headerShown: false
      }}>
      <MainStack.Screen name="home" component={homePage} />
    </MainStack.Navigator>
  );
}
export default MainStackNavigator;`
```

**Comment by PitlaSpandana** [comment]
I  upgraded mentioned versions but still am getting same issue

**Comment by joshmn** [comment]
did you ever figure this out?

**Comment by PitlaSpandana** [comment]
This is the first time I noticed the issue

**Comment by PitlaSpandana** [comment]
can any one please help me out on resolving this

**Comment by suwu150** [comment]
i get same error

**Comment by satya164** [comment]
You need to make sure that `react-native-safe-area-context` is linked properly. If automatic linking doesn't work, follow the documentation of the library to link it manually https://github.com/th3rdwave/react-native-safe-area-context#linking-in-react-native--060-1

**Comment by suwu150** [comment]
I specified it manually, but I still haven't solved my problem

**Comment by rasidre** [comment]
@suwu150 did you reinstall the pods again with `pod install` after upgrading the package?

**Comment by PitlaSpandana** [comment]
I specified it manually, but I still haven't solved my problem. and I reinstalled pods again and am running app in android

**Comment by heypran** [comment]
facing the same issue, linking done and pod install done.

**Comment by ankithans** [comment]
For me stopping and re-running the app worked 😅

**Comment by quachdev** [comment]
For whatever reason, I receive this error when I run it through my detox tests. I don't get it when building it normally though.

Anyone else experience this with Detox?

**Comment by SobhanBera** [comment]
### Follow These Steps:
I also got that error when setting up react navigations but the below code worked for me.
Paste this code in the files shown below:

- **android/settings.gradle**
```
include ':react-native-safe-area-context'
project(':react-native-safe-area-context').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-safe-area-context/android')
```

- **android/app/build.gradle**
```
dependencies {
    implementation project(':react-native-safe-area-context')
    ...
}
```

- **android/app/src/main/java/com/[APP_NAME]/MainApplication.java**
```
import com.th3rdwave.safeareacontext.SafeAreaContextPackage;
```

- **android/app/src/main/java/com/[APP_NAME]/MainApplication.java (Add this code where the getPackages function exists)**
```
@Override
protected List<ReactPackage> getPackages() {
    return Arrays.asList(
        ...
        new MainReactPackage(),
        new SafeAreaContextPackage()
    );
}
```
OR if already a package is returned then this code
```
@Override
protected List<ReactPackage> getPackages() {
    List<ReactPackage> packages = new PackageList(this).getPackages();
    packages.add(new ModuleRegistryAdapter(mModuleRegistryProvider));
    packages.add(new SafeAreaContextPackage());
    return packages;
}
```

### You can also get this for IOS [here](https://github.com/th3rdwave/react-native-safe-area-context#linking-in-react-native--060-1)
I was getting in android so I provided the android code.

**Comment by aboux** [comment]
I got this issue. I cleaned cashes cd ios/ pod install and re-run the app works for me.

**Comment by PiPauwels** [comment]
@SobhanBera : Great work! I got this exact error in a ReactXP project, when adding React Navigation to the React Native part of the project and trying to run it on a virtual device. After applying your changes, the project runs perfectly. How on earth did you find this out?

**Comment by VelislavP** [comment]
@SobhanBera You are a life savior! My app works perfectly now, after applying your solution!

**Comment by SobhanBera** [comment]
@PiPauwels @VelislavP
Keep Following Me I will share helpful codes in future too. Thanks

**Comment by john-harding** [comment]
For me running `npm i react-native-safe-area-context@0.7.3 --save` and then pod installing worked.

**Comment by jobn123** [comment]
> I got this issue. I cleaned cashes cd ios/ pod install and re-run the app works for me.
> I think react-native-safe-area-context was not properly installed.
> 
> Good luck 😉

thanks, works for me

**Comment by cat-ico** [comment]
`yarn add react-native-safe-area-context` worked for me

**Comment by joshuapinter** [comment]
Just a note on this (for Android at least): after adding `react-native-safe-area-context` to your `package.json` and installing, make sure to clean your build and re-run it in your device/simulator. Otherwise, you will run into an error like this: 

```
"RNCSafeAreaProvider" was not found in the UIManager
```

There's some native components that need to get packaged into the `.apk` after installing `react-native-safe-area-context`.

**Comment by edcelmanuel** [comment]
I got this issue too on create-react-native-app. I just run this command and it just works. try it

```js
expo install react-native-safe-area-context
```

**Comment by smity81435** [comment]
I fixed this issue (after hours of following above solutions) by simply running:
`npm i react-native-safe-area-context --save-exact` 
then re-running `react-native run-android`

**Comment by SherMish** [comment]
> `yarn add react-native-safe-area-context` worked for me

Thank you!!

**Comment by wapstySagheer** [comment]
@sobhanbera thanks bro its works for me

**Comment by walidmokhtari** [comment]
I've a same error, i just rebuild  my project after install ### 'react-native-safe-area-context'  and it's work

**Comment by RhesusP** [comment]
I had the same error. Just stop metro server and restart it !

**Comment by sarnakov** [comment]
Rebuilding after installation helped

**Comment by developerdex2908** [comment]
> I fixed this issue (after hours of following above solutions) by simply running: `npm i react-native-safe-area-context --save-exact` then re-running `react-native run-android`

Thanks for this. I've been trying out for hours too!

**Comment by Desintegrator** [comment]
same issue
fixed by adding in Podfile:
`pod 'react-native-safe-area-context', :path => '../node_modules/react-native-safe-area-context'`

**Comment by premathunga** [comment]
`npm install react-native-safe-area-context`
worked for me

**Comment by JairajJangleSLIOT** [comment]
> For android users with same issue - you can also try manual linking
> 
> 1. settings.gradle
> 
> ```
> include ':react-native-safe-area-context'
> project(':react-native-safe-area-context').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-safe-area-context/android')
> ```
> 
> 2. app/build.gradle
> 
> ```
> dependencies {
>   ...
>   implementation project(':react-native-safe-area-context')
>   ...
> }
> ```
> 
> 3. MainApplication.java
> 
> ```
> import com.th3rdwave.safeareacontext.SafeAreaContextPackage;
> ...
>   protected List<ReactPackage> getPackages() {
>     ...
>     packages.add(new SafeAreaContextPackage());
>     ...
>   }
> ```

This worked for me, I started facing this issue out of nowhere on Android and iOS even though nothing had changed in our project. This should have been handled by react native auto-linking. It's a mystery why react native auto-linking did not work for react-native-safe-area-context. I even tried reinstalling the library. I performed pod install multiple times but the react-native-safe-area-context pods were not getting installed at all. 

The pods and Android Gradle dependency were installed only after I applied this workaround.

**Comment by smit5364** [comment]
npm install react-native-safe-area-context
worked for me

**Comment by yhojann-cl** [comment]
When use `npm install react-native-safe-area-context` and try run says:

> Task :react-native-safe-area-context:processDebugManifest
> package="com.th3rdwave.safeareacontext" found in source AndroidManifest.xml: /.../app/node_modules/react-native-safe-area-context/android/src/main/AndroidManifest.xml.
> Setting the namespace via the package attribute in the source AndroidManifest.xml is no longer supported, and the value is ignored.
> Recommendation: remove package="com.th3rdwave.safeareacontext" from the source AndroidManifest.xml: /.../app/node_modules/react-native-safe-area-context/android/src/main/AndroidManifest.xml.
> ...
> Task :react-native-safe-area-context:compileDebugKotlin
w: file:///.../app/node_modules/react-native-safe-area-context/android/src/main/java/com/th3rdwave/safeareacontext/SafeAreaContextModule.kt:7:46 'ReactModule' is deprecated. Deprecated in Java

The manually solution is now deprecated?, Realy need a hard setting to use a simple navigation?
