### ISSUE TITLE
Exception: 'Can't find variable: DrawerActions' Stack Screen cannot access to nested Drawer method via Dispatch

### ISSUE THREAD

**Issue by smanzini** [react-navigation/react-navigation#8966]
**Current Behavior**
Exception: 'Can't find variable: DrawerActions
Reac-native js
- What code are you running and what is happening?
- Include a screenshot or video if it makes sense.

**Expected Behavior**

Navigate to nested drawer inside parent Stack
- What do you expect should be happening?
- Include a screenshot or video if it makes sense.

**How to reproduce**

const HomeDrawer = createDrawerNavigator();
const HomeDrawerScreen = ({navigation}) => (

  <HomeDrawer.Navigator>
        <HomeDrawer.Screen name="Profile" component={Profile} />
        <HomeDrawer.Screen name="Social" component={Social} />
      </HomeDrawer.Navigator>
);
 
const Stack = createStackNavigator();

const App = () => {  
  return (

    <NavigationContainer>
      
      <Stack.Navigator
      initialRouteName="Home"
      screenOptions={{ 
        title: 'Ubi',
        headerStyle: {
          backgroundColor: '#1B1A1A',
          height:100
        },
        headerTintColor: '#E00615',

        headerLeft:(navigation) => (
          
          <Button title="MENU"
          backgroundColor='#E00615'
          onPress={()=> 
            navigation.dispatch(DrawerActions.toggleDrawer())}/>
            ),
          }}
          >
            
        <Stack.Screen name="Home" component={HomeScreen}/> 
       <Stack.Screen name="MyVideos" component={MyVideos} options={({route}) => ({ title: route.params.name})}
        />
        <Stack.Screen name="HomeDrawerScreen" component={HomeDrawerScreen}/>

       </Stack.Navigator>

    </NavigationContainer>
  );
}

export default App;

- You must provide a way to reproduce the problem. If you are having an issue with your machine or build tools, the issue belongs on another repository as that is outside of the scope of React Navigation.
- Either re-create the bug on [Snack](https://snack.expo.io) or link to a GitHub repository with code that reproduces the bug.
- Explain how to run the example app and any steps that we need to take to reproduce the issue from the example app.
- Keep the repro code as simple as possible, with the minimum amount of code required to repro the issue.
- Before reporting an issue, make sure you are on latest version of the package.

**Your Environment**
iOS
import * as React from 'react';
import { Button, View, Text } from 'react-native';
import { NavigationContainer } from '@react-navigation/native';
import { createStackNavigator, HeaderBackButton } from '@react-navigation/stack';
import { createDrawerNavigator } from '@react-navigation/drawer';
import { createBottomTabNavigator } from '@react-navigation/bottom-tabs';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faCoffee } from '@fortawesome/free-solid-svg-icons'

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |
| @react-navigation/native       |
| @react-navigation/drawer       |
| react-native-reanimated        |
| react-native-gesture-handler   |
| react-native-safe-area-context |
| react-native-screens           |
| react-native                   |
| expo                           |
| node                           |
| npm or yarn                    |

**Comment by rparrett** [comment]
You need to import `DrawerActions`.

```import { NavigationContainer, DrawerActions } from '@react-navigation/native';```

**Comment by Deepak9811** [comment]
> You need to import `DrawerActions`.
> 
> `import { NavigationContainer, DrawerActions } from '@react-navigation/native';`

Not working
