### ISSUE TITLE
Navigating across nested navigators 'freezes' other navigation functions.

### ISSUE THREAD

**Issue by mofmn** [react-navigation/react-navigation#8970]
I have a Tab navigator that contains stack navigators 
Tab navigator contains Dashboard and explore screens with their own stack navigators. In explore you can navigate to a route page in a stack navigator that will show you the route passed in the item prop. So navigate from explore page with navigate(routeScreen, {item: item1}) will show you that item.

If i navigate from the Dashboard through navigate('Explore',{screen: 'routeScreen', params: {item:item2)}) it will work as expected, except the now the original navigations to item1 will only ever navigate back to the route page containing item2, it seems the item1 prop will no longer be passed in the navigation. Expected behaviour is that the params should always be passed to the screen regardless of where they are navigated from.

There is also some trippy goBack() behaviour that required me to use a specific page reference instead of the goBack() function but i am less concerned with that at this time as it can be designed around 

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | iOS 
| @react-navigation/native       | 5.7.3
| react-native                   |  0.63.2
| node                           |

**Comment by mofmn** [comment]
upgrading to 5.7.6 did not change the issue

**Comment by gazedash** [comment]
+1

**Comment by mofmn** [comment]
I see this is now tagged as needs more info, without a request for what info you want? You have current and expected behaviour. I am not writing you debug env code because i don't have the time. You should have a test written for this use case, if not, now sounds like a good time. If you expect example code of every issue you will only ever fix surface issues.

**Comment by oliverturner** [comment]
> I am not writing you debug env code because i don't have the time

Not sure this is the attitude to take when asking someone for help tbh.

**Comment by mofmn** [comment]
I am not asking for help @oliverturner , i am reporting a bug. I no longer intend to use this module as it does not appear to be maintained.

**Comment by thymikee** [comment]
@mofmn I believe you can imagine @satya164 and other maintainers of this lib get a lot of bug reports, support requests etc. 200+ issues is a lot and they're trying to manage it mostly doing it in their free time. 

In the issue template, which I'm sure you've read, **you're explicitly asked to provide a minimal reproduction**, ideally in a form of Snack or a repo that can be downloaded:

<img width="820" alt="image" src="https://user-images.githubusercontent.com/5106466/98115940-deb97580-1ea7-11eb-8c1a-c32fb09d5f2f.png">

Of course, this is some extra work for you to make, but it makes maintainers jobs so much easier and hence improving your chances for the bug to be picked up and fixed. When you don't care about the best repro you can come up with, how do you expect them to do their best for you? 

Cheers!

**Comment by mofmn** [comment]
I understand this, once again, i am reporting a bug, i don't need it fixed, i have other workarounds that are faster and more reliable. Issue was tagged with 'needs more information' and then effectively abandoned to be left like the 2 hundred others. It will not get fixed this way, there will be zero outcome. The fact is, you don't need more information, you need more effort. Whether this effort comes from me, you or one of the others that has encountered the same issue depends on who has the time. As i have said, i don't, if you don't either then thats fine. The issue will not get fixed until someone does.
