### ISSUE TITLE
[Web] query-string does not contain a default export

### ISSUE THREAD

**Issue by yairopro** [react-navigation/react-navigation#8971]
**Current Behavior**

I tried to import `createStackNavigator`, and I got the build error:
```
Failed to compile.

./node_modules/@react-navigation/core/lib/module/getStateFromPath.js
Attempted import error: 'query-string' does not contain a default export (imported as 'queryString').
```
I am using webpack & react-native-web.

**Expected Behavior**

The build to pass.

**How to reproduce**

````javascript
import {createStackNavigator} from "@react-navigation/stack";
````

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| @react-navigation/stack | ^5.9.3 |
| @react-navigation/native | ^5.7.6 |
| react-native-web | ^0.14.3 |
| webpack | 4.28.3 |

**Comment by yairopro** [comment]
Thanks !

**Comment by aliassar** [comment]
Just found this bug in my new project again. Exactly the same build error ( run perfectly in dev mode ) & here is my environment:

software | version
-- | --
@react-navigation/stack | ^5.12.8
@react-navigation/native | ^5.9.4
react-native-web | ^0.16.2
webpack | 4.33.0 ( not sure )

P. E. I tried a lot of version combinations & I don't think that's the problem.

**Comment by Nico-Guyon** [comment]
I have exactly the same problem, did you by any chance find a solution ?

**Comment by yairopro** [comment]
@Nico-Guyon 
The bug is fixed
Just update

**Comment by BlueBazze** [comment]
./node_modules/@react-navigation/core/lib/module/getStateFromPath.js
Attempted import error: 'parse' is not exported from 'query-string' (imported as 'queryString').

Using @react-navigation/core@6.1.0
Ive toyed around with it a bit. Dont seem to have found a solution.
Except importing from "querystring" instead of "query-string". I wouldnt know the side effects from this.

**Comment by MariaPtrv** [comment]
I have the same bug with Vue and jsx
