### ISSUE TITLE
Strange and random screen transitions

### ISSUE THREAD

**Issue by rueiwoqp** [react-navigation/react-navigation#8975]
**Current Behavior**
Navigation takes place without calling navigation.navigate or any other react-navigation API.

- What code are you running and what is happening?
    "@react-navigation/bottom-tabs": "^5.7.3",
    "@react-navigation/material-top-tabs": "^5.2.19",
    "@react-navigation/native": "^5.6.1",
    "@react-navigation/stack": "^5.6.2",

- Include a screenshot or video if it makes sense.

**Expected Behavior**
Navigation should not happen unless navigation.<function> is called

- What do you expect should be happening?
- Include a screenshot or video if it makes sense.

**How to reproduce**
**In my app:**
Pull to refresh a FlatList whose onRefresh function is an async function that makes several API calls. IT DOES NOT ATTEMPT TO NAVIGATE ANYWHERE. Despite this, the screen changes to a different screen.

I can't understand this and I've seen other strange behavior, seemingly related to state changes or possibly async calls.  I tried to reproduce with a base install but could not.

Maybe I'm just missing something about how it's supposed to work. Is there any scenario where an async function or state change in a parent navigator would cause random transitions to different screens. This is driving me insane.  The app is completely unstable because I  refactor something totally unrelated to navigation or I add some new feature and suddenly previous screen transitions that worked, stop working or the changes introduce a totally unnecessary screen transition.

- You must provide a way to reproduce the problem. If you are having an issue with your machine or build tools, the issue belongs on another repository as that is outside of the scope of React Navigation.
- Either re-create the bug on [Snack](https://snack.expo.io) or link to a GitHub repository with code that reproduces the bug.
- Explain how to run the example app and any steps that we need to take to reproduce the issue from the example app.
- Keep the repro code as simple as possible, with the minimum amount of code required to repro the issue.
- Before reporting an issue, make sure you are on latest version of the package.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |
| @react-navigation/native       |
| react-native                   |
| expo                           |
| node                           |
| npm or yarn                    |

**Comment by rueiwoqp** [comment]
Reproduced with the following
    "@react-navigation/bottom-tabs": "^5.9.2",
    "@react-navigation/material-top-tabs": "^5.2.19",
    "@react-navigation/native": "^5.7.6",
    "@react-navigation/stack": "^5.9.3",

**Comment by jchook** [comment]
Hey @rueiwoqp, I also ran into this issue and I think it has something to do with [creating components within other components](https://reactnavigation.org/docs/troubleshooting/#screens-are-unmountingremounting-during-navigation)
