### ISSUE TITLE
headerShown: true not working when headerMode set to none

### ISSUE THREAD

**Issue by mohity777** [react-navigation/react-navigation#8978]
**Current Behavior**
no header is shown

- What code are you running and what is happening?
- Include a screenshot or video if it makes sense.
![image](https://user-images.githubusercontent.com/56041802/97001558-2d851800-1556-11eb-9f25-1cbdfbcee422.png)

**Expected Behavior**
 header should be visible in chatscreen but it is not showing.
- What do you expect should be happening?
- Include a screenshot or video if it makes sense.

**How to reproduce**

- You must provide a way to reproduce the problem. If you are having an issue with your machine or build tools, the issue belongs on another repository as that is outside of the scope of React Navigation.
- Either re-create the bug on [Snack](https://snack.expo.io) or link to a GitHub repository with code that reproduces the bug.
- Explain how to run the example app and any steps that we need to take to reproduce the issue from the example app.
- Keep the repro code as simple as possible, with the minimum amount of code required to repro the issue.
- Before reporting an issue, make sure you are on latest version of the package.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |  android 9
| @react-navigation/native       |  "^5.7.5"
| @react-navigation/stack        |  "^5.9.2"
| react-native-gesture-handler   |
| react-native-safe-area-context |
| react-native-screens           |
| react-native                   |   "0.63.3"
| expo                           |
| node                           |
| npm or yarn                    |

**Comment by satya164** [comment]
![Screenshot_20201023-151856.png](https://user-images.githubusercontent.com/1174278/97008539-3d473100-1543-11eb-9d2a-5d92bf6c0ccb.png)

**Comment by mohity777** [comment]
but if i want the header not to render on all screens but render only on one screen do i have to keep headerMode= true and provide headerShown= false to all screens except for the screen i want the header to render? headerShown should override headerMode

**Comment by mclima123** [comment]
Don't use headerMode, use screenOptions={{headerShown: false}} on your navigator and overwrite the screens you want with options={{headerShown: true}}.
