### ISSUE TITLE
High CPU usage with drawerPosition set to "right"

### ISSUE THREAD

**Issue by m15r** [react-navigation/react-navigation#8979]
**Current Behavior**

Xcode's profiler reports over 120% CPU usage when ```drawerPosition``` is set to ```'right'``` on ```createDrawerNavigator```, resulting in extensive battery drain. When removing this property the CPU usage is less than 1%.

My drawer configuration:

```js
const DrawerNavigation = createDrawerNavigator({
  Home: { screen: LockStack }
  },{
    initialRouteName: 'Home',
    transitionConfig: () => ({
      transitionSpec: {
        duration: 0,
      },
    }),
    drawerPosition: 'right',
    contentComponent: SideMenu,
    overlayColor: 'rgba(0, 0, 0, .35)',
    drawerWidth: width / 1.6
})
```

With drawerPosition set:

<img width="865" alt="Screenshot 2020-10-23 at 16 19 58" src="https://user-images.githubusercontent.com/21246069/97015282-aaf75b00-154b-11eb-813f-6239248e57db.png">

Without drawerPosition set:

<img width="865" alt="Screenshot 2020-10-23 at 16 18 10" src="https://user-images.githubusercontent.com/21246069/97015330-bcd8fe00-154b-11eb-807f-b50e7f948193.png">

**How to reproduce**

Add ```drawerPosition: 'right'``` to ```createDrawerNavigator``` configuration.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | iOS
| react-navigation               | 4.4.2
| react-navigation-stack         | 2.8.2
| react-navigation-tabs          | 2.9.0
| react-navigation-drawer        | 2.5.2
| react-native-reanimated        | 1.13.0
| react-native-gesture-handler   | 1.7.0
| react-native-safe-area-context | 3.1.8
| react-native-screens           | 2.10.1
| react-native                   | 0.63.2
| expo                           |
| node                           | 12.18.4
| npm or yarn                    | yarn 1.22.5

**Comment by m15r** [comment]
The issue still persists after updating to the latest versions of `react-navigation-stack` and `react-navigation-tabs`.

**Comment by owenjeon** [comment]
same here

**Comment by yungblud** [comment]
I am curious that this problem occurs because of React Native version (0.63.2).
With the lower version of React Native (lower than 0.62), I think it was fine.

**Comment by owenjeon** [comment]
@m15r I solved it by changing the `drawerWidth` value to an integer. I hope this workaround will help you.
```javascript
drawerWidth: Math.round(width / 1.6)
```

**Comment by m15r** [comment]
@owenjeon Seems to work for me as well. Thank you.

**Comment by HessiPard** [comment]
> @m15r I solved it by changing the `drawerWidth` value to an integer. I hope this workaround will help you.
> 
> ```js
> drawerWidth: Math.round(width / 1.6)
> ```

thanks man 👌

**Comment by tannguyen05** [comment]
> @m15r I solved it by changing the `drawerWidth` value to an integer. I hope this workaround will help you.
> 
> ```js
> drawerWidth: Math.round(width / 1.6)
> ```

@owenjeon  thanks a lot 👌
