### ISSUE TITLE
Bug - background is white but when opening a new screen it becomes transparent.

### ISSUE THREAD

**Issue by wilberparedes** [react-navigation/react-navigation#8989]
"react": "16.11.0",
"react-native": "0.62.2",
"@react-navigation/bottom-tabs": "^5.7.3",
"@react-navigation/drawer": "^5.8.7",
"@react-navigation/native": "^5.7.2",
"@react-navigation/stack": "^5.8.0",

any solution?
what you see in the background is the screen on which the push was made
![WhatsApp Image 2020-10-24 at 7 58 13 PM](https://user-images.githubusercontent.com/7405443/97096614-917e0e00-1634-11eb-8cc3-bf9ae68a2e7d.jpeg)

**Comment by achigo16** [comment]
any update about this bug?

**Comment by satya164** [comment]
Closing since you haven't provided a repro to debug the issue. If you manage to make a repro, please open a new issue with it and someone will take a look at it when possible.
