### ISSUE TITLE
Scrollview Implementation

### ISSUE THREAD

**Issue by smagana254** [react-navigation/react-navigation#8990]
Scrollview is not working with Stack Navigator

**Comment by smagana254** [comment]
here is my package.json

"dependencies": {
    "@react-native-community/masked-view": "0.1.10",
    "@react-navigation/drawer": "^5.9.3",
    "@react-navigation/native": "^5.7.6",
    "@react-navigation/stack": "^5.9.3",
  }

**Comment by luco** [comment]
Please, detail your issue a bit more.

**Comment by komelabbbas** [comment]
```
animationEnabled: true,
gestureEnabled: true,
gestureResponseDistance: SCREEN_WIDTH * 0.95,
cardOverlayEnabled: false,
...TransitionPresets.SlideFromRightIOS
```

Scrollview is not working in android.
Plz help
