### ISSUE TITLE
Is there a way to check which deeplink route the user is?

### ISSUE THREAD

**Issue by luco** [react-navigation/react-navigation#8991]
Let's suppose I have a working deeplink: `myapp://chat/1234`. Is there a way to identify if the user is in this route in app or should I implement my own code?

**Comment by satya164** [comment]
You can use [`useLinkBuilder`](https://reactnavigation.org/docs/use-link-builder/):

```js
function MyScreen({ route }) {
  const buildLink = useLinkBuilder();
  const path = buildLink(route.name, route.params);

  // Whatever
}
```

**Comment by luco** [comment]
@satya164  I think you didn't understand. I'd like to know where the user is on the navigator, and based on this, show or not a notification.

**Comment by satya164** [comment]
Why doesn't the code I posted work for you?

**Comment by luco** [comment]
Because it creates a link for the screen. I already have this link. What I'd like to get is the current path the user is on the navigator. For example:

My linking config:

```
module.exports = {
    prefixes: ['finpli://'],
    config: {
      Main: {
        screens: {
          Home: 'home',
          Search: 'search',
          Profile: {
            path: 'profile',
            screens: {
              Profile_EditProfile: 'edit'
            }
          },
          Ads: 'ads',
          Deals: {
            screens: {
              Deals_Main: 'deals/:status',
              Deals_Chat: 'chat/:id',
            }
          }
        }
      }
    }
};
```

When the user receives the notification, is goes to the /chat screen, which is working properly. However I'm looking for how to identify the current screen is active on the navigator, to, based on this, display or not the notification.

**Comment by satya164** [comment]
https://reactnavigation.org/docs/screen-tracking/#example

**Comment by luco** [comment]
@satya164 Amazing. Just one more question.

Why using useLinkBuilder in the chat view gives me the path `/chat/1234` while using it at the NavigationContainer `onStateChange` gives me the `/Deals_chat?id=1234`?

They both have the same params.

**Comment by satya164** [comment]
It needs to be under correct context to work properly. If you're not inside the screen, then you need to use `getPathFromState(navigationState, config)`.

**Comment by luco** [comment]
I'm trying on NavigationContainer:

```
onStateChange={() => {
                                    const route = navigationRef.current.getCurrentRoute();
                                    console.log(route);
                                    const path = buildLink(route.name, route.params ? route.params : {});
                                    console.log(path);
                            }}
```

**Comment by luco** [comment]
For those who are looking for it:

```
import { useNavigationState, getPathFromState } from '@react-navigation/native';
...
const navState = useNavigationState(state => state);
const path = getPathFromState(navState, LinkingConfig.config);
```
