### ISSUE TITLE
tabBarIcon not showing on IOS with react-navigation-tabs 2.10.0

### ISSUE THREAD

**Issue by akin04** [react-navigation/react-navigation#8994]
Hi, sorry if it's not the right place to report the issue, I'm not sure which one is.

**Current Behavior**
The tabBarIcon component is not showing (tried various element), it was rendering correctly on previous versions. But the previous versions don't render the safe area correctly on Iphone 12 series. That's why I updated to 2.10.0 which correct this issue.

This is the behaviour with version 2.10.0 of react-navigations-tabs on Iphone 11 & 12 series.
![Screenshot 2020-10-27 at 06 29 54](https://user-images.githubusercontent.com/48533607/97260809-d7e29100-181d-11eb-9cdd-253e5e486cf8.png)

This is the behaviour with version 2.9.2 of react-navigations-tabs on Iphone 12 series only.
![Screenshot 2020-10-27 at 06 35 40](https://user-images.githubusercontent.com/48533607/97261213-a61dfa00-181e-11eb-9dca-f6a3cd8d7679.png)

**Expected Behavior**
It should render this way
![Screenshot 2020-10-27 at 06 47 30](https://user-images.githubusercontent.com/48533607/97262014-4cb6ca80-1820-11eb-9df3-79834f8e04dd.png)

**How to reproduce**
Here is the code sample I have used

`navigationOptions: ({ navigation }) => ({
      tabBarLabel: 'Tab1',
      tabBarIcon: ({ tintColor }) => {
        return <MaterialCommunityIcons size={23} color={tintColor} name='map' />;
      },
    }),`

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS                | 14.1
| react-navigation               | 4.0.10
| react-navigation-stack         | 1.10.3
| react-navigation-tabs          | 2.10.0
| react-native-reanimated        | 1.3.0
| react-native-gesture-handler   | 1.5.2
| react-native-safe-area-context | 0.7.3
| react-native-screens           | ^1.0.0-alpha.23
| react-native                   | 0.61.2
| npm                | 6.13.6

Thanks.

**Comment by WilliamAlexander** [comment]
Same problem on iPhone 12 Pro

**Comment by WilliamAlexander** [comment]
I updated to the following and it now works

`"react-native-safe-area-context": "^3.1.8",
"react-navigation": "^4.4.3",
    "react-navigation-stack": "^2.10.0",
    "react-navigation-tabs": "^2.10.1",`

**Comment by akin04** [comment]
> I updated to the following and it now works
> 
> ```
>  `"react-native-safe-area-context": "^3.1.8",
> 
> "react-navigation": "^4.4.3",
> 
> "react-navigation-stack": "^2.10.0",
> 
> "react-navigation-tabs": "^2.10.1",`
> ```

Thanks, I will try this and let you know

**Comment by satya164** [comment]
Closing since you didn't provide a repro to be able to debug the issue. Please open a new issue if you have a minimal repro which I could take a look at.
