### ISSUE TITLE
 Invariant Violation: Native module cannot be null when importing MaterialTopBarNavigator

### ISSUE THREAD

**Issue by FrappaF** [react-navigation/react-navigation#9002]
**Current Behavior**

I installed the module with:

`npm install @react-navigation/material-top-tabs react-native-tab-view`

code:
````
import React from 'react'
import { createMaterialTopTabNavigator } from '@react-navigation/material-top-tabs';

import HotScreen from './HotScreen';
import RatedScreen from './RatedScreen';
import OfferScreen from './OfferScreen';

const Tab = createMaterialTopTabNavigator();

export default function HomeScreen({navigation}) {

    return(
        <Tab.Navigator>
            <Tab.Screen name="Hot" component={HotScreen}/>
            <Tab.Screen name="Most rated" component={RatedScreen}/>
            <Tab.Screen name="Offers" component={OfferScreen}/>
        </Tab.Navigator>
    );

}

````

When I run it using `react-native run-ios` I get this:

<img width="574" alt="Schermata 2020-10-30 alle 00 19 55" src="https://user-images.githubusercontent.com/34452508/97642690-178bc180-1a46-11eb-9da3-8af06ba97ed3.png">

**Your Environment**
react-native info:

System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
    Memory: 649.57 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 15.0.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.0.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.1, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 12.1/12A7403 - /usr/bin/xcodebuild
  Languages:
    Java: javac 15 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**package.json:**
"dependencies": {
    "@invertase/react-native-apple-authentication": "^2.1.0",
    "@react-native-community/async-storage": "^1.12.1",
    "@react-native-community/checkbox": "^0.5.5",
    "@react-native-community/google-signin": "^5.0.0",
    "@react-native-firebase/app": "^8.4.6",
    "@react-native-firebase/auth": "^9.3.1",
    "@react-native-firebase/database": "^7.5.12",
    "@react-native-firebase/storage": "^7.4.10",
    "@react-navigation/bottom-tabs": "^5.10.1",
    "@react-navigation/material-bottom-tabs": "^5.3.1",
    "@react-navigation/material-top-tabs": "^5.3.1",
    "@react-navigation/native": "^5.8.1",
    "@react-navigation/stack": "^5.11.0",
    "base-64": "^1.0.0",
    "firebase": "^8.0.0",
    "react": "16.13.1",
    "react-native": "0.63.3",
    "react-native-animatable": "^1.3.3",
    "react-native-device-info": "^7.0.2",
    "react-native-elements": "^3.0.0-alpha.1",
    "react-native-fbsdk": "^2.0.0",
    "react-native-gesture-handler": "^1.8.0",
    "react-native-image-picker": "^3.0.0-vnext.0",
    "react-native-image-resizer": "^1.3.0",
    "react-native-keyboard-aware-scroll-view": "^0.9.3",
    "react-native-onboarding-swiper": "^1.1.4",
    "react-native-progress": "^4.1.2",
    "react-native-safe-area-context": "^3.1.8",
    "react-native-tab-view": "^2.15.2",
    "react-native-vector-icons": "^7.1.0"
  },
  "devDependencies": {
    "@babel/core": "^7.12.3",
    "@babel/runtime": "^7.12.1",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-jest": "^26.6.1",
    "eslint": "^7.12.0",
    "jest": "^26.6.1",
    "metro-react-native-babel-preset": "^0.63.0",
    "react-test-renderer": "16.13.1"
  },
  "jest": {
    "preset": "react-native"
  },
  "rnpm": {
    "assets": [
      "./assets/fonts/"
    ]
  }

**Comment by fortezhuo** [comment]
@FrappaF 
I also had this problem before.. and solve this problem by linking podspec (for < RN 60) and run pod install

**Comment by satya164** [comment]
Closing since you didn't provide a repro to be able to debug the issue. Please open a new issue if you have a minimal repro which I could take a look at.

**Comment by marcos012** [comment]
I had this problem and i followed the documentation

[https://reactnavigation.org/docs/testing/](https://reactnavigation.org/docs/testing/)

In file `setup.js` add this line:
`jest.mock('@react-navigation/material-top-tabs');`

Worked for me.

**Comment by gotoAndBliss** [comment]
If I copy / paste this code exactly as [described here](https://snack.expo.io/?platform=android&name=Getting%20started%20%7C%20React%20Navigation&dependencies=%40expo%2Fvector-icons%40*%2C%40react-native-community%2Fmasked-view%40*%2C%40react-navigation%2Fbottom-tabs%40%5E5.8.0%2C%40react-navigation%2Fdrawer%40%5E5.9.0%2C%40react-navigation%2Fmaterial-bottom-tabs%40%5E5.2.16%2C%40react-navigation%2Fmaterial-top-tabs%40%5E5.2.16%2C%40react-navigation%2Fnative%40%5E5.7.3%2C%40react-navigation%2Fstack%40%5E5.9.0%2Creact-native-paper%40%5E4.0.1%2Creact-native-reanimated%40*%2Creact-native-safe-area-context%40*%2Creact-native-gesture-handler%40*%2Creact-native-screens%40*%2Creact-native-tab-view%40%5E2.15.1&sourceUrl=https%3A%2F%2Freactnavigation.org%2Fexamples%2F5.x%2Fmaterial-top-tab-based-navigation-minimal.js)

I get this same error on a fresh install of RN any version between `.60` and `.63`. 

I've nuked `node_modules/`, and `yarn start --reset-cache`
