### ISSUE TITLE
Deep-links params are nested in two levels of params

### ISSUE THREAD

**Issue by marcinkornek** [react-navigation/react-navigation#9006]
**Current Behavior**

Deep-links params are nested in two levels of params

Here is my linking config:
```
const linking = {
  prefixes: ['https://www.myapp.com', 'myapp:'],
  config: {
    screens: {
      MagicLinkLogin: {
        path: 'magic-login/:token',
      },
    },
  },
}
```

in screen MagicLinkLogin `token` should be available under `route.params.token` but it's not. It's under `route.params.params.token`

Here's how my routes look like:
```
// RootStack.js
[...]
const RootNavigator = () => {
 return (
   <NavigationContainer
      linking={deepLinksConfig.linking}
    >
      <RootStack.Navigator>
        <RootStack.Screen
          name="Auth"
          component={AuthStack}
          options={{
            headerShown: false,
          }}
        />
      </RootStack.Navigator>
    </NavigationContainer>
)

export default RootNavigator
```

```
// AuthStack.js

const AuthStack = () => {
  return (
    <Stack.Navigator>
      [...]
      <Stack.Screen
        name="MagicLinkLogin"
        component={MagicLinkLoginScreen}
      />
    </Stack.Navigator>
  )
}
```

**Expected Behavior**

Params from deep link should be available in `route.parms`, not in `route.params.params`

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android          |   iOS 14.1 simulator   |
| @react-navigation/native     |  5.8.1 |
| react-native           | 0.63.3        |
| node                          | v13.8.0 |
| yarn             | 1.22.0       |

**Comment by lucksp** [comment]
hi @marcinkornek did you happen to resolve this `params.params` issue? I am running into it also
