### ISSUE TITLE
app fails to bundle on react-nav/bottom-tabs package installation

### ISSUE THREAD

**Issue by juniorbuba** [react-navigation/react-navigation#9011]
**Current Behavior**
![Screenshot_2020-10-30-20-29-52-009_com abulad](https://user-images.githubusercontent.com/41841881/97753150-955ad600-1af5-11eb-94aa-b98b64f31358.png)

![Screenshot (462)](https://user-images.githubusercontent.com/41841881/97751456-a524eb00-1af2-11eb-8602-c6829ad84825.png)

**Expected Behavior**

- The application should properly build and load on the device.

**package.json**

{
  "name": " ",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "go": "npx react-native run-android",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@react-native-community/masked-view": "^0.1.6",
    "@react-native-firebase/app": "^7.0.1",
    "@react-native-firebase/database": "^7.0.1",
    "@react-native-firebase/storage": "^7.0.1",
    "@react-navigation/bottom-tabs": "^5.10.1",
    "@react-navigation/drawer": "^5.4.1",
    "@react-navigation/native": "^5.0.5",
    "@react-navigation/stack": "^5.0.5",
    "install-peerdeps": "^2.0.1",
    "jetifier": "^1.6.5",
    "react": "16.9.0",
    "react-native": "0.61.5",
    "react-native-elements": "^1.2.7",
    "react-native-gesture-handler": "^1.6.0",
    "react-native-get-random-values": "^1.4.0",
    "react-native-reanimated": "^1.7.0",
    "react-native-safe-area-context": "^0.7.3",
    "react-native-screens": "^2.2.0",
    "react-native-splash-screen": "^3.2.0",
    "react-native-vector-icons": "^6.6.0",
    "react-native-webview": "9.1.1",
    "react-native-windows": "^0.61.5",
    "react-navigation": "^4.2.2",
    "uuid": "^7.0.3"
  },
  "devDependencies": {
    "@babel/core": "^7.6.2",
    "@babel/runtime": "^7.6.2",
    "@react-native-community/eslint-config": "^0.0.5",
    "babel-jest": "^24.9.0",
    "eslint": "^6.5.1",
    "install-peers": "^1.0.3",
    "jest": "^24.9.0",
    "metro-react-native-babel-preset": "^0.56.0",
    "react-test-renderer": "16.9.0"
  },
  "jest": {
    "preset": "react-native"
  }
}

**Your Environment**

| software                      | version |
| ----------------------------- | ------- |
| node               |      12.14.1     
| npm         |    6.13.4

**Comment by satya164** [comment]
https://reactnavigation.org/docs/troubleshooting/#im-getting-syntaxerror-in-react-navigationxxxxxxtsx-or-syntaxerror-xxxreact-navigationxxxxxxtsx-unexpected-token
