### ISSUE TITLE
Setting explicit 'screen' for navigation to bottom tab stops working after first time

### ISSUE THREAD

**Issue by maxbaldrighi** [react-navigation/react-navigation#9018]
I think this issue might be cross-referenced also for `@react-navigation/stack`, since I don't exactly know what package's fault this is.

**Current Behavior**

I have a main `StackNavigator` with as children:
 - 5-tab `BottomTabNavigator`
 - one screen where I don't want to see the bottom bar (followed https://reactnavigation.org/docs/hiding-tabbar-in-screens).
On `Tab3` I have a button navigating to this out-of-tabs-screen (`navigation.navigate('OutOfTabsScreen');`), where I have another button that must take users to `Tab4` (`navigation.navigate('Tabs', { screen: 'Tab4' });`).
What currently happens:
 - navigation from `Tab3` to `OutOfTabsScreen` -> **always work**
 - navigation from `OutOfTabsScreen` to `Tab4` -> always work **THE FIRST TIME**, but, repeating the flow again, button takes to `Tab3`.

**Expected Behavior**
No matter how many times the flow is repeated button in `OutOfTabsScreen` should always take to `Tab4`.

**How to reproduce**
https://snack.expo.io/@bigmec87/stack-to-tab-navigation

**Your Environment**

| software                      | version |
| ----------------------------- | ------- |
| iOS or Android                |  both
| @react-navigation/native      |  5.8.2
| @react-navigation/bottom-tabs |  5.10.2
| react-native-screens          | ~2.10.1
| react-native                  |  0.63.3
| expo                          |  39.0.0

**Comment by satya164** [comment]
Fixed in https://github.com/react-navigation/react-navigation/commit/0945689b70d71a4b5d766c61d57009761c460bf6
