### ISSUE TITLE
Calling `navigation.navigate()` adds screen to stack, but going back and trying to return doesn't work

### ISSUE THREAD

**Issue by joshuarize** [react-navigation/react-navigation#9020]
**Current Behavior**
1. On first screen, call `navigation.navigate(route)`
2. Observe going to second screen
3. Call `goBack()` hook or enable the `headerShown` option to enable going back
4. Observe going back to first screen
5. Try to call the same `navigation.navigate(route)`
6. Observe first screen does not transition to second screen

- What code are you running and what is happening?
```js
// first screen
const handleOnButtonPress = () => {
    navigation.navigate(routeTypes.SETTINGS_STACK.name, {
      screen: routeTypes.SETTINGS_STACK.routes.UPDATE_GENDER.name,
    });
  };
```

```js
// second screen
const { goBack } = useNavigation();
const handleGoBack = () => {
  goBack()
}
```

**Expected Behavior**

Should be able to go back and forth between the two screens, presumably by just using `navigation.navigate`

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | 14
| @react-navigation/native       | 5.8.0
| @react-navigation/stack        | 5.10.0
| react-native-gesture-handler   |
| react-native-safe-area-context |
| react-native-screens           | 2.10.1
| react-native                   | sdk-39.0.3
| expo                           | 39.0.0
| node                           | 14.7.0
| npm or yarn                    | 1.22.4

**Comment by satya164** [comment]
Fixed in https://github.com/react-navigation/react-navigation/commit/0945689b70d71a4b5d766c61d57009761c460bf6

**Comment by joshuarize** [comment]
@satya164 Thanks for recognizing the issue and fixing the bug.
