### ISSUE TITLE
Header inset not working on iOS 14 iPhone 12 Pro device

### ISSUE THREAD

**Issue by snamstorm** [react-navigation/react-navigation#9025]
Top insets are not working for iOS 14 on the iPhone 12 Pro device

Works fine for iOS 14 on iPhone 11 device.

Anyone else having this issue?

![navigation](https://user-images.githubusercontent.com/10230039/98098359-30262c80-1ec9-11eb-980d-cad4b987d276.png)

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | iOS
| react-navigation               | 4.4.1
| react-navigation-stack         | 1.10.3
| react-navigation-tabs          | 2.10.1
| react-navigation-drawer        | 1.4.0
| react-native-reanimated        | 1.4.0
| react-native-gesture-handler   | 1.8.0
| react-native-safe-area-context | 3.1.8
| react-native-screens           | 2.11.0
| react-native                   | 0.63.3
| node                           | v13.11.0
| npm or yarn                    | 6.13.7

**Comment by snamstorm** [comment]
> The versions mentioned in the issue for the following packages differ from the latest versions on npm:
> 
> * `react-navigation` (found: `4.4.1`, latest: `4.4.3`)
> * `react-navigation-stack` (found: `1.10.3`, latest: `2.10.0`)
> * `react-navigation-drawer` (found: `1.4.0`, latest: `2.6.0`)
> 
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?

Upgrading the above libs fixed the issue

**Comment by whiteHatCip** [comment]
I am actually having this issue with these packages versions

"@react-navigation/drawer": "^5.11.2",
"@react-navigation/native": "^5.8.9",
"@react-navigation/stack": "^5.12.6"

**Comment by xclidongbo** [comment]
This is happening with version 3.13.0 too

**Comment by Juliocbr** [comment]
same issue with:
"@react-navigation/bottom-tabs": "^5.11.0",
"@react-navigation/material-top-tabs": "^5.3.9",
"@react-navigation/native": "^5.8.7",
"@react-navigation/stack": "^5.12.5",
