### ISSUE TITLE
override backswipe behaviour in ios and android

### ISSUE THREAD

**Issue by rawatnaresh** [react-navigation/react-navigation#9027]
Is there any way to override back swipe behavior in ios and android? 

**Current Behavior**

Let's say I've 3 Screens A, B, and C. Users can navigate from `A->B->C` but they cannot navigate from `C->B`. when they press `Back Button` on `Screen C`, I'm navigating them to `Screen A` which is working fine. But they can still navigate to `screen B` by doing the back swipe which is not the expected behavior. 

**Expected Behavior**

I want the back button and back swipe to work in the same way.

**How to reproduce**
https://snack.expo.io/igB7RQcd_

![Expo (1)](https://user-images.githubusercontent.com/29520305/98325916-092a4080-2018-11eb-94e4-378f3515911c.GIF)

Also tried to add `backHandler` to screen `C` but it's exiting the app on back swipe

```
useFocusEffect(
    React.useCallback(() => {
      const onBackPress = () => {
        navigation.navigate('A')
      };

      BackHandler.addEventListener('hardwareBackPress', onBackPress);

      return () =>
        BackHandler.removeEventListener('hardwareBackPress', onBackPress);
    }, [navigation])
  );
```

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |both
| @react-navigation/native       |^5.7.3
| @react-navigation/stack        |^5.9.0
| react-native-gesture-handler   |
| react-native-safe-area-context |
| react-native-screens           |~2.10.1
| react-native                   |
| expo                           |39.0.0
| node                           |
| npm or yarn                    |

**Comment by rawatnaresh** [comment]
> The versions mentioned in the issue for the following packages differ from the latest versions on npm:
> 
>     * `@react-navigation/native` (found: `5.7.3`, latest: `5.8.6`)
> 
>     * `@react-navigation/stack` (found: `5.9.0`, latest: `5.12.3`)
> 
> 
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?

yes !

**Comment by rawatnaresh** [comment]
I can override android back swipe gestures by overriding `hardwareBackPress` . just forgot to return `true` after navigation.

```js
useFocusEffect(
    React.useCallback(() => {
      const onBackPress = () => {
        navigation.navigate('A');
        return true; // <--- this was missing
      };

      BackHandler.addEventListener('hardwareBackPress', onBackPress);

      return () =>
        BackHandler.removeEventListener('hardwareBackPress', onBackPress);
    }, [navigation])
  );

```
But still confused about overriding back swipe gestures in IOS.

**Comment by Joshandrews43** [comment]
+1

**Comment by kapobajza** [comment]
For anyone still wondering how to override the gesture back handler on iOS, here's how you can do it:

```
useEffect(() => {
  const gestureEndListener = () => {
    console.log('iOS back gesture ended');
  };

  // You can also use the 'gestureStart' or 'gestureCancel' events
  navigation.addListener('gestureEnd', gestureEndListener);

  return () => {
    navigation.removeListener('gestureEnd', gestureEndListener);
  };
}, []);
```

**Comment by Fernando922** [comment]
Thanks @kapobajza! You saved my life today!

**Comment by yagosenhorini** [comment]
@kapobajza thanks bro, it works nicely!

**Comment by vincent-paing** [comment]
| At first, you may be inclined to.....use useEffect to add the listener. This approach will not work - learn more about this in [navigation lifecycle](https://reactnavigation.org/docs/navigation-lifecycle).

@kapobajza Shouldn't we be using `useFocusEffect` instead of `useEffect` according to [the doc?](https://reactnavigation.org/docs/custom-android-back-button-handling/)

**Comment by boblitex** [comment]
> For anyone still wondering how to override the gesture back handler on iOS, here's how you can do it:
> 
> ```
> useEffect(() => {
>   const gestureEndListener = () => {
>     console.log('iOS back gesture ended');
>   };
> 
>   // You can also use the 'gestureStart' or 'gestureCancel' events
>   navigation.addListener('gestureEnd', gestureEndListener);
> 
>   return () => {
>     navigation.removeListener('gestureEnd', gestureEndListener);
>   };
> }, []);
> ```
> 
> I've also made a small hook which can be used for both the Android back handler and iOS gesture back at the same time:
> 
> ```
> import { ParamListBase, useNavigation } from '@react-navigation/native';
> import { StackNavigationProp } from '@react-navigation/stack';
> import { DependencyList, useEffect } from 'react';
> import { BackHandler } from 'react-native';
> 
> function useGoBackHandler<
>   ParamList extends ParamListBase,
>   RouteName extends keyof ParamList & string
> >(onGoBackCallback: () => boolean | null | undefined, deps?: DependencyList) {
>   const navigation = useNavigation<StackNavigationProp<ParamList, RouteName>>();
> 
>   useEffect(() => {
>     BackHandler.addEventListener('hardwareBackPress', onGoBackCallback);
>     navigation.addListener('gestureEnd', onGoBackCallback);
> 
>     return () => {
>       BackHandler.removeEventListener('hardwareBackPress', onGoBackCallback);
>       navigation.removeListener('gestureEnd', onGoBackCallback);
>     };
>   }, [navigation, onGoBackCallback, deps]);
> }
> ```
> 
> You can use it like this:
> 
> ```
> useGoBackHandler(() => {
>   console.log('Android hardware back button pressed and iOS back gesture ended');
>   return true;
> }, []);
> ```

is there a version when the `gestureEnd` event was introduced? can't seem to find it in v5.9.8

**Comment by lucasalvesa** [comment]
I'm using:

`react-native-gesture-handler: “1.10.3"`
`@react-navigation/native: “6.0.2"`
`@react-navigation/native-stack: “6.2.2"`

and I guess this issue still exists in these versions of these packages. 
This workaround `navigation.removeListener('gestureEnd', ...)` was not enough to solve my problem.

**Comment by dlehddnjs** [comment]
Error `gestureStart is not assignable` is occurred.

**Comment by abhimangalmsrently** [comment]
> gestureEnd

any fix found ?

**Comment by wuvinotre** [comment]
At first the 'gestureEnd' event doesn't exist in the Navigator Native Stack, only in the Stack. That's why react native can't find this event.

**Comment by bennkingy** [comment]
How do we make this also work with the react native back button?

**Comment by van8tka** [comment]
Hi! Anyone find solutions?

**Comment by satya164** [comment]
You should be using `navigation.replace` to achieve such behavior instead of overriding back button.

Overriding swipe gesture is not possible in native stack. If you're using JS stack, you can use https://reactnavigation.org/docs/preventing-going-back/

**Comment by van8tka** [comment]
> You should be using `navigation.replace` to achieve such behavior instead of overriding back button.
> 
> Overriding swipe gesture is not possible in native stack. If you're using JS stack, you can use https://reactnavigation.org/docs/preventing-going-back/

but it can't work for me :( 

I found a temporary solution... using options={{ gestureEnabled: false }} in   Stack.Screen

and in screen 
const panResponder = useRef(
    PanResponder.create({
      onStartShouldSetPanResponder: () => true,
      onPanResponderEnd: (evt, gestureState) => {
        // Check if the swipe gesture is towards the right (positive dx value)
        if (gestureState.dx > 50) {
          // Navigate to a specific screen when swipe gesture occurs
          navigation.navigate('OtherScreen');
        }
      },
    })
  ).current;
  
    return (
    <View
      style={{ flex: 1 }}
      {...panResponder.panHandlers}
    >
      {/* Screen content */}
    </View>
  );

**Comment by hotaryuzaki** [comment]
> > You should be using `navigation.replace` to achieve such behavior instead of overriding back button.
> > Overriding swipe gesture is not possible in native stack. If you're using JS stack, you can use https://reactnavigation.org/docs/preventing-going-back/
> 
> but it can't work for me :(
> 
> I found a temporary solution... using options={{ gestureEnabled: false }} in Stack.Screen
> 
> and in screen
> 
> ```
> const panResponder = useRef(
>     PanResponder.create({
>       onStartShouldSetPanResponder: () => true,
>       onPanResponderEnd: (evt, gestureState) => {
>         // Check if the swipe gesture is towards the right (positive dx value)
>         if (gestureState.dx > 50) {
>           // Navigate to a specific screen when swipe gesture occurs
>           navigation.navigate('OtherScreen');
>         }
>       },
>     })
>   ).current;
>   
>     return (
>     <View
>       style={{ flex: 1 }}
>       {...panResponder.panHandlers}
>     >
>       {/* Screen content */}
>     </View>
>   );
> ```

it works, but the problem is that it will trigger even if the user swipes not from the edge of the screen

**Comment by manuelGainza** [comment]
Hi! Anyone find solutions?
