### ISSUE TITLE
Tab content does not render when used with react-native-paper version 4.3.0

### ISSUE THREAD

**Issue by Kilowhisky** [react-navigation/react-navigation#9028]
**Current Behavior**

Not sure if this is a bug in the paper or this plugin. When this plugin is used with `react-native-paper` version `4.3.0` the tab content does not render in web view. If you drop down to version `4.2.0` it renders just fine. 

**Expected Behavior**

It should render with the updated paper framework.

**How to reproduce**

The snack that is presented on this plugins documentation shows the issue.  Change to web view and see that it does not render, lock `react-native-paper` version to 4.2.0 and see that it instantly starts rendering. 

[Link To Snack](https://snack.expo.io/?platform=android&name=Getting%20started%20%7C%20React%20Navigation&dependencies=%40react-native-community%2Fmasked-view%40*%2C%40react-navigation%2Fbottom-tabs%40%5E5.8.0%2C%40react-navigation%2Fdrawer%40%5E5.9.0%2C%40react-navigation%2Fmaterial-bottom-tabs%40%5E5.2.16%2C%40react-navigation%2Fmaterial-top-tabs%40%5E5.2.16%2C%40react-navigation%2Fnative%40%5E5.7.3%2C%40react-navigation%2Fstack%40%5E5.9.0%2Creact-native-paper%40%5E4.0.1%2Creact-native-reanimated%40*%2Creact-native-safe-area-context%40*%2Creact-native-screens%40*%2Creact-native-tab-view%40%5E2.15.1&sourceUrl=https%3A%2F%2Freactnavigation.org%2Fexamples%2F5.x%2Fmaterial-tab-based-navigation-minimal.js)

**Your Environment**

My environment doesn't matter, its on the documentation sample.

**Comment by satya164** [comment]
This should be fixed in latest version of react-native-paper
