### ISSUE TITLE
Getting error "Attempted import error: 'shouldUseActivityState' is not exported from 'react-native-screens'."

### ISSUE THREAD

**Issue by allandallopez** [react-navigation/react-navigation#9035]
**Current Behavior**

Im new in react native , then im triying to build project web and apps, using react-native-web. And there is no problem, until when im installing @react-navigation/bottom-tabs for bottom navigator. In mobile app is fine, but when running web app using "react-app-rewired start" is getting error like this  :
-  
<img width="1031" alt="Screen Shot 2020-11-07 at 22 45 34" src="https://user-images.githubusercontent.com/45220508/98445597-09772880-214b-11eb-9510-3980fc836cc5.png">

**Expected Behavior**

**How to reproduce**

and btw, i am using different way for routing app mobile and web. APP using react navigation and for web using react router. 

<img width="565" alt="Screen Shot 2020-11-07 at 22 46 58" src="https://user-images.githubusercontent.com/45220508/98445651-56f39580-214b-11eb-9fef-e29632f8055b.png">

<img width="565" alt="Screen Shot 2020-11-07 at 22 46 58" src="https://user-images.githubusercontent.com/45220508/98445675-738fcd80-214b-11eb-8722-2fa1afc90234.png">

**Your Environment**

| software                      | version |
| macOS Mojave | 10.14.4 |
| iOS and Android                |
| @react-navigation/native      |
| @react-navigation/bottom-tabs |
|@react-native-web |
| react-native-screens          |
| react-native                  |
| node                          |
|  yarn                   |

**Comment by satya164** [comment]
https://github.com/react-navigation/react-navigation/issues/8993

**Comment by ianmartorell** [comment]
@satya164 The comment you linked explains how to solve it for CRA, but I (and I believe @allandallopez too) am using [Expo Web](https://docs.expo.io/workflow/web/). Expo already uses `babel-loader` through `babel-preset-expo` I believe, so not sure how to go about making the warning go away. Thanks :)

**Comment by satya164** [comment]
The issue is about build failure. A warning won't fail your build and there's no way to avoid it (afaik), so you'll have to live with it.

**Comment by ianmartorell** [comment]
😢

**Comment by woodcockjosh** [comment]
out of the 100+ plugins I'm using for react-native they all seem to avoid warnings, yet in this case it is "unavoidable". Sound like a poor excuse to me. If you're willing to accept a PR to resolve this I would be happy to fix this for you.
