### ISSUE TITLE
Property 'push' does not exist on type 'NavigationProp'

### ISSUE THREAD

**Issue by AliRezaBeigy** [react-navigation/react-navigation#9037]
The push function doesn't exist on return type of useNavigate Hook but it's work

```TS2339: Property 'push' does not exist on type 'NavigationProp  , string, Readonly{ key: string; index: number; routeNames: string[]; history?: unknown[] | undefined; routes: NavigationRoute  , string>[]; type: string; stale: false; }>, {}, {}>'.```

Sample Code:
```ts
import {useNavigation} from '@react-navigation/native';

export default function Component() {
  const navigation = useNavigation();
  return <Pressable onPress={() => navigation.push('Heh')}/>
}
```

package.json:
```json
"@react-navigation/native": "^5.8.6"
````

**Comment by troublediehard** [comment]
Hi there, I had a similar issue and found a solution in docs https://reactnavigation.org/docs/typescript/#combining-navigation-props. So basically we need to define that we are using stack navigation props. Something like 
```
const navigation = useNavigation<StackNavigationProp<any>>();
```

**Comment by MortezaNajafian** [comment]
> Hi there, I had a similar issue and found a solution in docs https://reactnavigation.org/docs/typescript/#combining-navigation-props. So basically we need to define that we are using stack navigation props. Something like
> 
> ```
> const navigation = useNavigation<StackNavigationProp<any>>();
> ```

you can also use this line if there are not StackNavigationProp

`  const navigation = useNavigation<NativeStackNavigationProp<any>>();
`

**Comment by buuhvprojects** [comment]
> useNavigation<StackNavigationProp<any>>()

this solved to me

**Comment by ivankdev** [comment]
problem with setOptions with this solution

**Comment by saintyusuf** [comment]
> Hi there, I had a similar issue and found a solution in docs https://reactnavigation.org/docs/typescript/#combining-navigation-props. So basically we need to define that we are using stack navigation props. Something like
> 
> ```
> const navigation = useNavigation<StackNavigationProp<any>>();
> ```

Thanks bro! You are a life saver.
By the way, I think the type name has changed and it's called `NativeStackNavigationProp` now.

So basically, you guys need to use it just like this:
```
import { NativeStackNavigationProp } from "@react-navigation/native-stack"

const yourComponent = () => {
  const navigation = useNavigation<NativeStackNavigationProp<any>>()
}
```
