### ISSUE TITLE
[BUG] Slide up to the previous page

### ISSUE THREAD

**Issue by MonchiLin** [react-navigation/react-navigation#9043]
**Current Behavior**

I used react-navigation and react-native-web and expo, chrome86

Slide up to the previous page.

gif: https://ibb.co/ngWNyS4

**Expected Behavior**

Do not display the previous page

**How to reproduce**

sorry, I can't reproduce on new projects

**Your Environment**
    
    "@react-navigation/bottom-tabs": "^5.10.6",
    "@react-navigation/native": "^5.8.6",
    "@react-navigation/stack": "^5.12.3",
    "expo": "~39.0.4",

**Comment by MonchiLin** [comment]
This problem still exists when I upgrade to the following version
```
    "@react-navigation/bottom-tabs": "^5.10.7",
    "@react-navigation/native": "^5.8.7",
    "@react-navigation/stack": "^5.12.4",

```

**Comment by MonchiLin** [comment]
Any progress?

**Comment by MonchiLin** [comment]
> Hey! Thanks for opening the issue. Can you provide a [minimal repro](https://stackoverflow.com/help/minimal-reproducible-example) which demonstrates the issue? Posting a snippet of your code in the issue is useful, but it's not usually straightforward to run. A repro will help us debug the issue faster. Please try to keep the repro as small as possible.
> 
> The easiest way to provide a repro is on [snack.expo.io](https://snack.expo.io). If it's not possible to repro it on [snack.expo.io](https://snack.expo.io), then please provide the repro in a GitHub repository.

sorry 

Unable to provide reproducibility, because my project is too complicated, the project has already progressed to the later stage when I discovered this problem

**Comment by satya164** [comment]
It's impossible to debug for us without a repro.

**Comment by satya164** [comment]
Closing since you haven't provided a repro to debug the issue. If you manage to make a repro, please open a new issue with it and someone will take a look at it when possible.
