### ISSUE TITLE
undefined is not an object (evaluating 'navigation.navigate')

### ISSUE THREAD

**Issue by CharlotteRdn** [react-navigation/react-navigation#9044]
I have a very simple functional component for observing a sales order list. I would like that by clicking on this list, I will go to the detail page of the order in question.

I don't understand why I can't redirect using ***'navigation.navigate('OrderDetails')}'***

But I get 

> undefined is not an object (evaluating 'navigation.navigate')

It happens ONLY in that particular screen... the others are working fine. so i wandered if it's not due to the syntax in listitem 
Can anybody try to help me with this ? Thanks a lot for time and explanations.

    import * as React from 'react';
    import { View } from 'react-native';
    import { ListItem, Icon } from 'react-native-elements'
    
    const list = [
        
          {
            title: 'Commande 1',
            icon: 'av-timer'
        },
        {
            title: 'Commande 2',
            icon: 'flight-takeoff'
        },
          {
            title: 'Commande 3',
            icon: 'av-timer'
        },
        {
            title: 'Commande 4',
            icon: 'flight-takeoff'
        },
          {
            title: 'Commande 5',
            icon: 'av-timer'
        },
        {
            title: 'Commande 6',
            icon: 'flight-takeoff'
        },
        
        ]
    
    
    
    export default function Terminated({navigation}) {
    
        return (
    <View>
      {
        list.map((item, i) => (
          <ListItem key={i} bottomDivider
                    button onPress={() => navigation.navigate('OrderDetails')}>
            <Icon name={item.icon} />
            <ListItem.Content>
              <ListItem.Title>{item.title}</ListItem.Title>
            </ListItem.Content>
            <ListItem.Chevron />
          </ListItem>
        ))
      }
    </View>
        );
      }

Navigation : 

    import React from 'react';
    import { Image } from 'react-native';
    import { createBottomTabNavigator } from '@react-navigation/bottom-tabs';
    import { createStackNavigator} from "@react-navigation/stack";
    import { NavigationContainer } from '@react-navigation/native';
    import Authentication from '../../Screens/Authentication';
    import Activities from '../../Screens/Activities';
    import Login from '../../Screens/Authentication/Login';
    import Signup from '../../Screens/Authentication/Signup';
    import Tools from '../../Screens/Tools';
    import Dashboard from '../../Screens/Dashboard';
    import Orders from '../../Screens/Orders';
    import Terminated from '../../Screens/Orders/Terminated';
    import Ongoing from '../../Screens/Orders/Ongoing';
    import OrderDetails from '../../Screens/Orders/OrderDetails';
    import Settings from '../../Screens/Settings';
    import Scan from '../../Screens/Tools/Scan';
    import Products from '../../Screens/Tools/Products';
    import Tickets from '../../Screens/Tools/Tickets';
    import Welcome from '../../Screens/Welcome';
    import i18n from '../../src/i18n';
    import styles from '../../assets/styles';
    
    const Tab = createBottomTabNavigator();
    const Stack = createStackNavigator();
    
    function ScreenNavigator() {
      return(
        <Stack.Navigator>       
          <Stack.Screen name = 'Orders' component = {Orders}/> 
          <Stack.Screen name = 'Authentication' component = {Authentication}/>  
          <Stack.Screen name = 'Activities' component = {Activities}/>  
          <Stack.Screen name = 'Login' component = {Login}/>
          <Stack.Screen name = 'Signup' component = {Signup}/>
          <Stack.Screen name = 'Tools' component = {Tools}/>
          <Stack.Screen name = 'Scan' component = {Scan}/>      
          <Stack.Screen name = 'Ongoing' component = {Ongoing}/>
          <Stack.Screen name = 'Terminated' component = {Terminated}/>
          <Stack.Screen name = 'OrderDetails' component = {OrderDetails}/> 
          <Stack.Screen name = 'Products' component = {Products}/>      
          <Stack.Screen name = 'Tickets' component = {Tickets}/>
          <Stack.Screen name = 'Dashboard' component = {Dashboard}/>
          <Stack.Screen name = 'Settings' component = {Settings}/>
          <Stack.Screen name = 'Welcome' component = {Welcome}/>
        </Stack.Navigator>
      )
    }
    
    export default function AppNavigation() {
      return (
        <NavigationContainer>
          <Tab.Navigator initialRouteName="Orders"
                         tabBarOptions={{activeTintColor: '#F78400'}}>
            <Tab.Screen
              name={i18n.t("app.auth")}
              component={ScreenNavigator}
              options={{
                  tabBarIcon: ({ focused, horizontal, tintColor }) => {
                    return (
                      <Image
                        source={require("../../assets/images/authentication.png")}
                        style={styles.icon}
                      />
                    );
                  }
              }}
            />
            <Tab.Screen
              name={i18n.t("app.dash")}
              component={Dashboard}
              options={{
                tabBarIcon: ({ focused, horizontal, tintColor }) => {
                  return (
                    <Image
                      source={require("../../assets/images/dashboard.png")}
                      style={styles.icon}
                    />
                  );
                }
              }}
            />
            <Tab.Screen
              name={i18n.t("app.tools")}
              component={Tools}
              options={{
                tabBarIcon: ({ focused, horizontal, tintColor }) => {
                  return (
                    <Image
                      source={require("../../assets/images/tools.png")}
                      style={styles.icon}
                    />
                  );
                }
              }}
            />
            <Tab.Screen
              name={i18n.t("app.settings")}
              component={Settings}
              options={{
                tabBarIcon: ({ focused, horizontal, tintColor }) => {
                  return (
                    <Image
                      source={require("../../assets/images/settings.png")}
                      style={styles.icon}
                    />
                  );
                }
              }}
            />
          </Tab.Navigator>
        </NavigationContainer>
      )
    }

I tried this way : 

    import * as React from 'react';
    import { View } from 'react-native';
    import { ListItem, Icon } from 'react-native-elements'
    import { useNavigation } from '@react-navigation/native';
    
    
    const list = [
        
          {
            title: 'Commande 1',
            icon: 'av-timer'
        },
        {
            title: 'Commande 2',
            icon: 'flight-takeoff'
        },
          {
            title: 'Commande 3',
            icon: 'av-timer'
        },
        {
            title: 'Commande 4',
            icon: 'flight-takeoff'
        },
          {
            title: 'Commande 5',
            icon: 'av-timer'
        },
        {
            title: 'Commande 6',
            icon: 'flight-takeoff'
        },
        
        ]
    
    export default function Completed() {
    const navigation = useNavigation(); 
    
        return (
          <View>
            {
              list.map((item, i) => (
                <ListItem key={i} 
                          bottomDivider
                          onPress={() => navigation.navigate('Details')}>
                    <Icon name={item.icon} />
                    <ListItem.Content>
                      <ListItem.Title>{item.title}</ListItem.Title>
                    </ListItem.Content>
                  <ListItem.Chevron />
                </ListItem>           
              ))
            }
          </View>
        );
      }

But now the error is : 

> ReferenceError: Can't find variable: useNavigation

I truly don't understand...

Version of packages :     
**"@react-navigation/native": "^5.8.1",  "@react-navigation/stack": "^5.11.0",**

**Comment by CharlotteRdn** [comment]
I've upgrading, but I still get the same error message

**Comment by satya164** [comment]
Closing since you haven't provided a repro to debug the issue. If you manage to make a repro, please open a new issue with it and someone will take a look at it when possible.
