### ISSUE TITLE
navigation.push / pop doesn't work in Drawer

### ISSUE THREAD

**Issue by exentrich** [react-navigation/react-navigation#9048]
This issue have already been created few years ago and closed eventually https://github.com/react-navigation/react-navigation/issues/4793.
Many people told that this is expected behaviour due to Drawer is not a Stack. But in latest update (`5.11.0`) Drawer started support `header` option and now `options` almost identical to usual stack navigator.
This makes confusion honestly. Drawer looks very similar to Stack and I expect to use usual `push` and `pop` methods. The `navigate` method already supported, why not to support all other?

**Comment by satya164** [comment]
Just because drawer has a header, it doesn't make it a [stack](https://en.wikipedia.org/wiki/Stack_(abstract_data_type)). Besides, Stack Navigator has way more things than just header.
