### ISSUE TITLE
TabBarOptions() won't allow me to set the height with a parameter

### ISSUE THREAD

**Issue by chai86** [react-navigation/react-navigation#9050]
@satya164 I have global variables set in a globals.js file which work perfectly and get set in my App.js file fine. e.g.

        global.App_paddingLeft = 3,
        global.App_BottomTabBarHeight = '8%',

In my App.js i do this:

    //Tabs across the bottom of the screen
    const MainScreenTabNavigator = createBottomTabNavigator(
      {
        HomeStack,
        
        OtherStack,
    
      },
      {
    
        tabBarOptions: {
    
          activeTintColor: 'orange',
          inactiveTintColor: 'black', //white 
          style: {
            backgroundColor: '#ff8278',
            height: global.App_BottomTabBarHeight   // DOESN'T WORK but manually typing  '8%' or 0.08 does
          },
          indicatorStyle: {
            backgroundColor: 'black'
          },
          showLabel: false
        },
        
      }
      
    );

The height wont set with the variable `global.App_BottomTabBarHeight = '8%'`. This `global.App_BottomTabBarHeight` **definitely** passes the correct value of '8%' through to the App.js file as i've console.logged it. 

I've also tried doing this:
 `height: Dimensions.get('window').height * global.App_BottomTabBarHeight`, where `global.App_BottomTabBarHeight = 0.08`, but still nothing

Why can't i set the height to '8%' ?

If i manually type `height: '8%'` it works fine. Strange

**Comment by chai86** [comment]
?

**Comment by satya164** [comment]
https://github.com/react-navigation/react-navigation/issues/9068#issuecomment-735026309
