### ISSUE TITLE
I have updated react navigation v4 to v5 and many things stopped working like react native Alert, react native community dateTime Picker on iOS, react native Platform some times

### ISSUE THREAD

**Issue by georgeMorales** [react-navigation/react-navigation#9052]
React Navigation 4
`"dependencies": {
        "@expo/vector-icons": "^10.0.0",
        "@ptomasroos/react-native-multi-slider": "^1.0.0",
        "@react-native-community/datetimepicker": "3.0.0",
        "@react-native-community/masked-view": "0.1.10",
        "babel-plugin-transform-remove-console": "^6.9.4",
        "date-fns": "^1.29.0",
        "expo": "^39.0.0",
        "expo-apple-authentication": "~2.2.1",
        "expo-asset": "~8.2.0",
        "expo-av": "~8.6.0",
        "expo-blur": "~8.2.0",
        "expo-camera": "~9.0.0",
        "expo-facebook": "~9.0.0",
        "expo-firebase-analytics": "~2.5.0",
        "expo-font": "~8.3.0",
        "expo-google-app-auth": "^8.1.3",
        "expo-google-sign-in": "~8.3.0",
        "expo-image-manipulator": "~8.3.0",
        "expo-image-picker": "~9.1.0",
        "expo-linear-gradient": "~8.3.0",
        "expo-linking": "^1.0.1",
        "expo-localization": "~9.0.0",
        "firebase": "7.9.0",
        "geofirestore": "^3.3.1",
        "i18next": "^19.0.0",
        "lodash": "^4.17.11",
        "moment": "^2.22.2",
        "prop-types": "^15.6.2",
        "react": "16.13.1",
        "react-devtools": "^3.2.3",
        "react-native": "https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz",
        "react-native-card-stack-swiper": "1.2.5",
        "react-native-countdown-component": "^2.7.1",
        "react-native-datepicker": "^1.7.2",
        "react-native-expo-image-cache": "^4.1.0",
        "react-native-gesture-handler": "~1.7.0",
        "react-native-gifted-chat": "0.16.3",
        "react-native-google-autocomplete": "^0.1.9",
        "react-native-image-header-scroll-view": "^0.10.2",
        "react-native-keyboard-spacer": "^0.4.1",
        "react-native-maps": "0.27.1",
        "react-native-modal": "11.5.6",
        "react-native-modal-datetime-picker": "^6.0.0",
        "react-native-modal-selector": "git+https://github.com/peacechen/react-native-modal-selector.git",
        "react-native-neomorph-shadows": "0.0.8",
        "react-native-picker-select": "^6.3.3",
        "react-native-ratings": "7.3.0",
        "react-native-reanimated": "~1.13.0",
        "react-native-responsive-screen": "^1.4.1",
        "react-native-safe-area-context": "3.1.4",
        "react-native-screens": "~2.10.1",
        "react-native-sectioned-multi-select": "^0.6.7",
        "react-native-shadow": "^1.2.2",
        "react-native-simple-radio-button": "^2.7.4",
        "react-native-snap-carousel": "3.9.1",
        "react-native-svg": "12.1.0",
        "react-native-webview": "10.7.0",
        "react-navigation": "^4.0.10",
        "react-navigation-backhandler": "^1.3.2",
        "react-navigation-stack": "^2.1.0",
        "react-navigation-tabs": "^2.7.0",
        "react-redux": "6.0.1",
        "react-redux-firebase": "3.7.0",
        "redux": "4.0.5",
        "redux-enhancer-react-native-appstate": "^0.3.1",
        "redux-firestore": "0.14.0",
        "redux-form": "^8.2.6",
        "redux-logger": "^3.0.6",
        "redux-persist": "^6.0.0",
        "redux-thunk": "^2.3.0",
        "reselect": "^4.0.0",
        "uuid": "^3.3.2",
        "why-did-you-update": "^1.0.6"
    },`

React Navigation 5

`"dependencies": {
        "@expo/vector-icons": "^10.0.0",
        "@ptomasroos/react-native-multi-slider": "^1.0.0",
        "@react-native-community/datetimepicker": "3.0.0",
        "@react-native-community/masked-view": "0.1.10",
        "@react-navigation/material-top-tabs": "^5.3.7",
        "@react-navigation/native": "^5.8.7",
        "@react-navigation/stack": "^5.12.4",
        "babel-plugin-transform-remove-console": "^6.9.4",
        "date-fns": "^1.29.0",
        "expo": "^39.0.0",
        "expo-apple-authentication": "~2.2.1",
        "expo-asset": "~8.2.0",
        "expo-av": "~8.6.0",
        "expo-blur": "~8.2.0",
        "expo-camera": "~9.0.0",
        "expo-facebook": "~9.0.0",
        "expo-firebase-analytics": "~2.5.0",
        "expo-font": "~8.3.0",
        "expo-google-app-auth": "^8.1.3",
        "expo-google-sign-in": "~8.3.0",
        "expo-image-manipulator": "~8.3.0",
        "expo-image-picker": "~9.1.0",
        "expo-linear-gradient": "~8.3.0",
        "expo-linking": "^1.0.1",
        "expo-localization": "~9.0.0",
        "firebase": "7.9.0",
        "geofirestore": "^3.3.1",
        "i18next": "^19.0.0",
        "lodash": "^4.17.11",
        "moment": "^2.22.2",
        "prop-types": "^15.6.2",
        "react": "16.13.1",
        "react-devtools": "^3.2.3",
        "react-native": "https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz",
        "react-native-card-stack-swiper": "1.2.5",
        "react-native-countdown-component": "^2.7.1",
        "react-native-datepicker": "^1.7.2",
        "react-native-expo-image-cache": "^4.1.0",
        "react-native-gesture-handler": "~1.7.0",
        "react-native-gifted-chat": "0.16.3",
        "react-native-google-autocomplete": "^0.1.9",
        "react-native-image-header-scroll-view": "^0.10.2",
        "react-native-keyboard-spacer": "^0.4.1",
        "react-native-maps": "0.27.1",
        "react-native-modal": "11.5.6",
        "react-native-modal-datetime-picker": "^6.0.0",
        "react-native-modal-selector": "git+https://github.com/peacechen/react-native-modal-selector.git",
        "react-native-neomorph-shadows": "0.0.8",
        "react-native-picker-select": "^6.3.3",
        "react-native-ratings": "7.3.0",
        "react-native-reanimated": "~1.13.0",
        "react-native-responsive-screen": "^1.4.1",
        "react-native-safe-area-context": "3.1.4",
        "react-native-screens": "~2.10.1",
        "react-native-sectioned-multi-select": "^0.6.7",
        "react-native-shadow": "^1.2.2",
        "react-native-simple-radio-button": "^2.7.4",
        "react-native-snap-carousel": "3.9.1",
        "react-native-svg": "12.1.0",
        "react-native-tab-view": "^2.15.2",
        "react-native-webview": "10.7.0",
        "react-navigation-backhandler": "^2.0.0",
        "react-redux": "6.0.1",
        "react-redux-firebase": "3.7.0",
        "redux": "4.0.5",
        "redux-enhancer-react-native-appstate": "^0.3.1",
        "redux-firestore": "0.14.0",
        "redux-form": "^8.2.6",
        "redux-logger": "^3.0.6",
        "redux-persist": "^6.0.0",
        "redux-thunk": "^2.3.0",
        "reselect": "^4.0.0",
        "uuid": "^3.3.2",
        "why-did-you-update": "^1.0.6"
    },`

I have updated react navigation v4 to v5, I just put the two packages.json, the only thing that differs is that one has the v4 navigation and the other has the leatest v5, I have seen that many things had to be changed such as the way to pass parameters route.params vs navigation.state.params and I understand those changes. What I do not understand is that Alert from react native does not work both on iOS and Android, datetime picker works fine on Android but not on iOS and react native Platform sometimes returns the correct value and other times always false. With the configuration with React Native 4 these problems are not there and everything works perfectly.
What can happen?

**Comment by georgeMorales** [comment]
Verified, still not working
@react-navigation/material-top-tabs (5.3.9)
@react-navigation/native (5.8.9)
@react-navigation/stack (5.12.6)

**Comment by georgeMorales** [comment]
A little test project to check that Alert doesn't work and Platform sometimes works, sometimes doesn't work.
https://github.com/georgeMorales/react-navigation5-test

**Comment by georgeMorales** [comment]
Could these bugs be fixed?

**Comment by satya164** [comment]
> A little test project to check that Alert doesn't work and Platform sometimes works, sometimes doesn't work

These are React Native components and modules. It's impossible for React Navigation to affect anything regarding them.

I cloned your test project and things are breaking because you are assigning `Platform.OS` to `false` here https://github.com/georgeMorales/react-navigation5-test/blob/310500c956456790af2e3dd2c1ba170c29e0eed6/app/navigation/RootNav.js#L21

You should use a static type checker such as TypeScript which will catch these kind of issues.
