### ISSUE TITLE
Double headers when using nested navigators on Android

### ISSUE THREAD

**Issue by nimabrownlee** [react-navigation/react-navigation#9054]
**Current Behavior**

- RootNavigator (StackNavigator)
  - MainScreen
    - StackNavigator (StackNavigator)
       - RootScreen
       - TestScreen

Here is a screenshot on the issue: https://i.imgur.com/rIzt3NP.png

**Expected Behavior**

Child header should override Parent header. Keep in mind that this is working complete fine on iOS. And yes I've looked at the other issues and all of them hide the Child header instead. I dont want to do that.

**How to reproduce**

https://snack.expo.io/ENkEtnR8I

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Android
| @react-navigation/native       | 5.7.6
| @react-navigation/stack        | 5.9.3
| react-native-gesture-handler   | 1.7.0
| react-native-safe-area-context | 3.1.4
| react-native-screens           | 2.10.1
| react-native                   | 0.63.3
| expo                           | 39.0.2
| node                           | 12+
| npm or yarn                    | yarn

**Comment by nimabrownlee** [comment]
Yes the issue still persists after upgrading.

**Comment by rafaelsevla** [comment]
I am with same issue

**Comment by satya164** [comment]
You have opened an issue by mentioning `@react-navigation/stack` version while sharing a repro regarding `react-native-screens/native-stack`.

As mentioned in the docs, you need to hide the parent header yourself when nesting stacks: https://reactnavigation.org/docs/nesting-navigators#nesting-multiple-stack-navigators

If you use `react-native-screens/native-stack`, open the issue in `react-native-screens` repo as we ask in the docs: https://reactnavigation.org/docs/native-stack-navigator

**Comment by nimabrownlee** [comment]
@satya164 
Could you please let me explain myself before you close the issue. They literally have both the same problem. As I told you in the original post, I want to only hide the parent header when the child header is shown. The option you're suggesting (mentioned in the docs) always hides it.

Please re-open it.

**Comment by satya164** [comment]
https://reactnavigation.org/docs/screen-options-resolution#setting-parent-screen-options-based-on-child-navigators-state

**Comment by felipe-melo** [comment]
i'm having the same issue

**Comment by pbassut** [comment]
Yeah, just add `options={{ headerShown: false }}`
```jsx
<RootStack.Screen
   name="Home"
   component={Home}
   options={{ headerShown: false }} // <--- this
/>
```

So strange to have that added in as anything other than a breaking change. Hard to notice something like that.
