### ISSUE TITLE
Accessing the 'state' property of the 'route' object is not supported.

### ISSUE THREAD

**Issue by luco** [react-navigation/react-navigation#9056]
I'm trying to hide the TabBar based on the router index. I was using this code in `react-navigation/bottom-tabs@5.5.2` and it was working fine, however it's throwing this warning in the latest version:

> Accessing the 'state' property of the 'route' object is not supported. If you want to get the focused route name, use the 'getFocusedRouteNameFromRoute' helper instead: https://reactnavigation.org/docs/screen-options-resolution/#setting-parent-screen-options-based-on-child-navigators-state

My code:

```
const setTabBarVisible = (route, index) => {
    const {state} = route;
    if(state.index > index) return false;
    return true;
}
```

```
<Tab.Screen 
        name="Profile" 
        component={Profile}
        options={({ route }) => ({
            tabBarVisible: setTabBarVisible(route, 0)
        })}
/>
```

| software                       | version |
| ------------------------------ | ------- |
| @react-navigation/native       | 5.8.6
| @react-navigation/stack       | 5.12.3
| @react-navigation/bottom-tabs       | 5.10.7
| react-native                   | 0.63.3

**Comment by luco** [comment]
I can't even access the state on the latest version. How can I access the current route index?

**Comment by satya164** [comment]
Accessing index like this isn't documented and accessing `state` is even recommended against in the docs](https://reactnavigation.org/docs/route-prop).

You need to change your code to hide the tab bar in the recommended way rather than accessing child navigator state https://reactnavigation.org/docs/hiding-tabbar-in-screens/

**Comment by luco** [comment]
So, there's no way of accessing the current route index?

**Comment by satya164** [comment]
I think it's pretty clean that you nest tab inside stack and it works without any extra configuration. Accessing child component state is hacky, you write the same number of navigators (or usually more), then it requires extra code and it's prone to bugs.

**Comment by luco** [comment]
Managed to make it work using this:

```
const setTabBarVisible = (route) => {
    const routeName = getFocusedRouteNameFromRoute(route);
    const hideOnScreens = ['EditProfile'];
    if(hideOnScreens.indexOf(routeName) > -1) return false;
    return true;
  }
```

**Comment by arnaudambro** [comment]
I want to log every route change, and I tried quite some stuff but I always get this warning too, but I can't use `getFocusedRouteNameFromRoute` with the navigator ref, how can I manage ?

```js
class App extends React.Component {

  onStateChange = async () => {
    if (!this.navigationRef) return;
    const currentRouteName = this.navigationRef.getCurrentRoute().name;
    if (currentRouteName === this.prevCurrentRouteName) return;
    this.prevCurrentRouteName = currentRouteName;
    console.log({ currentRouteName })
  };

  render() {
    return (
        <NavigationContainer
          ref={(r) => (this.navigationRef = r)}
          onStateChange={this.onStateChange}>
            {this.props.children}
        </NavigationContainer>
    );
  }
}
```

**Comment by mcAnastasiou** [comment]
In the bottomTab navigator i used the example of [documentation](https://reactnavigation.org/docs/bottom-tab-navigator/)
and i have the following code 

![Screen Shot 2020-11-26 at 11 00 24 PM](https://user-images.githubusercontent.com/45881723/100391139-38423980-303b-11eb-8e53-b2fea3d55207.png)

i am getting the same error. How can i avoid it?

`"@react-navigation/bottom-tabs": "^5.11.1",
    "@react-navigation/native": "^5.8.9",
    "@react-navigation/stack": "^5.12.6",`

**Comment by IamMasterWayne** [comment]
+1

**Comment by satya164** [comment]
I'm pretty certain that that's not the code which triggers this warning.

**Comment by luco** [comment]
@satya164 It seems that `getFocusedRouteNameFromRoute` it's not working properly, giving the Route name.

**Comment by mcAnastasiou** [comment]
@satya164 you are totally right.

i was using this 

`
const useNavigatorDepth = (route: any) => {
  const dispatch = useDispatch();

  useEffect(() => {
    const stackIndex = route?.state ? route.state.index : 0;

    dispatch(setNavigatorIndex(stackIndex));
  }, [dispatch, route]);
};`

to hide the bottom tab bar when depth is bigger than 0

**Comment by elodieirdor** [comment]
I also have this same warning but it is triggered by the library why-did-you-render. I did not go deep into the code but when I disable it, I don't have warning anymore.

**Comment by AfraGngr** [comment]
> Managed to make it work using this:
> 
> ```
> const setTabBarVisible = (route) => {
>     const routeName = getFocusedRouteNameFromRoute(route);
>     const hideOnScreens = ['EditProfile'];
>     if(hideOnScreens.indexOf(routeName) > -1) return false;
>     return true;
>   }
> ```

Thank u this worked for me

**Comment by RogelioCamargo** [comment]
> Managed to make it work using this:
> 
> ```
> const setTabBarVisible = (route) => {
>     const routeName = getFocusedRouteNameFromRoute(route);
>     const hideOnScreens = ['EditProfile'];
>     if(hideOnScreens.indexOf(routeName) > -1) return false;
>     return true;
>   }
> ```

Could you explain ur logic?

**Comment by manastasiou** [comment]
> > Managed to make it work using this:
> > ```
> > const setTabBarVisible = (route) => {
> >     const routeName = getFocusedRouteNameFromRoute(route);
> >     const hideOnScreens = ['EditProfile'];
> >     if(hideOnScreens.indexOf(routeName) > -1) return false;
> >     return true;
> >   }
> > ```
> 
> Could you explain ur logic?

Sure. The logic behind this is the following:
getFocusedRouteNameFromRoute(route); will return  the focused route. For example if the tab bar route names are for simplicity 
1. 'Tab1'
2. 'Tab2'
3. 'Tab3'
and i am on Tab2 it will return Tab2. So i have the screens for which the tab bar should be hidden. A better idea is to have the screens for which it should be visible which is a better approach. 
Although i concluded to a better solution where i do the following
i have the tabbar navigator with one screen for each tab and after that if i want to navigate to an inner screen it navigates to another stack navigator or to a simple screen as follows. This is the most clean approach because you don't use redux at all

` <App.Navigator>
      <App.Screen
        name={BOTTOM_TABS_NAVIGATOR_ROUTE}
        component={BottomTabNavigator}
      />
      <App.Screen
        name={NESTED_NAVIGATOR_ROUTE}
        component={NestedNavigator}
      />
      <App.Screen name={SIMPLE_SCREEN_ROUTE} component={SimpleScreen} />
    </App.Navigator>`

**Comment by f-ricci** [comment]
Today I ran into the same problem, it was caused because I nested the tab navigator inside a context provider causing the tabs.navigator to re-render. I solved the problem by handling the state differently.

```javascript
changeDate('1984')

<Context.Provider value={date}>
  // Tab.Navigator here
</Context.Provider>
```

**Comment by efstathiosntonas** [comment]
In my case the issue was raised by a  custom lock function: (so the button tap is registered only once) 


```
  const lock = useNavigateLock();

  const onGoToFeed = useCallback(
    (feed: Doc<Feed>) => {
      if (lock()) {
        navigation.push("FeedDetailPage", { ...feed, tabType: "comment", blockedUsers });
      }
    },
    [blockedUsers, navigation, lock]

```

`useNavigateLock.ts` :

```

import { useFocusEffect } from "@react-navigation/native";

export const useNavigateLock = () => {
  const [isLocked, setIsLocked] = useState(false);

  useFocusEffect(
    useCallback(() => {
      setIsLocked(false);
    }, [])
  );

  const locker = () => {
    if (isLocked) {
      return false;
    } else {
      setIsLocked(true);
      return true;
    }
  };

  return locker;
};

```

as you can see, the `useNavigateLock` function uses `useFocusEffect` and this is causing the warning to appear. Removing that function from `onGoToFeed` function stopped the warning.

**Comment by AlexZurek** [comment]
I'm seeing this warning come from the `useRouteCache` function even though I don't explicitly try to access the route state in any of my screens. Here's the structure of the Navigators:

```
DrawerNavigator
|
|-- StackNavigator (headerMode = 'none')
    |
    |-- TabNavigator
        |
        |-- StackNavigator
    |-- StackNavigator
```
The warning is displayed when navigating between screens in the nested `StackNavigator` inside of the `TabNavigator`.

**Comment by AlexZurek** [comment]
> I'm seeing this warning come from the `useRouteCache` function even though I don't explicitly try to access the route state in any of my screens. Here's the structure of the Navigators:
> 
> ```
> DrawerNavigator
> |
> |-- StackNavigator (headerMode = 'none')
>     |
>     |-- TabNavigator
>         |
>         |-- StackNavigator
>     |-- StackNavigator
> ```
> 
> The warning is displayed when navigating between screens in the nested `StackNavigator` inside of the `TabNavigator`.

An update on this, we were able to narrow the issue down to a `headerRight` component we were setting on the nested `StackNavigator` inside of the `TabNavigator`. That component was accessing a Redux store using the `useSelector` hook and we were able to resolve the warning by calling `connect()` in the default export of that component. This was the article that convinced us to try this approach: https://www.pluralsight.com/guides/use-the-connect()-function-to-pass-redux-state-to-sub-routes

```js
import { connect } from 'react-redux';

// other component stuff

export default connect()(HeaderRightComponent);
```

We tried reproducing this issue with the component we were using in the `headerLeft` on that same `StackNavigator` but couldn't get the warning to appear again. 🤷‍♂️

**Comment by MuhammadUmar474** [comment]
Manage with this code
const setTabBarVisible = (route) => {
    const routeName = getFocusedRouteNameFromRoute(route);
    const hideOnScreens = ['EditProfile'];
    if(hideOnScreens.indexOf(routeName) > -1) return false;
    return true;
  }

**Comment by mtimofiiv** [comment]
The Tab navigator docs though show an example for using the `state` object:

```js
import { View, Text, TouchableOpacity } from 'react-native';

function MyTabBar({ state, descriptors, navigation }) {
  const focusedOptions = descriptors[state.routes[state.index].key].options;

  if (focusedOptions.tabBarVisible === false) {
    return null;
  }

  return (
    <View style={{ flexDirection: 'row' }}>
      {state.routes.map((route, index) => {
        const { options } = descriptors[route.key];
        const label =
          options.tabBarLabel !== undefined
            ? options.tabBarLabel
            : options.title !== undefined
            ? options.title
            : route.name;

        const isFocused = state.index === index;

        const onPress = () => {
          const event = navigation.emit({
            type: 'tabPress',
            target: route.key,
            canPreventDefault: true,
          });

          if (!isFocused && !event.defaultPrevented) {
            navigation.navigate(route.name);
          }
        };

        const onLongPress = () => {
          navigation.emit({
            type: 'tabLongPress',
            target: route.key,
          });
        };

        return (
          <TouchableOpacity
            accessibilityRole="button"
            accessibilityState={isFocused ? { selected: true } : {}}
            accessibilityLabel={options.tabBarAccessibilityLabel}
            testID={options.tabBarTestID}
            onPress={onPress}
            onLongPress={onLongPress}
            style={{ flex: 1 }}
          >
            <Text style={{ color: isFocused ? '#673ab7' : '#222' }}>
              {label}
            </Text>
          </TouchableOpacity>
        );
      })}
    </View>
  );
}

// ...

<Tab.Navigator tabBar={props => <MyTabBar {...props} />}>
  {...}
</Tab.Navigator>
```

https://reactnavigation.org/docs/bottom-tab-navigator#api-definition

Is this also considered the wrong way to use the nav state?

**Comment by JowelTisso** [comment]
> Managed to make it work using this:
> 
> ```
> const setTabBarVisible = (route) => {
>     const routeName = getFocusedRouteNameFromRoute(route);
>     const hideOnScreens = ['EditProfile'];
>     if(hideOnScreens.indexOf(routeName) > -1) return false;
>     return true;
>   }
> ```

@luco Thanks, It worked for me too...

**Comment by hichemBAALI** [comment]
``> Managed to make it work using this:
> 
> ```
> const setTabBarVisible = (route) => {
>     const routeName = getFocusedRouteNameFromRoute(route);
>     const hideOnScreens = ['EditProfile'];
>     if(hideOnScreens.indexOf(routeName) > -1) return false;
>     return true;
>   }
> ```


In case you would choose the show in screens:

```
const setTabBarVisible = (route) => {
  const routeName = getFocusedRouteNameFromRoute(route)
  const showOnScreens = [HOME_SCREEN, MARKET_SCREEN]
  console.log(showOnScreens.indexOf(routeName))
  console.log(routeName)
  if (
    routeName === undefined ||
    showOnScreens.indexOf(routeName) > -1
  )
    return true
  return false
}

```
