### ISSUE TITLE
(0 , _reactNativeSafeAreaContext.useSafeAreaInsets) is not a function

### ISSUE THREAD

**Issue by iqbalfaisal** [react-navigation/react-navigation#9060]
| software                       | version |
| ------------------------------ | ------- |
| Android                 | 25 API
| @react-navigation/native       | ^5.7.3
| @react-navigation/drawer       | ^5.9.0
| react-native-reanimated        | ^1.3.3
| react-native-gesture-handler   | ^1.6.1
| react-native-safe-area-context | ^0.7.3
| react-native-screens           | ^2.7.0
| react-native                   |  0.63.2
| node                           | 15.2.0
![Screenshot_1605248045](https://user-images.githubusercontent.com/46706064/99035466-9124c300-25a1-11eb-8d15-a710003a5259.png)

**Comment by iqbalfaisal** [comment]
> The versions mentioned in the issue for the following packages differ from the latest versions on npm:
> 
> * `@react-navigation/native` (found: `5.7.3`, latest: `5.8.9`)
> * `@react-navigation/drawer` (found: `5.9.0`, latest: `5.11.2`)
> 
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?

Still same

**Comment by satya164** [comment]
You're using a very old version of react-native-safe-area-context. Please upgrade.
