### ISSUE TITLE
Screen with WebView crashes App during navigation

### ISSUE THREAD

**Issue by chongma** [react-navigation/react-navigation#9061]
**Current Behavior**

- What code are you running and what is happening?

Navigating to a screen which contains a WebView crashes the whole app with no stack trace.  Disabling animations on the screen fixes the problem e.g. <Stack.Screen ... options={{animationEnabled: false}} />

**Expected Behavior**

- What do you expect should be happening?

It should navigate

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |  Android
| @react-navigation/native       | 5.8.9
| @react-navigation/stack        | 5.12.6
| react-native-gesture-handler   | 1.7.0
| react-native-safe-area-context | 3.1.4
| react-native-screens           | 2.10.1 
| react-native                   | 5.8.9
| expo                           | 39.0.3
| node                           | 12.19.0
| npm or yarn                    | npm

**Comment by chongma** [comment]
Sorry that was a typo.  It is version 5.12.6

**Comment by WoLewicki** [comment]
Do you use `enableScreens()`? If so, the issue with `WebView` should have been resolved in https://github.com/software-mansion/react-native-screens/pull/607 and should be available from `react-native-screens` v. 2.12.0.

**Comment by chongma** [comment]
@WoLewicki No I never used `enableScreens()` unless it is on by default?

**Comment by WoLewicki** [comment]
@chongma it depends on how you created the project. You can check if `enableScreens()` is present in your index.js or somewhere else in your code.

**Comment by satya164** [comment]
See the workaround here https://github.com/react-navigation/react-navigation/issues/9067#issuecomment-728074223

**Comment by avinashd3** [comment]
> **Current Behavior**
> 
> * What code are you running and what is happening?
> 
> Navigating to a screen which contains a WebView crashes the whole app with no stack trace. Disabling animations on the screen fixes the problem e.g. <Stack.Screen ... options={{animationEnabled: false}} />
> 
> **Expected Behavior**
> 
> * What do you expect should be happening?
> 
> It should navigate
> 
> **Your Environment**
> 
> software	version
> iOS or Android	Android
> @react-navigation/native	5.8.9
> @react-navigation/stack	5.12.6
> react-native-gesture-handler	1.7.0
> react-native-safe-area-context	3.1.4
> react-native-screens	2.10.1
> react-native	5.8.9
> expo	39.0.3
> node	12.19.0
> npm or yarn	npm

Hi Matthew(chongma),
I was getting the app crash while navigating and after applying the property {{animationEnabled: false}}, the issue got resolved.
Thanks for the solution.

Regards,
Avinash

**Comment by rezareact** [comment]
@chongma 
<Stack.Screen ... options={{animationEnabled: false}} /> -> That's solved my problem. thanks.
In react-navigation >= 6.x use ` <Stack.Screen ... options={{animation:'none'}} />`

**Comment by 1Jesper1** [comment]
Thanks @rezareact That worked, on IOS and Android!

**Comment by lennartkloock** [comment]
@chongma Thank you for your workaround! Seems to still be an issue

**Comment by josequintana94** [comment]
Solved with:

`<Stack.Screen options={{animationEnabled: false}} name="MainScreen" component={MainScreen} />`

**Comment by fabriziocucci** [comment]
The only reasonable workarounds I've found acceptable (without disabling the animations on the stack screen) are:
* setting `androidLayerType="software"` on the `WebView` component (as mentioned [here](https://github.com/react-navigation/react-navigation/issues/10290#issuecomment-1639862911)):
```
<WebView androidLayerType="software" ... />
```
* using  the `useIsFocused` hook to conditionally render the `WebView` (as mentioned [here](https://github.com/react-navigation/react-navigation/issues/9061#issuecomment-1511053069)):
```
const isFocused = useIsFocused();
// ...
return (isFocused && (<WebView ... />)
```

**Comment by stydeveloper** [comment]
> options={{animation:'none'}}

Issue resolved
