### ISSUE TITLE
Upgrading from 3.x to 5.x - how to determine if "went back"

### ISSUE THREAD

**Issue by alexfoxy** [react-navigation/react-navigation#9062]
Sorry, this is not a bug but I have spent hours searching the docs for this info.

I am upgrading a react native project from 3.x to 5.x and cannot find in the docs how to determine if a navigation event was triggered by going back. I was using `payload.action.type === 'Navigation/BACK'` on a `willFocus` listener in 3.x but cannot find how to do this in 5.x. The event passed to the `focus` listener in 5.x only contains `target` and `type`.

My use case is that I want to trigger an api call when the screen is focussed, but not if you go *back* to that screen.

Any pointers? 

Thanks 
Alex

**Comment by satya164** [comment]
Trigger API call in `componentDidMount`/`useEffect` instead of focus listener if yoo only want to fetch data when component is mounted.

**Comment by alexfoxy** [comment]
@satya164 just to clarify, `componentDidMount` is only called when navigating to a screen, not when navigating back?
