### ISSUE TITLE
Cannot clear History manually

### ISSUE THREAD

**Issue by jawil003** [react-navigation/react-navigation#9064]
**Current Behavior**

After dispatch the reset Action with History entries cleared, an Exception is called.

**Expected Behavior**

Possibility to clear History without Error.

**How to reproduce**

1. Install `react-navígation/native` and `react-navígation/drawer`.
2. Implement an Drawer Navigator.
3. Use `useNavigation()` to navigate to another Route and then Try to clean History with dispatch and reset.

**Your Environment**

yarn v1.22.4
Android 10
Windows 10
VS Code
@react-navigation/drawer": "^5.9.1,
@react-navigation/native": "^5.7.4,
@react-navigation/stack": "^5.9.2,
etc.

PS: If this is closed as Question, I will repoen it as long until you try to fix the actual Issue! No answer on StackOverflow or Reactiflux after 3 Years!

**Comment by raajnadar** [comment]
Instead of adding PS you should add a snack demo to reproduce the issue.

**Comment by jawil003** [comment]
@raajnadar I provided a short example Snack here: https://expo.io/@willey3x37/projects/historynavexample

**Comment by satya164** [comment]
That's not a snack. Snacks can be created here https://snack.expo.io/

You need to post info about what exactly the error is, as well as the source code to know what you're doing.

> PS: If this is closed as Question, I will repoen it as long until you try to fix the actual Issue! No answer on StackOverflow or Reactiflux after 3 Years!

Threatening to keep spamming OSS repos isn't nice. It's also a good way to get blocked from ever opening any issues or sending PRs.

**Comment by jawil003** [comment]
@satya164  @raajnadar  So [this](https://snack.expo.io/@willey3x37/example-react-native-history) is the correct one, not so familiar with expo snacks, so sorry but what choice I have when every Issue on the Topic gets immidially closed with no helpful advice just for looking to StackOverflow where noone has an Idea how this works because it isn't in the Docs, just want to make clear that this is an actual Issue!

**Comment by satya164** [comment]
> so sorry but what choice I have when every Issue on the Topic gets immidially closed with no helpful advice just for looking to StackOverflow where noone has an Idea how this works because it isn't in the Docs

You can read the source code and figure things out yourself if it's not in the docs. The source code is open to everyone. Regardless, the docs document how state object is structured: https://reactnavigation.org/docs/navigation-state

You can't expect OSS maintainers to answer every question, though I have always tried to answer people on StackOverflow and answer questions which may be tricky to figure out. Regardless, this is literally your first issue in the repo and somehow you decided that threatening to spam was a nice way to ask someone to help you.

>  just want to make clear that this is an actual Issue

It's not an actual issue. You are explicitly passing `undefined` in the history array by setting it to `[state.history[state.history.length]]` which is always going to be `[undefined]`.
