### ISSUE TITLE
Double headers are shown

### ISSUE THREAD

**Issue by DanielHosseini** [react-navigation/react-navigation#9066]
**Current Behavior**
I'm currently facing a problem with IOS, where two app bar headers are shown. On my local dev setup, it's working perfectly fine on Android, where only one Header is shown. However, when running the same code on an iPhone, two headers are shown.

![image](https://user-images.githubusercontent.com/2711831/99158145-02629400-26d0-11eb-9b42-64b69f18fc2e.png)

When creating a Snack, I can also see that the problem is on both an Android and iPhone device.

**Expected Behavior**
I expect that on IOS only one header is shown, just like on my local Android development setup.

**Android Device**
![image](https://user-images.githubusercontent.com/2711831/99158232-fe834180-26d0-11eb-8f0f-fdcd9189fb97.png)

**On IPhone:**
![Two](https://user-images.githubusercontent.com/2711831/99158315-ad278200-26d1-11eb-9b71-ffec96294720.png)
´

Also, when trying to add **headderMode**='none' or **showHeader**: false it will remove the custom header and not the default one

**headerMode = none or showHeader = false**
![headermode_none](https://user-images.githubusercontent.com/2711831/99158323-c6c8c980-26d1-11eb-9dce-b0075804157b.png)

**How to reproduce**
-  [Snack] https://snack.expo.io/@danielhosseini/tactless-nachos 

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |BOTH
| @react-navigation/native       |5.8.9
| @react-navigation/stack        |5.12.6
| react-native-gesture-handler   |1.7.0
| react-native-safe-area-context |3.1.4
| react-native-screens           | - 2.10.1
| react-native                   | 0.63
| expo                           | 39.0.4
| node                           | 12.18.0
| npm or yarn                    |yarn

**Comment by TheWirv** [comment]
Do you have a drawer? If yes, it is because of [this commit](https://github.com/react-navigation/react-navigation/commit/7bc385e4f39d22956ef37b69ecfb5e6463d29049#). I have the same problem. For now, just set the `headerShown` prop of your DrawerNavigator to false.

In the mean time: @satya164, is there any particular reason, why `headerShown` eventually has been defaulted to `true`, thus breaking quite a few apps that maybe have been updated withouth looking too closely at the changelogs?

**Comment by DanielHosseini** [comment]
@TheWirv I do have a Drawer as shown in the Expo snack. Is there even an headerShown option available in the DrawerNavigation?

**Comment by TheWirv** [comment]
@DanielHosseini Did you have a look at my link?

@react-navigation/drawer v5.11.0 introduced the `headerShown` property via [commit dbe961](https://github.com/react-navigation/react-navigation/commit/dbe961ba5bb243e8da4d889c3c7dd6ed1de287c4). Then, [commit 7bc385](https://github.com/react-navigation/react-navigation/commit/7bc385e4f39d22956ef37b69ecfb5e6463d29049#) defaulted it to `true`.

**Comment by DanielHosseini** [comment]
@TheWirv Yeah, I did.

Hmm, but I'm running the  @react-navigation/drawer": "^5.9.3" version in the Expo snack. Adding headerShown = false will just remove the custom bar and not the default bar as I show in the pictures above.

**Comment by TheWirv** [comment]
@DanielHosseini 
1. `"^5.9.3"` installs the most recent version that's not above `5.x.x`. For example, `6.0.1` would not be installed, but on a fresh project, without a `yarn.lock` file, it would install `5.11.2`, as of the time of writing this comment. (Have a look at [this](https://classic.yarnpkg.com/en/docs/dependency-versions/) for more information.)
2. If you set `headerShown: false` to the `Drawer.Screen` in your snack, it will hide the header that you don't want. So what exactly is the problem?

**Comment by DanielHosseini** [comment]
@TheWirv 

Tried doing on my local project and not it in the expo. I'm using Typescript and I'm not getting any IntelliSense headerShown in the options object so that's why I'm a little confused. However, if I add it, it seems to work as you said. Thanks!

Still a bit annoying, been spending a couple of hours on this :/

**Comment by TheWirv** [comment]
@DanielHosseini I have saved your snack [under a separate link](https://snack.expo.io/ww!WXAhtB) with one change: I gave the `<Drawer.Screen />` the property `options={{headerShown: false}}`. Isn't this exactly what you want?

**Comment by TheWirv** [comment]
I am using TypeScript too. It has not been any problem for me. You should maybe restart you TS server.
While you have a TS file open, press Ctrl/Cmd+Shift+P. Then just start typing restart and you'll find it.

**Comment by DanielHosseini** [comment]
@TheWirv 
The restart worked wonders.

Thanks a lot for the help!

![image](https://user-images.githubusercontent.com/2711831/99158975-caac1a00-26d8-11eb-80a2-7c47fa6ac8e0.png)

**Comment by TheWirv** [comment]
No thing, glad I could help!

@satya164 I would still be interested to know whether it is necessary to default `headerShown` for drawer screens to `true`.

**Comment by pke** [comment]
I agree, such breaking changes should not be introduced in a minor version.

You guys planning to apply for the beta "discussions" feature here at GH? The answer rate of StackOverflow questions regarding this lib (especially v5) is kind of low.

**Comment by satya164** [comment]
Thanks for the feedback folks. It should be hidden in latest version.

> You guys planning to apply for the beta "discussions" feature here at GH

Not sure if it's available publicly, but we'll enable it once it's available.

**Comment by gavinolsen** [comment]
I'm still seeing in version `^6.1.8`

**Comment by umrashrf** [comment]
Putting the following CSS on top container of Drawer.Screen helped me.

```
topContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: "#fff"
},
```

I don't understand exactly what it does but it removed or overlapped the double header and made it a single header. In my case, I had to use a header on the screen and a global navigator header to be hidden.

**Comment by aliraza943** [comment]
Add header shown false in **_screenOptions_** then it will not show this error. Below is my code.

`import React from "react";
import { createBottomTabNavigator } from "@react-navigation/bottom-tabs";
import HomeStack from "../MainStack/HomeStack";
import AuthStack from "../authStack/AuthStack";


const Tab = createBottomTabNavigator();

const BottomTabNavigator = () => {
    return (
        <Tab.Navigator screenOptions={{
            _**headerShown:false,**_
            headerStyle: {
                backgroundColor: '#f4511e',
            },
            headerTintColor: '#fff',
            headerTitleStyle: {
                fontWeight: 'bold',
            },
        }}>
            <Tab.Screen name="Home1" component={HomeStack} />
            <Tab.Screen name="Login1" component={AuthStack} options={{ headerShown: 'false' }} />
        </Tab.Navigator>
    );
};

export default BottomTabNavigator;`
