### ISSUE TITLE
Issue with text while making 5 tabs in top-tab bar

### ISSUE THREAD

**Issue by swapanil** [react-navigation/react-navigation#9071]
**Current Behavior**

If there are five tabs it is not fitting properly.

![Simulator Screen Shot - iPhone X - 2020-11-17 at 14 22 45](https://user-images.githubusercontent.com/42803028/99367937-9440eb80-28e0-11eb-8495-8676f7bd6ae0.png)

**Expected Behavior**

I should be able to make 5 or more tabs

**How to reproduce**

[top-tab-demo](https://github.com/swapanil/react-native-top-bar-demo)

**Your Environment**

| software                            | version |
| ----------------------------------- | ------- |
| iOS or Android                      | iOS 14
| @react-navigation/native            | ^5.8.9
| @react-navigation/material-top-tabs | ^5.3.9
| react-native-tab-view               | ^2.15.2
| react-native                        | 0.63.3
| expo                                | N/A
| node                                | 12.19.0
| npm or yarn                         | 6.14.8

**Comment by raajnadar** [comment]
https://reactnavigation.org/docs/material-top-tab-navigator#tabbaroptions use `scrollEnabled` option to fix the issue.

**Comment by swapanil** [comment]
> scrollEnabled

thanks

**Comment by elmcapp** [comment]
I solved my issue with this by doing the follow. Looks like I just needed to change the width of the lable

screenOptions={{
        tabBarLabelStyle: {width: '100%', textAlign: 'center'}
      }}
