### ISSUE TITLE
Wrong IOS 13 Modal Appearance

### ISSUE THREAD

**Issue by Joshandrews43** [react-navigation/react-navigation#9076]
**Current Behavior**

- What code are you running and what is happening?

When displaying a modal over a modal in the `ModalStack` as recommended by the docs, there is a white bar on the top that should not be present and ruins the UI.

Below is the code for my navigators `screenOptions`:
```
const modalScreenOptions: StackNavigationOptions = {
  cardStyle: { backgroundColor: 'transparent' },
  cardOverlayEnabled: true,
  gestureEnabled: true,
  gestureDirection: 'vertical',
  transitionSpec: {
    open: TransitionSpecs.TransitionIOSSpec,
    close: TransitionSpecs.TransitionIOSSpec,
  },
  cardStyleInterpolator: CardStyleInterpolators.forModalPresentationIOS,
};
```

- Include a screenshot or video if it makes sense.

<img width="463" alt="Screen Shot 2020-11-17 at 4 26 03 PM" src="https://user-images.githubusercontent.com/31226916/99466783-db83a800-28f1-11eb-8650-5d82b73d703b.png">

**Expected Behavior**

- What do you expect should be happening?

There is a white bar at the top of the screen when a modal is presented inside another modal. This should not occur. 

**How to reproduce**

Below is the code for my main navigation component. If you navigate to any modal in `ModalStack`, then from there navigate to another modal, there is a white bar at the top that should not be visible.

```
<NavigationContainer ref={navigationRef}>
      <RootStack.Navigator
        headerMode="none"
        initialRouteName="MainStack"
        mode="modal"
        screenOptions={modalScreenOptions}
      >
        <RootStack.Screen name="MainStack" component={MainStackScreens} />
        <RootStack.Screen name="ModalStack" component={ModalStackScreens} />
      </RootStack.Navigator>
    </NavigationContainer>
```

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |
    "@react-navigation/native": "^5.8.6",
    "@react-navigation/stack": "^5.12.1",
| react-native-gesture-handler   |
| react-native-safe-area-context |
| react-native-screens           |
| react-native                   |
| expo                           39.0.0
| node                           12.18.1
| npm or yarn                    |

**Comment by Joshandrews43** [comment]
> The versions mentioned in the issue for the following packages differ from the latest versions on npm:
> 
> * `@react-navigation/native` (found: `5.8.6`, latest: `5.8.9`)
> * `@react-navigation/stack` (found: `5.12.1`, latest: `5.12.6`)
> 
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?

Just upgraded, and yes, the issue still persists.

**Comment by Joshandrews43** [comment]
Any update here?

**Comment by satya164** [comment]
> When displaying a modal over a modal in the ModalStack as recommended by the docs

Docs don't recommend you to display a modal over a modal. You can have only one modal stack at root.

**Comment by Joshandrews43** [comment]
> Docs don't recommend you to display a modal over a modal. You can have only one modal stack at root.

Im building an iMessage clone, and this is seriously needed functionality otherwise any modal in modal is messed up, which IOS happens to do a lot. That was Apple's entire purpose in creating the UX for an ios 13 modal, so its only reasonable that react navigation should support it also?

**Comment by satya164** [comment]
I don't understand why you need to nest modal inside a modal navigator. Just push another screen in the navigator.

**Comment by Joshandrews43** [comment]
@satya164  Do you have an iphone? Go into messages, open a group chat. Then try to add another member to the group chat. A modal will appear and the previous modal will be pushed down slightly. This is a native action, that occurs frequently in a messaging app (which I am building). There are hundreds of other use cases for a modal in a modal using an IOS 13 style modal. If this library is truly trying to emulate native navigation, it **should** support this feature. 

Regardless of how you think it should behave, the behavior I have described above is indeed a bug, and this issue should be reopened.

**Comment by satya164** [comment]
Like I said, you can replicate that behavior just by pushing 3 screens. There's no reason to nest a modal inside another modal navigator.

**Comment by Joshandrews43** [comment]
> Like I said, you can replicate that behavior just by pushing 3 screens in the same modal navigator. There's no reason to nest a modal inside another modal navigator.

That isn't native behavior though... Users have UI/UX expectations. Can you give me a reply about the bug that isn't "well you can achieve a completely different looking result by doing X" when I'm clearly after native UI/UX? Can someone else comment on this? Don't just close it when clearly its a bug since you allow modal in modal... If that's your solution, disable IOS 13 modal in modal entirely

**Comment by Joshandrews43** [comment]
@satya164 When I put it all in the same navigator with the `screenOptions` of the modals defined as above, the header jitters in size.

**Comment by Joshandrews43** [comment]
Could you please share an example where there are stacked modals?

**Comment by mistricky** [comment]
Same problem, any update?
