### ISSUE TITLE
[Regression][Android] Keyboard not dismissed on navigation

### ISSUE THREAD

**Issue by TheAlmightyBob** [react-navigation/react-navigation#9078]
**Current Behavior**

If the keyboard is open on Android, `keyboardHandlingEnabled` is set to `true`, and a navigation is performed, the keyboard remains open.

**Expected Behavior**

If `keyboardHandlingEnabled` is set to `true`, the keyboard should be dismissed when navigation is performed.

This was previously addressed via #7907, but recently regressed again with #9008.

**How to reproduce**

Snack at https://snack.expo.io/h14NMl3T3 

(this is the same Snack that @frankyjuang provided in #7875, just updated to newer React Navigation versions)

By default the Snack is set up with React Navigation Stack 5.12.3, which introduced the regression. In this case, tapping the Edit button will take you to a new screen but keep the keyboard open.

If you change the version back to 5.12.2, the keyboard will dismiss upon navigation.

(the latest version also repros the issue, I just used 5.12.3 to highlight the first version that has the issue)

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |  Android
| @react-navigation/native       | 5.8.9
| @react-navigation/stack        | 5.12.6
| react-native-gesture-handler   | 1.7.0
| react-native-safe-area-context | 3.1.4
| react-native-screens           | 2.10.1
| react-native                   | 0.63.2
| expo                           | 39.0.4

**Comment by satya164** [comment]
If someone has time to debug why it happens and how to fix it, then help is greatly appreciated.

**Comment by TheAlmightyBob** [comment]
@satya164 Why it happens is simple: #9008 stopped the code from calling `Keyboard.dismiss()`. It only dismisses if `input` is defined, however `input` is only ever set when doing a swipe-back navigation gesture (which isn't even a thing on Android? at least not by default).

So fixing *this* bug is easy. Fixing it without then regressing #9008 is more complex... it seems like `handlePageChangeStart` (which sets `input`) should be called on all navigations, not just swipe-back gestures...? Or maybe this whole keyboard handling logic is just in the wrong place and those events were intentionally specific to swipe-back gestures? I don't know the background context there.

**Comment by satya164** [comment]
Yes, fixing this one is easy, but it's also necessary to debug #9008 and fix it. Also what doesn't make sense is that it still works on iOS somehow.

**Comment by TheAlmightyBob** [comment]
Thanks @satya164 !

If you're referring to _this_ bug not repro'ing on iOS, I assume that's just because iOS automatically dismisses the keyboard itself...

If you're referring to #9008 not repro'ing on iOS, I assume that's because the previous logic checked `if (Platform.OS === 'android')` before dismissing the keyboard.... but I see that your new code doesn't do that anymore, so if that behavior is _still_ Android-specific, then I'm out of ideas.
