### ISSUE TITLE
Crash with React Native Web and selectively mounted screens

### ISSUE THREAD

**Issue by paour** [react-navigation/react-navigation#9082]
**Current Behavior**

- I have a fairly complex navigator: stack -> bottom tabs -> stack in each tap
   - some screens are not mounted in the navigator depending on app state (logged-in / logged-out)
- on React Native it works fine
- on React Native Web it works too (including linking, which is really cool)
- but when I hit the browser reload button, or try to load a deep link directly, I get a crash `TypeError: Cannot read property 'options' of undefined` in `useDescriptors`.

```
  132 |       navigation,
  133 |     })),
  134 | // The `options` prop passed to `Screen` elements
> 135 | ...(typeof screen.options === 'object' || screen.options == null
      | ^  136 |   ? screen.options
  137 |   : // @ts-expect-error: this is a function, but typescript doesn't think so
  138 |     screen.options({
```

<img width="635" alt="undefined" src="https://user-images.githubusercontent.com/90963/99830731-68329e00-2b5e-11eb-8adf-d121b9d095de.png">

**Expected Behavior**

- not a crash…

**How to reproduce**

- hello

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Web
| @react-navigation/native       | 5.8.9
| react-native                   | 0.62.2
| node                           | 10.10.0
| yarn                    | 1.22.10
| @react-navigation/bottom-tabs | 5.11.1
| @react-navigation/core | 5.14.3
| @react-navigation/material-bottom-tabs | 5.3.9
| @react-navigation/routers | 5.6.2
| @react-navigation/stack | 5.12.6
| react-native-web | 0.14.8

**Comment by paour** [comment]
I can confirm that the crash no longer happens when all the screens are always mounted. Perhaps the route matching might not crash, and wait for the relevant screen to be mounted.

At the very least a more descriptive error message would be welcome.

**Comment by satya164** [comment]
> At the very least a more descriptive error message would be welcome.

Please provide a repro. There's no way to provide a descriptive error message (or know if there's a bug) if I don't know how to repro the issue or what exactly causes the issue.

**Comment by paour** [comment]
I've tried to produce a minimal repro, but I can't.

I've upgraded the packages and I can also no longer reproduce. Sorry for the inconvenience.
