### ISSUE TITLE
Drawer doesn't show on mobile web

### ISSUE THREAD

**Issue by juststartmeteor** [react-navigation/react-navigation#9083]
**Current Behavior**
When tap drawer icon just see overlay but there's no drawer, this happened on Chrome and Safari on mobile device, the drawer works well on native app.

**Expected Behavior**
See drawer open and close on mobile web browser.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | iOS and Android
| @react-navigation/native       | ^5.8.9
| @react-navigation/drawer       |^5.11.3
| react-native-reanimated        |~1.13.0
| react-native-gesture-handler   |~1.7.0
| react-native-safe-area-context |3.1.4
| react-native-screens           |~2.10.1
| expo                           |~39.0.2

**Comment by arorajatin** [comment]
Did you figure out why this was happening @juststartmeteor?

**Comment by radelcom** [comment]
@juststartmeteor i am also experiencing this issue in my latest project. were you able to find a workaround?
