### ISSUE TITLE
Only show last tab content on mobile web browser

### ISSUE THREAD

**Issue by juststartmeteor** [react-navigation/react-navigation#9084]
**Current Behavior**
We have 2 top tabs, on Chrome and Safari on mobile device it only show the second tab content, the first tab show blank content. And tab indicator only and always show under the first tab.

**Expected Behavior**
Show correct tab content when switch tab, and show correct indicator.

**Your Environment**

| software                            | version |
| ----------------------------------- | ------- |
| iOS or Android                      | iOS and Android
| @react-navigation/native            |^5.8.9
| @react-navigation/material-top-tabs |^5.3.9
| react-native-tab-view               |^2.15.2
| expo                                |~39.0.2

**Comment by SilvioLuis** [comment]
Bug stills exists... 

`"@react-navigation/material-top-tabs": "^5.3.15",`
