### ISSUE TITLE
Error when using @react-navigation/material-bottom-tabs and @react-navigation/material-top-tabs

### ISSUE THREAD

**Issue by Vn-ChemGio** [react-navigation/react-navigation#9085]
Hi, guy
when using both of them;
I get an error: 
`Module not found: Can't resolve 'react-native-tab-view' in '...\node_modules\@react-navigation\material-top-tabs\lib\module\views'`
I found lasted version of them is
 "@react-navigation/material-bottom-tabs": "^5.3.10",
    "@react-navigation/material-top-tabs": "^5.3.10",

But 
    "@react-navigation/bottom-tabs": "^5.11.2",

Maybe, both of them had not been update as react navigation version
Can you update them ?

**Comment by Vn-ChemGio** [comment]
Hi, i'm using all lasted version of them: 
    "@react-native-community/masked-view": "^0.1.10",
    "@react-navigation/bottom-tabs": "^5.11.2",
    "@react-navigation/material-bottom-tabs": "^5.3.10",
    "@react-navigation/material-top-tabs": "^5.3.10",
    "@react-navigation/native": "^5.8.10",
    "@react-navigation/stack": "^5.12.8",

**Comment by raajnadar** [comment]
Read the docs to fix this issue

https://reactnavigation.org/docs/material-top-tab-navigator/
