### ISSUE TITLE
Permanent drawer on web, scroll issue.

### ISSUE THREAD

**Issue by fyranollfyra** [react-navigation/react-navigation#9087]
There is a problem when setting the `drawerType` to permanent when using web as platform.
When filling the drawer with a lot of content the whole page gets larger instead of just the drawer, even if the screen that is showing to the right has nothing on it.
This result in that you can't scroll inside the drawer but instead you scroll the whole page instead.

You can easily test this with the provided Snack link. I you pick Android or iOS it works as it should where you just scroll inside the drawer when the content there is larger than the screen.

**Current Behavior**

The whole page takes the size of the drawer and when you scroll you scroll the whole page instead of just inside the drawer.

**Expected Behavior**

The same behavior as on iOS and Android where you just scroll inside the drawer if the content is larger than the browser window.

**How to reproduce**

https://snack.expo.io/@fyranollfyra/permanent-drawer-problem

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | web
| @react-navigation/native       | 5.8.10
| @react-navigation/drawer       | 5.11.4
| react-native-reanimated        | 1.13.0
| react-native-gesture-handler   | 1.7.0
| react-native-safe-area-context | 3.1.4
| react-native-screens           | 2.10.1
| react-native                   | 0.63.3
| expo                           | 39.0.0
| node                           | 14.8.0
| npm or yarn                    | Yarn 1.22.5

**Comment by fyranollfyra** [comment]
I actually solved this, just set the `body` tag to `100%`and it works as it should.

**Comment by nguyenkhooi** [comment]
Hi,
I have a same issue but I'm not sure where to find the `body` tag you mentioned above. Could you show me where to fix it? 
Thanks

**Comment by fyranollfyra** [comment]
You could solve this two ways. Either directly in your `index.html` file.
Just add a `style` attribute in the `body` tag like this `style=height: 100%`.
Or the way I did it was in `App.js`:

`useEffect(() => {
        if (Platform.OS === 'web') {
            document.body.style.height = '100%';
        }
    }, []);`

I hope this solves it for you too!
