### ISSUE TITLE
Three bugs

### ISSUE THREAD

**Issue by 1280103995** [react-navigation/react-navigation#9091]
```
"dependencies": {
    "@react-native-community/masked-view": "^0.1.10",
    "@react-navigation/bottom-tabs": "^5.11.1",
    "@react-navigation/native": "^5.8.9",
    "@react-navigation/stack": "^5.12.6",
    "prop-types": "^15.7.2",
    "react": "16.13.1",
    "react-native": "0.63.3",
    "react-native-gesture-handler": "^1.8.0",
    "react-native-reanimated": "^1.13.2",
    "react-native-safe-area-context": "^3.1.9",
    "react-native-screens": "^2.15.0"
  }
```
This is a demo:  https://github.com/1280103995/react-navigation-modal
Forget for my bad Englist.

Bug 1: 
    The screen options cannot override the navigator options. I set ```cardStyleInterpolator: CardStyleInterpolators.forHorizontalIOS``` to the Navigator, and set other values to the cardStyleInterpolator property of Modal screen. But when navigating from a screen to a Modal screen, the CardStyleInterpolators.forHorizontalIOS animation is still executed.
![Screen_Recording_20201123-175229_example](https://user-images.githubusercontent.com/17424486/99952015-f3f43680-2db9-11eb-85cd-e1327055c701.gif)

Bug 2: 
From one modal screen to another, a white screen flashes.
![Screen_Recording_20201123-175253_example](https://user-images.githubusercontent.com/17424486/99952184-387fd200-2dba-11eb-8d35-d3c26b3d9951.gif)

Bug 3:
After opening a Modal Screen (the Modal Screen has been restricted from clicking other places to close the modal), and then sliding the screen from left to right, you can see that the bottom screen is dragged.
![Screen_Recording_20201123-183522_example](https://user-images.githubusercontent.com/17424486/99952628-e4c1b880-2dba-11eb-80a4-ef28651ed8a0.gif)

**Comment by satya164** [comment]
> The screen options cannot override the navigator options. I set cardStyleInterpolator: CardStyleInterpolators.forHorizontalIOS to the Navigator, and set other values to the cardStyleInterpolator property of Modal screen. But when navigating from a screen to a Modal screen, the CardStyleInterpolators.forHorizontalIOS animation is still executed.
> From one modal screen to another, a white screen flashes.

I see you setting `cardStyleInterpolator` in `useEffect`. The animations start as soon as the screen mounts, and `useEffect` fires way late for them to be able to override the animation. You need to specify it in `options` prop of `Stack.Screen`

> After opening a Modal Screen (the Modal Screen has been restricted from clicking other places to close the modal), and then sliding the screen from left to right, you can see that the bottom screen is dragged.
This a known issue with gesture handler https://github.com/react-navigation/react-navigation/issues/8515

In future, please don't group multiple issues into one.

**Comment by 1280103995** [comment]
@satya164 Thanks!     I changed my code and it now works normally except for #8515

**Comment by adrirg2** [comment]
@1280103995 Could you fix de flickering?

**Comment by 1280103995** [comment]
> @1280103995 Could you fix de flickering?

Sorry for the late reply. Need to adjust the structure of the stack, [here](https://github.com/1280103995/react-navigation-modal) is my current structure.
