### ISSUE TITLE
Nested Navigation Not Working on Update of @react-navigation/core

### ISSUE THREAD

**Issue by danj565** [react-navigation/react-navigation#9093]
**Current Behavior**

Nested navigation does not work 

**Expected Behavior**

Nested navigation should work after upgrading core.  I have tested this multiple times by downgrading and then upgrading core.  Each time I go to 5.14.4 nested navigation fails.

I have had to override the dependancy for react-navigation native with the following update to downgrade core so it works:

"resolutions": {
    "@react-navigation/native/**/@react-navigation/core": "5.14.3"
  },

**How to reproduce**

Upgrade @react-navigation/core from 5.14.3 to 5.14.4 then attempt to do a nested navigation.

Example:

this.drawerNavigation.navigate('Contacts', {
      screen: 'Details',
      params: {
        liveCall: liveCall,
        disableInput: false,
      },
    });

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | iOS simulator and device
| react-navigation               | 5.8.10
| react-navigation-stack         | 5.12.8
| react-navigation-tabs          | 5.11.2
| react-navigation-drawer        | 5.11.4
| react-native-reanimated        | ^1.13.2
| react-native-gesture-handler   | ^1.6.1
| react-native-safe-area-context | ^3.1.8
| react-native-screens           | ^2.9.0
| react-native                   | 0.63.3
| expo                           | N/A
| node                           | 14.12.0
| npm or yarn                    | yarn

**Comment by satya164** [comment]
You shouldn't be using `@react-navigation/core` directly.

**Comment by danj565** [comment]
Hi Satyajit,  thanks for your reply.  I am not using it directly.  I had to downgrade the lib to get nested nav to work.

**Comment by satya164** [comment]
The only different between 5.14.3 and 5.14.4 is a fix regarding independent containers. So I believe there is nothing breaking regarding nesting navigators. However if you still believe it's bug and have a repro as the template asks, please open a new issue.

**Comment by danj565** [comment]
Thank you for your reply!!  Got it. I will investigate further.

**Comment by danj565** [comment]
I tested the code with core 5.14.3 and works fine, as soon as I upgrade to 5.14.4 none of my nested navigations work (Kept everything else the same).. It just goes to the first screen instead of the nested screen.

I set a class variable in render like so:

`
this.drawerNavigation = this.props.navigation;
`

Then in a callback to the controller I navigate like so:

`this.drawerNavigation.navigate('Phone', {
      screen: 'OnCall',
      params: {
        LiveCall: liveCall,
        AvatarURL: avatarURL,
      },
    });`

If I have some time ill try to re-create the issue in a snack.

**Comment by danj565** [comment]
If anyone has an issue with this I resolved it by removing react native context

**Comment by danj565** [comment]
Nevermind that did not fix it.

**Comment by ChenChuanzhen** [comment]
Error: Unable to resolve module `@react-navigation/core` from `node_modules/react-navigation-stack/lib/module/navigators/createStackNavigator.js`: @react-navigation/core could not be found within the project.
