### ISSUE TITLE
Error: Creating a navigator doesn't take an argument. Maybe you are trying to use React Navigation 4 API with React Navigation 5?

### ISSUE THREAD

**Issue by ChoiJinYoung** [react-navigation/react-navigation#9094]
**Current Behavior**
My app was working very well before I updated xcode, OSX in mac.
Even my android app is working very well. but when I start my app in mac for test.
I faced the following error.
"Error: Creating a navigator doesn't take an argument. Maybe you are trying to use React Navigation 4 API with React Navigation 5?"
I found an answer how to solve this problem at the following link https://reactnavigation.org/docs/upgrading-from-4.x/
but I still have a problem. There are a lot of new errors after applied that solution.

**Expected Behavior**
I didn't expect this problem when I update xcode, OSX. Do I have to downgrade xcode, OSX if I want the previous situation. I mean no error code in Mac. this solution also has a big risk for me. 
Is this the only solution? How can I start my app with no error in the new updated environment?
if someone knows a solution to my situation. 
please let me know. I am very serious and stress out because of this.
Thank you in advance.

**Your Environment**
xcode 12.2
OSX big sur 11.0.1

**Comment by satya164** [comment]
The error is because you upgraded React Navigation, not Xcode or Mac OS X. You can get more help on Discord from other users on what to do.

**Comment by ChoiJinYoung** [comment]
I am sorry. and Thank you I will ask them again.
