### ISSUE TITLE
Modal header too high with iOS 13 modal presentation (TransitionPresets.ModalPresentationIOS)

### ISSUE THREAD

**Issue by jhogervorst** [react-navigation/react-navigation#9095]
**Current Behavior**

I’m displaying a modal stack navigator using `TransitionPresets.ModalPresentationIOS`, to achieve the standard iOS 13 modal presentation style. However, the header in the modally presented stack navigator is too high:

<img width="545" alt="Schermafbeelding 2020-11-24 om 10 15 08" src="https://user-images.githubusercontent.com/304065/100073564-f4361580-2e3d-11eb-8966-f7e2b1d5b597.png">

**Expected Behavior**

I expect the header to have ’normal’ height, like in other apps (such as the native Calendar app):

<img width="545" alt="Schermafbeelding 2020-11-24 om 10 16 02" src="https://user-images.githubusercontent.com/304065/100073681-19c31f00-2e3e-11eb-8713-d565aa8519b2.png">

**How to reproduce**

https://snack.expo.io/@jnthn/ios-13-modal-stack

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | iOS 14.2
| @react-navigation/native       | 5.8.10
| @react-navigation/stack        | 5.12.8
| react-native-gesture-handler   | 1.7.0
| react-native-safe-area-context | 3.1.4
| react-native-screens           | 2.10.1
| expo                           | 39.0.0

**Comment by satya164** [comment]
It's documented that you need to set `headerStatusBarHeight` when configuring this animation: 
<img width="826" alt="Screen Shot 2020-11-24 at 14 03 37" src="https://user-images.githubusercontent.com/1174278/100098145-e7291e80-2e5d-11eb-8b1e-b971264a3d0f.png">

From next major, `mode="modal"` will automatically use this animation and configure `headerStatusBar` without extra code.

**Comment by benevbright** [comment]
hey @satya164 the example code in the document would work when the modal screen component is "simple screen component". And I assume that you're checking if the screen is not "the first root screen". 

But it's problem when the modal screen is another stack navigator. And this "modal screen" is `first` screen of this stack navigator. So we would need some different approach. Are you already aware of this?
