### ISSUE TITLE
UI flicker issue when orientation changes from portrait to landscape

### ISSUE THREAD

**Issue by Tanuja0064** [react-navigation/react-navigation#9100]
**Current Behavior**
We are using @react-navigation/material-top-tabs library to build carousal navigation which have 6 screens. We are using video player in one of screens where we have the functionality to make the video full screen.

When we click on the full screen button, we are seeing the cut screen of top tab menu screen. it shows half part of two screens, connected for a fraction of second before loading the landscape mode. This issue is very sporadic.

**Expected Behavior**
it should have a smooth transition from portrait to landscape and vice versa.

**How to reproduce**
1. Create material top tab bar with multiple screens
2. try to switch between portrait to landscape.

**Your Environment**
Issue occurring on both IOS and Android

**Comment by satya164** [comment]
Please provide a video or GIF when you're describing an UI issue.
