### ISSUE TITLE
Page not found 404 error - be allowed to choosing the url path

### ISSUE THREAD

**Issue by filozofer** [react-navigation/react-navigation#9102]
**Current Behavior**

I'm using "@react-navigation/native: 5.7.6" and I handle my 404 error on web build using the linking prop of the NavigationContainer as mention in the documentation : https://reactnavigation.org/docs/configuring-links#handling-unmatched-routes-or-404
My 404 page are handle correctly, but the url is automatically change into the name of the route which is "NotFound"

![image](https://user-images.githubusercontent.com/1324775/100335811-b0761400-2fd5-11eb-8ac5-93757329ce7a.png)

**Expected Behavior**

Keep the wrong url without change it (like "/i-dont-exist" for example) or allow the developer to choose which url must be used as replace when reaching the not found case (like "/not-found-page" for example)

**How to reproduce**

Basic ReactNative app create with expo, using react-navigation and passing the linking prop to the NavigationContainer as the documentation mention it : https://reactnavigation.org/docs/configuring-links#handling-unmatched-routes-or-404

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| @react-navigation/native       | 5.8.10 |
| react-native                   | 39.0.3 |
| expo                           | 39.0.4 |

**Comment by filozofer** [comment]
Still waiting for an answer on this :)

**Comment by unixvb** [comment]
any updates?

**Comment by unixvb** [comment]
btw current fix for this: 
```typescript 
const linking: LinkingOptions = {
    prefixes: [],
    config: { screens },
    ...getLinkingPathOptions()
};

// Use your 404 Screen name
const pageNotFoundPath = '/PageNotFound';

export const getLinkingPathOptions = (): Pick<LinkingOptions, 'getStateFromPath' | 'getPathFromState'> => {
    let currentUrl = '';

    return {
        getStateFromPath: (path, config) => {
            currentUrl = path;

            return getStateFromPath(currentUrl, config);
        },
        getPathFromState: (state, config) => {
            const path = getPathFromState(state, config);

            return path === pageNotFoundPath ? currentUrl : path;
        }
    };
};
```

**Comment by taj567** [comment]
guys,do you know any solution for it?
when am using linking in react-native-web it is working fine and after deploying and when page reloads getting 404 page not found.
![Uploading Screenshot 2022-03-08 153213.png…]()

**Comment by satya164** [comment]
This should be fixed by https://github.com/react-navigation/react-navigation/commit/86e64fdcd81a57cf3f3bdab4c9035b52984e7009
