### ISSUE TITLE
Can't achieve v4 back behavior. 

### ISSUE THREAD

**Issue by julensas** [react-navigation/react-navigation#9105]
**Current Behavior**
Go back action doesn't work as described in docs.
https://reactnavigation.org/docs/navigation-actions#goback

```javascript
 <Stack.Navigator initialRouteName="A">
   <Stack.Screen name="A" component={A} />
   <Stack.Screen name="B" component={B} />
   <Stack.Screen name="C" component={C} />
 </Stack.Navigator>
```
```javascript
// screen A
navigation.navigate('B');
```
```javascript
// screen B
navigation.navigate('C', { dontBackToMe: route.key });
```
```javascript
// screen C
navigation.dispatch({
      ...CommonActions.goBack(),
      source: route.params?.dontBackToMe,
    });
```
Screen B is rendered.

**Expected Behavior**
Screen A is rendered.

I'm aware of the "target" option, not sure how and why to set it. 
Used to work like this:
navigation.goBack(navigation.getParam('dontBackToMe')).

    "@react-navigation/native": "5.8.10",
    "@react-navigation/stack": "5.12.8",

**Comment by satya164** [comment]
> I'm aware of the "target" option, not sure how and why to set it.
target is the key of the navigation state: `navigation.dangerouslyGetState().key`

however this is only supported in stack navigator. what's your use case for tab navigator?

**Comment by julensas** [comment]
@satya164 This is the stack navigator. 

Use case:
Screen B is a search preview screen. And where screen C is the results.
After results are displayed, it doesn't make sense to go back to preview.

For me, this a very common technique. If this is not possible, I will have to downgrade back to v4.

**Comment by satya164** [comment]
Like I replied, you need to specify the target property for it to work

Also, instead of doing this, you should probably just replace to navigate from the search results screen in the first place.

**Comment by julensas** [comment]
After the target is set, back action is not being handled at all.

Ended up doing this. Will do the trick for now...
```javascript
navigation.dispatch({
      ...StackActions.pop(route.params?.dontBackToMe ? 2 : 1),
    });
```

Still like the new API. Good work ;)
