### ISSUE TITLE
Header transition on nested navigators

### ISSUE THREAD

**Issue by gfpacheco** [react-navigation/react-navigation#9106]
**Current Behavior**

Changing header transition doesn't work if transitioning from screen inside nested stack navigator to screen on root stack navigator (screen transition works fine, not the header).

**Expected Behavior**

Correct header transition plays.

**How to reproduce**

https://snack.expo.io/@gfpacheco/794c29

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS                 | 14 |
| @react-navigation/native       | 5.8.8 |
| react-native                   | 0.63.3 |
| expo                           | 39.0.4 |
| node                           | 14 |
| yarn                    | 1.22.10 |

**Comment by gfpacheco** [comment]
> The versions mentioned in the issue for the following packages differ from the latest versions on npm:
> 
> * `@react-navigation/native` (found: `5.8.8`, latest: `5.8.10`)
> 
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?

Yep, still happens

**Comment by satya164** [comment]
I assume by "header transition doesn't work" you mean that header in 2 different navigators. Each navigator is a React Component and generally things in one navigator doesn't affect other navigators, including animations. Similarly, it's not possible for headers in navigator to respect the animation in a different navigator

The child header still does animate along with the screen transition, since it's part of the screen, it doesn't animate the header separately because screens are not changing inside that navigator, but in a different navigator.

This is expected behaviour.

**Comment by gfpacheco** [comment]
> I assume by "header transition doesn't work" you mean that header in 2 different navigators. Each navigator is a React Component and generally things in one navigator doesn't affect other navigators, including animations. Similarly, it's not possible for headers in navigator to respect the animation in a different navigator
> 
> The child header still does animate along with the screen transition, since it's part of the screen, it doesn't animate the header separately because screens are not changing inside that navigator, but in a different navigator.
> 
> This is expected behaviour.

But if I configured both navigators to use a fade in/out animation for the headers, shouldn't the outer navigator header animate with a fade in as well?

**Comment by satya164** [comment]
No, the nested navigator acts is inside a screen inside the parent navigator, and animates because the screen which it's in animates.

**Comment by gfpacheco** [comment]
Last question, is there any other way I can set up my navigators in a way I can have the bottom tabs in some screens, no bottom tabs in others, and use a fade in/out transition for the header?
