### ISSUE TITLE
Botton tab don't respect safe area in iOS 14.2.1 (iPhone 12)

### ISSUE THREAD

**Issue by rvieceli** [react-navigation/react-navigation#9110]
**Current Behavior**
Only in iPhone 12 (access only in PRO from user) with version 14.2.1 (works fine in 14.2)

On IPhone X and IPhone11 ios 14.2.1 is not available (when I wrote this issue). With IOS 14.2 works fine in IPhone X, 11 and 12.

Bottom tab don't respect safe area.
![image](https://user-images.githubusercontent.com/2790845/100620019-31a71100-331e-11eb-934f-af39526ae9b9.png)

**Expected Behavior**

![image](https://user-images.githubusercontent.com/2790845/100620530-cf024500-331e-11eb-8974-078300147959.png)

**Your Environment**

| software                      | version |
| ----------------------------- | ------- |
| iOS or Android                | iOS 14.2.1
| @react-navigation/native      | 5.8.10
| @react-navigation/bottom-tabs | 5.11.2
| @react-navigation/core | 5.14.4
| @react-navigation/stack | 5.12.8
| react-native-screens          | 2.10.1
| react-native                  | 0.63.2
| expo                          | 39.0.4
| node                          | 12.13.1
| npm or yarn                   | npm 6.12.1

**Comment by katye333** [comment]
This is happening with version 5.8.10 too

**Comment by xclidongbo** [comment]
This is happening with version 3.13.0 too

**Comment by ghostknow** [comment]
same too, anyone can help?
I'm using react-navigation v2

**Comment by jeremiahk** [comment]
I am seeing this issue on iPhone 12, 12 pro and 12 pro max running 14.2. Does not show up on an iPhone 12 mini. It does not appear to be related to `react-native-safe-area-context`. I set up a simple project just using `react-native-safe-area-context` and it worked as expected.

**Comment by HughBerriez** [comment]
sadly the following didn't fix it for me but it worked for some others. Lmk if it works for any of you 
https://github.com/callstack/react-native-paper/issues/2323

**Comment by jeremiahk** [comment]
I was able to get it working by following [this](https://github.com/react-navigation/react-navigation/issues/8972#issuecomment-714474997) comment. In my case, all I needed to do was wrap my AppContainer in a SafeAreaProvider.

**Comment by rvieceli** [comment]
Hey guys, I discovered my problem, when try to do some fix, I saw old code to identify when running on iphonex checking screen size, and for iphone 12 is different.

If you are using packages like `react-native-iphone-x-helper`, check for updates. if you are using custom code like me, [chek it](https://github.com/ptelad/react-native-iphone-x-helper/blob/master/index.js#L9)

The strange thing is the screen size on my iPhone 12 pro max simulator, because keep using Iphone 11 screen size.

**Comment by whhlulu** [comment]
> I'm using react-navigation v2

I'm using react-navigation v2,too.
How did you solve it？

**Comment by askielboe** [comment]
Had similar safe area issues on iPhone 12 running iOS 14.2. I found that the issues disappeared when downgrading Xcode from 12 to 11.

**Comment by R-yan** [comment]
> 在运行iOS 14.2的iPhone 12上存在类似的安全区域问题。我发现将Xcode从12降级到11时问题消失了。


> Had similar safe area issues on iPhone 12 running iOS 14.2. I found that the issues disappeared when downgrading Xcode from 12 to 11.

Look at the source code, the essence is guard iphone12 model screen size to do adaptation

**Comment by HughBerriez** [comment]
https://github.com/callstack/react-native-paper/issues/2419

quick update from my end: updating to v4.5.0 fixed it for me

**Comment by Juliocbr** [comment]
same issue with:
"@react-navigation/bottom-tabs": "^5.11.0",
"@react-navigation/material-top-tabs": "^5.3.9",
"@react-navigation/native": "^5.8.7",
"@react-navigation/stack": "^5.12.5",

**Comment by HerbertLim** [comment]
After upgrading my iPhone from X to 12 Pro, I experienced this issue. 
I upgraded all npm packages including react-navigation related packages, but this issue remained.
I finally upgraded react-native-paper from 3.12.0 to 4.7.0, and this issue was resolved.
Major version upgrade of react-native-paper to 4.x seemed to be the key to resolve this issue. :)
