### ISSUE TITLE
Question: Making .navigate(screen) happen on swipe from right to left but new pushed screen follow finger movement

### ISSUE THREAD

**Issue by takeerdevs** [react-navigation/react-navigation#9111]
**Current Behavior**

i'm trying to replicate tiktok's main feed on swipe from right to left pushes profile screen but follows finger movement but i haven't found easy way to do it with react navigation. react navigation has sliding movement when moving back to previous screen and follows finger movement but i haven't found a way to make sliding work when moving to new screen

i've implemented panResponder to detect horizontal swipe but i don't know how to send onPanResponderMove events to react navigation on the new pushed screen so it can follow finger movement. How can this be done in react-navigation..

**Expected Behavior**
![ezgif com-optimize](https://user-images.githubusercontent.com/49426357/100633763-860eb880-333f-11eb-8473-1a2ff3288864.gif)

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS                 |14.0.1
| @react-navigation/native       |5.7.2
| @react-navigation/stack        |5.8.0
| react-native-gesture-handler   |1.7.0
| react-native-screens           |2.9.0
| react-native                   |0.61.5

**Comment by takeerdevs** [comment]
Yes

**Comment by satya164** [comment]
The issue tracker is only reserved for bug reports. However, here are some resources if you want to implement custom animations:

https://callstack.com/blog/custom-screen-transitions-in-react-navigation/
https://reactnavigation.org/docs/stack-navigator#animations

**Comment by anniewey** [comment]
@takeerdevs are u able to solve it?

**Comment by EthanDM** [comment]
I'm also trying to implement this but not finding much luck. Anyone have any tips or figure this out? Right now I'm using `material-top-tab-navigator` and hiding the top tab bar, but it doesn't have the "card" overlay over the current screen and main bottom tab bar.

**Comment by Bedd-Time-Media** [comment]
⁣Get i have unsubscribed to thia 5 times ​
