### ISSUE TITLE
Custom Header overlaps Top Tab header on iOS

### ISSUE THREAD

**Issue by miroslavskela** [react-navigation/react-navigation#9112]
**Current Behavior**
Hi, I have stack navigation with two stack screens, and both of these screens are separet material top navigatiors, in first stack i set custom header, and on second one there is no custom header. Currently on iOS, when i navigate to second one, custom header from first overlaps top bar navigation, and this happens only on iOS. On android, on second there is no custom header and it looks fine. 

**Expected Behavior**
Custom header should not be displayed.

**How to reproduce**
I don't have minimalistic example at this moment, but I will make it if there is no any ideo what happens here.

**Your Environment**

| software                            | version |
| ----------------------------------- | ------- |
| iOS or Android                      | iOS
| @react-navigation/native            |5.7.3
| @react-navigation/material-top-tabs |5.2.16
| react-native-tab-view               |2.15.1
| react-native                        |0.63
| expo                                |39.0.0
| node                                |10
| npm or yarn                         |npm

**ios screenshot**
![iOS](https://user-images.githubusercontent.com/36046629/100638507-bcc1e000-32f9-11eb-97a8-a54c4fa4c067.png)

**ANdroid screenshot**
![Android](https://user-images.githubusercontent.com/36046629/100638520-c0556700-32f9-11eb-9b93-8329979c3a00.png)

**Comment by miroslavskela** [comment]
Update versions, still same problem.

**Comment by devanjith** [comment]
Use headerMode="screen" in the navigator.
```<NavigationContainer>
  <Navigator
    headerMode={'screen'}
```
