### ISSUE TITLE
[web] linking configuration urls don't work on browser page refresh on production builds

### ISSUE THREAD

**Issue by dincozdemir** [react-navigation/react-navigation#9118]
**Current Behavior**

- I'm running a new expo project with tab examples. It has two tabs of BottomTabNavigator with a LinkingConfiguration defined in NavigationContainer. When I run the project on web, I can navigate between the tabs, see the url changes accordingly and refresh the page that is mapped to the current url successfully. When I run the application on production mode, I can navigate between the tabs, see the url changes accordingly but when I refresh the page I get an error message:

![Screenshot from 2020-12-01 23-21-51](https://user-images.githubusercontent.com/2143920/100803794-0e6a8780-342c-11eb-89b0-6b80329ab857.png)

**Expected Behavior**

- I expect to see the screen mapped to the url on page refresh.

**How to reproduce**

- Start a new expo project with expo init. Choose `tabs (TypeScript)     several example screens and tabs using react-navigation and TypeScript` template. Start expo and open web in production mode. Refresh any screen.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | X
| @react-navigation/native       |  5.8.10
| react-native                   |  https://github.com/expo/react-native/archive/sdk-39.0.4.tar.gz
| expo                           | sdk 39
| node                           | 14.4.0
| yarn                    | 1.22.5

**Comment by satya164** [comment]
You need to configure you server to serve the [correct page if you're doing SSR](https://reactnavigation.org/docs/server-rendering) or always serve `index.html` if you don't.

**Comment by markholland** [comment]
@dincozdemir Did you solve this?

**Comment by cxt19951016** [comment]
same error @dincozdemir
