### ISSUE TITLE
`gestureEnabled: false` not changing behaviour

### ISSUE THREAD

**Issue by ksloan** [react-navigation/react-navigation#9119]
First of all, thanks for your work on this library!

I think it's clear that there's an issue with disabling gestures in many version of react-navigation. You can see a huge list here of issues that have been opened or recently commented on with the same problem. 

The problem is: No matter where you put `gestureEnabled: false` there is no change to behaviour and swipe back gestures are still enabled.

I'm currently seeing this on:
```
    "@react-navigation/bottom-tabs": "^5.8.0",
    "@react-navigation/native": "^5.8.10",
    "@react-navigation/stack": "^5.12.8",
```

Issue list:

https://github.com/react-navigation/react-navigation/issues/6605
https://github.com/react-navigation/react-navigation/issues/8847
https://github.com/react-navigation/react-navigation/issues/1063#issuecomment-717089583
https://github.com/react-navigation/react-navigation/issues/7928#issuecomment-723325463
https://github.com/react-navigation/react-navigation/issues/8519
https://github.com/react-navigation/react-navigation/issues/6654#issuecomment-579762173
https://github.com/react-navigation/react-navigation/issues/7955
https://github.com/react-navigation/react-navigation/issues/8127
https://github.com/react-navigation/react-navigation/issues/7090
https://github.com/react-navigation/react-navigation/issues/5766

I think this warrants some investigation!

**Comment by ksloan** [comment]
yes it still exists

**Comment by askielboe** [comment]
Did you manage to solve this @ksloan?

**Comment by Dakuan** [comment]
as far as I can tell this is still an issue

**Comment by linoleum00** [comment]
it is still an issue, please reopen, I'm using:
    "react-navigation": "^4.4.4",
    "react-navigation-drawer": "^2.7.0",
    "react-navigation-stack": "^2.10.4",
    "react-navigation-tabs": "^2.11.0"
    
    on ios 14.4!!

**Comment by licoba** [comment]
+1, I tried it on https://snack.expo.io/
```
{
  "dependencies": {
    "@expo/vector-icons": "^12.0.0",
    "react-native-paper": "^4.0.1",
    "react-native-screens": "~2.15.2",
    "react-native-tab-view": "^2.15.1",
    "@react-navigation/stack": "^5.9.0",
    "react-native-reanimated": "~1.13.0",
    "@react-navigation/drawer": "^5.9.0",
    "@react-navigation/native": "^5.7.3",
    "react-native-gesture-handler": "~1.8.0",
    "@react-navigation/bottom-tabs": "^5.8.0",
    "react-native-safe-area-context": "3.1.9",
    "@react-native-community/masked-view": "0.1.10",
    "@react-navigation/material-top-tabs": "^5.2.16",
    "@react-navigation/material-bottom-tabs": "^5.2.16"
  }
}
```

**Comment by idrisdopico** [comment]
Still seems to be an issue for version 6.x.x

**Comment by VivienneB** [comment]
For me applying both options fixed this issue:
```ts
    gestureEnabled: false,
    swipeEnabled: false,
```

Although  in an earlier version a simple gestureEnabled: false was enough.

**Comment by zoobibackups** [comment]
> For me applying both options fixed this issue:
> 
> ```ts
>     gestureEnabled: false,
>     swipeEnabled: false,
> ```
> 
> Although in an earlier version a simple gestureEnabled: false was enough.

not working

**Comment by zoobibackups** [comment]
> Hey! This issue is closed and isn't watched by the core team. You are welcome to discuss the issue with others in this thread, but if you think this issue is still valid and needs to be tracked, please open a new issue with a repro.

Why the issue is closed without resolving 

```
gestureEnabled: false,
swipeEnabled: false,
```
non of them works, still the overlay is clickable.
How we prevent the drawer from closing when overlay is clicked

**Comment by Seb-AS** [comment]
Hey, any news about this issue? I'm trying to prevent to close a drawer tapping on the screen, and `gestureEnabled: false `doesn't work.

**Comment by olegmilan** [comment]
I got the same issue, I cannot disable gestures on a Screen if `mode='modal'`

**Comment by jacksonHendric** [comment]
Same issue even now with `native-stack
`
`gestureEnabled: false` on ios modal disables the pull down to close but the actual gesture is still enabled. You can pull down the screen.

Any fixes for this? Latest versions of all packages.

**Comment by OliveroRNDev** [comment]
I have found a solution. It is impossible to disable but when swiping back the focus on the screen changes and you can detect when a screen gets the focus. This way you can perform the actions that you were supposed to do when clicking on the goBack icon.

  useEffect(() => {
    const unsubscribe = navigation.addListener("focus", () => {
      // The screen is focused
      // Call any action
      console.log("focus on table");
      setGoBack(false);
    });

    // Return the function to unsubscribe from the event so it gets removed on unmount
    return unsubscribe;
  }, [navigation]);

I needed for example to change a boolean because I used it to hide the drawer when I pushed a stack navigator on top of it.
Hope this helps someone
