### ISSUE TITLE
Open drawer when I click on bottom tab navigator

### ISSUE THREAD

**Issue by GaylordP** [react-navigation/react-navigation#9120]
Hello :)
_Sorry for my English, I'm French and not very inhabited in Github :)_

I have asked this question on several forums ([notably Stackoverflow](https://stackoverflow.com/questions/65025965/react-navigation-open-drawer-when-i-click-on-bottom-tab-navigator)) but I am very surprised not to find an answer. My question is simple : **how to open a Drawer from bottom navigator** ?

I manage to create the bottom tabs buttons and click on them, the home page opens for both tabs (`GymIndexScreen` or `FoodIndexScreen`).

When I am on the home pages (`GymIndexScreen` or `FoodIndexScreen`), I can open the different Drawers **with my fingers** (`GymDrawerNavigator` and `FoodDrawerNavigator`) : **everything works fine**.

_Screen : https://i.stack.imgur.com/EONwp.png_

**Question** : I just want the drawers to open / close (toggle) automatically when I click the bottom tabs buttons, without having to open them with my fingers no matter where I am in the app.

`App.js` :

    import { NavigationContainer } from '@react-navigation/native'

    const App = () => {
      return (
        <NavigationContainer>
          <BottomTabNavigator />
        </NavigationContainer>
      )
    }

`BottomTabNavigator.js` :

    import { createMaterialBottomTabNavigator } from '@react-navigation/material-bottom-tabs'

    const Tab = createMaterialBottomTabNavigator()

    const BottomTabNavigator = (props) => {
      return (
        <Tab.Navigator>
          <Tab.Screen
            name="Gym"
            component={GymDrawerNavigator}
            options={{
              tabBarLabel: "Musculation",
            )}
          />
          <Tab.Screen
            name="Food"
            component={FoodDrawerNavigator}
            options={{
              tabBarLabel: "Alimentation",
            )}
          />
        </Tab.Navigator>
      )
    }

`GymDrawerNavigator.js` :

    import { createDrawerNavigator } from '@react-navigation/drawer'

    const Drawer = createDrawerNavigator()

    const GymDrawerNavigator = () => {
      return (
        <Drawer.Navigator>
          <Drawer.Screen
            name="Gym"
            component={GymStackNavigator}
          />
        </Drawer.Navigator>
      )
    }

`GymStackNavigator.js` :

    import { createStackNavigator } from '@react-navigation/stack'

    const Stack = createStackNavigator()

    const GymStackNavigator = () => {
      return (
        <Stack.Navigator initialRouteName="GymIndex">
          <Stack.Screen
            name="GymIndex"
            component={GymIndexScreen}
            }}
          />
          <Stack.Screen
            name="GymExerciseIndex"
            component={GymExerciseIndexScreen}
            }}
          />
          ... list of screens

**Your Environment**

| software                               | version |
| -------------------------------------- | ------- |
| iOS or Android                         | Android
| @react-navigation/native                | ^5.7.4
| @react-navigation/material-bottom-tabs | ^5.3.10
| @react-navigation/drawer | ^5.9.3
| react-native-paper                     | ^4.4.1
| react-native                           | 0.63.2
| npm or yarn                            | npm

**Comment by satya164** [comment]
https://stackoverflow.com/questions/64865543/opening-the-drawer-navigator-from-the-bottom-tab

**Comment by GaylordP** [comment]
Thank you very much for your answer, I had already read this answer :)

When I try to open the `component` drawer, I get this error :

> The action 'OPEN_DRAWER' was not handled by any navigator. Is your screen inside a Drawer navigator?

      <Tab.Screen
        name="Gym"
        component={GymDrawerNavigator}
        listeners={({ navigation }) => ({
          tabPress: e => {
            navigation.dispatch(DrawerActions.openDrawer())

            e.preventDefault()
          }
        })}

**Comment by iiagodias** [comment]
> Thank you very much for your answer, I had already read this answer :)
> 
> When I try to open the `component` drawer, I get this error :
> 
> > The action 'OPEN_DRAWER' was not handled by any navigator. Is your screen inside a Drawer navigator?
> 
> ```
>   <Tab.Screen
>     name="Gym"
>     component={GymDrawerNavigator}
>     listeners={({ navigation }) => ({
>       tabPress: e => {
>         navigation.dispatch(DrawerActions.openDrawer())
> 
>         e.preventDefault()
>       }
>     })}
> ```

how to perform tabpress without the tab being focused?

**Comment by Rooban19** [comment]
> > Thank you very much for your answer, I had already read this answer :)
> > When I try to open the `component` drawer, I get this error :
> > > The action 'OPEN_DRAWER' was not handled by any navigator. Is your screen inside a Drawer navigator?
> > 
> > 
> > ```
> >   <Tab.Screen
> >     name="Gym"
> >     component={GymDrawerNavigator}
> >     listeners={({ navigation }) => ({
> >       tabPress: e => {
> >         navigation.dispatch(DrawerActions.openDrawer())
> > 
> >         e.preventDefault()
> >       }
> >     })}
> > ```
> 
> how to perform tabpress without the tab being focused?

Did you get the answer?

**Comment by marcinb1986** [comment]
Hello. What is the solution here ? Did You fix it ?

**Comment by Manil-SoftNEP** [comment]
This [answer](https://stackoverflow.com/a/64866152/19476877) helped me.
Just use the `listeners` prop to `preventDefault` behaviour and then open the drawer.
```
<Tabs.Screen 
  name={"More"} 
  listeners={({ navigation }) => ({
    tabPress: e => {
      e.preventDefault();
      navigation.openDrawer();
    }
  })}
  component={Home} 
/>
```
