### ISSUE TITLE
Web - Navigation is broken after going back and forth

### ISSUE THREAD

**Issue by yairopro** [react-navigation/react-navigation#9128]
**Current Behavior**

Here's the demo [from the blog ](https://reactnavigation.org/blog/2020/05/16/web-support)

![web-broken](https://user-images.githubusercontent.com/8110568/101173483-469be100-364b-11eb-8f2c-dcd69a7562ac.gif)

**Expected Behavior**

The navigation to not be broken.

**How to reproduce**

Doing the following actions will break the navigation stack on web:
1. backward
2. forward
3. backward again
4. Now the navigation is broken. You cannot go backward or forward anymore.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| @react-navigation/native       | 5.8.10
| @react-navigation/stack        | 5.12.8

**Comment by StellarOcean** [comment]
This issue is reproducible with the following code: 
```
import 'react-native-gesture-handler';
import React from 'react';
import { NavigationContainer, useLinkTo } from '@react-navigation/native';
import { View, Text, Button } from 'react-native';

import { createStackNavigator } from '@react-navigation/stack';

const linking = {
  prefixes: ['https://localhost'],
  config: {
    screens: {
      Main: {
        screens: {
          Home: '/Main/Home',
          Details: '/Main/Details'
        }
      },
      MyModal: '/MyModal'
    },
  }
}

function HomeScreen() {
  const linkTo = useLinkTo();

  return (
    <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
      <Text style={{ fontSize: 30 }}>This is the home screen!</Text>
      <Button
        onPress={() => linkTo('/MyModal')}
        title="Open Modal"
      />
    </View>
  );
}

function DetailsScreen() {
  return (
    <View>
      <Text>Details</Text>
    </View>
  );
}

function ModalScreen() {
  const linkTo = useLinkTo();

  return (
    <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
      <Text style={{ fontSize: 30 }}>This is a modal!</Text>
      <Button onPress={() => linkTo('/Main/Home')} title="Dismiss" />
    </View>
  );
}


const MainStack = createStackNavigator();
const RootStack = createStackNavigator();

function MainStackScreen() {
  return (
    <MainStack.Navigator>
      <MainStack.Screen name="Home" component={HomeScreen} />
      <MainStack.Screen name="Details" component={DetailsScreen} />
    </MainStack.Navigator>
  );
}

function RootStackScreen() {
  return (
    <RootStack.Navigator mode="modal">
      <RootStack.Screen
        name="Main"
        component={MainStackScreen}
        options={{ headerShown: false }}
      />
      <RootStack.Screen name="MyModal" component={ModalScreen} />
    </RootStack.Navigator>
  );
}


export default function App() {
  return (
    <NavigationContainer linking={linking} fallback={<Text>Loading...</Text>}>
      <RootStackScreen />
    </NavigationContainer>
  );
}
```

**Comment by unixvb** [comment]
still relevant

**Comment by HeAtNet** [comment]
Same issue for me, when I use any type of navigation (e.g. createStackNavigator, createDrawerNavigator, createMaterialTopTabNavigator) with Expo project running in the web browser.

**Comment by adamhari** [comment]
I made a snack using the minimum reproducible example from @StellarOcean here: https://snack.expo.io/@adamhari/web---navigation-is-broken-after-going-back-and-forth-9128

**Comment by lesmo** [comment]
I see this behavior when using the browser history buttons too. I have a React Native template which is mashing together a stack I usually use:

https://github.com/lezzmo/razzle-treact-natigation/pull/9
```
The action 'RESET' with payload {"stale":false,"type":"stack","key":"stack-YDUoxSrlp7c_rSKXZ7GNw","index":1,"routeNames":["Home","Details"],"routes":[{"name":"Home","key":"Home-Y4E99beLSgaS3IhUFWdM7","params":{}},{"key":"Details-9CYFzWkM6ifCWd88-kRgE","name":"Details","params":{}}]} was not handled by any navigator.

This is a development-only warning and won't be shown in production.
```

**Comment by Hirbod** [comment]
And running this on local, I get:

```TypeError: Cannot read property 'routes' of undefined``` in BaseRouter.

<img width="1035" alt="Bildschirmfoto 2021-08-18 um 18 08 17" src="https://user-images.githubusercontent.com/504909/129933079-03cd8119-38a7-4f3b-a7f6-5e2891712369.png">

The error is also reproducible here:
https://react-navigation-example.netlify.app/

**Comment by AlastairTaft** [comment]
Sometimes I hit the same error as above.

![example](https://p187.p2.n0.cdn.getcloudapp.com/items/NQuYxqyj/81a769a3-0405-4479-a912-1069d0682cd1.jpg?source=viewer&v=b17b2bac7f44f036fc33deb6d0a636fb)

Whereas sometimes it resets the stack and I lose any state the mounted components had, which breaks a fair bit of our app.

**Comment by AlastairTaft** [comment]
Hit another case of this where navigating back in the browser throws an error.

Here is the navigation state before going back.

```
{
  "stale": false,
  "type": "stack",
  "key": "stack-syhsdz1NX_B3Gwh1tKPk3",
  "index": 2,
  "routeNames": [
    "DashboardScene",
    "ApplicationsKennelsScene",
    "ExpressionsOfInterestScene",
    // Have omitted other route names for brevity
  ],
  "routes": [
    {
      "name": "DashboardScene",
      "key": "DashboardScene-35pRUY4qSN6zNIFloTOKH"
    },
    {
      "key": "ApplicationsKennelsScene-tgfdjZ83aazqr7blHzVjk",
      "name": "ApplicationsKennelsScene",
      "params": {
        "redirectTo": "PendingApplicationsScene"
      }
    },
    {
      "key": "ExpressionsOfInterestScene-pwOSHRBeMbsdot04MrTfY",
      "name": "ExpressionsOfInterestScene",
      "params": {
        "kennelId": 3,
      }
    }
  ]
}
```

Then going back in the browser throws this error.

```
The action 'RESET' with payload {"stale":false,"type":"stack","key":"stack-qhcA5ULT7hId52wq5Haia","index":1,"routeNames":["DashboardScene","ApplicationsKennelsScene","ExpressionsOfInterestScene"],"routes":[{"key":"DashboardScene-NQ-5xqvEu0g8PPqEcUWtU","name":"DashboardScene"},{"key":"ApplicationsKennelsScene-OURVU3WAIBb1k-lF1ifIE","name":"ApplicationsKennelsScene","params":{"redirectTo":"PendingApplicationsScene"}}]} was not handled by any navigator.
```

It seems non of the keys match up, so maybe when you move to different nested navigators it causes an issue, because the above flow works the first time you do it, but errors the second time.

**Comment by takacskalman** [comment]
We have the same issue

**Comment by Hirbod** [comment]
Guess there is no way around but creating the issue again or giving @satya164 a friendly ping

**Comment by CarlosHdez** [comment]
Also facing this issues, mainly the one with the `RESET` message, does anyone have a workaround?

**Comment by awinograd** [comment]
I was experiencing the same issue hitting back to the initial screen. My fix was to stop setting initialState on web as described in https://reactnavigation.org/docs/navigation-container/#initialstate

**Comment by yairopro** [comment]
I am not able to reopen the issue.
@satya164

**Comment by AlastairTaft** [comment]
For what it's worth, it seems you must put the `<NavigationContainer>` almost, if not at the root of your app. If there's anything that causes it to rerender you'll run into these errors. Because everytime it rerenders it creates a new browser history in memory leading to these issues where a missing index leads to a runtime error.

**Comment by roryabraham** [comment]
We're also running into the same error shown in [this comment](https://github.com/react-navigation/react-navigation/issues/9128#issuecomment-941908166).

**Comment by yairopro** [comment]
#10262

**Comment by dan-doyon-endear** [comment]
Just ran into this just now, using the browser back and then forward was easiest way to reproduce. `nextState` is being set to `undefined` prior to testing `nextState.routes.length` inside of the `BaseRouter`.  If (at a minimum) a guard could be put in there to prevent this and just sent user to default route -assuming it can't be recovered, that would really help. I can see how my company feels about me doing PRs for open source.

**Comment by mrfr0g** [comment]
@dan-doyon-endear I am also able to reproduce the issue as you're describing. I created a simple example here: https://github.com/mrfr0g/stack-navigation-web-back-forward-bug which describes the issue, and shows how to reproduce it on web.

**Comment by dan-doyon-endear** [comment]
> @dan-doyon-endear I am also able to reproduce the issue as you're describing. I created a simple example here: https://github.com/mrfr0g/stack-navigation-web-back-forward-bug which describes the issue, and shows how to reproduce it on web.

@mrfr0g Sorry, I hadn't seen your earlier post, I created gmail filters as my inbox was getting crowded. Web hasn't been a big focus for us, until now... and I just re-ran into this issue and had sense of deja vu. Did you manage to do a work around?

**Comment by mrfr0g** [comment]
@dan-doyon-endear no worries. Unfortunately I haven't found a workaround for this. I'm hoping that its unlikely that our users will perform this back/forward sequence, but I may need to swap over to another routing library

**Comment by yairopro** [comment]
Hi @dan-doyon-endear 
For us, we didn't. We just hope our users don't find this issue.
