### ISSUE TITLE
Attempted import error: 'shouldUseActivityState' is not exported from 'react-native-screens'

### ISSUE THREAD

**Issue by Tow96** [react-navigation/react-navigation#9129]
**Current Behavior**
Creating a DrawerNavigator causes this warning to show up

**Expected Behavior**
The warning to not appear

- What do you expect should be happening?
- Include a screenshot or video if it makes sense.

**How to reproduce**
Create an expo managed app and write the following to the app.tsx

```
import * as React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { createDrawerNavigator } from '@react-navigation/drawer';
import { enableScreens } from 'react-native-screens';

enableScreens();
const drawer = createDrawerNavigator();

const App: React.FC = () => {
  return (
    <View style={styles.container}>
      <Text>React Native App</Text>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
});

export default App;
```

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| @react-navigation/native       | 5.8.10
| @react-navigation/drawer       |5.11.4
| react-native-screens           |2.10.1 & 2.15.0
| expo                           | sdk 39

**Comment by LorhanSohaky** [comment]
Any news?

**Comment by mheere** [comment]
Same issue on react-navigation/bottom-tabs  (version 5.11.2)
Reinstalled all to latest - but this message keeps blocking the build

**Comment by satya164** [comment]
https://github.com/react-navigation/react-navigation/issues/8993#issuecomment-717233195

**Comment by Gbadamson** [comment]
the issue still prevails

**Comment by bmaciag** [comment]
same issue here

**Comment by datai999** [comment]
"@react-navigation/bottom-tabs": "^5.11.7",
   "react-native-screens": "~2.15.0",
same issue here

**Comment by DaviDiibo** [comment]
tenia el mismo problema , solo ejecute el siguiente comando y el problema desaparecio , no estoy seguro de que ese sea la solucion , pero por mi parte sirvio 
no agregue nada de codigo ni importe nada , solo ejecute ese comando y ya 


expo install expo-keep-awake

**Comment by velociwabbit** [comment]
Is this closed?  I am getting the same error

**Comment by ApetweBc** [comment]
Same Error on my side. 
Code AppNavigator.js
```
import React from "react";
import { createStackNavigator } from "@react-navigation/stack";
const Stack = createStackNavigator();
const MoreNavigator = () => (
  <Stack.Navigator>
    <Stack.Screen name="Ghaba" component={GhabaScreen} />
    <Stack.Screen name="Shogun" component={ShogunScreen} />
  </Stack.Navigator>
);

export default MoreNavigator;
``` 
on app.js 
```
export default function app() {
  return (
    <NavigationContainer theme={navigationTheme}>
      <AppNavigator />
    </NavigationContainer>
  );
}
```

**Comment by ameer2468** [comment]
Yep getting this error too...

**Comment by Gbadamson** [comment]
I guess the components for the landing component page has not been imported

**Comment by XamuelUG** [comment]
upgraded expo to 41.0.1 and react-native-screens to 3.0.0
~~removed warning

**Comment by XamuelUG** [comment]
> Yep getting this error too...

upgraded expo to 41.0.1 and react-native-screens to 3.0.0
~~removed warning
