### ISSUE TITLE
Custom animation for certain navigation.replace action

### ISSUE THREAD

**Issue by sergeymild** [react-navigation/react-navigation#9131]
**Current Behavior**
For example i have a deep categories screens:
`->vehicles->cars->mazda`
I am using `navigation.replace` for move forward but when i want to return back i can't just use `navigation.goBack()`
i need to use `navigation.replace` again, but i want to set ios like pop animation for that current action so user can see that he is coming back to previous screen.
but `navigation.replace` always use `push` like animation

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| @react-navigation/native       | ^5.8.10
| @react-navigation/stack        | ^5.12.8
| react-native-gesture-handler   | ^1.8.0
| react-native-safe-area-context | ^3.1.9
| react-native-screens           |  ^2.15.0
| react-native                   | ^5.8.10

**Comment by satya164** [comment]
https://reactnavigation.org/docs/stack-navigator/#animationtypeforreplace
