### ISSUE TITLE
Cannot access element inside ScrollView using testing tool Appium

### ISSUE THREAD

**Issue by ghost** [react-navigation/react-navigation#9132]
**Current Behavior**

The elements inside ScrollView of the root tab screen are not accessible for Appium, the ScrollView is displayed as "Interactions are not available for this element" and I cannot select elements inside. Check the screen:

<img width="1081" alt="Screenshot 2020-12-07 at 14 10 35" src="https://user-images.githubusercontent.com/67360921/101356350-9de6bf00-38a0-11eb-8dd6-231a7dc2c8cf.png">

When I add the `accessible=true` prop to ScrollView - the items are still not accessible, but when I replace ScrollView with View and add that prop - I can access nested elements.
The same problem when I add FlatList and remove ScrollView - the elements inside FlatList are not accessible, but others are. 

Please, note, that access to nested elements is not working only for the Tab.Screen elements.

**Expected Behavior**

Access each element inside the root screen of the navigation tab.

**How to reproduce**

Check the following code:

```
import * as React from 'react';
import { Text, View, SafeAreaView, ScrollView } from 'react-native';
import { NavigationContainer } from '@react-navigation/native';
import {
  createStackNavigator,
  TransitionPresets,
} from '@react-navigation/stack';
import { createBottomTabNavigator } from '@react-navigation/bottom-tabs';

function RandomScreen() {
  return (
    <SafeAreaView style={{ flex: 1 }}>
      <ScrollView style={{ flex: 1 }}>
        <Text>This is item I cannot access</Text>
        <Text>This is item I cannot access</Text>
        <Text>This is item I cannot access</Text>
        <Text>This is item I cannot access</Text>
        <Text>This is item I cannot access</Text>
      </ScrollView>
    </SafeAreaView>
  );
}

const Tab = createBottomTabNavigator();

function TabsStack() {
  return (
    <SafeAreaView style={{ flex: 1 }}>
      <Tab.Navigator>
        <Tab.Screen name="RandomScreen" component={RandomScreen} />
      </Tab.Navigator>
    </SafeAreaView>
  );
}

const HomeStack = createStackNavigator();

function HomeStackScreen() {
  return (
    <HomeStack.Navigator headerMode="none" initialRouteName="TabsStack">
      <HomeStack.Screen name="TabsStack" component={TabsStack} />
    </HomeStack.Navigator>
  );
}

const forFade = ({ current }) => ({
  cardStyle: {
    opacity: current.progress,
  },
});

const MainStack = createStackNavigator();

function MainStackScreen() {
  return (
    <MainStack.Navigator headerMode="none">
      <MainStack.Screen
        name="HomeStackScreen"
        component={HomeStackScreen}
        options={{ cardStyleInterpolator: forFade }}
      />
    </MainStack.Navigator>
  );
}

const RootStack = createStackNavigator();

export default function App() {
  return (
    <NavigationContainer>
      <RootStack.Navigator
        initialRouteName="MainStackScreen"
        headerMode="none"
        mode="modal"
        screenOptions={{
          gestureEnabled: true,
          cardOverlayEnabled: true,
          ...TransitionPresets.ModalSlideFromBottomIOS,
        }}>
        <RootStack.Screen name="MainStackScreen" component={MainStackScreen} />
      </RootStack.Navigator>
    </NavigationContainer>
  );
}
```

**Your Environment**

| software                      | version |
| ----------------------------- | ------- |
| iOS or Android                | 11.4
| @react-navigation/native      | ^5.8.10
| @react-navigation/bottom-tabs | ^5.11.2
| react-native-screens          | ^2.11.0
| react-native                  | 0.60.4
| expo                          | - 
| node                          | 10.16.3
| yarn                   | 1.12.3

**Comment by garrottkai** [comment]
same issue here

**Comment by joxenford** [comment]
This bug is affecting our app as well.  Any estimated time to resolution?

**Comment by jennifersalas** [comment]
Same issue here, but experiencing it on react-navigation 4.4.3

**Comment by Abhijith-UST** [comment]
Same issue affecting for me as well, Any fix for this issue? 
**Details**
```
React version: "react-native": "0.67.2"
Appium: 1.22.2
Simulator: iPhone 8 Plus , (15.2)
```

**Comment by thebigredgeek** [comment]
No updates?  This makes it impossible to write Appium based test automation for iOS.  Appium is the most popular test automation framework, so this essentially makes it difficult to write iOS test automation in general :(

**Comment by caseygrimm** [comment]
This is crippling our test automation as well.  We'd like to know if there's a fix in the works before we spend time and focus on a replacement for Appium

**Comment by satya164** [comment]
PRs for a fix is welcome

**Comment by shimo44** [comment]
help plz @mykola-mokhnach

**Comment by himanshuchand** [comment]
Same issue here, its making difficult to write automation for iOS

**Comment by AMEntwistle** [comment]
I had what I believed to be this issue, however I increased the snpshotMaxDepth setting and was able to find elements within a ScrollView.

**Comment by kirannk-1306** [comment]
Hi @AMEntwistle, Thanks for the response. Can you please let me know how you have set the snapshotMaxDepth setting? I am currently using the below approach.

curl -H 'Content-type: application/json' -X POST http://localhost:4723/wd/hub/session/$sid/appium/settings -d '{"settings":{ "customSnapshotTimeout": 50000, "snapshotMaxDepth": 64, "ignoreUnimportantViews" : true }}'

Please let me know if something can be set on Appium inspector, Thanks in advance.

**Comment by AMEntwistle** [comment]
> Hi @AMEntwistle, Thanks for the response. Can you please let me know how you have set the snapshotMaxDepth setting? I am currently using the below approach.
> 
> curl -H 'Content-type: application/json' -X POST http://localhost:4723/wd/hub/session/$sid/appium/settings -d '{"settings":{ "customSnapshotTimeout": 50000, "snapshotMaxDepth": 64, "ignoreUnimportantViews" : true }}'
> 
> Please let me know if something can be set on Appium inspector, Thanks in advance.

I set mine using a desired capabilities json object which includes:

`  "settings[snapshotMaxDepth]": 65`

You can do this in the inspector as well

**Comment by shimo44** [comment]
@wswebcreation given your experience with appium and react-native, any ideas on a solution to this issue? Thanks

**Comment by miriarte33** [comment]
Bumping this thread as well: For us specifically, we have a FlatList nested in a View that cannot be accessed via appium. When I remove the View it works but we need that View there for styling/functionality purposes. I believe FlatList uses ScrollView under the hood so it might be related

**Comment by vadimlab** [comment]
Please suggest any solutions here guys and react native maintainers

**Comment by hitesh-grover** [comment]
any solution?

**Comment by sthota-fms** [comment]
any update?

**Comment by zbranevichfinstek** [comment]
still relevant

**Comment by byteofmydream** [comment]
+1

**Comment by lorenc-tomasz** [comment]
The same problem :(

**Comment by avlaev** [comment]
I have the exact same problem. Is there any solution?

**Comment by lorenc-tomasz** [comment]
At least I didn't find any. It's blocking UI test on iOS :(

**Comment by h2grover** [comment]
If you guys have code base access try this `accessible=false`
I am able to access elements after that.

https://reactnative.dev/docs/accessibility

**Comment by avlaev** [comment]
@satya164  are you having difficulty to reproduce the issue? It seems strange since so many developers see it. For me it is enough to just create a scroll view with any view inside of it and try to access this view by id. It doesn't work for me.

**Comment by satya164** [comment]
I don't use appium. reproducing it requires a project with appium setup and i don't have the time to learn and set it up myself. if you provide a repro then anyone willing to help can easily repro and debug the issue

**Comment by AlixBou** [comment]
Hello, I have the same issue. 

I have opened a support demand [here](https://discuss.appium.io/t/react-native-when-a-view-translate-of-more-than-the-width-of-the-screen-the-view-doesnt-appear-any-more-on-appium/38866) 
Reproduction is available [here](https://github.com/AlixBou/reproduction-appium)

You can simplify the exemple just by writing the following code in any react-native app : 
`  <Animated.View>
        <View style={{position : 'absolute', left: 0}}>
               <Text testID='blip'>Hello</Text>
        </View>
   </Animated.View>`
   
   With that code, the text testID is impossible to reach even when adding accessible={false} on the two parents.

**Comment by Girish-GAP** [comment]
The issue is still relevant, no workaround is working.

**Comment by newnok6** [comment]
still found this issue

**Comment by lucatomarelli** [comment]
We have the same issue with Flatlist at the moment.

**Comment by PawelErnestLuczak** [comment]
it is not only Appium. Native ios XCUItest can't see elements inside container UIView put inside a UIScrollView.
