### ISSUE TITLE
React Navigation Drawer doubling up URI parameter

### ISSUE THREAD

**Issue by reggi** [react-navigation/react-navigation#9134]
**Current Behavior**

Reproduced here https://github.com/reggi/drawer-demo/blob/main/App.tsx
StackOverflow question here https://stackoverflow.com/questions/65161009/react-navigation-drawer-doubling-up-uri-parameter

When I refresh the url `:id` duplicates, then when I refresh again, because there's no route for /dashboard/:id/:id it falls back.

![NgaPl](https://user-images.githubusercontent.com/296798/101399940-2dd73980-389e-11eb-81dc-bfa24df2fd96.gif)

**Expected Behavior**

On refresh for there not to be two `:id`'s

**How to reproduce**

I've included reproducible repo. (https://github.com/reggi/drawer-demo)

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |
| @react-navigation/native       | 5.8.10
| @react-navigation/drawer       | 5.11.4 
| react-native-reanimated        | 1.13.0
| react-native-gesture-handler   | 1.7.0
| react-native-safe-area-context | 3.1.4
| react-native-screens           | 2.10.1
| react-native                   | 0.63.3
| expo                           | 29.0.2
| node                           |  12.18.3
| npm or yarn                    | 1.22.5

**Comment by reggi** [comment]
I believe I've figured out how to have nested navigation work, like this: 

```
import React from 'react';
import {View} from 'react-native';
import {NavigationContainer} from '@react-navigation/native';
import {createStackNavigator} from '@react-navigation/stack';
import {createDrawerNavigator} from '@react-navigation/drawer';

const Drawer = createDrawerNavigator();
const Stack = createStackNavigator();

export function Dashboard() {
  return (
    <Drawer.Navigator drawerType='permanent' openByDefault>
      <Drawer.Screen name={'A'} component={View}  />
      <Drawer.Screen name={'B'} component={View} />
    </Drawer.Navigator>
  )
}

export default function App() {
  return (
      <NavigationContainer
        linking={{
          prefixes: ['https://localhost:19006'],
          config: {
            screens: {
              Home: '',
              Dashboard: {
                path: '/dashboard',
                screens: {
                  A: '/A',
                  B: '/B'
                }
              },
            },
          }
        }}>
        <Stack.Navigator>
          <Stack.Screen name="Home" component={View} />
          <Stack.Screen name="Dashboard" component={Dashboard} />
        </Stack.Navigator>
      </NavigationContainer>
    );
}
```

However this does not allow me to have an arbitrary number of dynamic `Drawer` elements populated on load (from a fetch call) and allow for routing. It seems `linking.config.screens` would need to know the `:id` or dynamic `name` of every drawer with this method.

**Comment by reggi** [comment]
I would need something like this:

```
      <NavigationContainer
        linking={{
          prefixes: ['https://localhost:19006'],
          config: {
            screens: {
              Home: '',
              Dashboard: {
                path: '/dashboard',
                screens: {
                  ['*']: '/:id?',
                }
              },
            },
          }
        }}>
```

**Comment by reggi** [comment]
If I could prevent the automatic url change from the drawer I'd rather change the URL manually is this possible (screams into void).

**Comment by satya164** [comment]
You can populate properties for `screens` inside the `linking` object the same way you create new screens inside drawer. React Navigation needs to know the full configuration to manage URLs.
