### ISSUE TITLE
error when using NavigationContainer

### ISSUE THREAD

**Issue by Rintsy** [react-navigation/react-navigation#9136]
error when using NavigationContainer
![Capture d’écran 2020-12-09 à 20 08 35](https://user-images.githubusercontent.com/67157400/101662836-0a0d2280-3a5b-11eb-80e8-42c9f1da9981.png)

react navigation has a Linking.addEventListener error, the error occurs when we wrap the stack or the tabBarbottom with the NavigationContainer, I think it's bug is related to the react native navigation version

version of package
   "@react-navigation/native": "^5.8.10",
    "@react-navigation/stack": "^5.12.8",
    "react": "16.13.1",
    "react-native": "0.63.4",

**Comment by okwasniewski** [comment]
Please follow the issue template. Closing this
