### ISSUE TITLE
preventDefault() does not work with beforeRemove listener when using createNativeStackNavigator

### ISSUE THREAD

**Issue by ComputerWolf** [react-navigation/react-navigation#9137]
**Current Behavior**

`preventDefault()` does not work with `beforeRemove` listener when using `createNativeStackNavigator` when header back button is pressed. However, it works properly using the Android back button. Not sure if this is a react-navigation or react-native-screens bug since it works in some cases.

[React Native Screens issue](https://github.com/software-mansion/react-native-screens/issues/742)

**Expected Behavior**

`preventDefault()` prevents the navigation for all methods of navigating.

**How to reproduce**

I have used the "Preventing going back" code example and modified it to use createNativeStackNavigator. This causes the Alert to appear _after_ the navigation is complete when clicking the back button in the header.

[Snack](https://snack.expo.io/@computerwolf/preventing-going-back---native-stack-navigator?preview=true&platform=android)

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Android
| @react-navigation/native       | 5.8.10
| react-native-screens | 2.15.0
| react-native                   | 0.63.3
| expo                           |
| node                           | 14.8.0
| npm or yarn                    | npm

**Comment by satya164** [comment]
I'm closing this since the issue belongs to the react-native-screens repo
