### ISSUE TITLE
How to navigate a third nested screen?

### ISSUE THREAD

**Issue by nimabrownlee** [react-navigation/react-navigation#9142]
**Current Behavior**

- RootNavigator (StackNavigator)
  - MainScreen
    - Tabs (TabNavigator)
       - TabScreen1
           - NestedStack (StackNavigator)
               - RootScreen
               - TestScreen

My goal is to navigate from `MainScreen` to `TestScreen`. Now thats possible with `navigation.navigate('TabScreen1', { screen: 'TestScreen '})`. The issue I have is that I want `TestScreen` to have a back button to `RootScreen`. That is also possible adding `initial: false` but when navigating from `MainScreen` to `TestScreen`, it goes first to `RootScreen` and then `TestScreen`. How can I fix this?

**Expected Behavior**

It should navigate directly to `TestScreen` and also have a back button.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Android
| @react-navigation/native       | 5.7.6
| @react-navigation/stack        | 5.9.3
| react-native-gesture-handler   | 1.7.0
| react-native-safe-area-context | 3.1.4
| react-native-screens           | 2.10.1
| react-native                   | 0.63.3
| expo                           | 39.0.2
| node                           | 12+
| npm or yarn                    | yarn

**Comment by nimabrownlee** [comment]
Yes. The issue persists.

**Comment by satya164** [comment]
https://reactnavigation.org/docs/nesting-navigators#passing-params-to-a-screen-in-a-nested-navigator

**Comment by nimabrownlee** [comment]
@satya164 Can you please stop closing that issues so fast? Let's at least resolve it before you redirect me to the docs. I literally mentioned that the solution in the docs doesn't work. Please re-open it.

**Comment by satya164** [comment]
What you have written sounds like expected behaviour. If you're reporting a bug, please provide a repro as asked in the template or at least a GIF/video of what exactly is wrong.
