### ISSUE TITLE
Status bar not reappearing after being hidden on the first screen

### ISSUE THREAD

**Issue by sagarshakya** [react-navigation/react-navigation#9144]
**Current Behavior**

When hiding the status bar on a stack on the first screen, the status bar is not showing on the second screen.

```
import * as React from 'react';
import {Text, StatusBar, Button, StyleSheet} from 'react-native';
import {NavigationContainer} from '@react-navigation/native';
import {createStackNavigator} from '@react-navigation/stack';
import {SafeAreaProvider, SafeAreaView} from 'react-native-safe-area-context';

function Screen1({navigation}) {
  return (
    <SafeAreaView style={[styles.container, {backgroundColor: '#6a51ae'}]}>
      <StatusBar hidden />
      <Text style={{color: '#fff'}}>Light Screen</Text>
      <Button
        title="Next screen"
        onPress={() => navigation.navigate('Screen2')}
      />
    </SafeAreaView>
  );
}

function Screen2({navigation}) {
  return (
    <SafeAreaView style={[styles.container, {backgroundColor: '#ecf0f1'}]}>
      <StatusBar barStyle="dark-content" backgroundColor="#ecf0f1" />
      <Text>Dark Screen</Text>
      <Button
        title="Next screen"
        onPress={() => navigation.navigate('Screen1')}
      />
    </SafeAreaView>
  );
}

const Stack = createStackNavigator();

export default function App() {
  return (
    <SafeAreaProvider>
      <NavigationContainer>
        <Stack.Navigator headerMode="none">
          <Stack.Screen name="Screen1" component={Screen1} />
          <Stack.Screen name="Screen2" component={Screen2} />
        </Stack.Navigator>
      </NavigationContainer>
    </SafeAreaProvider>
  );
}

const styles = StyleSheet.create({
  container: {flex: 1, justifyContent: 'center', alignItems: 'center'},
});
```
Here, on `Screen1`, status bar is hidden, but on `Screen2`, status bar is set to show, but it doesn't appear on `Screen2` either.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/66957698/101985741-eee82000-3cb1-11eb-82ed-c74c9033863a.gif)

**Expected Behavior**

The status bar should be hidden on `Screen1` but should reappear on `Screen2`.

**How to reproduce**

Run the code and when you click on the button on `Screen1`, it takes you to `Screen2`.

**Environment**

| software                       | version |
| ------------------------------ | ------- |
| @react-navigation/native       |^5.8.10|
| @react-navigation/stack        |^5.12.8|
| react-native-gesture-handler   |^1.9.0|
| react-native-safe-area-context |^3.1.9|
| react-native                   |0.63.4|

**Comment by raajnadar** [comment]
You need to use the static method `StatusBar` from `react-native` package. https://reactnative.dev/docs/statusbar#methods

**Comment by sagarshakya** [comment]
> You need to use the static method `StatusBar` from `react-native` package. https://reactnative.dev/docs/statusbar#methods

Thanks. It worked.
