### ISSUE TITLE
Custom header on ios stays visible when it's not supposed to.

### ISSUE THREAD

**Issue by ErkanGorgulu** [react-navigation/react-navigation#9152]
**Current Behavior**
When I move from a screen with Header to a screen without header, The header stays visible and doesn't hide. It's a custom header. The thing is it's not even a header. It seems like an image that doesn't respond any touch. You can press other touchables under it.
- What code are you running and what is happening?
`            
<AppStack.Navigator>
              <AppStack.Screen name="Tabs" component={TabScreens} options={({ route, navigation }) => ({
                header: () =>
                  <CommonHeader title={getHeaderTitle(route)}
                    leftButton={HeaderLeftButtonEnum.empty}
                    navigation={navigation} />                   
              })}/>
              <AppStack.Screen name="QRScreen" component={QRScreen}/>
</AppStack.Navigator>
`

`
        <LinearGradient                colors={["#900000", "#D00"]}                start={[0, 0]}                end={[0.65, 0]}            >
        <SafeAreaView>
            
                <View style={styles.contentContainer}>

                    {leftButton == HeaderLeftButtonEnum.empty ? <Text>{"             "}</Text> :
                        leftButton == HeaderLeftButtonEnum.settings ? <TouchableOpacity onPress={() => { navigation.navigate("Settings") }} style={styles.backButton}><SettingIcon width={30} height={30} fill="#FFF" /></TouchableOpacity> :
                            leftButton == HeaderLeftButtonEnum.back && <TouchableOpacity onPress={() => { navigation.goBack() }} style={styles.backButton}><BackButton width={20} height={20} fill="#FFF" /></TouchableOpacity>
                    }
                    <Text style={{ color: "#fff", fontSize: 19, fontFamily: "Ubuntu-Light", alignSelf: "center" }}>
                        {title}
                    </Text>
                    <TouchableOpacity onPress={() => setQrCodeInfoVisible(true)}>
                        <MaterialIcon name="information-outline" size={35} style={{ color: "#fff", marginRight: 20 }} />
                    </TouchableOpacity>
                </View>
                <QrCodeInfoOverlay qrCodeInfoVisible={qrCodeInfoVisible} setQrCodeInfoVisible={setQrCodeInfoVisible} />
            
        </SafeAreaView>
        </LinearGradient>
`
- Include a screenshot or video if it makes sense.
![1](https://user-images.githubusercontent.com/16388246/102221640-6d7fd000-3ef3-11eb-8ed1-1e3ff9ca46fa.png)
![2](https://user-images.githubusercontent.com/16388246/102221643-6eb0fd00-3ef3-11eb-8a60-e4ded0744bb8.png)

**Expected Behavior**

- What do you expect should be happening?
I want to hide the header on the navigated screen.
**How to reproduce**

- You must provide a way to reproduce the problem. If you are having an issue with your machine or build tools, the issue belongs on another repository as that is outside of the scope of React Navigation.
- Either re-create the bug on [Snack](https://snack.expo.io) or link to a GitHub repository with code that reproduces the bug.
- Explain how to run the example app and any steps that we need to take to reproduce the issue from the example app.
- Keep the repro code as simple as possible, with the minimum amount of code required to repro the issue.
- Before reporting an issue, make sure you are on latest version of the package.

**Your Environment**

| software                               | version |
| -------------------------------------- | ------- |
| iOS or Android                         | IOS only
| @react-navigation/native               |5.8.10
| @react-navigation/material-bottom-tabs |5.3.10
| react-native-paper                     |
| react-native                           |
| expo                                   |39.0.3
| node                                   |14.6.0
| npm or yarn                            |6.14.6

**Comment by FrickenHamster** [comment]
I'm getting the same issue on version 5.8.10

**Comment by FrickenHamster** [comment]
It seems to be an issue with the component with the custom header in the navigation stack. If I `replace` instead of navigate away, it won't have the ghost custom border.
I have a hunch this is only showing in these cases because the custom border is bigger than the standard border.

For now, the only workaround I have is to implement the custom header in the screen and not the navigation options.

**Comment by satya164** [comment]
Like the documentation mentions, you need to specify `headerMode="screen"` or animate your header: https://reactnavigation.org/docs/stack-navigator#header
