### ISSUE TITLE
[Android] Deep linking not working when app is in background with a destroyed activity

### ISSUE THREAD

**Issue by Ma3aXaH** [react-navigation/react-navigation#9154]
**Current Behavior**

Deep linking works perfectly when app is in foreground (navigates to the right screen) or is closed completely (opens app with the right screen). But in case when app is in background with a destroyed activity deep linking fails to open the correct screen and opens the default one instead.
In other words resolving uri `myapp://ss` leads to:

- if app is in foreground - opens SecondScreen (works as intended)
- if app is in background - opens SecondScreen (works as intended)
- if app is in background with a destroyed activity  - opens FirstScreen (opens wrong screen)
- if app is closed/killed - opens SecondScreen (works as intended)

```jsx
import React from 'react';
import {
  View,
  Text,
} from 'react-native';
import { createStackNavigator } from '@react-navigation/stack'
import { NavigationContainer } from '@react-navigation/native';

const FirstScreen = ({}) => {
  return (
    <View style={{flex: 1, alignItems: 'center', justifyContent: 'center'}}>
      <Text>First screen</Text>
    </View>
  )
}

const SecondScreen = ({}) => {
  return (
    <View style={{flex: 1, alignItems: 'center', justifyContent: 'center'}}>
      <Text>Second screen</Text>
    </View>
  )
}

const Stack = createStackNavigator()

const App = () => {

  const deeplink = {
    prefixes: ['myapp://'],
    config: {
      initialRouteName: 'FirstScreen',
      screens: {
        FirstScreen: 'fs',
        SecondScreen: 'ss'
      }
    }
  }

  return (
    <NavigationContainer linking={deeplink}>
      <Stack.Navigator>
        <Stack.Screen name='FirstScreen' component={FirstScreen}/>
        <Stack.Screen name='SecondScreen' component={SecondScreen}/>
      </Stack.Navigator>
    </NavigationContainer>
  )
};

export default App;
```
Here's a snippet of the manifest with deep linking configuration
```xml
          <intent-filter>
              <data android:scheme="myapp"/>
              <action android:name="android.intent.action.VIEW"/>
              <category android:name="android.intent.category.DEFAULT"/>
              <category android:name="android.intent.category.BROWSABLE"/>              
          </intent-filter>
```

**Expected Behavior**

Deep link should always open the correct screen

**How to reproduce**

Here's a minimal [repro](https://github.com/Ma3aXaH/navtest) if needed. But i think this bug should be reproducible with any app using a deep link feature just by following the steps.
Steps to reproduce the bug:

1. Enable developer options on your Android device
2. Enable **Don't keep activities** in developer options
3. Open the app
4. Tap Home button on your device to navigate away from the app (it should remain in background)
5. Reopen app using a deep link ( I used `npx uri-scheme open myapp://ss --android` from terminal)

**Possible idea why this happens**

When bringing the app back from background to foreground with a deep link it should handle the Linking `url` event from `react-native` ( which actually triggers if I subscribe to it separately inside of the App component).
But since activity was released by the OS opening it triggers recreation of the NavigationContainer. But instead of parsing the deep link url it tries to `getInitialUrl` from Linking which returns `null` since context of the app was never completely removed in the first place.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| @react-navigation/native       | ^5.8.10
| @react-navigation/stack       | ^5.12.8
| react    | 16.13.1
| react-native                   | 0.63.4

**Comment by satya164** [comment]
This sounds like a React Native bug rather than React Navigation issue. Since React Navigation just listenes to `Linking` events and handles them.

**Comment by satya164** [comment]
Maybe, it'd be good to have something like `getLastURL` rather than `getInitialURL`, which would let us get any previous URL events that we might have missed before rendering.

**Comment by Ma3aXaH** [comment]
@satya164 Thanks for the reply. I guess I'll try to implement my own react native module which return the correct url since react itself does not provide such method. And then use it in the `getInitialURL` of `linking` object.

**Comment by Hamawis** [comment]
Any update on it?

**Comment by Ma3aXaH** [comment]
Hi @Hamawis!
As I've mentioned in my previous comment I ended up creating my own react native module which returns the last url instead of using `Linking`'s `getInitialURL`. And then used it in the `config` prop of the navigation container

```jsx
config: {
  	getInitalURL: () => {
	return Promise.race([
		MyLinkingModule.getLastURL(),
		new Promise((resolve) =>
			// Timeout in 150ms if `getInitialState` doesn't resolve
			// Workaround for https://github.com/facebook/react-native/issues/25675
			setTimeout(resolve, 150)
		),
	    ])
  	},
	// other fields
}
```

And for the module itself:

```java
public class MyLinkingModule extends ReactContextBaseJavaModule implements ActivityEventListener {
    private ReactContext context;
    private Uri lastIntentData = null;

    public MyLinkingModule(@NonNull ReactApplicationContext reactContext) {
        super(reactContext);
        this.context = reactContext;
    }

    @NonNull
    @Override
    public String getName() {
        return "MyLinkingModule";
    }

    @ReactMethod
    public void getLastURL(final Promise promise) {
        Activity activity = context.getCurrentActivity();

        if (activity != null) {
            Uri data = lastIntentData != null ? lastIntentData : activity.getIntent().getData();
            if (data != null) {
                promise.resolve(data.toString());
            }
        }
    }

    @Override
    public void onActivityResult(Activity activity, int requestCode, int resultCode, Intent data) {

    }

    @Override
    public void onNewIntent(Intent intent) {
        lastIntentData = intent.getData();
    }
}
```
Maybe it's not the most elegant solution, but at least it works in my case.
Hope this will suffice.

**Comment by Marcoo09** [comment]
I'm on react navigation 5 and I have this issue, the way that I fixed that is manually getting the initialUrl and parse the roue manually:

```javascript
import {useNavigation} from '@react-navigation/core';
import {useState, useEffect} from 'react';
import {Linking} from 'react-native';
import {Routes} from '~/navigation/Routes';

type OuterProps = Pick<ReturnType<typeof useNavigation>, 'navigate'>;

export const useHandleAndroidDeepLink = (navigate: OuterProps['navigate']) => {
  const [url, setUrl] = useState<string | null>(null);
  const [processing, setProcessing] = useState(true);

  useEffect(() => {
    const getUrlAsync = async () => {
      // Get the deep link used to open the app
      const initialUrl = await Linking.getInitialURL();

      setUrl(initialUrl);
      setProcessing(false);
    };

    getUrlAsync();
  }, []);

  useEffect(() => {
    if (!!url) {
      const splittedUrl = url?.split('://');
      if (splittedUrl?.length > 1) {
        const urlToNavigate = splittedUrl[1];
        const route = getRoute(urlToNavigate);
        if (route) {
          navigate(route);
        }
      }
    }
  }, [url, navigate]);
};

const getRoute = (key: string) => {
  switch (key) {
    case 'yourkey':
      return yourroute;
    default:
      return undefined;
  }
};

```
I guess that this problem is solved on react navigation 6 but now I cannot update.

**Comment by soutua** [comment]
I was able to fix this on our application by handling onNewIntent in the application's MainActivity, otherwise the original intent gets used and not the one containing the deep link:

```
@Override
public void onNewIntent(Intent intent) {
    super.onNewIntent(intent);
    setIntent(intent);
}
```

**Comment by vdutz** [comment]
Was having the same problem only on Android. The following worked for us: adding the following `getInitialURL` parameter inside the linking config: 

```javascript
const linking: LinkingOptions<RootStackParamList> = {
  prefixes: [
    ''myapp://'',
     ...
  ],
  config: {
    ...
  },
  async getInitialURL() {
    return Linking.getInitialURL();
  },
}
```

Hope this helps someone!

**Comment by EvgenMarchuk-art** [comment]
> I was able to fix this on our application by handling onNewIntent in the application's MainActivity, otherwise the original intent gets used and not the one containing the deep link:
> 
> ```
> @Override
> public void onNewIntent(Intent intent) {
>     super.onNewIntent(intent);
>     setIntent(intent);
> }
> ```

In two weeks of searching, this is the only working solution! Thank you.

**Comment by martinezguillaume** [comment]
> I was able to fix this on our application by handling onNewIntent in the application's MainActivity, otherwise the original intent gets used and not the one containing the deep link:
> 
> ```
> @Override
> public void onNewIntent(Intent intent) {
>     super.onNewIntent(intent);
>     setIntent(intent);
> }
> ```

Oh wow, I think this is it
After weeks of searching, your solution seems to fix deeplinking on android perfectly... many thanks
