### ISSUE TITLE
Problem in Type checking screens, when using variable to address screen name

### ISSUE THREAD

**Issue by alexakasanjeev** [react-navigation/react-navigation#9163]
**Current Behavior**

I have created a variable to store screen name, and I want to use this variable  everywhere when denoting this screen

```js
export const NAVIGATION_TO_X_SCREEN = 'XScreen;
```

I'm using this variable in `StackNavigation`

```jsx
type StackParamList = {
  [NAVIGATION_TO_X_SCREEN]: { name: string; };
}
//...
const Stack = createStackNavigator<StackParamList>();
//...
<Stack.Navigator>
    <Stack.Screen
      name={NAVIGATION_TO_X_SCREEN}
      component={XScreen}
    />
</Stack.Navigator>
```

And I'm trying to type check my `XScreen`

```jsx
interface Props {
  route: RouteProp<StackParamList, NAVIGATION_TO_X_SCREEN>; // <========== This is the problem
}

const XScreen = ({
  route: {
    params: { name, extraKey },
  },
}: Props) => {}
```

But I'm not getting type check in screen when I use `NAVIGATION_TO_X_SCREEN` in `RouteProp` second variable in `<>` this

![Screenshot from 2020-12-20 16-50-33](https://user-images.githubusercontent.com/13250741/102712221-67b82f00-42e5-11eb-8b62-920e7bba0d11.png)

When I'm using this, then I am getting correct type check

```js
interface Props {
  route: RouteProp<StackParamList, 'XScreen`>; // <========== Now Working fine
 // But I don't want to do this, I want to use the variable
}
```

**Expected Behavior**

TypeScript should have warned there is no key named `extraKey` inside params for `XScreen`, but instead I'm getting this

**How to reproduce**

If you want I can provide a workable code snippet

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
|  Android                 |    10 |
| @react-navigation/native       | ^5.8.10 |
| @react-navigation/stack        | ^5.12.8 |
| react-native-gesture-handler   | ^1.9.0 |
| react-native-safe-area-context | ^3.1.9 |
| react-native-screens           | ^2.15.0 |
| react-native                   | 0.63.3 |
| node                           | v10.19.0 |
| yarn                    | 1.22.4 |

**Comment by KurtMar** [comment]
I was able to overcome this issue by using enums instead of strings. I don't know what the best practice is here, but this should work:

```typescript
export enum NAV_SCREENS {
  NAVIGATION_TO_X_SCREEN = 'XScreen'
}

type StackParamList = {
  [NAV_SCREENS.NAVIGATION_TO_X_SCREEN]: { name: string; };
}
//...
const Stack = createStackNavigator<StackParamList>();
//...
<Stack.Navigator>
    <Stack.Screen
      name={NAV_SCREENS.NAVIGATION_TO_X_SCREEN}
      component={XScreen}
    />
</Stack.Navigator>
And I'm trying to type check my XScreen

interface Props {
  route: RouteProp<StackParamList, NAV_SCREENS.NAVIGATION_TO_X_SCREEN>; // <========== This should now work
}

const XScreen = ({
  route: {
    params: { name, extraKey },
  },
}: Props) => {}
```

**Comment by satya164** [comment]
Like the error says, you can't use values in types. Either use actual strings, `typeof` or enums like @KurtMar suggested.

**Comment by alexakasanjeev** [comment]
ok, thank you for all your help

**Comment by alexakasanjeev** [comment]
@KurtMar @satya164 The solution above mentioned solved the problem above, but now whenever I'm trying to use `navigtaion.navigate(NAV_SCREENS.NAVIGATION_TO_X_SCREEN)` I am getting eslint error

```
Argument of type 'import("/home/abc/demoproject/src/navigation/routeNames").NAV_SCREEN' is not assignable to parameter of type '{ key: string; params?: {} | undefined; } | { name: Routes.NAVIGATION_TO_X_SCREEN | Routes.NAVIGATION_TO_Y_SCREEN; key?: string | undefined; params: {}; }'
```

**Comment by KurtMar** [comment]
Please provide your import statement for NAV_SCREENS.

**Comment by alexakasanjeev** [comment]
Hi @KurtMar 

This is `routeNames.ts` file

```ts
export enum NAV_SCREENS {
  NAVIGATION_TO_X_SCREEN = 'XScreen',
  NAVIGATION_TO_Y_SCREEN = 'yScreen',
}
```

This is how I'm importing in file

```ts
import { NAV_SCREENS } from '../../navigation/routeNames';

// and using in onPress

navigtaion.navigate(NAV_SCREENS.NAVIGATION_TO_X_SCREEN)
```

**Comment by KurtMar** [comment]
```typescript
type StackParamList = {
  [NAV_SCREENS.NAVIGATION_TO_X_SCREEN]: { name: string; };
}
```

In that type you declare that you will always provide an object with the property 'name' as the second argument to navigate(). So either change the type to:

```typescript
type StackParamList = {
  [NAV_SCREENS.NAVIGATION_TO_X_SCREEN]: { name: string; } | undefined;
}
```

The above is not tested, but should work. Or just include the name parameter:

```typescript
navigation.navigate(NAV_SCREENS.NAVIGATION_TO_X_SCREEN, { name: 'abc' })
`
``

**Comment by alexakasanjeev** [comment]
@KurtMar Thank you so much, 

I'm trying to learn TypeScript by making a demo, do you know any good TypeScript tutorial, apart from official docs

**Comment by KurtMar** [comment]
That's the hardest question so far :) People learn in different ways. Maybe search youtube for concepts like 'typescript union and intersection' or browse typescript projects on github. NodeJS typescript projects might be good to look at.
