### ISSUE TITLE
onReady={() => {}} callback called before navigationRef is set. (getCurrentRoute() undefined onReady)

### ISSUE THREAD

**Issue by JDMathew** [react-navigation/react-navigation#9170]
**Current Behavior**

I am following the react native screen navigation documentation and passing a callback to onReady to set the routeNameRef.current to the current route name, however when onReady runs the callback the navigationRef hasn't be set. 

`navigationRef.current?.getCurrentRoute().name` is `undefined` when calling:

`routeNameRef.current = navigationRef.current?.getCurrentRoute().name`

If I call a setTimeout for 1 second then navigationRef has been set. 

**Expected Behavior**

- I expect the onReady callback to only be called after navigationRef is set. 

**My Navigation Component**

```
import React, { useEffect, useState } from 'react'
import { NavigationContainer, DefaultTheme } from '@react-navigation/native'
import { navigationRef, routeNameRef, isReadyRef } from './RootNavigation'
import { createStackNavigator } from '@react-navigation/stack'
import RNBootSplash from 'react-native-bootsplash'
import analytics from '@react-native-firebase/analytics'

import NotFoundScreen from 'src/screens/NotFound'
import { RootStackParamList } from 'src/types'
import BottomTabNavigator from './BottomTabNavigator'
import AuthNavigator from './AuthNavigator'
import OnboardingNavigator from './OnboardingNavigator'
import LinkingConfiguration from './LinkingConfiguration'
import { useGlobalStore } from 'src/store'
import Splash from 'src/screens/Splash'

export default function Navigation () {
  const { store } = useGlobalStore()
  const [isLoading, setIsLoading] = useState(false)

  useEffect(() => {
    const initializer = async () => {
      setIsLoading(true)
      // …do multiple sync or async tasks
      setIsLoading(false)
    }

    initializer().finally(async () => {
      await RNBootSplash.hide({ fade: true })
    })

    return () => {
      isReadyRef.current = false
    }
  }, [])

  return (
    <NavigationContainer
      ref={navigationRef}
      linking={LinkingConfiguration}
      theme={DefaultTheme}
      onReady={() => {
        routeNameRef.current = navigationRef?.current?.getCurrentRoute()?.name
        isReadyRef.current = true
      }}
      onStateChange={async (state) => {
      const previousRouteName = routeNameRef.current
      const currentRouteName = navigationRef.current.getCurrentRoute().name //getActiveRouteName(state) 

        if (previousRouteName !== currentRouteName) {
          await analytics().logScreenView({
            screen_name: currentRouteName,
            screen_class: currentRouteName
          })
        }
        // Save the current route name for later comparision
        routeNameRef.current = currentRouteName
      }}
    >
      {
        store.initialized || isLoading ? <RootNavigator /> : <Splash />
      }
    </NavigationContainer>
  )
}

const Stack = createStackNavigator<RootStackParamList>()

function RootNavigator () {
  const { store } = useGlobalStore()
  const initialRouteName = store.token ? 'Root' : 'Auth'
  return (
    <Stack.Navigator initialRouteName={initialRouteName} screenOptions={{ headerShown: false }}>
      <Stack.Screen name='Auth' component={AuthNavigator} />
      <Stack.Screen name='Onboarding' component={OnboardingNavigator} />
      <Stack.Screen name='Root' component={BottomTabNavigator} options={{ cardStyle: { backgroundColor: '#fff' } }} />
      <Stack.Screen name='NotFound' component={NotFoundScreen} options={{ title: 'Oops!' }} />
    </Stack.Navigator>
  )
}
```

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | iOS 13.3
| @react-navigation/native       |  "^5.7.3"
| react-native                   | "0.63.3"
| node                           | "v12.18.3"
| npm or yarn                    | yarn "1.22.10"

**Comment by satya164** [comment]
You're conditionally rendering the navigator:

```js
store.initialized || isLoading ? <RootNavigator /> : <Splash />
```

`onReady` fires when the container finishes mounting (https://reactnavigation.org/docs/navigation-container/#onready). If you don't have a navigator rendered, there's no current route name.

> I expect the onReady callback to only be called after navigationRef is set.

The ref is already set, you just don't have any navigator rendered.

Instead of conditionally rendering the navigator, you need to conditionally render the container instead.

**Comment by roryabraham** [comment]
I'm seeing this happen in a slightly different way. I'm trying to perform some navigation when a push notification is tapped, and it works fine when the app is backgrounded, but not when the app is completely closed. Basically I have something like this:

### Navigation.js

```javascript
export const navigationRef = createNavigationContainerRef();
let initialRoute = null;

function navigate(route) {
    console.log(`trying to navigate to ${route}`);
    if (navigationRef.isReady()) {
        console.log(`navigationRef ready, navigating to ${route}`);
        
        // Some business logic, but basically just this
        navigationRef.current.dispatch(someAction);
    } else {
        // Navigation container not yet loaded, set initial route.
        console.log(`navigation not ready, setting initialRoute: ${route}`);
        initialRoute = route;
    }
}

function goToInitialRoute() {
    console.log(`initial route: ${initialRoute}`);
    if (initialRoute) {
        console.log('going to initial route');
        navigate(initialRoute);
    }
}

export default {
    navigate,
    goToInitialRoute,
};
```

### NavigationRoot.js

```javascript
import React, {Component} from 'react';
import PropTypes from 'prop-types';
import {getPathFromState, NavigationContainer} from '@react-navigation/native';
import Navigation, {navigationRef} from './Navigation';
import linkingConfig from './linkingConfig';
import AppNavigator from './AppNavigator';
import FullScreenLoadingIndicator from '../../components/FullscreenLoadingIndicator';

const propTypes = {
    /** Whether the current user is logged in with an authToken */
    authenticated: PropTypes.bool.isRequired,
};

class NavigationRoot extends Component {
    constructor(props) {
        super(props);
    }

    render() {
        return (
            <NavigationContainer
                fallback={<FullScreenLoadingIndicator visible />}
                onReady={Navigation.goToInitialRoute}
                ref={navigationRef}
                linking={linkingConfig}
                documentTitle={{
                    enabled: false,
                }}
            >
                <AppNavigator authenticated={this.props.authenticated} />
            </NavigationContainer>
        );
    }
}

NavigationRoot.propTypes = propTypes;
export default NavigationRoot;
```

And the logs are as follows:

```
// First, the app/navigation container is not ready, as expected
trying to navigate to r/225
navigation not ready, setting initialRoute: r/225

// Then onReady is called
initial route: r/225
going to initial route
trying to navigate to r/225

// So far so good, but the next line is unexpected
navigation not ready, setting initialRoute: r/225
```

So this means that I'm seeing the following:

1. `navigationRef.isReady()` is false
1. `onReady` is called
1. `navigationRef.isReady()` is still false. This seems incorrect to me

Am I doing something wrong, or is this a 🐛? Any help would be greatly appreciated 🙏

**Comment by Alexorz** [comment]
same issue with  @roryabraham

**Comment by MeesMaas** [comment]
@roryabraham did you find a solution by any chance? I have the same problem

**Comment by roryabraham** [comment]
@MeesMaas  I still think that what I posted above is a 🐛, but I was able to work around it by utilizing deep-linking. So in the callback for the `NotificationResponse` event (when the push notification is tapped), call `Linking.openURL(myDeepLink)`. PR is [here](https://github.com/Expensify/App/pull/3877) if it's helpful.

**Comment by akpinarserdar** [comment]
> I'm seeing this happen in a slightly different way. I'm trying to perform some navigation when a push notification is tapped, and it works fine when the app is backgrounded, but not when the app is completely closed. Basically I have something like this:
> 
> ### Navigation.js
> ```js
> export const navigationRef = createNavigationContainerRef();
> let initialRoute = null;
> 
> function navigate(route) {
>     console.log(`trying to navigate to ${route}`);
>     if (navigationRef.isReady()) {
>         console.log(`navigationRef ready, navigating to ${route}`);
>         
>         // Some business logic, but basically just this
>         navigationRef.current.dispatch(someAction);
>     } else {
>         // Navigation container not yet loaded, set initial route.
>         console.log(`navigation not ready, setting initialRoute: ${route}`);
>         initialRoute = route;
>     }
> }
> 
> function goToInitialRoute() {
>     console.log(`initial route: ${initialRoute}`);
>     if (initialRoute) {
>         console.log('going to initial route');
>         navigate(initialRoute);
>     }
> }
> 
> export default {
>     navigate,
>     goToInitialRoute,
> };
> ```
> 
> ### NavigationRoot.js
> ```js
> import React, {Component} from 'react';
> import PropTypes from 'prop-types';
> import {getPathFromState, NavigationContainer} from '@react-navigation/native';
> import Navigation, {navigationRef} from './Navigation';
> import linkingConfig from './linkingConfig';
> import AppNavigator from './AppNavigator';
> import FullScreenLoadingIndicator from '../../components/FullscreenLoadingIndicator';
> 
> const propTypes = {
>     /** Whether the current user is logged in with an authToken */
>     authenticated: PropTypes.bool.isRequired,
> };
> 
> class NavigationRoot extends Component {
>     constructor(props) {
>         super(props);
>     }
> 
>     render() {
>         return (
>             <NavigationContainer
>                 fallback={<FullScreenLoadingIndicator visible />}
>                 onReady={Navigation.goToInitialRoute}
>                 ref={navigationRef}
>                 linking={linkingConfig}
>                 documentTitle={{
>                     enabled: false,
>                 }}
>             >
>                 <AppNavigator authenticated={this.props.authenticated} />
>             </NavigationContainer>
>         );
>     }
> }
> 
> NavigationRoot.propTypes = propTypes;
> export default NavigationRoot;
> ```
> 
> And the logs are as follows:
> 
> ```
> // First, the app/navigation container is not ready, as expected
> trying to navigate to r/225
> navigation not ready, setting initialRoute: r/225
> 
> // Then onReady is called
> initial route: r/225
> going to initial route
> trying to navigate to r/225
> 
> // So far so good, but the next line is unexpected
> navigation not ready, setting initialRoute: r/225
> ```
> 
> So this means that I'm seeing the following:
> 
> 1. `navigationRef.isReady()` is false
> 2. `onReady` is called
> 3. `navigationRef.isReady()` is still false. This seems incorrect to me
> 
> Am I doing something wrong, or is this a 🐛? Any help would be greatly appreciated 🙏

i am having the same problem. were you able to find a solution?

**Comment by roryabraham** [comment]
@akpinarserdar see [this comment](https://github.com/react-navigation/react-navigation/issues/9170#issuecomment-909534765) ... I was able to find a solution using Deep Linking.

**Comment by Stevemoretz** [comment]
This is just a pointless behavior, it's sure better than nothing thanks, but should've automatically kept the rendering off before it was ready or at least let us do it.
