### ISSUE TITLE
Doc example isn't working on expo

### ISSUE THREAD

**Issue by 4E71-NOP** [react-navigation/react-navigation#9174]
**Current Behavior**

From https://reactnavigation.org/docs/localization/
The snack demo isn't working

At example #1 which redirects to: [This](https://snack.expo.io/?platform=android&name=Getting%20started%20%7C%20React%20Navigation&dependencies=%40expo%2Fvector-icons%40*%2C%40react-native-community%2Fmasked-view%40*%2C%40react-navigation%2Fbottom-tabs%40%5E5.8.0%2C%40react-navigation%2Fdrawer%40%5E5.9.0%2C%40react-navigation%2Fmaterial-bottom-tabs%40%5E5.2.16%2C%40react-navigation%2Fmaterial-top-tabs%40%5E5.2.16%2C%40react-navigation%2Fnative%40%5E5.7.3%2C%40react-navigation%2Fstack%40%5E5.9.0%2Creact-native-paper%40%5E4.0.1%2Creact-native-reanimated%40*%2Creact-native-safe-area-context%40*%2Creact-native-gesture-handler%40*%2Creact-native-screens%40*%2Creact-native-tab-view%40%5E2.15.1&sourceUrl=https%3A%2F%2Freactnavigation.org%2Fexamples%2F5.x%2Flocalization.js)
Console output:
```
App.js (2:31)'expo-localization' is not defined in dependencies.
App.js (3:18)'i18n-js' is not defined in dependencies.
App.js (1091:882)Unable to resolve module 'module://expo-localization.js' (Device)
```
Example #2 which redirects to : [This](https://snack.expo.io/?platform=android&name=Getting%20started%20%7C%20React%20Navigation&dependencies=%40expo%2Fvector-icons%40*%2C%40react-native-community%2Fmasked-view%40*%2C%40react-navigation%2Fbottom-tabs%40%5E5.8.0%2C%40react-navigation%2Fdrawer%40%5E5.9.0%2C%40react-navigation%2Fmaterial-bottom-tabs%40%5E5.2.16%2C%40react-navigation%2Fmaterial-top-tabs%40%5E5.2.16%2C%40react-navigation%2Fnative%40%5E5.7.3%2C%40react-navigation%2Fstack%40%5E5.9.0%2Creact-native-paper%40%5E4.0.1%2Creact-native-reanimated%40*%2Creact-native-safe-area-context%40*%2Creact-native-gesture-handler%40*%2Creact-native-screens%40*%2Creact-native-tab-view%40%5E2.15.1&sourceUrl=https%3A%2F%2Freactnavigation.org%2Fexamples%2F5.x%2Flocalization-with-title.js)

Console output:
```
package.json (6:5)Failed to resolve dependency '@react-navigation/drawer@^5.9.0' (request to https://s3-us-west-1.amazonaws.com/snackager-artifacts/snackager-1%2F%40react-navigation~drawer%405.11.4-ios/.done failed, reason: getaddrinfo EAI_AGAIN s3-us-west-1.amazonaws.com)
App.js (2:31)'expo-localization' is not defined in dependencies.
App.js (3:18)'i18n-js' is not defined in dependencies.
```

**Expected Behavior**
Working.

**How to reproduce**
Run the app on device or on snack.

**Your Environment**
None in particular.

**Comment by satya164** [comment]
The localization docs have been removed since they aren't relevant to navigation. So I'm closing this.
