### ISSUE TITLE
navigation.navigate() doesn't work if the 'Screen' still hasn't been loaded 

### ISSUE THREAD

**Issue by sofianear** [react-navigation/react-navigation#9182]
**Current Behavior**
I have a stack navigator `Nav` which has 2 screens __A__ and __B__
When I call `navigation.navigate('B')` from __A__ inside a `useEffect` like this: 
```lang-js
useEffect(()=>{
    navigation.navigate('B');
}, [navigation]);
```
It just doesn't work. The screen stays stuck at __A__ and doesn't navigate to __B__

**Expected Behavior**
The screen should navigate from __A__ to __B__.

**How to reproduce**
So using React Navigation 5, I built a stack navigator with two screens as follows: 
```lang-tsx
const Stack = createStackNavigator();
const Nav = () => {
  <Stack.Navigator
    <Stack.Screen
        name="A"
        component={A}
    />
    <Stack.Screen
        name="B"
        component={B}
    />
  </Stack.Navigator>
}

```
As the screen __A__ is the first in the navigator, it will be the first to be shown and rendered on screen. Now I want to immediately navigate to __B__ As soon as __A__ has rendered, so I wrote the following code in __A__: 
```lang-js
useEffect(()=>{
    navigation.navigate('B');
}, [navigation]);
```
The problem is that the screen stays stuck in __A__ and doesn't navigate to __B__

##### Possible cause:
I think that when the screen __A__ tried to execute its `useEffect` code, the screen __B__ still hasn't been loaded into the DOM of the navigator. Because when I actually tried to delay the execution of the `useEffect` by 2 seconds like this:  
```lang-js
useEffect(()=>{
    setTimeout(()=>{
        navigation.navigate('B');
    }, 2000)
}, [navigation]);
```

it worked, the screen navigated from __A__ to __B__! So I suppose that __B__ had the time to be loaded into the DOM in less than 2 seconds ?

##### Any solution ?
So, if my assumption is right, I was wondering whether there is a formal way of checking if the screen __B__ has been effectively loaded into the DOM of the navigator, or maybe waiting until the navigator has rendered before executing `useEffect` in __A__. Maybe there's a special react hook or library to check this kind of conditions ?

And if I'm wrong please help me !

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | iOS (10 to 13) and Android (5 to 10)
| @react-navigation/native       | 5.8.10
| @react-navigation/stack        | 5.12.8
| react-native-gesture-handler   | 1.6.0
| react-native-safe-area-context | 0.7.3
| react-native-screens           | 2.2.0
| react-native                   | 0.62
| expo                           | 3.21.3
| node                           | v13.6.0
| npm or yarn                    | npm: 6.14.9

**Comment by sofianear** [comment]
> 
> 
> The versions mentioned in the issue for the following packages differ from the latest versions on npm:
> 
>     * `@react-navigation/native` (found: `5.0.9`, latest: `5.8.10`)
> 
>     * `@react-navigation/stack` (found: `5.1.1`, latest: `5.12.8`)
> 
> 
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?

I have just updated  `@react-navigation/native` to version `5.8.10` and `@react-navigation/stack` to version `5.12.8` and the issue is still there

**Comment by wperez790** [comment]
I resolved it with a listener, check out this example:

`useEffect(() => {
      const unsub = navigation.addListener('focus', () => {
        navigation.push({Route});
      });

      return unsub;
    }, []);`

**Comment by ruida-shen** [comment]
Hi, I think the issue is still there, the only way I can get around it is to wrap the navigate function call in a setTimeout

**Comment by timoisalive** [comment]
Indeed the issue seems to persist. The above mentioned listener seems to work:
```
useEffect(() => {
      const unsub = navigation.addListener('focus', () => {
        navigation.push({Route});
      });

      return unsub;
    }, []);
```
    
But the provided hook doesn't, which seems surprising:
    
```
useFocusEffect(
    useCallback(() => {
      navigation.push({Route});
    }, [])
);

**Comment by slolkunchik** [comment]
issue still exist:

    "@react-navigation/native": "^6.0.2",
    "@react-navigation/stack": "^6.0.7",

**Comment by raajnadar** [comment]
Can someone explain the usecase? You can also navigate directly ton screen B.

Also add a snack repro, so I can check.

**Comment by oliviercperrier** [comment]
Still have this issue here also

**Comment by KushaanKapoor** [comment]
Facing this issue, specifically in Android. I have a home screen which does some API calls to fetch data. if a user navigates to some other screen or opens the drawer during this rendering or mounting, the navigation won't execute until after the screen is rendered. This doesn't seems to be a problem in iOS.

**Comment by ronakonline** [comment]
@KushaanKapoor +1 facing same problem

**Comment by anwersolangi** [comment]
+1 facing the same issue, on Android when I move to screen with params, the screen never mounts, however the params and useEffect in the desired destin screen executes, solution of @wperez790 is working fine, but don't understand what exactly is causing this

**Comment by C3sarRC** [comment]
+1 facing same issue is a bit annoying to deal with it in complex use cases

**Comment by 67millwood** [comment]
+1 still see it on my end.  nav works totally fine unless it's a nested page AND you navigate to it the first time without going through the nav tree (ie. top level, then down to a detail page for example).  expo error asks you like you named the screen wrong...works completely fine only AFTER you nav to that page some other way...then that 'error' never show up again.

**Comment by thianphat** [comment]
> +1 still see it on my end. nav works totally fine unless it's a nested page AND you navigate to it the first time without going through the nav tree (ie. top level, then down to a detail page for example). expo error asks you like you named the screen wrong...works completely fine only AFTER you nav to that page some other way...then that 'error' never show up again.

Facing this same exact issue and makes it hard to deal with routing after a user taps on a push notification if the app is in a killed state.

**Comment by IoTManagerProject** [comment]
I also fase with this issue... Waitng for resolve

**Comment by ABDUL-HASEEB-DAR** [comment]
no solution?

**Comment by devpascoe** [comment]
My issue i had was 3 tabs. If i open, first tab loaded. I tap to open 3rd tab and tap button that navs to a screen defined in tab 2. 
But since tab 2 hasn't been rendered yet it didn't like it.

Setting lazy={false} did the trick and i can get by with the performance hit for now.

const BottomTab = createBottomTabNavigator();

<BottomTab.Navigator
      screenOptions={{
        lazy: false,
      }}
      ...

**Comment by jimmyrheereckon** [comment]
Also having this weird issue..

**Comment by silentsilas** [comment]
When we converted a bare react native project to be managed by Expo, this issue started to occur.

Fine in the bare RN app with the following:

```
   "react-native": "0.70.8",
    "@react-navigation/bottom-tabs": "^6.5.2",
    "@react-navigation/native": "^6.1.1",
    "@react-navigation/native-stack": "^6.9.7",
```

This issue occurs in the Expo-managed project with:

```
    "@react-navigation/bottom-tabs": "^6.6.1",
    "@react-navigation/native": "^6.1.18",
    "@react-navigation/native-stack": "^6.11.0",
    "react-native": "0.74.5",
    "expo": "~51.0.34",
```

Tried reverting the @react-navigation packages to what the bare RN version uses, and still no dice. So it seems to have been introduced in newer React Native / Expo versions?

The hacky timeout workaround mentioned earlier solves it but is certainly not ideal.
