### ISSUE TITLE
SafeAreaView breaks with new react-navigation

### ISSUE THREAD

**Issue by padapada09** [react-navigation/react-navigation#9184]
**Current Behavior**

<img width="317" alt="Screen Shot 2020-12-29 at 10 03 43" src="https://user-images.githubusercontent.com/42701530/103285533-239bed00-49bd-11eb-8ef7-dcf4ef33a011.png">

- What code are you running and what is happening?
- All of my views with SafeAreaView in them, break when i upgrade react-navigation

**Expected Behavior**

The SafeAreaView should include some padding automatically to avoid the notch.

**How to reproduce**

I cant do a Snack because i dont know how to setup a device with a notch. (It uses iphone 8 wich does not have a notch).
That said, you just need to create a new project, create a simple navigation container with a stack navigator and include a screen with a SafeAreaView in it.

**Your Environment**

| software                                     | version |
| ------------------------------ | ------- |
| iOS or Android                           |14.1
| @react-navigation/native         |5.8.10
| react-native                               |0.63.3
| node                                           |14.11.0
| npm.                                           |6.14.8
| react-navigation/stack             |5.12.8
| react-native-screens.              |2.16.1

**Comment by satya164** [comment]
> I cant do a Snack because i dont know how to setup a device with a notch. (It uses iphone 8 wich does not have a notch).

A Snack can be run on any device, not just the default emulator.

**Comment by satya164** [comment]
Closing since you haven't provided a repro to debug the issue. If you manage to make a repro, please open a new issue with it and someone will take a look at it when possible.
