### ISSUE TITLE
In iOS deep linking or  universal linking does not navigate to the screen?

### ISSUE THREAD

**Issue by Tharinducs** [react-navigation/react-navigation#9185]
In Ios deep linking or universal linking does not navigate to the correct screen but in android same code is working fine. This is how I have configured my root navigator.

`import 'react-native-gesture-handler';
import * as React from 'react';
import {NavigationContainer} from '@react-navigation/native';
import {Linking} from 'react-native';
import AppStackNavigator from '_navigations/AppStackNavigator';
import I18n from 'i18n-js';

export default function App() {
  const linking = {
    prefixes: ['https://mydomain/meeting',"myappname://meeting"],
    config: {
      screens: {
        login: 'login/:data',
      },
    },
  };

  return (
    <NavigationContainer linking={linking}>
      <AppStackNavigator />
    </NavigationContainer>
  );
}
`

This is how I have configured my appdelgate.m file for handling the URL.

`@implementation AppDelegate

- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url
  sourceApplication:(NSString *)sourceApplication annotation:(id)annotation
{
  return [RCTLinkingManager application:application openURL:url
                      sourceApplication:sourceApplication annotation:annotation];
}

// Only if your app is using [Universal Links](https://developer.apple.com/library/prerelease/ios/documentation/General/Conceptual/AppSearch/UniversalLinks.html).
- (BOOL)application:(UIApplication *)application continueUserActivity:(NSUserActivity *)userActivity
 restorationHandler:(void (^)(NSArray * _Nullable))restorationHandler
{
 return [RCTLinkingManager application:application
                  continueUserActivity:userActivity
                    restorationHandler:restorationHandler];
}`

In Ios, it is opening the app when I click on the link but does not navigate to the correct location but works correctly on android.

- "@react-navigation/native": "5.2.1",
- "react-native": "0.62.2",
- "react": "16.11.0",
- "IOS": "14.2"
- XCode: 12

**Comment by KestasVenslauskas** [comment]
Got a report that linking stoped working on iOS also.

**Comment by daba-faith** [comment]
I am facing the same issue, has this been addressed?

**Comment by mercpls** [comment]
Is your well known file setup, and validated?

**Comment by RatFou** [comment]
Have the same issue and my associated domain file is OK

**Comment by MaxAst** [comment]
Same here. I have my AASA file deployed to my nextjs site under `/.well-known/apple-app-site-association` and validated it with `https://branch.io/resources/aasa-validator`. When I press a link to www.my-site.com, it opens the app, but `react-navigation` doesn't open the screen specified in the linking config. However, it does work if open a link using the custom scheme
