### ISSUE TITLE
Header and Bottom Tab Jump out

### ISSUE THREAD

**Issue by hungdev** [react-navigation/react-navigation#9186]
**Current Behavior**
Header and Bottom Tab Jump out. Please look at my gif

![ezgif com-gif-maker](https://user-images.githubusercontent.com/12009276/103337282-5f15e480-4aad-11eb-8627-5cebe4a0437b.gif)

**How to reproduce**
Reload the app, it will appear.

I tried with the code of docs, it also got the bug like my gif:
[https://reactnavigation.org/docs/tab-based-navigation/#a-stack-navigator-for-each-tab](https://snack.expo.io/?platform=android&name=Tab%20navigation%20%7C%20React%20Navigation&dependencies=%40expo%2Fvector-icons%40*%2C%40react-native-community%2Fmasked-view%40*%2C%40react-navigation%2Fbottom-tabs%40%5E5.8.0%2C%40react-navigation%2Fdrawer%40%5E5.9.0%2C%40react-navigation%2Fmaterial-bottom-tabs%40%5E5.2.16%2C%40react-navigation%2Fmaterial-top-tabs%40%5E5.2.16%2C%40react-navigation%2Fnative%40%5E5.7.3%2C%40react-navigation%2Fstack%40%5E5.9.0%2Creact-native-paper%40%5E4.0.1%2Creact-native-reanimated%40*%2Creact-native-safe-area-context%40*%2Creact-native-gesture-handler%40*%2Creact-native-screens%40*%2Creact-native-tab-view%40%5E2.15.1&sourceUrl=https%3A%2F%2Freactnavigation.org%2Fexamples%2F5.x%2Ftab-based-navigation-stack.js)

**My Environment**
"@react-native-async-storage/async-storage": "^1.13.2",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-navigation/bottom-tabs": "^5.11.2",
    "@react-navigation/native": "^5.8.10",
    "@react-navigation/stack": "^5.12.8",
     "react": "16.13.1",
    "react-native": "0.63.4",

**Comment by suhail135** [comment]
Add SafeAreaProvider in your app root component and use SafeAreaView as the root component of your page. Also check the import statement of SafeAreaView **import { SafeAreaProvider, SafeAreaView } from 'react-native-safe-area-context'**

**Comment by outaTiME** [comment]
Same here, solved wrapping my root component in the following way:

```js
import { SafeAreaProvider } from 'react-native-safe-area-context';

export default () => (
  <SafeAreaProvider>
    <App />
  </SafeAreaProvider>
);
```

hope it helps 🙏

**Comment by hungdev** [comment]
@suhail135  @outaTiME  thank guys. It worked. <3

**Comment by hodangnamtien** [comment]
Cái của mình sau khi thêm  <SafeAreaProvider> thấy nó nhảy lên nhảy xuống bựa lắm

**Comment by hungdev** [comment]
@hodangnamtien maybe you put it in wrong place.
