### ISSUE TITLE
Only show Tab Bar when using @react-navigation/bottom-tabs with react-native-web

### ISSUE THREAD

**Issue by dinhquan** [react-navigation/react-navigation#9187]
**Current Behavior**

The screen content doesn't appear on the web, it only shows the Tab Bar. It works fine on iOS and Android.

```
import {createBottomTabNavigator} from '@react-navigation/bottom-tabs';
import {NavigationContainer} from '@react-navigation/native';
import React from 'react';
import {Text, View} from 'react-native';

const HomeScreen = () => {
  return (
    <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
      <Text>This is the home screen</Text>
    </View>
  );
};

const RootView = () => {
  const Tab = createBottomTabNavigator();
  return (
    <NavigationContainer>
      <Tab.Navigator>
        <Tab.Screen name="Home" component={HomeScreen} />
      </Tab.Navigator>
    </NavigationContainer>
  );
};

export default React.memo(RootView);

```
On web:

<img width="821" alt="Screen Shot 2020-12-31 at 10 33 56 AM" src="https://user-images.githubusercontent.com/1617852/103393158-ecac0f80-4b53-11eb-96ac-bf586106aae1.png">

On iOS:

<img width="377" alt="Screen Shot 2020-12-31 at 10 43 16 AM" src="https://user-images.githubusercontent.com/1617852/103393266-66dc9400-4b54-11eb-952f-531b6cdf1b58.png">

There's the same issue on stackoverflow but no answer yet:
https://stackoverflow.com/questions/64264743/react-navigation-bottom-tabs-occupying-the-whole-screen-in-react-native-web

**Your Environment**

| software                      | version |
| ----------------------------- | ------- |
| iOS or Android                |
| @react-navigation/native      |^5.8.10
| @react-navigation/bottom-tabs |^5.11.2"
| react-native-screens          |^2.16.1
| react-native                  |0.63.3
| react-native-web|^0.14.10

**Comment by ZeroJian** [comment]
same problem, but only happens iOS 10 safari

**Comment by hamedmam** [comment]
I have the same problem in iOS 10 chrome, it seems like a styling issue since I was able to change some styling and see the content appearing, something to do with Flexbox implementation

**Comment by hamedmam** [comment]
update: as soon as I remove the bottom-tabs it works fine

**Comment by dinhquan** [comment]
I finally can resolve this issue by setting these styles in public/index.html
```html
    <style>
      /* These styles make the body full-height */
      html,
      body {
        height: 100%;
      }
      /* These styles disable body scrolling if you are using <ScrollView> */
      body {
        overflow: hidden;
      }
      /* These styles make the root element full-height */
      #root {
        display: flex;
        height: 100%;
      }
    </style>
```

**Comment by hamedmam** [comment]
@dinhquan unfortunately this won't fix it for me, it seems like I need to remove min-height: 0px; on bottom-tab for contents to appear

**Comment by ZeroJian** [comment]
> @dinhquan unfortunately this won't fix it for me, it seems like I need to remove min-height: 0px; on bottom-tab for contents to appear

yes, it is not work fo me

**Comment by ZeroJian** [comment]
my project useed expo default index.html  https://github.com/expo/expo-cli/blob/master/packages/webpack-config/web-default/index.html

I have the same problem in iOS 10 safari

**Comment by ZeroJian** [comment]
i find problem in iOS 10 safari, when body height equal clientHeight, only show Tab Bar, but if i set other height, the height is available 
example:
```javascript

// index.web.js

is work
const bodyHeight = document.body.clientHeight
document.body.style.height = bodyHeight + 1 + 'px'

is not work
const bodyHeight = document.body.clientHeight
document.body.style.height = bodyHeight + 'px'

```

**Comment by amhouel** [comment]
On web in Chrome my screen is completely blank, I don't even see the bottom tab bar. When I remove the bottom-tabs my screen content is back.
The bottom-tabs works fine on iOS and Android.

**Comment by hamedmam** [comment]
@dinhquan can we open this again please ? there seems to be more people are seeing this as they upgrade their browser

**Comment by jason-cf** [comment]
Happening for me as well, web=Chrome/Safari, mobile=ios14. If I remove the bottomTab, the page loads fine.

I tested using the simplest page as well: render(){return(<View><Text>Hello World</Text></View)}

Hardcoding height & width <View style={{backgroundColor: 'red', height:500, width:500}}> does not work. 

dinhquan's <style> solution did not work either.

**Comment by SilvioLuis** [comment]
Any updates? Same here...

**Comment by timbastin** [comment]
I have the same issue.It's a styling issue but the posted styles right here did not fix it for me :-( happens in all browsers that I tested. I do not have access to safari though.

Is there any help?

**Comment by usamaehsan** [comment]
i have the same issue .

**Comment by xhirazi** [comment]
+1

**Comment by UIT19521334** [comment]
Any solution here. i added html, body, app-root , etc.. but mot working

**Comment by UIT19521334** [comment]
Hi, I finally resolved this issue. Just create a View with **height** set to **fullHeight** and **display** set to **flex**, then wrap it in the navigation container like this:

``` javascript
export default function WebNavigator() {
	const { height } = useWindowDimensions()
	return (
		<View style={{ height: height, display: 'flex' }}>
			<NavigationContainer ref={navigationRef}>
				<Tab.Navigator>
					<Tab.Screen name="Home" component={DiscoverScreen} />
				</Tab.Navigator>
			</NavigationContainer>
		</View>
	)
}
```

**Comment by Priyanshu2117** [comment]
I tried all the suggestions given above, but still not able to resolve it.
