### ISSUE TITLE
React Navigation Drawer

### ISSUE THREAD

**Issue by rayyan224** [react-navigation/react-navigation#9188]
**Current Behavior**

I want to create a simple react navigation drawer. On import it gives me the error 
ReferenceError: Can't find variable: _globalSetter

**How to reproduce**

- You must provide a way to reproduce the problem. If you are having an issue with your machine or build tools, the issue belongs on another repository as that is outside of the scope of React Navigation.
- Either re-create the bug on [Snack](https://snack.expo.io) or link to a GitHub repository with code that reproduces the bug.
- Explain how to run the example app and any steps that we need to take to reproduce the issue from the example app.
- Keep the repro code as simple as possible, with the minimum amount of code required to repro the issue.
- Before reporting an issue, make sure you are on latest version of the package.

Environment

"@expo/vector-icons": "^12.0.1",
    "@react-native-community/datetimepicker": "^3.0.8",
    "@react-native-community/masked-view": "0.1.10",
    "@react-navigation/bottom-tabs": "^5.11.2",
    "@react-navigation/drawer": "^5.11.4",
    "@react-navigation/native": "^5.8.10",
    "@react-navigation/stack": "^5.12.8",

This is how I am importing:
import { createDrawerNavigator } from "@react-navigation/drawer";

![image](https://user-images.githubusercontent.com/62478924/103425275-4c6be000-4b7f-11eb-86f2-4b51e999728b.png)

**Comment by satya164** [comment]
Closing since you haven't provided a repro to debug the issue. If you manage to make a repro, please open a new issue with it and someone will take a look at it when possible.
