### ISSUE TITLE
Add initial: true/false to documentation

### ISSUE THREAD

**Issue by Aryk** [react-navigation/react-navigation#9189]
I was scouring the React Navigation 5.x navigation for over an hour, google searching, etc....I could not find any documentation for the initial: false/true param (I found out about it through stackoverflow).

Since it relates to navigating between screens, perhaps the obvious place for it would be:

https://reactnavigation.org/docs/navigating

Any chance we can get it added? If it is in the documentation then it is incredibly hard to find.

**Comment by satya164** [comment]
https://reactnavigation.org/docs/nesting-navigators#passing-params-to-a-screen-in-a-nested-navigator

**Comment by AndreiBehel** [comment]
This feature is broken in React Navigation v6
