### ISSUE TITLE
Cannot run Expo Typescript boilerplate

### ISSUE THREAD

**Issue by madhavgharmalkar** [react-navigation/react-navigation#9194]
**Current Behavior**

I'm creating an expo project with a react navigation preset (with typescript), and I'm expecting this application to compile correctly and work in the iOS simulator.
 
```
Failed building JavaScript bundle.
SyntaxError: /Users/madhav/dev/kuli/node_modules/@react-navigation/native/src/NavigationContainer.tsx: Unexpected token (14:12)

  12 | import useDocumentTitle from './useDocumentTitle';
  13 | import useBackButton from './useBackButton';
> 14 | import type { Theme, LinkingOptions, DocumentTitleOptions } from './types';
     |             ^
  15 | 
  16 | type Props = NavigationContainerProps & {
  17 |   theme?: Theme;
```
**Expected Behavior**

I should expect the React Native / Expo / React Navigation starter project to work and build correctly.

**How to reproduce**
1. Run `npx expo init demo-issue-stack`
2. Select ` tabs (TypeScript)     several example screens and tabs using react-navigation and TypeScript`
3. Follow the instructions to run the demo app on an iOS simulator.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | iOS (simulator)
| @react-navigation/native       | 5.8.9
| @react-navigation/stack        | 5.12.6
| react-native-gesture-handler   |
| react-native-safe-area-context |
| react-native-screens           |
| react-native                   | https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz
| expo                           | 40.0.0
| node                           |
| npm or yarn                    |

**Comment by madhavgharmalkar** [comment]
^ I've tried using the latest versions of these packages and I am still experiencing the same issue

**Comment by cmaycumber** [comment]
I'm running into the same issue. 

I was able to replicate the same issue on an Expo Typescript boilerplate as well.

**Comment by JasonYaoSiXu** [comment]
I'm running into the same issue. I tried using JitsiMeet + ReactNavigation
![Screen Shot 2021-02-20 at 9 44 05 AM](https://user-images.githubusercontent.com/11410731/108579107-5da3c280-7360-11eb-996b-c54b3cb5f221.png)

**Comment by JasonYaoSiXu** [comment]
Look this,[https://reactnavigation.org/docs/troubleshooting/#im-getting-syntaxerror-in-react-navigationxxxxxxtsx-or-syntaxerror-xxxreact-navigationxxxxxxtsx-unexpected-token](url). It work for me. I hope this can help you.

**Comment by bntzio** [comment]
I'm getting this error as well, Expo boilerplates isn't working.

**Comment by satya164** [comment]
I just created a new project with `expo` and have no issues. Can you confirm if you still have a problem?
