### ISSUE TITLE
CommonActions.reset() is not working correctly.

### ISSUE THREAD

**Issue by ercanozer** [react-navigation/react-navigation#9204]
**Current Behavior**

- I have a nested navigation which is stack navigator includes bottom tab navigation and I have an detail screen in stack navigation. When I go detail screen from home screen which is in bottom tab by pushing, every time creating new instance of detail screen and It is true. I am using push method because I need to send new params everytime. If I use navigate method, It will not send new params. So, when I come back to detail screen, I am resetting the navigation by removing detail screens and It is happening then I checked navigation state object everytime with in console.log, I saw that detail screens was removed, but when I try to come back to home screen from detail screens, If there are two or more detail screens , the navigation will go to those screens although not seeing in navigation state object.

**Expected Behavior**

**How to reproduce**

Because of those problems, I keep my params data in a class as static and when I navigate to detail screen, I change the static data then I am using static data in detail screen. I know, it is not good idea, but This is my best solution in this situation.

**Your Environment**
Android OS 10
| software React Native | version | 0.63.3
| ------------------------------ | ------- |
| Android |
| @react-navigation/native 5.8.10 |
| @react-navigation/stack 5.12.8 |
| @react-navigation/botom-tabs 5.11.2 |

| react-native 0.63.3 |
| node v10.16.0 |
| yarn |

**Comment by josecanizares** [comment]
Route params still get updated when reusing a screen so your reasoning to use 'push' instead of 'navigate' is faulty. It's to your benefit to use navigate so you aren't overwhelming your route history. Try using a focus listener to read in new changes to route params.
