### ISSUE TITLE
initialRouteName is not working on the stack navigator while linking is used

### ISSUE THREAD

**Issue by santhoshvai** [react-navigation/react-navigation#9206]
**Current Behavior**

The `initialRouteName` configured in `Stack.Navigator` is ignored when linking is used.

**Expected Behavior**

The `initialRouteName` configured in `Stack.Navigator` must not be ignored when linking is used.

**How to reproduce**

Repo - https://github.com/santhoshvai/react-navigation-linking-bug-example

- Run in terminal - `npm i && npm run ios`
- Force close the app in ios simulator 
- Run in terminal - `xcrun simctl openurl booted myapp://details`
	- This opens the details screen. But home screen is not on the stack even though it is configured as the initial route.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | ios 14.3 | 
| @react-navigation/native       | 5.8.10 |
| @react-navigation/stack        | 5.12.8 |
| react-native-gesture-handler   | ^1.9.0 |
| react-native-safe-area-context | ^1.13.2 |
| react-native-screens           | ^2.16.1 |
| react-native                   | 0.63.4 |
| expo                           |  - |
| node                           | 14.15.0 |
| npm or yarn                    | npm v6.14.8 |

**Comment by santhoshvai** [comment]
> The versions mentioned in the issue for the following packages differ from the latest versions on npm:
> 
> * `@react-navigation/native` (found: `5.7.3`, latest: `5.8.10`)
> * `@react-navigation/stack` (found: `5.9.0`, latest: `5.12.8`)
> 
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?

Yes they do

**Comment by satya164** [comment]
https://reactnavigation.org/docs/configuring-links/#rendering-an-initial-route

**Comment by santhoshvai** [comment]
@satya164 do you mean that I should always use the `initialRouteName` in the `LinkingOptions`, even though I configure `initialRouteName` in the `Stack.Navigator` and this is expected behaviour?.

According to the docs, the `initialRouteName` in  `Stack.Navigator` makes sure that the is rendered on first load of the navigator. The `initialRouteName` in the `LinkingOptions` makes sure that the route is always present first. 

We need the scenario where if the navigator is already present, the `initialRouteName` must be ignored but if the navigator is initially loaded then `initialRouteName` is the first route. So we expected that `initialRouteName` in the `Stack.Navigator` will provide this scenario.

**Comment by saeid-elio** [comment]
Why is this issue closed?!
