### ISSUE TITLE
TouchableOpacity doesn't work in navigation.navigate problem

### ISSUE THREAD

**Issue by 2006Ted** [react-navigation/react-navigation#9211]
**Current Behavior**

`import React from 'react'
import {
    View,
    Text,
    StyleSheet,
    TouchableOpacity,
    Platform,
} from 'react-native'
import { Ionicons } from '@expo/vector-icons'
import { useNavigation } from '@react-navigation/native';
import { createStackNavigator } from '@react-navigation/stack';
import ViewDiaryScreen from '../screens/ViewDiaryScreen'

const Stack = createStackNavigator();
    
    
const ArticleItem = ({
    article: {
        id,
        title,
        content,
        date,
    }
}) => {
    const navigation = useNavigation();
         return (
             <TouchableOpacity
             activeOpacity={0.8}
             onPress={() => navigation.navigate('ViewStackScreen')}
             >
        <View style={styles.container}>
             <View style={styles.icon}>
             <Ionicons name="md-list" size={14} color="#9E9E9E"/>
         </View>
        <View style={styles.info}>
            <Text style={styles.title}>
            {title}
            </Text>
            <Text style={styles.content}>
            {content}
            </Text>
             <Text style={styles.date}>
                {date}
             </Text>
        </View>
    </View> 
         
    </TouchableOpacity>
    
    );   
    }

    

const styles = StyleSheet.create({
    container: {
    flexDirection: 'row',
    padding: 16,
    paddingBottom: 0,
    },
    icon: {
      width: 16,
      height: 16,
      marginRight: 8,
      justifyContent: 'center',
      alignItems: 'center',
      paddingTop: Platform.select({
          ios: 3, android: 8,
      })
    },
    title: {
        marginBottom: 8,
        fontSize: 16,
        fontWeight: '800',
        color: '#212121',
    },
    content: {
        marginBottom: 4,
        fontSize: 14,
        color: '#9E9E9E',
        lineHeight: 18,
    },
    date: {
         fontSize: 12,
         color: '#BDBDBD',
    },
    info: {
        flex: 1,
       paddingBottom: 16,
       borderBottomWidth: 1,
       borderBottomColor: '#DEDEDE',
    },
})

export default ArticleItem
`
ArticleItem.js

`
import React from 'react' 
import {
    View,
    Text,
} from 'react-native'
import { createStackNavigator } from '@react-navigation/stack';
import ViewDiaryScreen from './ViewDiaryScreen'

const Stack = createStackNavigator();

 const ViewStackScreen = () => {
     return (
        <Stack.Navigator>
        <Stack.Screen name="ViewStack" component={ViewDiaryScreen}/>
    </Stack.Navigator>
    ) 
 }

    export default ViewStackScreen
`
ViewStackScreen.js

`
import React from 'react'
import {
    Text,
    StyleSheet,
    SafeAreaView, 
} from 'react-native'

const ViewDiaryScreen = () => {
    return (
        <SafeAreaView style={styles.container}>
            <Text>
                Screen
            </Text>
        </SafeAreaView>
    )   
}
    

const styles = StyleSheet.create({
    container: {
        flex: 1,
    }
})

export default ViewDiaryScreen
`
ViewDiaryScreen.js

`
import React from 'react'
import {
    View,
    Text,

} from 'react-native'
import { Ionicons } from '@expo/vector-icons'
import Header from '../components/Header'
import ArticleItem from '../components/ArticleItem'

const DiaryScreen = () => {
    return (
<View style={{ flex: 1}}>
    <Header title="new Diary" />

    
    
<ArticleItem
    article={{
        id: 1,
        title: 'Test1',
        content: 'contentTest1',
        date: '2021/1/2',
    }}
/>
<ArticleItem
    article={{
        id: 1,
        title: 'Test2',
        content: 'contentTest2',
        date: '2021/1/2',
    }}
/>
</View>
    );
}

export default DiaryScreen`

DiaryScreen.js

`
import 'react-native-gesture-handler';
import { StatusBar } from 'expo-status-bar';
import React from 'react';
import { StyleSheet, TabBarIOS, Text, View } from 'react-native';
import { createBottomTabNavigator } from '@react-navigation/bottom-tabs';
import { NavigationContainer } from '@react-navigation/native';
import { createStackNavigator } from '@react-navigation/stack';
import { Ionicons } from '@expo/vector-icons'

import DiaryScreen from './screens/DiaryScreen'
import HomeScreen from './screens/HomeScreen'
import MakeStackScreen from './screens/MakeStackScreen'

const Tab = createBottomTabNavigator();

export default function App() {
  return (
   <NavigationContainer>
      <Tab.Navigator
        screenOptions={({ route }) => ({
          tabBarIcon: ({ focused, color, size }) => {
            let iconName;

            if (route.name === 'Diary') {
              iconName = focused
                ? 'book'
                : 'book-outline';
            } else if (route.name === 'Add') {
              iconName = focused ? 'add' : 'add-outline';
              size = 32;
            } else if (route.name === 'Home') {
              iconName = focused ? 'home' : 'home-outline';
            }
            return <Ionicons name={iconName} size={size} color={color} />;
          },
        })}
        tabBarOptions={{
          activeTintColor: '#3D50FA',
          inactiveTintColor: 'gray',
          showLabel: false,
        }}
      >
        <Tab.Screen name="Diary" component={DiaryScreen} />
        <Tab.Screen name="Add" component={MakeStackScreen} 
        options={{ 
          tabBarVisible: false
         }}
        />
        <Tab.Screen name="Home" component={HomeScreen} />
      </Tab.Navigator>
   </NavigationContainer>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
`
App.js

And The error happens when I click ArticleItem: 
`The action 'NAVIGATE' with payload 
{"name":"ViewStackScreen"} was not handled by any navigator.
` 

**Expected Behavior**

I expect Move DiaryScreen to ViewDiaryScreen when I click ArticleItem.

**How to reproduce**

You just copy and paste and delete useless proportion.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
|Android OS 8|
| @react-navigation/native:v5.8.10 |
| react-native: 0.63.2 |
| expo: 3.27.13  |

| npm |

**Comment by quicksilverr** [comment]
Hey, any solutions ?
