### ISSUE TITLE
NavigationContainer reset the ref each render

### ISSUE THREAD

**Issue by yairopro** [react-navigation/react-navigation#9213]
**Current Behavior**

The NavigationContainer.ref gives a different instance each time the parent render even though the ref function is the same each render (I prefer function rather than ref objects).

**Expected Behavior**

- What do you expect should be happening?
- Include a screenshot or video if it makes sense.

**How to reproduce**

Here's a snack about the problem:
https://snack.expo.io/@yairopro/react-navigation:-bug---navigationcontainer-ref-reset-every-time

In the snack i use a state setter. The setter is always the same function instance so the `ref` prop should not trigger it a second time.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| @react-navigation/native       | 5.8.10
| react-native                   | *

**Comment by satya164** [comment]
Closing since this is no longer the case in React Navigation 6.

**Comment by yairopro** [comment]
🎉
