### ISSUE TITLE
Do 'keyboardHidesTabBar: true' works on mobile web?

### ISSUE THREAD

**Issue by temuccio** [react-navigation/react-navigation#9220]
**Current Behavior**
I have make a simple bottom tab navigation with expo frameworks.
This is the code 
```
const TabBot = createMaterialBottomTabNavigator();
...
return(
    <TabBot.Navigator 
      initialRouteName="np"
      tabBarOptions={{
        keyboardHidesTabBar: true
      }}
      barStyle={TabBotOpt}>
...
```

**Expected Behavior**

When on mobile website the keyboard is open, I'm like the bottom tab bar navigation is hide.
![immagine](https://user-images.githubusercontent.com/571582/104282611-9aea7a00-54af-11eb-9d02-d7b0c734984a.png)

**Your Environment**

| software                               | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 5.8.10
| @react-navigation/material-bottom-tabs | 5.3.10
| react-native-paper                     | 4.6.0
| react-native                           |0.63.4
| expo                                   | 40.0.0
| node                                   | 10.21.0
| npm or yarn                            | 6.14.11

**Comment by satya164** [comment]
It doesn't since there's no API to detect Keyboard on mobile web.
