### ISSUE TITLE
How to fix the issue of view while showing Material Top Tab Navigator in fix height & width view(Android)

### ISSUE THREAD

**Issue by sumitbalyan** [react-navigation/react-navigation#9224]
**Current Behavior**

- What code are you running and what is happening?
- Include a screenshot or video if it makes sense.

**Expected Behavior**

- Working fine in iOS

**How to reproduce**

import * as React from 'react';
import {View, StyleSheet, Dimensions, TouchableOpacity} from 'react-native';
import GetClaim from './GetClaim';
import MyView from './MyView';
import {createMaterialTopTabNavigator} from '@react-navigation/material-top-tabs';
import {NavigationContainer} from '@react-navigation/native';
import EntypoIcon from 'react-native-vector-icons/Entypo';
import {SafeAreaProvider} from 'react-native-safe-area-context';

const Tab = createMaterialTopTabNavigator();
const initialLayout = {
  width: Dimensions.get('window').width,
  height: Dimensions.get('window').height,
};
export default function TabViewExample() {
  const screen = {heightLogin: 308, heightClaim: 550};
  const indicatorLogin = {width: 50, left: '18%', backgroundColor: '#0B3F35'};
  const indicatorClaim = {width: 130, left: '6%', backgroundColor: '#0B3F35'};
  const [state, setstate] = React.useState({
    index: 0,
    screen: 'Login',
    size: screen.heightLogin,
    indicatorStyle: indicatorLogin,
    fabColor: '#FD9D60',
  });

  const onTabPress = (e) => {
    const name = e.target;
    console.log(name, name.includes('Signup'));
    if (name.includes('Signup')) {
      setstate({
        index: 1,
        size: screen.heightClaim,
        screen: 'Claim',
        indicatorStyle: indicatorClaim,
      });
    } else {
      setstate({
        index: 0,
        size: screen.heightLogin,
        screen: 'Login',
        indicatorStyle: indicatorLogin,
      });
    }
  };
  return (
    <SafeAreaProvider style={styles.scene}>
      <>
        <View style={[styles.childContainer, {height: state.size}]}>
          <NavigationContainer>
            <Tab.Navigator
              sceneContainerStyle={{}}
              tabBarOptions={{
                style: {elevation: 0, shadowOpacity: 0},
                indicatorStyle: state.indicatorStyle,
                labelStyle: {textTransform: 'none', fontSize: 18},
                activeTintColor: '#FD9D60',
                inactiveTintColor: '#0B3F35',
              }}>
              <Tab.Screen
                name="Login"
                listeners={{tabPress: onTabPress, focus: onTabPress}}>
                {(props) => (
                  <MyView
                    {...props}
                    handleChange={() => {}}
                    handleBlur={() => {}}
                    errors={() => {}}
                    values={''}
                    touched={{}}
                    setTouched={() => {}}
                  />
                )}
              </Tab.Screen>
              <Tab.Screen
                name="Signup"
                listeners={{tabPress: onTabPress, focus: onTabPress}}>
                {(props) => (
                  <GetClaim
                    {...props}
                    handleChange={() => {}}
                    handleBlur={() => {}}
                    errors={() => {}}
                    values={''}
                    touched={{}}
                    setTouched={() => {}}
                  />
                )}
              </Tab.Screen>
            </Tab.Navigator>
          </NavigationContainer>
        </View>
        <View style={{alignItems: 'center'}}>
          <TouchableOpacity style={styles.fabView} onPress={() => {}}>
            <View
              style={[
                styles.fab,
                {
                  height: 54,
                  width: 54,
                  borderRadius: 27,
                  padding: 10,
                  alignItems: 'center',
                  justifyContent: 'center',
                },
              ]}>
              <EntypoIcon name="arrow-right" size={25} color={'#FD9D60'} />
            </View>
          </TouchableOpacity>
        </View>
      </>
    </SafeAreaProvider>
  );
}

const styles = StyleSheet.create({
  scene: {
    flex: 1,
    marginTop: 60,
    paddingBottom: 40,
  },
  fabView: {
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
    //left: 180,
    bottom: -30,
    height: 72,
    width: 72,
    borderRadius: 36,
    backgroundColor: '#fff',
    elevation: 10,
    shadowOffset: {width: 1, height: 1},
    shadowColor: 'black',
    shadowOpacity: 0.3,
  },
  fab: {
    backgroundColor: '#0B3F35',
  },
  childContainer: {
    backgroundColor: '#fff',
    padding: 20,
    borderRadius: 10,
    marginHorizontal: 20,
  },
  image: {
    flex: 1,
    resizeMode: 'cover',
  },
  textView: {
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
    bottom: 40,
    right: 150,
  },
  text: {
    color: '#8A9EAD',
    fontSize: 12,
    fontFamily: 'Roboto-Regular',
  },
});

**Your Environment**
<img width="404" alt="Login" src="https://user-images.githubusercontent.com/14543001/104691605-8bc43000-572c-11eb-93a8-b0f3a42c6f7c.png">
<img width="404" alt="Signup" src="https://user-images.githubusercontent.com/14543001/104691610-8d8df380-572c-11eb-8777-4336ea6a5041.png">

| software                            | version |
| ----------------------------------- | ------- |
| Android                      | 29
| @react-navigation/native            | "^5.8.10"
| @react-navigation/material-top-tabs | "^5.3.10"
| react-native-tab-view               | "^2.15.2"
| react-native                        | "0.63.4"
| npm or yarn                         |

**Comment by sumitbalyan** [comment]
Issue not fixed after update the packages

@react-navigation/native (found: 5.8.10, latest: 5.9.0)
@react-navigation/material-top-tabs (found: 5.3.10, latest: 5.3.11)

please provide solution asap.

**Comment by sumitbalyan** [comment]
> The versions mentioned in the issue for the following packages differ from the latest versions on npm:
> 
> * `@react-navigation/native` (found: `5.8.10`, latest: `5.9.0`)
> * `@react-navigation/material-top-tabs` (found: `5.3.10`, latest: `5.3.11`)
> 
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?

Issue not fixed after update the packages

@react-navigation/native (found: 5.8.10, latest: 5.9.0)
@react-navigation/material-top-tabs (found: 5.3.10, latest: 5.3.11)

please provide solution asap.

**Comment by sumitbalyan** [comment]
just resolve the issue...sceneContainerStyle{{}}

**Comment by Gakki-coco** [comment]
Same issue too. So how do you fixed it ? dude

**Comment by uzielmperez** [comment]
Adding `overflow: "hidden"` to the style of the containing view worked for me.

```
<View style={{ overflow: "hidden" }}>
     <Navigator>
          (...screens)
     </Navigator>
<View/>
```
