### ISSUE TITLE
Drawer 5.11.5 doesn't render screens that are navigators (web)

### ISSUE THREAD

**Issue by jpaas** [react-navigation/react-navigation#9225]
**Current Behavior**

I have a react-native-web app that uses the drawer view. Many of the screens are navigators.
The latest version of `@react-navigation/drawer` (5.11.5) does not render any of these screens. It does, but they all appear to have 0 height/width.

**Expected Behavior**

The drawer screens should all render.

**How to reproduce**

- navigation container contains a `Drawer.Navigator` which has a screen that is a stack navigator.
- using `@react-navigation/drawer` 5.11.4 this works
- upgrade to 5.11.5 and it no longer renders

https://snack.expo.io/@dragonballsy/navdrawer

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | web
| @react-navigation/native       | 5.9.0
| @react-navigation/drawer       | 5.11.5
| react-native-reanimated        | 1.13.2
| react-native-gesture-handler   | 1.9.0
| react-native-safe-area-context | 0.7.3
| react-native-screens           | 2.16.1
| react-native                   | 0.63.4
| expo                           | n/a
| node                           |
| npm or yarn                    |

**Comment by jpaas** [comment]
I tried upgrading to `@react-navigation/native` `5.9.0` but this gives me a completely different error. One of my components uses `useNavigation` and this fails with `Couldn't find a navigation object. Is your component inside a screen in a navigator?`

So until I figure that error out, I can't validate.

**Comment by dario30186** [comment]
I have the same problem after upgrading from 5.9.2 
With inspect I can see that all the screens in the drawer haven't any height set, but before yes. 
If I force the heigth with chrome inspectin my screen container then I can see my screen

**Comment by jpaas** [comment]
Here's my minimal repro. It shows rendering the same screen, as a bare screen, and then inside a stack navigator. When you navigate to the stack, it all collapses.

https://snack.expo.io/@dragonballsy/navdrawer

**Comment by brentvatne** [comment]
similar issue in https://github.com/expo/expo/issues/11644 - worked around it by rolling back to `@react-navigation/bottom-tabs@5.11.2`

**Comment by jpaas** [comment]
I've upgraded to `@react-navigation/native` `5.9.0` but the problem remains. Repro updated to match.

**Comment by jpaas** [comment]
> similar issue in [expo/expo#11644](https://github.com/expo/expo/issues/11644) - worked around it by rolling back to `@react-navigation/bottom-tabs@5.11.2`

@brentvatne I tried rolling back bottom-tabs, but it didn't help. My repro doesn't even use or import that package.
