### ISSUE TITLE
Web - Drawer Navigator drawerPosition="right": drawer visible on scrolling

### ISSUE THREAD

**Issue by amhouel** [react-navigation/react-navigation#9234]
**Current Behavior**
On web when setting the drawerPosition prop to "right" a horizontal scrollbar appears on the screen and the drawer is visible when scrolling to the right.

**Expected Behavior**
Same behavior as the default/left drawer.
There should be no horizontal scrollbar and the drawer should not be visible until clicking the button to open it or toggle it.

**How to reproduce**
snack: https://snack.expo.io/@reachvote/drawer-navigation---drawerposition-right-%7C-react-navigation
You can reproduce by scrolling the view to the right.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
Web
| @react-navigation/native       | ^5.9.0
| @react-navigation/drawer       | ^5.11.5
| react-native-reanimated        | ~1.13.0
| react-native-gesture-handler   | ~1.8.0
| react-native-safe-area-context | 3.1.9
| react-native-screens           | ~2.15.0
| react-native                   | ~0.63.4
| expo                           | SDK 40
| node                           | v14.5.0
| npm or yarn                    | 1.22.4

**Comment by amhouel** [comment]
this issue still exist in the latest version of `@react-navigation/native (5.9.0)`

**Comment by buffaloDeveloper** [comment]
Seeing the same issue on both:
"@react-navigation/native": "5.8.0",
"@react-navigation/native": "5.9.0",

**Comment by buffaloDeveloper** [comment]
Anyone find a fix for this issue?  I really don't want to position the drawer on the left side...

**Comment by scottrules44** [comment]
Any updates on this?

**Comment by raajnadar** [comment]
Duplicate of #8415
