### ISSUE TITLE
React Navigation 5 add loader above bottom tab bar

### ISSUE THREAD

**Issue by kickbk** [react-navigation/react-navigation#9236]
**Current Behavior**

I am trying to add a component right above the bottom tab navigator. For the sake of demonstration, let's make that component a simple View with some styling.
From the docs, it looks like I need to pass `tabBar` with the actual tabs component as such:

```
<BottomTab.Navigator
    initialRouteName="Search"
    tabBar={(props) => <MyTabBar {...props} />}
  >
    <BottomTab.Screen
      ...
    />
    ...
```

However, I do not want to recreate the tabs from scratch. I just want to add a simple loader above it in this style:
```
function MyTabBar() {
  return (
    <View>
      <View style={{flex: 1, height: 2 backgroundColor: 'red'}} />
      {...TheRestOfTheDefaultNavigator}
    </View>
  )
}
```

How do I do that?

**Your Environment**

Expo SDK40
"@react-navigation/native": "^5.8.9",
"@react-navigation/bottom-tabs": "^5.11.1",

**Comment by kickbk** [comment]
Yes, it's unrelated to the version

**Comment by kickbk** [comment]
Ended up achieving this by creating a wrapper provider around each screen and placing the loader at the bottom inside of the wrapper.

**Comment by ithustle** [comment]
@kickbk , can you could share your code?

**Comment by renchap** [comment]
@ithustle You can use your own component wrapping the original one:

```ts
import type { BottomTabBarProps } from "@react-navigation/bottom-tabs"
import { BottomTabBar } from "@react-navigation/bottom-tabs"

const CustomBottomTabBar: React.FunctionComponent<BottomTabBarProps> = (
  props,
) => (
  <>
    <Text>Foo</Text>
    <BottomTabBar {...props} />
  </>
)

// and then in your navigator
<MyNavigator.Navigator tabBar={CustomBottomTabBar}>
```
