### ISSUE TITLE
when moving between screens in bottomTabNavigator the prevoius screen freezes

### ISSUE THREAD

**Issue by vikaschowdary47** [react-navigation/react-navigation#9248]
**Current Behavior**
when moving between screens 
Example I have A B C D screens in bottom tab
So, if go to B, and go back to screen A it doesn't work
if I go to C and go back to A and B they both doesn't work
they get stuck
not responding to any touch
- What code are you running and what is happening?
- Include a screenshot or video if it makes sense.

**Expected Behavior**
- What do you expect should be happening?
- Include a screenshot or video if it makes sense.

**How to reproduce**

- You must provide a way to reproduce the problem. If you are having an issue with your machine or build tools, the issue belongs on another repository as that is outside of the scope of React Navigation.
- Either re-create the bug on [Snack](https://snack.expo.io) or link to a GitHub repository with code that reproduces the bug.
- Explain how to run the example app and any steps that we need to take to reproduce the issue from the example app.
- Keep the repro code as simple as possible, with the minimum amount of code required to repro the issue.
- Before reporting an issue, make sure you are on latest version of the package.

**Your Environment**

| software                      | version |
| ----------------------------- | ------- |
| iOS or Android                | Android
| @react-navigation/native      | ^5.8.10
| @react-navigation/bottom-tabs | ^5.11.2
| react-native-screens          | ^2.16.1
| react-native                  | 0.63.4
| expo                          |
| node                          |
| npm or yarn                   | npm

**Comment by carlosfilipe** [comment]
Same issue using version 5.11.5 (installed on last friday)...

after update to 5.11.7, everything is working well

**Comment by Tammaoui** [comment]
Same issue.

**Comment by Tammaoui** [comment]
Same issue using version 5.9.2 and 5.11.7.

**Comment by jarederaj** [comment]
Dirty fix suggested by @frabanca

https://github.com/react-navigation/react-navigation/issues/9241#issuecomment-766636052

**Comment by vikaschowdary47** [comment]
> Dirty fix suggested by @frabanca
> 
> [#9241 (comment)](https://github.com/react-navigation/react-navigation/issues/9241#issuecomment-766636052)

did it work? using that fix?
 @jarederaj

**Comment by vikaschowdary47** [comment]
> Same issue using bottom-tabs version 5.11.5 (installed on last friday)...
> 
> after update to 5.11.7, everything is working well

is it working properly after update?
@carlosfilipe

**Comment by rnz269** [comment]
@vikaschowdary47 I had the same issue using bottom-tabs version 5.11.5. I just updated to 5.11.7 and it's working properly after update.

**Comment by JANGFREEMAN** [comment]
> Same issue using bottom-tabs version 5.11.5 (installed on last friday)...
> 
> after update to 5.11.7, everything is working well

it is work for me !!!! thanks
