### ISSUE TITLE
_native.createNavigatorFactory is not a function

### ISSUE THREAD

**Issue by IPWright83** [react-navigation/react-navigation#9249]
**Current Behavior**

Attempting to run tests with Jest and I'm getting this error:

> TypeError: (0 , _native.createNavigatorFactory) is not a function
>
>      at Object.<anonymous> (node_modules/@react-> navigation/stack/lib/commonjs/navigators/createStackNavigator.tsx:93:16)
>      at Object.<anonymous> (node_modules/@react-navigation/stack/lib/commonjs/index.tsx:9:1)

**Expected Behavior**

No errors triggered from this library, or alternatively something in the README.md to explain how to mock dependencies for this library for Jest testing.

**How to reproduce**

Create a unit test with a React component that uses a `<Stack.Navigator>` component within it. Then run Jest

**Versions**
"@react-navigation/bottom-tabs": "^5.8.0",
"@react-navigation/native": "^5.7.3",
"@react-navigation/stack": "^5.9.3",

**Comment by IPWright83** [comment]
I'm not able to test on the latest version right now, as that causes my application to crash. So I'd need to spend more time investigating/upgrading.

**Comment by mdbiscan** [comment]
Under the same scenario, I see this same issues. Trying to unit test navigators.

```
"@react-navigation/bottom-tabs": "^5.11.8"
"@react-navigation/native": "^5.8.10"
"@react-navigation/stack": "^5.12.8"
```

**Comment by TommyLeong** [comment]
Hello @IPWright83, do you mange to find a solution/workaround for this?

**Comment by IPWright83** [comment]
@TommyLeong good question - I was sure I had and forgotten the solution, but looking back I actually just left that section of code un-tested for the time being :(

**Comment by kopax-polyconseil** [comment]
Hello, we are just hitting this also in our project, any clue ?

**Comment by Prakosa** [comment]
for anyone who face this issue you can mock it like this : 
(you can mock it depend on the component you use)

`jest.mock("@react-navigation/stack", () => {
  return {
    createStackNavigator: () => {}
  }
})`

**Comment by trcoffman** [comment]
This bug is affecting us as well. We cannot do snapshot testing because we hit this error in our tests.

**Comment by droplessjordan** [comment]
Hitting the same error when run tests also. Any updates?

**Comment by yukster** [comment]
I'm just getting started on adding tests (jest/react-native-testing-library) for a small RN/expo app with React Navigation. I followed the instructions here:

https://reactnavigation.org/docs/testing

to set up my jest.setup file, but the file it says to import (react-native-gesture-handler/jestSetup) has an issue:

```
 Cannot find module 'react-native/Libraries/Animated/NativeAnimatedHelper' from 'setupJest.js'

    > 1 | import 'react-native-gesture-handler/jestSetup';
```

Maybe this doc is out of date?

**Comment by dvyne10** [comment]
Any solution to this problem yet?

**Comment by dvyne10** [comment]
I solved mine by creating a stack navigator (createStackNavigator ) to render the screen rather than just rendering the screen component, and also followed this https://reactnavigation.org/docs/testing/. @IPWright83 @trcoffman 
kindly see if it helps.

**Comment by arcollector** [comment]
i  leave my solution

`__mocks__/@react-navigation/native.js`

```js
module.exports = {
  createNavigatorFactory: jest.requireActual('@react-navigation/native').createNavigatorFactory,
};
```

`__mocks__/@react-navigation/drawer.js`

```js
module.exports = {
  createDrawerNavigator() {
    return {
      Navigator() { return null; },
      Screen() { return null; },
    }
  }
};
```

**Comment by RageOfJustice** [comment]
Hello everyone!
I faced the same error in my test using jest. 
I had next mock in my test file
```javascript

jest.mock('@react-navigation/native', () => ({
  useNavigation: () => {
    return { navigate: jest.fn() };
  },
}));

```

But I tried all solutions provided here and they did not work. Then I decided to try another trick:
```javascript

jest.mock('@react-navigation/native', () => ({
  ...jest.requireActual('@react-navigation/native'),
  useNavigation: () => {
    return mockNavigation;
  },
}));
```

Now it's working. Hope it'll help

**Comment by rafaelmaeuer** [comment]
> Hello everyone! I faced the same error in my test using jest. I had next mock in my test file
> 
> ```js
> jest.mock('@react-navigation/native', () => ({
>   useNavigation: () => {
>     return { navigate: jest.fn() };
>   },
> }));
> ```
> 
> But I tried all solutions provided here and they did not work. Then I decided to try another trick:
> 
> ```js
> jest.mock('@react-navigation/native', () => ({
>   ...jest.requireActual('@react-navigation/native'),
>   useNavigation: () => {
>     return mockNavigation;
>   },
> }));
> ```
> 
> Now it's working. Hope it'll help

What did you use as `mockNavigation` ???

**Comment by iviveros-code** [comment]
@rafaelmaeuer  Hey man, works with:

`const mockNavigation = jest.fn();
jest.mock('@react-navigation/native', () => ({
  ...jest.requireActual('@react-navigation/native'),
  useNavigation: () => {
    return mockNavigation;
  },
}));`

**Comment by felipemillhouse** [comment]
> ```js
> createNavigatorFactory: jest.requireActual('@react-navigation/native').createNavigatorFactory,
>   NavigationContainer: (props) => props.children,
> ```

it shows the follow error message to me:
```
The module factory of `jest.mock()` is not allowed to reference any out-of-scope variables.
 Invalid variable access: __assign
```
mock code:
```JS
const mockedDispatch = jest.fn();
jest.mock("@react-navigation/native", () => {
  const actualNav = jest.requireActual("@react-navigation/native");
  return {
    ...actualNav,
    useNavigation: () => ({
      navigate: jest.fn(),
      dispatch: mockedDispatch,
    }),
    useIsFocused: () => true,
    useRoute: () => ({
      params: {
        email: "",
      },
      name: "EmailLogin",
    }),
  };
});
```
![Screen Shot 2022-09-08 at 4 21 57 PM](https://user-images.githubusercontent.com/10479750/189218671-639d5e66-d46c-4905-b5eb-0068ca981e89.png)

Is anyone at the same situation?
