### ISSUE TITLE
Typescript checking not working when navigating using a ref 

### ISSUE THREAD

**Issue by alialaa** [react-navigation/react-navigation#9259]
I am in a situation where I need to use a ref to navigate in my stack navigator, so I have my ref setup:
```js
const navigatorRef = useRef<NavigationContainerRef>(null);

<NavigationContainer
    ref={navigatorRef}
    onReady={() => {
        setIsNavigatorReady(true);
    }}
>
  <Stack.Navigator>.....</Stack.Navigator>
</NavigationContainer>
```
But now when navigating, let's say I pass a screen that does not exist, I don't get any typescript error:
```js
navigatorRef.current?.navigate("DoesNotExist");
```
I have defined my screens and passed them to `createStackNavigator`:
```js
type StackNavigationParams = {
    Screen1: undefined;
    Screen2: undefined;
}
const Stack = createStackNavigator<StackNavigationParams>();
```

Is this an intended behaviour or a bug? is there a way to pass the StackNavigationParams to the ref somehow? I didn't find that in the docs.

Thanks

| software                       | version |
| ------------------------------ | ------- |
| @react-navigation/stack               | 5.9.0
| @react-navigation/native       | 5.7.3

**Comment by alialaa** [comment]
> The versions mentioned in the issue for the following packages differ from the latest versions on npm:
> 
> * `@react-navigation/stack` (found: `5.9.0`, latest: `5.14.2`)
> * `@react-navigation/native` (found: `5.7.3`, latest: `5.9.2`)
> 
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?

Yes I tried updating and still the same.

**Comment by sanduluca** [comment]
Why you are using ref when there is `useNavigation` hook 
```typescript
import * as React from 'react';
import { Button } from 'react-native';
import { useNavigation } from '@react-navigation/native';
import {    StackNavigationProp } from '@react-navigation/stack';

type YourNavigatorProp = StackNavigationProp<ParamList, keyof ParamList>

function Screen() {
  const navigation = useNavigation<YourNavigatorProp>();

  return (
    <Button
      title="Screen2"
      onPress={() => {
        navigation.navigate('Screen2');
      }}
    />
  );
}
```

You can find more info here 
https://reactnavigation.org/docs/use-navigation
https://reactnavigation.org/docs/typescript#annotating-usenavigation

**Comment by alialaa** [comment]
Because I need to navigate outside of the navigator, not inside a screen. I assume this hook can only be used inside the navigator, correct?

**Comment by sanduluca** [comment]
You want to navigate from a screen from your StackNavigator, to a screen outside of navigator. Is that correct ?

**Comment by alialaa** [comment]
No I want to navigate to a screen but not from another screen, from a component outside the navigator component:
```js
function Component() {
    //somewhere in this component
    navigatorRef.current?.navigate("ScreenName")
    return (
        <NavigationContainer
            ref={navigatorRef}
        >
            ...
        </NavigationContainer>
    )
}
```

**Comment by sanduluca** [comment]
As it says in documentation

> `NavigationContainer` is a component which manages our navigation tree and contains the navigation state. **`This component must wrap all navigators structure.`** Usually, we'd render this component at the root of our app, which is usually the component exported from App.js.

You can use `useNavigation` hook inside a screen navigator.

From your example, you can't navigate to that `ScreenName`, because `navigatorRef.current` is null/undefined at that moment and that line basically will result to false and will do nothing

**Comment by alialaa** [comment]
No it's actually working. But that's not my question, my problem is that typescript checking is not working when I navigate that way.

Here's using ref in the docs just for your reference: https://reactnavigation.org/docs/navigation-container/#ref

**Comment by Kleinhummel** [comment]
I have the same issue. Explained it a bit differently in #9391

**Comment by Kleinhummel** [comment]
@alialaa Have you already found a solution?

**Comment by alialaa** [comment]
@Kleinhummel no unfortunately

**Comment by lauramann** [comment]
I am having the same issue.

**Comment by satya164** [comment]
Type-checking on the ref is now supported in v6 (pre-release)

https://reactnavigation.org/docs/6.x/typescript#annotating-ref-on-navigationcontainer
https://reactnavigation.org/docs/6.x/typescript#specifying-default-types-for-usenavigation-link-ref-etc
