### ISSUE TITLE
Bugs don't navigate screen when custom tabbar bottom tab

### ISSUE THREAD

**Issue by markgotit** [react-navigation/react-navigation#9261]
![image](https://user-images.githubusercontent.com/52577080/106312732-b61ffc80-6299-11eb-8b6c-b0072a729a20.png)
![image](https://user-images.githubusercontent.com/52577080/106312763-c3d58200-6299-11eb-8004-2f1a28faf18d.png)
![image](https://user-images.githubusercontent.com/52577080/106312781-cafc9000-6299-11eb-8232-b6a9666431ba.png)
MyTabBar
![image](https://user-images.githubusercontent.com/52577080/106312798-cfc14400-6299-11eb-9e2c-8042959979a1.png)
Video Bugs: https://www.loom.com/share/f8911a7509de405eb4f8ef082f907b12

**Comment by nnhunguet** [comment]
> Couldn't find version numbers for the following packages in the issue:
> 
> * `@react-navigation/native`
> 
> Can you update the issue to include version numbers for those packages? The version numbers must match the format 1.2.3.

"@react-navigation/bottom-tabs": "^5.11.2",
"@react-navigation/native": "^5.8.10"
"@react-navigation/stack": "^5.12.8",
"react-native": "0.63.4",

**Comment by nnhunguet** [comment]
Help me, i don't navigate screen.
Bug description in my video, image is my code ! Help me !

**Comment by nnhunguet** [comment]
bug when i navigate depth >= 2 screen. I don't navigate !
