### ISSUE TITLE
The action 'NAVIGATE' with payload was not handled by any navigator

### ISSUE THREAD

**Issue by 2006Ted** [react-navigation/react-navigation#9263]
**Current Behavior**

This error is happening: The action 'NAVIGATE' with payload was not handled by any navigator.

**Expected Behavior**

to move DiaryScreen to ViewScreen.

**How to reproduce**

`
import React from 'react';
import { StyleSheet, Text, View, TouchableOpacity } from 'react-native';
import { NavigationContainer, useNavigation } from '@react-navigation/native'
import { createBottomTabNavigator } from '@react-navigation/bottom-tabs'
import { Ionicons } from '@expo/vector-icons'
import { createStackNavigator } from '@react-navigation/stack'

import AddStackScreen from './screens/AddStackScreen'
import HomeScreen from './screens/HomeScreen'
import ViewScreen from './screens/ViewScreen'

import Header from './components/Header'

const Stack = createStackNavigator();

function ViewStackScreen(){
    return (
        <Stack.Navigator>
            <Stack.Screen name="View" component={ViewScreen}
            options={{
                headerShown: false,
            }}
            />
        </Stack.Navigator>
    )
}

 function DiaryScreen () {
    return (
        <View style={styles.diarycontainer}>
            <Header title="My Diary" />
            <ArticleItem 
            article={{
                id: 1,
                title: 'test1',
                content: 'test1',
                date: '2021/01/25'
            }}
            
            />
            <ArticleItem 
            article={{
                id: 1,
                title: 'test2',
                content: 'test2',
                date: '2021/01/25'
            }}
            
            />
        </View>
    )
}

function ArticleItem ({
  article: {
      id,
      title,
      content,
      date,
  },
}){
  const navigation = useNavigation();
  return (
<TouchableOpacity
activeOpacity={0.8}
onPress={() => 
  navigation.navigate('ViewStackScreen',{ screen: 'View' })
}
>
  <View style={styles.articlecontainer}>
      <View style={styles.articleicon}>
       <Ionicons name="md-list" size={14} color="#9E9E9E"/>   
      </View>
    <View style={styles.articleinfo}>
  <Text style={styles.articletitle}>
      {title}
  </Text>
  <Text style={styles.articlecontent} numberOfLines={2}>
      {content}
  </Text>
  <Text style={styles.articledate}>
      {date}
  </Text>
</View>  
  </View>

</TouchableOpacity>
  )
}
......
`
app.js

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| Android                 |
| @react-navigation/native:   5.9.2     |
| react-native: 0.63.4                  |
| expo:40.0.0                           |
| node  : 14.15.4                         |
| npm                  |

**Comment by Adnan-Bacic** [comment]
you didnt wrap <NavigationContainer> around the <Stack.Navigator>

**Comment by udapy** [comment]
> you didnt wrap `<NavigationContainer>` around the `<Stack.Navigator>`

Didn't work for me.

**Comment by Adnan-Bacic** [comment]
im assuming `DiaryScreen` is in the navigator as well even if its not shown here.
you dont have to do: `navigation.navigate('ViewStackScreen',{ screen: 'View' })`. you can just do `navigation.navigate('View')`

maybe its due to to `useNavigation()`? i dont think its necessary here. i usually just pass navigation as a prop.

```
const ReusableComponent = ({ navigation }) => {
return(
content here
)
}
```

```
const SomeScreenComponent= ({ navigation }) => {
return(
<ReusableComponent 
navigation={navigation}
>
</ReusableComponent >
)
}
```

this way i can just call `navigation.navigate()` in both files.

**Comment by sinfzx** [comment]
<Stack.Navigator>
      {/* {!token ? (
        <Stack.Screen name="SignUp" component={SignUpScreen} />
      ) : (
        <Stack.Screen name="Home" component={HomeScreen} />
      )} */}
      <Stack.Screen name="SignUp" component={SignUpScreen} />
      <Stack.Screen name="Home" component={HomeScreen} />
    </Stack.Navigator>


may be you like this. the code in annotation doesn't work, the outside works, still figuring out the issue

**Comment by chetin4ever** [comment]
https://java.tutorialink.com/the-action-navigate-with-payload-namehomescreenparams-was-not-handled-by-any-navigator-do-you-have-a-screen-named/
this article  may helpful

**Comment by IbthajSami** [comment]
I am getting the Same error as mentioned above

**Comment by danielprrazevedo** [comment]
I'm coming in late, had this problem recently and looked around for an official alternative. It seems to me that this is a problem with lazy/anxious loading.

What was happening is: I have a route that will only be created when there is authentication and the component referring to that route is called as soon as the user logs in

``` jsx
// BaseStack
<>
  {isAuthenticated && <Stack.Screen name="AuthScreen" component={AuthScreen} />}
  <Stack.Screen name="LoginScreen" component={LoginScreen} />
</>

// AuthScreen

<Stack.Navigator>
  <Stack.Screen name="DashboardScreen" component={DashboardScreen} />
  {/* ... */}
</Stack.Navigator>
```
so once the user logs in i'm triggering navigate('Home') in parallel to the state change (my first mistake) and also that i'm calling a named route to a lower level stacks instance (my second mistake).

``` jsx
// LoginScreen
function submit() {
  // ...
  dispatch(setSession(response))
  navigator.navigate('DashboardScreen')
}
```
My solution:

I moved the navigate to a react to state with use effect, however as I was calling a SubStack of routes, I still had the same problem, so I modified the call to a main route and added a call to the route inside my stack instance initial

```jsx// LoginScreen
function submit() {
  // ...
  dispatch(setSession(response))
}

const { isAuthenticated } = useAppSelector(selectSession)

useEffect(() => {
  if (isAuthenticated) {
    navigator.navigate('AuthScreen') // changed this to my root stack, because the sub stack can be not loaded in this time
  }
}, [isAuthenticated])

// AuthScreen

// Added an initial route name, so when this is loaded, automatically goes to my screen
<Stack.Navigator initialRouteName="DashboardScreen">
  <Stack.Screen name="DashboardScreen" component={DashboardScreen} />
  {/* ... */}
</Stack.Navigator>

```

**Comment by Sadagopan-30** [comment]
this error is occuring only in my 2nd page.but my first page was working perfectly.but with same code,second page was not showing output
