### ISSUE TITLE
Can't modify tabBarBadge size 

### ISSUE THREAD

**Issue by SuhwanCha** [react-navigation/react-navigation#9264]
tabBarBadgeStyle doesn't allow modify badge's size

**Comment by sanduluca** [comment]
Size of the badge is static and has a value of `18.75` but you can change the badge size by changing `maxWidth` & `maxHeight`.
You also will have to adjust by youself `lineHeight`, `fontSize` and other
```javascript
tabBarBadgeStyle: {
     maxWidth: 10,
     maxHeight: 10,
     fontSize: 8,
     lineHeight: 9,
     alignSelf: undefined,
}
```

**Comment by StuartFeldt** [comment]
I also had to set minWidth
