### ISSUE TITLE
Deep linking not working if navigator names are not unique

### ISSUE THREAD

**Issue by dickfickling** [react-navigation/react-navigation#9267]
**Current Behavior**
Nested navigators that share the same name cause deep linking to break. Opening a deep link while the app is not running will navigate to the right place, but if the app is running in the foreground or in the background, we won't navigate correctly.

- What code are you running and what is happening?
```
const linkingConfig = {
  prefixes: ['prefix://'],
  config: {
    screens: {
      Login: 'login',
      Register: 'register',
      Onboarding: 'onboarding',
      Main: {
        screens: {
          Main: {
            screens: {
              Home: {
                initialRouteName: 'Home',
                screens: {
                  Home: 'home',
                  ExternalProfile: {
                    screens: {
                      ExternalProfile: 'user/:userId',
                    },
                  },
                },
              },
            },
          },
        },
      },
    },
  },
};

... snip ...

          <NavigationContainer
            linking={linkingConfig}
          >
            <AppNavigator />
          </NavigationContainer>

... snip ...
```

Our AppNavigator component has two `StackNavigator.Screen` components with the name `Main`. They are different components, and we have now renamed one of them which fixed this issue.

**Expected Behavior**

If the app is running, I should be able to navigate to `prefix://user/:userId`. This isn't really a huge issue as it was an easy fix, but it took us _forever_ to diagnose why it was happening. My goal in posting this is one of:
- users who run into this error and search for it will find this post and be able to fix their problem
- somebody fixes it in react-navigation
- something gets added to documentation to call out this gotcha.
I'm happy to push up a PR to add a note to the documentation; just say the word and I'll do it.

**How to reproduce**

Create a basic app with the navigation config described above, and try to open `prefix://user/:userId`. It won't work if the app is running. If you rename one of the `Main` navigators, navigation will work as expected.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | iOS 13.7 and iOS 14.4 (didn't test android) |
| @react-navigation/native       | 5.9.2 |
| react-native                   | latest |
| expo                           | not using |
| node                           | 14 |
| npm or yarn                    | npm |

**Comment by lorenzoangelini** [comment]
I'have a similar issue, i obtain this console warn "The navigation state parsed from the URL contains routes not present in the root navigator. This usually means that the linking configuration doesn't match the navigation structure. See https://reactnavigation.org/docs/configuring-links for more details on how to specify a linking configuration."

with "@react-navigation/native": "5.5.1", no problems
with"@react-navigation/native": "5.9.2" get the issue

**Comment by EyMaddis** [comment]
@lorenzoangelini Wow... This broke a crucial feature (payment process) in an app:
https://github.com/react-navigation/react-navigation/commit/52451d11094b8551e3c6950b3e005d68225c7da9

This was a breaking change in a minor version upgrade. I am very frustrated.
My config used to be so simple `someScreen: 'my/pretty/path'`, now it will be a nested nightmare... :/

All I had to make sure whats that someScreen is available somewhere, now that is not the case and I need to duplicate the whole structure and I am unsure what to do with something like un-/authenticated screens

**Comment by satya164** [comment]
It's not a breaking change. The documentation already asked you to nest things properly and if you didn't, it would've not worked at all if your app wasn't open yet.

**Comment by EyMaddis** [comment]
Well, touché. 
I actually had this issue and worked around it in the app...

**Comment by satya164** [comment]
> This could open the authenticated screen even if the user details are not loaded...

If you're conditionally rendering screens, it'd be impossible to open the screens not rendered since they aren't visible to React Navigation at all. In which case it would just render the first available screen (which probably is the login screen).

**Comment by EyMaddis** [comment]
I will switch to a useEffect() based solution where I get the link my self and open the screen.
I actually want to render the default screen and then open the new screen. 
I think I can achieve that via a simple `if(link === 
'...') navigate('myScreen')`.

**Comment by satya164** [comment]
> I think I can achieve that via a simple if(link === '...') navigate('myScreen').

The thing is it may not work in case of nested navigators. Since with dynamic definition, it's not possible to know where the screen is upfront. That's why it needs a different API for navigating to nested navigators (https://reactnavigation.org/docs/nesting-navigators/#navigating-to-a-screen-in-a-nested-navigator) and proper nesting in deep link config.

**Comment by voku** [comment]
Hi, I have also a problem with Deep-Linking: Screens in the main navigation (Bottom) are working, but I don't know how to get the Link from nested Stack navigations. Is it possible, or do I need to manually navigate into the nested navigation?
