### ISSUE TITLE
Bottom Tab translation leave empty space on screen

### ISSUE THREAD

**Issue by sanduluca** [react-navigation/react-navigation#9268]
**Current Behavior**
I have a Tab Navigator. 
Something like this
```javascript
return (
  <NavigationContainer>
    <Tab.Navigator
      tabBar={(props) => {
        return (
          <Animated.View style={{ transform: [{ translateY: -60 }] }}>
            <BottomTabBar {...props} />
          </Animated.View>
        )
      }}
    >
      <Tab.Screen name="Home" component={HomeScreen} />
      <Tab.Screen name="Settings" component={SettingsScreen} />
    </Tab.Navigator>
  </NavigationContainer>
);
```
As you can see I wrapped `BottomTabBar` with an `Animated.View` from `react-native-reanimated`
The point is when I am translating the tabbar, content is not filling the empty space

![image](https://user-images.githubusercontent.com/56228534/106475948-30759a00-64af-11eb-817b-1f05e18661d4.png)

In addition, when I am positioning my FAB (floating action button) closer to bottom, it goes under the tabbar 
![image](https://user-images.githubusercontent.com/56228534/106479405-f908ec80-64b2-11eb-9bf2-13bb4d1ca734.png)

**Expected Behavior**

- I expected that when I do translate the tab bar, content will fill the space. Actually I expect that content should go under the the tabbar with an element like `View`  at the bottom with height as tabbar height

**What I want to achieve**
-When I scroll up, tabbar will be translated down and a FAB (floating action button) will appear.
-When I scroll down, tabbar will be translated up and the FAB will disappear.
![image](https://user-images.githubusercontent.com/56228534/106477731-218fe700-64b1-11eb-84de-492cff3bd31e.png)

I want to mention that I don't like the approach of setting navigationOption `tabBarVisible` value based on scroll value

| software                      | version |
| ----------------------------- | ------- |
| iOS or Android                | android
| @react-navigation/native      |  ^5.9.2
| @react-navigation/bottom-tabs | ^5.11.7
| react-native-screens          |^2.17.1
| react-native                  |^0.63.4

**Comment by sanduluca** [comment]
Giving a style of `absolute` fixed, the empty space
```javascript
tabBar={(props) => {
     const  transitionFooterY  = .....
    return (
        <Animated.View style={{
            transform:[{ translateY: transitionFooterY }],
            position: "absolute",
            bottom: 0,
            left: 0,
            right: 0
        }}>
            <BottomTabBar {...props} />
        </Animated.View>
    )
  }}
```

**Comment by Jolteon18** [comment]
@sanduluca thaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaanks, it workedd

**Comment by yashsway** [comment]
@sanduluca wow can't believe this worked - thank you! I had to pair this with some changes to make the custom footer re-render as well because I'm 100% sure there is a rendering bug with the `Tab.Navigator`.

Posting solution below for reference for following versions:
```
    "@react-navigation/bottom-tabs": "^6.5.8",
    "@react-navigation/drawer": "^6.5.8",
    "@react-navigation/material-top-tabs": "^6.6.5",
    "@react-navigation/native": "^6.1.3",
    "@react-navigation/native-stack": "^6.9.9",
    "react-native": "0.73.6",
    "react-native-reanimated": "~3.6.2",
```

Here's how I got the custom footer to re-render. I made a custom hook to get the screen options (because for some baffling reason this is not provided by `react-navigation`. I had to come up with a convoluted way to get the _latest_ screen options which is not possible without listening to the `options` event... which in of itself is not well documented):
```ts
import {
  createNavigationContainerRef,
  EventListenerCallback,
  NavigationContainerEventMap,
} from "@react-navigation/native";
import { useEffect, useState } from "react";

// remember, this ref is passed to the `NavigationContainer` somewhere in the root component of your app's render tree
export const navigationRef = createNavigationContainerRef();

export const useCurrentRouteOptions = <T = Record<string, any>,>() => {
  const isNavigationReady = navigationRef.isReady();
  const currentRouteOpts =
    navigationRef.getCurrentOptions() as T;
  const [routeOptions, setRouteOptions] = useState<
   T
  >(currentRouteOpts ?? {});

  useEffect(() => {
    const listener: EventListenerCallback<
      NavigationContainerEventMap,
      "options"
    > = ({ data }) => {
      setRouteOptions(data.options as T);
    };

    // when navigation happens sometimes, the navigationRef.getCurrentOptions()
    // fetches screen options too early, so the screen options are inaccurate.
    // tapping into the options event, we can access the screen options of the
    // current focused screen properly
    navigationRef.addListener("options", listener);

    return () => navigationRef.removeListener("options", listener);
  }, [setRouteOptions]);

  if (!isNavigationReady) return {} as Partial<T>;
  return routeOptions;
};
```

and I use this in the custom `<Footer />` component provided to the `tabBar` prop of the `<Tab.Navigator />` component provided by react navigation.
```ts
import { createBottomTabNavigator } from "@react-navigation/bottom-tabs";
import Animated from "react-native-reanimated";

const Tab = createBottomTabNavigator<MainBottomTabsParamList>();

const Router = () => {
  return (
    <Tab.Navigator
      tabBar={(props) => (
        // react navigation bug causes footer area to be preserved even if it
        // gets hidden before render by screen options, so the footer must be in
        // an absolute container to take it out of the view. see
        // https://github.com/react-navigation/react-navigation/issues/9268#issuecomment-771018653
        <Animated.View
          style={{
            position: "absolute",
            bottom: 0,
            left: 0,
            right: 0,
          }}
        >
          <Footer {...props} />
        </Animated.View>
      )}
      initialRouteName="Home"
      screenOptions={{
        headerShown: false,
        lazy: false,
      }}
      backBehavior="initialRoute"
    >
      {/* Tab.Screen components below omitted for brevity */}
    </Tab.Navigator>
  );
};
```
