### ISSUE TITLE
react-navigation-drawer - release new version?

### ISSUE THREAD

**Issue by savv** [react-navigation/react-navigation#9269]
**Current Behavior**

I recently upgraded react-native-screens to the latest version (2.17.1) which requires changing from using `active` to `activityState` - see also here https://github.com/software-mansion/react-native-screens/issues/704
See warning at the end of the screen.

This change seems to have already been made to the legacy code: https://github.com/react-navigation/react-navigation/commit/5c7f892d77298f5c89534fa78a1a6a59c7f35a60

All that's required is pushing a new version of react-navigation-drawer that includes all the latest changes.

**How to reproduce**

I'm happy to produce a repro if necessary, but the issue seems clear (latest version of react-navigation-drawer was released in Oct, whereas the fix above was in Dec).

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | iOS
| react-navigation               | ^4.4.3
| react-navigation-stack         |2.10.2
| react-navigation-tabs          |-
| react-navigation-drawer        |^2.6.0
| react-native-reanimated        |^1.13.2
| react-native-gesture-handler   | ^1.9.0
| react-native-safe-area-context | ^3.1.9
| react-native-screens           | ^2.17.1
| react-native                   | 0.63.4
| node                           | 14
| npm or yarn                    | yarn

![simulator_screenshot_577A0532-AE64-45BD-836C-FCF84EC07CBB](https://user-images.githubusercontent.com/747519/106511377-6e36ea80-64d0-11eb-9405-efea6d6b501a.png)

**Comment by codercodingthecode** [comment]
Having the same issue
