### ISSUE TITLE
Group several screens in the same Context

### ISSUE THREAD

**Issue by chj-damon** [react-navigation/react-navigation#9271]
**Current Behavior**
Currently I define all the screens in <Stack.Navigator>

**Expected Behavior**
I want to define Context for several screens, like this:
```ts
<Stack.Navigator>
    <ContextOne.Provider value={{xxx}}>
        <Stack.Screen name="Screen1" component={Screen1} />
        <Stack.Screen name="Screen2" component={Screen2} />
    </ContextOne.Provider>
    <ContextTwo.Provider value={{xxx}}>
        <Stack.Screen name="Screen3" component={Screen3} />
        <Stack.Screen name="Screen4" component={Screen4} />
    </ContextTwo.Provider>
</Stack.Navigator>
```
it won't work in this way.

what should I do to achieve this?

**Comment by chj-damon** [comment]
I solved this problem.

**Comment by mccraveiro** [comment]
@chj-damon I'd also like to know :/

**Comment by paour** [comment]
The usual suggestion is for the screens that need to be wrapped inside a ContextProvider, to be nested inside another Screen > ContextProvider > Stack. This is much more verbose (especially when you factor in TS typing for the navigation) so a better solution is desirable. I had high hopes for Stack.Group, but it doesn't seem to solve this particular use-case.
