### ISSUE TITLE
Duplicate tabBarIcon in react tree

### ISSUE THREAD

**Issue by myckhel** [react-navigation/react-navigation#9272]
@react-navigation/native:5.7.3

The implementation of `tabBarIcon` causes `tabBarIcon` to be buggy when used as functional component (component that compute some inner functions).

Given this example: 
```jsx
<Tab.Screen
    options={{
      tabBarIcon: ({focused}) => (
        <CountableInbox key='4663' focused={focused} />
      ),
    }}
    name="Inbox"
    component={InboxScreen}
  />


const CountableInbox = memo(({focused}) => {
  const navigation = useNavigation()
  
  const {
    state: {data: count},
    setState,
  } = useConversationCount();
  
  useEventListener({
    names: [RELOAD_UNREAD_CONVERSATION_COUNT],
    callback: () =>
      setState(({data, ...s}, merge) => merge(s, {data: (data || 0) + 1})),
  });

  useLayoutEffect(() => {
    navigation.setOptions({tabBarBadge: count});
  }, [count]);
  
  return <Icon focused={focused} Icon={Chat} />;
});
```

Since `tabBarIcon` is always mounted twice so the `CountableInbox` component will be created twice and will cause `useConversationCount` to make network request twice.

https://github.com/react-navigation/react-navigation/blob/860adbfd8b4c493dc3e28c99ad5d78699c2f8797/packages/bottom-tabs/src/views/TabBarIcon.tsx#L49

From then referenced file i am sure the `renderIcon` can be called once based on the active prop.

Please help refactor `TabBarIcon`

**Comment by satya164** [comment]
https://github.com/react-navigation/react-navigation/pull/9273#issuecomment-774031982

**Comment by myckhel** [comment]
Hello,
i request for this issue to be opened.

i think the issue has not been resolved and no helping suggestion was provided.
