### ISSUE TITLE
Layout Structure Top Tab Navigator

### ISSUE THREAD

**Issue by sanduluca** [react-navigation/react-navigation#9275]
Is there a way to create a layout like this ?
![image](https://user-images.githubusercontent.com/56228534/106649923-e833a600-659a-11eb-88cf-c78bd2ae29d0.png)

Current structure
```javascript
<ScrollView>
    <UserInfo />
    <Tab.Navigator>
        <Tab.Screen children={/*here goes a FlatList with data*/} />
        <Tab.Screen children={/*here goes another FlatList with data*/} />
    </Tab.Navigator>
</ScrollView>
```
#### I was thinking how I can restructure this screen to get rid of warning, but could not think anything.

| software                            | version |
| ----------------------------------- | ------- |
| iOS or Android                      | Android
| @react-navigation/native            |  ^5.9.2
| @react-navigation/material-top-tabs | ^5.3.13
| react-native-tab-view               | ^2.15.2
| react-native                        | ^0.63.4

**Comment by trinhlinh0307** [comment]
same issue, how do u resolve this issue?

**Comment by RRaideRR** [comment]
@trinhlinh0307 @sanduluca have you found a solution for this?
