### ISSUE TITLE
Bottom Tab bar's labels are shifting during render

### ISSUE THREAD

**Issue by easonccc1** [react-navigation/react-navigation#9279]
**Current Behavior**
During page rendering, the bottom tab's labels are shifting their position. I already set the absolute position. 

**Expected Behavior**
bottom tab bar labels position should be fixed.

**How to reproduce**

```
<Tab.Navigator
      initialRouteName="HomepageMain"
      tabBarOptions={{
        style: {
          position: 'absolute',
          bottom: 0,
          left: 0,
          right: 0,
          backgroundColor: 'yellow',
        },
      }}
    >
      <Tab.Screen
        name="A"
        component={A}
        options={({route}) => ({
          tabBarLabel: 'A',
          tabBarIcon: ({ color, size }) => (
            <MaterialIcons
              name="cleaning-services"
              color={color}
              size={size}
            />
          ),
          tabBarVisible: getTabBarVisible(route),
        })}
      />
      <Tab.Screen
        name="B"
        component={B}
        options={{
          tabBarLabel: 'B',
          tabBarIcon: ({ color, size }) => (
            <MaterialCommunityIcons name="newspaper-variant-outline" color={color} size={size} />
          ),
          //tabBarBadge: 3,
        }}
      />
      <Tab.Screen
        name="C"
        component={C}
        options={{
          tabBarLabel: 'C',
          tabBarIcon: ({ color, size }) => (
            <MaterialCommunityIcons name="account-outline" color={color} size={size} />
          ),
        }}
      />
    </Tab.Navigator>
  );
```

**Your Environment**

| software                      | version |
| ----------------------------- | ------- |
| iOS or Android                | Android
| @react-navigation/native      | 5.9.0
| @react-navigation/bottom-tabs | 5.11.3
| react-native-screens          | 2.15.2
| react-native                  | 0.63.4

https://user-images.githubusercontent.com/29586734/106725641-8e87b600-6644-11eb-9b59-05bf79857531.mp4

**Comment by easonccc1** [comment]
> The versions mentioned in the issue for the following packages differ from the latest versions on npm:
> 
> * `@react-navigation/native` (found: `5.9.0`, latest: `5.9.2`)
> * `@react-navigation/bottom-tabs` (found: `5.11.3`, latest: `5.11.7`)
> 
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?

Tried latest version. The problem is still there.

**Comment by satya164** [comment]
Closing due to no response
