### ISSUE TITLE
sub.remove is not a function

### ISSUE THREAD

**Issue by octagonalsquare** [react-navigation/react-navigation#9280]
**Current Behavior**

I am creating a focus listener in the componentDidMount() function and removing it in componentWillUnmount() as shown in the docs. Here is what that looks like:
```
componentDidMount() {
    this._unsubscribe = this.props.navigation.addListener('focus', () => focusListener());
}
componentWillUnmount() {
  this._unsubscribe();
}
```
But when I return to this page or expo refreshes due to saving a file, I get an error that reads:
`sub.remove is not a function. (In 'sub.remove()', 'sub.remove is undefined)`

The location says it is in:
`node-modules/@react-navigation/core/lib/module/views/withNavigationFocus.js`

**Expected Behavior**

What I expect to happen is not have an error thrown when I am using functions as explained in the docs. I assume that when I return to the screen, it shouldn't be executing the componentWillUnmount since the screen is active. Am I missing something?

**How to reproduce**

I am unable to reproduce it in a minimal project. But it happens when I pass initial params to the screen and use the back button to return to it later or when the app refreshes due to a code change in expo.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS and Android                 | iOS 13.3 and Android 5.1.1
| @react-navigation/native       | 5.9.2
| @react-navigation/stack        | 5.12.8

**Comment by octagonalsquare** [comment]
> The versions mentioned in the issue for the following packages differ from the latest versions on npm:
> 
> * `@react-navigation/stack` (found: `5.12.8`, latest: `5.14.2`)
> 
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?

Yes, even after upgrading all parts of the @react-navigation package, it still has the error. I am using expo if that helps. I am also trying to fix the snack so it will actually work

**Comment by octagonalsquare** [comment]
Don't use the withNavigationFocus high level component. That was the problem

**Comment by GabrielDvt** [comment]
What did you use instead? How did you solve the problem?

**Comment by thijs-qv** [comment]
For anyone looking for a fix: I used the useIsFocused hook instead. If you're using a class component you can use it as such:
`
import {useIsFocused} from '@react-navigation/native';
export default function(props) {
  const isFocused = useIsFocused();
  return <YourClassComponent {...props} isFocused={isFocused} />;
}
`
