### ISSUE TITLE
After push 2nd large list page in stack make screen lag

### ISSUE THREAD

**Issue by zoom2009** [react-navigation/react-navigation#9289]
- @react-navigation/native version ^5.8.2

I have 2 page
- page A contain large list using recycle view
- page B same thing contain large list using recycle view

My problem is
My currentPage is ```A``` and after ```navigation.push(B)```   that make ```B``` slow.

I try to change ```navigation.push``` to ```navigation.replace``` that look fine not slow but I need to able to ```goBack()```

#### My question is 
Can I still push page into stack and not slow because I want to able to goBack()

And I already change ```RecyclerListView``` to ```react-native-large-list-v3``` still slow.

Sorry for my english
thank you

**Comment by satya164** [comment]
https://reactnavigation.org/docs/react-native-screens/
