### ISSUE TITLE
cardStyleInterpolator not working as expected in IOS

### ISSUE THREAD

**Issue by moriax** [react-navigation/react-navigation#9292]
**Current Behavior**

Code:
```
import { NavigationContainer, useNavigation } from '@react-navigation/native';
import { CardStyleInterpolators, createStackNavigator } from '@react-navigation/stack';
import React from 'react';
import {  View,  Text,  Button,} from 'react-native';

const Stack = createStackNavigator();


const TestScreen = () => {
  return (
    <View>
      <Text>HELLO WORLD</Text>
    </View>
  )
}

const HomeScreen = ({navigation}) => {

  return (  
    <View>
      <Button onPress={() => navigation.navigate('Test')} title='OpenModal' />
    </View>
  );
}

const App = () => {
  return (
    <NavigationContainer>
        <Stack.Navigator>
          <Stack.Screen name="Home" component={HomeScreen} />
          <Stack.Screen name="Test" component={TestScreen} options={{cardStyleInterpolator:CardStyleInterpolators.forModalPresentationIOS}} />
        </Stack.Navigator>
    </NavigationContainer>
  )
};

export default App;
```

![image](https://user-images.githubusercontent.com/12937605/107148388-10ccee80-6953-11eb-8a9c-5f564e7ec4bc.png)

**Expected Behavior**

The forModalPresentationIOS is only working correct in Android, but on IOS it looks strange.
The header bar is not moving down like in android.

**How to reproduce**

1. Create new react-native project, 
2. install react navigation
3. add two screens. 
4. add cardstyleinterpolator options to second screen
5. navigate

**Your Environment**
  "dependencies": {
    "@react-native-community/masked-view": "^0.1.10",
    "@react-navigation/native": "^5.9.2",
    "@react-navigation/stack": "^5.14.2",
    "react": "16.13.1",
    "react-native": "0.63.4",
    "react-native-gesture-handler": "^1.9.0",
    "react-native-reanimated": "^1.13.2",
    "react-native-safe-area-context": "^3.1.9",
    "react-native-screens": "^2.17.1"
  },

**Comment by moriax** [comment]
> The versions mentioned in the issue for the following packages differ from the latest versions on npm:
> 
> * `@react-navigation/bottom-tabs` (found: `5.11.2`, latest: `5.11.7`)
> * `@react-navigation/native` (found: `5.8.10`, latest: `5.9.2`)
> * `@react-navigation/stack` (found: `5.12.8`, latest: `5.14.2`)
> 
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?

created new test project, and problem still exists with latest version

**Comment by satya164** [comment]
We recommend to create a separate stack at root for modals: https://reactnavigation.org/docs/modal/

Mixing Modal presentation style with regular screens isn't possible.

**Comment by moriax** [comment]
Hello satya, 
thanks that helped to get it better, but still not perfect:
The header has the double height and the background is not getting smaller like on android..
![image](https://user-images.githubusercontent.com/12937605/107833439-9279ad80-6d93-11eb-88d8-f22237822ae4.png)

And if we have to use seperate stacks, you should add them to the snack examples on ?
https://reactnavigation.org/docs/stack-navigator/

**Comment by moriax** [comment]
@satya164 
Hi satya, should I create new isse, or can you reopen this?

Thanks

**Comment by mattwoberts** [comment]
I'm having the same issue here actually.. It seems that the header component adjust it's height for the notch, so you end up with an overly padded header component : 

<img width="647" alt="CleanShot 2021-03-19 at 13 03 57@2x" src="https://user-images.githubusercontent.com/109196/111784676-95485080-88b3-11eb-92ac-d6e23a86c982.png">

I've tried styling the header component with height, but it doesn't affect the internal padding that the header component is using.

**Comment by mattwoberts** [comment]
Aha - looks like the latest update here solves this

https://github.com/react-navigation/react-navigation/issues/7048
