### ISSUE TITLE
Bottom Tab Navigator Height Android

### ISSUE THREAD

**Issue by L-Yeiser** [react-navigation/react-navigation#9296]
**Current Behavior**
When consuming `useBottomTabBarHeight` on a Samsung Galaxy S8 / Galaxy Tablet / Pixel 3 XL the height is correct upon initial layout and then adjusts to subtract the back/home area.

My component is:
```
const Foo = () => {
  console.log('TAB BAR HEIGHT', useBottomTabBarHeight()
![Screen Shot 2021-02-08 at 11 10 23 AM](https://user-images.githubusercontent.com/6750498/107269299-411d9700-69fe-11eb-9ccd-b980f3dfab14.png)
)
  return null;
}
```

My logs are:
![Screen Shot 2021-02-08 at 11 22 54 AM](https://user-images.githubusercontent.com/6750498/107270596-ff8deb80-69ff-11eb-91ab-7f7e88ec3b56.png)

To hack around this issue I am using `useRef` to cache the initial value.

**How to reproduce**
Log the result of `useBottomtabBarHeight` on one of the Android devices listed above or any other device with the back/home area.

**Your Environment**

| software                      | version |
| ----------------------------- | ------- |
| iOS or Android                | Android
| @react-navigation/native      | 5.8.10
| @react-navigation/bottom-tabs | 5.11.2r
| react-native-screens          | 2.10.1
| react-native                  | 0.63

**Comment by ranka23** [comment]
I'm using version `5.11.9` and experiencing the same issue. The shared screenshot is pretty much what I'm logging. However, 97 (the initial value) is the wrong value and 49 is the right one in my case.

**Comment by gulsher7** [comment]
@ranka23 same things happing with me did you found any solution ? when i enable notch mode in android then bottomTabBarHeight return wrong height its working fine without notch device.

**Comment by L-Yeiser** [comment]
@gulsher7 we just wrap any component that needs to know the actual screen height in an `onLayout`. It is a bit of a hack but robust until this gets resolved.

**Comment by gulsher7** [comment]
@L-Yeiser can you please give me the example how can i do this ?

**Comment by ranka23** [comment]
@gulsher7 Here you go, as per @L-Yeiser suggestion:

```
// Typescript code!

import React, { useState } from "react"

const ProfileHeader: React.FC<ProfileHeaderProps> = () => {
  const [layoutHeight, setLayoutHeight] = useState<number>()

  const handleOnLayout = (e: LayoutChangeEvent) => {
    const { height } = e.nativeEvent.layout
    setLayoutHeight(height)
  }

  return (
    <View onLayout={handleOnLayout} style={styles.header}>
      {/* ... your component tree */}
    </View>
  )
}
```

You will get the layout height in the `layoutHeight` state when the component mounts.

**Comment by ser-emejia** [comment]
This still happen in real devices, in emulators works fine, any solutions?

**Comment by Steffi3rd** [comment]
I’m experiencing the same issue:

I tested on four different Android devices, and each one displays the main content at a different position when adjusting for bottomBarHeight.

I don’t think the problem is with bottomBarHeight, as it remains consistent across all devices. Instead, the issue seems to be with the parent container, but I’m unsure how to fix it.

![Image](https://github.com/user-attachments/assets/06186518-8445-4f05-83c5-85ad252944fd)
![Image](https://github.com/user-attachments/assets/a4279adb-1bb4-47f0-94ec-90fa3b0ab661)
![Image](https://github.com/user-attachments/assets/ea879228-f61f-4530-ae1a-47366916c114)
![Image](https://github.com/user-attachments/assets/3547b7a1-7f13-48a8-8bc2-cb7f4f902a6a)

**Comment by Steffi3rd** [comment]
Even when setting the tabBar to absolute with bottom: 0, it works correctly on one device—I can see my green background at the bottom.

However, on other devices, it doesn’t work as expected.
![Image](https://github.com/user-attachments/assets/59645cf2-f3a7-4645-b5f4-500a0200d0d5)
![Image](https://github.com/user-attachments/assets/6e8796e8-2192-4ce2-ae53-5f5ea379bac2)
![Image](https://github.com/user-attachments/assets/0032f6ad-d6a7-4f71-858e-2646f85e5527)
![Image](https://github.com/user-attachments/assets/88002634-b63e-47e5-b2f1-447ce23f0227)
