### ISSUE TITLE
Swipe gesture not opening Drawer Navigator

### ISSUE THREAD

**Issue by hcphoon01** [react-navigation/react-navigation#9302]
**Current Behavior**

I am running this code in a drawer.js file 
```
import React from 'react';
import { createDrawerNavigator } from '@react-navigation/drawer';
import { NavigationContainer } from '@react-navigation/native';

import HomeStack from './homeStack';
import AboutStack from './aboutStack';

const Drawer = createDrawerNavigator();

export const AppNavigator = () => (
    <NavigationContainer>
        <Drawer.Navigator initialRouteName='Home' screenOptions={{swipeEnabled: true}}>
            <Drawer.Screen
                name='Home'
                component={HomeStack}
            />
            <Drawer.Screen
                name='About'
                component={AboutStack}
            />
        </Drawer.Navigator>
    </NavigationContainer>
);

export default AppNavigator;
```
and that is used in my main App.js file like this 
```
import React from 'react';

import Navigator from './routes/drawer';

export default function App() {
    return (
        <Navigator />
    )
}
```

**Expected Behavior**

I am expecting to be able to swipe from the left of the screen to open my navigation drawer however this does not work. I know the drawer works as I have a button set up in my header that runs the `navigation.openDrawer()` method but the swipe gesture does not work.

I have tried the suggestion in [this comment](https://github.com/react-navigation/react-navigation/issues/7536#issuecomment-540667009) but that did not fix it

**How to reproduce**

I run the code on my android emulator and attempt a swipe with no success

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Android|
| @react-navigation/native       | 5.9.2|
| @react-navigation/drawer       |5.12.3|
| react-native-reanimated        |1.13.2|
| react-native-gesture-handler   |1.10.0|
| react-native-safe-area-context |3.1.9|
| react-native-screens           |2.17.1|
| react-native                   |0.63.4|
| expo                           |N/A|
| node                           |14.15.1|
| npm or yarn                    |6.14.8 - npm|

**Comment by deepakmehra96** [comment]
Same issue with 
```
 "@react-navigation/drawer": "^5.11.4",
    "@react-navigation/native": "^5.8.10",
    "@react-navigation/stack": "^5.12.8",
    "react": "17.0.1",
    "react-native": "0.63.4",
    
```
    android 10

**Comment by deepakmehra96** [comment]
It is not opening with swipe 
even if i open it using 

` navigation.openDrawer()`

it is not closing and the elements are not clickable inside the drawer

**Comment by sandipbiswasbehala** [comment]
Solution Found and Working in Android (by following https://docs.swmansion.com/react-native-gesture-handler/docs/#with-wixreact-native-navigation)

read android section ... Updating MainActivity.java and add 

For React Native 0.61 or greater, add the library as the first import in your index.js file:

import 'react-native-gesture-handler';

**Comment by deepakmehra96** [comment]
@sandipbiswasbehala  
i already tried this one but it is not working 

i used it like this 
`
import {AppRegistry} from 'react-native';
import App from './App';
import {name as appName} from './app.json';
import { gestureHandlerRootHOC } from 'react-native-gesture-handler'

AppRegistry.registerComponent(appName, () => gestureHandlerRootHOC(App));`

**Comment by sandipbiswasbehala** [comment]
did you update MainActivity.java ???

**Comment by sandipbiswasbehala** [comment]
@deepakmehra96  did you update MainActivity.java?? mandatory step. 

2nd step  

import 'react-native-gesture-handler';// on top
import {AppRegistry} from 'react-native';
import App from './App';
import {name as appName} from './app.json';
AppRegistry.registerComponent(appName, () => App);

And you will have to gradlew clean and rebuild.

I still working on my project right now. working fine.

**Comment by sandipbiswasbehala** [comment]
@deepakmehra96 
You will have to follow each steps carefully. or, wait for community to provide you ready made solution .  Read this url completely start to end each line

https://docs.swmansion.com/react-native-gesture-handler/docs/#with-wixreact-native-navigation

**Comment by sandipbiswasbehala** [comment]
reason to update java file...

React Native 0.60 migrated from Support Library to AndroidX. React Native Gesture Handler is not yet compatible with AndroidX.

**Comment by hcphoon01** [comment]
> Solution Found and Working in Android (by following https://docs.swmansion.com/react-native-gesture-handler/docs/#android)
> 
> read android section ... Updating MainActivity.java and add
> 
> For React Native 0.61 or greater, add the library as the first import in your index.js file:
> 
> import 'react-native-gesture-handler';

Legend, that fixed it!

**Comment by deepakmehra96** [comment]
Aaah now getting `compileDebugJavaWithJavac` issue while buidling 

i guess i need to do jetifier thing too for andriodX

but i was not expecting this to come from react-navigation

**Comment by deepakmehra96** [comment]
Fixed,  Thanks @sandipbiswasbehala

**Comment by akmal578** [comment]
> Solution Found and Working in Android (by following https://docs.swmansion.com/react-native-gesture-handler/docs/#android)
> 
> read android section ... Updating MainActivity.java and add
> 
> For React Native 0.61 or greater, add the library as the first import in your index.js file:
> 
> import 'react-native-gesture-handler';

Thanks finally fixed it, but why it removed from the original website docs ?

**Comment by thachsteven** [comment]
Not working :( 

> @deepakmehra96 You will have to follow each steps carefully. or, wait for community to provide you ready made solution . Read this url completely start to end each line
> 
> https://docs.swmansion.com/react-native-gesture-handler/docs/#android
> 
> For React Native 0.61 or greater, add the library as the first import in your index.js file:
> 
> Copy import 'react-native-gesture-handler';

**Comment by tarcisioandrade** [comment]
same problem, no solution?

**Comment by superyarik** [comment]
react navigation 4, Swipe gesture not opening Drawer Navigator on android.
gestureHandlerRootHOC used, first line import too, no effect

**Comment by ARSSHEIKH** [comment]
Stop debugger mode, it will work 😊
