### ISSUE TITLE
goBack doesn't reset the stack to load initial route when revisited

### ISSUE THREAD

**Issue by eyalyoli** [react-navigation/react-navigation#9310]
**Current Behavior**

I have a bottom tab navigation, and every tab holds a stack navigator.
Sometimes I need to navigate from screen1 in tab1 to screen2 in tab2 when screen2 is not the initial route (let's call it screen0) of tab2's stack.
I use the following code to navigate from screen1:
```javascript
navigation.navigate("tab2stack", {
  screen: "screen2",
})
```
This works fine! The problem happens in a specific case where the user never loads the tab2stack and navigates from screen1 to screen2. screen2 gets stuck from there on when loading tab2stack even when the user presses back on screen2.

**Expected Behavior**

tab2stack loads the initial route screen0 (as `goBack()` should've cleared all of tab2stack history)

**How to reproduce**

this is the [snack](https://snack.expo.io/QRzM0T7g4)
1. navigate from screen1 to screen2 using the button
2. press back using the button and return to screen1
3. press the tab2 (settings) and you'll get screen2 instead in initial screen0
**It is crucial** to not load the tab2 stack before step 1!

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | both
| @react-navigation/native       |  5.8.10
| @react-navigation/stack        | 5.12.8
| react-native-gesture-handler   | 1.7
| react-native-safe-area-context | 3.1.4
| react-native-screens           | 2.10
| react-native                   | 0.63.3
| expo                           | 39+40 (snack)
| npm or yarn                    | npm

**Comment by satya164** [comment]
https://reactnavigation.org/docs/nesting-navigators/#rendering-initial-route-defined-in-the-navigator
