### ISSUE TITLE
Is there an API for using react-navigation's code to parse my deep links manually?

### ISSUE THREAD

**Issue by technoplato** [react-navigation/react-navigation#9312]
Due to the way we are handling deep links that are behind authenticated routes, we are currently manually parsing deep links. Can you point me to the method(s) that are used by `react-navigation` internally that parse the deep link so I can use them for my authenticated routes when `react-navigation` does not handle them for me?

**Comment by satya164** [comment]
`getStateFromPath(pathWithoutPrefix, linkingConfig)` for parsing and `getPathFromState(navigationState, linkingConfig)` for converting to path.

**Comment by technoplato** [comment]
`useLinkTo` worked for us quite well
