### ISSUE TITLE
navigation.reset start again deep link if app use it before

### ISSUE THREAD

**Issue by Kornick** [react-navigation/react-navigation#9313]
**Current Behavior**

- navigation.reset({
  index: 0,
  routes: [{ name: 'Profile' }],
});

**Expected Behavior**

- if I do navigation.reset on android works correct, if iOS it started again deep link if I use it before
Expected that navigation.reset do not start deep link again

**How to reproduce**

start app with deep link and do immediately navigation.reset, after that you have endless loop. Reset start deep link again and it started navigation.reset ...

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |iOS14.3
| @react-navigation/native       |^5.9.2
| @react-navigation/stack        |^5.14.2
| react-native-gesture-handler   |^1.10.0
| react-native-safe-area-context |^3.1.9
| react-native-screens           |^2.17.1
| react-native                   |0.63.4
| node                           |15
| npm or yarn                    |npm

**Comment by Kornick** [comment]
I solve my question. I have a tree of navigation: drawer, tab and last stack.
If I do Tab.reset I have this issue
if I do drawer.reset I have success, because after this deep link is null.

**Comment by satya164** [comment]
Can you explain in more detail what's the issue and provide a repro?

**Comment by Kornick** [comment]
My structure of navigation:
drawer
    |__tab
          |__stack

i opening my app with deep link. Deep link opening stack screen and do analyzes params, after that i do navigation to next screen, but i do reset instead navigate. reset i do from tab navigation. And if do reset from tab deep link starting again.
If i do reset from drawer deep link do not start.

**Comment by satya164** [comment]
Closing due to no response
