### ISSUE TITLE
 com.facebook.react.uimanager.IllegalViewOperationException: Android (Tracked via crashlytics).  

### ISSUE THREAD

**Issue by ishandixit** [react-navigation/react-navigation#9314]
<img width="961" alt="Screenshot 2021-02-09 at 23 02 38" src="https://user-images.githubusercontent.com/34365458/107867664-b1b33080-6ea2-11eb-90a3-ca5d6119a09a.png">

Hi Team,

While using this @react-navigation/material-bottom-tabs library for bottom tabs, I am facing an above error. This above error is what we are facing only in Android OS. 

Below here is how i did the code:-

Packages Version:- 
"@react-navigation/material-bottom-tabs": "^5.2.6",
    "@react-navigation/native": "^5.7.0",

import { createMaterialBottomTabNavigator } from '@react-navigation/material-bottom-tabs';

const Tab = createMaterialBottomTabNavigator();

 <Tab.Navigator
        activeColor="#FA4832"
        inactiveColor="grey"
        barStyle={styles.botomSheet}
        indicator
        shifting={false}
        screenOptions={({ route }) => {
          return {
            tabBarIcon: ({ focused }) => {
              const icons = {
                HOME_ICON_BLACK: 'homeiconblack',
                DEALS_ICON_BLACK: 'dealsiconblack',
                PROFILE_ICON_BLACK: 'profileiconblack',
                REWARDS_ICON_BLACK: 'powericonblack',
                HOME_ICON_RED: 'homeiconred',
                DEALS_ICON_RED: 'dealsiconred',
                PROFILE_ICON_RED: 'profileiconred',
                REWARDS_ICON_RED: 'powerupred',
              };
              return (
                <SVGIcon
                  height={hp(20)}
                  iconName={icons[`${route.name.toUpperCase()}_ICON_${focused ? 'RED' : 'BLACK'}`]}
                />
              );
            },
          };
        }}>
        <Tab.Screen
          name="Home"
          component={Home}
          options={{
            tabBarLabel: 'Home',
          }}
          listeners={({ navigation }) => ({
            tabPress: () => {
              navigation.navigate('Home', {
                screen: 'Explore',
                params: {
                  giftHub: false,
                },
              });
            },
          })}
        />
        <Tab.Screen
          name="Deals"
          component={Deals}
          listeners={({ navigation }) => ({
            tabPress: () => {
              navigation.navigate('Deals', {
                screen: 'DealsHome',
                params: {
                  slotId: dealsSlotId,
                },
              });
            },
          })}
        />

        <Tab.Screen
          name="Rewards"
          component={RewardStack}
          options={{
            tabBarLabel: 'Rewards',
          }}
          listeners={({ navigation }) => ({
            tabPress: () => {
              navigation.navigate('Rewards');
            },
          })}
        />
        <Tab.Screen
          name="Profile"
          component={ProfileStack}
          options={{
            tabBarLabel: 'Profile',
          }}
          listeners={({ navigation }) => ({
            tabPress: () => {
              navigation.navigate('Profile');
            },
          })}
        />
      </Tab.Navigator>

**Comment by ishandixit** [comment]
"@react-navigation/material-bottom-tabs": "^5.2.6",
    "@react-navigation/native": "^5.7.0",

**Comment by ishandixit** [comment]
Yes this issue still exists with the latest versions as well.

**Comment by ishandixit** [comment]
Hey team, we tried with the approach provided by you guys to upgrade @react-navigation/native & @react-navigation/material-bottom-tabs but our app is lagging. Is there is any other solution/suggestions you could provide so that we would quickly fix this issue, as this is something really impacting our app as well as the user base.

**Comment by spsaucier-bakkt** [comment]
We've been seeing this issue for a long time too. 

Versions:
```
    "@react-navigation/bottom-tabs": "^5.11.2",
    "@react-navigation/material-top-tabs": "^5.3.10",
    "@react-navigation/native": "^5.8.10",
    "@react-navigation/stack": "^5.12.8",
```

**Comment by spsaucier-bakkt** [comment]
I'm not sure how to repro; otherwise we'd probably be able to work around it.
I do know it's our top crash on Android and has been for several months.

**Comment by spsaucier-bakkt** [comment]
Another trace (from Sentry this time)
```
com.facebook.react.uimanager.IllegalViewOperationException: Unable to execute operation dispatchViewManagerCommand on view with tag: 16395, since the view does not exists
    at com.facebook.react.uimanager.UIImplementation.assertViewExists(UIImplementation.java:830)
    at com.facebook.react.uimanager.UIImplementation.dispatchViewManagerCommand(UIImplementation.java:713)
    at com.facebook.react.uimanager.UIManagerModule.dispatchCommand(UIManagerModule.java:707)
    at com.facebook.react.uimanager.UIManagerModule.dispatchViewManagerCommand(UIManagerModule.java:694)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
    at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
    at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
    at android.os.Handler.handleCallback(Handler.java:789)
    at android.os.Handler.dispatchMessage(Handler.java:98)
    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
    at android.os.Looper.loop(Looper.java:164)
    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
    at java.lang.Thread.run(Thread.java:764)
```

**Comment by ishandixit** [comment]
On the basis Of assumptions this occurs when we used mentioned npm module
for bottom tab navigation. And this yes this stack trace is what we used to
get always. Is there any work around to this issue ?
