### ISSUE TITLE
Undefined parameters when passing to routes

### ISSUE THREAD

**Issue by Nathanotal** [react-navigation/react-navigation#9316]
**Current Behavior**

- What code are you running and what is happening?

This is my current code. A function takes a parameter n (navigation), gets two variables from AsyncStorage. It is then supposed to navigate to "LoggingIn" with parameters navig (navigation) and cred (c). All values are defined in this function. 

(In file: "LoginSkarm.js")
```
async function checkCredentials(n) {
    await AsyncStorage.multiGet(["email", "pass"]).then((result) => {
      const email = result[0][1];
      const pass = result[1][1];
      const c = { email, pass };
      if (email && pass) {
        n.navigate("LoggingIn", {
          navig: n,
          cred: c,
        });
      }
    });
}
```

This is part of my LoggingIn:

(In file: "LogginIn.js")
```
function LogginIn({ navig, cred }) {
  let a = true;
  if (!navig || !cred) {
    console.log("Undefined credentials:", navig, cred);
    a = false;
  }
  return (
    <SafeAreaView>
      <Text style={styles.rubrik}>Logging in...</Text>
      {a && <Knapp namn="Logging in..." onPress={logga(navig, cred)}></Knapp>}
    </SafeAreaView>
  );
}
```
I know the code is not terriffic but it should work. The console.log() always returns "Undefined credentials: undefined undefined". Why are navig and cred undefined?

**Expected Behavior**
I would expect the parameters to get passed. It seems correct when looking at the documentation at: https://reactnavigation.org/docs/params/

**How to reproduce**
Repo: https://github.com/Nathanotal/NAWPlanner
(Just noticed i have both npm and yarn lol)

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                | both 
| @react-navigation/native       | 5.9.2
| @react-navigation/stack        | 5.14.2
| react-native-gesture-handler  | 1.8.0 
| react-native-safe-area-context  | 3.1.9
| react-native-screens           | 2.17.1
| react-native                   | 0.63.2
| expo                           | 40.0.0
| node                           | 14.15.3
| npm or yarn                    | npm

**Comment by Nathanotal** [comment]
I upgraded the packages and the issue till persists!

**Comment by Nathanotal** [comment]
> 
> 
> The versions mentioned in the issue for the following packages differ from the latest versions on npm:
> 
>     * `@react-navigation/native` (found: `5.8.10`, latest: `5.9.2`)
> 
>     * `@react-navigation/stack` (found: `5.12.8`, latest: `5.14.2`)
> 
> 
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?

Verified

**Comment by bigcupcoffee** [comment]
You're trying to get the params from screen props instead of getting it from `props.route.params`.

You generally seem to be doing bad react and react-navigation practices, better take a look at both docs once again
