### ISSUE TITLE
ReactNavigation V5 for Web Babel and Webpack

### ISSUE THREAD

**Issue by tyrauber** [react-navigation/react-navigation#9317]
**Current Behavior**

Both babel and webpack are required to compile and use react-navigation for web.  react-navigation cannot be used as es6 with babel alone, unlike react, react-native, react-native-web or react-dom, which can be required as a constant in a commonjs script, or imported in an es6 module.

Running an es6 with react-navigation imported results in the following error:

```
node_modules/react-native/index.js:13
import typeof AccessibilityInfo from './Libraries/Components/AccessibilityInfo/AccessibilityInfo';
...
node_modules/@react-navigation/native/lib/commonjs/useBackButton.tsx:2:1)
```

**Expected Behavior**

The optimum behavior is to be able to import react-navigation in a es6 module and run it with limited compilation.

Using nodemon with babel-node would allow you to compile just your code, and not external modules in development, speeding up development without requiring a webpack build step.

`nodemon --exec babel-node index.js`

**How to reproduce**

I have created the repo, [babel-react-navigation](https://github.com/tyrauber/babel-react-navigation), to demonstrate this issue. It includes the required babel and webpack configuration, to use react-navigation on the web, and demonstrates the babel only error.

Any advice on how to optimize the development environment with as limited dependencies and compilation time would be greatly appreciated.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| @react-navigation/native       | ^5.9.2
| react-native                   | 40.0.1
| expo                           | 40.0.0
| node                           | 14.0.0
| yarn                    | 1.19.1

**Comment by satya164** [comment]
As you can see in the error message, the syntax error is from the `react-native` package, not anything in React Navigation.

Also if you're running it with node/web, you need to alias `react-native` to `react-native-web`.

**Comment by tyrauber** [comment]
Hi @satya164, thank you for the reply. As you can see in the repo provided, I am aliasing `react-native` to `react-native-web` through my [babel.config.js](https://github.com/tyrauber/babel-react-navigation/blob/main/babel.config.js).    But as you can see from the error, [useBackButton.tsx:2](https://github.com/react-navigation/react-navigation/blob/main/packages/native/src/useBackButton.tsx#L2) is is calling `react-native` as well.  Is it possible that reactive-navigation is ignoring the alias and calling `react-native` instead of `react-native-web`?

**Comment by satya164** [comment]
React Navigation cannot ignore the alias. If your alias isn't working, then there's some kind of configuration issue that you need to debug. Maybe your babel config is not being used, or maybe the dollar sign is causing issues.

**Comment by tyrauber** [comment]
Hi @satya164, I believe the alias is working properly as demonstrated in example repo.  

The demonstration now includes [basic server side rendering in koa](https://github.com/tyrauber/babel-react-navigation/blob/main/index.js#L15-L28) using both [react-native-web components](https://github.com/tyrauber/babel-react-navigation/blob/main/App.js) and [react-navigation components](https://github.com/tyrauber/babel-react-navigation/blob/main/AppNav.js).

The react-native-web components render without error.

```
import React from "react";
import { View, Text, Button } from "react-native";

export default function App() {
  return (
    <View style={{ flex: 1, justifyContent: "center", alignItems: "center" }}>
      <Text>Hello World</Text>
    </View>
  );
}
```

As you can [see here](https://github.com/tyrauber/babel-react-navigation/blob/main/App.js#L2), the import calls react-native, yet is importing the [View and Text](https://github.com/tyrauber/babel-react-navigation/blob/main/App.js#L6-L8) react-native-web components without issue.  Running the the server with `$ yarn dev` renders "Hello World" in the browser.

If [you remove the module-resolver alias for react-native](https://github.com/tyrauber/babel-react-navigation/blob/main/babel.config.js#L5-L12), and run the server again, the App no longer works, and in fact raises the same error, demonstrating that the alias is in fact functioning properly for the react-native(-web) import in App.js.

With the babel alias in place, I would expect @react-navigation/native components to function the same. Yet,  if I try to import [NavigationContainer from @react-navigation/native](https://github.com/tyrauber/babel-react-navigation/blob/main/AppNav.js#L3), it raises the error. 

This is what led me to believe the react-native import in [useBackButton.tsx:2](https://github.com/react-navigation/react-navigation/blob/main/packages/native/src/useBackButton.tsx#L2) is the culprit, not the babel configuration.

But perhaps it is my error.  I appreciate your time and consideration.

**Comment by satya164** [comment]
> Hi @satya164, I believe the alias is working properly as demonstrated in example repo.

If it was working correctly, then you wouldn't have an error. Try installing more react-native libraries other than react navigation and it's likely that you'll have the same issue.

Seems like your babel alias isn't applied to node_modules.

**Comment by tyrauber** [comment]
Ah, that's it! [Babel ignores node_modules by default](https://babeljs.io/docs/en/babel-node#options). Damn.

Passing an empty array to ignore, overrides the default from the command line.

```$ babel-node --ignore "[]" ./index.js```

Or better yet, explicitly not ignoring @react-navigation:

```babel-node --ignore '/node_modules/(?!@react-navigation)' index.js```

I'd love to disable ignoring node_modules in the babel config file, but that doesn't seem to be possible. It's easy enough to modify the package script to include it though.

```
   "dev": "nodemon index.js --exec \"babel-node --ignore '/node_modules/(?!@react-navigation)'\"",
```

Thanks @satya164 for all your help.
