### ISSUE TITLE
Massive header on android only

### ISSUE THREAD

**Issue by timurridjanovic** [react-navigation/react-navigation#9327]
**Current Behavior**
The header is ginormous on android (only on android):
![image](https://user-images.githubusercontent.com/1295621/108025588-bbe54400-6ff4-11eb-8f1b-9f6b53c304c1.png)

Current Code (I actually commented out my custom header just to show that even the default header is still massive:
```
const CompagnonStack = createNativeStackNavigator()
const headerOptions = props => {
  const { navigation, route: { name, params } } = props
  const options = screenOptions[name] || {}
  return {
    // headerLeft: () => <NavBar options={options} navigation={navigation} params={params} />,
    // headerTransparent: true,
    // headerStyle: { backgroundColor: 'blue' },
    // headerTitle: null,
  }
}
function CompagnonStackScreen () {
  return (
    <CompagnonStack.Navigator>
      <CompagnonStack.Screen name='Compagnon' component={Compagnon} options={headerOptions} />
      <CompagnonStack.Screen name='Refuge' component={Refuge} options={headerOptions} />
      <CompagnonStack.Screen name='RefugeNiche' component={RefugeNiche} options={headerOptions} />
      <CompagnonStack.Screen name='UserProfile' component={UserProfile} options={headerOptions} />
    </CompagnonStack.Navigator>
  )
}
```

**Your Environment**
Mac OS 10.15.7

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |
| @react-navigation/native       | ^5.6.1
| @react-navigation/stack        | ^5.6.2
| react-native-gesture-handler   | ^1.6.1
| react-native-safe-area-context | ^0.6.4
| react-native-screens           | ^2.0.0-alpha.32
| react-native                   | 0.61.4
| expo                           | not using expo
| node                           | v10.14.0
| npm or yarn                    | 6.4.1

**Comment by timurridjanovic** [comment]
I updated both packages and the issue is still there.

**Comment by taylorpringle** [comment]
I am also having the same issue and changing the height in screenOptions does nothing.

**Comment by taylorpringle** [comment]
@timurridjanovic I found the issue was with createNativeStackNavigator(). I changed it to createStackNavigator() and the height went to normal size.

**Comment by timurridjanovic** [comment]
mmm.. I was kind of hoping I could keep using react native screens and createNativeStackNavigator. Perhaps then I should bring this issue over to react native screens. Thanks!

**Comment by UADACID** [comment]
you can set` headerTopInsetEnabled: false` for normal height of header @timurridjanovic

**Comment by swizes** [comment]
![image](https://user-images.githubusercontent.com/8876645/115516686-0dc57700-a28f-11eb-85de-d9a5a9ea28d1.png)

I face the same issue and I am using createStackNavigator

**Comment by raajnadar** [comment]
It seems like you have 2 safe area views

**Comment by Mahmoudkhoder01** [comment]
> ![image](https://user-images.githubusercontent.com/8876645/115516686-0dc57700-a28f-11eb-85de-d9a5a9ea28d1.png)
> 
> I face the same issue and I am using createStackNavigator

Hello, did u fix it? I'm facing same problem
