### ISSUE TITLE
No ability to specify multiple paths for same screen.

### ISSUE THREAD

**Issue by jayshah123** [react-navigation/react-navigation#9328]
**Current Behavior**

Not able to specify multiple paths for a given screen e.g. `/user` and `/me` should both open the same screen i.e. Profile.

```
import { NavigationContainer } from '@react-navigation/native';

const config = {
  screens: {
    Chat: 'feed/:sort',
    Profile: ['user', 'me'],
  },
};

const linking = {
  prefixes: ['https://mychat.com', 'mychat://'],
  config,
};
```

**Expected Behavior**

Ability to specify multiple paths for a screen.

**How to reproduce**

Try launching app with given config.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |Both
| @react-navigation/native       |5.9.2
| react-native                   |0.63.2
| expo                           |NA
| node                           |10
| npm or yarn                    |6

**Comment by Hamawis** [comment]
@jayshah123 you can specify same screen twice with different paths. Here's the code to support multiple paths.
`const config = {
  screens: {
    Chat: 'feed/:sort',
    Profile: 'user',
   Profile: 'me'
  },
};`

**Comment by francescov1** [comment]
Was looking for something similar, ended up figuring out another workaround that doesn't require duplicating the screen using `getStateFromPath`:

```
import { NavigationContainer, getStateFromPath } from '@react-navigation/native';

const config = {
  screens: {
    Chat: 'feed/:sort',
    Profile: 'user'
  },
};

const linking = {
  prefixes: ['https://mychat.com', 'mychat://'],
  config,
  getStateFromPath: (path, options) => {
    const newPath = path === '/me' ? '/user' : path;
    return getStateFromPath(newPath, options);
  },
};
```

This essentially replaces the `/me` path with `/user` and then calls the default getStateFromPath function, which uses your screen config. Haven't tested super thoroughly but seems to work well for me so far!

**Comment by fcandi** [comment]
> Was looking for something similar, ended up figuring out another workaround that doesn't require duplicating the screen using `getStateFromPath`:

...

> This essentially replaces the `/me` path with `/user` and then calls the default getStateFromPath function, which uses your screen config. Haven't tested super thoroughly but seems to work well for me so far!

Thx @francescov1 this is a nice workaround for now :)

**Comment by ShubhamBathe-KM** [comment]
> @jayshah123 Its a hack but i fixed it by specifying same screen twice with different names. Here's the code to support multiple paths. ` <Stack.Screen name="Profile" component={ProfileComponent}/>
> 
> <Stack.Screen name="ProfileTwo" component={ProfileComponent}/>
> 
> const config = { screens: { Chat: 'feed/:sort', Profile: 'user', ProfileTwo: 'me' }, };`

@jayshah123 It dosen't seem to work. This is the error that I got if I tried to add 2 screens with same component
![Simulator Screen Shot - iPhone 12 - 2022-02-07 at 13 45 48](https://user-images.githubusercontent.com/67695272/152750638-4e369f79-809f-409f-b934-61d58480b90d.png)
.

**Comment by uuouter** [comment]
Also in need of multiple deep links to 1 component, in my case, HomeComponent takes care of most of the deep links (i.e. triggering modals).

i.e.
viewprofile/:uid
viewchallenge/:hash

both deep links need to be routed to Home.

Wasn't sure how to handle route parameters in the workaround provided by @francescov1 
My knowledge of react-navigation is very limited but got firebase dynamic links working so I guess I'm an expert! :p 

I went for a different approach using proxy components, not ideal at all... but hey it works!

```
config: {
            screens: {
                ViewProfileDeepLinkProxy: 'viewprofile/:uid',
                EmailLogin: '__/auth',
                ViewChallengeDeepLinkProxy: 'mychallenge/:hash'
            },
        },
```

```
export default function ViewProfileDeepLinkProxy({navigation, route}) {
    useEffect(() => {
        navigation.navigate('Home', {
            deepLink: true,
            uid: route.params.uid,
            path: route.path
        })
    }, [route]);

    return (
        <></>
    )
}
```

And in my Home Component

```
useEffect(() => {
        if(route?.params?.path) {
            switch(true) {
                case route.params.path.startsWith('viewprofile'):
                    showProfile(route.params.uid);
                    break;
                case route.params.path.startsWith('viewchallenge'):
                    console.debug('View Challenge deeplink from route.params.path', route);
                    break;
            }
        }
    }, [route]);
```

Again, maybe this can be done way easier with getStateFromPath but perhaps it helps you from a blocker.

W

**Comment by raajnadar** [comment]
> > @jayshah123 Its a hack but i fixed it by specifying same screen twice with different names. Here's the code to support multiple paths. ` <Stack.Screen name="Profile" component={ProfileComponent}/>
> > 
> > <Stack.Screen name="ProfileTwo" component={ProfileComponent}/>
> > 
> > const config = { screens: { Chat: 'feed/:sort', Profile: 'user', ProfileTwo: 'me' }, };`
> 
> @jayshah123 It dosen't seem to work. This is the error that I got if I tried to add 2 screens with same component
> ![Simulator Screen Shot - iPhone 12 - 2022-02-07 at 13 45 48](https://user-images.githubusercontent.com/67695272/152750638-4e369f79-809f-409f-b934-61d58480b90d.png)
> .

The error will show up only when there are same names, you can have same component return.

**Comment by ShubhamBathe-KM** [comment]
This one is fixed after changing component screen.

**Comment by myrs** [comment]
@francescov1 [solutions](https://github.com/react-navigation/react-navigation/issues/9328#issuecomment-905706019) for deep linking with multiple paths to the same screen works perfectly for me! 

As I needed to handle route params, my modification looks the following way:
```
import { NavigationContainer, getStateFromPath } from '@react-navigation/native';

const config = {
  screens: {
    Chat: 'feed/:sort',
    Profile: 'user'
  },
};

const linking = {
  prefixes: ['https://mychat.com', 'mychat://'],
  config,
  getStateFromPath: (path, options) => {
    // replace the "main" part of the route, keeping the "params" part intact
    if (path.includes('me')) {
      path = path.replace('me', 'user');
    }
    return getStateFromPath(path, options);
  },
};
```

**Comment by hbomatt** [comment]
@myrs Yup, I'm doing the same thing 👍🏻

**Comment by wagneer-nascimento** [comment]
No meu caso eu estava procurando como entrar em uma Screen com dois paths diferentes.
Solutions 

 const configScheenDetalheConteudos: any = {
    screens: {
      Detalhe: {
        path: 'detalhe/estabelecimentos/conteudos/:id',
        parse: {
          id: (id: string) => id
        },
      },
    }
  }

return (
    <NavigationContainer linking={{
      prefixes: ['teste://', 'https://teste/'],
      config: {
        screens: {
          Detalhe: {
            path: 'detalhe/estabelecimentos/:id',
            parse: {
              id: (id: string) => id
            },
          },
        }
      },
      getStateFromPath: (path, options) => {
        let conteudo: boolean = path.includes('conteudos');
        return getStateFromPath(path, conteudo ? configScheenDetalheConteudos : options);
      },

    }}>
      <Provider>
        <Routes />
      </Provider>
    </NavigationContainer>
  )
  
  Basicamente criei duas configurações para uma Screen especifica e faço o update conforme o link que o user click
