### ISSUE TITLE
Not able to read params on target page when using dispatch.CommonActions.reset() or resetRoot() on stackNavigator

### ISSUE THREAD

**Issue by ivanpagac** [react-navigation/react-navigation#9333]
**Current Behavior**
I took a ref of the NavigationContainer with nested Stack with Screen1(initial),Screen2,Screen3.

I can reset my stack, but I am unable to pass parameters to the screen .

navigation.dispatch(CommonActions.reset({index:0, routes:[{name:Screen3, params:{p1:1}}]}))
navigation.resetRoot({index:0, routes:[{name:Screen3, params:{p1:1}}]})

when trying to get params in connect(mapStateToProps,mapDispatchToProps)(Screen3) props.navigation.route.params are undefined 

**Expected Behavior**

params present

we were using v3 and this worked with no problem

**How to reproduce**

- You must provide a way to reproduce the problem. If you are having an issue with your machine or build tools, the issue belongs on another repository as that is outside of the scope of React Navigation.
- Either re-create the bug on [Snack](https://snack.expo.io) or link to a GitHub repository with code that reproduces the bug.
- Explain how to run the example app and any steps that we need to take to reproduce the issue from the example app.
- Keep the repro code as simple as possible, with the minimum amount of code required to repro the issue.
- Before reporting an issue, make sure you are on latest version of the package.

**Your Environment**

| RN                       | v |
| ------------------------------ | ------- |
| iOS or Android                 | both
| @react-navigation/native       | 5.9.2
| @react-navigation/stack        | 5.14.2
| react-native-gesture-handler   | 1.10.1
| react-native-safe-area-context | 3.1.9
| react-native-screens           | 2.17.1
| react-native                   | 0.63
| expo                           |
| node                           |
| npm or yarn                    | npm

**Comment by ivanpagac** [comment]
remove pls

**Comment by alexander126** [comment]
@ivanpagac how did you manage to solve this?
