### ISSUE TITLE
Can't get stack screen to full width.

### ISSUE THREAD

**Issue by hazelf42** [react-navigation/react-navigation#9339]
**Current Behavior**
`
 <NavigationContainer>
 
      <Stack.Navigator initialRouteName="Auth">
        <Stack.Screen
          name="Auth"
          component={Auth}
          options={{
            title: "Authenticate",
          }}
        />
      </Stack.Navigator>

    </NavigationContainer>`
![image](https://user-images.githubusercontent.com/30422151/108431402-aab85500-71f7-11eb-9bf0-c5e610a92c9a.png)
![image](https://user-images.githubusercontent.com/30422151/108431433-b86dda80-71f7-11eb-9167-049735cba925.png)

Results in the screen (with the normal flex 1 width 100% etc styling) to be as wide as the header. 

**Expected Behavior**

Normal full-width stack screens. 

    "@react-navigation/native": "^5.9.2",

**Comment by rawatnaresh** [comment]
make sure you have set `flex:1` to your parent wrapper. also, it would be easier to help  if you could reproduce your issue using [Snack](https://snack.expo.io/)

**Comment by hyunnaye** [comment]
how was this fixed?

**Comment by AudreyKj** [comment]
@hazelf42, @hyunnaye: we fixed it by removing `<SafeAreaView>` that was wrapping our `<NavigationContainer>`

**Comment by Adushar** [comment]
Just remove the outer `<View>` or `<SafeAreaView>` of the `<NavigationContainer>`. It works for me
