### ISSUE TITLE
React Navigation Bottom Tabs Working as stack on back press should exit app from inital route

### ISSUE THREAD

**Issue by Vanns35** [react-navigation/react-navigation#9340]
**Current Behavior**  

TabNavigation
```
<Tabs.Navigator
      backBehaviour="initialRoute"
      tabBar={(props) => <BottomTabBar {...props} />}>
      <Tabs.Screen name="Screen1" component={Screen1} />
      <Tabs.Screen name="Screen2" component={Screen2} />
      <Tabs.Screen name="Screen3" component={Screen3} />
      <Tabs.Screen name="Screen4" component={Screen4} />
      <Tabs.Screen name="Screen5" component={Screen5} />
    </Tabs.Navigator>
```

Main Navigation
```
     <NavigationContainer>
        <AppStack.Navigator>
          <AppStack.Screen name="TabNavigator" component={TabNavigator} />
        </AppStack.Navigator>
      </NavigationContainer>
```

After Opening App, Bottom Tabs are displaying. When I go through all tabs and then I press the back button it navigates from all previous screens even if I am on the initial screen that is screen1.  

**Expected Behavior**

If we go through all tabs and when we press back if we are on screen1 then the app should exit instead of again going back to another tab.

**How to reproduce**

- Open an app
- Click on Screen2 then screen3 again screen 1 then screen4, then screen 5, and last screen 1.
- Press the back button now instead of app exit we are going back to screen 5.

**Your Environment**

| software                                      | version |
| ------------------------------------------ | ---------- |
| @react-navigation/native            | ^5.9.2
| @react-navigation/bottom-tabs  | ^5.11.7
| react-native-screens                   | ^2.15.2
| react-native                                 | 0.63.4
| node                                            | v14.15.1
| npm or yarn                                 | 1.22.5

**Comment by bigcupcoffee** [comment]
You've got a typo in your code(backBehavio~~u~~r, `u` is extra). It works fine @Vanns35

**Comment by Vanns35** [comment]
yes.. backBehavior="initialRoute" is working..
