### ISSUE TITLE
Clean builds on iOS fail due to outdated peer dependency on masked-view

### ISSUE THREAD

**Issue by markwilcox** [react-navigation/react-navigation#9341]
**Current Behavior**

The native module in the masked-view peer dependency fails to build from clean on iOS because of an Xcode 12 issue where native modules now have to declare a dependency on React-Core rather than React. This was fixed in masked-view months ago, but we can't pull in the fixed version because the package has been renamed (moved to a new org/scope) and the stack navigator is still using the old name here: https://github.com/react-navigation/react-navigation/blob/860adbfd8b4c493dc3e28c99ad5d78699c2f8797/packages/stack/package.json#L63
and here:
https://github.com/react-navigation/react-navigation/blob/860adbfd8b4c493dc3e28c99ad5d78699c2f8797/packages/stack/src/views/MaskedViewNative.tsx#L18

The error we get is:
▸ Linking RNCMaskedView
❌  Undefined symbols for architecture x86_64
> Symbol: _OBJC_CLASS_$_RCTViewManager
> Referenced from: _OBJC_CLASS_$_RNCMaskedViewManager in RNCMaskedViewManager.o

If we remove the masked-view module (it's supposed to be optional) the static bundle creation fails:
yarn run v1.22.10
$ react-native bundle --entry-file index.js --bundle-output main.jsbundle
                 Welcome to React Native!
                Learn once, write anywhere
error Unable to resolve module `@react-native-community/masked-view` from `node_modules/@react-navigation/stack/src/views/MaskedViewNative.tsx`: @react-native-community/masked-view could not be found within the project.

So that "optional" part doesn't work either.

**Expected Behavior**

The peer dependency and module used for react-navigation needs to be updated to @react-native-masked-view/masked-view which has already fixed the React -> React-Core pod dependency issue.

**How to reproduce**

This error will not occur on all projects because it is related to build order on iOS, but it's a well known and already fixed issue on a dependency that has not been adopted by react-navigation. It's only an issue for clean builds but this obviously breaks CI pipelines that always build from clean.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS                | 12-14
| @react-navigation/native       | 5.9.2
| @react-navigation/stack        | 5.14.2
| react-native-gesture-handler   | 1.10.0
| react-native-safe-area-context | 3.1.9
| react-native-screens           | 2.17.1
| react-native                   | 0.63.4
| expo                           | n/a
| node                           | reproduces on 10, 12 and 14
| npm or yarn                    | yarn

**Comment by satya164** [comment]
Optional requires only supported in [latest React Native CLI (4.14)](https://github.com/react-native-community/cli#updating-the-cli).

Changing package name is a breaking change so it will be changed in next major version. For now you can use `patch-package` to use change the package name or update your CLI to make it optional.
