### ISSUE TITLE
Stack.Screen props getId is called twice

### ISSUE THREAD

**Issue by Daavidaviid** [react-navigation/react-navigation#9343]
**Current Behavior**

- What code are you running and what is happening?

I have a `Stack.Navigator` with screens inside, when i try to use getId, the getId callback is called twice in a row.
```javascript
<Stack.Screen
  getId={({ params }) => {
    console.log({ params });
    return params?.userId;
  }}
  name={'UserAchievements'}
  component={UserAchievements}
  />
```

This will print this after I call navigate or push to `UserAchievements` screen (only once, I checked) : 
```bash
> {"params": {"userId": "SQZ5MB9y1qg0OwnTrpFeIyAJ8Hn2"}}
> {"params": undefined}
```

**Expected Behavior**

It should not be called twice and with undefined value the second time.

I don't know if it's a bug or an error from my part.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |
| @react-navigation/native       | ^5.9.2
| @react-navigation/stack        | ^5.14.2
| react-native-gesture-handler   | ^1.10.1
| react-native-safe-area-context | ^3.1.9
| react-native-screens           | ^2.17.1
| react-native                   | ^0.63.4
| expo                           |
| node                           |
| npm or yarn                    | yarn

**Comment by divyanaimisha** [comment]
This is still happening
