### ISSUE TITLE
Content in React Native Web ScrollView overflows preventing sticky header/footer usage after upgrading from 5.0 to 5.8.1

### ISSUE THREAD

**Issue by wonathanjong** [react-navigation/react-navigation#9344]
**Current Behavior**

- What code are you running and what is happening?
I'm using the Stack.Navigator and Stack.Screens to implement a web screen with a sticky footer and header that has scrollable content in-between. 

This is the layout of the component that is being used as aa Stack.Screen.
<img width="127" alt="Screen Shot 2021-02-19 at 5 43 13 PM" src="https://user-images.githubusercontent.com/16651313/108576328-6e115a00-72da-11eb-9ae1-d4963358326e.png">

After I upgraded from
 "@react-navigation/native": "^5.0.0",
 "@react-navigation/stack": "^5.0.0",
to
 "@react-navigation/native": "^5.8.10",
 "@react-navigation/stack": "^5.12.8"

I found that the content in my ScrollView on web overflowed and made the header and footer no longer sticky and just part of one whole view that could be scrolled.

Before upgrade: 

https://user-images.githubusercontent.com/16651313/108576818-360b1680-72dc-11eb-8850-0e18bc633079.mp4

After upgrade:

https://user-images.githubusercontent.com/16651313/108576823-3b686100-72dc-11eb-8b07-dc7d02ada809.mov

**Expected Behavior**

I expect that content in a scrollview won't expand and will stay within the confines of the view allowing footers and headers to be stick rather than scrollable due to overflow.

**How to reproduce**

Here it is:
https://snack.expo.io/QCY0SjHQ0

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| Web                |
| @react-navigation/native       | 5.8.1 |
| @react-navigation/stack        | 5.12.8 |
| react-native-gesture-handler   | 1.7.0 |
| react-native-safe-area-context | 3.1.4 |
| react-native-screens           | 2.10.1 |
| react-native                   | 39.0.3 |
| expo                           | 39.0.0 |
| node                           | 12.16.2 |
| npm                    | 6.14.4 |

**Comment by satya164** [comment]
It's by design. Unlike apps, browsers on mobile have limited vertical space due to the browser's UI bar also being present. Preventing scroll on whole page also prevents the browser's UI from collpasing which provides a worse UX.

If you want to explictly override the behavior, then specify `cardStyle: { flex: 1 }` for your root stack.

**Comment by xn3cr0nx** [comment]
Hello @satya164, trying to achieve something similar on the web, but using a **global** header/footer. The issue discussed also in [other issues](https://github.com/react-navigation/react-navigation/issues/4771) is still tricky to date. Is there a way to obtain a sticky footer alongside the navigator? 

Nothing like the following works, the footer position is not relative to the stack but always to the screen, so the result is the footer is always visible in the bottom of the screen.

```jsx
<View style={{ flex: 1}}>
    <Navbar />
    <Stack.Navigator screenOptions={{ headerShown: false }}>
	<Stack.Screen name={"page1"} component={Page1} />
	<Stack.Screen name={"page2"} component={Page2} />
    </Stack.Navigator>
    <Footer />
</View>
```

Suggestions?
