### ISSUE TITLE
Custom header mounted twice on iOS

### ISSUE THREAD

**Issue by pors** [react-navigation/react-navigation#9345]
**Current Behavior**

When specifying a custom header in a `Stack.Navigator`, the custom header is mounted twice on top of each other in iOS. On web and Android this is not the case.

[iOS double custom header](https://snack.expo.io/@pors/ios-double-custom-header) (Snack) => On iOS when navigating to "details" and back you see a double shadow appear and disappear.

[iOS headerShown false ignored](https://snack.expo.io/@pors/ios-headershown-false-ignored) (Snack) => When setting `headerShown` to `false` for the second screen, this is ignored on iOS.

**Expected Behavior**

The behavior on Android/web is the expected behavior.

**How to reproduce**

See Snacks

**Your Environment**

See Snacks

**Comment by satya164** [comment]
https://reactnavigation.org/docs/stack-navigator#set-headermode-to-screen

**Comment by pors** [comment]
Thanks @satya164, I missed that!
