### ISSUE TITLE
Can't set CustomActionCreator to open, close or trigger 2nd Drawer because createDrawerNavigator doesn't take arguments.

### ISSUE THREAD

**Issue by nicely** [react-navigation/react-navigation#9347]
Trying to set custom REF to open my 2nd Drawer with getCustomActionCreators... But it seems like **createDrawerNavigator** doesn't take any argument at V5... Is there any other way to do it in the latest version, Do I need to downgrade to the old version to overcome?

```
    "@react-navigation/drawer": "^5.12.3",
    "@react-navigation/material-bottom-tabs": "^5.3.13",
    "@react-navigation/native": "^5.9.2",
```

```
const Tab = createDrawerNavigator(
  {
    inbox: Inbox,
  },
  {
    getCustomActionCreators: (route, stateKey) => {
      return {
        toggleRightDrawer: () => DrawerActions.toggleDrawer({ key: stateKey }),
      };
    },
  }
);
```

By the way, I also tried **createMaterialBottomTabNavigator()** but can't be solved the issue. any thoughts?

**Comment by satya164** [comment]
It's not supported in v5. You can achieve similar functionality with `dispatch`: https://reactnavigation.org/docs/navigation-prop/#custom-action-creators
