### ISSUE TITLE
documentation incorrect

### ISSUE THREAD

**Issue by krisbaum74** [react-navigation/react-navigation#9351]
https://reactnavigation.org/docs/bottom-tab-navigator 

import MaterialCommunityIcons from 'react-native-vector-icons/MaterialCommunityIcons';

should be 

import Icon from 'react-native-vector-icons/MaterialCommunityIcons';

**Comment by satya164** [comment]
Name of the default import doesn't matter

**Comment by krisbaum74** [comment]
> Name of the default import doesn't matter

it does in this instance.
