### ISSUE TITLE
How to keep using react navigation 4?

### ISSUE THREAD

**Issue by nickjuntilla** [react-navigation/react-navigation#9353]
**Current Behavior**

I'm trying to upgrade my app just to get it working again, but I don't have time to change all the code. I'd like to get it working with Navigation 4 if it's possible, but it keeps giving me the upgrade error. 

I'm using expo 40 and trying to use  "react-navigation": "4.4.4",

**Expected Behavior**

My app should load with navigation

**How to reproduce**

Starting expo shows this error: 
Error: `createStackNavigator()` has been moved to `react-navigation-stack`. See https://reactnavigation.org/docs/stack-navigator.html for more details.

**Your Environment**

    "expo": "^40.0.0",

How can I force it to use Navigation 4?

Thank you!

**Comment by satya164** [comment]
https://reactnavigation.org/docs/4.x/upgrading-from-3.x/
