### ISSUE TITLE
documentation needs updating

### ISSUE THREAD

**Issue by krisbaum74** [react-navigation/react-navigation#9354]
**Current Behavior**
import { createBottomTabNavigator } from '@react-navigation/bottom-tabs';
import MaterialCommunityIcons from 'react-native-vector-icons/MaterialCommunityIcons';

const Tab = createBottomTabNavigator();

function MyTabs() {
  return (
    <Tab.Navigator
      initialRouteName="Feed"
      tabBarOptions={{
        activeTintColor: '#e91e63',
      }}
    >
      <Tab.Screen
        name="Feed"
        component={Feed}
        options={{
          tabBarLabel: 'Home',
          tabBarIcon: ({ color, size }) => (
            <MaterialCommunityIcons name="home" color={color} size={size} />
          ),
        }}
      />
      <Tab.Screen
        name="Notifications"
        component={Notifications}
        options={{
          tabBarLabel: 'Updates',
          tabBarIcon: ({ color, size }) => (
            <MaterialCommunityIcons name="bell" color={color} size={size} />
          ),
          tabBarBadge: 3,
        }}
      />
      <Tab.Screen
        name="Profile"
        component={Profile}
        options={{
          tabBarLabel: 'Profile',
          tabBarIcon: ({ color, size }) => (
            <MaterialCommunityIcons name="account" color={color} size={size} />
          ),
        }}
      />
    </Tab.Navigator>
  );
}

creates this issue ->
https://github.com/oblador/react-native-vector-icons/issues/937

  "@react-navigation/bottom-tabs": "^5.11.8",
    "@react-navigation/native": "^5.9.3",

**Expected Behavior**
- tabs working as expected

** outcome ->

**Comment by satya164** [comment]
The linked issue has a completely different import statement with different path for module and using named imports.

Again, name of default import doesn't matter. Please read the code more carefully.
