### ISSUE TITLE
NavigationContainer.dangerouslyGetState() isn't updated

### ISSUE THREAD

**Issue by yairopro** [react-navigation/react-navigation#9356]
**Current Behavior**

I export globally the `NavigationContainer.ref` so it can be used by the whole app [like in this documentation page](https://reactnavigation.org/docs/navigating-without-navigation-prop).
After navigating, the `navigation.dangerouslyGetState()` isn't updated and contains only the first initial route.

**Expected Behavior**

`navigation.dangerouslyGetState()` should return the current navigation state.

**How to reproduce**

https://codesandbox.io/s/react-navigation-dangerouslygetstate-not-updated-ldggj

To reproduce the bug in the demo (link above), follow the step:
1. Make sure you start at the home screen `/`.
2. Click on "Go to another screen" button
3. Now you are on `/another` page. The page displays the current `routes` array (mapped to their names) returned by `dangerouslyGetState()`. You'll be able to see that only "home" is in the array.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| Chrome                | 88
| @react-navigation/native       | 5.9.3
| react-native-web                   | 0.15.0

**Comment by satya164** [comment]
Add mentioned in docs, you shouldn't use for rendering as it can't trigger a re-render. Use the hook instead https://reactnavigation.org/docs/navigation-prop/#dangerouslygetstate

**Comment by yairopro** [comment]
**Of course it should not trigger a re-render. I wasn't expecting it to.**
The issue is about the state not being updated at all, event after the user has navigated.
I've updated the [codesandbox](https://codesandbox.io/s/react-navigation-dangerouslygetstate-not-updated-ldggj) and it will now log the state's routes names after user has navigated from the home screen to "another" screen. 
The log is triggered as an effect after the 2nd screen has been mounted and rendered. Even so, the state is not updated because the routes should contain "home" and "another" screens, but only "home" will be displayed in the logged routes array.

**Comment by satya164** [comment]
@yairopro not sure what's going on there, but you can use `navigation.getRootState()` to get the state from the ref. there's also `onStateChange` callback to notify you of state changes (both are documented on the ref, `dangerouslyGetState()` is not documented) - https://reactnavigation.org/docs/navigation-container#methods-on-the-ref

there seems to be some issue with `dangerouslyGetState()`, but it's not a priority to look into what's happening there.

**Comment by satya164** [comment]
fixed in https://github.com/react-navigation/react-navigation/commit/1d40279db18ab2aed12517ed3ca6af6d509477d2

**Comment by yairopro** [comment]
Thx @satya164 !
I will still dig more on  `navigation.getRootState()`, it seems you're right I should have use this one instead. Thanks for your advice too.
