### ISSUE TITLE
How to add header border ?

### ISSUE THREAD

**Issue by ardyfeb** [react-navigation/react-navigation#9357]
**Current Behavior**
I currently migrating to react-navigation 5 from react-navigation 4, there so many missing option that version 4 has

I cannot add border style and another view style to header. Current options available in `headerStyle` is 
```ts
headerStyle?: {
    backgroundColor?: string;
    blurEffect?: ScreenStackHeaderConfigProps['blurEffect'];
};
```

**Expected Behavior**

Header style should accept view style, user should freely add own style to header. Why react-navigation restrict this with no reason ?

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Android
| @react-navigation/native       | ^5.9.2
| @react-navigation/stack        | ^5.14.2

**Comment by rawatnaresh** [comment]
As the [docs](https://reactnavigation.org/docs/headers#adjusting-header-styles) says 

> headerStyle: a style object that will be applied to the View that wraps the header

which means you can pass any valid style props.
```js
headerStyle: {
  backgroundColor: '#f4511e',
  borderBottomColor: 'yellow',
  borderBottomWidth: 5
},
```

![Screen Shot 2021-02-25 at 09 18 51](https://user-images.githubusercontent.com/29520305/109099063-848c3b00-774a-11eb-9741-f86cb1033488.png)
