### ISSUE TITLE
After v5 configures the deep link, the android app backbutton exits the application directly.

### ISSUE THREAD

**Issue by hoohooluuluu** [react-navigation/react-navigation#9360]
> configure the deep link successfully. However, my application android backbutton will exit directly.
No matter which page I go to, pressing the backbutton will exit the application. If I revoke the deep link, everything works fine.

### run

```javascript
npx uri-shceme open test://app/home/1 --android

```

> It can open home, success.
> But when I packaged the apk and tested it in the real machine and the simulator, I opened the page normally, and then pressed the backbutton, it will > > support to exit the application. If I cancel linking, repackage the apk. Then everything is normal.

### code 

![image](https://user-images.githubusercontent.com/16655229/109124314-bf5f9480-7785-11eb-88a9-dece680f8f08.png)
![image](https://user-images.githubusercontent.com/16655229/109124471-ea49e880-7785-11eb-9722-6b0a1389774d.png)

### version info

```javascript
 Expo CLI 4.1.6 environment info:
    System:
      OS: Windows 10 10.0.18363
    Binaries:
      Node: 14.15.1 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.10 - C:\Users\Administrator\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
    SDKs:
      Android SDK:
        API Levels: 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30
        Build Tools: 23.0.3, 24.0.3, 25.0.3, 26.0.3, 28.0.3, 29.0.2, 29.0.3, 30.0.3
    IDEs:
      Android Studio: Version  4.1.0.0 AI-201.8743.12.41.6953283
    npmPackages:
      expo: ~40.0.0 => 40.0.0
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: 0.63.4 => 0.63.4
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: bare

```

**Comment by satya164** [comment]
https://reactnavigation.org/docs/configuring-links/#rendering-an-initial-route

**Comment by hoohooluuluu** [comment]
@satya164 
Do you mean that the deep link I configured will conflict with my MainStack?

**Comment by hoohooluuluu** [comment]
@satya164 
Maybe I didn’t say it clearly enough,
I can use deep links.
But here comes the point. When I open the app without using the deep link, if I open the app manually normally, when I click the android back button, the app will exit directly.

I tried to cancel the linking and then build again, and my app resumed to work correctly.
If linking is added again and then build, the above error will occur.

I want to know whether the configuration in deepLinking is related to the configuration in Stack? Will there be a conflict?

**Comment by Md-Mudassir47** [comment]
> @satya164 Maybe I didn’t say it clearly enough, I can use deep links. But here comes the point. When I open the app without using the deep link, if I open the app manually normally, when I click the android back button, the app will exit directly.
> 
> I tried to cancel the linking and then build again, and my app resumed to work correctly. If linking is added again and then build, the above error will occur.
> 
> I want to know whether the configuration in deepLinking is related to the configuration in Stack? Will there be a conflict?

were you able to fix this? even i'm facing the issue when the app is opened using deep link and i try to go back then it exits the app completely.

**Comment by borasumer** [comment]
> > @satya164 Maybe I didn’t say it clearly enough, I can use deep links. But here comes the point. When I open the app without using the deep link, if I open the app manually normally, when I click the android back button, the app will exit directly.
> > I tried to cancel the linking and then build again, and my app resumed to work correctly. If linking is added again and then build, the above error will occur.
> > I want to know whether the configuration in deepLinking is related to the configuration in Stack? Will there be a conflict?
> 
> were you able to fix this? even i'm facing the issue when the app is opened using deep link and i try to go back then it exits the app completely.

Did you add initialRouteName to your linkingConfiguration file?
