### ISSUE TITLE
Finaly how it work ? is this still working ? why there so many tutorial and no one works ??????? t

### ISSUE THREAD

**Issue by eliaskh** [react-navigation/react-navigation#9361]
to 
import { NavigationContainer } from '@react-navigation/native';
what this bugs ?
i never success to make it run !!!!!!!!!!!!!!!!!!!!! 
wowwwwwwwwwwww so many bugs... unlimited !!!!!!!!!!!
HOW TO MAKE IT WORK ?
WHAT I NEED ?

**Comment by danihazler** [comment]
First you need to calm down.
Second you should reformulate your question.
Third, if it's not a bug and you have just a doubt, you should ask here https://stackoverflow.com/
Fourth, share some of your code so  people can try to understand where is the problem.
and fifth ...good luck!

**Comment by eliaskh** [comment]
i still insist that your compoenet is the worst in all npm i ever worked with..
this is my code 

import React from 'react';
import { View, Text } from 'react-native';
import { NavigationContainer } from '@react-navigation/native';
import { createStackNavigator } from '@react-navigation/stack';
import Home from '../walk/src/screens/Home';



const Stack = createStackNavigator();

function App() {
  return (
    <NavigationContainer>
      <Stack.Navigator>
        <Stack.Screen name="wow" component={Home} />
      </Stack.Navigator>
    </NavigationContainer>
  );
}

export default App;






this not working ....  with this error 
×
Error: Got an invalid value for 'component' prop for the screen 'wow'. It must be a valid React Component.

**Comment by raajnadar** [comment]
First learn to file a bug report! And add repro to fix the issue. And follow the issue template

**Comment by eliaskh** [comment]
> First learn to file a bug report! And add repro to fix the issue. And follow the issue template

it is better for you to speak Indian.. i will google it .. and will translate it to English!
