### ISSUE TITLE
Unable to set Transparent background to a custom tabBar

### ISSUE THREAD

**Issue by jalalaghazadeh** [react-navigation/react-navigation#9366]
I'm implementing a design with a custom bottom-bar.
I implement it using "MyTabBar" from [doc](https://reactnavigation.org/docs/bottom-tab-navigator/)
<img width="590" alt="Screen Shot 2021-02-25 at 10 35 55 PM" src="https://user-images.githubusercontent.com/20884306/109203826-dd46ec80-77b9-11eb-955d-0ff658a16340.png">

here is the result:
<img width="361" alt="Screen Shot 2021-02-25 at 10 07 16 PM" src="https://user-images.githubusercontent.com/20884306/109202218-f9e22500-77b7-11eb-9eb8-3ba3f886e2d0.png">

I want the black part to be "transparent".

- I've done setting backgeoundColor style to holder <View/> of "MyTabBar" component but it just became `gray` (rgb(242, 242, 242)).

<img width="630" alt="Screen Shot 2021-02-25 at 10 25 10 PM" src="https://user-images.githubusercontent.com/20884306/109202604-69581480-77b8-11eb-84ce-a56a061fcfde.png">

- I've done setting theme to NavigationContainer to change default theme color but it just change from `gray` to `white`:

<img width="491" alt="Screen Shot 2021-02-25 at 10 28 22 PM" src="https://user-images.githubusercontent.com/20884306/109202993-d9669a80-77b8-11eb-9608-425be78766f7.png">

I expect to have a transparent bottomBar by setting its background-color to `'transparent' ` in my bottomTabBar component

**any one facing the same problem and knows how to solve it?**

---------------------------------------------------------------------------------------
| Android                | API 30
| @react-navigation/native      | 5.9.3
| @react-navigation/bottom-tabs | 5.11.8
| react-native-screens          | 2.17.1
| react-native                  | 0.63.4
| node                          | 12.16.2
| npm or yarn                   | 1.22.4

**Comment by jalalaghazadeh** [comment]
> The versions mentioned in the issue for the following packages differ from the latest versions on npm:
> 
> * `@react-navigation/native` (found: `5.9.2`, latest: `5.9.3`)
> * `@react-navigation/bottom-tabs` (found: `5.11.7`, latest: `5.11.8`)
> 
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?

I've checked

**Comment by jalalaghazadeh** [comment]
> The versions mentioned in the issue for the following packages differ from the latest versions on npm:
> 
> * `@react-navigation/native` (found: `5.9.2`, latest: `5.9.3`)
> * `@react-navigation/bottom-tabs` (found: `5.11.7`, latest: `5.11.8`)
> 
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?

I've checked that, problem is still there...

**Comment by raajnadar** [comment]
Did you try using `position: 'absolute'` for the bottom bar that should fix the issue?
