### ISSUE TITLE
android backbutton cannot return to the previous page

### ISSUE THREAD

**Issue by hoohooluuluu** [react-navigation/react-navigation#9375]
After configuring the android deep link, the test passes. But there is a serious problem. Clicking the android backbutton will exit the app instead of returning to the previous page.

> android/app/src/main/src/AndroidManifest.xml

![image](https://user-images.githubusercontent.com/77035746/109449200-cb4b9f00-7a82-11eb-93cf-0dd5ee251d7c.png)

> deeplink config

![image](https://user-images.githubusercontent.com/77035746/109445898-8e2fde80-7a7b-11eb-99c9-82acaac407b2.png)

> route

![image](https://user-images.githubusercontent.com/77035746/109445927-a30c7200-7a7b-11eb-8f99-30a5a91cd6c1.png)

> home.component

![image](https://user-images.githubusercontent.com/77035746/109446876-778a8700-7a7d-11eb-96cb-18ff0060c031.png)

> test

`npx uri-scheme open a08://warn/33 --android`

![image](https://user-images.githubusercontent.com/77035746/109449262-f1713f00-7a82-11eb-8f8a-dbe1ea5d4ea9.png)

![image](https://user-images.githubusercontent.com/77035746/109446026-d8b15b00-7a7b-11eb-832f-835575694978.png)

> version info 

"@react-navigation/native": "^5.9.3",
"@react-navigation/stack": "^5.14.3",

![image](https://user-images.githubusercontent.com/77035746/109446066-ebc42b00-7a7b-11eb-904c-157c77cb0e2d.png)

**Comment by satya164** [comment]
Please read docs before opening issues https://reactnavigation.org/docs/configuring-links/#rendering-an-initial-route
