### ISSUE TITLE
Custom Stack Navigator don't display header default

### ISSUE THREAD

**Issue by urvish91** [react-navigation/react-navigation#9377]
**Current Behavior**

import React, {useCallback, useEffect, useRef} from 'react';
import {
  NavigationHelpersContext,
  useNavigationBuilder,
  StackRouter,
  createNavigatorFactory,
  StackNavigationState, ParamListBase, StackRouterOptions, StackActionHelpers,

} from '@react-navigation/native';
import {View, PanResponder} from 'react-native';

const CustomNavigator = ({initialRouteName, children, screenOptions}) => {
  const {state, navigation, descriptors} = useNavigationBuilder(StackRouter, {
    children,
    screenOptions,
    initialRouteName,
  });
 
  const timerId = useRef(false);

  useEffect(() => {
    resetInactivityTimeout();
  }, [resetInactivityTimeout]);

  const panResponder = useRef(
    PanResponder.create({
      onStartShouldSetPanResponderCapture: () => {
        resetInactivityTimeout();
      },
    }),
  ).current;

  const resetInactivityTimeout = useCallback(() => {
    clearTimeout(timerId.current);
    timerId.current = setTimeout(() => {
      // action after user has been detected idle
      // ex: logout from the app
      console.log("Logoout from app...")
    }, 5000);
  }, []);

  return (
    <NavigationHelpersContext.Provider value={navigation}>
      <View style={{flex: 1}} {...panResponder.panHandlers}>
        {descriptors[state.routes[state.index].key].render()}
      </View>
    </NavigationHelpersContext.Provider>
  );
};

export const createMyNavigator = createNavigatorFactory(CustomNavigator);

**Expected Behavior**

I have created custom stack navigator as above but when it runs it works perfectly fine but header is not visible anymore. 
so my expectation is, it should work along with header. my logic is that if user is don't do any activity then after 5 seconds we need to give them alert. so as of now I have put log to just test. and it performs well. but header is not visible so I am not able to use this solution.

"@react-navigation/native": "^5.9.3",
"@react-navigation/stack": "^5.14.3",
"expo": "~39.0.2",
"react": "16.13.1",
"react-native": "https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz",

**Comment by urvish91** [comment]
Can you please update me on the issue which I am facing?

**Comment by satya164** [comment]
If you create a custom navigator, your code is responsible for displaying UI, header, animations or anything UI related. Only what you render is shown.
