### ISSUE TITLE
Should NavigationActions.back have an action option?

### ISSUE THREAD

**Issue by vlexaargas** [react-navigation/react-navigation#938]
I have the following Navigator setup (simplified):

```
const SimpleStack = StackNavigator({
    Screen1: { screen: Screen1 },
    Screen2: { screen: Screen2 },
    Screen3: { screen: Screen3 }
});

const Drawer = DrawerNavigator({
    Drawer1: { screen: Drawer1 },
    Drawer2: { screen: Drawer2 },
    Drawer3: { screen: Drawer3 }
});

const Modal = const SimpleStack = StackNavigator({
    SimpleStack: { screen: SimpleStack },
    Drawer: { screen: Drawer}
}, {
    mode: Platform.OS === 'ios' ? 'modal' : 'card'
});
```

Here is what I am trying to accomplish:

Initially, I am in the SimpleStack in Screen1. I navigate to Screen2, then Screen 3, then over to Drawer/Drawer1 which is displayed modally. When I dispatch the `NavigationActions.back()` action, the modal view is popped and I land back on SimpleStack/Screen3. The problem here is I'd really like to be able to land back on SimpleStack/Screen2.

To tackle this problem, I think it would be nice to mirror the `navigate` API and be able to something like this, in my case, from Drawer/Drawer1:

```
import { NavigationActions } from 'react-navigation'

const backAction = NavigationActions.back({

  params: {},

  action: NavigationActions.navigate({ routeName: 'Screen2'})

})

this.props.navigation.dispatch(navigateAction)
```

Does this line of thinking make sense? Is there an alternative here that I am missing?

**Comment by rxb** [comment]
Did you ever find a solution to this? I'm trying to do the same thing, I think.

**Comment by ericvicenti** [comment]
In this case, I think you can dispatch several actions at once, and the correct thing will happen. Or, after we merge #3393, you can go back by providing a key on the navigate action, which allows you to navigate back to the specified screen.

Feel free to open a new issue if that doesn't work.
