### ISSUE TITLE
Material Bottom Tab Navigator place under android phone navigation

### ISSUE THREAD

**Issue by Mihai-github** [react-navigation/react-navigation#9380]
Test Phone: Samsung galaxy s20

**Current Behavior**

  I am currently working on a react native project and I can not figure out how to make the material bottom navigation to be placed higher then my phones navigation. Currently almost all of the navigation is placed under the phone navigation and the only way I've come is by adding padding or margin bottom.

- Include a screenshot or video if it makes sense.
![image](https://user-images.githubusercontent.com/56633911/109783654-e3522880-7c12-11eb-8e54-9d47dca301f5.png)

**Expected Behavior**
   On android phones, not like on IOS,  you can have the phone bottom in 2 different option and adding a padding or margin bottom will create too much space on IOS devices and also on 1 way of having the navigation on android. The weird part is that on android with the different type of navigation works ok (you can see that in the picture below)

 ![image](https://user-images.githubusercontent.com/56633911/109784216-82772000-7c13-11eb-8a0d-6cd203e3e665.png)

- What do you expect should be happening?
   Have for android/ios solution that works on both platforms

- Include a screenshot or video if it makes sense.

**How to reproduce**

- You must provide a way to reproduce the problem. If you are having an issue with your machine or build tools, the issue belongs on another repository as that is outside of the scope of React Navigation.
- Either re-create the bug on [Snack](https://snack.expo.io) or link to a GitHub repository with code that reproduces the bug.
- Explain how to run the example app and any steps that we need to take to reproduce the issue from the example app.
- Keep the repro code as simple as possible, with the minimum amount of code required to repro the issue.
- Before reporting an issue, make sure you are on latest version of the package.

**Your Environment**

| software                               | version |
| -------------------------------------- | ------- |
| iOS or Android                        14 | 11
| @react-navigation/native        :   "@react-navigation/native": "^5.9.2",
| @react-navigation/material-bottom-tabs  : "@react-navigation/bottom-tabs": "^5.11.1",
| react-native-paper                   :  "react-native-paper": "^4.7.2",
| react-native                           :  "react-native": "^0.63.3",
| expo                                 :  no expo
| node                                :   v14.15.1
| npm or yarn                     :      "yarn": "^1.22.10"

**Comment by satya164** [comment]
Closing due to no response
