### ISSUE TITLE
Justify Content set to "flex-end" on portrait bottom tab navigator

### ISSUE THREAD

**Issue by SampsonCrowley** [react-navigation/react-navigation#9388]
**Current Behavior**

- What code are you running and what is happening?

Very simple bottom tab navigator (literally the sample code from the docs)

- Include a screenshot or video if it makes sense.

#### Portrait
![Screenshot from 2021-03-05 22-14-00](https://user-images.githubusercontent.com/22461638/110196214-47860f80-7e00-11eb-93e6-d1be0d45d36d.png)
![Screenshot from 2021-03-05 22-14-08](https://user-images.githubusercontent.com/22461638/110196216-4d7bf080-7e00-11eb-8000-2c9888d88aa0.png)

#### Landscape
![Screenshot from 2021-03-05 22-14-28](https://user-images.githubusercontent.com/22461638/110196218-51a80e00-7e00-11eb-8ebe-89408f846568.png)
![Screenshot from 2021-03-05 22-14-38](https://user-images.githubusercontent.com/22461638/110196220-540a6800-7e00-11eb-8ff7-6d2baeeb4498.png)

**Expected Behavior**

Tabs should be set to `center` not `flex-end`

- What do you expect should be happening?

Content should be centered inside tabs, like it is for landscape

- Include a screenshot or video if it makes sense.

![Screenshot from 2021-03-05 22-28-11](https://user-images.githubusercontent.com/22461638/110196493-1eff1500-7e02-11eb-9e5f-284d44cd86ca.png)

**How to reproduce**
Use the provided snack from the docs for `createBottomTabNavigator` and use any screen smaller than `768px`

even just opening on web (chrome) and using the "responsive" mode in dev tools to set screen width to anything below 768 triggers the style change

```js
import * as React from 'react';
import { Text, View } from 'react-native';
import { NavigationContainer } from '@react-navigation/native';
import { createBottomTabNavigator } from '@react-navigation/bottom-tabs';

function HomeScreen() {
  return (
    <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
      <Text>Home!</Text>
    </View>
  );
}

function SettingsScreen() {
  return (
    <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
      <Text>Settings!</Text>
    </View>
  );
}

const Tab = createBottomTabNavigator();

function MyTabs() {
  return (
    <Tab.Navigator>
      <Tab.Screen name="Home" component={HomeScreen} />
      <Tab.Screen name="Settings" component={SettingsScreen} />
    </Tab.Navigator>
  );
}

export default function App() {
  return (
    <NavigationContainer>
      <MyTabs />
    </NavigationContainer>
  );
}
```

**Your Environment**

| software                      | version |
| ----------------------------- | ------- |
| Android           | Pixel 5, Android 11, Build RQ2A.210305.006
|  Web               | Chrome Version 90.0.4430.11 (Official Build) dev (64-bit)
| @react-navigation/native      | 5.9.2 (expo)
| @react-navigation/bottom-tabs | 5.11.8
| react-native-screens          | 2.17.1 (installed by expo)
| react-native                  | 0.63.2
| expo                          | 40.0.1
| node                          | 15.1.0
| npm or yarn                   | 1.22.10

**Comment by SampsonCrowley** [comment]
Yes, Still occurs on 5.9.3

**Comment by SampsonCrowley** [comment]
Setting `labelPosition` to `beside-icon` does fix it, but that really shouldn't be necessary when an icon doesn't even exist for the tab

**Comment by raajnadar** [comment]
Check this out https://github.com/callstack/react-native-paper/discussions/2428

**Comment by SampsonCrowley** [comment]
@raajnadar not sure how that's relevant. *This* library still unnecessarily changes the styling to something that looks terrible when using label-only tabs unless you specifically set a prop for that label to be "beside" a child that doesn't exist, or specifically override the styling. If an icon isn't set, *this* library should be using defaults that actually make sense for the content.

The problem is occurring using a sample given directly by the library, so that sample should actually look presentable

**Comment by satya164** [comment]
Bottom Tab Navigator is not supposed to be used without an icon. You need to specify an icon with `tabBarIcon` option.

PRs improving the docs to make it more clear is welcome.

**Comment by SampsonCrowley** [comment]
@satya164 it should be the exact opposite. Icons, especially don't icons, are not accessible and rely on the user guessing what it means or already being familiar with your content. The default should work with simple text that actually labels a tab. If content creators *want* to use icons they should absolutely be able to, but labels should be first-class citizens

**Comment by satya164** [comment]
Bottom Tab navigator implements the bottom tab bar UX from iOS platform. If you don't want to follow platform conventions then you're free to provide your own tab bar component.
