### ISSUE TITLE
'NativeReanimated' could not be found. Verify that a module by this name is registered in the native binary.

### ISSUE THREAD

**Issue by MananDesai54** [react-navigation/react-navigation#9389]
**Current Behavior**

- Getting this error while configuring any kind of navigation

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | 9 |
| @react-navigation/native       | 5.9 |
| react-native                   | 0.63 |
| expo                           | - |
| node                           | 15.x |
| npm or yarn                    |  7.4 |

**Comment by raajnadar** [comment]
Can you paste the dependencies in your package.json?

**Comment by ecin-tpk** [comment]
react-native-reanimated 2.0 is out now. I wonder if there would be any problem

**Comment by MananDesai54** [comment]
@raajnadar  ohh my bad, here are dependencies
```json
"dependencies": {
    "@react-native-community/masked-view": "^0.1.10",
    "@react-navigation/drawer": "^5.12.4",
    "@react-navigation/native": "^5.9.3",
    "@react-navigation/stack": "^5.14.3",
    "react": "16.13.1",
    "react-native": "0.63.4",
    "react-native-gesture-handler": "^1.10.3",
    "react-native-reanimated": "^2.0.0",
    "react-native-safe-area-context": "^3.1.9",
    "react-native-screens": "^2.18.1"
  },
```

**Comment by MananDesai54** [comment]
> react-native-reanimated 2.0 is out now. I wonder if there would be any problem

yes i am using version 2.0.0, is there any problem related to it?

**Comment by raajnadar** [comment]
yes the support for reanimate 2 will be in react navigation v6, use reanimated v1 until it is supported in v5.

**Comment by MananDesai54** [comment]
Okay Thanks @raajnadar

**Comment by MananDesai54** [comment]
> yes the support for reanimate 2 will be in react navigation v6, use reanimated v1 until it is supported in v5.

this worked

**Comment by ModusPwnens1337** [comment]
After I uninstall reanimated then install version 1.13.2 I get the following erre:
`error: Error: Unable to resolve module ./reanimated2 from C:\Users\dmril\Projects\MyInvestmentClub\node_modules\react-native-reanimated\src\Animated.js:`

**Comment by MananDesai54** [comment]
@ModusPwnens1337 have restarted project ?

**Comment by ModusPwnens1337** [comment]
> @ModusPwnens1337 have restarted project ?

Yes, I'll try to restart my machine and see if it helps.

**Comment by ModusPwnens1337** [comment]
Here's a screenshot:
![image](https://user-images.githubusercontent.com/6161922/110215515-3d075c80-7e78-11eb-89f8-9c88b96944d8.png)

[Original Issue](https://github.com/react-navigation/react-navigation/issues/9390) for specs.

**Comment by satya164** [comment]
Please open issues regarding errors with installation of reanimated in reanimated repo.

**Comment by ModusPwnens1337** [comment]
> Please open issues regarding errors with installation of reanimated in reanimated repo.

I have:
https://github.com/software-mansion/react-native-reanimated/issues/1798
Thank you.

**Comment by raajnadar** [comment]
I found this comment @MananDesai54 about react native reanimated https://github.com/react-navigation/react-navigation/issues/8981#issuecomment-731233042

**Comment by gaviin-h** [comment]
I am still getting this error with the following dependencies:

"@react-navigation/drawer": "^6.3.1",
"react-native-reanimated": "^2.4.1",

is there any solutions not related to an issue with nav5 and reanimated2?
