### ISSUE TITLE
Importing createDrawerNavigator throws 'NativeReanimated' error.

### ISSUE THREAD

**Issue by ModusPwnens1337** [react-navigation/react-navigation#9390]
### Description
After following the installation instructions for [React Navigation](https://reactnavigation.org/docs/getting-started/) and then [Drawer Navigation](https://reactnavigation.org/docs/drawer-based-navigation/), I am getting a NativeReanimated error.

I have reanimated in both my package-lock.json:
`    "react-native-reanimated": {
      "version": "2.0.0",
      "resolved": "https://registry.npmjs.org/react-native-reanimated/-/react-native-reanimated-2.0.0.tgz",
      "integrity": "sha512-kIrdBoXSky7DQ62SOgosgimKM+Lt+SzAaM+ovVpCLBcwUK2aYRfLxa9ffgvKjeH9/n7dONlwEMjbKssGkuyq2Q==",
      "requires": {
        "@babel/plugin-transform-object-assign": "^7.10.4",
        "fbjs": "^3.0.0",
        "mockdate": "^3.0.2",
        "string-hash-64": "^1.0.3"
      }`
and in my package.json:
`  "dependencies": {
    "@react-native-community/masked-view": "^0.1.10",
    "@react-navigation/drawer": "^5.12.4",
    "@react-navigation/native": "^5.9.3",
    "@react-navigation/stack": "^5.14.3",
    "react": "16.13.1",
    "react-native": "0.63.4",
    "react-native-gesture-handler": "^1.10.3",
    "react-native-reanimated": "^2.0.0",
    "react-native-safe-area-context": "^3.1.9",
    "react-native-screens": "^2.18.1"
  }`

It was installed vis the React Navigation instructions as follows:
`npm install react-native-reanimated react-native-gesture-handler react-native-screens react-native-safe-area-context @react-native-community/masked-view`

This is the error I'm receiving in Metro and node after running **npx react-native run-android:**
[Sat Mar 06 2021 10:25:12.380]  **BUNDLE  ./index.js**

[Sat Mar 06 2021 10:25:15.192]  **ERROR    Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'NativeReanimated' could not be found. Verify that a module by this name is registered in the native binary.**
[Sat Mar 06 2021 10:25:15.196]  **ERROR    Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)**
[Sat Mar 06 2021 10:25:15.196]  **ERROR    Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)**

In the emulator I'm just receiving a blank white screen.

### Screenshots
![image](https://user-images.githubusercontent.com/6161922/110212233-63bd9700-7e68-11eb-86ff-0616981769f0.png)
![image](https://user-images.githubusercontent.com/6161922/110212284-aa12f600-7e68-11eb-8718-26609dc489c8.png)
![image](https://user-images.githubusercontent.com/6161922/110212302-bbf49900-7e68-11eb-89e6-789f1724d818.png)

## Steps To Reproduce
1. Try to run the app via: **npx react-native run-android**

### Expected behavior
The app should run.

### Actual behavior
I get a blank white screen.

## Snack or minimal code example
Commenting out this line: **import { createDrawerNavigator } from '@react-navigation/drawer';** fixes the error.

![image](https://user-images.githubusercontent.com/6161922/110212461-7d131300-7e69-11eb-9bc6-3bd439e3a28e.png)

## Package versions
Windows 10
Visual Studio Code

    "@react-native-community/masked-view": "^0.1.10",
    "@react-navigation/drawer": "^5.12.4",
    "@react-navigation/native": "^5.9.3",
    "@react-navigation/stack": "^5.14.3",
    "react": "16.13.1",
    "react-native": "0.63.4",
    "react-native-gesture-handler": "^1.10.3",
    "react-native-reanimated": "^2.0.0",
    "react-native-safe-area-context": "^3.1.9",
    "react-native-screens": "^2.18.1"
- NodeJS: **v10.19.0**

**Comment by raajnadar** [comment]
Check this issue #9389

**Comment by ModusPwnens1337** [comment]
> Check this issue #9389

Thank you. I tried to just run this:
`npm i react-native-reanimated@1.13.2`
but I now get the following error:
`Error: Unable to resolve module ./reanimated2 from C:\Users\dmril\Projects\MyInvestmentClub\node_modules\react-native-reanimated\src\Animated.js:`
