### ISSUE TITLE
navigationRef.current?.navigate() is not type checked (Typescript)

### ISSUE THREAD

**Issue by Kleinhummel** [react-navigation/react-navigation#9391]
**Current Behavior**

I created a _navigationRef_ as described [here](https://reactnavigation.org/docs/navigating-without-navigation-prop/) and [here](https://reactnavigation.org/docs/typescript/#annotating-ref-on-navigationcontainer). But when I call `navigationRef.current?.navigate('Login', { email, password });`, no parameter is type checked. Since I typed the navigation prop correctly in my React Native components, as described [here](https://reactnavigation.org/docs/typescript/#type-checking-screens), IntelliSense directly suggests the screens to which I can navigate in my components. However, this typing does not work with _navigationRef_.

**Expected Behavior**

Is there a way that the parameters of the methods of _navigationRef_ (e.g. navigate, ...) are also correctly typed. Or is it a bug?

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| @react-navigation/native       | 5.7.3
| react-native                   | 0.63.2
| expo                           | 40.0.1
| node                           | 14.15.1
| yarn                    | 1.22.10

**Comment by Kleinhummel** [comment]
Sure. I created a [new Expo project](https://github.com/Kleinhummel/react-navigation-bug) (Tabs with typescript). Then I added the navigationRef code. In the file navigation/navigationRef.ts I call `navigationRef.current?.navigate('Incorrect string');` and I don't get an error although there is no screen with the name `'Incorrect string'`

**Comment by satya164** [comment]
It's fixed in React Navigation 6 https://reactnavigation.org/docs/6.x/typescript#specifying-default-types-for-usenavigation-link-ref-etc

**Comment by stuckj** [comment]
> It's fixed in React Navigation 6 https://reactnavigation.org/docs/6.x/typescript#specifying-default-types-for-usenavigation-link-ref-etc

FYI, that doc link is broken (maybe it changed?). The correct link is https://reactnavigation.org/docs/typescript#specifying-default-types-for-usenavigation-link-ref-etc
