### ISSUE TITLE
Bottom Tab Navigator : Always show labels

### ISSUE THREAD

**Issue by saurabhnemade** [react-navigation/react-navigation#9394]
**Current Behavior**

- It is not possible to create bottom navigation with labels always showing. Every example I tried, only active tab shows label.

**Expected Behavior**

- There should be config on individual tabOptions to always show tabLabel. 

**Your Environment**

| software                               | version |
| -------------------------------------- | ------- |
| iOS                         | 14.4
| @react-navigation/native               | 5.9.3
| @react-navigation/material-bottom-tabs | 5.3.14
| react-native-paper                     | 4.7.2
| react-native                           | 0.63.4
| expo                                   | -
| node                                   | 15.10.0.
| npm or yarn                            | 7.5.3

**Comment by satya164** [comment]
https://reactnavigation.org/docs/material-bottom-tab-navigator/#shifting
