### ISSUE TITLE
Unique key preventing from snapshot test

### ISSUE THREAD

**Issue by Rc85** [react-navigation/react-navigation#9396]
**Current Behavior**

Keys are dynamically generated and preventing from snapshot test.

**Expected Behavior**

It shouldn't make it difficult to do snapshot testing.

**How to reproduce**

Use `jest` and `react-test-renderer` to run a snapshot test.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | 9
| @react-navigation/native       | 5.8.9
| @react-navigation/drawer       | 5.11.4
| react-native-reanimated        | 1.13.2
| react-native-gesture-handler   | 1.8.0
| react-native-safe-area-context | 3.1.9
| react-native-screens           | 2.16.1
| react-native                   | 0.63.3
| expo                           | NA
| node                           | 14.16.0
| npm or yarn                    | npm

![image](https://user-images.githubusercontent.com/22307591/110318883-ee1a0e00-7fc2-11eb-8b8a-f208fb10cb0d.png)

They keys doesn't look like it's `Date.now()` as mentioned in the other issues and suggest we can mock it. The navigator is also deep within the App component. The snapshot is saved as a string of nested components, so I'm not sure how to navigate the tree to remove these keys.

Would it be possible to create a static key?

**Comment by satya164** [comment]
You can mock `nanoid` package in your tests package to return stable IDs. However snapshot tests containing navigators can get pretty unreadable and not something we recommend doing.
