### ISSUE TITLE
Document that statusBarAnimation prop only works on iOS

### ISSUE THREAD

**Issue by pplytas** [react-navigation/react-navigation#9397]
**Current Behavior**

Although `statusBarAnimation` prop works fine on iOS, it does not have any effect on Android.

**How to reproduce**

Snack with an example [here](https://snack.expo.io/@panagiotis.plytas/drawer-statusbaranimation-issue)

**Expected Behaviour**

After digging in the React Native code I found that `setHidden` passes `animation` to iOS statusbar manager only ([see here](https://github.com/facebook/react-native/blob/93377ff5089d981e56094329b6f6893b3124be12/Libraries/Components/StatusBar/StatusBar.js#L265)). Maybe we can add a note in the `@react-navigation/drawer` docs ([here](https://reactnavigation.org/docs/drawer-navigator/#statusbaranimation)) that this prop works on iOS only, so people won't have to go looking for this in the future. It would also be useful to add the list of allowed values (i.e. `slide`, `fade`, `none`). 🙂

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Android
| @react-navigation/native       | 5.8.10
| @react-navigation/drawer       | 5.12.4
| react-native-reanimated        | 1.13.2
| react-native-gesture-handler   | 1.8.0
| react-native-safe-area-context | 3.1.9
| react-native-screens           | 2.15.2
| expo                           | 40.0.0

**Comment by mayank-budhiraja** [comment]
Hey @pplytas , I want to help maintaining this repo. This would be my first open source contribution. Thanks

**Comment by lk11601** [comment]
@pplytas this issue has been fixed - could you close the issue?
