### ISSUE TITLE
Translatable Stack Navigator in-document header [feature request]

### ISSUE THREAD

**Issue by Invertisment** [react-navigation/react-navigation#9399]
The box in the feature requests was too small. I wanted to describe the details correctly.

**Current Behavior**

Currently the routing works in a way that I need to navigate to a screen by passing it's `name`. I'd like to translate it into a different language (locale).

The screenshot shows that I can customize my webpage title but I couldn't find the option to customize the title for the page which resides in the screen itself:

![Screenshot at 2021-03-09 13-18-00](https://user-images.githubusercontent.com/1641263/110463775-02e9c500-80db-11eb-9d48-dd0d3ed492b6.png)

**Expected Behavior**

I'd like to have a function which allows to specify a function that produces a translation or something that allows to add a translation component to the title which resides in the body of the webpage:
```
(name: string) => string | React.ReactNode
```
**How to reproduce**
```
function MyStack() {
  return (
    <Stack.Navigator>
      <Stack.Screen name="com.home" component={HomeScreen} />
    </Stack.Navigator>
  );
}
```
```
      <NavigationContainer
        linking={linking}
        documentTitle={{formatter: (options, route) => {
          return `a${route.name}a`
        } }}>
        <MyStack />
      </NavigationContainer>

```

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | no difference, web too
| @react-navigation/native       |^5.9.3
| @react-navigation/stack        |^5.14.3
| react-native-gesture-handler   |
| react-native-safe-area-context |
| react-native-screens           |
| react-native                   |
| expo                           |
| node                           |
| npm or yarn                    |

**Comment by satya164** [comment]
You need to use `title` option to add screen titles which can be translated. `route.name` is fallback if you don't specify any title.
