### ISSUE TITLE
Drawer Navigator break with react-native-reanimated latest release(2.0.0)

### ISSUE THREAD

**Issue by ThalKod** [react-navigation/react-navigation#9401]
I'm trying to create a simple Drawer Navigation using react-navigation, but after installing `yarn add @react-navigation/drawer` i can't run the app, i keep getting an error; ` Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'NativeReanimated' could not be found.` Screenshot below...
<img width="1376" alt="Screen Shot 2021-03-09 at 11 56 04 AM" src="https://user-images.githubusercontent.com/32584079/110508306-e21b7280-80ce-11eb-8eb3-81fe7b58e639.png">

After some research, seems this have something to do with the latest react-native-reanimated update ?

**My Environment**

| software                       | version |
| ------------------------------ | ------- |
| @react-navigation/native       | 5.9.3
| @react-navigation/drawer       | 5.12.4
| react-native-reanimated        | 2.0.0
| react-native-gesture-handler   | 1.10.3
| react-native-safe-area-context | 3.2.0
| react-native                   | 0.63.4

**Comment by raajnadar** [comment]
Read this thread https://github.com/react-navigation/react-navigation/discussions/9221#discussioncomment-415622
