### ISSUE TITLE
Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'NativeReanimated' could not be found. Verify that a module by this name is registered in the native binary.

### ISSUE THREAD

**Issue by NinadPRDXN** [react-navigation/react-navigation#9407]
whenever I am importing '  **import {createDrawerNavigator} from '@react-navigation/drawer';**  ' . I am getting this in my Console **Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'NativeReanimated' could not be found. Verify that a module by this name is registered in the native binary.**. And getting blank screen as an Output

**Comment by raajnadar** [comment]
Read this https://github.com/react-navigation/react-navigation/discussions/9221#discussioncomment-415622

**Comment by vlack-coder** [comment]
reanimated just got updated to the version 2 and it involves a lot of configuration to make it work well with react Navigation. to avoid the stress, install any version below 2.0
