### ISSUE TITLE
I get an error when using Navigation Drawer

### ISSUE THREAD

**Issue by YunusEmreNalbant** [react-navigation/react-navigation#9410]
Hi,

I use react navigation v5 in my react native project. I can use createStackNavigator, no problem, but I can't use createDrawerNavigator. when I import, the project gives an error. Please help me. I'm freaking out.

I cleared the cache. it didn't work.  I created a new project from scratch, it didn't work again.
![asda](https://user-images.githubusercontent.com/29780061/110820869-8dc7ec80-82a0-11eb-9dd1-6d877cc01cdc.png)

Node  version : 14.15.4
react-native-cli: 2.0.1
 "@react-navigation/drawer": "^5.12.4",
 "@react-navigation/native": "^5.9.3",
 "@react-navigation/stack": "^5.14.3",
 "react": "16.13.1",
    "react-native": "0.63.4",

**Comment by raajnadar** [comment]
Please do some research before creating new issue https://github.com/react-navigation/react-navigation/discussions/9221#discussioncomment-415622

**Comment by raajnadar** [comment]
Check I updated the link, I linked a wrong issue previously.
