### ISSUE TITLE
Drawer Navigator does not have an option to configure headerTitleContainer

### ISSUE THREAD

**Issue by SampsonCrowley** [react-navigation/react-navigation#9413]
**Current Behavior**

Using the DrawerNavigator, custom Title and Right buttons overlap without any option to configure

![Screenshot from 2021-03-11 15-56-03](https://user-images.githubusercontent.com/22461638/110866555-8a256d00-8282-11eb-854a-3a9e4d0f7c67.png)

**Expected Behavior**

there should be a `headerTitleContainerStyle` option, same as the Stack Navigator

**How to reproduce**

add any custom button to `headerRight` that has a width higher than 72 (apparently the set width for web judging by the given values)

[Snack: https://snack.expo.io/6AgRTuM6f](https://snack.expo.io/6AgRTuM6f)

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Android v11 (and Web) 
| @react-navigation/native       | 5.9.3
| @react-navigation/drawer       | 5.12.3
| react-native-reanimated        | packaged with expo
| react-native-gesture-handler   | packaged with expo
| react-native-safe-area-context | 3.1.9
| react-native-screens           | 2.17.1
| react-native                   | packaged with expo
| expo                           | 40.0.1
| node                           | 15
| npm or yarn                    | yarn 1.22.10

**Comment by SampsonCrowley** [comment]
Yes, still happens on 5.12.4

**Comment by satya164** [comment]
This is supported in 6.x as drawer uses same implementation for header as stack.
