### ISSUE TITLE
Undefined is not a Object (evaluating '_meal.MEALS.find')

### ISSUE THREAD

**Issue by luqmansabir950** [react-navigation/react-navigation#9417]
Undefined is not a Object (evaluating '_meal.MEALS.find')....
I am getting this error.... I am working in navigation.... I am pretty new to the React Native and Development world overall... Please help me with that.... I am posting the code down as well....

**Comment by luqmansabir950** [comment]
import React from 'react';
import {View, Text , StyleSheet , Button} from 'react-native';
import { FlatList } from 'react-native-gesture-handler';
import { HeaderTitle } from 'react-navigation-stack';
import MealItem from '../Components/MealItem';
import {CATEGORIES, MEALS} from '../Data/dummy-data'

const CategoryMealsScreen = props =>{
    const renderMealItem=itemData=>{
        return <MealItem 
                title={itemData.item.title}
                duration={itemData.item.duration}
                affordability={itemData.item.affordability}
                image={itemData.item.imageUrl}
                complexity={itemData.item.complexity}
                onSelect={()=>{
                    props.navigation.navigate({
                        routeName:'MealDetail' , 
                        params:{
                            mealId: itemData.item.id
                    }})
                }}
                />
    }

    const catId =props.navigation.getParam('categoryId')
    const displayedMeal=MEALS.filter(meal=>meal.categoryIds.indexOf(catId)>=0);
    return(
        <View style={styles.container}>
            <FlatList 
                data={displayedMeal}
                keyExtractor={(item , index) =>item.id}
                renderItem={renderMealItem}
                style={{width:'90%'}}
            />
        </View>
    );
}

const styles=StyleSheet.create({
    container:{
        flex:1,
        justifyContent:'center',
        alignItems:'center'
    }
});

export default CategoryMealsScreen;

**Comment by luqmansabir950** [comment]
From the Above file, I am sending the Id to the next screen

**Comment by luqmansabir950** [comment]
*import React from 'react';
import {View, Text , StyleSheet , Button} from 'react-native';
import {MEALS} from '../model/meal'

const MealDetailScreen = props =>{
    const mealId=props.navigation.getParam('mealId');
    const selectedMeal= MEALS.find(meal=>meal.id===mealId);
    
    return(
        <View style={styles.container}>
            <Text>{selectedMeal.title}</Text>
            <Button title="go to Categories" onPress={()=>{
            }}/>
        <Button title="Go back" onPress={()=>{
                props.navigation.popToTop();
            }}/>
        </View>
    );
}
const styles=StyleSheet.create({
    container:{
        flex:1,
        justifyContent:'center',
        alignItems:'center'
    }
});

export default MealDetailScreen;**

**Comment by luqmansabir950** [comment]
const selectedMeal= MEALS.find(meal=>meal.id===mealId); 

This line of code is problematic

**Comment by raajnadar** [comment]
This has nothing to do with react navigation. This section is to track bugs in the library.
