### ISSUE TITLE
Dynamically change linking prop of NavigationContainer

### ISSUE THREAD

**Issue by mir1198yusuf** [react-navigation/react-navigation#9421]
I just want to know , because I could not find in the docs.

Can I dynamically  change linking prop of NavigationContainer by its ref or some other way , similar to how to we do `navigation.setOptions` to update title, etc dynamically ?

**Comment by satya164** [comment]
It's a prop. You can update it like any other prop by using local state or any other way.

**Comment by mir1198yusuf** [comment]
No no, I mean based on some later events in app, I want to update it later after NavigationContainer is mounted example 2-3 screens later, not in the same file of NavigationContainer , then how should I do this ?

Also reopen the issue please till it is solved

**Comment by satya164** [comment]
> No no, I mean based on some later events in app

Just like you'd update any other prop based on some later events in the app. For example put it in state and expose some method via context to the child screens to be able to change this.

> Also reopen the issue please till it is solved

The issue tracker is reserved for bug reports. This is a question. Please ask your questions on the linked resources when you open an issue.

**Comment by mir1198yusuf** [comment]
> Just like you'd update any other prop based on some later events in the app. For example put it in state and expose some method via context to the child screens to be able to change this.

Yes! Since I was using redux already, based on state change I updated the linking prop of NavigationContainer by using local state.


> The issue tracker is reserved for bug reports. This is a question.

Yeah I will do that next time.

_Thanks a lot!_
