### ISSUE TITLE
navigation.popToTop() inside a tabPress listener is executed on the previous tab.

### ISSUE THREAD

**Issue by VictorioMolina** [react-navigation/react-navigation#9424]
**Current Behavior**

I have a stack navigator from [react-native-shared-element](https://github.com/IjzerenHein/react-native-shared-element) inside a materialBottomTabNavigator.

The bottom tab navigator tab presses are working as expected when the screen inside the tab which is pressed is a stack screen from your library.

But, when the stack screen is from react-native-shared-element, [this behaviour](https://reactnavigation.org/docs/bottom-tab-navigator/#tabpress) is ignored... That is why I am trying to implement it by my own inside a tabPress listener, to achieve the same behaviour.

**Code**

```
       <Tab.Screen
          name="Profile"
          component={ProfileStacks}
          listeners={({ navigation, route }) => ({
            tabPress: () => {
              /* 
                📝 Note: The stack navigator which is implemented in the library
                'react-navigation-shared-element' doesn't works with the default tab press
                behaviour from 'react-navigation'. 

                https://github.com/IjzerenHein/react-native-shared-element/issues/52

                In order to fix this issue, we have had to implement our popToTop()
                in the press listener.
              */

              /*
                Only pop to top if we are in the profile stacks, with multiple screens opened,
                and then we press the tab again. 
              */

              if (route.name === "Profile" && route.state?.routes.length > 1) {
                navigation.popToTop();
              }
            },
          })}
        />
```

**Expected Behavior**

When I press the tab which has the listener, the code is correctly executed, but, for some reasons, navigation.popToTop() is executed in the tab from which I am coming (the previous tab).

**Same problem**
https://github.com/IjzerenHein/react-navigation-shared-element/issues/81

**My Environment**

| software                      | version |
| ----------------------------- | ------- |
| iOS                              | 14.3
| @react-navigation/native      | ^5.9.2
| @react-navigation/bottom-tabs | ^5.11.7
| @react-navigation/material-bottom-tabs | ^5.3.13
| react-native-shared-element | ^0.7.0
| react-native-screens          | ~2.15.2
| react-native                  | ^0.63.4
| expo                          | ^40.0.1
| node                          | 15.9.0
| yarn                   | 1.22.10

**Comment by VictorioMolina** [comment]
Tested with last versions, but I am having the same problem. Not sure if this is a bug or if I am doing something wrong...

**Comment by VictorioMolina** [comment]
Solved with 

```
<Tab.Screen
          name="Profile"
          component={ProfileStacks}
          listeners={({ navigation, route }) => ({
            tabPress: () => {
              Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);

              if (
                navigation.dangerouslyGetState()?.index === 4 &&
                route.state?.routes.length > 1
              ) {
                navigation.popToTop();
              }
            },
          })}
        />
```

**Comment by VictorioMolina** [comment]
Okey, nope, the problem still continues happening. I don't know why (the code above seems good and logical to me). 90% of the times, the route which is popToTop() is the correct target (the stack of the 5th tab), but sometimes, the screen which is popToTop() is the stack of my previous route in the tab navigator.

**Comment by satya164** [comment]
If you can only repro this with `react-native-shared-element`, then this isn't an issue in React Navigation. Closing since the issue belongs in the relevant repo.

**Comment by alidavodii** [comment]
This code is enough and it works

`import { StackActions } from '@react-navigation/native'
`

` <Tab.Screen name='SearchNavigator' component={SearchNavigator}
            listeners={props => tabPressListener({ ...props })}/>`

and

`const tabPressListener = props => {
    const { navigation } = props
    return {
        blur: e => {
            const target = e.target
            const state = navigation.dangerouslyGetState()
            const route = state.routes.find(r => r.key === target)
            // If we are leaving a tab that has its own stack navigation, then clear it
            if (route.state?.type === "stack" && route.state.routes?.length > 1) {
                navigation.dispatch(StackActions.popToTop())
            }
        }
    }
}`
