### ISSUE TITLE
Provider is not defined: React-Native 0.64 [Inline Requires]

### ISSUE THREAD

**Issue by teamzz111** [react-navigation/react-navigation#9425]
**Current Behavior**

Im running MaterialBottom tab navigator, shows error with inlines requires enabled as default in react native .64

```
import * as React from 'react';
import {createMaterialBottomTabNavigator} from '@react-navigation/material-bottom-tabs';
import Task from '@navigations/Feed/Task';
import {PRIMARY_COLOR} from '@styles/colors';
import {Icon} from '@ui-kitten/components';
import {TFeedParamList} from '@interfaces/Navigations/Feed/IMaterialBottomNavigator';

const IconBar: React.FC<{color: string; name: string}> = ({color, name}) => (
  <Icon name={name} fill={color} style={{width: 25, height: 25}} />
);

const Home: React.FC = () => {
  const Tab = createMaterialBottomTabNavigator<TFeedParamList>();
  return (
    <>
      <Tab.Navigator
        initialRouteName="Tasks"
        barStyle={{backgroundColor: PRIMARY_COLOR}}
        shifting={true}
        sceneAnimationEnabled={false}>
        <Tab.Screen
          name="Tasks"
          component={Task}
          options={{
            title: 'Tasks',
            tabBarIcon: ({color}) => (
              <IconBar color={color} name="list-outline" />
            ),
          }}
        />
        <Tab.Screen
          name="Chat"
          component={Task}
          options={{
            title: 'Chat',
            tabBarIcon: ({color}) => (
              <IconBar color={color} name="message-square-outline" />
            ),
          }}
        />
      </Tab.Navigator>
    </>
  );
};

export default Home;
```
<img width="468" alt="Captura de Pantalla 2021-03-16 a la(s) 1 02 54 a  m" src="https://user-images.githubusercontent.com/37392536/111264260-2f2ea580-85f5-11eb-9b01-245ed46f0d5e.png">
**Expected Behavior**

Render material bottom tab navigator

**How to reproduce**

Create an empty project with RN 0.64 and insert Bottom tab navigator 

**Your Environment**

| software                      | version |
| ----------------------------- | ------- |
| iOS or Android                | iOS 14
| @react-navigation/native      | 5.9.3
| @react-navigation/bottom-tabs | 5.3.14
| react-native-screens          | 2.18.1
| react-native                  | 0.64
| expo                          | -
| node                          |  14.15.4
| npm or yarn                   | yarn 1.22.10

**Comment by teamzz111** [comment]
Persist.

**Comment by raajnadar** [comment]
https://github.com/react-navigation/react-navigation/issues/8166

Upgrade all the @react-navigation dependencies to latest and run `npx react-native start` after that `npx react-native run-android` or `npx react-native run-ios`

If that did not fix the issue let me know & also add a repro to check the issue.
