### ISSUE TITLE
"Could not resolve dependency" error with "react@^16.0"

### ISSUE THREAD

**Issue by roxlu** [react-navigation/react-navigation#9426]
**Current Behavior**

Installing `@react-navigation/stack` fails due to dependency error.

**How to reproduce**

I've just created a new react-native application following these steps:

```bash
npx react-native init test
cd test
npm install @react-navigation/native 
npm install @react-navigation/stack --save 
```
Running `npm install @react-navigation/stack --save` results in:

```bash
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: lc@0.0.1
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"17.0.1" from the root project
npm ERR!   peer react@"*" from @react-navigation/stack@5.14.3                               core/CMakeFiles/test-core_ty
npm ERR!   node_modules/@react-navigation/stack
npm ERR!     @react-navigation/stack@"*" from the root project                              st-bug_ms_vec_static
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.0" from @react-native-community/masked-view@0.1.10                 test-core_type_mat4x3
npm ERR! node_modules/@react-native-community/masked-view
npm ERR!   peer @react-native-community/masked-view@">= 0.1.0" from @react-navigation/stack@5.14.3
npm ERR!   node_modules/@react-navigation/stack
npm ERR!     @react-navigation/stack@"*" from the root project                              pe_length
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
```

This seems to be caused because the package.json from the react-native application template
has a dependency with `react 17.0.1` instead of `react 16`. The package.json that I currently have 
look like:

```js
{
  "name": "lc",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "exports": {
    "./": "./src/"
  },
  "dependencies": {
    "@react-native-async-storage/async-storage": "^1.14.1",
    "@react-navigation/native": "^5.9.3",
    "axios": "^0.21.1",
    "formik": "^2.2.6",
    "react": "17.0.1",
    "react-native": "0.64.0",
    "react-query": "^3.12.1",
    "yup": "^0.32.9"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-jest": "^26.6.3",
    "eslint": "7.14.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.64.0",
    "react-test-renderer": "17.0.1"
  },
  "jest": {
    "preset": "react-native"
  }
}

```

**Your Environment**

- Android
- Arch Linux 5.11.5
- Nove 15.11.0
- React Native  0.64.0

**Comment by hussainahmad** [comment]
+1 unable to install `@react-navigation/stack`

**Comment by minh-dai** [comment]
+1

**Comment by sdaoud** [comment]
+1

**Comment by SFV-CORE** [comment]
+1

**Comment by Abe90** [comment]
+1

**Comment by milesziemer** [comment]
+1

**Comment by yohandal123** [comment]
I'm having the same issue need a fix

**Comment by yohandal123** [comment]
Tried using navigation 6 when installing @react-navigation/stack@next I get an error

**Comment by satya164** [comment]
As per the error log, the issue is in the `@react-native-community/masked-view` package. Since the package is moved to a different name now, you have 2 options:

- Use `yarn` instead of `npm` which won't throw errors for mismatching peer dependency
- Or upgrade to React Navigation 6: https://reactnavigation.org/docs/6.x/upgrading-from-5.x which will use the new package

**Comment by roxlu** [comment]
Thanks @satya164 and I should have looked closer at the error message. It's related to the `@react-native-community/masked-view` package and not `@react-navigation/stack` indeed.  To get a better understanding I looked into the package.json of the `@react-navigation/stack` package and for anyone who finds this interesting I've written down some info below.

The package.json for `@react-navigation/stack` is located inside this `react-navigation` repository. [Here you can find the latest version](https://github.com/react-navigation/react-navigation/blob/main/packages/stack/package.json). As the currently published version is 5.14.3 you have to make sure to use the commit which you can select via the "tags" here on github:

![image](https://user-images.githubusercontent.com/358809/111598112-25f93080-87cf-11eb-9a9f-66bb5153c3fa.png)

The package.json for version 5.14.3 has the following listed as it's peer dependencies:

```json
  "peerDependencies": {
    "@react-native-community/masked-view": ">= 0.1.0",
    "@react-navigation/native": "^5.0.5",
    "react": "*",
    "react-native": "*",
    "react-native-gesture-handler": ">= 1.0.0",
    "react-native-safe-area-context": ">= 0.6.0",
    "react-native-screens": ">= 2.0.0-alpha.0 || >= 2.0.0-beta.0 || >= 2.0.0"
  },
```

There you'll find the `@react-native-community/masked-view` dependency which was causing the error:

```bash
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.0" from @react-native-community/masked-view@0.1.10                 test-core_type_mat4x3
npm ERR! node_modules/@react-native-community/masked-view
npm ERR!   peer @react-native-community/masked-view@">= 0.1.0" from @react-navigation/stack@5.14.3
npm ERR!   node_modules/@react-navigation/stack
npm ERR!     @react-navigation/stack@"*" from the root project                              pe_length
```

Note that like @satya164 said the name of `@react-native-community/masked-views` changed and also note that when you click the "Homepage" link, which is listed as [https://github.com/react-native-community/react-native-masked-view](https://github.com/react-native-community/react-native-masked-view) on the [npmjs repository](https://www.npmjs.com/package/@react-native-community/masked-view) you get redirected to the renamed package.

**Comment by roxlu** [comment]
Like @yohandal123 said, when you try to install `@react-navigation/stack@next` you'll run into the error below which you can fix by adding the `--legacy-peer-deps`: `npm install @react-navigation/stack@next --legacy-peer-deps`

```bash
$ npm install @react-navigation/stack@next
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: lc@0.0.1
npm ERR! Found: @react-navigation/native@6.0.0-next.1
npm ERR! node_modules/@react-navigation/native
npm ERR!   @react-navigation/native@"^6.0.0-next.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @react-navigation/native@"^6.0.0" from @react-navigation/stack@6.0.0-next.6
npm ERR! node_modules/@react-navigation/stack
npm ERR!   @react-navigation/stack@"6.0.0-next.6" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

```

**Comment by MrIceman** [comment]
This is frustrating, you can not just move packages around in a library that you decide to publish. You're breaking the application of tens of thousands of people

**Comment by sayeed360** [comment]
I'm new to RN and I got a feeling that this whole ecosystem is a complete mess, no one know what they are doing, don't even bother to update documentations. Everything works with expo, but with bare flow, something breaks everyday. I kinda feeling that it's a deliberate attempt to discourage bare flow.
