### ISSUE TITLE
Change backgroundColor of bottom tabs depending on Tab

### ISSUE THREAD

**Issue by iromjkee** [react-navigation/react-navigation#9427]
**Current Behavior**

So trying to change bottom tabs backgroundColor depending on the Tab, but nothing works, can`t find the solution for it.

**Expected Behavior**

Should look like this on different tabs
![image](https://user-images.githubusercontent.com/25479692/111426838-4dd09180-8706-11eb-9df7-817f50e3c20d.png)
![image](https://user-images.githubusercontent.com/25479692/111426875-5759f980-8706-11eb-83ac-f77286439af4.png)

**Your Environment**

| software                      | version |
| ----------------------------- | ------- |
| iOS or Android               | iOS
| @react-navigation/native      | 5.9.2
| @react-navigation/bottom-tabs | 5.11.7
| react-native-screens          | 2.17.1
| react-native                  | 0.63.4
| node                          | v14.11.0
| npm or yarn                   | yarn 1.22.5

**Comment by iromjkee** [comment]
> The versions mentioned in the issue for the following packages differ from the latest versions on npm:
> 
> * `@react-navigation/native` (found: `5.9.2`, latest: `5.9.3`)
> * `@react-navigation/bottom-tabs` (found: `5.11.7`, latest: `5.11.8`)
> 
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?

Issue still remains.

**Comment by raajnadar** [comment]
use this prop https://reactnavigation.org/docs/material-bottom-tab-navigator/#tabbarcolor

**Comment by iromjkee** [comment]
> use this prop https://reactnavigation.org/docs/material-bottom-tab-navigator/#tabbarcolor

I am using react-navigation/bottom-tabs not material

**Comment by raajnadar** [comment]
use can use the options to set the https://reactnavigation.org/docs/bottom-tab-navigator/#style

**Comment by iromjkee** [comment]
> https://reactnavigation.org/docs/bottom-tab-navigator/#style

See, I need to change whole tab bar backgroundColor in Tab.screen. For example take this, what should I do???
![image](https://user-images.githubusercontent.com/25479692/111451739-ce9d8680-8722-11eb-9f94-5503dfe92396.png)

**Comment by raajnadar** [comment]
`style: {backgroundColor: 'rgba(0, 0, 0, .25)' }` inside your options. If that did not work create a snack demo I will update it.

**Comment by iromjkee** [comment]
> `style: {backgroundColor: 'rgba(0, 0, 0, .25)' }` inside your options. If that did not work create a snack demo I will update it.
https://snack.expo.io/@iromjkee/react-navigation-bottom-tab-navigtator-change-backgroundcolor-of-bottom-tab-bar-on-different-tab

**Comment by iromjkee** [comment]
> `style: {backgroundColor: 'rgba(0, 0, 0, .25)' }` inside your options. If that did not work create a snack demo I will update it.

Could you check snack please?

**Comment by raajnadar** [comment]
@iromjkee you need to do something like this https://reactnavigation.org/docs/bottom-tab-navigator/#tabbar

**Comment by iromjkee** [comment]
> @iromjkee you need to do something like this https://reactnavigation.org/docs/bottom-tab-navigator/#tabbar

You mean just to change backgroundColor I need to write my own tab bar component? Hmm, funny.

**Comment by raajnadar** [comment]
You only need to provide the component that you need to render rest everything will be handled by react navigation. If you use react native paper for stack you can provide its appbar for stack bar. If you need custom configuration you need to provide your own element.
