### ISSUE TITLE
Setting header backgroundColor to rgba

### ISSUE THREAD

**Issue by iromjkee** [react-navigation/react-navigation#9428]
**Current Behavior**

Trying to set header backgroundColor to rgba(255,255,255, 0.94) in Stack Navigator

**Expected Behavior**

Expected to see such header bar
![image](https://user-images.githubusercontent.com/25479692/111432674-604ec900-870e-11eb-9f19-3279987f11e2.png)

**How to reproduce**
Just try to set backgroundColor to header in Stack Navigator to any rgba

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | iOS
| @react-navigation/native       | 5.9.2 
| @react-navigation/stack        | 5.14.2
| react-native-gesture-handler   | 1.10.0
| react-native-safe-area-context | 3.1.9
| react-native-screens           | 2.17.1
| react-native                   | 0.63.4
| node                           | v14.11.0
| npm or yarn                    | yarn 1.22.5

**Comment by iromjkee** [comment]
> The versions mentioned in the issue for the following packages differ from the latest versions on npm:
> 
> * `@react-navigation/native` (found: `5.9.2`, latest: `5.9.3`)
> * `@react-navigation/stack` (found: `5.14.2`, latest: `5.14.3`)
> 
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?

Issue still remains the same

**Comment by raajnadar** [comment]
Read the docs carefully we have many props to customize if in case find no option to do something you can always create a custom element and render it.

**Comment by iromjkee** [comment]
> Read the docs carefully we have many props to customise if in case you do not find any option to do some customisation you can always create a custom element and render it.

Didn`t find anything about that there, google also didn`t help
