### ISSUE TITLE
initialRouteName don't work with react-native-tab-view v3 on Android with Hermes

### ISSUE THREAD

**Issue by Bardiamist** [react-navigation/react-navigation#9435]
**Current Behavior**

`initialRouteName` don't work. Or scrolling to first route. Problem only on Android with Hermes (no problem on iOS with Hermes).

**Expected Behavior**

Tabs should open specified `initialRouteName` on init.

**How to reproduce**

https://github.com/Bardiamist/initialRouteRame

**Your Environment**

| software                            | version |
| ----------------------------------- | ------- |
| iOS or Android                      | Android (Checked on Android 11 simulator)
| @react-navigation/native            |5.9.3
| @react-navigation/material-top-tabs |5.3.14
| react-native-tab-view               |3.0.0
| react-native                        |0.64.0
| expo                                |-
| node                                |15.12.0
| npm or yarn                         |yarn 1.22.10

**Comment by Bardiamist** [comment]
I added minimal repro: https://github.com/Bardiamist/initialRouteRame

**Comment by Lukas-Heiligenbrunner** [comment]
This bug is fixed within v5.1.3 of react-native-pager-view: https://github.com/callstack/react-native-pager-view/releases

**Comment by Bardiamist** [comment]
Thanks @troZee @KusStar @Lukas-Heiligenbrunner
