### ISSUE TITLE
App crashes when using Reanimated 2

### ISSUE THREAD

**Issue by kaneki666** [react-navigation/react-navigation#9440]
**Current Behavior**

When i use drawercontent props.progress app crash

**Expected Behavior**

I can not use the props.progress value

**How to reproduce**

-import React from 'react';
import {createDrawerNavigator, useIsDrawerOpen} from '@react-navigation/drawer';
import {Dimensions} from 'react-native';

import StackNavigator from './StackNavigator';
import {colors} from '../utils';
import {CustomDrawerContent} from '../components/index';

import {
  Extrapolate,
  interpolate,
  useAnimatedStyle,
  useSharedValue,
} from 'react-native-reanimated';
import {useEffect} from 'react';

const Drawer = createDrawerNavigator();
const {width} = Dimensions.get('window');

const DrawerNavigation = props => {
  let progress = useSharedValue(0);
  const scale = interpolate(progress.value, [0, 1], [1, 0.6]);
  const borderRadius = interpolate(progress.value, [0, 1], [0, 16]);
  const animatedStyle = useAnimatedStyle(() => {
    return {
      borderRadius: borderRadius,
      transform: [{scale: scale}],
    };
  });

  return (
    <Drawer.Navigator
      initialRouteName="Home"
      style={{flex: 1}}
      drawerStyle={{
        backgroundColor: colors.TEXTWHITE,
        width: width * 0.6,
        opacity: 1,
      }}
      drawerContent={props => {
        progress.value = props.progress
        return <CustomDrawerContent {...props} />;
      }}>
      <Drawer.Screen name="Home">
        {props => <StackNavigator {...props} animatedStyle={animatedStyle} />}
      </Drawer.Screen>
    </Drawer.Navigator>
  );
};

export default DrawerNavigation;

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
|  Android                 |
 "@react-native-community/masked-view": "^0.1.10",
    "@react-navigation/drawer": "^5.12.4",
    "@react-navigation/native": "^5.9.3",
    "@react-navigation/stack": "^5.14.3",
    "react": "17.0.1",
    "react-native": "0.64.0",
    "react-native-gesture-handler": "^1.10.3",
    "react-native-reanimated": "^2.0.0",
    "react-native-safe-area-context": "^3.2.0",
    "react-native-screens": "^2.18.1",
    "react-native-vector-icons": "^8.1.0"  |
| node   v12.18.4|
|  yarn                    |

**Comment by satya164** [comment]
`progress` is an `Animated.Value`, you can't just assign it to a shared value like that. closing since this isn't a bug.

**Comment by kaneki666** [comment]
@satya164 is there workaround to use shared value? when open drawer so i can set sharedvalue =1

**Comment by satya164** [comment]
you should ask about it in Reanimated related forums

**Comment by pnogier** [comment]
@kaneki666 Hi ! Did you find a way to make this work ? 
I'm struggling animating a drawer, let me know if you did find a workaround 🙏

**Comment by kaneki666** [comment]
@pnogier i didn't ...so i removed the animation just

**Comment by pnogier** [comment]
@kaneki666 Ok, finaly I guess I found a workaround using `const [progress, setProgress] = useState(new Animated.Value(0));`
and then : `drawerContent={props => {
        setProgress(props.progress)
        return <DrawerContent {...props} />;
      }}`

**Comment by kaneki666** [comment]
@pnogier it works fine with reanimated v1

**Comment by pnogier** [comment]
@kaneki666 Sure, but I just wanted to handle it using reanimated v2, also I use interpolateNode instead of interpolate
