### ISSUE TITLE
Component Exception - undefined is not an object (near '...e.routes.length - 

### ISSUE THREAD

**Issue by pzanwar03** [react-navigation/react-navigation#9455]
**Current Behavior**

- 
![image](https://user-images.githubusercontent.com/25006760/112150732-a0c8ae00-8c0a-11eb-89da-088f82283635.png)

**How to reproduce**
![image](https://user-images.githubusercontent.com/25006760/112150979-e5ece000-8c0a-11eb-921e-7e59e4212187.png)

- Tab switching.
- Schedule tab has one stack screen which have **one** screen
- Icon tab has one stack screen which have **one** screen
- Order Now has one stack screen which have **four** screen
- When switching the tab screen and go Order Now two or three stack screen and back to schedule tab & then press Order Now tab then the error shows

**Code**
![image](https://user-images.githubusercontent.com/25006760/112152154-2bf67380-8c0c-11eb-933d-1eb899f99316.png)
 

**Your Environment**

| software                      | version |
| ----------------------------- | ------- |
| iOS or Android                | 14.4
| @react-navigation/native      | 5.9.3
| @react-navigation/bottom-tabs | 5.11.8
| react-native-screens          | 2.18.1
| react-native                  | 0.63.4
| node                          | 14.16.0

**Comment by satya164** [comment]
Closing since there's no repro to debug the issue.
