### ISSUE TITLE
Can't install Stack Navigator package when using React Native 0.64 which uses React 17

### ISSUE THREAD

**Issue by nechmads** [react-navigation/react-navigation#9459]
**Current Behavior**

When running npm install @react-navigation/stack (latest version 5.9.3) you get the error:
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.0" from @react-native-community/masked-view@0.1.10
npm ERR! node_modules/@react-native-community/masked-view
npm ERR!   peer @react-native-community/masked-view@">= 0.1.0" from @react-navigation/stack@5.14.3
npm ERR!   node_modules/@react-navigation/stack
npm ERR!     @react-navigation/stack@"*" from the root project

masked-view released a fix but it is published under:
react-native-masked-view/masked-view V0.2.3 and not under @react-native-community/masked-view which Stack Navigator relies upon.

**Expected Behavior**

Package to be installed successfully.

**How to reproduce**

Start a new bare React Native project V0.64.
Try to install Stack Navigator package.

**Your Environment**

Mac OS
React Native 0.64 without Expo
@react-navigation/native V 5.9.3

**Comment by nechmads** [comment]
Yes. Installing latest version of @react-navigation/native - 5.9.3

**Comment by raajnadar** [comment]
try yarn the issue should get resolved
