### ISSUE TITLE
Drawer that has stacks with same screen names should navigate to screen of most recently active stack

### ISSUE THREAD

**Issue by mackenziekira** [react-navigation/react-navigation#9460]
**Current Behavior**
When I have two stack navigators within a drawer navigator, and both stacks share a screen with the same name, I expect the screen registered with the most recently active stack navigator to be chosen when I select a drawer option. 

Reproducible example:
https://snack.expo.io/@rivet/react-navigation-bug

1) Navigate to "Projects"
2) Navigate back to "Chats"
3) Navigate to "Chats Detail"
4) Press back arrow
5) You are now on the "Projects" screen, even though you were within the context of the "Chats" stack navigator when you went to "Chats Detail", which is a screen of the same name registered with both stacks. I would expect to have ended up on the "Chats" screen when pressing the back arrow.

One workaround we are using now is to pass the `{ unmountOnBlur: true }` option to drawer screens that are stacks which contain duplicate screen names.

```
"@react-navigation/stack": "5.14.3",
"react-native-reanimated": "1.13.0",
"@react-navigation/drawer": "5.12.4",
"@react-navigation/native": "5.9.3",
```

**Comment by satya164** [comment]
You should be more specific about where you want to navigate when navigating to nested screens https://reactnavigation.org/docs/nesting-navigators/#navigating-to-a-screen-in-a-nested-navigator

Generally we don't recommend to have screens with same name in multiple navigators.
