### ISSUE TITLE
[web] Space is added to title when navigating from a screen to another

### ISSUE THREAD

**Issue by ggunti** [react-navigation/react-navigation#9461]
**Current Behavior**

This happens ONLY on web.

As you can see in the video below, if I navigate from the main screen to an another screen, an additional space is added to the title at the left side in header. But if I reload the page, the additional space disappears. It is a strange behavior.

https://user-images.githubusercontent.com/26307699/112605806-5de02380-8e20-11eb-9a43-bb3c8969ee84.mov

**Expected Behavior**

Just do not add the additional left space to the title when navigating from a screen to another.

**How to reproduce**

I use `react-native-web` without expo.

The `App.js` file:
```
import 'react-native-gesture-handler';
import React from 'react';
import { View } from 'react-native';
import { Button } from 'react-native-elements';
import { NavigationContainer } from '@react-navigation/native';
import { createStackNavigator } from '@react-navigation/stack';

const Stack = createStackNavigator();

const linking = {
  prefixes: ['http://localhost:8080'],
  config: {
    screens: {
      home: 'home',
      preview: 'home/preview',
    },
  },
};

function Router() {
  return (
    <NavigationContainer linking={linking}>
      <Stack.Navigator>
        <Stack.Screen
          name='home'
          options={{ title: 'Home' }}
          component={({ navigation }) => (
            <View>
              <Button title='Navigate' onPress={() => navigation.navigate('preview')} />
            </View>
          )}
        />
        <Stack.Screen name='preview' options={{ title: 'Preview' }} component={() => <View />} />
      </Stack.Navigator>
    </NavigationContainer>
  );
}

export default function App() {
  return <Router />;
}
```

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |-
| @react-navigation/native       |5.9.3
| @react-navigation/stack        |5.14.3
| react-native-gesture-handler   |1.10.3
| react-native-safe-area-context |3.1.9
| react-native-screens           |2.18.1
| react-native                   |0.63.4
| expo                           |-
| node                           |12.16.3
| npm or yarn                    |npm (6.14.4)

**Comment by satya164** [comment]
That's not additional space. That's where the back button is supposed to be. Looks like the icons are not loading in your setup due to incorrect configuration.

**Comment by ggunti** [comment]
@satya164 Thank you! You are right, I did not observe that there should be the back button. Anyhow, I can't find out why the icon is not shown. I use `file-loader` for loading the `.png` files.

My `webpack.config.js` file:
```
const path = require('path');
const webpack = require('webpack');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const rootDir = path.join(__dirname, '..');
const webpackEnv = process.env.NODE_ENV || 'development';

module.exports = function (env) {
  return {
    mode: webpackEnv,
    entry: {
      app: path.join(rootDir, './index.web.ts'),
    },
    output: {
      path: path.resolve(rootDir, 'dist'),
      filename: 'app-[hash].bundle.js',
      publicPath: '/',
    },
    devtool: 'source-map',
    devServer: {
      historyApiFallback: true,
    },
    module: {
      rules: [
        {
          test: /\.(js|jsx|ts|tsx)$/,
          loader: 'babel-loader',
          include: [
            path.resolve(rootDir, 'src'),
            path.resolve(rootDir, 'node_modules/react-native-vector-icons'),
            path.resolve(rootDir, 'node_modules/react-native-elements'),
            path.resolve(rootDir, 'node_modules/react-native-ratings'),
            path.resolve(rootDir, 'node_modules/react-native-safe-area-context'),
          ],
          options: {
            presets: ['module:metro-react-native-babel-preset'],
          },
        },
        {
          test: /\.(ttf|png)$/,
          loader: 'file-loader',
          include: [
            path.resolve(rootDir, 'node_modules/react-native-vector-icons'),
            path.resolve(rootDir, 'node_modules/react-native-elements'),
            path.resolve(rootDir, 'node_modules/react-native-ratings'),
            path.resolve(rootDir, 'node_modules/@react-navigation/stack'),
          ],
        },
        {
          test: /\.css$/i,
          use: ['style-loader', 'css-loader'],
        },
      ],
    },
    plugins: [
      new HtmlWebpackPlugin({
        template: path.join(__dirname, './index.html'),
      }),
      new webpack.HotModuleReplacementPlugin(),
    ],
    resolve: {
      extensions: ['.web.tsx', '.web.ts', '.tsx', '.ts', '.web.jsx', '.web.js', '.jsx', '.js'], // read files in following order
      alias: Object.assign({
        'react-native$': 'react-native-web',
        'react-native-vector-icons$': 'react-native-vector-icons/dist',
      }),
    },
  };
};
```

As a temporary solution, I added `headerBackImage: () => <Icon name='arrow-back' type='material' />` to the stack navigator and now I have a back button also on web.

**Comment by raajnadar** [comment]
Follow this steps https://github.com/oblador/react-native-vector-icons#web-with-webpack

**Comment by ggunti** [comment]
@raajnadar I followed those steps, here is my `index.web.ts` file:
```
import { AppRegistry } from 'react-native';
import app from './app.json';
import App from './src/App';

/* START react-native-vector-icons SETUP */

// Generate required css
// @ts-ignore
import fontAwesomeFont from 'react-native-vector-icons/Fonts/FontAwesome.ttf';
// @ts-ignore
import featherFont from 'react-native-vector-icons/Fonts/Feather.ttf';
// @ts-ignore
import materialFont from 'react-native-vector-icons/Fonts/MaterialIcons.ttf';

const fontAwesomeFontStyles = `@font-face {
  src: url(${fontAwesomeFont});
  font-family: FontAwesome;
}`;

const featherFontStyles = `@font-face {
  src: url(${featherFont});
  font-family: Feather;
}`;

const materialFontStyles = `@font-face {
  src: url(${materialFont});
  font-family: MaterialIcons;
}`;

// Create stylesheet
const style = document.createElement('style');
style.type = 'text/css';
style.appendChild(document.createTextNode(fontAwesomeFontStyles));
style.appendChild(document.createTextNode(featherFontStyles));
style.appendChild(document.createTextNode(materialFontStyles));

// Inject stylesheet
document.head.appendChild(style);

/* END react-native-vector-icons SETUP */

const appName = app.name;

AppRegistry.registerComponent(appName, () => App);

AppRegistry.runApplication(appName, {
  initialProps: {},
  rootTag: document.getElementById('app-root'),
});
```

**Comment by tranhiepqna** [comment]
Hi @ggunti, have you fixed your issue?  I'm facing the same issue when trying to use React Navigation on the web.

**Comment by tranhiepqna** [comment]
After an investigating day, I realize that @react-navigation/stack uses a local image to render the back icon. So you can use Webpack loader to include the local images into your bundling process. Add new loader in your Webpack configuration: 

```
module.exports =  {
  ...
  module: { 
     rules: {
         ...
         {
            test: /\.(jpg|png)$/,
            use: {
                  loader: 'url-loader',
            },
            options: {
                esModule: false,
            }
        }
     }
  }
}
````

**Comment by ElForastero** [comment]
I can confirm that buttons are loaded as base64 png images, not as svg.

If you are using cra, then you can patch webpack config this way:

```js
const reactScriptsRules = config.module.rules[1];
const imgRule = reactScriptsRules.oneOf.find(
    rule => rule.loader && rule.loader.includes('url-loader')
);
imgRule.options.esModule = false;
```

Without setting the `esModule` option to false it wouldn't work.

**Comment by leonineli** [comment]
我使用的是react-app-rewired，配置了config-overrides.js解决了这个问题：
const {override, addWebpackModuleRule} = require('customize-cra');

module.exports = override(
  addWebpackModuleRule({
    test: /\.(jpg|png)$/,
    loader: require.resolve('url-loader'),
    options: {
      esModule: false,
    },
  }),
);

**Comment by leonineli** [comment]
如果使用了react-app-rewired和customize-cra，配置config-overrides.js可解决此问题：
const {override, addWebpackModuleRule} = require('customize-cra');

module.exports = override(
  addWebpackModuleRule({
    test: /\.(jpg|png)$/,
    loader: require.resolve('url-loader'),
    options: {
      esModule: false,
    },
  }),
);

**Comment by ElForastero** [comment]
@leonineli Please, use English. It's a common language and everyone will be able to understand and help you.

**Comment by hymced** [comment]
> I can confirm that buttons are loaded as base64 png images, not as svg.
> 
> If you are using cra, then you can patch webpack config this way:
> 
> ```js
> const reactScriptsRules = config.module.rules[1];
> const imgRule = reactScriptsRules.oneOf.find(
>     rule => rule.loader && rule.loader.includes('url-loader')
> );
> imgRule.options.esModule = false;
> ```
> 
> Without setting the `esModule` option to false it wouldn't work.

This did not work for me because there was 2 rules with `url-loader` but with different `test` properties:
`test: [/\.avif$/],`
`test: [/\.bmp$/, /\.gif$/, /\.jpe?g$/, /\.png$/],`

This solution was only targetting the first one, on so not solving the issue with the back icon since it is a .png
In the end, I changed them all because [the issue affects all types of images](https://github.com/react-navigation/react-navigation/issues/8996#issuecomment-1824242686):

```
module.exports = function override(config, env) {
  const reactScriptsRules = config.module.rules[1];
  const urlLoaderRules = reactScriptsRules.oneOf.filter(
    rule => rule.loader && rule.loader.includes('url-loader'),
  );
  urlLoaderRules.forEach(urlLoaderRule => {
    urlLoaderRule.options.esModule = false;
  });
  return config;
};
```
