### ISSUE TITLE
Header Bar button is not tappable in Android

### ISSUE THREAD

**Issue by aadityapaliwal94** [react-navigation/react-navigation#9462]
**Current Behavior**

Header button is not tappable in Android.

**Expected Behavior**

They should tappable as iOS

**How to reproduce**

I am using react-navigation v5. In my Stack screen, I am using custom header, it's showing correctly but I am not able to tap on any buttons. iOS works fine for the same code.

**Current Behavior**

Header button is not tappable in Android.

**Expected Behavior**

They should tappable as iOS

**How to reproduce**

I am using react-navigation v5. In my Stack screen, I am using custom header, it's showing correctly but I am not able to tap on any buttons. iOS works fine for the same code.

const HomeStack = () => {
  return (
    <Stack.Navigator mode='card' headerMode={"screen"} screenOptions={{
      cardStyleInterpolator: CardStyleInterpolators.forHorizontalIOS
    }}>
      <Stack.Screen name='Home' component={Reader} options={({ route, navigation }) => ({ title: "Comic", headerShown:true, header: () => (<HeaderBar route={route} navigation={navigation} />) })} />
    </Stack.Navigator>
  )
}

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Android
| @react-navigation/native       | ^5.9.3
| react-native                   | 0.63.3
| expo                           | 
| node                           | 13.11.0
| npm or yarn                    | 7.5.6

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Android
| @react-navigation/native       | ^5.9.3
| react-native                   | 0.63.3
| expo                           | 
| node                           | 13.11.0
| npm or yarn                    | 7.5.6

**Comment by cainaleaouk** [comment]
@aadityapaliwal94  did you ever find a solution for this issue? I'm facing the same
