### ISSUE TITLE
StackNavigationProp not accepting strings on second generic param (RouteName)

### ISSUE THREAD

**Issue by nestorvanz** [react-navigation/react-navigation#9467]
**Current Behavior**

Creating `NavigationProp` for a screen:

The second generic param `RouteName` does not accept `string` type. See attachment.
```
type ProfileScreenNavigationProp = StackNavigationProp<{}, 'Profile'>;
```

![image](https://user-images.githubusercontent.com/12944703/112714702-d256a900-8e98-11eb-8465-e3b778d129be.png)

**Expected Behavior**

StackNavigationProp second generic param to accepts string values (RouteName).

**Your Environment**

@react-navigation/stack: v5.14.3

**Comment by nestorvanz** [comment]
@react-navigation/native:5.9.3

**Comment by satya164** [comment]
You need to pass a list of screens https://reactnavigation.org/docs/typescript/#type-checking-screens
