### ISSUE TITLE
Drawer menu not open from right the furthest after re-lunch app

### ISSUE THREAD

**Issue by mohamedanwer123** [react-navigation/react-navigation#9468]
Drawer menu not open from right the furthest after re-lunch app

"@react-navigation/drawer": "^5.12.4",
"@react-navigation/native": "^5.9.3",
"@react-navigation/stack": "^5.14.3",

const SideMenu = () => {

    const isRTL = useSelector(state=>state.lang.isRTL)

    return (
    <Menu.Navigator
        drawerContent={(props) => <SideMenuContent {...props} />}
        drawerPosition={isRTL?'right':'left'}
    >
        <Menu.Screen name='SideMenu1' component={SideMenu1} />
        <Menu.Screen name='SideMenu2' component={SideMenu2} />
    </Menu.Navigator>
    )

}

**Comment by okwasniewski** [comment]
Please follow the issue template. Closing this
