### ISSUE TITLE
App crashes on Android after adding React-Navigation using Expo

### ISSUE THREAD

**Issue by Wiingless** [react-navigation/react-navigation#9469]
**Current Behavior**

The app keeps crashing after adding the react-navigation/native and react-navigation/stack

Please see below my configuration:
**app.json**
{
  "expo": {
    "name": "TestApp",
    "slug": "TestApp",
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": true
    },
    "android": {
      "adaptiveIcon": {
        "foregroundImage": "./assets/adaptive-icon.png",
        "backgroundColor": "#FFFFFF"
      }
    },
    "web": {
      "favicon": "./assets/favicon.png"
    }
  }
}

**package.json**
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "@react-native-community/masked-view": "0.1.10",
    "@react-navigation/native": "^5.9.3",
    "@react-navigation/stack": "^5.14.3",
    "expo": "~40.0.0",
    "expo-status-bar": "~1.0.3",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz",
    "react-native-gesture-handler": "~1.8.0",
    "react-native-reanimated": "~1.13.0",
    "react-native-safe-area-context": "3.1.9",
    "react-native-screens": "~2.15.2",
    "react-native-web": "~0.13.12"
  },
  "devDependencies": {
    "@babel/core": "^7.9.0"
  },
  "private": true
}

**Expected Behavior**
I would like the app not to crash

**How to reproduce**

https://snack.expo.io/W-vyZZGo_

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Android
| @react-navigation/native       | "^5.9.3",
| react-native                   | "https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz"
| expo                           |"~40.0.0"
| node                           |
| npm or yarn                    |npm

**Comment by raajnadar** [comment]
Make sure you are not using reanimated v2.

**Comment by Wiingless** [comment]
> Make sure you are not using reanimated v2.

I'm using "react-native-reanimated": "~1.13.0"

**Comment by raajnadar** [comment]
```
<Stack.Navigator>
    <Stack.Screen name="Tweets" component={Tweets} />
    <Stack.Screen name="TweetDetails" component={TweetDetails} />
</Stack.Navigator>
```

You forgot to add . (Dot) between Stack & navigator.

**Comment by Kyuube** [comment]
> ```
> <Stack.Navigator>
>     <Stack.Screen name="Tweets" component={Tweets} />
>     <Stack.Screen name="TweetDetails" component={TweetDetails} />
> </Stack.Navigator>
> ```
> Thank you very much, I could not 




> ```
> <Stack.Navigator>
>     <Stack.Screen name="Tweets" component={Tweets} />
>     <Stack.Screen name="TweetDetails" component={TweetDetails} />
> </Stack.Navigator>
> ```
> 
> You forgot to add . (Dot) between Stack & navigator.
> 
> Fix here https://snack.expo.io/@raajnadar/e73bce

Thanks a lot for this. I wonder why it was just crashing and not giving me an error message. Anyway, thanks!
