### ISSUE TITLE
TypeError: null is not an object (evaluating '_ReanimatedModule.default.createNode')

### ISSUE THREAD

**Issue by jobn123** [react-navigation/react-navigation#9470]
### Current behaviour

TypeError: null is not an object (evaluating '_ReanimatedModule.default.createNode')

### Expected behaviour

when use react-navigation if use Stack works well but use Drawer got wrong

### Code sample

```javascript
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 *
 * Generated with the TypeScript template
 * https://github.com/react-native-community/react-native-template-typescript
 *
 * @format
 */
// import 'react-native-gesture-handler';
import * as React from 'react';
import {
  Text,
  View,
  Button
} from 'react-native';

import { createDrawerNavigator } from '@react-navigation/drawer';
import { NavigationContainer } from '@react-navigation/native';

function HomeScreen({ navigation }) {
  return (
    <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
      <Text>Home Screen</Text>
      <Button
          title="Go to Details... again"
          onPress={() => navigation.navigate('Details')}
        />
    </View>
  );
}

function DetailsScreen() {
  return (
    <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
      <Text>Details Screen</Text>
    </View>
  );
}

const Drawer = createDrawerNavigator();

const App = () => {
  return (
    <NavigationContainer>
      <Drawer.Navigator initialRouteName="Home">
        <Drawer.Screen name="Home" component={HomeScreen} />
        <Drawer.Screen name="Details" component={DetailsScreen} />
      </Drawer.Navigator>
    </NavigationContainer>
  );
};

export default App;

```

### Your Environment

| software                     | version
| ---------------------------- | -------
| ios              | 
| expo                         | ^40.0.1
| react-native                 | 0.64.0
| @react-navigation/native        | 5.9.3
| @react-navigation/drawer     | 5.12.4
| node                         |  v15.2.1
| npm or yarn                  | npm

**Comment by raajnadar** [comment]
which version of reanimated you are using?

**Comment by jobn123** [comment]
sorry i lost react-native-reanimated dependency.

**Comment by jobn123** [comment]
> which version of reanimated you are using?

sorry i lost react-native-reanimated dependency.

**Comment by jeremyrajan** [comment]
I have the same issue, 

![image](https://user-images.githubusercontent.com/2890683/131209911-66d3f84b-7107-43d9-8710-d6fde3a8cdb1.png)

how do we fix this? @jobn123

**Comment by abhigenva** [comment]
Hello, I am also experiencing the same issue, did you get it resolved @jeremyrajan 
"dependencies": {
      "@react-navigation/drawer": "^6.1.4",
      "@react-navigation/native": "^6.0.2",
      "@react-navigation/native-stack": "^6.1.0",
      "react": "17.0.2",
      "react-native": "0.65.1",
      "react-native-gesture-handler": "^1.10.3",
      "react-native-reanimated": "^2.2.0",
      "react-native-safe-area-context": "^3.3.0",
      "react-native-screens": "^3.6.0"
  },

**Comment by amrahmed-swe** [comment]
> Hello, I am also experiencing the same issue, did you get it resolved @jeremyrajan
> 
> ```
> "dependencies": {
>       "@react-navigation/drawer": "^6.1.4",
>       "@react-navigation/native": "^6.0.2",
>       "@react-navigation/native-stack": "^6.1.0",
>       "react": "17.0.2",
>       "react-native": "0.65.1",
>       "react-native-gesture-handler": "^1.10.3",
>       "react-native-reanimated": "^2.2.0",
>       "react-native-safe-area-context": "^3.3.0",
>       "react-native-screens": "^3.6.0"
>   },
> ```

Did you solve it? because i have the same issue

**Comment by nehaejaz** [comment]
> I have the same issue,
> 
> ![image](https://user-images.githubusercontent.com/2890683/131209911-66d3f84b-7107-43d9-8710-d6fde3a8cdb1.png)
> 
> how do we fix this? @jobn123

having the same issue :/

**Comment by naimachokri** [comment]
hey i'm getting the same issue

![dep](https://user-images.githubusercontent.com/89871501/148664574-174a2347-d848-4b77-bdf2-a18374170503.png)

**Comment by raajnadar** [comment]
Add reanimated and clear the cache with `expo start -c`

**Comment by Haukez** [comment]
Why is this closed? Just follow the installation guide for drawer and you will get an error.
null is not an object (evaluating '_ReanimatedModule.default.createNode')
As soon as you import createDrawerNavigator it breaks

**Comment by bobokeke0** [comment]
if multiple people are facing it, I don't think it's one specific codebase causing it

**Comment by yaser-elbatal** [comment]
I have the same issue,

**Comment by Mortle** [comment]
having the same issue
