### ISSUE TITLE
Header from previous screen does not dissappear

### ISSUE THREAD

**Issue by ihsanktmr** [react-navigation/react-navigation#9492]
**Current Behavior**

When I navigate another screen in stack, the header that i customized does not dissappear, it stays, so I can't use another customized header in the screen I navigated

**Expected Behavior**

Previous header should dissappear and I should be able to use new one 

![beforetransparent](https://user-images.githubusercontent.com/26416028/114299396-7e1c0d80-9ac3-11eb-85ce-f6e7667a011d.png)
![aftertransparent](https://user-images.githubusercontent.com/26416028/114299392-7b211d00-9ac3-11eb-8c3b-51d83ad43ded.png)

Below is how my stack func looks like 
```
const ExploreStackScreen = () => (
  <ExploreStack.Navigator>
    <ExploreStack.Screen
      name={Route.EXPLORE}
      options={{
        header: props => <ExploreHeader {...props} />,
      }}
      component={ExploreScreen}
    />
    <ExploreStack.Screen
      name={Route.DETAILEDITEM}
      options={{
        headerTransparent: true,// if I set headerShown: false icon form previous header(<ExploreHeader>) still appears
      }}
      component={DetailedHorizontalItem}
    />
  </ExploreStack.Navigator>
);
```

**Your Environment**

    "@react-navigation/bottom-tabs": "^5.11.8",
    "@react-navigation/native": "^6.0.0-next.1",
    "@react-navigation/stack": "^5.14.3",   
    "react": "17.0.1",
    "react-native": "0.64.0",
    "react-native-elements": "^3.3.2",
    "react-native-gesture-handler": "^1.10.3",
    "react-native-reanimated": "^2.0.1",
    "react-native-safe-area-context": "^3.2.0",
    "react-native-screens": "^2.18.1",

**Comment by ihsanktmr** [comment]
Yes, I have just upgraded, problem remains

**Comment by raajnadar** [comment]
When you use custom header use `headerMode: screen` https://reactnavigation.org/docs/stack-navigator/#header
