### ISSUE TITLE
Same routeName on different conditional rendering not re-rendering [Following Auth Flow Docs]

### ISSUE THREAD

**Issue by zxccvvv** [react-navigation/react-navigation#9497]
**Current Behavior**

Working on [Auth Flow](https://reactnavigation.org/docs/auth-flow), cannot handle `Global screen component (e.g. PIN, OTP, Global Result Modal)` or same `routeName` but in different conditional rendering

**Expected Behavior**

Should be re-rendering on same `routeName` but in different conditional

**How to reproduce**

<details>
<summary>App.js</summary>

```
import { NavigationContainer } from '@react-navigation/native';
import { createStackNavigator } from '@react-navigation/stack';
import React from 'react';
import { Button, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

const AuthContext = React.createContext();

function SkeletonScreen({currentScreen, buttonName, buttonOnPress}){
  return(
    <SafeAreaView style={{flex:1}}>
      <View style={{flex:1, justifyContent:'center', alignItems:'center'}}>
        <Text>{currentScreen}</Text>
        <Button
          title={buttonName}
          onPress={buttonOnPress}
        />
      </View>
    </SafeAreaView>
  )
}

const Home = ({navigation})=>{
  return <SkeletonScreen currentScreen='Home' buttonName='SignOut' buttonOnPress={()=>React.useContext(AuthContext).signOut} />
}
const Login = ({navigation})=>{
  return <SkeletonScreen currentScreen='Login' buttonName='navigate to OTP' buttonOnPress={()=>navigation.navigate('OTP')} />
}

const OTP = ({navigation})=>{
  const { signIn } = React.useContext(AuthContext);
  return <SkeletonScreen currentScreen='OTP' buttonName='UseContext SignIn' buttonOnPress={()=>signIn('Has Login')} />
}

export default ()=>{
  const Stack = createStackNavigator()

  const [state, dispatch] = React.useReducer(
    (prevState, action) => {
      switch (action.type) {
        case 'RESTORE_TOKEN':
          return {
            ...prevState,
            userToken: action.token,
            isLoading: false,
          };
        case 'SIGN_IN':
          return {
            ...prevState,
            isSignout: false,
            userToken: action.token,
          };
      }
    },
    {
      isLoading: true,
      isSignout: false,
      userToken: null,
    }
  );

  React.useEffect(() => {
    const bootstrapAsync = async () => {
      dispatch({ type: 'RESTORE_TOKEN', token: null });
    };

    bootstrapAsync();
  }, []);

  const authContext = React.useMemo(
    () => ({
      signIn: async data => {
        dispatch({ type: 'SIGN_IN', token: 'dummy-auth-token' });
      },
      signOut: () => dispatch({ type: 'SIGN_OUT' }),
      signUp: async data => {
        dispatch({ type: 'SIGN_IN', token: 'dummy-auth-token' });
      },
    }),
    []
  );
  
  return(
    <AuthContext.Provider value={authContext}>
      <NavigationContainer>
        <Stack.Navigator>
          {state.userToken == null ? (
            <>
            <Stack.Screen name="Login" component={Login}/>
            <Stack.Screen name="OTP" component={OTP}/>
            </>
          ) : (
            <>
            <Stack.Screen name="Home" component={Home} />
            <Stack.Screen name="OTP" component={OTP}/>
            </>
          )}
        </Stack.Navigator>
      </NavigationContainer>
    </AuthContext.Provider>
  )
}
```

</details>

<details>
<summary>Video</summary>

https://user-images.githubusercontent.com/19633881/114488492-ab8bc700-9c3b-11eb-931d-987500aee2f6.mov

</details>

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Both
| @react-navigation/native       | 5.9.3
| react-native                   | 0.63.4
| expo                           | RN Init
| node                           | v12.18.4
| npm or yarn                    | 6.14.6

**Comment by satya164** [comment]
Repeating it in 2 different conditional doesn't make a difference. It's essentially same as that screen being outside the conditional. If you need to navigate after signing in from such a common screen, you need to navigate manually. React Navigation cannot handle it automatically.

**Comment by zxccvvv** [comment]
> you need to navigate manually

@satya164 I have tried what you said before posting this issue, but React Navigation doesn't know if `PIN` screen is from `userToken == null` or not

as far as I know here's the flow of React Navigation running on conditional rendering:

1. on reload/ first open the app, I'm force `userToken` value to null so React Navigation have an array of `routeName` ['Login', 'PIN']
2. on `Login` navigate to `PIN`, which is the same array of `routeName`
3. on `PIN` I use `context.signIn` and `navigation.navigate('Home')`

the problem is React Navigation only have 2 array of `routeName` at first, so navigating to `Home` will throw an Error `There is no route defined for key Home. Must be one of: Login, OTP` or something like that

**Comment by satya164** [comment]
> React Navigation doesn't know if PIN screen is from userToken == null or not

It cannot. It's just a difference in your source code, from runtime perspective they are the same thing.

> so navigating to Home will throw an Error There is no route defined for key Home. Must be one of: Login, PIN or something like that

You can add a `useEffect` inside your `App.js` with `userToken` in dependency array and then navigate there. That should work.
