### ISSUE TITLE
When deeplink do open app application fail with 'navigation' object hasn't been initialized yet

### ISSUE THREAD

**Issue by RigottiG** [react-navigation/react-navigation#9500]
**Current Behavior**

- What code are you running and what is happening?

When I open the application through deeplink, if the user is logged out, a navigate is made to `AuthStack`, but the following error happens

> Error: The 'navigation' object hasn't been initialized yet. This might happen if you don't have a navigator mounted, or if the navigator hasn't finished mounting.

**Expected Behavior**

- What do you expect should be happening?
Do not trigger the error when opening the app via deeplink

**How to reproduce**

- Open app via DeepLink
- Made a navigate

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Both
| @react-navigation/native       |  5.9.2
| react-native                   | 0.63.4
| node                           | 15
| npm or yarn                    | both

**Comment by RigottiG** [comment]
> The versions mentioned in the issue for the following packages differ from the latest versions on npm:
> 
> * `@react-navigation/native` (found: `5.9.2`, latest: `5.9.4`)
> 
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?

Still facing issue with `5.9.4`

**Comment by ngtrhieu** [comment]
Hey! Thanks for opening the issue. The issue doesn't seem to contain a link to a repro (a [snack.expo.io](snack.expo.io) link or link to a GitHub repo under your username).

Can you provide a [minimal repro](https://stackoverflow.com/help/minimal-reproducible-example) which demonstrates the issue? A repro will help us debug the issue faster. Please try to keep the repro as small as possible and make sure that we can run it without additional setup.
