### ISSUE TITLE
headerLeft for RTL App

### ISSUE THREAD

**Issue by aliwaqar981** [react-navigation/react-navigation#9503]
**Current Behavior**
- headerLeft is on left side just like in LTR apps

**Expected Behaviour**
- It should be reversed.

- Code Snippet
  `useLayoutEffect(() => {
    navigation.setOptions({
      headerLeft: () => (
        <TouchableOpacity
          activeOpacity={0.5}
          onPress={() => navigation.goBack()}
          style={Style.iconContainer}>
          <Icon
            color={Colors.primary}
            name="chevron-left"
            type="font-awesome"
            size={24}
          />
        </TouchableOpacity>
      ),
    });
  }, []);`
  
- Screenshot
![image](https://user-images.githubusercontent.com/43547698/114826978-8fc22580-9de1-11eb-8b34-2d8673b8888b.png)

**How to reproduce**
- Step1: Install react navigation and add some screens in the app
- Step2: Paste below code in any screen
`
useLayoutEffect(() => {
    navigation.setOptions({
      headerLeft: () => (
        <TouchableOpacity
          activeOpacity={0.5}
          onPress={() => navigation.goBack()}
          style={Style.iconContainer}>
          <Icon
            color={Colors.primary}
            name="chevron-left"
            type="font-awesome"
            size={24}
          />
        </TouchableOpacity>
      ),
    });
  }, []);
`
-Step3: Paste below code in App.tsx
`import {I18nManager, ViewStyle} from 'react-native';
I18nManager.forceRTL(true);
`
- Step4: Restart the app

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| @react-navigation/native    |  5.9.3
| @react-navigation/stack      |  5.12.8
| react-native-gesture-handler  |  ^1.8.0
| react-native            |  0.63.3
| node                        | 14.16.0
| npm or yarn            | 1.22.4

**Comment by satya164** [comment]
React Navigation works fine with RTL. I'm not sure why you're doing `I18nManager.forceRTL(!I18nManager.isRTL)` which basically toggles RTL again after you restart the app which is gonna mess up things.

**Comment by aliwaqar981** [comment]
@satya164 my bad I wrote toggle mistakenly. Updated issue now but still react navigation header is not flipping like remaining layout.

**Comment by a-eid** [comment]
@aliwaqar981 it might help to remove your app complete and clear the cache then reinstall it.

**Comment by aliwaqar981** [comment]
yes I have done that and it's working fine now. Thanks
