### ISSUE TITLE
popping back when parent/previous component's state gets updated

### ISSUE THREAD

**Issue by maifeeulasad** [react-navigation/react-navigation#9509]
**Current Behavior**

But then problem is when I update value from cart-screen, it returns back to home-screen(previous screen of cart-screen). Maybe there is something like, when parent's state gets updated child gets popped up.

**Expected Behavior**

It shouldn't pop up.

**How to reproduce**

Complete GitHub repo is here : https://github.com/maifeeulasad/Free-Cart-Client

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Android
| @react-navigation/native       | ^5.9.4
| @react-navigation/stack        | ^5.14.4
| react-native-gesture-handler   | ~1.8.0
| react-native-safe-area-context | ^3.2.0
| react-native-screens           | ~2.15.0
| react-native                   | ~0.63.4
| expo                           | ~40.0.0
| node                           | v14.15.4
| npm or yarn                    | yarn

sof : https://stackoverflow.com/q/67123932/10305444

**Comment by ngtrhieu** [comment]
Cloned and tested. Nothing to do with this package. Check your own code for the problem.

Can close this issue 🙇‍♂️ 

_Hint: Check your own `useEffect`_
