### ISSUE TITLE
undefined is not an object (evaluating '_$$_REQUIRE(_dependencyMap[7], "@react-navigation/native").NavigationHelpersContext.Provider')

### ISSUE THREAD

**Issue by Krish143git** [react-navigation/react-navigation#9510]
**Current Behavior**

I am Using React native cli,Today i created a new project  and installed following packages But bottom is not showing giving error Here i wrapped the Navigator,screen with NavigationContainer But in below code it is not showing
 

import React from 'react';
import { NavigationContainer } from '@react-navigation/native';
import { createMaterialBottomTabNavigator } from '@react-navigation/material-bottom-tabs';
import PricesScreen from './Screens/PricesScreen';

const Tab = createMaterialBottomTabNavigator();
const App = () => {
  return (
    <>
    <NavigationContainer>
      <Tab.Navigator>
        <Tab.Screen name="Home" component={PricesScreen} />    
      </Tab.Navigator>
    </NavigationContainer>
    </>
  )
}
export default App;

Error =
 ERROR  TypeError: undefined is not an object (evaluating '_$$_REQUIRE(_dependencyMap[7], "@react-navigation/native").NavigationHelpersContext.Provider')

This error is located at:
    in MaterialBottomTabView (at createMaterialBottomTabNavigator.tsx:45)
    in MaterialBottomTabNavigator (at App.js:11)
    in EnsureSingleNavigator (at BaseNavigationContainer.tsx:409)
    in BaseNavigationContainer (at NavigationContainer.tsx:91)
    in ThemeProvider (at NavigationContainer.tsx:90)
    in NavigationContainer (at App.js:10)
    in App (at renderApplication.js:47)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:107)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:134)
    in AppContainer (at renderApplication.js:40)
 ERROR  TypeError: undefined is not an object (evaluating '_$$_REQUIRE(_dependencyMap[7], "@react-navigation/native").NavigationHelpersContext.Provider')

This error is located at:
    in MaterialBottomTabView (at createMaterialBottomTabNavigator.tsx:45)
    in MaterialBottomTabNavigator (at App.js:11)
    in EnsureSingleNavigator (at BaseNavigationContainer.tsx:409)
    in BaseNavigationContainer (at NavigationContainer.tsx:91)
    in ThemeProvider (at NavigationContainer.tsx:90)
    in NavigationContainer (at App.js:10)
    in App (at renderApplication.js:47)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:107)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:134)
    in AppContainer (at renderApplication.js:40)

**Your Environment**
   "@react-native-community/toolbar-android": "0.1.0-rc.2",
    "@react-navigation/material-bottom-tabs": "^5.3.15",
    "@react-navigation/native": "^5.9.4",
    "react": "17.0.1",
    "react-native": "0.64.0",
    "react-native-paper": "^4.7.2",
    "react-vector-icons": "0.0.1"

**Comment by Krish143git** [comment]
Please any one help me to solve the issue

**Comment by pokenrike** [comment]
what is de soluction?

**Comment by pokenrike** [comment]
which is the solution?

**Comment by Osamasomy** [comment]
I have same issue whats the solution.
i just download @react-navigation/material-top-tabs and face the same error.
