### ISSUE TITLE
Allow disabling BackHandler subscription in DrawerView

### ISSUE THREAD

**Issue by marcaaron** [react-navigation/react-navigation#9511]
**Current Behavior**

The current back handling behavior in the `DrawerView` when the screen is focused is to close or open the drawer. This behavior cannot be overridden by a screen in a `Drawer.Navigator`. According to the docs,

>Custom back button handling in other situations may not be supported at the moment (eg. A known case when this does not work is when you want to handle back button press in an open drawer. PRs for such use cases are welcome!).

**Expected Behavior**

`DrawerView` can be made more extensible by disabling the default `BackHandler` subscription entirely.

e.g. one should be able to delegate `BackHandler` responsibility to a Screen and determine whether to open the drawer or exit the application

**How to reproduce**

Attempt to add a `BackHandler` in a drawer screen observe it does not handle events.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |
| @react-navigation/native       |
| @react-navigation/drawer       |
| react-native-reanimated        |
| react-native-gesture-handler   |
| react-native-safe-area-context |
| react-native-screens           |
| react-native                   |
| expo                           |
| node                           |
| npm or yarn                    |

**Comment by marcaaron** [comment]
Curious if we would accept a PR that adds an `enableBackHandler` prop with a default of `true` to the `DrawerView` options? 

Or perhaps there is a better way this should be approached?

```diff
diff --git a/packages/drawer/src/views/DrawerView.tsx b/packages/drawer/src/views/DrawerView.tsx
index 869a1eda..0323aa7c 100644
--- a/packages/drawer/src/views/DrawerView.tsx
+++ b/packages/drawer/src/views/DrawerView.tsx
@@ -96,20 +96,21 @@ function DrawerViewBase({
     drawerStyle,
     drawerType = Platform.select({ ios: 'slide', default: 'front' }),
     gestureHandlerProps,
     keyboardDismissMode = 'on-drag',
     overlayColor = 'rgba(0, 0, 0, 0.5)',
     swipeEdgeWidth = 32,
     swipeEnabled = Platform.OS !== 'web' &&
       Platform.OS !== 'windows' &&
       Platform.OS !== 'macos',
     swipeMinDistance = 60,
+    enableBackHandler = true,
   } = descriptors[focusedRouteKey].options;

   const [loaded, setLoaded] = React.useState([focusedRouteKey]);

   if (!loaded.includes(focusedRouteKey)) {
     setLoaded([...loaded, focusedRouteKey]);
   }

   const dimensions = useSafeAreaFrame();

@@ -150,37 +151,42 @@ function DrawerViewBase({

     const handleEscape = (e: KeyboardEvent) => {
       if (e.key === 'Escape') {
         handleClose();
       }
     };

     // We only add the listeners when drawer opens
     // This way we can make sure that the listener is added as late as possible
     // This will make sure that our handler will run first when back button is pressed
-    const subscription = BackHandler.addEventListener(
-      'hardwareBackPress',
-      handleClose
-    );
+    const subscription = enableBackHandler
+      ? BackHandler.addEventListener('hardwareBackPress', handleClose)
+      : undefined;

     if (Platform.OS === 'web') {
       document?.body?.addEventListener?.('keyup', handleEscape);
     }

     return () => {
-      subscription.remove();
+      subscription?.remove();

       if (Platform.OS === 'web') {
         document?.body?.removeEventListener?.('keyup', handleEscape);
       }
     };
-  }, [drawerStatus, drawerType, handleDrawerClose, navigation]);
+  }, [
+    drawerStatus,
+    drawerType,
+    handleDrawerClose,
+    navigation,
+    enableBackHandler,
+  ]);
```

**Comment by ngtrhieu** [comment]
Just to clarify, if `handleDrawerClose` is false, that screen component would need to handle the backButtonPress by themselves?

**Comment by marcaaron** [comment]
Right, we would pass something like `enableBackHandler={false}` to the drawer navigator and then you'd need to do a custom back button handler.

**Comment by ngtrhieu** [comment]
Have you tried this before? https://reactnavigation.org/docs/preventing-going-back
