### ISSUE TITLE
Cannot test tab navigation with Jest and Typescript

### ISSUE THREAD

**Issue by githorse** [react-navigation/react-navigation#9517]
**Current Behavior**

I'm unable to run tests using `bottom-tab-navigator` and typescript. Under my current configuration (I've tried lots), I get this error:

```
yarn run v1.22.10
$ jest
FAIL __tests__/App.spec.tsx
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/en/ecmascript-modules for how to enable it.
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /home/githorse/cod/TS3/node_modules/react-native-iphone-x-helper/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import { Dimensions, Platform, StatusBar } from 'react-native';
                                                                                             ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1350:14)
      at Object.<anonymous> (node_modules/@react-navigation/bottom-tabs/lib/commonjs/views/SafeAreaProviderCompat.tsx:7:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.107 s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Expected Behavior**

A passing test.

**How to reproduce**

`App.tsx`: identical to the [Minimal Example of Tab-based Navigation](https://reactnavigation.org/docs/tab-based-navigation#minimal-example-of-tab-based-navigation).

`jest.config.js`: identical to the [ts-jest](https://kulshekhar.github.io/ts-jest/docs/guides/react-native) recommendation (along with `babel.config.js`).

`setup.jest.js`: identical to the [Mocking Native Modules example](https://reactnavigation.org/docs/testing/#mocking-native-modules), except that the line `jest.mock('react-native/Libraries/Animated/src/NativeAnimatedHelper');` is commented out as it causes an (unrelated) error.

`App.spec.tsx`:

```
// __tests__/App.spec.tsx
import 'react-native';
import React from 'react';
import App from '../App';

// Note: test renderer must be required after react-native.
import renderer from 'react-test-renderer';

jest.useFakeTimers();

it('renders correctly', () => {
  renderer.create(<App />);
});
```

The issue is reproduced in [this Github repo](https://github.com/githorse/rn-testing-issue-example).

Note that all works as expected in the Android emulator; my issue is only with testing. Presumably this is an issue with Jest, Typescript, [ts-jest](https://github.com/kulshekhar/ts-jest) or my configuration thereof, not React Navigation per se. However, since the [React Navigation Testing With Jest docs](https://reactnavigation.org/docs/testing/#mocking-native-modules) allegedly cover testing with Jest, I'm listing it here in the hopes of getting some help and possibly updating the docs to cover the Typescript case.

**Your Environment**

| software                      | version |
| ----------------------------- | ------- |
| iOS or Android                | Android |
| @react-navigation/native      |^5.9.4
| @react-navigation/bottom-tabs |^5.11.10
| react-native-screens          |^3.1.1
| react-native                  |0.64.0
| expo                          |NA
| node                          |v14.16.1
| npm or yarn                   |yarn

**Comment by ngtrhieu** [comment]
Sound like this is the problem with `jest` and not `react-navigation`.

**Comment by satya164** [comment]
Jest already supports TypeScript by default. You don't need to configure ts-jest. Please open a new issue if it's still not working after removing ts-jest.
