### ISSUE TITLE
[iOS Only] Keyboard dismissed automatically on key press when input is in option title navigator screen

### ISSUE THREAD

**Issue by KrifaYounes** [react-navigation/react-navigation#9521]
https://user-images.githubusercontent.com/3875788/115415166-f6d34600-a1f6-11eb-8926-499b627c0f80.mov

*** Code ***

```
<Drawer.Navigator screenOptions={SCREEN_OPTIONS(theme)} >
            <Drawer.Screen
                name="Drawer"
                options={({ route }) => {
                    const routeName = getFocusedRouteNameFromRoute(route);
                    return {
                          headerTitleAlign: 'center',
                          title: <SearchBarComponent placeholder={translation('search')} />,
                   }
                }}
                component={BottomTabNavigator}
            />
        </Drawer.Navigator>

```

**Expected Behavior**

Don't dismiss keyboard on keyPress when input is in options title.

**How to reproduce**

https://snack.expo.io/B8RiLYptL

Add a input in options title 
Focus the input
Press a key
Keyboard is dismissed

**Your Environment**

    "@react-navigation/bottom-tabs": "^6.0.0-next.5",
    "@react-navigation/drawer": "^6.0.0-next.4",
    "@react-navigation/material-top-tabs": "^5.3.15",
    "@react-navigation/native": "^6.0.0-next.2",
    "@react-navigation/stack": "^6.0.0-next.9",
    "react": "17.0.1",
    "react-native": "0.64.0",

Reproduce in react navigation V5 and V6

**Comment by KrifaYounes** [comment]
Reproduce in react navigation V5 and V6

**Comment by KrifaYounes** [comment]
Reproduction link : https://snack.expo.io/B8RiLYptL

**Comment by ngtrhieu** [comment]
`title` is supposed to be a `string` and not a React.Element in the first place. if you want more customisation, you would need to provide a component inside `headerTitle`.

Check the doc here:
- https://reactnavigation.org/docs/stack-navigator/#title
- https://reactnavigation.org/docs/stack-navigator/#headertitle

Btw, the `headerTitle` accepts a Component (i.e: `View`, `Text`) and not a ReactElement (i.e: `<View />`, `<Text>hello</Text>`)

**Comment by KrifaYounes** [comment]
Ok thank you
