### ISSUE TITLE
`expo build:web` Build the application,  refresh the page 404

### ISSUE THREAD

**Issue by hoohooluuluu** [react-navigation/react-navigation#9523]
**Current Behavior**

- `expo build:web` Build the application, deploy to the server, or start the service with `npx serve` locally, refresh the page 404
- sense：

![initproduct4](https://user-images.githubusercontent.com/77035746/115642154-01075880-a34d-11eb-9e5c-b3e8cd8794df.gif)

**Expected Behavior**

- Refresh the page and stay on the current page.

**How to reproduce**

- `expo init myweb`  
- cd myweb `expo build:web`  
- cd web-build `npx serve`
- localhost:5000
- Refresh page 404

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                  | web
| @react-navigation/native      | "~5.8.10"
| react-native                  | "https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz"
| expo                          | "^41.0.0"
| node                         | v14.15.1
| npm  or yarn   | 6.14.11 1.22.10

**Comment by raajnadar** [comment]
I recently encountered this issue https://nextjs.org/docs/api-reference/next.config.js/trailing-slash

```
module.exports = {
  trailingSlash: true,
}
```

Keep in mind this is for static export. Add this flag and rebuild the application and test it.

**Comment by hoohooluuluu** [comment]
@raajnadar 
Do you mean it can only be deployed through Next.js?

**Comment by hoohooluuluu** [comment]
I have never been in contact with Next.js, and for me, there is no need to use it at the moment. Is there no other solution?

**Comment by raajnadar** [comment]
you need to add that configuration thats it. It seems like you are using expo web with nextjs

**Comment by hoohooluuluu** [comment]
> you need to add that configuration thats it. It seems like you are using expo web with nextjs

I just use 

> Step1. `expo init myweb` 
> Step2.  `cd myweb` 
> Step3. `expo build:web` 
> Step4.  `npx serve`. 

I am not using next.js.
This is an initial project, I haven't touched any code at all.
I suggest to reopen this problem, because there must be someone who has a similar problem with me, but this problem has not been resolved.

**Comment by raajnadar** [comment]
I already gave you a solution to fix this issue https://docs.expo.io/guides/using-nextjs/#config

add the trailingSlash flag.

`npx serve` is used to serve static exports. I am 100% sure you get 404 because of the structure of build which need to be configured. You are using client side routing when you refresh the page serve cmd cannot find your file that's why it returned 404.

https://github.com/vercel/next.js/discussions/13754

**Comment by carlosds731** [comment]
Hi,

This problem is not related to next.config.js (you don't need that file). It's related with this https://stackoverflow.com/questions/69713939/expo-react-native-issue-with-url-refreshing

The solution described in SO worked for me; i.e., modify the file `web-build/serve.json` as follows

````json
{
  "headers": [
    {
      "source": "static/**/*.js",
      "headers": [
        {
          "key": "Cache-Control",
          "value": "public, max-age=31536000, immutable"
        }
      ]
    }
  ],
  "rewrites": [
    { "source": "/**", "destination": "/index.html"}
  ]
}
````

**Comment by henrique25teles** [comment]
@carlosds731 This worked out for me.
There is some place I can configure this before run "npx expo export:web"
or everytime I build I have to change this file manually ?

**Comment by DimitarTumbalov** [comment]
@henrique25teles Here is how I made it work:
1. Run `npx expo customize` in the terminal.
2. Select `web/serve.json` with **Space** from the shown options and press **Enter**.
3. Open the generated file `serve.json` inside the `web` folder (it's in the root directory) and add the required code to the file.
```json
{
  "headers": [
    {
      "source": "static/**/*.js",
      "headers": [
        {
          "key": "Cache-Control",
          "value": "public, max-age=31536000, immutable"
        }
      ]
    }
  ],
  "rewrites": [
    { "source": "/**", "destination": "/index.html"}
  ]
}
```

Now, when you run `npx expo export:web` the generated serve file will match this one! :sunglasses:

**Comment by jfbourne** [comment]
I am experiencing the same issue here except that I have a second route. Let me explain

1. I land on myapp.com which loads the index.html
2. index.html is my login page which then sends me to /dashboard using `router.replace("/dashboard");`
3. when I refresh /dashboard I get a page not found. 

How I solve this?

I does not matter if I use navigate, replace or push on the router. Same issue all the time

**Comment by harshosale** [comment]
Adding below part to app.json helped me

> 
    "web": {
      "output": "server"
    }
