### ISSUE TITLE
No way to dismiss modal through interaction with Overlay?

### ISSUE THREAD

**Issue by robertherber** [react-navigation/react-navigation#9524]
**Current Behavior**

It seems there is no way to capture dismiss when pressing a CardOverlay? I see no option for it and it doesn't pass on pointerEvents so I can capture the tap/gesture in the Overlay Component either.

Been digging around docs/codebase without finding a solution - but it feels like there must be one. Am I missing something here?

**Expected Behavior**

Just a simple option of "dismissOnOverlayPress" would suffice.

Versions: 
`@react-navigation/native@5.9.4`
`@react-navigation/stack@5.14.4`
`@react-navigation/core@5.15.3`

**Comment by raajnadar** [comment]
Did you check this? https://callstack.github.io/react-native-paper/modal.html#dismissable

**Comment by robertherber** [comment]
> Did you check this? https://callstack.github.io/react-native-paper/modal.html#dismissable

Yeah, but the problem here isn't showing a modal generally speaking. I'd like to use a react-navigation modal for reusability and persisting the navigation state in the URL (on web).

**Comment by ElForastero** [comment]
I'm also wondering if this is possible.

**Comment by ElForastero** [comment]
Yep, the issue is still there.

**Comment by nriin-oji** [comment]
This is what I did to resolve the issue, I put touchable without feedback as sibling of main content and set zIndex to 0, then set onPress callback to close, in this case we just need to go back.
```
<View style={styles.container}>
      <TouchableWithoutFeedback onPress={() => navigation.goBack()}>
        <View style={styles.overlay} />
      </TouchableWithoutFeedback>
      {renderContent()}
</View>
```

**Comment by robertherber** [comment]
Issue still here.

@nriin-oji How did you put it in relation to your navigation components?

**Comment by satya164** [comment]
There's an example on how to build such a modal here https://reactnavigation.org/docs/stack-navigator#transparent-modals

**Comment by robertherber** [comment]
> There's an example on how to build such a modal here https://reactnavigation.org/docs/stack-navigator#transparent-modals

Thanks! But I can't see how this could work with the built-in header?

**Comment by satya164** [comment]
> But I can't see how this could work with the built-in header?

What's the problem with the header?

**Comment by ElForastero** [comment]
It's still here.

**Comment by GollyJer** [comment]
@satya164 I have the example from here working great. Thanks.
https://reactnavigation.org/docs/stack-navigator/#transparent-modals

But, inline with the title of this issue, I can't figure out how to dismiss the screen when the transparent area is tapped.
`useCardAnimation` doesn't have any events it fires on tap. Thanks for any pointers.

**Comment by idoodler** [comment]
The easiest solution I found is by using [useClickAway](https://github.com/streamich/react-use/blob/master/docs/useClickAway.md)
