### ISSUE TITLE
JEST fail with "_native.createNavigatorFactory is not a function"

### ISSUE THREAD

**Issue by JeremieNallet** [react-navigation/react-navigation#9528]
**Current Behavior**
Running simple test to check a stack navigates to the correct screen using @testing-library/react-native 7.2.0 and jest 26.6.3

```
...
import StackApp from "../StackApp"; 

describe("<StackApp/>", () => {
    it("navigates to the correct screen", async () => {
        const { getByText } = render(
            <NavigationContainer>
                <StackApp />
            </NavigationContainer>
        );
        await waitFor(() => getByText("Discover"));

       ...

    });
});
```

will fail with  :

```
 FAIL  src/navigation/__test__/StackApp.test.js
  ● Test suite failed to run

    TypeError: (0 , _native.createNavigatorFactory) is not a function

      at Object.<anonymous> (node_modules/@react-navigation/stack/lib/commonjs/navigators/createStackNavigator.tsx:96:16)
      at Object.<anonymous> (node_modules/@react-navigation/stack/lib/commonjs/index.tsx:9:1)
```

**How to reproduce**
Attempting to run yarn test in test.js file with @testing-library/react-native 7.2.0 and jest 26.6.3 importing any component using "@react-navigation/stack" 

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| @react-navigation/native       | 5.9.4
| @react-navigation/stack        |5.14.4
| react-native-gesture-handler   |1.10.3
| react-native-safe-area-context |3.2.0
| react-native-screens           |3.1.1
| react-native                   |0.64.0
| npm or yarn                    | yarn

cheers

**Comment by ianebstein** [comment]
Was able to stub like so:
```tree
__mocks__
├── @react-navigation
│   └── native
│       └── index.ts
```
```index.ts
export const createNavigatorFactory = jest.fn()
```

**Comment by habibaamri** [comment]
I have the same error " TypeError: (0, _native.createNavigatorFactory) is not a function. (In '(0, _native.createNavigatorFactory)(StackNavigator)', '(0, _native.createNavigatorFactory)' is undefined)" when use monorepo rn +lerna

**Comment by trcoffman** [comment]
Yeah this bug affects us as well. Our app is also in a monorepo using yarn workspaces.

**Comment by tomgreco** [comment]
Same issue
