### ISSUE TITLE
Export the `NavigationRoute` type from @react-navigation/routers

### ISSUE THREAD

**Issue by varwasabi** [react-navigation/react-navigation#9531]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@react-navigation/routers@6.0.0-next.2` for the project I'm working on.

I've been creating a custom tab bar and there was a requirement to add an action button that isn't a route. Mutating the original list that is in `state.routes` messes with the type inference and i was then required to manually set the types on the newly created list. 

Simply adding an export to the below type in the routers library allowed me more flexibility on adding items to the tab bar that aren't associated with any route and still keep the efficiency of iterating over state.routes to render out the other buttons.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@react-navigation/routers/lib/typescript/src/types.d.ts b/node_modules/@react-navigation/routers/lib/typescript/src/types.d.ts
index c3dc0e7..5be5453 100644
--- a/node_modules/@react-navigation/routers/lib/typescript/src/types.d.ts
+++ b/node_modules/@react-navigation/routers/lib/typescript/src/types.d.ts
@@ -1,6 +1,6 @@
 import type * as CommonActions from './CommonActions';
 export declare type CommonNavigationAction = CommonActions.Action;
-declare type NavigationRoute<ParamList extends ParamListBase, RouteName extends keyof ParamList> = Route<Extract<RouteName, string>, ParamList[RouteName]> & {
+export declare type NavigationRoute<ParamList extends ParamListBase, RouteName extends keyof ParamList> = Route<Extract<RouteName, string>, ParamList[RouteName]> & {
     state?: NavigationState | PartialState<NavigationState>;
 };
 export declare type NavigationState<ParamList extends ParamListBase = ParamListBase> = Readonly<{
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by varwasabi** [comment]
@satya164 Happy to open a PR for this if you feel my case is valid and exporting this type adds value.

**Comment by satya164** [comment]
I want to avoid exporting it since there are already `Route` and `RouteProp` exports, so having another similar export is going to be confusing. But you can do `type NavigationRoute = NavigationState['routes'][number]` if you need.
