### ISSUE TITLE
scrollEnabled don't work in v6

### ISSUE THREAD

**Issue by IsmetGlumcevic** [react-navigation/react-navigation#9534]
I try react-navigation v6 and scrollEnabled and tabStyle width doesn't work. I use example from docs.  Tabs are fixed, can't change with... 

My code :

`<Tab.Navigator
      initialRouteName="Feed"
      tabBarOptions={{
        scrollEnabled: true,
        tabStyle: {width: 'auto', paddingHorizontal: 10},
      }}
      >
      <Tab.Screen
        name="Feed"
        component={FeedScreen}
        options={{tabBarLabel: 'Home'}}
      />
      <Tab.Screen
        name="Notifications"
        component={NotificationsScreen}
        options={{tabBarLabel: 'Updates'}}
      />
      <Tab.Screen
        name="Profile"
        component={ProfileScreen}
        options={{tabBarLabel: 'Profile'}}
      />
      <Tab.Screen
        name="Feed2"
        component={FeedScreen}
        options={{tabBarLabel: 'Home'}}
      />
      <Tab.Screen
        name="Notifications2"
        component={NotificationsScreen}
        options={{tabBarLabel: 'Updates'}}
      />
      <Tab.Screen
        name="Profile2"
        component={ProfileScreen}
        options={{tabBarLabel: 'Profile'}}
      />
    </Tab.Navigator>`

    "@react-native-masked-view/masked-view": "^0.2.4",
    "@react-navigation/bottom-tabs": "^6.0.0-next.5",
    "@react-navigation/drawer": "^6.0.0-next.4",
    "@react-navigation/material-top-tabs": "^6.0.0-next.3",
    "@react-navigation/native": "^6.0.0-next.2",
    "@react-navigation/stack": "^6.0.0-next.9",

tested on iphone simulator and device

**Comment by IsmetGlumcevic** [comment]
React-navigation v5 work well.

**Comment by satya164** [comment]
https://reactnavigation.org/docs/6.x/upgrading-from-5.x#the-tabbaroptions-prop-is-now-more-flexible-by-moving-to-options-for-material-top-tabs
