### ISSUE TITLE
Drawer gestures disabled on debug mode

### ISSUE THREAD

**Issue by a3diti** [react-navigation/react-navigation#9536]
**Current Behavior**

When react-native **Debug with Chrome** is enabled, the drawer swipe gesture does not work, and the overlay click does not work
If I stop "Debug with Chrome", the swipe gesture and overlay click will work as expected.

**Expected Behavior**

When "Debug with Chrome" is enabled, the gesture to swipe the menu (drawer) and overlay click should work.

**Environment**
MacOS Catalina 10.15.6
iOS simulator and device tested
yarn 1.22.5
node v14.15.4
@react-native-community/masked-view v0.1.10
@react-navigation/bottom-tabs v5.11.10
@react-navigation/drawer v5.12.5
@react-navigation/native v5.9.4
@react-navigation/stack v5.14.4
react v17.0.1
react-native v0.64.0
react-native-gesture-handler v1.10.3
react-native-reanimated v2.1.0
react-native-safe-area-context v3.2.0
react-native-screens v3.1.1

**Comment by satya164** [comment]
https://reactnavigation.org/docs/troubleshooting/#app-is-not-working-properly-when-connected-to-chrome-debugger
