### ISSUE TITLE
Some DrawerNavigator screenOptions are missing.

### ISSUE THREAD

**Issue by parsa-ra** [react-navigation/react-navigation#9538]
**Current Behavior**
Some `screenOptions` for `DrawerNavigator` isn't defined these are including:
* headerStyle
* headerTileStyle

**Expected Behavior**

By applying the following sample code I get customized drawerNavigator.
```js
const DrawerNav = observer(()=>(
  <Drawer.Navigator 
    initialRouteName="Home" 
    drawerType={rootStore.drawerType} 
    drawerStyle={{
      backgroundColor: colors[rootStore.theme].fillAreaColor,
      width:150
    }}
    screenOptions={{
      headerStyle: {
        backgroundColor: "#eaba33" 
      },
      headerTitleStyle: {
        fontSize: 30,
        fontFamily: 'Ubuntu',
        fontWeight: '500', 
      }
    }}>
    <Drawer.Screen name="Home" component={Home} options={{
      headerStyle: {
        backgroundColor: "#eaba33" 
      },
      headerTitleStyle: {
        fontSize: 30,
        fontFamily: 'Ubuntu',
        fontWeight: '500', 
      }
    }}/>
    <Drawer.Screen name="About" component={About} />
  </Drawer.Navigator>
))
```

For consolidation here is intellisense context menu suggestions for DrawerNavigator:
![image](https://user-images.githubusercontent.com/11356471/116210204-e4f22580-a757-11eb-9a9a-b419f2367b51.png)
vs StackNavigator:
![image](https://user-images.githubusercontent.com/11356471/116210811-75306a80-a758-11eb-849c-53e5494e0c1f.png)

**Your Environment**
Tests applied both using Web and Android ports.
    "@react-native-community/masked-view": "0.1.10",
    "@react-navigation/drawer": "^5.12.5",
    "@react-navigation/native": "^5.9.4",
    "@react-navigation/stack": "^5.14.4",
    "expo": "~40.0.0",
    "expo-app-loading": "^1.0.3",
    "expo-asset": "~8.2.1",
    "expo-font": "~8.4.0",
    "expo-splash-screen": "~0.8.1",
    "expo-status-bar": "~1.0.3",
    "expo-updates": "~0.4.0",
    "mobx": "^6.2.0",
    "mobx-react": "^7.1.0",
    "mobx-react-lite": "^3.2.0",
    "mobx-state-tree": "^5.0.1",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "~0.63.4",
    "react-native-gesture-handler": "~1.8.0",
    "react-native-reanimated": "~1.13.0",
    "react-native-safe-area-context": "3.1.9",
    "react-native-screens": "~2.15.2",
    "react-native-svg": "12.1.0",
    "react-native-unimodules": "~0.12.0",
    "react-native-web": "~0.13.12"

**Comment by satya164** [comment]
They are available in 6.x

**Comment by parsa-ra** [comment]
> They are available in 6.x

Tnx for the fast response, my team have to deliver a product in about a month and one of the most vital components of the app is a react-navigation package, I'm wondering if the 6.x/@next production-ready at its current stage? when we should anticipate the stable release of the 6.x ?

**Comment by satya164** [comment]
@parsa-ra there aren't any known new issues in 6.x. you can use it in production. it's still unreleased because there are few more things we want to implement.
