### ISSUE TITLE
Unable to animate permanent drawer

### ISSUE THREAD

**Issue by josehernandezv** [react-navigation/react-navigation#9542]
**Current Behavior**

I am trying to create a mini drawer that only shows icons when is closed and that shows icons and labels when is expanded. I couldn't find a similar example of what I am trying to achieve so I thought on creating a custom DrawerContent component with it's own open/closed state that would animate the drawer, the problem is that the permanent drawer by default adds a white background, I also thought on simple changing the permanent width but I couldn't found a way to do it with a smooth animation.

**Expected Behavior**

- I want to be able to create a Drawer that only shows icons when is closed and that it expands with an animation to reveal the label.

![Simulator Screen Shot - iPad (8th generation) - 2021-04-29 at 21 33 41](https://user-images.githubusercontent.com/28166305/116645417-107d3780-a933-11eb-8055-4047119613fc.png)
![Simulator Screen Shot - iPad (8th generation) - 2021-04-29 at 21 33 34](https://user-images.githubusercontent.com/28166305/116645421-11ae6480-a933-11eb-8ae0-6df0d00c38f2.png)

**How to reproduce**

https://snack.expo.io/@josehernandezv/mini-drawer

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | iOS
| @react-navigation/native       | 6.9.3
| @react-navigation/drawer       | 5.12.5
| react-native-reanimated        | 1.13.0
| react-native-gesture-handler   | 1.10.3
| react-native-safe-area-context | 3.1.9
| react-native-screens           | 2.18.1
| expo                           |  40.0.1
| npm or yarn                    | yarn

**Comment by ngtrhieu** [comment]
You didn't close the drawer, you only animate your `CustomDrawer`. Check this out: https://reactnavigation.org/docs/drawer-based-navigation#opening-and-closing-drawer

**Comment by josehernandezv** [comment]
But closing a permanent drawer doesn't do anything

**Comment by guilhermebpereira** [comment]
@josehernandezv 
[Does it solve your problem?](https://snack.expo.io/@guilhermebpereira/mini-drawer)
 Changes: update the width of the drawer, instead of the content.
 _PS: not working on web_

**Comment by josehernandezv** [comment]
I can change the width but not with an Animated.value, and I would like to expand with an animation, 
I ended up creating a custom layout component instead of using the Drawer

**Comment by guilhermebpereira** [comment]
> I can change the width but not with an Animated.value, and I would like to expand with an animation,
> I ended up creating a custom layout component instead of using the Drawer

@josehernandezv i used Animated.value on the example above. Doesn't it solve your problem?

**Comment by josehernandezv** [comment]
Oh sorry, I didn't saw your example, for me it works perfect that way, the only think that I'm not really happy with is that in my project typescript throw me an error because the Drawer wasn't expecting an Animated Value, so I'm not really sure if there would be any performance issues for using an Animated Value where a number is expected

**Comment by guilhermebpereira** [comment]
### Performance issues
Probably not, since it only works because `drawerStyle` is actually used on a `Animated.View`, as you can [check here](https://github.com/react-navigation/react-navigation/blob/a55d6a8d796fa2b9f46cfcaf71f05c6d87738072/packages/drawer/src/views/modern/Drawer.tsx#L339). Anyway, we could open a new issue if any performance issue appears in the future.
### Typescript issue
 Maybe we could do some PR updating the type being used on `drawerStyle`. I think it would be only updating [over here](https://github.com/react-navigation/react-navigation/blob/a4bf622b1af35aeecc26612390de007903791058/packages/drawer/src/types.tsx#L284), but i can dig into that later today.
 
 @josehernandezv what do you think about closing this issue?

**Comment by josehernandezv** [comment]
Thank you @guilhermebpereira
