### ISSUE TITLE
v6 error on fresh expo install (in the types file).

### ISSUE THREAD

**Issue by GollyJer** [react-navigation/react-navigation#9545]
I created a fresh "typescript with tabbed navigation" Expo 41 project. It runs great with react-navigation v5 (the default).

Then I run 
`yarn add @react-navigation/native@next @react-navigation/stack@next @react-navigation/bottom-tabs@next`

And get this error when the app loads...
![image](https://user-images.githubusercontent.com/689204/116788652-aa420300-aa5f-11eb-9fad-a4958d2f0614.png)

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | both
| @react-navigation/native       |  ^6.0.0-next.2
| @react-navigation/stack |  ^6.0.0-next.9
| @react-navigation/bottom-tabs   |  ^6.0.0-next.5
| react-native                   | https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz
| expo                           | ~41.0.1
| node                           | v14.15.5
| npm or yarn                    | yarn 1.22.5

I'd love to test v6 if anyone can help me through this. Thanks!

**Comment by GollyJer** [comment]
I created a snack with the exact same code as the default expo typescript tabbed project and it works.
https://snack.expo.io/jT1QZ8KW2

The only conclusion I can come to is there's something weird in the babel config or dev dependencies of the Expo cli version causing the issue. Any help/ideas?

**Comment by ngtrhieu** [comment]
Maybe it is me, but I never see such a syntax in TS. Can you try change `[screen: RouteName]` into `[screen] as RouteName[]`, `[screen] as Array<RouteName>` or even `[screen] as [RouteName]` ??

**Comment by GollyJer** [comment]
Hi. @ngtrhieu 
I thought for sure that would work but I'm getting the same error. Strangely.

Is there any chance you could fire up a create-react-app typescript and try this? I'm at a loss.

**Comment by satya164** [comment]
This is likely due to outdated expo-cli version. Please update it and check if it fixes the issue. You can also try the steps here https://reactnavigation.org/docs/6.x/troubleshooting#im-getting-syntaxerror-in-react-navigationxxxxxxtsx-or-syntaxerror-xxxreact-navigationxxxxxxtsx-unexpected-token

I'm closing the issue since I can't repro it in a fresh expo project.
