### ISSUE TITLE
TypeError: undefined is not an object (evaluating '_$$_REQUIRE(_dependencyMap[6], "@react-navigation/native").NavigationHelpersContext.Provider')

### ISSUE THREAD

**Issue by M1ck0** [react-navigation/react-navigation#9546]
**Current Behavior**

When I import and try to use  `createMaterialBottomTabNavigator` I get the `TypeError: undefined is not an object (evaluating '_$$_REQUIRE(_dependencyMap[6], "@react-navigation/native").NavigationHelpersContext.Provider')` error

I found similar issues like #8352 but nothing is working for me.

**Expected Behavior**

It should work

**How to reproduce**

Create a new bare `react-native` project with `react-native` `0.64.0`
Install `react-navigation` by following docs
Import and create basic navigation using `createMaterialBottomTabNavigator`
It will crash

**Your Environment**

| software                               | version |
| -------------------------------------- | ------- |
| Android                                  | 10   
| @react-navigation/native      | ^5.9.4  
| @react-navigation/material-bottom-tabs | ^5.3.15
| react-native-paper                     | ^4.8.1
| react-native                           | 0.64.0
| expo                                   | /
| node                                   | 16.0.0
| yarn                            | 1.22.10

I also tried with `react-native` `0.63` and problem still presists.

**Comment by lualbergipe** [comment]
Hola Amigo pudiste solucionar el problema?

**Comment by akshy78695** [comment]
I'm getting the same issue. I tried to run code in the expo.io its working fine there
here is the expo link:  [https://snack.expo.io/@ak_expo/material_bottom_tabs_v5-3-15]

But the same code is not working in my react-native project and gives the above error (with the same environment mentioned above).
![WhatsApp Image 2021-05-25 at 5 21 54 PM](https://user-images.githubusercontent.com/54743386/119493480-dbbb9f00-bd7d-11eb-971c-9bd4e58a5219.jpeg)

**Comment by maueli** [comment]
Hi! I am leading with the same issue...

**Comment by maueli** [comment]
I solved my problem. Check the file "packages.json" that all dependencies has the same version, in your case:

```
@react-navigation/native: ^5.3.15
@react-navigation/material-bottom-tabs: ^5.3.15
```

Always choose the old ones.

**Comment by luismigueldev1** [comment]
I'm getting the same issue.

**Comment by luismigueldev1** [comment]
@maueli in your case what version are using for solve the problem?

**Comment by maueli** [comment]
In my case it wasnt with @react-navigation/native package, I had the same error but with other package (@react-navigation/admob) but I solved this error just writing the same versions in "packages.json" (Be sure that the version yo will rewrite will be the newest because you need to get down the version, ie, use an old one). I hope all of that can be helpful

**Comment by satya164** [comment]
I recently noticed that this happens if you didn't install `react-native-vector-icons`. Seems like a bug in Metro, but make sure to install the package.

I'm closing the issue since that should fix it. Please comment if it doesn't.

**Comment by jeremyfrancis** [comment]
My issue was at @react-navigation/drawer and so I just opened that node module directory in Visual Studio and CMD+F searched the line of code getting "undefined". I found it and it changed require('./modern/Drawer').default to require('./legacy/Drawer').default and it works again.

Probably a node module like react native reanimated got updated prematurely for this package.

**Comment by frabanca** [comment]
> 

That actually was the only things I could use to resolve the issue. Thanks @jeremyfrancis for sharing your solution.

**Comment by Gautham495** [comment]
> My issue was at @react-navigation/drawer and so I just opened that node module directory in Visual Studio and CMD+F searched the line of code getting "undefined". I found it and it changed require('./modern/Drawer').default to require('./legacy/Drawer').default and it works again.
> 
> Probably a node module like react native reanimated got updated prematurely for this package.

Only solution which worked thanks a lot.

**Comment by andersonibstecnologia** [comment]
Solved this by setting  `useLegacyImplementation` on Drawer.Navigator

```
<Drawer.Navigator  useLegacyImplementation>
...
```

**Comment by bigujun** [comment]
Solved this by setting `useLegacyImplementation` on Drawer.Navigator

```
<Drawer.Navigator  useLegacyImplementation>
...
```

**Comment by tabish-kook** [comment]
> Solved this by setting `useLegacyImplementation` on Drawer.Navigator
> 
> ```
> <Drawer.Navigator  useLegacyImplementation>
> ...
> ```

This worked for me, thanks bro.
