### ISSUE TITLE
How to pass a function callback to child component using React Navigation?

### ISSUE THREAD

**Issue by interpegasus** [react-navigation/react-navigation#9549]
**Current Behavior**
Non-serializable values were found in the navigation state. Check: ... This can break usage such as persisting and restoring state. This might happen if you passed non-serializable values such as function, class instances etc. in params. If you need to use components with callbacks in your options, you can use 'navigation.setOptions' instead. See https://reactnavigation.org/docs/troubleshooting#i-get-the-warning-non-serializable-values-were-found-in-the-navigation-state for more details.

<img width="291" alt="Screen Shot 2021-05-03 at 10 16 22 AM" src="https://user-images.githubusercontent.com/934795/116895269-a1386980-abf8-11eb-8491-417c083e705a.png">

**Expected Behavior**
I would like to know how to pass a function param to a child component? Can it be done with react-navigation? 

**How to reproduce**
I am trying to pass updateListing via  navigation.navigate. It works but the warning is prompted.
```
      <FlatList
        onRefresh={() => updateListing()}
        refreshing={getSquadOrders.loading}
        data={orderArray}
        keyExtractor={(order) => order.id.toString()}
        renderItem={({ item }) => <Card title={item.order_name} subTitle={item.estado} imageUrl={item.imagen} 
onPress={() => navigation.navigate(routes.LISTING_DETAILS, { item: item, updateListing: updateListing })} thumbnailUrl={item.imagen} />}
      />
```
**Your Environment**
    "@react-navigation/bottom-tabs": "^5.11.10",
    "@react-navigation/native": "^5.3.2",
    "@react-navigation/stack": "^5.3.5",
    "react": "16.13.1",

Thank you

**Comment by interpegasus** [comment]
Expo Link: https://expo.io/@summus/projects/ryesa

**Comment by ngtrhieu** [comment]
No it is not possible to pass non-serialisable data when navigate. `react-navigation` is not designed to handle these type of values. I don't think other navigation libraries can do that also.

Just imagine how would you pass function when you navigate via deeplink.

**Comment by interpegasus** [comment]
Thanks for the clarification. I am closing this issue.

**Comment by zabojad** [comment]
[react-native-navigation](https://github.com/wix/react-native-navigation) allows passing functions to screens. One common use case is passing a callback to a user auth stack modal. The cb is called once the user has passed the auth tunnel...

**Comment by zabojad** [comment]
Also note that it's just a warning and passing functions in nav params seems to work fine anyway....

**Comment by beqramo** [comment]
it is a really handy way to get status from the next screen when it is for example OTP screen.

**Comment by Bacteria007** [comment]
You can do this  navigation.navigate(routes.LISTING_DETAILS, { item: item, updateListing:(something)=>updateListing(something)   })} and in LISTING_DETAILS screen you can use it like this  onPress={() => {
                                            updateListing(something);}}
