### ISSUE TITLE
Couldn't register the navigator. Have you wrapped your app with 'NavigationContainer'? 

### ISSUE THREAD

**Issue by thomasdittmar** [react-navigation/react-navigation#9556]
**Current Behavior**

- What code are you running and what is happening?

I'm running a NON-EXPO RN app with the environment below in a mono-repo (**yarn workspaces**). The app has no extra code running apart from the code below, taken from [here](https://reactnavigation.org/docs/tab-based-navigation)

```javascript
import * as React from 'react';
import { Text, View } from 'react-native';
import { NavigationContainer } from '@react-navigation/native';
import { createBottomTabNavigator } from '@react-navigation/bottom-tabs';

function HomeScreen() {
  return (
    <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
      <Text>Home!</Text>
    </View>
  );
}

function SettingsScreen() {
  return (
    <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
      <Text>Settings!</Text>
    </View>
  );
}

const Tab = createBottomTabNavigator();

export default function App() {
  return (
    <NavigationContainer>
      <Tab.Navigator>
        <Tab.Screen name="Home" component={HomeScreen} />
        <Tab.Screen name="Settings" component={SettingsScreen} />
      </Tab.Navigator>
    </NavigationContainer>
  );
}
```

- Include a screenshot or video if it makes sense.

Once I run that code I get the following error message: `Error: Couldn't register the navigator. Have you wrapped your app with 'NavigationContainer'?`, although the `<Tab.Navigator>` is wrapped in a `<NavigationContainer>`

![Screen Shot 2021-05-06 at 1 06 03 pm](https://user-images.githubusercontent.com/75284636/117236357-def0f880-ae6b-11eb-9c81-bda1cfbfabde.png)

The code runs perfectly with a `createStackNavigator()` like that:

```javascript
import * as React from 'react';
import { View, Text } from 'react-native';
import { NavigationContainer } from '@react-navigation/native';
import { createStackNavigator } from '@react-navigation/stack';

function HomeScreen() {
  return (
    <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
      <Text>Home Screen</Text>
    </View>
  );
}

const Stack = createStackNavigator();

function App() {
  return (
    <NavigationContainer>
      <Stack.Navigator>
        <Stack.Screen name="Home" component={HomeScreen} />
      </Stack.Navigator>
    </NavigationContainer>
  );
}

export default App;
```

**Expected Behavior**

- What do you expect should be happening?

I expected that the app, within a mono-repo will work in the same way this [EXPO app](https://snack.expo.io/@dittmarconsulting/bottom-tabs) with the same code.

**How to reproduce**

- Create a yarn workspace (`node_modules` folder will be in the root of the mono-repo)
- Create a Typescript RN from scratch in the `packages` folder
- Adjust the path to the `node_modules/react-native` folder in the `Podfile`
- Add the dependencies as described below
- Execute yarn to install dependencies
- Swap the existing code in `App.js` with the code snipped above

**Your Environment**

| software                      | version |
| ----------------------------- | ------- |
| iOS or Android                | iOS
| @react-navigation/native      | 5.9.4
| @react-navigation/bottom-tabs | 5.11.10
| react-native-screens          | 3.1.1
| react-native                  | 0.63.1
| expo                          | NO
| node                          | 15.3.0
| npm or yarn                   | yarn

**Comment by rawatnaresh** [comment]
Its working perfectly fine. Just in case try 
- `watchman watch-del-all`
- `yarn start --reset-cache`
If above didnt solve the issue try removing `node_modules` and `Pods` folder and install them again
-  `yarn`
- `npx pod-install ios`

**Comment by thomasdittmar** [comment]
I tried a fresh Metro app and a normal RN app and it worked. 

I forgot to mention that I have a Typescript RN app within a mono-repo (yarn workspaces)

I just created a fresh RN in the mono-repo and it failed again. 

The only difference is that the `node_modules` folder is outside of the app folder. I wonder if that causes it.

**Comment by satya164** [comment]
@thomasdittmar sounds like you have multiple versions of `@react-navigation/core` included.

**Comment by thomasdittmar** [comment]
Although I didn't have multiple `@react-navigation/core` installed, I had conflicting packages in the mono-repo. I rebuild everything from scratch and got it to work.

**Comment by retyui** [comment]
@thomasdittmar what do you meant "had conflicting packages"?

**Comment by irvingswiftj** [comment]
Moving `@react-navigation/native` from a dependency to a peer dependency and then `rm -Rf node_modules`, `pnpm i` did the trick for me.
