### ISSUE TITLE
Header flickering at the first launching

### ISSUE THREAD

**Issue by xyxc0673** [react-navigation/react-navigation#9557]
**Current Behavior**

I have this bug in my project, and I create a new project with the latest version and still got the bug.

![demo.gif](https://i.loli.net/2021/05/08/BQorYna7wW8gviU.gif)

**Expected Behavior**

Header should stay its place

**How to reproduce**

The demo repo

https://github.com/xyxc0673/RNDemo

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Android
| @react-navigation/native       |^5.9.4
| @react-navigation/stack        |^5.14.4
| react-native-gesture-handler   |^1.10.3
| react-native-safe-area-context |^3.2.0
| react-native-screens           |^3.1.1
| react-native                   | 0.64.1
| expo                           |
| node                           | v15.13.0
| npm or yarn                    | 1.22.10

**Comment by lc3t35** [comment]
I have the same problem but on iOS only :

![ScreenFlow](https://user-images.githubusercontent.com/921372/117580234-5be3d280-b0f7-11eb-9a54-5f2960908b25.gif)


```
"@react-navigation/native": "^5.9.4",
"@react-navigation/stack": "^5.14.4",
"react-native-gesture-handler": "~1.10.2",
"react-native-screens": "~3.0.0",
"react-native-safe-area-context": "3.2.0",
"react-native": "0.63.4",
"expo": "^41.0.1",
```

**Comment by sean-m-oleary** [comment]
same here.

**Comment by devpolo** [comment]
## 👋 Hi everyone

Same problem on load every screens with a custom header.
Bug observed on`iOS` and `Android`.

Unfortunatly, notihing to deal with #9530 or [react-native-screens#905](https://github.com/software-mansion/react-native-screens/issues/905). It's more about a **custom header component calculation** problem.

It Looks like it happened every time I use `header` in my `screenOptions` prop of my `Stack.Navigator` component.

## 1️⃣ first case

_with custom header render_

<img src="https://user-images.githubusercontent.com/36532199/126344327-fc5fb6ad-d199-4557-9eb8-2def5da30f39.gif" width="200" alt="bug-header">

```js
<Stack.Navigator
  screenOptions={{
    header: () => <Header />
  }}>
  ...
</Stack.Navigator>
```
## 2️⃣ second case

_without custom header render_

<img src="https://user-images.githubusercontent.com/36532199/126344308-99990dc2-57bc-4623-b939-464e9263ffdf.gif" width="200" alt="bug-header-null" >

```js
<Stack.Navigator
  screenOptions={{
    header: () => null
  }}>
  ...
</Stack.Navigator>
```
_GIF speed has been decreased for visualization purpose. In reality, it lasts 0.1s and it can be faster or slower, depending of the screen complexity to render._

## Packages versions

```json
{
  "@react-navigation/native": "^5.7.0",
  "@react-navigation/stack": "^5.7.0",
  "react-native-gesture-handler": "^1.6.1",
  "react-native-screens": "^2.9.0",
  "react-native-safe-area-context": "^3.1.7",
  "react-native": "0.63.1",
}
```

**Comment by raajnadar** [comment]
All this line as the very first line of the `index.js`

`import 'react-native-gesture-handler';`

Ready carefully `index.js` & not `App.js`

Something like this

```
import 'react-native-gesture-handler';

import {AppRegistry} from 'react-native';
import App from './App';
import {name as appName} from './app.json';

AppRegistry.registerComponent(appName, () => App);
```

**Comment by devpolo** [comment]
@raajnadar, thanks for trying to help. 
I already have this in my root project `index.js`:

```js
import 'react-native-gesture-handler'

import { AppRegistry } from 'react-native'
import App from './app/App'
import { name as appName } from './app.json'

AppRegistry.registerComponent(appName, () => App)
```

**Comment by satya164** [comment]
@devpolo https://reactnavigation.org/docs/stack-navigator#specify-a-height-in-headerstyle

**Comment by xyxc0673** [comment]
Hello everyone
In my case, I have solved the problem by adding SafeAreaProvider as the parent of navigations.

**Comment by devpolo** [comment]
> @devpolo
> 
> > first case
> 
> https://reactnavigation.org/docs/stack-navigator#specify-a-height-in-headerstyle
> 

You the best ! Thanks @satya164

**Comment by asprouse5** [comment]
I was able to solve my issue by adding `headerMode: 'float'`:
```
<Stack.Navigator screenOptions={{
        ...
        headerMode: 'float',
        ...
}}>
```

**Comment by scarlac** [comment]
For posterity: @xyxc0673 's comment fixed it for me. You need `SafeAreaProvider` wrapping your navigators, e.g.:
```jsx
import { SafeAreaProvider } from 'react-native-safe-area-context';
// ...
return (
  <SafeAreaProvider>
    <NavigationContainer>
      { /* ... */ }
    </NavigationContainer>
  </SafeAreaProvider>
);

```

**Comment by hamzaashrafi** [comment]
> PR to fix the docs:



> Hello everyone In my case, I have solved the problem by adding SafeAreaProvider as the parent of navigations.
