### ISSUE TITLE
Tapping outside doesn't close the drawer on iOS

### ISSUE THREAD

**Issue by aschick82** [react-navigation/react-navigation#9558]
**Current Behavior**

- Running on React Native 0.63.3 and React Navigation Drawer 5.12.5
- When I tap on the overlay outside of drawer when it's open, the drawer doesn't go away. Also I am not able to open it by swiping from left. This line also exists in my main index.js file: 

**import 'react-native-gesture-handler';**

**Expected Behavior**

- Drawer to be closed by tapping outside on iOS

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | iOS
| @react-navigation/native       |   5.9.4
| @react-navigation/drawer       | 5.12.5
| react-native-reanimated        | 2.1.0
| react-native-gesture-handler   | 1.10.3
| react-native-safe-area-context | 3.2.0
| react-native-screens           | 3.1.1
| react-native                   | 0.63.3
| node                           | v14.15.3
| npm or yarn                    | yarn

**Comment by aryalprakash** [comment]
I'm also facing this issue. It's working fine on Android though.

**Comment by aryalprakash** [comment]
@Romick2005 Getting this error when installing version 1.13.2 of react-native-reanimated
`error: Error: Unable to resolve module ./reanimated2 from /../node_modules/react-native-reanimated/src/Animated.js:
`

**Comment by Romick2005** [comment]
@aryalprakash Have you clean up after reanimated2? I mean remove "react-native-reanimated/plugin" in babel.config.js and of course "npx pod-install"? You should better go with 
`rm -rf node_modules && rm -rf package-lock.json && rm -rf ios/Pods && rm -rf ios/Podfile.lock && npm install --force && npx pod-install`

**Comment by aryalprakash** [comment]
@Romick2005 Thanks. I had to use `npm start -- --reset-cache` even after doing those.
It's working now but there's some flickering when opening/closing drawer.

**Comment by pinpointpanda** [comment]
I've also seen this in our project recently -- although we're not running latest `reanimated@2` yet. Will upgrade that tomorrow and if still present will provide a Snack and/or minimal repro.

**Comment by tomwanzek** [comment]
I can confirm that the issue replicates for us on iOS after upgrading `react-native-reanimated` from 1.8.0 to 2.2.0.

It is noteworthy though, that on an Emulator such as iPhone 11 w/ iOS 14.5 the issue seems to be limited to running in Debug mode. Whereas when debugging is stopped tapping outside the drawer closes it as expected.

This is with `react-native-gesture-handler@1.10.3`.

And replicates both with latest react-navigation/native, react-navigation/drawer, react-navigation/stack as well as, our pre-upgrade: 

react-navigation/native@5.7.5, react-navigation/drawer@5.9.2, react-navigation/stack@5.9.2

**Comment by tomwanzek** [comment]
For clarity, when I say replicates I'm referring to:

* swipe gesture to open/close Drawer is not working
* drawer can be programatically opened/closed e.g. menu on button click, but tapping outside of the drawer does not close it.

All of the above on Emulator in debug mode, but fine when debugger is not attached.

**Comment by tomwanzek** [comment]
This issue is becoming a blocker, as we want to use another popular 3rd party UI component library which has a minimum dependency of reanimated@2, so we cannot just simply stick with 1.x.

**Comment by imranMnts** [comment]
@satya164 

Do we have any updates regarding this topic?

**Comment by RaniXavier** [comment]
I am also facing this issue with "react-native-reanimated": "^2.1.0"

**Comment by ser-emejia** [comment]
Any updates?

Still the same problem, only in iOS

 **_`"react-native-reanimated": "~2.8.0"`_**
