### ISSUE TITLE
Programatically hiding tab bar doesn't work in v6 

### ISSUE THREAD

**Issue by akhilvc10** [react-navigation/react-navigation#9563]
**Current Behavior**

I tired hiding the tab bar using this code. But the below code doesn't work.

`navigation.setOptions({ tabBarVisible: false });`

**Expected Behavior**

Expect the tab bar to hide in specific screen programatically.

**How to reproduce**

Start the app, add the code inside any children of Bottom Tab navigator. 

`navigation.setOptions({ tabBarVisible: false });` 

**Your Environment**

| software                      | version |
| ----------------------------- | ------- |
| iOS or Android                | Android 11
| @react-navigation/native      | ^6.0.0-next.3
| @react-navigation/bottom-tabs | ^6.0.0-next.6
| react-native-screens          |  ~3.0.0
| react-native                  | sdk-41.0.0
| expo                          |  ~41.0.1
| node                          | v14.14.0
| npm or yarn                   | 7.12.0

**Comment by satya164** [comment]
https://reactnavigation.org/docs/6.x/upgrading-from-5.x#the-tabbarvisible-option-is-no-longer-present

**Comment by pehagg** [comment]
@akhilvc10 , were you able to use the new API? 

I can't for the life of me figure out how to make this work. Our navigation hierarchy is pretty complex and I'm many screens deep in and would like to hide the bottom tab tab before navigating to a child screen (the tab bar should be visible for all other views in the hierarchy).

**Comment by akhilvc10** [comment]
> @akhilvc10 , were you able to use the new API?
> 
> I can't for the life of me figure out how to make this work after upgrading from v5 to v6. Our navigation hierarchy is pretty complex and I'm many screens deep in and would like to hide the bottom tab tab before navigating to a child screen (the tab bar should be visible for all other views in the hierarchy).

@pehagg , `navigation.setOptions({ tabBarVisible: false });` worked for me. But I'm using a Custom Tabbar instead of the default one.

In my custom tabbar I've the below code which does the work for me

`if (focusedOptions.tabBarVisible === false) {
		return null;
	}
`

**Comment by pehagg** [comment]
@akhilvc10 , thanks, neat workaround :) I have a custom one as well, going to give your workaround a go tomorrow.

**Comment by Heltonphg** [comment]
> > @akhilvc10 , were you able to use the new API?
> > I can't for the life of me figure out how to make this work after upgrading from v5 to v6. Our navigation hierarchy is pretty complex and I'm many screens deep in and would like to hide the bottom tab tab before navigating to a child screen (the tab bar should be visible for all other views in the hierarchy).
> 
> @pehagg , `navigation.setOptions({ tabBarVisible: false });` worked for me. But I'm using a Custom Tabbar instead of the default one.
> 
> In my custom tabbar I've the below code which does the work for me
> 
> `if (focusedOptions.tabBarVisible === false) { return null; } `
> 
> The new API didn't work for me

how do you pass the "focusOptions" property to the function MyTabBar({ state, descriptors, navigation }) {...} ???

**Comment by akhilvc10** [comment]
> > > @akhilvc10 , were you able to use the new API?
> > > I can't for the life of me figure out how to make this work after upgrading from v5 to v6. Our navigation hierarchy is pretty complex and I'm many screens deep in and would like to hide the bottom tab tab before navigating to a child screen (the tab bar should be visible for all other views in the hierarchy).
> > 
> > 
> > @pehagg , `navigation.setOptions({ tabBarVisible: false });` worked for me. But I'm using a Custom Tabbar instead of the default one.
> > In my custom tabbar I've the below code which does the work for me
> > `if (focusedOptions.tabBarVisible === false) { return null; } `
> > The new API didn't work for me
> 
> how do you pass the "focusOptions" property to the function MyTabBar({ state, descriptors, navigation }) {...} ???


`const { navigationState, descriptors, navigation } = props;`
`const focusedOptions =
		descriptors[navigationState.routes[navigationState.index].key].options;`

**Comment by pehagg** [comment]
I start to get what's happening. As I have a custom tab bar, I need to check the existence and value of `tabBarStyle` myself, using the descriptor for the focused view's options. This would all probably work if I was using the built-in tab bar. This is something that has been overlooked in the documentation for custom tab bars.

**Comment by Heltonphg** [comment]
const focusedOptions = descriptors[state.routes[state.index].key].options;
console.log(focusedOptions);
-> {"headerShown": false}

**Comment by bombillazo** [comment]
This seems to be the solution in v6.x now:
https://reactnavigation.org/docs/upgrading-from-5.x/#the-tabbarvisible-option-is-no-longer-present

**Comment by j-cheung** [comment]
> I start to get what's happening. As I have a custom tab bar, I need to check the existence and value of `tabBarStyle` myself, using the descriptor for the focused view's options. This would all probably work if I was using the built-in tab bar. This is something that has been overlooked in the documentation for custom tab bars.
> 
> Was able to solve the issue, thanks @akhilvc10 for pointing me in the right direction.

hi, how were you able to get the focusedoptions with react-navigation v6? thanks.

**Comment by j-cheung** [comment]
> > I start to get what's happening. As I have a custom tab bar, I need to check the existence and value of `tabBarStyle` myself, using the descriptor for the focused view's options. This would all probably work if I was using the built-in tab bar. This is something that has been overlooked in the documentation for custom tab bars.
> > Was able to solve the issue, thanks @akhilvc10 for pointing me in the right direction.
> 
> hi, how were you able to get the focusedoptions with react-navigation v6? thanks.

nevermind, found it

`
  const focusedOptions = descriptors[state.routes[state.index].key]
    .options as BottomTabNavigationOptions
`

**Comment by praveens96** [comment]
I am hiding this way

```
export const useHideTabsHook = () => {
    const route = useRoute();
    const navigation = useNavigation();
    const tabHiddenRoutes = getHiddenRoutesForRoute(route.name);
    useLayoutEffect(() => {
        const routeName = getFocusedRouteNameFromRoute(route);
        if (tabHiddenRoutes && tabHiddenRoutes.includes(routeName)) {
            navigation.setOptions({ tabBarStyle: { display: 'none' } });
        } else {
            navigation.setOptions({ tabBarStyle: { display: 'flex' } });
        }
    }, [navigation, route, tabHiddenRoutes]);
};
```

and including this hook in each stack I need.
implement this method: getHiddenRoutesForRoute

**Comment by adnandothussain** [comment]
Do anyone tried using a custom tab bar?

**Comment by jleem99** [comment]
Using `display: 'none'` instead of `tabBarVisible` technically works, but then the animation set in `visibilityAnimationConfig` does not take effect.

Seems animation works only when keyboard is shown and `tabBarHideOnKeyboard` is set to true, so I had to patch the source code like below.

`
export default function BottomTabBar({
  state,
  navigation,
  descriptors,
  insets,
  style,
}: Props) {
  const { colors } = useTheme();
  const buildLink = useLinkBuilder();

  const focusedRoute = state.routes[state.index];
  const focusedDescriptor = descriptors[focusedRoute.key];
  const focusedOptions = focusedDescriptor.options;

  const {
    tabBarShowLabel,
    tabBarHideOnKeyboard = false,
    tabBarVisibilityAnimationConfig,
    tabBarStyle,
    tabBarBackground,
    tabBarActiveTintColor,
    tabBarInactiveTintColor,
    tabBarActiveBackgroundColor,
    tabBarInactiveBackgroundColor,
    // @ts-ignore
    tabBarVisible
  } = focusedOptions;

  const dimensions = useSafeAreaFrame();
  const isKeyboardShown = useIsKeyboardShown();

  const onHeightChange = React.useContext(BottomTabBarHeightCallbackContext);

  const shouldShowTabBar = !(tabBarHideOnKeyboard && isKeyboardShown) && tabBarVisible;

  const visibilityAnimationConfigRef = React.useRef(
    tabBarVisibilityAnimationConfig
  );
`
[Orignal Source](https://github.com/react-navigation/react-navigation/blob/%40react-navigation/bottom-tabs%406.2.0/packages/bottom-tabs/src/views/BottomTabView.tsx)

**Comment by zanyar3** [comment]
## Upgrading from 5.x


> The `tabBarVisible` option is no longer present

Since the the tab bar now supports a `tabBarStyle` option, we have removed the `tabBarVisible` option. You can achieve the same behavior by specifying `tabBarStyle: { display: 'none' }` in options.

**Comment by WalterOkumu** [comment]
> tabBarVisible



> ## Upgrading from 5.x
> > The `tabBarVisible` option is no longer present
> 
> Since the the tab bar now supports a `tabBarStyle` option, we have removed the `tabBarVisible` option. You can achieve the same behavior by specifying `tabBarStyle: { display: 'none' }` in options.

I tried this, but no change. Here's my code and here's my snack --> [https://snack.expo.dev/@okumu/coinbase-clone](url)

`<NavigationContainer>
      <Tab.Navigator
        options = {{
          tabBarStyle: {
            position: 'absolute',
            elevation: 0,
            backgroundColor: 'white',
            borderRadius: 15,
            height: 90,
            display: 'none',
          }
        }}
      >
        <Tab.Screen 
          name = 'Home' 
          component = {Home}
          options = {{
            tabBarIcon: ({ focused }) => (
              <View style = {{ alignItems: 'center', justifyContent: 'center' }}>
                <Image
                  source = { require('./src/assets/images/home.png') }
                  resizeMode = 'contain'
                  style = {{
                    width: 17,
                    height: 17,
                    tintColor: focused ? 'blue' : 'gray'
                  }}
                />
                <Text style = {{ color: focused ? 'blue' : 'gray', fontSize: 10 }}>
                  Home
                </Text>
              </View>
            )
          }} 
        />
        <Tab.Screen name = 'Portfolio' component={Portfolio} />
        <Tab.Screen name = 'Transfer' component={Transfer} />
        <Tab.Screen name = 'Prices' component={Prices} />
        <Tab.Screen name = 'Settings' component={Settings} />
      </Tab.Navigator>
    </NavigationContainer>`
