### ISSUE TITLE
Recommended approach for serving web port

### ISSUE THREAD

**Issue by parsa-ra** [react-navigation/react-navigation#9565]
**Current Behavior**
We're currently working on an App using Expo which later will be ported to web/android/ios, in the web version aside from the content of the main app functionality like `dashboard`  which usually don't require SEO accessibility, we put other screens like `About us`, `This Project` and ... 

When using static content servers like `serve-cli` by requesting each route the whole page will go through a full reload. 
This will hit SEO stuff really badly.

I'm wondering possible ways to serve SPA's using react-navigation as their router to be as SEO compliant as possible.

**Expected Behavior**

**How to reproduce**

**Your Environment**

    "@react-native-community/masked-view": "0.1.10",
    "@react-navigation/drawer": "^6.0.0-next.4",
    "@react-navigation/native": "^6.0.0-next.2",
    "@react-navigation/stack": "^5.14.4",
    "expo": "^41.0.1",
    "expo-app-loading": "^1.0.3",
    "expo-asset": "~8.3.1",
    "expo-av": "~9.1.2",
    "expo-clipboard": "~1.0.2",
    "expo-font": "~9.1.0",
    "expo-splash-screen": "~0.10.2",
    "expo-status-bar": "~1.0.4",
    "expo-updates": "~0.5.4",
    "express": "^4.17.1",
    "mobx": "^6.3.0",
    "mobx-react": "^7.1.0",
    "mobx-react-lite": "^3.2.0",
    "mobx-state-tree": "^5.0.1",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-native": "0.63.4",
    "react-native-gesture-handler": "~1.10.2",
    "react-native-markdown-display": "^7.0.0-alpha.2",
    "react-native-reanimated": "~2.1.0",
    "react-native-safe-area-context": "3.2.0",
    "react-native-screens": "~3.0.0",
    "react-native-svg": "12.1.0",
    "react-native-unimodules": "~0.13.3",
    "react-native-web": "~0.13.12"

**Comment by satya164** [comment]
I'm not sure why going to those pages requires full reload and why full reload hurts SEO when full reload is how must of the web works.

Regardless there's no recommendation regarding React Navigation here. It highly depends on which tools you use to serve the pages and if you're doing SSR or not, which is general web stuff.

So I'm closing this issue.
