### ISSUE TITLE
Nested Stack Navigators prevent scrolling for web

### ISSUE THREAD

**Issue by pors** [react-navigation/react-navigation#9566]
**Current Behavior**

Here is the code: https://snack.expo.io/@tositsa/nested-stacks-fixed-header-issue

**Expected Behavior**

The pink view is supposed to be scrollable, which is the case on iOS/Android, but not on web.

Note that with a double header (On line 48 change `headerMode="none"` to `headerMode="screen"`) it does scroll.

**How to reproduce**

See snack above.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | web |
| @react-navigation/native       | ^5.9.4 |
| @react-navigation/stack        | ^5.14.5 |
| react-native-gesture-handler   | ~1.10.2 |
| react-native-safe-area-context | 3.2.0 |
| react-native-screens           | ~3.0.0 |
| react-native                   |
| expo                           | 41 |
| node                           |
| npm or yarn                    |

**Comment by pors** [comment]
Updated to latest versions, problem remains

**Comment by pors** [comment]
An even more basic example (single stack, not nested) also doesn't work as intended: the content does scroll now, but the header scrolls with it. See snack here: https://snack.expo.io/@tositsa/nested-stacks-fixed-header-issue-2

On iOS/Android the header stays fixed at the top as expected.

**Comment by pors** [comment]
> flexGrow: 1,
> height: Platform.OS === 'web' ? Layout.window.height : undefined,

Thanks, that does it!
Snack with workaround here: https://snack.expo.io/@tositsa/nested-stacks-fixed-header-issue-2-workaround

PS I used [useWindowDimensions](https://reactnative.dev/docs/usewindowdimensions) as `Layout.window` doesn't seem to work

**Comment by buffaloDeveloper** [comment]
Yeah, that's just my variable that uses the same.  Glad it works for you.

**Comment by satya164** [comment]
> change headerMode="none" to headerMode="screen"

You should use `headerShown: false` in options instead of `headerMode="none"`. Not sure why `headerMode="none"` breaks it, but it's a legacy prop and entirely in removed in 6.x, and it works if you don't use it, so there's not much value in debugging this. So I'm closing the issue.

**Comment by satya164** [comment]
> @pors It doesn't solve the other issue though, that the header doesn't stick to the top for web

That's intentional. Mobile devices have limited screen space. Having both URL bar and header decreases that limited space massively. If you want to do it anyway, you can specify `cardStyle: { flex: 1 }` in `screenOptions`.

**Comment by buffaloDeveloper** [comment]
**headerShown: false** does not fix the scrolling issue on web when you have nested stack navigators.
The only thing I have found to work is adding flexGrow and the window height.

Here's some pseudocode below to demonstrate.

```
<NavContainer>
  <RootStack />
</NavContainer>

<RootStack.Navigator mode="modal">
  <RootStack.Screen name="Main" component={DrawerNavigator} options={{headerShown: false}}/>
</RootStack.Navigator>

<Drawer.Navigator
      openByDefault={Layout.isLargeDevice ? true : false}
      drawerType={Layout.isLargeDevice ? 'permanent' : 'slide'}
      drawerStyle={Layout.isLargeDevice ? {width: '17%', opacity: 1} : {opacity: 1}}
      overlayColor="transparent"
      drawerContent={(props) => <DrawerContent {...props} />}
    >
      <Drawer.Screen name="Home" component={HomeStack} />
</Drawer.Navigator>

<Stack.Navigator>
  <Stack.Screen 
    name="Home" 
    component={HomeScreen} 
    options={{
      ...defaultOptions,
      headerLeft: headerLeftToggleDrawer
    }} 
  />
<Stack.Navigator>
```
The HomeScreen component will not scroll without the flexGrow and window height.
