### ISSUE TITLE
When testing a Navigation container with jest the test passes, but the process fails

### ISSUE THREAD

**Issue by emmarq** [react-navigation/react-navigation#9568]
**Current Behavior**

The test succeeds, but the process fails. This is the output:
```
ReferenceError: You are trying to `import` a file after the Jest environment has been torn down.

      at Object.get Linking [as Linking] (node_modules/react-native/index.js:241:12)
      at node_modules/@react-navigation/native/lib/commonjs/useLinking.native.tsx:121:15
      at Object.invokeGuardedCallbackProd (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11308:10)
      at invokeGuardedCallback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11499:31)
      at flushPassiveEffectsImpl (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14560:11)
PASS __tests__/Navigation.test.js (15.215 s)
  ✓ just succeed (3 ms)
  Navigation Container
    ✓ run test without importing a file after it (236 ms)

Test Suites: 1 passed, 1 total
Tests:       2 passed, 2 total
Snapshots:   0 total
Time:        15.333 s
Ran all test suites matching /Navigation/i.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.
```

I haven´t found out why there is this `ReferenceError`. Even disabling linking it still happens.

**Expected Behavior**

The proccess should finish with no error code.

**How to reproduce**

This is the file with a simple test.

https://github.com/emmarq/RnReplica/blob/main/__tests__/Navigation.test.js

You can look the action with the result.

https://github.com/emmarq/RnReplica/runs/2547893152?check_suite_focus=true

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | N/A |
| @react-navigation/native       |  ^5.9.4 |
| react-native                   | 0.64 |
| expo                           | N/A |
| node                           |  12.16.3 |
| npm or yarn                    |  1.22.0 |

```
   "@testing-library/react-native": "^7.2.0",
    "babel-jest": "^26.6.3",
    "jest": "^26.6.3",
    "react-test-renderer": "^17.0.2"
```

Thank you for the help.

**Comment by emmarq** [comment]
> Hey! Thanks for opening the issue. The issue doesn't seem to contain a link to a repro (a [snack.expo.io](https://snack.expo.io) link or link to a GitHub repo under your username).
> 
> Can you provide a [minimal repro](https://stackoverflow.com/help/minimal-reproducible-example) which demonstrates the issue? A repro will help us debug the issue faster. Please try to keep the repro as small as possible and make sure that we can run it without additional setup.

https://github.com/emmarq/RnReplica

**Comment by satya164** [comment]
You'd need to use `jest.useFakeTimers();` in your tests

**Comment by emmarq** [comment]
Alright, i took the time to try to understand what useFakeTimers do, i was hesitant to use it because its big impact on all async tasks. So far it turns out that i might need to refactor my tests. 

The example goes like this

```js
 it('run test without importing a file after it', async () => {
    const { getByText } = render(<App />);
    await act(async () => {});

    getByText('Go to Screen B');
  });
```

The changes i think necessary involves removing the asynchronous test. No more async function for `it` and use the mock timers of jest to accomplish the same behaviour. I understand it like forcing a sync behaviour of async task by "tweaking the time" using the [jest api](https://jestjs.io/docs/timer-mocks) and somehow understanding the moments the side effects happens in the app, those moments are the key indicators where to put, or not to put the timer modifications.

```js
jest.useFakeTimers();
 it('run test without importing a file after it', () => {
    const { getByText } = render(<App />);
    act(() => jest.runAllTimers()); // In the case of an app with side effects on mount, 
                                    // this will trigger them in a safe context, rigth? 
                                    // in the case of another effects triggered by 
                                    // the press of a button, for example, 
                                    // i guess this would be neccesary as well.

    getByText('Go to Screen B');
  });
```

This line `act(() => jest.runAllTimers());` and previously this one `await act(async () => {});` is there to avoid  the warning ` An update to ForwardRef(NavigationContainer) inside a test was not wrapped in act(...)` in my actual test case. https://stackoverflow.com/questions/61695139/async-testing-react-navigation-5-in-jest-navigationcontainer-causes-console-err

I am now asking if this is the best way to go to fix the issue. Or is there any better alternative?

**Comment by emmarq** [comment]
Ok, i am closing this as my issue is resolved now, but before doing it, i hit one more problem with the animations of some navigators and the fake timers. I ended up following this comment https://github.com/facebook/jest/issues/5147#issuecomment-353274996

Maybe this can be of little to someone else.

**Comment by jehartzog** [comment]
@emmarq I was able to resolve this without using fake timers using the mock:
```tsx
jest.mock('@react-navigation/native/lib/commonjs/useLinking.native', () => ({
  default: () => ({getInitialState: {then: jest.fn()}}),
  __esModule: true,
}));
```

**Comment by professorkolik** [comment]
What worked for us is to disable linking in tests

Assuming you have 

```
<NavigationContainer
      ref={navigationRef}
      linking={{
         // Disable when JEST runs
         enabled: !process.env.JEST_WORKER_ID,
         prefixes: [...],
         config: {
           ....
         },
       async getInitialURL() {
          const url = await Linking.getInitialURL();

           if (!url) return;

           return url;
        },
        // Custom function to subscribe to incoming links
        subscribe(listener) {
          ...
        },
      }}>{children}</NavigationContainer>
```
enabled: !process.env.JEST_WORKER_ID,
