### ISSUE TITLE
Header overlaps in IOS

### ISSUE THREAD

**Issue by DeniferSantiago** [react-navigation/react-navigation#9571]
**Current Behavior**

- What code are you running and what is happening?
I am using react-navigation with the following navigation structure:
```
StackNavigator: App
-> TabNavigator: TabScreens
     -> StackNavigator: MyProfile
          -> StackNavigator: Reviews //All screens at this depth level have the problem
```
https://user-images.githubusercontent.com/41799285/117896282-363d0180-b28e-11eb-97d3-0c0e3134e794.mp4

StackNavigatorReviews code:
```
<StackReview.Navigator
            headerMode="none"
            screenOptions={{
                cardStyleInterpolator:
                    CardStyleInterpolators.forScaleFromCenterAndroid,
                gestureEnabled: true,
                gestureDirection: "vertical"
            }}>
            <StackReview.Screen
                component={MissingReviews}
                name={ReviewStack.ReviewsMissing}
            />
            <StackReview.Screen
                component={MakeReview}
                name={ReviewStack.MakeReview}
            />
</StackReview.Navigator>
```
The header I set on each screen as I don't use the react-navigation header, also in the root of my app I have a SafeAreaProvider (react-native-safe-area-context) but I don't use any SafeAreaView Should I use it in all the screens? as you could see in the video in the TabHome the Header is displayed correctly.

Does nesting influence? since it only happens to me with the screens at that level of nesting.

The styles of all my headers:
```javascript
header: {
    marginTop: Platform.OS === "ios" ? 0 : getStatusBarHeight(),
    backgroundColor: theme.colors.similar,
    height: Normalize(50),
    zIndex: 4
}
```
**Expected Behavior**

- What do you expect should be happening?

**How to reproduce**
I guess it can be recreated by implementing navigators with the following structure:

```
StackNavigator: App
-> Screen: Login
-> Screen: OnBoarding
-> Screen: SignUp
-> TabNavigator: TabScreens
     -> Screen: Home
     -> StackNavigator: Search
     -> StackNavigator: MyProfile
          -> StackNavigator: Reviews //All screens at this depth level have the problem
               -> Screen: ReviewList
               -> Screen: MakeReview
```

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS                 |14.5
| @react-navigation/native       |^5.9.4
| @react-navigation/stack        |^5.14.4
| react-native-gesture-handler   |^1.6.1
| react-native-safe-area-context |^3.0.5
| react-native-screens           |^2.16.1
| react-native                   |0.64.0
| node                           |14.1.0
| yarn                    |1.22.10

**Comment by raajnadar** [comment]
When you use a custom header you need to handle the safe area.

https://reactnavigation.org/docs/handling-safe-area/

**Comment by DeniferSantiago** [comment]
resolved by avoiding nesting navigators more than 3 levels deep
