### ISSUE TITLE
Can't change phone navbar background color (android)

### ISSUE THREAD

**Issue by AurimasG12** [react-navigation/react-navigation#9572]
**Current Behavior**
I'm trying to change android phone bottom navigation background color.
This is my code.

`<Tab.Navigator
      initialRouteName="Meetings"
      tabBarOptions={{
        showLabel: true,
        tabStyle: styles.button,
        labelStyle: styles.label,
      }}
      screenOptions={({route}) => ({
        tabBarVisible: true,
        tabBarIcon: ({color, size}) => {
          const iconName = getIconName(route);
          return <Icon name={iconName} size={size} color={color} />;
        },
      })}>
      <Tab.Screen name="Meetings" options={{title: t('meetings')}} component={MeetingsStack} />
      <Tab.Screen name="Groups" options={{title: t('groups')}} component={ConversationsStack} />
      <Tab.Screen name="Contacts" options={{title: t('contacts')}} component={ContactsStack} />
    </Tab.Navigator>`
**Expected Behavior**

In `styles.button` I have included background color I guess it should also change my phones navbar background.

**Your Environment**

| software                      | version |
| ----------------------------- | ------- |
| iOS or Android                | 10
| @react-navigation/native      | 5.8.10
| @react-navigation/bottom-tabs |  5.9.0
| react-native-screens          | 2.1.1
| react-native                  | 0.63.4
| expo                          | 
| node                          | 14
| npm or yarn                   |

**Comment by eqlion** [comment]
@AurimasG12, take a look at this snack: https://snack.expo.io/AyzuH2pbV. I've taken the example from [the documentation](https://reactnavigation.org/docs/tab-based-navigation), upgraded `@react-navigation/native` and `@react-navigation/bottom-tabs` to the latest versions and added `backgroundColor`:

```jsx
tabStyle: {
            backgroundColor: "blue",
          }
```

Can you post your `styles.button`?
