### ISSUE TITLE
Content goes behind Tab Bar when closing the keyboard

### ISSUE THREAD

**Issue by aitorct** [react-navigation/react-navigation#9574]
**Current Behavior**
Currently, if `keyboardHidesTabBar` is set to `true` and there's content stacked on top of the keyboard, such as a TextInput, it'll go behind the tab bar when the keyboard is being closed, and then jump up to its correct position.

![Current behavior demo](https://user-images.githubusercontent.com/6463569/118135854-c6508780-b403-11eb-9ef3-d5bc59eda571.gif)

**Expected Behavior**
Content should never be placed behind the tab bar, it should always be on top of the keyboard and the tab bar.

**How to reproduce**
[https://snack.expo.io/F1JjEqa7p](https://snack.expo.io/F1JjEqa7p)

**Your Environment**

| software                      | version |
| ----------------------------- | ------- |
| iOS or Android                | Both
| @react-navigation/native      | 5.9.4
| @react-navigation/bottom-tabs | 5.11.10
| react-native-screens          | 3.0.0
| expo                          | 41

**Comment by satya164** [comment]
You can find several issues about `keyboardHidesTabBar` in the repo and read about the limitations. We handle it the best we can with the limited APIs. If you think there are better ways to handle it and have an idea, feel free to send a pull request.

I don't want to repeat the same replies again and again, so I'm closing the issue.
