### ISSUE TITLE
Touchables interrupt/cancel navigation gestures

### ISSUE THREAD

**Issue by cwhenderson20** [react-navigation/react-navigation#9577]
**Current Behavior**

I'm trying out React Navigation v6 and I believe I've found a regression with gesture handling. It appears that touchables (imported from plain old React Native) interrupt gesture handlers. This becomes a problem when you have touchable items (mostly of the "row" style) that are located where the user might put their thumb to swipe back. In my case, many of those touchables navigate somewhere else, so in some cases, you get this weird double navigation effect. 

From what I can tell, this does not happen in v5. See the videos below for a comparison:

https://user-images.githubusercontent.com/5496110/118225221-b318d880-b452-11eb-86bc-2f7a75ce9703.mp4

https://user-images.githubusercontent.com/5496110/118225224-b318d880-b452-11eb-93bb-51446455d0db.mp4

**Expected Behavior**

I believe v5 is the correct behavior. You can see the responder get canceled when the gesture starts (the highlight disappears)

**How to reproduce**
[Here's a snack](https://snack.expo.io/@cwhenderson20/touchable-steals-gesture) that reproduces the issue.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | iOS (may happen on Android, but back gestures are iOS only)
| @react-navigation/native       | 6.0.0-next
| @react-navigation/stack        | 6.0.0-next
| react-native-gesture-handler   | 1.10.2
| react-native-safe-area-context | 3.2.0
| react-native-screens           | 3.0.0
| react-native                   | 0.64

**Comment by satya164** [comment]
There haven't been any changes regarding gesture handling between 5.x and 6.x to my knoweldge

**Comment by cwhenderson20** [comment]
@satya164 thanks for the reply. I kept all other package versions the same and switched out the react-navigation packages with their latest 5.x counterparts and couldn't get it to happen once.

**Comment by cwhenderson20** [comment]
I'm actually not using v5 in my app. I began with v6 given its impending release and relative stability. I noticed the issue in my app and only decided to see how it worked in v5 after creating the snack repro.

**Comment by cwhenderson20** [comment]
Just to make it easier to compare, I [created a snack](https://snack.expo.io/@cwhenderson20/touchable-steals-gesture-v5) with v5 of react-nav libraries pre-loaded into the package.json.

I've tried to look into this a bit, but with my limited knowledge of the internals of the libraries have found that @satya164 seems to be correct that gesture handling hasn't changed.

That notwithstanding, there's definitely a difference in behavior between v5 and v6.

**Comment by cwhenderson20** [comment]
On a whim, I wondered if it could be `react-native-screens` causing the issue (despite the requested version being `~3.0.0` in both provided snacks). Downgrading the snack using v6 to use `react-native-screens: ^2` fixes the issue. 

Let me know if this still belongs here or if I should move the issue to that library.

**Comment by tien** [comment]
The same thing is happening on v5 as mentioned in the issue that I've raised #9657

**Comment by satya164** [comment]
Can you also try  `enableScreens(false)` with screens 3.0?

**Comment by tien** [comment]
Yes disabling screen also work, I've created an issue at react-native-screens.

**Comment by cwhenderson20** [comment]
Closing due to the issue being in react-native-screens (more info [here](https://github.com/software-mansion/react-native-screens/issues/972#issuecomment-861463305)). Version 3.4.0 fixes the issue for me.
