### ISSUE TITLE
A navigator can only contain 'Screen', 'Group' or 'React.Fragment' as its direct children

### ISSUE THREAD

**Issue by KingAmo** [react-navigation/react-navigation#9578]
```
<Stack.Navigator>
  {
    isLogin ? <ComponentA /> :  <ComponentB />
  }
</Stack.Navigator>


const ComponentA = () => (
 arrA.map( v => <Stack.Screen name={v.name} component={v.component} />)
)

const ComponentB = () => (
 arrB.map( v => <Stack.Screen name={v.name} component={v.component} />)
)

```

**Current Behavior**

```
Error: A navigator can only contain 'Screen', 'Group' or 'React.Fragment' as its direct children 
(found 'ComponentA'). To render this component in the navigator, pass it in the 'component' prop to 'Screen'.
```

**Expected Behavior**
no error

**How to reproduce**

- You must provide a way to reproduce the problem. If you are having an issue with your machine or build tools, the issue belongs on another repository as that is outside of the scope of React Navigation.
- Either re-create the bug on [Snack](https://snack.expo.io) or link to a GitHub repository with code that reproduces the bug.
- Explain how to run the example app and any steps that we need to take to reproduce the issue from the example app.
- Keep the repro code as simple as possible, with the minimum amount of code required to repro the issue.
- Before reporting an issue, make sure you are on latest version of the package.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | both
| @react-navigation/native       | ^6.0.0-next.7
| react-native                   | 0.64.1
| expo                           |
| node                           |
| npm or yarn                    | yarn

**Comment by KingAmo** [comment]
in fact, i want use some hooks in `componentA` and  `componentB`, so i have to use them as function component, any help please?

**Comment by KingAmo** [comment]
@satya164  i thinks this is a common use case,  i asked this in [StackOverflow](https://stackoverflow.com/questions/67584461/a-navigator-can-only-contain-screen-group-or-react-fragment-as-its-direct/67584664#67584664), any help please

**Comment by Hmoulvad** [comment]
I agree this is really a common issue. If you have multiple tabs with the same screens. It would be super nice to be able to pack them into modules, that you can render within the Stack. Without having to use the Stack.Screen. Imagine having a group of 20 screens used across 5 tabs.

**Comment by guillainbisimwa** [comment]
Be sure you are on the latest version of these packages :

- "@react-navigation/bottom-tabs": "^6.0.8",
- "@react-navigation/native": "^6.0.5",
- "@react-navigation/native-stack": "^6.2.3",
- "@react-navigation/stack": "^6.0.10",
- "react-native-screens": "^3.8.0",

**Comment by mod4-lvr** [comment]
Change this 
<Stack.Navigator> <SearchModule Stack={Stack} /> </Stack.Navigator>
into this
<React.Fragment>{SearchModule()}</React.Fragment>

**Comment by Pranishparaj986** [comment]
> 

Can you help me I am having the same problem

**Comment by TySol** [comment]
+1 Having the same issue

**Comment by Hmoulvad** [comment]
Furthermore I have another example on how to solve this issue:

`
function selfServiceScreens() {
  return (
    <>
      <Stack.Screen name={WarehouseScreens.StartSelfService} component={StartSelfServiceScreen} />
      <Stack.Screen name={WarehouseScreens.SelfServiceCartControl} component={SelfServiceCartControlScreen} />
      <Stack.Screen
        name={WarehouseScreens.SelfServiceBasket}
        component={SelfServiceBasketScreen}
        options={{
          animationEnabled: true,
        }}
      />
      <Stack.Screen
        name={WarehouseScreens.Checkout}
        component={CheckoutScreen}
        options={{
          cardStyleInterpolator: CardStyleInterpolators.forBottomSheetAndroid,
          gestureEnabled: false,
          headerTintColor: Colors.WHITE,
          headerStyle: {
            backgroundColor: Colors.BLACK,
          },
        }}
      />
      <Stack.Screen
        name={WarehouseScreens.CheckoutBasketControlScreen}
        component={CheckoutBasketControlScreen}
        options={{
          cardStyleInterpolator: CardStyleInterpolators.forBottomSheetAndroid,
          gestureEnabled: false,
          headerTintColor: Colors.WHITE,
          headerStyle: {
            backgroundColor: Colors.BLACK,
          },
        }}
      />
    </>
  );
}
`

Then you can use them as screens like this. 

`
{(() => selfServiceScreens())()}
`

The syntax is super ugly but i gets the job done.

**Comment by ya5huk** [comment]
Any good answer yet?

**Comment by rachitGulati** [comment]
I have used it like this:

```
 {isSignedIn
              ? AuthStack({Screen: Stack.Screen})
              : UnAuthStack({Screen: Stack.Screen})}
```

// AuthStack.tsx file
```

const AuthStack = ({Screen}: IAuthStack) => {
  return (
    <>
      <Screen name="Main" component={Main} options={{...commonOptions}} />
      <Screen
        name="ActivityManager"
        component={ActivityManager}
        options={{...commonOptions}}
      />
    </>
  );
};
```
// UnAuthStack.tsx file
```
const UnAuthStack = ({Screen}: IUnAuthStack) => {
  return (
    <>
      <Screen
        name="LogIn"
        component={LogInManager}
        options={{...commonOptions}}
      />
      <Screen
        name="SignUp"
        component={SignUpManager}
        options={{...commonOptions}}
      />
      <Screen
        name="VerifyOTP"
        component={VerifyOTPManager}
        options={{...commonOptions}}
      />
    </>
  );
};
```

You can pass whole `Stack` as well in the new component but for me `Screen` was enough :)

**Comment by sandeepDevJs** [comment]
> I have used it like this:
> 
> ```
>  {isSignedIn
>               ? AuthStack({Screen: Stack.Screen})
>               : UnAuthStack({Screen: Stack.Screen})}
> ```
> 
> // AuthStack.tsx file
> 
> ```
> 
> const AuthStack = ({Screen}: IAuthStack) => {
>   return (
>     <>
>       <Screen name="Main" component={Main} options={{...commonOptions}} />
>       <Screen
>         name="ActivityManager"
>         component={ActivityManager}
>         options={{...commonOptions}}
>       />
>     </>
>   );
> };
> ```
> 
> // UnAuthStack.tsx file
> 
> ```
> const UnAuthStack = ({Screen}: IUnAuthStack) => {
>   return (
>     <>
>       <Screen
>         name="LogIn"
>         component={LogInManager}
>         options={{...commonOptions}}
>       />
>       <Screen
>         name="SignUp"
>         component={SignUpManager}
>         options={{...commonOptions}}
>       />
>       <Screen
>         name="VerifyOTP"
>         component={VerifyOTPManager}
>         options={{...commonOptions}}
>       />
>     </>
>   );
> };
> ```
> 
> You can pass whole `Stack` as well in the new component but for me `Screen` was enough :)

It worked!, But I cannot use hooks in any stacks .. it throws "Rendered more hooks than during the previous render."

**Comment by TechSaq** [comment]
> Furthermore I have another example on how to solve this issue:
> 
> ```
> function selfServiceScreens() {
>   
> return (
>     <>
>       <Stack.Screen name={WarehouseScreens.StartSelfService} component={StartSelfServiceScreen} />
>       <Stack.Screen name={WarehouseScreens.SelfServiceCartControl} component={SelfServiceCartControlScreen} />
>       <Stack.Screen
>         name={WarehouseScreens.SelfServiceBasket}
>         component={SelfServiceBasketScreen}
>         options={{
>           animationEnabled: true,
>         }}
>       />
>       <Stack.Screen
>         name={WarehouseScreens.Checkout}
>         component={CheckoutScreen}
>         options={{
>           cardStyleInterpolator: CardStyleInterpolators.forBottomSheetAndroid,
>           gestureEnabled: false,
>           headerTintColor: Colors.WHITE,
>           headerStyle: {
>             backgroundColor: Colors.BLACK,
>           },
>         }}
>       />
>       <Stack.Screen
>         name={WarehouseScreens.CheckoutBasketControlScreen}
>         component={CheckoutBasketControlScreen}
>         options={{
>           cardStyleInterpolator: CardStyleInterpolators.forBottomSheetAndroid,
>           gestureEnabled: false,
>           headerTintColor: Colors.WHITE,
>           headerStyle: {
>             backgroundColor: Colors.BLACK,
>           },
>         }}
>       />
>     </>
>  );
> }
> ```
> 
> Then you can use them as screens like this.
> 
> `{(() => selfServiceScreens())()}`
> 
> The syntax is super ugly but i gets the job done.

It is working but I just want to know if it has any performance issues or something else?

**Comment by RostyslavZahorulko** [comment]
In my case, the error was simply due to the incorrectly specified path to the font folder in my App component. If none of the above helped - check your imports

**Comment by tier3guy** [comment]
I was facing the same but haven't get solution. And eventually broke the Stack.Navigator into components instead keeping it into one parent file like this.

In the main file ---> Top Level 
![image](https://user-images.githubusercontent.com/73595465/218019790-c213c509-9afd-4c15-bfc7-58c18699ccd4.png)

In sub-component file ---> Next Level / Child Level
![image](https://user-images.githubusercontent.com/73595465/218019919-3ce9f767-8c20-4755-ba8e-3237ac2f1738.png)


If someone get the solution regarding keeping the Stack.Navigator at the top level please do share.

**Comment by Revitalismo** [comment]
Worst

**Comment by echoeyecodes** [comment]
You could create a Shared Stack Navigation template component like this

```
type SharedStackNavigationComponentProps = NativeStackNavigatorProps & {

}

export const SharedStackNavigationComponent = (props: SharedStackNavigationComponentProps) => {

    return <Stack.Navigator {...props as any}>
        {/* // other Stack.Screen components you want to use */}
        {props.children}
        
        {/* // shared screens */}
        <Stack.Group>
        {arrA.map( v => <Stack.Screen name={v.name} component={v.component} />)}
        </Stack.Group>
    </Stack.Navigator>
}
```

Now you can reuse this anywhere else and add other Stack.Screen components of your choice
```
export const MyNewScreen = () => {

    return <SharedStackNavigationComponent>
           <Stack.Screen name="MyScreen" component={MyScreen} />
    </SharedStackNavigationComponent>
    
}

```

**Comment by ajlee4** [comment]
any solutions?

**Comment by ajlee4** [comment]
@satya164 any help please

**Comment by pfcodes** [comment]
> Furthermore I have another example on how to solve this issue:
> 
> ```
> function selfServiceScreens() {
>   
> return (
>     <>
>       <Stack.Screen name={WarehouseScreens.StartSelfService} component={StartSelfServiceScreen} />
>       <Stack.Screen name={WarehouseScreens.SelfServiceCartControl} component={SelfServiceCartControlScreen} />
>       <Stack.Screen
>         name={WarehouseScreens.SelfServiceBasket}
>         component={SelfServiceBasketScreen}
>         options={{
>           animationEnabled: true,
>         }}
>       />
>       <Stack.Screen
>         name={WarehouseScreens.Checkout}
>         component={CheckoutScreen}
>         options={{
>           cardStyleInterpolator: CardStyleInterpolators.forBottomSheetAndroid,
>           gestureEnabled: false,
>           headerTintColor: Colors.WHITE,
>           headerStyle: {
>             backgroundColor: Colors.BLACK,
>           },
>         }}
>       />
>       <Stack.Screen
>         name={WarehouseScreens.CheckoutBasketControlScreen}
>         component={CheckoutBasketControlScreen}
>         options={{
>           cardStyleInterpolator: CardStyleInterpolators.forBottomSheetAndroid,
>           gestureEnabled: false,
>           headerTintColor: Colors.WHITE,
>           headerStyle: {
>             backgroundColor: Colors.BLACK,
>           },
>         }}
>       />
>     </>
>  );
> }
> ```
> 
> Then you can use them as screens like this.
> 
> `{(() => selfServiceScreens())()}`
> 
> The syntax is super ugly but i gets the job done.

Does using a function affect performance?

**Comment by badalsaibo** [comment]
I think this is an important feature which helps in code organization and should be looked into.
