### ISSUE TITLE
For web, doesn't refresh the screen properly

### ISSUE THREAD

**Issue by vitthalzephyr** [react-navigation/react-navigation#9579]
**Current Behavior**
created a simple stack navigator like this -
const Stack = createStackNavigator();
Then added my screens - 
    <Stack.Navigator>
      {!state.isLoggedIn ?
        <Stack.Screen name="Login" component={Login} options={{headerShown: false}}/>
      :
        <>
          <Stack.Screen name="QuickInvest" component={QuickInvest}
            options={{headerShown: true, headerLeft: null, headerTitle: props => <Header {...props} />}}/>
....</>
And finally in the App:
const App = () => {

  return (
    <AuthProvider>
      <NavigationContainer linking={linking} headerMode="screen">
        <Navigator/>
      </NavigationContainer>
    </AuthProvider>
  );
};
The navigation happens properly. Even the browser shows the correct address in the address bar and the page title etc.
**Expected Behavior**
In the web version (using react-native-web(0.14.8) upon browser refresh, it always goes to the first screen in the stack whereas it should just stay on the current URL whichever screen is pointing to.

**How to reproduce**

Write a simple stackNavigator and run it on web using react-native-web like one I shown above.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| Web            |
| @react-navigation/native  : 5.9.4     |
| @react-navigation/stack  : 5.14.4      |
| react-native-gesture-handler : na  |
| react-native-safe-area-context : 3.2.0|
| react-native-screens  : 3.1.1         |
| react-native  : 0.63.3                 |
| expo   : na                       |
| node    :  14.16.1                       |
| npm or yarn   : yarn 1.22.10                 |

**Comment by vitthalzephyr** [comment]
> The versions mentioned in the issue for the following packages differ from the latest versions on npm:
> 
> * `@react-navigation/stack` (found: `5.14.4`, latest: `5.14.5`)
> 
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?

Yes. The issue still exists

**Comment by samaneh-kamalian** [comment]
add `linking={{ enabled: true }}` in `NavigationContainer`

**Comment by vitthalzephyr** [comment]
> add `linking={{ enabled: true }}` in `NavigationContainer`

Didn't work

**Comment by sean-m-oleary** [comment]
same problem here. Have been pulling my hair out for it for months.

**Comment by vitthalzephyr** [comment]
What I observed further is if I remove the conditional part in Stack Navigator like below :
{!state.isLoggedIn ?
<Stack.Screen name="Login" component={Login} options={{headerShown: false}}/>
:
<>
<Stack.Screen name="QuickInvest" component={QuickInvest}
options={{headerShown: true, headerLeft: null, headerTitle: props => <Header {...props} />}}/>
....</>
Then it works as expected, i.e. the browser upon refresh stays on the same page. I can't understand why this should cause such problem and what is an alternative to this.

**Comment by sean-m-oleary** [comment]
yep i have a similar solution. I think it likely has something to do with the presence of the logged in routes. If they dont exist when rn tries to deep link to them it just defaults to the first route in the first navigator in the navigation container. Would be interesting to see one of the contributors confirm this is the case.
