### ISSUE TITLE
navigate back error with react-navigation 6

### ISSUE THREAD

**Issue by surethink** [react-navigation/react-navigation#9582]
**Current Behavior**
I have 4 screens in native stack A B C D, I'd like to navigate back to B from D. My code: navigation.navigate("B")
When in react-navigation 5.x,  it works well
Now I update to react-navigation 6,  It  shows error :TypeError: undefined is not an object (evaluating 'route.params.xxx')
I also tried the method, navigation.navigate({key:xxxxx}), not works too.

**Expected Behavior**
just navigate back to specified route in native stack, don't need to pass params again

**How to reproduce**
just open 4 screens in native stack, A B C D, then navigate back to B from D, and in screen B destructure "route.params", you will get the error

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | ios
| @react-navigation/native       | 6.0.0-next.7
| @react-navigation/stack        | 6.0.0-next.15
| react-native-gesture-handler   | ^1.10.3
| react-native-safe-area-context | ^3.2.0
| react-native-screens           | ^3.1.1
| react-native                   | 0.64

**Comment by satya164** [comment]
https://reactnavigation.org/docs/6.x/upgrading-from-5.x/#params-are-now-overwritten-on-navigation-instead-if-merging

> While the default has changed, it's still possible to merge params if you need it. To get the previous behavior, you can pass an object to navigate with merge: true and it'll merge the params
