### ISSUE TITLE
Header Back Icon Not Showing on Android and Web with Monorepo

### ISSUE THREAD

**Issue by ktprograms** [react-navigation/react-navigation#9584]
**Current Behavior**

I generated a React Native + Web Monorepo project based on [this](https://github.com/brunolemos/react-native-web-monorepo) template. Then I ran `yarn workspace components add @react-navigation/native @react-navigation/stack react-native-reanimated react-native-gesture-handler react-native-screens react-native-safe-area-context @react-native-community/masked-view` as well as `yarn workspace mobile add @react-navigation/native @react-navigation/stack react-native-reanimated react-native-gesture-handler react-native-screens react-native-safe-area-context @react-native-community/masked-view` (as suggested in the [tutorial](https://dev.to/brunolemos/tutorial-100-code-sharing-between-ios-android--web-using-react-native-web-andmonorepo-4pej) associated with the template. On iOS, the Back button in the header works as expected, but on Android and Web, the button is invisible but functional.
Link to my code: [https://github.com/ktprograms/rnw-monorepo/](https://github.com/ktprograms/rnw-monorepo/).
Screenshot (iOS simulator, working): 
![Simulator Screen Shot - iPhone 12 mini - 2021-05-15 at 13 41 02](https://user-images.githubusercontent.com/71804605/118349440-3b969680-b583-11eb-81ee-174f9f8bef17.png)
Screenshot (Android emulator, back button missing):
![Screenshot_1621057324](https://user-images.githubusercontent.com/71804605/118349462-5ff27300-b583-11eb-9f82-a2daff5e9a00.png)
Web looks the same as Android.

**Expected Behavior**

Back button icon should be shown on Android and Web.

**How to reproduce**

```
git clone https://github.com/ktprograms/rnw-monorepo.git
cd rnw-monorepo
yarn
cd packages/mobile/ios && pod update && pod install && cd -
yarn start
```
Then click the 'Go To Details' Button.

Source code is in packages/components/src/App.tsx

**Your Environment**
I'm using MacOS 11.2.3 on a MacBook Air (M1, 2020). The above steps to reproduce were run in a Terminal.app window with Rosetta enabled.

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | iOS 14.5 Emulator, Android S Emulator
| @react-navigation/native       | ^5.9.4
| @react-navigation/stack        | ^5.14.5
| react-native-gesture-handler   | ^1.10.3
| react-native-safe-area-context | ^3.2.0
| react-native-screens           | ^3.2.0
| react-native                   | 0.63.3
| expo                           | not using
| node                           | v16.0.0
| npm or yarn                    | yarn 1.22.10

**Comment by satya164** [comment]
It's not a bug in React Navigation. It's a bug in Metro on Android. You can see workarounds here https://github.com/react-navigation/react-navigation/blob/dc4ffc0171b4535fe1b6e839b9d54350121bcf55/example/metro.config.js#L71

For web, likely something missing in your webpack config to load assets that you need to fix.

**Comment by ktprograms** [comment]
Hi, where should I point the `req.url` to in metro.config.js? I tried `console.log` -ing the `req.url` and it already points to `/node_modules/@react-navigation/stack/src/views/assets/back-icon@3x.png?platform=android&hash=a364dc7a784101f7c8f6791c7b4514ce`

**Comment by ktprograms** [comment]
Nevermind, I managed to fix it. I added these lines to `packages/mobile/metro.config.js`:
```
server: {
  enhanceMiddleware: (middleware) => {
    return (req, res, next) => {
      // When an asset is imported outside the project root, it has wrong path on Android
      // So we fix the path to correct one
      if (/\/node_modules\/@react-navigation\/stack\/src\/views\/assets\/.+\.png\?.+$/.test(req.url)) {
        req.url = `/assets/../../node_modules/../${req.url}`;
      }

      return middleware(req, res, next);
    };
  }
}
```

**Comment by ktprograms** [comment]
Hi, can you please provide an example webpack `config-overrides.js` (The monorepo is using [react-app-rewired](https://github.com/timarney/react-app-rewired). I'm new to web development so I don't really understand webpack.

**Comment by bnussman** [comment]
OMG. How is this not fixed!?
