### ISSUE TITLE
On web, title tags generated cannot be disabled or overriden by other methods

### ISSUE THREAD

**Issue by ezekiel747** [react-navigation/react-navigation#9585]
**Current Behavior**
Title tags set by default by react-navigation  can't be overriden by other methods (react-helment for example)

**Expected Behavior**

I was expecting the title set with react-helmet to have priority over the title automatically set by react-navigation.
Is there a way to disable the title setting by react-navigation?
Meta description works fine.

**How to reproduce**

```
// MainNavigator.js
<Drawer.Navigator>
      <Drawer.Screen name='route1' component={SampleComponent} />
</Drawer.Navigator

// SampleComponent.js
import { Helmet } from "react-helmet";
const SampleComponent  = (props) => (
    <>
      <Helmet>
        <title>{props.title}</title>
        <meta name="description" content={props.text.substring(0, 120)} />
      </Helmet>
    </>
)
```

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | web
| @react-navigation/native       |  5.9.4
| react-native                   | 0.63.2
| expo                           | 41.0.1
| node                           | 14.15.3
| npm or yarn                    | npm

**Comment by satya164** [comment]
https://reactnavigation.org/docs/navigation-container/#documenttitleenabled

**Comment by ezekiel747** [comment]
Thank you. Sorry, i must have missed this piece of config.
