### ISSUE TITLE
Nested navigators re-render, and throw warning: 'Accessing the 'state' property of the 'route' object is not supported'

### ISSUE THREAD

**Issue by nextriot** [react-navigation/react-navigation#9591]
**Current Behavior**

I'm running the most basic configuration that I could think of that reproduces this bug. A tab bar navigator nested in a native stack navigator. Though it seems to be an issue with all nested navigators.

The `'Accessing the 'state' property of the 'route' object is not supported'` warning is persistent through the apps lifecycle when switching screens. I've installed [Why Did You Render](https://github.com/welldone-software/why-did-you-render) which is reporting re-renders in `StaticContainer` due to changes in the `route` & `children` props.

Repo & code further down.

<img width="400" alt="Simulator warning" src="https://user-images.githubusercontent.com/711457/118406614-e924ab00-b652-11eb-802b-3a8d3f9aaa83.png">

<img width="800" alt="WDYR warnings" src="https://user-images.githubusercontent.com/711457/118406836-0e65e900-b654-11eb-96e7-2659be42f809.png">

**Expected Behavior**

I expect nested navigators to be usable without the core code causing re-renders. 

**How to reproduce**

Repo with code reproducing the issue: https://github.com/nextriot/react-navigation-issue

App code for completeness:

```js
import 'react-native-gesture-handler';
import * as React from 'react';
import {View, Text} from 'react-native';

import {NavigationContainer} from '@react-navigation/native';
import {enableScreens} from 'react-native-screens';
import {createNativeStackNavigator} from 'react-native-screens/native-stack';
import {createBottomTabNavigator} from '@react-navigation/bottom-tabs';

enableScreens();

const Stack = createNativeStackNavigator();
const Tab = createBottomTabNavigator();

const Home = () => {
  return (
    <View>
      <Text>Home</Text>
    </View>
  );
};

const Settings = () => {
  return (
    <View>
      <Text>Settings</Text>
    </View>
  );
};

const TabNavigator = () => {
  return (
    <Tab.Navigator>
      <Tab.Screen name="Home" component={Home} />
      <Tab.Screen name="Settings" component={Settings} />
    </Tab.Navigator>
  );
};

const App = () => {
  return (
    <NavigationContainer>
      <Stack.Navigator>
        <Stack.Screen name="Main" component={TabNavigator} />
      </Stack.Navigator>
    </NavigationContainer>
  );
};

export default App;
```

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Both
| @react-navigation/native       | ^5.9.4
| @react-navigation/bottom-tabs | ^5.11.11
| react-native-screens | ^3.2.0
| @react-native-community/masked-view | ^0.1.11
| react-native                   | 0.64.1
| react | 17.0.1
| react-native-gesture-handler | ^1.10.3
| react-native-reanimated | ^2.1.0
| react-native-safe-area-context | ^3.2.0
| @welldone-software/why-did-you-render | ^6.1.1

**Comment by satya164** [comment]
Why is re-render a bug? 

> The 'Accessing the 'state' property of the 'route' object is not supported' warning is persistent through the apps lifecycle when switching screens. I've installed Why Did You Render

Sounds like that's what causes the warning

**Comment by nextriot** [comment]
> Why is re-render a bug?
> 
> > The 'Accessing the 'state' property of the 'route' object is not supported' warning is persistent through the apps lifecycle when switching screens. I've installed Why Did You Render
> 
> Sounds like that's what causes the warning

Perhaps it’s not. I understand that wdyr is indeed the reason for the warning, but it’s meant to surface redundant re-renders.

So is your stance that this is essentially a false positive? Any idea as to why wdyr is reporting the issue?

**Comment by satya164** [comment]
> Any idea as to why wdyr is reporting the issue

That property is deprecated, so not to break existing apps, we show a warning in a getter when the property is accessed. Wdyr would need to access all properties to compare what changed, which is likely causing the warning.

**Comment by nextriot** [comment]
Under

> > Any idea as to why wdyr is reporting the issue
> 
> That property is deprecated, so not to break existing apps, we show a warning in a getter when the property is accessed. Wdyr would need to access all properties to compare what changed, which is likely causing the warning.

Understood. Thanks for the clarification and prompt response. I’ll close the issue for now as I’m not seeing any hindrance in performance from the warning, I just thought it wise to report. 

Thanks again.
