### ISSUE TITLE
Screen is rendered not in order

### ISSUE THREAD

**Issue by mikheyrojo** [react-navigation/react-navigation#9595]
**Current Behavior**

I have two Stack.Navigators - When I go out of the `if` statement -> I come not to the first screen, but to the second.
You can see that the title changes.

```
https://snack.expo.io/@mikheyrojo/strange-behavior

```

**Expected Behavior**

I expect to get to HOME screen, not Profile. 
Is it s bug or expected behaviour?

**Comment by mikheyrojo** [comment]
uploaded a url

**Comment by satya164** [comment]
They aren't 2 stack navigators. They are the same stack navigator from React's point of view. We don't automatically navigate to new screens if the current screen still exists.
