### ISSUE TITLE
React Navigation doesn't work in release mode.

### ISSUE THREAD

**Issue by forbrightworld** [react-navigation/react-navigation#9598]
Hi, everyone!
Hope you are all doing well.
I don't know well here is right place for the problem I'm facing now in React Native app development but I hope you guys give me your hands kindly.

The problem is navigation works fine in debug mode but doesn't work in release mode.
I was going to reproduce issue to find out what is the problem, and I think @react-native-google-signin/google-signin, this module is problem.
When I uninstall this module, then it works fine but if I install this module then it doesn't work.

I'm going to show some contents.

package.json

{
  "name": "game_time",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@react-native-async-storage/async-storage": "^1.15.4",
    "@react-navigation/native": "^5.9.4",
    "@react-navigation/stack": "^5.14.5",
    "axios": "^0.21.1",
    "react": "17.0.1",
    "react-native": "0.64.1",
    "react-native-fbsdk-next": "^4.2.0",
    "react-native-gesture-handler": "^1.10.3",
    "react-native-responsive-dimensions": "^3.1.1",
    "react-native-safe-area-context": "^3.2.0",
    "react-native-screens": "^3.2.0",
    "react-native-splash-screen": "^3.2.0"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-jest": "^26.6.3",
    "eslint": "7.14.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.64.0",
    "react-test-renderer": "17.0.1"
  },
  "jest": {
    "preset": "react-native"
  }
}

App.js

import 'react-native-gesture-handler';
import React from 'react';
import { Image, Text, StyleSheet, View, ImageBackground } from 'react-native';
import AppNavContainer from './source/navigations';
import GlobalProvider, { GlobalContext } from './source/context/Provider';
import { GoogleSignin, statusCodes } from '@react-native-google-signin/google-signin';
import { Menu, MenuProvider } from 'react-native-popup-menu';

export default class App extends React.Component {

componentDidMount() {
  GoogleSignin.configure({
    scopes: ['https://www.googleapis.com/auth/drive.readonly'],
    webClientId: '307442699668-ok6hbo0s1k0k22cmtrap28sh934u86p6.apps.googleusercontent.com',
    offlineAccess: true,
    hostedDomain: '',
    loginHint: '',
    forceCodeForRefreshToken: true,
    accountName: '',
    iosClientId: '307442699668-jccaa666b52pr1715uhngitbeuc766jd.apps.googleusercontent.com'
  });
}

componentWillUnmount() {
console.log("Unmount");
}

  render() {
    return (
    <MenuProvider>
      <GlobalProvider>
        <AppNavContainer />
      </GlobalProvider>
    </MenuProvider>
    );
  }
}

const styles = StyleSheet.create({
  container : {
  flex : 1,
  },
  backgroundImage : {
  flex : 1,
  resizeMode : 'stretch',
  justifyContent : 'center',
  }
});

index.js (this is the file for navigation)

import React, {useEffect, useContext} from 'react';
import {NavigationContainer} from '@react-navigation/native';
import AuthNavigator from './AuthNavigator';
import AsyncStorage from '@react-native-async-storage/async-storage';
import SplashScreen from 'react-native-splash-screen';
import HomeNavigator from './HomeNavigator';
import { ActivityIndicator, Text, View } from 'react-native';
import {GlobalContext} from '../context/Provider';

const AppNavContainer = () => {
    const {
        authState : {isLoggedIn},
    } = useContext(GlobalContext);

    const [isAuthenticated, setIsAuthenticated] = React.useState(isLoggedIn);
    const [authLoaded, setAuthLoaded] = React.useState(false);

    const getUser = async () => {
        try {            
            const user = await AsyncStorage.getItem('user');
            if (user) {
                setAuthLoaded(true);
                setIsAuthenticated(true);
            } else {
                setAuthLoaded(true);
                setIsAuthenticated(false);
            }
        } catch (error) {
            console.log("navigations index.js", error);            
        }
    };
    useEffect(() => {
        getUser();
    }, [isLoggedIn]);
    React.useEffect(() => {
        SplashScreen.hide();
    }, []);

    return (

        // <AuthNavigator/>

        <>
            {authLoaded ? (
                <NavigationContainer>
                    {isAuthenticated ? <HomeNavigator/> : <AuthNavigator/> }
                </NavigationContainer>
            ) :(
                <ActivityIndicator />
            )}
        </>
    );
};

export default AppNavContainer;

AuthNavigator.js

import React from 'react';
import {createStackNavigator} from '@react-navigation/stack';
import {LOGIN, REGISTER, WELCOME, FORGOT_PASSWORD, CONFIRM, RESET_PASSWORD_PAGE} from '../constants/routeNames';
import Register from '../screens/Register';
import Test from '../screens/Test';
import { NavigationContainer } from '@react-navigation/native';
import Login from '../screens/Login';

const AuthNavigator = () => {
    const AuthStack = createStackNavigator();

    return (
            <AuthStack.Navigator screenOptions={{headerShown: false}} initialRouteName={LOGIN}>
                <AuthStack.Screen name="Test" component = {Test} />
                <AuthStack.Screen name={LOGIN} component = {Login} />
                <AuthStack.Screen name={REGISTER} component = {Register} />
            </AuthStack.Navigator>
    );
};

export default AuthNavigator;

HomeNavigator.js

import React from 'react';
import {createStackNavigator} from '@react-navigation/stack';
import Home from '../screens/Home';
import {HOME} from '../constants/routeNames';

const HomeNavigator = () => {
    const HomeStack = createStackNavigator();
    return (
        <HomeStack.Navigator screenOptions={{headerShown: false}} initialRouteName = {HOME}>
            <HomeStack.Screen name = {HOME} component={Home}/>
        </HomeStack.Navigator>
    );
};

export default HomeNavigator;

index.js screens/Login

import {useRoute} from '@react-navigation/native'
import React, {useState, useEffect, useContext} from 'react';
import { Alert } from 'react-native';
import LoginComponent from '../../components/Login';
import loginUser from '../../context/actions/auth/loginUser';
import { GlobalContext } from '../../context/Provider';

const Login = () => {
const [form, setForm] = useState({});
const [justSignedUp, setJustSignedUp] = useState(false);
const {params} = useRoute();
    React.useEffect(() => {
        if(params?.data) {
            setJustSignedUp(true);
            setForm({...form, userName : params.data.username})
        }
    }, [params]);

    const {
        authDispatch,
        authState: {error, loading},
    } = useContext(GlobalContext);

    const onSubmit = () => {
        if (form.userName && form.password) {
            loginUser(form)(authDispatch);
        }
    };

    // const googleSignIn = () => {
    // console.log("google signin at index.js Login screen");
    // googleSignInUser()(authDispatch);
    // }

    const onChange = ({name, value}) => {
        setJustSignedUp(false);
        setForm({...form, [name]: value});
    };

    return (
        <LoginComponent
            onSubmit={onSubmit}
            onChange={onChange}
            form={form}
            error={error}
            loading={loading}
            justSignedUp={justSignedUp}
        />
    );
};

export default Login;

index.js screens/Register

import {useFocusEffect, useNavigation, useRoute} from '@react-navigation/native'
import React, {useState, useEffect, useContext} from 'react';
import { Alert } from 'react-native';
import RegisterComponent from '../../components/Register';
import {CONFIRM} from '../../constants/routeNames';
import { GlobalContext } from '../../context/Provider';
import register, {clearAuthState} from '../../context/actions/auth/register';
// import googleSignInUser from '../../context/actions/auth/googleSignInUser';

const Register = () => {
    const [form, setForm] = useState({});
    const {navigate} = useNavigation();
    const [errors, setErrors] = useState({});
    const [justSignedUp, setJustSignedUp] = useState(false);
    const {
    authDispatch,
        authState : {error, loading, data},
    } = useContext(GlobalContext);

    useFocusEffect(
        React.useCallback(() => {
        return () => {
            if(data || error) {
            clearAuthState()(authDispatch);
            }
            };
        }, [data, error]),
    );

    const onChange = ({name, value}) => {
        setForm({...form, [name]: value});

        if(value !== '') {
            if(name === 'password') {
                if(value.length < 6) {
                    setErrors((prev) => {
                        return {...prev, [name]: 'Password should be 6 letters at minimum'};
                    });
                } else {
                    setErrors((prev) => {
                        return {...prev, [name]: null};
                    });
                }
            } else {
                setErrors((prev) => {
                    return {...prev, [name]: null};
                });
            }
        } else {
            setErrors((prev) => {
                return {...prev, [name]: 'This field is required'};
            });
        }
    };

    const onSubmit = () => {
        if (!form.username) {
            setErrors((prev) => {
                return {...prev, username: 'Please add a username'};
            });
        }
        if (!form.first_name) {
            setErrors((prev) => {
                return {...prev, first_name: 'Please add a first name'};
            });
        }
        if (!form.last_name) {
            setErrors((prev) => {
                return {...prev, last_name: 'Please add a last name'};
            });
        }
        if (!form.email) {
            setErrors((prev) => {
                return {...prev, email: 'Please add a email'};
            });
        }
        if (!form.password) {
            setErrors((prev) => {
                return {...prev, password: 'Please add a password'};
            });
        }

        if(
        Object.values(form).length === 6 &&
        Object.values(form).every((item) => item.trim().length>0) &&
        Object.values(errors).every((item) => !item)
        ) {
            register(form)(authDispatch)((response) => {
                navigate(CONFIRM, {data : response});
            });
        }
    };

    // const googleSignIn = () => {
    // console.log("google signin at index.js screen");
    // googleSignInUser()(authDispatch);
    // }

    return (
        <RegisterComponent
            // googleSignIn = {googleSignIn}
            onSubmit={onSubmit}
            onChange={onChange}
            form={form}
            error={error}
            errors = {errors}
            loading={loading}
        />
    );
};

export default Register;

Thank you for considering long and boring post.

**Comment by forbrightworld** [comment]
Hi, I made the reproduction for that issue I have as simple as possible, here is the git repo link https://github.com/forbrightworld/RNissueRepro. 

It works well in debug mode but when I made release apk by "npx react-native run-android --variant=release" then AuthStack works but HomeStack doesn't work just blank screen.
Thank you

**Comment by ulrellik** [comment]
Interesting, I've a very similar problem since upgrading to React Native 0.64. On debug everything works fine, but once I build it for release I get a blank screen. I'm not even using react-navigation v5, but I'm still on v4. As reference here are my dependencies:

`"dependencies": {
        "@react-native-async-storage/async-storage": "^1.15.4",
        "@react-native-community/audio-toolkit": "^2.0.3",
        "@react-native-community/masked-view": "^0.1.11",
        "@react-native-community/netinfo": "^5.9.10",
        "@react-native-community/progress-bar-android": "^1.0.4",
        "@react-native-community/progress-view": "^1.3.1",
        "@react-native-firebase/app": "^11.5.0",
        "@react-native-firebase/crashlytics": "^11.5.0",
        "@react-native-firebase/messaging": "^11.5.0",
        "@reduxjs/toolkit": "^1.5.1",
        "dayjs": "^1.10.4",
        "eventemitter3": "^4.0.7",
        "i18next": "^20.2.4",
        "lodash": "^4.17.21",
        "native-base": "^2.15.2",
        "prop-types": "^15.6.1",
        "re-reselect": "^4.0.0",
        "react": "17.0.1",
        "react-i18next": "^11.8.15",
        "react-native": "0.64.1",
        "react-native-calendars": "^1.1260.0",
        "react-native-device-info": "^8.1.3",
        "react-native-gesture-handler": "^1.6.1",
        "react-native-gifted-chat": "0.16.3",
        "react-native-image-crop-picker": "^0.36.2",
        "react-native-image-pan-zoom": "^2.1.12",
        "react-native-pdf": "^6.3.0",
        "react-native-progress-circle": "^2.1.0",
        "react-native-reanimated": "^1.13.3",
        "react-native-safe-area-context": "^3.2.0",
        "react-native-screens": "^2.18.1",
        "react-native-video": "^5.1.1",
        "react-navigation": "^4.4.4",
        "react-navigation-drawer": "^2.7.1",
        "react-navigation-stack": "^2.10.4",
        "react-redux": "^7.2.4",
        "redux-persist": "^6.0.0",
        "reselect": "^4.0.0",
        "rn-fetch-blob": "^0.12.0",
        "simpleddp": "^2.2.4",
        "simpleddp-plugin-login": "^4.0.2"
    },
    "devDependencies": {
        "@babel/core": "^7.14.3",
        "@babel/runtime": "^7.12.5",
        "babel-eslint": "^10.1.0",
        "babel-jest": "^26.6.3",
        "babel-plugin-module-resolver": "^4.1.0",
        "enzyme": "^3.10.0",
        "enzyme-adapter-react-16": "^1.15.6",
        "enzyme-to-json": "^3.6.2",
        "eslint": "^7.26.0",
        "eslint-config-airbnb": "^18.2.1",
        "eslint-import-resolver-babel-module": "^5.3.1",
        "eslint-plugin-import": "^2.23.2",
        "eslint-plugin-jest": "^24.3.6",
        "eslint-plugin-jsx-a11y": "^6.4.1",
        "eslint-plugin-react": "^7.23.2",
        "eslint-plugin-react-hooks": "^4.2.0",
        "jest": "^26.6.3",
        "metro-react-native-babel-preset": "^0.64.0",
        "patch-package": "^6.4.7",
        "postinstall-postinstall": "^2.1.0",
        "react-dom": "17.0.1",
        "react-test-renderer": "17.0.1",
        "redux-mock-store": "^1.5.3"
    },`

**Comment by forbrightworld** [comment]
Thank you your reply, ulrellik.
I'm not sure what the problem is, after I post this, then I was going to figure out the problem.
So, I made the clean project again and add minimal features to run the project
here is the dependencies

{
  "name": "gameroom",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@react-native-async-storage/async-storage": "^1.15.4",
    "@react-navigation/native": "^5.9.4",
    "@react-navigation/stack": "^5.14.5",
    "react": "17.0.1",
    "react-native": "0.64.1",
    "react-native-gesture-handler": "^1.10.3",
    "react-native-responsive-dimensions": "^3.1.1",
    "react-native-safe-area-context": "^3.2.0",
    "react-native-screens": "^3.2.0"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-jest": "^26.6.3",
    "eslint": "7.14.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.64.0",
    "react-test-renderer": "17.0.1"
  },
  "jest": {
    "preset": "react-native"
  }
}

As you can see the dependencies of the very first post, I used axios, so I remove almost dependencies but it doesn't work.
Interesting part of my problem is the first stack navigation works fine but the second one doesn't work.
I replaced this stack navigator with <View><Text>Home navigator</Text></View>, then the "Home navigator" is displayed.
        <HomeStack.Navigator screenOptions={{headerShown: false}} initialRouteName = {HOME}>
            <HomeStack.Screen name = {HOME} component={Home}/>
        </HomeStack.Navigator>

Thank you
