### ISSUE TITLE
Header Back Icon Not Showing on Web with Monorepo

### ISSUE THREAD

**Issue by ktprograms** [react-navigation/react-navigation#9599]
**Current Behavior**

I generated a React Native + Web Monorepo project based on [this](https://github.com/brunolemos/react-native-web-monorepo) template. Then I ran `yarn workspace components add @react-navigation/native @react-navigation/stack react-native-reanimated react-native-gesture-handler react-native-screens react-native-safe-area-context @react-native-community/masked-view` as well as `yarn workspace mobile add @react-navigation/native @react-navigation/stack react-native-reanimated react-native-gesture-handler react-native-screens react-native-safe-area-context @react-native-community/masked-view` (as suggested in the [tutorial](https://dev.to/brunolemos/tutorial-100-code-sharing-between-ios-android--web-using-react-native-web-andmonorepo-4pej) associated with the template. On iOS, the Back button in the header works as expected, but on Web, the button is invisible but functional.
Link to my code: [https://github.com/ktprograms/rnw-monorepo/](https://github.com/ktprograms/rnw-monorepo/).
Screenshot (Android emulator, working):
![Screenshot 2021-05-18 at 10 13 46 AM](https://user-images.githubusercontent.com/71804605/118580062-c82e9800-b7c1-11eb-92d6-3acdcacefa14.png)
Screenshot (Web, not working)
<img width="686" alt="Screenshot 2021-05-18 at 10 16 57 AM" src="https://user-images.githubusercontent.com/71804605/118580288-3a9f7800-b7c2-11eb-823f-a63fff23896f.png">

**Expected Behavior**

Back button icon should be shown on Web.

**How to reproduce**

```
git clone https://github.com/ktprograms/rnw-monorepo.git
cd rnw-monorepo
yarn
cd packages/mobile/ios && pod update && pod install && cd -
yarn start
```
Then click the 'Go To Details' Button.

Source code is in packages/components/src/App.tsx

**Your Environment**

I'm using MacOS 11.2.3 on a MacBook Air (M1, 2020). The above steps to reproduce were run in a Terminal.app window with Rosetta enabled.

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Android S Emulator
| @react-navigation/native       | ^5.9.4
| @react-navigation/stack        | ^5.14.5
| react-native-gesture-handler   | ^1.10.3
| react-native-safe-area-context | ^3.2.0
| react-native-screens           | ^3.2.0
| react-native                   | 0.63.3
| expo                           | not using
| node                           | v16.0.0
| npm or yarn                    | yarn 1.22.10

**Comment by satya164** [comment]
It's a bug in Metro, not in React Navigation. You can find the same issue in the issue tracker and workarounds if you search for it. You can also look at the metro config example app in this repo which is a monorepo.
