### ISSUE TITLE
useIsDrawerOpen hook is missing in React Navigation Version 6x.next

### ISSUE THREAD

**Issue by MuttakinHasib** [react-navigation/react-navigation#9600]
**Current Behavior**

- useIsDrawerOpen is not working

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |  android 10
| @react-navigation/native       |  6.0.0-next.7
| @react-navigation/drawer       |  6.0.0-next.9
| react-native-reanimated        |  2.1.0
| react-native-gesture-handler   |  1.10.2
| react-native-safe-area-context |  3.2.0
| react-native-screens           |  ~3.0.0
| react-native                   |  https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz
| expo                           |  41.0.1
| node                           |  14.16.1
| npm or yarn                    | npm 7.12.0, yarn 1.22.10

**Comment by MuttakinHasib** [comment]
latest version is ok, but problem with v6x.next

**Comment by satya164** [comment]
https://reactnavigation.org/docs/6.x/upgrading-from-5.x#drawer-status-is-now-a-string-instead-of-a-boolean
