### ISSUE TITLE
react native expo undefined is note un object (evaluating navigation.state.params)

### ISSUE THREAD

**Issue by elhoucinOlmstaf** [react-navigation/react-navigation#9608]
I have passed data from screen to other screen but when I am trying to access it . it keeps saying undefined is not an object (evaluating navigation.state.params). I am using N5 . I tried also route.params and it gave me undefined is not an object (evaluating route.params)
```
**_this is my AllNotes Screen_**
```
import React, { useState, useEffect } from "react";
import { View, Text } from "react-native";
import {
  TextInput,
  StyleSheet,
  Dimensions,
  ScrollView,
  FlatList,
} from "react-native";
import useFocusEffect from "@react-navigation/native";
import { EvilIcons, MaterialIcons } from "@expo/vector-icons";
import AsyncStorage from "@react-native-community/async-storage";

const windowWidth = Dimensions.get("window").width;
const windowHeight = Dimensions.get("screen").height;

const AllNotes = ({ navigation }) => {
  const [Note, setNote] = useState([]);
  // addnotes
  const addNotes = (note) => {
    note.id == note.length + 1;
    setNote([...Note, note]);
  };
  return (
    <View style={styles.container}>
      <View style={styles.searchInput}>
        <MaterialIcons
          name="search"
          size={22}
          style={styles.searchIcon}
          color="#bbb"
        />
        <TextInput
          style={styles.inputText}
          placeholder={"I'm looking for..."}
          placeholderTextColor={"#999"}
          underlineColorAndroid={"#fff"}
          autoCorrect={false}
        />
      </View>
      <ScrollView>
        <View style={styles.notesContainer}>
          <FlatList data={Note}
            renderItem = {({item})=>(
              <Text>{item.notes}</Text>
            )}
          />
        </View>
      </ScrollView>
      <View style={styles.plusContainer}>
        <EvilIcons
          onPress={() => navigation.navigate("Edite Notes", {notes: addNotes})}
          name="plus"
          size={74}
          color="black"
        />
      </View>
    </View>
  );
};
```
my EditeScreen
import AsyncStorage from "@react-native-community/async-storage";
import React, { useState } from "react";
import { TouchableNativeFeedback } from "react-native";

import {
  TextInput,
  StyleSheet,
  Dimensions,
  Text,
  View,
  ScrollView,
} from "react-native";
const EditeScreen = ({ navigation , route}) => {
  // mange textinput height
  const [height, setHeight] = useState(42);
  // manges textInput starts
  const [notes, setNotes] = useState("");
  // onSvaeNote
  function onSaveNote(){
    // navigation.state.params.addNotes({notes})
    // navigation.route.params.addNotes({notes})
    console.log(navigation.route.params?.notes)
    navigation.goBack();
  }
 
  return (
    <View style={styles.InputContainer}>
      <ScrollView>
        <TextInput
          style={{
            height: height,
            padding: 11,
            fontSize: 20,
          }}
          placeholder={"Start Note Taking ..."}
          onChangeText={setNotes}
          value={notes}
          multiline={true}
          autoFocus={true}
          onContentSizeChange={(e) =>
            setHeight(e.nativeEvent.contentSize.height)
          }
        />
      </ScrollView>
      <TouchableNativeFeedback onPress={() => onSaveNote()}>
        <Text style={styles.addbtn}>Add</Text>
      </TouchableNativeFeedback>
    </View>
  );
};

**Comment by Thomasbayy** [comment]
In react-navigation v5 params are stored in route.params.
Could it be possible that you have forgotten to destructure route from props before trying to access route.params?

**Comment by elhoucinOlmstaf** [comment]
this only happens when I use drawer. it just work fine with stacks only

**Comment by elhoucinOlmstaf** [comment]
I used Context instead
