### ISSUE TITLE
Previous route changes position when overlaying new route

### ISSUE THREAD

**Issue by leecop123** [react-navigation/react-navigation#9613]
**Current Behavior**

I'm playing with `react-native` stack navigators, overlaying views with transition animations and I've noticed an issue which I can't seem to get to grips with. Unsure if it's a bug or if I'm doing/not doing something. Probably the latter. 

Basically, the problem is around a view changing position when rendering a new a view (via `.navigate()`). 

I've made a minimal example which can be run on an IOS device via the expo app. From the Home Screen you can click a button which will render the action sheet, with a nice transition preset. This is all good. From the action sheet, you can render a "modal". When the modal renders, you can see the previous view has pushed up the page, as if some margin bottom has been applied. I suspect this has something to do with the device insets, but it's unclear how I can stop this behaviour. 

https://snack.expo.io/Jgac-odfZ 

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | 14.5
| @react-navigation/native       | 5.9.4
| @react-navigation/stack        | 5.14.3
| react-native-gesture-handler   | 1.10.3
| react-native-safe-area-context | 0.7.3
| react-native-screens           |  2.9.0
| react-native                   | 0.63.3
| expo                           | not using 
| node                           |  12.16.1
| npm or yarn                    | npm

**Comment by leecop123** [comment]
Still exists.

**Comment by satya164** [comment]
https://reactnavigation.org/docs/stack-navigator/#transparent-modals

**Comment by leecop123** [comment]
This doesn't fix the inset issue?

**Comment by samjtozer** [comment]
Would like to reopen this issue if I can please.

**Comment by leecop123** [comment]
Would like to reopen this issue if I can.

**Comment by satya164** [comment]
> This doesn't fix the inset issue?

You need to create a separate modal stack for your transparent modals as mentioned in the docs.

**Comment by leecop123** [comment]
Thanks for getting back to me. I tried this earlier, please see the updated snack: https://snack.expo.io/tgXA0CTli 

The problem is still present. Any ideas? Am I doing something wrong at this point. 

Thanks.

**Comment by leecop123** [comment]
And an additional attempt: https://snack.expo.io/2E-p0FlFD

**Comment by satya164** [comment]
> Note: The ModalPresentationIOS preset needs to be configured for the whole stack for it to work correctly. If you want few screens to have this transition, you can add a modal stack at root with this transition, and nest a regular stack inside it.

**Comment by leecop123** [comment]
Are you able to adjust my Snack with an example? Sorry I'm quite new to the navigation side and finding it hard to configure the whole stack.

**Comment by satya164** [comment]
You can ask for help from other community members in the channels mentioned by the bot ^

**Comment by leecop123** [comment]
Ah cool - I did already ask it yesterday. I didn't want to post the link in here as I didn't know whether the community would rather they be disjoint. Anyway, here is the link to the question: https://stackoverflow.com/questions/67662186/react-native-previous-route-changes-position-when-overlaying-new-route 

I'll also join the channel. Thanks.
