### ISSUE TITLE
Not scrollable on web (w/o ScrollView)

### ISSUE THREAD

**Issue by goldylucks** [react-navigation/react-navigation#9618]
**Current Behavior**
When content inside a screen has height > window, it's not scrollable (I'm NOT using ScrollView)
https://www.loom.com/share/5ce947bad2024da5ae9dd92a3695dd68

**Expected Behavior**
Should be scrollable

**How to reproduce**

- go to https://snack.expo.io/sh4vSfVQA
- try to scroll in web
- zoom on/out browser to see more/less content (further confirming it's actually there)

**Your Environment**
Latest snack, tho it happens for all of our customers in different envs

**Comment by satya164** [comment]
I don't see why you'd expect your content to be scrollable if you don't use a `ScrollView`.

It'd work without a `ScrollView` if you use `headerShown: false` instead of `headerMode="none"`, but that's still going to break on other platforms.  So you should use a `ScrollView` if you want your content to be scrollable.

**Comment by goldylucks** [comment]
@satya164 I read on another thread that RNW and react navigation v5 make content scrollable w/o ScrollView. Also, if you open the expo snack and wrap the root view with ScrollView, you won't see anything on the screen. 

And I can't give it height because it's dynamic for each page.

**Comment by goldylucks** [comment]
any updates on this?

**Comment by goldylucks** [comment]
@satya164 so what's the solution here?
as you can see, if I add `ScrollView` around my screens, nothing is shown:
https://snack.expo.io/3d0tFSLHW

and I want the scroll to be on the entire container, including the header, and want it to be cross app. Shouldn't this be out of the box? that was my understanding.
