### ISSUE TITLE
v6: useLinkBuilder is not a function

### ISSUE THREAD

**Issue by lb90** [react-navigation/react-navigation#9619]
**Current Behavior**

Attempting to use MaterialBottomNavigation gives an error:

![screen](https://user-images.githubusercontent.com/12200013/119488295-a9e51100-bd5a-11eb-892e-c78f6ddb6dbd.jpg)

OTOH if I use MaterialTopNavigation then everything is OK. All packages are up-to-date, here's an excerpt of my `package.json`:

```json
"dependencies": {
  "@react-native-masked-view/masked-view": "^0.2.4",
  "@react-navigation/bottom-tabs": "^6.0.0-next.13",
  "@react-navigation/material-bottom-tabs": "^6.0.0-next.9",
  "@react-navigation/material-top-tabs": "^6.0.0-next.10",
  "@react-navigation/native": "^6.0.0-next.9",
  "@react-navigation/stack": "^6.0.0-next.20",
  "react": "17.0.1",
  "react-native": "0.64.0",
  "react-native-gesture-handler": "^1.10.3",
  "react-native-pager-view": "^5.1.9",
  "react-native-paper": "^4.8.1",
  "react-native-reanimated": "^2.1.0",
  "react-native-safe-area-context": "^3.2.0",
  "react-native-screens": "^3.2.0",
  "react-native-tab-view": "^3.0.1",
  "react-native-webview": "11.4.3",
}
```

**How to reproduce**

1. `npx init test-issue-9619 && cd test-issue-9619`
2. `npm install @react-navigation/native@next @react-navigation/material-bottom-tabs@next react-native-paper react-native-reanimated react-native-gesture-handler react-native-screens react-native-safe-area-context`
3. Replace `App.js` content with:

```js
import 'react-native-gesture-handler';
import React from 'react';
import { View } from 'react-native';
import { NavigationContainer } from '@react-navigation/native';
import { createMaterialBottomTabNavigator } from '@react-navigation/material-bottom-tabs';

const Tab = createMaterialBottomTabNavigator();

function HomeScreen() {
  return null;
}

function SettingsScreen() {
  return null;
}

function App() {
  return (
    <NavigationContainer>
      <Tab.Navigator>
       <Tab.Screen name="Home" component={HomeScreen} />
       <Tab.Screen name="Settings" component={SettingsScreen} />
     </Tab.Navigator>
   </NavigationContainer>
  );
}

export default App;
```

Sample repo: https://github.com/lb90/RNTestIssue9619

**Your Environment**

| software                               | version |
| -------------------------------------- | ------- |
| iOS or Android                         | Android
| @react-navigation/native               | 6.0.0-next.9
| @react-navigation/material-bottom-tabs | 6.0.0-next.10
| react-native-paper                     | 4.8.1
| react-native                           | 0.64.0
| expo                                   | No
| node                                   | v12.17.0
| npm or yarn                            | yarn

**Comment by lb90** [comment]
As a workaround I could use MaterialTopTabNavigator, but looks like support for `tabBarPosition` was [removed](https://github.com/react-navigation/react-navigation/commit/7e10bcd089054e95e8f0f64112f99e5b342511ea). Is there a way to put MaterialTopBar on bottom?

Thanks! :)

**Comment by satya164** [comment]
Looks like the error somehow happens if `react-native-vector-icons` is not installed. So you need to install it and clear cache https://reactnavigation.org/docs/troubleshooting/#stale-cache-of-metro-bundler

Closing since this looks more like a bug in Metro which should be addressed there.
