### ISSUE TITLE
"TabBarOptions" cannot change the background color after customizing the "tabBar"

### ISSUE THREAD

**Issue by showtan001** [react-navigation/react-navigation#9626]
**Current Behavior**

After customizing tabBar, tabBarOptions cannot change the background color.
![Simulator Screen Shot - iPhone 11 - 2021-05-27 at 17 39 25](https://user-images.githubusercontent.com/32892347/119803944-7d73f500-bf12-11eb-84ab-088149ddb31c.png)

**Expo Go**

![WechatIMG59](https://user-images.githubusercontent.com/32892347/119810169-5e786180-bf18-11eb-98db-467d3027eba4.png)

**Expected Behavior**

After customizing the tabBar, tabBarOptions can set the background color to "transparent".

![Simulator Screen Shot - iPhone 11 - 2021-05-27 at 17 27 12 2](https://user-images.githubusercontent.com/32892347/119804263-c5931780-bf12-11eb-8699-621c248db461.png)

![WechatIMG59](https://user-images.githubusercontent.com/32892347/119811285-81efdc00-bf19-11eb-9703-1c1d8ba664c7.png)

**How to reproduce**
```
<div data-snack-id="@showtan/insane-beef-jerky" data-snack-platform="web" data-snack-preview="true" data-snack-theme="light" style="overflow:hidden;background:#F9F9F9;border:1px solid var(--color-border);border-radius:4px;height:505px;width:100%"></div>
<script async src="https://snack.expo.io/embed.js"></script>
```

**Your Environment**

| software                      | version |
| ----------------------------- | ------- |
| iOS or Android                | iOS and Android Any version
| @react-navigation/native      | ^5.9.4
| @react-navigation/bottom-tabs | ^5.11.11
| react-native-screens          | ^2.9.0
| react-native                  | ^0.63.2
| expo                          | https://snack.expo.io/@showtan/insane-beef-jerky
| node                          | v12.12.0
| npm or yarn                   | npm

**Comment by satya164** [comment]
You need to add `position: 'absolute'` to your tab bar if you want the content to be seen through underneath.

**Comment by showtan001** [comment]
> You need to add `position: 'absolute'` to your tab bar if you want the content to be seen through underneath.

Didn't you watch my expo? I have added position:'absolute' and backgroundColor:'transparent' to the style of tabBarOptions, but it is of no use! Can you help me find out what is wrong with my expo?

**Comment by satya164** [comment]
> Hi! Didn't you watch my expo? I have added position:'absolute' and backgroundColor:'transparent' to the style of tabBarOptions, but it is of no use! Can you help me find out what is wrong with my expo?

You have a custom tab bar. You need to accept `style` prop in your component and add it to your `View`, or directly specify it in your View.

**Comment by showtan001** [comment]
> > Hi! Didn't you watch my expo? I have added position:'absolute' and backgroundColor:'transparent' to the style of tabBarOptions, but it is of no use! Can you help me find out what is wrong with my expo?
> 
> You have a custom tab bar. You need to accept `style` prop in your component and add it to your `View`, or directly specify it in your `View`.

Thanks man!

**Comment by showtan001** [comment]
> > Hi! Didn't you watch my expo? I have added position:'absolute' and backgroundColor:'transparent' to the style of tabBarOptions, but it is of no use! Can you help me find out what is wrong with my expo?
> 
> You have a custom tab bar. You need to accept `style` prop in your component and add it to your `View`, or directly specify it in your `View`.

Thanks man!
