### ISSUE TITLE
TypeError: property is not configurable (in NavigationContainerInner)

### ISSUE THREAD

**Issue by beetlebum** [react-navigation/react-navigation#9627]
After upgrading from `6.0.0-next.9` to `6.0.0-next.10`, the application crashes with the following error:

![simulator_screenshot_5EA67F90-9412-4BC3-B20C-1BD999636111](https://user-images.githubusercontent.com/227258/119804719-847e1180-bed8-11eb-8727-323b561de2c0.png)

``` ERROR  TypeError: property is not configurable

This error is located at:
    in NavigationContainerInner (at Navigation.tsx:251)
    in RCTView (at View.js:34)
    in View
    in Unknown (at Navigation.tsx:250)
    in RCTView (at View.js:34)
    in View (at touchevents.js:74)
    in __Sentry.TouchEventBoundary (at EventBoundary.tsx:36)
    in ErrorBoundary (at EventBoundary.tsx:35)
    in EventBoundary (at Navigation.tsx:249)
    in Navigation (at App.tsx:14)
    in Splash (at Bootstrap.tsx:86)```

Using `react-native-screens` and `createNativeStackNavigator`

```const navigationRef = React.useRef<NavigationContainerRef>(null);
  const { onStateChange, onReady } = useOnStateChange(navigationRef);
  useNavigationListeners();
  return (
    <EventBoundary>
      <Host>
        <NavigationContainer
          ref={navigationRef}
          {...{ onStateChange, onReady }}
        >```

**Comment by aleppos** [comment]
@react-navigation/native: ^6.0.0-next.10

**Comment by beetlebum** [comment]
"@react-navigation/bottom-tabs@^6.0.0-next.13"
"@react-navigation/core@^6.0.0-next.10"
"@react-navigation/drawer@6.0.0-next.2"
"@react-navigation/elements@^1.0.0-next.13",
"@react-navigation/elements@^1.0.0-next.2"
"@react-navigation/native@^6.0.0-next.3"
"@react-navigation/routers@^6.0.0-next.3"
"@react-navigation/stack@^6.0.0-next.20"
"react-native-screens@^3.2.0"

**Comment by satya164** [comment]
Can you provide a repro in a GitHub repo?

**Comment by aleppos** [comment]
`
import React from 'react'
import { Text } from 'react-native'
import {
  NavigationContainer,
  useNavigationContainerRef,
} from '@react-navigation/native'

export default function Main() {
  const navigationRef = useNavigationContainerRef()

  return (
      <NavigationContainer ref={navigationRef} theme={navigationTheme}>
        <Text>test</Text>
      </NavigationContainer>
  )
}
`

**Comment by satya164** [comment]
@aleppos we have the same code in the example app, so there's not much I can debug here. it'd be helpful if you can provide a repro where it happens so I can check

**Comment by husseinAbdulnabi** [comment]
having the same issue when upgrading from 6.0.0-next.9 to next.10 or next.11, same code didn't change anything in my codebase

**Comment by husseinAbdulnabi** [comment]
I guess this was fixed by in this commit, https://github.com/react-navigation/react-navigation/commit/324ea7181db6b743f512854be267cc9d65975b6f, not having the issue anymore on: 
```
    "@react-navigation/elements": "1.0.0-next.16",
    "@react-navigation/native": "6.0.0-next.13",
    "@react-navigation/stack": "6.0.0-next.24",
```

**Comment by Rahulv2492** [comment]
@husseinAbdulnabi useNavigationContainerRef function in exported in react-navigation.

**Comment by nvdnvd00** [comment]
Can we re-open this issue, I'm getting it on ios too
```"@react-navigation/material-top-tabs": "^6.6.2",
		"@react-navigation/native": "6.1.6",
		"@react-navigation/stack": "6.2.0",```

**Comment by beetlebum** [comment]
> Can we re-open this issue, I'm getting it on ios too
> 
> ```
> "@react-navigation/material-top-tabs": "^6.6.2",
> "@react-navigation/native": "6.1.6",
> "@react-navigation/stack": "6.2.0",
> ```

are you using reanimated 3?

**Comment by malikzype** [comment]
Getting Same error again using reanimated 3.0.2 and 
    "@react-navigation/bottom-tabs": "6.5.7",
    "@react-navigation/core": "6.4.8",
    "@react-navigation/native": "6.1.6",
    "@react-navigation/stack": "6.3.16",

**Comment by invyctus92** [comment]
Same problem with  reanimated 3.0.2 but removing options from page settings with react navigation works

`<Stack.Screen
              name="DetailTeamScreenFromGlobal"
              component={DetailTeamScreen}
              // delete this options
              options={({ navigation, route }) => ({
                headerTitle: () => (
                  <Text
                    style={{
                      fontFamily: 'Nunito-Regular',
                    }}>
                    {route.params?.pageTitle ?? strings('id_4_15')}
                  </Text>
                ),
              })}
            />`

**Comment by beetlebum** [comment]
> > > Can we re-open this issue, I'm getting it on ios too
> > > ```
> > > "@react-navigation/material-top-tabs": "^6.6.2",
> > > "@react-navigation/native": "6.1.6",
> > > "@react-navigation/stack": "6.2.0",
> > > ```
> > 
> > 
> > are you using reanimated 3?
> 
> I can answer yes. I used reanimated 3 to custom tabbar. When I changed to default tabbar, the issue was disappear

Can you open a new issue on Github with your findings? thanks (I'm not associated with Software Mansion, I simply reported this issue last year)

**Comment by minemos** [comment]
Same here

```json
"dependencies": {
    "@react-native-community/blur": "^4.3.0",
    "@react-native-community/netinfo": "^9.3.7",
    "@react-navigation/bottom-tabs": "^6.5.7",
    "@react-navigation/native": "^6.1.6",
    "@react-navigation/native-stack": "^6.9.12",
    "@types/react-native-vector-icons": "^6.4.13",
    "patch-package": "^6.5.1",
    "postinstall-postinstall": "^2.1.0",
    "react": "18.2.0",
    "react-native": "0.71.4",
    "react-native-gesture-handler": "^2.9.0",
    "react-native-reanimated": "^3.0.2",
    "react-native-safe-area-context": "^4.5.0",
    "react-native-screens": "^3.20.0",
    "react-native-ui-lib": "^7.2.1",
    "react-native-vector-icons": "^9.2.0",
    "react-native-video": "^5.2.1"
  },
```

**Comment by jasontlouro** [comment]
+1

**Comment by EHRdev** [comment]
I had the same problem and it worked for me to downgrade version of `react-native-reanimated` to: `^2.9.1` in package.json.

After `npm i` then `npx react-native start --reset-cache` and then `npx react-native run-android`

**Comment by zhenguet** [comment]
+1

```
    "@react-navigation/bottom-tabs": "^6.5.7",
    "@react-navigation/drawer": "^6.6.2",
    "@react-navigation/native": "^6.1.6",
    "@react-navigation/stack": "^6.3.16",
    "react": "18.2.0",
    "react-native": "0.71.4",
```

**Comment by idlework** [comment]
Reverting to the latest 2.x.x solved this issue for me.

**Comment by mikebouwmans** [comment]
Could it be an issue with reanimated? Looks like they fixed something in https://github.com/software-mansion/react-native-reanimated/pull/4252
