### ISSUE TITLE
StackNavigator inside BottomTabNavigator is re-rendered when navigating between screens

### ISSUE THREAD

**Issue by vi07** [react-navigation/react-navigation#9629]
**Current Behavior**

I have a `Tab Navigator`. The `Tabs` contain `Stack Navigators`.

The structure of the code is:

```
    Tab = createBottomTabNavigator();
    HomeStack = createStackNavigator();
    SettingStack = createStackNavigator();
    
    function HomeScreen(){
      return //some JSX
    };
    
    function ProfileScreen(){
      return //some JSX
    };
    
    function SettingScreen(){
      return //some JSX
    };
    
    function MyStack(){
    
      //
      *********************** THIS_SEGMENT ****************************
      //
    
      return(
       <HomeStack.Navigator>
         <HomeStack.Screen component={HomeScreen} />
         <HomeStack.Screen component={ProfileScreen} />
       </HomeStack.Navigator>
      )
    }
    
    function SettingStackScreen(){
      return(
       <SettingStack.Navigator>
         <SettingStack.Screen component={SettingScreen} />
       </SettingStack.Navigator>
      )
    }
    
    export default function App() {
      return (
        <NavigationContainer>
          <Tab.Navigator>
            <Tab.Screen component={MyStack} />
            <Tab.Screen component={SettingStackScreen} />
          </Tab.Navigator>
        </NavigationContainer>
      );
    }
```

The problem is whenever I navigate between `HomeScreen` and `ProfileScreen`,  `THIS_SEGMENT` is executed.

**Expected Behavior**

I don't want to execute the `THIS_SEGMENT` part when switching between the two screens.

**How to reproduce**

This is the link to snack showing my problem: https://snack.expo.io/@vipulchandra04/nested-stacknavigator
. In `line-41` message is logged when switching between `HomeScreen` and `ProfileScreen`.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | 14.5
| @react-navigation/native       | 5.9.4
| @react-navigation/stack        | 5.14.5
| react-native                   | 0.64

**Comment by satya164** [comment]
That's not a bug. That's how React works, when navigation state in the `NavigationContainer` updates, all its children who need to update will re-render.

You need to put your side-effects in `useEffect` and provide a dependency array to optimize when it's executed.

**Comment by showtan001** [comment]
> That's not a bug. That's how React works, when navigation state in the `NavigationContainer` updates, all its children who need to update will re-render.
> 
> You need to put your side-effects in `useEffect` and provide a dependency array to optimize when it's executed.

Thanks man!
