### ISSUE TITLE
Android header is bigger than usual.

### ISSUE THREAD

**Issue by swizes** [react-navigation/react-navigation#9630]
**Current Behavior**

- What code are you running and what is happening?
I am using a single stack navigator with single screen and header on android is too big. On iOS it works as expected

- Include a screenshot or video if it makes sense.
![image](https://user-images.githubusercontent.com/8876645/120060756-3dbc2300-c062-11eb-9df4-e2082e97db15.png)

**Expected Behavior**

- What do you expect should be happening?
The header should look a bit smaller like in normal sizes...
- Include a screenshot or video if it makes sense.

**How to reproduce**

https://snack.expo.io/KfMMSYa-R

**My stack navigation**
```
import { createStackNavigator } from "@react-navigation/stack";
import { ProfileScreen } from "../../screens/ProfileScreen";
import { SharedScreens } from "./SharedScreens";
import React from "react";

const Stack = createStackNavigator();

export const ProfileStack = props => {
  const common = SharedScreens(Stack);

  return (
    <Stack.Navigator
      initialRouteName={'ProfileScreen'}
      screenOptions={{
        headerTitle: '',
        headerBackTitleVisible: false,
        headerTitleAlign:'center',
      }}>
      <Stack.Screen
        name="ProfileScreen"
        options={{
          headerTitle: 'Profil Screen',
          headerTopInsetEnabled: false,
        }}
        component={ProfileScreen}
      />
      {common}
    </Stack.Navigator>
  );
};
```
**App.js**

```
const App = () => {
  return (
    <>
      <NavigationContainer>
        <RootNavigation />
      </NavigationContainer>
    </>
  );
};
```

It does not matter if I put the **SafeAreaProvider** above NavigationContainer in App.js
It does not matter if I make **headerTopInsetEnabled: true or false**

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | 
| @react-navigation/native       | 5.9.4
| @react-navigation/stack        | 5.14.5
| react-native-gesture-handler   | 1.10.3
| react-native-safe-area-context | 3.2.0
| react-native-screens           | 3.3.0
| react-native                   | 0.64.1
| expo                           |
| node                           |
| npm or yarn                    |

**Comment by satya164** [comment]
The device you're emulating has a notch. The taller header accounts for the notch.
