### ISSUE TITLE
Janky animation in header when navigating between stacks(auth flow)

### ISSUE THREAD

**Issue by Adnan-Bacic** [react-navigation/react-navigation#9632]
**Current Behavior**

Link to repo: https://github.com/Adnan-Bacic/react_native_stack_navigation

Trying to do the auth flow mentioned in the v5 docs here: https://reactnavigation.org/docs/auth-flow
So when i navigate from one stack to another, there is a janky "jumping" animation, noticeable in the header.

https://user-images.githubusercontent.com/32088941/120106820-dfc13580-c15e-11eb-9a3a-c19222718000.mp4

**Expected Behavior**

I expect the header to stand still when switching stacks instead of jumping.

For example, if i add:
```
screenOptions={{
    headerShown: false,
  }}
```
in all my `Stack.Navigator` to remove the header, it does not jump, so it seems to be just the header in the navigator, not text in the screens.

Example:

https://user-images.githubusercontent.com/32088941/120106972-5fe79b00-c15f-11eb-8ff9-b3b284ff9225.mp4

**How to reproduce**

To reproduce simply run the link i provided. There is no setup required and it is a minimal example that only shows navigating between stacks. The example has 3 different stacks and a single screen per stack. Every screen has 1 button which takes you to another stack so you can see all 3 stacks. Every button press should navigate to another stack and show the janky animation.

The most important file here is `src/navigation/Navigator.js` which handles setting the initial navigator when the app launches as well as switching stacks when needed.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Android
| @react-navigation/native       | 5.9.4
| react-native                   | 0.64.1
| expo                           | -
| node                           | 12.18.3
| npm or yarn                    | Yarn 1.22.5

**Comment by satya164** [comment]
You need to make your status bar translucent - https://stackoverflow.com/a/29311321/1665026

Or specify `headerStatusBarHeight: 0` in `screenOptions` - https://reactnavigation.org/docs/stack-navigator/#headerstatusbarheight

**Comment by Adnan-Bacic** [comment]
> You need to make your status bar translucent - https://stackoverflow.com/a/29311321/1665026
> 
> Or specify `headerStatusBarHeight: 0` in `screenOptions` - https://reactnavigation.org/docs/stack-navigator/#headerstatusbarheight

i dont think setting statusbar to translucent would do anything since this is about the header that shows the screen name, not the statusbar color.

but setting `headerStatusBarHeight: 0` in `screenOptions` fixed it and removed the animation
