### ISSUE TITLE
Indicator not aligned with text in createMaterialTopTabNavigator

### ISSUE THREAD

**Issue by hasnaina-entertainer** [react-navigation/react-navigation#9634]
**Current Behavior**

I am trying to implement the top tab with scrollable tabs which are dynamic in number. It works fine for first tab but is misaligned for the second and later tabs.

<img width="425" alt="Untitled" src="https://user-images.githubusercontent.com/67307736/120313686-c7ceea80-c2f3-11eb-8f91-79c63834900b.png">

**Expected Behavior**

The text should be centered like the initial tab.
<img width="427" alt="Untitledd" src="https://user-images.githubusercontent.com/67307736/120313723-d3baac80-c2f3-11eb-8f8b-80d4f3af42a5.png">

**How to reproduce**

```
<View style={{flex: 1}}>
        {categories.length > 0 && (
          <Tab.Navigator
            lazy
            tabBarOptions={{
              labelStyle: {
                fontSize: 13,
                fontFamily: gothamMedium,
                textTransform: 'none',
                alignSelf: 'center',
                textAlign: 'center',
              },
              indicatorStyle: {
                backgroundColor: colors.AQUAMARINE,
                height: 4,
              },
              activeTintColor: colors.GREYISH_BROWN,
              inactiveTintColor: colors.WARM_GREY,
              scrollEnabled: true,
            }}>
            {categories.map(category => (
              <Tab.Screen
                options={{
                  title: category.title,
                }}
                name={category.title}
                component={() => <TabList tabData={category} />}
              />
            ))}
          </Tab.Navigator>
        )}  </View>
```

**Your Environment**

| software                            | version |
| ----------------------------------- | ------- |
| iOS or Android                      |ios
| @react-navigation/native            |^5.9.4
| @react-navigation/material-top-tabs |^5.3.15
| react-native-tab-view               |^2.16.0
| react-native                        |0.64.0
| expo                                |na
| node                                |v14.4.0
| npm or yarn                         |yarn

**Comment by sujanChy00** [comment]
screenOptions={{
          tabBarContentContainerStyle: {
            justifyContent: "space-between",
          },
        }}
        
        try this
