### ISSUE TITLE
header direction is not reverting on android

### ISSUE THREAD

**Issue by aliwaqar981** [react-navigation/react-navigation#9638]
**Current Behavior**

- What code are you running and what is happening?
`<HomeStack.Navigator
      screenOptions={{
        headerBackTitleVisible: false,
        headerTopInsetEnabled: false,
        direction: I18nManager.isRTL ? 'rtl' : 'ltr',
      }}>
      <HomeStack.Screen
        name="home"
        component={HomeScreen}
        options={{
          headerShown: true,
          headerCenter: () => (
            <Text style={Style.headerText}>{i18n.t('screens.home.title')}</Text>
          ),
        }}
      />
      <HomeStack.Screen
        name="custody"
        component={CustodyScreen}
        options={{
          headerCenter: () => (
            <Text style={Style.headerText}>
              {i18n.t('screens.custody.title')}
            </Text>
          ),
          headerShown: true,
        }}
      />
      <HomeStack.Screen
        name="shipments"
        component={ShipmentStackScreen}
        options={{
          headerShown: false,
        }}
      />
    </HomeStack.Navigator>`
- Include a screenshot or video if it makes sense.
### Android Screenshot
![WhatsApp Image 2021-06-02 at 18 55 35](https://user-images.githubusercontent.com/43547698/120493254-3b482900-c3d4-11eb-8683-41f6eb8edf7f.jpeg)

### Ios Screenshot
![Simulator Screen Shot - iPhone 12 - 2021-06-02 at 18 59 22](https://user-images.githubusercontent.com/43547698/120493780-ae519f80-c3d4-11eb-8e7e-1799a54d50fb.png)

**Expected Behavior**

- It should be same ios view (IOS screenshot attached above)

**How to reproduce**

1. Create new project
2. Install react navigation
3. Set direction: 'rtl' in `screenOptions`
4. Test on Android

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Android
| @react-navigation/native       | ^5.9.4
| @react-navigation/stack        | ^5.14.5
| react-native-gesture-handler   | ^1.8.0
| react-native-safe-area-context | ^3.1.8
| react-native-screens           | ^2.11.0
| react-native                   | 0.64.1
| node                           | v14.16.0
| npm or yarn                    | 1.22.5

**Comment by a7med-mahmoud** [comment]
I have the same problem with react-navigation 6 and native stack navigator
