### ISSUE TITLE
iOS 14.6 breaks the safe-area view

### ISSUE THREAD

**Issue by alimoli** [react-navigation/react-navigation#9641]
**Current Behavior**

- What code are you running and what is happening?
I create a basic bottom tab navigator using the function `createBottomTabNavigator`.

**Expected Behavior**

The bottom tab navigator and the top navigator (for the history) result aligned within the safe-area view of the screen before iOS 14.6. With iOS version 14.6, the bottom tabs go under the gesture icon on the bottom and the back arrow on the history changed its position going a bit closer to the top.

**How to reproduce**

- Just use a basic bottom navigator on iOS 14.6 to see the difference 

```ts
const routes: NavigationRouteConfigMap<NavigationBottomTabOptions, NavigationTabProp<NavigationRoute, any>> = {
	[TabNavigator.App]: {
		screen: AppNavigator,
		navigationOptions: () => ({
			title: translate('nav.home'),
			tabBarIcon: ({focused}) => <Icon
				theme={focused ? 'light' : 'dark'}
				icon={'tabInvoices'}
				containerStyle={tabIconContainerStyle}
			/>
		})
	},
	//etc.
}

export default createBottomTabNavigator(
	routes,
	{
		initialRouteName: TabNavigator.App,
		tabBarOptions: {
			style: {
				height: 62,
				backgroundColor: color.primaryDark,
				paddingTop: 5
			},
			labelStyle: {
				paddingBottom: 5,
				fontSize: 12,
				fontFamily: typography.primary
			},
			inactiveTintColor: color.secondaryLightTransparent,
			activeTintColor: color.secondary
		},
		lazy: false
	}
)
```

I think maybe some constants used by this library changed (?)

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | iOS  14.6
| react-navigation               | 4.4.4 (upgraded)
| react-navigation-stack         | 2.10.4 (upgraded)
| react-navigation-tabs          | 2.11.1 (upgraded)
| react-navigation-drawer        | 2.7.1 (upgraded)
| react-native-reanimated        | ^1.4.0
| react-native-gesture-handler   | ^1.5.2
| react-native-safe-area-context | ^3.2.0
| react-native-screens           | ^2.0.0-alpha.15
| react-native                   | 0.63.2
| expo                           |
| node                           | 12.18.1
| npm or yarn                    | ^1.22.10

**Comment by alimoli** [comment]
Upgraded, but still having the same issue.

**Before iOS 14.6**
![BEFORE_TOP](https://user-images.githubusercontent.com/68189985/120654767-48235600-c482-11eb-9216-c86243ccaddd.png)
![BEFORE_BOTTOM](https://user-images.githubusercontent.com/68189985/120654771-48bbec80-c482-11eb-89c4-f1fe009d03d3.png)

**With iOS 14.6**
![AFTER_TOP](https://user-images.githubusercontent.com/68189985/120654805-507b9100-c482-11eb-9d87-64ff4b7268c1.png)
![AFTER_BOTTOM](https://user-images.githubusercontent.com/68189985/120654798-4fe2fa80-c482-11eb-982e-23946f3dcc8c.png)

**Comment by jamesseils** [comment]
Same issue here when upgrading to ios 14.6

**Comment by wnikola** [comment]
Experiencing the same issue.

**Comment by nikolanjj** [comment]
Same here
