### ISSUE TITLE
Drawer not dismissed on tapping overlay on ipad

### ISSUE THREAD

**Issue by JeremyBradshaw7** [react-navigation/react-navigation#9642]
**Current Behavior**

Tapping the semi-transparent overlay to the right of the drawer menu closes the drawer as expected on Android and on an iphone, but doesn't on an ipad - at least in the simulator, it does close on my one real ipad device but I'm not convinced it will do on all devices.

**Expected Behavior**

Expect it to hide the menu on tapping the overlay to the right of the menu on all devices.

**How to reproduce**

```
    <Drawer.Navigator
      screenOptions={{
        unmountOnBlur: true
      }}
      drawerContentOptions={{
        activeBackgroundColor: 'rgba(255,255,255,0.15)',
        activeTintColor: WallpaperPrimaryColor,
        inactiveTintColor: WallpaperPrimaryColor
      }}
      drawerContent={(props) => <BurgerMenu {...props} />}
      drawerPosition={'left'}
      edgeWidth={0}
      overlayColor={'rgba(0,0,0,0.85)'}
    > 
```

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | iOS |
| @react-navigation/native       |  "^5.9.4" |
| @react-navigation/drawer       | "^5.12.5" |
| react-native-reanimated        | "^2.1.0" |
| react-native-gesture-handler   | "^1.10.3" |
| react-native-safe-area-context | "^3.2.0" |
| react-native-screens           | "^3.1.1" |
| react-native                   | "0.64.1" |
| expo                           | NO |
| node                           | v15.1.0 |
| npm or yarn                    | yarn |

**Comment by musti-91** [comment]
I have the same in IOS (simulator/real device). clicking outside drawer doesn't close drawer in ios.

**Comment by JeremyBradshaw7** [comment]
This is still an issue without a solution.
