### ISSUE TITLE
getFocusedRouteNameFromRoute initial value is undefined until a navigation event populates state

### ISSUE THREAD

**Issue by omonk** [react-navigation/react-navigation#9645]
**Current Behavior**

getFocusedRouteNameFromRoute initial value is undefined when using a StackNavigator and initial route component is a BottomTabNavigator.

If you have a look at the expo link, the initial headerTitle is `UNDEFINED`, once you switch to NestedSettings then back to NestedHome, the headerTitle becomes correctly populated.

**Expected Behavior**

(In the context of my expo example)

The initial focused routername should be `NestedHome` and the headerTitle should be `NestedHome`. 

Looking into [`getFocusedRouteNameFromRoute`](https://github.com/react-navigation/react-navigation/blob/main/packages/core/src/getFocusedRouteNameFromRoute.tsx) and understanding how that works I can see that we have no `state` in the route value on first render but im not sure why? Can we pass initial state? Should initialRouteName solve this issue?

**How to reproduce**

https://snack.expo.io/@omonk/ollie

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS                 | 14
| @react-navigation/native       | ^5.9.4
| @react-navigation/stack        | ^5.14.4
| react-native-gesture-handler   | ^1.10.3
| react-native-safe-area-context | ^3.2.0
| react-native-screens           |  ^2.5.0
| react-native                   | 0.64.0
| node                           | 15.8.0
| yarn                    | 1.22.10

**Comment by omonk** [comment]
Can verify that the issue still exists after upgrading

**Comment by satya164** [comment]
As shown in the documentation, you need to provide the initial route name as the fallback. https://reactnavigation.org/docs/screen-options-resolution#setting-parent-screen-options-based-on-child-navigators-state

It's impossible to automatically determine it.
