### ISSUE TITLE
HeaderBackButton uses require() which doesn't work on RN Web

### ISSUE THREAD

**Issue by ktprograms** [react-navigation/react-navigation#9647]
**Current Behavior**

I ran `npx create-react-native-web-app ReactNativeWebAppTest` to create a blank React Native Web project. Then I ran `yarn add @react-navigation/native @react-navigation/stack react-native-reanimated react-native-gesture-handler react-native-screens react-native-safe-area-context @react-native-community/masked-view as well as yarn workspace mobile add @react-navigation/native @react-navigation/stack react-native-reanimated react-native-gesture-handler react-native-screens react-native-safe-area-context @react-native-community/masked-view`. I then added some basic navigation as a test. On mobile, the `HeaderBackButton` shows as expected, but on Web there is no `back-icon` image but the button works to go back. As part of my debugging, I tried just putting the `back-icon` image in my layout. It turns out (as answered several times [on Stackoverflow](https://stackoverflow.com/a/64829831)) that you need to `import` the image rather than `require`-ing it to show on Web. In the [source code](https://github.com/react-navigation/react-navigation/blob/fe6d20c10e615cf0d538783ba88642ec3ef44c71/packages/elements/src/Header/HeaderBackButton.tsx) for `HeaderBackButton` in `@react-navigation/stack`, the image is being `require`'d, so it isn't showing on Web.
Link to my code: [https://github.com/ktprograms/ReactNativeWebAppTest](https://github.com/ktprograms/ReactNativeWebAppTest)

Screenshots (Android emulator, working):
![Screenshot 2021-06-05 at 10 35 42 AM](https://user-images.githubusercontent.com/71804605/120877560-cfd7a480-c5e9-11eb-9b9c-905ffa494b8f.png)![Screenshot 2021-06-05 at 10 38 23 AM](https://user-images.githubusercontent.com/71804605/120877628-2b099700-c5ea-11eb-96f9-a681563fb02e.png)

Screenshots (Web, not working):
<img width="686" alt="Screenshot 2021-06-05 at 10 36 31 AM" src="https://user-images.githubusercontent.com/71804605/120877597-feee1600-c5e9-11eb-90d1-e8849da2a405.png">
<img width="686" alt="Screenshot 2021-06-05 at 10 37 34 AM" src="https://user-images.githubusercontent.com/71804605/120877613-10372280-c5ea-11eb-8fb1-cdf00f967af9.png">

**Expected Behavior**

`HeaderBackButton` should show `back-icon` image on Web as well.

**How to reproduce**

```
git clone https://github.com/ktprograms/ReactNativeWebAppTest
cd ReactNativeWebAppTest
yarn
cd packages/mobile/ios && pod update && pod install && cd -
yarn ios                     (runs on iOS)
yarn android             (runs on Android)
yarn web                   (runs on Web)
```

Then click the 'Go To Details' Button.

Source code is in `src/App.js`

**Your Environment**

I'm using MacOS 11.2.3 on a MacBook Air (M1, 2020). The above steps to reproduce were run in a Terminal.app window with Rosetta enabled.

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | iPhone 12 mini (simulator), Android S Emulator
| @react-navigation/native       | ^5.9.4
| @react-navigation/stack        | ^5.14.5
| react-native-gesture-handler   | ^1.10.3
| react-native-safe-area-context | ^3.2.0
| react-native-screens           | ^3.2.0
| react-native                   | 0.63.3
| expo                           | not using
| node                           | v16.0.0
| npm or yarn                    | yarn 1.22.10

**Comment by satya164** [comment]
If something works with import but not with require, then that's an issue in your webpack configuration, not the library. It's the same code that works in React Native, your webpack configuration needs to account for that. In your repo, the webpack config treats images like modules which isn't how it works in React Native.

You can use a React Native Web optimized configuration preset like `@expo/webpack-config` (it's already pre-configured if you use `expo`) or configure webpack yourself: https://necolas.github.io/react-native-web/docs/multi-platform/#compiling-and-bundling
