### ISSUE TITLE
Bottom tab navigator size problem on app start

### ISSUE THREAD

**Issue by Vinnecent** [react-navigation/react-navigation#9649]
@react-navigation/native v5.9.4

I implemented the minimal example of the bottom tab navigator into my project.
When i start the my app the bottom tab navigator for one second is larger than it should be.

<img src="https://user-images.githubusercontent.com/44996141/120905674-05b17300-c654-11eb-8316-ca5f1dce6a4b.jpg" width="540" height="1200">

After this one second it looks normal.

<img src="https://user-images.githubusercontent.com/44996141/120905694-28dc2280-c654-11eb-942b-e3fccf95e364.jpg" width="540" height="1200">

The problem can be replicated by using the snack link underneath the minimal example of tab-based navigation.
https://reactnavigation.org/docs/tab-based-navigation/

The problem seems to only trigger on android.

**Comment by gusma296** [comment]
same problem on android, please help

**Comment by gusma296** [comment]
same problem on android, please help

**Comment by gusma296** [comment]
i found a solution for this issue, add SafeAreaProvider from react-native-safe-area-context
import React from 'react';
import Navigator from './navigation/Navigator';
import {SafeAreaProvider} from 'react-native-safe-area-context';

const App = () => {
  return (
        <SafeAreaProvider>
          <Navigator />
        </SafeAreaProvider>
  );
};

export default App;

**Comment by richardwu** [comment]
Thank you, this worked!
