### ISSUE TITLE
CommonActions.reset can't merge initial params to new screen.

### ISSUE THREAD

**Issue by LogLiangTang** [react-navigation/react-navigation#9654]
**Current Behavior**

- I used CommonActions.reset to close mid screen and open a new screen, but initial params doesn't merge to the new screen.

**Expected Behavior**

- CommonActions.reset can merge initial params to new screen.
- Here is code :
`
let routes = state.routes.filter(route => {
        return route.name !=== 'Contact';
      });
      return CommonActions.reset({
        ...state,
        routes: [...routes, {name: 'Detail', params:{name: '123'}}],
        index: routes.length,
      });
`

`
      <Stack.Screen
        name="Detail"
        component={DetailScreen}
        initialParams={{countryId: 'ID'}}
      />
`
The countryId doesn't merge to Detail screen.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |
| @react-navigation/native       |
| @react-navigation/stack        |

**Comment by ajsmth** [comment]
This seems to be the expected behaviour as outlined in the docs: https://reactnavigation.org/docs/navigation-actions/#reset

```
The state object specified in reset replaces the existing navigation state with the new one. This means that if you provide new route objects without a key, or route objects with a different key, it'll remove the existing screens for those routes and add new screens.

If you want to preserve the existing screens but only want to modify the state, you can pass a function to dispatch where you can get the existing state. Then you can change it as you like (make sure not to mutate the existing state, but create new state object for your changes). and return a reset action with the desired state:
```
