### ISSUE TITLE
Fixed HeaderBackButton not showing up on Web

### ISSUE THREAD

**Issue by ktprograms** [react-navigation/react-navigation#9655]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

I used [patch-package](https://github.com/ds300/patch-package) to patch `@react-navigation/stack@5.14.5` for the project I'm working on.

The `HeaderBackButton` component uses `require('../assets/back-icon.png')` to load the image. This works fine on iOS / Android. However, `create-react-app` has a bug that you need to use `require('../assets/back-icon.png').default` ([found the solution here](https://github.com/facebook/create-react-app/issues/10088#issuecomment-731707142)). I have tested that this patch works.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@react-navigation/stack/lib/module/views/Header/HeaderBackButton.js b/node_modules/@react-navigation/stack/lib/module/views/Header/HeaderBackButton.js
index 8e8e4ad..437cd68 100644
--- a/node_modules/@react-navigation/stack/lib/module/views/Header/HeaderBackButton.js
+++ b/node_modules/@react-navigation/stack/lib/module/views/Header/HeaderBackButton.js
@@ -50,7 +50,7 @@ export default function HeaderBackButton({
         style: [styles.icon, Boolean(labelVisible) && styles.iconWithLabel, Boolean(tintColor) && {
           tintColor
         }],
-        source: require('../assets/back-icon.png'),
+        source: require('../assets/back-icon.png').default,
         fadeDuration: 0
       });
     }
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**How to reproduce**

Example repository: [https://github.com/ktprograms/ReactNativeWebAppTest](https://github.com/ktprograms/ReactNativeWebAppTest)
To run:
```
git clone https://github.com/ktprograms/ReactNativeWebAppTest
cd ReactNativeWebAppTest
yarn
cd ios && pod update && pod install && cd -
yarn ios                     (runs on iOS)
yarn android             (runs on Android)
yarn web                   (runs on Web)
```
Then click on the `Go to details` button.
At this point, it will be fully working on iOS and Android, but the back button won't be showing on Web. You'll need to patch `@react-navigation/stack` using:
```
npx patch-package
```
Then re-run `yarn web` and it should be working!

**Your Environment**

I'm using MacOS 11.2.3 on a MacBook Air (M1, 2020). The above steps to reproduce were run in a Terminal.app window with Rosetta enabled.

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | iPhone 11 (simulator), Android S Emulator
| Browser                            | Safari Version 14.0.3 (16610.4.3.1.7)
| @react-navigation/native       | ^5.9.4
| @react-navigation/stack        | ^5.14.5 (patched)
| react-native-gesture-handler   | ^1.10.3
| react-native-safe-area-context | ^3.2.0
| react-native-screens           | ^3.3.0
| react-native                   | ^0.63.3
| expo                           | not using
| node                           | v16.0.0
| npm or yarn                    | yarn 1.22.10

**Comment by ajsmth** [comment]
this appears to be an issue with the webpack resolver in that package you are using.  I would suggest contacting them about updating it - in the mean time, you could override the back button with the correct image for your web project if you do not want to go the patch-package route

**Comment by camilossantos2809** [comment]
I had a similar problem, but with react-native-web.
The problem seems to be related to the url-loader.
I changed my webpack.config.js as below and it worked for me:

` 
module: {
    rules: [
      {
        test: /\.(gif|jpe?g|png)$/,
        type: "asset/resource",
      }
    ],
  },
`

More info [here](https://webpack.js.org/guides/asset-modules/)

**Comment by ktprograms** [comment]
> I changed my webpack.config.js as below and it worked for me:
>
> `module: { rules: [ { test: /\.(gif|jpe?g|png)$/, type: "asset/resource", } ], },`

How did you do that? I thought that requires Webpack 5 and create-react-app uses Webpack 4?

**Comment by camilossantos2809** [comment]
> > I changed my webpack.config.js as below and it worked for me:
> > `module: { rules: [ { test: /\.(gif|jpe?g|png)$/, type: "asset/resource", } ], },`
> 
> How did you do that? I thought that requires Webpack 5 and create-react-app uses Webpack 4?

I added react-native-web to an existing RN project so I had to use Webpack (5) directly and not create-react-app.

**Comment by ktprograms** [comment]
>>> I changed my webpack.config.js as below and it worked for me:
>>> `module: { rules: [ { test: /\.(gif|jpe?g|png)$/, type: "asset/resource", } ], },`
>>
>> How did you do that? I thought that requires Webpack 5 and create-react-app uses Webpack 4?
>
> I added react-native-web to an existing RN project so I had to use Webpack (5) directly and not create-react-app.

I see. Since I'm stuck with Webpack 4, I set `esModule: false` in the `webpack.config.js` `url-loader` sections. (see https://github.com/ktprograms/ReactNativeWebAppTest/blob/2b9376a843d6953f2e444f4122df361b78411df1/config/webpack.config.js#L371-L392).
