### ISSUE TITLE
Swipe to dismiss also trigger touchable item at the edge of screen

### ISSUE THREAD

**Issue by tien** [react-navigation/react-navigation#9657]
**Current Behavior**

On iOS swiping left to right from the edge of the screen will navigate to the previous screen. Unfortunately, if there are touchable components at the edge of the screen, the "onPress" event will also be triggered for those items. This will cause a very weird behaviour if those items are navigation link

**Expected Behavior**

When swiping to dismiss the current screen, "onPress" should not be triggered for items that were also at the edge of the screen. It should behave similarly to ScrollView where scrolling will cancel out touch event on items in the ScrollView

**How to reproduce**

Create a stack navigator with a list of touchable items that expand all the way to the edge, swiping left to right from the edge will also trigger a touch event on those items.

**Your Environment**

| software                       | version |
| ------------------------------- | ------- |
| iOS                                               | any
| @react-navigation/native           | ^5.9.4
| @react-navigation/stack            |^5.14.4
| react-native-gesture-handler    |^1.10.3
| react-native-safe-area-context |^3.2.0
| react-native-screens                  |^3.1.1
| react-native                                 |0.63.4

**Comment by andreasospedra** [comment]
I have the same issue and I can confirm that it is also happening with the latest versions of the packages `@react-navigation/stack`.

**Comment by tien** [comment]
@andreasospedra Can you see if updating `react-native-screens` to `3.4.0` fix it for you? As mentioned in this issue https://github.com/software-mansion/react-native-screens/issues/972

**Comment by tien** [comment]
Issue was fixed by upgrading `react-native-screens` to `^3.4.0`
