### ISSUE TITLE
Add a way to provide own dimensions values

### ISSUE THREAD

**Issue by CptFabulouso** [react-navigation/react-navigation#9659]
**Current Behavior**

Because of error in `Dimensions` API in react-native, tab bar can be stuck in `beside-icon` display, while device is in portrait and should be displayed with `below-icon`. Issues with Dimensions API here https://github.com/facebook/react-native/issues/31692 or https://github.com/facebook/react-native/issues/29290
Since I do not expect that API to be fixed anytime soon, it would be useful to be able to workaround it by passing own dimensions values, which can be obtained e.g. by using `react-native-orientation-locker`, which updates orientation correctly. Or use that lib or similar in this package.

**Expected Behavior**

Tab bar has correct dimensions.

**How to reproduce**

Follow steps in linked issues

**Your Environment**

| software                      | version |
| ----------------------------- | ------- |
| iOS or Android                |iOS 14.5|
| @react-navigation/native      |5.9.4|
| @react-navigation/bottom-tabs |5.11.11|
| react-native-screens          |2.18.1|
| react-native                  |0.62.2|
| node                          |14.5.0|
| yarn                   |1.22.10|

**Comment by satya164** [comment]
Please check if it's fixed in 6.x. It doesn't use `Dimensions` API.
