### ISSUE TITLE
navigating to absolute path on web breaks app

### ISSUE THREAD

**Issue by dereknelson** [react-navigation/react-navigation#9660]
**Current Behavior**

I have a linking config like so: 
```
export const linkingConfig = {
    prefixes: [],
    config: {
        screens: {
            [AUTH_NAVIGATOR]: {
                screens: {
                    home: '',
                    signup: 'signup',
                    login: 'login',
                },
            },
        },
    },
}
```
when running in development, going to `/signup` or `/signup/` loads `/signup`no problem
when deployed, navigating around correctly sets the path to `/signup` but if i navigate to `mydomain.com/signup` it appends a slash and breaks on chrome and safari. this is also true when i build it and serve it locally `localhost:5000`. i've tried adding every variation of `prefixes: ["localhost:5000", "https://mydomain.com"]` to no avail.

https://user-images.githubusercontent.com/6868432/121393569-7986a080-c91e-11eb-8810-7fec8dd9b3f3.mov

**Expected Behavior**

The web app not to completely break

**How to reproduce**

clone https://github.com/dereknelson/react-navigation-web-repro
`expo start`
w for web
`npx serve web-build`

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or android | web! lol |
| @react-navigation/native |  5.9.4 |
| react-native                   | 0.63.4
| expo                           | 41.0.1 |
| node                           | 14.15.1 |
| npm or yarn                    | yarn |

**Comment by satya164** [comment]
That error is from your server (`npx serve` in local, and whichever provider you use for prod), not from React Navigation (or even a client-side error). You need to handle that on your server.
