### ISSUE TITLE
Unable to resolve module ./views/DrawerToggleButton from @react-navigation\drawer

### ISSUE THREAD

**Issue by AnasAlamin** [react-navigation/react-navigation#9664]
**Current Behavior**

i'm trying to install @react-navigation\drawer but it's not working for me with the below error.

Unable to resolve module ./views/DrawerToggleButton from C:\[project_dir]\node_modules\@react-navigation\drawer\src\index.tsx:

None of these files exist:
  * node_modules\@react-navigation\drawer\src\views\DrawerToggleButton(.native|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json)
  * node_modules\@react-navigation\drawer\src\views\DrawerToggleButton\index(.native|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json)
> 1 | /**
  2 |  * Navigators
  3 |  */
  4 | export { default as createDrawerNavigator } from './navigators/createDrawerNavigator';

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | ios 14.3
| @react-navigation/native       | ^5.9.3
| @react-navigation/drawer       | ^5.12.5
| react-native-reanimated        | ~2.1.0
| react-native-gesture-handler   | ~1.10.2
| react-native-safe-area-context | 3.2.0
| react-native-screens           | ~3.0.0
| react-native                   | n/a
| expo                           | ^41.0.0
| node                           | v14.16.0
| npm or yarn                    | 6.14.11

**Comment by AnasAlamin** [comment]
> The versions mentioned in the issue for the following packages differ from the latest versions on npm:
> 
> * `@react-navigation/native` (found: `5.9.3`, latest: `5.9.4`)
> 
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?

error is still persisted

**Comment by AnasAlamin** [comment]
i downgraded versions and it worked, weird!!

**Comment by Madhav-Malhotra** [comment]
> i downgraded versions and it worked, weird!!

Which version did you downgrade to? @AnasAlamin

**Comment by raajnadar** [comment]
It is advised to upgrade to latest version and run `npx react-native --reset-cache && npx react-native run-android`

**Comment by Madhav-Malhotra** [comment]
@raajnadar Yes, what worked for me was to just uninstall and re-install everything to the latest version
```
npm uninstall @react-navigation/drawer @react-navigation/native react-native-reanimated
npm install @react-navigation/drawer @react-navigation/native react-native-reanimated
```
