### ISSUE TITLE
[v6] Navigate event is not handled in Stack + Tab nested navigation

### ISSUE THREAD

**Issue by AVancans** [react-navigation/react-navigation#9669]
If I have `Tab` navigator as a parent and `Stack` navigator as a child, navigating to a different tab from the child stack works well. However, if I have `Stack` navigator as parent and `Tab` navigator as a child, then navigating to a different stack from the tab screen throws `payload was not handled by any navigator` (using the same navigation event).

**Current Behavior**

```

function AuthenticatedTabs() {

  return ( 
    <NavigationContainer  independent={true}>
      <Tab.Navigator>
        <Tab.Screen name="Home" component={HomePage}  />
        <Tab.Screen name="Profile" component={ProfilePage}  />
      </Tab.Navigator>
    </NavigationContainer>
  );

}

export function RootStack() {

  return (
    <NavigationContainer  independent={true}>
      <Stack.Navigator >
        <Stack.Screen name="AuthenticatedTabs" component={AuthenticatedTabs}  />
        <Stack.Screen name="AboutPage" component={AboutPage}  />
        <Stack.Screen name="LoginPage" component={LoginPage}  />
      </Stack.Navigator>
    </NavigationContainer>
  );

}
```

`HomePage` component wants to show `AboutPage` stack component

```
const navigator = useNavigator();
navigator.navigate('AboutPage');
```

Throws 
```
The action 'NAVIGATE' with payload {"name":"AboutPage"} was not handled by any navigator.

Do you have a screen named 'AboutPage'?
```

**Expected Behavior**

Navigates to `AboutPage` stack screen.

**Your Environment**
```
"react": "17.0.1",
"react-native": "0.64.1",
"@babel/core": "^7.12.9",
"@babel/runtime": "^7.12.5",
"@react-navigation/native": "^6.0.0-next.13",
"@react-navigation/stack": "^6.0.0-next.25",
"@react-navigation/bottom-tabs": "^6.0.0-next.18",
```

This might be `useNavigation()` issue - if I create a global ref to the Stack navigator use that instead of `useNavigation()`, then it works well.

**Comment by satya164** [comment]
It doesn't work because you have added `NavigationContainer` with `independent={true}`. Unless you have a use case for making navigation trees independent, There should only be one `NavigationContainer` at the root of the app.
