### ISSUE TITLE
Drawer never dismiss when drawerPosition = right and nesting (v6)

### ISSUE THREAD

**Issue by likeSo** [react-navigation/react-navigation#9676]
**Current Behavior**

- What code are you running and what is happening?
- Include a screenshot or video if it makes sense.
![image](https://user-images.githubusercontent.com/12247340/122209254-e974c800-ced6-11eb-8fff-3eb6c518d1ff.png)

My screen architecture: Drawer Navigator(For a settings screen, drawerPosition: left) -> Drawer Navigator(For filter screen, drawerPosition: right) -> Counter Sale Orders Screen

For now, the filter drawer always display as the image above. The weird the is that everything is OK when i Turn on 'Debug Remote JS'.

**Expected Behavior**

- What do you expect should be happening?
- Include a screenshot or video if it makes sense.

**How to reproduce**

- You must provide a way to reproduce the problem. If you are having an issue with your machine or build tools, the issue belongs on another repository as that is outside of the scope of React Navigation.
- Either re-create the bug on [Snack](https://snack.expo.io) or link to a GitHub repository with code that reproduces the bug.
- Explain how to run the example app and any steps that we need to take to reproduce the issue from the example app.
- Keep the repro code as simple as possible, with the minimum amount of code required to repro the issue.
- Before reporting an issue, make sure you are on latest version of the package.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |
| @react-navigation/native       |^6.0.0-next.13|
| @react-navigation/drawer       |^6.0.0-next.17|
| react-native-reanimated        |~2.1.0|
| react-native-gesture-handler   |~1.10.2|
| react-native-safe-area-context |^3.2.0|
| react-native-screens           |^3.3.0|
| react-native                   |0.63.4|
| expo                           |^41.0.0|
| node                           |v14.15.4|
| npm or yarn                    |yarn|

**Comment by likeSo** [comment]
Landscape screenshots:
Normally:
<img width="854" alt="image" src="https://user-images.githubusercontent.com/12247340/122366985-a37b3b00-cf8e-11eb-9338-f346c148882a.png">
When Filter Drawer should visible:
<img width="854" alt="image" src="https://user-images.githubusercontent.com/12247340/122367087-b5f57480-cf8e-11eb-8f42-7989327178a4.png">
When Settings Drawer visible and Filter Drawer invisible:
<img width="854" alt="image" src="https://user-images.githubusercontent.com/12247340/122367184-c9a0db00-cf8e-11eb-8e54-a99bb707c564.png">

**Comment by likeSo** [comment]
Is there anyone who saw this? Who can solve this problem? What should I do?

**Comment by likeSo** [comment]
When i was trying to reproduce this problem, i found another bug... The drawer items are gone when a switch between screens quickly... I will file a new issue soon

**Comment by likeSo** [comment]
#9732

**Comment by likeSo** [comment]
I am using the latest beta version of v6, it seems been solved

**Comment by KolbySisk** [comment]
I'm seeing the same problem on v6.0.6
