### ISSUE TITLE
Bottom Tab style backgroundColor with iPhone X safe area v6

### ISSUE THREAD

**Issue by samuelbeaulieu** [react-navigation/react-navigation#9683]
**Current Behavior**

- What code are you running and what is happening?

The safe area at the bottom an iPhone X does not change background color on v6 like it did on v5.

- Include a screenshot or video if it makes sense.
![IMG_4583](https://user-images.githubusercontent.com/64789082/122651211-58376880-d105-11eb-8ad0-4da86e852569.PNG)

**Expected Behavior**

- What do you expect should be happening?
- Include a screenshot or video if it makes sense.
![IMG_4584](https://user-images.githubusercontent.com/64789082/122651234-7c934500-d105-11eb-9797-ef2fedd65ed2.PNG)

**How to reproduce**

Based on the code provided here: https://reactnavigation.org/docs/tab-based-navigation#a-stack-navigator-for-each-tab
I made an example on v5: https://snack.expo.io/@samuelbeaulieu/bottom-tabs-v5
Another one on v6: https://snack.expo.io/@samuelbeaulieu/bottom-tabs-v6

You should see right away that the safe area at the bottom an iPhone X does not change background color like it did on v5.

Line 66-77:
```js
      <Tab.Navigator screenOptions={{ headerShown: false }}
        tabBarOptions={{
          activeTintColor: 'red',
          inactiveTintColor: 'lime',
          tabStyle: {
            backgroundColor: 'blue',
          },
          style: {
            backgroundColor: 'blue',
          },
        }}
      >
```

My project is a React Native CLI one, but snack is still reproducing the problem so I though it would be easier to share.

**Your Environment**

| software                      | version |
| ----------------------------- | ------- |
| iOS or Android                |iOS 14.6
| @react-navigation/native      |^6.0.0-next.13
| @react-navigation/bottom-tabs |^6.0.0-next.18
| react-native-screens          |^3.4.0
| react-native                  |0.64.2
| expo                          |x
| node                          |14.17.0
| npm or yarn                   |npm v6.14.13

**Comment by samuelbeaulieu** [comment]
Okay, I read another part of the documentation on "Upgrading from 5.x", the new props names for the Bottom Tab are shown there, but not in the Bottom Tab documentation. It's now working has expected with the right props names. I'll close this issue, but the documentation should be updated to reflect those changes. I'll make a PR when I have time.

**Comment by jossydeleon** [comment]
@samuelbeaulieu you can try this: 
`<SafeAreaView style={{ flex:0, backgroundColor: 'blue' }} />`
      `<SafeAreaView style={{ flex:0, backgroundColor: 'red' }}>`
        `<StatusBar  />`
`</SafeAreaView>`

Hope this works ok

**Comment by jambu43** [comment]
<Navigator
      screenOptions={{
        tabBarActiveTintColor: theme.colors.main,
        tabBarInactiveTintColor: theme.colors.text_detail,
        tabBarShowLabel: false,
        tabBarStyle: {
          paddingVertical: Platform.OS === 'ios' ? 20 : 0,
          height: 78,
          backgroundColor: theme.colors.background_primary
        }
      }}
    >
