### ISSUE TITLE
Authentication example - missing <NavigationController> ?

### ISSUE THREAD

**Issue by esharmony** [react-navigation/react-navigation#9687]
### Discussed in https://github.com/react-navigation/react-navigation/discussions/9677

<div type='discussions-op-text'>

<sup>Originally posted by **esharmony** June 18, 2021</sup>
https://levelup.gitconnected.com/create-an-authorization-flow-with-react-navigation-5-x-10b84677806b

Looking at the authentication example in the documentation from the above link - the final code for App returns a Stack.Navigator wrapped in the context provider. Should this not be wrapped first in the <NavigationController></Nav... ?

I think this is the case, but maybe I am missing something.</div>

**Comment by ajsmth** [comment]
Hi - it's entirely possible there are small mistakes in the article! I would suggest contacting the author directly about this
