### ISSUE TITLE
Not clearing history of drawer with connect to tab

### ISSUE THREAD

**Issue by KumariShalini** [react-navigation/react-navigation#9690]
"react": "17.0.1",
"@react-navigation/bottom-tabs": "^5.11.11",
"@react-navigation/drawer": "^5.12.5",
"@react-navigation/native": "^5.9.4",
"@react-navigation/stack": "^5.14.5","react-native": "0.64.1",

I have 3 tab item (About, Home and Contact)
and 3 drawer item (Home, profile and settings)

here, home is default for tab and drawer also, so my problem is when i change the tab to about and go to drawer and change the item to profile, and then click home in drawer, that is not going to homw page, it is showing previous state means About screen. so can someone out me from problem, Please. Thank you,

**Comment by KumariShalini** [comment]
https://user-images.githubusercontent.com/23182585/123054217-46660600-d422-11eb-8760-53f3a5d322cb.mp4

**Comment by KumariShalini** [comment]
Please, anyone can help me to out from this above problem? Thank you.

**Comment by ajsmth** [comment]
If you can send me a reproducible example we can help you out @KumariShalini !

**Comment by KumariShalini** [comment]
> If you can send me a reproducible example we can help you out @KumariShalini !

i have added the example above in simulator, thank you.
