### ISSUE TITLE
interpolate() was renamed to interpolateNode() in Reanimated 2. Please use interpolateNode() instead

### ISSUE THREAD

**Issue by glenvollmer** [react-navigation/react-navigation#9699]
**Current Behavior**
at node_modules/@react-navigation/drawer/src/views/DrawerView.tsx:166:22 in renderNavigationView
at node_modules/@react-navigation/drawer/src/views/Drawer.tsx:698:32 in DrawerView#render
at [native code]:null in performSyncWorkOnRoot
at node_modules/react/cjs/react.development.js:490:2 in Component.prototype.forceUpdate
at node_modules/@react-navigation/drawer/src/views/Drawer.tsx:372:10 in call$argument_1
at node_modules/react-native-reanimated/src/reanimated1/core/AnimatedCall.js:10:10 in listener
at node_modules/react-native/Libraries/vendor/emitter/EventEmitter.js:189:10 in emit
at [native code]:null in callFunctionReturnFlushedQueue

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS                 |  14.5
| @react-navigation/native       |  5.9.4
| @react-navigation/drawer       | 5.12.5
| react-native-reanimated        | 2.1.0
| react-native-gesture-handler   | 1.10.2
| react-native-safe-area-context | 3.2.0
| react-native-screens           | 3.0.0
| react-native                   | 0.63.4
| expo                           | 41.0.0
| node                           | 14.17.1
| npm                   | 6.14.13

**Comment by glenvollmer** [comment]
when can we expect a fix for this???

**Comment by ajsmth** [comment]
If you provide a repro then we can fix it!

**Comment by LuuchoRocha** [comment]
Are you using a custom card interpolator or custom transitions?

**Comment by dapicester** [comment]
Related to #9665.
