### ISSUE TITLE
createDrawerNavigator - Compilation failed

### ISSUE THREAD

**Issue by adrianmcg85** [react-navigation/react-navigation#9706]
### Description

I’m getting ‘failed to compile’
Support for the experimental syntax ‘jsx’ isn’t currently enabled.

### Reproduction

https://github.com/react-navigation/drawer

### Platform

- [ ] Android
- [ ] iOS
- [X] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 5.9.4
| @react-navigation/bottom-tabs          |
| @react-navigation/drawer               |5.12.5
| @react-navigation/material-bottom-tabs |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                |
| react-native-safe-area-context         |3.2.0
| react-native-screens                   |3.4.0
| react-native-gesture-handler           |1.10.3
| react-native-reanimated                |2.2.0
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           |0.64.3
| expo                                   |
| node                                   |12.19.0
| npm or yarn                            | 6.14.8

**Comment by ajsmth** [comment]
Hi there - this sounds like an issue with your babel or metro config, not `react-navigation` - you'll likely find better answers here: https://stackoverflow.com/questions/63005011/support-for-the-experimental-syntax-jsx-isnt-currently-enabled

**Comment by kdevsoftware** [comment]
got the same error. what are the solutions to fix this problem?
