### ISSUE TITLE
URL Prefix documentation is not correct for standalone Expo apps

### ISSUE THREAD

**Issue by phatmann** [react-navigation/react-navigation#9709]
### Description

See #9081. The [React Navigation documentation](https://reactnavigation.org/docs/deep-linking#uri-prefix) for URL Prefixes in Expo is not correct. It mistakenly says that `createURL` has different behavior than `makeUrl` but per [Expo docs](https://docs.expo.io/versions/latest/sdk/linking/#linkingmakeurlpath-options-scheme) `makeUrl` is just an alias for `createURL`. I verified that they both behave the same. The React Navigation documentation implies that the `createURL` properly handles standalone apps, but this is not the case. 

The correct code is given in #9081:

```
import Constants, {AppOwnership} from 'expo-constants';
import * as Linking from 'expo-linking';

const isStandalone = Constants.appOwnership === AppOwnership.Standalone

<NavigationContainer
   linking={{
        prefixes: [
            Linking.createURL(isStandalone ? '' : '/'),
            // your associated domains, etc.
        ],
   }}
>
...
</NavigationContainer >
```

### Reproduction

https://github.com/react-navigation/react-navigation/issues/9081

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 5.9.4
| @react-navigation/stack                | 5.14.5
| @react-navigation/bottom-tabs | 5.11.11
| @react-navigation/drawer | 5.12.5
| @react-navigation/material-bottom-tabs  | 5.3.15
| @react-navigation/material-top-tabs  | 5.3.15
| react-native-safe-area-context         | 3.2.0
| react-native-screens                   | 3.0.0
| react-native-gesture-handler           | 1.10.3
| react-native-reanimated                | 2.1.0
| react-native-pager-view                | 5.0.12
| react-native                           | 0.63.2
| expo                                   | 41.0.0
| node                                   | 14.17.0
| yarn                            | 1.22.5

**Comment by phatmann** [comment]
Updated package versions, they are not relevant for this ticket anyway.

**Comment by satya164** [comment]
> It mistakenly says that createURL has different behavior than makeUrl

They have different behavior, and you can see their code that `makeUrl` uses different options.

https://github.com/expo/expo/blob/8f43418f248336b7906e2eb246ed105aa1789930/packages/expo-linking/src/Linking.ts#L91

> Updated package versions, they are not relevant for this ticket anyway.

It is relevant because as you see in the issue, it was fixed in the linked commit and you're using old versions without the fix.

> The correct code is given in #9081

The issue was already closed with a fix.

**Comment by phatmann** [comment]
Thanks for taking the time to review my issue and correct my error. I just updated to Expo 41 recently, so their fix must have been very recent!

**Comment by phatmann** [comment]
Actually I do have the relevant Expo code in my project. It is not working as advertised. But I will leave my fix in and let this issue go. It will be here for others to find.
