### ISSUE TITLE
Deep links to unopened application fail with "'navigation' object hasn't been initialized yet"

### ISSUE THREAD

**Issue by phatmann** [react-navigation/react-navigation#9713]
### Current behavior

I am trying to reopen #8537. The suggested setTimeout workaround does not work for me.

I have copied portions of that issue into this one.

I have added deep link support to my application that looks like this:

```
const ROUTING = {
  prefixes: ['https://my.app', 'myapp://'],
  config: {
    Main: {
      screens: {
        Explore: {
          path: 'map/:latitude/:longitude/:zoom',
          parse: {
            latitude: Number,
            longitude: Number,
            zoom: Number,
          },
        },
      },
    },
  },
};

...

export default function App() {
 
  return (
      <NavigationContainer linking={ROUTING} fallback={<Text>Loading...</Text>}>
            ....
      </NavigationContainer>
  );
}
```

This code works great when the application is already launched but when I try to use a deep link to launch the unlaunched application it fails with:

```
Error: The 'navigation' object hasn't been initialized yet. This might happen if you don't have a navigator mounted, or if the navigator hasn't finished mounting. See https://reactnavigation.org/docs/navigating-without-navigation-prop#handling-initialization for more details.

dispatch
    BaseNavigationContainer.tsx:140:10
listener
    useLinking.native.tsx:107:25
emit
    EventEmitter.js:189:10
__callFunction
    MessageQueue.js:425:19
__guard$argument_0
    MessageQueue.js:112:6
__guard
    MessageQueue.js:373:10
callFunctionReturnFlushedQueue
    MessageQueue.js:111:4
callFunctionReturnFlushedQueue
    [native code]:0
```

### Expected behavior

Deep linking works even when app is closed.

### Reproduction

https://github.com/phatmann/deeplinkbug

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |  5.9.4
| @react-navigation/bottom-tabs          |  5.11.11
| @react-navigation/drawer               |  5.12.5
| @react-navigation/stack                |. 5.14.5
| react-native-safe-area-context         | 3.2.0
| react-native-screens                   | 3.0.0
| react-native-gesture-handler           | 1.10.3
| react-native-reanimated                | 2.2.0
| react-native-pager-view                | 5.2.1
| react-native                           | 0.63.2
| expo                                   | 41.0.1
| node                                   | 14.17.0
| yarn                            | 1.22.5

**Comment by phatmann** [comment]
The repro link does not actually reproduce the bug, but it does reproduce the scenario that causes the crash in my app. I am not sure what the difference is yet, but I am trying different configurations to see. I believe the difference is  either (1) that my app is much larger and/or (2) does more operations before NavigationContainer is loaded. This causes the navigation object to not be ready when the deep link is processed.

Please leave this issue open for a while to give me time to repro. Thanks.

**Comment by phatmann** [comment]
With the repro code I published, I cannot get deep links from notifications to work at all when the app is closed. Please take a look and see what I could be doing wrong.

**Comment by phatmann** [comment]
I did provide a repro in Github. Since the bug involves push notifications, I don't think using snack.expo.io would work out.

**Comment by phatmann** [comment]
Ah, I see that the "repro provided" label was removed because I said the provided code did not repro the issue. Fair enough. I will try and alter it to repro the issue. Please leave this ticket open in the meantime. Thanks.

**Comment by phatmann** [comment]
I am going to spend some more time digging in on this issue. Stay tuned...

**Comment by phatmann** [comment]
In the repro code posted, tapping a notification does not open the deep link. This is the relevant code:

```
React.useEffect(() => {
    const subscription = Notifications.addNotificationResponseReceivedListener(response => {
      const route = response.notification.request.content.data.route as string;
      const url = Linking.createURL(route);
      Linking.openURL(url);
    });
    return () => subscription.remove();
  }, []);
```

I verified that `url` is "deeplinkbug://two". I verified that this URL works by doing:

```
xcrun simctl openurl booted deeplinkbug://two
```

Thinking this was a timing issue, I added a timeout before calling openURL:

```
...
setTimeout(() => Linking.openURL(url), 500);
...
```

With this change, the notification deep link opens, although you can see Tab One show first due to the delay.

Before I can reproduce the crash issue, I need to understand how to properly open a notification deep link. Any advice on what I need to change? I feel like I have followed the documentation precisely.

**Comment by phatmann** [comment]
@ajsmth

**Comment by satya164** [comment]
This is how you should handle deep links from notifications https://docs.expo.io/versions/latest/sdk/notifications/#handling-push-notifications-with-react-navigation
