### ISSUE TITLE
RN 6 Next - typescript error

### ISSUE THREAD

**Issue by francesco-clementi-92** [react-navigation/react-navigation#9718]
### Current behavior

```
node_modules/@react-navigation/bottom-tabs/lib/typescript/src/navigators/createBottomTabNavigator.d.ts:4:134 - error TS2339: Property 'lazy' does not exist
 on type 'Props'.
```

```
node_modules/@react-navigation/bottom-tabs/lib/typescript/src/navigators/createBottomTabNavigator.d.ts:4:140 - error TS2339: Property 'tabBarOptions' does
not exist on type 'Props'.
```

```
node_modules/@react-navigation/drawer/lib/typescript/src/navigators/createDrawerNavigator.d.ts:4:125 - error TS2339: Property 'lazy' does not exist on type
 'Props'.
```

```
node_modules/@react-navigation/drawer/lib/typescript/src/navigators/createDrawerNavigator.d.ts:4:131 - error TS2339: Property 'drawerContentOptions' does n
ot exist on type 'Props'.
```

### Expected behavior

No typescript error

### Reproduction

NA

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [X] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack

### Environment

"@react-navigation/bottom-tabs": "^6.0.0-next.20",
"@react-navigation/drawer": "^6.0.0-next.19",
"@react-navigation/material-top-tabs": "^6.0.0-next.16",
"@react-navigation/native": "^6.0.0-next.15",
"@react-navigation/stack": "^6.0.0-next.27",

**Comment by satya164** [comment]
https://reactnavigation.org/docs/6.x/upgrading-from-5.x/

**Comment by francesco-clementi-92** [comment]
@satya164 I started with v6, I didn't migrated from v5. 

The error is coming from node_modules, not my code.

**Comment by satya164** [comment]
Those APIs are not present in 6.x

**Comment by francesco-clementi-92** [comment]
You can check directly on the files, for example install "@react-navigation/drawer": "^6.0.0-next.19", go to @react-navigation/drawer/lib/typescript/src/navigators/createDrawerNavigator.d.ts e you will find the error prop.

**Comment by taylorkline** [comment]
@satya164 @francesco-clementi-92 I am experiencing this as well. I wonder if it has anything to do with the `// @ts-expect-error: lazy is deprecated` and `  // @ts-expect-error: tabBarOptions is deprecated
` https://github.com/react-navigation/react-navigation/blob/2084fb859ffa7c8ce2de859dba777a1227ff05c2/packages/bottom-tabs/src/navigators/createBottomTabNavigator.tsx#L37?

Perhaps these comments are being stripped out in `lib/typescript/src/navigators/createBottomTabNavigator.d.ts`?

**Comment by lucipacurar** [comment]
@taylorkline I'm having the same problem with the latest version. Pretty sure it's about those stripped comments. The workaround is to add `skipLibCheck: false` inside `tsconfig.json`
