### ISSUE TITLE
props.navigation.setOptions({ tabBarStyle: { display: 'none' } }); why doesn't it work?

### ISSUE THREAD

**Issue by plus24-library** [react-navigation/react-navigation#9720]
### Current behavior

why doesn't it work?

### Expected behavior

how to hide dynamically?

### Reproduction

https://snack.expo.io/

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | lattest
| @react-navigation/bottom-tabs          | lattest
| @react-navigation/drawer               | lattest
| @react-navigation/material-bottom-tabs | lattest
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                | lattest
| react-native-safe-area-context         | lattest
| react-native-screens                   | lattest
| react-native-gesture-handler           | lattest
| react-native-reanimated                | lattest
| react-native-tab-view                  | lattest
| react-native-pager-view                | lattest
| react-native                           | lattest
| expo                                   | lattest
| node                                   | lattest
| npm or yarn                            | lattest

**Comment by aurimassteponaitis** [comment]
I'm experiencing the same issue by using - createBottomTabNavigator from @react-navigation/bottom-tabs.
I'm trying to dynamically hide bottom tab bar from component I created and without manipulating route params during initial navigation setup/config. For example, I want to toggle bottom tab bar, by clicking a button - but is it even achievable?

Code snippet:
![image](https://user-images.githubusercontent.com/9442883/125040323-2ed48180-e0a0-11eb-93ce-0b5ef88c50e8.png)


dependencies:
"@react-navigation/bottom-tabs": "^6.0.0-next.20"
 "@react-navigation/native": "^6.0.0-next.15"

**Comment by plus24-library** [comment]
```js
export default function RootWithNavigationState() {
    const showBottomTabBar = useSelector(state => state.user.showBottomTabBar);
    const [ display, setDisplay ] = useState('flex');

    useEffect(() => {
        setDisplay(showBottomTabBar ? 'flex' : 'none');
    }, [showBottomTabBar]);



                            tabBarStyle: {
                                display,
                            },

    ```

temporary workaround

**Comment by sofianegargouri** [comment]
Here is what worked for me:
```
navigation.getParent()?.setOptions({
  tabBarStyle: { display: 'none' },
});
```

**Comment by efec89** [comment]
can't hide tabbar spesific screens on v6. tabbarStyle:{display:'none'} not works.

**Comment by gustaflindqvist** [comment]
> can't hide tabbar spesific screens on v6. tabbarStyle:{display:'none'} not works.

It's listed as solution with `tabBarStyle` for v6 here: https://reactnavigation.org/docs/upgrading-from-5.x/#the-tabbarvisible-option-is-no-longer-present

Shouldn't that work @efec89? Check this out: https://snack.expo.dev/@nazrdogan/hide-show-tab-bar

**Comment by hadnet** [comment]
I'm getting this weird behavior using v6. I'm setting a default backgroundColor in tabBarStyle Tab.Navigator screenOptions prop. But when using the setOptions function like navigation.setOptions({tabBarStyle: {display: 'flex'}}) in another component with the intent of hiding the tab bar, when the app starts the backgroundColor does not set to my backgroundColor and turns white! It's like navigation.setOptions doesn't merge with the default options and just overwrites all.

**Comment by cwnicoletti** [comment]
> Here is what worked for me:
> 
> ```
> navigation.getParent()?.setOptions({
>   tabBarStyle: { display: 'none' },
> });
> ```

Is it possible to animate something like this? I'd imagine you'd have to turn the bottom tab bar component into a custom Animated.View component, but even then I'm not sure if you could listen to this setOptions() call to know when to animate the bar away.

**Comment by a-eid** [comment]
> Here is what worked for me:
> 
> ```
> navigation.getParent()?.setOptions({
>   tabBarStyle: { display: 'none' },
> });
> ```

himm, I don't think this is a very good / scalable solution, let alone the jank it creates.

**Comment by osliver** [comment]
to be honest ```Since the the tab bar now supports a tabBarStyle option, we have removed the tabBarVisible option. You can achieve the same behavior by specifying tabBarStyle: { display: 'none' } in options.``` this is horrible decision, I have my own styles for tab bar, after set ```{ display: 'none' }``` on new screen, and on unmount I have to create my previous styles again, because im using theming and my styles depends on theme, it also have worse animation that it was with ```tabBarVisible: true / tabBarVisible: false```

**Comment by bearsworth** [comment]
> 

I tried this, but using a dark background I still see a white box during transitions. I can't seem to figure out how to first set a background dark before display none occurs.

**Comment by marcel-mintouge** [comment]
Hi, maybe this is off-topic. This works for me:

```
navigation.getParent()?.setOptions({
  tabBarStyle: { display: 'none' },
});
```
But now the tabBar remains hidden even when I leave the screen, is there any automatic way of restoring the style?

**Comment by lorchik7** [comment]
> Hi, maybe this is off-topic. This works for me:
> 
> ```
> navigation.getParent()?.setOptions({
>   tabBarStyle: { display: 'none' },
> });
> ```
> 
> But now the tabBar remains hidden even when I leave the screen, is there any automatic way of restoring the style?

Same issue for me. I have tried with `tabBarVisible: true / tabBarVisible: false` but doesn't work either.

**Comment by marcel-mintouge** [comment]
I ended reapplying the original style, quite ugly

**Comment by Iuriy-Budnikov** [comment]
Display none property works with bug in android.

**Comment by ViniTeider** [comment]
i have a bug where on IOS the bar doesnt hide, but on Android it works completely fine and i dont know what to do anymore.
I am using a Stack inside a Tab, and wanted to hide the tabBar on a specific Stack Screen.


```
    useEffect(() => {
        // Hides the bar
        navigation.getParent()?.setOptions({ tabBarStyle : { display: "none" } });
        
        // Shows the bar when getting to another screen
        return () => navigation.getParent()?.setOptions({ tabBarStyle: {
            backgroundColor: '#6458D7',
            borderTopEndRadius: 18,
            borderTopLeftRadius: 18,
        }});
    }, [navigation]);
```

i tried to do this and it fixes the problem on IOS, but then when i get to this screen, it returns to the previus one and theen if i click it again, i get to the screen with the tabBar hidden. does anyone know how can i solve this?

```
    useEffect(() => {
        // Hides the tabBar
        if (Platform.OS == "ios") enableScreens(false);
        navigation.getParent()?.setOptions({ tabBarStyle : { display: "none" } });
        
        // Shows the bar when getting to another screen
        return () => navigation.getParent()?.setOptions({ tabBarStyle: {
            backgroundColor: '#6458D7',
            borderTopEndRadius: 18,
            borderTopLeftRadius: 18,
        }});
    }, [navigation]);
```

**Comment by vibinjoby** [comment]
> return () => navigation.getParent()?.setOptions({ tabBarStyle: {
>             backgroundColor: '#6458D7',
>             borderTopEndRadius: 18,
>             borderTopLeftRadius: 18,
>         }});

you're missing a display:'flex' in 

```
return () => navigation.getParent()?.setOptions({ tabBarStyle: {
            display:'flex',
            backgroundColor: '#6458D7',
            borderTopEndRadius: 18,
            borderTopLeftRadius: 18,
        }});
```

**Comment by Rooffeell** [comment]
> can't hide tabbar spesific screens on v6. tabbarStyle:{display:'none'} not works.

it worked for me on android but not on iOS, I'm using expo router with expo go, I don't know if it hides it in dev build or preview, but it worked on android on the expo go sdk
