### ISSUE TITLE
Bug UI when navigate around on iOS 14.6 and prefer cross-fade Transitions enable (accessibility -> motion -> reduce motion enable, prefer cross-fade Transitions enable) 

### ISSUE THREAD

**Issue by viet97** [react-navigation/react-navigation#9721]
### Current behavior

On ios 14.6,  prefer cross-fade Transitions enable in setting, serious ui bug occurred when navigate between screens. See video:
https://drive.google.com/file/d/1DdTdZ5i5wLOYeJ-OxiO6LXjmDuhfWZGT/view?usp=sharing

This is a very serious UI BUG on ios 14.6. please check it as soon as posible. Thanks team!

### Expected behavior

navigate between screens smoothly without any bug UI.

### Reproduction

On ios 14.6, go to setting ->acessibility -> motion -> enable reduce motion -> enable prefer cross-fade Transitions, when navigate to another screen and go back, the UI become buggy and sometime screen just show a blank white space.
### Platform

- [X] iOS

### Packages

- [X] @react-navigation/bottom-tabs
- [X] @react-navigation/stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |5.9.4
| @react-navigation/bottom-tabs          |5.11.11
| @react-navigation/stack                |5.14.5

**Comment by nkhanhng** [comment]
I'm facing this issue in 14.6 too, please help

**Comment by sonseven5997** [comment]
Im facing this issue in 14.6 too please help ….

**Comment by lukeharvey** [comment]
Looks like this could be an issue with React Native and not with React Navigation, see here https://github.com/facebook/react-native/issues/29974 a possible workaround is provided in that thread

**Comment by viet97** [comment]
> Looks like this could be an issue with React Native and not with React Navigation, see here [facebook/react-native#29974](https://github.com/facebook/react-native/issues/29974) a possible workaround is provided in that thread

thanks man

**Comment by gaupoit** [comment]
Count me in. Please help to resolve it. Cheers.

**Comment by viet97** [comment]
Turned out it was a KeyboardAvoidingView bug. Close this issue as lukeharvey've gave a solution.
