### ISSUE TITLE
CompositeNavigationProp complains about 1st argument

### ISSUE THREAD

**Issue by Man-RP** [react-navigation/react-navigation#9724]
### Current behavior

Hello,
I have a root Material Tab navigator which contains a Stack navigator each tab.
Im trying to add a type checking.

I followed the instructions which described on [this](https://reactnavigation.org/docs/typescript/#nesting-navigators) guide.

I defined my root navigator's (Tab) params list types:

```
type RootParamList = {
  main: NavigatorScreenParams<MainScreenParamsList>;
  schedule: NavigatorScreenParams<ScheduleParamsList>;
  stats: undefined;
  participants: undefined;
};

const Tab = createMaterialBottomTabNavigator<RootParamList>();
```

and my MainScreen navigator's (Stack) params list: 

```
export type MainScreenParamsList = {
  week: undefined;
  dataAnalyze: undefined;
  dataEntry: { events: IEvent };
};

const Stack = createStackNavigator<MainScreenParamsList>();
```

but when Im trying to get the combined WeekScreen's 'navigation' prop type (using 'CompositeNavigationProp'):

```
type WeekScreenNavigationProp = CompositeNavigationProp<
  StackNavigationProp<MainScreenParamsList, "main">,
  MaterialBottomTabNavigationProp<RootParamList>
>;
```

typescript shouts about my first argument (stack navigator's navigation prop ) type:

> Type 'StackNavigationProp<MainScreenParamsList, "week">' does not satisfy the constraint 'NavigationProp<ParamListBase, string, any, any, {}>'.
>   Type 'NavigationScreenProp<MainScreenParamsList, "week"> & { push: (routeName: string, params?: NavigationParams, action?: NavigationNavigateAction) => boolean; ... 4 more ...; addListener: (event: NavigationStackEventName, callback: NavigationEventCallback) => NavigationEventSubscription; }' is missing the following properties from type '{ dispatch(action: Readonly<{ type: string; payload?: object; source?: string; target?: string; }> | ((state: any) => Readonly<{ type: string; payload?: object; source?: string; target?: string; }>)): void; ... 6 more ...; dangerouslyGetState(): any; }': canGoBack, dangerouslyGetStatets(2344)

### Expected behavior

work without issues.

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [X] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 5.9.4
| @react-navigation/bottom-tabs          |
| @react-navigation/drawer               |
| @react-navigation/material-bottom-tabs | 5.3.15
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                | 5.14.5
| react-native-safe-area-context         |
| react-native-screens                   |
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           |
| expo                                   |
| node                                   |
| npm or yarn                            |

**Comment by SebastianMieszczanczyk** [comment]
@Man-RP 

[Docs Nested navigators](https://reactnavigation.org/docs/typescript#combining-navigation-props)
> The CompositeNavigationProp type takes 2 parameters, first parameter is the primary navigation type (type for the navigator that owns this screen, in our case the tab navigator which contains the Profile screen) and second parameter is the secondary navigation type (type for a parent navigator). The primary navigation type should always have the screen's route name as it's second parameter.

and also few lines before:
[Docs Type checking screens](https://reactnavigation.org/docs/typescript#type-checking-screens)
> The type for the navigation prop takes 2 generics, the param list object we defined earlier, and the name of the current route. This allows us to type check route names and params which you're navigating using navigate, push etc.

So having these 2 things in mind, IMHO you should have:

`
type WeekScreenNavigationProp = CompositeNavigationProp<
  StackNavigationProp<MainScreenParamsList, "week">,
  MaterialBottomTabNavigationProp<RootParamList>
>;
`

**Comment by johhansantana** [comment]
> @Man-RP
> 
> [Docs Nested navigators](https://reactnavigation.org/docs/typescript#combining-navigation-props)
> 
> > The CompositeNavigationProp type takes 2 parameters, first parameter is the primary navigation type (type for the navigator that owns this screen, in our case the tab navigator which contains the Profile screen) and second parameter is the secondary navigation type (type for a parent navigator). The primary navigation type should always have the screen's route name as it's second parameter.
> 
> and also few lines before:
> [Docs Type checking screens](https://reactnavigation.org/docs/typescript#type-checking-screens)
> 
> > The type for the navigation prop takes 2 generics, the param list object we defined earlier, and the name of the current route. This allows us to type check route names and params which you're navigating using navigate, push etc.
> 
> So having these 2 things in mind, IMHO you should have:
> 
> ```
> type WeekScreenNavigationProp = CompositeNavigationProp<
>   StackNavigationProp<MainScreenParamsList, "week">,
>   MaterialBottomTabNavigationProp<RootParamList>
> >;
> ```

Isn't https://reactnavigation.org/docs/typescript/#type-checking-screens outdated? The library that it's being used there is:
```
@react-navigation/stack
```

instead of 

```
@react-navigation/native-stack
```

And there's no `StackNavigationProp` on the `@react-navigation/native-stack` one. Using `NativeStackNavigationProp` gives me an error if I don't include the `params: undefined`
