### ISSUE TITLE
getInitialUrl doesnt use provided url for deep linking

### ISSUE THREAD

**Issue by Ibcs16** [react-navigation/react-navigation#9725]
### Current behavior

Im using the following deeplinking config:
```
const deepLinksConf = {
  screens: {
    ...
    Invitation: "invitations",
    ...
  },
};
```

And in my getInitialUrl method im calling a function that gets a url from a notification tap when app is closed:
```
 let initialUrl = await Linking.getInitialURL();
 let initialUrlType = "initialUrl";

const urlFromNotificationResponse = await getUrlFromNotificationResponse();
if (urlFromNotificationResponse) {
  initialUrl = urlFromNotificationResponse;
  initialUrlType = "notificationUrl";
}

return initialUrl
```
And in my component
```
 <SafeAreaProvider>
   <NavigationContainer linking={linking} fallback={<AuthLoading />}>
              <Routes /> 
     </NavigationContainer>
```

The thing is, my function works fine for getting the notification url like:
`milhaspaybr://invitations?sourceType=DEEPLINK&NAME=example`

But even though Im returning it for getInititalUrl functions, it just doesnt open the right screen `/invitations`

### Expected behavior

Should open provided url in getInitialUrl

### Reproduction

https://snack.expo.io/@iagobrayham/react-navigation-test

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 5.9.3
| @react-navigation/bottom-tabs          | 5.11.8
| @react-navigation/stack                | 5.14.3
| react-native-safe-area-context         | 3.2.0
| react-native-screens                   | 3.0.0
| react-native-gesture-handler           | 1.10.2
| react-native-reanimated                | 2.1.0
| react-native                           | 41.0.0
| expo                                   | 41.0.0
| node                                   | 12
| npm or yarn                            | yarn

**Comment by gokul1630** [comment]
It's 2024, I'm still facing the same issue :(
