### ISSUE TITLE
jest: `You are trying to `import` a file after the Jest environment has been torn down.`

### ISSUE THREAD

**Issue by andreialecu** [react-navigation/react-navigation#9727]
### Current behavior

I created a `MockedNavigator`, using this code:

```tsx
import {NavigationContainer} from '@react-navigation/native';
import {createStackNavigator} from '@react-navigation/stack';
import React from 'react';

const Stack = createStackNavigator();
export const MockedNavigator: React.FC<React.ComponentProps<
  typeof Stack['Screen']
>> = ({...screenProps}) => {
  return (
    <NavigationContainer>
      <Stack.Navigator>
        <Stack.Screen {...screenProps} />
      </Stack.Navigator>
    </NavigationContainer>
  );
};
```

Which is used in tests via react native testing library like this:

```tsx
 test('renders login variant correctly', () => {
    const component = render(
      <MockedNavigator name="MockedScreen">
        {() => <EmailAndPasswordEntry type="login" />}
      </MockedNavigator>,
    );

    expect(component.getByText('Log in')).toBeTruthy();
 });
```

The test passes correctly, however jest logs this after every test where `MockedNavigator` is being used:

```
ReferenceError: You are trying to `import` a file after the Jest environment has been torn down.

      at Object.get Linking [as Linking] (node_modules/react-native/index.js:241:12)
      at node_modules/@react-navigation/native/lib/commonjs/useLinking.native.tsx:121:15
      at Object.invokeGuardedCallbackProd (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11308:10)
      at invokeGuardedCallback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11499:31)
      at flushPassiveEffectsImpl (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14560:11)
```

### Expected behavior

Should not log jest warning. I have attached a simple repro.

### Reproduction

https://github.com/andreialecu/rnavigation-jest-repro

### Platform

- [ ] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 5.9.4
| jest                                   | 26.6.3

**Comment by ajsmth** [comment]
A workaround for this is to call `jest.useFakeTimers()` at the top of your test file or in your `jest.setup.js` file. I don't have an exact reason why but its pointing to this module: 

<img width="864" alt="Screen Shot 2021-07-09 at 3 04 41 PM" src="https://user-images.githubusercontent.com/40680668/125140285-01e79500-e0c7-11eb-8af5-83bb29e6c654.png">


there might be a timeout somewhere in there? not too sure but that is where I would start if you wanted to properly fix the issue

**Comment by andreialecu** [comment]
I concur that `jest.useFakeTimers()` is *NOT* a solution. That completely breaks other things.

Not sure why this was closed, especially considering there's a repro attached.

**Comment by andreialecu** [comment]
Suddenly started getting complete jest test failures due to this error, breaking CI builds.

It seems that this mock helps:

```ts
jest.mock('@react-navigation/native/lib/commonjs/useLinking.native', () => ({
  default: () => ({getInitialState: {then: jest.fn()}}),
  __esModule: true,
}));
```

Courtesy of @jehartzog from: 
https://github.com/react-navigation/react-navigation/issues/9568#issuecomment-881943770

**Comment by renanmav** [comment]
@ajsmth could we reopen this one?

**Comment by khetanir** [comment]
If anyone is still looking for the fix, it looks like the cause of this problem for me was with **react-native-screens**. I was on version 3.4, upgraded to 3.10.1 and the issue was resolved - not entirely sure which change fixed the issue, there were a bunch of fixes in between the releases

**Comment by cam-shaw** [comment]
@khetanir did you also have the latest `react-navigation` packages? 🤔

**Comment by bwhite94** [comment]
FWIW I [found a recommendation](https://stackoverflow.com/a/67216156/2748747) to add the following to your Jest configuration. Interestingly, this resolves issues without the need for fakeTimers or any setup scripts added.
```
testEnvironment: 'jsdom',
```

I'm not sure if it makes a difference but I'm using React Native in an Expo project configuration as well.

**Comment by VVNTHEFLASH** [comment]
> FWIW I [found a recommendation](https://stackoverflow.com/a/67216156/2748747) to add the following to your Jest configuration. Interestingly, this resolves issues without the need for fakeTimers or any setup scripts added.
> 
> ```
> testEnvironment: 'jsdom',
> ```
> 
> I'm not sure if it makes a difference but I'm using React Native in an Expo project configuration as well.

Thanks only this solution worked for me
