### ISSUE TITLE
React-Navigation on reload page is not getting loaded with error 'Cannot GET /Home'

### ISSUE THREAD

**Issue by fahmiabdulyakub** [react-navigation/react-navigation#9729]
### Current behavior

On first load my page is loading fine when I run app or I directly put url as localhost:8080 in navigates me to initial route localhost:8080/Home but as soon as I reload page or it auto reload page can be reloaded with specific defined URL such as localhost:8080/Home or localhost:8080/Settings and fails with error Cannot GET /Home.

### Expected behavior

I am using react-native-web with RN. Following is code for navigation file:

`
import 'react-native-gesture-handler';
import * as React from 'react';
import {NavigationContainer} from '@react-navigation/native';
import {createStackNavigator} from '@react-navigation/stack';
import Home from './src/scence/Home/home';
import Settings from './src/scence/Settings/settings';

const Stack = createStackNavigator();

const linking = {
  prefixes: ['https://localhost:8080'],
  config: {
    screens: {
      Root: {
        path: '/',
        initialRouteName: '/',
        screens: {
          Home: '/',
          Settings: '/settings',
        },
      },
    },
  },
};
const Router = () => {
  return (
    <NavigationContainer linking={linking}>
      <Stack.Navigator
        screenOptions={{
          headerShown: false,
        }}>
        <Stack.Screen name="Home" component={Home} />
        <Stack.Screen name="Settings" component={Settings} />
      </Stack.Navigator>
    </NavigationContainer>
  );
};

export default Router;

`

### Reproduction

1234

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |
| @react-navigation/bottom-tabs          |
| @react-navigation/drawer               |
| @react-navigation/material-bottom-tabs |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                |
| react-native-safe-area-context         |
| react-native-screens                   |
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           |
| expo                                   |
| node                                   |
| npm or yarn                            |

**Comment by gciluffo** [comment]
@fahmiabdulyakub Im also running into this issue. Were you able to figure it out?

**Comment by mukul98s** [comment]
@gciluffo Can you please share the config file? I never tried webpack config before and it is  not working for me. 
It would great if you can share the file. 
Thanks
