### ISSUE TITLE
DrawerItem not showing when using it inside a .map() function

### ISSUE THREAD

**Issue by wassimAJ1** [react-navigation/react-navigation#9731]
### Current behavior

"item 1" and "item 2" not showing in the drawer navigator.

![simulator_screenshot_BC9B09B8-6601-4A56-97FC-7C68C8C0863A](https://user-images.githubusercontent.com/78846112/125039424-23cd2180-e09f-11eb-93c9-8cc70b5131ec.png)

......

const CustomDrawerContent=(props)=> {

    const arr =[
      {title:'item 1', id:1},
      {title:'item 2', id:2}
    ];
    return (
      <DrawerContentScrollView {...props}>
        <DrawerItemList {...props} />
        {arr.map(item => {
            {console.log(item)}
            <DrawerItem
            labelStyle={{color: 'white',
            fontSize: 20,
            }}
              style={{borderBottomWidth: 1, borderColor: 'white'}}
              key={item.id}
              label={item.title}
              onPress={()=>console.log("pressed item", item)}
            />
        })}  
      </DrawerContentScrollView>
    );
  }

......

<Drawer.Navigator

          initialRouteName="Home"
          drawerPosition="right"
          drawerStyle={{backgroundColor: 'blue'}}
          drawerContentOptions={{
            labelStyle: {
              color: 'white',
              fontSize: 20,
              fontFamily: font,
              alignSelf: 'flex-end',
            },
          }}
          drawerContent={props => <CustomDrawerContent {...props} />}
          >
          <Drawer.Screen key="xd450" name="Home" component={RestScreens} />
          <Drawer.Screen
            key="xd453"
            name="title 1"
            component={MostCommun}
          />
          <Drawer.Screen
            key="xd451"
            name="albums"
            component={AllAlbums}
            options={{title:'title 2'}}
          />
          <Drawer.Screen
            key="xd452"
            name="videos"
            component={AllVideos}
            options={{title: 'title 3'}}
          />
        </Drawer.Navigator>

### Expected behavior

Drawer navigator should have "title 1, title 3, title 3, item 1, item2".

### Reproduction

https://snack.expo.io/Nzr1PXFDv

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native            | ^5.9.4  
| @react-navigation/drawer               | ^5.12.5
| @react-navigation/bottom-tabs    | ^5.11.11
| @react-navigation/material-bottom-tabs   | ^5.3.15
| @react-navigation/material-top-tabs | ^5.3.15
| @react-navigation/stack   |^5.14.5
| react-native                           | ^0.63.4
| node                                   | ^15.11.0
| npm                           | ^7.6.0

**Comment by wassimAJ1** [comment]
The issue still exists.

**Comment by michelazzam** [comment]
In <DrawerItemList /> try to add a return statement for the component inside the .map

**Comment by wassimAJ1** [comment]
> In try to add a return statement for the component inside the .map

It worked.
