### ISSUE TITLE
FlatList does not maintain scroll position

### ISSUE THREAD

**Issue by sharan-SKY** [react-navigation/react-navigation#9733]
### Current behavior

I have a StackNavigator with two screens A and B
screen A has a FlatList with around 1000 items which are loaded based on scrolling of the user with onEndReached method,
Now when user clicks on any item in the flatlist, he goes to screen B which detail screen of that clicked item.
Now if user goes back to screen A, then the flat list again starts showing from first item so the scroll position is not maintained.

### Expected behavior

Flatlist should retain the scroll position.

### Reproduction

Corporate repo so cannot be linked here. 

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |
| @react-navigation/bottom-tabs          |
| @react-navigation/drawer               |
| @react-navigation/material-bottom-tabs |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                |
| react-native-safe-area-context         |
| react-native-screens                   |
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           |
| expo                                   |
| node                                   |
| npm or yarn                            |

**Comment by jp928** [comment]
Same here.

**Comment by sreuter** [comment]
The current behaviour actually is that the scroll position is being remembered when you switch between screens. It **does** reset though when you switch from a screen that has `headerTransparent` set to a different setting than the state you navigate there from. Took me a while to figure this out, hope it helps some folks out there!

**Comment by sandy105** [comment]
I used the detachInactiveScreens={false}  and it did not work for me, but I set detachPreviousScreen={false}, it works!!! so strange!!

**Comment by hufftheweevil** [comment]
I'm having the same issue but neither `detachInactiveScreens={false}` nor `detachPreviousScreen: false` works for me. Anyone else still having trouble with this?

**Comment by ahmetcangurel** [comment]
same issue

**Comment by nawfalhaddi** [comment]
Hello, I had the same issue, I solved it by disabling the detachment of my screen.
in order to do that make sure the next screen you navigate to, has this property in its navigation options:  
`detachPreviousScreen: false`

Example:

```
  useLayoutEffect(() => {
    navigation.setOptions({
       detachPreviousScreen: false
    });
  }, [navigation]);
```

**Comment by Alex69222** [comment]
> Hello, I had the same issue, I solved it by disabling the detachment of my screen. in order to do that make sure the next screen you navigate to, has this property in its navigation options: `detachPreviousScreen: false`
> 
> Example:
> 
> ```
>   useLayoutEffect(() => {
>     navigation.setOptions({
>        detachPreviousScreen: false
>     });
>   }, [navigation]);
> ```

This helped me. Thank you!
