### ISSUE TITLE
The action 'NAVIGATE' with payload {"name";"About"} was not handled by any navigator.

### ISSUE THREAD

**Issue by M2Changezi** [react-navigation/react-navigation#9734]
### Current behavior

It gives error `The action 'NAVIGATE' with payload {"name";"About"} was not handled by any navigator.`in the development server in emulator but here it gives nothing and don't navigate to About screen

### Expected behavior

It should navigate

### Reproduction

https://snack.expo.io/@m2c/ed283c

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
"@react-navigation/drawer": "^5.12.5",
    "@react-navigation/native": "^5.9.4",
    "@react-navigation/stack": "^5.14.5",
 "react-native-screens": "~3.0.0",
    "react-native-svg": "12.1.0",
    "react-native-unimodules": "~0.13.3",
    "react-native-web": "^0.16.5",
    "react-navigation": "^4.4.4",
    "react-navigation-drawer": "^2.7.1",
    "react-navigation-stack": "^2.10.4",

**Comment by satya164** [comment]
You don't have a screen named "About" in the repro you posted. There are only 2 screens, "Article" and "Feed"
