### ISSUE TITLE
Webview loses state on navigation

### ISSUE THREAD

**Issue by kpetrow** [react-navigation/react-navigation#9736]
### Current behavior

When i go back to a screen that contains a webview it is reset to original state and loses all injected javascript.

Found similar issue here:
https://github.com/react-navigation/react-navigation.github.io/issues/808
and:
https://stackoverflow.com/questions/41818857/keep-react-native-webview-mounted

### Expected behavior

Have some method of keeping stack state when out of focus

### Reproduction

https://stackoverflow.com/questions/41818857/keep-react-native-webview-mounted

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack

### Environment

"@react-native-community/masked-view": "^0.1.11",
    "@react-navigation/bottom-tabs": "^5.11.11",
    "@react-navigation/drawer": "^5.12.5",
    "@react-navigation/material-bottom-tabs": "^5.3.15",
    "@react-navigation/material-top-tabs": "^5.3.15",
    "@react-navigation/native": "^5.9.4",
    "@react-navigation/stack": "^5.14.4",

**Comment by linxianxi** [comment]
same.

**Comment by Brma1048** [comment]
@kpetrow @linxianxi do you found any solution?
