### ISSUE TITLE
getting error :- Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.

### ISSUE THREAD

**Issue by KumariShalini** [react-navigation/react-navigation#9740]
### Current behavior

When i navigate to tab item page, then back and go to drawer item, and again go to tab item , getting error. Not properly working nested navigation , getting error:-

Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.

### Expected behavior

How to cancel all subscriptions and asynchronous tasks in a useEffect cleanup function. Thank you.

### Reproduction

i have no repo now

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | ^5.9.4
| @react-navigation/bottom-tabs          |  ^5.11.11
| @react-navigation/drawer               | ^5.12.5
| @react-navigation/material-bottom-tabs |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                | ^5.14.5
| react-native-safe-area-context         |
| react-native-screens                   |
| react-native-gesture-handler           |
| react-native-reanimated                | ^2.1.0
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           | 0.64.1
| expo                                   |
| node                                   |
| npm or yarn                            | npm

**Comment by raajnadar** [comment]
Read this https://reactjs.org/docs/hooks-effect.html#effects-with-cleanup
