### ISSUE TITLE
V6 - navigation.navigate('MyRoute') emits TS2345 error

### ISSUE THREAD

**Issue by vahdet** [react-navigation/react-navigation#9741]
### Current behavior

After migrating from React Navigation V5 to **V6**. using `navigation.navigate` like:

```
const navigation = useNavigation()
navigation.navigate('MyRoute')
```

emits TS error:

```
Argument of type 'string' is not assignable to parameter of type '{ key: string; params?: undefined; } | { name: never; key?: string | undefined; params: never; }'.
  Type 'string' is not assignable to type '{ key: string; params?: undefined; } | { name: never; key?: string | undefined; params: never; }'. ts(2345)
```

However, `navigation.navigate({ key: 'MyRoute' })` is legal.

### Expected behavior

`navigation.navigate` should accept a single string as an argument (as it is in V5)

### Reproduction

https://github.com/gimmickless/iyiye-native-app/blob/ca80f3c997632a23af060363fee5ba5693fc0d46/src/screens/auth/ConfirmAccount.tsx#L41

`.tsx` files were not allowed on Expo Snack, so I shared a link to my project with an exact line. Cloning the project and running `npm i`, an editor showing the TS Errors (like VSCode) should reproduce the error.

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | ^6.0.0-next.15 |
| @react-navigation/bottom-tabs          | ^6.0.0-next.20 |
| @react-navigation/stack                | ^6.0.0-next.27 |
| react-native-safe-area-context         | 3.2.0 |
| react-native-screens                   | ~3.4.0 |
| react-native-gesture-handler           | ~1.10.2 |
| react-native-reanimated                | ~2.2.0 |
| react-native-pager-view                | 5.0.12 |
| react-native                           | https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz |
| expo                                   | ^42.0.0 |
| node                                   | 14.17.0 |
| npm                            | 6.14.13 |

**Comment by satya164** [comment]
You need to annotate `useNavigation` or specify a default type https://reactnavigation.org/docs/6.x/typescript#specifying-default-types-for-usenavigation-link-ref-etc

**Comment by vahdet** [comment]
@satya164 I don't think it addresses this issue. V5 has the same [doc](https://reactnavigation.org/docs/typescript/#annotating-usenavigation) for TypeScript and `useNavigation` , but it works fine in V5. Also, this does not explain why `navigation.navigate({ key: 'MyRoute' })` does not throw an error without an annotation on `useNavigation`

**Comment by satya164** [comment]
> but it works fine in V5

You can pass incorrect names and it won't give any error in v5, that's not correct behavior. If you don't want type-checking for your screen names, then you can ignore the error with `// @ts-ignore`

> why navigation.navigate({ key: 'MyRoute' }) does not throw an error

Because keys are randomly generated IDs, it's impossible statically typecheck a key.

**Comment by shensven** [comment]
> You need to annotate `useNavigation` or specify a default type https://reactnavigation.org/docs/6.x/typescript#specifying-default-types-for-usenavigation-link-ref-etc

Page Not Found

**Comment by satya164** [comment]
@shensven https://reactnavigation.org/docs/typescript/#specifying-default-types-for-usenavigation-link-ref-etc

**Comment by acro5piano** [comment]
I've fixed it by adding `<any>` https://reactnavigation.org/docs/use-navigation

```tsx
  const navi = useNavigation<any>();
```

**Comment by RemyMachado** [comment]
I feel like the navigation typing is way too complicated.
I just want to limit the `navigate` usage to my route enumeration.

Something like
```typescript
export enum ROUTES {
  HOME = 'HOME',
  TEST = 'TEST',
}


const navigation = useNavigation<ROUTES>()
```
would be nice.

**Comment by HoraceDiesel** [comment]
I solved it by annotate the useNavigation like this:
```

interface Props extends ScreenNavigationProp {

}

const Layout: React.FC<Props> = () => {
  const navigation = useNavigation<ScreenNavigationProp['navigation']>()

  // then you can do navigation.navigate(SCREEN_NAME_ENUM.screenName)

}
```

**Comment by kbwo** [comment]
I solved it by upgrading typescript.
Typescript version in react-native-template-typescript is `^3.8.3`.
I changed it to `^4.3.2`.

**Comment by acro5piano** [comment]
Hi all,

@satya164 is correct, and let me explain the details.

# Solution

You don't have to use generics like `useNavigation<SomeType>()`. 
Instead, **extend the global type defined on the library** and type is automagically checked anywhere in the project.

Example:

```
export type AppRootParamList = {
  home: undefined;
  profile: undefined;
  post: { postId: string };
};

// This registers which makes navigation fully type-safe.
// https://reactnavigation.org/docs/typescript#specifying-default-types-for-usenavigation-link-ref-etc
declare global {
  namespace ReactNavigation {
    interface RootParamList extends AppRootParamList {}
  }
}
```

# How it is checked

In the above example,

```
  const navi = useNavigation()

  // Correct
  navi.navigate('home')

  // Correct with parameter type
  navi.navigate('post', { postId: 'foo' })

  // Incorrect, and TS emits errors
  navi.navigate('__no_exists_route__')

  // Incorrect, and TS emits errors
  navi.navigate('post')
```

Completion also works well here.

![image](https://user-images.githubusercontent.com/10719495/139625769-b38961cd-5ee5-4f04-b341-61e7ce37fa15.png)

![image](https://user-images.githubusercontent.com/10719495/139626193-ad244d4a-ebca-4db6-af60-3f6c35754b80.png)

![image](https://user-images.githubusercontent.com/10719495/139626215-18498664-e6b6-4f96-b0cb-6b3380eff809.png)


Note that it is written in the document clearly **on the bottom** of the page.

https://reactnavigation.org/docs/typescript#specifying-default-types-for-usenavigation-link-ref-etc

**Comment by mikehardy** [comment]
@acro5piano your explanation in combo with the docs fixed me right up. Much appreciated.

**Comment by ambegossi** [comment]
@acro5piano Thanks for the detailed explanation. Do you have any suggestion on where to put the global declaration snippet?

**Comment by felipemillhouse** [comment]
In my case, I have nested screens and types doesn't work well with useNavigation xor linking config, maybe I'm doing something wrong

```typescript
export type RootStackParamList = {
  Auth: {
    Login: undefined
    CreateAccount: undefined
    ForgotPassword: undefined
  }
  Tabs: {
    FeedTab: {
      Feed: undefined
      Comment: { postId: number }
      CreatePost: {
        photo: {
          uri: string
          width: number
          height: number
        }
      }
      TankDetail: {
        tank?: TankState
        tankId: number
      }
      Profile: undefined
      PostDetail: {
        postId?: number
        commentId?: number
      }
    }
    TankTab: {
      Tank: {
        refresh: string
      }
      AddEditTank: {
        tank?: TankState
        fertilizers?: {
          id: number
          name: string
          dose: string
          avatar: string | null
        }
        plants?: {
          id: number
          name: string
          avatar: string | null
        }
      }
      TankDetail: {
        tank?: TankState
        tankId: number
      }
      FertilizerList: undefined
      PlantList: undefined
      Profile: undefined
      PostDetail: {
        postId?: number
        commentId?: number
      }
    }
  }
}
```
and then
```typescript
declare global {
  namespace ReactNavigation {
    interface RootParamList extends RootStackParamList {}
  }
}
```
on linking config I have
```jsx
<NavigationContainer
          linking={{
            ...linking,
            config: {
              screens: {
                Tabs: {
                  screens: {
                    FeedTab: {
                      screens: {
                        PostDetail: {
                          path: 'likePostComment/:postId/:commentId?',
                          parse: {
                            postId: Number,
                            commentId: Number,
                          },
                          exact: true,
                        },
                      },
                    },
                  },
                },
              },
            },
          }}
        >
```
at this point the ts error is:
```
Type '{ screens: { FeedTab: { screens: { PostDetail: { path: string; parse: { postId: NumberConstructor; commentId: NumberConstructor; }; exact: true; }; }; }; }; }' is not assignable to type 'string | Omit<PathConfig<{}>, "screens" | "initialRouteName"> | undefined'.
  Object literal may only specify known properties, and 'screens' does not exist in type 'Omit<PathConfig<{}>, "screens" | "initialRouteName">'.ts(2322)
main.tsx(124, 17): The expected type comes from property 'Tabs' which is declared here on type 'PathConfigMap<{ Tabs: unknown; }>'
```
and for useNavigation I have
```jsx
<Drawer.Item
  label="Profile"
  icon="account"
  onPress={() => hide(() => navigation.navigate('Profile'))}
/>
```
and the error is
```
Argument of type 'string' is not assignable to parameter of type '{ key: string; params?: { Login: undefined; CreateAccount: undefined; ForgotPassword: undefined; } | { FeedTab: { Feed: undefined; Comment: { postId: number; }; CreatePost: { photo: { uri: string; width: number; height: number; }; }; TankDetail: { ...; }; Profile: undefined; PostDetail: { ...; }; }; TankTab: { ...; ...'.
```

**Comment by acro5piano** [comment]
@felipemillhouse I think you should define your nested route as a flat one, like this:

```ts
export type RootStackParamList = {
  Auth: undefined
  Login: undefined
  CreateAccount: undefined
  ForgotPassword: undefined
  Tabs: undefined
  FeedTab: undefined
  Feed: undefined

  // ... and so on
}

declare global {
  namespace ReactNavigation {
    interface RootParamList extends RootStackParamList {}
  }
}
```

**Comment by felipemillhouse** [comment]
Thanks @acro5piano, it fixes useNavigation but doesn't fix linking, it would be nice to remove that ts error in my project, but I'll survive with it. Here is my complete type file.
I also followed that instruction for nested navigators: https://reactnavigation.org/docs/typescript#nesting-navigators
and for Combining navigation props: https://reactnavigation.org/docs/typescript#combining-navigation-props

```typescript
import { NativeStackScreenProps } from '@react-navigation/native-stack'
import { BottomTabScreenProps } from '@react-navigation/bottom-tabs'
import {
  NavigatorScreenParams,
  CompositeScreenProps,
} from '@react-navigation/native'

import { TankState } from '../store/tank/types'

export type RootStackParamList = ParamListMainStack &
  ParamListAuthStack &
  ParamListFeedStack &
  ParamListTankStack &
  ParamListTabStack

export type ParamListMainStack = {
  Auth: NavigatorScreenParams<ParamListAuthStack>
  Tabs: NavigatorScreenParams<ParamListTabStack>
}
export type ParamListTabStack = {
  FeedTab: NavigatorScreenParams<ParamListFeedStack>
  TankTab: NavigatorScreenParams<ParamListTankStack>
}
export type ParamListGeneralStack = {
  Profile: undefined
  PostDetail: {
    postId?: number
    commentId?: number
  }
}
export type ParamListAuthStack = {
  Login: undefined
  CreateAccount: undefined
  ForgotPassword: undefined
}
export type ParamListFeedStack = ParamListGeneralStack & {
  Feed: undefined
  Comment: { postId: number }
  CreatePost: {
    photo: {
      uri: string
      width: number
      height: number
    }
  }
  TankDetail: {
    tank?: TankState
    tankId: number
  }
}
export type ParamListTankStack = ParamListGeneralStack & {
  Tank: {
    refresh: string
  }
  AddEditTank: {
    tank?: TankState
    fertilizers?: {
      id: number
      name: string
      dose: string
      avatar: string | null
    }
    plants?: {
      id: number
      name: string
      avatar: string | null
    }
  }
  TankDetail: {
    tank?: TankState
    tankId: number
  }
  FertilizerList: undefined
  PlantList: undefined
}
// Root ************************************************************************
export type NavPropsAuth = NativeStackScreenProps<ParamListMainStack, 'Auth'>
export type NavPropsTabs = NativeStackScreenProps<ParamListMainStack, 'Tabs'>
// Auth ************************************************************************
export type NavPropsLogin = CompositeScreenProps<
  NativeStackScreenProps<ParamListAuthStack, 'Login'>,
  NativeStackScreenProps<ParamListMainStack>
>
export type NavPropsCreateAccount = CompositeScreenProps<
  NativeStackScreenProps<ParamListAuthStack, 'CreateAccount'>,
  NativeStackScreenProps<ParamListMainStack>
>
export type NavPropsForgotPassword = CompositeScreenProps<
  NativeStackScreenProps<ParamListAuthStack, 'ForgotPassword'>,
  NativeStackScreenProps<ParamListMainStack>
>
// Tabs ************************************************************************
export type NavPropsFeedTab = CompositeScreenProps<
  BottomTabScreenProps<ParamListTabStack, 'FeedTab'>,
  NativeStackScreenProps<ParamListMainStack>
>
export type NavPropsTankTab = CompositeScreenProps<
  BottomTabScreenProps<ParamListTabStack, 'TankTab'>,
  NativeStackScreenProps<ParamListMainStack>
>
// Feed Tab ********************************************************************
export type NavPropsFeed = CompositeScreenProps<
  NativeStackScreenProps<ParamListFeedStack, 'Feed'>,
  CompositeScreenProps<
    BottomTabScreenProps<ParamListTabStack, 'FeedTab'>,
    NativeStackScreenProps<ParamListMainStack>
  >
>
export type NavPropsCreatePost = CompositeScreenProps<
  NativeStackScreenProps<ParamListFeedStack, 'CreatePost'>,
  CompositeScreenProps<
    BottomTabScreenProps<ParamListTabStack, 'FeedTab'>,
    NativeStackScreenProps<ParamListMainStack>
  >
>
export type NavPropsComment = CompositeScreenProps<
  NativeStackScreenProps<ParamListFeedStack, 'Comment'>,
  CompositeScreenProps<
    BottomTabScreenProps<ParamListTabStack, 'FeedTab'>,
    NativeStackScreenProps<ParamListMainStack>
  >
>
export type NavPropsTankDetail = CompositeScreenProps<
  NativeStackScreenProps<ParamListFeedStack, 'TankDetail'>,
  CompositeScreenProps<
    BottomTabScreenProps<ParamListTabStack, 'FeedTab'>,
    NativeStackScreenProps<ParamListMainStack>
  >
>
// Tank Tab ********************************************************************
export type NavPropsTank = CompositeScreenProps<
  NativeStackScreenProps<ParamListTankStack, 'Tank'>,
  CompositeScreenProps<
    BottomTabScreenProps<ParamListTabStack, 'TankTab'>,
    NativeStackScreenProps<ParamListMainStack>
  >
>
export type NavPropsAddEditTank = CompositeScreenProps<
  NativeStackScreenProps<ParamListTankStack, 'AddEditTank'>,
  CompositeScreenProps<
    BottomTabScreenProps<ParamListTabStack, 'TankTab'>,
    NativeStackScreenProps<ParamListMainStack>
  >
>
export type NavPropsFertilizerList = CompositeScreenProps<
  NativeStackScreenProps<ParamListTankStack, 'FertilizerList'>,
  CompositeScreenProps<
    BottomTabScreenProps<ParamListTabStack, 'TankTab'>,
    NativeStackScreenProps<ParamListMainStack>
  >
>
export type NavPropsPlantList = CompositeScreenProps<
  NativeStackScreenProps<ParamListTankStack, 'PlantList'>,
  CompositeScreenProps<
    BottomTabScreenProps<ParamListTabStack, 'TankTab'>,
    NativeStackScreenProps<ParamListMainStack>
  >
>
// General *********************************************************************
export type NavPropsProfile = NativeStackScreenProps<
  ParamListGeneralStack,
  'Profile'
>
export type NavPropsPostDetail = NativeStackScreenProps<
  ParamListGeneralStack,
  'PostDetail'
>

// Global **********************************************************************
declare global {
  namespace ReactNavigation {
    interface RootParamList extends RootStackParamList {}
  }
}
```

linking error
```jsx
<NavigationContainer
  linking={{
    ...linking,
    config: {
      screens: {
        Tabs: {
          screens: {
            FeedTab: {
              screens: {
                PostDetail: {
                  path: 'likePostComment/:postId/:commentId?',
                  parse: {
                    postId: Number,
                    commentId: Number,
                  },
                  exact: true,
                },
              },
            },
          },
        },
      },
    },
  }}
>
```
```
Type '{ screens: { FeedTab: { screens: { PostDetail: { path: string; parse: { postId: NumberConstructor; commentId: NumberConstructor; }; exact: true; }; }; }; }; }' is not assignable to type 'string | Omit<PathConfig<{}>, "initialRouteName" | "screens"> | undefined'.
  Object literal may only specify known properties, and 'screens' does not exist in type 'Omit<PathConfig<{}>, "initialRouteName" | "screens">'.ts(2322)
main.tsx(124, 17): The expected type comes from property 'Tabs' which is declared here on type 'PathConfigMap<{ Tabs: unknown; }>'
```

**Comment by tajetaje** [comment]
> Thanks @acro5piano, it fixes useNavigation but doesn't fix linking, it would be nice to remove that ts error in my project, but I'll survive with it. Here is my complete type file. I also followed that instruction for nested navigators: https://reactnavigation.org/docs/typescript#nesting-navigators and for Combining navigation props: https://reactnavigation.org/docs/typescript#combining-navigation-props
> 
> ```ts
> import { NativeStackScreenProps } from '@react-navigation/native-stack'
> import { BottomTabScreenProps } from '@react-navigation/bottom-tabs'
> import {
>   NavigatorScreenParams,
>   CompositeScreenProps,
> } from '@react-navigation/native'
> 
> import { TankState } from '../store/tank/types'
> 
> export type RootStackParamList = ParamListMainStack &
>   ParamListAuthStack &
>   ParamListFeedStack &
>   ParamListTankStack &
>   ParamListTabStack
> 
> export type ParamListMainStack = {
>   Auth: NavigatorScreenParams<ParamListAuthStack>
>   Tabs: NavigatorScreenParams<ParamListTabStack>
> }
> export type ParamListTabStack = {
>   FeedTab: NavigatorScreenParams<ParamListFeedStack>
>   TankTab: NavigatorScreenParams<ParamListTankStack>
> }
> export type ParamListGeneralStack = {
>   Profile: undefined
>   PostDetail: {
>     postId?: number
>     commentId?: number
>   }
> }
> export type ParamListAuthStack = {
>   Login: undefined
>   CreateAccount: undefined
>   ForgotPassword: undefined
> }
> export type ParamListFeedStack = ParamListGeneralStack & {
>   Feed: undefined
>   Comment: { postId: number }
>   CreatePost: {
>     photo: {
>       uri: string
>       width: number
>       height: number
>     }
>   }
>   TankDetail: {
>     tank?: TankState
>     tankId: number
>   }
> }
> export type ParamListTankStack = ParamListGeneralStack & {
>   Tank: {
>     refresh: string
>   }
>   AddEditTank: {
>     tank?: TankState
>     fertilizers?: {
>       id: number
>       name: string
>       dose: string
>       avatar: string | null
>     }
>     plants?: {
>       id: number
>       name: string
>       avatar: string | null
>     }
>   }
>   TankDetail: {
>     tank?: TankState
>     tankId: number
>   }
>   FertilizerList: undefined
>   PlantList: undefined
> }
> // Root ************************************************************************
> export type NavPropsAuth = NativeStackScreenProps<ParamListMainStack, 'Auth'>
> export type NavPropsTabs = NativeStackScreenProps<ParamListMainStack, 'Tabs'>
> // Auth ************************************************************************
> export type NavPropsLogin = CompositeScreenProps<
>   NativeStackScreenProps<ParamListAuthStack, 'Login'>,
>   NativeStackScreenProps<ParamListMainStack>
> >
> export type NavPropsCreateAccount = CompositeScreenProps<
>   NativeStackScreenProps<ParamListAuthStack, 'CreateAccount'>,
>   NativeStackScreenProps<ParamListMainStack>
> >
> export type NavPropsForgotPassword = CompositeScreenProps<
>   NativeStackScreenProps<ParamListAuthStack, 'ForgotPassword'>,
>   NativeStackScreenProps<ParamListMainStack>
> >
> // Tabs ************************************************************************
> export type NavPropsFeedTab = CompositeScreenProps<
>   BottomTabScreenProps<ParamListTabStack, 'FeedTab'>,
>   NativeStackScreenProps<ParamListMainStack>
> >
> export type NavPropsTankTab = CompositeScreenProps<
>   BottomTabScreenProps<ParamListTabStack, 'TankTab'>,
>   NativeStackScreenProps<ParamListMainStack>
> >
> // Feed Tab ********************************************************************
> export type NavPropsFeed = CompositeScreenProps<
>   NativeStackScreenProps<ParamListFeedStack, 'Feed'>,
>   CompositeScreenProps<
>     BottomTabScreenProps<ParamListTabStack, 'FeedTab'>,
>     NativeStackScreenProps<ParamListMainStack>
>   >
> >
> export type NavPropsCreatePost = CompositeScreenProps<
>   NativeStackScreenProps<ParamListFeedStack, 'CreatePost'>,
>   CompositeScreenProps<
>     BottomTabScreenProps<ParamListTabStack, 'FeedTab'>,
>     NativeStackScreenProps<ParamListMainStack>
>   >
> >
> export type NavPropsComment = CompositeScreenProps<
>   NativeStackScreenProps<ParamListFeedStack, 'Comment'>,
>   CompositeScreenProps<
>     BottomTabScreenProps<ParamListTabStack, 'FeedTab'>,
>     NativeStackScreenProps<ParamListMainStack>
>   >
> >
> export type NavPropsTankDetail = CompositeScreenProps<
>   NativeStackScreenProps<ParamListFeedStack, 'TankDetail'>,
>   CompositeScreenProps<
>     BottomTabScreenProps<ParamListTabStack, 'FeedTab'>,
>     NativeStackScreenProps<ParamListMainStack>
>   >
> >
> // Tank Tab ********************************************************************
> export type NavPropsTank = CompositeScreenProps<
>   NativeStackScreenProps<ParamListTankStack, 'Tank'>,
>   CompositeScreenProps<
>     BottomTabScreenProps<ParamListTabStack, 'TankTab'>,
>     NativeStackScreenProps<ParamListMainStack>
>   >
> >
> export type NavPropsAddEditTank = CompositeScreenProps<
>   NativeStackScreenProps<ParamListTankStack, 'AddEditTank'>,
>   CompositeScreenProps<
>     BottomTabScreenProps<ParamListTabStack, 'TankTab'>,
>     NativeStackScreenProps<ParamListMainStack>
>   >
> >
> export type NavPropsFertilizerList = CompositeScreenProps<
>   NativeStackScreenProps<ParamListTankStack, 'FertilizerList'>,
>   CompositeScreenProps<
>     BottomTabScreenProps<ParamListTabStack, 'TankTab'>,
>     NativeStackScreenProps<ParamListMainStack>
>   >
> >
> export type NavPropsPlantList = CompositeScreenProps<
>   NativeStackScreenProps<ParamListTankStack, 'PlantList'>,
>   CompositeScreenProps<
>     BottomTabScreenProps<ParamListTabStack, 'TankTab'>,
>     NativeStackScreenProps<ParamListMainStack>
>   >
> >
> // General *********************************************************************
> export type NavPropsProfile = NativeStackScreenProps<
>   ParamListGeneralStack,
>   'Profile'
> >
> export type NavPropsPostDetail = NativeStackScreenProps<
>   ParamListGeneralStack,
>   'PostDetail'
> >
> 
> // Global **********************************************************************
> declare global {
>   namespace ReactNavigation {
>     interface RootParamList extends RootStackParamList {}
>   }
> }
> ```
> 
> linking error
> 
> ```js
> <NavigationContainer
>   linking={{
>     ...linking,
>     config: {
>       screens: {
>         Tabs: {
>           screens: {
>             FeedTab: {
>               screens: {
>                 PostDetail: {
>                   path: 'likePostComment/:postId/:commentId?',
>                   parse: {
>                     postId: Number,
>                     commentId: Number,
>                   },
>                   exact: true,
>                 },
>               },
>             },
>           },
>         },
>       },
>     },
>   }}
> >
> ```
> 
> ```
> Type '{ screens: { FeedTab: { screens: { PostDetail: { path: string; parse: { postId: NumberConstructor; commentId: NumberConstructor; }; exact: true; }; }; }; }; }' is not assignable to type 'string | Omit<PathConfig<{}>, "initialRouteName" | "screens"> | undefined'.
>   Object literal may only specify known properties, and 'screens' does not exist in type 'Omit<PathConfig<{}>, "initialRouteName" | "screens">'.ts(2322)
> main.tsx(124, 17): The expected type comes from property 'Tabs' which is declared here on type 'PathConfigMap<{ Tabs: unknown; }>'
> ```

Did you ever get the linking prop typed correctly? I am hitting a similar issue.

**Comment by felipemillhouse** [comment]
@tajetaje  absolutely not, I just collapsed the code lines on vsCode and forgot them. Unfortunately ¯\_(ツ)_/¯

**Comment by ShivamJoker** [comment]
> @felipemillhouse I think you should define your nested route as a flat one, like this:
> 
> ```ts
> export type RootStackParamList = {
>   Auth: undefined
>   Login: undefined
>   CreateAccount: undefined
>   ForgotPassword: undefined
>   Tabs: undefined
>   FeedTab: undefined
>   Feed: undefined
> 
>   // ... and so on
> }
> 
> declare global {
>   namespace ReactNavigation {
>     interface RootParamList extends RootStackParamList {}
>   }
> }
> ```

This does work in navigate hook but not getting any completion in Link component

**Comment by felipemillhouse** [comment]
any chance for the declaration
```ts
import { RootStackParamList } from "src/commons/Routing/types/screenTypes";

declare global {
  namespace ReactNavigation {
    // eslint-disable-next-line @typescript-eslint/no-empty-interface -- overwrite the default type
    interface RootParamList extends RootStackParamList {}
  }
}
```
doesn't overwrite the lib type? I'm in another project and looks like it doesn't do any effect. this way I need to type every `useNavigation` like `useNavigation<HomeTabScreenProps<"LibraryArticle">["navigation"]>();`

I feel it's some TS config or version

**Comment by ChamaraWP** [comment]
@FelipeSSantos1 have you found any solution.

**Comment by KelvinPaul** [comment]
```ts
// Param type definition
type RootStackParamList {
  Home: undefined;
  Login: undefined;
}
```

create a custom hook alias under `hooks` folder
```ts
// useAppNavitgation.ts
import {RootStackParamList} from 'path/to/param'

export const useAppNavigation = useNavigation<NavigationProp<RootStackParamList>>;
```

Use it in your component
```ts
import React from 'react';
import {useAppNavigation} from 'path/to/custom/hook'

const Login = () => {
  const navigation = useAppNavigation();
  
  const onLogin = () => {
   navigation.navigate('Home');
  ]

  return <>...</>
}
```
