### ISSUE TITLE
iOS header doesn't go after change route

### ISSUE THREAD

**Issue by amirito** [react-navigation/react-navigation#9743]
### Current behavior

Hi
I am using stack navigation 

These are two of my screens: 
```js
<Stack.Screen name="User" options={{ header: (props) => <Header {...props} />, "title": 'User' }} component={User} />
<Stack.Screen name="Chat" component={Chat} options={{ headerShown: false }} />
```
As you can see, the 'user' page has a header but the chat page has not.
Everything is OK in android
but in iOS when I navigate from 'User' to 'Chat' header doesn't go.
I user log on to the `Header` component to see if `scene.route.name` changes, but it doesn't change on iOS

<img width="388" alt="Screen Shot 2021-07-17 at 4 20 18 PM" src="https://user-images.githubusercontent.com/8308363/126036081-9b76979c-1e31-4abc-94a4-1f36b5e7d320.png">
<img width="388" alt="Screen Shot 2021-07-17 at 4 22 57 PM" src="https://user-images.githubusercontent.com/8308363/126036084-eb3345c3-ba1c-4b97-95c5-10916c135a0a.png">

### Expected behavior

The 'Chat' page shouldn't have any header

### Reproduction

none

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |5.8.10
| @react-navigation/bottom-tabs          |5.9.0
| @react-navigation/drawer               |5.11.4
| @react-navigation/material-bottom-tabs |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                |5.12.8
| react-native-safe-area-context         |
| react-native-screens                   |
| react-native-gesture-handler           |1.8.0
| react-native-reanimated                |2.2.0
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           |0.64.0
| expo                                   |
| node                                   |
| npm or yarn                            |

**Comment by satya164** [comment]
https://reactnavigation.org/docs/stack-navigator#header

**Comment by amirito** [comment]
@satya164 I didn't get you
Is that an answer to my issue??
I used this properties and options, but it doesn't work on iOS

**Comment by satya164** [comment]
Please read the link properly. You are missing `headerMode="screen"`

**Comment by raajnadar** [comment]
@amirito in the docs it is clearly mentioned in the `headers` props section.

_Make sure to set headerMode to screen as well when using a custom header (see below for more details)._

**Comment by amirito** [comment]
@satya164 and @raajnadar thank you for your answer
