### ISSUE TITLE
Indicator style not working of tabstyle background is changed.

### ISSUE THREAD

**Issue by vishnuc** [react-navigation/react-navigation#9745]
### Current behavior

 Hi when I change background color of tabStyle , indicatorStyle border bottom color is not working , but when i remove the tabstyle indicator style is working.
 
```
 <Nav />
      <tTab.Navigator
          tabStyle: { backgroundColor: "black" },
          indicatorStyle: {
            borderBottomColor: "#50d3a7",
            borderBottomWidth: 2,
          },
        }}
        initialRouteName="Points"
      >
        <tTab.Screen name="Points" component={pointleftScreen} />
        <tTab.Screen name="Daily Rewards" component={calendarScreen} />
      </tTab.Navigator>

```
### Expected behavior

Both indicatorStyle and tabStyle should work.

### Reproduction

none

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [X] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |

| @react-navigation/material-top-tabs    | version 5
| expo                                   | sdk 42

**Comment by raajnadar** [comment]
This will help you https://github.com/react-navigation/react-navigation/issues/8012#issuecomment-639498402
