### ISSUE TITLE
React Navigation Custom Header rendering multiple times

### ISSUE THREAD

**Issue by mraghuram** [react-navigation/react-navigation#9746]
### Current behavior

I have a simple React Navigation 5 stack component. I am inserting a custom Header component into the screenOptions of the navigator like so:

```<NavigationContainer>
      <Stack.Navigator screenOptions={ {headerShow:true, header:(p)=>
        <Header/> }}>
        <Stack.Screen name="Home" component={Home} />
        <Stack.Screen name="Notifications" component={AssetExample} />
      </Stack.Navigator>
    </NavigationContainer>
```

My header component is quite simple as well.

```
export default function Header({
  navigation
}) {
  console.log("WHATS HAPPENING HERE")
  return ( 
    <View style = {styles.container}>
        <Text style = {styles.paragraph}>
          Something text here 
        </Text>

    </View>
  );
}
```

The console log statement in the header prints multiple times and I am unsure why that's happening.

Btw, in the snack below it render 4 / 5 times and stops. In my actual project, it goes in a loop

### Expected behavior

The console.log should only render once the component is mounted

### Reproduction

https://snack.expo.io/@mmanojr/restless-crackers

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 5.8.10
| @react-navigation/bottom-tabs          | 5.11.2
| @react-navigation/drawer               |
| @react-navigation/material-bottom-tabs |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                | 5.12.8
| react-native-safe-area-context         |
| react-native-screens                   |
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           |
| expo                                   |
| node                                   |
| npm or yarn                            |

**Comment by mraghuram** [comment]
Happens with the latest and version 6

**Comment by satya164** [comment]
Re-renders are how React works. It's not a bug, unless there is actually an infinite loop or something.

> I am unsure why that's happening

You can use devtools and investigate what's happening if you want to understand how the library works under the hood.

> In my actual project, it goes in a loop

Please provide a repro for that

**Comment by mraghuram** [comment]
I have already provided the snack in the original post... can some human respond to this? https://snack.expo.io/@mmanojr/restless-crackers

**Comment by mraghuram** [comment]
> Re-renders are how React works. It's not a bug, unless there is actually an infinite loop or something.
> 
> > I am unsure why that's happening
> 
> You can use devtools and investigate what's happening if you want to understand how the library works under the hood.
> 
> > In my actual project, it goes in a loop
> 
> Please provide a repro for that

Look, I know React re-renders.. But here there is a render for no reason. If I pull out the customer header component and push that into the screen, the re-renders stop

**Comment by satya164** [comment]
> But here there is a render for no reason

It's not obviously for "no reason", there are things re-rendering because the library's internal state changes and it calls the callback again. If you want to understand every detail about when the library updates its state. then you're free to debug the code with devtools and understand why that happens.

If you are having actual problems with performance due to re-renders, then you can wrap your component in `React.memo` and only pass the props that you want from the `header` callback.

> If I pull out the customer header component and push that into the screen

The header component in the screen isn't going to receive any props that the header in options receives. It'll also work very differently and be limited in what can do.

If it's an actual bug causing issues, then please provide a repro for that bug and describe the issue.

**Comment by mraghuram** [comment]
If you look at the snack I provided, you can look at the log statement in the Header.js file. Why is that printing multiple times? I am unable to figure that out.

**Comment by filiptronicek** [comment]
I am experiencing the same issue, even without a custom header...
```jsx
<Stack.Navigator
  screenOptions={() => {
    return {
      headerStyle: {
        backgroundColor:
          colorScheme === "dark" ? colors.darkHeader : colors.light,
      },
      headerTitleStyle: {
        color: colorScheme === "dark" ? "white" : "black",
      },
    };
  }}
>
```

![screenshot with two headers](https://user-images.githubusercontent.com/29888641/128068883-2a26ded7-7fa1-4fa0-a678-2501b1f56f15.png)

**Comment by raajnadar** [comment]
Come on re render is not an issue until it goes on for infinity or you can really feel a performance lag or flicker issue. React js app are refresh using re render.

@mraghuram react navigation it self is a react component it also contains internal state that is causing re render which is perfectly fine. If you think it should not reload you can use `React.useMemo` it cannot be added from the library because the library cannot predict when you want to reload or refresh it.

**Comment by filiptronicek** [comment]
@raajnadar thanks for the heads up, I tried using the `headerShown` option, but that only disables one header, in v5, I had 0 headers with `headerShown: false`, now I have one (which I am unable to disable).

**Comment by raajnadar** [comment]
I would suggest you to check all the changes that are done between v5 & v6 https://reactnavigation.org/docs/upgrading-from-5.x

Remember `headerShown` can be used in `screenOptions` & `options` if you have nested nav and want to disable for both add  `headerShown` for both navigators.

**Comment by satya164** [comment]
@filiptronicek example: https://reactnavigation.org/docs/nesting-navigators/#nesting-multiple-navigators

**Comment by filiptronicek** [comment]
Awesome, thanks a lot to you both! My issue is fixed.
