### ISSUE TITLE
Safe area not respected on the bottom area for Android

### ISSUE THREAD

**Issue by trajano** [react-navigation/react-navigation#9749]
### Current behavior

The safe area on iOS renders the bottom tab navigation correctly in that it spreads all the way to the bottom, but on Android, it gets cut off.

![](https://user-images.githubusercontent.com/110627/126201588-ad7b8f23-cc93-4844-9f3b-64a2cd326ef7.png)

### Expected behavior

Same as iOS

### Reproduction

https://snack.expo.io/@trajano/bottom-tab-navigation

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack

### Environment

https://github.com/expo/expo/issues/13686

{
  "dependencies": {
    "@expo/vector-icons": "^12.0.0",
    "react-native-screens": "~3.4.0",
    "@react-navigation/stack": "^5.5.1",
    "react-native-reanimated": "~2.2.0",
    "@react-navigation/native": "^5.8.10",
    "react-native-gesture-handler": "~1.10.2",
    "@react-navigation/bottom-tabs": "^5.5.2",
    "react-native-safe-area-context": "3.2.0",
    "@react-native-community/masked-view": "0.1.10"
  }
}

**Comment by trajano** [comment]
I upgraded to the versions specified

{
  "dependencies": {
    "@expo/vector-icons": "^12.0.0",
    "react-native-screens": "~3.4.0",
    "@react-navigation/stack": "^5.14.5",
    "react-native-reanimated": "~2.2.0",
    "@react-navigation/native": "^5.9.4",
    "react-native-gesture-handler": "~1.10.2",
    "@react-navigation/bottom-tabs": "^5.11.11",
    "react-native-safe-area-context": "3.2.0",
    "@react-native-community/masked-view": "0.1.10"
  }
}

Still the same issue

![image](https://user-images.githubusercontent.com/110627/126348304-7583011e-81ac-494d-b7b9-78822ecf4491.png)

**Comment by satya164** [comment]
> but on Android, it gets cut off

it's not a bug. you don't have a translucent navigation bar, so the tab bar cannot extend below.

**Comment by trajano** [comment]
The system navigation is "translucent" since other apps are respecting it

![image](https://user-images.githubusercontent.com/110627/126360452-4d18fb5f-65bb-4b81-91a1-07d82cd99714.png)

![image](https://user-images.githubusercontent.com/110627/126360491-1b47b41a-1bc3-4b34-a48f-e7de17354d6b.png)

iOS renders it correctly without any extra settings.

**Comment by satya164** [comment]
> The system navigation is "translucent" since other apps are respecting it

That's an app-level configuration, not system level. You need to configure your app's theme to get a translucent navigation bar. You can google how to do that.

> iOS renders it correctly without any extra settings.

Well, iOS is not Android and has different defaults.
