### ISSUE TITLE
I try to customize the route

### ISSUE THREAD

**Issue by qqakashi** [react-navigation/react-navigation#9753]
### Current behavior

**CustomStackNavigator.tsx**
                import {
                  createNavigatorFactory,
                  NavigationHelpersContext,
                  ParamListBase,
                  PartialState,
                  Route,
                  RouterConfigOptions,
                  StackNavigationState,
                  StackRouter,
                  StackRouterOptions,
                  useNavigationBuilder,
                } from '@react-navigation/native';
                import React from 'react';
                import {View} from 'react-native';

                //don't need to sign in to see the page
                const publicRoute = ['Home', 'StartPage', 'Login'];
                
                const MyStackRouter = (options: StackRouterOptions) => {
                  const router = StackRouter(options);

                return {
                   ...router,
                   getStateForAction(
                    action:any,
                    state: any,
                    options: any,
                  ) {
                    const result = router.getStateForAction(state, action, options);
                    console.log(action);
                    switch (action.type) {
                        case 'GO_BACK':
                          if (publicRoute.includes(action?.payload?.name)) {
                            return result;
                          }
                          if (state.routes[state?.routes.length - 1].params?.ISLOGIN) {
                            state.routes = state?.routes?.filter(
                              (v: {name: string}) => v.name != 'Login',
                            );
                            state.index = state?.routes.length - 1;
                            return router.getStateForAction(state, action, options);
                        }
                       return result;
                    case 'NAVIGATE':
                        if (publicRoute.includes(action?.payload?.name)) {
                          return result;
                        }
                        if (!publicRoute.includes(action?.payload?.name) &&
                              action?.payload?.name != 'Login' &&
                              //@ts-ignore
                              !global.isLogin
                          ) {
                          action = {
                            payload: {
                              name: 'Login',
                              params: {
                                ...action?.payload?.params,
                                _routeName: action?.payload?.name,
                              },
                            },
                            source: state?.routes[state.routes.length - 1]?.key,
                            type: 'NAVIGATE',
                         };
                       }
                       return router.getStateForAction(state, action, options);
                    default:
                       return result;
                  }
                },
              };
            };

          function StackNavigator({initialRouteName, children, screenOptions}: any) {
                const {state, navigation, descriptors} = useNavigationBuilder(MyStackRouter, {
                    children,
                    screenOptions,
                    initialRouteName,
                });

                return (
                    <NavigationHelpersContext.Provider value={navigation}>
                         <View style={{flex: 1}}>
                              {descriptors[state.routes[state.index].key].render()}
                          </View>
                    </NavigationHelpersContext.Provider>
                 );
            }
            export const createMyNavigator = createNavigatorFactory(StackNavigator);

**StackNavigation.tsx**
                import React from "react"
                import { NavigationContainer } from '@react-navigation/native';
                import {createMyNavigator} from "./CustomStackNavigator"
                import { createBottomTabNavigator } from '@react-navigation/bottom-tabs';
                import { View, Text, Button, Animated, Easing, Dimensions } from "react-native";
                import { createStackNavigator, TransitionSpecs } from '@react-navigation/stack';
                const My = createMyNavigator()
                const Tab = createBottomTabNavigator();

                 function MyTabs() {
                           return (
                              <Tab.Navigator sceneContainerStyle={{
                              }} tabBarOptions={{
                                  tabStyle:{
                                      backgroundColor:"black"
                                  }
                              }}>
                                <Tab.Screen name="Home" component={HomeScreen} options={{
                                  tabBarLabel: 'Home',
                                  tabBarIcon: ({ focused }) => (
                                    <View style={{width:30,height:30,backgroundColor:focused?"red":"blue"}}/>
                                  ),
                                }} />
                                <Tab.Screen name="Settings" component={SettingsScreen} options={{
                                  tabBarLabel: 'Settings',
                                  tabBarIcon: ({ focused }) => (
                                    <View style={{width:30,height:30,backgroundColor:focused?"red":"blue"}}/>
                                  ),
                                }}/>
                              </Tab.Navigator>
                          );
                }

             export default class StackNavigator extends React.Component{

                render(){
                    return (<NavigationContainer>
                        <My.Navigator mode="card" screenOptions={{
                            headerShown:false,
                            cardOverlayEnabled: false,
                            cardShadowEnabled:false,
                            cardStyle:{borderWidth:0},
                            transitionSpec:{
                                open: TransitionSpecs.TransitionIOSSpec,
                                close: TransitionSpecs.TransitionIOSSpec,
                            }
                        }}>
                          <My.Screen name="Home" component={MyTabs} />
                          <My.Screen name="Feed" component={FeedScreen} />
                          <My.Screen name="Login" component={Login} />
                          <My.Screen name="Fuck" component={Fuck} />
                        </My.Navigator>
                    </NavigationContainer>)
                }
            }

### Expected behavior

I jump from the settings page to the login page and then back to the settings page, but the status of tab.navigator is reset. It shows the home page instead of the settings page. Besides, the jump animation doesn't work
 I can't find any examples in the official website

### Reproduction

Custom routers

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | ^5.9.4 |
| @react-navigation/bottom-tabs     |^5.11.11|
| @react-navigation/stack                |^5.14.5|
| react-native-safe-area-context         |^3.2.0|
| react-native-screens                   |^3.4.0|
| react-native-gesture-handler           |^1.10.3|
| react-native-reanimated                |^2.2.0|
| react-native                           |0.64.1|
| npm or yarn                            |1.21.0|

**Comment by qqakashi** [comment]
No one answers for me？ 
@Noemi Rozpara

**Comment by fatoldsun00** [comment]
Hi, i doesn't read all thread, but your problem

`I jump from the settings page to the login page and then back to the settings page, but the status of tab.navigator is reset. It shows the home page instead of the settings page. `

seems to be like mine, in fact there are an option for change the backBehavior

 <Tab.Navigator
      backBehavior='history'
    >

Default is not history.

Maybe it can help

**Comment by jswangtao** [comment]
I also encountered the same problem. I want to intercept the route and use getStateForAction, but I have to customize the navigation. I customized it and found that there is no default effect such as the default header, screen cutting animation, etc.

**Comment by jianxinzhoutiti** [comment]
> I also encountered the same problem. I want to intercept the route and use getStateForAction, but I have to customize the navigation. I customized it and found that there is no default effect such as the default header, screen cutting animation, etc.

+1
