### ISSUE TITLE
the action 'navigate' with payload { name : 'home'} was not handled by any navigator

### ISSUE THREAD

**Issue by M2Changezi** [react-navigation/react-navigation#9754]
### Discription
 I'm making custom Drawer Content where onPress <DrawerItem>i want to navigate to another screen but on press i got error the action 'navigate' with payload { name : 'home'} was not handled by any navigator snack expo : https://snack.expo.io/@m2c/navigation-events-%7C-react-navigation
### Current behavior

It's giving error in development-mode `the action 'navigate' with payload { name : 'home'} was not handled by any navigator` and not working in production mode

### Expected behavior

It should work fine

### Reproduction

 https://snack.expo.io/@m2c/navigation-events-%7C-react-navigation

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
|     "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz",
    "@react-navigation/drawer": "^5.12.5",
    "@react-navigation/native": "^5.9.4",
    "@react-navigation/stack": "^5.14.5",   
    "expo": "^41.0.0",
    "react": "16.13.1",
    "react-dom": "16.13.1",
     "react-native": "https://github.com/expo/react-native/archive/sdk-41.0.0.tar.gz",
     "react-native-elements": "^3.4.2",
     "react-native-screens": "~3.0.0",
     "react-navigation": "^4.4.4",
     "@react-navigation/bottom-tabs": "^5.11.11",
    "@react-navigation/material-bottom-tabs": "^5.3.15",
     "@react-navigation/material-top-tabs": "^5.3.15",

**Comment by satya164** [comment]
Your repro doesn't have any screen named `home`. Also this is basically the same as https://github.com/react-navigation/react-navigation/issues/9734

Please use other channels than GitHub issues for getting help unless it's a bug in the library.
