### ISSUE TITLE
[Android] Navigating to a screen embedding a WebView crashes the app (Expo SDK 42)

### ISSUE THREAD

**Issue by jsamr** [react-navigation/react-navigation#9755]
### Current behavior

When pressing the DETAIL button and navigating to `TopicDetail` route embedding a WebView, the app crashes.

```jsx
import 'react-native-gesture-handler';
import React from 'react';
import { Button, View } from 'react-native';
import { createStackNavigator } from '@react-navigation/stack';
import { NavigationContainer } from '@react-navigation/native';
import WebView from 'react-native-webview';

const MainTabs = ({ navigation, route }) => {
  return (
    <View style={{ marginTop: 100 }}>
      <Button title="Detail" onPress={() => navigation.push('TopicDetail')} />
    </View>
  );
};

const TopicDetail = () => {
  return (
    <View>
      <WebView style={{height: 100, width: 200}} source={{ html: '<table><tr><td>123123</td></tr></table>' }} />
    </View>
  );
};

const StackNav = createStackNavigator();

export default () => {
  return (
    <NavigationContainer>
      <StackNav.Navigator detachInactiveScreens={false} headerMode={'none'}>
        <StackNav.Screen name="MainTabs" component={MainTabs} />
        <StackNav.Screen name="TopicDetail" component={TopicDetail} />
      </StackNav.Navigator>
    </NavigationContainer>
  );
};
```

### Expected behavior

No crash.

### Reproduction

https://snack.expo.dev/@jsamr/rnrh-webview-screens

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 5.9.4 |
| @react-navigation/stack                | 5.14.5 |
| react-native-safe-area-context         | 3.2.0 |
| react-native-screens                   | 3.4.0 |
| react-native-gesture-handler           | 1.10.2 |
| react-native-reanimated                | 2.2.0 |
| react-native-webview | 11.6.2 |
| react-native                           | (via expo) |
| expo                                   | SDK 42 |
| node                                   | N/A |
| npm or yarn                            | N/A |

**Comment by AndreBovolini** [comment]
Same thing happened here, but I'm using bare react native with a WebView library. Versions:

"@react-navigation/bottom-tabs": "^5.11.11",
    "@react-navigation/native": "^5.9.4",
    "@react-navigation/stack": "^5.14.5",

**Comment by satya164** [comment]
https://github.com/react-navigation/react-navigation/issues/6960#issuecomment-587418809

Closing since this issue is not actionable for us

**Comment by dorapax-lab** [comment]
@satya164 could you please explain why this issue is not actionable for you ? This is a serious issue and react-native apps are getting crashed in some mobile apps due to this.

```
"react-native": "~0.63.4",
"react-native-screens": "^3.6.0",
"react-native-webview": "11.6.2",
"react-native-render-html": "^6.0.4",
"@native-html/table-plugin": "^5.3.0",
```

Thanks & Regards,
