### ISSUE TITLE
Cannot open notification link when app is closed

### ISSUE THREAD

**Issue by phatmann** [react-navigation/react-navigation#9759]
### Current behavior

Tapping a notification when app closed does not open the link in the notification. If the app is open when the notification is tapped, then the link is opened.

To reproduce, make a iOS Simulator build. Open the app in the simulator and give permission to accept notifications. Close the app. In the terminal, navigate to source code folder and run this command: `xcrun simctl push booted notif.apns`

In the attached video, I send notification with app closed, with app in background, and app in foreground. It works when app is in foreground or background, but not when app is closed.

https://user-images.githubusercontent.com/36146/126683345-1b01ac98-f3f3-422c-b8fa-700dc0202a2f.mp4

### Expected behavior

The link should be opened even if app is closed when the notification is tapped.

### Reproduction

https://github.com/phatmann/deeplinkbug

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |  5.9.4
| @react-navigation/bottom-tabs          | 5.11.11
| @react-navigation/stack                | 5.14.5
| @react-navigation/drawer                | 5.12.5
| @react-navigation/material-bottom-tabs | 5.3.15
| @react-navigation/material-top-tabs | 5.3.15
| react-native-safe-area-context         | 3.2.0
| react-native-screens                   | 3.4.0
| react-native-gesture-handler           | 1.10.3
| react-native-reanimated                | 2.2.0
| react-native                           | 0.63.2
| expo                                   | 42.0.0
| node                                   | 14.17.0
| yarn                            | 1.22.5

**Comment by phatmann** [comment]
Fixed @react-navigation/drawer version

**Comment by raajnadar** [comment]
You need to handle it yourself on which screen to navigate. Add an ref to the navigation container and navigate the app according to the notification press. Mae sure you have the listener to listen for notification when app is closed.

**Comment by phatmann** [comment]
@raajnadar This is not at all what the [React Native documentation](https://reactnavigation.org/docs/navigation-container#linkingsubscribe) or the [Expo documentation](https://docs.expo.io/versions/latest/sdk/notifications/#handling-push-notifications-with-react-navigation) says. And I was told to use this code by @satya164 [in this comment](https://github.com/react-navigation/react-navigation/issues/9713#issuecomment-883356821). The code I am using is right from the docs. So either the documentation is incorrect or there is a bug in the linking code.

I tried to code something like you suggested and it is quite a complicated workflow and I did not finish it since it seemed like the wrong approach.

**Comment by raajnadar** [comment]
I use react native firebase, (FCM) they have a background FCM listener using that I receive the notification on foreground/ background / closed app. To navigate I use navigation container ref on the app root and navigate accordingly I find this very easy.

**Comment by satya164** [comment]
I don't know how Expo passes the URL to the app for notifications, but if it doesn't pass it through a regular deep link, then you'd need to add a custom `getInitialURL` option in your config to handle that.

This is more of a question about Expo notification docs rather than React Navigation so I'm closing this.

**Comment by phatmann** [comment]
I finally got notification tapping to work by waiting for the home screen in the app to load, In that screen code I use Expo's `useLastNotificationResponse` in a `useEffect` block to get the notification and navigate to its link. I also save the notification date in a state variable to avoid navigating to it again later (which should never happen since the notification response won't change, but I wanted to be sure since I had issues with this when running in dev mode).

**Comment by Svarto** [comment]
@phatmann could you share a small code snippet to show how you wait for the home screen in the app to load? I have been struggling with these race conditions for a long time, there doesn't seem to be great support in React Navigation to handle navigations or even queue a navigation event before full initialization. Currently they just drop them instead...

**Comment by phatmann** [comment]
My experience is that using the Linking interface at startup is broken. Clearly this is not a common use case or it would have been fixed long ago. So, I have found it better to wait until the UI "settles in" and then do your navigation. The user will see your Home Screen and then see the navigation action, but in practice this feels just fine, perhaps even better than a direct transition. Here is the code I am using:

```
  const notificationResponse = useLastNotificationResponse()
  const [lastRoutedNotification, setLastRoutedNotification] = useState<
    Notification | undefined
  >()

useEffect(() => {
    if (
      notificationResponse &&
      lastRoutedNotification?.date !== notificationResponse.notification.date
    ) {
      const data = getNotificationInfo(notificationResponse)

      if (data) {
        gotoRoute(data.route)
        setLastRoutedNotification(notificationResponse.notification)
      }
    }
  }, [lastRoutedNotification?.date, notificationResponse])

export function gotoRoute(route: string | undefined) {
  if (!route) {
    return
  }

  Linking.openURL(routeToUrl(route)).catch(err => {
    console.warn('Error going to route ', route, ': ', err)
  })
}

function getNotificationInfo(
  response: Notifications.NotificationResponse
): NotificationInfo | undefined {
  const data = getDataFromNotificationResponse(response)

  if (!data) {
    return
  }

  const route = findRouteInActions(data.actions) // app-specific translation of 'actions' into routes

  if (!route) {
    return
  }

  return {
    route,
  }
}

function getDataFromNotificationResponse(
  response: Notifications.NotificationResponse
): { actions: Action[]; event: string | undefined } | undefined {
  const wasTapped =
    response.actionIdentifier === Notifications.DEFAULT_ACTION_IDENTIFIER

  if (!wasTapped) {
    return
  }

  const trigger = response.notification.request.trigger

  if (trigger.type !== 'push') {
    return
  }

  let actions: Action[]
  let event: string | undefined

  if ('payload' in trigger) {
    const data = trigger.payload
    actions = data.actions_v3 as Action[]
  } else if ('remoteMessage' in trigger) {
    const data = trigger.remoteMessage.data
    actions = JSON.parse(data.actions_v3)
  } else {
    return
  }

  return { actions, event }
}

```

**Comment by satya164** [comment]
> My experience is that using the Linking interface at startup is broken

Just because Expo documentation is incomplete, doesn't mean it's broken. Like I already mentioned, Expo docs are currently missing the code to handle initial URL. https://github.com/expo/expo/pull/13891

**Comment by Svarto** [comment]
@satya164 thanks for sharing that! Does that also handle the issue when navigation is not fully initialized yet? Does it just silently drop navigation attempts then or does it queue them? 

There might be two parts to this problem, one is just what you mentioned - code to handle initial notification tapping. The other is that react-navigation returns the listener before the navigation state is fully ready and then silently dropping that navigation attempt. This is why @phatmann code is so helpful to handle those cases

**Comment by satya164** [comment]
> Does that also handle the issue when navigation is not fully initialized yet?
> The other is that react-navigation returns the listener before the navigation state is fully ready and then silently dropping that navigation attempt

I don't see why navigation wouldn't be fully initialized when the listener fires unless the listener somehow fires extremely quickly after app opens - but before app finishes mounting which is such an edge case. When talking about app being opened with a URL, `getInitialURL` doesn't need navigation to be initialized.

Normally you only have such issues if you're trying to manually handle things by yourself instead of using the built-in linking API.

> This is why @phatmann code is so helpful to handle those cases

If the built-in API is not handling any cases, please open an issue. You shouldn't need to write such complicated logic to handle incoming links.

**Comment by phatmann** [comment]
@satya164 I have opened 2 issues now, and both have been closed before I had a chance to address the concerns that you raised. I was unable to come up with code that clearly repros the situation, so until I do, I won't open a third. Here is a summation of what is going on:

* If I try to handle the notification tap by using the Linking.openUrl call, it can fail if the app is not already open. The call comes too early in React Navigation's startup process.
* If I try to do it the "right" way and use getInitialUrl, that did not work either. I don't remember the details, but I had to give up.

That is why I am waiting for Home Screen to land before I navigate. Works 100% of the time.

**Comment by satya164** [comment]
> I have opened 2 issues now, and both have been closed before I had a chance to address the concerns that you raised

As I mentioned, the Expo documentation was incomplete and I sent a PR to update which should address it.

> The call comes too early in React Navigation's startup process

It doesn't matter how early it comes, the linking mehcanism of React Navigation doesn't require anything to be initialized for it to work. Deep Linking uses exact same mechanism and I successfully use it in several apps.

> If I try to do it the "right" way and use getInitialUrl, that did not work either. I don't remember the details, but I had to give up

Expo docs didn't even mention the API that needed to be used in `getInitialUrl` until I sent the PR, so I don't think you could've done it the right way without having knowledge of the available API. But if you can still repro it with the updated docs, then feel free to open an issue with the repro.

**Comment by bernardmma** [comment]
Running to the same issue following the docs [here](https://reactnavigation.org/docs/deep-linking#third-party-integrations) using firebase messaging. The deeplink works when the app is in the background but not when the app is killed. I'm getting the correct deep link from data, but it always opens to the home page.

```
async getInitialURL() {
    // Check if app was opened from a deep link
    const url = await Linking.getInitialURL()

    if (url != null) {
      return url;
    }

    // Check if there is an initial firebase notification
    const message = await messaging().getInitialNotification();

    // Get deep link from data
    // if this is undefined, the app will open the default/home page
    return message?.data?.link;
  },
  subscribe(listener) {
    const onReceiveURL = ({ url }: { url: string }) => listener(url);

    // Listen to incoming links from deep linking
    Linking.addEventListener('url', onReceiveURL);

    // Listen to firebase push notifications
    const unsubscribeNotification = messaging().onNotificationOpenedApp(
      message => {
        const url = message?.data?.link;

        if (url) {
          // Any custom logic to check whether the URL needs to be handled

          // Call the listener to let React Navigation handle the URL
          listener(url);
        }
      },
    );

    return () => {
      // Clean up the event listeners
      Linking.removeEventListener('url', onReceiveURL);
      unsubscribeNotification();
    };
}
```

**Comment by minhna** [comment]
I got the same issue. It looks like the navigation tried to set the state too soon. I had this warning:

>  WARN  The navigation state parsed from the URL contains routes not present in the root navigator. This usually means that the linking configuration doesn't match the navigation structure. See https://reactnavigation.org/docs/configuring-links for more details on how to specify a linking configuration.

I don't have this warning once the app was opened before and the deep linking works as expected.
