### ISSUE TITLE
Double tap on bottom bar doesn't navigate to initial route in nested navigators

### ISSUE THREAD

**Issue by chipmunkcode** [react-navigation/react-navigation#9764]
### Current behavior

When I press the tab bar button two times, nothing happens in a nested navigator, when I `push` the Screens on the Stack. I tried to add `initial:false`, which **worked**, **but** it destroyed my stack order, when I want to `goBack()`.

```js
export default function App() {
  return (
    <NavigationContainer>
      <StackNavigator />
    </NavigationContainer>
  );
}

const Screen1 = ({ navigation, route }) => {
  return (
    <View>
      <Button
        onPress={() =>
          navigation.push('HomeTabs', {
            screen: 'Tab1',
            params: { screen: 'Screen2' },
          })
        }
        title="push"
      />
    </View>
  );
};

const Screen2 = ({ navigation, route }) => {
  return (
    <View>
      <Button
        onPress={() =>
          navigation.push('HomeTabs', {
            screen: 'Tab1',
            params: { screen: 'Screen2' },
          })
        }
        title="push"
      />
    </View>
  );
};

const HomeNavigator = () => {
  return (
    <Stack2.Navigator>
      <Stack2.Screen name="Screen1" component={Screen1} />
      <Stack2.Screen name="Screen2" component={Screen2} />
    </Stack2.Navigator>
  );
};

const HomeTabs = () => {
  return (
    <Tab.Navigator>
      <Tab.Screen name="Tab1" component={HomeNavigator} />
    </Tab.Navigator>
  );
};

const StackNavigator = () => {
  return (
    <Stack.Navigator>
      <Stack.Screen
        name="HomeTabs"
        options={() => ({ headerShown: false })}
        component={HomeTabs}
      />
    </Stack.Navigator>
  );
};

```

### Expected behavior

I expect to double press the tab icon and it brings me to my initial screen (first screen in the stack route).
And when I go back with the header arrow (or swipe) it should go back to the previous pushed screen.

### Reproduction

https://staging.snack.expo.dev/yVNm8hkeq

### Platform

- [X] Android
- [X] iOS
- [X] Web
- [ ] Windows
- [X] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 5.9.4
| @react-navigation/bottom-tabs          | 5.11.11
| @react-navigation/stack                | 5.14.5
| react-native-safe-area-context         | 3.2.0
| react-native-screens                   | 3.0.0
| react-native-gesture-handler           | 1.10.2
| react-native-reanimated                | 2.1.0
| react-native                           | 41.0.0
| expo                                   | 41.0.1
| node                                   | 14.16.1
| npm                            | 6.14.2

**Comment by satya164** [comment]
> I expect to double press the tab icon and it brings me to my initial screen (first screen in the stack route).

In your example, there was no first screen in the stack when you navigate since you didn't use `initial: false`.

This is expected behavior. You can implement your own behavior by adding a `tabPress` listener and doing whatever you'd like there. Example https://github.com/react-navigation/react-navigation/blob/67f6950c14b5ec1baa4359162c3c59b1b2fec94d/packages/stack/src/navigators/createStackNavigator.tsx#L83

**Comment by chipmunkcode** [comment]
> > I expect to double press the tab icon and it brings me to my initial screen (first screen in the stack route).
> 
> In your example, there was no first screen in the stack when you navigate since you didn't use `initial: false`.

If I use  `initial: false` on: 


```
const Screen2 = ({ navigation, route }) => {
  return (
    <View>
      <Button
        onPress={() =>
          navigation.push('HomeTabs', {
            screen: 'Tab1',
            params: { screen: 'Screen2', initial: false },
          })
        }
        title="push"
      />
    </View>
  );
};

```

It works to double press, but it screws up the stack history. Instead of going back to the **previous** pushed screen in the stack (by using the goBack() function) it goes back to the initial screen of the Stack Navigator... so how would I adjust it in my code?

Modifying the tabPress listener sounds kind of complicated, considering that I have to recognize if it is a double press or not.
