### ISSUE TITLE
How can I add 'beforeRemove' event to a custom navigator?

### ISSUE THREAD

**Issue by dashlee92** [react-navigation/react-navigation#9765]
### Current behavior

I have a custom navigator, which using **TabRouter** as its router and has a 'history' behavior, the navigator has the  following screens: 
  - Root (Tab)
    - A (Screen)
    - B (Stack) 
        - C (Screen) 
        - D (Screen)
        
I wanna trigger a custom event before leaving C, such as 'NAVIGATE' or 'GO_BACK', and I add a 'beforeRemove' event according to doc described in [Preventing going back](https://reactnavigation.org/docs/preventing-going-back)

Now when I go back, nothing happens but simply switch to the previous tab screen.

Here is what my code looks like: 

```
    useEffect(() => {
        const onBeforeRemove = (e: any) => {
                e.preventDefault()
                // do sth here
                navigation.dispatch(e.data.action)
            }])
        }

        navigation.addListener('beforeRemove',onBeforeRemove)
        return () => {
            navigation.removeListener('beforeRemove',onBeforeRemove)
        }
    }, [navigation])
```

I also notice that there.is a caveat in the documentation : 

>   _There are couple of edge cases to be aware of when using this approach. Specifically, the event only checks if the route is removed from the navigation state when an action is handled. If the change was from other reasons, e.g. - screen getting unmounted due to parent being unmounted, conditionally rendering different screens based on state not managed by React Navigation, using unmountOnBlur etc., then this event won't be triggered. It's impossible to prevent unmounting a component._

but not really make sense to me.

### Expected behavior

Trigger custom event when I press the back button or dispatch a "GO_BACK" action

### Reproduction

 https://snack.expo.dev/@dashlee/cf947c

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |~5.8.10

**Comment by satya164** [comment]
The screen doesn't get removed when going back in a tab navigator, so "beforeRemove" doesn't make sense. Usually you don't have to do anything special for that to in custom navigators to work.

> but not really make sense to me.

I don't know how else to explain that, you can try asking some colleague or someone else to make sense of it if you are having difficulty in understanding.
