### ISSUE TITLE
[v6] MaterialTopTabs indicator glitch when switching view with an item in between the current and selected item

### ISSUE THREAD

**Issue by samuelbeaulieu** [react-navigation/react-navigation#9775]
### Current behavior

When I switch from "Home" (#1) to "Settings2" (#3) there is a visual glitch on the indicator. This problem is not present if switch from "Home" (#1) to "Settings" (#2) or "Settings" (#2) to "Home" (#1) or "Settings" (#2) to "Settings2" (#3). It only happens when there's another item between the current and selected item. This problem is also not present in the v5.

The problem happens on both react-native normal and expo.

Snack for v5(no problem): https://snack.expo.dev/@samuelbeaulieu/materialtoptabs-v5
Snack for v6(problem): https://snack.expo.dev/@samuelbeaulieu/materialtoptabs-v6

https://user-images.githubusercontent.com/64789082/127687843-a445afa9-dd81-4f9a-a4de-aad73683b1be.MP4

### Expected behavior

Should not make a visual glitch. Should behave like in v5.

https://user-images.githubusercontent.com/64789082/127687760-34d5d2ab-43cd-4962-8b80-7a5bd5f23883.MP4

### Reproduction

https://snack.expo.dev/@samuelbeaulieu/materialtoptabs-v6

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [x] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.0.0-next.17
| @react-navigation/bottom-tabs          | 6.0.0-next.22
| @react-navigation/drawer               |
| @react-navigation/material-bottom-tabs |
| @react-navigation/material-top-tabs    | 6.0.0-next.18
| @react-navigation/stack                | 6.0.0-next.29
| react-native-safe-area-context         | 3.2.0
| react-native-screens                   | 3.4.0
| react-native-gesture-handler           | 1.10.3
| react-native-reanimated                | 2.2.0
| react-native-tab-view                  | 3.1.0
| react-native-pager-view                | 5.4.0
| react-native                           | 0.64.2
| expo                                   |
| node                                   | 14.17.0
| npm or yarn                            | 6.14.13 (npm)

**Comment by samuelbeaulieu** [comment]
Not using.
- @react-navigation/drawer
- @react-navigation/material-bottom-tabs

**Comment by nguyenbathanh** [comment]
This is a known issue of react-native-tab-view: https://github.com/satya164/react-native-tab-view/issues/1193
