### ISSUE TITLE
Update masked view dependency (rename)

### ISSUE THREAD

**Issue by luisnaranjo733** [react-navigation/react-navigation#9776]
### Current behavior

The[ getting started documentation](https://reactnavigation.org/docs/getting-started/#installation) tells you to install @react-native-community/masked-view

> expo install react-native-gesture-handler react-native-reanimated react-native-screens react-native-safe-area-context @react-native-community/masked-view

However, this package appears to be deprecated in favor of  @react-native-masked-view/masked-view, which is getting critical bug fixes (latest - v0.2.6) while the former (v0.1.11) is not.

See https://github.com/react-native-masked-view/masked-view/issues/131

### Expected behavior

react-navigation internally relies on the most up to date version of react-native-masked-view, and consumers of react-navigation get to benefit from bug fixes. Currently, consumers of react-navigation appear to be stuck on the unfixed version, which has known crashes (https://github.com/react-native-masked-view/masked-view/issues/114)

### Reproduction

https://github.com/react-native-masked-view/masked-view/issues/131
https://snack.expo.dev/

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 5.9.4
| @react-navigation/bottom-tabs          | 5.11.1
| @react-navigation/drawer               | 0
| @react-navigation/material-bottom-tabs |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                | 5.14.5
| react-native-safe-area-context         | 3.2.0
| react-native-screens                   | 3.4.0
| react-native-gesture-handler           | 1.10.3
| react-native-reanimated                | 1.13.2
| react-native-tab-view                  | 0
| react-native-pager-view                | 0
| react-native                           | 0.64.2
| expo                                   | 0
| node                                   | 12.22.3
| npm or yarn                            | npm

https://snack.expo.dev/

**Comment by satya164** [comment]
The new package is already used in React Navigation 6. It cannot be changed in React Navigation 5 since changing a peer dependency is a breaking change.
