### ISSUE TITLE
Deep Linking not working with deeper nested screens

### ISSUE THREAD

**Issue by lukebars** [react-navigation/react-navigation#9778]
### Current behavior

Currently, on iOS deeplinks that are passed when launching the app (e.g. from notification) are not navigating to screens that are nested in second / third level. 

Seems like `onReady` fires earlier than those screens are being registered for navigation.

Is there any other possible method to check if deep link setup is ready?

All of the deep links work fine on Android and on app in background. The main issue is iOS with killed app.

### Expected behavior

Deeplinks should work the same as on Android devices

### Reproduction

I'm happy to provide reproduction if it's really necessary, but currently I'm more concerned if there is a workaround.

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack

### Environment

    "@react-navigation/bottom-tabs": "^5.11.10",
    "@react-navigation/native": "^5.9.4",
    "@react-navigation/stack": "^5.14.4",
    "react-native-safe-area-context": "^3.2.0",
    "react-native-screens": "^3.4.0",
    "react-native-gesture-handler": "^1.10.3",
    "react-native-reanimated": "^2.2.0",
    "react-native": "0.64.2",

**Comment by lukebars** [comment]
Hmm... Looks like this is fixed in v6

**Comment by hotaryuzaki** [comment]
> Hmm... Looks like this is fixed in v6

i already experienced this from long time ago when im using v3
i dont know why and i cannot find any solution.
but right now your issues report here give me clue, i tried it for a few times and i can confirm that is because nested stack navigation

what version do you used?
so are you already solved this?
