### ISSUE TITLE
Check the render method of `BottomTabNavigator`

### ISSUE THREAD

**Issue by geek3000** [react-navigation/react-navigation#9783]
### Current behavior

This error is located at:
    in BottomTabNavigator (at App.js:27)
    in EnsureSingleNavigator (at BaseNavigationContainer.tsx:409)
    in BaseNavigationContainer (at NavigationContainer.tsx:91)
    in ThemeProvider (at NavigationContainer.tsx:90)
    in NavigationContainer (at App.js:26)
    in App (at renderApplication.js:47)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:107)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:134)
    in AppContainer (at renderApplication.js:40)
 ERROR  Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `BottomTabNavigator`.

### Expected behavior

Having bottom tabs

### Reproduction

https://snack.expo.dev/@geek123/material-bottom-tabs-navigator-%7C-react-navigation

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 5.9.4
| @react-navigation/bottom-tabs          |6.0.0
| @react-navigation/stack                |5.14.15
|react-native-reanimated:  |2.2.0
|react-native-safe-area-context | 3.2.0
|react-native-screens  |3.4.0
| react-native-gesture-handler           |1.10.3
| react-native                           |0.64.2
| node                                   |14.17.2
| npm                        |6.14.13

**Comment by geek3000** [comment]
thanks I have upgrade but now i got another issue: 

`Error: Unable to resolve module ./checkLegacyPathConfig from /home/MyName//MyTestApp/node_modules/@react-navigation/core/src/getStateFromPath.tsx: 

None of these files exist:
  * node_modules/@react-navigation/core/src/checkLegacyPathConfig(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  * node_modules/@react-navigation/core/src/checkLegacyPathConfig/index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
> 1 | import type {
  2 |   InitialState,
  3 |   NavigationState,
  4 |   PartialState,
    at ModuleResolver.resolveDependency (/home/myName/MyTestApp/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:211:15)
    at DependencyGraph.resolveDependency (/home/myname/MyTestApp/node_modules/metro/src/node-haste/DependencyGraph.js:413:43)
    at Object.resolve (/home/myname/MyTestApp/node_modules/metro/src/lib/transformHelpers.js:317:42)
    at resolve (/home/myname/MyTestApp/node_modules/metro/src/DeltaBundler/traverseDependencies.js:629:33)
    at /home/Myname/MyTestApp/node_modules/metro/src/DeltaBundler/traverseDependencies.js:645:26
    at Array.reduce (<anonymous>)
    at resolveDependencies (/home/myname/MyTestApp/node_modules/metro/src/DeltaBundler/traverseDependencies.js:644:33)
    at /home/myname/MyTestApp/node_modules/metro/src/DeltaBundler/traverseDependencies.js:329:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/home/myname/MyTestApp/node_modules/metro/src/DeltaBundler/traverseDependencies.js:137:24)`

**Comment by satya164** [comment]
https://reactnavigation.org/docs/troubleshooting/#im-getting-an-error-unable-to-resolve-module-after-updating-to-the-latest-version

**Comment by geek3000** [comment]
thank @satya164  i have fix it by doing `react-native start --reset-cache`
