### ISSUE TITLE
Flash of white when initially rendering on react-navigation 6

### ISSUE THREAD

**Issue by hsjoberg** [react-navigation/react-navigation#9784]
### Current behavior

When rendering a navigator, let's say the Stack navigator (doesn't matter which one), a flash of white is seen before the Screen is rendered. This didn't happen did not happen before version 6.

This is a huge problem when an app is in a dark theme.

This seems to be happening on Android. iOS and web seems fine (I cannot test Windows and MacOS).

### Expected behavior

App should render the content of `Screen`, without any flashes of white.

---

To best see the problem, set the background color of the Android app to `#000000`

1. Add `styles.xml` to `android/app/src/main/res/values` with the following content:
```XML
<resources>
    <style name="AppTheme" parent="Theme.AppCompat.NoActionBar">
        <item name="android:windowBackground">#000000</item>
    </style>
</resources>
```
2. Add `android:theme="@style/AppTheme"` to the `<application>` tag in `AndroidManifest.xml`

Use this code to illustrate the problem (just mount it directly):

```JSX
import React from "react";
import { View } from "react-native";
import { createStackNavigator } from "@react-navigation/stack";
import { NavigationContainer } from '@react-navigation/native';

function Black() {
  return <View style={{ backgroundColor: "#000000", flex: 1 }}></View>
}

const RootStack = createStackNavigator();

export default function Flash() {
  return (
    <NavigationContainer>
      <RootStack.Navigator initialRouteName="Black" screenOptions={{ headerShown: false, headerMode: "screen", cardStyle: { backgroundColor: "transparent" } }}>
        <RootStack.Screen name="Black" component={Black} />
      </RootStack.Navigator>
    </NavigationContainer>
  );
}
```

If done correctly, you'll see the screen filled white for a couple of milliseconds before the Screen is rendered.

### Reproduction

https://github.com/hsjoberg/react-navigation-flouc

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [X] @react-navigation/material-top-tabs
- [X] @react-navigation/stack

### Environment

| package                                | version    |
| -------------------------------------- | ---------- |
| @react-navigation/native               | 6.0.1      |
| @react-navigation/bottom-tabs          | 6.0.1      |
| @react-navigation/material-top-tabs    | 6.0.1      |
| @react-navigation/stack                | 6.0.1      |
| react-native-safe-area-context         | 3.2.0      |
| react-native-screens                   | 3.4.0      |
| react-native-gesture-handler           | 1.10.3     |
| react-native-reanimated                | 2.2.0      |
| react-native-tab-view                  | 2.16.0     |
| react-native                           | 0.64.2     |
| expo                                   | N/A        |
| node                                   | 15.10.0    |
| npm or yarn                            | yarn

**Comment by hsjoberg** [comment]
I've added a repro repository: https://github.com/hsjoberg/react-navigation-flouc

**Comment by satya164** [comment]
You should also set the `DarkTheme` for React Navigation: https://reactnavigation.org/docs/themes

**Comment by hsjoberg** [comment]
@satya164 Thanks, setting the `colors.background` prop fixes the issue.

**Comment by hadnet** [comment]
I got the same problem, right before loading the screen, but using Drawer component instead and only happens on Android. Using theme prop fro NavigationContainer does not fixed the issue.
