### ISSUE TITLE
[v6] iOS modal doesn't reach the top of the top bar

### ISSUE THREAD

**Issue by Dor256** [react-navigation/react-navigation#9785]
### Current behavior

When using `presentation: 'modal'` on a `Screen`/`Group` the Modal doesn't reach the top of the screen like in previous versions (see video).

Also, when rendering a `Screen`/`Group` from a stack that is nested inside bottom tabs, the modal will open under the bottom tabs which seems a pretty weird behavior for a modal and again, wasn't like this in previous versions.

I was not able to find any way to make this work in the docs.

https://user-images.githubusercontent.com/36549796/128067844-6b02a906-9f5a-4386-b8a6-b1d579424f3a.mov

Example code to reproduction:

```ts
 import React from 'react';
 import { View } from 'react-native';
 import { createStackNavigator } from '@react-navigation/stack'; 

 const { Navigator, Screen } = createStackNavigator();

 const RootNavigator: React.FC = () => {
   return (
    <Navigator>
       <Screen
          name="Root"
          component={() => <View/>}
       />
       <Screen
         options={{ presentation: 'modal' }}
         name="Modal"
         component={() => <View/>}
       />
    </Navigator>
   );
};
```

### Expected behavior

Modal should open to the full extent of the screen or at least have a prop that allows it to do so.

### Reproduction

See above.

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.0.1 |
| @react-navigation/bottom-tabs          | 6.0.1 |
| @react-navigation/stack                | 6.0.1 |
| react-native-safe-area-context         | 3.2.1 |
| react-native-screens                   | 3.4.0 |
| react-native-gesture-handler           | 1.10.2 |
| react-native-reanimated                | 2.2.0 |
| react-native                           | 0.63.4 |
| expo                                   | 42.0.0 |
| node                                   | 14.15.1 |
| npm or yarn                            | 1.22.11 |

**Comment by satya164** [comment]
Please don't open issues for changes that are clearly documented https://reactnavigation.org/docs/upgrading-from-5.x#modemodal-is-removed-in-favor-of-presentation-modal

> the modal will open under the bottom tabs which seems a pretty weird behavior for a modal and again, wasn't like this in previous versions.

not true

**Comment by ZeeshanAhmadKhalil** [comment]
There is still a problem with iOS
In android, it works fine
But we can't use `presentation: "modal"` as it looks weird in iOS

**Comment by pavelgorbach** [comment]
+1
