### ISSUE TITLE
Bottom Tab Navigator

### ISSUE THREAD

**Issue by japrozs** [react-navigation/react-navigation#9786]
### Current behavior

I am using `@react-navigation/bottom-tabs` as follosw:

```typescript
import React from "react";
import { MainScreen } from "./MainTabStack/MainScreen";
import { MessageScreen } from "./MainTabStack/MessageScreen";
import { createBottomTabNavigator } from "@react-navigation/bottom-tabs";
import { MainTabParamList } from "./MainTabStack/MainTabNav";

interface MainTabStackProps {}

const Tab = createBottomTabNavigator<MainTabParamList>();

export const MainTabStack: React.FC<MainTabStackProps> = ({}) => {
    return (
        <Tab.Navigator initialRouteName={"main"}>
            <Tab.Screen name="main" component={MainScreen} />
            <Tab.Screen name="message" component={MessageScreen} />
        </Tab.Navigator>
    );
};

```

and the `MainParamList` is as follows:

```typescript
import { BottomTabNavigationProp } from "@react-navigation/bottom-tabs";
import { RouteProp } from "@react-navigation/native";

export type MainTabParamList = {
    main: undefined;
    message: undefined;
};

export type MainTabNav<RouteName extends keyof MainTabParamList> = {
    navigation: BottomTabNavigationProp<MainTabParamList, RouteName>;
    route: RouteProp<MainTabParamList, RouteName>;
};

```

Howevery, when I use this my tab navigator appears at the top of the screen
![Screen Shot 2021-08-04 at 10 37 56 AM](https://user-images.githubusercontent.com/66138036/128125226-78197753-4473-4fb3-8586-3f82ade74d02.png)

### Expected behavior

The Bottom Tab Navigator should appear at the bottom of the screen.

### Reproduction

https://snack.expo.dev/@japrozsaini/react-navigation-error

### Platform

- [ ] Android
- [ ] iOS
- [X] Web
- [ ] Windows
- [X] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [X] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack

### Environment

| package                                | version                                                      |
| -------------------------------------- | ------------------------------------------------------------ |
| @expo/vector-icons                     | ^12.0.5                                                      |
| @react-navigation/bottom-tabs          | ^5.8.0                                                       |
| @react-navigation/material-bottom-tabs | ^5.2.16                                                      |
| @react-navigation/native               | ^5.7.3                                                       |
| expo                                   | ~42.0.1                                                      |
| expo-linking                           | ^2.3.1                                                       |
| expo-status-bar                        | ~1.0.4                                                       |
| react                                  | 16.13.1                                                      |
| react-dom                              | 16.13.1                                                      |
| react-native                           | https://github.com/expo/react-native/archive/sdk-40.0.tar.gz |
| react-native-paper                     | ^4.9.2                                                       |
| react-native-screens                   | ~3.4.0                                                       |
| react-native-vector-icons              | ^8.1.0                                                       |
| react-native-w                         | ~0.13.12                                                     |
| npm or yarn                            | yarn                                                         |

**Comment by japrozs** [comment]
I upgraded the packages and the problem is still there.

**Comment by flexbox** [comment]
@japrozs 
It's because you wrapped your app with `SafeAreaView` **before** `NavigationContainer`
    
Solved on your example:
![image](https://user-images.githubusercontent.com/360936/129860775-8a0df678-f091-43ce-9c68-847cd4e2c32e.png)

I suggest you to add `react-native-safe-area-context` to your stack because you will have more control 

If your problem is solved can you please close the issue? 
It sparks joy for maintainers ✨

**Comment by japrozs** [comment]
It worked! Thanks
