### ISSUE TITLE
Documentation: React Navigation v4 end of life target date?

### ISSUE THREAD

**Issue by ruqqq-tw** [react-navigation/react-navigation#9787]
### Current behavior

Documentation does not mention the roadmap of when v4 will be sunsetting given v6 has been released.

### Expected behavior

Documentation should mention the timeline on when v4 will reach end of life so that consumers have ample time to plan an upgrade.

### Reproduction

https://reactnavigation.org/docs/upgrading-from-5.x

### Platform

- [ ] Android
- [ ] iOS
- [ ] Web

### Packages

- [ ] react-navigation-drawer
- [ ] react-navigation-stack
- [ ] react-navigation-tabs

### Environment

N/A

**Comment by satya164** [comment]
There's no planned EOL for 4.x. We still accept PRs for bug fixes in 4.x and will do so for quite a while.
