### ISSUE TITLE
[v6] Modal header renders extra padding for nested Stack

### ISSUE THREAD

**Issue by alexborton** [react-navigation/react-navigation#9790]
### Current behavior

Using RN v6 on iOS device with a notch and `presentation: “modal”` to reference another Stack (rather than a screen), renders extra padding in the modal header that would normally be required for a regular screen (safe area view), despite setting `headerShown: false` In the correct places. 

If I reference the Screen directly (rather than a whole stack) it knows that the additional padding in the header can be ignored and renders the padding correctly. 

### Expected behavior

Referencing a stack as a “modal” should recognise correctly the header does not require the additional padding that would normally be required to account for the notch. 

### Reproduction

Https

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.0.0
| @react-navigation/bottom-tabs          | 6.0.0
| @react-navigation/material-top-tabs    | 6.0.0
| @react-navigation/stack                | 6.0.0
| react-native-safe-area-context         | 3.2.0
| react-native-screens                   | 3.4.0
| react-native-gesture-handler           | 1.10.2
| react-native-reanimated                | 2.2.0
| react-native-tab-view                  | 3.1.1
| react-native-pager-view                | 5.0.12
| expo                                   | 42.0.0

**Comment by vonovak** [comment]
this can be caused by this calculation https://github.com/react-navigation/react-navigation/blob/80a8567618b8ef52be1e4e73a9a8ccdff3a31244/packages/stack/src/views/Header/HeaderSegment.tsx#L124

and can be worked around by setting `headerStatusBarHeight: 0` in the navigator's options.

**Comment by vonovak** [comment]
to reproduce, use this in the example app

```diff
diff --git a/example/src/Screens/MixedStack.tsx b/example/src/Screens/MixedStack.tsx
index 349c9112..47c2c7a8 100644
--- a/example/src/Screens/MixedStack.tsx
+++ b/example/src/Screens/MixedStack.tsx
@@ -9,6 +9,7 @@ import { Button } from 'react-native-paper';

 import Albums from '../Shared/Albums';
 import Article from '../Shared/Article';
+import SimpleStackScreen from './SimpleStack';

 type MixedStackParams = {
   Article: { author: string };
@@ -116,7 +117,7 @@ export default function MixedStackScreen({ navigation }: Props) {
       />
       <MixedStack.Screen
         name="Albums"
-        component={AlbumsScreen}
+        component={SimpleStackScreen}
         options={{
           title: 'Albums',
           presentation: 'modal',
```

**Comment by alexborton** [comment]
> headerStatusBarHeight: 0

Perfect 👌  This solves the issue.

**Comment by marcato15** [comment]
I think I'm having the same issue but adding `headerStatusBarHeight` to the screen options doesn't seem to work. Am I putting it in the wrong place? I'm not exactly sure what "navigator's options" is referring to.

**Comment by agostinhocbneto** [comment]
Just posting here to mention that this solution
`headerStatusBarHeight: 0`
 solves the problem when you have a nested `Drawer.Navigator` within a `SafeAreaView`.

Thanks
