### ISSUE TITLE
Back button Android Ripple effect is not showing up on react-navigation 6

### ISSUE THREAD

**Issue by hsjoberg** [react-navigation/react-navigation#9794]
### Current behavior

The Android Ripple effect is not showing up when pressing the back button on react-navigation 6.

I suppose this is a bug and I've somewhat tracked it down, although I'm not experienced enough in react-navigation to fix it.

https://github.com/react-navigation/react-navigation/blob/3aab9fd05e485948292f9c709f8b24118b2b2bd2/packages/elements/src/Header/HeaderBackButton.tsx#L146-L160

https://github.com/react-navigation/react-navigation/blob/3aab9fd05e485948292f9c709f8b24118b2b2bd2/packages/elements/src/PlatformPressable.tsx#L66-L84

Removing `borderless: true` makes it show up, but as a square. It looks like radius is missing or something.

I guess there is a reason, but why not just use react-native's `TouchableNativeFeedback`?
https://github.com/hsjoberg/blixt-wallet/blob/e1a689f5d8b9ddfc2950aec205b71748065acb64/src/components/NavigationButton.tsx

### Expected behavior

Ripple effect should show up on supported Android devices.

### Reproduction

https://github.com/hsjoberg/react-navigation-back

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.0.1   |
| @react-navigation/stack                | 6.0.1   |
| react-native-safe-area-context         | 3.2.0   |
| react-native-screens                   | 3.5.0   |
| react-native-gesture-handler           | 1.10.3  |
| react-native-reanimated                | 2.2.0   |
| react-native                           | 0.64.2  |
| node                                   | 15.10.0 |
| npm or yarn                            | npm     |

**Comment by SergioAN007** [comment]
Issue still exists


Packages:
        "@react-navigation/drawer": "^6.1.8",
        "@react-navigation/elements": "^1.2.1",
        "@react-navigation/native": "^6.0.6",
        "@react-navigation/stack": "^6.0.11",

        "react-native": "^0.66.2",
        "react-native-reanimated": "^2.2.3",
        "react-native-safe-area-context": "^3.3.2",
        "react-native-screens": "^3.9.0",

**Comment by hsjoberg** [comment]
Can confirm.
The code is still buggy, preventing the ripple effect to play out correctly.

**Comment by SergioAN007** [comment]
For ripple effect just add to ripple config "foreground: true"

react-navigation/packages/elements/src/Header/HeaderBackButton.tsx
line 155:  android_ripple={{ borderless: true, foreground: true }}

**Comment by gaodeng** [comment]
any news? @satya164

**Comment by JerakRus** [comment]
Это до сих пор не поправлено ?

**Comment by diegolmello** [comment]
The same issue is going to happen if you use PlatformPressable with `borderless: true` to render header right buttons.
I could pinpoint the issue to the header background, which is an absolute positioned view https://github.com/react-navigation/react-navigation/blob/e6624653fbbd931158dbebd17142abf9637205b6/packages/elements/src/Header/Header.tsx#L225

That also happens outside react-navigation.
