### ISSUE TITLE
[v6] Transition animation doesn't work on android

### ISSUE THREAD

**Issue by coolswood** [react-navigation/react-navigation#9796]
### Current behavior

https://user-images.githubusercontent.com/25247802/128504067-826b82c1-1d80-4303-92be-0449dbfd655d.mp4

The header jerks when transitioning and there is no overlapping effect

### Expected behavior

https://user-images.githubusercontent.com/25247802/128504153-99de9c66-6b3c-436b-a5c6-c88996e7e7c9.mov

### Reproduction

https://github.com/coolswood/womens_health

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |6.0.1
| @react-navigation/stack                |6.0.1
| react-native-safe-area-context         |3.2.0
| react-native-screens                   |3.5.0
| react-native-gesture-handler           |1.10.3
| react-native-reanimated                |2.0.0
| react-native                           |0.64.1

**Comment by satya164** [comment]
I'm not sure how the repro shows that "transition animations don't work on Android", if you're talking about different transition animations, the defaults are different on different platforms. If you want to customize the animations, then you can https://reactnavigation.org/docs/stack-navigator/#animation-related-options
