### ISSUE TITLE
ModalSlideFromBottomIOS not full screen

### ISSUE THREAD

**Issue by Bardiamist** [react-navigation/react-navigation#9797]
### Current behavior

1. Navigate to Intermediate screen
2. Navigate to Modal screen
Result: Home screen header visible over Modal 

### Expected behavior

Modal screen should take fullscreen

### Reproduction

https://github.com/Bardiamist/navigation6/tree/modal

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |6.0.1
| @react-navigation/bottom-tabs          |6.0.1
| @react-navigation/drawer               |-
| @react-navigation/material-bottom-tabs |-
| @react-navigation/material-top-tabs    |-
| @react-navigation/stack                |6.0.1
| react-native-safe-area-context         |3.3.0
| react-native-screens                   |3.5.0
| react-native-gesture-handler           |1.10.3
| react-native-reanimated                |-
| react-native-tab-view                  |-
| react-native-pager-view                |-
| react-native                           |0.64.2
| expo                                   |-
| node                                   |16.6.1
| npm or yarn                            |yarn@1.22.10

**Comment by satya164** [comment]
This is expected behavior. Your stack with modal needs to be at the root to appear on top of everything: https://reactnavigation.org/docs/nesting-navigators/#parent-navigators-ui-is-rendered-on-top-of-child-navigator

Please post screenshots when you're opening issues regarding UI and try to provide snacks links. It's a lot of work to have to build and run a GitHub repo just to even understand what's the issue is about.

**Comment by Bardiamist** [comment]
@satya164 No, it isn't expected. Modal should take full screen because tab bar not have header. Here some bug. If remove `forFade` then modal will take full screen. Try to investigate repro.

**Comment by satya164** [comment]
Please provide a screenshot of what you're talking about

**Comment by Bardiamist** [comment]
@satya164 

Bug:

[Bug](https://user-images.githubusercontent.com/22082342/128657031-e91ad8c4-0804-4336-8e7f-dbfee6544f29.mov)

If remove `headerStyleInterpolator: forFade` the no bug:

[If remove `headerStyleInterpolator: forFade`](https://user-images.githubusercontent.com/22082342/128656610-18166cf9-b9e7-4715-ba9c-afe5f8f8bdf5.mov)

Or if navigate to Modal first (no Intermediate screen) then also no bug:

[Or if navigate to Modal first (no Intermediate screen)](https://user-images.githubusercontent.com/22082342/128656688-39af0c2a-f17b-4f3e-805a-96c70a66a413.mov)
