### ISSUE TITLE
_reactNative.Keyboard.removeListener is not a function - After RN upgrade from 0.63.2 to 0.65.0-rc.3

### ISSUE THREAD

**Issue by h0nor** [react-navigation/react-navigation#9803]
### Current behavior

I just upgraded from RN 0.63.2 to 0.64.2 then to 0.65.0-rc.3. Now I started to get this exception while trying to navigate between screens: _reactNative.Keyboard.removeListener is not a function.

<img width="1460" alt="so1" src="https://user-images.githubusercontent.com/30260964/128616366-888e3a6f-972a-4e48-9b5b-557b99d991e8.png">

The problem seems to be in BottomTabBar.js. The code snippet is below.

<img width="657" alt="so2" src="https://user-images.githubusercontent.com/30260964/128616369-2811d2ee-8844-4990-8b42-6f4665f82845.png">

The React-navigation version is 4.4.0. React-navigation-tabs version is 1.2.0.

I checked the Keyboard class' methods and actually, I CAN see a method called "removeListener". Even the auto-complete shows it.

<img width="1004" alt="so3" src="https://user-images.githubusercontent.com/30260964/128616379-af21129a-aa32-4e5b-a3f1-95df5f5c23e7.png">

Also, I can see in the react-native documentation that this method exists:

<img width="950" alt="so4" src="https://user-images.githubusercontent.com/30260964/128616386-2e8eb559-f09e-4708-8ce4-2cc3f3e1a713.png">

So, I don't see why I am getting this exception. Any help is much appreciated.

Updating the react-navigation version could be a solution, not sure about that, but I would like to avoid that path if possible since it has been working perfectly till now.

Thanks.

Edit: Just realized this exception is not thrown when navigating to a screen for the first time. It is thrown when I revisit a screen that has been previously visited.

Edit2: I am seeing this behavior on android. Haven't been able to compile the project on iOS yet.

### Expected behavior

Navigation should work without exceptions. It was working in RN 0.63.2.

### Reproduction

.

### Platform

- [X] Android
- [ ] iOS
- [ ] Web

### Packages

- [ ] react-navigation-drawer
- [ ] react-navigation-stack
- [X] react-navigation-tabs

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| react-navigation                       | 4.4.0
| react-navigation-tabs                  | 1.2.0
| react-navigation-drawer                | 1.4.0
| react-navigation-stack                 | 1.10.3
| react-native-safe-area-context         | empty
| react-native-screens                   | 2.10.1
| react-native-gesture-handler           | 1.4.1
| react-native-reanimated                | empty
| react-native-tab-view                  | 

├── react-native-tab-view@2.15.1
├─┬ react-navigation-drawer@1.4.0
│ └── react-native-tab-view@1.4.1
└─┬ react-navigation-tabs@1.2.0
  └── react-native-tab-view@1.4.1

| react-native                           | 0.65.0-rc.3
| expo                                   | not used
| node                                   | v12.18.0
| npm or yarn                            | npm: 7.20.5

**Comment by raajnadar** [comment]
This will be reviewed once the stable release is made available.

**Comment by chrisbobbe** [comment]
> Also, I can see in the react-native documentation that this method exists:

That screenshot is from the RN v0.64 doc; I think currently https://reactnative.dev/docs/next/keyboard will be closer to what applies for v0.65-rc.3.

**Comment by raajnadar** [comment]
@serdarosmanonur quick fix will be to remove `removeListener()` and use `remove()` and patch it using patch package.

**Comment by serdarosmanonur** [comment]
> @serdarosmanonur quick fix will be to remove `removeListener()` and use `remove()` and patch it using patch package.

@raajnadar thank you very much for your response. I tried using remove() inside BottomTabBar.js but that did not work either. It throws "...remove is not a function" error. I investigated the code for the current Keyboard.js implementation of the latest react-native version and the method defined in there is called removeEventListener. Once I renamed removeListener to removeEventListener problem was gone. Cheers.

**Comment by raajnadar** [comment]
Actually `.remove()` does not replace `removeListener()` directly. The `removeListener()` is deprecated instead we need to use `.remove()` if you read the docs they have mentioned the new usage for `.remove()`

**Comment by serdarosmanonur** [comment]
Yeah, I see what you mean. I might just do that too. Thanks...

**Comment by brightsider** [comment]
0.65 deployed, but fix for this issue not :(

**Comment by Gustash** [comment]
This issue also persists through version 5.x and 6.x, since `bottom-tabs` hasn't updated in those tags either.

**Comment by khpa** [comment]
this is my patch file and it works:
`diff --git a/node_modules/react-navigation-tabs/lib/module/views/BottomTabBar.js b/node_modules/react-navigation-tabs/lib/module/views/BottomTabBar.js
index b913f4e..0819964 100644
--- a/node_modules/react-navigation-tabs/lib/module/views/BottomTabBar.js
+++ b/node_modules/react-navigation-tabs/lib/module/views/BottomTabBar.js
@@ -345,21 +345,21 @@ class TabBarBottom extends React.Component {
 
   componentDidMount() {
     if (Platform.OS === 'ios') {
-      Keyboard.addListener('keyboardWillShow', this._handleKeyboardShow);
-      Keyboard.addListener('keyboardWillHide', this._handleKeyboardHide);
+     this.willShowSub =  Keyboard.addListener('keyboardWillShow', this._handleKeyboardShow);
+     this.willHideSub =  Keyboard.addListener('keyboardWillHide', this._handleKeyboardHide);
     } else {
-      Keyboard.addListener('keyboardDidShow', this._handleKeyboardShow);
-      Keyboard.addListener('keyboardDidHide', this._handleKeyboardHide);
+   this.didShowSub =   Keyboard.addListener('keyboardDidShow', this._handleKeyboardShow);
+   this.didHideSub =   Keyboard.addListener('keyboardDidHide', this._handleKeyboardHide);
     }
   }
 
   componentWillUnmount() {
     if (Platform.OS === 'ios') {
-      Keyboard.removeListener('keyboardWillShow', this._handleKeyboardShow);
-      Keyboard.removeListener('keyboardWillHide', this._handleKeyboardHide);
+      this.willShowSub?.remove();
+      this.willHideSub?.remove();
     } else {
-      Keyboard.removeListener('keyboardDidShow', this._handleKeyboardShow);
-      Keyboard.removeListener('keyboardDidHide', this._handleKeyboardHide);
+      this.didShowSub?.remove();
+      this.didHideSub?.remove();
     }
   } // @ts-ignore
 
diff --git a/node_modules/react-navigation-tabs/src/views/BottomTabBar.tsx b/node_modules/react-navigation-tabs/src/views/BottomTabBar.tsx
index 6235b4a..d623a73 100644
--- a/node_modules/react-navigation-tabs/src/views/BottomTabBar.tsx
+++ b/node_modules/react-navigation-tabs/src/views/BottomTabBar.tsx
@@ -136,6 +136,7 @@ class TabBarBottom extends React.Component<BottomTabBarProps, State> {
       Keyboard.removeListener('keyboardWillShow', this._handleKeyboardShow);
       Keyboard.removeListener('keyboardWillHide', this._handleKeyboardHide);
     } else {
+      
       Keyboard.removeListener('keyboardDidShow', this._handleKeyboardShow);
       Keyboard.removeListener('keyboardDidHide', this._handleKeyboardHide);
     }
`

**Comment by gkasireddy202** [comment]
RemoveEventListener error in react-native-navigation@4

![Uploading Simulator Screenshot - iPhone 15 Pro Max - 2024-04-13 at 15.00.37.png…]()
