### ISSUE TITLE
v6: headerLeft doesn't pass onPress prop

### ISSUE THREAD

**Issue by gavrichards** [react-navigation/react-navigation#9805]
### Current behavior

In v5, you could set a headerLeft button in the screen's options like this:
```
options.headerLeft = ({onPress}) => (
  <CancelButton
    onPress={onPress}
  />
);
```
But in v6, onPress is not passed in these props. Is this a mistake or should this now be done differently?

### Expected behavior

onPress passed in headerLeft props.

### Reproduction

n/a

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |  6.0.2
| @react-navigation/bottom-tabs          | n/a
| @react-navigation/drawer               |  6.1.0
| @react-navigation/material-bottom-tabs | n/a
| @react-navigation/material-top-tabs    | n/a
| @react-navigation/stack                |  6.0.3
| react-native-safe-area-context         | 3.3.0
| react-native-screens                   | 3.5.0
| react-native-gesture-handler           | 1.10.3
| react-native-reanimated                | 1.13.2
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           | 0.64.2
| expo                                   |
| node                                   | 14.16.0
| npm or yarn                            | 6.14.11

**Comment by sergeymild** [comment]
the problem still remains in version 6.0.2
if i set custom ```headerLeft```
in props i only have ```{"tintColor": "string"}```
