### ISSUE TITLE
[v6] Stack.Navigator has a background color

### ISSUE THREAD

**Issue by gavrichards** [react-navigation/react-navigation#9811]
### Current behavior

Since upgrading to v6, my stack navigator appears to have gained a background color that wasn't there before.
I don't want this, as I have an image background that sits behind the navigator, to ensure it remains static across multiple screens.

This is how the background and stack navigator are set up.
```
return (
    <SplashBackground>
      <Stack.Navigator
        screenOptions={{
          cardStyle: {
            backgroundColor: 'transparent',
          },
          animationEnabled: false,
          headerShown: false,
        }}>
        {currentScreen}
      </Stack.Navigator>
    </SplashBackground>
  );
```

`currentScreen` is swapped for each screen - it's part of a 'startup' sequence for the app, where you go through each screen in turn. The screens have a transparent background.

In this screenshot, I've inserted a 100px transparent block in `SplashBackground` which is pushing the Stack.Navigator down, to prove the image background is there beneath. But as you can see, you can't see the image through the screen like you should, and could in v5.

![Simulator Screen Shot - iPhone 12 - 2021-08-10 at 11 48 55](https://user-images.githubusercontent.com/432315/128854595-b2051679-80f1-4570-bc92-4b00ddd6c39c.png)

If I change cardStyle.backgroundColor to 'red' for example, then the background of the screen changes accordingly. So it feels like Stack.Navigator has gained a background color that wasn't there before?

![Simulator Screen Shot - iPhone 12 - 2021-08-10 at 11 52 26](https://user-images.githubusercontent.com/432315/128854707-7a217232-345d-4368-ab38-f5940a598476.png)

### Expected behavior

In v5, Stack.Navigator didn't have a background color and so the image underneath showed through as the background of each of the screens, so long as screenOptions > cardStyle.backgroundColor: 'transparent' was set.

### Reproduction

n/a

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.0.2
| @react-navigation/bottom-tabs          | 0
| @react-navigation/drawer               | 6.1.3
| @react-navigation/material-bottom-tabs | 0
| @react-navigation/material-top-tabs    | 0
| @react-navigation/stack                | 6.0.6
| react-native-safe-area-context         | 3.3.0
| react-native-screens                   | 3.5.0
| react-native-gesture-handler           | 1.10.3
| react-native-reanimated                | 1.13.2
| react-native-tab-view                  | 0
| react-native-pager-view                | 0
| react-native                           | 0.64.2
| expo                                   | 0
| node                                   | 14.16.0
| npm or yarn                            | 6.14.11

**Comment by gavrichards** [comment]
I can confirm this is still an issue on the latest versions:

- `@react-navigation/drawer` 6.1.4
- `@react-navigation/native` 6.0.2
- `@react-navigation/stack` 6.0.7

**Comment by satya164** [comment]
This is intentional as a lot of people complained that they had flicker in darkmode since there's was no background color set and the default was white.

I don't recommend making the navigator to transparent as it can be expensive to animate, but if you really want it, you can set the background color to transparent in the theme.

Another option is to render an image on each screen, use the `useCardAnimation` hook to get animation progress, and translate the image in the opposite direction to make it appear like it's not moving.

**Comment by gavrichards** [comment]
@satya164 my stack isn't used in a traditional sense - it's used like the old Switch navigator was, where each screen is substituted, a stack is never formed. So there is no animation, so I don't think your latter suggestion is what I'm looking for.

I initially rendered the image background on each screen, but found that there was a flicker from seeing the image load each time, so it made sense to mount it behind the stack so the image only loads once and remains in place throughout the sequence.

Therefore I think the only solution would be what you suggest with setting the background to transparent in the theme. I'll investigate how that's done. Thanks.

**Comment by gavrichards** [comment]
For anyone else hitting the same issue, the solution is:

```
import {
  DefaultTheme,
  NavigationContainer,
} from '@react-navigation/native';

...

const navTheme = {
  ...DefaultTheme,
  colors: {
    ...DefaultTheme.colors,
    background: 'transparent',
  },
};

...

return (
    <NavigationContainer
      theme={navTheme}
...
```

**Comment by todorone** [comment]
@gavrichards Thanks, it helped!

**Comment by Thomasbayy** [comment]
I was having problems aswell, but nothing worked for my configuration. Everything was good on iOS, but on Android I kept having a black background, seemingly no matter what I did.
After trying different solutions for 3 hours, I came up with a combination that seems to do the job.
Note, my solution is only tested on Stack Navigator v6.

As @gavrichards mentioned, using a theme worked like a charm for iOS.

**Following is a copy of gavrichards code example**

```
import {
  DefaultTheme,
  NavigationContainer,
} from '@react-navigation/native';

...

const navTheme = {
  ...DefaultTheme,
  colors: {
    ...DefaultTheme.colors,
    background: 'transparent',
  },
};

...

return (
    <NavigationContainer
      theme={navTheme}
...


```

Now, to fix my problems on android, i added following screenOptions to the Stack.Navigator component:
`
 <Stack.Navigator
    screenOptions={{
        detachPreviousScreen: true,
        presentation: 'transparentModal'
    }}>
`

"presentation: 'transparentModal'" changes all of the screens to act like modals with transparent backgrounds, the only problem this caused, was being able to see the previous screen in the stack in the background.
This is the default behaviour of the stack, when the presentation is set to transparentModal or modal.
To the rescue comes "detachPreviousScreen: true", which tells the Stack.Navigator to always hide the previous screen, even if the presentation is a modal type.

It doesn't feel like a perfect solution, but it's the only way I could come up with that made it possible to work on both iOS and Android.

I also want to mention that my solution likely would need more tinkering if you either use nested navigators, which I don't, or if you are using the built-in presentation "modal" or "transparentModal" which I also don't (outside of my workaround solution).

**Comment by buddyeorl** [comment]
in our app
```
     "react-native": "0.68.5",
     "expo": "^45.0.0",
    "@react-navigation/bottom-tabs": "^5.11.9",
    "@react-navigation/native": "^5.9.4",
    "@react-navigation/stack": "^5.14.4",
```
I fixed this by disabling `react-native-screens` by adding this to the `App.tsx` or `App.js`

import { enableScreens } from 'react-native-screens';
enableScreens(false);

Reference in the Highlight section https://blog.expo.dev/expo-sdk-41-12cc5232f2ef
and here https://www.npmjs.com/package/react-native-screens

**Comment by coreybyrum7** [comment]
> To the rescue comes "detachPreviousScreen: true", which tells the Stack.Navigator to always hide the previous screen, even if the presentation is a modal type.



> I was having problems aswell, but nothing worked for my configuration. Everything was good on iOS, but on Android I kept having a black background, seemingly no matter what I did. After trying different solutions for 3 hours, I came up with a combination that seems to do the job. Note, my solution is only tested on Stack Navigator v6.
> 
> As @gavrichards mentioned, using a theme worked like a charm for iOS.
> 
> **Following is a copy of gavrichards code example**
> 
> ```
> import {
>   DefaultTheme,
>   NavigationContainer,
> } from '@react-navigation/native';
> 
> ...
> 
> const navTheme = {
>   ...DefaultTheme,
>   colors: {
>     ...DefaultTheme.colors,
>     background: 'transparent',
>   },
> };
> 
> ...
> 
> return (
>     <NavigationContainer
>       theme={navTheme}
> ...
> ```
> 
> Now, to fix my problems on android, i added following screenOptions to the Stack.Navigator component: `<Stack.Navigator screenOptions={{ detachPreviousScreen: true, presentation: 'transparentModal' }}>`
> 
> "presentation: 'transparentModal'" changes all of the screens to act like modals with transparent backgrounds, the only problem this caused, was being able to see the previous screen in the stack in the background. This is the default behaviour of the stack, when the presentation is set to transparentModal or modal. To the rescue comes "detachPreviousScreen: true", which tells the Stack.Navigator to always hide the previous screen, even if the presentation is a modal type.
> 
> It doesn't feel like a perfect solution, but it's the only way I could come up with that made it possible to work on both iOS and Android.
> 
> I also want to mention that my solution likely would need more tinkering if you either use nested navigators, which I don't, or if you are using the built-in presentation "modal" or "transparentModal" which I also don't (outside of my workaround solution).

this was a life saver to come across. thanks!

i'm noticing now that the transparent background causes the previous screens content to hang around a bit more. in my particular situation, when i'm navigating back and forth, it takes a moment for the previous screens text to fade out

**Comment by Quixot1k** [comment]
> For anyone else hitting the same issue, the solution is:
> 
> ```
> import {
>   DefaultTheme,
>   NavigationContainer,
> } from '@react-navigation/native';
> 
> ...
> 
> const navTheme = {
>   ...DefaultTheme,
>   colors: {
>     ...DefaultTheme.colors,
>     background: 'transparent',
>   },
> };
> 
> ...
> 
> return (
>     <NavigationContainer
>       theme={navTheme}
> ...
> ```

Absolutely saved my life! I've been searching for so many solutions and tried "transparent" "transparentModal" everywhere, because my navigation is in a bottom-sheet and it does need a transparent background
