### ISSUE TITLE
Cant open drawer on swipe, also cant find opportunity to configure drawer position

### ISSUE THREAD

**Issue by TyshkevichSergey** [react-navigation/react-navigation#9818]
### Current behavior

also import 'react-native-gesture-handler' in index.js file

`import React from 'react';
import {NavigationContainer} from '@react-navigation/native';
import {createDrawerNavigator} from '@react-navigation/drawer';
import HomeScreen from '../screens/HomeScreen';
import Details from '../screens/Details';

const Drawer = createDrawerNavigator();

const Navigation: React.FC = () => (
  <NavigationContainer>
    <Drawer.Navigator initialRouteName="Home">
      <Drawer.Screen name={'Home'} component={HomeScreen} />
      <Drawer.Screen name={'Details'} component={Details} />
    </Drawer.Navigator>
  </NavigationContainer>
);

export default Navigation;
`

### Expected behavior

Drawer doesnt opens on swipe, also, i cant figure out how to configure drawer position

### Reproduction

.

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |6.0.2|
| @react-navigation/drawer               |6.1.3|
| @react-navigation/native-stack         |6.0.5|
| react-native-safe-area-context         |3.3.0|
| react-native-screens                   |3.5.0|
| react-native-gesture-handler           |1.10.3|
| react-native-reanimated                |2.2.0|
| react-native                           |0.64.1|
| node                                   |15.8.0|
|yarn                            |1.22.10|

**Comment by wirebug** [comment]
Hi @TyshkevichSergey ,
You have to encapsulate your Navigator in a NavigationContainer.
The drawer position can be configured in [screen options](https://reactnavigation.org/docs/drawer-navigator#options) like so:

```jsx
<Drawer.Navigator 
    initialRouteName="Home"
    screenOptions={{
        drawerPosition: 'right'
}}>
<Drawer.Screen name={'Home'} component={HomeScreen} />
<Drawer.Screen name={'Details'} component={Details} />
</Drawer.Navigator>```
