### ISSUE TITLE
Switching between Stack.Navigators does not render the expected Screen.

### ISSUE THREAD

**Issue by hannigand** [react-navigation/react-navigation#9819]
### Current behavior

I have two Stack.Navigators, one for Authenticated users and one for Unauthenticated users. A screen exists in both Stack.Navigators.

Is this a bug or is this expected?

It resolves itself if I use a different `name` in both Stacks - is this documented?

### Expected behavior

The screen that is part of the Stack.Navigator that is unmounted is removed from view.

### Reproduction

https://snack.expo.dev/@hannigan/dave

In the above snack, I have set up an `AuthStack` and an `UnauthStack`. 

1. When the app loads, `isAuth` is `true` and you will see the Home screen on the AuthStack. 
2. Click on `SET AUTH: FALSE`. The UnauthStack is now rendered and the Welcome screen is displayed due to `initialRoute="Welcome"` - this is expected.
3. Click on `SET AUTH: TRUE` to see the AuthStack render and the Home screen is displayed.
4. Click on `SET AUTH: FALSE` once more, this renders the UnauthStack but the Home screen is now rendering instead of the Welcome screen. It appears `initialRoute="Welcome"` is being ignored.

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [x] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [X] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |   ^5.7.0
| @react-navigation/bottom-tabs          | ^5.8.0
| @react-navigation/drawer               |
| @react-navigation/material-bottom-tabs |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                | ^5.9.0
| @react-navigation/native-stack         |
| react-native-safe-area-context         |
| react-native-screens                   |
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           |  0.63.3
| expo                                   |
| node                                   | 14.7.0
| npm or yarn                            |  npm 6.14.13

**Comment by Haider-Ali-7** [comment]
@hannigand Hi, does upgrading react-navigation related packages solved your issue? I'm having tough time resolving this 
same issue.
