### ISSUE TITLE
[v6] navigation.navigate('Home') showing some error in typescript

### ISSUE THREAD

**Issue by umardevid** [react-navigation/react-navigation#9820]
### Current behavior

Hi :+1: 

When I use useNavigation or from props `{ navigation }` for navigate between screen using `navigation.navigate('Home')` the typescript return error `Argument of type '"Main"' is not assignable to parameter of type '{ key: string; params?: undefined; merge?: boolean | undefined; } | { name: never; key?: string | undefined; params: never; merge?: boolean | undefined; }'` what does it mean?

below is my code:
<details>

```
import { Button } from 'react-native-paper';
import { useNavigation } from '@react-navigation/native';

const Home: React.FC = () => {
  const navigation = useNavigation();

  return (
    <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
      <Button onPress={() => navigation.navigate('Main')}>Navigate</Button>
    </View>
  );
};

export default React.memo(Home);
```

</details>

previously i used react navigation v5 and working find with that method

thanks for your help

### Expected behavior

No error message

### Reproduction

https://github.com/umardevid/react-navigation

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | ^6.0.2
| @react-navigation/stack                | ^6.0.6
| @react-navigation/bottom-tabs      | ^6.0.4
| @react-navigation/drawer      | ^6.1.3
| @react-navigation/material-bottom-tabs      | ^6.0.4
| @react-navigation/material-top-tabs      | ^6.0.2
| node | 14.17.5

**Comment by umardevid** [comment]
> Couldn't find version numbers for the following packages in the issue:
> 
> * `@react-navigation/bottom-tabs`
> * `@react-navigation/drawer`
> * `@react-navigation/material-bottom-tabs`
> * `@react-navigation/material-top-tabs`
> 
> Can you update the issue to include version numbers for those packages? The version numbers must match the format 1.2.3.

done

**Comment by satya164** [comment]
https://reactnavigation.org/docs/upgrading-from-5.x/#stricter-types-for-typescript

**Comment by wiltonzanin** [comment]
Hello, I have the same issue, anyone has the solution?

**Comment by ezranbayantemur** [comment]
Same here..

**Comment by Lucasark** [comment]
Same issue

**Comment by michaelbayday** [comment]
same issue please reopen

**Comment by umardev500** [comment]
I still have this issue

**Comment by lorenamelor** [comment]
Same issue

**Comment by Chibao284-Jason** [comment]
![image](https://user-images.githubusercontent.com/95473195/147429485-ed652683-294a-4025-ac00-975f98ec0af8.png)
work for me !

**Comment by ChiBao284** [comment]
![image](https://user-images.githubusercontent.com/53886386/147429570-7bf23300-bc59-4478-8243-16d4caee13ca.png)
Work for me!

**Comment by raajnadar** [comment]
People saying "same issue" did you even care to open the link provided by @satya164 ?

In upgrade docs it is clearly written that v6 uses strict type check. So you need to annotate the methods to avoid those type errors.

Typescript doest mean you have code in .ts or .tsx files you also need to mention which types are allowed for a method parameters. I hope it is clear now.

**Comment by yujin-noh** [comment]
I solve this problem v6

1. RootType (index.ts file)
```
export type RootStackParamList = {
  Home: undefined;
  Login: undefined;
};

export type NavigationProps = StackNavigationProp<RootStackParamList>;

```
2. used (Foo.tsx)
```
const navigation = useNavigation<NavigationProps>()

const onPress = useCallback(() => {
    navigation.navigate('Home' as keyof RootStackParamList)
}, [])
```
I recommended global type

(index.d.ts)
```
namespace ReactNavigation {
    interface RootParamList extends RootStackParamList {}
  }
```
(Foo.tsx)
```
const navigation = useNavigation()

const onPress = useCallback(() => {
    navigation.navigate('Home' as keyof RootStackParamList)
}, [])

```

Please refer to the examples or docs

**Comment by nhanhoangDF** [comment]
![Screen Shot 2023-03-28 at 14 43 21](https://user-images.githubusercontent.com/109951984/228164600-f6028c99-da3d-4864-a603-0be08e9a3760.png)
Flow : Home -> detail -> fan
Issus : When i click navigate in fan screen back to Home -> and app is freezy and log bug like this image, thanks for read!

**Comment by Canoral** [comment]
Hi there 👋 this is the solution :

In my App.tsx file, I declare all my routes, screens, and also define the types for the routes. I'm using the React Navigation library.

```
import { NavigationContainer, NavigationProp } from "@react-navigation/native";
import { createNativeStackNavigator } from "@react-navigation/native-stack";
import Home from "./screens/Home";
import { Provider } from "react-redux";
import store from "./redux/store";
import Détails from "./screens/Détails";

export type RootStackParamList = {
  Home: undefined;
  Détails: { pokemonId: string };
};

const Stack = createNativeStackNavigator<RootStackParamList>();

function App() {
  return (
    <Provider store={store}>
      <NavigationContainer>
        <Stack.Navigator initialRouteName="Home">
          <Stack.Screen name="Home" component={Home} />
          <Stack.Screen name="Détails" component={Détails} />
        </Stack.Navigator>
      </NavigationContainer>
    </Provider>
  );
}
export default App;
```

Then, in my Home screen, I use the useNavigate() method from React Navigation and type it like this:

```
function Home() {
  const dispatch = useAppDispatch();
  const navigation = useNavigation<NavigationProp<RootStackParamList>>();
  const pokemons = useAppSelector((state) => state.interaction.pokemons);

  useEffect(() => {
    dispatch(fetchAllPokemons());
  }, [dispatch]);

  return (
    <ScrollView contentInsetAdjustmentBehavior="automatic">
      <View style={styles.viewContainer}>
        {pokemons &&
          pokemons.map((pokemon, index) => (
            <TouchableOpacity
              key={index}
              onPress={() => {
                navigation.navigate("Détails", {
                  pokemonId: pokemon.id.toString(),
                });
              }}
            >
```

I hope this helps! If you have any more questions or need further clarification, feel free to ask.
