### ISSUE TITLE
How to navigate between screen using navigation.navigate Typescript and useNavigation hook

### ISSUE THREAD

**Issue by umardevid** [react-navigation/react-navigation#9821]
### Current behavior

I use navigation.navigate in typescript but error

`Argument of type '[string]' is not assignable to parameter of type '[any, "Home" | "Main"]`

````
import React from 'react';
import { View } from 'react-native';
import { Button } from 'react-native-paper';
import { NativeStackNavigationProp } from '@react-navigation/native-stack';
import { useNavigation } from '@react-navigation/native';

export type RootStackParamList = {
  Home: undefined;
  Main: undefined;
};

type HomeScreenNavigationProp = NativeStackNavigationProp<
  RootStackParamList,
  'Home'
>;

const Home = (): JSX.Element => {
  const navigation = useNavigation<HomeScreenNavigationProp>()

  const handleNavigate = () => {
    navigation.navigate('Main')
  };

  return (
    <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
      <Button onPress={handleNavigate}>Navigate</Button>
    </View>
  );
};

export default React.memo(Home);


````

### Expected behavior

no error 

### Reproduction

https://github.com/umardevid/react-navigation

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | ^6.0.2
| @react-navigation/native-stack         | ^6.0.5
| react-native                           | 0.64.1
| node                                   | 14

**Comment by artola** [comment]
@umardevid Same problem for me. Mainly the typings for `navigation.navigate('Main')` are not supporting passing this `string` for the name of the route.

**Comment by cesargdm** [comment]
I'm getting for react navigation 6

`Argument of type 'string' is not assignable to parameter of type 'never'.`

<img width="893" alt="Screen Shot 2021-08-15 at 9 10 42 p m" src="https://user-images.githubusercontent.com/10179494/129502310-f1e1a08e-982e-4f9e-bd4e-90f9c54654d2.png">

**Comment by himrocks33** [comment]
@satya164 This should not need a repo... As @umardevid suggested the type definitions for the navigate function are just incorrect. It does not currently support `string`.  

navigate('Details') throws an error as the current definition only supports never.

navigate('Details' as never) fixes error.

**Comment by satya164** [comment]
@himrocks33

> This should not need a repo...

OP posted properly annotated code and says it gives type error, it needs a repro because I'm not going to know every config you have that could cause issue. 

> As @umardevid suggested the type definitions for the navigate function are just incorrect. It does not currently support string.

That's not at all what's posted in the issue. `useNavigation` is annotated so it shouldn't give type error for navigating to a valid screen.

`string` isn't type-safe and allows invalid screen names - navigating to a screen named `Profile` will give no error regardless you have it or not. if you don't care about type safety then you're free to use `any` to annotate your types or ignore the error with `@ts-ignore`

**Comment by satya164** [comment]
Anyway, I'm going to close this since OP didn't provide any repro and I don't get any errors from the code that they posted. Also tricking the bot by forking the repo to your account instead of actually providing a repro is not nice.

**Comment by hoshomoh** [comment]
> Anyway, I'm going to close this since OP didn't provide any repro and I don't get any errors from the code that they posted. Also tricking the bot by forking the repo to your account instead of actually providing a repro is not nice.

This is an actual issue, with "@react-navigation/bottom-tabs": "^6.0.4", "@react-navigation/native": "^6.0.2", "@react-navigation/stack": "^6.0.6". typescript complains even though you annotate `useNavigation`.

**Comment by satya164** [comment]
@hoshomoh please provide a repro. it's impossible for me to debug without a repro.

**Comment by hoshomoh** [comment]
> @hoshomoh please provide a repro. it's impossible for me to debug without a repro.

I am not sure how to provide a repro for you. See the screen recording below of the error I am getting. 

https://user-images.githubusercontent.com/5657993/129934180-de5248d7-5481-49a3-adbb-e1eceef162c3.mov

**Comment by satya164** [comment]
> I am not sure how to provide a repro for you

By providing code in a repository that shows an error.

That video is very low resolution and it's impossible to read anything there. Regardless it doesn't seem related to `useNavigation` at all.

Please don't ping me if you don't have a repro. There are other resources linked for getting help when you try to open an issue.

**Comment by hoshomoh** [comment]
I am quite certain the error is here https://github.com/react-navigation/react-navigation/blob/07a3f702daab055e467a924f9b62f31e670ef1be/packages/core/src/types.tsx#L190

That doesn't look correct to me. `args` is an array and should be typed as:

```
navigate<RouteName extends keyof ParamList>(
...args: undefined extends ParamList[RouteName]
    ? [RouteName] | [RouteName, ParamList[RouteName]]
    : [RouteName, ParamList[RouteName]]
): void;
```

**Comment by hoshomoh** [comment]
@umardevid @himrocks33 after updated my dependency to use typescript version 4.3.2 I stopped getting this error. satya164  was right after all.

**Comment by umardevid** [comment]
> @umardevid @himrocks33 after updated my dependency to use typescript version 4.3.2 I stopped getting this error. satya164 was right after all.

the @typescript-eslint/typescript-estree package does not support newer typecript > 4.x.x

**Comment by wilson208** [comment]
@umardevid I bumped `@typescript-eslint/typescript-estree` dependency also like so, this is only used by eslint:
```
    "@typescript-eslint/typescript-estree": "^4.29.2"
```

**Comment by khudratov** [comment]
why closed this issue. where is answer i update typescript but it don't help me

**Comment by DaywisonSilva** [comment]
@khudratov You can use this:
`type Props = StackNavigationProp<RootStackParamList, 'Home'>;`

in your component:
`const navigation = useNavigation<Props>();`
