### ISSUE TITLE
Can't center header title on android

### ISSUE THREAD

**Issue by ramicaza** [react-navigation/react-navigation#9823]
### Current behavior

I am unable to center the header title on android.  On iOS it's centered by default but on android it scoots to the left next to the back button.  Looking through the code of the native-stack/src/HeaderConfig.tsx it doesn't look like this is possible however I very well could be wrong here.

### Expected behavior

There should be a way to center the header title on android

### Reproduction

Run an app with a header title with a stack navigator on android 

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |  6.0.2
| @react-navigation/native-stack         | 6.0.5
| react-native-safe-area-context         | 3.3.0
| react-native-screens                   | 3.5.0

**Comment by vonovak** [comment]
hello, have you tried this? https://reactnavigation.org/docs/elements/#headertitlealign
