### ISSUE TITLE
[android] modal isn't shown above absolute view (different to ios)

### ISSUE THREAD

**Issue by hannojg** [react-navigation/react-navigation#9825]
### Current behavior

We have a custom pervasive header in our app that should be shown on any page. We implemented it in App.tsx like this:

```jsx
<View>
  <NavigationContainer>
  {/* ... */}
  </NavigationContainer>
  <View style={StyleSheet.absoluteFill}>
    <TopBar />
  </View>
</View>
```

When opening a `transparentModal` the behaviour on iOS and android is different:

### Behavior android:

As you can see in the video, the screen that is opened as modal will be behind the custom header view.

https://user-images.githubusercontent.com/16821682/129566322-1f2bee7a-611f-423d-a10f-b152cf5b7201.mp4

_Note:_ We already tried to fix this by playing with zIndex, which didn't help.

### Behavior iOS (correct):

https://user-images.githubusercontent.com/16821682/129566015-84fdd439-b711-4211-bf15-7b1c257edef7.mp4

Here the screen is shown above anything else which is what we are expecting.

### Reproduction

https://snack.expo.dev/@skillnation/react-navigation-v6-modal-reproduction

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [X] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.0.2
| @react-navigation/stack                | 6.0.6
| @react-navigation/native-stack         | 3.4.0
| react-native-screens                   | 3.4.0
| react-native-gesture-handler           | 1.10.2
| react-native-reanimated                | 2.2.0
| react-native                           | 0.64.2
| expo                                   | 42.0.1
| node                                   | v15
| npm or yarn                            | v7

**Comment by satya164** [comment]
You're using `react-native-screens/native-stack`, so please open the issue in relevant repo.

**Comment by hannojg** [comment]
@satya164 we might want to reopen the issue. I just tested using stackNavigator from `@react-navigation/stack`, and the issue is still the same.
