### ISSUE TITLE
[android] can't center a HeaderTitle in a NativeStackNavigator

### ISSUE THREAD

**Issue by JacquesLeupin** [react-navigation/react-navigation#9829]
### Current behavior

- this is a duplicate of #9823, which I don't think should've been closed
- when creating a `<HeaderTitle />` component on Android, the header title aligns left
- the solution proposed in #9823 doesn't seem to work with `createNativeStackNavigator()`

### Expected behavior

- center the HeaderTitle on Android

### Reproduction

https://github.com/JacquesLeupin/twn-alerting-rn/

### Platform

- [X] Android
- [ ] iOS
- [ ] Web

### Packages

- [ ] react-navigation-drawer
- [X] react-navigation-stack
- [ ] react-navigation-tabs

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| "@react-navigation/native": "^6.0.2"                      |
| "@react-navigation/native-stack": "^6.0.5" |
| "react-native": "0.64.2" |

**Comment by bviebahn** [comment]
Same problem here. I tried to work around it by using the Header component from @react-navigation/elements which has a headerTitleAlign prop. But I'm having some other problems with this component, like properly setting the header background, and it would be nice to be able to center the title without having to manually recreate the whole header.

**Comment by anwersolangi** [comment]
Same problem here! i even cant find any documentation in the latest docs related to align the title center... anyone who solved the issue?
