### ISSUE TITLE
Hiding tab bar in specific screens

### ISSUE THREAD

**Issue by robertototti** [react-navigation/react-navigation#9833]
### Current behavior

Hey everyone)
I use example from documentation for [hiding tab bar in specific screens](https://reactnavigation.org/docs/hiding-tabbar-in-screens)

```
function HomeTabs() {
  return (
    <Tab.Navigator>
      <Tab.Screen name="Home" component={Home} />
      <Tab.Screen name="Feed" component={Feed} />
      <Tab.Screen name="Notifications" component={Notifications} />
    </Tab.Navigator>
  );
}

function App() {
  return (
    <Stack.Navigator>
      <Stack.Screen name="Home" component={HomeTabs} />
      <Stack.Screen name="Profile" component={Profile} />
      <Stack.Screen name="Settings" component={Settings} />
    </Stack.Navigator>
  );
}
```

### Expected behavior

i expect to see the tab screen component on web, in ios and android work fine

### Reproduction

https://snack.expo.dev/E2E_Rk8R8

### Platform

- [ ] Android
- [ ] iOS
- [X] Web
- [ ] Windows
- [X] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

"@react-navigation/bottom-tabs": "^6.0.4",
    "@react-navigation/native": "^6.0.2",
    "@react-navigation/native-stack": "^6.0.4",
    "@react-navigation/stack": "^6.0.6",
    "axios": "^0.21.1",
    "expo": "~42.0.1",
    "expo-linking": "~2.3.1",
    "expo-status-bar": "~1.0.4",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz",
    "react-native-gesture-handler": "^1.10.3",
    "react-native-safe-area-context": "3.2.0",
    "react-native-screens": "~3.4.0",
    "react-native-web": "~0.13.12"

**Comment by satya164** [comment]
This is fixed in latest version of `@react-navigation/native-stack`. Please upgrade.
