### ISSUE TITLE
[v6] drawer background color transparent not working

### ISSUE THREAD

**Issue by vemarav** [react-navigation/react-navigation#9834]
### Current behavior

```
<Drawer.Navigator
  screenOptions={{
    drawerStyle: {
      backgroundColor: 'transparent',
      width: 240,
    },
  }}
>
  {/* screens */}
</Drawer.Navigator>
```

renders white background

### Expected behavior

should render transparent background

### Reproduction

NA

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/drawer               | 6.1.3
| @react-navigation/stack                | 6.0.6

**Comment by systemidx** [comment]
I am also experiencing this with StackNavigator. The following code renders a gray background.

```
import React from 'react'
import { ImageBackground, StyleSheet, View } from 'react-native'
import { createStackNavigator, StackNavigationOptions } from '@react-navigation/stack'

import { Routes } from './routes'

const Stack = createStackNavigator()
const image = require('@src/assets/images/login-background.png')

export function UnauthenticatedRoutes() {
    return (
        <View style={styles.container}>
            <ImageBackground source={image} resizeMode="cover" style={styles.image}>
                <Stack.Navigator initialRouteName={Routes.Login.RouteName} screenOptions={getScreenOptions()}>
                    <Stack.Screen name={Routes.Login.RouteName} options={Routes.Login.Options as StackNavigationOptions} component={Routes.Login.Component} />
                    <Stack.Screen
                        name={Routes.Registration.RouteName}
                        options={Routes.Registration.Options as StackNavigationOptions}
                        component={Routes.Registration.Component}
                    />
                </Stack.Navigator>
            </ImageBackground>
        </View>
    )
}

function getScreenOptions(): StackNavigationOptions {
    return {
        cardStyle: {
            backgroundColor: 'transparent',
            //flex: 1,
            //alignItems: 'center',
            //justifyContent: 'center',
        },
    }
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
        // width: '100%',
        // height: '100%',
    },
    image: {
        flex: 1,
        // width: '100%',
        // height: '100%',
        // alignItems: 'center',
    },
})
```

Versions:
```
        "@react-navigation/bottom-tabs": "^6.0.5",
        "@react-navigation/drawer": "^6.1.4",
        "@react-navigation/elements": "^1.1.0",
        "@react-navigation/material-top-tabs": "^6.0.2",
        "@react-navigation/native": "^6.0.2",
        "@react-navigation/stack": "^6.0.7",
```

**Comment by IljaDaderko** [comment]
Same issue with nested stack navigator. I literary set

```
cardStyle: {
            backgroundColor: 'transparent'
}
```

as well as equivalent in `options` on all my Navigators and screens and for some reason I still see that light grayish screen. Feels like there is something in-between the layers. Wasn't an issue on v5. I also tried with `presentation: 'transparentModal'` to ensure previous screen remains behind, but still got white background

**Comment by systemidx** [comment]
I ended up having to use NativeStack in lieu of the regular Stack lib and that ended up working.

**Comment by IljaDaderko** [comment]
It appears that setting backgroundColor through `Stack.Screen` options is not working

**Comment by systemidx** [comment]
Using `@react-navigation/native-stack`, this works for me:

```
import React from 'react'
import { createNativeStackNavigator, NativeStackNavigationOptions } from '@react-navigation/native-stack'

import { Routes } from './routes'

const Stack = createNativeStackNavigator()

export function UnauthenticatedRoutes() {
    return (
        <Stack.Navigator initialRouteName={Routes.Login.RouteName} screenOptions={getScreenOptions()}>
            <Stack.Group>
                <Stack.Screen name={Routes.Login.RouteName} options={Routes.Login.Options as NativeStackNavigationOptions} component={Routes.Login.Component} />
                <Stack.Screen
                    name={Routes.Registration.RouteName}
                    options={Routes.Registration.Options as NativeStackNavigationOptions}
                    component={Routes.Registration.Component}
                />
            </Stack.Group>
        </Stack.Navigator>
    )
}

function getScreenOptions(): NativeStackNavigationOptions {
    return {
        contentStyle: {
            backgroundColor: 'transparent',
        },
    }
}
```

**Comment by IljaDaderko** [comment]
Native stack solves it partially, things like `cardStyleInterpolator` don't work with it

**Comment by dgranahan** [comment]
This is still a problem for me. Commenting to keep this issue open.

```
    "@react-navigation/bottom-tabs": "^6.0.7",
    "@react-navigation/native": "^6.0.4",
    "@react-navigation/stack": "^6.0.9",
```

**Comment by dgranahan** [comment]
This is still a problem for me. Commenting to keep this issue open.

```
    "@react-navigation/bottom-tabs": "^6.0.7",
    "@react-navigation/native": "^6.0.4",
    "@react-navigation/stack": "^6.0.9",
```

**Comment by nyelmer** [comment]
@dgranahan putting `overlayColor: "transparent",` into `screenOptions` seems to be working 

```
"@react-navigation/drawer": "^6.1.8",
"@react-navigation/native": "^6.0.6",
"@react-navigation/native-stack": "^6.2.5",
```

```
<Drawer.Navigator
    screenOptions={{
        overlayColor: "transparent",
        drawerType: "slide",
        drawerStyle: { flex: 1, width: "70%", paddingRight: 20, backgroundColor: "transparent" },
        sceneContainerStyle: { backgroundColor: "transparent" },
        headerShown: false
        }}
>
```

**Comment by carlosmrivera** [comment]
> @dgranahan putting `overlayColor: "transparent",` into `screenOptions` seems to be working
> 
> ```
> "@react-navigation/drawer": "^6.1.8",
> "@react-navigation/native": "^6.0.6",
> "@react-navigation/native-stack": "^6.2.5",
> ```
> 
> ```
> <Drawer.Navigator
>     screenOptions={{
>         overlayColor: "transparent",
>         drawerType: "slide",
>         drawerStyle: { flex: 1, width: "70%", paddingRight: 20, backgroundColor: "transparent" },
>         sceneContainerStyle: { backgroundColor: "transparent" },
>         headerShown: false
>         }}
> >
> ```

This worked for me! Thanks.

**Comment by buddyeorl** [comment]
in our app
```
     "react-native": "0.68.5",
     "expo": "^45.0.0",
    "@react-navigation/bottom-tabs": "^5.11.9",
    "@react-navigation/native": "^5.9.4",
    "@react-navigation/stack": "^5.14.4",
```
I fixed this by disabling `react-native-screens` by adding this to the `App.tsx` or `App.js`

import { enableScreens } from 'react-native-screens';
enableScreens(false);

Reference in the Highlight section https://blog.expo.dev/expo-sdk-41-12cc5232f2ef
and here https://www.npmjs.com/package/react-native-screens

**Comment by fyunusyildiz** [comment]
Hi everyone. 

I set `presentation: 'transparentModal'` to StackNavigator screenOptions and it worked for me.

Here is my code: 

`<NavigationContainer>
      <Stack.Navigator screenOptions={{ presentation: "transparentModal" }}>
        <Stack.Screen
          options={{ headerShown: false }}
          name="EnableLocation"
          component={EnableLocation}
        />
        <Stack.Screen
          options={{ headerShown: false }}
          name="HomeNavigator"
          component={HomeNavigator}
        />
      </Stack.Navigator>
    </NavigationContainer>`

my drawer is inside HomeNavigator.
