### ISSUE TITLE
TypeScript Definition for Linking is incorrect v6

### ISSUE THREAD

**Issue by himrocks33** [react-navigation/react-navigation#9836]
### Current behavior

The Type Definition does not support a valid linking configuration. Provide the following to a the linking property and it throws a type definition error.

import * as Linking from 'expo-linking';

export default {
  prefixes: [Linking.makeUrl('/')],
  config: {
    screens: {
      Root: {
        screens: {
          Home: {
            screens: {
              Home: 'Home',
              Details: 'Details'
            },
          },
          EventNews: {
            screens: {
              EventNews: 'EventNews',
            },
          },
          About: {
            screens: {
              About: 'About',
            },
          },
          PostEvent: {
            screens: {
              PostEvent: 'PostEvent',
            },
          },
        },
      },
      NotFound: '*',
    },
  },
};
`

### Expected behavior

The type definition supports valid linking configuration.

### Reproduction

https://snack.expo.dev/@bwalton12011993/anxious-tortilla

### Platform

- [ ] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |  6.0.2
| @react-navigation/bottom-tabs          | 6.0.5
| @react-navigation/drawer               | 6.1.4
| @react-navigation/stack                | 6.0.7
| expo                                   | 42.0.1

**Comment by Hirbod** [comment]
Not stale
