### ISSUE TITLE
[v6] Drawer Navigation cannot be created

### ISSUE THREAD

**Issue by efefurkankarakaya** [react-navigation/react-navigation#9843]
### Current behavior

Hello,

Today I ran into a bug with Drawer. I can't create Drawer Navigator whilst able to create and use Tab and Stack Navigators as well.

```
 ERROR  TypeError: null is not an object (evaluating '_ReanimatedModule.default.createNode')
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect. 
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect. 
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
```

### Expected behavior

Being able to create Drawer Navigator.

### Reproduction

https://gist.github.com/efefurkankarakaya/830080bd6c57d78d3177169d7c3d8531

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | ^6.0.2
| @react-navigation/bottom-tabs          | ^6.0.5
| @react-navigation/drawer               | ^6.1.4
| @react-navigation/material-bottom-tabs |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                |
| @react-navigation/native-stack         | ^6.1.0
| react-native-safe-area-context         | ^3.3.0
| react-native-screens                   | ^3.5.0
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           |
| expo                                   |
| node                                   | v16.6.2
| npm or yarn                            | 7.20.6

**Comment by efefurkankarakaya** [comment]
As a solution, Drawer is requiring `"react-native-gesture-handler": "^1.10.3"` and "react-native-reanimated": "^1.13.2"` and document does not provide any information that dependencies for v6.

**Warning:** Latest `react-native-reanimated` package is not working properly, same issue occurs.

**Comment by ridvanaltun** [comment]
> As a solution, Drawer is still requiring `"react-native-gesture-handler": "^1.10.3"` and `"react-native-reanimated": "^1.13.2"` and the document does not provide any information that dependencies for v6.
> 
> **Warning:** Latest `react-native-reanimated` package is not working properly, same issue occurs.

Thanks! I was have the same issue.

**Comment by satya164** [comment]
>  the document does not provide any information that dependencies for v6

This is clearly documented in the installation command in the page for drawer navigator: https://reactnavigation.org/docs/drawer-navigator/

**Comment by efefurkankarakaya** [comment]
> > the document does not provide any information that dependencies for v6
> 
> This is clearly documented in the installation command in the page for drawer navigator: https://reactnavigation.org/docs/drawer-navigator/

It wasn't documented and / or routed to related installation in that page: https://reactnavigation.org/docs/drawer-based-navigation

**Comment by jeremyrajan** [comment]
Same issue is happening for me, 
![image](https://user-images.githubusercontent.com/2890683/131210095-2b193227-f851-4a16-bb76-08e745712ce4.png)

**Comment by vipulchakravarthy** [comment]
![Screenshot (4)](https://user-images.githubusercontent.com/41899503/131216568-0e94283e-4684-4c8a-b279-7f45638704ad.png)
I am getting the exact same error. Any quick fix for this issue?

**Comment by rzylim** [comment]
A tip for fellow Nx workspace users who's encountering this problem:
It's necessary to manually add some of the dependencies in the react native app's package.json as well. I believe they aren't automatically added on run-android since we do not explicitly import them in the app.
Adding `"react-native-reanimated": "*"` resolved this issue for me.
Adding `"react-native-safe-area-context": "*", "react-native-screens": "*"` resolved a couple other issues as well.
