### ISSUE TITLE
How to preserve state scroll position with tabs

### ISSUE THREAD

**Issue by umardevid** [react-navigation/react-navigation#9845]
### Current behavior

I have the Quran application that have great tab and scrolling behavior
that not reseted  current list position 

for example we have 2 tabs and if we scrolling in first tab until list of number 6 doing this will hidden the appbar/header and pinned top tabs/tab bar to the top and put list number 6 to last scroll position

then we switched to second tab and doing scrolling up e.g until number 8 of list and doing scrolling down until number 0 of list this will make appbar shown to normal again

and we switced to first tab again I want last scrolling in the first tab still number 6 event if we show hide the appbar/header from another tabs

like this apps https://play.google.com/store/apps/details?id=com.andi.alquran.id&hl=en_US&gl=US

how to do that?

### Expected behavior

make scroll position not reset and still in current scrolling position if we doing scrolling in anther tabs

### Reproduction

https://github.com/umardevid/react-navigation

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [X] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/material-top-tabs    | latest

**Comment by brentvatne** [comment]
that's not a reproducible example, please read https://stackoverflow.com/help/minimal-reproducible-example for more information on how to prepare one and then open an issue with it. much appreciated
