### ISSUE TITLE
Modals has no offset top by default

### ISSUE THREAD

**Issue by max-frai** [react-navigation/react-navigation#9847]
### Current behavior

When I open some ios modal, it does not have offset from top by default and is overlapping non-safe area. When I touch the modal it "jumps" to normal position with offset from top.

Here is modal from image picker from expo:

![img](https://user-images.githubusercontent.com/24208746/130220223-27f82412-39c9-4f2a-b785-165a57263329.jpg)

Here is jump offset video:

https://user-images.githubusercontent.com/24208746/130230792-936c9890-df23-4a80-b6ea-9a048ad5e3c3.mov

### Expected behavior

Opened modal should have offset top by default initially.

### Reproduction

https://github.com/max-frai/ExpoModalsTest

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/bottom-tabs          | 6.0.5
| @react-navigation/stack                | 6.0.7
| react-native-safe-area-context         | 3.2.0
| react-native-screens                   | 3.4.0
| react-native                           | 0.63.0
| expo                                   | 42.0.1
| node                                   | 16.6.0
| npm                            | 7.19.1

**Comment by satya164** [comment]
> When I open some ios modal
> Here is modal from image picker from expo

How is this a React Navigation issue?
