### ISSUE TITLE
Safe area view not working properly in iphone 12 series

### ISSUE THREAD

**Issue by vishal1198** [react-navigation/react-navigation#9855]
### Current behavior

These kind of issues were already been raised as an issue and those issues got solutions and those issues where closed now.

 But my observation is most of the issues says that need to upgrade the packages that are related to react-navigation like react-navigation, react-navigation-stack, react-navigation-drawer, react-navigation-tabs or add react-native-safe-area-context, react-native-safe-area-view.

 But I couldn't solve the issue even though I implemented all the ways that are mentioned in closed issues.

 Below I have attached the sample reference screenshot and the git issue link that I tried to fix my issue.
[https://github.com/react-navigation/react-native-safe-area-view/issues/136](url)
[https://github.com/react-navigation/react-navigation/issues/8972](url)
[https://github.com/react-navigation/react-native-safe-area-view/issues/138](url)
[https://github.com/react-navigation/react-navigation/issues/9025](url)
<img width="811" alt="Screen Shot 2021-08-23 at 12 06 59 AM" src="https://user-images.githubusercontent.com/34634564/130366243-4992fa00-15a6-40a1-8c3b-586e6af85a75.png">

Kindly someone do the needful to get out of this issue. Thanks in advance folks.

### Expected behavior

the expected behaviour is supposed to be like all the iphone devices should display an same UI.

### Reproduction

can verify the image attached

### Platform

- [ ] Android
- [X] iOS
- [ ] Web

### Packages

- [X] react-navigation-drawer
- [X] react-navigation-stack
- [X] react-navigation-tabs

### Environment

Packages I use:

  "react-navigation": "^4.0.10",
  "react-navigation-drawer": "^2.3.3",
  "react-navigation-stack": "^1.9.4",
  "react-navigation-tabs": "^2.5.6",
  "react-native-screens": "^2.0.0-alpha.4",

**Comment by vishal1198** [comment]
@github-actions



the above solution doesnt work in my case.

**Comment by vishal1198** [comment]
**List of attempts**

1. Tried adding safeAreaView for the whole app. It fixed in iphone 12 but all other devices got issue with same ui.
2. Tried upgrading 
        -  react-navigation-drawer from 2.3.3 to 2.6.0
        - react-navigation-stack from 1.9.4 to 2.10.0
        - react-navigation from  4.0.10 to 4.4.3
     still behaved the same.
3. Tried adding react-native-safe-area-view and react-native-safe-area-context and used safe area view, still behaved the same.

**Comment by satya164** [comment]
`react-native-safe-area-view` is deprecated. use https://github.com/th3rdwave/react-native-safe-area-context

also don't open issues for libraries other than react navigation in this repo.

**Comment by vishal1198** [comment]
> `react-native-safe-area-view` is deprecated. use https://github.com/th3rdwave/react-native-safe-area-context
> 
> also don't open issues for libraries other than react navigation in this repo.

I have also tried react-native-safe-area-context ....even though I didnt get any fix. If you can please guide me to fix the issue.
