### ISSUE TITLE
Documentation Proposal: By default, demonstrate how how to implement the Navigation stack in other `.js` files

### ISSUE THREAD

**Issue by hb-webdev** [react-navigation/react-navigation#9867]
### Current behavior

_(I couldn't find where to make documentation suggestions. After the frustration over this boiling for so long, I guess I'm too exhausted to care about facing the condescension of putting this here.)_

All the screens in the Snack examples are all contained within a single `App.js` file (notably in the Snacks in the "[Hello React Navigation](https://reactnavigation.org/docs/hello-react-navigation)" and "[Moving between screens](https://reactnavigation.org/docs/navigating)" documentation pages). I've been tearing my hair out for some hours now, trying to figure out how you'd break up the example Snacks, like the one below, into separate `.js` files so I can navigate between screens, multiple layers deep, in my app. (Example):

[`Screen1.js`] -> [`Screen2.js`] -> [`Screen3.js`]

Assuming the navigation stack resides in `Screen1.js`, what exactly would I need to import in `Screen2.js` to be able to navigate to `Screen1.js` or `Screen3.js`? What would that code look like? What if I instead wanted to put my Navigation stack in a completely separate `NavigationService.js` file that I import into each file? How could I implement that?

I feel like the default behavior for building apps is to use a separate `.js` file for each screen, and I'm disheartened trying to figure out how to implement navigation between files (using functional components)--what I feel would be the default goal of using this library.

[Example Snack](https://snack.expo.io/?platform=android&name=Hello%20React%20Navigation%20%7C%20React%20Navigation&dependencies=%40expo%2Fvector-icons%40*%2C%40react-native-community%2Fmasked-view%40*%2Creact-native-gesture-handler%40*%2Creact-native-pager-view%40*%2Creact-native-paper%40%5E4.7.2%2Creact-native-reanimated%40*%2Creact-native-safe-area-context%40*%2Creact-native-screens%40*%2Creact-native-tab-view%40%5E3.0.0%2C%40react-navigation%2Fbottom-tabs%406.0.4%2C%40react-navigation%2Fdrawer%406.1.3%2C%40react-navigation%2Felements%401.0.4%2C%40react-navigation%2Fmaterial-bottom-tabs%406.0.4%2C%40react-navigation%2Fmaterial-top-tabs%406.0.2%2C%40react-navigation%2Fnative-stack%406.0.5%2C%40react-navigation%2Fnative%406.0.2%2C%40react-navigation%2Fstack%406.0.6&hideQueryParams=true&sourceUrl=https%3A%2F%2Freactnavigation.org%2Fexamples%2F6.x%2Fpop-to-top.js):

```
import * as React from 'react';
import { Button, View, Text } from 'react-native';
import { NavigationContainer } from '@react-navigation/native';
import { createNativeStackNavigator } from '@react-navigation/native-stack';

function HomeScreen({ navigation }) {
  return (
    <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
      <Text>Home Screen</Text>
      <Button
        title="Go to Details"
        onPress={() => navigation.navigate('Details')}
      />
    </View>
  );
}

function DetailsScreen({ navigation }) {
  return (
    <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
      <Text>Details Screen</Text>
      <Button
        title="Go to Details... again"
        onPress={() => navigation.push('Details')}
      />
      <Button title="Go to Home" onPress={() => navigation.navigate('Home')} />
      <Button title="Go back" onPress={() => navigation.goBack()} />
      <Button
        title="Go back to first screen in stack"
        onPress={() => navigation.popToTop()}
      />
    </View>
  );
}

const Stack = createNativeStackNavigator();

function App() {
  return (
    <NavigationContainer>
      <Stack.Navigator initialRouteName="Home">
        <Stack.Screen name="Home" component={HomeScreen} />
        <Stack.Screen name="Details" component={DetailsScreen} />
      </Stack.Navigator>
    </NavigationContainer>
  );
}

export default App;
```

### Expected behavior

The documentation outlines what exactly you need to import or code out, in order to implement navigation between screens

### Reproduction

https://snack.expo.io/?platform=android&name=Hello%20React%20Navigation%20%7C%20React%20Navigation&dependencies=%40expo%2Fvector-icons%40*%2C%40react-native-community%2Fmasked-view%40*%2Creact-native-gesture-handler%40*%2Creact-native-pager-view%40*%2Creact-native-paper%40%5E4.7.2%2Creact-native-reanimated%40*%2Creact-native-safe-area-context%40*%2Creact-native-screens%40*%2Creact-native-tab-view%40%5E3.0.0%2C%40react-navigation%2Fbottom-tabs%406.0.4%2C%40react-navigation%2Fdrawer%406.1.3%2C%40react-navigation%2Felements%401.0.4%2C%40react-navigation%2Fmaterial-bottom-tabs%406.0.4%2C%40react-navigation%2Fmaterial-top-tabs%406.0.2%2C%40react-navigation%2Fnative-stack%406.0.5%2C%40react-navigation%2Fnative%406.0.2%2C%40react-navigation%2Fstack%406.0.6&hideQueryParams=true&sourceUrl=https%3A%2F%2Freactnavigation.org%2Fexamples%2F6.x%2Fpop-to-top.js

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |
| @react-navigation/native-stack         |

**Comment by satya164** [comment]
The documentation assumes you're already familiar with JavaScript and React. There are a lot of resources available already to learn JavaScript, and we have few links to learn React & React Native in the Getting Started guide. I suggest you make yourself familiar with the language first, otherwise, you'll have a hard time understanding the docs. This is not only about separate files, it's just one of the parts of the language.
