### ISSUE TITLE
"Found screens with the same name nested inside one another" warning on v6

### ISSUE THREAD

**Issue by outaTiME** [react-navigation/react-navigation#9868]
### Current behavior

The following warning is displayed, "Found screens with the same name nested inside one another." When there are screens with the same name, in version 5 this did not happen.

Even the examples in the documentation throw this warning as well (only when run locally, not in snack).

In some cases this is a very useful pattern to have repeated names, especially in tab navigation where each tab has a screen with a stack and the first screen of this is called the same way as the tab (as in several of the examples in the documentation).

<img width="479" alt="image" src="https://user-images.githubusercontent.com/140472/130719911-2f544244-6a54-4b15-8b77-45eb6c11944d.png">

### Expected behavior

Do not throw a warning or indicate what would be the best way to implement the following use case, avoiding the excess of different names in each of the screens.

Also, I think it is something that should be documented in the upgrade guide from version 5.

### Reproduction

https://snack.expo.dev/@outatime/navigating-without-the-navigation-prop-|-react-navigation
https://snack.expo.dev/@outatime/nesting-navigators-|-react-navigation

### Platform

- [ ] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.0.2
| @react-navigation/bottom-tabs          | 6.0.5
| @react-navigation/stack                | 6.0.7
| expo                                   | 42.0.3

**Comment by dylancom** [comment]
As this pattern is encouraged by the docs: https://reactnavigation.org/docs/tab-based-navigation#a-native-stack-navigator-for-each-tab, I also find it weird that it's throwing a warning.

**Comment by satya164** [comment]
> As this pattern is encouraged by the docs

It's an oversight. There's no text encouraging to write specifically use the same screen name for parent and child screens. Pull requests are welcome to update the docs.

As the warning says, writing such code is confusing and we recommend using unique names.

**Comment by astrahov** [comment]
```
Stack.Navigator
- Home (Tab.Navigator)
  - Feed (Stack.Navigator)
    - Feed (Screen)
    - Profile (Screen)
  - Settings (Stack.Navigator)
    - Settings (Screen)
    - Profile (Screen)
    - About (Screen)
```

@satya164, it turns out that such a structure needs to be changed in one of the following ways?

```
Stack.Navigator
- Home (Tab.Navigator)
  - FeedTab (Stack.Navigator)
    - Feed (Screen)
    - Profile (Screen)
  - SettingsTab (Stack.Navigator)
    - Settings (Screen)
    - Profile (Screen)
    - About (Screen)
```

```
Stack.Navigator
- Home (Tab.Navigator)
  - Feed (Stack.Navigator)
    - FeedMain (Screen)
    - Profile (Screen)
  - Settings (Stack.Navigator)
    - SettingsMain (Screen)
    - Profile (Screen)
    - About (Screen)
```
