### ISSUE TITLE
Modal presentation "transparentModal" cannot pull to close

### ISSUE THREAD

**Issue by NguyenHoangMinhkkkk** [react-navigation/react-navigation#9873]
### Current behavior

    <Stack.Group
      screenOptions={{
        presentation: 'transparentModal',
        headerShown: false,
      }}
    >
      <Stack.Screen name="alertModal" component={modalScreen} />
    </Stack.Group>

``
Curent behavior is the screen in stack group with screenOptions presentation="transparentModal" cannot swipe down or pull down to close like modal screen before.

### Expected behavior

I am asking about any docs about these behavior for pulling down to close
Or the transparentModal itself Expected to be using with this the right behavior ?

### Reproduction

https://github.com/NguyenHoangMinhkkkk/snack-nav-v6

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |^6.0.2
| @react-navigation/bottom-tabs          |6.0.5
| @react-navigation/drawer               |--
| @react-navigation/material-bottom-tabs |--
| @react-navigation/material-top-tabs    |--
| @react-navigation/stack                |--
| @react-navigation/native-stack         |6.1.0
| react-native-safe-area-context         |3.3.0
| react-native-screens                   |--
| react-native-gesture-handler           |1.10.3
| react-native-reanimated                |2.2.0
| react-native-tab-view                  |--
| react-native-pager-view                |--
| react-native                           |0.64.2
| expo                                   |--
| node                                   |
| npm or yarn                            |yarn

**Comment by samhv** [comment]
I need it working too

**Comment by samjtozer** [comment]
Bump. Repro: https://snack.expo.dev/@samtozer96/blessed-raspberries

**Comment by satya164** [comment]
https://reactnavigation.org/docs/stack-navigator/#gestureenabled

@samjtozer it's not supported in native-stacl

**Comment by samjtozer** [comment]
> https://reactnavigation.org/docs/stack-navigator/#gestureenabled
> 
> @samjtozer it's not supported in native-stacl

Great thanks. I've switched to `stack` and all works as expected.
