### ISSUE TITLE
React Navigation blurs TextInput with autoFocus:true on mount

### ISSUE THREAD

**Issue by cwhenderson20** [react-navigation/react-navigation#9875]
### Current behavior

A `TextInput` with `autoFocus={true}` that renders within a stack screen component is immediately blurred after the initial auto focus. This only occurs on Android.

The provided snack reproduction provides two exports in the main `App.js` file: 
- the default export is `AppWithNavigation` to show how the screen behaves when rendered within a stack
- a secondary export that can be swapped in to show how the screen behaves when rendered outside of any navigation context

As you'll be able to see, the input renders, focuses, and then immediately blurs when rendering within a stack (check the state log beneath the input). When rendering outside of a stack, the input renders and is focused—no blur.

A "workaround" (I hesitate to call it that because it would be pretty ridiculous to need to include in a production app) is to prevent the `TextInput` from rendering until after a short delay (100ms worked fine) using `setTimeout`.

Setting `keyboardHandlingEnabled: false` seems to have no effect.

I recently noticed this behavior in our app after updating all @react-navigation dependencies to their latest 6.x versions from their pre-release 6.x-next counterparts. For what it's worth, the issue stops after checking out the commit before the update. I tried creating a snack with those versions specified, but for whatever reason, the issue doesn't resolve when using expo. If it helps, those versions where it's working in production are:

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.0.0-next.13
| @react-navigation/stack                | 6.0.0-next.25
| react-native-safe-area-context         | 3.2.0
| react-native-screens                   | 3.4.0
| react-native-gesture-handler           | 1.10.3
| react-native-reanimated                | 1.13.0
| react-native                           | 0.64.1

### Expected behavior

Inputs with `autoFocus={true}` should not blur when the screen mounts.

### Reproduction

https://snack.expo.dev/@cwhenderson20/react-navigation-breaks-textinput-autofocus

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.0.2
| @react-navigation/stack                | 6.0.7
| react-native-safe-area-context         | 3.2.0
| react-native-screens                   | 3.4.0
| react-native-gesture-handler           | 1.10.3
| react-native-reanimated                | 1.13.0
| react-native                           | 0.64.1

**Comment by Titozzz** [comment]
Can confirm that new behavior :(

**Comment by martinezguillaume** [comment]
Same problem here ! only on android, the input focus briefly ou mount (like 2 milliseconds) then blurs immediately

```
    "@react-navigation/native": "^6.0.2",
    "@react-navigation/native-stack": "^6.1.0",
    "react-native-screens": "~3.8.0",
```

**Comment by jzxchiang1** [comment]
Workaround is to do this:

```
  useEffect(() => {
    setTimeout(() => textInputRef.current?.focus(), 100);
  }, []);
  ```

**Comment by jzxchiang1** [comment]
FYI it happens on React Navigation v5 as well.

**Comment by aretesoftware** [comment]
This is happening for me on iOS using material-top-tabs. I can reproduce every time by hitting the tab key on the keyboard when using a simulator, or when using a wireless keyboard. After that, every TextInput on the screen will automatically blur when focused.

It cannot be reproduced if I remove the tabs from the screen, so it seems likely the tabs are causing the issue.

    "@react-navigation/bottom-tabs": "^6.0.9",
    "@react-navigation/material-top-tabs": "^6.1.1",
    "@react-navigation/native": "^6.0.8",
    "@react-navigation/native-stack": "^6.1.0",
    "@react-navigation/stack": "^6.1.1",

**Comment by rishabhsaxena** [comment]
This workaround seemed to work for me:
```
  useEffect(() => {
    InteractionManager.runAfterInteractions(() => {
      inputRef.current?.focus();
    });
  }, []);
```

**Comment by MuhammadRafeh** [comment]
In newer version this bug has been solved. If you are still facing this then just give ref to TextInout component and then call Focus method on ref in the component's Mount Function.

Just simple as that.

**Comment by cwhenderson20** [comment]
@rishabhsaxena yeah, this is what I ended up doing in my app, too. I wrapped it into a hook for ease of use:

```tsx
import { useEffect, useRef } from 'react';
import { InteractionManager, Platform, TextInput } from 'react-native';

export default function useAutoFocusInput(
  autoFocus = Platform.OS === 'android'
) {
  const ref = useRef<TextInput>(null);

  useEffect(() => {
    const handle = InteractionManager.runAfterInteractions(() => {
      if (ref.current && autoFocus) {
        ref.current.focus();
      }
    });

    return handle.cancel;
  }, [autoFocus]);

  return {
    ref,
    // this is used as prop on the component; it is therefore the negated value
    // of whether or not this hook will handle the auto-focusing
    autoFocus: !autoFocus,
  };
}
```
**Usage**
```tsx
const autoFocusProps = useAutoFocusInput();

<TextInput {...autoFocusProps} />
```

However, I'd obviously prefer not having to use such a workaround.

**Comment by jzxchiang1** [comment]
InteractionManager worked for me too.

**Comment by zhiqingchen** [comment]
Same problem in RN 0.67 for Android

**Comment by zhiqingchen** [comment]
> In newer version this bug has been solved. 
> 
> If you are still facing this then just give ref to TextInout component and then call Focus method in the component's Mount Function. 
> 
> ```js
> Ref.current.focus()
> ```
> 
> Just simple as that. 

@MuhammadRafeh hi, you mean which version?

**Comment by ninety19** [comment]
import { createNativeStackNavigator } from '@react-navigation/native-stack';
const Stack = createNativeStackNavigator();
instead of
import { createStackNavigator } from '@react-navigation/stack';
const Stack = createStackNavigator();

it worked for me

**Comment by Bardiamist** [comment]
Looks it happens when `headerShown: false` or `headerTransparent: true`

**Comment by Nerostalgeek** [comment]
> ```js
> ```js
> Ref.current.focus()
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> ```

Also in RN 0.68

**Comment by taylorkline** [comment]
This is now fixed by upgrading to a version of react-native-screens with software-mansion/react-native-screens#1214, e.g. `3.17.0`.
