### ISSUE TITLE
[v6] useDrawerProgress() gives undefined on its value property i.e SharedValue

### ISSUE THREAD

**Issue by MuhammadRafeh** [react-navigation/react-navigation#9878]
### Current behavior

I want to translate the drawer's Content by the following way that mentioned in documentation But unable to do!

```js
function CustomDrawerContent(props) {
  const progress = useDrawerProgress(); 

 console.log(progress.value)  // ERROR HERE -> progress.value gives undefined

  const translateX = Animated.interpolate(progress.value, {
    inputRange: [0, 1],
    outputRange: [-100, 0],
  });

  return (
    <Animated.View style={{ transform: [{ translateX: translateX.value }] }}>
      {/* ... drawer contents */}
    </Animated.View>
  );
}
```
useDrawerProgress() giving undefined on his value property whenever we open or close drawer instead of animatedValue of number/float!!!

I saw this problem on android and web.

### Expected behavior

import {
  useDrawerProgress
} from '@react-navigation/drawer';

const progress = useDrawerProgress();

**progress.value should return some number/float instead of undefined**

### Reproduction

https://snack.expo.dev/@muhammadrafeh/drawer-animated-problem-reproduce

### Platform

- [X] Android
- [ ] iOS
- [X] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native |  6.0.2
| @react-navigation/bottom-tabs          |  6.0.5
| @react-navigation/drawer               | 6.1.4
| react-native-safe-area-context  | 3.2.0
| react-native-screens    |  3.4.0   
| react-native-gesture-handler  | 1.10.3
| react-native-reanimated     |     2.2.0
| react-native-tab-view       |   3.1.1
| react-native-pager-view     |   5.0.12
| react-native       |      0.63.3
| expo   |     42.0.1
| node         |    14.17.5
| yarn        |  1.22.10

**Comment by heikkimantere** [comment]
I would like to solve this as well. Also, the documentation states that `<Drawer.Navigator>` has a `drawerContent` prop, which is an object containing a prop `progress` — but `progress` is not included in `drawerContent`!

**Comment by MuhammadRafeh** [comment]
Yes! We need to fix this Bug!

**Comment by Fapalz** [comment]
I got the same problem!
`drawerContent` are missing a property `progress`

**Comment by MuhammadRafeh** [comment]
Any progress about this Bug?

**Comment by satya164** [comment]
Drawer progress is not a shared value if you're not using Reanimated 2. If you want a shared value, then configure Reanimated 2 in your project.

**Comment by MuhammadRafeh** [comment]
@satya164 its a shared value, for your kind information I am using react-native-reanimated 2!

**Comment by heikkimantere** [comment]
@satya164 I'm using reanimated 2 as well, and the prop `progress` is missing.

**Comment by satya164** [comment]
Please provide a repro with Reanimated 2.

**Comment by MuhammadRafeh** [comment]
@satya164 I think you such kind a deaf person, You are closing issues without investigating. WTF?

I already provided that, Providing again below;

https://snack.expo.dev/@muhammadrafeh/drawer-animated-problem-reproduce

**Comment by satya164** [comment]
@MuhammadRafeh thanks for the insult. can you kindly explain to me how am I supposed to configure and check reanimated 2 in the snack you provided?

**Comment by MuhammadRafeh** [comment]
@satya164 Open up snack and after opening up on mobile's expo, open up drawer and notice in console that progress.value is printing out undefined intead of floating/number!

It has implemented reanimated 2 !

**Comment by MuhammadRafeh** [comment]
Ok, let me reproduce quickly, I'll send you then.

**Comment by nvdnvd00** [comment]
This is my workaround:

`const WrapDrawerScreen = (props) => {

	const isDrawerOpen = useDrawerStatus();
	const sv = useSharedValue(0);

	useUpdateEffect(() => {
		if (isDrawerOpen === 'open') {
			sv.value = withTiming(1);
		} else {
			sv.value = withTiming(0);
		}
	}, [isDrawerOpen]);

	const screenStyle = useAnimatedStyle(() => {
		const scaleY = interpolate(sv.value, [0, 0.5, 1], [1, 0.9, 0.85], {
			extrapolateRight: Extrapolate.CLAMP,
		});
		const borderRadius = interpolate(sv.value, [0, 1], [1, 20], {
			extrapolateRight: Extrapolate.CLAMP,
		});
		return {
			transform: [
				{
					scaleY,
				},
			],
			borderRadius,
		};
	});
	return (
		<Animated.View style={[styles.animatedView, screenStyle]}>
			<Drawer.Screen {...props} />
		</Animated.View>
	);
};`
![CleanShot 2021-10-08 at 05 01 47](https://user-images.githubusercontent.com/17423070/136468205-4f1430e9-627a-4d36-8c17-5540213d0348.gif)

**Comment by zoobibackups** [comment]
> @react-navigation/native - 6.0.6 @react-navigation/drawer - 6.1.8
> 
> This is my solution. Hope useful!
> 
>  Screen.Recording.2021-10-22.at.11.33.46.PM.mov 
> ### Drawer custom component
> ```
> const DrawerCustom = ({}: any) => {
>   return (
>     <View style={styles.container}>
>       <Drawer.Navigator
>         drawerContent={(props) => <CustomDrawerContent {...props} />}
>         screenOptions={{
>           headerShown: false,
>           drawerStyle: {
>             flex: 1,
>             width: '60%',
>             backgroundColor: 'red',
>           },
>           drawerType: 'slide',
>           overlayColor: 'transparent',
>           sceneContainerStyle: {
>             backgroundColor: 'red',
>           },
>         }}>
>         <Drawer.Screen name="TabNav">
>           {(props) => <TabNav {...props} />} // <-- Focus here
>         </Drawer.Screen>
>       </Drawer.Navigator>
>     </View>
>   );
> };
> ```
> 
> ### Tab navigation
> ```
> const TabNav = ({}: any) => {
>   const progress = useDrawerProgress();
>   const scale = Animated.interpolateNode(progress as Adaptable<number>, {
>     inputRange: [0, 1],
>     outputRange: [1, 0.8],
>     extrapolate: Extrapolate.CLAMP,
>   });
>   const borderRadius = Animated.interpolateNode(progress as Adaptable<number>, {
>     inputRange: [0, 1],
>     outputRange: [1, 20],
>     extrapolate: Extrapolate.CLAMP,
>   });
>   const animatedStyle = {
>     borderRadius,
>     transform: [{scale}],
>   };
>   return (
>     <Animated.View style={[styles.tabWrapper, animatedStyle]}>
>       <Tab.Navigator
>         screenOptions={{
>           headerShown: false,
>         }}
>         tabBar={(props) => <MyTabBar {...props} />}>
>         <Tab.Screen name="Paging" component={PagingScreen} />
>         <Tab.Screen name="Paging1" component={PagingScreen} />
>         <Tab.Screen name="Paging2" component={PagingScreen} />
>         <Tab.Screen name="Paging3" component={PagingScreen} />
>         <Tab.Screen name="Home" component={HomeScreen} />
>       </Tab.Navigator>
>     </Animated.View>
>   );
> };
> ```

useDrawerProgress not working properly

**Comment by zoobibackups** [comment]
> This is my workaround:
> 
> <img alt="CleanShot 2021-10-08 at 05 05 03@2x" width="880" src="https://user-images.githubusercontent.com/17423070/136468546-7f14c020-61bf-433e-ab41-80908b6aa5f6.png">
> 
> ![CleanShot 2021-10-08 at 05 01 47](https://user-images.githubusercontent.com/17423070/136468205-4f1430e9-627a-4d36-8c17-5540213d0348.gif)

@[nvdnvd00](https://github.com/nvdnvd00) can you provide link of your project(example)??

**Comment by s0rta** [comment]
wondering if a quick check for if interpolate is undefined would be a cross version solution?

**Comment by malinjr07** [comment]
> > This is my workaround:
> > <img alt="CleanShot 2021-10-08 at 05 05 03@2x" width="880" src="https://user-images.githubusercontent.com/17423070/136468546-7f14c020-61bf-433e-ab41-80908b6aa5f6.png">
> > ![CleanShot 2021-10-08 at 05 01 47](https://user-images.githubusercontent.com/17423070/136468205-4f1430e9-627a-4d36-8c17-5540213d0348.gif)
> 
> @[nvdnvd00](https://github.com/nvdnvd00) can you provide link of your project(example)??

Can you please enlighten us with the explanation of the 'useUpdateEffect' hook, please?

**Comment by malinjr07** [comment]
> > This is my workaround:
> > <img alt="CleanShot 2021-10-08 at 05 05 03@2x" width="880" src="https://user-images.githubusercontent.com/17423070/136468546-7f14c020-61bf-433e-ab41-80908b6aa5f6.png">
> > ![CleanShot 2021-10-08 at 05 01 47](https://user-images.githubusercontent.com/17423070/136468205-4f1430e9-627a-4d36-8c17-5540213d0348.gif)
> 
> @[nvdnvd00](https://github.com/nvdnvd00) can you provide link of your project(example)??

can you provide a URL of your project(example)?? (02)

**Comment by malinjr07** [comment]
> @react-navigation/native - 6.0.6 @react-navigation/drawer - 6.1.8
> 
> This is my solution. Hope useful!
> 
>  Screen.Recording.2021-10-22.at.11.33.46.PM.mov 
> ### Drawer custom component
> ```
> const DrawerCustom = ({}: any) => {
>   return (
>     <View style={styles.container}>
>       <Drawer.Navigator
>         drawerContent={(props) => <CustomDrawerContent {...props} />}
>         screenOptions={{
>           headerShown: false,
>           drawerStyle: {
>             flex: 1,
>             width: '60%',
>             backgroundColor: 'red',
>           },
>           drawerType: 'slide',
>           overlayColor: 'transparent',
>           sceneContainerStyle: {
>             backgroundColor: 'red',
>           },
>         }}>
>         <Drawer.Screen name="TabNav">
>           {(props) => <TabNav {...props} />} // <-- Focus here
>         </Drawer.Screen>
>       </Drawer.Navigator>
>     </View>
>   );
> };
> ```
> 
> ### Tab navigation
> ```
> const TabNav = ({}: any) => {
>   const progress = useDrawerProgress();
>   const scale = Animated.interpolateNode(progress as Adaptable<number>, {
>     inputRange: [0, 1],
>     outputRange: [1, 0.8],
>     extrapolate: Extrapolate.CLAMP,
>   });
>   const borderRadius = Animated.interpolateNode(progress as Adaptable<number>, {
>     inputRange: [0, 1],
>     outputRange: [1, 20],
>     extrapolate: Extrapolate.CLAMP,
>   });
>   const animatedStyle = {
>     borderRadius,
>     transform: [{scale}],
>   };
>   return (
>     <Animated.View style={[styles.tabWrapper, animatedStyle]}>
>       <Tab.Navigator
>         screenOptions={{
>           headerShown: false,
>         }}
>         tabBar={(props) => <MyTabBar {...props} />}>
>         <Tab.Screen name="Paging" component={PagingScreen} />
>         <Tab.Screen name="Paging1" component={PagingScreen} />
>         <Tab.Screen name="Paging2" component={PagingScreen} />
>         <Tab.Screen name="Paging3" component={PagingScreen} />
>         <Tab.Screen name="Home" component={HomeScreen} />
>       </Tab.Navigator>
>     </Animated.View>
>   );
> };
> ```

Can You please share your project? It'll be much easier to understand. Because I'm trying your code and it's not working.

**Comment by saadi-ninjasCode** [comment]
I fixed the issue by useAnimatedStyle hook from Reanimated 2.

`  const progress = useDrawerProgress();

  const style = useAnimatedStyle(() => {
    const translateX = interpolate(progress.value, [0, 1], [-100, 100], Extrapolate.CLAMP);
    return {
      transform: [{ translateX }],
    };
  }, []);
  `

**Comment by malinjr07** [comment]
> I fixed the issue by useAnimatedStyle hook from Reanimated 2.
> 
> ```
>  const progress = useDrawerProgress();
> 
>   const style = useAnimatedStyle(() => {
>     const translateX = interpolate(progress.value, [0, 1], [-100, 100], Extrapolate.CLAMP);
>     return {
>       transform: [{ translateX }],
>     };
>   }, []);
> ```

Well, I got some weird issue on that. The progress.value is changing, but it's not re-rendering accordingly. How can I re-render it on value change?

**Comment by techmodule** [comment]
problem with useDrawerProgress(), it no default value? Maybe bugs?
I change to React.useRef(new Animated.Value(0)).current;
It work well
`const translation = React.useRef(new Animated.Value(0)).current;
    //const progress = useDrawerProgress();
    let translateX = Animated.interpolateNode(translation, {
        inputRange: [0, 0.5, 0.7, 0.8, 1],
        outputRange: [0, -85, -70, -45, 0],
    });`

**Comment by malinjr07** [comment]
> problem with useDrawerProgress(), it no default value? Maybe bugs? I change to React.useRef(new Animated.Value(0)).current; It work well `const translation = React.useRef(new Animated.Value(0)).current; //const progress = useDrawerProgress(); let translateX = Animated.interpolateNode(translation, { inputRange: [0, 0.5, 0.7, 0.8, 1], outputRange: [0, -85, -70, -45, 0], });`

Can you please share the whole component's code?

**Comment by mixmaker** [comment]
According to the documentation of react navigation [here](https://reactnavigation.org/docs/drawer-navigator/) 

`
function CustomDrawerContent(props) {
  const progress = useDrawerProgress();

  const translateX = Animated.interpolate(progress, {
    inputRange: [0, 1],
    outputRange: [-100, 0],
  });

  return (
    <Animated.View style={{ transform: [{ translateX }] }}>
      {/* ... drawer contents */}
    </Animated.View>
  );
}
`
I tried this and this throws error :
![image](https://user-images.githubusercontent.com/94787156/163536798-91993fbc-e300-476f-ba09-473c28af1e78.png)

I tried with `progress.value` and `interpolateNode` instead of `interpolate` but the screen component doesn't re-render!

**Comment by techmodule** [comment]
> > problem with useDrawerProgress(), it no default value? Maybe bugs? I change to React.useRef(new Animated.Value(0)).current; It work well `const translation = React.useRef(new Animated.Value(0)).current; //const progress = useDrawerProgress(); let translateX = Animated.interpolateNode(translation, { inputRange: [0, 0.5, 0.7, 0.8, 1], outputRange: [0, -85, -70, -45, 0], });`
> 
> Can you please share the whole component's code? I mean, the Whole **Tab Navigation** Component with Fixed Code?
Now it run
```import React from 'react';
import {Dimensions, Image, StyleSheet, TouchableOpacity, View} from "react-native";
import {MaterialCommunityIcons} from '@expo/vector-icons';
import {DrawerContentScrollView, DrawerItem, useDrawerProgress} from '@react-navigation/drawer';
import {styles} from "./styles";
import {Button, Caption, Drawer, Paragraph, Switch, Text, Title, TouchableRipple, useTheme} from 'react-native-paper';
import Animated from 'react-native-reanimated';
import {PreferencesContext} from '../../context/preferencesContext';
import {AuthContext} from "../../context/AuthContext";
import 'moment';
import 'moment/locale/vi'; // language must match config
import {_currencyFormat} from '../components/GlobalFunction';

const DEVICE_WIDTH = Math.round(Dimensions.get('window').width);

export function DrawerContent(props) {
    const paperTheme = useTheme();
    const {rtl, theme, toggleRTL, toggleTheme} = React.useContext(
        PreferencesContext
    );
    const {userData, signOut, signOutAll} = React.useContext(AuthContext);
    const [isLoading, setLoading] = React.useState(false);
    const translation = React.useRef(new Animated.Value(0)).current;
    const progress = useDrawerProgress();
    let translateX = Animated.interpolateNode(progress.value, {
        inputRange: [0, 0.5, 0.7, 0.8, 1],
        outputRange: [0, -85, -70, -45, 0],
    });

    const avatar = 'https://booking-app.vn/api/v2/customer/avatar?phone=' + userData.phone + "&shop_id=" + userData.shop.id.toString();
    const _onLogout = async () => {
        setLoading(true);
        await signOut();
        setLoading(false);
    }
    const _onLogoutAll = async () => {
        setLoading(true);
        await signOutAll();
        setLoading(false);
    }
    return (
        <DrawerContentScrollView {...props}>
            <Animated.View
                //@ts-ignore
                style={[
                    styles.drawerContent,
                    {
                        backgroundColor: paperTheme.colors.surface,
                        transform: [{translateX}],
                    },
                ]}
            >
                <View style={styles.userInfoSection}>
                    <TouchableOpacity
                        style={{marginLeft: 10, flexDirection: "row"}}
                        onPress={() => {
                            props.navigation.toggleDrawer();
                        }}
                    >
                        <View style={{flex: 3, justifyContent: "center"}}><Image
                            source={{
                                uri: avatar,
                            }}
                            style={stylesDrawer.logo}
                        /></View>
                        <View style={{flex: 9, justifyContent: "center"}}>
                            {userData.isVIP ? (<View><Title style={{
                                color: paperTheme.colors.primary,
                                padding: 5,
                                fontWeight: 'bold',
                            }}>VIP</Title>
                                <Caption style={[styles.caption]}>Bạn là khách hàng VIP</Caption>
                            </View>) : (<Text></Text>)}
                        </View>

                    </TouchableOpacity>

                    <Title style={styles.title}>{userData.last_name}</Title>
                    <Caption style={styles.caption}>{userData.first_name} </Caption>
                    <View style={styles.row}>
                        <View style={styles.section}>
                            <Paragraph style={[styles.paragraph, styles.caption]}>
                                {userData.loyalty.name}
                            </Paragraph>

                        </View>
                        <View style={styles.section}>
                            <Paragraph style={[styles.paragraph, styles.caption]}>
                                {_currencyFormat(userData.spent_per_year)}/Năm
                            </Paragraph>
                        </View>
                    </View>
                    <Caption style={[styles.caption, {color: userData.loyalty.background_color}]}>Giảm
                        giá {userData.loyalty.percentage_discount}% khi đặt qua app </Caption>
                    <View style={styles.row}>
                        <View style={styles.section}>
                            <Paragraph style={[styles.paragraph, styles.caption]}>
                                {userData.orders_count}
                            </Paragraph>
                            <Caption style={styles.caption}>Đơn hàng</Caption>
                        </View>
                        <View style={styles.section}>
                            <Paragraph style={[styles.paragraph, styles.caption]}>
                                {_currencyFormat(userData.total_spent)}
                            </Paragraph>
                        </View>
                    </View>
                </View>
                <Drawer.Section style={styles.drawerSection}>
                    <DrawerItem
                        icon={({color, size}) => (
                            <MaterialCommunityIcons
                                name="logout"
                                color={color}
                                size={size}
                            />
                        )}
                        label={isLoading ? "Đang đăng xuất" : "Đăng xuất máy này"}
                        onPress={() => _onLogout()}
                    />
                    <DrawerItem
                        icon={({color, size}) => (
                            <MaterialCommunityIcons
                                name="logout"
                                color={color}
                                size={size}
                            />
                        )}
                        label={isLoading ? "Đang đăng xuất" : "Đăng xuất toàn bộ"}
                        onPress={() => _onLogoutAll()}
                    />
                </Drawer.Section>
                <Drawer.Section title="Cài đặt giao diện">
                    <TouchableRipple onPress={() => toggleTheme()}>
                        <View style={styles.preference}>
                            <Text>Sáng/Tối</Text>
                            <View pointerEvents="none">
                                <Switch value={theme === 'dark'}/>
                            </View>
                        </View>
                    </TouchableRipple>
                    <TouchableRipple onPress={() => toggleRTL()}>
                        <View style={styles.preference}>
                            <Text>Đảo giao diện</Text>
                            <View pointerEvents="none">
                                <Switch value={rtl === 'right'}/>
                            </View>
                        </View>
                    </TouchableRipple>
                </Drawer.Section>
                <Drawer.Section title="Hướng dẫn">
                    <Button icon="close" onPress={() => props.navigation.closeDrawer()}>Đóng Menu</Button>
                    <View style={styles.preference}>
                        <Caption>Vuốt gang hoặc bấm để đóng menu</Caption>
                    </View>
                </Drawer.Section>
            </Animated.View>
        </DrawerContentScrollView>
    );
}

const stylesDrawer = StyleSheet.create({
    container: {
        paddingTop: 50,
    },
    tinyLogo: {
        width: 50,
        height: 50,
    },
    logo: {
        width: 50,
        height: 50,
        borderRadius: 25,
    },
});
```
<Drawer.Navigator initialRouteName="HomeStackNavigator"
                                      screenOptions={{
                                          headerShown: false,
                                          overlayColor: 'transparent',
                                          drawerType: isLargeScreen ? 'permanent' : 'back',
                                          drawerStyle: isLargeScreen ? null : {width: '70%'},
                                      }}
                                      defaultStatus='closed'
                                      drawerContent={props => <DrawerContent {...props}
                                      />}>
                        <Drawer.Screen name="HomeStackNavigator" component={HomeStackNavigator}
                                       options={{headerShown: false}}/>
                        <Drawer.Screen name="ProfileStackNavigator" component={ProfileStackNavigator}
                                       options={{headerShown: false}}/>
                        {state.userData.isAdmin &&
                        <Drawer.Screen name="AdminStackNavigator" component={AdminStackNavigator}
                                       options={{headerShown: false}}/>}

                    </Drawer.Navigator>}
```

```
Version
```
"dependencies": {
    "@babel/preset-env": "^7.16.11",
    "@baronha/react-native-multiple-image-picker": "^0.4.6",
    "@expo/vector-icons": "^12.0.0",
    "@native-html/iframe-plugin": "^2.0.0",
    "@react-native-async-storage/async-storage": "~1.15.0",
    "@react-native-community/checkbox": "^0.5.12",
    "@react-native-community/clipboard": "^1.5.1",
    "@react-native-community/datetimepicker": "4.0.0",
    "@react-native-masked-view/masked-view": "0.2.6",
    "@react-navigation/bottom-tabs": "^6.0.9",
    "@react-navigation/drawer": "^6.4.1",
    "@react-navigation/elements": "^1.2.1",
    "@react-navigation/material-bottom-tabs": "^6.0.9",
    "@react-navigation/native": "^6.0.10",
    "@react-navigation/native-stack": "^6.2.5",
    "@unimodules/core": "~7.2.0",
    "add": "^2.0.6",
    "babel-plugin-transform-remove-console": "^6.9.4",
    "color": "^3.1.2",
    "expo": "^44.0.6",
    "expo-asset": "~8.4.6",
    "expo-av": "~10.2.0",
    "expo-barcode-scanner": "~11.2.0",
    "expo-calendar": "~10.1.0",
    "expo-camera": "~12.1.2",
    "expo-checkbox": "~2.0.0",
    "expo-crypto": "~10.1.1",
    "expo-dev-client": "~0.8.4",
    "expo-device": "~4.1.0",
    "expo-file-system": "~13.1.4",
    "expo-image-manipulator": "~10.2.0",
    "expo-image-picker": "~12.0.1",
    "expo-image-picker-multiple": "^1.4.1",
    "expo-images-picker": "^2.3.0",
    "expo-linking": "~3.0.0",
    "expo-media-library": "~14.0.0",
    "expo-modules-autolinking": "^0.5.5",
    "expo-network": "~4.1.0",
    "expo-notifications": "~0.14.0",
    "expo-permissions": "~13.1.0",
    "expo-secure-store": "~11.1.0",
    "expo-sharing": "~10.1.0",
    "expo-sms": "~10.1.0",
    "expo-splash-screen": "~0.14.1",
    "expo-status-bar": "~1.2.0",
    "expo-updates": "~0.11.6",
    "expo-web-browser": "~10.1.0",
    "intl": "^1.2.5",
    "moment": "^2.29.1",
    "moment-timezone": "^0.5.33",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-native": "0.64.3",
    "react-native-appearance": "~0.3.3",
    "react-native-calendar-strip": "^2.2.5",
    "react-native-date-picker": "^4.0.0",
    "react-native-gesture-handler": "~2.1.0",
    "react-native-htmlview": "^0.16.0",
    "react-native-image-crop-picker": "^0.36.4",
    "react-native-image-slider-box": "^1.0.12",
    "react-native-openalpr": "^2.2.0",
    "react-native-paper": "^4.11.2",
    "react-native-picker-select": "^8.0.4",
    "react-native-qrcode-svg": "^6.1.0",
    "react-native-reanimated": "~2.3.1",
    "react-native-safe-area-context": "3.3.2",
    "react-native-screens": "~3.10.1",
    "react-native-svg": "12.1.1",
    "react-native-tab-view": "^2.13.0",
    "react-native-text-ticker": "^1.14.0",
    "react-native-unimodules": "~0.15.0",
    "react-native-vector-icons": "^9.0.0",
    "react-native-web": "0.17.1",
    "react-native-webview": "11.15.0",
    "react-native-youtube-iframe": "^2.1.0",
    "react-navigation": "^4.4.4",
    "react-navigation-drawer": "^2.7.2",
    "react-number-format": "^4.6.3",
    "styled-components": "5.3.3",
    "unimodules-permissions-interface": "^6.1.0",
    "yarn": "^1.22.17"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/plugin-proposal-async-generator-functions": "^7.14.7",
    "@callstack/eslint-config": "^12.0.2",
    "@types/color": "^3.0.1",
    "@types/react": "~17.0.21",
    "@types/react-native": "~0.64.12",
    "@typescript-eslint/eslint-plugin": "^5.1.0",
    "@typescript-eslint/parser": "^5.1.0",
    "babel-preset-expo": "9.0.2",
    "eslint": "^7.32.0",
    "metro-react-native-babel-preset": "^0.66.2",
    "react-native-render-html": "^6.0.0-beta.8",
    "react-test-renderer": "^17.0.2",
    "typescript": "~4.3.5",
    "yarn-upgrade-all": "^0.5.4"
  },
``

**Comment by cltsang** [comment]
Guys, `useDrawerProgress` seems to be only available inside of `DrawerContent`.
The above direct attempts don't work since `useDrawerProgress` is accessed from a screen component.

**Comment by wangoghstudio** [comment]
> Guys, `useDrawerProgress` seems to be only available inside of `DrawerContent`. The above direct attempts don't work since `useDrawerProgress` is accessed from a screen component.

It was usable inside a screen on  @react-navigation/drawer: "6.3.0" any solutiuon to grab drawerprogress inside a screen?

**Comment by anhquan291** [comment]
> 

You saved my day. Thanks

**Comment by SathishSaminathan** [comment]
> interpolateNode

Did you got any solution

**Comment by am2222** [comment]
I have tried all of these methods and they all fail. Is there any solutions for this?

**Comment by Rottelfeld** [comment]
> Its working but borderRadius not showing.

If you want animate borderRadius, overflow hidden needed.

**Comment by am2222** [comment]
@Dhaval167 @Rottelfeld 
Hi, Can you please share a working expo example? I still cannot make it work

**Comment by anhquan291** [comment]
> 

`const MainStackScreens = () => {
  const progress: any = useDrawerProgress();
  const scaleAnimated = interpolateNode(progress, {
    inputRange: [0, 1],
    outputRange: [1, 0.9],
    extrapolate: Extrapolate.CLAMP,
  });
  const borderRadius = interpolateNode(progress, {
    inputRange: [0, 1],
    outputRange: [0, 25],
    extrapolate: Extrapolate.CLAMP,
  });

  const animatedStyles = {
    borderRadius,
    transform: [{ scale: scaleAnimated }],
  };
  const isDrawerOpen = useDrawerStatus();
  const sv = useSharedValue(0);

  useEffect(() => {
    if (isDrawerOpen === 'open') {
      sv.value = withTiming(1);
    } else {
      sv.value = withTiming(0);
    }
  }, [isDrawerOpen]);

  const screenStyle = useAnimatedStyle(() => {
    const scaleY = interpolate(sv.value, [0, 1], [1, 0.9], Extrapolate.CLAMP);
    const borderRadius1 = interpolate(
      sv.value,
      [0, 1],
      [0, 25],
      Extrapolate.CLAMP,
    );
    return {
      transform: [{ scaleY }],
      borderRadius: borderRadius1,
    };
  });

  return (
    <Animated.View
      style={[
        Layout.fill,
        { overflow: 'hidden' },
        { ...(isIos ? animatedStyles : screenStyle) },
      ]}>
      <MainStack />
    </Animated.View>
  );
};`

**Comment by am2222** [comment]
@anhquan291 Thanks! Can you please share me the versions of the libraries you are using? I still have issues with reading the progress value

**Comment by anhquan291** [comment]
@am2222 So sorry for the delay. 
Here are the versions I'm using. Hope it's not too late :'(.
```
    "@react-navigation/bottom-tabs": "^6.3.1",
    "@react-navigation/drawer": "^6.4.1",
    "@react-navigation/material-top-tabs": "^6.2.1",
    "@react-navigation/native": "^6.0.10",
    "@react-navigation/native-stack": "^6.6.2",
```

**Comment by am2222** [comment]
@anhquan291 thanks!

**Comment by malinjr07** [comment]
Hi Everyone. Been almost 8 months since I last checked. Have anyone have the actual result with the latest version of all packages?

**Comment by Mukthayar1** [comment]
> Hi Everyone. Been almost 8 months since I last checked. Have anyone have the actual result with the latest version of all packages?

not yet

**Comment by malinjr07** [comment]
> > Hi Everyone. Been almost 8 months since I last checked. Have anyone have the actual result with the latest version of all packages?
> 
> not yet

Can we Somehow open this issue again??

**Comment by dunapanta** [comment]
I tried to implement the above solutions with the current versions but without success. Any updated solution?
`
"@react-navigation/drawer": "^6.6.2",
"@react-navigation/native": "^6.1.2",
"@react-navigation/native-stack": "^6.9.8",
"react-native-gesture-handler": "^2.9.0",
`

**Comment by Michael-AYK** [comment]
Try this : 
`const progress = useDrawerProgress() as Animated.SharedValue<number>;`

Then :

`
    const myAnimationStyle= useAnimatedStyle(() => {
      const translateX = interpolate(progress.value, [0, 1], [-100, 0], Extrapolate.CLAMP);

      return {
        transform: [{ translateX }],
      };
    });`
    
Don't forget to import interpolate from reanimated.
Let me know if it work.

**Comment by serdarmengutay** [comment]
const DrawerScreenContainer = ({ children }) => {
    const isDrawerOpen = useDrawerStatus();
    const progress = useDrawerProgress();
    const scale = Animated.interpolateNode(progress, {
      inputRange: [0, 1],
      outputRange: [1, 0.8],
    });
    const borderRadius = Animated.interpolateNode(progress, {
      inputRange: [0, 1],
      outputRange: [0, 25],
    }); 



this is my code, i tried every single exapmle but still giving this error: undefined is not a function in interpolateNode, 
can someone fix this, 


these are my package versions; 

 "@react-navigation/drawer": "^6.6.3",
    "@react-navigation/native": "^6.1.6",
    "@react-navigation/stack": "^6.3.16",
    "react": "18.2.0",
    "react-native": "0.71.10",
    "react-native-gesture-handler": "^2.11.0",
    "react-native-reanimated": "^3.3.0",
    "react-native-safe-area-context": "^4.5.3",
    "react-native-screens": "^3.20.0",

**Comment by Saliheen** [comment]
`const progress = useDrawerProgress()  `
works for me
