### ISSUE TITLE
[v6] (android) Native-Stack Navigator headerTitleAlign is ignored when headerText set to center alignment

### ISSUE THREAD

**Issue by alphatrl** [react-navigation/react-navigation#9885]
### Current behavior

I have a native-stack navigator with the screenOptions/options `headerTitleStyle` not being applied to the `headerTitle` when the `headerTitleAlign` is set to `center` on Android. The expected behaviour can be seen on the Web platform, but not on the Android.

The expected results should be that `headerTitle` to be styled similar to `headerTitleAlign: left`. 

Here's a quick example of this bug:
```jsx
import * as React from 'react';
import { Text, View, StyleSheet, Button } from 'react-native';
import { createNativeStackNavigator } from '@react-navigation/native-stack';
import { NavigationContainer, useNavigation } from '@react-navigation/native'

const HomeStack = createNativeStackNavigator();

const Screen1: React.FC = () => {
  const navigation = useNavigation();

  const goToScreen2 = () => {
    navigation.navigate('Screen 2', {});
  }

  const goToScreen3 = () => {
    navigation.navigate('Screen 3', {});
  }

  return (
    <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
      <Button onPress={goToScreen2} title="Go to Screen 2" />
      <Button onPress={goToScreen3} title="Go to Screen 3" />
    </View>
  );
};

const Screen2: React.FC = () => {
  return (
    <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
      <Text>Screen</Text>
    </View>
  );
};

export default function App() {
  return (
    <NavigationContainer>
      <HomeStack.Navigator>
        <HomeStack.Screen name="Screen 1" component={Screen1} />
        <HomeStack.Screen
          name="Screen 2"
          component={Screen2}
          options={{
            headerTitleAlign: 'left',
            headerTitleStyle: {
              fontFamily: 'sans-serif-condensed',
              fontWeight: 'bold',
              color: 'pink'
            },
          }}
        />
        <HomeStack.Screen 
          name="Screen 3"
          component={Screen2}
          options={{
            title: "Screen 3",
            headerTitleAlign: 'center',
            headerTitleStyle: {
              fontFamily: 'sans-serif-condensed',
              fontWeight: 'bold',
              color: 'pink'
            },
          }}
        />
      </HomeStack.Navigator>
    </NavigationContainer>
  );
}
```

### Expected behavior

I expect Android `headerTitle` have `headerTitleStyles` be applied to it regardless of headerTitleAlignment.

### Reproduction

https://snack.expo.dev/@alphatrl/react-navigation-v6-native-stack-bug-demo

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |  6.0.2 |
| @react-navigation/bottom-tabs          | n/a |
| @react-navigation/drawer               | n/a |
| @react-navigation/material-bottom-tabs | n/a |
| @react-navigation/material-top-tabs    | n/a |
| @react-navigation/stack                | n/a |
| @react-navigation/native-stack         | 6.1.0 |
| react-native-safe-area-context         | 3..3.0 |
| react-native-screens                   | 3.6.0 |
| react-native-gesture-handler           | 1.10.3 |
| react-native-reanimated                | 2.2.0 |
| react-native-tab-view                  | n/a |
| react-native-pager-view                | n/a |
| react-native                           | 0.64.2 |
| expo                                   | 42.0.0 |
| node                                   | 16.7.0 |
| npm or yarn                            | yarn |

**Comment by ferlnand** [comment]
+1

Title is misleading though! Should be "headerTitleStyle is not applied"

Expected behaviour on iOS, but not on Android. As soon as headerTitleAlign is set to "center", headerTitleStyle is completely ignored.
