### ISSUE TITLE
How remove bottom border of header

### ISSUE THREAD

**Issue by hearAllParties** [react-navigation/react-navigation#9888]
### Current behavior

![image](https://user-images.githubusercontent.com/14330629/131344147-3f5392ae-4e4e-4c4e-a492-cb529fa2a846.png)

### Expected behavior

i want to remove bottom border

### Reproduction

xx

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | ^6.0.2
| @react-navigation/bottom-tabs          |
| @react-navigation/drawer               |
| @react-navigation/material-bottom-tabs |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                | ^6.0.6
| @react-navigation/native-stack         |^6.0.5
| react-native-safe-area-context         |
| react-native-screens                   |^3.5.0
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           | 0.64.2
| expo                                   |
| node                                   | 14.0.0
| npm or yarn                            |

**Comment by Jonovono** [comment]
Would like to know this too, the solution for V5 doesn't seem to work on V6. Any ideas?
