### ISSUE TITLE
Attempt to access out of bounds index when hiding a DrawerItem 

### ISSUE THREAD

**Issue by minutetominute** [react-navigation/react-navigation#9890]
### Current behavior

Any attempt to access a hidden DrawerItem per this [suggestion](https://github.com/react-navigation/react-navigation/issues/795#issuecomment-632445484) using a version of @react-navigation/drawer after 6.1.2 returns an error about accessing `key` on undefined.

### Expected behavior

Ability to navigate to route for hidden DrawerItem.

### Reproduction

will add later

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |
| @react-navigation/bottom-tabs          |
| @react-navigation/drawer               | 6.1.3
| @react-navigation/material-bottom-tabs |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                |
| @react-navigation/native-stack         |
| react-native-safe-area-context         |
| react-native-screens                   |
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           |
| expo                                   |
| node                                   |
| npm or yarn                            |

**Comment by satya164** [comment]
That suggestion isn't documented. If you want to apply styles to drawer item, e.g. hide it, use `drawerItemStyle: { display: 'none' }`. Also please don't open issues because something in a random comment doesn't work.
