### ISSUE TITLE
EventEmitter.removeListener('change', ...): Method has been deprecated. Please instead use `remove()`

### ISSUE THREAD

**Issue by oceanroleplay** [react-navigation/react-navigation#9894]
### Current behavior

``` 
WARN EventEmitter.removeListener('change', ...): Method has been deprecated. Please instead use `remove()` on the subscription returned by `EventEmitter.addListener`.
MaybeScreen@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.app.test&modulesOnly=false&runModule=true:169371:24
```

### Expected behavior

No warning
___

### Code
```ts
  React.useEffect(() => {
    navigation.setOptions({
      headerRight: () => <CustomMenu route={route} navigation={navigation} />,
    });
  }, []);
```

if, I comment above code, warning disappear.

### Reproduction

NaN

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [X] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | ^6.0.2|
| react-native-safe-area-context         |^3.3.0
| react-native-screens                   |react-native-screens
| react-native-gesture-handler           |^1.10.3
| react-native-reanimated                |^2.3.0-alpha.2
| react-native-pager-view                |^5.4.1
| react-native                           |0.65.1
| node                                   | v16.x.x
| npm or yarn                            | yarn

**Comment by nikita-bekish** [comment]
Hey, @oceanroleplay, you closed the issue, did you find any solution?

**Comment by oceanroleplay** [comment]
@nikita-bekish that was related to my react-native-paper package (``Menu``).

**Comment by shensven** [comment]
I have same waring

**Comment by vinayr** [comment]
I had to create this patch for 0.66.1 and v5
```diff
diff --git a/node_modules/@react-navigation/bottom-tabs/src/utils/useIsKeyboardShown.tsx b/node_modules/@react-navigation/bottom-tabs/src/utils/useIsKeyboardShown.tsx
index 4ab974c..1a7ca0f 100644
--- a/node_modules/@react-navigation/bottom-tabs/src/utils/useIsKeyboardShown.tsx
+++ b/node_modules/@react-navigation/bottom-tabs/src/utils/useIsKeyboardShown.tsx
@@ -1,5 +1,5 @@
 import * as React from 'react';
-import { Keyboard, Platform } from 'react-native';
+import { Keyboard, Platform, EmitterSubscription } from 'react-native';
 
 export default function useIsKeyboardShown() {
   const [isKeyboardShown, setIsKeyboardShown] = React.useState(false);
@@ -8,22 +8,22 @@ export default function useIsKeyboardShown() {
     const handleKeyboardShow = () => setIsKeyboardShown(true);
     const handleKeyboardHide = () => setIsKeyboardShown(false);
 
+    let subscriptions: EmitterSubscription[];
+
     if (Platform.OS === 'ios') {
-      Keyboard.addListener('keyboardWillShow', handleKeyboardShow);
-      Keyboard.addListener('keyboardWillHide', handleKeyboardHide);
+      subscriptions = [
+        Keyboard.addListener('keyboardWillShow', handleKeyboardShow),
+        Keyboard.addListener('keyboardWillHide', handleKeyboardHide),
+      ];
     } else {
-      Keyboard.addListener('keyboardDidShow', handleKeyboardShow);
-      Keyboard.addListener('keyboardDidHide', handleKeyboardHide);
+      subscriptions = [
+        Keyboard.addListener('keyboardDidShow', handleKeyboardShow),
+        Keyboard.addListener('keyboardDidHide', handleKeyboardHide),
+      ];
     }
 
     return () => {
-      if (Platform.OS === 'ios') {
-        Keyboard.removeListener('keyboardWillShow', handleKeyboardShow);
-        Keyboard.removeListener('keyboardWillHide', handleKeyboardHide);
-      } else {
-        Keyboard.removeListener('keyboardDidShow', handleKeyboardShow);
-        Keyboard.removeListener('keyboardDidHide', handleKeyboardHide);
-      }
+      subscriptions.forEach((s) => s?.remove?.());
     };
   }, []);
 
diff --git a/node_modules/@react-navigation/bottom-tabs/src/utils/useWindowDimensions.tsx b/node_modules/@react-navigation/bottom-tabs/src/utils/useWindowDimensions.tsx
index 8000a59..1aecea1 100644
--- a/node_modules/@react-navigation/bottom-tabs/src/utils/useWindowDimensions.tsx
+++ b/node_modules/@react-navigation/bottom-tabs/src/utils/useWindowDimensions.tsx
@@ -28,9 +28,9 @@ export default function useWindowDimensions() {
     // So make sure to update the dimensions
     onChange({ window: Dimensions.get('window') });
 
-    Dimensions.addEventListener('change', onChange);
+    const listener = Dimensions.addEventListener('change', onChange);
 
-    return () => Dimensions.removeEventListener('change', onChange);
+    return () => listener.remove();
   }, []);
 
   return dimensions;
````

**Comment by jspizziri** [comment]
@vinayr did you create a PR for this so that it can be merged and released eventually?

**Comment by droplessjake** [comment]
> I had to create this patch for 0.66.1 and v5
> 
> ```diff
> diff --git a/node_modules/@react-navigation/bottom-tabs/src/utils/useIsKeyboardShown.tsx b/node_modules/@react-navigation/bottom-tabs/src/utils/useIsKeyboardShown.tsx
> index 4ab974c..1a7ca0f 100644
> --- a/node_modules/@react-navigation/bottom-tabs/src/utils/useIsKeyboardShown.tsx
> +++ b/node_modules/@react-navigation/bottom-tabs/src/utils/useIsKeyboardShown.tsx
> @@ -1,5 +1,5 @@
>  import * as React from 'react';
> -import { Keyboard, Platform } from 'react-native';
> +import { Keyboard, Platform, EmitterSubscription } from 'react-native';
>  
>  export default function useIsKeyboardShown() {
>    const [isKeyboardShown, setIsKeyboardShown] = React.useState(false);
> @@ -8,22 +8,22 @@ export default function useIsKeyboardShown() {
>      const handleKeyboardShow = () => setIsKeyboardShown(true);
>      const handleKeyboardHide = () => setIsKeyboardShown(false);
>  
> +    let subscriptions: EmitterSubscription[];
> +
>      if (Platform.OS === 'ios') {
> -      Keyboard.addListener('keyboardWillShow', handleKeyboardShow);
> -      Keyboard.addListener('keyboardWillHide', handleKeyboardHide);
> +      subscriptions = [
> +        Keyboard.addListener('keyboardWillShow', handleKeyboardShow),
> +        Keyboard.addListener('keyboardWillHide', handleKeyboardHide),
> +      ];
>      } else {
> -      Keyboard.addListener('keyboardDidShow', handleKeyboardShow);
> -      Keyboard.addListener('keyboardDidHide', handleKeyboardHide);
> +      subscriptions = [
> +        Keyboard.addListener('keyboardDidShow', handleKeyboardShow),
> +        Keyboard.addListener('keyboardDidHide', handleKeyboardHide),
> +      ];
>      }
>  
>      return () => {
> -      if (Platform.OS === 'ios') {
> -        Keyboard.removeListener('keyboardWillShow', handleKeyboardShow);
> -        Keyboard.removeListener('keyboardWillHide', handleKeyboardHide);
> -      } else {
> -        Keyboard.removeListener('keyboardDidShow', handleKeyboardShow);
> -        Keyboard.removeListener('keyboardDidHide', handleKeyboardHide);
> -      }
> +      subscriptions.forEach((s) => s?.remove?.());
>      };
>    }, []);
>  
> diff --git a/node_modules/@react-navigation/bottom-tabs/src/utils/useWindowDimensions.tsx b/node_modules/@react-navigation/bottom-tabs/src/utils/useWindowDimensions.tsx
> index 8000a59..1aecea1 100644
> --- a/node_modules/@react-navigation/bottom-tabs/src/utils/useWindowDimensions.tsx
> +++ b/node_modules/@react-navigation/bottom-tabs/src/utils/useWindowDimensions.tsx
> @@ -28,9 +28,9 @@ export default function useWindowDimensions() {
>      // So make sure to update the dimensions
>      onChange({ window: Dimensions.get('window') });
>  
> -    Dimensions.addEventListener('change', onChange);
> +    const listener = Dimensions.addEventListener('change', onChange);
>  
> -    return () => Dimensions.removeEventListener('change', onChange);
> +    return () => listener.remove();
>    }, []);
>  
>    return dimensions;
> ```

@vinayr can you provide a bit more info, what file name did you give that patch? which file did it target?

**Comment by vinayr** [comment]
@droplessjake you should check out https://github.com/ds300/patch-package which was used to create the patch file. Target files are already mentioned in the patch file if you look closely.

**Comment by sritharIOS** [comment]
Hi All, I am new to the react native and getting the same issue in react native 0.65.1

`EventEmitter.removeListener('change', ...): Method has been deprecated. Please instead use `remove()` on the subscription returned by `EventEmitter.addListener`. 
BottomTabBar`

Can you please help me to resolve this issue?.

**Comment by deyashu13** [comment]
hii every one even I am facing the same issue what is the solution to it ??

**Comment by panshak** [comment]
I am facing the same issue. Has anyone gotten a solution to this problem?

**Comment by panshak** [comment]
I am facing the same issue. Has anyone gotten a solution to this problem?

**Comment by panshak** [comment]
Since I couldn't find any helpful solution, I decided to downgrade react native to version `^0.64.2` and everything is working now so far without issues.

**Comment by fmacherey** [comment]
Hey guys, 
look e.g. at this comment https://github.com/react-navigation/react-navigation/issues/9894#issuecomment-989795424 It work for me to create a patch with `patch-package`. It look like this package is not maintained anymore, because of thier new variants.

**Comment by FayyazAliKhan1** [comment]
> I had to create this patch for 0.66.1 and v5
> 
> ```diff
> diff --git a/node_modules/@react-navigation/bottom-tabs/src/utils/useIsKeyboardShown.tsx b/node_modules/@react-navigation/bottom-tabs/src/utils/useIsKeyboardShown.tsx
> index 4ab974c..1a7ca0f 100644
> --- a/node_modules/@react-navigation/bottom-tabs/src/utils/useIsKeyboardShown.tsx
> +++ b/node_modules/@react-navigation/bottom-tabs/src/utils/useIsKeyboardShown.tsx
> @@ -1,5 +1,5 @@
>  import * as React from 'react';
> -import { Keyboard, Platform } from 'react-native';
> +import { Keyboard, Platform, EmitterSubscription } from 'react-native';
>  
>  export default function useIsKeyboardShown() {
>    const [isKeyboardShown, setIsKeyboardShown] = React.useState(false);
> @@ -8,22 +8,22 @@ export default function useIsKeyboardShown() {
>      const handleKeyboardShow = () => setIsKeyboardShown(true);
>      const handleKeyboardHide = () => setIsKeyboardShown(false);
>  
> +    let subscriptions: EmitterSubscription[];
> +
>      if (Platform.OS === 'ios') {
> -      Keyboard.addListener('keyboardWillShow', handleKeyboardShow);
> -      Keyboard.addListener('keyboardWillHide', handleKeyboardHide);
> +      subscriptions = [
> +        Keyboard.addListener('keyboardWillShow', handleKeyboardShow),
> +        Keyboard.addListener('keyboardWillHide', handleKeyboardHide),
> +      ];
>      } else {
> -      Keyboard.addListener('keyboardDidShow', handleKeyboardShow);
> -      Keyboard.addListener('keyboardDidHide', handleKeyboardHide);
> +      subscriptions = [
> +        Keyboard.addListener('keyboardDidShow', handleKeyboardShow),
> +        Keyboard.addListener('keyboardDidHide', handleKeyboardHide),
> +      ];
>      }
>  
>      return () => {
> -      if (Platform.OS === 'ios') {
> -        Keyboard.removeListener('keyboardWillShow', handleKeyboardShow);
> -        Keyboard.removeListener('keyboardWillHide', handleKeyboardHide);
> -      } else {
> -        Keyboard.removeListener('keyboardDidShow', handleKeyboardShow);
> -        Keyboard.removeListener('keyboardDidHide', handleKeyboardHide);
> -      }
> +      subscriptions.forEach((s) => s?.remove?.());
>      };
>    }, []);
>  
> diff --git a/node_modules/@react-navigation/bottom-tabs/src/utils/useWindowDimensions.tsx b/node_modules/@react-navigation/bottom-tabs/src/utils/useWindowDimensions.tsx
> index 8000a59..1aecea1 100644
> --- a/node_modules/@react-navigation/bottom-tabs/src/utils/useWindowDimensions.tsx
> +++ b/node_modules/@react-navigation/bottom-tabs/src/utils/useWindowDimensions.tsx
> @@ -28,9 +28,9 @@ export default function useWindowDimensions() {
>      // So make sure to update the dimensions
>      onChange({ window: Dimensions.get('window') });
>  
> -    Dimensions.addEventListener('change', onChange);
> +    const listener = Dimensions.addEventListener('change', onChange);
>  
> -    return () => Dimensions.removeEventListener('change', onChange);
> +    return () => listener.remove();
>    }, []);
>  
>    return dimensions;
> ```

Bro please tell me what name you gave to this file 
cause I am getting this error when running yarn postinstall(patch-package) Unrecognized patch package 
using version 6 react navigation
Because of this error my ios app crashes when I goBack from a specific where I am using Gifted chat component
Any help would be appreciated Thank you

**Comment by singhmp2k** [comment]
getting same message 'EventEmitter.removeListener('change', ...): Method has been deprecated. Please instead use `remove()` on the subscription returned by `EventEmitter.addListener`.'  from all inputs. 
and keyboard hide while typing when using INPUT in MODAL

**Comment by malzate** [comment]
> ```diff
> return () => listener.remove();
> ```

this solved mi issue on V5 of react navigation

**Comment by nica0012** [comment]
> > ```diff
> 
> > return () => listener.remove();
> 
> > ```
> 
> 
> 
> this solved mi issue on V5 of react navigation

Where did you add this code?

**Comment by josethz00** [comment]
This issue is because the EventEmitter class is still declared with the `removeListener`method, but they didn't add the `remove()`

```ts
/**
     * Removes the given listener for event of specific type.
     *
     * @param eventType - Name of the event to emit
     * @param listener - Function to invoke when the specified event is
     *   emitted
     *
     * @example
     *   emitter.removeListener('someEvent', function(message) {
     *     console.log(message);
     *   }); // removes the listener if already registered
     * @deprecated Use `remove` on the EventSubscription from `addListener`.
     */
    removeListener(eventType: string, listener: (...args: any[]) => any): void;
```

**Comment by dks333** [comment]
Encountering this warning still...

**Comment by alexkendall** [comment]
> Encountering this warning still...

Same/

**Comment by lrob7325** [comment]
The solution @vinayr provided worked for me. I have an in-house script that patches node modules in the postinstall script. I added the patch for those 2 files, and after a yarn install, or running my custom command directly, the node modules is patched and no more warnings! Thanks!

**Comment by seemranxec** [comment]
Still facing this issue
![Screenshot 2022-10-20 at 9 27 54 AM](https://user-images.githubusercontent.com/8757624/196884049-d487b10e-fccd-4bd0-899f-7754e9c9bd80.png)

**Comment by rdgomt** [comment]
still facing

**Comment by hellotreedigital** [comment]
same

**Comment by Buddimal-Liyanapathirana** [comment]
The warning message disappeared after inserting

_**import { LogBox } from "react-native";
LogBox.ignoreLogs(["EventEmitter.removeListener"]);**_

on top of the App.js file .

**Comment by miracleweb9000** [comment]
Is this correct way to remove warning completly?

**Comment by ronaldaraujo** [comment]
In my case, upgrading the version `react-native-modal` solved it. [Look](https://github.com/react-native-modal/react-native-modal/issues/588)!

**Comment by CyxouD** [comment]
In React Native 0.74 (after upgrading from 0.72), I need to call `listener?.remove` safely because not listener can be undefined

**Comment by flyskywhy** [comment]
```
    "@react-navigation/bottom-tabs": "6.6.1",
    "@react-navigation/drawer": "6.7.2",
    "@react-navigation/native": "6.1.18",
    "@react-navigation/stack": "6.4.1",
    "react-native-pager-view": "6.1.2",
    "react-native-safe-area-context": "4.10.9",
    "react-native-screens": "3.32.0",
    "react-native-tab-view": "3.5.2",
```
can fix this issue.
