### ISSUE TITLE
Expected a 'never' type argument but receive a string.

### ISSUE THREAD

**Issue by gustavos00** [react-navigation/react-navigation#9898]
### Current behavior

When I write a screen name on `navigation.navigate`, VSCode give me a error saying "Argument of type 'string' is not assignable to parameter of type 'never'".

I can "fix it" writing `as any` forward screen's name, but when I send some params, give me the same error again.

### Expected behavior

Do not give me a error.

### Reproduction

https://snack.expo.dev/@expg/myanimal-navigate-problem

### Platform

- [ ] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [X] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |^6.0.2
| @react-navigation/stack                |^6.07
| @react-navigation/native-stack        | ^6.1.0
| react-native                          | 0.63.2
| expo                                  | 4.11.0
| node                                  | 16.7.0
| yarn                                    | 1.22.11

**Comment by ahmetkuslular** [comment]
same problem !!

**Comment by andrelfnavarro** [comment]
I'm having the same problem.

I could get past the errors by doing this: 

`typescript
navigation.dispatch(
        CommonActions.navigate({
          name: 'Listagem',
        })
      );
`

But it's not that great...

**Comment by satya164** [comment]
https://reactnavigation.org/docs/typescript/#annotating-usenavigation

**Comment by Fabianolvs** [comment]
Same issue here, it happens onlyy with useNavigation, if I use prop navigation it works normally

**Comment by daihovey** [comment]
Same issue
