### ISSUE TITLE
Is there any plan to polish CardStyleInterpolators.forModalPresentationIOS + ScrollView gestures

### ISSUE THREAD

**Issue by gaodeng** [react-navigation/react-navigation#9908]
### Current behavior

Thanks to the react navigation team for providing such a high quality navigation library. However, the only minor flaw is that CardStyleInterpolators.forModalPresentationIOS + ScrollView gestures are not quite native-like yet.
Is there any plan to polish it a bit, similar to the implementation of the gesture in react-native-bottom-sheet, it would be perfect!

### Expected behavior

Gestures similar to iOS 13 

### Reproduction

https://github.com/gorhom/react-native-bottom-sheet

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/stack                |  6.0.7

**Comment by KrifaYounes** [comment]
you can try this but it's not perfect 
if you find a better solution or improve it will be perfect.


```
import React, { useState, useRef, useCallback } from 'react';
import { View, StyleSheet, Dimensions } from 'react-native';
import { ScrollView } from 'react-native-gesture-handler';

const ModalScreenPresentationIOSWithScrollView = ({ theme, navigation }) => {

    const handleScroll = useCallback(
        ({ nativeEvent }) => {
            setContentOffSetYScrollView(
                Math.min(
                    nativeEvent.contentOffset.y,
                    Math.max(0, scrollViewHeight - Dimensions.get('window').height + 239)
                )
            );
        },
        [scrollViewHeight]
    );
    

    return (
        <View style={styles.container}>
            <GestureHandlerRefContext.Consumer>
                {(ref) => (
                    <ScrollView
                        ref={scrollViewRef}
                        waitFor={contentOffSetYScrollView < 0 ? ref : undefined}
                        scrollToOverflowEnabled
                        onScroll={handleScroll}
                        scrollEventThrottle={16}
                       
                    >
                        <View>...</View>
                    </ScrollView>
                )}
            </GestureHandlerRefContext.Consumer>

            
        </View>
    );
};

```

**Comment by gaodeng** [comment]
thanks @gorhom https://github.com/gorhom/react-navigation-scrollable-modal
