### ISSUE TITLE
Drawer Navigator not rendering any view when drawerPosition: 'right'

### ISSUE THREAD

**Issue by muneebahmed97** [react-navigation/react-navigation#9909]
### Current behavior

Drawer Navigator is not rendering anything on both android & ios when drawerPosition: 'right' but it works when drawerPosition: 'left'.
The code I'm using is following:

**Drawer Navigator showing from right:**
![Screenshot_1631030034](https://user-images.githubusercontent.com/26996157/132375050-16c2aeac-381a-42c8-b81a-67a167ee4c57.png)
![simulator_screenshot_74B06792-BF6B-4C3A-81BD-0D45A9558490](https://user-images.githubusercontent.com/26996157/132375210-fac0f64c-17b6-46a1-b5f8-2a35677de91c.png)

**Drawer Navigator showing from left:**
![Screenshot_1631030150](https://user-images.githubusercontent.com/26996157/132375485-3afa7903-3ecf-4b72-938c-30f48b806797.png)
![simulator_screenshot_7BAF809C-7A00-4B7A-9EA2-2353C276AAB4](https://user-images.githubusercontent.com/26996157/132375520-2a7635a5-a890-44eb-9298-c1ea95ccf68b.png)

`<Drawer.Navigator
      screenOptions={{
        ...TransitionPresets.SlideFromRightIOS,
        swipeEnabled: false,
        headerShown: false,
        drawerPosition: 'right',
        drawerType: 'slide',
        drawerStyle: {
          width: '50%',
        },
      }}
      drawerContent={props => <DrawerScreen {...props} />}>
      <Drawer.Screen name={SCREENS.UserHome} component={UserHome} />
      <Drawer.Screen name={SCREENS.UserShopper} component={UserShopper} />
      </Drawer.Navigator>`
      

### Expected behavior

I want the drawer to show from the right side just like how it is shown from the left side.
attaching a screenshot below.
![Screenshot 2021-09-07 at 8 59 24 PM](https://user-images.githubusercontent.com/26996157/132375798-0565a100-79ea-4bd1-9d11-44f5ee9aad0f.png)

### Reproduction

https://reactnavigation.org/docs/drawer-navigator/#options

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |
| @react-navigation/bottom-tabs          |
| @react-navigation/drawer               |
| @react-navigation/material-bottom-tabs |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                |
| @react-navigation/native-stack         |
| react-native-safe-area-context         |
| react-native-screens                   |
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           |
| expo                                   |
| node                                   |
| npm or yarn                            |

**Comment by tomo10** [comment]
still an issue

**Comment by tomo10** [comment]
The following worked for me:

const { width } = Dimensions.get('window');
const DrawerWidth = width * 0.8;

Add the following to your Drawer.Navigator screenOptions:

screenOptions={{
          headerShown: false,
          drawerPosition: 'right',
          drawerStyle: {
            width: DrawerWidth,
            left: width,
          },
        }}

**Comment by pi0trpietruszewski** [comment]
Same issue
