### ISSUE TITLE
[RN6][Bottom-tabs][Android only] border top suddenly showing and no way to get rid of it

### ISSUE THREAD

**Issue by Alaa-Ben** [react-navigation/react-navigation#9914]
### Current behavior

After upgrading from React Navigation 5 to 6, a blue border top appeared, and no way to remove it. See attached pictures. I tried borderTopWidth: 0, elevation: 0, and this like that but doesn't change anything. Issue happening on Android only.
![Screenshot_20210908-153643_Qucit Bike](https://user-images.githubusercontent.com/26058727/132520367-2e6d6423-35a2-4951-8855-e8ff351cf83f.jpg)
![Screenshot_20210908-153845_Qucit Bike](https://user-images.githubusercontent.com/26058727/132520371-4116be44-2303-451e-b801-41a9c5e72cb5.jpg)
![Capture d’écran 2021-09-08 à 15 40 59](https://user-images.githubusercontent.com/26058727/132520460-65e9b153-2ea4-49a0-88f1-78567a411e02.png)

### Expected behavior

No border showing

### Reproduction

https://reactnavigation.org/docs/bottom-tab-navigator

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.0.2
| @react-navigation/bottom-tabs          | 6.0.5
| @react-navigation/drawer               |
| @react-navigation/material-bottom-tabs |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                | 6.0.7
| @react-navigation/native-stack         | 6.1.0
| react-native-safe-area-context         | 3.3.2
| react-native-screens                   | 3.6.0
| react-native-gesture-handler           | 1.10.3
| react-native-reanimated                | 1.13.2
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           | 0.65.1
| expo                                   |
| node                                   | 12.21.0
| npm or yarn                            | 6.14.11

**Comment by KrifaYounes** [comment]
try this : 

```

const TAB_BAR_OPTIONS_V6 = (theme) => {
    return {
        tabBarStyle: {
            borderTopColor: 'transparent',
            borderTopWidth: 0,
            backgroundColor: theme.colors.primaryBackground,
        },
    };
};

const BottomTab = (props) => {

    return (
        <>
            <BottomTabNavigator.Navigator
                initialRouteName={ROUTES.HOME}
                sceneContainerStyle={{
                    backgroundColor: theme.colors.primaryBackground,
                }}
                safeAreaInsets={applyBottomStyle && { bottom: 10 }}
                // react navigation v6
                screenOptions={TAB_BAR_OPTIONS_V6(theme)}
                // react v5
                // tabBarOptions={TAB_BAR_OPTIONS(theme)}
            >
```

**Comment by Alaa-Ben** [comment]
@KrifaYounes Where does theme come from ?

**Comment by mattahorton** [comment]
hey @Alaa-Ben did you figure this one out?
