### ISSUE TITLE
Material Bottom Tab compressed on iPhone 11 Pro iOS 14+ (small tab)

### ISSUE THREAD

**Issue by VictorioMolina** [react-navigation/react-navigation#9919]
### Typical navigation structure
In my App I have nested navigators. A "root" stack which contains a bottom tab that contains stacks.

### Problem
The problem I am experiencing is that, sometimes, in my physical iPhone 11 Pro (not in my iPhone 12 Pro Max emulator), the height of my material bottom tab is "compressed". Most of the time it renders correctly, but for some reason my tab sometimes looks like [this](https://user-images.githubusercontent.com/7931279/96848865-393ce580-1455-11eb-83f0-024c1b8ba3e4.png).

### People getting same error
I have seen other people experiencing this same error in previous versions: https://github.com/react-navigation/react-navigation/issues/8972

And, also, a related bug: https://github.com/react-navigation/react-native-safe-area-view/issues/136

In my case, I am suffering it since v5.

### Expected behavior

The bottom tab height shouldn't be compressed on my physical iOS device.

### Reproduction

I can't reproduce an example, as it happens randomly. Here is a code example from other user: https://github.com/react-navigation/react-navigation/issues/8972#issue-727210043

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [X] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | "^6.0.2"
| @react-navigation/bottom-tabs          | "^6.0.5"
| @react-navigation/material-bottom-tabs | "^6.0.5"
| @react-navigation/stack                | "^6.0.7"
| react-native-safe-area-context         | "3.2.0"
| react-native-screens                   | "^3.7.0"
| react-native-gesture-handler           | "~1.10.2"
| react-native-reanimated                | "~2.2.0"
| react-native-tab-view                  | "^2.15.2"
| react-native-pager-view                | "5.0.12"
| react-native                           | "42.0.0"
| expo                                   | "^42.0.3"
| node                                   | "15.9.0"
| yarn                            | "1.22.10"

**Comment by zwh1666258377** [comment]
i hava same issues

**Comment by DovletAmanov** [comment]
Same issue +1

**Comment by Rquaicoo** [comment]
Any solution?
