### ISSUE TITLE
Many new nested views and performance impact after updating from v4 to v5 or v6

### ISSUE THREAD

**Issue by Fabio-GC** [react-navigation/react-navigation#9923]
### Current behavior

We have been using react-navigation 4 for 2 years and had a nice experience with it. We decided to update to v5 recently and since then we are experiencing a few issues. We have also tried with v6 and we face the same issue.

We started diving into this because our automated UI tests started failing when Appium was not able to find the components on the iOS application.

Appium limits the number of nested views to 50 when processing the view tree. There are already issues opened in their repo but I would also like to get more into why is this happening after the migration.

I've used the debug view hierarchy feature from Xcode to try to understand what is the actual view tree of the app. This is a slice of all the views that are in the hierarchy when running the application You can see the difference in the following screenshots:

RN4: 
![image](https://user-images.githubusercontent.com/76812257/132830509-8a888dc5-505b-45fe-8eed-856f23fd59da.png)

This is already a fair amount of views but this is how this looks in RN5: enter image description here
![image](https://user-images.githubusercontent.com/76812257/132830559-5440668e-a077-4643-9a82-9840a1a0d094.png)

The number of views has been increased by 30 approx.

The performance has also been impacted. There are slight delays between the user triggers the action and the navigation happens. Not sure if that is directly related to the fact that more views are on the stack now.

The delay is unnoticeable in release mode.

I was wondering if anyone would be aware of a way to reduce the number of child views that appeared after the transition from react-navigation 4 to 5 or 6.

### Expected behavior

The number of view remain the same as it was with react navigation 4

### Reproduction

I can't give a code to reproduce since is private. But any app with some screens that were build with react navigation 4 should have the same behaviour.

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native  6.0.2           |
| @react-navigation/bottom-tabs    6.0.5      |
| @react-navigation/material-top-tabs  6.0.2 |
| @react-navigation/stack     6.0.7          |
| react-native-safe-area-context    3.2.0     |
| react-native-screens     3.3.0              |
| react-native-gesture-handler   1.10.3        |
| react-native-reanimated      2.2.0          |
| react-native-tab-view           3.0.0       |
| react-native-pager-view          5.4.1      |
| react-native                0.64.1           |
| node                     12.22.1              |
| npm or yarn            1.22.10                |

**Comment by cristianoccazinsp** [comment]
Found anything? Are you using react-native-screens so views are detatched?

**Comment by Fabio-GC** [comment]
Hey @cristianoccazinsp 
Yes, we are using react-native-screens but nothing changes. We have tried to remove as many nested navigator as posible but the problem still happens

**Comment by fantasyado** [comment]
facing the same issue

**Comment by fantasyado** [comment]
> facing the same issue

Edit, setting presentation to "modal" worked for me.
https://github.com/appium/appium/issues/14825#issuecomment-1190019763

**Comment by veeramarni** [comment]
@Fabio-GC  did you find solution to it?

**Comment by juliofihdeldev** [comment]
Same there

**Comment by Gnative** [comment]
Recently been looking at this too.
