### ISSUE TITLE
`useLinkProps` returns a malformed href

### ISSUE THREAD

**Issue by kevinwcyu** [react-navigation/react-navigation#9930]
### Current behavior

[`useLinkProps`](https://github.com/react-navigation/react-navigation/blob/main/packages/native/src/useLinkProps.tsx#L67) is returning the `to` param directly as the `href` which results in a malformed href when passed to a link component.

See the reproduction
- On the web, the "Sign up" and "Nested" links have a path that ends in `/[object Object]`. Hover over the links to see the malformed URL.
- On iOS or Android, when using a custom `Link` component is used, it can potentially cause an error as the `href` is not a string. Run the reproduction on iOS or Android and click the link that is labelled `(href is malformed and crashes on iOS and Android)`.

### Expected behavior

- When `Platform.OS === "web"` the `href` should be a well-formed string that is a valid href.
- When `Platform.OS !== "web"` there should not be an `href` returned.
- `useLinkProps` should provide the correct `href` for nested navigators as well.

### Reproduction

https://snack.expo.dev/@kevinwcyu/react-navigation-link-props-href

### Platform

- [X] Android
- [X] iOS
- [X] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | ^6.0.2 |
| @react-navigation/native-stack         | ^6.1.0 |
| react-native-safe-area-context         | ^3.2.0 |
| react-native-screens                   | ~3.4.0 |
| react-native                           | 0.63.4 (from Expo SDK 42) |
| expo                                   | 42 |
| node                                   | 14.17.6 |
| yarn                            | 1.22.11 |

**Comment by JJK801** [comment]
same problem here.

**Comment by JJK801** [comment]
@kevinwcyu here is a Q&D workaround:

``` javascript
type LinkProps = Parameters<typeof RNLink>[0]

type Route = {
  name: string
  params?: object
  state?: MinimalState
}

type MinimalState = {
  index: number;
  routes: Route[];
};

const buildState = (routeConfig: LinkProps['to']): MinimalState => {
  return {
    index: 0,
    routes: [
      buildRoute(routeConfig)
    ]
  }
}

const buildRoute = (routeConfig: LinkProps['to']) => {
  const { screen, params: { screen: subScreen, params: subParams, ...params } = {} } = routeConfig as { screen: string, params: any }
  let state

  if (subScreen) {
    state = buildState({ screen: subScreen, params: subParams })
  }

  return ({
    name: screen,
    state,
    params
  })
}

const buildHref = useCallback((to) => {
  if (typeof to === 'object') {
    const state = buildState(to)

    const path = getPathFromState(state, mainLinking);

    return path;
  } else {
    return to
  }
}, [])

```

`mainLinking` is the object provided to linking.config
