### ISSUE TITLE
presentation: 'modal' interpolates bottom radius causing visual bug when used with tab navigator

### ISSUE THREAD

**Issue by albinmartinsson91** [react-navigation/react-navigation#9933]
### Current behavior

Since `6.0` was introduced the transition specification for `presentation: 'modal'` seems to have been updated to follow the new `ModalPresentationIOS `-preset. Unfortunately this update causes some issues when used within a `Tab.Navigator`-context. 

The border-radius-interpolation is applied to all four edges causing a visual bug.

### Expected behavior

The border-radius-interpolation should only be applied to `borderTopLeftRadius` and `borderTopRightRadius`. 

### Reproduction

https://snack.expo.dev/@albinmartinsson/presentation-modal---glitch

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

| Package      | Version |
| ----------- | ----------- |
| @react-navigation/stack      | 6.0.7       |
| @react-navigation/bottom-tabs   | 6.0.5        |

**Comment by albinmartinsson91** [comment]
Yes this is still an issue.

**Comment by arunim2405** [comment]
can confirm this issue, causing placement issues for my components as well. Refer: 
![Simulator Screen Recording - iPhone 12 - 2021-09-24 at 13 58 35](https://user-images.githubusercontent.com/47343112/134796085-43c72a1e-a7c6-4cc9-bcf4-6c4dc0b262fb.gif)
![Simulator Screen Recording - iPhone 12 - 2021-09-24 at 13 57 56](https://user-images.githubusercontent.com/47343112/134796092-888f9232-b1c8-4fda-8526-9e8d420f80b1.gif)

**Comment by satya164** [comment]
Modals are intended to be used at root. It's not proper UX to have them nested inside tab navigator.

While it's not needed visually, the `borderRadius` is intentionally added for performance reasons. We won't change it since it works fine with its intended usage.

If you really want modals inside tab navigator for some reason, you can provide a custom `cardStyleInterpolator` which uses different border radius.

**Comment by b0n1q** [comment]
this is still an issue even it's not a nested navigator
the animation behaviour is weird

**Comment by kmonty12** [comment]
Did anybody find a solution here using a custom cardStyleInterpolator?

**Comment by JasonPan** [comment]
@kmonty12

1. Copy `forModalPresentationIOS` from here: https://github.com/react-navigation/react-navigation/blob/main/packages/stack/src/TransitionConfigs/CardStyleInterpolators.tsx#L93
2. Disable `borderBottomLeftRadius` and `borderBottomRightRadius`.

Notes
 - You can override the default exported components by doing something like the following, if you don't want to copy it manually

```ts
import { Platform } from "react-native";
import { TransitionPresets, StackCardInterpolationProps, StackCardInterpolatedStyle } from '@react-navigation/stack';

// Note: if not using the name `forModalPresentationIOS`, need to rename the function using something like `Object.defineProperty(Test, "name", {value: "forModalPresentationIOS"});`, as `react-navigation` has specific checks for the interpolator name.
const forModalPresentationIOS = (props: StackCardInterpolationProps): StackCardInterpolatedStyle => {
  const config = TransitionPresets.ModalPresentationIOS.cardStyleInterpolator(props);
  config.cardStyle.borderBottomLeftRadius = undefined;
  config.cardStyle.borderBottomRightRadius = undefined;
  return config
};

const fixTabNestedStackCardStyleInterpolator = Platform.select({
  ios: forModalPresentationIOS,
  default: TransitionPresets.BottomSheetAndroid.cardStyleInterpolator,
});


...


<Stack.Screen
  name="Test screen"
  component={TestCompoment}
  options={{ cardStyleInterpolator: fixTabNestedStackCardStyleInterpolator }}
/>

```

**Comment by EvgenMarchuk-art** [comment]
> @kmonty12
> 
> 1. Copy `forModalPresentationIOS` from here: https://github.com/react-navigation/react-navigation/blob/main/packages/stack/src/TransitionConfigs/CardStyleInterpolators.tsx#L93
> 2. Disable `borderBottomLeftRadius` and `borderBottomRightRadius`.
> 
> Notes
> 
> * You can override the default exported components by doing something like the following, if you don't want to copy it manually
> 
> ```ts
> import { Platform } from "react-native";
> import { TransitionPresets, StackCardInterpolationProps, StackCardInterpolatedStyle } from '@react-navigation/stack';
> 
> // Note: if not using the name `forModalPresentationIOS`, need to rename the function using something like `Object.defineProperty(Test, "name", {value: "forModalPresentationIOS"});`, as `react-navigation` has specific checks for the interpolator name.
> const forModalPresentationIOS = (props: StackCardInterpolationProps): StackCardInterpolatedStyle => {
>   const config = TransitionPresets.ModalPresentationIOS.cardStyleInterpolator(props);
>   config.cardStyle.borderBottomLeftRadius = undefined;
>   config.cardStyle.borderBottomRightRadius = undefined;
>   return config
> };
> 
> const fixTabNestedStackCardStyleInterpolator = Platform.select({
>   ios: forModalPresentationIOS,
>   default: TransitionPresets.BottomSheetAndroid.cardStyleInterpolator,
> });
> 
> 
> ...
> 
> 
> <Stack.Screen
>   name="Test screen"
>   component={TestCompoment}
>   options={{ cardStyleInterpolator: fixTabNestedStackCardStyleInterpolator }}
> />
> ```

Good day, the solution for iOS works perfectly. How can I achieve the same for Android?
