### ISSUE TITLE
Issue with Keyboard avoiding view and createNativeStackNavigator

### ISSUE THREAD

**Issue by bharatgupta99** [react-navigation/react-navigation#9939]
### Current behavior

```
const App = () => {
  enableScreens();
  const Stack = createNativeStackNavigator();

  return (
    <KeyboardAvoidingView
      behavior={Platform.OS === 'ios' ? 'padding' : undefined}
      style={{flex: 1}}>
      <NavigationContainer>
        <Stack.Navigator>
          <Stack.Screen name="Page1" component={Page1} />
          <Stack.Screen name="Page2" component={Page2} />
        </Stack.Navigator>
      </NavigationContainer>
    </KeyboardAvoidingView>
  );
};

const Page1 = ({navigation}) => {
  return (
    <View
      style={{
        flex: 1,
        backgroundColor: 'green',
        alignItems: 'center',
        justifyContent: 'center',
      }}>
      <Pressable
        style={{
          height: 42,
          width: 100,
          backgroundColor: 'yellow',
          justifyContent: 'center',
          alignItems: 'center',
        }}
        onPress={() => {
          navigation.navigate('Page2');
        }}>
        <Text>Go to Page2</Text>
      </Pressable>
    </View>
  );
};

const Page2 = () => {
  return (
    <View style={{flex: 1, alignItems: 'center', justifyContent: 'center'}}>
      <TextInput autoFocus style={{width: 100, height: 40, borderWidth: 1}} />
    </View>
  );
};
````
Issue - While navigating to `Page2` and navigating back to `Page1` there is a weird white background behind the Keyboard.

UI Issue video - [Link](https://drive.google.com/file/d/1VqZcvA1rrosaQn77PNwerAdV6pujsqUY/view?usp=sharing)

### Expected behavior

The white background should not appear.

### Reproduction

https://github.com/bharatgupta99/react-native-keyboard-issue

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | ^5.x
| @react-navigation/bottom-tabs          |
| @react-navigation/drawer               |
| @react-navigation/material-bottom-tabs |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                |
| @react-navigation/native-stack         |
| react-native-safe-area-context         | 3.3.2
| react-native-screens                   | 3.7.2
| react-native-gesture-handler           | 1.10.3
| react-native-reanimated                | 2.2.2
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           |
| expo                                   |
| node                                   |
| npm or yarn                            |

**Comment by balazs31** [comment]
hey @bharatgupta99 

I had the same problem but setting the theme prop on the NavigationContainer fixed the issue:

```
import {
  NavigationContainer,
  NavigationContainerRef,
  DefaultTheme,
} from '@react-navigation/native';

const theme = {
  ...DefaultTheme,
  dark: false,
  colors: {
    ...DefaultTheme.colors,
    background: colors.BACKGROUND, <- the color of your screen
  },
};

in the component: 

return (
    <NavigationContainer
      theme={theme}>
          ....content
    </NavigationContainer>
  );
```

If this does not work or your screens don't have a general BG color, you can set on each navigator's screenOptions the cardOverlay prop.

**Comment by pixelknitter** [comment]
This issue was brought up in this [medium post](https://chrisfrewin.medium.com/a-keyboard-avoiding-view-for-react-native-in-2021-196701ff0608) - wondering if this is something that may help fix the issue internally.

**Comment by bharatgupta99** [comment]
Actually, the issue was that I was wrapping the whole `StackNavigator` inside `KeyboardAvoidView` rather than just the screen which needs a keyboard. Hence removing the `KeyboardAvoidView` wrapped over `StackNavigator` fixed the issue.
