### ISSUE TITLE
Prevent back swipe gesture on modal iOS

### ISSUE THREAD

**Issue by wilau2** [react-navigation/react-navigation#9945]
### Current behavior

I did not find a way to prevent the horizontal back gesture on iOS. 

When you have a modal (especially a not full screen one on tablet) you should only be able to dismiss it with the vertical swipe and not the horizontal back swipe gesture. 

### Expected behavior

back swipe gesture should be disabled on vertically closable modals on iOS.

### Reproduction

will provided later

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |
| @react-navigation/bottom-tabs          |
| @react-navigation/drawer               |
| @react-navigation/material-bottom-tabs |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                |
| @react-navigation/native-stack         |
| react-native-safe-area-context         |
| react-native-screens                   |
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           |
| expo                                   |
| node                                   |
| npm or yarn                            |

**Comment by samuelbeaulieu** [comment]
Simply add `gestureEnabled: false` to your modal's screenOptions.

Exemple:
```js
<RootStack.Group
  screenOptions={{
    presentation: 'modal',
    gestureEnabled: false,
  }}
>
  <RootStack.Screen
    name="ViewMedias"
    component={ViewMediasScreen}
    options={ViewMediasOptions}
  />
</RootStack.Group>
```

**Comment by ombogdanJoinToIt** [comment]
this question is not closed. because there is no solution

**Comment by gldkru** [comment]
> this question is not closed. because there is no solution

Use `gestureEnabled: false` in screen options

and for dynamic update

```jsx
React.useEffect(
    () => navigation.setOptions({ gestureEnabled: !success }),
    [navigation, success],
);
```

**Comment by vantran-agilityio** [comment]
> > this question is not closed. because there is no solution
> 
> Use `gestureEnabled: false` in screen options
> 
> and for dynamic update
> 
> React.useEffect(
>     () => navigation.setOptions({ gestureEnabled: !success }),
>     [navigation, success],
> );

What is `!success`?
