### ISSUE TITLE
@react-navigation/material-top-tabs lags during screen change

### ISSUE THREAD

**Issue by RobinBobin** [react-navigation/react-navigation#9946]
### Current behavior

I have a `@react-navigation/material-top-tabs` with 3 tabs drawn at the bottom of the screen (`tabBarPosition={"bottom"}`).

Swiping is disabled.

The first and the third tabs are lightweight, the second tab contains a [`react-native-qrcode-scanner`](https://www.npmjs.com/package/react-native-qrcode-scanner) instance.

When I switch between tab 1 and tab 3, using the tab bar, the screens change with a terrible lag. I used `react-native-pager-view` to check if it has something to do with the bug, but everything's fine.

`Bug38_PagerView` and `Bug38_TabView` are absolutely the same with the exception that one uses `@react-navigation/material-top-tabs` and the other uses `react-native-pager-view`.

This is the release version of course. The debug version behaves absolutely the same.

https://user-images.githubusercontent.com/6296813/133794876-8b61a0e3-44aa-4c7e-b130-fd14dd7b111b.mp4

### Expected behavior

There's no lag when changing screens using `@react-navigation/material-top-tabs`.

### Reproduction

https://github.com/RobinBobin/bug38

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [X] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |^6.0.2
| @react-navigation/material-top-tabs    |^6.0.2
| @react-navigation/stack                |^6.0.7
| react-native-safe-area-context         |^3.3.2
| react-native-screens                   |^3.7.2
| react-native-gesture-handler           |^1.10.3
| react-native-reanimated                |^2.2.2
| react-native-tab-view                  |^3.1.1
| react-native-pager-view                |^5.4.4
| react-native                           |0.64.2
| node                                   |v15.8.0
| npm or yarn                            |npm

**Comment by RobinBobin** [comment]
> Couldn't find version numbers for the following packages in the issue:
> 
> * `@react-navigation/bottom-tabs`
> * `@react-navigation/drawer`
> * `@react-navigation/material-bottom-tabs`
> 
> Can you update the issue to include version numbers for those packages? The version numbers must match the format 1.2.3.

I don't use the mentioned packages.

**Comment by Emill-Z** [comment]
Have the same bug 
Switching between tabs does not work as expected

"@react-navigation/material-top-tabs": "^6.0.2",

https://user-images.githubusercontent.com/24586456/134171537-420802ca-e562-4075-a441-3b8d6d9bf944.mov

**Comment by cjhines** [comment]
I'm also experiencing really bad performance while moving between tabs.

**Comment by yanush** [comment]
I'm also experiencing the same issue, for me it's only in iOS.

**Comment by cjhines** [comment]
I think the underlying `react-native-tab-views` is just incredibly glitchy currently:

https://github.com/satya164/react-native-tab-view/issues/1250

**Comment by Emill-Z** [comment]
hm, downgrade to react-native-pager-view v4.2.4 works for me 
But I am sure I will get some bugs because of the downgrade

**Comment by yanush** [comment]
@Emill-Z Well it fixed the issue of lags, but on android if you have an initialRouteName that is not the first tab, it's broken

**Comment by Emill-Z** [comment]
The reason why it works in 4.2.4 is the lib does not show intermediate tabs
After clicking on a tab, we immediately go to the selected tab
That is why focus on intermediate tabs do not happen so we do not get the "wrong" index of the tab

But in v5 we see all intermediate tabs while the tab is switching to the tab we clicked on
And each tab emits its own index.

**Comment by Emill-Z** [comment]
I see two ways to fix it 
1. Fix the library
2. Create custom tab bar with animation

**Comment by Emill-Z** [comment]
For example, you can provide your own tab bar like this
PS: This code is not perfect it is just an example 

```
import React from 'react'
import { MaterialTopTabBarProps, MaterialTopTabNavigationOptions } from '@react-navigation/material-top-tabs'
import { View, Pressable, Route, Animated, Dimensions } from 'react-native'
import { SFProTextMedium, SFProTextRegular } from '~/components/StyledText'
import { styles } from './styles'

const { width , height } = Dimensions.get('screen')

type Measures = {
	x: number
	y: number
	width: number
	heigth: number
}

/** @Info For more information about MaterialTopTabNavigator read https://reactnavigation.org/docs/material-top-tab-navigator/ */
export const TopTabBarNavigator = ({ state, descriptors, navigation }: MaterialTopTabBarProps) => {

	const [dataState, setData] = React.useState<any[]>([])
	const [inputRangeState, setInputRange] = React.useState<any[]>([])
	const [measuresState, setMeasures] = React.useState<Measures[]>([])
	const containerRef = React.useRef()
	const tabIndex = React.useRef(new Animated.Value(0)).current

	React.useEffect(() => {
		setData(state.routes.map(i => ({ ...i, ref: React.createRef() })))
	}, [])

	const measureLayout = () => {
		const measures: Measures[] = []

		dataState.forEach((i) => {
			 i.ref.current.measureLayout(containerRef.current, (x: number, y: number, width: number, heigth: number) => {
				 measures.push({
					 x,
					 y,
					 width,
					 heigth,
				 })

				if (measures.length === dataState.length) {
					setMeasures(measures)
				}
			 })
		})
	}

	React.useEffect(() => {
		if (!dataState.length) { return }

		setInputRange(
			dataState.map((_, i) => i * width)
		)
	}, [dataState])


	const onPress = (route: Route, index: number, isFocused: boolean): void => {
		const event = navigation.emit({
			type: 'tabPress',
			target: route.key,
			canPreventDefault: true,
		})

		Animated.timing(tabIndex, { toValue: index * width, useNativeDriver: false }).start()

		if (!isFocused && !event.defaultPrevented) {
			// The `merge: true` option makes sure that the params inside the tab screen are preserved
			navigation.navigate<any>({ name: route.name, merge: true })
		}
	}

	const getLabel = (options: MaterialTopTabNavigationOptions, route: Route): string => (
		options.tabBarLabel !== undefined
			? options.tabBarLabel
			: options.title !== undefined
				? options.title
				: route.name
	)


	return (
		<View style={styles.container} ref={containerRef} onLayout={() => {measureLayout()}}>
			{dataState.map((route: Route, index: number) => {
				const { options } = descriptors[route.key]

				const label = getLabel(options, route)

				const isFocused = state.index === index

				const onLongPress = () => {
					navigation.emit({ type: 'tabLongPress', target: route.key })
				}

				return (
					<Pressable
						ref={route.ref}
						onPress={() => onPress(route, index, isFocused)}
						onLongPress={onLongPress}
						key={index}
						style={styles.tab}
					>
						<SFProTextRegular style={styles.tabLabel}>{label}</SFProTextRegular>
					</Pressable>
				)
			})}


			{
				!!(measuresState.length && inputRangeState.length)&& <Indicator measures={measuresState} inputRange={inputRangeState} tabIndex={tabIndex}/>
			}
		</View>
	)
}

type IndicatorProps = {
	measures: Measures[]
	inputRange: number[]
	tabIndex: Animated.Value
}

function Indicator({ measures, inputRange, tabIndex }: IndicatorProps) {
	const indicatorWidth = tabIndex.interpolate({
		inputRange,
		outputRange: measures.map(i => i.width)
	})
	const translateX = tabIndex.interpolate({
		inputRange,
		outputRange: measures.map(i => i.x)
	})

	return (
		<Animated.View style={[{
			position: 'absolute',
			bottom: 0,
			left: 0,
			width: indicatorWidth,
			borderBottomWidth: 2,
			borderColor: 'black',
			transform: [{
				translateX
			}],
		}]}></Animated.View>
	)
}

```

**Comment by Emill-Z** [comment]
The video how it looks to code above 
https://user-images.githubusercontent.com/24586456/134373859-677fbfd5-4a02-4a0f-b255-88f150314038.mov

**Comment by yanush** [comment]
Is it possible to navigate without animation when clicking the tab bar?
It might be a work around for me, but I couldn't find out how to achieve that behavior.
I know that react-native-pager-view supports both setPage and setPageWithoutAnimation so there must be a way

**Comment by Emill-Z** [comment]
@yanush I have not found such an option [here](https://reactnavigation.org/docs/material-top-tab-navigator/#options)

**Comment by yanush** [comment]
@Emill-Z where in this page? I read it already

**Comment by RobinBobin** [comment]
I've just followed the guide to install version 6 of react-navigation and saw the bug disappeared :tada: .

The versions of the relevant modules I got installed:
```
"@react-navigation/native": "^6.0.4",
"@react-navigation/material-top-tabs": "^6.0.4",
"@react-navigation/stack": "^6.0.9",
"react-native-safe-area-context": "^3.3.2",
"react-native-screens": "^3.8.0",
"react-native-gesture-handler": "^1.10.3",
"react-native-tab-view": "^3.1.1",
"react-native-pager-view": "^5.4.6",
```

**Comment by Jamal-ReachFirst** [comment]
Reopen this issue

**Comment by RobinBobin** [comment]
What for, @Jamal-ReachFirst ?

**Comment by Jamal-ReachFirst** [comment]
> What for, @Jamal-ReachFirst ?

In order to resolve it, (swipe screens are faster but delay and lag on tab press)

**Comment by RobinBobin** [comment]
The bug disappeared for me. I think a new issue should be opened, if you're facing it.

**Comment by Jamal-ReachFirst** [comment]
> 

Yes, it must be opened

**Comment by Jamal-ReachFirst** [comment]
#10858 

This is the exact issue

> > 
> 
> Yes, it must be opened

#10858 

It is already opened

**Comment by Jamal-ReachFirst** [comment]
> 

#11047

**Comment by laiqaGMIT** [comment]
Yes open this issue. Facing the same thing.

**Comment by yawin** [comment]
I also facing the same thing.

**Comment by sayan-avantai** [comment]
facing the same thing    
```
 "@react-navigation/material-top-tabs": "^7.1.0",
    "react-native-pager-view": "^6.7.0",
    "react-native": "0.76.2",
```
too much slow when moving to other tabs, index of the tabs is not maintaining.
