### ISSUE TITLE
TS2304: Cannot find name 'screen'.

### ISSUE THREAD

**Issue by blacklakeapp** [react-navigation/react-navigation#9964]
### Current behavior

<img width="665" alt="截屏2021-09-24 下午3 42 18" src="https://user-images.githubusercontent.com/84960744/134637341-3b9e2bd3-b265-4695-af4d-c3720ab3d2e4.png">

### Expected behavior

<img width="463" alt="截屏2021-09-24 下午3 44 47" src="https://user-images.githubusercontent.com/84960744/134637619-5b01c4c6-1dce-4b8e-a82f-8c3517e43961.png">

### Reproduction

-

### Platform

- [ ] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |  6.0.2
| @react-navigation/bottom-tabs          | 5.11.10
| @react-navigation/stack                | 5.14.4

**Comment by satya164** [comment]
https://reactnavigation.org/docs/getting-started#minimum-requirements
