### ISSUE TITLE
[Material-top-tabs v6] Swiping too fast causes infinite automatic swiping

### ISSUE THREAD

**Issue by alz10** [react-navigation/react-navigation#9966]
### Current behavior

After swiping or tapping on two tabs quickly, it causes an automatic infinite swiping. There's no problem in expo snack provided below and i don't know why. The problem appears in bare react-native android project..

https://user-images.githubusercontent.com/38030623/134710376-0c77ea25-52d2-41a0-9852-fe8f5ce8d447.mp4

Also when swiping slowly back and fourth, it causes a sudden jump or flicker.

https://user-images.githubusercontent.com/38030623/134756420-075aff83-744f-4f24-bf59-25588aece90b.mp4

### Expected behavior

Normal swiping

### Reproduction

https://snack.expo.dev/8e-rQRiLX

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [X] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |^6.0.2
| @react-navigation/material-top-tabs    |^6.0.2
| react-native-screens                   |^1.4.2
| react-native-gesture-handler           |^1.10.3
| react-native-reanimated                |^2.2.2
| react-native-tab-view                  |^3.1.1
| react-native-pager-view                |^5.4.4
| react-native                           |0.65.1

**Comment by arunim2405** [comment]
Can confirm, I have also experienced the infinite swiping issue

**Comment by dorapax-lab** [comment]
I can also confirm this behaviour for android. Swiping too fast in IOS is crashing the app.

@react-navigation/bottom-tabs - N/A
@react-navigation/drawer - ^6.1.4
@react-navigation/material-bottom-tabs - N/A
@react-navigation/stack - ^6.0.7

**Comment by mrshahzeb7** [comment]
I am also facing this issue !
also vertical scroll is triggering tab change

**Comment by KashaTeplaya** [comment]
THe issue resolve in tab-view was in downgrading to react-native-page-view v4, but then initial route doesnt working for me

**Comment by mrshahzeb7** [comment]
> THe issue resolve in tab-view was in downgrading to react-native-page-view v4, but then initial route doesnt working for me

can you explain? I didn't get you 
how you solved it ?

**Comment by alz10** [comment]
### **Fixed:** 
Update `react-native-tab-view to v5.4.5` or latest version

**Comment by dorapax-lab** [comment]
@alz10 `react-native-tab-view` or `react-native-pager-view` ?

**Comment by dorapax-lab** [comment]
> ### **Fixed:**
> Update `react-native-tab-view to v5.4.5` or latest version

@alz10  react-native-tab-view or react-native-pager-view ?

**Comment by alz10** [comment]
> > ### **Fixed:**
> > Update `react-native-tab-view to v5.4.5` or latest version
> 
> @alz10 `react-native-tab-view` or `react-native-pager-view` ?

Sorry it's`react-native-pager-view`. It fixes the problem in android. I don't know yet in iOS

**Comment by sophiemoustard** [comment]
Does anyone has the same issue on ios ? it's not working for me

**Comment by dorapax-lab** [comment]
> Does anyone has the same issue on ios ? it's not working for me

Still exists and this is the reason https://github.com/callstack/react-native-pager-view/issues/458
