### ISSUE TITLE
How to animate a stack on mount/unmount?

### ISSUE THREAD

**Issue by 10000multiplier** [react-navigation/react-navigation#9967]
### Current behavior

As recommended in the docs I have set up the authentication flow like so:

```jsx
<NavigationContainer>
	{user ? <MainTabs /> : <AuthStack />}
</NavigationContainer>
```

This works well except that when the user logs in there is no animation.

### Expected behavior

It would be great if there was a way to slide out the sign in screen on `<AuthStack/>`, and slide in the home screen on the `<MainTabs/>` when the `user` state changes.

Or is it perhaps already possible and I'm simply missing something?

### Reproduction

https://github.com/bithoven-dev/ReactNavigationAuthenticationFlowsWithHooks/blob/master/src/App.js

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | "^6.0.1"
| @react-navigation/bottom-tabs          | "^6.0.1"
| @react-navigation/native-stack         | "^6.0.2"
| react-native-safe-area-context         | "3.2.0"
| react-native-screens                   | "~3.4.0"
| react-native-gesture-handler           | "~1.10.2"
| react-native-reanimated                | "^2.2.2"
| react-native-pager-view                | "^5.4.4"
| react-native                           | "https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz"
| expo                                   | "^42.0.0"
| node                                   | "15.0.1"
| yarn                            | "1.22.10"

**Comment by 10000multiplier** [comment]
It seems that bottomtabs cannot be nested inside a native stack without breaking navigation.

**Comment by satya164** [comment]
Per docs:

> we recommend to use a single Stack navigator and place the conditional inside instead of using 2 different navigators. This makes it possible to have a proper transition animation during login/logout.

So you should place your `MainTabs` in a screen inside a stack navigator to get stack navigator's animations.

**Comment by 10000multiplier** [comment]
> Per docs:
> 
> > we recommend to use a single Stack navigator and place the conditional inside instead of using 2 different navigators. This makes it possible to have a proper transition animation during login/logout.
> 
> So you should place your `MainTabs` in a screen inside a stack navigator to get stack navigator's animations.

Unfortunately this leads to a bug as documented in [#8860](https://github.com/react-navigation/react-navigation/issues/8860#issuecomment-738237168)
