### ISSUE TITLE
[v6] orientation not work

### ISSUE THREAD

**Issue by zwh1666258377** [react-navigation/react-navigation#9969]
### Current behavior

https://reactnavigation.org/docs/native-stack-navigator/#orientation

when I set this prop,The screen does not rotate after entering the target page.

### Expected behavior

I hope screen rotate after entering the target page.

### Reproduction

https://snack.expo.dev/9LZ5ItpXl

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [x] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [x] @react-navigation/stack
- [x] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| react-native-screens | ~3.4.0|
| @react-navigation/native | ^6.0.2|
| @react-navigation/native-stack | ^6.1.0|
| react-native-safe-area-context | 3.2.0|
|react-navigation/bottom-tabs|5.11.2|
|react-navigation/drawer|0.0.0|
|react-navigation/material-bottom-tabs|0.0.0|
|react-navigation/material-top-tabs|0.0.0|
|react-navigation/stack| ^6.0.7|

**Comment by kacperkapusciak** [comment]
Closing due to issue being tracked in `react-native-screens` repo https://github.com/software-mansion/react-native-screens/issues/1152

**Comment by osliver** [comment]
I'm not sure is It issue, but also not working if you app have only portrait mode 

<img width="253" alt="Снимок экрана 2022-04-19 в 13 02 09" src="https://user-images.githubusercontent.com/97607365/163980195-69c03733-425f-4df4-b7b6-6d562c2f40de.png">
