### ISSUE TITLE
Web - Navigation is broken after navigating back and forth across more than two screens via browser buttons

### ISSUE THREAD

**Issue by adamhari** [react-navigation/react-navigation#9971]
### Current behavior

My code includes a stack navigator with more than two screens. I am navigating from screen A to screen B, and then from screen B to screen C. When I use the browser buttons to navigate backwards twice to screen A, and then forwards twice to screen C, and then backwards once again, I see the following error:

```
TypeError: Cannot read properties of undefined (reading 'id')

useLinking.tsx:52

  49 | const id = window.history.state?.id;
  50 | 
  51 | if (id) {
> 52 |   const index = items.findIndex((item) => item.id === id);
     | ^  53 | 
  54 |   return index > -1 ? index : 0;
  55 | }
```

### Expected behavior

User should be able to navigate backwards multiple times and then forwards multiple times repeatedly.[](url)

### Reproduction

https://snack.expo.dev/@adamhari/web---navigation-is-broken-after-going-back-and-forth-9971

### Platform

- [ ] Android
- [ ] iOS
- [X] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.0.3
| @react-navigation/stack                | 6.0.8
| react-native-screens                   | 3.7.2
| react-native-gesture-handler           | 1.10.3
| react-native                           | 0.65.1
| node                                   | 16.4.0
| npm or yarn                            | 7.18.1

**Comment by react-one** [comment]
Not reproducible. All is working just right. latest expo. Or the same reproduction example that was provided. And also tempering with version. Not reproducible.

And for new expo installation::

```json
{
    "@react-navigation/native": "^6.0.4",
    "@react-navigation/stack": "^6.0.9",
    "expo": "~42.0.1",
    "expo-status-bar": "~1.0.4",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz",
    "react-native-gesture-handler": "~1.10.2",
    "react-native-safe-area-context": "3.2.0",
    "react-native-screens": "~3.4.0",
    "react-native-web": "~0.13.12"
}
```
It works perfectly. So i guess no further investigation is required.

The given repro was tested locally  and in different machines. And no problem with it.

**Comment by singhmks2010** [comment]
Hi @adamhari how did you make it work?, I am still facing this issue, when navigating back and forth across more than two screens via browser buttons. Please help me.

**Comment by adamhari** [comment]
@singhmks2010 It doesn't work for me either. It's not reproducible in the snack anymore which is odd, the exact same snack was able to reproduce it initially.

**Comment by singhmks2010** [comment]
oh ok @adamhari

**Comment by singhmks2010** [comment]
Hi core Team,  still I am facing this issue even after upgrading the version, below are the versions I am using:

"@react-navigation/bottom-tabs": "^6.0.9",
"@react-navigation/drawer": "^6.1.8",
"@react-navigation/native": "^6.0.6",
"@react-navigation/stack": "^6.0.11",

**Comment by kopax-polyconseil** [comment]
We are also experiencing this error in production: 

![image](https://user-images.githubusercontent.com/77674046/156540046-258b9a08-bc8c-4fd0-8c82-d5ee4ee1d494.png)


Did you find what was wrong @singhmks2010 ?

**Comment by listiani13** [comment]
We also run into the same issue, but on more intermittent basis & I think it's related to this comment https://github.com/react-navigation/react-navigation/pull/9970/files#r784475821

**Comment by liuyankit** [comment]
upvote on this issue, it can be reproduced by pushing stack repetitively and quickly
