### ISSUE TITLE
Unable to resolve module @react-navigation/stack

### ISSUE THREAD

**Issue by abhitheawesomecoder** [react-navigation/react-navigation#9976]
### Current behavior

Unable to resolve module @react-navigation/stack from E:\expoapps\is-hr\App.tsx: @react-navigation/stack could not be found within the project.
[16:51:01]
[16:51:01] If you are sure the module exists, try these steps:
[16:51:01]  1. Clear watchman watches: watchman watch-del-all
[16:51:01]  2. Delete node_modules and run yarn install
[16:51:01]  3. Reset Metro's cache: yarn start --reset-cache
[16:51:01]  4. Remove the cache: rm -rf /tmp/metro-*
[16:51:01]    9 |
[16:51:01]   10 | import { NavigationContainer, StackActions } from '@react-navigation/native';
[16:51:01] > 11 | import { createStackNavigator } from '@react-navigation/stack';
[16:51:01]      |                                       ^
[16:51:01]   12 | import { Text } from './components/Themed';
[16:51:01]   13 | import { StackNavigationState, StackRouter } from '@react-navigation/routers';

### Expected behavior

react-navigation/stack is present

### Reproduction

https://github.com/abhitheawesomecoder/is_hr.git

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [X] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject",
    "test": "jest --watchAll"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@expo-google-fonts/inter": "^0.2.0",
    "@expo-google-fonts/montserrat": "^0.2.0",
    "@expo/vector-icons": "^12.0.0",
    "@react-navigation/bottom-tabs": "^6.0.5",
    "@react-navigation/native": "^6.0.4",
    "@react-navigation/native-stack": "^6.1.0",
    "expo": "~42.0.1",
    "expo-asset": "~8.3.2",
    "expo-constants": "~11.0.1",
    "expo-font": "~9.2.1",
    "expo-linking": "~2.3.1",
    "expo-splash-screen": "~0.11.2",
    "expo-status-bar": "~1.0.4",
    "expo-web-browser": "~9.2.0",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz",
    "react-native-gesture-handler": "~1.10.2",
    "react-native-reanimated": "~2.2.0",
    "react-native-safe-area-context": "^3.2.0",
    "react-native-screens": "^3.4.0",
    "react-native-web": "~0.13.12",
    "expo-av": "~9.2.3",
    "expo-camera": "~11.2.2",
    "@use-expo/font": "^2.0.0",
    "expo-file-system": "~11.1.3"
  },
  "devDependencies": {
    "@babel/core": "^7.9.0",
    "@types/react": "~16.9.35",
    "@types/react-native": "~0.63.2",
    "jest-expo": "~41.0.0-beta.0",
    "typescript": "~4.0.0"
  },
  "private": true
}

**Comment by abhitheawesomecoder** [comment]
"@react-navigation/bottom-tabs": "^6.0.5",
"@react-navigation/native-stack": "^6.1.0",

**Comment by raajnadar** [comment]
Did you try this https://reactnavigation.org/docs/troubleshooting/#im-getting-an-error-unable-to-resolve-module-after-updating-to-the-latest-version

The above docs should solve the issue, check and let us know if not solved.

**Comment by elijahkinyamal** [comment]
Cannot find module '@react-navigation/native-stack' or its corresponding type declarations.

**Comment by elijahkinyamal** [comment]
help me solve this "Cannot find module '@react-navigation/native-stack' or its corresponding type declarations."

**Comment by bawantha** [comment]
js frameworks are sh*ts as always
