### ISSUE TITLE
ScreenStack only accepts children of type Screen error

### ISSUE THREAD

**Issue by DeVontae316** [react-navigation/react-navigation#9979]
### Current behavior

I copy and paste the code from your docs concerning stack navigation
and I receive error:
"ScreenStack only accepts children of type Screen error"

![Screen Shot 2021-09-28 at 9 46 42 AM](https://user-images.githubusercontent.com/18466925/135110700-1dd0c5eb-170b-40cc-8d66-25cf452ba1a4.png)
 
### Expected behavior

I expected to see a simple stack navigator from your docs!

### Reproduction

https://github.com/DeVontae316/React-Native-Tutorial

### Platform

- [ ] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [X] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native "^6.0.4"              |

| @react-navigation/native-stack "^6.2.2"        |
| react-native-safe-area-context   "3.1.9"      |
| react-native-screens   "~2.15.2"                |
| react-native "https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz"                     |
| expo  "~40.0.0"                                 |
| node    v12.14.1                               |
| npm                          |

**Comment by DeVontae316** [comment]
"@react-navigation/native": "^6.0.4",
    "@react-navigation/native-stack": "^6.2.2",
    "expo": "~40.0.0",
    "expo-status-bar": "~1.0.3",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz",
    "react-native-safe-area-context": "3.1.9",
    "react-native-screens": "~2.15.2",

**Comment by aadityapaliwal94** [comment]
Same happening with me as well if I run the code with only one screen. Though I am using all the latest libraries and RN version

> "@react-navigation/drawer": "^6.5.0",
    "@react-navigation/native": "^6.0.13",
    "@react-navigation/native-stack": "^6.9.0",
    "react": "18.0.0",
    "react-native": "0.69.0",

**Comment by iMonk777** [comment]
> Same happening with me as well if I run the code with only one screen. Though I am using all the latest libraries and RN version
> 
> > "@react-navigation/drawer": "^6.5.0",
> > "@react-navigation/native": "^6.0.13",
> > "@react-navigation/native-stack": "^6.9.0",
> > "react": "18.0.0",
> > "react-native": "0.69.0",

Hi @aadityapaliwal94 , did you manage to fix the issue? I'm experiencing this by just having one screen inside the navigator. 
I'm on the latest versions of navigation

**Comment by mharrisweb** [comment]
If your using `react-native-screens`, the screens need enabling. 
```

`import { enableScreens } from 'react-native-screens';`

enableScreens();`

```
From https://www.npmjs.com/package/react-native-screens/v/2.18.1

The react Navigation docs for getting started doesn't mention this, which is confusing

**Comment by diegomichell** [comment]
> If your using `react-native-screens`, the screens need enabling.
> 
> ```
> 
> `import { enableScreens } from 'react-native-screens';`
> 
> enableScreens();`
> ```
> 
> From https://www.npmjs.com/package/react-native-screens/v/2.18.1
> 
> The React Navigation docs for getting started doesn't mention this, which is confusing

Exactly, just as you mentioned, this worked.

**Comment by detrujamilan** [comment]
Layout children must be of type Screen, all other children are ignored. To use custom children, create a custom <Layout />.
