### ISSUE TITLE
requireNativeComponent: "RNSScreenStackHeaderConfig" was not found in the UIManager 

### ISSUE THREAD

**Issue by Karthik-V26** [react-navigation/react-navigation#9981]
### Current behavior

Giving this error while running in Android previously it also happened in ios but fixed automatically. I followed exact installation process as given in Documentation

### Expected behavior

Run properly in android 

### Reproduction

-

### Platform

- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |
| @react-navigation/bottom-tabs          |
| @react-navigation/drawer               |
| @react-navigation/material-bottom-tabs |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                |
| @react-navigation/native-stack         |
| react-native-safe-area-context         |
| react-native-screens                   |
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           |
| node                                   |
| npm or yarn                            |

**Comment by codemang** [comment]
I'm also getting this error after trying multiple times to clear all build/cache data and reinstall.

**Comment by alonsovb** [comment]
> I'm getting this same error when trying to run the app in a [Nx monorepo](https://nx.dev/).

have you found any solution? I'm also having this issue under an nx monorepo.

**Comment by alonsovb** [comment]
> I'm getting this same error when trying to run the app in a [Nx monorepo](https://nx.dev/).

@stevenbdf have you found any solution? I'm also having this issue under an nx monorepo.

**Comment by HarvWorks** [comment]
Just for posterity sake, here is a link to a solution that works:
https://stackoverflow.com/a/67956805

**Comment by jgf5013** [comment]
@stevenbdf and @alonsovb, I'm also getting this issue in an Nx monorepo for both `nx run-android {app-name}` and `nx run-ios {app-name}`.
The issue seems to be [here](https://github.com/react-navigation/react-navigation/blob/main/packages/native-stack/src/views/HeaderConfig.tsx#L131). Interestingly I don't see any references to `RNSScreenStackHeaderConfig` anywhere in the `react-navigation` library.

@HarvWorks , the solution you linked to suggests the issue can be fixed by modifying the ios `Podfile` but I think something else might be going on for those of us experiencing the issue while running from Nx monorepo (as I'm getting the issue in both android and ios.) Am I right in thinking this issue is probably more for Nx than it is for react-navigation?

Note: I'm fairly new to React Native so apologies if I'm missing something obvious here.

**Comment by Ayzekberk** [comment]
try 
```
cd ios
pod-install 
```

than run app

**Comment by pnadj** [comment]
> try
> 
> ```
> cd ios
> pod-install 
> ```
> 
> than run app

Happening on android too

**Comment by InvestoAnil** [comment]
not found any solution

**Comment by uniquejava** [comment]
I fixed it! The following is what I did.

I created a brand new rn typescript project and followed the official rnn tutorial, I tested on both on the emulator/simulator and my android device.

- the getting started doc worked perfectly.
- then the 2nd one "Hello React navigation" worked perfectly on simulator.

However, the "Hello React navigation" tutorial not work on my android device(I was debugging over wifi), the screen shows me the error message which I googled and guided me here.

I read the posts here, and tried`yarn add react-native-gesture-handler`,  but it didn't work for me! 

And so I `yarn remove react-native-gesture-handler`.

I decided to uninstall the hello world app from my android device.

I then connected my device via USB,  and run `yarn android` again,  wow this time it worked perfectly!

**Comment by alitokmakci** [comment]
1 - Close the metro bundler.
2- `npx pod-install ios` run this on project folder.
3- `yarn ios`

worked fine for me. Good luck!

**Comment by Jahanzaib320** [comment]
> I got the same issue when running a barebones app with react-native and expo. I solved it by adding these packages to the project package.json
> 
> ```
> "react-native-screens": "*",
> "react-native-gesture-handler": "*",
> "react-native-safe-area-context": "*"
> ```
> 
> Please check [nrwl/nx-react-native#98](https://github.com/nrwl/nx-react-native/issues/98)

This Works

**Comment by lp4298707** [comment]
I resolve this problem by:

First stop the metro

Delete the "node_modules" folder

Run below commands respectively

npm install, npx react-native start, npx react-native run-ios

**Comment by EUGinsane** [comment]
> I resolve this problem by:
> 
> First stop the metro
> 
> Delete the "node_modules" folder
> 
> Run below commands respectively
> 
> npm install, npx react-native start, npx react-native run-ios
> 
> maybe Delete the "node_modules" folder is not necessary, just run npx react-native run-ios

this is the solution

**Comment by Rustamyan94** [comment]
1. Remove the app from the simulator.
2. run `npx react-native run-ios`
3. And enjoy life)

**Comment by bjin9** [comment]
I tried all of the above solutions, but they didn't work.
Finally I found I missed the ios configuration for react-native-screens package.
After that, it worked well.

Here is a detailed answer.
https://stackoverflow.com/a/74309344/12858250

**Comment by vishalg2235** [comment]
> I got the same issue when running a barebones app with react-native and expo. I solved it by adding these packages to the project package.json
> 
> ```
> "react-native-screens": "*",
> "react-native-gesture-handler": "*",
> "react-native-safe-area-context": "*"
> ```
> 
> Please check [nrwl/nx-react-native#98](https://github.com/nrwl/nx-react-native/issues/98)

After this then I did `pod install`. It worked 👯‍♂️

**Comment by sitehakim1992** [comment]
> I resolve this problem by:
> 
> First stop the metro
> 
> Delete the "node_modules" folder
> 
> Run below commands respectively
> 
> npm install, npx react-native start, npx react-native run-ios
> 
> maybe Delete the "node_modules" folder is not necessary, just run npx react-native run-ios

not work for me

**Comment by Frtn0717** [comment]
> I fixed it! The following is what I did.
> 
> I created a brand new rn typescript project and followed the official rnn tutorial, I tested on both the emulator/simulator and my android device.
> 
> * the getting started doc worked perfectly.
> * then the 2nd one "Hello React navigation" worked perfectly on simulator.
> 
> However, the "Hello React navigation" tutorial not work on my android device(I was debugging over wifi), the screen shows me the error message which I googled and guided me here.
> 
> I read the posts here, and tried`yarn add react-native-gesture-handler`, but it didn't work for me!
> 
> And so I `yarn remove react-native-gesture-handler`.
> 
> I decided to uninstall the hello world app from my android device.
> 
> I then connected my device via USB, and run `yarn android` again, wow this time it worked perfectly!

@uniquejava, thanks, it works for me
It looks like reinstalling the app from your device is mandatory

**Comment by Antsthebul** [comment]
> > I fixed it! The following is what I did.
> > I created a brand new rn typescript project and followed the official rnn tutorial, I tested on both the emulator/simulator and my android device.
> > 
> > * the getting started doc worked perfectly.
> > * then the 2nd one "Hello React navigation" worked perfectly on simulator.
> > 
> > However, the "Hello React navigation" tutorial not work on my android device(I was debugging over wifi), the screen shows me the error message which I googled and guided me here.
> > I read the posts here, and tried`yarn add react-native-gesture-handler`, but it didn't work for me!
> > And so I `yarn remove react-native-gesture-handler`.
> > I decided to uninstall the hello world app from my android device.
> > I then connected my device via USB, and run `yarn android` again, wow this time it worked perfectly!
> 
> @uniquejava, thanks, it works for me It looks like reinstalling the app from your device is mandatory

Agreed, Thanks!. Im testing on iOS and using bare React-Native project. Simply removing the app and re install worked!

Steps beforehand (which might be unessary):
1. Remove node_moduels and re install
2. cd into /ios and run `pod install`
