### ISSUE TITLE
NativeStackScreenProps don't return type for navigation.navigate [v6]

### ISSUE THREAD

**Issue by BrotskyS** [react-navigation/react-navigation#9986]
### Current behavior

export type RootStackParamList = {
  Main: any;
  BottomSheet1: any;
  BottomSheet2: any;
};

export const Screen = ({
  route,
  navigation,
}: NativeStackScreenProps<RootStackParamList, 'Main'>): JSX.Element => {
  const onPress = () => {
    navigation.navigate('BottomSheet');
  };
return(
...
)
}

![image](https://user-images.githubusercontent.com/49614370/135339930-c2304a5e-8064-4faa-9655-65acf57debfb.png)

"@react-navigation/bottom-tabs": "^6.0.5",
"@react-navigation/native": "^6.0.2",
"@react-navigation/native-stack": "^6.2.2",

When i was to navigate i saw this

![image](https://user-images.githubusercontent.com/49614370/135340375-4266dbf8-ee88-430b-8e5d-eed27ab60606.png)

and if i wrote this everything work fine
![image](https://user-images.githubusercontent.com/49614370/135340286-7375cb6a-4268-4b65-88fd-2b8f0515beb9.png)

![image](https://user-images.githubusercontent.com/49614370/135340670-0c30d694-7ef2-414a-a840-ae2c18584a92.png)

### Expected behavior

No type error

### Reproduction

https://snack.expo.dev/jp-w5V5qj

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |
| @react-navigation/bottom-tabs          |
| @react-navigation/drawer               |
| @react-navigation/material-bottom-tabs |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                |
| @react-navigation/native-stack         |
| react-native-safe-area-context         |
| react-native-screens                   |
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           |
| expo                                   |
| node                                   |
| npm or yarn                            |

**Comment by loveguo227** [comment]
> Updated the typescript version)
Have you solved this problem？

**Comment by ericleb010** [comment]
If anyone else is stuck on this, I updated the Typescript version my workspace is using and that got me through the issue.
