### ISSUE TITLE
"TypeError: undefined is not an object (evaluating '_$$_REQUIRE(_dependencyMap[6], "@react-navigation/elements").ResourceSavingView')"

### ISSUE THREAD

**Issue by krishna-6** [react-navigation/react-navigation#9995]
### Current behavior

I'm using react-navigation 6.x.
Following are the versions:
"@react-navigation/bottom-tabs": "^6.0.4",
"@react-navigation/native": "^6.0.4",
"@react-navigation/stack": "^6.0.9"

The stack navigation is working fine, but when using bottom-tabs I'm getting the following error:
"TypeError: undefined is not an object (evaluating '_$$_REQUIRE(_dependencyMap[6], "@react-navigation/elements").ResourceSavingView')"

### Expected behavior

It should work fine.

### Reproduction

Create a new bare react-native project with react-native 0.65.1
Install react-navigation 
create basic navigation using  createBottomTabNavigator
It will crash

### Platform

- [ ] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |
| @react-navigation/bottom-tabs          |
| @react-navigation/drawer               |
| @react-navigation/material-bottom-tabs |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                |
| @react-navigation/native-stack         |
| react-native-safe-area-context         |
| react-native-screens                   |
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native-tab-view                  |
| react-native-pager-view                |
| react-native                           |
| expo                                   |
| node                                   |
| npm or yarn                            |

**Comment by mariovillamizar** [comment]
@krishna-6 were you able to fix it? I'm having the same issue.

This is my environment:
"@react-navigation/drawer": "^6.1.6",
"@react-navigation/native": "^6.0.4",
"@react-navigation/stack": "^6.0.9",
"react-native-safe-area-context": "^3.3.2"
"react-native-screens": "^3.8.0"
"react-native": "0.64.2"
"typescript": "^4.0.3"
"node": "14.16.1"
"npm": "6.14.12"

![Simulator Screen Shot - iPhone 12 - 2021-10-01 at 15 02 39](https://user-images.githubusercontent.com/10704258/135679792-fc85108e-ef05-4c18-aacf-b69467a0f22a.png)
.

**Comment by cesc993** [comment]
Hello,
I had the same issue, in my case it got fixed when i reinstalled yarn packages by first removing them. And after that i did "pod deintegrate" and "pod install". Hope it can be helpful

**Comment by Davete0302** [comment]
Were you able to solve this? got the same problem.
 "@react-navigation/native": "^6.0.4",
"@react-navigation/native-stack": "^6.2.2",
"@react-navigation/bottom-tabs": "^6.0.7",

**Comment by GMH501** [comment]
solved installing `react-native-screens` => `yarn add react-native-screens`

**Comment by BilalHashmi94** [comment]
I had same issue and just fixed after installing react-native-screens

yarn add react-native-screens
or

npm install react-native-screens

**Comment by AkshayPatel7000** [comment]
> yarn add react-native-screens

still not working

**Comment by AkshayPatel7000** [comment]
> > yarn add react-native-screens
> 
> still not working

nhi  chal raha bhai dimag kharab ho rha h

**Comment by AkshayPatel7000** [comment]
![Screenshot 2022-03-02 at 4 23 01 PM](https://user-images.githubusercontent.com/91655605/156348442-c316fbf4-fa27-4243-a30d-d4a6b2818c54.png)

**Comment by AkshayPatel7000** [comment]
![Screenshot 2022-03-02 at 4 24 53 PM](https://user-images.githubusercontent.com/91655605/156348710-225070e1-bc16-461f-aca0-8a0d12a6a56f.png)
 added yarn add react-native-screens to the project but still getting the error

**Comment by deividgouveia** [comment]
TypeError: undefined is not an object (evaluating 'InnerNativeModule.installCoreFunctions'). React Navigation Drawer

**Comment by wltdev** [comment]
@deividgouveia I had the same error

**Comment by prasanthmurugasamy** [comment]
I too have the same error!!AnySolutions

**Comment by sauravptg** [comment]
i have the same error 

    "@react-navigation/bottom-tabs": "^6.2.0",
    "@react-navigation/drawer": "^6.3.1",
    "@react-navigation/native": "^6.0.8",
    "@react-navigation/native-stack": "^6.5.0",
    "@react-navigation/stack": "^6.1.1", 
    "react": "17.0.2",
    "react-native": "0.67.2"
<img width="398" alt="Screenshot 2022-03-13 at 12 45 32 AM" src="https://user-images.githubusercontent.com/100139977/158031784-52b1849c-5fb9-4858-86f6-053fcae24004.png">
,

**Comment by raajnadar** [comment]
You people derailed the main issue, check the OPs error and your error they are different.

Tips to solve this issue try this steps -

1) Clear the yarn or metro cache.
2) Remove the yarn.lock or pod.lock and reinstall it.
3) Clear the node modules and reinstall
4) Check for package dependency versions, expo managed can use `expo upgrade` to solve the issue.

**Comment by SharvanTech5** [comment]
i Have also save issue with react native drawer

    "@react-native-masked-view/masked-view": "^0.2.6",
    "@react-navigation/bottom-tabs": "^6.2.0",
    "@react-navigation/drawer": "^6.3.1",
    "@react-navigation/native": "^6.0.8",
    "@react-navigation/native-stack": "^6.5.0",
    "@react-navigation/stack": "^6.1.1",
    "react-native-reanimated": "^2.4.1",

**Comment by cyberdanes** [comment]
I am getting an error when using Drawer Navigator.

 ERROR  TypeError: undefined is not an object (evaluating '_$$_REQUIRE(_dependencyMap[3], "@react-navigation/drawer").createDrawerNavigator')

This error is located at:
    in DrawerNavigator (at navigations/index.js:22)
    in EnsureSingleNavigator (at BaseNavigationContainer.tsx:430)
    in BaseNavigationContainer (at NavigationContainer.tsx:132)
    in ThemeProvider (at NavigationContainer.tsx:131)
    in NavigationContainerInner (at navigations/index.js:19)
    in AppNavContainer (at App.js:50)
    in App (at renderApplication.js:50)
    in RCTView (at View.js:32)
    in View (at AppContainer.js:92)
    in RCTView (at View.js:32)
    in View (at AppContainer.js:119)
    in AppContainer (at renderApplication.js:43)

Versions:
├── @babel/core@7.17.5
├── @babel/runtime@7.17.2
├── @react-native-community/eslint-config@2.0.0
├── @react-navigation/drawer@6.3.1
├── @react-navigation/native@6.0.8
├── @react-navigation/stack@6.1.1
├── babel-jest@26.6.3
├── eslint@7.14.0
├── jest@26.6.3
├── metro-react-native-babel-preset@0.66.2
├── react-native-gesture-handler@2.3.1
├── react-native-reanimated@2.4.1
├── react-native-safe-area-context@4.1.2
├── react-native-screens@3.13.1
├── react-native@0.67.3
├── react-test-renderer@17.0.2
└── react@17.0.2

**Comment by jlsodai** [comment]
Here's how to resolve the issue without the need to deintegrate, uninstall, or install packages. The reason you are seeing this error is because **"An ordinary component that is not a screen component will not receive the navigation prop automatically."**

If you want to access the navigation from a component, you have two options:

**1.** Pass `navigation` down from a screen component for example HomeScreen directly to a child component; Card Component in this example.

```
const HomeScreen = ({ navigation }) => {
   return (
      <SafeAreaView>
         <GoToButton navigation={navigation} />
      </SafeAreaView>
   );
};
```

**2.** Use the `useNavigation()` hook to get access to the navigation object from any component.

```
import * as React from 'react';
import { Button } from 'react-native';
import { useNavigation } from '@react-navigation/native';

function GoToButton({ screenName }) {
  const navigation = useNavigation();

  return (
    <Button
      title={`Go to ${screenName}`}
      onPress={() => navigation.navigate(screenName)}
    />
  );
}
```

**Reference**: [https://reactnavigation.org/docs/connecting-navigation-prop/](https://reactnavigation.org/docs/connecting-navigation-prop/)

I hope this helps.

**Comment by radixxko** [comment]
Dont forget to install

`npm install react-native-gesture-handler react-native-reanimated`

and then place the 

`import 'react-native-gesture-handler';`

at the beginning of `index.js` or `App.js`

**Comment by souvik666** [comment]
**I was facing the same issue  on this versions**

```
    "@react-navigation/native": "^6.0.13",
    "@react-navigation/native-stack": "^6.9.1",
```

**After downgrading them into this versions the issue got resolved**  

```
    "@react-navigation/native": "^5.0.0",
    "@react-navigation/native-stack": "^5.0.0",
```

**Comment by raajnadar** [comment]
@souvik666 downgrade is not a solution it is a workaround

**Comment by souvik666** [comment]
@raajnadar yep you can say that at least now the app is building

**Comment by NhutMinhIT** [comment]
![image](https://user-images.githubusercontent.com/90835621/221353276-cfb31f94-79b4-47b8-98cd-903fb1e1ac6b.png)

**Comment by amitfleek01** [comment]
"@react-native-masked-view/masked-view": "^0.2.8",
    "@react-navigation/bottom-tabs": "^6.5.20",
    "@react-navigation/drawer": "^6.6.11",
    "@react-navigation/native": "^6.1.14",
    "@react-navigation/native-stack": "^6.9.22",
    "@react-navigation/stack": "^6.3.25",
    
    this is my navigation packages, it's working fine for android but throwing issue in ios
    
    
![Simulator Screenshot - iPhone 6s Plus - 2024-05-02 at 19 20 44](https://github.com/react-navigation/react-navigation/assets/122983425/3256ba66-1cb9-4430-9535-f88e4d67268d)
![Simulator Screenshot - iPhone 6s Plus - 2024-05-02 at 19 20 48](https://github.com/react-navigation/react-navigation/assets/122983425/6a93fa28-7ff3-4a02-9b8c-7dd2a84bf73b)

**Comment by ripon008** [comment]
> Were you able to solve this? got the same problem. "@react-navigation/native": "^6.0.4", "@react-navigation/native-stack": "^6.2.2", "@react-navigation/bottom-tabs": "^6.0.7",

thank you ...its working
