### ISSUE TITLE
Back navigation support in android with Reanimated 2

### ISSUE THREAD

**Issue by rana944** [react-navigation/react-navigation#9999]
### Current behavior

First of all I would like to thank you for such a wonderful package, but I am facing some weird issue once I configured react-native-reanimated 2.

After installing the reanimated 2 package, the @react-navigation/native-stack is creating some serious issues with back navigation.

Everything seems to work fine with iOS but on android, things are broken.

For demonstration of the issue. Let's say I have screens A & B.
When I move from A to B. the navigation works and it moves to screen B.
But, apparently when I navigate back from screen B to screen A, a white black screen appears.

I have tried this using the default navigation back button. and realized that after pressing the back button from screen B, the navigation jumps back to screen A, and then apparently jumps again to screen B which is not supposed to be the behavior.

### Expected behavior

Expected behavior should be when I go back from screen B to screen A, the white screen should not get appear and the previous screen (A) should appear which is in the navigation stack.

### Reproduction

https://github.com/rana944/React-Navigation-Reanimated.git

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.0.4
| @react-navigation/bottom-tabs          | 6.0.7
| @react-navigation/drawer               | 6.1.6
| @react-navigation/stack                | 6.0.9
| @react-navigation/native-stack         | 6.2.2
| react-native-safe-area-context         | 3.3.2
| react-native-screens                   | 3.8.0
| react-native-gesture-handler           | 1.10.3
| react-native-reanimated                | 2.3.0-beta.1
| react-native                           | 0.65.1
| node                                   | 16.8.0
| npm or yarn                            | 1.22.11
| @react-navigation/material-bottom-tabs | 6.0.7
| @react-navigation/material-top-tabs | 6.0.4

**Comment by Japjappedulap** [comment]
I'm using reanimated 2.3.0-beta.2 and this is what I'm getting when using the native-stack on android. iOS works fine

https://user-images.githubusercontent.com/34290379/135936173-02830463-a7bb-4dbe-ad35-324951a0308f.mov

**Comment by Japjappedulap** [comment]
I'm guessing this is the issue 
https://github.com/software-mansion/react-native-reanimated/issues/2460

**Comment by radko93** [comment]
Try using reanimated 2.2.2 and it should work. Not ideal.

**Comment by rana944** [comment]
its fixed now, thanks
